FFmpeg: libavcodec/aacadtsdec.h File Reference
aacadtsdec.h File Reference
#include <stdint.h>
#include "get_bits.h"
Data Structures
struct AACADTSHeaderInfo
Macros
#define AAC_ADTS_HEADER_SIZE 7
Functions
int avpriv_aac_parse_header (GetBitContext *gbc, AACADTSHeaderInfo *hdr)
Parse AAC frame header.
Macro Definition Documentation
AAC_ADTS_HEADER_SIZE
#define AAC_ADTS_HEADER_SIZE 7
Definition at line 29 of file aacadtsdec.h.
Referenced by aac_adtstoasc_filter(), aac_parse_init(), aac_sync(), avpriv_aac_parse_header(), ff_spdif_probe(), spdif_get_offset_and_codec(), and spdif_header_aac().
Function Documentation
avpriv_aac_parse_header()
int avpriv_aac_parse_header (GetBitContext * gbc, AACADTSHeaderInfo * hdr)
Parse AAC frame header.
Parse the ADTS frame header to the end of the variable header, which is the first 54 bits.
Parameters
[in] gbc BitContext containing the first 54 bits of the frame.
[out] hdr Pointer to struct where header info is written.
Returns
Returns 0 on success, -1 if there is a sync word mismatch, -2 if the version element is invalid, -3 if the sample rate element is invalid, or -4 if the bit rate element is invalid.
Definition at line 29 of file aacadtsdec.c.
Referenced by aac_adtstoasc_filter(), aac_sync(), parse_adts_frame_header(), spdif_get_offset_and_codec(), and spdif_header_aac().