FFmpeg: libavcodec/aacdec_fixed.c File Reference
aacdec_fixed.c File Reference
AAC decoder.
#include "libavutil/fixed_dsp.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "internal.h"
#include "get_bits.h"
#include "fft.h"
#include "lpc.h"
#include "kbdwin.h"
#include "sinewin.h"
#include "aac.h"
#include "aactab.h"
#include "aacdectab.h"
#include "cbrt_data.h"
#include "sbr.h"
#include "aacsbr.h"
#include "mpeg4audio.h"
#include "aacadtsdec.h"
#include "profiles.h"
#include "libavutil/intfloat.h"
#include <math.h>
#include <string.h>
#include "aacdec_template.c"
Macros
#define FFT_FLOAT 0
#define FFT_FIXED_32 1
#define USE_FIXED 1
Functions
static av_always_inline void reset_predict_state (PredictorState *ps)
static int * DEC_SPAIR (int *dst, unsigned idx)
static int * DEC_SQUAD (int *dst, unsigned idx)
static int * DEC_UPAIR (int *dst, unsigned idx, unsigned sign)
static int * DEC_UQUAD (int *dst, unsigned idx, unsigned sign)
static void vector_pow43 (int *coefs, int len)
static void subband_scale (int *dst, int *src, int scale, int offset, int len)
static void noise_scale (int *coefs, int scale, int band_energy, int len)
static av_always_inline SoftFloat flt16_round (SoftFloat pf)
static av_always_inline SoftFloat flt16_even (SoftFloat pf)
static av_always_inline SoftFloat flt16_trunc (SoftFloat pf)
static av_always_inline void predict (PredictorState *ps, int *coef, int output_enable)
static void apply_dependent_coupling_fixed (AACContext *ac, SingleChannelElement *target, ChannelElement *cce, int index)
Apply dependent channel coupling (applied before IMDCT).
static void apply_independent_coupling_fixed (AACContext *ac, SingleChannelElement *target, ChannelElement *cce, int index)
Apply independent channel coupling (applied after IMDCT).
Variables
static const int exp2tab [4] = { Q31(1.0000000000/2), Q31(1.1892071150/2), Q31(1.4142135624/2), Q31(1.6817928305/2) }
static const int cce_scale_fixed [8]
AVCodec ff_aac_fixed_decoder
Detailed Description
AAC decoder.
Author
Oded Shimon (ods15 ods15 dyndns org)
Maxim Gavrilov (maxim.gavrilov gmail com)
Fixed point implementation
Author
Stanislav Ocovaj (stanislav.ocovaj imgtec com)
Definition in file aacdec_fixed.c.
Macro Definition Documentation
FFT_FLOAT
#define FFT_FLOAT 0
Definition at line 61 of file aacdec_fixed.c.
FFT_FIXED_32
#define FFT_FIXED_32 1
Definition at line 62 of file aacdec_fixed.c.
USE_FIXED
#define USE_FIXED 1
Definition at line 63 of file aacdec_fixed.c.
Function Documentation
reset_predict_state()
static av_always_inline void reset_predict_state (PredictorState * ps) static
Definition at line 89 of file aacdec_fixed.c.
DEC_SPAIR()
static int* DEC_SPAIR (int * dst, unsigned idx) inline static
Definition at line 107 of file aacdec_fixed.c.
Referenced by decode_spectrum_and_dequant().
DEC_SQUAD()
static int* DEC_SQUAD (int * dst, unsigned idx) inline static
Definition at line 115 of file aacdec_fixed.c.
Referenced by decode_spectrum_and_dequant().
DEC_UPAIR()
static int* DEC_UPAIR (int * dst, unsigned idx, unsigned sign) inline static
Definition at line 125 of file aacdec_fixed.c.
Referenced by decode_spectrum_and_dequant().
DEC_UQUAD()
static int* DEC_UQUAD (int * dst, unsigned idx, unsigned sign) inline static
Definition at line 133 of file aacdec_fixed.c.
Referenced by decode_spectrum_and_dequant().
vector_pow43()
static void vector_pow43 (int * coefs, int len) static
Definition at line 151 of file aacdec_fixed.c.
Referenced by aacdec_init().
subband_scale()
static void subband_scale (int * dst, int * src, int scale, int offset, int len) static
Definition at line 165 of file aacdec_fixed.c.
Referenced by aacdec_init().
noise_scale()
static void noise_scale (int * coefs, int scale, int band_energy, int len) static
Definition at line 191 of file aacdec_fixed.c.
Referenced by decode_spectrum_and_dequant().
flt16_round()
static av_always_inline SoftFloat flt16_round (SoftFloat pf) static
Definition at line 223 of file aacdec_fixed.c.
Referenced by predict().
flt16_even()
static av_always_inline SoftFloat flt16_even (SoftFloat pf) static
Definition at line 237 of file aacdec_fixed.c.
Referenced by predict().
flt16_trunc()
static av_always_inline SoftFloat flt16_trunc (SoftFloat pf) static
Definition at line 251 of file aacdec_fixed.c.
Referenced by predict().
predict()
static av_always_inline void predict (PredictorState * ps, int * coef, int output_enable) static
Definition at line 265 of file aacdec_fixed.c.
apply_dependent_coupling_fixed()
static void apply_dependent_coupling_fixed (AACContext * ac, SingleChannelElement * target, ChannelElement * cce, int index) static
Apply dependent channel coupling (applied before IMDCT).
Parameters
index index into coupling gain array
Definition at line 336 of file aacdec_fixed.c.
apply_independent_coupling_fixed()
static void apply_independent_coupling_fixed (AACContext * ac, SingleChannelElement * target, ChannelElement * cce, int index) static
Apply independent channel coupling (applied after IMDCT).
Parameters
index index into coupling gain array
Definition at line 398 of file aacdec_fixed.c.
Variable Documentation
exp2tab
const int exp2tab[4] = { Q31(1.0000000000/2), Q31(1.1892071150/2), Q31(1.4142135624/2), Q31(1.6817928305/2) } static
Definition at line 105 of file aacdec_fixed.c.
Referenced by noise_scale(), and subband_scale().
cce_scale_fixed
const int cce_scale_fixed[8] static
Initial value:
= {
    Q30(1.0),
    Q30(1.0905077327),
    Q30(1.1892071150),
    Q30(1.2968395547),
    Q30(1.4142135624),
    Q30(1.5422108254),
    Q30(1.6817928305),
    Q30(1.8340080864),
}
Definition at line 320 of file aacdec_fixed.c.
Referenced by apply_dependent_coupling_fixed(), and apply_independent_coupling_fixed().
ff_aac_fixed_decoder
AVCodec ff_aac_fixed_decoder
Initial value:
= {
    .name            = "aac_fixed",
    .long_name       = NULL_IF_CONFIG_SMALL("AAC (Advanced Audio Coding)"),
    .type            = AVMEDIA_TYPE_AUDIO,
    .id              = AV_CODEC_ID_AAC,
    .priv_data_size  = sizeof(AACContext),
    .init            = aac_decode_init,
    .close           = aac_decode_close,
    .decode          = aac_decode_frame,
    .sample_fmts     = (const enum AVSampleFormat[]) {
        AV_SAMPLE_FMT_S32P, AV_SAMPLE_FMT_NONE
    },
    .capabilities    = AV_CODEC_CAP_CHANNEL_CONF | AV_CODEC_CAP_DR1,
    .caps_internal   = FF_CODEC_CAP_INIT_THREADSAFE,
    .channel_layouts = aac_channel_layout,
    .profiles        = NULL_IF_CONFIG_SMALL(ff_aac_profiles),
    .flush = flush,
}
Definition at line 429 of file aacdec_fixed.c.