FFmpeg: libavcodec/aacdec_template.c File Reference
aacdec_template.c File Reference
AAC decoder.
#include "libavutil/thread.h"
Data Structures
struct elem_to_channel
Macros
#define overread_err "Input buffer exhausted before END element found\n"
#define AAC_INIT_VLC_STATIC(num, size)
#define AACDEC_FLAGS AV_OPT_FLAG_DECODING_PARAM | AV_OPT_FLAG_AUDIO_PARAM
AVOptions for Japanese DTV specific extensions (ADTS only)
Functions
static int output_configure (AACContext *ac, uint8_t layout_map[MAX_ELEM_ID *4][3], int tags, enum OCStatus oc_type, int get_new_frame)
Configure output channel order based on the current program configuration element.
static int count_channels (uint8_t(*layout)[3], int tags)
static av_cold int che_configure (AACContext *ac, enum ChannelPosition che_pos, int type, int id, int *channels)
Check for the channel element in the current channel position configuration.
static int frame_configure_elements (AVCodecContext *avctx)
static int assign_pair (struct elem_to_channel e2c_vec[MAX_ELEM_ID], uint8_t(*layout_map)[3], int offset, uint64_t left, uint64_t right, int pos)
static int count_paired_channels (uint8_t(*layout_map)[3], int tags, int pos, int *current)
static uint64_t sniff_channel_order (uint8_t(*layout_map)[3], int tags)
static void push_output_configuration (AACContext *ac)
Save current output configuration if and only if it has been locked.
static void pop_output_configuration (AACContext *ac)
Restore the previous output configuration if and only if the current configuration is unlocked.
static void flush (AVCodecContext *avctx)
static int set_default_channel_config (AVCodecContext *avctx, uint8_t(*layout_map)[3], int *tags, int channel_config)
Set up channel positions based on a default channel configuration as specified in table 1.17.
static ChannelElement * get_che (AACContext *ac, int type, int elem_id)
static void decode_channel_map (uint8_t layout_map[][3], enum ChannelPosition type, GetBitContext *gb, int n)
Decode an array of 4 bit element IDs, optionally interleaved with a stereo/mono switching bit.
static int decode_pce (AVCodecContext *avctx, MPEG4AudioConfig *m4ac, uint8_t(*layout_map)[3], GetBitContext *gb)
Decode program configuration element; reference: table 4.2.
static int decode_ga_specific_config (AACContext *ac, AVCodecContext *avctx, GetBitContext *gb, MPEG4AudioConfig *m4ac, int channel_config)
Decode GA "General Audio" specific configuration; reference: table 4.1.
static int decode_eld_specific_config (AACContext *ac, AVCodecContext *avctx, GetBitContext *gb, MPEG4AudioConfig *m4ac, int channel_config)
static int decode_audio_specific_config (AACContext *ac, AVCodecContext *avctx, MPEG4AudioConfig *m4ac, const uint8_t *data, int64_t bit_size, int sync_extension)
Decode audio specific configuration; reference: table 1.13.
static av_always_inline int lcg_random (unsigned previous_val)
linear congruential pseudorandom number generator
static void reset_all_predictors (PredictorState *ps)
static int sample_rate_idx (int rate)
static void reset_predictor_group (PredictorState *ps, int group_num)
static void aacdec_init (AACContext *ac)
static av_cold void aac_static_table_init (void)
static av_cold int aac_decode_init (AVCodecContext *avctx)
static int skip_data_stream_element (AACContext *ac, GetBitContext *gb)
Skip data_stream_element; reference: table 4.10.
static int decode_prediction (AACContext *ac, IndividualChannelStream *ics, GetBitContext *gb)
static void decode_ltp (LongTermPrediction *ltp, GetBitContext *gb, uint8_t max_sfb)
Decode Long Term Prediction data; reference: table 4.xx.
static int decode_ics_info (AACContext *ac, IndividualChannelStream *ics, GetBitContext *gb)
Decode Individual Channel Stream info; reference: table 4.6.
static int decode_band_types (AACContext *ac, enum BandType band_type[120], int band_type_run_end[120], GetBitContext *gb, IndividualChannelStream *ics)
Decode band types (section_data payload); reference: table 4.46.
static int decode_scalefactors (AACContext *ac, INTFLOAT sf[120], GetBitContext *gb, unsigned int global_gain, IndividualChannelStream *ics, enum BandType band_type[120], int band_type_run_end[120])
Decode scalefactors; reference: table 4.47.
static int decode_pulses (Pulse *pulse, GetBitContext *gb, const uint16_t *swb_offset, int num_swb)
Decode pulse data; reference: table 4.7.
static int decode_tns (AACContext *ac, TemporalNoiseShaping *tns, GetBitContext *gb, const IndividualChannelStream *ics)
Decode Temporal Noise Shaping data; reference: table 4.48.
static void decode_mid_side_stereo (ChannelElement *cpe, GetBitContext *gb, int ms_present)
Decode Mid/Side data; reference: table 4.54.
static int decode_spectrum_and_dequant (AACContext *ac, INTFLOAT coef[1024], GetBitContext *gb, const INTFLOAT sf[120], int pulse_present, const Pulse *pulse, const IndividualChannelStream *ics, enum BandType band_type[120])
Decode spectral data; reference: table 4.50.
static void apply_prediction (AACContext *ac, SingleChannelElement *sce)
Apply AAC-Main style frequency domain prediction.
static int decode_ics (AACContext *ac, SingleChannelElement *sce, GetBitContext *gb, int common_window, int scale_flag)
Decode an individual_channel_stream payload; reference: table 4.44.
static void apply_mid_side_stereo (AACContext *ac, ChannelElement *cpe)
Mid/Side stereo decoding; reference: 4.6.8.1.3.
static void apply_intensity_stereo (AACContext *ac, ChannelElement *cpe, int ms_present)
intensity stereo decoding; reference: 4.6.8.2.3
static int decode_cpe (AACContext *ac, GetBitContext *gb, ChannelElement *cpe)
Decode a channel_pair_element; reference: table 4.4.
static int decode_cce (AACContext *ac, GetBitContext *gb, ChannelElement *che)
Decode coupling_channel_element; reference: table 4.8.
static int decode_drc_channel_exclusions (DynamicRangeControl *che_drc, GetBitContext *gb)
Parse whether channels are to be excluded from Dynamic Range Compression; reference: table 4.53.
static int decode_dynamic_range (DynamicRangeControl *che_drc, GetBitContext *gb)
Decode dynamic range information; reference: table 4.52.
static int decode_fill (AACContext *ac, GetBitContext *gb, int len)
static int decode_extension_payload (AACContext *ac, GetBitContext *gb, int cnt, ChannelElement *che, enum RawDataBlockType elem_type)
Decode extension data (incomplete); reference: table 4.51.
static void apply_tns (INTFLOAT coef[1024], TemporalNoiseShaping *tns, IndividualChannelStream *ics, int decode)
Decode Temporal Noise Shaping filter coefficients and apply all-pole filters; reference: 4.6.9.3.
static void windowing_and_mdct_ltp (AACContext *ac, INTFLOAT *out, INTFLOAT *in, IndividualChannelStream *ics)
Apply windowing and MDCT to obtain the spectral coefficient from the predicted sample by LTP.
static void apply_ltp (AACContext *ac, SingleChannelElement *sce)
Apply the long term prediction.
static void update_ltp (AACContext *ac, SingleChannelElement *sce)
Update the LTP buffer for next frame.
static void imdct_and_windowing (AACContext *ac, SingleChannelElement *sce)
Conduct IMDCT and windowing.
static void imdct_and_windowing_ld (AACContext *ac, SingleChannelElement *sce)
static void imdct_and_windowing_eld (AACContext *ac, SingleChannelElement *sce)
static void apply_channel_coupling (AACContext *ac, ChannelElement *cc, enum RawDataBlockType type, int elem_id, enum CouplingPoint coupling_point, void(*apply_coupling_method)(AACContext *ac, SingleChannelElement *target, ChannelElement *cce, int index))
channel coupling transformation interface
static void spectral_to_sample (AACContext *ac, int samples)
Convert spectral data to samples, applying all supported tools as appropriate.
static int parse_adts_frame_header (AACContext *ac, GetBitContext *gb)
static int aac_decode_er_frame (AVCodecContext *avctx, void *data, int *got_frame_ptr, GetBitContext *gb)
static int aac_decode_frame_int (AVCodecContext *avctx, void *data, int *got_frame_ptr, GetBitContext *gb, AVPacket *avpkt)
static int aac_decode_frame (AVCodecContext *avctx, void *data, int *got_frame_ptr, AVPacket *avpkt)
static av_cold int aac_decode_close (AVCodecContext *avctx)
Variables
static VLC vlc_scalefactors
static VLC vlc_spectral [11]
static AVOnce aac_table_init = AV_ONCE_INIT
static const float cce_scale []
static const AVOption options []
static const AVClass aac_decoder_class
Detailed Description
AAC decoder.
Author
Oded Shimon (ods15 ods15 dyndns org)
Maxim Gavrilov (maxim.gavrilov gmail com)
AAC decoder fixed-point implementation
Author
Stanislav Ocovaj (stanislav.ocovaj imgtec com)
Nedeljko Babic (nedeljko.babic imgtec com)
Definition in file aacdec_template.c.
Macro Definition Documentation
overread_err
#define overread_err "Input buffer exhausted before END element found\n"
Definition at line 101 of file aacdec_template.c.
Referenced by aac_decode_frame_int(), decode_band_types(), decode_eld_specific_config(), decode_pce(), and skip_data_stream_element().
AAC_INIT_VLC_STATIC
#define AAC_INIT_VLC_STATIC (num, size)
Value:
INIT_VLC_STATIC(&vlc_spectral[num], 8, ff_aac_spectral_sizes[num],     \
         ff_aac_spectral_bits[num], sizeof(ff_aac_spectral_bits[num][0]),  \
                                    sizeof(ff_aac_spectral_bits[num][0]),  \
        ff_aac_spectral_codes[num], sizeof(ff_aac_spectral_codes[num][0]), \
                                    sizeof(ff_aac_spectral_codes[num][0]), \
        size);
Definition at line 1062 of file aacdec_template.c.
Referenced by aac_static_table_init().
AACDEC_FLAGS
#define AACDEC_FLAGS AV_OPT_FLAG_DECODING_PARAM | AV_OPT_FLAG_AUDIO_PARAM
AVOptions for Japanese DTV specific extensions (ADTS only)
Definition at line 3221 of file aacdec_template.c.
Function Documentation
output_configure()
static int output_configure (AACContext * ac, uint8_t layout_map[MAX_ELEM_ID *4][3], int tags, enum OCStatus oc_type, int get_new_frame) static
Configure output channel order based on the current program configuration element.
Returns
Returns error status. 0 - OK, !0 - error
Definition at line 436 of file aacdec_template.c.
Referenced by aac_decode_frame_int(), aac_decode_init(), decode_eld_specific_config(), decode_extension_payload(), decode_ga_specific_config(), get_che(), parse_adts_frame_header(), and pop_output_configuration().
count_channels()
static int count_channels (uint8_t(*) layout[3], int tags) static
Definition at line 103 of file aacdec_template.c.
Referenced by decode_ga_specific_config().
che_configure()
static av_cold int che_configure (AACContext * ac, enum ChannelPosition che_pos, int type, int id, int * channels) static
Check for the channel element in the current channel position configuration.
If it exists, make sure the appropriate element is allocated and map the channel order to match the internal FFmpeg channel layout.
Parameters
che_pos current channel position configuration
type channel element type
id channel element id
channels count of the number of channels in the configuration
Returns
Returns error status. 0 - OK, !0 - error
Definition at line 127 of file aacdec_template.c.
Referenced by output_configure().
frame_configure_elements()
static int frame_configure_elements (AVCodecContext * avctx) static
Definition at line 158 of file aacdec_template.c.
Referenced by aac_decode_er_frame(), aac_decode_frame_int(), and output_configure().
assign_pair()
static int assign_pair (struct elem_to_channel e2c_vec[MAX_ELEM_ID], uint8_t(*) layout_map[3], int offset, uint64_t left, uint64_t right, int pos) static
Definition at line 199 of file aacdec_template.c.
Referenced by sniff_channel_order().
count_paired_channels()
static int count_paired_channels (uint8_t(*) layout_map[3], int tags, int pos, int * current) static
Definition at line 228 of file aacdec_template.c.
Referenced by sniff_channel_order().
sniff_channel_order()
static uint64_t sniff_channel_order (uint8_t(*) layout_map[3], int tags) static
Definition at line 260 of file aacdec_template.c.
Referenced by output_configure().
push_output_configuration()
static void push_output_configuration (AACContext * ac) static
Save current output configuration if and only if it has been locked.
Definition at line 409 of file aacdec_template.c.
Referenced by aac_decode_frame(), aac_decode_frame_int(), get_che(), latm_decode_frame(), and parse_adts_frame_header().
pop_output_configuration()
static void pop_output_configuration (AACContext * ac) static
Restore the previous output configuration if and only if the current configuration is unlocked.
Definition at line 420 of file aacdec_template.c.
Referenced by aac_decode_frame(), aac_decode_frame_int(), and latm_decode_frame().
flush()
static void flush (AVCodecContext * avctx) static
Definition at line 496 of file aacdec_template.c.
Referenced by av_interleaved_write_frame(), bmp_parse(), decode_flush(), dpx_parse(), ff_interleave_packet_per_dts(), ff_vp8_decode_init(), g726_reset(), gsm_flush(), libgsm_flush(), mediacodec_decode_flush(), mpegaudio_parse(), ogg_buffer_data(), png_parse(), and read_huffman_tree().
set_default_channel_config()
static int set_default_channel_config (AVCodecContext * avctx, uint8_t(*) layout_map[3], int * tags, int channel_config) static
Set up channel positions based on a default channel configuration as specified in table 1.17.
Returns
Returns error status. 0 - OK, !0 - error
Definition at line 519 of file aacdec_template.c.
Referenced by aac_decode_init(), decode_eld_specific_config(), decode_ga_specific_config(), get_che(), and parse_adts_frame_header().
get_che()
static ChannelElement* get_che (AACContext * ac, int type, int elem_id) static
Definition at line 556 of file aacdec_template.c.
Referenced by aac_decode_er_frame(), and aac_decode_frame_int().
decode_channel_map()
static void decode_channel_map (uint8_t layout_map[][3], enum ChannelPosition type, GetBitContext * gb, int n) static
Decode an array of 4 bit element IDs, optionally interleaved with a stereo/mono switching bit.
Parameters
type speaker type/position for these channels
Definition at line 688 of file aacdec_template.c.
Referenced by decode_pce().
decode_pce()
static int decode_pce (AVCodecContext * avctx, MPEG4AudioConfig * m4ac, uint8_t(*) layout_map[3], GetBitContext * gb) static
Decode program configuration element; reference: table 4.2.
Returns
Returns error status. 0 - OK, !0 - error
Definition at line 723 of file aacdec_template.c.
Referenced by aac_decode_frame_int(), and decode_ga_specific_config().
decode_ga_specific_config()
static int decode_ga_specific_config (AACContext * ac, AVCodecContext * avctx, GetBitContext * gb, MPEG4AudioConfig * m4ac, int channel_config) static
Decode GA "General Audio" specific configuration; reference: table 4.1.
Parameters
ac pointer to AACContext, may be null
avctx pointer to AVCCodecContext, used for logging
Returns
Returns error status. 0 - OK, !0 - error
Definition at line 793 of file aacdec_template.c.
Referenced by decode_audio_specific_config().
decode_eld_specific_config()
static int decode_eld_specific_config (AACContext * ac, AVCodecContext * avctx, GetBitContext * gb, MPEG4AudioConfig * m4ac, int channel_config) static
Definition at line 871 of file aacdec_template.c.
Referenced by decode_audio_specific_config().
decode_audio_specific_config()
static int decode_audio_specific_config (AACContext * ac, AVCodecContext * avctx, MPEG4AudioConfig * m4ac, const uint8_t * data, int64_t bit_size, int sync_extension) static
Decode audio specific configuration; reference: table 1.13.
Parameters
ac pointer to AACContext, may be null
avctx pointer to AVCCodecContext, used for logging
m4ac pointer to MPEG4AudioConfig, used for parsing
data pointer to buffer holding an audio specific config
bit_size size of audio specific config or data in bits
sync_extension look for an appended sync extension
Returns
Returns error status or number of consumed bits. <0 - error
Definition at line 946 of file aacdec_template.c.
Referenced by aac_decode_frame(), aac_decode_init(), latm_decode_audio_specific_config(), and latm_decode_frame().
lcg_random()
static av_always_inline int lcg_random (unsigned previous_val) static
linear congruential pseudorandom number generator
Parameters
previous_val pointer to the current state of the generator
Returns
Returns a 32-bit pseudorandom integer
Definition at line 1026 of file aacdec_template.c.
Referenced by decode_spectrum_and_dequant(), and search_for_pns().
reset_all_predictors()
static void reset_all_predictors (PredictorState * ps) static
Definition at line 1032 of file aacdec_template.c.
Referenced by apply_prediction().
sample_rate_idx()
static int sample_rate_idx (int rate) static
Definition at line 1039 of file aacdec_template.c.
Referenced by aac_decode_init().
reset_predictor_group()
static void reset_predictor_group (PredictorState * ps, int group_num) static
Definition at line 1055 of file aacdec_template.c.
Referenced by apply_prediction().
aacdec_init()
static void aacdec_init (AACContext * ac) static
Definition at line 3201 of file aacdec_template.c.
Referenced by aac_decode_init().
aac_static_table_init()
static av_cold void aac_static_table_init (void) static
Definition at line 1072 of file aacdec_template.c.
Referenced by aac_decode_init().
aac_decode_init()
static av_cold int aac_decode_init (AVCodecContext * avctx) static
Definition at line 1112 of file aacdec_template.c.
Referenced by latm_decode_init().
skip_data_stream_element()
static int skip_data_stream_element (AACContext * ac, GetBitContext * gb) static
Skip data_stream_element; reference: table 4.10.
Definition at line 1199 of file aacdec_template.c.
Referenced by aac_decode_frame_int().
decode_prediction()
static int decode_prediction (AACContext * ac, IndividualChannelStream * ics, GetBitContext * gb) static
Definition at line 1216 of file aacdec_template.c.
Referenced by decode_ics_info().
decode_ltp()
static void decode_ltp (LongTermPrediction * ltp, GetBitContext * gb, uint8_t max_sfb) static
Decode Long Term Prediction data; reference: table 4.xx.
Definition at line 1238 of file aacdec_template.c.
Referenced by decode_cpe(), and decode_ics_info().
decode_ics_info()
static int decode_ics_info (AACContext * ac, IndividualChannelStream * ics, GetBitContext * gb) static
Decode Individual Channel Stream info; reference: table 4.6.
Definition at line 1252 of file aacdec_template.c.
Referenced by decode_cpe(), and decode_ics().
decode_band_types()
static int decode_band_types (AACContext * ac, enum BandType band_type[120], int band_type_run_end[120], GetBitContext * gb, IndividualChannelStream * ics) static
Decode band types (section_data payload); reference: table 4.46.
Parameters
band_type array of the used band type
band_type_run_end array of the last scalefactor band of a band type run
Returns
Returns error status. 0 - OK, !0 - error
Definition at line 1363 of file aacdec_template.c.
Referenced by decode_ics().
decode_scalefactors()
static int decode_scalefactors (AACContext * ac, INTFLOAT sf[120], GetBitContext * gb, unsigned int global_gain, IndividualChannelStream * ics, enum BandType band_type[120], int band_type_run_end[120]) static
Decode scalefactors; reference: table 4.47.
Parameters
global_gain first scalefactor value as scalefactors are differentially coded
band_type array of the used band type
band_type_run_end array of the last scalefactor band of a band type run
sf array of scalefactors or intensity stereo positions
Returns
Returns error status. 0 - OK, !0 - error
Definition at line 1412 of file aacdec_template.c.
Referenced by decode_ics().
decode_pulses()
static int decode_pulses (Pulse * pulse, GetBitContext * gb, const uint16_t * swb_offset, int num_swb) static
Decode pulse data; reference: table 4.7.
Definition at line 1487 of file aacdec_template.c.
Referenced by decode_ics().
decode_tns()
static int decode_tns (AACContext * ac, TemporalNoiseShaping * tns, GetBitContext * gb, const IndividualChannelStream * ics) static
Decode Temporal Noise Shaping data; reference: table 4.48.
Returns
Returns error status. 0 - OK, !0 - error
Definition at line 1514 of file aacdec_template.c.
Referenced by decode_ics().
decode_mid_side_stereo()
static void decode_mid_side_stereo (ChannelElement * cpe, GetBitContext * gb, int ms_present) static
Decode Mid/Side data; reference: table 4.54.
Parameters
ms_present Indicates mid/side stereo presence. [0] mask is all 0s; [1] mask is decoded from bitstream; [2] mask is all 1s; [3] reserved for scalable AAC
Definition at line 1557 of file aacdec_template.c.
Referenced by decode_cpe().
decode_spectrum_and_dequant()
static int decode_spectrum_and_dequant (AACContext * ac, INTFLOAT coef[1024], GetBitContext * gb, const INTFLOAT sf[120], int pulse_present, const Pulse * pulse, const IndividualChannelStream * ics, enum BandType band_type[120]) static
Decode spectral data; reference: table 4.50.
Dequantize and scale spectral data; reference: 4.6.3.3.
Parameters
coef array of dequantized, scaled spectral data
sf array of scalefactors or intensity stereo positions
pulse_present set if pulses are present
pulse pointer to pulse data struct
band_type array of the used band type
Returns
Returns error status. 0 - OK, !0 - error
Definition at line 1582 of file aacdec_template.c.
Referenced by decode_ics().
apply_prediction()
static void apply_prediction (AACContext * ac, SingleChannelElement * sce) static
Apply AAC-Main style frequency domain prediction.
Definition at line 1879 of file aacdec_template.c.
Referenced by decode_cpe(), and decode_ics().
decode_ics()
static int decode_ics (AACContext * ac, SingleChannelElement * sce, GetBitContext * gb, int common_window, int scale_flag) static
Decode an individual_channel_stream payload; reference: table 4.44.
Parameters
common_window Channels have independent [0], or shared [1], Individual Channel Stream information.
scale_flag scalable [1] or non-scalable [0] AAC (Unused until scalable AAC is implemented.)
Returns
Returns error status. 0 - OK, !0 - error
Definition at line 1915 of file aacdec_template.c.
Referenced by aac_decode_er_frame(), aac_decode_frame_int(), decode_cce(), and decode_cpe().
apply_mid_side_stereo()
static void apply_mid_side_stereo (AACContext * ac, ChannelElement * cpe) static
Mid/Side stereo decoding; reference: 4.6.8.1.3.
Definition at line 1992 of file aacdec_template.c.
Referenced by decode_cpe().
apply_intensity_stereo()
static void apply_intensity_stereo (AACContext * ac, ChannelElement * cpe, int ms_present) static
intensity stereo decoding; reference: 4.6.8.2.3
Parameters
ms_present Indicates mid/side stereo presence. [0] mask is all 0s; [1] mask is decoded from bitstream; [2] mask is all 1s; [3] reserved for scalable AAC
Definition at line 2030 of file aacdec_template.c.
Referenced by decode_cpe().
decode_cpe()
static int decode_cpe (AACContext * ac, GetBitContext * gb, ChannelElement * cpe) static
Decode a channel_pair_element; reference: table 4.4.
Returns
Returns error status. 0 - OK, !0 - error
Definition at line 2080 of file aacdec_template.c.
Referenced by aac_decode_er_frame(), and aac_decode_frame_int().
decode_cce()
static int decode_cce (AACContext * ac, GetBitContext * gb, ChannelElement * che) static
Decode coupling_channel_element; reference: table 4.8.
Returns
Returns error status. 0 - OK, !0 - error
Definition at line 2133 of file aacdec_template.c.
Referenced by aac_decode_frame_int().
decode_drc_channel_exclusions()
static int decode_drc_channel_exclusions (DynamicRangeControl * che_drc, GetBitContext * gb) static
Parse whether channels are to be excluded from Dynamic Range Compression; reference: table 4.53.
Returns
Returns number of bytes consumed.
Definition at line 2205 of file aacdec_template.c.
Referenced by decode_dynamic_range().
decode_dynamic_range()
static int decode_dynamic_range (DynamicRangeControl * che_drc, GetBitContext * gb) static
Decode dynamic range information; reference: table 4.52.
Returns
Returns number of bytes consumed.
Definition at line 2224 of file aacdec_template.c.
Referenced by decode_extension_payload().
decode_fill()
static int decode_fill (AACContext * ac, GetBitContext * gb, int len) static
Definition at line 2271 of file aacdec_template.c.
Referenced by decode_extension_payload().
decode_extension_payload()
static int decode_extension_payload (AACContext * ac, GetBitContext * gb, int cnt, ChannelElement * che, enum RawDataBlockType elem_type) static
Decode extension data (incomplete); reference: table 4.51.
Parameters
cnt length of TYPE_FIL syntactic element in bytes
Returns
Returns number of bytes consumed
Definition at line 2304 of file aacdec_template.c.
Referenced by aac_decode_frame_int().
apply_tns()
static void apply_tns (INTFLOAT coef[1024], TemporalNoiseShaping * tns, IndividualChannelStream * ics, int decode) static
Decode Temporal Noise Shaping filter coefficients and apply all-pole filters; reference: 4.6.9.3.
Parameters
decode 1 if tool is used normally, 0 if tool is used in LTP.
coef spectral coefficients
Definition at line 2362 of file aacdec_template.c.
Referenced by aacdec_init().
windowing_and_mdct_ltp()
static void windowing_and_mdct_ltp (AACContext * ac, INTFLOAT * out, INTFLOAT * in, IndividualChannelStream * ics) static
Apply windowing and MDCT to obtain the spectral coefficient from the predicted sample by LTP.
Definition at line 2418 of file aacdec_template.c.
Referenced by aacdec_init().
apply_ltp()
static void apply_ltp (AACContext * ac, SingleChannelElement * sce) static
Apply the long term prediction.
Definition at line 2444 of file aacdec_template.c.
Referenced by aacdec_init().
update_ltp()
static void update_ltp (AACContext * ac, SingleChannelElement * sce) static
Update the LTP buffer for next frame.
Definition at line 2476 of file aacdec_template.c.
Referenced by aacdec_init().
imdct_and_windowing()
static void imdct_and_windowing (AACContext * ac, SingleChannelElement * sce) static
Conduct IMDCT and windowing.
Definition at line 2514 of file aacdec_template.c.
Referenced by aacdec_init().
imdct_and_windowing_ld()
static void imdct_and_windowing_ld (AACContext * ac, SingleChannelElement * sce) static
Definition at line 2579 of file aacdec_template.c.
Referenced by spectral_to_sample().
imdct_and_windowing_eld()
static void imdct_and_windowing_eld (AACContext * ac, SingleChannelElement * sce) static
Definition at line 2612 of file aacdec_template.c.
Referenced by spectral_to_sample().
apply_channel_coupling()
static void apply_channel_coupling (AACContext * ac, ChannelElement * cc, enum RawDataBlockType type, int elem_id, enum CouplingPoint coupling_point, void(*)(AACContext *ac, SingleChannelElement *target, ChannelElement *cce, int index) apply_coupling_method) static
channel coupling transformation interface
Parameters
apply_coupling_method pointer to (in)dependent coupling function
Definition at line 2685 of file aacdec_template.c.
Referenced by spectral_to_sample().
spectral_to_sample()
static void spectral_to_sample (AACContext * ac, int samples) static
Convert spectral data to samples, applying all supported tools as appropriate.
Definition at line 2718 of file aacdec_template.c.
Referenced by aac_decode_er_frame(), and aac_decode_frame_int().
parse_adts_frame_header()
static int parse_adts_frame_header (AACContext * ac, GetBitContext * gb) static
dual mono frames in Japanese DTV can have chan_config 0 WITHOUT specifying PCE. thus, set dual mono as default.
Definition at line 2787 of file aacdec_template.c.
Referenced by aac_decode_frame_int().
aac_decode_er_frame()
static int aac_decode_er_frame (AVCodecContext * avctx, void * data, int * got_frame_ptr, GetBitContext * gb) static
Definition at line 2849 of file aacdec_template.c.
Referenced by aac_decode_frame(), and latm_decode_frame().
aac_decode_frame_int()
static int aac_decode_frame_int (AVCodecContext * avctx, void * data, int * got_frame_ptr, GetBitContext * gb, AVPacket * avpkt) static
Definition at line 2921 of file aacdec_template.c.
Referenced by aac_decode_frame(), and latm_decode_frame().
aac_decode_frame()
static int aac_decode_frame (AVCodecContext * avctx, void * data, int * got_frame_ptr, AVPacket * avpkt) static
Definition at line 3108 of file aacdec_template.c.
aac_decode_close()
static av_cold int aac_decode_close (AVCodecContext * avctx) static
Definition at line 3177 of file aacdec_template.c.
Variable Documentation
vlc_scalefactors
VLC vlc_scalefactors static
Definition at line 94 of file aacdec_template.c.
vlc_spectral
VLC vlc_spectral[11] static
Definition at line 95 of file aacdec_template.c.
aac_table_init
AVOnce aac_table_init = AV_ONCE_INIT static
Definition at line 1110 of file aacdec_template.c.
cce_scale
const float cce_scale[] static
Initial value:
= {
    1.09050773266525765921,
    1.18920711500272106672,
    M_SQRT2,
    2,
}
Definition at line 2121 of file aacdec_template.c.
options
const AVOption options[] static
Initial value:
= {
    {"dual_mono_mode", "Select the channel to decode for dual mono",
     0x42, AV_OPT_TYPE_INT, {.i64=-1}, -1, 2,
     AACDEC_FLAGS, "dual_mono_mode"},
    {"auto", "autoselection",            0, AV_OPT_TYPE_CONST, {.i64=-1}, INT_MIN, INT_MAX, AACDEC_FLAGS, "dual_mono_mode"},
    {"main", "Select Main/Left channel", 0, AV_OPT_TYPE_CONST, {.i64= 1}, INT_MIN, INT_MAX, AACDEC_FLAGS, "dual_mono_mode"},
    {"sub" , "Select Sub/Right channel", 0, AV_OPT_TYPE_CONST, {.i64= 2}, INT_MIN, INT_MAX, AACDEC_FLAGS, "dual_mono_mode"},
    {"both", "Select both channels",     0, AV_OPT_TYPE_CONST, {.i64= 0}, INT_MIN, INT_MAX, AACDEC_FLAGS, "dual_mono_mode"},
    {NULL},
}
Definition at line 3222 of file aacdec_template.c.
aac_decoder_class
const AVClass aac_decoder_class static
Initial value:
= {
    .class_name = "AAC decoder",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 3235 of file aacdec_template.c.