FFmpeg: libavcodec/x86/aacencdsp_init.c File Reference
aacencdsp_init.c File Reference
#include "config.h"
#include "libavutil/float_dsp.h"
#include "libavutil/x86/cpu.h"
#include "libavcodec/aacenc.h"
Functions
void ff_abs_pow34_sse (float *out, const float *in, const int size)
void ff_aac_quantize_bands_sse2 (int *out, const float *in, const float *scaled, int size, int is_signed, int maxval, const float Q34, const float rounding)
av_cold void ff_aac_dsp_init_x86 (AACEncContext *s)
Function Documentation
ff_abs_pow34_sse()
void ff_abs_pow34_sse (float * out, const float * in, const int size)
Referenced by ff_aac_dsp_init_x86().
ff_aac_quantize_bands_sse2()
void ff_aac_quantize_bands_sse2 (int * out, const float * in, const float * scaled, int size, int is_signed, int maxval, const float Q34, const float rounding)
Referenced by ff_aac_dsp_init_x86().
ff_aac_dsp_init_x86()
av_cold void ff_aac_dsp_init_x86 (AACEncContext * s)
Definition at line 34 of file aacencdsp_init.c.
Referenced by aac_encode_init().