FFmpeg: libavcodec/aacenc.c File Reference
aacenc.c File Reference
AAC encoder.
#include "libavutil/libm.h"
#include "libavutil/thread.h"
#include "libavutil/float_dsp.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "put_bits.h"
#include "internal.h"
#include "mpeg4audio.h"
#include "kbdwin.h"
#include "sinewin.h"
#include "aac.h"
#include "aactab.h"
#include "aacenc.h"
#include "aacenctab.h"
#include "aacenc_utils.h"
#include "psymodel.h"
Macros
#define WINDOW_FUNC(type)
#define AACENC_FLAGS AV_OPT_FLAG_ENCODING_PARAM | AV_OPT_FLAG_AUDIO_PARAM
Functions
static void put_audio_specific_config (AVCodecContext *avctx)
Make AAC audio config object.
void ff_quantize_band_cost_cache_init (struct AACEncContext *s)
WINDOW_FUNC (only_long)
WINDOW_FUNC (long_start)
WINDOW_FUNC (long_stop)
WINDOW_FUNC (eight_short)
static void apply_window_and_mdct (AACEncContext *s, SingleChannelElement *sce, float *audio)
static void put_ics_info (AACEncContext *s, IndividualChannelStream *info)
Encode ics_info element.
static void encode_ms_info (PutBitContext *pb, ChannelElement *cpe)
Encode MS data.
static void adjust_frame_information (ChannelElement *cpe, int chans)
Produce integer coefficients from scalefactors provided by the model.
static void apply_intensity_stereo (ChannelElement *cpe)
static void apply_mid_side_stereo (ChannelElement *cpe)
static void encode_band_info (AACEncContext *s, SingleChannelElement *sce)
Encode scalefactor band coding type.
static void encode_scale_factors (AVCodecContext *avctx, AACEncContext *s, SingleChannelElement *sce)
Encode scalefactors.
static void encode_pulses (AACEncContext *s, Pulse *pulse)
Encode pulse data.
static void encode_spectral_coeffs (AACEncContext *s, SingleChannelElement *sce)
Encode spectral coefficients processed by psychoacoustic model.
static void avoid_clipping (AACEncContext *s, SingleChannelElement *sce)
Downscale spectral coefficients for near-clipping windows to avoid artifacts.
static int encode_individual_channel (AVCodecContext *avctx, AACEncContext *s, SingleChannelElement *sce, int common_window)
Encode one channel of audio data.
static void put_bitstream_info (AACEncContext *s, const char *name)
Write some auxiliary information about the created AAC file.
static void copy_input_samples (AACEncContext *s, const AVFrame *frame)
static int aac_encode_frame (AVCodecContext *avctx, AVPacket *avpkt, const AVFrame *frame, int *got_packet_ptr)
static av_cold int aac_encode_end (AVCodecContext *avctx)
static av_cold int dsp_init (AVCodecContext *avctx, AACEncContext *s)
static av_cold int alloc_buffers (AVCodecContext *avctx, AACEncContext *s)
static av_cold void aac_encode_init_tables (void)
static av_cold int aac_encode_init (AVCodecContext *avctx)
Variables
static AVOnce aac_table_init = AV_ONCE_INIT
static void(*const apply_window [4])(AVFloatDSPContext *fdsp, SingleChannelElement *sce, const float *audio)
static const AVOption aacenc_options []
static const AVClass aacenc_class
static const AVCodecDefault aac_encode_defaults []
AVCodec ff_aac_encoder
Detailed Description
AAC encoder.
Definition in file aacenc.c.
Macro Definition Documentation
WINDOW_FUNC
#define WINDOW_FUNC (type)
Value:
static void apply_ ##type ##_window(AVFloatDSPContext *fdsp, \
                                    SingleChannelElement *sce, \
                                    const float *audio)
Definition at line 88 of file aacenc.c.
AACENC_FLAGS
#define AACENC_FLAGS AV_OPT_FLAG_ENCODING_PARAM | AV_OPT_FLAG_AUDIO_PARAM
Definition at line 1053 of file aacenc.c.
Function Documentation
put_audio_specific_config()
static void put_audio_specific_config (AVCodecContext * avctx) static
Make AAC audio config object.
See also
1.6.2.1 "Syntax - AudioSpecificConfig"
Definition at line 57 of file aacenc.c.
Referenced by aac_encode_init().
ff_quantize_band_cost_cache_init()
void ff_quantize_band_cost_cache_init (struct AACEncContext * s)
Definition at line 79 of file aacenc.c.
Referenced by search_for_quantizers_fast(), and search_for_quantizers_twoloop().
WINDOW_FUNC() [1/4]
WINDOW_FUNC (only_long)
Definition at line 93 of file aacenc.c.
WINDOW_FUNC() [2/4]
WINDOW_FUNC (long_start)
Definition at line 103 of file aacenc.c.
WINDOW_FUNC() [3/4]
WINDOW_FUNC (long_stop)
Definition at line 115 of file aacenc.c.
WINDOW_FUNC() [4/4]
WINDOW_FUNC (eight_short)
Definition at line 127 of file aacenc.c.
apply_window_and_mdct()
static void apply_window_and_mdct (AACEncContext * s, SingleChannelElement * sce, float * audio) static
Definition at line 153 of file aacenc.c.
Referenced by aac_encode_frame().
put_ics_info()
static void put_ics_info (AACEncContext * s, IndividualChannelStream * info) static
Encode ics_info element.
See also
Table 4.6 (syntax of ics_info)
Definition at line 174 of file aacenc.c.
Referenced by aac_encode_frame(), and encode_individual_channel().
encode_ms_info()
static void encode_ms_info (PutBitContext * pb, ChannelElement * cpe) static
Encode MS data.
See also
4.6.8.1 "Joint Coding - M/S Stereo"
Definition at line 195 of file aacenc.c.
Referenced by aac_encode_frame().
adjust_frame_information()
static void adjust_frame_information (ChannelElement * cpe, int chans) static
Produce integer coefficients from scalefactors provided by the model.
Definition at line 209 of file aacenc.c.
Referenced by aac_encode_frame().
apply_intensity_stereo()
static void apply_intensity_stereo (ChannelElement * cpe) static
Definition at line 259 of file aacenc.c.
Referenced by aac_encode_frame().
apply_mid_side_stereo()
static void apply_mid_side_stereo (ChannelElement * cpe) static
Definition at line 288 of file aacenc.c.
Referenced by aac_encode_frame().
encode_band_info()
static void encode_band_info (AACEncContext * s, SingleChannelElement * sce) static
Encode scalefactor band coding type.
Definition at line 323 of file aacenc.c.
Referenced by encode_individual_channel().
encode_scale_factors()
static void encode_scale_factors (AVCodecContext * avctx, AACEncContext * s, SingleChannelElement * sce) static
Encode scalefactors.
Definition at line 337 of file aacenc.c.
Referenced by encode_individual_channel().
encode_pulses()
static void encode_pulses (AACEncContext * s, Pulse * pulse) static
Encode pulse data.
Definition at line 373 of file aacenc.c.
Referenced by encode_individual_channel().
encode_spectral_coeffs()
static void encode_spectral_coeffs (AACEncContext * s, SingleChannelElement * sce) static
Encode spectral coefficients processed by psychoacoustic model.
Definition at line 392 of file aacenc.c.
Referenced by encode_individual_channel().
avoid_clipping()
static void avoid_clipping (AACEncContext * s, SingleChannelElement * sce) static
Downscale spectral coefficients for near-clipping windows to avoid artifacts.
Definition at line 420 of file aacenc.c.
Referenced by aac_encode_frame().
encode_individual_channel()
static int encode_individual_channel (AVCodecContext * avctx, AACEncContext * s, SingleChannelElement * sce, int common_window) static
Encode one channel of audio data.
Definition at line 440 of file aacenc.c.
Referenced by aac_encode_frame().
put_bitstream_info()
static void put_bitstream_info (AACEncContext * s, const char * name) static
Write some auxiliary information about the created AAC file.
Definition at line 466 of file aacenc.c.
Referenced by aac_encode_frame().
copy_input_samples()
static void copy_input_samples (AACEncContext * s, const AVFrame * frame) static
Definition at line 487 of file aacenc.c.
Referenced by aac_encode_frame().
aac_encode_frame()
static int aac_encode_frame (AVCodecContext * avctx, AVPacket * avpkt, const AVFrame * frame, int * got_packet_ptr) static
Definition at line 509 of file aacenc.c.
aac_encode_end()
static av_cold int aac_encode_end (AVCodecContext * avctx) static
Definition at line 852 of file aacenc.c.
Referenced by aac_encode_init().
dsp_init()
static av_cold int dsp_init (AVCodecContext * avctx, AACEncContext * s) static
Definition at line 871 of file aacenc.c.
Referenced by aac_encode_init().
alloc_buffers()
static av_cold int alloc_buffers (AVCodecContext * avctx, AACEncContext * s) static
Definition at line 893 of file aacenc.c.
Referenced by aac_encode_init().
aac_encode_init_tables()
static av_cold void aac_encode_init_tables (void) static
Definition at line 908 of file aacenc.c.
Referenced by aac_encode_init().
aac_encode_init()
static av_cold int aac_encode_init (AVCodecContext * avctx) static
Definition at line 913 of file aacenc.c.
Variable Documentation
aac_table_init
AVOnce aac_table_init = AV_ONCE_INIT static
Definition at line 51 of file aacenc.c.
Referenced by aac_encode_init().
apply_window
void(*const apply_window[4])(AVFloatDSPContext *fdsp, SingleChannelElement *sce, const float *audio) static
Initial value:
= {
    [ONLY_LONG_SEQUENCE]   = apply_only_long_window,
    [LONG_START_SEQUENCE]  = apply_long_start_window,
    [EIGHT_SHORT_SEQUENCE] = apply_eight_short_window,
    [LONG_STOP_SEQUENCE]   = apply_long_stop_window
}
Definition at line 144 of file aacenc.c.
Referenced by aac_encode_frame(), apply_window_and_mdct(), and ff_mpa_synth_filter().
aacenc_options
const AVOption aacenc_options[] static
Initial value:
= {
    {"aac_coder", "Coding algorithm", 0x42, AV_OPT_TYPE_INT, {.i64 = AAC_CODER_TWOLOOP}, 0, AAC_CODER_NB-1, AACENC_FLAGS, "coder"},
        {"anmr",     "ANMR method",               0, AV_OPT_TYPE_CONST, {.i64 = AAC_CODER_ANMR},    INT_MIN, INT_MAX, AACENC_FLAGS, "coder"},
        {"twoloop",  "Two loop searching method", 0, AV_OPT_TYPE_CONST, {.i64 = AAC_CODER_TWOLOOP}, INT_MIN, INT_MAX, AACENC_FLAGS, "coder"},
        {"fast",     "Constant quantizer",        0, AV_OPT_TYPE_CONST, {.i64 = AAC_CODER_FAST},    INT_MIN, INT_MAX, AACENC_FLAGS, "coder"},
    {"aac_ms", "Force M/S stereo coding", 0x42, AV_OPT_TYPE_BOOL, {.i64 = -1}, -1, 1, AACENC_FLAGS},
    {"aac_is", "Intensity stereo coding", 0x42, AV_OPT_TYPE_BOOL, {.i64 = 1}, -1, 1, AACENC_FLAGS},
    {"aac_pns", "Perceptual noise substitution", 0x42, AV_OPT_TYPE_BOOL, {.i64 = 1}, -1, 1, AACENC_FLAGS},
    {"aac_tns", "Temporal noise shaping", 0x42, AV_OPT_TYPE_BOOL, {.i64 = 1}, -1, 1, AACENC_FLAGS},
    {"aac_ltp", "Long term prediction", 0x42, AV_OPT_TYPE_BOOL, {.i64 = 0}, -1, 1, AACENC_FLAGS},
    {"aac_pred", "AAC-Main prediction", 0x42, AV_OPT_TYPE_BOOL, {.i64 = 0}, -1, 1, AACENC_FLAGS},
    {NULL}
}
Definition at line 1054 of file aacenc.c.
aacenc_class
const AVClass aacenc_class static
Initial value:
= {
    "AAC encoder",
    av_default_item_name,
    aacenc_options,
    LIBAVUTIL_VERSION_INT,
}
Definition at line 1068 of file aacenc.c.
aac_encode_defaults
const AVCodecDefault aac_encode_defaults[] static
Initial value:
= {
    { "b", "0" },
    { NULL }
}
Definition at line 1075 of file aacenc.c.
ff_aac_encoder
AVCodec ff_aac_encoder
Initial value:
= {
    .name           = "aac",
    .long_name      = NULL_IF_CONFIG_SMALL("AAC (Advanced Audio Coding)"),
    .type           = AVMEDIA_TYPE_AUDIO,
    .id             = AV_CODEC_ID_AAC,
    .priv_data_size = sizeof(AACEncContext),
    .init           = aac_encode_init,
    .encode2        = aac_encode_frame,
    .close          = aac_encode_end,
    .defaults       = aac_encode_defaults,
    .supported_samplerates = mpeg4audio_sample_rates,
    .caps_internal  = FF_CODEC_CAP_INIT_THREADSAFE,
    .capabilities   = AV_CODEC_CAP_SMALL_LAST_FRAME | AV_CODEC_CAP_DELAY,
    .sample_fmts    = (const enum AVSampleFormat[]){ AV_SAMPLE_FMT_FLTP,
                                                     AV_SAMPLE_FMT_NONE },
    .priv_class     = &aacenc_class,
}
Definition at line 1080 of file aacenc.c.