FFmpeg: libavcodec/aacenc_pred.c File Reference
aacenc_pred.c File Reference
AAC encoder main-type prediction.
#include "aactab.h"
#include "aacenc_pred.h"
#include "aacenc_utils.h"
#include "aacenc_is.h"
#include "aacenc_quantization.h"
Macros
#define RESTORE_PRED(sce, sfb)
Functions
static float flt16_round (float pf)
static float flt16_even (float pf)
static float flt16_trunc (float pf)
static void predict (PredictorState *ps, float *coef, float *rcoef, int set)
static void reset_predict_state (PredictorState *ps)
static void reset_all_predictors (PredictorState *ps)
static void reset_predictor_group (SingleChannelElement *sce, int group_num)
void ff_aac_apply_main_pred (AACEncContext *s, SingleChannelElement *sce)
static int update_counters (IndividualChannelStream *ics, int inc)
void ff_aac_adjust_common_pred (AACEncContext *s, ChannelElement *cpe)
static void update_pred_resets (SingleChannelElement *sce)
void ff_aac_search_for_pred (AACEncContext *s, SingleChannelElement *sce)
void ff_aac_encode_main_pred (AACEncContext *s, SingleChannelElement *sce)
Encoder predictors data.
Detailed Description
AAC encoder main-type prediction.
Author
Rostislav Pehlivanov (atomnuker gmail com)
Definition in file aacenc_pred.c.
Macro Definition Documentation
RESTORE_PRED
#define RESTORE_PRED (sce, sfb)
Value:
if (sce->ics.prediction_used[sfb]) {\
            sce->ics.prediction_used[sfb] = 0;\
            sce->band_type[sfb] = sce->band_alt[sfb];\
        }
Definition at line 34 of file aacenc_pred.c.
Referenced by ff_aac_adjust_common_pred(), and ff_aac_search_for_pred().
Function Documentation
flt16_round()
static float flt16_round (float pf) inline static
Definition at line 40 of file aacenc_pred.c.
Referenced by predict().
flt16_even()
static float flt16_even (float pf) inline static
Definition at line 48 of file aacenc_pred.c.
Referenced by predict().
flt16_trunc()
static float flt16_trunc (float pf) inline static
Definition at line 56 of file aacenc_pred.c.
Referenced by predict().
predict()
static void predict (PredictorState * ps, float * coef, float * rcoef, int set) inline static
Definition at line 64 of file aacenc_pred.c.
Referenced by ff_aac_apply_main_pred().
reset_predict_state()
static void reset_predict_state (PredictorState * ps) inline static
Definition at line 92 of file aacenc_pred.c.
Referenced by reset_all_predictors(), and reset_predictor_group().
reset_all_predictors()
static void reset_all_predictors (PredictorState * ps) inline static
Definition at line 104 of file aacenc_pred.c.
Referenced by ff_aac_apply_main_pred(), and ff_aac_search_for_pred().
reset_predictor_group()
static void reset_predictor_group (SingleChannelElement * sce, int group_num) inline static
Definition at line 111 of file aacenc_pred.c.
Referenced by ff_aac_apply_main_pred().
ff_aac_apply_main_pred()
void ff_aac_apply_main_pred (AACEncContext * s, SingleChannelElement * sce)
Definition at line 119 of file aacenc_pred.c.
update_counters()
static int update_counters (IndividualChannelStream * ics, int inc) inline static
Definition at line 140 of file aacenc_pred.c.
Referenced by update_pred_resets().
ff_aac_adjust_common_pred()
void ff_aac_adjust_common_pred (AACEncContext * s, ChannelElement * cpe)
Definition at line 151 of file aacenc_pred.c.
update_pred_resets()
static void update_pred_resets (SingleChannelElement * sce) static
Definition at line 207 of file aacenc_pred.c.
Referenced by ff_aac_search_for_pred().
ff_aac_search_for_pred()
void ff_aac_search_for_pred (AACEncContext * s, SingleChannelElement * sce)
Definition at line 233 of file aacenc_pred.c.
ff_aac_encode_main_pred()
void ff_aac_encode_main_pred (AACEncContext * s, SingleChannelElement * sce)
Encoder predictors data.
Definition at line 332 of file aacenc_pred.c.