FFmpeg: libavcodec/aacenc.h File Reference
aacenc.h File Reference
#include "libavutil/float_dsp.h"
#include "avcodec.h"
#include "put_bits.h"
#include "aac.h"
#include "audio_frame_queue.h"
#include "psymodel.h"
#include "lpc.h"
Data Structures
struct AACEncOptions
struct AACCoefficientsEncoder
struct AACQuantizeBandCostCacheEntry
struct AACEncContext
AAC encoder context.
Enumerations
enum AACCoder { AAC_CODER_ANMR = 0, AAC_CODER_TWOLOOP, AAC_CODER_FAST, AAC_CODER_NB }
Functions
void ff_aac_dsp_init_x86 (AACEncContext *s)
void ff_aac_coder_init_mips (AACEncContext *c)
void ff_quantize_band_cost_cache_init (struct AACEncContext *s)
Variables
AACCoefficientsEncoder ff_aac_coders []
Enumeration Type Documentation
AACCoder
enum AACCoder
Enumerator
AAC_CODER_ANMR
AAC_CODER_TWOLOOP
AAC_CODER_FAST
AAC_CODER_NB
Definition at line 35 of file aacenc.h.
Function Documentation
ff_aac_dsp_init_x86()
void ff_aac_dsp_init_x86 (AACEncContext * s)
Definition at line 34 of file aacencdsp_init.c.
Referenced by aac_encode_init().
ff_aac_coder_init_mips()
void ff_aac_coder_init_mips (AACEncContext * c)
Definition at line 2484 of file aaccoder_mips.c.
Referenced by aac_encode_init().
ff_quantize_band_cost_cache_init()
void ff_quantize_band_cost_cache_init (struct AACEncContext * s)
Definition at line 79 of file aacenc.c.
Referenced by search_for_quantizers_fast(), and search_for_quantizers_twoloop().
Variable Documentation
ff_aac_coders
AACCoefficientsEncoder ff_aac_coders[]
Definition at line 897 of file aaccoder.c.
Referenced by aac_encode_init().