FFmpeg: libavcodec/aacpsdsp.h File Reference
aacpsdsp.h File Reference
#include "aac_defines.h"
Data Structures
struct PSDSPContext
Macros
#define PS_QMF_TIME_SLOTS 32
#define PS_AP_LINKS 3
#define PS_MAX_AP_DELAY 5
Functions
void AAC_RENAME() ff_psdsp_init (PSDSPContext *s)
void ff_psdsp_init_arm (PSDSPContext *s)
void ff_psdsp_init_mips (PSDSPContext *s)
void ff_psdsp_init_x86 (PSDSPContext *s)
Macro Definition Documentation
PS_QMF_TIME_SLOTS
#define PS_QMF_TIME_SLOTS 32
Definition at line 26 of file aacpsdsp.h.
PS_AP_LINKS
#define PS_AP_LINKS 3
Definition at line 27 of file aacpsdsp.h.
PS_MAX_AP_DELAY
#define PS_MAX_AP_DELAY 5
Definition at line 28 of file aacpsdsp.h.
Function Documentation
ff_psdsp_init()
void AAC_RENAME() ff_psdsp_init (PSDSPContext * s)
Definition at line 211 of file aacpsdsp_template.c.
Referenced by ff_ps_ctx_init().
ff_psdsp_init_arm()
void ff_psdsp_init_arm (PSDSPContext * s)
Definition at line 46 of file aacpsdsp_init_arm.c.
Referenced by ff_psdsp_init().
ff_psdsp_init_mips()
void ff_psdsp_init_mips (PSDSPContext * s)
Definition at line 450 of file aacpsdsp_mips.c.
Referenced by ff_psdsp_init().
ff_psdsp_init_x86()
void ff_psdsp_init_x86 (PSDSPContext * s)
Definition at line 41 of file aacpsdsp_init.c.
Referenced by ff_psdsp_init().