FFmpeg: libavcodec/x86/aacpsdsp_init.c File Reference
aacpsdsp_init.c File Reference
#include "config.h"
#include "libavutil/x86/cpu.h"
#include "libavutil/attributes.h"
#include "libavcodec/aacpsdsp.h"
Functions
void ff_ps_add_squares_sse (float *dst, const float(*src)[2], int n)
void ff_ps_add_squares_sse3 (float *dst, const float(*src)[2], int n)
void ff_ps_mul_pair_single_sse (float(*dst)[2], float(*src0)[2], float *src1, int n)
void ff_ps_hybrid_analysis_sse (float(*out)[2], float(*in)[2], const float(*filter)[8][2], int stride, int n)
void ff_ps_hybrid_analysis_sse3 (float(*out)[2], float(*in)[2], const float(*filter)[8][2], int stride, int n)
void ff_ps_stereo_interpolate_sse3 (float(*l)[2], float(*r)[2], float h[2][4], float h_step[2][4], int len)
av_cold void ff_psdsp_init_x86 (PSDSPContext *s)
Function Documentation
ff_ps_add_squares_sse()
void ff_ps_add_squares_sse (float * dst, const float(*) src[2], int n)
Referenced by ff_psdsp_init_x86().
ff_ps_add_squares_sse3()
void ff_ps_add_squares_sse3 (float * dst, const float(*) src[2], int n)
Referenced by ff_psdsp_init_x86().
ff_ps_mul_pair_single_sse()
void ff_ps_mul_pair_single_sse (float(*) dst[2], float(*) src0[2], float * src1, int n)
Referenced by ff_psdsp_init_x86().
ff_ps_hybrid_analysis_sse()
void ff_ps_hybrid_analysis_sse (float(*) out[2], float(*) in[2], const float(*) filter[8][2], int stride, int n)
Referenced by ff_psdsp_init_x86().
ff_ps_hybrid_analysis_sse3()
void ff_ps_hybrid_analysis_sse3 (float(*) out[2], float(*) in[2], const float(*) filter[8][2], int stride, int n)
Referenced by ff_psdsp_init_x86().
ff_ps_stereo_interpolate_sse3()
void ff_ps_stereo_interpolate_sse3 (float(*) l[2], float(*) r[2], float h[2][4], float h_step[2][4], int len)
Referenced by ff_psdsp_init_x86().
ff_psdsp_init_x86()
av_cold void ff_psdsp_init_x86 (PSDSPContext * s)
Definition at line 41 of file aacpsdsp_init.c.
Referenced by ff_psdsp_init().