FFmpeg: libavcodec/aarch64/fmtconvert_init.c File Reference
fmtconvert_init.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/aarch64/cpu.h"
#include "libavcodec/avcodec.h"
#include "libavcodec/fmtconvert.h"
Functions
void ff_int32_to_float_fmul_array8_neon (FmtConvertContext *c, float *dst, const int32_t *src, const float *mul, int len)
void ff_int32_to_float_fmul_scalar_neon (float *dst, const int32_t *src, float mul, int len)
av_cold void ff_fmt_convert_init_aarch64 (FmtConvertContext *c, AVCodecContext *avctx)
Function Documentation
ff_int32_to_float_fmul_array8_neon()
void ff_int32_to_float_fmul_array8_neon (FmtConvertContext * c, float * dst, const int32_t * src, const float * mul, int len)
Referenced by ff_fmt_convert_init_aarch64().
ff_int32_to_float_fmul_scalar_neon()
void ff_int32_to_float_fmul_scalar_neon (float * dst, const int32_t * src, float mul, int len)
Referenced by ff_fmt_convert_init_aarch64().
ff_fmt_convert_init_aarch64()
av_cold void ff_fmt_convert_init_aarch64 (FmtConvertContext * c, AVCodecContext * avctx)
Definition at line 34 of file fmtconvert_init.c.
Referenced by ff_fmt_convert_init().