FFmpeg: libavcodec/ac3.c File Reference
ac3.c File Reference
Common code between the AC-3 encoder and decoder.
#include "libavutil/common.h"
#include "avcodec.h"
#include "ac3.h"
Functions
static int calc_lowcomp1 (int a, int b0, int b1, int c)
static int calc_lowcomp (int a, int b0, int b1, int bin)
void ff_ac3_bit_alloc_calc_psd (int8_t *exp, int start, int end, int16_t *psd, int16_t *band_psd)
Calculate the log power-spectral density of the input signal.
int ff_ac3_bit_alloc_calc_mask (AC3BitAllocParameters *s, int16_t *band_psd, int start, int end, int fast_gain, int is_lfe, int dba_mode, int dba_nsegs, uint8_t *dba_offsets, uint8_t *dba_lengths, uint8_t *dba_values, int16_t *mask)
Calculate the masking curve.
Variables
const uint8_t ff_ac3_band_start_tab [AC3_CRITICAL_BANDS+1]
Starting frequency coefficient bin for each critical band.
const uint8_t ff_ac3_bin_to_band_tab [253]
Map each frequency coefficient bin to the critical band that contains it.
Detailed Description
Common code between the AC-3 encoder and decoder.
Definition in file ac3.c.
Function Documentation
calc_lowcomp1()
static int calc_lowcomp1 (int a, int b0, int b1, int c) inline static
Definition at line 71 of file ac3.c.
Referenced by calc_lowcomp(), and ff_ac3_bit_alloc_calc_mask().
calc_lowcomp()
static int calc_lowcomp (int a, int b0, int b1, int bin) inline static
Definition at line 81 of file ac3.c.
Referenced by ff_ac3_bit_alloc_calc_mask().
ff_ac3_bit_alloc_calc_psd()
void ff_ac3_bit_alloc_calc_psd (int8_t * exp, int start, int end, int16_t * psd, int16_t * band_psd)
Calculate the log power-spectral density of the input signal.
This gives a rough estimate of signal power in the frequency domain by using the spectral envelope (exponents). The psd is also separately grouped into critical bands for use in the calculating the masking curve. 128 units in psd = -6 dB. The dbknee parameter in AC3BitAllocParameters determines the reference level.
Parameters
[in] exp frequency coefficient exponents
[in] start starting bin location
[in] end ending bin location
[out] psd signal power for each frequency bin
[out] band_psd signal power for each critical band
Definition at line 92 of file ac3.c.
Referenced by bit_alloc_masking(), and decode_audio_block().
ff_ac3_bit_alloc_calc_mask()
int ff_ac3_bit_alloc_calc_mask (AC3BitAllocParameters * s, int16_t * band_psd, int start, int end, int fast_gain, int is_lfe, int dba_mode, int dba_nsegs, uint8_t * dba_offsets, uint8_t * dba_lengths, uint8_t * dba_values, int16_t * mask)
Calculate the masking curve.
First, the excitation is calculated using parameters in s and the signal power in each critical band. The excitation is compared with a predefined hearing threshold table to produce the masking curve. If delta bit allocation information is provided, it is used for adjusting the masking curve, usually to give a closer match to a better psychoacoustic model.
Parameters
[in] s adjustable bit allocation parameters
[in] band_psd signal power for each critical band
[in] start starting bin location
[in] end ending bin location
[in] fast_gain fast gain (estimated signal-to-mask ratio)
[in] is_lfe whether or not the channel being processed is the LFE
[in] dba_mode delta bit allocation mode (none, reuse, or new)
[in] dba_nsegs number of delta segments
[in] dba_offsets location offsets for each segment
[in] dba_lengths length of each segment
[in] dba_values delta bit allocation for each segment
[out] mask calculated masking curve
Returns
returns 0 for success, non-zero for error
Definition at line 118 of file ac3.c.
Referenced by bit_alloc_masking(), and decode_audio_block().
Variable Documentation
ff_ac3_band_start_tab
const uint8_t ff_ac3_band_start_tab[AC3_CRITICAL_BANDS+1]
Initial value:
= {
      0,  1,   2,   3,   4,   5,   6,   7,   8,   9,
     10,  11, 12,  13,  14,  15,  16,  17,  18,  19,
     20,  21, 22,  23,  24,  25,  26,  27,  28,  31,
     34,  37, 40,  43,  46,  49,  55,  61,  67,  73,
     79,  85, 97, 109, 121, 133, 157, 181, 205, 229, 253
}
Starting frequency coefficient bin for each critical band.
Definition at line 35 of file ac3.c.
Referenced by ac3_bit_alloc_calc_bap_c(), and ff_ac3_bit_alloc_calc_psd().
ff_ac3_bin_to_band_tab
const uint8_t ff_ac3_bin_to_band_tab[253]
Initial value:
= {
     0,
     1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
    13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
    25, 26, 27, 28, 28, 28, 29, 29, 29, 30, 30, 30,
    31, 31, 31, 32, 32, 32, 33, 33, 33, 34, 34, 34,
    35, 35, 35, 35, 35, 35, 36, 36, 36, 36, 36, 36,
    37, 37, 37, 37, 37, 37, 38, 38, 38, 38, 38, 38,
    39, 39, 39, 39, 39, 39, 40, 40, 40, 40, 40, 40,
    41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
    42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42,
    43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
    44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
    45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
    45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
    46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
    46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
    47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
    47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
    48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
    48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49
}
Map each frequency coefficient bin to the critical band that contains it.
Definition at line 46 of file ac3.c.
Referenced by ac3_bit_alloc_calc_bap_c(), ff_ac3_bit_alloc_calc_mask(), and ff_ac3_bit_alloc_calc_psd().