FFmpeg: libavcodec/ac3_parser.h File Reference
ac3_parser.h File Reference
#include "ac3.h"
#include "get_bits.h"
Functions
int avpriv_ac3_parse_header (GetBitContext *gbc, AC3HeaderInfo **hdr)
Parse AC-3 frame header.
Function Documentation
avpriv_ac3_parse_header()
int avpriv_ac3_parse_header (GetBitContext * gbc, AC3HeaderInfo ** hdr)
Parse AC-3 frame header.
Parse the header up to the lfeon element, which is the first 52 or 54 bits depending on the audio coding mode.
Parameters
[in] gbc BitContext containing the first 54 bits of the frame.
[out] hdr Pointer to Pointer to struct where header info is written. will be allocated if NULL
Returns
Returns 0 on success, -1 if there is a sync word mismatch, -2 if the bsid (version) element is invalid, -3 if the fscod (sample rate) element is invalid, or -4 if the frmsizecod (bit rate) element is invalid.
Definition at line 50 of file ac3_parser.c.
Referenced by ac3_eac3_probe(), ac3_sync(), ffat_create_decoder(), and parse_frame_header().