FFmpeg: libavcodec/ac3dsp.h File Reference
ac3dsp.h File Reference
#include <stdint.h>
Data Structures
struct AC3DSPContext
Functions
void ff_ac3dsp_init (AC3DSPContext *c, int bit_exact)
void ff_ac3dsp_init_arm (AC3DSPContext *c, int bit_exact)
void ff_ac3dsp_init_x86 (AC3DSPContext *c, int bit_exact)
void ff_ac3dsp_init_mips (AC3DSPContext *c, int bit_exact)
Variables
const uint16_t ff_ac3_bap_bits [16]
Number of mantissa bits written for each bap value.
Function Documentation
ff_ac3dsp_init()
void ff_ac3dsp_init (AC3DSPContext * c, int bit_exact)
Definition at line 279 of file ac3dsp.c.
Referenced by ac3_decode_init(), and ff_ac3_encode_init().
ff_ac3dsp_init_arm()
void ff_ac3dsp_init_arm (AC3DSPContext * c, int bit_exact)
Definition at line 52 of file ac3dsp_init_arm.c.
Referenced by ff_ac3dsp_init().
ff_ac3dsp_init_x86()
void ff_ac3dsp_init_x86 (AC3DSPContext * c, int bit_exact)
Definition at line 198 of file ac3dsp_init.c.
Referenced by ff_ac3dsp_init().
ff_ac3dsp_init_mips()
void ff_ac3dsp_init_mips (AC3DSPContext * c, int bit_exact)
Definition at line 403 of file ac3dsp_mips.c.
Referenced by ff_ac3dsp_init().
Variable Documentation
ff_ac3_bap_bits
const uint16_t ff_ac3_bap_bits[16]
Number of mantissa bits written for each bap value.
bap values with fractional bits are set to 0 and are calculated separately.
Definition at line 140 of file ac3dsp.c.
Referenced by ac3_compute_mantissa_size_c().