FFmpeg: libavcodec/ac3enc_template.c File Reference
ac3enc_template.c File Reference
AC-3 encoder float/fixed template.
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/internal.h"
#include "audiodsp.h"
#include "internal.h"
#include "ac3enc.h"
#include "eac3enc.h"
Functions
static void scale_coefficients (AC3EncodeContext *s)
static int normalize_samples (AC3EncodeContext *s)
static void clip_coefficients (AudioDSPContext *adsp, CoefType *coef, unsigned int len)
static CoefType calc_cpl_coord (CoefSumType energy_ch, CoefSumType energy_cpl)
static void sum_square_butterfly (AC3EncodeContext *s, CoefSumType sum[4], const CoefType *coef0, const CoefType *coef1, int len)
int AC3_NAME() allocate_sample_buffers (AC3EncodeContext *s)
static void copy_input_samples (AC3EncodeContext *s, SampleType **samples)
static void apply_mdct (AC3EncodeContext *s)
static void apply_channel_coupling (AC3EncodeContext *s)
static void compute_rematrixing_strategy (AC3EncodeContext *s)
int AC3_NAME() encode_frame (AVCodecContext *avctx, AVPacket *avpkt, const AVFrame *frame, int *got_packet_ptr)
Detailed Description
AC-3 encoder float/fixed template.
Definition in file ac3enc_template.c.
Function Documentation
scale_coefficients()
static void scale_coefficients (AC3EncodeContext * s) static
Referenced by encode_frame().
normalize_samples()
static int normalize_samples (AC3EncodeContext * s) static
Referenced by apply_mdct().
clip_coefficients()
static void clip_coefficients (AudioDSPContext * adsp, CoefType * coef, unsigned int len) static
Referenced by apply_channel_coupling(), and encode_frame().
calc_cpl_coord()
static CoefType calc_cpl_coord (CoefSumType energy_ch, CoefSumType energy_cpl) static
Referenced by apply_channel_coupling().
sum_square_butterfly()
static void sum_square_butterfly (AC3EncodeContext * s, CoefSumType sum[4], const CoefType * coef0, const CoefType * coef1, int len) static
Referenced by compute_rematrixing_strategy().
allocate_sample_buffers()
int AC3_NAME() allocate_sample_buffers (AC3EncodeContext * s)
Definition at line 54 of file ac3enc_template.c.
copy_input_samples()
static void copy_input_samples (AC3EncodeContext * s, SampleType ** samples) static
Definition at line 78 of file ac3enc_template.c.
Referenced by encode_frame().
apply_mdct()
static void apply_mdct (AC3EncodeContext * s) static
Definition at line 101 of file ac3enc_template.c.
Referenced by encode_frame().
apply_channel_coupling()
static void apply_channel_coupling (AC3EncodeContext * s) static
Definition at line 131 of file ac3enc_template.c.
Referenced by encode_frame().
compute_rematrixing_strategy()
static void compute_rematrixing_strategy (AC3EncodeContext * s) static
Definition at line 339 of file ac3enc_template.c.
Referenced by encode_frame().
encode_frame()
int AC3_NAME() encode_frame (AVCodecContext * avctx, AVPacket * avpkt, const AVFrame * frame, int * got_packet_ptr)
Definition at line 391 of file ac3enc_template.c.