FFmpeg: libavcodec/acelp_filters.h File Reference
acelp_filters.h File Reference
#include <stdint.h>
Data Structures
struct ACELPFContext
Functions
void ff_acelp_filter_init (ACELPFContext *c)
Initialize ACELPFContext.
void ff_acelp_filter_init_mips (ACELPFContext *c)
void ff_acelp_interpolate (int16_t *out, const int16_t *in, const int16_t *filter_coeffs, int precision, int frac_pos, int filter_length, int length)
Generic FIR interpolation routine.
void ff_acelp_interpolatef (float *out, const float *in, const float *filter_coeffs, int precision, int frac_pos, int filter_length, int length)
Floating point version of ff_acelp_interpolate()
void ff_acelp_high_pass_filter (int16_t *out, int hpf_f[2], const int16_t *in, int length)
high-pass filtering and upscaling (4.2.5 of G.729).
void ff_acelp_apply_order_2_transfer_function (float *out, const float *in, const float zero_coeffs[2], const float pole_coeffs[2], float gain, float mem[2], int n)
Apply an order 2 rational transfer function in-place.
void ff_tilt_compensation (float *mem, float tilt, float *samples, int size)
Apply tilt compensation filter, 1 - tilt * z-1.
Variables
const int16_t ff_acelp_interp_filter [61]
low-pass Finite Impulse Response filter coefficients.
Function Documentation
ff_acelp_filter_init()
void ff_acelp_filter_init (ACELPFContext * c)
Initialize ACELPFContext.
Definition at line 148 of file acelp_filters.c.
Referenced by amrnb_decode_init(), and amrwb_decode_init().
ff_acelp_filter_init_mips()
void ff_acelp_filter_init_mips (ACELPFContext * c)
Definition at line 213 of file acelp_filters_mips.c.
Referenced by ff_acelp_filter_init().
ff_acelp_interpolate()
void ff_acelp_interpolate (int16_t * out, const int16_t * in, const int16_t * filter_coeffs, int precision, int frac_pos, int filter_length, int length)
Generic FIR interpolation routine.
Parameters
[out] out buffer for interpolated data
in input data
filter_coeffs interpolation filter coefficients (0.15)
precision sub sample factor, that is the precision of the position
frac_pos fractional part of position [0..precision-1]
filter_length filter length
length length of output
filter_coeffs contains coefficients of the right half of the symmetric interpolation filter. filter_coeffs[0] should the central (unpaired) coefficient. See ff_acelp_interp_filter for an example.
Definition at line 44 of file acelp_filters.c.
Referenced by decode_frame(), and long_term_filter().
ff_acelp_interpolatef()
void ff_acelp_interpolatef (float * out, const float * in, const float * filter_coeffs, int precision, int frac_pos, int filter_length, int length)
Floating point version of ff_acelp_interpolate()
Definition at line 78 of file acelp_filters.c.
Referenced by decode_frame(), ff_acelp_filter_init(), ff_sipr_decode_frame_16k(), and synth_block_fcb_acb().
ff_acelp_high_pass_filter()
void ff_acelp_high_pass_filter (int16_t * out, int hpf_f[2], const int16_t * in, int length)
high-pass filtering and upscaling (4.2.5 of G.729).
Parameters
[out] out output buffer for filtered speech data
[in,out] hpf_f past filtered data from previous (2 items long) frames (-0x20000000 <= (14.13) < 0x20000000)
in speech data to process
length input data size
out[i] = 0.93980581 * in[i] - 1.8795834 * in[i-1] + 0.93980581 * in[i-2] + 1.9330735 * out[i-1] - 0.93589199 * out[i-2]
The filter has a cut-off frequency of 1/80 of the sampling freq
Note
Two items before the top of the in buffer must contain two items from the tail of the previous subframe.
Remarks
It is safe to pass the same array in in and out parameters.
AMR uses mostly the same filter (cut-off frequency 60Hz, same formula, but constants differs in 5th sign after comma). Fortunately in fixed-point all coefficients are the same as in G.729. Thus this routine can be used for the fixed-point AMR decoder, too.
Definition at line 99 of file acelp_filters.c.
Referenced by decode_frame().
ff_acelp_apply_order_2_transfer_function()
void ff_acelp_apply_order_2_transfer_function (float * out, const float * in, const float zero_coeffs[2], const float pole_coeffs[2], float gain, float mem[2], int n)
Apply an order 2 rational transfer function in-place.
Parameters
out output buffer for filtered speech samples
in input buffer containing speech data (may be the same as out)
zero_coeffs z^-1 and z^-2 coefficients of the numerator
pole_coeffs z^-1 and z^-2 coefficients of the denominator
gain scale factor for final output
mem intermediate values used by filter (should be 0 initially)
n number of samples
Definition at line 119 of file acelp_filters.c.
Referenced by decode_frame(), ff_acelp_filter_init(), and postfilter().
ff_tilt_compensation()
void ff_tilt_compensation (float * mem, float tilt, float * samples, int size)
Apply tilt compensation filter, 1 - tilt * z-1.
Parameters
mem pointer to the filter's state (one single float)
tilt tilt factor
samples array where the filter is applied
size the size of the samples array
Definition at line 136 of file acelp_filters.c.
Referenced by calc_input_response(), postfilter(), postfilter_5k0(), and wiener_denoise().
Variable Documentation
ff_acelp_interp_filter
const int16_t ff_acelp_interp_filter[61]
low-pass Finite Impulse Response filter coefficients.
Hamming windowed sinc filter with cutoff freq 3/40 of the sampling freq, the coefficients are scaled by 2^15. This array only contains the right half of the filter. This filter is likely identical to the one used in G.729, though this could not be determined from the original comments with certainty.
Definition at line 30 of file acelp_filters.c.
Referenced by decode_frame().