FFmpeg: libavcodec/adpcm.c File Reference
adpcm.c File Reference
ADPCM decoders Features and limitations:
#include "avcodec.h"
#include "get_bits.h"
#include "bytestream.h"
#include "adpcm.h"
#include "adpcm_data.h"
#include "internal.h"
Data Structures
struct ADPCMDecodeContext
Macros
#define DK3_GET_NEXT_NIBBLE()
#define THP_GET16(g)
#define ADPCM_DECODER(id_, sample_fmts_, name_, long_name_)
Functions
static av_cold int adpcm_decode_init (AVCodecContext *avctx)
static int16_t adpcm_ima_expand_nibble (ADPCMChannelStatus *c, int8_t nibble, int shift)
static int16_t adpcm_ima_wav_expand_nibble (ADPCMChannelStatus *c, GetBitContext *gb, int bps)
static int adpcm_ima_qt_expand_nibble (ADPCMChannelStatus *c, int nibble, int shift)
static int16_t adpcm_ms_expand_nibble (ADPCMChannelStatus *c, int nibble)
static int16_t adpcm_ima_oki_expand_nibble (ADPCMChannelStatus *c, int nibble)
static int16_t adpcm_ct_expand_nibble (ADPCMChannelStatus *c, int8_t nibble)
static int16_t adpcm_sbpro_expand_nibble (ADPCMChannelStatus *c, int8_t nibble, int size, int shift)
static int16_t adpcm_yamaha_expand_nibble (ADPCMChannelStatus *c, uint8_t nibble)
static int16_t adpcm_mtaf_expand_nibble (ADPCMChannelStatus *c, uint8_t nibble)
static int xa_decode (AVCodecContext *avctx, int16_t *out0, int16_t *out1, const uint8_t *in, ADPCMChannelStatus *left, ADPCMChannelStatus *right, int channels, int sample_offset)
static void adpcm_swf_decode (AVCodecContext *avctx, const uint8_t *buf, int buf_size, int16_t *samples)
static int get_nb_samples (AVCodecContext *avctx, GetByteContext *gb, int buf_size, int *coded_samples, int *approx_nb_samples)
Get the number of samples that will be decoded from the packet.
static int adpcm_decode_frame (AVCodecContext *avctx, void *data, int *got_frame_ptr, AVPacket *avpkt)
static void adpcm_flush (AVCodecContext *avctx)
ADPCM_DECODER (AV_CODEC_ID_ADPCM_4XM, sample_fmts_s16p, adpcm_4xm, "ADPCM 4X Movie")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_AFC, sample_fmts_s16p, adpcm_afc, "ADPCM Nintendo Gamecube AFC")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_AICA, sample_fmts_s16p, adpcm_aica, "ADPCM Yamaha AICA")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_CT, sample_fmts_s16, adpcm_ct, "ADPCM Creative Technology")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_DTK, sample_fmts_s16p, adpcm_dtk, "ADPCM Nintendo Gamecube DTK")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_EA, sample_fmts_s16, adpcm_ea, "ADPCM Electronic Arts")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_EA_MAXIS_XA, sample_fmts_s16, adpcm_ea_maxis_xa, "ADPCM Electronic Arts Maxis CDROM XA")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_EA_R1, sample_fmts_s16p, adpcm_ea_r1, "ADPCM Electronic Arts R1")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_EA_R2, sample_fmts_s16p, adpcm_ea_r2, "ADPCM Electronic Arts R2")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_EA_R3, sample_fmts_s16p, adpcm_ea_r3, "ADPCM Electronic Arts R3")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_EA_XAS, sample_fmts_s16p, adpcm_ea_xas, "ADPCM Electronic Arts XAS")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_AMV, sample_fmts_s16, adpcm_ima_amv, "ADPCM IMA AMV")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_APC, sample_fmts_s16, adpcm_ima_apc, "ADPCM IMA CRYO APC")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_DAT4, sample_fmts_s16, adpcm_ima_dat4, "ADPCM IMA Eurocom DAT4")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_DK3, sample_fmts_s16, adpcm_ima_dk3, "ADPCM IMA Duck DK3")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_DK4, sample_fmts_s16, adpcm_ima_dk4, "ADPCM IMA Duck DK4")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_EA_EACS, sample_fmts_s16, adpcm_ima_ea_eacs, "ADPCM IMA Electronic Arts EACS")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_EA_SEAD, sample_fmts_s16, adpcm_ima_ea_sead, "ADPCM IMA Electronic Arts SEAD")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_ISS, sample_fmts_s16, adpcm_ima_iss, "ADPCM IMA Funcom ISS")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_OKI, sample_fmts_s16, adpcm_ima_oki, "ADPCM IMA Dialogic OKI")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_QT, sample_fmts_s16p, adpcm_ima_qt, "ADPCM IMA QuickTime")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_RAD, sample_fmts_s16, adpcm_ima_rad, "ADPCM IMA Radical")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_SMJPEG, sample_fmts_s16, adpcm_ima_smjpeg, "ADPCM IMA Loki SDL MJPEG")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_WAV, sample_fmts_s16p, adpcm_ima_wav, "ADPCM IMA WAV")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_WS, sample_fmts_both, adpcm_ima_ws, "ADPCM IMA Westwood")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_MS, sample_fmts_s16, adpcm_ms, "ADPCM Microsoft")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_MTAF, sample_fmts_s16p, adpcm_mtaf, "ADPCM MTAF")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_PSX, sample_fmts_s16p, adpcm_psx, "ADPCM Playstation")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_SBPRO_2, sample_fmts_s16, adpcm_sbpro_2, "ADPCM Sound Blaster Pro 2-bit")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_SBPRO_3, sample_fmts_s16, adpcm_sbpro_3, "ADPCM Sound Blaster Pro 2.6-bit")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_SBPRO_4, sample_fmts_s16, adpcm_sbpro_4, "ADPCM Sound Blaster Pro 4-bit")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_SWF, sample_fmts_s16, adpcm_swf, "ADPCM Shockwave Flash")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_THP_LE, sample_fmts_s16p, adpcm_thp_le, "ADPCM Nintendo THP (little-endian)")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_THP, sample_fmts_s16p, adpcm_thp, "ADPCM Nintendo THP")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_XA, sample_fmts_s16p, adpcm_xa, "ADPCM CDROM XA")
ADPCM_DECODER (AV_CODEC_ID_ADPCM_YAMAHA, sample_fmts_s16, adpcm_yamaha, "ADPCM Yamaha")
Variables
static const int xa_adpcm_table [5][2]
static const int ea_adpcm_table []
static const int swf_index_tables [4][16]
static enum AVSampleFormat sample_fmts_s16 []
static enum AVSampleFormat sample_fmts_s16p []
static enum AVSampleFormat sample_fmts_both []
Detailed Description
ADPCM decoders Features and limitations:
Reference documents: http://wiki.multimedia.cx/index.php?title=Category:ADPCM_Audio_Codecs http://www.pcisys.net/~melanson/codecs/simpleaudio.html [dead] http://www.geocities.com/SiliconValley/8682/aud3.txt [dead] http://openquicktime.sourceforge.net/ XAnim sources (xa_codec.c) http://xanim.polter.net/ http://www.cs.ucla.edu/~leec/mediabench/applications.html [dead] SoX source code http://sox.sourceforge.net/
CD-ROM XA: http://ku-www.ss.titech.ac.jp/~yatsushi/xaadpcm.html [dead] vagpack & depack http://homepages.compuserve.de/bITmASTER32/psx-index.html [dead] readstr http://www.geocities.co.jp/Playtown/2004/
Definition in file adpcm.c.
Macro Definition Documentation
DK3_GET_NEXT_NIBBLE
#define DK3_GET_NEXT_NIBBLE ()
Value:
if (decode_top_nibble_next) { \
        nibble = last_byte >> 4; \
        decode_top_nibble_next = 0; \
    } else { \
        last_byte = bytestream2_get_byteu(&gb); \
        nibble = last_byte & 0x0F; \
        decode_top_nibble_next = 1; \
    }
Referenced by adpcm_decode_frame().
THP_GET16
#define THP_GET16 (g)
Value:
sign_extend(\
        avctx->codec->id == AV_CODEC_ID_ADPCM_THP_LE ? \
        bytestream2_get_le16u(&(g)) : \
        bytestream2_get_be16u(&(g)), 16)
Referenced by adpcm_decode_frame().
ADPCM_DECODER
#define ADPCM_DECODER (id_, sample_fmts_, name_, long_name_)
Value:
AVCodec ff_ ## name_ ## _decoder = {                        \
    .name           = #name_,                               \
    .long_name      = NULL_IF_CONFIG_SMALL(long_name_),     \
    .type           = AVMEDIA_TYPE_AUDIO,                   \
    .id             = id_,                                  \
    .priv_data_size = sizeof(ADPCMDecodeContext),           \
    .init           = adpcm_decode_init,                    \
    .decode         = adpcm_decode_frame,                   \
    .flush          = adpcm_flush,                          \
    .capabilities   = AV_CODEC_CAP_DR1,                     \
    .sample_fmts    = sample_fmts_,                         \
}
Definition at line 1708 of file adpcm.c.
Function Documentation
adpcm_decode_init()
static av_cold int adpcm_decode_init (AVCodecContext * avctx) static
Definition at line 92 of file adpcm.c.
adpcm_ima_expand_nibble()
static int16_t adpcm_ima_expand_nibble (ADPCMChannelStatus * c, int8_t nibble, int shift) inline static
Definition at line 180 of file adpcm.c.
Referenced by adpcm_decode_frame().
adpcm_ima_wav_expand_nibble()
static int16_t adpcm_ima_wav_expand_nibble (ADPCMChannelStatus * c, GetBitContext * gb, int bps) inline static
Definition at line 206 of file adpcm.c.
Referenced by adpcm_decode_frame().
adpcm_ima_qt_expand_nibble()
static int adpcm_ima_qt_expand_nibble (ADPCMChannelStatus * c, int nibble, int shift) inline static
Definition at line 229 of file adpcm.c.
Referenced by adpcm_decode_frame().
adpcm_ms_expand_nibble()
static int16_t adpcm_ms_expand_nibble (ADPCMChannelStatus * c, int nibble) inline static
Definition at line 255 of file adpcm.c.
Referenced by adpcm_decode_frame().
adpcm_ima_oki_expand_nibble()
static int16_t adpcm_ima_oki_expand_nibble (ADPCMChannelStatus * c, int nibble) inline static
Definition at line 274 of file adpcm.c.
Referenced by adpcm_decode_frame().
adpcm_ct_expand_nibble()
static int16_t adpcm_ct_expand_nibble (ADPCMChannelStatus * c, int8_t nibble) inline static
Definition at line 295 of file adpcm.c.
Referenced by adpcm_decode_frame().
adpcm_sbpro_expand_nibble()
static int16_t adpcm_sbpro_expand_nibble (ADPCMChannelStatus * c, int8_t nibble, int size, int shift) inline static
Definition at line 316 of file adpcm.c.
Referenced by adpcm_decode_frame().
adpcm_yamaha_expand_nibble()
static int16_t adpcm_yamaha_expand_nibble (ADPCMChannelStatus * c, uint8_t nibble) inline static
Definition at line 336 of file adpcm.c.
Referenced by adpcm_decode_frame().
adpcm_mtaf_expand_nibble()
static int16_t adpcm_mtaf_expand_nibble (ADPCMChannelStatus * c, uint8_t nibble) inline static
Definition at line 350 of file adpcm.c.
Referenced by adpcm_decode_frame().
xa_decode()
static int xa_decode (AVCodecContext * avctx, int16_t * out0, int16_t * out1, const uint8_t * in, ADPCMChannelStatus * left, ADPCMChannelStatus * right, int channels, int sample_offset) static
Definition at line 359 of file adpcm.c.
Referenced by adpcm_decode_frame().
adpcm_swf_decode()
static void adpcm_swf_decode (AVCodecContext * avctx, const uint8_t * buf, int buf_size, int16_t * samples) static
Definition at line 439 of file adpcm.c.
Referenced by adpcm_decode_frame().
get_nb_samples()
static int get_nb_samples (AVCodecContext * avctx, GetByteContext * gb, int buf_size, int * coded_samples, int * approx_nb_samples) static
Get the number of samples that will be decoded from the packet.
In one case, this is actually the maximum number of samples possible to decode with the given buf_size.
Parameters
[out] coded_samples set to the number of samples as coded in the packet, or 0 if the codec does not encode the number of samples in each frame.
[out] approx_nb_samples set to non-zero if the number of samples returned is an approximation.
Definition at line 507 of file adpcm.c.
Referenced by adpcm_decode_frame().
adpcm_decode_frame()
static int adpcm_decode_frame (AVCodecContext * avctx, void * data, int * got_frame_ptr, AVPacket * avpkt) static
Definition at line 708 of file adpcm.c.
adpcm_flush()
static void adpcm_flush (AVCodecContext * avctx) static
Definition at line 1693 of file adpcm.c.
ADPCM_DECODER() [1/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_4XM , sample_fmts_s16p , adpcm_4xm , "ADPCM 4X Movie")
ADPCM_DECODER() [2/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_AFC , sample_fmts_s16p , adpcm_afc , "ADPCM Nintendo Gamecube AFC")
ADPCM_DECODER() [3/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_AICA , sample_fmts_s16p , adpcm_aica , "ADPCM Yamaha AICA")
ADPCM_DECODER() [4/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_CT , sample_fmts_s16 , adpcm_ct , "ADPCM Creative Technology")
ADPCM_DECODER() [5/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_DTK , sample_fmts_s16p , adpcm_dtk , "ADPCM Nintendo Gamecube DTK")
ADPCM_DECODER() [6/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_EA , sample_fmts_s16 , adpcm_ea , "ADPCM Electronic Arts")
ADPCM_DECODER() [7/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_EA_MAXIS_XA , sample_fmts_s16 , adpcm_ea_maxis_xa , "ADPCM Electronic Arts Maxis CDROM XA")
ADPCM_DECODER() [8/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_EA_R1 , sample_fmts_s16p , adpcm_ea_r1 , "ADPCM Electronic Arts R1")
ADPCM_DECODER() [9/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_EA_R2 , sample_fmts_s16p , adpcm_ea_r2 , "ADPCM Electronic Arts R2")
ADPCM_DECODER() [10/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_EA_R3 , sample_fmts_s16p , adpcm_ea_r3 , "ADPCM Electronic Arts R3")
ADPCM_DECODER() [11/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_EA_XAS , sample_fmts_s16p , adpcm_ea_xas , "ADPCM Electronic Arts XAS")
ADPCM_DECODER() [12/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_AMV , sample_fmts_s16 , adpcm_ima_amv , "ADPCM IMA AMV")
ADPCM_DECODER() [13/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_APC , sample_fmts_s16 , adpcm_ima_apc , "ADPCM IMA CRYO APC")
ADPCM_DECODER() [14/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_DAT4 , sample_fmts_s16 , adpcm_ima_dat4 , "ADPCM IMA Eurocom DAT4")
ADPCM_DECODER() [15/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_DK3 , sample_fmts_s16 , adpcm_ima_dk3 , "ADPCM IMA Duck DK3")
ADPCM_DECODER() [16/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_DK4 , sample_fmts_s16 , adpcm_ima_dk4 , "ADPCM IMA Duck DK4")
ADPCM_DECODER() [17/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_EA_EACS , sample_fmts_s16 , adpcm_ima_ea_eacs , "ADPCM IMA Electronic Arts EACS")
ADPCM_DECODER() [18/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_EA_SEAD , sample_fmts_s16 , adpcm_ima_ea_sead , "ADPCM IMA Electronic Arts SEAD")
ADPCM_DECODER() [19/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_ISS , sample_fmts_s16 , adpcm_ima_iss , "ADPCM IMA Funcom ISS")
ADPCM_DECODER() [20/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_OKI , sample_fmts_s16 , adpcm_ima_oki , "ADPCM IMA Dialogic OKI")
ADPCM_DECODER() [21/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_QT , sample_fmts_s16p , adpcm_ima_qt , "ADPCM IMA QuickTime")
ADPCM_DECODER() [22/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_RAD , sample_fmts_s16 , adpcm_ima_rad , "ADPCM IMA Radical")
ADPCM_DECODER() [23/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_SMJPEG , sample_fmts_s16 , adpcm_ima_smjpeg , "ADPCM IMA Loki SDL MJPEG")
ADPCM_DECODER() [24/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_WAV , sample_fmts_s16p , adpcm_ima_wav , "ADPCM IMA WAV")
ADPCM_DECODER() [25/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_IMA_WS , sample_fmts_both , adpcm_ima_ws , "ADPCM IMA Westwood")
ADPCM_DECODER() [26/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_MS , sample_fmts_s16 , adpcm_ms , "ADPCM Microsoft")
ADPCM_DECODER() [27/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_MTAF , sample_fmts_s16p , adpcm_mtaf , "ADPCM MTAF")
ADPCM_DECODER() [28/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_PSX , sample_fmts_s16p , adpcm_psx , "ADPCM Playstation")
ADPCM_DECODER() [29/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_SBPRO_2 , sample_fmts_s16 , adpcm_sbpro_2 , "ADPCM Sound Blaster Pro 2-bit")
ADPCM_DECODER() [30/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_SBPRO_3 , sample_fmts_s16 , adpcm_sbpro_3 , "ADPCM Sound Blaster Pro 2.6-bit")
ADPCM_DECODER() [31/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_SBPRO_4 , sample_fmts_s16 , adpcm_sbpro_4 , "ADPCM Sound Blaster Pro 4-bit")
ADPCM_DECODER() [32/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_SWF , sample_fmts_s16 , adpcm_swf , "ADPCM Shockwave Flash")
ADPCM_DECODER() [33/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_THP_LE , sample_fmts_s16p , adpcm_thp_le , "ADPCM Nintendo THP (little-endian)")
ADPCM_DECODER() [34/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_THP , sample_fmts_s16p , adpcm_thp , "ADPCM Nintendo THP")
ADPCM_DECODER() [35/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_XA , sample_fmts_s16p , adpcm_xa , "ADPCM CDROM XA")
ADPCM_DECODER() [36/36]
ADPCM_DECODER (AV_CODEC_ID_ADPCM_YAMAHA , sample_fmts_s16 , adpcm_yamaha , "ADPCM Yamaha")
Variable Documentation
xa_adpcm_table
const int xa_adpcm_table[5][2] static
Initial value:
= {
    {   0,   0 },
    {  60,   0 },
    { 115, -52 },
    {  98, -55 },
    { 122, -60 }
}
Definition at line 60 of file adpcm.c.
Referenced by adpcm_decode_frame(), and xa_decode().
ea_adpcm_table
const int ea_adpcm_table[] static
Initial value:
= {
    0,  240,  460,  392,
    0,    0, -208, -220,
    0,    1,    3,    4,
    7,    8,   10,   11,
    0,   -1,   -3,   -4
}
Definition at line 68 of file adpcm.c.
Referenced by adpcm_decode_frame().
swf_index_tables
const int swf_index_tables[4][16] static
Initial value:
= {
     { -1, 2 },
     { -1, -1, 2, 4 },
     { -1, -1, -1, -1, 2, 4, 6, 8 },
     { -1, -1, -1, -1, -1, -1, -1, -1, 1, 2, 4, 6, 8, 10, 13, 16 }
}
Definition at line 77 of file adpcm.c.
Referenced by adpcm_swf_decode().
sample_fmts_s16
enum AVSampleFormat sample_fmts_s16[] static
Initial value:
= { AV_SAMPLE_FMT_S16,
                                                        AV_SAMPLE_FMT_NONE }
Definition at line 1700 of file adpcm.c.
sample_fmts_s16p
enum AVSampleFormat sample_fmts_s16p[] static
Initial value:
= { AV_SAMPLE_FMT_S16P,
                                                        AV_SAMPLE_FMT_NONE }
Definition at line 1702 of file adpcm.c.
sample_fmts_both
enum AVSampleFormat sample_fmts_both[] static
Initial value:
= { AV_SAMPLE_FMT_S16,
                                                        AV_SAMPLE_FMT_S16P,
                                                        AV_SAMPLE_FMT_NONE }
Definition at line 1704 of file adpcm.c.