FFmpeg: libavutil/aes_ctr.c File Reference
aes_ctr.c File Reference
#include "common.h"
#include "aes_ctr.h"
#include "aes.h"
#include "random_seed.h"
Data Structures
struct AVAESCTR
Macros
#define AES_BLOCK_SIZE (16)
Functions
struct AVAESCTR * av_aes_ctr_alloc (void)
Allocate an AVAESCTR context.
void av_aes_ctr_set_iv (struct AVAESCTR *a, const uint8_t *iv)
Forcefully change the iv.
const uint8_t * av_aes_ctr_get_iv (struct AVAESCTR *a)
Get the current iv.
void av_aes_ctr_set_random_iv (struct AVAESCTR *a)
Generate a random iv.
int av_aes_ctr_init (struct AVAESCTR *a, const uint8_t *key)
Initialize an AVAESCTR context.
void av_aes_ctr_free (struct AVAESCTR *a)
Release an AVAESCTR context.
static void av_aes_ctr_increment_be64 (uint8_t *counter)
void av_aes_ctr_increment_iv (struct AVAESCTR *a)
Increment the top 64 bit of the iv (performed after each frame)
void av_aes_ctr_crypt (struct AVAESCTR *a, uint8_t *dst, const uint8_t *src, int count)
Process a buffer using a previously initialized context.
Macro Definition Documentation
AES_BLOCK_SIZE
#define AES_BLOCK_SIZE (16)
Definition at line 27 of file aes_ctr.c.
Referenced by av_aes_ctr_crypt().
Function Documentation
av_aes_ctr_alloc()
struct AVAESCTR* av_aes_ctr_alloc (void)
Allocate an AVAESCTR context.
Definition at line 36 of file aes_ctr.c.
Referenced by ff_mov_cenc_init(), and mov_read_senc().
av_aes_ctr_set_iv()
void av_aes_ctr_set_iv (struct AVAESCTR * a, const uint8_t * iv)
Forcefully change the iv.
Definition at line 41 of file aes_ctr.c.
Referenced by av_aes_ctr_set_random_iv(), and cenc_filter().
av_aes_ctr_get_iv()
const uint8_t* av_aes_ctr_get_iv (struct AVAESCTR * a)
Get the current iv.
Definition at line 48 of file aes_ctr.c.
Referenced by mov_cenc_start_packet().
av_aes_ctr_set_random_iv()
void av_aes_ctr_set_random_iv (struct AVAESCTR * a)
Generate a random iv.
Definition at line 53 of file aes_ctr.c.
Referenced by ff_mov_cenc_init().
av_aes_ctr_init()
int av_aes_ctr_init (struct AVAESCTR * a, const uint8_t * key)
Initialize an AVAESCTR context.
Parameters
key encryption key, must have a length of AES_CTR_KEY_SIZE
Definition at line 63 of file aes_ctr.c.
Referenced by ff_mov_cenc_init(), and mov_read_senc().
av_aes_ctr_free()
void av_aes_ctr_free (struct AVAESCTR * a)
Release an AVAESCTR context.
Definition at line 78 of file aes_ctr.c.
Referenced by ff_mov_cenc_free(), and mov_read_close().
av_aes_ctr_increment_be64()
static void av_aes_ctr_increment_be64 (uint8_t * counter) static
Definition at line 86 of file aes_ctr.c.
Referenced by av_aes_ctr_crypt(), and av_aes_ctr_increment_iv().
av_aes_ctr_increment_iv()
void av_aes_ctr_increment_iv (struct AVAESCTR * a)
Increment the top 64 bit of the iv (performed after each frame)
Definition at line 98 of file aes_ctr.c.
Referenced by mov_cenc_end_packet().
av_aes_ctr_crypt()
void av_aes_ctr_crypt (struct AVAESCTR * a, uint8_t * dst, const uint8_t * src, int size)
Process a buffer using a previously initialized context.
Parameters
dst destination array, can be equal to src
src source array, can be equal to dst
size the size of src and dst
Definition at line 105 of file aes_ctr.c.
Referenced by cenc_filter(), and mov_cenc_write_encrypted().