FFmpeg: libavutil/aes.c File Reference
aes.c File Reference
#include "common.h"
#include "aes.h"
#include "aes_internal.h"
#include "intreadwrite.h"
#include "timer.h"
Macros
#define ROT(x, s) (((x) << (s)) | ((x) >> (32-(s))))
Functions
struct AVAES * av_aes_alloc (void)
Allocate an AVAES context.
static void addkey (av_aes_block *dst, const av_aes_block *src, const av_aes_block *round_key)
static void addkey_s (av_aes_block *dst, const uint8_t *src, const av_aes_block *round_key)
static void addkey_d (uint8_t *dst, const av_aes_block *src, const av_aes_block *round_key)
static void subshift (av_aes_block s0[2], int s, const uint8_t *box)
static int mix_core (uint32_t multbl[][256], int a, int b, int c, int d)
static void mix (av_aes_block state[2], uint32_t multbl[][256], int s1, int s3)
static void aes_crypt (AVAES *a, int s, const uint8_t *sbox, uint32_t multbl[][256])
static void aes_encrypt (AVAES *a, uint8_t *dst, const uint8_t *src, int count, uint8_t *iv, int rounds)
static void aes_decrypt (AVAES *a, uint8_t *dst, const uint8_t *src, int count, uint8_t *iv, int rounds)
void av_aes_crypt (AVAES *a, uint8_t *dst, const uint8_t *src, int count, uint8_t *iv, int decrypt)
Encrypt or decrypt a buffer using a previously initialized context.
static void init_multbl2 (uint32_t tbl[][256], const int c[4], const uint8_t *log8, const uint8_t *alog8, const uint8_t *sbox)
int av_aes_init (AVAES *a, const uint8_t *key, int key_bits, int decrypt)
Initialize an AVAES context.
Variables
const int av_aes_size = sizeof(AVAES)
static const uint8_t rcon [10]
static uint8_t sbox [256]
static uint8_t inv_sbox [256]
static uint32_t enc_multbl [4][256]
static uint32_t dec_multbl [4][256]
Macro Definition Documentation
ROT
#define ROT (x, s) (((x) << (s)) | ((x) >> (32-(s))))
Definition at line 53 of file aes.c.
Referenced by init_multbl2(), and mix_core().
Function Documentation
addkey()
static void addkey (av_aes_block * dst, const av_aes_block * src, const av_aes_block * round_key) inline static
Definition at line 56 of file aes.c.
Referenced by aes_crypt().
addkey_s()
static void addkey_s (av_aes_block * dst, const uint8_t * src, const av_aes_block * round_key) inline static
Definition at line 63 of file aes.c.
Referenced by aes_decrypt(), and aes_encrypt().
addkey_d()
static void addkey_d (uint8_t * dst, const av_aes_block * src, const av_aes_block * round_key) inline static
Definition at line 70 of file aes.c.
Referenced by aes_decrypt(), and aes_encrypt().
subshift()
static void subshift (av_aes_block s0[2], int s, const uint8_t * box) static
Definition at line 77 of file aes.c.
Referenced by aes_crypt(), and av_aes_init().
mix_core()
static int mix_core (uint32_t multbl[][256], int a, int b, int c, int d) inline static
Definition at line 100 of file aes.c.
Referenced by mix().
mix()
static void mix (av_aes_block state[2], uint32_t multbl[][256], int s1, int s3) inline static
Definition at line 109 of file aes.c.
Referenced by aes_crypt(), and av_aes_init().
aes_crypt()
static void aes_crypt (AVAES * a, int s, const uint8_t * sbox, uint32_t multbl[][256]) inline static
Definition at line 118 of file aes.c.
Referenced by aes_decrypt(), and aes_encrypt().
aes_encrypt()
static void aes_encrypt (AVAES * a, uint8_t * dst, const uint8_t * src, int count, uint8_t * iv, int rounds) static
Definition at line 131 of file aes.c.
Referenced by av_aes_init().
aes_decrypt()
static void aes_decrypt (AVAES * a, uint8_t * dst, const uint8_t * src, int count, uint8_t * iv, int rounds) static
Definition at line 147 of file aes.c.
Referenced by av_aes_init().
init_multbl2()
static void init_multbl2 (uint32_t tbl[][256], const int c[4], const uint8_t * log8, const uint8_t * alog8, const uint8_t * sbox) static
Definition at line 169 of file aes.c.
Referenced by av_aes_init().
Variable Documentation
rcon
const uint8_t rcon[10] static
Initial value:
= {
    0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80, 0x1b, 0x36
}
Definition at line 36 of file aes.c.
Referenced by av_aes_init().
sbox
uint8_t sbox[256] static
Definition at line 40 of file aes.c.
Referenced by aes_encrypt(), and av_aes_init().
inv_sbox
uint8_t inv_sbox[256] static
Definition at line 41 of file aes.c.
Referenced by aes_decrypt(), and av_aes_init().
enc_multbl
uint32_t enc_multbl[4][256] static
Definition at line 46 of file aes.c.
Referenced by aes_encrypt(), and av_aes_init().
dec_multbl
uint32_t dec_multbl[4][256] static
Definition at line 47 of file aes.c.
Referenced by aes_decrypt(), and av_aes_init().