FFmpeg: libavfilter/af_join.c File Reference
af_join.c File Reference
Audio join filter.
#include "libavutil/avassert.h"
#include "libavutil/channel_layout.h"
#include "libavutil/common.h"
#include "libavutil/opt.h"
#include "audio.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
Data Structures
struct ChannelMap
struct JoinContext
Macros
#define OFFSET(x) offsetof(JoinContext, x)
#define A AV_OPT_FLAG_AUDIO_PARAM
#define F AV_OPT_FLAG_FILTERING_PARAM
#define PARSE_CHANNEL(str, var, inout)
Functions
AVFILTER_DEFINE_CLASS (join)
static int try_push_frame (AVFilterContext *ctx)
static int filter_frame (AVFilterLink *link, AVFrame *frame)
static int parse_maps (AVFilterContext *ctx)
static av_cold int join_init (AVFilterContext *ctx)
static av_cold void join_uninit (AVFilterContext *ctx)
static int join_query_formats (AVFilterContext *ctx)
static void guess_map_matching (AVFilterContext *ctx, ChannelMap *ch, uint64_t *inputs)
static void guess_map_any (AVFilterContext *ctx, ChannelMap *ch, uint64_t *inputs)
static int join_config_output (AVFilterLink *outlink)
static int join_request_frame (AVFilterLink *outlink)
Variables
static const AVOption join_options []
static const AVFilterPad avfilter_af_join_outputs []
AVFilter ff_af_join
Detailed Description
Audio join filter.
Join multiple audio inputs as different channels in a single output
Definition in file af_join.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(JoinContext, x)
Definition at line 66 of file af_join.c.
A
#define A AV_OPT_FLAG_AUDIO_PARAM
Definition at line 67 of file af_join.c.
F
#define F AV_OPT_FLAG_FILTERING_PARAM
Definition at line 68 of file af_join.c.
PARSE_CHANNEL
#define PARSE_CHANNEL (str, var, inout)
Value:
if (!(var = av_get_channel_layout(str))) {                             \
            av_log(ctx, AV_LOG_ERROR, "Invalid " inout " channel: %s.\n", str);\
            return AVERROR(EINVAL);                                            \
        }                                                                      \
        if (av_get_channel_layout_nb_channels(var) != 1) {                     \
            av_log(ctx, AV_LOG_ERROR, "Channel map describes more than one "   \
                   inout " channel.\n");                                       \
            return AVERROR(EINVAL);                                            \
        }
Referenced by parse_maps().
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (join)
try_push_frame()
static int try_push_frame (AVFilterContext * ctx) static
Definition at line 413 of file af_join.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * link, AVFrame * frame) static
Definition at line 83 of file af_join.c.
Referenced by join_init().
parse_maps()
static int parse_maps (AVFilterContext * ctx) static
Definition at line 109 of file af_join.c.
Referenced by join_init().
join_init()
static av_cold int join_init (AVFilterContext * ctx) static
Definition at line 196 of file af_join.c.
join_uninit()
static av_cold void join_uninit (AVFilterContext * ctx) static
Definition at line 241 of file af_join.c.
join_query_formats()
static int join_query_formats (AVFilterContext * ctx) static
Definition at line 256 of file af_join.c.
guess_map_matching()
static void guess_map_matching (AVFilterContext * ctx, ChannelMap * ch, uint64_t * inputs) static
Definition at line 279 of file af_join.c.
Referenced by join_config_output().
guess_map_any()
static void guess_map_any (AVFilterContext * ctx, ChannelMap * ch, uint64_t * inputs) static
Definition at line 297 of file af_join.c.
Referenced by join_config_output().
join_config_output()
static int join_config_output (AVFilterLink * outlink) static
Definition at line 316 of file af_join.c.
join_request_frame()
static int join_request_frame (AVFilterLink * outlink) static
Definition at line 398 of file af_join.c.
Variable Documentation
join_options
const AVOption join_options[] static
Initial value:
= {
    { "inputs",         "Number of input streams.", OFFSET(inputs),             AV_OPT_TYPE_INT,    { .i64 = 2 }, 1, INT_MAX,       A|F },
    { "channel_layout", "Channel layout of the "
                        "output stream.",           OFFSET(channel_layout_str), AV_OPT_TYPE_STRING, {.str = "stereo"}, 0, 0, A|F },
    { "map",            "A comma-separated list of channels maps in the format "
                        "'input_stream.input_channel-output_channel.",
                                                    OFFSET(map),                AV_OPT_TYPE_STRING,                 .flags = A|F },
    { NULL }
}
Definition at line 69 of file af_join.c.
avfilter_af_join_outputs
const AVFilterPad avfilter_af_join_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_AUDIO,
        .config_props  = join_config_output,
        .request_frame = join_request_frame,
    },
    { NULL }
}
Definition at line 516 of file af_join.c.
ff_af_join
AVFilter ff_af_join
Initial value:
= {
    .name           = "join",
    .description    = NULL_IF_CONFIG_SMALL("Join multiple audio streams into "
                                           "multi-channel output."),
    .priv_size      = sizeof(JoinContext),
    .priv_class     = &join_class,
    .init           = join_init,
    .uninit         = join_uninit,
    .query_formats  = join_query_formats,
    .inputs         = NULL,
    .outputs        = avfilter_af_join_outputs,
    .flags          = AVFILTER_FLAG_DYNAMIC_INPUTS,
}
Definition at line 526 of file af_join.c.