FFmpeg: libavfilter/af_channelmap.c File Reference
af_channelmap.c File Reference
audio channel mapping filter
#include <ctype.h>
#include "libavutil/avstring.h"
#include "libavutil/channel_layout.h"
#include "libavutil/common.h"
#include "libavutil/mathematics.h"
#include "libavutil/opt.h"
#include "libavutil/samplefmt.h"
#include "audio.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
Data Structures
struct ChannelMap
struct ChannelMapContext
Macros
#define MAX_CH 64
#define OFFSET(x) offsetof(ChannelMapContext, x)
#define A AV_OPT_FLAG_AUDIO_PARAM
#define F AV_OPT_FLAG_FILTERING_PARAM
Enumerations
enum MappingMode {
MAP_NONE, MAP_ONE_INT, MAP_ONE_STR, MAP_PAIR_INT_INT,
MAP_PAIR_INT_STR, MAP_PAIR_STR_INT, MAP_PAIR_STR_STR
}
Functions
AVFILTER_DEFINE_CLASS (channelmap)
static char * split (char *message, char delim)
static int get_channel_idx (char **map, int *ch, char delim, int max_ch)
static int get_channel (char **map, uint64_t *ch, char delim)
static av_cold int channelmap_init (AVFilterContext *ctx)
static int channelmap_query_formats (AVFilterContext *ctx)
static int channelmap_filter_frame (AVFilterLink *inlink, AVFrame *buf)
static int channelmap_config_input (AVFilterLink *inlink)
Variables
static const AVOption channelmap_options []
static const AVFilterPad avfilter_af_channelmap_inputs []
static const AVFilterPad avfilter_af_channelmap_outputs []
AVFilter ff_af_channelmap
Detailed Description
audio channel mapping filter
Definition in file af_channelmap.c.
Macro Definition Documentation
MAX_CH
#define MAX_CH 64
Definition at line 57 of file af_channelmap.c.
Referenced by channelmap_filter_frame(), and channelmap_init().
OFFSET
#define OFFSET (x) offsetof(ChannelMapContext, x)
Definition at line 68 of file af_channelmap.c.
A
#define A AV_OPT_FLAG_AUDIO_PARAM
Definition at line 69 of file af_channelmap.c.
F
#define F AV_OPT_FLAG_FILTERING_PARAM
Definition at line 70 of file af_channelmap.c.
Enumeration Type Documentation
MappingMode
enum MappingMode
Enumerator
MAP_NONE
MAP_ONE_INT
MAP_ONE_STR
MAP_PAIR_INT_INT
MAP_PAIR_INT_STR
MAP_PAIR_STR_INT
MAP_PAIR_STR_STR
Definition at line 47 of file af_channelmap.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (channelmap)
split()
static char* split (char * message, char delim) static
Definition at line 81 of file af_channelmap.c.
Referenced by arith2_get_scaled_value(), arith2_rescale_interval(), avfilter_register_all(), celt_decode_band(), dirac_unpack_block_motion_data(), encode_block(), get_channel(), get_channel_idx(), intra_prediction_unit(), main(), and mss4_decode_image_block().
get_channel_idx()
static int get_channel_idx (char ** map, int * ch, char delim, int max_ch) static
Definition at line 88 of file af_channelmap.c.
Referenced by channelmap_init().
get_channel()
static int get_channel (char ** map, uint64_t * ch, char delim) static
Definition at line 108 of file af_channelmap.c.
Referenced by channelmap_init().
channelmap_init()
static av_cold int channelmap_init (AVFilterContext * ctx) static
Definition at line 120 of file af_channelmap.c.
channelmap_query_formats()
static int channelmap_query_formats (AVFilterContext * ctx) static
Definition at line 287 of file af_channelmap.c.
channelmap_filter_frame()
static int channelmap_filter_frame (AVFilterLink * inlink, AVFrame * buf) static
Definition at line 314 of file af_channelmap.c.
channelmap_config_input()
static int channelmap_config_input (AVFilterLink * inlink) static
Definition at line 362 of file af_channelmap.c.
Variable Documentation
channelmap_options
const AVOption channelmap_options[] static
Initial value:
= {
    { "map", "A comma-separated list of input channel numbers in output order.",
          OFFSET(mapping_str),        AV_OPT_TYPE_STRING, .flags = A|F },
    { "channel_layout", "Output channel layout.",
          OFFSET(channel_layout_str), AV_OPT_TYPE_STRING, .flags = A|F },
    { NULL }
}
Definition at line 71 of file af_channelmap.c.
avfilter_af_channelmap_inputs
const AVFilterPad avfilter_af_channelmap_inputs[] static
Initial value:
= {
    {
        .name           = "default",
        .type           = AVMEDIA_TYPE_AUDIO,
        .filter_frame   = channelmap_filter_frame,
        .config_props   = channelmap_config_input,
        .needs_writable = 1,
    },
    { NULL }
}
Definition at line 399 of file af_channelmap.c.
avfilter_af_channelmap_outputs
const AVFilterPad avfilter_af_channelmap_outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_AUDIO
    },
    { NULL }
}
Definition at line 410 of file af_channelmap.c.
ff_af_channelmap
AVFilter ff_af_channelmap
Initial value:
= {
    .name          = "channelmap",
    .description   = NULL_IF_CONFIG_SMALL("Remap audio channels."),
    .init          = channelmap_init,
    .query_formats = channelmap_query_formats,
    .priv_size     = sizeof(ChannelMapContext),
    .priv_class    = &channelmap_class,
    .inputs        = avfilter_af_channelmap_inputs,
    .outputs       = avfilter_af_channelmap_outputs,
}
Definition at line 418 of file af_channelmap.c.