FFmpeg: libavfilter/af_astats.c File Reference
af_astats.c File Reference
#include <float.h>
#include "libavutil/opt.h"
#include "audio.h"
#include "avfilter.h"
#include "internal.h"
Data Structures
struct ChannelStats
struct AudioStatsContext
Macros
#define OFFSET(x) offsetof(AudioStatsContext, x)
#define FLAGS AV_OPT_FLAG_AUDIO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
#define LINEAR_TO_DB(x) (log10(x) * 20)
Functions
AVFILTER_DEFINE_CLASS (astats)
static int query_formats (AVFilterContext *ctx)
static void reset_stats (AudioStatsContext *s)
static int config_output (AVFilterLink *outlink)
static void bit_depth (AudioStatsContext *s, uint64_t mask, uint64_t imask, AVRational *depth)
static void update_stat (AudioStatsContext *s, ChannelStats *p, double d, double nd, int64_t i)
static void set_meta (AVDictionary **metadata, int chan, const char *key, const char *fmt, double val)
static void set_metadata (AudioStatsContext *s, AVDictionary **metadata)
static int filter_frame (AVFilterLink *inlink, AVFrame *buf)
static void print_stats (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const AVOption astats_options []
static const AVFilterPad astats_inputs []
static const AVFilterPad astats_outputs []
AVFilter ff_af_astats
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(AudioStatsContext, x)
Definition at line 57 of file af_astats.c.
FLAGS
#define FLAGS AV_OPT_FLAG_AUDIO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 58 of file af_astats.c.
LINEAR_TO_DB
#define LINEAR_TO_DB (x) (log10(x) * 20)
Definition at line 225 of file af_astats.c.
Referenced by print_stats(), and set_metadata().
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (astats)
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 69 of file af_astats.c.
reset_stats()
static void reset_stats (AudioStatsContext * s) static
Definition at line 103 of file af_astats.c.
Referenced by config_output(), and filter_frame().
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 132 of file af_astats.c.
bit_depth()
static void bit_depth (AudioStatsContext * s, uint64_t mask, uint64_t imask, AVRational * depth) static
Definition at line 150 of file af_astats.c.
Referenced by check_idct(), check_ipred(), check_itxfm(), check_loopfilter(), check_mc(), checkasm_check_h264pred(), checkasm_check_h264qpel(), dnxhd_encode_init(), dnxhd_init_vlc(), ff_bwdif_init_x86(), ff_get_qtpalette(), ff_isom_write_vpcc(), ff_yadif_init_x86(), hl_decode_mb(), hl_decode_mb_444(), matroska_parse_tracks(), mkv_write_track(), print_stats(), randomize_loopfilter_buffers(), and set_metadata().
update_stat()
static void update_stat (AudioStatsContext * s, ChannelStats * p, double d, double nd, int64_t i) inline static
Definition at line 166 of file af_astats.c.
Referenced by filter_frame().
set_meta()
static void set_meta (AVDictionary ** metadata, int chan, const char * key, const char * fmt, double val) static
Definition at line 211 of file af_astats.c.
Referenced by set_metadata().
set_metadata()
static void set_metadata (AudioStatsContext * s, AVDictionary ** metadata) static
Definition at line 227 of file af_astats.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * buf) static
Definition at line 305 of file af_astats.c.
print_stats()
static void print_stats (AVFilterContext * ctx) static
Definition at line 414 of file af_astats.c.
Referenced by uninit().
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 495 of file af_astats.c.
Variable Documentation
astats_options
const AVOption astats_options[] static
Initial value:
= {
    { "length", "set the window length", OFFSET(time_constant), AV_OPT_TYPE_DOUBLE, {.dbl=.05}, .01, 10, FLAGS },
    { "metadata", "inject metadata in the filtergraph", OFFSET(metadata), AV_OPT_TYPE_BOOL, {.i64=0}, 0, 1, FLAGS },
    { "reset", "recalculate stats after this many frames", OFFSET(reset_count), AV_OPT_TYPE_INT, {.i64=0}, 0, INT_MAX, FLAGS },
    { NULL }
}
Definition at line 60 of file af_astats.c.
astats_inputs
const AVFilterPad astats_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_AUDIO,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 504 of file af_astats.c.
astats_outputs
const AVFilterPad astats_outputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_AUDIO,
        .config_props = config_output,
    },
    { NULL }
}
Definition at line 513 of file af_astats.c.
ff_af_astats
AVFilter ff_af_astats
Initial value:
= {
    .name          = "astats",
    .description   = NULL_IF_CONFIG_SMALL("Show time domain statistics about audio frames."),
    .query_formats = query_formats,
    .priv_size     = sizeof(AudioStatsContext),
    .priv_class    = &astats_class,
    .uninit        = uninit,
    .inputs        = astats_inputs,
    .outputs       = astats_outputs,
}
Definition at line 522 of file af_astats.c.