FFmpeg: libavfilter/af_replaygain.c File Reference
af_replaygain.c File Reference
ReplayGain scanner.
#include "libavutil/avassert.h"
#include "libavutil/channel_layout.h"
#include "audio.h"
#include "avfilter.h"
#include "internal.h"
Data Structures
struct ReplayGainFreqInfo
struct ReplayGainContext
Macros
#define HISTOGRAM_SLOTS 12000
#define BUTTER_ORDER 2
#define YULE_ORDER 10
Functions
static int query_formats (AVFilterContext *ctx)
static int config_input (AVFilterLink *inlink)
static void calc_stereo_peak (const float *samples, int nb_samples, float *peak_p)
static double calc_stereo_rms (const float *samples, int nb_samples)
static void butter_filter_stereo_samples (ReplayGainContext *s, float *samples, int nb_samples)
static void yule_filter_stereo_samples (ReplayGainContext *s, const float *src, float *dst, int nb_samples)
static float calc_replaygain (uint32_t *histogram)
static int filter_frame (AVFilterLink *inlink, AVFrame *in)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const ReplayGainFreqInfo freqinfos []
static const AVFilterPad replaygain_inputs []
static const AVFilterPad replaygain_outputs []
AVFilter ff_af_replaygain
Detailed Description
ReplayGain scanner.
Definition in file af_replaygain.c.
Macro Definition Documentation
HISTOGRAM_SLOTS
#define HISTOGRAM_SLOTS 12000
Definition at line 32 of file af_replaygain.c.
Referenced by calc_replaygain(), and filter_frame().
BUTTER_ORDER
#define BUTTER_ORDER 2
Definition at line 33 of file af_replaygain.c.
YULE_ORDER
#define YULE_ORDER 10
Definition at line 34 of file af_replaygain.c.
Function Documentation
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 322 of file af_replaygain.c.
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 343 of file af_replaygain.c.
calc_stereo_peak()
static void calc_stereo_peak (const float * samples, int nb_samples, float * peak_p) static
Definition at line 372 of file af_replaygain.c.
Referenced by filter_frame().
calc_stereo_rms()
static double calc_stereo_rms (const float * samples, int nb_samples) static
Definition at line 399 of file af_replaygain.c.
Referenced by filter_frame().
butter_filter_stereo_samples()
static void butter_filter_stereo_samples (ReplayGainContext * s, float * samples, int nb_samples) static
Definition at line 415 of file af_replaygain.c.
Referenced by filter_frame().
yule_filter_stereo_samples()
static void yule_filter_stereo_samples (ReplayGainContext * s, const float * src, float * dst, int nb_samples) static
Definition at line 464 of file af_replaygain.c.
Referenced by filter_frame().
calc_replaygain()
static float calc_replaygain (uint32_t * histogram) static
Definition at line 531 of file af_replaygain.c.
Referenced by uninit().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 549 of file af_replaygain.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 580 of file af_replaygain.c.
Variable Documentation
freqinfos
const ReplayGainFreqInfo freqinfos[] static
Definition at line 44 of file af_replaygain.c.
replaygain_inputs
const AVFilterPad replaygain_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_AUDIO,
        .filter_frame = filter_frame,
        .config_props = config_input,
    },
    { NULL }
}
Definition at line 589 of file af_replaygain.c.
replaygain_outputs
const AVFilterPad replaygain_outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_AUDIO,
    },
    { NULL }
}
Definition at line 599 of file af_replaygain.c.
ff_af_replaygain
AVFilter ff_af_replaygain
Initial value:
= {
    .name          = "replaygain",
    .description   = NULL_IF_CONFIG_SMALL("ReplayGain scanner."),
    .query_formats = query_formats,
    .uninit        = uninit,
    .priv_size     = sizeof(ReplayGainContext),
    .inputs        = replaygain_inputs,
    .outputs       = replaygain_outputs,
}
Definition at line 607 of file af_replaygain.c.