FFmpeg: libavfilter/af_dynaudnorm.c File Reference
af_dynaudnorm.c File Reference
Dynamic Audio Normalizer.
#include <float.h>
#include "libavutil/avassert.h"
#include "libavutil/opt.h"
#include "libavfilter/bufferqueue.h"
#include "audio.h"
#include "avfilter.h"
#include "internal.h"
Data Structures
struct cqueue
struct DynamicAudioNormalizerContext
Macros
#define FF_BUFQUEUE_SIZE 302
#define OFFSET(x) offsetof(DynamicAudioNormalizerContext, x)
#define FLAGS AV_OPT_FLAG_AUDIO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Functions
AVFILTER_DEFINE_CLASS (dynaudnorm)
static av_cold int init (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static int frame_size (int sample_rate, int frame_len_msec)
static void precalculate_fade_factors (double *fade_factors[2], int frame_len)
static cqueue * cqueue_create (int size)
static void cqueue_free (cqueue *q)
static int cqueue_size (cqueue *q)
static int cqueue_empty (cqueue *q)
static int cqueue_enqueue (cqueue *q, double element)
static double cqueue_peek (cqueue *q, int index)
static int cqueue_dequeue (cqueue *q, double *element)
static int cqueue_pop (cqueue *q)
static void init_gaussian_filter (DynamicAudioNormalizerContext *s)
static av_cold void uninit (AVFilterContext *ctx)
static int config_input (AVFilterLink *inlink)
static double fade (double prev, double next, int pos, double *fade_factors[2])
static double pow2 (const double value)
static double bound (const double threshold, const double val)
static double find_peak_magnitude (AVFrame *frame, int channel)
static double compute_frame_rms (AVFrame *frame, int channel)
static double get_max_local_gain (DynamicAudioNormalizerContext *s, AVFrame *frame, int channel)
static double minimum_filter (cqueue *q)
static double gaussian_filter (DynamicAudioNormalizerContext *s, cqueue *q)
static void update_gain_history (DynamicAudioNormalizerContext *s, int channel, double current_gain_factor)
static double update_value (double new, double old, double aggressiveness)
static void perform_dc_correction (DynamicAudioNormalizerContext *s, AVFrame *frame)
static double setup_compress_thresh (double threshold)
static double compute_frame_std_dev (DynamicAudioNormalizerContext *s, AVFrame *frame, int channel)
static void perform_compression (DynamicAudioNormalizerContext *s, AVFrame *frame)
static void analyze_frame (DynamicAudioNormalizerContext *s, AVFrame *frame)
static void amplify_frame (DynamicAudioNormalizerContext *s, AVFrame *frame)
static int filter_frame (AVFilterLink *inlink, AVFrame *in)
static int flush_buffer (DynamicAudioNormalizerContext *s, AVFilterLink *inlink, AVFilterLink *outlink)
static int request_frame (AVFilterLink *outlink)
Variables
static const AVOption dynaudnorm_options []
static const AVFilterPad avfilter_af_dynaudnorm_inputs []
static const AVFilterPad avfilter_af_dynaudnorm_outputs []
AVFilter ff_af_dynaudnorm
Detailed Description
Dynamic Audio Normalizer.
Definition in file af_dynaudnorm.c.
Macro Definition Documentation
FF_BUFQUEUE_SIZE
#define FF_BUFQUEUE_SIZE 302
Definition at line 32 of file af_dynaudnorm.c.
OFFSET
#define OFFSET (x) offsetof(DynamicAudioNormalizerContext, x)
Definition at line 76 of file af_dynaudnorm.c.
FLAGS
#define FLAGS AV_OPT_FLAG_AUDIO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 77 of file af_dynaudnorm.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (dynaudnorm)
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 94 of file af_dynaudnorm.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 106 of file af_dynaudnorm.c.
frame_size()
static int frame_size (int sample_rate, int frame_len_msec) inline static
Definition at line 136 of file af_dynaudnorm.c.
Referenced by config_input().
precalculate_fade_factors()
static void precalculate_fade_factors (double * fade_factors[2], int frame_len) static
Definition at line 142 of file af_dynaudnorm.c.
Referenced by config_input().
cqueue_create()
static cqueue* cqueue_create (int size) static
Definition at line 153 of file af_dynaudnorm.c.
Referenced by config_input().
cqueue_free()
static void cqueue_free (cqueue * q) static
Definition at line 174 of file af_dynaudnorm.c.
Referenced by uninit().
cqueue_size()
static int cqueue_size (cqueue * q) static
Definition at line 181 of file af_dynaudnorm.c.
Referenced by gaussian_filter(), minimum_filter(), and update_gain_history().
cqueue_empty()
static int cqueue_empty (cqueue * q) static
Definition at line 186 of file af_dynaudnorm.c.
Referenced by cqueue_dequeue(), cqueue_pop(), filter_frame(), perform_compression(), perform_dc_correction(), and update_gain_history().
cqueue_enqueue()
static int cqueue_enqueue (cqueue * q, double element) static
Definition at line 191 of file af_dynaudnorm.c.
Referenced by update_gain_history().
cqueue_peek()
static double cqueue_peek (cqueue * q, int index) static
Definition at line 204 of file af_dynaudnorm.c.
Referenced by gaussian_filter(), minimum_filter(), and update_gain_history().
cqueue_dequeue()
static int cqueue_dequeue (cqueue * q, double * element) static
Definition at line 210 of file af_dynaudnorm.c.
Referenced by amplify_frame().
cqueue_pop()
static int cqueue_pop (cqueue * q) static
Definition at line 221 of file af_dynaudnorm.c.
Referenced by update_gain_history().
init_gaussian_filter()
static void init_gaussian_filter (DynamicAudioNormalizerContext * s) static
Definition at line 231 of file af_dynaudnorm.c.
Referenced by config_input().
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 258 of file af_dynaudnorm.c.
Referenced by config_input().
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 287 of file af_dynaudnorm.c.
fade()
static double fade (double prev, double next, int pos, double * fade_factors[2]) inline static
Definition at line 338 of file af_dynaudnorm.c.
Referenced by amplify_frame(), perform_compression(), and perform_dc_correction().
pow2()
static double pow2 (const double value) inline static
Definition at line 344 of file af_dynaudnorm.c.
Referenced by compute_frame_rms(), and compute_frame_std_dev().
bound()
static double bound (const double threshold, const double val) inline static
Definition at line 349 of file af_dynaudnorm.c.
Referenced by get_max_local_gain(), mp_decode_layer1(), mp_decode_layer2(), perform_compression(), and setup_compress_thresh().
find_peak_magnitude()
static double find_peak_magnitude (AVFrame * frame, int channel) static
Definition at line 355 of file af_dynaudnorm.c.
Referenced by get_max_local_gain().
compute_frame_rms()
static double compute_frame_rms (AVFrame * frame, int channel) static
Definition at line 377 of file af_dynaudnorm.c.
Referenced by get_max_local_gain().
get_max_local_gain()
static double get_max_local_gain (DynamicAudioNormalizerContext * s, AVFrame * frame, int channel) static
Definition at line 404 of file af_dynaudnorm.c.
Referenced by analyze_frame().
minimum_filter()
static double minimum_filter (cqueue * q) static
Definition at line 412 of file af_dynaudnorm.c.
Referenced by update_gain_history().
gaussian_filter()
static double gaussian_filter (DynamicAudioNormalizerContext * s, cqueue * q) static
Definition at line 424 of file af_dynaudnorm.c.
Referenced by update_gain_history().
update_gain_history()
static void update_gain_history (DynamicAudioNormalizerContext * s, int channel, double current_gain_factor) static
Definition at line 436 of file af_dynaudnorm.c.
Referenced by analyze_frame().
update_value()
static double update_value (double new, double old, double aggressiveness) inline static
Definition at line 486 of file af_dynaudnorm.c.
Referenced by perform_compression(), and perform_dc_correction().
perform_dc_correction()
static void perform_dc_correction (DynamicAudioNormalizerContext * s, AVFrame * frame) static
Definition at line 492 of file af_dynaudnorm.c.
Referenced by analyze_frame().
setup_compress_thresh()
static double setup_compress_thresh (double threshold) static
Definition at line 515 of file af_dynaudnorm.c.
Referenced by perform_compression().
compute_frame_std_dev()
static double compute_frame_std_dev (DynamicAudioNormalizerContext * s, AVFrame * frame, int channel) static
Definition at line 537 of file af_dynaudnorm.c.
Referenced by perform_compression().
perform_compression()
static void perform_compression (DynamicAudioNormalizerContext * s, AVFrame * frame) static
Definition at line 564 of file af_dynaudnorm.c.
Referenced by analyze_frame().
analyze_frame()
static void analyze_frame (DynamicAudioNormalizerContext * s, AVFrame * frame) static
Definition at line 609 of file af_dynaudnorm.c.
Referenced by filter_frame().
amplify_frame()
static void amplify_frame (DynamicAudioNormalizerContext * s, AVFrame * frame) static
Definition at line 633 of file af_dynaudnorm.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 658 of file af_dynaudnorm.c.
Referenced by flush_buffer().
flush_buffer()
static int flush_buffer (DynamicAudioNormalizerContext * s, AVFilterLink * inlink, AVFilterLink * outlink) static
Definition at line 678 of file af_dynaudnorm.c.
Referenced by request_frame().
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 703 of file af_dynaudnorm.c.
Variable Documentation
dynaudnorm_options
const AVOption dynaudnorm_options[] static
Initial value:
= {
    { "f", "set the frame length in msec",     OFFSET(frame_len_msec),    AV_OPT_TYPE_INT,    {.i64 = 500},   10,  8000, FLAGS },
    { "g", "set the filter size",              OFFSET(filter_size),       AV_OPT_TYPE_INT,    {.i64 = 31},     3,   301, FLAGS },
    { "p", "set the peak value",               OFFSET(peak_value),        AV_OPT_TYPE_DOUBLE, {.dbl = 0.95}, 0.0,   1.0, FLAGS },
    { "m", "set the max amplification",        OFFSET(max_amplification), AV_OPT_TYPE_DOUBLE, {.dbl = 10.0}, 1.0, 100.0, FLAGS },
    { "r", "set the target RMS",               OFFSET(target_rms),        AV_OPT_TYPE_DOUBLE, {.dbl = 0.0},  0.0,   1.0, FLAGS },
    { "n", "set channel coupling",             OFFSET(channels_coupled),  AV_OPT_TYPE_BOOL,   {.i64 = 1},      0,     1, FLAGS },
    { "c", "set DC correction",                OFFSET(dc_correction),     AV_OPT_TYPE_BOOL,   {.i64 = 0},      0,     1, FLAGS },
    { "b", "set alternative boundary mode",    OFFSET(alt_boundary_mode), AV_OPT_TYPE_BOOL,   {.i64 = 0},      0,     1, FLAGS },
    { "s", "set the compress factor",          OFFSET(compress_factor),   AV_OPT_TYPE_DOUBLE, {.dbl = 0.0},  0.0,  30.0, FLAGS },
    { NULL }
}
Definition at line 79 of file af_dynaudnorm.c.
avfilter_af_dynaudnorm_inputs
const AVFilterPad avfilter_af_dynaudnorm_inputs[] static
Initial value:
= {
    {
        .name           = "default",
        .type           = AVMEDIA_TYPE_AUDIO,
        .filter_frame   = filter_frame,
        .config_props   = config_input,
        .needs_writable = 1,
    },
    { NULL }
}
Definition at line 717 of file af_dynaudnorm.c.
avfilter_af_dynaudnorm_outputs
const AVFilterPad avfilter_af_dynaudnorm_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_AUDIO,
        .request_frame = request_frame,
    },
    { NULL }
}
Definition at line 728 of file af_dynaudnorm.c.
ff_af_dynaudnorm
AVFilter ff_af_dynaudnorm
Initial value:
= {
    .name          = "dynaudnorm",
    .description   = NULL_IF_CONFIG_SMALL("Dynamic Audio Normalizer."),
    .query_formats = query_formats,
    .priv_size     = sizeof(DynamicAudioNormalizerContext),
    .init          = init,
    .uninit        = uninit,
    .inputs        = avfilter_af_dynaudnorm_inputs,
    .outputs       = avfilter_af_dynaudnorm_outputs,
    .priv_class    = &dynaudnorm_class,
}
Definition at line 737 of file af_dynaudnorm.c.