FFmpeg: libavfilter/af_ashowinfo.c File Reference
af_ashowinfo.c File Reference
filter for showing textual audio frame information
#include <inttypes.h>
#include <stddef.h>
#include "libavutil/adler32.h"
#include "libavutil/attributes.h"
#include "libavutil/channel_layout.h"
#include "libavutil/common.h"
#include "libavutil/downmix_info.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/mem.h"
#include "libavutil/replaygain.h"
#include "libavutil/timestamp.h"
#include "libavutil/samplefmt.h"
#include "libavcodec/avcodec.h"
#include "audio.h"
#include "avfilter.h"
#include "internal.h"
Data Structures
struct AShowInfoContext
Functions
static av_cold void uninit (AVFilterContext *ctx)
static void dump_matrixenc (AVFilterContext *ctx, AVFrameSideData *sd)
static void dump_downmix (AVFilterContext *ctx, AVFrameSideData *sd)
static void print_gain (AVFilterContext *ctx, const char *str, int32_t gain)
static void print_peak (AVFilterContext *ctx, const char *str, uint32_t peak)
static void dump_replaygain (AVFilterContext *ctx, AVFrameSideData *sd)
static void dump_audio_service_type (AVFilterContext *ctx, AVFrameSideData *sd)
static void dump_unknown (AVFilterContext *ctx, AVFrameSideData *sd)
static int filter_frame (AVFilterLink *inlink, AVFrame *buf)
Variables
static const AVFilterPad inputs []
static const AVFilterPad outputs []
AVFilter ff_af_ashowinfo
Detailed Description
filter for showing textual audio frame information
Definition in file af_ashowinfo.c.
Function Documentation
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 53 of file af_ashowinfo.c.
dump_matrixenc()
static void dump_matrixenc (AVFilterContext * ctx, AVFrameSideData * sd) static
Definition at line 59 of file af_ashowinfo.c.
Referenced by filter_frame().
dump_downmix()
static void dump_downmix (AVFilterContext * ctx, AVFrameSideData * sd) static
Definition at line 83 of file af_ashowinfo.c.
Referenced by filter_frame().
print_gain()
static void print_gain (AVFilterContext * ctx, const char * str, int32_t gain) static
Definition at line 110 of file af_ashowinfo.c.
Referenced by dump_replaygain().
print_peak()
static void print_peak (AVFilterContext * ctx, const char * str, uint32_t peak) static
Definition at line 120 of file af_ashowinfo.c.
Referenced by dump_replaygain().
dump_replaygain()
static void dump_replaygain (AVFilterContext * ctx, AVFrameSideData * sd) static
Definition at line 130 of file af_ashowinfo.c.
Referenced by filter_frame().
dump_audio_service_type()
static void dump_audio_service_type (AVFilterContext * ctx, AVFrameSideData * sd) static
Definition at line 147 of file af_ashowinfo.c.
Referenced by filter_frame().
dump_unknown()
static void dump_unknown (AVFilterContext * ctx, AVFrameSideData * sd) static
Definition at line 171 of file af_ashowinfo.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * buf) static
Definition at line 176 of file af_ashowinfo.c.
Variable Documentation
inputs
const AVFilterPad inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_AUDIO,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 239 of file af_ashowinfo.c.
outputs
const AVFilterPad outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_AUDIO,
    },
    { NULL }
}
Definition at line 248 of file af_ashowinfo.c.
ff_af_ashowinfo
AVFilter ff_af_ashowinfo
Initial value:
= {
    .name        = "ashowinfo",
    .description = NULL_IF_CONFIG_SMALL("Show textual information for each audio frame."),
    .priv_size   = sizeof(AShowInfoContext),
    .uninit      = uninit,
    .inputs      = inputs,
    .outputs     = outputs,
}
Definition at line 256 of file af_ashowinfo.c.