FFmpeg: libavfilter/af_acrusher.c File Reference
af_acrusher.c File Reference
#include "libavutil/opt.h"
#include "avfilter.h"
#include "internal.h"
#include "audio.h"
Data Structures
struct LFOContext
struct SRContext
struct ACrusherContext
Macros
#define OFFSET(x) offsetof(ACrusherContext, x)
#define A AV_OPT_FLAG_AUDIO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Functions
AVFILTER_DEFINE_CLASS (acrusher)
static double samplereduction (ACrusherContext *s, SRContext *sr, double in)
static double add_dc (double s, double dc, double idc)
static double remove_dc (double s, double dc, double idc)
static double factor (double y, double k, double aa1, double aa)
static double bitreduction (ACrusherContext *s, double in)
static double lfo_get (LFOContext *lfo)
static void lfo_advance (LFOContext *lfo, unsigned count)
static int filter_frame (AVFilterLink *inlink, AVFrame *in)
static int query_formats (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
static int config_input (AVFilterLink *inlink)
Variables
static const AVOption acrusher_options []
static const AVFilterPad avfilter_af_acrusher_inputs []
static const AVFilterPad avfilter_af_acrusher_outputs []
AVFilter ff_af_acrusher
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(ACrusherContext, x)
Definition at line 70 of file af_acrusher.c.
A
#define A AV_OPT_FLAG_AUDIO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 71 of file af_acrusher.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (acrusher)
samplereduction()
static double samplereduction (ACrusherContext * s, SRContext * sr, double in) static
Definition at line 92 of file af_acrusher.c.
Referenced by filter_frame().
add_dc()
static double add_dc (double s, double dc, double idc) static
Definition at line 108 of file af_acrusher.c.
Referenced by bitreduction().
remove_dc()
static double remove_dc (double s, double dc, double idc) static
Definition at line 113 of file af_acrusher.c.
Referenced by bitreduction().
factor()
static double factor (double y, double k, double aa1, double aa) inline static
Definition at line 118 of file af_acrusher.c.
Referenced by bitreduction().
bitreduction()
static double bitreduction (ACrusherContext * s, double in) static
Definition at line 123 of file af_acrusher.c.
Referenced by filter_frame().
lfo_get()
static double lfo_get (LFOContext * lfo) static
Definition at line 196 of file af_acrusher.c.
Referenced by filter_frame().
lfo_advance()
static void lfo_advance (LFOContext * lfo, unsigned count) static
Definition at line 209 of file af_acrusher.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 216 of file af_acrusher.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 266 of file af_acrusher.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 296 of file af_acrusher.c.
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 303 of file af_acrusher.c.
Variable Documentation
acrusher_options
const AVOption acrusher_options[] static
Initial value:
= {
    { "level_in", "set level in",         OFFSET(level_in),  AV_OPT_TYPE_DOUBLE, {.dbl=1},    0.015625, 64, A },
    { "level_out","set level out",        OFFSET(level_out), AV_OPT_TYPE_DOUBLE, {.dbl=1},    0.015625, 64, A },
    { "bits",     "set bit reduction",    OFFSET(bits),      AV_OPT_TYPE_DOUBLE, {.dbl=8},    1,        64, A },
    { "mix",      "set mix",              OFFSET(mix),       AV_OPT_TYPE_DOUBLE, {.dbl=.5},   0,         1, A },
    { "mode",     "set mode",             OFFSET(mode),      AV_OPT_TYPE_INT,    {.i64=0},    0,         1, A, "mode" },
    {   "lin",    "linear",               0,                 AV_OPT_TYPE_CONST,  {.i64=0},    0,         0, A, "mode" },
    {   "log",    "logarithmic",          0,                 AV_OPT_TYPE_CONST,  {.i64=1},    0,         0, A, "mode" },
    { "dc",       "set DC",               OFFSET(dc),        AV_OPT_TYPE_DOUBLE, {.dbl=1},  .25,         4, A },
    { "aa",       "set anti-aliasing",    OFFSET(aa),        AV_OPT_TYPE_DOUBLE, {.dbl=.5},   0,         1, A },
    { "samples",  "set sample reduction", OFFSET(samples),   AV_OPT_TYPE_DOUBLE, {.dbl=1},    1,       250, A },
    { "lfo",      "enable LFO",           OFFSET(is_lfo),    AV_OPT_TYPE_BOOL,   {.i64=0},    0,         1, A },
    { "lforange", "set LFO depth",        OFFSET(lforange),  AV_OPT_TYPE_DOUBLE, {.dbl=20},   1,       250, A },
    { "lforate",  "set LFO rate",         OFFSET(lforate),   AV_OPT_TYPE_DOUBLE, {.dbl=.3}, .01,       200, A },
    { NULL }
}
Definition at line 73 of file af_acrusher.c.
avfilter_af_acrusher_inputs
const AVFilterPad avfilter_af_acrusher_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_AUDIO,
        .config_props = config_input,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 335 of file af_acrusher.c.
avfilter_af_acrusher_outputs
const AVFilterPad avfilter_af_acrusher_outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_AUDIO,
    },
    { NULL }
}
Definition at line 345 of file af_acrusher.c.
ff_af_acrusher
AVFilter ff_af_acrusher
Initial value:
= {
    .name          = "acrusher",
    .description   = NULL_IF_CONFIG_SMALL("Reduce audio bit resolution."),
    .priv_size     = sizeof(ACrusherContext),
    .priv_class    = &acrusher_class,
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = avfilter_af_acrusher_inputs,
    .outputs       = avfilter_af_acrusher_outputs,
}
Definition at line 353 of file af_acrusher.c.