FFmpeg: libavfilter/af_sofalizer.c File Reference
af_sofalizer.c File Reference
#include <math.h>
#include <netcdf.h>
#include "libavcodec/avfft.h"
#include "libavutil/avstring.h"
#include "libavutil/channel_layout.h"
#include "libavutil/float_dsp.h"
#include "libavutil/intmath.h"
#include "libavutil/opt.h"
#include "avfilter.h"
#include "internal.h"
#include "audio.h"
Data Structures
struct NCSofa
struct VirtualSpeaker
struct SOFAlizerContext
struct ThreadData
Macros
#define TIME_DOMAIN 0
#define FREQUENCY_DOMAIN 1
#define OFFSET(x) offsetof(SOFAlizerContext, x)
#define FLAGS AV_OPT_FLAG_AUDIO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Functions
static int close_sofa (struct NCSofa *sofa)
static int load_sofa (AVFilterContext *ctx, char *filename, int *samplingrate)
static int parse_channel_name (char **arg, int *rchannel, char *buf)
static void parse_speaker_pos (AVFilterContext *ctx, int64_t in_channel_layout)
static int get_speaker_pos (AVFilterContext *ctx, float *speaker_azim, float *speaker_elev)
static int max_delay (struct NCSofa *sofa)
static int find_m (SOFAlizerContext *s, int azim, int elev, float radius)
static int compensate_volume (AVFilterContext *ctx)
static int sofalizer_convolute (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int sofalizer_fast_convolute (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int filter_frame (AVFilterLink *inlink, AVFrame *in)
static int query_formats (AVFilterContext *ctx)
static int load_data (AVFilterContext *ctx, int azim, int elev, float radius)
static av_cold int init (AVFilterContext *ctx)
static int config_input (AVFilterLink *inlink)
static av_cold void uninit (AVFilterContext *ctx)
AVFILTER_DEFINE_CLASS (sofalizer)
Variables
static const AVOption sofalizer_options []
static const AVFilterPad inputs []
static const AVFilterPad outputs []
AVFilter ff_af_sofalizer
Macro Definition Documentation
TIME_DOMAIN
#define TIME_DOMAIN 0
Definition at line 41 of file af_sofalizer.c.
Referenced by config_input(), filter_frame(), and load_data().
FREQUENCY_DOMAIN
#define FREQUENCY_DOMAIN 1
Definition at line 42 of file af_sofalizer.c.
Referenced by config_input().
OFFSET
#define OFFSET (x) offsetof(SOFAlizerContext, x)
Definition at line 1183 of file af_sofalizer.c.
FLAGS
#define FLAGS AV_OPT_FLAG_AUDIO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 1184 of file af_sofalizer.c.
Function Documentation
close_sofa()
static int close_sofa (struct NCSofa * sofa) static
Definition at line 109 of file af_sofalizer.c.
Referenced by load_sofa().
load_sofa()
static int load_sofa (AVFilterContext * ctx, char * filename, int * samplingrate) static
Definition at line 122 of file af_sofalizer.c.
Referenced by init().
parse_channel_name()
static int parse_channel_name (char ** arg, int * rchannel, char * buf) static
Definition at line 376 of file af_sofalizer.c.
Referenced by parse_speaker_pos().
parse_speaker_pos()
static void parse_speaker_pos (AVFilterContext * ctx, int64_t in_channel_layout) static
Definition at line 401 of file af_sofalizer.c.
Referenced by get_speaker_pos().
get_speaker_pos()
static int get_speaker_pos (AVFilterContext * ctx, float * speaker_azim, float * speaker_elev) static
Definition at line 434 of file af_sofalizer.c.
Referenced by config_input().
max_delay()
static int max_delay (struct NCSofa * sofa) static
Definition at line 509 of file af_sofalizer.c.
Referenced by config_input(), output_packet(), and udp_get_file_handle().
find_m()
static int find_m (SOFAlizerContext * s, int azim, int elev, float radius) static
Definition at line 521 of file af_sofalizer.c.
Referenced by compensate_volume(), and load_data().
compensate_volume()
static int compensate_volume (AVFilterContext * ctx) static
Definition at line 549 of file af_sofalizer.c.
Referenced by config_input().
sofalizer_convolute()
static int sofalizer_convolute (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 597 of file af_sofalizer.c.
Referenced by filter_frame().
sofalizer_fast_convolute()
static int sofalizer_fast_convolute (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 683 of file af_sofalizer.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 797 of file af_sofalizer.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 835 of file af_sofalizer.c.
load_data()
static int load_data (AVFilterContext * ctx, int azim, int elev, float radius) static
Definition at line 873 of file af_sofalizer.c.
Referenced by config_input().
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 1014 of file af_sofalizer.c.
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 1049 of file af_sofalizer.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 1151 of file af_sofalizer.c.
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (sofalizer)
Variable Documentation
sofalizer_options
const AVOption sofalizer_options[] static
Initial value:
= {
    { "sofa",      "sofa filename",  OFFSET(filename),  AV_OPT_TYPE_STRING, {.str=NULL},            .flags = FLAGS },
    { "gain",      "set gain in dB", OFFSET(gain),      AV_OPT_TYPE_FLOAT,  {.dbl=0},     -20,  40, .flags = FLAGS },
    { "rotation",  "set rotation"  , OFFSET(rotation),  AV_OPT_TYPE_FLOAT,  {.dbl=0},    -360, 360, .flags = FLAGS },
    { "elevation", "set elevation",  OFFSET(elevation), AV_OPT_TYPE_FLOAT,  {.dbl=0},     -90,  90, .flags = FLAGS },
    { "radius",    "set radius",     OFFSET(radius),    AV_OPT_TYPE_FLOAT,  {.dbl=1},       0,   3, .flags = FLAGS },
    { "type",      "set processing", OFFSET(type),      AV_OPT_TYPE_INT,    {.i64=1},       0,   1, .flags = FLAGS, "type" },
    { "time",      "time domain",      0,               AV_OPT_TYPE_CONST,  {.i64=0},       0,   0, .flags = FLAGS, "type" },
    { "freq",      "frequency domain", 0,               AV_OPT_TYPE_CONST,  {.i64=1},       0,   0, .flags = FLAGS, "type" },
    { "speakers",  "set speaker custom positions", OFFSET(speakers_pos), AV_OPT_TYPE_STRING,  {.str=0},    0, 0, .flags = FLAGS },
    { NULL }
}
Definition at line 1186 of file af_sofalizer.c.
inputs
const AVFilterPad inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_AUDIO,
        .config_props = config_input,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 1201 of file af_sofalizer.c.
outputs
const AVFilterPad outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_AUDIO,
    },
    { NULL }
}
Definition at line 1211 of file af_sofalizer.c.
ff_af_sofalizer
AVFilter ff_af_sofalizer
Initial value:
= {
    .name          = "sofalizer",
    .description   = NULL_IF_CONFIG_SMALL("SOFAlizer (Spatially Oriented Format for Acoustics)."),
    .priv_size     = sizeof(SOFAlizerContext),
    .priv_class    = &sofalizer_class,
    .init          = init,
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = inputs,
    .outputs       = outputs,
    .flags         = AVFILTER_FLAG_SLICE_THREADS,
}
Definition at line 1219 of file af_sofalizer.c.