FFmpeg: libavfilter/af_silenceremove.c File Reference
af_silenceremove.c File Reference
#include <float.h>
#include "libavutil/opt.h"
#include "libavutil/timestamp.h"
#include "audio.h"
#include "formats.h"
#include "avfilter.h"
#include "internal.h"
Data Structures
struct SilenceRemoveContext
Macros
#define OFFSET(x) offsetof(SilenceRemoveContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_AUDIO_PARAM
Enumerations
enum SilenceMode {
SILENCE_TRIM, SILENCE_TRIM_FLUSH, SILENCE_COPY, SILENCE_COPY_FLUSH,
SILENCE_STOP
}
Functions
AVFILTER_DEFINE_CLASS (silenceremove)
static double compute_peak (SilenceRemoveContext *s, double sample)
static void update_peak (SilenceRemoveContext *s, double sample)
static double compute_rms (SilenceRemoveContext *s, double sample)
static void update_rms (SilenceRemoveContext *s, double sample)
static av_cold int init (AVFilterContext *ctx)
static void clear_window (SilenceRemoveContext *s)
static int config_input (AVFilterLink *inlink)
static void flush (AVFrame *out, AVFilterLink *outlink, int *nb_samples_written, int *ret)
static int filter_frame (AVFilterLink *inlink, AVFrame *in)
static int request_frame (AVFilterLink *outlink)
static int query_formats (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const AVOption silenceremove_options []
static const AVFilterPad silenceremove_inputs []
static const AVFilterPad silenceremove_outputs []
AVFilter ff_af_silenceremove
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(SilenceRemoveContext, x)
Definition at line 80 of file af_silenceremove.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_AUDIO_PARAM
Definition at line 81 of file af_silenceremove.c.
Enumeration Type Documentation
SilenceMode
enum SilenceMode
Enumerator
SILENCE_TRIM
SILENCE_TRIM_FLUSH
SILENCE_COPY
SILENCE_COPY_FLUSH
SILENCE_STOP
Definition at line 33 of file af_silenceremove.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (silenceremove)
compute_peak()
static double compute_peak (SilenceRemoveContext * s, double sample) static
Definition at line 99 of file af_silenceremove.c.
Referenced by init().
update_peak()
static void update_peak (SilenceRemoveContext * s, double sample) static
Definition at line 110 of file af_silenceremove.c.
Referenced by init().
compute_rms()
static double compute_rms (SilenceRemoveContext * s, double sample) static
Definition at line 121 of file af_silenceremove.c.
Referenced by init().
update_rms()
static void update_rms (SilenceRemoveContext * s, double sample) static
Definition at line 132 of file af_silenceremove.c.
Referenced by init().
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 143 of file af_silenceremove.c.
clear_window()
static void clear_window (SilenceRemoveContext * s) static
Definition at line 166 of file af_silenceremove.c.
Referenced by config_input(), and filter_frame().
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 175 of file af_silenceremove.c.
flush()
static void flush (AVFrame * out, AVFilterLink * outlink, int * nb_samples_written, int * ret) static
Definition at line 220 of file af_silenceremove.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 232 of file af_silenceremove.c.
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 423 of file af_silenceremove.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 449 of file af_silenceremove.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 478 of file af_silenceremove.c.
Variable Documentation
silenceremove_options
const AVOption silenceremove_options[] static
Initial value:
= {
    { "start_periods",   NULL, OFFSET(start_periods),   AV_OPT_TYPE_INT,      {.i64=0},     0,    9000, FLAGS },
    { "start_duration",  NULL, OFFSET(start_duration),  AV_OPT_TYPE_DURATION, {.i64=0},     0,    9000, FLAGS },
    { "start_threshold", NULL, OFFSET(start_threshold), AV_OPT_TYPE_DOUBLE,   {.dbl=0},     0, DBL_MAX, FLAGS },
    { "stop_periods",    NULL, OFFSET(stop_periods),    AV_OPT_TYPE_INT,      {.i64=0}, -9000,    9000, FLAGS },
    { "stop_duration",   NULL, OFFSET(stop_duration),   AV_OPT_TYPE_DURATION, {.i64=0},     0,    9000, FLAGS },
    { "stop_threshold",  NULL, OFFSET(stop_threshold),  AV_OPT_TYPE_DOUBLE,   {.dbl=0},     0, DBL_MAX, FLAGS },
    { "leave_silence",   NULL, OFFSET(leave_silence),   AV_OPT_TYPE_BOOL,     {.i64=0},     0,       1, FLAGS },
    { "detection",       NULL, OFFSET(detection),       AV_OPT_TYPE_INT,      {.i64=1},     0,       1, FLAGS, "detection" },
    {   "peak",          0,    0,                       AV_OPT_TYPE_CONST,    {.i64=0},     0,       0, FLAGS, "detection" },
    {   "rms",           0,    0,                       AV_OPT_TYPE_CONST,    {.i64=1},     0,       0, FLAGS, "detection" },
    { "window",          NULL, OFFSET(window_ratio),    AV_OPT_TYPE_DOUBLE,   {.dbl=0.02},  0,      10, FLAGS },
    { NULL }
}
Definition at line 82 of file af_silenceremove.c.
silenceremove_inputs
const AVFilterPad silenceremove_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_AUDIO,
        .config_props = config_input,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 487 of file af_silenceremove.c.
silenceremove_outputs
const AVFilterPad silenceremove_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_AUDIO,
        .request_frame = request_frame,
    },
    { NULL }
}
Definition at line 497 of file af_silenceremove.c.
ff_af_silenceremove
AVFilter ff_af_silenceremove
Initial value:
= {
    .name          = "silenceremove",
    .description   = NULL_IF_CONFIG_SMALL("Remove silence."),
    .priv_size     = sizeof(SilenceRemoveContext),
    .priv_class    = &silenceremove_class,
    .init          = init,
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = silenceremove_inputs,
    .outputs       = silenceremove_outputs,
}
Definition at line 506 of file af_silenceremove.c.