FFmpeg: libavfilter/af_anequalizer.c File Reference
af_anequalizer.c File Reference
#include "libavutil/intreadwrite.h"
#include "libavutil/avstring.h"
#include "libavutil/ffmath.h"
#include "libavutil/opt.h"
#include "libavutil/parseutils.h"
#include "avfilter.h"
#include "internal.h"
#include "audio.h"
Data Structures
struct FoSection
struct EqualizatorFilter
struct AudioNEqualizerContext
Macros
#define FILTER_ORDER 4
#define OFFSET(x) offsetof(AudioNEqualizerContext, x)
#define A AV_OPT_FLAG_AUDIO_PARAM
#define V AV_OPT_FLAG_VIDEO_PARAM
#define F AV_OPT_FLAG_FILTERING_PARAM
Enumerations
enum FilterType {
BUTTERWORTH, CHEBYSHEV1, CHEBYSHEV2, NB_TYPES,
biquad, equalizer, bass, treble,
band, bandpass, bandreject, allpass,
highpass, lowpass, LOWPASS, FLAT,
AFLAT, CHROMA, COLOR, ACOLOR,
NB_FILTERS
}
Functions
AVFILTER_DEFINE_CLASS (anequalizer)
static void draw_curves (AVFilterContext *ctx, AVFilterLink *inlink, AVFrame *out)
static int config_video (AVFilterLink *outlink)
static av_cold int init (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
static void butterworth_fo_section (FoSection *S, double beta, double si, double g, double g0, double D, double c0)
static void butterworth_bp_filter (EqualizatorFilter *f, int N, double w0, double wb, double G, double Gb, double G0)
static void chebyshev1_fo_section (FoSection *S, double a, double c, double tetta_b, double g0, double si, double b, double D, double c0)
static void chebyshev1_bp_filter (EqualizatorFilter *f, int N, double w0, double wb, double G, double Gb, double G0)
static void chebyshev2_fo_section (FoSection *S, double a, double c, double tetta_b, double g, double si, double b, double D, double c0)
static void chebyshev2_bp_filter (EqualizatorFilter *f, int N, double w0, double wb, double G, double Gb, double G0)
static double butterworth_compute_bw_gain_db (double gain)
static double chebyshev1_compute_bw_gain_db (double gain)
static double chebyshev2_compute_bw_gain_db (double gain)
static double hz_2_rad (double x, double fs)
static void equalizer (EqualizatorFilter *f, double sample_rate)
static int add_filter (AudioNEqualizerContext *s, AVFilterLink *inlink)
static int config_input (AVFilterLink *inlink)
static int process_command (AVFilterContext *ctx, const char *cmd, const char *args, char *res, int res_len, int flags)
static double section_process (FoSection *S, double in)
static double process_sample (FoSection *s1, double in)
static int filter_frame (AVFilterLink *inlink, AVFrame *buf)
Variables
static const AVOption anequalizer_options []
static const AVFilterPad inputs []
AVFilter ff_af_anequalizer
Macro Definition Documentation
FILTER_ORDER
#define FILTER_ORDER 4
Definition at line 31 of file af_anequalizer.c.
Referenced by draw_curves(), equalizer(), and process_sample().
OFFSET
#define OFFSET (x) offsetof(AudioNEqualizerContext, x)
Definition at line 75 of file af_anequalizer.c.
A
#define A AV_OPT_FLAG_AUDIO_PARAM
Definition at line 76 of file af_anequalizer.c.
V
#define V AV_OPT_FLAG_VIDEO_PARAM
Definition at line 77 of file af_anequalizer.c.
F
#define F AV_OPT_FLAG_FILTERING_PARAM
Definition at line 78 of file af_anequalizer.c.
Enumeration Type Documentation
FilterType
enum FilterType
Enumerator
BUTTERWORTH
CHEBYSHEV1
CHEBYSHEV2
NB_TYPES
biquad
equalizer
bass
treble
band
bandpass
bandreject
allpass
highpass
lowpass
LOWPASS
FLAT
AFLAT
CHROMA
COLOR
ACOLOR
NB_FILTERS
Definition at line 33 of file af_anequalizer.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (anequalizer)
draw_curves()
static void draw_curves (AVFilterContext * ctx, AVFilterLink * inlink, AVFrame * out) static
Definition at line 94 of file af_anequalizer.c.
Referenced by config_video(), and process_command().
config_video()
static int config_video (AVFilterLink * outlink) static
Definition at line 167 of file af_anequalizer.c.
Referenced by init().
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 188 of file af_anequalizer.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 219 of file af_anequalizer.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 258 of file af_anequalizer.c.
butterworth_fo_section()
static void butterworth_fo_section (FoSection * S, double beta, double si, double g, double g0, double D, double c0) static
Definition at line 271 of file af_anequalizer.c.
Referenced by butterworth_bp_filter().
butterworth_bp_filter()
static void butterworth_bp_filter (EqualizatorFilter * f, int N, double w0, double wb, double G, double Gb, double G0) static
Definition at line 302 of file af_anequalizer.c.
Referenced by equalizer().
chebyshev1_fo_section()
static void chebyshev1_fo_section (FoSection * S, double a, double c, double tetta_b, double g0, double si, double b, double D, double c0) static
Definition at line 339 of file af_anequalizer.c.
Referenced by chebyshev1_bp_filter().
chebyshev1_bp_filter()
static void chebyshev1_bp_filter (EqualizatorFilter * f, int N, double w0, double wb, double G, double Gb, double G0) static
Definition at line 371 of file af_anequalizer.c.
Referenced by equalizer().
chebyshev2_fo_section()
static void chebyshev2_fo_section (FoSection * S, double a, double c, double tetta_b, double g, double si, double b, double D, double c0) static
Definition at line 412 of file af_anequalizer.c.
Referenced by chebyshev2_bp_filter().
chebyshev2_bp_filter()
static void chebyshev2_bp_filter (EqualizatorFilter * f, int N, double w0, double wb, double G, double Gb, double G0) static
Definition at line 444 of file af_anequalizer.c.
Referenced by equalizer().
butterworth_compute_bw_gain_db()
static double butterworth_compute_bw_gain_db (double gain) static
Definition at line 485 of file af_anequalizer.c.
Referenced by equalizer().
chebyshev1_compute_bw_gain_db()
static double chebyshev1_compute_bw_gain_db (double gain) static
Definition at line 499 of file af_anequalizer.c.
Referenced by equalizer().
chebyshev2_compute_bw_gain_db()
static double chebyshev2_compute_bw_gain_db (double gain) static
Definition at line 513 of file af_anequalizer.c.
Referenced by equalizer().
hz_2_rad()
static double hz_2_rad (double x, double fs) inline static
Definition at line 527 of file af_anequalizer.c.
Referenced by equalizer().
equalizer()
static void equalizer (EqualizatorFilter * f, double sample_rate) static
Definition at line 532 of file af_anequalizer.c.
Referenced by add_filter(), and process_command().
add_filter()
static int add_filter (AudioNEqualizerContext * s, AVFilterLink * inlink) static
Definition at line 555 of file af_anequalizer.c.
Referenced by config_input().
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 574 of file af_anequalizer.c.
process_command()
static int process_command (AVFilterContext * ctx, const char * cmd, const char * args, char * res, int res_len, int flags) static
Definition at line 632 of file af_anequalizer.c.
Referenced by request_frame().
section_process()
static double section_process (FoSection * S, double in) inline static
Definition at line 665 of file af_anequalizer.c.
Referenced by process_sample().
process_sample()
static double process_sample (FoSection * s1, double in) static
Definition at line 688 of file af_anequalizer.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * buf) static
Definition at line 701 of file af_anequalizer.c.
Variable Documentation
anequalizer_options
const AVOption anequalizer_options[] static
Initial value:
= {
    { "params", NULL,                             OFFSET(args),        AV_OPT_TYPE_STRING,     {.str=""}, 0, 0, A|F },
    { "curves", "draw frequency response curves", OFFSET(draw_curves), AV_OPT_TYPE_BOOL,       {.i64=0}, 0, 1, V|F },
    { "size",   "set video size",                 OFFSET(w),           AV_OPT_TYPE_IMAGE_SIZE, {.str = "hd720"}, 0, 0, V|F },
    { "mgain",  "set max gain",                   OFFSET(mag),         AV_OPT_TYPE_DOUBLE,     {.dbl=60}, -900, 900, V|F },
    { "fscale", "set frequency scale",            OFFSET(fscale),      AV_OPT_TYPE_INT,        {.i64=1}, 0, 1, V|F, "fscale" },
        { "lin",  "linear",                       0,                   AV_OPT_TYPE_CONST,      {.i64=0}, 0, 0, V|F, "fscale" },
        { "log",  "logarithmic",                  0,                   AV_OPT_TYPE_CONST,      {.i64=1}, 0, 0, V|F, "fscale" },
    { "colors", "set channels curves colors",     OFFSET(colors),      AV_OPT_TYPE_STRING,     {.str = "red|green|blue|yellow|orange|lime|pink|magenta|brown" }, 0, 0, V|F },
    { NULL }
}
Definition at line 80 of file af_anequalizer.c.
inputs
const AVFilterPad inputs[] static
Initial value:
= {
    {
        .name           = "default",
        .type           = AVMEDIA_TYPE_AUDIO,
        .config_props   = config_input,
        .filter_frame   = filter_frame,
        .needs_writable = 1,
    },
    { NULL }
}
Definition at line 739 of file af_anequalizer.c.
ff_af_anequalizer
AVFilter ff_af_anequalizer
Initial value:
= {
    .name          = "anequalizer",
    .description   = NULL_IF_CONFIG_SMALL("Apply high-order audio parametric multi band equalizer."),
    .priv_size     = sizeof(AudioNEqualizerContext),
    .priv_class    = &anequalizer_class,
    .init          = init,
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = inputs,
    .outputs       = NULL,
    .flags         = AVFILTER_FLAG_DYNAMIC_OUTPUTS,
    .process_command = process_command,
}
Definition at line 750 of file af_anequalizer.c.