FFmpeg: libavfilter/af_amix.c File Reference
af_amix.c File Reference
Audio Mix Filter.
#include "libavutil/attributes.h"
#include "libavutil/audio_fifo.h"
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/channel_layout.h"
#include "libavutil/common.h"
#include "libavutil/float_dsp.h"
#include "libavutil/mathematics.h"
#include "libavutil/opt.h"
#include "libavutil/samplefmt.h"
#include "audio.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
Data Structures
struct FrameInfo
struct FrameList
Linked list used to store timestamps and frame sizes of all frames in the FIFO for the first input.
struct MixContext
Macros
#define INPUT_ON 1
input is active
#define INPUT_EOF 2
input has reached EOF (may still be active)
#define DURATION_LONGEST 0
#define DURATION_SHORTEST 1
#define DURATION_FIRST 2
#define OFFSET(x) offsetof(MixContext, x)
#define A AV_OPT_FLAG_AUDIO_PARAM
#define F AV_OPT_FLAG_FILTERING_PARAM
Functions
static void frame_list_clear (FrameList *frame_list)
static int frame_list_next_frame_size (FrameList *frame_list)
static int64_t frame_list_next_pts (FrameList *frame_list)
static void frame_list_remove_samples (FrameList *frame_list, int nb_samples)
static int frame_list_add_frame (FrameList *frame_list, int nb_samples, int64_t pts)
AVFILTER_DEFINE_CLASS (amix)
static void calculate_scales (MixContext *s, int nb_samples)
Update the scaling factors to apply to each input during mixing.
static int config_output (AVFilterLink *outlink)
static int calc_active_inputs (MixContext *s)
Calculates the number of active inputs and determines EOF based on the duration option.
static int output_frame (AVFilterLink *outlink)
Read samples from the input FIFOs, mix, and write to the output link.
static int request_samples (AVFilterContext *ctx, int min_samples)
Requests a frame, if needed, from each input link other than the first.
static int request_frame (AVFilterLink *outlink)
static int filter_frame (AVFilterLink *inlink, AVFrame *buf)
static av_cold int init (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
Variables
static const AVOption amix_options []
static const AVFilterPad avfilter_af_amix_outputs []
AVFilter ff_af_amix
Detailed Description
Audio Mix Filter.
Mixes audio from multiple sources into a single output. The channel layout, sample rate, and sample format will be the same for all inputs and the output.
Definition in file af_amix.c.
Macro Definition Documentation
INPUT_ON
#define INPUT_ON 1
input is active
Definition at line 47 of file af_amix.c.
Referenced by calc_active_inputs(), calculate_scales(), config_output(), output_frame(), request_frame(), and request_samples().
INPUT_EOF
#define INPUT_EOF 2
input has reached EOF (may still be active)
Definition at line 48 of file af_amix.c.
Referenced by output_frame(), and request_samples().
DURATION_LONGEST
#define DURATION_LONGEST 0
Definition at line 50 of file af_amix.c.
DURATION_SHORTEST
#define DURATION_SHORTEST 1
Definition at line 51 of file af_amix.c.
Referenced by calc_active_inputs().
DURATION_FIRST
#define DURATION_FIRST 2
Definition at line 52 of file af_amix.c.
Referenced by calc_active_inputs().
OFFSET
#define OFFSET (x) offsetof(MixContext, x)
Definition at line 175 of file af_amix.c.
A
#define A AV_OPT_FLAG_AUDIO_PARAM
Definition at line 176 of file af_amix.c.
F
#define F AV_OPT_FLAG_FILTERING_PARAM
Definition at line 177 of file af_amix.c.
Function Documentation
frame_list_clear()
static void frame_list_clear (FrameList * frame_list) static
Definition at line 76 of file af_amix.c.
Referenced by frame_list_remove_samples(), and uninit().
frame_list_next_frame_size()
static int frame_list_next_frame_size (FrameList * frame_list) static
Definition at line 90 of file af_amix.c.
Referenced by output_frame(), and request_frame().
frame_list_next_pts()
static int64_t frame_list_next_pts (FrameList * frame_list) static
Definition at line 97 of file af_amix.c.
Referenced by output_frame().
frame_list_remove_samples()
static void frame_list_remove_samples (FrameList * frame_list, int nb_samples) static
Definition at line 104 of file af_amix.c.
Referenced by output_frame().
frame_list_add_frame()
static int frame_list_add_frame (FrameList * frame_list, int nb_samples, int64_t pts) static
Definition at line 131 of file af_amix.c.
Referenced by filter_frame().
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (amix)
calculate_scales()
static void calculate_scales (MixContext * s, int nb_samples) static
Update the scaling factors to apply to each input during mixing.
This balances the full volume range between active inputs and handles volume transitions when EOF is encountered on an input but mixing continues with the remaining inputs.
Definition at line 201 of file af_amix.c.
Referenced by config_output(), and output_frame().
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 218 of file af_amix.c.
calc_active_inputs()
static int calc_active_inputs (MixContext * s) static
Calculates the number of active inputs and determines EOF based on the duration option.
Returns
0 if mixing should continue, or AVERROR_EOF if mixing should stop.
Definition at line 390 of file af_amix.c.
Referenced by config_output(), output_frame(), and request_frame().
output_frame()
static int output_frame (AVFilterLink * outlink) static
Read samples from the input FIFOs, mix, and write to the output link.
Definition at line 271 of file af_amix.c.
Referenced by filter_frame(), request_frame(), and request_samples().
request_samples()
static int request_samples (AVFilterContext * ctx, int min_samples) static
Requests a frame, if needed, from each input link other than the first.
Definition at line 358 of file af_amix.c.
Referenced by request_frame().
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 405 of file af_amix.c.
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * buf) static
Definition at line 436 of file af_amix.c.
Referenced by init().
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 472 of file af_amix.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 498 of file af_amix.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 518 of file af_amix.c.
Variable Documentation
amix_options
const AVOption amix_options[] static
Initial value:
= {
    { "inputs", "Number of inputs.",
            OFFSET(nb_inputs), AV_OPT_TYPE_INT, { .i64 = 2 }, 1, 32, A|F },
    { "duration", "How to determine the end-of-stream.",
            OFFSET(duration_mode), AV_OPT_TYPE_INT, { .i64 = DURATION_LONGEST }, 0,  2, A|F, "duration" },
        { "longest",  "Duration of longest input.",  0, AV_OPT_TYPE_CONST, { .i64 = DURATION_LONGEST  }, INT_MIN, INT_MAX, A|F, "duration" },
        { "shortest", "Duration of shortest input.", 0, AV_OPT_TYPE_CONST, { .i64 = DURATION_SHORTEST }, INT_MIN, INT_MAX, A|F, "duration" },
        { "first",    "Duration of first input.",    0, AV_OPT_TYPE_CONST, { .i64 = DURATION_FIRST    }, INT_MIN, INT_MAX, A|F, "duration" },
    { "dropout_transition", "Transition time, in seconds, for volume "
                            "renormalization when an input stream ends.",
            OFFSET(dropout_transition), AV_OPT_TYPE_FLOAT, { .dbl = 2.0 }, 0, INT_MAX, A|F },
    { NULL }
}
Definition at line 178 of file af_amix.c.
avfilter_af_amix_outputs
const AVFilterPad avfilter_af_amix_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_AUDIO,
        .config_props  = config_output,
        .request_frame = request_frame
    },
    { NULL }
}
Definition at line 544 of file af_amix.c.
ff_af_amix
AVFilter ff_af_amix
Initial value:
= {
    .name           = "amix",
    .description    = NULL_IF_CONFIG_SMALL("Audio mixing."),
    .priv_size      = sizeof(MixContext),
    .priv_class     = &amix_class,
    .init           = init,
    .uninit         = uninit,
    .query_formats  = query_formats,
    .inputs         = NULL,
    .outputs        = avfilter_af_amix_outputs,
    .flags          = AVFILTER_FLAG_DYNAMIC_INPUTS,
}
Definition at line 554 of file af_amix.c.