FFmpeg: libavfilter/af_aecho.c File Reference
af_aecho.c File Reference
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/opt.h"
#include "libavutil/samplefmt.h"
#include "avfilter.h"
#include "audio.h"
#include "internal.h"
Data Structures
struct AudioEchoContext
Macros
#define OFFSET(x) offsetof(AudioEchoContext, x)
#define A AV_OPT_FLAG_AUDIO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
#define MOD(a, b) (((a) >= (b)) ? (a) - (b) : (a))
#define ECHO(name, type, min, max)
Functions
AVFILTER_DEFINE_CLASS (aecho)
static void count_items (char *item_str, int *nb_items)
static void fill_items (char *item_str, int *nb_items, float *items)
static av_cold void uninit (AVFilterContext *ctx)
static av_cold int init (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static int config_output (AVFilterLink *outlink)
static int filter_frame (AVFilterLink *inlink, AVFrame *frame)
static int request_frame (AVFilterLink *outlink)
Variables
static const AVOption aecho_options []
static const AVFilterPad aecho_inputs []
static const AVFilterPad aecho_outputs []
AVFilter ff_af_aecho
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(AudioEchoContext, x)
Definition at line 46 of file af_aecho.c.
A
#define A AV_OPT_FLAG_AUDIO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 47 of file af_aecho.c.
MOD
#define MOD (a, b) (((a) >= (b)) ? (a) - (b) : (a))
Definition at line 183 of file af_aecho.c.
ECHO
#define ECHO (name, type, min, max)
Definition at line 185 of file af_aecho.c.
Referenced by set_tty_echo(), and term_init().
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (aecho)
count_items()
static void count_items (char * item_str, int * nb_items) static
Definition at line 59 of file af_aecho.c.
Referenced by init().
fill_items()
static void fill_items (char * item_str, int * nb_items, float * items) static
Definition at line 71 of file af_aecho.c.
Referenced by init().
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 86 of file af_aecho.c.
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 99 of file af_aecho.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 152 of file af_aecho.c.
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 231 of file af_aecho.c.
Referenced by compressor(), and filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * frame) static
Definition at line 272 of file af_aecho.c.
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 300 of file af_aecho.c.
Variable Documentation
aecho_options
const AVOption aecho_options[] static
Initial value:
= {
    { "in_gain",  "set signal input gain",  OFFSET(in_gain),  AV_OPT_TYPE_FLOAT,  {.dbl=0.6}, 0, 1, A },
    { "out_gain", "set signal output gain", OFFSET(out_gain), AV_OPT_TYPE_FLOAT,  {.dbl=0.3}, 0, 1, A },
    { "delays",   "set list of signal delays", OFFSET(delays), AV_OPT_TYPE_STRING, {.str="1000"}, 0, 0, A },
    { "decays",   "set list of signal decays", OFFSET(decays), AV_OPT_TYPE_STRING, {.str="0.5"}, 0, 0, A },
    { NULL }
}
Definition at line 49 of file af_aecho.c.
aecho_inputs
const AVFilterPad aecho_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_AUDIO,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 335 of file af_aecho.c.
aecho_outputs
const AVFilterPad aecho_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .request_frame = request_frame,
        .config_props  = config_output,
        .type          = AVMEDIA_TYPE_AUDIO,
    },
    { NULL }
}
Definition at line 344 of file af_aecho.c.
ff_af_aecho
AVFilter ff_af_aecho
Initial value:
= {
    .name          = "aecho",
    .description   = NULL_IF_CONFIG_SMALL("Add echoing to the audio."),
    .query_formats = query_formats,
    .priv_size     = sizeof(AudioEchoContext),
    .priv_class    = &aecho_class,
    .init          = init,
    .uninit        = uninit,
    .inputs        = aecho_inputs,
    .outputs       = aecho_outputs,
}
Definition at line 354 of file af_aecho.c.