FFmpeg: libavfilter/af_chorus.c File Reference
af_chorus.c File Reference
chorus audio filter
#include "libavutil/avstring.h"
#include "libavutil/opt.h"
#include "audio.h"
#include "avfilter.h"
#include "internal.h"
#include "generate_wave_table.h"
Data Structures
struct ChorusContext
Macros
#define OFFSET(x) offsetof(ChorusContext, x)
#define A AV_OPT_FLAG_AUDIO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
#define MOD(a, b) (((a) >= (b)) ? (a) - (b) : (a))
Functions
AVFILTER_DEFINE_CLASS (chorus)
static void count_items (char *item_str, int *nb_items)
static void fill_items (char *item_str, int *nb_items, float *items)
static av_cold int init (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static int config_output (AVFilterLink *outlink)
static int filter_frame (AVFilterLink *inlink, AVFrame *frame)
static int request_frame (AVFilterLink *outlink)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const AVOption chorus_options []
static const AVFilterPad chorus_inputs []
static const AVFilterPad chorus_outputs []
AVFilter ff_af_chorus
Detailed Description
chorus audio filter
Definition in file af_chorus.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(ChorusContext, x)
Definition at line 63 of file af_chorus.c.
A
#define A AV_OPT_FLAG_AUDIO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 64 of file af_chorus.c.
MOD
#define MOD (a, b) (((a) >= (b)) ? (a) - (b) : (a))
Definition at line 237 of file af_chorus.c.
Referenced by filter_frame().
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (chorus)
count_items()
static void count_items (char * item_str, int * nb_items) static
Definition at line 78 of file af_chorus.c.
Referenced by init().
fill_items()
static void fill_items (char * item_str, int * nb_items, float * items) static
Definition at line 90 of file af_chorus.c.
Referenced by init().
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 105 of file af_chorus.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 156 of file af_chorus.c.
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 185 of file af_chorus.c.
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * frame) static
Definition at line 239 of file af_chorus.c.
Referenced by request_frame().
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 292 of file af_chorus.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 324 of file af_chorus.c.
Variable Documentation
chorus_options
const AVOption chorus_options[] static
Initial value:
= {
    { "in_gain",  "set input gain",  OFFSET(in_gain),    AV_OPT_TYPE_FLOAT,  {.dbl=.4}, 0, 1, A },
    { "out_gain", "set output gain", OFFSET(out_gain),   AV_OPT_TYPE_FLOAT,  {.dbl=.4}, 0, 1, A },
    { "delays",   "set delays",      OFFSET(delays_str), AV_OPT_TYPE_STRING, {.str=NULL}, 0, 0, A },
    { "decays",   "set decays",      OFFSET(decays_str), AV_OPT_TYPE_STRING, {.str=NULL}, 0, 0, A },
    { "speeds",   "set speeds",      OFFSET(speeds_str), AV_OPT_TYPE_STRING, {.str=NULL}, 0, 0, A },
    { "depths",   "set depths",      OFFSET(depths_str), AV_OPT_TYPE_STRING, {.str=NULL}, 0, 0, A },
    { NULL }
}
Definition at line 66 of file af_chorus.c.
chorus_inputs
const AVFilterPad chorus_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_AUDIO,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 352 of file af_chorus.c.
chorus_outputs
const AVFilterPad chorus_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_AUDIO,
        .request_frame = request_frame,
        .config_props  = config_output,
    },
    { NULL }
}
Definition at line 361 of file af_chorus.c.
ff_af_chorus
AVFilter ff_af_chorus
Initial value:
= {
    .name          = "chorus",
    .description   = NULL_IF_CONFIG_SMALL("Add a chorus effect to the audio."),
    .query_formats = query_formats,
    .priv_size     = sizeof(ChorusContext),
    .priv_class    = &chorus_class,
    .init          = init,
    .uninit        = uninit,
    .inputs        = chorus_inputs,
    .outputs       = chorus_outputs,
}
Definition at line 371 of file af_chorus.c.