FFmpeg: libavfilter/af_pan.c File Reference
af_pan.c File Reference
Audio panning filter (channels mixing) Original code written by Anders Johansson for MPlayer, reimplemented for FFmpeg.
#include <stdio.h>
#include "libavutil/avstring.h"
#include "libavutil/channel_layout.h"
#include "libavutil/opt.h"
#include "libswresample/swresample.h"
#include "audio.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
Data Structures
struct PanContext
Macros
#define MAX_CHANNELS 64
#define OFFSET(x) offsetof(PanContext, x)
Functions
static void skip_spaces (char **arg)
static int parse_channel_name (char **arg, int *rchannel, int *rnamed)
static av_cold int init (AVFilterContext *ctx)
static int are_gains_pure (const PanContext *pan)
static int query_formats (AVFilterContext *ctx)
static int config_props (AVFilterLink *link)
static int filter_frame (AVFilterLink *inlink, AVFrame *insamples)
static av_cold void uninit (AVFilterContext *ctx)
AVFILTER_DEFINE_CLASS (pan)
Variables
static const AVOption pan_options []
static const AVFilterPad pan_inputs []
static const AVFilterPad pan_outputs []
AVFilter ff_af_pan
Detailed Description
Audio panning filter (channels mixing) Original code written by Anders Johansson for MPlayer, reimplemented for FFmpeg.
Definition in file af_pan.c.
Macro Definition Documentation
MAX_CHANNELS
#define MAX_CHANNELS 64
Definition at line 40 of file af_pan.c.
Referenced by are_gains_pure(), config_props(), and parse_channel_name().
OFFSET
#define OFFSET (x) offsetof(PanContext, x)
Definition at line 400 of file af_pan.c.
Function Documentation
skip_spaces()
static void skip_spaces (char ** arg) static
Definition at line 57 of file af_pan.c.
Referenced by init(), and parse_channel_name().
parse_channel_name()
static int parse_channel_name (char ** arg, int * rchannel, int * rnamed) static
Definition at line 65 of file af_pan.c.
Referenced by init().
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 101 of file af_pan.c.
are_gains_pure()
static int are_gains_pure (const PanContext * pan) static
Definition at line 205 of file af_pan.c.
Referenced by query_formats().
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 227 of file af_pan.c.
config_props()
static int config_props (AVFilterLink * link) static
Definition at line 259 of file af_pan.c.
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * insamples) static
Definition at line 373 of file af_pan.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 394 of file af_pan.c.
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (pan)
Variable Documentation
pan_options
const AVOption pan_options[] static
Initial value:
= {
    { "args", NULL, OFFSET(args), AV_OPT_TYPE_STRING, { .str = NULL }, CHAR_MIN, CHAR_MAX, AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_FILTERING_PARAM },
    { NULL }
}
Definition at line 402 of file af_pan.c.
pan_inputs
const AVFilterPad pan_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_AUDIO,
        .config_props = config_props,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 409 of file af_pan.c.
pan_outputs
const AVFilterPad pan_outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_AUDIO,
    },
    { NULL }
}
Definition at line 419 of file af_pan.c.
ff_af_pan
AVFilter ff_af_pan
Initial value:
= {
    .name          = "pan",
    .description   = NULL_IF_CONFIG_SMALL("Remix channels with coefficients (panning)."),
    .priv_size     = sizeof(PanContext),
    .priv_class    = &pan_class,
    .init          = init,
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = pan_inputs,
    .outputs       = pan_outputs,
}
Definition at line 427 of file af_pan.c.