FFmpeg: libavfilter/x86/af_volume_init.c File Reference
af_volume_init.c File Reference
#include "config.h"
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/samplefmt.h"
#include "libavutil/x86/cpu.h"
#include "libavfilter/af_volume.h"
Functions
void ff_scale_samples_s16_sse2 (uint8_t *dst, const uint8_t *src, int len, int volume)
void ff_scale_samples_s32_sse2 (uint8_t *dst, const uint8_t *src, int len, int volume)
void ff_scale_samples_s32_ssse3_atom (uint8_t *dst, const uint8_t *src, int len, int volume)
void ff_scale_samples_s32_avx (uint8_t *dst, const uint8_t *src, int len, int volume)
av_cold void ff_volume_init_x86 (VolumeContext *vol)
Function Documentation
ff_scale_samples_s16_sse2()
void ff_scale_samples_s16_sse2 (uint8_t * dst, const uint8_t * src, int len, int volume)
Referenced by ff_volume_init_x86().
ff_scale_samples_s32_sse2()
void ff_scale_samples_s32_sse2 (uint8_t * dst, const uint8_t * src, int len, int volume)
Referenced by ff_volume_init_x86().
ff_scale_samples_s32_ssse3_atom()
void ff_scale_samples_s32_ssse3_atom (uint8_t * dst, const uint8_t * src, int len, int volume)
Referenced by ff_volume_init_x86().
ff_scale_samples_s32_avx()
void ff_scale_samples_s32_avx (uint8_t * dst, const uint8_t * src, int len, int volume)
Referenced by ff_volume_init_x86().
ff_volume_init_x86()
av_cold void ff_volume_init_x86 (VolumeContext * vol)
Definition at line 36 of file af_volume_init.c.
Referenced by volume_init().