FFmpeg: libavfilter/af_asyncts.c File Reference
af_asyncts.c File Reference
#include <stdint.h>
#include "libavresample/avresample.h"
#include "libavutil/attributes.h"
#include "libavutil/audio_fifo.h"
#include "libavutil/common.h"
#include "libavutil/mathematics.h"
#include "libavutil/opt.h"
#include "libavutil/samplefmt.h"
#include "audio.h"
#include "avfilter.h"
#include "internal.h"
Data Structures
struct ASyncContext
Macros
#define OFFSET(x) offsetof(ASyncContext, x)
#define A AV_OPT_FLAG_AUDIO_PARAM
#define F AV_OPT_FLAG_FILTERING_PARAM
Functions
AVFILTER_DEFINE_CLASS (asyncts)
static av_cold int init (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
static int config_props (AVFilterLink *link)
static int64_t get_delay (ASyncContext *s)
static void handle_trimming (AVFilterContext *ctx)
static int request_frame (AVFilterLink *link)
static int write_to_fifo (ASyncContext *s, AVFrame *buf)
static int filter_frame (AVFilterLink *inlink, AVFrame *buf)
Variables
static const AVOption asyncts_options []
static const AVFilterPad avfilter_af_asyncts_inputs []
static const AVFilterPad avfilter_af_asyncts_outputs []
AVFilter ff_af_asyncts
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(ASyncContext, x)
Definition at line 52 of file af_asyncts.c.
A
#define A AV_OPT_FLAG_AUDIO_PARAM
Definition at line 53 of file af_asyncts.c.
F
#define F AV_OPT_FLAG_FILTERING_PARAM
Definition at line 54 of file af_asyncts.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (asyncts)
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 66 of file af_asyncts.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 76 of file af_asyncts.c.
config_props()
static int config_props (AVFilterLink * link) static
Definition at line 86 of file af_asyncts.c.
get_delay()
static int64_t get_delay (ASyncContext * s) static
Definition at line 115 of file af_asyncts.c.
Referenced by filter_frame(), and request_frame().
handle_trimming()
static void handle_trimming (AVFilterContext * ctx) static
Definition at line 120 of file af_asyncts.c.
Referenced by filter_frame(), and request_frame().
request_frame()
static int request_frame (AVFilterLink * link) static
Definition at line 134 of file af_asyncts.c.
write_to_fifo()
static int write_to_fifo (ASyncContext * s, AVFrame * buf) static
Definition at line 168 of file af_asyncts.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * buf) static
Definition at line 176 of file af_asyncts.c.
Variable Documentation
asyncts_options
const AVOption asyncts_options[] static
Initial value:
= {
    { "compensate", "Stretch/squeeze the data to make it match the timestamps", OFFSET(resample),      AV_OPT_TYPE_BOOL,  { .i64 = 0 },   0, 1,       A|F },
    { "min_delta",  "Minimum difference between timestamps and audio data "
                    "(in seconds) to trigger padding/trimmin the data.",        OFFSET(min_delta_sec), AV_OPT_TYPE_FLOAT, { .dbl = 0.1 }, 0, INT_MAX, A|F },
    { "max_comp",   "Maximum compensation in samples per second.",              OFFSET(max_comp),      AV_OPT_TYPE_INT,   { .i64 = 500 }, 0, INT_MAX, A|F },
    { "first_pts",  "Assume the first pts should be this value.",               OFFSET(first_pts),     AV_OPT_TYPE_INT64, { .i64 = AV_NOPTS_VALUE }, INT64_MIN, INT64_MAX, A|F },
    { NULL }
}
Definition at line 55 of file af_asyncts.c.
avfilter_af_asyncts_inputs
const AVFilterPad avfilter_af_asyncts_inputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_AUDIO,
        .filter_frame  = filter_frame
    },
    { NULL }
}
Definition at line 294 of file af_asyncts.c.
avfilter_af_asyncts_outputs
const AVFilterPad avfilter_af_asyncts_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_AUDIO,
        .config_props  = config_props,
        .request_frame = request_frame
    },
    { NULL }
}
Definition at line 303 of file af_asyncts.c.
ff_af_asyncts
AVFilter ff_af_asyncts
Initial value:
= {
    .name        = "asyncts",
    .description = NULL_IF_CONFIG_SMALL("Sync audio data to timestamps."),
    .init        = init,
    .uninit      = uninit,
    .priv_size   = sizeof(ASyncContext),
    .priv_class  = &asyncts_class,
    .query_formats = ff_query_formats_all_layouts,
    .inputs      = avfilter_af_asyncts_inputs,
    .outputs     = avfilter_af_asyncts_outputs,
}
Definition at line 313 of file af_asyncts.c.