FFmpeg: libavformat/aiffdec.c File Reference
aiffdec.c File Reference
#include "libavutil/intreadwrite.h"
#include "libavutil/mathematics.h"
#include "libavutil/dict.h"
#include "avformat.h"
#include "internal.h"
#include "pcm.h"
#include "aiff.h"
#include "isom.h"
#include "id3v2.h"
#include "mov_chan.h"
Data Structures
struct AIFFInputContext
Macros
#define AIFF 0
#define AIFF_C_VERSION1 0xA2805140
#define MAX_SIZE 4096
Functions
static enum AVCodecID aiff_codec_get_id (int bps)
static int get_tag (AVIOContext *pb, uint32_t *tag)
static void get_meta (AVFormatContext *s, const char *key, int size)
static int get_aiff_header (AVFormatContext *s, int size, unsigned version)
static int aiff_probe (AVProbeData *p)
static int aiff_read_header (AVFormatContext *s)
static int aiff_read_packet (AVFormatContext *s, AVPacket *pkt)
Variables
AVInputFormat ff_aiff_demuxer
Macro Definition Documentation
AIFF
#define AIFF 0
Definition at line 33 of file aiffdec.c.
Referenced by aiff_read_header(), av_register_all(), and get_aiff_header().
AIFF_C_VERSION1
#define AIFF_C_VERSION1 0xA2805140
Definition at line 34 of file aiffdec.c.
Referenced by aiff_read_header(), and get_aiff_header().
MAX_SIZE
#define MAX_SIZE 4096
Definition at line 359 of file aiffdec.c.
Referenced by aiff_read_packet().
Function Documentation
aiff_codec_get_id()
static enum AVCodecID aiff_codec_get_id (int bps) static
Definition at line 41 of file aiffdec.c.
Referenced by get_aiff_header().
get_tag()
static int get_tag (AVIOContext * pb, uint32_t * tag) static
Definition at line 57 of file aiffdec.c.
Referenced by aiff_read_header().
get_meta()
static void get_meta (AVFormatContext * s, const char * key, int size) static
Definition at line 74 of file aiffdec.c.
Referenced by aiff_read_header().
get_aiff_header()
static int get_aiff_header (AVFormatContext * s, int size, unsigned version) static
Definition at line 94 of file aiffdec.c.
Referenced by aiff_read_header().
aiff_probe()
static int aiff_probe (AVProbeData * p) static
Definition at line 195 of file aiffdec.c.
aiff_read_header()
static int aiff_read_header (AVFormatContext * s) static
Definition at line 208 of file aiffdec.c.
aiff_read_packet()
static int aiff_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 361 of file aiffdec.c.
Variable Documentation
ff_aiff_demuxer
AVInputFormat ff_aiff_demuxer
Initial value:
= {
    .name           = "aiff",
    .long_name      = NULL_IF_CONFIG_SMALL("Audio IFF"),
    .priv_data_size = sizeof(AIFFInputContext),
    .read_probe     = aiff_probe,
    .read_header    = aiff_read_header,
    .read_packet    = aiff_read_packet,
    .read_seek      = ff_pcm_read_seek,
    .codec_tag      = (const AVCodecTag* const []){ ff_codec_aiff_tags, 0 },
}
Definition at line 403 of file aiffdec.c.