FFmpeg: libavcodec/alacenc.c File Reference
alacenc.c File Reference
#include "libavutil/opt.h"
#include "avcodec.h"
#include "put_bits.h"
#include "internal.h"
#include "lpc.h"
#include "mathops.h"
#include "alac_data.h"
Data Structures
struct RiceContext
struct AlacLPCContext
struct AlacEncodeContext
Macros
#define DEFAULT_FRAME_SIZE 4096
#define ALAC_EXTRADATA_SIZE 36
#define ALAC_FRAME_HEADER_SIZE 55
#define ALAC_FRAME_FOOTER_SIZE 3
#define ALAC_ESCAPE_CODE 0x1FF
#define ALAC_MAX_LPC_ORDER 30
#define DEFAULT_MAX_PRED_ORDER 6
#define DEFAULT_MIN_PRED_ORDER 4
#define ALAC_MAX_LPC_PRECISION 9
#define ALAC_MIN_LPC_SHIFT 0
#define ALAC_MAX_LPC_SHIFT 9
#define ALAC_CHMODE_LEFT_RIGHT 0
#define ALAC_CHMODE_LEFT_SIDE 1
#define ALAC_CHMODE_RIGHT_SIDE 2
#define ALAC_CHMODE_MID_SIDE 3
#define COPY_SAMPLES(type)
#define OFFSET(x) offsetof(AlacEncodeContext, x)
#define AE AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Functions
static void init_sample_buffers (AlacEncodeContext *s, int channels, const uint8_t *samples[2])
static void encode_scalar (AlacEncodeContext *s, int x, int k, int write_sample_size)
static void write_element_header (AlacEncodeContext *s, enum AlacRawDataBlockType element, int instance)
static void calc_predictor_params (AlacEncodeContext *s, int ch)
static int estimate_stereo_mode (int32_t *left_ch, int32_t *right_ch, int n)
static void alac_stereo_decorrelation (AlacEncodeContext *s)
static void alac_linear_predictor (AlacEncodeContext *s, int ch)
static void alac_entropy_coder (AlacEncodeContext *s, int ch)
static void write_element (AlacEncodeContext *s, enum AlacRawDataBlockType element, int instance, const uint8_t *samples0, const uint8_t *samples1)
static int write_frame (AlacEncodeContext *s, AVPacket *avpkt, uint8_t *const *samples)
static av_always_inline int get_max_frame_size (int frame_size, int ch, int bps)
static av_cold int alac_encode_close (AVCodecContext *avctx)
static av_cold int alac_encode_init (AVCodecContext *avctx)
static int alac_encode_frame (AVCodecContext *avctx, AVPacket *avpkt, const AVFrame *frame, int *got_packet_ptr)
Variables
static const AVOption options []
static const AVClass alacenc_class
AVCodec ff_alac_encoder
Macro Definition Documentation
DEFAULT_FRAME_SIZE
#define DEFAULT_FRAME_SIZE 4096
Definition at line 31 of file alacenc.c.
Referenced by alac_encode_frame(), alac_encode_init(), get_max_frame_size(), and write_element_header().
ALAC_EXTRADATA_SIZE
#define ALAC_EXTRADATA_SIZE 36
Definition at line 32 of file alacenc.c.
Referenced by alac_encode_init().
ALAC_FRAME_HEADER_SIZE
#define ALAC_FRAME_HEADER_SIZE 55
Definition at line 33 of file alacenc.c.
ALAC_FRAME_FOOTER_SIZE
#define ALAC_FRAME_FOOTER_SIZE 3
Definition at line 34 of file alacenc.c.
ALAC_ESCAPE_CODE
#define ALAC_ESCAPE_CODE 0x1FF
Definition at line 36 of file alacenc.c.
Referenced by encode_scalar().
ALAC_MAX_LPC_ORDER
#define ALAC_MAX_LPC_ORDER 30
Definition at line 37 of file alacenc.c.
Referenced by alac_encode_init().
DEFAULT_MAX_PRED_ORDER
#define DEFAULT_MAX_PRED_ORDER 6
Definition at line 38 of file alacenc.c.
DEFAULT_MIN_PRED_ORDER
#define DEFAULT_MIN_PRED_ORDER 4
Definition at line 39 of file alacenc.c.
ALAC_MAX_LPC_PRECISION
#define ALAC_MAX_LPC_PRECISION 9
Definition at line 40 of file alacenc.c.
Referenced by calc_predictor_params().
ALAC_MIN_LPC_SHIFT
#define ALAC_MIN_LPC_SHIFT 0
Definition at line 41 of file alacenc.c.
Referenced by calc_predictor_params().
ALAC_MAX_LPC_SHIFT
#define ALAC_MAX_LPC_SHIFT 9
Definition at line 42 of file alacenc.c.
Referenced by calc_predictor_params().
ALAC_CHMODE_LEFT_RIGHT
#define ALAC_CHMODE_LEFT_RIGHT 0
Definition at line 44 of file alacenc.c.
Referenced by alac_stereo_decorrelation().
ALAC_CHMODE_LEFT_SIDE
#define ALAC_CHMODE_LEFT_SIDE 1
Definition at line 45 of file alacenc.c.
Referenced by alac_stereo_decorrelation().
ALAC_CHMODE_RIGHT_SIDE
#define ALAC_CHMODE_RIGHT_SIDE 2
Definition at line 46 of file alacenc.c.
Referenced by alac_stereo_decorrelation().
ALAC_CHMODE_MID_SIDE
#define ALAC_CHMODE_MID_SIDE 3
Definition at line 47 of file alacenc.c.
COPY_SAMPLES
#define COPY_SAMPLES (type)
Value:
do {                             \
        for (ch = 0; ch < channels; ch++) {                 \
            int32_t       *bptr = s->sample_buf[ch];        \
            const type *sptr = (const type *)samples[ch];   \
            for (i = 0; i < s->frame_size; i++)             \
                bptr[i] = sptr[i] >> shift;                 \
        }                                                   \
    } while (0)
Referenced by init_sample_buffers().
OFFSET
#define OFFSET (x) offsetof(AlacEncodeContext, x)
Definition at line 654 of file alacenc.c.
AE
#define AE AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 655 of file alacenc.c.
Referenced by g726_reset().
Function Documentation
init_sample_buffers()
static void init_sample_buffers (AlacEncodeContext * s, int channels, const uint8_t * samples[2]) static
Definition at line 84 of file alacenc.c.
Referenced by write_element().
encode_scalar()
static void encode_scalar (AlacEncodeContext * s, int x, int k, int write_sample_size) static
Definition at line 106 of file alacenc.c.
Referenced by alac_entropy_coder().
write_element_header()
static void write_element_header (AlacEncodeContext * s, enum AlacRawDataBlockType element, int instance) static
Definition at line 134 of file alacenc.c.
Referenced by write_element().
calc_predictor_params()
static void calc_predictor_params (AlacEncodeContext * s, int ch) static
Definition at line 153 of file alacenc.c.
Referenced by write_element().
estimate_stereo_mode()
static int estimate_stereo_mode (int32_t * left_ch, int32_t * right_ch, int n) static
Definition at line 184 of file alacenc.c.
Referenced by alac_stereo_decorrelation().
alac_stereo_decorrelation()
static void alac_stereo_decorrelation (AlacEncodeContext * s) static
Definition at line 217 of file alacenc.c.
Referenced by write_element().
alac_linear_predictor()
static void alac_linear_predictor (AlacEncodeContext * s, int ch) static
Definition at line 257 of file alacenc.c.
Referenced by write_element().
alac_entropy_coder()
static void alac_entropy_coder (AlacEncodeContext * s, int ch) static
Definition at line 321 of file alacenc.c.
Referenced by write_element().
write_element()
static void write_element (AlacEncodeContext * s, enum AlacRawDataBlockType element, int instance, const uint8_t * samples0, const uint8_t * samples1) static
Definition at line 365 of file alacenc.c.
Referenced by write_frame().
write_frame()
static int write_frame (AlacEncodeContext * s, AVPacket * avpkt, uint8_t *const * samples) static
Definition at line 460 of file alacenc.c.
Referenced by alac_encode_frame().
get_max_frame_size()
static av_always_inline int get_max_frame_size (int frame_size, int ch, int bps) static
Definition at line 491 of file alacenc.c.
Referenced by alac_encode_frame(), and alac_encode_init().
alac_encode_close()
static av_cold int alac_encode_close (AVCodecContext * avctx) static
Definition at line 497 of file alacenc.c.
Referenced by alac_encode_init().
alac_encode_init()
static av_cold int alac_encode_init (AVCodecContext * avctx) static
Definition at line 506 of file alacenc.c.
alac_encode_frame()
static int alac_encode_frame (AVCodecContext * avctx, AVPacket * avpkt, const AVFrame * frame, int * got_packet_ptr) static
Definition at line 614 of file alacenc.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "min_prediction_order", NULL, OFFSET(min_prediction_order), AV_OPT_TYPE_INT, { .i64 = DEFAULT_MIN_PRED_ORDER }, MIN_LPC_ORDER, ALAC_MAX_LPC_ORDER, AE },
    { "max_prediction_order", NULL, OFFSET(max_prediction_order), AV_OPT_TYPE_INT, { .i64 = DEFAULT_MAX_PRED_ORDER }, MIN_LPC_ORDER, ALAC_MAX_LPC_ORDER, AE },
    { NULL },
}
Definition at line 656 of file alacenc.c.
alacenc_class
const AVClass alacenc_class static
Initial value:
= {
    .class_name = "alacenc",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 663 of file alacenc.c.
ff_alac_encoder
AVCodec ff_alac_encoder
Initial value:
= {
    .name           = "alac",
    .long_name      = NULL_IF_CONFIG_SMALL("ALAC (Apple Lossless Audio Codec)"),
    .type           = AVMEDIA_TYPE_AUDIO,
    .id             = AV_CODEC_ID_ALAC,
    .priv_data_size = sizeof(AlacEncodeContext),
    .priv_class     = &alacenc_class,
    .init           = alac_encode_init,
    .encode2        = alac_encode_frame,
    .close          = alac_encode_close,
    .capabilities   = AV_CODEC_CAP_SMALL_LAST_FRAME,
    .channel_layouts = ff_alac_channel_layouts,
    .sample_fmts    = (const enum AVSampleFormat[]){ AV_SAMPLE_FMT_S32P,
                                                     AV_SAMPLE_FMT_S16P,
                                                     AV_SAMPLE_FMT_NONE },
}
Definition at line 670 of file alacenc.c.