FFmpeg: libavcodec/x86/alacdsp_init.c File Reference
alacdsp_init.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/x86/cpu.h"
#include "libavcodec/alacdsp.h"
#include "config.h"
Functions
void ff_alac_decorrelate_stereo_sse4 (int32_t *buffer[2], int nb_samples, int decorr_shift, int decorr_left_weight)
void ff_alac_append_extra_bits_stereo_sse2 (int32_t *buffer[2], int32_t *extra_bits_buffer[2], int extra_bits, int channels, int nb_samples)
void ff_alac_append_extra_bits_mono_sse2 (int32_t *buffer[2], int32_t *extra_bits_buffer[2], int extra_bits, int channels, int nb_samples)
av_cold void ff_alacdsp_init_x86 (ALACDSPContext *c)
Function Documentation
ff_alac_decorrelate_stereo_sse4()
void ff_alac_decorrelate_stereo_sse4 (int32_t * buffer[2], int nb_samples, int decorr_shift, int decorr_left_weight)
Referenced by ff_alacdsp_init_x86().
ff_alac_append_extra_bits_stereo_sse2()
void ff_alac_append_extra_bits_stereo_sse2 (int32_t * buffer[2], int32_t * extra_bits_buffer[2], int extra_bits, int channels, int nb_samples)
Referenced by ff_alacdsp_init_x86().
ff_alac_append_extra_bits_mono_sse2()
void ff_alac_append_extra_bits_mono_sse2 (int32_t * buffer[2], int32_t * extra_bits_buffer[2], int extra_bits, int channels, int nb_samples)
Referenced by ff_alacdsp_init_x86().
ff_alacdsp_init_x86()
av_cold void ff_alacdsp_init_x86 (ALACDSPContext * c)
Definition at line 31 of file alacdsp_init.c.
Referenced by ff_alacdsp_init().