FFmpeg: libavcodec/alac.c File Reference
alac.c File Reference
ALAC (Apple Lossless Audio Codec) decoder.
#include <inttypes.h>
#include "libavutil/channel_layout.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "get_bits.h"
#include "bytestream.h"
#include "internal.h"
#include "thread.h"
#include "unary.h"
#include "mathops.h"
#include "alac_data.h"
#include "alacdsp.h"
Data Structures
struct ALACContext
Macros
#define ALAC_EXTRADATA_SIZE 36
Functions
static unsigned int decode_scalar (GetBitContext *gb, int k, int bps)
static int rice_decompress (ALACContext *alac, int32_t *output_buffer, int nb_samples, int bps, int rice_history_mult)
static int sign_only (int v)
static void lpc_prediction (int32_t *error_buffer, int32_t *buffer_out, int nb_samples, int bps, int16_t *lpc_coefs, int lpc_order, int lpc_quant)
static int decode_element (AVCodecContext *avctx, AVFrame *frame, int ch_index, int channels)
static int alac_decode_frame (AVCodecContext *avctx, void *data, int *got_frame_ptr, AVPacket *avpkt)
static av_cold int alac_decode_close (AVCodecContext *avctx)
static int allocate_buffers (ALACContext *alac)
static int alac_set_info (ALACContext *alac)
static av_cold int alac_decode_init (AVCodecContext *avctx)
Variables
static const AVOption options []
static const AVClass alac_class
AVCodec ff_alac_decoder
Detailed Description
ALAC (Apple Lossless Audio Codec) decoder.
Author
2005 David Hammerton
See also
http://crazney.net/programs/itunes/alac.html
Note: This decoder expects a 36-byte QuickTime atom to be passed through the extradata[_size] fields. This atom is tacked onto the end of an 'alac' stsd atom and has the following format:
32 bits atom size 32 bits tag ("alac") 32 bits tag version (0) 32 bits samples per frame (used when not set explicitly in the frames) 8 bits compatible version (0) 8 bits sample size 8 bits history mult (40) 8 bits initial history (10) 8 bits rice param limit (14) 8 bits channels 16 bits maxRun (255) 32 bits max coded frame size (0 means unknown) 32 bits average bitrate (0 means unknown) 32 bits samplerate
Definition in file alac.c.
Macro Definition Documentation
ALAC_EXTRADATA_SIZE
#define ALAC_EXTRADATA_SIZE 36
Definition at line 62 of file alac.c.
Referenced by alac_decode_init().
Function Documentation
decode_scalar()
static unsigned int decode_scalar (GetBitContext * gb, int k, int bps) inline static
Definition at line 89 of file alac.c.
Referenced by rice_decompress().
rice_decompress()
static int rice_decompress (ALACContext * alac, int32_t * output_buffer, int nb_samples, int bps, int rice_history_mult) static
Definition at line 111 of file alac.c.
Referenced by decode_element().
sign_only()
static int sign_only (int v) inline static
Definition at line 168 of file alac.c.
Referenced by lpc_prediction().
lpc_prediction()
static void lpc_prediction (int32_t * error_buffer, int32_t * buffer_out, int nb_samples, int bps, int16_t * lpc_coefs, int lpc_order, int lpc_quant) static
Definition at line 173 of file alac.c.
Referenced by decode_element().
decode_element()
static int decode_element (AVCodecContext * avctx, AVFrame * frame, int ch_index, int channels) static
Definition at line 236 of file alac.c.
Referenced by alac_decode_frame().
alac_decode_frame()
static int alac_decode_frame (AVCodecContext * avctx, void * data, int * got_frame_ptr, AVPacket * avpkt) static
Definition at line 411 of file alac.c.
alac_decode_close()
static av_cold int alac_decode_close (AVCodecContext * avctx) static
Definition at line 470 of file alac.c.
Referenced by allocate_buffers().
allocate_buffers()
static int allocate_buffers (ALACContext * alac) static
Definition at line 485 of file alac.c.
Referenced by alac_decode_init().
alac_set_info()
static int alac_set_info (ALACContext * alac) static
Definition at line 515 of file alac.c.
Referenced by alac_decode_init().
alac_decode_init()
static av_cold int alac_decode_init (AVCodecContext * avctx) static
Definition at line 546 of file alac.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "extra_bits_bug", "Force non-standard decoding process",
      0x42, AV_OPT_TYPE_BOOL, { .i64 = 0 },
      0, 1, AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_DECODING_PARAM },
    { NULL },
}
Definition at line 609 of file alac.c.
alac_class
const AVClass alac_class static
Initial value:
= {
    .class_name = "alac",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 616 of file alac.c.
ff_alac_decoder
AVCodec ff_alac_decoder
Initial value:
= {
    .name           = "alac",
    .long_name      = NULL_IF_CONFIG_SMALL("ALAC (Apple Lossless Audio Codec)"),
    .type           = AVMEDIA_TYPE_AUDIO,
    .id             = AV_CODEC_ID_ALAC,
    .priv_data_size = sizeof(ALACContext),
    .init           = alac_decode_init,
    .close          = alac_decode_close,
    .decode         = alac_decode_frame,
    .init_thread_copy = ONLY_IF_THREADS_ENABLED(init_thread_copy),
    .capabilities   = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_FRAME_THREADS,
    .priv_class     = &alac_class
}
Definition at line 623 of file alac.c.