FFmpeg: libavdevice/alsa.c File Reference
alsa.c File Reference
ALSA input and output: common code.
#include <alsa/asoundlib.h>
#include "avdevice.h"
#include "libavutil/avassert.h"
#include "libavutil/channel_layout.h"
#include "alsa.h"
Macros
#define MAKE_REORDER_FUNC(NAME, TYPE, CHANNELS, LAYOUT, MAP)
#define MAKE_REORDER_FUNCS(CHANNELS, LAYOUT, MAP)
#define FORMAT_I8 0
#define FORMAT_I16 1
#define FORMAT_I32 2
#define FORMAT_F32 3
#define PICK_REORDER(layout)
Functions
static av_cold snd_pcm_format_t codec_id_to_pcm_format (int codec_id)
MAKE_REORDER_FUNCS (5, out_50, out [0]=in[0];out[1]=in[1];out[2]=in[3];out[3]=in[4];out[4]=in[2];)
av_cold int ff_alsa_open (AVFormatContext *ctx, snd_pcm_stream_t mode, unsigned int *sample_rate, int channels, enum AVCodecID *codec_id)
Open an ALSA PCM.
av_cold int ff_alsa_close (AVFormatContext *s1)
Close the ALSA PCM.
int ff_alsa_xrun_recover (AVFormatContext *s1, int err)
Try to recover from ALSA buffer underrun.
int ff_alsa_extend_reorder_buf (AlsaData *s, int min_size)
int ff_alsa_get_device_list (AVDeviceInfoList *device_list, snd_pcm_stream_t stream_type)
Detailed Description
ALSA input and output: common code.
Author
Luca Abeni (lucabe72 email it)
Benoit Fouet (benoit fouet free fr)
Nicolas George (nicolas george normalesup org)
Definition in file alsa.c.
Macro Definition Documentation
MAKE_REORDER_FUNC
#define MAKE_REORDER_FUNC (NAME, TYPE, CHANNELS, LAYOUT, MAP)
Value:
static void alsa_reorder_ ## NAME ## _ ## LAYOUT(const void *in_v,          \
                                                 void *out_v,               \
                                                 int n)                     \
{                                                                           \
    const TYPE *in = in_v;                                                  \
    TYPE      *out = out_v;                                                 \
                                                                            \
    while (n-- > 0) {                                                       \
        MAP                                                                 \
        in  += CHANNELS;                                                    \
        out += CHANNELS;                                                    \
    }                                                                       \
}
Definition at line 65 of file alsa.c.
MAKE_REORDER_FUNCS
#define MAKE_REORDER_FUNCS (CHANNELS, LAYOUT, MAP)
Value:
MAKE_REORDER_FUNC(int8,  int8_t,  CHANNELS, LAYOUT, MAP) \
    MAKE_REORDER_FUNC(int16, int16_t, CHANNELS, LAYOUT, MAP) \
    MAKE_REORDER_FUNC(int32, int32_t, CHANNELS, LAYOUT, MAP) \
    MAKE_REORDER_FUNC(f32,   float,   CHANNELS, LAYOUT, MAP)
Definition at line 80 of file alsa.c.
FORMAT_I8
#define FORMAT_I8 0
Referenced by MAKE_REORDER_FUNCS().
FORMAT_I16
#define FORMAT_I16 1
Referenced by MAKE_REORDER_FUNCS().
FORMAT_I32
#define FORMAT_I32 2
Referenced by MAKE_REORDER_FUNCS().
FORMAT_F32
#define FORMAT_F32 3
Referenced by MAKE_REORDER_FUNCS().
PICK_REORDER
#define PICK_REORDER (layout)
Value:
switch(format) {\
    case FORMAT_I8:  s->reorder_func = alsa_reorder_int8_out_ ##layout;  break;\
    case FORMAT_I16: s->reorder_func = alsa_reorder_int16_out_ ##layout; break;\
    case FORMAT_I32: s->reorder_func = alsa_reorder_int32_out_ ##layout; break;\
    case FORMAT_F32: s->reorder_func = alsa_reorder_f32_out_ ##layout;   break;\
}
Referenced by MAKE_REORDER_FUNCS().
Function Documentation
codec_id_to_pcm_format()
static av_cold snd_pcm_format_t codec_id_to_pcm_format (int codec_id) static
Definition at line 38 of file alsa.c.
Referenced by ff_alsa_open().
MAKE_REORDER_FUNCS()
MAKE_REORDER_FUNCS (5 , out_50 , out [0] = in[0]; out[1] = in[1]; out[2] = in[3]; out[3] = in[4]; out[4] = in[2];)
Definition at line 86 of file alsa.c.
ff_alsa_open()
av_cold int ff_alsa_open (AVFormatContext * s, snd_pcm_stream_t mode, unsigned int * sample_rate, int channels, enum AVCodecID * codec_id)
Open an ALSA PCM.
Parameters
s media file handle
mode either SND_PCM_STREAM_CAPTURE or SND_PCM_STREAM_PLAYBACK
sample_rate in: requested sample rate; out: actually selected sample rate
channels number of channels
codec_id in: requested AVCodecID or AV_CODEC_ID_NONE; out: actually selected AVCodecID, changed only if AV_CODEC_ID_NONE was requested
Returns
0 if OK, AVERROR_xxx on error
Definition at line 167 of file alsa.c.
Referenced by audio_read_header(), and audio_write_header().
ff_alsa_close()
av_cold int ff_alsa_close (AVFormatContext * s1)
Close the ALSA PCM.
Parameters
s1 media file handle
Returns
0
Definition at line 299 of file alsa.c.
ff_alsa_xrun_recover()
int ff_alsa_xrun_recover (AVFormatContext * s1, int err)
Try to recover from ALSA buffer underrun.
Parameters
s1 media file handle
err error code reported by the previous ALSA call
Returns
0 if OK, AVERROR_xxx on error
Definition at line 310 of file alsa.c.
Referenced by audio_read_packet(), and audio_write_packet().
ff_alsa_extend_reorder_buf()
int ff_alsa_extend_reorder_buf (AlsaData * s, int min_size)
Definition at line 331 of file alsa.c.
Referenced by audio_write_packet().
ff_alsa_get_device_list()
int ff_alsa_get_device_list (AVDeviceInfoList * device_list, snd_pcm_stream_t stream_type)
Definition at line 348 of file alsa.c.
Referenced by audio_get_device_list().