FFmpeg: libavcodec/apedec.c File Reference
apedec.c File Reference
Monkey's Audio lossless audio decoder.
#include <inttypes.h>
#include "libavutil/avassert.h"
#include "libavutil/channel_layout.h"
#include "libavutil/opt.h"
#include "lossless_audiodsp.h"
#include "avcodec.h"
#include "bswapdsp.h"
#include "bytestream.h"
#include "internal.h"
#include "get_bits.h"
#include "unary.h"
Data Structures
struct APEFilter
Filters applied to the decoded data.
struct APERice
struct APERangecoder
struct APEPredictor
Filter histories.
struct APEContext
Decoder context.
Macros
#define MAX_CHANNELS 2
#define MAX_BYTESPERSAMPLE 3
#define APE_FRAMECODE_MONO_SILENCE 1
#define APE_FRAMECODE_STEREO_SILENCE 3
#define APE_FRAMECODE_PSEUDO_STEREO 4
#define HISTORY_SIZE 512
#define PREDICTOR_ORDER 8
#define PREDICTOR_SIZE 50
Total size of all predictor histories.
#define YDELAYA (18 + PREDICTOR_ORDER*4)
#define YDELAYB (18 + PREDICTOR_ORDER*3)
#define XDELAYA (18 + PREDICTOR_ORDER*2)
#define XDELAYB (18 + PREDICTOR_ORDER)
#define YADAPTCOEFFSA 18
#define XADAPTCOEFFSA 14
#define YADAPTCOEFFSB 10
#define XADAPTCOEFFSB 5
#define APE_FILTER_LEVELS 3
#define OFFSET(x) offsetof(APEContext, x)
#define PAR (AV_OPT_FLAG_DECODING_PARAM | AV_OPT_FLAG_AUDIO_PARAM)
Enumerations
enum APECompressionLevel {
COMPRESSION_LEVEL_FAST = 1000, COMPRESSION_LEVEL_NORMAL = 2000, COMPRESSION_LEVEL_HIGH = 3000, COMPRESSION_LEVEL_EXTRA_HIGH = 4000,
COMPRESSION_LEVEL_INSANE = 5000
}
Possible compression levels.
Functions
static void ape_apply_filters (APEContext *ctx, int32_t *decoded0, int32_t *decoded1, int count)
static void entropy_decode_mono_0000 (APEContext *ctx, int blockstodecode)
static void entropy_decode_stereo_0000 (APEContext *ctx, int blockstodecode)
static void entropy_decode_mono_3860 (APEContext *ctx, int blockstodecode)
static void entropy_decode_stereo_3860 (APEContext *ctx, int blockstodecode)
static void entropy_decode_mono_3900 (APEContext *ctx, int blockstodecode)
static void entropy_decode_stereo_3900 (APEContext *ctx, int blockstodecode)
static void entropy_decode_stereo_3930 (APEContext *ctx, int blockstodecode)
static void entropy_decode_mono_3990 (APEContext *ctx, int blockstodecode)
static void entropy_decode_stereo_3990 (APEContext *ctx, int blockstodecode)
static void predictor_decode_mono_3800 (APEContext *ctx, int count)
static void predictor_decode_stereo_3800 (APEContext *ctx, int count)
static void predictor_decode_mono_3930 (APEContext *ctx, int count)
static void predictor_decode_stereo_3930 (APEContext *ctx, int count)
static void predictor_decode_mono_3950 (APEContext *ctx, int count)
static void predictor_decode_stereo_3950 (APEContext *ctx, int count)
static av_cold int ape_decode_close (AVCodecContext *avctx)
static av_cold int ape_decode_init (AVCodecContext *avctx)
static void update_rice (APERice *rice, unsigned int x)
static int get_rice_ook (GetBitContext *gb, int k)
static int ape_decode_value_3860 (APEContext *ctx, GetBitContext *gb, APERice *rice)
static int ape_decode_value_3900 (APEContext *ctx, APERice *rice)
static int ape_decode_value_3990 (APEContext *ctx, APERice *rice)
static void decode_array_0000 (APEContext *ctx, GetBitContext *gb, int32_t *out, APERice *rice, int blockstodecode)
static int init_entropy_decoder (APEContext *ctx)
static void init_predictor_decoder (APEContext *ctx)
static int APESIGN (int32_t x)
Get inverse sign of integer (-1 for positive, 1 for negative and 0 for zero)
static av_always_inline int filter_fast_3320 (APEPredictor *p, const int decoded, const int filter, const int delayA)
static av_always_inline int filter_3800 (APEPredictor *p, const int decoded, const int filter, const int delayA, const int delayB, const int start, const int shift)
static void long_filter_high_3800 (int32_t *buffer, int order, int shift, int length)
static void long_filter_ehigh_3830 (int32_t *buffer, int length)
static av_always_inline int predictor_update_3930 (APEPredictor *p, const int decoded, const int filter, const int delayA)
static av_always_inline int predictor_update_filter (APEPredictor *p, const int decoded, const int filter, const int delayA, const int delayB, const int adaptA, const int adaptB)
static void do_init_filter (APEFilter *f, int16_t *buf, int order)
static void init_filter (APEContext *ctx, APEFilter *f, int16_t *buf, int order)
static void do_apply_filter (APEContext *ctx, int version, APEFilter *f, int32_t *data, int count, int order, int fracbits)
static void apply_filter (APEContext *ctx, APEFilter *f, int32_t *data0, int32_t *data1, int count, int order, int fracbits)
static int init_frame_decoder (APEContext *ctx)
static void ape_unpack_mono (APEContext *ctx, int count)
static void ape_unpack_stereo (APEContext *ctx, int count)
static int ape_decode_frame (AVCodecContext *avctx, void *data, int *got_frame_ptr, AVPacket *avpkt)
static void ape_flush (AVCodecContext *avctx)
Variables
static const uint16_t ape_filter_orders [5][APE_FILTER_LEVELS]
Filter orders depending on compression level.
static const uint8_t ape_filter_fracbits [5][APE_FILTER_LEVELS]
Filter fraction bits depending on compression level.
static const int32_t initial_coeffs_fast_3320 [1]
static const int32_t initial_coeffs_a_3800 [3]
static const int32_t initial_coeffs_b_3800 [2]
static const int32_t initial_coeffs_3930 [4]
static const AVOption options []
static const AVClass ape_decoder_class
AVCodec ff_ape_decoder
APE range decoding functions
#define CODE_BITS 32
#define TOP_VALUE ((unsigned int)1 << (CODE_BITS-1))
#define SHIFT_BITS (CODE_BITS - 9)
#define EXTRA_BITS ((CODE_BITS-2) % 8 + 1)
#define BOTTOM_VALUE (TOP_VALUE >> 8)
#define MODEL_ELEMENTS 64
static const uint16_t counts_3970 [22]
Fixed probabilities for symbols in Monkey Audio version 3.97.
static const uint16_t counts_diff_3970 [21]
Probability ranges for symbols in Monkey Audio version 3.97.
static const uint16_t counts_3980 [22]
Fixed probabilities for symbols in Monkey Audio version 3.98.
static const uint16_t counts_diff_3980 [21]
Probability ranges for symbols in Monkey Audio version 3.98.
static void range_start_decoding (APEContext *ctx)
Start the decoder.
static void range_dec_normalize (APEContext *ctx)
Perform normalization.
static int range_decode_culfreq (APEContext *ctx, int tot_f)
Calculate cumulative frequency for next symbol.
static int range_decode_culshift (APEContext *ctx, int shift)
Decode value with given size in bits.
static void range_decode_update (APEContext *ctx, int sy_f, int lt_f)
Update decoding state.
static int range_decode_bits (APEContext *ctx, int n)
Decode n bits (n <= 16) without modelling.
static int range_get_symbol (APEContext *ctx, const uint16_t counts[], const uint16_t counts_diff[])
Decode symbol.
Detailed Description
Monkey's Audio lossless audio decoder.
Definition in file apedec.c.
Macro Definition Documentation
MAX_CHANNELS
#define MAX_CHANNELS 2
Definition at line 41 of file apedec.c.
MAX_BYTESPERSAMPLE
#define MAX_BYTESPERSAMPLE 3
Definition at line 42 of file apedec.c.
APE_FRAMECODE_MONO_SILENCE
#define APE_FRAMECODE_MONO_SILENCE 1
Definition at line 44 of file apedec.c.
APE_FRAMECODE_STEREO_SILENCE
#define APE_FRAMECODE_STEREO_SILENCE 3
Definition at line 45 of file apedec.c.
Referenced by ape_unpack_mono(), and ape_unpack_stereo().
APE_FRAMECODE_PSEUDO_STEREO
#define APE_FRAMECODE_PSEUDO_STEREO 4
Definition at line 46 of file apedec.c.
Referenced by ape_decode_frame().
HISTORY_SIZE
#define HISTORY_SIZE 512
Definition at line 48 of file apedec.c.
Referenced by ape_decode_init(), do_apply_filter(), init_filter(), predictor_decode_mono_3800(), predictor_decode_mono_3930(), predictor_decode_mono_3950(), predictor_decode_stereo_3800(), predictor_decode_stereo_3930(), and predictor_decode_stereo_3950().
PREDICTOR_ORDER
#define PREDICTOR_ORDER 8
Definition at line 49 of file apedec.c.
PREDICTOR_SIZE
#define PREDICTOR_SIZE 50
Total size of all predictor histories.
Definition at line 51 of file apedec.c.
Referenced by init_predictor_decoder(), predictor_decode_mono_3800(), predictor_decode_mono_3930(), predictor_decode_mono_3950(), predictor_decode_stereo_3800(), predictor_decode_stereo_3930(), and predictor_decode_stereo_3950().
YDELAYA
#define YDELAYA (18 + PREDICTOR_ORDER*4)
Definition at line 53 of file apedec.c.
Referenced by predictor_decode_mono_3800(), predictor_decode_mono_3930(), predictor_decode_mono_3950(), predictor_decode_stereo_3800(), predictor_decode_stereo_3930(), and predictor_decode_stereo_3950().
YDELAYB
#define YDELAYB (18 + PREDICTOR_ORDER*3)
Definition at line 54 of file apedec.c.
Referenced by predictor_decode_mono_3800(), predictor_decode_stereo_3800(), and predictor_decode_stereo_3950().
XDELAYA
#define XDELAYA (18 + PREDICTOR_ORDER*2)
Definition at line 55 of file apedec.c.
Referenced by predictor_decode_stereo_3800(), predictor_decode_stereo_3930(), and predictor_decode_stereo_3950().
XDELAYB
#define XDELAYB (18 + PREDICTOR_ORDER)
Definition at line 56 of file apedec.c.
Referenced by predictor_decode_stereo_3800(), and predictor_decode_stereo_3950().
YADAPTCOEFFSA
#define YADAPTCOEFFSA 18
Definition at line 58 of file apedec.c.
Referenced by predictor_decode_mono_3950(), and predictor_decode_stereo_3950().
XADAPTCOEFFSA
#define XADAPTCOEFFSA 14
Definition at line 59 of file apedec.c.
Referenced by predictor_decode_stereo_3950().
YADAPTCOEFFSB
#define YADAPTCOEFFSB 10
Definition at line 60 of file apedec.c.
Referenced by predictor_decode_stereo_3950().
XADAPTCOEFFSB
#define XADAPTCOEFFSB 5
Definition at line 61 of file apedec.c.
Referenced by predictor_decode_stereo_3950().
APE_FILTER_LEVELS
#define APE_FILTER_LEVELS 3
Definition at line 76 of file apedec.c.
Referenced by ape_apply_filters(), ape_decode_close(), ape_decode_init(), and init_frame_decoder().
CODE_BITS
#define CODE_BITS 32
Definition at line 311 of file apedec.c.
TOP_VALUE
#define TOP_VALUE ((unsigned int)1 << (CODE_BITS-1))
Definition at line 312 of file apedec.c.
SHIFT_BITS
#define SHIFT_BITS (CODE_BITS - 9)
Definition at line 313 of file apedec.c.
EXTRA_BITS
#define EXTRA_BITS ((CODE_BITS-2) % 8 + 1)
Definition at line 314 of file apedec.c.
Referenced by range_start_decoding().
BOTTOM_VALUE
#define BOTTOM_VALUE (TOP_VALUE >> 8)
Definition at line 315 of file apedec.c.
Referenced by range_dec_normalize().
MODEL_ELEMENTS
#define MODEL_ELEMENTS 64
Definition at line 388 of file apedec.c.
Referenced by ape_decode_value_3900(), and ape_decode_value_3990().
OFFSET
#define OFFSET (x) offsetof(APEContext, x)
Definition at line 1560 of file apedec.c.
PAR
#define PAR (AV_OPT_FLAG_DECODING_PARAM | AV_OPT_FLAG_AUDIO_PARAM)
Definition at line 1561 of file apedec.c.
Enumeration Type Documentation
APECompressionLevel
enum APECompressionLevel
Possible compression levels.
Enumerator
COMPRESSION_LEVEL_FAST
COMPRESSION_LEVEL_NORMAL
COMPRESSION_LEVEL_HIGH
COMPRESSION_LEVEL_EXTRA_HIGH
COMPRESSION_LEVEL_INSANE
Definition at line 67 of file apedec.c.
Function Documentation
ape_apply_filters()
static void ape_apply_filters (APEContext * ctx, int32_t * decoded0, int32_t * decoded1, int count) static
Definition at line 1328 of file apedec.c.
Referenced by predictor_decode_mono_3930(), predictor_decode_mono_3950(), predictor_decode_stereo_3930(), and predictor_decode_stereo_3950().
entropy_decode_mono_0000()
static void entropy_decode_mono_0000 (APEContext * ctx, int blockstodecode) static
Definition at line 632 of file apedec.c.
Referenced by ape_decode_init().
entropy_decode_stereo_0000()
static void entropy_decode_stereo_0000 (APEContext * ctx, int blockstodecode) static
Definition at line 638 of file apedec.c.
Referenced by ape_decode_init().
entropy_decode_mono_3860()
static void entropy_decode_mono_3860 (APEContext * ctx, int blockstodecode) static
Definition at line 646 of file apedec.c.
Referenced by ape_decode_init().
entropy_decode_stereo_3860()
static void entropy_decode_stereo_3860 (APEContext * ctx, int blockstodecode) static
Definition at line 654 of file apedec.c.
Referenced by ape_decode_init().
entropy_decode_mono_3900()
static void entropy_decode_mono_3900 (APEContext * ctx, int blockstodecode) static
Definition at line 666 of file apedec.c.
Referenced by ape_decode_init().
entropy_decode_stereo_3900()
static void entropy_decode_stereo_3900 (APEContext * ctx, int blockstodecode) static
Definition at line 674 of file apedec.c.
Referenced by ape_decode_init().
entropy_decode_stereo_3930()
static void entropy_decode_stereo_3930 (APEContext * ctx, int blockstodecode) static
Definition at line 690 of file apedec.c.
Referenced by ape_decode_init().
entropy_decode_mono_3990()
static void entropy_decode_mono_3990 (APEContext * ctx, int blockstodecode) static
Definition at line 701 of file apedec.c.
Referenced by ape_decode_init().
entropy_decode_stereo_3990()
static void entropy_decode_stereo_3990 (APEContext * ctx, int blockstodecode) static
Definition at line 709 of file apedec.c.
Referenced by ape_decode_init().
predictor_decode_mono_3800()
static void predictor_decode_mono_3800 (APEContext * ctx, int count) static
Definition at line 990 of file apedec.c.
Referenced by ape_decode_init().
predictor_decode_stereo_3800()
static void predictor_decode_stereo_3800 (APEContext * ctx, int count) static
Definition at line 935 of file apedec.c.
Referenced by ape_decode_init().
predictor_decode_mono_3930()
static void predictor_decode_mono_3930 (APEContext * ctx, int count) static
Definition at line 1093 of file apedec.c.
Referenced by ape_decode_init().
predictor_decode_stereo_3930()
static void predictor_decode_stereo_3930 (APEContext * ctx, int count) static
Definition at line 1065 of file apedec.c.
Referenced by ape_decode_init().
predictor_decode_mono_3950()
static void predictor_decode_mono_3950 (APEContext * ctx, int count) static
Definition at line 1191 of file apedec.c.
Referenced by ape_decode_init().
predictor_decode_stereo_3950()
static void predictor_decode_stereo_3950 (APEContext * ctx, int count) static
Definition at line 1162 of file apedec.c.
Referenced by ape_decode_init().
ape_decode_close()
static av_cold int ape_decode_close (AVCodecContext * avctx) static
Definition at line 200 of file apedec.c.
Referenced by ape_decode_init().
ape_decode_init()
static av_cold int ape_decode_init (AVCodecContext * avctx) static
Definition at line 215 of file apedec.c.
range_start_decoding()
static void range_start_decoding (APEContext * ctx) inline static
Start the decoder.
Definition at line 318 of file apedec.c.
Referenced by entropy_decode_stereo_3900(), and init_entropy_decoder().
range_dec_normalize()
static void range_dec_normalize (APEContext * ctx) inline static
Perform normalization.
Definition at line 326 of file apedec.c.
Referenced by entropy_decode_stereo_3900(), range_decode_culfreq(), and range_decode_culshift().
range_decode_culfreq()
static int range_decode_culfreq (APEContext * ctx, int tot_f) inline static
Calculate cumulative frequency for next symbol.
Does NO update!
Parameters
ctx decoder context
tot_f is the total frequency or (code_value)1<<shift
Returns
the cumulative frequency
Definition at line 347 of file apedec.c.
Referenced by ape_decode_value_3990().
range_decode_culshift()
static int range_decode_culshift (APEContext * ctx, int shift) inline static
Decode value with given size in bits.
Parameters
ctx decoder context
shift number of bits to decode
Definition at line 359 of file apedec.c.
Referenced by range_decode_bits(), and range_get_symbol().
range_decode_update()
static void range_decode_update (APEContext * ctx, int sy_f, int lt_f) inline static
Update decoding state.
Parameters
ctx decoder context
sy_f the interval length (frequency of the symbol)
lt_f the lower end (frequency sum of < symbols)
Definition at line 373 of file apedec.c.
Referenced by ape_decode_value_3990(), range_decode_bits(), and range_get_symbol().
range_decode_bits()
static int range_decode_bits (APEContext * ctx, int n) inline static
Decode n bits (n <= 16) without modelling.
Definition at line 380 of file apedec.c.
Referenced by ape_decode_value_3900(), and ape_decode_value_3990().
range_get_symbol()
static int range_get_symbol (APEContext * ctx, const uint16_t counts[], const uint16_t counts_diff[]) inline static
Decode symbol.
Parameters
ctx decoder context
counts probability range start position
counts_diff probability range widths
Definition at line 432 of file apedec.c.
Referenced by ape_decode_value_3900(), and ape_decode_value_3990().
update_rice()
static void update_rice (APERice * rice, unsigned int x) inline static
Definition at line 456 of file apedec.c.
Referenced by ape_decode_value_3900(), and ape_decode_value_3990().
get_rice_ook()
static int get_rice_ook (GetBitContext * gb, int k) inline static
Definition at line 467 of file apedec.c.
Referenced by decode_array_0000().
ape_decode_value_3860()
static int ape_decode_value_3860 (APEContext * ctx, GetBitContext * gb, APERice * rice) inline static
Definition at line 479 of file apedec.c.
Referenced by entropy_decode_mono_3860(), and entropy_decode_stereo_3860().
ape_decode_value_3900()
static int ape_decode_value_3900 (APEContext * ctx, APERice * rice) inline static
Definition at line 511 of file apedec.c.
Referenced by entropy_decode_mono_3900(), entropy_decode_stereo_3900(), and entropy_decode_stereo_3930().
ape_decode_value_3990()
static int ape_decode_value_3990 (APEContext * ctx, APERice * rice) inline static
Definition at line 545 of file apedec.c.
Referenced by entropy_decode_mono_3990(), and entropy_decode_stereo_3990().
decode_array_0000()
static void decode_array_0000 (APEContext * ctx, GetBitContext * gb, int32_t * out, APERice * rice, int blockstodecode) static
Definition at line 588 of file apedec.c.
Referenced by entropy_decode_mono_0000(), and entropy_decode_stereo_0000().
init_entropy_decoder()
static int init_entropy_decoder (APEContext * ctx) static
Definition at line 720 of file apedec.c.
Referenced by init_frame_decoder().
init_predictor_decoder()
static void init_predictor_decoder (APEContext * ctx) static
Definition at line 773 of file apedec.c.
Referenced by init_frame_decoder().
APESIGN()
static int APESIGN (int32_t x) inline static
Get inverse sign of integer (-1 for positive, 1 for negative and 0 for zero)
Definition at line 814 of file apedec.c.
Referenced by do_apply_filter(), filter_3800(), long_filter_ehigh_3830(), long_filter_high_3800(), predictor_decode_mono_3950(), predictor_update_3930(), and predictor_update_filter().
filter_fast_3320()
static av_always_inline int filter_fast_3320 (APEPredictor * p, const int decoded, const int filter, const int delayA) static
Definition at line 818 of file apedec.c.
Referenced by predictor_decode_mono_3800(), and predictor_decode_stereo_3800().
filter_3800()
static av_always_inline int filter_3800 (APEPredictor * p, const int decoded, const int filter, const int delayA, const int delayB, const int start, const int shift) static
Definition at line 844 of file apedec.c.
Referenced by predictor_decode_mono_3800(), and predictor_decode_stereo_3800().
long_filter_high_3800()
static void long_filter_high_3800 (int32_t * buffer, int order, int shift, int length) static
Definition at line 889 of file apedec.c.
Referenced by predictor_decode_mono_3800(), and predictor_decode_stereo_3800().
long_filter_ehigh_3830()
static void long_filter_ehigh_3830 (int32_t * buffer, int length) static
Definition at line 915 of file apedec.c.
Referenced by predictor_decode_mono_3800(), and predictor_decode_stereo_3800().
predictor_update_3930()
static av_always_inline int predictor_update_3930 (APEPredictor * p, const int decoded, const int filter, const int delayA) static
Definition at line 1035 of file apedec.c.
Referenced by predictor_decode_mono_3930(), and predictor_decode_stereo_3930().
predictor_update_filter()
static av_always_inline int predictor_update_filter (APEPredictor * p, const int decoded, const int filter, const int delayA, const int delayB, const int adaptA, const int adaptB) static
Definition at line 1115 of file apedec.c.
Referenced by predictor_decode_stereo_3950().
do_init_filter()
static void do_init_filter (APEFilter * f, int16_t * buf, int order) static
Definition at line 1239 of file apedec.c.
Referenced by init_filter().
init_filter()
static void init_filter (APEContext * ctx, APEFilter * f, int16_t * buf, int order) static
Definition at line 1251 of file apedec.c.
Referenced by init_frame_decoder().
do_apply_filter()
static void do_apply_filter (APEContext * ctx, int version, APEFilter * f, int32_t * data, int count, int order, int fracbits) static
Definition at line 1257 of file apedec.c.
Referenced by apply_filter().
apply_filter()
static void apply_filter (APEContext * ctx, APEFilter * f, int32_t * data0, int32_t * data1, int count, int order, int fracbits) static
Definition at line 1319 of file apedec.c.
Referenced by ape_apply_filters().
init_frame_decoder()
static int init_frame_decoder (APEContext * ctx) static
Definition at line 1342 of file apedec.c.
Referenced by ape_decode_frame().
ape_unpack_mono()
static void ape_unpack_mono (APEContext * ctx, int count) static
Definition at line 1358 of file apedec.c.
Referenced by ape_decode_frame().
ape_unpack_stereo()
static void ape_unpack_stereo (APEContext * ctx, int count) static
Definition at line 1377 of file apedec.c.
Referenced by ape_decode_frame().
ape_decode_frame()
static int ape_decode_frame (AVCodecContext * avctx, void * data, int * got_frame_ptr, AVPacket * avpkt) static
Definition at line 1404 of file apedec.c.
ape_flush()
static void ape_flush (AVCodecContext * avctx) static
Definition at line 1554 of file apedec.c.
Variable Documentation
ape_filter_orders
const uint16_t ape_filter_orders[5][APE_FILTER_LEVELS] static
Initial value:
= {
    {  0,   0,    0 },
    { 16,   0,    0 },
    { 64,   0,    0 },
    { 32, 256,    0 },
    { 16, 256, 1280 }
}
Filter orders depending on compression level.
Definition at line 79 of file apedec.c.
Referenced by ape_apply_filters(), ape_decode_init(), and init_frame_decoder().
ape_filter_fracbits
const uint8_t ape_filter_fracbits[5][APE_FILTER_LEVELS] static
Initial value:
= {
    {  0,  0,  0 },
    { 11,  0,  0 },
    { 11,  0,  0 },
    { 10, 13,  0 },
    { 11, 13, 15 }
}
Filter fraction bits depending on compression level.
Definition at line 88 of file apedec.c.
Referenced by ape_apply_filters().
counts_3970
const uint16_t counts_3970[22] static
Initial value:
= {
        0, 14824, 28224, 39348, 47855, 53994, 58171, 60926,
    62682, 63786, 64463, 64878, 65126, 65276, 65365, 65419,
    65450, 65469, 65480, 65487, 65491, 65493,
}
Fixed probabilities for symbols in Monkey Audio version 3.97.
Definition at line 393 of file apedec.c.
Referenced by ape_decode_value_3900().
counts_diff_3970
const uint16_t counts_diff_3970[21] static
Initial value:
= {
    14824, 13400, 11124, 8507, 6139, 4177, 2755, 1756,
    1104, 677, 415, 248, 150, 89, 54, 31,
    19, 11, 7, 4, 2,
}
Probability ranges for symbols in Monkey Audio version 3.97.
Definition at line 402 of file apedec.c.
Referenced by ape_decode_value_3900().
counts_3980
const uint16_t counts_3980[22] static
Initial value:
= {
        0, 19578, 36160, 48417, 56323, 60899, 63265, 64435,
    64971, 65232, 65351, 65416, 65447, 65466, 65476, 65482,
    65485, 65488, 65490, 65491, 65492, 65493,
}
Fixed probabilities for symbols in Monkey Audio version 3.98.
Definition at line 411 of file apedec.c.
Referenced by ape_decode_value_3990().
counts_diff_3980
const uint16_t counts_diff_3980[21] static
Initial value:
= {
    19578, 16582, 12257, 7906, 4576, 2366, 1170, 536,
    261, 119, 65, 31, 19, 10, 6, 3,
    3, 2, 1, 1, 1,
}
Probability ranges for symbols in Monkey Audio version 3.98.
Definition at line 420 of file apedec.c.
Referenced by ape_decode_value_3990().
initial_coeffs_fast_3320
const int32_t initial_coeffs_fast_3320[1] static
Initial value:
= {
    375,
}
Definition at line 757 of file apedec.c.
Referenced by init_predictor_decoder().
initial_coeffs_a_3800
const int32_t initial_coeffs_a_3800[3] static
Initial value:
= {
    64, 115, 64,
}
Definition at line 761 of file apedec.c.
Referenced by init_predictor_decoder().
initial_coeffs_b_3800
const int32_t initial_coeffs_b_3800[2] static
Initial value:
= {
    740, 0
}
Definition at line 765 of file apedec.c.
Referenced by init_predictor_decoder().
initial_coeffs_3930
const int32_t initial_coeffs_3930[4] static
Initial value:
= {
    360, 317, -109, 98
}
Definition at line 769 of file apedec.c.
Referenced by init_predictor_decoder().
options
const AVOption options[] static
Initial value:
= {
    { "max_samples", "maximum number of samples decoded per call",             OFFSET(blocks_per_loop), AV_OPT_TYPE_INT,   { .i64 = 4608 },    1,       INT_MAX, PAR, "max_samples" },
    { "all",         "no maximum. decode all samples for each packet at once", 0,                       AV_OPT_TYPE_CONST, { .i64 = INT_MAX }, INT_MIN, INT_MAX, PAR, "max_samples" },
    { NULL},
}
Definition at line 1562 of file apedec.c.
ape_decoder_class
const AVClass ape_decoder_class static
Initial value:
= {
    .class_name = "APE decoder",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1568 of file apedec.c.
ff_ape_decoder
AVCodec ff_ape_decoder
Initial value:
= {
    .name           = "ape",
    .long_name      = NULL_IF_CONFIG_SMALL("Monkey's Audio"),
    .type           = AVMEDIA_TYPE_AUDIO,
    .id             = AV_CODEC_ID_APE,
    .priv_data_size = sizeof(APEContext),
    .init           = ape_decode_init,
    .close          = ape_decode_close,
    .decode         = ape_decode_frame,
    .capabilities   = AV_CODEC_CAP_SUBFRAMES | AV_CODEC_CAP_DELAY |
                      AV_CODEC_CAP_DR1,
    .flush          = ape_flush,
    .sample_fmts    = (const enum AVSampleFormat[]) { AV_SAMPLE_FMT_U8P,
                                                      AV_SAMPLE_FMT_S16P,
                                                      AV_SAMPLE_FMT_S32P,
                                                      AV_SAMPLE_FMT_NONE },
    .priv_class     = &ape_decoder_class,
}
Definition at line 1575 of file apedec.c.