FFmpeg: libavformat/apetag.c File Reference
apetag.c File Reference
#include <inttypes.h>
#include "libavutil/intreadwrite.h"
#include "libavutil/dict.h"
#include "avformat.h"
#include "avio_internal.h"
#include "apetag.h"
#include "internal.h"
Macros
#define APE_TAG_FLAG_CONTAINS_HEADER (1 << 31)
#define APE_TAG_FLAG_CONTAINS_FOOTER (1 << 30)
#define APE_TAG_FLAG_IS_HEADER (1 << 29)
#define APE_TAG_FLAG_IS_BINARY (1 << 1)
Functions
static int ape_tag_read_field (AVFormatContext *s)
int64_t ff_ape_parse_tag (AVFormatContext *s)
Read and parse an APE tag.
static int string_is_ascii (const uint8_t *str)
int ff_ape_write_tag (AVFormatContext *s)
Write an APE tag into a file.
Macro Definition Documentation
APE_TAG_FLAG_CONTAINS_HEADER
#define APE_TAG_FLAG_CONTAINS_HEADER (1 << 31)
Definition at line 32 of file apetag.c.
Referenced by ff_ape_write_tag().
APE_TAG_FLAG_CONTAINS_FOOTER
#define APE_TAG_FLAG_CONTAINS_FOOTER (1 << 30)
Definition at line 33 of file apetag.c.
Referenced by ff_ape_write_tag().
APE_TAG_FLAG_IS_HEADER
#define APE_TAG_FLAG_IS_HEADER (1 << 29)
Definition at line 34 of file apetag.c.
Referenced by ff_ape_parse_tag(), and ff_ape_write_tag().
APE_TAG_FLAG_IS_BINARY
#define APE_TAG_FLAG_IS_BINARY (1 << 1)
Definition at line 35 of file apetag.c.
Referenced by ape_tag_read_field().
Function Documentation
ape_tag_read_field()
static int ape_tag_read_field (AVFormatContext * s) static
Definition at line 37 of file apetag.c.
Referenced by ff_ape_parse_tag().
ff_ape_parse_tag()
int64_t ff_ape_parse_tag (AVFormatContext * s)
Read and parse an APE tag.
Returns
offset of the tag start in the file
Definition at line 118 of file apetag.c.
Referenced by adts_aac_read_header(), ape_read_header(), mpc8_read_header(), mpc_read_header(), tak_read_header(), tta_read_header(), and wv_read_header().
string_is_ascii()
static int string_is_ascii (const uint8_t * str) static
Definition at line 175 of file apetag.c.
Referenced by ff_ape_write_tag().
ff_ape_write_tag()
int ff_ape_write_tag (AVFormatContext * s)
Write an APE tag into a file.
Definition at line 181 of file apetag.c.
Referenced by adts_write_trailer(), tta_write_trailer(), and wv_write_trailer().