FFmpeg: libavformat/apetag.h File Reference
apetag.h File Reference
#include "avformat.h"
Macros
#define APE_TAG_PREAMBLE "APETAGEX"
#define APE_TAG_VERSION 2000
#define APE_TAG_FOOTER_BYTES 32
Functions
int64_t ff_ape_parse_tag (AVFormatContext *s)
Read and parse an APE tag.
int ff_ape_write_tag (AVFormatContext *s)
Write an APE tag into a file.
Macro Definition Documentation
APE_TAG_PREAMBLE
#define APE_TAG_PREAMBLE "APETAGEX"
Definition at line 28 of file apetag.h.
Referenced by ff_ape_parse_tag().
APE_TAG_VERSION
#define APE_TAG_VERSION 2000
Definition at line 29 of file apetag.h.
Referenced by ff_ape_parse_tag(), and ff_ape_write_tag().
APE_TAG_FOOTER_BYTES
#define APE_TAG_FOOTER_BYTES 32
Definition at line 30 of file apetag.h.
Referenced by ff_ape_parse_tag().
Function Documentation
ff_ape_parse_tag()
int64_t ff_ape_parse_tag (AVFormatContext * s)
Read and parse an APE tag.
Returns
offset of the tag start in the file
Definition at line 118 of file apetag.c.
Referenced by adts_aac_read_header(), ape_read_header(), mpc8_read_header(), mpc_read_header(), tak_read_header(), tta_read_header(), and wv_read_header().
ff_ape_write_tag()
int ff_ape_write_tag (AVFormatContext * s)
Write an APE tag into a file.
Definition at line 181 of file apetag.c.
Referenced by adts_write_trailer(), tta_write_trailer(), and wv_write_trailer().