FFmpeg: tests/api/api-codec-param-test.c File Reference
api-codec-param-test.c File Reference
#include <stdio.h>
#include "libavformat/avformat.h"
#include "libavutil/pixdesc.h"
#include "libavcodec/internal.h"
#include "libavutil/avassert.h"
#include "libavutil/opt.h"
Functions
static int try_decode_video_frame (AVCodecContext *codec_ctx, AVPacket *pkt, int decode)
static int find_video_stream_info (AVFormatContext *fmt_ctx, int decode)
static void dump_video_streams (const AVFormatContext *fmt_ctx, int decode)
static int open_and_probe_video_streams (AVFormatContext **fmt_ctx, const char *filename, int decode)
static int check_video_streams (const AVFormatContext *fmt_ctx1, const AVFormatContext *fmt_ctx2)
int main (int argc, char *argv[])
Function Documentation
try_decode_video_frame()
static int try_decode_video_frame (AVCodecContext * codec_ctx, AVPacket * pkt, int decode) static
Definition at line 30 of file api-codec-param-test.c.
Referenced by find_video_stream_info().
find_video_stream_info()
static int find_video_stream_info (AVFormatContext * fmt_ctx, int decode) static
Definition at line 77 of file api-codec-param-test.c.
Referenced by open_and_probe_video_streams().
dump_video_streams()
static void dump_video_streams (const AVFormatContext * fmt_ctx, int decode) static
Definition at line 141 of file api-codec-param-test.c.
Referenced by open_and_probe_video_streams().
open_and_probe_video_streams()
static int open_and_probe_video_streams (AVFormatContext ** fmt_ctx, const char * filename, int decode) static
Definition at line 168 of file api-codec-param-test.c.
Referenced by main().
check_video_streams()
static int check_video_streams (const AVFormatContext * fmt_ctx1, const AVFormatContext * fmt_ctx2) static
Definition at line 189 of file api-codec-param-test.c.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 228 of file api-codec-param-test.c.