FFmpeg: tests/api/api-flac-test.c File Reference
api-flac-test.c File Reference
#include "libavcodec/avcodec.h"
#include "libavutil/common.h"
#include "libavutil/samplefmt.h"
Macros
#define NUMBER_OF_FRAMES 200
#define NAME_BUFF_SIZE 100
Functions
static int generate_raw_frame (uint16_t *frame_data, int i, int sample_rate, int channels, int frame_size)
static int init_encoder (AVCodec *enc, AVCodecContext **enc_ctx, int64_t ch_layout, int sample_rate)
static int init_decoder (AVCodec *dec, AVCodecContext **dec_ctx, int64_t ch_layout)
static int run_test (AVCodec *enc, AVCodec *dec, AVCodecContext *enc_ctx, AVCodecContext *dec_ctx)
static int close_encoder (AVCodecContext **enc_ctx)
static int close_decoder (AVCodecContext **dec_ctx)
int main (void)
Macro Definition Documentation
NUMBER_OF_FRAMES
#define NUMBER_OF_FRAMES 200
Definition at line 34 of file api-flac-test.c.
Referenced by run_test().
NAME_BUFF_SIZE
#define NAME_BUFF_SIZE 100
Definition at line 35 of file api-flac-test.c.
Referenced by init_encoder().
Function Documentation
generate_raw_frame()
static int generate_raw_frame (uint16_t * frame_data, int i, int sample_rate, int channels, int frame_size) static
Definition at line 38 of file api-flac-test.c.
Referenced by run_test().
init_encoder()
static int init_encoder (AVCodec * enc, AVCodecContext ** enc_ctx, int64_t ch_layout, int sample_rate) static
Definition at line 51 of file api-flac-test.c.
Referenced by main().
init_decoder()
static int init_decoder (AVCodec * dec, AVCodecContext ** dec_ctx, int64_t ch_layout) static
Definition at line 81 of file api-flac-test.c.
Referenced by main().
run_test()
static int run_test (AVCodec * enc, AVCodec * dec, AVCodecContext * enc_ctx, AVCodecContext * dec_ctx) static
Definition at line 108 of file api-flac-test.c.
Referenced by main().
close_encoder()
static int close_encoder (AVCodecContext ** enc_ctx) static
Definition at line 226 of file api-flac-test.c.
Referenced by main().
close_decoder()
static int close_decoder (AVCodecContext ** dec_ctx) static
Definition at line 233 of file api-flac-test.c.
Referenced by main().
main()
int main (void)
Definition at line 240 of file api-flac-test.c.