FFmpeg: libavformat/apngenc.c File Reference
apngenc.c File Reference
#include "avformat.h"
#include "internal.h"
#include "libavutil/avassert.h"
#include "libavutil/crc.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/log.h"
#include "libavutil/opt.h"
#include "libavcodec/png.h"
#include "libavcodec/apng.h"
Data Structures
struct APNGMuxContext
Macros
#define OFFSET(x) offsetof(APNGMuxContext, x)
#define ENC AV_OPT_FLAG_ENCODING_PARAM
Functions
static uint8_t * apng_find_chunk (uint32_t tag, uint8_t *buf, size_t length)
static void apng_write_chunk (AVIOContext *io_context, uint32_t tag, uint8_t *buf, size_t length)
static int apng_write_header (AVFormatContext *format_context)
static int flush_packet (AVFormatContext *format_context, AVPacket *packet)
static int apng_write_packet (AVFormatContext *format_context, AVPacket *packet)
static int apng_write_trailer (AVFormatContext *format_context)
Variables
static const AVOption options []
static const AVClass apng_muxer_class
AVOutputFormat ff_apng_muxer
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(APNGMuxContext, x)
Definition at line 275 of file apngenc.c.
ENC
#define ENC AV_OPT_FLAG_ENCODING_PARAM
Definition at line 276 of file apngenc.c.
Function Documentation
apng_find_chunk()
static uint8_t* apng_find_chunk (uint32_t tag, uint8_t * buf, size_t length) static
Definition at line 52 of file apngenc.c.
Referenced by flush_packet().
apng_write_chunk()
static void apng_write_chunk (AVIOContext * io_context, uint32_t tag, uint8_t * buf, size_t length) static
Definition at line 61 of file apngenc.c.
Referenced by apng_write_trailer(), and flush_packet().
apng_write_header()
static int apng_write_header (AVFormatContext * format_context) static
Definition at line 81 of file apngenc.c.
flush_packet()
static int flush_packet (AVFormatContext * format_context, AVPacket * packet) static
Definition at line 116 of file apngenc.c.
Referenced by apng_write_packet(), and apng_write_trailer().
apng_write_packet()
static int apng_write_packet (AVFormatContext * format_context, AVPacket * packet) static
Definition at line 225 of file apngenc.c.
apng_write_trailer()
static int apng_write_trailer (AVFormatContext * format_context) static
Definition at line 245 of file apngenc.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "plays", "Number of times to play the output: 0 - infinite loop, 1 - no loop", OFFSET(plays),
      AV_OPT_TYPE_INT, { .i64 = 1 }, 0, UINT_MAX, ENC },
    { "final_delay", "Force delay after the last frame", OFFSET(last_delay),
      AV_OPT_TYPE_RATIONAL, { .dbl = 0 }, 0, USHRT_MAX, ENC },
    { NULL },
}
Definition at line 277 of file apngenc.c.
apng_muxer_class
const AVClass apng_muxer_class static
Initial value:
= {
    .class_name = "APNG muxer",
    .item_name  = av_default_item_name,
    .version    = LIBAVUTIL_VERSION_INT,
    .option     = options,
}
Definition at line 285 of file apngenc.c.
ff_apng_muxer
AVOutputFormat ff_apng_muxer
Initial value:
= {
    .name           = "apng",
    .long_name      = NULL_IF_CONFIG_SMALL("Animated Portable Network Graphics"),
    .mime_type      = "image/png",
    .extensions     = "apng",
    .priv_data_size = sizeof(APNGMuxContext),
    .audio_codec    = AV_CODEC_ID_NONE,
    .video_codec    = AV_CODEC_ID_APNG,
    .write_header   = apng_write_header,
    .write_packet   = apng_write_packet,
    .write_trailer  = apng_write_trailer,
    .priv_class     = &apng_muxer_class,
    .flags          = AVFMT_VARIABLE_FPS,
}
Definition at line 292 of file apngenc.c.