FFmpeg: libavcodec/arm/vp8dsp.h File Reference
vp8dsp.h File Reference
#include "libavcodec/vp8dsp.h"
Macros
#define VP8_LF_Y(hv, inner, opt)
#define VP8_LF_UV(hv, inner, opt)
#define VP8_LF_SIMPLE(hv, opt)
#define VP8_LF_HV(inner, opt)
#define VP8_LF(opt)
#define VP8_MC(n, opt)
#define VP8_EPEL(w, opt)
#define VP8_BILIN(w, opt)
Functions
void ff_vp78dsp_init_armv6 (VP8DSPContext *dsp)
void ff_vp78dsp_init_neon (VP8DSPContext *dsp)
void ff_vp8dsp_init_armv6 (VP8DSPContext *dsp)
void ff_vp8dsp_init_neon (VP8DSPContext *dsp)
Macro Definition Documentation
VP8_LF_Y
#define VP8_LF_Y (hv, inner, opt)
Value:
void ff_vp8_##hv##_loop_filter16##inner##_##opt(uint8_t *dst,            \
                                                    ptrdiff_t stride,        \
                                                    int flim_E, int flim_I,  \
                                                    int hev_thresh)
Definition at line 29 of file vp8dsp.h.
VP8_LF_UV
#define VP8_LF_UV (hv, inner, opt)
Value:
void ff_vp8_##hv##_loop_filter8uv##inner##_##opt(uint8_t *dstU,          \
                                                     uint8_t *dstV,          \
                                                     ptrdiff_t stride,       \
                                                     int flim_E, int flim_I, \
                                                     int hev_thresh)
Definition at line 35 of file vp8dsp.h.
VP8_LF_SIMPLE
#define VP8_LF_SIMPLE (hv, opt)
Value:
void ff_vp8_##hv##_loop_filter16_simple_##opt(uint8_t *dst,         \
                                                  ptrdiff_t stride,     \
                                                  int flim)
Definition at line 42 of file vp8dsp.h.
VP8_LF_HV
#define VP8_LF_HV (inner, opt)
Value:
VP8_LF_Y(h,  inner, opt);                   \
    VP8_LF_Y(v,  inner, opt);                   \
    VP8_LF_UV(h, inner, opt);                   \
    VP8_LF_UV(v, inner, opt)
Definition at line 47 of file vp8dsp.h.
VP8_LF
#define VP8_LF (opt)
Value:
VP8_LF_HV(,       opt);                     \
    VP8_LF_HV(_inner, opt);                     \
    VP8_LF_SIMPLE(h, opt);                      \
    VP8_LF_SIMPLE(v, opt)
Definition at line 53 of file vp8dsp.h.
VP8_MC
#define VP8_MC (n, opt)
Value:
void ff_put_vp8_##n##_##opt(uint8_t *dst, ptrdiff_t dststride,      \
                                uint8_t *src, ptrdiff_t srcstride,      \
                                int h, int x, int y)
Definition at line 59 of file vp8dsp.h.
VP8_EPEL
#define VP8_EPEL (w, opt)
Value:
VP8_MC(pixels ## w, opt);                   \
    VP8_MC(epel ## w ## _h4, opt);              \
    VP8_MC(epel ## w ## _h6, opt);              \
    VP8_MC(epel ## w ## _v4, opt);              \
    VP8_MC(epel ## w ## _h4v4, opt);            \
    VP8_MC(epel ## w ## _h6v4, opt);            \
    VP8_MC(epel ## w ## _v6, opt);              \
    VP8_MC(epel ## w ## _h4v6, opt);            \
    VP8_MC(epel ## w ## _h6v6, opt)
Definition at line 64 of file vp8dsp.h.
VP8_BILIN
#define VP8_BILIN (w, opt)
Value:
VP8_MC(bilin ## w ## _h, opt);              \
    VP8_MC(bilin ## w ## _v, opt);              \
    VP8_MC(bilin ## w ## _hv, opt)
Definition at line 75 of file vp8dsp.h.
Function Documentation
ff_vp78dsp_init_armv6()
void ff_vp78dsp_init_armv6 (VP8DSPContext * dsp)
Definition at line 43 of file vp8dsp_init_armv6.c.
Referenced by ff_vp78dsp_init_arm().
ff_vp78dsp_init_neon()
void ff_vp78dsp_init_neon (VP8DSPContext * dsp)
Definition at line 42 of file vp8dsp_init_neon.c.
Referenced by ff_vp78dsp_init_arm().
ff_vp8dsp_init_armv6()
void ff_vp8dsp_init_armv6 (VP8DSPContext * dsp)
Definition at line 101 of file vp8dsp_init_armv6.c.
Referenced by ff_vp8dsp_init_arm().
ff_vp8dsp_init_neon()
void ff_vp8dsp_init_neon (VP8DSPContext * dsp)
Definition at line 98 of file vp8dsp_init_neon.c.
Referenced by ff_vp8dsp_init_arm().