FFmpeg: libavformat/asfcrypt.h File Reference
asfcrypt.h File Reference
#include <inttypes.h>
Functions
void ff_asfcrypt_dec (const uint8_t key[20], uint8_t *data, int len)
Function Documentation
ff_asfcrypt_dec()
void ff_asfcrypt_dec (const uint8_t key[20], uint8_t * data, int len)
Definition at line 147 of file asfcrypt.c.
Referenced by asf_parse_packet(), asf_read_multiple_payload(), and asf_read_single_payload().