FFmpeg: libavformat/asfdec_f.c File Reference
asfdec_f.c File Reference
#include <inttypes.h>
#include "libavutil/attributes.h"
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/bswap.h"
#include "libavutil/common.h"
#include "libavutil/dict.h"
#include "libavutil/internal.h"
#include "libavutil/mathematics.h"
#include "libavutil/opt.h"
#include "avformat.h"
#include "avio_internal.h"
#include "avlanguage.h"
#include "id3v2.h"
#include "internal.h"
#include "riff.h"
#include "asf.h"
#include "asfcrypt.h"
#include <assert.h>
Data Structures
struct ASFPayload
struct ASFStream
struct ASFContext
Macros
#define ASF_MAX_STREAMS 127
#define FRAME_HEADER_SIZE 6
#define print_guid(g) while(0)
#define LEN 22
#define DO_2BITS(bits, var, defval)
Functions
static int asf_probe (AVProbeData *pd)
static int get_value (AVIOContext *pb, int type, int type2_size)
static int asf_read_picture (AVFormatContext *s, int len)
static void get_id3_tag (AVFormatContext *s, int len)
static void get_tag (AVFormatContext *s, const char *key, int type, int len, int type2_size)
static int asf_read_file_properties (AVFormatContext *s, int64_t size)
static int asf_read_stream_properties (AVFormatContext *s, int64_t size)
static int asf_read_ext_stream_properties (AVFormatContext *s, int64_t size)
static int asf_read_content_desc (AVFormatContext *s, int64_t size)
static int asf_read_ext_content_desc (AVFormatContext *s, int64_t size)
static int asf_read_language_list (AVFormatContext *s, int64_t size)
static int asf_read_metadata (AVFormatContext *s, int64_t size)
static int asf_read_marker (AVFormatContext *s, int64_t size)
static int asf_read_header (AVFormatContext *s)
static int asf_get_packet (AVFormatContext *s, AVIOContext *pb)
Load a single ASF packet into the demuxer.
static int asf_read_frame_header (AVFormatContext *s, AVIOContext *pb)
static int asf_parse_packet (AVFormatContext *s, AVIOContext *pb, AVPacket *pkt)
Parse data from individual ASF packets (which were previously loaded with asf_get_packet()).
static int asf_read_packet (AVFormatContext *s, AVPacket *pkt)
static void asf_reset_header (AVFormatContext *s)
static void skip_to_key (AVFormatContext *s)
static int asf_read_close (AVFormatContext *s)
static int64_t asf_read_pts (AVFormatContext *s, int stream_index, int64_t *ppos, int64_t pos_limit)
static int asf_build_simple_index (AVFormatContext *s, int stream_index)
static int asf_read_seek (AVFormatContext *s, int stream_index, int64_t pts, int flags)
Variables
static const AVOption options []
static const AVClass asf_class
AVInputFormat ff_asf_demuxer
Macro Definition Documentation
ASF_MAX_STREAMS
#define ASF_MAX_STREAMS 127
Definition at line 136 of file asfdec_f.c.
Referenced by asf_read_pts(), and asf_read_stream_properties().
FRAME_HEADER_SIZE
#define FRAME_HEADER_SIZE 6
Definition at line 137 of file asfdec_f.c.
Referenced by asf_parse_packet(), and asf_read_packet().
print_guid
#define print_guid (g) while(0)
Definition at line 186 of file asfdec_f.c.
Referenced by asf_read_header().
LEN
#define LEN 22
Referenced by build_filter(), and get_tag().
DO_2BITS
#define DO_2BITS (bits, var, defval)
Value:
switch (bits & 3) {                         \
    case 3:                                     \
        var = avio_rl32(pb);                    \
        rsize += 4;                             \
        break;                                  \
    case 2:                                     \
        var = avio_rl16(pb);                    \
        rsize += 2;                             \
        break;                                  \
    case 1:                                     \
        var = avio_r8(pb);                      \
        rsize++;                                \
        break;                                  \
    default:                                    \
        var = defval;                           \
        break;                                  \
    }
Definition at line 929 of file asfdec_f.c.
Referenced by asf_get_packet(), and asf_read_frame_header().
Function Documentation
asf_probe()
static int asf_probe (AVProbeData * pd) static
Definition at line 189 of file asfdec_f.c.
get_value()
static int get_value (AVIOContext * pb, int type, int type2_size) static
Definition at line 200 of file asfdec_f.c.
Referenced by asf_read_ext_content_desc(), asf_read_metadata(), and get_tag().
asf_read_picture()
static int asf_read_picture (AVFormatContext * s, int len) static
Definition at line 218 of file asfdec_f.c.
Referenced by get_tag().
get_id3_tag()
static void get_id3_tag (AVFormatContext * s, int len) static
Definition at line 305 of file asfdec_f.c.
Referenced by get_tag().
get_tag()
static void get_tag (AVFormatContext * s, const char * key, int type, int len, int type2_size) static
Definition at line 315 of file asfdec_f.c.
Referenced by asf_read_content_desc(), asf_read_ext_content_desc(), asf_read_header(), and asf_read_metadata().
asf_read_file_properties()
static int asf_read_file_properties (AVFormatContext * s, int64_t size) static
Definition at line 373 of file asfdec_f.c.
Referenced by asf_read_header().
asf_read_stream_properties()
static int asf_read_stream_properties (AVFormatContext * s, int64_t size) static
Definition at line 397 of file asfdec_f.c.
Referenced by asf_read_header().
asf_read_ext_stream_properties()
static int asf_read_ext_stream_properties (AVFormatContext * s, int64_t size) static
Definition at line 564 of file asfdec_f.c.
Referenced by asf_read_header().
asf_read_content_desc()
static int asf_read_content_desc (AVFormatContext * s, int64_t size) static
Definition at line 622 of file asfdec_f.c.
Referenced by asf_read_header().
asf_read_ext_content_desc()
static int asf_read_ext_content_desc (AVFormatContext * s, int64_t size) static
Definition at line 641 of file asfdec_f.c.
Referenced by asf_read_header().
asf_read_language_list()
static int asf_read_language_list (AVFormatContext * s, int64_t size) static
Definition at line 675 of file asfdec_f.c.
Referenced by asf_read_header().
asf_read_metadata()
static int asf_read_metadata (AVFormatContext * s, int64_t size) static
Definition at line 695 of file asfdec_f.c.
Referenced by asf_read_header().
asf_read_marker()
static int asf_read_marker (AVFormatContext * s, int64_t size) static
Definition at line 740 of file asfdec_f.c.
Referenced by asf_read_header().
asf_read_header()
static int asf_read_header (AVFormatContext * s) static
Definition at line 776 of file asfdec_f.c.
asf_get_packet()
static int asf_get_packet (AVFormatContext * s, AVIOContext * pb) static
Load a single ASF packet into the demuxer.
Parameters
s demux context
pb context to read data from
Returns
0 on success, <0 on error
Definition at line 954 of file asfdec_f.c.
Referenced by asf_read_packet().
asf_read_frame_header()
static int asf_read_frame_header (AVFormatContext * s, AVIOContext * pb) static
Returns
<0 if error
Definition at line 1076 of file asfdec_f.c.
Referenced by asf_parse_packet().
asf_parse_packet()
static int asf_parse_packet (AVFormatContext * s, AVIOContext * pb, AVPacket * pkt) static
Parse data from individual ASF packets (which were previously loaded with asf_get_packet()).
Parameters
s demux context
pb context to read data from
pkt pointer to store packet data into
Returns
0 if data was stored in pkt, <0 on error or 1 if more ASF packets need to be loaded (through asf_get_packet())
Definition at line 1205 of file asfdec_f.c.
Referenced by asf_read_packet().
asf_read_packet()
static int asf_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 1434 of file asfdec_f.c.
asf_reset_header()
static void asf_reset_header (AVFormatContext * s) static
Definition at line 1454 of file asfdec_f.c.
Referenced by asf_read_close(), asf_read_pts(), and asf_read_seek().
skip_to_key()
static void skip_to_key (AVFormatContext * s) static
Definition at line 1487 of file asfdec_f.c.
Referenced by asf_read_seek().
asf_read_close()
static int asf_read_close (AVFormatContext * s) static
Definition at line 1502 of file asfdec_f.c.
asf_read_pts()
static int64_t asf_read_pts (AVFormatContext * s, int stream_index, int64_t * ppos, int64_t pos_limit) static
Definition at line 1509 of file asfdec_f.c.
asf_build_simple_index()
static int asf_build_simple_index (AVFormatContext * s, int stream_index) static
Definition at line 1566 of file asfdec_f.c.
Referenced by asf_read_seek().
asf_read_seek()
static int asf_read_seek (AVFormatContext * s, int stream_index, int64_t pts, int flags) static
Definition at line 1629 of file asfdec_f.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "no_resync_search", "Don't try to resynchronize by looking for a certain optional start code", 0x42, AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, AV_OPT_FLAG_DECODING_PARAM },
    { "export_xmp", "Export full XMP metadata", 0x42, AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, AV_OPT_FLAG_DECODING_PARAM },
    { NULL },
}
Definition at line 120 of file asfdec_f.c.
asf_class
const AVClass asf_class static
Initial value:
= {
    .class_name = "asf demuxer",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 126 of file asfdec_f.c.
ff_asf_demuxer
AVInputFormat ff_asf_demuxer
Initial value:
= {
    .name           = "asf",
    .long_name      = NULL_IF_CONFIG_SMALL("ASF (Advanced / Active Streaming Format)"),
    .priv_data_size = sizeof(ASFContext),
    .read_probe     = asf_probe,
    .read_header    = asf_read_header,
    .read_packet    = asf_read_packet,
    .read_close     = asf_read_close,
    .read_seek      = asf_read_seek,
    .read_timestamp = asf_read_pts,
    .flags          = AVFMT_NOBINSEARCH | AVFMT_NOGENSEARCH,
    .priv_class     = &asf_class,
}
Definition at line 1684 of file asfdec_f.c.