FFmpeg: libavformat/asfenc.c File Reference
asfenc.c File Reference
#include "libavutil/avassert.h"
#include "libavutil/dict.h"
#include "libavutil/mathematics.h"
#include "libavutil/parseutils.h"
#include "libavutil/opt.h"
#include "avformat.h"
#include "avlanguage.h"
#include "avio_internal.h"
#include "internal.h"
#include "riff.h"
#include "asf.h"
Data Structures
struct ASFPayload
struct ASFStream
struct ASFContext
Macros
#define ASF_INDEXED_INTERVAL 10000000
#define ASF_INDEX_BLOCK (1<<9)
#define ASF_PAYLOADS_PER_PACKET 63
#define ASF_PACKET_ERROR_CORRECTION_DATA_SIZE 0x2
#define ASF_PACKET_ERROR_CORRECTION_FLAGS
#define ASF_PACKET_ERROR_CORRECTION_FLAGS_FIELD_SIZE 1
#define ASF_PPI_PROPERTY_FLAGS
#define ASF_PPI_LENGTH_TYPE_FLAGS 0
#define ASF_PAYLOAD_FLAGS ASF_PL_FLAG_PAYLOAD_LENGTH_FIELD_IS_WORD
#define ASF_PPI_SEQUENCE_FIELD_SIZE 0
#define ASF_PPI_PACKET_LENGTH_FIELD_SIZE 0
#define ASF_PPI_PADDING_LENGTH_FIELD_SIZE 0
#define ASF_PAYLOAD_REPLICATED_DATA_LENGTH_FIELD_SIZE 1
#define ASF_PAYLOAD_OFFSET_INTO_MEDIA_OBJECT_FIELD_SIZE 4
#define ASF_PAYLOAD_MEDIA_OBJECT_NUMBER_FIELD_SIZE 1
#define ASF_PAYLOAD_LENGTH_FIELD_SIZE 2
#define PACKET_HEADER_MIN_SIZE
#define ASF_PAYLOAD_REPLICATED_DATA_LENGTH 0x08
#define PAYLOAD_HEADER_SIZE_SINGLE_PAYLOAD
#define PAYLOAD_HEADER_SIZE_MULTIPLE_PAYLOADS
#define SINGLE_PAYLOAD_HEADERS
#define MULTI_PAYLOAD_HEADERS
#define DATA_HEADER_SIZE 50
#define PACKET_SIZE_MAX 65536
#define PACKET_SIZE_MIN 100
#define PREROLL_TIME 3100
Functions
static void put_str16 (AVIOContext *s, const char *tag)
static int64_t put_header (AVIOContext *pb, const ff_asf_guid *g)
static void end_header (AVIOContext *pb, int64_t pos)
static void put_chunk (AVFormatContext *s, int type, int payload_length, int flags)
static int64_t unix_to_file_time (int64_t ti)
static int32_t get_send_time (ASFContext *asf, int64_t pres_time, uint64_t *offset)
static int asf_write_markers (AVFormatContext *s)
static int asf_write_header1 (AVFormatContext *s, int64_t file_size, int64_t data_chunk_size)
static int asf_write_header (AVFormatContext *s)
static int asf_write_stream_header (AVFormatContext *s)
static int put_payload_parsing_info (AVFormatContext *s, unsigned sendtime, unsigned duration, int nb_payloads, int padsize)
static void flush_packet (AVFormatContext *s)
static void put_payload_header (AVFormatContext *s, ASFStream *stream, int64_t presentation_time, int m_obj_size, int m_obj_offset, int payload_len, int flags)
static void put_frame (AVFormatContext *s, ASFStream *stream, AVStream *avst, int64_t timestamp, const uint8_t *buf, int m_obj_size, int flags)
static int update_index (AVFormatContext *s, int start_sec, uint32_t packet_number, uint16_t packet_count, uint64_t packet_offset)
static int asf_write_packet (AVFormatContext *s, AVPacket *pkt)
static int asf_write_index (AVFormatContext *s, const ASFIndex *index, uint16_t max, uint32_t count)
static int asf_write_trailer (AVFormatContext *s)
Variables
static const AVCodecTag codec_asf_bmp_tags []
static const AVOption asf_options []
Macro Definition Documentation
ASF_INDEXED_INTERVAL
#define ASF_INDEXED_INTERVAL 10000000
Definition at line 34 of file asfenc.c.
Referenced by asf_write_index(), and asf_write_packet().
ASF_INDEX_BLOCK
#define ASF_INDEX_BLOCK (1<<9)
Definition at line 35 of file asfenc.c.
Referenced by asf_write_header(), and update_index().
ASF_PAYLOADS_PER_PACKET
#define ASF_PAYLOADS_PER_PACKET 63
Definition at line 36 of file asfenc.c.
Referenced by put_frame().
ASF_PACKET_ERROR_CORRECTION_DATA_SIZE
#define ASF_PACKET_ERROR_CORRECTION_DATA_SIZE 0x2
Definition at line 38 of file asfenc.c.
Referenced by put_payload_parsing_info().
ASF_PACKET_ERROR_CORRECTION_FLAGS
#define ASF_PACKET_ERROR_CORRECTION_FLAGS
Value:
(ASF_PACKET_FLAG_ERROR_CORRECTION_PRESENT |    \
     ASF_PACKET_ERROR_CORRECTION_DATA_SIZE)
Definition at line 39 of file asfenc.c.
Referenced by put_payload_parsing_info().
ASF_PACKET_ERROR_CORRECTION_FLAGS_FIELD_SIZE
#define ASF_PACKET_ERROR_CORRECTION_FLAGS_FIELD_SIZE 1
Definition at line 44 of file asfenc.c.
ASF_PPI_PROPERTY_FLAGS
#define ASF_PPI_PROPERTY_FLAGS
Value:
(ASF_PL_FLAG_REPLICATED_DATA_LENGTH_FIELD_IS_BYTE           |    \
     ASF_PL_FLAG_OFFSET_INTO_MEDIA_OBJECT_LENGTH_FIELD_IS_DWORD |    \
     ASF_PL_FLAG_MEDIA_OBJECT_NUMBER_LENGTH_FIELD_IS_BYTE       |    \
     ASF_PL_FLAG_STREAM_NUMBER_LENGTH_FIELD_IS_BYTE)
Definition at line 49 of file asfenc.c.
Referenced by put_payload_parsing_info().
ASF_PPI_LENGTH_TYPE_FLAGS
#define ASF_PPI_LENGTH_TYPE_FLAGS 0
Definition at line 55 of file asfenc.c.
Referenced by put_payload_parsing_info().
ASF_PAYLOAD_FLAGS
#define ASF_PAYLOAD_FLAGS ASF_PL_FLAG_PAYLOAD_LENGTH_FIELD_IS_WORD
Definition at line 57 of file asfenc.c.
Referenced by put_payload_parsing_info().
ASF_PPI_SEQUENCE_FIELD_SIZE
#define ASF_PPI_SEQUENCE_FIELD_SIZE 0
Definition at line 69 of file asfenc.c.
ASF_PPI_PACKET_LENGTH_FIELD_SIZE
#define ASF_PPI_PACKET_LENGTH_FIELD_SIZE 0
Definition at line 82 of file asfenc.c.
ASF_PPI_PADDING_LENGTH_FIELD_SIZE
#define ASF_PPI_PADDING_LENGTH_FIELD_SIZE 0
Definition at line 95 of file asfenc.c.
ASF_PAYLOAD_REPLICATED_DATA_LENGTH_FIELD_SIZE
#define ASF_PAYLOAD_REPLICATED_DATA_LENGTH_FIELD_SIZE 1
Definition at line 99 of file asfenc.c.
ASF_PAYLOAD_OFFSET_INTO_MEDIA_OBJECT_FIELD_SIZE
#define ASF_PAYLOAD_OFFSET_INTO_MEDIA_OBJECT_FIELD_SIZE 4
Definition at line 118 of file asfenc.c.
ASF_PAYLOAD_MEDIA_OBJECT_NUMBER_FIELD_SIZE
#define ASF_PAYLOAD_MEDIA_OBJECT_NUMBER_FIELD_SIZE 1
Definition at line 125 of file asfenc.c.
ASF_PAYLOAD_LENGTH_FIELD_SIZE
#define ASF_PAYLOAD_LENGTH_FIELD_SIZE 2
Definition at line 141 of file asfenc.c.
PACKET_HEADER_MIN_SIZE
#define PACKET_HEADER_MIN_SIZE
Value:
(ASF_PACKET_ERROR_CORRECTION_FLAGS_FIELD_SIZE +       \
     ASF_PACKET_ERROR_CORRECTION_DATA_SIZE +              \
     1 +        /* Length Type Flags */                   \
     1 +        /* Property Flags */                      \
     ASF_PPI_PACKET_LENGTH_FIELD_SIZE +                   \
     ASF_PPI_SEQUENCE_FIELD_SIZE +                        \
     ASF_PPI_PADDING_LENGTH_FIELD_SIZE +                  \
     4 +        /* Send Time Field */                     \
     2)         /* Duration Field */
Definition at line 147 of file asfenc.c.
Referenced by put_frame(), and put_payload_parsing_info().
ASF_PAYLOAD_REPLICATED_DATA_LENGTH
#define ASF_PAYLOAD_REPLICATED_DATA_LENGTH 0x08
Definition at line 159 of file asfenc.c.
Referenced by put_payload_header().
PAYLOAD_HEADER_SIZE_SINGLE_PAYLOAD
#define PAYLOAD_HEADER_SIZE_SINGLE_PAYLOAD
Value:
(1 +     /* Stream Number */                          \
     ASF_PAYLOAD_MEDIA_OBJECT_NUMBER_FIELD_SIZE +         \
     ASF_PAYLOAD_OFFSET_INTO_MEDIA_OBJECT_FIELD_SIZE +    \
     ASF_PAYLOAD_REPLICATED_DATA_LENGTH_FIELD_SIZE +      \
     ASF_PAYLOAD_REPLICATED_DATA_LENGTH)
Definition at line 161 of file asfenc.c.
Referenced by put_frame().
PAYLOAD_HEADER_SIZE_MULTIPLE_PAYLOADS
#define PAYLOAD_HEADER_SIZE_MULTIPLE_PAYLOADS
Value:
(1 +        /* Stream Number */                       \
     ASF_PAYLOAD_MEDIA_OBJECT_NUMBER_FIELD_SIZE +         \
     ASF_PAYLOAD_OFFSET_INTO_MEDIA_OBJECT_FIELD_SIZE +    \
     ASF_PAYLOAD_REPLICATED_DATA_LENGTH_FIELD_SIZE +      \
     ASF_PAYLOAD_REPLICATED_DATA_LENGTH +                 \
     ASF_PAYLOAD_LENGTH_FIELD_SIZE)
Definition at line 168 of file asfenc.c.
Referenced by put_frame().
SINGLE_PAYLOAD_HEADERS
#define SINGLE_PAYLOAD_HEADERS
Value:
(PACKET_HEADER_MIN_SIZE +                             \
     PAYLOAD_HEADER_SIZE_SINGLE_PAYLOAD)
Definition at line 176 of file asfenc.c.
Referenced by put_frame().
MULTI_PAYLOAD_HEADERS
#define MULTI_PAYLOAD_HEADERS
Value:
(PACKET_HEADER_MIN_SIZE +                             \
     1 +         /* Payload Flags */                      \
     2 * PAYLOAD_HEADER_SIZE_MULTIPLE_PAYLOADS)
Definition at line 180 of file asfenc.c.
Referenced by put_frame().
DATA_HEADER_SIZE
#define DATA_HEADER_SIZE 50
Definition at line 185 of file asfenc.c.
Referenced by asf_write_header(), asf_write_header1(), and get_send_time().
PACKET_SIZE_MAX
#define PACKET_SIZE_MAX 65536
Definition at line 187 of file asfenc.c.
PACKET_SIZE_MIN
#define PACKET_SIZE_MIN 100
Definition at line 188 of file asfenc.c.
PREROLL_TIME
#define PREROLL_TIME 3100
Definition at line 262 of file asfenc.c.
Referenced by asf_write_header1(), asf_write_markers(), asf_write_packet(), and put_frame().
Function Documentation
put_str16()
static void put_str16 (AVIOContext * s, const char * tag) static
Definition at line 264 of file asfenc.c.
Referenced by asf_write_header1().
put_header()
static int64_t put_header (AVIOContext * pb, const ff_asf_guid * g) static
Definition at line 279 of file asfenc.c.
Referenced by asf_write_header1(), and asf_write_markers().
end_header()
static void end_header (AVIOContext * pb, int64_t pos) static
Definition at line 290 of file asfenc.c.
Referenced by asf_write_header1(), and asf_write_markers().
put_chunk()
static void put_chunk (AVFormatContext * s, int type, int payload_length, int flags) static
Definition at line 301 of file asfenc.c.
Referenced by asf_write_header1(), asf_write_trailer(), and flush_packet().
unix_to_file_time()
static int64_t unix_to_file_time (int64_t ti) static
Definition at line 318 of file asfenc.c.
Referenced by asf_write_header1().
get_send_time()
static int32_t get_send_time (ASFContext * asf, int64_t pres_time, uint64_t * offset) static
Definition at line 327 of file asfenc.c.
Referenced by asf_write_markers().
asf_write_markers()
static int asf_write_markers (AVFormatContext * s) static
Definition at line 342 of file asfenc.c.
Referenced by asf_write_header1().
asf_write_header1()
static int asf_write_header1 (AVFormatContext * s, int64_t file_size, int64_t data_chunk_size) static
Definition at line 386 of file asfenc.c.
Referenced by asf_write_header(), and asf_write_trailer().
asf_write_header()
static int asf_write_header (AVFormatContext * s) static
Definition at line 777 of file asfenc.c.
Referenced by asf_write_stream_header().
asf_write_stream_header()
static int asf_write_stream_header (AVFormatContext * s) static
Definition at line 819 of file asfenc.c.
put_payload_parsing_info()
static int put_payload_parsing_info (AVFormatContext * s, unsigned sendtime, unsigned duration, int nb_payloads, int padsize) static
Definition at line 828 of file asfenc.c.
Referenced by flush_packet().
flush_packet()
static void flush_packet (AVFormatContext * s) static
Definition at line 876 of file asfenc.c.
Referenced by asf_write_trailer(), and put_frame().
put_payload_header()
static void put_payload_header (AVFormatContext * s, ASFStream * stream, int64_t presentation_time, int m_obj_size, int m_obj_offset, int payload_len, int flags) static
Definition at line 907 of file asfenc.c.
Referenced by put_frame().
put_frame()
static void put_frame (AVFormatContext * s, ASFStream * stream, AVStream * avst, int64_t timestamp, const uint8_t * buf, int m_obj_size, int flags) static
Definition at line 938 of file asfenc.c.
Referenced by asf_write_packet().
update_index()
static int update_index (AVFormatContext * s, int start_sec, uint32_t packet_number, uint16_t packet_count, uint64_t packet_offset) static
Definition at line 1009 of file asfenc.c.
Referenced by asf_write_packet(), and asf_write_trailer().
asf_write_packet()
static int asf_write_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 1051 of file asfenc.c.
asf_write_index()
static int asf_write_index (AVFormatContext * s, const ASFIndex * index, uint16_t max, uint32_t count) static
Definition at line 1099 of file asfenc.c.
Referenced by asf_write_trailer().
asf_write_trailer()
static int asf_write_trailer (AVFormatContext * s) static
Definition at line 1119 of file asfenc.c.
Variable Documentation
codec_asf_bmp_tags
const AVCodecTag codec_asf_bmp_tags[] static
Initial value:
= {
    { AV_CODEC_ID_MPEG4,     MKTAG('M', '4', 'S', '2') },
    { AV_CODEC_ID_MPEG4,     MKTAG('M', 'P', '4', 'S') },
    { AV_CODEC_ID_MSMPEG4V3, MKTAG('M', 'P', '4', '3') },
    { AV_CODEC_ID_NONE,      0 },
}
Definition at line 255 of file asfenc.c.
asf_options
const AVOption asf_options[] static
Initial value:
= {
    { "packet_size", "Packet size", 0x42, AV_OPT_TYPE_INT, {.i64 = 3200}, PACKET_SIZE_MIN, PACKET_SIZE_MAX, AV_OPT_FLAG_ENCODING_PARAM },
    { NULL },
}
Definition at line 1151 of file asfenc.c.