FFmpeg: libavfilter/asrc_flite.c File Reference
asrc_flite.c File Reference
flite voice synth source
#include <flite/flite.h>
#include "libavutil/channel_layout.h"
#include "libavutil/file.h"
#include "libavutil/opt.h"
#include "avfilter.h"
#include "audio.h"
#include "formats.h"
#include "internal.h"
Data Structures
struct FliteContext
struct voice_entry
Macros
#define OFFSET(x) offsetof(FliteContext, x)
#define FLAGS AV_OPT_FLAG_AUDIO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
#define DECLARE_REGISTER_VOICE_FN(name)
#define MAKE_VOICE_STRUCTURE(voice_name)
Functions
AVFILTER_DEFINE_CLASS (flite)
DECLARE_REGISTER_VOICE_FN (awb)
DECLARE_REGISTER_VOICE_FN (kal)
DECLARE_REGISTER_VOICE_FN (kal16)
DECLARE_REGISTER_VOICE_FN (rms)
DECLARE_REGISTER_VOICE_FN (slt)
static void list_voices (void *log_ctx, const char *sep)
static int select_voice (struct voice_entry **entry_ret, const char *voice_name, void *log_ctx)
static av_cold int init (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static int config_props (AVFilterLink *outlink)
static int request_frame (AVFilterLink *outlink)
Variables
static const AVOption flite_options []
static volatile int flite_inited = 0
struct voice_entry voice_entry
static struct voice_entry voice_entries []
static const AVFilterPad flite_outputs []
AVFilter ff_asrc_flite
Detailed Description
flite voice synth source
Definition in file asrc_flite.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(FliteContext, x)
Definition at line 50 of file asrc_flite.c.
FLAGS
#define FLAGS AV_OPT_FLAG_AUDIO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 51 of file asrc_flite.c.
DECLARE_REGISTER_VOICE_FN
#define DECLARE_REGISTER_VOICE_FN (name)
Value:
cst_voice *register_cmu_us_## name(const char *); \
    void     unregister_cmu_us_## name(cst_voice *);
Definition at line 69 of file asrc_flite.c.
MAKE_VOICE_STRUCTURE
#define MAKE_VOICE_STRUCTURE (voice_name)
Value:
{             \
    .name          =                      #voice_name, \
    .register_fn   =   register_cmu_us_ ## voice_name, \
    .unregister_fn = unregister_cmu_us_ ## voice_name, \
}
Definition at line 86 of file asrc_flite.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (flite)
DECLARE_REGISTER_VOICE_FN() [1/5]
DECLARE_REGISTER_VOICE_FN (awb)
DECLARE_REGISTER_VOICE_FN() [2/5]
DECLARE_REGISTER_VOICE_FN (kal)
DECLARE_REGISTER_VOICE_FN() [3/5]
DECLARE_REGISTER_VOICE_FN (kal16)
DECLARE_REGISTER_VOICE_FN() [4/5]
DECLARE_REGISTER_VOICE_FN (rms)
DECLARE_REGISTER_VOICE_FN() [5/5]
DECLARE_REGISTER_VOICE_FN (slt)
list_voices()
static void list_voices (void * log_ctx, const char * sep) static
Definition at line 99 of file asrc_flite.c.
Referenced by init(), and select_voice().
select_voice()
static int select_voice (struct voice_entry ** entry_ret, const char * voice_name, void * log_ctx) static
Definition at line 107 of file asrc_flite.c.
Referenced by init().
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 134 of file asrc_flite.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 193 of file asrc_flite.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 205 of file asrc_flite.c.
config_props()
static int config_props (AVFilterLink * outlink) static
Definition at line 226 of file asrc_flite.c.
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 240 of file asrc_flite.c.
Variable Documentation
flite_options
const AVOption flite_options[] static
Initial value:
= {
    { "list_voices", "list voices and exit",              OFFSET(list_voices), AV_OPT_TYPE_BOOL, {.i64=0}, 0, 1, FLAGS },
    { "nb_samples",  "set number of samples per frame",   OFFSET(frame_nb_samples), AV_OPT_TYPE_INT, {.i64=512}, 0, INT_MAX, FLAGS },
    { "n",           "set number of samples per frame",   OFFSET(frame_nb_samples), AV_OPT_TYPE_INT, {.i64=512}, 0, INT_MAX, FLAGS },
    { "text",        "set text to speak",                 OFFSET(text),      AV_OPT_TYPE_STRING, {.str=NULL}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "textfile",    "set filename of the text to speak", OFFSET(textfile),  AV_OPT_TYPE_STRING, {.str=NULL}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "v",           "set voice",                         OFFSET(voice_str), AV_OPT_TYPE_STRING, {.str="kal"}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "voice",       "set voice",                         OFFSET(voice_str), AV_OPT_TYPE_STRING, {.str="kal"}, CHAR_MIN, CHAR_MAX, FLAGS },
    { NULL }
}
Definition at line 53 of file asrc_flite.c.
flite_inited
volatile int flite_inited = 0 static
Definition at line 66 of file asrc_flite.c.
Referenced by init().
voice_entry
struct voice_entry voice_entry
voice_entries
struct voice_entry voice_entries[] static
Initial value:
= {
    MAKE_VOICE_STRUCTURE(awb),
    MAKE_VOICE_STRUCTURE(kal),
    MAKE_VOICE_STRUCTURE(kal16),
    MAKE_VOICE_STRUCTURE(rms),
    MAKE_VOICE_STRUCTURE(slt),
}
Definition at line 91 of file asrc_flite.c.
flite_outputs
const AVFilterPad flite_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_AUDIO,
        .config_props  = config_props,
        .request_frame = request_frame,
    },
    { NULL }
}
Definition at line 265 of file asrc_flite.c.
ff_asrc_flite
AVFilter ff_asrc_flite
Initial value:
= {
    .name          = "flite",
    .description   = NULL_IF_CONFIG_SMALL("Synthesize voice from text using libflite."),
    .query_formats = query_formats,
    .init          = init,
    .uninit        = uninit,
    .priv_size     = sizeof(FliteContext),
    .inputs        = NULL,
    .outputs       = flite_outputs,
    .priv_class    = &flite_class,
}
Definition at line 275 of file asrc_flite.c.