FFmpeg: libavcodec/ass.h File Reference
ass.h File Reference
#include "avcodec.h"
#include "libavutil/bprint.h"
Data Structures
struct FFASSDecoderContext
Macros
#define ASS_DEFAULT_PLAYRESX 384
#define ASS_DEFAULT_PLAYRESY 288
Default values for ASS style
#define ASS_DEFAULT_FONT "Arial"
#define ASS_DEFAULT_FONT_SIZE 16
#define ASS_DEFAULT_COLOR 0xffffff
#define ASS_DEFAULT_BACK_COLOR 0
#define ASS_DEFAULT_BOLD 0
#define ASS_DEFAULT_ITALIC 0
#define ASS_DEFAULT_UNDERLINE 0
#define ASS_DEFAULT_ALIGNMENT 2
#define ASS_DEFAULT_BORDERSTYLE 1
Functions
int ff_ass_subtitle_header (AVCodecContext *avctx, const char *font, int font_size, int color, int back_color, int bold, int italic, int underline, int border_style, int alignment)
Generate a suitable AVCodecContext.subtitle_header for SUBTITLE_ASS.
int ff_ass_subtitle_header_default (AVCodecContext *avctx)
Generate a suitable AVCodecContext.subtitle_header for SUBTITLE_ASS with default style.
char * ff_ass_get_dialog (int readorder, int layer, const char *style, const char *speaker, const char *text)
Craft an ASS dialog string.
int ff_ass_add_rect (AVSubtitle *sub, const char *dialog, int readorder, int layer, const char *style, const char *speaker)
Add an ASS dialog to a subtitle.
void ff_ass_decoder_flush (AVCodecContext *avctx)
Helper to flush a text subtitles decoder making use of the FFASSDecoderContext.
void ff_ass_bprint_text_event (AVBPrint *buf, const char *p, int size, const char *linebreaks, int keep_ass_markup)
Escape a text subtitle using ASS syntax into an AVBPrint buffer.
Macro Definition Documentation
ASS_DEFAULT_PLAYRESX
#define ASS_DEFAULT_PLAYRESX 384
Definition at line 28 of file ass.h.
Referenced by capture_screen(), ff_ass_subtitle_header(), and srt_to_ass().
ASS_DEFAULT_PLAYRESY
#define ASS_DEFAULT_PLAYRESY 288
Definition at line 29 of file ass.h.
Referenced by capture_screen(), ff_ass_subtitle_header(), and srt_to_ass().
ASS_DEFAULT_FONT
#define ASS_DEFAULT_FONT "Arial"
Definition at line 35 of file ass.h.
Referenced by ff_ass_subtitle_header_default(), microdvd_init(), and srt_style_apply().
ASS_DEFAULT_FONT_SIZE
#define ASS_DEFAULT_FONT_SIZE 16
Definition at line 36 of file ass.h.
Referenced by ff_ass_subtitle_header_default(), init_decoder(), microdvd_init(), and srt_style_apply().
ASS_DEFAULT_COLOR
#define ASS_DEFAULT_COLOR 0xffffff
Definition at line 37 of file ass.h.
Referenced by ff_ass_subtitle_header_default(), init_decoder(), microdvd_init(), and srt_style_apply().
ASS_DEFAULT_BACK_COLOR
#define ASS_DEFAULT_BACK_COLOR 0
Definition at line 38 of file ass.h.
Referenced by ff_ass_subtitle_header_default(), init_decoder(), and microdvd_init().
ASS_DEFAULT_BOLD
#define ASS_DEFAULT_BOLD 0
Definition at line 39 of file ass.h.
Referenced by ff_ass_subtitle_header_default(), init_decoder(), microdvd_init(), srt_style_apply(), and webvtt_style_apply().
ASS_DEFAULT_ITALIC
#define ASS_DEFAULT_ITALIC 0
Definition at line 40 of file ass.h.
Referenced by ff_ass_subtitle_header_default(), init_decoder(), microdvd_init(), srt_style_apply(), and webvtt_style_apply().
ASS_DEFAULT_UNDERLINE
#define ASS_DEFAULT_UNDERLINE 0
Definition at line 41 of file ass.h.
Referenced by ff_ass_subtitle_header_default(), init_decoder(), microdvd_init(), srt_style_apply(), and webvtt_style_apply().
ASS_DEFAULT_ALIGNMENT
#define ASS_DEFAULT_ALIGNMENT 2
Definition at line 42 of file ass.h.
Referenced by ff_ass_subtitle_header_default(), init_decoder(), microdvd_init(), and srt_style_apply().
ASS_DEFAULT_BORDERSTYLE
#define ASS_DEFAULT_BORDERSTYLE 1
Definition at line 43 of file ass.h.
Referenced by ff_ass_subtitle_header_default(), microdvd_init(), and mov_text_init().
Function Documentation
ff_ass_subtitle_header()
int ff_ass_subtitle_header (AVCodecContext * avctx, const char * font, int font_size, int color, int back_color, int bold, int italic, int underline, int border_style, int alignment)
Generate a suitable AVCodecContext.subtitle_header for SUBTITLE_ASS.
Parameters
avctx pointer to the AVCodecContext
font name of the default font face to use
font_size default font size to use
color default text color to use (ABGR)
back_color default background color to use (ABGR)
bold 1 for bold text, 0 for normal text
italic 1 for italic text, 0 for normal text
underline 1 for underline text, 0 for normal text
alignment position of the text (left, center, top...), defined after the layout of the numpad (1-3 sub, 4-6 mid, 7-9 top)
Returns
>= 0 on success otherwise an error code <0
Definition at line 29 of file ass.c.
Referenced by ff_ass_subtitle_header_default(), init_decoder(), microdvd_init(), and mov_text_init().
ff_ass_subtitle_header_default()
int ff_ass_subtitle_header_default (AVCodecContext * avctx)
Generate a suitable AVCodecContext.subtitle_header for SUBTITLE_ASS with default style.
Parameters
avctx pointer to the AVCodecContext
Returns
>= 0 on success otherwise an error code <0
Definition at line 80 of file ass.c.
Referenced by mov_text_init(), sami_init(), srt_decode_frame(), and teletext_init_decoder().
ff_ass_get_dialog()
char* ff_ass_get_dialog (int readorder, int layer, const char * style, const char * speaker, const char * text)
Craft an ASS dialog string.
Definition at line 93 of file ass.c.
Referenced by create_ass_text(), and ff_ass_add_rect().
ff_ass_add_rect()
int ff_ass_add_rect (AVSubtitle * sub, const char * dialog, int readorder, int layer, const char * style, const char * speaker)
Add an ASS dialog to a subtitle.
Definition at line 101 of file ass.c.
Referenced by decode(), jacosub_decode_frame(), microdvd_decode_frame(), mov_text_decode_frame(), mpl2_decode_frame(), realtext_decode_frame(), sami_decode_frame(), srt_decode_frame(), subviewer_decode_frame(), text_decode_frame(), and webvtt_decode_frame().
ff_ass_decoder_flush()
void ff_ass_decoder_flush (AVCodecContext * avctx)
Helper to flush a text subtitles decoder making use of the FFASSDecoderContext.
Definition at line 124 of file ass.c.
Referenced by srt_decode_frame().
ff_ass_bprint_text_event()
void ff_ass_bprint_text_event (AVBPrint * buf, const char * p, int size, const char * linebreaks, int keep_ass_markup)
Escape a text subtitle using ASS syntax into an AVBPrint buffer.
Newline characters will be escaped to .
Parameters
buf pointer to an initialized AVBPrint buffer
p source text
size size of the source text
linebreaks additional newline chars, which will be escaped to
keep_ass_markup braces and backslash will not be escaped if set
Definition at line 131 of file ass.c.
Referenced by create_ass_text(), and text_decode_frame().