FFmpeg: libavcodec/asvdec.c File Reference
asvdec.c File Reference
ASUS V1/V2 decoder.
#include "libavutil/attributes.h"
#include "libavutil/mem.h"
#include "asv.h"
#include "avcodec.h"
#include "blockdsp.h"
#include "idctdsp.h"
#include "internal.h"
#include "mathops.h"
#include "mpeg12data.h"
Macros
#define VLC_BITS 6
#define ASV2_LEVEL_VLC_BITS 10
Functions
static av_cold void init_vlcs (ASV1Context *a)
static int asv2_get_bits (GetBitContext *gb, int n)
static int asv1_get_level (GetBitContext *gb)
static int asv2_get_level (GetBitContext *gb)
static int asv1_decode_block (ASV1Context *a, int16_t block[64])
static int asv2_decode_block (ASV1Context *a, int16_t block[64])
static int decode_mb (ASV1Context *a, int16_t block[6][64])
static void idct_put (ASV1Context *a, AVFrame *frame, int mb_x, int mb_y)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int decode_init (AVCodecContext *avctx)
static av_cold int decode_end (AVCodecContext *avctx)
Variables
static VLC ccp_vlc
static VLC level_vlc
static VLC dc_ccp_vlc
static VLC ac_ccp_vlc
static VLC asv2_level_vlc
Detailed Description
ASUS V1/V2 decoder.
Definition in file asvdec.c.
Macro Definition Documentation
VLC_BITS
#define VLC_BITS 6
Definition at line 37 of file asvdec.c.
Referenced by asv1_decode_block(), asv1_get_level(), asv2_decode_block(), cfhd_decode(), decode_bgr_1(), decode_plane_bitstream(), ff_cfhd_init_vlcs(), generate_joint_tables(), init_vlcs(), read_huffman_tables(), and read_old_huffman_tables().
ASV2_LEVEL_VLC_BITS
#define ASV2_LEVEL_VLC_BITS 10
Definition at line 38 of file asvdec.c.
Referenced by asv2_get_level(), and init_vlcs().
Function Documentation
init_vlcs()
static av_cold void init_vlcs (ASV1Context * a) static
Definition at line 46 of file asvdec.c.
Referenced by decode_init().
asv2_get_bits()
static int asv2_get_bits (GetBitContext * gb, int n) inline static
Definition at line 72 of file asvdec.c.
Referenced by asv2_decode_block(), and asv2_get_level().
asv1_get_level()
static int asv1_get_level (GetBitContext * gb) inline static
Definition at line 77 of file asvdec.c.
Referenced by asv1_decode_block().
asv2_get_level()
static int asv2_get_level (GetBitContext * gb) inline static
Definition at line 87 of file asvdec.c.
Referenced by asv2_decode_block().
asv1_decode_block()
static int asv1_decode_block (ASV1Context * a, int16_t block[64]) inline static
Definition at line 97 of file asvdec.c.
Referenced by decode_mb().
asv2_decode_block()
static int asv2_decode_block (ASV1Context * a, int16_t block[64]) inline static
Definition at line 128 of file asvdec.c.
Referenced by decode_mb().
decode_mb()
static int decode_mb (ASV1Context * a, int16_t block[6][64]) inline static
Definition at line 164 of file asvdec.c.
Referenced by decode_frame().
idct_put()
static void idct_put (ASV1Context * a, AVFrame * frame, int mb_x, int mb_y) inline static
Definition at line 184 of file asvdec.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 204 of file asvdec.c.
Referenced by decode_end().
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 270 of file asvdec.c.
Referenced by decode_end().
decode_end()
static av_cold int decode_end (AVCodecContext * avctx) static
Definition at line 305 of file asvdec.c.
Variable Documentation
ccp_vlc
VLC ccp_vlc static
Definition at line 40 of file asvdec.c.
level_vlc
VLC level_vlc static
Definition at line 41 of file asvdec.c.
dc_ccp_vlc
VLC dc_ccp_vlc static
Definition at line 42 of file asvdec.c.
ac_ccp_vlc
VLC ac_ccp_vlc static
Definition at line 43 of file asvdec.c.
asv2_level_vlc
VLC asv2_level_vlc static
Definition at line 44 of file asvdec.c.