FFmpeg: libavcodec/asvenc.c File Reference
asvenc.c File Reference
ASUS V1/V2 encoder.
#include "libavutil/attributes.h"
#include "libavutil/mem.h"
#include "aandcttab.h"
#include "asv.h"
#include "avcodec.h"
#include "dct.h"
#include "fdctdsp.h"
#include "internal.h"
#include "mathops.h"
#include "mpeg12data.h"
Macros
#define MAX_MB_SIZE (30 * 16 * 16 * 3 / 2 / 8)
Functions
static void asv2_put_bits (PutBitContext *pb, int n, int v)
static void asv1_put_level (PutBitContext *pb, int level)
static void asv2_put_level (ASV1Context *a, PutBitContext *pb, int level)
static void asv1_encode_block (ASV1Context *a, int16_t block[64])
static void asv2_encode_block (ASV1Context *a, int16_t block[64])
static int encode_mb (ASV1Context *a, int16_t block[6][64])
static void dct_get (ASV1Context *a, const AVFrame *frame, int mb_x, int mb_y)
static int encode_frame (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *pict, int *got_packet)
static av_cold int encode_init (AVCodecContext *avctx)
Detailed Description
ASUS V1/V2 encoder.
Definition in file asvenc.c.
Macro Definition Documentation
MAX_MB_SIZE
#define MAX_MB_SIZE (30 * 16 * 16 * 3 / 2 / 8)
Definition at line 170 of file asvenc.c.
Referenced by encode_frame(), and encode_mb().
Function Documentation
asv2_put_bits()
static void asv2_put_bits (PutBitContext * pb, int n, int v) inline static
Definition at line 38 of file asvenc.c.
Referenced by asv2_encode_block(), and asv2_put_level().
asv1_put_level()
static void asv1_put_level (PutBitContext * pb, int level) inline static
Definition at line 43 of file asvenc.c.
Referenced by asv1_encode_block().
asv2_put_level()
static void asv2_put_level (ASV1Context * a, PutBitContext * pb, int level) inline static
Definition at line 55 of file asvenc.c.
Referenced by asv2_encode_block().
asv1_encode_block()
static void asv1_encode_block (ASV1Context * a, int16_t block[64]) inline static
Definition at line 71 of file asvenc.c.
Referenced by encode_mb().
asv2_encode_block()
static void asv2_encode_block (ASV1Context * a, int16_t block[64]) inline static
Definition at line 117 of file asvenc.c.
Referenced by encode_mb().
encode_mb()
static int encode_mb (ASV1Context * a, int16_t block[6][64]) inline static
Definition at line 172 of file asvenc.c.
Referenced by encode_frame().
dct_get()
static void dct_get (ASV1Context * a, const AVFrame * frame, int mb_x, int mb_y) inline static
Definition at line 192 of file asvenc.c.
Referenced by encode_frame().
encode_frame()
static int encode_frame (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * pict, int * got_packet) static
Definition at line 218 of file asvenc.c.
Referenced by encode_init().
encode_init()
static av_cold int encode_init (AVCodecContext * avctx) static
Definition at line 319 of file asvenc.c.