FFmpeg: libavcodec/atrac3plus.c File Reference
atrac3plus.c File Reference
Bitstream parser for ATRAC3+ decoder.
#include "libavutil/avassert.h"
#include "avcodec.h"
#include "get_bits.h"
#include "atrac3plus.h"
#include "atrac3plus_data.h"
Macros
#define UNPACK_SF_VQ_SHAPE(gb, dst, num_vals)
#define DEC_CT_IDX_COMMON(OP)
#define CODING_DIRECT get_bits(gb, num_bits)
#define CODING_VLC get_vlc2(gb, vlc_tab->table, vlc_tab->bits, 1)
#define CODING_VLC_DELTA
#define CODING_VLC_DIFF
Functions
static av_cold void build_canonical_huff (const uint8_t *cb, const uint8_t *xlat, int *tab_offset, VLC *out_vlc)
Generate canonical VLC table from given descriptor.
av_cold void ff_atrac3p_init_vlcs (void)
Initialize VLC tables for bitstream parsing.
static int num_coded_units (GetBitContext *gb, Atrac3pChanParams *chan, Atrac3pChanUnitCtx *ctx, AVCodecContext *avctx)
Decode number of coded quantization units.
static int add_wordlen_weights (Atrac3pChanUnitCtx *ctx, Atrac3pChanParams *chan, int wtab_idx, AVCodecContext *avctx)
Add weighting coefficients to the decoded word-length information.
static int subtract_sf_weights (Atrac3pChanUnitCtx *ctx, Atrac3pChanParams *chan, int wtab_idx, AVCodecContext *avctx)
Subtract weighting coefficients from decoded scalefactors.
static void unpack_vq_shape (int start_val, const int8_t *shape_vec, int *dst, int num_values)
Unpack vector quantization tables.
static int decode_channel_wordlen (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, int ch_num, AVCodecContext *avctx)
Decode word length for each quantization unit of a channel.
static int decode_channel_sf_idx (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, int ch_num, AVCodecContext *avctx)
Decode scale factor indexes for each quant unit of a channel.
static int decode_quant_wordlen (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, int num_channels, AVCodecContext *avctx)
Decode word length information for each channel.
static int decode_scale_factors (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, int num_channels, AVCodecContext *avctx)
Decode scale factor indexes for each channel.
static int get_num_ct_values (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, AVCodecContext *avctx)
Decode number of code table values.
static int decode_channel_code_tab (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, int ch_num, AVCodecContext *avctx)
Decode code table indexes for each quant unit of a channel.
static int decode_code_table_indexes (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, int num_channels, AVCodecContext *avctx)
Decode code table indexes for each channel.
static void decode_qu_spectra (GetBitContext *gb, const Atrac3pSpecCodeTab *tab, VLC *vlc_tab, int16_t *out, const int num_specs)
Decode huffman-coded spectral lines for a given quant unit.
static void decode_spectrum (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, int num_channels, AVCodecContext *avctx)
Decode huffman-coded IMDCT spectrum for all channels.
static int get_subband_flags (GetBitContext *gb, uint8_t *out, int num_flags)
Retrieve specified amount of flag bits from the input bitstream.
static void decode_window_shape (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, int num_channels)
Decode mdct window shape flags for all channels.
static int decode_gainc_npoints (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, int ch_num, int coded_subbands)
Decode number of gain control points.
static void gainc_level_mode3s (AtracGainInfo *dst, AtracGainInfo *ref)
Implements coding mode 3 (slave) for gain compensation levels.
static void gainc_level_mode1m (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, AtracGainInfo *dst)
Implements coding mode 1 (master) for gain compensation levels.
static int decode_gainc_levels (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, int ch_num, int coded_subbands)
Decode level code for each gain control point.
static void gainc_loc_mode0 (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, AtracGainInfo *dst, int pos)
Implements coding mode 0 for gain compensation locations.
static void gainc_loc_mode1 (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, AtracGainInfo *dst)
Implements coding mode 1 for gain compensation locations.
static int decode_gainc_loc_codes (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, int ch_num, int coded_subbands, AVCodecContext *avctx)
Decode location code for each gain control point.
static int decode_gainc_data (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, int num_channels, AVCodecContext *avctx)
Decode gain control data for all channels.
static void decode_tones_envelope (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, int ch_num, int band_has_tones[])
Decode envelope for all tones of a channel.
static int decode_band_numwavs (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, int ch_num, int band_has_tones[], AVCodecContext *avctx)
Decode number of tones for each subband of a channel.
static void decode_tones_frequency (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, int ch_num, int band_has_tones[])
Decode frequency information for each subband of a channel.
static void decode_tones_amplitude (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, int ch_num, int band_has_tones[])
Decode amplitude information for each subband of a channel.
static void decode_tones_phase (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, int ch_num, int band_has_tones[])
Decode phase information for each subband of a channel.
static int decode_tones_info (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, int num_channels, AVCodecContext *avctx)
Decode tones info for all channels.
int ff_atrac3p_decode_channel_unit (GetBitContext *gb, Atrac3pChanUnitCtx *ctx, int num_channels, AVCodecContext *avctx)
Decode bitstream data of a channel unit.
Variables
static VLC_TYPE tables_data [154276][2]
static VLC wl_vlc_tabs [4]
static VLC sf_vlc_tabs [8]
static VLC ct_vlc_tabs [4]
static VLC spec_vlc_tabs [112]
static VLC gain_vlc_tabs [11]
static VLC tone_vlc_tabs [7]
Detailed Description
Bitstream parser for ATRAC3+ decoder.
Definition in file atrac3plus.c.
Macro Definition Documentation
UNPACK_SF_VQ_SHAPE
#define UNPACK_SF_VQ_SHAPE (gb, dst, num_vals)
Value:
start_val = get_bits((gb), 6);                                       \
    unpack_vq_shape(start_val, &atrac3p_sf_shapes[get_bits((gb), 6)][0], \
                    (dst), (num_vals))
Definition at line 321 of file atrac3plus.c.
Referenced by decode_channel_sf_idx().
DEC_CT_IDX_COMMON
#define DEC_CT_IDX_COMMON (OP)
Value:
num_vals = get_num_ct_values(gb, ctx, avctx);                       \
    if (num_vals < 0)                                                   \
        return num_vals;                                                \
                                                                        \
    for (i = 0; i < num_vals; i++) {                                    \
        if (chan->qu_wordlen[i]) {                                      \
            chan->qu_tab_idx[i] = OP;                                   \
        } else if (ch_num && ref_chan->qu_wordlen[i])                   \
            /* get clone master flag */                                 \
            chan->qu_tab_idx[i] = get_bits1(gb);                        \
    }
Definition at line 690 of file atrac3plus.c.
Referenced by decode_channel_code_tab().
CODING_DIRECT
#define CODING_DIRECT get_bits(gb, num_bits)
Definition at line 703 of file atrac3plus.c.
Referenced by decode_channel_code_tab().
CODING_VLC
#define CODING_VLC get_vlc2(gb, vlc_tab->table, vlc_tab->bits, 1)
Definition at line 705 of file atrac3plus.c.
Referenced by decode_channel_code_tab().
CODING_VLC_DELTA
#define CODING_VLC_DELTA
Value:
(!i) ? CODING_VLC                                                   \
         : (pred + get_vlc2(gb, delta_vlc->table,                       \
                            delta_vlc->bits, 1)) & mask;                \
    pred = chan->qu_tab_idx[i]
Definition at line 707 of file atrac3plus.c.
Referenced by decode_channel_code_tab().
CODING_VLC_DIFF
#define CODING_VLC_DIFF
Value:
(ref_chan->qu_tab_idx[i] +                                          \
     get_vlc2(gb, vlc_tab->table, vlc_tab->bits, 1)) & mask
Definition at line 713 of file atrac3plus.c.
Referenced by decode_channel_code_tab().
Function Documentation
build_canonical_huff()
static av_cold void build_canonical_huff (const uint8_t * cb, const uint8_t * xlat, int * tab_offset, VLC * out_vlc) static
Generate canonical VLC table from given descriptor.
Parameters
[in] cb ptr to codebook descriptor
[in] xlat ptr to translation table or NULL
[in,out] tab_offset starting offset to the generated vlc table
[out] out_vlc ptr to vlc table to be generated
Definition at line 50 of file atrac3plus.c.
Referenced by ff_atrac3p_init_vlcs().
ff_atrac3p_init_vlcs()
av_cold void ff_atrac3p_init_vlcs (void)
Initialize VLC tables for bitstream parsing.
Definition at line 80 of file atrac3plus.c.
Referenced by atrac3p_decode_init().
num_coded_units()
static int num_coded_units (GetBitContext * gb, Atrac3pChanParams * chan, Atrac3pChanUnitCtx * ctx, AVCodecContext * avctx) static
Decode number of coded quantization units.
Parameters
[in] gb the GetBit context
[in,out] chan ptr to the channel parameters
[in,out] ctx ptr to the channel unit context
[in] avctx ptr to the AVCodecContext
Returns
result code: 0 = OK, otherwise - error code
Definition at line 221 of file atrac3plus.c.
Referenced by decode_channel_wordlen().
add_wordlen_weights()
static int add_wordlen_weights (Atrac3pChanUnitCtx * ctx, Atrac3pChanParams * chan, int wtab_idx, AVCodecContext * avctx) static
Add weighting coefficients to the decoded word-length information.
Parameters
[in,out] ctx ptr to the channel unit context
[in,out] chan ptr to the channel parameters
[in] wtab_idx index of the table of weights
[in] avctx ptr to the AVCodecContext
Returns
result code: 0 = OK, otherwise - error code
Definition at line 251 of file atrac3plus.c.
Referenced by decode_channel_wordlen().
subtract_sf_weights()
static int subtract_sf_weights (Atrac3pChanUnitCtx * ctx, Atrac3pChanParams * chan, int wtab_idx, AVCodecContext * avctx) static
Subtract weighting coefficients from decoded scalefactors.
Parameters
[in,out] ctx ptr to the channel unit context
[in,out] chan ptr to the channel parameters
[in] wtab_idx index of table of weights
[in] avctx ptr to the AVCodecContext
Returns
result code: 0 = OK, otherwise - error code
Definition at line 281 of file atrac3plus.c.
Referenced by decode_channel_sf_idx().
unpack_vq_shape()
static void unpack_vq_shape (int start_val, const int8_t * shape_vec, int * dst, int num_values) inline static
Unpack vector quantization tables.
Parameters
[in] start_val start value for the unpacked table
[in] shape_vec ptr to table to unpack
[out] dst ptr to output array
[in] num_values number of values to unpack
Definition at line 309 of file atrac3plus.c.
Referenced by decode_channel_wordlen().
decode_channel_wordlen()
static int decode_channel_wordlen (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, int ch_num, AVCodecContext * avctx) static
Decode word length for each quantization unit of a channel.
Parameters
[in] gb the GetBit context
[in,out] ctx ptr to the channel unit context
[in] ch_num channel to process
[in] avctx ptr to the AVCodecContext
Returns
result code: 0 = OK, otherwise - error code
Definition at line 335 of file atrac3plus.c.
Referenced by decode_quant_wordlen().
decode_channel_sf_idx()
static int decode_channel_sf_idx (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, int ch_num, AVCodecContext * avctx) static
Decode scale factor indexes for each quant unit of a channel.
Parameters
[in] gb the GetBit context
[in,out] ctx ptr to the channel unit context
[in] ch_num channel to process
[in] avctx ptr to the AVCodecContext
Returns
result code: 0 = OK, otherwise - error code
Definition at line 478 of file atrac3plus.c.
Referenced by decode_scale_factors().
decode_quant_wordlen()
static int decode_quant_wordlen (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, int num_channels, AVCodecContext * avctx) static
Decode word length information for each channel.
Parameters
[in] gb the GetBit context
[in,out] ctx ptr to the channel unit context
[in] num_channels number of channels to process
[in] avctx ptr to the AVCodecContext
Returns
result code: 0 = OK, otherwise - error code
Definition at line 613 of file atrac3plus.c.
Referenced by ff_atrac3p_decode_channel_unit().
decode_scale_factors()
static int decode_scale_factors (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, int num_channels, AVCodecContext * avctx) static
Decode scale factor indexes for each channel.
Parameters
[in] gb the GetBit context
[in,out] ctx ptr to the channel unit context
[in] num_channels number of channels to process
[in] avctx ptr to the AVCodecContext
Returns
result code: 0 = OK, otherwise - error code
Definition at line 646 of file atrac3plus.c.
Referenced by ff_atrac3p_decode_channel_unit().
get_num_ct_values()
static int get_num_ct_values (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, AVCodecContext * avctx) static
Decode number of code table values.
Parameters
[in] gb the GetBit context
[in,out] ctx ptr to the channel unit context
[in] avctx ptr to the AVCodecContext
Returns
result code: 0 = OK, otherwise - error code
Definition at line 673 of file atrac3plus.c.
decode_channel_code_tab()
static int decode_channel_code_tab (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, int ch_num, AVCodecContext * avctx) static
Decode code table indexes for each quant unit of a channel.
Parameters
[in] gb the GetBit context
[in,out] ctx ptr to the channel unit context
[in] ch_num channel to process
[in] avctx ptr to the AVCodecContext
Returns
result code: 0 = OK, otherwise - error code
Definition at line 726 of file atrac3plus.c.
Referenced by decode_code_table_indexes().
decode_code_table_indexes()
static int decode_code_table_indexes (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, int num_channels, AVCodecContext * avctx) static
Decode code table indexes for each channel.
Parameters
[in] gb the GetBit context
[in,out] ctx ptr to the channel unit context
[in] num_channels number of channels to process
[in] avctx ptr to the AVCodecContext
Returns
result code: 0 = OK, otherwise - error code
Definition at line 779 of file atrac3plus.c.
Referenced by ff_atrac3p_decode_channel_unit().
decode_qu_spectra()
static void decode_qu_spectra (GetBitContext * gb, const Atrac3pSpecCodeTab * tab, VLC * vlc_tab, int16_t * out, const int num_specs) static
Decode huffman-coded spectral lines for a given quant unit.
This is a generalized version for all known coding modes. Its speed can be improved by creating separate functions for each mode.
Parameters
[in] gb the GetBit context
[in] tab code table telling how to decode spectral lines
[in] vlc_tab ptr to the huffman table associated with the code table
[out] out pointer to buffer where decoded data should be stored
[in] num_specs number of spectral lines to decode
Definition at line 812 of file atrac3plus.c.
Referenced by decode_spectrum().
decode_spectrum()
static void decode_spectrum (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, int num_channels, AVCodecContext * avctx) static
Decode huffman-coded IMDCT spectrum for all channels.
Parameters
[in] gb the GetBit context
[in,out] ctx ptr to the channel unit context
[in] num_channels number of channels to process
[in] avctx ptr to the AVCodecContext
Definition at line 851 of file atrac3plus.c.
Referenced by ff_atrac3p_decode_channel_unit().
get_subband_flags()
static int get_subband_flags (GetBitContext * gb, uint8_t * out, int num_flags) static
Retrieve specified amount of flag bits from the input bitstream.
The data can be shortened in the case of the following two common conditions: if all bits are zero then only one signal bit = 0 will be stored, if all bits are ones then two signal bits = 1,0 will be stored. Otherwise, all necessary bits will be directly stored prefixed by two signal bits = 1,1.
Parameters
[in] gb ptr to the GetBitContext
[out] out where to place decoded flags
[in] num_flags number of flags to process
Returns
: 0 = all flag bits are zero, 1 = there is at least one non-zero flag bit
Definition at line 921 of file atrac3plus.c.
Referenced by decode_tones_info(), decode_window_shape(), and ff_atrac3p_decode_channel_unit().
decode_window_shape()
static void decode_window_shape (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, int num_channels) static
Decode mdct window shape flags for all channels.
Parameters
[in] gb the GetBit context
[in,out] ctx ptr to the channel unit context
[in] num_channels number of channels to process
Definition at line 946 of file atrac3plus.c.
Referenced by ff_atrac3p_decode_channel_unit().
decode_gainc_npoints()
static int decode_gainc_npoints (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, int ch_num, int coded_subbands) static
Decode number of gain control points.
Parameters
[in] gb the GetBit context
[in,out] ctx ptr to the channel unit context
[in] ch_num channel to process
[in] coded_subbands number of subbands to process
Returns
result code: 0 = OK, otherwise - error code
Definition at line 965 of file atrac3plus.c.
Referenced by decode_gainc_data().
gainc_level_mode3s()
static void gainc_level_mode3s (AtracGainInfo * dst, AtracGainInfo * ref) inline static
Implements coding mode 3 (slave) for gain compensation levels.
Parameters
[out] dst ptr to the output array
[in] ref ptr to the reference channel
Definition at line 1030 of file atrac3plus.c.
Referenced by decode_gainc_levels().
gainc_level_mode1m()
static void gainc_level_mode1m (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, AtracGainInfo * dst) inline static
Implements coding mode 1 (master) for gain compensation levels.
Parameters
[in] gb the GetBit context
[in] ctx ptr to the channel unit context
[out] dst ptr to the output array
Definition at line 1045 of file atrac3plus.c.
Referenced by decode_gainc_levels().
decode_gainc_levels()
static int decode_gainc_levels (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, int ch_num, int coded_subbands) static
Decode level code for each gain control point.
Parameters
[in] gb the GetBit context
[in,out] ctx ptr to the channel unit context
[in] ch_num channel to process
[in] coded_subbands number of subbands to process
Returns
result code: 0 = OK, otherwise - error code
Definition at line 1071 of file atrac3plus.c.
Referenced by decode_gainc_data().
gainc_loc_mode0()
static void gainc_loc_mode0 (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, AtracGainInfo * dst, int pos) inline static
Implements coding mode 0 for gain compensation locations.
Parameters
[in] gb the GetBit context
[in] ctx ptr to the channel unit context
[out] dst ptr to the output array
[in] pos position of the value to be processed
Definition at line 1153 of file atrac3plus.c.
Referenced by decode_gainc_loc_codes().
gainc_loc_mode1()
static void gainc_loc_mode1 (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, AtracGainInfo * dst) inline static
Implements coding mode 1 for gain compensation locations.
Parameters
[in] gb the GetBit context
[in] ctx ptr to the channel unit context
[out] dst ptr to the output array
Definition at line 1176 of file atrac3plus.c.
Referenced by decode_gainc_loc_codes().
decode_gainc_loc_codes()
static int decode_gainc_loc_codes (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, int ch_num, int coded_subbands, AVCodecContext * avctx) static
Decode location code for each gain control point.
Parameters
[in] gb the GetBit context
[in,out] ctx ptr to the channel unit context
[in] ch_num channel to process
[in] coded_subbands number of subbands to process
[in] avctx ptr to the AVCodecContext
Returns
result code: 0 = OK, otherwise - error code
Definition at line 1208 of file atrac3plus.c.
Referenced by decode_gainc_data().
decode_gainc_data()
static int decode_gainc_data (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, int num_channels, AVCodecContext * avctx) static
Decode gain control data for all channels.
Parameters
[in] gb the GetBit context
[in,out] ctx ptr to the channel unit context
[in] num_channels number of channels to process
[in] avctx ptr to the AVCodecContext
Returns
result code: 0 = OK, otherwise - error code
Definition at line 1362 of file atrac3plus.c.
Referenced by ff_atrac3p_decode_channel_unit().
decode_tones_envelope()
static void decode_tones_envelope (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, int ch_num, int band_has_tones[]) static
Decode envelope for all tones of a channel.
Parameters
[in] gb the GetBit context
[in,out] ctx ptr to the channel unit context
[in] ch_num channel to process
[in] band_has_tones ptr to an array of per-band-flags: 1 - tone data present
Definition at line 1405 of file atrac3plus.c.
Referenced by decode_tones_info().
decode_band_numwavs()
static int decode_band_numwavs (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, int ch_num, int band_has_tones[], AVCodecContext * avctx) static
Decode number of tones for each subband of a channel.
Parameters
[in] gb the GetBit context
[in,out] ctx ptr to the channel unit context
[in] ch_num channel to process
[in] band_has_tones ptr to an array of per-band-flags: 1 - tone data present
[in] avctx ptr to the AVCodecContext
Returns
result code: 0 = OK, otherwise - error code
fixed-length coding
variable-length coding
VLC modulo delta to master (slave only)
copy master (slave only)
initialize start tone index for each subband
Definition at line 1446 of file atrac3plus.c.
Referenced by decode_tones_info().
decode_tones_frequency()
static void decode_tones_frequency (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, int ch_num, int band_has_tones[]) static
Decode frequency information for each subband of a channel.
Parameters
[in] gb the GetBit context
[in,out] ctx ptr to the channel unit context
[in] ch_num channel to process
[in] band_has_tones ptr to an array of per-band-flags: 1 - tone data present
packed numbers in descending order
packed numbers in ascending order
Definition at line 1510 of file atrac3plus.c.
Referenced by decode_tones_info().
decode_tones_amplitude()
static void decode_tones_amplitude (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, int ch_num, int band_has_tones[]) static
Decode amplitude information for each subband of a channel.
Parameters
[in] gb the GetBit context
[in,out] ctx ptr to the channel unit context
[in] ch_num channel to process
[in] band_has_tones ptr to an array of per-band-flags: 1 - tone data present
fixed-length coding
min + VLC delta
VLC modulo delta to master (slave only)
clone master (slave only)
Definition at line 1570 of file atrac3plus.c.
Referenced by decode_tones_info().
decode_tones_phase()
static void decode_tones_phase (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, int ch_num, int band_has_tones[]) static
Decode phase information for each subband of a channel.
Parameters
[in] gb the GetBit context
[in,out] ctx ptr to the channel unit context
[in] ch_num channel to process
[in] band_has_tones ptr to an array of per-band-flags: 1 - tone data present
Definition at line 1670 of file atrac3plus.c.
Referenced by decode_tones_info().
decode_tones_info()
static int decode_tones_info (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, int num_channels, AVCodecContext * avctx) static
Decode tones info for all channels.
Parameters
[in] gb the GetBit context
[in,out] ctx ptr to the channel unit context
[in] num_channels number of channels to process
[in] avctx ptr to the AVCodecContext
Returns
result code: 0 = OK, otherwise - error code
Definition at line 1695 of file atrac3plus.c.
Referenced by ff_atrac3p_decode_channel_unit().
ff_atrac3p_decode_channel_unit()
int ff_atrac3p_decode_channel_unit (GetBitContext * gb, Atrac3pChanUnitCtx * ctx, int num_channels, AVCodecContext * avctx)
Decode bitstream data of a channel unit.
Parameters
[in] gb the GetBit context
[in,out] ctx ptr to the channel unit context
[in] num_channels number of channels to process
[in] avctx ptr to the AVCodecContext
Returns
result code: 0 = OK, otherwise - error code
Definition at line 1757 of file atrac3plus.c.
Referenced by atrac3p_decode_frame().
Variable Documentation
tables_data
VLC_TYPE tables_data[154276][2] static
Definition at line 34 of file atrac3plus.c.
Referenced by build_canonical_huff(), and ff_atrac3p_init_vlcs().
wl_vlc_tabs
VLC wl_vlc_tabs[4] static
Definition at line 35 of file atrac3plus.c.
sf_vlc_tabs
VLC sf_vlc_tabs[8] static
Definition at line 36 of file atrac3plus.c.
ct_vlc_tabs
VLC ct_vlc_tabs[4] static
Definition at line 37 of file atrac3plus.c.
Referenced by decode_channel_code_tab().
spec_vlc_tabs
VLC spec_vlc_tabs[112] static
Definition at line 38 of file atrac3plus.c.
gain_vlc_tabs
VLC gain_vlc_tabs[11] static
Definition at line 39 of file atrac3plus.c.
tone_vlc_tabs
VLC tone_vlc_tabs[7] static
Definition at line 40 of file atrac3plus.c.