FFmpeg: libavresample/x86/audio_mix_init.c File Reference
audio_mix_init.c File Reference
#include "config.h"
#include "libavutil/cpu.h"
#include "libavutil/x86/cpu.h"
#include "libavresample/audio_mix.h"
Macros
#define DEFINE_MIX_3_8_TO_1_2(chan)
#define SET_MIX_3_8_TO_1_2(chan)
Functions
void ff_mix_2_to_1_fltp_flt_sse (float **src, float **matrix, int len, int out_ch, int in_ch)
void ff_mix_2_to_1_fltp_flt_avx (float **src, float **matrix, int len, int out_ch, int in_ch)
void ff_mix_2_to_1_s16p_flt_sse2 (int16_t **src, float **matrix, int len, int out_ch, int in_ch)
void ff_mix_2_to_1_s16p_flt_sse4 (int16_t **src, float **matrix, int len, int out_ch, int in_ch)
void ff_mix_2_to_1_s16p_q8_sse2 (int16_t **src, int16_t **matrix, int len, int out_ch, int in_ch)
void ff_mix_1_to_2_fltp_flt_sse (float **src, float **matrix, int len, int out_ch, int in_ch)
void ff_mix_1_to_2_fltp_flt_avx (float **src, float **matrix, int len, int out_ch, int in_ch)
void ff_mix_1_to_2_s16p_flt_sse2 (int16_t **src, float **matrix, int len, int out_ch, int in_ch)
void ff_mix_1_to_2_s16p_flt_sse4 (int16_t **src, float **matrix, int len, int out_ch, int in_ch)
void ff_mix_1_to_2_s16p_flt_avx (int16_t **src, float **matrix, int len, int out_ch, int in_ch)
av_cold void ff_audio_mix_init_x86 (AudioMix *am)
Macro Definition Documentation
DEFINE_MIX_3_8_TO_1_2
#define DEFINE_MIX_3_8_TO_1_2 (chan)
Definition at line 51 of file audio_mix_init.c.
SET_MIX_3_8_TO_1_2
#define SET_MIX_3_8_TO_1_2 (chan)
Definition at line 108 of file audio_mix_init.c.
Referenced by ff_audio_mix_init_x86().
Function Documentation
ff_mix_2_to_1_fltp_flt_sse()
void ff_mix_2_to_1_fltp_flt_sse (float ** src, float ** matrix, int len, int out_ch, int in_ch)
Referenced by ff_audio_mix_init_x86().
ff_mix_2_to_1_fltp_flt_avx()
void ff_mix_2_to_1_fltp_flt_avx (float ** src, float ** matrix, int len, int out_ch, int in_ch)
Referenced by ff_audio_mix_init_x86().
ff_mix_2_to_1_s16p_flt_sse2()
void ff_mix_2_to_1_s16p_flt_sse2 (int16_t ** src, float ** matrix, int len, int out_ch, int in_ch)
Referenced by ff_audio_mix_init_x86().
ff_mix_2_to_1_s16p_flt_sse4()
void ff_mix_2_to_1_s16p_flt_sse4 (int16_t ** src, float ** matrix, int len, int out_ch, int in_ch)
Referenced by ff_audio_mix_init_x86().
ff_mix_2_to_1_s16p_q8_sse2()
void ff_mix_2_to_1_s16p_q8_sse2 (int16_t ** src, int16_t ** matrix, int len, int out_ch, int in_ch)
Referenced by ff_audio_mix_init_x86().
ff_mix_1_to_2_fltp_flt_sse()
void ff_mix_1_to_2_fltp_flt_sse (float ** src, float ** matrix, int len, int out_ch, int in_ch)
Referenced by ff_audio_mix_init_x86().
ff_mix_1_to_2_fltp_flt_avx()
void ff_mix_1_to_2_fltp_flt_avx (float ** src, float ** matrix, int len, int out_ch, int in_ch)
Referenced by ff_audio_mix_init_x86().
ff_mix_1_to_2_s16p_flt_sse2()
void ff_mix_1_to_2_s16p_flt_sse2 (int16_t ** src, float ** matrix, int len, int out_ch, int in_ch)
Referenced by ff_audio_mix_init_x86().
ff_mix_1_to_2_s16p_flt_sse4()
void ff_mix_1_to_2_s16p_flt_sse4 (int16_t ** src, float ** matrix, int len, int out_ch, int in_ch)
Referenced by ff_audio_mix_init_x86().
ff_mix_1_to_2_s16p_flt_avx()
void ff_mix_1_to_2_s16p_flt_avx (int16_t ** src, float ** matrix, int len, int out_ch, int in_ch)
Referenced by ff_audio_mix_init_x86().
ff_audio_mix_init_x86()
av_cold void ff_audio_mix_init_x86 (AudioMix * am)
Definition at line 174 of file audio_mix_init.c.
Referenced by mix_function_init().