FFmpeg: libavcodec/audiodsp.c File Reference
audiodsp.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/common.h"
#include "audiodsp.h"
Functions
static uint32_t clipf_c_one (uint32_t a, uint32_t mini, uint32_t maxi, uint32_t maxisign)
static void vector_clipf_c_opposite_sign (float *dst, const float *src, float *min, float *max, int len)
static void vector_clipf_c (float *dst, const float *src, float min, float max, int len)
static int32_t scalarproduct_int16_c (const int16_t *v1, const int16_t *v2, int order)
static void vector_clip_int32_c (int32_t *dst, const int32_t *src, int32_t min, int32_t max, unsigned int len)
av_cold void ff_audiodsp_init (AudioDSPContext *c)
Function Documentation
clipf_c_one()
static uint32_t clipf_c_one (uint32_t a, uint32_t mini, uint32_t maxi, uint32_t maxisign) inline static
Definition at line 25 of file audiodsp.c.
Referenced by vector_clipf_c_opposite_sign().
vector_clipf_c_opposite_sign()
static void vector_clipf_c_opposite_sign (float * dst, const float * src, float * min, float * max, int len) static
Definition at line 36 of file audiodsp.c.
Referenced by vector_clipf_c().
vector_clipf_c()
static void vector_clipf_c (float * dst, const float * src, float min, float max, int len) static
Definition at line 58 of file audiodsp.c.
Referenced by ff_audiodsp_init().
scalarproduct_int16_c()
static int32_t scalarproduct_int16_c (const int16_t * v1, const int16_t * v2, int order) static
Definition at line 79 of file audiodsp.c.
Referenced by ff_audiodsp_init().
vector_clip_int32_c()
static void vector_clip_int32_c (int32_t * dst, const int32_t * src, int32_t min, int32_t max, unsigned int len) static
Definition at line 90 of file audiodsp.c.
Referenced by ff_audiodsp_init().
ff_audiodsp_init()
av_cold void ff_audiodsp_init (AudioDSPContext * c)
Definition at line 106 of file audiodsp.c.
Referenced by cook_decode_init(), decoder_init(), ff_ac3_encode_init(), ra144_decode_init(), ra144_encode_init(), and tak_decode_init().