FFmpeg: libavcodec/arm/audiodsp_init_neon.c File Reference
audiodsp_init_neon.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavcodec/audiodsp.h"
#include "audiodsp_arm.h"
Functions
void ff_vector_clipf_neon (float *dst, const float *src, float min, float max, int len)
void ff_vector_clip_int32_neon (int32_t *dst, const int32_t *src, int32_t min, int32_t max, unsigned int len)
int32_t ff_scalarproduct_int16_neon (const int16_t *v1, const int16_t *v2, int len)
av_cold void ff_audiodsp_init_neon (AudioDSPContext *c)
Function Documentation
ff_vector_clipf_neon()
void ff_vector_clipf_neon (float * dst, const float * src, float min, float max, int len)
Referenced by ff_audiodsp_init_neon().
ff_vector_clip_int32_neon()
void ff_vector_clip_int32_neon (int32_t * dst, const int32_t * src, int32_t min, int32_t max, unsigned int len)
Referenced by ff_audiodsp_init_neon().
ff_scalarproduct_int16_neon()
int32_t ff_scalarproduct_int16_neon (const int16_t * v1, const int16_t * v2, int len)
Referenced by ff_audiodsp_init_neon().
ff_audiodsp_init_neon()
av_cold void ff_audiodsp_init_neon (AudioDSPContext * c)
Definition at line 35 of file audiodsp_init_neon.c.
Referenced by ff_audiodsp_init_arm().