FFmpeg: libavresample/audio_mix.c File Reference
audio_mix.c File Reference
#include <stdint.h>
#include "libavutil/common.h"
#include "libavutil/libm.h"
#include "libavutil/samplefmt.h"
#include "avresample.h"
#include "internal.h"
#include "audio_data.h"
#include "audio_mix.h"
Data Structures
struct AudioMix
Macros
#define MIX_FUNC_NAME(fmt, cfmt) mix_any_ ## fmt ##_## cfmt ##_c
#define MIX_FUNC_GENERIC(fmt, cfmt, stype, ctype, sumtype, expr)
#define GET_MATRIX_CONVERT(suffix, scale)
#define CONVERT_MATRIX(type, expr)
Functions
void ff_audio_mix_set_func (AudioMix *am, enum AVSampleFormat fmt, enum AVMixCoeffType coeff_type, int in_channels, int out_channels, int ptr_align, int samples_align, const char *descr, void *mix_func)
Set mixing function if the parameters match.
MIX_FUNC_GENERIC (S16P, FLT, int16_t, float, float, av_clip_int16(lrintf(sum)))
static void mix_2_to_1_s16p_flt_c (int16_t **samples, float **matrix, int len, int out_ch, int in_ch)
static void mix_2_to_1_s16p_q8_c (int16_t **samples, int16_t **matrix, int len, int out_ch, int in_ch)
static void mix_1_to_2_fltp_flt_c (float **samples, float **matrix, int len, int out_ch, int in_ch)
static void mix_6_to_2_fltp_flt_c (float **samples, float **matrix, int len, int out_ch, int in_ch)
static void mix_2_to_6_fltp_flt_c (float **samples, float **matrix, int len, int out_ch, int in_ch)
static av_cold int mix_function_init (AudioMix *am)
AudioMix * ff_audio_mix_alloc (AVAudioResampleContext *avr)
Allocate and initialize an AudioMix context.
void ff_audio_mix_free (AudioMix **am_p)
Free an AudioMix context.
int ff_audio_mix (AudioMix *am, AudioData *src)
Apply channel mixing to audio data using the current mixing matrix.
int ff_audio_mix_get_matrix (AudioMix *am, double *matrix, int stride)
Get the current mixing matrix.
static void reduce_matrix (AudioMix *am, const double *matrix, int stride)
int ff_audio_mix_set_matrix (AudioMix *am, const double *matrix, int stride)
Set the current mixing matrix.
Variables
static const char *const coeff_type_names [] = { "q8", "q15", "flt" }
Macro Definition Documentation
MIX_FUNC_NAME
#define MIX_FUNC_NAME (fmt, cfmt) mix_any_ ## fmt ##_## cfmt ##_c
Definition at line 99 of file audio_mix.c.
Referenced by mix_function_init().
MIX_FUNC_GENERIC
#define MIX_FUNC_GENERIC (fmt, cfmt, stype, ctype, sumtype, expr)
Value:
static void MIX_FUNC_NAME(fmt, cfmt)(stype **samples, ctype **matrix,       \
                                     int len, int out_ch, int in_ch)        \
{                                                                           \
    int i, in, out;                                                         \
    stype temp[AVRESAMPLE_MAX_CHANNELS];                                    \
    for (i = 0; i < len; i++) {                                             \
        for (out = 0; out < out_ch; out++) {                                \
            sumtype sum = 0;                                                \
            for (in = 0; in < in_ch; in++)                                  \
                sum += samples[in][i] * matrix[out][in];                    \
            temp[out] = expr;                                               \
        }                                                                   \
        for (out = 0; out < out_ch; out++)                                  \
            samples[out][i] = temp[out];                                    \
    }                                                                       \
}
Definition at line 101 of file audio_mix.c.
GET_MATRIX_CONVERT
#define GET_MATRIX_CONVERT (suffix, scale)
Value:
if (!am->matrix_ ## suffix[0]) {                                        \
        av_log(am->avr, AV_LOG_ERROR, "matrix is not set\n");               \
        return AVERROR(EINVAL);                                             \
    }                                                                       \
    for (o = 0, o0 = 0; o < am->out_channels; o++) {                        \
        for (i = 0, i0 = 0; i < am->in_channels; i++) {                     \
            if (am->input_skip[i] || am->output_zero[o])                    \
                matrix[o * stride + i] = 0.0;                               \
            else                                                            \
                matrix[o * stride + i] = am->matrix_ ## suffix[o0][i0] *    \
                                         (scale);                           \
            if (!am->input_skip[i])                                         \
                i0++;                                                       \
        }                                                                   \
        if (!am->output_zero[o])                                            \
            o0++;                                                           \
    }
Referenced by ff_audio_mix_get_matrix().
CONVERT_MATRIX
#define CONVERT_MATRIX (type, expr)
Value:
am->matrix_## type[0] = av_mallocz(am->out_matrix_channels *            \
                                       am->in_matrix_channels  *            \
                                       sizeof(*am->matrix_## type[0]));     \
    if (!am->matrix_## type[0])                                             \
        return AVERROR(ENOMEM);                                             \
    for (o = 0, o0 = 0; o < am->out_channels; o++) {                        \
        if (am->output_zero[o] || am->output_skip[o])                       \
            continue;                                                       \
        if (o0 > 0)                                                         \
            am->matrix_## type[o0] = am->matrix_## type[o0 - 1] +           \
                                     am->in_matrix_channels;                \
        for (i = 0, i0 = 0; i < am->in_channels; i++) {                     \
            double v;                                                       \
            if (am->input_skip[i] || am->output_zero[i])                    \
                continue;                                                   \
            v = matrix[o * stride + i];                                     \
            am->matrix_## type[o0][i0] = expr;                              \
            i0++;                                                           \
        }                                                                   \
        o0++;                                                               \
    }                                                                       \
    am->matrix = (void **)am->matrix_## type;
Referenced by ff_audio_mix_set_matrix().
Function Documentation
ff_audio_mix_set_func()
void ff_audio_mix_set_func (AudioMix * am, enum AVSampleFormat fmt, enum AVMixCoeffType coeff_type, int in_channels, int out_channels, int ptr_align, int samples_align, const char * descr, void * mix_func)
Set mixing function if the parameters match.
This compares the parameters of the mixing function to the parameters in the AudioMix context. If the parameters do not match, no changes are made to the active functions. If the parameters do match and the alignment is not constrained, the function is set as the generic mixing function. If the parameters match and the alignment is constrained, the function is set as the optimized mixing function.
Parameters
am AudioMix context
fmt input/output sample format
coeff_type mixing coefficient type
in_channels number of input channels, or 0 for any number of channels
out_channels number of output channels, or 0 for any number of channels
ptr_align buffer pointer alignment, in bytes
samples_align buffer size alignment, in samples
descr function type description (e.g. "C" or "SSE")
mix_func mixing function pointer
Definition at line 61 of file audio_mix.c.
Referenced by ff_audio_mix_init_x86(), and mix_function_init().
MIX_FUNC_GENERIC()
MIX_FUNC_GENERIC (S16P , FLT , int16_t , float , float , av_clip_int16(lrintf(sum)))
Definition at line 120 of file audio_mix.c.
mix_2_to_1_s16p_flt_c()
static void mix_2_to_1_s16p_flt_c (int16_t ** samples, float ** matrix, int len, int out_ch, int in_ch) static
Definition at line 148 of file audio_mix.c.
Referenced by mix_function_init().
mix_2_to_1_s16p_q8_c()
static void mix_2_to_1_s16p_q8_c (int16_t ** samples, int16_t ** matrix, int len, int out_ch, int in_ch) static
Definition at line 170 of file audio_mix.c.
Referenced by mix_function_init().
mix_1_to_2_fltp_flt_c()
static void mix_1_to_2_fltp_flt_c (float ** samples, float ** matrix, int len, int out_ch, int in_ch) static
Definition at line 192 of file audio_mix.c.
Referenced by mix_function_init().
mix_6_to_2_fltp_flt_c()
static void mix_6_to_2_fltp_flt_c (float ** samples, float ** matrix, int len, int out_ch, int in_ch) static
Definition at line 225 of file audio_mix.c.
Referenced by mix_function_init().
mix_2_to_6_fltp_flt_c()
static void mix_2_to_6_fltp_flt_c (float ** samples, float ** matrix, int len, int out_ch, int in_ch) static
Definition at line 259 of file audio_mix.c.
Referenced by mix_function_init().
mix_function_init()
static av_cold int mix_function_init (AudioMix * am) static
Definition at line 285 of file audio_mix.c.
Referenced by ff_audio_mix_set_matrix().
ff_audio_mix_alloc()
AudioMix* ff_audio_mix_alloc (AVAudioResampleContext * avr)
Allocate and initialize an AudioMix context.
The parameters in the AVAudioResampleContext are used to initialize the AudioMix context.
Parameters
avr AVAudioResampleContext
Returns
newly-allocated AudioMix context.
Definition at line 341 of file audio_mix.c.
Referenced by avresample_open().
ff_audio_mix_free()
void ff_audio_mix_free (AudioMix ** am_p)
Free an AudioMix context.
Definition at line 409 of file audio_mix.c.
Referenced by avresample_close().
ff_audio_mix()
int ff_audio_mix (AudioMix * am, AudioData * src)
Apply channel mixing to audio data using the current mixing matrix.
Definition at line 428 of file audio_mix.c.
Referenced by avresample_convert().
ff_audio_mix_get_matrix()
int ff_audio_mix_get_matrix (AudioMix * am, double * matrix, int stride)
Get the current mixing matrix.
Definition at line 483 of file audio_mix.c.
Referenced by avresample_get_matrix().
reduce_matrix()
static void reduce_matrix (AudioMix * am, const double * matrix, int stride) static
Definition at line 530 of file audio_mix.c.
Referenced by ff_audio_mix_set_matrix().
ff_audio_mix_set_matrix()
int ff_audio_mix_set_matrix (AudioMix * am, const double * matrix, int stride)
Set the current mixing matrix.
Definition at line 653 of file audio_mix.c.
Referenced by avresample_set_matrix(), and ff_audio_mix_alloc().
Variable Documentation
coeff_type_names
const char* const coeff_type_names[] = { "q8", "q15", "flt" } static
Definition at line 31 of file audio_mix.c.
Referenced by ff_audio_mix_set_func(), and mix_function_init().