FFmpeg: libavcodec/audio_frame_queue.h File Reference
audio_frame_queue.h File Reference
#include "avcodec.h"
Data Structures
struct AudioFrame
struct AudioFrameQueue
Functions
void ff_af_queue_init (AVCodecContext *avctx, AudioFrameQueue *afq)
Initialize AudioFrameQueue.
void ff_af_queue_close (AudioFrameQueue *afq)
Close AudioFrameQueue.
int ff_af_queue_add (AudioFrameQueue *afq, const AVFrame *f)
Add a frame to the queue.
void ff_af_queue_remove (AudioFrameQueue *afq, int nb_samples, int64_t *pts, int64_t *duration)
Remove frame(s) from the queue.
Function Documentation
ff_af_queue_init()
void ff_af_queue_init (AVCodecContext * avctx, AudioFrameQueue * afq)
Initialize AudioFrameQueue.
Parameters
avctx context to use for time_base and av_log
afq queue context
Definition at line 28 of file audio_frame_queue.c.
Referenced by aac_encode_init(), amr_decode_fix_avctx(), encode_init(), ffat_init_encoder(), libopus_encode_init(), libshine_encode_init(), libvorbis_encode_init(), mlp_encode_init(), mp3lame_encode_init(), ra144_encode_init(), and wavpack_encode_init().
ff_af_queue_close()
void ff_af_queue_close (AudioFrameQueue * afq)
Close AudioFrameQueue.
Frees memory if needed.
Parameters
afq queue context
Definition at line 36 of file audio_frame_queue.c.
Referenced by aac_encode_close(), aac_encode_end(), amr_decode_fix_avctx(), encode_close(), encode_end(), ffat_close_encoder(), libopus_encode_close(), libshine_encode_close(), libvorbis_encode_close(), mlp_encode_close(), mp3lame_encode_close(), ra144_encode_close(), and wavpack_encode_close().
ff_af_queue_add()
int ff_af_queue_add (AudioFrameQueue * afq, const AVFrame * f)
Add a frame to the queue.
Parameters
afq queue context
f frame to add to the queue
Definition at line 44 of file audio_frame_queue.c.
Referenced by aac_encode_frame(), amr_decode_fix_avctx(), encode_frame(), ffat_encode(), libopus_encode(), libshine_encode_frame(), libvorbis_encode_frame(), mlp_encode_frame(), mp3lame_encode_frame(), ra144_encode_frame(), and wavpack_encode_frame().
ff_af_queue_remove()
void ff_af_queue_remove (AudioFrameQueue * afq, int nb_samples, int64_t * pts, int64_t * duration)
Remove frame(s) from the queue.
Retrieves the pts of the next available frame, or a generated pts based on the last frame duration if there are no frames left in the queue. The number of requested samples should be the full number of samples represented by the packet that will be output by the encoder. If fewer samples are available in the queue, a smaller value will be used for the output duration.
Parameters
afq queue context
nb_samples number of samples to remove from the queue
[out] pts output packet pts
[out] duration output packet duration
Definition at line 75 of file audio_frame_queue.c.
Referenced by aac_encode_frame(), amr_decode_fix_avctx(), encode_frame(), ffat_encode(), libopus_encode(), libshine_encode_frame(), libvorbis_encode_frame(), mlp_encode_frame(), mp3lame_encode_frame(), ra144_encode_frame(), and wavpack_encode_frame().