FFmpeg: libavformat/audiointerleave.h File Reference
audiointerleave.h File Reference
#include "libavutil/fifo.h"
#include "avformat.h"
Data Structures
struct AudioInterleaveContext
Functions
int ff_audio_interleave_init (AVFormatContext *s, const int *samples_per_frame, AVRational time_base)
void ff_audio_interleave_close (AVFormatContext *s)
int ff_audio_rechunk_interleave (AVFormatContext *s, AVPacket *out, AVPacket *pkt, int flush, int(*get_packet)(AVFormatContext *, AVPacket *, AVPacket *, int), int(*compare_ts)(AVFormatContext *, AVPacket *, AVPacket *))
Rechunk audio PCM packets per AudioInterleaveContext->samples_per_frame and interleave them correctly.
Function Documentation
ff_audio_interleave_init()
int ff_audio_interleave_init (AVFormatContext * s, const int * samples_per_frame, AVRational time_base)
Definition at line 41 of file audiointerleave.c.
Referenced by gxf_write_header(), and mxf_write_header().
ff_audio_interleave_close()
void ff_audio_interleave_close (AVFormatContext * s)
Definition at line 29 of file audiointerleave.c.
Referenced by gxf_write_trailer(), and mxf_write_footer().
ff_audio_rechunk_interleave()
int ff_audio_rechunk_interleave (AVFormatContext * s, AVPacket * out, AVPacket * pkt, int flush, int(*)(AVFormatContext *, AVPacket *, AVPacket *, int) get_packet, int(*)(AVFormatContext *, AVPacket *, AVPacket *) compare_ts)
Rechunk audio PCM packets per AudioInterleaveContext->samples_per_frame and interleave them correctly.
The first element of AVStream->priv_data must be AudioInterleaveContext when using this function.
Parameters
get_packet function will output a packet when streams are correctly interleaved.
compare_ts function will compare AVPackets and decide interleaving order.
Definition at line 105 of file audiointerleave.c.
Referenced by gxf_interleave_packet(), and mxf_interleave().