FFmpeg: libavcodec/audiodsp.h File Reference
audiodsp.h File Reference
#include <stdint.h>
Data Structures
struct AudioDSPContext
Functions
void ff_audiodsp_init (AudioDSPContext *c)
void ff_audiodsp_init_arm (AudioDSPContext *c)
void ff_audiodsp_init_ppc (AudioDSPContext *c)
void ff_audiodsp_init_x86 (AudioDSPContext *c)
Function Documentation
ff_audiodsp_init()
void ff_audiodsp_init (AudioDSPContext * c)
Definition at line 106 of file audiodsp.c.
Referenced by cook_decode_init(), decoder_init(), ff_ac3_encode_init(), ra144_decode_init(), ra144_encode_init(), and tak_decode_init().
ff_audiodsp_init_arm()
void ff_audiodsp_init_arm (AudioDSPContext * c)
Definition at line 27 of file audiodsp_init_arm.c.
Referenced by ff_audiodsp_init().
ff_audiodsp_init_ppc()
void ff_audiodsp_init_ppc (AudioDSPContext * c)
Definition at line 64 of file audiodsp.c.
Referenced by ff_audiodsp_init().
ff_audiodsp_init_x86()
void ff_audiodsp_init_x86 (AudioDSPContext * c)
Definition at line 43 of file audiodsp_init.c.
Referenced by ff_audiodsp_init().