FFmpeg: libavfilter/audio.h File Reference
audio.h File Reference
#include "avfilter.h"
#include "internal.h"
Functions
AVFrame * ff_default_get_audio_buffer (AVFilterLink *link, int nb_samples)
default handler for get_audio_buffer() for audio inputs
AVFrame * ff_null_get_audio_buffer (AVFilterLink *link, int nb_samples)
get_audio_buffer() handler for filters which simply pass audio along
AVFrame * ff_get_audio_buffer (AVFilterLink *link, int nb_samples)
Request an audio samples buffer with a specific set of permissions.
Variables
static enum AVSampleFormat ff_packed_sample_fmts_array []
static enum AVSampleFormat ff_planar_sample_fmts_array []
Function Documentation
ff_default_get_audio_buffer()
AVFrame* ff_default_get_audio_buffer (AVFilterLink * link, int nb_samples)
default handler for get_audio_buffer() for audio inputs
Definition at line 35 of file audio.c.
Referenced by ff_get_audio_buffer().
ff_null_get_audio_buffer()
AVFrame* ff_null_get_audio_buffer (AVFilterLink * link, int nb_samples)
get_audio_buffer() handler for filters which simply pass audio along
Definition at line 30 of file audio.c.
Referenced by init().
ff_get_audio_buffer()
AVFrame* ff_get_audio_buffer (AVFilterLink * link, int nb_samples)
Request an audio samples buffer with a specific set of permissions.
Parameters
link the output link to the filter from which the buffer will be requested
nb_samples the number of samples per channel
Returns
A reference to the samples. This must be unreferenced with avfilter_unref_buffer when you are finished with it.
Definition at line 64 of file audio.c.
Referenced by compand_delay(), compand_drain(), compand_nodelay(), compressor(), config_input(), config_output(), ff_filter_frame_framed(), ff_null_get_audio_buffer(), filter_frame(), flush_buffer(), flush_frame(), gate(), get_audio_buffer(), output_frame(), plot_spectrum_column(), push_samples(), read_from_fifo(), request_frame(), return_audio_frame(), send_silence(), take_samples(), and try_push_frame().
Variable Documentation
ff_packed_sample_fmts_array
enum AVSampleFormat ff_packed_sample_fmts_array[] static
Initial value:
= {
    AV_SAMPLE_FMT_U8,
    AV_SAMPLE_FMT_S16,
    AV_SAMPLE_FMT_S32,
    AV_SAMPLE_FMT_FLT,
    AV_SAMPLE_FMT_DBL,
    AV_SAMPLE_FMT_NONE
}
Definition at line 28 of file audio.h.
Referenced by query_formats().
ff_planar_sample_fmts_array
enum AVSampleFormat ff_planar_sample_fmts_array[] static
Initial value:
= {
    AV_SAMPLE_FMT_U8P,
    AV_SAMPLE_FMT_S16P,
    AV_SAMPLE_FMT_S32P,
    AV_SAMPLE_FMT_FLTP,
    AV_SAMPLE_FMT_DBLP,
    AV_SAMPLE_FMT_NONE
}
Definition at line 37 of file audio.h.