FFmpeg: libavcodec/audiotoolboxenc.c File Reference
audiotoolboxenc.c File Reference
#include <AudioToolbox/AudioToolbox.h>
#include "libavfilter/bufferqueue.h"
#include "config.h"
#include "audio_frame_queue.h"
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
#include "libavformat/isom.h"
#include "libavutil/avassert.h"
#include "libavutil/opt.h"
#include "libavutil/log.h"
Data Structures
struct ATDecodeContext
Macros
#define FF_BUFQUEUE_SIZE 256
#define AE AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
#define FFAT_ENC_CLASS(NAME)
#define FFAT_ENC(NAME, ID, PROFILES, ...)
Functions
static UInt32 ffat_get_format_id (enum AVCodecID codec, int profile)
static void ffat_update_ctx (AVCodecContext *avctx)
static int read_descr (GetByteContext *gb, int *tag)
static int get_ilbc_mode (AVCodecContext *avctx)
static av_cold int get_channel_label (int channel)
static int remap_layout (AudioChannelLayout *layout, uint64_t in_layout, int count)
static int get_aac_tag (uint64_t in_layout)
static av_cold int ffat_init_encoder (AVCodecContext *avctx)
static OSStatus ffat_encode_callback (AudioConverterRef converter, UInt32 *nb_packets, AudioBufferList *data, AudioStreamPacketDescription **packets, void *inctx)
static int ffat_encode (AVCodecContext *avctx, AVPacket *avpkt, const AVFrame *frame, int *got_packet_ptr)
static av_cold void ffat_encode_flush (AVCodecContext *avctx)
static av_cold int ffat_close_encoder (AVCodecContext *avctx)
Variables
static const AVProfile aac_profiles []
static const AVOption options []
static const uint64_t aac_at_channel_layouts []
Macro Definition Documentation
FF_BUFQUEUE_SIZE
#define FF_BUFQUEUE_SIZE 256
Definition at line 25 of file audiotoolboxenc.c.
AE
#define AE AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 580 of file audiotoolboxenc.c.
FFAT_ENC_CLASS
#define FFAT_ENC_CLASS (NAME)
Value:
static const AVClass ffat_##NAME##_enc_class = { \
        .class_name = "at_" #NAME "_enc", \
        .item_name  = av_default_item_name, \
        .option     = options, \
        .version    = LIBAVUTIL_VERSION_INT, \
    };
Definition at line 594 of file audiotoolboxenc.c.
FFAT_ENC
#define FFAT_ENC (NAME, ID, PROFILES, ...)
Value:
FFAT_ENC_CLASS(NAME) \
    AVCodec ff_##NAME##_at_encoder = { \
        .name           = #NAME "_at", \
        .long_name      = NULL_IF_CONFIG_SMALL(#NAME " (AudioToolbox)"), \
        .type           = AVMEDIA_TYPE_AUDIO, \
        .id             = ID, \
        .priv_data_size = sizeof(ATDecodeContext), \
        .init           = ffat_init_encoder, \
        .close          = ffat_close_encoder, \
        .encode2        = ffat_encode, \
        .flush          = ffat_encode_flush, \
        .priv_class     = &ffat_##NAME##_enc_class, \
        .capabilities   = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_DELAY __VA_ARGS__, \
        .sample_fmts    = (const enum AVSampleFormat[]) { \
            AV_SAMPLE_FMT_S16, \
            AV_SAMPLE_FMT_U8,  AV_SAMPLE_FMT_NONE \
        }, \
        .caps_internal  = FF_CODEC_CAP_INIT_THREADSAFE, \
        .profiles       = PROFILES, \
    };
Definition at line 602 of file audiotoolboxenc.c.
Function Documentation
ffat_get_format_id()
static UInt32 ffat_get_format_id (enum AVCodecID codec, int profile) static
Definition at line 53 of file audiotoolboxenc.c.
Referenced by ffat_init_encoder().
ffat_update_ctx()
static void ffat_update_ctx (AVCodecContext * avctx) static
Definition at line 86 of file audiotoolboxenc.c.
Referenced by ffat_init_encoder().
read_descr()
static int read_descr (GetByteContext * gb, int * tag) static
Definition at line 126 of file audiotoolboxenc.c.
Referenced by ffat_init_encoder().
get_ilbc_mode()
static int get_ilbc_mode (AVCodecContext * avctx) static
Definition at line 140 of file audiotoolboxenc.c.
Referenced by ffat_init_encoder().
get_channel_label()
static av_cold int get_channel_label (int channel) static
Definition at line 152 of file audiotoolboxenc.c.
Referenced by remap_layout().
remap_layout()
static int remap_layout (AudioChannelLayout * layout, uint64_t in_layout, int count) static
Definition at line 177 of file audiotoolboxenc.c.
Referenced by ffat_init_encoder().
get_aac_tag()
static int get_aac_tag (uint64_t in_layout) static
Definition at line 198 of file audiotoolboxenc.c.
Referenced by ffat_init_encoder().
ffat_init_encoder()
static av_cold int ffat_init_encoder (AVCodecContext * avctx) static
Definition at line 232 of file audiotoolboxenc.c.
ffat_encode_callback()
static OSStatus ffat_encode_callback (AudioConverterRef converter, UInt32 * nb_packets, AudioBufferList * data, AudioStreamPacketDescription ** packets, void * inctx) static
Definition at line 448 of file audiotoolboxenc.c.
Referenced by ffat_encode().
ffat_encode()
static int ffat_encode (AVCodecContext * avctx, AVPacket * avpkt, const AVFrame * frame, int * got_packet_ptr) static
Definition at line 483 of file audiotoolboxenc.c.
ffat_encode_flush()
static av_cold void ffat_encode_flush (AVCodecContext * avctx) static
Definition at line 553 of file audiotoolboxenc.c.
ffat_close_encoder()
static av_cold int ffat_close_encoder (AVCodecContext * avctx) static
Definition at line 561 of file audiotoolboxenc.c.
Variable Documentation
aac_profiles
const AVProfile aac_profiles[] static
Initial value:
= {
    { FF_PROFILE_AAC_LOW,   "LC"       },
    { FF_PROFILE_AAC_HE,    "HE-AAC"   },
    { FF_PROFILE_AAC_HE_V2, "HE-AACv2" },
    { FF_PROFILE_AAC_LD,    "LD"       },
    { FF_PROFILE_AAC_ELD,   "ELD"      },
    { FF_PROFILE_UNKNOWN },
}
Definition at line 571 of file audiotoolboxenc.c.
Referenced by matroska_aac_profile().
options
const AVOption options[] static
Initial value:
= {
    {"aac_at_mode", "ratecontrol mode", 0x42, AV_OPT_TYPE_INT, {.i64 = -1}, -1, kAudioCodecBitRateControlMode_Variable, AE, "mode"},
        {"auto", "VBR if global quality is given; CBR otherwise", 0, AV_OPT_TYPE_CONST, {.i64 = -1}, INT_MIN, INT_MAX, AE, "mode"},
        {"cbr",  "constant bitrate", 0, AV_OPT_TYPE_CONST, {.i64 = kAudioCodecBitRateControlMode_Constant}, INT_MIN, INT_MAX, AE, "mode"},
        {"abr",  "long-term average bitrate", 0, AV_OPT_TYPE_CONST, {.i64 = kAudioCodecBitRateControlMode_LongTermAverage}, INT_MIN, INT_MAX, AE, "mode"},
        {"cvbr", "constrained variable bitrate", 0, AV_OPT_TYPE_CONST, {.i64 = kAudioCodecBitRateControlMode_VariableConstrained}, INT_MIN, INT_MAX, AE, "mode"},
        {"vbr" , "variable bitrate", 0, AV_OPT_TYPE_CONST, {.i64 = kAudioCodecBitRateControlMode_Variable}, INT_MIN, INT_MAX, AE, "mode"},
    {"aac_at_quality", "quality vs speed control", 0x42, AV_OPT_TYPE_INT, {.i64 = 0}, 0, 2, AE},
    { NULL },
}
Definition at line 581 of file audiotoolboxenc.c.
aac_at_channel_layouts
const uint64_t aac_at_channel_layouts[] static
Initial value:
= {
    AV_CH_LAYOUT_MONO,
    AV_CH_LAYOUT_STEREO,
    AV_CH_LAYOUT_SURROUND,
    AV_CH_LAYOUT_4POINT0,
    AV_CH_LAYOUT_5POINT0,
    AV_CH_LAYOUT_5POINT1,
    AV_CH_LAYOUT_6POINT0,
    AV_CH_LAYOUT_6POINT1,
    AV_CH_LAYOUT_7POINT0,
    AV_CH_LAYOUT_7POINT1_WIDE_BACK,
    AV_CH_LAYOUT_QUAD,
    AV_CH_LAYOUT_OCTAGONAL,
    0,
}
Definition at line 624 of file audiotoolboxenc.c.