FFmpeg: libavcodec/audiotoolboxdec.c File Reference
audiotoolboxdec.c File Reference
#include <AudioToolbox/AudioToolbox.h>
#include "config.h"
#include "avcodec.h"
#include "ac3_parser.h"
#include "bytestream.h"
#include "internal.h"
#include "mpegaudiodecheader.h"
#include "libavutil/avassert.h"
#include "libavutil/opt.h"
#include "libavutil/log.h"
Data Structures
struct ATDecodeContext
Macros
#define kAudioFormatEnhancedAC3 'ec-3'
#define COPY_SAMPLES(type)
#define FFAT_DEC_CLASS(NAME)
#define FFAT_DEC(NAME, ID)
Functions
static UInt32 ffat_get_format_id (enum AVCodecID codec, int profile)
static int ffat_get_channel_id (AudioChannelLabel label)
static int ffat_compare_channel_descriptions (const void *a, const void *b)
static AudioChannelLayout * ffat_convert_layout (AudioChannelLayout *layout, UInt32 *size)
static int ffat_update_ctx (AVCodecContext *avctx)
static void put_descr (PutByteContext *pb, int tag, unsigned int size)
static uint8_t * ffat_get_magic_cookie (AVCodecContext *avctx, UInt32 *cookie_size)
static av_cold int ffat_usable_extradata (AVCodecContext *avctx)
static int ffat_set_extradata (AVCodecContext *avctx)
static av_cold int ffat_create_decoder (AVCodecContext *avctx, AVPacket *pkt)
static av_cold int ffat_init_decoder (AVCodecContext *avctx)
static OSStatus ffat_decode_callback (AudioConverterRef converter, UInt32 *nb_packets, AudioBufferList *data, AudioStreamPacketDescription **packets, void *inctx)
static void ffat_copy_samples (AVCodecContext *avctx, AVFrame *frame)
static int ffat_decode (AVCodecContext *avctx, void *data, int *got_frame_ptr, AVPacket *avpkt)
static av_cold void ffat_decode_flush (AVCodecContext *avctx)
static av_cold int ffat_close_decoder (AVCodecContext *avctx)
Macro Definition Documentation
kAudioFormatEnhancedAC3
#define kAudioFormatEnhancedAC3 'ec-3'
Definition at line 36 of file audiotoolboxdec.c.
Referenced by ffat_get_format_id().
COPY_SAMPLES
#define COPY_SAMPLES (type)
Value:
type *in_ptr = (type*)at->decoded_data; \
    type *end_ptr = in_ptr + frame->nb_samples * avctx->channels; \
    type *out_ptr = (type*)frame->data[0]; \
    for (; in_ptr < end_ptr; in_ptr += avctx->channels, out_ptr += avctx->channels) { \
        int c; \
        for (c = 0; c < avctx->channels; c++) \
            out_ptr[c] = in_ptr[at->channel_map[c]]; \
    }
Definition at line 450 of file audiotoolboxdec.c.
Referenced by ffat_copy_samples().
FFAT_DEC_CLASS
#define FFAT_DEC_CLASS (NAME)
Value:
static const AVClass ffat_##NAME##_dec_class = { \
        .class_name = "at_" #NAME "_dec", \
        .version    = LIBAVUTIL_VERSION_INT, \
    };
Definition at line 593 of file audiotoolboxdec.c.
FFAT_DEC
#define FFAT_DEC (NAME, ID)
Value:
FFAT_DEC_CLASS(NAME) \
    AVCodec ff_##NAME##_at_decoder = { \
        .name           = #NAME "_at", \
        .long_name      = NULL_IF_CONFIG_SMALL(#NAME " (AudioToolbox)"), \
        .type           = AVMEDIA_TYPE_AUDIO, \
        .id             = ID, \
        .priv_data_size = sizeof(ATDecodeContext), \
        .init           = ffat_init_decoder, \
        .close          = ffat_close_decoder, \
        .decode         = ffat_decode, \
        .flush          = ffat_decode_flush, \
        .priv_class     = &ffat_##NAME##_dec_class, \
        .capabilities   = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_DELAY, \
        .caps_internal  = FF_CODEC_CAP_INIT_THREADSAFE, \
    };
Definition at line 599 of file audiotoolboxdec.c.
Function Documentation
ffat_get_format_id()
static UInt32 ffat_get_format_id (enum AVCodecID codec, int profile) static
Definition at line 57 of file audiotoolboxdec.c.
Referenced by ffat_create_decoder().
ffat_get_channel_id()
static int ffat_get_channel_id (AudioChannelLabel label) static
Definition at line 96 of file audiotoolboxdec.c.
Referenced by ffat_compare_channel_descriptions(), and ffat_update_ctx().
ffat_compare_channel_descriptions()
static int ffat_compare_channel_descriptions (const void * a, const void * b) static
Definition at line 124 of file audiotoolboxdec.c.
Referenced by ffat_update_ctx().
ffat_convert_layout()
static AudioChannelLayout* ffat_convert_layout (AudioChannelLayout * layout, UInt32 * size) static
Definition at line 131 of file audiotoolboxdec.c.
Referenced by ffat_update_ctx().
ffat_update_ctx()
static int ffat_update_ctx (AVCodecContext * avctx) static
Definition at line 159 of file audiotoolboxdec.c.
Referenced by ffat_create_decoder().
put_descr()
static void put_descr (PutByteContext * pb, int tag, unsigned int size) static
Definition at line 219 of file audiotoolboxdec.c.
Referenced by ffat_get_magic_cookie().
ffat_get_magic_cookie()
static uint8_t* ffat_get_magic_cookie (AVCodecContext * avctx, UInt32 * cookie_size) static
Definition at line 228 of file audiotoolboxdec.c.
Referenced by ffat_create_decoder(), and ffat_set_extradata().
ffat_usable_extradata()
static av_cold int ffat_usable_extradata (AVCodecContext * avctx) static
Definition at line 268 of file audiotoolboxdec.c.
Referenced by ffat_create_decoder(), ffat_init_decoder(), and ffat_set_extradata().
ffat_set_extradata()
static int ffat_set_extradata (AVCodecContext * avctx) static
Definition at line 278 of file audiotoolboxdec.c.
Referenced by ffat_create_decoder().
ffat_create_decoder()
static av_cold int ffat_create_decoder (AVCodecContext * avctx, AVPacket * pkt) static
Definition at line 300 of file audiotoolboxdec.c.
Referenced by ffat_decode(), and ffat_init_decoder().
ffat_init_decoder()
static av_cold int ffat_init_decoder (AVCodecContext * avctx) static
Definition at line 399 of file audiotoolboxdec.c.
ffat_decode_callback()
static OSStatus ffat_decode_callback (AudioConverterRef converter, UInt32 * nb_packets, AudioBufferList * data, AudioStreamPacketDescription ** packets, void * inctx) static
Definition at line 411 of file audiotoolboxdec.c.
Referenced by ffat_decode().
ffat_copy_samples()
static void ffat_copy_samples (AVCodecContext * avctx, AVFrame * frame) static
Definition at line 460 of file audiotoolboxdec.c.
Referenced by ffat_decode().
ffat_decode()
static int ffat_decode (AVCodecContext * avctx, void * data, int * got_frame_ptr, AVPacket * avpkt) static
Definition at line 470 of file audiotoolboxdec.c.
ffat_decode_flush()
static av_cold void ffat_decode_flush (AVCodecContext * avctx) static
Definition at line 574 of file audiotoolboxdec.c.
ffat_close_decoder()
static av_cold int ffat_close_decoder (AVCodecContext * avctx) static
Definition at line 582 of file audiotoolboxdec.c.