FFmpeg: tests/audiomatch.c File Reference
audiomatch.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <inttypes.h>
Macros
#define FFMIN(a, b) ((a) > (b) ? (b) : (a))
#define FFMAX(a, b) ((a) > (b) ? (a) : (b))
Functions
static int64_t fsize (FILE *f)
int main (int argc, char **argv)
Macro Definition Documentation
FFMIN
#define FFMIN (a, b) ((a) > (b) ? (b) : (a))
Definition at line 25 of file audiomatch.c.
Referenced by main().
FFMAX
#define FFMAX (a, b) ((a) > (b) ? (a) : (b))
Definition at line 26 of file audiomatch.c.
Referenced by main().
Function Documentation
fsize()
static int64_t fsize (FILE * f) static
Definition at line 28 of file audiomatch.c.
Referenced by adts_aac_probe(), asf_read_stream_properties(), avi_read_header(), bmp_decode_frame(), dv_write_packet(), dxa_read_header(), ffserver_parse_config_feed(), flush(), flv_read_packet(), init_stream(), loas_probe(), main(), mp3_parse_info_tag(), pmp_header(), and thp_read_header().
main()
int main (int argc, char ** argv)
Definition at line 36 of file audiomatch.c.