FFmpeg: libavformat/avc.h File Reference
avc.h File Reference
#include <stdint.h>
#include "avio.h"
Functions
int ff_avc_parse_nal_units (AVIOContext *s, const uint8_t *buf, int size)
int ff_avc_parse_nal_units_buf (const uint8_t *buf_in, uint8_t **buf, int *size)
int ff_isom_write_avcc (AVIOContext *pb, const uint8_t *data, int len)
const uint8_t * ff_avc_find_startcode (const uint8_t *p, const uint8_t *end)
int ff_avc_write_annexb_extradata (const uint8_t *in, uint8_t **buf, int *size)
const uint8_t * ff_avc_mp4_find_startcode (const uint8_t *start, const uint8_t *end, int nal_length_size)
Function Documentation
ff_avc_parse_nal_units()
int ff_avc_parse_nal_units (AVIOContext * s, const uint8_t * buf, int size)
Definition at line 70 of file avc.c.
Referenced by ff_avc_parse_nal_units_buf(), ff_hevc_annexb2mp4(), and ff_mov_write_packet().
ff_avc_parse_nal_units_buf()
int ff_avc_parse_nal_units_buf (const uint8_t * buf_in, uint8_t ** buf, int * size)
Definition at line 92 of file avc.c.
Referenced by ff_hevc_annexb2mp4(), ff_isom_write_avcc(), ff_isom_write_hvcc(), ff_mov_write_packet(), flv_write_packet(), and mkv_write_block().
ff_isom_write_avcc()
int ff_isom_write_avcc (AVIOContext * pb, const uint8_t * data, int len)
Definition at line 106 of file avc.c.
Referenced by flv_write_codec_header(), mkv_write_native_codecprivate(), mov_write_avcc_tag(), and set_codec_str().
ff_avc_find_startcode()
const uint8_t* ff_avc_find_startcode (const uint8_t * p, const uint8_t * end)
Definition at line 64 of file avc.c.
Referenced by ff_avc_parse_nal_units(), ff_mov_cenc_avc_parse_nal_units(), and ff_rtp_send_h264_hevc().
ff_avc_write_annexb_extradata()
int ff_avc_write_annexb_extradata (const uint8_t * in, uint8_t ** buf, int * size)
Definition at line 164 of file avc.c.
Referenced by get_private_data(), and mov_write_isml_manifest().
ff_avc_mp4_find_startcode()
const uint8_t* ff_avc_mp4_find_startcode (const uint8_t * start, const uint8_t * end, int nal_length_size)
Definition at line 195 of file avc.c.
Referenced by ff_rtp_send_h264_hevc().