FFmpeg: libavdevice/avdevice.c File Reference
avdevice.c File Reference
#include "libavutil/avassert.h"
#include "libavutil/samplefmt.h"
#include "libavutil/pixfmt.h"
#include "libavcodec/avcodec.h"
#include "avdevice.h"
#include "internal.h"
#include "config.h"
#include "libavutil/ffversion.h"
Macros
#define E AV_OPT_FLAG_ENCODING_PARAM
#define D AV_OPT_FLAG_DECODING_PARAM
#define A AV_OPT_FLAG_AUDIO_PARAM
#define V AV_OPT_FLAG_VIDEO_PARAM
#define OFFSET(x) offsetof(AVDeviceCapabilitiesQuery, x)
#define LICENSE_PREFIX "libavdevice license: "
Functions
unsigned avdevice_version (void)
Return the LIBAVDEVICE_VERSION_INT constant.
const char * avdevice_configuration (void)
Return the libavdevice build-time configuration.
const char * avdevice_license (void)
Return the libavdevice license.
static void * device_next (void *prev, int output, AVClassCategory c1, AVClassCategory c2)
AVInputFormat * av_input_audio_device_next (AVInputFormat *d)
Audio input devices iterator.
AVInputFormat * av_input_video_device_next (AVInputFormat *d)
Video input devices iterator.
AVOutputFormat * av_output_audio_device_next (AVOutputFormat *d)
Audio output devices iterator.
AVOutputFormat * av_output_video_device_next (AVOutputFormat *d)
Video output devices iterator.
int avdevice_app_to_dev_control_message (struct AVFormatContext *s, enum AVAppToDevMessageType type, void *data, size_t data_size)
Send control message from application to device.
int avdevice_dev_to_app_control_message (struct AVFormatContext *s, enum AVDevToAppMessageType type, void *data, size_t data_size)
Send control message from device to application.
int avdevice_capabilities_create (AVDeviceCapabilitiesQuery **caps, AVFormatContext *s, AVDictionary **device_options)
Initialize capabilities probing API based on AVOption API.
void avdevice_capabilities_free (AVDeviceCapabilitiesQuery **caps, AVFormatContext *s)
Free resources created by avdevice_capabilities_create()
int avdevice_list_devices (AVFormatContext *s, AVDeviceInfoList **device_list)
List devices.
static int list_devices_for_context (AVFormatContext *s, AVDictionary *options, AVDeviceInfoList **device_list)
int avdevice_list_input_sources (AVInputFormat *device, const char *device_name, AVDictionary *device_options, AVDeviceInfoList **device_list)
List devices.
int avdevice_list_output_sinks (AVOutputFormat *device, const char *device_name, AVDictionary *device_options, AVDeviceInfoList **device_list)
void avdevice_free_list_devices (AVDeviceInfoList **device_list)
Convenient function to free result of avdevice_list_devices().
Variables
const char av_device_ffversion [] = "FFmpeg version " FFMPEG_VERSION
const AVOption av_device_capabilities []
AVOption table used by devices to implement device capabilities API.
Macro Definition Documentation
E
#define E AV_OPT_FLAG_ENCODING_PARAM
Definition at line 30 of file avdevice.c.
D
#define D AV_OPT_FLAG_DECODING_PARAM
Definition at line 31 of file avdevice.c.
A
#define A AV_OPT_FLAG_AUDIO_PARAM
Definition at line 32 of file avdevice.c.
V
#define V AV_OPT_FLAG_VIDEO_PARAM
Definition at line 33 of file avdevice.c.
OFFSET
#define OFFSET (x) offsetof(AVDeviceCapabilitiesQuery, x)
Definition at line 34 of file avdevice.c.
LICENSE_PREFIX
#define LICENSE_PREFIX "libavdevice license: "
Referenced by avdevice_license().
Function Documentation
device_next()
static void* device_next (void * prev, int output, AVClassCategory c1, AVClassCategory c2) static
Definition at line 81 of file avdevice.c.
Referenced by av_input_audio_device_next(), av_input_video_device_next(), av_output_audio_device_next(), and av_output_video_device_next().
list_devices_for_context()
static int list_devices_for_context (AVFormatContext * s, AVDictionary * options, AVDeviceInfoList ** device_list) static
Definition at line 212 of file avdevice.c.
Referenced by avdevice_list_input_sources(), and avdevice_list_output_sinks().
Variable Documentation
av_device_ffversion
const char av_device_ffversion[] = "FFmpeg version " FFMPEG_VERSION
Definition at line 28 of file avdevice.c.