FFmpeg: libavfilter/avf_avectorscope.c File Reference
avf_avectorscope.c File Reference
audio to video multimedia vectorscope filter
#include "libavutil/avassert.h"
#include "libavutil/channel_layout.h"
#include "libavutil/opt.h"
#include "libavutil/parseutils.h"
#include "avfilter.h"
#include "formats.h"
#include "audio.h"
#include "video.h"
#include "internal.h"
Data Structures
struct AudioVectorScopeContext
Macros
#define OFFSET(x) offsetof(AudioVectorScopeContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Enumerations
enum VectorScopeMode { LISSAJOUS, LISSAJOUS_XY, POLAR, MODE_NB }
enum VectorScopeDraw { DOT, LINE, DRAW_NB }
enum VectorScopeScale {
LIN, SQRT, CBRT, LOG,
SCALE_NB
}
Functions
AVFILTER_DEFINE_CLASS (avectorscope)
static void draw_dot (AudioVectorScopeContext *s, unsigned x, unsigned y)
static void draw_line (AudioVectorScopeContext *s, int x0, int y0, int x1, int y1)
static void fade (AudioVectorScopeContext *s)
static int query_formats (AVFilterContext *ctx)
static int config_input (AVFilterLink *inlink)
static int config_output (AVFilterLink *outlink)
static int filter_frame (AVFilterLink *inlink, AVFrame *insamples)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const AVOption avectorscope_options []
static const AVFilterPad audiovectorscope_inputs []
static const AVFilterPad audiovectorscope_outputs []
AVFilter ff_avf_avectorscope
Detailed Description
audio to video multimedia vectorscope filter
Definition in file avf_avectorscope.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(AudioVectorScopeContext, x)
Definition at line 72 of file avf_avectorscope.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 73 of file avf_avectorscope.c.
Enumeration Type Documentation
VectorScopeMode
enum VectorScopeMode
Enumerator
LISSAJOUS
LISSAJOUS_XY
POLAR
MODE_NB
Definition at line 36 of file avf_avectorscope.c.
VectorScopeDraw
enum VectorScopeDraw
Enumerator
DOT
LINE
DRAW_NB
Definition at line 43 of file avf_avectorscope.c.
VectorScopeScale
enum VectorScopeScale
Enumerator
LIN
SQRT
CBRT
LOG
SCALE_NB
Definition at line 49 of file avf_avectorscope.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (avectorscope)
draw_dot()
static void draw_dot (AudioVectorScopeContext * s, unsigned x, unsigned y) static
Definition at line 107 of file avf_avectorscope.c.
Referenced by draw_line(), and filter_frame().
draw_line()
static void draw_line (AudioVectorScopeContext * s, int x0, int y0, int x1, int y1) static
Definition at line 127 of file avf_avectorscope.c.
Referenced by filter_frame().
fade()
static void fade (AudioVectorScopeContext * s) static
Definition at line 153 of file avf_avectorscope.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 172 of file avf_avectorscope.c.
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 199 of file avf_avectorscope.c.
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 213 of file avf_avectorscope.c.
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * insamples) static
Definition at line 228 of file avf_avectorscope.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 319 of file avf_avectorscope.c.
Variable Documentation
avectorscope_options
const AVOption avectorscope_options[] static
Initial value:
= {
    { "mode", "set mode", OFFSET(mode), AV_OPT_TYPE_INT, {.i64=LISSAJOUS}, 0, MODE_NB-1, FLAGS, "mode" },
    { "m",    "set mode", OFFSET(mode), AV_OPT_TYPE_INT, {.i64=LISSAJOUS}, 0, MODE_NB-1, FLAGS, "mode" },
    { "lissajous",    "", 0, AV_OPT_TYPE_CONST, {.i64=LISSAJOUS},    0, 0, FLAGS, "mode" },
    { "lissajous_xy", "", 0, AV_OPT_TYPE_CONST, {.i64=LISSAJOUS_XY}, 0, 0, FLAGS, "mode" },
    { "polar",        "", 0, AV_OPT_TYPE_CONST, {.i64=POLAR},        0, 0, FLAGS, "mode" },
    { "rate", "set video rate", OFFSET(frame_rate), AV_OPT_TYPE_VIDEO_RATE, {.str="25"}, 0, INT_MAX, FLAGS },
    { "r",    "set video rate", OFFSET(frame_rate), AV_OPT_TYPE_VIDEO_RATE, {.str="25"}, 0, INT_MAX, FLAGS },
    { "size", "set video size", OFFSET(w), AV_OPT_TYPE_IMAGE_SIZE, {.str="400x400"}, 0, 0, FLAGS },
    { "s",    "set video size", OFFSET(w), AV_OPT_TYPE_IMAGE_SIZE, {.str="400x400"}, 0, 0, FLAGS },
    { "rc", "set red contrast",   OFFSET(contrast[0]), AV_OPT_TYPE_INT, {.i64=40},  0, 255, FLAGS },
    { "gc", "set green contrast", OFFSET(contrast[1]), AV_OPT_TYPE_INT, {.i64=160}, 0, 255, FLAGS },
    { "bc", "set blue contrast",  OFFSET(contrast[2]), AV_OPT_TYPE_INT, {.i64=80},  0, 255, FLAGS },
    { "ac", "set alpha contrast", OFFSET(contrast[3]), AV_OPT_TYPE_INT, {.i64=255}, 0, 255, FLAGS },
    { "rf", "set red fade",       OFFSET(fade[0]), AV_OPT_TYPE_INT, {.i64=15}, 0, 255, FLAGS },
    { "gf", "set green fade",     OFFSET(fade[1]), AV_OPT_TYPE_INT, {.i64=10}, 0, 255, FLAGS },
    { "bf", "set blue fade",      OFFSET(fade[2]), AV_OPT_TYPE_INT, {.i64=5},  0, 255, FLAGS },
    { "af", "set alpha fade",     OFFSET(fade[3]), AV_OPT_TYPE_INT, {.i64=5},  0, 255, FLAGS },
    { "zoom", "set zoom factor",  OFFSET(zoom), AV_OPT_TYPE_DOUBLE, {.dbl=1},  1, 10, FLAGS },
    { "draw", "set draw mode", OFFSET(draw), AV_OPT_TYPE_INT, {.i64=DOT}, 0, DRAW_NB-1, FLAGS, "draw" },
    { "dot",   "", 0, AV_OPT_TYPE_CONST, {.i64=DOT} , 0, 0, FLAGS, "draw" },
    { "line",  "", 0, AV_OPT_TYPE_CONST, {.i64=LINE}, 0, 0, FLAGS, "draw" },
    { "scale", "set amplitude scale mode", OFFSET(scale), AV_OPT_TYPE_INT, {.i64=LIN}, 0, SCALE_NB-1, FLAGS, "scale" },
    { "lin",   "linear",      0, AV_OPT_TYPE_CONST, {.i64=LIN},  0, 0, FLAGS, "scale" },
    { "sqrt",  "square root", 0, AV_OPT_TYPE_CONST, {.i64=SQRT}, 0, 0, FLAGS, "scale" },
    { "cbrt",  "cube root",   0, AV_OPT_TYPE_CONST, {.i64=CBRT}, 0, 0, FLAGS, "scale" },
    { "log",   "logarithmic", 0, AV_OPT_TYPE_CONST, {.i64=LOG},  0, 0, FLAGS, "scale" },
    { NULL }
}
Definition at line 75 of file avf_avectorscope.c.
audiovectorscope_inputs
const AVFilterPad audiovectorscope_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_AUDIO,
        .config_props = config_input,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 326 of file avf_avectorscope.c.
audiovectorscope_outputs
const AVFilterPad audiovectorscope_outputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .config_props = config_output,
    },
    { NULL }
}
Definition at line 336 of file avf_avectorscope.c.
ff_avf_avectorscope
AVFilter ff_avf_avectorscope
Initial value:
= {
    .name          = "avectorscope",
    .description   = NULL_IF_CONFIG_SMALL("Convert input audio to vectorscope video output."),
    .uninit        = uninit,
    .query_formats = query_formats,
    .priv_size     = sizeof(AudioVectorScopeContext),
    .inputs        = audiovectorscope_inputs,
    .outputs       = audiovectorscope_outputs,
    .priv_class    = &avectorscope_class,
}
Definition at line 345 of file avf_avectorscope.c.