FFmpeg: libavfilter/avf_showspectrum.c File Reference
avf_showspectrum.c File Reference
audio to spectrum (video) transmedia filter, based on ffplay rdft showmode (by Michael Niedermayer) and lavfi/avf_showwaves (by Stefano Sabatini).
#include <math.h>
#include "libavcodec/avfft.h"
#include "libavutil/audio_fifo.h"
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/channel_layout.h"
#include "libavutil/opt.h"
#include "libavutil/xga_font_data.h"
#include "audio.h"
#include "video.h"
#include "avfilter.h"
#include "internal.h"
#include "window_func.h"
Data Structures
struct ShowSpectrumContext
struct ColorTable
Macros
#define OFFSET(x) offsetof(ShowSpectrumContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
#define RE(y, ch) s->fft_data[ch][y].re
#define IM(y, ch) s->fft_data[ch][y].im
#define MAGNITUDE(y, ch) hypot(RE(y, ch), IM(y, ch))
#define PHASE(y, ch) atan2(IM(y, ch), RE(y, ch))
Enumerations
enum DisplayMode {
SINGLE, SEPARATE, NB_DMODES, LINE,
BAR, DOT, NB_MODES, COMBINED,
SEPARATE, NB_MODES
}
enum DataMode { D_MAGNITUDE, D_PHASE, NB_DMODES }
enum DisplayScale {
LINEAR, SQRT, CBRT, LOG,
RLOG, NB_SCALES, LINEAR, SQRT,
CBRT, LOG, FOURTHRT, FIFTHRT,
NB_SCALES
}
enum ColorMode {
CHANNEL, INTENSITY, RAINBOW, MORELAND,
NEBULAE, FIRE, FIERY, FRUIT,
COOL, NB_CLMODES, COLOR_MODE_NONE = -1, COLOR_MODE_BT709,
COLOR_MODE_FCC, COLOR_MODE_BT601, COLOR_MODE_SMPTE240M, COLOR_MODE_BT2020,
COLOR_MODE_COUNT
}
enum SlideMode {
REPLACE, SCROLL, NB_SLIDES, REPLACE,
SCROLL, FULLFRAME, RSCROLL, NB_SLIDES,
REPLACE, SCROLL, FULLFRAME, RSCROLL,
NB_SLIDES
}
enum Orientation {
VERTICAL, HORIZONTAL, NB_ORIENTATIONS, VERTICAL,
HORIZONTAL, NB_ORIENTATIONS
}
Functions
AVFILTER_DEFINE_CLASS (showspectrum)
static av_cold void uninit (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static int config_output (AVFilterLink *outlink)
static int run_channel_fft (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int calc_channel_magnitudes (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int calc_channel_phases (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static void acalc_magnitudes (ShowSpectrumContext *s)
static void scale_magnitudes (ShowSpectrumContext *s, float scale)
static void color_range (ShowSpectrumContext *s, int ch, float *yf, float *uf, float *vf)
static void pick_color (ShowSpectrumContext *s, float yf, float uf, float vf, float a, float *out)
static void clear_combine_buffer (ShowSpectrumContext *s, int size)
static int plot_channel (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int plot_spectrum_column (AVFilterLink *inlink, AVFrame *insamples)
Variables
static const AVOption showspectrum_options []
static const struct ColorTable color_table [][8]
Detailed Description
audio to spectrum (video) transmedia filter, based on ffplay rdft showmode (by Michael Niedermayer) and lavfi/avf_showwaves (by Stefano Sabatini).
Definition in file avf_showspectrum.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(ShowSpectrumContext, x)
Definition at line 88 of file avf_showspectrum.c.
Referenced by plot_spectrum_column().
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 89 of file avf_showspectrum.c.
Referenced by plot_spectrum_column().
RE
#define RE (y, ch) s->fft_data[ch][y].re
Definition at line 485 of file avf_showspectrum.c.
IM
#define IM (y, ch) s->fft_data[ch][y].im
Definition at line 486 of file avf_showspectrum.c.
MAGNITUDE
#define MAGNITUDE (y, ch) hypot(RE(y, ch), IM(y, ch))
Definition at line 487 of file avf_showspectrum.c.
Referenced by acalc_magnitudes(), and calc_channel_magnitudes().
PHASE
#define PHASE (y, ch) atan2(IM(y, ch), RE(y, ch))
Definition at line 488 of file avf_showspectrum.c.
Referenced by avfilter_register_all(), and calc_channel_phases().
Enumeration Type Documentation
DisplayMode
enum DisplayMode
Enumerator
SINGLE
SEPARATE
NB_DMODES
LINE
BAR
DOT
NB_MODES
COMBINED
SEPARATE
NB_MODES
Definition at line 44 of file avf_showspectrum.c.
DataMode
enum DataMode
Enumerator
D_MAGNITUDE
D_PHASE
NB_DMODES
Definition at line 45 of file avf_showspectrum.c.
DisplayScale
enum DisplayScale
Enumerator
LINEAR
SQRT
CBRT
LOG
RLOG
NB_SCALES
LINEAR
SQRT
CBRT
LOG
FOURTHRT
FIFTHRT
NB_SCALES
Definition at line 46 of file avf_showspectrum.c.
ColorMode
enum ColorMode
Enumerator
CHANNEL
INTENSITY
RAINBOW
MORELAND
NEBULAE
FIRE
FIERY
FRUIT
COOL
NB_CLMODES
COLOR_MODE_NONE
COLOR_MODE_BT709
COLOR_MODE_FCC
COLOR_MODE_BT601
COLOR_MODE_SMPTE240M
COLOR_MODE_BT2020
COLOR_MODE_COUNT
Definition at line 47 of file avf_showspectrum.c.
SlideMode
enum SlideMode
Enumerator
REPLACE
SCROLL
NB_SLIDES
REPLACE
SCROLL
FULLFRAME
RSCROLL
NB_SLIDES
REPLACE
SCROLL
FULLFRAME
RSCROLL
NB_SLIDES
Definition at line 48 of file avf_showspectrum.c.
Orientation
enum Orientation
Enumerator
VERTICAL
HORIZONTAL
NB_ORIENTATIONS
VERTICAL
HORIZONTAL
NB_ORIENTATIONS
Definition at line 49 of file avf_showspectrum.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (showspectrum)
Referenced by plot_spectrum_column().
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 227 of file avf_showspectrum.c.
Referenced by plot_spectrum_column().
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 263 of file avf_showspectrum.c.
Referenced by plot_spectrum_column().
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 294 of file avf_showspectrum.c.
Referenced by plot_spectrum_column().
run_channel_fft()
static int run_channel_fft (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 462 of file avf_showspectrum.c.
Referenced by plot_spectrum_column().
calc_channel_magnitudes()
static int calc_channel_magnitudes (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 490 of file avf_showspectrum.c.
Referenced by plot_spectrum_column().
calc_channel_phases()
static int calc_channel_phases (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 505 of file avf_showspectrum.c.
Referenced by plot_spectrum_column().
acalc_magnitudes()
static void acalc_magnitudes (ShowSpectrumContext * s) static
Definition at line 519 of file avf_showspectrum.c.
Referenced by plot_spectrum_column().
scale_magnitudes()
static void scale_magnitudes (ShowSpectrumContext * s, float scale) static
Definition at line 533 of file avf_showspectrum.c.
Referenced by plot_spectrum_column().
color_range()
static void color_range (ShowSpectrumContext * s, int ch, float * yf, float * uf, float * vf) static
Definition at line 545 of file avf_showspectrum.c.
Referenced by plot_channel().
pick_color()
static void pick_color (ShowSpectrumContext * s, float yf, float uf, float vf, float a, float * out) static
Definition at line 601 of file avf_showspectrum.c.
Referenced by plot_channel(), and plot_spectrum_column().
clear_combine_buffer()
static void clear_combine_buffer (ShowSpectrumContext * s, int size) static
Definition at line 645 of file avf_showspectrum.c.
Referenced by plot_spectrum_column().
plot_channel()
static int plot_channel (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 656 of file avf_showspectrum.c.
Referenced by plot_spectrum_column().
plot_spectrum_column()
static int plot_spectrum_column (AVFilterLink * inlink, AVFrame * insamples) static
Definition at line 718 of file avf_showspectrum.c.
Variable Documentation
showspectrum_options
const AVOption showspectrum_options[] static
Definition at line 91 of file avf_showspectrum.c.
color_table
const struct ColorTable color_table[][8] static
Referenced by ff_get_qtpalette(), pick_color(), rgtc1_block_internal(), and seq_decode_op1().