FFmpeg: libavfilter/avf_concat.c File Reference
avf_concat.c File Reference
concat audio-video filter
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/channel_layout.h"
#include "libavutil/opt.h"
#include "avfilter.h"
#include "bufferqueue.h"
#include "internal.h"
#include "video.h"
#include "audio.h"
Data Structures
struct ConcatContext
struct ConcatContext::concat_in
Macros
#define FF_BUFQUEUE_SIZE 256
#define TYPE_ALL 2
#define OFFSET(x) offsetof(ConcatContext, x)
#define A AV_OPT_FLAG_AUDIO_PARAM
#define F AV_OPT_FLAG_FILTERING_PARAM
#define V AV_OPT_FLAG_VIDEO_PARAM
Functions
AVFILTER_DEFINE_CLASS (concat)
static int query_formats (AVFilterContext *ctx)
static int config_output (AVFilterLink *outlink)
static int push_frame (AVFilterContext *ctx, unsigned in_no, AVFrame *buf)
static int process_frame (AVFilterLink *inlink, AVFrame *buf)
static AVFrame * get_video_buffer (AVFilterLink *inlink, int w, int h)
static AVFrame * get_audio_buffer (AVFilterLink *inlink, int nb_samples)
static int filter_frame (AVFilterLink *inlink, AVFrame *buf)
static void close_input (AVFilterContext *ctx, unsigned in_no)
static void find_next_delta_ts (AVFilterContext *ctx, int64_t *seg_delta)
static int send_silence (AVFilterContext *ctx, unsigned in_no, unsigned out_no, int64_t seg_delta)
static int flush_segment (AVFilterContext *ctx)
static int request_frame (AVFilterLink *outlink)
static av_cold int init (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const AVOption concat_options []
AVFilter ff_avf_concat
Detailed Description
concat audio-video filter
Definition in file avf_concat.c.
Macro Definition Documentation
FF_BUFQUEUE_SIZE
#define FF_BUFQUEUE_SIZE 256
Definition at line 31 of file avf_concat.c.
TYPE_ALL
#define TYPE_ALL 2
Definition at line 37 of file avf_concat.c.
Referenced by init(), and query_formats().
OFFSET
#define OFFSET (x) offsetof(ConcatContext, x)
Definition at line 55 of file avf_concat.c.
A
#define A AV_OPT_FLAG_AUDIO_PARAM
Definition at line 56 of file avf_concat.c.
F
#define F AV_OPT_FLAG_FILTERING_PARAM
Definition at line 57 of file avf_concat.c.
V
#define V AV_OPT_FLAG_VIDEO_PARAM
Definition at line 58 of file avf_concat.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (concat)
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 77 of file avf_concat.c.
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 122 of file avf_concat.c.
Referenced by init().
push_frame()
static int push_frame (AVFilterContext * ctx, unsigned in_no, AVFrame * buf) static
Definition at line 163 of file avf_concat.c.
Referenced by flush_segment(), and process_frame().
process_frame()
static int process_frame (AVFilterLink * inlink, AVFrame * buf) static
Definition at line 188 of file avf_concat.c.
Referenced by filter_frame().
get_video_buffer()
static AVFrame* get_video_buffer (AVFilterLink * inlink, int w, int h) static
Definition at line 206 of file avf_concat.c.
Referenced by ff_get_video_buffer(), and init().
get_audio_buffer()
static AVFrame* get_audio_buffer (AVFilterLink * inlink, int nb_samples) static
Definition at line 215 of file avf_concat.c.
Referenced by init().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * buf) static
Definition at line 224 of file avf_concat.c.
Referenced by init().
close_input()
static void close_input (AVFilterContext * ctx, unsigned in_no) static
Definition at line 229 of file avf_concat.c.
Referenced by request_frame().
find_next_delta_ts()
static void find_next_delta_ts (AVFilterContext * ctx, int64_t * seg_delta) static
Definition at line 239 of file avf_concat.c.
Referenced by flush_segment().
send_silence()
static int send_silence (AVFilterContext * ctx, unsigned in_no, unsigned out_no, int64_t seg_delta) static
Definition at line 253 of file avf_concat.c.
Referenced by flush_segment().
flush_segment()
static int flush_segment (AVFilterContext * ctx) static
Definition at line 286 of file avf_concat.c.
Referenced by request_frame().
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 323 of file avf_concat.c.
Referenced by init().
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 360 of file avf_concat.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 400 of file avf_concat.c.
Variable Documentation
concat_options
const AVOption concat_options[] static
Initial value:
= {
    { "n", "specify the number of segments", OFFSET(nb_segments),
      AV_OPT_TYPE_INT, { .i64 = 2 }, 1, INT_MAX, V|A|F},
    { "v", "specify the number of video streams",
      OFFSET(nb_streams[AVMEDIA_TYPE_VIDEO]),
      AV_OPT_TYPE_INT, { .i64 = 1 }, 0, INT_MAX, V|F },
    { "a", "specify the number of audio streams",
      OFFSET(nb_streams[AVMEDIA_TYPE_AUDIO]),
      AV_OPT_TYPE_INT, { .i64 = 0 }, 0, INT_MAX, A|F},
    { "unsafe", "enable unsafe mode",
      OFFSET(unsafe),
      AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, V|A|F},
    { NULL }
}
Definition at line 60 of file avf_concat.c.
ff_avf_concat
AVFilter ff_avf_concat
Initial value:
= {
    .name          = "concat",
    .description   = NULL_IF_CONFIG_SMALL("Concatenate audio and video streams."),
    .init          = init,
    .uninit        = uninit,
    .query_formats = query_formats,
    .priv_size     = sizeof(ConcatContext),
    .inputs        = NULL,
    .outputs       = NULL,
    .priv_class    = &concat_class,
    .flags         = AVFILTER_FLAG_DYNAMIC_INPUTS | AVFILTER_FLAG_DYNAMIC_OUTPUTS,
}
Definition at line 414 of file avf_concat.c.