FFmpeg: libavfilter/avf_showvolume.c File Reference
avf_showvolume.c File Reference
#include "libavutil/avstring.h"
#include "libavutil/channel_layout.h"
#include "libavutil/eval.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/opt.h"
#include "libavutil/parseutils.h"
#include "libavutil/xga_font_data.h"
#include "avfilter.h"
#include "formats.h"
#include "audio.h"
#include "video.h"
#include "internal.h"
Data Structures
struct ShowVolumeContext
Macros
#define OFFSET(x) offsetof(ShowVolumeContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Enumerations
enum { VAR_VOLUME, VAR_CHANNEL, VAR_PEAK, VAR_VARS_NB }
Functions
AVFILTER_DEFINE_CLASS (showvolume)
static av_cold int init (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static int config_input (AVFilterLink *inlink)
static int config_output (AVFilterLink *outlink)
static void drawtext (AVFrame *pic, int x, int y, const char *txt, int o)
static int filter_frame (AVFilterLink *inlink, AVFrame *insamples)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const char *const var_names [] = { "VOLUME", "CHANNEL", "PEAK", NULL }
static const AVOption showvolume_options []
static const AVFilterPad showvolume_inputs []
static const AVFilterPad showvolume_outputs []
AVFilter ff_avf_showvolume
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(ShowVolumeContext, x)
Definition at line 55 of file avf_showvolume.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 56 of file avf_showvolume.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
VAR_VOLUME
VAR_CHANNEL
VAR_PEAK
VAR_VARS_NB
Definition at line 35 of file avf_showvolume.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (showvolume)
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 77 of file avf_showvolume.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 92 of file avf_showvolume.c.
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 121 of file avf_showvolume.c.
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 142 of file avf_showvolume.c.
drawtext()
static void drawtext (AVFrame * pic, int x, int y, const char * txt, int o) static
Definition at line 175 of file avf_showvolume.c.
Referenced by avfilter_register_all(), filter_frame(), and plot_spectrum_column().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * insamples) static
Definition at line 209 of file avf_showvolume.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 325 of file avf_showvolume.c.
Variable Documentation
var_names
const char* const var_names[] = { "VOLUME", "CHANNEL", "PEAK", NULL } static
Definition at line 34 of file avf_showvolume.c.
Referenced by init().
showvolume_options
const AVOption showvolume_options[] static
Initial value:
= {
    { "rate", "set video rate",  OFFSET(frame_rate), AV_OPT_TYPE_VIDEO_RATE, {.str="25"}, 0, INT_MAX, FLAGS },
    { "r",    "set video rate",  OFFSET(frame_rate), AV_OPT_TYPE_VIDEO_RATE, {.str="25"}, 0, INT_MAX, FLAGS },
    { "b", "set border width",   OFFSET(b), AV_OPT_TYPE_INT, {.i64=1}, 0, 5, FLAGS },
    { "w", "set channel width",  OFFSET(w), AV_OPT_TYPE_INT, {.i64=400}, 80, 8192, FLAGS },
    { "h", "set channel height", OFFSET(h), AV_OPT_TYPE_INT, {.i64=20}, 1, 900, FLAGS },
    { "f", "set fade",           OFFSET(f), AV_OPT_TYPE_DOUBLE, {.dbl=0.95}, 0.001, 1, FLAGS },
    { "c", "set volume color expression", OFFSET(color), AV_OPT_TYPE_STRING, {.str="PEAK*255+floor((1-PEAK)*255)*256+0xff000000"}, 0, 0, FLAGS },
    { "t", "display channel names", OFFSET(draw_text), AV_OPT_TYPE_BOOL, {.i64=1}, 0, 1, FLAGS },
    { "v", "display volume value", OFFSET(draw_volume), AV_OPT_TYPE_BOOL, {.i64=1}, 0, 1, FLAGS },
    { "o", "set orientation", OFFSET(orientation), AV_OPT_TYPE_INT, {.i64=0}, 0, 1, FLAGS, "orientation" },
    {   "h", "horizontal", 0, AV_OPT_TYPE_CONST, {.i64=0}, 0, 0, FLAGS, "orientation" },
    {   "v", "vertical",   0, AV_OPT_TYPE_CONST, {.i64=1}, 0, 0, FLAGS, "orientation" },
    { "s", "set step size", OFFSET(step), AV_OPT_TYPE_INT, {.i64=0}, 0, 5, FLAGS },
    { NULL }
}
Definition at line 58 of file avf_showvolume.c.
showvolume_inputs
const AVFilterPad showvolume_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_AUDIO,
        .config_props = config_input,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 335 of file avf_showvolume.c.
showvolume_outputs
const AVFilterPad showvolume_outputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .config_props = config_output,
    },
    { NULL }
}
Definition at line 345 of file avf_showvolume.c.
ff_avf_showvolume
AVFilter ff_avf_showvolume
Initial value:
= {
    .name          = "showvolume",
    .description   = NULL_IF_CONFIG_SMALL("Convert input audio volume to video output."),
    .init          = init,
    .uninit        = uninit,
    .query_formats = query_formats,
    .priv_size     = sizeof(ShowVolumeContext),
    .inputs        = showvolume_inputs,
    .outputs       = showvolume_outputs,
    .priv_class    = &showvolume_class,
}
Definition at line 354 of file avf_showvolume.c.