FFmpeg: libavfilter/avf_showfreqs.c File Reference
avf_showfreqs.c File Reference
#include <float.h>
#include <math.h>
#include "libavcodec/avfft.h"
#include "libavutil/audio_fifo.h"
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/channel_layout.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/opt.h"
#include "libavutil/parseutils.h"
#include "audio.h"
#include "video.h"
#include "avfilter.h"
#include "internal.h"
#include "window_func.h"
Data Structures
struct ShowFreqsContext
Macros
#define OFFSET(x) offsetof(ShowFreqsContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
#define RE(x, ch) s->fft_data[ch][x].re
#define IM(x, ch) s->fft_data[ch][x].im
#define M(a, b) (sqrt((a) * (a) + (b) * (b)))
Enumerations
enum DisplayMode {
SINGLE, SEPARATE, NB_DMODES, LINE,
BAR, DOT, NB_MODES, COMBINED,
SEPARATE, NB_MODES
}
enum ChannelMode { COMBINED, SEPARATE, NB_CMODES }
enum FrequencyScale { FS_LINEAR, FS_LOG, FS_RLOG, NB_FSCALES }
enum AmplitudeScale {
ALINEAR, ALOG, NB_ASCALES, AS_LINEAR,
AS_SQRT, AS_CBRT, AS_LOG, NB_ASCALES
}
Functions
AVFILTER_DEFINE_CLASS (showfreqs)
static int query_formats (AVFilterContext *ctx)
static av_cold int init (AVFilterContext *ctx)
static int config_output (AVFilterLink *outlink)
static void draw_dot (AVFrame *out, int x, int y, uint8_t fg[4])
static int get_sx (ShowFreqsContext *s, int f)
static float get_bsize (ShowFreqsContext *s, int f)
static void plot_freq (ShowFreqsContext *s, int ch, double a, int f, uint8_t fg[4], int *prev_y, AVFrame *out, AVFilterLink *outlink)
static int plot_freqs (AVFilterLink *inlink, AVFrame *in)
static int filter_frame (AVFilterLink *inlink, AVFrame *in)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const AVOption showfreqs_options []
static const AVFilterPad showfreqs_inputs []
static const AVFilterPad showfreqs_outputs []
AVFilter ff_avf_showfreqs
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(ShowFreqsContext, x)
Definition at line 68 of file avf_showfreqs.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 69 of file avf_showfreqs.c.
RE
#define RE (x, ch) s->fft_data[ch][x].re
Referenced by plot_freqs().
IM
#define IM (x, ch) s->fft_data[ch][x].im
Referenced by plot_freqs().
M
#define M (a, b) (sqrt((a) * (a) + (b) * (b)))
Referenced by plot_freqs().
Enumeration Type Documentation
DisplayMode
enum DisplayMode
Enumerator
SINGLE
SEPARATE
NB_DMODES
LINE
BAR
DOT
NB_MODES
COMBINED
SEPARATE
NB_MODES
Definition at line 38 of file avf_showfreqs.c.
ChannelMode
enum ChannelMode
Enumerator
COMBINED
SEPARATE
NB_CMODES
Definition at line 39 of file avf_showfreqs.c.
FrequencyScale
enum FrequencyScale
Enumerator
FS_LINEAR
FS_LOG
FS_RLOG
NB_FSCALES
Definition at line 40 of file avf_showfreqs.c.
AmplitudeScale
enum AmplitudeScale
Enumerator
ALINEAR
ALOG
NB_ASCALES
AS_LINEAR
AS_SQRT
AS_CBRT
AS_LOG
NB_ASCALES
Definition at line 41 of file avf_showfreqs.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (showfreqs)
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 133 of file avf_showfreqs.c.
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 164 of file avf_showfreqs.c.
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 173 of file avf_showfreqs.c.
draw_dot()
static void draw_dot (AVFrame * out, int x, int y, uint8_t fg[4]) inline static
Definition at line 245 of file avf_showfreqs.c.
Referenced by plot_freq().
get_sx()
static int get_sx (ShowFreqsContext * s, int f) static
Definition at line 256 of file avf_showfreqs.c.
Referenced by plot_freq().
get_bsize()
static float get_bsize (ShowFreqsContext * s, int f) static
Definition at line 270 of file avf_showfreqs.c.
Referenced by plot_freq().
plot_freq()
static void plot_freq (ShowFreqsContext * s, int ch, double a, int f, uint8_t fg[4], int * prev_y, AVFrame * out, AVFilterLink * outlink) inline static
Definition at line 286 of file avf_showfreqs.c.
Referenced by plot_freqs().
plot_freqs()
static int plot_freqs (AVFilterLink * inlink, AVFrame * in) static
Definition at line 369 of file avf_showfreqs.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 440 of file avf_showfreqs.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 479 of file avf_showfreqs.c.
Variable Documentation
showfreqs_options
const AVOption showfreqs_options[] static
Definition at line 71 of file avf_showfreqs.c.
showfreqs_inputs
const AVFilterPad showfreqs_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_AUDIO,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 497 of file avf_showfreqs.c.
showfreqs_outputs
const AVFilterPad showfreqs_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .config_props  = config_output,
    },
    { NULL }
}
Definition at line 506 of file avf_showfreqs.c.
ff_avf_showfreqs
AVFilter ff_avf_showfreqs
Initial value:
= {
    .name          = "showfreqs",
    .description   = NULL_IF_CONFIG_SMALL("Convert input audio to a frequencies video output."),
    .init          = init,
    .uninit        = uninit,
    .query_formats = query_formats,
    .priv_size     = sizeof(ShowFreqsContext),
    .inputs        = showfreqs_inputs,
    .outputs       = showfreqs_outputs,
    .priv_class    = &showfreqs_class,
}
Definition at line 515 of file avf_showfreqs.c.