FFmpeg: libavfilter/avf_showwaves.c File Reference
avf_showwaves.c File Reference
audio to video multimedia filter
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/channel_layout.h"
#include "libavutil/opt.h"
#include "libavutil/parseutils.h"
#include "avfilter.h"
#include "formats.h"
#include "audio.h"
#include "video.h"
#include "internal.h"
Data Structures
struct frame_node
struct ShowWavesContext
Macros
#define OFFSET(x) offsetof(ShowWavesContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Enumerations
enum ShowWavesMode {
MODE_POINT, MODE_LINE, MODE_P2P, MODE_CENTERED_LINE,
MODE_NB
}
enum ShowWavesScale {
SCALE_LIN, SCALE_LOG, SCALE_SQRT, SCALE_CBRT,
SCALE_NB
}
Functions
AVFILTER_DEFINE_CLASS (showwaves)
static av_cold void uninit (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static int get_lin_h (int16_t sample, int height)
static int get_lin_h2 (int16_t sample, int height)
static int get_log_h (int16_t sample, int height)
static int get_log_h2 (int16_t sample, int height)
static int get_sqrt_h (int16_t sample, int height)
static int get_sqrt_h2 (int16_t sample, int height)
static int get_cbrt_h (int16_t sample, int height)
static int get_cbrt_h2 (int16_t sample, int height)
static void draw_sample_point_rgba (uint8_t *buf, int height, int linesize, int16_t *prev_y, const uint8_t color[4], int h)
static void draw_sample_line_rgba (uint8_t *buf, int height, int linesize, int16_t *prev_y, const uint8_t color[4], int h)
static void draw_sample_p2p_rgba (uint8_t *buf, int height, int linesize, int16_t *prev_y, const uint8_t color[4], int h)
static void draw_sample_cline_rgba (uint8_t *buf, int height, int linesize, int16_t *prev_y, const uint8_t color[4], int h)
static void draw_sample_point_gray (uint8_t *buf, int height, int linesize, int16_t *prev_y, const uint8_t color[4], int h)
static void draw_sample_line_gray (uint8_t *buf, int height, int linesize, int16_t *prev_y, const uint8_t color[4], int h)
static void draw_sample_p2p_gray (uint8_t *buf, int height, int linesize, int16_t *prev_y, const uint8_t color[4], int h)
static void draw_sample_cline_gray (uint8_t *buf, int height, int linesize, int16_t *prev_y, const uint8_t color[4], int h)
static int config_output (AVFilterLink *outlink)
static int push_frame (AVFilterLink *outlink)
static int push_single_pic (AVFilterLink *outlink)
static int request_frame (AVFilterLink *outlink)
static int alloc_out_frame (ShowWavesContext *showwaves, const int16_t *p, const AVFilterLink *inlink, AVFilterLink *outlink, const AVFrame *in)
static av_cold int init (AVFilterContext *ctx)
Variables
static const AVOption showwaves_options []
Detailed Description
audio to video multimedia filter
Definition in file avf_showwaves.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(ShowWavesContext, x)
Definition at line 86 of file avf_showwaves.c.
Referenced by init().
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 87 of file avf_showwaves.c.
Referenced by init().
Enumeration Type Documentation
ShowWavesMode
enum ShowWavesMode
Enumerator
MODE_POINT
MODE_LINE
MODE_P2P
MODE_CENTERED_LINE
MODE_NB
Definition at line 37 of file avf_showwaves.c.
ShowWavesScale
enum ShowWavesScale
Enumerator
SCALE_LIN
SCALE_LOG
SCALE_SQRT
SCALE_CBRT
SCALE_NB
Definition at line 45 of file avf_showwaves.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (showwaves)
Referenced by init().
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 112 of file avf_showwaves.c.
Referenced by init().
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 134 of file avf_showwaves.c.
Referenced by init().
get_lin_h()
static int get_lin_h (int16_t sample, int height) static
Definition at line 165 of file avf_showwaves.c.
Referenced by config_output().
get_lin_h2()
static int get_lin_h2 (int16_t sample, int height) static
Definition at line 170 of file avf_showwaves.c.
Referenced by config_output().
get_log_h()
static int get_log_h (int16_t sample, int height) static
Definition at line 175 of file avf_showwaves.c.
Referenced by config_output().
get_log_h2()
static int get_log_h2 (int16_t sample, int height) static
Definition at line 180 of file avf_showwaves.c.
Referenced by config_output().
get_sqrt_h()
static int get_sqrt_h (int16_t sample, int height) static
Definition at line 185 of file avf_showwaves.c.
Referenced by config_output().
get_sqrt_h2()
static int get_sqrt_h2 (int16_t sample, int height) static
Definition at line 190 of file avf_showwaves.c.
Referenced by config_output().
get_cbrt_h()
static int get_cbrt_h (int16_t sample, int height) static
Definition at line 195 of file avf_showwaves.c.
Referenced by config_output().
get_cbrt_h2()
static int get_cbrt_h2 (int16_t sample, int height) static
Definition at line 200 of file avf_showwaves.c.
Referenced by config_output().
draw_sample_point_rgba()
static void draw_sample_point_rgba (uint8_t * buf, int height, int linesize, int16_t * prev_y, const uint8_t color[4], int h) static
Definition at line 205 of file avf_showwaves.c.
Referenced by config_output().
draw_sample_line_rgba()
static void draw_sample_line_rgba (uint8_t * buf, int height, int linesize, int16_t * prev_y, const uint8_t color[4], int h) static
Definition at line 217 of file avf_showwaves.c.
Referenced by config_output().
draw_sample_p2p_rgba()
static void draw_sample_p2p_rgba (uint8_t * buf, int height, int linesize, int16_t * prev_y, const uint8_t color[4], int h) static
Definition at line 234 of file avf_showwaves.c.
Referenced by config_output().
draw_sample_cline_rgba()
static void draw_sample_cline_rgba (uint8_t * buf, int height, int linesize, int16_t * prev_y, const uint8_t color[4], int h) static
Definition at line 260 of file avf_showwaves.c.
Referenced by config_output().
draw_sample_point_gray()
static void draw_sample_point_gray (uint8_t * buf, int height, int linesize, int16_t * prev_y, const uint8_t color[4], int h) static
Definition at line 275 of file avf_showwaves.c.
Referenced by config_output().
draw_sample_line_gray()
static void draw_sample_line_gray (uint8_t * buf, int height, int linesize, int16_t * prev_y, const uint8_t color[4], int h) static
Definition at line 283 of file avf_showwaves.c.
Referenced by config_output().
draw_sample_p2p_gray()
static void draw_sample_p2p_gray (uint8_t * buf, int height, int linesize, int16_t * prev_y, const uint8_t color[4], int h) static
Definition at line 296 of file avf_showwaves.c.
Referenced by config_output().
draw_sample_cline_gray()
static void draw_sample_cline_gray (uint8_t * buf, int height, int linesize, int16_t * prev_y, const uint8_t color[4], int h) static
Definition at line 315 of file avf_showwaves.c.
Referenced by config_output().
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 326 of file avf_showwaves.c.
Referenced by init().
push_frame()
static int push_frame (AVFilterLink * outlink) inline static
Definition at line 458 of file avf_showwaves.c.
Referenced by init(), push_single_pic(), and request_frame().
push_single_pic()
static int push_single_pic (AVFilterLink * outlink) static
Definition at line 474 of file avf_showwaves.c.
Referenced by request_frame().
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 531 of file avf_showwaves.c.
Referenced by init().
alloc_out_frame()
static int alloc_out_frame (ShowWavesContext * showwaves, const int16_t * p, const AVFilterLink * inlink, AVFilterLink * outlink, const AVFrame * in) static
Definition at line 548 of file avf_showwaves.c.
Referenced by init().
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 569 of file avf_showwaves.c.
Variable Documentation
showwaves_options
const AVOption showwaves_options[] static
Initial value:
= {
    { "size", "set video size", OFFSET(w), AV_OPT_TYPE_IMAGE_SIZE, {.str = "600x240"}, 0, 0, FLAGS },
    { "s",    "set video size", OFFSET(w), AV_OPT_TYPE_IMAGE_SIZE, {.str = "600x240"}, 0, 0, FLAGS },
    { "mode", "select display mode", OFFSET(mode), AV_OPT_TYPE_INT, {.i64=MODE_POINT}, 0, MODE_NB-1, FLAGS, "mode"},
        { "point", "draw a point for each sample",         0, AV_OPT_TYPE_CONST, {.i64=MODE_POINT},         .flags=FLAGS, .unit="mode"},
        { "line",  "draw a line for each sample",          0, AV_OPT_TYPE_CONST, {.i64=MODE_LINE},          .flags=FLAGS, .unit="mode"},
        { "p2p",   "draw a line between samples",          0, AV_OPT_TYPE_CONST, {.i64=MODE_P2P},           .flags=FLAGS, .unit="mode"},
        { "cline", "draw a centered line for each sample", 0, AV_OPT_TYPE_CONST, {.i64=MODE_CENTERED_LINE}, .flags=FLAGS, .unit="mode"},
    { "n",    "set how many samples to show in the same point", OFFSET(n), AV_OPT_TYPE_INT, {.i64 = 0}, 0, INT_MAX, FLAGS },
    { "rate", "set video rate", OFFSET(rate), AV_OPT_TYPE_VIDEO_RATE, {.str = "25"}, 0, INT_MAX, FLAGS },
    { "r",    "set video rate", OFFSET(rate), AV_OPT_TYPE_VIDEO_RATE, {.str = "25"}, 0, INT_MAX, FLAGS },
    { "split_channels", "draw channels separately", OFFSET(split_channels), AV_OPT_TYPE_BOOL, {.i64 = 0}, 0, 1, FLAGS },
    { "colors", "set channels colors", OFFSET(colors), AV_OPT_TYPE_STRING, {.str = "red|green|blue|yellow|orange|lime|pink|magenta|brown" }, 0, 0, FLAGS },
    { "scale", "set amplitude scale", OFFSET(scale), AV_OPT_TYPE_INT, {.i64 = 0 }, 0, SCALE_NB-1, FLAGS, .unit="scale" },
        { "lin", "linear",         0, AV_OPT_TYPE_CONST, {.i64=SCALE_LIN}, .flags=FLAGS, .unit="scale"},
        { "log", "logarithmic",    0, AV_OPT_TYPE_CONST, {.i64=SCALE_LOG}, .flags=FLAGS, .unit="scale"},
        { "sqrt", "square root",   0, AV_OPT_TYPE_CONST, {.i64=SCALE_SQRT}, .flags=FLAGS, .unit="scale"},
        { "cbrt", "cubic root",    0, AV_OPT_TYPE_CONST, {.i64=SCALE_CBRT}, .flags=FLAGS, .unit="scale"},
    { NULL }
}
Definition at line 89 of file avf_showwaves.c.