FFmpeg: libavfilter/avfilter.c File Reference
avfilter.c File Reference
#include "libavutil/atomic.h"
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/buffer.h"
#include "libavutil/channel_layout.h"
#include "libavutil/common.h"
#include "libavutil/eval.h"
#include "libavutil/hwcontext.h"
#include "libavutil/imgutils.h"
#include "libavutil/internal.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "libavutil/rational.h"
#include "libavutil/samplefmt.h"
#include "framequeue.h"
#include "audio.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
#include "libavutil/ffversion.h"
Macros
#define FF_INTERNAL_FIELDS 1
#define LICENSE_PREFIX "libavfilter license: "
#define OFFSET(x) offsetof(AVFilterContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM
#define FFERROR_NOT_READY FFERRTAG('N','R','D','Y')
Enumerations
enum {
VAR_T, VAR_N, VAR_POS, VAR_W,
VAR_H, VAR_VARS_NB
}
Functions
static int ff_filter_frame_framed (AVFilterLink *link, AVFrame *frame)
void ff_tlog_ref (void *ctx, AVFrame *ref, int end)
unsigned avfilter_version (void)
Return the LIBAVFILTER_VERSION_INT constant.
const char * avfilter_configuration (void)
Return the libavfilter build-time configuration.
const char * avfilter_license (void)
Return the libavfilter license.
void ff_command_queue_pop (AVFilterContext *filter)
int ff_insert_pad (unsigned idx, unsigned *count, size_t padidx_off, AVFilterPad **pads, AVFilterLink ***links, AVFilterPad *newpad)
Insert a new pad.
int avfilter_link (AVFilterContext *src, unsigned srcpad, AVFilterContext *dst, unsigned dstpad)
Link two filters together.
void avfilter_link_free (AVFilterLink **link)
Free the link in *link, and set its pointer to NULL.
int avfilter_link_get_channels (AVFilterLink *link)
Get the number of channels of a link.
static void ff_filter_set_ready (AVFilterContext *filter, unsigned priority)
static void filter_unblock (AVFilterContext *filter)
Clear frame_blocked_in on all outputs.
void ff_avfilter_link_set_in_status (AVFilterLink *link, int status, int64_t pts)
Set the status field of a link from the source filter.
void ff_avfilter_link_set_out_status (AVFilterLink *link, int status, int64_t pts)
Set the status field of a link from the destination filter.
void avfilter_link_set_closed (AVFilterLink *link, int closed)
Set the closed field of a link.
int avfilter_insert_filter (AVFilterLink *link, AVFilterContext *filt, unsigned filt_srcpad_idx, unsigned filt_dstpad_idx)
Insert a filter in the middle of an existing link.
int avfilter_config_links (AVFilterContext *filter)
Negotiate the media format, dimensions, etc of all inputs to a filter.
void ff_tlog_link (void *ctx, AVFilterLink *link, int end)
int ff_request_frame (AVFilterLink *link)
Request an input frame from the filter at the other end of the link.
int ff_request_frame_to_filter (AVFilterLink *link)
int ff_poll_frame (AVFilterLink *link)
Poll a frame from the filter chain.
static int set_enable_expr (AVFilterContext *ctx, const char *expr)
void ff_update_link_current_pts (AVFilterLink *link, int64_t pts)
int avfilter_process_command (AVFilterContext *filter, const char *cmd, const char *arg, char *res, int res_len, int flags)
Make the filter instance process a command.
AVFilter * avfilter_get_by_name (const char *name)
Get a filter definition matching the given name.
int avfilter_register (AVFilter *filter)
Register a filter.
const AVFilter * avfilter_next (const AVFilter *prev)
Iterate over all registered filters.
AVFilter ** av_filter_next (AVFilter **filter)
void avfilter_uninit (void)
int avfilter_pad_count (const AVFilterPad *pads)
Get the number of elements in a NULL-terminated array of AVFilterPads (e.g.
static const char * default_filter_name (void *filter_ctx)
static void * filter_child_next (void *obj, void *prev)
static const AVClass * filter_child_class_next (const AVClass *prev)
static int default_execute (AVFilterContext *ctx, avfilter_action_func *func, void *arg, int *ret, int nb_jobs)
AVFilterContext * ff_filter_alloc (const AVFilter *filter, const char *inst_name)
Allocate a new filter context and return it.
int avfilter_open (AVFilterContext **filter_ctx, AVFilter *filter, const char *inst_name)
static void free_link (AVFilterLink *link)
void avfilter_free (AVFilterContext *filter)
Free a filter context.
int ff_filter_get_nb_threads (AVFilterContext *ctx)
Get number of threads for current filter instance.
static int process_options (AVFilterContext *ctx, AVDictionary **options, const char *args)
int avfilter_init_filter (AVFilterContext *filter, const char *args, void *opaque)
int avfilter_init_dict (AVFilterContext *ctx, AVDictionary **options)
Initialize a filter with the supplied dictionary of options.
int avfilter_init_str (AVFilterContext *filter, const char *args)
Initialize a filter with the supplied parameters.
const char * avfilter_pad_get_name (const AVFilterPad *pads, int pad_idx)
Get the name of an AVFilterPad.
enum AVMediaType avfilter_pad_get_type (const AVFilterPad *pads, int pad_idx)
Get the type of an AVFilterPad.
static int default_filter_frame (AVFilterLink *link, AVFrame *frame)
int ff_filter_frame (AVFilterLink *link, AVFrame *frame)
Send a frame of data to the next filter.
static int samples_ready (AVFilterLink *link)
static int take_samples (AVFilterLink *link, unsigned min, unsigned max, AVFrame **rframe)
int ff_filter_frame_to_filter (AVFilterLink *link)
static int forward_status_change (AVFilterContext *filter, AVFilterLink *in)
static int ff_filter_activate_default (AVFilterContext *filter)
int ff_filter_activate (AVFilterContext *filter)
const AVClass * avfilter_get_class (void)
Variables
const char av_filter_ffversion [] = "FFmpeg version " FFMPEG_VERSION
static const char *const var_names []
static AVFilter * first_filter
static AVFilter ** last_filter = &first_filter
static const AVOption avfilter_options []
static const AVClass avfilter_class
Macro Definition Documentation
FF_INTERNAL_FIELDS
#define FF_INTERNAL_FIELDS 1
Definition at line 37 of file avfilter.c.
LICENSE_PREFIX
#define LICENSE_PREFIX "libavfilter license: "
Referenced by avfilter_license().
OFFSET
#define OFFSET (x) offsetof(AVFilterContext, x)
Definition at line 659 of file avfilter.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM
Definition at line 660 of file avfilter.c.
FFERROR_NOT_READY
#define FFERROR_NOT_READY FFERRTAG('N','R','D','Y')
Definition at line 1374 of file avfilter.c.
Referenced by ff_filter_activate(), and ff_filter_activate_default().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
VAR_T
VAR_N
VAR_POS
VAR_W
VAR_H
VAR_VARS_NB
Definition at line 479 of file avfilter.c.
Function Documentation
ff_filter_frame_framed()
static int ff_filter_frame_framed (AVFilterLink * link, AVFrame * frame) static
Definition at line 1096 of file avfilter.c.
Referenced by ff_filter_frame_to_filter().
ff_tlog_ref()
void ff_tlog_ref (void * ctx, AVFrame * ref, int end)
Definition at line 50 of file avfilter.c.
Referenced by ff_filter_frame().
ff_command_queue_pop()
void ff_command_queue_pop (AVFilterContext * filter)
Definition at line 95 of file avfilter.c.
Referenced by avfilter_free(), and ff_filter_frame_framed().
ff_insert_pad()
int ff_insert_pad (unsigned idx, unsigned * count, size_t padidx_off, AVFilterPad ** pads, AVFilterLink *** links, AVFilterPad * newpad)
Insert a new pad.
Parameters
idx Insertion point. Pad is inserted at the end if this point is beyond the end of the list of pads.
count Pointer to the number of pads in the list
padidx_off Offset within an AVFilterLink structure to the element to increment when inserting a new pad causes link numbering to change
pads Pointer to the pointer to the beginning of the list of pads
links Pointer to the pointer to the beginning of the list of links
newpad The new pad to add. A copy is made when adding.
Returns
>= 0 in case of success, a negative AVERROR code on error
Definition at line 104 of file avfilter.c.
Referenced by ff_insert_inpad(), and ff_insert_outpad().
ff_filter_set_ready()
static void ff_filter_set_ready (AVFilterContext * filter, unsigned priority) static
Definition at line 192 of file avfilter.c.
Referenced by ff_avfilter_link_set_in_status(), ff_avfilter_link_set_out_status(), ff_filter_frame(), ff_filter_frame_to_filter(), ff_request_frame(), and forward_status_change().
filter_unblock()
static void filter_unblock (AVFilterContext * filter) static
Clear frame_blocked_in on all outputs.
This is necessary whenever something changes on input.
Definition at line 201 of file avfilter.c.
Referenced by ff_avfilter_link_set_in_status(), ff_avfilter_link_set_out_status(), ff_filter_frame(), and ff_filter_frame_to_filter().
ff_avfilter_link_set_in_status()
void ff_avfilter_link_set_in_status (AVFilterLink * link, int status, int64_t pts)
Set the status field of a link from the source filter.
The pts should reflect the timestamp of the status change, in link time base and relative to the frames timeline. In particular, for AVERROR_EOF, it should reflect the end time of the last frame.
Definition at line 210 of file avfilter.c.
Referenced by av_buffersrc_add_frame_internal(), and ff_request_frame_to_filter().
ff_avfilter_link_set_out_status()
void ff_avfilter_link_set_out_status (AVFilterLink * link, int status, int64_t pts)
Set the status field of a link from the destination filter.
The pts should probably be left unset (AV_NOPTS_VALUE).
Definition at line 223 of file avfilter.c.
Referenced by avfilter_link_set_closed(), ff_filter_frame_to_filter(), ff_request_frame(), and forward_status_change().
ff_tlog_link()
void ff_tlog_link (void * ctx, AVFilterLink * link, int end)
Definition at line 384 of file avfilter.c.
Referenced by ff_filter_frame(), ff_get_video_buffer(), ff_request_frame(), and ff_request_frame_to_filter().
ff_request_frame()
int ff_request_frame (AVFilterLink * link)
Request an input frame from the filter at the other end of the link.
The input filter may pass the request on to its inputs, fulfill the request from an internal buffer or any other means specific to its function.
When the end of a stream is reached AVERROR_EOF is returned and no further frames are returned after that.
When a filter is unable to output a frame for example due to its sources being unable to do so or because it depends on external means pushing data into it then AVERROR(EAGAIN) is returned. It is important that a AVERROR(EAGAIN) return is returned all the way to the caller (generally eventually a user application) as this step may (but does not have to be) necessary to provide the input with the next frame.
If a request is successful then some progress has been made towards providing a frame on the link (through ff_filter_frame()). A filter that needs several frames to produce one is allowed to return success if one more frame has been processed but no output has been produced yet. A filter is also allowed to simply forward a success return value.
Parameters
link the input link
Returns
zero on success AVERROR_EOF on end of file AVERROR(EAGAIN) if the previous filter cannot output a frame currently and can neither guarantee that EOF has been reached.
Definition at line 408 of file avfilter.c.
Referenced by av_buffersink_get_frame_flags(), avfilter_graph_request_oldest(), compressor(), config_output(), ff_framesync_request_frame(), ff_insert_outpad(), ff_request_frame_to_filter(), filter_frame(), gate(), join_request_frame(), plot_spectrum_column(), request_frame(), request_frame_ref(), request_inlink(), request_samples(), and return_audio_frame().
ff_request_frame_to_filter()
int ff_request_frame_to_filter (AVFilterLink * link)
Definition at line 432 of file avfilter.c.
Referenced by ff_filter_activate_default(), ff_insert_outpad(), and forward_status_change().
ff_poll_frame()
int ff_poll_frame (AVFilterLink * link)
Poll a frame from the filter chain.
Parameters
link the input link
Returns
the number of immediately available frames, a negative number in case of error
Definition at line 452 of file avfilter.c.
Referenced by ff_insert_outpad(), and ff_poll_frame().
set_enable_expr()
static int set_enable_expr (AVFilterContext * ctx, const char * expr) static
Definition at line 488 of file avfilter.c.
Referenced by avfilter_process_command(), and process_options().
ff_update_link_current_pts()
void ff_update_link_current_pts (AVFilterLink * link, int64_t pts)
Definition at line 528 of file avfilter.c.
Referenced by ff_avfilter_link_set_out_status(), and ff_filter_frame_framed().
av_filter_next()
AVFilter** av_filter_next (AVFilter ** filter)
Definition at line 602 of file avfilter.c.
avfilter_uninit()
void avfilter_uninit (void)
Definition at line 607 of file avfilter.c.
default_filter_name()
static const char* default_filter_name (void * filter_ctx) static
Definition at line 624 of file avfilter.c.
filter_child_next()
static void* filter_child_next (void * obj, void * prev) static
Definition at line 630 of file avfilter.c.
filter_child_class_next()
static const AVClass* filter_child_class_next (const AVClass * prev) static
Definition at line 638 of file avfilter.c.
default_execute()
static int default_execute (AVFilterContext * ctx, avfilter_action_func * func, void * arg, int * ret, int nb_jobs) static
Definition at line 681 of file avfilter.c.
Referenced by ff_filter_alloc().
ff_filter_alloc()
AVFilterContext* ff_filter_alloc (const AVFilter * filter, const char * inst_name)
Allocate a new filter context and return it.
Parameters
filter what filter to create an instance of
inst_name name to give to the new filter context
Returns
newly created filter context or NULL on failure
Definition at line 694 of file avfilter.c.
Referenced by avfilter_graph_alloc_filter(), and avfilter_open().
avfilter_open()
int avfilter_open (AVFilterContext ** filter_ctx, AVFilter * filter, const char * inst_name)
Definition at line 763 of file avfilter.c.
free_link()
static void free_link (AVFilterLink * link) static
Definition at line 770 of file avfilter.c.
Referenced by avfilter_free().
ff_filter_get_nb_threads()
int ff_filter_get_nb_threads (AVFilterContext * ctx)
Get number of threads for current filter instance.
This number is always same or less than graph->nb_threads.
Definition at line 833 of file avfilter.c.
Referenced by apply_lut(), averageiir2d(), blend_frame(), config_input(), config_props(), ff_norm_qscale(), filter(), filter_frame(), filter_frame16(), filter_frame8(), gaussianiir2d(), and nlmeans_plane().
process_options()
static int process_options (AVFilterContext * ctx, AVDictionary ** options, const char * args) static
Definition at line 840 of file avfilter.c.
Referenced by avfilter_init_str().
avfilter_init_filter()
int avfilter_init_filter (AVFilterContext * filter, const char * args, void * opaque)
Definition at line 919 of file avfilter.c.
default_filter_frame()
static int default_filter_frame (AVFilterLink * link, AVFrame * frame) static
Definition at line 1091 of file avfilter.c.
Referenced by ff_filter_frame_framed().
ff_filter_frame()
int ff_filter_frame (AVFilterLink * link, AVFrame * frame)
Send a frame of data to the next filter.
Parameters
link the output link over which the data is being sent
frame a reference to the buffer of data being sent. The receiving filter will free this reference when it no longer needs it or pass it on to the next filter.
Returns
>= 0 on success, a negative AVERROR on error. The receiving filter is responsible for unreferencing frame in case of error.
Definition at line 1187 of file avfilter.c.
Referenced by apply_filter(), channelmap_filter_frame(), compand_delay(), compand_drain(), compand_nodelay(), compressor(), config_output(), cudaupload_filter_frame(), default_filter_frame(), end_last_frame(), filter(), filter_frame(), filter_frame16(), filter_frame8(), filter_frame_ref(), flush(), gate(), geq_filter_frame(), hwdownload_filter_frame(), hwupload_filter_frame(), movie_push_frame(), nppscale_filter_frame(), output_frame(), output_single_frame(), plot_freqs(), plot_spectrum_column(), pp_filter_frame(), process_frame(), process_work_frame(), push_frame(), push_samples(), request_frame(), return_audio_frame(), return_frame(), scale_vaapi_filter_frame(), send_silence(), shuffleplanes_filter_frame(), source_request_frame(), and try_push_frame().
samples_ready()
static int samples_ready (AVFilterLink * link) static
Definition at line 1238 of file avfilter.c.
Referenced by ff_filter_activate_default(), and take_samples().
take_samples()
static int take_samples (AVFilterLink * link, unsigned min, unsigned max, AVFrame ** rframe) static
Definition at line 1245 of file avfilter.c.
Referenced by ff_filter_frame_to_filter().
ff_filter_frame_to_filter()
int ff_filter_frame_to_filter (AVFilterLink * link)
Definition at line 1311 of file avfilter.c.
Referenced by ff_filter_activate_default(), and ff_insert_outpad().
forward_status_change()
static int forward_status_change (AVFilterContext * filter, AVFilterLink * in) static
Definition at line 1342 of file avfilter.c.
Referenced by ff_filter_activate_default().
ff_filter_activate_default()
static int ff_filter_activate_default (AVFilterContext * filter) static
Definition at line 1376 of file avfilter.c.
Referenced by ff_filter_activate().
ff_filter_activate()
int ff_filter_activate (AVFilterContext * filter)
Definition at line 1535 of file avfilter.c.
Referenced by ff_filter_graph_run_once().
Variable Documentation
av_filter_ffversion
const char av_filter_ffversion[] = "FFmpeg version " FFMPEG_VERSION
Definition at line 46 of file avfilter.c.
var_names
const char* const var_names[] static
Initial value:
= {
    "t",
    "n",
    "pos",
    "w",
    "h",
    NULL
}
Definition at line 470 of file avfilter.c.
Referenced by set_enable_expr().
first_filter
AVFilter* first_filter static
Definition at line 560 of file avfilter.c.
Referenced by av_filter_next(), and avfilter_next().
last_filter
AVFilter** last_filter = &first_filter static
Definition at line 561 of file avfilter.c.
Referenced by avfilter_register(), configure_input_audio_filter(), configure_input_video_filter(), configure_output_audio_filter(), configure_output_video_filter(), and get_video_frame().
avfilter_options
const AVOption avfilter_options[] static
Initial value:
= {
    { "thread_type", "Allowed thread types", OFFSET(thread_type), AV_OPT_TYPE_FLAGS,
        { .i64 = AVFILTER_THREAD_SLICE }, 0, INT_MAX, FLAGS, "thread_type" },
        { "slice", NULL, 0, AV_OPT_TYPE_CONST, { .i64 = AVFILTER_THREAD_SLICE }, .unit = "thread_type" },
    { "enable", "set enable expression", OFFSET(enable_str), AV_OPT_TYPE_STRING, {.str=NULL}, .flags = FLAGS },
    { "threads", "Allowed number of threads", OFFSET(nb_threads), AV_OPT_TYPE_INT,
        { .i64 = 0 }, 0, INT_MAX, FLAGS },
    { NULL },
}
Definition at line 661 of file avfilter.c.
avfilter_class
const AVClass avfilter_class static
Initial value:
= {
    .class_name = "AVFilter",
    .item_name  = default_filter_name,
    .version    = LIBAVUTIL_VERSION_INT,
    .category   = AV_CLASS_CATEGORY_FILTER,
    .child_next = filter_child_next,
    .child_class_next = filter_child_class_next,
    .option           = avfilter_options,
}
Definition at line 671 of file avfilter.c.
Referenced by avfilter_get_class(), and ff_filter_alloc().