FFmpeg: libavformat/avidec.c File Reference
avidec.c File Reference
#include <inttypes.h>
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/bswap.h"
#include "libavutil/opt.h"
#include "libavutil/dict.h"
#include "libavutil/internal.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/mathematics.h"
#include "avformat.h"
#include "avi.h"
#include "dv.h"
#include "internal.h"
#include "isom.h"
#include "riff.h"
#include "libavcodec/bytestream.h"
#include "libavcodec/exif.h"
#include "libavcodec/internal.h"
Data Structures
struct AVIStream
struct AVIContext
Macros
#define MAX_ODML_DEPTH 1000
#define print_tag(str, tag, size)
Functions
static int avi_load_index (AVFormatContext *s)
static int guess_ni_flag (AVFormatContext *s)
static int get_duration (AVIStream *ast, int len)
static int get_riff (AVFormatContext *s, AVIOContext *pb)
static int read_braindead_odml_indx (AVFormatContext *s, int frame_num)
static void clean_index (AVFormatContext *s)
static int avi_read_tag (AVFormatContext *s, AVStream *st, uint32_t tag, uint32_t size)
static void avi_metadata_creation_time (AVDictionary **metadata, char *date)
static void avi_read_nikon (AVFormatContext *s, uint64_t end)
static int avi_extract_stream_metadata (AVFormatContext *s, AVStream *st)
static int calculate_bitrate (AVFormatContext *s)
static int avi_read_header (AVFormatContext *s)
static int read_gab2_sub (AVFormatContext *s, AVStream *st, AVPacket *pkt)
static AVStream * get_subtitle_pkt (AVFormatContext *s, AVStream *next_st, AVPacket *pkt)
static int get_stream_idx (const unsigned *d)
static int avi_sync (AVFormatContext *s, int exit_early)
static int ni_prepare_read (AVFormatContext *s)
static int avi_read_packet (AVFormatContext *s, AVPacket *pkt)
static int avi_read_idx1 (AVFormatContext *s, int size)
static int check_stream_max_drift (AVFormatContext *s)
static void seek_subtitle (AVStream *st, AVStream *st2, int64_t timestamp)
static int avi_read_seek (AVFormatContext *s, int stream_index, int64_t timestamp, int flags)
static int avi_read_close (AVFormatContext *s)
static int avi_probe (AVProbeData *p)
Variables
static const AVOption options []
static const AVClass demuxer_class
static const char avi_headers [][8]
static const AVMetadataConv avi_metadata_conv []
static const char months [12][4]
AVInputFormat ff_avi_demuxer
Macro Definition Documentation
MAX_ODML_DEPTH
#define MAX_ODML_DEPTH 1000
Definition at line 84 of file avidec.c.
Referenced by read_braindead_odml_indx().
print_tag
#define print_tag (str, tag, size)
Value:
av_log(NULL, AV_LOG_TRACE, "pos:%"PRIX64" %s: tag=%c%c%c%c size=0x%x\n", \
            avio_tell(pb), str, tag & 0xff,              \
            (tag >> 8) & 0xff,                           \
            (tag >> 16) & 0xff,                          \
            (tag >> 24) & 0xff,                          \
            size)
Definition at line 120 of file avidec.c.
Referenced by avi_read_header().
Function Documentation
avi_load_index()
static int avi_load_index (AVFormatContext * s) static
Definition at line 1744 of file avidec.c.
Referenced by avi_read_header(), and avi_read_seek().
guess_ni_flag()
static int guess_ni_flag (AVFormatContext * s) static
Definition at line 1702 of file avidec.c.
Referenced by avi_read_header().
get_duration()
static int get_duration (AVIStream * ast, int len) inline static
Definition at line 128 of file avidec.c.
Referenced by avi_read_idx1(), avi_read_packet(), avi_sync(), and read_braindead_odml_indx().
get_riff()
static int get_riff (AVFormatContext * s, AVIOContext * pb) static
Definition at line 138 of file avidec.c.
Referenced by avi_read_header().
read_braindead_odml_indx()
static int read_braindead_odml_indx (AVFormatContext * s, int frame_num) static
Definition at line 163 of file avidec.c.
Referenced by avi_read_header().
clean_index()
static void clean_index (AVFormatContext * s) static
Definition at line 271 of file avidec.c.
Referenced by avi_read_header().
avi_read_tag()
static int avi_read_tag (AVFormatContext * s, AVStream * st, uint32_t tag, uint32_t size) static
Definition at line 299 of file avidec.c.
Referenced by avi_read_header().
avi_metadata_creation_time()
static void avi_metadata_creation_time (AVDictionary ** metadata, char * date) static
Definition at line 326 of file avidec.c.
Referenced by avi_read_header().
avi_read_nikon()
static void avi_read_nikon (AVFormatContext * s, uint64_t end) static
Definition at line 345 of file avidec.c.
Referenced by avi_read_header().
avi_extract_stream_metadata()
static int avi_extract_stream_metadata (AVFormatContext * s, AVStream * st) static
Definition at line 388 of file avidec.c.
Referenced by avi_read_header().
calculate_bitrate()
static int calculate_bitrate (AVFormatContext * s) static
Definition at line 426 of file avidec.c.
Referenced by avi_read_header().
avi_read_header()
static int avi_read_header (AVFormatContext * s) static
Definition at line 470 of file avidec.c.
read_gab2_sub()
static int read_gab2_sub (AVFormatContext * s, AVStream * st, AVPacket * pkt) static
Definition at line 1070 of file avidec.c.
Referenced by avi_read_packet().
get_subtitle_pkt()
static AVStream* get_subtitle_pkt (AVFormatContext * s, AVStream * next_st, AVPacket * pkt) static
Definition at line 1136 of file avidec.c.
Referenced by avi_read_packet().
get_stream_idx()
static int get_stream_idx (const unsigned * d) static
Definition at line 1170 of file avidec.c.
Referenced by avi_sync(), and guess_ni_flag().
avi_sync()
static int avi_sync (AVFormatContext * s, int exit_early) static
Parameters
exit_early set to 1 to just gather packet position without making the changes needed to actually read & return the packet
Definition at line 1184 of file avidec.c.
Referenced by avi_read_idx1(), and avi_read_packet().
ni_prepare_read()
static int ni_prepare_read (AVFormatContext * s) static
Definition at line 1333 of file avidec.c.
Referenced by avi_read_packet().
avi_read_packet()
static int avi_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 1402 of file avidec.c.
avi_read_idx1()
static int avi_read_idx1 (AVFormatContext * s, int size) static
Definition at line 1559 of file avidec.c.
Referenced by avi_load_index().
check_stream_max_drift()
static int check_stream_max_drift (AVFormatContext * s) static
Definition at line 1647 of file avidec.c.
Referenced by guess_ni_flag().
seek_subtitle()
static void seek_subtitle (AVStream * st, AVStream * st2, int64_t timestamp) static
Definition at line 1791 of file avidec.c.
Referenced by avi_read_seek().
avi_read_seek()
static int avi_read_seek (AVFormatContext * s, int stream_index, int64_t timestamp, int flags) static
Definition at line 1801 of file avidec.c.
avi_read_close()
static int avi_read_close (AVFormatContext * s) static
Definition at line 1918 of file avidec.c.
avi_probe()
static int avi_probe (AVProbeData * p) static
Definition at line 1941 of file avidec.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "use_odml", "use odml index", 0x42, AV_OPT_TYPE_BOOL, {.i64 = 1}, -1, 1, AV_OPT_FLAG_DECODING_PARAM},
    { NULL },
}
Definition at line 89 of file avidec.c.
demuxer_class
const AVClass demuxer_class static
Initial value:
= {
    .class_name = "avi",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
    .category   = AV_CLASS_CATEGORY_DEMUXER,
}
Definition at line 94 of file avidec.c.
avi_headers
const char avi_headers[][8] static
Initial value:
= {
    { 'R', 'I', 'F', 'F', 'A', 'V', 'I', ' '  },
    { 'R', 'I', 'F', 'F', 'A', 'V', 'I', 'X'  },
    { 'R', 'I', 'F', 'F', 'A', 'V', 'I', 0x19 },
    { 'O', 'N', '2', ' ', 'O', 'N', '2', 'f'  },
    { 'R', 'I', 'F', 'F', 'A', 'M', 'V', ' '  },
    { 0 }
}
Definition at line 103 of file avidec.c.
Referenced by avi_probe(), and get_riff().
avi_metadata_conv
const AVMetadataConv avi_metadata_conv[] static
Initial value:
= {
    { "strn", "title" },
    { 0 },
}
Definition at line 112 of file avidec.c.
months
const char months[12][4] static
Initial value:
= { "Jan", "Feb", "Mar", "Apr", "May", "Jun",
                                    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }
Definition at line 323 of file avidec.c.
Referenced by avi_metadata_creation_time().
ff_avi_demuxer
AVInputFormat ff_avi_demuxer
Initial value:
= {
    .name           = "avi",
    .long_name      = NULL_IF_CONFIG_SMALL("AVI (Audio Video Interleaved)"),
    .priv_data_size = sizeof(AVIContext),
    .extensions     = "avi",
    .read_probe     = avi_probe,
    .read_header    = avi_read_header,
    .read_packet    = avi_read_packet,
    .read_close     = avi_read_close,
    .read_seek      = avi_read_seek,
    .priv_class = &demuxer_class,
}
Definition at line 1954 of file avidec.c.