FFmpeg: doc/examples/avio_reading.c File Reference
avio_reading.c File Reference
libavformat AVIOContext API example.
#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
#include <libavformat/avio.h>
#include <libavutil/file.h>
Data Structures
struct buffer_data
Functions
static int read_packet (void *opaque, uint8_t *buf, int buf_size)
int main (int argc, char *argv[])
Detailed Description
libavformat AVIOContext API example.
Make libavformat demuxer access media content through a custom AVIOContext read callback.
Definition in file avio_reading.c.
Function Documentation
read_packet()
static int read_packet (void * opaque, uint8_t * buf, int buf_size) static
Examples:
avio_reading.c.
Definition at line 42 of file avio_reading.c.
Referenced by amr_read_packet(), avio_alloc_context(), ff_rtsp_open_transport_ctx(), ffio_init_context(), main(), mmf_read_packet(), and set_spdif().
main()
int main (int argc, char * argv[])
Examples:
avio_reading.c.
Definition at line 57 of file avio_reading.c.