FFmpeg: libavformat/avio.h File Reference
avio.h File Reference
libavformat » I/O Read/Write
Buffered I/O operations.
#include <stdint.h>
#include "libavutil/common.h"
#include "libavutil/dict.h"
#include "libavutil/log.h"
#include "libavformat/version.h"
Data Structures
struct AVIOInterruptCB
Callback for checking whether to abort blocking functions.
struct AVIODirEntry
Describes single entry of the directory.
struct AVIODirContext
struct AVIOContext
Bytestream IO Context.
Macros
#define AVIO_SEEKABLE_NORMAL 0x0001
Seeking works like for a local file.
#define AVSEEK_SIZE 0x10000
ORing this as the "whence" parameter to a seek function causes it to return the filesize without seeking anywhere.
#define AVSEEK_FORCE 0x20000
Passing this flag as the "whence" parameter to a seek function causes it to seek by any means (like reopening and linear reading) or other normally unreasonable means that can be extremely slow.
#define AVIO_FLAG_NONBLOCK 8
Use non-blocking mode.
#define AVIO_FLAG_DIRECT 0x8000
Use direct mode.
URL open modes
The flags argument to avio_open must be one of the following constants, optionally ORed with other flags.
#define AVIO_FLAG_READ 1
read-only
#define AVIO_FLAG_WRITE 2
write-only
#define AVIO_FLAG_READ_WRITE (AVIO_FLAG_READ|AVIO_FLAG_WRITE)
read-write pseudo flag
Enumerations
enum AVIODirEntryType {
AVIO_ENTRY_UNKNOWN, AVIO_ENTRY_BLOCK_DEVICE, AVIO_ENTRY_CHARACTER_DEVICE, AVIO_ENTRY_DIRECTORY,
AVIO_ENTRY_NAMED_PIPE, AVIO_ENTRY_SYMBOLIC_LINK, AVIO_ENTRY_SOCKET, AVIO_ENTRY_FILE,
AVIO_ENTRY_SERVER, AVIO_ENTRY_SHARE, AVIO_ENTRY_WORKGROUP
}
Directory entry types.
enum AVIODataMarkerType {
AVIO_DATA_MARKER_HEADER, AVIO_DATA_MARKER_SYNC_POINT, AVIO_DATA_MARKER_BOUNDARY_POINT, AVIO_DATA_MARKER_UNKNOWN,
AVIO_DATA_MARKER_TRAILER
}
Different data types that can be returned via the AVIO write_data_type callback.
Functions
const char * avio_find_protocol_name (const char *url)
Return the name of the protocol that will handle the passed URL.
int avio_check (const char *url, int flags)
Return AVIO_FLAG_* access flags corresponding to the access permissions of the resource in url, or a negative value corresponding to an AVERROR code in case of failure.
int avpriv_io_move (const char *url_src, const char *url_dst)
Move or rename a resource.
int avpriv_io_delete (const char *url)
Delete a resource.
int avio_open_dir (AVIODirContext **s, const char *url, AVDictionary **options)
Open directory for reading.
int avio_read_dir (AVIODirContext *s, AVIODirEntry **next)
Get next directory entry.
int avio_close_dir (AVIODirContext **s)
Close directory.
void avio_free_directory_entry (AVIODirEntry **entry)
Free entry allocated by avio_read_dir().
AVIOContext * avio_alloc_context (unsigned char *buffer, int buffer_size, int write_flag, void *opaque, int(*read_packet)(void *opaque, uint8_t *buf, int buf_size), int(*write_packet)(void *opaque, uint8_t *buf, int buf_size), int64_t(*seek)(void *opaque, int64_t offset, int whence))
Allocate and initialize an AVIOContext for buffered I/O.
void avio_w8 (AVIOContext *s, int b)
void avio_write (AVIOContext *s, const unsigned char *buf, int size)
void avio_wl64 (AVIOContext *s, uint64_t val)
void avio_wb64 (AVIOContext *s, uint64_t val)
void avio_wl32 (AVIOContext *s, unsigned int val)
void avio_wb32 (AVIOContext *s, unsigned int val)
void avio_wl24 (AVIOContext *s, unsigned int val)
void avio_wb24 (AVIOContext *s, unsigned int val)
void avio_wl16 (AVIOContext *s, unsigned int val)
void avio_wb16 (AVIOContext *s, unsigned int val)
int avio_put_str (AVIOContext *s, const char *str)
Write a NULL-terminated string.
int avio_put_str16le (AVIOContext *s, const char *str)
Convert an UTF-8 string to UTF-16LE and write it.
int avio_put_str16be (AVIOContext *s, const char *str)
Convert an UTF-8 string to UTF-16BE and write it.
void avio_write_marker (AVIOContext *s, int64_t time, enum AVIODataMarkerType type)
Mark the written bytestream as a specific type.
int64_t avio_seek (AVIOContext *s, int64_t offset, int whence)
fseek() equivalent for AVIOContext.
int64_t avio_skip (AVIOContext *s, int64_t offset)
Skip given number of bytes forward.
static av_always_inline int64_t avio_tell (AVIOContext *s)
ftell() equivalent for AVIOContext.
int64_t avio_size (AVIOContext *s)
Get the filesize.
int avio_feof (AVIOContext *s)
feof() equivalent for AVIOContext.
int avio_printf (AVIOContext *s, const char *fmt,...) av_printf_format(2
int void avio_flush (AVIOContext *s)
Force flushing of buffered data.
int avio_read (AVIOContext *s, unsigned char *buf, int size)
Read size bytes from AVIOContext into buf.
int avio_get_str (AVIOContext *pb, int maxlen, char *buf, int buflen)
Read a string from pb into buf.
int avio_get_str16le (AVIOContext *pb, int maxlen, char *buf, int buflen)
Read a UTF-16 string from pb and convert it to UTF-8.
int avio_get_str16be (AVIOContext *pb, int maxlen, char *buf, int buflen)
int avio_open (AVIOContext **s, const char *url, int flags)
Create and initialize a AVIOContext for accessing the resource indicated by url.
int avio_open2 (AVIOContext **s, const char *url, int flags, const AVIOInterruptCB *int_cb, AVDictionary **options)
Create and initialize a AVIOContext for accessing the resource indicated by url.
int avio_close (AVIOContext *s)
Close the resource accessed by the AVIOContext s and free it.
int avio_closep (AVIOContext **s)
Close the resource accessed by the AVIOContext *s, free it and set the pointer pointing to it to NULL.
int avio_open_dyn_buf (AVIOContext **s)
Open a write only memory stream.
int avio_close_dyn_buf (AVIOContext *s, uint8_t **pbuffer)
Return the written size and a pointer to the buffer.
const char * avio_enum_protocols (void **opaque, int output)
Iterate through names of available protocols.
int avio_pause (AVIOContext *h, int pause)
Pause and resume playing - only meaningful if using a network streaming protocol (e.g.
int64_t avio_seek_time (AVIOContext *h, int stream_index, int64_t timestamp, int flags)
Seek to a given timestamp relative to some component stream.
int avio_read_to_bprint (AVIOContext *h, struct AVBPrint *pb, size_t max_size)
Read contents of h into print buffer, up to max_size bytes, or up to EOF.
int avio_accept (AVIOContext *s, AVIOContext **c)
Accept and allocate a client context on a server context.
int avio_handshake (AVIOContext *c)
Perform one step of the protocol handshake to accept a new client.
Functions for reading from AVIOContext
Note
return 0 if EOF, so you cannot use it if EOF handling is necessary
int avio_r8 (AVIOContext *s)
unsigned int avio_rl16 (AVIOContext *s)
unsigned int avio_rl24 (AVIOContext *s)
unsigned int avio_rl32 (AVIOContext *s)
uint64_t avio_rl64 (AVIOContext *s)
unsigned int avio_rb16 (AVIOContext *s)
unsigned int avio_rb24 (AVIOContext *s)
unsigned int avio_rb32 (AVIOContext *s)
uint64_t avio_rb64 (AVIOContext *s)
Detailed Description
Buffered I/O operations.
Definition in file avio.h.
Macro Definition Documentation
AVIO_SEEKABLE_NORMAL
#define AVIO_SEEKABLE_NORMAL 0x0001
Seeking works like for a local file.
Definition at line 37 of file avio.h.
Referenced by ffio_fdopen(), ffio_init_context(), and mov_read_cmov().
AVSEEK_SIZE
#define AVSEEK_SIZE 0x10000
ORing this as the "whence" parameter to a seek function causes it to return the filesize without seeking anywhere.
Supporting this is optional. If it is not supported then the seek function will return <0.
Definition at line 485 of file avio.h.
Referenced by async_seek(), avio_size(), bluray_seek(), cache_seek(), crypto_seek(), ffurl_size(), file_move(), ftp_seek(), http_seek_internal(), libsmbc_seek(), libssh_seek(), rtmp_calc_swfhash(), subfile_seek(), and wtvfile_seek().
AVSEEK_FORCE
#define AVSEEK_FORCE 0x20000
Passing this flag as the "whence" parameter to a seek function causes it to seek by any means (like reopening and linear reading) or other normally unreasonable means that can be extremely slow.
This may be ignored by the seek code.
Definition at line 493 of file avio.h.
Referenced by avio_seek(), and ffurl_seek().
AVIO_FLAG_READ
#define AVIO_FLAG_READ 1
read-only
Examples:
http_multiclient.c.
Definition at line 606 of file avio.h.
Referenced by avio_open_dir(), build_feed_streams(), copy_moof(), crypto_open2(), ff_img_read_packet(), ff_rtsp_open_transport_ctx(), ffio_init_context(), ffio_set_buf_size(), ffurl_read(), ffurl_read_complete(), file_check(), file_move(), find_image_range(), find_index_range(), find_sidx(), ftp_open(), get_preset_file_2(), hls_encryption_start(), hls_read(), http_shutdown(), icecast_open(), import_pem(), init_input(), lavfi_read_header(), libsmbc_open(), libssh_open_file(), main(), mmsh_open_internal(), mov_open_dref(), open_output_file(), open_url(), parse_fragment(), parse_playlist(), process_client(), process_line(), read_file(), read_header(), read_mfra(), rtmp_calc_swfhash(), sap_read_header(), shift_data(), tcp_shutdown(), tee_open(), udp_close(), udp_open(), url_alloc_for_protocol(), and url_resetbuf().
AVIO_FLAG_WRITE
#define AVIO_FLAG_WRITE 2
write-only
Examples:
http_multiclient.c, muxing.c, qsvdec.c, remuxing.c, transcode_aac.c, and transcoding.c.
Definition at line 607 of file avio.h.
Referenced by avpriv_io_delete(), avpriv_io_move(), build_feed_streams(), chunk_end(), copy_moof(), crypto_open2(), crypto_seek(), dash_flush(), dash_init(), dump_attachment(), ff_format_output_open(), ff_rtsp_open_transport_ctx(), ffio_fdopen(), ffio_init_context(), ffio_set_buf_size(), ffurl_connect(), ffurl_write(), file_check(), file_move(), ftp_connect_control_connection(), ftp_open(), hds_write_header(), hls_open(), hls_start(), hls_window(), http_connect(), http_shutdown(), init(), init_file(), init_fps(), ism_flush(), ism_seek(), ism_write_header(), libsmbc_open(), libssh_open_file(), main(), md5_close(), md5_open(), open_null_ctx(), open_output_file(), opt_progress(), print_sdp(), rtmp_open(), rtp_new_av_stream(), rtp_open(), sap_write_header(), seg_init(), seg_write_header(), segment_list_open(), segment_start(), tcp_shutdown(), udp_open(), url_alloc_for_protocol(), url_resetbuf(), webm_chunk_write_header(), write_abst(), write_fragment(), write_manifest(), and write_packet().
AVIO_FLAG_READ_WRITE
#define AVIO_FLAG_READ_WRITE (AVIO_FLAG_READ|AVIO_FLAG_WRITE)
read-write pseudo flag
Definition at line 608 of file avio.h.
Referenced by avpriv_io_move(), ff_rtsp_open_transport_ctx(), ff_tls_open_underlying(), ftp_connect_control_connection(), gopher_open(), http_listen(), http_open_cnx_internal(), icecast_open(), mms_open(), rtmp_http_open(), rtmp_open(), rtmpe_open(), rtsp_listen(), and rtsp_read_setup().
AVIO_FLAG_NONBLOCK
#define AVIO_FLAG_NONBLOCK 8
Use non-blocking mode.
If this flag is set, operations on the context will return AVERROR(EAGAIN) if they can not be performed immediately. If this flag is not set, operations on the context will never return AVERROR(EAGAIN). Note that this flag does not affect the opening/connecting of the context. Connecting a protocol will always block if necessary (e.g. on network protocols) but never hang (e.g. on busy devices). Warning: non-blocking protocols is work-in-progress; this flag may be silently ignored.
Definition at line 625 of file avio.h.
Referenced by retry_transfer_wrapper(), rtmp_http_read(), rtmp_write(), rtmpe_read(), rtp_read(), rtp_write(), sctp_read(), sctp_write(), tcp_read(), tcp_write(), udp_read(), udp_write(), unix_read(), and unix_write().
AVIO_FLAG_DIRECT
#define AVIO_FLAG_DIRECT 0x8000
Use direct mode.
avio_read and avio_write should if possible be satisfied directly instead of going through a buffer, and avio_seek will always call the underlying seek function directly.
Definition at line 633 of file avio.h.
Referenced by ffio_fdopen().
Enumeration Type Documentation
AVIODirEntryType
enum AVIODirEntryType
Directory entry types.
Enumerator
AVIO_ENTRY_UNKNOWN
AVIO_ENTRY_BLOCK_DEVICE
AVIO_ENTRY_CHARACTER_DEVICE
AVIO_ENTRY_DIRECTORY
AVIO_ENTRY_NAMED_PIPE
AVIO_ENTRY_SYMBOLIC_LINK
AVIO_ENTRY_SOCKET
AVIO_ENTRY_FILE
AVIO_ENTRY_SERVER
AVIO_ENTRY_SHARE
AVIO_ENTRY_WORKGROUP
Definition at line 58 of file avio.h.
AVIODataMarkerType
enum AVIODataMarkerType
Different data types that can be returned via the AVIO write_data_type callback.
Enumerator
AVIO_DATA_MARKER_HEADER
Header data; this needs to be present for the stream to be decodeable.
AVIO_DATA_MARKER_SYNC_POINT
A point in the output bytestream where a decoder can start decoding (i.e.
a keyframe). A demuxer/decoder given the data flagged with AVIO_DATA_MARKER_HEADER, followed by any AVIO_DATA_MARKER_SYNC_POINT, should give decodeable results.
AVIO_DATA_MARKER_BOUNDARY_POINT
A point in the output bytestream where a demuxer can start parsing (for non self synchronizing bytestream formats).
That is, any non-keyframe packet start point.
AVIO_DATA_MARKER_UNKNOWN
This is any, unlabelled data.
It can either be a muxer not marking any positions at all, it can be an actual boundary/sync point that the muxer chooses not to mark, or a later part of a packet/fragment that is cut into multiple write callbacks due to limited IO buffer size.
AVIO_DATA_MARKER_TRAILER
Trailer data, which doesn't contain actual content, but only for finalizing the output file.
Definition at line 103 of file avio.h.
Function Documentation
avio_find_protocol_name()
const char* avio_find_protocol_name (const char * url)
Return the name of the protocol that will handle the passed URL.
NULL is returned if no protocol could be found for the given URL.
Returns
Name of the protocol or NULL.
Definition at line 473 of file avio.c.
Referenced by add_file(), assert_file_overwrite(), ff_configure_buffers_for_index(), hls_window(), open_url(), and seg_init().
avio_check()
int avio_check (const char * url, int flags)
Return AVIO_FLAG_* access flags corresponding to the access permissions of the resource in url, or a negative value corresponding to an AVERROR code in case of failure.
The returned access flags are masked by the value in flags.
Note
This function is intrinsically unsafe, in the sense that the checked resource may change its existence or permission status from one call to another. Thus you should not trust the returned value, unless you are sure that no other processes are accessing the checked resource.
Definition at line 480 of file avio.c.
Referenced by assert_file_overwrite(), build_feed_streams(), and find_image_range().
avpriv_io_move()
int avpriv_io_move (const char * url_src, const char * url_dst)
Move or rename a resource.
Note
url_src and url_dst should share the same protocol and authority.
Parameters
url_src url to resource to be moved
url_dst new url to resource if the operation succeeded
Returns
>=0 on success or negative on error.
Definition at line 499 of file avio.c.
Referenced by dash_flush(), move_op(), and write_manifest().
avpriv_io_delete()
int avpriv_io_delete (const char * url)
Delete a resource.
Parameters
url resource to be deleted.
Returns
>=0 on success or negative on error.
Definition at line 521 of file avio.c.
Referenced by del_op().
avio_open_dir()
int avio_open_dir (AVIODirContext ** s, const char * url, AVDictionary ** options)
Open directory for reading.
Parameters
s directory read context. Pointer to a NULL pointer must be passed.
url directory to be listed.
options A dictionary filled with protocol-private options. On return this parameter will be destroyed and replaced with a dictionary containing options that were not found. May be NULL.
Returns
>=0 on success or negative on error.
Definition at line 537 of file avio.c.
Referenced by list_op().
avio_read_dir()
int avio_read_dir (AVIODirContext * s, AVIODirEntry ** next)
Get next directory entry.
Returned entry must be freed with avio_free_directory_entry(). In particular it may outlive AVIODirContext.
Parameters
s directory read context.
[out] next next entry or NULL when no more entries.
Returns
>=0 on success or negative on error. End of list is not considered an error.
Definition at line 575 of file avio.c.
Referenced by list_op().
avio_close_dir()
int avio_close_dir (AVIODirContext ** s)
Close directory.
Note
Entries created using avio_read_dir() are not deleted and must be freeded with avio_free_directory_entry().
Parameters
s directory read context.
Returns
>=0 on success or negative on error.
Definition at line 588 of file avio.c.
Referenced by list_op().
avio_free_directory_entry()
void avio_free_directory_entry (AVIODirEntry ** entry)
Free entry allocated by avio_read_dir().
Parameters
entry entry to be freed.
Definition at line 603 of file avio.c.
Referenced by avio_read_dir(), ftp_read_dir(), and list_op().
avio_alloc_context()
AVIOContext* avio_alloc_context (unsigned char * buffer, int buffer_size, int write_flag, void * opaque, int(*)(void *opaque, uint8_t *buf, int buf_size) read_packet, int(*)(void *opaque, uint8_t *buf, int buf_size) write_packet, int64_t(*)(void *opaque, int64_t offset, int whence) seek)
Allocate and initialize an AVIOContext for buffered I/O.
It must be later freed with av_free().
Parameters
buffer Memory block for input/output operations via AVIOContext. The buffer must be allocated with av_malloc() and friends. It may be freed and replaced with a new buffer by libavformat. AVIOContext.buffer holds the buffer currently in use, which must be later freed with av_free().
buffer_size The buffer size is very important for performance. For protocols with fixed blocksize it should be set to this blocksize. For others a typical size is a cache page, e.g. 4kb.
write_flag Set to 1 if the buffer should be writable, 0 otherwise.
opaque An opaque pointer to user-specific data.
read_packet A function for refilling the buffer, may be NULL.
write_packet A function for writing the buffer contents, may be NULL. The function may not change the input buffers content.
seek A function for seeking to specified byte position, may be NULL.
Returns
Allocated AVIOContext or NULL on failure.
Examples:
avio_reading.c.
Definition at line 126 of file aviobuf.c.
Referenced by dash_init(), ff_flac_parse_picture(), ffio_fdopen(), hds_write_header(), http_receive_data(), init_fps(), ism_write_header(), main(), mpjpeg_read_probe(), open_null_ctx(), rdt_parse_packet(), read_gab2_sub(), swf_read_header(), url_open_dyn_buf_internal(), and wtvfile_open_sector().
avio_w8()
void avio_w8 (AVIOContext * s, int b)
Definition at line 182 of file aviobuf.c.
Referenced by aiff_write_trailer(), asf_write_header1(), avi_write_ix(), avi_write_packet(), avi_write_packet_internal(), avio_put_str(), avio_wb16(), avio_wb24(), avio_wb32(), avio_wl16(), avio_wl24(), avio_wl32(), caf_write_header(), decode_str(), ff_end_tag(), ff_id3v2_start(), ff_id3v2_write_apic(), ff_isom_write_avcc(), ff_isom_write_vpcc(), ff_mov_cenc_avc_parse_nal_units(), ff_put_bmp_header(), ff_put_v(), ff_put_wav_header(), ff_riff_write_info_tag(), ff_rtp_check_and_send_back_rr(), ff_rtp_send_data(), ff_rtp_send_punch_packets(), ff_rtp_send_rtcp_feedback(), ffm_write_header(), ffm_write_header_codec_ctx(), flac_write_block_padding(), flush(), flush_packet(), flv_write_codec_header(), flv_write_header(), flv_write_packet(), flv_write_trailer(), get_line(), gif_image_write_header(), gif_write_trailer(), gxf_write_dv_auxiliary(), gxf_write_map_packet(), gxf_write_material_data_section(), gxf_write_media_preamble(), gxf_write_mpeg_auxiliary(), gxf_write_packet_header(), gxf_write_padding(), gxf_write_timecode_auxiliary(), gxf_write_track_description(), gxf_write_umf_media_description(), gxf_write_umf_packet(), h261_handle_packet(), h263_handle_packet(), hvcc_write(), ico_write_packet(), ico_write_trailer(), id3v2_put_size(), id3v2_put_ttag(), klv_encode_ber4_length(), klv_encode_ber9_length(), klv_encode_ber_length(), mkv_write_block(), mkv_write_codecprivate(), mkv_write_vtt_blocks(), mmf_rate(), mov_cenc_write_saio_tag(), mov_cenc_write_saiz_tag(), mov_cenc_write_schi_tag(), mov_create_chapter_track(), mov_write_3gp_udta_tag(), mov_write_amr_tag(), mov_write_chan_tag(), mov_write_chpl_tag(), mov_write_colr_tag(), mov_write_d263_tag(), mov_write_dfla_tag(), mov_write_edts_tag(), mov_write_esds_tag(), mov_write_hdlr_tag(), mov_write_int8_metadata(), mov_write_iods_tag(), mov_write_itunes_hdlr_tag(), mov_write_loci_tag(), mov_write_mdhd_tag(), mov_write_mdta_hdlr_tag(), mov_write_mvhd_tag(), mov_write_sidx_tag(), mov_write_tcmi_tag(), mov_write_tfdt_tag(), mov_write_tfhd_tag(), mov_write_tfra_tag(), mov_write_tfrf_tag(), mov_write_tfxd_tag(), mov_write_tkhd_tag(), mov_write_tmcd_tag(), mov_write_traf_tag(), mov_write_trun_tag(), mov_write_video_tag(), mp3_write_xing(), mxf_write_cdci_common(), mxf_write_d10_audio_packet(), mxf_write_generic_sound_common(), mxf_write_index_table_segment(), mxf_write_mpegvideo_desc(), mxf_write_system_item(), mxf_write_timecode_component(), mxf_write_umid(), nut_write_header(), nut_write_packet(), ogg_write_page(), oma_write_header(), output_immediate(), output_match(), print_csv_escaped_str(), put_amf_bool(), put_amf_byte(), put_amf_double(), put_amf_dword_array(), put_avc_eos_tag(), put_descr(), put_ebml_id(), put_ebml_num(), put_ebml_sint(), put_ebml_size_unknown(), put_ebml_uint(), put_id3v2_tags(), put_meta(), put_padding_packet(), put_payload_header(), put_payload_parsing_info(), put_str(), put_str8(), put_timestamp(), put_vcd_padding_sector(), put_xiph_codecpriv(), put_xiph_size(), read_file(), rm_write_audio(), rm_write_video(), rtcp_send_sr(), rv10_write_header(), smjpeg_write_header(), swf_write_header(), swf_write_video(), vc1test_write_header(), voc_write_packet(), voc_write_trailer(), write_abst(), write_escape_str(), write_header(), write_metadata(), write_odml_master(), write_packet_header(), write_streamheader(), write_table_entries_attrib(), write_tags(), and write_trailer().
avio_write()
void avio_write (AVIOContext * s, const unsigned char * buf, int size)
Examples:
http_multiclient.c, and qsvdec.c.
Definition at line 204 of file aviobuf.c.
Referenced by a64_write_header(), ac3_handle_packet(), adts_write_packet(), aiff_write_header(), aiff_write_packet(), apng_write_chunk(), asf_write_header1(), asf_write_markers(), asfrtp_parse_packet(), ast_write_packet(), avi_write_packet_internal(), avio_close_dyn_buf(), avio_printf(), avio_put_str(), caf_write_header(), caf_write_packet(), caf_write_trailer(), chunk_end(), copy_moof(), copy_tag(), crc_write_trailer(), dash_write(), daud_write_packet(), decode_packet(), dump_attachment(), dv_handle_packet(), dv_write_packet(), end_ebml_master_crc32(), ff_ape_write_tag(), ff_avc_parse_nal_units(), ff_flac_write_header(), ff_hevc_annexb2mp4(), ff_id3v2_write_apic(), ff_isom_write_avcc(), ff_isom_write_hvcc(), ff_mov_cenc_avc_write_nal_units(), ff_mov_write_packet(), ff_put_bmp_header(), ff_put_guid(), ff_put_wav_header(), ff_raw_write_packet(), ff_rtp_check_and_send_back_rr(), ff_rtp_send_data(), ffm_write_header(), ffm_write_header_codec_ctx(), flac_write_block_comment(), flac_write_packet(), flac_write_trailer(), flush(), flush_packet(), flv_write_codec_header(), flv_write_header(), flv_write_packet(), framecrc_write_packet(), get_video_private_data(), gif_image_write_header(), gxf_write_material_data_section(), gxf_write_mpeg_auxiliary(), gxf_write_packet(), gxf_write_track_description(), gxf_write_umf_media_description(), h261_handle_packet(), h263_handle_packet(), hds_write(), http_send_data(), hvcc_write(), ico_write_packet(), id3v2_put_ttag(), ilbc_write_header(), ilbc_write_packet(), init_file(), ivf_write_header(), ivf_write_packet(), jacosub_write_header(), jpeg_parse_packet(), latm_parse_packet(), latm_write_packet(), main(), matroska_parse_tracks(), microdvd_write_header(), microdvd_write_packet(), mkv_write_block(), mkv_write_codecprivate(), mkv_write_native_codecprivate(), mkv_write_video_color(), mmf_rate(), mov_cenc_write_encrypted(), mov_cenc_write_saiz_tag(), mov_cenc_write_schi_tag(), mov_cenc_write_senc_tag(), mov_flush_fragment(), mov_flush_fragment_interleaving(), mov_write_3gp_udta_tag(), mov_write_ac3_tag(), mov_write_chpl_tag(), mov_write_dfla_tag(), mov_write_dvc1_tag(), mov_write_eac3_tag(), mov_write_esds_tag(), mov_write_extradata_tag(), mov_write_glbl_tag(), mov_write_hdlr_tag(), mov_write_isml_manifest(), mov_write_loci_tag(), mov_write_mdta_keys_tag(), mov_write_raw_metadata_tag(), mov_write_source_reference_tag(), mov_write_string_data_tag(), mov_write_subtitle_tag(), mov_write_tcmi_tag(), mov_write_tfrf_tag(), mov_write_tfxd_tag(), mov_write_tmcd_tag(), mov_write_track_metadata(), mov_write_track_udta_tag(), mov_write_udta_sdp(), mov_write_udta_tag(), mov_write_video_tag(), mp3_update_xing(), mp3_write_trailer(), mp3_write_xing(), mpa_robust_parse_packet(), mpegts_insert_null_packet(), mpegts_insert_pcr_only(), mpegts_prefix_m2ts_header(), mpegts_write_pes(), mpjpeg_write_packet(), mxf_write_cdci_common(), mxf_write_common_fields(), mxf_write_d10_video_packet(), mxf_write_essence_container_refs(), mxf_write_generic_desc(), mxf_write_index_table_segment(), mxf_write_klv_fill(), mxf_write_metadata_key(), mxf_write_multi_descriptor(), mxf_write_opatom_body_partition(), mxf_write_opatom_packet(), mxf_write_packet(), mxf_write_partition(), mxf_write_preface(), mxf_write_primer_pack(), mxf_write_random_index_pack(), mxf_write_system_item(), mxf_write_tagged_value(), mxf_write_track(), mxf_write_umid(), mxf_write_uuid(), nut_write_header(), nut_write_packet(), ogg_write_page(), output_immediate(), print_file(), print_report(), process_client(), put_amf_string(), put_ebml_binary(), put_flac_codecpriv(), put_frame(), put_meta(), put_packet(), put_str(), put_str16(), put_swf_matrix(), put_swf_rect(), put_videoinfoheader2(), put_wv_codecpriv(), put_xiph_codecpriv(), read_file(), rm_write_audio(), rm_write_video(), roq_write_header(), rso_write_packet(), rtcp_send_sr(), rtsp_cmd_describe(), rv10_write_header(), section_write_packet(), shift_data(), smjpeg_write_header(), smjpeg_write_packet(), sox_write_header(), spdif_write_packet(), srt_write_packet(), svq3_parse_packet(), swf_write_header(), swf_write_video(), tta_write_header(), tta_write_packet(), tta_write_trailer(), vc1test_write_header(), vc1test_write_packet(), vc2hq_handle_frame_fragment(), voc_write_header(), voc_write_packet(), vp8_handle_packet(), vp9_handle_packet(), webp_write_packet(), webvtt_write_packet(), write_chapter(), write_frame(), write_globalinfo(), write_header(), write_header_chunk(), write_hint_packets(), write_mainheader(), write_packet(), write_root_table(), write_sm_data(), write_stream_codec_info(), write_streamheader(), write_streaminfo(), write_table0_header_legacy_attrib(), write_table_entries_attrib(), write_trailer(), wv_write_packet(), xiph_handle_packet(), and yuv4_write_packet().
avio_wl64()
void avio_wl64 (AVIOContext * s, uint64_t val)
Definition at line 434 of file aviobuf.c.
Referenced by asf_write_header1(), asf_write_index(), asf_write_markers(), avi_write_ix(), end_header(), gxf_write_dv_auxiliary(), gxf_write_track_description(), gxf_write_umf_material_description(), gxf_write_umf_media_audio(), ivf_write_header(), ivf_write_packet(), ivf_write_trailer(), ogg_write_page(), put_header(), put_videoinfoheader2(), sox_write_header(), sox_write_trailer(), update_odml_entry(), write_chunk_header(), write_chunk_header2(), write_index(), write_odml_master(), write_root_table(), write_sync(), write_table0_header_events(), write_table0_header_time(), write_table_entries_events(), write_table_entries_time(), write_table_redirector_legacy_attrib(), and write_timestamp().
avio_wb64()
void avio_wb64 (AVIOContext * s, uint64_t val)
Definition at line 440 of file aviobuf.c.
Referenced by aiff_write_header(), apng_write_header(), ast_write_header(), ast_write_packet(), caf_write_header(), caf_write_trailer(), ffm_write_header(), flush_packet(), klv_encode_ber9_length(), mov_cenc_write_saio_tag(), mov_write_audio_tag(), mov_write_avid_tag(), mov_write_chpl_tag(), mov_write_edts_tag(), mov_write_mdhd_tag(), mov_write_mvhd_tag(), mov_write_sidx_tag(), mov_write_stco_tag(), mov_write_tfdt_tag(), mov_write_tfhd_tag(), mov_write_tfra_tag(), mov_write_tfrf_tag(), mov_write_tfxd_tag(), mov_write_tkhd_tag(), mov_write_trailer(), mov_write_vmhd_tag(), mxf_write_common_fields(), mxf_write_generic_sound_common(), mxf_write_identification(), mxf_write_index_table_segment(), mxf_write_package(), mxf_write_partition(), mxf_write_preface(), mxf_write_random_index_pack(), mxf_write_structural_component(), mxf_write_system_item(), mxf_write_timecode_component(), mxf_write_track(), put_amf_double(), put_ebml_float(), put_packet(), sox_write_header(), sox_write_trailer(), write_abst(), and write_index().
avio_wl32()
void avio_wl32 (AVIOContext * s, unsigned int val)
Definition at line 346 of file aviobuf.c.
Referenced by aiff_write_header(), asf_write_header1(), asf_write_index(), asf_write_markers(), ast_write_header(), avi_write_counters(), avi_write_header(), avi_write_idx1(), avi_write_ix(), avi_write_packet(), avi_write_packet_internal(), avi_write_trailer(), avio_wl64(), caf_write_header(), ff_ape_write_tag(), ff_end_tag(), ff_mov_cenc_write_sinf_tag(), ff_put_bmp_header(), ff_put_wav_header(), ff_riff_write_info_tag(), ff_start_tag(), ffio_wfourcc(), ffm_write_header(), finish_chunk_noindex(), flush(), gxf_write_flt_packet(), gxf_write_timecode_auxiliary(), gxf_write_umf_material_description(), gxf_write_umf_media_audio(), gxf_write_umf_media_description(), gxf_write_umf_media_dv(), gxf_write_umf_media_mpeg(), gxf_write_umf_media_timecode(), gxf_write_umf_payload(), ico_write_packet(), ico_write_trailer(), init_file(), ircam_write_header(), ivf_write_header(), ivf_write_packet(), matroska_parse_tracks(), mkv_write_codecprivate(), mkv_write_native_codecprivate(), mov_write_audio_tag(), mov_write_ms_tag(), mov_write_subtitle_tag(), mov_write_tref_tag(), mov_write_video_tag(), mov_write_wave_tag(), mxf_write_d10_audio_packet(), nut_write_packet(), ogg_write_page(), oma_write_header(), put_chunk(), put_id3v2_tags(), put_meta(), put_packet(), put_payload_header(), put_payload_parsing_info(), put_swf_end_tag(), put_swf_tag(), put_videoinfoheader2(), rv10_write_header(), smjpeg_write_header(), smjpeg_write_packet(), smjpeg_write_trailer(), sox_write_header(), swf_write_header(), swf_write_trailer(), tta_write_header(), tta_write_packet(), tta_write_trailer(), update_odml_entry(), vc1test_write_header(), vc1test_write_packet(), voc_write_packet(), webp_write_trailer(), write_abst(), write_chunk_header(), write_fat(), write_header(), write_index(), write_metadata_header(), write_odml_master(), write_root_table(), write_stream_codec(), write_stream_codec_info(), write_stream_data(), write_streamheader(), write_table0_header_events(), write_table0_header_legacy_attrib(), write_table0_header_time(), write_table_entries_attrib(), write_tag_int32(), write_trailer(), and wv_write_trailer().
avio_wb32()
void avio_wb32 (AVIOContext * s, unsigned int val)
Definition at line 354 of file aviobuf.c.
Referenced by aiff_write_header(), aiff_write_trailer(), apng_write_chunk(), ast_write_header(), ast_write_packet(), ast_write_trailer(), avi_write_packet(), avio_wb64(), caf_write_header(), caf_write_trailer(), close_file(), copy_tag(), ff_avc_parse_nal_units(), ff_hevc_annexb2mp4(), ff_id3v2_start(), ff_id3v2_write_apic(), ff_mov_cenc_avc_parse_nal_units(), ff_mov_cenc_write_sinf_tag(), ff_mov_write_chan(), ff_rtp_check_and_send_back_rr(), ff_rtp_send_data(), ff_rtp_send_punch_packets(), ff_rtp_send_rtcp_feedback(), ffm_write_header(), flush_packet(), flv_write_codec_header(), flv_write_header(), flv_write_packet(), force_one_stream(), get_video_private_data(), gxf_write_material_data_section(), gxf_write_media_preamble(), gxf_write_packet_header(), gxf_write_track_description(), gxf_write_umf_packet(), hvcc_write(), id3v2_put_ttag(), init_file(), mkv_write_codecprivate(), mmf_rate(), mov_cenc_write_saio_tag(), mov_cenc_write_saiz_tag(), mov_cenc_write_schi_tag(), mov_cenc_write_senc_tag(), mov_create_chapter_track(), mov_flush_fragment(), mov_write_3gp_udta_tag(), mov_write_ac3_tag(), mov_write_amr_tag(), mov_write_audio_tag(), mov_write_avcc_tag(), mov_write_avid_tag(), mov_write_chan_tag(), mov_write_chpl_tag(), mov_write_colr_tag(), mov_write_ctts_tag(), mov_write_d263_tag(), mov_write_dfla_tag(), mov_write_dinf_tag(), mov_write_dpxe_tag(), mov_write_dref_tag(), mov_write_dvc1_tag(), mov_write_eac3_tag(), mov_write_edts_tag(), mov_write_enda_tag(), mov_write_enda_tag_be(), mov_write_esds_tag(), mov_write_fiel_tag(), mov_write_ftyp_tag(), mov_write_gama_tag(), mov_write_glbl_tag(), mov_write_gmhd_tag(), mov_write_hdlr_tag(), mov_write_hmhd_tag(), mov_write_hvcc_tag(), mov_write_ilst_tag(), mov_write_int8_metadata(), mov_write_iods_tag(), mov_write_isml_manifest(), mov_write_itunes_hdlr_tag(), mov_write_loci_tag(), mov_write_mdat_tag(), mov_write_mdhd_tag(), mov_write_mdia_tag(), mov_write_mdta_hdlr_tag(), mov_write_mdta_ilst_tag(), mov_write_mdta_keys_tag(), mov_write_meta_tag(), mov_write_mfhd_tag(), mov_write_mfra_tag(), mov_write_minf_tag(), mov_write_moof_tag_internal(), mov_write_moov_tag(), mov_write_ms_tag(), mov_write_mvex_tag(), mov_write_mvhd_tag(), mov_write_nmhd_tag(), mov_write_pasp_tag(), mov_write_psp_udta_tag(), mov_write_raw_metadata_tag(), mov_write_rtp_tag(), mov_write_sidx_tag(), mov_write_smhd_tag(), mov_write_source_reference_tag(), mov_write_stbl_tag(), mov_write_stco_tag(), mov_write_string_data_tag(), mov_write_string_tag(), mov_write_stsc_tag(), mov_write_stsd_tag(), mov_write_stss_tag(), mov_write_stsz_tag(), mov_write_stts_tag(), mov_write_subtitle_tag(), mov_write_tapt_tag(), mov_write_tcmi_tag(), mov_write_tfdt_tag(), mov_write_tfhd_tag(), mov_write_tfra_tag(), mov_write_tfrf_tag(), mov_write_tfxd_tag(), mov_write_tkhd_tag(), mov_write_tmcd_tag(), mov_write_tmpo_tag(), mov_write_track_metadata(), mov_write_track_udta_tag(), mov_write_traf_tag(), mov_write_trailer(), mov_write_trak_tag(), mov_write_tref_tag(), mov_write_trex_tag(), mov_write_trkn_tag(), mov_write_trun_tag(), mov_write_udta_sdp(), mov_write_udta_tag(), mov_write_uuid_tag_ipod(), mov_write_uuid_tag_psp(), mov_write_uuidprof_tag(), mov_write_uuidusmt_tag(), mov_write_video_tag(), mov_write_vmhd_tag(), mov_write_vpcc_tag(), mov_write_wave_tag(), mov_write_wfex_tag(), mp3_write_xing(), mxf_write_cdci_common(), mxf_write_essence_container_data(), mxf_write_generic_desc(), mxf_write_generic_sound_common(), mxf_write_index_table_segment(), mxf_write_mpegvideo_desc(), mxf_write_multi_descriptor(), mxf_write_partition(), mxf_write_primer_pack(), mxf_write_random_index_pack(), mxf_write_refs_count(), mxf_write_structural_component(), mxf_write_system_item(), mxf_write_track(), mxf_write_wav_common(), ogg_update_checksum(), oma_write_header(), output_match(), put_amf_dword_array(), put_avc_eos_tag(), put_id3v2_tags(), put_meta(), put_padding_packet(), rm_write_trailer(), rm_write_video(), rtcp_send_sr(), rv10_write_header(), shift_data(), smjpeg_write_header(), smjpeg_write_packet(), smjpeg_write_trailer(), sox_write_header(), swf_write_video(), update_size(), updatePacketSize(), write_abst(), write_chapter(), write_header_chunk(), write_hint_packets(), write_matrix(), write_metadata(), write_packet_header(), write_styp(), and write_trailer().
avio_wl24()
void avio_wl24 (AVIOContext * s, unsigned int val)
Definition at line 458 of file aviobuf.c.
Referenced by flush(), vc1test_write_header(), vc1test_write_trailer(), and voc_write_packet().
avio_wb24()
void avio_wb24 (AVIOContext * s, unsigned int val)
Definition at line 464 of file aviobuf.c.
Referenced by flac_write_block_padding(), flv_write_codec_header(), flv_write_header(), flv_write_packet(), gif_image_write_header(), gxf_write_media_preamble(), klv_encode_ber4_length(), mov_cenc_write_saio_tag(), mov_cenc_write_schi_tag(), mov_write_chan_tag(), mov_write_dfla_tag(), mov_write_edts_tag(), mov_write_esds_tag(), mov_write_mdhd_tag(), mov_write_mvhd_tag(), mov_write_sidx_tag(), mov_write_tfdt_tag(), mov_write_tfhd_tag(), mov_write_tfra_tag(), mov_write_tfrf_tag(), mov_write_tfxd_tag(), mov_write_tkhd_tag(), mov_write_trun_tag(), mp3_write_xing(), mxf_write_metadata_key(), mxf_write_umid(), put_avc_eos_tag(), shift_data(), and write_metadata().
avio_wl16()
void avio_wl16 (AVIOContext * s, unsigned int val)
Definition at line 446 of file aviobuf.c.
Referenced by asf_write_header1(), asf_write_index(), asf_write_markers(), avi_write_header(), avi_write_ix(), avi_write_packet(), avio_wl24(), ff_put_bmp_header(), ff_put_wav_header(), flush(), flush_packet(), gif_image_write_header(), gxf_write_umf_material_description(), gxf_write_umf_media_description(), gxf_write_umf_track_description(), ico_write_header(), ico_write_trailer(), id3v2_encode_string(), ivf_write_header(), matroska_parse_tracks(), mxf_write_d10_audio_packet(), oma_write_header(), put_chunk(), put_payload_header(), put_payload_parsing_info(), put_str16(), put_swf_end_tag(), put_swf_tag(), put_wv_codecpriv(), spdif_put_16(), swf_write_header(), swf_write_trailer(), swf_write_video(), tta_write_header(), voc_write_header(), voc_write_packet(), webp_write_trailer(), write_odml_master(), and write_root_table().
avio_wb16()
void avio_wb16 (AVIOContext * s, unsigned int val)
Definition at line 452 of file aviobuf.c.
Referenced by aiff_write_header(), ascii_to_wc(), ast_write_header(), ast_write_trailer(), avio_wb24(), caf_write_header(), daud_write_packet(), ff_id3v2_write_apic(), ff_isom_write_avcc(), ff_isom_write_vpcc(), ff_rtp_check_and_send_back_rr(), ff_rtp_send_data(), ff_rtp_send_punch_packets(), ff_rtp_send_rtcp_feedback(), flush_packet(), gxf_write_material_data_section(), gxf_write_media_preamble(), gxf_write_track_description(), gxf_write_track_description_section(), gxf_write_umf_media_description(), hvcc_write(), id3v2_put_ttag(), mkv_write_block(), mkv_write_vtt_blocks(), mov_create_chapter_track(), mov_write_3gp_udta_tag(), mov_write_amr_tag(), mov_write_audio_tag(), mov_write_colr_tag(), mov_write_enda_tag(), mov_write_enda_tag_be(), mov_write_esds_tag(), mov_write_fiel_tag(), mov_write_gmhd_tag(), mov_write_hmhd_tag(), mov_write_iods_tag(), mov_write_loci_tag(), mov_write_mdhd_tag(), mov_write_mvhd_tag(), mov_write_psp_udta_tag(), mov_write_rtp_tag(), mov_write_sidx_tag(), mov_write_smhd_tag(), mov_write_source_reference_tag(), mov_write_string_data_tag(), mov_write_subtitle_tag(), mov_write_tcmi_tag(), mov_write_tkhd_tag(), mov_write_tmcd_tag(), mov_write_tmpo_tag(), mov_write_trkn_tag(), mov_write_uuidprof_tag(), mov_write_uuidusmt_tag(), mov_write_video_tag(), mp3_write_xing(), mxf_write_local_tag(), mxf_write_partition(), mxf_write_preface(), mxf_write_primer_pack(), mxf_write_system_item(), mxf_write_timecode_component(), mxf_write_uuid(), mxf_write_wav_common(), output_match(), put_amf_string(), put_padding_packet(), put_str(), put_str16(), put_timestamp(), rm_write_video(), rso_write_header(), rso_write_trailer(), rtcp_send_sr(), rv10_write_header(), smjpeg_write_header(), spdif_put_16(), updateSize(), write_chapter(), write_hint_packets(), write_packet_header(), and write_trailer().
avio_put_str()
int avio_put_str (AVIOContext * s, const char * str)
Write a NULL-terminated string.
Returns
number of bytes written.
Definition at line 362 of file aviobuf.c.
Referenced by caf_write_header(), ff_ape_write_tag(), ff_id3v2_write_apic(), ff_riff_write_info_tag(), ffm_write_recommended_config(), id3v2_encode_string(), and write_chapter().
avio_put_str16le()
int avio_put_str16le (AVIOContext * s, const char * str)
Convert an UTF-8 string to UTF-16LE and write it.
Parameters
s the AVIOContext
str NULL-terminated UTF-8 string
Returns
number of bytes written.
Referenced by asf_write_header1(), asf_write_markers(), id3v2_encode_string(), mms_put_utf16(), mxf_write_tagged_value(), put_str16(), write_metadata_header(), write_table_entries_attrib(), and write_tag().
avio_put_str16be()
int avio_put_str16be (AVIOContext * s, const char * str)
Convert an UTF-8 string to UTF-16BE and write it.
Parameters
s the AVIOContext
str NULL-terminated UTF-8 string
Returns
number of bytes written.
Referenced by mxf_write_local_tag_utf16().
avio_write_marker()
void avio_write_marker (AVIOContext * s, int64_t time, enum AVIODataMarkerType type)
Mark the written bytestream as a specific type.
Zero-length ranges are omitted from the output.
Parameters
time the stream time the current bytestream pos corresponds to (in AV_TIME_BASE units), or AV_NOPTS_VALUE if unknown or not applicable
type the kind of data written starting at the current pos
Definition at line 470 of file aviobuf.c.
Referenced by av_write_trailer(), flv_write_packet(), mkv_write_packet(), mov_flush_fragment(), mov_write_trailer(), and write_header_internal().
avio_seek()
int64_t avio_seek (AVIOContext * s, int64_t offset, int whence)
fseek() equivalent for AVIOContext.
Returns
new position or AVERROR.
Definition at line 230 of file aviobuf.c.
Referenced by aa_read_header(), adjust_write_index(), adts_aac_read_header(), adx_read_header(), aiff_read_header(), aiff_write_trailer(), aix_read_header(), align_position(), ape_read_header(), ape_read_packet(), ape_read_seek(), apng_read_header(), apng_read_packet(), apng_write_trailer(), asf_build_simple_index(), asf_get_packet(), asf_read_frame_header(), asf_read_header(), asf_read_packet(), asf_read_payload(), asf_read_pts(), asf_read_seek(), asf_read_subpayload(), asf_read_timestamp(), asf_write_header1(), asf_write_trailer(), ast_write_trailer(), av_seek(), avi_load_index(), avi_read_header(), avi_read_idx1(), avi_read_seek(), avi_write_counters(), avi_write_packet(), avi_write_trailer(), avio_skip(), avio_tell(), bfi_read_header(), caf_write_trailer(), check(), check_tag(), cine_read_header(), cine_read_packet(), close_file(), dsf_read_header(), dss_read_header(), dss_read_metadata_date(), dss_read_metadata_string(), dss_read_seek(), dtshd_read_header(), dv_read_header(), dv_read_seek(), dv_read_timecode(), dxa_read_header(), dxa_read_packet(), ea_read_packet(), efi_read(), end_ebml_master(), end_header(), estimate_timings_from_pts(), ff_ape_parse_tag(), ff_end_tag(), ff_get_qtpalette(), ff_id3v1_read(), ff_id3v2_finish(), ff_img_read_header(), ff_img_read_packet(), ff_pcm_read_seek(), ff_read_riff_info(), ff_rm_read_mdpr_codecdata(), ff_sauce_read(), ff_seek_frame_binary(), ffm2_read_header(), ffm_read_data(), ffm_seek1(), film_read_packet(), film_read_seek(), find_and_decode_index(), find_any_startcode(), find_index_range(), find_sidx(), finish_chunk_noindex(), flac_read_header(), flac_read_timestamp(), flac_seek(), flac_write_trailer(), flic_read_header(), flv_data_packet(), flv_read_header(), flv_read_packet(), flv_write_codec_header(), flv_write_packet(), flv_write_trailer(), force_one_stream(), fsb_read_header(), genh_read_header(), get_attachment(), get_tag(), gif_read_header(), gif_read_packet(), guess_ni_flag(), gxf_read_timestamp(), gxf_resync_media(), gxf_seek(), gxf_write_trailer(), gxf_write_umf_media_description(), hnm_read_packet(), ico_write_trailer(), id3v2_parse(), id3v2_read_internal(), idcin_read_seek(), iff_read_header(), init_stream(), ipmovie_read_header(), ivf_write_trailer(), ivr_read_header(), load_ipmovie_packet(), lvf_read_header(), matroska_parse_seekhead_entry(), matroska_read_seek(), matroska_resync(), mkv_check_new_extra_data(), mkv_write_seekhead(), mkv_write_trailer(), mmf_rate(), mov_parse_stsd_video(), mov_read_chapters(), mov_read_custom(), mov_read_default(), mov_read_dref(), mov_read_dvc1(), mov_read_glbl(), mov_read_header(), mov_read_meta(), mov_read_mfra(), mov_read_packet(), mov_read_rtmd_track(), mov_read_timecode_track(), mov_read_udta_string(), mov_switch_root(), mov_write_mdta_keys_tag(), mov_write_sidx_tag(), mov_write_stsc_tag(), mov_write_stss_tag(), mov_write_tfrf_tag(), mov_write_tfrf_tags(), mov_write_trailer(), mp3_parse_vbr_tags(), mp3_parse_vbri_tag(), mp3_read_header(), mp3_sync(), mp3_update_xing(), mpc8_handle_chunk(), mpc8_parse_seektable(), mpc8_read_header(), mpc8_read_seek(), mpc_read_header(), mpc_read_packet(), mpegps_read_dts(), mpegps_read_header(), mpegps_read_packet(), mpegps_read_pes_header(), mpegts_get_dts(), mpegts_get_pcr(), mpegts_raw_read_packet(), mpegts_resync(), mpjpeg_read_header(), mpjpeg_read_packet(), mtaf_read_header(), mtv_read_header(), musx_read_header(), mv_read_packet(), mxf_parse_handle_essence(), mxf_parse_klv(), mxf_read_header(), mxf_read_local_tags(), mxf_read_packet(), mxf_read_packet_old(), mxf_read_random_index_pack(), mxf_read_seek(), mxf_seek_to_previous_partition(), mxf_write_footer(), mxf_write_partition(), ni_prepare_read(), nsv_parse_NSVf_header(), nsv_read_seek(), nut_read_header(), nuv_read_dts(), ogg_get_length(), ogg_read_page(), ogg_read_timestamp(), ogg_replace_stream(), ogg_restore(), ogg_update_checksum(), oma_read_seek(), open_input(), parse_fragment(), parse_keyframes_index(), parse_media_type(), parse_mp4_descr(), process_ea_header(), put_id3v2_tags(), put_swf_end_tag(), pva_read_timestamp(), qt_rtp_parse_packet(), r3d_read_header(), r3d_seek(), rdt_load_mdpr(), read_apic(), read_braindead_odml_indx(), read_dst_frame(), read_frame(), read_header(), read_id3(), read_mfra(), read_moof_duration(), read_packet(), read_seek(), read_tfra(), recover(), resync(), rl2_read_packet(), rm_read_dts(), rm_read_header(), rm_read_index(), rm_write_trailer(), roq_read_packet(), rpl_read_header(), rpl_read_packet(), rso_write_trailer(), sdr2_read_header(), seek_back(), seek_by_sector(), seek_frame_byte(), seek_frame_generic(), seq_fill_buffer(), seq_init_frame_buffers(), seq_parse_frame_data(), seq_read_packet(), set_spdif(), shift_data(), skip_reserved(), skip_tag(), smacker_read_packet(), smjpeg_write_trailer(), sox_write_trailer(), str_read_header(), swf_write_trailer(), tak_read_header(), thp_read_header(), thp_read_packet(), tmv_read_seek(), tta_read_header(), tta_read_seek(), update_odml_entry(), update_size(), updatePacketSize(), updateSize(), vag_read_header(), vc1test_write_trailer(), vc2hq_handle_frame_fragment(), vmd_read_header(), vmd_read_packet(), voc_read_seek(), vqf_read_seek(), wc3_read_header(), wc3_read_packet(), webm_clusters_start_with_keyframe(), webm_dash_manifest_cues(), webp_write_trailer(), write_fragments(), write_hint_packets(), write_metadata(), write_root_table(), write_stream_codec_info(), write_trailer(), wsd_read_header(), wsvqa_read_header(), wv_read_block_header(), wv_read_header(), wv_write_trailer(), xmv_fetch_audio_packet(), xmv_fetch_new_packet(), xmv_fetch_video_packet(), yop_read_header(), yop_read_seek(), and yuv4_read_seek().
avio_skip()
int64_t avio_skip (AVIOContext * s, int64_t offset)
Skip given number of bytes forward.
Returns
new position or AVERROR.
Definition at line 304 of file aviobuf.c.
Referenced by aa_read_header(), aa_read_packet(), ads_read_header(), aea_read_header(), afc_read_header(), aiff_read_header(), aix_read_header(), aix_read_packet(), amf_get_string(), amf_parse_object(), amf_skip_tag(), ape_read_header(), apng_read_packet(), asf_build_simple_index(), asf_parse_packet(), asf_read_content_desc(), asf_read_data(), asf_read_ext_content_desc(), asf_read_ext_stream_properties(), asf_read_frame_header(), asf_read_header(), asf_read_language_list(), asf_read_marker(), asf_read_metadata(), asf_read_metadata_obj(), asf_read_multiple_payload(), asf_read_packet(), asf_read_packet_header(), asf_read_properties(), asf_read_replicated_data(), asf_read_simple_index(), asf_read_single_payload(), asf_read_stream_properties(), asf_read_subpayload(), asf_read_unknown(), asfrtp_parse_packet(), ast_read_header(), ast_read_packet(), ast_write_trailer(), avformat_open_input(), avi_read_header(), avi_read_nikon(), avi_sync(), avi_write_trailer(), avr_read_header(), avs_read_header(), avs_read_packet(), bfi_read_header(), cdata_read_header(), cdxl_read_packet(), check_file_header(), cine_read_header(), cine_read_packet(), dcstr_read_header(), decode_fctl_chunk(), decode_frame(), dfa_read_header(), dfa_read_packet(), dsf_read_header(), dss_read_seek(), dss_skip_audio_header(), dtshd_read_header(), dxa_read_header(), ea_read_packet(), ebml_parse_elem(), epaf_read_header(), ff_flac_parse_picture(), ff_get_line(), ff_get_wav_header(), ff_img_read_packet(), ff_mov_read_chan(), ff_mov_read_stsd_entries(), ff_mp4_parse_es_descr(), ff_read_riff_info(), ff_rm_read_mdpr_codecdata(), ff_sauce_read(), ff_spdif_read_packet(), ff_voc_get_packet(), finished_reading_packet(), flac_read_header(), flic_read_packet(), flv_read_header(), flv_read_packet(), flv_set_video_codec(), flv_write_codec_header(), fourxm_read_header(), fourxm_read_packet(), frm_read_header(), fsb_read_header(), genh_read_header(), get_aiff_header(), get_codec_data(), get_dts(), get_meta(), get_packet_header(), get_tag(), gif_read_ext(), gif_read_packet(), gif_skip_subblocks(), gxf_header(), gxf_material_tags(), gxf_packet(), gxf_read_index(), gxf_track_tags(), hnm_read_header(), hnm_read_packet(), ico_write_header(), id3v2_parse(), idcin_read_packet(), iff_read_header(), iff_read_packet(), ingenient_read_packet(), init_stream(), ircam_read_header(), ivr_read_header(), ivr_read_packet(), lmlm4_read_packet(), lvf_read_header(), lvf_read_packet(), lxf_read_header(), matroska_parse_tracks(), mmf_read_header(), mov_metadata_loci(), mov_parse_stsd_data(), mov_parse_stsd_video(), mov_read_ares(), mov_read_chan(), mov_read_covr(), mov_read_custom(), mov_read_default(), mov_read_dref(), mov_read_keys(), mov_read_moov(), mov_read_mvhd(), mov_read_rtmd_track(), mov_read_st3d(), mov_read_strf(), mov_read_sv3d(), mov_read_uuid(), mov_read_wave(), mov_read_wide(), mov_skip_multiple_stsd(), mov_write_header(), mp3_parse_info_tag(), mp3_parse_vbri_tag(), mpc8_handle_chunk(), mpc8_read_header(), mpegps_psm_parse(), mpegps_read_dts(), mpegps_read_packet(), mpegps_read_pes_header(), msf_read_header(), msnwc_tcp_read_packet(), mtaf_read_header(), mtv_read_header(), mtv_read_packet(), musx_read_header(), mv_read_header(), mv_read_packet(), mxf_decrypt_triplet(), mxf_read_header(), mxf_read_index_entry_array(), mxf_read_packet_old(), mxf_read_partition_pack(), mxf_read_random_index_pack(), mxf_read_strong_ref_array(), nc_read_packet(), nist_read_header(), nsv_read_chunk(), nut_read_packet(), nuv_header(), nuv_packet(), nuv_read_dts(), ogg_read_page(), ogg_replace_stream(), parse_chunks(), parse_dsd_diin(), parse_dsd_prop(), parse_global_var(), parse_media_type(), parse_video_info(), parse_video_var(), parse_videoinfoheader2(), pmp_header(), pmp_packet(), process_audio_header_eacs(), process_ea_header(), process_ipmovie_chunk(), process_video_header_cmv(), process_video_header_mdec(), process_video_header_vp6(), pvf_read_header(), qcp_read_header(), qcp_read_packet(), qt_rtp_parse_packet(), r3d_read_packet(), r3d_read_red1(), r3d_read_reos(), rdt_load_mdpr(), read_chapter(), read_dst_frame(), read_gab2_sub(), read_header(), read_index(), read_kuki_chunk(), read_packet(), read_pakt_chunk(), read_part_of_packet(), read_sm_data(), read_string(), read_table(), rl2_read_header(), rm_read_audio_stream_info(), rm_read_dts(), rm_read_header(), rm_read_index(), rm_sync(), roq_read_packet(), rpl_read_packet(), rsd_read_header(), scan_file(), sdr2_read_header(), sdr2_read_packet(), set_spdif(), siff_parse_soun(), siff_parse_vbv1(), siff_read_header(), smjpeg_read_header(), smush_read_header(), smush_read_packet(), sol_read_header(), sox_read_header(), svag_read_header(), swf_read_header(), swf_read_packet(), tak_read_header(), threedostr_read_header(), threedostr_read_packet(), tmv_read_packet(), tta_read_header(), txd_read_packet(), update_odml_entry(), vag_read_header(), var_read_string(), vc1t_read_header(), vid_read_header(), vivo_read_header(), vivo_read_packet(), voc_read_header(), vpk_read_header(), vpk_read_packet(), vqf_read_header(), wc3_read_header(), wc3_read_packet(), write_metadata(), wsd_read_header(), wsvqa_read_header(), wsvqa_read_packet(), wv_read_block_header(), wv_read_header(), wve_read_header(), xa_read_header(), xmv_read_header(), xvag_read_header(), xwma_read_header(), yop_read_header(), and yop_read_packet().
avio_tell()
static av_always_inline int64_t avio_tell (AVIOContext * s) static
ftell() equivalent for AVIOContext.
Returns
position or AVERROR.
Definition at line 511 of file avio.h.
Referenced by adjust_write_index(), adts_aac_read_header(), adx_read_packet(), afc_read_packet(), aiff_read_header(), aiff_read_packet(), aiff_write_header(), aiff_write_trailer(), aix_read_packet(), align_position(), amf_parse_object(), amr_read_packet(), ape_read_header(), apng_read_header(), aqt_read_header(), asf_build_simple_index(), asf_get_packet(), asf_parse_packet(), asf_read_data(), asf_read_frame_header(), asf_read_header(), asf_read_multiple_payload(), asf_read_packet(), asf_read_packet_header(), asf_read_single_payload(), asf_read_stream_properties(), asf_read_subpayload(), asf_read_timestamp(), asf_write_header1(), asf_write_packet(), asf_write_trailer(), asfrtp_parse_packet(), ast_read_packet(), ast_write_header(), ast_write_trailer(), av_demuxer_open(), av_get_packet(), avformat_find_stream_info(), avformat_open_input(), avi_add_ientry(), avi_load_index(), avi_read_header(), avi_read_idx1(), avi_read_nikon(), avi_read_packet(), avi_sync(), avi_write_counters(), avi_write_header(), avi_write_ix(), avi_write_packet(), avi_write_packet_internal(), avi_write_trailer(), avs_read_audio_packet(), caf_write_header(), caf_write_trailer(), cdxl_read_packet(), close_file(), dash_flush(), dcstr_read_header(), decode_frame(), decode_frame_header(), decode_info_header(), decode_main_header(), decode_stream_header(), decode_syncpoint(), detect_unknown_subobject(), dsf_read_header(), dsf_read_packet(), dss_723_1_read_packet(), dss_sp_read_packet(), dtshd_read_header(), dv_read_header(), dv_read_packet(), dv_read_timecode(), dxa_read_header(), dxa_read_packet(), ebml_level_end(), ebml_parse_elem(), ebml_read_binary(), ebml_read_master(), ebml_read_num(), end_ebml_master(), end_header(), event_loop(), ff_end_tag(), ff_id3v1_read(), ff_id3v2_finish(), ff_id3v2_start(), ff_img_read_packet(), ff_mov_cenc_write_sinf_tag(), ff_mov_read_stsd_entries(), ff_mov_write_packet(), ff_put_wav_header(), ff_raw_read_partial_packet(), ff_read_riff_info(), ff_rm_read_mdpr_codecdata(), ff_spdif_read_packet(), ff_start_tag(), ff_text_pos(), ff_voc_get_packet(), ff_wms_parse_sdp_a_line(), ffio_limit(), ffm2_read_header(), ffm_is_avail_data(), ffm_read_data(), ffm_read_header(), ffm_read_packet(), ffm_write_header(), find_and_decode_index(), find_sidx(), find_startcode(), finish_chunk_noindex(), finish_file(), flac_read_header(), flac_write_trailer(), flic_read_packet(), flush_packet(), flv_read_packet(), flv_write_codec_header(), flv_write_header(), flv_write_packet(), flv_write_trailer(), force_one_stream(), fourxm_read_packet(), fsb_read_header(), fsb_read_packet(), g723_1_read_packet(), genh_read_header(), get_attachment(), get_pcr(), get_riff(), get_tag(), gif_read_packet(), gsm_read_packet(), guess_ni_flag(), gxf_read_timestamp(), gxf_resync_media(), gxf_write_eos_packet(), gxf_write_flt_packet(), gxf_write_map_packet(), gxf_write_material_data_section(), gxf_write_packet(), gxf_write_track_description(), gxf_write_track_description_section(), gxf_write_trailer(), gxf_write_umf_media_description(), gxf_write_umf_packet(), gxf_write_umf_track_description(), handle_packet(), handle_packets(), hls_write_packet(), hls_write_trailer(), hnm_read_packet(), ico_write_packet(), id3v2_parse(), id3v2_read_internal(), idcin_read_header(), iff_read_header(), iff_read_packet(), ilbc_read_packet(), ipmovie_read_header(), iss_read_header(), iss_read_packet(), ivf_write_trailer(), ivr_read_header(), ivr_read_packet(), jacosub_read_header(), jpeg_parse_packet(), klv_read_packet(), lvf_read_header(), lvf_read_packet(), matroska_parse_cluster(), matroska_parse_cluster_incremental(), matroska_parse_seekhead_entry(), matroska_read_header(), matroska_read_packet(), microdvd_read_header(), mkv_check_new_extra_data(), mkv_start_new_cluster(), mkv_start_seekhead(), mkv_write_attachments(), mkv_write_block(), mkv_write_chapters(), mkv_write_cues(), mkv_write_flush_packet(), mkv_write_header(), mkv_write_packet(), mkv_write_packet_internal(), mkv_write_seekhead(), mkv_write_tag_targets(), mkv_write_tags(), mkv_write_track(), mkv_write_tracks(), mkv_write_trailer(), mkv_write_vtt_blocks(), mmf_rate(), mmf_read_header(), mmf_read_packet(), mov_add_tfra_entries(), mov_cenc_write_saio_tag(), mov_cenc_write_saiz_tag(), mov_cenc_write_schi_tag(), mov_cenc_write_senc_tag(), mov_flush_fragment(), mov_flush_fragment_interleaving(), mov_parse_stsd_video(), mov_read_chapters(), mov_read_custom(), mov_read_default(), mov_read_dref(), mov_read_header(), mov_read_mfra(), mov_read_moof(), mov_read_rtmd_track(), mov_read_sidx(), mov_read_timecode_track(), mov_switch_root(), mov_write_3gp_udta_tag(), mov_write_audio_tag(), mov_write_avcc_tag(), mov_write_chan_tag(), mov_write_chpl_tag(), mov_write_dfla_tag(), mov_write_dinf_tag(), mov_write_esds_tag(), mov_write_ftyp_tag(), mov_write_gmhd_tag(), mov_write_hdlr_tag(), mov_write_header(), mov_write_hvcc_tag(), mov_write_ilst_tag(), mov_write_iods_tag(), mov_write_isml_manifest(), mov_write_loci_tag(), mov_write_mdat_tag(), mov_write_mdia_tag(), mov_write_mdta_ilst_tag(), mov_write_mdta_keys_tag(), mov_write_meta_tag(), mov_write_mfra_tag(), mov_write_minf_tag(), mov_write_moof_tag_internal(), mov_write_moov_tag(), mov_write_ms_tag(), mov_write_mvex_tag(), mov_write_rtp_tag(), mov_write_sidx_tag(), mov_write_source_reference_tag(), mov_write_stbl_tag(), mov_write_stco_tag(), mov_write_string_tag(), mov_write_stsc_tag(), mov_write_stsd_tag(), mov_write_stss_tag(), mov_write_stsz_tag(), mov_write_subtitle_tag(), mov_write_tapt_tag(), mov_write_tcmi_tag(), mov_write_tfdt_tag(), mov_write_tfhd_tag(), mov_write_tfra_tag(), mov_write_tfrf_tags(), mov_write_tfxd_tag(), mov_write_tmcd_tag(), mov_write_track_metadata(), mov_write_traf_tag(), mov_write_trailer(), mov_write_trak_tag(), mov_write_trun_tag(), mov_write_uuidusmt_tag(), mov_write_video_tag(), mov_write_vpcc_tag(), mov_write_wave_tag(), mov_write_wfex_tag(), mp3_parse_info_tag(), mp3_read_header(), mp3_read_packet(), mp3_write_xing(), mp4_read_iods(), mp4_read_od(), mpc8_get_chunk_header(), mpc8_handle_chunk(), mpc8_read_header(), mpc8_read_packet(), mpc_read_header(), mpc_read_packet(), mpegps_read_header(), mpegps_read_pes_header(), mpegts_get_pcr(), mpegts_raw_read_packet(), mpegts_read_header(), mpegts_resync(), mpjpeg_read_header(), mpjpeg_read_packet(), mpl2_read_header(), mpsub_read_header(), msf_read_header(), mtv_read_packet(), mv_read_packet(), mxf_decrypt_triplet(), mxf_parse_handle_essence(), mxf_parse_klv(), mxf_read_header(), mxf_read_local_tags(), mxf_read_packet_old(), mxf_read_partition_pack(), mxf_write_d10_video_packet(), mxf_write_footer(), mxf_write_klv_fill(), mxf_write_partition(), mxf_write_random_index_pack(), need_output(), nist_read_header(), nsv_parse_NSVf_header(), nsv_resync(), nut_read_header(), nut_read_packet(), nut_write_packet(), nuv_packet(), nuv_read_dts(), nuv_resync(), ogg_read_page(), ogg_read_timestamp(), ogg_replace_stream(), ogg_reset(), ogg_save(), ogg_update_checksum(), ogg_write_page(), oma_read_header(), oma_read_packet(), oma_read_seek(), parse_chunks(), parse_dsd_diin(), parse_dsd_prop(), parse_file(), parse_fragment(), parse_keyframes_index(), parse_playlist(), pjs_read_header(), pmp_header(), print_report(), process_ea_header(), process_ipmovie_chunk(), put_ebml_void(), put_header(), put_id3v2_tags(), put_payload_parsing_info(), put_swf_end_tag(), put_swf_tag(), pva_read_timestamp(), qcp_read_packet(), qt_rtp_parse_packet(), r3d_read_header(), r3d_read_reda(), r3d_read_redv(), raw_read_packet(), rdt_parse_packet(), read_apic(), read_atom(), read_braindead_odml_indx(), read_dst_frame(), read_frame(), read_header(), read_kuki_chunk(), read_line(), read_moof_duration(), read_packet(), read_pakt_chunk(), read_part_of_packet(), read_sm_data(), read_tfra(), read_trun_duration(), reanalyze(), resync(), rm_assemble_video_frame(), rm_read_audio_stream_info(), rm_read_header(), rm_read_index(), rm_read_packet(), rm_sync(), rm_write_trailer(), roq_read_packet(), rsd_read_header(), rsd_read_packet(), rso_write_trailer(), scan_file(), sdr2_read_packet(), set_spdif(), shift_data(), skip_reserved(), skip_tag(), smacker_read_header(), smacker_read_packet(), smjpeg_read_packet(), smjpeg_write_trailer(), sox_write_trailer(), start_ebml_master(), stl_read_header(), str_read_packet(), subviewer1_read_header(), subviewer_read_header(), sup_read_packet(), svag_read_header(), swf_read_packet(), swf_write_header(), swf_write_trailer(), swf_write_video(), tak_read_header(), tedcaptions_read_header(), threedostr_read_packet(), tta_read_header(), update_odml_entry(), update_offsets(), update_size(), updatePacketSize(), updateSize(), vmd_read_packet(), vp8_handle_packet(), vpk_read_header(), vplayer_read_header(), vqf_read_packet(), webm_clusters_start_with_keyframe(), webm_dash_manifest_cues(), webm_dash_manifest_read_header(), webp_write_trailer(), webvtt_read_header(), write_abst(), write_chunk_header(), write_fat_sector(), write_fragments(), write_header(), write_hint_packets(), write_index(), write_metadata(), write_root_table(), write_stream_codec_info(), write_trailer(), wv_read_block_header(), wv_read_header(), wv_write_trailer(), xmv_process_packet_header(), xmv_read_header(), xvag_read_header(), xwma_read_header(), xwma_read_packet(), yop_read_packet(), yuv4_read_header(), and yuv4_read_packet().
avio_size()
int64_t avio_size (AVIOContext * s)
Get the filesize.
Returns
filesize or AVERROR
Definition at line 309 of file aviobuf.c.
Referenced by adp_read_header(), ape_read_header(), apng_read_header(), asf_read_stream_properties(), av_seek(), avi_read_header(), avio_tell(), cdxl_read_header(), dv_frame_offset(), estimate_timings(), estimate_timings_from_bit_rate(), estimate_timings_from_pts(), event_loop(), ff_ape_parse_tag(), ff_find_last_ts(), ff_id3v1_read(), ff_img_read_packet(), ff_sauce_read(), ff_voc_get_packet(), ffio_limit(), ffm2_read_header(), ffm_read_header(), find_and_decode_index(), flv_read_packet(), gxf_write_material_data_section(), import_pem(), init_stream(), main(), modplug_read_header(), mov_read_default(), mov_read_header(), mov_read_mfra(), mov_read_sidx(), mp3_parse_info_tag(), mp3_read_header(), mp3_seek(), mxf_read_random_index_pack(), ogg_get_length(), open_output_file(), pmp_header(), print_report(), r3d_read_header(), read_header(), read_header_gme(), read_header_openmpt(), read_mfra(), read_xing_toc(), rm_read_index(), rsd_read_header(), seek_frame_byte(), set_spdif(), show_format(), thp_read_header(), update_init_section(), update_stream_timings(), wtvfile_open_sector(), yop_read_seek(), and yuv4_read_header().
avio_feof()
int avio_feof (AVIOContext * s)
feof() equivalent for AVIOContext.
Returns
non zero if and only if end of file
Definition at line 328 of file aviobuf.c.
Referenced by adp_read_packet(), aix_read_packet(), amr_read_packet(), ape_read_packet(), apng_read_header(), aqt_read_header(), asf_build_simple_index(), asf_get_packet(), asf_parse_packet(), asf_read_header(), ast_read_packet(), avi_load_index(), avi_read_header(), avi_read_idx1(), avi_read_nikon(), avi_sync(), avio_read(), avio_tell(), bfi_read_packet(), cdxl_read_packet(), cin_read_frame_header(), daud_packet(), dfa_read_packet(), dtshd_read_header(), dv_read_header(), dxa_read_header(), dxa_read_packet(), ea_read_packet(), ebml_read_num(), ff_get_line(), ff_img_read_packet(), ff_read_riff_info(), ff_spdif_read_packet(), ff_text_eof(), ff_text_peek_r8(), ffio_read_partial(), ffm2_read_header(), ffm_resync(), find_any_startcode(), find_next_start_code(), flac_read_header(), flv_read_packet(), fourxm_read_packet(), fsb_read_packet(), genh_read_packet(), get_codec_data(), get_line(), get_swf_tag(), get_tag(), gif_read_packet(), gxf_packet(), hls_read_packet(), idcin_read_packet(), iff_read_header(), iff_read_packet(), ipmovie_read_header(), ivr_read_header(), ivr_read_packet(), jacosub_read_header(), lrc_read_header(), lvf_read_header(), lvf_read_packet(), lxf_sync(), matroska_resync(), microdvd_read_header(), mmf_read_packet(), mov_read_default(), mov_read_dref(), mov_switch_root(), mpc8_read_header(), mpc8_read_packet(), mpegps_read_pes_header(), mpegts_resync(), mpl2_read_header(), mpsub_read_header(), msnwc_tcp_read_header(), mxf_read_header(), mxf_read_local_tags(), mxf_read_packet_old(), mxf_read_sync(), mxg_read_packet(), nc_read_packet(), nist_read_header(), nsv_parse_NSVf_header(), nsv_read_chunk(), nsv_resync(), nut_read_packet(), nuv_packet(), nuv_read_dts(), nuv_resync(), ogg_read_page(), parse_chunks(), parse_dsd_diin(), parse_dsd_prop(), parse_legacy_attrib(), parse_playlist(), pjs_read_header(), pmp_header(), pmp_packet(), process_audio_header_elements(), process_ipmovie_chunk(), qcp_read_packet(), read_braindead_odml_indx(), read_dst_frame(), read_header(), read_info_chunk(), read_line(), read_packet(), read_thread(), redspark_read_packet(), resync(), rm_read_header(), rm_read_packet(), rm_sync(), roq_read_packet(), rsd_read_packet(), scan_file(), set_spdif(), should_retry(), smacker_read_packet(), smjpeg_read_header(), smjpeg_read_packet(), smush_read_header(), smush_read_packet(), sol_read_packet(), stl_read_header(), str_read_packet(), subviewer1_read_header(), subviewer_read_header(), sup_read_packet(), tak_read_header(), threedostr_read_header(), threedostr_read_packet(), tmv_read_packet(), txd_read_packet(), vc1t_read_packet(), vid_read_packet(), vivo_get_packet_header(), vivo_read_packet(), vplayer_read_header(), vqf_read_header(), wc3_read_header(), wc3_read_packet(), wtvfile_read_packet(), wv_read_block_header(), and wv_read_packet().
avio_printf()
int avio_printf (AVIOContext * s, const char * fmt, ...)
Warning
Writes up to 4 KiB per call
Referenced by avio_tell(), choose_pix_fmts(), compute_status(), ff_framehash_write_header(), fmt_bytecount(), framecrc_write_header(), hls_window(), lrc_write_header(), lrc_write_packet(), microdvd_write_packet(), mkv_write_vtt_blocks(), mov_write_isml_manifest(), mpjpeg_write_header(), mpjpeg_write_packet(), output_chunk_list(), output_segment_list(), param_write_hex(), param_write_int(), param_write_string(), print_sdp(), print_stream_params(), purge_dialogues(), rtsp_cmd_describe(), rtsp_cmd_interrupt(), rtsp_cmd_options(), rtsp_cmd_play(), rtsp_cmd_setup(), rtsp_reply_error(), rtsp_reply_header(), segment_end(), segment_list_open(), segment_list_print_entry(), srt_write_packet(), webm_dash_manifest_write_header(), webvtt_write_header(), webvtt_write_packet(), webvtt_write_time(), write_adaptation_set(), write_footer(), write_header(), write_manifest(), write_representation(), write_time(), write_trailer(), and yuv4_write_packet().
avio_flush()
int void avio_flush (AVIOContext * s)
Force flushing of buffered data.
For write streams, force the buffered data to be immediately written to the output, without to wait to fill the internal buffer.
For read streams, discard all currently buffered data, and advance the reported file position to that of the underlying stream. This does not read new data, and does not perform any seeks.
Examples:
http_multiclient.c.
Definition at line 224 of file aviobuf.c.
Referenced by aiff_write_header(), aiff_write_trailer(), asf_write_header(), asf_write_trailer(), ast_write_header(), ast_write_trailer(), av_write_frame(), av_write_trailer(), avi_write_header(), avio_close(), avio_close_dyn_buf(), avio_tell(), avio_write(), avio_write_marker(), caf_write_header(), caf_write_trailer(), close_file(), copy_moof(), dash_flush(), dash_init(), dump_attachment(), ff_framehash_write_header(), ff_rtp_check_and_send_back_rr(), ff_rtp_send_data(), ff_rtp_send_punch_packets(), ff_rtp_send_rtcp_feedback(), ffio_close_null_buf(), ffm_write_header(), flac_write_trailer(), flush_packet(), gif_image_write_header(), gxf_write_header(), gxf_write_trailer(), hds_flush(), hds_write_header(), ico_write_header(), ilbc_write_header(), ism_flush(), ism_write_header(), jacosub_write_header(), main(), microdvd_write_header(), mkv_start_new_cluster(), mkv_write_flush_packet(), mkv_write_header(), mmf_rate(), mov_flush_fragment(), mov_write_header(), mpjpeg_write_header(), mxf_write_opatom_packet(), mxf_write_packet(), mxf_write_partition(), nut_write_header(), ogg_write_page(), print_report(), process_client(), put_vcd_padding_sector(), rm_write_header(), roq_write_header(), rso_write_header(), rtcp_send_sr(), segment_end(), shift_data(), smjpeg_write_header(), sox_write_header(), sox_write_trailer(), swf_write_header(), tta_write_trailer(), update_odml_entry(), vc1test_write_trailer(), webvtt_write_header(), write_fragment(), write_header(), write_header_internal(), write_manifest(), write_packet(), and write_trailer().
avio_read()
int avio_read (AVIOContext * s, unsigned char * buf, int size)
Read size bytes from AVIOContext into buf.
Returns
number of bytes read or AVERROR
Examples:
http_multiclient.c.
Definition at line 604 of file aviobuf.c.
Referenced by aa_read_header(), aa_read_packet(), acm_read_header(), add_metadata(), amf_get_string(), amr_read_header(), amr_read_packet(), ape_read_header(), ape_read_packet(), ape_tag_read_field(), apng_read_header(), append_extradata(), append_packet_chunked(), asf_parse_packet(), asf_read_multiple_payload(), asf_read_single_payload(), asf_read_stream_properties(), asf_read_value(), av_probe_input_buffer2(), av_read(), avi_read_header(), avi_read_nikon(), avi_read_tag(), avio_read_to_bprint(), avio_tell(), avs_read_packet(), avs_read_video_packet(), bfi_read_header(), bmv_read_packet(), cdxl_read_packet(), check(), check_file_header(), check_tag(), cin_read_packet(), copy_moof(), copy_tag(), decode_frame(), decode_main_header(), dss_723_1_read_packet(), dss_read_metadata_date(), dss_read_metadata_string(), dss_read_seek(), dss_sp_read_packet(), dtshd_read_header(), dv_read_header(), dv_read_packet(), dv_read_timecode(), dxa_read_packet(), ebml_read_ascii(), ebml_read_binary(), ff_ape_parse_tag(), ff_flac_parse_picture(), ff_get_extradata(), ff_get_guid(), ff_id3v1_read(), ff_img_read_header(), ff_img_read_packet(), ff_read_riff_info(), ff_rtsp_open_transport_ctx(), ff_sauce_read(), ff_spdif_read_packet(), ffio_read_indirect(), ffio_read_size(), ffm2_read_header(), ffm_read_data(), ffm_read_header(), film_read_header(), find_index_range(), flac_read_header(), flic_read_header(), flic_read_packet(), flv_queue_extradata(), fourxm_read_header(), fourxm_read_packet(), fsb_read_header(), g723_1_read_packet(), genh_read_header(), get_meta(), get_metadata(), get_packet_header(), get_pts(), get_riff(), get_str(), get_tag(), gif_read_ext(), gif_read_packet(), hls_encryption_start(), id3v2_parse(), id3v2_read_internal(), idcin_read_packet(), iff_read_header(), ilbc_read_header(), ilbc_read_packet(), import_pem(), init_stream(), ipmovie_read_header(), klv_read_packet(), load_ipmovie_packet(), lxf_read_header(), lxf_read_packet(), lxf_sync(), main(), modplug_read_header(), mov_read_adrm(), mov_read_ddts(), mov_read_default(), mov_read_dfla(), mov_read_free(), mov_read_keys(), mov_read_saiz(), mov_read_senc(), mov_read_uuid(), mov_read_wave(), mp3_parse_info_tag(), mpc8_parse_seektable(), mpc_read_packet(), mpegps_read_packet(), mpegps_read_pes_header(), mpegts_get_pcr(), mpegts_raw_read_packet(), mpegts_read_header(), mxf_decrypt_triplet(), mxf_read_cryptographic_context(), mxf_read_generic_descriptor(), mxf_read_indirect_value(), mxf_read_local_tags(), mxf_read_package(), mxf_read_partition_pack(), mxf_read_primer_pack(), mxf_read_pulldown_component(), mxf_read_sequence(), mxf_read_source_clip(), mxf_read_strong_ref_array(), mxf_read_track(), mxg_update_cache(), next_byte(), nsv_parse_NSVf_header(), nuv_header(), nuv_packet(), nuv_read_dts(), ogg_read_page(), ogg_replace_stream(), oma_read_header(), oma_read_seek(), open_input(), open_output_file(), parse_chunks(), parse_fragment(), parse_MP4DecConfigDescrTag(), parse_video_info(), process_client(), process_ipmovie_chunk(), qcp_read_header(), r3d_read_red1(), read_apic(), read_chapter(), read_file(), read_frame(), read_from_url(), read_geobtag(), read_header(), read_header_gme(), read_header_openmpt(), read_kuki_chunk(), read_packet(), read_part_of_packet(), read_priv(), read_sm_data(), read_string(), read_table(), read_uslt(), read_whole_file(), readfull(), rm_assemble_video_frame(), rm_read_audio_stream_info(), roq_read_header(), roq_read_packet(), rsd_read_header(), sdr2_read_packet(), seq_fill_buffer(), seq_read_packet(), set_spdif(), shift_data(), siff_read_packet(), smacker_read_header(), smacker_read_packet(), smjpeg_read_header(), sox_read_header(), str_read_header(), str_read_packet(), swf_probe(), swf_read_packet(), tak_read_header(), thp_read_header(), tta_read_header(), vid_read_packet(), vivo_read_header(), vmd_read_header(), vmd_read_packet(), vpk_read_packet(), vqf_read_header(), vqf_read_packet(), wc3_read_header(), wc3_read_packet(), wsaud_read_header(), wsaud_read_packet(), wsvqa_read_header(), wsvqa_read_packet(), wtvfile_read_packet(), wv_read_block_header(), wv_read_packet(), xmv_process_packet_header(), yop_read_header(), and yop_read_packet().
avio_r8()
int avio_r8 (AVIOContext * s)
Definition at line 595 of file aviobuf.c.
Referenced by aea_read_header(), aix_read_header(), aix_read_packet(), amf_parse_object(), amf_skip_tag(), amr_read_packet(), ape_read_header(), ape_tag_read_field(), asf_get_packet(), asf_parse_packet(), asf_read_frame_header(), asf_read_header(), asf_read_language_list(), asf_read_marker(), asf_read_packet_header(), asf_read_payload(), asf_read_picture(), asf_read_stream_properties(), asf_read_subpayload(), asfrtp_parse_packet(), avi_read_header(), avi_sync(), avio_get_str(), avio_rb16(), avio_rb24(), avio_rl16(), avio_rl24(), avio_tell(), avs_read_packet(), bfi_read_packet(), bmv_read_packet(), cdata_read_header(), cin_read_file_header(), cin_read_frame_header(), decode_fctl_chunk(), decode_str(), dss_723_1_read_packet(), dss_read_header(), dv_read_header(), dxa_read_header(), ebml_read_num(), ebml_read_sint(), ebml_read_uint(), efi_read(), ff_get_line(), ff_get_qtpalette(), ff_mp4_parse_es_descr(), ff_mp4_read_dec_config_descr(), ff_mp4_read_descr(), ff_mp4_read_descr_len(), ff_sauce_read(), ff_spdif_read_packet(), ff_text_init_avio(), ff_text_r8(), ff_voc_get_packet(), ffio_read_varlen(), ffm2_read_header(), ffm_read_header(), ffm_resync(), find_any_startcode(), find_next_start_code(), flv_data_packet(), flv_read_header(), flv_read_metabody(), flv_read_packet(), flv_set_video_codec(), frm_read_header(), fsb_read_header(), fsb_read_packet(), g723_1_read_packet(), genh_read_packet(), get_attachment(), get_codec_data(), get_line(), get_pts(), get_size(), get_str(), get_str8(), get_strl(), get_token(), gif_read_ext(), gif_read_packet(), gif_skip_subblocks(), guess_ni_flag(), gxf_header(), gxf_material_tags(), gxf_packet(), gxf_resync_media(), gxf_track_tags(), id3v2_parse(), iff_read_header(), init_stream(), ipmovie_read_header(), ivr_read_header(), ivr_read_packet(), klv_decode_ber_length(), lvf_read_header(), lxf_sync(), matroska_resync(), mmf_read_header(), mov_metadata_gnre(), mov_metadata_int8_bypass_padding(), mov_metadata_int8_no_padding(), mov_parse_stsd_video(), mov_read_chpl(), mov_read_colr(), mov_read_ctts(), mov_read_dfla(), mov_read_dref(), mov_read_dvc1(), mov_read_elst(), mov_read_hdlr(), mov_read_mac_string(), mov_read_mdhd(), mov_read_mvhd(), mov_read_rtmd_track(), mov_read_saiz(), mov_read_sbgp(), mov_read_senc(), mov_read_sidx(), mov_read_st3d(), mov_read_stco(), mov_read_stsc(), mov_read_stsd(), mov_read_stss(), mov_read_stsz(), mov_read_stts(), mov_read_sv3d(), mov_read_tfdt(), mov_read_tfhd(), mov_read_tkhd(), mov_read_trex(), mov_read_trun(), mov_read_udta_string(), mp3_parse_info_tag(), mpc8_read_header(), mpc_read_header(), mpegps_psm_parse(), mpegps_read_packet(), mpegps_read_pes_header(), mpegts_resync(), msnwc_tcp_read_header(), mtaf_read_header(), mtv_read_header(), mxf_read_generic_descriptor(), mxf_read_index_entry_array(), mxf_read_pixel_layout(), mxf_read_sequence(), mxf_read_sync(), mxf_read_timecode_component(), nc_read_packet(), nsv_parse_NSVs_header(), nsv_read_chunk(), nsv_resync(), nut_read_packet(), nuv_header(), nuv_resync(), ogg_read_page(), parse_chunks(), parse_dsd_prop(), parse_keyframes_index(), parse_MP4IODescrTag(), parse_MP4SLDescrTag(), parse_packet_header(), pmp_packet(), process_audio_header_eacs(), process_audio_header_elements(), qcp_read_header(), qcp_read_packet(), r3d_read_red1(), r3d_read_reda(), r3d_read_redv(), read_apic(), read_arbitrary(), read_braindead_odml_indx(), read_comment(), read_frame(), read_geobtag(), read_header(), read_line(), read_moof_duration(), read_part_of_packet(), read_tfra(), read_trun_duration(), read_ttag(), read_uint8(), read_uslt(), read_xing_toc(), resync(), rm_assemble_video_frame(), rm_read_audio_stream_info(), rm_read_dts(), rm_read_metadata(), rm_sync(), rsd_read_header(), rsd_read_packet(), seq_parse_frame_data(), set_spdif(), skip_reserved(), smacker_read_header(), smacker_read_packet(), smjpeg_read_header(), sol_read_header(), swf_read_header(), swf_read_packet(), tak_read_header(), tmv_read_header(), vc1t_read_header(), vc1t_read_packet(), vid_read_packet(), vivo_get_packet_header(), wsd_read_header(), wv_read_block_header(), yop_read_header(), yuv4_read_header(), and yuv4_read_packet().
avio_rl16()
unsigned int avio_rl16 (AVIOContext * s)
Definition at line 710 of file aviobuf.c.
Referenced by ape_read_header(), asf_build_simple_index(), asf_get_packet(), asf_read_content_desc(), asf_read_ext_content(), asf_read_ext_content_desc(), asf_read_ext_stream_properties(), asf_read_frame_header(), asf_read_generic_value(), asf_read_language_list(), asf_read_marker(), asf_read_metadata(), asf_read_metadata_obj(), asf_read_multiple_payload(), asf_read_stream_properties(), asf_read_subpayload(), avi_read_header(), avi_read_nikon(), avi_sync(), avio_rl24(), avio_rl32(), avio_tell(), avs_read_header(), avs_read_packet(), cin_read_file_header(), cin_read_frame_header(), cine_read_header(), decode_str(), dfa_read_header(), ff_get_bmp_header(), ff_get_wav_header(), ff_sauce_read(), ff_spdif_read_packet(), ff_text_r8(), ff_voc_get_packet(), ffm2_read_header(), ffm_read_header(), frm_read_header(), fsb_read_header(), get_asf_string(), get_fourcc(), get_swf_tag(), get_tag(), get_value(), gif_read_ext(), gif_read_header(), guess_ni_flag(), hnm_read_header(), hnm_read_packet(), ingenient_read_packet(), init_stream(), lvf_read_header(), mpc8_get_chunk_header(), msnwc_tcp_read_packet(), mtv_read_header(), nc_read_packet(), nsv_parse_NSVs_header(), nsv_read_chunk(), parse_video_info(), parse_waveformatex(), pmp_header(), process_ea_header(), process_video_header_cmv(), process_video_header_mdec(), qcp_read_header(), qt_rtp_parse_packet(), read16(), read_braindead_odml_indx(), read_frame(), read_gab2_sub(), read_header(), read_packet(), read_uint16(), rl2_read_header(), scan_file(), seq_init_frame_buffers(), seq_parse_frame_data(), set_spdif(), siff_parse_soun(), siff_parse_vbv1(), siff_read_packet(), smush_read_header(), sol_read_header(), swf_read_header(), swf_read_packet(), tmv_read_header(), tta_read_header(), vid_read_header(), vid_read_packet(), voc_read_header(), wv_read_block_header(), xa_read_header(), xmv_read_header(), and yop_read_header().
avio_rl24()
unsigned int avio_rl24 (AVIOContext * s)
Definition at line 718 of file aviobuf.c.
Referenced by avio_tell(), bmv_read_packet(), ff_voc_get_packet(), hnm_read_packet(), mpc_read_header(), mtv_read_header(), read_comment(), read_header(), set_spdif(), smacker_read_header(), tak_read_header(), vc1t_read_header(), vc1t_read_packet(), and wv_read_block_header().
avio_rl32()
unsigned int avio_rl32 (AVIOContext * s)
Definition at line 726 of file aviobuf.c.
Referenced by ads_read_header(), aiff_read_header(), aix_read_header(), aix_read_packet(), apc_read_header(), ape_read_header(), ape_tag_read_field(), apng_read_header(), apng_read_packet(), asf_build_simple_index(), asf_get_packet(), asf_read_ext_stream_properties(), asf_read_file_properties(), asf_read_frame_header(), asf_read_generic_value(), asf_read_header(), asf_read_marker(), asf_read_metadata(), asf_read_metadata_obj(), asf_read_packet_header(), asf_read_picture(), asf_read_properties(), asf_read_replicated_data(), asf_read_simple_index(), asf_read_single_payload(), asf_read_stream_properties(), ast_read_packet(), avi_load_index(), avi_read_header(), avi_read_idx1(), avi_read_nikon(), avio_rl64(), avio_tell(), avs_read_header(), bfi_read_header(), bfi_read_packet(), check_file_header(), cin_read_file_header(), cin_read_frame_header(), cine_read_header(), cine_read_packet(), dcstr_read_header(), dfa_read_header(), dsf_read_header(), dxa_read_header(), ea_read_packet(), epaf_read_header(), ff_ape_parse_tag(), ff_get_bmp_header(), ff_get_wav_header(), ff_mov_read_chan(), ff_mov_read_stsd_entries(), ff_read_riff_info(), ff_rm_read_mdpr_codecdata(), ff_voc_get_packet(), ffm_read_header(), flac_read_header(), fourxm_read_packet(), fsb_read_header(), genh_read_header(), get_aiff_header(), get_attachment(), get_codec_data(), get_fourcc(), get_riff(), get_swf_tag(), get_tag(), get_value(), guess_ni_flag(), gxf_header(), gxf_read_index(), hnm_read_header(), idcin_read_header(), idcin_read_packet(), iff_read_header(), iff_read_packet(), ingenient_read_packet(), ircam_read_header(), ivr_read_header(), lvf_read_header(), lvf_read_packet(), mmf_read_header(), mov_read_cmov(), mov_read_custom(), mov_read_default(), mov_read_dref(), mov_read_frma(), mov_read_glbl(), mov_read_hdlr(), mov_read_keys(), mov_read_meta(), mov_read_sbgp(), mov_read_sv3d(), mov_read_udta_string(), mov_read_wide(), mpc8_read_header(), mpc_read_header(), mpc_read_packet(), msnwc_tcp_read_packet(), mtaf_read_header(), mtv_read_header(), musx_read_header(), nsv_parse_NSVf_header(), nsv_parse_NSVs_header(), nsv_read_chunk(), nuv_header(), ogg_read_page(), parse_chunks(), parse_dsd_diin(), parse_dsd_prop(), parse_fragment(), parse_legacy_attrib(), parse_video_info(), parse_waveformatex(), pmp_header(), pmp_packet(), process_audio_header_eacs(), process_audio_header_sead(), process_ea_header(), process_video_header_vp6(), qcp_read_header(), qcp_read_packet(), qt_rtp_parse_packet(), rdt_load_mdpr(), read32(), read_atom(), read_braindead_odml_indx(), read_desc_chunk(), read_dst_frame(), read_gab2_sub(), read_header(), read_ints(), read_packet(), read_table(), read_uint32(), rl2_read_header(), rm_read_audio_stream_info(), rm_read_header(), rm_read_index(), rpl_read_packet(), rsd_read_header(), scan_file(), sdr2_read_header(), sdr2_read_packet(), set_spdif(), siff_parse_soun(), siff_parse_vbv1(), siff_read_header(), siff_read_packet(), smacker_read_header(), smacker_read_packet(), smjpeg_read_header(), smjpeg_read_packet(), smush_read_header(), sol_read_header(), sox_read_header(), svag_read_header(), swf_read_header(), swf_read_packet(), tak_read_header(), threedostr_read_header(), threedostr_read_packet(), tmv_read_header(), tta_read_header(), txd_read_packet(), vag_read_header(), vc1t_read_header(), vc1t_read_packet(), vpk_read_header(), vqf_read_header(), wc3_read_header(), wc3_read_packet(), wv_read_block_header(), xa_read_header(), xmv_fetch_video_packet(), xmv_process_packet_header(), xmv_read_extradata(), xmv_read_header(), xvag_read_header(), and xwma_read_header().
avio_rl64()
uint64_t avio_rl64 (AVIOContext * s)
Definition at line 734 of file aviobuf.c.
Referenced by asf_build_simple_index(), asf_read_content_desc(), asf_read_data(), asf_read_ext_content(), asf_read_ext_stream_properties(), asf_read_file_properties(), asf_read_frame_header(), asf_read_generic_value(), asf_read_header(), asf_read_language_list(), asf_read_marker(), asf_read_metadata_obj(), asf_read_properties(), asf_read_simple_index(), asf_read_stream_properties(), asf_read_unknown(), avio_tell(), check_file_header(), cine_read_header(), dsf_read_header(), get_tag(), get_value(), gxf_track_tags(), nuv_header(), ogg_read_page(), parse_chunks(), read_braindead_odml_indx(), read_header(), read_packet(), read_sm_data(), read_uint64(), set_spdif(), and sox_read_header().
avio_rb16()
unsigned int avio_rb16 (AVIOContext * s)
Definition at line 742 of file aviobuf.c.
Referenced by adx_read_header(), afc_read_header(), aix_read_header(), aix_read_packet(), amf_get_string(), amf_skip_tag(), ast_read_header(), avio_rb24(), avio_rb32(), avio_tell(), avr_read_header(), cdata_read_header(), daud_packet(), decode_fctl_chunk(), decode_str(), dtshd_read_header(), dxa_read_header(), ff_get_qtpalette(), ff_get_wav_header(), ff_mov_read_esds(), ff_mov_read_stsd_entries(), ff_mp4_parse_es_descr(), ff_rm_parse_packet(), ff_rm_read_mdpr_codecdata(), ff_text_r8(), ffm2_read_header(), ffm_read_data(), ffm_read_header(), flv_data_packet(), get_aiff_header(), get_num(), gxf_header(), id3v2_parse(), iff_read_header(), ivr_read_header(), ivr_read_packet(), lmlm4_read_packet(), matroska_parse_tracks(), mov_metadata_loci(), mov_metadata_track_or_disc_number(), mov_parse_stsd_audio(), mov_parse_stsd_video(), mov_read_ares(), mov_read_chapters(), mov_read_colr(), mov_read_dec3(), mov_read_dref(), mov_read_enda(), mov_read_fiel(), mov_read_mdhd(), mov_read_mvhd(), mov_read_sidx(), mov_read_tkhd(), mov_read_udta_string(), mp3_parse_info_tag(), mp3_parse_vbri_tag(), mpegps_psm_parse(), mpegps_read_packet(), mpegps_read_pes_header(), mv_read_header(), mxf_read_generic_descriptor(), mxf_read_local_tags(), mxf_read_timecode_component(), parse_dsd_prop(), parse_MP4IODescrTag(), parse_MP4ODescrTag(), parse_MP4SLDescrTag(), qt_rtp_parse_packet(), r3d_read_red1(), r3d_read_reda(), r3d_read_redv(), rdt_load_mdpr(), read16(), read_header(), read_packet(), read_part_of_packet(), rm_read_audio_stream_info(), rm_read_header(), rm_read_index(), rm_read_metadata(), rm_read_multi(), rm_sync(), rso_read_header(), smjpeg_read_header(), sup_read_packet(), and xvag_read_header().
avio_rb24()
unsigned int avio_rb24 (AVIOContext * s)
Definition at line 750 of file aviobuf.c.
Referenced by asfrtp_parse_packet(), avio_tell(), avr_read_header(), dtshd_read_header(), ff_mp4_read_dec_config_descr(), flv_read_packet(), id3v2_parse(), mov_read_chpl(), mov_read_ctts(), mov_read_dac3(), mov_read_dec3(), mov_read_dfla(), mov_read_elst(), mov_read_hdlr(), mov_read_mdhd(), mov_read_mvhd(), mov_read_saiz(), mov_read_sbgp(), mov_read_senc(), mov_read_sidx(), mov_read_stco(), mov_read_stsc(), mov_read_stsd(), mov_read_stss(), mov_read_stsz(), mov_read_stts(), mov_read_tfdt(), mov_read_tfhd(), mov_read_tkhd(), mov_read_trex(), mov_read_trun(), mov_read_udta_string(), mp3_parse_info_tag(), read_moof_duration(), read_part_of_packet(), read_tfra(), read_trun_duration(), smush_read_header(), and tak_read_header().
avio_rb32()
unsigned int avio_rb32 (AVIOContext * s)
Definition at line 757 of file aviobuf.c.
Referenced by aa_read_header(), aa_read_packet(), afc_read_header(), aiff_read_header(), aix_read_header(), aix_read_packet(), amf_parse_object(), amf_skip_tag(), apng_read_header(), apng_read_packet(), ast_read_header(), ast_read_packet(), avi_sync(), avio_rb64(), avio_tell(), copy_tag(), decode_fctl_chunk(), decode_frame_header(), dtshd_read_header(), dv_read_header(), dxa_read_header(), ea_read_packet(), ebml_read_float(), epaf_read_header(), ff_flac_parse_picture(), ff_get_qtpalette(), ff_get_wav_header(), ff_mov_read_chan(), ff_mov_read_esds(), ff_mov_read_stsd_entries(), ff_mp4_read_dec_config_descr(), ff_rm_read_mdpr_codecdata(), ffm2_read_header(), ffm_read_header(), find_sidx(), flv_read_header(), flv_read_packet(), fsb_read_header(), get_aiff_header(), get_packetheader(), get_tag(), gxf_material_tags(), gxf_packet(), gxf_resync_media(), gxf_track_tags(), id3v2_parse(), iff_read_header(), iff_read_packet(), ircam_read_header(), ivr_read_header(), ivr_read_packet(), lmlm4_read_packet(), matroska_parse_tracks(), matroska_resync(), mmf_read_header(), mov_metadata_hmmt(), mov_metadata_loci(), mov_parse_stsd_audio(), mov_parse_stsd_video(), mov_read_ares(), mov_read_chap(), mov_read_chpl(), mov_read_cmov(), mov_read_ctts(), mov_read_custom(), mov_read_default(), mov_read_dref(), mov_read_elst(), mov_read_ftyp(), mov_read_glbl(), mov_read_hdlr(), mov_read_keys(), mov_read_mdhd(), mov_read_mfra(), mov_read_mvhd(), mov_read_pasp(), mov_read_saiz(), mov_read_sbgp(), mov_read_senc(), mov_read_sidx(), mov_read_stco(), mov_read_stps(), mov_read_stsc(), mov_read_stsd(), mov_read_stss(), mov_read_stsz(), mov_read_stts(), mov_read_sv3d(), mov_read_tfdt(), mov_read_tfhd(), mov_read_timecode_track(), mov_read_tkhd(), mov_read_tmcd(), mov_read_trex(), mov_read_trun(), mov_read_udta_string(), mov_read_wide(), mp3_parse_info_tag(), mp3_parse_vbr_tags(), mp3_parse_vbri_tag(), mpegps_psm_parse(), msf_read_header(), musx_read_header(), mv_read_header(), mxf_read_generic_descriptor(), mxf_read_index_entry_array(), mxf_read_index_table_segment(), mxf_read_partition_pack(), mxf_read_primer_pack(), mxf_read_random_index_pack(), mxf_read_source_clip(), mxf_read_strong_ref_array(), mxf_read_track(), nuv_resync(), parse_dsd_diin(), parse_dsd_prop(), parse_fragment(), parse_keyframes_index(), parse_MP4SLDescrTag(), parse_packet_header(), process_audio_header_eacs(), qcp_read_header(), qt_rtp_parse_packet(), r3d_read_rdvo(), r3d_read_red1(), r3d_read_reda(), r3d_read_redv(), r3d_read_reos(), rdt_load_mdpr(), read32(), read_atom(), read_chapter(), read_desc_chunk(), read_dst_frame(), read_header(), read_index(), read_info_chunk(), read_mfra(), read_moof_duration(), read_packet(), read_pakt_chunk(), read_part_of_packet(), read_table(), read_tfra(), read_trun_duration(), redspark_read_header(), rl2_read_header(), rm_read_audio_stream_info(), rm_read_header(), rm_read_index(), rm_read_multi(), rm_sync(), rsd_read_header(), set_spdif(), siff_parse_soun(), siff_parse_vbv1(), skip_tag(), smjpeg_read_header(), smjpeg_read_packet(), smush_read_header(), smush_read_packet(), sox_read_header(), sup_read_packet(), swf_read_header(), thp_read_header(), thp_read_packet(), threedostr_read_header(), threedostr_read_packet(), vag_read_header(), vqf_read_header(), wc3_read_header(), wc3_read_packet(), wsd_read_header(), wve_read_header(), and xvag_read_header().
avio_rb64()
uint64_t avio_rb64 (AVIOContext * s)
Definition at line 824 of file aviobuf.c.
Referenced by amf_parse_object(), apng_read_header(), avio_tell(), dtshd_read_header(), ebml_read_float(), ffm2_read_header(), ffm_read_data(), ffm_read_header(), find_and_decode_index(), get_aiff_header(), get_dts(), iff_read_header(), ivr_read_header(), ivr_read_packet(), mov_parse_stsd_audio(), mov_read_chpl(), mov_read_default(), mov_read_elst(), mov_read_mdhd(), mov_read_mvhd(), mov_read_sidx(), mov_read_stco(), mov_read_tfdt(), mov_read_tfhd(), mov_read_tkhd(), mov_read_wave(), mxf_decrypt_triplet(), mxf_read_essence_group(), mxf_read_generic_descriptor(), mxf_read_index_entry_array(), mxf_read_index_table_segment(), mxf_read_partition_pack(), mxf_read_random_index_pack(), mxf_read_sequence(), mxf_read_source_clip(), mxf_read_timecode_component(), parse_dsd_diin(), parse_dsd_prop(), parse_fragment(), parse_keyframes_index(), read_desc_chunk(), read_dst_frame(), read_header(), read_moof_duration(), read_pakt_chunk(), read_tfra(), set_spdif(), and sox_read_header().
avio_get_str()
int avio_get_str (AVIOContext * pb, int maxlen, char * buf, int buflen)
Read a string from pb into buf.
The reading will terminate when either a NULL character was encountered, maxlen bytes have been read, or nothing more can be read from pb. The result is guaranteed to be NULL-terminated, it will be truncated if buf is too small. Note that the string is not interpreted or validated in any way, it might get truncated in the middle of a sequence for multi-byte encodings.
Returns
number of bytes read (is always <= maxlen). If reading ends on EOF or error, the return value will be one more than bytes actually read.
Definition at line 782 of file aviobuf.c.
Referenced by ape_tag_read_field(), avio_tell(), cine_read_header(), ffm2_read_header(), ffm_read_header(), ivr_read_header(), mov_metadata_loci(), mov_read_chapters(), mpegps_read_header(), read_apic(), read_info_chunk(), and var_read_string().
avio_get_str16le()
int avio_get_str16le (AVIOContext * pb, int maxlen, char * buf, int buflen)
Read a UTF-16 string from pb and convert it to UTF-8.
The reading will terminate when either a null or invalid character was encountered or maxlen bytes have been read.
Returns
number of bytes read (is always <= maxlen)
Referenced by asf_read_ext_content(), asf_read_ext_content_desc(), asf_read_language_list(), asf_read_marker(), asf_read_metadata(), asf_read_metadata_obj(), asf_read_picture(), avio_tell(), get_attachment(), get_tag(), mov_read_chapters(), mxf_read_utf16_string(), parse_legacy_attrib(), read_gab2_sub(), and set_spdif().
avio_get_str16be()
int avio_get_str16be (AVIOContext * pb, int maxlen, char * buf, int buflen)
Referenced by avio_tell(), mov_read_chapters(), and mxf_read_utf16_string().
avio_open()
int avio_open (AVIOContext ** s, const char * url, int flags)
Create and initialize a AVIOContext for accessing the resource indicated by url.
Note
When the resource indicated by url has been opened in read+write mode, the AVIOContext can be used only for writing.
Parameters
s Used to return the pointer to the created AVIOContext. In case of failure the pointed to value is set to NULL.
url resource to access
flags flags which control how the resource indicated by url is to be opened
Returns
>= 0 in case of success, a negative value corresponding to an AVERROR code in case of failure
Examples:
muxing.c, qsvdec.c, remuxing.c, transcode_aac.c, and transcoding.c.
Definition at line 1033 of file aviobuf.c.
Referenced by build_feed_streams(), init(), main(), open_output_file(), and read_file().
avio_open2()
int avio_open2 (AVIOContext ** s, const char * url, int flags, const AVIOInterruptCB * int_cb, AVDictionary ** options)
Create and initialize a AVIOContext for accessing the resource indicated by url.
Note
When the resource indicated by url has been opened in read+write mode, the AVIOContext can be used only for writing.
Parameters
s Used to return the pointer to the created AVIOContext. In case of failure the pointed to value is set to NULL.
url resource to access
flags flags which control how the resource indicated by url is to be opened
int_cb an interrupt callback to be used at the protocols level
options A dictionary filled with protocol-private options. On return this parameter will be destroyed and replaced with a dict containing options that were not found. May be NULL.
Returns
>= 0 in case of success, a negative value corresponding to an AVERROR code in case of failure
Examples:
http_multiclient.c.
Definition at line 1057 of file aviobuf.c.
Referenced by avio_open(), dump_attachment(), find_sidx(), get_preset_file_2(), lavfi_read_header(), main(), open_output_file(), opt_progress(), print_sdp(), process_client(), read_mfra(), and write_fragment().
avio_close()
int avio_close (AVIOContext * s)
Close the resource accessed by the AVIOContext s and free it.
This function can only be used if s was opened by avio_open().
The internal buffer is automatically flushed before closing the resource.
Returns
0 on success, an AVERROR < 0 on error.
See also
avio_closep
Examples:
http_multiclient.c, and qsvdec.c.
Definition at line 1069 of file aviobuf.c.
Referenced by avformat_close_input(), avio_closep(), dump_attachment(), find_sidx(), import_pem(), io_close_default(), main(), parse_playlist(), process_client(), read_mfra(), and write_fragment().
avio_closep()
int avio_closep (AVIOContext ** s)
Close the resource accessed by the AVIOContext *s, free it and set the pointer pointing to it to NULL.
This function can only be used if s was opened by avio_open().
The internal buffer is automatically flushed before closing the resource.
Returns
0 on success, an AVERROR < 0 on error.
See also
avio_close
Examples:
muxing.c, remuxing.c, transcode_aac.c, and transcoding.c.
Definition at line 1092 of file aviobuf.c.
Referenced by avformat_open_input(), build_feed_streams(), ff_rtp_chain_mux_open(), ff_rtsp_undo_setup(), ffio_fdopen(), ffmpeg_cleanup(), lavfi_read_header(), main(), new_output_stream(), open_output_file(), print_report(), print_sdp(), read_file(), sap_write_close(), and uninit().
avio_open_dyn_buf()
int avio_open_dyn_buf (AVIOContext ** s)
Open a write only memory stream.
Parameters
s new IO context
Returns
zero if no error.
Definition at line 1268 of file aviobuf.c.
Referenced by ac3_handle_packet(), asf_write_header1(), asf_write_markers(), asfrtp_parse_packet(), choose_pix_fmts(), chunk_start(), close_connection(), compute_status(), decode_str(), dv_handle_packet(), ff_ape_write_tag(), ff_avc_parse_nal_units_buf(), ff_hevc_annexb2mp4_buf(), ff_id3v2_write_apic(), ff_mov_add_hinted_packet(), ff_mov_write_packet(), ff_rtp_check_and_send_back_rr(), ff_rtp_send_punch_packets(), ff_rtp_send_rtcp_feedback(), ffm_write_header(), ffm_write_header_codec_ctx(), ffm_write_recommended_config(), get_line(), get_video_private_data(), h261_handle_packet(), h263_handle_packet(), http_prepare_data(), http_send_data(), id3v2_put_ttag(), jpeg_parse_packet(), latm_parse_packet(), mkv_write_codecprivate(), mkv_write_video_color(), mov_create_chapter_track(), mov_flush_fragment_interleaving(), mov_write_track_udta_tag(), mov_write_udta_tag(), mp3_write_xing(), mpa_robust_parse_packet(), mpegts_write_packet_internal(), nut_write_packet(), nut_write_trailer(), ogg_write_page(), put_str16(), read_file(), rtp_mpegts_write_header(), rtp_mpegts_write_packet(), rtsp_parse_request(), set_codec_str(), start_ebml_master_crc32(), svq3_parse_packet(), tta_write_header(), vc2hq_handle_frame_fragment(), vp8_handle_packet(), vp9_handle_packet(), write_chapter(), write_globalinfo(), write_headers(), write_sm_data(), write_streaminfo(), and xiph_handle_packet().
avio_close_dyn_buf()
int avio_close_dyn_buf (AVIOContext * s, uint8_t ** pbuffer)
Return the written size and a pointer to the buffer.
The buffer must be freed with av_free(). Padding of AV_INPUT_BUFFER_PADDING_SIZE is added to the buffer.
Parameters
s IO context
pbuffer pointer to a byte buffer
Returns
the length of the byte buffer
Definition at line 1280 of file aviobuf.c.
Referenced by asf_write_header1(), asf_write_markers(), asfrtp_parse_packet(), choose_pix_fmts(), chunk_end(), close_connection(), compute_status(), decode_str(), end_ebml_master_crc32(), ff_ape_write_tag(), ff_avc_parse_nal_units_buf(), ff_hevc_annexb2mp4_buf(), ff_id3v2_write_apic(), ff_mov_add_hinted_packet(), ff_rtp_check_and_send_back_rr(), ff_rtp_finalize_packet(), ff_rtp_send_punch_packets(), ff_rtp_send_rtcp_feedback(), ff_rtsp_tcp_write_packet(), ffio_free_dyn_buf(), get_line(), get_video_private_data(), http_prepare_data(), http_send_data(), id3v2_put_ttag(), latm_parse_packet(), mkv_write_codecprivate(), mkv_write_video_color(), mov_create_chapter_track(), mov_flush_fragment(), mov_flush_fragment_interleaving(), mov_write_track_udta_tag(), mov_write_udta_tag(), mp3_write_xing(), mpegts_write_packet_internal(), nut_write_packet(), ogg_write_page(), put_packet(), put_str16(), read_file(), rtp_mpegts_write_packet(), rtp_new_av_stream(), rtsp_parse_request(), set_codec_str(), tta_write_trailer(), write_chapter(), write_globalinfo(), write_header_chunk(), write_sm_data(), and write_streaminfo().
avio_enum_protocols()
const char* avio_enum_protocols (void ** opaque, int output)
Iterate through names of available protocols.
Parameters
opaque A private pointer representing current protocol. It must be a pointer to NULL on first iteration and will be updated by successive calls to avio_enum_protocols.
output If set to 1, iterate over output protocols, otherwise over input protocols.
Returns
A static string containing the name of current protocol or NULL
Definition at line 96 of file protocols.c.
Referenced by show_protocols().
avio_pause()
int avio_pause (AVIOContext * h, int pause)
Pause and resume playing - only meaningful if using a network streaming protocol (e.g.
MMS).
Parameters
h IO context from which to call the read_pause function pointer
pause 1 for pause, 0 for resume
Definition at line 1112 of file aviobuf.c.
Referenced by av_read_pause(), and av_read_play().
avio_seek_time()
int64_t avio_seek_time (AVIOContext * h, int stream_index, int64_t timestamp, int flags)
Seek to a given timestamp relative to some component stream.
Only meaningful if using a network streaming protocol (e.g. MMS.).
Parameters
h IO context from which to call the seek function pointers
stream_index The stream index that the timestamp is relative to. If stream_index is (-1) the timestamp should be in AV_TIME_BASE units from the beginning of the presentation. If a stream_index >= 0 is used and the protocol does not support seeking based on component streams, the call will fail.
timestamp timestamp in AVStream.time_base units or if there is no stream specified then in AV_TIME_BASE units.
flags Optional combination of AVSEEK_FLAG_BACKWARD, AVSEEK_FLAG_BYTE and AVSEEK_FLAG_ANY. The protocol may silently ignore AVSEEK_FLAG_BACKWARD and AVSEEK_FLAG_ANY, but AVSEEK_FLAG_BYTE will fail if used and not supported.
Returns
>= 0 on success
See also
AVInputFormat::read_seek
Definition at line 1119 of file aviobuf.c.
Referenced by asf_read_seek(), and flv_read_seek().
avio_read_to_bprint()
int avio_read_to_bprint (AVIOContext * h, struct AVBPrint * pb, size_t max_size)
Read contents of h into print buffer, up to max_size bytes, or up to EOF.
Returns
0 for success (max_size bytes read or EOF reached), negative error code otherwise
Definition at line 1138 of file aviobuf.c.
Referenced by lavfi_read_header().
avio_accept()
int avio_accept (AVIOContext * s, AVIOContext ** c)
Accept and allocate a client context on a server context.
Parameters
s the server context
c the client context, must be unallocated
Returns
>= 0 on success or a negative value corresponding to an AVERROR on failure
Examples:
http_multiclient.c.
Definition at line 1156 of file aviobuf.c.
Referenced by main().
avio_handshake()
int avio_handshake (AVIOContext * c)
Perform one step of the protocol handshake to accept a new client.
This function must be called on a client returned by avio_accept() before using it as a read/write context. It is separate from avio_accept() because it may block. A step of the handshake is defined by places where the application may decide to change the proceedings. For example, on a protocol with a request header and a reply header, each one can constitute a step because the application may use the parameters from the request to change parameters in the reply; or each individual chunk of the request can constitute a step. If the handshake is already finished, avio_handshake() does nothing and returns 0 immediately.
Parameters
c the client context to perform the handshake on
Returns
0 on a complete and successful handshake > 0 if the handshake progressed, but is not complete < 0 for an AVERROR code
Examples:
http_multiclient.c.
Definition at line 1168 of file aviobuf.c.
Referenced by process_client().