FFmpeg: libavformat/avlanguage.c File Reference
avlanguage.c File Reference
#include "avlanguage.h"
#include "libavutil/avstring.h"
#include "libavutil/common.h"
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
Data Structures
struct LangEntry
Functions
static int lang_table_compare (const void *lhs, const void *rhs)
const char * ff_convert_lang_to (const char *lang, enum AVLangCodespace target_codespace)
Convert a language code to a target codespace.
const char * av_convert_lang_to (const char *lang, enum AVLangCodespace target_codespace)
Variables
static const uint16_t lang_table_counts [] = { 484, 20, 184 }
static const uint16_t lang_table_offsets [] = { 0, 484, 504 }
static const LangEntry lang_table []
Function Documentation
lang_table_compare()
static int lang_table_compare (const void * lhs, const void * rhs) static
Definition at line 731 of file avlanguage.c.
Referenced by ff_convert_lang_to().
ff_convert_lang_to()
const char* ff_convert_lang_to (const char * lang, enum AVLangCodespace target_codespace)
Convert a language code to a target codespace.
The source codespace is guessed.
Returns
NULL if the provided lang is null or invalid.
Definition at line 736 of file avlanguage.c.
Referenced by asf_read_header(), asf_write_header1(), av_convert_lang_to(), avi_write_header(), ff_convert_lang_to(), mkv_write_simpletag(), and set_language().
av_convert_lang_to()
const char* av_convert_lang_to (const char * lang, enum AVLangCodespace target_codespace)
Definition at line 768 of file avlanguage.c.
Variable Documentation
lang_table_counts
const uint16_t lang_table_counts[] = { 484, 20, 184 } static
Definition at line 33 of file avlanguage.c.
Referenced by ff_convert_lang_to().
lang_table_offsets
const uint16_t lang_table_offsets[] = { 0, 484, 504 } static
Definition at line 34 of file avlanguage.c.
Referenced by ff_convert_lang_to().
lang_table
const LangEntry lang_table[] static
Definition at line 36 of file avlanguage.c.