FFmpeg: libavformat/avlanguage.h File Reference
avlanguage.h File Reference
#include "libavutil/attributes.h"
#include "libavformat/version.h"
Enumerations
enum AVLangCodespace { AV_LANG_ISO639_2_BIBL, AV_LANG_ISO639_2_TERM, AV_LANG_ISO639_1 }
Known language codespaces.
Functions
const char * ff_convert_lang_to (const char *lang, enum AVLangCodespace target_codespace)
Convert a language code to a target codespace.
attribute_deprecated const char * av_convert_lang_to (const char *lang, enum AVLangCodespace target_codespace)
Enumeration Type Documentation
AVLangCodespace
enum AVLangCodespace
Known language codespaces.
Enumerator
AV_LANG_ISO639_2_BIBL
AV_LANG_ISO639_2_TERM
3-char bibliographic language codes as per ISO-IEC 639-2
AV_LANG_ISO639_1
3-char terminological language codes as per ISO-IEC 639-2
2-char code of language as per ISO/IEC 639-1
Definition at line 30 of file avlanguage.h.
Function Documentation
ff_convert_lang_to()
const char* ff_convert_lang_to (const char * lang, enum AVLangCodespace target_codespace)
Convert a language code to a target codespace.
The source codespace is guessed.
Returns
NULL if the provided lang is null or invalid.
Definition at line 736 of file avlanguage.c.
Referenced by asf_read_header(), asf_write_header1(), av_convert_lang_to(), avi_write_header(), ff_convert_lang_to(), mkv_write_simpletag(), and set_language().
av_convert_lang_to()
attribute_deprecated const char* av_convert_lang_to (const char * lang, enum AVLangCodespace target_codespace)
Definition at line 768 of file avlanguage.c.