FFmpeg: libavcodec/avpacket.c File Reference
avpacket.c File Reference
#include <string.h>
#include "libavutil/avassert.h"
#include "libavutil/common.h"
#include "libavutil/internal.h"
#include "libavutil/mathematics.h"
#include "libavutil/mem.h"
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
Macros
#define ALLOC_MALLOC(data, size) data = av_malloc(size)
#define ALLOC_BUF(data, size)
#define DUP_DATA(dst, src, size, padding, ALLOC)
#define FF_MERGE_MARKER 0x8c4d9d108e25e9feULL
Functions
void av_init_packet (AVPacket *pkt)
Initialize optional fields of a packet with default values.
AVPacket * av_packet_alloc (void)
Allocate an AVPacket and set its fields to default values.
void av_packet_free (AVPacket **pkt)
Free the packet, if the packet is reference counted, it will be unreferenced first.
static int packet_alloc (AVBufferRef **buf, int size)
int av_new_packet (AVPacket *pkt, int size)
Allocate the payload of a packet and initialize its fields with default values.
void av_shrink_packet (AVPacket *pkt, int size)
Reduce packet size, correctly zeroing padding.
int av_grow_packet (AVPacket *pkt, int grow_by)
Increase packet size, correctly zeroing padding.
int av_packet_from_data (AVPacket *pkt, uint8_t *data, int size)
Initialize a reference-counted packet from av_malloc()ed data.
static int copy_packet_data (AVPacket *pkt, const AVPacket *src, int dup)
int av_copy_packet_side_data (AVPacket *pkt, const AVPacket *src)
Copy packet side data.
FF_ENABLE_DEPRECATION_WARNINGS int av_dup_packet (AVPacket *pkt)
int av_copy_packet (AVPacket *dst, const AVPacket *src)
Copy packet, including contents.
void av_packet_free_side_data (AVPacket *pkt)
Convenience function to free all the side data stored.
FF_DISABLE_DEPRECATION_WARNINGS void av_free_packet (AVPacket *pkt)
Free a packet.
FF_ENABLE_DEPRECATION_WARNINGS int av_packet_add_side_data (AVPacket *pkt, enum AVPacketSideDataType type, uint8_t *data, size_t size)
Wrap an existing array as a packet side data.
uint8_t * av_packet_new_side_data (AVPacket *pkt, enum AVPacketSideDataType type, int size)
Allocate new information of a packet.
uint8_t * av_packet_get_side_data (AVPacket *pkt, enum AVPacketSideDataType type, int *size)
Get side information from packet.
const char * av_packet_side_data_name (enum AVPacketSideDataType type)
int av_packet_merge_side_data (AVPacket *pkt)
int av_packet_split_side_data (AVPacket *pkt)
uint8_t * av_packet_pack_dictionary (AVDictionary *dict, int *size)
Pack a dictionary for use in side_data.
int av_packet_unpack_dictionary (const uint8_t *data, int size, AVDictionary **dict)
Unpack a dictionary from side_data.
int av_packet_shrink_side_data (AVPacket *pkt, enum AVPacketSideDataType type, int size)
Shrink the already allocated side data buffer.
int av_packet_copy_props (AVPacket *dst, const AVPacket *src)
Copy only "properties" fields from src to dst.
void av_packet_unref (AVPacket *pkt)
Wipe the packet.
int av_packet_ref (AVPacket *dst, const AVPacket *src)
Setup a new reference to the data described by a given packet.
AVPacket * av_packet_clone (AVPacket *src)
Create a new packet that references the same data as src.
void av_packet_move_ref (AVPacket *dst, AVPacket *src)
Move every field in src to dst and reset src.
void av_packet_rescale_ts (AVPacket *pkt, AVRational src_tb, AVRational dst_tb)
Convert valid timing fields (timestamps / durations) in a packet from one timebase to another.
int ff_side_data_set_encoder_stats (AVPacket *pkt, int quality, int64_t *error, int error_count, int pict_type)
Macro Definition Documentation
ALLOC_MALLOC
#define ALLOC_MALLOC (data, size) data = av_malloc(size)
Definition at line 170 of file avpacket.c.
Referenced by av_copy_packet_side_data().
ALLOC_BUF
#define ALLOC_BUF (data, size)
Value:
do {                                         \
    av_buffer_realloc(&pkt->buf, size);      \
    data = pkt->buf ? pkt->buf->data : NULL; \
} while (0)
Definition at line 171 of file avpacket.c.
Referenced by copy_packet_data().
DUP_DATA
#define DUP_DATA (dst, src, size, padding, ALLOC)
Value:
do {                                                                \
        void *data;                                                     \
        if (padding) {                                                  \
            if ((unsigned)(size) >                                      \
                (unsigned)(size) + AV_INPUT_BUFFER_PADDING_SIZE)        \
                goto failed_alloc;                                      \
            ALLOC(data, size + AV_INPUT_BUFFER_PADDING_SIZE);           \
        } else {                                                        \
            ALLOC(data, size);                                          \
        }                                                               \
        if (!data)                                                      \
            goto failed_alloc;                                          \
        memcpy(data, src, size);                                        \
        if (padding)                                                    \
            memset((uint8_t *)data + size, 0,                           \
                   AV_INPUT_BUFFER_PADDING_SIZE);                       \
        dst = data;                                                     \
    } while (0)
Definition at line 177 of file avpacket.c.
Referenced by av_copy_packet_side_data(), and copy_packet_data().
FF_MERGE_MARKER
#define FF_MERGE_MARKER 0x8c4d9d108e25e9feULL
Definition at line 380 of file avpacket.c.
Referenced by av_packet_merge_side_data(), and av_packet_split_side_data().
Function Documentation
packet_alloc()
static int packet_alloc (AVBufferRef ** buf, int size) static
Definition at line 71 of file avpacket.c.
Referenced by av_new_packet(), and av_packet_ref().
copy_packet_data()
static int copy_packet_data (AVPacket * pkt, const AVPacket * src, int dup) static
Definition at line 198 of file avpacket.c.
Referenced by av_copy_packet(), and av_dup_packet().
ff_side_data_set_encoder_stats()
int ff_side_data_set_encoder_stats (AVPacket * pkt, int quality, int64_t * error, int error_count, int pict_type)
Definition at line 648 of file avpacket.c.
Referenced by dnxhd_encode_picture(), encode_frame(), ff_exp2fi(), ff_mpv_encode_picture(), process_output_surface(), storeframe(), svq1_encode_frame(), X264_frame(), XAVS_frame(), and xvid_encode_frame().