FFmpeg: libavcodec/avrndec.c File Reference
avrndec.c File Reference
#include "avcodec.h"
#include "internal.h"
#include "mjpeg.h"
#include "mjpegdec.h"
#include "libavutil/imgutils.h"
Data Structures
struct AVRnContext
Functions
static av_cold int init (AVCodecContext *avctx)
static av_cold int end (AVCodecContext *avctx)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
Variables
AVCodec ff_avrn_decoder
Function Documentation
init()
static av_cold int init (AVCodecContext * avctx) static
Definition at line 35 of file avrndec.c.
Referenced by a64multi_encode_frame(), amr_decode_fix_avctx(), config_output(), cyuv_decode_frame(), decode_end(), decode_flush(), eightsvx_decode_close(), encode_init(), encode_superframe(), ff_mpeg4_frame_end(), ff_vp8_decode_init(), filter_frame(), flashsv_decode_frame(), flush(), g726_reset(), gsm_flush(), idct248_ref(), FFMPEG_FrameReceiver::initWithContext:, AVFFrameReceiver::initWithContext:, AVFAudioReceiver::initWithContext:, libgsm_flush(), mediacodec_decode_flush(), mlp_encode_close(), mpeg12_class(), mvc_decode_frame(), png_dec_end(), predictor_calc_error(), process_command(), read_access_unit(), read_huffman_tree(), sp5x_decode_frame(), srt_encode_close(), and vpx_free().
end()
static av_cold int end (AVCodecContext * avctx) static
Examples:
avio_reading.c, demuxing_decoding.c, ffhash.c, filtering_audio.c, filtering_video.c, http_multiclient.c, remuxing.c, resampling_audio.c, scaling_video.c, and transcoding.c.
Definition at line 90 of file avrndec.c.
Referenced by ac3_eac3_probe(), add_to_pool(), adjust_write_index(), adts_aac_probe(), alias_pix_read_probe(), analyze_plane(), apng_probe(), apply_tns(), asf_build_simple_index(), asf_read_frame_header(), ass_read_header(), ast_write_header(), av_asprintf(), av_audio_convert(), av_base64_decode(), av_bsf_list_append2(), av_bsf_list_finalize(), av_bsf_list_parse_str(), av_crc(), av_expr_parse(), av_get_token(), av_log_default_callback(), av_md5_update(), av_murmur3_update(), av_opencl_benchmark(), av_opencl_compile(), av_opencl_init(), av_opencl_register_kernel_code(), av_opencl_uninit(), av_packet_unpack_dictionary(), av_strncasecmp(), av_strndup(), av_utf8_decode(), av_vorbis_parse_init(), avcodec_encode_audio2(), avcodec_open2(), avfilter_graph_parse2(), avfilter_graph_parse_ptr(), avi_read_packet(), avpriv_find_start_code(), avpriv_new_chapter(), avpriv_opencl_set_parameter(), avpriv_strtod(), bethsoftvid_decode_frame(), bidir_refine(), bsf_parse_single(), buffer_needs_copy(), build_frame_code(), cache_seek(), cavsvideo_probe(), cfhd_decode(), check(), check_header_mismatch(), check_pixel(), choose_qop(), close_output_stream(), colormap_nearest_iterative(), commit_bitstream_and_slice_buffer(), compute_chapters_end(), compute_mask(), compute_rematrixing_strategy(), copy_input_samples(), copy_separable_masks(), dct_quantize(), deband_16_c(), deband_16_coupling_c(), deband_8_c(), deband_8_coupling_c(), decode_frame_common(), decode_info_header(), decode_main_header(), decode_nal_units(), decode_p_block(), decode_stream_header(), decode_subframe(), decode_syncpoint(), decode_transform_coeffs(), decode_var_block_data(), decouple_info(), deinterlace_slice(), dnxhd_encode_rdo(), do_rematrixing(), doTest(), draw_sample_cline_gray(), draw_sample_cline_rgba(), draw_sample_line_gray(), draw_sample_line_rgba(), draw_sample_p2p_gray(), draw_sample_p2p_rgba(), dshow_cycle_formats(), dshow_set_audio_buffer_size(), dshow_show_filter_properties(), dshow_try_setup_crossbar_options(), dvbsub_decode(), dvbsub_probe(), dvbtxt_probe(), encode_frame(), envelope_instant(), envelope_instant16(), envelope_peak(), envelope_peak16(), expand_function(), fdk_aac_decode_frame(), ff_aac_apply_tns(), ff_ac3_apply_rematrixing(), ff_ac3_bit_alloc_calc_psd(), ff_ape_write_tag(), ff_avc_find_startcode_internal(), ff_avc_parse_nal_units(), ff_dxva2_common_end_frame(), ff_exp2fi(), ff_h263_decode_mb(), ff_h263_find_resync_marker_reverse(), ff_hevc_annexb2mp4(), ff_htmlmarkup_to_ass(), ff_huff_gen_len_table(), ff_init_scantable(), ff_init_slice_from_src(), ff_isom_write_avcc(), ff_isom_write_hvcc(), ff_jpegls_decode_picture(), ff_libwebp_get_frame(), ff_load_image(), ff_mjpeg_encode_picture_header(), ff_mms_asf_header_parser(), ff_mov_cenc_avc_parse_nal_units(), ff_mov_write_packet(), ff_mpeg1_decode_block_intra(), ff_mpeg4_decode_picture_header(), ff_mpeg4_init_partitions(), ff_mpeg4video_split(), ff_mpv_encode_picture(), ff_opus_parse_packet(), ff_read_riff_info(), ff_rl_init(), ff_rtp_send_h263(), ff_rtp_send_h263_rfc2190(), ff_rtp_send_h264_hevc(), ff_rtp_send_mpegvideo(), ff_rtp_send_vc2hq(), ff_rtsp_open_transport_ctx(), ff_scale_image(), ff_vorbis_comment(), ff_wma_init(), fifo_thread_write_header(), fill_colmap(), fill_ones(), filter(), filter16_3x3(), filter16_5x5(), filter16_prewitt(), filter16_sobel(), filter_3x3(), filter_5x5(), filter_frame(), filter_prewitt(), filter_slice(), filter_sobel(), find_and_decode_index(), find_component(), find_new_headers(), find_next_marker(), find_resync_marker_reverse(), find_video_stream_info(), flv_write_trailer(), fsize(), ftp_connect(), ftp_current_dir(), ftp_passive_mode(), ftp_passive_mode_epsv(), geq_init(), get_buffer_internal(), get_channel_layout_single(), get_device_list(), get_event_info(), get_floor_average(), get_pts(), get_sockaddr(), get_video_frame(), gif_encode_frame(), gxf_write_trailer(), h264_split(), hevc_split(), hvcc_add_nal_unit(), id3v2_parse(), if(), import_pem(), init(), init_cqt(), init_dict(), init_filter(), init_filters(), interpolate(), ivf_write_trailer(), jacosub_decode_frame(), jpeg2000_decode_frame(), kalman_smoothen(), lag_decode_zero_run_line(), lavfi_read_header(), lex_double(), lex_name(), lex_wsword(), libschroedinger_decode_frame(), libssh_connect(), libwebp_anim_encode_frame(), libwebp_encode_frame(), LLVMFuzzerTestOneInput(), load_ca(), load_cert(), load_mask(), loas_probe(), main(), matroska_parse_block(), microdvd_decode_frame(), mlp_thd_probe(), mov_create_chapter_track(), mov_parse_vc1_frame(), mov_read_chapters(), mov_read_custom(), mov_read_mac_string(), mov_text_decode_frame(), mov_write_dvc1_structs(), mov_write_eac3_tag(), mov_write_loci_tag(), mov_write_subtitle_end_packet(), mov_write_trailer(), mov_write_trun_tag(), mp3_read_probe(), mp_decode_frame(), mpeg1_decode_block_inter(), mpeg1_fast_decode_block_inter(), mpeg2_decode_block_non_intra(), mpeg2_fast_decode_block_non_intra(), mpeg4_decode_mb(), mpegvideo_probe(), mpjpeg_get_boundary(), mpl2_probe(), mpsub_read_header(), mxf_decrypt_triplet(), mxf_probe(), mxf_read_random_index_pack(), mxf_write_d10_audio_packet(), mxf_write_footer(), mxg_find_startmarker(), mxg_read_packet(), new_video_stream(), noise(), ogg_get_length(), old_codec1(), omx_encode_frame(), open_and_probe_video_streams(), open_slave(), opengl_resize(), paf_video_decode(), parse_channel_expressions(), parse_fmtp_config(), parse_fragment(), parse_frames(), parse_ifo_palette(), parse_interval(), parse_psfile(), parse_read_interval(), parse_read_intervals(), parse_str_int(), parse_times(), pcx_decode_frame(), pick_color(), pjs_probe(), plot_freq(), postProcess(), preview_obmc(), print_report(), probe_codec(), probe_file(), process_client(), process_line(), prompeg_write(), put_id3v2_tags(), qdm2_parse_packet(), queue_length(), rac_get_model256_sym(), rac_get_model_sym(), read_access_unit(), read_apic(), read_chapter(), read_dialogue(), read_header(), read_huffman_tables(), read_interval_packets(), read_trun_duration(), read_ts(), real_parse_asm_rule(), real_parse_asm_rulebook(), realtext_read_header(), recode_subtitle(), recv_msg(), resample_cubic(), resample_linear(), revert_channel_correlation(), rgb12to15(), rgb15to16(), rgb15to16_c(), rgb15to24(), rgb15to32(), rgb15to32_c(), rgb15tobgr24(), rgb15tobgr24_c(), rgb15tobgr32(), rgb16to15(), rgb16to15_c(), rgb16to24(), rgb16to32(), rgb16to32_c(), rgb16tobgr24(), rgb16tobgr24_c(), rgb16tobgr32(), rgb24to15(), rgb24to15_c(), rgb24to16(), rgb24to16_c(), rgb24tobgr15(), rgb24tobgr15_c(), rgb24tobgr16(), rgb24tobgr16_c(), rgb24tobgr32(), rgb24tobgr32_c(), rgb32to15(), rgb32to15_c(), rgb32to16(), rgb32to16_c(), rgb32tobgr15(), rgb32tobgr15_c(), rgb32tobgr16(), rgb32tobgr16_c(), rgb32tobgr24(), rgb32tobgr24_c(), rscc_decode_frame(), rt_event_to_ass(), rtp_asf_fix_header(), run_opencl_bench(), run_test(), rv34_decode_slice(), sami_paragraph_to_ass(), sami_read_header(), sbr_hf_gen_c(), segment_end(), set_spdif(), set_string_bool(), shift_data(), show_program(), srt_read_header(), str_probe(), str_to_time(), subviewer_read_header(), sunrast_decode_frame(), test_encode_decode(), tiff_decode_tag(), tm2_read_stream(), tqi_decode_frame(), transcode_subtitles(), trim_right(), try_decode_video_frame(), tta_check_crc64(), udp_get_file_handle(), uninit(), update_metadata(), update_size(), vaapi_encode_get_next(), validate_string(), var_diamond_search(), vc1_decode_frame(), vc1_decode_init(), vc1_decode_p_mb(), vc1_split(), vp3_dequant(), vp3_h_loop_filter_c(), vp3_v_loop_filter_c(), wavpack_encode_block(), webvtt_read_header(), worker(), write_chapter(), write_packet(), write_substrs(), writer_print_string(), xbm_decode_frame(), and xmv_fetch_video_packet().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 100 of file avrndec.c.
Variable Documentation
ff_avrn_decoder
AVCodec ff_avrn_decoder
Initial value:
= {
    .name           = "avrn",
    .long_name      = NULL_IF_CONFIG_SMALL("Avid AVI Codec"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_AVRN,
    .priv_data_size = sizeof(AVRnContext),
    .init           = init,
    .close          = end,
    .decode         = decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
    .max_lowres     = 3,
}
Definition at line 162 of file avrndec.c.