FFmpeg: libavutil/avstring.c File Reference
avstring.c File Reference
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "config.h"
#include "common.h"
#include "mem.h"
#include "avassert.h"
#include "avstring.h"
#include "bprint.h"
Macros
#define WHITESPACES " \n\t\r"
Functions
int av_strstart (const char *str, const char *pfx, const char **ptr)
Return non-zero if pfx is a prefix of str.
int av_stristart (const char *str, const char *pfx, const char **ptr)
Return non-zero if pfx is a prefix of str independent of case.
char * av_stristr (const char *s1, const char *s2)
Locate the first case-independent occurrence in the string haystack of the string needle.
char * av_strnstr (const char *haystack, const char *needle, size_t hay_length)
Locate the first occurrence of the string needle in the string haystack where not more than hay_length characters are searched.
size_t av_strlcpy (char *dst, const char *src, size_t size)
Copy the string src to dst, but no more than size - 1 bytes, and null-terminate dst.
size_t av_strlcat (char *dst, const char *src, size_t size)
Append the string src to the string dst, but to a total length of no more than size - 1 bytes, and null-terminate dst.
size_t av_strlcatf (char *dst, size_t size, const char *fmt,...)
char * av_asprintf (const char *fmt,...)
char * av_d2str (double d)
Convert a number to an av_malloced string.
char * av_get_token (const char **buf, const char *term)
Unescape the given string until a non escaped terminating char, and return the token corresponding to the unescaped string.
char * av_strtok (char *s, const char *delim, char **saveptr)
Split the string into several tokens which can be accessed by successive calls to av_strtok().
int av_strcasecmp (const char *a, const char *b)
Locale-independent case-insensitive compare.
int av_strncasecmp (const char *a, const char *b, size_t n)
Locale-independent case-insensitive compare.
const char * av_basename (const char *path)
Thread safe basename.
const char * av_dirname (char *path)
Thread safe dirname.
char * av_append_path_component (const char *path, const char *component)
Append path component to the existing path.
int av_escape (char **dst, const char *src, const char *special_chars, enum AVEscapeMode mode, int flags)
Escape string in src, and put the escaped string in an allocated string in *dst, which must be freed with av_free().
int av_match_name (const char *name, const char *names)
Match instances of a name in a comma-separated list of names.
int av_utf8_decode (int32_t *codep, const uint8_t **bufp, const uint8_t *buf_end, unsigned int flags)
Read and decode a single UTF-8 code point (character) from the buffer in *buf, and update *buf to point to the next byte to decode.
int av_match_list (const char *name, const char *list, char separator)
Check if a name is in a list.
Macro Definition Documentation
WHITESPACES
#define WHITESPACES " \n\t\r"
Definition at line 147 of file avstring.c.
Referenced by av_get_token().
Function Documentation
av_strlcatf()
size_t av_strlcatf (char * dst, size_t size, const char * fmt, ...)
Definition at line 101 of file avstring.c.
Referenced by amr_decode_fix_avctx(), avcodec_string(), avfilter_process_command(), avpriv_dict_set_timestamp(), configure_filtergraph(), configure_input_audio_filter(), configure_output_audio_filter(), configure_output_video_filter(), cookie_string(), do_adobe_auth(), ff_rdt_subscribe_rule(), ff_rtsp_open_transport_ctx(), ff_rtsp_setup_output_streams(), ff_url_join(), find_compressor(), framecrc_write_packet(), func_eval_expr_int_format(), get_opt_flags_string(), get_video_frame(), get_wb_bitrate_mode(), http_connect(), http_parse_request(), make_digest_auth(), mov_metadata_loci(), mov_rewrite_dvd_sub_extradata(), mov_write_udta_sdp(), parse_icy(), rtsp_read_packet(), rtsp_read_setup(), rtsp_send_reply(), set_codec_str(), uninit(), and value_string().
av_asprintf()
char* av_asprintf (const char * fmt, ...)
Definition at line 113 of file avstring.c.
Referenced by avi_write_header(), create_filter(), ff_ass_get_dialog(), ff_ass_subtitle_header(), ffserver_parse_config_feed(), filter_frame(), frei0r_init(), hls_start(), init(), load_path(), modplug_load_metadata(), mpjpeg_read_packet(), opt_old2new(), opt_qscale(), opt_show_format_entry(), opt_timecode(), parse_definition(), parse_filename(), plot_spectrum_column(), read_thread(), read_uslt(), sender_thread(), try_load(), webm_dash_manifest_read_header(), write_adaptation_set(), and write_packet().