FFmpeg: compat/avisynth/avxsynth_c.h File Reference
avxsynth_c.h File Reference
#include "windowsPorts/windows2linux.h"
#include <stdarg.h>
Data Structures
struct AVS_VideoInfo
struct AVS_VideoFrameBuffer
struct AVS_VideoFrame
struct AVS_Value
struct AVS_FilterInfo
Macros
#define EXTERN_C
#define AVSC_USE_STDCALL 1
#define AVSC_CC __stdcall
#define AVSC_INLINE static __inline
#define AVSC_EXPORT EXTERN_C __declspec(dllexport)
#define AVSC_API(ret, name) EXTERN_C __declspec(dllimport) ret AVSC_CC name
#define AVS_FRAME_ALIGN 16
Typedefs
typedef long long int INT64
typedef struct AVS_Clip AVS_Clip
typedef struct AVS_ScriptEnvironment AVS_ScriptEnvironment
typedef AVS_Value(AVSC_CC * AVS_ApplyFunc) (AVS_ScriptEnvironment *, AVS_Value args, void *user_data)
typedef void(AVSC_CC * AVS_ShutdownFunc) (void *user_data, AVS_ScriptEnvironment *env)
Enumerations
enum { AVISYNTH_INTERFACE_VERSION = 3 }
enum {
AVS_SAMPLE_INT8 = 1<<0, AVS_SAMPLE_INT16 = 1<<1, AVS_SAMPLE_INT24 = 1<<2, AVS_SAMPLE_INT32 = 1<<3,
AVS_SAMPLE_FLOAT = 1<<4
}
enum {
AVS_PLANAR_Y =1<<0, AVS_PLANAR_U =1<<1, AVS_PLANAR_V =1<<2, AVS_PLANAR_ALIGNED =1<<3,
AVS_PLANAR_Y_ALIGNED =AVS_PLANAR_Y|AVS_PLANAR_ALIGNED, AVS_PLANAR_U_ALIGNED =AVS_PLANAR_U|AVS_PLANAR_ALIGNED, AVS_PLANAR_V_ALIGNED =AVS_PLANAR_V|AVS_PLANAR_ALIGNED
}
enum { AVS_CS_BGR = 1<<28, AVS_CS_YUV = 1<<29, AVS_CS_INTERLEAVED = 1<<30, AVS_CS_PLANAR = 1<<31 }
enum {
AVS_CS_UNKNOWN = 0, AVS_CS_BGR24 = 1<<0 | AVS_CS_BGR | AVS_CS_INTERLEAVED, AVS_CS_BGR32 = 1<<1 | AVS_CS_BGR | AVS_CS_INTERLEAVED, AVS_CS_YUY2 = 1<<2 | AVS_CS_YUV | AVS_CS_INTERLEAVED,
AVS_CS_YV12 = 1<<3 | AVS_CS_YUV | AVS_CS_PLANAR, AVS_CS_I420 = 1<<4 | AVS_CS_YUV | AVS_CS_PLANAR, AVS_CS_IYUV = 1<<4 | AVS_CS_YUV | AVS_CS_PLANAR
}
enum { AVS_IT_BFF = 1<<0, AVS_IT_TFF = 1<<1, AVS_IT_FIELDBASED = 1<<2 }
enum {
AVS_FILTER_TYPE =1, AVS_FILTER_INPUT_COLORSPACE =2, AVS_FILTER_OUTPUT_TYPE =9, AVS_FILTER_NAME =4,
AVS_FILTER_AUTHOR =5, AVS_FILTER_VERSION =6, AVS_FILTER_ARGS =7, AVS_FILTER_ARGS_INFO =8,
AVS_FILTER_ARGS_DESCRIPTION =10, AVS_FILTER_DESCRIPTION =11
}
enum { AVS_FILTER_TYPE_AUDIO =1, AVS_FILTER_TYPE_VIDEO =2, AVS_FILTER_OUTPUT_TYPE_SAME =3, AVS_FILTER_OUTPUT_TYPE_DIFFERENT =4 }
enum {
AVS_CACHE_NOTHING =0, AVS_CACHE_RANGE =1, AVS_CACHE_ALL =2, AVS_CACHE_AUDIO =3,
AVS_CACHE_AUDIO_NONE =4, AVS_CACHE_AUDIO_AUTO =5
}
enum {
AVS_CPU_FORCE = 0x01, AVS_CPU_FPU = 0x02, AVS_CPU_MMX = 0x04, AVS_CPU_INTEGER_SSE = 0x08,
AVS_CPU_SSE = 0x10, AVS_CPU_SSE2 = 0x20, AVS_CPU_3DNOW = 0x40, AVS_CPU_3DNOW_EXT = 0x80,
AVS_CPU_X86_64 = 0xA0
}
Functions
AVSC_INLINE int avs_has_video (const AVS_VideoInfo *p)
AVSC_INLINE int avs_has_audio (const AVS_VideoInfo *p)
AVSC_INLINE int avs_is_rgb (const AVS_VideoInfo *p)
AVSC_INLINE int avs_is_rgb24 (const AVS_VideoInfo *p)
AVSC_INLINE int avs_is_rgb32 (const AVS_VideoInfo *p)
AVSC_INLINE int avs_is_yuv (const AVS_VideoInfo *p)
AVSC_INLINE int avs_is_yuy2 (const AVS_VideoInfo *p)
AVSC_INLINE int avs_is_yv12 (const AVS_VideoInfo *p)
AVSC_INLINE int avs_is_color_space (const AVS_VideoInfo *p, int c_space)
AVSC_INLINE int avs_is_property (const AVS_VideoInfo *p, int property)
AVSC_INLINE int avs_is_planar (const AVS_VideoInfo *p)
AVSC_INLINE int avs_is_field_based (const AVS_VideoInfo *p)
AVSC_INLINE int avs_is_parity_known (const AVS_VideoInfo *p)
AVSC_INLINE int avs_is_bff (const AVS_VideoInfo *p)
AVSC_INLINE int avs_is_tff (const AVS_VideoInfo *p)
AVSC_INLINE int avs_bits_per_pixel (const AVS_VideoInfo *p)
AVSC_INLINE int avs_bytes_from_pixels (const AVS_VideoInfo *p, int pixels)
AVSC_INLINE int avs_row_size (const AVS_VideoInfo *p)
AVSC_INLINE int avs_bmp_size (const AVS_VideoInfo *vi)
AVSC_INLINE int avs_samples_per_second (const AVS_VideoInfo *p)
AVSC_INLINE int avs_bytes_per_channel_sample (const AVS_VideoInfo *p)
AVSC_INLINE int avs_bytes_per_audio_sample (const AVS_VideoInfo *p)
AVSC_INLINE INT64 avs_audio_samples_from_frames (const AVS_VideoInfo *p, INT64 frames)
AVSC_INLINE int avs_frames_from_audio_samples (const AVS_VideoInfo *p, INT64 samples)
AVSC_INLINE INT64 avs_audio_samples_from_bytes (const AVS_VideoInfo *p, INT64 bytes)
AVSC_INLINE INT64 avs_bytes_from_audio_samples (const AVS_VideoInfo *p, INT64 samples)
AVSC_INLINE int avs_audio_channels (const AVS_VideoInfo *p)
AVSC_INLINE int avs_sample_type (const AVS_VideoInfo *p)
AVSC_INLINE void avs_set_property (AVS_VideoInfo *p, int property)
AVSC_INLINE void avs_clear_property (AVS_VideoInfo *p, int property)
AVSC_INLINE void avs_set_field_based (AVS_VideoInfo *p, int isfieldbased)
AVSC_INLINE void avs_set_fps (AVS_VideoInfo *p, unsigned numerator, unsigned denominator)
AVSC_INLINE int avs_is_same_colorspace (AVS_VideoInfo *x, AVS_VideoInfo *y)
AVSC_INLINE int avs_get_pitch (const AVS_VideoFrame *p)
AVSC_INLINE int avs_get_pitch_p (const AVS_VideoFrame *p, int plane)
AVSC_INLINE int avs_get_row_size (const AVS_VideoFrame *p)
AVSC_INLINE int avs_get_row_size_p (const AVS_VideoFrame *p, int plane)
AVSC_INLINE int avs_get_height (const AVS_VideoFrame *p)
AVSC_INLINE int avs_get_height_p (const AVS_VideoFrame *p, int plane)
AVSC_INLINE const unsigned char * avs_get_read_ptr (const AVS_VideoFrame *p)
AVSC_INLINE const unsigned char * avs_get_read_ptr_p (const AVS_VideoFrame *p, int plane)
AVSC_INLINE int avs_is_writable (const AVS_VideoFrame *p)
AVSC_INLINE unsigned char * avs_get_write_ptr (const AVS_VideoFrame *p)
AVSC_INLINE unsigned char * avs_get_write_ptr_p (const AVS_VideoFrame *p, int plane)
AVSC_API (void, avs_release_video_frame)(AVS_VideoFrame *)
AVSC_API (AVS_VideoFrame *, avs_copy_video_frame)(AVS_VideoFrame *)
AVSC_INLINE void avs_release_frame (AVS_VideoFrame *f)
AVSC_INLINE AVS_VideoFrame * avs_copy_frame (AVS_VideoFrame *f)
AVSC_API (void, avs_copy_value)(AVS_Value *dest
AVSC_API (void, avs_release_value)(AVS_Value)
AVSC_INLINE int avs_defined (AVS_Value v)
AVSC_INLINE int avs_is_clip (AVS_Value v)
AVSC_INLINE int avs_is_bool (AVS_Value v)
AVSC_INLINE int avs_is_int (AVS_Value v)
AVSC_INLINE int avs_is_float (AVS_Value v)
AVSC_INLINE int avs_is_string (AVS_Value v)
AVSC_INLINE int avs_is_array (AVS_Value v)
AVSC_INLINE int avs_is_error (AVS_Value v)
AVSC_API (AVS_Clip *, avs_take_clip)(AVS_Value
AVS_ScriptEnvironment * AVSC_API (void, avs_set_to_clip)(AVS_Value *
AVS_ScriptEnvironment AVS_Clip *AVSC_INLINE int avs_as_bool (AVS_Value v)
AVSC_INLINE int avs_as_int (AVS_Value v)
AVSC_INLINE const char * avs_as_string (AVS_Value v)
AVSC_INLINE double avs_as_float (AVS_Value v)
AVSC_INLINE const char * avs_as_error (AVS_Value v)
AVSC_INLINE const AVS_Value * avs_as_array (AVS_Value v)
AVSC_INLINE int avs_array_size (AVS_Value v)
AVSC_INLINE AVS_Value avs_array_elt (AVS_Value v, int index)
AVSC_INLINE AVS_Value avs_new_value_bool (int v0)
AVSC_INLINE AVS_Value avs_new_value_int (int v0)
AVSC_INLINE AVS_Value avs_new_value_string (const char *v0)
AVSC_INLINE AVS_Value avs_new_value_float (float v0)
AVSC_INLINE AVS_Value avs_new_value_error (const char *v0)
AVSC_INLINE AVS_Value avs_new_value_clip (AVS_Clip *v0)
AVSC_INLINE AVS_Value avs_new_value_array (AVS_Value *v0, int size)
AVSC_API (void, avs_release_clip)(AVS_Clip *)
AVSC_API (AVS_Clip *, avs_copy_clip)(AVS_Clip *)
AVSC_API (const char *, avs_clip_get_error)(AVS_Clip *)
AVSC_API (const AVS_VideoInfo *, avs_get_video_info)(AVS_Clip *)
AVSC_API (int, avs_get_version)(AVS_Clip *)
AVSC_API (AVS_VideoFrame *, avs_get_frame)(AVS_Clip *
AVSC_API (int, avs_get_parity)(AVS_Clip *
AVSC_API (int, avs_get_audio)(AVS_Clip *
AVSC_API (int, avs_set_cache_hints)(AVS_Clip *
AVSC_API (AVS_Clip *, avs_new_c_filter)(AVS_ScriptEnvironment *e
AVSC_API (const char *, avs_get_error)(AVS_ScriptEnvironment *)
AVSC_API (long, avs_get_cpu_flags)(AVS_ScriptEnvironment *)
AVSC_API (int, avs_check_version)(AVS_ScriptEnvironment *
AVSC_API (char *, avs_save_string)(AVS_ScriptEnvironment *
AVSC_API (char *, avs_sprintf)(AVS_ScriptEnvironment *
const char AVSC_API (char *, avs_vsprintf)(AVS_ScriptEnvironment *
AVSC_API (int, avs_add_function)(AVS_ScriptEnvironment *
AVSC_API (int, avs_function_exists)(AVS_ScriptEnvironment *
AVSC_API (AVS_Value, avs_invoke)(AVS_ScriptEnvironment *
AVSC_API (AVS_Value, avs_get_var)(AVS_ScriptEnvironment *
AVSC_API (int, avs_set_var)(AVS_ScriptEnvironment *
AVSC_API (int, avs_set_global_var)(AVS_ScriptEnvironment *
AVSC_API (AVS_VideoFrame *, avs_new_video_frame_a)(AVS_ScriptEnvironment *
AVSC_INLINE AVS_VideoFrame * avs_new_video_frame (AVS_ScriptEnvironment *env, const AVS_VideoInfo *vi)
AVSC_INLINE AVS_VideoFrame * avs_new_frame (AVS_ScriptEnvironment *env, const AVS_VideoInfo *vi)
AVSC_API (int, avs_make_writable)(AVS_ScriptEnvironment *
AVSC_API (void, avs_bit_blt)(AVS_ScriptEnvironment *
AVSC_API (void, avs_at_exit)(AVS_ScriptEnvironment *
AVSC_API (AVS_VideoFrame *, avs_subframe)(AVS_ScriptEnvironment *
AVSC_API (int, avs_set_memory_max)(AVS_ScriptEnvironment *
AVSC_API (int, avs_set_working_dir)(AVS_ScriptEnvironment *
AVSC_API (AVS_ScriptEnvironment *, avs_create_script_environment)(int version)
AVSC_EXPORT const char *AVSC_CC avisynth_c_plugin_init (AVS_ScriptEnvironment *env)
AVSC_API (void, avs_delete_script_environment)(AVS_ScriptEnvironment *)
AVSC_API (AVS_VideoFrame *, avs_subframe_planar)(AVS_ScriptEnvironment *
Variables
static const AVS_Value avs_void = {'v'}
AVS_Value src
int n
void * buf
void INT64 start
void INT64 INT64 count
int cachehints
int size_t frame_range
AVS_FilterInfo ** fi
AVS_FilterInfo AVS_Value child
AVS_FilterInfo AVS_Value int store_child
int version
const char * s
const char int length
const char * fmt
const char const char va_list val
const char * name
const char const char * params
const char const char AVS_ApplyFunc apply
const char const char AVS_ApplyFunc void * user_data
const char AVS_Value args
const char AVS_Value const char ** arg_names
const AVS_VideoInfo * vi
const AVS_VideoInfo int align
AVS_VideoFrame ** pvf
unsigned char * dstp
unsigned char int dst_pitch
unsigned char int const unsigned char * srcp
unsigned char int const unsigned char int src_pitch
unsigned char int const unsigned char int int row_size
unsigned char int const unsigned char int int int height
AVS_ShutdownFunc function
AVS_VideoFrame int rel_offset
AVS_VideoFrame int int new_pitch
AVS_VideoFrame int int int new_row_size
AVS_VideoFrame int int int int new_height
int mem
const char * newdir
AVS_VideoFrame int int int int int rel_offsetU
AVS_VideoFrame int int int int int int rel_offsetV
AVS_VideoFrame int int int int int int int new_pitchUV
Macro Definition Documentation
EXTERN_C
#define EXTERN_C
Definition at line 43 of file avxsynth_c.h.
AVSC_USE_STDCALL
#define AVSC_USE_STDCALL 1
Definition at line 46 of file avxsynth_c.h.
AVSC_CC
#define AVSC_CC __stdcall
Definition at line 51 of file avxsynth_c.h.
AVSC_INLINE
#define AVSC_INLINE static __inline
Definition at line 54 of file avxsynth_c.h.
Referenced by avs_new_video_frame().
AVSC_EXPORT
#define AVSC_EXPORT EXTERN_C __declspec(dllexport)
Definition at line 60 of file avxsynth_c.h.
AVSC_API
#define AVSC_API (ret, name) EXTERN_C __declspec(dllimport) ret AVSC_CC name
Definition at line 62 of file avxsynth_c.h.
Referenced by avs_get_write_ptr_p(), avs_is_error(), and avs_new_value_array().
AVS_FRAME_ALIGN
#define AVS_FRAME_ALIGN 16
Definition at line 147 of file avxsynth_c.h.
Referenced by avs_get_row_size_p(), avs_new_frame(), and avs_new_video_frame().
Typedef Documentation
INT64
typedef long long int INT64
Definition at line 69 of file avxsynth_c.h.
AVS_Clip
typedef struct AVS_Clip AVS_Clip
Definition at line 149 of file avxsynth_c.h.
AVS_ScriptEnvironment
typedef struct AVS_ScriptEnvironment AVS_ScriptEnvironment
Definition at line 150 of file avxsynth_c.h.
AVS_ApplyFunc
typedef AVS_Value(AVSC_CC * AVS_ApplyFunc) (AVS_ScriptEnvironment *, AVS_Value args, void *user_data)
Definition at line 567 of file avxsynth_c.h.
AVS_ShutdownFunc
typedef void(AVSC_CC * AVS_ShutdownFunc) (void *user_data, AVS_ScriptEnvironment *env)
Definition at line 692 of file avxsynth_c.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
AVISYNTH_INTERFACE_VERSION
Definition at line 81 of file avxsynth_c.h.
anonymous enum
anonymous enum
Enumerator
AVS_SAMPLE_INT8
AVS_SAMPLE_INT16
AVS_SAMPLE_INT24
AVS_SAMPLE_INT32
AVS_SAMPLE_FLOAT
Definition at line 84 of file avxsynth_c.h.
anonymous enum
anonymous enum
Enumerator
AVS_PLANAR_Y
AVS_PLANAR_U
AVS_PLANAR_V
AVS_PLANAR_ALIGNED
AVS_PLANAR_Y_ALIGNED
AVS_PLANAR_U_ALIGNED
AVS_PLANAR_V_ALIGNED
Definition at line 90 of file avxsynth_c.h.
anonymous enum
anonymous enum
Enumerator
AVS_CS_BGR
AVS_CS_YUV
AVS_CS_INTERLEAVED
AVS_CS_PLANAR
Definition at line 99 of file avxsynth_c.h.
anonymous enum
anonymous enum
Enumerator
AVS_CS_UNKNOWN
AVS_CS_BGR24
AVS_CS_BGR32
AVS_CS_YUY2
AVS_CS_YV12
AVS_CS_I420
AVS_CS_IYUV
Definition at line 105 of file avxsynth_c.h.
anonymous enum
anonymous enum
Enumerator
AVS_IT_BFF
AVS_IT_TFF
AVS_IT_FIELDBASED
Definition at line 115 of file avxsynth_c.h.
anonymous enum
anonymous enum
Enumerator
AVS_FILTER_TYPE
AVS_FILTER_INPUT_COLORSPACE
AVS_FILTER_OUTPUT_TYPE
AVS_FILTER_NAME
AVS_FILTER_AUTHOR
AVS_FILTER_VERSION
AVS_FILTER_ARGS
AVS_FILTER_ARGS_INFO
AVS_FILTER_ARGS_DESCRIPTION
AVS_FILTER_DESCRIPTION
Definition at line 120 of file avxsynth_c.h.
anonymous enum
anonymous enum
Enumerator
AVS_FILTER_TYPE_AUDIO
AVS_FILTER_TYPE_VIDEO
AVS_FILTER_OUTPUT_TYPE_SAME
AVS_FILTER_OUTPUT_TYPE_DIFFERENT
Definition at line 132 of file avxsynth_c.h.
anonymous enum
anonymous enum
Enumerator
AVS_CACHE_NOTHING
AVS_CACHE_RANGE
AVS_CACHE_ALL
AVS_CACHE_AUDIO
AVS_CACHE_AUDIO_NONE
AVS_CACHE_AUDIO_AUTO
Definition at line 138 of file avxsynth_c.h.
anonymous enum
anonymous enum
Enumerator
AVS_CPU_FORCE
AVS_CPU_FPU
AVS_CPU_MMX
AVS_CPU_INTEGER_SSE
AVS_CPU_SSE
AVS_CPU_SSE2
AVS_CPU_3DNOW
AVS_CPU_3DNOW_EXT
AVS_CPU_X86_64
Definition at line 616 of file avxsynth_c.h.
Function Documentation
avs_has_video()
AVSC_INLINE int avs_has_video (const AVS_VideoInfo * p)
Definition at line 176 of file avxsynth_c.h.
avs_has_audio()
AVSC_INLINE int avs_has_audio (const AVS_VideoInfo * p)
Definition at line 179 of file avxsynth_c.h.
avs_is_rgb()
AVSC_INLINE int avs_is_rgb (const AVS_VideoInfo * p)
Definition at line 182 of file avxsynth_c.h.
avs_is_rgb24()
AVSC_INLINE int avs_is_rgb24 (const AVS_VideoInfo * p)
Definition at line 185 of file avxsynth_c.h.
avs_is_rgb32()
AVSC_INLINE int avs_is_rgb32 (const AVS_VideoInfo * p)
Definition at line 188 of file avxsynth_c.h.
avs_is_yuv()
AVSC_INLINE int avs_is_yuv (const AVS_VideoInfo * p)
Definition at line 191 of file avxsynth_c.h.
avs_is_yuy2()
AVSC_INLINE int avs_is_yuy2 (const AVS_VideoInfo * p)
Definition at line 194 of file avxsynth_c.h.
avs_is_yv12()
AVSC_INLINE int avs_is_yv12 (const AVS_VideoInfo * p)
Definition at line 197 of file avxsynth_c.h.
Referenced by avs_is_same_colorspace(), avs_is_yuy2(), and avs_set_fps().
avs_is_color_space()
AVSC_INLINE int avs_is_color_space (const AVS_VideoInfo * p, int c_space)
Definition at line 200 of file avxsynth_c.h.
avs_is_property()
AVSC_INLINE int avs_is_property (const AVS_VideoInfo * p, int property)
Definition at line 203 of file avxsynth_c.h.
avs_is_planar()
AVSC_INLINE int avs_is_planar (const AVS_VideoInfo * p)
Definition at line 206 of file avxsynth_c.h.
Referenced by avs_bmp_size().
avs_is_field_based()
AVSC_INLINE int avs_is_field_based (const AVS_VideoInfo * p)
Definition at line 209 of file avxsynth_c.h.
avs_is_parity_known()
AVSC_INLINE int avs_is_parity_known (const AVS_VideoInfo * p)
Definition at line 212 of file avxsynth_c.h.
avs_is_bff()
AVSC_INLINE int avs_is_bff (const AVS_VideoInfo * p)
Definition at line 215 of file avxsynth_c.h.
avs_is_tff()
AVSC_INLINE int avs_is_tff (const AVS_VideoInfo * p)
Definition at line 218 of file avxsynth_c.h.
avs_bits_per_pixel()
AVSC_INLINE int avs_bits_per_pixel (const AVS_VideoInfo * p)
Definition at line 221 of file avxsynth_c.h.
Referenced by avisynth_load_library(), avisynth_read_packet_video(), and avs_bytes_from_pixels().
avs_bytes_from_pixels()
AVSC_INLINE int avs_bytes_from_pixels (const AVS_VideoInfo * p, int pixels)
Definition at line 232 of file avxsynth_c.h.
Referenced by avs_row_size().
avs_row_size()
AVSC_INLINE int avs_row_size (const AVS_VideoInfo * p)
Definition at line 235 of file avxsynth_c.h.
Referenced by avs_bmp_size().
avs_bmp_size()
AVSC_INLINE int avs_bmp_size (const AVS_VideoInfo * vi)
Definition at line 238 of file avxsynth_c.h.
avs_samples_per_second()
AVSC_INLINE int avs_samples_per_second (const AVS_VideoInfo * p)
Definition at line 241 of file avxsynth_c.h.
avs_bytes_per_channel_sample()
AVSC_INLINE int avs_bytes_per_channel_sample (const AVS_VideoInfo * p)
Definition at line 245 of file avxsynth_c.h.
Referenced by avs_bytes_per_audio_sample().
avs_bytes_per_audio_sample()
AVSC_INLINE int avs_bytes_per_audio_sample (const AVS_VideoInfo * p)
Definition at line 256 of file avxsynth_c.h.
Referenced by avs_audio_samples_from_bytes(), and avs_bytes_from_audio_samples().
avs_audio_samples_from_frames()
AVSC_INLINE INT64 avs_audio_samples_from_frames (const AVS_VideoInfo * p, INT64 frames)
Definition at line 259 of file avxsynth_c.h.
avs_frames_from_audio_samples()
AVSC_INLINE int avs_frames_from_audio_samples (const AVS_VideoInfo * p, INT64 samples)
Definition at line 262 of file avxsynth_c.h.
avs_audio_samples_from_bytes()
AVSC_INLINE INT64 avs_audio_samples_from_bytes (const AVS_VideoInfo * p, INT64 bytes)
Definition at line 265 of file avxsynth_c.h.
avs_bytes_from_audio_samples()
AVSC_INLINE INT64 avs_bytes_from_audio_samples (const AVS_VideoInfo * p, INT64 samples)
Definition at line 268 of file avxsynth_c.h.
avs_audio_channels()
AVSC_INLINE int avs_audio_channels (const AVS_VideoInfo * p)
Definition at line 271 of file avxsynth_c.h.
avs_sample_type()
AVSC_INLINE int avs_sample_type (const AVS_VideoInfo * p)
Definition at line 274 of file avxsynth_c.h.
avs_set_property()
AVSC_INLINE void avs_set_property (AVS_VideoInfo * p, int property)
Definition at line 278 of file avxsynth_c.h.
avs_clear_property()
AVSC_INLINE void avs_clear_property (AVS_VideoInfo * p, int property)
Definition at line 281 of file avxsynth_c.h.
avs_set_field_based()
AVSC_INLINE void avs_set_field_based (AVS_VideoInfo * p, int isfieldbased)
Definition at line 284 of file avxsynth_c.h.
avs_set_fps()
AVSC_INLINE void avs_set_fps (AVS_VideoInfo * p, unsigned numerator, unsigned denominator)
Definition at line 287 of file avxsynth_c.h.
avs_is_same_colorspace()
AVSC_INLINE int avs_is_same_colorspace (AVS_VideoInfo * x, AVS_VideoInfo * y)
Definition at line 297 of file avxsynth_c.h.
Referenced by avs_set_fps().
avs_get_pitch()
AVSC_INLINE int avs_get_pitch (const AVS_VideoFrame * p)
Definition at line 337 of file avxsynth_c.h.
avs_get_pitch_p()
AVSC_INLINE int avs_get_pitch_p (const AVS_VideoFrame * p, int plane)
Definition at line 340 of file avxsynth_c.h.
Referenced by avisynth_load_library(), and avisynth_read_packet_video().
avs_get_row_size()
AVSC_INLINE int avs_get_row_size (const AVS_VideoFrame * p)
Definition at line 345 of file avxsynth_c.h.
avs_get_row_size_p()
AVSC_INLINE int avs_get_row_size_p (const AVS_VideoFrame * p, int plane)
Definition at line 348 of file avxsynth_c.h.
Referenced by avisynth_load_library(), and avisynth_read_packet_video().
avs_get_height()
AVSC_INLINE int avs_get_height (const AVS_VideoFrame * p)
Definition at line 370 of file avxsynth_c.h.
avs_get_height_p()
AVSC_INLINE int avs_get_height_p (const AVS_VideoFrame * p, int plane)
Definition at line 373 of file avxsynth_c.h.
Referenced by avisynth_load_library(), avisynth_read_packet_video(), and avs_get_row_size().
avs_get_read_ptr()
AVSC_INLINE const unsigned char* avs_get_read_ptr (const AVS_VideoFrame * p)
Definition at line 381 of file avxsynth_c.h.
Referenced by avs_get_height().
avs_get_read_ptr_p()
AVSC_INLINE const unsigned char* avs_get_read_ptr_p (const AVS_VideoFrame * p, int plane)
Definition at line 384 of file avxsynth_c.h.
Referenced by avisynth_load_library(), avisynth_read_packet_video(), and avs_get_height().
avs_is_writable()
AVSC_INLINE int avs_is_writable (const AVS_VideoFrame * p)
Definition at line 392 of file avxsynth_c.h.
Referenced by avs_get_height(), avs_get_write_ptr(), and avs_get_write_ptr_p().
avs_get_write_ptr()
AVSC_INLINE unsigned char* avs_get_write_ptr (const AVS_VideoFrame * p)
Definition at line 395 of file avxsynth_c.h.
Referenced by avs_get_height().
avs_get_write_ptr_p()
AVSC_INLINE unsigned char* avs_get_write_ptr_p (const AVS_VideoFrame * p, int plane)
Definition at line 404 of file avxsynth_c.h.
Referenced by avs_get_height().
AVSC_API() [1/38]
AVSC_API (void , avs_release_video_frame)
AVSC_API() [2/38]
AVSC_API (AVS_VideoFrame * , avs_copy_video_frame)
avs_release_frame()
AVSC_INLINE void avs_release_frame (AVS_VideoFrame * f)
Definition at line 432 of file avxsynth_c.h.
avs_copy_frame()
AVSC_INLINE AVS_VideoFrame* avs_copy_frame (AVS_VideoFrame * f)
Definition at line 434 of file avxsynth_c.h.
AVSC_API() [3/38]
AVSC_API (void , avs_copy_value)
AVSC_API() [4/38]
AVSC_API (void , avs_release_value)
avs_defined()
AVSC_INLINE int avs_defined (AVS_Value v)
Definition at line 477 of file avxsynth_c.h.
avs_is_clip()
AVSC_INLINE int avs_is_clip (AVS_Value v)
Definition at line 478 of file avxsynth_c.h.
avs_is_bool()
AVSC_INLINE int avs_is_bool (AVS_Value v)
Definition at line 479 of file avxsynth_c.h.
avs_is_int()
AVSC_INLINE int avs_is_int (AVS_Value v)
Definition at line 480 of file avxsynth_c.h.
Referenced by avs_as_float().
avs_is_float()
AVSC_INLINE int avs_is_float (AVS_Value v)
Definition at line 481 of file avxsynth_c.h.
avs_is_string()
AVSC_INLINE int avs_is_string (AVS_Value v)
Definition at line 482 of file avxsynth_c.h.
Referenced by avs_as_string().
avs_is_array()
AVSC_INLINE int avs_is_array (AVS_Value v)
Definition at line 483 of file avxsynth_c.h.
Referenced by avs_array_elt(), and avs_array_size().
avs_is_error()
AVSC_INLINE int avs_is_error (AVS_Value v)
Definition at line 484 of file avxsynth_c.h.
Referenced by avs_as_error(), and avs_as_string().
AVSC_API() [5/38]
AVSC_API (AVS_Clip * , avs_take_clip)
AVSC_API() [6/38]
AVS_ScriptEnvironment* AVSC_API (void , avs_set_to_clip)
avs_as_bool()
AVS_ScriptEnvironment AVS_Clip* AVSC_INLINE int avs_as_bool (AVS_Value v)
Definition at line 496 of file avxsynth_c.h.
avs_as_int()
AVSC_INLINE int avs_as_int (AVS_Value v)
Definition at line 498 of file avxsynth_c.h.
avs_as_string()
AVSC_INLINE const char* avs_as_string (AVS_Value v)
Definition at line 500 of file avxsynth_c.h.
avs_as_float()
AVSC_INLINE double avs_as_float (AVS_Value v)
Definition at line 502 of file avxsynth_c.h.
avs_as_error()
AVSC_INLINE const char* avs_as_error (AVS_Value v)
Definition at line 504 of file avxsynth_c.h.
avs_as_array()
AVSC_INLINE const AVS_Value* avs_as_array (AVS_Value v)
Definition at line 506 of file avxsynth_c.h.
avs_array_size()
AVSC_INLINE int avs_array_size (AVS_Value v)
Definition at line 508 of file avxsynth_c.h.
avs_array_elt()
AVSC_INLINE AVS_Value avs_array_elt (AVS_Value v, int index)
Definition at line 510 of file avxsynth_c.h.
avs_new_value_bool()
AVSC_INLINE AVS_Value avs_new_value_bool (int v0)
Definition at line 515 of file avxsynth_c.h.
avs_new_value_int()
AVSC_INLINE AVS_Value avs_new_value_int (int v0)
Definition at line 517 of file avxsynth_c.h.
avs_new_value_string()
AVSC_INLINE AVS_Value avs_new_value_string (const char * v0)
Definition at line 519 of file avxsynth_c.h.
avs_new_value_float()
AVSC_INLINE AVS_Value avs_new_value_float (float v0)
Definition at line 521 of file avxsynth_c.h.
avs_new_value_error()
AVSC_INLINE AVS_Value avs_new_value_error (const char * v0)
Definition at line 523 of file avxsynth_c.h.
avs_new_value_clip()
AVSC_INLINE AVS_Value avs_new_value_clip (AVS_Clip * v0)
Definition at line 526 of file avxsynth_c.h.
avs_new_value_array()
AVSC_INLINE AVS_Value avs_new_value_array (AVS_Value * v0, int size)
Definition at line 529 of file avxsynth_c.h.
AVSC_API() [7/38]
AVSC_API (void , avs_release_clip)
AVSC_API() [8/38]
AVSC_API (AVS_Clip * , avs_copy_clip)
AVSC_API() [9/38]
AVSC_API (const char * , avs_clip_get_error)
AVSC_API() [10/38]
AVSC_API (const AVS_VideoInfo * , avs_get_video_info)
AVSC_API() [11/38]
AVSC_API (int , avs_get_version)
AVSC_API() [12/38]
AVSC_API (AVS_VideoFrame * , avs_get_frame)
AVSC_API() [13/38]
AVSC_API (int , avs_get_parity)
AVSC_API() [14/38]
AVSC_API (int , avs_get_audio)
AVSC_API() [15/38]
AVSC_API (int , avs_set_cache_hints)
AVSC_API() [16/38]
AVSC_API (AVS_Clip * , avs_new_c_filter)
AVSC_API() [17/38]
AVSC_API (const char * , avs_get_error)
AVSC_API() [18/38]
AVSC_API (long , avs_get_cpu_flags)
AVSC_API() [19/38]
AVSC_API (int , avs_check_version)
AVSC_API() [20/38]
AVSC_API (char * , avs_save_string)
AVSC_API() [21/38]
AVSC_API (char * , avs_sprintf)
AVSC_API() [22/38]
const char AVSC_API (char * , avs_vsprintf)
AVSC_API() [23/38]
AVSC_API (int , avs_add_function)
AVSC_API() [24/38]
AVSC_API (int , avs_function_exists)
AVSC_API() [25/38]
AVSC_API (AVS_Value , avs_invoke)
AVSC_API() [26/38]
AVSC_API (AVS_Value , avs_get_var)
AVSC_API() [27/38]
AVSC_API (int , avs_set_var)
AVSC_API() [28/38]
AVSC_API (int , avs_set_global_var)
AVSC_API() [29/38]
AVSC_API (AVS_VideoFrame * , avs_new_video_frame_a)
avs_new_video_frame()
AVSC_INLINE AVS_VideoFrame* avs_new_video_frame (AVS_ScriptEnvironment * env, const AVS_VideoInfo * vi)
Definition at line 674 of file avxsynth_c.h.
avs_new_frame()
AVSC_INLINE AVS_VideoFrame* avs_new_frame (AVS_ScriptEnvironment * env, const AVS_VideoInfo * vi)
Definition at line 679 of file avxsynth_c.h.
AVSC_API() [30/38]
AVSC_API (int , avs_make_writable)
AVSC_API() [31/38]
AVSC_API (void , avs_bit_blt)
AVSC_API() [32/38]
AVSC_API (void , avs_at_exit)
AVSC_API() [33/38]
AVSC_API (AVS_VideoFrame * , avs_subframe)
AVSC_API() [34/38]
AVSC_API (int , avs_set_memory_max)
AVSC_API() [35/38]
AVSC_API (int , avs_set_working_dir)
AVSC_API() [36/38]
AVSC_API (AVS_ScriptEnvironment * , avs_create_script_environment)
avisynth_c_plugin_init()
AVSC_EXPORT const char* AVSC_CC avisynth_c_plugin_init (AVS_ScriptEnvironment * env)
AVSC_API() [37/38]
AVSC_API (void , avs_delete_script_environment)
AVSC_API() [38/38]
AVSC_API (AVS_VideoFrame * , avs_subframe_planar)
Variable Documentation
avs_void
const AVS_Value avs_void = {'v'} static
Definition at line 472 of file avxsynth_c.h.
src
AVS_VideoFrame* src
Definition at line 474 of file avxsynth_c.h.
n
int n
Definition at line 549 of file avxsynth_c.h.
buf
void* buf
Definition at line 555 of file avxsynth_c.h.
start
void INT64 start
Definition at line 555 of file avxsynth_c.h.
count
void INT64 INT64 count
Definition at line 555 of file avxsynth_c.h.
cachehints
int cachehints
Definition at line 560 of file avxsynth_c.h.
frame_range
int size_t frame_range
Definition at line 560 of file avxsynth_c.h.
fi
AVS_FilterInfo* * fi
Definition at line 603 of file avxsynth_c.h.
child
AVS_FilterInfo AVS_Value child
Definition at line 603 of file avxsynth_c.h.
store_child
AVS_FilterInfo AVS_Value int store_child
Definition at line 603 of file avxsynth_c.h.
version
int version
Definition at line 637 of file avxsynth_c.h.
s
const char* s
Definition at line 639 of file avxsynth_c.h.
length
const char int length
Definition at line 639 of file avxsynth_c.h.
fmt
const char const char* fmt
Definition at line 640 of file avxsynth_c.h.
val
const char const AVS_Value val
Definition at line 642 of file avxsynth_c.h.
name
const char* name
Definition at line 646 of file avxsynth_c.h.
params
const char const char* params
Definition at line 646 of file avxsynth_c.h.
apply
const char const char AVS_ApplyFunc apply
Definition at line 646 of file avxsynth_c.h.
user_data
AVS_ShutdownFunc void* user_data
Definition at line 646 of file avxsynth_c.h.
args
const char AVS_Value args
Definition at line 651 of file avxsynth_c.h.
arg_names
const char AVS_Value const char** arg_names
Definition at line 651 of file avxsynth_c.h.
vi
const AVS_VideoInfo* vi
Definition at line 666 of file avxsynth_c.h.
align
const AVS_VideoInfo int align
Definition at line 666 of file avxsynth_c.h.
pvf
AVS_VideoFrame* * pvf
Definition at line 688 of file avxsynth_c.h.
dstp
unsigned char* dstp
Definition at line 690 of file avxsynth_c.h.
dst_pitch
unsigned char int dst_pitch
Definition at line 690 of file avxsynth_c.h.
srcp
unsigned char int const unsigned char* srcp
Definition at line 690 of file avxsynth_c.h.
src_pitch
unsigned char int const unsigned char int src_pitch
Definition at line 690 of file avxsynth_c.h.
row_size
unsigned char int const unsigned char int int row_size
Definition at line 690 of file avxsynth_c.h.
height
unsigned char int const unsigned char int int int height
Definition at line 690 of file avxsynth_c.h.
function
AVS_ShutdownFunc function
Definition at line 693 of file avxsynth_c.h.
rel_offset
AVS_VideoFrame int rel_offset
Definition at line 695 of file avxsynth_c.h.
new_pitch
AVS_VideoFrame int int new_pitch
Definition at line 695 of file avxsynth_c.h.
new_row_size
AVS_VideoFrame int int int new_row_size
Definition at line 695 of file avxsynth_c.h.
new_height
AVS_VideoFrame int int int int new_height
Definition at line 695 of file avxsynth_c.h.
mem
int mem
Definition at line 698 of file avxsynth_c.h.
newdir
const char* newdir
Definition at line 700 of file avxsynth_c.h.
rel_offsetU
AVS_VideoFrame int int int int int rel_offsetU
Definition at line 722 of file avxsynth_c.h.
rel_offsetV
AVS_VideoFrame int int int int int int rel_offsetV
Definition at line 722 of file avxsynth_c.h.
new_pitchUV
AVS_VideoFrame int int int int int int int new_pitchUV
Definition at line 722 of file avxsynth_c.h.