FFmpeg: libavcodec/bgmc.h File Reference
bgmc.h File Reference
Block Gilbert-Moore decoder header.
#include "avcodec.h"
#include "get_bits.h"
Functions
int ff_bgmc_init (AVCodecContext *avctx, uint8_t **cf_lut, int **cf_lut_status)
Initialize the lookup table arrays.
void ff_bgmc_end (uint8_t **cf_lut, int **cf_lut_status)
Release the lookup table arrays.
void ff_bgmc_decode_init (GetBitContext *gb, unsigned int *h, unsigned int *l, unsigned int *v)
Initialize decoding and reads the first value.
void ff_bgmc_decode_end (GetBitContext *gb)
Finish decoding.
void ff_bgmc_decode (GetBitContext *gb, unsigned int num, int32_t *dst, int delta, unsigned int sx, unsigned int *h, unsigned int *l, unsigned int *v, uint8_t *cf_lut, int *cf_lut_status)
Read and decode a block Gilbert-Moore coded symbol.
Detailed Description
Block Gilbert-Moore decoder header.
Author
Thilo Borgmann <thilo.borgmann at mail.de>
Definition in file bgmc.h.
Function Documentation
ff_bgmc_init()
int ff_bgmc_init (AVCodecContext * avctx, uint8_t ** cf_lut, int ** cf_lut_status)
Initialize the lookup table arrays.
Definition at line 460 of file bgmc.c.
Referenced by decode_init().
ff_bgmc_end()
void ff_bgmc_end (uint8_t ** cf_lut, int ** cf_lut_status)
Release the lookup table arrays.
Definition at line 480 of file bgmc.c.
Referenced by decode_end(), and ff_bgmc_init().
ff_bgmc_decode_init()
void ff_bgmc_decode_init (GetBitContext * gb, unsigned int * h, unsigned int * l, unsigned int * v)
Initialize decoding and reads the first value.
Definition at line 488 of file bgmc.c.
Referenced by read_var_block_data().
ff_bgmc_decode_end()
void ff_bgmc_decode_end (GetBitContext * gb)
Finish decoding.
Definition at line 498 of file bgmc.c.
Referenced by read_var_block_data().
ff_bgmc_decode()
void ff_bgmc_decode (GetBitContext * gb, unsigned int num, int32_t * dst, int delta, unsigned int sx, unsigned int * h, unsigned int * l, unsigned int * v, uint8_t * cf_lut, int * cf_lut_status)
Read and decode a block Gilbert-Moore coded symbol.
Definition at line 505 of file bgmc.c.
Referenced by read_var_block_data().