FFmpeg: libavcodec/binkaudio.c File Reference
binkaudio.c File Reference
Bink Audio decoder.
#include "libavutil/channel_layout.h"
#include "libavutil/intfloat.h"
#include "avcodec.h"
#include "dct.h"
#include "get_bits.h"
#include "internal.h"
#include "rdft.h"
#include "wma_freqs.h"
Data Structures
struct BinkAudioContext
Macros
#define BITSTREAM_READER_LE
#define MAX_CHANNELS 2
#define BINK_BLOCK_MAX_SIZE (MAX_CHANNELS << 11)
Functions
static av_cold int decode_init (AVCodecContext *avctx)
static float get_float (GetBitContext *gb)
static int decode_block (BinkAudioContext *s, float **out, int use_dct)
Decode Bink Audio block.
static av_cold int decode_end (AVCodecContext *avctx)
static void get_bits_align32 (GetBitContext *s)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame_ptr, AVPacket *avpkt)
Variables
static float quant_table [96]
static const uint8_t rle_length_tab [16]
AVCodec ff_binkaudio_rdft_decoder
AVCodec ff_binkaudio_dct_decoder
Detailed Description
Bink Audio decoder.
Technical details here: http://wiki.multimedia.cx/index.php?title=Bink_Audio
Definition in file binkaudio.c.
Macro Definition Documentation
BITSTREAM_READER_LE
#define BITSTREAM_READER_LE
Definition at line 34 of file binkaudio.c.
MAX_CHANNELS
#define MAX_CHANNELS 2
Definition at line 44 of file binkaudio.c.
Referenced by decode_init().
BINK_BLOCK_MAX_SIZE
#define BINK_BLOCK_MAX_SIZE (MAX_CHANNELS << 11)
Definition at line 45 of file binkaudio.c.
Function Documentation
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 68 of file binkaudio.c.
get_float()
static float get_float (GetBitContext * gb) static
Definition at line 146 of file binkaudio.c.
Referenced by decode_block().
decode_block()
static int decode_block (BinkAudioContext * s, float ** out, int use_dct) static
Decode Bink Audio block.
Parameters
[out] out Output buffer (must contain s->block_size elements)
Returns
0 on success, negative error code on failure
Definition at line 164 of file binkaudio.c.
Referenced by decode_frame().
decode_end()
static av_cold int decode_end (AVCodecContext * avctx) static
Definition at line 268 of file binkaudio.c.
get_bits_align32()
static void get_bits_align32 (GetBitContext * s) static
Definition at line 281 of file binkaudio.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame_ptr, AVPacket * avpkt) static
Definition at line 287 of file binkaudio.c.
Variable Documentation
quant_table
float quant_table[96] static
Definition at line 42 of file binkaudio.c.
Referenced by decode_block(), decode_init(), read_quant_tables(), and write_quant_tables().
rle_length_tab
const uint8_t rle_length_tab[16] static
Initial value:
= {
    2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 32, 64
}
Definition at line 155 of file binkaudio.c.
Referenced by decode_block().
ff_binkaudio_rdft_decoder
AVCodec ff_binkaudio_rdft_decoder
Initial value:
= {
    .name           = "binkaudio_rdft",
    .long_name      = NULL_IF_CONFIG_SMALL("Bink Audio (RDFT)"),
    .type           = AVMEDIA_TYPE_AUDIO,
    .id             = AV_CODEC_ID_BINKAUDIO_RDFT,
    .priv_data_size = sizeof(BinkAudioContext),
    .init           = decode_init,
    .close          = decode_end,
    .decode         = decode_frame,
    .capabilities   = AV_CODEC_CAP_DELAY | AV_CODEC_CAP_DR1,
}
Definition at line 338 of file binkaudio.c.
ff_binkaudio_dct_decoder
AVCodec ff_binkaudio_dct_decoder
Initial value:
= {
    .name           = "binkaudio_dct",
    .long_name      = NULL_IF_CONFIG_SMALL("Bink Audio (DCT)"),
    .type           = AVMEDIA_TYPE_AUDIO,
    .id             = AV_CODEC_ID_BINKAUDIO_DCT,
    .priv_data_size = sizeof(BinkAudioContext),
    .init           = decode_init,
    .close          = decode_end,
    .decode         = decode_frame,
    .capabilities   = AV_CODEC_CAP_DELAY | AV_CODEC_CAP_DR1,
}
Definition at line 350 of file binkaudio.c.