FFmpeg: libavcodec/blockdsp.c File Reference
blockdsp.c File Reference
#include <stdint.h>
#include <string.h>
#include "config.h"
#include "libavutil/attributes.h"
#include "avcodec.h"
#include "blockdsp.h"
#include "version.h"
Functions
static void clear_block_c (int16_t *block)
static void clear_blocks_c (int16_t *blocks)
static void fill_block16_c (uint8_t *block, uint8_t value, int line_size, int h)
static void fill_block8_c (uint8_t *block, uint8_t value, int line_size, int h)
av_cold void ff_blockdsp_init (BlockDSPContext *c, AVCodecContext *avctx)
Function Documentation
clear_block_c()
static void clear_block_c (int16_t * block) static
Definition at line 28 of file blockdsp.c.
Referenced by ff_blockdsp_init().
clear_blocks_c()
static void clear_blocks_c (int16_t * blocks) static
Definition at line 33 of file blockdsp.c.
Referenced by ff_blockdsp_init().
fill_block16_c()
static void fill_block16_c (uint8_t * block, uint8_t value, int line_size, int h) static
Definition at line 38 of file blockdsp.c.
Referenced by ff_blockdsp_init().
fill_block8_c()
static void fill_block8_c (uint8_t * block, uint8_t value, int line_size, int h) static
Definition at line 48 of file blockdsp.c.
Referenced by ff_blockdsp_init().
ff_blockdsp_init()
av_cold void ff_blockdsp_init (BlockDSPContext * c, AVCodecContext * avctx)
Definition at line 58 of file blockdsp.c.
Referenced by dct_init(), decode_init(), dnxhd_decode_header(), dnxhd_encode_init(), ff_cavs_init(), ff_intrax8_common_init(), ff_mjpeg_decode_init(), ff_wmv2_common_init(), jpg_init(), mimic_decode_init(), tqi_decode_init(), and vc1_decode_init().