FFmpeg: libavcodec/blockdsp.h File Reference
blockdsp.h File Reference
#include <stdint.h>
#include "avcodec.h"
#include "version.h"
Data Structures
struct BlockDSPContext
Typedefs
typedef void(* op_fill_func) (uint8_t *block, uint8_t value, int line_size, int h)
Functions
void ff_blockdsp_init (BlockDSPContext *c, AVCodecContext *avctx)
void ff_blockdsp_init_alpha (BlockDSPContext *c)
void ff_blockdsp_init_arm (BlockDSPContext *c)
void ff_blockdsp_init_ppc (BlockDSPContext *c)
void ff_blockdsp_init_x86 (BlockDSPContext *c, AVCodecContext *avctx)
void ff_blockdsp_init_mips (BlockDSPContext *c)
Typedef Documentation
op_fill_func
typedef void(* op_fill_func) (uint8_t *block, uint8_t value, int line_size, int h)
Definition at line 31 of file blockdsp.h.
Function Documentation
ff_blockdsp_init()
void ff_blockdsp_init (BlockDSPContext * c, AVCodecContext * avctx)
Definition at line 58 of file blockdsp.c.
Referenced by dct_init(), decode_init(), dnxhd_decode_header(), dnxhd_encode_init(), ff_cavs_init(), ff_intrax8_common_init(), ff_mjpeg_decode_init(), ff_wmv2_common_init(), jpg_init(), mimic_decode_init(), tqi_decode_init(), and vc1_decode_init().
ff_blockdsp_init_alpha()
void ff_blockdsp_init_alpha (BlockDSPContext * c)
Definition at line 46 of file blockdsp_alpha.c.
Referenced by ff_blockdsp_init().
ff_blockdsp_init_arm()
void ff_blockdsp_init_arm (BlockDSPContext * c)
Definition at line 27 of file blockdsp_init_arm.c.
Referenced by ff_blockdsp_init().
ff_blockdsp_init_ppc()
void ff_blockdsp_init_ppc (BlockDSPContext * c)
Definition at line 146 of file blockdsp.c.
Referenced by ff_blockdsp_init().
ff_blockdsp_init_x86()
void ff_blockdsp_init_x86 (BlockDSPContext * c, AVCodecContext * avctx)
Definition at line 34 of file blockdsp_init.c.
Referenced by ff_blockdsp_init().
ff_blockdsp_init_mips()
void ff_blockdsp_init_mips (BlockDSPContext * c)
Definition at line 46 of file blockdsp_init_mips.c.
Referenced by ff_blockdsp_init().