FFmpeg: libavcodec/mips/blockdsp_msa.c File Reference
blockdsp_msa.c File Reference
#include "libavutil/mips/generic_macros_msa.h"
#include "blockdsp_mips.h"
Functions
static void copy_8bit_value_width8_msa (uint8_t *src, uint8_t val, int32_t src_stride, int32_t height)
static void copy_8bit_value_width16_msa (uint8_t *src, uint8_t val, int32_t src_stride, int32_t height)
static void memset_zero_16width_msa (uint8_t *src, int32_t stride, int32_t height)
void ff_fill_block16_msa (uint8_t *src, uint8_t val, int stride, int height)
void ff_fill_block8_msa (uint8_t *src, uint8_t val, int stride, int height)
void ff_clear_block_msa (int16_t *block)
void ff_clear_blocks_msa (int16_t *block)
Function Documentation
copy_8bit_value_width8_msa()
static void copy_8bit_value_width8_msa (uint8_t * src, uint8_t val, int32_t src_stride, int32_t height) static
Definition at line 24 of file blockdsp_msa.c.
Referenced by ff_fill_block8_msa().
copy_8bit_value_width16_msa()
static void copy_8bit_value_width16_msa (uint8_t * src, uint8_t val, int32_t src_stride, int32_t height) static
Definition at line 40 of file blockdsp_msa.c.
Referenced by ff_fill_block16_msa().
memset_zero_16width_msa()
static void memset_zero_16width_msa (uint8_t * src, int32_t stride, int32_t height) static
Definition at line 54 of file blockdsp_msa.c.
Referenced by ff_clear_block_msa(), and ff_clear_blocks_msa().
ff_fill_block16_msa()
void ff_fill_block16_msa (uint8_t * src, uint8_t val, int stride, int height)
Definition at line 68 of file blockdsp_msa.c.
ff_fill_block8_msa()
void ff_fill_block8_msa (uint8_t * src, uint8_t val, int stride, int height)
Definition at line 73 of file blockdsp_msa.c.
ff_clear_block_msa()
void ff_clear_block_msa (int16_t * block)
Definition at line 78 of file blockdsp_msa.c.
ff_clear_blocks_msa()
void ff_clear_blocks_msa (int16_t * block)
Definition at line 83 of file blockdsp_msa.c.