FFmpeg: libavutil/bprint.h File Reference
bprint.h File Reference
#include <stdarg.h>
#include "attributes.h"
#include "avstring.h"
Macros
#define FF_PAD_STRUCTURE(name, size, ...)
Define a structure with extra padding to a fixed size This helps ensuring binary compatibility with future versions.
#define AV_BPRINT_SIZE_UNLIMITED ((unsigned)-1)
#define AV_BPRINT_SIZE_AUTOMATIC 1
#define AV_BPRINT_SIZE_COUNT_ONLY 0
Functions
FF_PAD_STRUCTURE (AVBPrint, 1024, char *str;unsigned len;unsigned size;unsigned size_max;char reserved_internal_buffer[1];) void av_bprint_init(AVBPrint *buf
Buffer to print data progressively.
void av_bprint_init_for_buffer (AVBPrint *buf, char *buffer, unsigned size)
Init a print buffer using a pre-existing buffer.
void av_bprintf (AVBPrint *buf, const char *fmt,...) av_printf_format(2
Append a formatted string to a print buffer.
void void av_vbprintf (AVBPrint *buf, const char *fmt, va_list vl_arg)
Append a formatted string to a print buffer.
void av_bprint_chars (AVBPrint *buf, char c, unsigned n)
Append char c n times to a print buffer.
void av_bprint_append_data (AVBPrint *buf, const char *data, unsigned size)
Append data to a print buffer.
void av_bprint_strftime (AVBPrint *buf, const char *fmt, const struct tm *tm)
Append a formatted date and time to a print buffer.
void av_bprint_get_buffer (AVBPrint *buf, unsigned size, unsigned char **mem, unsigned *actual_size)
Allocate bytes in the buffer for external use.
void av_bprint_clear (AVBPrint *buf)
Reset the string to "" but keep internal allocated data.
static int av_bprint_is_complete (const AVBPrint *buf)
Test if the print buffer is complete (not truncated).
int av_bprint_finalize (AVBPrint *buf, char **ret_str)
Finalize a print buffer.
void av_bprint_escape (AVBPrint *dstbuf, const char *src, const char *special_chars, enum AVEscapeMode mode, int flags)
Escape the content in src and append it to dstbuf.
Variables
unsigned size_init
unsigned unsigned size_max
Macro Definition Documentation
FF_PAD_STRUCTURE
#define FF_PAD_STRUCTURE (name, size, ...)
Value:
struct ff_pad_helper_##name { __VA_ARGS__ }; \
typedef struct name { \
    __VA_ARGS__ \
    char reserved_padding[size - sizeof(struct ff_pad_helper_##name)]; \
} name;
Define a structure with extra padding to a fixed size This helps ensuring binary compatibility with future versions.
Definition at line 34 of file bprint.h.
AV_BPRINT_SIZE_UNLIMITED
#define AV_BPRINT_SIZE_UNLIMITED ((unsigned)-1)
Referenced by ass_read_header(), av_dict_get_string(), av_escape(), av_opt_serialize(), compact_print_str(), convert_sub_to_old_ass_form(), create_ass_text(), disp_tree(), dump_curves(), ff_tadd_bytes_metadata(), ff_tadd_long_metadata(), ff_tadd_rational_metadata(), ff_tadd_shorts_metadata(), ffprobe_show_program_version(), flat_print_str(), ini_print_str(), init(), init_decoder(), json_print_int(), json_print_item_str(), json_print_section_header(), lavfi_read_header(), lavfi_read_packet(), lrc_read_header(), main(), mov_text_decode_frame(), mov_text_encode_init(), mpl2_decode_frame(), mpsub_read_header(), realtext_read_header(), sami_read_header(), show_frame(), show_packet(), show_stream(), show_subtitle(), srt_decode_frame(), srt_encode_init(), srt_read_header(), subviewer_decode_frame(), subviewer_read_header(), text_decode_frame(), validate_string(), webvtt_decode_frame(), webvtt_encode_init(), webvtt_read_header(), write_frame(), writer_open(), writer_print_data(), writer_print_integers(), and xml_print_str().
AV_BPRINT_SIZE_AUTOMATIC
#define AV_BPRINT_SIZE_AUTOMATIC 1
Referenced by configure_input_audio_filter(), ff_jni_exception_get_summary(), ftp_status(), make_command_flags_str(), microdvd_init(), parse_psfile(), query_formats(), validate_string(), writer_open(), and writer_print_rational().
AV_BPRINT_SIZE_COUNT_ONLY
#define AV_BPRINT_SIZE_COUNT_ONLY 0
Function Documentation
FF_PAD_STRUCTURE()
FF_PAD_STRUCTURE (AVBPrint , 1024 , char *str;unsigned len;unsigned size;unsigned size_max;char reserved_internal_buffer; [1])
Buffer to print data progressively.
The string buffer grows as necessary and is always 0-terminated. The content of the string is never accessed, and thus is encoding-agnostic and can even hold binary data.
Small buffers are kept in the structure itself, and thus require no memory allocation at all (unless the contents of the buffer is needed after the structure goes out of scope). This is almost as lightweight as declaring a local "char buf[512]".
The length of the string can go beyond the allocated size: the buffer is then truncated, but the functions still keep account of the actual total length.
In other words, buf->len can be greater than buf->size and records the total length of what would have been to the buffer if there had been enough memory.
Append operations do not need to be tested for failure: if a memory allocation fails, data stop being appended to the buffer, but the length is still updated. This situation can be tested with av_bprint_is_complete().
The size_max field determines several possible behaviours:
size_max = -1 (= UINT_MAX) or any large value will let the buffer be reallocated as necessary, with an amortized linear cost.
size_max = 0 prevents writing anything to the buffer: only the total length is computed. The write operations can then possibly be repeated in a buffer with exactly the necessary size (using size_init = size_max = len + 1).
size_max = 1 is automatically replaced by the exact size available in the structure itself, thus ensuring no dynamic memory allocation. The internal buffer is large enough to hold a reasonable paragraph of text, such as the current paragraph. Convenience macros for special values for av_bprint_init() size_max parameter. Init a print buffer.
Parameters
buf buffer to init
size_init initial size (including the final 0)
size_max maximum size; 0 means do not write anything, just count the length; 1 is replaced by the maximum value for automatic storage; any large value means that the internal buffer will be reallocated as needed up to that limit; -1 is converted to UINT_MAX, the largest limit possible. Check also AV_BPRINT_SIZE_* macros.
av_bprint_init_for_buffer()
void av_bprint_init_for_buffer (AVBPrint * buf, char * buffer, unsigned size)
Init a print buffer using a pre-existing buffer.
The buffer will not be reallocated.
Parameters
buf buffer structure to init
buffer byte buffer to use for the string data
size size of buffer
Definition at line 85 of file bprint.c.
Referenced by av_get_channel_layout_string(), and main().
av_bprintf()
void av_bprintf (AVBPrint * buf, const char * fmt, ...)
Append a formatted string to a print buffer.
av_vbprintf()
void void av_vbprintf (AVBPrint * buf, const char * fmt, va_list vl_arg)
Append a formatted string to a print buffer.
Definition at line 117 of file bprint.c.
Referenced by format_line(), srt_print(), and webvtt_print().
av_bprint_chars()
void av_bprint_chars (AVBPrint * buf, char c, unsigned n)
Append char c n times to a print buffer.
Definition at line 140 of file bprint.c.
Referenced by av_bprint_escape(), av_bprint_utf8(), avfilter_graph_dump_to_buf(), c_escape_str(), csv_escape_str(), expand_filename_template(), expand_text(), ff_ass_bprint_text_event(), ff_htmlmarkup_to_ass(), ff_smil_extract_next_text_chunk(), ff_subtitles_read_text_chunk(), flat_escape_key_str(), flat_escape_value_str(), get_line(), ini_escape_str(), json_escape_str(), lavfi_read_header(), lavfi_read_packet(), main(), make_command_flags_str(), microdvd_decode_frame(), mpl2_event_to_ass(), parse_string(), read_line(), rt_event_to_ass(), sami_paragraph_to_ass(), subviewer_event_to_ass(), text_to_ass(), webvtt_event_to_ass(), write_frame(), writer_print_data(), and xml_escape_str().
av_bprint_append_data()
void av_bprint_append_data (AVBPrint * buf, const char * data, unsigned size)
Append data to a print buffer.
param buf bprint buffer to use param data pointer to data param size size of data
Definition at line 158 of file bprint.c.
Referenced by av_dict_get_string(), av_opt_serialize(), avio_read_to_bprint(), gen_sub_text(), mov_text_new_line_cb(), mov_text_text_cb(), srt_text_cb(), validate_string(), and webvtt_text_cb().
av_bprint_strftime()
void av_bprint_strftime (AVBPrint * buf, const char * fmt, const struct tm * tm)
Append a formatted date and time to a print buffer.
param buf bprint buffer to use param fmt date and time format string, see strftime() param tm broken-down time structure to translate
Note
due to poor design of the standard strftime function, it may produce poor results if the format string expands to a very long text and the bprint buffer is near the limit stated by the size_max option.
Definition at line 176 of file bprint.c.
Referenced by draw_text(), func_pts(), func_strftime(), and main().
av_bprint_get_buffer()
void av_bprint_get_buffer (AVBPrint * buf, unsigned size, unsigned char ** mem, unsigned * actual_size)
Allocate bytes in the buffer for external use.
Parameters
[in] buf buffer structure
[in] size required size
[out] mem pointer to the memory area
[out] actual_size size of the memory area after allocation; can be larger or smaller than size
Definition at line 218 of file bprint.c.
Referenced by decode_zbuf().
av_bprint_clear()
void av_bprint_clear (AVBPrint * buf)
Reset the string to "" but keep internal allocated data.
Definition at line 227 of file bprint.c.
Referenced by add_event(), capture_screen(), compact_print_section_header(), convert_sub_to_old_ass_form(), default_print_section_header(), draw_text(), encode_frame(), expand_text(), ff_subtitles_read_text_chunk(), flat_print_section_header(), flat_print_str(), flush_decoder(), get_line(), ini_print_section_header(), ini_print_str(), json_print_item_str(), microdvd_init(), mov_text_encode_frame(), mov_text_style_cb(), parse_psfile(), read_dialogue(), read_line(), realtext_read_header(), sami_paragraph_to_ass(), sami_read_header(), show_frame(), show_stream(), webvtt_encode_frame(), and xml_print_str().
av_bprint_is_complete()
static int av_bprint_is_complete (const AVBPrint * buf) inline static
Test if the print buffer is complete (not truncated).
It may have been truncated due to a memory allocation failure or the size_max limit (compare size and size_max if necessary).
Definition at line 185 of file bprint.h.
Referenced by av_bprint_alloc(), av_escape(), avio_read_to_bprint(), avpriv_bprint_to_extradata(), capture_screen(), convert_sub_to_old_ass_form(), create_ass_text(), draw_text(), encode_frame(), expand_text(), ff_bprint_to_codecpar_extradata(), gen_sub_text(), icecast_open(), init_report(), lavfi_read_header(), lavfi_read_packet(), main(), mov_text_encode_frame(), parse_string(), webvtt_encode_frame(), and write_frame().
av_bprint_finalize()
int av_bprint_finalize (AVBPrint * buf, char ** ret_str)
Finalize a print buffer.
The print buffer can no longer be used afterwards, but the len and size fields are still valid.
[out] ret_str if not NULL, used to return a permanent copy of the buffer contents, or NULL if memory allocation fails; if NULL, the buffer is discarded and freed
Returns
0 for success or error code (probably AVERROR(ENOMEM))
Definition at line 235 of file bprint.c.
Referenced by ass_read_header(), av_bprint_is_complete(), av_dict_get_string(), av_escape(), av_log_default_callback(), av_log_format_line2(), av_opt_serialize(), avfilter_graph_dump(), avpriv_bprint_to_extradata(), bsf_list_item_name(), close_decoder(), compact_print_str(), configure_output_audio_filter(), convert_sub_to_old_ass_form(), create_ass_text(), decode_text_chunk(), decode_zbuf(), disp_tree(), dump_curves(), ff_bprint_to_codecpar_extradata(), ff_jni_exception_get_summary(), ff_tadd_bytes_metadata(), ff_tadd_doubles_metadata(), ff_tadd_long_metadata(), ff_tadd_rational_metadata(), ff_tadd_shorts_metadata(), ffprobe_show_program_version(), flat_print_str(), ftp_status(), gen_sub_text(), icecast_open(), ini_print_str(), init_report(), jacosub_decode_frame(), json_print_int(), json_print_item_str(), json_print_section_header(), lavfi_read_header(), lavfi_read_packet(), main(), microdvd_decode_frame(), mov_text_decode_frame(), mov_text_encode_close(), mpl2_decode_frame(), mpsub_read_header(), parse_file(), parse_psfile(), parse_string(), print_report(), realtext_decode_frame(), realtext_read_header(), sami_close(), sami_read_header(), show_frame(), show_packet(), show_stream(), show_subtitle(), srt_decode_frame(), srt_encode_close(), srt_read_header(), subviewer_decode_frame(), subviewer_read_header(), text_decode_frame(), uninit(), validate_string(), webvtt_decode_frame(), webvtt_encode_close(), webvtt_read_header(), write_frame(), writer_close(), writer_print_data(), writer_print_integers(), and xml_print_str().
av_bprint_escape()
void av_bprint_escape (AVBPrint * dstbuf, const char * src, const char * special_chars, enum AVEscapeMode mode, int flags)
Escape the content in src and append it to dstbuf.
Parameters
dstbuf already inited destination bprint buffer
src string containing the text to escape
special_chars string containing the special characters which need to be escaped, can be NULL
mode escape mode to employ, see AV_ESCAPE_MODE_* macros. Any unknown value for mode will be considered equivalent to AV_ESCAPE_MODE_BACKSLASH, but this behaviour can change without notice.
flags flags which control how to escape, see AV_ESCAPE_FLAG_* macros
Definition at line 265 of file bprint.c.
Referenced by av_bprint_is_complete(), av_dict_get_string(), av_escape(), and av_opt_serialize().
Variable Documentation
size_init
unsigned size_init
Definition at line 111 of file bprint.h.
size_max
unsigned unsigned size_max
Definition at line 111 of file bprint.h.
Referenced by av_bprint_init().