FFmpeg: libavutil/bprint.c File Reference
bprint.c File Reference
#include <stdarg.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include "avassert.h"
#include "avstring.h"
#include "bprint.h"
#include "common.h"
#include "compat/va_copy.h"
#include "error.h"
#include "mem.h"
Macros
#define av_bprint_room(buf) ((buf)->size - FFMIN((buf)->len, (buf)->size))
#define av_bprint_is_allocated(buf) ((buf)->str != (buf)->reserved_internal_buffer)
#define WHITESPACES " \n\t\r"
Functions
static int av_bprint_alloc (AVBPrint *buf, unsigned room)
static void av_bprint_grow (AVBPrint *buf, unsigned extra_len)
void av_bprint_init (AVBPrint *buf, unsigned size_init, unsigned size_max)
void av_bprint_init_for_buffer (AVBPrint *buf, char *buffer, unsigned size)
Init a print buffer using a pre-existing buffer.
void av_bprintf (AVBPrint *buf, const char *fmt,...)
void av_vbprintf (AVBPrint *buf, const char *fmt, va_list vl_arg)
Append a formatted string to a print buffer.
void av_bprint_chars (AVBPrint *buf, char c, unsigned n)
Append char c n times to a print buffer.
void av_bprint_append_data (AVBPrint *buf, const char *data, unsigned size)
Append data to a print buffer.
void av_bprint_strftime (AVBPrint *buf, const char *fmt, const struct tm *tm)
Append a formatted date and time to a print buffer.
void av_bprint_get_buffer (AVBPrint *buf, unsigned size, unsigned char **mem, unsigned *actual_size)
Allocate bytes in the buffer for external use.
void av_bprint_clear (AVBPrint *buf)
Reset the string to "" but keep internal allocated data.
int av_bprint_finalize (AVBPrint *buf, char **ret_str)
Finalize a print buffer.
void av_bprint_escape (AVBPrint *dstbuf, const char *src, const char *special_chars, enum AVEscapeMode mode, int flags)
Escape the content in src and append it to dstbuf.
Macro Definition Documentation
av_bprint_room
#define av_bprint_room (buf) ((buf)->size - FFMIN((buf)->len, (buf)->size))
Definition at line 33 of file bprint.c.
Referenced by av_bprint_append_data(), av_bprint_chars(), av_bprint_get_buffer(), av_bprint_strftime(), av_bprintf(), and av_vbprintf().
av_bprint_is_allocated
#define av_bprint_is_allocated (buf) ((buf)->str != (buf)->reserved_internal_buffer)
Definition at line 34 of file bprint.c.
Referenced by av_bprint_alloc(), and av_bprint_finalize().
WHITESPACES
#define WHITESPACES " \n\t\r"
Definition at line 263 of file bprint.c.
Referenced by av_bprint_escape().
Function Documentation
av_bprint_alloc()
static int av_bprint_alloc (AVBPrint * buf, unsigned room) static
Definition at line 36 of file bprint.c.
Referenced by av_bprint_append_data(), av_bprint_chars(), av_bprint_get_buffer(), av_bprint_init(), av_bprint_strftime(), av_bprintf(), and av_vbprintf().
av_bprint_grow()
static void av_bprint_grow (AVBPrint * buf, unsigned extra_len) static
Definition at line 60 of file bprint.c.
Referenced by av_bprint_append_data(), av_bprint_chars(), av_bprint_strftime(), av_bprintf(), and av_vbprintf().
av_bprint_init()
void av_bprint_init (AVBPrint * buf, unsigned size_init, unsigned size_max)
Definition at line 69 of file bprint.c.
Referenced by ass_read_header(), av_dict_get_string(), av_escape(), av_opt_serialize(), avfilter_graph_dump(), bsf_list_item_name(), compact_print_str(), config_output(), configure_input_audio_filter(), configure_input_video_filter(), configure_output_audio_filter(), convert_sub_to_old_ass_form(), create_ass_text(), decode_zbuf(), disp_tree(), dump_curves(), dvdsub_init(), ff_jni_exception_get_summary(), ff_tadd_bytes_metadata(), ff_tadd_doubles_metadata(), ff_tadd_long_metadata(), ff_tadd_rational_metadata(), ff_tadd_shorts_metadata(), ffprobe_show_program_version(), flat_print_str(), format_line(), ftp_status(), gen_sub_text(), icecast_open(), ini_print_str(), init(), init_decoder(), init_report(), jacosub_decode_frame(), jacosub_read_header(), json_print_int(), json_print_item_str(), json_print_section_header(), lavfi_read_header(), lavfi_read_packet(), lrc_read_header(), main(), make_command_flags_str(), microdvd_decode_frame(), microdvd_init(), mov_text_decode_frame(), mov_text_encode_init(), mpl2_decode_frame(), mpsub_read_header(), parse_psfile(), parse_string(), print_report(), query_formats(), realtext_decode_frame(), realtext_read_header(), sami_init(), sami_read_header(), show_frame(), show_packet(), show_stream(), show_subtitle(), srt_decode_frame(), srt_encode_init(), srt_read_header(), subviewer_decode_frame(), subviewer_read_header(), text_decode_frame(), validate_string(), webvtt_decode_frame(), webvtt_encode_init(), webvtt_read_header(), write_frame(), writer_open(), writer_print_data(), writer_print_integers(), writer_print_rational(), and xml_print_str().
av_bprint_init_for_buffer()
void av_bprint_init_for_buffer (AVBPrint * buf, char * buffer, unsigned size)
Init a print buffer using a pre-existing buffer.
The buffer will not be reallocated.
Parameters
buf buffer structure to init
buffer byte buffer to use for the string data
size size of buffer
Definition at line 85 of file bprint.c.
Referenced by av_get_channel_layout_string(), and main().
av_bprintf()
void av_bprintf (AVBPrint * buf, const char * fmt, ...)
Definition at line 94 of file bprint.c.
Referenced by add_event(), ass_read_header(), audio_frame_cksum(), av_bprint_channel_layout(), av_bprint_escape(), av_bprint_strftime(), avfilter_graph_dump_to_buf(), bprint_bytes(), bprint_pascal(), bsf_list_item_name(), c_escape_str(), capture_screen(), cat_header(), compact_print_section_header(), config_output(), configure_input_audio_filter(), configure_input_video_filter(), configure_output_audio_filter(), convert_sub_to_old_ass_form(), default_print_section_header(), disp_node(), disp_tree(), draw_text(), dump_curves(), dvdsub_init(), expand_filename_template(), ff_ass_bprint_text_event(), ff_htmlmarkup_to_ass(), ff_jni_exception_get_summary(), ff_subtitles_read_text_chunk(), ff_tadd_bytes_metadata(), ff_tadd_doubles_metadata(), ff_tadd_long_metadata(), ff_tadd_rational_metadata(), ff_tadd_shorts_metadata(), flat_escape_value_str(), flat_print_section_header(), format_line(), ftp_status(), func_eval_expr(), func_eval_expr_int_format(), func_frame_num(), func_metadata(), func_pict_type(), func_pts(), gen_sub_text(), ini_escape_str(), ini_print_section_header(), insert_datetime(), insert_text(), insert_ts(), jacosub_read_header(), jacosub_to_ass(), json_escape_str(), lavfi_read_packet(), make_command_flags_str(), microdvd_close_no_persistent_tags(), microdvd_decode_frame(), microdvd_init(), microdvd_open_tags(), mpl2_event_to_ass(), parse_psfile(), print_link_prop(), print_report(), query_formats(), read_dialogue(), rt_event_to_ass(), sami_paragraph_to_ass(), sami_read_header(), srt_read_header(), srt_to_ass(), subviewer_event_to_ass(), subviewer_read_header(), text_to_ass(), validate_string(), video_frame_cksum(), webvtt_event_to_ass(), write_frame(), writer_print_data(), writer_print_integers(), writer_print_rational(), and xml_escape_str().
av_vbprintf()
void av_vbprintf (AVBPrint * buf, const char * fmt, va_list vl_arg)
Append a formatted string to a print buffer.
Definition at line 117 of file bprint.c.
Referenced by format_line(), srt_print(), and webvtt_print().
av_bprint_chars()
void av_bprint_chars (AVBPrint * buf, char c, unsigned n)
Append char c n times to a print buffer.
Definition at line 140 of file bprint.c.
Referenced by av_bprint_escape(), av_bprint_utf8(), avfilter_graph_dump_to_buf(), c_escape_str(), csv_escape_str(), expand_filename_template(), expand_text(), ff_ass_bprint_text_event(), ff_htmlmarkup_to_ass(), ff_smil_extract_next_text_chunk(), ff_subtitles_read_text_chunk(), flat_escape_key_str(), flat_escape_value_str(), get_line(), ini_escape_str(), json_escape_str(), lavfi_read_header(), lavfi_read_packet(), main(), make_command_flags_str(), microdvd_decode_frame(), mpl2_event_to_ass(), parse_string(), read_line(), rt_event_to_ass(), sami_paragraph_to_ass(), subviewer_event_to_ass(), text_to_ass(), webvtt_event_to_ass(), write_frame(), writer_print_data(), and xml_escape_str().
av_bprint_append_data()
void av_bprint_append_data (AVBPrint * buf, const char * data, unsigned size)
Append data to a print buffer.
param buf bprint buffer to use param data pointer to data param size size of data
Definition at line 158 of file bprint.c.
Referenced by av_dict_get_string(), av_opt_serialize(), avio_read_to_bprint(), gen_sub_text(), mov_text_new_line_cb(), mov_text_text_cb(), srt_text_cb(), validate_string(), and webvtt_text_cb().
av_bprint_strftime()
void av_bprint_strftime (AVBPrint * buf, const char * fmt, const struct tm * tm)
Append a formatted date and time to a print buffer.
param buf bprint buffer to use param fmt date and time format string, see strftime() param tm broken-down time structure to translate
Note
due to poor design of the standard strftime function, it may produce poor results if the format string expands to a very long text and the bprint buffer is near the limit stated by the size_max option.
Definition at line 176 of file bprint.c.
Referenced by draw_text(), func_pts(), func_strftime(), and main().
av_bprint_get_buffer()
void av_bprint_get_buffer (AVBPrint * buf, unsigned size, unsigned char ** mem, unsigned * actual_size)
Allocate bytes in the buffer for external use.
Parameters
[in] buf buffer structure
[in] size required size
[out] mem pointer to the memory area
[out] actual_size size of the memory area after allocation; can be larger or smaller than size
Definition at line 218 of file bprint.c.
Referenced by decode_zbuf().
av_bprint_clear()
void av_bprint_clear (AVBPrint * buf)
Reset the string to "" but keep internal allocated data.
Definition at line 227 of file bprint.c.
Referenced by add_event(), capture_screen(), compact_print_section_header(), convert_sub_to_old_ass_form(), default_print_section_header(), draw_text(), encode_frame(), expand_text(), ff_subtitles_read_text_chunk(), flat_print_section_header(), flat_print_str(), flush_decoder(), get_line(), ini_print_section_header(), ini_print_str(), json_print_item_str(), microdvd_init(), mov_text_encode_frame(), mov_text_style_cb(), parse_psfile(), read_dialogue(), read_line(), realtext_read_header(), sami_paragraph_to_ass(), sami_read_header(), show_frame(), show_stream(), webvtt_encode_frame(), and xml_print_str().
av_bprint_finalize()
int av_bprint_finalize (AVBPrint * buf, char ** ret_str)
Finalize a print buffer.
The print buffer can no longer be used afterwards, but the len and size fields are still valid.
[out] ret_str if not NULL, used to return a permanent copy of the buffer contents, or NULL if memory allocation fails; if NULL, the buffer is discarded and freed
Returns
0 for success or error code (probably AVERROR(ENOMEM))
Definition at line 235 of file bprint.c.
Referenced by ass_read_header(), av_bprint_is_complete(), av_dict_get_string(), av_escape(), av_log_default_callback(), av_log_format_line2(), av_opt_serialize(), avfilter_graph_dump(), avpriv_bprint_to_extradata(), bsf_list_item_name(), close_decoder(), compact_print_str(), configure_output_audio_filter(), convert_sub_to_old_ass_form(), create_ass_text(), decode_text_chunk(), decode_zbuf(), disp_tree(), dump_curves(), ff_bprint_to_codecpar_extradata(), ff_jni_exception_get_summary(), ff_tadd_bytes_metadata(), ff_tadd_doubles_metadata(), ff_tadd_long_metadata(), ff_tadd_rational_metadata(), ff_tadd_shorts_metadata(), ffprobe_show_program_version(), flat_print_str(), ftp_status(), gen_sub_text(), icecast_open(), ini_print_str(), init_report(), jacosub_decode_frame(), json_print_int(), json_print_item_str(), json_print_section_header(), lavfi_read_header(), lavfi_read_packet(), main(), microdvd_decode_frame(), mov_text_decode_frame(), mov_text_encode_close(), mpl2_decode_frame(), mpsub_read_header(), parse_file(), parse_psfile(), parse_string(), print_report(), realtext_decode_frame(), realtext_read_header(), sami_close(), sami_read_header(), show_frame(), show_packet(), show_stream(), show_subtitle(), srt_decode_frame(), srt_encode_close(), srt_read_header(), subviewer_decode_frame(), subviewer_read_header(), text_decode_frame(), uninit(), validate_string(), webvtt_decode_frame(), webvtt_encode_close(), webvtt_read_header(), write_frame(), writer_close(), writer_print_data(), writer_print_integers(), and xml_print_str().
av_bprint_escape()
void av_bprint_escape (AVBPrint * dstbuf, const char * src, const char * special_chars, enum AVEscapeMode mode, int flags)
Escape the content in src and append it to dstbuf.
Parameters
dstbuf already inited destination bprint buffer
src string containing the text to escape
special_chars string containing the special characters which need to be escaped, can be NULL
mode escape mode to employ, see AV_ESCAPE_MODE_* macros. Any unknown value for mode will be considered equivalent to AV_ESCAPE_MODE_BACKSLASH, but this behaviour can change without notice.
flags flags which control how to escape, see AV_ESCAPE_FLAG_* macros
Definition at line 265 of file bprint.c.
Referenced by av_bprint_is_complete(), av_dict_get_string(), av_escape(), and av_opt_serialize().