FFmpeg: libavformat/brstm.c File Reference
brstm.c File Reference
#include "libavutil/intreadwrite.h"
#include "libavcodec/bytestream.h"
#include "avformat.h"
#include "internal.h"
Data Structures
struct BRSTMDemuxContext
Functions
static int probe (AVProbeData *p)
static int probe_bfstm (AVProbeData *p)
static int read_close (AVFormatContext *s)
static av_always_inline unsigned int read16 (AVFormatContext *s)
static av_always_inline unsigned int read32 (AVFormatContext *s)
static int read_header (AVFormatContext *s)
static int read_packet (AVFormatContext *s, AVPacket *pkt)
static int read_seek (AVFormatContext *s, int stream_index, int64_t timestamp, int flags)
Variables
AVInputFormat ff_brstm_demuxer
AVInputFormat ff_bfstm_demuxer
Function Documentation
probe()
static int probe (AVProbeData * p) static
Definition at line 41 of file brstm.c.
probe_bfstm()
static int probe_bfstm (AVProbeData * p) static
Definition at line 50 of file brstm.c.
read_close()
static int read_close (AVFormatContext * s) static
Definition at line 60 of file brstm.c.
Referenced by read_header().
read16()
static av_always_inline unsigned int read16 (AVFormatContext * s) static
Definition at line 70 of file brstm.c.
Referenced by read_header().
read32()
static av_always_inline unsigned int read32 (AVFormatContext * s) static
Definition at line 79 of file brstm.c.
Referenced by read_header().
read_header()
static int read_header (AVFormatContext * s) static
Definition at line 88 of file brstm.c.
read_packet()
static int read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 358 of file brstm.c.
read_seek()
static int read_seek (AVFormatContext * s, int stream_index, int64_t timestamp, int flags) static
Definition at line 443 of file brstm.c.
Variable Documentation
ff_brstm_demuxer
AVInputFormat ff_brstm_demuxer
Initial value:
= {
    .name           = "brstm",
    .long_name      = NULL_IF_CONFIG_SMALL("BRSTM (Binary Revolution Stream)"),
    .priv_data_size = sizeof(BRSTMDemuxContext),
    .read_probe     = probe,
    .read_header    = read_header,
    .read_packet    = read_packet,
    .read_close     = read_close,
    .read_seek      = read_seek,
    .extensions     = "brstm",
}
Definition at line 461 of file brstm.c.
ff_bfstm_demuxer
AVInputFormat ff_bfstm_demuxer
Initial value:
= {
    .name           = "bfstm",
    .long_name      = NULL_IF_CONFIG_SMALL("BFSTM (Binary Cafe Stream)"),
    .priv_data_size = sizeof(BRSTMDemuxContext),
    .read_probe     = probe_bfstm,
    .read_header    = read_header,
    .read_packet    = read_packet,
    .read_close     = read_close,
    .read_seek      = read_seek,
    .extensions     = "bfstm,bcstm",
}
Definition at line 473 of file brstm.c.