FFmpeg: libavcodec/bsf.c File Reference
bsf.c File Reference
#include <string.h>
#include "libavutil/log.h"
#include "libavutil/mem.h"
#include "libavutil/opt.h"
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/bprint.h"
#include "avcodec.h"
#include "bsf.h"
Data Structures
struct AVBSFInternal
struct BSFListContext
struct AVBSFList
Structure for chain/list of bitstream filters.
Functions
void av_bsf_free (AVBSFContext **pctx)
Free a bitstream filter context and everything associated with it; write NULL into the supplied pointer.
static void * bsf_child_next (void *obj, void *prev)
const AVClass * av_bsf_get_class (void)
Get the AVClass for AVBSFContext.
int av_bsf_alloc (const AVBitStreamFilter *filter, AVBSFContext **pctx)
Allocate a context for a given bitstream filter.
int av_bsf_init (AVBSFContext *ctx)
Prepare the filter for use, after all the parameters and options have been set.
int av_bsf_send_packet (AVBSFContext *ctx, AVPacket *pkt)
Submit a packet for filtering.
int av_bsf_receive_packet (AVBSFContext *ctx, AVPacket *pkt)
Retrieve a filtered packet.
int ff_bsf_get_packet (AVBSFContext *ctx, AVPacket **pkt)
Called by the bitstream filters to get the next packet for filtering.
int ff_bsf_get_packet_ref (AVBSFContext *ctx, AVPacket *pkt)
Called by bitstream filters to get packet for filtering.
static int bsf_list_init (AVBSFContext *bsf)
static int bsf_list_filter (AVBSFContext *bsf, AVPacket *out)
static void bsf_list_close (AVBSFContext *bsf)
static const char * bsf_list_item_name (void *ctx)
AVBSFList * av_bsf_list_alloc (void)
Allocate empty list of bitstream filters.
void av_bsf_list_free (AVBSFList **lst)
Free list of bitstream filters.
int av_bsf_list_append (AVBSFList *lst, AVBSFContext *bsf)
Append bitstream filter to the list of bitstream filters.
int av_bsf_list_append2 (AVBSFList *lst, const char *bsf_name, AVDictionary **options)
Construct new bitstream filter context given it's name and options and append it to the list of bitstream filters.
int av_bsf_list_finalize (AVBSFList **lst, AVBSFContext **bsf)
Finalize list of bitstream filters.
static int bsf_parse_single (const char *str, AVBSFList *bsf_lst)
int av_bsf_list_parse_str (const char *str, AVBSFContext **bsf_lst)
Parse string describing list of bitstream filters and create single AVBSFContext describing the whole chain of bitstream filters.
int av_bsf_get_null_filter (AVBSFContext **bsf)
Get null/pass-through bitstream filter.
Variables
static const AVClass bsf_class
static const AVClass bsf_list_class
const AVBitStreamFilter ff_list_bsf
Function Documentation
bsf_child_next()
static void* bsf_child_next (void * obj, void * prev) static
Definition at line 61 of file bsf.c.
ff_bsf_get_packet()
int ff_bsf_get_packet (AVBSFContext * ctx, AVPacket ** pkt)
Called by the bitstream filters to get the next packet for filtering.
The filter is responsible for either freeing the packet or passing it to the caller.
Definition at line 204 of file bsf.c.
Referenced by aac_adtstoasc_filter(), chomp_filter(), dca_core_filter(), dump_extradata(), h264_mp4toannexb_filter(), hevc_mp4toannexb_filter(), imx_dump_header(), mjpeg2jpeg_filter(), mjpega_dump_header(), mov2textsub(), mp3_header_decompress(), mpeg4_unpack_bframes_filter(), noise(), remove_extradata(), text2movsub(), and vp9_superframe_filter().
ff_bsf_get_packet_ref()
int ff_bsf_get_packet_ref (AVBSFContext * ctx, AVPacket * pkt)
Called by bitstream filters to get packet for filtering.
The reference to packet is moved to provided packet structure.
Parameters
ctx pointer to AVBSFContext of filter
pkt pointer to packet to move reference to
Returns
0>= on success, negative AVERROR in case of failure
Definition at line 226 of file bsf.c.
Referenced by bsf_list_filter().
bsf_list_init()
static int bsf_list_init (AVBSFContext * bsf) static
Definition at line 255 of file bsf.c.
bsf_list_filter()
static int bsf_list_filter (AVBSFContext * bsf, AVPacket * out) static
Definition at line 284 of file bsf.c.
bsf_list_close()
static void bsf_list_close (AVBSFContext * bsf) static
Definition at line 341 of file bsf.c.
bsf_list_item_name()
static const char* bsf_list_item_name (void * ctx) static
Definition at line 352 of file bsf.c.
bsf_parse_single()
static int bsf_parse_single (const char * str, AVBSFList * bsf_lst) static
Definition at line 475 of file bsf.c.
Referenced by av_bsf_list_parse_str().
Variable Documentation
bsf_class
const AVClass bsf_class static
Initial value:
= {
    .class_name       = "AVBSFContext",
    .item_name        = av_default_item_name,
    .version          = LIBAVUTIL_VERSION_INT,
    .child_next       = bsf_child_next,
    .child_class_next = ff_bsf_child_class_next,
}
Definition at line 69 of file bsf.c.
Referenced by av_bsf_alloc(), and av_bsf_get_class().
bsf_list_class
const AVClass bsf_list_class static
Initial value:
= {
        .class_name = "bsf_list",
        .item_name  = bsf_list_item_name,
        .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 377 of file bsf.c.
ff_list_bsf
const AVBitStreamFilter ff_list_bsf
Initial value:
= {
        .name           = "bsf_list",
        .priv_data_size = sizeof(BSFListContext),
        .priv_class     = &bsf_list_class,
        .init           = bsf_list_init,
        .filter         = bsf_list_filter,
        .close          = bsf_list_close,
}
Definition at line 383 of file bsf.c.