FFmpeg: libavcodec/bsf.h File Reference
bsf.h File Reference
#include "avcodec.h"
Functions
int ff_bsf_get_packet (AVBSFContext *ctx, AVPacket **pkt)
Called by the bitstream filters to get the next packet for filtering.
int ff_bsf_get_packet_ref (AVBSFContext *ctx, AVPacket *pkt)
Called by bitstream filters to get packet for filtering.
const AVClass * ff_bsf_child_class_next (const AVClass *prev)
Function Documentation
ff_bsf_get_packet()
int ff_bsf_get_packet (AVBSFContext * ctx, AVPacket ** pkt)
Called by the bitstream filters to get the next packet for filtering.
The filter is responsible for either freeing the packet or passing it to the caller.
Definition at line 204 of file bsf.c.
Referenced by aac_adtstoasc_filter(), chomp_filter(), dca_core_filter(), dump_extradata(), h264_mp4toannexb_filter(), hevc_mp4toannexb_filter(), imx_dump_header(), mjpeg2jpeg_filter(), mjpega_dump_header(), mov2textsub(), mp3_header_decompress(), mpeg4_unpack_bframes_filter(), noise(), remove_extradata(), text2movsub(), and vp9_superframe_filter().
ff_bsf_get_packet_ref()
int ff_bsf_get_packet_ref (AVBSFContext * ctx, AVPacket * pkt)
Called by bitstream filters to get packet for filtering.
The reference to packet is moved to provided packet structure.
Parameters
ctx pointer to AVBSFContext of filter
pkt pointer to packet to move reference to
Returns
0>= on success, negative AVERROR in case of failure
Definition at line 226 of file bsf.c.
Referenced by bsf_list_filter().
ff_bsf_child_class_next()
const AVClass* ff_bsf_child_class_next (const AVClass * prev)
Definition at line 70 of file bitstream_filters.c.