FFmpeg: libavcodec/bswapdsp.h File Reference
bswapdsp.h File Reference
#include <stdint.h>
Data Structures
struct BswapDSPContext
Functions
void ff_bswapdsp_init (BswapDSPContext *c)
void ff_bswapdsp_init_x86 (BswapDSPContext *c)
Function Documentation
ff_bswapdsp_init()
void ff_bswapdsp_init (BswapDSPContext * c)
Definition at line 49 of file bswapdsp.c.
Referenced by ac3_decode_init(), ape_decode_init(), checkasm_check_bswapdsp(), cllc_decode_init(), decode_init(), ff_asv_common_init(), ff_huffyuv_common_init(), flac_encode_init(), hevc_init_context(), imc_decode_init(), mimic_decode_init(), mp_decode_init(), mpc7_decode_init(), raw_init_decoder(), tqi_decode_init(), truespeech_decode_init(), and utvideo_encode_init().
ff_bswapdsp_init_x86()
void ff_bswapdsp_init_x86 (BswapDSPContext * c)
Definition at line 29 of file bswapdsp_init.c.
Referenced by ff_bswapdsp_init().