FFmpeg: libavcodec/x86/bswapdsp_init.c File Reference
bswapdsp_init.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/x86/cpu.h"
#include "libavcodec/bswapdsp.h"
Functions
void ff_bswap32_buf_sse2 (uint32_t *dst, const uint32_t *src, int w)
void ff_bswap32_buf_ssse3 (uint32_t *dst, const uint32_t *src, int w)
av_cold void ff_bswapdsp_init_x86 (BswapDSPContext *c)
Function Documentation
ff_bswap32_buf_sse2()
void ff_bswap32_buf_sse2 (uint32_t * dst, const uint32_t * src, int w)
Referenced by ff_bswapdsp_init_x86().
ff_bswap32_buf_ssse3()
void ff_bswap32_buf_ssse3 (uint32_t * dst, const uint32_t * src, int w)
Referenced by ff_bswapdsp_init_x86().
ff_bswapdsp_init_x86()
av_cold void ff_bswapdsp_init_x86 (BswapDSPContext * c)
Definition at line 29 of file bswapdsp_init.c.
Referenced by ff_bswapdsp_init().