FFmpeg: libavfilter/buffersrc.c File Reference
buffersrc.c File Reference
memory buffer source filter
#include <float.h>
#include "libavutil/channel_layout.h"
#include "libavutil/common.h"
#include "libavutil/fifo.h"
#include "libavutil/frame.h"
#include "libavutil/imgutils.h"
#include "libavutil/internal.h"
#include "libavutil/opt.h"
#include "libavutil/samplefmt.h"
#include "audio.h"
#include "avfilter.h"
#include "buffersrc.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
Data Structures
struct BufferSourceContext
Macros
#define CHECK_VIDEO_PARAM_CHANGE(s, c, width, height, format)
#define CHECK_AUDIO_PARAM_CHANGE(s, c, srate, ch_layout, ch_count, format)
#define OFFSET(x) offsetof(BufferSourceContext, x)
#define A AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_AUDIO_PARAM
#define V AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Functions
AVBufferSrcParameters * av_buffersrc_parameters_alloc (void)
Allocate a new AVBufferSrcParameters instance.
int av_buffersrc_parameters_set (AVFilterContext *ctx, AVBufferSrcParameters *param)
Initialize the buffersrc or abuffersrc filter with the provided parameters.
int attribute_align_arg av_buffersrc_write_frame (AVFilterContext *ctx, const AVFrame *frame)
Add a frame to the buffer source.
int attribute_align_arg av_buffersrc_add_frame (AVFilterContext *ctx, AVFrame *frame)
Add a frame to the buffer source.
static int av_buffersrc_add_frame_internal (AVFilterContext *ctx, AVFrame *frame, int flags)
int attribute_align_arg av_buffersrc_add_frame_flags (AVFilterContext *ctx, AVFrame *frame, int flags)
Add a frame to the buffer source.
static int push_frame (AVFilterGraph *graph)
static av_cold int init_video (AVFilterContext *ctx)
unsigned av_buffersrc_get_nb_failed_requests (AVFilterContext *buffer_src)
Get the number of failed requests.
AVFILTER_DEFINE_CLASS (buffer)
AVFILTER_DEFINE_CLASS (abuffer)
static av_cold int init_audio (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static int config_props (AVFilterLink *link)
static int request_frame (AVFilterLink *link)
static int poll_frame (AVFilterLink *link)
Variables
static const AVOption buffer_options []
static const AVOption abuffer_options []
static const AVFilterPad avfilter_vsrc_buffer_outputs []
AVFilter ff_vsrc_buffer
static const AVFilterPad avfilter_asrc_abuffer_outputs []
AVFilter ff_asrc_abuffer
Detailed Description
memory buffer source filter
Definition in file buffersrc.c.
Macro Definition Documentation
CHECK_VIDEO_PARAM_CHANGE
#define CHECK_VIDEO_PARAM_CHANGE (s, c, width, height, format)
Value:
if (c->w != width || c->h != height || c->pix_fmt != format) {\
        av_log(s, AV_LOG_INFO, "Changing frame properties on the fly is not supported by all filters.\n");\
    }
Definition at line 70 of file buffersrc.c.
Referenced by av_buffersrc_add_frame_internal().
CHECK_AUDIO_PARAM_CHANGE
#define CHECK_AUDIO_PARAM_CHANGE (s, c, srate, ch_layout, ch_count, format)
Value:
if (c->sample_fmt != format || c->sample_rate != srate ||\
        c->channel_layout != ch_layout || c->channels != ch_count) {\
        av_log(s, AV_LOG_ERROR, "Changing frame properties on the fly is not supported.\n");\
        return AVERROR(EINVAL);\
    }
Definition at line 75 of file buffersrc.c.
Referenced by av_buffersrc_add_frame_internal().
OFFSET
#define OFFSET (x) offsetof(BufferSourceContext, x)
Definition at line 296 of file buffersrc.c.
A
#define A AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_AUDIO_PARAM
Definition at line 297 of file buffersrc.c.
V
#define V AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 298 of file buffersrc.c.
Function Documentation
av_buffersrc_add_frame_internal()
static int av_buffersrc_add_frame_internal (AVFilterContext * ctx, AVFrame * frame, int flags) static
Definition at line 190 of file buffersrc.c.
Referenced by av_buffersrc_add_frame(), and av_buffersrc_add_frame_flags().
push_frame()
static int push_frame (AVFilterGraph * graph) static
Definition at line 176 of file buffersrc.c.
Referenced by av_buffersrc_add_frame_internal().
init_video()
static av_cold int init_video (AVFilterContext * ctx) static
Definition at line 270 of file buffersrc.c.
AVFILTER_DEFINE_CLASS() [1/2]
AVFILTER_DEFINE_CLASS (buffer)
AVFILTER_DEFINE_CLASS() [2/2]
AVFILTER_DEFINE_CLASS (abuffer)
init_audio()
static av_cold int init_audio (AVFilterContext * ctx) static
Definition at line 334 of file buffersrc.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 385 of file buffersrc.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 397 of file buffersrc.c.
config_props()
static int config_props (AVFilterLink * link) static
Definition at line 432 of file buffersrc.c.
request_frame()
static int request_frame (AVFilterLink * link) static
Definition at line 461 of file buffersrc.c.
poll_frame()
static int poll_frame (AVFilterLink * link) static
Definition at line 480 of file buffersrc.c.
Variable Documentation
buffer_options
const AVOption buffer_options[] static
Initial value:
= {
    { "width",         NULL,                     OFFSET(w),                AV_OPT_TYPE_INT,      { .i64 = 0 }, 0, INT_MAX, V },
    { "video_size",    NULL,                     OFFSET(w),                AV_OPT_TYPE_IMAGE_SIZE,                .flags = V },
    { "height",        NULL,                     OFFSET(h),                AV_OPT_TYPE_INT,      { .i64 = 0 }, 0, INT_MAX, V },
    { "pix_fmt",       NULL,                     OFFSET(pix_fmt),          AV_OPT_TYPE_PIXEL_FMT, { .i64 = AV_PIX_FMT_NONE }, .min = AV_PIX_FMT_NONE, .max = INT_MAX, .flags = V },
    { "time_base_num", "deprecated, do not use", OFFSET(time_base.num),    AV_OPT_TYPE_INT,      { .i64 = 0 }, 0, INT_MAX, V },
    { "time_base_den", "deprecated, do not use", OFFSET(time_base.den),    AV_OPT_TYPE_INT,      { .i64 = 0 }, 0, INT_MAX, V },
    { "sar_num",       "deprecated, do not use", OFFSET(pixel_aspect.num), AV_OPT_TYPE_INT,      { .i64 = 0 }, 0, INT_MAX, V },
    { "sar_den",       "deprecated, do not use", OFFSET(pixel_aspect.den), AV_OPT_TYPE_INT,      { .i64 = 0 }, 0, INT_MAX, V },
    { "sar",           "sample aspect ratio",    OFFSET(pixel_aspect),     AV_OPT_TYPE_RATIONAL, { .dbl = 0 }, 0, DBL_MAX, V },
    { "pixel_aspect",  "sample aspect ratio",    OFFSET(pixel_aspect),     AV_OPT_TYPE_RATIONAL, { .dbl = 0 }, 0, DBL_MAX, V },
    { "time_base",     NULL,                     OFFSET(time_base),        AV_OPT_TYPE_RATIONAL, { .dbl = 0 }, 0, DBL_MAX, V },
    { "frame_rate",    NULL,                     OFFSET(frame_rate),       AV_OPT_TYPE_RATIONAL, { .dbl = 0 }, 0, DBL_MAX, V },
    { "sws_param",     NULL,                     OFFSET(sws_param),        AV_OPT_TYPE_STRING,                    .flags = V },
    { NULL },
}
Definition at line 300 of file buffersrc.c.
abuffer_options
const AVOption abuffer_options[] static
Initial value:
= {
    { "time_base",      NULL, OFFSET(time_base),           AV_OPT_TYPE_RATIONAL, { .dbl = 0 }, 0, INT_MAX, A },
    { "sample_rate",    NULL, OFFSET(sample_rate),         AV_OPT_TYPE_INT,      { .i64 = 0 }, 0, INT_MAX, A },
    { "sample_fmt",     NULL, OFFSET(sample_fmt),          AV_OPT_TYPE_SAMPLE_FMT, { .i64 = AV_SAMPLE_FMT_NONE }, .min = AV_SAMPLE_FMT_NONE, .max = INT_MAX, .flags = A },
    { "channel_layout", NULL, OFFSET(channel_layout_str),  AV_OPT_TYPE_STRING,             .flags = A },
    { "channels",       NULL, OFFSET(channels),            AV_OPT_TYPE_INT,      { .i64 = 0 }, 0, INT_MAX, A },
    { NULL },
}
Definition at line 323 of file buffersrc.c.
avfilter_vsrc_buffer_outputs
const AVFilterPad avfilter_vsrc_buffer_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .request_frame = request_frame,
        .poll_frame    = poll_frame,
        .config_props  = config_props,
    },
    { NULL }
}
Definition at line 489 of file buffersrc.c.
ff_vsrc_buffer
AVFilter ff_vsrc_buffer
Initial value:
= {
    .name      = "buffer",
    .description = NULL_IF_CONFIG_SMALL("Buffer video frames, and make them accessible to the filterchain."),
    .priv_size = sizeof(BufferSourceContext),
    .query_formats = query_formats,
    .init      = init_video,
    .uninit    = uninit,
    .inputs    = NULL,
    .outputs   = avfilter_vsrc_buffer_outputs,
    .priv_class = &buffer_class,
}
Definition at line 500 of file buffersrc.c.
avfilter_asrc_abuffer_outputs
const AVFilterPad avfilter_asrc_abuffer_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_AUDIO,
        .request_frame = request_frame,
        .poll_frame    = poll_frame,
        .config_props  = config_props,
    },
    { NULL }
}
Definition at line 514 of file buffersrc.c.
ff_asrc_abuffer
AVFilter ff_asrc_abuffer
Initial value:
= {
    .name          = "abuffer",
    .description   = NULL_IF_CONFIG_SMALL("Buffer audio frames, and make them accessible to the filterchain."),
    .priv_size     = sizeof(BufferSourceContext),
    .query_formats = query_formats,
    .init      = init_audio,
    .uninit    = uninit,
    .inputs    = NULL,
    .outputs   = avfilter_asrc_abuffer_outputs,
    .priv_class = &abuffer_class,
}
Definition at line 525 of file buffersrc.c.