FFmpeg: libavcodec/cabac_functions.h File Reference
cabac_functions.h File Reference
Context Adaptive Binary Arithmetic Coder inline functions.
#include <stdint.h>
#include "cabac.h"
#include "config.h"
Macros
#define UNCHECKED_BITSTREAM_READER !CONFIG_SAFE_BITSTREAM_READER
Functions
static void refill (CABACContext *c)
static void renorm_cabac_decoder_once (CABACContext *c)
static void refill2 (CABACContext *c)
static av_always_inline int get_cabac_inline (CABACContext *c, uint8_t *const state)
static int av_noinline av_unused get_cabac_noinline (CABACContext *c, uint8_t *const state)
static int av_unused get_cabac (CABACContext *c, uint8_t *const state)
static int av_unused get_cabac_bypass (CABACContext *c)
static av_always_inline int get_cabac_bypass_sign (CABACContext *c, int val)
static int av_unused get_cabac_terminate (CABACContext *c)
static av_unused const uint8_t * skip_bytes (CABACContext *c, int n)
Skip n bytes and reset the decoder.
Variables
static const uint8_t *const ff_h264_norm_shift = ff_h264_cabac_tables + H264_NORM_SHIFT_OFFSET
static const uint8_t *const ff_h264_lps_range = ff_h264_cabac_tables + H264_LPS_RANGE_OFFSET
static const uint8_t *const ff_h264_mlps_state = ff_h264_cabac_tables + H264_MLPS_STATE_OFFSET
static const uint8_t *const ff_h264_last_coeff_flag_offset_8x8 = ff_h264_cabac_tables + H264_LAST_COEFF_FLAG_OFFSET_8x8_OFFSET
Detailed Description
Context Adaptive Binary Arithmetic Coder inline functions.
Definition in file cabac_functions.h.
Macro Definition Documentation
UNCHECKED_BITSTREAM_READER
#define UNCHECKED_BITSTREAM_READER !CONFIG_SAFE_BITSTREAM_READER
Definition at line 36 of file cabac_functions.h.
Function Documentation
refill()
static void refill (CABACContext * c) static
Definition at line 55 of file cabac_functions.h.
Referenced by get_cabac_bypass(), get_cabac_bypass_sign(), and renorm_cabac_decoder_once().
renorm_cabac_decoder_once()
static void renorm_cabac_decoder_once (CABACContext * c) inline static
Definition at line 70 of file cabac_functions.h.
Referenced by get_cabac_terminate().
refill2()
static void refill2 (CABACContext * c) static
Definition at line 80 of file cabac_functions.h.
Referenced by get_cabac_inline().
get_cabac_inline()
static av_always_inline int get_cabac_inline (CABACContext * c, uint8_t *const state) static
Definition at line 107 of file cabac_functions.h.
Referenced by get_cabac(), and get_cabac_noinline().
get_cabac_noinline()
static int av_noinline av_unused get_cabac_noinline (CABACContext * c, uint8_t *const state) static
Definition at line 131 of file cabac_functions.h.
Referenced by decode_cabac_field_decoding_flag(), decode_cabac_intra_mb_type(), decode_cabac_mb_cbp_chroma(), decode_cabac_mb_cbp_luma(), decode_cabac_mb_chroma_pre_mode(), decode_cabac_mb_skip(), ff_h264_decode_mb_cabac(), and main().
get_cabac()
static int av_unused get_cabac (CABACContext * c, uint8_t *const state) static
Definition at line 135 of file cabac_functions.h.
Referenced by decode_cabac_b_mb_sub_type(), decode_cabac_mb_intra4x4_pred_mode(), decode_cabac_mb_mvd(), decode_cabac_mb_ref(), decode_cabac_p_mb_sub_type(), decode_cabac_residual_dc(), decode_cabac_residual_dc_422(), and decode_cabac_residual_nondc().
get_cabac_bypass()
static int av_unused get_cabac_bypass (CABACContext * c) static
Definition at line 140 of file cabac_functions.h.
Referenced by coeff_abs_level_remaining_decode(), coeff_sign_flag_decode(), decode_cabac_mb_mvd(), ff_hevc_cu_qp_delta_abs(), ff_hevc_cu_qp_delta_sign_flag(), ff_hevc_intra_chroma_pred_mode_decode(), ff_hevc_merge_idx_decode(), ff_hevc_mpm_idx_decode(), ff_hevc_part_mode_decode(), ff_hevc_ref_idx_lx_decode(), ff_hevc_rem_intra_luma_pred_mode_decode(), ff_hevc_sao_band_position_decode(), ff_hevc_sao_eo_class_decode(), ff_hevc_sao_offset_abs_decode(), ff_hevc_sao_offset_sign_decode(), ff_hevc_sao_type_idx_decode(), last_significant_coeff_suffix_decode(), main(), and mvd_decode().
get_cabac_bypass_sign()
static av_always_inline int get_cabac_bypass_sign (CABACContext * c, int val) static
Definition at line 158 of file cabac_functions.h.
Referenced by decode_cabac_mb_mvd(), mvd_decode(), and mvd_sign_flag_decode().
get_cabac_terminate()
static int av_unused get_cabac_terminate (CABACContext * c) static
Returns
the number of bytes read or 0 if no end
Definition at line 178 of file cabac_functions.h.
Referenced by decode_cabac_intra_mb_type(), decode_slice(), ff_hevc_cabac_init(), ff_hevc_end_of_slice_flag_decode(), ff_hevc_pcm_flag_decode(), and main().
skip_bytes()
static av_unused const uint8_t* skip_bytes (CABACContext * c, int n) static
Skip n bytes and reset the decoder.
Returns
the address of the first skipped byte or NULL if there's less than n bytes left
Definition at line 194 of file cabac_functions.h.
Referenced by cabac_reinit(), ff_mms_asf_header_parser(), hls_pcm_sample(), main(), and read_header().
Variable Documentation
ff_h264_norm_shift
const uint8_t* const ff_h264_norm_shift = ff_h264_cabac_tables + H264_NORM_SHIFT_OFFSET static
Definition at line 49 of file cabac_functions.h.
Referenced by get_cabac_inline(), and refill2().
ff_h264_lps_range
const uint8_t* const ff_h264_lps_range = ff_h264_cabac_tables + H264_LPS_RANGE_OFFSET static
Definition at line 50 of file cabac_functions.h.
Referenced by get_cabac_inline(), and put_cabac().
ff_h264_mlps_state
const uint8_t* const ff_h264_mlps_state = ff_h264_cabac_tables + H264_MLPS_STATE_OFFSET static
Definition at line 51 of file cabac_functions.h.
Referenced by get_cabac_inline(), and put_cabac().
ff_h264_last_coeff_flag_offset_8x8
const uint8_t* const ff_h264_last_coeff_flag_offset_8x8 = ff_h264_cabac_tables + H264_LAST_COEFF_FLAG_OFFSET_8x8_OFFSET static
Definition at line 52 of file cabac_functions.h.
Referenced by decode_cabac_residual_internal().