FFmpeg: libavcodec/cabac.h File Reference
cabac.h File Reference
Context Adaptive Binary Arithmetic Coder.
#include <stdint.h>
#include "put_bits.h"
Data Structures
struct CABACContext
Macros
#define H264_NORM_SHIFT_OFFSET 0
#define H264_LPS_RANGE_OFFSET 512
#define H264_MLPS_STATE_OFFSET 1024
#define H264_LAST_COEFF_FLAG_OFFSET_8x8_OFFSET 1280
#define CABAC_BITS 16
#define CABAC_MASK ((1<<CABAC_BITS)-1)
Functions
void ff_init_cabac_encoder (CABACContext *c, uint8_t *buf, int buf_size)
int ff_init_cabac_decoder (CABACContext *c, const uint8_t *buf, int buf_size)
Variables
const uint8_t ff_h264_cabac_tables [512+4 *2 *64+4 *64+63]
Detailed Description
Context Adaptive Binary Arithmetic Coder.
Definition in file cabac.h.
Macro Definition Documentation
H264_NORM_SHIFT_OFFSET
#define H264_NORM_SHIFT_OFFSET 0
Definition at line 35 of file cabac.h.
H264_LPS_RANGE_OFFSET
#define H264_LPS_RANGE_OFFSET 512
Definition at line 36 of file cabac.h.
H264_MLPS_STATE_OFFSET
#define H264_MLPS_STATE_OFFSET 1024
Definition at line 37 of file cabac.h.
H264_LAST_COEFF_FLAG_OFFSET_8x8_OFFSET
#define H264_LAST_COEFF_FLAG_OFFSET_8x8_OFFSET 1280
Definition at line 38 of file cabac.h.
CABAC_BITS
#define CABAC_BITS 16
Definition at line 40 of file cabac.h.
Referenced by ff_h264_decode_mb_cabac(), ff_init_cabac_decoder(), get_cabac_bypass(), get_cabac_bypass_sign(), get_cabac_inline(), get_cabac_terminate(), refill(), and refill2().
CABAC_MASK
#define CABAC_MASK ((1<<CABAC_BITS)-1)
Definition at line 41 of file cabac.h.
Referenced by get_cabac_bypass(), get_cabac_bypass_sign(), get_cabac_inline(), refill(), refill2(), and renorm_cabac_decoder_once().
Function Documentation
ff_init_cabac_encoder()
void ff_init_cabac_encoder (CABACContext * c, uint8_t * buf, int buf_size)
Parameters
buf_size size of buf in bits
Definition at line 164 of file cabac.c.
Referenced by main().
ff_init_cabac_decoder()
int ff_init_cabac_decoder (CABACContext * c, const uint8_t * buf, int buf_size)
Parameters
buf_size size of buf in bits
Definition at line 177 of file cabac.c.
Referenced by cabac_init_decoder(), decode_slice(), ff_h264_decode_mb_cabac(), hls_decode_entry_wpp(), main(), and skip_bytes().
Variable Documentation
ff_h264_cabac_tables
const uint8_t ff_h264_cabac_tables[512+4 *2 *64+4 *64+63]
Definition at line 35 of file cabac.c.