FFmpeg: libavcodec/cabac.c File Reference
cabac.c File Reference
Context Adaptive Binary Arithmetic Coder.
#include <string.h>
#include "libavutil/common.h"
#include "libavutil/timer.h"
#include "cabac.h"
#include "cabac_functions.h"
Functions
void ff_init_cabac_encoder (CABACContext *c, uint8_t *buf, int buf_size)
int ff_init_cabac_decoder (CABACContext *c, const uint8_t *buf, int buf_size)
Variables
const uint8_t ff_h264_cabac_tables [512+4 *2 *64+4 *64+63]
Detailed Description
Context Adaptive Binary Arithmetic Coder.
Definition in file cabac.c.
Function Documentation
ff_init_cabac_encoder()
void ff_init_cabac_encoder (CABACContext * c, uint8_t * buf, int buf_size)
Parameters
buf_size size of buf in bits
Definition at line 164 of file cabac.c.
Referenced by main().
ff_init_cabac_decoder()
int ff_init_cabac_decoder (CABACContext * c, const uint8_t * buf, int buf_size)
Parameters
buf_size size of buf in bits
Definition at line 177 of file cabac.c.
Referenced by cabac_init_decoder(), decode_slice(), ff_h264_decode_mb_cabac(), hls_decode_entry_wpp(), main(), and skip_bytes().
Variable Documentation
ff_h264_cabac_tables
const uint8_t ff_h264_cabac_tables[512+4 *2 *64+4 *64+63]
Definition at line 35 of file cabac.c.