FFmpeg: libavformat/cafdec.c File Reference
cafdec.c File Reference
Core Audio Format demuxer.
#include <inttypes.h>
#include "avformat.h"
#include "internal.h"
#include "isom.h"
#include "mov_chan.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/intfloat.h"
#include "libavutil/dict.h"
#include "caf.h"
Data Structures
struct CafContext
Macros
#define ALAC_PREAMBLE 12
#define ALAC_HEADER 36
#define ALAC_NEW_KUKI 24
#define _(x) ((x) >= ' ' ? (x) : ' ')
#define CAF_MAX_PKT_SIZE 4096
Functions
static int probe (AVProbeData *p)
static int read_desc_chunk (AVFormatContext *s)
Read audio description chunk.
static int read_kuki_chunk (AVFormatContext *s, int64_t size)
Read magic cookie chunk.
static int read_pakt_chunk (AVFormatContext *s, int64_t size)
Read packet table chunk.
static void read_info_chunk (AVFormatContext *s, int64_t size)
Read information chunk.
static int read_header (AVFormatContext *s)
static int read_packet (AVFormatContext *s, AVPacket *pkt)
static int read_seek (AVFormatContext *s, int stream_index, int64_t timestamp, int flags)
Variables
AVInputFormat ff_caf_demuxer
Detailed Description
Core Audio Format demuxer.
Definition in file cafdec.c.
Macro Definition Documentation
ALAC_PREAMBLE
#define ALAC_PREAMBLE 12
Referenced by read_kuki_chunk().
ALAC_HEADER
#define ALAC_HEADER 36
Referenced by read_kuki_chunk().
ALAC_NEW_KUKI
#define ALAC_NEW_KUKI 24
Referenced by read_kuki_chunk().
_
#define _ (x) ((x) >= ' ' ? (x) : ' ')
Referenced by read_header(), and x11grab_read_packet().
CAF_MAX_PKT_SIZE
#define CAF_MAX_PKT_SIZE 4096
Definition at line 349 of file cafdec.c.
Referenced by read_packet().
Function Documentation
probe()
static int probe (AVProbeData * p) static
Definition at line 51 of file cafdec.c.
read_desc_chunk()
static int read_desc_chunk (AVFormatContext * s) static
Read audio description chunk.
Definition at line 59 of file cafdec.c.
Referenced by read_header().
read_kuki_chunk()
static int read_kuki_chunk (AVFormatContext * s, int64_t size) static
Read magic cookie chunk.
Definition at line 99 of file cafdec.c.
Referenced by read_header().
read_pakt_chunk()
static int read_pakt_chunk (AVFormatContext * s, int64_t size) static
Read packet table chunk.
Definition at line 179 of file cafdec.c.
Referenced by read_header().
read_info_chunk()
static void read_info_chunk (AVFormatContext * s, int64_t size) static
Read information chunk.
Definition at line 215 of file cafdec.c.
Referenced by read_header().
read_header()
static int read_header (AVFormatContext * s) static
Definition at line 229 of file cafdec.c.
read_packet()
static int read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 351 of file cafdec.c.
read_seek()
static int read_seek (AVFormatContext * s, int stream_index, int64_t timestamp, int flags) static
Definition at line 407 of file cafdec.c.
Variable Documentation
ff_caf_demuxer
AVInputFormat ff_caf_demuxer
Initial value:
= {
    .name           = "caf",
    .long_name      = NULL_IF_CONFIG_SMALL("Apple CAF (Core Audio Format)"),
    .priv_data_size = sizeof(CafContext),
    .read_probe     = probe,
    .read_header    = read_header,
    .read_packet    = read_packet,
    .read_seek      = read_seek,
    .codec_tag      = (const AVCodecTag* const []){ ff_codec_caf_tags, 0 },
}
Definition at line 440 of file cafdec.c.