FFmpeg: libavformat/cafenc.c File Reference
cafenc.c File Reference
#include "avformat.h"
#include "caf.h"
#include "isom.h"
#include "avio_internal.h"
#include "libavutil/intfloat.h"
#include "libavutil/dict.h"
Data Structures
struct CAFContext
Functions
static uint32_t codec_flags (enum AVCodecID codec_id)
static uint32_t samples_per_packet (enum AVCodecID codec_id, int channels, int block_align)
static int caf_write_header (AVFormatContext *s)
static int caf_write_packet (AVFormatContext *s, AVPacket *pkt)
static int caf_write_trailer (AVFormatContext *s)
Variables
AVOutputFormat ff_caf_muxer
Function Documentation
codec_flags()
static uint32_t codec_flags (enum AVCodecID codec_id) static
Definition at line 37 of file cafenc.c.
Referenced by caf_write_header(), and set_encoder_id().
samples_per_packet()
static uint32_t samples_per_packet (enum AVCodecID codec_id, int channels, int block_align) static
Definition at line 54 of file cafenc.c.
Referenced by caf_write_header(), and caf_write_trailer().
caf_write_header()
static int caf_write_header (AVFormatContext * s) static
Definition at line 103 of file cafenc.c.
caf_write_packet()
static int caf_write_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 203 of file cafenc.c.
caf_write_trailer()
static int caf_write_trailer (AVFormatContext * s) static
< mNumberPackets
< mNumberValidFrames
< mPrimingFrames
< mRemainderFrames
Definition at line 233 of file cafenc.c.
Variable Documentation
ff_caf_muxer
AVOutputFormat ff_caf_muxer
Initial value:
= {
    .name           = "caf",
    .long_name      = NULL_IF_CONFIG_SMALL("Apple CAF (Core Audio Format)"),
    .mime_type      = "audio/x-caf",
    .extensions     = "caf",
    .priv_data_size = sizeof(CAFContext),
    .audio_codec    = AV_CODEC_ID_PCM_S16BE,
    .video_codec    = AV_CODEC_ID_NONE,
    .write_header   = caf_write_header,
    .write_packet   = caf_write_packet,
    .write_trailer  = caf_write_trailer,
    .codec_tag      = (const AVCodecTag* const []){ff_codec_caf_tags, 0},
}
Definition at line 261 of file cafenc.c.