FFmpeg: libavcodec/cbrt_tablegen.h File Reference
cbrt_tablegen.h File Reference
#include <stdint.h>
#include <math.h>
#include "libavutil/attributes.h"
#include "libavutil/intfloat.h"
#include "libavcodec/aac_defines.h"
Macros
#define CBRT(x) av_float2int((float)(x))
Functions
uint32_t AAC_RENAME (ff_cbrt_tab)[1<< 13]
av_cold void AAC_RENAME() ff_cbrt_tableinit (void)
Macro Definition Documentation
CBRT
#define CBRT (x) av_float2int((float)(x))
Definition at line 35 of file cbrt_tablegen.h.
Referenced by ff_cbrt_tableinit().
Function Documentation
AAC_RENAME()
uint32_t AAC_RENAME (ff_cbrt_tab)
Referenced by ff_cbrt_tableinit().
ff_cbrt_tableinit()
av_cold void AAC_RENAME() ff_cbrt_tableinit (void)
Definition at line 40 of file cbrt_tablegen.h.
Referenced by aac_static_table_init(), and main().