FFmpeg: libavcodec/ccaption_dec.c File Reference
ccaption_dec.c File Reference
#include "avcodec.h"
#include "ass.h"
#include "libavutil/opt.h"
Data Structures
struct Screen
struct CCaptionSubContext
Macros
#define SCREEN_ROWS 15
#define SCREEN_COLUMNS 32
#define SET_FLAG(var, val) ((var) |= (1 << (val)))
#define UNSET_FLAG(var, val) ((var) &= ~(1 << (val)))
#define CHECK_FLAG(var, val) ((var) & (1 << (val)))
#define OFFSET(x) offsetof(CCaptionSubContext, x)
#define SD AV_OPT_FLAG_SUBTITLE_PARAM | AV_OPT_FLAG_DECODING_PARAM
Enumerations
enum cc_mode { CCMODE_POPON, CCMODE_PAINTON, CCMODE_ROLLUP, CCMODE_TEXT }
enum cc_color_code {
CCCOL_WHITE, CCCOL_GREEN, CCCOL_BLUE, CCCOL_CYAN,
CCCOL_RED, CCCOL_YELLOW, CCCOL_MAGENTA, CCCOL_USERDEFINED,
CCCOL_BLACK, CCCOL_TRANSPARENT
}
enum cc_font { CCFONT_REGULAR, CCFONT_ITALICS, CCFONT_UNDERLINED, CCFONT_UNDERLINED_ITALICS }
enum cc_charset { CCSET_BASIC_AMERICAN, CCSET_SPECIAL_AMERICAN, CCSET_EXTENDED_SPANISH_FRENCH_MISC, CCSET_EXTENDED_PORTUGUESE_GERMAN_DANISH }
Functions
static av_cold int init_decoder (AVCodecContext *avctx)
static av_cold int close_decoder (AVCodecContext *avctx)
static void flush_decoder (AVCodecContext *avctx)
static void write_char (CCaptionSubContext *ctx, struct Screen *screen, char ch)
static int validate_cc_data_pair (uint8_t *cc_data_pair)
This function after validating parity bit, also remove it from data pair.
static struct Screen * get_writing_screen (CCaptionSubContext *ctx)
static void roll_up (CCaptionSubContext *ctx)
static int capture_screen (CCaptionSubContext *ctx)
static int reap_screen (CCaptionSubContext *ctx, int64_t pts)
static void handle_textattr (CCaptionSubContext *ctx, uint8_t hi, uint8_t lo)
static void handle_pac (CCaptionSubContext *ctx, uint8_t hi, uint8_t lo)
static void handle_edm (CCaptionSubContext *ctx, int64_t pts)
static void handle_eoc (CCaptionSubContext *ctx, int64_t pts)
static void handle_delete_end_of_row (CCaptionSubContext *ctx, char hi, char lo)
static void handle_char (CCaptionSubContext *ctx, char hi, char lo, int64_t pts)
static void process_cc608 (CCaptionSubContext *ctx, int64_t pts, uint8_t hi, uint8_t lo)
static int decode (AVCodecContext *avctx, void *data, int *got_sub, AVPacket *avpkt)
Variables
static const AVRational ms_tb = {1, 1000}
static const char * charset_overrides [4][128]
static const unsigned char pac2_attribs [32][3]
static const AVOption options []
static const AVClass ccaption_dec_class
AVCodec ff_ccaption_decoder
Macro Definition Documentation
SCREEN_ROWS
#define SCREEN_ROWS 15
Definition at line 26 of file ccaption_dec.c.
Referenced by capture_screen(), and roll_up().
SCREEN_COLUMNS
#define SCREEN_COLUMNS 32
Definition at line 27 of file ccaption_dec.c.
Referenced by capture_screen(), roll_up(), and write_char().
SET_FLAG
#define SET_FLAG (var, val) ((var) |= (1 << (val)))
Definition at line 29 of file ccaption_dec.c.
Referenced by handle_char(), handle_textattr(), and roll_up().
UNSET_FLAG
#define UNSET_FLAG (var, val) ((var) &= ~(1 << (val)))
Definition at line 30 of file ccaption_dec.c.
Referenced by roll_up().
CHECK_FLAG
#define CHECK_FLAG (var, val) ((var) & (1 << (val)))
Definition at line 31 of file ccaption_dec.c.
Referenced by capture_screen(), and roll_up().
OFFSET
#define OFFSET (x) offsetof(CCaptionSubContext, x)
Definition at line 818 of file ccaption_dec.c.
SD
#define SD AV_OPT_FLAG_SUBTITLE_PARAM | AV_OPT_FLAG_DECODING_PARAM
Definition at line 819 of file ccaption_dec.c.
Referenced by common_vt_4t_24w_msa(), common_vt_4t_8x6_msa(), common_vt_8t_12w_msa(), copy_8x8_msa(), copy_width8_msa(), ff_loop_filter_v_16_8_msa(), ff_loop_filter_v_8_8_msa(), ff_vp8_v_loop_filter8uv_msa(), hevc_hv_4t_6w_msa(), hevc_hz_4t_6w_msa(), hevc_hz_bi_8t_24w_msa(), hevc_hz_biwgt_8t_24w_msa(), hevc_hz_biwgt_8t_48w_msa(), hevc_intra_pred_angular_lower_4width_msa(), hevc_intra_pred_angular_upper_4width_msa(), hevc_intra_pred_dc_8x8_msa(), hevc_intra_pred_horiz_8x8_msa(), hevc_intra_pred_vert_8x8_msa(), hevc_loopfilter_luma_hor_msa(), hevc_sao_edge_filter_0degree_8width_msa(), hevc_sao_edge_filter_135degree_8width_msa(), hevc_sao_edge_filter_45degree_8width_msa(), hevc_sao_edge_filter_90degree_8width_msa(), hevc_vt_4t_6w_msa(), intra_predict_hor_dc_8x8_msa(), intra_predict_mad_cow_dc_0l0_8x8_msa(), intra_predict_mad_cow_dc_l00_8x8_msa(), and intra_predict_plane_8x8_msa().
Enumeration Type Documentation
cc_mode
enum cc_mode
Enumerator
CCMODE_POPON
CCMODE_PAINTON
CCMODE_ROLLUP
CCMODE_TEXT
Definition at line 39 of file ccaption_dec.c.
cc_color_code
enum cc_color_code
Enumerator
CCCOL_WHITE
CCCOL_GREEN
CCCOL_BLUE
CCCOL_CYAN
CCCOL_RED
CCCOL_YELLOW
CCCOL_MAGENTA
CCCOL_USERDEFINED
CCCOL_BLACK
CCCOL_TRANSPARENT
Definition at line 46 of file ccaption_dec.c.
cc_font
enum cc_font
Enumerator
CCFONT_REGULAR
CCFONT_ITALICS
CCFONT_UNDERLINED
CCFONT_UNDERLINED_ITALICS
Definition at line 59 of file ccaption_dec.c.
cc_charset
enum cc_charset
Enumerator
CCSET_BASIC_AMERICAN
CCSET_SPECIAL_AMERICAN
CCSET_EXTENDED_SPANISH_FRENCH_MISC
CCSET_EXTENDED_PORTUGUESE_GERMAN_DANISH
Definition at line 66 of file ccaption_dec.c.
Function Documentation
init_decoder()
static av_cold int init_decoder (AVCodecContext * avctx) static
Definition at line 256 of file ccaption_dec.c.
close_decoder()
static av_cold int close_decoder (AVCodecContext * avctx) static
Definition at line 282 of file ccaption_dec.c.
flush_decoder()
static void flush_decoder (AVCodecContext * avctx) static
Definition at line 291 of file ccaption_dec.c.
write_char()
static void write_char (CCaptionSubContext * ctx, struct Screen * screen, char ch) static
Parameters
ctx closed caption context just to print log
Definition at line 317 of file ccaption_dec.c.
Referenced by handle_char(), handle_delete_end_of_row(), handle_pac(), and handle_textattr().
validate_cc_data_pair()
static int validate_cc_data_pair (uint8_t * cc_data_pair) static
This function after validating parity bit, also remove it from data pair.
The first byte doesn't pass parity, we replace it with a solid blank and process the pair. If the second byte doesn't pass parity, it returns INVALIDDATA user can ignore the whole pair and pass the other pair.
Definition at line 350 of file ccaption_dec.c.
Referenced by decode().
get_writing_screen()
static struct Screen* get_writing_screen (CCaptionSubContext * ctx) static
Definition at line 384 of file ccaption_dec.c.
Referenced by handle_char(), handle_delete_end_of_row(), handle_pac(), handle_textattr(), and roll_up().
roll_up()
static void roll_up (CCaptionSubContext * ctx) static
Definition at line 400 of file ccaption_dec.c.
Referenced by process_cc608().
capture_screen()
static int capture_screen (CCaptionSubContext * ctx) static
Definition at line 435 of file ccaption_dec.c.
Referenced by avf_read_header(), decode(), and reap_screen().
reap_screen()
static int reap_screen (CCaptionSubContext * ctx, int64_t pts) static
Definition at line 529 of file ccaption_dec.c.
Referenced by handle_edm(), handle_eoc(), and process_cc608().
handle_textattr()
static void handle_textattr (CCaptionSubContext * ctx, uint8_t hi, uint8_t lo) static
Definition at line 537 of file ccaption_dec.c.
Referenced by process_cc608().
handle_pac()
static void handle_pac (CCaptionSubContext * ctx, uint8_t hi, uint8_t lo) static
Definition at line 552 of file ccaption_dec.c.
Referenced by process_cc608().
handle_edm()
static void handle_edm (CCaptionSubContext * ctx, int64_t pts) static
Parameters
pts it is required to set end time
Definition at line 582 of file ccaption_dec.c.
Referenced by handle_eoc(), and process_cc608().
handle_eoc()
static void handle_eoc (CCaptionSubContext * ctx, int64_t pts) static
Definition at line 599 of file ccaption_dec.c.
Referenced by process_cc608().
handle_delete_end_of_row()
static void handle_delete_end_of_row (CCaptionSubContext * ctx, char hi, char lo) static
Definition at line 615 of file ccaption_dec.c.
Referenced by process_cc608().
handle_char()
static void handle_char (CCaptionSubContext * ctx, char hi, char lo, int64_t pts) static
Definition at line 621 of file ccaption_dec.c.
Referenced by process_cc608().
process_cc608()
static void process_cc608 (CCaptionSubContext * ctx, int64_t pts, uint8_t hi, uint8_t lo) static
Definition at line 661 of file ccaption_dec.c.
Referenced by decode().
decode()
static int decode (AVCodecContext * avctx, void * data, int * got_sub, AVPacket * avpkt) static
Definition at line 750 of file ccaption_dec.c.
Variable Documentation
ms_tb
const AVRational ms_tb = {1, 1000} static
Definition at line 33 of file ccaption_dec.c.
charset_overrides
const char* charset_overrides[4][128] static
Definition at line 73 of file ccaption_dec.c.
Referenced by capture_screen().
pac2_attribs
const unsigned char pac2_attribs[32][3] static
Definition at line 176 of file ccaption_dec.c.
Referenced by handle_pac(), and handle_textattr().
options
const AVOption options[] static
Initial value:
= {
    { "real_time", "emit subtitle events as they are decoded for real-time display", OFFSET(real_time), AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, SD },
    {NULL}
}
Definition at line 820 of file ccaption_dec.c.
ccaption_dec_class
const AVClass ccaption_dec_class static
Initial value:
= {
    .class_name = "Closed caption Decoder",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 825 of file ccaption_dec.c.
ff_ccaption_decoder
AVCodec ff_ccaption_decoder
Initial value:
= {
    .name           = "cc_dec",
    .long_name      = NULL_IF_CONFIG_SMALL("Closed Caption (EIA-608 / CEA-708) Decoder"),
    .type           = AVMEDIA_TYPE_SUBTITLE,
    .id             = AV_CODEC_ID_EIA_608,
    .priv_data_size = sizeof(CCaptionSubContext),
    .init           = init_decoder,
    .close          = close_decoder,
    .flush          = flush_decoder,
    .decode         = decode,
    .priv_class     = &ccaption_dec_class,
}
Definition at line 832 of file ccaption_dec.c.