FFmpeg: libavcodec/celp_math.h File Reference
celp_math.h File Reference
#include <stdint.h>
Data Structures
struct CELPMContext
Functions
void ff_celp_math_init (CELPMContext *c)
Initialize CELPMContext.
void ff_celp_math_init_mips (CELPMContext *c)
int ff_exp2 (uint16_t power)
fixed-point implementation of exp2(x) in [0; 1] domain.
int ff_log2_q15 (uint32_t value)
Calculate log2(x).
int64_t ff_dot_product (const int16_t *a, const int16_t *b, int length)
Calculate the dot product of 2 int16_t vectors.
static int bidir_sal (int value, int offset)
Shift value left or right depending on sign of offset parameter.
float ff_dot_productf (const float *a, const float *b, int length)
Return the dot product.
Function Documentation
ff_celp_math_init()
void ff_celp_math_init (CELPMContext * c)
Initialize CELPMContext.
Definition at line 120 of file celp_math.c.
Referenced by amrnb_decode_init(), and amrwb_decode_init().
ff_celp_math_init_mips()
void ff_celp_math_init_mips (CELPMContext * c)
Definition at line 87 of file celp_math_mips.c.
Referenced by ff_celp_math_init().
ff_exp2()
int ff_exp2 (uint16_t power)
fixed-point implementation of exp2(x) in [0; 1] domain.
Parameters
power argument to exp2, 0 <= power <= 0x7fff
Returns
value of (1<<20) * exp2(power / (1<<15)) 0x8000c <= result <= 0xfffea
Definition at line 48 of file celp_math.c.
Referenced by ff_acelp_decode_gain_code().
ff_log2_q15()
int ff_log2_q15 (uint32_t value)
Calculate log2(x).
Parameters
value function argument, 0 < value <= 7fff ffff
Returns
value of (1<<15) * log2(value)
Definition at line 78 of file celp_math.c.
Referenced by ff_acelp_update_past_gain().
ff_dot_product()
int64_t ff_dot_product (const int16_t * a, const int16_t * b, int length)
Calculate the dot product of 2 int16_t vectors.
Parameters
a input data array
b input data array
length number of elements
Returns
dot product = sum of elementwise products
Definition at line 98 of file celp_math.c.
Referenced by acb_search(), comp_autocorr(), comp_harmonic_coeff(), estimate_pitch(), ff_g723_1_dot_product(), and ff_g723_1_gen_acb_excitation().
bidir_sal()
static int bidir_sal (int value, int offset) inline static
Shift value left or right depending on sign of offset parameter.
Parameters
value value to shift
offset shift offset
Returns
value << offset, if offset>=0; value >> -offset - otherwise
Definition at line 81 of file celp_math.h.
Referenced by ff_acelp_decode_gain_code(), and ff_g729_adaptive_gain_control().
ff_dot_productf()
float ff_dot_productf (const float * a, const float * b, int length)
Return the dot product.
Parameters
a input data array
b input data array
length number of elements
Returns
dot product = sum of elementwise products
Definition at line 109 of file celp_math.c.
Referenced by bidir_sal(), and ff_celp_math_init().