FFmpeg: libavcodec/cfhd.c File Reference
cfhd.c File Reference
CFHD Video Decoder.
#include "libavutil/buffer.h"
#include "libavutil/common.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/imgutils.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "internal.h"
#include "bytestream.h"
#include "thread.h"
#include "cfhd.h"
Macros
#define SUBBAND_COUNT 10
Functions
static av_cold int cfhd_decode_init (AVCodecContext *avctx)
static void init_plane_defaults (CFHDContext *s)
static void init_frame_defaults (CFHDContext *s)
static int dequant_and_decompand (int level, int quantisation)
static void filter (int16_t *output, ptrdiff_t out_stride, int16_t *low, ptrdiff_t low_stride, int16_t *high, ptrdiff_t high_stride, int len, uint8_t clip)
static void horiz_filter (int16_t *output, int16_t *low, int16_t *high, int width)
static void horiz_filter_clip (int16_t *output, int16_t *low, int16_t *high, int width, uint8_t clip)
static void vert_filter (int16_t *output, int out_stride, int16_t *low, int low_stride, int16_t *high, int high_stride, int len)
static void free_buffers (AVCodecContext *avctx)
static int alloc_buffers (AVCodecContext *avctx)
static int cfhd_decode (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int cfhd_close_decoder (AVCodecContext *avctx)
Variables
AVCodec ff_cfhd_decoder
Detailed Description
CFHD Video Decoder.
Definition in file cfhd.c.
Macro Definition Documentation
SUBBAND_COUNT
#define SUBBAND_COUNT 10
Definition at line 38 of file cfhd.c.
Referenced by cfhd_decode().
Function Documentation
cfhd_decode_init()
static av_cold int cfhd_decode_init (AVCodecContext * avctx) static
Definition at line 40 of file cfhd.c.
init_plane_defaults()
static void init_plane_defaults (CFHDContext * s) static
Definition at line 50 of file cfhd.c.
Referenced by cfhd_decode(), and init_frame_defaults().
init_frame_defaults()
static void init_frame_defaults (CFHDContext * s) static
Definition at line 57 of file cfhd.c.
Referenced by cfhd_decode().
dequant_and_decompand()
static int dequant_and_decompand (int level, int quantisation) inline static
Definition at line 74 of file cfhd.c.
Referenced by cfhd_decode().
filter()
static void filter (int16_t * output, ptrdiff_t out_stride, int16_t * low, ptrdiff_t low_stride, int16_t * high, ptrdiff_t high_stride, int len, uint8_t clip) inline static
Definition at line 80 of file cfhd.c.
Referenced by adpcm_decode_frame(), apply_filter(), apply_ir_filter(), av_bitstream_filter_next(), av_bsf_alloc(), av_bsf_list_append2(), av_resample(), avfilter_graph_add_filter(), avfilter_graph_dump_to_buf(), avfilter_graph_parse2(), avfilter_graph_parse_ptr(), avfilter_graph_queue_command(), avfilter_graph_send_command(), build_filter(), check_mc(), compare_filter_params(), configure_output_video_filter(), copy_filter_params(), copy_restart_frame_params(), create_filter(), decode_frame(), determine_filters(), do_scaled_8tap_c(), do_video_out(), ff_alsa_get_device_list(), ff_avg_bilin_16h_msa(), ff_avg_bilin_16v_msa(), ff_avg_bilin_32h_msa(), ff_avg_bilin_32v_msa(), ff_avg_bilin_4h_msa(), ff_avg_bilin_4v_msa(), ff_avg_bilin_64h_msa(), ff_avg_bilin_64v_msa(), ff_avg_bilin_8h_msa(), ff_avg_bilin_8v_msa(), ff_filter_alloc(), ff_filter_graph_run_once(), ff_put_bilin_16h_msa(), ff_put_bilin_16v_msa(), ff_put_bilin_32h_msa(), ff_put_bilin_32v_msa(), ff_put_bilin_4h_msa(), ff_put_bilin_4v_msa(), ff_put_bilin_64h_msa(), ff_put_bilin_64v_msa(), ff_put_bilin_8h_msa(), ff_put_bilin_8v_msa(), ff_put_vp8_bilinear16_h_msa(), ff_put_vp8_bilinear16_v_msa(), ff_put_vp8_bilinear4_h_msa(), ff_put_vp8_bilinear4_v_msa(), ff_put_vp8_bilinear8_h_msa(), ff_put_vp8_bilinear8_v_msa(), ff_put_vp8_epel16_h4_mmi(), ff_put_vp8_epel16_h4_msa(), ff_put_vp8_epel16_h4v4_mmi(), ff_put_vp8_epel16_h4v6_mmi(), ff_put_vp8_epel16_h6_mmi(), ff_put_vp8_epel16_h6_msa(), ff_put_vp8_epel16_h6v4_mmi(), ff_put_vp8_epel16_h6v6_mmi(), ff_put_vp8_epel16_v4_mmi(), ff_put_vp8_epel16_v4_msa(), ff_put_vp8_epel16_v6_mmi(), ff_put_vp8_epel16_v6_msa(), ff_put_vp8_epel4_h4_mmi(), ff_put_vp8_epel4_h4_msa(), ff_put_vp8_epel4_h4v4_mmi(), ff_put_vp8_epel4_h4v6_mmi(), ff_put_vp8_epel4_h6_mmi(), ff_put_vp8_epel4_h6_msa(), ff_put_vp8_epel4_h6v4_mmi(), ff_put_vp8_epel4_h6v6_mmi(), ff_put_vp8_epel4_v4_mmi(), ff_put_vp8_epel4_v4_msa(), ff_put_vp8_epel4_v6_mmi(), ff_put_vp8_epel4_v6_msa(), ff_put_vp8_epel8_h4_mmi(), ff_put_vp8_epel8_h4_msa(), ff_put_vp8_epel8_h4v4_mmi(), ff_put_vp8_epel8_h4v6_mmi(), ff_put_vp8_epel8_h6_mmi(), ff_put_vp8_epel8_h6_msa(), ff_put_vp8_epel8_h6v4_mmi(), ff_put_vp8_epel8_h6v6_mmi(), ff_put_vp8_epel8_v4_mmi(), ff_put_vp8_epel8_v4_msa(), ff_put_vp8_epel8_v6_mmi(), ff_put_vp8_epel8_v6_msa(), filter_3800(), filter_fast_3320(), hevc_idct_16x16_msa(), hevc_idct_8x8_msa(), horiz_filter(), horiz_filter_clip(), hybrid4_8_12_cx(), hybrid6_cx(), iir_filter(), init_bsf(), initFilter(), libAVEnumPins_Cleanup(), libAVEnumPins_Clone(), libAVEnumPins_Setup(), libAVPin_Disconnect(), libAVPin_QueryPinInfo(), libAVPin_ReceiveConnection(), libAVPin_Setup(), list_filters(), main(), make_filters_from_proto(), mpegts_open_filter(), mpegts_open_pes_filter(), mpegts_open_section_filter(), new_output_stream(), pick_formats(), predictor_update_3930(), predictor_update_filter(), process_command(), ps_hybrid_analysis_c(), put_hevc_epel_bi_h(), put_hevc_epel_bi_hv(), put_hevc_epel_bi_v(), put_hevc_epel_bi_w_h(), put_hevc_epel_bi_w_hv(), put_hevc_epel_bi_w_v(), put_hevc_epel_h(), put_hevc_epel_hv(), put_hevc_epel_uni_h(), put_hevc_epel_uni_hv(), put_hevc_epel_uni_v(), put_hevc_epel_uni_w_h(), put_hevc_epel_uni_w_hv(), put_hevc_epel_uni_w_v(), put_hevc_epel_v(), put_hevc_qpel_bi_h(), put_hevc_qpel_bi_hv(), put_hevc_qpel_bi_v(), put_hevc_qpel_bi_w_h(), put_hevc_qpel_bi_w_hv(), put_hevc_qpel_bi_w_v(), put_hevc_qpel_h(), put_hevc_qpel_hv(), put_hevc_qpel_uni_h(), put_hevc_qpel_uni_hv(), put_hevc_qpel_uni_v(), put_hevc_qpel_uni_w_h(), put_hevc_qpel_uni_w_hv(), put_hevc_qpel_uni_w_v(), put_hevc_qpel_v(), qsv_init_bsf(), query_formats(), read_filter_params(), reap_filters(), resample_common(), resample_linear(), resample_one(), set_filter(), set_filter_params(), show_filters(), sws_getDefaultFilter(), truespeech_apply_twopoint_filter(), tta_decode_frame(), tta_encode_frame(), usePal(), vert_filter(), write_filter_params(), xa_decode(), and yuv2yuvX().
horiz_filter()
static void horiz_filter (int16_t * output, int16_t * low, int16_t * high, int width) static
Definition at line 121 of file cfhd.c.
Referenced by cfhd_decode().
horiz_filter_clip()
static void horiz_filter_clip (int16_t * output, int16_t * low, int16_t * high, int width, uint8_t clip) static
Definition at line 126 of file cfhd.c.
Referenced by cfhd_decode().
vert_filter()
static void vert_filter (int16_t * output, int out_stride, int16_t * low, int low_stride, int16_t * high, int high_stride, int len) static
Definition at line 131 of file cfhd.c.
Referenced by cfhd_decode().
free_buffers()
static void free_buffers (AVCodecContext * avctx) static
Definition at line 137 of file cfhd.c.
Referenced by cfhd_close_decoder(), and cfhd_decode().
alloc_buffers()
static int alloc_buffers (AVCodecContext * avctx) static
Definition at line 156 of file cfhd.c.
Referenced by cfhd_decode().
cfhd_decode()
static int cfhd_decode (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 227 of file cfhd.c.
cfhd_close_decoder()
static av_cold int cfhd_close_decoder (AVCodecContext * avctx) static
Definition at line 772 of file cfhd.c.
Variable Documentation
ff_cfhd_decoder
AVCodec ff_cfhd_decoder
Initial value:
= {
    .name           = "cfhd",
    .long_name      = NULL_IF_CONFIG_SMALL("Cineform HD"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_CFHD,
    .priv_data_size = sizeof(CFHDContext),
    .init           = cfhd_decode_init,
    .close          = cfhd_close_decoder,
    .decode         = cfhd_decode,
    .capabilities   = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_FRAME_THREADS,
    .caps_internal  = FF_CODEC_CAP_INIT_THREADSAFE | FF_CODEC_CAP_INIT_CLEANUP,
}
Definition at line 786 of file cfhd.c.