FFmpeg: libavcodec/cinepak.c File Reference
cinepak.c File Reference
Cinepak video decoder.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "libavutil/common.h"
#include "libavutil/intreadwrite.h"
#include "avcodec.h"
#include "internal.h"
Data Structures
struct cvid_strip
struct CinepakContext
Macros
#define MAX_STRIPS 32
Typedefs
typedef uint8_t cvid_codebook[12]
Functions
static void cinepak_decode_codebook (cvid_codebook *codebook, int chunk_id, int size, const uint8_t *data)
static int cinepak_decode_vectors (CinepakContext *s, cvid_strip *strip, int chunk_id, int size, const uint8_t *data)
static int cinepak_decode_strip (CinepakContext *s, cvid_strip *strip, const uint8_t *data, int size)
static int cinepak_decode (CinepakContext *s)
static av_cold int cinepak_decode_init (AVCodecContext *avctx)
static int cinepak_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int cinepak_decode_end (AVCodecContext *avctx)
Variables
AVCodec ff_cinepak_decoder
Detailed Description
Cinepak video decoder.
Author
Ewald Snel ewald.nosp@m.@ram.nosp@m.bo.it.nosp@m.s.tu.nosp@m.delft.nosp@m..nl
See also
For more information on the Cinepak algorithm, visit: http://www.csse.monash.edu.au/~timf/
For more information on the quirky data inside Sega FILM/CPK files, visit: http://wiki.multimedia.cx/index.php?title=Sega_FILM
Cinepak colorspace support (c) 2013 Rl, Aetey Global Technologies AB
Author
Cinepak colorspace, Rl, Aetey Global Technologies AB
Definition in file cinepak.c.
Macro Definition Documentation
MAX_STRIPS
#define MAX_STRIPS 32
Definition at line 48 of file cinepak.c.
Referenced by cinepak_decode().
Typedef Documentation
cvid_codebook
typedef uint8_t cvid_codebook[12]
Definition at line 46 of file cinepak.c.
Function Documentation
cinepak_decode_codebook()
static void cinepak_decode_codebook (cvid_codebook * codebook, int chunk_id, int size, const uint8_t * data) static
Definition at line 76 of file cinepak.c.
Referenced by cinepak_decode_strip().
cinepak_decode_vectors()
static int cinepak_decode_vectors (CinepakContext * s, cvid_strip * strip, int chunk_id, int size, const uint8_t * data) static
Definition at line 132 of file cinepak.c.
Referenced by cinepak_decode_strip().
cinepak_decode_strip()
static int cinepak_decode_strip (CinepakContext * s, cvid_strip * strip, const uint8_t * data, int size) static
Definition at line 266 of file cinepak.c.
Referenced by cinepak_decode().
cinepak_decode()
static int cinepak_decode (CinepakContext * s) static
Definition at line 318 of file cinepak.c.
Referenced by cinepak_decode_frame().
cinepak_decode_init()
static av_cold int cinepak_decode_init (AVCodecContext * avctx) static
Definition at line 405 of file cinepak.c.
cinepak_decode_frame()
static int cinepak_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 431 of file cinepak.c.
cinepak_decode_end()
static av_cold int cinepak_decode_end (AVCodecContext * avctx) static
Definition at line 472 of file cinepak.c.
Variable Documentation
ff_cinepak_decoder
AVCodec ff_cinepak_decoder
Initial value:
= {
    .name           = "cinepak",
    .long_name      = NULL_IF_CONFIG_SMALL("Cinepak"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_CINEPAK,
    .priv_data_size = sizeof(CinepakContext),
    .init           = cinepak_decode_init,
    .close          = cinepak_decode_end,
    .decode         = cinepak_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 481 of file cinepak.c.