FFmpeg: libavcodec/cllc.c File Reference
cllc.c File Reference
#include <inttypes.h>
#include "libavutil/intreadwrite.h"
#include "bswapdsp.h"
#include "canopus.h"
#include "get_bits.h"
#include "avcodec.h"
#include "internal.h"
Data Structures
struct CLLCContext
Functions
static int read_code_table (CLLCContext *ctx, GetBitContext *gb, VLC *vlc)
static int read_argb_line (CLLCContext *ctx, GetBitContext *gb, int *top_left, VLC *vlc, uint8_t *outbuf)
static int read_rgb24_component_line (CLLCContext *ctx, GetBitContext *gb, int *top_left, VLC *vlc, uint8_t *outbuf)
static int read_yuv_component_line (CLLCContext *ctx, GetBitContext *gb, int *top_left, VLC *vlc, uint8_t *outbuf, int is_chroma)
static int decode_argb_frame (CLLCContext *ctx, GetBitContext *gb, AVFrame *pic)
static int decode_rgb24_frame (CLLCContext *ctx, GetBitContext *gb, AVFrame *pic)
static int decode_yuv_frame (CLLCContext *ctx, GetBitContext *gb, AVFrame *pic)
static int cllc_decode_frame (AVCodecContext *avctx, void *data, int *got_picture_ptr, AVPacket *avpkt)
static av_cold int cllc_decode_close (AVCodecContext *avctx)
static av_cold int cllc_decode_init (AVCodecContext *avctx)
Variables
AVCodec ff_cllc_decoder
Function Documentation
read_code_table()
static int read_code_table (CLLCContext * ctx, GetBitContext * gb, VLC * vlc) static
Definition at line 40 of file cllc.c.
Referenced by decode_argb_frame(), decode_rgb24_frame(), and decode_yuv_frame().
read_argb_line()
static int read_argb_line (CLLCContext * ctx, GetBitContext * gb, int * top_left, VLC * vlc, uint8_t * outbuf) static
Definition at line 85 of file cllc.c.
Referenced by decode_argb_frame().
read_rgb24_component_line()
static int read_rgb24_component_line (CLLCContext * ctx, GetBitContext * gb, int * top_left, VLC * vlc, uint8_t * outbuf) static
Definition at line 154 of file cllc.c.
Referenced by decode_rgb24_frame().
read_yuv_component_line()
static int read_yuv_component_line (CLLCContext * ctx, GetBitContext * gb, int * top_left, VLC * vlc, uint8_t * outbuf, int is_chroma) static
Definition at line 184 of file cllc.c.
Referenced by decode_yuv_frame().
decode_argb_frame()
static int decode_argb_frame (CLLCContext * ctx, GetBitContext * gb, AVFrame * pic) static
Definition at line 212 of file cllc.c.
Referenced by cllc_decode_frame().
decode_rgb24_frame()
static int decode_rgb24_frame (CLLCContext * ctx, GetBitContext * gb, AVFrame * pic) static
Definition at line 256 of file cllc.c.
Referenced by cllc_decode_frame().
decode_yuv_frame()
static int decode_yuv_frame (CLLCContext * ctx, GetBitContext * gb, AVFrame * pic) static
Definition at line 300 of file cllc.c.
Referenced by cllc_decode_frame().
cllc_decode_frame()
static int cllc_decode_frame (AVCodecContext * avctx, void * data, int * got_picture_ptr, AVPacket * avpkt) static
Definition at line 355 of file cllc.c.
cllc_decode_close()
static av_cold int cllc_decode_close (AVCodecContext * avctx) static
Definition at line 466 of file cllc.c.
cllc_decode_init()
static av_cold int cllc_decode_init (AVCodecContext * avctx) static
Definition at line 475 of file cllc.c.
Variable Documentation
ff_cllc_decoder
AVCodec ff_cllc_decoder
Initial value:
= {
    .name           = "cllc",
    .long_name      = NULL_IF_CONFIG_SMALL("Canopus Lossless Codec"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_CLLC,
    .priv_data_size = sizeof(CLLCContext),
    .init           = cllc_decode_init,
    .decode         = cllc_decode_frame,
    .close          = cllc_decode_close,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 489 of file cllc.c.