FFmpeg: cmdutils_opencl.c File Reference
cmdutils_opencl.c File Reference
#include "libavutil/opt.h"
#include "libavutil/time.h"
#include "libavutil/log.h"
#include "libavutil/opencl.h"
#include "libavutil/avstring.h"
#include "cmdutils.h"
Data Structures
struct OpenCLDeviceBenchmark
Macros
#define OCLCHECK(method, ...)
#define CREATEBUF(out, flags, size)
#define OPENCL_NB_ITER 5
Functions
static void fill_rand_int (int *data, int n)
static int64_t run_opencl_bench (AVOpenCLExternalEnv *ext_opencl_env)
static int compare_ocl_device_desc (const void *a, const void *b)
int opt_opencl_bench (void *optctx, const char *opt, const char *arg)
int opt_opencl (void *optctx, const char *opt, const char *arg)
Variables
const char * ocl_bench_source
Macro Definition Documentation
OCLCHECK
#define OCLCHECK (method, ...)
Value:
do {                                                                           \
    status = method(__VA_ARGS__);                                              \
    if (status != CL_SUCCESS) {                                                \
        av_log(NULL, AV_LOG_ERROR, # method " error '%s'\n",                   \
               av_opencl_errstr(status));                                      \
        ret = AVERROR_EXTERNAL;                                                \
        goto end;                                                              \
    }                                                                          \
} while (0)
Definition at line 95 of file cmdutils_opencl.c.
Referenced by run_opencl_bench().
CREATEBUF
#define CREATEBUF (out, flags, size)
Value:
do {                                                                           \
    out = clCreateBuffer(ext_opencl_env->context, flags, size, NULL, &status); \
    if (status != CL_SUCCESS) {                                                \
        av_log(NULL, AV_LOG_ERROR, "Could not create OpenCL buffer\n");        \
        ret = AVERROR_EXTERNAL;                                                \
        goto end;                                                              \
    }                                                                          \
} while (0)
Definition at line 106 of file cmdutils_opencl.c.
Referenced by run_opencl_bench().
OPENCL_NB_ITER
#define OPENCL_NB_ITER 5
Definition at line 124 of file cmdutils_opencl.c.
Referenced by run_opencl_bench().
Function Documentation
fill_rand_int()
static void fill_rand_int (int * data, int n) static
Definition at line 116 of file cmdutils_opencl.c.
Referenced by run_opencl_bench().
run_opencl_bench()
static int64_t run_opencl_bench (AVOpenCLExternalEnv * ext_opencl_env) static
Definition at line 125 of file cmdutils_opencl.c.
Referenced by opt_opencl_bench().
compare_ocl_device_desc()
static int compare_ocl_device_desc (const void * a, const void * b) static
Definition at line 207 of file cmdutils_opencl.c.
Referenced by opt_opencl_bench().
opt_opencl_bench()
int opt_opencl_bench (void * optctx, const char * opt, const char * arg)
Definition at line 214 of file cmdutils_opencl.c.
opt_opencl()
int opt_opencl (void * optctx, const char * opt, const char * arg)
Definition at line 262 of file cmdutils_opencl.c.
Variable Documentation
ocl_bench_source
const char* ocl_bench_source
Definition at line 35 of file cmdutils_opencl.c.
Referenced by run_opencl_bench().