FFmpeg: cmdutils.h File Reference
cmdutils.h File Reference
#include <stdint.h>
#include "config.h"
#include "libavcodec/avcodec.h"
#include "libavfilter/avfilter.h"
#include "libavformat/avformat.h"
#include "libswscale/swscale.h"
Data Structures
struct SpecifierOpt
struct OptionDef
struct Option
An option extracted from the commandline.
struct OptionGroupDef
struct OptionGroup
struct OptionGroupList
A list of option groups that all have the same group type (e.g.
struct OptionParseContext
Macros
#define HAS_ARG 0x0001
#define OPT_BOOL 0x0002
#define OPT_EXPERT 0x0004
#define OPT_STRING 0x0008
#define OPT_VIDEO 0x0010
#define OPT_AUDIO 0x0020
#define OPT_INT 0x0080
#define OPT_FLOAT 0x0100
#define OPT_SUBTITLE 0x0200
#define OPT_INT64 0x0400
#define OPT_EXIT 0x0800
#define OPT_DATA 0x1000
#define OPT_PERFILE
#define OPT_OFFSET 0x4000 /* option is specified as an offset in a passed optctx */
#define OPT_SPEC
#define OPT_TIME 0x10000
#define OPT_DOUBLE 0x20000
#define OPT_INPUT 0x40000
#define OPT_OUTPUT 0x80000
#define media_type_string av_get_media_type_string
#define GROW_ARRAY(array, nb_elems) array = grow_array(array, sizeof(*array), &nb_elems, nb_elems + 1)
#define GET_PIX_FMT_NAME(pix_fmt) const char *name = av_get_pix_fmt_name(pix_fmt);
#define GET_SAMPLE_FMT_NAME(sample_fmt) const char *name = av_get_sample_fmt_name(sample_fmt)
#define GET_SAMPLE_RATE_NAME(rate)
#define GET_CH_LAYOUT_NAME(ch_layout)
#define GET_CH_LAYOUT_DESC(ch_layout)
Functions
void register_exit (void(*cb)(int ret))
Register a program-specific cleanup routine.
void exit_program (int ret) av_noreturn
Wraps exit with a program-specific cleanup routine.
void init_dynload (void)
Initialize dynamic library loading.
void init_opts (void)
Initialize the cmdutils option system, in particular allocate the *_opts contexts.
void uninit_opts (void)
Uninitialize the cmdutils option system, in particular free the *_opts contexts and their contents.
void log_callback_help (void *ptr, int level, const char *fmt, va_list vl)
Trivial log callback.
int opt_cpuflags (void *optctx, const char *opt, const char *arg)
Override the cpuflags.
int opt_default (void *optctx, const char *opt, const char *arg)
Fallback for options that are not explicitly handled, these will be parsed through AVOptions.
int opt_loglevel (void *optctx, const char *opt, const char *arg)
Set the libav* libraries log level.
int opt_report (const char *opt)
int opt_max_alloc (void *optctx, const char *opt, const char *arg)
int opt_codec_debug (void *optctx, const char *opt, const char *arg)
int opt_timelimit (void *optctx, const char *opt, const char *arg)
Limit the execution time.
double parse_number_or_die (const char *context, const char *numstr, int type, double min, double max)
Parse a string and return its corresponding value as a double.
int64_t parse_time_or_die (const char *context, const char *timestr, int is_duration)
Parse a string specifying a time and return its corresponding value as a number of microseconds.
void show_help_options (const OptionDef *options, const char *msg, int req_flags, int rej_flags, int alt_flags)
Print help for all options matching specified flags.
void show_help_children (const AVClass *class, int flags)
Show help for all options with given flags in class and all its children.
void show_help_default (const char *opt, const char *arg)
Per-fftool specific help handler.
int show_help (void *optctx, const char *opt, const char *arg)
Generic -h handler common to all fftools.
void parse_options (void *optctx, int argc, char **argv, const OptionDef *options, void(*parse_arg_function)(void *optctx, const char *))
Parse the command line arguments.
int parse_option (void *optctx, const char *opt, const char *arg, const OptionDef *options)
Parse one given option.
int parse_optgroup (void *optctx, OptionGroup *g)
Parse an options group and write results into optctx.
int split_commandline (OptionParseContext *octx, int argc, char *argv[], const OptionDef *options, const OptionGroupDef *groups, int nb_groups)
Split the commandline into an intermediate form convenient for further processing.
void uninit_parse_context (OptionParseContext *octx)
Free all allocated memory in an OptionParseContext.
void parse_loglevel (int argc, char **argv, const OptionDef *options)
Find the '-loglevel' option in the command line args and apply it.
int locate_option (int argc, char **argv, const OptionDef *options, const char *optname)
Return index of option opt in argv or 0 if not found.
int check_stream_specifier (AVFormatContext *s, AVStream *st, const char *spec)
Check if the given stream matches a stream specifier.
AVDictionary * filter_codec_opts (AVDictionary *opts, enum AVCodecID codec_id, AVFormatContext *s, AVStream *st, AVCodec *codec)
Filter out options for given codec.
AVDictionary ** setup_find_stream_info_opts (AVFormatContext *s, AVDictionary *codec_opts)
Setup AVCodecContext options for avformat_find_stream_info().
void print_error (const char *filename, int err)
Print an error message to stderr, indicating filename and a human readable description of the error code err.
void show_banner (int argc, char **argv, const OptionDef *options)
Print the program banner to stderr.
int show_version (void *optctx, const char *opt, const char *arg)
Print the version of the program to stdout.
int show_buildconf (void *optctx, const char *opt, const char *arg)
Print the build configuration of the program to stdout.
int show_license (void *optctx, const char *opt, const char *arg)
Print the license of the program to stdout.
int show_formats (void *optctx, const char *opt, const char *arg)
Print a listing containing all the formats supported by the program (including devices).
int show_muxers (void *optctx, const char *opt, const char *arg)
Print a listing containing all the muxers supported by the program (including devices).
int show_demuxers (void *optctx, const char *opt, const char *arg)
Print a listing containing all the demuxer supported by the program (including devices).
int show_devices (void *optctx, const char *opt, const char *arg)
Print a listing containing all the devices supported by the program.
int show_codecs (void *optctx, const char *opt, const char *arg)
Print a listing containing all the codecs supported by the program.
int show_decoders (void *optctx, const char *opt, const char *arg)
Print a listing containing all the decoders supported by the program.
int show_encoders (void *optctx, const char *opt, const char *arg)
Print a listing containing all the encoders supported by the program.
int show_filters (void *optctx, const char *opt, const char *arg)
Print a listing containing all the filters supported by the program.
int show_bsfs (void *optctx, const char *opt, const char *arg)
Print a listing containing all the bit stream filters supported by the program.
int show_protocols (void *optctx, const char *opt, const char *arg)
Print a listing containing all the protocols supported by the program.
int show_pix_fmts (void *optctx, const char *opt, const char *arg)
Print a listing containing all the pixel formats supported by the program.
int show_layouts (void *optctx, const char *opt, const char *arg)
Print a listing containing all the standard channel layouts supported by the program.
int show_sample_fmts (void *optctx, const char *opt, const char *arg)
Print a listing containing all the sample formats supported by the program.
int show_colors (void *optctx, const char *opt, const char *arg)
Print a listing containing all the color names and values recognized by the program.
int read_yesno (void)
Return a positive value if a line read from standard input starts with [yY], otherwise return 0.
FILE * get_preset_file (char *filename, size_t filename_size, const char *preset_name, int is_path, const char *codec_name)
Get a file corresponding to a preset file.
void * grow_array (void *array, int elem_size, int *size, int new_size)
Realloc array to hold new_size elements of elem_size.
double get_rotation (AVStream *st)
Variables
const char program_name []
program name, defined by the program for show_version().
const int program_birth_year
program birth year, defined by the program for show_banner()
AVCodecContext * avcodec_opts [AVMEDIA_TYPE_NB]
AVFormatContext * avformat_opts
AVDictionary * sws_dict
AVDictionary * swr_opts
AVDictionary * format_opts
AVDictionary * codec_opts
AVDictionary * resample_opts
int hide_banner
Macro Definition Documentation
HAS_ARG
#define HAS_ARG 0x0001
Definition at line 168 of file cmdutils.h.
Referenced by locate_option(), opt_progress(), parse_option(), and split_commandline().
OPT_BOOL
#define OPT_BOOL 0x0002
Definition at line 169 of file cmdutils.h.
Referenced by opt_progress(), parse_option(), split_commandline(), and write_option().
OPT_EXPERT
#define OPT_EXPERT 0x0004
Definition at line 170 of file cmdutils.h.
Referenced by show_help_default().
OPT_STRING
#define OPT_STRING 0x0008
Definition at line 171 of file cmdutils.h.
Referenced by uninit_options(), and write_option().
OPT_VIDEO
#define OPT_VIDEO 0x0010
Definition at line 172 of file cmdutils.h.
Referenced by show_help_default().
OPT_AUDIO
#define OPT_AUDIO 0x0020
Definition at line 173 of file cmdutils.h.
Referenced by show_help_default().
OPT_INT
#define OPT_INT 0x0080
Definition at line 174 of file cmdutils.h.
Referenced by opt_show_mode(), opt_streamid(), opt_vsync(), parse_number_or_die(), and write_option().
OPT_FLOAT
#define OPT_FLOAT 0x0100
Definition at line 175 of file cmdutils.h.
Referenced by write_option().
OPT_SUBTITLE
#define OPT_SUBTITLE 0x0200
Definition at line 176 of file cmdutils.h.
Referenced by show_help_default().
OPT_INT64
#define OPT_INT64 0x0400
Definition at line 177 of file cmdutils.h.
Referenced by opt_height(), opt_timelimit(), opt_width(), parse_number_or_die(), and write_option().
OPT_EXIT
#define OPT_EXIT 0x0800
Definition at line 178 of file cmdutils.h.
Referenced by opt_progress(), show_help_default(), split_commandline(), and write_option().
OPT_DATA
#define OPT_DATA 0x1000
Definition at line 179 of file cmdutils.h.
OPT_PERFILE
#define OPT_PERFILE
Value:
0x2000     /* the option is per-file (currently ffmpeg-only).
                                   implied by OPT_OFFSET or OPT_SPEC */
Definition at line 180 of file cmdutils.h.
Referenced by add_opt(), check_options(), and show_help_default().
OPT_OFFSET
#define OPT_OFFSET 0x4000 /* option is specified as an offset in a passed optctx */
Definition at line 182 of file cmdutils.h.
Referenced by add_opt(), show_help_default(), uninit_options(), and write_option().
OPT_SPEC
#define OPT_SPEC
Value:
0x8000       /* option is to be stored in an array of SpecifierOpt.
                                   Implies OPT_OFFSET. Next element after the offset is
                                   an int containing element count in the array. */
Definition at line 183 of file cmdutils.h.
Referenced by add_opt(), show_help_default(), uninit_options(), and write_option().
OPT_TIME
#define OPT_TIME 0x10000
Definition at line 186 of file cmdutils.h.
Referenced by write_option().
OPT_DOUBLE
#define OPT_DOUBLE 0x20000
Definition at line 187 of file cmdutils.h.
Referenced by write_option().
OPT_INPUT
#define OPT_INPUT 0x40000
Definition at line 188 of file cmdutils.h.
Referenced by check_options().
OPT_OUTPUT
#define OPT_OUTPUT 0x80000
Definition at line 189 of file cmdutils.h.
Referenced by check_options().
media_type_string
#define media_type_string av_get_media_type_string
Definition at line 590 of file cmdutils.h.
Referenced by print_final_stats(), and show_help_muxer().
GROW_ARRAY
#define GROW_ARRAY (array, nb_elems) array = grow_array(array, sizeof(*array), &nb_elems, nb_elems + 1)
Definition at line 592 of file cmdutils.h.
Referenced by add_input_streams(), add_opt(), DEF_CHOOSE_FORMAT(), finish_group(), init_complex_filtergraph(), init_input_filter(), new_output_stream(), open_input_file(), open_output_file(), opt_attach(), opt_filter_complex(), opt_filter_complex_script(), opt_map(), and opt_map_channel().
GET_PIX_FMT_NAME
#define GET_PIX_FMT_NAME (pix_fmt) const char *name = av_get_pix_fmt_name(pix_fmt);
Definition at line 595 of file cmdutils.h.
Referenced by print_codec().
GET_SAMPLE_FMT_NAME
#define GET_SAMPLE_FMT_NAME (sample_fmt) const char *name = av_get_sample_fmt_name(sample_fmt)
Definition at line 598 of file cmdutils.h.
Referenced by print_codec().
GET_SAMPLE_RATE_NAME
#define GET_SAMPLE_RATE_NAME (rate)
Value:
char name[16];\
    snprintf(name, sizeof(name), "%d", rate);
Definition at line 601 of file cmdutils.h.
Referenced by print_codec().
GET_CH_LAYOUT_NAME
#define GET_CH_LAYOUT_NAME (ch_layout)
Value:
char name[16];\
    snprintf(name, sizeof(name), "0x%"PRIx64, ch_layout);
Definition at line 605 of file cmdutils.h.
GET_CH_LAYOUT_DESC
#define GET_CH_LAYOUT_DESC (ch_layout)
Value:
char name[128];\
    av_get_channel_layout_string(name, sizeof(name), 0, ch_layout);
Definition at line 609 of file cmdutils.h.
Referenced by print_codec().
Function Documentation
register_exit()
void register_exit (void(*)(int ret) cb)
Register a program-specific cleanup routine.
Definition at line 130 of file cmdutils.c.
Referenced by main().
exit_program()
void exit_program (int ret)
Wraps exit with a program-specific cleanup routine.
Definition at line 135 of file cmdutils.c.
Referenced by abort_codec_experimental(), add_input_streams(), assert_avoptions(), assert_file_overwrite(), check_decode_result(), check_streamcopy_filters(), choose_pix_fmts(), configure_output_filter(), copy_metadata(), decode_audio(), decode_video(), DEF_CHOOSE_FORMAT(), do_audio_out(), do_streamcopy(), do_subtitle_out(), do_video_out(), do_video_stats(), dump_attachment(), filter_codec_opts(), find_codec_or_die(), flush_encoders(), get_codecs_sorted(), get_line(), get_ost_filters(), grow_array(), init_complex_filtergraph(), init_input_filter(), init_output_filter(), init_output_stream(), init_output_stream_encode(), init_output_stream_streamcopy(), init_parse_context(), init_report(), main(), new_audio_stream(), new_data_stream(), new_output_stream(), new_subtitle_stream(), new_unknown_stream(), new_video_stream(), open_input_file(), open_output_file(), opt_input_file(), opt_loglevel(), opt_map(), opt_map_channel(), opt_max_alloc(), opt_preset(), opt_sdp_file(), opt_streamid(), opt_target(), opt_vstats(), output_packet(), parse_forced_key_frames(), parse_matrix_coeffs(), parse_meta_type(), parse_number_or_die(), parse_options(), parse_time_or_die(), print_sdp(), process_input(), process_input_packet(), set_encoder_id(), transcode(), transcode_init(), write_option(), and write_packet().
init_dynload()
void init_dynload (void)
Initialize dynamic library loading.
Definition at line 119 of file cmdutils.c.
Referenced by main().
init_opts()
void init_opts (void)
Initialize the cmdutils option system, in particular allocate the *_opts contexts.
Definition at line 84 of file cmdutils.c.
Referenced by finish_group(), init_parse_context(), and main().
uninit_opts()
void uninit_opts (void)
Uninitialize the cmdutils option system, in particular free the *_opts contexts and their contents.
Definition at line 89 of file cmdutils.c.
Referenced by do_exit(), ffmpeg_cleanup(), main(), and uninit_parse_context().
log_callback_help()
void log_callback_help (void * ptr, int level, const char * fmt, va_list vl)
Trivial log callback.
Only suitable for opt_help and similar since it lacks prefix handling.
Definition at line 98 of file cmdutils.c.
Referenced by show_buildconf(), show_help(), show_help_default(), and show_version().
opt_cpuflags()
int opt_cpuflags (void * optctx, const char * opt, const char * arg)
Override the cpuflags.
Definition at line 956 of file cmdutils.c.
opt_default()
int opt_default (void * optctx, const char * opt, const char * arg)
Fallback for options that are not explicitly handled, these will be parsed through AVOptions.
Definition at line 550 of file cmdutils.c.
Referenced by opt_default_new(), opt_frame_pix_fmt(), opt_frame_size(), opt_target(), opt_video_channel(), opt_video_standard(), and split_commandline().
opt_loglevel()
int opt_loglevel (void * optctx, const char * opt, const char * arg)
Set the libav* libraries log level.
Definition at line 968 of file cmdutils.c.
Referenced by main(), and parse_loglevel().
opt_report()
int opt_report (const char * opt)
Definition at line 1117 of file cmdutils.c.
opt_max_alloc()
int opt_max_alloc (void * optctx, const char * opt, const char * arg)
Definition at line 1122 of file cmdutils.c.
opt_codec_debug()
int opt_codec_debug (void * optctx, const char * opt, const char * arg)
opt_timelimit()
int opt_timelimit (void * optctx, const char * opt, const char * arg)
Limit the execution time.
Definition at line 1136 of file cmdutils.c.
parse_number_or_die()
double parse_number_or_die (const char * context, const char * numstr, int type, double min, double max)
Parse a string and return its corresponding value as a double.
Exit from the application if the string cannot be correctly parsed or the corresponding value is invalid.
Parameters
context the context of the value to be set (e.g. the corresponding command line option name)
numstr the string to be parsed
type the type (OPT_INT64 or OPT_FLOAT) as which the string should be parsed
min the minimum valid accepted value
max the maximum valid accepted value
Definition at line 143 of file cmdutils.c.
Referenced by opt_height(), opt_show_mode(), opt_streamid(), opt_timelimit(), opt_vsync(), opt_width(), and write_option().
parse_time_or_die()
int64_t parse_time_or_die (const char * context, const char * timestr, int is_duration)
Parse a string specifying a time and return its corresponding value as a number of microseconds.
Exit from the application if the string cannot be correctly parsed.
Parameters
context the context of the value to be set (e.g. the corresponding command line option name)
timestr the string to be parsed
is_duration a flag which tells how to interpret timestr, if not zero timestr is interpreted as a duration, otherwise as a date
See also
av_parse_time()
Definition at line 164 of file cmdutils.c.
Referenced by opt_duration(), opt_recording_timestamp(), opt_seek(), parse_forced_key_frames(), and write_option().
show_help_options()
void show_help_options (const OptionDef * options, const char * msg, int req_flags, int rej_flags, int alt_flags)
Print help for all options matching specified flags.
Parameters
options a list of options
msg title of this group. Only printed if at least one option matches.
req_flags print only options which have all those flags set.
rej_flags don't print options which have any of those flags set.
alt_flags print only options that have at least one of those flags set
Definition at line 176 of file cmdutils.c.
Referenced by show_help_default().
show_help_children()
void show_help_children (const AVClass * class, int flags)
Show help for all options with given flags in class and all its children.
Definition at line 205 of file cmdutils.c.
Referenced by print_codec(), show_help_children(), show_help_default(), show_help_demuxer(), and show_help_muxer().
show_help_default()
void show_help_default (const char * opt, const char * arg)
Per-fftool specific help handler.
Implemented in each fftool, called by show_help().
Definition at line 3133 of file ffmpeg_opt.c.
Referenced by show_help().
show_help()
int show_help (void * optctx, const char * opt, const char * arg)
Generic -h handler common to all fftools.
Definition at line 1997 of file cmdutils.c.
parse_options()
void parse_options (void * optctx, int argc, char ** argv, const OptionDef * options, void(*)(void *optctx, const char *) parse_arg_function)
Parse the command line arguments.
Parameters
optctx an opaque options context
argc number of command line arguments
argv values of command line arguments
options Array with the definitions required to interpret every option of the form: -option_name [argument]
parse_arg_function Name of the function called to process every argument without a leading option name flag. NULL if such arguments do not have to be processed.
parse_option()
int parse_option (void * optctx, const char * opt, const char * arg, const OptionDef * options)
Parse one given option.
Returns
on success 1 if arg was consumed, 0 otherwise; negative number on error
Definition at line 353 of file cmdutils.c.
Referenced by open_output_file(), opt_audio_codec(), opt_audio_filters(), opt_audio_frames(), opt_audio_qscale(), opt_channel_layout(), opt_data_codec(), opt_data_frames(), opt_old2new(), opt_qscale(), opt_recording_timestamp(), opt_subtitle_codec(), opt_target(), opt_timecode(), opt_video_codec(), opt_video_filters(), opt_video_frames(), and parse_options().
parse_optgroup()
int parse_optgroup (void * optctx, OptionGroup * g)
Parse an options group and write results into optctx.
Parameters
optctx an app-specific options context. NULL for global options group
Definition at line 419 of file cmdutils.c.
Referenced by ffmpeg_parse_options(), and open_files().
split_commandline()
int split_commandline (OptionParseContext * octx, int argc, char * argv[], const OptionDef * options, const OptionGroupDef * groups, int nb_groups)
Split the commandline into an intermediate form convenient for further processing.
The commandline is assumed to be composed of options which either belong to a group (those with OPT_SPEC, OPT_OFFSET or OPT_PERFILE) or are global (everything else).
A group (defined by an OptionGroupDef struct) is a sequence of options terminated by either a group separator option (e.g. -i) or a parameter that is not an option (doesn't start with -). A group without a separator option must always be first in the supplied groups list.
All options within the same group are stored in one OptionGroup struct in an OptionGroupList, all groups with the same group definition are stored in one OptionGroupList in OptionParseContext.groups. The order of group lists is the same as the order of group definitions.
Definition at line 850 of file cmdutils.c.
Referenced by ffmpeg_parse_options().
uninit_parse_context()
void uninit_parse_context (OptionParseContext * octx)
Free all allocated memory in an OptionParseContext.
Definition at line 824 of file cmdutils.c.
Referenced by ffmpeg_parse_options().
parse_loglevel()
void parse_loglevel (int argc, char ** argv, const OptionDef * options)
Find the '-loglevel' option in the command line args and apply it.
Definition at line 511 of file cmdutils.c.
Referenced by main().
locate_option()
int locate_option (int argc, char ** argv, const OptionDef * options, const char * optname)
Return index of option opt in argv or 0 if not found.
Definition at line 452 of file cmdutils.c.
Referenced by parse_loglevel(), and show_banner().
check_stream_specifier()
int check_stream_specifier (AVFormatContext * s, AVStream * st, const char * spec)
Check if the given stream matches a stream specifier.
Parameters
s Corresponding format context.
st Stream from s to be checked.
spec A stream specifier of the [v|a|s|d]:[<stream index>] form.
Returns
1 if the stream matches, 0 if it doesn't, <0 on error
Definition at line 2092 of file cmdutils.c.
Referenced by copy_metadata(), filter_codec_opts(), init_input_filter(), open_input_file(), open_output_file(), and opt_map().
filter_codec_opts()
AVDictionary* filter_codec_opts (AVDictionary * opts, enum AVCodecID codec_id, AVFormatContext * s, AVStream * st, AVCodec * codec)
Filter out options for given codec.
Create a new options dictionary containing only the options from opts which apply to the codec with ID codec_id.
Parameters
opts dictionary to place options in
codec_id ID of the codec that should be filtered for
s Corresponding format context.
st A stream from s for which the options should be filtered.
codec The particular codec for which the options should be filtered. If null, the default one is looked up according to the codec id.
Returns
a pointer to the created dictionary
Definition at line 2102 of file cmdutils.c.
Referenced by add_input_streams(), new_output_stream(), open_input_file(), setup_find_stream_info_opts(), and stream_component_open().
setup_find_stream_info_opts()
AVDictionary** setup_find_stream_info_opts (AVFormatContext * s, AVDictionary * codec_opts)
Setup AVCodecContext options for avformat_find_stream_info().
Create an array of dictionaries, one dictionary for each stream contained in s. Each dictionary will contain the options from codec_opts which can be applied to the corresponding stream codec context.
Returns
pointer to the created array of dictionaries, NULL if it cannot be created
Definition at line 2159 of file cmdutils.c.
Referenced by open_input_file(), and read_thread().
print_error()
void print_error (const char * filename, int err)
Print an error message to stderr, indicating filename and a human readable description of the error code err.
If strerror_r() is not available the use of this function in a multithreaded application may be unsafe.
See also
av_strerror()
Definition at line 1149 of file cmdutils.c.
Referenced by open_input_file(), open_output_file(), process_input(), read_thread(), and write_packet().
show_banner()
void show_banner (int argc, char ** argv, const OptionDef * options)
Print the program banner to stderr.
The banner contents depend on the current version of the repository and of the libav* libraries used by the program.
Definition at line 1248 of file cmdutils.c.
Referenced by main().
show_version()
int show_version (void * optctx, const char * opt, const char * arg)
Print the version of the program to stdout.
The version message depends on the current versions of the repository and of the libav* libraries. This option processing function does not utilize the arguments.
Definition at line 1259 of file cmdutils.c.
show_buildconf()
int show_buildconf (void * optctx, const char * opt, const char * arg)
Print the build configuration of the program to stdout.
The contents depend on the definition of FFMPEG_CONFIGURATION. This option processing function does not utilize the arguments.
Definition at line 1268 of file cmdutils.c.
show_license()
int show_license (void * optctx, const char * opt, const char * arg)
Print the license of the program to stdout.
The license depends on the license of the libraries compiled into the program. This option processing function does not utilize the arguments.
Definition at line 1276 of file cmdutils.c.
show_formats()
int show_formats (void * optctx, const char * opt, const char * arg)
Print a listing containing all the formats supported by the program (including devices).
This option processing function does not utilize the arguments.
Definition at line 1416 of file cmdutils.c.
show_muxers()
int show_muxers (void * optctx, const char * opt, const char * arg)
Print a listing containing all the muxers supported by the program (including devices).
This option processing function does not utilize the arguments.
Definition at line 1421 of file cmdutils.c.
show_demuxers()
int show_demuxers (void * optctx, const char * opt, const char * arg)
Print a listing containing all the demuxer supported by the program (including devices).
This option processing function does not utilize the arguments.
Definition at line 1426 of file cmdutils.c.
show_devices()
int show_devices (void * optctx, const char * opt, const char * arg)
Print a listing containing all the devices supported by the program.
This option processing function does not utilize the arguments.
Definition at line 1431 of file cmdutils.c.
show_codecs()
int show_codecs (void * optctx, const char * opt, const char * arg)
Print a listing containing all the codecs supported by the program.
This option processing function does not utilize the arguments.
Definition at line 1592 of file cmdutils.c.
show_decoders()
int show_decoders (void * optctx, const char * opt, const char * arg)
Print a listing containing all the decoders supported by the program.
Definition at line 1685 of file cmdutils.c.
show_encoders()
int show_encoders (void * optctx, const char * opt, const char * arg)
Print a listing containing all the encoders supported by the program.
Definition at line 1691 of file cmdutils.c.
show_filters()
int show_filters (void * optctx, const char * opt, const char * arg)
Print a listing containing all the filters supported by the program.
This option processing function does not utilize the arguments.
Definition at line 1724 of file cmdutils.c.
show_bsfs()
int show_bsfs (void * optctx, const char * opt, const char * arg)
Print a listing containing all the bit stream filters supported by the program.
This option processing function does not utilize the arguments.
Definition at line 1697 of file cmdutils.c.
show_protocols()
int show_protocols (void * optctx, const char * opt, const char * arg)
Print a listing containing all the protocols supported by the program.
This option processing function does not utilize the arguments.
Definition at line 1709 of file cmdutils.c.
show_pix_fmts()
int show_pix_fmts (void * optctx, const char * opt, const char * arg)
Print a listing containing all the pixel formats supported by the program.
This option processing function does not utilize the arguments.
Definition at line 1784 of file cmdutils.c.
show_layouts()
int show_layouts (void * optctx, const char * opt, const char * arg)
Print a listing containing all the standard channel layouts supported by the program.
This option processing function does not utilize the arguments.
Definition at line 1817 of file cmdutils.c.
show_sample_fmts()
int show_sample_fmts (void * optctx, const char * opt, const char * arg)
Print a listing containing all the sample formats supported by the program.
Definition at line 1846 of file cmdutils.c.
show_colors()
int show_colors (void * optctx, const char * opt, const char * arg)
Print a listing containing all the color names and values recognized by the program.
Definition at line 1770 of file cmdutils.c.
read_yesno()
int read_yesno (void)
Return a positive value if a line read from standard input starts with [yY], otherwise return 0.
Definition at line 2031 of file cmdutils.c.
Referenced by assert_file_overwrite().
get_preset_file()
FILE* get_preset_file (char * filename, size_t filename_size, const char * preset_name, int is_path, const char * codec_name)
Get a file corresponding to a preset file.
If is_path is non-zero, look for the file in the path preset_name. Otherwise search for a file named arg.ffpreset in the directories $FFMPEG_DATADIR (if set), $HOME/.ffmpeg, and in the datadir defined at configuration time or in a "ffpresets" folder along the executable on win32, in that order. If no such file is found and codec_name is defined, then search for a file named codec_name-preset_name.avpreset in the above-mentioned directories.
Parameters
filename buffer where the name of the found filename is written
filename_size size in bytes of the filename buffer
preset_name name of the preset to search
is_path tell if preset_name is a filename path
codec_name name of the codec for which to look for the preset, may be NULL
Definition at line 2042 of file cmdutils.c.
Referenced by ffserver_opt_preset(), and opt_preset().
grow_array()
void* grow_array (void * array, int elem_size, int * size, int new_size)
Realloc array to hold new_size elements of elem_size.
Calls exit() on failure.
Parameters
array array to reallocate
elem_size size in bytes of each element
size new element count will be written here
new_size number of elements to place in reallocated array
Returns
reallocated array
Definition at line 2179 of file cmdutils.c.
Referenced by opt_streamid(), and write_option().
get_rotation()
double get_rotation (AVStream * st)
Definition at line 2198 of file cmdutils.c.
Referenced by configure_input_video_filter(), and get_video_frame().
Variable Documentation
program_name
const char program_name[]
program name, defined by the program for show_version().
Definition at line 109 of file ffmpeg.c.
Referenced by compute_status(), expand_filename_template(), init_report(), main(), print_program_info(), show_help_default(), show_license(), and show_usage().
program_birth_year
const int program_birth_year
program birth year, defined by the program for show_banner()
Definition at line 110 of file ffmpeg.c.
Referenced by ffprobe_show_program_version(), and print_program_info().
avcodec_opts
AVCodecContext* avcodec_opts[AVMEDIA_TYPE_NB]
avformat_opts
AVFormatContext* avformat_opts
sws_dict
AVDictionary* sws_dict
Definition at line 70 of file cmdutils.c.
Referenced by finish_group(), and get_video_frame().
swr_opts
AVDictionary* swr_opts
Definition at line 71 of file cmdutils.c.
Referenced by finish_group(), and get_video_frame().
format_opts
AVDictionary* format_opts
Definition at line 72 of file cmdutils.c.
Referenced by finish_group(), main(), open_input_file(), opt_default_new(), opt_target(), and read_thread().
codec_opts
AVDictionary * codec_opts
Definition at line 72 of file cmdutils.c.
Referenced by finish_group(), open_input_file(), opt_default_new(), opt_target(), read_thread(), and stream_component_open().
resample_opts
AVDictionary * resample_opts
Definition at line 72 of file cmdutils.c.
Referenced by finish_group().
hide_banner
int hide_banner
Definition at line 76 of file cmdutils.c.
Referenced by parse_loglevel(), and show_banner().