FFmpeg: libavfilter/colorspacedsp.c File Reference
colorspacedsp.c File Reference
#include "colorspacedsp.h"
#include "colorspacedsp_template.c"
Macros
#define SS_W 0
#define SS_H 0
#define BIT_DEPTH 8
#define BIT_DEPTH 10
#define BIT_DEPTH 12
#define SS_W 1
#define SS_H 0
#define BIT_DEPTH 8
#define BIT_DEPTH 10
#define BIT_DEPTH 12
#define SS_W 1
#define SS_H 1
#define BIT_DEPTH 8
#define BIT_DEPTH 10
#define BIT_DEPTH 12
#define init_yuv2rgb_fn(bit)
#define init_rgb2yuv_fn(bit)
#define init_rgb2yuv_fsb_fn(bit)
#define init_yuv2yuv_fn(idx1, bit1, bit2)
#define init_yuv2yuv_fns(bit1)
Functions
static void multiply3x3_c (int16_t *buf[3], ptrdiff_t stride, int w, int h, const int16_t m[3][3][8])
void ff_colorspacedsp_init (ColorSpaceDSPContext *dsp)
Macro Definition Documentation
SS_W [1/3]
#define SS_W 0
Definition at line 62 of file colorspacedsp.c.
Referenced by rgb2yuv(), rgb2yuv_fsb(), yuv2rgb(), and yuv2yuv().
SS_H [1/3]
#define SS_H 0
Definition at line 63 of file colorspacedsp.c.
Referenced by rgb2yuv(), rgb2yuv_fsb(), yuv2rgb(), and yuv2yuv().
BIT_DEPTH [1/9]
#define BIT_DEPTH 8
Definition at line 74 of file colorspacedsp.c.
BIT_DEPTH [2/9]
#define BIT_DEPTH 10
Definition at line 74 of file colorspacedsp.c.
BIT_DEPTH [3/9]
#define BIT_DEPTH 12
Definition at line 74 of file colorspacedsp.c.
SS_W [2/3]
#define SS_W 1
Definition at line 62 of file colorspacedsp.c.
SS_H [2/3]
#define SS_H 0
Definition at line 63 of file colorspacedsp.c.
BIT_DEPTH [4/9]
#define BIT_DEPTH 8
Definition at line 74 of file colorspacedsp.c.
BIT_DEPTH [5/9]
#define BIT_DEPTH 10
Definition at line 74 of file colorspacedsp.c.
BIT_DEPTH [6/9]
#define BIT_DEPTH 12
Definition at line 74 of file colorspacedsp.c.
SS_W [3/3]
#define SS_W 1
Definition at line 62 of file colorspacedsp.c.
SS_H [3/3]
#define SS_H 1
Definition at line 63 of file colorspacedsp.c.
BIT_DEPTH [7/9]
#define BIT_DEPTH 8
Definition at line 74 of file colorspacedsp.c.
BIT_DEPTH [8/9]
#define BIT_DEPTH 10
Definition at line 74 of file colorspacedsp.c.
BIT_DEPTH [9/9]
#define BIT_DEPTH 12
Definition at line 74 of file colorspacedsp.c.
init_yuv2rgb_fn
#define init_yuv2rgb_fn (bit)
Value:
dsp->yuv2rgb[BPP_##bit][SS_444] = yuv2rgb_444p##bit##_c; \
    dsp->yuv2rgb[BPP_##bit][SS_422] = yuv2rgb_422p##bit##_c; \
    dsp->yuv2rgb[BPP_##bit][SS_420] = yuv2rgb_420p##bit##_c
Referenced by ff_colorspacedsp_init().
init_rgb2yuv_fn
#define init_rgb2yuv_fn (bit)
Value:
dsp->rgb2yuv[BPP_##bit][SS_444] = rgb2yuv_444p##bit##_c; \
    dsp->rgb2yuv[BPP_##bit][SS_422] = rgb2yuv_422p##bit##_c; \
    dsp->rgb2yuv[BPP_##bit][SS_420] = rgb2yuv_420p##bit##_c
Referenced by ff_colorspacedsp_init().
init_rgb2yuv_fsb_fn
#define init_rgb2yuv_fsb_fn (bit)
Value:
dsp->rgb2yuv_fsb[BPP_##bit][SS_444] = rgb2yuv_fsb_444p##bit##_c; \
    dsp->rgb2yuv_fsb[BPP_##bit][SS_422] = rgb2yuv_fsb_422p##bit##_c; \
    dsp->rgb2yuv_fsb[BPP_##bit][SS_420] = rgb2yuv_fsb_420p##bit##_c
Referenced by ff_colorspacedsp_init().
init_yuv2yuv_fn
#define init_yuv2yuv_fn (idx1, bit1, bit2)
Value:
dsp->yuv2yuv[idx1][BPP_##bit2][SS_444] = yuv2yuv_444p##bit1##to##bit2##_c; \
    dsp->yuv2yuv[idx1][BPP_##bit2][SS_422] = yuv2yuv_422p##bit1##to##bit2##_c; \
    dsp->yuv2yuv[idx1][BPP_##bit2][SS_420] = yuv2yuv_420p##bit1##to##bit2##_c
init_yuv2yuv_fns
#define init_yuv2yuv_fns (bit1)
Value:
init_yuv2yuv_fn(BPP_##bit1, bit1,  8); \
    init_yuv2yuv_fn(BPP_##bit1, bit1, 10); \
    init_yuv2yuv_fn(BPP_##bit1, bit1, 12)
Referenced by ff_colorspacedsp_init().
Function Documentation
multiply3x3_c()
static void multiply3x3_c (int16_t * buf[3], ptrdiff_t stride, int w, int h, const int16_t m[3][3][8]) static
Definition at line 77 of file colorspacedsp.c.
Referenced by ff_colorspacedsp_init().
ff_colorspacedsp_init()
void ff_colorspacedsp_init (ColorSpaceDSPContext * dsp)
Definition at line 101 of file colorspacedsp.c.
Referenced by check_multiply3x3(), check_rgb2yuv(), check_yuv2rgb(), check_yuv2yuv(), and init().