FFmpeg: libavfilter/colorspacedsp.h File Reference
colorspacedsp.h File Reference
#include <stddef.h>
#include <stdint.h>
Data Structures
struct ColorSpaceDSPContext
Typedefs
typedef void(* yuv2rgb_fn) (int16_t *rgb[3], ptrdiff_t rgb_stride, uint8_t *yuv[3], const ptrdiff_t yuv_stride[3], int w, int h, const int16_t yuv2rgb_coeffs[3][3][8], const int16_t yuv_offset[8])
typedef void(* rgb2yuv_fn) (uint8_t *yuv[3], const ptrdiff_t yuv_stride[3], int16_t *rgb[3], ptrdiff_t rgb_stride, int w, int h, const int16_t rgb2yuv_coeffs[3][3][8], const int16_t yuv_offset[8])
typedef void(* rgb2yuv_fsb_fn) (uint8_t *yuv[3], const ptrdiff_t yuv_stride[3], int16_t *rgb[3], ptrdiff_t rgb_stride, int w, int h, const int16_t rgb2yuv_coeffs[3][3][8], const int16_t yuv_offset[8], int *rnd[3][2])
typedef void(* yuv2yuv_fn) (uint8_t *yuv_out[3], const ptrdiff_t yuv_out_stride[3], uint8_t *yuv_in[3], const ptrdiff_t yuv_in_stride[3], int w, int h, const int16_t yuv2yuv_coeffs[3][3][8], const int16_t yuv_offset[2][8])
Enumerations
enum BitDepthIndex { BPP_8, BPP_10, BPP_12, NB_BPP }
enum ChromaSubsamplingIndex { SS_444, SS_422, SS_420, NB_SS }
Functions
void ff_colorspacedsp_init (ColorSpaceDSPContext *dsp)
void ff_colorspacedsp_x86_init (ColorSpaceDSPContext *dsp)
Typedef Documentation
yuv2rgb_fn
typedef void(* yuv2rgb_fn) (int16_t *rgb[3], ptrdiff_t rgb_stride, uint8_t *yuv[3], const ptrdiff_t yuv_stride[3], int w, int h, const int16_t yuv2rgb_coeffs[3][3][8], const int16_t yuv_offset[8])
Definition at line 27 of file colorspacedsp.h.
rgb2yuv_fn
typedef void(* rgb2yuv_fn) (uint8_t *yuv[3], const ptrdiff_t yuv_stride[3], int16_t *rgb[3], ptrdiff_t rgb_stride, int w, int h, const int16_t rgb2yuv_coeffs[3][3][8], const int16_t yuv_offset[8])
Definition at line 31 of file colorspacedsp.h.
rgb2yuv_fsb_fn
typedef void(* rgb2yuv_fsb_fn) (uint8_t *yuv[3], const ptrdiff_t yuv_stride[3], int16_t *rgb[3], ptrdiff_t rgb_stride, int w, int h, const int16_t rgb2yuv_coeffs[3][3][8], const int16_t yuv_offset[8], int *rnd[3][2])
Definition at line 35 of file colorspacedsp.h.
yuv2yuv_fn
typedef void(* yuv2yuv_fn) (uint8_t *yuv_out[3], const ptrdiff_t yuv_out_stride[3], uint8_t *yuv_in[3], const ptrdiff_t yuv_in_stride[3], int w, int h, const int16_t yuv2yuv_coeffs[3][3][8], const int16_t yuv_offset[2][8])
Definition at line 40 of file colorspacedsp.h.
Enumeration Type Documentation
BitDepthIndex
enum BitDepthIndex
Enumerator
BPP_8
BPP_10
BPP_12
NB_BPP
Definition at line 45 of file colorspacedsp.h.
ChromaSubsamplingIndex
enum ChromaSubsamplingIndex
Enumerator
SS_444
SS_422
SS_420
NB_SS
Definition at line 52 of file colorspacedsp.h.
Function Documentation
ff_colorspacedsp_init()
void ff_colorspacedsp_init (ColorSpaceDSPContext * dsp)
Definition at line 101 of file colorspacedsp.c.
Referenced by check_multiply3x3(), check_rgb2yuv(), check_yuv2rgb(), check_yuv2yuv(), and init().
ff_colorspacedsp_x86_init()
void ff_colorspacedsp_x86_init (ColorSpaceDSPContext * dsp)
Definition at line 79 of file colorspacedsp_init.c.
Referenced by ff_colorspacedsp_init().