FFmpeg: libavformat/concatdec.c File Reference
concatdec.c File Reference
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/opt.h"
#include "libavutil/parseutils.h"
#include "libavutil/timestamp.h"
#include "avformat.h"
#include "internal.h"
#include "url.h"
Data Structures
struct ConcatStream
struct ConcatFile
struct ConcatContext
Macros
#define FAIL(retcode) do { ret = (retcode); goto fail; } while(0)
#define OFFSET(x) offsetof(ConcatContext, x)
#define DEC AV_OPT_FLAG_DECODING_PARAM
Enumerations
enum ConcatMatchMode { MATCH_ONE_TO_ONE, MATCH_EXACT_ID }
Functions
static int concat_probe (AVProbeData *probe)
static char * get_keyword (uint8_t **cursor)
static int safe_filename (const char *f)
static int add_file (AVFormatContext *avf, char *filename, ConcatFile **rfile, unsigned *nb_files_alloc)
static int copy_stream_props (AVStream *st, AVStream *source_st)
static int detect_stream_specific (AVFormatContext *avf, int idx)
static int match_streams_one_to_one (AVFormatContext *avf)
static int match_streams_exact_id (AVFormatContext *avf)
static int match_streams (AVFormatContext *avf)
static int open_file (AVFormatContext *avf, unsigned fileno)
static int concat_read_close (AVFormatContext *avf)
static int concat_read_header (AVFormatContext *avf)
static int open_next_file (AVFormatContext *avf)
static int filter_packet (AVFormatContext *avf, ConcatStream *cs, AVPacket *pkt)
static int packet_after_outpoint (ConcatContext *cat, AVPacket *pkt)
static int concat_read_packet (AVFormatContext *avf, AVPacket *pkt)
static void rescale_interval (AVRational tb_in, AVRational tb_out, int64_t *min_ts, int64_t *ts, int64_t *max_ts)
static int try_seek (AVFormatContext *avf, int stream, int64_t min_ts, int64_t ts, int64_t max_ts, int flags)
static int real_seek (AVFormatContext *avf, int stream, int64_t min_ts, int64_t ts, int64_t max_ts, int flags, AVFormatContext *cur_avf)
static int concat_seek (AVFormatContext *avf, int stream, int64_t min_ts, int64_t ts, int64_t max_ts, int flags)
Variables
static const AVOption options []
static const AVClass concat_class
AVInputFormat ff_concat_demuxer
Macro Definition Documentation
FAIL
#define FAIL (retcode) do { ret = (retcode); goto fail; } while(0)
Definition at line 105 of file concatdec.c.
Referenced by add_file(), and concat_read_header().
OFFSET
#define OFFSET (x) offsetof(ConcatContext, x)
Definition at line 763 of file concatdec.c.
DEC
#define DEC AV_OPT_FLAG_DECODING_PARAM
Definition at line 764 of file concatdec.c.
Enumeration Type Documentation
ConcatMatchMode
enum ConcatMatchMode
Enumerator
MATCH_ONE_TO_ONE
MATCH_EXACT_ID
Definition at line 31 of file concatdec.c.
Function Documentation
concat_probe()
static int concat_probe (AVProbeData * probe) static
Definition at line 69 of file concatdec.c.
get_keyword()
static char* get_keyword (uint8_t ** cursor) static
Definition at line 75 of file concatdec.c.
Referenced by concat_read_header().
safe_filename()
static int safe_filename (const char * f) static
Definition at line 86 of file concatdec.c.
Referenced by add_file().
add_file()
static int add_file (AVFormatContext * avf, char * filename, ConcatFile ** rfile, unsigned * nb_files_alloc) static
Definition at line 107 of file concatdec.c.
Referenced by concat_read_header().
copy_stream_props()
static int copy_stream_props (AVStream * st, AVStream * source_st) static
Definition at line 164 of file concatdec.c.
Referenced by match_streams_exact_id(), and match_streams_one_to_one().
detect_stream_specific()
static int detect_stream_specific (AVFormatContext * avf, int idx) static
Definition at line 194 of file concatdec.c.
Referenced by match_streams().
match_streams_one_to_one()
static int match_streams_one_to_one (AVFormatContext * avf) static
Definition at line 233 of file concatdec.c.
Referenced by match_streams().
match_streams_exact_id()
static int match_streams_exact_id (AVFormatContext * avf) static
Definition at line 253 of file concatdec.c.
Referenced by match_streams().
match_streams()
static int match_streams (AVFormatContext * avf) static
Definition at line 275 of file concatdec.c.
Referenced by concat_read_packet(), and open_file().
open_file()
static int open_file (AVFormatContext * avf, unsigned fileno) static
Definition at line 312 of file concatdec.c.
Referenced by concat_read_header(), open_files(), open_next_file(), and real_seek().
concat_read_close()
static int concat_read_close (AVFormatContext * avf) static
Definition at line 361 of file concatdec.c.
Referenced by concat_read_header().
concat_read_header()
static int concat_read_header (AVFormatContext * avf) static
Definition at line 383 of file concatdec.c.
open_next_file()
static int open_next_file (AVFormatContext * avf) static
Definition at line 506 of file concatdec.c.
Referenced by concat_read_packet().
filter_packet()
static int filter_packet (AVFormatContext * avf, ConcatStream * cs, AVPacket * pkt) static
Definition at line 521 of file concatdec.c.
Referenced by concat_read_packet(), crystalhd_decode_packet(), and cuvid_decode_packet().
packet_after_outpoint()
static int packet_after_outpoint (ConcatContext * cat, AVPacket * pkt) static
Definition at line 578 of file concatdec.c.
Referenced by concat_read_packet().
concat_read_packet()
static int concat_read_packet (AVFormatContext * avf, AVPacket * pkt) static
Definition at line 587 of file concatdec.c.
rescale_interval()
static void rescale_interval (AVRational tb_in, AVRational tb_out, int64_t * min_ts, int64_t * ts, int64_t * max_ts) static
Definition at line 663 of file concatdec.c.
Referenced by real_seek(), and try_seek().
try_seek()
static int try_seek (AVFormatContext * avf, int stream, int64_t min_ts, int64_t ts, int64_t max_ts, int flags) static
Definition at line 673 of file concatdec.c.
Referenced by real_seek().
real_seek()
static int real_seek (AVFormatContext * avf, int stream, int64_t min_ts, int64_t ts, int64_t max_ts, int flags, AVFormatContext * cur_avf) static
Definition at line 691 of file concatdec.c.
Referenced by concat_seek().
concat_seek()
static int concat_seek (AVFormatContext * avf, int stream, int64_t min_ts, int64_t ts, int64_t max_ts, int flags) static
Definition at line 734 of file concatdec.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "safe", "enable safe mode",
      OFFSET(safe), AV_OPT_TYPE_BOOL, {.i64 = 1}, -1, 1, DEC },
    { "auto_convert", "automatically convert bitstream format",
      OFFSET(auto_convert), AV_OPT_TYPE_BOOL, {.i64 = 1}, 0, 1, DEC },
    { "segment_time_metadata", "output file segment start time and duration as packet metadata",
      OFFSET(segment_time_metadata), AV_OPT_TYPE_BOOL, {.i64 = 0}, 0, 1, DEC },
    { NULL }
}
Definition at line 766 of file concatdec.c.
concat_class
const AVClass concat_class static
Initial value:
= {
    .class_name = "concat demuxer",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 776 of file concatdec.c.
ff_concat_demuxer
AVInputFormat ff_concat_demuxer
Initial value:
= {
    .name           = "concat",
    .long_name      = NULL_IF_CONFIG_SMALL("Virtual concatenation script"),
    .priv_data_size = sizeof(ConcatContext),
    .read_probe     = concat_probe,
    .read_header    = concat_read_header,
    .read_packet    = concat_read_packet,
    .read_close     = concat_read_close,
    .read_seek2     = concat_seek,
    .priv_class     = &concat_class,
}
Definition at line 784 of file concatdec.c.