FFmpeg: libavcodec/copy_block.h File Reference
copy_block.h File Reference
#include <stdint.h>
#include "libavutil/intreadwrite.h"
Functions
static void copy_block2 (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride, int h)
static void copy_block4 (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride, int h)
static void copy_block8 (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride, int h)
static void copy_block9 (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride, int h)
static void copy_block16 (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride, int h)
static void copy_block17 (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride, int h)
Function Documentation
copy_block2()
static void copy_block2 (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride, int h) inline static
Definition at line 26 of file copy_block.h.
Referenced by mjpeg_copy_block().
copy_block4()
static void copy_block4 (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride, int h) inline static
Definition at line 37 of file copy_block.h.
Referenced by copy_block(), decode_0(), mjpeg_copy_block(), and old_codec37().
copy_block8()
static void copy_block8 (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride, int h) inline static
Definition at line 47 of file copy_block.h.
Referenced by copy_block(), and rd8x8_c().
copy_block9()
static void copy_block9 (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride, int h) inline static
Definition at line 57 of file copy_block.h.
copy_block16()
static void copy_block16 (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride, int h) inline static
Definition at line 68 of file copy_block.h.
Referenced by copy_block().
copy_block17()
static void copy_block17 (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride, int h) inline static
Definition at line 78 of file copy_block.h.