FFmpeg: libavutil/cpu_internal.h File Reference
cpu_internal.h File Reference
#include "cpu.h"
Macros
#define CPUEXT_SUFFIX(flags, suffix, cpuext) (HAVE_ ## cpuext ## suffix && ((flags) & AV_CPU_FLAG_ ## cpuext))
#define CPUEXT_SUFFIX_FAST2(flags, suffix, cpuext, slow_cpuext)
#define CPUEXT_SUFFIX_SLOW2(flags, suffix, cpuext, slow_cpuext)
#define CPUEXT_SUFFIX_FAST(flags, suffix, cpuext) CPUEXT_SUFFIX_FAST2(flags, suffix, cpuext, cpuext)
#define CPUEXT_SUFFIX_SLOW(flags, suffix, cpuext) CPUEXT_SUFFIX_SLOW2(flags, suffix, cpuext, cpuext)
#define CPUEXT(flags, cpuext) CPUEXT_SUFFIX(flags, , cpuext)
#define CPUEXT_FAST(flags, cpuext) CPUEXT_SUFFIX_FAST(flags, , cpuext)
#define CPUEXT_SLOW(flags, cpuext) CPUEXT_SUFFIX_SLOW(flags, , cpuext)
Functions
int ff_get_cpu_flags_aarch64 (void)
int ff_get_cpu_flags_arm (void)
int ff_get_cpu_flags_ppc (void)
This function MAY rely on signal() or fork() in order to make sure AltiVec is present.
int ff_get_cpu_flags_x86 (void)
Macro Definition Documentation
CPUEXT_SUFFIX
#define CPUEXT_SUFFIX (flags, suffix, cpuext) (HAVE_ ## cpuext ## suffix && ((flags) & AV_CPU_FLAG_ ## cpuext))
Definition at line 24 of file cpu_internal.h.
CPUEXT_SUFFIX_FAST2
#define CPUEXT_SUFFIX_FAST2 (flags, suffix, cpuext, slow_cpuext)
Value:
(HAVE_ ## cpuext ## suffix && ((flags) & AV_CPU_FLAG_ ## cpuext) && \
     !((flags) & AV_CPU_FLAG_ ## slow_cpuext ## SLOW))
Definition at line 27 of file cpu_internal.h.
CPUEXT_SUFFIX_SLOW2
#define CPUEXT_SUFFIX_SLOW2 (flags, suffix, cpuext, slow_cpuext)
Value:
(HAVE_ ## cpuext ## suffix && ((flags) & AV_CPU_FLAG_ ## cpuext) && \
     ((flags) & AV_CPU_FLAG_ ## slow_cpuext ## SLOW))
Definition at line 31 of file cpu_internal.h.
CPUEXT_SUFFIX_FAST
#define CPUEXT_SUFFIX_FAST (flags, suffix, cpuext) CPUEXT_SUFFIX_FAST2(flags, suffix, cpuext, cpuext)
Definition at line 35 of file cpu_internal.h.
CPUEXT_SUFFIX_SLOW
#define CPUEXT_SUFFIX_SLOW (flags, suffix, cpuext) CPUEXT_SUFFIX_SLOW2(flags, suffix, cpuext, cpuext)
Definition at line 36 of file cpu_internal.h.
CPUEXT
#define CPUEXT (flags, cpuext) CPUEXT_SUFFIX(flags, , cpuext)
Definition at line 38 of file cpu_internal.h.
CPUEXT_FAST
#define CPUEXT_FAST (flags, cpuext) CPUEXT_SUFFIX_FAST(flags, , cpuext)
Definition at line 39 of file cpu_internal.h.
CPUEXT_SLOW
#define CPUEXT_SLOW (flags, cpuext) CPUEXT_SUFFIX_SLOW(flags, , cpuext)
Definition at line 40 of file cpu_internal.h.
Function Documentation
ff_get_cpu_flags_aarch64()
int ff_get_cpu_flags_aarch64 (void)
Definition at line 23 of file cpu.c.
Referenced by get_cpu_flags().
ff_get_cpu_flags_arm()
int ff_get_cpu_flags_arm (void)
Definition at line 149 of file cpu.c.
Referenced by get_cpu_flags().
ff_get_cpu_flags_ppc()
int ff_get_cpu_flags_ppc (void)
This function MAY rely on signal() or fork() in order to make sure AltiVec is present.
Definition at line 48 of file cpu.c.
Referenced by get_cpu_flags().
ff_get_cpu_flags_x86()
int ff_get_cpu_flags_x86 (void)
Definition at line 90 of file cpu.c.
Referenced by get_cpu_flags().