FFmpeg: tools/crypto_bench.c File Reference
crypto_bench.c File Reference
#include <stdlib.h>
#include <math.h>
#include "libavutil/avutil.h"
#include "libavutil/avstring.h"
#include "libavutil/crc.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/timer.h"
#include "compat/getopt.c"
#include "libavutil/md5.h"
#include "libavutil/sha.h"
#include "libavutil/sha512.h"
#include "libavutil/ripemd.h"
#include "libavutil/aes.h"
#include "libavutil/blowfish.h"
#include "libavutil/camellia.h"
#include "libavutil/cast5.h"
#include "libavutil/des.h"
#include "libavutil/twofish.h"
#include "libavutil/rc4.h"
#include "libavutil/xtea.h"
Data Structures
struct hash_impl
Macros
#define USE_crypto 0x01 /* OpenSSL's libcrypto */
#define USE_gcrypt 0x02 /* GnuTLS's libgcrypt */
#define USE_tomcrypt 0x04 /* LibTomCrypt */
#define AV_READ_TIME(x) 0
#define MAX_INPUT_SIZE 1048576
#define MAX_OUTPUT_SIZE 128
#define IMPL_USE_lavu IMPL_USE
#define DEFINE_LAVU_MD(suffix, type, namespace, hsize)
#define IMPL_USE_crypto(...) /* ignore */
#define IMPL_USE_gcrypt(...) /* ignore */
#define IMPL_USE_tomcrypt(...) /* ignore */
#define IMPL_USE(lib, name, symbol, output) { #lib, name, run_ ## lib ## _ ## symbol, output },
#define IMPL(lib, ...) IMPL_USE_ ## lib(lib, __VA_ARGS__)
#define IMPL_ALL(...)
Functions
static void fatal_error (const char *tag)
static void run_lavu_md5 (uint8_t *output, const uint8_t *input, unsigned size)
DEFINE_LAVU_MD (sha1, AVSHA, sha, 160)
DEFINE_LAVU_MD (sha256, AVSHA, sha, 256)
DEFINE_LAVU_MD (sha512, AVSHA512, sha512, 512)
DEFINE_LAVU_MD (ripemd128, AVRIPEMD, ripemd, 128)
DEFINE_LAVU_MD (ripemd160, AVRIPEMD, ripemd, 160)
static void run_lavu_aes128 (uint8_t *output, const uint8_t *input, unsigned size)
static void run_lavu_blowfish (uint8_t *output, const uint8_t *input, unsigned size)
static void run_lavu_camellia (uint8_t *output, const uint8_t *input, unsigned size)
static void run_lavu_cast128 (uint8_t *output, const uint8_t *input, unsigned size)
static void run_lavu_des (uint8_t *output, const uint8_t *input, unsigned size)
static void run_lavu_twofish (uint8_t *output, const uint8_t *input, unsigned size)
static void run_lavu_rc4 (uint8_t *output, const uint8_t *input, unsigned size)
static void run_lavu_xtea (uint8_t *output, const uint8_t *input, unsigned size)
static unsigned crc32 (const uint8_t *data, unsigned size)
static void run_implementation (const uint8_t *input, uint8_t *output, struct hash_impl *impl, unsigned size)
int main (int argc, char **argv)
Variables
static const char * enabled_libs
static const char * enabled_algos
static unsigned specified_runs
static const uint8_t * hardcoded_key = "FFmpeg is the best program ever."
struct hash_impl implementations []
Macro Definition Documentation
USE_crypto
#define USE_crypto 0x01 /* OpenSSL's libcrypto */
Definition at line 23 of file crypto_bench.c.
Referenced by main().
USE_gcrypt
#define USE_gcrypt 0x02 /* GnuTLS's libgcrypt */
Definition at line 24 of file crypto_bench.c.
Referenced by main().
USE_tomcrypt
#define USE_tomcrypt 0x04 /* LibTomCrypt */
Definition at line 25 of file crypto_bench.c.
Referenced by main().
AV_READ_TIME
#define AV_READ_TIME (x) 0
Definition at line 37 of file crypto_bench.c.
Referenced by run_implementation().
MAX_INPUT_SIZE
#define MAX_INPUT_SIZE 1048576
Definition at line 47 of file crypto_bench.c.
Referenced by main().
MAX_OUTPUT_SIZE
#define MAX_OUTPUT_SIZE 128
Definition at line 48 of file crypto_bench.c.
Referenced by run_implementation().
IMPL_USE_lavu
#define IMPL_USE_lavu IMPL_USE
Definition at line 86 of file crypto_bench.c.
DEFINE_LAVU_MD
#define DEFINE_LAVU_MD (suffix, type, namespace, hsize)
Value:
static void run_lavu_ ## suffix(uint8_t *output,                             \
                                const uint8_t *input, unsigned size)         \
{                                                                            \
    static struct type *h;                                                   \
    if (!h && !(h = av_ ## namespace ## _alloc()))                           \
        fatal_error("out of memory");                                        \
    av_ ## namespace ## _init(h, hsize);                                     \
    av_ ## namespace ## _update(h, input, size);                             \
    av_ ## namespace ## _final(h, output);                                   \
}
Definition at line 94 of file crypto_bench.c.
IMPL_USE_crypto
#define IMPL_USE_crypto (...) /* ignore */
Definition at line 290 of file crypto_bench.c.
IMPL_USE_gcrypt
#define IMPL_USE_gcrypt (...) /* ignore */
Definition at line 334 of file crypto_bench.c.
IMPL_USE_tomcrypt
#define IMPL_USE_tomcrypt (...) /* ignore */
Definition at line 445 of file crypto_bench.c.
IMPL_USE
#define IMPL_USE (lib, name, symbol, output) { #lib, name, run_ ## lib ## _ ## symbol, output },
Definition at line 508 of file crypto_bench.c.
IMPL
#define IMPL (lib, ...) IMPL_USE_ ## lib(lib, __VA_ARGS__)
Definition at line 510 of file crypto_bench.c.
IMPL_ALL
#define IMPL_ALL (...)
Value:
IMPL(lavu,       __VA_ARGS__) \
    IMPL(crypto,     __VA_ARGS__) \
    IMPL(gcrypt,     __VA_ARGS__) \
    IMPL(tomcrypt,   __VA_ARGS__)
Definition at line 511 of file crypto_bench.c.
Function Documentation
fatal_error()
static void fatal_error (const char * tag) static
Definition at line 56 of file crypto_bench.c.
Referenced by main(), run_implementation(), run_lavu_aes128(), run_lavu_blowfish(), run_lavu_camellia(), run_lavu_cast128(), run_lavu_des(), run_lavu_rc4(), run_lavu_twofish(), and run_lavu_xtea().
run_lavu_md5()
static void run_lavu_md5 (uint8_t * output, const uint8_t * input, unsigned size) static
Definition at line 88 of file crypto_bench.c.
DEFINE_LAVU_MD() [1/5]
DEFINE_LAVU_MD (sha1 , AVSHA , sha , 160)
DEFINE_LAVU_MD() [2/5]
DEFINE_LAVU_MD (sha256 , AVSHA , sha , 256)
DEFINE_LAVU_MD() [3/5]
DEFINE_LAVU_MD (sha512 , AVSHA512 , sha512 , 512)
DEFINE_LAVU_MD() [4/5]
DEFINE_LAVU_MD (ripemd128 , AVRIPEMD , ripemd , 128)
DEFINE_LAVU_MD() [5/5]
DEFINE_LAVU_MD (ripemd160 , AVRIPEMD , ripemd , 160)
run_lavu_aes128()
static void run_lavu_aes128 (uint8_t * output, const uint8_t * input, unsigned size) static
Definition at line 112 of file crypto_bench.c.
run_lavu_blowfish()
static void run_lavu_blowfish (uint8_t * output, const uint8_t * input, unsigned size) static
Definition at line 122 of file crypto_bench.c.
run_lavu_camellia()
static void run_lavu_camellia (uint8_t * output, const uint8_t * input, unsigned size) static
Definition at line 132 of file crypto_bench.c.
run_lavu_cast128()
static void run_lavu_cast128 (uint8_t * output, const uint8_t * input, unsigned size) static
Definition at line 142 of file crypto_bench.c.
run_lavu_des()
static void run_lavu_des (uint8_t * output, const uint8_t * input, unsigned size) static
Definition at line 152 of file crypto_bench.c.
run_lavu_twofish()
static void run_lavu_twofish (uint8_t * output, const uint8_t * input, unsigned size) static
Definition at line 162 of file crypto_bench.c.
run_lavu_rc4()
static void run_lavu_rc4 (uint8_t * output, const uint8_t * input, unsigned size) static
Definition at line 172 of file crypto_bench.c.
run_lavu_xtea()
static void run_lavu_xtea (uint8_t * output, const uint8_t * input, unsigned size) static
Definition at line 182 of file crypto_bench.c.
crc32()
static unsigned crc32 (const uint8_t * data, unsigned size) static
Definition at line 452 of file crypto_bench.c.
Referenced by run_implementation().
run_implementation()
static void run_implementation (const uint8_t * input, uint8_t * output, struct hash_impl * impl, unsigned size) static
Definition at line 457 of file crypto_bench.c.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 540 of file crypto_bench.c.
Variable Documentation
enabled_libs
const char* enabled_libs static
Definition at line 50 of file crypto_bench.c.
Referenced by main(), and run_implementation().
enabled_algos
const char* enabled_algos static
Definition at line 51 of file crypto_bench.c.
Referenced by main(), and run_implementation().
specified_runs
unsigned specified_runs static
Definition at line 52 of file crypto_bench.c.
Referenced by main(), and run_implementation().
hardcoded_key
const uint8_t* hardcoded_key = "FFmpeg is the best program ever." static
Definition at line 54 of file crypto_bench.c.
Referenced by run_lavu_aes128(), run_lavu_blowfish(), run_lavu_camellia(), run_lavu_cast128(), run_lavu_des(), run_lavu_rc4(), run_lavu_twofish(), and run_lavu_xtea().
implementations
struct hash_impl implementations[]
Initial value:
= {
    IMPL_ALL("SHA-512",    sha512,    "3afdd44a80d99af15c87bd724cb717243193767835ce866dd5d58c02d674bb57"
                                      "7c25b9e118c200a189fcd5a01ef106a4e200061f3e97dbf50ba065745fd46bef")
}
Definition at line 517 of file crypto_bench.c.