FFmpeg: libavcodec/crystalhd.c File Reference
crystalhd.c File Reference
#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <libcrystalhd/bc_dts_types.h>
#include <libcrystalhd/bc_dts_defs.h>
#include <libcrystalhd/libcrystalhd_if.h>
#include "avcodec.h"
#include "internal.h"
#include "libavutil/imgutils.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/opt.h"
Data Structures
struct OpaqueList
struct CHDContext
Macros
#define _XOPEN_SOURCE 600
#define OUTPUT_PROC_TIMEOUT 50
Timeout parameter passed to DtsProcOutput() in us.
#define TIMESTAMP_UNIT 100000
Step between fake timestamps passed to hardware in units of 100ns.
#define DEFINE_CRYSTALHD_DECODER(x, X)
Enumerations
enum CopyRet { RET_ERROR = -1, RET_OK = 0, RET_COPY_AGAIN = 1 }
Functions
static BC_MEDIA_SUBTYPE id2subtype (CHDContext *priv, enum AVCodecID id)
static void print_frame_info (CHDContext *priv, BC_DTS_PROC_OUT *output)
static uint64_t opaque_list_push (CHDContext *priv, uint64_t reordered_opaque)
static OpaqueList * opaque_list_pop (CHDContext *priv, uint64_t fake_timestamp)
static void flush (AVCodecContext *avctx)
static av_cold int uninit (AVCodecContext *avctx)
static av_cold int init_bsf (AVCodecContext *avctx, const char *bsf_name)
static av_cold int init (AVCodecContext *avctx)
static CopyRet copy_frame (AVCodecContext *avctx, BC_DTS_PROC_OUT *output, AVFrame *frame, int *got_frame)
static CopyRet receive_frame (AVCodecContext *avctx, AVFrame *frame, int *got_frame)
static int crystalhd_decode_packet (AVCodecContext *avctx, const AVPacket *avpkt)
static int crystalhd_receive_frame (AVCodecContext *avctx, AVFrame *frame)
Variables
static const AVOption options []
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 600
Definition at line 48 of file crystalhd.c.
OUTPUT_PROC_TIMEOUT
#define OUTPUT_PROC_TIMEOUT 50
Timeout parameter passed to DtsProcOutput() in us.
Definition at line 68 of file crystalhd.c.
Referenced by receive_frame().
TIMESTAMP_UNIT
#define TIMESTAMP_UNIT 100000
Step between fake timestamps passed to hardware in units of 100ns.
Definition at line 70 of file crystalhd.c.
Referenced by opaque_list_push().
DEFINE_CRYSTALHD_DECODER
#define DEFINE_CRYSTALHD_DECODER (x, X)
Value:
static const AVClass x##_crystalhd_class = { \
        .class_name = #x "_crystalhd", \
        .item_name = av_default_item_name, \
        .option = options, \
        .version = LIBAVUTIL_VERSION_INT, \
    }; \
    AVCodec ff_##x##_crystalhd_decoder = { \
        .name           = #x "_crystalhd", \
        .long_name      = NULL_IF_CONFIG_SMALL("CrystalHD " #X " decoder"), \
        .type           = AVMEDIA_TYPE_VIDEO, \
        .id             = AV_CODEC_ID_##X, \
        .priv_data_size = sizeof(CHDContext), \
        .priv_class     = &x##_crystalhd_class, \
        .init           = init, \
        .close          = uninit, \
        .send_packet    = crystalhd_decode_packet, \
        .receive_frame  = crystalhd_receive_frame, \
        .flush          = flush, \
        .capabilities   = AV_CODEC_CAP_DELAY | AV_CODEC_CAP_AVOID_PROBING, \
        .pix_fmts       = (const enum AVPixelFormat[]){AV_PIX_FMT_YUYV422, AV_PIX_FMT_NONE}, \
    };
Definition at line 894 of file crystalhd.c.
Enumeration Type Documentation
CopyRet
enum CopyRet
Enumerator
RET_ERROR
RET_OK
RET_COPY_AGAIN
Definition at line 77 of file crystalhd.c.
Function Documentation
id2subtype()
static BC_MEDIA_SUBTYPE id2subtype (CHDContext * priv, enum AVCodecID id) inline static
Definition at line 128 of file crystalhd.c.
Referenced by init().
print_frame_info()
static void print_frame_info (CHDContext * priv, BC_DTS_PROC_OUT * output) inline static
Definition at line 148 of file crystalhd.c.
Referenced by receive_frame().
opaque_list_push()
static uint64_t opaque_list_push (CHDContext * priv, uint64_t reordered_opaque) static
Definition at line 194 of file crystalhd.c.
Referenced by crystalhd_decode_packet().
opaque_list_pop()
static OpaqueList* opaque_list_pop (CHDContext * priv, uint64_t fake_timestamp) static
Definition at line 222 of file crystalhd.c.
Referenced by copy_frame().
flush()
static void flush (AVCodecContext * avctx) static
Definition at line 275 of file crystalhd.c.
uninit()
static av_cold int uninit (AVCodecContext * avctx) static
Definition at line 287 of file crystalhd.c.
Referenced by compressor(), config_output(), filter_frame(), gate(), init(), and process_command().
init_bsf()
static av_cold int init_bsf (AVCodecContext * avctx, const char * bsf_name) static
Definition at line 329 of file crystalhd.c.
Referenced by init().
init()
static av_cold int init (AVCodecContext * avctx) static
Definition at line 378 of file crystalhd.c.
copy_frame()
static CopyRet copy_frame (AVCodecContext * avctx, BC_DTS_PROC_OUT * output, AVFrame * frame, int * got_frame) inline static
Definition at line 510 of file crystalhd.c.
Referenced by receive_frame().
receive_frame()
static CopyRet receive_frame (AVCodecContext * avctx, AVFrame * frame, int * got_frame) inline static
Definition at line 650 of file crystalhd.c.
Referenced by crystalhd_receive_frame().
crystalhd_decode_packet()
static int crystalhd_decode_packet (AVCodecContext * avctx, const AVPacket * avpkt) static
Definition at line 755 of file crystalhd.c.
crystalhd_receive_frame()
static int crystalhd_receive_frame (AVCodecContext * avctx, AVFrame * frame) static
Definition at line 857 of file crystalhd.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "crystalhd_downscale_width",
      "Turn on downscaling to the specified width",
      0x42,
      AV_OPT_TYPE_INT, {.i64 = 0}, 0, UINT32_MAX,
      AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_DECODING_PARAM, },
    { NULL, },
}
Definition at line 114 of file crystalhd.c.