FFmpeg: libavcodec/cuvid.c File Reference
cuvid.c File Reference
#include "compat/cuda/dynlink_loader.h"
#include "libavutil/buffer.h"
#include "libavutil/mathematics.h"
#include "libavutil/hwcontext.h"
#include "libavutil/hwcontext_cuda_internal.h"
#include "libavutil/fifo.h"
#include "libavutil/log.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "avcodec.h"
#include "internal.h"
Data Structures
struct CuvidContext
struct CuvidParsedFrame
Macros
#define CHECK_CU(x) check_cu(avctx, (x), #x)
#define OFFSET(x) offsetof(CuvidContext, x)
#define VD AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_DECODING_PARAM
#define DEFINE_CUVID_CODEC(x, X)
Functions
static int check_cu (AVCodecContext *avctx, CUresult err, const char *func)
static int CUDAAPI cuvid_handle_video_sequence (void *opaque, CUVIDEOFORMAT *format)
static int CUDAAPI cuvid_handle_picture_decode (void *opaque, CUVIDPICPARAMS *picparams)
static int CUDAAPI cuvid_handle_picture_display (void *opaque, CUVIDPARSERDISPINFO *dispinfo)
static int cuvid_decode_packet (AVCodecContext *avctx, const AVPacket *avpkt)
static int cuvid_output_frame (AVCodecContext *avctx, AVFrame *frame)
static int cuvid_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int cuvid_decode_end (AVCodecContext *avctx)
static int cuvid_test_dummy_decoder (AVCodecContext *avctx, CUVIDPARSERPARAMS *cuparseinfo)
static av_cold int cuvid_decode_init (AVCodecContext *avctx)
static void cuvid_flush (AVCodecContext *avctx)
Variables
static const AVOption options []
Macro Definition Documentation
CHECK_CU
#define CHECK_CU (x) check_cu(avctx, (x), #x)
Definition at line 98 of file cuvid.c.
Referenced by cuvid_decode_init(), cuvid_handle_picture_decode(), cuvid_output_frame(), and cuvid_test_dummy_decoder().
OFFSET
#define OFFSET (x) offsetof(CuvidContext, x)
Definition at line 916 of file cuvid.c.
VD
#define VD AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_DECODING_PARAM
Definition at line 917 of file cuvid.c.
Referenced by decode_flush().
DEFINE_CUVID_CODEC
#define DEFINE_CUVID_CODEC (x, X)
Definition at line 928 of file cuvid.c.
Function Documentation
check_cu()
static int check_cu (AVCodecContext * avctx, CUresult err, const char * func) static
Definition at line 76 of file cuvid.c.
cuvid_handle_video_sequence()
static int CUDAAPI cuvid_handle_video_sequence (void * opaque, CUVIDEOFORMAT * format) static
Definition at line 100 of file cuvid.c.
Referenced by cuvid_decode_init().
cuvid_handle_picture_decode()
static int CUDAAPI cuvid_handle_picture_decode (void * opaque, CUVIDPICPARAMS * picparams) static
Definition at line 273 of file cuvid.c.
Referenced by cuvid_decode_init().
cuvid_handle_picture_display()
static int CUDAAPI cuvid_handle_picture_display (void * opaque, CUVIDPARSERDISPINFO * dispinfo) static
Definition at line 287 of file cuvid.c.
Referenced by cuvid_decode_init().
cuvid_decode_packet()
static int cuvid_decode_packet (AVCodecContext * avctx, const AVPacket * avpkt) static
Definition at line 308 of file cuvid.c.
Referenced by cuvid_decode_frame(), and cuvid_output_frame().
cuvid_output_frame()
static int cuvid_output_frame (AVCodecContext * avctx, AVFrame * frame) static
Definition at line 398 of file cuvid.c.
Referenced by cuvid_decode_frame().
cuvid_decode_frame()
static int cuvid_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 559 of file cuvid.c.
cuvid_decode_end()
static av_cold int cuvid_decode_end (AVCodecContext * avctx) static
Definition at line 590 of file cuvid.c.
Referenced by cuvid_decode_init().
cuvid_test_dummy_decoder()
static int cuvid_test_dummy_decoder (AVCodecContext * avctx, CUVIDPARSERPARAMS * cuparseinfo) static
Definition at line 615 of file cuvid.c.
Referenced by cuvid_decode_init().
cuvid_decode_init()
static av_cold int cuvid_decode_init (AVCodecContext * avctx) static
Definition at line 656 of file cuvid.c.
cuvid_flush()
static void cuvid_flush (AVCodecContext * avctx) static
Definition at line 860 of file cuvid.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "deint",    "Set deinterlacing mode", OFFSET(deint_mode), AV_OPT_TYPE_INT,   { .i64 = cudaVideoDeinterlaceMode_Weave    }, cudaVideoDeinterlaceMode_Weave, cudaVideoDeinterlaceMode_Adaptive, VD, "deint" },
    { "weave",    "Weave deinterlacing (do nothing)",        0, AV_OPT_TYPE_CONST, { .i64 = cudaVideoDeinterlaceMode_Weave    }, 0, 0, VD, "deint" },
    { "bob",      "Bob deinterlacing",                       0, AV_OPT_TYPE_CONST, { .i64 = cudaVideoDeinterlaceMode_Bob      }, 0, 0, VD, "deint" },
    { "adaptive", "Adaptive deinterlacing",                  0, AV_OPT_TYPE_CONST, { .i64 = cudaVideoDeinterlaceMode_Adaptive }, 0, 0, VD, "deint" },
    { "gpu",      "GPU to be used for decoding", OFFSET(cu_gpu), AV_OPT_TYPE_STRING, { .str = NULL }, 0, 0, VD },
    { "surfaces", "Maximum surfaces to be used for decoding", OFFSET(nb_surfaces), AV_OPT_TYPE_INT, { .i64 = 25 }, 0, INT_MAX, VD },
    { NULL }
}
Definition at line 918 of file cuvid.c.