FFmpeg: libavcodec/dca_exss.c File Reference
dca_exss.c File Reference
#include "dcadec.h"
Functions
static void parse_xll_parameters (DCAExssParser *s, DCAExssAsset *asset)
static void parse_lbr_parameters (DCAExssParser *s, DCAExssAsset *asset)
static int parse_descriptor (DCAExssParser *s, DCAExssAsset *asset)
static int set_exss_offsets (DCAExssAsset *asset)
int ff_dca_exss_parse (DCAExssParser *s, const uint8_t *data, int size)
Function Documentation
parse_xll_parameters()
static void parse_xll_parameters (DCAExssParser * s, DCAExssAsset * asset) static
Definition at line 23 of file dca_exss.c.
Referenced by parse_descriptor().
parse_lbr_parameters()
static void parse_lbr_parameters (DCAExssParser * s, DCAExssAsset * asset) static
Definition at line 49 of file dca_exss.c.
Referenced by parse_descriptor().
parse_descriptor()
static int parse_descriptor (DCAExssParser * s, DCAExssAsset * asset) static
Definition at line 60 of file dca_exss.c.
Referenced by ff_dca_exss_parse().
set_exss_offsets()
static int set_exss_offsets (DCAExssAsset * asset) static
Definition at line 322 of file dca_exss.c.
Referenced by ff_dca_exss_parse().
ff_dca_exss_parse()
int ff_dca_exss_parse (DCAExssParser * s, const uint8_t * data, int size)
Definition at line 378 of file dca_exss.c.
Referenced by dca_parse_params(), and dcadec_decode_frame().