FFmpeg: libavcodec/dcadsp.c File Reference
dcadsp.c File Reference
#include "libavutil/mem.h"
#include "dcadsp.h"
#include "dcamath.h"
Functions
static void decode_hf_c (int32_t **dst, const int32_t *vq_index, const int8_t hf_vq[1024][32], int32_t scale_factors[32][2], ptrdiff_t sb_start, ptrdiff_t sb_end, ptrdiff_t ofs, ptrdiff_t len)
static void decode_joint_c (int32_t **dst, int32_t **src, const int32_t *scale_factors, ptrdiff_t sb_start, ptrdiff_t sb_end, ptrdiff_t ofs, ptrdiff_t len)
static void lfe_fir_float_c (float *pcm_samples, int32_t *lfe_samples, const float *filter_coeff, ptrdiff_t npcmblocks, int dec_select)
static void lfe_fir0_float_c (float *pcm_samples, int32_t *lfe_samples, const float *filter_coeff, ptrdiff_t npcmblocks)
static void lfe_fir1_float_c (float *pcm_samples, int32_t *lfe_samples, const float *filter_coeff, ptrdiff_t npcmblocks)
static void lfe_x96_float_c (float *dst, const float *src, float *hist, ptrdiff_t len)
static void sub_qmf32_float_c (SynthFilterContext *synth, FFTContext *imdct, float *pcm_samples, int32_t **subband_samples_lo, int32_t **subband_samples_hi, float *hist1, int *offset, float *hist2, const float *filter_coeff, ptrdiff_t npcmblocks, float scale)
static void sub_qmf64_float_c (SynthFilterContext *synth, FFTContext *imdct, float *pcm_samples, int32_t **subband_samples_lo, int32_t **subband_samples_hi, float *hist1, int *offset, float *hist2, const float *filter_coeff, ptrdiff_t npcmblocks, float scale)
static void lfe_fir_fixed_c (int32_t *pcm_samples, int32_t *lfe_samples, const int32_t *filter_coeff, ptrdiff_t npcmblocks)
static void lfe_x96_fixed_c (int32_t *dst, const int32_t *src, int32_t *hist, ptrdiff_t len)
static void sub_qmf32_fixed_c (SynthFilterContext *synth, DCADCTContext *imdct, int32_t *pcm_samples, int32_t **subband_samples_lo, int32_t **subband_samples_hi, int32_t *hist1, int *offset, int32_t *hist2, const int32_t *filter_coeff, ptrdiff_t npcmblocks)
static void sub_qmf64_fixed_c (SynthFilterContext *synth, DCADCTContext *imdct, int32_t *pcm_samples, int32_t **subband_samples_lo, int32_t **subband_samples_hi, int32_t *hist1, int *offset, int32_t *hist2, const int32_t *filter_coeff, ptrdiff_t npcmblocks)
static void decor_c (int32_t *dst, const int32_t *src, int coeff, ptrdiff_t len)
static void dmix_sub_xch_c (int32_t *dst1, int32_t *dst2, const int32_t *src, ptrdiff_t len)
static void dmix_sub_c (int32_t *dst, const int32_t *src, int coeff, ptrdiff_t len)
static void dmix_add_c (int32_t *dst, const int32_t *src, int coeff, ptrdiff_t len)
static void dmix_scale_c (int32_t *dst, int scale, ptrdiff_t len)
static void dmix_scale_inv_c (int32_t *dst, int scale_inv, ptrdiff_t len)
static void filter0 (int32_t *dst, const int32_t *src, int32_t coeff, ptrdiff_t len)
static void filter1 (int32_t *dst, const int32_t *src, int32_t coeff, ptrdiff_t len)
static void assemble_freq_bands_c (int32_t *dst, int32_t *src0, int32_t *src1, const int32_t *coeff, ptrdiff_t len)
static void lbr_bank_c (float output[32][4], float **input, const float *coeff, ptrdiff_t ofs, ptrdiff_t len)
static void lfe_iir_c (float *output, const float *input, const float iir[5][4], float hist[5][2], ptrdiff_t factor)
av_cold void ff_dcadsp_init (DCADSPContext *s)
Function Documentation
decode_hf_c()
static void decode_hf_c (int32_t ** dst, const int32_t * vq_index, const int8_t hf_vq[1024][32], int32_t scale_factors[32][2], ptrdiff_t sb_start, ptrdiff_t sb_end, ptrdiff_t ofs, ptrdiff_t len) static
Definition at line 26 of file dcadsp.c.
Referenced by ff_dcadsp_init().
decode_joint_c()
static void decode_joint_c (int32_t ** dst, int32_t ** src, const int32_t * scale_factors, ptrdiff_t sb_start, ptrdiff_t sb_end, ptrdiff_t ofs, ptrdiff_t len) static
Definition at line 43 of file dcadsp.c.
Referenced by ff_dcadsp_init().
lfe_fir_float_c()
static void lfe_fir_float_c (float * pcm_samples, int32_t * lfe_samples, const float * filter_coeff, ptrdiff_t npcmblocks, int dec_select) static
Definition at line 57 of file dcadsp.c.
Referenced by lfe_fir0_float_c(), and lfe_fir1_float_c().
lfe_fir0_float_c()
static void lfe_fir0_float_c (float * pcm_samples, int32_t * lfe_samples, const float * filter_coeff, ptrdiff_t npcmblocks) static
Definition at line 87 of file dcadsp.c.
Referenced by ff_dcadsp_init().
lfe_fir1_float_c()
static void lfe_fir1_float_c (float * pcm_samples, int32_t * lfe_samples, const float * filter_coeff, ptrdiff_t npcmblocks) static
Definition at line 93 of file dcadsp.c.
Referenced by ff_dcadsp_init().
lfe_x96_float_c()
static void lfe_x96_float_c (float * dst, const float * src, float * hist, ptrdiff_t len) static
Definition at line 99 of file dcadsp.c.
Referenced by ff_dcadsp_init().
sub_qmf32_float_c()
static void sub_qmf32_float_c (SynthFilterContext * synth, FFTContext * imdct, float * pcm_samples, int32_t ** subband_samples_lo, int32_t ** subband_samples_hi, float * hist1, int * offset, float * hist2, const float * filter_coeff, ptrdiff_t npcmblocks, float scale) static
Definition at line 116 of file dcadsp.c.
Referenced by ff_dcadsp_init().
sub_qmf64_float_c()
static void sub_qmf64_float_c (SynthFilterContext * synth, FFTContext * imdct, float * pcm_samples, int32_t ** subband_samples_lo, int32_t ** subband_samples_hi, float * hist1, int * offset, float * hist2, const float * filter_coeff, ptrdiff_t npcmblocks, float scale) static
Definition at line 145 of file dcadsp.c.
Referenced by ff_dcadsp_init().
lfe_fir_fixed_c()
static void lfe_fir_fixed_c (int32_t * pcm_samples, int32_t * lfe_samples, const int32_t * filter_coeff, ptrdiff_t npcmblocks) static
Definition at line 194 of file dcadsp.c.
Referenced by ff_dcadsp_init().
lfe_x96_fixed_c()
static void lfe_x96_fixed_c (int32_t * dst, const int32_t * src, int32_t * hist, ptrdiff_t len) static
Definition at line 221 of file dcadsp.c.
Referenced by ff_dcadsp_init().
sub_qmf32_fixed_c()
static void sub_qmf32_fixed_c (SynthFilterContext * synth, DCADCTContext * imdct, int32_t * pcm_samples, int32_t ** subband_samples_lo, int32_t ** subband_samples_hi, int32_t * hist1, int * offset, int32_t * hist2, const int32_t * filter_coeff, ptrdiff_t npcmblocks) static
Definition at line 238 of file dcadsp.c.
Referenced by ff_dcadsp_init().
sub_qmf64_fixed_c()
static void sub_qmf64_fixed_c (SynthFilterContext * synth, DCADCTContext * imdct, int32_t * pcm_samples, int32_t ** subband_samples_lo, int32_t ** subband_samples_hi, int32_t * hist1, int * offset, int32_t * hist2, const int32_t * filter_coeff, ptrdiff_t npcmblocks) static
Definition at line 262 of file dcadsp.c.
Referenced by ff_dcadsp_init().
decor_c()
static void decor_c (int32_t * dst, const int32_t * src, int coeff, ptrdiff_t len) static
Definition at line 298 of file dcadsp.c.
Referenced by ff_dcadsp_init().
dmix_sub_xch_c()
static void dmix_sub_xch_c (int32_t * dst1, int32_t * dst2, const int32_t * src, ptrdiff_t len) static
Definition at line 306 of file dcadsp.c.
Referenced by ff_dcadsp_init().
dmix_sub_c()
static void dmix_sub_c (int32_t * dst, const int32_t * src, int coeff, ptrdiff_t len) static
Definition at line 318 of file dcadsp.c.
Referenced by ff_dcadsp_init().
dmix_add_c()
static void dmix_add_c (int32_t * dst, const int32_t * src, int coeff, ptrdiff_t len) static
Definition at line 326 of file dcadsp.c.
Referenced by ff_dcadsp_init().
dmix_scale_c()
static void dmix_scale_c (int32_t * dst, int scale, ptrdiff_t len) static
Definition at line 334 of file dcadsp.c.
Referenced by ff_dcadsp_init().
dmix_scale_inv_c()
static void dmix_scale_inv_c (int32_t * dst, int scale_inv, ptrdiff_t len) static
Definition at line 342 of file dcadsp.c.
Referenced by ff_dcadsp_init().
filter0()
static void filter0 (int32_t * dst, const int32_t * src, int32_t coeff, ptrdiff_t len) static
Definition at line 350 of file dcadsp.c.
Referenced by assemble_freq_bands_c(), ff_put_vp8_epel16_h6_mmi(), ff_put_vp8_epel16_v6_mmi(), ff_put_vp8_epel4_h6_mmi(), ff_put_vp8_epel4_v6_mmi(), ff_put_vp8_epel8_h6_mmi(), ff_put_vp8_epel8_v6_mmi(), hevc_idct_8x32_column_msa(), and set_filter().
filter1()
static void filter1 (int32_t * dst, const int32_t * src, int32_t coeff, ptrdiff_t len) static
Definition at line 358 of file dcadsp.c.
Referenced by apply_ir_filter(), assemble_freq_bands_c(), ff_put_vp8_epel16_h4_mmi(), ff_put_vp8_epel16_h6_mmi(), ff_put_vp8_epel16_v4_mmi(), ff_put_vp8_epel16_v6_mmi(), ff_put_vp8_epel4_h4_mmi(), ff_put_vp8_epel4_h6_mmi(), ff_put_vp8_epel4_v4_mmi(), ff_put_vp8_epel4_v6_mmi(), ff_put_vp8_epel8_h4_mmi(), ff_put_vp8_epel8_h6_mmi(), ff_put_vp8_epel8_v4_mmi(), ff_put_vp8_epel8_v6_mmi(), and hevc_idct_8x32_column_msa().
assemble_freq_bands_c()
static void assemble_freq_bands_c (int32_t * dst, int32_t * src0, int32_t * src1, const int32_t * coeff, ptrdiff_t len) static
Definition at line 366 of file dcadsp.c.
Referenced by ff_dcadsp_init().
lbr_bank_c()
static void lbr_bank_c (float output[32][4], float ** input, const float * coeff, ptrdiff_t ofs, ptrdiff_t len) static
Definition at line 388 of file dcadsp.c.
Referenced by ff_dcadsp_init().
lfe_iir_c()
static void lfe_iir_c (float * output, const float * input, const float iir[5][4], float hist[5][2], ptrdiff_t factor) static
Definition at line 434 of file dcadsp.c.
Referenced by ff_dcadsp_init().
ff_dcadsp_init()
av_cold void ff_dcadsp_init (DCADSPContext * s)
Definition at line 459 of file dcadsp.c.
Referenced by dcadec_init().