FFmpeg: libavcodec/dcadct.c File Reference
dcadct.c File Reference
#include "libavutil/common.h"
#include "dcadct.h"
#include "dcamath.h"
Functions
static void sum_a (const int *input, int *output, int len)
static void sum_b (const int *input, int *output, int len)
static void sum_c (const int *input, int *output, int len)
static void sum_d (const int *input, int *output, int len)
static void dct_a (const int *input, int *output)
static void dct_b (const int *input, int *output)
static void mod_a (const int *input, int *output)
static void mod_b (int *input, int *output)
static void mod_c (const int *input, int *output)
static void clp_v (int *input, int len)
static void imdct_half_32 (int32_t *output, const int32_t *input)
static void mod64_a (const int *input, int *output)
static void mod64_b (int *input, int *output)
static void mod64_c (const int *input, int *output)
static void imdct_half_64 (int32_t *output, const int32_t *input)
av_cold void ff_dcadct_init (DCADCTContext *c)
Function Documentation
sum_a()
static void sum_a (const int * input, int * output, int len) static
Definition at line 26 of file dcadct.c.
Referenced by imdct_half_32(), imdct_half_64(), and main().
sum_b()
static void sum_b (const int * input, int * output, int len) static
Definition at line 34 of file dcadct.c.
Referenced by imdct_half_32(), imdct_half_64(), and main().
sum_c()
static void sum_c (const int * input, int * output, int len) static
Definition at line 43 of file dcadct.c.
Referenced by imdct_half_32(), and imdct_half_64().
sum_d()
static void sum_d (const int * input, int * output, int len) static
Definition at line 51 of file dcadct.c.
Referenced by ff_dc_16x16_msa(), ff_dc_32x32_msa(), ff_dc_4x4_msa(), ff_dc_8x8_msa(), imdct_half_32(), and imdct_half_64().
dct_a()
static void dct_a (const int * input, int * output) static
Definition at line 60 of file dcadct.c.
Referenced by imdct_half_32(), and imdct_half_64().
dct_b()
static void dct_b (const int * input, int * output) static
Definition at line 83 of file dcadct.c.
Referenced by imdct_half_32(), and imdct_half_64().
mod_a()
static void mod_a (const int * input, int * output) static
Definition at line 106 of file dcadct.c.
Referenced by imdct_half_32(), and imdct_half_64().
mod_b()
static void mod_b (int * input, int * output) static
Definition at line 124 of file dcadct.c.
Referenced by imdct_half_32(), and imdct_half_64().
mod_c()
static void mod_c (const int * input, int * output) static
Definition at line 143 of file dcadct.c.
Referenced by imdct_half_32().
clp_v()
static void clp_v (int * input, int len) static
Definition at line 165 of file dcadct.c.
Referenced by imdct_half_32(), and imdct_half_64().
imdct_half_32()
static void imdct_half_32 (int32_t * output, const int32_t * input) static
Definition at line 173 of file dcadct.c.
Referenced by ff_dcadct_init().
mod64_a()
static void mod64_a (const int * input, int * output) static
Definition at line 219 of file dcadct.c.
Referenced by imdct_half_64().
mod64_b()
static void mod64_b (int * input, int * output) static
Definition at line 241 of file dcadct.c.
Referenced by imdct_half_64().
mod64_c()
static void mod64_c (const int * input, int * output) static
Definition at line 262 of file dcadct.c.
Referenced by imdct_half_64().
imdct_half_64()
static void imdct_half_64 (int32_t * output, const int32_t * input) static
Definition at line 292 of file dcadct.c.
Referenced by ff_dcadct_init().
ff_dcadct_init()
av_cold void ff_dcadct_init (DCADCTContext * c)
Definition at line 358 of file dcadct.c.
Referenced by ff_dca_core_init().