FFmpeg: libavcodec/dcadec.h File Reference
dcadec.h File Reference
#include "libavutil/common.h"
#include "libavutil/crc.h"
#include "libavutil/float_dsp.h"
#include "avcodec.h"
#include "get_bits.h"
#include "dca.h"
#include "dcadsp.h"
#include "dca_core.h"
#include "dca_exss.h"
#include "dca_xll.h"
#include "dca_lbr.h"
Data Structures
struct DCAContext
Macros
#define DCA_PACKET_CORE 0x01
#define DCA_PACKET_EXSS 0x02
#define DCA_PACKET_XLL 0x04
#define DCA_PACKET_LBR 0x08
#define DCA_PACKET_MASK 0x0f
#define DCA_PACKET_RECOVERY 0x10
Sync error recovery flag.
#define DCA_PACKET_RESIDUAL 0x20
Core valid for residual decoding.
Functions
int ff_dca_set_channel_layout (AVCodecContext *avctx, int *ch_remap, int dca_mask)
void ff_dca_downmix_to_stereo_fixed (DCADSPContext *dcadsp, int32_t **samples, int *coeff_l, int nsamples, int ch_mask)
void ff_dca_downmix_to_stereo_float (AVFloatDSPContext *fdsp, float **samples, int *coeff_l, int nsamples, int ch_mask)
static int ff_dca_check_crc (AVCodecContext *avctx, GetBitContext *s, int p1, int p2)
static int ff_dca_seek_bits (GetBitContext *s, int p)
Macro Definition Documentation
DCA_PACKET_CORE
#define DCA_PACKET_CORE 0x01
Definition at line 37 of file dcadec.h.
Referenced by combine_residual_frame(), and dcadec_decode_frame().
DCA_PACKET_EXSS
#define DCA_PACKET_EXSS 0x02
Definition at line 38 of file dcadec.h.
Referenced by dcadec_decode_frame(), and ff_dca_core_filter_frame().
DCA_PACKET_XLL
#define DCA_PACKET_XLL 0x04
Definition at line 39 of file dcadec.h.
Referenced by dcadec_decode_frame(), ff_dca_core_parse_exss(), and filter_frame_fixed().
DCA_PACKET_LBR
#define DCA_PACKET_LBR 0x08
Definition at line 40 of file dcadec.h.
Referenced by dcadec_decode_frame().
DCA_PACKET_MASK
#define DCA_PACKET_MASK 0x0f
Definition at line 41 of file dcadec.h.
Referenced by dcadec_flush().
DCA_PACKET_RECOVERY
#define DCA_PACKET_RECOVERY 0x10
Sync error recovery flag.
Definition at line 43 of file dcadec.h.
Referenced by dcadec_decode_frame(), and ff_dca_xll_filter_frame().
DCA_PACKET_RESIDUAL
#define DCA_PACKET_RESIDUAL 0x20
Core valid for residual decoding.
Definition at line 44 of file dcadec.h.
Referenced by dcadec_decode_frame().
Function Documentation
ff_dca_set_channel_layout()
int ff_dca_set_channel_layout (AVCodecContext * avctx, int * ch_remap, int dca_mask)
Definition at line 32 of file dcadec.c.
Referenced by ff_dca_core_filter_frame(), and ff_dca_xll_filter_frame().
ff_dca_downmix_to_stereo_fixed()
void ff_dca_downmix_to_stereo_fixed (DCADSPContext * dcadsp, int32_t ** samples, int * coeff_l, int nsamples, int ch_mask)
Definition at line 79 of file dcadec.c.
Referenced by ff_dca_xll_filter_frame(), and filter_frame_fixed().
ff_dca_downmix_to_stereo_float()
void ff_dca_downmix_to_stereo_float (AVFloatDSPContext * fdsp, float ** samples, int * coeff_l, int nsamples, int ch_mask)
Definition at line 110 of file dcadec.c.
Referenced by filter_frame_float().
ff_dca_check_crc()
static int ff_dca_check_crc (AVCodecContext * avctx, GetBitContext * s, int p1, int p2) inline static
Definition at line 75 of file dcadec.h.
Referenced by chs_parse_header(), ff_dca_exss_parse(), parse_aux_data(), parse_coding_header(), parse_common_header(), parse_navi_table(), parse_x96_coding_header(), parse_x96_frame_exss(), parse_xbr_frame(), and parse_xxch_frame().
ff_dca_seek_bits()
static int ff_dca_seek_bits (GetBitContext * s, int p) inline static
Definition at line 89 of file dcadec.h.
Referenced by chs_parse_band_data(), chs_parse_header(), ff_dca_core_parse(), ff_dca_exss_parse(), parse_coding_header(), parse_common_header(), parse_descriptor(), parse_frame(), parse_x96_coding_header(), parse_x96_frame(), parse_x96_frame_exss(), parse_xbr_frame(), parse_xch_frame(), and parse_xxch_frame().