FFmpeg: libavcodec/dcadec.c File Reference
dcadec.c File Reference
#include "libavutil/opt.h"
#include "libavutil/channel_layout.h"
#include "dcadec.h"
#include "dcahuff.h"
#include "dca_syncwords.h"
#include "profiles.h"
Macros
#define MIN_PACKET_SIZE 16
#define MAX_PACKET_SIZE 0x104000
#define OFFSET(x) offsetof(DCAContext, x)
#define PARAM AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_DECODING_PARAM
Functions
int ff_dca_set_channel_layout (AVCodecContext *avctx, int *ch_remap, int dca_mask)
void ff_dca_downmix_to_stereo_fixed (DCADSPContext *dcadsp, int32_t **samples, int *coeff_l, int nsamples, int ch_mask)
void ff_dca_downmix_to_stereo_float (AVFloatDSPContext *fdsp, float **samples, int *coeff_l, int nsamples, int ch_mask)
static int dcadec_decode_frame (AVCodecContext *avctx, void *data, int *got_frame_ptr, AVPacket *avpkt)
static av_cold void dcadec_flush (AVCodecContext *avctx)
static av_cold int dcadec_close (AVCodecContext *avctx)
static av_cold int dcadec_init (AVCodecContext *avctx)
Variables
static const AVOption dcadec_options []
static const AVClass dcadec_class
AVCodec ff_dca_decoder
Macro Definition Documentation
MIN_PACKET_SIZE
#define MIN_PACKET_SIZE 16
Definition at line 29 of file dcadec.c.
Referenced by dcadec_decode_frame().
MAX_PACKET_SIZE
#define MAX_PACKET_SIZE 0x104000
Definition at line 30 of file dcadec.c.
Referenced by dcadec_decode_frame().
OFFSET
#define OFFSET (x) offsetof(DCAContext, x)
Definition at line 368 of file dcadec.c.
PARAM
#define PARAM AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_DECODING_PARAM
Definition at line 369 of file dcadec.c.
Function Documentation
ff_dca_set_channel_layout()
int ff_dca_set_channel_layout (AVCodecContext * avctx, int * ch_remap, int dca_mask)
Definition at line 32 of file dcadec.c.
Referenced by ff_dca_core_filter_frame(), and ff_dca_xll_filter_frame().
ff_dca_downmix_to_stereo_fixed()
void ff_dca_downmix_to_stereo_fixed (DCADSPContext * dcadsp, int32_t ** samples, int * coeff_l, int nsamples, int ch_mask)
Definition at line 79 of file dcadec.c.
Referenced by ff_dca_xll_filter_frame(), and filter_frame_fixed().
ff_dca_downmix_to_stereo_float()
void ff_dca_downmix_to_stereo_float (AVFloatDSPContext * fdsp, float ** samples, int * coeff_l, int nsamples, int ch_mask)
Definition at line 110 of file dcadec.c.
Referenced by filter_frame_float().
dcadec_decode_frame()
static int dcadec_decode_frame (AVCodecContext * avctx, void * data, int * got_frame_ptr, AVPacket * avpkt) static
Definition at line 144 of file dcadec.c.
dcadec_flush()
static av_cold void dcadec_flush (AVCodecContext * avctx) static
Definition at line 296 of file dcadec.c.
dcadec_close()
static av_cold int dcadec_close (AVCodecContext * avctx) static
Definition at line 307 of file dcadec.c.
dcadec_init()
static av_cold int dcadec_init (AVCodecContext * avctx) static
Definition at line 321 of file dcadec.c.
Variable Documentation
dcadec_options
const AVOption dcadec_options[] static
Initial value:
= {
    { "core_only", "Decode core only without extensions", OFFSET(core_only), AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, PARAM },
    { NULL }
}
Definition at line 371 of file dcadec.c.
dcadec_class
const AVClass dcadec_class static
Initial value:
= {
    .class_name = "DCA decoder",
    .item_name  = av_default_item_name,
    .option     = dcadec_options,
    .version    = LIBAVUTIL_VERSION_INT,
    .category   = AV_CLASS_CATEGORY_DECODER,
}
Definition at line 376 of file dcadec.c.
ff_dca_decoder
AVCodec ff_dca_decoder
Initial value:
= {
    .name           = "dca",
    .long_name      = NULL_IF_CONFIG_SMALL("DCA (DTS Coherent Acoustics)"),
    .type           = AVMEDIA_TYPE_AUDIO,
    .id             = AV_CODEC_ID_DTS,
    .priv_data_size = sizeof(DCAContext),
    .init           = dcadec_init,
    .decode         = dcadec_decode_frame,
    .close          = dcadec_close,
    .flush          = dcadec_flush,
    .capabilities   = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_CHANNEL_CONF,
    .sample_fmts    = (const enum AVSampleFormat[]) { AV_SAMPLE_FMT_S16P, AV_SAMPLE_FMT_S32P,
                                                      AV_SAMPLE_FMT_FLTP, AV_SAMPLE_FMT_NONE },
    .priv_class     = &dcadec_class,
    .profiles       = NULL_IF_CONFIG_SMALL(ff_dca_profiles),
    .caps_internal  = FF_CODEC_CAP_INIT_CLEANUP,
}
Definition at line 384 of file dcadec.c.