FFmpeg: libavcodec/dcaenc.c File Reference
dcaenc.c File Reference
#include "libavutil/avassert.h"
#include "libavutil/channel_layout.h"
#include "libavutil/common.h"
#include "libavutil/ffmath.h"
#include "avcodec.h"
#include "dca.h"
#include "dcadata.h"
#include "dcaenc.h"
#include "internal.h"
#include "mathops.h"
#include "put_bits.h"
Data Structures
struct DCAEncContext
struct cplx32
Macros
#define MAX_CHANNELS 6
#define DCA_MAX_FRAME_SIZE 16384
#define DCA_HEADER_SIZE 13
#define DCA_LFE_SAMPLES 8
#define DCAENC_SUBBANDS 32
#define SUBFRAMES 1
#define SUBSUBFRAMES 2
#define SUBBAND_SAMPLES (SUBFRAMES * SUBSUBFRAMES * 8)
#define AUBANDS 25
#define USED_1ABITS 1
#define USED_NABITS 2
#define USED_26ABITS 4
Typedefs
typedef void(* walk_band_t) (DCAEncContext *c, int band1, int band2, int f, int32_t spectrum1, int32_t spectrum2, int channel, int32_t *arg)
Functions
static double hom (double f)
static double gammafilter (int i, double f)
static int encode_init (AVCodecContext *avctx)
static int32_t cos_t (int x)
static int32_t sin_t (int x)
static int32_t half32 (int32_t a)
static int32_t mul32 (int32_t a, int32_t b)
static void subband_transform (DCAEncContext *c, const int32_t *input)
static void lfe_downsample (DCAEncContext *c, const int32_t *input)
static void fft (const int32_t in[2 *256], cplx32 out[256])
static int32_t get_cb (int32_t in)
static int32_t add_cb (int32_t a, int32_t b)
static void adjust_jnd (int samplerate_index, const int32_t in[512], int32_t out_cb[256])
static void walk_band_low (DCAEncContext *c, int band, int channel, walk_band_t walk, int32_t *arg)
static void walk_band_high (DCAEncContext *c, int band, int channel, walk_band_t walk, int32_t *arg)
static void update_band_masking (DCAEncContext *c, int band1, int band2, int f, int32_t spectrum1, int32_t spectrum2, int channel, int32_t *arg)
static void calc_masking (DCAEncContext *c, const int32_t *input)
static void find_peaks (DCAEncContext *c)
static int init_quantization_noise (DCAEncContext *c, int noise)
static void assign_bits (DCAEncContext *c)
static void shift_history (DCAEncContext *c, const int32_t *input)
static int32_t quantize_value (int32_t value, softfloat quant)
static int calc_one_scale (int32_t peak_cb, int abits, softfloat *quant)
static void calc_scales (DCAEncContext *c)
static void quantize_all (DCAEncContext *c)
static void put_frame_header (DCAEncContext *c)
static void put_primary_audio_header (DCAEncContext *c)
static void put_subframe_samples (DCAEncContext *c, int ss, int band, int ch)
static void put_subframe (DCAEncContext *c, int subframe)
static int encode_frame (AVCodecContext *avctx, AVPacket *avpkt, const AVFrame *frame, int *got_packet_ptr)
Variables
static int32_t cos_table [2048]
static int32_t band_interpolation [2][512]
static int32_t band_spectrum [2][8]
static int32_t auf [9][AUBANDS][256]
static int32_t cb_to_add [256]
static int32_t cb_to_level [2048]
static int32_t lfe_fir_64i [512]
static const int snr_fudge = 128
static const AVCodecDefault defaults []
AVCodec ff_dca_encoder
Macro Definition Documentation
MAX_CHANNELS
#define MAX_CHANNELS 6
Definition at line 36 of file dcaenc.c.
DCA_MAX_FRAME_SIZE
#define DCA_MAX_FRAME_SIZE 16384
Definition at line 37 of file dcaenc.c.
Referenced by encode_init().
DCA_HEADER_SIZE
#define DCA_HEADER_SIZE 13
Definition at line 38 of file dcaenc.c.
DCA_LFE_SAMPLES
#define DCA_LFE_SAMPLES 8
Definition at line 39 of file dcaenc.c.
Referenced by find_peaks(), lfe_downsample(), and put_subframe().
DCAENC_SUBBANDS
#define DCAENC_SUBBANDS 32
Definition at line 41 of file dcaenc.c.
Referenced by put_primary_audio_header(), and put_subframe().
SUBFRAMES
#define SUBFRAMES 1
Definition at line 42 of file dcaenc.c.
Referenced by acb_search(), comp_lpc_coeff(), encode_frame(), ff_g723_1_lsp_interpolate(), formant_postfilter(), g723_1_decode_frame(), g723_1_encode_frame(), generate_noise(), pack_bitstream(), perceptual_filter(), put_primary_audio_header(), and unpack_bitstream().
SUBSUBFRAMES
#define SUBSUBFRAMES 2
Definition at line 43 of file dcaenc.c.
Referenced by calc_masking(), and put_subframe().
SUBBAND_SAMPLES
#define SUBBAND_SAMPLES (SUBFRAMES * SUBSUBFRAMES * 8)
Definition at line 44 of file dcaenc.c.
Referenced by encode_init(), find_peaks(), put_frame_header(), quantize_all(), and subband_transform().
AUBANDS
#define AUBANDS 25
Definition at line 45 of file dcaenc.c.
Referenced by adjust_jnd(), and encode_init().
USED_1ABITS
#define USED_1ABITS 1
Definition at line 569 of file dcaenc.c.
Referenced by assign_bits(), and init_quantization_noise().
USED_NABITS
#define USED_NABITS 2
Definition at line 570 of file dcaenc.c.
Referenced by init_quantization_noise().
USED_26ABITS
#define USED_26ABITS 4
Definition at line 571 of file dcaenc.c.
Referenced by assign_bits(), and init_quantization_noise().
Typedef Documentation
walk_band_t
typedef void(* walk_band_t) (DCAEncContext *c, int band1, int band2, int f, int32_t spectrum1, int32_t spectrum2, int channel, int32_t *arg)
Definition at line 461 of file dcaenc.c.
Function Documentation
hom()
static double hom (double f) static
Definition at line 89 of file dcaenc.c.
Referenced by encode_init().
gammafilter()
static double gammafilter (int i, double f) static
Definition at line 99 of file dcaenc.c.
Referenced by encode_init().
encode_init()
static int encode_init (AVCodecContext * avctx) static
Definition at line 108 of file dcaenc.c.
cos_t()
static int32_t cos_t (int x) inline static
Definition at line 231 of file dcaenc.c.
Referenced by fft(), sin_t(), and subband_transform().
sin_t()
static int32_t sin_t (int x) inline static
Definition at line 236 of file dcaenc.c.
Referenced by fft().
half32()
static int32_t half32 (int32_t a) inline static
Definition at line 241 of file dcaenc.c.
Referenced by fft().
mul32()
static int32_t mul32 (int32_t a, int32_t b) inline static
Definition at line 246 of file dcaenc.c.
Referenced by calc_one_scale(), fft(), init_quantization_noise(), lfe_downsample(), quantize_value(), and subband_transform().
subband_transform()
static void subband_transform (DCAEncContext * c, const int32_t * input) static
Definition at line 252 of file dcaenc.c.
Referenced by encode_frame().
lfe_downsample()
static void lfe_downsample (DCAEncContext * c, const int32_t * input) static
Definition at line 303 of file dcaenc.c.
Referenced by encode_frame().
fft()
static void fft (const int32_t in[2 *256], cplx32 out[256]) static
Definition at line 339 of file dcaenc.c.
Referenced by adjust_jnd(), and sofalizer_fast_convolute().
get_cb()
static int32_t get_cb (int32_t in) static
Definition at line 406 of file dcaenc.c.
Referenced by adjust_jnd(), and find_peaks().
add_cb()
static int32_t add_cb (int32_t a, int32_t b) static
Definition at line 420 of file dcaenc.c.
Referenced by adjust_jnd().
adjust_jnd()
static void adjust_jnd (int samplerate_index, const int32_t in[512], int32_t out_cb[256]) static
Definition at line 430 of file dcaenc.c.
Referenced by calc_masking().
walk_band_low()
static void walk_band_low (DCAEncContext * c, int band, int channel, walk_band_t walk, int32_t * arg) static
Definition at line 465 of file dcaenc.c.
Referenced by calc_masking().
walk_band_high()
static void walk_band_high (DCAEncContext * c, int band, int channel, walk_band_t walk, int32_t * arg) static
Definition at line 480 of file dcaenc.c.
Referenced by calc_masking().
update_band_masking()
static void update_band_masking (DCAEncContext * c, int band1, int band2, int f, int32_t spectrum1, int32_t spectrum2, int channel, int32_t * arg) static
Definition at line 495 of file dcaenc.c.
Referenced by calc_masking().
calc_masking()
static void calc_masking (DCAEncContext * c, const int32_t * input) static
Definition at line 505 of file dcaenc.c.
Referenced by encode_frame().
find_peaks()
static void find_peaks (DCAEncContext * c) static
Definition at line 540 of file dcaenc.c.
Referenced by encode_frame().
init_quantization_noise()
static int init_quantization_noise (DCAEncContext * c, int noise) static
Definition at line 573 of file dcaenc.c.
Referenced by assign_bits().
assign_bits()
static void assign_bits (DCAEncContext * c) static
Definition at line 610 of file dcaenc.c.
Referenced by encode_frame().
shift_history()
static void shift_history (DCAEncContext * c, const int32_t * input) static
Definition at line 648 of file dcaenc.c.
Referenced by encode_frame().
quantize_value()
static int32_t quantize_value (int32_t value, softfloat quant) static
Definition at line 660 of file dcaenc.c.
Referenced by calc_one_scale(), put_subframe(), and quantize_all().
calc_one_scale()
static int calc_one_scale (int32_t peak_cb, int abits, softfloat * quant) static
Definition at line 669 of file dcaenc.c.
Referenced by calc_scales().
calc_scales()
static void calc_scales (DCAEncContext * c) static
Definition at line 701 of file dcaenc.c.
Referenced by encode_frame().
quantize_all()
static void quantize_all (DCAEncContext * c) static
Definition at line 715 of file dcaenc.c.
Referenced by encode_frame().
put_frame_header()
static void put_frame_header (DCAEncContext * c) static
Definition at line 725 of file dcaenc.c.
Referenced by encode_frame().
put_primary_audio_header()
static void put_primary_audio_header (DCAEncContext * c) static
Definition at line 808 of file dcaenc.c.
Referenced by encode_frame().
put_subframe_samples()
static void put_subframe_samples (DCAEncContext * c, int ss, int band, int ch) static
Definition at line 854 of file dcaenc.c.
Referenced by put_subframe().
put_subframe()
static void put_subframe (DCAEncContext * c, int subframe) static
Definition at line 876 of file dcaenc.c.
Referenced by encode_frame().
encode_frame()
static int encode_frame (AVCodecContext * avctx, AVPacket * avpkt, const AVFrame * frame, int * got_packet_ptr) static
Definition at line 933 of file dcaenc.c.
Variable Documentation
cos_table
int32_t cos_table[2048] static
Definition at line 80 of file dcaenc.c.
Referenced by cos_t(), and encode_init().
band_interpolation
int32_t band_interpolation[2][512] static
Definition at line 81 of file dcaenc.c.
band_spectrum
int32_t band_spectrum[2][8] static
Definition at line 82 of file dcaenc.c.
auf
int32_t auf[9][AUBANDS][256] static
Definition at line 83 of file dcaenc.c.
Referenced by adjust_jnd(), and encode_init().
cb_to_add
int32_t cb_to_add[256] static
Definition at line 84 of file dcaenc.c.
Referenced by add_cb(), and encode_init().
cb_to_level
int32_t cb_to_level[2048] static
Definition at line 85 of file dcaenc.c.
Referenced by calc_one_scale(), encode_init(), and get_cb().
lfe_fir_64i
int32_t lfe_fir_64i[512] static
Definition at line 86 of file dcaenc.c.
Referenced by encode_init(), and lfe_downsample().
snr_fudge
const int snr_fudge = 128 static
Definition at line 568 of file dcaenc.c.
Referenced by assign_bits().
defaults
const AVCodecDefault defaults[] static
Initial value:
= {
    { "b",          "1411200" },
    { NULL },
}
Definition at line 975 of file dcaenc.c.
Referenced by g726_reset().
ff_dca_encoder
AVCodec ff_dca_encoder
Initial value:
= {
    .name                  = "dca",
    .long_name             = NULL_IF_CONFIG_SMALL("DCA (DTS Coherent Acoustics)"),
    .type                  = AVMEDIA_TYPE_AUDIO,
    .id                    = AV_CODEC_ID_DTS,
    .priv_data_size        = sizeof(DCAEncContext),
    .init                  = encode_init,
    .encode2               = encode_frame,
    .capabilities          = AV_CODEC_CAP_EXPERIMENTAL,
    .sample_fmts           = (const enum AVSampleFormat[]){ AV_SAMPLE_FMT_S32,
                                                            AV_SAMPLE_FMT_NONE },
    .supported_samplerates = sample_rates,
    .channel_layouts       = (const uint64_t[]) { AV_CH_LAYOUT_MONO,
                                                  AV_CH_LAYOUT_STEREO,
                                                  AV_CH_LAYOUT_2_2,
                                                  AV_CH_LAYOUT_5POINT0,
                                                  AV_CH_LAYOUT_5POINT1,
                                                  0 },
    .defaults              = defaults,
}
Definition at line 980 of file dcaenc.c.