FFmpeg: libavcodec/dcamath.h File Reference
dcamath.h File Reference
#include "libavutil/common.h"
#include "libavutil/intmath.h"
Functions
static int32_t norm__ (int64_t a, int bits)
static int32_t mul__ (int32_t a, int32_t b, int bits)
static int32_t norm13 (int64_t a)
static int32_t norm16 (int64_t a)
static int32_t norm20 (int64_t a)
static int32_t norm21 (int64_t a)
static int32_t norm23 (int64_t a)
static int32_t mul15 (int32_t a, int32_t b)
static int32_t mul16 (int32_t a, int32_t b)
static int32_t mul17 (int32_t a, int32_t b)
static int32_t mul22 (int32_t a, int32_t b)
static int32_t mul23 (int32_t a, int32_t b)
static int32_t mul31 (int32_t a, int32_t b)
static int32_t clip23 (int32_t a)
Function Documentation
norm__()
static int32_t norm__ (int64_t a, int bits) inline static
Definition at line 27 of file dcamath.h.
Referenced by dequantize(), mul__(), norm13(), norm16(), norm20(), norm21(), and norm23().
mul__()
static int32_t mul__ (int32_t a, int32_t b, int bits) inline static
Definition at line 35 of file dcamath.h.
Referenced by mul15(), mul16(), mul17(), mul22(), mul23(), and mul31().
norm13()
static int32_t norm13 (int64_t a) inline static
Definition at line 40 of file dcamath.h.
Referenced by inverse_adpcm().
norm16()
static int32_t norm16 (int64_t a) inline static
Definition at line 41 of file dcamath.h.
Referenced by chs_filter_band_data().
norm20()
static int32_t norm20 (int64_t a) inline static
Definition at line 42 of file dcamath.h.
Referenced by synth_filter_fixed_64().
norm21()
static int32_t norm21 (int64_t a) inline static
Definition at line 43 of file dcamath.h.
Referenced by synth_filter_fixed().
norm23()
static int32_t norm23 (int64_t a) inline static
Definition at line 44 of file dcamath.h.
Referenced by dct_a(), dct_b(), lfe_fir_fixed_c(), and lfe_x96_fixed_c().
mul15()
static int32_t mul15 (int32_t a, int32_t b) inline static
Definition at line 46 of file dcamath.h.
Referenced by dmix_add_c(), dmix_scale_c(), dmix_sub_c(), and prescale_down_mix().
mul16()
static int32_t mul16 (int32_t a, int32_t b) inline static
Definition at line 47 of file dcamath.h.
Referenced by chs_filter_band_data(), combine_residual_frame(), dmix_scale_inv_c(), filter_frame_fixed(), parse_dmix_coeffs(), and prescale_down_mix().
mul17()
static int32_t mul17 (int32_t a, int32_t b) inline static
Definition at line 48 of file dcamath.h.
Referenced by decode_joint_c().
mul22()
static int32_t mul22 (int32_t a, int32_t b) inline static
Definition at line 49 of file dcamath.h.
Referenced by filter0().
mul23()
static int32_t mul23 (int32_t a, int32_t b) inline static
Definition at line 50 of file dcamath.h.
Referenced by dmix_sub_xch_c(), filter1(), mod64_a(), mod64_b(), mod64_c(), mod_a(), mod_b(), mod_c(), and parse_subframe_audio().
mul31()
static int32_t mul31 (int32_t a, int32_t b) inline static
Definition at line 51 of file dcamath.h.
Referenced by parse_x96_subframe_audio().
clip23()
static int32_t clip23 (int32_t a) inline static
Definition at line 53 of file dcamath.h.
Referenced by chs_filter_band_data(), clp_v(), combine_residual_frame(), decode_hf_c(), decode_joint_c(), dequantize(), ff_dca_xll_filter_frame(), filter_frame_fixed(), imdct_half_32(), imdct_half_64(), inverse_adpcm(), lfe_fir_fixed_c(), lfe_x96_fixed_c(), parse_subframe_audio(), parse_x96_subframe_audio(), synth_filter_fixed(), and synth_filter_fixed_64().