FFmpeg: libavcodec/dct.h File Reference
dct.h File Reference
#include <stdint.h>
#include "rdft.h"
Data Structures
struct DCTContext
Macros
#define AVCODEC_DCT_H
Functions
int ff_dct_init (DCTContext *s, int nbits, enum DCTTransformType type)
Set up DCT.
void ff_dct_end (DCTContext *s)
void ff_dct_init_x86 (DCTContext *s)
void ff_fdct_ifast (int16_t *data)
void ff_fdct_ifast248 (int16_t *data)
void ff_jpeg_fdct_islow_8 (int16_t *data)
void ff_jpeg_fdct_islow_10 (int16_t *data)
void ff_fdct248_islow_8 (int16_t *data)
void ff_fdct248_islow_10 (int16_t *data)
void ff_j_rev_dct (int16_t *data)
void ff_j_rev_dct4 (int16_t *data)
void ff_j_rev_dct2 (int16_t *data)
void ff_j_rev_dct1 (int16_t *data)
void ff_jref_idct_put (uint8_t *dest, int line_size, int16_t *block)
void ff_jref_idct_add (uint8_t *dest, int line_size, int16_t *block)
Macro Definition Documentation
AVCODEC_DCT_H
#define AVCODEC_DCT_H
Definition at line 25 of file dct.h.
Function Documentation
ff_dct_init()
int ff_dct_init (DCTContext * s, int nbits, enum DCTTransformType type)
Set up DCT.
Parameters
nbits size of the input array: (1 << nbits) for DCT-II, DCT-III and DST-I (1 << nbits) + 1 for DCT-I
Note
the first element of the input of DST-I is ignored
Definition at line 177 of file dct.c.
Referenced by av_fft_end(), decode_init(), ff_mpadsp_init(), fft_end(), and wmavoice_decode_init().
ff_dct_end()
void ff_dct_end (DCTContext * s)
Definition at line 220 of file dct.c.
Referenced by av_fft_end(), decode_end(), fft_end(), and wmavoice_decode_end().
ff_dct_init_x86()
void ff_dct_init_x86 (DCTContext * s)
Definition at line 29 of file dct_init.c.
Referenced by ff_dct_init().
ff_fdct_ifast()
void ff_fdct_ifast (int16_t * data)
Definition at line 208 of file jfdctfst.c.
Referenced by dct_quantize_trellis_c(), encode_init(), ff_convert_matrix(), and ff_fdctdsp_init().
ff_fdct_ifast248()
void ff_fdct_ifast248 (int16_t * data)
Definition at line 274 of file jfdctfst.c.
Referenced by ff_fdctdsp_init().
ff_jpeg_fdct_islow_8()
void ff_jpeg_fdct_islow_8 (int16_t * data)
Referenced by ff_convert_matrix(), and ff_fdctdsp_init().
ff_jpeg_fdct_islow_10()
void ff_jpeg_fdct_islow_10 (int16_t * data)
Referenced by ff_convert_matrix(), and ff_fdctdsp_init().
ff_fdct248_islow_8()
void ff_fdct248_islow_8 (int16_t * data)
Referenced by ff_fdctdsp_init().
ff_fdct248_islow_10()
void ff_fdct248_islow_10 (int16_t * data)
Referenced by ff_fdctdsp_init().
ff_j_rev_dct()
void ff_j_rev_dct (int16_t * data)
Referenced by ff_idctdsp_init().
ff_j_rev_dct4()
void ff_j_rev_dct4 (int16_t * data)
Referenced by ff_idctdsp_init(), ff_jref_idct4_add(), and ff_jref_idct4_put().
ff_j_rev_dct2()
void ff_j_rev_dct2 (int16_t * data)
Referenced by ff_idctdsp_init(), ff_jref_idct2_add(), and ff_jref_idct2_put().
ff_j_rev_dct1()
void ff_j_rev_dct1 (int16_t * data)
Referenced by ff_idctdsp_init().
ff_jref_idct_put()
void ff_jref_idct_put (uint8_t * dest, int line_size, int16_t * block)
Definition at line 1159 of file jrevdct.c.
Referenced by ff_idctdsp_init().
ff_jref_idct_add()
void ff_jref_idct_add (uint8_t * dest, int line_size, int16_t * block)
Definition at line 1165 of file jrevdct.c.
Referenced by ff_idctdsp_init().