FFmpeg: libavcodec/x86/dct_init.c File Reference
dct_init.c File Reference
#include "config.h"
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/x86/cpu.h"
#include "libavcodec/dct.h"
Functions
void ff_dct32_float_sse (FFTSample *out, const FFTSample *in)
void ff_dct32_float_sse2 (FFTSample *out, const FFTSample *in)
void ff_dct32_float_avx (FFTSample *out, const FFTSample *in)
av_cold void ff_dct_init_x86 (DCTContext *s)
Function Documentation
ff_dct32_float_sse()
void ff_dct32_float_sse (FFTSample * out, const FFTSample * in)
Referenced by ff_dct_init_x86().
ff_dct32_float_sse2()
void ff_dct32_float_sse2 (FFTSample * out, const FFTSample * in)
Referenced by ff_dct_init_x86().
ff_dct32_float_avx()
void ff_dct32_float_avx (FFTSample * out, const FFTSample * in)
Referenced by ff_dct_init_x86().
ff_dct_init_x86()
av_cold void ff_dct_init_x86 (DCTContext * s)
Definition at line 29 of file dct_init.c.
Referenced by ff_dct_init().