FFmpeg: libavcodec/dctref.c File Reference
dctref.c File Reference
reference discrete cosine transform (double precision)
#include "libavutil/mathematics.h"
#include "dctref.h"
Functions
av_cold void ff_ref_dct_init (void)
Initialize the double precision discrete cosine transform functions fdct & idct.
void ff_ref_fdct (short *block)
Transform 8x8 block of data with a double precision forward DCT
This is a reference implementation.
void ff_ref_idct (short *block)
Transform 8x8 block of data with a double precision inverse DCT
This is a reference implementation.
Variables
static double coefficients [8 *8]
Detailed Description
reference discrete cosine transform (double precision)
Author
Dylan Yudaken (dyudaken at gmail)
Note
This file could be optimized a lot, but is for reference and so readability is better.
Definition in file dctref.c.
Function Documentation
ff_ref_dct_init()
av_cold void ff_ref_dct_init (void)
Initialize the double precision discrete cosine transform functions fdct & idct.
Definition at line 41 of file dctref.c.
Referenced by main().
ff_ref_fdct()
void ff_ref_fdct (short * block)
Transform 8x8 block of data with a double precision forward DCT
This is a reference implementation.
Parameters
block pointer to 8x8 block of data to transform
Definition at line 59 of file dctref.c.
Referenced by dct_error(), and init_block().
ff_ref_idct()
void ff_ref_idct (short * block)
Transform 8x8 block of data with a double precision inverse DCT
This is a reference implementation.
Parameters
block pointer to 8x8 block of data to transform
Definition at line 95 of file dctref.c.
Referenced by dct_error().
Variable Documentation
coefficients
double coefficients[8 *8] static
Definition at line 35 of file dctref.c.
Referenced by ff_ref_dct_init(), ff_ref_fdct(), and ff_ref_idct().