FFmpeg: libavcodec/dctref.h File Reference
dctref.h File Reference
Functions
void ff_ref_fdct (short *block)
Transform 8x8 block of data with a double precision forward DCT
This is a reference implementation.
void ff_ref_idct (short *block)
Transform 8x8 block of data with a double precision inverse DCT
This is a reference implementation.
void ff_ref_dct_init (void)
Initialize the double precision discrete cosine transform functions fdct & idct.
Function Documentation
ff_ref_fdct()
void ff_ref_fdct (short * block)
Transform 8x8 block of data with a double precision forward DCT
This is a reference implementation.
Parameters
block pointer to 8x8 block of data to transform
Definition at line 59 of file dctref.c.
Referenced by dct_error(), and init_block().
ff_ref_idct()
void ff_ref_idct (short * block)
Transform 8x8 block of data with a double precision inverse DCT
This is a reference implementation.
Parameters
block pointer to 8x8 block of data to transform
Definition at line 95 of file dctref.c.
Referenced by dct_error().
ff_ref_dct_init()
void ff_ref_dct_init (void)
Initialize the double precision discrete cosine transform functions fdct & idct.
Definition at line 41 of file dctref.c.
Referenced by main().