FFmpeg: libavdevice/decklink_dec.cpp File Reference
decklink_dec.cpp File Reference
#include <DeckLinkAPI.h>
#include <pthread.h>
#include <semaphore.h>
#include "config.h"
#include "libavformat/avformat.h"
#include "libavformat/internal.h"
#include "libavutil/avutil.h"
#include "libavutil/common.h"
#include "libavutil/imgutils.h"
#include "libavutil/time.h"
#include "libavutil/mathematics.h"
#include "decklink_common.h"
#include "decklink_dec.h"
Data Structures
class decklink_input_callback
Functions
static void avpacket_queue_init (AVFormatContext *avctx, AVPacketQueue *q)
static void avpacket_queue_flush (AVPacketQueue *q)
static void avpacket_queue_end (AVPacketQueue *q)
static unsigned long long avpacket_queue_size (AVPacketQueue *q)
static int avpacket_queue_put (AVPacketQueue *q, AVPacket *pkt)
static int avpacket_queue_get (AVPacketQueue *q, AVPacket *pkt, int block)
static int64_t get_pkt_pts (IDeckLinkVideoInputFrame *videoFrame, IDeckLinkAudioInputPacket *audioFrame, int64_t wallclock, DecklinkPtsSource pts_src, AVRational time_base, int64_t *initial_pts)
static HRESULT decklink_start_input (AVFormatContext *avctx)
av_cold int ff_decklink_read_close (AVFormatContext *avctx)
av_cold int ff_decklink_read_header (AVFormatContext *avctx)
int ff_decklink_read_packet (AVFormatContext *avctx, AVPacket *pkt)
Function Documentation
avpacket_queue_init()
static void avpacket_queue_init (AVFormatContext * avctx, AVPacketQueue * q) static
Definition at line 73 of file decklink_dec.cpp.
Referenced by ff_decklink_read_header().
avpacket_queue_flush()
static void avpacket_queue_flush (AVPacketQueue * q) static
Definition at line 81 of file decklink_dec.cpp.
Referenced by avpacket_queue_end().
avpacket_queue_end()
static void avpacket_queue_end (AVPacketQueue * q) static
Definition at line 98 of file decklink_dec.cpp.
Referenced by ff_decklink_read_close().
avpacket_queue_size()
static unsigned long long avpacket_queue_size (AVPacketQueue * q) static
Definition at line 105 of file decklink_dec.cpp.
Referenced by avpacket_queue_put(), and decklink_input_callback::VideoInputFrameArrived().
avpacket_queue_put()
static int avpacket_queue_put (AVPacketQueue * q, AVPacket * pkt) static
Definition at line 114 of file decklink_dec.cpp.
Referenced by decklink_input_callback::VideoInputFrameArrived().
avpacket_queue_get()
static int avpacket_queue_get (AVPacketQueue * q, AVPacket * pkt, int block) static
Definition at line 153 of file decklink_dec.cpp.
Referenced by ff_decklink_read_packet().
get_pkt_pts()
static int64_t get_pkt_pts (IDeckLinkVideoInputFrame * videoFrame, IDeckLinkAudioInputPacket * audioFrame, int64_t wallclock, DecklinkPtsSource pts_src, AVRational time_base, int64_t * initial_pts) static
Definition at line 244 of file decklink_dec.cpp.
Referenced by decklink_input_callback::VideoInputFrameArrived().
decklink_start_input()
static HRESULT decklink_start_input (AVFormatContext * avctx) static
Definition at line 433 of file decklink_dec.cpp.
Referenced by ff_decklink_read_header().
ff_decklink_read_close()
av_cold int ff_decklink_read_close (AVFormatContext * avctx)
Definition at line 445 of file decklink_dec.cpp.
ff_decklink_read_header()
av_cold int ff_decklink_read_header (AVFormatContext * avctx)
Definition at line 464 of file decklink_dec.cpp.
ff_decklink_read_packet()
int ff_decklink_read_packet (AVFormatContext * avctx, AVPacket * pkt)
Definition at line 642 of file decklink_dec.cpp.