FFmpeg: libavdevice/decklink_common.cpp File Reference
decklink_common.cpp File Reference
#include <DeckLinkAPI.h>
#include <DeckLinkAPIDispatch.cpp>
#include <pthread.h>
#include <semaphore.h>
#include "libavformat/avformat.h"
#include "libavformat/internal.h"
#include "libavutil/imgutils.h"
#include "decklink_common.h"
Macros
#define DECKLINK_STR const char *
#define DECKLINK_STRDUP av_strdup
#define DECKLINK_FREE(s) free((void *) s)
#define DECKLINK_BOOL bool
Functions
HRESULT ff_decklink_get_display_name (IDeckLink *This, const char **displayName)
static int decklink_select_input (AVFormatContext *avctx, BMDDeckLinkConfigurationID cfg_id)
int ff_decklink_set_format (AVFormatContext *avctx, int width, int height, int tb_num, int tb_den, decklink_direction_t direction, int num)
int ff_decklink_set_format (AVFormatContext *avctx, decklink_direction_t direction, int num)
int ff_decklink_list_devices (AVFormatContext *avctx)
int ff_decklink_list_formats (AVFormatContext *avctx, decklink_direction_t direction)
void ff_decklink_cleanup (AVFormatContext *avctx)
int ff_decklink_init_device (AVFormatContext *avctx, const char *name)
Macro Definition Documentation
DECKLINK_STR
#define DECKLINK_STR const char *
Definition at line 86 of file decklink_common.cpp.
Referenced by ff_decklink_get_display_name().
DECKLINK_STRDUP
#define DECKLINK_STRDUP av_strdup
Definition at line 87 of file decklink_common.cpp.
Referenced by ff_decklink_get_display_name().
DECKLINK_FREE
#define DECKLINK_FREE (s) free((void *) s)
Definition at line 89 of file decklink_common.cpp.
Referenced by ff_decklink_get_display_name().
DECKLINK_BOOL
#define DECKLINK_BOOL bool
Definition at line 90 of file decklink_common.cpp.
Referenced by ff_decklink_set_format().
Function Documentation
ff_decklink_get_display_name()
HRESULT ff_decklink_get_display_name (IDeckLink * This, const char ** displayName)
Definition at line 93 of file decklink_common.cpp.
Referenced by ff_decklink_init_device(), and ff_decklink_list_devices().
decklink_select_input()
static int decklink_select_input (AVFormatContext * avctx, BMDDeckLinkConfigurationID cfg_id) static
Definition at line 104 of file decklink_common.cpp.
Referenced by ff_decklink_list_formats(), and ff_decklink_set_format().
ff_decklink_set_format() [1/2]
int ff_decklink_set_format (AVFormatContext * avctx, int width, int height, int tb_num, int tb_den, decklink_direction_t direction, int num)
Definition at line 133 of file decklink_common.cpp.
Referenced by decklink_setup_video(), ff_decklink_read_header(), and ff_decklink_set_format().
ff_decklink_set_format() [2/2]
int ff_decklink_set_format (AVFormatContext * avctx, decklink_direction_t direction, int num)
Definition at line 232 of file decklink_common.cpp.
ff_decklink_list_devices()
int ff_decklink_list_devices (AVFormatContext * avctx)
Definition at line 236 of file decklink_common.cpp.
Referenced by ff_decklink_read_header(), and ff_decklink_write_header().
ff_decklink_list_formats()
int ff_decklink_list_formats (AVFormatContext * avctx, decklink_direction_t direction)
Definition at line 256 of file decklink_common.cpp.
Referenced by ff_decklink_read_header(), and ff_decklink_write_header().
ff_decklink_cleanup()
void ff_decklink_cleanup (AVFormatContext * avctx)
Definition at line 306 of file decklink_common.cpp.
Referenced by ff_decklink_init_device(), ff_decklink_read_close(), ff_decklink_read_header(), ff_decklink_write_header(), and ff_decklink_write_trailer().
ff_decklink_init_device()
int ff_decklink_init_device (AVFormatContext * avctx, const char * name)
Definition at line 323 of file decklink_common.cpp.
Referenced by ff_decklink_read_header(), and ff_decklink_write_header().