FFmpeg: libavdevice/decklink_common.h File Reference
decklink_common.h File Reference
#include <DeckLinkAPIVersion.h>
#include "decklink_common_c.h"
Data Structures
struct AVPacketQueue
struct decklink_ctx
Typedefs
typedef uint32_t buffercount_type
Enumerations
enum decklink_direction_t { DIRECTION_IN, DIRECTION_OUT }
Functions
HRESULT ff_decklink_get_display_name (IDeckLink *This, const char **displayName)
int ff_decklink_set_format (AVFormatContext *avctx, int width, int height, int tb_num, int tb_den, decklink_direction_t direction=DIRECTION_OUT, int num=0)
int ff_decklink_set_format (AVFormatContext *avctx, decklink_direction_t direction, int num)
int ff_decklink_list_devices (AVFormatContext *avctx)
int ff_decklink_list_formats (AVFormatContext *avctx, decklink_direction_t direction=DIRECTION_OUT)
void ff_decklink_cleanup (AVFormatContext *avctx)
int ff_decklink_init_device (AVFormatContext *avctx, const char *name)
Variables
static const BMDAudioConnection decklink_audio_connection_map []
static const BMDVideoConnection decklink_video_connection_map []
Typedef Documentation
buffercount_type
typedef uint32_t buffercount_type
Definition at line 107 of file decklink_common.h.
Enumeration Type Documentation
decklink_direction_t
enum decklink_direction_t
Enumerator
DIRECTION_IN
DIRECTION_OUT
Definition at line 97 of file decklink_common.h.
Function Documentation
ff_decklink_get_display_name()
HRESULT ff_decklink_get_display_name (IDeckLink * This, const char ** displayName)
Definition at line 93 of file decklink_common.cpp.
Referenced by ff_decklink_init_device(), and ff_decklink_list_devices().
ff_decklink_set_format() [1/2]
int ff_decklink_set_format (AVFormatContext * avctx, int width, int height, int tb_num, int tb_den, decklink_direction_t direction = DIRECTION_OUT, int num = 0)
Definition at line 133 of file decklink_common.cpp.
Referenced by decklink_setup_video(), ff_decklink_read_header(), and ff_decklink_set_format().
ff_decklink_set_format() [2/2]
int ff_decklink_set_format (AVFormatContext * avctx, decklink_direction_t direction, int num)
Definition at line 232 of file decklink_common.cpp.
ff_decklink_list_devices()
int ff_decklink_list_devices (AVFormatContext * avctx)
Definition at line 236 of file decklink_common.cpp.
Referenced by ff_decklink_read_header(), and ff_decklink_write_header().
ff_decklink_list_formats()
int ff_decklink_list_formats (AVFormatContext * avctx, decklink_direction_t direction = DIRECTION_OUT)
Definition at line 256 of file decklink_common.cpp.
Referenced by ff_decklink_read_header(), and ff_decklink_write_header().
ff_decklink_cleanup()
void ff_decklink_cleanup (AVFormatContext * avctx)
Definition at line 306 of file decklink_common.cpp.
Referenced by ff_decklink_init_device(), ff_decklink_read_close(), ff_decklink_read_header(), ff_decklink_write_header(), and ff_decklink_write_trailer().
ff_decklink_init_device()
int ff_decklink_init_device (AVFormatContext * avctx, const char * name)
Definition at line 323 of file decklink_common.cpp.
Referenced by ff_decklink_read_header(), and ff_decklink_write_header().
Variable Documentation
decklink_audio_connection_map
const BMDAudioConnection decklink_audio_connection_map[] static
Initial value:
= {
    (BMDAudioConnection)0,
    bmdAudioConnectionEmbedded,
    bmdAudioConnectionAESEBU,
    bmdAudioConnectionAnalog,
    bmdAudioConnectionAnalogXLR,
    bmdAudioConnectionAnalogRCA,
    bmdAudioConnectionMicrophone,
}
Definition at line 110 of file decklink_common.h.
Referenced by ff_decklink_read_header().
decklink_video_connection_map
const BMDVideoConnection decklink_video_connection_map[] static
Initial value:
= {
    (BMDVideoConnection)0,
    bmdVideoConnectionSDI,
    bmdVideoConnectionHDMI,
    bmdVideoConnectionOpticalSDI,
    bmdVideoConnectionComponent,
    bmdVideoConnectionComposite,
    bmdVideoConnectionSVideo,
}
Definition at line 120 of file decklink_common.h.
Referenced by ff_decklink_read_header().