FFmpeg: libavdevice/decklink_enc.cpp File Reference
decklink_enc.cpp File Reference
#include <DeckLinkAPI.h>
#include <pthread.h>
#include <semaphore.h>
#include "libavformat/avformat.h"
#include "libavformat/internal.h"
#include "libavutil/imgutils.h"
#include "decklink_common.h"
#include "decklink_enc.h"
Data Structures
class decklink_frame
class decklink_output_callback
Functions
static int decklink_setup_video (AVFormatContext *avctx, AVStream *st)
static int decklink_setup_audio (AVFormatContext *avctx, AVStream *st)
av_cold int ff_decklink_write_trailer (AVFormatContext *avctx)
static int decklink_write_video_packet (AVFormatContext *avctx, AVPacket *pkt)
static int decklink_write_audio_packet (AVFormatContext *avctx, AVPacket *pkt)
av_cold int ff_decklink_write_header (AVFormatContext *avctx)
int ff_decklink_write_packet (AVFormatContext *avctx, AVPacket *pkt)
Function Documentation
decklink_setup_video()
static int decklink_setup_video (AVFormatContext * avctx, AVStream * st) static
Definition at line 91 of file decklink_enc.cpp.
Referenced by ff_decklink_write_header().
decklink_setup_audio()
static int decklink_setup_audio (AVFormatContext * avctx, AVStream * st) static
Definition at line 141 of file decklink_enc.cpp.
Referenced by ff_decklink_write_header().
ff_decklink_write_trailer()
av_cold int ff_decklink_write_trailer (AVFormatContext * avctx)
Definition at line 182 of file decklink_enc.cpp.
decklink_write_video_packet()
static int decklink_write_video_packet (AVFormatContext * avctx, AVPacket * pkt) static
Definition at line 208 of file decklink_enc.cpp.
Referenced by ff_decklink_write_packet().
decklink_write_audio_packet()
static int decklink_write_audio_packet (AVFormatContext * avctx, AVPacket * pkt) static
Definition at line 288 of file decklink_enc.cpp.
Referenced by ff_decklink_write_packet().
ff_decklink_write_header()
av_cold int ff_decklink_write_header (AVFormatContext * avctx)
Definition at line 311 of file decklink_enc.cpp.
ff_decklink_write_packet()
int ff_decklink_write_packet (AVFormatContext * avctx, AVPacket * pkt)
Definition at line 375 of file decklink_enc.cpp.