FFmpeg: libavfilter/deshake_opencl.c File Reference
deshake_opencl.c File Reference
transform input video
#include "libavutil/common.h"
#include "libavutil/dict.h"
#include "libavutil/pixdesc.h"
#include "deshake_opencl.h"
#include "libavutil/opencl_internal.h"
Macros
#define PLANE_NUM 3
#define ROUND_TO_16(a) (((((a) - 1)/16)+1)*16)
Functions
int ff_opencl_transform (AVFilterContext *ctx, int width, int height, int cw, int ch, const float *matrix_y, const float *matrix_uv, enum InterpolateMethod interpolate, enum FillMethod fill, AVFrame *in, AVFrame *out)
int ff_opencl_deshake_init (AVFilterContext *ctx)
void ff_opencl_deshake_uninit (AVFilterContext *ctx)
int ff_opencl_deshake_process_inout_buf (AVFilterContext *ctx, AVFrame *in, AVFrame *out)
Detailed Description
transform input video
Definition in file deshake_opencl.c.
Macro Definition Documentation
PLANE_NUM
#define PLANE_NUM 3
Definition at line 33 of file deshake_opencl.c.
Referenced by ff_opencl_deshake_init().
ROUND_TO_16
#define ROUND_TO_16 (a) (((((a) - 1)/16)+1)*16)
Definition at line 34 of file deshake_opencl.c.
Referenced by ff_opencl_transform().
Function Documentation
ff_opencl_transform()
int ff_opencl_transform (AVFilterContext * ctx, int width, int height, int cw, int ch, const float * matrix_y, const float * matrix_uv, enum InterpolateMethod interpolate, enum FillMethod fill, AVFrame * in, AVFrame * out)
Definition at line 36 of file deshake_opencl.c.
Referenced by init().
ff_opencl_deshake_init()
int ff_opencl_deshake_init (AVFilterContext * ctx)
Definition at line 108 of file deshake_opencl.c.
Referenced by init().
ff_opencl_deshake_uninit()
void ff_opencl_deshake_uninit (AVFilterContext * ctx)
Definition at line 145 of file deshake_opencl.c.
Referenced by uninit().
ff_opencl_deshake_process_inout_buf()
int ff_opencl_deshake_process_inout_buf (AVFilterContext * ctx, AVFrame * in, AVFrame * out)
Definition at line 157 of file deshake_opencl.c.
Referenced by filter_frame().