FFmpeg: libavutil/dict.c File Reference
dict.c File Reference
#include <string.h>
#include "avstring.h"
#include "dict.h"
#include "internal.h"
#include "mem.h"
#include "time_internal.h"
#include "bprint.h"
Data Structures
struct AVDictionary
Functions
int av_dict_count (const AVDictionary *m)
Get number of entries in dictionary.
AVDictionaryEntry * av_dict_get (const AVDictionary *m, const char *key, const AVDictionaryEntry *prev, int flags)
Get a dictionary entry with matching key.
int av_dict_set (AVDictionary **pm, const char *key, const char *value, int flags)
Set the given entry in *pm, overwriting an existing entry.
int av_dict_set_int (AVDictionary **pm, const char *key, int64_t value, int flags)
Convenience wrapper for av_dict_set that converts the value to a string and stores it.
static int parse_key_value_pair (AVDictionary **pm, const char **buf, const char *key_val_sep, const char *pairs_sep, int flags)
int av_dict_parse_string (AVDictionary **pm, const char *str, const char *key_val_sep, const char *pairs_sep, int flags)
Parse the key/value pairs list and add the parsed entries to a dictionary.
void av_dict_free (AVDictionary **pm)
Free all the memory allocated for an AVDictionary struct and all keys and values.
int av_dict_copy (AVDictionary **dst, const AVDictionary *src, int flags)
Copy entries from one AVDictionary struct into another.
int av_dict_get_string (const AVDictionary *m, char **buffer, const char key_val_sep, const char pairs_sep)
Get dictionary entries as a string.
int avpriv_dict_set_timestamp (AVDictionary **dict, const char *key, int64_t timestamp)
Set a dictionary value to an ISO-8601 compliant timestamp string.
Function Documentation
parse_key_value_pair()
static int parse_key_value_pair (AVDictionary ** pm, const char ** buf, const char * key_val_sep, const char * pairs_sep, int flags) static
Definition at line 156 of file dict.c.
Referenced by av_dict_parse_string().
avpriv_dict_set_timestamp()
int avpriv_dict_set_timestamp (AVDictionary ** dict, const char * key, int64_t timestamp)
Set a dictionary value to an ISO-8601 compliant timestamp string.
Parameters
s AVFormatContext
key metadata key
timestamp unix timestamp in microseconds
Returns
<0 on error
Definition at line 258 of file dict.c.
Referenced by avpriv_mirror(), ff_standardize_creation_time(), matroska_metadata_creation_time(), and mov_metadata_creation_time().