FFmpeg: libavcodec/diracdsp.c File Reference
diracdsp.c File Reference
#include "avcodec.h"
#include "diracdsp.h"
Macros
#define FILTER(src, stride)
#define PIXOP_BILINEAR(PFX, OP, WIDTH)
#define OP_PUT(dst, val) (dst) = (val)
#define OP_AVG(dst, val) (dst) = (((dst) + (val) + 1)>>1)
#define op_scale1(x) block[x] = av_clip_uint8((block[x]*weight + (1<<(log2_denom-1))) >> log2_denom)
#define op_scale2(x) dst[x] = av_clip_uint8((src[x]*weights + dst[x]*weightd + (1<<(log2_denom-1))) >> log2_denom)
#define DIRAC_WEIGHT(W)
#define ADD_OBMC(xblen)
#define PUT_SIGNED_RECT_CLAMPED(PX)
#define DEQUANT_SUBBAND(PX)
#define PIXFUNC(PFX, WIDTH)
Functions
static void dirac_hpel_filter (uint8_t *dsth, uint8_t *dstv, uint8_t *dstc, const uint8_t *src, int stride, int width, int height)
static void put_signed_rect_clamped_8bit_c (uint8_t *dst, int dst_stride, const uint8_t *_src, int src_stride, int width, int height)
static void add_rect_clamped_c (uint8_t *dst, const uint16_t *src, int stride, const int16_t *idwt, int idwt_stride, int width, int height)
av_cold void ff_diracdsp_init (DiracDSPContext *c)
Macro Definition Documentation
FILTER
#define FILTER (src, stride)
Value:
((21*((src)[ 0*stride] + (src)[1*stride])                   \
      -7*((src)[-1*stride] + (src)[2*stride])                   \
      +3*((src)[-2*stride] + (src)[3*stride])                   \
      -1*((src)[-3*stride] + (src)[4*stride]) + 16) >> 5)
Definition at line 24 of file diracdsp.c.
Referenced by dirac_hpel_filter().
PIXOP_BILINEAR
#define PIXOP_BILINEAR (PFX, OP, WIDTH)
Value:
static void ff_ ## PFX ## _dirac_pixels ## WIDTH ## _bilinear_c(uint8_t *dst, const uint8_t *src[5], int stride, int h) \
    {                                                                   \
        int x;                                                          \
        const uint8_t *s0 = src[0];                                     \
        const uint8_t *s1 = src[1];                                     \
        const uint8_t *s2 = src[2];                                     \
        const uint8_t *s3 = src[3];                                     \
        const uint8_t *w  = src[4];                                     \
                                                                        \
        while (h--) {                                                   \
            for (x = 0; x < WIDTH; x++) {                               \
                OP(dst[x], (s0[x]*w[0] + s1[x]*w[1] + s2[x]*w[2] + s3[x]*w[3] + 8) >> 4); \
            }                                                           \
                                                                        \
            dst += stride;                                              \
            s0 += stride;                                               \
            s1 += stride;                                               \
            s2 += stride;                                               \
            s3 += stride;                                               \
        }                                                               \
    }
Definition at line 52 of file diracdsp.c.
OP_PUT
#define OP_PUT (dst, val) (dst) = (val)
Definition at line 75 of file diracdsp.c.
OP_AVG
#define OP_AVG (dst, val) (dst) = (((dst) + (val) + 1)>>1)
Definition at line 76 of file diracdsp.c.
op_scale1
#define op_scale1 (x) block[x] = av_clip_uint8((block[x]*weight + (1<<(log2_denom-1))) >> log2_denom)
Definition at line 85 of file diracdsp.c.
op_scale2
#define op_scale2 (x) dst[x] = av_clip_uint8((src[x]*weights + dst[x]*weightd + (1<<(log2_denom-1))) >> log2_denom)
Definition at line 86 of file diracdsp.c.
DIRAC_WEIGHT
#define DIRAC_WEIGHT (W)
Value:
static void weight_dirac_pixels ## W ## _c(uint8_t *block, int stride, int log2_denom, \
                                               int weight, int h) {     \
        int x;                                                          \
        while (h--) {                                                   \
            for (x = 0; x < W; x++) {                                   \
                op_scale1(x);                                           \
                op_scale1(x+1);                                         \
            }                                                           \
            block += stride;                                            \
        }                                                               \
    }                                                                   \
    static void biweight_dirac_pixels ## W ## _c(uint8_t *dst, const uint8_t *src, int stride, int log2_denom, \
                                                 int weightd, int weights, int h) { \
        int x;                                                          \
        while (h--) {                                                   \
            for (x = 0; x < W; x++) {                                   \
                op_scale2(x);                                           \
                op_scale2(x+1);                                         \
            }                                                           \
            dst += stride;                                              \
            src += stride;                                              \
        }                                                               \
    }
Definition at line 88 of file diracdsp.c.
ADD_OBMC
#define ADD_OBMC (xblen)
Value:
static void add_obmc ## xblen ## _c(uint16_t *dst, const uint8_t *src, int stride, \
                                        const uint8_t *obmc_weight, int yblen) \
    {                                                                   \
        int x;                                                          \
        while (yblen--) {                                               \
            for (x = 0; x < xblen; x += 2) {                            \
                dst[x  ] += src[x  ] * obmc_weight[x  ];                \
                dst[x+1] += src[x+1] * obmc_weight[x+1];                \
            }                                                           \
            dst += stride;                                              \
            src += stride;                                              \
            obmc_weight += 32;                                          \
        }                                                               \
    }
Definition at line 117 of file diracdsp.c.
PUT_SIGNED_RECT_CLAMPED
#define PUT_SIGNED_RECT_CLAMPED (PX)
Value:
static void put_signed_rect_clamped_ ## PX ## bit_c(uint8_t *_dst, int dst_stride, const uint8_t *_src, \
                                                  int src_stride, int width, int height)                \
{                                                                                                       \
    int x, y;                                                                                           \
    uint16_t *dst = (uint16_t *)_dst;                                                                   \
    int32_t *src = (int32_t *)_src;                                                                     \
    for (y = 0; y < height; y++) {                                                                      \
        for (x = 0; x < width; x+=4) {                                                                  \
            dst[x  ] = av_clip_uintp2(src[x  ] + (1 << (PX - 1)), PX);                                  \
            dst[x+1] = av_clip_uintp2(src[x+1] + (1 << (PX - 1)), PX);                                  \
            dst[x+2] = av_clip_uintp2(src[x+2] + (1 << (PX - 1)), PX);                                  \
            dst[x+3] = av_clip_uintp2(src[x+3] + (1 << (PX - 1)), PX);                                  \
        }                                                                                               \
        dst += dst_stride >> 1;                                                                         \
        src += src_stride >> 2;                                                                         \
    }                                                                                                   \
}
Definition at line 153 of file diracdsp.c.
DEQUANT_SUBBAND
#define DEQUANT_SUBBAND (PX)
Value:
static void dequant_subband_ ## PX ## _c(uint8_t *src, uint8_t *dst, ptrdiff_t stride,     \
                                         const int qf, const int qs, int tot_v, int tot_h) \
{                                                                                          \
    int i, y;                                                                              \
    for (y = 0; y < tot_v; y++) {                                                          \
        PX c, sign, *src_r = (PX *)src, *dst_r = (PX *)dst;                                \
        for (i = 0; i < tot_h; i++) {                                                      \
            c = *src_r++;                                                                  \
            sign = FFSIGN(c)*(!!c);                                                        \
            c = (FFABS(c)*qf + qs) >> 2;                                                   \
            *dst_r++ = c*sign;                                                             \
        }                                                                                  \
        src += tot_h << (sizeof(PX) >> 1);                                                 \
        dst += stride;                                                                     \
    }                                                                                      \
}
Definition at line 192 of file diracdsp.c.
PIXFUNC
#define PIXFUNC (PFX, WIDTH)
Value:
c->PFX ## _dirac_pixels_tab[WIDTH>>4][0] = ff_ ## PFX ## _dirac_pixels ## WIDTH ## _c; \
    c->PFX ## _dirac_pixels_tab[WIDTH>>4][1] = ff_ ## PFX ## _dirac_pixels ## WIDTH ## _l2_c; \
    c->PFX ## _dirac_pixels_tab[WIDTH>>4][2] = ff_ ## PFX ## _dirac_pixels ## WIDTH ## _l4_c; \
    c->PFX ## _dirac_pixels_tab[WIDTH>>4][3] = ff_ ## PFX ## _dirac_pixels ## WIDTH ## _bilinear_c
Definition at line 213 of file diracdsp.c.
Referenced by ff_diracdsp_init().
Function Documentation
dirac_hpel_filter()
static void dirac_hpel_filter (uint8_t * dsth, uint8_t * dstv, uint8_t * dstc, const uint8_t * src, int stride, int width, int height) static
Definition at line 30 of file diracdsp.c.
Referenced by ff_diracdsp_init().
put_signed_rect_clamped_8bit_c()
static void put_signed_rect_clamped_8bit_c (uint8_t * dst, int dst_stride, const uint8_t * _src, int src_stride, int width, int height) static
Definition at line 137 of file diracdsp.c.
Referenced by ff_diracdsp_init().
add_rect_clamped_c()
static void add_rect_clamped_c (uint8_t * dst, const uint16_t * src, int stride, const int16_t * idwt, int idwt_stride, int width, int height) static
Definition at line 175 of file diracdsp.c.
Referenced by ff_diracdsp_init().
ff_diracdsp_init()
av_cold void ff_diracdsp_init (DiracDSPContext * c)
Definition at line 219 of file diracdsp.c.
Referenced by dirac_decode_init().