FFmpeg: libavcodec/dirac_dwt_template.c File Reference
dirac_dwt_template.c File Reference
Functions
static void RENAME() vertical_compose53iL0 (uint8_t *_b0, uint8_t *_b1, uint8_t *_b2, int width)
static av_always_inline void RENAME() interleave (TYPE *dst, TYPE *src0, TYPE *src1, int w2, int add, int shift)
static void RENAME() horizontal_compose_dirac53i (uint8_t *_b, uint8_t *_temp, int w)
static void RENAME() horizontal_compose_dd97i (uint8_t *_b, uint8_t *_tmp, int w)
static void RENAME() horizontal_compose_dd137i (uint8_t *_b, uint8_t *_tmp, int w)
static av_always_inline void RENAME() horizontal_compose_haari (TYPE *b, TYPE *temp, int w, int shift)
static void RENAME() horizontal_compose_haar0i (uint8_t *_b, uint8_t *_temp, int w)
static void RENAME() horizontal_compose_haar1i (uint8_t *_b, uint8_t *_temp, int w)
static void RENAME() horizontal_compose_fidelityi (uint8_t *_b, uint8_t *_tmp, int w)
static void RENAME() horizontal_compose_daub97i (uint8_t *_b, uint8_t *_temp, int w)
static void RENAME() vertical_compose_dirac53iH0 (uint8_t *_b0, uint8_t *_b1, uint8_t *_b2, int width)
static void RENAME() vertical_compose_dd97iH0 (uint8_t *_b0, uint8_t *_b1, uint8_t *_b2, uint8_t *_b3, uint8_t *_b4, int width)
static void RENAME() vertical_compose_dd137iL0 (uint8_t *_b0, uint8_t *_b1, uint8_t *_b2, uint8_t *_b3, uint8_t *_b4, int width)
static void RENAME() vertical_compose_haar (uint8_t *_b0, uint8_t *_b1, int width)
static void RENAME() vertical_compose_fidelityiH0 (uint8_t *_dst, uint8_t *_b[8], int width)
static void RENAME() vertical_compose_fidelityiL0 (uint8_t *_dst, uint8_t *_b[8], int width)
static void RENAME() vertical_compose_daub97iH0 (uint8_t *_b0, uint8_t *_b1, uint8_t *_b2, int width)
static void RENAME() vertical_compose_daub97iH1 (uint8_t *_b0, uint8_t *_b1, uint8_t *_b2, int width)
static void RENAME() vertical_compose_daub97iL0 (uint8_t *_b0, uint8_t *_b1, uint8_t *_b2, int width)
static void RENAME() vertical_compose_daub97iL1 (uint8_t *_b0, uint8_t *_b1, uint8_t *_b2, int width)
static void RENAME() spatial_compose_dd97i_dy (DWTContext *d, int level, int width, int height, int stride)
static void RENAME() spatial_compose_dirac53i_dy (DWTContext *d, int level, int width, int height, int stride)
static void RENAME() spatial_compose_dd137i_dy (DWTContext *d, int level, int width, int height, int stride)
static void RENAME() spatial_compose_haari_dy (DWTContext *d, int level, int width, int height, int stride)
static void RENAME() spatial_compose_fidelity (DWTContext *d, int level, int width, int height, int stride)
static void RENAME() spatial_compose_daub97i_dy (DWTContext *d, int level, int width, int height, int stride)
static void RENAME() spatial_compose97i_init (DWTCompose *cs, uint8_t *buffer, int height, int stride)
static void RENAME() spatial_compose53i_init (DWTCompose *cs, uint8_t *buffer, int height, int stride)
static void RENAME() spatial_compose_dd97i_init (DWTCompose *cs, uint8_t *buffer, int height, int stride)
static void RENAME() spatial_compose_dd137i_init (DWTCompose *cs, uint8_t *buffer, int height, int stride)
static int RENAME() ff_spatial_idwt_init (DWTContext *d, enum dwt_type type)
Function Documentation
vertical_compose53iL0()
static void RENAME() vertical_compose53iL0 (uint8_t * _b0, uint8_t * _b1, uint8_t * _b2, int width) static
Definition at line 44 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
interleave()
static av_always_inline void RENAME() interleave (TYPE * dst, TYPE * src0, TYPE * src1, int w2, int add, int shift) static
Definition at line 55 of file dirac_dwt_template.c.
Referenced by advance_line(), avfilter_register_all(), decode_frame(), ff_rtsp_open_transport_ctx(), horizontal_compose_dirac53i(), horizontal_compose_fidelityi(), horizontal_compose_haari(), and request_frame().
horizontal_compose_dirac53i()
static void RENAME() horizontal_compose_dirac53i (uint8_t * _b, uint8_t * _temp, int w) static
Definition at line 65 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
horizontal_compose_dd97i()
static void RENAME() horizontal_compose_dd97i (uint8_t * _b, uint8_t * _tmp, int w) static
Definition at line 82 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
horizontal_compose_dd137i()
static void RENAME() horizontal_compose_dd137i (uint8_t * _b, uint8_t * _tmp, int w) static
Definition at line 103 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
horizontal_compose_haari()
static av_always_inline void RENAME() horizontal_compose_haari (TYPE * b, TYPE * temp, int w, int shift) static
Definition at line 126 of file dirac_dwt_template.c.
Referenced by horizontal_compose_haar0i(), and horizontal_compose_haar1i().
horizontal_compose_haar0i()
static void RENAME() horizontal_compose_haar0i (uint8_t * _b, uint8_t * _temp, int w) static
Definition at line 140 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
horizontal_compose_haar1i()
static void RENAME() horizontal_compose_haar1i (uint8_t * _b, uint8_t * _temp, int w) static
Definition at line 147 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
horizontal_compose_fidelityi()
static void RENAME() horizontal_compose_fidelityi (uint8_t * _b, uint8_t * _tmp, int w) static
Definition at line 154 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
horizontal_compose_daub97i()
static void RENAME() horizontal_compose_daub97i (uint8_t * _b, uint8_t * _temp, int w) static
Definition at line 177 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
vertical_compose_dirac53iH0()
static void RENAME() vertical_compose_dirac53iH0 (uint8_t * _b0, uint8_t * _b1, uint8_t * _b2, int width) static
Definition at line 204 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
vertical_compose_dd97iH0()
static void RENAME() vertical_compose_dd97iH0 (uint8_t * _b0, uint8_t * _b1, uint8_t * _b2, uint8_t * _b3, uint8_t * _b4, int width) static
Definition at line 216 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
vertical_compose_dd137iL0()
static void RENAME() vertical_compose_dd137iL0 (uint8_t * _b0, uint8_t * _b1, uint8_t * _b2, uint8_t * _b3, uint8_t * _b4, int width) static
Definition at line 230 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
vertical_compose_haar()
static void RENAME() vertical_compose_haar (uint8_t * _b0, uint8_t * _b1, int width) static
Definition at line 244 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
vertical_compose_fidelityiH0()
static void RENAME() vertical_compose_fidelityiH0 (uint8_t * _dst, uint8_t * _b[8], int width) static
Definition at line 256 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
vertical_compose_fidelityiL0()
static void RENAME() vertical_compose_fidelityiL0 (uint8_t * _dst, uint8_t * _b[8], int width) static
Definition at line 273 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
vertical_compose_daub97iH0()
static void RENAME() vertical_compose_daub97iH0 (uint8_t * _b0, uint8_t * _b1, uint8_t * _b2, int width) static
Definition at line 291 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
vertical_compose_daub97iH1()
static void RENAME() vertical_compose_daub97iH1 (uint8_t * _b0, uint8_t * _b1, uint8_t * _b2, int width) static
Definition at line 303 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
vertical_compose_daub97iL0()
static void RENAME() vertical_compose_daub97iL0 (uint8_t * _b0, uint8_t * _b1, uint8_t * _b2, int width) static
Definition at line 315 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
vertical_compose_daub97iL1()
static void RENAME() vertical_compose_daub97iL1 (uint8_t * _b0, uint8_t * _b1, uint8_t * _b2, int width) static
Definition at line 327 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
spatial_compose_dd97i_dy()
static void RENAME() spatial_compose_dd97i_dy (DWTContext * d, int level, int width, int height, int stride) static
Definition at line 339 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
spatial_compose_dirac53i_dy()
static void RENAME() spatial_compose_dirac53i_dy (DWTContext * d, int level, int width, int height, int stride) static
Definition at line 363 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
spatial_compose_dd137i_dy()
static void RENAME() spatial_compose_dd137i_dy (DWTContext * d, int level, int width, int height, int stride) static
Definition at line 385 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
spatial_compose_haari_dy()
static void RENAME() spatial_compose_haari_dy (DWTContext * d, int level, int width, int height, int stride) static
Definition at line 410 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
spatial_compose_fidelity()
static void RENAME() spatial_compose_fidelity (DWTContext * d, int level, int width, int height, int stride) static
Definition at line 426 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
spatial_compose_daub97i_dy()
static void RENAME() spatial_compose_daub97i_dy (DWTContext * d, int level, int width, int height, int stride) static
Definition at line 451 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
spatial_compose97i_init()
static void RENAME() spatial_compose97i_init (DWTCompose * cs, uint8_t * buffer, int height, int stride) static
Definition at line 479 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
spatial_compose53i_init()
static void RENAME() spatial_compose53i_init (DWTCompose * cs, uint8_t * buffer, int height, int stride) static
Definition at line 488 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
spatial_compose_dd97i_init()
static void RENAME() spatial_compose_dd97i_init (DWTCompose * cs, uint8_t * buffer, int height, int stride) static
Definition at line 495 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
spatial_compose_dd137i_init()
static void RENAME() spatial_compose_dd137i_init (DWTCompose * cs, uint8_t * buffer, int height, int stride) static
Definition at line 506 of file dirac_dwt_template.c.
Referenced by ff_spatial_idwt_init().
ff_spatial_idwt_init()
static int RENAME() ff_spatial_idwt_init (DWTContext * d, enum dwt_type type) static
Definition at line 519 of file dirac_dwt_template.c.