FFmpeg: libavcodec/dirac_parser.c File Reference
dirac_parser.c File Reference
Dirac Parser.
#include <string.h>
#include "libavutil/intreadwrite.h"
#include "libavutil/mem.h"
#include "parser.h"
Data Structures
struct DiracParseContext
Find the end of the current frame in the bitstream.
struct DiracParseUnit
Macros
#define DIRAC_PARSE_INFO_PREFIX 0x42424344
Functions
static int find_frame_end (DiracParseContext *pc, const uint8_t *buf, int buf_size)
static int unpack_parse_unit (DiracParseUnit *pu, DiracParseContext *pc, int offset)
static int dirac_combine_frame (AVCodecParserContext *s, AVCodecContext *avctx, int next, const uint8_t **buf, int *buf_size)
static int dirac_parse (AVCodecParserContext *s, AVCodecContext *avctx, const uint8_t **poutbuf, int *poutbuf_size, const uint8_t *buf, int buf_size)
static void dirac_parse_close (AVCodecParserContext *s)
Variables
AVCodecParser ff_dirac_parser
Detailed Description
Dirac Parser.
Author
Marco Gerards marco.nosp@m.@gnu.nosp@m..org
Definition in file dirac_parser.c.
Macro Definition Documentation
DIRAC_PARSE_INFO_PREFIX
#define DIRAC_PARSE_INFO_PREFIX 0x42424344
Definition at line 37 of file dirac_parser.c.
Referenced by find_frame_end().
Function Documentation
find_frame_end()
static int find_frame_end (DiracParseContext * pc, const uint8_t * buf, int buf_size) static
Definition at line 56 of file dirac_parser.c.
Referenced by dirac_parse().
unpack_parse_unit()
static int unpack_parse_unit (DiracParseUnit * pu, DiracParseContext * pc, int offset) static
Definition at line 100 of file dirac_parser.c.
Referenced by dirac_combine_frame().
dirac_combine_frame()
static int dirac_combine_frame (AVCodecParserContext * s, AVCodecContext * avctx, int next, const uint8_t ** buf, int * buf_size) static
Definition at line 137 of file dirac_parser.c.
Referenced by dirac_parse().
dirac_parse()
static int dirac_parse (AVCodecParserContext * s, AVCodecContext * avctx, const uint8_t ** poutbuf, int * poutbuf_size, const uint8_t * buf, int buf_size) static
Definition at line 238 of file dirac_parser.c.
dirac_parse_close()
static void dirac_parse_close (AVCodecParserContext * s) static
Definition at line 268 of file dirac_parser.c.
Variable Documentation
ff_dirac_parser
AVCodecParser ff_dirac_parser
Initial value:
= {
    .codec_ids      = { AV_CODEC_ID_DIRAC },
    .priv_data_size = sizeof(DiracParseContext),
    .parser_parse   = dirac_parse,
    .parser_close   = dirac_parse_close,
}
Definition at line 276 of file dirac_parser.c.