FFmpeg: libavcodec/x86/diracdsp_init.c File Reference
diracdsp_init.c File Reference
#include "libavutil/x86/cpu.h"
#include "libavcodec/diracdsp.h"
#include "fpel.h"
Macros
#define HPEL_FILTER(MMSIZE, EXT)
#define PIXFUNC(PFX, IDX, EXT) do {} while (0)
Functions
DECL_DIRAC_PIXOP (put, mmx)
DECL_DIRAC_PIXOP (avg, mmx)
DECL_DIRAC_PIXOP (avg, mmxext)
void ff_put_dirac_pixels16_sse2 (uint8_t *dst, const uint8_t *src[5], int stride, int h)
void ff_avg_dirac_pixels16_sse2 (uint8_t *dst, const uint8_t *src[5], int stride, int h)
void ff_put_dirac_pixels32_sse2 (uint8_t *dst, const uint8_t *src[5], int stride, int h)
void ff_avg_dirac_pixels32_sse2 (uint8_t *dst, const uint8_t *src[5], int stride, int h)
void ff_add_rect_clamped_mmx (uint8_t *, const uint16_t *, int, const int16_t *, int, int, int)
void ff_add_rect_clamped_sse2 (uint8_t *, const uint16_t *, int, const int16_t *, int, int, int)
void ff_add_dirac_obmc8_mmx (uint16_t *dst, const uint8_t *src, int stride, const uint8_t *obmc_weight, int yblen)
void ff_add_dirac_obmc16_mmx (uint16_t *dst, const uint8_t *src, int stride, const uint8_t *obmc_weight, int yblen)
void ff_add_dirac_obmc32_mmx (uint16_t *dst, const uint8_t *src, int stride, const uint8_t *obmc_weight, int yblen)
void ff_add_dirac_obmc16_sse2 (uint16_t *dst, const uint8_t *src, int stride, const uint8_t *obmc_weight, int yblen)
void ff_add_dirac_obmc32_sse2 (uint16_t *dst, const uint8_t *src, int stride, const uint8_t *obmc_weight, int yblen)
void ff_put_rect_clamped_mmx (uint8_t *dst, int dst_stride, const int16_t *src, int src_stride, int width, int height)
void ff_put_rect_clamped_sse2 (uint8_t *dst, int dst_stride, const int16_t *src, int src_stride, int width, int height)
void ff_put_signed_rect_clamped_mmx (uint8_t *dst, int dst_stride, const int16_t *src, int src_stride, int width, int height)
void ff_put_signed_rect_clamped_sse2 (uint8_t *dst, int dst_stride, const int16_t *src, int src_stride, int width, int height)
void ff_put_signed_rect_clamped_10_sse4 (uint8_t *dst, int dst_stride, const uint8_t *src, int src_stride, int width, int height)
void ff_dequant_subband_32_sse4 (uint8_t *src, uint8_t *dst, ptrdiff_t stride, const int qf, const int qs, int tot_v, int tot_h)
void ff_diracdsp_init_x86 (DiracDSPContext *c)
Macro Definition Documentation
HPEL_FILTER
#define HPEL_FILTER (MMSIZE, EXT)
Value:
void dirac_hpel_filter_ ## EXT(uint8_t *dsth, uint8_t *dstv, uint8_t *dstc,              \
                                   const uint8_t *src, int stride, int width, int height);
Definition at line 143 of file diracdsp_init.c.
PIXFUNC
#define PIXFUNC (PFX, IDX, EXT) do {} while (0)
Definition at line 147 of file diracdsp_init.c.
Referenced by ff_diracdsp_init_x86().
Function Documentation
DECL_DIRAC_PIXOP() [1/3]
DECL_DIRAC_PIXOP (put , mmx)
DECL_DIRAC_PIXOP() [2/3]
DECL_DIRAC_PIXOP (avg , mmx)
DECL_DIRAC_PIXOP() [3/3]
DECL_DIRAC_PIXOP (avg , mmxext)
ff_put_dirac_pixels16_sse2()
void ff_put_dirac_pixels16_sse2 (uint8_t * dst, const uint8_t * src[5], int stride, int h)
Referenced by ff_diracdsp_init_x86().
ff_avg_dirac_pixels16_sse2()
void ff_avg_dirac_pixels16_sse2 (uint8_t * dst, const uint8_t * src[5], int stride, int h)
Referenced by ff_diracdsp_init_x86().
ff_put_dirac_pixels32_sse2()
void ff_put_dirac_pixels32_sse2 (uint8_t * dst, const uint8_t * src[5], int stride, int h)
Referenced by ff_diracdsp_init_x86().
ff_avg_dirac_pixels32_sse2()
void ff_avg_dirac_pixels32_sse2 (uint8_t * dst, const uint8_t * src[5], int stride, int h)
Referenced by ff_diracdsp_init_x86().
ff_add_rect_clamped_mmx()
void ff_add_rect_clamped_mmx (uint8_t * , const uint16_t * , int , const int16_t * , int , int , int)
Referenced by ff_diracdsp_init_x86().
ff_add_rect_clamped_sse2()
void ff_add_rect_clamped_sse2 (uint8_t * , const uint16_t * , int , const int16_t * , int , int , int)
Referenced by ff_diracdsp_init_x86().
ff_add_dirac_obmc8_mmx()
void ff_add_dirac_obmc8_mmx (uint16_t * dst, const uint8_t * src, int stride, const uint8_t * obmc_weight, int yblen)
Referenced by ff_diracdsp_init_x86().
ff_add_dirac_obmc16_mmx()
void ff_add_dirac_obmc16_mmx (uint16_t * dst, const uint8_t * src, int stride, const uint8_t * obmc_weight, int yblen)
Referenced by ff_diracdsp_init_x86().
ff_add_dirac_obmc32_mmx()
void ff_add_dirac_obmc32_mmx (uint16_t * dst, const uint8_t * src, int stride, const uint8_t * obmc_weight, int yblen)
Referenced by ff_diracdsp_init_x86().
ff_add_dirac_obmc16_sse2()
void ff_add_dirac_obmc16_sse2 (uint16_t * dst, const uint8_t * src, int stride, const uint8_t * obmc_weight, int yblen)
Referenced by ff_diracdsp_init_x86().
ff_add_dirac_obmc32_sse2()
void ff_add_dirac_obmc32_sse2 (uint16_t * dst, const uint8_t * src, int stride, const uint8_t * obmc_weight, int yblen)
Referenced by ff_diracdsp_init_x86().
ff_put_rect_clamped_mmx()
void ff_put_rect_clamped_mmx (uint8_t * dst, int dst_stride, const int16_t * src, int src_stride, int width, int height)
ff_put_rect_clamped_sse2()
void ff_put_rect_clamped_sse2 (uint8_t * dst, int dst_stride, const int16_t * src, int src_stride, int width, int height)
ff_put_signed_rect_clamped_mmx()
void ff_put_signed_rect_clamped_mmx (uint8_t * dst, int dst_stride, const int16_t * src, int src_stride, int width, int height)
Referenced by ff_diracdsp_init_x86().
ff_put_signed_rect_clamped_sse2()
void ff_put_signed_rect_clamped_sse2 (uint8_t * dst, int dst_stride, const int16_t * src, int src_stride, int width, int height)
Referenced by ff_diracdsp_init_x86().
ff_put_signed_rect_clamped_10_sse4()
void ff_put_signed_rect_clamped_10_sse4 (uint8_t * dst, int dst_stride, const uint8_t * src, int src_stride, int width, int height)
Referenced by ff_diracdsp_init_x86().
ff_dequant_subband_32_sse4()
void ff_dequant_subband_32_sse4 (uint8_t * src, uint8_t * dst, ptrdiff_t stride, const int qf, const int qs, int tot_v, int tot_h)
Referenced by ff_diracdsp_init_x86().
ff_diracdsp_init_x86()
void ff_diracdsp_init_x86 (DiracDSPContext * c)
Definition at line 156 of file diracdsp_init.c.
Referenced by ff_diracdsp_init().