FFmpeg: libavcodec/dirac_vlc.h File Reference
dirac_vlc.h File Reference
#include "libavutil/avutil.h"
Data Structures
struct DiracGolombLUT
Macros
#define LUT_BITS 8
Typedefs
typedef uint64_t residual
Functions
av_cold int ff_dirac_golomb_reader_init (DiracGolombLUT **lut_ctx)
int ff_dirac_golomb_read_32bit (DiracGolombLUT *lut_ctx, const uint8_t *buf, int bytes, uint8_t *dst, int coeffs)
int ff_dirac_golomb_read_16bit (DiracGolombLUT *lut_ctx, const uint8_t *buf, int bytes, uint8_t *_dst, int coeffs)
av_cold void ff_dirac_golomb_reader_end (DiracGolombLUT **lut_ctx)
Macro Definition Documentation
LUT_BITS
#define LUT_BITS 8
Definition at line 31 of file dirac_vlc.h.
Typedef Documentation
residual
typedef uint64_t residual
Definition at line 29 of file dirac_vlc.h.
Function Documentation
ff_dirac_golomb_reader_init()
av_cold int ff_dirac_golomb_reader_init (DiracGolombLUT ** lut_ctx)
Definition at line 227 of file dirac_vlc.c.
Referenced by dirac_decode_init().
ff_dirac_golomb_read_32bit()
int ff_dirac_golomb_read_32bit (DiracGolombLUT * lut_ctx, const uint8_t * buf, int bytes, uint8_t * dst, int coeffs)
Definition at line 42 of file dirac_vlc.c.
Referenced by decode_hq_slice().
ff_dirac_golomb_read_16bit()
int ff_dirac_golomb_read_16bit (DiracGolombLUT * lut_ctx, const uint8_t * buf, int bytes, uint8_t * _dst, int coeffs)
Definition at line 82 of file dirac_vlc.c.
Referenced by decode_hq_slice().
ff_dirac_golomb_reader_end()
av_cold void ff_dirac_golomb_reader_end (DiracGolombLUT ** lut_ctx)
Definition at line 244 of file dirac_vlc.c.
Referenced by dirac_decode_end().