FFmpeg: libavcodec/dirac_arith.c File Reference
dirac_arith.c File Reference
Arithmetic decoder for Dirac.
#include "dirac_arith.h"
Functions
void ff_dirac_init_arith_decoder (DiracArith *c, GetBitContext *gb, int length)
Variables
const uint16_t ff_dirac_prob [256]
const uint8_t ff_dirac_next_ctx [DIRAC_CTX_COUNT]
int16_t ff_dirac_prob_branchless [256][2]
Detailed Description
Arithmetic decoder for Dirac.
Author
Marco Gerards marco.nosp@m.@gnu.nosp@m..org
Definition in file dirac_arith.c.
Function Documentation
ff_dirac_init_arith_decoder()
void ff_dirac_init_arith_decoder (DiracArith * c, GetBitContext * gb, int length)
Definition at line 86 of file dirac_arith.c.
Referenced by decode_subband_internal(), dirac_get_arith_int(), and dirac_unpack_block_motion_data().
Variable Documentation
ff_dirac_prob
const uint16_t ff_dirac_prob[256]
Definition at line 31 of file dirac_arith.c.
Referenced by ff_dirac_init_arith_decoder().
ff_dirac_next_ctx
const uint8_t ff_dirac_next_ctx[DIRAC_CTX_COUNT]
Initial value:
= {
    [CTX_ZPZN_F1]   = CTX_ZP_F2,
    [CTX_ZPNN_F1]   = CTX_ZP_F2,
    [CTX_ZP_F2]     = CTX_ZP_F3,
    [CTX_ZP_F3]     = CTX_ZP_F4,
    [CTX_ZP_F4]     = CTX_ZP_F5,
    [CTX_ZP_F5]     = CTX_ZP_F6,
    [CTX_ZP_F6]     = CTX_ZP_F6,
    [CTX_NPZN_F1]   = CTX_NP_F2,
    [CTX_NPNN_F1]   = CTX_NP_F2,
    [CTX_NP_F2]     = CTX_NP_F3,
    [CTX_NP_F3]     = CTX_NP_F4,
    [CTX_NP_F4]     = CTX_NP_F5,
    [CTX_NP_F5]     = CTX_NP_F6,
    [CTX_NP_F6]     = CTX_NP_F6,
    [CTX_DELTA_Q_F] = CTX_DELTA_Q_F,
}
Definition at line 66 of file dirac_arith.c.
Referenced by dirac_get_arith_uint().
ff_dirac_prob_branchless
int16_t ff_dirac_prob_branchless[256][2]
Definition at line 84 of file dirac_arith.c.
Referenced by dirac_get_arith_bit(), and ff_dirac_init_arith_decoder().