FFmpeg: libavresample/x86/dither_init.c File Reference
dither_init.c File Reference
#include "config.h"
#include "libavutil/cpu.h"
#include "libavutil/x86/cpu.h"
#include "libavresample/dither.h"
Functions
void ff_quantize_sse2 (int16_t *dst, const float *src, float *dither, int len)
void ff_dither_int_to_float_rectangular_sse2 (float *dst, int *src, int len)
void ff_dither_int_to_float_rectangular_avx (float *dst, int *src, int len)
void ff_dither_int_to_float_triangular_sse2 (float *dst, int *src0, int len)
void ff_dither_int_to_float_triangular_avx (float *dst, int *src0, int len)
av_cold void ff_dither_init_x86 (DitherDSPContext *ddsp, enum AVResampleDitherMethod method)
Function Documentation
ff_quantize_sse2()
void ff_quantize_sse2 (int16_t * dst, const float * src, float * dither, int len)
Referenced by ff_dither_init_x86().
ff_dither_int_to_float_rectangular_sse2()
void ff_dither_int_to_float_rectangular_sse2 (float * dst, int * src, int len)
Referenced by ff_dither_init_x86().
ff_dither_int_to_float_rectangular_avx()
void ff_dither_int_to_float_rectangular_avx (float * dst, int * src, int len)
Referenced by ff_dither_init_x86().
ff_dither_int_to_float_triangular_sse2()
void ff_dither_int_to_float_triangular_sse2 (float * dst, int * src0, int len)
Referenced by ff_dither_init_x86().
ff_dither_int_to_float_triangular_avx()
void ff_dither_int_to_float_triangular_avx (float * dst, int * src0, int len)
Referenced by ff_dither_init_x86().
ff_dither_init_x86()
av_cold void ff_dither_init_x86 (DitherDSPContext * ddsp, enum AVResampleDitherMethod method)
Definition at line 34 of file dither_init.c.
Referenced by dither_init().