FFmpeg: libavcodec/dnxhddata.h File Reference
dnxhddata.h File Reference
#include <stdint.h>
#include "avcodec.h"
#include "libavutil/internal.h"
#include "libavutil/intreadwrite.h"
Data Structures
struct CIDEntry
Macros
#define DNXHD_INTERLACED (1<<0)
Additional profile info flags.
#define DNXHD_MBAFF (1<<1)
#define DNXHD_444 (1<<2)
#define DNXHD_HEADER_INITIAL 0x000002800100
Frame headers, extra 0x00 added to end for parser.
#define DNXHD_HEADER_444 0x000002800200
#define DNXHD_VARIABLE 0
Indicate that a CIDEntry value must be read in the bitstream.
Functions
int ff_dnxhd_get_cid_table (int cid)
int ff_dnxhd_find_cid (AVCodecContext *avctx, int bit_depth)
void ff_dnxhd_print_profiles (AVCodecContext *avctx, int loglevel)
static av_always_inline uint64_t ff_dnxhd_check_header_prefix_hr (uint64_t prefix)
static av_always_inline uint64_t ff_dnxhd_check_header_prefix (uint64_t prefix)
static av_always_inline uint64_t ff_dnxhd_parse_header_prefix (const uint8_t *buf)
int avpriv_dnxhd_get_frame_size (int cid)
int avpriv_dnxhd_get_interlaced (int cid)
attribute_deprecated uint64_t avpriv_dnxhd_parse_header_prefix (const uint8_t *buf)
Variables
const CIDEntry ff_dnxhd_cid_table []
Macro Definition Documentation
DNXHD_INTERLACED
#define DNXHD_INTERLACED (1<<0)
Additional profile info flags.
Definition at line 31 of file dnxhddata.h.
Referenced by avpriv_dnxhd_get_interlaced(), ff_dnxhd_find_cid(), and ff_dnxhd_print_profiles().
DNXHD_MBAFF
#define DNXHD_MBAFF (1<<1)
Definition at line 32 of file dnxhddata.h.
Referenced by ff_dnxhd_find_cid().
DNXHD_444
#define DNXHD_444 (1<<2)
Definition at line 33 of file dnxhddata.h.
Referenced by ff_dnxhd_find_cid().
DNXHD_HEADER_INITIAL
#define DNXHD_HEADER_INITIAL 0x000002800100
Frame headers, extra 0x00 added to end for parser.
Definition at line 36 of file dnxhddata.h.
Referenced by ff_dnxhd_check_header_prefix().
DNXHD_HEADER_444
#define DNXHD_HEADER_444 0x000002800200
Definition at line 37 of file dnxhddata.h.
Referenced by ff_dnxhd_check_header_prefix().
DNXHD_VARIABLE
#define DNXHD_VARIABLE 0
Indicate that a CIDEntry value must be read in the bitstream.
Definition at line 40 of file dnxhddata.h.
Referenced by dnxhd_decode_header(), dnxhd_encode_init(), and dnxhd_init_vlc().
Function Documentation
ff_dnxhd_get_cid_table()
int ff_dnxhd_get_cid_table (int cid)
Definition at line 1090 of file dnxhddata.c.
Referenced by avpriv_dnxhd_get_frame_size(), avpriv_dnxhd_get_interlaced(), dnxhd_encode_init(), and dnxhd_init_vlc().
ff_dnxhd_find_cid()
int ff_dnxhd_find_cid (AVCodecContext * avctx, int bit_depth)
Definition at line 1139 of file dnxhddata.c.
Referenced by dnxhd_encode_init().
ff_dnxhd_print_profiles()
void ff_dnxhd_print_profiles (AVCodecContext * avctx, int loglevel)
Definition at line 1169 of file dnxhddata.c.
Referenced by dnxhd_encode_init().
ff_dnxhd_check_header_prefix_hr()
static av_always_inline uint64_t ff_dnxhd_check_header_prefix_hr (uint64_t prefix) static
Definition at line 68 of file dnxhddata.h.
Referenced by dnxhd_decode_header(), and ff_dnxhd_check_header_prefix().
ff_dnxhd_check_header_prefix()
static av_always_inline uint64_t ff_dnxhd_check_header_prefix (uint64_t prefix) static
Definition at line 78 of file dnxhddata.h.
Referenced by dnxhd_find_frame_end(), and ff_dnxhd_parse_header_prefix().
ff_dnxhd_parse_header_prefix()
static av_always_inline uint64_t ff_dnxhd_parse_header_prefix (const uint8_t * buf) static
Definition at line 87 of file dnxhddata.h.
Referenced by avpriv_dnxhd_parse_header_prefix(), dnxhd_decode_header(), dnxhd_probe(), and mov_write_avid_tag().
avpriv_dnxhd_get_frame_size()
int avpriv_dnxhd_get_frame_size (int cid)
Definition at line 1099 of file dnxhddata.c.
Referenced by ff_dnxhd_parse_header_prefix(), and mxf_parse_dnxhd_frame().
avpriv_dnxhd_get_interlaced()
int avpriv_dnxhd_get_interlaced (int cid)
Definition at line 1107 of file dnxhddata.c.
Referenced by ff_dnxhd_parse_header_prefix(), and mxf_parse_dnxhd_frame().
avpriv_dnxhd_parse_header_prefix()
attribute_deprecated uint64_t avpriv_dnxhd_parse_header_prefix (const uint8_t * buf)
Definition at line 1116 of file dnxhddata.c.
Referenced by ff_dnxhd_parse_header_prefix().
Variable Documentation
ff_dnxhd_cid_table
const CIDEntry ff_dnxhd_cid_table[]
Definition at line 935 of file dnxhddata.c.
Referenced by dnxhd_encode_init(), and dnxhd_init_vlc().