FFmpeg: libavcodec/dnxhddata.c File Reference
dnxhddata.c File Reference
#include "avcodec.h"
#include "dnxhddata.h"
#include "libavutil/common.h"
Functions
int ff_dnxhd_get_cid_table (int cid)
int avpriv_dnxhd_get_frame_size (int cid)
int avpriv_dnxhd_get_interlaced (int cid)
uint64_t avpriv_dnxhd_parse_header_prefix (const uint8_t *buf)
static int dnxhd_find_hr_cid (AVCodecContext *avctx)
int ff_dnxhd_find_cid (AVCodecContext *avctx, int bit_depth)
void ff_dnxhd_print_profiles (AVCodecContext *avctx, int loglevel)
Variables
static const uint8_t dnxhd_1235_luma_weight []
static const uint8_t dnxhd_1235_chroma_weight []
static const uint8_t dnxhd_1237_luma_weight []
static const uint8_t dnxhd_1237_chroma_weight []
static const uint8_t dnxhd_1238_luma_weight []
static const uint8_t dnxhd_1238_chroma_weight []
static const uint8_t dnxhd_1241_luma_weight []
static const uint8_t dnxhd_1241_chroma_weight []
static const uint8_t dnxhd_1242_luma_weight []
static const uint8_t dnxhd_1242_chroma_weight []
static const uint8_t dnxhd_1243_luma_weight []
static const uint8_t dnxhd_1243_chroma_weight []
static const uint8_t dnxhd_1250_luma_weight []
static const uint8_t dnxhd_1250_chroma_weight []
static const uint8_t dnxhd_1251_luma_weight []
static const uint8_t dnxhd_1251_chroma_weight []
static const uint8_t dnxhd_1252_luma_weight []
static const uint8_t dnxhd_1252_chroma_weight []
static const uint8_t dnxhd_1260_luma_weight []
static const uint8_t dnxhd_1260_chroma_weight []
static const uint8_t dnxhd_1235_dc_codes [14]
static const uint8_t dnxhd_1235_dc_bits [14]
static const uint8_t dnxhd_1237_dc_codes [12]
static const uint8_t dnxhd_1237_dc_bits [12]
static const uint16_t dnxhd_1237_ac_codes [257]
static const uint8_t dnxhd_1237_ac_bits [257]
static const uint8_t dnxhd_1237_ac_info [2 *257]
static const uint16_t dnxhd_1238_ac_codes [257]
static const uint8_t dnxhd_1238_ac_bits [257]
static const uint8_t dnxhd_1238_ac_info [2 *257]
static const uint16_t dnxhd_1235_ac_codes [257]
static const uint8_t dnxhd_1235_ac_bits [257]
static const uint8_t dnxhd_1235_ac_info [2 *257]
static const uint16_t dnxhd_1250_ac_codes [257]
static const uint8_t dnxhd_1250_ac_bits [257]
static const uint8_t dnxhd_1250_ac_info [2 *257]
static const uint16_t dnxhd_1251_ac_codes [257]
static const uint8_t dnxhd_1251_ac_bits [257]
static const uint8_t dnxhd_1251_ac_info [2 *257]
static const uint16_t dnxhd_1252_ac_codes [257]
static const uint8_t dnxhd_1252_ac_bits [257]
static const uint8_t dnxhd_1252_ac_info [2 *257]
static const uint16_t dnxhd_1235_run_codes [62]
static const uint8_t dnxhd_1235_run_bits [62]
static const uint8_t dnxhd_1235_run [62]
static const uint16_t dnxhd_1237_run_codes [62]
static const uint8_t dnxhd_1237_run_bits [62]
static const uint8_t dnxhd_1237_run [62]
static const uint8_t dnxhd_1238_run [62]
static const uint16_t dnxhd_1250_run_codes [62]
static const uint8_t dnxhd_1250_run_bits [62]
static const uint8_t dnxhd_1250_run [62]
const CIDEntry ff_dnxhd_cid_table []
Function Documentation
ff_dnxhd_get_cid_table()
int ff_dnxhd_get_cid_table (int cid)
Definition at line 1090 of file dnxhddata.c.
Referenced by avpriv_dnxhd_get_frame_size(), avpriv_dnxhd_get_interlaced(), dnxhd_encode_init(), and dnxhd_init_vlc().
avpriv_dnxhd_get_frame_size()
int avpriv_dnxhd_get_frame_size (int cid)
Definition at line 1099 of file dnxhddata.c.
Referenced by ff_dnxhd_parse_header_prefix(), and mxf_parse_dnxhd_frame().
avpriv_dnxhd_get_interlaced()
int avpriv_dnxhd_get_interlaced (int cid)
Definition at line 1107 of file dnxhddata.c.
Referenced by ff_dnxhd_parse_header_prefix(), and mxf_parse_dnxhd_frame().
avpriv_dnxhd_parse_header_prefix()
uint64_t avpriv_dnxhd_parse_header_prefix (const uint8_t * buf)
Definition at line 1116 of file dnxhddata.c.
Referenced by ff_dnxhd_parse_header_prefix().
dnxhd_find_hr_cid()
static int dnxhd_find_hr_cid (AVCodecContext * avctx) static
Definition at line 1122 of file dnxhddata.c.
Referenced by ff_dnxhd_find_cid().
ff_dnxhd_find_cid()
int ff_dnxhd_find_cid (AVCodecContext * avctx, int bit_depth)
Definition at line 1139 of file dnxhddata.c.
Referenced by dnxhd_encode_init().
ff_dnxhd_print_profiles()
void ff_dnxhd_print_profiles (AVCodecContext * avctx, int loglevel)
Definition at line 1169 of file dnxhddata.c.
Referenced by dnxhd_encode_init().
Variable Documentation
dnxhd_1235_luma_weight
const uint8_t dnxhd_1235_luma_weight[] static
Initial value:
= {
     0, 32, 32, 32, 33, 32, 32, 32,
    32, 31, 32, 33, 33, 33, 33, 35,
    36, 36, 34, 34, 36, 37, 37, 36,
    36, 35, 36, 38, 39, 39, 37, 36,
    37, 37, 39, 41, 42, 41, 39, 39,
    40, 41, 42, 43, 42, 42, 41, 41,
    41, 44, 47, 46, 46, 48, 51, 51,
    50, 50, 53, 55, 55, 56, 60, 60,
}
Definition at line 29 of file dnxhddata.c.
dnxhd_1235_chroma_weight
const uint8_t dnxhd_1235_chroma_weight[] static
Initial value:
= {
     0, 32, 33, 34, 34, 33, 34, 35,
    37, 40, 43, 42, 39, 38, 39, 41,
    43, 44, 47, 50, 55, 61, 63, 56,
    48, 46, 49, 54, 59, 58, 55, 58,
    63, 65, 67, 74, 84, 82, 75, 72,
    70, 74, 84, 87, 87, 94, 93, 81,
    75, 78, 83, 89, 91, 86, 82, 85,
    90, 90, 85, 79, 73, 73, 73, 73,
}
Definition at line 41 of file dnxhddata.c.
dnxhd_1237_luma_weight
const uint8_t dnxhd_1237_luma_weight[] static
Initial value:
= {
     0,  32,  33,  34, 34, 36, 37, 36,
    36,  37,  38,  38, 38, 39, 41, 44,
    43,  41,  40,  41, 46, 49, 47, 46,
    47,  49,  51,  54, 60, 62, 59, 55,
    54,  56,  58,  61, 65, 66, 64, 63,
    66,  73,  78,  79, 80, 79, 78, 78,
    82,  87,  89,  90, 93, 95, 96, 97,
    97, 100, 104, 102, 98, 98, 99, 99,
}
Definition at line 53 of file dnxhddata.c.
dnxhd_1237_chroma_weight
const uint8_t dnxhd_1237_chroma_weight[] static
Initial value:
= {
     0,  32,  36,  39, 39, 38, 39,  41,
    45,  51,  57,  58, 53, 48, 47,  51,
    55,  58,  66,  75, 81, 83, 82,  78,
    73,  72,  74,  77, 83, 85, 83,  82,
    89,  99,  96,  90, 94, 97, 99, 105,
   109, 105,  95,  89, 92, 95, 94,  93,
    92,  88,  89,  90, 93, 95, 96,  97,
    97, 100, 104, 102, 98, 98, 99,  99,
}
Definition at line 65 of file dnxhddata.c.
dnxhd_1238_luma_weight
const uint8_t dnxhd_1238_luma_weight[] static
Initial value:
= {
     0, 32, 32, 33, 34, 33, 33, 33,
    33, 33, 33, 33, 33, 35, 37, 37,
    36, 36, 35, 36, 38, 38, 36, 35,
    36, 37, 38, 41, 42, 41, 39, 38,
    38, 38, 39, 41, 42, 41, 39, 39,
    40, 41, 43, 44, 44, 44, 44, 44,
    45, 47, 47, 47, 49, 50, 51, 51,
    51, 53, 55, 57, 58, 59, 57, 57,
}
Definition at line 77 of file dnxhddata.c.
dnxhd_1238_chroma_weight
const uint8_t dnxhd_1238_chroma_weight[] static
Initial value:
= {
     0, 32, 35, 35, 35, 34, 34, 35,
    39, 43, 45, 45, 41, 39, 40, 41,
    42, 44, 48, 55, 59, 63, 65, 59,
    53, 52, 52, 55, 61, 62, 58, 58,
    63, 66, 66, 65, 70, 74, 70, 66,
    65, 68, 75, 77, 74, 74, 77, 76,
    73, 73, 73, 73, 76, 80, 89, 90,
    82, 77, 80, 86, 84, 82, 82, 82,
}
Definition at line 89 of file dnxhddata.c.
dnxhd_1241_luma_weight
const uint8_t dnxhd_1241_luma_weight[] static
Initial value:
= {
     0, 32, 33, 34, 34, 35, 36, 37,
    36, 37, 38, 38, 38, 39, 39, 40,
    40, 38, 38, 39, 38, 37, 39, 41,
    41, 42, 43, 45, 45, 46, 47, 46,
    45, 43, 39, 37, 37, 40, 44, 45,
    45, 46, 46, 46, 47, 47, 46, 44,
    42, 43, 45, 47, 48, 49, 50, 49,
    48, 46, 47, 48, 48, 49, 49, 49,
}
Definition at line 101 of file dnxhddata.c.
dnxhd_1241_chroma_weight
const uint8_t dnxhd_1241_chroma_weight[] static
Initial value:
= {
     0, 32, 36, 38, 37, 37, 40, 41,
    40, 40, 42, 42, 41, 41, 41, 41,
    42, 43, 44, 44, 45, 46, 46, 45,
    44, 45, 45, 45, 45, 46, 47, 46,
    45, 44, 42, 41, 43, 45, 45, 47,
    48, 48, 48, 46, 47, 47, 46, 47,
    46, 45, 45, 47, 48, 49, 50, 49,
    48, 46, 48, 49, 48, 49, 49, 49,
}
Definition at line 113 of file dnxhddata.c.
dnxhd_1242_luma_weight
const uint8_t dnxhd_1242_luma_weight[] static
Initial value:
= {
     0, 32, 33, 33, 34, 35, 36, 35,
    33, 33, 35, 36, 37, 37, 38, 37,
    37, 37, 36, 37, 37, 37, 38, 39,
    37, 36, 37, 40, 42, 45, 46, 44,
    41, 42, 44, 45, 47, 49, 50, 48,
    46, 48, 49, 50, 52, 52, 50, 49,
    47, 48, 50, 50, 51, 51, 50, 49,
    49, 51, 52, 51, 49, 47, 47, 47,
}
Definition at line 124 of file dnxhddata.c.
dnxhd_1242_chroma_weight
const uint8_t dnxhd_1242_chroma_weight[] static
Initial value:
= {
     0, 32, 37, 42, 45, 45, 45, 44,
    38, 37, 40, 42, 44, 49, 51, 47,
    41, 40, 43, 44, 46, 48, 51, 54,
    51, 47, 47, 45, 47, 50, 51, 49,
    46, 47, 49, 47, 50, 55, 55, 51,
    48, 49, 51, 51, 52, 52, 54, 54,
    49, 49, 52, 53, 54, 54, 53, 53,
    55, 59, 63, 62, 60, 60, 60, 60,
}
Definition at line 135 of file dnxhddata.c.
dnxhd_1243_luma_weight
const uint8_t dnxhd_1243_luma_weight[] static
Initial value:
= {
     0, 32, 32, 33, 33, 35, 35, 35,
    35, 35, 35, 35, 34, 35, 38, 40,
    39, 37, 37, 37, 36, 35, 36, 38,
    40, 41, 42, 44, 45, 44, 42, 41,
    40, 38, 36, 36, 37, 38, 40, 43,
    44, 45, 45, 45, 45, 45, 45, 41,
    39, 41, 45, 47, 47, 48, 48, 48,
    46, 44, 45, 47, 47, 48, 47, 47,
}
Definition at line 146 of file dnxhddata.c.
dnxhd_1243_chroma_weight
const uint8_t dnxhd_1243_chroma_weight[] static
Initial value:
= {
     0, 32, 36, 37, 36, 37, 39, 39,
    41, 43, 43, 42, 41, 41, 41, 42,
    43, 43, 43, 44, 44, 44, 46, 47,
    46, 45, 45, 45, 45, 46, 44, 44,
    45, 44, 42, 41, 43, 46, 45, 44,
    45, 45, 45, 46, 46, 46, 45, 44,
    45, 44, 45, 47, 47, 48, 49, 48,
    46, 45, 46, 47, 47, 48, 47, 47,
}
Definition at line 157 of file dnxhddata.c.
dnxhd_1250_luma_weight
const uint8_t dnxhd_1250_luma_weight[] static
Initial value:
= {
     0, 32, 32, 33, 34, 35, 35, 35,
    34, 34, 35, 36, 36, 36, 36, 36,
    37, 38, 38, 38, 38, 38, 39, 39,
    38, 38, 39, 41, 43, 43, 42, 41,
    40, 40, 39, 40, 41, 41, 39, 39,
    40, 42, 47, 50, 47, 45, 46, 46,
    44, 45, 46, 47, 49, 54, 58, 54,
    48, 49, 54, 57, 60, 62, 63, 63,
}
Definition at line 168 of file dnxhddata.c.
dnxhd_1250_chroma_weight
const uint8_t dnxhd_1250_chroma_weight[] static
Initial value:
= {
     0, 32, 35, 36, 36, 35, 36, 39,
    41, 43, 45, 44, 41, 39, 40, 42,
    43, 43, 45, 48, 49, 51, 52, 50,
    50, 51, 51, 51, 51, 52, 53, 54,
    51, 49, 51, 52, 52, 56, 57, 55,
    54, 54, 55, 56, 55, 58, 58, 58,
    60, 61, 62, 62, 59, 57, 58, 58,
    61, 59, 59, 59, 60, 62, 63, 63,
}
Definition at line 179 of file dnxhddata.c.
dnxhd_1251_luma_weight
const uint8_t dnxhd_1251_luma_weight[] static
Initial value:
= {
     0, 32, 32, 34, 34, 34, 34, 35,
    35, 35, 36, 37, 36, 36, 35, 36,
    38, 38, 38, 38, 38, 38, 38, 38,
    38, 38, 39, 41, 44, 43, 41, 40,
    40, 40, 40, 39, 40, 41, 40, 39,
    40, 43, 46, 46, 44, 44, 44, 42,
    41, 43, 46, 48, 50, 55, 58, 53,
    48, 50, 55, 58, 61, 62, 62, 62,
}
Definition at line 190 of file dnxhddata.c.
dnxhd_1251_chroma_weight
const uint8_t dnxhd_1251_chroma_weight[] static
Initial value:
= {
     0, 32, 35, 36, 36, 35, 36, 39,
    41, 43, 45, 44, 41, 39, 40, 42,
    43, 43, 45, 48, 48, 48, 50, 50,
    50, 51, 51, 51, 51, 52, 53, 54,
    51, 49, 51, 52, 52, 56, 57, 55,
    54, 54, 55, 56, 55, 58, 58, 58,
    60, 61, 62, 62, 59, 57, 58, 58,
    61, 59, 59, 59, 61, 62, 62, 62,
}
Definition at line 201 of file dnxhddata.c.
dnxhd_1252_luma_weight
const uint8_t dnxhd_1252_luma_weight[] static
Initial value:
= {
      0,  32,  34, 35, 36, 36, 36, 37,
     36,  37,  39, 40, 41, 40, 40, 40,
     41,  41,  42, 41, 41, 43, 44, 44,
     45,  46,  48, 55, 60, 57, 52, 50,
     49,  49,  52, 52, 53, 55, 58, 62,
     65,  73,  82, 82, 80, 78, 73, 68,
     71,  82,  90, 90, 88, 87, 90, 95,
    100, 107, 103, 97, 95, 93, 99, 99,
}
Definition at line 213 of file dnxhddata.c.
dnxhd_1252_chroma_weight
const uint8_t dnxhd_1252_chroma_weight[] static
Initial value:
= {
      0,  32,  35,  36,  37,  37,  38,  40,
     42,  46,  49,  50,  50,  49,  49,  53,
     56,  56,  57,  58,  60,  62,  64,  65,
     63,  64,  64,  65,  66,  65,  67,  71,
     72,  74,  74,  74,  74,  77,  81,  78,
     72,  73,  82,  85,  89,  88,  84,  80,
     90, 100,  90,  90,  88,  87,  90,  95,
    114, 128, 125, 129, 134, 125, 116, 116,
}
Definition at line 225 of file dnxhddata.c.
dnxhd_1260_luma_weight
const uint8_t dnxhd_1260_luma_weight[] static
Initial value:
= {
     0, 32, 33, 34, 36, 37, 37, 36,
    34, 33, 34, 35, 37, 38, 40, 41,
    40, 39, 38, 37, 34, 33, 34, 37,
    40, 44, 48, 52, 53, 49, 47, 45,
    42, 38, 36, 36, 38, 41, 43, 44,
    46, 49, 52, 54, 54, 49, 44, 44,
    44, 47, 51, 51, 52, 51, 48, 50,
    52, 53, 53, 50, 50, 54, 54, 54,
}
Definition at line 237 of file dnxhddata.c.
dnxhd_1260_chroma_weight
const uint8_t dnxhd_1260_chroma_weight[] static
Initial value:
= {
     0, 32, 34, 38, 42, 40, 38, 36,
    35, 35, 38, 42, 43, 43, 42, 40,
    38, 39, 43, 43, 42, 41, 43, 43,
    42, 44, 46, 45, 45, 46, 47, 46,
    44, 44, 45, 46, 46, 46, 50, 50,
    47, 47, 49, 49, 49, 49, 51, 53,
    51, 49, 53, 57, 56, 52, 50, 52,
    56, 56, 53, 53, 53, 54, 58, 58,
}
Definition at line 249 of file dnxhddata.c.
dnxhd_1235_dc_codes
const uint8_t dnxhd_1235_dc_codes[14] static
Initial value:
= {
    10, 62, 11, 12, 13, 0, 1, 2, 3, 4, 14, 30, 126, 127,
}
Definition at line 261 of file dnxhddata.c.
dnxhd_1235_dc_bits
const uint8_t dnxhd_1235_dc_bits[14] static
Initial value:
= {
    4, 6, 4, 4, 4, 3, 3, 3, 3, 3, 4, 5, 7, 7,
}
Definition at line 266 of file dnxhddata.c.
dnxhd_1237_dc_codes
const uint8_t dnxhd_1237_dc_codes[12] static
Initial value:
= {
    0, 12, 13, 1, 2, 3, 4, 5, 14, 30, 62, 63,
}
Definition at line 271 of file dnxhddata.c.
dnxhd_1237_dc_bits
const uint8_t dnxhd_1237_dc_bits[12] static
Initial value:
= {
    3, 4, 4, 3, 3, 3, 3, 3, 4, 5, 6, 6,
}
Definition at line 276 of file dnxhddata.c.
dnxhd_1237_ac_codes
const uint16_t dnxhd_1237_ac_codes[257] static
Definition at line 281 of file dnxhddata.c.
dnxhd_1237_ac_bits
const uint8_t dnxhd_1237_ac_bits[257] static
Initial value:
= {
     2,  2,  3,  3,  4,  5,  5,  6,  6,  6,  6,  7,  7,  8,  8,  8,
     8,  8,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 11, 11, 11,
    11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13,
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16,
}
Definition at line 318 of file dnxhddata.c.
dnxhd_1237_ac_info
const uint8_t dnxhd_1237_ac_info[2 *257] static
Definition at line 339 of file dnxhddata.c.
dnxhd_1238_ac_codes
const uint16_t dnxhd_1238_ac_codes[257] static
Definition at line 376 of file dnxhddata.c.
dnxhd_1238_ac_bits
const uint8_t dnxhd_1238_ac_bits[257] static
Initial value:
= {
     2,  2,  3,  4,  4,  5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,
     8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10,
    10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11,
    11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13,
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16,
}
Definition at line 413 of file dnxhddata.c.
dnxhd_1238_ac_info
const uint8_t dnxhd_1238_ac_info[2 *257] static
Definition at line 434 of file dnxhddata.c.
dnxhd_1235_ac_codes
const uint16_t dnxhd_1235_ac_codes[257] static
Definition at line 471 of file dnxhddata.c.
dnxhd_1235_ac_bits
const uint8_t dnxhd_1235_ac_bits[257] static
Initial value:
= {
     2,  2,  3,  4,  4,  5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,
     8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10,
    10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11,
    11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
    13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16,
}
Definition at line 508 of file dnxhddata.c.
dnxhd_1235_ac_info
const uint8_t dnxhd_1235_ac_info[2 *257] static
Definition at line 529 of file dnxhddata.c.
dnxhd_1250_ac_codes
const uint16_t dnxhd_1250_ac_codes[257] static
Definition at line 565 of file dnxhddata.c.
dnxhd_1250_ac_bits
const uint8_t dnxhd_1250_ac_bits[257] static
Initial value:
= {
     2,  2,  3,  4,  4,  5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,
     8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10,
    10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
    11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16
}
Definition at line 600 of file dnxhddata.c.
dnxhd_1250_ac_info
const uint8_t dnxhd_1250_ac_info[2 *257] static
Definition at line 620 of file dnxhddata.c.
dnxhd_1251_ac_codes
const uint16_t dnxhd_1251_ac_codes[257] static
Definition at line 656 of file dnxhddata.c.
dnxhd_1251_ac_bits
const uint8_t dnxhd_1251_ac_bits[257] static
Initial value:
= {
     2,  2,  3,  4,  4,  5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,
     8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10,
    10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
    11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16,
}
Definition at line 692 of file dnxhddata.c.
dnxhd_1251_ac_info
const uint8_t dnxhd_1251_ac_info[2 *257] static
Definition at line 712 of file dnxhddata.c.
dnxhd_1252_ac_codes
const uint16_t dnxhd_1252_ac_codes[257] static
Definition at line 749 of file dnxhddata.c.
dnxhd_1252_ac_bits
const uint8_t dnxhd_1252_ac_bits[257] static
Initial value:
= {
     2,  2,  3,  4,  4,  4,  5,  5,  6,  6,  6,  7,  7,  7,  8,  8,
     8,  8,  8,  8,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10,
    10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16,
}
Definition at line 786 of file dnxhddata.c.
dnxhd_1252_ac_info
const uint8_t dnxhd_1252_ac_info[2 *257] static
Definition at line 807 of file dnxhddata.c.
dnxhd_1235_run_codes
const uint16_t dnxhd_1235_run_codes[62] static
Initial value:
= {
       0,    4,   10,   11,   24,   25,   26,   27,
      56,   57,   58,   59,  120,  242,  486,  487,
     488,  489,  980,  981,  982,  983,  984,  985,
     986,  987,  988,  989,  990,  991,  992,  993,
     994,  995,  996,  997,  998,  999, 1000, 1001,
    1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009,
    1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017,
    1018, 1019, 1020, 1021, 1022, 1023,
}
Definition at line 844 of file dnxhddata.c.
dnxhd_1235_run_bits
const uint8_t dnxhd_1235_run_bits[62] static
Initial value:
= {
     1,  3,  4,  4,  5,  5,  5,  5,  6,  6,  6,  6,  7,  8,  9,  9,
     9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
}
Definition at line 856 of file dnxhddata.c.
dnxhd_1235_run
const uint8_t dnxhd_1235_run[62] static
Initial value:
= {
     1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
    18, 20, 17, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
    33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
    49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
}
Definition at line 864 of file dnxhddata.c.
dnxhd_1237_run_codes
const uint16_t dnxhd_1237_run_codes[62] static
Initial value:
= {
       0,    4,   10,   11,   24,   25,   26,   54,
      55,   56,   57,   58,  118,  119,  240,  482,
     483,  484,  485,  486,  487,  488,  489,  490,
     491,  492,  493,  494,  990,  991,  992,  993,
     994,  995,  996,  997,  998,  999, 1000, 1001,
    1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009,
    1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017,
    1018, 1019, 1020, 1021, 1022, 1023,
}
Definition at line 872 of file dnxhddata.c.
dnxhd_1237_run_bits
const uint8_t dnxhd_1237_run_bits[62] static
Initial value:
= {
     1,  3,  4,  4,  5,  5,  5,  6,  6,  6,  6,  6,  7,  7,  8,  9,
     9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10,
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
}
Definition at line 884 of file dnxhddata.c.
dnxhd_1237_run
const uint8_t dnxhd_1237_run[62] static
Initial value:
= {
     1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
    17, 18, 19, 20, 21, 53, 57, 58, 59, 60, 61, 62, 22, 23, 24, 25,
    26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
    42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 54, 55, 56,
}
Definition at line 892 of file dnxhddata.c.
dnxhd_1238_run
const uint8_t dnxhd_1238_run[62] static
Initial value:
= {
     1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
    20, 21, 17, 18, 19, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
    33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
    49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
}
Definition at line 900 of file dnxhddata.c.
dnxhd_1250_run_codes
const uint16_t dnxhd_1250_run_codes[62] static
Initial value:
= {
       0,    4,    5,   12,   26,   27,   28,   58,
     118,  119,  120,  242,  486,  487,  976,  977,
     978,  979,  980,  981,  982,  983,  984,  985,
     986,  987,  988,  989,  990,  991,  992,  993,
     994,  995,  996,  997,  998,  999, 1000, 1001,
    1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009,
    1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017,
    1018, 1019, 1020, 1021, 1022, 1023,
}
Definition at line 908 of file dnxhddata.c.
dnxhd_1250_run_bits
const uint8_t dnxhd_1250_run_bits[62] static
Initial value:
= {
     1,  3,  3,  4,  5,  5,  5,  6,  7,  7,  7,  8,  9,  9, 10, 10,
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
}
Definition at line 920 of file dnxhddata.c.
dnxhd_1250_run
const uint8_t dnxhd_1250_run[62] static
Initial value:
= {
     1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
    17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
    33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
    49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
}
Definition at line 928 of file dnxhddata.c.
ff_dnxhd_cid_table
const CIDEntry ff_dnxhd_cid_table[]
Definition at line 935 of file dnxhddata.c.
Referenced by dnxhd_encode_init(), and dnxhd_init_vlc().