FFmpeg: libavcodec/dnxhdenc.c File Reference
dnxhdenc.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/internal.h"
#include "libavutil/opt.h"
#include "libavutil/timer.h"
#include "avcodec.h"
#include "blockdsp.h"
#include "fdctdsp.h"
#include "internal.h"
#include "mpegvideo.h"
#include "pixblockdsp.h"
#include "profiles.h"
#include "dnxhdenc.h"
Macros
#define DNX10BIT_QMAT_SHIFT 18
#define RC_VARIANCE 1
#define LAMBDA_FRAC_BITS 10
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
#define BUCKET_BITS 8
#define RADIX_PASSES 4
#define NBUCKETS (1 << BUCKET_BITS)
Functions
static void dnxhd_8bit_get_pixels_8x4_sym (int16_t *av_restrict block, const uint8_t *pixels, ptrdiff_t line_size)
static av_always_inline void dnxhd_10bit_get_pixels_8x4_sym (int16_t *av_restrict block, const uint8_t *pixels, ptrdiff_t line_size)
static int dnxhd_10bit_dct_quantize (MpegEncContext *ctx, int16_t *block, int n, int qscale, int *overflow)
static av_cold int dnxhd_init_vlc (DNXHDEncContext *ctx)
static av_cold int dnxhd_init_qmat (DNXHDEncContext *ctx, int lbias, int cbias)
static av_cold int dnxhd_init_rc (DNXHDEncContext *ctx)
static int dnxhd_get_hr_frame_size (const CIDEntry *profile, int mb_num)
static av_cold int dnxhd_encode_init (AVCodecContext *avctx)
static int dnxhd_write_header (AVCodecContext *avctx, uint8_t *buf)
static av_always_inline void dnxhd_encode_dc (DNXHDEncContext *ctx, int diff)
static av_always_inline void dnxhd_encode_block (DNXHDEncContext *ctx, int16_t *block, int last_index, int n)
static av_always_inline void dnxhd_unquantize_c (DNXHDEncContext *ctx, int16_t *block, int n, int qscale, int last_index)
static av_always_inline int dnxhd_ssd_block (int16_t *qblock, int16_t *block)
static av_always_inline int dnxhd_calc_ac_bits (DNXHDEncContext *ctx, int16_t *block, int last_index)
static av_always_inline void dnxhd_get_blocks (DNXHDEncContext *ctx, int mb_x, int mb_y)
static av_always_inline int dnxhd_switch_matrix (DNXHDEncContext *ctx, int i)
static int dnxhd_calc_bits_thread (AVCodecContext *avctx, void *arg, int jobnr, int threadnr)
static int dnxhd_encode_thread (AVCodecContext *avctx, void *arg, int jobnr, int threadnr)
static void dnxhd_setup_threads_slices (DNXHDEncContext *ctx)
static int dnxhd_mb_var_thread (AVCodecContext *avctx, void *arg, int jobnr, int threadnr)
static int dnxhd_encode_rdo (AVCodecContext *avctx, DNXHDEncContext *ctx)
static int dnxhd_find_qscale (DNXHDEncContext *ctx)
static int get_bucket (int value, int shift)
static void radix_count (const RCCMPEntry *data, int size, int buckets[RADIX_PASSES][NBUCKETS])
static void radix_sort_pass (RCCMPEntry *dst, const RCCMPEntry *data, int size, int buckets[NBUCKETS], int pass)
static void radix_sort (RCCMPEntry *data, RCCMPEntry *tmp, int size)
static int dnxhd_encode_fast (AVCodecContext *avctx, DNXHDEncContext *ctx)
static void dnxhd_load_picture (DNXHDEncContext *ctx, const AVFrame *frame)
static int dnxhd_encode_picture (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *frame, int *got_packet)
static av_cold int dnxhd_encode_end (AVCodecContext *avctx)
Variables
static const AVOption options []
static const AVClass dnxhd_class
static const AVCodecDefault dnxhd_defaults []
AVCodec ff_dnxhd_encoder
Macro Definition Documentation
DNX10BIT_QMAT_SHIFT
#define DNX10BIT_QMAT_SHIFT 18
Definition at line 41 of file dnxhdenc.c.
Referenced by dnxhd_10bit_dct_quantize(), and dnxhd_init_qmat().
RC_VARIANCE
#define RC_VARIANCE 1
Definition at line 42 of file dnxhdenc.c.
Referenced by dnxhd_calc_bits_thread(), and dnxhd_encode_fast().
LAMBDA_FRAC_BITS
#define LAMBDA_FRAC_BITS 10
Definition at line 43 of file dnxhdenc.c.
Referenced by dnxhd_encode_rdo(), and dnxhd_init_rc().
VE
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 45 of file dnxhdenc.c.
BUCKET_BITS
#define BUCKET_BITS 8
Definition at line 1034 of file dnxhdenc.c.
Referenced by radix_count(), and radix_sort_pass().
RADIX_PASSES
#define RADIX_PASSES 4
Definition at line 1035 of file dnxhdenc.c.
Referenced by radix_count(), and radix_sort().
NBUCKETS
#define NBUCKETS (1 << BUCKET_BITS)
Definition at line 1036 of file dnxhdenc.c.
Referenced by get_bucket(), and radix_sort().
Function Documentation
dnxhd_8bit_get_pixels_8x4_sym()
static void dnxhd_8bit_get_pixels_8x4_sym (int16_t *av_restrict block, const uint8_t * pixels, ptrdiff_t line_size) static
Definition at line 77 of file dnxhdenc.c.
Referenced by dnxhd_encode_init().
dnxhd_10bit_get_pixels_8x4_sym()
static av_always_inline void dnxhd_10bit_get_pixels_8x4_sym (int16_t *av_restrict block, const uint8_t * pixels, ptrdiff_t line_size) static
Definition at line 101 of file dnxhdenc.c.
Referenced by dnxhd_encode_init().
dnxhd_10bit_dct_quantize()
static int dnxhd_10bit_dct_quantize (MpegEncContext * ctx, int16_t * block, int n, int qscale, int * overflow) static
Definition at line 115 of file dnxhdenc.c.
Referenced by dnxhd_encode_init().
dnxhd_init_vlc()
static av_cold int dnxhd_init_vlc (DNXHDEncContext * ctx) static
Definition at line 146 of file dnxhdenc.c.
Referenced by dnxhd_encode_init().
dnxhd_init_qmat()
static av_cold int dnxhd_init_qmat (DNXHDEncContext * ctx, int lbias, int cbias) static
Definition at line 207 of file dnxhdenc.c.
Referenced by dnxhd_encode_init().
dnxhd_init_rc()
static av_cold int dnxhd_init_rc (DNXHDEncContext * ctx) static
Definition at line 287 of file dnxhdenc.c.
Referenced by dnxhd_encode_init().
dnxhd_get_hr_frame_size()
static int dnxhd_get_hr_frame_size (const CIDEntry * profile, int mb_num) static
Definition at line 306 of file dnxhdenc.c.
Referenced by dnxhd_encode_init().
dnxhd_encode_init()
static av_cold int dnxhd_encode_init (AVCodecContext * avctx) static
Definition at line 312 of file dnxhdenc.c.
dnxhd_write_header()
static int dnxhd_write_header (AVCodecContext * avctx, uint8_t * buf) static
Definition at line 473 of file dnxhdenc.c.
Referenced by dnxhd_encode_picture().
dnxhd_encode_dc()
static av_always_inline void dnxhd_encode_dc (DNXHDEncContext * ctx, int diff) static
Definition at line 509 of file dnxhdenc.c.
Referenced by dnxhd_encode_block().
dnxhd_encode_block()
static av_always_inline void dnxhd_encode_block (DNXHDEncContext * ctx, int16_t * block, int last_index, int n) static
Definition at line 524 of file dnxhdenc.c.
Referenced by dnxhd_encode_thread().
dnxhd_unquantize_c()
static av_always_inline void dnxhd_unquantize_c (DNXHDEncContext * ctx, int16_t * block, int n, int qscale, int last_index) static
Definition at line 550 of file dnxhdenc.c.
Referenced by dnxhd_calc_bits_thread().
dnxhd_ssd_block()
static av_always_inline int dnxhd_ssd_block (int16_t * qblock, int16_t * block) static
Definition at line 593 of file dnxhdenc.c.
Referenced by dnxhd_calc_bits_thread().
dnxhd_calc_ac_bits()
static av_always_inline int dnxhd_calc_ac_bits (DNXHDEncContext * ctx, int16_t * block, int last_index) static
Definition at line 603 of file dnxhdenc.c.
Referenced by dnxhd_calc_bits_thread().
dnxhd_get_blocks()
static av_always_inline void dnxhd_get_blocks (DNXHDEncContext * ctx, int mb_x, int mb_y) static
Definition at line 622 of file dnxhdenc.c.
Referenced by dnxhd_calc_bits_thread(), and dnxhd_encode_thread().
dnxhd_switch_matrix()
static av_always_inline int dnxhd_switch_matrix (DNXHDEncContext * ctx, int i) static
Definition at line 706 of file dnxhdenc.c.
Referenced by dnxhd_calc_bits_thread(), and dnxhd_encode_thread().
dnxhd_calc_bits_thread()
static int dnxhd_calc_bits_thread (AVCodecContext * avctx, void * arg, int jobnr, int threadnr) static
Definition at line 712 of file dnxhdenc.c.
Referenced by dnxhd_encode_rdo(), and dnxhd_find_qscale().
dnxhd_encode_thread()
static int dnxhd_encode_thread (AVCodecContext * avctx, void * arg, int jobnr, int threadnr) static
Definition at line 768 of file dnxhdenc.c.
Referenced by dnxhd_encode_picture().
dnxhd_setup_threads_slices()
static void dnxhd_setup_threads_slices (DNXHDEncContext * ctx) static
Definition at line 805 of file dnxhdenc.c.
Referenced by dnxhd_encode_picture().
dnxhd_mb_var_thread()
static int dnxhd_mb_var_thread (AVCodecContext * avctx, void * arg, int jobnr, int threadnr) static
Definition at line 824 of file dnxhdenc.c.
Referenced by dnxhd_encode_fast().
dnxhd_encode_rdo()
static int dnxhd_encode_rdo (AVCodecContext * avctx, DNXHDEncContext * ctx) static
Definition at line 892 of file dnxhdenc.c.
Referenced by dnxhd_encode_picture().
dnxhd_find_qscale()
static int dnxhd_find_qscale (DNXHDEncContext * ctx) static
Definition at line 973 of file dnxhdenc.c.
Referenced by dnxhd_encode_fast().
get_bucket()
static int get_bucket (int value, int shift) inline static
Definition at line 1038 of file dnxhdenc.c.
Referenced by radix_count(), and radix_sort_pass().
radix_count()
static void radix_count (const RCCMPEntry * data, int size, int buckets[RADIX_PASSES][NBUCKETS]) static
Definition at line 1045 of file dnxhdenc.c.
Referenced by radix_sort().
radix_sort_pass()
static void radix_sort_pass (RCCMPEntry * dst, const RCCMPEntry * data, int size, int buckets[NBUCKETS], int pass) static
Definition at line 1066 of file dnxhdenc.c.
Referenced by radix_sort().
radix_sort()
static void radix_sort (RCCMPEntry * data, RCCMPEntry * tmp, int size) static
Definition at line 1078 of file dnxhdenc.c.
Referenced by dnxhd_encode_fast().
dnxhd_encode_fast()
static int dnxhd_encode_fast (AVCodecContext * avctx, DNXHDEncContext * ctx) static
Definition at line 1090 of file dnxhdenc.c.
Referenced by dnxhd_encode_picture().
dnxhd_load_picture()
static void dnxhd_load_picture (DNXHDEncContext * ctx, const AVFrame * frame) static
Definition at line 1134 of file dnxhdenc.c.
Referenced by dnxhd_encode_picture().
dnxhd_encode_picture()
static int dnxhd_encode_picture (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * frame, int * got_packet) static
Definition at line 1153 of file dnxhdenc.c.
dnxhd_encode_end()
static av_cold int dnxhd_encode_end (AVCodecContext * avctx) static
Definition at line 1223 of file dnxhdenc.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "nitris_compat", "encode with Avid Nitris compatibility",
        0x42, AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, VE },
    { "ibias", "intra quant bias",
        0x42, AV_OPT_TYPE_INT,
        { .i64 = 0 }, INT_MIN, INT_MAX, VE },
    { "profile",       NULL, 0x42, AV_OPT_TYPE_INT,
        { .i64 = FF_PROFILE_DNXHD },
        FF_PROFILE_DNXHD, FF_PROFILE_DNXHR_444, VE, "profile" },
    { "dnxhd",     NULL, 0, AV_OPT_TYPE_CONST, { .i64 = FF_PROFILE_DNXHD },
        0, 0, VE, "profile" },
    { "dnxhr_444", NULL, 0, AV_OPT_TYPE_CONST, { .i64 = FF_PROFILE_DNXHR_444 },
        0, 0, VE, "profile" },
    { "dnxhr_hqx", NULL, 0, AV_OPT_TYPE_CONST, { .i64 = FF_PROFILE_DNXHR_HQX },
        0, 0, VE, "profile" },
    { "dnxhr_hq",  NULL, 0, AV_OPT_TYPE_CONST, { .i64 = FF_PROFILE_DNXHR_HQ },
        0, 0, VE, "profile" },
    { "dnxhr_sq",  NULL, 0, AV_OPT_TYPE_CONST, { .i64 = FF_PROFILE_DNXHR_SQ },
        0, 0, VE, "profile" },
    { "dnxhr_lb",  NULL, 0, AV_OPT_TYPE_CONST, { .i64 = FF_PROFILE_DNXHR_LB },
        0, 0, VE, "profile" },
    { NULL }
}
Definition at line 46 of file dnxhdenc.c.
dnxhd_class
const AVClass dnxhd_class static
Initial value:
= {
    .class_name = "dnxhd",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 70 of file dnxhdenc.c.
dnxhd_defaults
const AVCodecDefault dnxhd_defaults[] static
Initial value:
= {
    { "qmax", "1024" },
    { NULL },
}
Definition at line 1253 of file dnxhdenc.c.
ff_dnxhd_encoder
AVCodec ff_dnxhd_encoder
Initial value:
= {
    .name           = "dnxhd",
    .long_name      = NULL_IF_CONFIG_SMALL("VC3/DNxHD"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_DNXHD,
    .priv_data_size = sizeof(DNXHDEncContext),
    .init           = dnxhd_encode_init,
    .encode2        = dnxhd_encode_picture,
    .close          = dnxhd_encode_end,
    .capabilities   = AV_CODEC_CAP_SLICE_THREADS,
    .pix_fmts       = (const enum AVPixelFormat[]) {
        AV_PIX_FMT_YUV422P,
        AV_PIX_FMT_YUV422P10,
        AV_PIX_FMT_NONE
    },
    .priv_class     = &dnxhd_class,
    .defaults       = dnxhd_defaults,
    .profiles       = NULL_IF_CONFIG_SMALL(ff_dnxhd_profiles),
}
Definition at line 1258 of file dnxhdenc.c.