FFmpeg: libavcodec/dpx.c File Reference
dpx.c File Reference
#include "libavutil/intreadwrite.h"
#include "libavutil/intfloat.h"
#include "libavutil/imgutils.h"
#include "bytestream.h"
#include "avcodec.h"
#include "internal.h"
Functions
static unsigned int read16 (const uint8_t **ptr, int is_big)
static unsigned int read32 (const uint8_t **ptr, int is_big)
static uint16_t read10in32 (const uint8_t **ptr, uint32_t *lbuf, int *n_datum, int is_big)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
Variables
AVCodec ff_dpx_decoder
Function Documentation
read16()
static unsigned int read16 (const uint8_t ** ptr, int is_big) static
Definition at line 29 of file dpx.c.
Referenced by decode_frame().
read32()
static unsigned int read32 (const uint8_t ** ptr, int is_big) static
Definition at line 41 of file dpx.c.
Referenced by decode_frame(), and read10in32().
read10in32()
static uint16_t read10in32 (const uint8_t ** ptr, uint32_t * lbuf, int * n_datum, int is_big) static
Definition at line 53 of file dpx.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 68 of file dpx.c.
Variable Documentation
ff_dpx_decoder
AVCodec ff_dpx_decoder
Initial value:
= {
    .name           = "dpx",
    .long_name      = NULL_IF_CONFIG_SMALL("DPX (Digital Picture Exchange) image"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_DPX,
    .decode         = decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 398 of file dpx.c.