FFmpeg: libavcodec/dpxenc.c File Reference
dpxenc.c File Reference
#include "libavutil/common.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/imgutils.h"
#include "avcodec.h"
#include "internal.h"
Data Structures
struct DPXContext
Macros
#define write16(p, value) write16_internal(s->big_endian, p, value)
#define write32(p, value) write32_internal(s->big_endian, p, value)
#define HEADER_SIZE 1664 /* DPX Generic header */
Functions
static av_cold int encode_init (AVCodecContext *avctx)
static av_always_inline void write16_internal (int big_endian, void *p, int value)
static av_always_inline void write32_internal (int big_endian, void *p, int value)
static void encode_rgb48_10bit (AVCodecContext *avctx, const AVFrame *pic, uint8_t *dst)
static void encode_gbrp10 (AVCodecContext *avctx, const AVFrame *pic, uint8_t *dst)
static void encode_gbrp12 (AVCodecContext *avctx, const AVFrame *pic, uint16_t *dst)
static int encode_frame (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *frame, int *got_packet)
Variables
AVCodec ff_dpx_encoder
Macro Definition Documentation
write16
#define write16 (p, value) write16_internal(s->big_endian, p, value)
Definition at line 90 of file dpxenc.c.
Referenced by encode_frame(), and encode_gbrp12().
write32
#define write32 (p, value) write32_internal(s->big_endian, p, value)
Definition at line 91 of file dpxenc.c.
Referenced by encode_frame(), encode_gbrp10(), and encode_rgb48_10bit().
HEADER_SIZE
#define HEADER_SIZE 1664 /* DPX Generic header */
Referenced by encode_frame().
Function Documentation
encode_init()
static av_cold int encode_init (AVCodecContext * avctx) static
Definition at line 36 of file dpxenc.c.
write16_internal()
static av_always_inline void write16_internal (int big_endian, void * p, int value) static
Definition at line 78 of file dpxenc.c.
write32_internal()
static av_always_inline void write32_internal (int big_endian, void * p, int value) static
Definition at line 84 of file dpxenc.c.
encode_rgb48_10bit()
static void encode_rgb48_10bit (AVCodecContext * avctx, const AVFrame * pic, uint8_t * dst) static
Definition at line 93 of file dpxenc.c.
Referenced by encode_frame().
encode_gbrp10()
static void encode_gbrp10 (AVCodecContext * avctx, const AVFrame * pic, uint8_t * dst) static
Definition at line 119 of file dpxenc.c.
Referenced by encode_frame().
encode_gbrp12()
static void encode_gbrp12 (AVCodecContext * avctx, const AVFrame * pic, uint16_t * dst) static
Definition at line 145 of file dpxenc.c.
Referenced by encode_frame().
encode_frame()
static int encode_frame (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * frame, int * got_packet) static
Definition at line 176 of file dpxenc.c.
Variable Documentation
ff_dpx_encoder
AVCodec ff_dpx_encoder
Initial value:
= {
    .name           = "dpx",
    .long_name      = NULL_IF_CONFIG_SMALL("DPX (Digital Picture Exchange) image"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_DPX,
    .priv_data_size = sizeof(DPXContext),
    .init           = encode_init,
    .encode2        = encode_frame,
    .pix_fmts       = (const enum AVPixelFormat[]){
        AV_PIX_FMT_GRAY8,
        AV_PIX_FMT_RGB24,    AV_PIX_FMT_RGBA, AV_PIX_FMT_ABGR,
        AV_PIX_FMT_GRAY16LE, AV_PIX_FMT_GRAY16BE,
        AV_PIX_FMT_RGB48LE,  AV_PIX_FMT_RGB48BE,
        AV_PIX_FMT_RGBA64LE, AV_PIX_FMT_RGBA64BE,
        AV_PIX_FMT_GBRP10LE, AV_PIX_FMT_GBRP10BE,
        AV_PIX_FMT_GBRP12LE, AV_PIX_FMT_GBRP12BE,
        AV_PIX_FMT_NONE},
}
Definition at line 279 of file dpxenc.c.