FFmpeg: libavdevice/dshow_crossbar.c File Reference
dshow_crossbar.c File Reference
#include "dshow_capture.h"
Functions
static const char * GetPhysicalPinName (long pin_type)
static HRESULT setup_crossbar_options (IAMCrossbar *cross_bar, enum dshowDeviceType devtype, AVFormatContext *avctx)
HRESULT dshow_try_setup_crossbar_options (ICaptureGraphBuilder2 *graph_builder2, IBaseFilter *device_filter, enum dshowDeviceType devtype, AVFormatContext *avctx)
Given a fully constructed graph, check if there is a cross bar filter, and configure its pins if so.
Function Documentation
GetPhysicalPinName()
static const char* GetPhysicalPinName (long pin_type) static
Definition at line 25 of file dshow_crossbar.c.
Referenced by setup_crossbar_options().
setup_crossbar_options()
static HRESULT setup_crossbar_options (IAMCrossbar * cross_bar, enum dshowDeviceType devtype, AVFormatContext * avctx) static
Definition at line 58 of file dshow_crossbar.c.
Referenced by dshow_try_setup_crossbar_options().
dshow_try_setup_crossbar_options()
HRESULT dshow_try_setup_crossbar_options (ICaptureGraphBuilder2 * graph_builder2, IBaseFilter * device_filter, enum dshowDeviceType devtype, AVFormatContext * avctx)
Given a fully constructed graph, check if there is a cross bar filter, and configure its pins if so.
Definition at line 140 of file dshow_crossbar.c.
Referenced by dshow_open_device().