FFmpeg: libavdevice/dshow_common.c File Reference
dshow_common.c File Reference
#include "dshow_capture.h"
Macros
#define dstruct(pctx, sname, var, type) dshowdebug(" "#var":\t%"type"\n", sname->var)
Functions
long ff_copy_dshow_media_type (AM_MEDIA_TYPE *dst, const AM_MEDIA_TYPE *src)
void ff_printGUID (const GUID *g)
static const char * dshow_context_to_name (void *ptr)
void ff_print_VIDEO_STREAM_CONFIG_CAPS (const VIDEO_STREAM_CONFIG_CAPS *caps)
void ff_print_AUDIO_STREAM_CONFIG_CAPS (const AUDIO_STREAM_CONFIG_CAPS *caps)
void ff_print_AM_MEDIA_TYPE (const AM_MEDIA_TYPE *type)
Variables
static const AVClass ff_dshow_context_class = { "DirectShow", dshow_context_to_name }
const AVClass * ff_dshow_context_class_ptr = &ff_dshow_context_class
Macro Definition Documentation
dstruct
#define dstruct (pctx, sname, var, type) dshowdebug(" "#var":\t%"type"\n", sname->var)
Definition at line 62 of file dshow_common.c.
Function Documentation
ff_copy_dshow_media_type()
long ff_copy_dshow_media_type (AM_MEDIA_TYPE * dst, const AM_MEDIA_TYPE * src)
Definition at line 24 of file dshow_common.c.
Referenced by DECLARE_QUERYINTERFACE(), libAVEnumMediaTypes_Setup(), libAVPin_ConnectionMediaType(), and libAVPin_ReceiveConnection().
ff_printGUID()
void ff_printGUID (const GUID * g)
Definition at line 42 of file dshow_common.c.
Referenced by ff_print_AM_MEDIA_TYPE(), ff_print_AUDIO_STREAM_CONFIG_CAPS(), and ff_print_VIDEO_STREAM_CONFIG_CAPS().
dshow_context_to_name()
static const char* dshow_context_to_name (void * ptr) static
Definition at line 55 of file dshow_common.c.
ff_print_VIDEO_STREAM_CONFIG_CAPS()
void ff_print_VIDEO_STREAM_CONFIG_CAPS (const VIDEO_STREAM_CONFIG_CAPS * caps)
Definition at line 85 of file dshow_common.c.
Referenced by dshow_cycle_formats().
ff_print_AUDIO_STREAM_CONFIG_CAPS()
void ff_print_AUDIO_STREAM_CONFIG_CAPS (const AUDIO_STREAM_CONFIG_CAPS * caps)
Definition at line 115 of file dshow_common.c.
Referenced by dshow_cycle_formats().
ff_print_AM_MEDIA_TYPE()
void ff_print_AM_MEDIA_TYPE (const AM_MEDIA_TYPE * type)
Definition at line 134 of file dshow_common.c.
Referenced by dshow_cycle_formats(), and libAVPin_ReceiveConnection().
Variable Documentation
ff_dshow_context_class
const AVClass ff_dshow_context_class = { "DirectShow", dshow_context_to_name } static
Definition at line 59 of file dshow_common.c.
ff_dshow_context_class_ptr
const AVClass* ff_dshow_context_class_ptr = &ff_dshow_context_class
Definition at line 60 of file dshow_common.c.