FFmpeg: libavcodec/dsicinvideo.c File Reference
dsicinvideo.c File Reference
Delphine Software International CIN video decoder.
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
Data Structures
struct CinVideoContext
Enumerations
enum CinVideoBitmapIndex { CIN_CUR_BMP = 0, CIN_PRE_BMP = 1, CIN_INT_BMP = 2 }
Functions
static av_cold void destroy_buffers (CinVideoContext *cin)
static av_cold int allocate_buffers (CinVideoContext *cin)
static av_cold int cinvideo_decode_init (AVCodecContext *avctx)
static void cin_apply_delta_data (const unsigned char *src, unsigned char *dst, int size)
static int cin_decode_huffman (const unsigned char *src, int src_size, unsigned char *dst, int dst_size)
static int cin_decode_lzss (const unsigned char *src, int src_size, unsigned char *dst, int dst_size)
static int cin_decode_rle (const unsigned char *src, int src_size, unsigned char *dst, int dst_size)
static int cinvideo_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int cinvideo_decode_end (AVCodecContext *avctx)
Variables
AVCodec ff_dsicinvideo_decoder
Detailed Description
Delphine Software International CIN video decoder.
Definition in file dsicinvideo.c.
Enumeration Type Documentation
CinVideoBitmapIndex
enum CinVideoBitmapIndex
Enumerator
CIN_CUR_BMP
CIN_PRE_BMP
CIN_INT_BMP
Definition at line 31 of file dsicinvideo.c.
Function Documentation
destroy_buffers()
static av_cold void destroy_buffers (CinVideoContext * cin) static
Definition at line 45 of file dsicinvideo.c.
Referenced by allocate_buffers(), and cinvideo_decode_end().
allocate_buffers()
static av_cold int allocate_buffers (CinVideoContext * cin) static
Definition at line 53 of file dsicinvideo.c.
Referenced by cinvideo_decode_init().
cinvideo_decode_init()
static av_cold int cinvideo_decode_init (AVCodecContext * avctx) static
Definition at line 69 of file dsicinvideo.c.
cin_apply_delta_data()
static void cin_apply_delta_data (const unsigned char * src, unsigned char * dst, int size) static
Definition at line 87 of file dsicinvideo.c.
Referenced by cinvideo_decode_frame().
cin_decode_huffman()
static int cin_decode_huffman (const unsigned char * src, int src_size, unsigned char * dst, int dst_size) static
Definition at line 94 of file dsicinvideo.c.
Referenced by cinvideo_decode_frame().
cin_decode_lzss()
static int cin_decode_lzss (const unsigned char * src, int src_size, unsigned char * dst, int dst_size) static
Definition at line 129 of file dsicinvideo.c.
Referenced by cinvideo_decode_frame().
cin_decode_rle()
static int cin_decode_rle (const unsigned char * src, int src_size, unsigned char * dst, int dst_size) static
Definition at line 164 of file dsicinvideo.c.
Referenced by cinvideo_decode_frame().
cinvideo_decode_frame()
static int cinvideo_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 190 of file dsicinvideo.c.
cinvideo_decode_end()
static av_cold int cinvideo_decode_end (AVCodecContext * avctx) static
Definition at line 296 of file dsicinvideo.c.
Variable Documentation
ff_dsicinvideo_decoder
AVCodec ff_dsicinvideo_decoder
Initial value:
= {
    .name           = "dsicinvideo",
    .long_name      = NULL_IF_CONFIG_SMALL("Delphine Software International CIN video"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_DSICINVIDEO,
    .priv_data_size = sizeof(CinVideoContext),
    .init           = cinvideo_decode_init,
    .close          = cinvideo_decode_end,
    .decode         = cinvideo_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 307 of file dsicinvideo.c.