FFmpeg: libavcodec/dstdec.c File Reference
dstdec.c File Reference
Direct Stream Transfer (DST) decoder ISO/IEC 14496-3 Part 3 Subpart 10: Technical description of lossless coding of oversampled audio.
#include "libavutil/avassert.h"
#include "libavutil/intreadwrite.h"
#include "internal.h"
#include "get_bits.h"
#include "avcodec.h"
#include "golomb.h"
#include "mathops.h"
#include "dsd.h"
Data Structures
struct ArithCoder
struct Table
struct DSTContext
Macros
#define DST_MAX_CHANNELS 6
#define DST_MAX_ELEMENTS (2 * DST_MAX_CHANNELS)
#define DSD_FS44(sample_rate) (sample_rate * 8 / 44100)
#define DST_SAMPLES_PER_FRAME(sample_rate) (588 * DSD_FS44(sample_rate))
#define F(x) filter[(x)][status[(x)]]
Functions
static av_cold int decode_init (AVCodecContext *avctx)
static int read_map (GetBitContext *gb, Table *t, unsigned int map[DST_MAX_CHANNELS], int channels)
static av_always_inline int get_sr_golomb_dst (GetBitContext *gb, unsigned int k)
static void read_uncoded_coeff (GetBitContext *gb, int *dst, unsigned int elements, int coeff_bits, int is_signed, int offset)
static int read_table (GetBitContext *gb, Table *t, const int8_t code_pred_coeff[3][3], int length_bits, int coeff_bits, int is_signed, int offset)
static void ac_init (ArithCoder *ac, GetBitContext *gb)
static av_always_inline void ac_get (ArithCoder *ac, GetBitContext *gb, int p, int *e)
static uint8_t prob_dst_x_bit (int c)
static void build_filter (int16_t table[DST_MAX_ELEMENTS][16][256], const Table *fsets)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame_ptr, AVPacket *avpkt)
Variables
static const int8_t fsets_code_pred_coeff [3][3]
static const int8_t probs_code_pred_coeff [3][3]
AVCodec ff_dst_decoder
Detailed Description
Direct Stream Transfer (DST) decoder ISO/IEC 14496-3 Part 3 Subpart 10: Technical description of lossless coding of oversampled audio.
Definition in file dstdec.c.
Macro Definition Documentation
DST_MAX_CHANNELS
#define DST_MAX_CHANNELS 6
Definition at line 37 of file dstdec.c.
Referenced by decode_frame(), and decode_init().
DST_MAX_ELEMENTS
#define DST_MAX_ELEMENTS (2 * DST_MAX_CHANNELS)
Definition at line 38 of file dstdec.c.
Referenced by read_map().
DSD_FS44
#define DSD_FS44 (sample_rate) (sample_rate * 8 / 44100)
Definition at line 40 of file dstdec.c.
DST_SAMPLES_PER_FRAME
#define DST_SAMPLES_PER_FRAME (sample_rate) (588 * DSD_FS44(sample_rate))
Definition at line 42 of file dstdec.c.
Referenced by decode_frame().
F
#define F (x) filter[(x)][status[(x)]]
Referenced by check_loopfilter(), decode_frame(), idct(), and loop_filter().
Function Documentation
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 78 of file dstdec.c.
read_map()
static int read_map (GetBitContext * gb, Table * t, unsigned int map[DST_MAX_CHANNELS], int channels) static
Definition at line 98 of file dstdec.c.
Referenced by decode_frame().
get_sr_golomb_dst()
static av_always_inline int get_sr_golomb_dst (GetBitContext * gb, unsigned int k) static
Definition at line 121 of file dstdec.c.
Referenced by read_table().
read_uncoded_coeff()
static void read_uncoded_coeff (GetBitContext * gb, int * dst, unsigned int elements, int coeff_bits, int is_signed, int offset) static
Definition at line 129 of file dstdec.c.
Referenced by read_table().
read_table()
static int read_table (GetBitContext * gb, Table * t, const int8_t code_pred_coeff[3][3], int length_bits, int coeff_bits, int is_signed, int offset) static
Definition at line 139 of file dstdec.c.
Referenced by decode_frame().
ac_init()
static void ac_init (ArithCoder * ac, GetBitContext * gb) static
Definition at line 171 of file dstdec.c.
Referenced by decode_frame().
ac_get()
static av_always_inline void ac_get (ArithCoder * ac, GetBitContext * gb, int p, int * e) static
Definition at line 177 of file dstdec.c.
Referenced by decode_frame().
prob_dst_x_bit()
static uint8_t prob_dst_x_bit (int c) static
Definition at line 198 of file dstdec.c.
Referenced by decode_frame().
build_filter()
static void build_filter (int16_t table[DST_MAX_ELEMENTS][16][256], const Table * fsets) static
Definition at line 203 of file dstdec.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame_ptr, AVPacket * avpkt) static
Definition at line 224 of file dstdec.c.
Variable Documentation
fsets_code_pred_coeff
const int8_t fsets_code_pred_coeff[3][3] static
Initial value:
= {
    {  -8 },
    { -16,  8 },
    {  -9, -5, 6 },
}
Definition at line 44 of file dstdec.c.
Referenced by decode_frame().
probs_code_pred_coeff
const int8_t probs_code_pred_coeff[3][3] static
Initial value:
= {
    {  -8 },
    { -16,  8 },
    { -24, 24, -8 },
}
Definition at line 50 of file dstdec.c.
Referenced by decode_frame().
ff_dst_decoder
AVCodec ff_dst_decoder
Initial value:
= {
    .name           = "dst",
    .long_name      = NULL_IF_CONFIG_SMALL("DST (Digital Stream Transfer)"),
    .type           = AVMEDIA_TYPE_AUDIO,
    .id             = AV_CODEC_ID_DST,
    .priv_data_size = sizeof(DSTContext),
    .init           = decode_init,
    .decode         = decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
    .sample_fmts    = (const enum AVSampleFormat[]) { AV_SAMPLE_FMT_FLT,
                                                      AV_SAMPLE_FMT_NONE },
}
Definition at line 363 of file dstdec.c.