FFmpeg: libavformat/dump.c File Reference
dump.c File Reference
#include <stdio.h>
#include <stdint.h>
#include "libavutil/channel_layout.h"
#include "libavutil/display.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/log.h"
#include "libavutil/mastering_display_metadata.h"
#include "libavutil/mathematics.h"
#include "libavutil/opt.h"
#include "libavutil/avstring.h"
#include "libavutil/replaygain.h"
#include "libavutil/spherical.h"
#include "libavutil/stereo3d.h"
#include "avformat.h"
Macros
#define HEXDUMP_PRINT(...)
Functions
static void hex_dump_internal (void *avcl, FILE *f, int level, const uint8_t *buf, int size)
void av_hex_dump (FILE *f, const uint8_t *buf, int size)
Send a nice hexadecimal dump of a buffer to the specified file stream.
void av_hex_dump_log (void *avcl, int level, const uint8_t *buf, int size)
Send a nice hexadecimal dump of a buffer to the log.
static void pkt_dump_internal (void *avcl, FILE *f, int level, const AVPacket *pkt, int dump_payload, AVRational time_base)
void av_pkt_dump2 (FILE *f, const AVPacket *pkt, int dump_payload, const AVStream *st)
Send a nice dump of a packet to the specified file stream.
void av_pkt_dump_log2 (void *avcl, int level, const AVPacket *pkt, int dump_payload, const AVStream *st)
Send a nice dump of a packet to the log.
static void print_fps (double d, const char *postfix)
static void dump_metadata (void *ctx, AVDictionary *m, const char *indent)
static void dump_paramchange (void *ctx, AVPacketSideData *sd)
static void print_gain (void *ctx, const char *str, int32_t gain)
static void print_peak (void *ctx, const char *str, uint32_t peak)
static void dump_replaygain (void *ctx, AVPacketSideData *sd)
static void dump_stereo3d (void *ctx, AVPacketSideData *sd)
static void dump_audioservicetype (void *ctx, AVPacketSideData *sd)
static void dump_cpb (void *ctx, AVPacketSideData *sd)
static void dump_mastering_display_metadata (void *ctx, AVPacketSideData *sd)
static void dump_spherical (void *ctx, AVPacketSideData *sd)
static void dump_sidedata (void *ctx, AVStream *st, const char *indent)
static void dump_stream_format (AVFormatContext *ic, int i, int index, int is_output)
void av_dump_format (AVFormatContext *ic, int index, const char *url, int is_output)
Print detailed information about the input or output format, such as duration, bitrate, streams, container, programs, metadata, side data, codec and time base.
Macro Definition Documentation
HEXDUMP_PRINT
#define HEXDUMP_PRINT (...)
Value:
do {                                                                      \
        if (!f)                                                               \
            av_log(avcl, level, __VA_ARGS__);                                 \
        else                                                                  \
            fprintf(f, __VA_ARGS__);                                          \
    } while (0)
Definition at line 39 of file dump.c.
Referenced by hex_dump_internal(), and pkt_dump_internal().
Function Documentation
hex_dump_internal()
static void hex_dump_internal (void * avcl, FILE * f, int level, const uint8_t * buf, int size) static
Definition at line 47 of file dump.c.
Referenced by av_hex_dump(), av_hex_dump_log(), and pkt_dump_internal().
pkt_dump_internal()
static void pkt_dump_internal (void * avcl, FILE * f, int level, const AVPacket * pkt, int dump_payload, AVRational time_base) static
Definition at line 84 of file dump.c.
Referenced by av_pkt_dump2(), and av_pkt_dump_log2().
print_fps()
static void print_fps (double d, const char * postfix) static
Definition at line 120 of file dump.c.
Referenced by dump_stream_format().
dump_metadata()
static void dump_metadata (void * ctx, AVDictionary * m, const char * indent) static
Definition at line 133 of file dump.c.
Referenced by av_dump_format(), and dump_stream_format().
dump_paramchange()
static void dump_paramchange (void * ctx, AVPacketSideData * sd) static
Definition at line 160 of file dump.c.
Referenced by dump_sidedata().
print_gain()
static void print_gain (void * ctx, const char * str, int32_t gain) static
Definition at line 217 of file dump.c.
Referenced by dump_replaygain().
print_peak()
static void print_peak (void * ctx, const char * str, uint32_t peak) static
Definition at line 227 of file dump.c.
Referenced by dump_replaygain().
dump_replaygain()
static void dump_replaygain (void * ctx, AVPacketSideData * sd) static
Definition at line 237 of file dump.c.
Referenced by dump_sidedata().
dump_stereo3d()
static void dump_stereo3d (void * ctx, AVPacketSideData * sd) static
Definition at line 253 of file dump.c.
Referenced by dump_sidedata().
dump_audioservicetype()
static void dump_audioservicetype (void * ctx, AVPacketSideData * sd) static
Definition at line 270 of file dump.c.
Referenced by dump_sidedata().
dump_cpb()
static void dump_cpb (void * ctx, AVPacketSideData * sd) static
Definition at line 313 of file dump.c.
Referenced by dump_sidedata().
dump_mastering_display_metadata()
static void dump_mastering_display_metadata (void * ctx, AVPacketSideData * sd) static
Definition at line 329 of file dump.c.
Referenced by dump_sidedata().
dump_spherical()
static void dump_spherical (void * ctx, AVPacketSideData * sd) static
Definition at line 346 of file dump.c.
Referenced by dump_sidedata().
dump_sidedata()
static void dump_sidedata (void * ctx, AVStream * st, const char * indent) static
Definition at line 371 of file dump.c.
Referenced by dump_stream_format().
dump_stream_format()
static void dump_stream_format (AVFormatContext * ic, int i, int index, int is_output) static
Definition at line 437 of file dump.c.
Referenced by av_dump_format().