FFmpeg: libavdevice/dv1394.c File Reference
dv1394.c File Reference
#include "config.h"
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <poll.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include "libavutil/internal.h"
#include "libavutil/log.h"
#include "libavutil/opt.h"
#include "avdevice.h"
#include "libavformat/dv.h"
#include "dv1394.h"
Data Structures
struct dv1394_data
Functions
static int dv1394_reset (struct dv1394_data *dv)
static int dv1394_start (struct dv1394_data *dv)
static int dv1394_read_header (AVFormatContext *context)
static int dv1394_read_packet (AVFormatContext *context, AVPacket *pkt)
static int dv1394_close (AVFormatContext *context)
Variables
static const AVOption options []
static const AVClass dv1394_class
AVInputFormat ff_dv1394_demuxer
Function Documentation
dv1394_reset()
static int dv1394_reset (struct dv1394_data * dv) static
Definition at line 57 of file dv1394.c.
Referenced by dv1394_read_header(), and dv1394_read_packet().
dv1394_start()
static int dv1394_start (struct dv1394_data * dv) static
Definition at line 73 of file dv1394.c.
Referenced by dv1394_read_header(), and dv1394_read_packet().
dv1394_read_header()
static int dv1394_read_header (AVFormatContext * context) static
Definition at line 83 of file dv1394.c.
dv1394_read_packet()
static int dv1394_read_packet (AVFormatContext * context, AVPacket * pkt) static
Definition at line 120 of file dv1394.c.
dv1394_close()
static int dv1394_close (AVFormatContext * context) static
Definition at line 196 of file dv1394.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "standard", "", 0x42, AV_OPT_TYPE_INT, {.i64 = DV1394_NTSC}, DV1394_NTSC, DV1394_PAL, AV_OPT_FLAG_DECODING_PARAM, "standard" },
    { "PAL",      "", 0, AV_OPT_TYPE_CONST, {.i64 = DV1394_PAL},   0, 0, AV_OPT_FLAG_DECODING_PARAM, "standard" },
    { "NTSC",     "", 0, AV_OPT_TYPE_CONST, {.i64 = DV1394_NTSC},  0, 0, AV_OPT_FLAG_DECODING_PARAM, "standard" },
    { "channel",  "", 0x42, AV_OPT_TYPE_INT, {.i64 = DV1394_DEFAULT_CHANNEL}, 0, INT_MAX, AV_OPT_FLAG_DECODING_PARAM },
    { NULL },
}
Definition at line 214 of file dv1394.c.
dv1394_class
const AVClass dv1394_class static
Initial value:
= {
    .class_name = "DV1394 indev",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
    .category   = AV_CLASS_CATEGORY_DEVICE_VIDEO_INPUT,
}
Definition at line 222 of file dv1394.c.
ff_dv1394_demuxer
AVInputFormat ff_dv1394_demuxer
Initial value:
= {
    .name           = "dv1394",
    .long_name      = NULL_IF_CONFIG_SMALL("DV1394 A/V grab"),
    .priv_data_size = sizeof(struct dv1394_data),
    .read_header    = dv1394_read_header,
    .read_packet    = dv1394_read_packet,
    .read_close     = dv1394_close,
    .flags          = AVFMT_NOFILE,
    .priv_class     = &dv1394_class,
}
Definition at line 230 of file dv1394.c.