FFmpeg: libavcodec/dv_profile_internal.h File Reference
dv_profile_internal.h File Reference
#include "dv_profile.h"
Functions
void ff_dv_print_profiles (void *logctx, int loglevel)
Print all allowed DV profiles into logctx at specified logging level.
const AVDVProfile * ff_dv_frame_profile (AVCodecContext *codec, const AVDVProfile *sys, const uint8_t *frame, unsigned buf_size)
Get a DV profile for the provided compressed frame.
Function Documentation
ff_dv_print_profiles()
void ff_dv_print_profiles (void * logctx, int loglevel)
Print all allowed DV profiles into logctx at specified logging level.
Referenced by dvvideo_encode_init().
ff_dv_frame_profile()
const AVDVProfile* ff_dv_frame_profile (AVCodecContext * codec, const AVDVProfile * sys, const uint8_t * frame, unsigned buf_size)
Get a DV profile for the provided compressed frame.
Definition at line 260 of file dv_profile.c.
Referenced by av_dv_frame_profile(), and dvvideo_decode_frame().