FFmpeg: libavcodec/dv_profile.c File Reference
dv_profile.c File Reference
#include "config.h"
#include <stdint.h>
#include "libavutil/common.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/log.h"
#include "libavutil/pixdesc.h"
#include "avcodec.h"
#include "dv_profile.h"
#include "dv_profile_internal.h"
Functions
const AVDVProfile * ff_dv_frame_profile (AVCodecContext *codec, const AVDVProfile *sys, const uint8_t *frame, unsigned buf_size)
Get a DV profile for the provided compressed frame.
const AVDVProfile * av_dv_frame_profile (const AVDVProfile *sys, const uint8_t *frame, unsigned buf_size)
Get a DV profile for the provided compressed frame.
const AVDVProfile * av_dv_codec_profile (int width, int height, enum AVPixelFormat pix_fmt)
Get a DV profile for the provided stream parameters.
const AVDVProfile * av_dv_codec_profile2 (int width, int height, enum AVPixelFormat pix_fmt, AVRational frame_rate)
Get a DV profile for the provided stream parameters.
Function Documentation
ff_dv_frame_profile()
const AVDVProfile* ff_dv_frame_profile (AVCodecContext * codec, const AVDVProfile * sys, const uint8_t * frame, unsigned buf_size)
Get a DV profile for the provided compressed frame.
Definition at line 260 of file dv_profile.c.
Referenced by av_dv_frame_profile(), and dvvideo_decode_frame().
av_dv_frame_profile()
const AVDVProfile* av_dv_frame_profile (const AVDVProfile * sys, const uint8_t * frame, unsigned buf_size)
Get a DV profile for the provided compressed frame.
Parameters
sys the profile used for the previous frame, may be NULL
frame the compressed data buffer
buf_size size of the buffer in bytes
Returns
the DV profile for the supplied data or NULL on failure
Definition at line 300 of file dv_profile.c.
Referenced by avpriv_dv_produce_packet(), and dv_read_header().
av_dv_codec_profile()
const AVDVProfile* av_dv_codec_profile (int width, int height, enum AVPixelFormat pix_fmt)
Get a DV profile for the provided stream parameters.
Definition at line 306 of file dv_profile.c.
av_dv_codec_profile2()
const AVDVProfile* av_dv_codec_profile2 (int width, int height, enum AVPixelFormat pix_fmt, AVRational frame_rate)
Get a DV profile for the provided stream parameters.
The frame rate is used as a best-effort parameter.
Definition at line 316 of file dv_profile.c.
Referenced by av_dv_codec_profile(), dv_init_mux(), and dvvideo_encode_init().