FFmpeg: libavcodec/dvbsubdec.c File Reference
dvbsubdec.c File Reference
#include "avcodec.h"
#include "get_bits.h"
#include "bytestream.h"
#include "internal.h"
#include "libavutil/colorspace.h"
#include "libavutil/opt.h"
Data Structures
struct DVBSubCLUT
struct DVBSubObjectDisplay
struct DVBSubObject
struct DVBSubRegionDisplay
struct DVBSubRegion
struct DVBSubDisplayDefinition
struct DVBSubContext
Macros
#define DVBSUB_PAGE_SEGMENT 0x10
#define DVBSUB_REGION_SEGMENT 0x11
#define DVBSUB_CLUT_SEGMENT 0x12
#define DVBSUB_OBJECT_SEGMENT 0x13
#define DVBSUB_DISPLAYDEFINITION_SEGMENT 0x14
#define DVBSUB_DISPLAY_SEGMENT 0x80
#define cm (ff_crop_tab + MAX_NEG_CROP)
#define RGBA(r, g, b, a) (((unsigned)(a) << 24) | ((r) << 16) | ((g) << 8) | (b))
#define V(x, y) rect->data[0][(x) + (y)*rect->linesize[0]]
#define L(x, y) list[ rect->data[0][(x) + (y)*rect->linesize[0]] ]
#define DS AV_OPT_FLAG_DECODING_PARAM | AV_OPT_FLAG_SUBTITLE_PARAM
Functions
static DVBSubObject * get_object (DVBSubContext *ctx, int object_id)
static DVBSubCLUT * get_clut (DVBSubContext *ctx, int clut_id)
static DVBSubRegion * get_region (DVBSubContext *ctx, int region_id)
static void delete_region_display_list (DVBSubContext *ctx, DVBSubRegion *region)
static void delete_cluts (DVBSubContext *ctx)
static void delete_objects (DVBSubContext *ctx)
static void delete_regions (DVBSubContext *ctx)
static av_cold int dvbsub_init_decoder (AVCodecContext *avctx)
static av_cold int dvbsub_close_decoder (AVCodecContext *avctx)
static int dvbsub_read_2bit_string (AVCodecContext *avctx, uint8_t *destbuf, int dbuf_len, const uint8_t **srcbuf, int buf_size, int non_mod, uint8_t *map_table, int x_pos)
static int dvbsub_read_4bit_string (AVCodecContext *avctx, uint8_t *destbuf, int dbuf_len, const uint8_t **srcbuf, int buf_size, int non_mod, uint8_t *map_table, int x_pos)
static int dvbsub_read_8bit_string (AVCodecContext *avctx, uint8_t *destbuf, int dbuf_len, const uint8_t **srcbuf, int buf_size, int non_mod, uint8_t *map_table, int x_pos)
static void compute_default_clut (AVSubtitleRect *rect, int w, int h)
static int save_subtitle_set (AVCodecContext *avctx, AVSubtitle *sub, int *got_output)
static void dvbsub_parse_pixel_data_block (AVCodecContext *avctx, DVBSubObjectDisplay *display, const uint8_t *buf, int buf_size, int top_bottom, int non_mod)
static int dvbsub_parse_object_segment (AVCodecContext *avctx, const uint8_t *buf, int buf_size)
static int dvbsub_parse_clut_segment (AVCodecContext *avctx, const uint8_t *buf, int buf_size)
static int dvbsub_parse_region_segment (AVCodecContext *avctx, const uint8_t *buf, int buf_size)
static int dvbsub_parse_page_segment (AVCodecContext *avctx, const uint8_t *buf, int buf_size, AVSubtitle *sub, int *got_output)
static int dvbsub_parse_display_definition_segment (AVCodecContext *avctx, const uint8_t *buf, int buf_size)
static int dvbsub_display_end_segment (AVCodecContext *avctx, const uint8_t *buf, int buf_size, AVSubtitle *sub, int *got_output)
static int dvbsub_decode (AVCodecContext *avctx, void *data, int *data_size, AVPacket *avpkt)
Variables
static DVBSubCLUT default_clut
static const AVOption options []
static const AVClass dvbsubdec_class
AVCodec ff_dvbsub_decoder
Macro Definition Documentation
DVBSUB_PAGE_SEGMENT
#define DVBSUB_PAGE_SEGMENT 0x10
Definition at line 29 of file dvbsubdec.c.
Referenced by dvbsub_decode().
DVBSUB_REGION_SEGMENT
#define DVBSUB_REGION_SEGMENT 0x11
Definition at line 30 of file dvbsubdec.c.
Referenced by dvbsub_decode().
DVBSUB_CLUT_SEGMENT
#define DVBSUB_CLUT_SEGMENT 0x12
Definition at line 31 of file dvbsubdec.c.
Referenced by dvbsub_decode().
DVBSUB_OBJECT_SEGMENT
#define DVBSUB_OBJECT_SEGMENT 0x13
Definition at line 32 of file dvbsubdec.c.
Referenced by dvbsub_decode().
DVBSUB_DISPLAYDEFINITION_SEGMENT
#define DVBSUB_DISPLAYDEFINITION_SEGMENT 0x14
Definition at line 33 of file dvbsubdec.c.
Referenced by dvbsub_decode().
DVBSUB_DISPLAY_SEGMENT
#define DVBSUB_DISPLAY_SEGMENT 0x80
Definition at line 34 of file dvbsubdec.c.
Referenced by dvbsub_decode().
cm
#define cm (ff_crop_tab + MAX_NEG_CROP)
Definition at line 36 of file dvbsubdec.c.
Referenced by celt_decode_band(), celt_decode_bands(), ff_put_vp8_epel16_h4_mmi(), ff_put_vp8_epel16_h4v4_mmi(), ff_put_vp8_epel16_h4v6_mmi(), ff_put_vp8_epel16_h6_mmi(), ff_put_vp8_epel16_h6v4_mmi(), ff_put_vp8_epel16_h6v6_mmi(), ff_put_vp8_epel16_v4_mmi(), ff_put_vp8_epel16_v6_mmi(), ff_put_vp8_epel4_h4_mmi(), ff_put_vp8_epel4_h4v4_mmi(), ff_put_vp8_epel4_h4v6_mmi(), ff_put_vp8_epel4_h6_mmi(), ff_put_vp8_epel4_h6v4_mmi(), ff_put_vp8_epel4_h6v6_mmi(), ff_put_vp8_epel4_v4_mmi(), ff_put_vp8_epel4_v6_mmi(), ff_put_vp8_epel8_h4_mmi(), ff_put_vp8_epel8_h4v4_mmi(), ff_put_vp8_epel8_h4v6_mmi(), ff_put_vp8_epel8_h6_mmi(), ff_put_vp8_epel8_h6v4_mmi(), ff_put_vp8_epel8_h6v6_mmi(), ff_put_vp8_epel8_v4_mmi(), ff_put_vp8_epel8_v6_mmi(), filter_common(), filter_mbedge(), h_block_filter(), intra_pred_plane(), mp_yuv_to_rgb(), parse_ifo_palette(), parse_palette_segment(), pick_color(), pred16x16_tm_vp8_c(), pred4x4_tm_vp8_c(), pred8x8_tm_vp8_c(), query_codec(), refine_colors(), rv30_weak_loop_filter(), rv40_weak_loop_filter(), v_block_filter(), vp8_filter_common_is4tap(), vp8_filter_common_isnot4tap(), wmv2_mspel8_h_lowpass(), wmv2_mspel8_v_lowpass(), and yuv_a_to_rgba().
RGBA
#define RGBA (r, g, b, a) (((unsigned)(a) << 24) | ((r) << 16) | ((g) << 8) | (b))
Definition at line 153 of file dvbsubdec.c.
Referenced by compute_default_clut(), dvbsub_init_decoder(), dvbsub_parse_clut_segment(), ff_sws_init_swscale_x86(), and findRgbConvFn().
V
#define V (x, y) rect->data[0][(x) + (y)*rect->linesize[0]]
Referenced by compute_default_clut().
L
#define L (x, y) list[ rect->data[0][(x) + (y)*rect->linesize[0]] ]
Referenced by compute_default_clut().
DS
#define DS AV_OPT_FLAG_DECODING_PARAM | AV_OPT_FLAG_SUBTITLE_PARAM
Definition at line 1732 of file dvbsubdec.c.
Function Documentation
get_object()
static DVBSubObject* get_object (DVBSubContext * ctx, int object_id) static
Definition at line 252 of file dvbsubdec.c.
Referenced by delete_region_display_list(), dvbsub_parse_object_segment(), and dvbsub_parse_region_segment().
get_clut()
static DVBSubCLUT* get_clut (DVBSubContext * ctx, int clut_id) static
Definition at line 263 of file dvbsubdec.c.
Referenced by dvbsub_parse_clut_segment(), dvbsub_parse_page_segment(), and save_subtitle_set().
get_region()
static DVBSubRegion* get_region (DVBSubContext * ctx, int region_id) static
Definition at line 274 of file dvbsubdec.c.
Referenced by dvbsub_parse_page_segment(), dvbsub_parse_pixel_data_block(), dvbsub_parse_region_segment(), and save_subtitle_set().
delete_region_display_list()
static void delete_region_display_list (DVBSubContext * ctx, DVBSubRegion * region) static
Definition at line 285 of file dvbsubdec.c.
Referenced by delete_regions(), and dvbsub_parse_region_segment().
delete_cluts()
static void delete_cluts (DVBSubContext * ctx) static
Definition at line 331 of file dvbsubdec.c.
Referenced by dvbsub_close_decoder(), and dvbsub_parse_page_segment().
delete_objects()
static void delete_objects (DVBSubContext * ctx) static
Definition at line 342 of file dvbsubdec.c.
Referenced by dvbsub_close_decoder(), and dvbsub_parse_page_segment().
delete_regions()
static void delete_regions (DVBSubContext * ctx) static
Definition at line 353 of file dvbsubdec.c.
Referenced by dvbsub_close_decoder(), and dvbsub_parse_page_segment().
dvbsub_init_decoder()
static av_cold int dvbsub_init_decoder (AVCodecContext * avctx) static
Definition at line 367 of file dvbsubdec.c.
dvbsub_close_decoder()
static av_cold int dvbsub_close_decoder (AVCodecContext * avctx) static
Definition at line 456 of file dvbsubdec.c.
dvbsub_read_2bit_string()
static int dvbsub_read_2bit_string (AVCodecContext * avctx, uint8_t * destbuf, int dbuf_len, const uint8_t ** srcbuf, int buf_size, int non_mod, uint8_t * map_table, int x_pos) static
Definition at line 479 of file dvbsubdec.c.
Referenced by dvbsub_parse_pixel_data_block().
dvbsub_read_4bit_string()
static int dvbsub_read_4bit_string (AVCodecContext * avctx, uint8_t * destbuf, int dbuf_len, const uint8_t ** srcbuf, int buf_size, int non_mod, uint8_t * map_table, int x_pos) static
Definition at line 587 of file dvbsubdec.c.
Referenced by dvbsub_parse_pixel_data_block().
dvbsub_read_8bit_string()
static int dvbsub_read_8bit_string (AVCodecContext * avctx, uint8_t * destbuf, int dbuf_len, const uint8_t ** srcbuf, int buf_size, int non_mod, uint8_t * map_table, int x_pos) static
Definition at line 710 of file dvbsubdec.c.
Referenced by dvbsub_parse_pixel_data_block().
compute_default_clut()
static void compute_default_clut (AVSubtitleRect * rect, int w, int h) static
Definition at line 764 of file dvbsubdec.c.
Referenced by save_subtitle_set().
save_subtitle_set()
static int save_subtitle_set (AVCodecContext * avctx, AVSubtitle * sub, int * got_output) static
Definition at line 821 of file dvbsubdec.c.
Referenced by dvbsub_display_end_segment(), and dvbsub_parse_page_segment().
dvbsub_parse_pixel_data_block()
static void dvbsub_parse_pixel_data_block (AVCodecContext * avctx, DVBSubObjectDisplay * display, const uint8_t * buf, int buf_size, int top_bottom, int non_mod) static
Definition at line 958 of file dvbsubdec.c.
Referenced by dvbsub_parse_object_segment().
dvbsub_parse_object_segment()
static int dvbsub_parse_object_segment (AVCodecContext * avctx, const uint8_t * buf, int buf_size) static
Definition at line 1074 of file dvbsubdec.c.
Referenced by dvbsub_decode().
dvbsub_parse_clut_segment()
static int dvbsub_parse_clut_segment (AVCodecContext * avctx, const uint8_t * buf, int buf_size) static
Definition at line 1134 of file dvbsubdec.c.
Referenced by dvbsub_decode().
dvbsub_parse_region_segment()
static int dvbsub_parse_region_segment (AVCodecContext * avctx, const uint8_t * buf, int buf_size) static
Definition at line 1233 of file dvbsubdec.c.
Referenced by dvbsub_decode().
dvbsub_parse_page_segment()
static int dvbsub_parse_page_segment (AVCodecContext * avctx, const uint8_t * buf, int buf_size, AVSubtitle * sub, int * got_output) static
Definition at line 1363 of file dvbsubdec.c.
Referenced by dvbsub_decode().
dvbsub_parse_display_definition_segment()
static int dvbsub_parse_display_definition_segment (AVCodecContext * avctx, const uint8_t * buf, int buf_size) static
Definition at line 1553 of file dvbsubdec.c.
Referenced by dvbsub_decode().
dvbsub_display_end_segment()
static int dvbsub_display_end_segment (AVCodecContext * avctx, const uint8_t * buf, int buf_size, AVSubtitle * sub, int * got_output) static
Definition at line 1599 of file dvbsubdec.c.
Referenced by dvbsub_decode().
dvbsub_decode()
static int dvbsub_decode (AVCodecContext * avctx, void * data, int * data_size, AVPacket * avpkt) static
Definition at line 1612 of file dvbsubdec.c.
Variable Documentation
default_clut
DVBSubCLUT default_clut static
Definition at line 166 of file dvbsubdec.c.
Referenced by dvbsub_parse_page_segment(), and save_subtitle_set().
options
const AVOption options[] static
Initial value:
= {
    {"compute_edt", "compute end of time using pts or timeout", 0x42, AV_OPT_TYPE_BOOL, {.i64 = 0}, 0, 1, DS},
    {"compute_clut", "compute clut when not available(-1) or always(1) or never(0)", 0x42, AV_OPT_TYPE_BOOL, {.i64 = -1}, -1, 1, DS},
    {"dvb_substream", "", 0x42, AV_OPT_TYPE_INT, {.i64 = -1}, -1, 63, DS},
    {NULL}
}
Definition at line 1733 of file dvbsubdec.c.
dvbsubdec_class
const AVClass dvbsubdec_class static
Initial value:
= {
    .class_name = "DVB Sub Decoder",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1739 of file dvbsubdec.c.
ff_dvbsub_decoder
AVCodec ff_dvbsub_decoder
Initial value:
= {
    .name           = "dvbsub",
    .long_name      = NULL_IF_CONFIG_SMALL("DVB subtitles"),
    .type           = AVMEDIA_TYPE_SUBTITLE,
    .id             = AV_CODEC_ID_DVB_SUBTITLE,
    .priv_data_size = sizeof(DVBSubContext),
    .init           = dvbsub_init_decoder,
    .close          = dvbsub_close_decoder,
    .decode         = dvbsub_decode,
    .priv_class     = &dvbsubdec_class,
}
Definition at line 1746 of file dvbsubdec.c.