FFmpeg: libavcodec/dvbtxt.h File Reference
dvbtxt.h File Reference
#include "libavutil/attributes.h"
Functions
static av_always_inline int ff_data_identifier_is_teletext (int data_identifier)
static av_always_inline int ff_data_unit_id_is_teletext (int data_unit_id)
Function Documentation
ff_data_identifier_is_teletext()
static av_always_inline int ff_data_identifier_is_teletext (int data_identifier) static
Definition at line 28 of file dvbtxt.h.
Referenced by dvbtxt_probe(), and teletext_decode_frame().
ff_data_unit_id_is_teletext()
static av_always_inline int ff_data_unit_id_is_teletext (int data_unit_id) static
Definition at line 36 of file dvbtxt.h.
Referenced by dvbtxt_probe(), and slice_to_vbi_lines().