FFmpeg: libavcodec/dvdec.c File Reference
dvdec.c File Reference
DV decoder.
#include "libavutil/avassert.h"
#include "libavutil/imgutils.h"
#include "libavutil/internal.h"
#include "libavutil/pixdesc.h"
#include "avcodec.h"
#include "dv.h"
#include "dv_profile_internal.h"
#include "dvdata.h"
#include "get_bits.h"
#include "idctdsp.h"
#include "internal.h"
#include "put_bits.h"
#include "simple_idct.h"
Data Structures
struct BlockInfo
Functions
static void dv_init_weight_tables (DVVideoContext *ctx, const AVDVProfile *d)
static av_cold int dvvideo_decode_init (AVCodecContext *avctx)
static void dv_decode_ac (GetBitContext *gb, BlockInfo *mb, int16_t *block)
static void bit_copy (PutBitContext *pb, GetBitContext *gb)
static int dv_decode_video_segment (AVCodecContext *avctx, void *arg)
static int dvvideo_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
Variables
static const int dv_iweight_bits = 14
static const uint16_t dv_iweight_88 [64]
static const uint16_t dv_iweight_248 [64]
static const uint16_t dv_iweight_1080_y [64]
The "inverse" DV100 weights are actually just the spec weights (zig-zagged).
static const uint16_t dv_iweight_1080_c [64]
static const uint16_t dv_iweight_720_y [64]
static const uint16_t dv_iweight_720_c [64]
AVCodec ff_dvvideo_decoder
Detailed Description
DV decoder.
Definition in file dvdec.c.
Function Documentation
dv_init_weight_tables()
static void dv_init_weight_tables (DVVideoContext * ctx, const AVDVProfile * d) static
Definition at line 130 of file dvdec.c.
Referenced by dvvideo_decode_frame().
dvvideo_decode_init()
static av_cold int dvvideo_decode_init (AVCodecContext * avctx) static
Definition at line 176 of file dvdec.c.
dv_decode_ac()
static void dv_decode_ac (GetBitContext * gb, BlockInfo * mb, int16_t * block) static
Definition at line 203 of file dvdec.c.
Referenced by dv_decode_video_segment().
bit_copy()
static void bit_copy (PutBitContext * pb, GetBitContext * gb) inline static
Definition at line 263 of file dvdec.c.
Referenced by dv_decode_video_segment().
dv_decode_video_segment()
static int dv_decode_video_segment (AVCodecContext * avctx, void * arg) static
Definition at line 275 of file dvdec.c.
Referenced by dvvideo_decode_frame().
dvvideo_decode_frame()
static int dvvideo_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 496 of file dvdec.c.
Variable Documentation
dv_iweight_bits
const int dv_iweight_bits = 14 static
Definition at line 63 of file dvdec.c.
Referenced by dv_decode_ac().
dv_iweight_88
const uint16_t dv_iweight_88[64] static
Initial value:
= {
    32768, 16705, 16705, 17734, 17032, 17734, 18205, 18081,
    18081, 18205, 18725, 18562, 19195, 18562, 18725, 19266,
    19091, 19705, 19705, 19091, 19266, 21407, 19643, 20267,
    20228, 20267, 19643, 21407, 22725, 21826, 20853, 20806,
    20806, 20853, 21826, 22725, 23170, 23170, 21407, 21400,
    21407, 23170, 23170, 24598, 23786, 22018, 22018, 23786,
    24598, 25251, 24465, 22654, 24465, 25251, 25972, 25172,
    25172, 25972, 26722, 27969, 26722, 29692, 29692, 31521,
}
Definition at line 65 of file dvdec.c.
Referenced by dv_init_weight_tables().
dv_iweight_248
const uint16_t dv_iweight_248[64] static
Initial value:
= {
    32768, 16384, 16705, 16705, 17734, 17734, 17734, 17734,
    18081, 18081, 18725, 18725, 21407, 21407, 19091, 19091,
    19195, 19195, 18205, 18205, 18725, 18725, 19705, 19705,
    20267, 20267, 21826, 21826, 23170, 23170, 20806, 20806,
    20267, 20267, 19266, 19266, 21407, 21407, 20853, 20853,
    21400, 21400, 23786, 23786, 24465, 24465, 22018, 22018,
    23170, 23170, 22725, 22725, 24598, 24598, 24465, 24465,
    25172, 25172, 27969, 27969, 25972, 25972, 29692, 29692
}
Definition at line 75 of file dvdec.c.
Referenced by dv_init_weight_tables().
dv_iweight_1080_y
const uint16_t dv_iweight_1080_y[64] static
Initial value:
= {
    128,  16,  16,  17,  17,  17,  18,  18,
     18,  18,  18,  18,  19,  18,  18,  19,
     19,  19,  19,  19,  19,  42,  38,  40,
     40,  40,  38,  42,  44,  43,  41,  41,
     41,  41,  43,  44,  45,  45,  42,  42,
     42,  45,  45,  48,  46,  43,  43,  46,
     48,  49,  48,  44,  48,  49, 101,  98,
     98, 101, 104, 109, 104, 116, 116, 123,
}
The "inverse" DV100 weights are actually just the spec weights (zig-zagged).
Definition at line 89 of file dvdec.c.
Referenced by dv_init_weight_tables().
dv_iweight_1080_c
const uint16_t dv_iweight_1080_c[64] static
Initial value:
= {
    128,  16,  16,  17,  17,  17,  25,  25,
     25,  25,  26,  25,  26,  25,  26,  26,
     26,  27,  27,  26,  26,  42,  38,  40,
     40,  40,  38,  42,  44,  43,  41,  41,
     41,  41,  43,  44,  91,  91,  84,  84,
     84,  91,  91,  96,  93,  86,  86,  93,
     96, 197, 191, 177, 191, 197, 203, 197,
    197, 203, 209, 219, 209, 232, 232, 246,
}
Definition at line 99 of file dvdec.c.
Referenced by dv_init_weight_tables().
dv_iweight_720_y
const uint16_t dv_iweight_720_y[64] static
Initial value:
= {
    128,  16,  16,  17,  17,  17,  18,  18,
     18,  18,  18,  18,  19,  18,  18,  19,
     19,  19,  19,  19,  19,  42,  38,  40,
     40,  40,  38,  42,  44,  43,  41,  41,
     41,  41,  43,  44,  68,  68,  63,  63,
     63,  68,  68,  96,  92,  86,  86,  92,
     96,  98,  96,  88,  96,  98, 202, 196,
    196, 202, 208, 218, 208, 232, 232, 246,
}
Definition at line 109 of file dvdec.c.
Referenced by dv_init_weight_tables().
dv_iweight_720_c
const uint16_t dv_iweight_720_c[64] static
Initial value:
= {
    128,  24,  24,  26,  26,  26,  36,  36,
     36,  36,  36,  36,  38,  36,  36,  38,
     38,  38,  38,  38,  38,  84,  76,  80,
     80,  80,  76,  84,  88,  86,  82,  82,
     82,  82,  86,  88, 182, 182, 168, 168,
    168, 182, 182, 192, 186, 192, 172, 186,
    192, 394, 382, 354, 382, 394, 406, 394,
    394, 406, 418, 438, 418, 464, 464, 492,
}
Definition at line 119 of file dvdec.c.
Referenced by dv_init_weight_tables().
ff_dvvideo_decoder
AVCodec ff_dvvideo_decoder
Initial value:
= {
    .name           = "dvvideo",
    .long_name      = NULL_IF_CONFIG_SMALL("DV (Digital Video)"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_DVVIDEO,
    .priv_data_size = sizeof(DVVideoContext),
    .init           = dvvideo_decode_init,
    .decode         = dvvideo_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_SLICE_THREADS,
    .max_lowres     = 3,
}
Definition at line 564 of file dvdec.c.