FFmpeg: libavcodec/dvdsubdec.c File Reference
dvdsubdec.c File Reference
#include "avcodec.h"
#include "get_bits.h"
#include "internal.h"
#include "libavutil/attributes.h"
#include "libavutil/colorspace.h"
#include "libavutil/opt.h"
#include "libavutil/imgutils.h"
#include "libavutil/avstring.h"
#include "libavutil/bswap.h"
Data Structures
struct DVDSubContext
Macros
#define READ_OFFSET(a) (big_offsets ? AV_RB32(a) : AV_RB16(a))
#define OFFSET(field) offsetof(DVDSubContext, field)
#define SD AV_OPT_FLAG_SUBTITLE_PARAM | AV_OPT_FLAG_DECODING_PARAM
Functions
static void yuv_a_to_rgba (const uint8_t *ycbcr, const uint8_t *alpha, uint32_t *rgba, int num_values)
static int decode_run_2bit (GetBitContext *gb, int *color)
static int decode_run_8bit (GetBitContext *gb, int *color)
static int decode_rle (uint8_t *bitmap, int linesize, int w, int h, const uint8_t *buf, int start, int buf_size, int is_8bit)
static void guess_palette (DVDSubContext *ctx, uint32_t *rgba_palette, uint32_t subtitle_color)
static void reset_rects (AVSubtitle *sub_header)
static int decode_dvd_subtitles (DVDSubContext *ctx, AVSubtitle *sub_header, const uint8_t *buf, int buf_size)
static int is_transp (const uint8_t *buf, int pitch, int n, const uint8_t *transp_color)
static int find_smallest_bounding_rectangle (AVSubtitle *s)
static int append_to_cached_buf (AVCodecContext *avctx, const uint8_t *buf, int buf_size)
static int dvdsub_decode (AVCodecContext *avctx, void *data, int *data_size, AVPacket *avpkt)
static void parse_palette (DVDSubContext *ctx, char *p)
static int parse_ifo_palette (DVDSubContext *ctx, char *p)
static int dvdsub_parse_extradata (AVCodecContext *avctx)
static av_cold int dvdsub_init (AVCodecContext *avctx)
static void dvdsub_flush (AVCodecContext *avctx)
static av_cold int dvdsub_close (AVCodecContext *avctx)
Variables
static const AVOption options []
static const AVClass dvdsub_class
AVCodec ff_dvdsub_decoder
Macro Definition Documentation
READ_OFFSET
#define READ_OFFSET (a) (big_offsets ? AV_RB32(a) : AV_RB16(a))
Definition at line 218 of file dvdsubdec.c.
Referenced by decode_dvd_subtitles().
OFFSET
#define OFFSET (field) offsetof(DVDSubContext, field)
Definition at line 769 of file dvdsubdec.c.
SD
#define SD AV_OPT_FLAG_SUBTITLE_PARAM | AV_OPT_FLAG_DECODING_PARAM
Definition at line 770 of file dvdsubdec.c.
Function Documentation
yuv_a_to_rgba()
static void yuv_a_to_rgba (const uint8_t * ycbcr, const uint8_t * alpha, uint32_t * rgba, int num_values) static
Definition at line 50 of file dvdsubdec.c.
Referenced by decode_dvd_subtitles().
decode_run_2bit()
static int decode_run_2bit (GetBitContext * gb, int * color) static
Definition at line 67 of file dvdsubdec.c.
Referenced by decode_rle().
decode_run_8bit()
static int decode_run_8bit (GetBitContext * gb, int * color) static
Definition at line 81 of file dvdsubdec.c.
Referenced by decode_rle().
decode_rle()
static int decode_rle (uint8_t * bitmap, int linesize, int w, int h, const uint8_t * buf, int start, int buf_size, int is_8bit) static
Definition at line 103 of file dvdsubdec.c.
Referenced by decode_dvd_subtitles().
guess_palette()
static void guess_palette (DVDSubContext * ctx, uint32_t * rgba_palette, uint32_t subtitle_color) static
Definition at line 146 of file dvdsubdec.c.
Referenced by decode_dvd_subtitles().
reset_rects()
static void reset_rects (AVSubtitle * sub_header) static
Definition at line 203 of file dvdsubdec.c.
Referenced by decode_dvd_subtitles(), and dvdsub_decode().
decode_dvd_subtitles()
static int decode_dvd_subtitles (DVDSubContext * ctx, AVSubtitle * sub_header, const uint8_t * buf, int buf_size) static
Definition at line 220 of file dvdsubdec.c.
Referenced by dvdsub_decode().
is_transp()
static int is_transp (const uint8_t * buf, int pitch, int n, const uint8_t * transp_color) static
Definition at line 438 of file dvdsubdec.c.
Referenced by find_smallest_bounding_rectangle().
find_smallest_bounding_rectangle()
static int find_smallest_bounding_rectangle (AVSubtitle * s) static
Definition at line 451 of file dvdsubdec.c.
Referenced by dvdsub_decode().
append_to_cached_buf()
static int append_to_cached_buf (AVCodecContext * avctx, const uint8_t * buf, int buf_size) static
Definition at line 546 of file dvdsubdec.c.
Referenced by dvdsub_decode().
dvdsub_decode()
static int dvdsub_decode (AVCodecContext * avctx, void * data, int * data_size, AVPacket * avpkt) static
Definition at line 563 of file dvdsubdec.c.
parse_palette()
static void parse_palette (DVDSubContext * ctx, char * p) static
Definition at line 622 of file dvdsubdec.c.
Referenced by dvdsub_init(), and dvdsub_parse_extradata().
parse_ifo_palette()
static int parse_ifo_palette (DVDSubContext * ctx, char * p) static
Definition at line 634 of file dvdsubdec.c.
Referenced by dvdsub_init().
dvdsub_parse_extradata()
static int dvdsub_parse_extradata (AVCodecContext * avctx) static
Definition at line 694 of file dvdsubdec.c.
Referenced by dvdsub_init().
dvdsub_init()
static av_cold int dvdsub_init (AVCodecContext * avctx) static
Definition at line 734 of file dvdsubdec.c.
dvdsub_flush()
static void dvdsub_flush (AVCodecContext * avctx) static
Definition at line 757 of file dvdsubdec.c.
Referenced by dvdsub_close().
dvdsub_close()
static av_cold int dvdsub_close (AVCodecContext * avctx) static
Definition at line 763 of file dvdsubdec.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "palette", "set the global palette", OFFSET(palette_str), AV_OPT_TYPE_STRING, { .str = NULL }, 0, 0, SD },
    { "ifo_palette", "obtain the global palette from .IFO file", OFFSET(ifo_str), AV_OPT_TYPE_STRING, { .str = NULL }, 0, 0, SD },
    { "forced_subs_only", "Only show forced subtitles", OFFSET(forced_subs_only), AV_OPT_TYPE_BOOL, {.i64 = 0}, 0, 1, SD},
    { NULL }
}
Definition at line 771 of file dvdsubdec.c.
dvdsub_class
const AVClass dvdsub_class static
Initial value:
= {
    .class_name = "dvdsubdec",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 777 of file dvdsubdec.c.
ff_dvdsub_decoder
AVCodec ff_dvdsub_decoder
Initial value:
= {
    .name           = "dvdsub",
    .long_name      = NULL_IF_CONFIG_SMALL("DVD subtitles"),
    .type           = AVMEDIA_TYPE_SUBTITLE,
    .id             = AV_CODEC_ID_DVD_SUBTITLE,
    .priv_data_size = sizeof(DVDSubContext),
    .init           = dvdsub_init,
    .decode         = dvdsub_decode,
    .flush          = dvdsub_flush,
    .close          = dvdsub_close,
    .priv_class     = &dvdsub_class,
}
Definition at line 784 of file dvdsubdec.c.