FFmpeg: libavcodec/dxv.c File Reference
dxv.c File Reference
#include <stdint.h>
#include "libavutil/imgutils.h"
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
#include "lzf.h"
#include "texturedsp.h"
#include "thread.h"
Data Structures
struct DXVContext
Macros
#define CHECKPOINT(x)
Functions
static int decompress_texture_thread (AVCodecContext *avctx, void *arg, int slice, int thread_nb)
static int dxv_decompress_dxt1 (AVCodecContext *avctx)
static int dxv_decompress_dxt5 (AVCodecContext *avctx)
static int dxv_decompress_lzf (AVCodecContext *avctx)
static int dxv_decompress_raw (AVCodecContext *avctx)
static int dxv_decode (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static int dxv_init (AVCodecContext *avctx)
static int dxv_close (AVCodecContext *avctx)
Variables
AVCodec ff_dxv_decoder
Macro Definition Documentation
CHECKPOINT
#define CHECKPOINT (x)
Value:
do {                                                                      \
        if (state == 0) {                                                     \
            value = bytestream2_get_le32(gbc);                                \
            state = 16;                                                       \
        }                                                                     \
        op = value & 0x3;                                                     \
        value >>= 2;                                                          \
        state--;                                                              \
        switch (op) {                                                         \
        case 1:                                                               \
            idx = x;                                                          \
            break;                                                            \
        case 2:                                                               \
            idx = (bytestream2_get_byte(gbc) + 2) * x;                        \
            if (idx > pos) {                                                  \
                av_log(avctx, AV_LOG_ERROR, "idx %d > %d\n", idx, pos);       \
                return AVERROR_INVALIDDATA;                                   \
            }                                                                 \
            break;                                                            \
        case 3:                                                               \
            idx = (bytestream2_get_le16(gbc) + 0x102) * x;                    \
            if (idx > pos) {                                                  \
                av_log(avctx, AV_LOG_ERROR, "idx %d > %d\n", idx, pos);       \
                return AVERROR_INVALIDDATA;                                   \
            }                                                                 \
            break;                                                            \
        }                                                                     \
    } while(0)
Definition at line 93 of file dxv.c.
Referenced by dxv_decompress_dxt1(), and dxv_decompress_dxt5().
Function Documentation
decompress_texture_thread()
static int decompress_texture_thread (AVCodecContext * avctx, void * arg, int slice, int thread_nb) static
Definition at line 49 of file dxv.c.
Referenced by dxv_decode().
dxv_decompress_dxt1()
static int dxv_decompress_dxt1 (AVCodecContext * avctx) static
Definition at line 123 of file dxv.c.
Referenced by dxv_decode().
dxv_decompress_dxt5()
static int dxv_decompress_dxt5 (AVCodecContext * avctx) static
Definition at line 172 of file dxv.c.
Referenced by dxv_decode().
dxv_decompress_lzf()
static int dxv_decompress_lzf (AVCodecContext * avctx) static
Definition at line 323 of file dxv.c.
Referenced by dxv_decode().
dxv_decompress_raw()
static int dxv_decompress_raw (AVCodecContext * avctx) static
Definition at line 329 of file dxv.c.
Referenced by dxv_decode().
dxv_decode()
static int dxv_decode (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 338 of file dxv.c.
dxv_init()
static int dxv_init (AVCodecContext * avctx) static
Definition at line 460 of file dxv.c.
dxv_close()
static int dxv_close (AVCodecContext * avctx) static
Definition at line 484 of file dxv.c.
Variable Documentation
ff_dxv_decoder
AVCodec ff_dxv_decoder
Initial value:
= {
    .name           = "dxv",
    .long_name      = NULL_IF_CONFIG_SMALL("Resolume DXV"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_DXV,
    .init           = dxv_init,
    .decode         = dxv_decode,
    .close          = dxv_close,
    .priv_data_size = sizeof(DXVContext),
    .capabilities   = AV_CODEC_CAP_DR1 |
                      AV_CODEC_CAP_SLICE_THREADS |
                      AV_CODEC_CAP_FRAME_THREADS,
    .caps_internal  = FF_CODEC_CAP_INIT_THREADSAFE |
                      FF_CODEC_CAP_INIT_CLEANUP,
}
Definition at line 493 of file dxv.c.