FFmpeg: libavcodec/dxva2_mpeg2.c File Reference
dxva2_mpeg2.c File Reference
#include "libavutil/log.h"
#include "mpegutils.h"
#include "mpegvideo.h"
#include "dxva2_internal.h"
Data Structures
struct dxva2_picture_context
Macros
#define MAX_SLICES 1024
Functions
static void fill_picture_parameters (AVCodecContext *avctx, AVDXVAContext *ctx, const struct MpegEncContext *s, DXVA_PictureParameters *pp)
static void fill_quantization_matrices (AVCodecContext *avctx, AVDXVAContext *ctx, const struct MpegEncContext *s, DXVA_QmatrixData *qm)
static void fill_slice (AVCodecContext *avctx, const struct MpegEncContext *s, DXVA_SliceInfo *slice, unsigned position, const uint8_t *buffer, unsigned size)
static int commit_bitstream_and_slice_buffer (AVCodecContext *avctx, DECODER_BUFFER_DESC *bs, DECODER_BUFFER_DESC *sc)
static int dxva2_mpeg2_start_frame (AVCodecContext *avctx, av_unused const uint8_t *buffer, av_unused uint32_t size)
static int dxva2_mpeg2_decode_slice (AVCodecContext *avctx, const uint8_t *buffer, uint32_t size)
static int dxva2_mpeg2_end_frame (AVCodecContext *avctx)
Macro Definition Documentation
MAX_SLICES
#define MAX_SLICES 1024
Definition at line 32 of file dxva2_mpeg2.c.
Referenced by dxva2_mpeg2_decode_slice().
Function Documentation
fill_picture_parameters()
static void fill_picture_parameters (AVCodecContext * avctx, AVDXVAContext * ctx, const struct MpegEncContext * s, DXVA_PictureParameters * pp) static
Definition at line 43 of file dxva2_mpeg2.c.
Referenced by dxva2_mpeg2_start_frame().
fill_quantization_matrices()
static void fill_quantization_matrices (AVCodecContext * avctx, AVDXVAContext * ctx, const struct MpegEncContext * s, DXVA_QmatrixData * qm) static
Definition at line 109 of file dxva2_mpeg2.c.
Referenced by dxva2_mpeg2_start_frame().
fill_slice()
static void fill_slice (AVCodecContext * avctx, const struct MpegEncContext * s, DXVA_SliceInfo * slice, unsigned position, const uint8_t * buffer, unsigned size) static
Definition at line 126 of file dxva2_mpeg2.c.
Referenced by dxva2_mpeg2_decode_slice().
commit_bitstream_and_slice_buffer()
static int commit_bitstream_and_slice_buffer (AVCodecContext * avctx, DECODER_BUFFER_DESC * bs, DECODER_BUFFER_DESC * sc) static
Definition at line 153 of file dxva2_mpeg2.c.
Referenced by dxva2_mpeg2_end_frame().
dxva2_mpeg2_start_frame()
static int dxva2_mpeg2_start_frame (AVCodecContext * avctx, av_unused const uint8_t * buffer, av_unused uint32_t size) static
Definition at line 256 of file dxva2_mpeg2.c.
Referenced by dxva2_mpeg2_end_frame().
dxva2_mpeg2_decode_slice()
static int dxva2_mpeg2_decode_slice (AVCodecContext * avctx, const uint8_t * buffer, uint32_t size) static
Definition at line 280 of file dxva2_mpeg2.c.
Referenced by dxva2_mpeg2_end_frame().
dxva2_mpeg2_end_frame()
static int dxva2_mpeg2_end_frame (AVCodecContext * avctx) static
Definition at line 303 of file dxva2_mpeg2.c.