FFmpeg: libavcodec/dxva2_vc1.c File Reference
dxva2_vc1.c File Reference
#include "mpegutils.h"
#include "vc1.h"
#include "vc1data.h"
#include "dxva2_internal.h"
Data Structures
struct dxva2_picture_context
Macros
#define MAX_SLICES 1024
Functions
static void fill_picture_parameters (AVCodecContext *avctx, AVDXVAContext *ctx, const VC1Context *v, DXVA_PictureParameters *pp)
static void fill_slice (AVCodecContext *avctx, DXVA_SliceInfo *slice, unsigned position, unsigned size)
static int commit_bitstream_and_slice_buffer (AVCodecContext *avctx, DECODER_BUFFER_DESC *bs, DECODER_BUFFER_DESC *sc)
static int dxva2_vc1_start_frame (AVCodecContext *avctx, av_unused const uint8_t *buffer, av_unused uint32_t size)
static int dxva2_vc1_decode_slice (AVCodecContext *avctx, const uint8_t *buffer, uint32_t size)
static int dxva2_vc1_end_frame (AVCodecContext *avctx)
Macro Definition Documentation
MAX_SLICES
#define MAX_SLICES 1024
Definition at line 32 of file dxva2_vc1.c.
Referenced by dxva2_vc1_decode_slice().
Function Documentation
fill_picture_parameters()
static void fill_picture_parameters (AVCodecContext * avctx, AVDXVAContext * ctx, const VC1Context * v, DXVA_PictureParameters * pp) static
Definition at line 42 of file dxva2_vc1.c.
Referenced by dxva2_vc1_start_frame().
fill_slice()
static void fill_slice (AVCodecContext * avctx, DXVA_SliceInfo * slice, unsigned position, unsigned size) static
Definition at line 165 of file dxva2_vc1.c.
Referenced by dxva2_vc1_decode_slice().
commit_bitstream_and_slice_buffer()
static int commit_bitstream_and_slice_buffer (AVCodecContext * avctx, DECODER_BUFFER_DESC * bs, DECODER_BUFFER_DESC * sc) static
Definition at line 185 of file dxva2_vc1.c.
Referenced by dxva2_vc1_end_frame().
dxva2_vc1_start_frame()
static int dxva2_vc1_start_frame (AVCodecContext * avctx, av_unused const uint8_t * buffer, av_unused uint32_t size) static
Definition at line 312 of file dxva2_vc1.c.
Referenced by dxva2_vc1_end_frame().
dxva2_vc1_decode_slice()
static int dxva2_vc1_decode_slice (AVCodecContext * avctx, const uint8_t * buffer, uint32_t size) static
Definition at line 334 of file dxva2_vc1.c.
Referenced by dxva2_vc1_end_frame().
dxva2_vc1_end_frame()
static int dxva2_vc1_end_frame (AVCodecContext * avctx) static
Definition at line 364 of file dxva2_vc1.c.