FFmpeg: libavcodec/dxva2_internal.h File Reference
dxva2_internal.h File Reference
#include "config.h"
#include <objbase.h>
#include "avcodec.h"
Data Structures
union AVDXVAContext
Macros
#define COBJMACROS
Typedefs
typedef void DECODER_BUFFER_DESC
Functions
void * ff_dxva2_get_surface (const AVFrame *frame)
unsigned ff_dxva2_get_surface_index (const AVCodecContext *avctx, const AVDXVAContext *, const AVFrame *frame)
int ff_dxva2_commit_buffer (AVCodecContext *, AVDXVAContext *, DECODER_BUFFER_DESC *, unsigned type, const void *data, unsigned size, unsigned mb_count)
int ff_dxva2_common_end_frame (AVCodecContext *, AVFrame *, const void *pp, unsigned pp_size, const void *qm, unsigned qm_size, int(*commit_bs_si)(AVCodecContext *, DECODER_BUFFER_DESC *bs, DECODER_BUFFER_DESC *slice))
Macro Definition Documentation
COBJMACROS
#define COBJMACROS
Definition at line 26 of file dxva2_internal.h.
Typedef Documentation
DECODER_BUFFER_DESC
typedef void DECODER_BUFFER_DESC
Definition at line 52 of file dxva2_internal.h.
Function Documentation
ff_dxva2_get_surface()
void* ff_dxva2_get_surface (const AVFrame * frame)
Definition at line 32 of file dxva2.c.
Referenced by ff_dxva2_common_end_frame(), and ff_dxva2_get_surface_index().
ff_dxva2_get_surface_index()
unsigned ff_dxva2_get_surface_index (const AVCodecContext * avctx, const AVDXVAContext * , const AVFrame * frame)
Definition at line 37 of file dxva2.c.
Referenced by fill_picture_parameters(), and fill_slice_long().
ff_dxva2_commit_buffer()
int ff_dxva2_commit_buffer (AVCodecContext * , AVDXVAContext * , DECODER_BUFFER_DESC * , unsigned type, const void * data, unsigned size, unsigned mb_count)
Definition at line 63 of file dxva2.c.
Referenced by commit_bitstream_and_slice_buffer(), and ff_dxva2_common_end_frame().
ff_dxva2_common_end_frame()
int ff_dxva2_common_end_frame (AVCodecContext * , AVFrame * , const void * pp, unsigned pp_size, const void * qm, unsigned qm_size, int(*)(AVCodecContext *, DECODER_BUFFER_DESC *bs, DECODER_BUFFER_DESC *slice) commit_bs_si)
Definition at line 136 of file dxva2.c.
Referenced by dxva2_h264_end_frame(), dxva2_hevc_end_frame(), dxva2_mpeg2_end_frame(), dxva2_vc1_end_frame(), and dxva2_vp9_end_frame().