FFmpeg: libavcodec/dxva2_vp9.c File Reference
dxva2_vp9.c File Reference
#include "libavutil/avassert.h"
#include "libavutil/pixdesc.h"
#include "vp9.h"
#include "dxva2_internal.h"
Data Structures
struct vp9_dxva2_picture_context
Functions
static void fill_picture_entry (DXVA_PicEntry_VPx *pic, unsigned index, unsigned flag)
static int fill_picture_parameters (const AVCodecContext *avctx, AVDXVAContext *ctx, const VP9SharedContext *h, DXVA_PicParams_VP9 *pp)
static void fill_slice_short (DXVA_Slice_VPx_Short *slice, unsigned position, unsigned size)
static int commit_bitstream_and_slice_buffer (AVCodecContext *avctx, DECODER_BUFFER_DESC *bs, DECODER_BUFFER_DESC *sc)
static int dxva2_vp9_start_frame (AVCodecContext *avctx, av_unused const uint8_t *buffer, av_unused uint32_t size)
static int dxva2_vp9_decode_slice (AVCodecContext *avctx, const uint8_t *buffer, uint32_t size)
static int dxva2_vp9_end_frame (AVCodecContext *avctx)
Function Documentation
fill_picture_entry()
static void fill_picture_entry (DXVA_PicEntry_VPx * pic, unsigned index, unsigned flag) static
Definition at line 40 of file dxva2_vp9.c.
Referenced by fill_picture_parameters().
fill_picture_parameters()
static int fill_picture_parameters (const AVCodecContext * avctx, AVDXVAContext * ctx, const VP9SharedContext * h, DXVA_PicParams_VP9 * pp) static
Definition at line 47 of file dxva2_vp9.c.
Referenced by dxva2_vp9_start_frame().
fill_slice_short()
static void fill_slice_short (DXVA_Slice_VPx_Short * slice, unsigned position, unsigned size) static
Definition at line 159 of file dxva2_vp9.c.
Referenced by dxva2_vp9_decode_slice().
commit_bitstream_and_slice_buffer()
static int commit_bitstream_and_slice_buffer (AVCodecContext * avctx, DECODER_BUFFER_DESC * bs, DECODER_BUFFER_DESC * sc) static
Definition at line 168 of file dxva2_vp9.c.
Referenced by dxva2_vp9_end_frame().
dxva2_vp9_start_frame()
static int dxva2_vp9_start_frame (AVCodecContext * avctx, av_unused const uint8_t * buffer, av_unused uint32_t size) static
Definition at line 256 of file dxva2_vp9.c.
Referenced by dxva2_vp9_end_frame().
dxva2_vp9_decode_slice()
static int dxva2_vp9_decode_slice (AVCodecContext * avctx, const uint8_t * buffer, uint32_t size) static
Definition at line 279 of file dxva2_vp9.c.
Referenced by dxva2_vp9_end_frame().
dxva2_vp9_end_frame()
static int dxva2_vp9_end_frame (AVCodecContext * avctx) static
Definition at line 297 of file dxva2_vp9.c.