FFmpeg: libavcodec/dxva2_hevc.c File Reference
dxva2_hevc.c File Reference
#include "libavutil/avassert.h"
#include "hevc.h"
#include "dxva2_internal.h"
Data Structures
struct hevc_dxva2_picture_context
Macros
#define MAX_SLICES 256
#define DO_REF_LIST(ref_idx, ref_list)
Functions
static void fill_picture_entry (DXVA_PicEntry_HEVC *pic, unsigned index, unsigned flag)
static int get_refpic_index (const DXVA_PicParams_HEVC *pp, int surface_index)
static void fill_picture_parameters (const AVCodecContext *avctx, AVDXVAContext *ctx, const HEVCContext *h, DXVA_PicParams_HEVC *pp)
static void fill_scaling_lists (AVDXVAContext *ctx, const HEVCContext *h, DXVA_Qmatrix_HEVC *qm)
static void fill_slice_short (DXVA_Slice_HEVC_Short *slice, unsigned position, unsigned size)
static int commit_bitstream_and_slice_buffer (AVCodecContext *avctx, DECODER_BUFFER_DESC *bs, DECODER_BUFFER_DESC *sc)
static int dxva2_hevc_start_frame (AVCodecContext *avctx, av_unused const uint8_t *buffer, av_unused uint32_t size)
static int dxva2_hevc_decode_slice (AVCodecContext *avctx, const uint8_t *buffer, uint32_t size)
static int dxva2_hevc_end_frame (AVCodecContext *avctx)
Macro Definition Documentation
MAX_SLICES
#define MAX_SLICES 256
Definition at line 32 of file dxva2_hevc.c.
Referenced by copy_fields(), dxva2_h264_decode_slice(), dxva2_hevc_decode_slice(), ff_h264_decode_slice_header(), fill_filter_caches_inter(), and read_header().
DO_REF_LIST
#define DO_REF_LIST (ref_idx, ref_list)
Value:
{ \
        const RefPicList *rpl = &h->rps[ref_idx]; \
        for (i = 0, j = 0; i < FF_ARRAY_ELEMS(pp->ref_list); i++) { \
            const HEVCFrame *frame = NULL; \
            while (!frame && j < rpl->nb_refs) \
                frame = rpl->ref[j++]; \
            if (frame) \
                pp->ref_list[i] = get_refpic_index(pp, ff_dxva2_get_surface_index(avctx, ctx, frame->frame)); \
            else \
                pp->ref_list[i] = 0xff; \
        } \
    }
Referenced by fill_picture_parameters().
Function Documentation
fill_picture_entry()
static void fill_picture_entry (DXVA_PicEntry_HEVC * pic, unsigned index, unsigned flag) static
Definition at line 43 of file dxva2_hevc.c.
Referenced by fill_picture_parameters().
get_refpic_index()
static int get_refpic_index (const DXVA_PicParams_HEVC * pp, int surface_index) static
Definition at line 50 of file dxva2_hevc.c.
fill_picture_parameters()
static void fill_picture_parameters (const AVCodecContext * avctx, AVDXVAContext * ctx, const HEVCContext * h, DXVA_PicParams_HEVC * pp) static
Definition at line 60 of file dxva2_hevc.c.
Referenced by dxva2_hevc_start_frame().
fill_scaling_lists()
static void fill_scaling_lists (AVDXVAContext * ctx, const HEVCContext * h, DXVA_Qmatrix_HEVC * qm) static
Definition at line 203 of file dxva2_hevc.c.
Referenced by dxva2_hevc_start_frame().
fill_slice_short()
static void fill_slice_short (DXVA_Slice_HEVC_Short * slice, unsigned position, unsigned size) static
Definition at line 231 of file dxva2_hevc.c.
Referenced by dxva2_hevc_decode_slice().
commit_bitstream_and_slice_buffer()
static int commit_bitstream_and_slice_buffer (AVCodecContext * avctx, DECODER_BUFFER_DESC * bs, DECODER_BUFFER_DESC * sc) static
Definition at line 240 of file dxva2_hevc.c.
Referenced by dxva2_hevc_end_frame().
dxva2_hevc_start_frame()
static int dxva2_hevc_start_frame (AVCodecContext * avctx, av_unused const uint8_t * buffer, av_unused uint32_t size) static
Definition at line 359 of file dxva2_hevc.c.
Referenced by dxva2_hevc_end_frame().
dxva2_hevc_decode_slice()
static int dxva2_hevc_decode_slice (AVCodecContext * avctx, const uint8_t * buffer, uint32_t size) static
Definition at line 385 of file dxva2_hevc.c.
Referenced by dxva2_hevc_end_frame().
dxva2_hevc_end_frame()
static int dxva2_hevc_end_frame (AVCodecContext * avctx) static
Definition at line 408 of file dxva2_hevc.c.