FFmpeg: libavcodec/dxva2_h264.c File Reference
dxva2_h264.c File Reference
#include "libavutil/avassert.h"
#include "h264dec.h"
#include "h264data.h"
#include "h264_ps.h"
#include "mpegutils.h"
#include "dxva2_internal.h"
Data Structures
struct dxva2_picture_context
Functions
static void fill_picture_entry (DXVA_PicEntry_H264 *pic, unsigned index, unsigned flag)
static void fill_picture_parameters (const AVCodecContext *avctx, AVDXVAContext *ctx, const H264Context *h, DXVA_PicParams_H264 *pp)
static void fill_scaling_lists (const AVCodecContext *avctx, AVDXVAContext *ctx, const H264Context *h, DXVA_Qmatrix_H264 *qm)
static int is_slice_short (const AVCodecContext *avctx, AVDXVAContext *ctx)
static void fill_slice_short (DXVA_Slice_H264_Short *slice, unsigned position, unsigned size)
static int get_refpic_index (const DXVA_PicParams_H264 *pp, int surface_index)
static void fill_slice_long (AVCodecContext *avctx, DXVA_Slice_H264_Long *slice, const DXVA_PicParams_H264 *pp, unsigned position, unsigned size)
static int commit_bitstream_and_slice_buffer (AVCodecContext *avctx, DECODER_BUFFER_DESC *bs, DECODER_BUFFER_DESC *sc)
static int dxva2_h264_start_frame (AVCodecContext *avctx, av_unused const uint8_t *buffer, av_unused uint32_t size)
static int dxva2_h264_decode_slice (AVCodecContext *avctx, const uint8_t *buffer, uint32_t size)
static int dxva2_h264_end_frame (AVCodecContext *avctx)
Function Documentation
fill_picture_entry()
static void fill_picture_entry (DXVA_PicEntry_H264 * pic, unsigned index, unsigned flag) static
Definition at line 45 of file dxva2_h264.c.
Referenced by fill_picture_parameters(), and fill_slice_long().
fill_picture_parameters()
static void fill_picture_parameters (const AVCodecContext * avctx, AVDXVAContext * ctx, const H264Context * h, DXVA_PicParams_H264 * pp) static
Definition at line 52 of file dxva2_h264.c.
Referenced by dxva2_h264_start_frame().
fill_scaling_lists()
static void fill_scaling_lists (const AVCodecContext * avctx, AVDXVAContext * ctx, const H264Context * h, DXVA_Qmatrix_H264 * qm) static
Definition at line 168 of file dxva2_h264.c.
Referenced by dxva2_h264_start_frame().
is_slice_short()
static int is_slice_short (const AVCodecContext * avctx, AVDXVAContext * ctx) static
Definition at line 194 of file dxva2_h264.c.
Referenced by commit_bitstream_and_slice_buffer(), and dxva2_h264_decode_slice().
fill_slice_short()
static void fill_slice_short (DXVA_Slice_H264_Short * slice, unsigned position, unsigned size) static
Definition at line 201 of file dxva2_h264.c.
Referenced by dxva2_h264_decode_slice().
get_refpic_index()
static int get_refpic_index (const DXVA_PicParams_H264 * pp, int surface_index) static
Definition at line 210 of file dxva2_h264.c.
Referenced by fill_slice_long().
fill_slice_long()
static void fill_slice_long (AVCodecContext * avctx, DXVA_Slice_H264_Long * slice, const DXVA_PicParams_H264 * pp, unsigned position, unsigned size) static
Definition at line 220 of file dxva2_h264.c.
Referenced by dxva2_h264_decode_slice().
commit_bitstream_and_slice_buffer()
static int commit_bitstream_and_slice_buffer (AVCodecContext * avctx, DECODER_BUFFER_DESC * bs, DECODER_BUFFER_DESC * sc) static
Definition at line 301 of file dxva2_h264.c.
Referenced by dxva2_h264_end_frame().
dxva2_h264_start_frame()
static int dxva2_h264_start_frame (AVCodecContext * avctx, av_unused const uint8_t * buffer, av_unused uint32_t size) static
Definition at line 445 of file dxva2_h264.c.
Referenced by dxva2_h264_end_frame().
dxva2_h264_decode_slice()
static int dxva2_h264_decode_slice (AVCodecContext * avctx, const uint8_t * buffer, uint32_t size) static
Definition at line 471 of file dxva2_h264.c.
Referenced by dxva2_h264_end_frame().
dxva2_h264_end_frame()
static int dxva2_h264_end_frame (AVCodecContext * avctx) static
Definition at line 503 of file dxva2_h264.c.