FFmpeg: compat/cuda/dynlink_loader.h File Reference
dynlink_loader.h File Reference
#include "compat/cuda/dynlink_cuda.h"
#include "compat/cuda/dynlink_nvcuvid.h"
#include "compat/nvenc/nvEncodeAPI.h"
#include "compat/w32dlfcn.h"
#include "libavutil/log.h"
#include "libavutil/error.h"
Data Structures
struct CudaFunctions
struct CuvidFunctions
struct NvencFunctions
Macros
#define LIB_HANDLE void*
#define CUDA_LIBNAME "libcuda.so.1"
#define NVCUVID_LIBNAME "libnvcuvid.so.1"
#define NVENC_LIBNAME "libnvidia-encode.so.1"
#define LOAD_LIBRARY(l, path)
#define LOAD_SYMBOL(fun, symbol)
#define GENERIC_LOAD_FUNC_PREAMBLE(T, n, N)
#define GENERIC_LOAD_FUNC_FINALE(n)
#define GENERIC_FREE_FUNC()
Functions
static void cuda_free_functions (CudaFunctions **functions)
static void cuvid_free_functions (CuvidFunctions **functions)
static void nvenc_free_functions (NvencFunctions **functions)
static int cuda_load_functions (CudaFunctions **functions)
static int cuvid_load_functions (CuvidFunctions **functions)
static int nvenc_load_functions (NvencFunctions **functions)
Macro Definition Documentation
LIB_HANDLE
#define LIB_HANDLE void*
Definition at line 42 of file dynlink_loader.h.
CUDA_LIBNAME
#define CUDA_LIBNAME "libcuda.so.1"
Definition at line 54 of file dynlink_loader.h.
Referenced by cuda_load_functions().
NVCUVID_LIBNAME
#define NVCUVID_LIBNAME "libnvcuvid.so.1"
Definition at line 55 of file dynlink_loader.h.
Referenced by cuvid_load_functions().
NVENC_LIBNAME
#define NVENC_LIBNAME "libnvidia-encode.so.1"
Definition at line 56 of file dynlink_loader.h.
Referenced by nvenc_load_functions().
LOAD_LIBRARY
#define LOAD_LIBRARY (l, path)
Value:
do {                                                          \
        if (!((l) = dlopen(path, RTLD_LAZY))) {                   \
            av_log(NULL, AV_LOG_ERROR, "Cannot load %s\n", path); \
            ret = AVERROR_UNKNOWN;                                \
            goto error;                                           \
        }                                                         \
        av_log(NULL, AV_LOG_TRACE, "Loaded lib: %s\n", path);     \
    } while (0)
Definition at line 59 of file dynlink_loader.h.
LOAD_SYMBOL
#define LOAD_SYMBOL (fun, symbol)
Value:
do {                                                            \
        if (!((f->fun) = dlsym(f->lib, symbol))) {                  \
            av_log(NULL, AV_LOG_ERROR, "Cannot load %s\n", symbol); \
            ret = AVERROR_UNKNOWN;                                  \
            goto error;                                             \
        }                                                           \
        av_log(NULL, AV_LOG_TRACE, "Loaded sym: %s\n", symbol);     \
    } while (0)
Definition at line 69 of file dynlink_loader.h.
Referenced by cuda_load_functions(), cuvid_load_functions(), and nvenc_load_functions().
GENERIC_LOAD_FUNC_PREAMBLE
#define GENERIC_LOAD_FUNC_PREAMBLE (T, n, N)
Value:
T *f;                                    \
    int ret;                                 \
                                             \
    n##_free_functions(functions);           \
                                             \
    f = *functions = av_mallocz(sizeof(*f)); \
    if (!f)                                  \
        return AVERROR(ENOMEM);              \
                                             \
    LOAD_LIBRARY(f->lib, N);
Definition at line 79 of file dynlink_loader.h.
Referenced by cuda_load_functions(), cuvid_load_functions(), and nvenc_load_functions().
GENERIC_LOAD_FUNC_FINALE
#define GENERIC_LOAD_FUNC_FINALE (n)
Value:
return 0;                       \
error:                              \
    n##_free_functions(functions);  \
    return ret;
Definition at line 91 of file dynlink_loader.h.
Referenced by cuda_load_functions(), cuvid_load_functions(), and nvenc_load_functions().
GENERIC_FREE_FUNC
#define GENERIC_FREE_FUNC ()
Value:
if (!functions)                      \
        return;                          \
    if (*functions && (*functions)->lib) \
        dlclose((*functions)->lib);      \
    av_freep(functions);
Definition at line 97 of file dynlink_loader.h.
Referenced by cuda_free_functions(), cuvid_free_functions(), and nvenc_free_functions().
Function Documentation
cuda_free_functions()
static void cuda_free_functions (CudaFunctions ** functions) inline static
Definition at line 160 of file dynlink_loader.h.
Referenced by cuda_device_uninit(), and ff_nvenc_encode_close().
cuvid_free_functions()
static void cuvid_free_functions (CuvidFunctions ** functions) inline static
Definition at line 166 of file dynlink_loader.h.
Referenced by cuvid_decode_end().
nvenc_free_functions()
static void nvenc_free_functions (NvencFunctions ** functions) inline static
Definition at line 171 of file dynlink_loader.h.
Referenced by ff_nvenc_encode_close().
cuda_load_functions()
static int cuda_load_functions (CudaFunctions ** functions) inline static
Definition at line 177 of file dynlink_loader.h.
Referenced by cuda_device_init(), and nvenc_load_libraries().
cuvid_load_functions()
static int cuvid_load_functions (CuvidFunctions ** functions) inline static
Definition at line 200 of file dynlink_loader.h.
Referenced by cuvid_decode_init().
nvenc_load_functions()
static int nvenc_load_functions (NvencFunctions ** functions) inline static
Definition at line 233 of file dynlink_loader.h.
Referenced by nvenc_load_libraries().