FFmpeg: libavcodec/eac3enc.h File Reference
eac3enc.h File Reference
E-AC-3 encoder.
#include "ac3enc.h"
Functions
void ff_eac3_exponent_init (void)
Initialize E-AC-3 exponent tables.
void ff_eac3_get_frame_exp_strategy (AC3EncodeContext *s)
Determine frame exponent strategy use and indices.
void ff_eac3_set_cpl_states (AC3EncodeContext *s)
Set coupling states.
void ff_eac3_output_frame_header (AC3EncodeContext *s)
Write the E-AC-3 frame header to the output bitstream.
Detailed Description
E-AC-3 encoder.
Definition in file eac3enc.h.
Function Documentation
ff_eac3_exponent_init()
void ff_eac3_exponent_init (void)
Initialize E-AC-3 exponent tables.
Definition at line 52 of file eac3enc.c.
Referenced by exponent_init().
ff_eac3_get_frame_exp_strategy()
void ff_eac3_get_frame_exp_strategy (AC3EncodeContext * s)
Determine frame exponent strategy use and indices.
Definition at line 68 of file eac3enc.c.
Referenced by compute_exp_strategy().
ff_eac3_set_cpl_states()
void ff_eac3_set_cpl_states (AC3EncodeContext * s)
Set coupling states.
This determines whether certain flags must be written to the bitstream or whether they will be implicitly already known by the decoder.
Definition at line 95 of file eac3enc.c.
Referenced by apply_channel_coupling().
ff_eac3_output_frame_header()
void ff_eac3_output_frame_header (AC3EncodeContext * s)
Write the E-AC-3 frame header to the output bitstream.
Definition at line 128 of file eac3enc.c.
Referenced by ff_ac3_encode_init().