FFmpeg: libavcodec/eac3dec.c File Reference
eac3dec.c File Reference
#include "avcodec.h"
#include "internal.h"
#include "aac_ac3_parser.h"
#include "ac3.h"
#include "ac3_parser.h"
#include "ac3dec.h"
#include "ac3dec_data.h"
#include "eac3_data.h"
Macros
#define EAC3_SR_CODE_REDUCED 3
#define COEFF_0 10273905LL
lrint(M_SQRT2*cos(2*M_PI/12)*(1<<23))
#define COEFF_1 11863283LL
lrint(M_SQRT2*cos(0*M_PI/12)*(1<<23)) = lrint(M_SQRT2*(1<<23))
#define COEFF_2 3070444LL
lrint(M_SQRT2*cos(5*M_PI/12)*(1<<23))
Enumerations
enum EAC3GaqMode { EAC3_GAQ_NO =0, EAC3_GAQ_12, EAC3_GAQ_14, EAC3_GAQ_124 }
gain adaptive quantization mode
Functions
static void ff_eac3_apply_spectral_extension (AC3DecodeContext *s)
static void idct6 (int pre_mant[6])
Calculate 6-point IDCT of the pre-mantissas.
static void ff_eac3_decode_transform_coeffs_aht_ch (AC3DecodeContext *s, int ch)
static int ff_eac3_parse_header (AC3DecodeContext *s)
Macro Definition Documentation
EAC3_SR_CODE_REDUCED
#define EAC3_SR_CODE_REDUCED 3
Definition at line 64 of file eac3dec.c.
Referenced by ff_eac3_parse_header().
COEFF_0
#define COEFF_0 10273905LL
lrint(M_SQRT2*cos(2*M_PI/12)*(1<<23))
Definition at line 161 of file eac3dec.c.
Referenced by idct6().
COEFF_1
#define COEFF_1 11863283LL
lrint(M_SQRT2*cos(0*M_PI/12)*(1<<23)) = lrint(M_SQRT2*(1<<23))
Definition at line 164 of file eac3dec.c.
Referenced by idct6().
COEFF_2
#define COEFF_2 3070444LL
lrint(M_SQRT2*cos(5*M_PI/12)*(1<<23))
Definition at line 167 of file eac3dec.c.
Referenced by idct6().
Enumeration Type Documentation
EAC3GaqMode
enum EAC3GaqMode
gain adaptive quantization mode
Enumerator
EAC3_GAQ_NO
EAC3_GAQ_12
EAC3_GAQ_14
EAC3_GAQ_124
Definition at line 57 of file eac3dec.c.
Function Documentation
ff_eac3_apply_spectral_extension()
static void ff_eac3_apply_spectral_extension (AC3DecodeContext * s) static
Definition at line 66 of file eac3dec.c.
Referenced by decode_audio_block().
idct6()
static void idct6 (int pre_mant[6]) static
Calculate 6-point IDCT of the pre-mantissas.
All calculations are 24-bit fixed-point.
Definition at line 173 of file eac3dec.c.
Referenced by ff_eac3_decode_transform_coeffs_aht_ch().
ff_eac3_decode_transform_coeffs_aht_ch()
static void ff_eac3_decode_transform_coeffs_aht_ch (AC3DecodeContext * s, int ch) static
Definition at line 203 of file eac3dec.c.
Referenced by decode_transform_coeffs_ch().
ff_eac3_parse_header()
static int ff_eac3_parse_header (AC3DecodeContext * s) static
Definition at line 296 of file eac3dec.c.
Referenced by parse_frame_header().