FFmpeg: libavcodec/eac3enc.c File Reference
eac3enc.c File Reference
E-AC-3 encoder.
#include "libavutil/attributes.h"
#include "ac3enc.h"
#include "eac3enc.h"
#include "eac3_data.h"
#include "ac3enc_opts_template.c"
Macros
#define CONFIG_AC3ENC_FLOAT 1
#define AC3ENC_TYPE AC3ENC_TYPE_EAC3
Functions
av_cold void ff_eac3_exponent_init (void)
Initialize E-AC-3 exponent tables.
void ff_eac3_get_frame_exp_strategy (AC3EncodeContext *s)
Determine frame exponent strategy use and indices.
void ff_eac3_set_cpl_states (AC3EncodeContext *s)
Set coupling states.
void ff_eac3_output_frame_header (AC3EncodeContext *s)
Write the E-AC-3 frame header to the output bitstream.
Variables
static const AVClass eac3enc_class
static int8_t eac3_frame_expstr_index_tab [3][4][4][4][4][4]
LUT for finding a matching frame exponent strategy index from a set of exponent strategies for a single channel across all 6 blocks.
AVCodec ff_eac3_encoder
Detailed Description
E-AC-3 encoder.
Definition in file eac3enc.c.
Macro Definition Documentation
CONFIG_AC3ENC_FLOAT
#define CONFIG_AC3ENC_FLOAT 1
Definition at line 27 of file eac3enc.c.
AC3ENC_TYPE
#define AC3ENC_TYPE AC3ENC_TYPE_EAC3
Definition at line 35 of file eac3enc.c.
Function Documentation
ff_eac3_exponent_init()
av_cold void ff_eac3_exponent_init (void)
Initialize E-AC-3 exponent tables.
Definition at line 52 of file eac3enc.c.
Referenced by exponent_init().
ff_eac3_get_frame_exp_strategy()
void ff_eac3_get_frame_exp_strategy (AC3EncodeContext * s)
Determine frame exponent strategy use and indices.
Definition at line 68 of file eac3enc.c.
Referenced by compute_exp_strategy().
ff_eac3_set_cpl_states()
void ff_eac3_set_cpl_states (AC3EncodeContext * s)
Set coupling states.
This determines whether certain flags must be written to the bitstream or whether they will be implicitly already known by the decoder.
Definition at line 95 of file eac3enc.c.
Referenced by apply_channel_coupling().
ff_eac3_output_frame_header()
void ff_eac3_output_frame_header (AC3EncodeContext * s)
Write the E-AC-3 frame header to the output bitstream.
Definition at line 128 of file eac3enc.c.
Referenced by ff_ac3_encode_init().
Variable Documentation
eac3enc_class
const AVClass eac3enc_class static
Initial value:
= {
    .class_name = "E-AC-3 Encoder",
    .item_name  = av_default_item_name,
    .option     = ac3_options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 38 of file eac3enc.c.
eac3_frame_expstr_index_tab
int8_t eac3_frame_expstr_index_tab[3][4][4][4][4][4] static
LUT for finding a matching frame exponent strategy index from a set of exponent strategies for a single channel across all 6 blocks.
Definition at line 49 of file eac3enc.c.
Referenced by ff_eac3_exponent_init(), and ff_eac3_get_frame_exp_strategy().
ff_eac3_encoder
AVCodec ff_eac3_encoder
Initial value:
= {
    .name            = "eac3",
    .long_name       = NULL_IF_CONFIG_SMALL("ATSC A/52 E-AC-3"),
    .type            = AVMEDIA_TYPE_AUDIO,
    .id              = AV_CODEC_ID_EAC3,
    .priv_data_size  = sizeof(AC3EncodeContext),
    .init            = ff_ac3_float_encode_init,
    .encode2         = ff_ac3_float_encode_frame,
    .close           = ff_ac3_encode_close,
    .sample_fmts     = (const enum AVSampleFormat[]){ AV_SAMPLE_FMT_FLTP,
                                                      AV_SAMPLE_FMT_NONE },
    .priv_class      = &eac3enc_class,
    .channel_layouts = ff_ac3_channel_layouts,
    .defaults        = ac3_defaults,
}
Definition at line 254 of file eac3enc.c.