FFmpeg: libavcodec/eacmv.c File Reference
eacmv.c File Reference
Electronic Arts CMV Video Decoder by Peter Ross (pross.nosp@m.@xvi.nosp@m.d.org)
#include "libavutil/common.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/imgutils.h"
#include "avcodec.h"
#include "internal.h"
Data Structures
struct CmvContext
Macros
#define EA_PREAMBLE_SIZE 8
#define MVIh_TAG MKTAG('M', 'V', 'I', 'h')
Functions
static av_cold int cmv_decode_init (AVCodecContext *avctx)
static void cmv_decode_intra (CmvContext *s, AVFrame *frame, const uint8_t *buf, const uint8_t *buf_end)
static void cmv_motcomp (unsigned char *dst, int dst_stride, const unsigned char *src, int src_stride, int x, int y, int xoffset, int yoffset, int width, int height)
static void cmv_decode_inter (CmvContext *s, AVFrame *frame, const uint8_t *buf, const uint8_t *buf_end)
static int cmv_process_header (CmvContext *s, const uint8_t *buf, const uint8_t *buf_end)
static int cmv_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int cmv_decode_end (AVCodecContext *avctx)
Variables
AVCodec ff_eacmv_decoder
Detailed Description
Electronic Arts CMV Video Decoder by Peter Ross (pross.nosp@m.@xvi.nosp@m.d.org)
Technical details here: http://wiki.multimedia.cx/index.php?title=Electronic_Arts_CMV
Definition in file eacmv.c.
Macro Definition Documentation
EA_PREAMBLE_SIZE
#define EA_PREAMBLE_SIZE 8
Definition at line 171 of file eacmv.c.
Referenced by cmv_decode_frame().
MVIh_TAG
#define MVIh_TAG MKTAG('M', 'V', 'I', 'h')
Definition at line 172 of file eacmv.c.
Referenced by cmv_decode_frame().
Function Documentation
cmv_decode_init()
static av_cold int cmv_decode_init (AVCodecContext * avctx) static
Definition at line 45 of file eacmv.c.
cmv_decode_intra()
static void cmv_decode_intra (CmvContext * s, AVFrame * frame, const uint8_t * buf, const uint8_t * buf_end) static
Definition at line 62 of file eacmv.c.
Referenced by cmv_decode_frame().
cmv_motcomp()
static void cmv_motcomp (unsigned char * dst, int dst_stride, const unsigned char * src, int src_stride, int x, int y, int xoffset, int yoffset, int width, int height) static
Definition at line 75 of file eacmv.c.
Referenced by cmv_decode_inter().
cmv_decode_inter()
static void cmv_decode_inter (CmvContext * s, AVFrame * frame, const uint8_t * buf, const uint8_t * buf_end) static
Definition at line 94 of file eacmv.c.
Referenced by cmv_decode_frame().
cmv_process_header()
static int cmv_process_header (CmvContext * s, const uint8_t * buf, const uint8_t * buf_end) static
Definition at line 133 of file eacmv.c.
Referenced by cmv_decode_frame().
cmv_decode_frame()
static int cmv_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 174 of file eacmv.c.
cmv_decode_end()
static av_cold int cmv_decode_end (AVCodecContext * avctx) static
Definition at line 227 of file eacmv.c.
Variable Documentation
ff_eacmv_decoder
AVCodec ff_eacmv_decoder
Initial value:
= {
    .name           = "eacmv",
    .long_name      = NULL_IF_CONFIG_SMALL("Electronic Arts CMV video"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_CMV,
    .priv_data_size = sizeof(CmvContext),
    .init           = cmv_decode_init,
    .close          = cmv_decode_end,
    .decode         = cmv_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 236 of file eacmv.c.