FFmpeg: libavcodec/eaidct.h File Reference
eaidct.h File Reference
#include <stdint.h>
Functions
void ff_ea_idct_put_c (uint8_t *dest, int linesize, int16_t *block)
Function Documentation
ff_ea_idct_put_c()
void ff_ea_idct_put_c (uint8_t * dest, int linesize, int16_t * block)
Definition at line 80 of file eaidct.c.
Referenced by idct_put(), tgq_idct_put_mb(), and tqi_idct_put().