FFmpeg: libavcodec/eamad.c File Reference
eamad.c File Reference
Electronic Arts Madcow Video Decoder.
#include "avcodec.h"
#include "blockdsp.h"
#include "bytestream.h"
#include "bswapdsp.h"
#include "get_bits.h"
#include "aandcttab.h"
#include "eaidct.h"
#include "idctdsp.h"
#include "internal.h"
#include "mpeg12data.h"
#include "mpeg12vlc.h"
Data Structures
struct MadContext
Macros
#define EA_PREAMBLE_SIZE 8
#define MADk_TAG MKTAG('M', 'A', 'D', 'k') /* MAD I-frame */
#define MADm_TAG MKTAG('M', 'A', 'D', 'm') /* MAD P-frame */
#define MADe_TAG MKTAG('M', 'A', 'D', 'e') /* MAD lqp-frame */
Functions
static av_cold int decode_init (AVCodecContext *avctx)
static void comp (unsigned char *dst, int dst_stride, unsigned char *src, int src_stride, int add)
static void comp_block (MadContext *t, AVFrame *frame, int mb_x, int mb_y, int j, int mv_x, int mv_y, int add)
static void idct_put (MadContext *t, AVFrame *frame, int16_t *block, int mb_x, int mb_y, int j)
static int decode_block_intra (MadContext *s, int16_t *block)
static int decode_motion (GetBitContext *gb)
static int decode_mb (MadContext *s, AVFrame *frame, int inter)
static void calc_quant_matrix (MadContext *s, int qscale)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int decode_end (AVCodecContext *avctx)
Variables
AVCodec ff_eamad_decoder
Detailed Description
Electronic Arts Madcow Video Decoder.
Author
Peter Ross pross.nosp@m.@xvi.nosp@m.d.org
See also
technical details at http://wiki.multimedia.cx/index.php?title=Electronic_Arts_MAD
Definition in file eamad.c.
Macro Definition Documentation
EA_PREAMBLE_SIZE
#define EA_PREAMBLE_SIZE 8
Definition at line 43 of file eamad.c.
MADk_TAG
#define MADk_TAG MKTAG('M', 'A', 'D', 'k') /* MAD I-frame */
Definition at line 44 of file eamad.c.
MADm_TAG
#define MADm_TAG MKTAG('M', 'A', 'D', 'm') /* MAD P-frame */
Definition at line 45 of file eamad.c.
Referenced by decode_frame().
MADe_TAG
#define MADe_TAG MKTAG('M', 'A', 'D', 'e') /* MAD lqp-frame */
Definition at line 46 of file eamad.c.
Referenced by decode_frame().
Function Documentation
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 64 of file eamad.c.
comp()
static void comp (unsigned char * dst, int dst_stride, unsigned char * src, int src_stride, int add) inline static
Definition at line 83 of file eamad.c.
Referenced by av_get_padded_bits_per_pixel(), av_image_fill_max_pixsteps(), av_read_image_line(), av_write_image_line(), bmp_decode_frame(), comp_block(), config_output(), config_props(), decode_component(), dirac_decode_frame_internal(), ff_blend_mask(), ff_blend_rectangle(), ff_get_unscaled_swscale(), ff_jpeg2000_getsgnctxno(), fill_coding_method_array(), filter_frame(), init_noise(), init_tile(), interleave_compare_dts(), jpeg2000_dec_cleanup(), jpeg2000_decode_packets_po_iteration(), ls_decode_line(), ls_encode_line(), ls_encode_run(), main(), noise(), sad_hv_bilinear_filter_16width_msa(), swr_next_pts(), tile_codeblocks(), vp5_parse_vector_adjustment(), vp5_parse_vector_models(), vp6_parse_vector_adjustment(), and vp6_parse_vector_models().
comp_block()
static void comp_block (MadContext * t, AVFrame * frame, int mb_x, int mb_y, int j, int mv_x, int mv_y, int add) inline static
Definition at line 92 of file eamad.c.
Referenced by decode_mb().
idct_put()
static void idct_put (MadContext * t, AVFrame * frame, int16_t * block, int mb_x, int mb_y, int j) inline static
Definition at line 116 of file eamad.c.
Referenced by decode_mb().
decode_block_intra()
static int decode_block_intra (MadContext * s, int16_t * block) inline static
Definition at line 131 of file eamad.c.
Referenced by decode_mb().
decode_motion()
static int decode_motion (GetBitContext * gb) static
Definition at line 197 of file eamad.c.
Referenced by decode_mb().
decode_mb()
static int decode_mb (MadContext * s, AVFrame * frame, int inter) static
Definition at line 208 of file eamad.c.
Referenced by decode_frame().
calc_quant_matrix()
static void calc_quant_matrix (MadContext * s, int qscale) static
Definition at line 238 of file eamad.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 247 of file eamad.c.
decode_end()
static av_cold int decode_end (AVCodecContext * avctx) static
Definition at line 334 of file eamad.c.
Variable Documentation
ff_eamad_decoder
AVCodec ff_eamad_decoder
Initial value:
= {
    .name           = "eamad",
    .long_name      = NULL_IF_CONFIG_SMALL("Electronic Arts Madcow Video"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_MAD,
    .priv_data_size = sizeof(MadContext),
    .init           = decode_init,
    .close          = decode_end,
    .decode         = decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 342 of file eamad.c.