FFmpeg: libavcodec/eatgq.c File Reference
eatgq.c File Reference
Electronic Arts TGQ Video Decoder.
#include "aandcttab.h"
#include "avcodec.h"
#include "bytestream.h"
#include "eaidct.h"
#include "get_bits.h"
#include "idctdsp.h"
#include "internal.h"
Data Structures
struct TgqContext
Macros
#define BITSTREAM_READER_LE
Functions
static av_cold int tgq_decode_init (AVCodecContext *avctx)
static void tgq_decode_block (TgqContext *s, int16_t block[64], GetBitContext *gb)
static void tgq_idct_put_mb (TgqContext *s, int16_t(*block)[64], AVFrame *frame, int mb_x, int mb_y)
static void tgq_dconly (TgqContext *s, unsigned char *dst, int dst_stride, int dc)
static void tgq_idct_put_mb_dconly (TgqContext *s, AVFrame *frame, int mb_x, int mb_y, const int8_t *dc)
static int tgq_decode_mb (TgqContext *s, AVFrame *frame, int mb_y, int mb_x)
static void tgq_calculate_qtable (TgqContext *s, int quant)
static int tgq_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
Variables
AVCodec ff_eatgq_decoder
Detailed Description
Electronic Arts TGQ Video Decoder.
Author
Peter Ross pross.nosp@m.@xvi.nosp@m.d.org
Technical details here: http://wiki.multimedia.cx/index.php?title=Electronic_Arts_TGQ
Definition in file eatgq.c.
Macro Definition Documentation
BITSTREAM_READER_LE
#define BITSTREAM_READER_LE
Definition at line 31 of file eatgq.c.
Function Documentation
tgq_decode_init()
static av_cold int tgq_decode_init (AVCodecContext * avctx) static
Definition at line 49 of file eatgq.c.
tgq_decode_block()
static void tgq_decode_block (TgqContext * s, int16_t block[64], GetBitContext * gb) static
Definition at line 61 of file eatgq.c.
Referenced by tgq_decode_mb().
tgq_idct_put_mb()
static void tgq_idct_put_mb (TgqContext * s, int16_t(*) block[64], AVFrame * frame, int mb_x, int mb_y) static
Definition at line 107 of file eatgq.c.
Referenced by tgq_decode_mb().
tgq_dconly()
static void tgq_dconly (TgqContext * s, unsigned char * dst, int dst_stride, int dc) inline static
Definition at line 125 of file eatgq.c.
Referenced by tgq_idct_put_mb_dconly().
tgq_idct_put_mb_dconly()
static void tgq_idct_put_mb_dconly (TgqContext * s, AVFrame * frame, int mb_x, int mb_y, const int8_t * dc) static
Definition at line 134 of file eatgq.c.
Referenced by tgq_decode_mb().
tgq_decode_mb()
static int tgq_decode_mb (TgqContext * s, AVFrame * frame, int mb_y, int mb_x) static
Definition at line 151 of file eatgq.c.
Referenced by tgq_decode_frame().
tgq_calculate_qtable()
static void tgq_calculate_qtable (TgqContext * s, int quant) static
Definition at line 189 of file eatgq.c.
Referenced by tgq_decode_frame().
tgq_decode_frame()
static int tgq_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 200 of file eatgq.c.
Variable Documentation
ff_eatgq_decoder
AVCodec ff_eatgq_decoder
Initial value:
= {
    .name           = "eatgq",
    .long_name      = NULL_IF_CONFIG_SMALL("Electronic Arts TGQ video"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_TGQ,
    .priv_data_size = sizeof(TgqContext),
    .init           = tgq_decode_init,
    .decode         = tgq_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 247 of file eatgq.c.