FFmpeg: libavcodec/eatqi.c File Reference
eatqi.c File Reference
Electronic Arts TQI Video Decoder.
#include "avcodec.h"
#include "blockdsp.h"
#include "bswapdsp.h"
#include "get_bits.h"
#include "aandcttab.h"
#include "eaidct.h"
#include "idctdsp.h"
#include "internal.h"
#include "mpeg12.h"
Data Structures
struct TqiContext
Functions
static av_cold int tqi_decode_init (AVCodecContext *avctx)
static int tqi_decode_mb (TqiContext *t, int16_t(*block)[64])
static void tqi_idct_put (AVCodecContext *avctx, AVFrame *frame, int16_t(*block)[64])
static void tqi_calculate_qtable (TqiContext *t, int quant)
static int tqi_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int tqi_decode_end (AVCodecContext *avctx)
Variables
AVCodec ff_eatqi_decoder
Detailed Description
Electronic Arts TQI Video Decoder.
Author
Peter Ross pross.nosp@m.@xvi.nosp@m.d.org
See also
http://wiki.multimedia.cx/index.php?title=Electronic_Arts_TQI
Definition in file eatqi.c.
Function Documentation
tqi_decode_init()
static av_cold int tqi_decode_init (AVCodecContext * avctx) static
Definition at line 57 of file eatqi.c.
tqi_decode_mb()
static int tqi_decode_mb (TqiContext * t, int16_t(*) block[64]) static
Definition at line 73 of file eatqi.c.
Referenced by tqi_decode_frame().
tqi_idct_put()
static void tqi_idct_put (AVCodecContext * avctx, AVFrame * frame, int16_t(*) block[64]) inline static
Definition at line 93 of file eatqi.c.
Referenced by tqi_decode_frame().
tqi_calculate_qtable()
static void tqi_calculate_qtable (TqiContext * t, int quant) static
Definition at line 113 of file eatqi.c.
Referenced by tqi_decode_frame().
tqi_decode_frame()
static int tqi_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 123 of file eatqi.c.
tqi_decode_end()
static av_cold int tqi_decode_end (AVCodecContext * avctx) static
Definition at line 172 of file eatqi.c.
Variable Documentation
ff_eatqi_decoder
AVCodec ff_eatqi_decoder
Initial value:
= {
    .name           = "eatqi",
    .long_name      = NULL_IF_CONFIG_SMALL("Electronic Arts TQI Video"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_TQI,
    .priv_data_size = sizeof(TqiContext),
    .init           = tqi_decode_init,
    .close          = tqi_decode_end,
    .decode         = tqi_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 179 of file eatqi.c.