FFmpeg: libavcodec/elsdec.h File Reference
elsdec.h File Reference
Entropy Logarithmic-Scale binary arithmetic coder.
#include <stdint.h>
#include <sys/types.h>
Data Structures
struct ElsDecCtx
struct ElsRungNode
struct ElsUnsignedRung
Macros
#define ELS_EXPGOLOMB_LEN 10
Functions
void ff_els_decoder_init (ElsDecCtx *ctx, const uint8_t *in, size_t data_size)
void ff_els_decoder_uninit (ElsUnsignedRung *rung)
int ff_els_decode_bit (ElsDecCtx *ctx, unsigned char *rung)
unsigned ff_els_decode_unsigned (ElsDecCtx *ctx, ElsUnsignedRung *ur)
Detailed Description
Entropy Logarithmic-Scale binary arithmetic coder.
Definition in file elsdec.h.
Macro Definition Documentation
ELS_EXPGOLOMB_LEN
#define ELS_EXPGOLOMB_LEN 10
Definition at line 34 of file elsdec.h.
Referenced by ff_els_decode_unsigned().
Function Documentation
ff_els_decoder_init()
void ff_els_decoder_init (ElsDecCtx * ctx, const uint8_t * in, size_t data_size)
Definition at line 247 of file elsdec.c.
Referenced by epic_jb_decode_tile().
ff_els_decoder_uninit()
void ff_els_decoder_uninit (ElsUnsignedRung * rung)
Definition at line 272 of file elsdec.c.
Referenced by epic_jb_decode_tile().
ff_els_decode_bit()
int ff_els_decode_bit (ElsDecCtx * ctx, unsigned char * rung)
ff_els_decode_unsigned()
unsigned ff_els_decode_unsigned (ElsDecCtx * ctx, ElsUnsignedRung * ur)
Definition at line 350 of file elsdec.c.
Referenced by epic_decode_component_pred(), epic_decode_pixel_pred(), epic_handle_edges(), and epic_jb_decode_tile().