FFmpeg: tools/enum_options.c File Reference
enum_options.c File Reference
#include <string.h>
#include "libavformat/avformat.h"
#include "libavcodec/avcodec.h"
#include "libavutil/log.h"
#include "libavutil/opt.h"
Functions
static void print_usage (void)
static void print_option (const AVClass *class, const AVOption *o)
static void show_opts (const AVClass *class)
static void show_format_opts (void)
static void show_codec_opts (void)
int main (int argc, char **argv)
Function Documentation
print_usage()
static void print_usage (void) static
Definition at line 32 of file enum_options.c.
Referenced by main().
print_option()
static void print_option (const AVClass * class, const AVOption * o) static
Definition at line 39 of file enum_options.c.
Referenced by show_opts().
show_opts()
static void show_opts (const AVClass * class) static
Definition at line 78 of file enum_options.c.
Referenced by show_codec_opts(), and show_format_opts().
show_format_opts()
static void show_format_opts (void) static
Definition at line 89 of file enum_options.c.
Referenced by main().
show_codec_opts()
static void show_codec_opts (void) static
Definition at line 112 of file enum_options.c.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 128 of file enum_options.c.