FFmpeg: libavcodec/escape124.c File Reference
escape124.c File Reference
#include "avcodec.h"
#include "get_bits.h"
#include "internal.h"
Data Structures
union MacroBlock
union SuperBlock
struct CodeBook
struct Escape124Context
Macros
#define BITSTREAM_READER_LE
Functions
static av_cold int escape124_decode_init (AVCodecContext *avctx)
Initialize the decoder.
static av_cold int escape124_decode_close (AVCodecContext *avctx)
static CodeBook unpack_codebook (GetBitContext *gb, unsigned depth, unsigned size)
static unsigned decode_skip_count (GetBitContext *gb)
static MacroBlock decode_macroblock (Escape124Context *s, GetBitContext *gb, int *codebook_index, int superblock_index)
static void insert_mb_into_sb (SuperBlock *sb, MacroBlock mb, unsigned index)
static void copy_superblock (uint16_t *dest, unsigned dest_stride, uint16_t *src, unsigned src_stride)
static int escape124_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
Variables
static const uint16_t mask_matrix []
AVCodec ff_escape124_decoder
Macro Definition Documentation
BITSTREAM_READER_LE
#define BITSTREAM_READER_LE
Definition at line 22 of file escape124.c.
Function Documentation
escape124_decode_init()
static av_cold int escape124_decode_init (AVCodecContext * avctx) static
Initialize the decoder.
Parameters
avctx decoder context
Returns
0 success, negative on error
Definition at line 56 of file escape124.c.
escape124_decode_close()
static av_cold int escape124_decode_close (AVCodecContext * avctx) static
Definition at line 72 of file escape124.c.
unpack_codebook()
static CodeBook unpack_codebook (GetBitContext * gb, unsigned depth, unsigned size) static
Definition at line 85 of file escape124.c.
Referenced by escape124_decode_frame().
decode_skip_count()
static unsigned decode_skip_count (GetBitContext * gb) static
Definition at line 117 of file escape124.c.
Referenced by escape124_decode_frame().
decode_macroblock()
static MacroBlock decode_macroblock (Escape124Context * s, GetBitContext * gb, int * codebook_index, int superblock_index) static
Definition at line 139 of file escape124.c.
Referenced by escape124_decode_frame().
insert_mb_into_sb()
static void insert_mb_into_sb (SuperBlock * sb, MacroBlock mb, unsigned index) static
Definition at line 171 of file escape124.c.
Referenced by escape124_decode_frame().
copy_superblock()
static void copy_superblock (uint16_t * dest, unsigned dest_stride, uint16_t * src, unsigned src_stride) static
Definition at line 180 of file escape124.c.
Referenced by escape124_decode_frame().
escape124_decode_frame()
static int escape124_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 198 of file escape124.c.
Variable Documentation
mask_matrix
const uint16_t mask_matrix[] static
Initial value:
= {0x1,   0x2,   0x10,   0x20,
                                       0x4,   0x8,   0x40,   0x80,
                                       0x100, 0x200, 0x1000, 0x2000,
                                       0x400, 0x800, 0x4000, 0x8000}
Definition at line 193 of file escape124.c.
Referenced by escape124_decode_frame(), and generate_mask().
ff_escape124_decoder
AVCodec ff_escape124_decoder
Initial value:
= {
    .name           = "escape124",
    .long_name      = NULL_IF_CONFIG_SMALL("Escape 124"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_ESCAPE124,
    .priv_data_size = sizeof(Escape124Context),
    .init           = escape124_decode_init,
    .close          = escape124_decode_close,
    .decode         = escape124_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 370 of file escape124.c.