FFmpeg: libavcodec/exif.h File Reference
exif.h File Reference
EXIF metadata parser.
#include "avcodec.h"
#include "bytestream.h"
#include "tiff.h"
Data Structures
struct exif_tag
Macros
#define EXIF_MAX_IFD_RECURSION 2
#define EXIF_TAG_NAME_LENGTH 32
Functions
int avpriv_exif_decode_ifd (void *logctx, GetByteContext *gbytes, int le, int depth, AVDictionary **metadata)
Recursively decodes all IFD's and adds included TAGS into the metadata dictionary.
Variables
static const struct exif_tag tag_list []
Detailed Description
EXIF metadata parser.
Author
Thilo Borgmann <thilo.borgmann at mail.de>
Definition in file exif.h.
Macro Definition Documentation
EXIF_MAX_IFD_RECURSION
#define EXIF_MAX_IFD_RECURSION 2
Definition at line 35 of file exif.h.
EXIF_TAG_NAME_LENGTH
#define EXIF_TAG_NAME_LENGTH 32
Definition at line 36 of file exif.h.
Function Documentation
avpriv_exif_decode_ifd()
int avpriv_exif_decode_ifd (void * logctx, GetByteContext * gbytes, int le, int depth, AVDictionary ** metadata)
Recursively decodes all IFD's and adds included TAGS into the metadata dictionary.
Definition at line 122 of file exif.c.
Referenced by avi_extract_stream_metadata(), exif_decode_tag(), mjpeg_decode_app(), and webp_decode_frame().
Variable Documentation
tag_list
const struct exif_tag tag_list[] static
Definition at line 43 of file exif.h.
Referenced by exif_get_tag_name().