FFmpeg: libavcodec/exif.c File Reference
exif.c File Reference
EXIF metadata parser.
#include "exif.h"
Functions
static const char * exif_get_tag_name (uint16_t id)
static int exif_add_metadata (void *logctx, int count, int type, const char *name, const char *sep, GetByteContext *gb, int le, AVDictionary **metadata)
static int exif_decode_tag (void *logctx, GetByteContext *gbytes, int le, int depth, AVDictionary **metadata)
int avpriv_exif_decode_ifd (void *logctx, GetByteContext *gbytes, int le, int depth, AVDictionary **metadata)
Recursively decodes all IFD's and adds included TAGS into the metadata dictionary.
Detailed Description
EXIF metadata parser.
Author
Thilo Borgmann <thilo.borgmann at mail.de>
Definition in file exif.c.
Function Documentation
exif_get_tag_name()
static const char* exif_get_tag_name (uint16_t id) static
Definition at line 31 of file exif.c.
Referenced by exif_decode_tag().
exif_add_metadata()
static int exif_add_metadata (void * logctx, int count, int type, const char * name, const char * sep, GetByteContext * gb, int le, AVDictionary ** metadata) static
Definition at line 44 of file exif.c.
Referenced by exif_decode_tag().
exif_decode_tag()
static int exif_decode_tag (void * logctx, GetByteContext * gbytes, int le, int depth, AVDictionary ** metadata) static
Definition at line 73 of file exif.c.
Referenced by avpriv_exif_decode_ifd().
avpriv_exif_decode_ifd()
int avpriv_exif_decode_ifd (void * logctx, GetByteContext * gbytes, int le, int depth, AVDictionary ** metadata)
Recursively decodes all IFD's and adds included TAGS into the metadata dictionary.
Definition at line 122 of file exif.c.
Referenced by avi_extract_stream_metadata(), exif_decode_tag(), mjpeg_decode_app(), and webp_decode_frame().