FFmpeg: libavcodec/exr.c File Reference
exr.c File Reference
OpenEXR decoder.
#include <float.h>
#include <zlib.h>
#include "libavutil/common.h"
#include "libavutil/imgutils.h"
#include "libavutil/intfloat.h"
#include "libavutil/opt.h"
#include "libavutil/color_utils.h"
#include "avcodec.h"
#include "bytestream.h"
#include "get_bits.h"
#include "internal.h"
#include "mathops.h"
#include "thread.h"
Data Structures
struct EXRChannel
struct EXRTileAttribute
struct EXRThreadData
struct EXRContext
struct HufDec
Macros
#define HALF_FLOAT_MIN_BIASED_EXP_AS_SINGLE_FP_EXP 0x38000000
#define HALF_FLOAT_MAX_BIASED_EXP_AS_SINGLE_FP_EXP 0x47800000
#define FLOAT_MAX_BIASED_EXP (0xFF << 23)
#define HALF_FLOAT_MAX_BIASED_EXP (0x1F << 10)
#define USHORT_RANGE (1 << 16)
#define BITMAP_SIZE (1 << 13)
#define HUF_ENCBITS 16
#define HUF_DECBITS 14
#define HUF_ENCSIZE ((1 << HUF_ENCBITS) + 1)
#define HUF_DECSIZE (1 << HUF_DECBITS)
#define HUF_DECMASK (HUF_DECSIZE - 1)
#define SHORT_ZEROCODE_RUN 59
#define LONG_ZEROCODE_RUN 63
#define SHORTEST_LONG_RUN (2 + LONG_ZEROCODE_RUN - SHORT_ZEROCODE_RUN)
#define LONGEST_LONG_RUN (255 + SHORTEST_LONG_RUN)
#define get_char(c, lc, gb)
#define get_code(po, rlc, c, lc, gb, out, oe, outb)
#define NBITS 16
#define A_OFFSET (1 << (NBITS - 1))
#define MOD_MASK ((1 << NBITS) - 1)
#define OFFSET(x) offsetof(EXRContext, x)
#define VD AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_DECODING_PARAM
Enumerations
enum ExrCompr {
EXR_RAW, EXR_RLE, EXR_ZIP1, EXR_ZIP16,
EXR_PIZ, EXR_PXR24, EXR_B44, EXR_B44A,
EXR_UNKN
}
enum ExrPixelType { EXR_UINT, EXR_HALF, EXR_FLOAT, EXR_UNKNOWN }
enum ExrTileLevelMode { EXR_TILE_LEVEL_ONE, EXR_TILE_LEVEL_MIPMAP, EXR_TILE_LEVEL_RIPMAP, EXR_TILE_LEVEL_UNKNOWN }
enum ExrTileLevelRound { EXR_TILE_ROUND_UP, EXR_TILE_ROUND_DOWN, EXR_TILE_ROUND_UNKNOWN }
Functions
static union av_intfloat32 exr_half2float (uint16_t hf)
Convert a half float as a uint16_t into a full float.
static uint16_t exr_flt2uint (uint32_t v)
Convert from 32-bit float as uint32_t to uint16_t.
static uint16_t exr_halflt2uint (uint16_t v)
Convert from 16-bit float as uint16_t to uint16_t.
static void predictor (uint8_t *src, int size)
static void reorder_pixels (uint8_t *src, uint8_t *dst, int size)
static int zip_uncompress (const uint8_t *src, int compressed_size, int uncompressed_size, EXRThreadData *td)
static int rle_uncompress (const uint8_t *src, int compressed_size, int uncompressed_size, EXRThreadData *td)
static uint16_t reverse_lut (const uint8_t *bitmap, uint16_t *lut)
static void apply_lut (const uint16_t *lut, uint16_t *dst, int dsize)
static void huf_canonical_code_table (uint64_t *hcode)
static int huf_unpack_enc_table (GetByteContext *gb, int32_t im, int32_t iM, uint64_t *hcode)
static int huf_build_dec_table (const uint64_t *hcode, int im, int iM, HufDec *hdecod)
static int huf_decode (const uint64_t *hcode, const HufDec *hdecod, GetByteContext *gb, int nbits, int rlc, int no, uint16_t *out)
static int huf_uncompress (GetByteContext *gb, uint16_t *dst, int dst_size)
static void wdec14 (uint16_t l, uint16_t h, uint16_t *a, uint16_t *b)
static void wdec16 (uint16_t l, uint16_t h, uint16_t *a, uint16_t *b)
static void wav_decode (uint16_t *in, int nx, int ox, int ny, int oy, uint16_t mx)
static int piz_uncompress (EXRContext *s, const uint8_t *src, int ssize, int dsize, EXRThreadData *td)
static int pxr24_uncompress (EXRContext *s, const uint8_t *src, int compressed_size, int uncompressed_size, EXRThreadData *td)
static void unpack_14 (const uint8_t b[14], uint16_t s[16])
static void unpack_3 (const uint8_t b[3], uint16_t s[16])
static int b44_uncompress (EXRContext *s, const uint8_t *src, int compressed_size, int uncompressed_size, EXRThreadData *td)
static int decode_block (AVCodecContext *avctx, void *tdata, int jobnr, int threadnr)
static int check_header_variable (EXRContext *s, const char *value_name, const char *value_type, unsigned int minimum_length)
Check if the variable name corresponds to its data type.
static int decode_header (EXRContext *s)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int decode_init (AVCodecContext *avctx)
static av_cold int decode_end (AVCodecContext *avctx)
Variables
static const AVOption options []
static const AVClass exr_class
AVCodec ff_exr_decoder
Detailed Description
OpenEXR decoder.
Author
Jimmy Christensen
For more information on the OpenEXR format, visit: http://openexr.com/
exr_flt2uint() and exr_halflt2uint() is credited to Reimar Döffinger. exr_half2float() is credited to Aaftab Munshi, Dan Ginsburg, Dave Shreiner.
Definition in file exr.c.
Macro Definition Documentation
HALF_FLOAT_MIN_BIASED_EXP_AS_SINGLE_FP_EXP
#define HALF_FLOAT_MIN_BIASED_EXP_AS_SINGLE_FP_EXP 0x38000000
Definition at line 152 of file exr.c.
Referenced by exr_half2float().
HALF_FLOAT_MAX_BIASED_EXP_AS_SINGLE_FP_EXP
#define HALF_FLOAT_MAX_BIASED_EXP_AS_SINGLE_FP_EXP 0x47800000
Definition at line 156 of file exr.c.
FLOAT_MAX_BIASED_EXP
#define FLOAT_MAX_BIASED_EXP (0xFF << 23)
Definition at line 159 of file exr.c.
Referenced by exr_half2float().
HALF_FLOAT_MAX_BIASED_EXP
#define HALF_FLOAT_MAX_BIASED_EXP (0x1F << 10)
Definition at line 161 of file exr.c.
Referenced by exr_half2float().
USHORT_RANGE
#define USHORT_RANGE (1 << 16)
Definition at line 346 of file exr.c.
Referenced by reverse_lut().
BITMAP_SIZE
#define BITMAP_SIZE (1 << 13)
Definition at line 347 of file exr.c.
Referenced by piz_uncompress().
HUF_ENCBITS
#define HUF_ENCBITS 16
Definition at line 372 of file exr.c.
HUF_DECBITS
#define HUF_DECBITS 14
Definition at line 373 of file exr.c.
Referenced by huf_build_dec_table(), and huf_decode().
HUF_ENCSIZE
#define HUF_ENCSIZE ((1 << HUF_ENCBITS) + 1)
Definition at line 375 of file exr.c.
Referenced by huf_canonical_code_table(), and huf_uncompress().
HUF_DECSIZE
#define HUF_DECSIZE (1 << HUF_DECBITS)
Definition at line 376 of file exr.c.
Referenced by huf_uncompress().
HUF_DECMASK
#define HUF_DECMASK (HUF_DECSIZE - 1)
Definition at line 377 of file exr.c.
Referenced by huf_decode().
SHORT_ZEROCODE_RUN
#define SHORT_ZEROCODE_RUN 59
Definition at line 408 of file exr.c.
Referenced by huf_unpack_enc_table().
LONG_ZEROCODE_RUN
#define LONG_ZEROCODE_RUN 63
Definition at line 409 of file exr.c.
Referenced by huf_unpack_enc_table().
SHORTEST_LONG_RUN
#define SHORTEST_LONG_RUN (2 + LONG_ZEROCODE_RUN - SHORT_ZEROCODE_RUN)
Definition at line 410 of file exr.c.
Referenced by huf_unpack_enc_table().
LONGEST_LONG_RUN
#define LONGEST_LONG_RUN (255 + SHORTEST_LONG_RUN)
Definition at line 411 of file exr.c.
get_char
#define get_char (c, lc, gb)
Value:
{                                                                             \
        c   = (c << 8) | bytestream2_get_byte(gb);                            \
        lc += 8;                                                              \
}
Definition at line 490 of file exr.c.
Referenced by huf_decode().
get_code
#define get_code (po, rlc, c, lc, gb, out, oe, outb)
Value:
{                                                                             \
        if (po == rlc) {                                                      \
            if (lc < 8)                                                       \
                get_char(c, lc, gb);                                          \
            lc -= 8;                                                          \
                                                                              \
            cs = c >> lc;                                                     \
                                                                              \
            if (out + cs > oe || out == outb)                                 \
                return AVERROR_INVALIDDATA;                                   \
                                                                              \
            s = out[-1];                                                      \
                                                                              \
            while (cs-- > 0)                                                  \
                *out++ = s;                                                   \
        } else if (out < oe) {                                                \
            *out++ = po;                                                      \
        } else {                                                              \
            return AVERROR_INVALIDDATA;                                       \
        }                                                                     \
}
Definition at line 496 of file exr.c.
Referenced by huf_decode().
NBITS
#define NBITS 16
Definition at line 652 of file exr.c.
A_OFFSET
#define A_OFFSET (1 << (NBITS - 1))
Definition at line 653 of file exr.c.
Referenced by wdec16().
MOD_MASK
#define MOD_MASK ((1 << NBITS) - 1)
Definition at line 654 of file exr.c.
Referenced by wdec16().
OFFSET
#define OFFSET (x) offsetof(EXRContext, x)
Definition at line 1817 of file exr.c.
VD
#define VD AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_DECODING_PARAM
Definition at line 1818 of file exr.c.
Enumeration Type Documentation
ExrCompr
enum ExrCompr
Enumerator
EXR_RAW
EXR_RLE
EXR_ZIP1
EXR_ZIP16
EXR_PIZ
EXR_PXR24
EXR_B44
EXR_B44A
EXR_UNKN
Definition at line 53 of file exr.c.
ExrPixelType
enum ExrPixelType
Enumerator
EXR_UINT
EXR_HALF
EXR_FLOAT
EXR_UNKNOWN
Definition at line 65 of file exr.c.
ExrTileLevelMode
enum ExrTileLevelMode
Enumerator
EXR_TILE_LEVEL_ONE
EXR_TILE_LEVEL_MIPMAP
EXR_TILE_LEVEL_RIPMAP
EXR_TILE_LEVEL_UNKNOWN
Definition at line 72 of file exr.c.
ExrTileLevelRound
enum ExrTileLevelRound
Enumerator
EXR_TILE_ROUND_UP
EXR_TILE_ROUND_DOWN
EXR_TILE_ROUND_UNKNOWN
Definition at line 79 of file exr.c.
Function Documentation
exr_half2float()
static union av_intfloat32 exr_half2float (uint16_t hf) static
Convert a half float as a uint16_t into a full float.
Parameters
hf half float as uint16_t
Returns
float value
Definition at line 170 of file exr.c.
Referenced by decode_init().
exr_flt2uint()
static uint16_t exr_flt2uint (uint32_t v) inline static
Convert from 32-bit float as uint32_t to uint16_t.
Parameters
v 32-bit float
Returns
normalized 16-bit unsigned int
Definition at line 221 of file exr.c.
Referenced by decode_block(), and decode_init().
exr_halflt2uint()
static uint16_t exr_halflt2uint (uint16_t v) inline static
Convert from 16-bit float as uint16_t to uint16_t.
Parameters
v 16-bit float
Returns
normalized 16-bit unsigned int
Definition at line 241 of file exr.c.
Referenced by decode_block(), and decode_init().
predictor()
static void predictor (uint8_t * src, int size) static
Definition at line 254 of file exr.c.
Referenced by adpcm_compress_trellis(), adpcm_decode_frame(), adpcm_encode_frame(), adpcm_ima_expand_nibble(), adpcm_ima_oki_expand_nibble(), adpcm_ima_qt_expand_nibble(), adpcm_ima_wav_expand_nibble(), adpcm_ms_compress_sample(), adpcm_ms_expand_nibble(), decode_audio_s16(), dpcm_decode_frame(), ff_mjpeg_decode_sos(), ljpeg_decode_rgb_scan(), rle_uncompress(), tta_decode_frame(), and zip_uncompress().
reorder_pixels()
static void reorder_pixels (uint8_t * src, uint8_t * dst, int size) static
Definition at line 266 of file exr.c.
Referenced by rle_uncompress(), and zip_uncompress().
zip_uncompress()
static int zip_uncompress (const uint8_t * src, int compressed_size, int uncompressed_size, EXRThreadData * td) static
Definition at line 286 of file exr.c.
Referenced by decode_block().
rle_uncompress()
static int rle_uncompress (const uint8_t * src, int compressed_size, int uncompressed_size, EXRThreadData * td) static
Definition at line 301 of file exr.c.
Referenced by decode_block().
reverse_lut()
static uint16_t reverse_lut (const uint8_t * bitmap, uint16_t * lut) static
Definition at line 349 of file exr.c.
Referenced by piz_uncompress().
apply_lut()
static void apply_lut (const uint16_t * lut, uint16_t * dst, int dsize) static
Definition at line 364 of file exr.c.
Referenced by piz_uncompress().
huf_canonical_code_table()
static void huf_canonical_code_table (uint64_t * hcode) static
Definition at line 385 of file exr.c.
Referenced by huf_unpack_enc_table().
huf_unpack_enc_table()
static int huf_unpack_enc_table (GetByteContext * gb, int32_t im, int32_t iM, uint64_t * hcode) static
Definition at line 413 of file exr.c.
Referenced by huf_uncompress().
huf_build_dec_table()
static int huf_build_dec_table (const uint64_t * hcode, int im, int iM, HufDec * hdecod) static
Definition at line 453 of file exr.c.
Referenced by huf_uncompress().
huf_decode()
static int huf_decode (const uint64_t * hcode, const HufDec * hdecod, GetByteContext * gb, int nbits, int rlc, int no, uint16_t * out) static
Definition at line 519 of file exr.c.
Referenced by huf_uncompress().
huf_uncompress()
static int huf_uncompress (GetByteContext * gb, uint16_t * dst, int dst_size) static
Definition at line 588 of file exr.c.
Referenced by piz_uncompress().
wdec14()
static void wdec14 (uint16_t l, uint16_t h, uint16_t * a, uint16_t * b) inline static
Definition at line 639 of file exr.c.
Referenced by wav_decode().
wdec16()
static void wdec16 (uint16_t l, uint16_t h, uint16_t * a, uint16_t * b) inline static
Definition at line 656 of file exr.c.
Referenced by wav_decode().
wav_decode()
static void wav_decode (uint16_t * in, int nx, int ox, int ny, int oy, uint16_t mx) static
Definition at line 666 of file exr.c.
Referenced by piz_uncompress().
piz_uncompress()
static int piz_uncompress (EXRContext * s, const uint8_t * src, int ssize, int dsize, EXRThreadData * td) static
Definition at line 745 of file exr.c.
Referenced by decode_block().
pxr24_uncompress()
static int pxr24_uncompress (EXRContext * s, const uint8_t * src, int compressed_size, int uncompressed_size, EXRThreadData * td) static
Definition at line 825 of file exr.c.
Referenced by decode_block().
unpack_14()
static void unpack_14 (const uint8_t b[14], uint16_t s[16]) static
Definition at line 909 of file exr.c.
Referenced by b44_uncompress().
unpack_3()
static void unpack_3 (const uint8_t b[3], uint16_t s[16]) static
Definition at line 944 of file exr.c.
Referenced by b44_uncompress().
b44_uncompress()
static int b44_uncompress (EXRContext * s, const uint8_t * src, int compressed_size, int uncompressed_size, EXRThreadData * td) static
Definition at line 960 of file exr.c.
Referenced by decode_block().
decode_block()
static int decode_block (AVCodecContext * avctx, void * tdata, int jobnr, int threadnr) static
Definition at line 1037 of file exr.c.
Referenced by decode_frame().
check_header_variable()
static int check_header_variable (EXRContext * s, const char * value_name, const char * value_type, unsigned int minimum_length) static
Check if the variable name corresponds to its data type.
Parameters
s the EXRContext
value_name name of the variable to check
value_type type of the variable to check
minimum_length minimum length of the variable data
Returns
bytes to read containing variable data -1 if variable is not found 0 if buffer ended prematurely
Definition at line 1275 of file exr.c.
Referenced by decode_header().
decode_header()
static int decode_header (EXRContext * s) static
Definition at line 1304 of file exr.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 1618 of file exr.c.
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 1743 of file exr.c.
decode_end()
static av_cold int decode_end (AVCodecContext * avctx) static
Definition at line 1799 of file exr.c.
Variable Documentation
options
const AVOption options[] static
Definition at line 1819 of file exr.c.
exr_class
const AVClass exr_class static
Initial value:
= {
    .class_name = "EXR",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1864 of file exr.c.
ff_exr_decoder
AVCodec ff_exr_decoder
Initial value:
= {
    .name             = "exr",
    .long_name        = NULL_IF_CONFIG_SMALL("OpenEXR image"),
    .type             = AVMEDIA_TYPE_VIDEO,
    .id               = AV_CODEC_ID_EXR,
    .priv_data_size   = sizeof(EXRContext),
    .init             = decode_init,
    .init_thread_copy = ONLY_IF_THREADS_ENABLED(decode_init_thread_copy),
    .close            = decode_end,
    .decode           = decode_frame,
    .capabilities     = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_FRAME_THREADS |
                        AV_CODEC_CAP_SLICE_THREADS,
    .priv_class       = &exr_class,
}
Definition at line 1871 of file exr.c.