FFmpeg: libavfilter/f_interleave.c File Reference
f_interleave.c File Reference
audio and video interleaver
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/opt.h"
#include "framequeue.h"
#include "avfilter.h"
#include "bufferqueue.h"
#include "formats.h"
#include "internal.h"
#include "audio.h"
#include "video.h"
Data Structures
struct InterleaveContext
Macros
#define FF_INTERNAL_FIELDS 1
#define OFFSET(x) offsetof(InterleaveContext, x)
#define DEFINE_OPTIONS(filt_name, flags_)
Functions
static int push_frame (AVFilterContext *ctx)
static int filter_frame (AVFilterLink *inlink, AVFrame *frame)
static av_cold int init (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
static int config_output (AVFilterLink *outlink)
static int request_frame (AVFilterLink *outlink)
Detailed Description
audio and video interleaver
Definition in file f_interleave.c.
Macro Definition Documentation
FF_INTERNAL_FIELDS
#define FF_INTERNAL_FIELDS 1
Definition at line 30 of file f_interleave.c.
OFFSET
#define OFFSET (x) offsetof(InterleaveContext, x)
Definition at line 46 of file f_interleave.c.
DEFINE_OPTIONS
#define DEFINE_OPTIONS (filt_name, flags_)
Value:
static const AVOption filt_name##_options[] = {                     \
   { "nb_inputs", "set number of inputs", OFFSET(nb_inputs), AV_OPT_TYPE_INT, {.i64 = 2}, 1, INT_MAX, .flags = flags_ }, \
   { "n",         "set number of inputs", OFFSET(nb_inputs), AV_OPT_TYPE_INT, {.i64 = 2}, 1, INT_MAX, .flags = flags_ }, \
   { NULL }                                                         \
}
Definition at line 48 of file f_interleave.c.
Referenced by request_frame().
Function Documentation
push_frame()
static int push_frame (AVFilterContext * ctx) inline static
Definition at line 55 of file f_interleave.c.
Referenced by filter_frame(), and request_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * frame) static
Definition at line 87 of file f_interleave.c.
Referenced by init().
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 109 of file f_interleave.c.
Referenced by request_frame().
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 142 of file f_interleave.c.
Referenced by request_frame().
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 154 of file f_interleave.c.
Referenced by request_frame().
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 190 of file f_interleave.c.