FFmpeg: libavfilter/f_metadata.c File Reference
f_metadata.c File Reference
filter for manipulating frame metadata
#include <float.h>
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/eval.h"
#include "libavutil/internal.h"
#include "libavutil/opt.h"
#include "libavutil/timestamp.h"
#include "libavformat/avio.h"
#include "avfilter.h"
#include "audio.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
Data Structures
struct MetadataContext
Macros
#define OFFSET(x) offsetof(MetadataContext, x)
#define DEFINE_OPTIONS(filt_name, FLAGS)
Enumerations
enum MetadataMode {
METADATA_SELECT, METADATA_ADD, METADATA_MODIFY, METADATA_DELETE,
METADATA_PRINT, METADATA_NB
}
enum MetadataFunction {
METADATAF_SAME_STR, METADATAF_STARTS_WITH, METADATAF_LESS, METADATAF_EQUAL,
METADATAF_GREATER, METADATAF_EXPR, METADATAF_NB
}
enum var_name {
VAR_CH, VAR_N, VAR_NB_IN_CHANNELS, VAR_NB_OUT_CHANNELS,
VAR_T, VAR_S, VAR_VARS_NB, VAR_VALUE1,
VAR_VALUE2, VAR_VARS_NB, VAR_TB, VAR_PTS,
VAR_START_PTS, VAR_PREV_PTS, VAR_PREV_SELECTED_PTS, VAR_T,
VAR_START_T, VAR_PREV_T, VAR_PREV_SELECTED_T, VAR_PICT_TYPE,
VAR_I, VAR_P, VAR_B, VAR_S,
VAR_SI, VAR_SP, VAR_BI, VAR_PICT_TYPE_I,
VAR_PICT_TYPE_P, VAR_PICT_TYPE_B, VAR_PICT_TYPE_S, VAR_PICT_TYPE_SI,
VAR_PICT_TYPE_SP, VAR_PICT_TYPE_BI, VAR_INTERLACE_TYPE, VAR_INTERLACE_TYPE_P,
VAR_INTERLACE_TYPE_T, VAR_INTERLACE_TYPE_B, VAR_CONSUMED_SAMPLES_N, VAR_SAMPLES_N,
VAR_SAMPLE_RATE, VAR_N, VAR_SELECTED_N, VAR_PREV_SELECTED_N,
VAR_KEY, VAR_POS, VAR_SCENE, VAR_CONCATDEC_SELECT,
VAR_VARS_NB, VAR_FRAME_RATE, VAR_INTERLACED, VAR_N,
VAR_NB_CONSUMED_SAMPLES, VAR_NB_SAMPLES, VAR_POS, VAR_PREV_INPTS,
VAR_PREV_INT, VAR_PREV_OUTPTS, VAR_PREV_OUTT, VAR_PTS,
VAR_SAMPLE_RATE, VAR_STARTPTS, VAR_STARTT, VAR_T,
VAR_TB, VAR_RTCTIME, VAR_RTCSTART, VAR_S,
VAR_SR, VAR_VARS_NB, VAR_AVTB, VAR_INTB,
VAR_SR, VAR_VARS_NB, VAR_W, VAR_H,
VAR_A, VAR_DAR, VAR_SAR, VAR_HSUB,
VAR_VSUB, VARS_NB, VAR_W, VAR_H,
VAR_CW, VAR_CH, VAR_HSUB, VAR_VSUB,
VARS_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_A, VAR_SAR, VAR_DAR,
VAR_HSUB, VAR_VSUB, VAR_X, VAR_Y,
VAR_N, VAR_POS, VAR_T, VAR_VARS_NB,
VAR_DAR, VAR_HSUB, VAR_VSUB, VAR_IN_H,
VAR_IH, VAR_IN_W, VAR_IW, VAR_SAR,
VAR_X, VAR_Y, VAR_H, VAR_W,
VAR_T, VAR_MAX, VARS_NB, VAR_DAR,
VAR_HSUB, VAR_VSUB, VAR_LINE_H, VAR_LH,
VAR_MAIN_H, VAR_h, VAR_H, VAR_MAIN_W,
VAR_w, VAR_W, VAR_MAX_GLYPH_A, VAR_ASCENT,
VAR_MAX_GLYPH_D, VAR_DESCENT, VAR_MAX_GLYPH_H, VAR_MAX_GLYPH_W,
VAR_N, VAR_SAR, VAR_T, VAR_TEXT_H,
VAR_TH, VAR_TEXT_W, VAR_TW, VAR_X,
VAR_Y, VAR_PICT_TYPE, VAR_VARS_NB, VAR_N,
VAR_POS, VAR_R, VAR_T, VAR_NB,
VAR_N, VAR_PTS, VAR_R, VAR_T,
VAR_TB, VAR_NB, VAR_W, VAR_H,
VAR_VAL, VAR_MAXVAL, VAR_MINVAL, VAR_NEGVAL,
VAR_CLIPVAL, VAR_VARS_NB, VAR_W, VAR_H,
VAR_X, VAR_Y, VAR_BITDEPTHX, VAR_BITDEPTHY,
VAR_VARS_NB, VAR_MAIN_W, VAR_MW, VAR_MAIN_H,
VAR_MH, VAR_OVERLAY_W, VAR_OW, VAR_OVERLAY_H,
VAR_OH, VAR_HSUB, VAR_VSUB, VAR_X,
VAR_Y, VAR_N, VAR_POS, VAR_T,
VAR_VARS_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_X, VAR_Y, VAR_A,
VAR_SAR, VAR_DAR, VAR_HSUB, VAR_VSUB,
VARS_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_HSUB, VAR_VSUB, VAR_N,
VAR_T, VAR_VARS_NB, VAR_IN_W, VAR_IW,
VAR_IN_H, VAR_IH, VAR_OUT_W, VAR_OW,
VAR_OUT_H, VAR_OH, VAR_A, VAR_SAR,
VAR_DAR, VAR_HSUB, VAR_VSUB, VAR_OHSUB,
VAR_OVSUB, VARS_NB, VAR_PI, VAR_PHI,
VAR_E, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_A, VAR_DAR, VAR_SAR,
VARS_NB, VAR_W, VAR_H, VAR_N,
VAR_PTS, VAR_R, VAR_T, VAR_TB,
VAR_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_IN, VAR_ON, VAR_DURATION,
VAR_PDURATION, VAR_TIME, VAR_FRAME, VAR_ZOOM,
VAR_PZOOM, VAR_X, VAR_PX, VAR_Y,
VAR_PY, VAR_A, VAR_SAR, VAR_DAR,
VAR_HSUB, VAR_VSUB, VARS_NB, VAR_IN_W,
VAR_IW, VAR_IN_H, VAR_IH, VAR_OUT_W,
VAR_OW, VAR_OUT_H, VAR_OH, VAR_A,
VAR_SAR, VAR_DAR, VAR_HSUB, VAR_VSUB,
VAR_OHSUB, VAR_OVSUB, VARS_NB, VAR_X,
VAR_Y, VAR_W, VAR_H, VAR_TIME,
VAR_SPEED, VAR_TEMPO, VAR_ORDER, VAR_PATTERN,
VAR_ROW, VAR_VARS_NB
}
Functions
static int same_str (MetadataContext *s, const char *value1, const char *value2)
static int starts_with (MetadataContext *s, const char *value1, const char *value2)
static int equal (MetadataContext *s, const char *value1, const char *value2)
static int less (MetadataContext *s, const char *value1, const char *value2)
static int greater (MetadataContext *s, const char *value1, const char *value2)
static int parse_expr (MetadataContext *s, const char *value1, const char *value2)
static void print_log (AVFilterContext *ctx, const char *msg,...)
static void print_file (AVFilterContext *ctx, const char *msg,...)
static av_cold int init (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
static int filter_frame (AVFilterLink *inlink, AVFrame *frame)
Variables
static const char *const var_names []
Detailed Description
filter for manipulating frame metadata
Definition in file f_metadata.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(MetadataContext, x)
Definition at line 92 of file f_metadata.c.
DEFINE_OPTIONS
#define DEFINE_OPTIONS (filt_name, FLAGS)
Value:
static const AVOption filt_name##_options[] = { \
    { "mode", "set a mode of operation", OFFSET(mode),   AV_OPT_TYPE_INT,    {.i64 = 0 }, 0, METADATA_NB-1, FLAGS, "mode" }, \
    {   "select", "select frame",        0,              AV_OPT_TYPE_CONST,  {.i64 = METADATA_SELECT }, 0, 0, FLAGS, "mode" }, \
    {   "add",    "add new metadata",    0,              AV_OPT_TYPE_CONST,  {.i64 = METADATA_ADD },    0, 0, FLAGS, "mode" }, \
    {   "modify", "modify metadata",     0,              AV_OPT_TYPE_CONST,  {.i64 = METADATA_MODIFY }, 0, 0, FLAGS, "mode" }, \
    {   "delete", "delete metadata",     0,              AV_OPT_TYPE_CONST,  {.i64 = METADATA_DELETE }, 0, 0, FLAGS, "mode" }, \
    {   "print",  "print metadata",      0,              AV_OPT_TYPE_CONST,  {.i64 = METADATA_PRINT },  0, 0, FLAGS, "mode" }, \
    { "key",   "set metadata key",       OFFSET(key),    AV_OPT_TYPE_STRING, {.str = NULL }, 0, 0, FLAGS }, \
    { "value", "set metadata value",     OFFSET(value),  AV_OPT_TYPE_STRING, {.str = NULL }, 0, 0, FLAGS }, \
    { "function", "function for comparing values", OFFSET(function), AV_OPT_TYPE_INT, {.i64 = 0 }, 0, METADATAF_NB-1, FLAGS, "function" }, \
    {   "same_str",    NULL, 0, AV_OPT_TYPE_CONST, {.i64 = METADATAF_SAME_STR },    0, 3, FLAGS, "function" }, \
    {   "starts_with", NULL, 0, AV_OPT_TYPE_CONST, {.i64 = METADATAF_STARTS_WITH }, 0, 0, FLAGS, "function" }, \
    {   "less",        NULL, 0, AV_OPT_TYPE_CONST, {.i64 = METADATAF_LESS    },     0, 3, FLAGS, "function" }, \
    {   "equal",       NULL, 0, AV_OPT_TYPE_CONST, {.i64 = METADATAF_EQUAL   },     0, 3, FLAGS, "function" }, \
    {   "greater",     NULL, 0, AV_OPT_TYPE_CONST, {.i64 = METADATAF_GREATER },     0, 3, FLAGS, "function" }, \
    {   "expr",        NULL, 0, AV_OPT_TYPE_CONST, {.i64 = METADATAF_EXPR    },     0, 3, FLAGS, "function" }, \
    { "expr", "set expression for expr function", OFFSET(expr_str), AV_OPT_TYPE_STRING, {.str = NULL }, 0, 0, FLAGS }, \
    { "file", "set file where to print metadata information", OFFSET(file_str), AV_OPT_TYPE_STRING, {.str=NULL}, 0, 0, FLAGS }, \
    { NULL } \
}
Definition at line 93 of file f_metadata.c.
Referenced by filter_frame().
Enumeration Type Documentation
MetadataMode
enum MetadataMode
Enumerator
METADATA_SELECT
METADATA_ADD
METADATA_MODIFY
METADATA_DELETE
METADATA_PRINT
METADATA_NB
Definition at line 41 of file f_metadata.c.
MetadataFunction
enum MetadataFunction
Enumerator
METADATAF_SAME_STR
METADATAF_STARTS_WITH
METADATAF_LESS
METADATAF_EQUAL
METADATAF_GREATER
METADATAF_EXPR
METADATAF_NB
Definition at line 50 of file f_metadata.c.
var_name
enum var_name
Enumerator
VAR_CH
VAR_N
VAR_NB_IN_CHANNELS
VAR_NB_OUT_CHANNELS
VAR_T
VAR_S
VAR_VARS_NB
VAR_VALUE1
VAR_VALUE2
VAR_VARS_NB
VAR_TB
VAR_PTS
VAR_START_PTS
VAR_PREV_PTS
VAR_PREV_SELECTED_PTS
VAR_T
VAR_START_T
VAR_PREV_T
VAR_PREV_SELECTED_T
VAR_PICT_TYPE
VAR_I
VAR_P
VAR_B
VAR_S
VAR_SI
VAR_SP
VAR_BI
VAR_PICT_TYPE_I
VAR_PICT_TYPE_P
VAR_PICT_TYPE_B
VAR_PICT_TYPE_S
VAR_PICT_TYPE_SI
VAR_PICT_TYPE_SP
VAR_PICT_TYPE_BI
VAR_INTERLACE_TYPE
VAR_INTERLACE_TYPE_P
VAR_INTERLACE_TYPE_T
VAR_INTERLACE_TYPE_B
VAR_CONSUMED_SAMPLES_N
VAR_SAMPLES_N
VAR_SAMPLE_RATE
VAR_N
VAR_SELECTED_N
VAR_PREV_SELECTED_N
VAR_KEY
VAR_POS
VAR_SCENE
VAR_CONCATDEC_SELECT
VAR_VARS_NB
VAR_FRAME_RATE
VAR_INTERLACED
VAR_N
VAR_NB_CONSUMED_SAMPLES
VAR_NB_SAMPLES
VAR_POS
VAR_PREV_INPTS
VAR_PREV_INT
VAR_PREV_OUTPTS
VAR_PREV_OUTT
VAR_PTS
VAR_SAMPLE_RATE
VAR_STARTPTS
VAR_STARTT
VAR_T
VAR_TB
VAR_RTCTIME
VAR_RTCSTART
VAR_S
VAR_SR
VAR_VARS_NB
VAR_AVTB
VAR_INTB
VAR_SR
VAR_VARS_NB
VAR_W
VAR_H
VAR_A
VAR_DAR
VAR_SAR
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_W
VAR_H
VAR_CW
VAR_CH
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_X
VAR_Y
VAR_N
VAR_POS
VAR_T
VAR_VARS_NB
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_IN_H
VAR_IH
VAR_IN_W
VAR_IW
VAR_SAR
VAR_X
VAR_Y
VAR_H
VAR_W
VAR_T
VAR_MAX
VARS_NB
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_LINE_H
VAR_LH
VAR_MAIN_H
VAR_h
VAR_H
VAR_MAIN_W
VAR_w
VAR_W
VAR_MAX_GLYPH_A
VAR_ASCENT
VAR_MAX_GLYPH_D
VAR_DESCENT
VAR_MAX_GLYPH_H
VAR_MAX_GLYPH_W
VAR_N
VAR_SAR
VAR_T
VAR_TEXT_H
VAR_TH
VAR_TEXT_W
VAR_TW
VAR_X
VAR_Y
VAR_PICT_TYPE
VAR_VARS_NB
VAR_N
VAR_POS
VAR_R
VAR_T
VAR_NB
VAR_N
VAR_PTS
VAR_R
VAR_T
VAR_TB
VAR_NB
VAR_W
VAR_H
VAR_VAL
VAR_MAXVAL
VAR_MINVAL
VAR_NEGVAL
VAR_CLIPVAL
VAR_VARS_NB
VAR_W
VAR_H
VAR_X
VAR_Y
VAR_BITDEPTHX
VAR_BITDEPTHY
VAR_VARS_NB
VAR_MAIN_W
VAR_MW
VAR_MAIN_H
VAR_MH
VAR_OVERLAY_W
VAR_OW
VAR_OVERLAY_H
VAR_OH
VAR_HSUB
VAR_VSUB
VAR_X
VAR_Y
VAR_N
VAR_POS
VAR_T
VAR_VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_X
VAR_Y
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_HSUB
VAR_VSUB
VAR_N
VAR_T
VAR_VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_OHSUB
VAR_OVSUB
VARS_NB
VAR_PI
VAR_PHI
VAR_E
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_DAR
VAR_SAR
VARS_NB
VAR_W
VAR_H
VAR_N
VAR_PTS
VAR_R
VAR_T
VAR_TB
VAR_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_IN
VAR_ON
VAR_DURATION
VAR_PDURATION
VAR_TIME
VAR_FRAME
VAR_ZOOM
VAR_PZOOM
VAR_X
VAR_PX
VAR_Y
VAR_PY
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_OHSUB
VAR_OVSUB
VARS_NB
VAR_X
VAR_Y
VAR_W
VAR_H
VAR_TIME
VAR_SPEED
VAR_TEMPO
VAR_ORDER
VAR_PATTERN
VAR_ROW
VAR_VARS_NB
Definition at line 66 of file f_metadata.c.
Function Documentation
same_str()
static int same_str (MetadataContext * s, const char * value1, const char * value2) static
Definition at line 115 of file f_metadata.c.
Referenced by init().
starts_with()
static int starts_with (MetadataContext * s, const char * value1, const char * value2) static
Definition at line 120 of file f_metadata.c.
Referenced by init().
equal()
static int equal (MetadataContext * s, const char * value1, const char * value2) static
Definition at line 125 of file f_metadata.c.
Referenced by init().
less()
static int less (MetadataContext * s, const char * value1, const char * value2) static
Definition at line 135 of file f_metadata.c.
Referenced by init().
greater()
static int greater (MetadataContext * s, const char * value1, const char * value2) static
Definition at line 145 of file f_metadata.c.
Referenced by init().
parse_expr()
static int parse_expr (MetadataContext * s, const char * value1, const char * value2) static
Definition at line 155 of file f_metadata.c.
Referenced by init().
print_log()
static void print_log (AVFilterContext * ctx, const char * msg, ...) static
Definition at line 168 of file f_metadata.c.
Referenced by init().
print_file()
static void print_file (AVFilterContext * ctx, const char * msg, ...) static
Definition at line 178 of file f_metadata.c.
Referenced by init().
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 192 of file f_metadata.c.
Referenced by filter_frame().
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 269 of file f_metadata.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * frame) static
Definition at line 278 of file f_metadata.c.
Variable Documentation
var_names
const char* const var_names[] static
Initial value:
= {
    "VALUE1",
    "VALUE2",
    NULL
}
Definition at line 60 of file f_metadata.c.
Referenced by init().