FFmpeg: libavfilter/f_streamselect.c File Reference
f_streamselect.c File Reference
#include "libavutil/avstring.h"
#include "libavutil/internal.h"
#include "libavutil/opt.h"
#include "avfilter.h"
#include "audio.h"
#include "formats.h"
#include "framesync.h"
#include "internal.h"
#include "video.h"
Data Structures
struct StreamSelectContext
Macros
#define OFFSET(x) offsetof(StreamSelectContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_FILTERING_PARAM
#define astreamselect_options streamselect_options
Functions
AVFILTER_DEFINE_CLASS (streamselect)
static int filter_frame (AVFilterLink *inlink, AVFrame *in)
static int process_frame (FFFrameSync *fs)
static int request_frame (AVFilterLink *outlink)
static int config_output (AVFilterLink *outlink)
static int parse_definition (AVFilterContext *ctx, int nb_pads, void *filter_frame, int is_audio)
static int parse_mapping (AVFilterContext *ctx, const char *map)
static int process_command (AVFilterContext *ctx, const char *cmd, const char *args, char *res, int res_len, int flags)
static av_cold int init (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
AVFILTER_DEFINE_CLASS (astreamselect)
Variables
static const AVOption streamselect_options []
AVFilter ff_vf_streamselect
AVFilter ff_af_astreamselect
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(StreamSelectContext, x)
Definition at line 41 of file f_streamselect.c.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_FILTERING_PARAM
Definition at line 42 of file f_streamselect.c.
astreamselect_options
#define astreamselect_options streamselect_options
Definition at line 340 of file f_streamselect.c.
Function Documentation
AVFILTER_DEFINE_CLASS() [1/2]
AVFILTER_DEFINE_CLASS (streamselect)
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 51 of file f_streamselect.c.
Referenced by init(), and parse_definition().
process_frame()
static int process_frame (FFFrameSync * fs) static
Definition at line 57 of file f_streamselect.c.
Referenced by config_output().
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 93 of file f_streamselect.c.
Referenced by parse_definition().
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 99 of file f_streamselect.c.
Referenced by parse_definition().
parse_definition()
static int parse_definition (AVFilterContext * ctx, int nb_pads, void * filter_frame, int is_audio) static
Definition at line 154 of file f_streamselect.c.
Referenced by init().
parse_mapping()
static int parse_mapping (AVFilterContext * ctx, const char * map) static
Definition at line 189 of file f_streamselect.c.
Referenced by init(), and process_command().
process_command()
static int process_command (AVFilterContext * ctx, const char * cmd, const char * args, char * res, int res_len, int flags) static
Definition at line 248 of file f_streamselect.c.
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 261 of file f_streamselect.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 294 of file f_streamselect.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 304 of file f_streamselect.c.
AVFILTER_DEFINE_CLASS() [2/2]
AVFILTER_DEFINE_CLASS (astreamselect)
Variable Documentation
streamselect_options
const AVOption streamselect_options[] static
Initial value:
= {
    { "inputs",  "number of input streams",           OFFSET(nb_inputs),  AV_OPT_TYPE_INT,    {.i64=2},    2, INT_MAX,  .flags=FLAGS },
    { "map",     "input indexes to remap to outputs", OFFSET(map_str),    AV_OPT_TYPE_STRING, {.str=NULL},              .flags=FLAGS },
    { NULL }
}
Definition at line 43 of file f_streamselect.c.
ff_vf_streamselect
AVFilter ff_vf_streamselect
Initial value:
= {
    .name            = "streamselect",
    .description     = NULL_IF_CONFIG_SMALL("Select video streams"),
    .init            = init,
    .query_formats   = query_formats,
    .process_command = process_command,
    .uninit          = uninit,
    .priv_size       = sizeof(StreamSelectContext),
    .priv_class      = &streamselect_class,
    .flags           = AVFILTER_FLAG_DYNAMIC_INPUTS | AVFILTER_FLAG_DYNAMIC_OUTPUTS,
}
Definition at line 328 of file f_streamselect.c.
ff_af_astreamselect
AVFilter ff_af_astreamselect
Initial value:
= {
    .name            = "astreamselect",
    .description     = NULL_IF_CONFIG_SMALL("Select audio streams"),
    .init            = init,
    .query_formats   = query_formats,
    .process_command = process_command,
    .uninit          = uninit,
    .priv_size       = sizeof(StreamSelectContext),
    .priv_class      = &astreamselect_class,
    .flags           = AVFILTER_FLAG_DYNAMIC_INPUTS | AVFILTER_FLAG_DYNAMIC_OUTPUTS,
}
Definition at line 343 of file f_streamselect.c.