FFmpeg: libavfilter/f_zmq.c File Reference
f_zmq.c File Reference
receive commands through libzeromq and broker them to filters
#include <zmq.h>
#include "libavutil/avstring.h"
#include "libavutil/bprint.h"
#include "libavutil/opt.h"
#include "avfilter.h"
#include "internal.h"
#include "avfiltergraph.h"
#include "audio.h"
#include "video.h"
Data Structures
struct ZMQContext
struct Command
Macros
#define OFFSET(x) offsetof(ZMQContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM | AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_VIDEO_PARAM
#define SPACES " \f\t\n\r"
Functions
static av_cold int init (AVFilterContext *ctx)
static void av_cold uninit (AVFilterContext *ctx)
static int parse_command (Command *cmd, const char *command_str, void *log_ctx)
static int recv_msg (AVFilterContext *ctx, char **buf, int *buf_size)
static int filter_frame (AVFilterLink *inlink, AVFrame *ref)
Variables
static const AVOption options []
Detailed Description
receive commands through libzeromq and broker them to filters
Definition in file f_zmq.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(ZMQContext, x)
Definition at line 44 of file f_zmq.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM | AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_VIDEO_PARAM
Definition at line 45 of file f_zmq.c.
SPACES
#define SPACES " \f\t\n\r"
Definition at line 93 of file f_zmq.c.
Referenced by parse_command().
Function Documentation
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 52 of file f_zmq.c.
Referenced by filter_frame().
uninit()
static void av_cold uninit (AVFilterContext * ctx) static
Definition at line 81 of file f_zmq.c.
Referenced by filter_frame().
parse_command()
static int parse_command (Command * cmd, const char * command_str, void * log_ctx) static
Definition at line 95 of file f_zmq.c.
Referenced by filter_frame().
recv_msg()
static int recv_msg (AVFilterContext * ctx, char ** buf, int * buf_size) static
Definition at line 117 of file f_zmq.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * ref) static
Definition at line 151 of file f_zmq.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "bind_address", "set bind address", OFFSET(bind_address), AV_OPT_TYPE_STRING, {.str = "tcp://*:5555"}, 0, 0, FLAGS },
    { "b",            "set bind address", OFFSET(bind_address), AV_OPT_TYPE_STRING, {.str = "tcp://*:5555"}, 0, 0, FLAGS },
    { NULL }
}
Definition at line 46 of file f_zmq.c.