FFmpeg: libavcodec/faandct.h File Reference
faandct.h File Reference
Floating point AAN DCT
#include <stdint.h>
Functions
void ff_faandct (int16_t *data)
void ff_faandct248 (int16_t *data)
Detailed Description
Floating point AAN DCT
Author
Michael Niedermayer micha.nosp@m.elni.nosp@m.@gmx..nosp@m.at
Definition in file faandct.h.
Function Documentation
ff_faandct()
void ff_faandct (int16_t * data)
Definition at line 122 of file faandct.c.
Referenced by ff_convert_matrix(), and ff_fdctdsp_init().
ff_faandct248()
void ff_faandct248 (int16_t * data)
Definition at line 184 of file faandct.c.
Referenced by ff_fdctdsp_init().