FFmpeg: libavcodec/faanidct.h File Reference
faanidct.h File Reference
#include <stdint.h>
Functions
void ff_faanidct (int16_t block[64])
void ff_faanidct_add (uint8_t *dest, int line_size, int16_t block[64])
void ff_faanidct_put (uint8_t *dest, int line_size, int16_t block[64])
Function Documentation
ff_faanidct()
void ff_faanidct (int16_t block[64])
Definition at line 134 of file faanidct.c.
Referenced by ff_idctdsp_init().
ff_faanidct_add()
void ff_faanidct_add (uint8_t * dest, int line_size, int16_t block[64])
Definition at line 147 of file faanidct.c.
Referenced by ff_idctdsp_init().
ff_faanidct_put()
void ff_faanidct_put (uint8_t * dest, int line_size, int16_t block[64])
Definition at line 160 of file faanidct.c.
Referenced by ff_idctdsp_init().