FFmpeg: libavcodec/faxcompr.c File Reference
faxcompr.c File Reference
CCITT Fax Group 3 and 4 decompression.
#include "avcodec.h"
#include "get_bits.h"
#include "put_bits.h"
#include "faxcompr.h"
Macros
#define CCITT_SYMS 104
Functions
av_cold void ff_ccitt_unpack_init (void)
initialize unpacker code
static int decode_uncompressed (AVCodecContext *avctx, GetBitContext *gb, unsigned int *pix_left, int **runs, const int *runend, int *mode)
static int decode_group3_1d_line (AVCodecContext *avctx, GetBitContext *gb, unsigned int pix_left, int *runs, const int *runend)
static int decode_group3_2d_line (AVCodecContext *avctx, GetBitContext *gb, unsigned int width, int *runs, const int *runend, const int *ref)
static void put_line (uint8_t *dst, int size, int width, const int *runs)
static int find_group3_syncmarker (GetBitContext *gb, int srcsize)
int ff_ccitt_unpack (AVCodecContext *avctx, const uint8_t *src, int srcsize, uint8_t *dst, int height, int stride, enum TiffCompr compr, int opts)
unpack data compressed with CCITT Group 3 1/2-D or Group 4 method
Variables
static const uint16_t ccitt_syms [CCITT_SYMS]
static const uint8_t ccitt_codes_bits [2][CCITT_SYMS]
static const uint8_t ccitt_codes_lens [2][CCITT_SYMS]
static const uint8_t ccitt_group3_2d_bits [11]
static const uint8_t ccitt_group3_2d_lens [11]
static VLC ccitt_vlc [2]
static VLC ccitt_group3_2d_vlc
Detailed Description
CCITT Fax Group 3 and 4 decompression.
Author
Konstantin Shishkov
Definition in file faxcompr.c.
Macro Definition Documentation
CCITT_SYMS
#define CCITT_SYMS 104
Definition at line 32 of file faxcompr.c.
Referenced by ff_ccitt_unpack_init().
Function Documentation
ff_ccitt_unpack_init()
av_cold void ff_ccitt_unpack_init (void)
initialize unpacker code
Definition at line 99 of file faxcompr.c.
Referenced by tiff_init().
decode_uncompressed()
static int decode_uncompressed (AVCodecContext * avctx, GetBitContext * gb, unsigned int * pix_left, int ** runs, const int * runend, int * mode) static
Definition at line 125 of file faxcompr.c.
Referenced by decode_group3_1d_line(), and decode_group3_2d_line().
decode_group3_1d_line()
static int decode_group3_1d_line (AVCodecContext * avctx, GetBitContext * gb, unsigned int pix_left, int * runs, const int * runend) static
Definition at line 201 of file faxcompr.c.
Referenced by ff_ccitt_unpack().
decode_group3_2d_line()
static int decode_group3_2d_line (AVCodecContext * avctx, GetBitContext * gb, unsigned int width, int * runs, const int * runend, const int * ref) static
Definition at line 245 of file faxcompr.c.
Referenced by ff_ccitt_unpack().
put_line()
static void put_line (uint8_t * dst, int size, int width, const int * runs) static
Definition at line 351 of file faxcompr.c.
Referenced by ff_ccitt_unpack().
find_group3_syncmarker()
static int find_group3_syncmarker (GetBitContext * gb, int srcsize) static
Definition at line 369 of file faxcompr.c.
Referenced by ff_ccitt_unpack().
ff_ccitt_unpack()
int ff_ccitt_unpack (AVCodecContext * avctx, const uint8_t * src, int srcsize, uint8_t * dst, int height, int stride, enum TiffCompr compr, int opts)
unpack data compressed with CCITT Group 3 1/2-D or Group 4 method
Definition at line 381 of file faxcompr.c.
Referenced by tiff_unpack_fax().
Variable Documentation
ccitt_syms
const uint16_t ccitt_syms[CCITT_SYMS] static
Initial value:
= {
    0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,   12,
   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
   26,   27,   28,   29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
   39,   40,   41,   42,   43,   44,   45,   46,   47,   48,   49,   50,   51,
   52,   53,   54,   55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
  128,  192,  256,  320,  384,  448,  512,  576,  640,  704,  768,  832,  896,
  960, 1024, 1088, 1152, 1216, 1280, 1344, 1408, 1472, 1536, 1600, 1664, 1728,
 1792, 1856, 1920, 1984, 2048, 2112, 2176, 2240, 2304, 2368, 2432, 2496, 2560
}
Definition at line 34 of file faxcompr.c.
Referenced by ff_ccitt_unpack_init().
ccitt_codes_bits
const uint8_t ccitt_codes_bits[2][CCITT_SYMS] static
Initial value:
=
{
  {
    0x35, 0x07, 0x07, 0x08, 0x0B, 0x0C, 0x0E, 0x0F, 0x13, 0x14, 0x07, 0x08, 0x08,
    0x03, 0x34, 0x35, 0x2A, 0x2B, 0x27, 0x0C, 0x08, 0x17, 0x03, 0x04, 0x28, 0x2B,
    0x13, 0x24, 0x18, 0x02, 0x03, 0x1A, 0x1B, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17,
    0x28, 0x29, 0x2A, 0x2B, 0x2C, 0x2D, 0x04, 0x05, 0x0A, 0x0B, 0x52, 0x53, 0x54,
    0x55, 0x24, 0x25, 0x58, 0x59, 0x5A, 0x5B, 0x4A, 0x4B, 0x32, 0x33, 0x34, 0x1B,
    0x12, 0x17, 0x37, 0x36, 0x37, 0x64, 0x65, 0x68, 0x67, 0xCC, 0xCD, 0xD2, 0xD3,
    0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0x98, 0x99, 0x9A, 0x18, 0x9B,
    0x08, 0x0C, 0x0D, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x1C, 0x1D, 0x1E, 0x1F
  },
  {
    0x37, 0x02, 0x03, 0x02, 0x03, 0x03, 0x02, 0x03, 0x05, 0x04, 0x04, 0x05, 0x07,
    0x04, 0x07, 0x18, 0x17, 0x18, 0x08, 0x67, 0x68, 0x6C, 0x37, 0x28, 0x17, 0x18,
    0xCA, 0xCB, 0xCC, 0xCD, 0x68, 0x69, 0x6A, 0x6B, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6,
    0xD7, 0x6C, 0x6D, 0xDA, 0xDB, 0x54, 0x55, 0x56, 0x57, 0x64, 0x65, 0x52, 0x53,
    0x24, 0x37, 0x38, 0x27, 0x28, 0x58, 0x59, 0x2B, 0x2C, 0x5A, 0x66, 0x67, 0x0F,
    0xC8, 0xC9, 0x5B, 0x33, 0x34, 0x35, 0x6C, 0x6D, 0x4A, 0x4B, 0x4C, 0x4D, 0x72,
    0x73, 0x74, 0x75, 0x76, 0x77, 0x52, 0x53, 0x54, 0x55, 0x5A, 0x5B, 0x64, 0x65,
    0x08, 0x0C, 0x0D, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x1C, 0x1D, 0x1E, 0x1F
  }
}
Definition at line 45 of file faxcompr.c.
Referenced by ff_ccitt_unpack_init().
ccitt_codes_lens
const uint8_t ccitt_codes_lens[2][CCITT_SYMS] static
Initial value:
=
{
  {
     8,  6,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  7,  7,
     7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
     8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
     8,  8,  8,  8,  5,  5,  6,  7,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,
     9,  9,  9,  9,  9,  9,  9,  9,  9,  6,  9, 11, 11, 11, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12
  },
  {
    10,  3,  2,  2,  3,  4,  4,  5,  6,  6,  7,  7,  7,  8,  8,  9, 10, 10, 10, 11,
    11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 10, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 11, 11, 11, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12
  }
}
Definition at line 69 of file faxcompr.c.
Referenced by ff_ccitt_unpack_init().
ccitt_group3_2d_bits
const uint8_t ccitt_group3_2d_bits[11] static
Initial value:
= {
    1, 1, 2, 2, 2, 1, 3, 3, 3, 1, 1
}
Definition at line 89 of file faxcompr.c.
Referenced by ff_ccitt_unpack_init().
ccitt_group3_2d_lens
const uint8_t ccitt_group3_2d_lens[11] static
Initial value:
= {
    4, 3, 7, 6, 3, 1, 3, 6, 7, 7, 9
}
Definition at line 93 of file faxcompr.c.
Referenced by ff_ccitt_unpack_init().
ccitt_vlc
VLC ccitt_vlc[2] static
Definition at line 97 of file faxcompr.c.
ccitt_group3_2d_vlc
VLC ccitt_group3_2d_vlc static
Definition at line 97 of file faxcompr.c.