FFmpeg: libavdevice/fbdev_common.c File Reference
fbdev_common.c File Reference
#include <unistd.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <stdlib.h>
#include "fbdev_common.h"
#include "libavutil/common.h"
#include "avdevice.h"
Data Structures
struct rgb_pixfmt_map_entry
Functions
enum AVPixelFormat ff_get_pixfmt_from_fb_varinfo (struct fb_var_screeninfo *varinfo)
const char * ff_fbdev_default_device ()
int ff_fbdev_get_device_list (AVDeviceInfoList *device_list)
Variables
static const struct rgb_pixfmt_map_entry rgb_pixfmt_map []
Function Documentation
ff_get_pixfmt_from_fb_varinfo()
enum AVPixelFormat ff_get_pixfmt_from_fb_varinfo (struct fb_var_screeninfo * varinfo)
Definition at line 48 of file fbdev_common.c.
Referenced by fbdev_read_header(), fbdev_write_header(), and fbdev_write_packet().
ff_fbdev_default_device()
const char* ff_fbdev_default_device (void)
Definition at line 64 of file fbdev_common.c.
Referenced by fbdev_read_header(), fbdev_write_header(), and ff_fbdev_get_device_list().
ff_fbdev_get_device_list()
int ff_fbdev_get_device_list (AVDeviceInfoList * device_list)
Definition at line 72 of file fbdev_common.c.
Referenced by fbdev_get_device_list().
Variable Documentation
rgb_pixfmt_map
const struct rgb_pixfmt_map_entry rgb_pixfmt_map[] static
Initial value:
= {
    {  32,       0,           8,          16,           24,   AV_PIX_FMT_RGBA  },
    {  32,      16,           8,           0,           24,   AV_PIX_FMT_BGRA  },
    {  32,       8,          16,          24,            0,   AV_PIX_FMT_ARGB  },
    {  32,       3,           2,           8,            0,   AV_PIX_FMT_ABGR  },
    {  24,       0,           8,          16,            0,   AV_PIX_FMT_RGB24 },
    {  24,      16,           8,           0,            0,   AV_PIX_FMT_BGR24 },
    {  16,      11,           5,           0,            0,   AV_PIX_FMT_RGB565 },
}
Definition at line 37 of file fbdev_common.c.