FFmpeg: libavdevice/fbdev_common.h File Reference
fbdev_common.h File Reference
#include <features.h>
#include <linux/fb.h>
#include "libavutil/pixfmt.h"
Functions
enum AVPixelFormat ff_get_pixfmt_from_fb_varinfo (struct fb_var_screeninfo *varinfo)
const char * ff_fbdev_default_device (void)
int ff_fbdev_get_device_list (struct AVDeviceInfoList *device_list)
Function Documentation
ff_get_pixfmt_from_fb_varinfo()
enum AVPixelFormat ff_get_pixfmt_from_fb_varinfo (struct fb_var_screeninfo * varinfo)
Definition at line 48 of file fbdev_common.c.
Referenced by fbdev_read_header(), fbdev_write_header(), and fbdev_write_packet().
ff_fbdev_default_device()
const char* ff_fbdev_default_device (void)
Definition at line 64 of file fbdev_common.c.
Referenced by fbdev_read_header(), fbdev_write_header(), and ff_fbdev_get_device_list().
ff_fbdev_get_device_list()
int ff_fbdev_get_device_list (struct AVDeviceInfoList * device_list)
Definition at line 72 of file fbdev_common.c.
Referenced by fbdev_get_device_list().