FFmpeg: libavcodec/fdctdsp.c File Reference
fdctdsp.c File Reference
#include "libavutil/attributes.h"
#include "avcodec.h"
#include "dct.h"
#include "faandct.h"
#include "fdctdsp.h"
#include "config.h"
Functions
av_cold void ff_fdctdsp_init (FDCTDSPContext *c, AVCodecContext *avctx)
Function Documentation
ff_fdctdsp_init()
av_cold void ff_fdctdsp_init (FDCTDSPContext * c, AVCodecContext * avctx)
Definition at line 26 of file fdctdsp.c.
Referenced by avcodec_dct_init(), dnxhd_encode_init(), dvvideo_encode_init(), encode_init(), ff_mpv_encode_init(), and prores_encode_init().