FFmpeg: libavcodec/ffjni.c File Reference
ffjni.c File Reference
#include <jni.h>
#include <pthread.h>
#include <stdlib.h>
#include "libavutil/bprint.h"
#include "libavutil/log.h"
#include "config.h"
#include "ffjni.h"
Functions
static void jni_detach_env (void *data)
static void jni_create_pthread_key (void)
JNIEnv * ff_jni_get_env (void *log_ctx)
char * ff_jni_jstring_to_utf_chars (JNIEnv *env, jstring string, void *log_ctx)
jstring ff_jni_utf_chars_to_jstring (JNIEnv *env, const char *utf_chars, void *log_ctx)
int ff_jni_exception_get_summary (JNIEnv *env, jthrowable exception, char **error, void *log_ctx)
int ff_jni_exception_check (JNIEnv *env, int log, void *log_ctx)
int ff_jni_init_jfields (JNIEnv *env, void *jfields, const struct FFJniField *jfields_mapping, int global, void *log_ctx)
int ff_jni_reset_jfields (JNIEnv *env, void *jfields, const struct FFJniField *jfields_mapping, int global, void *log_ctx)
Variables
static JavaVM * java_vm
static pthread_key_t current_env
static pthread_once_t once = PTHREAD_ONCE_INIT
static pthread_mutex_t lock = PTHREAD_MUTEX_INITIALIZER
Function Documentation
jni_detach_env()
static void jni_detach_env (void * data) static
Definition at line 39 of file ffjni.c.
Referenced by jni_create_pthread_key().
jni_create_pthread_key()
static void jni_create_pthread_key (void) static
Definition at line 46 of file ffjni.c.
Referenced by ff_jni_get_env().
ff_jni_get_env()
JNIEnv* ff_jni_get_env (void * log_ctx)
Definition at line 51 of file ffjni.c.
Referenced by ff_AMediaCodec_cleanOutputBuffers(), ff_AMediaCodec_createCodecByName(), ff_AMediaCodec_createDecoderByType(), ff_AMediaCodec_createEncoderByType(), ff_AMediaFormat_new(), ff_AMediaFormat_newFromObject(), ff_mediacodec_surface_ref(), and ff_mediacodec_surface_unref().
ff_jni_jstring_to_utf_chars()
char* ff_jni_jstring_to_utf_chars (JNIEnv * env, jstring string, void * log_ctx)
Definition at line 97 of file ffjni.c.
Referenced by ff_AMediaCodec_getName(), ff_AMediaCodecList_getCodecNameByType(), ff_AMediaFormat_getString(), ff_AMediaFormat_toString(), and ff_jni_exception_get_summary().
ff_jni_utf_chars_to_jstring()
jstring ff_jni_utf_chars_to_jstring (JNIEnv * env, const char * utf_chars, void * log_ctx)
Definition at line 127 of file ffjni.c.
Referenced by ff_AMediaCodec_createCodecByName(), ff_AMediaCodec_createDecoderByType(), ff_AMediaCodec_createEncoderByType(), ff_AMediaFormat_getBuffer(), ff_AMediaFormat_getFloat(), ff_AMediaFormat_getInt32(), ff_AMediaFormat_getInt64(), ff_AMediaFormat_getString(), ff_AMediaFormat_setBuffer(), ff_AMediaFormat_setFloat(), ff_AMediaFormat_setInt32(), ff_AMediaFormat_setInt64(), and ff_AMediaFormat_setString().
ff_jni_exception_get_summary()
int ff_jni_exception_get_summary (JNIEnv * env, jthrowable exception, char ** error, void * log_ctx)
Definition at line 141 of file ffjni.c.
Referenced by ff_jni_exception_check().
ff_jni_exception_check()
int ff_jni_exception_check (JNIEnv * env, int log, void * log_ctx)
Definition at line 252 of file ffjni.c.
Referenced by codec_init_static_fields(), ff_AMediaCodec_configure(), ff_AMediaCodec_createCodecByName(), ff_AMediaCodec_createDecoderByType(), ff_AMediaCodec_createEncoderByType(), ff_AMediaCodec_delete(), ff_AMediaCodec_dequeueInputBuffer(), ff_AMediaCodec_dequeueOutputBuffer(), ff_AMediaCodec_flush(), ff_AMediaCodec_getInputBuffer(), ff_AMediaCodec_getName(), ff_AMediaCodec_getOutputBuffer(), ff_AMediaCodec_getOutputFormat(), ff_AMediaCodec_queueInputBuffer(), ff_AMediaCodec_releaseOutputBuffer(), ff_AMediaCodec_releaseOutputBufferAtTime(), ff_AMediaCodec_start(), ff_AMediaCodec_stop(), ff_AMediaCodecList_getCodecNameByType(), ff_AMediaCodecProfile_getProfileFromAVCodecContext(), ff_AMediaFormat_getBuffer(), ff_AMediaFormat_getFloat(), ff_AMediaFormat_getInt32(), ff_AMediaFormat_getInt64(), ff_AMediaFormat_getString(), ff_AMediaFormat_setBuffer(), ff_AMediaFormat_setFloat(), ff_AMediaFormat_setInt32(), ff_AMediaFormat_setInt64(), ff_AMediaFormat_setString(), ff_AMediaFormat_toString(), and ff_jni_init_jfields().
ff_jni_init_jfields()
int ff_jni_init_jfields (JNIEnv * env, void * jfields, const struct FFJniField * jfields_mapping, int global, void * log_ctx)
Definition at line 285 of file ffjni.c.
Referenced by ff_AMediaCodec_createCodecByName(), ff_AMediaCodec_createDecoderByType(), ff_AMediaCodec_createEncoderByType(), ff_AMediaCodecList_getCodecNameByType(), ff_AMediaCodecProfile_getProfileFromAVCodecContext(), ff_AMediaFormat_new(), and ff_AMediaFormat_newFromObject().
ff_jni_reset_jfields()
int ff_jni_reset_jfields (JNIEnv * env, void * jfields, const struct FFJniField * jfields_mapping, int global, void * log_ctx)
Definition at line 369 of file ffjni.c.
Referenced by ff_AMediaCodec_createCodecByName(), ff_AMediaCodec_createDecoderByType(), ff_AMediaCodec_createEncoderByType(), ff_AMediaCodec_delete(), ff_AMediaCodecList_getCodecNameByType(), ff_AMediaCodecProfile_getProfileFromAVCodecContext(), ff_AMediaFormat_delete(), ff_AMediaFormat_new(), ff_AMediaFormat_newFromObject(), and ff_jni_init_jfields().
Variable Documentation
java_vm
JavaVM* java_vm static
Definition at line 34 of file ffjni.c.
Referenced by ff_jni_get_env(), and jni_detach_env().
current_env
pthread_key_t current_env static
Definition at line 35 of file ffjni.c.
Referenced by ff_jni_get_env(), and jni_create_pthread_key().
once
pthread_once_t once = PTHREAD_ONCE_INIT static
Definition at line 36 of file ffjni.c.
lock
pthread_mutex_t lock = PTHREAD_MUTEX_INITIALIZER static
Definition at line 37 of file ffjni.c.
Referenced by ff_jni_get_env().