FFmpeg: libavcodec/ffjni.h File Reference
ffjni.h File Reference
#include <jni.h>
Data Structures
struct FFJniField
Enumerations
enum FFJniFieldType {
FF_JNI_CLASS, FF_JNI_FIELD, FF_JNI_STATIC_FIELD, FF_JNI_METHOD,
FF_JNI_STATIC_METHOD
}
Functions
JNIEnv * ff_jni_get_env (void *log_ctx)
char * ff_jni_jstring_to_utf_chars (JNIEnv *env, jstring string, void *log_ctx)
jstring ff_jni_utf_chars_to_jstring (JNIEnv *env, const char *utf_chars, void *log_ctx)
int ff_jni_exception_get_summary (JNIEnv *env, jthrowable exception, char **error, void *log_ctx)
int ff_jni_exception_check (JNIEnv *env, int log, void *log_ctx)
int ff_jni_init_jfields (JNIEnv *env, void *jfields, const struct FFJniField *jfields_mapping, int global, void *log_ctx)
int ff_jni_reset_jfields (JNIEnv *env, void *jfields, const struct FFJniField *jfields_mapping, int global, void *log_ctx)
Enumeration Type Documentation
FFJniFieldType
enum FFJniFieldType
Enumerator
FF_JNI_CLASS
FF_JNI_FIELD
FF_JNI_STATIC_FIELD
FF_JNI_METHOD
FF_JNI_STATIC_METHOD
Definition at line 88 of file ffjni.h.
Function Documentation
ff_jni_get_env()
JNIEnv* ff_jni_get_env (void * log_ctx)
Definition at line 51 of file ffjni.c.
Referenced by ff_AMediaCodec_cleanOutputBuffers(), ff_AMediaCodec_createCodecByName(), ff_AMediaCodec_createDecoderByType(), ff_AMediaCodec_createEncoderByType(), ff_AMediaFormat_new(), ff_AMediaFormat_newFromObject(), ff_mediacodec_surface_ref(), and ff_mediacodec_surface_unref().
ff_jni_jstring_to_utf_chars()
char* ff_jni_jstring_to_utf_chars (JNIEnv * env, jstring string, void * log_ctx)
Definition at line 97 of file ffjni.c.
Referenced by ff_AMediaCodec_getName(), ff_AMediaCodecList_getCodecNameByType(), ff_AMediaFormat_getString(), ff_AMediaFormat_toString(), and ff_jni_exception_get_summary().
ff_jni_utf_chars_to_jstring()
jstring ff_jni_utf_chars_to_jstring (JNIEnv * env, const char * utf_chars, void * log_ctx)
Definition at line 127 of file ffjni.c.
Referenced by ff_AMediaCodec_createCodecByName(), ff_AMediaCodec_createDecoderByType(), ff_AMediaCodec_createEncoderByType(), ff_AMediaFormat_getBuffer(), ff_AMediaFormat_getFloat(), ff_AMediaFormat_getInt32(), ff_AMediaFormat_getInt64(), ff_AMediaFormat_getString(), ff_AMediaFormat_setBuffer(), ff_AMediaFormat_setFloat(), ff_AMediaFormat_setInt32(), ff_AMediaFormat_setInt64(), and ff_AMediaFormat_setString().
ff_jni_exception_get_summary()
int ff_jni_exception_get_summary (JNIEnv * env, jthrowable exception, char ** error, void * log_ctx)
Definition at line 141 of file ffjni.c.
Referenced by ff_jni_exception_check().
ff_jni_exception_check()
int ff_jni_exception_check (JNIEnv * env, int log, void * log_ctx)
Definition at line 252 of file ffjni.c.
Referenced by codec_init_static_fields(), ff_AMediaCodec_configure(), ff_AMediaCodec_createCodecByName(), ff_AMediaCodec_createDecoderByType(), ff_AMediaCodec_createEncoderByType(), ff_AMediaCodec_delete(), ff_AMediaCodec_dequeueInputBuffer(), ff_AMediaCodec_dequeueOutputBuffer(), ff_AMediaCodec_flush(), ff_AMediaCodec_getInputBuffer(), ff_AMediaCodec_getName(), ff_AMediaCodec_getOutputBuffer(), ff_AMediaCodec_getOutputFormat(), ff_AMediaCodec_queueInputBuffer(), ff_AMediaCodec_releaseOutputBuffer(), ff_AMediaCodec_releaseOutputBufferAtTime(), ff_AMediaCodec_start(), ff_AMediaCodec_stop(), ff_AMediaCodecList_getCodecNameByType(), ff_AMediaCodecProfile_getProfileFromAVCodecContext(), ff_AMediaFormat_getBuffer(), ff_AMediaFormat_getFloat(), ff_AMediaFormat_getInt32(), ff_AMediaFormat_getInt64(), ff_AMediaFormat_getString(), ff_AMediaFormat_setBuffer(), ff_AMediaFormat_setFloat(), ff_AMediaFormat_setInt32(), ff_AMediaFormat_setInt64(), ff_AMediaFormat_setString(), ff_AMediaFormat_toString(), and ff_jni_init_jfields().
ff_jni_init_jfields()
int ff_jni_init_jfields (JNIEnv * env, void * jfields, const struct FFJniField * jfields_mapping, int global, void * log_ctx)
Definition at line 285 of file ffjni.c.
Referenced by ff_AMediaCodec_createCodecByName(), ff_AMediaCodec_createDecoderByType(), ff_AMediaCodec_createEncoderByType(), ff_AMediaCodecList_getCodecNameByType(), ff_AMediaCodecProfile_getProfileFromAVCodecContext(), ff_AMediaFormat_new(), and ff_AMediaFormat_newFromObject().
ff_jni_reset_jfields()
int ff_jni_reset_jfields (JNIEnv * env, void * jfields, const struct FFJniField * jfields_mapping, int global, void * log_ctx)
Definition at line 369 of file ffjni.c.
Referenced by ff_AMediaCodec_createCodecByName(), ff_AMediaCodec_createDecoderByType(), ff_AMediaCodec_createEncoderByType(), ff_AMediaCodec_delete(), ff_AMediaCodecList_getCodecNameByType(), ff_AMediaCodecProfile_getProfileFromAVCodecContext(), ff_AMediaFormat_delete(), ff_AMediaFormat_new(), ff_AMediaFormat_newFromObject(), and ff_jni_init_jfields().