FFmpeg: libavformat/ffmdec.c File Reference
ffmdec.c File Reference
#include <stdint.h>
#include "libavutil/imgutils.h"
#include "libavutil/internal.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/intfloat.h"
#include "libavutil/opt.h"
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/pixdesc.h"
#include "libavcodec/internal.h"
#include "avformat.h"
#include "internal.h"
#include "ffm.h"
#include "avio_internal.h"
Macros
#define VALIDATE_PARAMETER(parameter, name, check)
Functions
static int ffm_is_avail_data (AVFormatContext *s, int size)
static int ffm_resync (AVFormatContext *s, uint32_t state)
static int ffm_read_data (AVFormatContext *s, uint8_t *buf, int size, int header)
static int64_t ffm_seek1 (AVFormatContext *s, int64_t pos1)
static int64_t get_dts (AVFormatContext *s, int64_t pos)
static void adjust_write_index (AVFormatContext *s)
static int ffm_append_recommended_configuration (AVStream *st, char **conf)
static int ffm2_read_header (AVFormatContext *s)
static int ffm_read_header (AVFormatContext *s)
static int ffm_read_packet (AVFormatContext *s, AVPacket *pkt)
static int ffm_seek (AVFormatContext *s, int stream_index, int64_t wanted_pts, int flags)
static int ffm_probe (AVProbeData *p)
Variables
static const AVOption options []
static const AVClass ffm_class
AVInputFormat ff_ffm_demuxer
Macro Definition Documentation
VALIDATE_PARAMETER
#define VALIDATE_PARAMETER (parameter, name, check)
Value:
{                              \
    if (check) {                                                                  \
        av_log(s, AV_LOG_ERROR, "Invalid " name " %d\n", codecpar->parameter);   \
        ret = AVERROR_INVALIDDATA;                                                \
        goto fail;                                                                \
    }                                                                             \
}
Definition at line 272 of file ffmdec.c.
Referenced by ffm2_read_header(), and ffm_read_header().
Function Documentation
ffm_is_avail_data()
static int ffm_is_avail_data (AVFormatContext * s, int size) static
Definition at line 38 of file ffmdec.c.
Referenced by ffm_read_packet().
ffm_resync()
static int ffm_resync (AVFormatContext * s, uint32_t state) static
Definition at line 74 of file ffmdec.c.
Referenced by ffm_read_data().
ffm_read_data()
static int ffm_read_data (AVFormatContext * s, uint8_t * buf, int size, int header) static
Definition at line 88 of file ffmdec.c.
Referenced by ffm_read_packet().
ffm_seek1()
static int64_t ffm_seek1 (AVFormatContext * s, int64_t pos1) static
Definition at line 173 of file ffmdec.c.
Referenced by ffm_seek(), and get_dts().
get_dts()
static int64_t get_dts (AVFormatContext * s, int64_t pos) static
Definition at line 185 of file ffmdec.c.
Referenced by adjust_write_index(), and ffm_seek().
adjust_write_index()
static void adjust_write_index (AVFormatContext * s) static
Definition at line 197 of file ffmdec.c.
Referenced by ffm2_read_header(), and ffm_read_header().
ffm_append_recommended_configuration()
static int ffm_append_recommended_configuration (AVStream * st, char ** conf) static
Definition at line 251 of file ffmdec.c.
Referenced by ffm2_read_header().
ffm2_read_header()
static int ffm2_read_header (AVFormatContext * s) static
Definition at line 280 of file ffmdec.c.
Referenced by ffm_read_header().
ffm_read_header()
static int ffm_read_header (AVFormatContext * s) static
Definition at line 536 of file ffmdec.c.
ffm_read_packet()
static int ffm_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 723 of file ffmdec.c.
ffm_seek()
static int ffm_seek (AVFormatContext * s, int stream_index, int64_t wanted_pts, int flags) static
Definition at line 785 of file ffmdec.c.
ffm_probe()
static int ffm_probe (AVProbeData * p) static
Definition at line 847 of file ffmdec.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    {"server_attached", NULL, 0x42, AV_OPT_TYPE_BOOL, {.i64 = 0}, 0, 1, AV_OPT_FLAG_EXPORT },
    {"ffm_write_index", NULL, 0x42, AV_OPT_TYPE_INT64, {.i64 = 0}, 0, INT64_MAX, AV_OPT_FLAG_EXPORT },
    {"ffm_file_size", NULL, 0x42, AV_OPT_TYPE_INT64, {.i64 = 0}, 0, INT64_MAX, AV_OPT_FLAG_EXPORT },
    { NULL },
}
Definition at line 856 of file ffmdec.c.
ffm_class
const AVClass ffm_class static
Initial value:
= {
    .class_name = "ffm demuxer",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 863 of file ffmdec.c.
ff_ffm_demuxer
AVInputFormat ff_ffm_demuxer
Initial value:
= {
    .name           = "ffm",
    .long_name      = NULL_IF_CONFIG_SMALL("FFM (FFserver live feed)"),
    .priv_data_size = sizeof(FFMContext),
    .read_probe     = ffm_probe,
    .read_header    = ffm_read_header,
    .read_packet    = ffm_read_packet,
    .read_seek      = ffm_seek,
    .priv_class     = &ffm_class,
}
Definition at line 869 of file ffmdec.c.