FFmpeg: libavformat/ffmenc.c File Reference
ffmenc.c File Reference
#include "libavutil/intreadwrite.h"
#include "libavutil/intfloat.h"
#include "libavutil/avassert.h"
#include "libavutil/parseutils.h"
#include "libavutil/opt.h"
#include "avformat.h"
#include "avio_internal.h"
#include "internal.h"
#include "ffm.h"
Macros
#define SKIP_DEFAULTS AV_OPT_SERIALIZE_SKIP_DEFAULTS
#define OPT_FLAGS_EXACT AV_OPT_SERIALIZE_OPT_FLAGS_EXACT
#define ENC AV_OPT_FLAG_ENCODING_PARAM
Functions
static void flush_packet (AVFormatContext *s)
static void ffm_write_data (AVFormatContext *s, const uint8_t *buf, int size, int64_t dts, int header)
static void write_header_chunk (AVIOContext *pb, AVIOContext *dpb, unsigned id)
static int ffm_write_header_codec_ctx (AVIOContext *pb, AVCodecParameters *ctxpar, unsigned tag, int type)
static int ffm_write_recommended_config (AVIOContext *pb, AVCodecParameters *codecpar, unsigned tag, const char *configuration)
static int ffm_write_header (AVFormatContext *s)
static int ffm_write_packet (AVFormatContext *s, AVPacket *pkt)
static int ffm_write_trailer (AVFormatContext *s)
Variables
AVOutputFormat ff_ffm_muxer
Macro Definition Documentation
SKIP_DEFAULTS
#define SKIP_DEFAULTS AV_OPT_SERIALIZE_SKIP_DEFAULTS
Referenced by ffm_write_header_codec_ctx().
OPT_FLAGS_EXACT
#define OPT_FLAGS_EXACT AV_OPT_SERIALIZE_OPT_FLAGS_EXACT
Referenced by ffm_write_header_codec_ctx().
ENC
#define ENC AV_OPT_FLAG_ENCODING_PARAM
Referenced by ffm_write_header_codec_ctx().
Function Documentation
flush_packet()
static void flush_packet (AVFormatContext * s) static
Definition at line 32 of file ffmenc.c.
Referenced by ffm_write_data(), and ffm_write_trailer().
ffm_write_data()
static void ffm_write_data (AVFormatContext * s, const uint8_t * buf, int size, int64_t dts, int header) static
Definition at line 61 of file ffmenc.c.
Referenced by ffm_write_packet().
write_header_chunk()
static void write_header_chunk (AVIOContext * pb, AVIOContext * dpb, unsigned id) static
Definition at line 88 of file ffmenc.c.
Referenced by ffm_write_header(), ffm_write_header_codec_ctx(), and ffm_write_recommended_config().
ffm_write_header_codec_ctx()
static int ffm_write_header_codec_ctx (AVIOContext * pb, AVCodecParameters * ctxpar, unsigned tag, int type) static
Definition at line 98 of file ffmenc.c.
Referenced by ffm_write_header().
ffm_write_recommended_config()
static int ffm_write_recommended_config (AVIOContext * pb, AVCodecParameters * codecpar, unsigned tag, const char * configuration) static
Definition at line 151 of file ffmenc.c.
Referenced by ffm_write_header().
ffm_write_header()
static int ffm_write_header (AVFormatContext * s) static
Definition at line 205 of file ffmenc.c.
ffm_write_packet()
static int ffm_write_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 313 of file ffmenc.c.
ffm_write_trailer()
static int ffm_write_trailer (AVFormatContext * s) static
Definition at line 340 of file ffmenc.c.
Variable Documentation
ff_ffm_muxer
AVOutputFormat ff_ffm_muxer
Initial value:
= {
    .name              = "ffm",
    .long_name         = NULL_IF_CONFIG_SMALL("FFM (FFserver live feed)"),
    .extensions        = "ffm",
    .priv_data_size    = sizeof(FFMContext),
    .audio_codec       = AV_CODEC_ID_MP2,
    .video_codec       = AV_CODEC_ID_MPEG1VIDEO,
    .write_header      = ffm_write_header,
    .write_packet      = ffm_write_packet,
    .write_trailer     = ffm_write_trailer,
    .flags             = AVFMT_TS_NEGATIVE,
}
Definition at line 351 of file ffmenc.c.