FFmpeg: libavformat/ffmetadec.c File Reference
ffmetadec.c File Reference
#include "libavutil/mathematics.h"
#include "avformat.h"
#include "ffmeta.h"
#include "internal.h"
#include "libavutil/dict.h"
Functions
static int probe (AVProbeData *p)
static void get_line (AVIOContext *s, uint8_t *buf, int size)
static AVChapter * read_chapter (AVFormatContext *s)
static uint8_t * unescape (const uint8_t *buf, int size)
static int read_tag (const uint8_t *line, AVDictionary **m)
static int read_header (AVFormatContext *s)
static int read_packet (AVFormatContext *s, AVPacket *pkt)
Variables
AVInputFormat ff_ffmetadata_demuxer
Function Documentation
probe()
static int probe (AVProbeData * p) static
Definition at line 28 of file ffmetadec.c.
get_line()
static void get_line (AVIOContext * s, uint8_t * buf, int size) static
Definition at line 35 of file ffmetadec.c.
Referenced by read_chapter(), and read_header().
read_chapter()
static AVChapter* read_chapter (AVFormatContext * s) static
Definition at line 56 of file ffmetadec.c.
Referenced by read_header().
unescape()
static uint8_t* unescape (const uint8_t * buf, int size) static
Definition at line 81 of file ffmetadec.c.
Referenced by read_tag().
read_tag()
static int read_tag (const uint8_t * line, AVDictionary ** m) static
Definition at line 99 of file ffmetadec.c.
Referenced by read_header().
read_header()
static int read_header (AVFormatContext * s) static
Definition at line 128 of file ffmetadec.c.
read_packet()
static int read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 166 of file ffmetadec.c.
Variable Documentation
ff_ffmetadata_demuxer
AVInputFormat ff_ffmetadata_demuxer
Initial value:
= {
    .name        = "ffmetadata",
    .long_name   = NULL_IF_CONFIG_SMALL("FFmpeg metadata in text"),
    .read_probe  = probe,
    .read_header = read_header,
    .read_packet = read_packet,
}
Definition at line 171 of file ffmetadec.c.