FFmpeg: ffmpeg_vdpau.c File Reference
ffmpeg_vdpau.c File Reference
#include <stdint.h>
#include "ffmpeg.h"
#include "libavcodec/vdpau.h"
#include "libavutil/buffer.h"
#include "libavutil/frame.h"
#include "libavutil/hwcontext.h"
#include "libavutil/hwcontext_vdpau.h"
#include "libavutil/pixfmt.h"
Data Structures
struct VDPAUContext
Functions
static void vdpau_uninit (AVCodecContext *s)
static int vdpau_get_buffer (AVCodecContext *s, AVFrame *frame, int flags)
static int vdpau_retrieve_data (AVCodecContext *s, AVFrame *frame)
static int vdpau_alloc (AVCodecContext *s)
int vdpau_init (AVCodecContext *s)
Function Documentation
vdpau_uninit()
static void vdpau_uninit (AVCodecContext * s) static
Definition at line 36 of file ffmpeg_vdpau.c.
Referenced by vdpau_alloc().
vdpau_get_buffer()
static int vdpau_get_buffer (AVCodecContext * s, AVFrame * frame, int flags) static
Definition at line 52 of file ffmpeg_vdpau.c.
Referenced by vdpau_alloc(), and vdpau_init().
vdpau_retrieve_data()
static int vdpau_retrieve_data (AVCodecContext * s, AVFrame * frame) static
Definition at line 60 of file ffmpeg_vdpau.c.
Referenced by vdpau_alloc(), and vdpau_init().
vdpau_alloc()
static int vdpau_alloc (AVCodecContext * s) static
Definition at line 82 of file ffmpeg_vdpau.c.
Referenced by vdpau_init().
vdpau_init()
int vdpau_init (AVCodecContext * s)
Definition at line 145 of file ffmpeg_vdpau.c.