FFmpeg: ffmpeg_qsv.c File Reference
ffmpeg_qsv.c File Reference
#include <mfx/mfxvideo.h>
#include <stdlib.h>
#include "libavutil/dict.h"
#include "libavutil/hwcontext.h"
#include "libavutil/hwcontext_qsv.h"
#include "libavutil/mem.h"
#include "libavutil/opt.h"
#include "libavcodec/qsv.h"
#include "ffmpeg.h"
Functions
static int qsv_get_buffer (AVCodecContext *s, AVFrame *frame, int flags)
static void qsv_uninit (AVCodecContext *s)
static int qsv_device_init (InputStream *ist)
int qsv_init (AVCodecContext *s)
int qsv_transcode_init (OutputStream *ost)
Function Documentation
qsv_get_buffer()
static int qsv_get_buffer (AVCodecContext * s, AVFrame * frame, int flags) static
Definition at line 31 of file ffmpeg_qsv.c.
Referenced by qsv_init().
qsv_uninit()
static void qsv_uninit (AVCodecContext * s) static
Definition at line 38 of file ffmpeg_qsv.c.
Referenced by qsv_init().
qsv_device_init()
static int qsv_device_init (InputStream * ist) static
Definition at line 44 of file ffmpeg_qsv.c.
Referenced by qsv_init(), and qsv_transcode_init().
qsv_init()
int qsv_init (AVCodecContext * s)
Definition at line 58 of file ffmpeg_qsv.c.
qsv_transcode_init()
int qsv_transcode_init (OutputStream * ost)
Definition at line 98 of file ffmpeg_qsv.c.
Referenced by transcode_init().