FFmpeg: ffmpeg.c File Reference
ffmpeg.c File Reference
multimedia converter based on the FFmpeg libraries
#include "config.h"
#include <ctype.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>
#include <errno.h>
#include <limits.h>
#include <stdint.h>
#include "libavformat/avformat.h"
#include "libavdevice/avdevice.h"
#include "libswresample/swresample.h"
#include "libavutil/opt.h"
#include "libavutil/channel_layout.h"
#include "libavutil/parseutils.h"
#include "libavutil/samplefmt.h"
#include "libavutil/fifo.h"
#include "libavutil/internal.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/dict.h"
#include "libavutil/mathematics.h"
#include "libavutil/pixdesc.h"
#include "libavutil/avstring.h"
#include "libavutil/libm.h"
#include "libavutil/imgutils.h"
#include "libavutil/timestamp.h"
#include "libavutil/bprint.h"
#include "libavutil/time.h"
#include "libavutil/threadmessage.h"
#include "libavcodec/mathops.h"
#include "libavformat/os_support.h"
#include "libavfilter/avfilter.h"
#include "libavfilter/buffersrc.h"
#include "libavfilter/buffersink.h"
#include "ffmpeg.h"
#include "cmdutils.h"
#include "libavutil/avassert.h"
Functions
static void do_video_stats (OutputStream *ost, int frame_size)
static int64_t getutime (void)
static int64_t getmaxrss (void)
static int sub2video_get_blank_frame (InputStream *ist)
static void sub2video_copy_rect (uint8_t *dst, int dst_linesize, int w, int h, AVSubtitleRect *r)
static void sub2video_push_ref (InputStream *ist, int64_t pts)
static void sub2video_update (InputStream *ist, AVSubtitle *sub)
static void sub2video_heartbeat (InputStream *ist, int64_t pts)
static void sub2video_flush (InputStream *ist)
static void term_exit_sigsafe (void)
void term_exit (void)
static void sigterm_handler (int sig)
void term_init (void)
static int read_key (void)
static int decode_interrupt_cb (void *ctx)
static void ffmpeg_cleanup (int ret)
void remove_avoptions (AVDictionary **a, AVDictionary *b)
void assert_avoptions (AVDictionary *m)
static void abort_codec_experimental (AVCodec *c, int encoder)
static void update_benchmark (const char *fmt,...)
static void close_all_output_streams (OutputStream *ost, OSTFinished this_stream, OSTFinished others)
static void write_packet (OutputFile *of, AVPacket *pkt, OutputStream *ost)
static void close_output_stream (OutputStream *ost)
static void output_packet (OutputFile *of, AVPacket *pkt, OutputStream *ost)
static int check_recording_time (OutputStream *ost)
static void do_audio_out (OutputFile *of, OutputStream *ost, AVFrame *frame)
static void do_subtitle_out (OutputFile *of, OutputStream *ost, AVSubtitle *sub)
static void do_video_out (OutputFile *of, OutputStream *ost, AVFrame *next_picture, double sync_ipts)
static double psnr (double d)
static void finish_output_stream (OutputStream *ost)
static int reap_filters (int flush)
Get and encode new output from any of the filtergraphs, without causing activity.
static void print_final_stats (int64_t total_size)
static void print_report (int is_last_report, int64_t timer_start, int64_t cur_time)
static void flush_encoders (void)
static int check_output_constraints (InputStream *ist, OutputStream *ost)
static void do_streamcopy (InputStream *ist, OutputStream *ost, const AVPacket *pkt)
int guess_input_channel_layout (InputStream *ist)
static void check_decode_result (InputStream *ist, int *got_output, int ret)
static int decode (AVCodecContext *avctx, AVFrame *frame, int *got_frame, AVPacket *pkt)
static int send_frame_to_filters (InputStream *ist, AVFrame *decoded_frame)
static int decode_audio (InputStream *ist, AVPacket *pkt, int *got_output)
static int decode_video (InputStream *ist, AVPacket *pkt, int *got_output, int eof)
static int transcode_subtitles (InputStream *ist, AVPacket *pkt, int *got_output)
static int send_filter_eof (InputStream *ist)
static int process_input_packet (InputStream *ist, const AVPacket *pkt, int no_eof)
static void print_sdp (void)
static const HWAccel * get_hwaccel (enum AVPixelFormat pix_fmt)
static enum AVPixelFormat get_format (AVCodecContext *s, const enum AVPixelFormat *pix_fmts)
static int get_buffer (AVCodecContext *s, AVFrame *frame, int flags)
static int init_input_stream (int ist_index, char *error, int error_len)
static InputStream * get_input_stream (OutputStream *ost)
static int compare_int64 (const void *a, const void *b)
static int check_init_output_file (OutputFile *of, int file_index)
static int init_output_bsfs (OutputStream *ost)
static int init_output_stream_streamcopy (OutputStream *ost)
static void set_encoder_id (OutputFile *of, OutputStream *ost)
static void parse_forced_key_frames (char *kf, OutputStream *ost, AVCodecContext *avctx)
static int init_output_stream_encode (OutputStream *ost)
static int init_output_stream (OutputStream *ost, char *error, int error_len)
static void report_new_stream (int input_index, AVPacket *pkt)
static int transcode_init (void)
static int need_output (void)
static OutputStream * choose_output (void)
Select the output stream to process.
static void set_tty_echo (int on)
static int check_keyboard_interaction (int64_t cur_time)
static int get_input_packet (InputFile *f, AVPacket *pkt)
static int got_eagain (void)
static void reset_eagain (void)
static AVRational duration_max (int64_t tmp, int64_t *duration, AVRational tmp_time_base, AVRational time_base)
static int seek_to_start (InputFile *ifile, AVFormatContext *is)
static int process_input (int file_index)
static int transcode_from_filter (FilterGraph *graph, InputStream **best_ist)
Perform a step of transcoding for the specified filter graph.
static int transcode_step (void)
Run a single step of transcoding.
static int transcode (void)
static void log_callback_null (void *ptr, int level, const char *fmt, va_list vl)
int main (int argc, char **argv)
Variables
const char program_name [] = "ffmpeg"
program name, defined by the program for show_version().
const int program_birth_year = 2000
program birth year, defined by the program for show_banner()
static FILE * vstats_file
const char *const forced_keyframes_const_names []
static int run_as_daemon = 0
static int nb_frames_dup = 0
static unsigned dup_warning = 1000
static int nb_frames_drop = 0
static int64_t decode_error_stat [2]
static int want_sdp = 1
static int current_time
AVIOContext * progress_avio = NULL
static uint8_t * subtitle_out
InputStream ** input_streams = NULL
int nb_input_streams = 0
InputFile ** input_files = NULL
int nb_input_files = 0
OutputStream ** output_streams = NULL
int nb_output_streams = 0
OutputFile ** output_files = NULL
int nb_output_files = 0
FilterGraph ** filtergraphs
int nb_filtergraphs
static volatile int received_sigterm = 0
static volatile int received_nb_signals = 0
static volatile int transcode_init_done = 0
static volatile int ffmpeg_exited = 0
static int main_return_code = 0
const AVIOInterruptCB int_cb = { decode_interrupt_cb, NULL }
Detailed Description
multimedia converter based on the FFmpeg libraries
Definition in file ffmpeg.c.
Function Documentation
do_video_stats()
static void do_video_stats (OutputStream * ost, int frame_size) static
Definition at line 1336 of file ffmpeg.c.
Referenced by do_video_out(), and flush_encoders().
getutime()
static int64_t getutime (void) static
Definition at line 4513 of file ffmpeg.c.
Referenced by main(), and update_benchmark().
getmaxrss()
static int64_t getmaxrss (void) static
Definition at line 4531 of file ffmpeg.c.
Referenced by ffmpeg_cleanup().
sub2video_get_blank_frame()
static int sub2video_get_blank_frame (InputStream * ist) static
Definition at line 172 of file ffmpeg.c.
Referenced by sub2video_update().
sub2video_copy_rect()
static void sub2video_copy_rect (uint8_t * dst, int dst_linesize, int w, int h, AVSubtitleRect * r) static
Definition at line 187 of file ffmpeg.c.
Referenced by sub2video_update().
sub2video_push_ref()
static void sub2video_push_ref (InputStream * ist, int64_t pts) static
Definition at line 218 of file ffmpeg.c.
Referenced by sub2video_heartbeat(), and sub2video_update().
sub2video_update()
static void sub2video_update (InputStream * ist, AVSubtitle * sub) static
Definition at line 231 of file ffmpeg.c.
Referenced by sub2video_flush(), sub2video_heartbeat(), and transcode_subtitles().
sub2video_heartbeat()
static void sub2video_heartbeat (InputStream * ist, int64_t pts) static
Definition at line 265 of file ffmpeg.c.
Referenced by process_input().
sub2video_flush()
static void sub2video_flush (InputStream * ist) static
Definition at line 294 of file ffmpeg.c.
Referenced by transcode_subtitles().
term_exit_sigsafe()
static void term_exit_sigsafe (void) static
Definition at line 306 of file ffmpeg.c.
Referenced by sigterm_handler(), and term_exit().
term_exit()
void term_exit (void)
Definition at line 314 of file ffmpeg.c.
Referenced by assert_file_overwrite(), ffmpeg_cleanup(), and transcode().
sigterm_handler()
static void sigterm_handler (int sig) static
Definition at line 327 of file ffmpeg.c.
Referenced by term_init().
term_init()
void term_init (void)
Definition at line 372 of file ffmpeg.c.
Referenced by assert_file_overwrite(), and ffmpeg_parse_options().
read_key()
static int read_key (void) static
Definition at line 407 of file ffmpeg.c.
Referenced by check_keyboard_interaction().
decode_interrupt_cb()
static int decode_interrupt_cb (void * ctx) static
Definition at line 458 of file ffmpeg.c.
ffmpeg_cleanup()
static void ffmpeg_cleanup (int ret) static
Definition at line 465 of file ffmpeg.c.
Referenced by main().
remove_avoptions()
void remove_avoptions (AVDictionary ** a, AVDictionary * b)
Definition at line 606 of file ffmpeg.c.
Referenced by open_input_file().
assert_avoptions()
void assert_avoptions (AVDictionary * m)
Definition at line 615 of file ffmpeg.c.
Referenced by init_input_stream(), init_output_stream(), and open_input_file().
abort_codec_experimental()
static void abort_codec_experimental (AVCodec * c, int encoder) static
Definition at line 624 of file ffmpeg.c.
Referenced by init_input_stream(), and init_output_stream().
update_benchmark()
static void update_benchmark (const char * fmt, ...) static
Definition at line 629 of file ffmpeg.c.
Referenced by decode_audio(), decode_video(), do_audio_out(), do_video_out(), and flush_encoders().
close_all_output_streams()
static void close_all_output_streams (OutputStream * ost, OSTFinished this_stream, OSTFinished others) static
Definition at line 646 of file ffmpeg.c.
Referenced by write_packet().
write_packet()
static void write_packet (OutputFile * of, AVPacket * pkt, OutputStream * ost) static
Definition at line 655 of file ffmpeg.c.
Referenced by avio_alloc_context(), check_init_output_file(), ffio_init_context(), mmf_read_packet(), mov_check_bitstream(), ogg_write_trailer(), output_packet(), and swf_write_trailer().
close_output_stream()
static void close_output_stream (OutputStream * ost) static
Definition at line 783 of file ffmpeg.c.
Referenced by check_recording_time(), do_streamcopy(), need_output(), and transcode_from_filter().
output_packet()
static void output_packet (OutputFile * of, AVPacket * pkt, OutputStream * ost) static
Examples:
transcode_aac.c.
Definition at line 794 of file ffmpeg.c.
Referenced by do_audio_out(), do_streamcopy(), do_subtitle_out(), do_video_out(), encode_audio_frame(), and flush_encoders().
check_recording_time()
static int check_recording_time (OutputStream * ost) static
Definition at line 857 of file ffmpeg.c.
Referenced by do_audio_out(), do_subtitle_out(), and do_video_out().
do_audio_out()
static void do_audio_out (OutputFile * of, OutputStream * ost, AVFrame * frame) static
Definition at line 870 of file ffmpeg.c.
Referenced by reap_filters().
do_subtitle_out()
static void do_subtitle_out (OutputFile * of, OutputStream * ost, AVSubtitle * sub) static
Definition at line 930 of file ffmpeg.c.
Referenced by transcode_subtitles().
do_video_out()
static void do_video_out (OutputFile * of, OutputStream * ost, AVFrame * next_picture, double sync_ipts) static
Definition at line 1013 of file ffmpeg.c.
Referenced by reap_filters().
psnr()
static double psnr (double d) static
Definition at line 1331 of file ffmpeg.c.
Referenced by avfilter_register_all(), do_video_stats(), main(), print_report(), and run_psnr().
finish_output_stream()
static void finish_output_stream (OutputStream * ost) static
Definition at line 1374 of file ffmpeg.c.
Referenced by process_input().
reap_filters()
static int reap_filters (int flush) static
Get and encode new output from any of the filtergraphs, without causing activity.
Returns
0 for success, <0 for severe errors
Definition at line 1393 of file ffmpeg.c.
Referenced by transcode_from_filter(), and transcode_step().
print_final_stats()
static void print_final_stats (int64_t total_size) static
Definition at line 1488 of file ffmpeg.c.
Referenced by print_report().
print_report()
static void print_report (int is_last_report, int64_t timer_start, int64_t cur_time) static
Definition at line 1605 of file ffmpeg.c.
Referenced by transcode().
flush_encoders()
static void flush_encoders (void) static
Definition at line 1815 of file ffmpeg.c.
Referenced by transcode().
check_output_constraints()
static int check_output_constraints (InputStream * ist, OutputStream * ost) static
Definition at line 1891 of file ffmpeg.c.
Referenced by process_input_packet(), and transcode_subtitles().
do_streamcopy()
static void do_streamcopy (InputStream * ist, OutputStream * ost, const AVPacket * pkt) static
Definition at line 1908 of file ffmpeg.c.
Referenced by process_input_packet().
guess_input_channel_layout()
int guess_input_channel_layout (InputStream * ist)
Definition at line 2021 of file ffmpeg.c.
Referenced by add_input_streams(), and decode_audio().
check_decode_result()
static void check_decode_result (InputStream * ist, int * got_output, int ret) static
Definition at line 2041 of file ffmpeg.c.
Referenced by decode_audio(), decode_video(), and transcode_subtitles().
decode()
static int decode (AVCodecContext * avctx, AVFrame * frame, int * got_frame, AVPacket * pkt) static
Examples:
qsvdec.c.
Definition at line 2061 of file ffmpeg.c.
Referenced by amr_decode_fix_avctx(), cyuv_decode_frame(), decode_audio(), decode_end(), decode_flush(), decode_frame(), decode_video(), dxva2_init_pool(), eightsvx_decode_close(), ff_vp8_decode_init(), flashsv_decode_frame(), flush(), frame_alloc(), g726_reset(), get_buffer(), get_format(), gsm_flush(), libgsm_flush(), main(), mediacodec_decode_flush(), mvc_decode_frame(), png_dec_end(), pnm_decode_frame(), predictor_calc_error(), read_access_unit(), read_huffman_tree(), show_formats_devices(), sp5x_decode_frame(), and vpx_free().
send_frame_to_filters()
static int send_frame_to_filters (InputStream * ist, AVFrame * decoded_frame) static
Definition at line 2084 of file ffmpeg.c.
Referenced by decode_audio(), and decode_video().
decode_audio()
static int decode_audio (InputStream * ist, AVPacket * pkt, int * got_output) static
Definition at line 2111 of file ffmpeg.c.
Referenced by process_input_packet().
decode_video()
static int decode_video (InputStream * ist, AVPacket * pkt, int * got_output, int eof) static
Definition at line 2229 of file ffmpeg.c.
Referenced by process_input_packet().
transcode_subtitles()
static int transcode_subtitles (InputStream * ist, AVPacket * pkt, int * got_output) static
Definition at line 2388 of file ffmpeg.c.
Referenced by process_input_packet().
send_filter_eof()
static int send_filter_eof (InputStream * ist) static
Definition at line 2447 of file ffmpeg.c.
Referenced by process_input_packet().
process_input_packet()
static int process_input_packet (InputStream * ist, const AVPacket * pkt, int no_eof) static
Definition at line 2459 of file ffmpeg.c.
Referenced by process_input(), seek_to_start(), and transcode().
print_sdp()
static void print_sdp (void) static
Definition at line 2625 of file ffmpeg.c.
Referenced by check_init_output_file().
get_hwaccel()
static const HWAccel* get_hwaccel (enum AVPixelFormat pix_fmt) static
Definition at line 2670 of file ffmpeg.c.
Referenced by get_format().
get_format()
static enum AVPixelFormat get_format (AVCodecContext * s, const enum AVPixelFormat * pix_fmts) static
Definition at line 2679 of file ffmpeg.c.
Referenced by init_input_stream().
get_buffer()
static int get_buffer (AVCodecContext * s, AVFrame * frame, int flags) static
Definition at line 2724 of file ffmpeg.c.
Referenced by init_input_stream().
init_input_stream()
static int init_input_stream (int ist_index, char * error, int error_len) static
Definition at line 2734 of file ffmpeg.c.
Referenced by transcode_init().
get_input_stream()
static InputStream* get_input_stream (OutputStream * ost) static
Definition at line 2795 of file ffmpeg.c.
Referenced by init_output_stream(), init_output_stream_encode(), and init_output_stream_streamcopy().
compare_int64()
static int compare_int64 (const void * a, const void * b) static
Definition at line 2802 of file ffmpeg.c.
Referenced by parse_forced_key_frames().
check_init_output_file()
static int check_init_output_file (OutputFile * of, int file_index) static
Definition at line 2808 of file ffmpeg.c.
Referenced by init_output_stream(), and transcode_init().
init_output_bsfs()
static int init_output_bsfs (OutputStream * ost) static
Definition at line 2850 of file ffmpeg.c.
Referenced by init_output_stream().
init_output_stream_streamcopy()
static int init_output_stream_streamcopy (OutputStream * ost) static
Definition at line 2886 of file ffmpeg.c.
Referenced by init_output_stream().
set_encoder_id()
static void set_encoder_id (OutputFile * of, OutputStream * ost) static
Definition at line 2997 of file ffmpeg.c.
Referenced by init_output_stream_encode().
parse_forced_key_frames()
static void parse_forced_key_frames (char * kf, OutputStream * ost, AVCodecContext * avctx) static
Definition at line 3038 of file ffmpeg.c.
Referenced by init_output_stream_encode().
init_output_stream_encode()
static int init_output_stream_encode (OutputStream * ost) static
Definition at line 3101 of file ffmpeg.c.
Referenced by init_output_stream().
init_output_stream()
static int init_output_stream (OutputStream * ost, char * error, int error_len) static
Definition at line 3265 of file ffmpeg.c.
Referenced by transcode_init().
report_new_stream()
static void report_new_stream (int input_index, AVPacket * pkt) static
Definition at line 3420 of file ffmpeg.c.
Referenced by process_input().
transcode_init()
static int transcode_init (void) static
Definition at line 3435 of file ffmpeg.c.
Referenced by transcode().
need_output()
static int need_output (void) static
Definition at line 3621 of file ffmpeg.c.
Referenced by transcode().
choose_output()
static OutputStream* choose_output (void) static
Select the output stream to process.
Returns
selected output stream, or NULL if none available
Definition at line 3651 of file ffmpeg.c.
Referenced by transcode_step().
set_tty_echo()
static void set_tty_echo (int on) static
Definition at line 3673 of file ffmpeg.c.
Referenced by check_keyboard_interaction().
check_keyboard_interaction()
static int check_keyboard_interaction (int64_t cur_time) static
Definition at line 3685 of file ffmpeg.c.
Referenced by transcode().
get_input_packet()
static int get_input_packet (InputFile * f, AVPacket * pkt) static
Definition at line 3901 of file ffmpeg.c.
Referenced by process_input().
got_eagain()
static int got_eagain (void) static
Definition at line 3921 of file ffmpeg.c.
Referenced by transcode_step().
reset_eagain()
static void reset_eagain (void) static
Definition at line 3930 of file ffmpeg.c.
Referenced by process_input(), and transcode_step().
duration_max()
static AVRational duration_max (int64_t tmp, int64_t * duration, AVRational tmp_time_base, AVRational time_base) static
Definition at line 3940 of file ffmpeg.c.
Referenced by seek_to_start().
seek_to_start()
static int seek_to_start (InputFile * ifile, AVFormatContext * is) static
Definition at line 3959 of file ffmpeg.c.
Referenced by process_input().
process_input()
static int process_input (int file_index) static
Definition at line 4027 of file ffmpeg.c.
Referenced by transcode_step().
transcode_from_filter()
static int transcode_from_filter (FilterGraph * graph, InputStream ** best_ist) static
Perform a step of transcoding for the specified filter graph.
Parameters
[in] graph filter graph to consider
[out] best_ist input stream where a frame would allow to continue
Returns
0 for success, <0 for error
Definition at line 4280 of file ffmpeg.c.
Referenced by transcode_step().
transcode_step()
static int transcode_step (void) static
Run a single step of transcoding.
Returns
0 for success, <0 for error
Definition at line 4326 of file ffmpeg.c.
Referenced by transcode().
transcode()
static int transcode (void) static
Definition at line 4369 of file ffmpeg.c.
Referenced by main().
log_callback_null()
static void log_callback_null (void * ptr, int level, const char * fmt, va_list vl) static
Definition at line 4549 of file ffmpeg.c.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 4555 of file ffmpeg.c.
Variable Documentation
program_name
const char program_name[] = "ffmpeg"
program name, defined by the program for show_version().
Definition at line 109 of file ffmpeg.c.
Referenced by main().
program_birth_year
const int program_birth_year = 2000
program birth year, defined by the program for show_banner()
Definition at line 110 of file ffmpeg.c.
vstats_file
FILE* vstats_file static
Definition at line 112 of file ffmpeg.c.
Referenced by do_video_stats(), and ffmpeg_cleanup().
forced_keyframes_const_names
const char* const forced_keyframes_const_names[]
Initial value:
= {
    "n",
    "n_forced",
    "prev_forced_n",
    "prev_forced_t",
    "t",
    NULL
}
Definition at line 117 of file ffmpeg.c.
Referenced by init_output_stream_encode().
run_as_daemon
int run_as_daemon = 0 static
Definition at line 130 of file ffmpeg.c.
Referenced by check_keyboard_interaction(), main(), and term_init().
nb_frames_dup
int nb_frames_dup = 0 static
Definition at line 131 of file ffmpeg.c.
Referenced by do_video_out(), main(), and print_report().
dup_warning
unsigned dup_warning = 1000 static
Definition at line 132 of file ffmpeg.c.
Referenced by do_video_out().
nb_frames_drop
int nb_frames_drop = 0 static
Definition at line 133 of file ffmpeg.c.
Referenced by do_video_out(), main(), and print_report().
decode_error_stat
int64_t decode_error_stat[2] static
Definition at line 134 of file ffmpeg.c.
Referenced by check_decode_result(), and main().
want_sdp
int want_sdp = 1 static
Definition at line 136 of file ffmpeg.c.
Referenced by check_init_output_file(), and main().
current_time
int current_time static
Definition at line 138 of file ffmpeg.c.
Referenced by main(), and update_benchmark().
progress_avio
AVIOContext* progress_avio = NULL
Definition at line 139 of file ffmpeg.c.
Referenced by opt_progress().
subtitle_out
uint8_t* subtitle_out static
Definition at line 141 of file ffmpeg.c.
Referenced by do_subtitle_out(), ffmpeg_cleanup(), and main().
input_streams
InputStream** input_streams = NULL
Definition at line 143 of file ffmpeg.c.
Referenced by add_input_streams(), cuvid_transcode_init(), init_input_filter(), new_audio_stream(), new_output_stream(), open_input_file(), open_output_file(), and qsv_transcode_init().
nb_input_streams
int nb_input_streams = 0
Definition at line 144 of file ffmpeg.c.
Referenced by add_input_streams(), check_keyboard_interaction(), ffmpeg_cleanup(), init_input_filter(), main(), open_input_file(), open_output_file(), transcode(), and transcode_init().
input_files
InputFile** input_files = NULL
Definition at line 145 of file ffmpeg.c.
Referenced by configure_input_audio_filter(), configure_input_video_filter(), init_input_filter(), open_input_file(), open_output_file(), opt_map(), opt_map_channel(), opt_target(), and sub2video_prepare().
nb_input_files
int nb_input_files = 0
Definition at line 146 of file ffmpeg.c.
Referenced by add_input_streams(), check_keyboard_interaction(), dump_attachment(), ffmpeg_cleanup(), get_input_packet(), init_input_filter(), main(), open_input_file(), open_output_file(), opt_map(), opt_map_channel(), opt_target(), print_final_stats(), reset_eagain(), and transcode_init().
output_streams
OutputStream** output_streams = NULL
Definition at line 148 of file ffmpeg.c.
Referenced by new_output_stream(), open_output_file(), and qsv_transcode_init().
nb_output_streams
int nb_output_streams = 0
Definition at line 149 of file ffmpeg.c.
Referenced by check_keyboard_interaction(), choose_output(), close_all_output_streams(), ffmpeg_cleanup(), flush_encoders(), got_eagain(), main(), need_output(), new_output_stream(), open_output_file(), print_final_stats(), print_report(), process_input(), process_input_packet(), qsv_transcode_init(), reap_filters(), reset_eagain(), transcode(), transcode_init(), and transcode_subtitles().
output_files
OutputFile** output_files = NULL
Definition at line 150 of file ffmpeg.c.
Referenced by configure_output_audio_filter(), configure_output_video_filter(), and open_output_file().
nb_output_files
int nb_output_files = 0
Definition at line 151 of file ffmpeg.c.
Referenced by ffmpeg_cleanup(), get_ost_filters(), main(), new_output_stream(), open_output_file(), print_final_stats(), print_sdp(), transcode(), and transcode_init().
filtergraphs
FilterGraph** filtergraphs
Definition at line 153 of file ffmpeg.c.
Referenced by configure_complex_filters(), DEF_CHOOSE_FORMAT(), init_complex_filters(), open_output_file(), opt_filter_complex(), and opt_filter_complex_script().
nb_filtergraphs
int nb_filtergraphs
Definition at line 154 of file ffmpeg.c.
Referenced by check_keyboard_interaction(), configure_complex_filters(), decode_audio(), decode_video(), DEF_CHOOSE_FORMAT(), ffmpeg_cleanup(), init_complex_filters(), main(), open_output_file(), opt_filter_complex(), opt_filter_complex_script(), and transcode_init().
received_sigterm
volatile int received_sigterm = 0 static
Definition at line 320 of file ffmpeg.c.
Referenced by ffmpeg_cleanup(), sigterm_handler(), and transcode().
received_nb_signals
volatile int received_nb_signals = 0 static
Definition at line 321 of file ffmpeg.c.
Referenced by check_keyboard_interaction(), decode_interrupt_cb(), main(), and sigterm_handler().
transcode_init_done
volatile int transcode_init_done = 0 static
Definition at line 322 of file ffmpeg.c.
Referenced by decode_interrupt_cb(), ffmpeg_cleanup(), and transcode_init().
ffmpeg_exited
volatile int ffmpeg_exited = 0 static
Definition at line 323 of file ffmpeg.c.
Referenced by ffmpeg_cleanup(), main(), and sigterm_handler().
main_return_code
int main_return_code = 0 static
Definition at line 324 of file ffmpeg.c.
Referenced by main(), and write_packet().
int_cb
const AVIOInterruptCB int_cb = { decode_interrupt_cb, NULL }
Definition at line 463 of file ffmpeg.c.
Referenced by check_init_output_file(), dump_attachment(), ffio_wfourcc(), get_preset_file_2(), open_input_file(), open_output_file(), opt_progress(), read_ffserver_streams(), and url_alloc_for_protocol().