FFmpeg: ffplay.c File Reference
ffplay.c File Reference
simple media player based on the FFmpeg libraries
#include "config.h"
#include <inttypes.h>
#include <math.h>
#include <limits.h>
#include <signal.h>
#include <stdint.h>
#include "libavutil/avstring.h"
#include "libavutil/eval.h"
#include "libavutil/mathematics.h"
#include "libavutil/pixdesc.h"
#include "libavutil/imgutils.h"
#include "libavutil/dict.h"
#include "libavutil/parseutils.h"
#include "libavutil/samplefmt.h"
#include "libavutil/avassert.h"
#include "libavutil/time.h"
#include "libavformat/avformat.h"
#include "libavdevice/avdevice.h"
#include "libswscale/swscale.h"
#include "libavutil/opt.h"
#include "libavcodec/avfft.h"
#include "libswresample/swresample.h"
#include <SDL.h>
#include <SDL_thread.h>
#include "cmdutils.h"
#include <assert.h>
#include "cmdutils_common_opts.h"
Data Structures
struct MyAVPacketList
struct PacketQueue
struct AudioParams
struct Clock
struct Frame
struct FrameQueue
struct Decoder
struct VideoState
Macros
#define MAX_QUEUE_SIZE (15 * 1024 * 1024)
#define MIN_FRAMES 25
#define EXTERNAL_CLOCK_MIN_FRAMES 2
#define EXTERNAL_CLOCK_MAX_FRAMES 10
#define SDL_AUDIO_MIN_BUFFER_SIZE 512
#define SDL_AUDIO_MAX_CALLBACKS_PER_SEC 30
#define SDL_VOLUME_STEP (SDL_MIX_MAXVOLUME / 50)
#define AV_SYNC_THRESHOLD_MIN 0.04
#define AV_SYNC_THRESHOLD_MAX 0.1
#define AV_SYNC_FRAMEDUP_THRESHOLD 0.1
#define AV_NOSYNC_THRESHOLD 10.0
#define SAMPLE_CORRECTION_PERCENT_MAX 10
#define EXTERNAL_CLOCK_SPEED_MIN 0.900
#define EXTERNAL_CLOCK_SPEED_MAX 1.010
#define EXTERNAL_CLOCK_SPEED_STEP 0.001
#define AUDIO_DIFF_AVG_NB 20
#define REFRESH_RATE 0.01
#define SAMPLE_ARRAY_SIZE (8 * 65536)
#define CURSOR_HIDE_DELAY 1000000
#define USE_ONEPASS_SUBTITLE_RENDER 1
#define VIDEO_PICTURE_QUEUE_SIZE 3
#define SUBPICTURE_QUEUE_SIZE 16
#define SAMPLE_QUEUE_SIZE 9
#define FRAME_QUEUE_SIZE FFMAX(SAMPLE_QUEUE_SIZE, FFMAX(VIDEO_PICTURE_QUEUE_SIZE, SUBPICTURE_QUEUE_SIZE))
#define FF_ALLOC_EVENT (SDL_USEREVENT)
#define FF_QUIT_EVENT (SDL_USEREVENT + 2)
Enumerations
enum { AV_SYNC_AUDIO_MASTER, AV_SYNC_VIDEO_MASTER, AV_SYNC_EXTERNAL_CLOCK }
Functions
static int cmp_audio_fmts (enum AVSampleFormat fmt1, int64_t channel_count1, enum AVSampleFormat fmt2, int64_t channel_count2)
static int64_t get_valid_channel_layout (int64_t channel_layout, int channels)
static void free_picture (Frame *vp)
static int packet_queue_put_private (PacketQueue *q, AVPacket *pkt)
static int packet_queue_put (PacketQueue *q, AVPacket *pkt)
static int packet_queue_put_nullpacket (PacketQueue *q, int stream_index)
static int packet_queue_init (PacketQueue *q)
static void packet_queue_flush (PacketQueue *q)
static void packet_queue_destroy (PacketQueue *q)
static void packet_queue_abort (PacketQueue *q)
static void packet_queue_start (PacketQueue *q)
static int packet_queue_get (PacketQueue *q, AVPacket *pkt, int block, int *serial)
static void decoder_init (Decoder *d, AVCodecContext *avctx, PacketQueue *queue, SDL_cond *empty_queue_cond)
static int decoder_decode_frame (Decoder *d, AVFrame *frame, AVSubtitle *sub)
static void decoder_destroy (Decoder *d)
static void frame_queue_unref_item (Frame *vp)
static int frame_queue_init (FrameQueue *f, PacketQueue *pktq, int max_size, int keep_last)
static void frame_queue_destory (FrameQueue *f)
static void frame_queue_signal (FrameQueue *f)
static Frame * frame_queue_peek (FrameQueue *f)
static Frame * frame_queue_peek_next (FrameQueue *f)
static Frame * frame_queue_peek_last (FrameQueue *f)
static Frame * frame_queue_peek_writable (FrameQueue *f)
static Frame * frame_queue_peek_readable (FrameQueue *f)
static void frame_queue_push (FrameQueue *f)
static void frame_queue_next (FrameQueue *f)
static int frame_queue_nb_remaining (FrameQueue *f)
static int64_t frame_queue_last_pos (FrameQueue *f)
static void decoder_abort (Decoder *d, FrameQueue *fq)
static void fill_rectangle (int x, int y, int w, int h)
static int realloc_texture (SDL_Texture **texture, Uint32 new_format, int new_width, int new_height, SDL_BlendMode blendmode, int init_texture)
static void calculate_display_rect (SDL_Rect *rect, int scr_xleft, int scr_ytop, int scr_width, int scr_height, int pic_width, int pic_height, AVRational pic_sar)
static int upload_texture (SDL_Texture *tex, AVFrame *frame, struct SwsContext **img_convert_ctx)
static void video_image_display (VideoState *is)
static int compute_mod (int a, int b)
static void video_audio_display (VideoState *s)
static void stream_component_close (VideoState *is, int stream_index)
static void stream_close (VideoState *is)
static void do_exit (VideoState *is)
static void sigterm_handler (int sig)
static void set_default_window_size (int width, int height, AVRational sar)
static int video_open (VideoState *is, Frame *vp)
static void video_display (VideoState *is)
static double get_clock (Clock *c)
static void set_clock_at (Clock *c, double pts, int serial, double time)
static void set_clock (Clock *c, double pts, int serial)
static void set_clock_speed (Clock *c, double speed)
static void init_clock (Clock *c, int *queue_serial)
static void sync_clock_to_slave (Clock *c, Clock *slave)
static int get_master_sync_type (VideoState *is)
static double get_master_clock (VideoState *is)
static void check_external_clock_speed (VideoState *is)
static void stream_seek (VideoState *is, int64_t pos, int64_t rel, int seek_by_bytes)
static void stream_toggle_pause (VideoState *is)
static void toggle_pause (VideoState *is)
static void toggle_mute (VideoState *is)
static void update_volume (VideoState *is, int sign, int step)
static void step_to_next_frame (VideoState *is)
static double compute_target_delay (double delay, VideoState *is)
static double vp_duration (VideoState *is, Frame *vp, Frame *nextvp)
static void update_video_pts (VideoState *is, double pts, int64_t pos, int serial)
static void video_refresh (void *opaque, double *remaining_time)
static void alloc_picture (VideoState *is)
static int queue_picture (VideoState *is, AVFrame *src_frame, double pts, double duration, int64_t pos, int serial)
static int get_video_frame (VideoState *is, AVFrame *frame)
static int audio_thread (void *arg)
static int decoder_start (Decoder *d, int(*fn)(void *), void *arg)
static int video_thread (void *arg)
static int subtitle_thread (void *arg)
static void update_sample_display (VideoState *is, short *samples, int samples_size)
static int synchronize_audio (VideoState *is, int nb_samples)
static int audio_decode_frame (VideoState *is)
Decode one audio frame and return its uncompressed size.
static void sdl_audio_callback (void *opaque, Uint8 *stream, int len)
static int audio_open (void *opaque, int64_t wanted_channel_layout, int wanted_nb_channels, int wanted_sample_rate, struct AudioParams *audio_hw_params)
static int stream_component_open (VideoState *is, int stream_index)
static int decode_interrupt_cb (void *ctx)
static int stream_has_enough_packets (AVStream *st, int stream_id, PacketQueue *queue)
static int is_realtime (AVFormatContext *s)
static int read_thread (void *arg)
static VideoState * stream_open (const char *filename, AVInputFormat *iformat)
static void stream_cycle_channel (VideoState *is, int codec_type)
static void toggle_full_screen (VideoState *is)
static void toggle_audio_display (VideoState *is)
static void refresh_loop_wait_event (VideoState *is, SDL_Event *event)
static void seek_chapter (VideoState *is, int incr)
static void event_loop (VideoState *cur_stream)
static int opt_frame_size (void *optctx, const char *opt, const char *arg)
static int opt_width (void *optctx, const char *opt, const char *arg)
static int opt_height (void *optctx, const char *opt, const char *arg)
static int opt_format (void *optctx, const char *opt, const char *arg)
static int opt_frame_pix_fmt (void *optctx, const char *opt, const char *arg)
static int opt_sync (void *optctx, const char *opt, const char *arg)
static int opt_seek (void *optctx, const char *opt, const char *arg)
static int opt_duration (void *optctx, const char *opt, const char *arg)
static int opt_show_mode (void *optctx, const char *opt, const char *arg)
static void opt_input_file (void *optctx, const char *filename)
static int opt_codec (void *optctx, const char *opt, const char *arg)
static void show_usage (void)
void show_help_default (const char *opt, const char *arg)
Per-fftool specific help handler.
static int lockmgr (void **mtx, enum AVLockOp op)
int main (int argc, char **argv)
Variables
const char program_name [] = "ffplay"
program name, defined by the program for show_version().
const int program_birth_year = 2003
program birth year, defined by the program for show_banner()
static unsigned sws_flags = SWS_BICUBIC
static AVInputFormat * file_iformat
static const char * input_filename
static const char * window_title
static int default_width = 640
static int default_height = 480
static int screen_width = 0
static int screen_height = 0
static int audio_disable
static int video_disable
static int subtitle_disable
static const char * wanted_stream_spec [AVMEDIA_TYPE_NB] = {0}
static int seek_by_bytes = -1
static int display_disable
static int startup_volume = 100
static int show_status = 1
static int av_sync_type = AV_SYNC_AUDIO_MASTER
static int64_t start_time = AV_NOPTS_VALUE
static int64_t duration = AV_NOPTS_VALUE
static int fast = 0
static int genpts = 0
static int lowres = 0
static int decoder_reorder_pts = -1
static int autoexit
static int exit_on_keydown
static int exit_on_mousedown
static int loop = 1
static int framedrop = -1
static int infinite_buffer = -1
static enum ShowMode show_mode = SHOW_MODE_NONE
static const char * audio_codec_name
static const char * subtitle_codec_name
static const char * video_codec_name
double rdftspeed = 0.02
static int64_t cursor_last_shown
static int cursor_hidden = 0
static int autorotate = 1
static int is_full_screen
static int64_t audio_callback_time
static AVPacket flush_pkt
static SDL_Window * window
static SDL_Renderer * renderer
static int dummy
static const OptionDef options []
Detailed Description
simple media player based on the FFmpeg libraries
Definition in file ffplay.c.
Macro Definition Documentation
MAX_QUEUE_SIZE
#define MAX_QUEUE_SIZE (15 * 1024 * 1024)
Definition at line 66 of file ffplay.c.
Referenced by read_thread().
MIN_FRAMES
#define MIN_FRAMES 25
Definition at line 67 of file ffplay.c.
Referenced by stream_has_enough_packets().
EXTERNAL_CLOCK_MIN_FRAMES
#define EXTERNAL_CLOCK_MIN_FRAMES 2
Definition at line 68 of file ffplay.c.
Referenced by check_external_clock_speed().
EXTERNAL_CLOCK_MAX_FRAMES
#define EXTERNAL_CLOCK_MAX_FRAMES 10
Definition at line 69 of file ffplay.c.
Referenced by check_external_clock_speed().
SDL_AUDIO_MIN_BUFFER_SIZE
#define SDL_AUDIO_MIN_BUFFER_SIZE 512
Definition at line 72 of file ffplay.c.
Referenced by audio_open(), and sdl_audio_callback().
SDL_AUDIO_MAX_CALLBACKS_PER_SEC
#define SDL_AUDIO_MAX_CALLBACKS_PER_SEC 30
Definition at line 74 of file ffplay.c.
Referenced by audio_open().
SDL_VOLUME_STEP
#define SDL_VOLUME_STEP (SDL_MIX_MAXVOLUME / 50)
Definition at line 77 of file ffplay.c.
Referenced by event_loop().
AV_SYNC_THRESHOLD_MIN
#define AV_SYNC_THRESHOLD_MIN 0.04
Definition at line 80 of file ffplay.c.
Referenced by compute_target_delay().
AV_SYNC_THRESHOLD_MAX
#define AV_SYNC_THRESHOLD_MAX 0.1
Definition at line 82 of file ffplay.c.
Referenced by compute_target_delay(), and video_refresh().
AV_SYNC_FRAMEDUP_THRESHOLD
#define AV_SYNC_FRAMEDUP_THRESHOLD 0.1
Definition at line 84 of file ffplay.c.
Referenced by compute_target_delay().
AV_NOSYNC_THRESHOLD
#define AV_NOSYNC_THRESHOLD 10.0
Definition at line 86 of file ffplay.c.
Referenced by get_video_frame(), sync_clock_to_slave(), synchronize_audio(), and video_thread().
SAMPLE_CORRECTION_PERCENT_MAX
#define SAMPLE_CORRECTION_PERCENT_MAX 10
Definition at line 89 of file ffplay.c.
Referenced by synchronize_audio().
EXTERNAL_CLOCK_SPEED_MIN
#define EXTERNAL_CLOCK_SPEED_MIN 0.900
Definition at line 92 of file ffplay.c.
Referenced by check_external_clock_speed().
EXTERNAL_CLOCK_SPEED_MAX
#define EXTERNAL_CLOCK_SPEED_MAX 1.010
Definition at line 93 of file ffplay.c.
Referenced by check_external_clock_speed().
EXTERNAL_CLOCK_SPEED_STEP
#define EXTERNAL_CLOCK_SPEED_STEP 0.001
Definition at line 94 of file ffplay.c.
Referenced by check_external_clock_speed().
AUDIO_DIFF_AVG_NB
#define AUDIO_DIFF_AVG_NB 20
Definition at line 97 of file ffplay.c.
Referenced by stream_component_open(), and synchronize_audio().
REFRESH_RATE
#define REFRESH_RATE 0.01
Definition at line 100 of file ffplay.c.
Referenced by refresh_loop_wait_event().
SAMPLE_ARRAY_SIZE
#define SAMPLE_ARRAY_SIZE (8 * 65536)
Definition at line 104 of file ffplay.c.
Referenced by update_sample_display(), and video_audio_display().
CURSOR_HIDE_DELAY
#define CURSOR_HIDE_DELAY 1000000
Definition at line 106 of file ffplay.c.
Referenced by refresh_loop_wait_event().
USE_ONEPASS_SUBTITLE_RENDER
#define USE_ONEPASS_SUBTITLE_RENDER 1
Definition at line 108 of file ffplay.c.
VIDEO_PICTURE_QUEUE_SIZE
#define VIDEO_PICTURE_QUEUE_SIZE 3
Definition at line 129 of file ffplay.c.
Referenced by stream_open().
SUBPICTURE_QUEUE_SIZE
#define SUBPICTURE_QUEUE_SIZE 16
Definition at line 130 of file ffplay.c.
Referenced by stream_open().
SAMPLE_QUEUE_SIZE
#define SAMPLE_QUEUE_SIZE 9
Definition at line 131 of file ffplay.c.
Referenced by stream_open().
FRAME_QUEUE_SIZE
#define FRAME_QUEUE_SIZE FFMAX(SAMPLE_QUEUE_SIZE, FFMAX(VIDEO_PICTURE_QUEUE_SIZE, SUBPICTURE_QUEUE_SIZE))
Definition at line 132 of file ffplay.c.
Referenced by frame_queue_init().
FF_ALLOC_EVENT
#define FF_ALLOC_EVENT (SDL_USEREVENT)
Definition at line 360 of file ffplay.c.
Referenced by event_loop(), and queue_picture().
FF_QUIT_EVENT
#define FF_QUIT_EVENT (SDL_USEREVENT + 2)
Definition at line 361 of file ffplay.c.
Referenced by event_loop(), read_thread(), and video_thread().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
AV_SYNC_AUDIO_MASTER
AV_SYNC_VIDEO_MASTER
AV_SYNC_EXTERNAL_CLOCK
Definition at line 184 of file ffplay.c.
Function Documentation
cmp_audio_fmts()
static int cmp_audio_fmts (enum AVSampleFormat fmt1, int64_t channel_count1, enum AVSampleFormat fmt2, int64_t channel_count2) inline static
Definition at line 376 of file ffplay.c.
Referenced by audio_thread().
get_valid_channel_layout()
static int64_t get_valid_channel_layout (int64_t channel_layout, int channels) inline static
Definition at line 387 of file ffplay.c.
Referenced by audio_thread(), and stream_component_open().
free_picture()
static void free_picture (Frame * vp) static
Definition at line 801 of file ffplay.c.
Referenced by frame_queue_destory(), and get_valid_channel_layout().
packet_queue_put_private()
static int packet_queue_put_private (PacketQueue * q, AVPacket * pkt) static
Definition at line 397 of file ffplay.c.
Referenced by packet_queue_put(), and packet_queue_start().
packet_queue_put()
static int packet_queue_put (PacketQueue * q, AVPacket * pkt) static
Definition at line 426 of file ffplay.c.
Referenced by packet_queue_put_nullpacket(), and read_thread().
packet_queue_put_nullpacket()
static int packet_queue_put_nullpacket (PacketQueue * q, int stream_index) static
Definition at line 440 of file ffplay.c.
Referenced by read_thread().
packet_queue_init()
static int packet_queue_init (PacketQueue * q) static
Definition at line 451 of file ffplay.c.
Referenced by stream_open().
packet_queue_flush()
static void packet_queue_flush (PacketQueue * q) static
Definition at line 468 of file ffplay.c.
Referenced by decoder_abort(), packet_queue_destroy(), and read_thread().
packet_queue_destroy()
static void packet_queue_destroy (PacketQueue * q) static
Definition at line 486 of file ffplay.c.
Referenced by stream_close().
packet_queue_abort()
static void packet_queue_abort (PacketQueue * q) static
Definition at line 493 of file ffplay.c.
Referenced by decoder_abort().
packet_queue_start()
static void packet_queue_start (PacketQueue * q) static
Definition at line 504 of file ffplay.c.
Referenced by decoder_start().
packet_queue_get()
static int packet_queue_get (PacketQueue * q, AVPacket * pkt, int block, int * serial) static
Definition at line 513 of file ffplay.c.
Referenced by decoder_decode_frame().
decoder_init()
static void decoder_init (Decoder * d, AVCodecContext * avctx, PacketQueue * queue, SDL_cond * empty_queue_cond) static
Definition at line 551 of file ffplay.c.
Referenced by stream_component_open().
decoder_decode_frame()
static int decoder_decode_frame (Decoder * d, AVFrame * frame, AVSubtitle * sub) static
Definition at line 559 of file ffplay.c.
Referenced by audio_thread(), get_video_frame(), and subtitle_thread().
decoder_destroy()
static void decoder_destroy (Decoder * d) static
Definition at line 641 of file ffplay.c.
Referenced by stream_component_close().
frame_queue_unref_item()
static void frame_queue_unref_item (Frame * vp) static
Definition at line 646 of file ffplay.c.
Referenced by frame_queue_destory(), and frame_queue_next().
frame_queue_init()
static int frame_queue_init (FrameQueue * f, PacketQueue * pktq, int max_size, int keep_last) static
Definition at line 652 of file ffplay.c.
Referenced by stream_open().
frame_queue_destory()
static void frame_queue_destory (FrameQueue * f) static
Definition at line 673 of file ffplay.c.
Referenced by stream_close().
frame_queue_signal()
static void frame_queue_signal (FrameQueue * f) static
Definition at line 686 of file ffplay.c.
Referenced by decoder_abort().
frame_queue_peek()
static Frame* frame_queue_peek (FrameQueue * f) static
Definition at line 693 of file ffplay.c.
Referenced by video_image_display(), and video_refresh().
frame_queue_peek_next()
static Frame* frame_queue_peek_next (FrameQueue * f) static
Definition at line 698 of file ffplay.c.
Referenced by video_refresh().
frame_queue_peek_last()
static Frame* frame_queue_peek_last (FrameQueue * f) static
Definition at line 703 of file ffplay.c.
Referenced by video_image_display(), and video_refresh().
frame_queue_peek_writable()
static Frame* frame_queue_peek_writable (FrameQueue * f) static
Definition at line 708 of file ffplay.c.
Referenced by audio_thread(), queue_picture(), and subtitle_thread().
frame_queue_peek_readable()
static Frame* frame_queue_peek_readable (FrameQueue * f) static
Definition at line 724 of file ffplay.c.
Referenced by audio_decode_frame().
frame_queue_push()
static void frame_queue_push (FrameQueue * f) static
Definition at line 740 of file ffplay.c.
Referenced by audio_thread(), queue_picture(), and subtitle_thread().
frame_queue_next()
static void frame_queue_next (FrameQueue * f) static
Definition at line 750 of file ffplay.c.
Referenced by audio_decode_frame(), and video_refresh().
frame_queue_nb_remaining()
static int frame_queue_nb_remaining (FrameQueue * f) static
Definition at line 766 of file ffplay.c.
Referenced by audio_decode_frame(), read_thread(), video_image_display(), and video_refresh().
frame_queue_last_pos()
static int64_t frame_queue_last_pos (FrameQueue * f) static
Definition at line 772 of file ffplay.c.
Referenced by event_loop().
decoder_abort()
static void decoder_abort (Decoder * d, FrameQueue * fq) static
Definition at line 781 of file ffplay.c.
Referenced by stream_component_close().
fill_rectangle()
static void fill_rectangle (int x, int y, int w, int h) inline static
Definition at line 790 of file ffplay.c.
Referenced by decode_cabac_luma_residual(), decode_cabac_residual_internal(), decode_cabac_residual_nondc(), decode_luma_residual(), ff_h264_decode_mb_cabac(), ff_h264_decode_mb_cavlc(), fill_decode_caches(), fill_filter_caches_inter(), h264_er_decode_mb(), hl_decode_mb(), hl_decode_mb_444(), pred_pskip_motion(), pred_spatial_direct_motion(), pred_temp_direct_motion(), rv34_decode_inter_macroblock(), rv34_decode_inter_mb_header(), rv34_decode_intra_macroblock(), rv34_decode_intra_mb_header(), rv34_output_intra(), svq3_mc_dir(), video_audio_display(), write_back_motion(), and ZERO8x2().
realloc_texture()
static int realloc_texture (SDL_Texture ** texture, Uint32 new_format, int new_width, int new_height, SDL_BlendMode blendmode, int init_texture) static
Definition at line 809 of file ffplay.c.
Referenced by alloc_picture(), video_audio_display(), and video_image_display().
calculate_display_rect()
static void calculate_display_rect (SDL_Rect * rect, int scr_xleft, int scr_ytop, int scr_width, int scr_height, int pic_width, int pic_height, AVRational pic_sar) static
Definition at line 831 of file ffplay.c.
Referenced by set_default_window_size(), and video_image_display().
upload_texture()
static int upload_texture (SDL_Texture * tex, AVFrame * frame, struct SwsContext ** img_convert_ctx) static
Definition at line 862 of file ffplay.c.
Referenced by video_image_display().
video_image_display()
static void video_image_display (VideoState * is) static
Definition at line 903 of file ffplay.c.
Referenced by video_display().
compute_mod()
static int compute_mod (int a, int b) inline static
Definition at line 986 of file ffplay.c.
Referenced by video_audio_display().
video_audio_display()
static void video_audio_display (VideoState * s) static
Definition at line 991 of file ffplay.c.
Referenced by video_display().
stream_component_close()
static void stream_component_close (VideoState * is, int stream_index) static
Definition at line 1133 of file ffplay.c.
Referenced by stream_close(), and stream_cycle_channel().
stream_close()
static void stream_close (VideoState * is) static
Definition at line 1190 of file ffplay.c.
Referenced by do_exit(), and stream_open().
do_exit()
static void do_exit (VideoState * is) static
Definition at line 1225 of file ffplay.c.
Referenced by alloc_picture(), event_loop(), main(), and video_open().
sigterm_handler()
static void sigterm_handler (int sig) static
Definition at line 1247 of file ffplay.c.
Referenced by main().
set_default_window_size()
static void set_default_window_size (int width, int height, AVRational sar) static
Definition at line 1252 of file ffplay.c.
Referenced by read_thread(), and video_open().
video_open()
static int video_open (VideoState * is, Frame * vp) static
Definition at line 1260 of file ffplay.c.
Referenced by alloc_picture(), and video_display().
video_display()
static void video_display (VideoState * is) static
Definition at line 1311 of file ffplay.c.
Referenced by video_refresh().
get_clock()
static double get_clock (Clock * c) static
Definition at line 1325 of file ffplay.c.
Referenced by compute_target_delay(), get_master_clock(), set_clock_speed(), stream_toggle_pause(), sync_clock_to_slave(), synchronize_audio(), and video_refresh().
set_clock_at()
static void set_clock_at (Clock * c, double pts, int serial, double time) static
Definition at line 1337 of file ffplay.c.
Referenced by sdl_audio_callback(), and set_clock().
set_clock()
static void set_clock (Clock * c, double pts, int serial) static
Definition at line 1345 of file ffplay.c.
Referenced by init_clock(), read_thread(), set_clock_speed(), stream_toggle_pause(), sync_clock_to_slave(), and update_video_pts().
set_clock_speed()
static void set_clock_speed (Clock * c, double speed) static
Definition at line 1351 of file ffplay.c.
Referenced by check_external_clock_speed().
init_clock()
static void init_clock (Clock * c, int * queue_serial) static
Definition at line 1357 of file ffplay.c.
Referenced by stream_open().
sync_clock_to_slave()
static void sync_clock_to_slave (Clock * c, Clock * slave) static
Definition at line 1365 of file ffplay.c.
Referenced by sdl_audio_callback(), and update_video_pts().
get_master_sync_type()
static int get_master_sync_type (VideoState * is) static
Definition at line 1373 of file ffplay.c.
Referenced by compute_target_delay(), get_master_clock(), get_video_frame(), synchronize_audio(), and video_refresh().
get_master_clock()
static double get_master_clock (VideoState * is) static
Definition at line 1390 of file ffplay.c.
Referenced by compute_target_delay(), event_loop(), get_video_frame(), seek_chapter(), synchronize_audio(), and video_refresh().
check_external_clock_speed()
static void check_external_clock_speed (VideoState * is) static
Definition at line 1408 of file ffplay.c.
Referenced by video_refresh().
stream_seek()
static void stream_seek (VideoState * is, int64_t pos, int64_t rel, int seek_by_bytes) static
Definition at line 1423 of file ffplay.c.
Referenced by event_loop(), info_callback(), libopenjpeg_decode_frame(), libopenjpeg_encode_frame(), read_thread(), and seek_chapter().
stream_toggle_pause()
static void stream_toggle_pause (VideoState * is) static
Definition at line 1437 of file ffplay.c.
Referenced by step_to_next_frame(), toggle_pause(), and video_refresh().
toggle_pause()
static void toggle_pause (VideoState * is) static
Definition at line 1450 of file ffplay.c.
Referenced by event_loop().
toggle_mute()
static void toggle_mute (VideoState * is) static
Definition at line 1456 of file ffplay.c.
Referenced by event_loop().
update_volume()
static void update_volume (VideoState * is, int sign, int step) static
Definition at line 1461 of file ffplay.c.
Referenced by event_loop().
step_to_next_frame()
static void step_to_next_frame (VideoState * is) static
Definition at line 1466 of file ffplay.c.
Referenced by event_loop(), and read_thread().
compute_target_delay()
static double compute_target_delay (double delay, VideoState * is) static
Definition at line 1474 of file ffplay.c.
Referenced by video_refresh().
vp_duration()
static double vp_duration (VideoState * is, Frame * vp, Frame * nextvp) static
Definition at line 1504 of file ffplay.c.
Referenced by video_refresh().
update_video_pts()
static void update_video_pts (VideoState * is, double pts, int64_t pos, int serial) static
Definition at line 1516 of file ffplay.c.
Referenced by video_refresh().
video_refresh()
static void video_refresh (void * opaque, double * remaining_time) static
Definition at line 1523 of file ffplay.c.
Referenced by refresh_loop_wait_event().
alloc_picture()
static void alloc_picture (VideoState * is) static
Definition at line 1683 of file ffplay.c.
Referenced by event_loop().
queue_picture()
static int queue_picture (VideoState * is, AVFrame * src_frame, double pts, double duration, int64_t pos, int serial) static
Definition at line 1713 of file ffplay.c.
Referenced by video_thread().
get_video_frame()
static int get_video_frame (VideoState * is, AVFrame * frame) static
Definition at line 1776 of file ffplay.c.
Referenced by video_thread().
audio_thread()
static int audio_thread (void * arg) static
Definition at line 2022 of file ffplay.c.
Referenced by stream_component_open().
decoder_start()
static int decoder_start (Decoder * d, int(*)(void *) fn, void * arg) static
Definition at line 2109 of file ffplay.c.
Referenced by stream_component_open().
video_thread()
static int video_thread (void * arg) static
Definition at line 2120 of file ffplay.c.
Referenced by stream_component_open().
subtitle_thread()
static int subtitle_thread (void * arg) static
Definition at line 2229 of file ffplay.c.
Referenced by stream_component_open().
update_sample_display()
static void update_sample_display (VideoState * is, short * samples, int samples_size) static
Definition at line 2264 of file ffplay.c.
Referenced by sdl_audio_callback().
synchronize_audio()
static int synchronize_audio (VideoState * is, int nb_samples) static
Definition at line 2284 of file ffplay.c.
Referenced by audio_decode_frame().
audio_decode_frame()
static int audio_decode_frame (VideoState * is) static
Decode one audio frame and return its uncompressed size.
The processed audio frame is decoded, converted if required, and stored in is->audio_buf, with size in bytes given by the return value.
Definition at line 2332 of file ffplay.c.
Referenced by sdl_audio_callback().
sdl_audio_callback()
static void sdl_audio_callback (void * opaque, Uint8 * stream, int len) static
Definition at line 2445 of file ffplay.c.
Referenced by audio_open().
audio_open()
static int audio_open (void * opaque, int64_t wanted_channel_layout, int wanted_nb_channels, int wanted_sample_rate, struct AudioParams * audio_hw_params) static
Definition at line 2488 of file ffplay.c.
Referenced by stream_component_open().
stream_component_open()
static int stream_component_open (VideoState * is, int stream_index) static
Definition at line 2562 of file ffplay.c.
Referenced by read_thread(), and stream_cycle_channel().
decode_interrupt_cb()
static int decode_interrupt_cb (void * ctx) static
Definition at line 2721 of file ffplay.c.
Referenced by read_thread().
stream_has_enough_packets()
static int stream_has_enough_packets (AVStream * st, int stream_id, PacketQueue * queue) static
Definition at line 2727 of file ffplay.c.
Referenced by read_thread().
is_realtime()
static int is_realtime (AVFormatContext * s) static
Definition at line 2734 of file ffplay.c.
Referenced by read_thread().
read_thread()
static int read_thread (void * arg) static
Definition at line 2751 of file ffplay.c.
Referenced by stream_open().
stream_open()
static VideoState* stream_open (const char * filename, AVInputFormat * iformat) static
Definition at line 3073 of file ffplay.c.
Referenced by main().
stream_cycle_channel()
static void stream_cycle_channel (VideoState * is, int codec_type) static
Definition at line 3128 of file ffplay.c.
Referenced by event_loop().
toggle_full_screen()
static void toggle_full_screen (VideoState * is) static
Definition at line 3207 of file ffplay.c.
Referenced by event_loop().
toggle_audio_display()
static void toggle_audio_display (VideoState * is) static
Definition at line 3213 of file ffplay.c.
Referenced by event_loop().
refresh_loop_wait_event()
static void refresh_loop_wait_event (VideoState * is, SDL_Event * event) static
Definition at line 3225 of file ffplay.c.
Referenced by event_loop().
seek_chapter()
static void seek_chapter (VideoState * is, int incr) static
Definition at line 3242 of file ffplay.c.
Referenced by event_loop().
event_loop()
static void event_loop (VideoState * cur_stream) static
Definition at line 3270 of file ffplay.c.
Referenced by main().
opt_frame_size()
static int opt_frame_size (void * optctx, const char * opt, const char * arg) static
Definition at line 3473 of file ffplay.c.
opt_width()
static int opt_width (void * optctx, const char * opt, const char * arg) static
Definition at line 3479 of file ffplay.c.
opt_height()
static int opt_height (void * optctx, const char * opt, const char * arg) static
Definition at line 3485 of file ffplay.c.
opt_format()
static int opt_format (void * optctx, const char * opt, const char * arg) static
Definition at line 3491 of file ffplay.c.
opt_frame_pix_fmt()
static int opt_frame_pix_fmt (void * optctx, const char * opt, const char * arg) static
Definition at line 3501 of file ffplay.c.
opt_sync()
static int opt_sync (void * optctx, const char * opt, const char * arg) static
Definition at line 3507 of file ffplay.c.
opt_seek()
static int opt_seek (void * optctx, const char * opt, const char * arg) static
Definition at line 3522 of file ffplay.c.
opt_duration()
static int opt_duration (void * optctx, const char * opt, const char * arg) static
Definition at line 3528 of file ffplay.c.
opt_show_mode()
static int opt_show_mode (void * optctx, const char * opt, const char * arg) static
Definition at line 3534 of file ffplay.c.
opt_input_file()
static void opt_input_file (void * optctx, const char * filename) static
Definition at line 3543 of file ffplay.c.
Referenced by main().
opt_codec()
static int opt_codec (void * optctx, const char * opt, const char * arg) static
Definition at line 3556 of file ffplay.c.
show_usage()
static void show_usage (void) static
Definition at line 3628 of file ffplay.c.
Referenced by main(), and show_help_default().
show_help_default()
void show_help_default (const char * opt, const char * arg)
Per-fftool specific help handler.
Implemented in each fftool, called by show_help().
Definition at line 3635 of file ffplay.c.
lockmgr()
static int lockmgr (void ** mtx, enum AVLockOp op) static
Definition at line 3670 of file ffplay.c.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 3692 of file ffplay.c.
Variable Documentation
program_name
const char program_name[] = "ffplay"
program name, defined by the program for show_version().
Definition at line 63 of file ffplay.c.
Referenced by main(), and show_usage().
program_birth_year
const int program_birth_year = 2003
program birth year, defined by the program for show_banner()
Definition at line 64 of file ffplay.c.
sws_flags
unsigned sws_flags = SWS_BICUBIC static
Definition at line 110 of file ffplay.c.
Referenced by upload_texture().
file_iformat
AVInputFormat* file_iformat static
Definition at line 312 of file ffplay.c.
Referenced by open_input_file().
input_filename
const char* input_filename static
Examples:
avio_reading.c.
Definition at line 313 of file ffplay.c.
Referenced by main(), open_input_stream(), opt_input_file(), read_thread(), and video_open().
window_title
const char* window_title static
Definition at line 314 of file ffplay.c.
Referenced by read_thread(), and video_open().
default_width
int default_width = 640 static
Definition at line 315 of file ffplay.c.
Referenced by set_default_window_size(), and video_open().
default_height
int default_height = 480 static
Definition at line 316 of file ffplay.c.
Referenced by set_default_window_size(), and video_open().
screen_width
int screen_width = 0 static
Definition at line 317 of file ffplay.c.
Referenced by event_loop(), opt_width(), and video_open().
screen_height
int screen_height = 0 static
Definition at line 318 of file ffplay.c.
Referenced by event_loop(), opt_height(), and video_open().
audio_disable
int audio_disable static
Definition at line 319 of file ffplay.c.
Referenced by main(), open_output_file(), and read_thread().
video_disable
int video_disable static
Definition at line 320 of file ffplay.c.
Referenced by main(), open_output_file(), and read_thread().
subtitle_disable
int subtitle_disable static
Definition at line 321 of file ffplay.c.
Referenced by read_thread().
wanted_stream_spec
const char* wanted_stream_spec[AVMEDIA_TYPE_NB] = {0} static
Definition at line 322 of file ffplay.c.
Referenced by read_thread().
seek_by_bytes
int seek_by_bytes = -1 static
Definition at line 323 of file ffplay.c.
Referenced by event_loop(), and read_thread().
display_disable
int display_disable static
Definition at line 324 of file ffplay.c.
Referenced by main(), and video_refresh().
startup_volume
int startup_volume = 100 static
Definition at line 325 of file ffplay.c.
Referenced by stream_open().
show_status
int show_status = 1 static
Definition at line 326 of file ffplay.c.
Referenced by do_exit(), read_thread(), and video_refresh().
av_sync_type
int av_sync_type = AV_SYNC_AUDIO_MASTER static
Definition at line 327 of file ffplay.c.
Referenced by opt_sync(), and stream_open().
start_time
int64_t start_time = AV_NOPTS_VALUE static
Definition at line 328 of file ffplay.c.
Referenced by asf_read_ext_stream_properties(), asf_read_stream_properties(), config_output(), copy_chapters(), decode(), do_streamcopy(), get_concatdec_select(), gxf_seek(), libAVFilter_Run(), main(), mov_build_index(), open_output_file(), opt_seek(), read_thread(), real_seek(), reap_filters(), rm_read_header(), skeleton_header(), update_stream_timings(), and write_manifest().
duration
int64_t duration = AV_NOPTS_VALUE static
Definition at line 329 of file ffplay.c.
Referenced by opt_duration(), queue_picture(), read_thread(), video_refresh(), video_thread(), and vp_duration().
fast
int fast = 0 static
Definition at line 330 of file ffplay.c.
Referenced by stream_component_open().
genpts
int genpts = 0 static
Definition at line 331 of file ffplay.c.
Referenced by av_read_frame(), and read_thread().
lowres
int lowres = 0 static
Definition at line 332 of file ffplay.c.
Referenced by chroma_4mv_motion_lowres(), ff_get_format(), hpel_motion_lowres(), mpeg_decode_slice(), mpeg_motion_lowres(), MPV_motion_lowres(), and stream_component_open().
decoder_reorder_pts
int decoder_reorder_pts = -1 static
Definition at line 333 of file ffplay.c.
Referenced by decoder_decode_frame().
autoexit
int autoexit static
Definition at line 334 of file ffplay.c.
Referenced by read_thread().
exit_on_keydown
int exit_on_keydown static
Definition at line 335 of file ffplay.c.
Referenced by event_loop().
exit_on_mousedown
int exit_on_mousedown static
Definition at line 336 of file ffplay.c.
Referenced by event_loop().
loop
int loop = 1 static
Definition at line 337 of file ffplay.c.
Referenced by avfilter_register_all(), hevc_idct_dc_16x16_msa(), hevc_idct_dc_32x32_msa(), img_read_seek(), process_input(), read_header(), and read_thread().
framedrop
int framedrop = -1 static
Definition at line 338 of file ffplay.c.
Referenced by get_video_frame(), and video_refresh().
infinite_buffer
int infinite_buffer = -1 static
Definition at line 339 of file ffplay.c.
Referenced by read_thread().
show_mode
enum ShowMode show_mode = SHOW_MODE_NONE static
Definition at line 340 of file ffplay.c.
Referenced by opt_show_mode(), and read_thread().
audio_codec_name
const char* audio_codec_name static
Definition at line 341 of file ffplay.c.
Referenced by compute_status(), open_input_file(), opt_codec(), and stream_component_open().
subtitle_codec_name
const char* subtitle_codec_name static
Definition at line 342 of file ffplay.c.
Referenced by open_input_file(), open_output_file(), opt_codec(), and stream_component_open().
video_codec_name
const char* video_codec_name static
Definition at line 343 of file ffplay.c.
Referenced by compute_status(), open_input_file(), opt_codec(), and stream_component_open().
rdftspeed
double rdftspeed = 0.02
Definition at line 344 of file ffplay.c.
Referenced by video_refresh().
cursor_last_shown
int64_t cursor_last_shown static
Definition at line 345 of file ffplay.c.
Referenced by event_loop(), and refresh_loop_wait_event().
cursor_hidden
int cursor_hidden = 0 static
Definition at line 346 of file ffplay.c.
Referenced by event_loop(), and refresh_loop_wait_event().
autorotate
int autorotate = 1 static
Definition at line 352 of file ffplay.c.
Referenced by add_input_streams(), and get_video_frame().
is_full_screen
int is_full_screen static
Definition at line 355 of file ffplay.c.
Referenced by toggle_full_screen(), and video_open().
audio_callback_time
int64_t audio_callback_time static
Definition at line 356 of file ffplay.c.
Referenced by audio_decode_frame(), sdl_audio_callback(), and video_audio_display().
flush_pkt
AVPacket flush_pkt static
Definition at line 358 of file ffplay.c.
Referenced by parse_packet().
window
SDL_Window* window static
Definition at line 363 of file ffplay.c.
Referenced by checkasm_check_synth_filter(), do_exit(), ff_ac3_float_mdct_init(), ff_mpa_synth_filter(), ff_mpadsp_apply_window(), ff_sine_window_init(), hdcd_integrate(), imdct_and_windowing_eld(), toggle_full_screen(), video_display(), video_open(), wmapro_window(), yae_reset(), and yae_xcorr_via_rdft().
renderer
SDL_Renderer* renderer static
Definition at line 364 of file ffplay.c.
Referenced by do_exit(), fill_rectangle(), realloc_texture(), video_audio_display(), video_display(), video_image_display(), and video_open().
dummy
int dummy static
Definition at line 3578 of file ffplay.c.
options
const OptionDef options[] static
Definition at line 3580 of file ffplay.c.