FFmpeg: ffprobe.c File Reference
ffprobe.c File Reference
simple media prober based on the FFmpeg libraries
#include "config.h"
#include "libavutil/ffversion.h"
#include <string.h>
#include "libavformat/avformat.h"
#include "libavcodec/avcodec.h"
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/bprint.h"
#include "libavutil/display.h"
#include "libavutil/hash.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "libavutil/spherical.h"
#include "libavutil/stereo3d.h"
#include "libavutil/dict.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/libm.h"
#include "libavutil/parseutils.h"
#include "libavutil/timecode.h"
#include "libavutil/timestamp.h"
#include "libavdevice/avdevice.h"
#include "libswscale/swscale.h"
#include "libswresample/swresample.h"
#include "libpostproc/postprocess.h"
#include "cmdutils.h"
#include "cmdutils_common_opts.h"
Data Structures
struct InputStream
struct InputFile
struct ReadInterval
struct section
struct unit_value
struct Writer
struct WriterContext
struct DefaultContext
struct CompactContext
struct FlatContext
struct INIContext
struct JSONContext
struct XMLContext
Macros
#define SECTION_MAX_NB_CHILDREN 10
#define SECTION_FLAG_IS_WRAPPER 1
the section only contains other sections, but has no data at its own level
#define SECTION_FLAG_IS_ARRAY 2
the section contains an array of elements of the same type
#define SECTION_FLAG_HAS_VARIABLE_FIELDS 4
the section may contain a variable number of fields with variable keys.
#define WRITER_FLAG_DISPLAY_OPTIONAL_FIELDS 1
#define WRITER_FLAG_PUT_PACKETS_AND_FRAMES_IN_SAME_CHAPTER 2
#define SECTION_MAX_NB_LEVELS 10
#define OFFSET(x) offsetof(WriterContext, x)
#define PRINT_STRING_OPT 1
#define PRINT_STRING_VALIDATE 2
#define MAX_REGISTERED_WRITERS_NB 64
#define DEFINE_WRITER_CLASS(name)
#define OFFSET(x) offsetof(DefaultContext, x)
#define OFFSET(x) offsetof(CompactContext, x)
#define OFFSET(x) offsetof(CompactContext, x)
#define OFFSET(x) offsetof(FlatContext, x)
#define OFFSET(x) offsetof(INIContext, x)
#define OFFSET(x) offsetof(JSONContext, x)
#define JSON_INDENT() printf("%*c", json->indent_level * 4, ' ')
#define OFFSET(x) offsetof(XMLContext, x)
#define CHECK_COMPLIANCE(opt, opt_name)
#define XML_INDENT() printf("%*c", xml->indent_level * 4, ' ')
#define print_fmt(k, f, ...)
#define print_int(k, v) writer_print_integer(w, k, v)
#define print_q(k, v, s) writer_print_rational(w, k, v, s)
#define print_str(k, v) writer_print_string(w, k, v, 0)
#define print_str_opt(k, v) writer_print_string(w, k, v, PRINT_STRING_OPT)
#define print_str_validate(k, v) writer_print_string(w, k, v, PRINT_STRING_VALIDATE)
#define print_time(k, v, tb) writer_print_time(w, k, v, tb, 0)
#define print_ts(k, v) writer_print_ts(w, k, v, 0)
#define print_duration_time(k, v, tb) writer_print_time(w, k, v, tb, 1)
#define print_duration_ts(k, v) writer_print_ts(w, k, v, 1)
#define print_val(k, v, u)
#define print_section_header(s) writer_print_section_header(w, s)
#define print_section_footer(s) writer_print_section_footer(w, s)
#define REALLOCZ_ARRAY_STREAM(ptr, cur_n, new_n)
#define PRINT_DISPOSITION(flagname, name)
#define CHECK_END if (ret < 0) goto end
#define SHOW_LIB_VERSION(libname, LIBNAME)
#define PRINT_PIX_FMT_FLAG(flagname, name)
#define DEFINE_OPT_SHOW_SECTION(section, target_section_id)
#define SET_DO_SHOW(id, varname)
Enumerations
enum SectionID {
SECTION_ID_NONE = -1, SECTION_ID_CHAPTER, SECTION_ID_CHAPTER_TAGS, SECTION_ID_CHAPTERS,
SECTION_ID_ERROR, SECTION_ID_FORMAT, SECTION_ID_FORMAT_TAGS, SECTION_ID_FRAME,
SECTION_ID_FRAMES, SECTION_ID_FRAME_TAGS, SECTION_ID_FRAME_SIDE_DATA_LIST, SECTION_ID_FRAME_SIDE_DATA,
SECTION_ID_LIBRARY_VERSION, SECTION_ID_LIBRARY_VERSIONS, SECTION_ID_PACKET, SECTION_ID_PACKET_TAGS,
SECTION_ID_PACKETS, SECTION_ID_PACKETS_AND_FRAMES, SECTION_ID_PACKET_SIDE_DATA_LIST, SECTION_ID_PACKET_SIDE_DATA,
SECTION_ID_PIXEL_FORMAT, SECTION_ID_PIXEL_FORMAT_FLAGS, SECTION_ID_PIXEL_FORMAT_COMPONENT, SECTION_ID_PIXEL_FORMAT_COMPONENTS,
SECTION_ID_PIXEL_FORMATS, SECTION_ID_PROGRAM_STREAM_DISPOSITION, SECTION_ID_PROGRAM_STREAM_TAGS, SECTION_ID_PROGRAM,
SECTION_ID_PROGRAM_STREAMS, SECTION_ID_PROGRAM_STREAM, SECTION_ID_PROGRAM_TAGS, SECTION_ID_PROGRAM_VERSION,
SECTION_ID_PROGRAMS, SECTION_ID_ROOT, SECTION_ID_STREAM, SECTION_ID_STREAM_DISPOSITION,
SECTION_ID_STREAMS, SECTION_ID_STREAM_TAGS, SECTION_ID_STREAM_SIDE_DATA_LIST, SECTION_ID_STREAM_SIDE_DATA,
SECTION_ID_SUBTITLE
}
enum StringValidation { WRITER_STRING_VALIDATION_FAIL, WRITER_STRING_VALIDATION_REPLACE, WRITER_STRING_VALIDATION_IGNORE, WRITER_STRING_VALIDATION_NB }
Functions
static void ffprobe_cleanup (int ret)
static char * value_string (char *buf, int buf_size, struct unit_value uv)
static const char * writer_get_name (void *p)
static void * writer_child_next (void *obj, void *prev)
static void writer_close (WriterContext **wctx)
static void bprint_bytes (AVBPrint *bp, const uint8_t *ubuf, size_t ubuf_size)
static int writer_open (WriterContext **wctx, const Writer *writer, const char *args, const struct section *sections, int nb_sections)
static void writer_print_section_header (WriterContext *wctx, int section_id)
static void writer_print_section_footer (WriterContext *wctx)
static void writer_print_integer (WriterContext *wctx, const char *key, long long int val)
static int validate_string (WriterContext *wctx, char **dstp, const char *src)
static int writer_print_string (WriterContext *wctx, const char *key, const char *val, int flags)
static void writer_print_rational (WriterContext *wctx, const char *key, AVRational q, char sep)
static void writer_print_time (WriterContext *wctx, const char *key, int64_t ts, const AVRational *time_base, int is_duration)
static void writer_print_ts (WriterContext *wctx, const char *key, int64_t ts, int is_duration)
static void writer_print_data (WriterContext *wctx, const char *name, uint8_t *data, int size)
static void writer_print_data_hash (WriterContext *wctx, const char *name, uint8_t *data, int size)
static void writer_print_integers (WriterContext *wctx, const char *name, uint8_t *data, int size, const char *format, int columns, int bytes, int offset_add)
static int writer_register (const Writer *writer)
static const Writer * writer_get_by_name (const char *name)
DEFINE_WRITER_CLASS (default)
static char * upcase_string (char *dst, size_t dst_size, const char *src)
static void default_print_section_header (WriterContext *wctx)
static void default_print_section_footer (WriterContext *wctx)
static void default_print_str (WriterContext *wctx, const char *key, const char *value)
static void default_print_int (WriterContext *wctx, const char *key, long long int value)
static const char * c_escape_str (AVBPrint *dst, const char *src, const char sep, void *log_ctx)
Apply C-language-like string escaping.
static const char * csv_escape_str (AVBPrint *dst, const char *src, const char sep, void *log_ctx)
Quote fields containing special characters, check RFC4180.
static const char * none_escape_str (AVBPrint *dst, const char *src, const char sep, void *log_ctx)
DEFINE_WRITER_CLASS (compact)
static av_cold int compact_init (WriterContext *wctx)
static void compact_print_section_header (WriterContext *wctx)
static void compact_print_section_footer (WriterContext *wctx)
static void compact_print_str (WriterContext *wctx, const char *key, const char *value)
static void compact_print_int (WriterContext *wctx, const char *key, long long int value)
DEFINE_WRITER_CLASS (csv)
DEFINE_WRITER_CLASS (flat)
static av_cold int flat_init (WriterContext *wctx)
static const char * flat_escape_key_str (AVBPrint *dst, const char *src, const char sep)
static const char * flat_escape_value_str (AVBPrint *dst, const char *src)
static void flat_print_section_header (WriterContext *wctx)
static void flat_print_int (WriterContext *wctx, const char *key, long long int value)
static void flat_print_str (WriterContext *wctx, const char *key, const char *value)
DEFINE_WRITER_CLASS (ini)
static char * ini_escape_str (AVBPrint *dst, const char *src)
static void ini_print_section_header (WriterContext *wctx)
static void ini_print_str (WriterContext *wctx, const char *key, const char *value)
static void ini_print_int (WriterContext *wctx, const char *key, long long int value)
DEFINE_WRITER_CLASS (json)
static av_cold int json_init (WriterContext *wctx)
static const char * json_escape_str (AVBPrint *dst, const char *src, void *log_ctx)
static void json_print_section_header (WriterContext *wctx)
static void json_print_section_footer (WriterContext *wctx)
static void json_print_item_str (WriterContext *wctx, const char *key, const char *value)
static void json_print_str (WriterContext *wctx, const char *key, const char *value)
static void json_print_int (WriterContext *wctx, const char *key, long long int value)
DEFINE_WRITER_CLASS (xml)
static av_cold int xml_init (WriterContext *wctx)
static const char * xml_escape_str (AVBPrint *dst, const char *src, void *log_ctx)
static void xml_print_section_header (WriterContext *wctx)
static void xml_print_section_footer (WriterContext *wctx)
static void xml_print_str (WriterContext *wctx, const char *key, const char *value)
static void xml_print_int (WriterContext *wctx, const char *key, long long int value)
static void writer_register_all (void)
static int show_tags (WriterContext *w, AVDictionary *tags, int section_id)
static void print_pkt_side_data (WriterContext *w, const AVPacketSideData *side_data, int nb_side_data, SectionID id_data_list, SectionID id_data)
static void show_packet (WriterContext *w, InputFile *ifile, AVPacket *pkt, int packet_idx)
static void show_subtitle (WriterContext *w, AVSubtitle *sub, AVStream *stream, AVFormatContext *fmt_ctx)
static void show_frame (WriterContext *w, AVFrame *frame, AVStream *stream, AVFormatContext *fmt_ctx)
static av_always_inline int process_frame (WriterContext *w, InputFile *ifile, AVFrame *frame, AVPacket *pkt)
static void log_read_interval (const ReadInterval *interval, void *log_ctx, int log_level)
static int read_interval_packets (WriterContext *w, InputFile *ifile, const ReadInterval *interval, int64_t *cur_ts)
static int read_packets (WriterContext *w, InputFile *ifile)
static int show_stream (WriterContext *w, AVFormatContext *fmt_ctx, int stream_idx, InputStream *ist, int in_program)
static int show_streams (WriterContext *w, InputFile *ifile)
static int show_program (WriterContext *w, InputFile *ifile, AVProgram *program)
static int show_programs (WriterContext *w, InputFile *ifile)
static int show_chapters (WriterContext *w, InputFile *ifile)
static int show_format (WriterContext *w, InputFile *ifile)
static void show_error (WriterContext *w, int err)
static int open_input_file (InputFile *ifile, const char *filename)
static void close_input_file (InputFile *ifile)
static int probe_file (WriterContext *wctx, const char *filename)
static void show_usage (void)
static void ffprobe_show_program_version (WriterContext *w)
static void ffprobe_show_library_versions (WriterContext *w)
static void ffprobe_show_pixel_formats (WriterContext *w)
static int opt_format (void *optctx, const char *opt, const char *arg)
static void mark_section_show_entries (SectionID section_id, int show_all_entries, AVDictionary *entries)
static int match_section (const char *section_name, int show_all_entries, AVDictionary *entries)
static int opt_show_entries (void *optctx, const char *opt, const char *arg)
static int opt_show_format_entry (void *optctx, const char *opt, const char *arg)
static void opt_input_file (void *optctx, const char *arg)
static int opt_input_file_i (void *optctx, const char *opt, const char *arg)
void show_help_default (const char *opt, const char *arg)
Per-fftool specific help handler.
static int parse_read_interval (const char *interval_spec, ReadInterval *interval)
Parse interval specification, according to the format: INTERVAL ::= [START|+START_OFFSET][%[END|+END_OFFSET]] INTERVALS ::= INTERVAL[,INTERVALS].
static int parse_read_intervals (const char *intervals_spec)
static int opt_read_intervals (void *optctx, const char *opt, const char *arg)
static int opt_pretty (void *optctx, const char *opt, const char *arg)
static void print_section (SectionID id, int level)
static int opt_sections (void *optctx, const char *opt, const char *arg)
static int opt_show_versions (const char *opt, const char *arg)
static int check_section_show_entries (int section_id)
int main (int argc, char **argv)
Variables
const char program_name [] = "ffprobe"
program name, defined by the program for show_version().
const int program_birth_year = 2007
program birth year, defined by the program for show_banner()
static int do_bitexact = 0
static int do_count_frames = 0
static int do_count_packets = 0
static int do_read_frames = 0
static int do_read_packets = 0
static int do_show_chapters = 0
static int do_show_error = 0
static int do_show_format = 0
static int do_show_frames = 0
static int do_show_packets = 0
static int do_show_programs = 0
static int do_show_streams = 0
static int do_show_stream_disposition = 0
static int do_show_data = 0
static int do_show_program_version = 0
static int do_show_library_versions = 0
static int do_show_pixel_formats = 0
static int do_show_pixel_format_flags = 0
static int do_show_pixel_format_components = 0
static int do_show_chapter_tags = 0
static int do_show_format_tags = 0
static int do_show_frame_tags = 0
static int do_show_program_tags = 0
static int do_show_stream_tags = 0
static int do_show_packet_tags = 0
static int show_value_unit = 0
static int use_value_prefix = 0
static int use_byte_value_binary_prefix = 0
static int use_value_sexagesimal_format = 0
static int show_private_data = 1
static char * print_format
static char * stream_specifier
static char * show_data_hash
static ReadInterval * read_intervals
static int read_intervals_nb = 0
static struct section sections []
static const OptionDef * options
static const char * input_filename
static AVInputFormat * iformat = NULL
static struct AVHashContext * hash
struct {
double bin_val
double dec_val
const char * bin_str
const char * dec_str
} si_prefixes []
static const char unit_second_str [] = "s"
static const char unit_hertz_str [] = "Hz"
static const char unit_byte_str [] = "byte"
static const char unit_bit_per_second_str [] = "bit/s"
static int nb_streams
static uint64_t * nb_streams_packets
static uint64_t * nb_streams_frames
static int * selected_streams
static const AVOption writer_options []
static const AVClass writer_class
static const Writer * registered_writers [MAX_REGISTERED_WRITERS_NB+1]
static const AVOption default_options []
static const Writer default_writer
static const AVOption compact_options []
static const Writer compact_writer
static const AVOption csv_options []
static const Writer csv_writer
static const AVOption flat_options []
static const Writer flat_writer
static const AVOption ini_options []
static const Writer ini_writer
static const AVOption json_options []
static const Writer json_writer
static const AVOption xml_options []
static Writer xml_writer
static const OptionDef real_options []
Detailed Description
simple media prober based on the FFmpeg libraries
Definition in file ffprobe.c.
Macro Definition Documentation
SECTION_MAX_NB_CHILDREN
#define SECTION_MAX_NB_CHILDREN 10
Definition at line 120 of file ffprobe.c.
SECTION_FLAG_IS_WRAPPER
#define SECTION_FLAG_IS_WRAPPER 1
the section only contains other sections, but has no data at its own level
Definition at line 126 of file ffprobe.c.
Referenced by compact_print_section_footer(), compact_print_section_header(), default_print_section_footer(), default_print_section_header(), flat_print_section_header(), ini_print_section_header(), json_print_section_header(), print_section(), and xml_print_section_header().
SECTION_FLAG_IS_ARRAY
#define SECTION_FLAG_IS_ARRAY 2
the section contains an array of elements of the same type
Definition at line 127 of file ffprobe.c.
Referenced by compact_print_section_footer(), compact_print_section_header(), default_print_section_footer(), default_print_section_header(), flat_print_section_header(), ini_print_section_header(), json_print_section_footer(), json_print_section_header(), print_section(), and xml_print_section_header().
SECTION_FLAG_HAS_VARIABLE_FIELDS
#define SECTION_FLAG_HAS_VARIABLE_FIELDS 4
the section may contain a variable number of fields with variable keys.
Definition at line 128 of file ffprobe.c.
Referenced by print_section(), xml_print_section_footer(), xml_print_section_header(), and xml_print_str().
WRITER_FLAG_DISPLAY_OPTIONAL_FIELDS
#define WRITER_FLAG_DISPLAY_OPTIONAL_FIELDS 1
Definition at line 329 of file ffprobe.c.
Referenced by writer_print_string().
WRITER_FLAG_PUT_PACKETS_AND_FRAMES_IN_SAME_CHAPTER
#define WRITER_FLAG_PUT_PACKETS_AND_FRAMES_IN_SAME_CHAPTER 2
Definition at line 330 of file ffprobe.c.
Referenced by probe_file().
SECTION_MAX_NB_LEVELS
#define SECTION_MAX_NB_LEVELS 10
Definition at line 355 of file ffprobe.c.
Referenced by writer_close(), writer_open(), and writer_print_section_header().
OFFSET [1/8]
#define OFFSET (x) offsetof(WriterContext, x)
Definition at line 1535 of file ffprobe.c.
PRINT_STRING_OPT
#define PRINT_STRING_OPT 1
Definition at line 643 of file ffprobe.c.
Referenced by writer_print_string(), writer_print_time(), and writer_print_ts().
PRINT_STRING_VALIDATE
#define PRINT_STRING_VALIDATE 2
Definition at line 644 of file ffprobe.c.
Referenced by writer_print_string().
MAX_REGISTERED_WRITERS_NB
#define MAX_REGISTERED_WRITERS_NB 64
Definition at line 786 of file ffprobe.c.
Referenced by writer_register().
DEFINE_WRITER_CLASS
#define DEFINE_WRITER_CLASS (name)
Value:
static const char *name##_get_name(void *ctx)       \
{                                                   \
    return #name ;                                  \
}                                                   \
static const AVClass name##_class = {               \
    .class_name = #name,                            \
    .item_name  = name##_get_name,                  \
    .option     = name##_options                    \
}
Definition at line 815 of file ffprobe.c.
OFFSET [2/8]
#define OFFSET (x) offsetof(DefaultContext, x)
Definition at line 1535 of file ffprobe.c.
OFFSET [3/8]
#define OFFSET (x) offsetof(CompactContext, x)
Definition at line 1535 of file ffprobe.c.
OFFSET [4/8]
#define OFFSET (x) offsetof(CompactContext, x)
Definition at line 1535 of file ffprobe.c.
OFFSET [5/8]
#define OFFSET (x) offsetof(FlatContext, x)
Definition at line 1535 of file ffprobe.c.
OFFSET [6/8]
#define OFFSET (x) offsetof(INIContext, x)
Definition at line 1535 of file ffprobe.c.
OFFSET [7/8]
#define OFFSET (x) offsetof(JSONContext, x)
Definition at line 1535 of file ffprobe.c.
JSON_INDENT
#define JSON_INDENT () printf("%*c", json->indent_level * 4, ' ')
Definition at line 1412 of file ffprobe.c.
Referenced by json_print_int(), json_print_section_footer(), json_print_section_header(), and json_print_str().
OFFSET [8/8]
#define OFFSET (x) offsetof(XMLContext, x)
Definition at line 1535 of file ffprobe.c.
CHECK_COMPLIANCE
#define CHECK_COMPLIANCE (opt, opt_name)
Value:
if (opt) {                                                      \
            av_log(wctx, AV_LOG_ERROR,                                  \
                   "XSD-compliant output selected but option '%s' was selected, XML output may be non-compliant.\n" \
                   "You need to disable such option with '-no%s'\n", opt_name, opt_name); \
            return AVERROR(EINVAL);                                     \
        }
Referenced by xml_init().
XML_INDENT
#define XML_INDENT () printf("%*c", xml->indent_level * 4, ' ')
Definition at line 1593 of file ffprobe.c.
Referenced by xml_print_section_footer(), xml_print_section_header(), and xml_print_str().
print_fmt
#define print_fmt (k, f, ...)
Value:
do {              \
    av_bprint_clear(&pbuf);                    \
    av_bprintf(&pbuf, f, __VA_ARGS__);         \
    writer_print_string(w, k, pbuf.str, 0);    \
} while (0)
Definition at line 1713 of file ffprobe.c.
Referenced by ffprobe_show_program_version(), show_frame(), show_packet(), and show_stream().
print_int
#define print_int (k, v) writer_print_integer(w, k, v)
Definition at line 1719 of file ffprobe.c.
Referenced by ffprobe_show_pixel_formats(), print_pkt_side_data(), show_chapters(), show_error(), show_format(), show_frame(), show_packet(), show_program(), show_stream(), and show_subtitle().
print_q
#define print_q (k, v, s) writer_print_rational(w, k, v, s)
Definition at line 1720 of file ffprobe.c.
Referenced by show_chapters(), show_frame(), and show_stream().
print_str
#define print_str (k, v) writer_print_string(w, k, v, 0)
Definition at line 1721 of file ffprobe.c.
Referenced by ffprobe_show_pixel_formats(), ffprobe_show_program_version(), print_pkt_side_data(), show_error(), show_format(), show_frame(), show_packet(), show_stream(), and show_subtitle().
print_str_opt
#define print_str_opt (k, v) writer_print_string(w, k, v, PRINT_STRING_OPT)
Definition at line 1722 of file ffprobe.c.
Referenced by ffprobe_show_pixel_formats(), show_format(), show_frame(), show_packet(), and show_stream().
print_str_validate
#define print_str_validate (k, v) writer_print_string(w, k, v, PRINT_STRING_VALIDATE)
Definition at line 1723 of file ffprobe.c.
Referenced by show_format(), and show_tags().
print_time
#define print_time (k, v, tb) writer_print_time(w, k, v, tb, 0)
Definition at line 1724 of file ffprobe.c.
Referenced by show_chapters(), show_format(), show_frame(), show_packet(), show_program(), show_stream(), and show_subtitle().
print_ts
#define print_ts (k, v) writer_print_ts(w, k, v, 0)
Definition at line 1725 of file ffprobe.c.
Referenced by show_frame(), show_packet(), show_program(), show_stream(), and show_subtitle().
print_duration_time
#define print_duration_time (k, v, tb) writer_print_time(w, k, v, tb, 1)
Definition at line 1726 of file ffprobe.c.
Referenced by show_frame(), and show_packet().
print_duration_ts
#define print_duration_ts (k, v) writer_print_ts(w, k, v, 1)
Definition at line 1727 of file ffprobe.c.
Referenced by show_frame(), and show_packet().
print_val
#define print_val (k, v, u)
Value:
do {                                     \
    struct unit_value uv;                                           \
    uv.val.i = v;                                                   \
    uv.unit = u;                                                    \
    writer_print_string(w, k, value_string(val_str, sizeof(val_str), uv), 0); \
} while (0)
Definition at line 1728 of file ffprobe.c.
Referenced by show_format(), show_frame(), show_packet(), and show_stream().
print_section_header
#define print_section_header (s) writer_print_section_header(w, s)
Definition at line 1735 of file ffprobe.c.
print_section_footer
#define print_section_footer (s) writer_print_section_footer(w, s)
Definition at line 1736 of file ffprobe.c.
REALLOCZ_ARRAY_STREAM
#define REALLOCZ_ARRAY_STREAM (ptr, cur_n, new_n)
Value:
{                                                                       \
    ret = av_reallocp_array(&(ptr), (new_n), sizeof(*(ptr)));           \
    if (ret < 0)                                                        \
        goto end;                                                       \
    memset( (ptr) + (cur_n), 0, ((new_n) - (cur_n)) * sizeof(*(ptr)) ); \
}
Definition at line 1738 of file ffprobe.c.
Referenced by probe_file(), and read_interval_packets().
PRINT_DISPOSITION
#define PRINT_DISPOSITION (flagname, name)
Value:
do {                                \
        print_int(name, !!(stream->disposition & AV_DISPOSITION_##flagname)); \
    } while (0)
Referenced by show_stream().
CHECK_END
#define CHECK_END if (ret < 0) goto end
Referenced by probe_file().
SHOW_LIB_VERSION
#define SHOW_LIB_VERSION (libname, LIBNAME)
Value:
do {                                                                \
        if (CONFIG_##LIBNAME) {                                         \
            unsigned int version = libname##_version();                 \
            writer_print_section_header(w, SECTION_ID_LIBRARY_VERSION); \
            print_str("name",    "lib" #libname);                       \
            print_int("major",   LIB##LIBNAME##_VERSION_MAJOR);         \
            print_int("minor",   LIB##LIBNAME##_VERSION_MINOR);         \
            print_int("micro",   LIB##LIBNAME##_VERSION_MICRO);         \
            print_int("version", version);                              \
            print_str("ident",   LIB##LIBNAME##_IDENT);                 \
            writer_print_section_footer(w);                             \
        }                                                               \
    } while (0)
Definition at line 2778 of file ffprobe.c.
Referenced by ffprobe_show_library_versions().
PRINT_PIX_FMT_FLAG
#define PRINT_PIX_FMT_FLAG (flagname, name)
Value:
do {                                                                  \
        print_int(name, !!(pixdesc->flags & AV_PIX_FMT_FLAG_##flagname)); \
    } while (0)
Definition at line 2807 of file ffprobe.c.
Referenced by ffprobe_show_pixel_formats().
DEFINE_OPT_SHOW_SECTION
#define DEFINE_OPT_SHOW_SECTION (section, target_section_id)
Value:
static int opt_show_##section(const char *opt, const char *arg)     \
    {                                                                   \
        mark_section_show_entries(SECTION_ID_##target_section_id, 1, NULL); \
        return 0;                                                       \
    }
Definition at line 3182 of file ffprobe.c.
SET_DO_SHOW
#define SET_DO_SHOW (id, varname)
Value:
do {                                   \
        if (check_section_show_entries(SECTION_ID_##id))                \
            do_show_##varname = 1;                                      \
    } while (0)
Definition at line 3256 of file ffprobe.c.
Referenced by main().
Enumeration Type Documentation
SectionID
enum SectionID
Enumerator
SECTION_ID_NONE
SECTION_ID_CHAPTER
SECTION_ID_CHAPTER_TAGS
SECTION_ID_CHAPTERS
SECTION_ID_ERROR
SECTION_ID_FORMAT
SECTION_ID_FORMAT_TAGS
SECTION_ID_FRAME
SECTION_ID_FRAMES
SECTION_ID_FRAME_TAGS
SECTION_ID_FRAME_SIDE_DATA_LIST
SECTION_ID_FRAME_SIDE_DATA
SECTION_ID_LIBRARY_VERSION
SECTION_ID_LIBRARY_VERSIONS
SECTION_ID_PACKET
SECTION_ID_PACKET_TAGS
SECTION_ID_PACKETS
SECTION_ID_PACKETS_AND_FRAMES
SECTION_ID_PACKET_SIDE_DATA_LIST
SECTION_ID_PACKET_SIDE_DATA
SECTION_ID_PIXEL_FORMAT
SECTION_ID_PIXEL_FORMAT_FLAGS
SECTION_ID_PIXEL_FORMAT_COMPONENT
SECTION_ID_PIXEL_FORMAT_COMPONENTS
SECTION_ID_PIXEL_FORMATS
SECTION_ID_PROGRAM_STREAM_DISPOSITION
SECTION_ID_PROGRAM_STREAM_TAGS
SECTION_ID_PROGRAM
SECTION_ID_PROGRAM_STREAMS
SECTION_ID_PROGRAM_STREAM
SECTION_ID_PROGRAM_TAGS
SECTION_ID_PROGRAM_VERSION
SECTION_ID_PROGRAMS
SECTION_ID_ROOT
SECTION_ID_STREAM
SECTION_ID_STREAM_DISPOSITION
SECTION_ID_STREAMS
SECTION_ID_STREAM_TAGS
SECTION_ID_STREAM_SIDE_DATA_LIST
SECTION_ID_STREAM_SIDE_DATA
SECTION_ID_SUBTITLE
Definition at line 138 of file ffprobe.c.
StringValidation
enum StringValidation
Enumerator
WRITER_STRING_VALIDATION_FAIL
WRITER_STRING_VALIDATION_REPLACE
WRITER_STRING_VALIDATION_IGNORE
WRITER_STRING_VALIDATION_NB
Definition at line 332 of file ffprobe.c.
Function Documentation
ffprobe_cleanup()
static void ffprobe_cleanup (int ret) static
Definition at line 260 of file ffprobe.c.
Referenced by main().
value_string()
static char* value_string (char * buf, int buf_size, struct unit_value uv) static
Definition at line 272 of file ffprobe.c.
Referenced by writer_print_time().
writer_get_name()
static const char* writer_get_name (void * p) static
Definition at line 385 of file ffprobe.c.
writer_child_next()
static void* writer_child_next (void * obj, void * prev) static
Definition at line 406 of file ffprobe.c.
writer_close()
static void writer_close (WriterContext ** wctx) static
Definition at line 422 of file ffprobe.c.
Referenced by main(), and writer_open().
bprint_bytes()
static void bprint_bytes (AVBPrint * bp, const uint8_t * ubuf, size_t ubuf_size) static
Definition at line 440 of file ffprobe.c.
Referenced by validate_string(), and writer_open().
writer_open()
static int writer_open (WriterContext ** wctx, const Writer * writer, const char * args, const struct section * sections, int nb_sections) static
Definition at line 449 of file ffprobe.c.
Referenced by main().
writer_print_section_header()
static void writer_print_section_header (WriterContext * wctx, int section_id) inline static
Definition at line 536 of file ffprobe.c.
Referenced by ffprobe_show_library_versions(), ffprobe_show_pixel_formats(), ffprobe_show_program_version(), main(), print_pkt_side_data(), probe_file(), show_chapters(), show_error(), show_format(), show_frame(), show_packet(), show_program(), show_programs(), show_stream(), show_streams(), show_subtitle(), and show_tags().
writer_print_section_footer()
static void writer_print_section_footer (WriterContext * wctx) inline static
Definition at line 560 of file ffprobe.c.
Referenced by ffprobe_show_library_versions(), ffprobe_show_pixel_formats(), ffprobe_show_program_version(), main(), print_pkt_side_data(), probe_file(), show_chapters(), show_error(), show_format(), show_frame(), show_packet(), show_program(), show_programs(), show_stream(), show_streams(), show_subtitle(), and show_tags().
writer_print_integer()
static void writer_print_integer (WriterContext * wctx, const char * key, long long int val) inline static
Definition at line 577 of file ffprobe.c.
Referenced by writer_print_ts().
validate_string()
static int validate_string (WriterContext * wctx, char ** dstp, const char * src) inline static
Definition at line 588 of file ffprobe.c.
Referenced by writer_print_string().
writer_print_string()
static int writer_print_string (WriterContext * wctx, const char * key, const char * val, int flags) inline static
Definition at line 646 of file ffprobe.c.
Referenced by writer_print_data(), writer_print_data_hash(), writer_print_integers(), writer_print_rational(), writer_print_time(), and writer_print_ts().
writer_print_rational()
static void writer_print_rational (WriterContext * wctx, const char * key, AVRational q, char sep) inline static
Definition at line 682 of file ffprobe.c.
writer_print_time()
static void writer_print_time (WriterContext * wctx, const char * key, int64_t ts, const AVRational * time_base, int is_duration) static
Definition at line 691 of file ffprobe.c.
writer_print_ts()
static void writer_print_ts (WriterContext * wctx, const char * key, int64_t ts, int is_duration) static
Definition at line 708 of file ffprobe.c.
writer_print_data()
static void writer_print_data (WriterContext * wctx, const char * name, uint8_t * data, int size) static
Definition at line 717 of file ffprobe.c.
Referenced by show_packet(), and show_stream().
writer_print_data_hash()
static void writer_print_data_hash (WriterContext * wctx, const char * name, uint8_t * data, int size) static
Definition at line 745 of file ffprobe.c.
Referenced by show_packet(), and show_stream().
writer_print_integers()
static void writer_print_integers (WriterContext * wctx, const char * name, uint8_t * data, int size, const char * format, int columns, int bytes, int offset_add) static
Definition at line 760 of file ffprobe.c.
Referenced by print_pkt_side_data(), and show_frame().
writer_register()
static int writer_register (const Writer * writer) static
Definition at line 790 of file ffprobe.c.
Referenced by writer_register_all().
writer_get_by_name()
static const Writer* writer_get_by_name (const char * name) static
Definition at line 801 of file ffprobe.c.
Referenced by main().
DEFINE_WRITER_CLASS() [1/7]
DEFINE_WRITER_CLASS (default)
upcase_string()
static char* upcase_string (char * dst, size_t dst_size, const char * src) inline static
Definition at line 849 of file ffprobe.c.
Referenced by default_print_section_footer(), and default_print_section_header().
default_print_section_header()
static void default_print_section_header (WriterContext * wctx) static
Definition at line 858 of file ffprobe.c.
default_print_section_footer()
static void default_print_section_footer (WriterContext * wctx) static
Definition at line 883 of file ffprobe.c.
default_print_str()
static void default_print_str (WriterContext * wctx, const char * key, const char * value) static
Definition at line 896 of file ffprobe.c.
default_print_int()
static void default_print_int (WriterContext * wctx, const char * key, long long int value) static
Definition at line 905 of file ffprobe.c.
c_escape_str()
static const char* c_escape_str (AVBPrint * dst, const char * src, const char sep, void * log_ctx) static
Apply C-language-like string escaping.
Definition at line 930 of file ffprobe.c.
Referenced by compact_init().
csv_escape_str()
static const char* csv_escape_str (AVBPrint * dst, const char * src, const char sep, void * log_ctx) static
Quote fields containing special characters, check RFC4180.
Definition at line 953 of file ffprobe.c.
Referenced by compact_init().
none_escape_str()
static const char* none_escape_str (AVBPrint * dst, const char * src, const char sep, void * log_ctx) static
Definition at line 971 of file ffprobe.c.
Referenced by compact_init().
DEFINE_WRITER_CLASS() [2/7]
DEFINE_WRITER_CLASS (compact)
compact_init()
static av_cold int compact_init (WriterContext * wctx) static
Definition at line 1006 of file ffprobe.c.
compact_print_section_header()
static void compact_print_section_header (WriterContext * wctx) static
Definition at line 1028 of file ffprobe.c.
compact_print_section_footer()
static void compact_print_section_footer (WriterContext * wctx) static
Definition at line 1058 of file ffprobe.c.
compact_print_str()
static void compact_print_str (WriterContext * wctx, const char * key, const char * value) static
Definition at line 1068 of file ffprobe.c.
compact_print_int()
static void compact_print_int (WriterContext * wctx, const char * key, long long int value) static
Definition at line 1081 of file ffprobe.c.
DEFINE_WRITER_CLASS() [3/7]
DEFINE_WRITER_CLASS (csv)
DEFINE_WRITER_CLASS() [4/7]
DEFINE_WRITER_CLASS (flat)
flat_init()
static av_cold int flat_init (WriterContext * wctx) static
Definition at line 1156 of file ffprobe.c.
flat_escape_key_str()
static const char* flat_escape_key_str (AVBPrint * dst, const char * src, const char sep) static
Definition at line 1170 of file ffprobe.c.
Referenced by flat_print_str().
flat_escape_value_str()
static const char* flat_escape_value_str (AVBPrint * dst, const char * src) static
Definition at line 1185 of file ffprobe.c.
Referenced by flat_print_str().
flat_print_section_header()
static void flat_print_section_header (WriterContext * wctx) static
Definition at line 1203 of file ffprobe.c.
flat_print_int()
static void flat_print_int (WriterContext * wctx, const char * key, long long int value) static
Definition at line 1229 of file ffprobe.c.
flat_print_str()
static void flat_print_str (WriterContext * wctx, const char * key, const char * value) static
Definition at line 1234 of file ffprobe.c.
DEFINE_WRITER_CLASS() [5/7]
DEFINE_WRITER_CLASS (ini)
ini_escape_str()
static char* ini_escape_str (AVBPrint * dst, const char * src) static
Definition at line 1276 of file ffprobe.c.
Referenced by ini_print_str().
ini_print_section_header()
static void ini_print_section_header (WriterContext * wctx) static
Definition at line 1303 of file ffprobe.c.
ini_print_str()
static void ini_print_str (WriterContext * wctx, const char * key, const char * value) static
Definition at line 1336 of file ffprobe.c.
ini_print_int()
static void ini_print_int (WriterContext * wctx, const char * key, long long int value) static
Definition at line 1347 of file ffprobe.c.
DEFINE_WRITER_CLASS() [6/7]
DEFINE_WRITER_CLASS (json)
json_init()
static av_cold int json_init (WriterContext * wctx) static
Definition at line 1382 of file ffprobe.c.
json_escape_str()
static const char* json_escape_str (AVBPrint * dst, const char * src, void * log_ctx) static
Definition at line 1392 of file ffprobe.c.
Referenced by json_print_int(), json_print_item_str(), and json_print_section_header().
json_print_section_header()
static void json_print_section_header (WriterContext * wctx) static
Definition at line 1414 of file ffprobe.c.
json_print_section_footer()
static void json_print_section_footer (WriterContext * wctx) static
Definition at line 1452 of file ffprobe.c.
json_print_item_str()
static void json_print_item_str (WriterContext * wctx, const char * key, const char * value) inline static
Definition at line 1474 of file ffprobe.c.
Referenced by json_print_str().
json_print_str()
static void json_print_str (WriterContext * wctx, const char * key, const char * value) static
Definition at line 1486 of file ffprobe.c.
json_print_int()
static void json_print_int (WriterContext * wctx, const char * key, long long int value) static
Definition at line 1497 of file ffprobe.c.
DEFINE_WRITER_CLASS() [7/7]
DEFINE_WRITER_CLASS (xml)
xml_init()
static av_cold int xml_init (WriterContext * wctx) static
Definition at line 1547 of file ffprobe.c.
xml_escape_str()
static const char* xml_escape_str (AVBPrint * dst, const char * src, void * log_ctx) static
Definition at line 1575 of file ffprobe.c.
Referenced by xml_print_str().
xml_print_section_header()
static void xml_print_section_header (WriterContext * wctx) static
Definition at line 1595 of file ffprobe.c.
xml_print_section_footer()
static void xml_print_section_footer (WriterContext * wctx) static
Definition at line 1635 of file ffprobe.c.
xml_print_str()
static void xml_print_str (WriterContext * wctx, const char * key, const char * value) static
Definition at line 1654 of file ffprobe.c.
xml_print_int()
static void xml_print_int (WriterContext * wctx, const char * key, long long int value) static
Definition at line 1677 of file ffprobe.c.
writer_register_all()
static void writer_register_all (void) static
Definition at line 1696 of file ffprobe.c.
Referenced by main().
show_tags()
static int show_tags (WriterContext * w, AVDictionary * tags, int section_id) inline static
Definition at line 1746 of file ffprobe.c.
Referenced by show_chapters(), show_format(), show_frame(), show_packet(), show_program(), and show_stream().
print_pkt_side_data()
static void print_pkt_side_data (WriterContext * w, const AVPacketSideData * side_data, int nb_side_data, SectionID id_data_list, SectionID id_data) static
Definition at line 1764 of file ffprobe.c.
Referenced by show_packet(), and show_stream().
show_packet()
static void show_packet (WriterContext * w, InputFile * ifile, AVPacket * pkt, int packet_idx) static
Definition at line 1805 of file ffprobe.c.
Referenced by read_interval_packets().
show_subtitle()
static void show_subtitle (WriterContext * w, AVSubtitle * sub, AVStream * stream, AVFormatContext * fmt_ctx) static
Definition at line 1860 of file ffprobe.c.
Referenced by process_frame().
show_frame()
static void show_frame (WriterContext * w, AVFrame * frame, AVStream * stream, AVFormatContext * fmt_ctx) static
Definition at line 1883 of file ffprobe.c.
Referenced by process_frame().
process_frame()
static av_always_inline int process_frame (WriterContext * w, InputFile * ifile, AVFrame * frame, AVPacket * pkt) static
Definition at line 1982 of file ffprobe.c.
Referenced by read_interval_packets().
log_read_interval()
static void log_read_interval (const ReadInterval * interval, void * log_ctx, int log_level) static
Definition at line 2027 of file ffprobe.c.
Referenced by parse_read_intervals(), and read_interval_packets().
read_interval_packets()
static int read_interval_packets (WriterContext * w, InputFile * ifile, const ReadInterval * interval, int64_t * cur_ts) static
Definition at line 2051 of file ffprobe.c.
Referenced by read_packets().
read_packets()
static int read_packets (WriterContext * w, InputFile * ifile) static
Definition at line 2157 of file ffprobe.c.
Referenced by probe_file().
show_stream()
static int show_stream (WriterContext * w, AVFormatContext * fmt_ctx, int stream_idx, InputStream * ist, int in_program) static
Definition at line 2177 of file ffprobe.c.
Referenced by show_program(), and show_streams().
show_streams()
static int show_streams (WriterContext * w, InputFile * ifile) static
Definition at line 2419 of file ffprobe.c.
Referenced by probe_file().
show_program()
static int show_program (WriterContext * w, InputFile * ifile, AVProgram * program) static
Definition at line 2436 of file ffprobe.c.
Referenced by show_programs().
show_programs()
static int show_programs (WriterContext * w, InputFile * ifile) static
Definition at line 2471 of file ffprobe.c.
Referenced by probe_file().
show_chapters()
static int show_chapters (WriterContext * w, InputFile * ifile) static
Definition at line 2489 of file ffprobe.c.
Referenced by probe_file().
show_format()
static int show_format (WriterContext * w, InputFile * ifile) static
Definition at line 2514 of file ffprobe.c.
Referenced by probe_file().
show_error()
static void show_error (WriterContext * w, int err) static
Definition at line 2545 of file ffprobe.c.
Referenced by main().
open_input_file()
static int open_input_file (InputFile * ifile, const char * filename) static
Definition at line 2559 of file ffprobe.c.
Referenced by probe_file().
close_input_file()
static void close_input_file (InputFile * ifile) static
Definition at line 2662 of file ffprobe.c.
Referenced by probe_file().
probe_file()
static int probe_file (WriterContext * wctx, const char * filename) static
Definition at line 2677 of file ffprobe.c.
Referenced by main().
show_usage()
static void show_usage (void) static
Definition at line 2755 of file ffprobe.c.
Referenced by main(), and show_help_default().
ffprobe_show_program_version()
static void ffprobe_show_program_version (WriterContext * w) static
Definition at line 2762 of file ffprobe.c.
Referenced by main().
ffprobe_show_library_versions()
static void ffprobe_show_library_versions (WriterContext * w) static
Definition at line 2793 of file ffprobe.c.
Referenced by main().
ffprobe_show_pixel_formats()
static void ffprobe_show_pixel_formats (WriterContext * w) static
Definition at line 2812 of file ffprobe.c.
Referenced by main().
opt_format()
static int opt_format (void * optctx, const char * opt, const char * arg) static
Definition at line 2859 of file ffprobe.c.
mark_section_show_entries()
static void mark_section_show_entries (SectionID section_id, int show_all_entries, AVDictionary * entries) inline static
Definition at line 2869 of file ffprobe.c.
Referenced by match_section(), and opt_show_versions().
match_section()
static int match_section (const char * section_name, int show_all_entries, AVDictionary * entries) static
Definition at line 2884 of file ffprobe.c.
Referenced by opt_show_entries().
opt_show_entries()
static int opt_show_entries (void * optctx, const char * opt, const char * arg) static
Definition at line 2903 of file ffprobe.c.
Referenced by opt_show_format_entry().
opt_show_format_entry()
static int opt_show_format_entry (void * optctx, const char * opt, const char * arg) static
Definition at line 2953 of file ffprobe.c.
opt_input_file()
static void opt_input_file (void * optctx, const char * arg) static
Definition at line 2969 of file ffprobe.c.
Referenced by main(), and opt_input_file_i().
opt_input_file_i()
static int opt_input_file_i (void * optctx, const char * opt, const char * arg) static
Definition at line 2982 of file ffprobe.c.
show_help_default()
void show_help_default (const char * opt, const char * arg)
Per-fftool specific help handler.
Implemented in each fftool, called by show_help().
Definition at line 2988 of file ffprobe.c.
parse_read_interval()
static int parse_read_interval (const char * interval_spec, ReadInterval * interval) static
Parse interval specification, according to the format: INTERVAL ::= [START|+START_OFFSET][%[END|+END_OFFSET]] INTERVALS ::= INTERVAL[,INTERVALS].
Definition at line 3003 of file ffprobe.c.
Referenced by parse_read_intervals().
parse_read_intervals()
static int parse_read_intervals (const char * intervals_spec) static
Definition at line 3084 of file ffprobe.c.
Referenced by opt_read_intervals().
opt_read_intervals()
static int opt_read_intervals (void * optctx, const char * opt, const char * arg) static
Definition at line 3132 of file ffprobe.c.
opt_pretty()
static int opt_pretty (void * optctx, const char * opt, const char * arg) static
Definition at line 3137 of file ffprobe.c.
print_section()
static void print_section (SectionID id, int level) static
Definition at line 3146 of file ffprobe.c.
Referenced by opt_sections().
opt_sections()
static int opt_sections (void * optctx, const char * opt, const char * arg) static
Definition at line 3163 of file ffprobe.c.
opt_show_versions()
static int opt_show_versions (const char * opt, const char * arg) static
Definition at line 3175 of file ffprobe.c.
check_section_show_entries()
static int check_section_show_entries (int section_id) inline static
Definition at line 3244 of file ffprobe.c.
main()
int main (int argc, char ** argv)
Definition at line 3261 of file ffprobe.c.
Variable Documentation
program_name
const char program_name[] = "ffprobe"
program name, defined by the program for show_version().
Definition at line 67 of file ffprobe.c.
Referenced by main(), and show_usage().
program_birth_year
const int program_birth_year = 2007
program birth year, defined by the program for show_banner()
Definition at line 68 of file ffprobe.c.
Referenced by ffprobe_show_program_version().
do_bitexact
int do_bitexact = 0 static
Definition at line 70 of file ffprobe.c.
Referenced by main(), show_format(), and show_stream().
do_count_frames
int do_count_frames = 0 static
Definition at line 71 of file ffprobe.c.
Referenced by probe_file().
do_count_packets
int do_count_packets = 0 static
Definition at line 72 of file ffprobe.c.
Referenced by probe_file().
do_read_frames
int do_read_frames = 0 static
Definition at line 73 of file ffprobe.c.
Referenced by probe_file(), and read_interval_packets().
do_read_packets
int do_read_packets = 0 static
Definition at line 74 of file ffprobe.c.
Referenced by probe_file(), and read_interval_packets().
do_show_chapters
int do_show_chapters = 0 static
Definition at line 75 of file ffprobe.c.
Referenced by main(), and probe_file().
do_show_error
int do_show_error = 0 static
Definition at line 76 of file ffprobe.c.
Referenced by main().
do_show_format
int do_show_format = 0 static
Definition at line 77 of file ffprobe.c.
Referenced by main(), and probe_file().
do_show_frames
int do_show_frames = 0 static
Definition at line 78 of file ffprobe.c.
Referenced by probe_file(), process_frame(), and xml_init().
do_show_packets
int do_show_packets = 0 static
Definition at line 79 of file ffprobe.c.
Referenced by main(), probe_file(), read_interval_packets(), and xml_init().
do_show_programs
int do_show_programs = 0 static
Definition at line 80 of file ffprobe.c.
Referenced by main(), and probe_file().
do_show_streams
int do_show_streams = 0 static
Definition at line 81 of file ffprobe.c.
Referenced by main(), and probe_file().
do_show_stream_disposition
int do_show_stream_disposition = 0 static
Definition at line 82 of file ffprobe.c.
Referenced by show_stream().
do_show_data
int do_show_data = 0 static
Definition at line 83 of file ffprobe.c.
Referenced by show_packet(), and show_stream().
do_show_program_version
int do_show_program_version = 0 static
Definition at line 84 of file ffprobe.c.
Referenced by main().
do_show_library_versions
int do_show_library_versions = 0 static
Definition at line 85 of file ffprobe.c.
Referenced by main().
do_show_pixel_formats
int do_show_pixel_formats = 0 static
Definition at line 86 of file ffprobe.c.
Referenced by main().
do_show_pixel_format_flags
int do_show_pixel_format_flags = 0 static
Definition at line 87 of file ffprobe.c.
Referenced by ffprobe_show_pixel_formats().
do_show_pixel_format_components
int do_show_pixel_format_components = 0 static
Definition at line 88 of file ffprobe.c.
Referenced by ffprobe_show_pixel_formats().
do_show_chapter_tags
int do_show_chapter_tags = 0 static
Definition at line 90 of file ffprobe.c.
Referenced by show_chapters().
do_show_format_tags
int do_show_format_tags = 0 static
Definition at line 91 of file ffprobe.c.
Referenced by show_format().
do_show_frame_tags
int do_show_frame_tags = 0 static
Definition at line 92 of file ffprobe.c.
Referenced by show_frame().
do_show_program_tags
int do_show_program_tags = 0 static
Definition at line 93 of file ffprobe.c.
Referenced by show_program().
do_show_stream_tags
int do_show_stream_tags = 0 static
Definition at line 94 of file ffprobe.c.
Referenced by show_stream().
do_show_packet_tags
int do_show_packet_tags = 0 static
Definition at line 95 of file ffprobe.c.
Referenced by show_packet().
show_value_unit
int show_value_unit = 0 static
Definition at line 97 of file ffprobe.c.
Referenced by opt_pretty(), value_string(), and xml_init().
use_value_prefix
int use_value_prefix = 0 static
Definition at line 98 of file ffprobe.c.
Referenced by opt_pretty(), value_string(), and xml_init().
use_byte_value_binary_prefix
int use_byte_value_binary_prefix = 0 static
Definition at line 99 of file ffprobe.c.
Referenced by opt_pretty(), and value_string().
use_value_sexagesimal_format
int use_value_sexagesimal_format = 0 static
Definition at line 100 of file ffprobe.c.
Referenced by opt_pretty(), and value_string().
show_private_data
int show_private_data = 1 static
Definition at line 101 of file ffprobe.c.
Referenced by show_stream(), and xml_init().
print_format
char* print_format static
Definition at line 103 of file ffprobe.c.
Referenced by main().
stream_specifier
char* stream_specifier static
Definition at line 104 of file ffprobe.c.
Referenced by probe_file().
show_data_hash
char* show_data_hash static
Definition at line 105 of file ffprobe.c.
Referenced by main().
read_intervals
ReadInterval* read_intervals static
Definition at line 115 of file ffprobe.c.
read_intervals_nb
int read_intervals_nb = 0 static
Definition at line 116 of file ffprobe.c.
Referenced by parse_read_intervals(), and read_packets().
sections
struct section sections[] static
Definition at line 182 of file ffprobe.c.
Referenced by writer_open().
options
const OptionDef* options static
Definition at line 228 of file ffprobe.c.
input_filename
const char* input_filename static
Definition at line 231 of file ffprobe.c.
Referenced by main(), and opt_input_file().
iformat
AVInputFormat* iformat = NULL static
Definition at line 232 of file ffprobe.c.
Referenced by ff_alloc_input_device_context(), ff_load_image(), ff_wms_parse_sdp_a_line(), movie_common_init(), show_format_opts(), and stream_open().
hash
struct AVHashContext* hash static
Definition at line 234 of file ffprobe.c.
bin_val
double bin_val
Definition at line 237 of file ffprobe.c.
dec_val
double dec_val
Definition at line 238 of file ffprobe.c.
bin_str
const char* bin_str
Definition at line 239 of file ffprobe.c.
dec_str
const char* dec_str
Definition at line 240 of file ffprobe.c.
si_prefixes
const { ... } si_prefixes[]
Initial value:
= {
    { 1.0, 1.0, "", "" },
    { 1.024e3, 1e3, "Ki", "K" },
    { 1.048576e6, 1e6, "Mi", "M" },
    { 1.073741824e9, 1e9, "Gi", "G" },
    { 1.099511627776e12, 1e12, "Ti", "T" },
    { 1.125899906842624e15, 1e15, "Pi", "P" },
}
Referenced by value_string().
unit_second_str
const char unit_second_str[] = "s" static
Definition at line 250 of file ffprobe.c.
Referenced by value_string(), and writer_print_time().
unit_hertz_str
const char unit_hertz_str[] = "Hz" static
Definition at line 251 of file ffprobe.c.
Referenced by show_stream().
unit_byte_str
const char unit_byte_str[] = "byte" static
Definition at line 252 of file ffprobe.c.
Referenced by show_format(), show_frame(), show_packet(), and value_string().
unit_bit_per_second_str
const char unit_bit_per_second_str[] = "bit/s" static
Definition at line 253 of file ffprobe.c.
Referenced by show_format(), and show_stream().
nb_streams
int nb_streams static
Definition at line 255 of file ffprobe.c.
Referenced by aix_read_header(), asf_read_close(), av_dump_format(), av_find_best_stream(), avi_read_header(), avi_sync(), close_connection(), decode_frame_header(), decode_info_header(), decode_stream_header(), ff_get_wav_header(), ffm_read_header(), ivr_read_header(), libopus_decode_init(), lvf_read_header(), main(), match_streams_one_to_one(), mov_flush_fragment(), mov_write_moov_tag(), movie_common_init(), opt_map(), probe_file(), qt_rtp_parse_packet(), read_interval_packets(), and stream_cycle_channel().
nb_streams_packets
uint64_t* nb_streams_packets static
Definition at line 256 of file ffprobe.c.
Referenced by probe_file(), read_interval_packets(), and show_stream().
nb_streams_frames
uint64_t* nb_streams_frames static
Definition at line 257 of file ffprobe.c.
Referenced by probe_file(), process_frame(), read_interval_packets(), and show_stream().
selected_streams
int* selected_streams static
Definition at line 258 of file ffprobe.c.
Referenced by probe_file(), read_interval_packets(), show_program(), and show_streams().
writer_options
const AVOption writer_options[] static
Initial value:
= {
    { "string_validation", "set string validation mode",
      OFFSET(string_validation), AV_OPT_TYPE_INT, {.i64=WRITER_STRING_VALIDATION_REPLACE}, 0, WRITER_STRING_VALIDATION_NB-1, .unit = "sv" },
    { "sv", "set string validation mode",
      OFFSET(string_validation), AV_OPT_TYPE_INT, {.i64=WRITER_STRING_VALIDATION_REPLACE}, 0, WRITER_STRING_VALIDATION_NB-1, .unit = "sv" },
    { "ignore",  NULL, 0, AV_OPT_TYPE_CONST, {.i64 = WRITER_STRING_VALIDATION_IGNORE},  .unit = "sv" },
    { "replace", NULL, 0, AV_OPT_TYPE_CONST, {.i64 = WRITER_STRING_VALIDATION_REPLACE}, .unit = "sv" },
    { "fail",    NULL, 0, AV_OPT_TYPE_CONST, {.i64 = WRITER_STRING_VALIDATION_FAIL},    .unit = "sv" },
    { "string_validation_replacement", "set string validation replacement string", OFFSET(string_validation_replacement), AV_OPT_TYPE_STRING, {.str=""}},
    { "svr", "set string validation replacement string", OFFSET(string_validation_replacement), AV_OPT_TYPE_STRING, {.str="\xEF\xBF\xBD"}},
    { NULL }
}
Definition at line 393 of file ffprobe.c.
writer_class
const AVClass writer_class static
Initial value:
= {
    .class_name = "Writer",
    .item_name  = writer_get_name,
    .option     = writer_options,
    .version    = LIBAVUTIL_VERSION_INT,
    .child_next = writer_child_next,
}
Definition at line 414 of file ffprobe.c.
Referenced by writer_open().
registered_writers
const Writer* registered_writers[MAX_REGISTERED_WRITERS_NB+1] static
Definition at line 788 of file ffprobe.c.
default_options
const AVOption default_options[] static
Initial value:
= {
    { "noprint_wrappers", "do not print headers and footers", OFFSET(noprint_wrappers), AV_OPT_TYPE_BOOL, {.i64=0}, 0, 1 },
    { "nw",               "do not print headers and footers", OFFSET(noprint_wrappers), AV_OPT_TYPE_BOOL, {.i64=0}, 0, 1 },
    { "nokey",          "force no key printing",     OFFSET(nokey),          AV_OPT_TYPE_BOOL, {.i64=0}, 0, 1 },
    { "nk",             "force no key printing",     OFFSET(nokey),          AV_OPT_TYPE_BOOL, {.i64=0}, 0, 1 },
    {NULL},
}
Definition at line 838 of file ffprobe.c.
default_writer
const Writer default_writer static
Initial value:
= {
    .name                  = "default",
    .priv_size             = sizeof(DefaultContext),
    .print_section_header  = default_print_section_header,
    .print_section_footer  = default_print_section_footer,
    .print_integer         = default_print_int,
    .print_string          = default_print_str,
    .flags = WRITER_FLAG_DISPLAY_OPTIONAL_FIELDS,
    .priv_class            = &default_class,
}
Definition at line 914 of file ffprobe.c.
compact_options
const AVOption compact_options[] static
Initial value:
= {
    {"item_sep", "set item separator",    OFFSET(item_sep_str),    AV_OPT_TYPE_STRING, {.str="|"},  CHAR_MIN, CHAR_MAX },
    {"s",        "set item separator",    OFFSET(item_sep_str),    AV_OPT_TYPE_STRING, {.str="|"},  CHAR_MIN, CHAR_MAX },
    {"nokey",    "force no key printing", OFFSET(nokey),           AV_OPT_TYPE_BOOL,   {.i64=0},    0,        1        },
    {"nk",       "force no key printing", OFFSET(nokey),           AV_OPT_TYPE_BOOL,   {.i64=0},    0,        1        },
    {"escape",   "set escape mode",       OFFSET(escape_mode_str), AV_OPT_TYPE_STRING, {.str="c"},  CHAR_MIN, CHAR_MAX },
    {"e",        "set escape mode",       OFFSET(escape_mode_str), AV_OPT_TYPE_STRING, {.str="c"},  CHAR_MIN, CHAR_MAX },
    {"print_section", "print section name", OFFSET(print_section), AV_OPT_TYPE_BOOL,   {.i64=1},    0,        1        },
    {"p",             "print section name", OFFSET(print_section), AV_OPT_TYPE_BOOL,   {.i64=1},    0,        1        },
    {NULL},
}
Definition at line 992 of file ffprobe.c.
compact_writer
const Writer compact_writer static
Initial value:
= {
    .name                 = "compact",
    .priv_size            = sizeof(CompactContext),
    .init                 = compact_init,
    .print_section_header = compact_print_section_header,
    .print_section_footer = compact_print_section_footer,
    .print_integer        = compact_print_int,
    .print_string         = compact_print_str,
    .flags = WRITER_FLAG_DISPLAY_OPTIONAL_FIELDS,
    .priv_class           = &compact_class,
}
Definition at line 1091 of file ffprobe.c.
csv_options
const AVOption csv_options[] static
Initial value:
= {
    {"item_sep", "set item separator",    OFFSET(item_sep_str),    AV_OPT_TYPE_STRING, {.str=","},  CHAR_MIN, CHAR_MAX },
    {"s",        "set item separator",    OFFSET(item_sep_str),    AV_OPT_TYPE_STRING, {.str=","},  CHAR_MIN, CHAR_MAX },
    {"nokey",    "force no key printing", OFFSET(nokey),           AV_OPT_TYPE_BOOL,   {.i64=1},    0,        1        },
    {"nk",       "force no key printing", OFFSET(nokey),           AV_OPT_TYPE_BOOL,   {.i64=1},    0,        1        },
    {"escape",   "set escape mode",       OFFSET(escape_mode_str), AV_OPT_TYPE_STRING, {.str="csv"}, CHAR_MIN, CHAR_MAX },
    {"e",        "set escape mode",       OFFSET(escape_mode_str), AV_OPT_TYPE_STRING, {.str="csv"}, CHAR_MIN, CHAR_MAX },
    {"print_section", "print section name", OFFSET(print_section), AV_OPT_TYPE_BOOL,   {.i64=1},    0,        1        },
    {"p",             "print section name", OFFSET(print_section), AV_OPT_TYPE_BOOL,   {.i64=1},    0,        1        },
    {NULL},
}
Definition at line 1108 of file ffprobe.c.
csv_writer
const Writer csv_writer static
Initial value:
= {
    .name                 = "csv",
    .priv_size            = sizeof(CompactContext),
    .init                 = compact_init,
    .print_section_header = compact_print_section_header,
    .print_section_footer = compact_print_section_footer,
    .print_integer        = compact_print_int,
    .print_string         = compact_print_str,
    .flags = WRITER_FLAG_DISPLAY_OPTIONAL_FIELDS,
    .priv_class           = &csv_class,
}
Definition at line 1122 of file ffprobe.c.
flat_options
const AVOption flat_options[] static
Initial value:
= {
    {"sep_char", "set separator",    OFFSET(sep_str),    AV_OPT_TYPE_STRING, {.str="."},  CHAR_MIN, CHAR_MAX },
    {"s",        "set separator",    OFFSET(sep_str),    AV_OPT_TYPE_STRING, {.str="."},  CHAR_MIN, CHAR_MAX },
    {"hierarchical", "specify if the section specification should be hierarchical", OFFSET(hierarchical), AV_OPT_TYPE_BOOL, {.i64=1}, 0, 1 },
    {"h",            "specify if the section specification should be hierarchical", OFFSET(hierarchical), AV_OPT_TYPE_BOOL, {.i64=1}, 0, 1 },
    {NULL},
}
Definition at line 1146 of file ffprobe.c.
flat_writer
const Writer flat_writer static
Initial value:
= {
    .name                  = "flat",
    .priv_size             = sizeof(FlatContext),
    .init                  = flat_init,
    .print_section_header  = flat_print_section_header,
    .print_integer         = flat_print_int,
    .print_string          = flat_print_str,
    .flags = WRITER_FLAG_DISPLAY_OPTIONAL_FIELDS|WRITER_FLAG_PUT_PACKETS_AND_FRAMES_IN_SAME_CHAPTER,
    .priv_class            = &flat_class,
}
Definition at line 1247 of file ffprobe.c.
ini_options
const AVOption ini_options[] static
Initial value:
= {
    {"hierarchical", "specify if the section specification should be hierarchical", OFFSET(hierarchical), AV_OPT_TYPE_BOOL, {.i64=1}, 0, 1 },
    {"h",            "specify if the section specification should be hierarchical", OFFSET(hierarchical), AV_OPT_TYPE_BOOL, {.i64=1}, 0, 1 },
    {NULL},
}
Definition at line 1268 of file ffprobe.c.
ini_writer
const Writer ini_writer static
Initial value:
= {
    .name                  = "ini",
    .priv_size             = sizeof(INIContext),
    .print_section_header  = ini_print_section_header,
    .print_integer         = ini_print_int,
    .print_string          = ini_print_str,
    .flags = WRITER_FLAG_DISPLAY_OPTIONAL_FIELDS|WRITER_FLAG_PUT_PACKETS_AND_FRAMES_IN_SAME_CHAPTER,
    .priv_class            = &ini_class,
}
Definition at line 1352 of file ffprobe.c.
json_options
const AVOption json_options[] static
Initial value:
= {
    { "compact", "enable compact output", OFFSET(compact), AV_OPT_TYPE_BOOL, {.i64=0}, 0, 1 },
    { "c",       "enable compact output", OFFSET(compact), AV_OPT_TYPE_BOOL, {.i64=0}, 0, 1 },
    { NULL }
}
Definition at line 1374 of file ffprobe.c.
json_writer
const Writer json_writer static
Initial value:
= {
    .name                 = "json",
    .priv_size            = sizeof(JSONContext),
    .init                 = json_init,
    .print_section_header = json_print_section_header,
    .print_section_footer = json_print_section_footer,
    .print_integer        = json_print_int,
    .print_string         = json_print_str,
    .flags = WRITER_FLAG_PUT_PACKETS_AND_FRAMES_IN_SAME_CHAPTER,
    .priv_class           = &json_class,
}
Definition at line 1512 of file ffprobe.c.
xml_options
const AVOption xml_options[] static
Initial value:
= {
    {"fully_qualified", "specify if the output should be fully qualified", OFFSET(fully_qualified), AV_OPT_TYPE_BOOL, {.i64=0},  0, 1 },
    {"q",               "specify if the output should be fully qualified", OFFSET(fully_qualified), AV_OPT_TYPE_BOOL, {.i64=0},  0, 1 },
    {"xsd_strict",      "ensure that the output is XSD compliant",         OFFSET(xsd_strict),      AV_OPT_TYPE_BOOL, {.i64=0},  0, 1 },
    {"x",               "ensure that the output is XSD compliant",         OFFSET(xsd_strict),      AV_OPT_TYPE_BOOL, {.i64=0},  0, 1 },
    {NULL},
}
Definition at line 1537 of file ffprobe.c.
xml_writer
Writer xml_writer static
Initial value:
= {
    .name                 = "xml",
    .priv_size            = sizeof(XMLContext),
    .init                 = xml_init,
    .print_section_header = xml_print_section_header,
    .print_section_footer = xml_print_section_footer,
    .print_integer        = xml_print_int,
    .print_string         = xml_print_str,
    .flags = WRITER_FLAG_PUT_PACKETS_AND_FRAMES_IN_SAME_CHAPTER,
    .priv_class           = &xml_class,
}
Definition at line 1684 of file ffprobe.c.
real_options
const OptionDef real_options[] static
Definition at line 3200 of file ffprobe.c.
Referenced by main().