FFmpeg: ffserver_config.h File Reference
ffserver_config.h File Reference
#include "libavutil/dict.h"
#include "libavformat/avformat.h"
#include "libavformat/network.h"
Data Structures
struct FFServerIPAddressACL
struct LayeredAVStream
This holds the stream parameters for an AVStream, it cannot be a AVStream because AVStreams cannot be instanciated without a AVFormatContext, especially not outside libavformat.
struct FFServerStream
struct FFServerConfig
Macros
#define FFM_PACKET_SIZE 4096
#define FFSERVER_MAX_STREAMS 20
Enumerations
enum FFServerStreamType { STREAM_TYPE_LIVE, STREAM_TYPE_STATUS, STREAM_TYPE_REDIRECT }
enum FFServerIPAddressAction { IP_ALLOW = 1, IP_DENY }
Functions
void ffserver_get_arg (char *buf, int buf_size, const char **pp)
void ffserver_parse_acl_row (FFServerStream *stream, FFServerStream *feed, FFServerIPAddressACL *ext_acl, const char *p, const char *filename, int line_num)
int ffserver_parse_ffconfig (const char *filename, FFServerConfig *config)
void ffserver_free_child_args (void *argsp)
Macro Definition Documentation
FFM_PACKET_SIZE
#define FFM_PACKET_SIZE 4096
Definition at line 24 of file ffserver_config.h.
Referenced by adjust_write_index(), build_feed_streams(), ffm2_read_header(), ffm_is_avail_data(), ffm_read_header(), ffm_seek(), ffm_seek1(), ffm_write_header(), ffserver_parse_config_feed(), http_receive_data(), http_start_receive_data(), and open_input_stream().
FFSERVER_MAX_STREAMS
#define FFSERVER_MAX_STREAMS 20
Definition at line 30 of file ffserver_config.h.
Enumeration Type Documentation
FFServerStreamType
enum FFServerStreamType
Enumerator
STREAM_TYPE_LIVE
STREAM_TYPE_STATUS
STREAM_TYPE_REDIRECT
Definition at line 33 of file ffserver_config.h.
FFServerIPAddressAction
enum FFServerIPAddressAction
Enumerator
IP_ALLOW
IP_DENY
Definition at line 39 of file ffserver_config.h.
Function Documentation
ffserver_get_arg()
void ffserver_get_arg (char * buf, int buf_size, const char ** pp)
Definition at line 82 of file ffserver_config.c.
Referenced by ffserver_parse_acl_row(), ffserver_parse_config_feed(), ffserver_parse_config_global(), ffserver_parse_config_redirect(), ffserver_parse_config_stream(), ffserver_parse_ffconfig(), and parse_dynamic_acl().
ffserver_parse_acl_row()
void ffserver_parse_acl_row (FFServerStream * stream, FFServerStream * feed, FFServerIPAddressACL * ext_acl, const char * p, const char * filename, int line_num)
Definition at line 110 of file ffserver_config.c.
Referenced by ffserver_parse_config_feed(), ffserver_parse_config_stream(), and parse_dynamic_acl().
ffserver_parse_ffconfig()
int ffserver_parse_ffconfig (const char * filename, FFServerConfig * config)
Definition at line 1210 of file ffserver_config.c.
Referenced by main().
ffserver_free_child_args()
void ffserver_free_child_args (void * argsp)
Definition at line 1313 of file ffserver_config.c.
Referenced by handle_child_exit().