FFmpeg: ffserver_config.c File Reference
ffserver_config.c File Reference
#include <float.h>
#include "libavutil/opt.h"
#include "libavutil/parseutils.h"
#include "libavutil/avstring.h"
#include "libavutil/pixdesc.h"
#include "libavutil/avassert.h"
#include "cmdutils.h"
#include "ffserver_config.h"
Macros
#define MAX_CHILD_ARGS 64
#define ERROR(...)
#define WARNING(...)
Functions
static int ffserver_save_avoption (const char *opt, const char *arg, int type, FFServerConfig *config)
static void vreport_config_error (const char *filename, int line_num, int log_level, int *errors, const char *fmt, va_list vl)
static void report_config_error (const char *filename, int line_num, int log_level, int *errors, const char *fmt,...)
static int resolve_host (struct in_addr *sin_addr, const char *hostname)
void ffserver_get_arg (char *buf, int buf_size, const char **pp)
void ffserver_parse_acl_row (FFServerStream *stream, FFServerStream *feed, FFServerIPAddressACL *ext_acl, const char *p, const char *filename, int line_num)
static void add_codec (FFServerStream *stream, AVCodecContext *av, FFServerConfig *config)
static int ffserver_set_codec (AVCodecContext *ctx, const char *codec_name, FFServerConfig *config)
static int ffserver_opt_preset (const char *arg, int type, FFServerConfig *config)
static AVOutputFormat * ffserver_guess_format (const char *short_name, const char *filename, const char *mime_type)
static int ffserver_set_int_param (int *dest, const char *value, int factor, int min, int max, FFServerConfig *config, const char *error_msg,...)
static int ffserver_set_float_param (float *dest, const char *value, float factor, float min, float max, FFServerConfig *config, const char *error_msg,...)
static int ffserver_save_avoption_int (const char *opt, int64_t arg, int type, FFServerConfig *config)
static int ffserver_parse_config_global (FFServerConfig *config, const char *cmd, const char **p)
static int ffserver_parse_config_feed (FFServerConfig *config, const char *cmd, const char **p, FFServerStream **pfeed)
static int ffserver_parse_config_stream (FFServerConfig *config, const char *cmd, const char **p, FFServerStream **pstream)
static int ffserver_parse_config_redirect (FFServerConfig *config, const char *cmd, const char **p, FFServerStream **predirect)
int ffserver_parse_ffconfig (const char *filename, FFServerConfig *config)
void ffserver_free_child_args (void *argsp)
Macro Definition Documentation
MAX_CHILD_ARGS
#define MAX_CHILD_ARGS 64
Definition at line 31 of file ffserver_config.c.
Referenced by ffserver_free_child_args(), and ffserver_parse_config_feed().
ERROR
#define ERROR (...)
Value:
report_config_error(config->filename, config->line_num,\
                                       AV_LOG_ERROR, &config->errors, __VA_ARGS__)
Definition at line 42 of file ffserver_config.c.
Referenced by ffserver_parse_config_feed(), ffserver_parse_config_global(), ffserver_parse_config_redirect(), ffserver_parse_config_stream(), ffserver_parse_ffconfig(), and main().
WARNING
#define WARNING (...)
Value:
report_config_error(config->filename, config->line_num,\
                                         AV_LOG_WARNING, &config->warnings, __VA_ARGS__)
Definition at line 44 of file ffserver_config.c.
Referenced by add_codec(), ffserver_parse_config_feed(), ffserver_parse_config_global(), and ffserver_parse_config_stream().
Function Documentation
ffserver_save_avoption()
static int ffserver_save_avoption (const char * opt, const char * arg, int type, FFServerConfig * config) static
Definition at line 518 of file ffserver_config.c.
Referenced by ffserver_opt_preset(), ffserver_parse_config_stream(), and ffserver_save_avoption_int().
vreport_config_error()
static void vreport_config_error (const char * filename, int line_num, int log_level, int * errors, const char * fmt, va_list vl) static
Definition at line 434 of file ffserver_config.c.
Referenced by ffserver_set_float_param(), ffserver_set_int_param(), and report_config_error().
report_config_error()
static void report_config_error (const char * filename, int line_num, int log_level, int * errors, const char * fmt, ...) static
Definition at line 444 of file ffserver_config.c.
Referenced by add_codec(), ffserver_save_avoption(), and ffserver_set_codec().
resolve_host()
static int resolve_host (struct in_addr * sin_addr, const char * hostname) static
Definition at line 49 of file ffserver_config.c.
Referenced by ffserver_parse_acl_row(), ffserver_parse_config_global(), and ffserver_parse_config_stream().
ffserver_get_arg()
void ffserver_get_arg (char * buf, int buf_size, const char ** pp)
Definition at line 82 of file ffserver_config.c.
Referenced by ffserver_parse_acl_row(), ffserver_parse_config_feed(), ffserver_parse_config_global(), ffserver_parse_config_redirect(), ffserver_parse_config_stream(), ffserver_parse_ffconfig(), and parse_dynamic_acl().
ffserver_parse_acl_row()
void ffserver_parse_acl_row (FFServerStream * stream, FFServerStream * feed, FFServerIPAddressACL * ext_acl, const char * p, const char * filename, int line_num)
Definition at line 110 of file ffserver_config.c.
Referenced by ffserver_parse_config_feed(), ffserver_parse_config_stream(), and parse_dynamic_acl().
add_codec()
static void add_codec (FFServerStream * stream, AVCodecContext * av, FFServerConfig * config) static
Definition at line 187 of file ffserver_config.c.
Referenced by ffserver_parse_config_stream().
ffserver_set_codec()
static int ffserver_set_codec (AVCodecContext * ctx, const char * codec_name, FFServerConfig * config) static
Definition at line 333 of file ffserver_config.c.
Referenced by ffserver_opt_preset(), ffserver_parse_config_stream(), and ffserver_save_avoption().
ffserver_opt_preset()
static int ffserver_opt_preset (const char * arg, int type, FFServerConfig * config) static
Definition at line 358 of file ffserver_config.c.
Referenced by ffserver_parse_config_stream().
ffserver_guess_format()
static AVOutputFormat* ffserver_guess_format (const char * short_name, const char * filename, const char * mime_type) static
Definition at line 413 of file ffserver_config.c.
Referenced by ffserver_parse_config_stream().
ffserver_set_int_param()
static int ffserver_set_int_param (int * dest, const char * value, int factor, int min, int max, FFServerConfig * config, const char * error_msg, ...) static
Definition at line 454 of file ffserver_config.c.
Referenced by ffserver_parse_config_global(), and ffserver_parse_config_stream().
ffserver_set_float_param()
static int ffserver_set_float_param (float * dest, const char * value, float factor, float min, float max, FFServerConfig * config, const char * error_msg, ...) static
Definition at line 487 of file ffserver_config.c.
Referenced by ffserver_parse_config_stream().
ffserver_save_avoption_int()
static int ffserver_save_avoption_int (const char * opt, int64_t arg, int type, FFServerConfig * config) static
Definition at line 605 of file ffserver_config.c.
Referenced by ffserver_parse_config_stream().
ffserver_parse_config_global()
static int ffserver_parse_config_global (FFServerConfig * config, const char * cmd, const char ** p) static
Definition at line 613 of file ffserver_config.c.
Referenced by ffserver_parse_ffconfig().
ffserver_parse_config_feed()
static int ffserver_parse_config_feed (FFServerConfig * config, const char * cmd, const char ** p, FFServerStream ** pfeed) static
Definition at line 692 of file ffserver_config.c.
Referenced by ffserver_parse_ffconfig().
ffserver_parse_config_stream()
static int ffserver_parse_config_stream (FFServerConfig * config, const char * cmd, const char ** p, FFServerStream ** pstream) static
Definition at line 800 of file ffserver_config.c.
Referenced by ffserver_parse_ffconfig().
ffserver_parse_config_redirect()
static int ffserver_parse_config_redirect (FFServerConfig * config, const char * cmd, const char ** p, FFServerStream ** predirect) static
Definition at line 1174 of file ffserver_config.c.
Referenced by ffserver_parse_ffconfig().
ffserver_parse_ffconfig()
int ffserver_parse_ffconfig (const char * filename, FFServerConfig * config)
Definition at line 1210 of file ffserver_config.c.
Referenced by main().
ffserver_free_child_args()
void ffserver_free_child_args (void * argsp)
Definition at line 1313 of file ffserver_config.c.
Referenced by handle_child_exit().