FFmpeg: libavcodec/arm/fft_fixed_init_arm.c File Reference
fft_fixed_init_arm.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/arm/cpu.h"
#include "libavcodec/fft.h"
Macros
#define FFT_FLOAT 0
Functions
void ff_fft_fixed_calc_neon (FFTContext *s, FFTComplex *z)
void ff_mdct_fixed_calc_neon (FFTContext *s, FFTSample *o, const FFTSample *i)
void ff_mdct_fixed_calcw_neon (FFTContext *s, FFTDouble *o, const FFTSample *i)
av_cold void ff_fft_fixed_init_arm (FFTContext *s)
Macro Definition Documentation
FFT_FLOAT
#define FFT_FLOAT 0
Definition at line 25 of file fft_fixed_init_arm.c.
Function Documentation
ff_fft_fixed_calc_neon()
void ff_fft_fixed_calc_neon (FFTContext * s, FFTComplex * z)
Referenced by ff_fft_fixed_init_arm().
ff_mdct_fixed_calc_neon()
void ff_mdct_fixed_calc_neon (FFTContext * s, FFTSample * o, const FFTSample * i)
Referenced by ff_fft_fixed_init_arm().
ff_mdct_fixed_calcw_neon()
void ff_mdct_fixed_calcw_neon (FFTContext * s, FFTDouble * o, const FFTSample * i)
Referenced by ff_fft_fixed_init_arm().
ff_fft_fixed_init_arm()
av_cold void ff_fft_fixed_init_arm (FFTContext * s)
Definition at line 32 of file fft_fixed_init_arm.c.
Referenced by ff_fft_init().