FFmpeg: libavcodec/fft_table.h File Reference
fft_table.h File Reference
definitions and tables for FFT
#include "libavcodec/fft.h"
Macros
#define MAX_LOG2_NFFT 17
Specifies maximum allowed fft size.
#define MAX_FFT_SIZE (1 << MAX_LOG2_NFFT)
Functions
void ff_fft_lut_init (uint16_t *table, int off, int size, int *index)
Variables
const int32_t ff_w_tab_sr []
uint16_t ff_fft_offsets_lut []
Detailed Description
definitions and tables for FFT
Definition in file fft_table.h.
Macro Definition Documentation
MAX_LOG2_NFFT
#define MAX_LOG2_NFFT 17
Specifies maximum allowed fft size.
Definition at line 59 of file fft_table.h.
Referenced by ff_fft_end().
MAX_FFT_SIZE
#define MAX_FFT_SIZE (1 << MAX_LOG2_NFFT)
Definition at line 60 of file fft_table.h.
Referenced by ff_fft_end().
Function Documentation
ff_fft_lut_init()
void ff_fft_lut_init (uint16_t * table, int off, int size, int * index)
Definition at line 317 of file fft_init_table.c.
Referenced by ff_fft_init(), ff_fft_init_mips(), and ff_fft_lut_init().
Variable Documentation
ff_w_tab_sr
const int32_t ff_w_tab_sr[]
Definition at line 56 of file fft_init_table.c.
Referenced by ff_fft_end().
ff_fft_offsets_lut
uint16_t ff_fft_offsets_lut[]
Definition at line 315 of file fft_init_table.c.
Referenced by ff_fft_end(), ff_fft_init(), and ff_fft_init_mips().