FFmpeg: libavcodec/aarch64/fft_init_aarch64.c File Reference
fft_init_aarch64.c File Reference
#include "config.h"
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/aarch64/cpu.h"
#include "libavcodec/fft.h"
Functions
void ff_fft_permute_neon (FFTContext *s, FFTComplex *z)
void ff_fft_calc_neon (FFTContext *s, FFTComplex *z)
void ff_imdct_calc_neon (FFTContext *s, FFTSample *output, const FFTSample *input)
void ff_imdct_half_neon (FFTContext *s, FFTSample *output, const FFTSample *input)
void ff_mdct_calc_neon (FFTContext *s, FFTSample *output, const FFTSample *input)
av_cold void ff_fft_init_aarch64 (FFTContext *s)
Function Documentation
ff_fft_permute_neon()
void ff_fft_permute_neon (FFTContext * s, FFTComplex * z)
Referenced by ff_fft_init_aarch64().
ff_fft_calc_neon()
void ff_fft_calc_neon (FFTContext * s, FFTComplex * z)
Referenced by ff_fft_init_aarch64().
ff_imdct_calc_neon()
void ff_imdct_calc_neon (FFTContext * s, FFTSample * output, const FFTSample * input)
Referenced by ff_fft_init_aarch64().
ff_imdct_half_neon()
void ff_imdct_half_neon (FFTContext * s, FFTSample * output, const FFTSample * input)
Referenced by ff_fft_init_aarch64().
ff_mdct_calc_neon()
void ff_mdct_calc_neon (FFTContext * s, FFTSample * output, const FFTSample * input)
Referenced by ff_fft_init_aarch64().
ff_fft_init_aarch64()
av_cold void ff_fft_init_aarch64 (FFTContext * s)
Definition at line 36 of file fft_init_aarch64.c.
Referenced by ff_fft_init().