FFmpeg: libavcodec/ffv1.c File Reference
ffv1.c File Reference
FF Video Codec 1 (a lossless codec)
#include "libavutil/attributes.h"
#include "libavutil/avassert.h"
#include "libavutil/crc.h"
#include "libavutil/opt.h"
#include "libavutil/imgutils.h"
#include "libavutil/pixdesc.h"
#include "libavutil/timer.h"
#include "avcodec.h"
#include "internal.h"
#include "rangecoder.h"
#include "mathops.h"
#include "ffv1.h"
Functions
av_cold int ff_ffv1_common_init (AVCodecContext *avctx)
av_cold int ff_ffv1_init_slice_state (FFV1Context *f, FFV1Context *fs)
av_cold int ff_ffv1_init_slices_state (FFV1Context *f)
av_cold int ff_ffv1_init_slice_contexts (FFV1Context *f)
int ff_ffv1_allocate_initial_states (FFV1Context *f)
void ff_ffv1_clear_slice_state (FFV1Context *f, FFV1Context *fs)
av_cold int ff_ffv1_close (AVCodecContext *avctx)
Detailed Description
FF Video Codec 1 (a lossless codec)
Definition in file ffv1.c.
Function Documentation
ff_ffv1_common_init()
av_cold int ff_ffv1_common_init (AVCodecContext * avctx)
Definition at line 42 of file ffv1.c.
Referenced by decode_init(), and encode_init().
ff_ffv1_init_slice_state()
av_cold int ff_ffv1_init_slice_state (FFV1Context * f, FFV1Context * fs)
Definition at line 67 of file ffv1.c.
Referenced by decode_slice(), and ff_ffv1_init_slices_state().
ff_ffv1_init_slices_state()
av_cold int ff_ffv1_init_slices_state (FFV1Context * f)
Definition at line 106 of file ffv1.c.
Referenced by encode_init().
ff_ffv1_init_slice_contexts()
av_cold int ff_ffv1_init_slice_contexts (FFV1Context * f)
Definition at line 117 of file ffv1.c.
Referenced by decode_frame(), decode_init(), and encode_init().
ff_ffv1_allocate_initial_states()
int ff_ffv1_allocate_initial_states (FFV1Context * f)
Definition at line 167 of file ffv1.c.
Referenced by encode_init(), and read_extra_header().
ff_ffv1_clear_slice_state()
void ff_ffv1_clear_slice_state (FFV1Context * f, FFV1Context * fs)
Definition at line 182 of file ffv1.c.
Referenced by decode_slice(), encode_slice(), and encode_slice_header().
ff_ffv1_close()
av_cold int ff_ffv1_close (AVCodecContext * avctx)
Definition at line 210 of file ffv1.c.
Referenced by encode_close().