FFmpeg: libavcodec/ffv1dec.c File Reference
ffv1dec.c File Reference
FF Video Codec 1 (a lossless codec) decoder.
#include "libavutil/avassert.h"
#include "libavutil/crc.h"
#include "libavutil/opt.h"
#include "libavutil/imgutils.h"
#include "libavutil/pixdesc.h"
#include "libavutil/timer.h"
#include "avcodec.h"
#include "internal.h"
#include "get_bits.h"
#include "rangecoder.h"
#include "golomb.h"
#include "mathops.h"
#include "ffv1.h"
#include "ffv1dec_template.c"
Macros
#define TYPE int16_t
#define RENAME(name) name
#define TYPE int32_t
#define RENAME(name) name ## 32
Functions
static av_flatten int get_symbol_inline (RangeCoder *c, uint8_t *state, int is_signed)
static av_noinline int get_symbol (RangeCoder *c, uint8_t *state, int is_signed)
static int get_vlc_symbol (GetBitContext *gb, VlcState *const state, int bits)
static void decode_plane (FFV1Context *s, uint8_t *src, int w, int h, int stride, int plane_index, int pixel_stride)
static int decode_slice_header (FFV1Context *f, FFV1Context *fs)
static int decode_slice (AVCodecContext *c, void *arg)
static int read_quant_table (RangeCoder *c, int16_t *quant_table, int scale)
static int read_quant_tables (RangeCoder *c, int16_t quant_table[MAX_CONTEXT_INPUTS][256])
static int read_extra_header (FFV1Context *f)
static int read_header (FFV1Context *f)
static av_cold int decode_init (AVCodecContext *avctx)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static void copy_fields (FFV1Context *fsdst, FFV1Context *fssrc, FFV1Context *fsrc)
Variables
AVCodec ff_ffv1_decoder
Detailed Description
FF Video Codec 1 (a lossless codec) decoder.
Definition in file ffv1dec.c.
Macro Definition Documentation
TYPE [1/2]
#define TYPE int16_t
Definition at line 106 of file ffv1dec.c.
RENAME [1/2]
#define RENAME (name) name
Definition at line 107 of file ffv1dec.c.
TYPE [2/2]
#define TYPE int32_t
Definition at line 106 of file ffv1dec.c.
RENAME [2/2]
#define RENAME (name) name ## 32
Definition at line 107 of file ffv1dec.c.
Function Documentation
get_symbol_inline()
static av_flatten int get_symbol_inline (RangeCoder * c, uint8_t * state, int is_signed) inline static
Definition at line 42 of file ffv1dec.c.
Referenced by decode_line(), and get_symbol().
get_symbol()
static av_noinline int get_symbol (RangeCoder * c, uint8_t * state, int is_signed) static
Definition at line 65 of file ffv1dec.c.
Referenced by decode_header(), decode_q_branch(), decode_qlogs(), decode_slice_header(), read_extra_header(), read_header(), and read_quant_table().
get_vlc_symbol()
static int get_vlc_symbol (GetBitContext * gb, VlcState *const state, int bits) inline static
Definition at line 70 of file ffv1dec.c.
Referenced by decode_line().
decode_plane()
static void decode_plane (FFV1Context * s, uint8_t * src, int w, int h, int stride, int plane_index, int pixel_stride) static
Definition at line 110 of file ffv1dec.c.
Referenced by decode_slice().
decode_slice_header()
static int decode_slice_header (FFV1Context * f, FFV1Context * fs) static
Definition at line 153 of file ffv1dec.c.
Referenced by decode_slice().
decode_slice()
static int decode_slice (AVCodecContext * c, void * arg) static
Definition at line 232 of file ffv1dec.c.
Referenced by decode_frame(), and dxtory_decode_v2().
read_quant_table()
static int read_quant_table (RangeCoder * c, int16_t * quant_table, int scale) static
Definition at line 352 of file ffv1dec.c.
Referenced by read_quant_tables().
read_quant_tables()
static int read_quant_tables (RangeCoder * c, int16_t quant_table[MAX_CONTEXT_INPUTS][256]) static
Definition at line 379 of file ffv1dec.c.
Referenced by read_extra_header(), and read_header().
read_extra_header()
static int read_extra_header (FFV1Context * f) static
Definition at line 397 of file ffv1dec.c.
Referenced by decode_init().
read_header()
static int read_header (FFV1Context * f) static
Definition at line 514 of file ffv1dec.c.
Referenced by amr_read_packet(), decode_frame(), ff_rtsp_open_transport_ctx(), mjpegb_decode_frame(), mmf_read_packet(), and set_spdif().
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 776 of file ffv1dec.c.
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 795 of file ffv1dec.c.
copy_fields()
static void copy_fields (FFV1Context * fsdst, FFV1Context * fssrc, FFV1Context * fsrc) static
Definition at line 965 of file ffv1dec.c.
Variable Documentation
ff_ffv1_decoder
AVCodec ff_ffv1_decoder
Initial value:
= {
    .name           = "ffv1",
    .long_name      = NULL_IF_CONFIG_SMALL("FFmpeg video codec #1"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_FFV1,
    .priv_data_size = sizeof(FFV1Context),
    .init           = decode_init,
    .close          = ff_ffv1_close,
    .decode         = decode_frame,
    .init_thread_copy = ONLY_IF_THREADS_ENABLED(init_thread_copy),
    .update_thread_context = ONLY_IF_THREADS_ENABLED(update_thread_context),
    .capabilities   = AV_CODEC_CAP_DR1  |
                      AV_CODEC_CAP_FRAME_THREADS | AV_CODEC_CAP_SLICE_THREADS,
    .caps_internal  = FF_CODEC_CAP_INIT_CLEANUP
}
Definition at line 1039 of file ffv1dec.c.