FFmpeg: libavcodec/ffv1enc_template.c File Reference
ffv1enc_template.c File Reference
Functions
static av_always_inline int RENAME() encode_line (FFV1Context *s, int w, TYPE *sample[3], int plane_index, int bits)
static int RENAME() encode_rgb_frame (FFV1Context *s, const uint8_t *src[3], int w, int h, const int stride[3])
Function Documentation
encode_line()
static av_always_inline int RENAME() encode_line (FFV1Context * s, int w, TYPE * sample[3], int plane_index, int bits) static
Definition at line 23 of file ffv1enc_template.c.
Referenced by encode_plane(), and encode_rgb_frame().
encode_rgb_frame()
static int RENAME() encode_rgb_frame (FFV1Context * s, const uint8_t * src[3], int w, int h, const int stride[3]) static
Definition at line 125 of file ffv1enc_template.c.
Referenced by encode_slice().