FFmpeg: libavcodec/fic.c File Reference
fic.c File Reference
#include "libavutil/common.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "internal.h"
#include "get_bits.h"
#include "golomb.h"
Data Structures
struct FICThreadContext
struct FICContext
Macros
#define FIC_HEADER_SIZE 27
Functions
static av_always_inline void fic_idct (int16_t *blk, int step, int shift, int rnd)
static void fic_idct_put (uint8_t *dst, int stride, int16_t *block)
static int fic_decode_block (FICContext *ctx, GetBitContext *gb, uint8_t *dst, int stride, int16_t *block)
static int fic_decode_slice (AVCodecContext *avctx, void *tdata)
static av_always_inline void fic_alpha_blend (uint8_t *dst, uint8_t *src, int size, uint8_t *alpha)
static void fic_draw_cursor (AVCodecContext *avctx, int cur_x, int cur_y)
static int fic_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int fic_decode_close (AVCodecContext *avctx)
static av_cold int fic_decode_init (AVCodecContext *avctx)
Variables
static const uint8_t fic_qmat_hq [64]
static const uint8_t fic_qmat_lq [64]
static const uint8_t fic_header [7] = { 0, 0, 1, 'F', 'I', 'C', 'V' }
static const AVOption options []
static const AVClass fic_decoder_class
AVCodec ff_fic_decoder
Macro Definition Documentation
FIC_HEADER_SIZE
#define FIC_HEADER_SIZE 27
Definition at line 83 of file fic.c.
Referenced by fic_decode_frame().
Function Documentation
fic_idct()
static av_always_inline void fic_idct (int16_t * blk, int step, int shift, int rnd) static
Definition at line 85 of file fic.c.
Referenced by fic_idct_put().
fic_idct_put()
static void fic_idct_put (uint8_t * dst, int stride, int16_t * block) static
Definition at line 109 of file fic.c.
Referenced by fic_decode_block().
fic_decode_block()
static int fic_decode_block (FICContext * ctx, GetBitContext * gb, uint8_t * dst, int stride, int16_t * block) static
Definition at line 135 of file fic.c.
Referenced by fic_decode_slice().
fic_decode_slice()
static int fic_decode_slice (AVCodecContext * avctx, void * tdata) static
Definition at line 164 of file fic.c.
Referenced by fic_decode_frame().
fic_alpha_blend()
static av_always_inline void fic_alpha_blend (uint8_t * dst, uint8_t * src, int size, uint8_t * alpha) static
Definition at line 196 of file fic.c.
Referenced by fic_draw_cursor().
fic_draw_cursor()
static void fic_draw_cursor (AVCodecContext * avctx, int cur_x, int cur_y) static
Definition at line 205 of file fic.c.
Referenced by fic_decode_frame().
fic_decode_frame()
static int fic_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 259 of file fic.c.
fic_decode_close()
static av_cold int fic_decode_close (AVCodecContext * avctx) static
Definition at line 428 of file fic.c.
fic_decode_init()
static av_cold int fic_decode_init (AVCodecContext * avctx) static
Definition at line 439 of file fic.c.
Variable Documentation
fic_qmat_hq
const uint8_t fic_qmat_hq[64] static
Initial value:
= {
    1, 2, 2, 2, 3, 3, 3, 4,
    2, 2, 2, 3, 3, 3, 4, 4,
    2, 2, 3, 3, 3, 4, 4, 4,
    2, 2, 3, 3, 3, 4, 4, 5,
    2, 3, 3, 3, 4, 4, 5, 6,
    3, 3, 3, 4, 4, 5, 6, 7,
    3, 3, 3, 4, 4, 5, 7, 7,
    3, 3, 4, 4, 5, 7, 7, 7,
}
Definition at line 59 of file fic.c.
Referenced by fic_decode_frame().
fic_qmat_lq
const uint8_t fic_qmat_lq[64] static
Initial value:
= {
    1,  5,  6,  7,  8,  9,  9, 11,
    5,  5,  7,  8,  9,  9, 11, 12,
    6,  7,  8,  9,  9, 11, 11, 12,
    7,  7,  8,  9,  9, 11, 12, 13,
    7,  8,  9,  9, 10, 11, 13, 16,
    8,  9,  9, 10, 11, 13, 16, 19,
    8,  9,  9, 11, 12, 15, 18, 23,
    9,  9, 11, 12, 15, 18, 23, 27
}
Definition at line 70 of file fic.c.
Referenced by fic_decode_frame().
fic_header
const uint8_t fic_header[7] = { 0, 0, 1, 'F', 'I', 'C', 'V' } static
Definition at line 81 of file fic.c.
Referenced by fic_decode_frame().
options
const AVOption options[] static
Initial value:
= {
{ "skip_cursor", "skip the cursor", 0x42, AV_OPT_TYPE_BOOL, {.i64 = 0 }, 0, 1, AV_OPT_FLAG_DECODING_PARAM | AV_OPT_FLAG_VIDEO_PARAM },
{ NULL },
}
Definition at line 458 of file fic.c.
fic_decoder_class
const AVClass fic_decoder_class static
Initial value:
= {
    .class_name = "FIC encoder",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 463 of file fic.c.
ff_fic_decoder
AVCodec ff_fic_decoder
Initial value:
= {
    .name           = "fic",
    .long_name      = NULL_IF_CONFIG_SMALL("Mirillis FIC"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_FIC,
    .priv_data_size = sizeof(FICContext),
    .init           = fic_decode_init,
    .decode         = fic_decode_frame,
    .close          = fic_decode_close,
    .capabilities   = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_SLICE_THREADS,
    .priv_class     = &fic_decoder_class,
}
Definition at line 470 of file fic.c.