FFmpeg: libavformat/tests/fifo_muxer.c File Reference
fifo_muxer.c File Reference
#include <stdlib.h>
#include "libavutil/opt.h"
#include "libavutil/time.h"
#include "libavutil/avassert.h"
#include "libavformat/avformat.h"
#include "libavformat/url.h"
#include "libavformat/network.h"
Data Structures
struct FailingMuxerPacketData
struct FailingMuxerContext
struct TestCase
Macros
#define MAX_TST_PACKETS 128
#define SLEEPTIME_50_MS 50000
#define SLEEPTIME_10_MS 10000
#define OFFSET(x) offsetof(FailingMuxerContext, x)
#define BUFFER_SIZE 64
Functions
static int failing_write_header (AVFormatContext *avf)
static int failing_write_packet (AVFormatContext *avf, AVPacket *pkt)
static int failing_write_trailer (AVFormatContext *avf)
static void failing_deinit (AVFormatContext *avf)
static int prepare_packet (AVPacket *pkt, const FailingMuxerPacketData *pkt_data, int64_t pts)
static int initialize_fifo_tst_muxer_chain (AVFormatContext **oc)
static int fifo_basic_test (AVFormatContext *oc, AVDictionary **opts, const FailingMuxerPacketData *pkt_data)
static int fifo_write_header_err_tst (AVFormatContext *oc, AVDictionary **opts, const FailingMuxerPacketData *pkt_data)
static int fifo_overflow_drop_test (AVFormatContext *oc, AVDictionary **opts, const FailingMuxerPacketData *data)
static int run_test (const TestCase *test)
int main (int argc, char *argv[])
Variables
static const AVOption options []
static const AVClass failing_muxer_class
AVOutputFormat tst_failing_muxer
const TestCase tests []
Macro Definition Documentation
MAX_TST_PACKETS
#define MAX_TST_PACKETS 128
Definition at line 30 of file fifo_muxer.c.
Referenced by fifo_write_header_err_tst().
SLEEPTIME_50_MS
#define SLEEPTIME_50_MS 50000
Definition at line 31 of file fifo_muxer.c.
Referenced by fifo_overflow_drop_test().
SLEEPTIME_10_MS
#define SLEEPTIME_10_MS 10000
Definition at line 32 of file fifo_muxer.c.
Referenced by failing_write_packet().
OFFSET
#define OFFSET (x) offsetof(FailingMuxerContext, x)
Definition at line 120 of file fifo_muxer.c.
BUFFER_SIZE
#define BUFFER_SIZE 64
Definition at line 353 of file fifo_muxer.c.
Referenced by run_test().
Function Documentation
failing_write_header()
static int failing_write_header (AVFormatContext * avf) static
Definition at line 57 of file fifo_muxer.c.
failing_write_packet()
static int failing_write_packet (AVFormatContext * avf, AVPacket * pkt) static
Definition at line 63 of file fifo_muxer.c.
failing_write_trailer()
static int failing_write_trailer (AVFormatContext * avf) static
Definition at line 98 of file fifo_muxer.c.
failing_deinit()
static void failing_deinit (AVFormatContext * avf) static
Definition at line 104 of file fifo_muxer.c.
prepare_packet()
static int prepare_packet (AVPacket * pkt, const FailingMuxerPacketData * pkt_data, int64_t pts) static
Definition at line 150 of file fifo_muxer.c.
Referenced by fifo_basic_test(), fifo_overflow_drop_test(), and fifo_write_header_err_tst().
initialize_fifo_tst_muxer_chain()
static int initialize_fifo_tst_muxer_chain (AVFormatContext ** oc) static
Definition at line 163 of file fifo_muxer.c.
Referenced by run_test().
fifo_basic_test()
static int fifo_basic_test (AVFormatContext * oc, AVDictionary ** opts, const FailingMuxerPacketData * pkt_data) static
Definition at line 185 of file fifo_muxer.c.
fifo_write_header_err_tst()
static int fifo_write_header_err_tst (AVFormatContext * oc, AVDictionary ** opts, const FailingMuxerPacketData * pkt_data) static
Definition at line 238 of file fifo_muxer.c.
fifo_overflow_drop_test()
static int fifo_overflow_drop_test (AVFormatContext * oc, AVDictionary ** opts, const FailingMuxerPacketData * data) static
Definition at line 286 of file fifo_muxer.c.
run_test()
static int run_test (const TestCase * test) static
Definition at line 355 of file fifo_muxer.c.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 430 of file fifo_muxer.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
        {"write_header_ret", "write_header() return value", OFFSET(write_header_ret),
         AV_OPT_TYPE_INT, {.i64 = 0}, INT_MIN, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM},
        {"write_trailer_ret", "write_trailer() return value", OFFSET(write_trailer_ret),
         AV_OPT_TYPE_INT, {.i64 = 0}, INT_MIN, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM},
        {"print_deinit_summary", "print summary when deinitializing muxer", OFFSET(print_deinit_summary),
         AV_OPT_TYPE_BOOL, {.i64 = 1}, 0, 1, AV_OPT_FLAG_ENCODING_PARAM},
        {NULL}
    }
Definition at line 121 of file fifo_muxer.c.
failing_muxer_class
const AVClass failing_muxer_class static
Initial value:
= {
    .class_name = "Failing test muxer",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 131 of file fifo_muxer.c.
tst_failing_muxer
AVOutputFormat tst_failing_muxer
Initial value:
= {
    .name           = "fail",
    .long_name      = NULL_IF_CONFIG_SMALL("Failing test muxer"),
    .priv_data_size = sizeof(FailingMuxerContext),
    .write_header   = failing_write_header,
    .write_packet   = failing_write_packet,
    .write_trailer  = failing_write_trailer,
    .deinit         = failing_deinit,
    .priv_class     = &failing_muxer_class,
    .flags          = AVFMT_NOFILE | AVFMT_ALLOW_FLUSH,
}
Definition at line 138 of file fifo_muxer.c.
tests
const TestCase tests[]
Initial value:
= {
        {fifo_basic_test, "nonfail test", NULL,1, 0, 0, {0, 0, 0}},
        {fifo_write_header_err_tst, "write header error test", NULL, 0, -1, 0, {0, 0, 0}},
        {fifo_basic_test, "recovery test", "attempt_recovery=1:recovery_wait_time=0",
         0, 0, 0, {AVERROR(ETIMEDOUT), 3, 0}},
        {fifo_basic_test, "overflow without packet dropping","queue_size=3",
         1, 0, 0, {0, 0, SLEEPTIME_10_MS}},
        {fifo_overflow_drop_test, "overflow with packet dropping", "queue_size=3:drop_pkts_on_overflow=1",
         0, 0, 0, {0, 0, SLEEPTIME_50_MS}},
        {NULL}
}
Definition at line 398 of file fifo_muxer.c.
Referenced by checkasm_check_h264pred(), and main().