FFmpeg: libavutil/fifo.h File Reference
fifo.h File Reference
a very simple circular buffer FIFO implementation
#include <stdint.h>
#include "avutil.h"
#include "attributes.h"
Data Structures
struct AVFifoBuffer
Functions
AVFifoBuffer * av_fifo_alloc (unsigned int size)
Initialize an AVFifoBuffer.
AVFifoBuffer * av_fifo_alloc_array (size_t nmemb, size_t size)
Initialize an AVFifoBuffer.
void av_fifo_free (AVFifoBuffer *f)
Free an AVFifoBuffer.
void av_fifo_freep (AVFifoBuffer **f)
Free an AVFifoBuffer and reset pointer to NULL.
void av_fifo_reset (AVFifoBuffer *f)
Reset the AVFifoBuffer to the state right after av_fifo_alloc, in particular it is emptied.
int av_fifo_size (const AVFifoBuffer *f)
Return the amount of data in bytes in the AVFifoBuffer, that is the amount of data you can read from it.
int av_fifo_space (const AVFifoBuffer *f)
Return the amount of space in bytes in the AVFifoBuffer, that is the amount of data you can write into it.
int av_fifo_generic_peek_at (AVFifoBuffer *f, void *dest, int offset, int buf_size, void(*func)(void *, void *, int))
Feed data at specific position from an AVFifoBuffer to a user-supplied callback.
int av_fifo_generic_peek (AVFifoBuffer *f, void *dest, int buf_size, void(*func)(void *, void *, int))
Feed data from an AVFifoBuffer to a user-supplied callback.
int av_fifo_generic_read (AVFifoBuffer *f, void *dest, int buf_size, void(*func)(void *, void *, int))
Feed data from an AVFifoBuffer to a user-supplied callback.
int av_fifo_generic_write (AVFifoBuffer *f, void *src, int size, int(*func)(void *, void *, int))
Feed data from a user-supplied callback to an AVFifoBuffer.
int av_fifo_realloc2 (AVFifoBuffer *f, unsigned int size)
Resize an AVFifoBuffer.
int av_fifo_grow (AVFifoBuffer *f, unsigned int additional_space)
Enlarge an AVFifoBuffer.
void av_fifo_drain (AVFifoBuffer *f, int size)
Read and discard the specified amount of data from an AVFifoBuffer.
static uint8_t * av_fifo_peek2 (const AVFifoBuffer *f, int offs)
Return a pointer to the data stored in a FIFO buffer at a certain offset.
Detailed Description
a very simple circular buffer FIFO implementation
Definition in file fifo.h.
Function Documentation
av_fifo_alloc()
AVFifoBuffer* av_fifo_alloc (unsigned int size)
Initialize an AVFifoBuffer.
Parameters
size of FIFO
Returns
AVFifoBuffer or NULL in case of memory allocation failure
Definition at line 43 of file fifo.c.
Referenced by av_audio_fifo_alloc(), av_fifo_realloc2(), av_thread_message_queue_alloc(), cuvid_decode_init(), ff_qsv_enc_init(), init_audio(), init_video(), libvorbis_encode_init(), main(), mediacodec_decode_init(), mpeg_mux_init(), new_output_stream(), nvenc_setup_surfaces(), qsv_decode_init(), ring_init(), svc_decode_init(), swf_write_header(), and udp_open().
av_fifo_alloc_array()
AVFifoBuffer* av_fifo_alloc_array (size_t nmemb, size_t size)
Initialize an AVFifoBuffer.
Parameters
nmemb number of elements
size size of the single element
Returns
AVFifoBuffer or NULL in case of memory allocation failure
Definition at line 49 of file fifo.c.
Referenced by common_init(), dv_init_mux(), ff_audio_interleave_init(), ff_frame_thread_encoder_init(), flac_parse_init(), init(), and start_jack().
av_fifo_free()
void av_fifo_free (AVFifoBuffer * f)
Free an AVFifoBuffer.
Parameters
f AVFifoBuffer to free
Definition at line 55 of file fifo.c.
Referenced by av_fifo_freep(), ff_qsv_decode_close(), ff_qsv_enc_close(), main(), mediacodec_decode_close(), qsv_decode_close(), and svc_decode_close().
av_fifo_freep()
void av_fifo_freep (AVFifoBuffer ** f)
Free an AVFifoBuffer and reset pointer to NULL.
Parameters
f AVFifoBuffer to free
Definition at line 63 of file fifo.c.
Referenced by av_audio_fifo_free(), av_thread_message_queue_free(), cuvid_decode_end(), dv_delete_mux(), dv_init_mux(), ff_audio_interleave_close(), ff_frame_thread_encoder_free(), ff_nvenc_encode_close(), ffmpeg_cleanup(), flac_parse_close(), free_pkt_fifo(), libvorbis_encode_close(), mpeg_mux_end(), ring_destroy(), swf_write_trailer(), udp_close(), udp_open(), and uninit().
av_fifo_reset()
void av_fifo_reset (AVFifoBuffer * f)
Reset the AVFifoBuffer to the state right after av_fifo_alloc, in particular it is emptied.
Parameters
f AVFifoBuffer to reset
Definition at line 71 of file fifo.c.
Referenced by av_audio_fifo_reset(), fifo_alloc_common(), main(), mediacodec_decode_flush(), and ring_reset().
av_fifo_size()
int av_fifo_size (const AVFifoBuffer * f)
Return the amount of data in bytes in the AVFifoBuffer, that is the amount of data you can read from it.
Parameters
f AVFifoBuffer to read from
Returns
size
Definition at line 77 of file fifo.c.
Referenced by add_buffer_ref(), av_buffersink_get_frame_flags(), av_buffersrc_add_frame_internal(), av_fifo_drain(), av_fifo_grow(), av_fifo_realloc2(), av_fifo_space(), av_thread_message_flush(), av_thread_message_queue_free(), check_init_output_file(), cuvid_output_frame(), dv_assemble_frame(), ff_audio_rechunk_interleave(), ff_nvenc_encode_frame(), ff_qsv_decode_close(), ff_qsv_enc_close(), ff_qsv_encode(), ffmpeg_cleanup(), filter_frame(), find_new_headers(), flac_parse(), flush_fifo(), flush_packet(), free_pkt_fifo(), get_best_header(), interleave_new_audio_packet(), libvorbis_encode_frame(), main(), mediacodec_decode_flush(), mediacodec_decode_frame(), mpeg_mux_end(), mpeg_mux_write_packet(), output_packet(), output_ready(), poll_frame(), process_callback(), qsv_clear_buffers(), qsv_decode(), qsv_decode_frame(), request_frame(), ring_size(), svc_decode_close(), svc_decode_frame(), swf_write_audio(), swf_write_video(), timestamp_queue_dequeue(), udp_get_file_handle(), udp_read(), uninit(), worker(), write_packet(), and write_to_fifo().
av_fifo_space()
int av_fifo_space (const AVFifoBuffer * f)
Return the amount of space in bytes in the AVFifoBuffer, that is the amount of data you can write into it.
Parameters
f AVFifoBuffer to write into
Returns
size
Definition at line 82 of file fifo.c.
Referenced by add_buffer_ref(), av_buffersrc_add_frame_internal(), av_thread_message_queue_free(), ff_qsv_encode(), flac_parse(), libvorbis_encode_frame(), main(), mediacodec_decode_frame(), process_callback(), qsv_decode(), qsv_decode_frame(), ring_space(), supply_new_packets(), svc_decode_frame(), udp_get_file_handle(), udp_write(), write_packet(), and write_to_fifo().
av_fifo_generic_peek_at()
int av_fifo_generic_peek_at (AVFifoBuffer * f, void * dest, int offset, int buf_size, void(*)(void *, void *, int) func)
Feed data at specific position from an AVFifoBuffer to a user-supplied callback.
Similar as av_fifo_gereric_read but without discarding data.
Parameters
f AVFifoBuffer to read from
offset offset from current read position
buf_size number of bytes to read
func generic read function
dest data destination
Definition at line 151 of file fifo.c.
Referenced by av_audio_fifo_peek_at(), av_thread_message_flush(), main(), and ring_generic_read().
av_fifo_generic_peek()
int av_fifo_generic_peek (AVFifoBuffer * f, void * dest, int buf_size, void(*)(void *, void *, int) func)
Feed data from an AVFifoBuffer to a user-supplied callback.
Similar as av_fifo_gereric_read but without discarding data.
Parameters
f AVFifoBuffer to read from
buf_size number of bytes to read
func generic read function
dest data destination
Definition at line 189 of file fifo.c.
Referenced by av_audio_fifo_peek(), and main().
av_fifo_generic_read()
int av_fifo_generic_read (AVFifoBuffer * f, void * dest, int buf_size, void(*)(void *, void *, int) func)
Feed data from an AVFifoBuffer to a user-supplied callback.
Parameters
f AVFifoBuffer to read from
buf_size number of bytes to read
func generic read function
dest data destination
Definition at line 213 of file fifo.c.
Referenced by audio_read_packet(), av_audio_fifo_read(), av_buffersink_get_frame_flags(), av_fifo_realloc2(), av_thread_message_queue_free(), check_init_output_file(), cuvid_output_frame(), ff_nvenc_encode_frame(), ff_qsv_decode_close(), ff_qsv_enc_close(), ff_qsv_encode(), ffmpeg_cleanup(), filter_frame(), flush_fifo(), flush_packet(), free_pkt_fifo(), interleave_new_audio_packet(), libvorbis_encode_frame(), main(), mediacodec_decode_flush(), mediacodec_decode_frame(), process_callback(), qsv_clear_buffers(), qsv_decode(), qsv_decode_frame(), request_frame(), svc_decode_close(), svc_decode_frame(), swf_write_video(), timestamp_queue_dequeue(), udp_get_file_handle(), udp_read(), uninit(), and worker().
av_fifo_generic_write()
int av_fifo_generic_write (AVFifoBuffer * f, void * src, int size, int(*)(void *, void *, int) func)
Feed data from a user-supplied callback to an AVFifoBuffer.
Parameters
f AVFifoBuffer to write to
src data source; non-const since it may be used as a modifiable context by the function defined in func
size number of bytes to write
func generic write function; the first parameter is src, the second is dest_buf, the third is dest_buf_size. func must return the number of bytes written to dest_buf, or <= 0 to indicate no more data available to write. If func is NULL, src is interpreted as a simple byte array for source data.
Returns
the number of bytes written to the FIFO
Definition at line 122 of file fifo.c.
Referenced by add_buffer_ref(), av_audio_fifo_write(), av_buffersrc_add_frame_internal(), av_thread_message_queue_free(), cuvid_handle_picture_display(), dv_assemble_frame(), encode_frame(), ff_audio_rechunk_interleave(), ff_nvenc_encode_frame(), ff_thread_video_encode_frame(), flac_parse(), libvorbis_encode_frame(), main(), mediacodec_decode_frame(), mpeg_mux_write_packet(), process_callback(), qsv_decode(), qsv_decode_frame(), ring_generic_write(), supply_new_packets(), svc_decode_frame(), swf_write_audio(), timestamp_queue_enqueue(), udp_get_file_handle(), udp_write(), write_packet(), and write_to_fifo().
av_fifo_realloc2()
int av_fifo_realloc2 (AVFifoBuffer * f, unsigned int size)
Resize an AVFifoBuffer.
In case of reallocation failure, the old FIFO is kept unchanged.
Parameters
f AVFifoBuffer to resize
size new AVFifoBuffer size in bytes
Returns
<0 for failure, >=0 otherwise
Definition at line 87 of file fifo.c.
Referenced by add_buffer_ref(), av_audio_fifo_realloc(), av_buffersrc_add_frame_internal(), av_fifo_grow(), ff_audio_rechunk_interleave(), flac_parse(), mediacodec_decode_frame(), mpeg_mux_write_packet(), qsv_decode_frame(), svc_decode_frame(), write_packet(), and write_to_fifo().
av_fifo_grow()
int av_fifo_grow (AVFifoBuffer * f, unsigned int additional_space)
Enlarge an AVFifoBuffer.
In case of reallocation failure, the old FIFO is kept unchanged. The new fifo size may be larger than the requested size.
Parameters
f AVFifoBuffer to resize
additional_space the amount of space in bytes to allocate in addition to av_fifo_size()
Returns
<0 for failure, >=0 otherwise
Definition at line 107 of file fifo.c.
Referenced by main().
av_fifo_drain()
void av_fifo_drain (AVFifoBuffer * f, int size)
Read and discard the specified amount of data from an AVFifoBuffer.
Parameters
f AVFifoBuffer to read from
size amount of data to read in bytes
Read and discard the specified amount of data from an AVFifoBuffer.
Definition at line 233 of file fifo.c.
Referenced by av_audio_fifo_drain(), av_fifo_generic_read(), av_thread_message_flush(), dv_assemble_frame(), flac_parse(), ring_generic_read(), and udp_read().
av_fifo_peek2()
static uint8_t* av_fifo_peek2 (const AVFifoBuffer * f, int offs) inline static
Return a pointer to the data stored in a FIFO buffer at a certain offset.
The FIFO buffer is not modified.
Parameters
f AVFifoBuffer to peek at, f must be non-NULL
offs an offset in bytes, its absolute value must be less than the used buffer size or the returned pointer will point outside to the buffer data. The used buffer size can be checked with av_fifo_size().
Definition at line 169 of file fifo.h.
Referenced by av_buffersink_get_frame_flags(), dv_inject_audio(), and main().