FFmpeg: libavutil/fixed_dsp.c File Reference
fixed_dsp.c File Reference
#include "fixed_dsp.h"
Functions
static void vector_fmul_add_c (int *dst, const int *src0, const int *src1, const int *src2, int len)
static void vector_fmul_reverse_c (int *dst, const int *src0, const int *src1, int len)
static void vector_fmul_window_scaled_c (int16_t *dst, const int32_t *src0, const int32_t *src1, const int32_t *win, int len, uint8_t bits)
static void vector_fmul_window_c (int32_t *dst, const int32_t *src0, const int32_t *src1, const int32_t *win, int len)
static void vector_fmul_c (int *dst, const int *src0, const int *src1, int len)
static int scalarproduct_fixed_c (const int *v1, const int *v2, int len)
static void butterflies_fixed_c (int *v1, int *v2, int len)
AVFixedDSPContext * avpriv_alloc_fixed_dsp (int bit_exact)
Allocate and initialize a fixed DSP context.
Function Documentation
vector_fmul_add_c()
static void vector_fmul_add_c (int * dst, const int * src0, const int * src1, const int * src2, int len) static
Definition at line 50 of file fixed_dsp.c.
Referenced by avpriv_alloc_fixed_dsp().
vector_fmul_reverse_c()
static void vector_fmul_reverse_c (int * dst, const int * src0, const int * src1, int len) static
Definition at line 60 of file fixed_dsp.c.
Referenced by avpriv_alloc_fixed_dsp().
vector_fmul_window_scaled_c()
static void vector_fmul_window_scaled_c (int16_t * dst, const int32_t * src0, const int32_t * src1, const int32_t * win, int len, uint8_t bits) static
Definition at line 72 of file fixed_dsp.c.
Referenced by avpriv_alloc_fixed_dsp().
vector_fmul_window_c()
static void vector_fmul_window_c (int32_t * dst, const int32_t * src0, const int32_t * src1, const int32_t * win, int len) static
Definition at line 93 of file fixed_dsp.c.
Referenced by avpriv_alloc_fixed_dsp().
vector_fmul_c()
static void vector_fmul_c (int * dst, const int * src0, const int * src1, int len) static
Definition at line 113 of file fixed_dsp.c.
Referenced by avpriv_alloc_fixed_dsp().
scalarproduct_fixed_c()
static int scalarproduct_fixed_c (const int * v1, const int * v2, int len) static
p is initialized with 0x40000000 so that the proper rounding will occur at the end
Definition at line 124 of file fixed_dsp.c.
Referenced by avpriv_alloc_fixed_dsp().
butterflies_fixed_c()
static void butterflies_fixed_c (int * v1, int * v2, int len) static
Definition at line 137 of file fixed_dsp.c.
Referenced by avpriv_alloc_fixed_dsp().
avpriv_alloc_fixed_dsp()
AVFixedDSPContext* avpriv_alloc_fixed_dsp (int strict)
Allocate and initialize a fixed DSP context.
note: should be freed with a av_free call when no longer needed.
Parameters
strict setting to non-zero avoids using functions which may not be IEEE-754 compliant
Definition at line 148 of file fixed_dsp.c.
Referenced by aac_decode_init(), ac3_decode_init(), and ff_dca_core_init().