FFmpeg: libavformat/flacenc.h File Reference
flacenc.h File Reference
#include "libavcodec/flac.h"
#include "libavcodec/bytestream.h"
#include "avformat.h"
Functions
int ff_flac_write_header (AVIOContext *pb, uint8_t *extradata, int extradata_size, int last_block)
int ff_flac_is_native_layout (uint64_t channel_layout)
Function Documentation
ff_flac_write_header()
int ff_flac_write_header (AVIOContext * pb, uint8_t * extradata, int extradata_size, int last_block)
Definition at line 29 of file flacenc_header.c.
Referenced by flac_write_header(), and put_flac_codecpriv().
ff_flac_is_native_layout()
int ff_flac_is_native_layout (uint64_t channel_layout)
Definition at line 50 of file flacenc_header.c.
Referenced by flac_write_header(), and put_flac_codecpriv().