FFmpeg: libavcodec/flashsv.c File Reference
flashsv.c File Reference
Flash Screen Video decoder.
#include <stdio.h>
#include <stdlib.h>
#include <zlib.h>
#include "libavutil/intreadwrite.h"
#include "avcodec.h"
#include "bytestream.h"
#include "get_bits.h"
#include "internal.h"
Data Structures
struct BlockInfo
struct FlashSVContext
Functions
static int decode_hybrid (const uint8_t *sptr, const uint8_t *sptr_end, uint8_t *dptr, int dx, int dy, int h, int w, int stride, const uint32_t *pal)
static av_cold int flashsv_decode_end (AVCodecContext *avctx)
static av_cold int flashsv_decode_init (AVCodecContext *avctx)
static int flashsv2_prime (FlashSVContext *s, uint8_t *src, int size)
static int flashsv_decode_block (AVCodecContext *avctx, AVPacket *avpkt, GetBitContext *gb, int block_size, int width, int height, int x_pos, int y_pos, int blk_idx)
static int calc_deflate_block_size (int tmpblock_size)
static int flashsv_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
Detailed Description
Flash Screen Video decoder.
Author
Alex Beregszaszi
Benjamin Larsson
Daniel Verkamp
Konstantin Shishkov
A description of the bitstream format for Flash Screen Video version 1/2 is part of the SWF File Format Specification (version 10), which can be downloaded from http://www.adobe.com/devnet/swf.html.
Definition in file flashsv.c.
Function Documentation
decode_hybrid()
static int decode_hybrid (const uint8_t * sptr, const uint8_t * sptr_end, uint8_t * dptr, int dx, int dy, int h, int w, int stride, const uint32_t * pal) static
Definition at line 72 of file flashsv.c.
Referenced by flashsv_decode_block().
flashsv_decode_end()
static av_cold int flashsv_decode_end (AVCodecContext * avctx) static
Definition at line 104 of file flashsv.c.
Referenced by flashsv_decode_frame(), and flashsv_decode_init().
flashsv_decode_init()
static av_cold int flashsv_decode_init (AVCodecContext * avctx) static
Definition at line 117 of file flashsv.c.
Referenced by flashsv_decode_frame().
flashsv2_prime()
static int flashsv2_prime (FlashSVContext * s, uint8_t * src, int size) static
Definition at line 142 of file flashsv.c.
Referenced by flashsv_decode_block().
flashsv_decode_block()
static int flashsv_decode_block (AVCodecContext * avctx, AVPacket * avpkt, GetBitContext * gb, int block_size, int width, int height, int x_pos, int y_pos, int blk_idx) static
Definition at line 183 of file flashsv.c.
Referenced by flashsv_decode_frame().
calc_deflate_block_size()
static int calc_deflate_block_size (int tmpblock_size) static
Definition at line 251 of file flashsv.c.
Referenced by flashsv_decode_frame().
flashsv_decode_frame()
static int flashsv_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 267 of file flashsv.c.