FFmpeg: libavutil/float_dsp.c File Reference
float_dsp.c File Reference
#include "config.h"
#include "attributes.h"
#include "float_dsp.h"
#include "mem.h"
Functions
static void vector_fmul_c (float *dst, const float *src0, const float *src1, int len)
static void vector_fmac_scalar_c (float *dst, const float *src, float mul, int len)
static void vector_fmul_scalar_c (float *dst, const float *src, float mul, int len)
static void vector_dmul_scalar_c (double *dst, const double *src, double mul, int len)
static void vector_fmul_window_c (float *dst, const float *src0, const float *src1, const float *win, int len)
static void vector_fmul_add_c (float *dst, const float *src0, const float *src1, const float *src2, int len)
static void vector_fmul_reverse_c (float *dst, const float *src0, const float *src1, int len)
static void butterflies_float_c (float *av_restrict v1, float *av_restrict v2, int len)
float avpriv_scalarproduct_float_c (const float *v1, const float *v2, int len)
Return the scalar product of two vectors.
av_cold AVFloatDSPContext * avpriv_float_dsp_alloc (int bit_exact)
Allocate a float DSP context.
Function Documentation
vector_fmul_c()
static void vector_fmul_c (float * dst, const float * src0, const float * src1, int len) static
Definition at line 27 of file float_dsp.c.
Referenced by avpriv_float_dsp_alloc().
vector_fmac_scalar_c()
static void vector_fmac_scalar_c (float * dst, const float * src, float mul, int len) static
Definition at line 35 of file float_dsp.c.
Referenced by avpriv_float_dsp_alloc().
vector_fmul_scalar_c()
static void vector_fmul_scalar_c (float * dst, const float * src, float mul, int len) static
Definition at line 43 of file float_dsp.c.
Referenced by avpriv_float_dsp_alloc().
vector_dmul_scalar_c()
static void vector_dmul_scalar_c (double * dst, const double * src, double mul, int len) static
Definition at line 51 of file float_dsp.c.
Referenced by avpriv_float_dsp_alloc().
vector_fmul_window_c()
static void vector_fmul_window_c (float * dst, const float * src0, const float * src1, const float * win, int len) static
Definition at line 59 of file float_dsp.c.
Referenced by avpriv_float_dsp_alloc().
vector_fmul_add_c()
static void vector_fmul_add_c (float * dst, const float * src0, const float * src1, const float * src2, int len) static
Definition at line 78 of file float_dsp.c.
Referenced by avpriv_float_dsp_alloc().
vector_fmul_reverse_c()
static void vector_fmul_reverse_c (float * dst, const float * src0, const float * src1, int len) static
Definition at line 86 of file float_dsp.c.
Referenced by avpriv_float_dsp_alloc().
butterflies_float_c()
static void butterflies_float_c (float *av_restrict v1, float *av_restrict v2, int len) static
Definition at line 96 of file float_dsp.c.
Referenced by avpriv_float_dsp_alloc().
avpriv_scalarproduct_float_c()
float avpriv_scalarproduct_float_c (const float * v1, const float * v2, int len)
Return the scalar product of two vectors.
Parameters
v1 first input vector
v2 first input vector
len number of elements
Returns
sum of elementwise products
Definition at line 108 of file float_dsp.c.
Referenced by acelp_decode_gain_codef(), apply_gain_ctrl(), avpriv_float_dsp_alloc(), calc_input_response(), compensate_volume(), convolve(), decode(), decode_frame(), ff_adaptive_gain_control(), ff_amr_set_fixed_gain(), ff_scale_vector_to_given_sum_of_squares(), kalman_smoothen(), postfilter(), synth_block_fcb_acb(), and tilt_factor().
avpriv_float_dsp_alloc()
av_cold AVFloatDSPContext* avpriv_float_dsp_alloc (int strict)
Allocate a float DSP context.
Parameters
strict setting to non-zero avoids using functions which may not be IEEE-754 compliant
Definition at line 119 of file float_dsp.c.
Referenced by aac_decode_init(), ac3_decode_init(), atrac1_decode_init(), atrac3_decode_init(), atrac3p_decode_init(), decode_init(), dsp_init(), encode_init(), ff_ac3_float_encode_init(), ff_celt_init(), ff_dca_core_init(), ff_dca_lbr_init(), ff_twinvq_decode_init(), ff_wma_init(), imc_decode_init(), init(), main(), mp3lame_encode_init(), on2avc_decode_init(), opus_decode_init(), pcm_decode_init(), ra288_decode_init(), and vorbis_parse_id_hdr().