FFmpeg: libavutil/float_dsp.h File Reference
float_dsp.h File Reference
#include "config.h"
Data Structures
struct AVFloatDSPContext
Functions
float avpriv_scalarproduct_float_c (const float *v1, const float *v2, int len)
Return the scalar product of two vectors.
void ff_float_dsp_init_aarch64 (AVFloatDSPContext *fdsp)
void ff_float_dsp_init_arm (AVFloatDSPContext *fdsp)
void ff_float_dsp_init_ppc (AVFloatDSPContext *fdsp, int strict)
void ff_float_dsp_init_x86 (AVFloatDSPContext *fdsp)
void ff_float_dsp_init_mips (AVFloatDSPContext *fdsp)
AVFloatDSPContext * avpriv_float_dsp_alloc (int strict)
Allocate a float DSP context.
Function Documentation
avpriv_scalarproduct_float_c()
float avpriv_scalarproduct_float_c (const float * v1, const float * v2, int len)
Return the scalar product of two vectors.
Parameters
v1 first input vector
v2 first input vector
len number of elements
Returns
sum of elementwise products
Definition at line 108 of file float_dsp.c.
Referenced by acelp_decode_gain_codef(), apply_gain_ctrl(), avpriv_float_dsp_alloc(), calc_input_response(), compensate_volume(), convolve(), decode(), decode_frame(), ff_adaptive_gain_control(), ff_amr_set_fixed_gain(), ff_scale_vector_to_given_sum_of_squares(), kalman_smoothen(), postfilter(), synth_block_fcb_acb(), and tilt_factor().
ff_float_dsp_init_aarch64()
void ff_float_dsp_init_aarch64 (AVFloatDSPContext * fdsp)
Definition at line 54 of file float_dsp_init.c.
Referenced by avpriv_float_dsp_alloc().
ff_float_dsp_init_arm()
void ff_float_dsp_init_arm (AVFloatDSPContext * fdsp)
Definition at line 24 of file float_dsp_init_arm.c.
Referenced by avpriv_float_dsp_alloc().
ff_float_dsp_init_ppc()
void ff_float_dsp_init_ppc (AVFloatDSPContext * fdsp, int strict)
Definition at line 29 of file float_dsp_init.c.
Referenced by avpriv_float_dsp_alloc().
ff_float_dsp_init_x86()
void ff_float_dsp_init_x86 (AVFloatDSPContext * fdsp)
Definition at line 68 of file float_dsp_init.c.
Referenced by avpriv_float_dsp_alloc().
ff_float_dsp_init_mips()
void ff_float_dsp_init_mips (AVFloatDSPContext * fdsp)
Definition at line 346 of file float_dsp_mips.c.
Referenced by avpriv_float_dsp_alloc().
avpriv_float_dsp_alloc()
AVFloatDSPContext* avpriv_float_dsp_alloc (int strict)
Allocate a float DSP context.
Parameters
strict setting to non-zero avoids using functions which may not be IEEE-754 compliant
Definition at line 119 of file float_dsp.c.
Referenced by aac_decode_init(), ac3_decode_init(), atrac1_decode_init(), atrac3_decode_init(), atrac3p_decode_init(), decode_init(), dsp_init(), encode_init(), ff_ac3_float_encode_init(), ff_celt_init(), ff_dca_core_init(), ff_dca_lbr_init(), ff_twinvq_decode_init(), ff_wma_init(), imc_decode_init(), init(), main(), mp3lame_encode_init(), on2avc_decode_init(), opus_decode_init(), pcm_decode_init(), ra288_decode_init(), and vorbis_parse_id_hdr().