FFmpeg: libavutil/arm/float_dsp_init_neon.c File Reference
float_dsp_init_neon.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/float_dsp.h"
#include "float_dsp_arm.h"
Functions
void ff_vector_fmul_neon (float *dst, const float *src0, const float *src1, int len)
void ff_vector_fmac_scalar_neon (float *dst, const float *src, float mul, int len)
void ff_vector_fmul_scalar_neon (float *dst, const float *src, float mul, int len)
void ff_vector_fmul_window_neon (float *dst, const float *src0, const float *src1, const float *win, int len)
void ff_vector_fmul_add_neon (float *dst, const float *src0, const float *src1, const float *src2, int len)
void ff_vector_fmul_reverse_neon (float *dst, const float *src0, const float *src1, int len)
void ff_butterflies_float_neon (float *v1, float *v2, int len)
float ff_scalarproduct_float_neon (const float *v1, const float *v2, int len)
av_cold void ff_float_dsp_init_neon (AVFloatDSPContext *fdsp)
Function Documentation
ff_vector_fmul_neon()
void ff_vector_fmul_neon (float * dst, const float * src0, const float * src1, int len)
Referenced by ff_float_dsp_init_neon().
ff_vector_fmac_scalar_neon()
void ff_vector_fmac_scalar_neon (float * dst, const float * src, float mul, int len)
Referenced by ff_float_dsp_init_neon().
ff_vector_fmul_scalar_neon()
void ff_vector_fmul_scalar_neon (float * dst, const float * src, float mul, int len)
Referenced by ff_float_dsp_init_neon().
ff_vector_fmul_window_neon()
void ff_vector_fmul_window_neon (float * dst, const float * src0, const float * src1, const float * win, int len)
Referenced by ff_float_dsp_init_neon().
ff_vector_fmul_add_neon()
void ff_vector_fmul_add_neon (float * dst, const float * src0, const float * src1, const float * src2, int len)
Referenced by ff_float_dsp_init_neon().
ff_vector_fmul_reverse_neon()
void ff_vector_fmul_reverse_neon (float * dst, const float * src0, const float * src1, int len)
Referenced by ff_float_dsp_init_neon().
ff_butterflies_float_neon()
void ff_butterflies_float_neon (float * v1, float * v2, int len)
Referenced by ff_float_dsp_init_neon().
ff_scalarproduct_float_neon()
float ff_scalarproduct_float_neon (const float * v1, const float * v2, int len)
Referenced by ff_float_dsp_init_neon().
ff_float_dsp_init_neon()
av_cold void ff_float_dsp_init_neon (AVFloatDSPContext * fdsp)
Definition at line 49 of file float_dsp_init_neon.c.
Referenced by ff_float_dsp_init_arm().