FFmpeg: libavutil/arm/float_dsp_init_vfp.c File Reference
float_dsp_init_vfp.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/float_dsp.h"
#include "cpu.h"
#include "float_dsp_arm.h"
Functions
void ff_vector_fmul_vfp (float *dst, const float *src0, const float *src1, int len)
void ff_vector_fmul_window_vfp (float *dst, const float *src0, const float *src1, const float *win, int len)
void ff_vector_fmul_reverse_vfp (float *dst, const float *src0, const float *src1, int len)
void ff_butterflies_float_vfp (float *av_restrict v1, float *av_restrict v2, int len)
av_cold void ff_float_dsp_init_vfp (AVFloatDSPContext *fdsp, int cpu_flags)
Function Documentation
ff_vector_fmul_vfp()
void ff_vector_fmul_vfp (float * dst, const float * src0, const float * src1, int len)
Referenced by ff_float_dsp_init_vfp().
ff_vector_fmul_window_vfp()
void ff_vector_fmul_window_vfp (float * dst, const float * src0, const float * src1, const float * win, int len)
Referenced by ff_float_dsp_init_vfp().
ff_vector_fmul_reverse_vfp()
void ff_vector_fmul_reverse_vfp (float * dst, const float * src0, const float * src1, int len)
Referenced by ff_float_dsp_init_vfp().
ff_butterflies_float_vfp()
void ff_butterflies_float_vfp (float *av_restrict v1, float *av_restrict v2, int len)
Referenced by ff_float_dsp_init_vfp().
ff_float_dsp_init_vfp()
av_cold void ff_float_dsp_init_vfp (AVFloatDSPContext * fdsp, int cpu_flags)
Definition at line 37 of file float_dsp_init_vfp.c.
Referenced by ff_float_dsp_init_arm().