FFmpeg: libavcodec/fmtconvert.h File Reference
fmtconvert.h File Reference
#include "avcodec.h"
Data Structures
struct FmtConvertContext
Functions
void ff_fmt_convert_init (FmtConvertContext *c, AVCodecContext *avctx)
void ff_fmt_convert_init_aarch64 (FmtConvertContext *c, AVCodecContext *avctx)
void ff_fmt_convert_init_arm (FmtConvertContext *c, AVCodecContext *avctx)
void ff_fmt_convert_init_ppc (FmtConvertContext *c, AVCodecContext *avctx)
void ff_fmt_convert_init_x86 (FmtConvertContext *c, AVCodecContext *avctx)
void ff_fmt_convert_init_mips (FmtConvertContext *c)
Function Documentation
ff_fmt_convert_init()
void ff_fmt_convert_init (FmtConvertContext * c, AVCodecContext * avctx)
Definition at line 52 of file fmtconvert.c.
Referenced by ac3_decode_init(), and checkasm_check_fmtconvert().
ff_fmt_convert_init_aarch64()
void ff_fmt_convert_init_aarch64 (FmtConvertContext * c, AVCodecContext * avctx)
Definition at line 34 of file fmtconvert_init.c.
Referenced by ff_fmt_convert_init().
ff_fmt_convert_init_arm()
void ff_fmt_convert_init_arm (FmtConvertContext * c, AVCodecContext * avctx)
Definition at line 40 of file fmtconvert_init_arm.c.
Referenced by ff_fmt_convert_init().
ff_fmt_convert_init_ppc()
void ff_fmt_convert_init_ppc (FmtConvertContext * c, AVCodecContext * avctx)
Definition at line 57 of file fmtconvert_altivec.c.
Referenced by ff_fmt_convert_init().
ff_fmt_convert_init_x86()
void ff_fmt_convert_init_x86 (FmtConvertContext * c, AVCodecContext * avctx)
Definition at line 41 of file fmtconvert_init.c.
Referenced by ff_fmt_convert_init().
ff_fmt_convert_init_mips()
void ff_fmt_convert_init_mips (FmtConvertContext * c)
Definition at line 136 of file fmtconvert_mips.c.
Referenced by ff_fmt_convert_init().