FFmpeg: libavcodec/arm/fmtconvert_init_arm.c File Reference
fmtconvert_init_arm.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/arm/cpu.h"
#include "libavcodec/avcodec.h"
#include "libavcodec/fmtconvert.h"
Functions
void ff_int32_to_float_fmul_array8_neon (FmtConvertContext *c, float *dst, const int32_t *src, const float *mul, int len)
void ff_int32_to_float_fmul_scalar_neon (float *dst, const int32_t *src, float mul, int len)
void ff_int32_to_float_fmul_scalar_vfp (float *dst, const int32_t *src, float mul, int len)
void ff_int32_to_float_fmul_array8_vfp (FmtConvertContext *c, float *dst, const int32_t *src, const float *mul, int len)
av_cold void ff_fmt_convert_init_arm (FmtConvertContext *c, AVCodecContext *avctx)
Function Documentation
ff_int32_to_float_fmul_array8_neon()
void ff_int32_to_float_fmul_array8_neon (FmtConvertContext * c, float * dst, const int32_t * src, const float * mul, int len)
Referenced by ff_fmt_convert_init_arm().
ff_int32_to_float_fmul_scalar_neon()
void ff_int32_to_float_fmul_scalar_neon (float * dst, const int32_t * src, float mul, int len)
Referenced by ff_fmt_convert_init_arm().
ff_int32_to_float_fmul_scalar_vfp()
void ff_int32_to_float_fmul_scalar_vfp (float * dst, const int32_t * src, float mul, int len)
Referenced by ff_fmt_convert_init_arm().
ff_int32_to_float_fmul_array8_vfp()
void ff_int32_to_float_fmul_array8_vfp (FmtConvertContext * c, float * dst, const int32_t * src, const float * mul, int len)
Referenced by ff_fmt_convert_init_arm().
ff_fmt_convert_init_arm()
av_cold void ff_fmt_convert_init_arm (FmtConvertContext * c, AVCodecContext * avctx)
Definition at line 40 of file fmtconvert_init_arm.c.
Referenced by ff_fmt_convert_init().