FFmpeg: libavcodec/x86/fpel.h File Reference
fpel.h File Reference
#include <stddef.h>
#include <stdint.h>
Functions
void ff_avg_pixels4_mmx (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels4_mmxext (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_mmx (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_mmxext (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_mmx (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_mmxext (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_sse2 (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels4_mmx (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_mmx (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_mmx (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_sse2 (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
Function Documentation
ff_avg_pixels4_mmx()
void ff_avg_pixels4_mmx (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
ff_avg_pixels4_mmxext()
void ff_avg_pixels4_mmxext (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
ff_avg_pixels8_mmx()
void ff_avg_pixels8_mmx (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_mmx().
ff_avg_pixels8_mmxext()
void ff_avg_pixels8_mmxext (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_mmxext().
ff_avg_pixels16_mmx()
void ff_avg_pixels16_mmx (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
ff_avg_pixels16_mmxext()
void ff_avg_pixels16_mmxext (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
ff_avg_pixels16_sse2()
void ff_avg_pixels16_sse2 (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_sse2().
ff_put_pixels4_mmx()
void ff_put_pixels4_mmx (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
ff_put_pixels8_mmx()
void ff_put_pixels8_mmx (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
ff_put_pixels16_mmx()
void ff_put_pixels16_mmx (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
ff_put_pixels16_sse2()
void ff_put_pixels16_sse2 (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_sse2().