FFmpeg: libavfilter/framequeue.h File Reference
framequeue.h File Reference
#include "libavutil/frame.h"
Data Structures
struct FFFrameBucket
FFFrameQueue: simple AVFrame queue API.
struct FFFrameQueueGlobal
Structure to hold global options and statistics for frame queues.
struct FFFrameQueue
Queue of AVFrame pointers.
Functions
void ff_framequeue_global_init (FFFrameQueueGlobal *fqg)
Init a global structure.
void ff_framequeue_init (FFFrameQueue *fq, FFFrameQueueGlobal *fqg)
Init a frame queue and attach it to a global structure.
void ff_framequeue_free (FFFrameQueue *fq)
Free the queue and all queued frames.
int ff_framequeue_add (FFFrameQueue *fq, AVFrame *frame)
Add a frame.
AVFrame * ff_framequeue_take (FFFrameQueue *fq)
Take the first frame in the queue.
AVFrame * ff_framequeue_peek (FFFrameQueue *fq, size_t idx)
Access a frame in the queue, without removing it.
static size_t ff_framequeue_queued_frames (const FFFrameQueue *fq)
Get the number of queued frames.
static uint64_t ff_framequeue_queued_samples (const FFFrameQueue *fq)
Get the number of queued samples.
static void ff_framequeue_update_peeked (FFFrameQueue *fq, size_t idx)
Update the statistics after a frame accessed using ff_framequeue_peek() was modified.
static void ff_framequeue_skip_samples (FFFrameQueue *fq, size_t n)
Update the sample count in the queue.
Function Documentation
ff_framequeue_global_init()
void ff_framequeue_global_init (FFFrameQueueGlobal * fqg)
Init a global structure.
Definition at line 30 of file framequeue.c.
Referenced by avfilter_graph_alloc().
ff_framequeue_init()
void ff_framequeue_init (FFFrameQueue * fq, FFFrameQueueGlobal * fqg)
Init a frame queue and attach it to a global structure.
Definition at line 47 of file framequeue.c.
Referenced by avfilter_link().
ff_framequeue_free()
void ff_framequeue_free (FFFrameQueue * fq)
Free the queue and all queued frames.
Definition at line 53 of file framequeue.c.
Referenced by avfilter_link_free().
ff_framequeue_add()
int ff_framequeue_add (FFFrameQueue * fq, AVFrame * frame)
Add a frame.
Returns
>=0 or an AVERROR code.
Definition at line 63 of file framequeue.c.
Referenced by ff_filter_frame().
ff_framequeue_take()
AVFrame* ff_framequeue_take (FFFrameQueue * fq)
Take the first frame in the queue.
Must not be used with empty queues.
Definition at line 98 of file framequeue.c.
Referenced by ff_filter_frame_to_filter(), ff_framequeue_free(), and take_samples().
ff_framequeue_peek()
AVFrame* ff_framequeue_peek (FFFrameQueue * fq, size_t idx)
Access a frame in the queue, without removing it.
The first frame is numbered 0; the designated frame must exist.
Definition at line 114 of file framequeue.c.
Referenced by take_samples().
ff_framequeue_queued_frames()
static size_t ff_framequeue_queued_frames (const FFFrameQueue * fq) inline static
Get the number of queued frames.
Definition at line 141 of file framequeue.h.
Referenced by av_buffersink_get_frame_flags(), ff_filter_activate_default(), ff_filter_frame_to_filter(), ff_framesync_request_frame(), ff_request_frame(), samples_ready(), and take_samples().
ff_framequeue_queued_samples()
static uint64_t ff_framequeue_queued_samples (const FFFrameQueue * fq) inline static
Get the number of queued samples.
Definition at line 149 of file framequeue.h.
Referenced by av_buffersink_get_frame_flags(), ff_filter_frame_to_filter(), and samples_ready().
ff_framequeue_update_peeked()
static void ff_framequeue_update_peeked (FFFrameQueue * fq, size_t idx) inline static
Update the statistics after a frame accessed using ff_framequeue_peek() was modified.
Currently used only as a marker.
Definition at line 159 of file framequeue.h.
Referenced by take_samples().
ff_framequeue_skip_samples()
static void ff_framequeue_skip_samples (FFFrameQueue * fq, size_t n) inline static
Update the sample count in the queue.
This function must be used when the first frame was accessed using ff_framequeue_peek() and samples were removed from it.
Definition at line 169 of file framequeue.h.
Referenced by take_samples().