FFmpeg: libavcodec/frame_thread_encoder.c File Reference
frame_thread_encoder.c File Reference
#include "frame_thread_encoder.h"
#include "libavutil/fifo.h"
#include "libavutil/avassert.h"
#include "libavutil/imgutils.h"
#include "libavutil/thread.h"
#include "avcodec.h"
#include "internal.h"
#include "thread.h"
Data Structures
struct Task
struct ThreadContext
Macros
#define MAX_THREADS 64
#define BUFFER_SIZE (2*MAX_THREADS)
Functions
static void *attribute_align_arg worker (void *v)
int ff_frame_thread_encoder_init (AVCodecContext *avctx, AVDictionary *options)
void ff_frame_thread_encoder_free (AVCodecContext *avctx)
int ff_thread_video_encode_frame (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *frame, int *got_packet_ptr)
Macro Definition Documentation
MAX_THREADS
#define MAX_THREADS 64
Definition at line 31 of file frame_thread_encoder.c.
Referenced by dnxhd_encode_init(), ff_frame_thread_encoder_init(), ff_mpv_common_init(), free_buffers(), update_dimensions(), and vp78_decode_frame().
BUFFER_SIZE
#define BUFFER_SIZE (2*MAX_THREADS)
Definition at line 32 of file frame_thread_encoder.c.
Referenced by ff_frame_thread_encoder_init(), and ff_thread_video_encode_frame().
Function Documentation
worker()
static void* attribute_align_arg worker (void * v) static
Definition at line 60 of file frame_thread_encoder.c.
Referenced by ff_frame_thread_encoder_init().
ff_frame_thread_encoder_init()
int ff_frame_thread_encoder_init (AVCodecContext * avctx, AVDictionary * options)
Definition at line 114 of file frame_thread_encoder.c.
Referenced by avcodec_open2().
ff_frame_thread_encoder_free()
void ff_frame_thread_encoder_free (AVCodecContext * avctx)
Definition at line 228 of file frame_thread_encoder.c.
Referenced by avcodec_close(), and ff_frame_thread_encoder_init().
ff_thread_video_encode_frame()
int ff_thread_video_encode_frame (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * frame, int * got_packet_ptr)
Definition at line 250 of file frame_thread_encoder.c.
Referenced by avcodec_encode_video2().