FFmpeg: libavfilter/framepool.h File Reference
framepool.h File Reference
#include "libavutil/buffer.h"
#include "libavutil/frame.h"
Functions
FFVideoFramePool * ff_video_frame_pool_init (AVBufferRef *(*alloc)(int size), int width, int height, enum AVPixelFormat format, int align)
Allocate and initialize a video frame pool.
void ff_video_frame_pool_uninit (FFVideoFramePool **pool)
Deallocate the video frame pool.
int ff_video_frame_pool_get_config (FFVideoFramePool *pool, int *width, int *height, enum AVPixelFormat *format, int *align)
Get the video frame pool configuration.
AVFrame * ff_video_frame_pool_get (FFVideoFramePool *pool)
Allocate a new AVFrame, reussing old buffers from the pool when available.
Function Documentation
ff_video_frame_pool_init()
FFVideoFramePool* ff_video_frame_pool_init (AVBufferRef *(*)(int size) alloc, int width, int height, enum AVPixelFormat format, int align)
Allocate and initialize a video frame pool.
Parameters
alloc a function that will be used to allocate new frame buffers when the pool is empty. May be NULL, then the default allocator will be used (av_buffer_alloc()).
width width of each frame in this pool
height height of each frame in this pool
format format of each frame in this pool
align buffers alignement of each frame in this pool
Returns
newly created video frame pool on success, NULL on error.
Definition at line 40 of file framepool.c.
Referenced by ff_default_get_video_buffer().
ff_video_frame_pool_uninit()
void ff_video_frame_pool_uninit (FFVideoFramePool ** pool)
Deallocate the video frame pool.
It is safe to call this function while some of the allocated video frame are still in use.
Parameters
pool pointer to the video frame pool to be freed. It will be set to NULL.
Definition at line 177 of file framepool.c.
Referenced by avfilter_link_free(), ff_default_get_video_buffer(), and ff_video_frame_pool_init().
ff_video_frame_pool_get_config()
int ff_video_frame_pool_get_config (FFVideoFramePool * pool, int * width, int * height, enum AVPixelFormat * format, int * align)
Get the video frame pool configuration.
Parameters
width width of each frame in this pool
height height of each frame in this pool
format format of each frame in this pool
align buffers alignement of each frame in this pool
Returns
0 on success, a negative AVERROR otherwise.
Definition at line 107 of file framepool.c.
Referenced by ff_default_get_video_buffer().
ff_video_frame_pool_get()
AVFrame* ff_video_frame_pool_get (FFVideoFramePool * pool)
Allocate a new AVFrame, reussing old buffers from the pool when available.
This function may be called simultaneously from multiple threads.
Returns
a new AVFrame on success, NULL on error.
Definition at line 125 of file framepool.c.
Referenced by ff_default_get_video_buffer().