FFmpeg: libavutil/frame.c File Reference
frame.c File Reference
#include "channel_layout.h"
#include "avassert.h"
#include "buffer.h"
#include "common.h"
#include "dict.h"
#include "frame.h"
#include "imgutils.h"
#include "mem.h"
#include "samplefmt.h"
Macros
#define CHECK_CHANNELS_CONSISTENCY(frame)
Functions
AVDictionary ** avpriv_frame_get_metadatap (AVFrame *frame)
int av_frame_set_qp_table (AVFrame *f, AVBufferRef *buf, int stride, int qp_type)
int8_t * av_frame_get_qp_table (AVFrame *f, int *stride, int *type)
const char * av_get_colorspace_name (enum AVColorSpace val)
Get the name of a colorspace.
static void get_frame_defaults (AVFrame *frame)
static void free_side_data (AVFrameSideData **ptr_sd)
static void wipe_side_data (AVFrame *frame)
AVFrame * av_frame_alloc (void)
Allocate an AVFrame and set its fields to default values.
void av_frame_free (AVFrame **frame)
Free the frame and any dynamically allocated objects in it, e.g.
static int get_video_buffer (AVFrame *frame, int align)
static int get_audio_buffer (AVFrame *frame, int align)
int av_frame_get_buffer (AVFrame *frame, int align)
Allocate new buffer(s) for audio or video data.
static int frame_copy_props (AVFrame *dst, const AVFrame *src, int force_copy)
int av_frame_ref (AVFrame *dst, const AVFrame *src)
Set up a new reference to the data described by the source frame.
AVFrame * av_frame_clone (const AVFrame *src)
Create a new frame that references the same data as src.
void av_frame_unref (AVFrame *frame)
Unreference all the buffers referenced by frame and reset the frame fields.
void av_frame_move_ref (AVFrame *dst, AVFrame *src)
Move everything contained in src to dst and reset src.
int av_frame_is_writable (AVFrame *frame)
Check if the frame data is writable.
int av_frame_make_writable (AVFrame *frame)
Ensure that the frame data is writable, avoiding data copy if possible.
int av_frame_copy_props (AVFrame *dst, const AVFrame *src)
Copy only "metadata" fields from src to dst.
AVBufferRef * av_frame_get_plane_buffer (AVFrame *frame, int plane)
Get the buffer reference a given data plane is stored in.
AVFrameSideData * av_frame_new_side_data (AVFrame *frame, enum AVFrameSideDataType type, int size)
Add a new side data to a frame.
AVFrameSideData * av_frame_get_side_data (const AVFrame *frame, enum AVFrameSideDataType type)
static int frame_copy_video (AVFrame *dst, const AVFrame *src)
static int frame_copy_audio (AVFrame *dst, const AVFrame *src)
int av_frame_copy (AVFrame *dst, const AVFrame *src)
Copy the frame data from src to dst.
void av_frame_remove_side_data (AVFrame *frame, enum AVFrameSideDataType type)
If side data of the supplied type exists in the frame, free it and remove it from the frame.
const char * av_frame_side_data_name (enum AVFrameSideDataType type)
Macro Definition Documentation
CHECK_CHANNELS_CONSISTENCY
#define CHECK_CHANNELS_CONSISTENCY (frame)
Value:
av_assert2(!(frame)->channel_layout || \
               (frame)->channels == \
               av_get_channel_layout_nb_channels((frame)->channel_layout))
Definition at line 41 of file frame.c.
Referenced by av_frame_get_plane_buffer(), av_frame_ref(), frame_copy_audio(), and get_audio_buffer().
Function Documentation
get_frame_defaults()
static void get_frame_defaults (AVFrame * frame) static
Definition at line 94 of file frame.c.
Referenced by av_frame_alloc(), av_frame_move_ref(), and av_frame_unref().
free_side_data()
static void free_side_data (AVFrameSideData ** ptr_sd) static
Definition at line 124 of file frame.c.
Referenced by av_frame_remove_side_data(), and wipe_side_data().
wipe_side_data()
static void wipe_side_data (AVFrame * frame) static
Definition at line 133 of file frame.c.
Referenced by av_frame_unref(), and frame_copy_props().
get_video_buffer()
static int get_video_buffer (AVFrame * frame, int align) static
Definition at line 167 of file frame.c.
Referenced by av_frame_get_buffer().
get_audio_buffer()
static int get_audio_buffer (AVFrame * frame, int align) static
Definition at line 219 of file frame.c.
Referenced by av_frame_get_buffer().
frame_copy_props()
static int frame_copy_props (AVFrame * dst, const AVFrame * src, int force_copy) static
Definition at line 288 of file frame.c.
Referenced by av_frame_copy_props(), and av_frame_ref().
frame_copy_video()
static int frame_copy_video (AVFrame * dst, const AVFrame * src) static
Definition at line 675 of file frame.c.
Referenced by av_frame_copy().
frame_copy_audio()
static int frame_copy_audio (AVFrame * dst, const AVFrame * src) static
Definition at line 697 of file frame.c.
Referenced by av_frame_copy().