FFmpeg: libavfilter/framequeue.c File Reference
framequeue.c File Reference
#include "libavutil/avassert.h"
#include "framequeue.h"
Functions
static FFFrameBucket * bucket (FFFrameQueue *fq, size_t idx)
void ff_framequeue_global_init (FFFrameQueueGlobal *fqg)
Init a global structure.
static void check_consistency (FFFrameQueue *fq)
void ff_framequeue_init (FFFrameQueue *fq, FFFrameQueueGlobal *fqg)
Init a frame queue and attach it to a global structure.
void ff_framequeue_free (FFFrameQueue *fq)
Free the queue and all queued frames.
int ff_framequeue_add (FFFrameQueue *fq, AVFrame *frame)
Add a frame.
AVFrame * ff_framequeue_take (FFFrameQueue *fq)
Take the first frame in the queue.
AVFrame * ff_framequeue_peek (FFFrameQueue *fq, size_t idx)
Access a frame in the queue, without removing it.
Function Documentation
bucket()
static FFFrameBucket* bucket (FFFrameQueue * fq, size_t idx) inline static
Definition at line 25 of file framequeue.c.
Referenced by check_consistency(), epic_hash_add(), epic_hash_find(), ff_framequeue_add(), ff_framequeue_peek(), and ff_framequeue_take().
ff_framequeue_global_init()
void ff_framequeue_global_init (FFFrameQueueGlobal * fqg)
Init a global structure.
Definition at line 30 of file framequeue.c.
Referenced by avfilter_graph_alloc().
check_consistency()
static void check_consistency (FFFrameQueue * fq) static
Definition at line 34 of file framequeue.c.
Referenced by ff_framequeue_add(), ff_framequeue_peek(), and ff_framequeue_take().
ff_framequeue_init()
void ff_framequeue_init (FFFrameQueue * fq, FFFrameQueueGlobal * fqg)
Init a frame queue and attach it to a global structure.
Definition at line 47 of file framequeue.c.
Referenced by avfilter_link().
ff_framequeue_free()
void ff_framequeue_free (FFFrameQueue * fq)
Free the queue and all queued frames.
Definition at line 53 of file framequeue.c.
Referenced by avfilter_link_free().
ff_framequeue_add()
int ff_framequeue_add (FFFrameQueue * fq, AVFrame * frame)
Add a frame.
Returns
>=0 or an AVERROR code.
Definition at line 63 of file framequeue.c.
Referenced by ff_filter_frame().
ff_framequeue_take()
AVFrame* ff_framequeue_take (FFFrameQueue * fq)
Take the first frame in the queue.
Must not be used with empty queues.
Definition at line 98 of file framequeue.c.
Referenced by ff_filter_frame_to_filter(), ff_framequeue_free(), and take_samples().
ff_framequeue_peek()
AVFrame* ff_framequeue_peek (FFFrameQueue * fq, size_t idx)
Access a frame in the queue, without removing it.
The first frame is numbered 0; the designated frame must exist.
Definition at line 114 of file framequeue.c.
Referenced by take_samples().