FFmpeg: libavcodec/g722dsp.c File Reference
g722dsp.c File Reference
#include "g722dsp.h"
#include "mathops.h"
Functions
static void g722_apply_qmf (const int16_t *prev_samples, int xout[2])
av_cold void ff_g722dsp_init (G722DSPContext *c)
Function Documentation
g722_apply_qmf()
static void g722_apply_qmf (const int16_t * prev_samples, int xout[2]) static
Definition at line 29 of file g722dsp.c.
Referenced by ff_g722dsp_init().
ff_g722dsp_init()
av_cold void ff_g722dsp_init (G722DSPContext * c)
Definition at line 68 of file g722dsp.c.
Referenced by g722_decode_init(), and g722_encode_init().