FFmpeg: libavcodec/g722enc.c File Reference
g722enc.c File Reference
G.722 ADPCM audio encoder.
#include "libavutil/avassert.h"
#include "avcodec.h"
#include "internal.h"
#include "g722.h"
#include "libavutil/common.h"
Macros
#define FREEZE_INTERVAL 128
#define MAX_FRAME_SIZE 32768
#define MIN_TRELLIS 0
#define MAX_TRELLIS 16
#define STORE_NODE(index, UPDATE, VALUE)
Functions
static av_cold int g722_encode_close (AVCodecContext *avctx)
static av_cold int g722_encode_init (AVCodecContext *avctx)
static void filter_samples (G722Context *c, const int16_t *samples, int *xlow, int *xhigh)
static int encode_high (const struct G722Band *state, int xhigh)
static int encode_low (const struct G722Band *state, int xlow)
static void g722_encode_trellis (G722Context *c, int trellis, uint8_t *dst, int nb_samples, const int16_t *samples)
static av_always_inline void encode_byte (G722Context *c, uint8_t *dst, const int16_t *samples)
static void g722_encode_no_trellis (G722Context *c, uint8_t *dst, int nb_samples, const int16_t *samples)
static int g722_encode_frame (AVCodecContext *avctx, AVPacket *avpkt, const AVFrame *frame, int *got_packet_ptr)
Variables
static const int16_t low_quant [33]
AVCodec ff_adpcm_g722_encoder
Detailed Description
G.722 ADPCM audio encoder.
Definition in file g722enc.c.
Macro Definition Documentation
FREEZE_INTERVAL
#define FREEZE_INTERVAL 128
Definition at line 36 of file g722enc.c.
Referenced by g722_encode_init(), and g722_encode_trellis().
MAX_FRAME_SIZE
#define MAX_FRAME_SIZE 32768
Definition at line 40 of file g722enc.c.
Referenced by g722_encode_init().
MIN_TRELLIS
#define MIN_TRELLIS 0
Definition at line 44 of file g722enc.c.
Referenced by g722_encode_init().
MAX_TRELLIS
#define MAX_TRELLIS 16
Definition at line 45 of file g722enc.c.
Referenced by g722_encode_init().
STORE_NODE
#define STORE_NODE (index, UPDATE, VALUE)
Referenced by g722_encode_trellis().
Function Documentation
g722_encode_close()
static av_cold int g722_encode_close (AVCodecContext * avctx) static
Definition at line 47 of file g722enc.c.
Referenced by g722_encode_init().
g722_encode_init()
static av_cold int g722_encode_init (AVCodecContext * avctx) static
Definition at line 59 of file g722enc.c.
filter_samples()
static void filter_samples (G722Context * c, const int16_t * samples, int * xlow, int * xhigh) inline static
Definition at line 138 of file g722enc.c.
Referenced by encode_byte(), and g722_encode_trellis().
encode_high()
static int encode_high (const struct G722Band * state, int xhigh) inline static
Definition at line 155 of file g722enc.c.
Referenced by encode_byte().
encode_low()
static int encode_low (const struct G722Band * state, int xlow) inline static
Definition at line 163 of file g722enc.c.
Referenced by encode_byte(), and g722_encode_trellis().
g722_encode_trellis()
static void g722_encode_trellis (G722Context * c, int trellis, uint8_t * dst, int nb_samples, const int16_t * samples) static
Definition at line 177 of file g722enc.c.
Referenced by g722_encode_frame().
encode_byte()
static av_always_inline void encode_byte (G722Context * c, uint8_t * dst, const int16_t * samples) static
Definition at line 331 of file g722enc.c.
Referenced by g722_encode_frame(), and g722_encode_no_trellis().
g722_encode_no_trellis()
static void g722_encode_no_trellis (G722Context * c, uint8_t * dst, int nb_samples, const int16_t * samples) static
Definition at line 344 of file g722enc.c.
Referenced by g722_encode_frame().
g722_encode_frame()
static int g722_encode_frame (AVCodecContext * avctx, AVPacket * avpkt, const AVFrame * frame, int * got_packet_ptr) static
Definition at line 353 of file g722enc.c.
Variable Documentation
low_quant
const int16_t low_quant[33] static
Initial value:
= {
      35,   72,  110,  150,  190,  233,  276,  323,
     370,  422,  473,  530,  587,  650,  714,  786,
     858,  940, 1023, 1121, 1219, 1339, 1458, 1612,
    1765, 1980, 2195, 2557, 2919
}
Definition at line 131 of file g722enc.c.
Referenced by encode_low().
ff_adpcm_g722_encoder
AVCodec ff_adpcm_g722_encoder
Initial value:
= {
    .name           = "g722",
    .long_name      = NULL_IF_CONFIG_SMALL("G.722 ADPCM"),
    .type           = AVMEDIA_TYPE_AUDIO,
    .id             = AV_CODEC_ID_ADPCM_G722,
    .priv_data_size = sizeof(G722Context),
    .init           = g722_encode_init,
    .close          = g722_encode_close,
    .encode2        = g722_encode_frame,
    .capabilities   = AV_CODEC_CAP_SMALL_LAST_FRAME,
    .sample_fmts    = (const enum AVSampleFormat[]){ AV_SAMPLE_FMT_S16,
                                                     AV_SAMPLE_FMT_NONE },
}
Definition at line 383 of file g722enc.c.