FFmpeg: libavcodec/g722dsp.h File Reference
g722dsp.h File Reference
#include <stdint.h>
Data Structures
struct G722DSPContext
Functions
void ff_g722dsp_init (G722DSPContext *c)
void ff_g722dsp_init_arm (G722DSPContext *c)
void ff_g722dsp_init_x86 (G722DSPContext *c)
Function Documentation
ff_g722dsp_init()
void ff_g722dsp_init (G722DSPContext * c)
Definition at line 68 of file g722dsp.c.
Referenced by g722_decode_init(), and g722_encode_init().
ff_g722dsp_init_arm()
void ff_g722dsp_init_arm (G722DSPContext * c)
Definition at line 29 of file g722dsp_init_arm.c.
Referenced by ff_g722dsp_init().
ff_g722dsp_init_x86()
void ff_g722dsp_init_x86 (G722DSPContext * c)
Definition at line 29 of file g722dsp_init.c.
Referenced by ff_g722dsp_init().