FFmpeg: libavcodec/g722.h File Reference
g722.h File Reference
#include <stdint.h>
#include "avcodec.h"
#include "g722dsp.h"
Data Structures
struct G722Context
struct G722Context::G722Band
The band[0] and band[1] correspond respectively to the lower band and higher band.
struct G722Context::TrellisNode
struct G722Context::TrellisPath
Macros
#define PREV_SAMPLES_BUF_SIZE 1024
Functions
void ff_g722_update_low_predictor (struct G722Band *band, const int ilow)
void ff_g722_update_high_predictor (struct G722Band *band, const int dhigh, const int ihigh)
Variables
const int16_t ff_g722_high_inv_quant [4]
const int16_t ff_g722_low_inv_quant4 [16]
const int16_t ff_g722_low_inv_quant6 [64]
Macro Definition Documentation
PREV_SAMPLES_BUF_SIZE
#define PREV_SAMPLES_BUF_SIZE 1024
Definition at line 32 of file g722.h.
Referenced by filter_samples(), and g722_decode_frame().
Function Documentation
ff_g722_update_low_predictor()
void ff_g722_update_low_predictor (struct G722Band * band, const int ilow)
Definition at line 143 of file g722.c.
Referenced by encode_byte(), g722_decode_frame(), and g722_encode_trellis().
ff_g722_update_high_predictor()
void ff_g722_update_high_predictor (struct G722Band * band, const int dhigh, const int ihigh)
Definition at line 154 of file g722.c.
Referenced by encode_byte(), g722_decode_frame(), and g722_encode_trellis().
Variable Documentation
ff_g722_high_inv_quant
const int16_t ff_g722_high_inv_quant[4]
Definition at line 51 of file g722.c.
Referenced by encode_byte(), g722_decode_frame(), and g722_encode_trellis().
ff_g722_low_inv_quant4
const int16_t ff_g722_low_inv_quant4[16]
Definition at line 59 of file g722.c.
Referenced by ff_g722_update_low_predictor().
ff_g722_low_inv_quant6
const int16_t ff_g722_low_inv_quant6[64]
Definition at line 63 of file g722.c.
Referenced by g722_encode_trellis().