FFmpeg: libavcodec/g723_1enc.c File Reference
g723_1enc.c File Reference
G.723.1 compatible encoder.
#include <stdint.h>
#include <string.h>
#include "libavutil/channel_layout.h"
#include "libavutil/common.h"
#include "libavutil/mem.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "celp_math.h"
#include "g723_1.h"
#include "internal.h"
#include "put_bits.h"
Macros
#define BITSTREAM_WRITER_LE
#define get_index(num, offset, size)
Quantize the current LSP subvector.
Functions
static av_cold int g723_1_encode_init (AVCodecContext *avctx)
static void highpass_filter (int16_t *buf, int16_t *fir, int *iir)
Remove DC component from the input signal.
static void comp_autocorr (int16_t *buf, int16_t *autocorr)
Estimate autocorrelation of the input vector.
static void levinson_durbin (int16_t *lpc, int16_t *autocorr, int16_t error)
Use Levinson-Durbin recursion to compute LPC coefficients from autocorrelation values.
static void comp_lpc_coeff (int16_t *buf, int16_t *lpc)
Calculate LPC coefficients for the current frame.
static void lpc2lsp (int16_t *lpc, int16_t *prev_lsp, int16_t *lsp)
static void lsp_quantize (uint8_t *lsp_index, int16_t *lsp, int16_t *prev_lsp)
Vector quantize the LSP frequencies.
static void iir_filter (int16_t *fir_coef, int16_t *iir_coef, int16_t *src, int16_t *dest)
Perform IIR filtering.
static void perceptual_filter (G723_1_Context *p, int16_t *flt_coef, int16_t *unq_lpc, int16_t *buf)
Apply the formant perceptual weighting filter.
static int estimate_pitch (int16_t *buf, int start)
Estimate the open loop pitch period.
static void comp_harmonic_coeff (int16_t *buf, int16_t pitch_lag, HFParam *hf)
Compute harmonic noise filter parameters.
static void harmonic_filter (HFParam *hf, const int16_t *src, int16_t *dest)
Apply the harmonic noise shaping filter.
static void harmonic_noise_sub (HFParam *hf, const int16_t *src, int16_t *dest)
static void synth_percept_filter (int16_t *qnt_lpc, int16_t *perf_lpc, int16_t *perf_fir, int16_t *perf_iir, const int16_t *src, int16_t *dest, int scale)
Combined synthesis and formant perceptual weighting filer.
static void acb_search (G723_1_Context *p, int16_t *residual, int16_t *impulse_resp, const int16_t *buf, int index)
Compute the adaptive codebook contribution.
static void sub_acb_contrib (const int16_t *residual, const int16_t *impulse_resp, int16_t *buf)
Subtract the adaptive codebook contribution from the input to obtain the residual.
static void get_fcb_param (FCBParam *optim, int16_t *impulse_resp, int16_t *buf, int pulse_cnt, int pitch_lag)
Quantize the residual signal using the fixed codebook (MP-MLQ).
static void pack_fcb_param (G723_1_Subframe *subfrm, FCBParam *optim, int16_t *buf, int pulse_cnt)
Encode the pulse position and gain of the current subframe.
static void fcb_search (G723_1_Context *p, int16_t *impulse_resp, int16_t *buf, int index)
Compute the fixed codebook excitation.
static int pack_bitstream (G723_1_Context *p, AVPacket *avpkt)
Pack the frame parameters into output bitstream.
static int g723_1_encode_frame (AVCodecContext *avctx, AVPacket *avpkt, const AVFrame *frame, int *got_packet_ptr)
Variables
AVCodec ff_g723_1_encoder
Detailed Description
G.723.1 compatible encoder.
Definition in file g723_1enc.c.
Macro Definition Documentation
BITSTREAM_WRITER_LE
#define BITSTREAM_WRITER_LE
Definition at line 40 of file g723_1enc.c.
get_index
#define get_index (num, offset, size)
Value:
{                                                                             \
    int error, max = -1;                                                      \
    int16_t temp[4];                                                          \
    int i, j;                                                                 \
                                                                              \
    for (i = 0; i < LSP_CB_SIZE; i++) {                                       \
        for (j = 0; j < size; j++){                                           \
            temp[j] = (weight[j + (offset)] * lsp_band##num[i][j] +           \
                      (1 << 14)) >> 15;                                       \
        }                                                                     \
        error  = ff_g723_1_dot_product(lsp + (offset), temp, size) << 1;      \
        error -= ff_g723_1_dot_product(lsp_band##num[i], temp, size);         \
        if (error > max) {                                                    \
            max = error;                                                      \
            lsp_index[num] = i;                                               \
        }                                                                     \
    }                                                                         \
}
Quantize the current LSP subvector.
Parameters
num band number
offset offset of the current subvector in an LPC_ORDER vector
size size of the current subvector
Definition at line 291 of file g723_1enc.c.
Referenced by lsp_quantize().
Function Documentation
g723_1_encode_init()
static av_cold int g723_1_encode_init (AVCodecContext * avctx) static
Definition at line 43 of file g723_1enc.c.
highpass_filter()
static void highpass_filter (int16_t * buf, int16_t * fir, int * iir) static
Remove DC component from the input signal.
Parameters
buf input signal
fir zero memory
iir pole memory
Definition at line 79 of file g723_1enc.c.
Referenced by g723_1_encode_frame().
comp_autocorr()
static void comp_autocorr (int16_t * buf, int16_t * autocorr) static
Estimate autocorrelation of the input vector.
Parameters
buf input buffer
autocorr autocorrelation coefficients vector
Definition at line 95 of file g723_1enc.c.
Referenced by comp_lpc_coeff().
levinson_durbin()
static void levinson_durbin (int16_t * lpc, int16_t * autocorr, int16_t error) static
Use Levinson-Durbin recursion to compute LPC coefficients from autocorrelation values.
Parameters
lpc LPC coefficients vector
autocorr autocorrelation coefficients vector
error prediction error
Definition at line 137 of file g723_1enc.c.
Referenced by comp_lpc_coeff().
comp_lpc_coeff()
static void comp_lpc_coeff (int16_t * buf, int16_t * lpc) static
Calculate LPC coefficients for the current frame.
Parameters
buf current frame
prev_data 2 trailing subframes of the previous frame
lpc LPC coefficients vector
Definition at line 181 of file g723_1enc.c.
Referenced by g723_1_encode_frame().
lpc2lsp()
static void lpc2lsp (int16_t * lpc, int16_t * prev_lsp, int16_t * lsp) static
< coefficients of the sum and difference polynomials (F1, F2) ordered as f1[0], f2[0], ...., f1[5], f2[5]
Evaluate F1 and F2 at uniform intervals of pi/256 along the unit circle and check for zero crossings.
Definition at line 197 of file g723_1enc.c.
Referenced by g723_1_encode_frame().
lsp_quantize()
static void lsp_quantize (uint8_t * lsp_index, int16_t * lsp, int16_t * prev_lsp) static
Vector quantize the LSP frequencies.
Parameters
lsp the current lsp vector
prev_lsp the previous lsp vector
Definition at line 317 of file g723_1enc.c.
Referenced by g723_1_encode_frame().
iir_filter()
static void iir_filter (int16_t * fir_coef, int16_t * iir_coef, int16_t * src, int16_t * dest) static
Perform IIR filtering.
Parameters
fir_coef FIR coefficients
iir_coef IIR coefficients
src source vector
dest destination vector
Definition at line 365 of file g723_1enc.c.
Referenced by perceptual_filter().
perceptual_filter()
static void perceptual_filter (G723_1_Context * p, int16_t * flt_coef, int16_t * unq_lpc, int16_t * buf) static
Apply the formant perceptual weighting filter.
Parameters
flt_coef filter coefficients
unq_lpc unquantized lpc vector
Definition at line 388 of file g723_1enc.c.
Referenced by g723_1_encode_frame().
estimate_pitch()
static int estimate_pitch (int16_t * buf, int start) static
Estimate the open loop pitch period.
Parameters
buf perceptually weighted speech
start estimation is carried out from this position
Definition at line 420 of file g723_1enc.c.
Referenced by g723_1_encode_frame().
comp_harmonic_coeff()
static void comp_harmonic_coeff (int16_t * buf, int16_t pitch_lag, HFParam * hf) static
Compute harmonic noise filter parameters.
Parameters
buf perceptually weighted speech
pitch_lag open loop pitch period
hf harmonic filter parameters
Definition at line 493 of file g723_1enc.c.
Referenced by g723_1_encode_frame().
harmonic_filter()
static void harmonic_filter (HFParam * hf, const int16_t * src, int16_t * dest) static
Apply the harmonic noise shaping filter.
Parameters
hf filter parameters
Definition at line 566 of file g723_1enc.c.
Referenced by g723_1_encode_frame().
harmonic_noise_sub()
static void harmonic_noise_sub (HFParam * hf, const int16_t * src, int16_t * dest) static
Definition at line 576 of file g723_1enc.c.
Referenced by g723_1_encode_frame().
synth_percept_filter()
static void synth_percept_filter (int16_t * qnt_lpc, int16_t * perf_lpc, int16_t * perf_fir, int16_t * perf_iir, const int16_t * src, int16_t * dest, int scale) static
Combined synthesis and formant perceptual weighting filer.
Parameters
qnt_lpc quantized lpc coefficients
perf_lpc perceptual filter coefficients
perf_fir perceptual filter fir memory
perf_iir perceptual filter iir memory
scale the filter output will be scaled by 2^scale
Definition at line 595 of file g723_1enc.c.
Referenced by g723_1_encode_frame().
acb_search()
static void acb_search (G723_1_Context * p, int16_t * residual, int16_t * impulse_resp, const int16_t * buf, int index) static
Compute the adaptive codebook contribution.
Parameters
buf input signal
index the current subframe index
Definition at line 637 of file g723_1enc.c.
Referenced by g723_1_encode_frame().
sub_acb_contrib()
static void sub_acb_contrib (const int16_t * residual, const int16_t * impulse_resp, int16_t * buf) static
Subtract the adaptive codebook contribution from the input to obtain the residual.
Parameters
buf target vector
Definition at line 755 of file g723_1enc.c.
Referenced by g723_1_encode_frame().
get_fcb_param()
static void get_fcb_param (FCBParam * optim, int16_t * impulse_resp, int16_t * buf, int pulse_cnt, int pitch_lag) static
Quantize the residual signal using the fixed codebook (MP-MLQ).
Parameters
optim optimized fixed codebook parameters
buf excitation vector
Definition at line 775 of file g723_1enc.c.
Referenced by fcb_search().
pack_fcb_param()
static void pack_fcb_param (G723_1_Subframe * subfrm, FCBParam * optim, int16_t * buf, int pulse_cnt) static
Encode the pulse position and gain of the current subframe.
Parameters
optim optimized fixed CB parameters
buf excitation vector
Definition at line 930 of file g723_1enc.c.
Referenced by fcb_search().
fcb_search()
static void fcb_search (G723_1_Context * p, int16_t * impulse_resp, int16_t * buf, int index) static
Compute the fixed codebook excitation.
Parameters
buf target vector
impulse_resp impulse response of the combined filter
Definition at line 965 of file g723_1enc.c.
Referenced by g723_1_encode_frame().
pack_bitstream()
static int pack_bitstream (G723_1_Context * p, AVPacket * avpkt) static
Pack the frame parameters into output bitstream.
Parameters
frame output buffer
size size of the buffer
Definition at line 997 of file g723_1enc.c.
Referenced by g723_1_encode_frame().
g723_1_encode_frame()
static int g723_1_encode_frame (AVCodecContext * avctx, AVPacket * avpkt, const AVFrame * frame, int * got_packet_ptr) static
Compute the combined impulse response of the synthesis filter, formant perceptual weighting filter and harmonic noise shaping filter
Definition at line 1055 of file g723_1enc.c.
Variable Documentation
ff_g723_1_encoder
AVCodec ff_g723_1_encoder
Initial value:
= {
    .name           = "g723_1",
    .long_name      = NULL_IF_CONFIG_SMALL("G.723.1"),
    .type           = AVMEDIA_TYPE_AUDIO,
    .id             = AV_CODEC_ID_G723_1,
    .priv_data_size = sizeof(G723_1_Context),
    .init           = g723_1_encode_init,
    .encode2        = g723_1_encode_frame,
    .sample_fmts    = (const enum AVSampleFormat[]) {
        AV_SAMPLE_FMT_S16, AV_SAMPLE_FMT_NONE
    },
}
Definition at line 1191 of file g723_1enc.c.