FFmpeg: libavcodec/g723_1dec.c File Reference
g723_1dec.c File Reference
G.723.1 compatible decoder.
#include "libavutil/channel_layout.h"
#include "libavutil/mem.h"
#include "libavutil/opt.h"
#include "acelp_vectors.h"
#include "avcodec.h"
#include "celp_filters.h"
#include "celp_math.h"
#include "get_bits.h"
#include "internal.h"
#include "g723_1.h"
Macros
#define BITSTREAM_READER_LE
#define CNG_RANDOM_SEED 12345
#define iir_filter(fir_coef, iir_coef, src, dest, width)
Perform IIR filtering.
#define OFFSET(x) offsetof(G723_1_Context, x)
#define AD AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_DECODING_PARAM
Functions
static av_cold int g723_1_decode_init (AVCodecContext *avctx)
static int unpack_bitstream (G723_1_Context *p, const uint8_t *buf, int buf_size)
Unpack the frame into parameters.
static int16_t square_root (unsigned val)
Bitexact implementation of sqrt(val/2).
static void gen_fcb_excitation (int16_t *vector, G723_1_Subframe *subfrm, enum Rate cur_rate, int pitch_lag, int index)
Generate fixed codebook excitation vector.
static int autocorr_max (const int16_t *buf, int offset, int *ccr_max, int pitch_lag, int length, int dir)
Estimate maximum auto-correlation around pitch lag.
static void comp_ppf_gains (int lag, PPFParam *ppf, enum Rate cur_rate, int tgt_eng, int ccr, int res_eng)
Calculate pitch postfilter optimal and scaling gains.
static void comp_ppf_coeff (G723_1_Context *p, int offset, int pitch_lag, PPFParam *ppf, enum Rate cur_rate)
Calculate pitch postfilter parameters.
static int comp_interp_index (G723_1_Context *p, int pitch_lag, int *exc_eng, int *scale)
Classify frames as voiced/unvoiced.
static void residual_interp (int16_t *buf, int16_t *out, int lag, int gain, int *rseed)
Perform residual interpolation based on frame classification.
static void gain_scale (G723_1_Context *p, int16_t *buf, int energy)
Adjust gain of postfiltered signal.
static void formant_postfilter (G723_1_Context *p, int16_t *lpc, int16_t *buf, int16_t *dst)
Perform formant filtering.
static int sid_gain_to_lsp_index (int gain)
static int cng_rand (int *state, int base)
static int estimate_sid_gain (G723_1_Context *p)
static void generate_noise (G723_1_Context *p)
static int g723_1_decode_frame (AVCodecContext *avctx, void *data, int *got_frame_ptr, AVPacket *avpkt)
Variables
static const AVOption options []
static const AVClass g723_1dec_class
AVCodec ff_g723_1_decoder
Detailed Description
G.723.1 compatible decoder.
Definition in file g723_1dec.c.
Macro Definition Documentation
BITSTREAM_READER_LE
#define BITSTREAM_READER_LE
Definition at line 32 of file g723_1dec.c.
CNG_RANDOM_SEED
#define CNG_RANDOM_SEED 12345
Definition at line 41 of file g723_1dec.c.
Referenced by g723_1_decode_frame(), and g723_1_decode_init().
iir_filter
#define iir_filter (fir_coef, iir_coef, src, dest, width)
Value:
{\
    int m, n;\
    int res_shift = 16 & ~-(width);\
    int in_shift  = 16 - res_shift;\
\
    for (m = 0; m < SUBFRAME_LEN; m++) {\
        int64_t filter = 0;\
        for (n = 1; n <= LPC_ORDER; n++) {\
            filter -= (fir_coef)[n - 1] * (src)[m - n] -\
                      (iir_coef)[n - 1] * ((dest)[m - n] >> in_shift);\
        }\
\
        (dest)[m] = av_clipl_int32(((src)[m] << 16) + (filter << 3) +\
                                   (1 << 15)) >> res_shift;\
    }\
}
Perform IIR filtering.
Parameters
fir_coef FIR coefficients
iir_coef IIR coefficients
src source vector
dest destination vector
width width of the output, 16 bits(0) / 32 bits(1)
Definition at line 507 of file g723_1dec.c.
Referenced by formant_postfilter().
OFFSET
#define OFFSET (x) offsetof(G723_1_Context, x)
Definition at line 1001 of file g723_1dec.c.
AD
#define AD AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_DECODING_PARAM
Definition at line 1002 of file g723_1dec.c.
Function Documentation
g723_1_decode_init()
static av_cold int g723_1_decode_init (AVCodecContext * avctx) static
Definition at line 43 of file g723_1dec.c.
unpack_bitstream()
static int unpack_bitstream (G723_1_Context * p, const uint8_t * buf, int buf_size) static
Unpack the frame into parameters.
Parameters
p the context
buf pointer to the input buffer
buf_size size of the input buffer
Definition at line 68 of file g723_1dec.c.
Referenced by g723_1_decode_frame().
square_root()
static int16_t square_root (unsigned val) static
Bitexact implementation of sqrt(val/2).
Definition at line 183 of file g723_1dec.c.
Referenced by comp_ppf_gains(), gain_scale(), and generate_noise().
gen_fcb_excitation()
static void gen_fcb_excitation (int16_t * vector, G723_1_Subframe * subfrm, enum Rate cur_rate, int pitch_lag, int index) static
Generate fixed codebook excitation vector.
Parameters
vector decoded excitation vector
subfrm current subframe
cur_rate current bitrate
pitch_lag closed loop pitch lag
index current subframe index
Definition at line 199 of file g723_1dec.c.
Referenced by g723_1_decode_frame().
autocorr_max()
static int autocorr_max (const int16_t * buf, int offset, int * ccr_max, int pitch_lag, int length, int dir) static
Estimate maximum auto-correlation around pitch lag.
Parameters
buf buffer with offset applied
offset offset of the excitation vector
ccr_max pointer to the maximum auto-correlation
pitch_lag decoded pitch lag
length length of autocorrelation
dir forward lag(1) / backward lag(-1)
Definition at line 266 of file g723_1dec.c.
Referenced by comp_interp_index(), and comp_ppf_coeff().
comp_ppf_gains()
static void comp_ppf_gains (int lag, PPFParam * ppf, enum Rate cur_rate, int tgt_eng, int ccr, int res_eng) static
Calculate pitch postfilter optimal and scaling gains.
Parameters
lag pitch postfilter forward/backward lag
ppf pitch postfilter parameters
cur_rate current bitrate
tgt_eng target energy
ccr cross-correlation
res_eng residual energy
Definition at line 299 of file g723_1dec.c.
Referenced by comp_ppf_coeff().
comp_ppf_coeff()
static void comp_ppf_coeff (G723_1_Context * p, int offset, int pitch_lag, PPFParam * ppf, enum Rate cur_rate) static
Calculate pitch postfilter parameters.
Parameters
p the context
offset offset of the excitation vector
pitch_lag decoded pitch lag
ppf pitch postfilter parameters
cur_rate current bitrate
Definition at line 347 of file g723_1dec.c.
Referenced by g723_1_decode_frame().
comp_interp_index()
static int comp_interp_index (G723_1_Context * p, int pitch_lag, int * exc_eng, int * scale) static
Classify frames as voiced/unvoiced.
Parameters
p the context
pitch_lag decoded pitch_lag
exc_eng excitation energy estimation
scale scaling factor of exc_eng
Returns
residual interpolation index if voiced, 0 otherwise
Definition at line 433 of file g723_1dec.c.
Referenced by g723_1_decode_frame().
residual_interp()
static void residual_interp (int16_t * buf, int16_t * out, int lag, int gain, int * rseed) static
Perform residual interpolation based on frame classification.
Parameters
buf decoded excitation vector
out output vector
lag decoded pitch lag
gain interpolated gain
rseed seed for random number generator
Definition at line 478 of file g723_1dec.c.
Referenced by g723_1_decode_frame().
gain_scale()
static void gain_scale (G723_1_Context * p, int16_t * buf, int energy) static
Adjust gain of postfiltered signal.
Parameters
p the context
buf postfiltered output vector
energy input energy coefficient
Definition at line 532 of file g723_1dec.c.
Referenced by formant_postfilter().
formant_postfilter()
static void formant_postfilter (G723_1_Context * p, int16_t * lpc, int16_t * buf, int16_t * dst) static
Perform formant filtering.
Parameters
p the context
lpc quantized lpc coefficients
buf input buffer
dst output buffer
Definition at line 575 of file g723_1dec.c.
Referenced by g723_1_decode_frame().
sid_gain_to_lsp_index()
static int sid_gain_to_lsp_index (int gain) static
Definition at line 642 of file g723_1dec.c.
Referenced by g723_1_decode_frame().
cng_rand()
static int cng_rand (int * state, int base) inline static
Definition at line 652 of file g723_1dec.c.
Referenced by generate_noise().
estimate_sid_gain()
static int estimate_sid_gain (G723_1_Context * p) static
Definition at line 658 of file g723_1dec.c.
Referenced by g723_1_decode_frame().
generate_noise()
static void generate_noise (G723_1_Context * p) static
Definition at line 712 of file g723_1dec.c.
Referenced by g723_1_decode_frame().
g723_1_decode_frame()
static int g723_1_decode_frame (AVCodecContext * avctx, void * data, int * got_frame_ptr, AVPacket * avpkt) static
Definition at line 837 of file g723_1dec.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "postfilter", "enable postfilter", OFFSET(postfilter), AV_OPT_TYPE_BOOL,
      { .i64 = 1 }, 0, 1, AD },
    { NULL }
}
Definition at line 1004 of file g723_1dec.c.
g723_1dec_class
const AVClass g723_1dec_class static
Initial value:
= {
    .class_name = "G.723.1 decoder",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1011 of file g723_1dec.c.
ff_g723_1_decoder
AVCodec ff_g723_1_decoder
Initial value:
= {
    .name           = "g723_1",
    .long_name      = NULL_IF_CONFIG_SMALL("G.723.1"),
    .type           = AVMEDIA_TYPE_AUDIO,
    .id             = AV_CODEC_ID_G723_1,
    .priv_data_size = sizeof(G723_1_Context),
    .init           = g723_1_decode_init,
    .decode         = g723_1_decode_frame,
    .capabilities   = AV_CODEC_CAP_SUBFRAMES | AV_CODEC_CAP_DR1,
    .priv_class     = &g723_1dec_class,
}
Definition at line 1018 of file g723_1dec.c.