FFmpeg: libavcodec/get_bits.h File Reference
get_bits.h File Reference
bitstream reader API header.
#include <stdint.h>
#include "libavutil/common.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/log.h"
#include "libavutil/avassert.h"
#include "mathops.h"
#include "vlc.h"
Data Structures
struct GetBitContext
Macros
#define UNCHECKED_BITSTREAM_READER !CONFIG_SAFE_BITSTREAM_READER
#define MIN_CACHE_BITS 25
#define OPEN_READER_NOSIZE(name, gb)
#define OPEN_READER(name, gb) OPEN_READER_NOSIZE(name, gb)
#define BITS_AVAILABLE(name, gb) 1
#define CLOSE_READER(name, gb) (gb)->index = name ## _index
#define UPDATE_CACHE_LE(name, gb)
#define UPDATE_CACHE_BE(name, gb)
#define UPDATE_CACHE(name, gb) UPDATE_CACHE_BE(name, gb)
#define SKIP_CACHE(name, gb, num) name ## _cache <<= (num)
#define SKIP_COUNTER(name, gb, num) name ## _index += (num)
#define BITS_LEFT(name, gb) ((int)((gb)->size_in_bits - name ## _index))
#define SKIP_BITS(name, gb, num)
#define LAST_SKIP_BITS(name, gb, num) SKIP_COUNTER(name, gb, num)
#define SHOW_UBITS_LE(name, gb, num) zero_extend(name ## _cache, num)
#define SHOW_SBITS_LE(name, gb, num) sign_extend(name ## _cache, num)
#define SHOW_UBITS_BE(name, gb, num) NEG_USR32(name ## _cache, num)
#define SHOW_SBITS_BE(name, gb, num) NEG_SSR32(name ## _cache, num)
#define SHOW_UBITS(name, gb, num) SHOW_UBITS_BE(name, gb, num)
#define SHOW_SBITS(name, gb, num) SHOW_SBITS_BE(name, gb, num)
#define GET_CACHE(name, gb) ((uint32_t) name ## _cache)
#define GET_VLC(code, name, gb, table, bits, max_depth)
If the vlc code is invalid and max_depth=1, then no bits will be removed.
#define GET_RL_VLC(level, run, name, gb, table, bits, max_depth, need_update)
Functions
static int get_bits_count (const GetBitContext *s)
static void skip_bits_long (GetBitContext *s, int n)
static int get_xbits (GetBitContext *s, int n)
Read MPEG-1 dc-style VLC (sign bit + mantissa with no MSB).
static int get_sbits (GetBitContext *s, int n)
static unsigned int get_bits (GetBitContext *s, int n)
Read 1-25 bits.
static av_always_inline int get_bitsz (GetBitContext *s, int n)
Read 0-25 bits.
static unsigned int get_bits_le (GetBitContext *s, int n)
static unsigned int show_bits (GetBitContext *s, int n)
Show 1-25 bits.
static void skip_bits (GetBitContext *s, int n)
static unsigned int get_bits1 (GetBitContext *s)
static unsigned int show_bits1 (GetBitContext *s)
static void skip_bits1 (GetBitContext *s)
static unsigned int get_bits_long (GetBitContext *s, int n)
Read 0-32 bits.
static uint64_t get_bits64 (GetBitContext *s, int n)
Read 0-64 bits.
static int get_sbits_long (GetBitContext *s, int n)
Read 0-32 bits as a signed integer.
static unsigned int show_bits_long (GetBitContext *s, int n)
Show 0-32 bits.
static int check_marker (void *logctx, GetBitContext *s, const char *msg)
static int init_get_bits (GetBitContext *s, const uint8_t *buffer, int bit_size)
Initialize GetBitContext.
static int init_get_bits8 (GetBitContext *s, const uint8_t *buffer, int byte_size)
Initialize GetBitContext.
static const uint8_t * align_get_bits (GetBitContext *s)
static av_always_inline int get_vlc2 (GetBitContext *s, VLC_TYPE(*table)[2], int bits, int max_depth)
Parse a vlc code.
static int decode012 (GetBitContext *gb)
static int decode210 (GetBitContext *gb)
static int get_bits_left (GetBitContext *gb)
static int skip_1stop_8data_bits (GetBitContext *gb)
Detailed Description
bitstream reader API header.
Definition in file get_bits.h.
Macro Definition Documentation
UNCHECKED_BITSTREAM_READER
#define UNCHECKED_BITSTREAM_READER !CONFIG_SAFE_BITSTREAM_READER
Definition at line 52 of file get_bits.h.
MIN_CACHE_BITS
#define MIN_CACHE_BITS 25
Definition at line 112 of file get_bits.h.
Referenced by ape_decode_value_3860(), bit_copy(), decode_block(), decode_block_progressive(), ff_wma_init(), get_bits_long(), get_ur_golomb_jpegls(), show_bits_long(), tgv_decode_inter(), and tta_decode_frame().
OPEN_READER_NOSIZE
#define OPEN_READER_NOSIZE (name, gb)
Value:
unsigned int name ## _index = (gb)->index;  \
    unsigned int av_unused name ## _cache
Definition at line 115 of file get_bits.h.
Referenced by dv_decode_ac(), and show_bits().
OPEN_READER
#define OPEN_READER (name, gb) OPEN_READER_NOSIZE(name, gb)
Definition at line 120 of file get_bits.h.
Referenced by cfhd_decode(), decode_422_bitstream(), decode_ac_coeffs(), decode_bgr_1(), decode_block(), decode_block_intra(), decode_block_progressive(), decode_block_refinement(), decode_dc_coeffs(), decode_gray_bitstream(), decode_plane_bitstream(), decode_spectrum_and_dequant(), decode_vlc_codeword(), dnxhd_decode_dct_block(), ff_mpeg1_decode_block_intra(), ff_msmpeg4_decode_block(), get_bits(), get_bits_le(), get_interleaved_se_golomb(), get_interleaved_ue_golomb(), get_level_prefix(), get_sbits(), get_se_golomb(), get_ue_golomb(), get_ue_golomb_31(), get_ur_golomb(), get_ur_golomb_jpegls(), get_vlc2(), get_xbits(), h261_decode_block(), h263_decode_block(), mdec_decode_block_intra(), mpeg1_decode_block_inter(), mpeg1_fast_decode_block_inter(), mpeg2_decode_block_intra(), mpeg2_decode_block_non_intra(), mpeg2_fast_decode_block_intra(), mpeg2_fast_decode_block_non_intra(), mpeg4_decode_block(), read_argb_line(), read_rgb24_component_line(), read_yuv_component_line(), skip_bits(), and webp_get_vlc().
BITS_AVAILABLE
#define BITS_AVAILABLE (name, gb) 1
Definition at line 122 of file get_bits.h.
Referenced by get_interleaved_ue_golomb().
CLOSE_READER
#define CLOSE_READER (name, gb) (gb)->index = name ## _index
Definition at line 131 of file get_bits.h.
Referenced by cfhd_decode(), decode_422_bitstream(), decode_ac_coeffs(), decode_bgr_1(), decode_block(), decode_block_intra(), decode_block_progressive(), decode_block_refinement(), decode_dc_coeffs(), decode_gray_bitstream(), decode_plane_bitstream(), decode_spectrum_and_dequant(), decode_vlc_codeword(), dnxhd_decode_dct_block(), dv_decode_ac(), ff_mpeg1_decode_block_intra(), ff_msmpeg4_decode_block(), get_bits(), get_bits_le(), get_interleaved_se_golomb(), get_interleaved_ue_golomb(), get_level_prefix(), get_sbits(), get_se_golomb(), get_ue_golomb(), get_ue_golomb_31(), get_ur_golomb(), get_ur_golomb_jpegls(), get_vlc2(), get_xbits(), h261_decode_block(), h263_decode_block(), mdec_decode_block_intra(), mpeg1_decode_block_inter(), mpeg1_fast_decode_block_inter(), mpeg2_decode_block_intra(), mpeg2_decode_block_non_intra(), mpeg2_fast_decode_block_intra(), mpeg2_fast_decode_block_non_intra(), mpeg4_decode_block(), read_argb_line(), read_rgb24_component_line(), read_yuv_component_line(), skip_bits(), and webp_get_vlc().
UPDATE_CACHE_LE
#define UPDATE_CACHE_LE (name, gb)
Value:
name ## _cache = \
      AV_RL32((gb)->buffer + (name ## _index >> 3)) >> (name ## _index & 7)
Definition at line 143 of file get_bits.h.
Referenced by get_bits_le().
UPDATE_CACHE_BE
#define UPDATE_CACHE_BE (name, gb)
Value:
name ## _cache = \
      AV_RB32((gb)->buffer + (name ## _index >> 3)) << (name ## _index & 7)
Definition at line 146 of file get_bits.h.
UPDATE_CACHE
#define UPDATE_CACHE (name, gb) UPDATE_CACHE_BE(name, gb)
Definition at line 160 of file get_bits.h.
Referenced by cfhd_decode(), decode_ac_coeffs(), decode_bgr_1(), decode_block(), decode_block_intra(), decode_block_progressive(), decode_block_refinement(), decode_plane_bitstream(), decode_spectrum_and_dequant(), decode_vlc_codeword(), dnxhd_decode_dct_block(), dv_decode_ac(), ff_mpeg1_decode_block_intra(), ff_msmpeg4_decode_block(), get_bits(), get_interleaved_se_golomb(), get_interleaved_ue_golomb(), get_level_prefix(), get_sbits(), get_se_golomb(), get_ue_golomb(), get_ue_golomb_31(), get_ur_golomb(), get_ur_golomb_jpegls(), get_vlc2(), get_xbits(), h261_decode_block(), h263_decode_block(), mdec_decode_block_intra(), mpeg1_decode_block_inter(), mpeg1_fast_decode_block_inter(), mpeg2_decode_block_intra(), mpeg2_decode_block_non_intra(), mpeg2_fast_decode_block_intra(), mpeg2_fast_decode_block_non_intra(), mpeg4_decode_block(), read_argb_line(), read_rgb24_component_line(), read_yuv_component_line(), show_bits(), and webp_get_vlc().
SKIP_CACHE
#define SKIP_CACHE (name, gb, num) name ## _cache <<= (num)
Definition at line 162 of file get_bits.h.
Referenced by ff_msmpeg4_decode_block(), h261_decode_block(), h263_decode_block(), and mpeg4_decode_block().
SKIP_COUNTER
#define SKIP_COUNTER (name, gb, num) name ## _index += (num)
Definition at line 167 of file get_bits.h.
Referenced by ff_msmpeg4_decode_block(), h261_decode_block(), h263_decode_block(), and mpeg4_decode_block().
BITS_LEFT
#define BITS_LEFT (name, gb) ((int)((gb)->size_in_bits - name ## _index))
Definition at line 173 of file get_bits.h.
Referenced by decode_422_bitstream(), decode_bgr_1(), decode_gray_bitstream(), and decode_plane_bitstream().
SKIP_BITS
#define SKIP_BITS (name, gb, num)
Value:
do {                                        \
        SKIP_CACHE(name, gb, num);              \
        SKIP_COUNTER(name, gb, num);            \
    } while (0)
Definition at line 175 of file get_bits.h.
Referenced by decode_ac_coeffs(), decode_block_intra(), decode_spectrum_and_dequant(), dnxhd_decode_dct_block(), ff_mpeg1_decode_block_intra(), ff_msmpeg4_decode_block(), get_ur_golomb_jpegls(), mdec_decode_block_intra(), mpeg1_decode_block_inter(), mpeg1_fast_decode_block_inter(), mpeg2_decode_block_intra(), mpeg2_decode_block_non_intra(), mpeg2_fast_decode_block_intra(), mpeg2_fast_decode_block_non_intra(), mpeg4_decode_block(), and webp_get_vlc().
LAST_SKIP_BITS
#define LAST_SKIP_BITS (name, gb, num) SKIP_COUNTER(name, gb, num)
Definition at line 181 of file get_bits.h.
Referenced by decode_bgr_1(), decode_block(), decode_block_intra(), decode_block_progressive(), decode_block_refinement(), decode_spectrum_and_dequant(), decode_vlc_codeword(), dnxhd_decode_dct_block(), ff_mpeg1_decode_block_intra(), ff_msmpeg4_decode_block(), get_bits(), get_bits_le(), get_interleaved_se_golomb(), get_interleaved_ue_golomb(), get_level_prefix(), get_sbits(), get_se_golomb(), get_ue_golomb(), get_ue_golomb_31(), get_ur_golomb(), get_ur_golomb_jpegls(), get_xbits(), mdec_decode_block_intra(), mpeg1_decode_block_inter(), mpeg1_fast_decode_block_inter(), mpeg2_decode_block_intra(), mpeg2_decode_block_non_intra(), mpeg2_fast_decode_block_intra(), mpeg2_fast_decode_block_non_intra(), mpeg4_decode_block(), skip_bits(), and webp_get_vlc().
SHOW_UBITS_LE
#define SHOW_UBITS_LE (name, gb, num) zero_extend(name ## _cache, num)
Definition at line 183 of file get_bits.h.
Referenced by get_bits_le().
SHOW_SBITS_LE
#define SHOW_SBITS_LE (name, gb, num) sign_extend(name ## _cache, num)
Definition at line 184 of file get_bits.h.
SHOW_UBITS_BE
#define SHOW_UBITS_BE (name, gb, num) NEG_USR32(name ## _cache, num)
Definition at line 186 of file get_bits.h.
SHOW_SBITS_BE
#define SHOW_SBITS_BE (name, gb, num) NEG_SSR32(name ## _cache, num)
Definition at line 187 of file get_bits.h.
SHOW_UBITS
#define SHOW_UBITS (name, gb, num) SHOW_UBITS_BE(name, gb, num)
Definition at line 193 of file get_bits.h.
Referenced by decode_ac_coeffs(), decode_bgr_1(), decode_block_intra(), decode_block_refinement(), decode_plane_bitstream(), decode_spectrum_and_dequant(), dnxhd_decode_dct_block(), dv_decode_ac(), ff_mpeg1_decode_block_intra(), ff_msmpeg4_decode_block(), get_bits(), get_ur_golomb(), get_ur_golomb_jpegls(), h261_decode_block(), h263_decode_block(), mdec_decode_block_intra(), mpeg1_decode_block_inter(), mpeg1_fast_decode_block_inter(), mpeg2_decode_block_intra(), mpeg2_decode_block_non_intra(), mpeg2_fast_decode_block_intra(), mpeg2_fast_decode_block_non_intra(), mpeg4_decode_block(), show_bits(), and webp_get_vlc().
SHOW_SBITS
#define SHOW_SBITS (name, gb, num) SHOW_SBITS_BE(name, gb, num)
Definition at line 194 of file get_bits.h.
Referenced by decode_ac_coeffs(), decode_block_intra(), dnxhd_decode_dct_block(), ff_mpeg1_decode_block_intra(), ff_msmpeg4_decode_block(), get_sbits(), h261_decode_block(), h263_decode_block(), mdec_decode_block_intra(), mpeg1_decode_block_inter(), mpeg1_fast_decode_block_inter(), mpeg2_decode_block_intra(), mpeg2_decode_block_non_intra(), mpeg2_fast_decode_block_intra(), mpeg2_fast_decode_block_non_intra(), and mpeg4_decode_block().
GET_CACHE
#define GET_CACHE (name, gb) ((uint32_t) name ## _cache)
Definition at line 197 of file get_bits.h.
Referenced by decode_block(), decode_block_progressive(), decode_spectrum_and_dequant(), decode_vlc_codeword(), dnxhd_decode_dct_block(), ff_mpeg1_decode_block_intra(), ff_msmpeg4_decode_block(), get_interleaved_se_golomb(), get_interleaved_ue_golomb(), get_level_prefix(), get_se_golomb(), get_ue_golomb(), get_ue_golomb_31(), get_ur_golomb(), get_ur_golomb_jpegls(), get_xbits(), mpeg1_decode_block_inter(), mpeg1_fast_decode_block_inter(), mpeg2_decode_block_non_intra(), mpeg2_fast_decode_block_non_intra(), and mpeg4_decode_block().
GET_VLC
#define GET_VLC (code, name, gb, table, bits, max_depth)
Value:
do {                                                        \
        int n, nb_bits;                                         \
        unsigned int index;                                     \
                                                                \
        index = SHOW_UBITS(name, gb, bits);                     \
        code  = table[index][0];                                \
        n     = table[index][1];                                \
                                                                \
        if (max_depth > 1 && n < 0) {                           \
            LAST_SKIP_BITS(name, gb, bits);                     \
            UPDATE_CACHE(name, gb);                             \
                                                                \
            nb_bits = -n;                                       \
                                                                \
            index = SHOW_UBITS(name, gb, nb_bits) + code;       \
            code  = table[index][0];                            \
            n     = table[index][1];                            \
            if (max_depth > 2 && n < 0) {                       \
                LAST_SKIP_BITS(name, gb, nb_bits);              \
                UPDATE_CACHE(name, gb);                         \
                                                                \
                nb_bits = -n;                                   \
                                                                \
                index = SHOW_UBITS(name, gb, nb_bits) + code;   \
                code  = table[index][0];                        \
                n     = table[index][1];                        \
            }                                                   \
        }                                                       \
        SKIP_BITS(name, gb, n);                                 \
    } while (0)
If the vlc code is invalid and max_depth=1, then no bits will be removed.
If the vlc code is invalid and max_depth>1, then the number of bits removed is undefined.
Definition at line 463 of file get_bits.h.
Referenced by decode_block(), decode_block_progressive(), decode_block_refinement(), decode_spectrum_and_dequant(), dnxhd_decode_dct_block(), get_vlc2(), read_argb_line(), read_rgb24_component_line(), and read_yuv_component_line().
GET_RL_VLC
#define GET_RL_VLC (level, run, name, gb, table, bits, max_depth, need_update)
Definition at line 495 of file get_bits.h.
Referenced by cfhd_decode(), decode_block_intra(), ff_mpeg1_decode_block_intra(), ff_msmpeg4_decode_block(), h261_decode_block(), h263_decode_block(), mdec_decode_block_intra(), mpeg1_decode_block_inter(), mpeg1_fast_decode_block_inter(), mpeg2_decode_block_intra(), mpeg2_decode_block_non_intra(), mpeg2_fast_decode_block_intra(), mpeg2_fast_decode_block_non_intra(), and mpeg4_decode_block().
Function Documentation
get_bits_count()
static int get_bits_count (const GetBitContext * s) inline static
Definition at line 199 of file get_bits.h.
Referenced by aac_adtstoasc_filter(), aac_decode_frame(), adpcm_swf_decode(), alac_decode_frame(), align_get_bits(), avpriv_mpeg4audio_get_config(), bink_decode_plane(), binkb_decode_plane(), cabac_init_decoder(), categorize(), cfhd_decode(), check_for_slice(), check_marker(), chs_parse_header(), cook_decode_frame(), decode_audio_specific_config(), decode_band(), decode_component(), decode_frame(), decode_frame_header(), decode_hq_slice(), decode_line(), decode_lowdelay(), decode_lowdelay_slice(), decode_packet(), decode_rle(), decode_slice(), decode_subband(), decode_subframe(), decode_user_data(), decode_vol_header(), dvbsub_read_2bit_string(), dvbsub_read_4bit_string(), encode_picture_ls(), escape124_decode_frame(), escape130_decode_frame(), ff_dirac_init_arith_decoder(), ff_flac_decode_frame_header(), ff_h263_resync(), ff_h264_decode_picture_parameter_set(), ff_h264_sei_decode(), ff_ivi_decode_frame(), ff_lag_rac_init(), ff_mjpeg_decode_frame(), ff_mlp_read_major_sync(), ff_mpeg4_decode_picture_header(), ff_mpeg4_decode_video_packet_header(), ff_mpeg4_frame_end(), ff_msmpeg4_decode_ext_header(), ff_ps_read_data(), ff_rdt_parse_header(), ff_rtjpeg_decode_frame_yuv420(), fill_slice(), fill_slice_long(), find_group3_syncmarker(), flac_decode_frame(), flashsv_decode_block(), flashsv_decode_frame(), get_bits_align32(), get_bits_left(), get_consumed_bytes(), get_sr_golomb_shorten(), handle_rstn(), huf_unpack_enc_table(), huffman_decode(), imc_decode_block(), imc_get_coeffs(), latm_decode_audio_specific_config(), loco_decode_plane(), metasound_read_bitstream(), mp_decode_frame(), mp_decode_layer3(), mpc7_decode_frame(), mpc8_decode_frame(), mpeg4_is_resync(), mpeg_decode_slice(), mss2_decode_frame(), mxpeg_decode_frame(), parse_aux_data(), parse_band_data(), parse_bintree(), parse_coding_header(), parse_descriptor(), parse_navi_table(), parse_optional_info(), parse_setup_header(), parse_x96_coding_header(), parse_x96_frame_exss(), parse_xbr_frame(), parse_xxch_frame(), ps_read_extension_data(), qdm2_decode_sub_packet_header(), qdm2_decode_super_block(), qt_rtp_parse_packet(), read_access_unit(), read_block_data(), read_high_coeffs(), read_huffman_tables(), read_huffman_tree(), read_low_coeffs(), read_restart_header(), read_sbr_data(), read_sbr_header(), read_sl_header(), remaining_bits(), rv10_decode_packet(), save_bits(), send_picture(), seq_unpack_rle_block(), shorten_decode_frame(), svq3_decode_frame(), svq3_decode_init(), switch_buffer(), tak_decode_frame(), tak_parse(), tm2_read_stream(), twinvq_read_bitstream(), unpack_SQVH(), vaapi_h264_decode_slice(), vaapi_hevc_decode_slice(), vaapi_mpeg2_decode_slice(), vaapi_mpeg4_decode_slice(), vaapi_vc1_decode_slice(), vc1_decode_b_blocks(), vc1_decode_frame(), vc1_decode_i_blocks(), vc1_decode_i_blocks_adv(), vc1_decode_init(), vc1_decode_p_blocks(), vorbis_decode_frame(), vorbis_floor1_decode(), wma_decode_superframe(), and wmavoice_decode_packet().
skip_bits_long()
static void skip_bits_long (GetBitContext * s, int n) inline static
Definition at line 204 of file get_bits.h.
Referenced by aac_decode_er_frame(), adts_decode_extradata(), ape_decode_frame(), avpriv_mpeg4audio_get_config(), bink_decode_plane(), binkb_decode_plane(), check_for_slice(), dca_parse_params(), decode_audio_specific_config(), decode_component(), decode_eld_specific_config(), decode_extension_payload(), decode_fill(), decode_frame(), decode_gop_header(), decode_hq_slice(), decode_lowdelay_slice(), decode_nal_sei_prefix(), decode_nal_sei_suffix(), decode_nal_sei_user_data_registered_itu_t_t35(), decode_pce(), decode_pic_hdr(), decode_subframe(), decode_vol_header(), decode_vop_header(), dts_probe(), ensure_bits(), escape130_decode_frame(), ff_bgmc_decode_end(), ff_dca_core_parse(), ff_dca_exss_parse(), ff_decode_sbr_extension(), ff_dirac_init_arith_decoder(), ff_eac3_parse_header(), ff_flac_parse_streaminfo(), ff_h264_decode_mb_cavlc(), ff_h264_sei_decode(), ff_ivi_decode_frame(), ff_mlp_read_major_sync(), ff_ps_read_data(), flac_header(), flashsv_decode_block(), get_ue_golomb_long(), handle_rstn(), huffman_decode(), hvcc_parse_ptl(), hvcc_parse_vui(), kempf_restore_buf(), latm_decode_audio_specific_config(), latm_write_frame_header(), mov_read_ddts(), mov_write_dvc1_structs(), mp_decode_layer3(), mpc7_decode_frame(), mpc7_decode_init(), nelly_decode_block(), parse_aux_data(), parse_config_ALS(), parse_descriptor(), parse_optional_info(), parse_setup_header(), read_diff_float_data(), read_frame_data(), read_huffman_tree(), read_sbr_extension(), read_sl_header(), read_specific_config(), read_stream_mux_config(), save_bits(), skip_data_stream_element(), skip_timing_info(), svq3_decode_slice_header(), switch_buffer(), theora_header(), tta_decode_frame(), tta_decode_init(), vp3_decode_frame(), and wmavoice_decode_packet().
get_xbits()
static int get_xbits (GetBitContext * s, int n) inline static
Read MPEG-1 dc-style VLC (sign bit + mantissa with no MSB).
if MSB not set it is negative
Parameters
n length in bits
Definition at line 218 of file get_bits.h.
Referenced by decode_dc(), decode_i_block(), jpg_decode_block(), mjpeg_decode_dc(), mpeg4_decode_dc(), and mpeg4_decode_sprite_trajectory().
get_sbits()
static int get_sbits (GetBitContext * s, int n) inline static
Definition at line 232 of file get_bits.h.
Referenced by ac3_decode_transform_coeffs_ch(), adpcm_swf_decode(), adx_decode(), asv1_get_level(), at1_unpack_dequant(), decode_ac_coeffs(), decode_block_intra(), decode_channel(), decode_element(), decode_frame(), decode_lpc(), decode_subframe(), decode_subframe_lpc(), decorrelate(), dv_decode_video_segment(), ff_eac3_decode_transform_coeffs_aht_ch(), ff_h263_decode_picture_header(), get_array(), get_block(), hq_decode_block(), mdec_decode_block_intra(), mpeg_decode_picture_display_extension(), read_channel_params(), read_decoding_params(), read_filter_params(), read_matrix_params(), read_quant_spectral_coeffs(), read_uncoded_coeff(), seq_unpack_rle_block(), tak_decode_frame(), tgq_decode_block(), and tgv_decode_inter().
get_bits()
static unsigned int get_bits (GetBitContext * s, int n) inline static
Read 1-25 bits.
Definition at line 247 of file get_bits.h.
Referenced by aac_adtstoasc_filter(), aac_decode_frame_int(), ac3_decode_transform_coeffs_ch(), ac3_parse_header(), ac_get(), ac_init(), active_parameter_sets(), adpcm_swf_decode(), adts_decode_extradata(), aic_decode_coeffs(), alac_decode_frame(), apcm_dequant_add(), ape_decode_value_3860(), apply_color_indexing_transform(), arith_init(), asv1_decode_block(), asv2_get_bits(), at1_parse_bsm(), at1_unpack_dequant(), atrac3p_decode_frame(), avpriv_aac_parse_header(), avpriv_ac3_parse_header(), avpriv_mpeg4audio_get_config(), avpriv_tak_parse_streaminfo(), aw_parse_coords(), aw_pulse_set1(), aw_pulse_set2(), bink_decode_plane(), binkb_decode_plane(), binkb_read_bundle(), bit_copy(), build_huffman(), check_for_slice(), chs_parse_band_data(), chs_parse_header(), copy_bits(), dca_parse_params(), decode(), decode2x2(), decode4x4(), decode8x8(), decode_ac_filter(), decode_argb(), decode_argbi(), decode_argx(), decode_argxi(), decode_audio_block(), decode_aybr(), decode_aybri(), decode_band_hdr(), decode_band_numwavs(), decode_band_types(), decode_block(), decode_byry(), decode_byryi(), decode_c82i(), decode_c82p(), decode_ca2i(), decode_ca2p(), decode_ca4i(), decode_ca4p(), decode_cce(), decode_cdlms(), decode_channel(), decode_channel_code_tab(), decode_channel_map(), decode_channel_residues(), decode_channel_sf_idx(), decode_channel_sound_unit(), decode_channel_wordlen(), decode_chunks(), decode_coeff(), decode_cpe(), decode_decorrelation_matrix(), decode_display_orientation(), decode_dynamic_range(), decode_eld_specific_config(), decode_element(), decode_entropy_coded_image(), decode_envelope(), decode_exp_lsp(), decode_exp_vlc(), decode_exponents(), decode_ext_header(), decode_extension_payload(), decode_fill(), decode_frame(), decode_frame_header(), decode_frame_packing_arrangement(), decode_ga_specific_config(), decode_gain_control(), decode_gain_info(), decode_gainc_data(), decode_gainc_levels(), decode_gainc_loc_codes(), decode_gainc_npoints(), decode_gop_header(), decode_green_metadata(), decode_group3_2d_line(), decode_hq_slice(), decode_hrd_parameters(), decode_ics(), decode_ics_info(), decode_line(), decode_lowdelay_slice(), decode_lpc(), decode_lt_rps(), decode_ltp(), decode_mb(), decode_mb_b(), decode_mb_i(), decode_mb_info(), decode_mclms(), decode_motion(), decode_nal_sei_decoded_picture_hash(), decode_nal_sei_display_orientation(), decode_nal_sei_frame_packing_arrangement(), decode_nal_sei_mastering_display_info(), decode_nal_sei_message(), decode_nal_sei_user_data_registered_itu_t_t35(), decode_new_pred(), decode_packet(), decode_parameters(), decode_pce(), decode_pic(), decode_pic_hdr(), decode_pic_timing(), decode_picture_timing(), decode_plane_bitstream(), decode_plane_subdivision(), decode_prediction(), decode_profile_tier_level(), decode_pulses(), decode_registered_user_data(), decode_registered_user_data_afd(), decode_registered_user_data_closed_caption(), decode_residual(), decode_residuals(), decode_residues(), decode_rgb(), decode_rgbi(), decode_rgbx(), decode_rgbxi(), decode_rle(), decode_run_2bit(), decode_run_8bit(), decode_scale_factors(), decode_scalefactors(), decode_segment(), decode_seq_header(), decode_sequence_header_adv(), decode_skip_count(), decode_slice_header(), decode_spectrum(), decode_subframe(), decode_subframe_length(), decode_subframe_lpc(), decode_sym(), decode_sym_565(), decode_tns(), decode_tonal_components(), decode_tones_amplitude(), decode_tones_envelope(), decode_tones_frequency(), decode_tones_phase(), decode_unregistered_user_data(), decode_user_data(), decode_vbmtree(), decode_vol_header(), decode_vop_header(), decode_vui(), decode_vui_parameters(), decode_ybr(), decode_ybr10(), decode_ybr10i(), decode_ybri(), decode_ybyr(), decode_yry10(), decode_yry10i(), decode_yuv_frame(), decorrelate(), decouple_info(), dequant_lsp10i(), dequant_lsp10r(), dequant_lsp16i(), dequant_lsp16r(), dnxhd_decode_macroblock(), do_output_subblock(), dss_sp_unpack_coeffs(), dts_probe(), dv_decode_video_segment(), dvbsub_read_2bit_string(), dvbsub_read_4bit_string(), encode_picture_ls(), escape124_decode_frame(), escape130_decode_frame(), extend_code(), ff_atrac3p_decode_channel_unit(), ff_dca_exss_parse(), ff_eac3_decode_transform_coeffs_aht_ch(), ff_eac3_parse_header(), ff_flac_decode_frame_header(), ff_flac_parse_streaminfo(), ff_flv_decode_picture_header(), ff_h263_decode_mba(), ff_h263_decode_motion(), ff_h263_decode_picture_header(), ff_h264_decode_mb_cavlc(), ff_h264_decode_picture_parameter_set(), ff_h264_decode_seq_parameter_set(), ff_h264_sei_decode(), ff_hevc_decode_nal_pps(), ff_hevc_decode_nal_vps(), ff_hevc_parse_sps(), ff_intel_h263_decode_picture_header(), ff_ivi_dec_huff_desc(), ff_ivi_decode_frame(), ff_jpegls_decode_lse(), ff_mjpeg_decode_dht(), ff_mjpeg_decode_dqt(), ff_mjpeg_decode_sof(), ff_mjpeg_decode_sos(), ff_mlp_read_major_sync(), ff_mpeg4_decode_partitions(), ff_mpeg4_decode_picture_header(), ff_mpeg4_decode_video_packet_header(), ff_msmpeg4_decode_ext_header(), ff_msmpeg4_decode_motion(), ff_msmpeg4_decode_picture_header(), ff_opus_rc_dec_init(), ff_ps_read_data(), ff_rdt_parse_header(), ff_rtp_send_h263_rfc2190(), ff_rv_decode_dc(), ff_tak_decode_frame_header(), ff_vc1_decode_entry_point(), ff_vc1_decode_sequence_header(), ff_vc1_parse_frame_header(), ff_vc1_parse_frame_header_adv(), ff_wma_run_level_decode(), ff_wmv2_decode_picture_header(), fic_decode_block(), fill_block(), fill_slice(), flac_header(), flashsv_decode_frame(), g722_decode_frame(), g726_reset(), gainc_loc_mode0(), gainc_loc_mode1(), gb_get_v(), generate_fake_vps(), get_array(), get_bits_esc4(), get_bits_long(), get_bitsz(), get_block(), get_coeff_bits(), get_dimension(), get_float(), get_mvdata_interlaced(), get_num_ct_values(), get_object_type(), get_qscale(), get_rice_ook(), get_sample_rate(), get_sbits_inv(), get_scale_idx(), get_ue_code(), get_utf8(), get_value_cached(), gsm_decode_block(), gsm_decode_frame(), h261_decode_block(), h261_decode_gob_header(), h261_decode_mb(), h261_decode_picture_header(), h261_handle_packet(), h263_decode_block(), h263_decode_dquant(), h263_decode_gob_header(), h263_get_modb(), h263_handle_packet(), h264_parse_nal_header(), h264_probe(), h264_slice_header_parse(), handle_rstn(), hevc_find_frame_end(), hevc_parse_nal_header(), hl_decode_mb(), hl_decode_mb_444(), hls_slice_header(), hq_decode_block(), hq_decode_mb(), hqx_decode_422(), hqx_decode_422a(), hqx_decode_444(), hqx_decode_444a(), huf_unpack_enc_table(), hvcc_parse_ptl(), hvcc_parse_sps(), hvcc_parse_vps(), hvcc_parse_vui(), idx_to_quant(), imc_decode_block(), imc_get_coeffs(), imc_read_level_coeffs(), imc_read_level_coeffs_raw(), intlist_read(), ipvideo_decode_opcodes(), ivi_dec_tile_data_size(), k23(), k24(), k34(), k35(), k44(), k45(), kempf_restore_buf(), latm_decode_frame(), latm_get_value(), linear(), load_matrix(), magy_decode_slice(), magy_decode_slice10(), metasound_read_bitstream(), mjpeg_decode_app(), mjpeg_decode_com(), mjpeg_decode_dri(), mono_decode(), mov_read_ddts(), mov_write_ac3_tag(), mov_write_dvc1_structs(), mp_decode_frame(), mp_decode_layer1(), mp_decode_layer2(), mp_decode_layer3(), mp_read_changes_map(), mp_read_codes_table(), mpc7_decode_frame(), mpc7_decode_init(), mpc8_decode_frame(), mpc8_decode_init(), mpc8_parse_seektable(), mpeg1_decode_picture(), mpeg1_decode_sequence(), mpeg4_decode_dc(), mpeg4_decode_gop_header(), mpeg4_decode_mb(), mpeg4_decode_partition_a(), mpeg4_decode_partition_b(), mpeg4_decode_profile_level(), mpeg4_is_resync(), mpeg_decode_gop(), mpeg_decode_mb(), mpeg_decode_motion(), mpeg_decode_picture_coding_extension(), mpeg_decode_sequence_display_extension(), mpeg_decode_sequence_extension(), msmpeg4_decode_dc(), msmpeg4v2_decode_motion(), mss2_decode_frame(), mss4_decode_image_block(), nal_unit_parse_header(), nelly_decode_block(), num_coded_units(), on2avc_decode_band_scales(), on2avc_decode_band_types(), on2avc_decode_subframe(), opus_rc_dec_normalize(), parse_aux_data(), parse_bintree(), parse_block_codes(), parse_ch(), parse_coding_header(), parse_common_header(), parse_config_ALS(), parse_descriptor(), parse_dmix_coeffs(), parse_fmtp_config(), parse_frame(), parse_frame_header(), parse_grid_1_chunk(), parse_high_res_grid(), parse_joint_scale(), parse_lbr_parameters(), parse_lfe_16(), parse_lfe_24(), parse_lpc(), parse_mb_skip(), parse_nal_units(), parse_optional_info(), parse_packet_header(), parse_ptl(), parse_scale(), parse_setup_header(), parse_subframe_audio(), parse_subframe_header(), parse_tonal(), parse_tonal_chunk(), parse_transform_color_indexing(), parse_ts(), parse_vlc(), parse_x96_coding_header(), parse_x96_frame(), parse_x96_frame_exss(), parse_x96_subframe_audio(), parse_x96_subframe_header(), parse_xbr_frame(), parse_xbr_subframe(), parse_xll_parameters(), parse_xxch_frame(), pcx_decode_frame(), predictor_calc_error(), process_subpacket_11(), put_pcm(), qcelp_decode_frame(), qdm2_decode_fft_packets(), qdm2_decode_sub_packet_header(), qdm2_decode_super_block(), qdm2_fft_decode_tones(), qdm2_get_vlc(), qt_rtp_parse_packet(), ra144_decode_frame(), ra288_decode_frame(), read_access_unit(), read_audio_mux_element(), read_block_data(), read_block_types(), read_cb_data(), read_channel_data(), read_channel_params(), read_code_table(), read_colorspace_details(), read_dcs(), read_dct_coeffs(), read_decoding_params(), read_diff_float_data(), read_filter_params(), read_header(), read_high_coeffs(), read_huff_channels(), read_huffman_code_normal(), read_huffman_code_simple(), read_huffman_tree(), read_len_table(), read_low_coeffs(), read_map(), read_matrix_params(), read_motion_values(), read_payload_length_info(), read_quant_spectral_coeffs(), read_residue(), read_restart_header(), read_runs(), read_sbr_data(), read_sbr_envelope(), read_sbr_grid(), read_sbr_header(), read_sbr_invf(), read_sbr_noise(), read_sl_header(), read_specific_config(), read_stream_mux_config(), read_table(), read_tree(), read_uncoded_coeff(), read_var_block_data(), read_vec_pos(), rv10_decode_picture_header(), rv20_decode_picture_header(), rv30_parse_slice_header(), rv34_decode_inter_mb_header(), rv34_decode_intra_mb_header(), rv40_parse_slice_header(), save_bits(), seq_decode_op1(), seqvideo_decode(), skip_data_stream_element(), skip_hdr_extension(), smacker_decode_header_tree(), smacker_decode_tree(), smka_decode_frame(), svq1_decode_frame(), svq1_decode_frame_header(), svq1_parse_string(), svq3_decode_init(), svq3_decode_slice_header(), swf_probe(), synth_block_fcb_acb(), synth_block_hardcoded(), synth_frame(), synth_superframe(), synthfilt_build_sb_samples(), t15(), t27(), t37(), tak_decode_frame(), tak_read_header(), tgq_decode_block(), tgv_decode_inter(), theora_header(), tm2_build_huff_table(), tm2_read_deltas(), truemotion2rt_decode_frame(), truespeech_read_frame(), tscc2_decode_mb(), tta_decode_frame(), tta_decode_init(), twinvq_read_bitstream(), unpack_alpha(), unpack_bitstream(), unpack_block_qpis(), unpack_codebook(), unpack_dct_coeffs(), unpack_frame(), unpack_modes(), unpack_superblocks(), unpack_vectors(), unpack_vlcs(), vaapi_mpeg2_decode_slice(), vble_restore_plane(), vc1_decode_ac_coeff(), vc1_decode_frame(), vc1_decode_i_block(), vc1_decode_i_block_adv(), vc1_decode_intra_block(), vlc_decode_block(), vop_dquant_decoding(), vorbis_decode_init(), vorbis_floor0_decode(), vorbis_floor1_decode(), vorbis_parse_audio_packet(), vorbis_parse_id_hdr(), vorbis_parse_setup_hdr(), vorbis_parse_setup_hdr_codebooks(), vorbis_parse_setup_hdr_floors(), vorbis_parse_setup_hdr_mappings(), vorbis_parse_setup_hdr_modes(), vorbis_parse_setup_hdr_residues(), vorbis_parse_setup_hdr_tdtransforms(), vp3_decode_frame(), vp6_get_nb_null(), vp6_parse_coeff_huffman(), vp8_lossless_decode_frame(), vp9_superframe_filter(), wma_decode_block(), wma_decode_superframe(), wnv1_get_code(), wv_get_value_float(), x8_get_ac_rlf(), x8_get_dc_rlf(), x8_get_orient_vlc(), and x8_select_ac_table().
get_bitsz()
static av_always_inline int get_bitsz (GetBitContext * s, int n) static
Read 0-25 bits.
Definition at line 262 of file get_bits.h.
Referenced by build_huffman(), decode_ac_filter(), decode_cdlms(), decode_channel_sf_idx(), decode_channel_wordlen(), decode_gainc_levels(), decode_gainc_npoints(), decode_macroblock(), decode_mclms(), decode_subframe(), get_tail(), hevc_find_frame_end(), hls_slice_header(), huffman_decode(), parse_tonal(), and read_diff_float_data().
get_bits_le()
static unsigned int get_bits_le (GetBitContext * s, int n) inline static
Definition at line 267 of file get_bits.h.
Referenced by adpcm_ima_wav_expand_nibble(), and g726_reset().
show_bits()
static unsigned int show_bits (GetBitContext * s, int n) inline static
Show 1-25 bits.
Definition at line 282 of file get_bits.h.
Referenced by aac_adtstoasc_filter(), aac_decode_frame_int(), avpriv_mpeg4audio_get_config(), check_for_slice(), check_slice_end(), decode_ac_coeffs(), decode_frame(), decode_group3_1d_line(), decode_packet(), decode_pic(), decode_residual(), decode_scalar(), decode_slice(), decode_uncompressed(), decode_user_data(), decode_vop_header(), ff_ccitt_unpack(), ff_h263_decode_mb(), ff_h263_decode_picture_header(), ff_h263_resync(), ff_h264_sei_decode(), ff_mjpeg_decode_sos(), ff_mpeg4_decode_partitions(), ff_mpeg4_decode_picture_header(), ff_msmpeg4_decode_block(), ff_wmv2_decode_mb(), get_sr_golomb_shorten(), h261_decode_block(), h261_decode_gob_header(), h261_resync(), h263_decode_gob_header(), handle_rstn(), hqx_get_ac(), latm_decode_frame(), main(), mjpeg_decode_app(), mjpegb_decode_frame(), more_rbsp_data(), mpeg1_decode_sequence(), mpeg4_decode_gop_header(), mpeg4_decode_partition_a(), mpeg4_is_resync(), mpeg_decode_slice(), msmpeg4v34_decode_mb(), read_high_coeffs(), read_low_coeffs(), read_sbr_extension(), rv10_decode_packet(), rv10_decode_picture_header(), show_bits1(), show_bits_long(), svq3_decode_frame(), svq3_decode_slice_header(), tgq_decode_block(), and vble_unpack().
skip_bits()
static void skip_bits (GetBitContext * s, int n) inline static
Definition at line 292 of file get_bits.h.
Referenced by aac_decode_er_frame(), ac3_parse_header(), aic_decode_coeffs(), align_get_bits(), apply_color_indexing_transform(), at1_parse_bsm(), avpriv_aac_parse_header(), avpriv_ac3_parse_header(), avpriv_mpeg4audio_get_config(), avpriv_tak_parse_streaminfo(), bitline2chunky(), bitplanar2chunky(), cabac_init_decoder(), dca_parse_params(), decode_argb_frame(), decode_audio_block(), decode_band_hdr(), decode_block(), decode_buffering_period(), decode_dynamic_range(), decode_element(), decode_frame(), decode_frame_header(), decode_frame_packing_arrangement(), decode_ga_specific_config(), decode_gop_header(), decode_group3_1d_line(), decode_hrd(), decode_nal_sei_decoded_picture_hash(), decode_nal_sei_frame_packing_arrangement(), decode_nal_sei_prefix(), decode_nal_sei_user_data_registered_itu_t_t35(), decode_packet(), decode_pce(), decode_pic(), decode_pic_hdr(), decode_picture_timing(), decode_profile_tier_level(), decode_recovery_point(), decode_registered_user_data(), decode_registered_user_data_afd(), decode_registered_user_data_closed_caption(), decode_residual(), decode_rgb24_frame(), decode_scalar(), decode_seq_header(), decode_sequence_header_adv(), decode_uncompressed(), decode_vol_header(), decode_vop_header(), decode_yuv_frame(), dts_probe(), ff_dca_exss_parse(), ff_decode_sbr_extension(), ff_eac3_parse_header(), ff_flac_decode_frame_header(), ff_flac_parse_streaminfo(), ff_h263_decode_picture_header(), ff_h263_resync(), ff_h264_decode_seq_parameter_set(), ff_hevc_decode_nal_vps(), ff_hevc_parse_sps(), ff_intel_h263_decode_picture_header(), ff_jpegls_decode_picture(), ff_mjpeg_decode_sos(), ff_mlp_read_major_sync(), ff_mpeg4_decode_partitions(), ff_mpeg4_decode_picture_header(), ff_mpeg4_decode_video_packet_header(), ff_msmpeg4_decode_ext_header(), ff_msmpeg4_decode_picture_header(), ff_ps_read_data(), ff_rdt_parse_header(), ff_rtp_send_h263_rfc2190(), ff_rv_decode_dc(), ff_tak_decode_frame_header(), ff_vc1_decode_entry_point(), ff_vc1_decode_sequence_header(), ff_vc1_parse_frame_header(), ff_vc1_parse_frame_header_adv(), flashsv_decode_frame(), g722_decode_frame(), get_bits_align32(), h261_decode_block(), h261_decode_gob_header(), h261_handle_packet(), h261_resync(), h263_decode_gob_header(), h263_handle_packet(), h264_probe(), handle_rstn(), hevc_find_frame_end(), hls_slice_header(), hqx_get_ac(), hvcc_parse_pps(), hvcc_parse_ptl(), hvcc_parse_sps(), hvcc_parse_vps(), hvcc_parse_vui(), ljpeg_decode_rgb_scan(), ljpeg_decode_yuv_scan(), metasound_read_bitstream(), mjpeg_decode_app(), mjpegb_decode_frame(), mov_read_ddts(), mov_write_ac3_tag(), mov_write_dvc1_structs(), mp_decode_frame(), mp_decode_layer3(), mpc8_decode_frame(), mpc8_decode_init(), mpeg1_decode_sequence(), mpeg4_is_resync(), mpeg_decode_picture_display_extension(), mpeg_decode_sequence_display_extension(), mpeg_decode_sequence_extension(), mpeg_decode_slice(), mss2_decode_frame(), mxpeg_decode_app(), mxpeg_decode_com(), nal_unit_parse_header(), parse_adts_frame_header(), parse_aux_data(), parse_coding_header(), parse_descriptor(), parse_fmtp_config(), parse_frame_header(), parse_lbr_parameters(), parse_navi_table(), parse_packet_header(), parse_ptl(), parse_setup_header(), parse_subframe_header(), parse_x96_coding_header(), parse_x96_subframe_header(), parse_xll_parameters(), predictor_calc_error(), preview_obmc(), qdm2_decode_super_block(), qt_rtp_parse_packet(), read_access_unit(), read_block_data(), read_const_block_data(), read_header(), read_high_coeffs(), read_huffman_tree(), read_low_coeffs(), read_payload_length_info(), read_restart_header(), read_sbr_channel_pair_element(), read_sbr_data(), read_sbr_header(), read_sbr_single_channel_element(), read_sl_header(), read_specific_config(), read_stream_mux_config(), rv10_decode_picture_header(), rv20_decode_picture_header(), save_bits(), shorten_decode_frame(), skip_1stop_8data_bits(), skip_bits1(), skip_hdr_extension(), skip_hrd_parameters(), svq1_decode_frame(), svq1_decode_frame_header(), svq3_decode_slice_header(), swf_probe(), synth_block_fcb_acb(), synth_superframe(), tak_decode_frame(), tgq_decode_block(), theora_header(), truemotion2rt_decode_frame(), twinvq_read_bitstream(), vaapi_mpeg2_decode_slice(), vble_unpack(), vorbis_parse_setup_hdr_mappings(), vp3_decode_frame(), wma_decode_superframe(), and wmavoice_decode_packet().
get_bits1()
static unsigned int get_bits1 (GetBitContext * s) inline static
Definition at line 299 of file get_bits.h.
Referenced by ac3_parse_header(), aic_decode_coeffs(), arith_normalise(), atrac3p_decode_frame(), avpriv_aac_parse_header(), avpriv_ac3_parse_header(), avpriv_mpeg4audio_get_config(), avpriv_tak_parse_streaminfo(), avs_decode_frame(), aw_pulse_set2(), bink_decode_plane(), binkb_decode_plane(), bitline2chunky(), bitplanar2chunky(), bitplane_decoding(), check_marker(), chs_parse_band_data(), chs_parse_header(), codeblock(), decode(), decode012(), decode210(), decode2x2(), decode4x4(), decode8x8(), decode_argb(), decode_argbi(), decode_argx(), decode_argxi(), decode_audio_block(), decode_aybr(), decode_aybri(), decode_band(), decode_band_hdr(), decode_band_structure(), decode_block(), decode_byry(), decode_byryi(), decode_c82i(), decode_c82p(), decode_ca2i(), decode_ca2p(), decode_ca4i(), decode_ca4p(), decode_cce(), decode_cdlms(), decode_channel_code_tab(), decode_channel_map(), decode_channel_residues(), decode_channel_transform(), decode_channel_wordlen(), decode_code_table_indexes(), decode_coeff(), decode_coeffs(), decode_colskip(), decode_cpe(), decode_decorrelation_matrix(), decode_display_orientation(), decode_drc_channel_exclusions(), decode_dynamic_range(), decode_eld_specific_config(), decode_element(), decode_entropy_coded_image(), decode_ext_header(), decode_frame(), decode_frame_header(), decode_frame_packing_arrangement(), decode_ga_specific_config(), decode_gain_info(), decode_gainc_data(), decode_gainc_levels(), decode_gainc_loc_codes(), decode_gop_header(), decode_header_trees(), decode_hrd(), decode_hrd_parameters(), decode_ics(), decode_ics_info(), decode_line(), decode_lt_rps(), decode_ltp(), decode_macroblock(), decode_mb_i(), decode_mb_info(), decode_mb_p(), decode_mclms(), decode_mid_side_stereo(), decode_motion(), decode_mv_component(), decode_nal_sei_display_orientation(), decode_nal_sei_frame_packing_arrangement(), decode_new_pred(), decode_packet(), decode_pce(), decode_pic(), decode_pic_hdr(), decode_prediction(), decode_profile_tier_level(), decode_qu_spectra(), decode_residual(), decode_residues(), decode_rgb(), decode_rgbi(), decode_rgbx(), decode_rgbxi(), decode_rice(), decode_rle(), decode_rowskip(), decode_run_8bit(), decode_scale_factors(), decode_scaling_list(), decode_scaling_matrices(), decode_segment(), decode_seq_header(), decode_sequence_header_adv(), decode_skip_count(), decode_slice_header(), decode_spectrum(), decode_subframe(), decode_subframe_length(), decode_tilehdr(), decode_tns(), decode_tonal_components(), decode_tones_envelope(), decode_tones_frequency(), decode_tones_info(), decode_uncompressed(), decode_vol_header(), decode_vop_header(), decode_vui(), decode_vui_parameters(), decode_ybr(), decode_ybr10(), decode_ybr10i(), decode_ybri(), decode_ybyr(), decode_yry10(), decode_yry10i(), decorrelate(), decouple_info(), dirac_get_se_golomb(), dirac_unpack_idwt_params(), dirac_unpack_prediction_parameters(), dnxhd_decode_macroblock(), dts_probe(), dv_decode_video_segment(), dvbsub_read_2bit_string(), dvbsub_read_4bit_string(), escape124_decode_frame(), escape130_decode_frame(), ff_atrac3p_decode_channel_unit(), ff_bgmc_decode(), ff_ccitt_unpack(), ff_dca_exss_parse(), ff_decode_sbr_extension(), ff_eac3_decode_transform_coeffs_aht_ch(), ff_eac3_parse_header(), ff_flac_decode_frame_header(), ff_h263_decode_mb(), ff_h263_decode_motion(), ff_h263_decode_picture_header(), ff_h264_decode_mb_cavlc(), ff_h264_decode_picture_parameter_set(), ff_h264_decode_ref_pic_list_reordering(), ff_h264_decode_ref_pic_marking(), ff_h264_decode_seq_parameter_set(), ff_h264_parse_ref_count(), ff_h264_pred_weight_table(), ff_hevc_decode_nal_pps(), ff_hevc_decode_nal_vps(), ff_hevc_decode_short_term_rps(), ff_hevc_parse_sps(), ff_intel_h263_decode_picture_header(), ff_intrax8_decode_picture(), ff_mlp_read_major_sync(), ff_mpeg4_decode_video_packet_header(), ff_msmpeg4_decode_ext_header(), ff_msmpeg4_decode_picture_header(), ff_ps_read_data(), ff_rdt_parse_header(), ff_rv_decode_dc(), ff_vc1_decode_entry_point(), ff_vc1_decode_sequence_header(), ff_vc1_parse_frame_header(), ff_vc1_parse_frame_header_adv(), ff_vc1_pred_b_mv(), ff_vc1_pred_mv(), ff_wma_get_large_val(), ff_wma_run_level_decode(), ff_wmv2_decode_mb(), ff_wmv2_decode_picture_header(), ff_wmv2_decode_secondary_picture_header(), fic_decode_block(), find_group3_syncmarker(), flashsv_decode_frame(), gb_get_v(), get_bits1_vector(), get_bits_esc4(), get_dimension(), get_dmv(), get_egolomb(), get_float(), get_num_ct_values(), get_sbits_inv(), get_sr_golomb_dst(), get_subband_flags(), get_tail(), get_te0_golomb(), get_te_golomb(), get_unary(), get_value_cached(), h261_decode_picture_header(), h263_decode_dquant(), h263_decode_gob_header(), h263_get_modb(), h263p_decode_umotion(), h264_parse_nal_header(), h264_slice_header_parse(), hevc_find_frame_end(), hevc_parse_nal_header(), hevc_parse_slice_header(), hls_slice_header(), hq_decode_mb(), hqa_decode_mb(), hqx_decode_422(), hqx_decode_422a(), hqx_decode_444(), hqx_decode_444a(), huff_reader_get_symbol(), huffman_decode(), hvcc_parse_pps(), hvcc_parse_ptl(), hvcc_parse_sps(), hvcc_parse_vui(), idx_to_quant(), imc_decode_block(), imc_get_skip_coeff(), init_tone_level_dequantization(), input_code(), intlist_read(), ivi_dec_tile_data_size(), k12(), k13(), k23(), k24(), k34(), k35(), k44(), k45(), lag_decode_prob(), ls_decode_line(), merge(), metasound_read_bitstream(), mjpeg_decode_scan(), mov_write_ac3_tag(), mov_write_dvc1_structs(), mp_decode_layer3(), mp_get_code(), mpc7_decode_frame(), mpc7_decode_init(), mpc8_dec_base(), mpc8_decode_frame(), mpc8_decode_init(), mpeg1_decode_picture(), mpeg1_decode_sequence(), mpeg4_decode_dc(), mpeg4_decode_mb(), mpeg4_decode_partition_a(), mpeg4_decode_partition_b(), mpeg4_is_resync(), mpeg_decode_gop(), mpeg_decode_mb(), mpeg_decode_motion(), mpeg_decode_picture_coding_extension(), mpeg_decode_quant_matrix_extension(), mpeg_decode_sequence_display_extension(), mpeg_decode_sequence_extension(), msmpeg4_decode_dc(), msmpeg4v12_decode_mb(), msmpeg4v2_decode_motion(), msmpeg4v34_decode_mb(), mss2_decode_frame(), mss4_decode_image_block(), on2avc_decode_subframe(), on2avc_read_ms_info(), parse_aux_data(), parse_ch(), parse_coding_header(), parse_common_header(), parse_descriptor(), parse_frame(), parse_frame_header(), parse_grid_2(), parse_lbr_parameters(), parse_mb_skip(), parse_nal_units(), parse_packet_header(), parse_ptl(), parse_rps(), parse_setup_header(), parse_subframe_header(), parse_tonal(), parse_x96_coding_header(), parse_x96_frame_exss(), parse_x96_subframe_header(), parse_xbr_frame(), parse_xll_parameters(), parse_xxch_frame(), pps_range_extensions(), pred_weight_table(), predictor_calc_error(), preview_obmc(), ps_read_extension_data(), qdm2_fft_decode_tones(), qt_rtp_parse_packet(), read_access_unit(), read_block(), read_block_types(), read_channel_data(), read_channel_params(), read_colors(), read_colorspace_details(), read_const_block_data(), read_dcs(), read_dct_coeffs(), read_decoding_params(), read_diff_float_data(), read_filter_params(), read_frame_data(), read_high_coeffs(), read_huff_channels(), read_huffman_code_normal(), read_huffman_code_simple(), read_huffman_tree(), read_map(), read_matrix_params(), read_motion_values(), read_residue(), read_restart_header(), read_runs(), read_sbr_channel_pair_element(), read_sbr_data(), read_sbr_grid(), read_sbr_header(), read_sbr_single_channel_element(), read_sl_header(), read_specific_config(), read_table(), read_tree(), read_var_block_data(), read_vec_pos(), rv10_decode_picture_header(), rv20_decode_picture_header(), rv30_parse_slice_header(), rv34_decode_cbp(), rv34_decode_intra_mb_header(), rv40_decode_intra_types(), rv40_parse_slice_header(), scaling_list_data(), scan_mmco_reset(), skip_1stop_8data_bits(), skip_data_stream_element(), skip_hrd_parameters(), skip_scaling_list_data(), skip_timing_info(), smacker_decode_bigtree(), smacker_decode_header_tree(), smacker_decode_tree(), smk_get_code(), smka_decode_frame(), svq1_decode_frame_header(), svq1_decode_motion_vector(), svq3_decode_init(), svq3_decode_mb(), svq3_decode_slice_header(), synth_block_fcb_acb(), synth_superframe(), synthfilt_build_sb_samples(), tak_decode_frame(), tm2_read_tree(), truespeech_read_frame(), tscc2_decode_mb(), twinvq_read_bitstream(), unpack_alpha(), unpack_bitstream(), unpack_block_qpis(), unpack_frame(), unpack_SQVH(), unpack_superblocks(), unpack_vectors(), vaapi_mpeg2_decode_slice(), vble_unpack(), vc1_decode_ac_coeff(), vc1_decode_b_mb(), vc1_decode_b_mb_intfi(), vc1_decode_b_mb_intfr(), vc1_decode_frame(), vc1_decode_i_block(), vc1_decode_i_block_adv(), vc1_decode_i_blocks(), vc1_decode_i_blocks_adv(), vc1_decode_intra_block(), vc1_decode_p_mb(), vc1_decode_p_mb_intfi(), vc1_decode_p_mb_intfr(), vop_dquant_decoding(), vorbis_floor1_decode(), vorbis_parse_audio_packet(), vorbis_parse_id_hdr(), vorbis_parse_setup_hdr(), vorbis_parse_setup_hdr_codebooks(), vorbis_parse_setup_hdr_mappings(), vorbis_parse_setup_hdr_modes(), vorbis_parse_setup_hdr_residues(), vp3_decode_frame(), vp6_get_nb_null(), vp6_parse_coeff_huffman(), vp8_lossless_decode_frame(), vp9_superframe_filter(), wma_decode_block(), wmv2_decode_motion(), wmv2_pred_motion(), wv_get_value(), wv_get_value_float(), x8_decode_intra_mb(), x8_get_ac_rlf(), and xan_huffman_decode().
show_bits1()
static unsigned int show_bits1 (GetBitContext * s) inline static
Definition at line 319 of file get_bits.h.
Referenced by decode_vui_parameters().
skip_bits1()
static void skip_bits1 (GetBitContext * s) inline static
Definition at line 324 of file get_bits.h.
Referenced by avpriv_aac_parse_header(), decode_channel_map(), decode_display_orientation(), decode_dynamic_range(), decode_frame(), decode_frame_packing_arrangement(), decode_ga_specific_config(), decode_nal_sei_display_orientation(), decode_nal_sei_frame_packing_arrangement(), decode_pic(), decode_seq_header(), decode_sequence_header_adv(), decode_sublayer_hrd(), decode_vol_header(), decode_vop_header(), ff_eac3_parse_header(), ff_flv_decode_picture_header(), ff_h263_decode_mb(), ff_h263_decode_picture_header(), ff_h263_resync(), ff_h264_decode_ref_pic_marking(), ff_hevc_parse_sps(), ff_intel_h263_decode_picture_header(), flac_header(), h261_decode_picture_header(), hvcc_parse_sps(), hvcc_parse_vui(), mpeg4_decode_gop_header(), mpeg4_decode_partition_a(), mpeg_decode_mb(), mpeg_decode_slice(), nal_unit_parse_header(), parse_descriptor(), parse_frame_header(), parse_rps(), preview_obmc(), ps_read_extension_data(), read_access_unit(), read_specific_config(), rv30_parse_slice_header(), rv40_parse_slice_header(), skip_sub_layer_hrd_parameters(), smacker_decode_header_tree(), smka_decode_frame(), svq1_decode_frame_header(), svq3_decode_slice_header(), and unpack_bitstream().
get_bits_long()
static unsigned int get_bits_long (GetBitContext * s, int n) inline static
Read 0-32 bits.
Definition at line 332 of file get_bits.h.
Referenced by chs_parse_header(), dca_parse_params(), decode_band_hdr(), decode_block(), decode_buffering_period(), decode_channel_residues(), decode_element(), decode_frame(), decode_frame_header(), decode_gop_header(), decode_lowdelay_slice(), decode_nal_sei_mastering_display_info(), decode_nal_sei_user_data_registered_itu_t_t35(), decode_pic_hdr(), decode_picture_timing(), decode_registered_user_data(), decode_rice(), decode_scalar(), decode_segment(), decode_vui(), decode_vui_parameters(), dirac_decode_picture_header(), dss_sp_unpack_coeffs(), escape124_decode_frame(), ff_bgmc_decode_init(), ff_flac_parse_streaminfo(), ff_flv_decode_picture_header(), ff_hevc_decode_nal_vps(), ff_intel_h263_decode_picture_header(), ff_mlp_read_major_sync(), ff_mpeg4_decode_partitions(), ff_msmpeg4_decode_picture_header(), ff_rdt_parse_header(), ff_wma_get_large_val(), flac_header(), get_bits64(), get_block_sizes(), get_egolomb(), get_float(), get_linear(), get_rice_un(), get_sbits_long(), get_ue_golomb_long(), hls_slice_header(), hvcc_parse_ptl(), init_entropy_decoder(), ivi_dec_tile_data_size(), lag_decode_prob(), latm_get_value(), ls_decode_line(), mjpeg_decode_app(), mjpegb_decode_frame(), mov_read_ddts(), mov_read_stsz(), mp_read_changes_map(), mpc8_dec_base(), parse_aux_data(), parse_coding_header(), parse_common_header(), parse_config_ALS(), parse_descriptor(), parse_navi_table(), parse_x96_frame_exss(), parse_xbr_frame(), parse_xll_parameters(), parse_xxch_frame(), read_channel_data(), read_diff_float_data(), read_header(), read_huffman_tree(), read_offs(), read_specific_config(), read_var_block_data(), rtp_parse_mp4_au(), show_bits_long(), swf_probe(), tak_read_header(), theora_header(), tm2_build_huff_table(), tm2_read_deltas(), tm2_read_tree(), truespeech_read_frame(), tta_decode_init(), vaapi_mpeg2_decode_slice(), vc1_decode_init(), vorbis_parse_id_hdr(), vorbis_parse_setup_hdr_codebooks(), wavpack_decode_block(), wv_get_value(), and wv_get_value_integer().
get_bits64()
static uint64_t get_bits64 (GetBitContext * s, int n) inline static
Read 0-64 bits.
Definition at line 353 of file get_bits.h.
Referenced by avpriv_tak_parse_streaminfo(), ff_flac_parse_streaminfo(), get_ts64(), hvcc_parse_ptl(), and tak_read_header().
get_sbits_long()
static int get_sbits_long (GetBitContext * s, int n) inline static
Read 0-32 bits as a signed integer.
Definition at line 371 of file get_bits.h.
Referenced by chs_parse_band_data(), decode_channel_residues(), decode_element(), decode_residuals(), decode_subframe(), decode_subframe_fixed(), decode_subframe_lpc(), and read_const_block_data().
show_bits_long()
static unsigned int show_bits_long (GetBitContext * s, int n) inline static
Show 0-32 bits.
Definition at line 383 of file get_bits.h.
Referenced by avpriv_ac3_parse_header(), avpriv_mpeg4audio_get_config(), check_for_slice(), decode_subframe(), decode_vui(), ff_ivi_decode_frame(), ff_vc1_decode_entry_point(), ff_vc1_decode_sequence_header(), get_ue_golomb_long(), ls_get_code_regular(), ls_get_code_runterm(), main(), mjpeg_decode_app(), mpeg4_decode_partition_a(), mpeg_decode_slice(), read_access_unit(), and tta_decode_init().
check_marker()
static int check_marker (void * logctx, GetBitContext * s, const char * msg) inline static
Definition at line 393 of file get_bits.h.
Referenced by decode_new_pred(), decode_vol_header(), decode_vop_header(), ff_h263_decode_picture_header(), ff_intel_h263_decode_picture_header(), ff_mpeg4_decode_video_packet_header(), h263_decode_gob_header(), mpeg1_decode_sequence(), mpeg4_decode_gop_header(), mpeg4_decode_sprite_trajectory(), mpeg_decode_mb(), and mpeg_decode_sequence_extension().
init_get_bits()
static int init_get_bits (GetBitContext * s, const uint8_t * buffer, int bit_size) inline static
Initialize GetBitContext.
Parameters
buffer bitstream buffer, must be AV_INPUT_BUFFER_PADDING_SIZE bytes larger than the actual read bits because some optimized bitstream readers read 32 or 64 bit at once and could read over the end
bit_size the size of the buffer in bits
Returns
0 on success, AVERROR_INVALIDDATA if the buffer_size would overflow.
Definition at line 411 of file get_bits.h.
Referenced by aac_adtstoasc_filter(), aac_sync(), ac3_eac3_probe(), ac3_sync(), adpcm_swf_decode(), adts_decode_extradata(), adx_decode(), aic_decode_slice(), apply_color_indexing_transform(), atrac1_decode_frame(), avpriv_mpeg4audio_get_config(), avs_decode_frame(), cavs_decode_frame(), cfhd_decode(), dca_parse_params(), decode_alpha_plane(), decode_audio_specific_config(), decode_bytes_and_gain(), decode_chunks(), decode_ext_header(), decode_frame(), decode_i_frame(), decode_lowdelay(), decode_p_frame(), decode_packet(), decode_plane(), decode_plane10(), decode_rle(), decode_slice(), decode_slice_alpha(), decode_slice_chroma(), decode_slice_luma(), decode_slice_plane(), dirac_decode_data_unit(), dnxhd_decode_row(), dss_sp_unpack_coeffs(), dts_probe(), dv_decode_video_segment(), dvbsub_read_2bit_string(), dvbsub_read_4bit_string(), encode_picture_ls(), ff_flac_parse_streaminfo(), ff_h2645_packet_split(), ff_ivi_decode_frame(), ff_mjpeg_decode_init(), ff_msgsm_decode_block(), ff_rdt_parse_header(), ff_rtp_send_h263_rfc2190(), ff_rv34_decode_frame(), ffat_create_decoder(), fic_decode_slice(), fill_slice(), flac_header(), frame_header_is_valid(), g722_decode_frame(), g726_reset(), gsm_decode_frame(), h261_decode_frame(), h261_handle_packet(), h263_handle_packet(), h264_find_frame_end(), hl_decode_mb(), hl_decode_mb_444(), hls_pcm_sample(), hq_decode_frame(), hqa_decode_frame(), imc_decode_frame(), init_get_bits8(), ipvideo_decode_opcodes(), main(), metasound_read_bitstream(), mimic_decode_frame(), mjpeg_decode_scan(), mjpegb_decode_frame(), mlp_parse(), mov_read_ddts(), mov_read_stsz(), mov_write_ac3_tag(), mov_write_dvc1_structs(), mp_decode_frame(), mp_decode_layer3(), mpc7_decode_frame(), mpc7_decode_init(), mpc8_decode_frame(), mpc8_decode_init(), mpc8_parse_seektable(), mpeg1_decode_picture(), mpeg1_decode_sequence(), mpeg4_decode_header(), mpeg_decode_gop(), mpeg_decode_slice(), mxpeg_decode_frame(), nelly_decode_block(), parse_fmtp_config(), parse_setup_header(), process_subpacket_10(), process_subpacket_11(), process_subpacket_12(), process_subpacket_9(), qdm2_decode_fft_packets(), qdm2_decode_super_block(), qt_rtp_parse_packet(), read_access_unit(), read_huffman_tables(), read_old_huffman_tables(), read_sl_header(), rtp_parse_mp4_au(), rv10_decode_packet(), rv34_decode_slice(), save_bits(), send_picture(), seq_decode_op1(), seq_unpack_rle_block(), seqvideo_decode(), sipr_decode_frame(), spdif_get_offset_and_codec(), spdif_header_aac(), svq1_decode_frame(), svq3_decode_frame(), svq3_decode_init(), svq3_decode_slice_header(), synth_superframe(), tgv_decode_inter(), theora_header(), tm2_read_stream(), tqi_decode_frame(), truespeech_read_frame(), unpack_bitstream(), vaapi_mpeg2_decode_slice(), vble_decode_frame(), vc1_decode_frame(), vc1_decode_init(), vc1_extract_header(), vorbis_decode_init(), vp6_parse_header(), wma_decode_superframe(), wmavoice_decode_init(), and wmavoice_decode_packet().
init_get_bits8()
static int init_get_bits8 (GetBitContext * s, const uint8_t * buffer, int byte_size) inline static
Initialize GetBitContext.
Parameters
buffer bitstream buffer, must be AV_INPUT_BUFFER_PADDING_SIZE bytes larger than the actual read bits because some optimized bitstream readers read 32 or 64 bit at once and could read over the end
byte_size the size of the buffer in bytes
Returns
0 on success, AVERROR_INVALIDDATA if the buffer_size would overflow.
Definition at line 442 of file get_bits.h.
Referenced by aac_decode_frame(), ac3_decode_frame(), adpcm_decode_frame(), alac_decode_frame(), ape_decode_frame(), atrac3p_decode_frame(), bitline2chunky(), bitplanar2chunky(), cllc_decode_frame(), dca_parse_params(), decode_frame(), decode_frame_header(), decode_header_trees(), decode_nal_units(), decode_plane(), decode_slice_thread(), decode_subband_internal(), decode_wmv9(), dxtory_decode_v2(), escape124_decode_frame(), escape130_decode_frame(), evrc_decode_frame(), ff_ccitt_unpack(), ff_dca_core_parse(), ff_dca_core_parse_exss(), ff_dca_exss_parse(), ff_h263_decode_frame(), ff_mjpeg_decode_frame(), ff_opus_rc_dec_init(), ff_rtjpeg_decode_frame_yuv420(), flac_decode_frame(), flashsv_decode_frame(), fraps2_decode_plane(), generate_fake_vps(), get_last_needed_nal(), h264_probe(), hevc_find_frame_end(), hls_decode_entry_wpp(), huf_unpack_enc_table(), hvcc_add_nal_unit(), ir2_decode_frame(), jpg_decode_data(), kempf_restore_buf(), lag_decode_arith_plane(), latm_decode_frame(), latm_write_frame_header(), loco_decode_plane(), magy_decode_frame(), magy_decode_slice(), magy_decode_slice10(), mss1_decode_frame(), mss2_decode_frame(), mss4_decode_frame(), on2avc_decode_subframe(), parse_frame(), parse_grid_1_chunk(), parse_high_res_grid(), parse_lfe_chunk(), parse_nal_units(), parse_tonal_chunk(), parse_tonal_group(), parse_ts1_chunk(), parse_ts2_chunk(), pcx_decode_frame(), predictor_calc_error(), qcelp_decode_frame(), ra144_decode_frame(), ra288_decode_frame(), read_high_coeffs(), read_huffman_tree(), read_specific_config(), shn_probe(), shorten_decode_frame(), smka_decode_frame(), svq1_decode_frame(), swf_probe(), tak_decode_frame(), tak_parse(), tak_read_header(), tgq_decode_mb(), truemotion2rt_decode_frame(), tscc2_decode_slice(), tta_decode_frame(), tta_decode_init(), twinvq_read_bitstream(), vorbis_decode_frame(), vp3_decode_frame(), vp8_lossless_decode_frame(), vp9_superframe_filter(), wavpack_decode_block(), and xan_huffman_decode().
align_get_bits()
static const uint8_t* align_get_bits (GetBitContext * s) inline static
Definition at line 450 of file get_bits.h.
Referenced by avpriv_copy_pce_data(), avs_decode_frame(), cabac_init_decoder(), decode_band(), decode_band_hdr(), decode_component(), decode_frame(), decode_frame_header(), decode_gop_header(), decode_hq_slice(), decode_lowdelay(), decode_mb_info(), decode_pce(), decode_pic_hdr(), decode_rle(), decode_slice(), dirac_unpack_block_motion_data(), dirac_unpack_idwt_params(), dirac_unpack_prediction_parameters(), ff_ccitt_unpack(), ff_dirac_init_arith_decoder(), ff_h263_decode_picture_header(), ff_h263_resync(), ff_h264_decode_mb_cavlc(), ff_h264_sei_decode(), ff_jpegls_decode_picture(), ff_lag_rac_init(), ff_mjpeg_decode_sos(), ff_mpeg4_decode_picture_header(), ff_tak_decode_frame_header(), h261_resync(), handle_rstn(), ivi_dec_tile_data_size(), ivi_decode_blocks(), ljpeg_decode_rgb_scan(), ljpeg_decode_yuv_scan(), mjpeg_decode_app(), mp_decode_frame(), mpeg4_is_resync(), mpeg_decode_slice(), mss2_decode_frame(), read_block(), read_channel_data(), read_diff_float_data(), read_frame_data(), read_high_coeffs(), read_low_coeffs(), read_specific_config(), skip_data_stream_element(), tak_decode_frame(), tta_decode_frame(), and wma_decode_block().
get_vlc2()
static av_always_inline int get_vlc2 (GetBitContext * s, VLC_TYPE(*) table[2], int bits, int max_depth) static
Parse a vlc code.
Parameters
bits is the number of bits which will be read at once, must be identical to nb_bits in init_vlc()
max_depth is the number of times bits bits must be read to completely read the longest vlc code = (max_vlc_length + bits - 1) / bits
Definition at line 540 of file get_bits.h.
Referenced by asv1_decode_block(), asv1_get_level(), asv2_decode_block(), asv2_get_level(), bitplane_decoding(), dca_get_vlc(), decode_argb(), decode_argbi(), decode_argx(), decode_argxi(), decode_aybr(), decode_aybri(), decode_band_numwavs(), decode_block(), decode_byry(), decode_byryi(), decode_c82i(), decode_c82p(), decode_ca2i(), decode_ca2p(), decode_ca4i(), decode_ca4p(), decode_cce(), decode_channel(), decode_channel_sf_idx(), decode_channel_wordlen(), decode_coeff(), decode_coeffs(), decode_dc(), decode_envelope(), decode_exp_vlc(), decode_frame(), decode_gainc_levels(), decode_gainc_loc_codes(), decode_gainc_npoints(), decode_group3_1d_line(), decode_group3_2d_line(), decode_i_block(), decode_i_frame(), decode_mb_info(), decode_mv_component(), decode_p_block(), decode_plane(), decode_plane10(), decode_plane_bitstream(), decode_qu_spectra(), decode_residual(), decode_rgb(), decode_rgbi(), decode_rgbx(), decode_rgbxi(), decode_rle(), decode_scale_factors(), decode_scalefactors(), decode_tones_amplitude(), decode_tones_frequency(), decode_tones_info(), decode_ybr(), decode_ybr10(), decode_ybr10i(), decode_ybri(), decode_ybyr(), decode_yry10(), decode_yry10i(), decouple_info(), ff_h263_decode_mb(), ff_h263_decode_motion(), ff_msmpeg4_decode_motion(), ff_rv_decode_dc(), ff_wma_run_level_decode(), ff_wmv2_decode_mb(), fraps2_decode_plane(), gainc_level_mode1m(), gainc_loc_mode1(), get_coeff(), get_mvdata_interlaced(), get_scale_idx(), h261_decode_mb(), hq_decode_block(), hqa_decode_mb(), hqx_decode_422a(), hqx_decode_444a(), huffman_decode(), idx_to_quant(), imc_read_level_coeffs(), ir2_get_code(), ivi_decode_coded_blocks(), jpg_decode_block(), magy_decode_slice(), magy_decode_slice10(), mjpeg_decode_dc(), mp_get_vlc(), mpc7_decode_frame(), mpc8_decode_frame(), mpeg4_decode_dc(), mpeg4_decode_mb(), mpeg4_decode_partition_a(), mpeg4_decode_partition_b(), mpeg4_decode_sprite_trajectory(), mpeg_decode_mb(), mpeg_decode_motion(), mpeg_decode_slice(), msmpeg4_decode_dc(), msmpeg4v12_decode_mb(), msmpeg4v2_decode_motion(), msmpeg4v34_decode_mb(), mss4_decode_dct(), on2avc_decode_band_scales(), on2avc_decode_pairs(), on2avc_decode_quads(), parse_ch(), parse_vlc(), preview_obmc(), qdm2_get_vlc(), read_bfraction(), read_huff_channels(), read_quant_spectral_coeffs(), read_sbr_envelope(), read_sbr_noise(), rv34_decode_block(), rv34_decode_cbp(), rv40_decode_intra_types(), rv40_decode_mb_info(), setup_classifs(), smacker_decode_bigtree(), smka_decode_frame(), svq1_decode_block_intra(), svq1_decode_block_non_intra(), svq1_decode_delta_block(), svq1_decode_motion_vector(), synth_frame(), tm2_get_token(), tscc2_decode_mb(), unpack_block_qpis(), unpack_modes(), unpack_SQVH(), unpack_superblocks(), unpack_vectors(), unpack_vlcs(), vc1_decode_ac_coeff(), vc1_decode_b_mb(), vc1_decode_b_mb_intfi(), vc1_decode_b_mb_intfr(), vc1_decode_i_block(), vc1_decode_i_block_adv(), vc1_decode_i_blocks(), vc1_decode_i_blocks_adv(), vc1_decode_intra_block(), vc1_decode_p_block(), vc1_decode_p_mb(), vc1_decode_p_mb_intfi(), vc1_decode_p_mb_intfr(), vlc_decode_block(), vorbis_floor0_decode(), vorbis_floor1_decode(), vorbis_residue_decode_internal(), vp6_parse_coeff_huffman(), wma_decode_block(), wnv1_get_code(), x8_get_ac_rlf(), x8_get_dc_rlf(), and x8_get_orient_vlc().
decode012()
static int decode012 (GetBitContext * gb) inline static
Definition at line 555 of file get_bits.h.
Referenced by decode_frame_header(), ff_msmpeg4_decode_picture_header(), ff_vc1_parse_frame_header(), ff_vc1_parse_frame_header_adv(), ff_wmv2_decode_mb(), ff_wmv2_decode_secondary_picture_header(), msmpeg4v34_decode_mb(), mss4_decode_frame(), vc1_decode_b_mb(), vc1_decode_b_mb_intfi(), vc1_decode_b_mb_intfr(), vc1_decode_p_block(), and wmv2_decode_inter_block().
decode210()
static int decode210 (GetBitContext * gb) inline static
Definition at line 565 of file get_bits.h.
Referenced by decode_mb(), ff_vc1_parse_frame_header_adv(), and vc1_decode_ac_coeff().
get_bits_left()
static int get_bits_left (GetBitContext * gb) inline static
Definition at line 573 of file get_bits.h.
Referenced by aac_decode_er_frame(), aac_decode_frame_int(), alac_decode_frame(), ape_decode_value_3860(), atrac3p_decode_frame(), avpriv_mpeg4audio_get_config(), bit_copy(), build_huffman(), cabac_init_decoder(), check_slice_end(), chs_parse_band_data(), copy_bits(), decode_422_bitstream(), decode_ac_coeffs(), decode_band_types(), decode_block(), decode_channel(), decode_channel_residues(), decode_component(), decode_eld_specific_config(), decode_element(), decode_frame(), decode_gain_info(), decode_gray_bitstream(), decode_hq_slice(), decode_i_block(), decode_lowdelay(), decode_lowdelay_slice(), decode_mb(), decode_pce(), decode_plane(), decode_plane10(), decode_plane_bitstream(), decode_profile_tier_level(), decode_rice(), decode_skip_count(), decode_slice(), decode_subframe(), decode_subframe_length(), decode_vol_header(), decode_vop_header(), decode_vui(), decode_vui_parameters(), dv_decode_video_segment(), dx2_decode_slice_410(), dx2_decode_slice_420(), ensure_bits(), escape124_decode_frame(), ff_dirac_init_arith_decoder(), ff_h263_decode_frame(), ff_h263_decode_mb(), ff_h263_decode_picture_header(), ff_h263_resync(), ff_h264_decode_mb_cavlc(), ff_h264_decode_seq_parameter_set(), ff_h264_sei_decode(), ff_hevc_decode_nal_pps(), ff_hevc_decode_nal_vps(), ff_hevc_parse_sps(), ff_intel_h263_decode_picture_header(), ff_ivi_decode_frame(), ff_lag_rac_init(), ff_mjpeg_decode_dht(), ff_mjpeg_decode_dqt(), ff_mjpeg_decode_sos(), ff_msmpeg4_decode_block(), flashsv_decode_frame(), fraps2_decode_plane(), g726_reset(), get_block(), get_dimension(), get_rice_ook(), get_rice_un(), get_sr_golomb_dst(), get_ts64(), h261_decode_mb(), h261_decode_picture_header(), h261_handle_packet(), h261_resync(), h263_decode_gob_header(), h263_handle_packet(), handle_rstn(), hls_slice_header(), init_quantized_coeffs_elem0(), init_tone_level_dequantization(), latm_decode_audio_specific_config(), magy_decode_slice(), magy_decode_slice10(), mjpeg_decode_app(), mjpeg_decode_com(), mjpeg_decode_scan(), more_rbsp_data(), mp_decode_frame(), mp_decode_layer3(), mpc8_decode_frame(), mpeg_decode_slice(), parse_aux_data(), parse_bintree(), parse_ch(), parse_coding_header(), parse_config_ALS(), parse_descriptor(), parse_fmtp_config(), parse_grid_1_chunk(), parse_grid_2(), parse_packet_header(), parse_ptl(), parse_rps(), parse_setup_header(), parse_subframe_audio(), parse_subframe_header(), parse_tonal(), parse_tonal_chunk(), parse_x96_coding_header(), parse_x96_subframe_audio(), parse_x96_subframe_header(), parse_xbr_subframe(), qdm2_fft_decode_tones(), read_audio_mux_element(), read_frame_data(), read_header(), read_len_table(), read_specific_config(), rice_decompress(), seq_unpack_rle_block(), shorten_decode_frame(), skip_1stop_8data_bits(), skip_data_stream_element(), skip_hdr_extension(), smka_decode_frame(), svq3_decode_frame(), svq3_decode_slice_header(), synth_superframe(), synthfilt_build_sb_samples(), tak_decode_frame(), tgv_decode_inter(), tm2_read_stream(), tscc2_decode_mb(), tta_decode_frame(), unpack_alpha(), unpack_block_qpis(), unpack_codebook(), unpack_modes(), unpack_superblocks(), unpack_vectors(), unpack_vlcs(), vble_unpack(), vc1_decode_ac_coeff(), vp6_parse_coeff_huffman(), wavpack_decode_block(), wma_decode_block(), wma_decode_superframe(), wmavoice_decode_packet(), wv_get_value(), wv_get_value_float(), and wv_get_value_integer().
skip_1stop_8data_bits()
static int skip_1stop_8data_bits (GetBitContext * gb) inline static
Definition at line 578 of file get_bits.h.
Referenced by ff_flv_decode_picture_header(), ff_h263_decode_picture_header(), ff_intel_h263_decode_picture_header(), fill_slice(), h261_decode_gob_header(), h261_decode_picture_header(), mpeg_decode_slice(), svq1_decode_frame_header(), svq3_decode_init(), svq3_decode_slice_header(), and vaapi_mpeg2_decode_slice().