FFmpeg: libavcodec/golomb.h File Reference
golomb.h File Reference
exp golomb vlc stuff
#include <stdint.h>
#include "get_bits.h"
#include "put_bits.h"
Macros
#define INVALID_VLC 0x80000000
Functions
static int get_ue_golomb (GetBitContext *gb)
Read an unsigned Exp-Golomb code in the range 0 to 8190.
static unsigned get_ue_golomb_long (GetBitContext *gb)
Read an unsigned Exp-Golomb code in the range 0 to UINT32_MAX-1.
static int get_ue_golomb_31 (GetBitContext *gb)
read unsigned exp golomb code, constraint to a max of 31.
static unsigned get_interleaved_ue_golomb (GetBitContext *gb)
static int get_te0_golomb (GetBitContext *gb, int range)
read unsigned truncated exp golomb code.
static int get_te_golomb (GetBitContext *gb, int range)
read unsigned truncated exp golomb code.
static int get_se_golomb (GetBitContext *gb)
read signed exp golomb code.
static int get_se_golomb_long (GetBitContext *gb)
static int get_interleaved_se_golomb (GetBitContext *gb)
static int dirac_get_se_golomb (GetBitContext *gb)
static int get_ur_golomb (GetBitContext *gb, int k, int limit, int esc_len)
read unsigned golomb rice code (ffv1).
static int get_ur_golomb_jpegls (GetBitContext *gb, int k, int limit, int esc_len)
read unsigned golomb rice code (jpegls).
static int get_sr_golomb (GetBitContext *gb, int k, int limit, int esc_len)
read signed golomb rice code (ffv1).
static int get_sr_golomb_flac (GetBitContext *gb, int k, int limit, int esc_len)
read signed golomb rice code (flac).
static unsigned int get_ur_golomb_shorten (GetBitContext *gb, int k)
read unsigned golomb rice code (shorten).
static int get_sr_golomb_shorten (GetBitContext *gb, int k)
read signed golomb rice code (shorten).
static void set_ue_golomb (PutBitContext *pb, int i)
write unsigned exp golomb code.
static void set_te_golomb (PutBitContext *pb, int i, int range)
write truncated unsigned exp golomb code.
static void set_se_golomb (PutBitContext *pb, int i)
write signed exp golomb code.
static void set_ur_golomb (PutBitContext *pb, int i, int k, int limit, int esc_len)
write unsigned golomb rice code (ffv1).
static void set_ur_golomb_jpegls (PutBitContext *pb, int i, int k, int limit, int esc_len)
write unsigned golomb rice code (jpegls).
static void set_sr_golomb (PutBitContext *pb, int i, int k, int limit, int esc_len)
write signed golomb rice code (ffv1).
static void set_sr_golomb_flac (PutBitContext *pb, int i, int k, int limit, int esc_len)
write signed golomb rice code (flac).
Variables
const uint8_t ff_golomb_vlc_len [512]
const uint8_t ff_ue_golomb_vlc_code [512]
const int8_t ff_se_golomb_vlc_code [512]
const uint8_t ff_ue_golomb_len [256]
const uint8_t ff_interleaved_golomb_vlc_len [256]
const uint8_t ff_interleaved_ue_golomb_vlc_code [256]
const int8_t ff_interleaved_se_golomb_vlc_code [256]
const uint8_t ff_interleaved_dirac_golomb_vlc_code [256]
Detailed Description
exp golomb vlc stuff
Author
Michael Niedermayer micha.nosp@m.elni.nosp@m.@gmx..nosp@m.at and Alex Beregszaszi
Definition in file golomb.h.
Macro Definition Documentation
INVALID_VLC
#define INVALID_VLC 0x80000000
Definition at line 38 of file golomb.h.
Referenced by get_interleaved_se_golomb(), and svq3_mc_dir().
Function Documentation
get_ue_golomb()
static int get_ue_golomb (GetBitContext * gb) inline static
Read an unsigned Exp-Golomb code in the range 0 to 8190.
Definition at line 53 of file golomb.h.
Referenced by decode_mb_i(), decode_pic(), decode_residual_inter(), decode_vui_parameters(), extend_code(), ff_h264_decode_mb_cavlc(), ff_h264_decode_picture_parameter_set(), ff_h264_decode_seq_parameter_set(), ff_h264_parse_ref_count(), ff_h264_pred_weight_table(), get_sr_golomb_shorten(), get_te0_golomb(), get_te_golomb(), get_ue_code(), h264_slice_header_parse(), hevc_find_frame_end(), main(), parse_nal_units(), and scan_mmco_reset().
get_ue_golomb_long()
static unsigned get_ue_golomb_long (GetBitContext * gb) inline static
Read an unsigned Exp-Golomb code in the range 0 to UINT32_MAX-1.
Definition at line 85 of file golomb.h.
Referenced by active_parameter_sets(), decode_display_orientation(), decode_frame_packing_arrangement(), decode_hrd(), decode_hrd_parameters(), decode_lt_rps(), decode_nal_sei_frame_packing_arrangement(), decode_recovery_point(), decode_sublayer_hrd(), decode_vui(), ff_h264_decode_mb_cavlc(), ff_h264_decode_ref_pic_list_reordering(), ff_h264_decode_ref_pic_marking(), ff_hevc_decode_nal_pps(), ff_hevc_decode_nal_vps(), ff_hevc_decode_short_term_rps(), ff_hevc_parse_sps(), get_last_needed_nal(), get_se_golomb_long(), h264_find_frame_end(), h264_probe(), h264_slice_header_parse(), hevc_parse_slice_header(), hls_slice_header(), hvcc_parse_pps(), hvcc_parse_sps(), hvcc_parse_vui(), main(), parse_nal_units(), parse_rps(), pps_range_extensions(), pred_weight_table(), scaling_list_data(), scan_mmco_reset(), skip_hrd_parameters(), skip_scaling_list_data(), skip_sub_layer_hrd_parameters(), skip_sub_layer_ordering_info(), and skip_timing_info().
get_ue_golomb_31()
static int get_ue_golomb_31 (GetBitContext * gb) inline static
read unsigned exp golomb code, constraint to a max of 31.
the return value is undefined if the stored value exceeds 31.
Definition at line 100 of file golomb.h.
Referenced by decode_buffering_period(), decode_hrd_parameters(), ff_h264_decode_mb_cavlc(), ff_h264_decode_picture_parameter_set(), ff_h264_decode_ref_pic_list_reordering(), ff_h264_decode_ref_pic_marking(), ff_h264_decode_seq_parameter_set(), h264_slice_header_parse(), parse_nal_units(), and scan_mmco_reset().
get_interleaved_ue_golomb()
static unsigned get_interleaved_ue_golomb (GetBitContext * gb) inline static
Definition at line 115 of file golomb.h.
Referenced by decode_component(), dirac_get_se_golomb(), dirac_unpack_block_motion_data(), dirac_unpack_idwt_params(), dirac_unpack_prediction_parameters(), rv30_decode_intra_types(), rv30_decode_mb_info(), rv40_decode_mb_info(), send_picture(), svq3_decode_block(), svq3_decode_frame(), svq3_decode_init(), svq3_decode_mb(), and svq3_decode_slice_header().
get_te0_golomb()
static int get_te0_golomb (GetBitContext * gb, int range) inline static
read unsigned truncated exp golomb code.
Definition at line 155 of file golomb.h.
Referenced by get_sr_golomb_shorten().
get_te_golomb()
static int get_te_golomb (GetBitContext * gb, int range) inline static
read unsigned truncated exp golomb code.
Definition at line 170 of file golomb.h.
get_se_golomb()
static int get_se_golomb (GetBitContext * gb) inline static
read signed exp golomb code.
Definition at line 183 of file golomb.h.
Referenced by decode_mb_i(), decode_pic(), decode_residual_inter(), decode_scaling_list(), ff_cavs_mv(), ff_h264_decode_mb_cavlc(), ff_h264_decode_picture_parameter_set(), ff_h264_decode_seq_parameter_set(), ff_h264_pred_weight_table(), ff_hevc_decode_nal_pps(), fic_decode_block(), get_sr_golomb_shorten(), h264_slice_header_parse(), hls_slice_header(), intlist_read(), main(), parse_nal_units(), pred_weight_table(), and scaling_list_data().
get_se_golomb_long()
static int get_se_golomb_long (GetBitContext * gb) inline static
Definition at line 215 of file golomb.h.
Referenced by hvcc_parse_pps(), pps_range_extensions(), and skip_scaling_list_data().
get_interleaved_se_golomb()
static int get_interleaved_se_golomb (GetBitContext * gb) inline static
Definition at line 222 of file golomb.h.
Referenced by rv34_decode_mv(), svq3_decode_mb(), and svq3_mc_dir().
dirac_get_se_golomb()
static int dirac_get_se_golomb (GetBitContext * gb) inline static
Definition at line 255 of file golomb.h.
Referenced by codeblock(), coeff_unpack_golomb(), dirac_decode_picture_header(), and dirac_unpack_prediction_parameters().
get_ur_golomb()
static int get_ur_golomb (GetBitContext * gb, int k, int limit, int esc_len) inline static
read unsigned golomb rice code (ffv1).
Definition at line 270 of file golomb.h.
Referenced by get_sr_golomb(), and get_sr_golomb_dst().
get_ur_golomb_jpegls()
static int get_ur_golomb_jpegls (GetBitContext * gb, int k, int limit, int esc_len) inline static
read unsigned golomb rice code (jpegls).
Definition at line 305 of file golomb.h.
Referenced by get_sr_golomb_flac(), get_sr_golomb_shorten(), get_ur_golomb_shorten(), loco_get_rice(), ls_get_code_regular(), and ls_get_code_runterm().
get_sr_golomb()
static int get_sr_golomb (GetBitContext * gb, int k, int limit, int esc_len) inline static
read signed golomb rice code (ffv1).
Definition at line 370 of file golomb.h.
Referenced by get_vlc_symbol().
get_sr_golomb_flac()
static int get_sr_golomb_flac (GetBitContext * gb, int k, int limit, int esc_len) inline static
read signed golomb rice code (flac).
Definition at line 380 of file golomb.h.
Referenced by decode_residuals().
get_ur_golomb_shorten()
static unsigned int get_ur_golomb_shorten (GetBitContext * gb, int k) inline static
read unsigned golomb rice code (shorten).
Definition at line 390 of file golomb.h.
Referenced by decode_subframe_lpc(), get_uint(), read_header(), shn_probe(), and shorten_decode_frame().
get_sr_golomb_shorten()
static int get_sr_golomb_shorten (GetBitContext * gb, int k) inline static
read signed golomb rice code (shorten).
Definition at line 398 of file golomb.h.
Referenced by decode_subframe_lpc().
set_ue_golomb()
static void set_ue_golomb (PutBitContext * pb, int i) inline static
write unsigned exp golomb code.
Definition at line 461 of file golomb.h.
Referenced by ff_hevc_encode_nal_vps(), main(), set_se_golomb(), and set_te_golomb().
set_te_golomb()
static void set_te_golomb (PutBitContext * pb, int i, int range) inline static
write truncated unsigned exp golomb code.
Definition at line 476 of file golomb.h.
set_se_golomb()
static void set_se_golomb (PutBitContext * pb, int i) inline static
write signed exp golomb code.
16 bits at most.
Definition at line 490 of file golomb.h.
Referenced by intlist_read(), and main().
set_ur_golomb()
static void set_ur_golomb (PutBitContext * pb, int i, int k, int limit, int esc_len) inline static
write unsigned golomb rice code (ffv1).
Definition at line 511 of file golomb.h.
Referenced by set_sr_golomb().
set_ur_golomb_jpegls()
static void set_ur_golomb_jpegls (PutBitContext * pb, int i, int k, int limit, int esc_len) inline static
write unsigned golomb rice code (jpegls).
Definition at line 528 of file golomb.h.
Referenced by ls_encode_regular(), ls_encode_runterm(), and set_sr_golomb_flac().
set_sr_golomb()
static void set_sr_golomb (PutBitContext * pb, int i, int k, int limit, int esc_len) inline static
write signed golomb rice code (ffv1).
Definition at line 557 of file golomb.h.
Referenced by put_vlc_symbol().
set_sr_golomb_flac()
static void set_sr_golomb_flac (PutBitContext * pb, int i, int k, int limit, int esc_len) inline static
write signed golomb rice code (flac).
Definition at line 571 of file golomb.h.
Referenced by write_subframes().
Variable Documentation
ff_golomb_vlc_len
const uint8_t ff_golomb_vlc_len[512]
Definition at line 31 of file golomb.c.
Referenced by get_se_golomb(), get_ue_golomb(), and get_ue_golomb_31().
ff_ue_golomb_vlc_code
const uint8_t ff_ue_golomb_vlc_code[512]
Definition at line 50 of file golomb.c.
Referenced by get_ue_golomb(), and get_ue_golomb_31().
ff_se_golomb_vlc_code
const int8_t ff_se_golomb_vlc_code[512]
Definition at line 69 of file golomb.c.
Referenced by get_se_golomb().
ff_ue_golomb_len
const uint8_t ff_ue_golomb_len[256]
Definition at line 89 of file golomb.c.
Referenced by set_ue_golomb().
ff_interleaved_golomb_vlc_len
const uint8_t ff_interleaved_golomb_vlc_len[256]
Definition at line 100 of file golomb.c.
Referenced by get_interleaved_se_golomb(), and get_interleaved_ue_golomb().
ff_interleaved_ue_golomb_vlc_code
const uint8_t ff_interleaved_ue_golomb_vlc_code[256]
Definition at line 119 of file golomb.c.
Referenced by get_interleaved_ue_golomb().
ff_interleaved_se_golomb_vlc_code
const int8_t ff_interleaved_se_golomb_vlc_code[256]
Definition at line 138 of file golomb.c.
Referenced by get_interleaved_se_golomb().
ff_interleaved_dirac_golomb_vlc_code
const uint8_t ff_interleaved_dirac_golomb_vlc_code[256]
Definition at line 157 of file golomb.c.
Referenced by get_interleaved_ue_golomb().