FFmpeg: libavformat/gopher.c File Reference
gopher.c File Reference
#include "libavutil/avstring.h"
#include "avformat.h"
#include "internal.h"
#include "network.h"
#include "url.h"
Data Structures
struct GopherContext
Functions
static int gopher_write (URLContext *h, const uint8_t *buf, int size)
static int gopher_connect (URLContext *h, const char *path)
static int gopher_close (URLContext *h)
static int gopher_open (URLContext *h, const char *uri, int flags)
static int gopher_read (URLContext *h, uint8_t *buf, int size)
Variables
const URLProtocol ff_gopher_protocol
Function Documentation
gopher_write()
static int gopher_write (URLContext * h, const uint8_t * buf, int size) static
Definition at line 35 of file gopher.c.
Referenced by gopher_connect().
gopher_connect()
static int gopher_connect (URLContext * h, const char * path) static
Definition at line 41 of file gopher.c.
Referenced by gopher_open().
gopher_close()
static int gopher_close (URLContext * h) static
Definition at line 68 of file gopher.c.
Referenced by gopher_open().
gopher_open()
static int gopher_open (URLContext * h, const char * uri, int flags) static
Definition at line 78 of file gopher.c.
gopher_read()
static int gopher_read (URLContext * h, uint8_t * buf, int size) static
Definition at line 109 of file gopher.c.
Variable Documentation
ff_gopher_protocol
const URLProtocol ff_gopher_protocol
Initial value:
= {
    .name           = "gopher",
    .url_open       = gopher_open,
    .url_read       = gopher_read,
    .url_write      = gopher_write,
    .url_close      = gopher_close,
    .priv_data_size = sizeof(GopherContext),
    .flags          = URL_PROTOCOL_FLAG_NETWORK,
}
Definition at line 117 of file gopher.c.