FFmpeg: VDPAU Decoder and Renderer
VDPAU Decoder and Renderer
libavcodec » Codecs » Hardware Accelerators bridge
VDPAU hardware acceleration has two modules.
Files
file vdpau.h
Public libavcodec VDPAU header.
Data Structures
union AVVDPAUPictureInfo
struct AVVDPAUContext
This structure is used to share data between the libavcodec library and the client video application.
struct vdpau_render_state
This structure is used as a callback between the FFmpeg decoder (vd_) and presentation (vo_) module.
Macros
#define FF_VDPAU_STATE_USED_FOR_RENDER 1
The videoSurface is used for rendering.
#define FF_VDPAU_STATE_USED_FOR_REFERENCE 2
The videoSurface is needed for reference/prediction.
Typedefs
typedef int(* AVVDPAU_Render2) (struct AVCodecContext *, struct AVFrame *, const VdpPictureInfo *, uint32_t, const VdpBitstreamBuffer *)
Functions
AVVDPAUContext * av_alloc_vdpaucontext (void)
allocation function for AVVDPAUContext
AVVDPAU_Render2 av_vdpau_hwaccel_get_render2 (const AVVDPAUContext *)
void av_vdpau_hwaccel_set_render2 (AVVDPAUContext *, AVVDPAU_Render2)
int av_vdpau_bind_context (AVCodecContext *avctx, VdpDevice device, VdpGetProcAddress *get_proc_address, unsigned flags)
Associate a VDPAU device with a codec context for hardware acceleration.
int av_vdpau_get_surface_parameters (AVCodecContext *avctx, VdpChromaType *type, uint32_t *width, uint32_t *height)
Gets the parameters to create an adequate VDPAU video surface for the codec context using VDPAU hardware decoding acceleration.
AVVDPAUContext * av_vdpau_alloc_context (void)
Allocate an AVVDPAUContext.
attribute_deprecated int av_vdpau_get_profile (AVCodecContext *avctx, VdpDecoderProfile *profile)
Get a decoder profile that should be used for initializing a VDPAU decoder.
Detailed Description
VDPAU hardware acceleration has two modules.
VDPAU decoding
VDPAU presentation
The VDPAU decoding module parses all headers using FFmpeg parsing mechanisms and uses VDPAU for the actual decoding.
As per the current implementation, the actual decoding and rendering (API calls) are done as part of the VDPAU presentation (vo_vdpau.c) module.
Macro Definition Documentation
FF_VDPAU_STATE_USED_FOR_RENDER
#define FF_VDPAU_STATE_USED_FOR_RENDER 1
The videoSurface is used for rendering.
Definition at line 219 of file vdpau.h.
FF_VDPAU_STATE_USED_FOR_REFERENCE
#define FF_VDPAU_STATE_USED_FOR_REFERENCE 2
The videoSurface is needed for reference/prediction.
The codec manipulates this.
Definition at line 225 of file vdpau.h.
Typedef Documentation
AVVDPAU_Render2
typedef int(* AVVDPAU_Render2) (struct AVCodecContext *, struct AVFrame *, const VdpPictureInfo *, uint32_t, const VdpBitstreamBuffer *)
Definition at line 72 of file vdpau.h.
Function Documentation
av_alloc_vdpaucontext()
AVVDPAUContext* av_alloc_vdpaucontext (void)
allocation function for AVVDPAUContext
Allows extending the struct without breaking API/ABI
Definition at line 75 of file vdpau.c.
av_vdpau_hwaccel_get_render2()
AVVDPAU_Render2 av_vdpau_hwaccel_get_render2 (const AVVDPAUContext *)
av_vdpau_hwaccel_set_render2()
void av_vdpau_hwaccel_set_render2 (AVVDPAUContext * , AVVDPAU_Render2)
av_vdpau_bind_context()
int av_vdpau_bind_context (AVCodecContext * avctx, VdpDevice device, VdpGetProcAddress * get_proc_address, unsigned flags)
Associate a VDPAU device with a codec context for hardware acceleration.
This function is meant to be called from the get_format() codec callback, or earlier. It can also be called after avcodec_flush_buffers() to change the underlying VDPAU device mid-stream (e.g. to recover from non-transparent display preemption).
Note
get_format() must return AV_PIX_FMT_VDPAU if this function completes successfully.
Parameters
avctx decoding context whose get_format() callback is invoked
device VDPAU device handle to use for hardware acceleration
get_proc_address VDPAU device driver
flags zero of more OR'd AV_HWACCEL_FLAG_* flags
Returns
0 on success, an AVERROR code on failure.
Definition at line 758 of file vdpau.c.
Referenced by vdpau_alloc().
av_vdpau_get_surface_parameters()
int av_vdpau_get_surface_parameters (AVCodecContext * avctx, VdpChromaType * type, uint32_t * width, uint32_t * height)
Gets the parameters to create an adequate VDPAU video surface for the codec context using VDPAU hardware decoding acceleration.
Note
Behavior is undefined if the context was not successfully bound to a VDPAU device using av_vdpau_bind_context().
Parameters
avctx the codec context being used for decoding the stream
type storage space for the VDPAU video surface chroma type (or NULL to ignore)
width storage space for the VDPAU video surface pixel width (or NULL to ignore)
height storage space for the VDPAU video surface pixel height (or NULL to ignore)
Returns
0 on success, a negative AVERROR code on failure.
Definition at line 82 of file vdpau.c.
Referenced by ff_vdpau_common_init().
av_vdpau_alloc_context()
AVVDPAUContext* av_vdpau_alloc_context (void)
Allocate an AVVDPAUContext.
Returns
Newly-allocated AVVDPAUContext or NULL on failure.
Definition at line 753 of file vdpau.c.
Referenced by av_alloc_vdpaucontext().
av_vdpau_get_profile()
attribute_deprecated int av_vdpau_get_profile (AVCodecContext * avctx, VdpDecoderProfile * profile)
Get a decoder profile that should be used for initializing a VDPAU decoder.
Should be called from the AVCodecContext.get_format() callback.
Deprecated:
Use av_vdpau_bind_context() instead.
Parameters
avctx the codec context being used for decoding the stream
profile a pointer into which the result will be written on success. The contents of profile are undefined if this function returns an error.
Returns
0 on success (non-negative), a negative AVERROR on failure.
Definition at line 705 of file vdpau.c.