FFmpeg: Crypto and Hashing
Crypto and Hashing
libavutil
Modules
AES
Base64
Blowfish
CAMELLIA
CAST5
DES
Hash Functions
Hash functions useful in multimedia.
HMAC
LZO
RC4
TEA
TWOFISH
XTEA
Functions
uint32_t av_get_random_seed (void)
Get a seed to use in conjunction with random functions.
Detailed Description
Function Documentation
av_get_random_seed()
uint32_t av_get_random_seed (void)
Get a seed to use in conjunction with random functions.
This function tries to provide a good seed at a best effort bases. Its possible to call this function multiple times if more bits are needed. It can be quite slow, which is why it should only be used as seed for a faster PRNG. The quality of the seed depends on the platform.
Definition at line 120 of file random_seed.c.
Referenced by av_aes_ctr_set_random_iv(), av_parse_color(), config_input(), config_props(), do_adobe_auth(), do_llnw_auth(), ff_rtsp_open_transport_ctx(), init(), main(), make_digest_auth(), mkv_write_attachments(), mkv_write_header(), mxf_gen_umid(), ogg_write_header(), prompeg_init(), rtmp_server_handshake(), rtp_write_header(), rtsp_read_setup(), and sap_write_header().