FFmpeg: Option setting functions
Option setting functions
libavutil » Data Structures » AVOptions
Those functions set the field of obj with the given name to value.
Macros
#define av_opt_set_int_list(obj, name, val, term, flags)
Set a binary option to an integer list.
Functions
int av_opt_set (void *obj, const char *name, const char *val, int search_flags)
int av_opt_set_int (void *obj, const char *name, int64_t val, int search_flags)
int av_opt_set_double (void *obj, const char *name, double val, int search_flags)
int av_opt_set_q (void *obj, const char *name, AVRational val, int search_flags)
int av_opt_set_bin (void *obj, const char *name, const uint8_t *val, int size, int search_flags)
int av_opt_set_image_size (void *obj, const char *name, int w, int h, int search_flags)
int av_opt_set_pixel_fmt (void *obj, const char *name, enum AVPixelFormat fmt, int search_flags)
int av_opt_set_sample_fmt (void *obj, const char *name, enum AVSampleFormat fmt, int search_flags)
int av_opt_set_video_rate (void *obj, const char *name, AVRational val, int search_flags)
int av_opt_set_channel_layout (void *obj, const char *name, int64_t ch_layout, int search_flags)
int av_opt_set_dict_val (void *obj, const char *name, const AVDictionary *val, int search_flags)
Detailed Description
Those functions set the field of obj with the given name to value.
Parameters
[in] obj A struct whose first element is a pointer to an AVClass.
[in] name the name of the field to set
[in] val The value to set. In case of av_opt_set() if the field is not of a string type, then the given string is parsed. SI postfixes and some named scalars are supported. If the field is of a numeric type, it has to be a numeric or named scalar. Behavior with more than one scalar and +- infix operators is undefined. If the field is of a flags type, it has to be a sequence of numeric scalars or named flags separated by '+' or '-'. Prefixing a flag with '+' causes it to be set without affecting the other flags; similarly, '-' unsets a flag.
search_flags flags passed to av_opt_find2. I.e. if AV_OPT_SEARCH_CHILDREN is passed here, then the option may be set on a child of obj.
Returns
0 if the value has been set, or an AVERROR code in case of error: AVERROR_OPTION_NOT_FOUND if no matching option exists AVERROR(ERANGE) if the value is out of range AVERROR(EINVAL) if the value is not valid
Macro Definition Documentation
av_opt_set_int_list
#define av_opt_set_int_list (obj, name, val, term, flags)
Value:
(av_int_list_length(val, term) > INT_MAX / sizeof(*(val)) ? \
     AVERROR(EINVAL) : \
     av_opt_set_bin(obj, name, (const uint8_t *)(val), \
                    av_int_list_length(val, term) * sizeof(*(val)), flags))
Set a binary option to an integer list.
Parameters
obj AVClass object to set options on
name name of the binary option
val pointer to an integer list (must have the correct type with regard to the contents of the list)
term list terminator (usually 0 or -1)
flags search flags
Examples:
filtering_audio.c, and filtering_video.c.
Definition at line 709 of file opt.h.
Referenced by asink_init(), get_video_frame(), init_filters(), lavfi_read_header(), and vsink_init().
Function Documentation
av_opt_set()
int av_opt_set (void * obj, const char * name, const char * val, int search_flags)
Definition at line 451 of file opt.c.
Referenced by av_opencl_set_option(), av_opt_set_dict2(), av_opt_set_from_string(), avcodec_get_subtitle_rect_class(), avformat_find_stream_info(), choose_pix_fmts(), config_props(), configure_filtergraph(), dump_stream_format(), estimate_timings_from_pts(), ff_rtsp_open_transport_ctx(), ffserver_save_avoption(), filter_frame(), get_video_frame(), hls_start(), hls_write_packet(), init(), init_context_defaults(), init_dict(), init_filter_graph(), mmsh_open_internal(), open_output_file(), opt_default(), parse_key_value_pair(), process_command(), process_options(), rtmp_http_open(), segment_start(), store_icy(), test_copy(), url_alloc_for_protocol(), video_encode_example(), and writer_open().
av_opt_set_int()
int av_opt_set_int (void * obj, const char * name, int64_t val, int search_flags)
Definition at line 560 of file opt.c.
Referenced by asink_init(), chunk_mux_init(), config_audio_output(), config_input(), config_output(), config_props(), configure_output_audio_filter(), ffm_set_write_index(), get_video_frame(), init_dict(), init_filter_graph(), init_input_stream(), insert_trim(), lavfi_read_header(), main(), open_audio(), open_input_file(), opus_decode_init(), opus_init_resample(), output_single_frame(), process_client(), swr_alloc_set_opts(), swr_config_frame(), and sws_getCachedContext().
av_opt_set_double()
int av_opt_set_double (void * obj, const char * name, double val, int search_flags)
Definition at line 565 of file opt.c.
av_opt_set_q()
int av_opt_set_q (void * obj, const char * name, AVRational val, int search_flags)
Definition at line 570 of file opt.c.
Referenced by init_filter_graph().
av_opt_set_bin()
int av_opt_set_bin (void * obj, const char * name, const uint8_t * val, int size, int search_flags)
Definition at line 575 of file opt.c.
Referenced by init_filter(), rtmp_calc_swfhash(), rtmp_http_open(), and rtmp_http_send_cmd().
av_opt_set_image_size()
int av_opt_set_image_size (void * obj, const char * name, int w, int h, int search_flags)
Definition at line 605 of file opt.c.
av_opt_set_pixel_fmt()
int av_opt_set_pixel_fmt (void * obj, const char * name, enum AVPixelFormat fmt, int search_flags)
Definition at line 673 of file opt.c.
av_opt_set_sample_fmt()
int av_opt_set_sample_fmt (void * obj, const char * name, enum AVSampleFormat fmt, int search_flags)
Definition at line 678 of file opt.c.
Referenced by config_audio_output(), main(), and open_audio().
av_opt_set_video_rate()
int av_opt_set_video_rate (void * obj, const char * name, AVRational val, int search_flags)
Definition at line 627 of file opt.c.
av_opt_set_channel_layout()
int av_opt_set_channel_layout (void * obj, const char * name, int64_t ch_layout, int search_flags)
Definition at line 683 of file opt.c.
av_opt_set_dict_val()
int av_opt_set_dict_val (void * obj, const char * name, const AVDictionary * val, int search_flags)
Note
Any old dictionary present is discarded and replaced with a copy of the new one. The caller still owns val is and responsible for freeing it.
Definition at line 699 of file opt.c.
Referenced by read_frame_internal().