FFmpeg: AES
AES
libavutil » Crypto and Hashing
Functions
struct AVAES * av_aes_alloc (void)
Allocate an AVAES context.
int av_aes_init (struct AVAES *a, const uint8_t *key, int key_bits, int decrypt)
Initialize an AVAES context.
void av_aes_crypt (struct AVAES *a, uint8_t *dst, const uint8_t *src, int count, uint8_t *iv, int decrypt)
Encrypt or decrypt a buffer using a previously initialized context.
Variables
const int av_aes_size
Detailed Description
Function Documentation
av_aes_alloc()
struct AVAES* av_aes_alloc (void)
Allocate an AVAES context.
Definition at line 31 of file aes.c.
Referenced by av_aes_ctr_init(), crypto_open2(), ff_srtp_set_crypto(), main(), mov_read_adrm(), mxf_decrypt_triplet(), and run_lavu_aes128().
av_aes_init()
int av_aes_init (struct AVAES * a, const uint8_t * key, int key_bits, int decrypt)
Initialize an AVAES context.
Parameters
key_bits 128, 192 or 256
decrypt 0 for encryption, 1 for decryption
Definition at line 195 of file aes.c.
Referenced by aax_filter(), av_aes_ctr_init(), crypto_open2(), ff_srtp_decrypt(), ff_srtp_encrypt(), ff_srtp_set_crypto(), main(), mov_read_adrm(), mxf_decrypt_triplet(), and run_lavu_aes128().
av_aes_crypt()
void av_aes_crypt (struct AVAES * a, uint8_t * dst, const uint8_t * src, int count, uint8_t * iv, int decrypt)
Encrypt or decrypt a buffer using a previously initialized context.
Parameters
count number of 16 byte blocks
dst destination array, can be equal to src
src source array, can be equal to dst
iv initialization vector for CBC mode, if NULL then ECB will be used
decrypt 0 for encryption, 1 for decryption
Definition at line 163 of file aes.c.
Referenced by aax_filter(), av_aes_ctr_crypt(), crypto_close(), crypto_read(), crypto_write(), encrypt_counter(), main(), mov_read_adrm(), mxf_decrypt_triplet(), and run_lavu_aes128().
Variable Documentation
av_aes_size
const int av_aes_size
Definition at line 29 of file aes.c.