FFmpeg: VDPAU_Decoding
VDPAU_Decoding
Functions
static int vdpau_error (VdpStatus status)
AVVDPAUContext * av_alloc_vdpaucontext (void)
allocation function for AVVDPAUContext
int av_vdpau_get_surface_parameters (AVCodecContext *avctx, VdpChromaType *type, uint32_t *width, uint32_t *height)
Gets the parameters to create an adequate VDPAU video surface for the codec context using VDPAU hardware decoding acceleration.
int ff_vdpau_common_init (AVCodecContext *avctx, VdpDecoderProfile profile, int level)
int ff_vdpau_common_uninit (AVCodecContext *avctx)
static int ff_vdpau_common_reinit (AVCodecContext *avctx)
int ff_vdpau_common_start_frame (struct vdpau_picture_context *pic_ctx, av_unused const uint8_t *buffer, av_unused uint32_t size)
int ff_vdpau_common_end_frame (AVCodecContext *avctx, AVFrame *frame, struct vdpau_picture_context *pic_ctx)
int ff_vdpau_add_buffer (struct vdpau_picture_context *pic_ctx, const uint8_t *buf, uint32_t size)
int av_vdpau_get_profile (AVCodecContext *avctx, VdpDecoderProfile *profile)
Get a decoder profile that should be used for initializing a VDPAU decoder.
AVVDPAUContext * av_vdpau_alloc_context (void)
Allocate an AVVDPAUContext.
int av_vdpau_bind_context (AVCodecContext *avctx, VdpDevice device, VdpGetProcAddress *get_proc, unsigned flags)
Associate a VDPAU device with a codec context for hardware acceleration.
Detailed Description
Function Documentation
vdpau_error()
static int vdpau_error (VdpStatus status) static
Definition at line 51 of file vdpau.c.
Referenced by ff_vdpau_common_end_frame(), ff_vdpau_common_init(), and ff_vdpau_common_uninit().
av_alloc_vdpaucontext()
AVVDPAUContext* av_alloc_vdpaucontext (void)
allocation function for AVVDPAUContext
Allows extending the struct without breaking API/ABI
Definition at line 75 of file vdpau.c.
av_vdpau_get_surface_parameters()
int av_vdpau_get_surface_parameters (AVCodecContext * avctx, VdpChromaType * type, uint32_t * width, uint32_t * height)
Gets the parameters to create an adequate VDPAU video surface for the codec context using VDPAU hardware decoding acceleration.
Note
Behavior is undefined if the context was not successfully bound to a VDPAU device using av_vdpau_bind_context().
Parameters
avctx the codec context being used for decoding the stream
type storage space for the VDPAU video surface chroma type (or NULL to ignore)
width storage space for the VDPAU video surface pixel width (or NULL to ignore)
height storage space for the VDPAU video surface pixel height (or NULL to ignore)
Returns
0 on success, a negative AVERROR code on failure.
Definition at line 82 of file vdpau.c.
Referenced by ff_vdpau_common_init().
ff_vdpau_common_init()
int ff_vdpau_common_init (AVCodecContext * avctx, VdpDecoderProfile profile, int level)
Definition at line 122 of file vdpau.c.
Referenced by vdpau_h264_init(), vdpau_hevc_init(), vdpau_mpeg4_init(), vdpau_mpeg_decode_slice(), and vdpau_vc1_init().
ff_vdpau_common_uninit()
int ff_vdpau_common_uninit (AVCodecContext * avctx)
Definition at line 235 of file vdpau.c.
Referenced by vdpau_mpeg_decode_slice(), and vdpau_vc1_init().
ff_vdpau_common_reinit()
static int ff_vdpau_common_reinit (AVCodecContext * avctx) static
Definition at line 258 of file vdpau.c.
Referenced by ff_vdpau_common_end_frame().
ff_vdpau_common_start_frame()
int ff_vdpau_common_start_frame (struct vdpau_picture_context * pic_ctx, av_unused const uint8_t * buffer, av_unused uint32_t size)
Definition at line 273 of file vdpau.c.
Referenced by vdpau_h264_start_frame(), vdpau_hevc_start_frame(), vdpau_mpeg4_start_frame(), vdpau_mpeg_start_frame(), and vdpau_vc1_start_frame().
ff_vdpau_common_end_frame()
int ff_vdpau_common_end_frame (AVCodecContext * avctx, AVFrame * frame, struct vdpau_picture_context * pic_ctx)
Definition at line 283 of file vdpau.c.
Referenced by ff_vdpau_common_end_frame(), vdpau_h264_end_frame(), and vdpau_hevc_end_frame().
ff_vdpau_add_buffer()
int ff_vdpau_add_buffer (struct vdpau_picture_context * pic_ctx, const uint8_t * buf, uint32_t size)
Definition at line 346 of file vdpau.c.
Referenced by vdpau_h264_decode_slice(), vdpau_hevc_decode_slice(), vdpau_mpeg4_start_frame(), vdpau_mpeg_decode_slice(), and vdpau_vc1_decode_slice().
av_vdpau_get_profile()
int av_vdpau_get_profile (AVCodecContext * avctx, VdpDecoderProfile * profile)
Get a decoder profile that should be used for initializing a VDPAU decoder.
Should be called from the AVCodecContext.get_format() callback.
Deprecated:
Use av_vdpau_bind_context() instead.
Parameters
avctx the codec context being used for decoding the stream
profile a pointer into which the result will be written on success. The contents of profile are undefined if this function returns an error.
Returns
0 on success (non-negative), a negative AVERROR on failure.
Definition at line 705 of file vdpau.c.
av_vdpau_alloc_context()
AVVDPAUContext* av_vdpau_alloc_context (void)
Allocate an AVVDPAUContext.
Returns
Newly-allocated AVVDPAUContext or NULL on failure.
Definition at line 753 of file vdpau.c.
Referenced by av_alloc_vdpaucontext().
av_vdpau_bind_context()
int av_vdpau_bind_context (AVCodecContext * avctx, VdpDevice device, VdpGetProcAddress * get_proc_address, unsigned flags)
Associate a VDPAU device with a codec context for hardware acceleration.
This function is meant to be called from the get_format() codec callback, or earlier. It can also be called after avcodec_flush_buffers() to change the underlying VDPAU device mid-stream (e.g. to recover from non-transparent display preemption).
Note
get_format() must return AV_PIX_FMT_VDPAU if this function completes successfully.
Parameters
avctx decoding context whose get_format() callback is invoked
device VDPAU device handle to use for hardware acceleration
get_proc_address VDPAU device driver
flags zero of more OR'd AV_HWACCEL_FLAG_* flags
Returns
0 on success, an AVERROR code on failure.
Definition at line 758 of file vdpau.c.
Referenced by vdpau_alloc().