FFmpeg: Utility functions
Utility functions
libavformat
Miscellaneous utility functions related to both muxing and demuxing (or neither).
Modules
RIFF FourCCs
Get the tables mapping RIFF FourCCs to libavcodec AVCodecIDs.
Macros
#define AV_FRAME_FILENAME_FLAGS_MULTIPLE 1
Allow multiple d.
Enumerations
enum AVTimebaseSource { AVFMT_TBCF_AUTO = -1, AVFMT_TBCF_DECODER, AVFMT_TBCF_DEMUXER }
Apply a list of bitstream filters to a packet.
Functions
void av_hex_dump (FILE *f, const uint8_t *buf, int size)
Send a nice hexadecimal dump of a buffer to the specified file stream.
void av_hex_dump_log (void *avcl, int level, const uint8_t *buf, int size)
Send a nice hexadecimal dump of a buffer to the log.
void av_pkt_dump2 (FILE *f, const AVPacket *pkt, int dump_payload, const AVStream *st)
Send a nice dump of a packet to the specified file stream.
void av_pkt_dump_log2 (void *avcl, int level, const AVPacket *pkt, int dump_payload, const AVStream *st)
Send a nice dump of a packet to the log.
enum AVCodecID av_codec_get_id (const struct AVCodecTag *const *tags, unsigned int tag)
Get the AVCodecID for the given codec tag tag.
unsigned int av_codec_get_tag (const struct AVCodecTag *const *tags, enum AVCodecID id)
Get the codec tag for the given codec id id.
int av_codec_get_tag2 (const struct AVCodecTag *const *tags, enum AVCodecID id, unsigned int *tag)
Get the codec tag for the given codec id.
int av_find_default_stream_index (AVFormatContext *s)
int av_index_search_timestamp (AVStream *st, int64_t timestamp, int flags)
Get the index for a specific timestamp.
int av_add_index_entry (AVStream *st, int64_t pos, int64_t timestamp, int size, int distance, int flags)
Add an index entry into a sorted list.
void av_url_split (char *proto, int proto_size, char *authorization, int authorization_size, char *hostname, int hostname_size, int *port_ptr, char *path, int path_size, const char *url)
Split a URL string into components.
void av_dump_format (AVFormatContext *ic, int index, const char *url, int is_output)
Print detailed information about the input or output format, such as duration, bitrate, streams, container, programs, metadata, side data, codec and time base.
int av_get_frame_filename2 (char *buf, int buf_size, const char *path, int number, int flags)
Return in 'buf' the path with 'd' replaced by a number.
int av_get_frame_filename (char *buf, int buf_size, const char *path, int number)
int av_filename_number_test (const char *filename)
Check whether filename actually is a numbered sequence generator.
int av_sdp_create (AVFormatContext *ac[], int n_files, char *buf, int size)
Generate an SDP for an RTP session.
int av_match_ext (const char *filename, const char *extensions)
Return a positive value if the given filename has one of the given extensions, 0 otherwise.
int avformat_query_codec (const AVOutputFormat *ofmt, enum AVCodecID codec_id, int std_compliance)
Test if the given container can store a codec.
AVRational av_guess_sample_aspect_ratio (AVFormatContext *format, AVStream *stream, AVFrame *frame)
Guess the sample aspect ratio of a frame, based on both the stream and the frame aspect ratio.
AVRational av_guess_frame_rate (AVFormatContext *ctx, AVStream *stream, AVFrame *frame)
Guess the frame rate, based on both the container and codec information.
int avformat_match_stream_specifier (AVFormatContext *s, AVStream *st, const char *spec)
Check if the stream st contained in s is matched by the stream specifier spec.
int avformat_queue_attached_pictures (AVFormatContext *s)
int avformat_transfer_internal_stream_timing_info (const AVOutputFormat *ofmt, AVStream *ost, const AVStream *ist, enum AVTimebaseSource copy_tb)
Transfer internal timing information from one stream to another.
AVRational av_stream_get_codec_timebase (const AVStream *st)
Get the internal codec timebase from a stream.
Detailed Description
Miscellaneous utility functions related to both muxing and demuxing (or neither).
Macro Definition Documentation
AV_FRAME_FILENAME_FLAGS_MULTIPLE
#define AV_FRAME_FILENAME_FLAGS_MULTIPLE 1
Allow multiple d.
Definition at line 2802 of file avformat.h.
Referenced by av_get_frame_filename2(), hls_start(), and write_packet().
Enumeration Type Documentation
AVTimebaseSource
enum AVTimebaseSource
Apply a list of bitstream filters to a packet.
Parameters
codec AVCodecContext, usually from an AVStream
pkt the packet to apply filters to. If, on success, the returned packet has size == 0 and side_data_elems == 0, it indicates that the packet should be dropped
bsfc a NULL-terminated list of filters to apply
Returns
>=0 on success; AVERROR code on failure
Enumerator
AVFMT_TBCF_AUTO
AVFMT_TBCF_DECODER
AVFMT_TBCF_DEMUXER
Definition at line 2973 of file avformat.h.
Function Documentation
av_hex_dump()
void av_hex_dump (FILE * f, const uint8_t * buf, int size)
Send a nice hexadecimal dump of a buffer to the specified file stream.
Parameters
f The file stream pointer where the dump should be sent to.
buf buffer
size buffer size
See also
av_hex_dump_log, av_pkt_dump2, av_pkt_dump_log2
Definition at line 74 of file dump.c.
av_hex_dump_log()
void av_hex_dump_log (void * avcl, int level, const uint8_t * buf, int size)
Send a nice hexadecimal dump of a buffer to the log.
Parameters
avcl A pointer to an arbitrary struct of which the first field is a pointer to an AVClass struct.
level The importance level of the message, lower values signifying higher importance.
buf buffer
size buffer size
See also
av_hex_dump, av_pkt_dump2, av_pkt_dump_log2
Definition at line 79 of file dump.c.
Referenced by asf_read_header().
av_pkt_dump2()
void av_pkt_dump2 (FILE * f, const AVPacket * pkt, int dump_payload, const AVStream * st)
Send a nice dump of a packet to the specified file stream.
Parameters
f The file stream pointer where the dump should be sent to.
pkt packet to dump
dump_payload True if the payload must be displayed, too.
st AVStream that the packet belongs to
Definition at line 108 of file dump.c.
av_pkt_dump_log2()
void av_pkt_dump_log2 (void * avcl, int level, const AVPacket * pkt, int dump_payload, const AVStream * st)
Send a nice dump of a packet to the log.
Parameters
avcl A pointer to an arbitrary struct of which the first field is a pointer to an AVClass struct.
level The importance level of the message, lower values signifying higher importance.
pkt packet to dump
dump_payload True if the payload must be displayed, too.
st AVStream that the packet belongs to
Definition at line 113 of file dump.c.
Referenced by process_input().
av_codec_get_id()
enum AVCodecID av_codec_get_id (const struct AVCodecTag *const * tags, unsigned int tag)
Get the AVCodecID for the given codec tag tag.
If no codec id is found returns AV_CODEC_ID_NONE.
Parameters
tags list of supported codec_id-codec_tag pairs, as stored in AVInputFormat.codec_tag and AVOutputFormat.codec_tag
tag codec tag to match to a codec ID
Referenced by decode_stream_header(), dshow_add_device(), dshow_cycle_formats(), init_output_stream_streamcopy(), seg_write_header(), and segment_mux_init().
av_codec_get_tag()
unsigned int av_codec_get_tag (const struct AVCodecTag *const * tags, enum AVCodecID id)
Get the codec tag for the given codec id id.
If no codec tag is found returns 0.
Parameters
tags list of supported codec_id-codec_tag pairs, as stored in AVInputFormat.codec_tag and AVOutputFormat.codec_tag
id codec ID to match to a codec tag
Referenced by init_muxer(), seg_write_header(), segment_mux_init(), and set_codec_str().
av_codec_get_tag2()
int av_codec_get_tag2 (const struct AVCodecTag *const * tags, enum AVCodecID id, unsigned int * tag)
Get the codec tag for the given codec id.
Parameters
tags list of supported codec_id - codec_tag pairs, as stored in AVInputFormat.codec_tag and AVOutputFormat.codec_tag
id codec id that should be searched for in the list
tag A pointer to the found tag
Returns
0 if id was not found in tags, > 0 if it was found
Referenced by init_output_stream_streamcopy().
av_find_default_stream_index()
int av_find_default_stream_index (AVFormatContext * s)
Definition at line 1805 of file utils.c.
Referenced by seek_frame_internal(), and update_wrap_reference().
av_index_search_timestamp()
int av_index_search_timestamp (AVStream * st, int64_t timestamp, int flags)
Get the index for a specific timestamp.
Parameters
st stream that the timestamp belongs to
timestamp timestamp to retrieve the index for
flags if AVSEEK_FLAG_BACKWARD then the returned index will correspond to the timestamp which is <= the requested one, if backward is 0, then it will be >= if AVSEEK_FLAG_ANY seek to any frame, only keyframes otherwise
Returns
< 0 if no such timestamp could be found
Definition at line 2073 of file utils.c.
Referenced by ape_read_seek(), asf_read_seek(), avi_read_packet(), avi_read_seek(), ff_seek_frame_binary(), film_read_seek(), find_prev_closest_index(), flac_seek(), gxf_seek(), img_read_seek(), matroska_read_seek(), mov_seek_stream(), mp3_seek(), mpc8_read_seek(), mpc_read_seek(), mv_read_seek(), ni_prepare_read(), nsv_read_seek(), nut_write_packet(), read_packet(), read_seek(), rl2_read_seek(), seek_frame_generic(), tta_read_seek(), voc_read_seek(), and webm_clusters_start_with_keyframe().
av_add_index_entry()
int av_add_index_entry (AVStream * st, int64_t pos, int64_t timestamp, int size, int distance, int flags)
Add an index entry into a sorted list.
Update the entry if the list already contains it.
Parameters
timestamp timestamp in the time base of the given stream
Definition at line 1964 of file utils.c.
Referenced by add_keyframes_index(), ape_read_header(), asf_build_simple_index(), asf_read_pts(), asf_read_simple_index(), asf_read_timestamp(), av_read_frame(), avi_read_idx1(), avi_sync(), cine_read_header(), clean_index(), ff_img_read_packet(), ff_voc_get_packet(), film_read_header(), find_and_decode_index(), flac_read_header(), flv_read_packet(), gxf_read_index(), matroska_add_index_entries(), matroska_parse_block(), mov_read_trun(), mpc8_parse_seektable(), mpc_read_packet(), mpegps_read_pes_header(), mpegts_get_dts(), mv_read_header(), nsv_parse_NSVs_header(), nut_write_packet(), nuv_read_dts(), pmp_header(), pva_read_header(), read_braindead_odml_indx(), read_frame_internal(), read_header(), read_index(), read_pakt_chunk(), read_part_of_packet(), read_xing_toc(), rl2_read_header(), rm_read_dts(), rm_read_index(), rm_read_packet(), rpl_read_header(), tta_read_header(), and xwma_read_header().
av_url_split()
void av_url_split (char * proto, int proto_size, char * authorization, int authorization_size, char * hostname, int hostname_size, int * port_ptr, char * path, int path_size, const char * url)
Split a URL string into components.
The pointers to buffers for storing individual components may be null, in order to ignore that component. Buffers for components not found are set to empty strings. If the port is not found, it is set to a negative value.
Parameters
proto the buffer for the protocol
proto_size the size of the proto buffer
authorization the buffer for the authorization
authorization_size the size of the authorization buffer
hostname the buffer for the host name
hostname_size the size of the hostname buffer
port_ptr a pointer to store the port number in
path the buffer for the path
path_size the size of the path buffer
url the URL to split
Definition at line 4486 of file utils.c.
Referenced by ff_rtp_set_remote_url(), ff_rtsp_open_transport_ctx(), ff_tls_open_underlying(), ff_udp_set_remote_url(), find_rtp_session_with_url(), ftp_connect(), ftp_move(), get_sockaddr(), gopher_open(), http_listen(), http_open_cnx_internal(), icecast_open(), libssh_connect(), libssh_move(), mms_open(), mmsh_open_internal(), parse_command_line(), prompeg_open(), resetup_tcp(), rtmp_http_open(), rtmp_open(), rtmpe_open(), rtp_open(), rtsp_cmd_describe(), rtsp_cmd_setup(), rtsp_listen(), sap_read_header(), sap_write_header(), sctp_open(), srtp_open(), tcp_open(), test_same_origin(), and udp_open().
av_dump_format()
void av_dump_format (AVFormatContext * ic, int index, const char * url, int is_output)
Print detailed information about the input or output format, such as duration, bitrate, streams, container, programs, metadata, side data, codec and time base.
Parameters
ic the context to analyze
index index of the stream to dump information about
url the URL to print, such as source or destination file
is_output Select whether the specified context is an input(0) or output(1)
Examples:
avio_reading.c, demuxing_decoding.c, muxing.c, remuxing.c, and transcoding.c.
Definition at line 541 of file dump.c.
Referenced by check_init_output_file(), main(), open_input_file(), open_output_file(), and read_thread().
av_get_frame_filename2()
int av_get_frame_filename2 (char * buf, int buf_size, const char * path, int number, int flags)
Return in 'buf' the path with 'd' replaced by a number.
Also handles the '%0nd' format where 'n' is the total number of digits and '%'.
Parameters
buf destination buffer
buf_size destination buffer size
path numbered sequence string
number frame number
flags AV_FRAME_FILENAME_FLAGS_*
Returns
0 if OK, -1 on format error
Definition at line 4426 of file utils.c.
Referenced by av_get_frame_filename(), hls_start(), and write_packet().
av_get_frame_filename()
int av_get_frame_filename (char * buf, int buf_size, const char * path, int number)
Definition at line 4481 of file utils.c.
Referenced by av_filename_number_test(), ff_img_read_packet(), find_image_range(), get_chunk_filename(), and set_segment_filename().
av_filename_number_test()
int av_filename_number_test (const char * filename)
Check whether filename actually is a numbered sequence generator.
Parameters
filename possible numbered sequence string
Returns
1 if a valid numbered sequence string, 0 otherwise
Definition at line 306 of file utils.c.
Referenced by av_guess_format(), avformat_open_input(), img_read_probe(), and open_output_file().
av_sdp_create()
int av_sdp_create (AVFormatContext * ac[], int n_files, char * buf, int size)
Generate an SDP for an RTP session.
Note, this overwrites the id values of AVStreams in the muxer contexts for getting unique dynamic payload types.
Parameters
ac array of AVFormatContexts describing the RTP streams. If the array is composed by only one context, such context can contain multiple AVStreams (one AVStream per RTP stream). Otherwise, all the contexts in the array (an AVCodecContext per RTP stream) must contain only one AVStream.
n_files number of AVCodecContexts contained in ac
buf buffer where the SDP will be stored (must be allocated by the caller)
size the size of the buffer
Returns
0 if OK, AVERROR_xxx on error
Definition at line 827 of file sdp.c.
Referenced by ff_rtsp_setup_output_streams(), prepare_sdp_description(), print_sdp(), and sap_write_header().
av_match_ext()
int av_match_ext (const char * filename, const char * extensions)
Return a positive value if the given filename has one of the given extensions, 0 otherwise.
Parameters
filename file name to check against the given extensions
extensions a comma-separated list of filename extensions
Definition at line 85 of file format.c.
Referenced by av_guess_format(), av_probe_input_format3(), http_parse_request(), img_read_probe(), ipod_get_codec_tag(), modplug_probe(), mpegts_init(), nsv_probe(), pgm_probe(), pgmyuv_probe(), and seg_init().
avformat_query_codec()
int avformat_query_codec (const AVOutputFormat * ofmt, enum AVCodecID codec_id, int std_compliance)
Test if the given container can store a codec.
Parameters
ofmt container to check for compatibility
codec_id codec to potentially store in container
std_compliance standards compliance level, one of FF_COMPLIANCE_*
Returns
1 if codec with ID codec_id can be stored in ofmt, 0 if it cannot. A negative number if this information is not available.
Definition at line 4701 of file utils.c.
Referenced by open_output_file().
av_guess_sample_aspect_ratio()
AVRational av_guess_sample_aspect_ratio (AVFormatContext * format, AVStream * stream, AVFrame * frame)
Guess the sample aspect ratio of a frame, based on both the stream and the frame aspect ratio.
Since the frame aspect ratio is set by the codec but the stream aspect ratio is set by the demuxer, these two may not be equal. This function tries to return the value that you should use if you would like to display the frame.
Basic logic is to use the stream aspect ratio if it is set to something sane otherwise use the frame aspect ratio. This way a container setting, which is usually easy to modify can override the coded value in the frames.
Parameters
format the format context which the stream is part of
stream the stream which the frame is part of
frame the frame with the aspect ratio to be determined
Returns
the guessed (valid) sample_aspect_ratio, 0/1 if no idea
Definition at line 4784 of file utils.c.
Referenced by get_video_frame(), read_thread(), show_frame(), and show_stream().
av_guess_frame_rate()
AVRational av_guess_frame_rate (AVFormatContext * ctx, AVStream * stream, AVFrame * frame)
Guess the frame rate, based on both the container and codec information.
Parameters
ctx the format context which the stream is part of
stream the stream which the frame is part of
frame the frame for which the frame rate should be determined, may be NULL
Returns
the guessed (valid) frame rate, 0/1 if no idea
Definition at line 4807 of file utils.c.
Referenced by configure_input_video_filter(), get_video_frame(), and video_thread().
avformat_match_stream_specifier()
int avformat_match_stream_specifier (AVFormatContext * s, AVStream * st, const char * spec)
Check if the stream st contained in s is matched by the stream specifier spec.
See the "stream specifiers" chapter in the documentation for the syntax of spec.
Returns
>0 if st is matched by spec; 0 if st is not matched by spec; AVERROR code if spec is invalid
Note
A stream specifier can match several streams in the format.
Definition at line 4828 of file utils.c.
Referenced by check_stream_specifier(), find_stream(), open_slave(), probe_file(), read_thread(), and select_reference_stream().
avformat_queue_attached_pictures()
int avformat_queue_attached_pictures (AVFormatContext * s)
Definition at line 453 of file utils.c.
Referenced by av_seek_frame(), avformat_open_input(), avformat_seek_file(), and hls_read_header().
avformat_transfer_internal_stream_timing_info()
int avformat_transfer_internal_stream_timing_info (const AVOutputFormat * ofmt, AVStream * ost, const AVStream * ist, enum AVTimebaseSource copy_tb)
Transfer internal timing information from one stream to another.
This function is useful when doing stream copy.
Parameters
ofmt target output format for ost
ost output stream which needs timings copy and adjustments
ist reference input stream to copy timings from
copy_tb define from where the stream codec timebase needs to be imported
Definition at line 5703 of file utils.c.
Referenced by init_output_stream_streamcopy().
av_stream_get_codec_timebase()
AVRational av_stream_get_codec_timebase (const AVStream * st)
Get the internal codec timebase from a stream.
Parameters
st input stream to extract the timebase from
Definition at line 5765 of file utils.c.
Referenced by init_output_stream_streamcopy().