FFmpeg: Option getting functions
Option getting functions
libavutil » Data Structures » AVOptions
Those functions get a value of the option with the given name from an object.
Functions
int av_opt_get (void *obj, const char *name, int search_flags, uint8_t **out_val)
int av_opt_get_int (void *obj, const char *name, int search_flags, int64_t *out_val)
int av_opt_get_double (void *obj, const char *name, int search_flags, double *out_val)
int av_opt_get_q (void *obj, const char *name, int search_flags, AVRational *out_val)
int av_opt_get_image_size (void *obj, const char *name, int search_flags, int *w_out, int *h_out)
int av_opt_get_pixel_fmt (void *obj, const char *name, int search_flags, enum AVPixelFormat *out_fmt)
int av_opt_get_sample_fmt (void *obj, const char *name, int search_flags, enum AVSampleFormat *out_fmt)
int av_opt_get_video_rate (void *obj, const char *name, int search_flags, AVRational *out_val)
int av_opt_get_channel_layout (void *obj, const char *name, int search_flags, int64_t *ch_layout)
int av_opt_get_dict_val (void *obj, const char *name, int search_flags, AVDictionary **out_val)
Detailed Description
Those functions get a value of the option with the given name from an object.
Parameters
[in] obj a struct whose first element is a pointer to an AVClass.
[in] name name of the option to get.
[in] search_flags flags passed to av_opt_find2. I.e. if AV_OPT_SEARCH_CHILDREN is passed here, then the option may be found in a child of obj.
[out] out_val value of the option will be written here
Returns
>=0 on success, a negative error code otherwise
Function Documentation
av_opt_get()
int av_opt_get (void * obj, const char * name, int search_flags, uint8_t ** out_val)
Note
the returned string will be av_malloc()ed and must be av_free()ed by the caller
if AV_OPT_ALLOW_NULL is set in search_flags in av_opt_get, and the option has AV_OPT_TYPE_STRING or AV_OPT_TYPE_BINARY and is set to NULL, *out_val will be set to NULL instead of an allocated empty string.
Definition at line 753 of file opt.c.
Referenced by av_opencl_get_option(), av_opt_serialize(), av_probe_input_buffer2(), avcodec_get_subtitle_rect_class(), check_video_streams(), dump_video_streams(), ff_rtp_chain_mux_open(), mpjpeg_get_boundary(), parse_playlist(), pcm_read_header(), process_client(), save_avio_options(), show_stream(), test_copy_print_codec(), and update_options().
av_opt_get_int()
int av_opt_get_int (void * obj, const char * name, int search_flags, int64_t * out_val)
Definition at line 877 of file opt.c.
Referenced by av_opt_flag_is_set(), avcodec_get_subtitle_rect_class(), config_output(), ff_rtp_get_payload_type(), ff_spp_init_x86(), opus_decode_subpacket(), query_formats(), sws_getCachedContext(), and test_copy_print_codec().
av_opt_get_double()
int av_opt_get_double (void * obj, const char * name, int search_flags, double * out_val)
Definition at line 889 of file opt.c.
av_opt_get_q()
int av_opt_get_q (void * obj, const char * name, int search_flags, AVRational * out_val)
Definition at line 901 of file opt.c.
av_opt_get_image_size()
int av_opt_get_image_size (void * obj, const char * name, int search_flags, int * w_out, int * h_out)
Definition at line 917 of file opt.c.
av_opt_get_pixel_fmt()
int av_opt_get_pixel_fmt (void * obj, const char * name, int search_flags, enum AVPixelFormat * out_fmt)
Definition at line 969 of file opt.c.
av_opt_get_sample_fmt()
int av_opt_get_sample_fmt (void * obj, const char * name, int search_flags, enum AVSampleFormat * out_fmt)
Definition at line 974 of file opt.c.
Referenced by config_output(), and query_formats().
av_opt_get_video_rate()
int av_opt_get_video_rate (void * obj, const char * name, int search_flags, AVRational * out_val)
Definition at line 935 of file opt.c.
av_opt_get_channel_layout()
int av_opt_get_channel_layout (void * obj, const char * name, int search_flags, int64_t * ch_layout)
Definition at line 979 of file opt.c.
av_opt_get_dict_val()
int av_opt_get_dict_val (void * obj, const char * name, int search_flags, AVDictionary ** out_val)
Parameters
[out] out_val The returned dictionary is a copy of the actual value and must be freed with av_dict_free() by the caller
Definition at line 996 of file opt.c.
Referenced by read_frame_internal().