FFmpeg: Encoding
Encoding
libavcodec
Data Structures
struct RcOverride
Macros
#define AV_INPUT_BUFFER_MIN_SIZE 16384
minimum encoding buffer size Used to avoid some checks during header writing.
Enumerations
enum Motion_Est_ID {
ME_ZERO = 1, ME_FULL, ME_LOG, ME_PHODS,
ME_EPZS, ME_X1, ME_HEX, ME_UMH,
ME_TESA, ME_ITER =50
}
motion estimation type.
Functions
AVCodec * avcodec_find_encoder (enum AVCodecID id)
Find a registered encoder with a matching codec ID.
AVCodec * avcodec_find_encoder_by_name (const char *name)
Find a registered encoder with the specified name.
attribute_deprecated int avcodec_encode_audio2 (AVCodecContext *avctx, AVPacket *avpkt, const AVFrame *frame, int *got_packet_ptr)
Encode a frame of audio.
attribute_deprecated int avcodec_encode_video2 (AVCodecContext *avctx, AVPacket *avpkt, const AVFrame *frame, int *got_packet_ptr)
Encode a frame of video.
int avcodec_encode_subtitle (AVCodecContext *avctx, uint8_t *buf, int buf_size, const AVSubtitle *sub)
Detailed Description
Macro Definition Documentation
AV_INPUT_BUFFER_MIN_SIZE
#define AV_INPUT_BUFFER_MIN_SIZE 16384
minimum encoding buffer size Used to avoid some checks during header writing.
Definition at line 745 of file avcodec.h.
Referenced by encode_apng(), encode_frame(), encode_nals(), encode_picture_ls(), encode_png(), flashsv2_encode_frame(), gif_encode_frame(), ljpeg_encode_frame(), prores_encode_frame(), svq1_encode_frame(), and xvid_encode_frame().
Enumeration Type Documentation
Motion_Est_ID
enum Motion_Est_ID
motion estimation type.
Deprecated:
use codec private option instead
Enumerator
ME_ZERO
no search, that is use 0,0 vector whenever one is needed
ME_FULL
ME_LOG
ME_PHODS
ME_EPZS
enhanced predictive zonal search
ME_X1
reserved for experiments
ME_HEX
hexagon based search
ME_UMH
uneven multi-hexagon search
ME_TESA
transformed exhaustive search algorithm
ME_ITER
iterative search
Definition at line 765 of file avcodec.h.
Function Documentation
avcodec_find_encoder()
AVCodec* avcodec_find_encoder (enum AVCodecID id)
Find a registered encoder with a matching codec ID.
Parameters
id AVCodecID of the requested encoder
Returns
An encoder if one was found, NULL otherwise.
Examples:
decoding_encoding.c, muxing.c, transcode_aac.c, and transcoding.c.
Definition at line 3110 of file utils.c.
Referenced by add_stream(), audio_encode_example(), avcodec_get_name(), avcodec_open2(), choose_encoder(), compute_status(), config_input(), config_props(), estimate_best_b_count(), ffm2_read_header(), ffm_write_recommended_config(), ffserver_opt_preset(), ffserver_parse_config_stream(), filter_codec_opts(), find_codec_or_die(), main(), open_output_file(), print_stream_params(), read_ffserver_streams(), show_codecs(), and video_encode_example().
avcodec_find_encoder_by_name()
AVCodec* avcodec_find_encoder_by_name (const char * name)
Find a registered encoder with the specified name.
Parameters
name name of the requested encoder
Returns
An encoder if one was found, NULL otherwise.
Definition at line 3115 of file utils.c.
Referenced by ffserver_set_codec(), find_codec_or_die(), and show_help_codec().
avcodec_encode_audio2()
attribute_deprecated int avcodec_encode_audio2 (AVCodecContext * avctx, AVPacket * avpkt, const AVFrame * frame, int * got_packet_ptr)
Encode a frame of audio.
Takes input samples from frame and writes the next output packet, if available, to avpkt. The output packet does not necessarily contain data for the most recent frame, as encoders can delay, split, and combine input frames internally as needed.
Parameters
avctx codec context
avpkt output AVPacket. The user can supply an output buffer by setting avpkt->data and avpkt->size prior to calling the function, but if the size of the user-provided data is not large enough, encoding will fail. If avpkt->data and avpkt->size are set, avpkt->destruct must also be set. All other AVPacket fields will be reset by the encoder using av_init_packet(). If avpkt->data is NULL, the encoder will allocate it. The encoder will set avpkt->size to the size of the output packet.
If this function fails or produces no output, avpkt will be freed using av_packet_unref().
Parameters
[in] frame AVFrame containing the raw audio data to be encoded. May be NULL when flushing an encoder that has the AV_CODEC_CAP_DELAY capability set. If AV_CODEC_CAP_VARIABLE_FRAME_SIZE is set, then each frame can have any number of samples. If it is not set, frame->nb_samples must be equal to avctx->frame_size for all frames except the last. The final frame may be smaller than avctx->frame_size.
[out] got_packet_ptr This field is set to 1 by libavcodec if the output packet is non-empty, and to 0 if it is empty. If the function returns an error, the packet can be assumed to be invalid, and the value of got_packet_ptr is undefined and should not be used.
Returns
0 on success, negative error code on failure
Deprecated:
use avcodec_send_frame()/avcodec_receive_packet() instead
Examples:
decoding_encoding.c, muxing.c, transcode_aac.c, and transcoding.c.
Definition at line 1809 of file utils.c.
Referenced by audio_encode_example(), do_encode(), encode_audio_frame(), encode_write_frame(), run_test(), wrap(), and write_audio_frame().
avcodec_encode_video2()
attribute_deprecated int avcodec_encode_video2 (AVCodecContext * avctx, AVPacket * avpkt, const AVFrame * frame, int * got_packet_ptr)
Encode a frame of video.
Takes input raw video data from frame and writes the next output packet, if available, to avpkt. The output packet does not necessarily contain data for the most recent frame, as encoders can delay and reorder input frames internally as needed.
Parameters
avctx codec context
avpkt output AVPacket. The user can supply an output buffer by setting avpkt->data and avpkt->size prior to calling the function, but if the size of the user-provided data is not large enough, encoding will fail. All other AVPacket fields will be reset by the encoder using av_init_packet(). If avpkt->data is NULL, the encoder will allocate it. The encoder will set avpkt->size to the size of the output packet. The returned data (if any) belongs to the caller, he is responsible for freeing it.
If this function fails or produces no output, avpkt will be freed using av_packet_unref().
Parameters
[in] frame AVFrame containing the raw video data to be encoded. May be NULL when flushing an encoder that has the AV_CODEC_CAP_DELAY capability set.
[out] got_packet_ptr This field is set to 1 by libavcodec if the output packet is non-empty, and to 0 if it is empty. If the function returns an error, the packet can be assumed to be invalid, and the value of got_packet_ptr is undefined and should not be used.
Returns
0 on success, negative error code on failure
Deprecated:
use avcodec_send_frame()/avcodec_receive_packet() instead
Examples:
decoding_encoding.c, muxing.c, and transcoding.c.
Definition at line 1955 of file utils.c.
Referenced by do_encode(), encode_frame(), encode_write_frame(), filter(), filter_frame(), video_encode_example(), worker(), wrap(), and write_video_frame().
avcodec_encode_subtitle()
int avcodec_encode_subtitle (AVCodecContext * avctx, uint8_t * buf, int buf_size, const AVSubtitle * sub)
Definition at line 2040 of file utils.c.
Referenced by do_subtitle_out(), and wrap().