FFmpeg: Miscellaneous Functions
Miscellaneous Functions
libavutil » Memory Management
Other functions related to memory allocation.
Functions
static int av_size_mult (size_t a, size_t b, size_t *r)
Multiply two size_t values checking for overflow.
void av_max_alloc (size_t max)
Set the maximum size that may be allocated in one block.
Detailed Description
Other functions related to memory allocation.
Function Documentation
av_size_mult()
static int av_size_mult (size_t a, size_t b, size_t * r) inline static
Multiply two size_t values checking for overflow.
Parameters
[in] a,b Operands of multiplication
[out] r Pointer to the result of the operation
Returns
0 on success, AVERROR(EINVAL) on overflow
Definition at line 665 of file mem.h.
Referenced by av_realloc_f(), and ogg_new_stream().
av_max_alloc()
void av_max_alloc (size_t max)
Set the maximum size that may be allocated in one block.
The value specified with this function is effective for all libavutil's heap management functions.
By default, the max value is defined as INT_MAX.
Parameters
max Value to be set as the new maximum size
Warning
Exercise extreme caution when using this function. Don't touch this if you do not understand the full consequence of doing so.
Definition at line 73 of file mem.c.
Referenced by av_size_mult(), and opt_max_alloc().