FFmpeg: String Manipulation
String Manipulation
libavutil
Macros
#define AV_ESCAPE_FLAG_WHITESPACE (1 << 0)
Consider spaces special and escape them even in the middle of the string.
#define AV_ESCAPE_FLAG_STRICT (1 << 1)
Escape only specified special characters.
#define AV_UTF8_FLAG_ACCEPT_INVALID_BIG_CODES 1
accept codepoints over 0x10FFFF
#define AV_UTF8_FLAG_ACCEPT_NON_CHARACTERS 2
accept non-characters - 0xFFFE and 0xFFFF
#define AV_UTF8_FLAG_ACCEPT_SURROGATES 4
accept UTF-16 surrogates codes
#define AV_UTF8_FLAG_EXCLUDE_XML_INVALID_CONTROL_CODES 8
exclude control codes not accepted by XML
#define AV_UTF8_FLAG_ACCEPT_ALL AV_UTF8_FLAG_ACCEPT_INVALID_BIG_CODES|AV_UTF8_FLAG_ACCEPT_NON_CHARACTERS|AV_UTF8_FLAG_ACCEPT_SURROGATES
Enumerations
enum AVEscapeMode { AV_ESCAPE_MODE_AUTO, AV_ESCAPE_MODE_BACKSLASH, AV_ESCAPE_MODE_QUOTE }
Functions
int av_strstart (const char *str, const char *pfx, const char **ptr)
Return non-zero if pfx is a prefix of str.
int av_stristart (const char *str, const char *pfx, const char **ptr)
Return non-zero if pfx is a prefix of str independent of case.
char * av_stristr (const char *haystack, const char *needle)
Locate the first case-independent occurrence in the string haystack of the string needle.
char * av_strnstr (const char *haystack, const char *needle, size_t hay_length)
Locate the first occurrence of the string needle in the string haystack where not more than hay_length characters are searched.
size_t av_strlcpy (char *dst, const char *src, size_t size)
Copy the string src to dst, but no more than size - 1 bytes, and null-terminate dst.
size_t av_strlcat (char *dst, const char *src, size_t size)
Append the string src to the string dst, but to a total length of no more than size - 1 bytes, and null-terminate dst.
size_t av_strlcatf (char *dst, size_t size, const char *fmt,...) av_printf_format(3
Append output to a string, according to a format.
size_t static size_t av_strnlen (const char *s, size_t len)
Get the count of continuous non zero chars starting from the beginning.
char * av_asprintf (const char *fmt,...) av_printf_format(1
Print arguments following specified format into a large enough auto allocated buffer.
char char * av_d2str (double d)
Convert a number to an av_malloced string.
char * av_get_token (const char **buf, const char *term)
Unescape the given string until a non escaped terminating char, and return the token corresponding to the unescaped string.
char * av_strtok (char *s, const char *delim, char **saveptr)
Split the string into several tokens which can be accessed by successive calls to av_strtok().
static av_const int av_isdigit (int c)
Locale-independent conversion of ASCII isdigit.
static av_const int av_isgraph (int c)
Locale-independent conversion of ASCII isgraph.
static av_const int av_isspace (int c)
Locale-independent conversion of ASCII isspace.
static av_const int av_toupper (int c)
Locale-independent conversion of ASCII characters to uppercase.
static av_const int av_tolower (int c)
Locale-independent conversion of ASCII characters to lowercase.
static av_const int av_isxdigit (int c)
Locale-independent conversion of ASCII isxdigit.
int av_strcasecmp (const char *a, const char *b)
Locale-independent case-insensitive compare.
int av_strncasecmp (const char *a, const char *b, size_t n)
Locale-independent case-insensitive compare.
const char * av_basename (const char *path)
Thread safe basename.
const char * av_dirname (char *path)
Thread safe dirname.
int av_match_name (const char *name, const char *names)
Match instances of a name in a comma-separated list of names.
char * av_append_path_component (const char *path, const char *component)
Append path component to the existing path.
av_warn_unused_result int av_escape (char **dst, const char *src, const char *special_chars, enum AVEscapeMode mode, int flags)
Escape string in src, and put the escaped string in an allocated string in *dst, which must be freed with av_free().
av_warn_unused_result int av_utf8_decode (int32_t *codep, const uint8_t **bufp, const uint8_t *buf_end, unsigned int flags)
Read and decode a single UTF-8 code point (character) from the buffer in *buf, and update *buf to point to the next byte to decode.
int av_match_list (const char *name, const char *list, char separator)
Check if a name is in a list.
Detailed Description
Macro Definition Documentation
AV_ESCAPE_FLAG_WHITESPACE
#define AV_ESCAPE_FLAG_WHITESPACE (1 << 0)
Consider spaces special and escape them even in the middle of the string.
This is equivalent to adding the whitespace characters to the special characters lists, except it is guaranteed to use the exact same list of whitespace characters as the rest of libavutil.
Definition at line 322 of file avstring.h.
Referenced by av_bprint_escape(), main(), and segment_list_print_entry().
AV_ESCAPE_FLAG_STRICT
#define AV_ESCAPE_FLAG_STRICT (1 << 1)
Escape only specified special characters.
Without this flag, escape also any characters that may be considered special by av_get_token(), such as the single quote.
Definition at line 329 of file avstring.h.
Referenced by av_bprint_escape(), and main().
AV_UTF8_FLAG_ACCEPT_INVALID_BIG_CODES
#define AV_UTF8_FLAG_ACCEPT_INVALID_BIG_CODES 1
accept codepoints over 0x10FFFF
Definition at line 351 of file avstring.h.
Referenced by av_utf8_decode().
AV_UTF8_FLAG_ACCEPT_NON_CHARACTERS
#define AV_UTF8_FLAG_ACCEPT_NON_CHARACTERS 2
accept non-characters - 0xFFFE and 0xFFFF
Definition at line 352 of file avstring.h.
Referenced by av_utf8_decode().
AV_UTF8_FLAG_ACCEPT_SURROGATES
#define AV_UTF8_FLAG_ACCEPT_SURROGATES 4
accept UTF-16 surrogates codes
Definition at line 353 of file avstring.h.
Referenced by av_utf8_decode().
AV_UTF8_FLAG_EXCLUDE_XML_INVALID_CONTROL_CODES
#define AV_UTF8_FLAG_EXCLUDE_XML_INVALID_CONTROL_CODES 8
exclude control codes not accepted by XML
Definition at line 354 of file avstring.h.
Referenced by av_utf8_decode(), and main().
AV_UTF8_FLAG_ACCEPT_ALL
#define AV_UTF8_FLAG_ACCEPT_ALL AV_UTF8_FLAG_ACCEPT_INVALID_BIG_CODES|AV_UTF8_FLAG_ACCEPT_NON_CHARACTERS|AV_UTF8_FLAG_ACCEPT_SURROGATES
Definition at line 356 of file avstring.h.
Enumeration Type Documentation
AVEscapeMode
enum AVEscapeMode
Enumerator
AV_ESCAPE_MODE_AUTO
Use auto-selected escaping mode.
AV_ESCAPE_MODE_BACKSLASH
Use backslash escaping.
AV_ESCAPE_MODE_QUOTE
Use single-quote escaping.
Definition at line 308 of file avstring.h.
Function Documentation
av_strstart()
int av_strstart (const char * str, const char * pfx, const char ** ptr)
Return non-zero if pfx is a prefix of str.
If it is, *ptr is set to the address of the first character in str after the prefix.
Parameters
str input string
pfx prefix to test
ptr updated if the prefix is matched inside str
Returns
non-zero if the prefix matches, zero otherwise
Definition at line 34 of file avstring.c.
Referenced by amr_parse_sdp_line(), asfrtp_parse_sdp_line(), async_open(), bluray_open(), cache_open(), concat_open(), crypto_open2(), dash_read_tmpl_id(), data_open(), dv_parse_sdp_line(), ff_make_absolute_url(), ff_real_parse_sdp_a_line(), ff_rtsp_open_transport_ctx(), ff_tls_open_underlying(), ff_wms_parse_sdp_a_line(), ffurl_alloc(), file_check(), file_delete(), file_move(), find_component(), get_sockaddr(), hevc_parse_sdp_line(), hls_open(), http_open_cnx_internal(), ilbc_parse_sdp_line(), latm_parse_sdp_line(), main(), md5_close(), open_output_file(), open_url(), parse_command_line(), parse_h264_sdp_line(), parse_multipart_header(), parse_playlist(), parse_sdp_line(), rdt_parse_sdp_line(), rtsp_probe(), sap_probe(), subfile_open(), tee_open(), unix_open(), v4l2_read_probe(), and xiph_parse_sdp_line().
av_stristart()
int av_stristart (const char * str, const char * pfx, const char ** ptr)
Return non-zero if pfx is a prefix of str independent of case.
If it is, *ptr is set to the address of the first character in str after the prefix.
Parameters
str input string
pfx prefix to test
ptr updated if the prefix is matched inside str
Returns
non-zero if the prefix matches, zero otherwise
Definition at line 45 of file avstring.c.
Referenced by av_stristr(), ff_http_auth_handle_header(), ff_rtsp_open_transport_ctx(), has_header(), main(), mpjpeg_get_boundary(), and rtsp_parse_range_npt().
av_stristr()
char* av_stristr (const char * haystack, const char * needle)
Locate the first case-independent occurrence in the string haystack of the string needle.
A zero-length string needle is considered to match at the start of haystack.
This function is a case-insensitive version of the standard strstr().
Parameters
haystack string to search in
needle string to search for
Returns
pointer to the located match within haystack or a null pointer if no match
Definition at line 56 of file avstring.c.
Referenced by av_opencl_compile(), ftp_connect_control_connection(), ftp_has_feature(), has_header(), http_start_receive_data(), mov_parse_uuid_spherical(), mov_read_uuid(), parse_filename(), run_implementation(), and sami_paragraph_to_ass().
av_strnstr()
char* av_strnstr (const char * haystack, const char * needle, size_t hay_length)
Locate the first occurrence of the string needle in the string haystack where not more than hay_length characters are searched.
A zero-length string needle is considered to match at the start of haystack.
This function is a length-limited version of the standard strstr().
Parameters
haystack string to search in
needle string to search for
hay_length length of string to search in
Returns
pointer to the located match within haystack or a null pointer if no match
Definition at line 69 of file avstring.c.
av_strlcpy()
size_t av_strlcpy (char * dst, const char * src, size_t size)
Copy the string src to dst, but no more than size - 1 bytes, and null-terminate dst.
This function is the same as BSD strlcpy().
Parameters
dst destination buffer
src source string
size size of destination buffer
Returns
the length of src
Warning
since the return value is the length of src, src absolutely must be a properly 0-terminated string, otherwise this will read beyond the end of the buffer and possibly crash.
Definition at line 83 of file avstring.c.
Referenced by add_fragment(), add_segment(), amf_parse_object(), asf_read_language_list(), ass_encode_frame(), av_append_path_component(), av_parse_color(), av_pix_fmt_swap_endianness(), av_strerror(), av_strlcat(), av_url_split(), avformat_alloc_output_context2(), avformat_open_input(), choose_qop(), compute_real_filename(), compute_status(), concat_open(), ctime1(), dash_fill_tmpl_params(), dash_init(), dash_read_tmpl_id(), dprint_options(), dump_metadata(), ff_amf_get_field_value(), ff_htmlmarkup_to_ass(), ff_img_read_header(), ff_img_read_packet(), ff_make_absolute_url(), ff_rtsp_open_transport_ctx(), ff_rtsp_setup_output_streams(), find_component(), find_compressor(), get_chunk_filename(), get_preset_file(), get_sockaddr(), handle_connect_error(), hls_append_segment(), hls_delete_old_segments(), hls_open(), hls_start(), hls_write_header(), http_connect(), http_parse_request(), id3v1_set_string(), id3v2_3_metadata_split_date(), libssh_connect(), main(), matroska_convert_tag(), merge_date(), mmsh_open_internal(), omx_component_init(), open_input(), open_output_file(), opt_channel_layout(), opt_default(), opt_opencl_bench(), opt_preset(), opt_streamid(), parse_command(), parse_command_line(), parse_filename(), parse_playlist(), parse_sws_flags(), pp_get_mode_by_name_and_quality(), rtmp_open(), rtp_new_connection(), rtp_open(), rtsp_parse_request(), sap_read_header(), sap_write_header(), set_encoder_id(), show_help_options(), to_integer(), udp_open(), unix_open(), url_find_protocol(), write_header(), and write_packet().
av_strlcat()
size_t av_strlcat (char * dst, const char * src, size_t size)
Append the string src to the string dst, but to a total length of no more than size - 1 bytes, and null-terminate dst.
This function is similar to BSD strlcat(), but differs when size <= strlen(dst).
Parameters
dst destination buffer
src source string
size size of destination buffer
Returns
the total length of src and dst
Warning
since the return value use the length of src and dst, these absolutely must be a properly 0-terminated strings, otherwise this will read beyond the end of the buffer and possibly crash.
Definition at line 93 of file avstring.c.
Referenced by av_dict_set(), av_printf_format(), avcodec_string(), clean_html(), ff_http_auth_create_response(), ff_make_absolute_url(), ff_rtsp_open_transport_ctx(), ff_rtsp_setup_input_streams(), ff_url_join(), ffm_append_recommended_configuration(), get_sockaddr(), hls_delete_old_segments(), hls_write_header(), matroska_convert_tag(), mmsh_open_internal(), mov_open_dref(), mov_rewrite_dvd_sub_extradata(), opt_channel_layout(), rtmp_open(), rtp_new_connection(), rtsp_read_packet(), rtsp_send_reply(), set_best_codebook(), set_encoder_id(), and show_help_options().
av_strlcatf()
size_t av_strlcatf (char * dst, size_t size, const char * fmt, ...)
Append output to a string, according to a format.
Never write out of the destination buffer, and always put a terminating 0 within the buffer.
Parameters
dst destination buffer (string to which the output is appended)
size total size of the destination buffer
fmt printf-compatible format string, specifying how the following parameters are used
Returns
the length of the string that would have been generated if enough space had been available
av_strnlen()
size_t static size_t av_strnlen (const char * s, size_t len) inline static
Get the count of continuous non zero chars starting from the beginning.
Parameters
len maximum number of characters to check in the string, that is the maximum value which is returned by the function
Definition at line 140 of file avstring.h.
Referenced by print_file(), and wc3_read_packet().
av_asprintf()
char* av_asprintf (const char * fmt, ...)
Print arguments following specified format into a large enough auto allocated buffer.
It is similar to GNU asprintf().
Parameters
fmt printf-compatible format string, specifying how the following parameters are used.
Returns
the allocated string
Note
You have to free the string yourself with av_free().
Referenced by av_strnlen().
av_d2str()
char char* av_d2str (double d)
Convert a number to an av_malloced string.
Definition at line 139 of file avstring.c.
Referenced by av_strnlen().
av_get_token()
char* av_get_token (const char ** buf, const char * term)
Unescape the given string until a non escaped terminating char, and return the token corresponding to the unescaped string.
The normal \ and ' escaping is supported. Leading and trailing whitespaces are removed, unless they are escaped with '\' or are enclosed between ''.
Parameters
buf the buffer to parse, buf will be updated to point to the terminating char
term a 0-terminated list of terminating chars
Returns
the malloced unescaped string, which must be av_freed by the user, NULL in case of allocation failure
Definition at line 149 of file avstring.c.
Referenced by av_opt_get_key_value(), av_strnlen(), concat_read_header(), dilate_init(), expand_function(), main(), new_output_stream(), open_output_file(), opt_map(), opt_show_entries(), parse_command(), parse_filter(), parse_interval(), parse_key_value_pair(), parse_link_name(), qsv_load_plugins(), rtp_open(), set_params(), tee_open(), and tee_write_header().
av_strtok()
char* av_strtok (char * s, const char * delim, char ** saveptr)
Split the string into several tokens which can be accessed by successive calls to av_strtok().
A token is defined as a sequence of characters not belonging to the set specified in delim.
On the first call to av_strtok(), s should point to the string to parse, and the value of saveptr is ignored. In subsequent calls, s should be NULL, and saveptr should be unchanged since the previous call.
This function is similar to strtok_r() defined in POSIX.1.
Parameters
s the string to parse, may be NULL
delim 0-terminated list of token delimiters, must be non-NULL
saveptr user-provided pointer which points to stored information necessary for av_strtok() to continue scanning the same string. saveptr is updated to point to the next character after the first delimiter found, or to NULL if the string was terminated
Returns
the found token, or NULL when no token is found
Definition at line 184 of file avstring.c.
Referenced by av_bsf_list_parse_str(), av_strnlen(), bsf_parse_single(), config_input(), config_output(), draw_curves(), fill_items(), frei0r_init(), ftp_connect(), ftp_parse_entry_mlsd(), ftp_passive_mode(), get_cookies(), init(), libssh_connect(), main(), movie_common_init(), new_output_stream(), new_rendition(), open_slave(), opt_preset(), parse_channel_expressions(), parse_device_name(), parse_frames(), parse_interval(), parse_speaker_pos(), parse_times(), plot_freqs(), pp_get_mode_by_name_and_quality(), and sami_paragraph_to_ass().
av_isdigit()
static av_const int av_isdigit (int c) inline static
Locale-independent conversion of ASCII isdigit.
Definition at line 206 of file avstring.h.
Referenced by av_get_frame_filename2(), av_isxdigit(), av_parse_time(), channelmap_init(), cmp_func_names(), dash_read_tmpl_id(), date_get_num(), init(), and parse_value().
av_isgraph()
static av_const int av_isgraph (int c) inline static
Locale-independent conversion of ASCII isgraph.
Definition at line 214 of file avstring.h.
Referenced by init_pattern_from_file(), init_pattern_from_string(), and read_shape_from_file().
av_isspace()
static av_const int av_isspace (int c) inline static
Locale-independent conversion of ASCII isspace.
Definition at line 222 of file avstring.h.
Referenced by av_expr_parse(), av_parse_time(), av_small_strptime(), avpriv_strtod(), choose_qop(), extract_rates(), ff_parse_key_value(), ff_smil_get_attr_ptr(), ffserver_get_arg(), ffserver_parse_ffconfig(), get_word(), http_parse_request(), mpjpeg_get_boundary(), parse_dynamic_acl(), parse_palette(), process_line(), read_chomp_line(), rt_event_to_ass(), rtmp_http_open(), sami_paragraph_to_ass(), skip_line(), split_tag_value(), and trim_right().
av_toupper()
static av_const int av_toupper (int c) inline static
Locale-independent conversion of ASCII characters to uppercase.
Definition at line 231 of file avstring.h.
Referenced by av_dict_get(), av_stristart(), avpriv_toupper4(), ff_hex_to_data(), ff_vorbis_comment(), ffserver_parse_config_feed(), get_jss_cmd(), jacosub_to_ass(), read_yesno(), and upcase_string().
av_tolower()
static av_const int av_tolower (int c) inline static
Locale-independent conversion of ASCII characters to lowercase.
Definition at line 241 of file avstring.h.
Referenced by av_isxdigit(), av_strcasecmp(), av_strncasecmp(), ff_urldecode(), ffserver_parse_config_stream(), microdvd_init(), and subviewer_read_header().
av_isxdigit()
static av_const int av_isxdigit (int c) inline static
Locale-independent conversion of ASCII isxdigit.
Definition at line 251 of file avstring.h.
Referenced by ff_urldecode(), and xbm_decode_frame().
av_strcasecmp()
int av_strcasecmp (const char * a, const char * b)
Locale-independent case-insensitive compare.
Note
This means only ASCII-range characters are case-insensitive
Definition at line 213 of file avstring.c.
Referenced by av_hash_alloc(), av_isxdigit(), av_parse_color(), av_parse_time(), av_probe_input_buffer2(), avi_metadata_creation_time(), color_table_compare(), decode_info_header(), ff_AMediaCodecList_getCodecNameByType(), ff_http_auth_handle_header(), ff_id3v2_write_apic(), ff_img_read_header(), ff_metadata_conv(), ff_rtp_codec_id(), ff_rtp_handler_find_by_name(), ff_rtsp_open_transport_ctx(), ffserver_parse_acl_row(), ffserver_parse_config_feed(), ffserver_parse_config_global(), ffserver_parse_config_redirect(), ffserver_parse_config_stream(), ffserver_parse_ffconfig(), filter_frame(), find_segment_by_filename(), ftp_parse_entry_mlsd(), get_cookies(), hls_window(), id3v1_create_tag(), id3v2_3_metadata_split_date(), mkv_check_tag_name(), nist_read_header(), opt_vsync(), parse_dynamic_acl(), parse_fmtp(), parse_multipart_header(), parse_slave_failure_policy_option(), process_line(), str2id(), v4l2_set_parameters(), and write_header().
av_strncasecmp()
int av_strncasecmp (const char * a, const char * b, size_t n)
Locale-independent case-insensitive compare.
Note
This means only ASCII-range characters are case-insensitive
Definition at line 223 of file avstring.c.
Referenced by av_isxdigit(), av_match_name(), avpriv_strtod(), data_open(), extract_rates(), ff_rtsp_open_transport_ctx(), ff_smil_get_attr_ptr(), get_cookies(), http_parse_request(), jacosub_read_header(), main(), nist_read_header(), parse_content_encoding(), process_line(), read_apic(), realtext_probe(), realtext_read_header(), rt_event_to_ass(), sami_paragraph_to_ass(), and sami_read_header().
av_basename()
const char* av_basename (const char * path)
Thread safe basename.
Parameters
path the path, on DOS both \ and / are considered separators.
Returns
pointer to the basename substring.
Definition at line 234 of file avstring.c.
Referenced by av_isxdigit(), hls_append_segment(), hls_delete_old_segments(), main(), set_segment_filename(), and write_manifest().
av_dirname()
const char* av_dirname (char * path)
Thread safe dirname.
Parameters
path the path, on DOS both \ and / are considered separators.
Returns
the path with the separator replaced by the string terminator or ".".
Note
the function may change the input string.
Definition at line 251 of file avstring.c.
Referenced by av_isxdigit(), hls_start(), and main().
av_match_name()
int av_match_name (const char * name, const char * names)
Match instances of a name in a comma-separated list of names.
List entries are checked from the start to the end of the names list, the first match ends further processing. If an entry prefixed with '-' matches, then 0 is returned. The "ALL" list entry is considered to match all names.
Parameters
name Name to look for.
names List of names.
Returns
1 on match, 0 otherwise.
Definition at line 320 of file avstring.c.
Referenced by av_find_input_format(), av_guess_codec(), av_guess_format(), av_isxdigit(), av_match_ext(), av_probe_input_format3(), avformat_transfer_internal_stream_timing_info(), ffurl_get_protocols(), get_pix_fmt_internal(), get_rotation(), parse_slave_fifo_options(), and set_string_bool().
av_append_path_component()
char* av_append_path_component (const char * path, const char * component)
Append path component to the existing path.
Path separator '/' is placed between when needed. Resulting string have to be freed with av_free().
Parameters
path base path
component component to be appended
Returns
new path or NULL on error.
Definition at line 272 of file avstring.c.
Referenced by av_isxdigit(), file_move(), ftp_connect(), and libsmbc_read_dir().
av_escape()
av_warn_unused_result int av_escape (char ** dst, const char * src, const char * special_chars, enum AVEscapeMode mode, int flags)
Escape string in src, and put the escaped string in an allocated string in *dst, which must be freed with av_free().
Parameters
dst pointer where an allocated string is put
src string to escape, must be non-NULL
special_chars string containing the special characters which need to be escaped, can be NULL
mode escape mode to employ, see AV_ESCAPE_MODE_* macros. Any unknown value for mode will be considered equivalent to AV_ESCAPE_MODE_BACKSLASH, but this behaviour can change without notice.
flags flags which control how to escape, see AV_ESCAPE_FLAG_ macros
Returns
the length of the allocated string, or a negative error code in case of error
See also
av_bprint_escape()
Definition at line 303 of file avstring.c.
Referenced by main(), and segment_list_print_entry().
av_utf8_decode()
av_warn_unused_result int av_utf8_decode (int32_t * codep, const uint8_t ** bufp, const uint8_t * buf_end, unsigned int flags)
Read and decode a single UTF-8 code point (character) from the buffer in *buf, and update *buf to point to the next byte to decode.
In case of an invalid byte sequence, the pointer will be updated to the next byte after the invalid sequence and the function will return an error code.
Depending on the specified flags, the function will also fail in case the decoded code point does not belong to a valid range.
Note
For speed-relevant code a carefully implemented use of GET_UTF8() may be preferred.
Parameters
codep pointer used to return the parsed code in case of success. The value in *codep is set even in case the range check fails.
bufp pointer to the address the first byte of the sequence to decode, updated by the function to point to the byte next after the decoded sequence
buf_end pointer to the end of the buffer, points to the next byte past the last in the buffer. This is used to avoid buffer overreads (in case of an unfinished UTF-8 sequence towards the end of the buffer).
flags a collection of AV_UTF8_FLAG_* flags
Returns
>= 0 in case a sequence was successfully read, a negative value in case of invalid sequence
Definition at line 343 of file avstring.c.
Referenced by main(), validate_string(), and writer_open().
av_match_list()
int av_match_list (const char * name, const char * list, char separator)
Check if a name is in a list.
Returns
0 if not found, or the 1 based index where it has been found in the list.
Definition at line 419 of file avstring.c.
Referenced by av_demuxer_open(), avcodec_open2(), avformat_open_input(), and ffurl_connect().