FFmpeg: VDA
VDA
libavcodec » Codecs » Hardware Accelerators bridge
Files
file vda.h
Public libavcodec VDA header.
Data Structures
struct vda_context
This structure is used to provide the necessary configurations and data to the VDA FFmpeg HWAccel implementation.
struct AVVDAContext
This struct holds all the information that needs to be passed between the caller and libavcodec for initializing VDA decoding.
Functions
int ff_vda_create_decoder (struct vda_context *vda_ctx, uint8_t *extradata, int extradata_size)
Create the video decoder.
int ff_vda_destroy_decoder (struct vda_context *vda_ctx)
Destroy the video decoder.
AVVDAContext * av_vda_alloc_context (void)
Allocate and initialize a VDA context.
int av_vda_default_init (AVCodecContext *avctx)
This is a convenience function that creates and sets up the VDA context using an internal implementation.
int av_vda_default_init2 (AVCodecContext *avctx, AVVDAContext *vdactx)
This is a convenience function that creates and sets up the VDA context using an internal implementation.
void av_vda_default_free (AVCodecContext *avctx)
This function must be called to free the VDA context initialized with av_vda_default_init().
Detailed Description
Function Documentation
ff_vda_create_decoder()
int ff_vda_create_decoder (struct vda_context * vda_ctx, uint8_t * extradata, int extradata_size)
Create the video decoder.
Definition at line 164 of file vda_h264.c.
Referenced by vdadec_init().
ff_vda_destroy_decoder()
int ff_vda_destroy_decoder (struct vda_context * vda_ctx)
Destroy the video decoder.
Definition at line 251 of file vda_h264.c.
Referenced by vdadec_close().
av_vda_alloc_context()
AVVDAContext* av_vda_alloc_context (void)
Allocate and initialize a VDA context.
This function should be called from the get_format() callback when the caller selects the AV_PIX_FMT_VDA format. The caller must then create the decoder object (using the output callback provided by libavcodec) that will be used for VDA-accelerated decoding.
When decoding with VDA is finished, the caller must destroy the decoder object and free the VDA context using av_free().
Returns
the newly allocated context or NULL on failure
Definition at line 66 of file vda.c.
Referenced by videotoolbox_init().
av_vda_default_init()
int av_vda_default_init (AVCodecContext * avctx)
This is a convenience function that creates and sets up the VDA context using an internal implementation.
Parameters
avctx the corresponding codec context
Returns
>= 0 on success, a negative AVERROR code on failure
Definition at line 71 of file vda.c.
Referenced by videotoolbox_init().
av_vda_default_init2()
int av_vda_default_init2 (AVCodecContext * avctx, AVVDAContext * vdactx)
This is a convenience function that creates and sets up the VDA context using an internal implementation.
Parameters
avctx the corresponding codec context
vdactx the VDA context to use
Returns
>= 0 on success, a negative AVERROR code on failure
Definition at line 76 of file vda.c.
Referenced by videotoolbox_init().
av_vda_default_free()
void av_vda_default_free (AVCodecContext * avctx)
This function must be called to free the VDA context initialized with av_vda_default_init().
Parameters
avctx the corresponding codec context
Definition at line 81 of file vda.c.
Referenced by videotoolbox_uninit().