FFmpeg: Buffer sink API
Buffer sink API
libavfilter
Files
file buffersink.h
memory buffer sink API for audio and video
Data Structures
struct AVBufferSinkParams
Struct to use for initializing a buffersink context.
struct AVABufferSinkParams
Struct to use for initializing an abuffersink context.
Macros
#define AV_BUFFERSINK_FLAG_PEEK 1
Tell av_buffersink_get_buffer_ref() to read video/samples buffer reference, but not remove it from the buffer.
#define AV_BUFFERSINK_FLAG_NO_REQUEST 2
Tell av_buffersink_get_buffer_ref() not to request a frame from its input.
Functions
int av_buffersink_get_frame_flags (AVFilterContext *ctx, AVFrame *frame, int flags)
Get a frame with filtered data from sink and put it in frame.
AVBufferSinkParams * av_buffersink_params_alloc (void)
Create an AVBufferSinkParams structure.
AVABufferSinkParams * av_abuffersink_params_alloc (void)
Create an AVABufferSinkParams structure.
void av_buffersink_set_frame_size (AVFilterContext *ctx, unsigned frame_size)
Set the frame size for an audio buffer sink.
AVRational av_buffersink_get_frame_rate (AVFilterContext *ctx)
Get the frame rate of the input.
int av_buffersink_get_frame (AVFilterContext *ctx, AVFrame *frame)
Get a frame with filtered data from sink and put it in frame.
int av_buffersink_get_samples (AVFilterContext *ctx, AVFrame *frame, int nb_samples)
Same as av_buffersink_get_frame(), but with the ability to specify the number of samples read.
Detailed Description
Macro Definition Documentation
AV_BUFFERSINK_FLAG_PEEK
#define AV_BUFFERSINK_FLAG_PEEK 1
Tell av_buffersink_get_buffer_ref() to read video/samples buffer reference, but not remove it from the buffer.
This is useful if you need only to read a video/samples buffer, without to fetch it.
Definition at line 53 of file buffersink.h.
Referenced by av_buffersink_get_frame_flags(), and lavfi_read_packet().
AV_BUFFERSINK_FLAG_NO_REQUEST
#define AV_BUFFERSINK_FLAG_NO_REQUEST 2
Tell av_buffersink_get_buffer_ref() not to request a frame from its input.
If a frame is already buffered, it is read (and removed from the buffer), but if no frame is present, return AVERROR(EAGAIN).
Definition at line 60 of file buffersink.h.
Referenced by av_buffersink_get_frame_flags(), main(), and reap_filters().
Function Documentation
av_buffersink_get_frame_flags()
int av_buffersink_get_frame_flags (AVFilterContext * ctx, AVFrame * frame, int flags)
Get a frame with filtered data from sink and put it in frame.
Parameters
ctx pointer to a buffersink or abuffersink filter context.
frame pointer to an allocated frame that will be filled with data. The data must be freed using av_frame_unref() / av_frame_free()
flags a combination of AV_BUFFERSINK_FLAG_* flags
Returns
>= 0 in for success, a negative AVERROR code for failure.
Definition at line 131 of file buffersink.c.
Referenced by audio_thread(), av_buffersink_get_frame(), av_buffersink_get_samples(), lavfi_read_packet(), main(), reap_filters(), and video_thread().
av_buffersink_params_alloc()
AVBufferSinkParams* av_buffersink_params_alloc (void)
Create an AVBufferSinkParams structure.
Must be freed with av_free().
Definition at line 240 of file buffersink.c.
av_abuffersink_params_alloc()
AVABufferSinkParams* av_abuffersink_params_alloc (void)
Create an AVABufferSinkParams structure.
Must be freed with av_free().
Definition at line 251 of file buffersink.c.
av_buffersink_set_frame_size()
void av_buffersink_set_frame_size (AVFilterContext * ctx, unsigned frame_size)
Set the frame size for an audio buffer sink.
All calls to av_buffersink_get_buffer_ref will return a buffer with exactly the specified number of samples, or AVERROR(EAGAIN) if there is not enough. The last buffer at EOF will be padded with 0.
Definition at line 274 of file buffersink.c.
Referenced by configure_filtergraph(), and init_output_stream().
av_buffersink_get_frame_rate()
AVRational av_buffersink_get_frame_rate (AVFilterContext * ctx)
Get the frame rate of the input.
Definition at line 282 of file buffersink.c.
Referenced by init_output_stream_encode(), and main().
av_buffersink_get_frame()
int av_buffersink_get_frame (AVFilterContext * ctx, AVFrame * frame)
Get a frame with filtered data from sink and put it in frame.
Parameters
ctx pointer to a context of a buffersink or abuffersink AVFilter.
frame pointer to an allocated frame that will be filled with data. The data must be freed using av_frame_unref() / av_frame_free()
Returns
>= 0 if a frame was successfully returned.
AVERROR(EAGAIN) if no frames are available at this point; more input frames must be added to the filtergraph to get more output.
AVERROR_EOF if there will be no more output frames on this sink.
A different negative AVERROR code in other failure cases.
Definition at line 126 of file buffersink.c.
Referenced by filter_encode_write_frame(), and main().
av_buffersink_get_samples()
int av_buffersink_get_samples (AVFilterContext * ctx, AVFrame * frame, int nb_samples)
Same as av_buffersink_get_frame(), but with the ability to specify the number of samples read.
This function is less efficient than av_buffersink_get_frame(), because it copies the data around.
Parameters
ctx pointer to a context of the abuffersink AVFilter.
frame pointer to an allocated frame that will be filled with data. The data must be freed using av_frame_unref() / av_frame_free() frame will contain exactly nb_samples audio samples, except at the end of stream, when it can contain less than nb_samples.
Returns
The return codes have the same meaning as for av_buffersink_get_samples().
Warning
do not mix this function with av_buffersink_get_frame(). Use only one or the other with a single sink, not both.
Definition at line 196 of file buffersink.c.