FFmpeg: VAAPI_Decoding
VAAPI_Decoding
Data Structures
struct FFVAContext
Functions
static void destroy_buffers (VADisplay display, VABufferID *buffers, unsigned int n_buffers)
int ff_vaapi_context_init (AVCodecContext *avctx)
Common AVHWAccel.init() implementation.
int ff_vaapi_context_fini (AVCodecContext *avctx)
Common AVHWAccel.uninit() implementation.
int ff_vaapi_render_picture (FFVAContext *vactx, VASurfaceID surface)
int ff_vaapi_commit_slices (FFVAContext *vactx)
static void * alloc_buffer (FFVAContext *vactx, int type, unsigned int size, uint32_t *buf_id)
void * ff_vaapi_alloc_pic_param (FFVAContext *vactx, unsigned int size)
Allocate a new picture parameter buffer.
void * ff_vaapi_alloc_iq_matrix (FFVAContext *vactx, unsigned int size)
Allocate a new IQ matrix buffer.
uint8_t * ff_vaapi_alloc_bitplane (FFVAContext *vactx, uint32_t size)
Allocate a new bit-plane buffer.
VASliceParameterBufferBase * ff_vaapi_alloc_slice (FFVAContext *vactx, const uint8_t *buffer, uint32_t size)
Allocate a new slice descriptor for the input slice.
void ff_vaapi_common_end_frame (AVCodecContext *avctx)
Common AVHWAccel.end_frame() implementation.
static FFVAContext * ff_vaapi_get_context (AVCodecContext *avctx)
Extract vaapi_context from an AVCodecContext.
static VASurfaceID ff_vaapi_get_surface_id (AVFrame *pic)
Extract VASurfaceID from an AVFrame.
int ff_vaapi_mpeg_end_frame (AVCodecContext *avctx)
Detailed Description
Function Documentation
destroy_buffers()
static void destroy_buffers (VADisplay display, VABufferID * buffers, unsigned int n_buffers) static
Definition at line 34 of file vaapi.c.
Referenced by ff_vaapi_common_end_frame().
ff_vaapi_context_init()
int ff_vaapi_context_init (AVCodecContext * avctx)
Common AVHWAccel.init() implementation.
Definition at line 45 of file vaapi.c.
Referenced by ff_vaapi_get_surface_id(), vaapi_mpeg4_decode_slice(), and vaapi_vc1_decode_slice().
ff_vaapi_context_fini()
int ff_vaapi_context_fini (AVCodecContext * avctx)
Common AVHWAccel.uninit() implementation.
Definition at line 66 of file vaapi.c.
Referenced by ff_vaapi_get_surface_id(), vaapi_mpeg4_decode_slice(), and vaapi_vc1_decode_slice().
ff_vaapi_render_picture()
int ff_vaapi_render_picture (FFVAContext * vactx, VASurfaceID surface)
Definition at line 71 of file vaapi.c.
Referenced by ff_vaapi_common_end_frame(), ff_vaapi_get_surface_id(), vaapi_h264_end_frame(), vaapi_hevc_end_frame(), and vaapi_vp9_end_frame().
ff_vaapi_commit_slices()
int ff_vaapi_commit_slices (FFVAContext * vactx)
Definition at line 111 of file vaapi.c.
Referenced by ff_vaapi_alloc_slice(), ff_vaapi_common_end_frame(), ff_vaapi_get_surface_id(), vaapi_h264_end_frame(), vaapi_hevc_end_frame(), and vaapi_vp9_end_frame().
alloc_buffer()
static void* alloc_buffer (FFVAContext * vactx, int type, unsigned int size, uint32_t * buf_id) static
Definition at line 151 of file vaapi.c.
Referenced by ff_vaapi_alloc_bitplane(), ff_vaapi_alloc_iq_matrix(), and ff_vaapi_alloc_pic_param().
ff_vaapi_alloc_pic_param()
void * ff_vaapi_alloc_pic_param (FFVAContext * vactx, unsigned int size)
Allocate a new picture parameter buffer.
Definition at line 163 of file vaapi.c.
Referenced by ff_vaapi_get_surface_id(), vaapi_h264_start_frame(), vaapi_hevc_start_frame(), vaapi_mpeg2_start_frame(), vaapi_mpeg4_start_frame(), vaapi_vc1_start_frame(), and vaapi_vp9_start_frame().
ff_vaapi_alloc_iq_matrix()
void * ff_vaapi_alloc_iq_matrix (FFVAContext * vactx, unsigned int size)
Allocate a new IQ matrix buffer.
Definition at line 168 of file vaapi.c.
Referenced by ff_vaapi_get_surface_id(), vaapi_h264_start_frame(), vaapi_hevc_start_frame(), vaapi_mpeg2_start_frame(), and vaapi_mpeg4_start_frame().
ff_vaapi_alloc_bitplane()
uint8_t * ff_vaapi_alloc_bitplane (FFVAContext * vactx, uint32_t size)
Allocate a new bit-plane buffer.
Definition at line 173 of file vaapi.c.
Referenced by ff_vaapi_get_surface_id(), and vaapi_vc1_start_frame().
ff_vaapi_alloc_slice()
VASliceParameterBufferBase * ff_vaapi_alloc_slice (FFVAContext * vactx, const uint8_t * buffer, uint32_t size)
Allocate a new slice descriptor for the input slice.
Parameters
vactx the VA API context
buffer the slice data buffer base
size the size of the slice in bytes
Returns
the newly allocated slice parameter
Definition at line 178 of file vaapi.c.
Referenced by ff_vaapi_get_surface_id(), vaapi_h264_decode_slice(), vaapi_hevc_decode_slice(), vaapi_mpeg2_decode_slice(), vaapi_mpeg4_decode_slice(), vaapi_vc1_decode_slice(), and vaapi_vp9_decode_slice().
ff_vaapi_common_end_frame()
void ff_vaapi_common_end_frame (AVCodecContext * avctx)
Common AVHWAccel.end_frame() implementation.
Definition at line 209 of file vaapi.c.
Referenced by ff_vaapi_get_surface_id(), vaapi_h264_end_frame(), vaapi_hevc_end_frame(), and vaapi_vp9_end_frame().
ff_vaapi_get_context()
static FFVAContext* ff_vaapi_get_context (AVCodecContext * avctx) inline static
Extract vaapi_context from an AVCodecContext.
Definition at line 57 of file vaapi_internal.h.
Referenced by ff_vaapi_common_end_frame(), ff_vaapi_context_init(), vaapi_h264_decode_slice(), vaapi_h264_end_frame(), vaapi_h264_start_frame(), vaapi_hevc_decode_slice(), vaapi_hevc_end_frame(), vaapi_hevc_start_frame(), vaapi_mpeg2_decode_slice(), vaapi_mpeg2_start_frame(), vaapi_mpeg4_decode_slice(), vaapi_mpeg4_start_frame(), vaapi_vc1_decode_slice(), vaapi_vc1_start_frame(), vaapi_vp9_decode_slice(), vaapi_vp9_end_frame(), and vaapi_vp9_start_frame().
ff_vaapi_get_surface_id()
static VASurfaceID ff_vaapi_get_surface_id (AVFrame * pic) inline static
Extract VASurfaceID from an AVFrame.
Definition at line 63 of file vaapi_internal.h.
Referenced by dpb_add(), ff_vaapi_common_end_frame(), fill_picture_parameters(), fill_vaapi_pic(), find_frame_rps_type(), get_ref_pic_index(), vaapi_h264_end_frame(), vaapi_hevc_end_frame(), vaapi_mpeg2_start_frame(), vaapi_mpeg4_start_frame(), vaapi_vc1_start_frame(), and vaapi_vp9_end_frame().
ff_vaapi_mpeg_end_frame()
int ff_vaapi_mpeg_end_frame (AVCodecContext * avctx)
Referenced by ff_vaapi_common_end_frame(), ff_vaapi_get_surface_id(), vaapi_mpeg4_decode_slice(), and vaapi_vc1_decode_slice().