FFmpeg: AVRational
AVRational
libavutil » Mathematics
Rational number calculation.
Files
file rational.h
Utilties for rational number calculation.
Data Structures
struct AVRational
Rational number (pair of numerator and denominator).
Functions
static AVRational av_make_q (int num, int den)
Create an AVRational.
static int av_cmp_q (AVRational a, AVRational b)
Compare two rationals.
static double av_q2d (AVRational a)
Convert an AVRational to a double.
int av_reduce (int *dst_num, int *dst_den, int64_t num, int64_t den, int64_t max)
Reduce a fraction.
AVRational av_mul_q (AVRational b, AVRational c) av_const
Multiply two rationals.
AVRational av_div_q (AVRational b, AVRational c) av_const
Divide one rational by another.
AVRational av_add_q (AVRational b, AVRational c) av_const
Add two rationals.
AVRational av_sub_q (AVRational b, AVRational c) av_const
Subtract one rational from another.
static av_always_inline AVRational av_inv_q (AVRational q)
Invert a rational.
AVRational av_d2q (double d, int max) av_const
Convert a double precision floating point number to a rational.
int av_nearer_q (AVRational q, AVRational q1, AVRational q2)
Find which of the two rationals is closer to another rational.
int av_find_nearest_q_idx (AVRational q, const AVRational *q_list)
Find the value in a list of rationals nearest a given reference rational.
uint32_t av_q2intfloat (AVRational q)
Convert an AVRational to a IEEE 32-bit float expressed in fixed-point format.
Detailed Description
Rational number calculation.
While rational numbers can be expressed as floating-point numbers, the conversion process is a lossy one, so are floating-point operations. On the other hand, the nature of FFmpeg demands highly accurate calculation of timestamps. This set of rational number utilities serves as a generic interface for manipulating rational numbers as pairs of numerators and denominators.
Many of the functions that operate on AVRational's have the suffix _q, in reference to the mathematical symbol "ℚ" (Q) which denotes the set of all rational numbers.
Function Documentation
av_make_q()
static AVRational av_make_q (int num, int den) inline static
Create an AVRational.
Useful for compilers that do not support compound literals.
Note
The return value is not reduced.
See also
av_reduce()
Definition at line 71 of file rational.h.
Referenced by alloc_out_frame(), avf_read_packet(), config_out_props(), config_output(), config_props(), convert_sub_to_old_ass_form(), encode_frame(), ff_decklink_read_header(), ff_decklink_set_format(), ff_mediacodec_dec_decode(), filter_frame(), mediacodec_wrap_hw_buffer(), mkv_parse_video_color(), mov_metadata_hmmt(), mov_read_sidx(), plot_cqt(), push_frame(), request_frame(), and take_samples().
av_cmp_q()
static int av_cmp_q (AVRational a, AVRational b) inline static
Compare two rationals.
Parameters
a First rational
b Second rational
Returns
One of the following values:
0 if a == b
1 if a > b
-1 if a < b
INT_MIN if one of the values is of the form 0 / 0
Definition at line 89 of file rational.h.
Referenced by av_nearer_q(), av_opt_is_set_to_default(), check_codec_match(), compute_display_area(), compute_texture_rect(), config_out_props(), config_output(), dash_init(), dump_stream_format(), ff_decklink_set_format(), ff_h263_aspect_to_info(), ff_mxf_get_samples_per_frame(), filter_frame(), find_frame_rate_index(), h264_init_ps(), init_muxer(), main(), mkv_write_track(), mpeg_decode_postinit(), opengl_compute_display_area(), update_pts(), and write_manifest().
av_q2d()
static double av_q2d (AVRational a) inline static
Convert an AVRational to a double.
Parameters
a AVRational to convert
Returns
a in floating-point form
See also
av_d2q()
Definition at line 104 of file rational.h.
Referenced by audio_thread(), av_dump_format(), av_guess_frame_rate(), av_ts_make_time_string(), avformat_find_stream_info(), avformat_transfer_internal_stream_timing_info(), calculate_display_rect(), config_input(), config_output(), config_output_props(), config_props(), configure_video_device(), decode_frame(), decode_syncpoint(), DEFINE_BLEND8(), do_blend(), do_video_out(), do_video_stats(), draw_text(), dump_mastering_display_metadata(), dump_stream_format(), dv_write_pack(), estimate_timings(), fbdev_read_header(), fbdev_read_packet(), ff_decklink_set_format(), ff_filter_frame_framed(), ff_mpv_encode_init(), ff_mpv_encode_picture(), ff_rfps_add_frame(), ff_rfps_calculate(), filter_frame(), find_compressor(), flv_write_header(), gdigrab_read_header(), gdigrab_read_packet(), geq_filter_frame(), get_best_frame(), get_fps(), get_video_frame(), grab_read_header(), init(), init_muxer(), init_output_stream_encode(), init_stream(), init_video(), main(), mkv_write_trailer(), mkv_write_video_color(), mov_get_h264_codec_tag(), mov_get_mpeg2_xdcam_codec_tag(), mov_write_trak_tag(), mpegvideo_parse(), mxf_compute_sample_count(), output_single_frame(), pkt_dump_internal(), process_input_packet(), push_frame(), put_videoinfoheader2(), read_header(), read_seek(), read_thread(), request_frame(), seg_write_packet(), segment_end(), select_frame(), set_side_data(), set_work_frame_pts(), stream_has_enough_packets(), svc_encode_init(), thp_read_header(), update(), v4l2_read_header(), video_thread(), write_manifest(), writer_print_time(), x11grab_read_header(), and x11grab_read_packet().
av_reduce()
int av_reduce (int * dst_num, int * dst_den, int64_t num, int64_t den, int64_t max)
Reduce a fraction.
This is useful for framerate calculations.
Parameters
[out] dst_num Destination numerator
[out] dst_den Destination denominator
[in] num Source numerator
[in] den Source denominator
[in] max Maximum allowed values for dst_num & dst_den
Returns
1 if the operation is exact, 0 otherwise
Definition at line 35 of file rational.c.
Referenced by apng_write_header(), asf_read_header(), av_add_q(), av_d2q(), av_guess_sample_aspect_ratio(), av_mul_q(), av_parse_ratio(), av_resample_init(), avcodec_string(), avformat_find_stream_info(), avformat_transfer_internal_stream_timing_info(), avi_write_header(), avpriv_set_pts_info(), compute_dar(), config_input(), config_output(), decode_frame(), decode_sequence_header_adv(), dnxhd_decode_header(), dump_stream_format(), dxa_read_header(), export_stream_params(), ff_audio_resample_init(), ff_canopus_parse_info_tag(), ff_compute_frame_duration(), ff_mpv_encode_init(), ff_rfps_calculate(), ff_rm_read_mdpr_codecdata(), filter_frame(), flush_packet(), get_aspect_ratio(), h264_slice_header_init(), init_output_stream_encode(), jpeg_put_comments(), libx265_encode_init(), matroska_parse_tracks(), mkv_write_track(), mov_read_header(), mov_read_pasp(), mov_read_trak(), mov_write_pasp_tag(), mpeg4_encode_vol_header(), mpeg_decode_postinit(), mxf_parse_mpeg2_frame(), nppscale_filter_frame(), nvenc_setup_encoder(), parse_video_var(), pcx_encode_frame(), put_videoinfoheader2(), read_fps(), read_huffman_tree(), rebuild_filter_bank_with_compensation(), resample_init(), set_sar(), show_stream(), skeleton_header(), smacker_read_header(), tmv_read_header(), vmd_read_header(), vtenc_create_encoder(), X264_init(), xvid_encode_frame(), yuv4_generate_header(), and yuv4_read_header().
av_mul_q()
AVRational av_mul_q (AVRational b, AVRational c) const
Multiply two rationals.
Parameters
b First rational
c Second rational
Returns
b*c
Definition at line 80 of file rational.c.
Referenced by av_add_stable(), av_div_q(), avcodec_decode_video2(), avcodec_open2(), avformat_find_stream_info(), avi_write_header(), compute_display_area(), compute_pkt_fields(), compute_texture_rect(), config_input(), config_out_props(), config_output(), config_props(), decode_vol_header(), decode_vop_header(), encode_frame(), ff_compute_frame_duration(), filter_frame(), find_frame_rate_index(), h264_parse(), init_output_stream_encode(), init_output_stream_streamcopy(), mpeg_decode_postinit(), mpegvideo_extract_headers(), mxf_compute_sample_count(), nppscale_config_props(), opengl_compute_display_area(), put_videoinfoheader2(), rv20_decode_picture_header(), set_work_frame_pts(), update_sar(), and vc1_extract_header().
av_div_q()
AVRational av_div_q (AVRational b, AVRational c) const
Divide one rational by another.
Parameters
b First rational
c Second rational
Returns
b/c
Definition at line 88 of file rational.c.
Referenced by av_dv_codec_profile2(), av_guess_frame_rate(), avi_read_header(), build_frame_code(), config_output(), config_output_props(), config_props(), config_props_output(), and mpeg_decode_postinit().
av_add_q()
AVRational av_add_q (AVRational b, AVRational c) const
Add two rationals.
Parameters
b First rational
c Second rational
Returns
b+c
Definition at line 93 of file rational.c.
Referenced by av_sub_q(), init_output_stream(), init_output_stream_streamcopy(), and main().
av_sub_q()
AVRational av_sub_q (AVRational b, AVRational c) const
Subtract one rational from another.
Parameters
b First rational
c Second rational
Returns
b-c
Definition at line 101 of file rational.c.
Referenced by ff_mxf_get_samples_per_frame(), and main().
av_inv_q()
static av_always_inline AVRational av_inv_q (AVRational q) static
Invert a rational.
Parameters
q value
Returns
1 / q
Definition at line 159 of file rational.h.
Referenced by avcodec_decode_video2(), avcodec_open2(), avformat_find_stream_info(), avformat_transfer_internal_stream_timing_info(), avi_read_header(), build_frame_code(), config_output(), config_props(), configure_input_video_filter(), decode_vol_header(), decode_vop_header(), dshow_add_device(), dv_extract_video_info(), dvvideo_decode_frame(), ff_compute_frame_duration(), ff_rfps_calculate(), find_fps(), find_frame_rate_index(), gdigrab_read_header(), h264_parse(), init(), init_output_stream_encode(), init_src(), init_video_stream(), mkv_write_track(), mov_create_timecode_track(), mov_parse_stsd_data(), mpegvideo_extract_headers(), mv_read_header(), mxf_compute_sample_count(), mxf_parse_structural_metadata(), mxf_read_seek(), mxf_write_header(), process_input_packet(), r3d_read_rdvo(), r3d_seek(), read_header(), rm_write_header(), set_work_frame_pts(), smush_read_header(), source_config_props(), txd_read_header(), vc1_extract_header(), vivo_read_header(), write_packet(), x11grab_read_header(), and yuv4_read_header().
av_d2q()
AVRational av_d2q (double d, int max) const
Convert a double precision floating point number to a rational.
In case of infinity, the returned value is expressed as {1, 0} or {-1, 0} depending on the sign.
Parameters
d double to convert
max Maximum allowed numerator and denominator
Returns
d in AVRational form
See also
av_q2d()
Definition at line 106 of file rational.c.
Referenced by amf_parse_object(), av_inv_q(), av_opt_get_q(), av_opt_get_video_rate(), av_opt_is_set_to_default(), av_opt_set_defaults2(), av_parse_ratio(), config_output_props(), decode_frame(), decode_header(), fourxm_read_header(), get_aspect_ratio(), init(), microdvd_read_header(), mov_read_tkhd(), mov_read_trak(), mpeg_decode_postinit(), nuv_header(), opt_list(), read_header(), thp_read_header(), var_read_float(), and write_number().
av_nearer_q()
int av_nearer_q (AVRational q, AVRational q1, AVRational q2)
Find which of the two rationals is closer to another rational.
Parameters
q Rational to be compared against
q1,q2 Rationals to be tested
Returns
One of the following values:
1 if q1 is nearer to q than q2
-1 if q2 is nearer to q than q1
0 if they have the same distance
Definition at line 127 of file rational.c.
Referenced by av_find_nearest_q_idx(), av_inv_q(), and find_frame_rate_index().
av_find_nearest_q_idx()
int av_find_nearest_q_idx (AVRational q, const AVRational * q_list)
Find the value in a list of rationals nearest a given reference rational.
Parameters
q Reference rational
q_list Array of rationals terminated by {0, 0}
Returns
Index of the nearest value found in the array
Definition at line 142 of file rational.c.
Referenced by av_inv_q(), ff_mxf_get_samples_per_frame(), and init_output_stream_encode().
av_q2intfloat()
uint32_t av_q2intfloat (AVRational q)
Convert an AVRational to a IEEE 32-bit float expressed in fixed-point format.
Parameters
q Rational to be converted
Returns
Equivalent floating-point value, expressed as an unsigned 32-bit integer.
Note
The returned value is platform-indepedant.
Definition at line 152 of file rational.c.
Referenced by av_inv_q(), ircam_write_header(), and main().