FFmpeg: Spherical video mapping
Spherical video mapping
libavutil » Video related
A spherical video file contains surfaces that need to be mapped onto a sphere.
Data Structures
struct AVSphericalMapping
This structure describes how to handle spherical videos, outlining information about projection, initial layout, and any other view modifier.
Enumerations
enum AVSphericalProjection { AV_SPHERICAL_EQUIRECTANGULAR, AV_SPHERICAL_CUBEMAP }
Projection of the video surface(s) on a sphere.
Functions
AVSphericalMapping * av_spherical_alloc (size_t *size)
Allocate a AVSphericalVideo structure and initialize its fields to default values.
Detailed Description
A spherical video file contains surfaces that need to be mapped onto a sphere.
Depending on how the frame was converted, a different distortion transformation or surface recomposition function needs to be applied before the video should be mapped and displayed.
Enumeration Type Documentation
AVSphericalProjection
enum AVSphericalProjection
Projection of the video surface(s) on a sphere.
Enumerator
AV_SPHERICAL_EQUIRECTANGULAR
Video represents a sphere mapped on a flat surface using equirectangular projection.
AV_SPHERICAL_CUBEMAP
Video frame is split into 6 faces of a cube, and arranged on a 3x2 layout.
Faces are oriented upwards for the front, left, right, and back faces. The up face is oriented so the top of the face is forwards and the down face is oriented so the top of the face is to the back.
Definition at line 51 of file spherical.h.
Function Documentation
av_spherical_alloc()
AVSphericalMapping* av_spherical_alloc (size_t * size)
Allocate a AVSphericalVideo structure and initialize its fields to default values.
Returns
the newly allocated struct or NULL on failure
Definition at line 24 of file spherical.c.
Referenced by mkv_parse_video_projection(), mov_parse_uuid_spherical(), and mov_read_sv3d().