FFmpeg: Frame parsing
Frame parsing
libavcodec » Decoding
Data Structures
struct AVCodecParserContext
struct AVCodecParser
Enumerations
enum AVPictureStructure { AV_PICTURE_STRUCTURE_UNKNOWN, AV_PICTURE_STRUCTURE_TOP_FIELD, AV_PICTURE_STRUCTURE_BOTTOM_FIELD, AV_PICTURE_STRUCTURE_FRAME }
Functions
AVCodecParser * av_parser_next (const AVCodecParser *c)
void av_register_codec_parser (AVCodecParser *parser)
AVCodecParserContext * av_parser_init (int codec_id)
int av_parser_parse2 (AVCodecParserContext *s, AVCodecContext *avctx, uint8_t **poutbuf, int *poutbuf_size, const uint8_t *buf, int buf_size, int64_t pts, int64_t dts, int64_t pos)
Parse a packet.
int av_parser_change (AVCodecParserContext *s, AVCodecContext *avctx, uint8_t **poutbuf, int *poutbuf_size, const uint8_t *buf, int buf_size, int keyframe)
void av_parser_close (AVCodecParserContext *s)
Detailed Description
Enumeration Type Documentation
AVPictureStructure
enum AVPictureStructure
Enumerator
AV_PICTURE_STRUCTURE_UNKNOWN
AV_PICTURE_STRUCTURE_TOP_FIELD
AV_PICTURE_STRUCTURE_BOTTOM_FIELD
AV_PICTURE_STRUCTURE_FRAME
Definition at line 4993 of file avcodec.h.
Function Documentation
av_parser_next()
AVCodecParser* av_parser_next (const AVCodecParser * c)
Definition at line 36 of file parser.c.
av_register_codec_parser()
void av_register_codec_parser (AVCodecParser * parser)
Definition at line 44 of file parser.c.
av_parser_init()
AVCodecParserContext* av_parser_init (int codec_id)
Definition at line 52 of file parser.c.
Referenced by avformat_find_stream_info(), ff_qsv_process_data(), flac_read_timestamp(), init_output_stream_streamcopy(), old_flac_header(), read_frame_internal(), and remove_extradata_init().
av_parser_parse2()
int av_parser_parse2 (AVCodecParserContext * s, AVCodecContext * avctx, uint8_t ** poutbuf, int * poutbuf_size, const uint8_t * buf, int buf_size, int64_t pts, int64_t dts, int64_t pos)
Parse a packet.
Parameters
s parser context.
avctx codec context.
poutbuf set to pointer to parsed buffer or NULL if not yet finished.
poutbuf_size set to size of parsed buffer or zero if not yet finished.
buf input buffer.
buf_size buffer size in bytes without the padding. I.e. the full buffer size is assumed to be buf_size + AV_INPUT_BUFFER_PADDING_SIZE. To signal EOF, this should be 0 (so that the last frame can be output).
pts input presentation timestamp.
dts input decoding timestamp.
pos input byte position in stream.
Returns
the number of bytes of the input bitstream used.
Example:
while(in_len){
    len = av_parser_parse2(myparser, AVCodecContext, &data, &size,
                                     in_data, in_len,
                                     pts, dts, pos);
    in_data += len;
    in_len  -= len;
    if(size)
       decode_frame(data, size);
}
Definition at line 137 of file parser.c.
Referenced by ff_qsv_process_data(), flac_read_timestamp(), old_flac_header(), and parse_packet().
av_parser_change()
int av_parser_change (AVCodecParserContext * s, AVCodecContext * avctx, uint8_t ** poutbuf, int * poutbuf_size, const uint8_t * buf, int buf_size, int keyframe)
Returns
0 if the output buffer is a subset of the input, 1 if it is allocated and must be freed
Deprecated:
use AVBitStreamFilter
Definition at line 206 of file parser.c.
Referenced by do_streamcopy().
av_parser_close()
void av_parser_close (AVCodecParserContext * s)
Definition at line 241 of file parser.c.
Referenced by estimate_timings_from_pts(), ff_qsv_decode_close(), ff_read_frame_flush(), ffmpeg_cleanup(), flac_read_timestamp(), free_stream(), old_flac_header(), parse_packet(), read_frame_internal(), remove_extradata_close(), and update_stream_avctx().