FFmpeg: ASS styles
ASS styles
Variables
void(* ASSCodesCallbacks::text)(void *priv, const char *text, int len)
void(* ASSCodesCallbacks::new_line)(void *priv, int forced)
void(* ASSCodesCallbacks::style)(void *priv, char style, int close)
void(* ASSCodesCallbacks::color)(void *priv, unsigned int, unsigned int color_id)
void(* ASSCodesCallbacks::alpha)(void *priv, int alpha, int alpha_id)
void(* ASSCodesCallbacks::font_name)(void *priv, const char *name)
void(* ASSCodesCallbacks::font_size)(void *priv, int size)
void(* ASSCodesCallbacks::alignment)(void *priv, int alignment)
void(* ASSCodesCallbacks::cancel_overrides)(void *priv, const char *style)
Detailed Description
Variable Documentation
text
void(* ASSCodesCallbacks::text) (void *priv, const char *text, int len)
Definition at line 159 of file ass_split.h.
Referenced by ff_ass_split_override_codes().
new_line
void(* ASSCodesCallbacks::new_line) (void *priv, int forced)
Definition at line 160 of file ass_split.h.
Referenced by ff_ass_split_override_codes().
style
void(* ASSCodesCallbacks::style) (void *priv, char style, int close)
Definition at line 161 of file ass_split.h.
Referenced by ff_ass_split_override_codes().
color
void(* ASSCodesCallbacks::color) (void *priv, unsigned int, unsigned int color_id)
Definition at line 162 of file ass_split.h.
Referenced by ff_ass_split_override_codes().
alpha
void(* ASSCodesCallbacks::alpha) (void *priv, int alpha, int alpha_id)
Definition at line 163 of file ass_split.h.
Referenced by ff_ass_split_override_codes().
font_name
void(* ASSCodesCallbacks::font_name) (void *priv, const char *name)
Definition at line 164 of file ass_split.h.
Referenced by ff_ass_split_override_codes().
font_size
void(* ASSCodesCallbacks::font_size) (void *priv, int size)
Definition at line 165 of file ass_split.h.
Referenced by ff_ass_split_override_codes().
alignment
void(* ASSCodesCallbacks::alignment) (void *priv, int alignment)
Definition at line 166 of file ass_split.h.
Referenced by ff_ass_split_override_codes().
cancel_overrides
void(* ASSCodesCallbacks::cancel_overrides) (void *priv, const char *style)
Definition at line 167 of file ass_split.h.
Referenced by ff_ass_split_override_codes().