FFmpeg: AVPacket
AVPacket
libavcodec » Core functions/structures.
Types and functions for working with AVPacket.
Data Structures
struct AVPacketSideData
struct AVPacket
This structure stores compressed data.
Macros
#define AV_PKT_DATA_QUALITY_FACTOR AV_PKT_DATA_QUALITY_STATS
#define AV_PKT_FLAG_KEY 0x0001
The packet contains a keyframe.
#define AV_PKT_FLAG_CORRUPT 0x0002
The packet content is corrupted.
#define AV_PKT_FLAG_DISCARD 0x0004
Flag is used to discard packets which are required to maintain valid decoder state but are not required for output and should be dropped after decoding.
Enumerations
enum AVPacketSideDataType {
AV_PKT_DATA_PALETTE, AV_PKT_DATA_NEW_EXTRADATA, AV_PKT_DATA_PARAM_CHANGE, AV_PKT_DATA_H263_MB_INFO,
AV_PKT_DATA_REPLAYGAIN, AV_PKT_DATA_DISPLAYMATRIX, AV_PKT_DATA_STEREO3D, AV_PKT_DATA_AUDIO_SERVICE_TYPE,
AV_PKT_DATA_QUALITY_STATS, AV_PKT_DATA_FALLBACK_TRACK, AV_PKT_DATA_CPB_PROPERTIES, AV_PKT_DATA_SKIP_SAMPLES =70,
AV_PKT_DATA_JP_DUALMONO, AV_PKT_DATA_STRINGS_METADATA, AV_PKT_DATA_SUBTITLE_POSITION, AV_PKT_DATA_MATROSKA_BLOCKADDITIONAL,
AV_PKT_DATA_WEBVTT_IDENTIFIER, AV_PKT_DATA_WEBVTT_SETTINGS, AV_PKT_DATA_METADATA_UPDATE, AV_PKT_DATA_MPEGTS_STREAM_ID,
AV_PKT_DATA_MASTERING_DISPLAY_METADATA, AV_PKT_DATA_SPHERICAL
}
enum AVSideDataParamChangeFlags { AV_SIDE_DATA_PARAM_CHANGE_CHANNEL_COUNT = 0x0001, AV_SIDE_DATA_PARAM_CHANGE_CHANNEL_LAYOUT = 0x0002, AV_SIDE_DATA_PARAM_CHANGE_SAMPLE_RATE = 0x0004, AV_SIDE_DATA_PARAM_CHANGE_DIMENSIONS = 0x0008 }
Functions
AVPacket * av_packet_alloc (void)
Allocate an AVPacket and set its fields to default values.
AVPacket * av_packet_clone (AVPacket *src)
Create a new packet that references the same data as src.
void av_packet_free (AVPacket **pkt)
Free the packet, if the packet is reference counted, it will be unreferenced first.
void av_init_packet (AVPacket *pkt)
Initialize optional fields of a packet with default values.
int av_new_packet (AVPacket *pkt, int size)
Allocate the payload of a packet and initialize its fields with default values.
void av_shrink_packet (AVPacket *pkt, int size)
Reduce packet size, correctly zeroing padding.
int av_grow_packet (AVPacket *pkt, int grow_by)
Increase packet size, correctly zeroing padding.
int av_packet_from_data (AVPacket *pkt, uint8_t *data, int size)
Initialize a reference-counted packet from av_malloc()ed data.
attribute_deprecated int av_dup_packet (AVPacket *pkt)
int av_copy_packet (AVPacket *dst, const AVPacket *src)
Copy packet, including contents.
int av_copy_packet_side_data (AVPacket *dst, const AVPacket *src)
Copy packet side data.
attribute_deprecated void av_free_packet (AVPacket *pkt)
Free a packet.
uint8_t * av_packet_new_side_data (AVPacket *pkt, enum AVPacketSideDataType type, int size)
Allocate new information of a packet.
int av_packet_add_side_data (AVPacket *pkt, enum AVPacketSideDataType type, uint8_t *data, size_t size)
Wrap an existing array as a packet side data.
int av_packet_shrink_side_data (AVPacket *pkt, enum AVPacketSideDataType type, int size)
Shrink the already allocated side data buffer.
uint8_t * av_packet_get_side_data (AVPacket *pkt, enum AVPacketSideDataType type, int *size)
Get side information from packet.
int av_packet_merge_side_data (AVPacket *pkt)
int av_packet_split_side_data (AVPacket *pkt)
const char * av_packet_side_data_name (enum AVPacketSideDataType type)
uint8_t * av_packet_pack_dictionary (AVDictionary *dict, int *size)
Pack a dictionary for use in side_data.
int av_packet_unpack_dictionary (const uint8_t *data, int size, AVDictionary **dict)
Unpack a dictionary from side_data.
void av_packet_free_side_data (AVPacket *pkt)
Convenience function to free all the side data stored.
int av_packet_ref (AVPacket *dst, const AVPacket *src)
Setup a new reference to the data described by a given packet.
void av_packet_unref (AVPacket *pkt)
Wipe the packet.
void av_packet_move_ref (AVPacket *dst, AVPacket *src)
Move every field in src to dst and reset src.
int av_packet_copy_props (AVPacket *dst, const AVPacket *src)
Copy only "properties" fields from src to dst.
void av_packet_rescale_ts (AVPacket *pkt, AVRational tb_src, AVRational tb_dst)
Convert valid timing fields (timestamps / durations) in a packet from one timebase to another.
Detailed Description
Types and functions for working with AVPacket.
Macro Definition Documentation
AV_PKT_DATA_QUALITY_FACTOR
#define AV_PKT_DATA_QUALITY_FACTOR AV_PKT_DATA_QUALITY_STATS
Definition at line 1552 of file avcodec.h.
AV_PKT_FLAG_KEY
#define AV_PKT_FLAG_KEY 0x0001
The packet contains a keyframe.
Definition at line 1643 of file avcodec.h.
Referenced by a64multi_encode_frame(), ape_tag_read_field(), apng_read_packet(), asf_parse_packet(), asf_read_payload(), asf_read_picture(), asf_read_pts(), asf_read_timestamp(), asf_write_packet(), av_read_frame(), avcodec_encode_audio2(), avf_read_packet(), avi_read_packet(), avi_write_packet_internal(), avpriv_dv_produce_packet(), avs_read_audio_packet(), avs_read_video_packet(), avui_encode_frame(), bmp_encode_frame(), cdxl_read_packet(), cine_read_packet(), cinepak_encode_frame(), compute_pkt_fields(), daala_gptopts(), dash_write_packet(), dc1394_read_common(), decode_frame(), decode_frame_common(), dirac_gptopts(), dnxhd_encode_picture(), do_streamcopy(), do_video_out(), dump_extradata(), dv_extract_audio_info(), dvvideo_encode_frame(), ea_read_packet(), encode_frame(), encode_picture_ls(), encode_png(), ff_flac_parse_picture(), ff_id3v2_parse_apic(), ff_img_read_packet(), ff_mov_add_hinted_packet(), ff_mov_write_packet(), ff_mpv_encode_picture(), ff_qsv_encode(), ff_rm_parse_packet(), ff_rm_retrieve_cache(), ff_stream_add_bitstream_filter(), ff_subtitles_queue_insert(), ffm_read_packet(), ffm_write_packet(), fifo_thread_write_packet(), filter_packet(), flashsv2_encode_frame(), flashsv_decode_frame(), flashsv_encode_frame(), flv_data_packet(), flv_read_packet(), flv_write_packet(), framecrc_write_packet(), get_attachment(), get_needed_flags(), gif_encode_frame(), gif_read_packet(), h263_handle_packet(), hap_encode(), hds_write_packet(), hls_read_packet(), hls_write_packet(), http_prepare_data(), idcin_read_packet(), iff_read_packet(), ism_write_packet(), libkvazaar_encode(), libopenjpeg_encode_frame(), libschroedinger_encode_frame(), libwebp_anim_encode_frame(), libwebp_encode_frame(), libx265_encode_frame(), ljpeg_encode_frame(), lmlm4_read_packet(), lvf_read_packet(), lxf_read_packet(), main(), matroska_parse_block(), matroska_read_header(), mkv_write_packet(), mkv_write_packet_internal(), modplug_read_packet(), mov_create_chapter_track(), mov_create_timecode_track(), mov_parse_vc1_frame(), mov_read_chapters(), mov_read_covr(), mov_read_packet(), mov_write_single_packet(), mpeg_mux_write_packet(), mpegts_write_flush(), mpegts_write_packet_internal(), msnwc_tcp_read_packet(), mux_frames(), mv_read_packet(), nsv_read_chunk(), nut_read_packet(), nut_write_packet(), nuv_packet(), ogg_read_packet(), ogg_read_timestamp(), ogg_validate_keyframe(), ogg_write_packet_internal(), ogm_packet(), old_dirac_gptopts(), omx_encode_frame(), pam_encode_frame(), parse_packet(), pcx_encode_frame(), pkt_dump_internal(), pnm_encode_frame(), process_output_surface(), prores_encode_frame(), put_payload_header(), qt_rtp_parse_packet(), qtkit_read_packet(), qtrle_encode_frame(), raw_encode(), read_dst_frame(), read_frame(), read_frame_internal(), read_packet(), remove_extradata(), rm_write_audio(), rm_write_video(), roq_encode_frame(), rpl_read_packet(), sdr2_read_packet(), seek_frame_generic(), seg_write_packet(), show_packet(), siff_read_packet(), smush_read_packet(), storeframe(), sunrast_encode_frame(), sup_read_packet(), svc_encode_frame(), svq1_encode_frame(), targa_encode_frame(), theora_gptopts(), tmv_read_packet(), utvideo_encode_frame(), v308_encode_frame(), v408_encode_frame(), v410_encode_frame(), vaapi_encode_output(), vc1t_read_packet(), vc1test_write_packet(), vid_read_packet(), decklink_input_callback::VideoInputFrameArrived(), vp8_gptopts(), vp8_handle_packet(), vtenc_cm_to_avpacket(), webm_chunk_write_packet(), webm_clusters_start_with_keyframe(), wrapped_avframe_encode(), write_timestamp(), X264_frame(), XAVS_frame(), xbm_encode_frame(), xface_encode_frame(), xmv_fetch_video_packet(), xvid_encode_frame(), xwd_encode_frame(), y41p_encode_frame(), yop_read_packet(), yuv4_encode_frame(), and zerocodec_decode_frame().
AV_PKT_FLAG_CORRUPT
#define AV_PKT_FLAG_CORRUPT 0x0002
The packet content is corrupted.
Definition at line 1644 of file avcodec.h.
Referenced by aiff_read_packet(), apc_read_packet(), append_packet_chunked(), ff_pcm_read_packet(), ff_read_packet(), handle_packet(), mp3_read_packet(), new_pes_packet(), oma_read_packet(), opus_packet(), process_input(), read_packet(), sol_read_packet(), vorbis_packet(), and vp8_handle_packet().
AV_PKT_FLAG_DISCARD
#define AV_PKT_FLAG_DISCARD 0x0004
Flag is used to discard packets which are required to maintain valid decoder state but are not required for output and should be dropped after decoding.
Definition at line 1650 of file avcodec.h.
Referenced by ff_init_buffer_info(), initializations(), mov_read_packet(), and show_packet().
Enumeration Type Documentation
AVPacketSideDataType
enum AVPacketSideDataType
Enumerator
AV_PKT_DATA_PALETTE
AV_PKT_DATA_NEW_EXTRADATA
The AV_PKT_DATA_NEW_EXTRADATA is used to notify the codec or the format that the extradata buffer was changed and the receiving side should act upon it appropriately.
The new extradata is embedded in the side data buffer and should be immediately used for processing the current frame or packet.
AV_PKT_DATA_PARAM_CHANGE
An AV_PKT_DATA_PARAM_CHANGE side data packet is laid out as follows:
u32le param_flags
if (param_flags & AV_SIDE_DATA_PARAM_CHANGE_CHANNEL_COUNT)
    s32le channel_count
if (param_flags & AV_SIDE_DATA_PARAM_CHANGE_CHANNEL_LAYOUT)
    u64le channel_layout
if (param_flags & AV_SIDE_DATA_PARAM_CHANGE_SAMPLE_RATE)
    s32le sample_rate
if (param_flags & AV_SIDE_DATA_PARAM_CHANGE_DIMENSIONS)
    s32le width
    s32le height
AV_PKT_DATA_H263_MB_INFO
An AV_PKT_DATA_H263_MB_INFO side data packet contains a number of structures with info about macroblocks relevant to splitting the packet into smaller packets on macroblock edges (e.g.
as for RFC 2190). That is, it does not necessarily contain info about all macroblocks, as long as the distance between macroblocks in the info is smaller than the target payload size. Each MB info structure is 12 bytes, and is laid out as follows:
u32le bit offset from the start of the packet
u8    current quantizer at the start of the macroblock
u8    GOB number
u16le macroblock address within the GOB
u8    horizontal MV predictor
u8    vertical MV predictor
u8    horizontal MV predictor for block number 3
u8    vertical MV predictor for block number 3
AV_PKT_DATA_REPLAYGAIN
This side data should be associated with an audio stream and contains ReplayGain information in form of the AVReplayGain struct.
AV_PKT_DATA_DISPLAYMATRIX
This side data contains a 3x3 transformation matrix describing an affine transformation that needs to be applied to the decoded video frames for correct presentation.
See libavutil/display.h for a detailed description of the data.
AV_PKT_DATA_STEREO3D
This side data should be associated with a video stream and contains Stereoscopic 3D information in form of the AVStereo3D struct.
AV_PKT_DATA_AUDIO_SERVICE_TYPE
This side data should be associated with an audio stream and corresponds to enum AVAudioServiceType.
AV_PKT_DATA_QUALITY_STATS
This side data contains quality related information from the encoder.
u32le quality factor of the compressed frame. Allowed range is between 1 (good) and FF_LAMBDA_MAX (bad).
u8    picture type
u8    error count
u16   reserved
u64le[error count] sum of squared differences between encoder in and output
AV_PKT_DATA_FALLBACK_TRACK
This side data contains an integer value representing the stream index of a "fallback" track.
A fallback track indicates an alternate track to use when the current track can not be decoded for some reason. e.g. no decoder available for codec.
AV_PKT_DATA_CPB_PROPERTIES
This side data corresponds to the AVCPBProperties struct.
AV_PKT_DATA_SKIP_SAMPLES
Recommmends skipping the specified number of samples.
u32le number of samples to skip from start of this packet
u32le number of samples to skip from end of this packet
u8    reason for start skip
u8    reason for end   skip (0=padding silence, 1=convergence)
AV_PKT_DATA_JP_DUALMONO
An AV_PKT_DATA_JP_DUALMONO side data packet indicates that the packet may contain "dual mono" audio specific to Japanese DTV and if it is true, recommends only the selected channel to be used.
u8    selected channels (0=mail/left, 1=sub/right, 2=both)
AV_PKT_DATA_STRINGS_METADATA
A list of zero terminated key/value strings.
There is no end marker for the list, so it is required to rely on the side data size to stop.
AV_PKT_DATA_SUBTITLE_POSITION
Subtitle event position.
u32le x1
u32le y1
u32le x2
u32le y2
AV_PKT_DATA_MATROSKA_BLOCKADDITIONAL
Data found in BlockAdditional element of matroska container.
There is no end marker for the data, so it is required to rely on the side data size to recognize the end. 8 byte id (as found in BlockAddId) followed by data.
AV_PKT_DATA_WEBVTT_IDENTIFIER
The optional first identifier line of a WebVTT cue.
AV_PKT_DATA_WEBVTT_SETTINGS
The optional settings (rendering instructions) that immediately follow the timestamp specifier of a WebVTT cue.
AV_PKT_DATA_METADATA_UPDATE
A list of zero terminated key/value strings.
There is no end marker for the list, so it is required to rely on the side data size to stop. This side data includes updated metadata which appeared in the stream.
AV_PKT_DATA_MPEGTS_STREAM_ID
MPEGTS stream ID, this is required to pass the stream ID information from the demuxer to the corresponding muxer.
AV_PKT_DATA_MASTERING_DISPLAY_METADATA
Mastering display metadata (based on SMPTE-2086:2014).
This metadata should be associated with a video stream and containts data in the form of the AVMasteringDisplayMetadata struct.
AV_PKT_DATA_SPHERICAL
This side data should be associated with a video stream and corresponds to the AVSphericalMapping structure.
Definition at line 1366 of file avcodec.h.
AVSideDataParamChangeFlags
enum AVSideDataParamChangeFlags
Enumerator
AV_SIDE_DATA_PARAM_CHANGE_CHANNEL_COUNT
AV_SIDE_DATA_PARAM_CHANGE_CHANNEL_LAYOUT
AV_SIDE_DATA_PARAM_CHANGE_SAMPLE_RATE
AV_SIDE_DATA_PARAM_CHANGE_DIMENSIONS
Definition at line 1652 of file avcodec.h.
Function Documentation
av_packet_alloc()
AVPacket* av_packet_alloc (void)
Allocate an AVPacket and set its fields to default values.
The resulting struct must be freed using av_packet_free().
Returns
An AVPacket filled with default values or NULL on failure.
Note
this only allocates the AVPacket itself, not the data buffers. Those must be allocated through other means such as av_new_packet.
See also
av_new_packet
Definition at line 51 of file avpacket.c.
Referenced by av_bsf_alloc(), av_packet_clone(), avcodec_open2(), ff_bsf_get_packet(), and ff_reshuffle_raw_rgb().
av_packet_clone()
AVPacket* av_packet_clone (AVPacket * src)
Create a new packet that references the same data as src.
This is a shortcut for av_packet_alloc()+av_packet_ref().
Returns
newly created AVPacket on success, NULL on error.
See also
av_packet_alloc
av_packet_ref
Definition at line 611 of file avpacket.c.
Referenced by main().
av_packet_free()
void av_packet_free (AVPacket ** pkt)
Free the packet, if the packet is reference counted, it will be unreferenced first.
Parameters
packet packet to be freed. The pointer will be set to NULL.
Note
passing NULL is a no-op.
Definition at line 62 of file avpacket.c.
Referenced by aac_adtstoasc_filter(), av_bsf_free(), av_packet_clone(), avcodec_close(), avcodec_open2(), avi_write_packet(), chomp_filter(), dca_core_filter(), dump_extradata(), ff_reshuffle_raw_rgb(), h264_mp4toannexb_filter(), hevc_mp4toannexb_filter(), imx_dump_header(), main(), mjpeg2jpeg_filter(), mjpega_dump_header(), mov2textsub(), mov_write_packet(), mp3_header_decompress(), mpeg4_unpack_bframes_filter(), noise(), remove_extradata(), text2movsub(), and vp9_superframe_filter().
av_init_packet()
void av_init_packet (AVPacket * pkt)
Initialize optional fields of a packet with default values.
Note, this does not touch the data and size members, which have to be initialized separately.
Parameters
pkt packet
Examples:
decoding_encoding.c, demuxing_decoding.c, muxing.c, transcode_aac.c, and transcoding.c.
Definition at line 33 of file avpacket.c.
Referenced by asf_read_stream_properties(), asf_read_timestamp(), audio_decode_example(), audio_encode_example(), av_get_packet(), av_interleaved_write_frame(), av_new_packet(), av_packet_move_ref(), av_packet_unref(), av_write_uncoded_frame_internal(), avcodec_encode_audio2(), avcodec_encode_video2(), avformat_find_stream_info(), avpriv_dv_produce_packet(), compute_crc_of_packets(), dc1394_read_common(), do_audio_out(), do_streamcopy(), do_subtitle_out(), do_video_out(), dv_extract_audio_info(), encode_frame(), encode_write_frame(), FDBPrepare(), ff_alloc_packet2(), ff_flac_parse_picture(), ff_id3v2_parse_apic(), ff_interleave_packet_per_dts(), ff_load_image(), ff_mov_add_hinted_packet(), ff_read_packet(), ff_rtp_finalize_packet(), ffmmal_decode(), fifo_basic_test(), fifo_overflow_drop_test(), fifo_write_header_err_tst(), fifo_write_packet(), filter(), filter_frame(), find_video_stream_info(), flac_read_timestamp(), flush_encoders(), hnm_read_header(), init_packet(), initializations(), lavfi_read_packet(), LLVMFuzzerTestOneInput(), main(), matroska_read_header(), mediacodec_decode_init(), mkv_write_header(), mov_write_subtitle_end_packet(), movie_push_frame(), mpegts_get_dts(), mpegts_write_packet_internal(), mpjpeg_read_packet(), mux_frames(), mxf_interleave_get_packet(), new_data_packet(), new_pes_packet(), packet_queue_put_nullpacket(), parse_packet(), process_input_packet(), qt_rtp_parse_packet(), read_frame_internal(), read_interval_packets(), reset_packet(), reset_packet_state(), rtp_mpegts_write_packet(), run_test(), signal_init_ts(), sp5x_decode_frame(), tdsc_decode_jpeg_tile(), video_decode(), video_decode_example(), video_encode_example(), decklink_input_callback::VideoInputFrameArrived(), vp8_lossy_decode_frame(), wc3_read_header(), worker(), write_audio_frame(), write_skip_frames(), write_video_frame(), and xvid_encode_init().
av_new_packet()
int av_new_packet (AVPacket * pkt, int size)
Allocate the payload of a packet and initialize its fields with default values.
Parameters
pkt packet
size wanted payload size
Returns
0 if OK, AVERROR_xxx otherwise
Definition at line 86 of file avpacket.c.
Referenced by aa_read_packet(), aac_parse_packet(), ac3_handle_packet(), amr_handle_packet(), amr_read_packet(), ape_read_packet(), asf_deinterleave(), asf_parse_packet(), asf_read_replicated_data(), asf_read_single_payload(), audio_read_packet(), avf_read_packet(), avisynth_read_packet_audio(), avisynth_read_packet_video(), avs_read_video_packet(), bmv_read_packet(), callback(), cdxl_read_packet(), cin_read_packet(), create_subcc_packet(), decode_frame(), dss_723_1_read_packet(), dss_sp_read_packet(), dump_extradata(), dxa_read_packet(), encode_frame(), fbdev_read_packet(), ff_alloc_packet2(), ff_h263_handle_packet(), ff_h264_handle_aggregated_packet(), ff_h264_handle_frag_packet(), ff_img_read_packet(), ff_raw_read_partial_packet(), ff_reshuffle_raw_rgb(), ff_rm_retrieve_cache(), ff_spdif_read_packet(), ff_subtitles_queue_insert(), ffm_read_packet(), flic_read_packet(), fourxm_read_packet(), fsb_read_packet(), g723_1_read_packet(), gdigrab_read_packet(), genh_read_packet(), grab_read_packet(), h264_handle_packet(), hevc_handle_packet(), ilbc_read_packet(), imx_dump_header(), interleave_new_audio_packet(), latm_parse_packet(), lavfi_read_packet(), load_ipmovie_packet(), lxf_read_packet(), main(), matroska_parse_frame(), matroska_parse_rm_audio(), matroska_parse_webvtt(), matroska_read_header(), merge_superframe(), mjpeg2jpeg_filter(), mjpega_dump_header(), mmap_read_frame(), modplug_read_packet(), mov2textsub(), mp3_header_decompress(), mpa_robust_parse_packet(), mpc_read_packet(), mpeg_parse_packet(), mpegts_raw_read_packet(), noise(), nut_read_packet(), nuv_packet(), ogg_read_packet(), pulse_read_packet(), qdm2_restore_block(), qt_rtp_parse_packet(), qtkit_read_packet(), read_frame(), read_packet(), read_packet_gme(), read_packet_openmpt(), recode_subtitle(), return_stored_frame(), rm_assemble_video_frame(), rm_read_audio_stream_info(), roq_read_packet(), rsd_read_packet(), rtp_parse_packet_internal(), sbg_read_packet(), sdr2_read_packet(), seq_read_packet(), siff_read_packet(), smacker_read_packet(), store_packet(), str_read_packet(), supply_new_packets(), swf_read_packet(), text2movsub(), vaapi_encode_output(), vc2hq_handle_sequence_header(), vc2hq_mark_end_of_sequence(), videostream_cb(), vmd_read_packet(), vpk_read_packet(), vqf_read_packet(), wsaud_read_packet(), wv_read_packet(), xcbgrab_frame(), xiph_handle_packet(), and yop_read_packet().
av_shrink_packet()
void av_shrink_packet (AVPacket * pkt, int size)
Reduce packet size, correctly zeroing padding.
Parameters
pkt packet
size new size
Definition at line 101 of file avpacket.c.
Referenced by adp_read_packet(), append_packet_chunked(), asf_parse_packet(), cdxl_read_packet(), cin_read_packet(), decode_frame(), encode_frame(), ff_raw_read_partial_packet(), fourxm_read_packet(), hap_encode(), libopenjpeg_encode_frame(), libopus_encode(), mxf_decrypt_triplet(), mxf_get_d10_aes3_packet(), nuv_packet(), sdr2_read_packet(), swf_read_packet(), twolame_encode_frame(), and yop_read_packet().
av_grow_packet()
int av_grow_packet (AVPacket * pkt, int grow_by)
Increase packet size, correctly zeroing padding.
Parameters
pkt packet
grow_by number of bytes by which to increase the size of the packet
Definition at line 109 of file avpacket.c.
Referenced by alloc_and_copy(), append_packet_chunked(), encode_callback(), encode_frame(), ff_subtitles_queue_insert(), hevc_mp4toannexb_filter(), info_callback(), main(), and wv_read_packet().
av_packet_from_data()
int av_packet_from_data (AVPacket * pkt, uint8_t * data, int size)
Initialize a reference-counted packet from av_malloc()ed data.
Parameters
pkt packet to be initialized. This function will set the data, size, buf and destruct fields, all others are left untouched.
data Data allocated by av_malloc() to be used as packet data. If this function returns successfully, the data is owned by the underlying AVBuffer. The caller may not access the data through other means.
size size of data in bytes, without the padding. I.e. the full buffer size is assumed to be size + AV_INPUT_BUFFER_PADDING_SIZE.
Returns
0 on success, a negative AVERROR on error
Definition at line 152 of file avpacket.c.
Referenced by ff_rtp_finalize_packet(), main(), mpeg4_unpack_bframes_filter(), omx_encode_frame(), prepare_packet(), and qt_rtp_parse_packet().
av_dup_packet()
attribute_deprecated int av_dup_packet (AVPacket * pkt)
Warning
This is a hack - the packet memory allocation stuff is broken. The packet is allocated if it was not really allocated.
Deprecated:
Use av_packet_ref
Definition at line 253 of file avpacket.c.
Referenced by avcodec_encode_audio2(), avcodec_encode_video2(), avpacket_queue_put(), worker(), and write_packet().
av_copy_packet()
int av_copy_packet (AVPacket * dst, const AVPacket * src)
Copy packet, including contents.
Returns
0 on success, negative AVERROR on fail
Definition at line 264 of file avpacket.c.
Referenced by aiff_write_packet(), apng_write_packet(), ff_subtitles_queue_read_packet(), filter_packet(), flush_packet(), gif_write_packet(), mp3_write_packet(), read_thread(), webp_write_packet(), and write_packet().
av_copy_packet_side_data()
int av_copy_packet_side_data (AVPacket * dst, const AVPacket * src)
Copy packet side data.
Returns
0 on success, negative AVERROR on fail
Definition at line 226 of file avpacket.c.
Referenced by copy_packet_data(), and do_streamcopy().
av_free_packet()
attribute_deprecated void av_free_packet (AVPacket * pkt)
Free a packet.
Deprecated:
Use av_packet_unref
Parameters
pkt packet to free
Definition at line 281 of file avpacket.c.
av_packet_new_side_data()
uint8_t* av_packet_new_side_data (AVPacket * pkt, enum AVPacketSideDataType type, int size)
Allocate new information of a packet.
Parameters
pkt packet
type side information type
size side information size
Returns
pointer to fresh allocated data or NULL otherwise
Definition at line 318 of file avpacket.c.
Referenced by add_event(), asf_parse_packet(), av_packet_copy_props(), avi_read_packet(), concat_read_packet(), encode_apng(), ff_add_param_change(), ff_mpv_encode_picture(), ff_side_data_set_encoder_stats(), flac_encode_frame(), flv_read_packet(), gif_encode_frame(), gif_image_write_image(), idcin_read_packet(), lavfi_read_packet(), libopus_encode(), load_ipmovie_packet(), matroska_deliver_packet(), matroska_parse_frame(), matroska_parse_webvtt(), mov_change_extradata(), mov_read_packet(), mp3lame_encode_frame(), new_pes_packet(), ogg_read_packet(), process_input(), read_frame(), read_frame_internal(), read_sm_data(), storeframe(), swf_read_packet(), and x11grab_read_packet().
av_packet_add_side_data()
int av_packet_add_side_data (AVPacket * pkt, enum AVPacketSideDataType type, uint8_t * data, size_t size)
Wrap an existing array as a packet side data.
Parameters
pkt packet
type side information type
data the side data array. It must be allocated with the av_malloc() family of functions. The ownership of the data is transferred to pkt.
size side information size
Returns
a non-negative number on success, a negative AVERROR code on failure. On failure, the packet is unchanged and the data remains owned by the caller.
Definition at line 295 of file avpacket.c.
Referenced by av_packet_new_side_data(), ff_mpv_encode_picture(), and setup_side_data_entry().
av_packet_shrink_side_data()
int av_packet_shrink_side_data (AVPacket * pkt, enum AVPacketSideDataType type, int size)
Shrink the already allocated side data buffer.
Parameters
pkt packet
type side information type
size new side information size
Returns
0 on success, < 0 on failure
Definition at line 521 of file avpacket.c.
Referenced by ff_mpv_encode_picture().
av_packet_get_side_data()
uint8_t* av_packet_get_side_data (AVPacket * pkt, enum AVPacketSideDataType type, int * size)
Get side information from packet.
Parameters
pkt packet
type desired side information type
size pointer for side information size to store (optional)
Returns
pointer to data if present or NULL otherwise
Definition at line 339 of file avpacket.c.
Referenced by aac_decode_frame(), aac_decode_frame_int(), add_metadata_from_side_data(), apply_param_change(), avcodec_decode_audio4(), cinepak_decode_frame(), decode_frame(), decode_tag(), ff_get_packet_palette(), ff_init_buffer_info(), ff_side_data_set_encoder_stats(), flac_write_packet(), flush_packet(), flv_write_packet(), gif_write_packet(), h264_decode_frame(), hevc_decode_frame(), idcin_decode_frame(), ipvideo_decode_frame(), mkv_check_new_extra_data(), mkv_write_block(), mkv_write_vtt_blocks(), mov_write_single_packet(), mp3_write_audio_packet(), mpegts_write_packet_internal(), msrle_decode_frame(), msvideo1_decode_frame(), process_input(), qtrle_decode_frame(), raw_decode(), read_frame_internal(), rscc_decode_frame(), rtp_write_packet(), show_packet(), smc_decode_frame(), srt_decode_frame(), srt_write_packet(), vpx_decode(), webvtt_write_packet(), and write_packet().
av_packet_merge_side_data()
int av_packet_merge_side_data (AVPacket * pkt)
Definition at line 382 of file avpacket.c.
Referenced by read_frame_internal(), and write_packet().
av_packet_split_side_data()
int av_packet_split_side_data (AVPacket * pkt)
Definition at line 417 of file avpacket.c.
Referenced by avcodec_decode_audio4(), avcodec_decode_subtitle2(), avcodec_decode_video2(), avcodec_send_packet(), do_packet_auto_bsf(), output_packet(), process_input(), and write_packet().
av_packet_side_data_name()
const char* av_packet_side_data_name (enum AVPacketSideDataType type)
Definition at line 354 of file avpacket.c.
Referenced by print_pkt_side_data(), and setup_side_data_entry().
av_packet_pack_dictionary()
uint8_t* av_packet_pack_dictionary (AVDictionary * dict, int * size)
Pack a dictionary for use in side_data.
Parameters
dict The dictionary to pack.
size pointer to store the size of the returned data
Returns
pointer to data if successful, NULL otherwise
Definition at line 461 of file avpacket.c.
Referenced by concat_read_packet(), and vorbis_update_metadata().
av_packet_unpack_dictionary()
int av_packet_unpack_dictionary (const uint8_t * data, int size, AVDictionary ** dict)
Unpack a dictionary from side_data.
Parameters
data data from side_data
size size of the data
dict the metadata storage dictionary
Returns
0 on success, < 0 on failure
Definition at line 496 of file avpacket.c.
Referenced by add_metadata_from_side_data(), and show_packet().
av_packet_free_side_data()
void av_packet_free_side_data (AVPacket * pkt)
Convenience function to free all the side data stored.
All the other fields stay untouched.
Parameters
pkt packet
Definition at line 270 of file avpacket.c.
Referenced by av_free_packet(), av_packet_copy_props(), av_packet_ref(), av_packet_unref(), avcodec_decode_audio4(), avcodec_decode_subtitle2(), avcodec_decode_video2(), and avcodec_send_packet().
av_packet_ref()
int av_packet_ref (AVPacket * dst, const AVPacket * src)
Setup a new reference to the data described by a given packet.
If src is reference-counted, setup dst as a new reference to the buffer in src. Otherwise allocate a new buffer in dst and copy the data from src into it.
All the other fields are copied from src.
See also
av_packet_unref
Parameters
dst Destination packet
src Source packet
Returns
0 on success, a negative AVERROR on error.
Definition at line 578 of file avpacket.c.
Referenced by add_to_pktbuf(), av_packet_clone(), crystalhd_decode_packet(), do_decode(), ff_interleave_add_packet(), ff_read_packet(), ffat_decode(), fifo_write_packet(), mediacodec_decode_frame(), mkv_write_packet(), qsv_decode_frame(), submit_packet(), svc_decode_frame(), and tee_write_packet().
av_packet_unref()
void av_packet_unref (AVPacket * pkt)
Wipe the packet.
Unreference the buffer referenced by the packet and reset the remaining packet fields to their default values.
Parameters
pkt The packet to be unreferenced.
Examples:
decoding_encoding.c, demuxing_decoding.c, filtering_audio.c, filtering_video.c, qsvdec.c, remuxing.c, transcode_aac.c, and transcoding.c.
Definition at line 569 of file avpacket.c.
Referenced by adp_read_packet(), adx_read_packet(), aiff_write_trailer(), amr_read_packet(), ape_read_packet(), append_packet_chunked(), asf_deinterleave(), asf_parse_packet(), asf_read_close(), asf_read_header(), asf_read_picture(), asf_read_pts(), asf_read_timestamp(), asf_reset_header(), asfrtp_parse_packet(), audio_encode_example(), audio_read_packet(), av_bitstream_filter_filter(), av_copy_packet_side_data(), av_interleaved_write_frame(), av_packet_alloc(), av_packet_free(), av_packet_merge_side_data(), av_read_frame(), av_write_trailer(), avcodec_decode_subtitle2(), avcodec_encode_audio2(), avcodec_encode_video2(), avcodec_flush_buffers(), avcodec_receive_frame(), avcodec_receive_packet(), avformat_find_stream_info(), avi_read_close(), avi_read_packet(), avisynth_read_packet_audio(), avisynth_read_packet_video(), avpacket_queue_flush(), avs_read_video_packet(), bsf_list_filter(), cdxl_read_packet(), check_keyboard_interaction(), cin_read_packet(), compute_crc_of_packets(), concat_read_packet(), copy_packet_data(), crystalhd_decode_packet(), decode_audio_frame(), decode_frame(), decoder_decode_frame(), decoder_destroy(), dfa_read_packet(), do_decode(), do_encode(), drop_dups(), dshow_read_close(), dss_723_1_read_packet(), dss_sp_read_packet(), dump_extradata(), dxa_read_packet(), ea_read_packet(), encode_audio_frame(), encode_frame(), encode_picture_ls(), estimate_timings_from_pts(), failing_write_packet(), ff_frame_thread_free(), ff_img_read_packet(), ff_interleave_add_packet(), ff_interleave_packet_per_dts(), ff_load_image(), ff_qsv_enc_close(), ff_qsv_encode(), ff_raw_read_partial_packet(), ff_read_packet(), ff_rm_free_rmstream(), ff_spdif_read_packet(), ff_stream_add_bitstream_filter(), ff_subtitles_queue_clean(), ffat_close_decoder(), ffat_decode(), ffat_decode_callback(), ffat_decode_flush(), ffm_read_packet(), ffmpeg_cleanup(), fifo_basic_test(), fifo_overflow_drop_test(), fifo_thread_recover(), fifo_thread_write_packet(), fifo_write_header_err_tst(), fifo_write_packet(), filter_packet(), find_video_stream_info(), flac_read_timestamp(), flic_read_packet(), flush(), flush_encoders(), flush_packet(), flv_read_packet(), fourxm_read_packet(), free_message(), free_packet_buffer(), free_pkt_fifo(), free_playlist_list(), free_stream(), g723_1_read_packet(), gsm_read_packet(), h264_mp4toannexb_filter(), hevc_mp4toannexb_filter(), hls_read_packet(), hls_read_seek(), hnm_read_close(), http_prepare_data(), idcin_read_packet(), ilbc_read_packet(), imx_dump_header(), interleave_packet(), lavfi_read_packet(), libopus_encode(), load_ipmovie_packet(), lxf_read_packet(), main(), matroska_clear_queue(), matroska_parse_frame(), mediacodec_decode_close(), mediacodec_decode_flush(), mediacodec_decode_frame(), mjpeg2jpeg_filter(), mjpega_dump_header(), mkv_write_packet(), mkv_write_trailer(), mmap_read_frame(), modplug_read_packet(), mov2textsub(), mov_write_eac3_tag(), mov_write_subtitle_end_packet(), movie_push_frame(), mp3_queue_flush(), mp3lame_encode_frame(), mpa_robust_parse_packet(), mpc_read_packet(), mpc_read_seek(), mpeg4_unpack_bframes_filter(), mpegts_get_dts(), mpegts_raw_read_packet(), mpegts_read_packet(), mpjpeg_read_packet(), mxf_interleave_get_packet(), nc_read_packet(), noise(), nsv_read_close(), nuv_packet(), ogg_read_packet(), packet_queue_flush(), packet_queue_put(), parse_packet(), process_input(), qsv_clear_buffers(), qsv_decode_frame(), qt_rtp_parse_packet(), read_frame_internal(), read_interval_packets(), read_packet(), read_thread(), recode_subtitle(), redspark_read_packet(), reset_packet(), reset_packet_state(), rl2_read_packet(), rm_assemble_video_frame(), rm_read_packet(), roq_read_packet(), rpl_read_packet(), run_test(), sap_fetch_packet(), sdr2_read_packet(), seek_frame_generic(), seek_subtitle(), siff_read_packet(), storeframe(), str_read_close(), str_read_packet(), submit_packet(), svc_decode_close(), svc_decode_frame(), swf_read_packet(), text2movsub(), thp_read_packet(), tta_encode_frame(), vfw_read_close(), video_decode(), video_decode_example(), video_encode_example(), vivo_read_packet(), vmd_read_packet(), vp9_superframe_filter(), vpk_read_packet(), vqf_read_packet(), vtenc_frame(), wc3_read_close(), write_packet(), write_trailer(), wv_read_packet(), xiph_handle_packet(), xvid_encode_frame(), xvid_encode_init(), yop_read_close(), yop_read_packet(), yop_read_seek(), and yuv4_read_packet().
av_packet_move_ref()
void av_packet_move_ref (AVPacket * dst, AVPacket * src)
Move every field in src to dst and reset src.
See also
av_packet_unref
Parameters
src Source packet, will be reset
dst Destination packet
Definition at line 624 of file avpacket.c.
Referenced by aac_adtstoasc_filter(), asf_read_packet(), av_bsf_send_packet(), avcodec_receive_packet(), chomp_filter(), dca_core_filter(), dump_extradata(), ff_bsf_get_packet_ref(), ffat_decode_callback(), h264_mp4toannexb_filter(), hevc_mp4toannexb_filter(), mediacodec_decode_frame(), mjpega_dump_header(), mp3_header_decompress(), mpeg4_unpack_bframes_filter(), qsv_decode_frame(), remove_extradata(), svc_decode_frame(), vp9_superframe_filter(), and write_packet().
av_packet_copy_props()
int av_packet_copy_props (AVPacket * dst, const AVPacket * src)
Copy only "properties" fields from src to dst.
Properties for the purpose of this function are all the fields beside those related to the packet data (buf, data, size)
Parameters
dst Destination packet
src Source packet
Returns
0 on success AVERROR on failure.
Definition at line 537 of file avpacket.c.
Referenced by av_packet_ref(), dump_extradata(), ff_qsv_encode(), ff_reshuffle_raw_rgb(), h264_mp4toannexb_filter(), hevc_mp4toannexb_filter(), imx_dump_header(), mjpeg2jpeg_filter(), mjpega_dump_header(), mov2textsub(), mp3_header_decompress(), mpeg4_unpack_bframes_filter(), noise(), text2movsub(), and vp9_superframe_filter().
av_packet_rescale_ts()
void av_packet_rescale_ts (AVPacket * pkt, AVRational tb_src, AVRational tb_dst)
Convert valid timing fields (timestamps / durations) in a packet from one timebase to another.
Timestamps with unknown values (AV_NOPTS_VALUE) will be ignored.
Parameters
pkt packet on which the conversion will be performed
tb_src source timebase, in which the timing fields in pkt are expressed
tb_dst destination timebase, to which the timing fields will be converted
Examples:
muxing.c, and transcoding.c.
Definition at line 632 of file avpacket.c.
Referenced by do_audio_out(), do_video_out(), encode_write_frame(), fifo_thread_write_packet(), flush_encoders(), main(), tee_write_packet(), and write_frame().