FFmpeg: Base64
Base64
libavutil » Crypto and Hashing
Macros
#define AV_BASE64_DECODE_SIZE(x) ((x) * 3LL / 4)
Calculate the output size in bytes needed to decode a base64 string with length x to a data buffer.
#define AV_BASE64_SIZE(x) (((x)+2) / 3 * 4 + 1)
Calculate the output size needed to base64-encode x bytes to a null-terminated string.
Functions
int av_base64_decode (uint8_t *out, const char *in, int out_size)
Decode a base64-encoded string.
char * av_base64_encode (char *out, int out_size, const uint8_t *in, int in_size)
Encode data to base64 and null-terminate.
Detailed Description
Macro Definition Documentation
AV_BASE64_DECODE_SIZE
#define AV_BASE64_DECODE_SIZE (x) ((x) * 3LL / 4)
Calculate the output size in bytes needed to decode a base64 string with length x to a data buffer.
Definition at line 48 of file base64.h.
Referenced by ff_vorbis_comment().
AV_BASE64_SIZE
#define AV_BASE64_SIZE (x) (((x)+2) / 3 * 4 + 1)
Calculate the output size needed to base64-encode x bytes to a null-terminated string.
Definition at line 66 of file base64.h.
Referenced by av_base64_encode(), av_hash_final_b64(), do_adobe_auth(), ff_http_auth_create_response(), ff_rtsp_open_transport_ctx(), get_stats(), matroska_parse_tracks(), vpx_encode(), and write_manifest().
Function Documentation
av_base64_decode()
int av_base64_decode (uint8_t * out, const char * in, int out_size)
Decode a base64-encoded string.
Parameters
out buffer for decoded data
in null-terminated input string
out_size size in bytes of the out buffer, must be at least 3/4 of the length of in, that is AV_BASE64_DECODE_SIZE(strlen(in))
Returns
number of bytes written, or a negative value in case of invalid input
Definition at line 79 of file base64.c.
Referenced by data_open(), ff_h264_parse_sprop_parameter_sets(), ff_srtp_set_crypto(), ff_vorbis_comment(), ff_wms_parse_sdp_a_line(), main(), rdt_parse_b64buf(), submit_stats(), test_encode_decode(), vpx_init(), and xiph_parse_fmtp_pair().
av_base64_encode()
char* av_base64_encode (char * out, int out_size, const uint8_t * in, int in_size)
Encode data to base64 and null-terminate.
Parameters
out buffer for encoded data
out_size size in bytes of the out buffer (including the null terminator), must be at least AV_BASE64_SIZE(in_size)
in input buffer containing the data to encode
in_size size in bytes of the in buffer
Returns
out or NULL in case of error
Definition at line 138 of file base64.c.
Referenced by av_hash_final_b64(), do_adobe_auth(), ff_http_auth_create_response(), ff_rtsp_open_transport_ctx(), get_stats(), main(), matroska_parse_tracks(), test_encode_decode(), vpx_encode(), and write_manifest().