FFmpeg: Other
Other
libavutil
Modules
Preprocessor String Macros
String manipulation macros.
Library Version Macros
Useful to check and match library version in order to maintain backward compatibility.
Constants
Image related
AVPicture types, pixel formats and basic image planes manipulation.
Version and Build diagnostics
Macros and function useful to check at compiletime and at runtime which version of libavutil is in use.
Media Type
Media Type.
Macros
#define av_int_list_length(list, term) av_int_list_length_for_size(sizeof(*(list)), list, term)
Compute the length of an integer list.
Enumerations
enum AVMediaType {
AVMEDIA_TYPE_UNKNOWN = -1, AVMEDIA_TYPE_VIDEO, AVMEDIA_TYPE_AUDIO, AVMEDIA_TYPE_DATA,
AVMEDIA_TYPE_SUBTITLE, AVMEDIA_TYPE_ATTACHMENT, AVMEDIA_TYPE_NB
}
Functions
const char * av_get_media_type_string (enum AVMediaType media_type)
Return a string describing the media_type enum, NULL if media_type is unknown.
static void * av_x_if_null (const void *p, const void *x)
Return x default pointer in case p is NULL.
unsigned av_int_list_length_for_size (unsigned elsize, const void *list, uint64_t term) av_pure
Compute the length of an integer list.
FILE * av_fopen_utf8 (const char *path, const char *mode)
Open a file using a UTF-8 filename.
AVRational av_get_time_base_q (void)
Return the fractional representation of the internal time base.
Detailed Description
Macro Definition Documentation
av_int_list_length
#define av_int_list_length (list, term) av_int_list_length_for_size(sizeof(*(list)), list, term)
Compute the length of an integer list.
Parameters
term list terminator (usually 0 or -1)
list pointer to the list
Returns
length of the list, in elements, not counting the terminator
Definition at line 331 of file avutil.h.
Enumeration Type Documentation
AVMediaType
enum AVMediaType
Enumerator
AVMEDIA_TYPE_UNKNOWN
Usually treated as AVMEDIA_TYPE_DATA.
AVMEDIA_TYPE_VIDEO
AVMEDIA_TYPE_AUDIO
AVMEDIA_TYPE_DATA
Opaque data information usually continuous.
AVMEDIA_TYPE_SUBTITLE
AVMEDIA_TYPE_ATTACHMENT
Opaque data information usually sparse.
AVMEDIA_TYPE_NB
Definition at line 199 of file avutil.h.
Function Documentation
av_get_media_type_string()
const char* av_get_media_type_string (enum AVMediaType media_type)
Return a string describing the media_type enum, NULL if media_type is unknown.
Examples:
demuxing_decoding.c.
Definition at line 79 of file utils.c.
Referenced by avcodec_string(), avfilter_link(), avi_write_header(), check_streamcopy_filters(), describe_frame_to_str(), ff_framehash_write_header(), find_stream(), flv_read_packet(), flv_write_header(), graph_check_validity(), log_slave(), mpeg_mux_init(), mxf_add_metadata_stream(), open_codec_context(), open_output_file(), process_input(), read_thread(), report_new_stream(), seg_init(), show_frame(), show_packet(), show_stream(), stream_cycle_channel(), write_frame(), and write_packet().
av_x_if_null()
static void* av_x_if_null (const void * p, const void * x) inline static
Return x default pointer in case p is NULL.
Examples:
filtering_audio.c.
Definition at line 308 of file avutil.h.
Referenced by av_opt_get(), avcodec_open2(), avfilter_link(), avi_write_header(), compact_print_section_header(), data_open(), default_print_section_header(), device_try_init(), filter_frame(), ftp_connect(), init(), init_dict(), init_filters(), init_report(), init_video(), match_section(), opt_list(), parse_script(), print_link_prop(), and video_thread().
av_int_list_length_for_size()
unsigned av_int_list_length_for_size (unsigned elsize, const void * list, uint64_t term)
Compute the length of an integer list.
Parameters
elsize size in bytes of each list element (only 1, 2, 4 or 8)
term list terminator (usually 0 or -1)
list pointer to the list
Returns
length of the list, in elements, not counting the terminator
Definition at line 105 of file utils.c.
Referenced by av_x_if_null().
av_fopen_utf8()
FILE* av_fopen_utf8 (const char * path, const char * mode)
Open a file using a UTF-8 filename.
The API of this function matches POSIX fopen(), errors are returned through errno.
Definition at line 154 of file file_open.c.
Referenced by disp_tree(), dump_curves(), and new_video_stream().
av_get_time_base_q()
AVRational av_get_time_base_q (void)
Return the fractional representation of the internal time base.
Definition at line 124 of file utils.c.