FFmpeg: Audio FIFO Buffer
Audio FIFO Buffer
libavutil » Audio related
Functions
void av_audio_fifo_free (AVAudioFifo *af)
Free an AVAudioFifo.
AVAudioFifo * av_audio_fifo_alloc (enum AVSampleFormat sample_fmt, int channels, int nb_samples)
Allocate an AVAudioFifo.
av_warn_unused_result int av_audio_fifo_realloc (AVAudioFifo *af, int nb_samples)
Reallocate an AVAudioFifo.
int av_audio_fifo_write (AVAudioFifo *af, void **data, int nb_samples)
Write data to an AVAudioFifo.
int av_audio_fifo_peek (AVAudioFifo *af, void **data, int nb_samples)
Peek data from an AVAudioFifo.
int av_audio_fifo_peek_at (AVAudioFifo *af, void **data, int nb_samples, int offset)
Peek data from an AVAudioFifo.
int av_audio_fifo_read (AVAudioFifo *af, void **data, int nb_samples)
Read data from an AVAudioFifo.
int av_audio_fifo_drain (AVAudioFifo *af, int nb_samples)
Drain data from an AVAudioFifo.
void av_audio_fifo_reset (AVAudioFifo *af)
Reset the AVAudioFifo buffer.
int av_audio_fifo_size (AVAudioFifo *af)
Get the current number of samples in the AVAudioFifo available for reading.
int av_audio_fifo_space (AVAudioFifo *af)
Get the current number of samples in the AVAudioFifo available for writing.
Detailed Description
Function Documentation
av_audio_fifo_free()
void av_audio_fifo_free (AVAudioFifo * af)
Free an AVAudioFifo.
Parameters
af AVAudioFifo to free
Definition at line 45 of file audio_fifo.c.
Referenced by av_audio_fifo_alloc(), avresample_close(), compressor(), config_output(), gate(), main(), opus_decode_close(), test_function(), and uninit().
av_audio_fifo_alloc()
AVAudioFifo* av_audio_fifo_alloc (enum AVSampleFormat sample_fmt, int channels, int nb_samples)
Allocate an AVAudioFifo.
Parameters
sample_fmt sample format
channels number of channels
nb_samples initial allocation size, in samples
Returns
newly allocated AVAudioFifo, or NULL on error
Definition at line 59 of file audio_fifo.c.
Referenced by av_buffersink_get_samples(), avresample_open(), compressor(), config_input(), config_output(), config_props_output(), gate(), init_fifo(), opus_decode_init(), and test_function().
av_audio_fifo_realloc()
av_warn_unused_result int av_audio_fifo_realloc (AVAudioFifo * af, int nb_samples)
Reallocate an AVAudioFifo.
Parameters
af AVAudioFifo to reallocate
nb_samples new allocation size, in samples
Returns
0 if OK, or negative AVERROR code on failure
Definition at line 96 of file audio_fifo.c.
Referenced by add_samples_to_fifo(), av_audio_fifo_write(), and filter_frame().
av_audio_fifo_write()
int av_audio_fifo_write (AVAudioFifo * af, void ** data, int nb_samples)
Write data to an AVAudioFifo.
The AVAudioFifo will be reallocated automatically if the available space is less than nb_samples.
See also
enum AVSampleFormat The documentation for AVSampleFormat describes the data layout.
Parameters
af AVAudioFifo to write to
data audio data plane pointers
nb_samples number of samples to write
Returns
number of samples actually written, or negative AVERROR code on failure. If successful, the number of samples actually written will always be nb_samples.
Definition at line 112 of file audio_fifo.c.
Referenced by add_samples_to_fifo(), av_buffersink_get_samples(), compressor(), config_output(), ff_audio_data_add_to_fifo(), filter_frame(), gate(), opus_decode_frame(), opus_decode_packet(), plot_spectrum_column(), and write_samples_to_audio_fifo().
av_audio_fifo_peek()
int av_audio_fifo_peek (AVAudioFifo * af, void ** data, int nb_samples)
Peek data from an AVAudioFifo.
See also
enum AVSampleFormat The documentation for AVSampleFormat describes the data layout.
Parameters
af AVAudioFifo to read from
data audio data plane pointers
nb_samples number of samples to peek
Returns
number of samples actually peek, or negative AVERROR code on failure. The number of samples actually peek will not be greater than nb_samples, and will only be less than nb_samples if av_audio_fifo_size is less than nb_samples.
Definition at line 138 of file audio_fifo.c.
Referenced by filter_frame(), plot_spectrum_column(), and test_function().
av_audio_fifo_peek_at()
int av_audio_fifo_peek_at (AVAudioFifo * af, void ** data, int nb_samples, int offset)
Peek data from an AVAudioFifo.
See also
enum AVSampleFormat The documentation for AVSampleFormat describes the data layout.
Parameters
af AVAudioFifo to read from
data audio data plane pointers
nb_samples number of samples to peek
offset offset from current read position
Returns
number of samples actually peek, or negative AVERROR code on failure. The number of samples actually peek will not be greater than nb_samples, and will only be less than nb_samples if av_audio_fifo_size is less than nb_samples.
Definition at line 157 of file audio_fifo.c.
Referenced by test_function().
av_audio_fifo_read()
int av_audio_fifo_read (AVAudioFifo * af, void ** data, int nb_samples)
Read data from an AVAudioFifo.
See also
enum AVSampleFormat The documentation for AVSampleFormat describes the data layout.
Parameters
af AVAudioFifo to read from
data audio data plane pointers
nb_samples number of samples to read
Returns
number of samples actually read, or negative AVERROR code on failure. The number of samples actually read will not be greater than nb_samples, and will only be less than nb_samples if av_audio_fifo_size is less than nb_samples.
Definition at line 181 of file audio_fifo.c.
Referenced by avresample_read(), compressor(), config_output(), ff_audio_data_read_from_fifo(), gate(), load_encode_and_write(), opus_decode_frame(), opus_decode_packet(), opus_flush_resample(), output_frame(), push_samples(), read_from_fifo(), and read_samples_from_audio_fifo().
av_audio_fifo_drain()
int av_audio_fifo_drain (AVAudioFifo * af, int nb_samples)
Drain data from an AVAudioFifo.
Removes the data without reading it.
Parameters
af AVAudioFifo to drain
nb_samples number of samples to drain
Returns
0 if OK, or negative AVERROR code on failure
Definition at line 201 of file audio_fifo.c.
Referenced by avresample_read(), filter_frame(), opus_decode_flush(), opus_decode_frame(), plot_spectrum_column(), and test_function().
av_audio_fifo_reset()
void av_audio_fifo_reset (AVAudioFifo * af)
Reset the AVAudioFifo buffer.
This empties all data in the buffer.
Parameters
af AVAudioFifo to reset
Definition at line 218 of file audio_fifo.c.
av_audio_fifo_size()
int av_audio_fifo_size (AVAudioFifo * af)
Get the current number of samples in the AVAudioFifo available for reading.
Parameters
af the AVAudioFifo to query
Returns
number of samples available for reading
Definition at line 228 of file audio_fifo.c.
Referenced by add_samples_to_fifo(), av_audio_fifo_write(), av_buffersink_get_samples(), avresample_available(), avresample_convert(), compressor(), config_output(), filter_frame(), gate(), handle_buffered_output(), load_encode_and_write(), main(), opus_decode_flush(), opus_decode_frame(), opus_decode_packet(), opus_flush_resample(), output_frame(), plot_spectrum_column(), push_samples(), request_samples(), and test_function().
av_audio_fifo_space()
int av_audio_fifo_space (AVAudioFifo * af)
Get the current number of samples in the AVAudioFifo available for writing.
Parameters
af the AVAudioFifo to query
Returns
number of samples available for writing
Definition at line 233 of file audio_fifo.c.
Referenced by av_audio_fifo_write(), and filter_frame().