FFmpeg: libavcodec/gsmdec_template.c File Reference
gsmdec_template.c File Reference
GSM decoder.
#include "get_bits.h"
#include "gsm.h"
#include "gsmdec_data.h"
Functions
static void apcm_dequant_add (GetBitContext *gb, int16_t *dst, const int *frame_bits)
static int gsm_mult (int a, int b)
static void long_term_synth (int16_t *dst, int lag, int gain_idx)
static int decode_log_area (int coded, int factor, int offset)
static av_noinline int get_rrp (int filtered)
static int filter_value (int in, int rrp[8], int v[9])
static void short_term_synth (GSMContext *ctx, int16_t *dst, const int16_t *src)
static int postprocess (int16_t *data, int msr)
static int gsm_decode_block (AVCodecContext *avctx, int16_t *samples, GetBitContext *gb, int mode)
Detailed Description
GSM decoder.
Definition in file gsmdec_template.c.
Function Documentation
apcm_dequant_add()
static void apcm_dequant_add (GetBitContext * gb, int16_t * dst, const int * frame_bits) static
Definition at line 31 of file gsmdec_template.c.
Referenced by gsm_decode_block().
gsm_mult()
static int gsm_mult (int a, int b) inline static
Definition at line 42 of file gsmdec_template.c.
Referenced by decode_log_area(), filter_value(), long_term_synth(), and postprocess().
long_term_synth()
static void long_term_synth (int16_t * dst, int lag, int gain_idx) static
Definition at line 47 of file gsmdec_template.c.
Referenced by gsm_decode_block().
decode_log_area()
static int decode_log_area (int coded, int factor, int offset) inline static
Definition at line 56 of file gsmdec_template.c.
Referenced by gsm_decode_block().
get_rrp()
static av_noinline int get_rrp (int filtered) static
Definition at line 63 of file gsmdec_template.c.
Referenced by short_term_synth().
filter_value()
static int filter_value (int in, int rrp[8], int v[9]) static
Definition at line 72 of file gsmdec_template.c.
Referenced by short_term_synth(), vp3_h_loop_filter_c(), and vp3_v_loop_filter_c().
short_term_synth()
static void short_term_synth (GSMContext * ctx, int16_t * dst, const int16_t * src) static
Definition at line 83 of file gsmdec_template.c.
Referenced by gsm_decode_block().
postprocess()
static int postprocess (int16_t * data, int msr) static
Definition at line 112 of file gsmdec_template.c.
Referenced by gsm_decode_block().
gsm_decode_block()
static int gsm_decode_block (AVCodecContext * avctx, int16_t * samples, GetBitContext * gb, int mode) static
Definition at line 122 of file gsmdec_template.c.
Referenced by ff_msgsm_decode_block(), and gsm_decode_frame().