FFmpeg: libavcodec/h261.h File Reference
h261.h File Reference
H.261 codec.
#include "mpegvideo.h"
#include "rl.h"
Data Structures
struct H261Context
H261Context.
Macros
#define MB_TYPE_H261_FIL 0x800000
Functions
void ff_h261_loop_filter (MpegEncContext *s)
void ff_h261_common_init (void)
int ff_h261_get_picture_format (int width, int height)
void ff_h261_reorder_mb_index (MpegEncContext *s)
void ff_h261_encode_mb (MpegEncContext *s, int16_t block[6][64], int motion_x, int motion_y)
void ff_h261_encode_picture_header (MpegEncContext *s, int picture_number)
void ff_h261_encode_init (MpegEncContext *s)
Variables
uint8_t ff_h261_rl_table_store [2][2 *MAX_RUN+MAX_LEVEL+3]
const uint8_t ff_h261_mba_code [35]
const uint8_t ff_h261_mba_bits [35]
const uint8_t ff_h261_mtype_code [10]
const uint8_t ff_h261_mtype_bits [10]
const int ff_h261_mtype_map [10]
const uint8_t ff_h261_mv_tab [17][2]
const uint8_t ff_h261_cbp_tab [63][2]
RLTable ff_h261_rl_tcoeff
Detailed Description
H.261 codec.
Definition in file h261.h.
Macro Definition Documentation
MB_TYPE_H261_FIL
#define MB_TYPE_H261_FIL 0x800000
Definition at line 49 of file h261.h.
Referenced by h261_decode_mb_skipped().
Function Documentation
ff_h261_loop_filter()
void ff_h261_loop_filter (MpegEncContext * s)
Definition at line 63 of file h261.c.
Referenced by mpeg_motion_internal().
ff_h261_common_init()
void ff_h261_common_init (void)
Definition at line 83 of file h261.c.
Referenced by ff_h261_encode_init(), and h261_decode_init().
ff_h261_get_picture_format()
int ff_h261_get_picture_format (int width, int height)
Definition at line 40 of file h261enc.c.
Referenced by ff_h261_encode_picture_header(), ff_h261_reorder_mb_index(), ff_mpv_encode_init(), and h261_encode_gob_header().
ff_h261_reorder_mb_index()
void ff_h261_reorder_mb_index (MpegEncContext * s)
Definition at line 108 of file h261enc.c.
Referenced by encode_thread().
ff_h261_encode_mb()
void ff_h261_encode_mb (MpegEncContext * s, int16_t block[6][64], int motion_x, int motion_y)
Definition at line 237 of file h261enc.c.
Referenced by encode_mb_internal().
ff_h261_encode_picture_header()
void ff_h261_encode_picture_header (MpegEncContext * s, int picture_number)
Definition at line 53 of file h261enc.c.
Referenced by encode_picture().
ff_h261_encode_init()
void ff_h261_encode_init (MpegEncContext * s)
Definition at line 365 of file h261enc.c.
Referenced by ff_mpv_encode_init().
Variable Documentation
ff_h261_rl_table_store
uint8_t ff_h261_rl_table_store[2][2 *MAX_RUN+MAX_LEVEL+3]
Definition at line 33 of file h261.c.
Referenced by ff_h261_common_init().
ff_h261_mba_code
const uint8_t ff_h261_mba_code[35]
Definition at line 34 of file h261data.c.
Referenced by ff_h261_encode_mb(), and h261_decode_init_vlc().
ff_h261_mba_bits
const uint8_t ff_h261_mba_bits[35]
Definition at line 48 of file h261data.c.
Referenced by ff_h261_encode_mb(), and h261_decode_init_vlc().
ff_h261_mtype_code
const uint8_t ff_h261_mtype_code[10]
Definition at line 63 of file h261data.c.
Referenced by ff_h261_encode_mb(), and h261_decode_init_vlc().
ff_h261_mtype_bits
const uint8_t ff_h261_mtype_bits[10]
Definition at line 69 of file h261data.c.
Referenced by ff_h261_encode_mb(), and h261_decode_init_vlc().
ff_h261_mtype_map
const int ff_h261_mtype_map[10]
Definition at line 75 of file h261data.c.
Referenced by ff_h261_encode_mb(), and h261_decode_mb().
ff_h261_mv_tab
const uint8_t ff_h261_mv_tab[17][2]
Definition at line 89 of file h261data.c.
Referenced by h261_decode_init_vlc(), and h261_encode_motion().
ff_h261_cbp_tab
const uint8_t ff_h261_cbp_tab[63][2]
Definition at line 95 of file h261data.c.
Referenced by ff_h261_encode_mb(), and h261_decode_init_vlc().
ff_h261_rl_tcoeff
RLTable ff_h261_rl_tcoeff
Definition at line 150 of file h261data.c.
Referenced by ff_h261_common_init(), ff_h261_encode_init(), h261_decode_block(), h261_decode_init_vlc(), and h261_encode_block().