FFmpeg: libavcodec/h261.c File Reference
h261.c File Reference
H.261 codec.
#include "avcodec.h"
#include "h261.h"
Macros
#define IS_FIL(a) ((a) & MB_TYPE_H261_FIL)
Functions
static void h261_loop_filter (uint8_t *src, int stride)
void ff_h261_loop_filter (MpegEncContext *s)
av_cold void ff_h261_common_init (void)
Variables
uint8_t ff_h261_rl_table_store [2][2 *MAX_RUN+MAX_LEVEL+3]
Detailed Description
H.261 codec.
Definition in file h261.c.
Macro Definition Documentation
IS_FIL
#define IS_FIL (a) ((a) & MB_TYPE_H261_FIL)
Definition at line 31 of file h261.c.
Referenced by ff_h261_loop_filter().
Function Documentation
h261_loop_filter()
static void h261_loop_filter (uint8_t * src, int stride) static
Definition at line 35 of file h261.c.
Referenced by ff_h261_loop_filter().
ff_h261_loop_filter()
void ff_h261_loop_filter (MpegEncContext * s)
Definition at line 63 of file h261.c.
Referenced by mpeg_motion_internal().
ff_h261_common_init()
av_cold void ff_h261_common_init (void)
Definition at line 83 of file h261.c.
Referenced by ff_h261_encode_init(), and h261_decode_init().
Variable Documentation
ff_h261_rl_table_store
uint8_t ff_h261_rl_table_store[2][2 *MAX_RUN+MAX_LEVEL+3]
Definition at line 33 of file h261.c.
Referenced by ff_h261_common_init().