FFmpeg: libavcodec/h261enc.c File Reference
h261enc.c File Reference
H.261 encoder.
#include "libavutil/attributes.h"
#include "libavutil/avassert.h"
#include "avcodec.h"
#include "mpegutils.h"
#include "mpegvideo.h"
#include "h263.h"
#include "h261.h"
#include "mpegvideodata.h"
Macros
#define UNI_ENC_INDEX(last, run, level) ((last)*128*64 + (run)*128 + (level))
Functions
int ff_h261_get_picture_format (int width, int height)
void ff_h261_encode_picture_header (MpegEncContext *s, int picture_number)
static void h261_encode_gob_header (MpegEncContext *s, int mb_line)
Encode a group of blocks header.
void ff_h261_reorder_mb_index (MpegEncContext *s)
static void h261_encode_motion (H261Context *h, int val)
static int get_cbp (MpegEncContext *s, int16_t block[6][64])
static void h261_encode_block (H261Context *h, int16_t *block, int n)
Encode an 8x8 block.
void ff_h261_encode_mb (MpegEncContext *s, int16_t block[6][64], int motion_x, int motion_y)
static av_cold void init_uni_h261_rl_tab (RLTable *rl, uint32_t *bits_tab, uint8_t *len_tab)
av_cold void ff_h261_encode_init (MpegEncContext *s)
Variables
static uint8_t uni_h261_rl_len [64 *64 *2 *2]
static const AVClass h261_class
AVCodec ff_h261_encoder
Detailed Description
H.261 encoder.
Definition in file h261enc.c.
Macro Definition Documentation
UNI_ENC_INDEX
#define UNI_ENC_INDEX (last, run, level) ((last)*128*64 + (run)*128 + (level))
Definition at line 38 of file h261enc.c.
Referenced by init_uni_h261_rl_tab().
Function Documentation
ff_h261_get_picture_format()
int ff_h261_get_picture_format (int width, int height)
Definition at line 40 of file h261enc.c.
Referenced by ff_h261_encode_picture_header(), ff_h261_reorder_mb_index(), ff_mpv_encode_init(), and h261_encode_gob_header().
ff_h261_encode_picture_header()
void ff_h261_encode_picture_header (MpegEncContext * s, int picture_number)
Definition at line 53 of file h261enc.c.
Referenced by encode_picture().
h261_encode_gob_header()
static void h261_encode_gob_header (MpegEncContext * s, int mb_line) static
Encode a group of blocks header.
Definition at line 91 of file h261enc.c.
Referenced by ff_h261_reorder_mb_index().
ff_h261_reorder_mb_index()
void ff_h261_reorder_mb_index (MpegEncContext * s)
Definition at line 108 of file h261enc.c.
Referenced by encode_thread().
h261_encode_motion()
static void h261_encode_motion (H261Context * h, int val) static
Definition at line 135 of file h261enc.c.
Referenced by ff_h261_encode_mb().
get_cbp()
static int get_cbp (MpegEncContext * s, int16_t block[6][64]) inline static
Definition at line 154 of file h261enc.c.
Referenced by ff_h261_encode_mb().
h261_encode_block()
static void h261_encode_block (H261Context * h, int16_t * block, int n) static
Encode an 8x8 block.
Parameters
block the 8x8 block
n block index (0-3 are luma, 4-5 are chroma)
Definition at line 169 of file h261enc.c.
Referenced by ff_h261_encode_mb().
ff_h261_encode_mb()
void ff_h261_encode_mb (MpegEncContext * s, int16_t block[6][64], int motion_x, int motion_y)
Definition at line 237 of file h261enc.c.
Referenced by encode_mb_internal().
init_uni_h261_rl_tab()
static av_cold void init_uni_h261_rl_tab (RLTable * rl, uint32_t * bits_tab, uint8_t * len_tab) static
Definition at line 325 of file h261enc.c.
Referenced by ff_h261_encode_init().
ff_h261_encode_init()
av_cold void ff_h261_encode_init (MpegEncContext * s)
Definition at line 365 of file h261enc.c.
Referenced by ff_mpv_encode_init().
Variable Documentation
uni_h261_rl_len
uint8_t uni_h261_rl_len[64 *64 *2 *2] static
Definition at line 37 of file h261enc.c.
Referenced by ff_h261_encode_init().
h261_class
const AVClass h261_class static
Initial value:
= {
    .class_name = "h261 encoder",
    .item_name  = av_default_item_name,
    .option     = ff_mpv_generic_options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 381 of file h261enc.c.
ff_h261_encoder
AVCodec ff_h261_encoder
Initial value:
= {
    .name           = "h261",
    .long_name      = NULL_IF_CONFIG_SMALL("H.261"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_H261,
    .priv_data_size = sizeof(H261Context),
    .init           = ff_mpv_encode_init,
    .encode2        = ff_mpv_encode_picture,
    .close          = ff_mpv_encode_end,
    .pix_fmts       = (const enum AVPixelFormat[]) { AV_PIX_FMT_YUV420P,
                                                     AV_PIX_FMT_NONE },
    .priv_class     = &h261_class,
}
Definition at line 388 of file h261enc.c.