FFmpeg: libavcodec/x86/h263dsp_init.c File Reference
h263dsp_init.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/x86/cpu.h"
#include "libavcodec/h263dsp.h"
Functions
void ff_h263_h_loop_filter_mmx (uint8_t *src, int stride, int qscale)
void ff_h263_v_loop_filter_mmx (uint8_t *src, int stride, int qscale)
av_cold void ff_h263dsp_init_x86 (H263DSPContext *c)
Function Documentation
ff_h263_h_loop_filter_mmx()
void ff_h263_h_loop_filter_mmx (uint8_t * src, int stride, int qscale)
Referenced by ff_h263dsp_init_x86().
ff_h263_v_loop_filter_mmx()
void ff_h263_v_loop_filter_mmx (uint8_t * src, int stride, int qscale)
Referenced by ff_h263dsp_init_x86().
ff_h263dsp_init_x86()
av_cold void ff_h263dsp_init_x86 (H263DSPContext * c)
Definition at line 31 of file h263dsp_init.c.
Referenced by ff_h263dsp_init().