FFmpeg: libavcodec/h263.c File Reference
h263.c File Reference
H.263/MPEG-4 codec.
#include <limits.h>
#include "avcodec.h"
#include "mpegvideo.h"
#include "h263.h"
#include "h263data.h"
#include "mathops.h"
#include "mpegutils.h"
#include "flv.h"
#include "mpeg4video.h"
Functions
void ff_h263_update_motion_val (MpegEncContext *s)
int ff_h263_pred_dc (MpegEncContext *s, int n, int16_t **dc_val_ptr)
void ff_h263_loop_filter (MpegEncContext *s)
void ff_h263_pred_acdc (MpegEncContext *s, int16_t *block, int n)
int16_t * ff_h263_pred_motion (MpegEncContext *s, int block, int dir, int *px, int *py)
Detailed Description
H.263/MPEG-4 codec.
Definition in file h263.c.
Function Documentation
ff_h263_update_motion_val()
void ff_h263_update_motion_val (MpegEncContext * s)
Definition at line 42 of file h263.c.
Referenced by decode_slice(), encode_thread(), and rv10_decode_packet().
ff_h263_pred_dc()
int ff_h263_pred_dc (MpegEncContext * s, int n, int16_t ** dc_val_ptr)
Definition at line 94 of file h263.c.
Referenced by ff_h263_encode_mb().
ff_h263_loop_filter()
void ff_h263_loop_filter (MpegEncContext * s)
Definition at line 135 of file h263.c.
Referenced by decode_slice(), encode_thread(), and rv10_decode_packet().
ff_h263_pred_acdc()
void ff_h263_pred_acdc (MpegEncContext * s, int16_t * block, int n)
Definition at line 222 of file h263.c.
Referenced by h263_decode_block().
ff_h263_pred_motion()
int16_t* ff_h263_pred_motion (MpegEncContext * s, int block, int dir, int * px, int * py)
Definition at line 309 of file h263.c.
Referenced by ff_h263_decode_mb(), ff_h263_encode_mb(), ff_mpeg4_encode_mb(), ff_msmpeg4_encode_mb(), ff_wmv2_encode_mb(), mpeg4_decode_mb(), mpeg4_decode_partition_a(), msmpeg4v12_decode_mb(), msmpeg4v34_decode_mb(), preview_obmc(), svq1_encode_plane(), and write_mb_info().