FFmpeg: libavcodec/h263dsp.h File Reference
h263dsp.h File Reference
#include <stdint.h>
Data Structures
struct H263DSPContext
Functions
void ff_h263dsp_init (H263DSPContext *ctx)
void ff_h263dsp_init_x86 (H263DSPContext *ctx)
void ff_h263dsp_init_mips (H263DSPContext *ctx)
Variables
const uint8_t ff_h263_loop_filter_strength [32]
Function Documentation
ff_h263dsp_init()
void ff_h263dsp_init (H263DSPContext * ctx)
Definition at line 117 of file h263dsp.c.
Referenced by ff_dct_encode_init(), ff_h263_decode_init(), and rv10_decode_init().
ff_h263dsp_init_x86()
void ff_h263dsp_init_x86 (H263DSPContext * ctx)
Definition at line 31 of file h263dsp_init.c.
Referenced by ff_h263dsp_init().
ff_h263dsp_init_mips()
void ff_h263dsp_init_mips (H263DSPContext * ctx)
Definition at line 31 of file h263dsp_init_mips.c.
Referenced by ff_h263dsp_init().
Variable Documentation
ff_h263_loop_filter_strength
const uint8_t ff_h263_loop_filter_strength[32]
Definition at line 26 of file h263dsp.c.
Referenced by h263_h_loop_filter_c(), and h263_v_loop_filter_c().