FFmpeg: libavcodec/h263dsp.c File Reference
h263dsp.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/common.h"
#include "config.h"
#include "h263dsp.h"
Functions
static void h263_h_loop_filter_c (uint8_t *src, int stride, int qscale)
static void h263_v_loop_filter_c (uint8_t *src, int stride, int qscale)
av_cold void ff_h263dsp_init (H263DSPContext *ctx)
Variables
const uint8_t ff_h263_loop_filter_strength [32]
Function Documentation
h263_h_loop_filter_c()
static void h263_h_loop_filter_c (uint8_t * src, int stride, int qscale) static
Definition at line 31 of file h263dsp.c.
Referenced by ff_h263dsp_init().
h263_v_loop_filter_c()
static void h263_v_loop_filter_c (uint8_t * src, int stride, int qscale) static
Definition at line 74 of file h263dsp.c.
Referenced by ff_h263dsp_init().
ff_h263dsp_init()
av_cold void ff_h263dsp_init (H263DSPContext * ctx)
Definition at line 117 of file h263dsp.c.
Referenced by ff_dct_encode_init(), ff_h263_decode_init(), and rv10_decode_init().
Variable Documentation
ff_h263_loop_filter_strength
const uint8_t ff_h263_loop_filter_strength[32]
Initial value:
= {
    0, 1, 1, 2, 2, 3, 3,  4,  4,  4,  5,  5,  6,  6,  7, 7,
    7, 8, 8, 8, 9, 9, 9, 10, 10, 10, 11, 11, 11, 12, 12, 12
}
Definition at line 26 of file h263dsp.c.
Referenced by h263_h_loop_filter_c(), and h263_v_loop_filter_c().