FFmpeg: libavcodec/h263.h File Reference
h263.h File Reference
#include <stdint.h>
#include "libavutil/rational.h"
#include "get_bits.h"
#include "mpegvideo.h"
#include "h263data.h"
#include "rl.h"
Macros
#define INT_BIT (CHAR_BIT * sizeof(int))
#define INTRA_MCBPC_VLC_BITS 6
#define INTER_MCBPC_VLC_BITS 7
#define CBPY_VLC_BITS 6
#define TEX_VLC_BITS 9
#define H263_GOB_HEIGHT(h) ((h) <= 400 ? 1 : (h) <= 800 ? 2 : 4)
Functions
int ff_h263_decode_motion (MpegEncContext *s, int pred, int f_code)
av_const int ff_h263_aspect_to_info (AVRational aspect)
Return the 4 bit value that specifies the given aspect ratio.
int ff_h263_decode_init (AVCodecContext *avctx)
int ff_h263_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
int ff_h263_decode_end (AVCodecContext *avctx)
void ff_h263_encode_mb (MpegEncContext *s, int16_t block[6][64], int motion_x, int motion_y)
void ff_h263_encode_picture_header (MpegEncContext *s, int picture_number)
void ff_h263_encode_gob_header (MpegEncContext *s, int mb_line)
Encode a group of blocks header.
int16_t * ff_h263_pred_motion (MpegEncContext *s, int block, int dir, int *px, int *py)
void ff_h263_encode_init (MpegEncContext *s)
void ff_h263_decode_init_vlc (void)
int ff_h263_decode_picture_header (MpegEncContext *s)
int ff_h263_decode_gob_header (MpegEncContext *s)
void ff_h263_update_motion_val (MpegEncContext *s)
void ff_h263_loop_filter (MpegEncContext *s)
int ff_h263_decode_mba (MpegEncContext *s)
void ff_h263_encode_mba (MpegEncContext *s)
void ff_init_qscale_tab (MpegEncContext *s)
init s->current_picture.qscale_table from s->lambda_table
int ff_h263_pred_dc (MpegEncContext *s, int n, int16_t **dc_val_ptr)
void ff_h263_pred_acdc (MpegEncContext *s, int16_t *block, int n)
void ff_h263_show_pict_info (MpegEncContext *s)
Print picture info if FF_DEBUG_PICT_INFO is set.
int ff_intel_h263_decode_picture_header (MpegEncContext *s)
int ff_h263_decode_mb (MpegEncContext *s, int16_t block[6][64])
int av_const h263_get_picture_format (int width, int height)
Return the value of the 3-bit "source format" syntax element.
void ff_clean_h263_qscales (MpegEncContext *s)
modify qscale so that encoding is actually possible in H.263 (limit difference to -2..2)
int ff_h263_resync (MpegEncContext *s)
Decode the group of blocks / video packet header.
void ff_h263_encode_motion (PutBitContext *pb, int val, int f_code)
static int h263_get_motion_length (int val, int f_code)
static void ff_h263_encode_motion_vector (MpegEncContext *s, int x, int y, int f_code)
static int get_p_cbp (MpegEncContext *s, int16_t block[6][64], int motion_x, int motion_y)
Variables
VLC ff_h263_intra_MCBPC_vlc
VLC ff_h263_inter_MCBPC_vlc
VLC ff_h263_cbpy_vlc
enum AVPixelFormat ff_h263_hwaccel_pixfmt_list_420 []
Macro Definition Documentation
INT_BIT
#define INT_BIT (CHAR_BIT * sizeof(int))
Definition at line 33 of file h263.h.
Referenced by h263_get_motion_length().
INTRA_MCBPC_VLC_BITS
#define INTRA_MCBPC_VLC_BITS 6
Definition at line 39 of file h263.h.
Referenced by ff_h263_decode_init_vlc(), ff_h263_decode_mb(), mpeg4_decode_mb(), mpeg4_decode_partition_a(), and msmpeg4v12_decode_mb().
INTER_MCBPC_VLC_BITS
#define INTER_MCBPC_VLC_BITS 7
Definition at line 40 of file h263.h.
Referenced by ff_h263_decode_init_vlc(), ff_h263_decode_mb(), mpeg4_decode_mb(), mpeg4_decode_partition_a(), msmpeg4v12_decode_mb(), and preview_obmc().
CBPY_VLC_BITS
#define CBPY_VLC_BITS 6
Definition at line 41 of file h263.h.
Referenced by ff_h263_decode_init_vlc(), ff_h263_decode_mb(), mpeg4_decode_mb(), mpeg4_decode_partition_b(), msmpeg4v12_decode_mb(), and preview_obmc().
TEX_VLC_BITS
#define TEX_VLC_BITS 9
Definition at line 42 of file h263.h.
H263_GOB_HEIGHT
#define H263_GOB_HEIGHT (h) ((h) <= 400 ? 1 : (h) <= 800 ? 2 : 4)
Definition at line 44 of file h263.h.
Referenced by encode_thread(), ff_h263_decode_frame(), and vaapi_mpeg4_start_frame().
Function Documentation
ff_h263_decode_motion()
int ff_h263_decode_motion (MpegEncContext * s, int pred, int f_code)
Definition at line 255 of file ituh263dec.c.
Referenced by ff_h263_decode_mb(), mpeg4_decode_mb(), mpeg4_decode_partition_a(), and preview_obmc().
ff_h263_aspect_to_info()
av_const int ff_h263_aspect_to_info (AVRational aspect)
Return the 4 bit value that specifies the given aspect ratio.
This may be one of the standard aspect ratios or it specifies that the aspect will be stored explicitly later.
Definition at line 89 of file ituh263enc.c.
Referenced by ff_h263_encode_picture_header(), and mpeg4_encode_vol_header().
ff_h263_decode_init()
int ff_h263_decode_init (AVCodecContext * avctx)
Definition at line 62 of file h263dec.c.
Referenced by decode_init(), and ff_msmpeg4_decode_init().
ff_h263_decode_frame()
int ff_h263_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt)
Definition at line 409 of file h263dec.c.
ff_h263_decode_end()
int ff_h263_decode_end (AVCodecContext * avctx)
Definition at line 149 of file h263dec.c.
Referenced by wmv2_decode_end().
ff_h263_encode_mb()
void ff_h263_encode_mb (MpegEncContext * s, int16_t block[6][64], int motion_x, int motion_y)
Definition at line 447 of file ituh263enc.c.
Referenced by encode_mb_internal().
ff_h263_encode_picture_header()
void ff_h263_encode_picture_header (MpegEncContext * s, int picture_number)
Definition at line 103 of file ituh263enc.c.
Referenced by encode_picture().
ff_h263_encode_gob_header()
void ff_h263_encode_gob_header (MpegEncContext * s, int mb_line)
Encode a group of blocks header.
Definition at line 240 of file ituh263enc.c.
Referenced by encode_thread().
ff_h263_pred_motion()
int16_t* ff_h263_pred_motion (MpegEncContext * s, int block, int dir, int * px, int * py)
Definition at line 309 of file h263.c.
Referenced by ff_h263_decode_mb(), ff_h263_encode_mb(), ff_mpeg4_encode_mb(), ff_msmpeg4_encode_mb(), ff_wmv2_encode_mb(), mpeg4_decode_mb(), mpeg4_decode_partition_a(), msmpeg4v12_decode_mb(), msmpeg4v34_decode_mb(), preview_obmc(), svq1_encode_plane(), and write_mb_info().
ff_h263_encode_init()
void ff_h263_encode_init (MpegEncContext * s)
Definition at line 761 of file ituh263enc.c.
Referenced by encode_init(), ff_mpv_encode_init(), and svq1_encode_init().
ff_h263_decode_init_vlc()
void ff_h263_decode_init_vlc (void)
Definition at line 108 of file ituh263dec.c.
Referenced by ff_h263_decode_init(), and rv10_decode_init().
ff_h263_decode_picture_header()
int ff_h263_decode_picture_header (MpegEncContext * s)
Definition at line 877 of file ituh263dec.c.
Referenced by ff_h263_decode_frame().
ff_h263_decode_gob_header()
int ff_h263_decode_gob_header (MpegEncContext * s)
ff_h263_update_motion_val()
void ff_h263_update_motion_val (MpegEncContext * s)
Definition at line 42 of file h263.c.
Referenced by decode_slice(), encode_thread(), and rv10_decode_packet().
ff_h263_loop_filter()
void ff_h263_loop_filter (MpegEncContext * s)
Definition at line 135 of file h263.c.
Referenced by decode_slice(), encode_thread(), and rv10_decode_packet().
ff_h263_decode_mba()
int ff_h263_decode_mba (MpegEncContext * s)
Definition at line 139 of file ituh263dec.c.
Referenced by ff_h263_decode_picture_header(), h263_decode_gob_header(), and rv20_decode_picture_header().
ff_h263_encode_mba()
void ff_h263_encode_mba (MpegEncContext * s)
Definition at line 825 of file ituh263enc.c.
Referenced by ff_h263_encode_gob_header(), ff_h263_encode_picture_header(), and ff_rv20_encode_picture_header().
ff_init_qscale_tab()
void ff_init_qscale_tab (MpegEncContext * s)
init s->current_picture.qscale_table from s->lambda_table
Definition at line 217 of file mpegvideo_enc.c.
Referenced by estimate_qp(), and ff_clean_h263_qscales().
ff_h263_pred_dc()
int ff_h263_pred_dc (MpegEncContext * s, int n, int16_t ** dc_val_ptr)
Definition at line 94 of file h263.c.
Referenced by ff_h263_encode_mb().
ff_h263_pred_acdc()
void ff_h263_pred_acdc (MpegEncContext * s, int16_t * block, int n)
Definition at line 222 of file h263.c.
Referenced by h263_decode_block().
ff_h263_show_pict_info()
void ff_h263_show_pict_info (MpegEncContext * s)
Print picture info if FF_DEBUG_PICT_INFO is set.
Definition at line 76 of file ituh263dec.c.
Referenced by ff_h263_decode_picture_header(), and ff_intel_h263_decode_picture_header().
ff_intel_h263_decode_picture_header()
int ff_intel_h263_decode_picture_header (MpegEncContext * s)
Definition at line 27 of file intelh263dec.c.
Referenced by ff_h263_decode_frame().
ff_h263_decode_mb()
int ff_h263_decode_mb (MpegEncContext * s, int16_t block[6][64])
Definition at line 611 of file ituh263dec.c.
Referenced by ff_h263_decode_init(), and rv10_decode_packet().
h263_get_picture_format()
int av_const h263_get_picture_format (int width, int height)
Return the value of the 3-bit "source format" syntax element.
This represents some standard picture dimensions or indicates that width&height are explicitly stored later.
ff_clean_h263_qscales()
void ff_clean_h263_qscales (MpegEncContext * s)
modify qscale so that encoding is actually possible in H.263 (limit difference to -2..2)
Definition at line 266 of file ituh263enc.c.
Referenced by estimate_qp(), and ff_clean_mpeg4_qscales().
ff_h263_resync()
int ff_h263_resync (MpegEncContext * s)
Decode the group of blocks / video packet header.
Returns
bit position of the resync_marker, or <0 if none was found
Definition at line 213 of file ituh263dec.c.
Referenced by ff_h263_decode_frame().
ff_h263_encode_motion()
void ff_h263_encode_motion (PutBitContext * pb, int val, int f_code)
Definition at line 646 of file ituh263enc.c.
Referenced by ff_h263_encode_motion_vector(), and svq1_encode_plane().
h263_get_motion_length()
static int h263_get_motion_length (int val, int f_code) inline static
Definition at line 101 of file h263.h.
Referenced by ff_h263_encode_motion_vector().
ff_h263_encode_motion_vector()
static void ff_h263_encode_motion_vector (MpegEncContext * s, int x, int y, int f_code) inline static
Definition at line 118 of file h263.h.
Referenced by ff_h263_encode_mb(), and ff_mpeg4_encode_mb().
get_p_cbp()
static int get_p_cbp (MpegEncContext * s, int16_t block[6][64], int motion_x, int motion_y) inline static
Definition at line 129 of file h263.h.
Referenced by ff_h263_encode_mb(), and ff_mpeg4_encode_mb().
Variable Documentation
ff_h263_intra_MCBPC_vlc
VLC ff_h263_intra_MCBPC_vlc
Definition at line 98 of file ituh263dec.c.
Referenced by mpeg4_decode_mb(), mpeg4_decode_partition_a(), and msmpeg4v12_decode_mb().
ff_h263_inter_MCBPC_vlc
VLC ff_h263_inter_MCBPC_vlc
Definition at line 99 of file ituh263dec.c.
Referenced by mpeg4_decode_mb(), mpeg4_decode_partition_a(), and msmpeg4v12_decode_mb().
ff_h263_cbpy_vlc
VLC ff_h263_cbpy_vlc
Definition at line 100 of file ituh263dec.c.
Referenced by mpeg4_decode_mb(), mpeg4_decode_partition_b(), and msmpeg4v12_decode_mb().
ff_h263_hwaccel_pixfmt_list_420
enum AVPixelFormat ff_h263_hwaccel_pixfmt_list_420[]
Definition at line 721 of file h263dec.c.