FFmpeg: libavcodec/h264idct_template.c File Reference
h264idct_template.c File Reference
H.264 IDCT.
#include "bit_depth_template.c"
#include "libavutil/common.h"
#include "h264dec.h"
#include "h264idct.h"
Macros
#define stride 16
Functions
void FUNCC() ff_h264_idct_add (uint8_t *_dst, int16_t *_block, int stride)
void FUNCC() ff_h264_idct8_add (uint8_t *_dst, int16_t *_block, int stride)
void FUNCC() ff_h264_idct_dc_add (uint8_t *_dst, int16_t *_block, int stride)
void FUNCC() ff_h264_idct8_dc_add (uint8_t *_dst, int16_t *_block, int stride)
void FUNCC() ff_h264_idct_add16 (uint8_t *dst, const int *block_offset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
void FUNCC() ff_h264_idct_add16intra (uint8_t *dst, const int *block_offset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
void FUNCC() ff_h264_idct8_add4 (uint8_t *dst, const int *block_offset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
void FUNCC() ff_h264_idct_add8 (uint8_t **dest, const int *block_offset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
void FUNCC() ff_h264_idct_add8_422 (uint8_t **dest, const int *block_offset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
void FUNCC() ff_h264_luma_dc_dequant_idct (int16_t *_output, int16_t *_input, int qmul)
IDCT transforms the 16 dc values and dequantizes them.
void FUNCC() ff_h264_chroma422_dc_dequant_idct (int16_t *_block, int qmul)
void FUNCC() ff_h264_chroma_dc_dequant_idct (int16_t *_block, int qmul)
Detailed Description
H.264 IDCT.
Author
Michael Niedermayer micha.nosp@m.elni.nosp@m.@gmx..nosp@m.at
Definition in file h264idct_template.c.
Macro Definition Documentation
stride
#define stride 16
Referenced by ff_h264_chroma422_dc_dequant_idct(), ff_h264_chroma_dc_dequant_idct(), ff_h264_idct8_add(), ff_h264_idct8_add4(), ff_h264_idct8_dc_add(), ff_h264_idct_add(), ff_h264_idct_add16(), ff_h264_idct_add16intra(), ff_h264_idct_add8(), ff_h264_idct_add8_422(), ff_h264_idct_dc_add(), and ff_h264_luma_dc_dequant_idct().
Function Documentation
ff_h264_idct_add()
void FUNCC() ff_h264_idct_add (uint8_t * _dst, int16_t * _block, int stride)
Definition at line 33 of file h264idct_template.c.
Referenced by ff_h264_idct_add16(), ff_h264_idct_add16intra(), ff_h264_idct_add8(), and ff_h264_idct_add8_422().
ff_h264_idct8_add()
void FUNCC() ff_h264_idct8_add (uint8_t * _dst, int16_t * _block, int stride)
Definition at line 69 of file h264idct_template.c.
Referenced by ff_h264_idct8_add4().
ff_h264_idct_dc_add()
void FUNCC() ff_h264_idct_dc_add (uint8_t * _dst, int16_t * _block, int stride)
Definition at line 144 of file h264idct_template.c.
Referenced by ff_h264_idct_add16(), ff_h264_idct_add16intra(), ff_h264_idct_add8(), and ff_h264_idct_add8_422().
ff_h264_idct8_dc_add()
void FUNCC() ff_h264_idct8_dc_add (uint8_t * _dst, int16_t * _block, int stride)
Definition at line 159 of file h264idct_template.c.
Referenced by ff_h264_idct8_add4().
ff_h264_idct_add16()
void FUNCC() ff_h264_idct_add16 (uint8_t * dst, const int * block_offset, int16_t * block, int stride, const uint8_t nnzc[15 *8])
Definition at line 174 of file h264idct_template.c.
ff_h264_idct_add16intra()
void FUNCC() ff_h264_idct_add16intra (uint8_t * dst, const int * block_offset, int16_t * block, int stride, const uint8_t nnzc[15 *8])
Definition at line 185 of file h264idct_template.c.
ff_h264_idct8_add4()
void FUNCC() ff_h264_idct8_add4 (uint8_t * dst, const int * block_offset, int16_t * block, int stride, const uint8_t nnzc[15 *8])
Definition at line 193 of file h264idct_template.c.
ff_h264_idct_add8()
void FUNCC() ff_h264_idct_add8 (uint8_t ** dest, const int * block_offset, int16_t * block, int stride, const uint8_t nnzc[15 *8])
Definition at line 204 of file h264idct_template.c.
ff_h264_idct_add8_422()
void FUNCC() ff_h264_idct_add8_422 (uint8_t ** dest, const int * block_offset, int16_t * block, int stride, const uint8_t nnzc[15 *8])
Definition at line 216 of file h264idct_template.c.
ff_h264_luma_dc_dequant_idct()
void FUNCC() ff_h264_luma_dc_dequant_idct (int16_t * _output, int16_t * _input, int qmul)
IDCT transforms the 16 dc values and dequantizes them.
Parameters
qmul quantization parameter
Definition at line 242 of file h264idct_template.c.
ff_h264_chroma422_dc_dequant_idct()
void FUNCC() ff_h264_chroma422_dc_dequant_idct (int16_t * _block, int qmul)
Definition at line 277 of file h264idct_template.c.
ff_h264_chroma_dc_dequant_idct()
void FUNCC() ff_h264_chroma_dc_dequant_idct (int16_t * _block, int qmul)
Definition at line 304 of file h264idct_template.c.