FFmpeg: libavcodec/h264_picture.c File Reference
h264_picture.c File Reference
H.264 / AVC / MPEG-4 part10 codec.
#include "libavutil/avassert.h"
#include "libavutil/imgutils.h"
#include "libavutil/timer.h"
#include "internal.h"
#include "cabac.h"
#include "cabac_functions.h"
#include "error_resilience.h"
#include "avcodec.h"
#include "h264dec.h"
#include "h264data.h"
#include "h264chroma.h"
#include "h264_mvpred.h"
#include "mathops.h"
#include "mpegutils.h"
#include "rectangle.h"
#include "thread.h"
#include "vdpau_compat.h"
Functions
void ff_h264_unref_picture (H264Context *h, H264Picture *pic)
int ff_h264_ref_picture (H264Context *h, H264Picture *dst, H264Picture *src)
void ff_h264_set_erpic (ERPicture *dst, H264Picture *src)
int ff_h264_field_end (H264Context *h, H264SliceContext *sl, int in_setup)
Detailed Description
H.264 / AVC / MPEG-4 part10 codec.
Author
Michael Niedermayer micha.nosp@m.elni.nosp@m.@gmx..nosp@m.at
Definition in file h264_picture.c.
Function Documentation
ff_h264_unref_picture()
void ff_h264_unref_picture (H264Context * h, H264Picture * pic)
Definition at line 46 of file h264_picture.c.
Referenced by alloc_picture(), ff_h264_flush_change(), ff_h264_ref_picture(), ff_h264_remove_all_refs(), ff_h264_update_thread_context(), find_start_code(), flush_dpb(), h264_decode_end(), h264_decode_frame(), h264_frame_start(), and release_unused_pictures().
ff_h264_ref_picture()
int ff_h264_ref_picture (H264Context * h, H264Picture * dst, H264Picture * src)
Definition at line 67 of file h264_picture.c.
Referenced by ff_h264_remove_all_refs(), ff_h264_update_thread_context(), find_start_code(), and h264_frame_start().
ff_h264_set_erpic()
void ff_h264_set_erpic (ERPicture * dst, H264Picture * src)
Definition at line 130 of file h264_picture.c.
Referenced by decode_nal_units(), and h264_frame_start().
ff_h264_field_end()
int ff_h264_field_end (H264Context * h, H264SliceContext * sl, int in_setup)
Definition at line 153 of file h264_picture.c.
Referenced by ff_h264_decode_slice_header(), find_start_code(), and h264_decode_frame().