FFmpeg: libavcodec/mips/h264qpel_msa.c File Reference
h264qpel_msa.c File Reference
#include "libavutil/mips/generic_macros_msa.h"
#include "h264dsp_mips.h"
Macros
#define AVC_CALC_DPADD_H_6PIX_2COEFF_SH(in0, in1, in2, in3, in4, in5)
#define AVC_HORZ_FILTER_SH(in, mask0, mask1, mask2)
#define AVC_CALC_DPADD_B_6PIX_2COEFF_SH(vec0, vec1, vec2, vec3, vec4, vec5, out1, out2)
#define AVC_CALC_DPADD_B_6PIX_2COEFF_R_SH(vec0, vec1, vec2, vec3, vec4, vec5)
#define AVC_CALC_DPADD_H_6PIX_2COEFF_R_SH(vec0, vec1, vec2, vec3, vec4, vec5)
#define AVC_XOR_VSHF_B_AND_APPLY_6TAP_HORIZ_FILT_SH(src0, src1, mask0, mask1, mask2)
Functions
static void avc_luma_hz_4w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avc_luma_hz_8w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avc_luma_hz_16w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avc_luma_hz_qrt_4w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, uint8_t hor_offset)
static void avc_luma_hz_qrt_8w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, uint8_t hor_offset)
static void avc_luma_hz_qrt_16w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, uint8_t hor_offset)
static void avc_luma_vt_4w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avc_luma_vt_8w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avc_luma_vt_16w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avc_luma_vt_qrt_4w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, uint8_t ver_offset)
static void avc_luma_vt_qrt_8w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, uint8_t ver_offset)
static void avc_luma_vt_qrt_16w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, uint8_t ver_offset)
static void avc_luma_mid_4w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avc_luma_mid_8w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avc_luma_mid_16w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avc_luma_midh_qrt_4w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, uint8_t horiz_offset)
static void avc_luma_midh_qrt_8w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, uint8_t horiz_offset)
static void avc_luma_midh_qrt_16w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, uint8_t horiz_offset)
static void avc_luma_midv_qrt_4w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, uint8_t ver_offset)
static void avc_luma_midv_qrt_8w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, uint8_t ver_offset)
static void avc_luma_midv_qrt_16w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, uint8_t vert_offset)
static void avc_luma_hv_qrt_4w_msa (const uint8_t *src_x, const uint8_t *src_y, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avc_luma_hv_qrt_8w_msa (const uint8_t *src_x, const uint8_t *src_y, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avc_luma_hv_qrt_16w_msa (const uint8_t *src_x, const uint8_t *src_y, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avc_luma_hz_and_aver_dst_4x4_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void avc_luma_hz_and_aver_dst_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void avc_luma_hz_and_aver_dst_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void avc_luma_hz_qrt_and_aver_dst_4x4_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t hor_offset)
static void avc_luma_hz_qrt_and_aver_dst_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t hor_offset)
static void avc_luma_hz_qrt_and_aver_dst_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t hor_offset)
static void avc_luma_vt_and_aver_dst_4x4_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void avc_luma_vt_and_aver_dst_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void avc_luma_vt_and_aver_dst_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void avc_luma_vt_qrt_and_aver_dst_4x4_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t ver_offset)
static void avc_luma_vt_qrt_and_aver_dst_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t ver_offset)
static void avc_luma_vt_qrt_and_aver_dst_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t ver_offset)
static void avc_luma_mid_and_aver_dst_4x4_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void avc_luma_mid_and_aver_dst_8w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avc_luma_mid_and_aver_dst_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void avc_luma_midh_qrt_and_aver_dst_4w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, uint8_t horiz_offset)
static void avc_luma_midh_qrt_and_aver_dst_8w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, uint8_t horiz_offset)
static void avc_luma_midh_qrt_and_aver_dst_16w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, uint8_t horiz_offset)
static void avc_luma_midv_qrt_and_aver_dst_4w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, uint8_t ver_offset)
static void avc_luma_midv_qrt_and_aver_dst_8w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, uint8_t vert_offset)
static void avc_luma_midv_qrt_and_aver_dst_16w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, uint8_t vert_offset)
static void avc_luma_hv_qrt_and_aver_dst_4x4_msa (const uint8_t *src_x, const uint8_t *src_y, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void avc_luma_hv_qrt_and_aver_dst_8x8_msa (const uint8_t *src_x, const uint8_t *src_y, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void avc_luma_hv_qrt_and_aver_dst_16x16_msa (const uint8_t *src_x, const uint8_t *src_y, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void copy_width8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void copy_16multx8mult_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t width)
static void copy_width16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avg_width4_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avg_width8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avg_width16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
void ff_put_h264_qpel16_mc00_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc00_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc00_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc00_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc00_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc10_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc30_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc10_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc30_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc10_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc30_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc20_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc20_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc20_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc01_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc03_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc01_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc03_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc01_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc03_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc11_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc31_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc13_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc33_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc11_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc31_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc13_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc33_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc11_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc31_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc13_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc33_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc21_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc23_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc21_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc23_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc21_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc23_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc02_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc02_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc02_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc12_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc32_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc12_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc32_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc12_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc32_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc22_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc22_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc22_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc10_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc30_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc10_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc30_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc10_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc30_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc20_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc20_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc20_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc01_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc03_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc01_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc03_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc01_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc03_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc11_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc31_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc13_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc33_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc11_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc31_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc13_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc33_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc11_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc31_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc13_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc33_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc21_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc23_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc21_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc23_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc21_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc23_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc02_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc02_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc02_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc12_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc32_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc12_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc32_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc12_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc32_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc22_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc22_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc22_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
Variables
static const uint8_t luma_mask_arr [16 *8]
Macro Definition Documentation
AVC_CALC_DPADD_H_6PIX_2COEFF_SH
#define AVC_CALC_DPADD_H_6PIX_2COEFF_SH (in0, in1, in2, in3, in4, in5)
Value:
({                                                                      \
    v4i32 tmp0_m, tmp1_m;                                                \
    v8i16 out0_m, out1_m, out2_m, out3_m;                                \
    v8i16 minus5h_m = __msa_ldi_h(-5);                                   \
    v8i16 plus20h_m = __msa_ldi_h(20);                                   \
                                                                         \
    ILVRL_H2_SW(in5, in0, tmp0_m, tmp1_m);                               \
                                                                         \
    tmp0_m = __msa_hadd_s_w((v8i16) tmp0_m, (v8i16) tmp0_m);             \
    tmp1_m = __msa_hadd_s_w((v8i16) tmp1_m, (v8i16) tmp1_m);             \
                                                                         \
    ILVRL_H2_SH(in1, in4, out0_m, out1_m);                               \
    DPADD_SH2_SW(out0_m, out1_m, minus5h_m, minus5h_m, tmp0_m, tmp1_m);  \
    ILVRL_H2_SH(in2, in3, out2_m, out3_m);                               \
    DPADD_SH2_SW(out2_m, out3_m, plus20h_m, plus20h_m, tmp0_m, tmp1_m);  \
                                                                         \
    SRARI_W2_SW(tmp0_m, tmp1_m, 10);                                     \
    SAT_SW2_SW(tmp0_m, tmp1_m, 7);                                       \
    out0_m = __msa_pckev_h((v8i16) tmp1_m, (v8i16) tmp0_m);              \
                                                                         \
    out0_m;                                                              \
})
Definition at line 24 of file h264qpel_msa.c.
Referenced by avc_luma_mid_8w_msa(), avc_luma_mid_and_aver_dst_8w_msa(), avc_luma_midv_qrt_4w_msa(), avc_luma_midv_qrt_8w_msa(), and avc_luma_midv_qrt_and_aver_dst_8w_msa().
AVC_HORZ_FILTER_SH
#define AVC_HORZ_FILTER_SH (in, mask0, mask1, mask2)
Value:
({                                                     \
    v8i16 out0_m, out1_m;                               \
    v16i8 tmp0_m, tmp1_m;                               \
    v16i8 minus5b = __msa_ldi_b(-5);                    \
    v16i8 plus20b = __msa_ldi_b(20);                    \
                                                        \
    tmp0_m = __msa_vshf_b((v16i8) mask0, in, in);       \
    out0_m = __msa_hadd_s_h(tmp0_m, tmp0_m);            \
                                                        \
    tmp0_m = __msa_vshf_b((v16i8) mask1, in, in);       \
    out0_m = __msa_dpadd_s_h(out0_m, minus5b, tmp0_m);  \
                                                        \
    tmp1_m = __msa_vshf_b((v16i8) (mask2), in, in);     \
    out1_m = __msa_dpadd_s_h(out0_m, plus20b, tmp1_m);  \
                                                        \
    out1_m;                                             \
})
Definition at line 48 of file h264qpel_msa.c.
Referenced by avc_luma_hv_qrt_8w_msa(), avc_luma_hv_qrt_and_aver_dst_8x8_msa(), avc_luma_mid_4w_msa(), avc_luma_mid_8w_msa(), avc_luma_mid_and_aver_dst_4x4_msa(), avc_luma_mid_and_aver_dst_8w_msa(), avc_luma_midv_qrt_4w_msa(), avc_luma_midv_qrt_8w_msa(), avc_luma_midv_qrt_and_aver_dst_4w_msa(), and avc_luma_midv_qrt_and_aver_dst_8w_msa().
AVC_CALC_DPADD_B_6PIX_2COEFF_SH
#define AVC_CALC_DPADD_B_6PIX_2COEFF_SH (vec0, vec1, vec2, vec3, vec4, vec5, out1, out2)
Value:
{                                                                            \
    v16i8 tmp0_m, tmp1_m;                                                    \
    v16i8 minus5b_m = __msa_ldi_b(-5);                                       \
    v16i8 plus20b_m = __msa_ldi_b(20);                                       \
                                                                             \
    ILVRL_B2_SB(vec5, vec0, tmp0_m, tmp1_m);                                 \
    HADD_SB2_SH(tmp0_m, tmp1_m, out1, out2);                                 \
    ILVRL_B2_SB(vec4, vec1, tmp0_m, tmp1_m);                                 \
    DPADD_SB2_SH(tmp0_m, tmp1_m, minus5b_m, minus5b_m, out1, out2);          \
    ILVRL_B2_SB(vec3, vec2, tmp0_m, tmp1_m);                                 \
    DPADD_SB2_SH(tmp0_m, tmp1_m, plus20b_m, plus20b_m, out1, out2);          \
}
Definition at line 82 of file h264qpel_msa.c.
Referenced by avc_luma_hv_qrt_8w_msa(), avc_luma_hv_qrt_and_aver_dst_8x8_msa(), avc_luma_midh_qrt_4w_msa(), and avc_luma_midh_qrt_and_aver_dst_4w_msa().
AVC_CALC_DPADD_B_6PIX_2COEFF_R_SH
#define AVC_CALC_DPADD_B_6PIX_2COEFF_R_SH (vec0, vec1, vec2, vec3, vec4, vec5)
Value:
({                                                                            \
    v8i16 tmp1_m;                                                              \
    v16i8 tmp0_m, tmp2_m;                                                      \
    v16i8 minus5b_m = __msa_ldi_b(-5);                                         \
    v16i8 plus20b_m = __msa_ldi_b(20);                                         \
                                                                               \
    tmp1_m = (v8i16) __msa_ilvr_b((v16i8) vec5, (v16i8) vec0);                 \
    tmp1_m = __msa_hadd_s_h((v16i8) tmp1_m, (v16i8) tmp1_m);                   \
                                                                               \
    ILVR_B2_SB(vec4, vec1, vec3, vec2, tmp0_m, tmp2_m);                        \
    DPADD_SB2_SH(tmp0_m, tmp2_m, minus5b_m, plus20b_m, tmp1_m, tmp1_m);        \
                                                                               \
    tmp1_m;                                                                    \
})
Definition at line 97 of file h264qpel_msa.c.
Referenced by avc_luma_hv_qrt_4w_msa(), and avc_luma_hv_qrt_and_aver_dst_4x4_msa().
AVC_CALC_DPADD_H_6PIX_2COEFF_R_SH
#define AVC_CALC_DPADD_H_6PIX_2COEFF_R_SH (vec0, vec1, vec2, vec3, vec4, vec5)
Value:
({                                                                            \
    v4i32 tmp1_m;                                                              \
    v8i16 tmp2_m, tmp3_m;                                                      \
    v8i16 minus5h_m = __msa_ldi_h(-5);                                         \
    v8i16 plus20h_m = __msa_ldi_h(20);                                         \
                                                                               \
    tmp1_m = (v4i32) __msa_ilvr_h((v8i16) vec5, (v8i16) vec0);                 \
    tmp1_m = __msa_hadd_s_w((v8i16) tmp1_m, (v8i16) tmp1_m);                   \
                                                                               \
    ILVR_H2_SH(vec1, vec4, vec2, vec3, tmp2_m, tmp3_m);                        \
    DPADD_SH2_SW(tmp2_m, tmp3_m, minus5h_m, plus20h_m, tmp1_m, tmp1_m);        \
                                                                               \
    tmp1_m = __msa_srari_w(tmp1_m, 10);                                        \
    tmp1_m = __msa_sat_s_w(tmp1_m, 7);                                         \
                                                                               \
    tmp2_m = __msa_pckev_h((v8i16) tmp1_m, (v8i16) tmp1_m);                    \
                                                                               \
    tmp2_m;                                                                    \
})
Definition at line 113 of file h264qpel_msa.c.
Referenced by avc_luma_mid_4w_msa(), avc_luma_mid_and_aver_dst_4x4_msa(), and avc_luma_midv_qrt_and_aver_dst_4w_msa().
AVC_XOR_VSHF_B_AND_APPLY_6TAP_HORIZ_FILT_SH
#define AVC_XOR_VSHF_B_AND_APPLY_6TAP_HORIZ_FILT_SH (src0, src1, mask0, mask1, mask2)
Value:
({                                                                          \
    v8i16 hz_out_m;                                                          \
    v16i8 vec0_m, vec1_m, vec2_m;                                            \
    v16i8 minus5b_m = __msa_ldi_b(-5);                                       \
    v16i8 plus20b_m = __msa_ldi_b(20);                                       \
                                                                             \
    vec0_m = __msa_vshf_b((v16i8) mask0, (v16i8) src1, (v16i8) src0);        \
    hz_out_m = __msa_hadd_s_h(vec0_m, vec0_m);                               \
                                                                             \
    VSHF_B2_SB(src0, src1, src0, src1, mask1, mask2, vec1_m, vec2_m);        \
    DPADD_SB2_SH(vec1_m, vec2_m, minus5b_m, plus20b_m, hz_out_m, hz_out_m);  \
                                                                             \
    hz_out_m;                                                                \
})
Definition at line 134 of file h264qpel_msa.c.
Referenced by avc_luma_hv_qrt_4w_msa(), avc_luma_hv_qrt_and_aver_dst_4x4_msa(), avc_luma_mid_4w_msa(), avc_luma_mid_and_aver_dst_4x4_msa(), avc_luma_midv_qrt_4w_msa(), and avc_luma_midv_qrt_and_aver_dst_4w_msa().
Function Documentation
avc_luma_hz_4w_msa()
static void avc_luma_hz_4w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 151 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel4_mc20_msa().
avc_luma_hz_8w_msa()
static void avc_luma_hz_8w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 184 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel8_mc20_msa().
avc_luma_hz_16w_msa()
static void avc_luma_hz_16w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 225 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel16_mc20_msa().
avc_luma_hz_qrt_4w_msa()
static void avc_luma_hz_qrt_4w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, uint8_t hor_offset) static
Definition at line 289 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel4_mc10_msa(), and ff_put_h264_qpel4_mc30_msa().
avc_luma_hz_qrt_8w_msa()
static void avc_luma_hz_qrt_8w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, uint8_t hor_offset) static
Definition at line 335 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel8_mc10_msa(), and ff_put_h264_qpel8_mc30_msa().
avc_luma_hz_qrt_16w_msa()
static void avc_luma_hz_qrt_16w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, uint8_t hor_offset) static
Definition at line 390 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel16_mc10_msa(), and ff_put_h264_qpel16_mc30_msa().
avc_luma_vt_4w_msa()
static void avc_luma_vt_4w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 445 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel4_mc02_msa().
avc_luma_vt_8w_msa()
static void avc_luma_vt_8w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 494 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel8_mc02_msa().
avc_luma_vt_16w_msa()
static void avc_luma_vt_16w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 546 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel16_mc02_msa().
avc_luma_vt_qrt_4w_msa()
static void avc_luma_vt_qrt_4w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, uint8_t ver_offset) static
Definition at line 615 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel4_mc01_msa(), and ff_put_h264_qpel4_mc03_msa().
avc_luma_vt_qrt_8w_msa()
static void avc_luma_vt_qrt_8w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, uint8_t ver_offset) static
Definition at line 678 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel8_mc01_msa(), and ff_put_h264_qpel8_mc03_msa().
avc_luma_vt_qrt_16w_msa()
static void avc_luma_vt_qrt_16w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, uint8_t ver_offset) static
Definition at line 742 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel16_mc01_msa(), and ff_put_h264_qpel16_mc03_msa().
avc_luma_mid_4w_msa()
static void avc_luma_mid_4w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 826 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel4_mc22_msa().
avc_luma_mid_8w_msa()
static void avc_luma_mid_8w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 891 of file h264qpel_msa.c.
Referenced by avc_luma_mid_16w_msa(), and ff_put_h264_qpel8_mc22_msa().
avc_luma_mid_16w_msa()
static void avc_luma_mid_16w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 946 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel16_mc22_msa().
avc_luma_midh_qrt_4w_msa()
static void avc_luma_midh_qrt_4w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, uint8_t horiz_offset) static
Definition at line 959 of file h264qpel_msa.c.
Referenced by avc_luma_midh_qrt_16w_msa(), avc_luma_midh_qrt_8w_msa(), ff_put_h264_qpel4_mc12_msa(), and ff_put_h264_qpel4_mc32_msa().
avc_luma_midh_qrt_8w_msa()
static void avc_luma_midh_qrt_8w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, uint8_t horiz_offset) static
Definition at line 1031 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel8_mc12_msa(), and ff_put_h264_qpel8_mc32_msa().
avc_luma_midh_qrt_16w_msa()
static void avc_luma_midh_qrt_16w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, uint8_t horiz_offset) static
Definition at line 1046 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel16_mc12_msa(), and ff_put_h264_qpel16_mc32_msa().
avc_luma_midv_qrt_4w_msa()
static void avc_luma_midv_qrt_4w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, uint8_t ver_offset) static
Definition at line 1061 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel4_mc21_msa(), and ff_put_h264_qpel4_mc23_msa().
avc_luma_midv_qrt_8w_msa()
static void avc_luma_midv_qrt_8w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, uint8_t ver_offset) static
Definition at line 1143 of file h264qpel_msa.c.
Referenced by avc_luma_midv_qrt_16w_msa(), ff_put_h264_qpel8_mc21_msa(), and ff_put_h264_qpel8_mc23_msa().
avc_luma_midv_qrt_16w_msa()
static void avc_luma_midv_qrt_16w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, uint8_t vert_offset) static
Definition at line 1226 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel16_mc21_msa(), and ff_put_h264_qpel16_mc23_msa().
avc_luma_hv_qrt_4w_msa()
static void avc_luma_hv_qrt_4w_msa (const uint8_t * src_x, const uint8_t * src_y, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 1241 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel4_mc11_msa(), ff_put_h264_qpel4_mc13_msa(), ff_put_h264_qpel4_mc31_msa(), and ff_put_h264_qpel4_mc33_msa().
avc_luma_hv_qrt_8w_msa()
static void avc_luma_hv_qrt_8w_msa (const uint8_t * src_x, const uint8_t * src_y, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 1319 of file h264qpel_msa.c.
Referenced by avc_luma_hv_qrt_16w_msa(), ff_put_h264_qpel8_mc11_msa(), ff_put_h264_qpel8_mc13_msa(), ff_put_h264_qpel8_mc31_msa(), and ff_put_h264_qpel8_mc33_msa().
avc_luma_hv_qrt_16w_msa()
static void avc_luma_hv_qrt_16w_msa (const uint8_t * src_x, const uint8_t * src_y, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 1396 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel16_mc11_msa(), ff_put_h264_qpel16_mc13_msa(), ff_put_h264_qpel16_mc31_msa(), and ff_put_h264_qpel16_mc33_msa().
avc_luma_hz_and_aver_dst_4x4_msa()
static void avc_luma_hz_and_aver_dst_4x4_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 1412 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel4_mc20_msa().
avc_luma_hz_and_aver_dst_8x8_msa()
static void avc_luma_hz_and_aver_dst_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 1446 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel8_mc20_msa().
avc_luma_hz_and_aver_dst_16x16_msa()
static void avc_luma_hz_and_aver_dst_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 1489 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel16_mc20_msa().
avc_luma_hz_qrt_and_aver_dst_4x4_msa()
static void avc_luma_hz_qrt_and_aver_dst_4x4_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t hor_offset) static
Definition at line 1555 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel4_mc10_msa(), and ff_avg_h264_qpel4_mc30_msa().
avc_luma_hz_qrt_and_aver_dst_8x8_msa()
static void avc_luma_hz_qrt_and_aver_dst_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t hor_offset) static
Definition at line 1613 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel8_mc10_msa(), and ff_avg_h264_qpel8_mc30_msa().
avc_luma_hz_qrt_and_aver_dst_16x16_msa()
static void avc_luma_hz_qrt_and_aver_dst_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t hor_offset) static
Definition at line 1682 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel16_mc10_msa(), and ff_avg_h264_qpel16_mc30_msa().
avc_luma_vt_and_aver_dst_4x4_msa()
static void avc_luma_vt_and_aver_dst_4x4_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 1742 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel4_mc02_msa().
avc_luma_vt_and_aver_dst_8x8_msa()
static void avc_luma_vt_and_aver_dst_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 1788 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel8_mc02_msa().
avc_luma_vt_and_aver_dst_16x16_msa()
static void avc_luma_vt_and_aver_dst_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 1841 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel16_mc02_msa().
avc_luma_vt_qrt_and_aver_dst_4x4_msa()
static void avc_luma_vt_qrt_and_aver_dst_4x4_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t ver_offset) static
Definition at line 1913 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel4_mc01_msa(), and ff_avg_h264_qpel4_mc03_msa().
avc_luma_vt_qrt_and_aver_dst_8x8_msa()
static void avc_luma_vt_qrt_and_aver_dst_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t ver_offset) static
Definition at line 1972 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel8_mc01_msa(), and ff_avg_h264_qpel8_mc03_msa().
avc_luma_vt_qrt_and_aver_dst_16x16_msa()
static void avc_luma_vt_qrt_and_aver_dst_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t ver_offset) static
Definition at line 2044 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel16_mc01_msa(), and ff_avg_h264_qpel16_mc03_msa().
avc_luma_mid_and_aver_dst_4x4_msa()
static void avc_luma_mid_and_aver_dst_4x4_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 2134 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel4_mc22_msa().
avc_luma_mid_and_aver_dst_8w_msa()
static void avc_luma_mid_and_aver_dst_8w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 2188 of file h264qpel_msa.c.
Referenced by avc_luma_mid_and_aver_dst_16x16_msa(), and ff_avg_h264_qpel8_mc22_msa().
avc_luma_mid_and_aver_dst_16x16_msa()
static void avc_luma_mid_and_aver_dst_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 2245 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel16_mc22_msa().
avc_luma_midh_qrt_and_aver_dst_4w_msa()
static void avc_luma_midh_qrt_and_aver_dst_4w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, uint8_t horiz_offset) static
Definition at line 2255 of file h264qpel_msa.c.
Referenced by avc_luma_midh_qrt_and_aver_dst_16w_msa(), avc_luma_midh_qrt_and_aver_dst_8w_msa(), ff_avg_h264_qpel4_mc12_msa(), and ff_avg_h264_qpel4_mc32_msa().
avc_luma_midh_qrt_and_aver_dst_8w_msa()
static void avc_luma_midh_qrt_and_aver_dst_8w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, uint8_t horiz_offset) static
Definition at line 2338 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel8_mc12_msa(), and ff_avg_h264_qpel8_mc32_msa().
avc_luma_midh_qrt_and_aver_dst_16w_msa()
static void avc_luma_midh_qrt_and_aver_dst_16w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, uint8_t horiz_offset) static
Definition at line 2356 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel16_mc12_msa(), and ff_avg_h264_qpel16_mc32_msa().
avc_luma_midv_qrt_and_aver_dst_4w_msa()
static void avc_luma_midv_qrt_and_aver_dst_4w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, uint8_t ver_offset) static
Definition at line 2374 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel4_mc21_msa(), and ff_avg_h264_qpel4_mc23_msa().
avc_luma_midv_qrt_and_aver_dst_8w_msa()
static void avc_luma_midv_qrt_and_aver_dst_8w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, uint8_t vert_offset) static
Definition at line 2454 of file h264qpel_msa.c.
Referenced by avc_luma_midv_qrt_and_aver_dst_16w_msa(), ff_avg_h264_qpel8_mc21_msa(), and ff_avg_h264_qpel8_mc23_msa().
avc_luma_midv_qrt_and_aver_dst_16w_msa()
static void avc_luma_midv_qrt_and_aver_dst_16w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, uint8_t vert_offset) static
Definition at line 2534 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel16_mc21_msa(), and ff_avg_h264_qpel16_mc23_msa().
avc_luma_hv_qrt_and_aver_dst_4x4_msa()
static void avc_luma_hv_qrt_and_aver_dst_4x4_msa (const uint8_t * src_x, const uint8_t * src_y, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 2552 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel4_mc11_msa(), ff_avg_h264_qpel4_mc13_msa(), ff_avg_h264_qpel4_mc31_msa(), and ff_avg_h264_qpel4_mc33_msa().
avc_luma_hv_qrt_and_aver_dst_8x8_msa()
static void avc_luma_hv_qrt_and_aver_dst_8x8_msa (const uint8_t * src_x, const uint8_t * src_y, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 2617 of file h264qpel_msa.c.
Referenced by avc_luma_hv_qrt_and_aver_dst_16x16_msa(), ff_avg_h264_qpel8_mc11_msa(), ff_avg_h264_qpel8_mc13_msa(), ff_avg_h264_qpel8_mc31_msa(), and ff_avg_h264_qpel8_mc33_msa().
avc_luma_hv_qrt_and_aver_dst_16x16_msa()
static void avc_luma_hv_qrt_and_aver_dst_16x16_msa (const uint8_t * src_x, const uint8_t * src_y, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 2691 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel16_mc11_msa(), ff_avg_h264_qpel16_mc13_msa(), ff_avg_h264_qpel16_mc31_msa(), and ff_avg_h264_qpel16_mc33_msa().
copy_width8_msa()
static void copy_width8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 2722 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel8_mc00_msa().
copy_16multx8mult_msa()
static void copy_16multx8mult_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t width) static
Definition at line 2808 of file h264qpel_msa.c.
Referenced by copy_width16_msa().
copy_width16_msa()
static void copy_width16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 2836 of file h264qpel_msa.c.
Referenced by ff_put_h264_qpel16_mc00_msa().
avg_width4_msa()
static void avg_width4_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 2870 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel4_mc00_msa().
avg_width8_msa()
static void avg_width8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 2915 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel8_mc00_msa().
avg_width16_msa()
static void avg_width16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 2941 of file h264qpel_msa.c.
Referenced by ff_avg_h264_qpel16_mc00_msa().
ff_put_h264_qpel16_mc00_msa()
void ff_put_h264_qpel16_mc00_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2963 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc00_msa()
void ff_put_h264_qpel8_mc00_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2969 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc00_msa()
void ff_avg_h264_qpel16_mc00_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2975 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc00_msa()
void ff_avg_h264_qpel8_mc00_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2981 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc00_msa()
void ff_avg_h264_qpel4_mc00_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2987 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc10_msa()
void ff_put_h264_qpel16_mc10_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2993 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc30_msa()
void ff_put_h264_qpel16_mc30_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2999 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc10_msa()
void ff_put_h264_qpel8_mc10_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3005 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc30_msa()
void ff_put_h264_qpel8_mc30_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3011 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc10_msa()
void ff_put_h264_qpel4_mc10_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3017 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc30_msa()
void ff_put_h264_qpel4_mc30_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3023 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc20_msa()
void ff_put_h264_qpel16_mc20_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3029 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc20_msa()
void ff_put_h264_qpel8_mc20_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3035 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc20_msa()
void ff_put_h264_qpel4_mc20_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3041 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc01_msa()
void ff_put_h264_qpel16_mc01_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3047 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc03_msa()
void ff_put_h264_qpel16_mc03_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3053 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc01_msa()
void ff_put_h264_qpel8_mc01_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3059 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc03_msa()
void ff_put_h264_qpel8_mc03_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3065 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc01_msa()
void ff_put_h264_qpel4_mc01_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3071 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc03_msa()
void ff_put_h264_qpel4_mc03_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3077 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc11_msa()
void ff_put_h264_qpel16_mc11_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3083 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc31_msa()
void ff_put_h264_qpel16_mc31_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3090 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc13_msa()
void ff_put_h264_qpel16_mc13_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3098 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc33_msa()
void ff_put_h264_qpel16_mc33_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3105 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc11_msa()
void ff_put_h264_qpel8_mc11_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3113 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc31_msa()
void ff_put_h264_qpel8_mc31_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3119 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc13_msa()
void ff_put_h264_qpel8_mc13_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3127 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc33_msa()
void ff_put_h264_qpel8_mc33_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3134 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc11_msa()
void ff_put_h264_qpel4_mc11_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3143 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc31_msa()
void ff_put_h264_qpel4_mc31_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3149 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc13_msa()
void ff_put_h264_qpel4_mc13_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3157 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc33_msa()
void ff_put_h264_qpel4_mc33_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3164 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc21_msa()
void ff_put_h264_qpel16_mc21_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3172 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc23_msa()
void ff_put_h264_qpel16_mc23_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3179 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc21_msa()
void ff_put_h264_qpel8_mc21_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3186 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc23_msa()
void ff_put_h264_qpel8_mc23_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3192 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc21_msa()
void ff_put_h264_qpel4_mc21_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3198 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc23_msa()
void ff_put_h264_qpel4_mc23_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3204 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc02_msa()
void ff_put_h264_qpel16_mc02_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3210 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc02_msa()
void ff_put_h264_qpel8_mc02_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3216 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc02_msa()
void ff_put_h264_qpel4_mc02_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3222 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc12_msa()
void ff_put_h264_qpel16_mc12_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3228 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc32_msa()
void ff_put_h264_qpel16_mc32_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3235 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc12_msa()
void ff_put_h264_qpel8_mc12_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3242 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc32_msa()
void ff_put_h264_qpel8_mc32_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3248 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc12_msa()
void ff_put_h264_qpel4_mc12_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3254 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc32_msa()
void ff_put_h264_qpel4_mc32_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3260 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc22_msa()
void ff_put_h264_qpel16_mc22_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3266 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc22_msa()
void ff_put_h264_qpel8_mc22_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3272 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc22_msa()
void ff_put_h264_qpel4_mc22_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3278 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc10_msa()
void ff_avg_h264_qpel16_mc10_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3284 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc30_msa()
void ff_avg_h264_qpel16_mc30_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3290 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc10_msa()
void ff_avg_h264_qpel8_mc10_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3296 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc30_msa()
void ff_avg_h264_qpel8_mc30_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3302 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc10_msa()
void ff_avg_h264_qpel4_mc10_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3308 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc30_msa()
void ff_avg_h264_qpel4_mc30_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3314 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc20_msa()
void ff_avg_h264_qpel16_mc20_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3320 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc20_msa()
void ff_avg_h264_qpel8_mc20_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3326 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc20_msa()
void ff_avg_h264_qpel4_mc20_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3332 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc01_msa()
void ff_avg_h264_qpel16_mc01_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3338 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc03_msa()
void ff_avg_h264_qpel16_mc03_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3345 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc01_msa()
void ff_avg_h264_qpel8_mc01_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3352 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc03_msa()
void ff_avg_h264_qpel8_mc03_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3359 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc01_msa()
void ff_avg_h264_qpel4_mc01_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3366 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc03_msa()
void ff_avg_h264_qpel4_mc03_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3373 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc11_msa()
void ff_avg_h264_qpel16_mc11_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3380 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc31_msa()
void ff_avg_h264_qpel16_mc31_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3388 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc13_msa()
void ff_avg_h264_qpel16_mc13_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3397 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc33_msa()
void ff_avg_h264_qpel16_mc33_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3405 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc11_msa()
void ff_avg_h264_qpel8_mc11_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3414 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc31_msa()
void ff_avg_h264_qpel8_mc31_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3422 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc13_msa()
void ff_avg_h264_qpel8_mc13_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3430 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc33_msa()
void ff_avg_h264_qpel8_mc33_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3438 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc11_msa()
void ff_avg_h264_qpel4_mc11_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3447 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc31_msa()
void ff_avg_h264_qpel4_mc31_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3455 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc13_msa()
void ff_avg_h264_qpel4_mc13_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3463 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc33_msa()
void ff_avg_h264_qpel4_mc33_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3471 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc21_msa()
void ff_avg_h264_qpel16_mc21_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3479 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc23_msa()
void ff_avg_h264_qpel16_mc23_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3486 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc21_msa()
void ff_avg_h264_qpel8_mc21_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3493 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc23_msa()
void ff_avg_h264_qpel8_mc23_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3500 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc21_msa()
void ff_avg_h264_qpel4_mc21_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3507 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc23_msa()
void ff_avg_h264_qpel4_mc23_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3514 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc02_msa()
void ff_avg_h264_qpel16_mc02_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3521 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc02_msa()
void ff_avg_h264_qpel8_mc02_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3527 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc02_msa()
void ff_avg_h264_qpel4_mc02_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3533 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc12_msa()
void ff_avg_h264_qpel16_mc12_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3539 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc32_msa()
void ff_avg_h264_qpel16_mc32_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3546 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc12_msa()
void ff_avg_h264_qpel8_mc12_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3553 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc32_msa()
void ff_avg_h264_qpel8_mc32_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3560 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc12_msa()
void ff_avg_h264_qpel4_mc12_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3567 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc32_msa()
void ff_avg_h264_qpel4_mc32_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3574 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc22_msa()
void ff_avg_h264_qpel16_mc22_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3581 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc22_msa()
void ff_avg_h264_qpel8_mc22_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3588 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc22_msa()
void ff_avg_h264_qpel4_mc22_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3595 of file h264qpel_msa.c.
Variable Documentation
luma_mask_arr
const uint8_t luma_mask_arr[16 *8] static
Initial value:
= {
    0, 5, 1, 6, 2, 7, 3, 8, 4, 9, 5, 10, 6, 11, 7, 12,
    1, 4, 2, 5, 3, 6, 4, 7, 5, 8, 6, 9, 7, 10, 8, 11,
    2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10,
    0, 5, 1, 6, 2, 7, 3, 8, 16, 21, 17, 22, 18, 23, 19, 24,
    1, 4, 2, 5, 3, 6, 4, 7, 17, 20, 18, 21, 19, 22, 20, 23,
    2, 3, 3, 4, 4, 5, 5, 6, 18, 19, 19, 20, 20, 21, 21, 22,
    2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 24, 25,
    3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 24, 25, 26
}
Definition at line 67 of file h264qpel_msa.c.
Referenced by avc_luma_hv_qrt_4w_msa(), avc_luma_hv_qrt_8w_msa(), avc_luma_hv_qrt_and_aver_dst_4x4_msa(), avc_luma_hv_qrt_and_aver_dst_8x8_msa(), avc_luma_hz_16w_msa(), avc_luma_hz_4w_msa(), avc_luma_hz_8w_msa(), avc_luma_hz_and_aver_dst_16x16_msa(), avc_luma_hz_and_aver_dst_4x4_msa(), avc_luma_hz_and_aver_dst_8x8_msa(), avc_luma_hz_qrt_16w_msa(), avc_luma_hz_qrt_4w_msa(), avc_luma_hz_qrt_8w_msa(), avc_luma_hz_qrt_and_aver_dst_16x16_msa(), avc_luma_hz_qrt_and_aver_dst_4x4_msa(), avc_luma_hz_qrt_and_aver_dst_8x8_msa(), avc_luma_mid_4w_msa(), avc_luma_mid_8w_msa(), avc_luma_mid_and_aver_dst_4x4_msa(), avc_luma_mid_and_aver_dst_8w_msa(), avc_luma_midv_qrt_4w_msa(), avc_luma_midv_qrt_8w_msa(), avc_luma_midv_qrt_and_aver_dst_4w_msa(), and avc_luma_midv_qrt_and_aver_dst_8w_msa().