FFmpeg: libavcodec/h264_sei.h File Reference
h264_sei.h File Reference
#include "get_bits.h"
Data Structures
struct H264SEIPictureTiming
struct H264SEIAFD
struct H264SEIA53Caption
struct H264SEIUnregistered
struct H264SEIRecoveryPoint
struct H264SEIBufferingPeriod
struct H264SEIFramePacking
struct H264SEIDisplayOrientation
struct H264SEIGreenMetaData
struct H264SEIContext
Enumerations
enum SEI_Type {
SEI_TYPE_BUFFERING_PERIOD = 0, SEI_TYPE_PIC_TIMING = 1, SEI_TYPE_USER_DATA_REGISTERED = 4, SEI_TYPE_USER_DATA_UNREGISTERED = 5,
SEI_TYPE_RECOVERY_POINT = 6, SEI_TYPE_FRAME_PACKING = 45, SEI_TYPE_DISPLAY_ORIENTATION = 47, SEI_TYPE_GREEN_METADATA = 56
}
SEI message types.
enum SEI_PicStructType {
SEI_PIC_STRUCT_FRAME = 0, SEI_PIC_STRUCT_TOP_FIELD = 1, SEI_PIC_STRUCT_BOTTOM_FIELD = 2, SEI_PIC_STRUCT_TOP_BOTTOM = 3,
SEI_PIC_STRUCT_BOTTOM_TOP = 4, SEI_PIC_STRUCT_TOP_BOTTOM_TOP = 5, SEI_PIC_STRUCT_BOTTOM_TOP_BOTTOM = 6, SEI_PIC_STRUCT_FRAME_DOUBLING = 7,
SEI_PIC_STRUCT_FRAME_TRIPLING = 8
}
pic_struct in picture timing SEI message
enum SEI_FpaType {
SEI_FPA_TYPE_CHECKERBOARD = 0, SEI_FPA_TYPE_INTERLEAVE_COLUMN = 1, SEI_FPA_TYPE_INTERLEAVE_ROW = 2, SEI_FPA_TYPE_SIDE_BY_SIDE = 3,
SEI_FPA_TYPE_TOP_BOTTOM = 4, SEI_FPA_TYPE_INTERLEAVE_TEMPORAL = 5, SEI_FPA_TYPE_2D = 6
}
frame_packing_arrangement types
Functions
int ff_h264_sei_decode (H264SEIContext *h, GetBitContext *gb, const struct H264ParamSets *ps, void *logctx)
void ff_h264_sei_uninit (H264SEIContext *h)
Reset SEI values at the beginning of the frame.
const char * ff_h264_sei_stereo_mode (const H264SEIFramePacking *h)
Get stereo_mode string from the h264 frame_packing_arrangement.
Enumeration Type Documentation
SEI_Type
enum SEI_Type
SEI message types.
Enumerator
SEI_TYPE_BUFFERING_PERIOD
buffering period (H.264, D.1.1)
SEI_TYPE_PIC_TIMING
picture timing
SEI_TYPE_USER_DATA_REGISTERED
registered user data as specified by Rec. ITU-T T.35
SEI_TYPE_USER_DATA_UNREGISTERED
unregistered user data
SEI_TYPE_RECOVERY_POINT
recovery point (frame # to decoder sync)
SEI_TYPE_FRAME_PACKING
frame packing arrangement
SEI_TYPE_DISPLAY_ORIENTATION
display orientation
SEI_TYPE_GREEN_METADATA
GreenMPEG information.
Definition at line 27 of file h264_sei.h.
SEI_PicStructType
enum SEI_PicStructType
pic_struct in picture timing SEI message
Enumerator
SEI_PIC_STRUCT_FRAME
0: frame
SEI_PIC_STRUCT_TOP_FIELD
1: top field
SEI_PIC_STRUCT_BOTTOM_FIELD
2: bottom field
SEI_PIC_STRUCT_TOP_BOTTOM
3: top field, bottom field, in that order
SEI_PIC_STRUCT_BOTTOM_TOP
4: bottom field, top field, in that order
SEI_PIC_STRUCT_TOP_BOTTOM_TOP
5: top field, bottom field, top field repeated, in that order
SEI_PIC_STRUCT_BOTTOM_TOP_BOTTOM
6: bottom field, top field, bottom field repeated, in that order
SEI_PIC_STRUCT_FRAME_DOUBLING
7: frame doubling
SEI_PIC_STRUCT_FRAME_TRIPLING
8: frame tripling
Definition at line 41 of file h264_sei.h.
SEI_FpaType
enum SEI_FpaType
frame_packing_arrangement types
Enumerator
SEI_FPA_TYPE_CHECKERBOARD
SEI_FPA_TYPE_INTERLEAVE_COLUMN
SEI_FPA_TYPE_INTERLEAVE_ROW
SEI_FPA_TYPE_SIDE_BY_SIDE
SEI_FPA_TYPE_TOP_BOTTOM
SEI_FPA_TYPE_INTERLEAVE_TEMPORAL
SEI_FPA_TYPE_2D
Definition at line 56 of file h264_sei.h.
Function Documentation
ff_h264_sei_decode()
int ff_h264_sei_decode (H264SEIContext * h, GetBitContext * gb, const struct H264ParamSets * ps, void * logctx)
ff_h264_sei_uninit()
void ff_h264_sei_uninit (H264SEIContext * h)
Reset SEI values at the beginning of the frame.
Definition at line 41 of file h264_sei.c.
Referenced by decode_nal_units(), ff_h264_flush_change(), h264_close(), h264_decode_end(), h264_init_context(), and parse_nal_units().
ff_h264_sei_stereo_mode()
const char* ff_h264_sei_stereo_mode (const H264SEIFramePacking * h)
Get stereo_mode string from the h264 frame_packing_arrangement.
Definition at line 454 of file h264_sei.c.
Referenced by output_frame().