FFmpeg: libavcodec/h264qpel.h File Reference
h264qpel.h File Reference
#include "qpeldsp.h"
Data Structures
struct H264QpelContext
Functions
void ff_h264qpel_init (H264QpelContext *c, int bit_depth)
void ff_h264qpel_init_aarch64 (H264QpelContext *c, int bit_depth)
void ff_h264qpel_init_arm (H264QpelContext *c, int bit_depth)
void ff_h264qpel_init_ppc (H264QpelContext *c, int bit_depth)
void ff_h264qpel_init_x86 (H264QpelContext *c, int bit_depth)
void ff_h264qpel_init_mips (H264QpelContext *c, int bit_depth)
Function Documentation
ff_h264qpel_init()
void ff_h264qpel_init (H264QpelContext * c, int bit_depth)
Definition at line 49 of file h264qpel.c.
Referenced by checkasm_check_h264qpel(), ff_rv30dsp_init(), ff_rv40dsp_init(), h264_slice_header_init(), and mca().
ff_h264qpel_init_aarch64()
void ff_h264qpel_init_aarch64 (H264QpelContext * c, int bit_depth)
Definition at line 98 of file h264qpel_init_aarch64.c.
Referenced by ff_h264qpel_init().
ff_h264qpel_init_arm()
void ff_h264qpel_init_arm (H264QpelContext * c, int bit_depth)
Definition at line 97 of file h264qpel_init_arm.c.
Referenced by ff_h264qpel_init().
ff_h264qpel_init_ppc()
void ff_h264qpel_init_ppc (H264QpelContext * c, int bit_depth)
Definition at line 280 of file h264qpel.c.
Referenced by ff_h264qpel_init().
ff_h264qpel_init_x86()
void ff_h264qpel_init_x86 (H264QpelContext * c, int bit_depth)
Definition at line 538 of file h264_qpel.c.
Referenced by ff_h264qpel_init().
ff_h264qpel_init_mips()
void ff_h264qpel_init_mips (H264QpelContext * c, int bit_depth)
Definition at line 241 of file h264qpel_init_mips.c.
Referenced by ff_h264qpel_init().