FFmpeg: libavcodec/arm/h264chroma_init_arm.c File Reference
h264chroma_init_arm.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/arm/cpu.h"
#include "libavcodec/h264chroma.h"
Functions
void ff_put_h264_chroma_mc8_neon (uint8_t *, uint8_t *, int, int, int, int)
void ff_put_h264_chroma_mc4_neon (uint8_t *, uint8_t *, int, int, int, int)
void ff_put_h264_chroma_mc2_neon (uint8_t *, uint8_t *, int, int, int, int)
void ff_avg_h264_chroma_mc8_neon (uint8_t *, uint8_t *, int, int, int, int)
void ff_avg_h264_chroma_mc4_neon (uint8_t *, uint8_t *, int, int, int, int)
void ff_avg_h264_chroma_mc2_neon (uint8_t *, uint8_t *, int, int, int, int)
av_cold void ff_h264chroma_init_arm (H264ChromaContext *c, int bit_depth)
Function Documentation
ff_put_h264_chroma_mc8_neon()
void ff_put_h264_chroma_mc8_neon (uint8_t * , uint8_t * , int , int , int , int)
Referenced by ff_h264chroma_init_arm().
ff_put_h264_chroma_mc4_neon()
void ff_put_h264_chroma_mc4_neon (uint8_t * , uint8_t * , int , int , int , int)
Referenced by ff_h264chroma_init_arm().
ff_put_h264_chroma_mc2_neon()
void ff_put_h264_chroma_mc2_neon (uint8_t * , uint8_t * , int , int , int , int)
Referenced by ff_h264chroma_init_arm().
ff_avg_h264_chroma_mc8_neon()
void ff_avg_h264_chroma_mc8_neon (uint8_t * , uint8_t * , int , int , int , int)
Referenced by ff_h264chroma_init_arm().
ff_avg_h264_chroma_mc4_neon()
void ff_avg_h264_chroma_mc4_neon (uint8_t * , uint8_t * , int , int , int , int)
Referenced by ff_h264chroma_init_arm().
ff_avg_h264_chroma_mc2_neon()
void ff_avg_h264_chroma_mc2_neon (uint8_t * , uint8_t * , int , int , int , int)
Referenced by ff_h264chroma_init_arm().
ff_h264chroma_init_arm()
av_cold void ff_h264chroma_init_arm (H264ChromaContext * c, int bit_depth)
Definition at line 37 of file h264chroma_init_arm.c.
Referenced by ff_h264chroma_init().