FFmpeg: libavcodec/h264chroma.h File Reference
h264chroma.h File Reference
#include <stdint.h>
Data Structures
struct H264ChromaContext
Typedefs
typedef void(* h264_chroma_mc_func) (uint8_t *dst, uint8_t *src, int srcStride, int h, int x, int y)
Functions
void ff_h264chroma_init (H264ChromaContext *c, int bit_depth)
void ff_h264chroma_init_aarch64 (H264ChromaContext *c, int bit_depth)
void ff_h264chroma_init_arm (H264ChromaContext *c, int bit_depth)
void ff_h264chroma_init_ppc (H264ChromaContext *c, int bit_depth)
void ff_h264chroma_init_x86 (H264ChromaContext *c, int bit_depth)
void ff_h264chroma_init_mips (H264ChromaContext *c, int bit_depth)
Typedef Documentation
h264_chroma_mc_func
typedef void(* h264_chroma_mc_func) (uint8_t *dst, uint8_t *src, int srcStride, int h, int x, int y)
Definition at line 24 of file h264chroma.h.
Function Documentation
ff_h264chroma_init()
void ff_h264chroma_init (H264ChromaContext * c, int bit_depth)
Definition at line 41 of file h264chroma.c.
Referenced by dct_init(), ff_cavs_init(), ff_rv30dsp_init(), ff_vp56_init_context(), h264_slice_header_init(), and vc1_decode_init().
ff_h264chroma_init_aarch64()
void ff_h264chroma_init_aarch64 (H264ChromaContext * c, int bit_depth)
Definition at line 45 of file h264chroma_init_aarch64.c.
Referenced by ff_h264chroma_init().
ff_h264chroma_init_arm()
void ff_h264chroma_init_arm (H264ChromaContext * c, int bit_depth)
Definition at line 37 of file h264chroma_init_arm.c.
Referenced by ff_h264chroma_init().
ff_h264chroma_init_ppc()
void ff_h264chroma_init_ppc (H264ChromaContext * c, int bit_depth)
Definition at line 51 of file h264chroma_init.c.
Referenced by ff_h264chroma_init().
ff_h264chroma_init_x86()
void ff_h264chroma_init_x86 (H264ChromaContext * c, int bit_depth)
Definition at line 70 of file h264chroma_init.c.
Referenced by ff_h264chroma_init().
ff_h264chroma_init_mips()
void ff_h264chroma_init_mips (H264ChromaContext * c, int bit_depth)
Definition at line 55 of file h264chroma_init_mips.c.
Referenced by ff_h264chroma_init().