FFmpeg: libavcodec/aarch64/h264qpel_init_aarch64.c File Reference
h264qpel_init_aarch64.c File Reference
#include <stdint.h>
#include "config.h"
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/aarch64/cpu.h"
#include "libavcodec/h264qpel.h"
Functions
void ff_put_h264_qpel16_mc00_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc10_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc20_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc30_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc01_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc11_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc21_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc31_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc02_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc12_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc22_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc32_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc03_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc13_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc23_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc33_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc00_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc10_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc20_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc30_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc01_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc11_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc21_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc31_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc02_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc12_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc22_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc32_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc03_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc13_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc23_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc33_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc00_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc10_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc20_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc30_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc01_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc11_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc21_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc31_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc02_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc12_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc22_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc32_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc03_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc13_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc23_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc33_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc00_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc10_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc20_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc30_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc01_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc11_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc21_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc31_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc02_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc12_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc22_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc32_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc03_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc13_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc23_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc33_neon (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
av_cold void ff_h264qpel_init_aarch64 (H264QpelContext *c, int bit_depth)
Function Documentation
ff_put_h264_qpel16_mc00_neon()
void ff_put_h264_qpel16_mc00_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel16_mc10_neon()
void ff_put_h264_qpel16_mc10_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel16_mc20_neon()
void ff_put_h264_qpel16_mc20_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel16_mc30_neon()
void ff_put_h264_qpel16_mc30_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel16_mc01_neon()
void ff_put_h264_qpel16_mc01_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel16_mc11_neon()
void ff_put_h264_qpel16_mc11_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel16_mc21_neon()
void ff_put_h264_qpel16_mc21_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel16_mc31_neon()
void ff_put_h264_qpel16_mc31_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel16_mc02_neon()
void ff_put_h264_qpel16_mc02_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel16_mc12_neon()
void ff_put_h264_qpel16_mc12_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel16_mc22_neon()
void ff_put_h264_qpel16_mc22_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel16_mc32_neon()
void ff_put_h264_qpel16_mc32_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel16_mc03_neon()
void ff_put_h264_qpel16_mc03_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel16_mc13_neon()
void ff_put_h264_qpel16_mc13_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel16_mc23_neon()
void ff_put_h264_qpel16_mc23_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel16_mc33_neon()
void ff_put_h264_qpel16_mc33_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel8_mc00_neon()
void ff_put_h264_qpel8_mc00_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel8_mc10_neon()
void ff_put_h264_qpel8_mc10_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel8_mc20_neon()
void ff_put_h264_qpel8_mc20_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel8_mc30_neon()
void ff_put_h264_qpel8_mc30_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel8_mc01_neon()
void ff_put_h264_qpel8_mc01_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel8_mc11_neon()
void ff_put_h264_qpel8_mc11_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel8_mc21_neon()
void ff_put_h264_qpel8_mc21_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel8_mc31_neon()
void ff_put_h264_qpel8_mc31_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel8_mc02_neon()
void ff_put_h264_qpel8_mc02_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel8_mc12_neon()
void ff_put_h264_qpel8_mc12_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel8_mc22_neon()
void ff_put_h264_qpel8_mc22_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel8_mc32_neon()
void ff_put_h264_qpel8_mc32_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel8_mc03_neon()
void ff_put_h264_qpel8_mc03_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel8_mc13_neon()
void ff_put_h264_qpel8_mc13_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel8_mc23_neon()
void ff_put_h264_qpel8_mc23_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_put_h264_qpel8_mc33_neon()
void ff_put_h264_qpel8_mc33_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel16_mc00_neon()
void ff_avg_h264_qpel16_mc00_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel16_mc10_neon()
void ff_avg_h264_qpel16_mc10_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel16_mc20_neon()
void ff_avg_h264_qpel16_mc20_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel16_mc30_neon()
void ff_avg_h264_qpel16_mc30_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel16_mc01_neon()
void ff_avg_h264_qpel16_mc01_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel16_mc11_neon()
void ff_avg_h264_qpel16_mc11_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel16_mc21_neon()
void ff_avg_h264_qpel16_mc21_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel16_mc31_neon()
void ff_avg_h264_qpel16_mc31_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel16_mc02_neon()
void ff_avg_h264_qpel16_mc02_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel16_mc12_neon()
void ff_avg_h264_qpel16_mc12_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel16_mc22_neon()
void ff_avg_h264_qpel16_mc22_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel16_mc32_neon()
void ff_avg_h264_qpel16_mc32_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel16_mc03_neon()
void ff_avg_h264_qpel16_mc03_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel16_mc13_neon()
void ff_avg_h264_qpel16_mc13_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel16_mc23_neon()
void ff_avg_h264_qpel16_mc23_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel16_mc33_neon()
void ff_avg_h264_qpel16_mc33_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel8_mc00_neon()
void ff_avg_h264_qpel8_mc00_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel8_mc10_neon()
void ff_avg_h264_qpel8_mc10_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel8_mc20_neon()
void ff_avg_h264_qpel8_mc20_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel8_mc30_neon()
void ff_avg_h264_qpel8_mc30_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel8_mc01_neon()
void ff_avg_h264_qpel8_mc01_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel8_mc11_neon()
void ff_avg_h264_qpel8_mc11_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel8_mc21_neon()
void ff_avg_h264_qpel8_mc21_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel8_mc31_neon()
void ff_avg_h264_qpel8_mc31_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel8_mc02_neon()
void ff_avg_h264_qpel8_mc02_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel8_mc12_neon()
void ff_avg_h264_qpel8_mc12_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel8_mc22_neon()
void ff_avg_h264_qpel8_mc22_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel8_mc32_neon()
void ff_avg_h264_qpel8_mc32_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel8_mc03_neon()
void ff_avg_h264_qpel8_mc03_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel8_mc13_neon()
void ff_avg_h264_qpel8_mc13_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel8_mc23_neon()
void ff_avg_h264_qpel8_mc23_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_avg_h264_qpel8_mc33_neon()
void ff_avg_h264_qpel8_mc33_neon (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Referenced by ff_h264qpel_init_aarch64().
ff_h264qpel_init_aarch64()
av_cold void ff_h264qpel_init_aarch64 (H264QpelContext * c, int bit_depth)
Definition at line 98 of file h264qpel_init_aarch64.c.
Referenced by ff_h264qpel_init().