FFmpeg: libavcodec/aarch64/h264dsp_init_aarch64.c File Reference
h264dsp_init_aarch64.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/aarch64/cpu.h"
#include "libavcodec/h264dsp.h"
Functions
void ff_h264_v_loop_filter_luma_neon (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
void ff_h264_h_loop_filter_luma_neon (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
void ff_h264_v_loop_filter_chroma_neon (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
void ff_h264_h_loop_filter_chroma_neon (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
void ff_weight_h264_pixels_16_neon (uint8_t *dst, int stride, int height, int log2_den, int weight, int offset)
void ff_weight_h264_pixels_8_neon (uint8_t *dst, int stride, int height, int log2_den, int weight, int offset)
void ff_weight_h264_pixels_4_neon (uint8_t *dst, int stride, int height, int log2_den, int weight, int offset)
void ff_biweight_h264_pixels_16_neon (uint8_t *dst, uint8_t *src, int stride, int height, int log2_den, int weightd, int weights, int offset)
void ff_biweight_h264_pixels_8_neon (uint8_t *dst, uint8_t *src, int stride, int height, int log2_den, int weightd, int weights, int offset)
void ff_biweight_h264_pixels_4_neon (uint8_t *dst, uint8_t *src, int stride, int height, int log2_den, int weightd, int weights, int offset)
void ff_h264_idct_add_neon (uint8_t *dst, int16_t *block, int stride)
void ff_h264_idct_dc_add_neon (uint8_t *dst, int16_t *block, int stride)
void ff_h264_idct_add16_neon (uint8_t *dst, const int *block_offset, int16_t *block, int stride, const uint8_t nnzc[6 *8])
void ff_h264_idct_add16intra_neon (uint8_t *dst, const int *block_offset, int16_t *block, int stride, const uint8_t nnzc[6 *8])
void ff_h264_idct_add8_neon (uint8_t **dest, const int *block_offset, int16_t *block, int stride, const uint8_t nnzc[6 *8])
void ff_h264_idct8_add_neon (uint8_t *dst, int16_t *block, int stride)
void ff_h264_idct8_dc_add_neon (uint8_t *dst, int16_t *block, int stride)
void ff_h264_idct8_add4_neon (uint8_t *dst, const int *block_offset, int16_t *block, int stride, const uint8_t nnzc[6 *8])
av_cold void ff_h264dsp_init_aarch64 (H264DSPContext *c, const int bit_depth, const int chroma_format_idc)
Function Documentation
ff_h264_v_loop_filter_luma_neon()
void ff_h264_v_loop_filter_luma_neon (uint8_t * pix, int stride, int alpha, int beta, int8_t * tc0)
Referenced by ff_h264dsp_init_aarch64().
ff_h264_h_loop_filter_luma_neon()
void ff_h264_h_loop_filter_luma_neon (uint8_t * pix, int stride, int alpha, int beta, int8_t * tc0)
Referenced by ff_h264dsp_init_aarch64().
ff_h264_v_loop_filter_chroma_neon()
void ff_h264_v_loop_filter_chroma_neon (uint8_t * pix, int stride, int alpha, int beta, int8_t * tc0)
Referenced by ff_h264dsp_init_aarch64().
ff_h264_h_loop_filter_chroma_neon()
void ff_h264_h_loop_filter_chroma_neon (uint8_t * pix, int stride, int alpha, int beta, int8_t * tc0)
Referenced by ff_h264dsp_init_aarch64().
ff_weight_h264_pixels_16_neon()
void ff_weight_h264_pixels_16_neon (uint8_t * dst, int stride, int height, int log2_den, int weight, int offset)
Referenced by ff_h264dsp_init_aarch64().
ff_weight_h264_pixels_8_neon()
void ff_weight_h264_pixels_8_neon (uint8_t * dst, int stride, int height, int log2_den, int weight, int offset)
Referenced by ff_h264dsp_init_aarch64().
ff_weight_h264_pixels_4_neon()
void ff_weight_h264_pixels_4_neon (uint8_t * dst, int stride, int height, int log2_den, int weight, int offset)
Referenced by ff_h264dsp_init_aarch64().
ff_biweight_h264_pixels_16_neon()
void ff_biweight_h264_pixels_16_neon (uint8_t * dst, uint8_t * src, int stride, int height, int log2_den, int weightd, int weights, int offset)
Referenced by ff_h264dsp_init_aarch64().
ff_biweight_h264_pixels_8_neon()
void ff_biweight_h264_pixels_8_neon (uint8_t * dst, uint8_t * src, int stride, int height, int log2_den, int weightd, int weights, int offset)
Referenced by ff_h264dsp_init_aarch64().
ff_biweight_h264_pixels_4_neon()
void ff_biweight_h264_pixels_4_neon (uint8_t * dst, uint8_t * src, int stride, int height, int log2_den, int weightd, int weights, int offset)
Referenced by ff_h264dsp_init_aarch64().
ff_h264_idct_add_neon()
void ff_h264_idct_add_neon (uint8_t * dst, int16_t * block, int stride)
Referenced by ff_h264dsp_init_aarch64().
ff_h264_idct_dc_add_neon()
void ff_h264_idct_dc_add_neon (uint8_t * dst, int16_t * block, int stride)
Referenced by ff_h264dsp_init_aarch64().
ff_h264_idct_add16_neon()
void ff_h264_idct_add16_neon (uint8_t * dst, const int * block_offset, int16_t * block, int stride, const uint8_t nnzc[6 *8])
Referenced by ff_h264dsp_init_aarch64().
ff_h264_idct_add16intra_neon()
void ff_h264_idct_add16intra_neon (uint8_t * dst, const int * block_offset, int16_t * block, int stride, const uint8_t nnzc[6 *8])
Referenced by ff_h264dsp_init_aarch64().
ff_h264_idct_add8_neon()
void ff_h264_idct_add8_neon (uint8_t ** dest, const int * block_offset, int16_t * block, int stride, const uint8_t nnzc[6 *8])
Referenced by ff_h264dsp_init_aarch64().
ff_h264_idct8_add_neon()
void ff_h264_idct8_add_neon (uint8_t * dst, int16_t * block, int stride)
Referenced by ff_h264dsp_init_aarch64().
ff_h264_idct8_dc_add_neon()
void ff_h264_idct8_dc_add_neon (uint8_t * dst, int16_t * block, int stride)
Referenced by ff_h264dsp_init_aarch64().
ff_h264_idct8_add4_neon()
void ff_h264_idct8_add4_neon (uint8_t * dst, const int * block_offset, int16_t * block, int stride, const uint8_t nnzc[6 *8])
Referenced by ff_h264dsp_init_aarch64().
ff_h264dsp_init_aarch64()
av_cold void ff_h264dsp_init_aarch64 (H264DSPContext * c, const int bit_depth, const int chroma_format_idc)
Definition at line 72 of file h264dsp_init_aarch64.c.
Referenced by ff_h264dsp_init().