FFmpeg: libavcodec/h264_parse.h File Reference
h264_parse.h File Reference
H.264 decoder/parser shared code.
#include "get_bits.h"
#include "h264_ps.h"
Data Structures
struct H264PredWeightTable
struct H264POCContext
Functions
int ff_h264_pred_weight_table (GetBitContext *gb, const SPS *sps, const int *ref_count, int slice_type_nos, H264PredWeightTable *pwt, void *logctx)
int ff_h264_check_intra4x4_pred_mode (int8_t *pred_mode_cache, void *logctx, int top_samples_available, int left_samples_available)
Check if the top & left blocks are available if needed & change the dc mode so it only uses the available blocks.
int ff_h264_check_intra_pred_mode (void *logctx, int top_samples_available, int left_samples_available, int mode, int is_chroma)
Check if the top & left blocks are available if needed & change the dc mode so it only uses the available blocks.
int ff_h264_parse_ref_count (int *plist_count, int ref_count[2], GetBitContext *gb, const PPS *pps, int slice_type_nos, int picture_structure, void *logctx)
int ff_h264_init_poc (int pic_field_poc[2], int *pic_poc, const SPS *sps, H264POCContext *poc, int picture_structure, int nal_ref_idc)
int ff_h264_decode_extradata (const uint8_t *data, int size, H264ParamSets *ps, int *is_avc, int *nal_length_size, int err_recognition, void *logctx)
int ff_h264_get_profile (const SPS *sps)
compute profile from sps
Detailed Description
H.264 decoder/parser shared code.
Definition in file h264_parse.h.
Function Documentation
ff_h264_pred_weight_table()
int ff_h264_pred_weight_table (GetBitContext * gb, const SPS * sps, const int * ref_count, int slice_type_nos, H264PredWeightTable * pwt, void * logctx)
Definition at line 27 of file h264_parse.c.
Referenced by h264_slice_header_parse(), and scan_mmco_reset().
ff_h264_check_intra4x4_pred_mode()
int ff_h264_check_intra4x4_pred_mode (int8_t * pred_mode_cache, void * logctx, int top_samples_available, int left_samples_available)
Check if the top & left blocks are available if needed & change the dc mode so it only uses the available blocks.
Check if the top & left blocks are available if needed & change the dc mode so it only uses the available blocks.
Definition at line 113 of file h264_parse.c.
Referenced by ff_h264_decode_mb_cabac(), ff_h264_decode_mb_cavlc(), and svq3_decode_mb().
ff_h264_check_intra_pred_mode()
int ff_h264_check_intra_pred_mode (void * logctx, int top_samples_available, int left_samples_available, int mode, int is_chroma)
Check if the top & left blocks are available if needed & change the dc mode so it only uses the available blocks.
Check if the top & left blocks are available if needed & change the dc mode so it only uses the available blocks.
Definition at line 161 of file h264_parse.c.
Referenced by ff_h264_decode_mb_cabac(), ff_h264_decode_mb_cavlc(), and svq3_decode_mb().
ff_h264_parse_ref_count()
int ff_h264_parse_ref_count (int * plist_count, int ref_count[2], GetBitContext * gb, const PPS * pps, int slice_type_nos, int picture_structure, void * logctx)
Definition at line 201 of file h264_parse.c.
Referenced by h264_slice_header_parse(), and scan_mmco_reset().
ff_h264_init_poc()
int ff_h264_init_poc (int pic_field_poc[2], int * pic_poc, const SPS * sps, H264POCContext * poc, int picture_structure, int nal_ref_idc)
Definition at line 254 of file h264_parse.c.
Referenced by h264_field_start(), and parse_nal_units().
ff_h264_decode_extradata()
int ff_h264_decode_extradata (const uint8_t * data, int size, H264ParamSets * ps, int * is_avc, int * nal_length_size, int err_recognition, void * logctx)
Definition at line 422 of file h264_parse.c.
Referenced by ff_h264_decode_init(), h264_decode_frame(), h264_parse(), and mediacodec_decode_close().
ff_h264_get_profile()
int ff_h264_get_profile (const SPS * sps)
compute profile from sps
compute profile from sps
Parameters
sps SPS
Returns
profile as defined by FF_PROFILE_H264_*
Definition at line 489 of file h264_parse.c.
Referenced by h264_init_ps(), and parse_nal_units().