FFmpeg: libavcodec/mips/h264dsp_mips.h File Reference
h264dsp_mips.h File Reference
#include "libavcodec/h264dec.h"
#include "constants.h"
Functions
void ff_h264_h_lpf_luma_inter_msa (uint8_t *src, int stride, int alpha, int beta, int8_t *tc0)
void ff_h264_v_lpf_luma_inter_msa (uint8_t *src, int stride, int alpha, int beta, int8_t *tc0)
void ff_h264_h_lpf_chroma_inter_msa (uint8_t *src, int stride, int alpha, int beta, int8_t *tc0)
void ff_h264_v_lpf_chroma_inter_msa (uint8_t *src, int stride, int alpha, int beta, int8_t *tc0)
void ff_h264_h_loop_filter_chroma422_msa (uint8_t *src, int32_t stride, int32_t alpha, int32_t beta, int8_t *tc0)
void ff_h264_h_loop_filter_chroma422_mbaff_msa (uint8_t *src, int32_t stride, int32_t alpha, int32_t beta, int8_t *tc0)
void ff_h264_h_loop_filter_luma_mbaff_msa (uint8_t *src, int32_t stride, int32_t alpha, int32_t beta, int8_t *tc0)
void ff_h264_idct_add_msa (uint8_t *dst, int16_t *src, int32_t dst_stride)
void ff_h264_idct4x4_addblk_dc_msa (uint8_t *dst, int16_t *src, int32_t dst_stride)
void ff_h264_deq_idct_luma_dc_msa (int16_t *dst, int16_t *src, int32_t de_q_val)
void ff_h264_idct_add16_msa (uint8_t *dst, const int32_t *blk_offset, int16_t *block, int32_t stride, const uint8_t nnzc[15 *8])
void ff_h264_idct_add16_intra_msa (uint8_t *dst, const int32_t *blk_offset, int16_t *block, int32_t dst_stride, const uint8_t nnzc[15 *8])
void ff_h264_idct_add8_msa (uint8_t **dst, const int32_t *blk_offset, int16_t *block, int32_t dst_stride, const uint8_t nnzc[15 *8])
void ff_h264_idct_add8_422_msa (uint8_t **dst, const int32_t *blk_offset, int16_t *block, int32_t dst_stride, const uint8_t nnzc[15 *8])
void ff_h264_idct8_addblk_msa (uint8_t *dst, int16_t *src, int32_t dst_stride)
void ff_h264_idct8_dc_addblk_msa (uint8_t *dst, int16_t *src, int32_t dst_stride)
void ff_h264_idct8_add4_msa (uint8_t *dst, const int *blk_offset, int16_t *blk, int dst_stride, const uint8_t nnzc[15 *8])
void ff_h264_h_lpf_luma_intra_msa (uint8_t *src, int stride, int alpha, int beta)
void ff_h264_v_lpf_luma_intra_msa (uint8_t *src, int stride, int alpha, int beta)
void ff_h264_h_lpf_chroma_intra_msa (uint8_t *src, int stride, int alpha, int beta)
void ff_h264_v_lpf_chroma_intra_msa (uint8_t *src, int stride, int alpha, int beta)
void ff_h264_h_loop_filter_luma_mbaff_intra_msa (uint8_t *src, int stride, int alpha, int beta)
void ff_biweight_h264_pixels16_8_msa (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int height, int log2_denom, int weightd, int weights, int offset)
void ff_biweight_h264_pixels8_8_msa (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int height, int log2_denom, int weightd, int weights, int offset)
void ff_biweight_h264_pixels4_8_msa (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int height, int log2_denom, int weightd, int weights, int offset)
void ff_weight_h264_pixels16_8_msa (uint8_t *src, ptrdiff_t stride, int height, int log2_denom, int weight, int offset)
void ff_weight_h264_pixels8_8_msa (uint8_t *src, ptrdiff_t stride, int height, int log2_denom, int weight, int offset)
void ff_weight_h264_pixels4_8_msa (uint8_t *src, ptrdiff_t stride, int height, int log2_denom, int weight, int offset)
void ff_put_h264_qpel16_mc00_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc10_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc20_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc30_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc01_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc11_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc21_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc31_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc02_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc12_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc22_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc32_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc03_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc13_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc23_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc33_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc00_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc10_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc20_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc30_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc01_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc11_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc21_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc31_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc02_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc12_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc22_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc32_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc03_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc13_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc23_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc33_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc00_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc10_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc20_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc30_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc01_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc11_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc21_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc31_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc02_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc12_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc22_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc32_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc03_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc13_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc23_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc33_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc00_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc10_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc20_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc30_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc01_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc11_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc21_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc31_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc02_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc12_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc22_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc32_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc03_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc13_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc23_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc33_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc00_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc10_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc20_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc30_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc01_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc11_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc21_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc31_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc02_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc12_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc22_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc32_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc03_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc13_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc23_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc33_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc00_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc10_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc20_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc30_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc01_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc11_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc21_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc31_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc02_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc12_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc22_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc32_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc03_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc13_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc23_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc33_msa (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_h264_intra_predict_plane_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_predict_dc_4blk_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_predict_hor_dc_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_predict_vert_dc_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_predict_mad_cow_dc_l0t_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_predict_mad_cow_dc_0lt_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_predict_mad_cow_dc_l00_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_predict_mad_cow_dc_0l0_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_predict_plane_16x16_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_pred_vert_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_pred_horiz_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_pred_dc_16x16_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_pred_vert_16x16_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_pred_horiz_16x16_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_pred_dc_left_16x16_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_pred_dc_top_16x16_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_pred_dc_128_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_pred_dc_128_16x16_msa (uint8_t *src, ptrdiff_t stride)
void ff_vp8_pred8x8_127_dc_8_msa (uint8_t *src, ptrdiff_t stride)
void ff_vp8_pred8x8_129_dc_8_msa (uint8_t *src, ptrdiff_t stride)
void ff_vp8_pred16x16_127_dc_8_msa (uint8_t *src, ptrdiff_t stride)
void ff_vp8_pred16x16_129_dc_8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_add_pixels4_8_mmi (uint8_t *_dst, int16_t *_src, int stride)
void ff_h264_idct_add_8_mmi (uint8_t *dst, int16_t *block, int stride)
void ff_h264_idct8_add_8_mmi (uint8_t *dst, int16_t *block, int stride)
void ff_h264_idct_dc_add_8_mmi (uint8_t *dst, int16_t *block, int stride)
void ff_h264_idct8_dc_add_8_mmi (uint8_t *dst, int16_t *block, int stride)
void ff_h264_idct_add16_8_mmi (uint8_t *dst, const int *block_offset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
void ff_h264_idct_add16intra_8_mmi (uint8_t *dst, const int *block_offset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
void ff_h264_idct8_add4_8_mmi (uint8_t *dst, const int *block_offset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
void ff_h264_idct_add8_8_mmi (uint8_t **dest, const int *block_offset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
void ff_h264_idct_add8_422_8_mmi (uint8_t **dest, const int *block_offset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
void ff_h264_luma_dc_dequant_idct_8_mmi (int16_t *output, int16_t *input, int qmul)
void ff_h264_chroma_dc_dequant_idct_8_mmi (int16_t *block, int qmul)
void ff_h264_chroma422_dc_dequant_idct_8_mmi (int16_t *block, int qmul)
void ff_h264_weight_pixels16_8_mmi (uint8_t *block, ptrdiff_t stride, int height, int log2_denom, int weight, int offset)
void ff_h264_biweight_pixels16_8_mmi (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int height, int log2_denom, int weightd, int weights, int offset)
void ff_h264_weight_pixels8_8_mmi (uint8_t *block, ptrdiff_t stride, int height, int log2_denom, int weight, int offset)
void ff_h264_biweight_pixels8_8_mmi (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int height, int log2_denom, int weightd, int weights, int offset)
void ff_h264_weight_pixels4_8_mmi (uint8_t *block, ptrdiff_t stride, int height, int log2_denom, int weight, int offset)
void ff_h264_biweight_pixels4_8_mmi (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int height, int log2_denom, int weightd, int weights, int offset)
void ff_deblock_v_chroma_8_mmi (uint8_t *pix, ptrdiff_t stride, int alpha, int beta, int8_t *tc0)
void ff_deblock_v_chroma_intra_8_mmi (uint8_t *pix, int stride, int alpha, int beta)
void ff_deblock_h_chroma_8_mmi (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
void ff_deblock_h_chroma_intra_8_mmi (uint8_t *pix, int stride, int alpha, int beta)
void ff_deblock_v_luma_8_mmi (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
void ff_deblock_v_luma_intra_8_mmi (uint8_t *pix, int stride, int alpha, int beta)
void ff_deblock_h_luma_8_mmi (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
void ff_deblock_h_luma_intra_8_mmi (uint8_t *pix, int stride, int alpha, int beta)
void ff_deblock_v8_luma_8_mmi (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
void ff_deblock_v8_luma_intra_8_mmi (uint8_t *pix, int stride, int alpha, int beta)
void ff_put_h264_qpel16_mc00_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc10_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc20_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc30_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc01_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc11_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc21_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc31_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc02_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc12_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc22_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc32_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc03_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc13_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc23_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel16_mc33_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc00_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc10_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc20_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc30_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc01_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc11_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc21_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc31_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc02_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc12_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc22_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc32_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc03_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc13_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc23_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel8_mc33_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc00_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc10_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc20_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc30_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc01_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc11_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc21_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc31_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc02_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc12_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc22_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc32_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc03_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc13_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc23_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_put_h264_qpel4_mc33_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc00_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc10_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc20_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc30_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc01_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc11_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc21_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc31_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc02_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc12_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc22_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc32_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc03_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc13_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc23_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel16_mc33_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc00_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc10_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc20_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc30_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc01_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc11_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc21_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc31_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc02_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc12_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc22_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc32_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc03_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc13_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc23_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel8_mc33_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc00_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc10_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc20_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc30_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc01_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc11_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc21_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc31_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc02_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc12_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc22_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc32_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc03_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc13_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc23_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
void ff_avg_h264_qpel4_mc33_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_stride)
Function Documentation
ff_h264_h_lpf_luma_inter_msa()
void ff_h264_h_lpf_luma_inter_msa (uint8_t * src, int stride, int alpha, int beta, int8_t * tc0)
Definition at line 2343 of file h264dsp_msa.c.
ff_h264_v_lpf_luma_inter_msa()
void ff_h264_v_lpf_luma_inter_msa (uint8_t * src, int stride, int alpha, int beta, int8_t * tc0)
Definition at line 2365 of file h264dsp_msa.c.
ff_h264_h_lpf_chroma_inter_msa()
void ff_h264_h_lpf_chroma_inter_msa (uint8_t * src, int stride, int alpha, int beta, int8_t * tc0)
Definition at line 2388 of file h264dsp_msa.c.
ff_h264_v_lpf_chroma_inter_msa()
void ff_h264_v_lpf_chroma_inter_msa (uint8_t * src, int stride, int alpha, int beta, int8_t * tc0)
Definition at line 2410 of file h264dsp_msa.c.
ff_h264_h_loop_filter_chroma422_msa()
void ff_h264_h_loop_filter_chroma422_msa (uint8_t * src, int32_t stride, int32_t alpha, int32_t beta, int8_t * tc0)
Definition at line 2464 of file h264dsp_msa.c.
ff_h264_h_loop_filter_chroma422_mbaff_msa()
void ff_h264_h_loop_filter_chroma422_mbaff_msa (uint8_t * src, int32_t stride, int32_t alpha, int32_t beta, int8_t * tc0)
Definition at line 2472 of file h264dsp_msa.c.
ff_h264_h_loop_filter_luma_mbaff_msa()
void ff_h264_h_loop_filter_luma_mbaff_msa (uint8_t * src, int32_t stride, int32_t alpha, int32_t beta, int8_t * tc0)
Definition at line 2481 of file h264dsp_msa.c.
ff_h264_idct_add_msa()
void ff_h264_idct_add_msa (uint8_t * dst, int16_t * src, int32_t dst_stride)
Definition at line 320 of file h264idct_msa.c.
Referenced by ff_h264_idct_add16_intra_msa(), ff_h264_idct_add16_msa(), ff_h264_idct_add8_422_msa(), and ff_h264_idct_add8_msa().
ff_h264_idct4x4_addblk_dc_msa()
void ff_h264_idct4x4_addblk_dc_msa (uint8_t * dst, int16_t * src, int32_t dst_stride)
Definition at line 334 of file h264idct_msa.c.
Referenced by ff_h264_idct_add16_intra_msa(), ff_h264_idct_add16_msa(), ff_h264_idct_add8_422_msa(), and ff_h264_idct_add8_msa().
ff_h264_deq_idct_luma_dc_msa()
void ff_h264_deq_idct_luma_dc_msa (int16_t * dst, int16_t * src, int32_t de_q_val)
Definition at line 465 of file h264idct_msa.c.
ff_h264_idct_add16_msa()
void ff_h264_idct_add16_msa (uint8_t * dst, const int32_t * blk_offset, int16_t * block, int32_t stride, const uint8_t nnzc[15 *8])
Definition at line 346 of file h264idct_msa.c.
ff_h264_idct_add16_intra_msa()
void ff_h264_idct_add16_intra_msa (uint8_t * dst, const int32_t * blk_offset, int16_t * block, int32_t dst_stride, const uint8_t nnzc[15 *8])
Definition at line 446 of file h264idct_msa.c.
ff_h264_idct_add8_msa()
void ff_h264_idct_add8_msa (uint8_t ** dst, const int32_t * blk_offset, int16_t * block, int32_t dst_stride, const uint8_t nnzc[15 *8])
Definition at line 391 of file h264idct_msa.c.
ff_h264_idct_add8_422_msa()
void ff_h264_idct_add8_422_msa (uint8_t ** dst, const int32_t * blk_offset, int16_t * block, int32_t dst_stride, const uint8_t nnzc[15 *8])
Definition at line 412 of file h264idct_msa.c.
ff_h264_idct8_addblk_msa()
void ff_h264_idct8_addblk_msa (uint8_t * dst, int16_t * src, int32_t dst_stride)
Definition at line 327 of file h264idct_msa.c.
Referenced by ff_h264_idct8_add4_msa().
ff_h264_idct8_dc_addblk_msa()
void ff_h264_idct8_dc_addblk_msa (uint8_t * dst, int16_t * src, int32_t dst_stride)
Definition at line 340 of file h264idct_msa.c.
Referenced by ff_h264_idct8_add4_msa().
ff_h264_idct8_add4_msa()
void ff_h264_idct8_add4_msa (uint8_t * dst, const int * blk_offset, int16_t * blk, int dst_stride, const uint8_t nnzc[15 *8])
ff_h264_h_lpf_luma_intra_msa()
void ff_h264_h_lpf_luma_intra_msa (uint8_t * src, int stride, int alpha, int beta)
Definition at line 2432 of file h264dsp_msa.c.
ff_h264_v_lpf_luma_intra_msa()
void ff_h264_v_lpf_luma_intra_msa (uint8_t * src, int stride, int alpha, int beta)
Definition at line 2440 of file h264dsp_msa.c.
ff_h264_h_lpf_chroma_intra_msa()
void ff_h264_h_lpf_chroma_intra_msa (uint8_t * src, int stride, int alpha, int beta)
Definition at line 2448 of file h264dsp_msa.c.
ff_h264_v_lpf_chroma_intra_msa()
void ff_h264_v_lpf_chroma_intra_msa (uint8_t * src, int stride, int alpha, int beta)
Definition at line 2456 of file h264dsp_msa.c.
ff_h264_h_loop_filter_luma_mbaff_intra_msa()
void ff_h264_h_loop_filter_luma_mbaff_intra_msa (uint8_t * src, int stride, int alpha, int beta)
ff_biweight_h264_pixels16_8_msa()
void ff_biweight_h264_pixels16_8_msa (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int height, int log2_denom, int weightd, int weights, int offset)
Definition at line 2519 of file h264dsp_msa.c.
ff_biweight_h264_pixels8_8_msa()
void ff_biweight_h264_pixels8_8_msa (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int height, int log2_denom, int weightd, int weights, int offset)
Definition at line 2528 of file h264dsp_msa.c.
ff_biweight_h264_pixels4_8_msa()
void ff_biweight_h264_pixels4_8_msa (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int height, int log2_denom, int weightd, int weights, int offset)
Definition at line 2537 of file h264dsp_msa.c.
ff_weight_h264_pixels16_8_msa()
void ff_weight_h264_pixels16_8_msa (uint8_t * src, ptrdiff_t stride, int height, int log2_denom, int weight, int offset)
Definition at line 2498 of file h264dsp_msa.c.
ff_weight_h264_pixels8_8_msa()
void ff_weight_h264_pixels8_8_msa (uint8_t * src, ptrdiff_t stride, int height, int log2_denom, int weight, int offset)
Definition at line 2505 of file h264dsp_msa.c.
ff_weight_h264_pixels4_8_msa()
void ff_weight_h264_pixels4_8_msa (uint8_t * src, ptrdiff_t stride, int height, int log2_denom, int weight, int offset)
Definition at line 2512 of file h264dsp_msa.c.
ff_put_h264_qpel16_mc00_msa()
void ff_put_h264_qpel16_mc00_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2963 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc10_msa()
void ff_put_h264_qpel16_mc10_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2993 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc20_msa()
void ff_put_h264_qpel16_mc20_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3029 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc30_msa()
void ff_put_h264_qpel16_mc30_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2999 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc01_msa()
void ff_put_h264_qpel16_mc01_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3047 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc11_msa()
void ff_put_h264_qpel16_mc11_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3083 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc21_msa()
void ff_put_h264_qpel16_mc21_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3172 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc31_msa()
void ff_put_h264_qpel16_mc31_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3090 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc02_msa()
void ff_put_h264_qpel16_mc02_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3210 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc12_msa()
void ff_put_h264_qpel16_mc12_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3228 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc22_msa()
void ff_put_h264_qpel16_mc22_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3266 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc32_msa()
void ff_put_h264_qpel16_mc32_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3235 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc03_msa()
void ff_put_h264_qpel16_mc03_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3053 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc13_msa()
void ff_put_h264_qpel16_mc13_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3098 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc23_msa()
void ff_put_h264_qpel16_mc23_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3179 of file h264qpel_msa.c.
ff_put_h264_qpel16_mc33_msa()
void ff_put_h264_qpel16_mc33_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3105 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc00_msa()
void ff_put_h264_qpel8_mc00_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2969 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc10_msa()
void ff_put_h264_qpel8_mc10_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3005 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc20_msa()
void ff_put_h264_qpel8_mc20_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3035 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc30_msa()
void ff_put_h264_qpel8_mc30_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3011 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc01_msa()
void ff_put_h264_qpel8_mc01_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3059 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc11_msa()
void ff_put_h264_qpel8_mc11_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3113 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc21_msa()
void ff_put_h264_qpel8_mc21_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3186 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc31_msa()
void ff_put_h264_qpel8_mc31_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3119 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc02_msa()
void ff_put_h264_qpel8_mc02_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3216 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc12_msa()
void ff_put_h264_qpel8_mc12_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3242 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc22_msa()
void ff_put_h264_qpel8_mc22_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3272 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc32_msa()
void ff_put_h264_qpel8_mc32_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3248 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc03_msa()
void ff_put_h264_qpel8_mc03_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3065 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc13_msa()
void ff_put_h264_qpel8_mc13_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3127 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc23_msa()
void ff_put_h264_qpel8_mc23_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3192 of file h264qpel_msa.c.
ff_put_h264_qpel8_mc33_msa()
void ff_put_h264_qpel8_mc33_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3134 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc00_msa()
void ff_put_h264_qpel4_mc00_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
ff_put_h264_qpel4_mc10_msa()
void ff_put_h264_qpel4_mc10_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3017 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc20_msa()
void ff_put_h264_qpel4_mc20_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3041 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc30_msa()
void ff_put_h264_qpel4_mc30_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3023 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc01_msa()
void ff_put_h264_qpel4_mc01_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3071 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc11_msa()
void ff_put_h264_qpel4_mc11_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3143 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc21_msa()
void ff_put_h264_qpel4_mc21_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3198 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc31_msa()
void ff_put_h264_qpel4_mc31_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3149 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc02_msa()
void ff_put_h264_qpel4_mc02_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3222 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc12_msa()
void ff_put_h264_qpel4_mc12_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3254 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc22_msa()
void ff_put_h264_qpel4_mc22_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3278 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc32_msa()
void ff_put_h264_qpel4_mc32_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3260 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc03_msa()
void ff_put_h264_qpel4_mc03_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3077 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc13_msa()
void ff_put_h264_qpel4_mc13_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3157 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc23_msa()
void ff_put_h264_qpel4_mc23_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3204 of file h264qpel_msa.c.
ff_put_h264_qpel4_mc33_msa()
void ff_put_h264_qpel4_mc33_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3164 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc00_msa()
void ff_avg_h264_qpel16_mc00_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2975 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc10_msa()
void ff_avg_h264_qpel16_mc10_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3284 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc20_msa()
void ff_avg_h264_qpel16_mc20_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3320 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc30_msa()
void ff_avg_h264_qpel16_mc30_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3290 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc01_msa()
void ff_avg_h264_qpel16_mc01_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3338 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc11_msa()
void ff_avg_h264_qpel16_mc11_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3380 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc21_msa()
void ff_avg_h264_qpel16_mc21_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3479 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc31_msa()
void ff_avg_h264_qpel16_mc31_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3388 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc02_msa()
void ff_avg_h264_qpel16_mc02_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3521 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc12_msa()
void ff_avg_h264_qpel16_mc12_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3539 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc22_msa()
void ff_avg_h264_qpel16_mc22_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3581 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc32_msa()
void ff_avg_h264_qpel16_mc32_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3546 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc03_msa()
void ff_avg_h264_qpel16_mc03_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3345 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc13_msa()
void ff_avg_h264_qpel16_mc13_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3397 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc23_msa()
void ff_avg_h264_qpel16_mc23_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3486 of file h264qpel_msa.c.
ff_avg_h264_qpel16_mc33_msa()
void ff_avg_h264_qpel16_mc33_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3405 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc00_msa()
void ff_avg_h264_qpel8_mc00_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2981 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc10_msa()
void ff_avg_h264_qpel8_mc10_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3296 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc20_msa()
void ff_avg_h264_qpel8_mc20_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3326 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc30_msa()
void ff_avg_h264_qpel8_mc30_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3302 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc01_msa()
void ff_avg_h264_qpel8_mc01_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3352 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc11_msa()
void ff_avg_h264_qpel8_mc11_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3414 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc21_msa()
void ff_avg_h264_qpel8_mc21_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3493 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc31_msa()
void ff_avg_h264_qpel8_mc31_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3422 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc02_msa()
void ff_avg_h264_qpel8_mc02_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3527 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc12_msa()
void ff_avg_h264_qpel8_mc12_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3553 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc22_msa()
void ff_avg_h264_qpel8_mc22_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3588 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc32_msa()
void ff_avg_h264_qpel8_mc32_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3560 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc03_msa()
void ff_avg_h264_qpel8_mc03_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3359 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc13_msa()
void ff_avg_h264_qpel8_mc13_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3430 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc23_msa()
void ff_avg_h264_qpel8_mc23_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3500 of file h264qpel_msa.c.
ff_avg_h264_qpel8_mc33_msa()
void ff_avg_h264_qpel8_mc33_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3438 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc00_msa()
void ff_avg_h264_qpel4_mc00_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2987 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc10_msa()
void ff_avg_h264_qpel4_mc10_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3308 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc20_msa()
void ff_avg_h264_qpel4_mc20_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3332 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc30_msa()
void ff_avg_h264_qpel4_mc30_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3314 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc01_msa()
void ff_avg_h264_qpel4_mc01_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3366 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc11_msa()
void ff_avg_h264_qpel4_mc11_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3447 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc21_msa()
void ff_avg_h264_qpel4_mc21_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3507 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc31_msa()
void ff_avg_h264_qpel4_mc31_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3455 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc02_msa()
void ff_avg_h264_qpel4_mc02_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3533 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc12_msa()
void ff_avg_h264_qpel4_mc12_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3567 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc22_msa()
void ff_avg_h264_qpel4_mc22_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3595 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc32_msa()
void ff_avg_h264_qpel4_mc32_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3574 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc03_msa()
void ff_avg_h264_qpel4_mc03_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3373 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc13_msa()
void ff_avg_h264_qpel4_mc13_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3463 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc23_msa()
void ff_avg_h264_qpel4_mc23_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3514 of file h264qpel_msa.c.
ff_avg_h264_qpel4_mc33_msa()
void ff_avg_h264_qpel4_mc33_msa (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3471 of file h264qpel_msa.c.
ff_h264_intra_predict_plane_8x8_msa()
void ff_h264_intra_predict_plane_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 583 of file h264pred_msa.c.
ff_h264_intra_predict_dc_4blk_8x8_msa()
void ff_h264_intra_predict_dc_4blk_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 588 of file h264pred_msa.c.
ff_h264_intra_predict_hor_dc_8x8_msa()
void ff_h264_intra_predict_hor_dc_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 593 of file h264pred_msa.c.
ff_h264_intra_predict_vert_dc_8x8_msa()
void ff_h264_intra_predict_vert_dc_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 598 of file h264pred_msa.c.
ff_h264_intra_predict_mad_cow_dc_l0t_8x8_msa()
void ff_h264_intra_predict_mad_cow_dc_l0t_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 603 of file h264pred_msa.c.
ff_h264_intra_predict_mad_cow_dc_0lt_8x8_msa()
void ff_h264_intra_predict_mad_cow_dc_0lt_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 609 of file h264pred_msa.c.
ff_h264_intra_predict_mad_cow_dc_l00_8x8_msa()
void ff_h264_intra_predict_mad_cow_dc_l00_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 615 of file h264pred_msa.c.
ff_h264_intra_predict_mad_cow_dc_0l0_8x8_msa()
void ff_h264_intra_predict_mad_cow_dc_0l0_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 621 of file h264pred_msa.c.
ff_h264_intra_predict_plane_16x16_msa()
void ff_h264_intra_predict_plane_16x16_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 627 of file h264pred_msa.c.
ff_h264_intra_pred_vert_8x8_msa()
void ff_h264_intra_pred_vert_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 632 of file h264pred_msa.c.
ff_h264_intra_pred_horiz_8x8_msa()
void ff_h264_intra_pred_horiz_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 639 of file h264pred_msa.c.
ff_h264_intra_pred_dc_16x16_msa()
void ff_h264_intra_pred_dc_16x16_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 646 of file h264pred_msa.c.
ff_h264_intra_pred_vert_16x16_msa()
void ff_h264_intra_pred_vert_16x16_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 655 of file h264pred_msa.c.
ff_h264_intra_pred_horiz_16x16_msa()
void ff_h264_intra_pred_horiz_16x16_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 662 of file h264pred_msa.c.
ff_h264_intra_pred_dc_left_16x16_msa()
void ff_h264_intra_pred_dc_left_16x16_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 669 of file h264pred_msa.c.
ff_h264_intra_pred_dc_top_16x16_msa()
void ff_h264_intra_pred_dc_top_16x16_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 678 of file h264pred_msa.c.
ff_h264_intra_pred_dc_128_8x8_msa()
void ff_h264_intra_pred_dc_128_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 687 of file h264pred_msa.c.
ff_h264_intra_pred_dc_128_16x16_msa()
void ff_h264_intra_pred_dc_128_16x16_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 696 of file h264pred_msa.c.
ff_vp8_pred8x8_127_dc_8_msa()
void ff_vp8_pred8x8_127_dc_8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 705 of file h264pred_msa.c.
ff_vp8_pred8x8_129_dc_8_msa()
void ff_vp8_pred8x8_129_dc_8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 710 of file h264pred_msa.c.
ff_vp8_pred16x16_127_dc_8_msa()
void ff_vp8_pred16x16_127_dc_8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 715 of file h264pred_msa.c.
ff_vp8_pred16x16_129_dc_8_msa()
void ff_vp8_pred16x16_129_dc_8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 720 of file h264pred_msa.c.
ff_h264_add_pixels4_8_mmi()
void ff_h264_add_pixels4_8_mmi (uint8_t * _dst, int16_t * _src, int stride)
Definition at line 30 of file h264dsp_mmi.c.
ff_h264_idct_add_8_mmi()
void ff_h264_idct_add_8_mmi (uint8_t * dst, int16_t * block, int stride)
Definition at line 78 of file h264dsp_mmi.c.
Referenced by ff_h264_idct_add16_8_mmi(), ff_h264_idct_add16intra_8_mmi(), ff_h264_idct_add8_422_8_mmi(), and ff_h264_idct_add8_8_mmi().
ff_h264_idct8_add_8_mmi()
void ff_h264_idct8_add_8_mmi (uint8_t * dst, int16_t * block, int stride)
Definition at line 173 of file h264dsp_mmi.c.
Referenced by ff_h264_idct8_add4_8_mmi().
ff_h264_idct_dc_add_8_mmi()
void ff_h264_idct_dc_add_8_mmi (uint8_t * dst, int16_t * block, int stride)
Definition at line 644 of file h264dsp_mmi.c.
Referenced by ff_h264_idct_add16_8_mmi(), ff_h264_idct_add16intra_8_mmi(), ff_h264_idct_add8_422_8_mmi(), and ff_h264_idct_add8_8_mmi().
ff_h264_idct8_dc_add_8_mmi()
void ff_h264_idct8_dc_add_8_mmi (uint8_t * dst, int16_t * block, int stride)
Definition at line 688 of file h264dsp_mmi.c.
Referenced by ff_h264_idct8_add4_8_mmi().
ff_h264_idct_add16_8_mmi()
void ff_h264_idct_add16_8_mmi (uint8_t * dst, const int * block_offset, int16_t * block, int stride, const uint8_t nnzc[15 *8])
Definition at line 773 of file h264dsp_mmi.c.
ff_h264_idct_add16intra_8_mmi()
void ff_h264_idct_add16intra_8_mmi (uint8_t * dst, const int * block_offset, int16_t * block, int stride, const uint8_t nnzc[15 *8])
Definition at line 790 of file h264dsp_mmi.c.
ff_h264_idct8_add4_8_mmi()
void ff_h264_idct8_add4_8_mmi (uint8_t * dst, const int * block_offset, int16_t * block, int stride, const uint8_t nnzc[15 *8])
Definition at line 803 of file h264dsp_mmi.c.
ff_h264_idct_add8_8_mmi()
void ff_h264_idct_add8_8_mmi (uint8_t ** dest, const int * block_offset, int16_t * block, int stride, const uint8_t nnzc[15 *8])
Definition at line 820 of file h264dsp_mmi.c.
ff_h264_idct_add8_422_8_mmi()
void ff_h264_idct_add8_422_8_mmi (uint8_t ** dest, const int * block_offset, int16_t * block, int stride, const uint8_t nnzc[15 *8])
Definition at line 836 of file h264dsp_mmi.c.
ff_h264_luma_dc_dequant_idct_8_mmi()
void ff_h264_luma_dc_dequant_idct_8_mmi (int16_t * output, int16_t * input, int qmul)
Definition at line 864 of file h264dsp_mmi.c.
ff_h264_chroma_dc_dequant_idct_8_mmi()
void ff_h264_chroma_dc_dequant_idct_8_mmi (int16_t * block, int qmul)
Definition at line 1124 of file h264dsp_mmi.c.
ff_h264_chroma422_dc_dequant_idct_8_mmi()
void ff_h264_chroma422_dc_dequant_idct_8_mmi (int16_t * block, int qmul)
Definition at line 1091 of file h264dsp_mmi.c.
ff_h264_weight_pixels16_8_mmi()
void ff_h264_weight_pixels16_8_mmi (uint8_t * block, ptrdiff_t stride, int height, int log2_denom, int weight, int offset)
Definition at line 1138 of file h264dsp_mmi.c.
ff_h264_biweight_pixels16_8_mmi()
void ff_h264_biweight_pixels16_8_mmi (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int height, int log2_denom, int weightd, int weights, int offset)
Definition at line 1194 of file h264dsp_mmi.c.
ff_h264_weight_pixels8_8_mmi()
void ff_h264_weight_pixels8_8_mmi (uint8_t * block, ptrdiff_t stride, int height, int log2_denom, int weight, int offset)
Definition at line 1265 of file h264dsp_mmi.c.
ff_h264_biweight_pixels8_8_mmi()
void ff_h264_biweight_pixels8_8_mmi (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int height, int log2_denom, int weightd, int weights, int offset)
Definition at line 1308 of file h264dsp_mmi.c.
ff_h264_weight_pixels4_8_mmi()
void ff_h264_weight_pixels4_8_mmi (uint8_t * block, ptrdiff_t stride, int height, int log2_denom, int weight, int offset)
Definition at line 1360 of file h264dsp_mmi.c.
ff_h264_biweight_pixels4_8_mmi()
void ff_h264_biweight_pixels4_8_mmi (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int height, int log2_denom, int weightd, int weights, int offset)
Definition at line 1398 of file h264dsp_mmi.c.
ff_deblock_v_chroma_8_mmi()
void ff_deblock_v_chroma_8_mmi (uint8_t * pix, ptrdiff_t stride, int alpha, int beta, int8_t * tc0)
Definition at line 1796 of file h264dsp_mmi.c.
ff_deblock_v_chroma_intra_8_mmi()
void ff_deblock_v_chroma_intra_8_mmi (uint8_t * pix, int stride, int alpha, int beta)
Definition at line 1880 of file h264dsp_mmi.c.
ff_deblock_h_chroma_8_mmi()
void ff_deblock_h_chroma_8_mmi (uint8_t * pix, int stride, int alpha, int beta, int8_t * tc0)
Definition at line 1958 of file h264dsp_mmi.c.
ff_deblock_h_chroma_intra_8_mmi()
void ff_deblock_h_chroma_intra_8_mmi (uint8_t * pix, int stride, int alpha, int beta)
Definition at line 2098 of file h264dsp_mmi.c.
ff_deblock_v_luma_8_mmi()
void ff_deblock_v_luma_8_mmi (uint8_t * pix, int stride, int alpha, int beta, int8_t * tc0)
Definition at line 2231 of file h264dsp_mmi.c.
Referenced by ff_deblock_h_luma_8_mmi().
ff_deblock_v_luma_intra_8_mmi()
void ff_deblock_v_luma_intra_8_mmi (uint8_t * pix, int stride, int alpha, int beta)
Definition at line 2240 of file h264dsp_mmi.c.
Referenced by ff_deblock_h_luma_intra_8_mmi().
ff_deblock_h_luma_8_mmi()
void ff_deblock_h_luma_8_mmi (uint8_t * pix, int stride, int alpha, int beta, int8_t * tc0)
Definition at line 2247 of file h264dsp_mmi.c.
ff_deblock_h_luma_intra_8_mmi()
void ff_deblock_h_luma_intra_8_mmi (uint8_t * pix, int stride, int alpha, int beta)
Definition at line 2466 of file h264dsp_mmi.c.
ff_deblock_v8_luma_8_mmi()
void ff_deblock_v8_luma_8_mmi (uint8_t * pix, int stride, int alpha, int beta, int8_t * tc0)
Definition at line 1442 of file h264dsp_mmi.c.
Referenced by ff_deblock_v_luma_8_mmi().
ff_deblock_v8_luma_intra_8_mmi()
void ff_deblock_v8_luma_intra_8_mmi (uint8_t * pix, int stride, int alpha, int beta)
ff_put_h264_qpel16_mc00_mmi()
void ff_put_h264_qpel16_mc00_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2806 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc10_mmi()
void ff_put_h264_qpel16_mc10_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2812 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc20_mmi()
void ff_put_h264_qpel16_mc20_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2820 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc30_mmi()
void ff_put_h264_qpel16_mc30_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2826 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc01_mmi()
void ff_put_h264_qpel16_mc01_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2834 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc11_mmi()
void ff_put_h264_qpel16_mc11_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2865 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc21_mmi()
void ff_put_h264_qpel16_mc21_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2925 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc31_mmi()
void ff_put_h264_qpel16_mc31_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2878 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc02_mmi()
void ff_put_h264_qpel16_mc02_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2845 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc12_mmi()
void ff_put_h264_qpel16_mc12_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2947 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc22_mmi()
void ff_put_h264_qpel16_mc22_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2917 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc32_mmi()
void ff_put_h264_qpel16_mc32_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2958 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc03_mmi()
void ff_put_h264_qpel16_mc03_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2854 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc13_mmi()
void ff_put_h264_qpel16_mc13_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2891 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc23_mmi()
void ff_put_h264_qpel16_mc23_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2936 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc33_mmi()
void ff_put_h264_qpel16_mc33_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2904 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc00_mmi()
void ff_put_h264_qpel8_mc00_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2478 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc10_mmi()
void ff_put_h264_qpel8_mc10_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2484 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc20_mmi()
void ff_put_h264_qpel8_mc20_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2492 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc30_mmi()
void ff_put_h264_qpel8_mc30_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2498 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc01_mmi()
void ff_put_h264_qpel8_mc01_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2506 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc11_mmi()
void ff_put_h264_qpel8_mc11_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2537 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc21_mmi()
void ff_put_h264_qpel8_mc21_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2597 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc31_mmi()
void ff_put_h264_qpel8_mc31_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2550 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc02_mmi()
void ff_put_h264_qpel8_mc02_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2517 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc12_mmi()
void ff_put_h264_qpel8_mc12_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2619 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc22_mmi()
void ff_put_h264_qpel8_mc22_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2589 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc32_mmi()
void ff_put_h264_qpel8_mc32_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2630 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc03_mmi()
void ff_put_h264_qpel8_mc03_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2526 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc13_mmi()
void ff_put_h264_qpel8_mc13_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2563 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc23_mmi()
void ff_put_h264_qpel8_mc23_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2608 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc33_mmi()
void ff_put_h264_qpel8_mc33_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2576 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc00_mmi()
void ff_put_h264_qpel4_mc00_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2150 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc10_mmi()
void ff_put_h264_qpel4_mc10_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2156 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc20_mmi()
void ff_put_h264_qpel4_mc20_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2164 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc30_mmi()
void ff_put_h264_qpel4_mc30_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2170 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc01_mmi()
void ff_put_h264_qpel4_mc01_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2178 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc11_mmi()
void ff_put_h264_qpel4_mc11_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2209 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc21_mmi()
void ff_put_h264_qpel4_mc21_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2267 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc31_mmi()
void ff_put_h264_qpel4_mc31_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2222 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc02_mmi()
void ff_put_h264_qpel4_mc02_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2189 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc12_mmi()
void ff_put_h264_qpel4_mc12_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2287 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc22_mmi()
void ff_put_h264_qpel4_mc22_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2261 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc32_mmi()
void ff_put_h264_qpel4_mc32_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2300 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc03_mmi()
void ff_put_h264_qpel4_mc03_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2198 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc13_mmi()
void ff_put_h264_qpel4_mc13_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2235 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc23_mmi()
void ff_put_h264_qpel4_mc23_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2277 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc33_mmi()
void ff_put_h264_qpel4_mc33_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2248 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc00_mmi()
void ff_avg_h264_qpel16_mc00_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2970 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc10_mmi()
void ff_avg_h264_qpel16_mc10_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2976 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc20_mmi()
void ff_avg_h264_qpel16_mc20_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2984 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc30_mmi()
void ff_avg_h264_qpel16_mc30_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2990 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc01_mmi()
void ff_avg_h264_qpel16_mc01_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2998 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc11_mmi()
void ff_avg_h264_qpel16_mc11_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3029 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc21_mmi()
void ff_avg_h264_qpel16_mc21_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3089 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc31_mmi()
void ff_avg_h264_qpel16_mc31_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3042 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc02_mmi()
void ff_avg_h264_qpel16_mc02_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3009 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc12_mmi()
void ff_avg_h264_qpel16_mc12_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3111 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc22_mmi()
void ff_avg_h264_qpel16_mc22_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3081 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc32_mmi()
void ff_avg_h264_qpel16_mc32_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3122 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc03_mmi()
void ff_avg_h264_qpel16_mc03_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3018 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc13_mmi()
void ff_avg_h264_qpel16_mc13_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3055 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc23_mmi()
void ff_avg_h264_qpel16_mc23_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3100 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc33_mmi()
void ff_avg_h264_qpel16_mc33_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 3068 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc00_mmi()
void ff_avg_h264_qpel8_mc00_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2642 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc10_mmi()
void ff_avg_h264_qpel8_mc10_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2648 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc20_mmi()
void ff_avg_h264_qpel8_mc20_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2656 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc30_mmi()
void ff_avg_h264_qpel8_mc30_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2662 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc01_mmi()
void ff_avg_h264_qpel8_mc01_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2670 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc11_mmi()
void ff_avg_h264_qpel8_mc11_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2701 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc21_mmi()
void ff_avg_h264_qpel8_mc21_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2761 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc31_mmi()
void ff_avg_h264_qpel8_mc31_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2714 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc02_mmi()
void ff_avg_h264_qpel8_mc02_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2681 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc12_mmi()
void ff_avg_h264_qpel8_mc12_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2783 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc22_mmi()
void ff_avg_h264_qpel8_mc22_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2753 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc32_mmi()
void ff_avg_h264_qpel8_mc32_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2794 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc03_mmi()
void ff_avg_h264_qpel8_mc03_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2690 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc13_mmi()
void ff_avg_h264_qpel8_mc13_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2727 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc23_mmi()
void ff_avg_h264_qpel8_mc23_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2772 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc33_mmi()
void ff_avg_h264_qpel8_mc33_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2740 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc00_mmi()
void ff_avg_h264_qpel4_mc00_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2314 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc10_mmi()
void ff_avg_h264_qpel4_mc10_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2320 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc20_mmi()
void ff_avg_h264_qpel4_mc20_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2328 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc30_mmi()
void ff_avg_h264_qpel4_mc30_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2334 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc01_mmi()
void ff_avg_h264_qpel4_mc01_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2342 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc11_mmi()
void ff_avg_h264_qpel4_mc11_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2373 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc21_mmi()
void ff_avg_h264_qpel4_mc21_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2431 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc31_mmi()
void ff_avg_h264_qpel4_mc31_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2386 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc02_mmi()
void ff_avg_h264_qpel4_mc02_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2353 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc12_mmi()
void ff_avg_h264_qpel4_mc12_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2451 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc22_mmi()
void ff_avg_h264_qpel4_mc22_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2425 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc32_mmi()
void ff_avg_h264_qpel4_mc32_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2464 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc03_mmi()
void ff_avg_h264_qpel4_mc03_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2362 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc13_mmi()
void ff_avg_h264_qpel4_mc13_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2399 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc23_mmi()
void ff_avg_h264_qpel4_mc23_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2441 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc33_mmi()
void ff_avg_h264_qpel4_mc33_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t dst_stride)
Definition at line 2412 of file h264qpel_mmi.c.