FFmpeg: libavcodec/h264chroma.c File Reference
h264chroma.c File Reference
#include "config.h"
#include "libavutil/attributes.h"
#include "h264chroma.h"
#include "h264chroma_template.c"
Macros
#define BIT_DEPTH 8
#define BIT_DEPTH 16
#define SET_CHROMA(depth)
Functions
av_cold void ff_h264chroma_init (H264ChromaContext *c, int bit_depth)
Macro Definition Documentation
BIT_DEPTH [1/2]
#define BIT_DEPTH 8
Definition at line 27 of file h264chroma.c.
BIT_DEPTH [2/2]
#define BIT_DEPTH 16
Definition at line 27 of file h264chroma.c.
SET_CHROMA
#define SET_CHROMA (depth)
Value:
c->put_h264_chroma_pixels_tab[0] = put_h264_chroma_mc8_ ## depth ## _c; \
    c->put_h264_chroma_pixels_tab[1] = put_h264_chroma_mc4_ ## depth ## _c; \
    c->put_h264_chroma_pixels_tab[2] = put_h264_chroma_mc2_ ## depth ## _c; \
    c->put_h264_chroma_pixels_tab[3] = put_h264_chroma_mc1_ ## depth ## _c; \
    c->avg_h264_chroma_pixels_tab[0] = avg_h264_chroma_mc8_ ## depth ## _c; \
    c->avg_h264_chroma_pixels_tab[1] = avg_h264_chroma_mc4_ ## depth ## _c; \
    c->avg_h264_chroma_pixels_tab[2] = avg_h264_chroma_mc2_ ## depth ## _c; \
    c->avg_h264_chroma_pixels_tab[3] = avg_h264_chroma_mc1_ ## depth ## _c; \
Definition at line 31 of file h264chroma.c.
Referenced by ff_h264chroma_init().
Function Documentation
ff_h264chroma_init()
av_cold void ff_h264chroma_init (H264ChromaContext * c, int bit_depth)
Definition at line 41 of file h264chroma.c.
Referenced by dct_init(), ff_cavs_init(), ff_rv30dsp_init(), ff_vp56_init_context(), h264_slice_header_init(), and vc1_decode_init().