FFmpeg: libavcodec/mips/h264pred_msa.c File Reference
h264pred_msa.c File Reference
#include "libavutil/mips/generic_macros_msa.h"
#include "h264dsp_mips.h"
Macros
#define INTRA_PREDICT_VALDC_8X8_MSA(val)
#define INTRA_PREDICT_VALDC_16X16_MSA(val)
Functions
static void intra_predict_vert_8x8_msa (uint8_t *src, uint8_t *dst, int32_t dst_stride)
static void intra_predict_vert_16x16_msa (uint8_t *src, uint8_t *dst, int32_t dst_stride)
static void intra_predict_horiz_8x8_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void intra_predict_horiz_16x16_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void intra_predict_dc_8x8_msa (uint8_t *src_top, uint8_t *src_left, int32_t src_stride_left, uint8_t *dst, int32_t dst_stride, uint8_t is_above, uint8_t is_left)
static void intra_predict_dc_16x16_msa (uint8_t *src_top, uint8_t *src_left, int32_t src_stride_left, uint8_t *dst, int32_t dst_stride, uint8_t is_above, uint8_t is_left)
INTRA_PREDICT_VALDC_8X8_MSA (127)
INTRA_PREDICT_VALDC_8X8_MSA (129)
INTRA_PREDICT_VALDC_16X16_MSA (127)
INTRA_PREDICT_VALDC_16X16_MSA (129)
static void intra_predict_plane_8x8_msa (uint8_t *src, int32_t stride)
static void intra_predict_plane_16x16_msa (uint8_t *src, int32_t stride)
static void intra_predict_dc_4blk_8x8_msa (uint8_t *src, int32_t stride)
static void intra_predict_hor_dc_8x8_msa (uint8_t *src, int32_t stride)
static void intra_predict_vert_dc_8x8_msa (uint8_t *src, int32_t stride)
static void intra_predict_mad_cow_dc_l0t_8x8_msa (uint8_t *src, int32_t stride)
static void intra_predict_mad_cow_dc_0lt_8x8_msa (uint8_t *src, int32_t stride)
static void intra_predict_mad_cow_dc_l00_8x8_msa (uint8_t *src, int32_t stride)
static void intra_predict_mad_cow_dc_0l0_8x8_msa (uint8_t *src, int32_t stride)
void ff_h264_intra_predict_plane_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_predict_dc_4blk_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_predict_hor_dc_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_predict_vert_dc_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_predict_mad_cow_dc_l0t_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_predict_mad_cow_dc_0lt_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_predict_mad_cow_dc_l00_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_predict_mad_cow_dc_0l0_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_predict_plane_16x16_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_pred_vert_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_pred_horiz_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_pred_dc_16x16_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_pred_vert_16x16_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_pred_horiz_16x16_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_pred_dc_left_16x16_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_pred_dc_top_16x16_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_pred_dc_128_8x8_msa (uint8_t *src, ptrdiff_t stride)
void ff_h264_intra_pred_dc_128_16x16_msa (uint8_t *src, ptrdiff_t stride)
void ff_vp8_pred8x8_127_dc_8_msa (uint8_t *src, ptrdiff_t stride)
void ff_vp8_pred8x8_129_dc_8_msa (uint8_t *src, ptrdiff_t stride)
void ff_vp8_pred16x16_127_dc_8_msa (uint8_t *src, ptrdiff_t stride)
void ff_vp8_pred16x16_129_dc_8_msa (uint8_t *src, ptrdiff_t stride)
Macro Definition Documentation
INTRA_PREDICT_VALDC_8X8_MSA
#define INTRA_PREDICT_VALDC_8X8_MSA (val)
Value:
static void intra_predict_##val##dc_8x8_msa(uint8_t *dst,        \
                                            int32_t dst_stride)  \
{                                                                \
    uint32_t row, out;                                           \
    v16i8 store;                                                 \
                                                                 \
    store = __msa_ldi_b(val);                                    \
    out = __msa_copy_u_w((v4i32) store, 0);                      \
                                                                 \
    for (row = 8; row--;) {                                      \
        SW(out, dst);                                            \
        SW(out, (dst + 4));                                      \
        dst += dst_stride;                                       \
    }                                                            \
}
Definition at line 209 of file h264pred_msa.c.
INTRA_PREDICT_VALDC_16X16_MSA
#define INTRA_PREDICT_VALDC_16X16_MSA (val)
Value:
static void intra_predict_##val##dc_16x16_msa(uint8_t *dst,        \
                                              int32_t dst_stride)  \
{                                                                  \
    uint32_t row;                                                  \
    v16u8 store;                                                   \
                                                                   \
    store = (v16u8) __msa_ldi_b(val);                              \
                                                                   \
    for (row = 16; row--;) {                                       \
        ST_UB(store, dst);                                         \
        dst += dst_stride;                                         \
    }                                                              \
}
Definition at line 229 of file h264pred_msa.c.
Function Documentation
intra_predict_vert_8x8_msa()
static void intra_predict_vert_8x8_msa (uint8_t * src, uint8_t * dst, int32_t dst_stride) static
Definition at line 24 of file h264pred_msa.c.
Referenced by ff_h264_intra_pred_vert_8x8_msa().
intra_predict_vert_16x16_msa()
static void intra_predict_vert_16x16_msa (uint8_t * src, uint8_t * dst, int32_t dst_stride) static
Definition at line 40 of file h264pred_msa.c.
Referenced by ff_h264_intra_pred_vert_16x16_msa().
intra_predict_horiz_8x8_msa()
static void intra_predict_horiz_8x8_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 54 of file h264pred_msa.c.
Referenced by ff_h264_intra_pred_horiz_8x8_msa().
intra_predict_horiz_16x16_msa()
static void intra_predict_horiz_16x16_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 73 of file h264pred_msa.c.
Referenced by ff_h264_intra_pred_horiz_16x16_msa().
intra_predict_dc_8x8_msa()
static void intra_predict_dc_8x8_msa (uint8_t * src_top, uint8_t * src_left, int32_t src_stride_left, uint8_t * dst, int32_t dst_stride, uint8_t is_above, uint8_t is_left) static
Definition at line 100 of file h264pred_msa.c.
Referenced by ff_h264_intra_pred_dc_128_8x8_msa().
intra_predict_dc_16x16_msa()
static void intra_predict_dc_16x16_msa (uint8_t * src_top, uint8_t * src_left, int32_t src_stride_left, uint8_t * dst, int32_t dst_stride, uint8_t is_above, uint8_t is_left) static
Definition at line 154 of file h264pred_msa.c.
Referenced by ff_h264_intra_pred_dc_128_16x16_msa(), ff_h264_intra_pred_dc_16x16_msa(), ff_h264_intra_pred_dc_left_16x16_msa(), and ff_h264_intra_pred_dc_top_16x16_msa().
INTRA_PREDICT_VALDC_8X8_MSA() [1/2]
INTRA_PREDICT_VALDC_8X8_MSA (127)
INTRA_PREDICT_VALDC_8X8_MSA() [2/2]
INTRA_PREDICT_VALDC_8X8_MSA (129)
INTRA_PREDICT_VALDC_16X16_MSA() [1/2]
INTRA_PREDICT_VALDC_16X16_MSA (127)
INTRA_PREDICT_VALDC_16X16_MSA() [2/2]
INTRA_PREDICT_VALDC_16X16_MSA (129)
intra_predict_plane_8x8_msa()
static void intra_predict_plane_8x8_msa (uint8_t * src, int32_t stride) static
Definition at line 247 of file h264pred_msa.c.
Referenced by ff_h264_intra_predict_plane_8x8_msa().
intra_predict_plane_16x16_msa()
static void intra_predict_plane_16x16_msa (uint8_t * src, int32_t stride) static
Definition at line 315 of file h264pred_msa.c.
Referenced by ff_h264_intra_predict_plane_16x16_msa().
intra_predict_dc_4blk_8x8_msa()
static void intra_predict_dc_4blk_8x8_msa (uint8_t * src, int32_t stride) static
Definition at line 382 of file h264pred_msa.c.
Referenced by ff_h264_intra_predict_dc_4blk_8x8_msa().
intra_predict_hor_dc_8x8_msa()
static void intra_predict_hor_dc_8x8_msa (uint8_t * src, int32_t stride) static
Definition at line 420 of file h264pred_msa.c.
Referenced by ff_h264_intra_predict_hor_dc_8x8_msa().
intra_predict_vert_dc_8x8_msa()
static void intra_predict_vert_dc_8x8_msa (uint8_t * src, int32_t stride) static
Definition at line 443 of file h264pred_msa.c.
Referenced by ff_h264_intra_predict_vert_dc_8x8_msa().
intra_predict_mad_cow_dc_l0t_8x8_msa()
static void intra_predict_mad_cow_dc_l0t_8x8_msa (uint8_t * src, int32_t stride) static
Definition at line 468 of file h264pred_msa.c.
Referenced by ff_h264_intra_predict_mad_cow_dc_l0t_8x8_msa().
intra_predict_mad_cow_dc_0lt_8x8_msa()
static void intra_predict_mad_cow_dc_0lt_8x8_msa (uint8_t * src, int32_t stride) static
Definition at line 502 of file h264pred_msa.c.
Referenced by ff_h264_intra_predict_mad_cow_dc_0lt_8x8_msa().
intra_predict_mad_cow_dc_l00_8x8_msa()
static void intra_predict_mad_cow_dc_l00_8x8_msa (uint8_t * src, int32_t stride) static
Definition at line 540 of file h264pred_msa.c.
Referenced by ff_h264_intra_predict_mad_cow_dc_l00_8x8_msa().
intra_predict_mad_cow_dc_0l0_8x8_msa()
static void intra_predict_mad_cow_dc_0l0_8x8_msa (uint8_t * src, int32_t stride) static
Definition at line 561 of file h264pred_msa.c.
Referenced by ff_h264_intra_predict_mad_cow_dc_0l0_8x8_msa().
ff_h264_intra_predict_plane_8x8_msa()
void ff_h264_intra_predict_plane_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 583 of file h264pred_msa.c.
ff_h264_intra_predict_dc_4blk_8x8_msa()
void ff_h264_intra_predict_dc_4blk_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 588 of file h264pred_msa.c.
ff_h264_intra_predict_hor_dc_8x8_msa()
void ff_h264_intra_predict_hor_dc_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 593 of file h264pred_msa.c.
ff_h264_intra_predict_vert_dc_8x8_msa()
void ff_h264_intra_predict_vert_dc_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 598 of file h264pred_msa.c.
ff_h264_intra_predict_mad_cow_dc_l0t_8x8_msa()
void ff_h264_intra_predict_mad_cow_dc_l0t_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 603 of file h264pred_msa.c.
ff_h264_intra_predict_mad_cow_dc_0lt_8x8_msa()
void ff_h264_intra_predict_mad_cow_dc_0lt_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 609 of file h264pred_msa.c.
ff_h264_intra_predict_mad_cow_dc_l00_8x8_msa()
void ff_h264_intra_predict_mad_cow_dc_l00_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 615 of file h264pred_msa.c.
ff_h264_intra_predict_mad_cow_dc_0l0_8x8_msa()
void ff_h264_intra_predict_mad_cow_dc_0l0_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 621 of file h264pred_msa.c.
ff_h264_intra_predict_plane_16x16_msa()
void ff_h264_intra_predict_plane_16x16_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 627 of file h264pred_msa.c.
ff_h264_intra_pred_vert_8x8_msa()
void ff_h264_intra_pred_vert_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 632 of file h264pred_msa.c.
ff_h264_intra_pred_horiz_8x8_msa()
void ff_h264_intra_pred_horiz_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 639 of file h264pred_msa.c.
ff_h264_intra_pred_dc_16x16_msa()
void ff_h264_intra_pred_dc_16x16_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 646 of file h264pred_msa.c.
ff_h264_intra_pred_vert_16x16_msa()
void ff_h264_intra_pred_vert_16x16_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 655 of file h264pred_msa.c.
ff_h264_intra_pred_horiz_16x16_msa()
void ff_h264_intra_pred_horiz_16x16_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 662 of file h264pred_msa.c.
ff_h264_intra_pred_dc_left_16x16_msa()
void ff_h264_intra_pred_dc_left_16x16_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 669 of file h264pred_msa.c.
ff_h264_intra_pred_dc_top_16x16_msa()
void ff_h264_intra_pred_dc_top_16x16_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 678 of file h264pred_msa.c.
ff_h264_intra_pred_dc_128_8x8_msa()
void ff_h264_intra_pred_dc_128_8x8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 687 of file h264pred_msa.c.
ff_h264_intra_pred_dc_128_16x16_msa()
void ff_h264_intra_pred_dc_128_16x16_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 696 of file h264pred_msa.c.
ff_vp8_pred8x8_127_dc_8_msa()
void ff_vp8_pred8x8_127_dc_8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 705 of file h264pred_msa.c.
ff_vp8_pred8x8_129_dc_8_msa()
void ff_vp8_pred8x8_129_dc_8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 710 of file h264pred_msa.c.
ff_vp8_pred16x16_127_dc_8_msa()
void ff_vp8_pred16x16_127_dc_8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 715 of file h264pred_msa.c.
ff_vp8_pred16x16_129_dc_8_msa()
void ff_vp8_pred16x16_129_dc_8_msa (uint8_t * src, ptrdiff_t stride)
Definition at line 720 of file h264pred_msa.c.