FFmpeg: libavcodec/h264dsp.h File Reference
h264dsp.h File Reference
H.264 DSP functions.
#include <stdint.h>
#include <stddef.h>
Data Structures
struct H264DSPContext
Context for storing H.264 DSP functions.
Typedefs
typedef void(* h264_weight_func) (uint8_t *block, ptrdiff_t stride, int height, int log2_denom, int weight, int offset)
typedef void(* h264_biweight_func) (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int height, int log2_denom, int weightd, int weights, int offset)
Functions
void ff_h264dsp_init (H264DSPContext *c, const int bit_depth, const int chroma_format_idc)
void ff_h264dsp_init_aarch64 (H264DSPContext *c, const int bit_depth, const int chroma_format_idc)
void ff_h264dsp_init_arm (H264DSPContext *c, const int bit_depth, const int chroma_format_idc)
void ff_h264dsp_init_ppc (H264DSPContext *c, const int bit_depth, const int chroma_format_idc)
void ff_h264dsp_init_x86 (H264DSPContext *c, const int bit_depth, const int chroma_format_idc)
void ff_h264dsp_init_mips (H264DSPContext *c, const int bit_depth, const int chroma_format_idc)
Detailed Description
H.264 DSP functions.
Author
Michael Niedermayer micha.nosp@m.elni.nosp@m.@gmx..nosp@m.at
Definition in file h264dsp.h.
Typedef Documentation
h264_weight_func
typedef void(* h264_weight_func) (uint8_t *block, ptrdiff_t stride, int height, int log2_denom, int weight, int offset)
Definition at line 33 of file h264dsp.h.
h264_biweight_func
typedef void(* h264_biweight_func) (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int height, int log2_denom, int weightd, int weights, int offset)
Definition at line 35 of file h264dsp.h.
Function Documentation
ff_h264dsp_init()
void ff_h264dsp_init (H264DSPContext * c, const int bit_depth, const int chroma_format_idc)
Definition at line 67 of file h264dsp.c.
Referenced by check_idct(), h264_slice_header_init(), init(), and svq3_decode_init().
ff_h264dsp_init_aarch64()
void ff_h264dsp_init_aarch64 (H264DSPContext * c, const int bit_depth, const int chroma_format_idc)
Definition at line 72 of file h264dsp_init_aarch64.c.
Referenced by ff_h264dsp_init().
ff_h264dsp_init_arm()
void ff_h264dsp_init_arm (H264DSPContext * c, const int bit_depth, const int chroma_format_idc)
Definition at line 105 of file h264dsp_init_arm.c.
Referenced by ff_h264dsp_init().
ff_h264dsp_init_ppc()
void ff_h264dsp_init_ppc (H264DSPContext * c, const int bit_depth, const int chroma_format_idc)
Definition at line 790 of file h264dsp.c.
Referenced by ff_h264dsp_init().
ff_h264dsp_init_x86()
void ff_h264dsp_init_x86 (H264DSPContext * c, const int bit_depth, const int chroma_format_idc)
Definition at line 221 of file h264dsp_init.c.
Referenced by ff_h264dsp_init().
ff_h264dsp_init_mips()
void ff_h264dsp_init_mips (H264DSPContext * c, const int bit_depth, const int chroma_format_idc)
Definition at line 138 of file h264dsp_init_mips.c.
Referenced by ff_h264dsp_init().