FFmpeg: libavcodec/h264_parser.c File Reference
h264_parser.c File Reference
H.264 / AVC / MPEG-4 part10 parser.
#include <assert.h>
#include <stdint.h>
#include "libavutil/avutil.h"
#include "libavutil/error.h"
#include "libavutil/log.h"
#include "libavutil/mem.h"
#include "libavutil/pixfmt.h"
#include "avcodec.h"
#include "get_bits.h"
#include "golomb.h"
#include "h264.h"
#include "h264_sei.h"
#include "h264_ps.h"
#include "h264data.h"
#include "internal.h"
#include "mpegutils.h"
#include "parser.h"
Data Structures
struct H264ParseContext
Macros
#define UNCHECKED_BITSTREAM_READER 1
Functions
static int h264_find_frame_end (H264ParseContext *p, const uint8_t *buf, int buf_size, void *logctx)
static int scan_mmco_reset (AVCodecParserContext *s, GetBitContext *gb, void *logctx)
static int parse_nal_units (AVCodecParserContext *s, AVCodecContext *avctx, const uint8_t *const buf, int buf_size)
Parse NAL units of found picture and decode some basic information.
static int h264_parse (AVCodecParserContext *s, AVCodecContext *avctx, const uint8_t **poutbuf, int *poutbuf_size, const uint8_t *buf, int buf_size)
static int h264_split (AVCodecContext *avctx, const uint8_t *buf, int buf_size)
static void h264_close (AVCodecParserContext *s)
static av_cold int init (AVCodecParserContext *s)
Variables
AVCodecParser ff_h264_parser
Detailed Description
H.264 / AVC / MPEG-4 part10 parser.
Author
Michael Niedermayer micha.nosp@m.elni.nosp@m.@gmx..nosp@m.at
Definition in file h264_parser.c.
Macro Definition Documentation
UNCHECKED_BITSTREAM_READER
#define UNCHECKED_BITSTREAM_READER 1
Definition at line 28 of file h264_parser.c.
Function Documentation
h264_find_frame_end()
static int h264_find_frame_end (H264ParseContext * p, const uint8_t * buf, int buf_size, void * logctx) static
Definition at line 68 of file h264_parser.c.
Referenced by h264_parse().
scan_mmco_reset()
static int scan_mmco_reset (AVCodecParserContext * s, GetBitContext * gb, void * logctx) static
Definition at line 155 of file h264_parser.c.
Referenced by parse_nal_units().
parse_nal_units()
static int parse_nal_units (AVCodecParserContext * s, AVCodecContext * avctx, const uint8_t *const buf, int buf_size) inline static
Parse NAL units of found picture and decode some basic information.
Parameters
s parser context.
avctx codec context.
buf buffer with field/frame data.
buf_size size of the buffer.
Definition at line 241 of file h264_parser.c.
Referenced by h264_parse().
h264_parse()
static int h264_parse (AVCodecParserContext * s, AVCodecContext * avctx, const uint8_t ** poutbuf, int * poutbuf_size, const uint8_t * buf, int buf_size) static
Definition at line 562 of file h264_parser.c.
h264_split()
static int h264_split (AVCodecContext * avctx, const uint8_t * buf, int buf_size) static
Definition at line 640 of file h264_parser.c.
h264_close()
static void h264_close (AVCodecParserContext * s) static
Definition at line 677 of file h264_parser.c.
init()
static av_cold int init (AVCodecParserContext * s) static
Definition at line 688 of file h264_parser.c.
Variable Documentation
ff_h264_parser
AVCodecParser ff_h264_parser
Initial value:
= {
    .codec_ids      = { AV_CODEC_ID_H264 },
    .priv_data_size = sizeof(H264ParseContext),
    .parser_init    = init,
    .parser_parse   = h264_parse,
    .parser_close   = h264_close,
    .split          = h264_split,
}
Definition at line 698 of file h264_parser.c.