FFmpeg: libavcodec/mips/h264dsp_mmi.c File Reference
h264dsp_mmi.c File Reference
#include "libavcodec/bit_depth_template.c"
#include "h264dsp_mips.h"
#include "libavutil/mips/mmiutils.h"
Functions
void ff_h264_add_pixels4_8_mmi (uint8_t *dst, int16_t *src, int stride)
void ff_h264_idct_add_8_mmi (uint8_t *dst, int16_t *block, int stride)
void ff_h264_idct8_add_8_mmi (uint8_t *dst, int16_t *block, int stride)
void ff_h264_idct_dc_add_8_mmi (uint8_t *dst, int16_t *block, int stride)
void ff_h264_idct8_dc_add_8_mmi (uint8_t *dst, int16_t *block, int stride)
void ff_h264_idct_add16_8_mmi (uint8_t *dst, const int *block_offset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
void ff_h264_idct_add16intra_8_mmi (uint8_t *dst, const int *block_offset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
void ff_h264_idct8_add4_8_mmi (uint8_t *dst, const int *block_offset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
void ff_h264_idct_add8_8_mmi (uint8_t **dest, const int *block_offset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
void ff_h264_idct_add8_422_8_mmi (uint8_t **dest, const int *block_offset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
void ff_h264_luma_dc_dequant_idct_8_mmi (int16_t *output, int16_t *input, int qmul)
void ff_h264_chroma422_dc_dequant_idct_8_mmi (int16_t *block, int qmul)
void ff_h264_chroma_dc_dequant_idct_8_mmi (int16_t *block, int qmul)
void ff_h264_weight_pixels16_8_mmi (uint8_t *block, ptrdiff_t stride, int height, int log2_denom, int weight, int offset)
void ff_h264_biweight_pixels16_8_mmi (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int height, int log2_denom, int weightd, int weights, int offset)
void ff_h264_weight_pixels8_8_mmi (uint8_t *block, ptrdiff_t stride, int height, int log2_denom, int weight, int offset)
void ff_h264_biweight_pixels8_8_mmi (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int height, int log2_denom, int weightd, int weights, int offset)
void ff_h264_weight_pixels4_8_mmi (uint8_t *block, ptrdiff_t stride, int height, int log2_denom, int weight, int offset)
void ff_h264_biweight_pixels4_8_mmi (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int height, int log2_denom, int weightd, int weights, int offset)
void ff_deblock_v8_luma_8_mmi (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
static void deblock_v8_luma_intra_8_mmi (uint8_t *pix, int stride, int alpha, int beta)
void ff_deblock_v_chroma_8_mmi (uint8_t *pix, ptrdiff_t stride, int alpha, int beta, int8_t *tc0)
void ff_deblock_v_chroma_intra_8_mmi (uint8_t *pix, int stride, int alpha, int beta)
void ff_deblock_h_chroma_8_mmi (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
void ff_deblock_h_chroma_intra_8_mmi (uint8_t *pix, int stride, int alpha, int beta)
void ff_deblock_v_luma_8_mmi (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
void ff_deblock_v_luma_intra_8_mmi (uint8_t *pix, int stride, int alpha, int beta)
void ff_deblock_h_luma_8_mmi (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
void ff_deblock_h_luma_intra_8_mmi (uint8_t *pix, int stride, int alpha, int beta)
Function Documentation
ff_h264_add_pixels4_8_mmi()
void ff_h264_add_pixels4_8_mmi (uint8_t * dst, int16_t * src, int stride)
Definition at line 30 of file h264dsp_mmi.c.
ff_h264_idct_add_8_mmi()
void ff_h264_idct_add_8_mmi (uint8_t * dst, int16_t * block, int stride)
Definition at line 78 of file h264dsp_mmi.c.
Referenced by ff_h264_idct_add16_8_mmi(), ff_h264_idct_add16intra_8_mmi(), ff_h264_idct_add8_422_8_mmi(), and ff_h264_idct_add8_8_mmi().
ff_h264_idct8_add_8_mmi()
void ff_h264_idct8_add_8_mmi (uint8_t * dst, int16_t * block, int stride)
Definition at line 173 of file h264dsp_mmi.c.
Referenced by ff_h264_idct8_add4_8_mmi().
ff_h264_idct_dc_add_8_mmi()
void ff_h264_idct_dc_add_8_mmi (uint8_t * dst, int16_t * block, int stride)
Definition at line 644 of file h264dsp_mmi.c.
Referenced by ff_h264_idct_add16_8_mmi(), ff_h264_idct_add16intra_8_mmi(), ff_h264_idct_add8_422_8_mmi(), and ff_h264_idct_add8_8_mmi().
ff_h264_idct8_dc_add_8_mmi()
void ff_h264_idct8_dc_add_8_mmi (uint8_t * dst, int16_t * block, int stride)
Definition at line 688 of file h264dsp_mmi.c.
Referenced by ff_h264_idct8_add4_8_mmi().
ff_h264_idct_add16_8_mmi()
void ff_h264_idct_add16_8_mmi (uint8_t * dst, const int * block_offset, int16_t * block, int stride, const uint8_t nnzc[15 *8])
Definition at line 773 of file h264dsp_mmi.c.
ff_h264_idct_add16intra_8_mmi()
void ff_h264_idct_add16intra_8_mmi (uint8_t * dst, const int * block_offset, int16_t * block, int stride, const uint8_t nnzc[15 *8])
Definition at line 790 of file h264dsp_mmi.c.
ff_h264_idct8_add4_8_mmi()
void ff_h264_idct8_add4_8_mmi (uint8_t * dst, const int * block_offset, int16_t * block, int stride, const uint8_t nnzc[15 *8])
Definition at line 803 of file h264dsp_mmi.c.
ff_h264_idct_add8_8_mmi()
void ff_h264_idct_add8_8_mmi (uint8_t ** dest, const int * block_offset, int16_t * block, int stride, const uint8_t nnzc[15 *8])
Definition at line 820 of file h264dsp_mmi.c.
ff_h264_idct_add8_422_8_mmi()
void ff_h264_idct_add8_422_8_mmi (uint8_t ** dest, const int * block_offset, int16_t * block, int stride, const uint8_t nnzc[15 *8])
Definition at line 836 of file h264dsp_mmi.c.
ff_h264_luma_dc_dequant_idct_8_mmi()
void ff_h264_luma_dc_dequant_idct_8_mmi (int16_t * output, int16_t * input, int qmul)
Definition at line 864 of file h264dsp_mmi.c.
ff_h264_chroma422_dc_dequant_idct_8_mmi()
void ff_h264_chroma422_dc_dequant_idct_8_mmi (int16_t * block, int qmul)
Definition at line 1091 of file h264dsp_mmi.c.
ff_h264_chroma_dc_dequant_idct_8_mmi()
void ff_h264_chroma_dc_dequant_idct_8_mmi (int16_t * block, int qmul)
Definition at line 1124 of file h264dsp_mmi.c.
ff_h264_weight_pixels16_8_mmi()
void ff_h264_weight_pixels16_8_mmi (uint8_t * block, ptrdiff_t stride, int height, int log2_denom, int weight, int offset)
Definition at line 1138 of file h264dsp_mmi.c.
ff_h264_biweight_pixels16_8_mmi()
void ff_h264_biweight_pixels16_8_mmi (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int height, int log2_denom, int weightd, int weights, int offset)
Definition at line 1194 of file h264dsp_mmi.c.
ff_h264_weight_pixels8_8_mmi()
void ff_h264_weight_pixels8_8_mmi (uint8_t * block, ptrdiff_t stride, int height, int log2_denom, int weight, int offset)
Definition at line 1265 of file h264dsp_mmi.c.
ff_h264_biweight_pixels8_8_mmi()
void ff_h264_biweight_pixels8_8_mmi (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int height, int log2_denom, int weightd, int weights, int offset)
Definition at line 1308 of file h264dsp_mmi.c.
ff_h264_weight_pixels4_8_mmi()
void ff_h264_weight_pixels4_8_mmi (uint8_t * block, ptrdiff_t stride, int height, int log2_denom, int weight, int offset)
Definition at line 1360 of file h264dsp_mmi.c.
ff_h264_biweight_pixels4_8_mmi()
void ff_h264_biweight_pixels4_8_mmi (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int height, int log2_denom, int weightd, int weights, int offset)
Definition at line 1398 of file h264dsp_mmi.c.
ff_deblock_v8_luma_8_mmi()
void ff_deblock_v8_luma_8_mmi (uint8_t * pix, int stride, int alpha, int beta, int8_t * tc0)
Definition at line 1442 of file h264dsp_mmi.c.
Referenced by ff_deblock_v_luma_8_mmi().
deblock_v8_luma_intra_8_mmi()
static void deblock_v8_luma_intra_8_mmi (uint8_t * pix, int stride, int alpha, int beta) static
Definition at line 1570 of file h264dsp_mmi.c.
Referenced by ff_deblock_v_luma_intra_8_mmi().
ff_deblock_v_chroma_8_mmi()
void ff_deblock_v_chroma_8_mmi (uint8_t * pix, ptrdiff_t stride, int alpha, int beta, int8_t * tc0)
Definition at line 1796 of file h264dsp_mmi.c.
ff_deblock_v_chroma_intra_8_mmi()
void ff_deblock_v_chroma_intra_8_mmi (uint8_t * pix, int stride, int alpha, int beta)
Definition at line 1880 of file h264dsp_mmi.c.
ff_deblock_h_chroma_8_mmi()
void ff_deblock_h_chroma_8_mmi (uint8_t * pix, int stride, int alpha, int beta, int8_t * tc0)
Definition at line 1958 of file h264dsp_mmi.c.
ff_deblock_h_chroma_intra_8_mmi()
void ff_deblock_h_chroma_intra_8_mmi (uint8_t * pix, int stride, int alpha, int beta)
Definition at line 2098 of file h264dsp_mmi.c.
ff_deblock_v_luma_8_mmi()
void ff_deblock_v_luma_8_mmi (uint8_t * pix, int stride, int alpha, int beta, int8_t * tc0)
Definition at line 2231 of file h264dsp_mmi.c.
Referenced by ff_deblock_h_luma_8_mmi().
ff_deblock_v_luma_intra_8_mmi()
void ff_deblock_v_luma_intra_8_mmi (uint8_t * pix, int stride, int alpha, int beta)
Definition at line 2240 of file h264dsp_mmi.c.
Referenced by ff_deblock_h_luma_intra_8_mmi().
ff_deblock_h_luma_8_mmi()
void ff_deblock_h_luma_8_mmi (uint8_t * pix, int stride, int alpha, int beta, int8_t * tc0)
Definition at line 2247 of file h264dsp_mmi.c.
ff_deblock_h_luma_intra_8_mmi()
void ff_deblock_h_luma_intra_8_mmi (uint8_t * pix, int stride, int alpha, int beta)
Definition at line 2466 of file h264dsp_mmi.c.