FFmpeg: libavcodec/aarch64/h264chroma_init_aarch64.c File Reference
h264chroma_init_aarch64.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/aarch64/cpu.h"
#include "libavcodec/h264chroma.h"
#include "config.h"
Functions
void ff_put_h264_chroma_mc8_neon (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_put_h264_chroma_mc4_neon (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_put_h264_chroma_mc2_neon (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_avg_h264_chroma_mc8_neon (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_avg_h264_chroma_mc4_neon (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_avg_h264_chroma_mc2_neon (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
av_cold void ff_h264chroma_init_aarch64 (H264ChromaContext *c, int bit_depth)
Function Documentation
ff_put_h264_chroma_mc8_neon()
void ff_put_h264_chroma_mc8_neon (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_h264chroma_init_aarch64().
ff_put_h264_chroma_mc4_neon()
void ff_put_h264_chroma_mc4_neon (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_h264chroma_init_aarch64().
ff_put_h264_chroma_mc2_neon()
void ff_put_h264_chroma_mc2_neon (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_h264chroma_init_aarch64().
ff_avg_h264_chroma_mc8_neon()
void ff_avg_h264_chroma_mc8_neon (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_h264chroma_init_aarch64().
ff_avg_h264_chroma_mc4_neon()
void ff_avg_h264_chroma_mc4_neon (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_h264chroma_init_aarch64().
ff_avg_h264_chroma_mc2_neon()
void ff_avg_h264_chroma_mc2_neon (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_h264chroma_init_aarch64().
ff_h264chroma_init_aarch64()
av_cold void ff_h264chroma_init_aarch64 (H264ChromaContext * c, int bit_depth)
Definition at line 45 of file h264chroma_init_aarch64.c.
Referenced by ff_h264chroma_init().