FFmpeg: libavcodec/mips/h264dsp_msa.c File Reference
h264dsp_msa.c File Reference
#include "libavutil/mips/generic_macros_msa.h"
#include "h264dsp_mips.h"
Macros
#define AVC_LPF_P0P1P2_OR_Q0Q1Q2(p3_or_q3_org_in, p0_or_q0_org_in, q3_or_p3_org_in, p1_or_q1_org_in, p2_or_q2_org_in, q1_or_p1_org_in, p0_or_q0_out, p1_or_q1_out, p2_or_q2_out)
#define AVC_LPF_P0_OR_Q0(p0_or_q0_org_in, q1_or_p1_org_in, p1_or_q1_org_in, p0_or_q0_out)
#define AVC_LPF_P1_OR_Q1(p0_or_q0_org_in, q0_or_p0_org_in, p1_or_q1_org_in, p2_or_q2_org_in, negate_tc_in, tc_in, p1_or_q1_out)
#define AVC_LPF_P0Q0(q0_or_p0_org_in, p0_or_q0_org_in, p1_or_q1_org_in, q1_or_p1_org_in, negate_threshold_in, threshold_in, p0_or_q0_out, q0_or_p0_out)
#define AVC_LPF_H_CHROMA_422(src, stride, tc_val, alpha, beta, res)
#define TRANSPOSE2x4_B_UB(in0, in1, out0, out1, out2, out3)
#define AVC_LPF_H_2BYTE_CHROMA_422(src, stride, tc_val, alpha, beta, res)
Functions
static void avc_wgt_4x2_msa (uint8_t *data, int32_t stride, int32_t log2_denom, int32_t src_weight, int32_t offset_in)
static void avc_wgt_4x4multiple_msa (uint8_t *data, int32_t stride, int32_t height, int32_t log2_denom, int32_t src_weight, int32_t offset_in)
static void avc_wgt_4width_msa (uint8_t *data, int32_t stride, int32_t height, int32_t log2_denom, int32_t src_weight, int32_t offset_in)
static void avc_wgt_8width_msa (uint8_t *data, int32_t stride, int32_t height, int32_t log2_denom, int32_t src_weight, int32_t offset_in)
static void avc_wgt_16width_msa (uint8_t *data, int32_t stride, int32_t height, int32_t log2_denom, int32_t src_weight, int32_t offset_in)
static void avc_biwgt_4x2_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t log2_denom, int32_t src_weight, int32_t dst_weight, int32_t offset_in)
static void avc_biwgt_4x4multiple_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t log2_denom, int32_t src_weight, int32_t dst_weight, int32_t offset_in)
static void avc_biwgt_4width_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t log2_denom, int32_t src_weight, int32_t dst_weight, int32_t offset_in)
static void avc_biwgt_8width_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t log2_denom, int32_t src_weight, int32_t dst_weight, int32_t offset_in)
static void avc_biwgt_16width_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t log2_denom, int32_t src_weight, int32_t dst_weight, int32_t offset_in)
static void avc_loopfilter_luma_intra_edge_hor_msa (uint8_t *data, uint8_t alpha_in, uint8_t beta_in, uint32_t img_width)
static void avc_loopfilter_luma_intra_edge_ver_msa (uint8_t *data, uint8_t alpha_in, uint8_t beta_in, uint32_t img_width)
static void avc_h_loop_filter_luma_mbaff_intra_msa (uint8_t *src, int32_t stride, int32_t alpha_in, int32_t beta_in)
static void avc_loopfilter_cb_or_cr_intra_edge_hor_msa (uint8_t *data_cb_or_cr, uint8_t alpha_in, uint8_t beta_in, uint32_t img_width)
static void avc_loopfilter_cb_or_cr_intra_edge_ver_msa (uint8_t *data_cb_or_cr, uint8_t alpha_in, uint8_t beta_in, uint32_t img_width)
static void avc_loopfilter_luma_inter_edge_ver_msa (uint8_t *data, uint8_t bs0, uint8_t bs1, uint8_t bs2, uint8_t bs3, uint8_t tc0, uint8_t tc1, uint8_t tc2, uint8_t tc3, uint8_t alpha_in, uint8_t beta_in, uint32_t img_width)
static void avc_loopfilter_luma_inter_edge_hor_msa (uint8_t *data, uint8_t bs0, uint8_t bs1, uint8_t bs2, uint8_t bs3, uint8_t tc0, uint8_t tc1, uint8_t tc2, uint8_t tc3, uint8_t alpha_in, uint8_t beta_in, uint32_t image_width)
static void avc_h_loop_filter_luma_mbaff_msa (uint8_t *in, int32_t stride, int32_t alpha_in, int32_t beta_in, int8_t *tc0)
static void avc_loopfilter_cb_or_cr_inter_edge_hor_msa (uint8_t *data, uint8_t bs0, uint8_t bs1, uint8_t bs2, uint8_t bs3, uint8_t tc0, uint8_t tc1, uint8_t tc2, uint8_t tc3, uint8_t alpha_in, uint8_t beta_in, uint32_t img_width)
static void avc_loopfilter_cb_or_cr_inter_edge_ver_msa (uint8_t *data, uint8_t bs0, uint8_t bs1, uint8_t bs2, uint8_t bs3, uint8_t tc0, uint8_t tc1, uint8_t tc2, uint8_t tc3, uint8_t alpha_in, uint8_t beta_in, uint32_t img_width)
static void avc_h_loop_filter_chroma422_msa (uint8_t *src, int32_t stride, int32_t alpha_in, int32_t beta_in, int8_t *tc0)
static void avc_h_loop_filter_chroma422_mbaff_msa (uint8_t *src, int32_t stride, int32_t alpha_in, int32_t beta_in, int8_t *tc0)
void ff_h264_h_lpf_luma_inter_msa (uint8_t *data, int img_width, int alpha, int beta, int8_t *tc)
void ff_h264_v_lpf_luma_inter_msa (uint8_t *data, int img_width, int alpha, int beta, int8_t *tc)
void ff_h264_h_lpf_chroma_inter_msa (uint8_t *data, int img_width, int alpha, int beta, int8_t *tc)
void ff_h264_v_lpf_chroma_inter_msa (uint8_t *data, int img_width, int alpha, int beta, int8_t *tc)
void ff_h264_h_lpf_luma_intra_msa (uint8_t *data, int img_width, int alpha, int beta)
void ff_h264_v_lpf_luma_intra_msa (uint8_t *data, int img_width, int alpha, int beta)
void ff_h264_h_lpf_chroma_intra_msa (uint8_t *data, int img_width, int alpha, int beta)
void ff_h264_v_lpf_chroma_intra_msa (uint8_t *data, int img_width, int alpha, int beta)
void ff_h264_h_loop_filter_chroma422_msa (uint8_t *src, int32_t ystride, int32_t alpha, int32_t beta, int8_t *tc0)
void ff_h264_h_loop_filter_chroma422_mbaff_msa (uint8_t *src, int32_t ystride, int32_t alpha, int32_t beta, int8_t *tc0)
void ff_h264_h_loop_filter_luma_mbaff_msa (uint8_t *src, int32_t ystride, int32_t alpha, int32_t beta, int8_t *tc0)
void ff_h264_h_loop_filter_luma_mbaff_intra_msa (uint8_t *src, int32_t ystride, int32_t alpha, int32_t beta)
void ff_weight_h264_pixels16_8_msa (uint8_t *src, ptrdiff_t stride, int height, int log2_denom, int weight_src, int offset)
void ff_weight_h264_pixels8_8_msa (uint8_t *src, ptrdiff_t stride, int height, int log2_denom, int weight_src, int offset)
void ff_weight_h264_pixels4_8_msa (uint8_t *src, ptrdiff_t stride, int height, int log2_denom, int weight_src, int offset)
void ff_biweight_h264_pixels16_8_msa (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int height, int log2_denom, int weight_dst, int weight_src, int offset)
void ff_biweight_h264_pixels8_8_msa (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int height, int log2_denom, int weight_dst, int weight_src, int offset)
void ff_biweight_h264_pixels4_8_msa (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int height, int log2_denom, int weight_dst, int weight_src, int offset)
Macro Definition Documentation
AVC_LPF_P0P1P2_OR_Q0Q1Q2
#define AVC_LPF_P0P1P2_OR_Q0Q1Q2 (p3_or_q3_org_in, p0_or_q0_org_in, q3_or_p3_org_in, p1_or_q1_org_in, p2_or_q2_org_in, q1_or_p1_org_in, p0_or_q0_out, p1_or_q1_out, p2_or_q2_out)
Value:
{                                                                           \
    v8i16 threshold;                                                        \
    v8i16 const3 = __msa_ldi_h(3);                                          \
                                                                            \
    threshold = (p0_or_q0_org_in) + (q3_or_p3_org_in);                      \
    threshold += (p1_or_q1_org_in);                                         \
                                                                            \
    (p0_or_q0_out) = threshold << 1;                                        \
    (p0_or_q0_out) += (p2_or_q2_org_in);                                    \
    (p0_or_q0_out) += (q1_or_p1_org_in);                                    \
    (p0_or_q0_out) = __msa_srari_h((p0_or_q0_out), 3);                      \
                                                                            \
    (p1_or_q1_out) = (p2_or_q2_org_in) + threshold;                         \
    (p1_or_q1_out) = __msa_srari_h((p1_or_q1_out), 2);                      \
                                                                            \
    (p2_or_q2_out) = (p2_or_q2_org_in) * const3;                            \
    (p2_or_q2_out) += (p3_or_q3_org_in);                                    \
    (p2_or_q2_out) += (p3_or_q3_org_in);                                    \
    (p2_or_q2_out) += threshold;                                            \
    (p2_or_q2_out) = __msa_srari_h((p2_or_q2_out), 3);                      \
}
Definition at line 448 of file h264dsp_msa.c.
Referenced by avc_loopfilter_luma_intra_edge_hor_msa(), and avc_loopfilter_luma_intra_edge_ver_msa().
AVC_LPF_P0_OR_Q0
#define AVC_LPF_P0_OR_Q0 (p0_or_q0_org_in, q1_or_p1_org_in, p1_or_q1_org_in, p0_or_q0_out)
Value:
{                                                            \
    (p0_or_q0_out) = (p0_or_q0_org_in) + (q1_or_p1_org_in);  \
    (p0_or_q0_out) += (p1_or_q1_org_in);                     \
    (p0_or_q0_out) += (p1_or_q1_org_in);                     \
    (p0_or_q0_out) = __msa_srari_h((p0_or_q0_out), 2);       \
}
Definition at line 475 of file h264dsp_msa.c.
Referenced by avc_loopfilter_cb_or_cr_intra_edge_hor_msa(), avc_loopfilter_cb_or_cr_intra_edge_ver_msa(), avc_loopfilter_luma_intra_edge_hor_msa(), and avc_loopfilter_luma_intra_edge_ver_msa().
AVC_LPF_P1_OR_Q1
#define AVC_LPF_P1_OR_Q1 (p0_or_q0_org_in, q0_or_p0_org_in, p1_or_q1_org_in, p2_or_q2_org_in, negate_tc_in, tc_in, p1_or_q1_out)
Value:
{                                                             \
    v8i16 clip3, temp;                                        \
                                                              \
    clip3 = (v8i16) __msa_aver_u_h((v8u16) p0_or_q0_org_in,   \
                                   (v8u16) q0_or_p0_org_in);  \
    temp = p1_or_q1_org_in << 1;                              \
    clip3 = clip3 - temp;                                     \
    clip3 = __msa_ave_s_h(p2_or_q2_org_in, clip3);            \
    clip3 = CLIP_SH(clip3, negate_tc_in, tc_in);              \
    p1_or_q1_out = p1_or_q1_org_in + clip3;                   \
}
Definition at line 484 of file h264dsp_msa.c.
Referenced by avc_loopfilter_luma_inter_edge_hor_msa(), and avc_loopfilter_luma_inter_edge_ver_msa().
AVC_LPF_P0Q0
#define AVC_LPF_P0Q0 (q0_or_p0_org_in, p0_or_q0_org_in, p1_or_q1_org_in, q1_or_p1_org_in, negate_threshold_in, threshold_in, p0_or_q0_out, q0_or_p0_out)
Value:
{                                                               \
    v8i16 q0_sub_p0, p1_sub_q1, delta;                          \
                                                                \
    q0_sub_p0 = q0_or_p0_org_in - p0_or_q0_org_in;              \
    p1_sub_q1 = p1_or_q1_org_in - q1_or_p1_org_in;              \
    q0_sub_p0 <<= 2;                                            \
    p1_sub_q1 += 4;                                             \
    delta = q0_sub_p0 + p1_sub_q1;                              \
    delta >>= 3;                                                \
                                                                \
    delta = CLIP_SH(delta, negate_threshold_in, threshold_in);  \
                                                                \
    p0_or_q0_out = p0_or_q0_org_in + delta;                     \
    q0_or_p0_out = q0_or_p0_org_in - delta;                     \
                                                                \
    CLIP_SH2_0_255(p0_or_q0_out, q0_or_p0_out);                 \
}
Definition at line 499 of file h264dsp_msa.c.
Referenced by avc_loopfilter_cb_or_cr_inter_edge_hor_msa(), avc_loopfilter_cb_or_cr_inter_edge_ver_msa(), avc_loopfilter_luma_inter_edge_hor_msa(), and avc_loopfilter_luma_inter_edge_ver_msa().
AVC_LPF_H_CHROMA_422
#define AVC_LPF_H_CHROMA_422 (src, stride, tc_val, alpha, beta, res)
Definition at line 521 of file h264dsp_msa.c.
Referenced by avc_h_loop_filter_chroma422_msa().
TRANSPOSE2x4_B_UB
#define TRANSPOSE2x4_B_UB (in0, in1, out0, out1, out2, out3)
Value:
{                                                            \
    v16i8 zero_m = { 0 };                                    \
                                                             \
    out0 = (v16u8) __msa_ilvr_b((v16i8) in1, (v16i8) in0);   \
    out1 = (v16u8) __msa_sldi_b(zero_m, (v16i8) out0, 2);    \
    SLDI_B2_0_UB(out1, out2, out2, out3, 2);                 \
}
Definition at line 578 of file h264dsp_msa.c.
AVC_LPF_H_2BYTE_CHROMA_422
#define AVC_LPF_H_2BYTE_CHROMA_422 (src, stride, tc_val, alpha, beta, res)
Definition at line 587 of file h264dsp_msa.c.
Referenced by avc_h_loop_filter_chroma422_mbaff_msa().
Function Documentation
avc_wgt_4x2_msa()
static void avc_wgt_4x2_msa (uint8_t * data, int32_t stride, int32_t log2_denom, int32_t src_weight, int32_t offset_in) static
Definition at line 24 of file h264dsp_msa.c.
Referenced by avc_wgt_4width_msa().
avc_wgt_4x4multiple_msa()
static void avc_wgt_4x4multiple_msa (uint8_t * data, int32_t stride, int32_t height, int32_t log2_denom, int32_t src_weight, int32_t offset_in) static
Definition at line 69 of file h264dsp_msa.c.
Referenced by avc_wgt_4width_msa().
avc_wgt_4width_msa()
static void avc_wgt_4width_msa (uint8_t * data, int32_t stride, int32_t height, int32_t log2_denom, int32_t src_weight, int32_t offset_in) static
Definition at line 112 of file h264dsp_msa.c.
Referenced by ff_weight_h264_pixels4_8_msa().
avc_wgt_8width_msa()
static void avc_wgt_8width_msa (uint8_t * data, int32_t stride, int32_t height, int32_t log2_denom, int32_t src_weight, int32_t offset_in) static
Definition at line 124 of file h264dsp_msa.c.
Referenced by ff_weight_h264_pixels8_8_msa().
avc_wgt_16width_msa()
static void avc_wgt_16width_msa (uint8_t * data, int32_t stride, int32_t height, int32_t log2_denom, int32_t src_weight, int32_t offset_in) static
Definition at line 163 of file h264dsp_msa.c.
Referenced by ff_weight_h264_pixels16_8_msa().
avc_biwgt_4x2_msa()
static void avc_biwgt_4x2_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t log2_denom, int32_t src_weight, int32_t dst_weight, int32_t offset_in) static
Definition at line 212 of file h264dsp_msa.c.
Referenced by avc_biwgt_4width_msa().
avc_biwgt_4x4multiple_msa()
static void avc_biwgt_4x4multiple_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t log2_denom, int32_t src_weight, int32_t dst_weight, int32_t offset_in) static
Definition at line 266 of file h264dsp_msa.c.
Referenced by avc_biwgt_4width_msa().
avc_biwgt_4width_msa()
static void avc_biwgt_4width_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t log2_denom, int32_t src_weight, int32_t dst_weight, int32_t offset_in) static
Definition at line 325 of file h264dsp_msa.c.
Referenced by ff_biweight_h264_pixels4_8_msa().
avc_biwgt_8width_msa()
static void avc_biwgt_8width_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t log2_denom, int32_t src_weight, int32_t dst_weight, int32_t offset_in) static
Definition at line 341 of file h264dsp_msa.c.
Referenced by ff_biweight_h264_pixels8_8_msa().
avc_biwgt_16width_msa()
static void avc_biwgt_16width_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t log2_denom, int32_t src_weight, int32_t dst_weight, int32_t offset_in) static
Definition at line 390 of file h264dsp_msa.c.
Referenced by ff_biweight_h264_pixels16_8_msa().
avc_loopfilter_luma_intra_edge_hor_msa()
static void avc_loopfilter_luma_intra_edge_hor_msa (uint8_t * data, uint8_t alpha_in, uint8_t beta_in, uint32_t img_width) static
Definition at line 642 of file h264dsp_msa.c.
Referenced by ff_h264_v_lpf_luma_intra_msa().
avc_loopfilter_luma_intra_edge_ver_msa()
static void avc_loopfilter_luma_intra_edge_ver_msa (uint8_t * data, uint8_t alpha_in, uint8_t beta_in, uint32_t img_width) static
Definition at line 833 of file h264dsp_msa.c.
Referenced by ff_h264_h_lpf_luma_intra_msa().
avc_h_loop_filter_luma_mbaff_intra_msa()
static void avc_h_loop_filter_luma_mbaff_intra_msa (uint8_t * src, int32_t stride, int32_t alpha_in, int32_t beta_in) static
Definition at line 1087 of file h264dsp_msa.c.
Referenced by ff_h264_h_loop_filter_luma_mbaff_intra_msa().
avc_loopfilter_cb_or_cr_intra_edge_hor_msa()
static void avc_loopfilter_cb_or_cr_intra_edge_hor_msa (uint8_t * data_cb_or_cr, uint8_t alpha_in, uint8_t beta_in, uint32_t img_width) static
Definition at line 1285 of file h264dsp_msa.c.
Referenced by ff_h264_v_lpf_chroma_intra_msa().
avc_loopfilter_cb_or_cr_intra_edge_ver_msa()
static void avc_loopfilter_cb_or_cr_intra_edge_ver_msa (uint8_t * data_cb_or_cr, uint8_t alpha_in, uint8_t beta_in, uint32_t img_width) static
Definition at line 1334 of file h264dsp_msa.c.
Referenced by ff_h264_h_lpf_chroma_intra_msa().
avc_loopfilter_luma_inter_edge_ver_msa()
static void avc_loopfilter_luma_inter_edge_ver_msa (uint8_t * data, uint8_t bs0, uint8_t bs1, uint8_t bs2, uint8_t bs3, uint8_t tc0, uint8_t tc1, uint8_t tc2, uint8_t tc3, uint8_t alpha_in, uint8_t beta_in, uint32_t img_width) static
Definition at line 1396 of file h264dsp_msa.c.
Referenced by ff_h264_h_lpf_luma_inter_msa().
avc_loopfilter_luma_inter_edge_hor_msa()
static void avc_loopfilter_luma_inter_edge_hor_msa (uint8_t * data, uint8_t bs0, uint8_t bs1, uint8_t bs2, uint8_t bs3, uint8_t tc0, uint8_t tc1, uint8_t tc2, uint8_t tc3, uint8_t alpha_in, uint8_t beta_in, uint32_t image_width) static
Definition at line 1706 of file h264dsp_msa.c.
Referenced by ff_h264_v_lpf_luma_inter_msa().
avc_h_loop_filter_luma_mbaff_msa()
static void avc_h_loop_filter_luma_mbaff_msa (uint8_t * in, int32_t stride, int32_t alpha_in, int32_t beta_in, int8_t * tc0) static
Definition at line 1886 of file h264dsp_msa.c.
Referenced by ff_h264_h_loop_filter_luma_mbaff_msa().
avc_loopfilter_cb_or_cr_inter_edge_hor_msa()
static void avc_loopfilter_cb_or_cr_inter_edge_hor_msa (uint8_t * data, uint8_t bs0, uint8_t bs1, uint8_t bs2, uint8_t bs3, uint8_t tc0, uint8_t tc1, uint8_t tc2, uint8_t tc3, uint8_t alpha_in, uint8_t beta_in, uint32_t img_width) static
Definition at line 2106 of file h264dsp_msa.c.
Referenced by ff_h264_v_lpf_chroma_inter_msa().
avc_loopfilter_cb_or_cr_inter_edge_ver_msa()
static void avc_loopfilter_cb_or_cr_inter_edge_ver_msa (uint8_t * data, uint8_t bs0, uint8_t bs1, uint8_t bs2, uint8_t bs3, uint8_t tc0, uint8_t tc1, uint8_t tc2, uint8_t tc3, uint8_t alpha_in, uint8_t beta_in, uint32_t img_width) static
Definition at line 2192 of file h264dsp_msa.c.
Referenced by ff_h264_h_lpf_chroma_inter_msa().
avc_h_loop_filter_chroma422_msa()
static void avc_h_loop_filter_chroma422_msa (uint8_t * src, int32_t stride, int32_t alpha_in, int32_t beta_in, int8_t * tc0) static
Definition at line 2287 of file h264dsp_msa.c.
Referenced by ff_h264_h_loop_filter_chroma422_msa().
avc_h_loop_filter_chroma422_mbaff_msa()
static void avc_h_loop_filter_chroma422_mbaff_msa (uint8_t * src, int32_t stride, int32_t alpha_in, int32_t beta_in, int8_t * tc0) static
Definition at line 2311 of file h264dsp_msa.c.
Referenced by ff_h264_h_loop_filter_chroma422_mbaff_msa().
ff_h264_h_lpf_luma_inter_msa()
void ff_h264_h_lpf_luma_inter_msa (uint8_t * data, int img_width, int alpha, int beta, int8_t * tc)
Definition at line 2343 of file h264dsp_msa.c.
ff_h264_v_lpf_luma_inter_msa()
void ff_h264_v_lpf_luma_inter_msa (uint8_t * data, int img_width, int alpha, int beta, int8_t * tc)
Definition at line 2365 of file h264dsp_msa.c.
ff_h264_h_lpf_chroma_inter_msa()
void ff_h264_h_lpf_chroma_inter_msa (uint8_t * data, int img_width, int alpha, int beta, int8_t * tc)
Definition at line 2388 of file h264dsp_msa.c.
ff_h264_v_lpf_chroma_inter_msa()
void ff_h264_v_lpf_chroma_inter_msa (uint8_t * data, int img_width, int alpha, int beta, int8_t * tc)
Definition at line 2410 of file h264dsp_msa.c.
ff_h264_h_lpf_luma_intra_msa()
void ff_h264_h_lpf_luma_intra_msa (uint8_t * data, int img_width, int alpha, int beta)
Definition at line 2432 of file h264dsp_msa.c.
ff_h264_v_lpf_luma_intra_msa()
void ff_h264_v_lpf_luma_intra_msa (uint8_t * data, int img_width, int alpha, int beta)
Definition at line 2440 of file h264dsp_msa.c.
ff_h264_h_lpf_chroma_intra_msa()
void ff_h264_h_lpf_chroma_intra_msa (uint8_t * data, int img_width, int alpha, int beta)
Definition at line 2448 of file h264dsp_msa.c.
ff_h264_v_lpf_chroma_intra_msa()
void ff_h264_v_lpf_chroma_intra_msa (uint8_t * data, int img_width, int alpha, int beta)
Definition at line 2456 of file h264dsp_msa.c.
ff_h264_h_loop_filter_chroma422_msa()
void ff_h264_h_loop_filter_chroma422_msa (uint8_t * src, int32_t ystride, int32_t alpha, int32_t beta, int8_t * tc0)
Definition at line 2464 of file h264dsp_msa.c.
ff_h264_h_loop_filter_chroma422_mbaff_msa()
void ff_h264_h_loop_filter_chroma422_mbaff_msa (uint8_t * src, int32_t ystride, int32_t alpha, int32_t beta, int8_t * tc0)
Definition at line 2472 of file h264dsp_msa.c.
ff_h264_h_loop_filter_luma_mbaff_msa()
void ff_h264_h_loop_filter_luma_mbaff_msa (uint8_t * src, int32_t ystride, int32_t alpha, int32_t beta, int8_t * tc0)
Definition at line 2481 of file h264dsp_msa.c.
ff_h264_h_loop_filter_luma_mbaff_intra_msa()
void ff_h264_h_loop_filter_luma_mbaff_intra_msa (uint8_t * src, int32_t ystride, int32_t alpha, int32_t beta)
Definition at line 2490 of file h264dsp_msa.c.
ff_weight_h264_pixels16_8_msa()
void ff_weight_h264_pixels16_8_msa (uint8_t * src, ptrdiff_t stride, int height, int log2_denom, int weight_src, int offset)
Definition at line 2498 of file h264dsp_msa.c.
ff_weight_h264_pixels8_8_msa()
void ff_weight_h264_pixels8_8_msa (uint8_t * src, ptrdiff_t stride, int height, int log2_denom, int weight_src, int offset)
Definition at line 2505 of file h264dsp_msa.c.
ff_weight_h264_pixels4_8_msa()
void ff_weight_h264_pixels4_8_msa (uint8_t * src, ptrdiff_t stride, int height, int log2_denom, int weight_src, int offset)
Definition at line 2512 of file h264dsp_msa.c.
ff_biweight_h264_pixels16_8_msa()
void ff_biweight_h264_pixels16_8_msa (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int height, int log2_denom, int weight_dst, int weight_src, int offset)
Definition at line 2519 of file h264dsp_msa.c.
ff_biweight_h264_pixels8_8_msa()
void ff_biweight_h264_pixels8_8_msa (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int height, int log2_denom, int weight_dst, int weight_src, int offset)
Definition at line 2528 of file h264dsp_msa.c.
ff_biweight_h264_pixels4_8_msa()
void ff_biweight_h264_pixels4_8_msa (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int height, int log2_denom, int weight_dst, int weight_src, int offset)
Definition at line 2537 of file h264dsp_msa.c.