FFmpeg: libavcodec/mips/h264pred_mmi.c File Reference
h264pred_mmi.c File Reference
#include "h264pred_mips.h"
#include "libavcodec/bit_depth_template.c"
#include "libavutil/mips/mmiutils.h"
#include "constants.h"
Functions
void ff_pred16x16_vertical_8_mmi (uint8_t *src, ptrdiff_t stride)
void ff_pred16x16_horizontal_8_mmi (uint8_t *src, ptrdiff_t stride)
void ff_pred16x16_dc_8_mmi (uint8_t *src, ptrdiff_t stride)
void ff_pred8x8l_top_dc_8_mmi (uint8_t *src, int has_topleft, int has_topright, ptrdiff_t stride)
void ff_pred8x8l_dc_8_mmi (uint8_t *src, int has_topleft, int has_topright, ptrdiff_t stride)
void ff_pred8x8l_vertical_8_mmi (uint8_t *src, int has_topleft, int has_topright, ptrdiff_t stride)
void ff_pred4x4_dc_8_mmi (uint8_t *src, const uint8_t *topright, ptrdiff_t stride)
void ff_pred8x8_vertical_8_mmi (uint8_t *src, ptrdiff_t stride)
void ff_pred8x8_horizontal_8_mmi (uint8_t *src, ptrdiff_t stride)
void ff_pred8x8_top_dc_8_mmi (uint8_t *src, ptrdiff_t stride)
void ff_pred8x8_dc_8_mmi (uint8_t *src, ptrdiff_t stride)
void ff_pred8x16_vertical_8_mmi (uint8_t *src, ptrdiff_t stride)
void ff_pred8x16_horizontal_8_mmi (uint8_t *src, ptrdiff_t stride)
static void pred16x16_plane_compat_mmi (uint8_t *src, int stride, const int svq3, const int rv40)
void ff_pred16x16_plane_h264_8_mmi (uint8_t *src, ptrdiff_t stride)
void ff_pred16x16_plane_svq3_8_mmi (uint8_t *src, ptrdiff_t stride)
void ff_pred16x16_plane_rv40_8_mmi (uint8_t *src, ptrdiff_t stride)
Function Documentation
ff_pred16x16_vertical_8_mmi()
void ff_pred16x16_vertical_8_mmi (uint8_t * src, ptrdiff_t stride)
Definition at line 30 of file h264pred_mmi.c.
ff_pred16x16_horizontal_8_mmi()
void ff_pred16x16_horizontal_8_mmi (uint8_t * src, ptrdiff_t stride)
Definition at line 60 of file h264pred_mmi.c.
ff_pred16x16_dc_8_mmi()
void ff_pred16x16_dc_8_mmi (uint8_t * src, ptrdiff_t stride)
Definition at line 97 of file h264pred_mmi.c.
ff_pred8x8l_top_dc_8_mmi()
void ff_pred8x8l_top_dc_8_mmi (uint8_t * src, int has_topleft, int has_topright, ptrdiff_t stride)
Definition at line 155 of file h264pred_mmi.c.
ff_pred8x8l_dc_8_mmi()
void ff_pred8x8l_dc_8_mmi (uint8_t * src, int has_topleft, int has_topright, ptrdiff_t stride)
Definition at line 244 of file h264pred_mmi.c.
ff_pred8x8l_vertical_8_mmi()
void ff_pred8x8l_vertical_8_mmi (uint8_t * src, int has_topleft, int has_topright, ptrdiff_t stride)
Definition at line 350 of file h264pred_mmi.c.
ff_pred4x4_dc_8_mmi()
void ff_pred4x4_dc_8_mmi (uint8_t * src, const uint8_t * topright, ptrdiff_t stride)
Definition at line 430 of file h264pred_mmi.c.
ff_pred8x8_vertical_8_mmi()
void ff_pred8x8_vertical_8_mmi (uint8_t * src, ptrdiff_t stride)
Definition at line 460 of file h264pred_mmi.c.
ff_pred8x8_horizontal_8_mmi()
void ff_pred8x8_horizontal_8_mmi (uint8_t * src, ptrdiff_t stride)
Definition at line 487 of file h264pred_mmi.c.
ff_pred8x8_top_dc_8_mmi()
void ff_pred8x8_top_dc_8_mmi (uint8_t * src, ptrdiff_t stride)
Definition at line 520 of file h264pred_mmi.c.
ff_pred8x8_dc_8_mmi()
void ff_pred8x8_dc_8_mmi (uint8_t * src, ptrdiff_t stride)
Definition at line 572 of file h264pred_mmi.c.
ff_pred8x16_vertical_8_mmi()
void ff_pred8x16_vertical_8_mmi (uint8_t * src, ptrdiff_t stride)
Definition at line 678 of file h264pred_mmi.c.
ff_pred8x16_horizontal_8_mmi()
void ff_pred8x16_horizontal_8_mmi (uint8_t * src, ptrdiff_t stride)
Definition at line 709 of file h264pred_mmi.c.
pred16x16_plane_compat_mmi()
static void pred16x16_plane_compat_mmi (uint8_t * src, int stride, const int svq3, const int rv40) inline static
Definition at line 742 of file h264pred_mmi.c.
Referenced by ff_pred16x16_plane_h264_8_mmi(), ff_pred16x16_plane_rv40_8_mmi(), and ff_pred16x16_plane_svq3_8_mmi().
ff_pred16x16_plane_h264_8_mmi()
void ff_pred16x16_plane_h264_8_mmi (uint8_t * src, ptrdiff_t stride)
Definition at line 972 of file h264pred_mmi.c.
ff_pred16x16_plane_svq3_8_mmi()
void ff_pred16x16_plane_svq3_8_mmi (uint8_t * src, ptrdiff_t stride)
Definition at line 977 of file h264pred_mmi.c.
ff_pred16x16_plane_rv40_8_mmi()
void ff_pred16x16_plane_rv40_8_mmi (uint8_t * src, ptrdiff_t stride)
Definition at line 982 of file h264pred_mmi.c.