FFmpeg: libavcodec/mips/h264chroma_msa.c File Reference
h264chroma_msa.c File Reference
#include "libavutil/mips/generic_macros_msa.h"
#include "h264chroma_mips.h"
Functions
static void avc_chroma_hz_2x2_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1)
static void avc_chroma_hz_2x4_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1)
static void avc_chroma_hz_2x8_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1)
static void avc_chroma_hz_2w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height)
static void avc_chroma_hz_4x2_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1)
static void avc_chroma_hz_4x4multiple_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height)
static void avc_chroma_hz_4w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height)
static void avc_chroma_hz_8w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height)
static void avc_chroma_vt_2x2_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1)
static void avc_chroma_vt_2x4_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1)
static void avc_chroma_vt_2x8_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1)
static void avc_chroma_vt_2w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height)
static void avc_chroma_vt_4x2_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1)
static void avc_chroma_vt_4x4multiple_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height)
static void avc_chroma_vt_4w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height)
static void avc_chroma_vt_8w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height)
static void avc_chroma_hv_2x2_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1)
static void avc_chroma_hv_2x4_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1)
static void avc_chroma_hv_2x8_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1)
static void avc_chroma_hv_2w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1, int32_t height)
static void avc_chroma_hv_4x2_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1)
static void avc_chroma_hv_4x4multiple_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1, int32_t height)
static void avc_chroma_hv_4w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1, int32_t height)
static void avc_chroma_hv_8w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1, int32_t height)
static void avc_chroma_hz_and_aver_dst_2x2_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1)
static void avc_chroma_hz_and_aver_dst_2x4_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1)
static void avc_chroma_hz_and_aver_dst_2x8_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1)
static void avc_chroma_hz_and_aver_dst_2w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height)
static void avc_chroma_hz_and_aver_dst_4x2_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1)
static void avc_chroma_hz_and_aver_dst_4x4multiple_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height)
static void avc_chroma_hz_and_aver_dst_4w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height)
static void avc_chroma_hz_and_aver_dst_8w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height)
static void avc_chroma_vt_and_aver_dst_2x2_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1)
static void avc_chroma_vt_and_aver_dst_2x4_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1)
static void avc_chroma_vt_and_aver_dst_2x8_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1)
static void avc_chroma_vt_and_aver_dst_2w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height)
static void avc_chroma_vt_and_aver_dst_4x2_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1)
static void avc_chroma_vt_and_aver_dst_4x4mul_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height)
static void avc_chroma_vt_and_aver_dst_4w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height)
static void avc_chroma_vt_and_aver_dst_8w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height)
static void avc_chroma_hv_and_aver_dst_2x2_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1)
static void avc_chroma_hv_and_aver_dst_2x4_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1)
static void avc_chroma_hv_and_aver_dst_2x8_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1)
static void avc_chroma_hv_and_aver_dst_2w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1, int32_t height)
static void avc_chroma_hv_and_aver_dst_4x2_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1)
static void avc_chroma_hv_and_aver_dst_4x4mul_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1, int32_t height)
static void avc_chroma_hv_and_aver_dst_4w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1, int32_t height)
static void avc_chroma_hv_and_aver_dst_8w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1, int32_t height)
static void copy_width8_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avg_width4_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avg_width8_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
void ff_put_h264_chroma_mc8_msa (uint8_t *dst, uint8_t *src, int stride, int height, int x, int y)
void ff_put_h264_chroma_mc4_msa (uint8_t *dst, uint8_t *src, int stride, int height, int x, int y)
void ff_put_h264_chroma_mc2_msa (uint8_t *dst, uint8_t *src, int stride, int height, int x, int y)
void ff_avg_h264_chroma_mc8_msa (uint8_t *dst, uint8_t *src, int stride, int height, int x, int y)
void ff_avg_h264_chroma_mc4_msa (uint8_t *dst, uint8_t *src, int stride, int height, int x, int y)
void ff_avg_h264_chroma_mc2_msa (uint8_t *dst, uint8_t *src, int stride, int height, int x, int y)
Variables
static const uint8_t chroma_mask_arr [16 *5]
Function Documentation
avc_chroma_hz_2x2_msa()
static void avc_chroma_hz_2x2_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1) static
Definition at line 32 of file h264chroma_msa.c.
Referenced by avc_chroma_hz_2w_msa().
avc_chroma_hz_2x4_msa()
static void avc_chroma_hz_2x4_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1) static
Definition at line 64 of file h264chroma_msa.c.
Referenced by avc_chroma_hz_2w_msa().
avc_chroma_hz_2x8_msa()
static void avc_chroma_hz_2x8_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1) static
Definition at line 93 of file h264chroma_msa.c.
Referenced by avc_chroma_hz_2w_msa().
avc_chroma_hz_2w_msa()
static void avc_chroma_hz_2w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height) static
Definition at line 132 of file h264chroma_msa.c.
Referenced by ff_put_h264_chroma_mc2_msa().
avc_chroma_hz_4x2_msa()
static void avc_chroma_hz_4x2_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1) static
Definition at line 146 of file h264chroma_msa.c.
Referenced by avc_chroma_hz_4w_msa().
avc_chroma_hz_4x4multiple_msa()
static void avc_chroma_hz_4x4multiple_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height) static
Definition at line 172 of file h264chroma_msa.c.
Referenced by avc_chroma_hz_4w_msa().
avc_chroma_hz_4w_msa()
static void avc_chroma_hz_4w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height) static
Definition at line 207 of file h264chroma_msa.c.
Referenced by ff_put_h264_chroma_mc4_msa().
avc_chroma_hz_8w_msa()
static void avc_chroma_hz_8w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height) static
Definition at line 220 of file h264chroma_msa.c.
Referenced by ff_put_h264_chroma_mc8_msa().
avc_chroma_vt_2x2_msa()
static void avc_chroma_vt_2x2_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1) static
Definition at line 270 of file h264chroma_msa.c.
Referenced by avc_chroma_vt_2w_msa().
avc_chroma_vt_2x4_msa()
static void avc_chroma_vt_2x4_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1) static
Definition at line 303 of file h264chroma_msa.c.
Referenced by avc_chroma_vt_2w_msa().
avc_chroma_vt_2x8_msa()
static void avc_chroma_vt_2x8_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1) static
Definition at line 332 of file h264chroma_msa.c.
Referenced by avc_chroma_vt_2w_msa().
avc_chroma_vt_2w_msa()
static void avc_chroma_vt_2w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height) static
Definition at line 381 of file h264chroma_msa.c.
Referenced by ff_put_h264_chroma_mc2_msa().
avc_chroma_vt_4x2_msa()
static void avc_chroma_vt_4x2_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1) static
Definition at line 395 of file h264chroma_msa.c.
Referenced by avc_chroma_vt_4w_msa().
avc_chroma_vt_4x4multiple_msa()
static void avc_chroma_vt_4x4multiple_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height) static
Definition at line 420 of file h264chroma_msa.c.
Referenced by avc_chroma_vt_4w_msa().
avc_chroma_vt_4w_msa()
static void avc_chroma_vt_4w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height) static
Definition at line 459 of file h264chroma_msa.c.
Referenced by ff_put_h264_chroma_mc4_msa().
avc_chroma_vt_8w_msa()
static void avc_chroma_vt_8w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height) static
Definition at line 472 of file h264chroma_msa.c.
Referenced by ff_put_h264_chroma_mc8_msa().
avc_chroma_hv_2x2_msa()
static void avc_chroma_hv_2x2_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1) static
Definition at line 507 of file h264chroma_msa.c.
Referenced by avc_chroma_hv_2w_msa().
avc_chroma_hv_2x4_msa()
static void avc_chroma_hv_2x4_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1) static
Definition at line 543 of file h264chroma_msa.c.
Referenced by avc_chroma_hv_2w_msa().
avc_chroma_hv_2x8_msa()
static void avc_chroma_hv_2x8_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1) static
Definition at line 577 of file h264chroma_msa.c.
Referenced by avc_chroma_hv_2w_msa().
avc_chroma_hv_2w_msa()
static void avc_chroma_hv_2w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1, int32_t height) static
Definition at line 629 of file h264chroma_msa.c.
Referenced by ff_put_h264_chroma_mc2_msa().
avc_chroma_hv_4x2_msa()
static void avc_chroma_hv_4x2_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1) static
Definition at line 647 of file h264chroma_msa.c.
Referenced by avc_chroma_hv_4w_msa().
avc_chroma_hv_4x4multiple_msa()
static void avc_chroma_hv_4x4multiple_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1, int32_t height) static
Definition at line 676 of file h264chroma_msa.c.
Referenced by avc_chroma_hv_4w_msa().
avc_chroma_hv_4w_msa()
static void avc_chroma_hv_4w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1, int32_t height) static
Definition at line 724 of file h264chroma_msa.c.
Referenced by ff_put_h264_chroma_mc4_msa().
avc_chroma_hv_8w_msa()
static void avc_chroma_hv_8w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1, int32_t height) static
Definition at line 740 of file h264chroma_msa.c.
Referenced by ff_put_h264_chroma_mc8_msa().
avc_chroma_hz_and_aver_dst_2x2_msa()
static void avc_chroma_hz_and_aver_dst_2x2_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1) static
Definition at line 794 of file h264chroma_msa.c.
Referenced by avc_chroma_hz_and_aver_dst_2w_msa().
avc_chroma_hz_and_aver_dst_2x4_msa()
static void avc_chroma_hz_and_aver_dst_2x4_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1) static
Definition at line 836 of file h264chroma_msa.c.
Referenced by avc_chroma_hz_and_aver_dst_2w_msa().
avc_chroma_hz_and_aver_dst_2x8_msa()
static void avc_chroma_hz_and_aver_dst_2x8_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1) static
Definition at line 872 of file h264chroma_msa.c.
Referenced by avc_chroma_hz_and_aver_dst_2w_msa().
avc_chroma_hz_and_aver_dst_2w_msa()
static void avc_chroma_hz_and_aver_dst_2w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height) static
Definition at line 915 of file h264chroma_msa.c.
Referenced by ff_avg_h264_chroma_mc2_msa().
avc_chroma_hz_and_aver_dst_4x2_msa()
static void avc_chroma_hz_and_aver_dst_4x2_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1) static
Definition at line 932 of file h264chroma_msa.c.
Referenced by avc_chroma_hz_and_aver_dst_4w_msa().
avc_chroma_hz_and_aver_dst_4x4multiple_msa()
static void avc_chroma_hz_and_aver_dst_4x4multiple_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height) static
Definition at line 966 of file h264chroma_msa.c.
Referenced by avc_chroma_hz_and_aver_dst_4w_msa().
avc_chroma_hz_and_aver_dst_4w_msa()
static void avc_chroma_hz_and_aver_dst_4w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height) static
Definition at line 1017 of file h264chroma_msa.c.
Referenced by ff_avg_h264_chroma_mc4_msa().
avc_chroma_hz_and_aver_dst_8w_msa()
static void avc_chroma_hz_and_aver_dst_8w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height) static
Definition at line 1032 of file h264chroma_msa.c.
Referenced by ff_avg_h264_chroma_mc8_msa().
avc_chroma_vt_and_aver_dst_2x2_msa()
static void avc_chroma_vt_and_aver_dst_2x2_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1) static
Definition at line 1067 of file h264chroma_msa.c.
Referenced by avc_chroma_vt_and_aver_dst_2w_msa().
avc_chroma_vt_and_aver_dst_2x4_msa()
static void avc_chroma_vt_and_aver_dst_2x4_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1) static
Definition at line 1103 of file h264chroma_msa.c.
Referenced by avc_chroma_vt_and_aver_dst_2w_msa().
avc_chroma_vt_and_aver_dst_2x8_msa()
static void avc_chroma_vt_and_aver_dst_2x8_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1) static
Definition at line 1149 of file h264chroma_msa.c.
Referenced by avc_chroma_vt_and_aver_dst_2w_msa().
avc_chroma_vt_and_aver_dst_2w_msa()
static void avc_chroma_vt_and_aver_dst_2w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height) static
Definition at line 1218 of file h264chroma_msa.c.
Referenced by ff_avg_h264_chroma_mc2_msa().
avc_chroma_vt_and_aver_dst_4x2_msa()
static void avc_chroma_vt_and_aver_dst_4x2_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1) static
Definition at line 1235 of file h264chroma_msa.c.
Referenced by avc_chroma_vt_and_aver_dst_4w_msa().
avc_chroma_vt_and_aver_dst_4x4mul_msa()
static void avc_chroma_vt_and_aver_dst_4x4mul_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height) static
Definition at line 1268 of file h264chroma_msa.c.
Referenced by avc_chroma_vt_and_aver_dst_4w_msa().
avc_chroma_vt_and_aver_dst_4w_msa()
static void avc_chroma_vt_and_aver_dst_4w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height) static
Definition at line 1321 of file h264chroma_msa.c.
Referenced by ff_avg_h264_chroma_mc4_msa().
avc_chroma_vt_and_aver_dst_8w_msa()
static void avc_chroma_vt_and_aver_dst_8w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coeff0, uint32_t coeff1, int32_t height) static
Definition at line 1335 of file h264chroma_msa.c.
Referenced by ff_avg_h264_chroma_mc8_msa().
avc_chroma_hv_and_aver_dst_2x2_msa()
static void avc_chroma_hv_and_aver_dst_2x2_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1) static
Definition at line 1373 of file h264chroma_msa.c.
Referenced by avc_chroma_hv_and_aver_dst_2w_msa().
avc_chroma_hv_and_aver_dst_2x4_msa()
static void avc_chroma_hv_and_aver_dst_2x4_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1) static
Definition at line 1413 of file h264chroma_msa.c.
Referenced by avc_chroma_hv_and_aver_dst_2w_msa().
avc_chroma_hv_and_aver_dst_2x8_msa()
static void avc_chroma_hv_and_aver_dst_2x8_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1) static
Definition at line 1454 of file h264chroma_msa.c.
Referenced by avc_chroma_hv_and_aver_dst_2w_msa().
avc_chroma_hv_and_aver_dst_2w_msa()
static void avc_chroma_hv_and_aver_dst_2w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1, int32_t height) static
Definition at line 1518 of file h264chroma_msa.c.
Referenced by ff_avg_h264_chroma_mc2_msa().
avc_chroma_hv_and_aver_dst_4x2_msa()
static void avc_chroma_hv_and_aver_dst_4x2_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1) static
Definition at line 1541 of file h264chroma_msa.c.
Referenced by avc_chroma_hv_and_aver_dst_4w_msa().
avc_chroma_hv_and_aver_dst_4x4mul_msa()
static void avc_chroma_hv_and_aver_dst_4x4mul_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1, int32_t height) static
Definition at line 1576 of file h264chroma_msa.c.
Referenced by avc_chroma_hv_and_aver_dst_4w_msa().
avc_chroma_hv_and_aver_dst_4w_msa()
static void avc_chroma_hv_and_aver_dst_4w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1, int32_t height) static
Definition at line 1634 of file h264chroma_msa.c.
Referenced by ff_avg_h264_chroma_mc4_msa().
avc_chroma_hv_and_aver_dst_8w_msa()
static void avc_chroma_hv_and_aver_dst_8w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint32_t coef_hor0, uint32_t coef_hor1, uint32_t coef_ver0, uint32_t coef_ver1, int32_t height) static
Definition at line 1653 of file h264chroma_msa.c.
Referenced by ff_avg_h264_chroma_mc8_msa().
copy_width8_msa()
static void copy_width8_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 1714 of file h264chroma_msa.c.
Referenced by ff_put_h264_chroma_mc8_msa().
avg_width4_msa()
static void avg_width4_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 1800 of file h264chroma_msa.c.
Referenced by ff_avg_h264_chroma_mc4_msa().
avg_width8_msa()
static void avg_width8_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 1845 of file h264chroma_msa.c.
Referenced by ff_avg_h264_chroma_mc8_msa().
ff_put_h264_chroma_mc8_msa()
void ff_put_h264_chroma_mc8_msa (uint8_t * dst, uint8_t * src, int stride, int height, int x, int y)
Definition at line 1871 of file h264chroma_msa.c.
ff_put_h264_chroma_mc4_msa()
void ff_put_h264_chroma_mc4_msa (uint8_t * dst, uint8_t * src, int stride, int height, int x, int y)
Definition at line 1888 of file h264chroma_msa.c.
ff_put_h264_chroma_mc2_msa()
void ff_put_h264_chroma_mc2_msa (uint8_t * dst, uint8_t * src, int stride, int height, int x, int y)
Definition at line 1912 of file h264chroma_msa.c.
ff_avg_h264_chroma_mc8_msa()
void ff_avg_h264_chroma_mc8_msa (uint8_t * dst, uint8_t * src, int stride, int height, int x, int y)
Definition at line 1936 of file h264chroma_msa.c.
ff_avg_h264_chroma_mc4_msa()
void ff_avg_h264_chroma_mc4_msa (uint8_t * dst, uint8_t * src, int stride, int height, int x, int y)
Definition at line 1957 of file h264chroma_msa.c.
ff_avg_h264_chroma_mc2_msa()
void ff_avg_h264_chroma_mc2_msa (uint8_t * dst, uint8_t * src, int stride, int height, int x, int y)
Definition at line 1977 of file h264chroma_msa.c.
Variable Documentation
chroma_mask_arr
const uint8_t chroma_mask_arr[16 *5] static
Initial value:
= {
    0, 1, 1, 2, 2, 3, 3, 4, 16, 17, 17, 18, 18, 19, 19, 20,
    0, 2, 2, 4, 4, 6, 6, 8, 16, 18, 18, 20, 20, 22, 22, 24,
    0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8,
    0, 1, 1, 2, 16, 17, 17, 18, 4, 5, 5, 6, 6, 7, 7, 8,
    0, 1, 1, 2, 16, 17, 17, 18, 16, 17, 17, 18, 18, 19, 19, 20
}
Definition at line 24 of file h264chroma_msa.c.
Referenced by avc_chroma_hv_2x2_msa(), avc_chroma_hv_2x4_msa(), avc_chroma_hv_2x8_msa(), avc_chroma_hv_4x2_msa(), avc_chroma_hv_4x4multiple_msa(), avc_chroma_hv_8w_msa(), avc_chroma_hv_and_aver_dst_2x2_msa(), avc_chroma_hv_and_aver_dst_2x4_msa(), avc_chroma_hv_and_aver_dst_2x8_msa(), avc_chroma_hv_and_aver_dst_4x2_msa(), avc_chroma_hv_and_aver_dst_4x4mul_msa(), avc_chroma_hv_and_aver_dst_8w_msa(), avc_chroma_hz_2x2_msa(), avc_chroma_hz_2x4_msa(), avc_chroma_hz_2x8_msa(), avc_chroma_hz_4x2_msa(), avc_chroma_hz_4x4multiple_msa(), avc_chroma_hz_8w_msa(), avc_chroma_hz_and_aver_dst_2x2_msa(), avc_chroma_hz_and_aver_dst_2x4_msa(), avc_chroma_hz_and_aver_dst_2x8_msa(), avc_chroma_hz_and_aver_dst_4x2_msa(), avc_chroma_hz_and_aver_dst_4x4multiple_msa(), and avc_chroma_hz_and_aver_dst_8w_msa().