FFmpeg: libavcodec/mips/h264idct_msa.c File Reference
h264idct_msa.c File Reference
#include "libavutil/mips/generic_macros_msa.h"
#include "h264dsp_mips.h"
#include "libavcodec/bit_depth_template.c"
Macros
#define AVC_ITRANS_H(in0, in1, in2, in3, out0, out1, out2, out3)
#define DC_DEST_STRIDE 16
Functions
static void avc_idct4x4_addblk_msa (uint8_t *dst, int16_t *src, int32_t dst_stride)
static void avc_idct4x4_addblk_dc_msa (uint8_t *dst, int16_t *src, int32_t dst_stride)
static void avc_deq_idct_luma_dc_msa (int16_t *dst, int16_t *src, int32_t de_q_val)
static void avc_idct8_addblk_msa (uint8_t *dst, int16_t *src, int32_t dst_stride)
static void avc_idct8_dc_addblk_msa (uint8_t *dst, int16_t *src, int32_t dst_stride)
void ff_h264_idct_add_msa (uint8_t *dst, int16_t *src, int32_t dst_stride)
void ff_h264_idct8_addblk_msa (uint8_t *dst, int16_t *src, int32_t dst_stride)
void ff_h264_idct4x4_addblk_dc_msa (uint8_t *dst, int16_t *src, int32_t dst_stride)
void ff_h264_idct8_dc_addblk_msa (uint8_t *dst, int16_t *src, int32_t dst_stride)
void ff_h264_idct_add16_msa (uint8_t *dst, const int32_t *blk_offset, int16_t *block, int32_t dst_stride, const uint8_t nzc[15 *8])
void ff_h264_idct8_add4_msa (uint8_t *dst, const int32_t *blk_offset, int16_t *block, int32_t dst_stride, const uint8_t nzc[15 *8])
void ff_h264_idct_add8_msa (uint8_t **dst, const int32_t *blk_offset, int16_t *block, int32_t dst_stride, const uint8_t nzc[15 *8])
void ff_h264_idct_add8_422_msa (uint8_t **dst, const int32_t *blk_offset, int16_t *block, int32_t dst_stride, const uint8_t nzc[15 *8])
void ff_h264_idct_add16_intra_msa (uint8_t *dst, const int32_t *blk_offset, int16_t *block, int32_t dst_stride, const uint8_t nzc[15 *8])
void ff_h264_deq_idct_luma_dc_msa (int16_t *dst, int16_t *src, int32_t de_qval)
Macro Definition Documentation
AVC_ITRANS_H
#define AVC_ITRANS_H (in0, in1, in2, in3, out0, out1, out2, out3)
Value:
{                                                                         \
    v8i16 tmp0_m, tmp1_m, tmp2_m, tmp3_m;                                 \
                                                                          \
    tmp0_m = in0 + in2;                                                   \
    tmp1_m = in0 - in2;                                                   \
    tmp2_m = in1 >> 1;                                                    \
    tmp2_m = tmp2_m - in3;                                                \
    tmp3_m = in3 >> 1;                                                    \
    tmp3_m = in1 + tmp3_m;                                                \
                                                                          \
    BUTTERFLY_4(tmp0_m, tmp1_m, tmp2_m, tmp3_m, out0, out1, out2, out3);  \
}
Definition at line 25 of file h264idct_msa.c.
Referenced by avc_idct4x4_addblk_msa().
DC_DEST_STRIDE
#define DC_DEST_STRIDE 16
Referenced by avc_deq_idct_luma_dc_msa().
Function Documentation
avc_idct4x4_addblk_msa()
static void avc_idct4x4_addblk_msa (uint8_t * dst, int16_t * src, int32_t dst_stride) static
Definition at line 39 of file h264idct_msa.c.
Referenced by ff_h264_idct_add_msa().
avc_idct4x4_addblk_dc_msa()
static void avc_idct4x4_addblk_dc_msa (uint8_t * dst, int16_t * src, int32_t dst_stride) static
Definition at line 56 of file h264idct_msa.c.
Referenced by ff_h264_idct4x4_addblk_dc_msa().
avc_deq_idct_luma_dc_msa()
static void avc_deq_idct_luma_dc_msa (int16_t * dst, int16_t * src, int32_t de_q_val) static
Definition at line 81 of file h264idct_msa.c.
Referenced by ff_h264_deq_idct_luma_dc_msa().
avc_idct8_addblk_msa()
static void avc_idct8_addblk_msa (uint8_t * dst, int16_t * src, int32_t dst_stride) static
Definition at line 155 of file h264idct_msa.c.
Referenced by ff_h264_idct8_addblk_msa().
avc_idct8_dc_addblk_msa()
static void avc_idct8_dc_addblk_msa (uint8_t * dst, int16_t * src, int32_t dst_stride) static
Definition at line 288 of file h264idct_msa.c.
Referenced by ff_h264_idct8_dc_addblk_msa().
ff_h264_idct_add_msa()
void ff_h264_idct_add_msa (uint8_t * dst, int16_t * src, int32_t dst_stride)
Definition at line 320 of file h264idct_msa.c.
Referenced by ff_h264_idct_add16_intra_msa(), ff_h264_idct_add16_msa(), ff_h264_idct_add8_422_msa(), and ff_h264_idct_add8_msa().
ff_h264_idct8_addblk_msa()
void ff_h264_idct8_addblk_msa (uint8_t * dst, int16_t * src, int32_t dst_stride)
Definition at line 327 of file h264idct_msa.c.
Referenced by ff_h264_idct8_add4_msa().
ff_h264_idct4x4_addblk_dc_msa()
void ff_h264_idct4x4_addblk_dc_msa (uint8_t * dst, int16_t * src, int32_t dst_stride)
Definition at line 334 of file h264idct_msa.c.
Referenced by ff_h264_idct_add16_intra_msa(), ff_h264_idct_add16_msa(), ff_h264_idct_add8_422_msa(), and ff_h264_idct_add8_msa().
ff_h264_idct8_dc_addblk_msa()
void ff_h264_idct8_dc_addblk_msa (uint8_t * dst, int16_t * src, int32_t dst_stride)
Definition at line 340 of file h264idct_msa.c.
Referenced by ff_h264_idct8_add4_msa().
ff_h264_idct_add16_msa()
void ff_h264_idct_add16_msa (uint8_t * dst, const int32_t * blk_offset, int16_t * block, int32_t dst_stride, const uint8_t nzc[15 *8])
Definition at line 346 of file h264idct_msa.c.
ff_h264_idct8_add4_msa()
void ff_h264_idct8_add4_msa (uint8_t * dst, const int32_t * blk_offset, int16_t * block, int32_t dst_stride, const uint8_t nzc[15 *8])
Definition at line 369 of file h264idct_msa.c.
ff_h264_idct_add8_msa()
void ff_h264_idct_add8_msa (uint8_t ** dst, const int32_t * blk_offset, int16_t * block, int32_t dst_stride, const uint8_t nzc[15 *8])
Definition at line 391 of file h264idct_msa.c.
ff_h264_idct_add8_422_msa()
void ff_h264_idct_add8_422_msa (uint8_t ** dst, const int32_t * blk_offset, int16_t * block, int32_t dst_stride, const uint8_t nzc[15 *8])
Definition at line 412 of file h264idct_msa.c.
ff_h264_idct_add16_intra_msa()
void ff_h264_idct_add16_intra_msa (uint8_t * dst, const int32_t * blk_offset, int16_t * block, int32_t dst_stride, const uint8_t nzc[15 *8])
Definition at line 446 of file h264idct_msa.c.
ff_h264_deq_idct_luma_dc_msa()
void ff_h264_deq_idct_luma_dc_msa (int16_t * dst, int16_t * src, int32_t de_qval)
Definition at line 465 of file h264idct_msa.c.