FFmpeg: libavcodec/h264dsp_template.c File Reference
h264dsp_template.c File Reference
H.264 / AVC / MPEG-4 part10 DSP functions.
#include "bit_depth_template.c"
Macros
#define op_scale1(x) block[x] = av_clip_pixel((block[x]*weight + offset) >> log2_denom)
#define op_scale2(x) dst[x] = av_clip_pixel((src[x]*weights + dst[x]*weightd + offset) >> (log2_denom+1))
#define H264_WEIGHT(W)
Functions
static av_always_inline av_flatten void FUNCC() h264_loop_filter_luma (uint8_t *p_pix, int xstride, int ystride, int inner_iters, int alpha, int beta, int8_t *tc0)
static void FUNCC() h264_v_loop_filter_luma (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
static void FUNCC() h264_h_loop_filter_luma (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
static void FUNCC() h264_h_loop_filter_luma_mbaff (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
static av_always_inline av_flatten void FUNCC() h264_loop_filter_luma_intra (uint8_t *p_pix, int xstride, int ystride, int inner_iters, int alpha, int beta)
static void FUNCC() h264_v_loop_filter_luma_intra (uint8_t *pix, int stride, int alpha, int beta)
static void FUNCC() h264_h_loop_filter_luma_intra (uint8_t *pix, int stride, int alpha, int beta)
static void FUNCC() h264_h_loop_filter_luma_mbaff_intra (uint8_t *pix, int stride, int alpha, int beta)
static av_always_inline av_flatten void FUNCC() h264_loop_filter_chroma (uint8_t *p_pix, int xstride, int ystride, int inner_iters, int alpha, int beta, int8_t *tc0)
static void FUNCC() h264_v_loop_filter_chroma (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
static void FUNCC() h264_h_loop_filter_chroma (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
static void FUNCC() h264_h_loop_filter_chroma_mbaff (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
static void FUNCC() h264_h_loop_filter_chroma422 (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
static void FUNCC() h264_h_loop_filter_chroma422_mbaff (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
static av_always_inline av_flatten void FUNCC() h264_loop_filter_chroma_intra (uint8_t *p_pix, int xstride, int ystride, int inner_iters, int alpha, int beta)
static void FUNCC() h264_v_loop_filter_chroma_intra (uint8_t *pix, int stride, int alpha, int beta)
static void FUNCC() h264_h_loop_filter_chroma_intra (uint8_t *pix, int stride, int alpha, int beta)
static void FUNCC() h264_h_loop_filter_chroma_mbaff_intra (uint8_t *pix, int stride, int alpha, int beta)
static void FUNCC() h264_h_loop_filter_chroma422_intra (uint8_t *pix, int stride, int alpha, int beta)
static void FUNCC() h264_h_loop_filter_chroma422_mbaff_intra (uint8_t *pix, int stride, int alpha, int beta)
Detailed Description
H.264 / AVC / MPEG-4 part10 DSP functions.
Author
Michael Niedermayer micha.nosp@m.elni.nosp@m.@gmx..nosp@m.at
Definition in file h264dsp_template.c.
Macro Definition Documentation
op_scale1
#define op_scale1 (x) block[x] = av_clip_pixel((block[x]*weight + offset) >> log2_denom)
Definition at line 30 of file h264dsp_template.c.
op_scale2
#define op_scale2 (x) dst[x] = av_clip_pixel((src[x]*weights + dst[x]*weightd + offset) >> (log2_denom+1))
Definition at line 31 of file h264dsp_template.c.
H264_WEIGHT
#define H264_WEIGHT (W)
Definition at line 32 of file h264dsp_template.c.
Function Documentation
h264_loop_filter_luma()
static av_always_inline av_flatten void FUNCC() h264_loop_filter_luma (uint8_t * p_pix, int xstride, int ystride, int inner_iters, int alpha, int beta, int8_t * tc0) static
Definition at line 104 of file h264dsp_template.c.
Referenced by h264_h_loop_filter_luma(), h264_h_loop_filter_luma_mbaff(), and h264_v_loop_filter_luma().
h264_v_loop_filter_luma()
static void FUNCC() h264_v_loop_filter_luma (uint8_t * pix, int stride, int alpha, int beta, int8_t * tc0) static
Definition at line 152 of file h264dsp_template.c.
h264_h_loop_filter_luma()
static void FUNCC() h264_h_loop_filter_luma (uint8_t * pix, int stride, int alpha, int beta, int8_t * tc0) static
Definition at line 156 of file h264dsp_template.c.
h264_h_loop_filter_luma_mbaff()
static void FUNCC() h264_h_loop_filter_luma_mbaff (uint8_t * pix, int stride, int alpha, int beta, int8_t * tc0) static
Definition at line 160 of file h264dsp_template.c.
h264_loop_filter_luma_intra()
static av_always_inline av_flatten void FUNCC() h264_loop_filter_luma_intra (uint8_t * p_pix, int xstride, int ystride, int inner_iters, int alpha, int beta) static
Definition at line 165 of file h264dsp_template.c.
Referenced by h264_h_loop_filter_luma_intra(), h264_h_loop_filter_luma_mbaff_intra(), and h264_v_loop_filter_luma_intra().
h264_v_loop_filter_luma_intra()
static void FUNCC() h264_v_loop_filter_luma_intra (uint8_t * pix, int stride, int alpha, int beta) static
Definition at line 218 of file h264dsp_template.c.
h264_h_loop_filter_luma_intra()
static void FUNCC() h264_h_loop_filter_luma_intra (uint8_t * pix, int stride, int alpha, int beta) static
Definition at line 222 of file h264dsp_template.c.
h264_h_loop_filter_luma_mbaff_intra()
static void FUNCC() h264_h_loop_filter_luma_mbaff_intra (uint8_t * pix, int stride, int alpha, int beta) static
Definition at line 226 of file h264dsp_template.c.
h264_loop_filter_chroma()
static av_always_inline av_flatten void FUNCC() h264_loop_filter_chroma (uint8_t * p_pix, int xstride, int ystride, int inner_iters, int alpha, int beta, int8_t * tc0) static
Definition at line 231 of file h264dsp_template.c.
Referenced by h264_h_loop_filter_chroma(), h264_h_loop_filter_chroma422(), h264_h_loop_filter_chroma422_mbaff(), h264_h_loop_filter_chroma_mbaff(), and h264_v_loop_filter_chroma().
h264_v_loop_filter_chroma()
static void FUNCC() h264_v_loop_filter_chroma (uint8_t * pix, int stride, int alpha, int beta, int8_t * tc0) static
Definition at line 264 of file h264dsp_template.c.
h264_h_loop_filter_chroma()
static void FUNCC() h264_h_loop_filter_chroma (uint8_t * pix, int stride, int alpha, int beta, int8_t * tc0) static
Definition at line 268 of file h264dsp_template.c.
h264_h_loop_filter_chroma_mbaff()
static void FUNCC() h264_h_loop_filter_chroma_mbaff (uint8_t * pix, int stride, int alpha, int beta, int8_t * tc0) static
Definition at line 272 of file h264dsp_template.c.
h264_h_loop_filter_chroma422()
static void FUNCC() h264_h_loop_filter_chroma422 (uint8_t * pix, int stride, int alpha, int beta, int8_t * tc0) static
Definition at line 276 of file h264dsp_template.c.
h264_h_loop_filter_chroma422_mbaff()
static void FUNCC() h264_h_loop_filter_chroma422_mbaff (uint8_t * pix, int stride, int alpha, int beta, int8_t * tc0) static
Definition at line 280 of file h264dsp_template.c.
h264_loop_filter_chroma_intra()
static av_always_inline av_flatten void FUNCC() h264_loop_filter_chroma_intra (uint8_t * p_pix, int xstride, int ystride, int inner_iters, int alpha, int beta) static
Definition at line 285 of file h264dsp_template.c.
Referenced by h264_h_loop_filter_chroma422_intra(), h264_h_loop_filter_chroma422_mbaff_intra(), h264_h_loop_filter_chroma_intra(), h264_h_loop_filter_chroma_mbaff_intra(), and h264_v_loop_filter_chroma_intra().
h264_v_loop_filter_chroma_intra()
static void FUNCC() h264_v_loop_filter_chroma_intra (uint8_t * pix, int stride, int alpha, int beta) static
Definition at line 309 of file h264dsp_template.c.
h264_h_loop_filter_chroma_intra()
static void FUNCC() h264_h_loop_filter_chroma_intra (uint8_t * pix, int stride, int alpha, int beta) static
Definition at line 313 of file h264dsp_template.c.
h264_h_loop_filter_chroma_mbaff_intra()
static void FUNCC() h264_h_loop_filter_chroma_mbaff_intra (uint8_t * pix, int stride, int alpha, int beta) static
Definition at line 317 of file h264dsp_template.c.
h264_h_loop_filter_chroma422_intra()
static void FUNCC() h264_h_loop_filter_chroma422_intra (uint8_t * pix, int stride, int alpha, int beta) static
Definition at line 321 of file h264dsp_template.c.
h264_h_loop_filter_chroma422_mbaff_intra()
static void FUNCC() h264_h_loop_filter_chroma422_mbaff_intra (uint8_t * pix, int stride, int alpha, int beta) static
Definition at line 325 of file h264dsp_template.c.