FFmpeg: libavcodec/mips/h264qpel_mmi.c File Reference
h264qpel_mmi.c File Reference
#include "h264dsp_mips.h"
#include "hpeldsp_mips.h"
#include "libavcodec/bit_depth_template.c"
#include "libavutil/mips/mmiutils.h"
Macros
#define op2_avg(a, b) a = (((a)+CLIP(((b) + 512)>>10)+1)>>1)
#define op2_put(a, b) a = CLIP(((b) + 512)>>10)
Functions
static void copy_block4_mmi (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride, int h)
static void copy_block8_mmi (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride, int h)
static void copy_block16_mmi (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride, int h)
static void put_h264_qpel4_h_lowpass_mmi (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride)
static void put_h264_qpel8_h_lowpass_mmi (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride)
static void put_h264_qpel16_h_lowpass_mmi (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride)
static void avg_h264_qpel4_h_lowpass_mmi (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride)
static void avg_h264_qpel8_h_lowpass_mmi (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride)
static void avg_h264_qpel16_h_lowpass_mmi (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride)
static void put_h264_qpel4_v_lowpass_mmi (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride)
static void put_h264_qpel8_v_lowpass_mmi (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride)
static void put_h264_qpel16_v_lowpass_mmi (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride)
static void avg_h264_qpel4_v_lowpass_mmi (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride)
static void avg_h264_qpel8_v_lowpass_mmi (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride)
static void avg_h264_qpel16_v_lowpass_mmi (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride)
static void put_h264_qpel4_hv_lowpass_mmi (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride)
static void put_h264_qpel8or16_hv1_lowpass_mmi (int16_t *tmp, const uint8_t *src, ptrdiff_t tmpStride, ptrdiff_t srcStride, int size)
static void put_h264_qpel8or16_hv2_lowpass_mmi (uint8_t *dst, int16_t *tmp, ptrdiff_t dstStride, ptrdiff_t tmpStride, int size)
static void put_h264_qpel8or16_hv_lowpass_mmi (uint8_t *dst, int16_t *tmp, const uint8_t *src, ptrdiff_t dstStride, ptrdiff_t tmpStride, ptrdiff_t srcStride, int size)
static void put_h264_qpel8_hv_lowpass_mmi (uint8_t *dst, int16_t *tmp, const uint8_t *src, ptrdiff_t dstStride, ptrdiff_t tmpStride, ptrdiff_t srcStride)
static void put_h264_qpel16_hv_lowpass_mmi (uint8_t *dst, int16_t *tmp, const uint8_t *src, ptrdiff_t dstStride, ptrdiff_t tmpStride, ptrdiff_t srcStride)
static void put_h264_qpel8_h_lowpass_l2_mmi (uint8_t *dst, const uint8_t *src, const uint8_t *src2, ptrdiff_t dstStride, ptrdiff_t src2Stride)
static void put_pixels8_l2_shift5_mmi (uint8_t *dst, int16_t *src16, const uint8_t *src8, ptrdiff_t dstStride, ptrdiff_t src8Stride, int h)
static void put_h264_qpel16_h_lowpass_l2_mmi (uint8_t *dst, const uint8_t *src, const uint8_t *src2, ptrdiff_t dstStride, ptrdiff_t src2Stride)
static void put_pixels16_l2_shift5_mmi (uint8_t *dst, int16_t *src16, const uint8_t *src8, ptrdiff_t dstStride, ptrdiff_t src8Stride, int h)
static void avg_h264_qpel4_hv_lowpass_mmi (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride)
static void avg_h264_qpel8or16_hv2_lowpass_mmi (uint8_t *dst, int16_t *tmp, ptrdiff_t dstStride, ptrdiff_t tmpStride, int size)
static void avg_h264_qpel8or16_hv_lowpass_mmi (uint8_t *dst, int16_t *tmp, const uint8_t *src, ptrdiff_t dstStride, ptrdiff_t tmpStride, ptrdiff_t srcStride, int size)
static void avg_h264_qpel8_hv_lowpass_mmi (uint8_t *dst, int16_t *tmp, const uint8_t *src, ptrdiff_t dstStride, ptrdiff_t tmpStride, ptrdiff_t srcStride)
static void avg_h264_qpel16_hv_lowpass_mmi (uint8_t *dst, int16_t *tmp, const uint8_t *src, ptrdiff_t dstStride, ptrdiff_t tmpStride, ptrdiff_t srcStride)
static void avg_h264_qpel8_h_lowpass_l2_mmi (uint8_t *dst, const uint8_t *src, const uint8_t *src2, ptrdiff_t dstStride, ptrdiff_t src2Stride)
static void avg_h264_qpel16_h_lowpass_l2_mmi (uint8_t *dst, const uint8_t *src, const uint8_t *src2, ptrdiff_t dstStride, ptrdiff_t src2Stride)
static void avg_pixels8_l2_shift5_mmi (uint8_t *dst, int16_t *src16, const uint8_t *src8, ptrdiff_t dstStride, ptrdiff_t src8Stride, int b)
static void avg_pixels16_l2_shift5_mmi (uint8_t *dst, int16_t *src16, const uint8_t *src8, ptrdiff_t dstStride, ptrdiff_t src8Stride, int b)
void ff_put_h264_qpel4_mc00_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc10_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc20_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc30_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc01_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc02_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc03_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc11_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc31_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc13_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc33_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc22_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc21_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc23_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc12_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel4_mc32_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc00_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc10_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc20_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc30_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc01_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc02_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc03_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc11_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc31_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc13_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc33_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc22_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc21_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc23_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc12_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel4_mc32_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc00_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc10_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc20_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc30_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc01_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc02_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc03_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc11_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc31_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc13_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc33_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc22_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc21_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc23_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc12_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel8_mc32_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc00_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc10_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc20_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc30_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc01_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc02_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc03_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc11_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc31_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc13_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc33_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc22_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc21_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc23_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc12_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel8_mc32_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc00_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc10_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc20_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc30_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc01_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc02_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc03_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc11_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc31_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc13_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc33_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc22_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc21_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc23_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc12_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_h264_qpel16_mc32_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc00_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc10_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc20_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc30_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc01_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc02_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc03_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc11_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc31_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc13_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc33_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc22_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc21_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc23_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc12_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_h264_qpel16_mc32_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
Macro Definition Documentation
op2_avg
#define op2_avg (a, b) a = (((a)+CLIP(((b) + 512)>>10)+1)>>1)
Definition at line 107 of file h264qpel_mmi.c.
Referenced by avg_h264_qpel4_hv_lowpass_mmi().
op2_put
#define op2_put (a, b) a = CLIP(((b) + 512)>>10)
Definition at line 108 of file h264qpel_mmi.c.
Referenced by put_h264_qpel4_hv_lowpass_mmi().
Function Documentation
copy_block4_mmi()
static void copy_block4_mmi (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride, int h) inline static
Definition at line 29 of file h264qpel_mmi.c.
Referenced by ff_avg_h264_qpel4_mc01_mmi(), ff_avg_h264_qpel4_mc02_mmi(), ff_avg_h264_qpel4_mc03_mmi(), ff_avg_h264_qpel4_mc11_mmi(), ff_avg_h264_qpel4_mc12_mmi(), ff_avg_h264_qpel4_mc13_mmi(), ff_avg_h264_qpel4_mc31_mmi(), ff_avg_h264_qpel4_mc32_mmi(), ff_avg_h264_qpel4_mc33_mmi(), ff_put_h264_qpel4_mc01_mmi(), ff_put_h264_qpel4_mc02_mmi(), ff_put_h264_qpel4_mc03_mmi(), ff_put_h264_qpel4_mc11_mmi(), ff_put_h264_qpel4_mc12_mmi(), ff_put_h264_qpel4_mc13_mmi(), ff_put_h264_qpel4_mc31_mmi(), ff_put_h264_qpel4_mc32_mmi(), and ff_put_h264_qpel4_mc33_mmi().
copy_block8_mmi()
static void copy_block8_mmi (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride, int h) inline static
Definition at line 53 of file h264qpel_mmi.c.
Referenced by ff_avg_h264_qpel8_mc01_mmi(), ff_avg_h264_qpel8_mc02_mmi(), ff_avg_h264_qpel8_mc03_mmi(), ff_avg_h264_qpel8_mc11_mmi(), ff_avg_h264_qpel8_mc13_mmi(), ff_avg_h264_qpel8_mc31_mmi(), ff_avg_h264_qpel8_mc33_mmi(), ff_put_h264_qpel8_mc01_mmi(), ff_put_h264_qpel8_mc02_mmi(), ff_put_h264_qpel8_mc03_mmi(), ff_put_h264_qpel8_mc11_mmi(), ff_put_h264_qpel8_mc13_mmi(), ff_put_h264_qpel8_mc31_mmi(), and ff_put_h264_qpel8_mc33_mmi().
copy_block16_mmi()
static void copy_block16_mmi (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride, int h) inline static
Definition at line 77 of file h264qpel_mmi.c.
Referenced by ff_avg_h264_qpel16_mc01_mmi(), ff_avg_h264_qpel16_mc02_mmi(), ff_avg_h264_qpel16_mc03_mmi(), ff_avg_h264_qpel16_mc11_mmi(), ff_avg_h264_qpel16_mc13_mmi(), ff_avg_h264_qpel16_mc31_mmi(), ff_avg_h264_qpel16_mc33_mmi(), ff_put_h264_qpel16_mc01_mmi(), ff_put_h264_qpel16_mc02_mmi(), ff_put_h264_qpel16_mc03_mmi(), ff_put_h264_qpel16_mc11_mmi(), ff_put_h264_qpel16_mc13_mmi(), ff_put_h264_qpel16_mc31_mmi(), and ff_put_h264_qpel16_mc33_mmi().
put_h264_qpel4_h_lowpass_mmi()
static void put_h264_qpel4_h_lowpass_mmi (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride) static
Definition at line 109 of file h264qpel_mmi.c.
Referenced by ff_avg_h264_qpel4_mc10_mmi(), ff_avg_h264_qpel4_mc11_mmi(), ff_avg_h264_qpel4_mc13_mmi(), ff_avg_h264_qpel4_mc21_mmi(), ff_avg_h264_qpel4_mc23_mmi(), ff_avg_h264_qpel4_mc30_mmi(), ff_avg_h264_qpel4_mc31_mmi(), ff_avg_h264_qpel4_mc33_mmi(), ff_put_h264_qpel4_mc10_mmi(), ff_put_h264_qpel4_mc11_mmi(), ff_put_h264_qpel4_mc13_mmi(), ff_put_h264_qpel4_mc20_mmi(), ff_put_h264_qpel4_mc21_mmi(), ff_put_h264_qpel4_mc23_mmi(), ff_put_h264_qpel4_mc30_mmi(), ff_put_h264_qpel4_mc31_mmi(), and ff_put_h264_qpel4_mc33_mmi().
put_h264_qpel8_h_lowpass_mmi()
static void put_h264_qpel8_h_lowpass_mmi (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride) static
Definition at line 164 of file h264qpel_mmi.c.
Referenced by ff_avg_h264_qpel8_mc10_mmi(), ff_avg_h264_qpel8_mc11_mmi(), ff_avg_h264_qpel8_mc13_mmi(), ff_avg_h264_qpel8_mc30_mmi(), ff_avg_h264_qpel8_mc31_mmi(), ff_avg_h264_qpel8_mc33_mmi(), ff_put_h264_qpel8_mc10_mmi(), ff_put_h264_qpel8_mc11_mmi(), ff_put_h264_qpel8_mc13_mmi(), ff_put_h264_qpel8_mc20_mmi(), ff_put_h264_qpel8_mc30_mmi(), ff_put_h264_qpel8_mc31_mmi(), ff_put_h264_qpel8_mc33_mmi(), and put_h264_qpel16_h_lowpass_mmi().
put_h264_qpel16_h_lowpass_mmi()
static void put_h264_qpel16_h_lowpass_mmi (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride) static
Definition at line 234 of file h264qpel_mmi.c.
Referenced by ff_avg_h264_qpel16_mc10_mmi(), ff_avg_h264_qpel16_mc11_mmi(), ff_avg_h264_qpel16_mc13_mmi(), ff_avg_h264_qpel16_mc30_mmi(), ff_avg_h264_qpel16_mc31_mmi(), ff_avg_h264_qpel16_mc33_mmi(), ff_put_h264_qpel16_mc10_mmi(), ff_put_h264_qpel16_mc11_mmi(), ff_put_h264_qpel16_mc13_mmi(), ff_put_h264_qpel16_mc20_mmi(), ff_put_h264_qpel16_mc30_mmi(), ff_put_h264_qpel16_mc31_mmi(), and ff_put_h264_qpel16_mc33_mmi().
avg_h264_qpel4_h_lowpass_mmi()
static void avg_h264_qpel4_h_lowpass_mmi (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride) static
Definition at line 245 of file h264qpel_mmi.c.
Referenced by ff_avg_h264_qpel4_mc20_mmi().
avg_h264_qpel8_h_lowpass_mmi()
static void avg_h264_qpel8_h_lowpass_mmi (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride) static
Definition at line 302 of file h264qpel_mmi.c.
Referenced by avg_h264_qpel16_h_lowpass_mmi(), and ff_avg_h264_qpel8_mc20_mmi().
avg_h264_qpel16_h_lowpass_mmi()
static void avg_h264_qpel16_h_lowpass_mmi (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride) static
Definition at line 374 of file h264qpel_mmi.c.
Referenced by ff_avg_h264_qpel16_mc20_mmi().
put_h264_qpel4_v_lowpass_mmi()
static void put_h264_qpel4_v_lowpass_mmi (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride) static
Definition at line 385 of file h264qpel_mmi.c.
Referenced by ff_avg_h264_qpel4_mc01_mmi(), ff_avg_h264_qpel4_mc03_mmi(), ff_avg_h264_qpel4_mc11_mmi(), ff_avg_h264_qpel4_mc12_mmi(), ff_avg_h264_qpel4_mc13_mmi(), ff_avg_h264_qpel4_mc31_mmi(), ff_avg_h264_qpel4_mc32_mmi(), ff_avg_h264_qpel4_mc33_mmi(), ff_put_h264_qpel4_mc01_mmi(), ff_put_h264_qpel4_mc02_mmi(), ff_put_h264_qpel4_mc03_mmi(), ff_put_h264_qpel4_mc11_mmi(), ff_put_h264_qpel4_mc12_mmi(), ff_put_h264_qpel4_mc13_mmi(), ff_put_h264_qpel4_mc31_mmi(), ff_put_h264_qpel4_mc32_mmi(), and ff_put_h264_qpel4_mc33_mmi().
put_h264_qpel8_v_lowpass_mmi()
static void put_h264_qpel8_v_lowpass_mmi (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride) static
Definition at line 494 of file h264qpel_mmi.c.
Referenced by ff_avg_h264_qpel8_mc01_mmi(), ff_avg_h264_qpel8_mc03_mmi(), ff_avg_h264_qpel8_mc11_mmi(), ff_avg_h264_qpel8_mc13_mmi(), ff_avg_h264_qpel8_mc31_mmi(), ff_avg_h264_qpel8_mc33_mmi(), ff_put_h264_qpel8_mc01_mmi(), ff_put_h264_qpel8_mc02_mmi(), ff_put_h264_qpel8_mc03_mmi(), ff_put_h264_qpel8_mc11_mmi(), ff_put_h264_qpel8_mc13_mmi(), ff_put_h264_qpel8_mc31_mmi(), ff_put_h264_qpel8_mc33_mmi(), and put_h264_qpel16_v_lowpass_mmi().
put_h264_qpel16_v_lowpass_mmi()
static void put_h264_qpel16_v_lowpass_mmi (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride) static
Definition at line 792 of file h264qpel_mmi.c.
Referenced by ff_avg_h264_qpel16_mc01_mmi(), ff_avg_h264_qpel16_mc03_mmi(), ff_avg_h264_qpel16_mc11_mmi(), ff_avg_h264_qpel16_mc13_mmi(), ff_avg_h264_qpel16_mc31_mmi(), ff_avg_h264_qpel16_mc33_mmi(), ff_put_h264_qpel16_mc01_mmi(), ff_put_h264_qpel16_mc02_mmi(), ff_put_h264_qpel16_mc03_mmi(), ff_put_h264_qpel16_mc11_mmi(), ff_put_h264_qpel16_mc13_mmi(), ff_put_h264_qpel16_mc31_mmi(), and ff_put_h264_qpel16_mc33_mmi().
avg_h264_qpel4_v_lowpass_mmi()
static void avg_h264_qpel4_v_lowpass_mmi (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride) static
Definition at line 803 of file h264qpel_mmi.c.
Referenced by ff_avg_h264_qpel4_mc02_mmi().
avg_h264_qpel8_v_lowpass_mmi()
static void avg_h264_qpel8_v_lowpass_mmi (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride) static
Definition at line 917 of file h264qpel_mmi.c.
Referenced by avg_h264_qpel16_v_lowpass_mmi(), and ff_avg_h264_qpel8_mc02_mmi().
avg_h264_qpel16_v_lowpass_mmi()
static void avg_h264_qpel16_v_lowpass_mmi (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride) static
Definition at line 1247 of file h264qpel_mmi.c.
Referenced by ff_avg_h264_qpel16_mc02_mmi().
put_h264_qpel4_hv_lowpass_mmi()
static void put_h264_qpel4_hv_lowpass_mmi (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride) static
Definition at line 1258 of file h264qpel_mmi.c.
Referenced by ff_avg_h264_qpel4_mc12_mmi(), ff_avg_h264_qpel4_mc21_mmi(), ff_avg_h264_qpel4_mc23_mmi(), ff_avg_h264_qpel4_mc32_mmi(), ff_put_h264_qpel4_mc12_mmi(), ff_put_h264_qpel4_mc21_mmi(), ff_put_h264_qpel4_mc22_mmi(), ff_put_h264_qpel4_mc23_mmi(), and ff_put_h264_qpel4_mc32_mmi().
put_h264_qpel8or16_hv1_lowpass_mmi()
static void put_h264_qpel8or16_hv1_lowpass_mmi (int16_t * tmp, const uint8_t * src, ptrdiff_t tmpStride, ptrdiff_t srcStride, int size) static
Definition at line 1334 of file h264qpel_mmi.c.
Referenced by avg_h264_qpel8or16_hv_lowpass_mmi(), and put_h264_qpel8or16_hv_lowpass_mmi().
put_h264_qpel8or16_hv2_lowpass_mmi()
static void put_h264_qpel8or16_hv2_lowpass_mmi (uint8_t * dst, int16_t * tmp, ptrdiff_t dstStride, ptrdiff_t tmpStride, int size) static
Definition at line 1579 of file h264qpel_mmi.c.
Referenced by put_h264_qpel8or16_hv_lowpass_mmi().
put_h264_qpel8or16_hv_lowpass_mmi()
static void put_h264_qpel8or16_hv_lowpass_mmi (uint8_t * dst, int16_t * tmp, const uint8_t * src, ptrdiff_t dstStride, ptrdiff_t tmpStride, ptrdiff_t srcStride, int size) static
Definition at line 1650 of file h264qpel_mmi.c.
Referenced by put_h264_qpel16_hv_lowpass_mmi(), and put_h264_qpel8_hv_lowpass_mmi().
put_h264_qpel8_hv_lowpass_mmi()
static void put_h264_qpel8_hv_lowpass_mmi (uint8_t * dst, int16_t * tmp, const uint8_t * src, ptrdiff_t dstStride, ptrdiff_t tmpStride, ptrdiff_t srcStride) static
Definition at line 1658 of file h264qpel_mmi.c.
Referenced by ff_avg_h264_qpel8_mc12_mmi(), ff_avg_h264_qpel8_mc21_mmi(), ff_avg_h264_qpel8_mc23_mmi(), ff_avg_h264_qpel8_mc32_mmi(), ff_put_h264_qpel8_mc12_mmi(), ff_put_h264_qpel8_mc21_mmi(), ff_put_h264_qpel8_mc22_mmi(), ff_put_h264_qpel8_mc23_mmi(), and ff_put_h264_qpel8_mc32_mmi().
put_h264_qpel16_hv_lowpass_mmi()
static void put_h264_qpel16_hv_lowpass_mmi (uint8_t * dst, int16_t * tmp, const uint8_t * src, ptrdiff_t dstStride, ptrdiff_t tmpStride, ptrdiff_t srcStride) static
Definition at line 1666 of file h264qpel_mmi.c.
Referenced by ff_avg_h264_qpel16_mc12_mmi(), ff_avg_h264_qpel16_mc21_mmi(), ff_avg_h264_qpel16_mc23_mmi(), ff_avg_h264_qpel16_mc32_mmi(), ff_put_h264_qpel16_mc12_mmi(), ff_put_h264_qpel16_mc21_mmi(), ff_put_h264_qpel16_mc22_mmi(), ff_put_h264_qpel16_mc23_mmi(), and ff_put_h264_qpel16_mc32_mmi().
put_h264_qpel8_h_lowpass_l2_mmi()
static void put_h264_qpel8_h_lowpass_l2_mmi (uint8_t * dst, const uint8_t * src, const uint8_t * src2, ptrdiff_t dstStride, ptrdiff_t src2Stride) static
Definition at line 1674 of file h264qpel_mmi.c.
Referenced by ff_put_h264_qpel8_mc21_mmi(), ff_put_h264_qpel8_mc23_mmi(), and put_h264_qpel16_h_lowpass_l2_mmi().
put_pixels8_l2_shift5_mmi()
static void put_pixels8_l2_shift5_mmi (uint8_t * dst, int16_t * src16, const uint8_t * src8, ptrdiff_t dstStride, ptrdiff_t src8Stride, int h) static
Definition at line 1750 of file h264qpel_mmi.c.
Referenced by ff_put_h264_qpel8_mc12_mmi(), ff_put_h264_qpel8_mc32_mmi(), and put_pixels16_l2_shift5_mmi().
put_h264_qpel16_h_lowpass_l2_mmi()
static void put_h264_qpel16_h_lowpass_l2_mmi (uint8_t * dst, const uint8_t * src, const uint8_t * src2, ptrdiff_t dstStride, ptrdiff_t src2Stride) static
Definition at line 1798 of file h264qpel_mmi.c.
Referenced by ff_put_h264_qpel16_mc21_mmi(), and ff_put_h264_qpel16_mc23_mmi().
put_pixels16_l2_shift5_mmi()
static void put_pixels16_l2_shift5_mmi (uint8_t * dst, int16_t * src16, const uint8_t * src8, ptrdiff_t dstStride, ptrdiff_t src8Stride, int h) static
Definition at line 1814 of file h264qpel_mmi.c.
Referenced by ff_put_h264_qpel16_mc12_mmi(), and ff_put_h264_qpel16_mc32_mmi().
avg_h264_qpel4_hv_lowpass_mmi()
static void avg_h264_qpel4_hv_lowpass_mmi (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride) static
Definition at line 1822 of file h264qpel_mmi.c.
Referenced by ff_avg_h264_qpel4_mc22_mmi().
avg_h264_qpel8or16_hv2_lowpass_mmi()
static void avg_h264_qpel8or16_hv2_lowpass_mmi (uint8_t * dst, int16_t * tmp, ptrdiff_t dstStride, ptrdiff_t tmpStride, int size) static
Definition at line 1898 of file h264qpel_mmi.c.
Referenced by avg_h264_qpel8or16_hv_lowpass_mmi().
avg_h264_qpel8or16_hv_lowpass_mmi()
static void avg_h264_qpel8or16_hv_lowpass_mmi (uint8_t * dst, int16_t * tmp, const uint8_t * src, ptrdiff_t dstStride, ptrdiff_t tmpStride, ptrdiff_t srcStride, int size) static
Definition at line 1971 of file h264qpel_mmi.c.
Referenced by avg_h264_qpel16_hv_lowpass_mmi(), and avg_h264_qpel8_hv_lowpass_mmi().
avg_h264_qpel8_hv_lowpass_mmi()
static void avg_h264_qpel8_hv_lowpass_mmi (uint8_t * dst, int16_t * tmp, const uint8_t * src, ptrdiff_t dstStride, ptrdiff_t tmpStride, ptrdiff_t srcStride) static
Definition at line 1979 of file h264qpel_mmi.c.
Referenced by ff_avg_h264_qpel8_mc22_mmi().
avg_h264_qpel16_hv_lowpass_mmi()
static void avg_h264_qpel16_hv_lowpass_mmi (uint8_t * dst, int16_t * tmp, const uint8_t * src, ptrdiff_t dstStride, ptrdiff_t tmpStride, ptrdiff_t srcStride) static
Definition at line 1987 of file h264qpel_mmi.c.
Referenced by ff_avg_h264_qpel16_mc22_mmi().
avg_h264_qpel8_h_lowpass_l2_mmi()
static void avg_h264_qpel8_h_lowpass_l2_mmi (uint8_t * dst, const uint8_t * src, const uint8_t * src2, ptrdiff_t dstStride, ptrdiff_t src2Stride) static
Definition at line 1995 of file h264qpel_mmi.c.
Referenced by avg_h264_qpel16_h_lowpass_l2_mmi(), ff_avg_h264_qpel8_mc21_mmi(), and ff_avg_h264_qpel8_mc23_mmi().
avg_h264_qpel16_h_lowpass_l2_mmi()
static void avg_h264_qpel16_h_lowpass_l2_mmi (uint8_t * dst, const uint8_t * src, const uint8_t * src2, ptrdiff_t dstStride, ptrdiff_t src2Stride) static
Definition at line 2073 of file h264qpel_mmi.c.
Referenced by ff_avg_h264_qpel16_mc21_mmi(), and ff_avg_h264_qpel16_mc23_mmi().
avg_pixels8_l2_shift5_mmi()
static void avg_pixels8_l2_shift5_mmi (uint8_t * dst, int16_t * src16, const uint8_t * src8, ptrdiff_t dstStride, ptrdiff_t src8Stride, int b) static
Definition at line 2089 of file h264qpel_mmi.c.
Referenced by avg_pixels16_l2_shift5_mmi(), ff_avg_h264_qpel8_mc12_mmi(), and ff_avg_h264_qpel8_mc32_mmi().
avg_pixels16_l2_shift5_mmi()
static void avg_pixels16_l2_shift5_mmi (uint8_t * dst, int16_t * src16, const uint8_t * src8, ptrdiff_t dstStride, ptrdiff_t src8Stride, int b) static
Definition at line 2141 of file h264qpel_mmi.c.
Referenced by ff_avg_h264_qpel16_mc12_mmi(), and ff_avg_h264_qpel16_mc32_mmi().
ff_put_h264_qpel4_mc00_mmi()
void ff_put_h264_qpel4_mc00_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2150 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc10_mmi()
void ff_put_h264_qpel4_mc10_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2156 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc20_mmi()
void ff_put_h264_qpel4_mc20_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2164 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc30_mmi()
void ff_put_h264_qpel4_mc30_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2170 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc01_mmi()
void ff_put_h264_qpel4_mc01_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2178 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc02_mmi()
void ff_put_h264_qpel4_mc02_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2189 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc03_mmi()
void ff_put_h264_qpel4_mc03_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2198 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc11_mmi()
void ff_put_h264_qpel4_mc11_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2209 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc31_mmi()
void ff_put_h264_qpel4_mc31_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2222 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc13_mmi()
void ff_put_h264_qpel4_mc13_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2235 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc33_mmi()
void ff_put_h264_qpel4_mc33_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2248 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc22_mmi()
void ff_put_h264_qpel4_mc22_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2261 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc21_mmi()
void ff_put_h264_qpel4_mc21_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2267 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc23_mmi()
void ff_put_h264_qpel4_mc23_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2277 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc12_mmi()
void ff_put_h264_qpel4_mc12_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2287 of file h264qpel_mmi.c.
ff_put_h264_qpel4_mc32_mmi()
void ff_put_h264_qpel4_mc32_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2300 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc00_mmi()
void ff_avg_h264_qpel4_mc00_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2314 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc10_mmi()
void ff_avg_h264_qpel4_mc10_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2320 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc20_mmi()
void ff_avg_h264_qpel4_mc20_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2328 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc30_mmi()
void ff_avg_h264_qpel4_mc30_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2334 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc01_mmi()
void ff_avg_h264_qpel4_mc01_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2342 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc02_mmi()
void ff_avg_h264_qpel4_mc02_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2353 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc03_mmi()
void ff_avg_h264_qpel4_mc03_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2362 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc11_mmi()
void ff_avg_h264_qpel4_mc11_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2373 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc31_mmi()
void ff_avg_h264_qpel4_mc31_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2386 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc13_mmi()
void ff_avg_h264_qpel4_mc13_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2399 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc33_mmi()
void ff_avg_h264_qpel4_mc33_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2412 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc22_mmi()
void ff_avg_h264_qpel4_mc22_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2425 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc21_mmi()
void ff_avg_h264_qpel4_mc21_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2431 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc23_mmi()
void ff_avg_h264_qpel4_mc23_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2441 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc12_mmi()
void ff_avg_h264_qpel4_mc12_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2451 of file h264qpel_mmi.c.
ff_avg_h264_qpel4_mc32_mmi()
void ff_avg_h264_qpel4_mc32_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2464 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc00_mmi()
void ff_put_h264_qpel8_mc00_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2478 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc10_mmi()
void ff_put_h264_qpel8_mc10_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2484 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc20_mmi()
void ff_put_h264_qpel8_mc20_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2492 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc30_mmi()
void ff_put_h264_qpel8_mc30_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2498 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc01_mmi()
void ff_put_h264_qpel8_mc01_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2506 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc02_mmi()
void ff_put_h264_qpel8_mc02_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2517 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc03_mmi()
void ff_put_h264_qpel8_mc03_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2526 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc11_mmi()
void ff_put_h264_qpel8_mc11_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2537 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc31_mmi()
void ff_put_h264_qpel8_mc31_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2550 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc13_mmi()
void ff_put_h264_qpel8_mc13_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2563 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc33_mmi()
void ff_put_h264_qpel8_mc33_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2576 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc22_mmi()
void ff_put_h264_qpel8_mc22_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2589 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc21_mmi()
void ff_put_h264_qpel8_mc21_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2597 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc23_mmi()
void ff_put_h264_qpel8_mc23_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2608 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc12_mmi()
void ff_put_h264_qpel8_mc12_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2619 of file h264qpel_mmi.c.
ff_put_h264_qpel8_mc32_mmi()
void ff_put_h264_qpel8_mc32_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2630 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc00_mmi()
void ff_avg_h264_qpel8_mc00_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2642 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc10_mmi()
void ff_avg_h264_qpel8_mc10_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2648 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc20_mmi()
void ff_avg_h264_qpel8_mc20_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2656 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc30_mmi()
void ff_avg_h264_qpel8_mc30_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2662 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc01_mmi()
void ff_avg_h264_qpel8_mc01_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2670 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc02_mmi()
void ff_avg_h264_qpel8_mc02_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2681 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc03_mmi()
void ff_avg_h264_qpel8_mc03_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2690 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc11_mmi()
void ff_avg_h264_qpel8_mc11_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2701 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc31_mmi()
void ff_avg_h264_qpel8_mc31_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2714 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc13_mmi()
void ff_avg_h264_qpel8_mc13_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2727 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc33_mmi()
void ff_avg_h264_qpel8_mc33_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2740 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc22_mmi()
void ff_avg_h264_qpel8_mc22_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2753 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc21_mmi()
void ff_avg_h264_qpel8_mc21_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2761 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc23_mmi()
void ff_avg_h264_qpel8_mc23_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2772 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc12_mmi()
void ff_avg_h264_qpel8_mc12_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2783 of file h264qpel_mmi.c.
ff_avg_h264_qpel8_mc32_mmi()
void ff_avg_h264_qpel8_mc32_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2794 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc00_mmi()
void ff_put_h264_qpel16_mc00_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2806 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc10_mmi()
void ff_put_h264_qpel16_mc10_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2812 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc20_mmi()
void ff_put_h264_qpel16_mc20_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2820 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc30_mmi()
void ff_put_h264_qpel16_mc30_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2826 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc01_mmi()
void ff_put_h264_qpel16_mc01_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2834 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc02_mmi()
void ff_put_h264_qpel16_mc02_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2845 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc03_mmi()
void ff_put_h264_qpel16_mc03_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2854 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc11_mmi()
void ff_put_h264_qpel16_mc11_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2865 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc31_mmi()
void ff_put_h264_qpel16_mc31_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2878 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc13_mmi()
void ff_put_h264_qpel16_mc13_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2891 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc33_mmi()
void ff_put_h264_qpel16_mc33_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2904 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc22_mmi()
void ff_put_h264_qpel16_mc22_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2917 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc21_mmi()
void ff_put_h264_qpel16_mc21_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2925 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc23_mmi()
void ff_put_h264_qpel16_mc23_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2936 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc12_mmi()
void ff_put_h264_qpel16_mc12_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2947 of file h264qpel_mmi.c.
ff_put_h264_qpel16_mc32_mmi()
void ff_put_h264_qpel16_mc32_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2958 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc00_mmi()
void ff_avg_h264_qpel16_mc00_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2970 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc10_mmi()
void ff_avg_h264_qpel16_mc10_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2976 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc20_mmi()
void ff_avg_h264_qpel16_mc20_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2984 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc30_mmi()
void ff_avg_h264_qpel16_mc30_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2990 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc01_mmi()
void ff_avg_h264_qpel16_mc01_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 2998 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc02_mmi()
void ff_avg_h264_qpel16_mc02_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3009 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc03_mmi()
void ff_avg_h264_qpel16_mc03_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3018 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc11_mmi()
void ff_avg_h264_qpel16_mc11_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3029 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc31_mmi()
void ff_avg_h264_qpel16_mc31_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3042 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc13_mmi()
void ff_avg_h264_qpel16_mc13_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3055 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc33_mmi()
void ff_avg_h264_qpel16_mc33_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3068 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc22_mmi()
void ff_avg_h264_qpel16_mc22_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3081 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc21_mmi()
void ff_avg_h264_qpel16_mc21_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3089 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc23_mmi()
void ff_avg_h264_qpel16_mc23_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3100 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc12_mmi()
void ff_avg_h264_qpel16_mc12_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3111 of file h264qpel_mmi.c.
ff_avg_h264_qpel16_mc32_mmi()
void ff_avg_h264_qpel16_mc32_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 3122 of file h264qpel_mmi.c.