FFmpeg: libavcodec/h264pred_template.c File Reference
h264pred_template.c File Reference
H.264 / AVC / MPEG-4 part10 prediction functions.
#include "libavutil/intreadwrite.h"
#include "mathops.h"
#include "bit_depth_template.c"
Macros
#define LOAD_TOP_RIGHT_EDGE
#define LOAD_DOWN_LEFT_EDGE
#define LOAD_LEFT_EDGE
#define LOAD_TOP_EDGE
#define PREDICT_16x16_DC(v)
#define PRED16x16_X(n, v)
#define PRED8x8_X(n, v)
#define SRC(x, y) src[(x)+(y)*stride]
#define PL(y) const int l##y = (SRC(-1,y-1) + 2*SRC(-1,y) + SRC(-1,y+1) + 2) >> 2;
#define PREDICT_8x8_LOAD_LEFT
#define PT(x) const int t##x = (SRC(x-1,-1) + 2*SRC(x,-1) + SRC(x+1,-1) + 2) >> 2;
#define PREDICT_8x8_LOAD_TOP
#define PTR(x) t##x = (SRC(x-1,-1) + 2*SRC(x,-1) + SRC(x+1,-1) + 2) >> 2;
#define PREDICT_8x8_LOAD_TOPRIGHT
#define PREDICT_8x8_LOAD_TOPLEFT const int lt = (SRC(-1,0) + 2*SRC(-1,-1) + SRC(0,-1) + 2) >> 2
#define PREDICT_8x8_DC(v)
#define ROW(y)
Functions
static void FUNCC() pred4x4_vertical (uint8_t *_src, const uint8_t *topright, ptrdiff_t _stride)
static void FUNCC() pred4x4_horizontal (uint8_t *_src, const uint8_t *topright, ptrdiff_t _stride)
static void FUNCC() pred4x4_dc (uint8_t *_src, const uint8_t *topright, ptrdiff_t _stride)
static void FUNCC() pred4x4_left_dc (uint8_t *_src, const uint8_t *topright, ptrdiff_t _stride)
static void FUNCC() pred4x4_top_dc (uint8_t *_src, const uint8_t *topright, ptrdiff_t _stride)
static void FUNCC() pred4x4_128_dc (uint8_t *_src, const uint8_t *topright, ptrdiff_t _stride)
static void FUNCC() pred4x4_127_dc (uint8_t *_src, const uint8_t *topright, ptrdiff_t _stride)
static void FUNCC() pred4x4_129_dc (uint8_t *_src, const uint8_t *topright, ptrdiff_t _stride)
static void FUNCC() pred4x4_down_right (uint8_t *_src, const uint8_t *topright, ptrdiff_t _stride)
static void FUNCC() pred4x4_down_left (uint8_t *_src, const uint8_t *_topright, ptrdiff_t _stride)
static void FUNCC() pred4x4_vertical_right (uint8_t *_src, const uint8_t *topright, ptrdiff_t _stride)
static void FUNCC() pred4x4_vertical_left (uint8_t *_src, const uint8_t *_topright, ptrdiff_t _stride)
static void FUNCC() pred4x4_horizontal_up (uint8_t *_src, const uint8_t *topright, ptrdiff_t _stride)
static void FUNCC() pred4x4_horizontal_down (uint8_t *_src, const uint8_t *topright, ptrdiff_t _stride)
static void FUNCC() pred16x16_vertical (uint8_t *_src, ptrdiff_t _stride)
static void FUNCC() pred16x16_horizontal (uint8_t *_src, ptrdiff_t stride)
static void FUNCC() pred16x16_dc (uint8_t *_src, ptrdiff_t stride)
static void FUNCC() pred16x16_left_dc (uint8_t *_src, ptrdiff_t stride)
static void FUNCC() pred16x16_top_dc (uint8_t *_src, ptrdiff_t stride)
PRED16x16_X (127,(1<<(BIT_DEPTH-1)) -1) PRED16x16_X(128
for (j=16;j >0;--j)
static void FUNCC() pred16x16_plane (uint8_t *src, ptrdiff_t stride)
static void FUNCC() pred8x8_vertical (uint8_t *_src, ptrdiff_t _stride)
static void FUNCC() pred8x16_vertical (uint8_t *_src, ptrdiff_t _stride)
static void FUNCC() pred8x8_horizontal (uint8_t *_src, ptrdiff_t stride)
static void FUNCC() pred8x16_horizontal (uint8_t *_src, ptrdiff_t stride)
PRED8x8_X (127,(1<<(BIT_DEPTH-1)) -1) PRED8x8_X(128
for (i=0;i< 4;i++)
static void FUNCC() pred8x16_left_dc (uint8_t *_src, ptrdiff_t stride)
static void FUNCC() pred8x8_top_dc (uint8_t *_src, ptrdiff_t stride)
static void FUNCC() pred8x16_top_dc (uint8_t *_src, ptrdiff_t stride)
static void FUNCC() pred8x8_dc (uint8_t *_src, ptrdiff_t stride)
static void FUNCC() pred8x16_dc (uint8_t *_src, ptrdiff_t stride)
static void FUNC() pred8x8_mad_cow_dc_l0t (uint8_t *src, ptrdiff_t stride)
static void FUNC() pred8x16_mad_cow_dc_l0t (uint8_t *src, ptrdiff_t stride)
static void FUNC() pred8x8_mad_cow_dc_0lt (uint8_t *src, ptrdiff_t stride)
static void FUNC() pred8x16_mad_cow_dc_0lt (uint8_t *src, ptrdiff_t stride)
static void FUNC() pred8x8_mad_cow_dc_l00 (uint8_t *src, ptrdiff_t stride)
static void FUNC() pred8x16_mad_cow_dc_l00 (uint8_t *src, ptrdiff_t stride)
static void FUNC() pred8x8_mad_cow_dc_0l0 (uint8_t *src, ptrdiff_t stride)
static void FUNC() pred8x16_mad_cow_dc_0l0 (uint8_t *src, ptrdiff_t stride)
static void FUNCC() pred8x8_plane (uint8_t *_src, ptrdiff_t _stride)
static void FUNCC() pred8x16_plane (uint8_t *_src, ptrdiff_t _stride)
static void FUNCC() pred8x8l_128_dc (uint8_t *_src, int has_topleft, int has_topright, ptrdiff_t _stride)
static void FUNCC() pred8x8l_left_dc (uint8_t *_src, int has_topleft, int has_topright, ptrdiff_t _stride)
static void FUNCC() pred8x8l_top_dc (uint8_t *_src, int has_topleft, int has_topright, ptrdiff_t _stride)
static void FUNCC() pred8x8l_dc (uint8_t *_src, int has_topleft, int has_topright, ptrdiff_t _stride)
static void FUNCC() pred8x8l_horizontal (uint8_t *_src, int has_topleft, int has_topright, ptrdiff_t _stride)
static void FUNCC() pred8x8l_vertical (uint8_t *_src, int has_topleft, int has_topright, ptrdiff_t _stride)
static void FUNCC() pred8x8l_down_left (uint8_t *_src, int has_topleft, int has_topright, ptrdiff_t _stride)
static void FUNCC() pred8x8l_down_right (uint8_t *_src, int has_topleft, int has_topright, ptrdiff_t _stride)
static void FUNCC() pred8x8l_vertical_right (uint8_t *_src, int has_topleft, int has_topright, ptrdiff_t _stride)
static void FUNCC() pred8x8l_horizontal_down (uint8_t *_src, int has_topleft, int has_topright, ptrdiff_t _stride)
static void FUNCC() pred8x8l_vertical_left (uint8_t *_src, int has_topleft, int has_topright, ptrdiff_t _stride)
static void FUNCC() pred8x8l_horizontal_up (uint8_t *_src, int has_topleft, int has_topright, ptrdiff_t _stride)
static void FUNCC() pred8x8l_vertical_filter_add (uint8_t *_src, int16_t *_block, int has_topleft, int has_topright, ptrdiff_t _stride)
static void FUNCC() pred8x8l_horizontal_filter_add (uint8_t *_src, int16_t *_block, int has_topleft, int has_topright, ptrdiff_t _stride)
static void FUNCC() pred4x4_vertical_add (uint8_t *_pix, int16_t *_block, ptrdiff_t stride)
static void FUNCC() pred4x4_horizontal_add (uint8_t *_pix, int16_t *_block, ptrdiff_t stride)
static void FUNCC() pred8x8l_vertical_add (uint8_t *_pix, int16_t *_block, ptrdiff_t stride)
static void FUNCC() pred8x8l_horizontal_add (uint8_t *_pix, int16_t *_block, ptrdiff_t stride)
static void FUNCC() pred16x16_vertical_add (uint8_t *pix, const int *block_offset, int16_t *block, ptrdiff_t stride)
static void FUNCC() pred16x16_horizontal_add (uint8_t *pix, const int *block_offset, int16_t *block, ptrdiff_t stride)
static void FUNCC() pred8x8_vertical_add (uint8_t *pix, const int *block_offset, int16_t *block, ptrdiff_t stride)
static void FUNCC() pred8x16_vertical_add (uint8_t *pix, const int *block_offset, int16_t *block, ptrdiff_t stride)
static void FUNCC() pred8x8_horizontal_add (uint8_t *pix, const int *block_offset, int16_t *block, ptrdiff_t stride)
static void FUNCC() pred8x16_horizontal_add (uint8_t *pix, const int *block_offset, int16_t *block, ptrdiff_t stride)
Variables
<<(BIT_DEPTH-1))+0) PRED16x16_X(129,(1<<(BIT_DEPTH-1))+1) static inline void FUNCC(pred16x16_plane_compat)(uint8_t *_src, ptrdiff_t _stride, const int svq3, const int rv40) { int i, j, k;int a;INIT_CLIP pixel *src=(pixel *) _src;int stride=_stride >>(sizeof(pixel) -1);const pixel *const src0=src+7-stride;const pixel *src1=src+8 *stride-1;const pixel *src2=src1-2 *stride;int H=src0[1] - src0[-1];int V=src1[0] - src2[0];for(k=2;k<=8;++k) { src1+=stride;src2 -=stride;H+=k *(src0[k] - src0[-k]);V+=k *(src1[0] - src2[0]);} if(svq3){ H=(5 *(H/4))/16;V=(5 *(V/4))/16;i=H;H=V;V=i;}else if(rv40){ H=(H+(H >> V = (V + (V>>2)) >> 4
else
a = 16*(src1[0] + src2[16] + 1) - 7*(V+H)
<<(BIT_DEPTH-1))+0) PRED8x8_X(129,(1<<(BIT_DEPTH-1))+1) static void FUNCC(pred8x16_128_dc)(uint8_t *_src, ptrdiff_t stride) { FUNCC(pred8x8_128_dc)(_src, stride);FUNCC(pred8x8_128_dc)(_src+8 *stride, stride);} static void FUNCC(pred8x8_left_dc)(uint8_t *_src, ptrdiff_t stride) { int i;int dc0, dc2;pixel4 dc0splat, dc2splat;pixel *src=(pixel *) _src;stride >>=sizeof(pixel) -1;dc0=dc2=0;for(i=0;i< 4;i++){ dc0+=src[-1+i *stride];dc2+=src[-1+(i+4) *stride];} dc0splat=PIXEL_SPLAT_X4((dc0+2)>> dc2splat = PIXEL_SPLAT_X4((dc2 + 2)>>2)
Detailed Description
H.264 / AVC / MPEG-4 part10 prediction functions.
Author
Michael Niedermayer micha.nosp@m.elni.nosp@m.@gmx..nosp@m.at
Definition in file h264pred_template.c.
Macro Definition Documentation
LOAD_TOP_RIGHT_EDGE
#define LOAD_TOP_RIGHT_EDGE
Value:
const unsigned av_unused t4 = topright[0];\
    const unsigned av_unused t5 = topright[1];\
    const unsigned av_unused t6 = topright[2];\
    const unsigned av_unused t7 = topright[3];\
Definition at line 141 of file h264pred_template.c.
Referenced by pred4x4_down_left(), pred4x4_down_left_rv40_c(), pred4x4_down_left_rv40_nodown_c(), pred4x4_horizontal_up_rv40_c(), pred4x4_horizontal_up_rv40_nodown_c(), pred4x4_vertical_left(), pred4x4_vertical_left_rv40(), pred4x4_vertical_left_vp8_c(), and pred4x4_vertical_vp8_c().
LOAD_DOWN_LEFT_EDGE
#define LOAD_DOWN_LEFT_EDGE
Value:
const unsigned av_unused l4 = src[-1+4*stride];\
    const unsigned av_unused l5 = src[-1+5*stride];\
    const unsigned av_unused l6 = src[-1+6*stride];\
    const unsigned av_unused l7 = src[-1+7*stride];\
Definition at line 147 of file h264pred_template.c.
Referenced by pred4x4_down_left_rv40_c(), pred4x4_horizontal_up_rv40_c(), and pred4x4_vertical_left_rv40_c().
LOAD_LEFT_EDGE
#define LOAD_LEFT_EDGE
Value:
const unsigned av_unused l0 = src[-1+0*stride];\
    const unsigned av_unused l1 = src[-1+1*stride];\
    const unsigned av_unused l2 = src[-1+2*stride];\
    const unsigned av_unused l3 = src[-1+3*stride];\
Definition at line 153 of file h264pred_template.c.
Referenced by pred4x4_down_left_rv40_c(), pred4x4_down_left_rv40_nodown_c(), pred4x4_down_left_svq3_c(), pred4x4_down_right(), pred4x4_horizontal_down(), pred4x4_horizontal_up(), pred4x4_horizontal_up_rv40_c(), pred4x4_horizontal_up_rv40_nodown_c(), pred4x4_horizontal_vp8_c(), pred4x4_vertical_left_rv40_c(), pred4x4_vertical_left_rv40_nodown_c(), and pred4x4_vertical_right().
LOAD_TOP_EDGE
#define LOAD_TOP_EDGE
Value:
const unsigned av_unused t0 = src[ 0-1*stride];\
    const unsigned av_unused t1 = src[ 1-1*stride];\
    const unsigned av_unused t2 = src[ 2-1*stride];\
    const unsigned av_unused t3 = src[ 3-1*stride];\
Definition at line 159 of file h264pred_template.c.
Referenced by pred4x4_down_left(), pred4x4_down_left_rv40_c(), pred4x4_down_left_rv40_nodown_c(), pred4x4_down_left_svq3_c(), pred4x4_down_right(), pred4x4_horizontal_down(), pred4x4_horizontal_up_rv40_c(), pred4x4_horizontal_up_rv40_nodown_c(), pred4x4_vertical_left(), pred4x4_vertical_left_rv40(), pred4x4_vertical_left_vp8_c(), pred4x4_vertical_right(), and pred4x4_vertical_vp8_c().
PREDICT_16x16_DC
#define PREDICT_16x16_DC (v)
Value:
for(i=0; i<16; i++){\
        AV_WN4PA(src+ 0, v);\
        AV_WN4PA(src+ 4, v);\
        AV_WN4PA(src+ 8, v);\
        AV_WN4PA(src+12, v);\
        src += stride;\
    }
Definition at line 363 of file h264pred_template.c.
Referenced by pred16x16_dc(), pred16x16_left_dc(), and pred16x16_top_dc().
PRED16x16_X
#define PRED16x16_X (n, v)
Value:
static void FUNCC(pred16x16_##n##_dc)(uint8_t *_src, ptrdiff_t stride)\
{\
    int i;\
    pixel *src = (pixel*)_src;\
    stride >>= sizeof(pixel)-1;\
    PREDICT_16x16_DC(PIXEL_SPLAT_X4(v));\
}
Definition at line 421 of file h264pred_template.c.
PRED8x8_X
#define PRED8x8_X (n, v)
Value:
static void FUNCC(pred8x8_##n##_dc)(uint8_t *_src, ptrdiff_t stride)\
{\
    int i;\
    const pixel4 a = PIXEL_SPLAT_X4(v);\
    pixel *src = (pixel*)_src;\
    stride >>= sizeof(pixel)-1;\
    for(i=0; i<8; i++){\
        AV_WN4PA(((pixel4*)(src+i*stride))+0, a);\
        AV_WN4PA(((pixel4*)(src+i*stride))+1, a);\
    }\
}
Definition at line 541 of file h264pred_template.c.
SRC
#define SRC (x, y) src[(x)+(y)*stride]
Definition at line 847 of file h264pred_template.c.
Referenced by dct_sad8x8_c(), pred8x8l_down_left(), pred8x8l_down_right(), pred8x8l_horizontal_down(), pred8x8l_horizontal_up(), pred8x8l_vertical_left(), and pred8x8l_vertical_right().
PL
#define PL (y) const int l##y = (SRC(-1,y-1) + 2*SRC(-1,y) + SRC(-1,y+1) + 2) >> 2;
Definition at line 848 of file h264pred_template.c.
PREDICT_8x8_LOAD_LEFT
#define PREDICT_8x8_LOAD_LEFT
Value:
const int l0 = ((has_topleft ? SRC(-1,-1) : SRC(-1,0)) \
                     + 2*SRC(-1,0) + SRC(-1,1) + 2) >> 2; \
    PL(1) PL(2) PL(3) PL(4) PL(5) PL(6) \
    const int l7 av_unused = (SRC(-1,6) + 3*SRC(-1,7) + 2) >> 2
Definition at line 850 of file h264pred_template.c.
Referenced by pred8x8l_dc(), pred8x8l_down_right(), pred8x8l_horizontal(), pred8x8l_horizontal_down(), pred8x8l_horizontal_filter_add(), pred8x8l_horizontal_up(), pred8x8l_left_dc(), and pred8x8l_vertical_right().
PT
#define PT (x) const int t##x = (SRC(x-1,-1) + 2*SRC(x,-1) + SRC(x+1,-1) + 2) >> 2;
Definition at line 856 of file h264pred_template.c.
PREDICT_8x8_LOAD_TOP
#define PREDICT_8x8_LOAD_TOP
Value:
const int t0 = ((has_topleft ? SRC(-1,-1) : SRC(0,-1)) \
                     + 2*SRC(0,-1) + SRC(1,-1) + 2) >> 2; \
    PT(1) PT(2) PT(3) PT(4) PT(5) PT(6) \
    const int t7 av_unused = ((has_topright ? SRC(8,-1) : SRC(7,-1)) \
                     + 2*SRC(7,-1) + SRC(6,-1) + 2) >> 2
Definition at line 858 of file h264pred_template.c.
Referenced by pred8x8l_dc(), pred8x8l_down_left(), pred8x8l_down_right(), pred8x8l_horizontal_down(), pred8x8l_top_dc(), pred8x8l_vertical(), pred8x8l_vertical_filter_add(), pred8x8l_vertical_left(), and pred8x8l_vertical_right().
PTR
#define PTR (x) t##x = (SRC(x-1,-1) + 2*SRC(x,-1) + SRC(x+1,-1) + 2) >> 2;
Definition at line 865 of file h264pred_template.c.
PREDICT_8x8_LOAD_TOPRIGHT
#define PREDICT_8x8_LOAD_TOPRIGHT
Value:
int t8, t9, t10, t11, t12, t13, t14, t15; \
    if(has_topright) { \
        PTR(8) PTR(9) PTR(10) PTR(11) PTR(12) PTR(13) PTR(14) \
        t15 = (SRC(14,-1) + 3*SRC(15,-1) + 2) >> 2; \
    } else t8=t9=t10=t11=t12=t13=t14=t15= SRC(7,-1);
Definition at line 867 of file h264pred_template.c.
Referenced by pred8x8l_down_left(), and pred8x8l_vertical_left().
PREDICT_8x8_LOAD_TOPLEFT
#define PREDICT_8x8_LOAD_TOPLEFT const int lt = (SRC(-1,0) + 2*SRC(-1,-1) + SRC(0,-1) + 2) >> 2
Definition at line 874 of file h264pred_template.c.
Referenced by pred8x8l_down_right(), pred8x8l_horizontal_down(), and pred8x8l_vertical_right().
PREDICT_8x8_DC
#define PREDICT_8x8_DC (v)
Value:
int y; \
    for( y = 0; y < 8; y++ ) { \
        AV_WN4PA(((pixel4*)src)+0, v); \
        AV_WN4PA(((pixel4*)src)+1, v); \
        src += stride; \
    }
Definition at line 877 of file h264pred_template.c.
Referenced by pred8x8l_128_dc(), pred8x8l_dc(), pred8x8l_left_dc(), and pred8x8l_top_dc().
ROW
#define ROW (y)
Value:
a = PIXEL_SPLAT_X4(l##y); \
               AV_WN4PA(src+y*stride, a); \
               AV_WN4PA(src+y*stride+4, a);
Referenced by pred8x8l_horizontal().
Function Documentation
pred4x4_vertical()
static void FUNCC() pred4x4_vertical (uint8_t * _src, const uint8_t * topright, ptrdiff_t _stride) static
Definition at line 34 of file h264pred_template.c.
pred4x4_horizontal()
static void FUNCC() pred4x4_horizontal (uint8_t * _src, const uint8_t * topright, ptrdiff_t _stride) static
Definition at line 47 of file h264pred_template.c.
pred4x4_dc()
static void FUNCC() pred4x4_dc (uint8_t * _src, const uint8_t * topright, ptrdiff_t _stride) static
Definition at line 58 of file h264pred_template.c.
Referenced by pred8x16_mad_cow_dc_l0t(), and pred8x8_mad_cow_dc_l0t().
pred4x4_left_dc()
static void FUNCC() pred4x4_left_dc (uint8_t * _src, const uint8_t * topright, ptrdiff_t _stride) static
Definition at line 73 of file h264pred_template.c.
pred4x4_top_dc()
static void FUNCC() pred4x4_top_dc (uint8_t * _src, const uint8_t * topright, ptrdiff_t _stride) static
Definition at line 87 of file h264pred_template.c.
Referenced by pred8x16_mad_cow_dc_0lt(), and pred8x8_mad_cow_dc_0lt().
pred4x4_128_dc()
static void FUNCC() pred4x4_128_dc (uint8_t * _src, const uint8_t * topright, ptrdiff_t _stride) static
Definition at line 101 of file h264pred_template.c.
Referenced by pred8x16_mad_cow_dc_0l0(), pred8x16_mad_cow_dc_l00(), pred8x8_mad_cow_dc_0l0(), and pred8x8_mad_cow_dc_l00().
pred4x4_127_dc()
static void FUNCC() pred4x4_127_dc (uint8_t * _src, const uint8_t * topright, ptrdiff_t _stride) static
Definition at line 114 of file h264pred_template.c.
pred4x4_129_dc()
static void FUNCC() pred4x4_129_dc (uint8_t * _src, const uint8_t * topright, ptrdiff_t _stride) static
Definition at line 127 of file h264pred_template.c.
pred4x4_down_right()
static void FUNCC() pred4x4_down_right (uint8_t * _src, const uint8_t * topright, ptrdiff_t _stride) static
Definition at line 165 of file h264pred_template.c.
pred4x4_down_left()
static void FUNCC() pred4x4_down_left (uint8_t * _src, const uint8_t * _topright, ptrdiff_t _stride) static
Definition at line 192 of file h264pred_template.c.
pred4x4_vertical_right()
static void FUNCC() pred4x4_vertical_right (uint8_t * _src, const uint8_t * topright, ptrdiff_t _stride) static
Definition at line 220 of file h264pred_template.c.
pred4x4_vertical_left()
static void FUNCC() pred4x4_vertical_left (uint8_t * _src, const uint8_t * _topright, ptrdiff_t _stride) static
Definition at line 248 of file h264pred_template.c.
pred4x4_horizontal_up()
static void FUNCC() pred4x4_horizontal_up (uint8_t * _src, const uint8_t * topright, ptrdiff_t _stride) static
Definition at line 276 of file h264pred_template.c.
pred4x4_horizontal_down()
static void FUNCC() pred4x4_horizontal_down (uint8_t * _src, const uint8_t * topright, ptrdiff_t _stride) static
Definition at line 301 of file h264pred_template.c.
pred16x16_vertical()
static void FUNCC() pred16x16_vertical (uint8_t * _src, ptrdiff_t _stride) static
Definition at line 329 of file h264pred_template.c.
pred16x16_horizontal()
static void FUNCC() pred16x16_horizontal (uint8_t * _src, ptrdiff_t stride) static
Definition at line 347 of file h264pred_template.c.
pred16x16_dc()
static void FUNCC() pred16x16_dc (uint8_t * _src, ptrdiff_t stride) static
Definition at line 372 of file h264pred_template.c.
pred16x16_left_dc()
static void FUNCC() pred16x16_left_dc (uint8_t * _src, ptrdiff_t stride) static
Definition at line 391 of file h264pred_template.c.
pred16x16_top_dc()
static void FUNCC() pred16x16_top_dc (uint8_t * _src, ptrdiff_t stride) static
Definition at line 406 of file h264pred_template.c.
PRED16x16_X()
PRED16x16_X (127 , (1<<(BIT_DEPTH-1)) - 1)
for() [1/2]
for (j = 16; j, 0;-- j)
Examples:
filter_audio.c, and muxing.c.
Definition at line 469 of file h264pred_template.c.
Referenced by aac_encode_frame(), ac3_decode_frame(), ac3_decode_transform_coeffs_ch(), add_frame_default(), adpcm_decode_frame(), adpcm_encode_frame(), alloc_frame(), alloc_picture(), alpha_composite(), ape_decode_frame(), apng_do_inverse_blend(), apply_filter(), apply_window_and_mdct(), asf_read_header(), audio_read_packet(), av_hmac_final(), av_hmac_init(), av_hwframe_ctx_init(), av_image_fill_pointers(), av_pix_fmt_count_planes(), avpriv_solve_lls(), bfi_decode_frame(), bidirectional_obmc(), blend_image_packed_rgb(), bmv_aud_decode_frame(), build_table(), calc_masking(), cdg_load_palette(), cfhd_decode(), choose_rct_params(), chs_filter_band_data(), chs_parse_header(), cng_decode_frame(), compute_frame_rms(), compute_frame_std_dev(), compute_stereo(), config_input(), config_input_ref(), config_output(), copy_frame_default(), copy_pad(), debug_mean_error(), decode_block(), decode_element(), decode_frame(), decode_mode(), decode_packet(), decode_residual_spectrum(), decode_rgbxi(), decode_tag(), decode_ybr10i(), decode_yry10i(), decorrelate(), dnxhd_unquantize_c(), do_psnr(), draw_axis_rgb(), draw_vtext(), drawtext(), dss_sp_update_state(), encode_frame(), encode_headers(), encode_init(), encode_tile(), envelope_instant16(), envelope_peak16(), epic_jb_decode_tile(), evrc_decode_frame(), evrc_decode_init(), expand_timestamps(), ff_atrac_gain_compensation(), ff_dca_core_filter_fixed(), ff_dca_xll_filter_frame(), ff_draw_horiz_band(), ff_h264_decode_mb_cabac(), ff_h264_draw_horiz_band(), ff_h264_execute_decode_slices(), ff_hevc_frame_nb_refs(), ff_hevc_hls_residual_coding(), ff_jpegls_decode_picture(), ff_jpegls_init_state(), ff_mjpeg_decode_frame(), ff_mpeg4_pred_ac(), ff_qsv_enc_init(), ff_rv34_decode_frame(), fill_picture(), fill_picture_parameters(), fill_quantization_matrices(), fill_scaling_lists(), fill_yuv_image(), filter16_brng(), filter16_tout(), filter16_vrep(), filter_frame(), filter_frame_fixed(), filter_frame_float(), find_peak_magnitude(), fix_transparency(), flashsv_decode_frame(), flip_swap_frame(), flush_buffer(), free_buffers(), generate_intervals(), generate_joint_tables(), get_buffer(), get_fcb_param(), get_input(), gif_fill(), gif_fill_rect(), gif_read_image(), idcin_decode_init(), imc_decode_block(), imc_decode_init(), init(), init_image(), input_to_sample_buffer(), interpolate(), ipvideo_decode_block_opcode_0x9_16(), ipvideo_decode_block_opcode_0xA_16(), ipvideo_decode_block_opcode_0xB_16(), ipvideo_decode_block_opcode_0xC_16(), ipvideo_decode_block_opcode_0xD_16(), is_yuv_planar(), lag_decode_frame(), lavfi_read_header(), lfe_downsample(), libgsm_decode_frame(), libopenjpeg_copy_packed12(), libopenjpeg_copy_packed16(), libopenjpeg_copy_unpacked16(), libopenjpeg_copy_unpacked8(), libopus_decode(), lut2_16bit(), m101_decode_frame(), magy_decode_slice10(), mclms_update(), movie_common_init(), mss4_decode_image_block(), mss4_update_dc_cache(), msvideo1_decode_16bit(), mxf_compute_ptses_fake_index(), mxf_get_sorted_table_segments(), mxf_read_close(), nvenc_register_frame(), paf_audio_decode(), parse_high_res_grid(), parse_mb_skip(), pcm_decode_frame(), perform_compression(), perform_dc_correction(), pitch_sharpening(), plot_freqs(), plot_spectrum_column(), pnm_decode_frame(), postfilter(), predictor_calc_error(), print_audio_bytes(), process_callback(), push_single_pic(), qdm2_decode_fft_packets(), qdm2_decode_frame(), qsv_init_opaque_alloc(), query_formats(), ra288_decode_frame(), read_old_huffman_tables(), read_packet(), recheck_discard_flags(), request_frame(), restore_rgb_planes10(), restore_tqb_pixels(), run_channel_fft(), s302m_decode_frame(), s302m_encode2_frame(), search_for_quantizers_twoloop(), set_ct_depth(), setup_pps(), shorten_decode_frame(), sub2video_copy_rect(), subband_transform(), sws_diffVec(), sws_init_context(), sws_sumVec(), synth_superframe(), tak_decode_frame(), try_push_frame(), tta_decode_frame(), txd_decode_frame(), use_normal_update_speed(), v410_decode_frame(), v410_encode_frame(), vcr1_decode_frame(), vectorscope8(), vmdvideo_decode_init(), vorbis_encode_frame(), vp56_parse_mb_type_models(), wavesynth_decode(), write_palette(), xwd_decode_frame(), y216_decode_frame(), yop_decode_frame(), and zerocodec_decode_frame().
pred16x16_plane()
static void FUNCC() pred16x16_plane (uint8_t * src, ptrdiff_t stride) static
Definition at line 483 of file h264pred_template.c.
pred8x8_vertical()
static void FUNCC() pred8x8_vertical (uint8_t * _src, ptrdiff_t _stride) static
Definition at line 488 of file h264pred_template.c.
pred8x16_vertical()
static void FUNCC() pred8x16_vertical (uint8_t * _src, ptrdiff_t _stride) static
Definition at line 502 of file h264pred_template.c.
pred8x8_horizontal()
static void FUNCC() pred8x8_horizontal (uint8_t * _src, ptrdiff_t stride) static
Definition at line 516 of file h264pred_template.c.
pred8x16_horizontal()
static void FUNCC() pred8x16_horizontal (uint8_t * _src, ptrdiff_t stride) static
Definition at line 529 of file h264pred_template.c.
PRED8x8_X()
PRED8x8_X (127 , (1<<(BIT_DEPTH-1)) - 1)
for() [2/2]
for ()
Definition at line 580 of file h264pred_template.c.
pred8x16_left_dc()
static void FUNCC() pred8x16_left_dc (uint8_t * _src, ptrdiff_t stride) static
Definition at line 590 of file h264pred_template.c.
Referenced by pred8x16_mad_cow_dc_0l0(), and pred8x16_mad_cow_dc_l00().
pred8x8_top_dc()
static void FUNCC() pred8x8_top_dc (uint8_t * _src, ptrdiff_t stride) static
Definition at line 596 of file h264pred_template.c.
Referenced by pred8x8_mad_cow_dc_l0t().
pred8x16_top_dc()
static void FUNCC() pred8x16_top_dc (uint8_t * _src, ptrdiff_t stride) static
Definition at line 622 of file h264pred_template.c.
Referenced by pred8x16_mad_cow_dc_l0t().
pred8x8_dc()
static void FUNCC() pred8x8_dc (uint8_t * _src, ptrdiff_t stride) static
Definition at line 644 of file h264pred_template.c.
Referenced by pred8x8_mad_cow_dc_0lt().
pred8x16_dc()
static void FUNCC() pred8x16_dc (uint8_t * _src, ptrdiff_t stride) static
Definition at line 673 of file h264pred_template.c.
Referenced by pred8x16_mad_cow_dc_0lt().
pred8x8_mad_cow_dc_l0t()
static void FUNC() pred8x8_mad_cow_dc_l0t (uint8_t * src, ptrdiff_t stride) static
Definition at line 717 of file h264pred_template.c.
pred8x16_mad_cow_dc_l0t()
static void FUNC() pred8x16_mad_cow_dc_l0t (uint8_t * src, ptrdiff_t stride) static
Definition at line 723 of file h264pred_template.c.
pred8x8_mad_cow_dc_0lt()
static void FUNC() pred8x8_mad_cow_dc_0lt (uint8_t * src, ptrdiff_t stride) static
Definition at line 729 of file h264pred_template.c.
pred8x16_mad_cow_dc_0lt()
static void FUNC() pred8x16_mad_cow_dc_0lt (uint8_t * src, ptrdiff_t stride) static
Definition at line 735 of file h264pred_template.c.
pred8x8_mad_cow_dc_l00()
static void FUNC() pred8x8_mad_cow_dc_l00 (uint8_t * src, ptrdiff_t stride) static
Definition at line 741 of file h264pred_template.c.
pred8x16_mad_cow_dc_l00()
static void FUNC() pred8x16_mad_cow_dc_l00 (uint8_t * src, ptrdiff_t stride) static
Definition at line 748 of file h264pred_template.c.
pred8x8_mad_cow_dc_0l0()
static void FUNC() pred8x8_mad_cow_dc_0l0 (uint8_t * src, ptrdiff_t stride) static
Definition at line 755 of file h264pred_template.c.
pred8x16_mad_cow_dc_0l0()
static void FUNC() pred8x16_mad_cow_dc_0l0 (uint8_t * src, ptrdiff_t stride) static
Definition at line 762 of file h264pred_template.c.
pred8x8_plane()
static void FUNCC() pred8x8_plane (uint8_t * _src, ptrdiff_t _stride) static
Definition at line 769 of file h264pred_template.c.
pred8x16_plane()
static void FUNCC() pred8x16_plane (uint8_t * _src, ptrdiff_t _stride) static
Definition at line 805 of file h264pred_template.c.
pred8x8l_128_dc()
static void FUNCC() pred8x8l_128_dc (uint8_t * _src, int has_topleft, int has_topright, ptrdiff_t _stride) static
Definition at line 885 of file h264pred_template.c.
pred8x8l_left_dc()
static void FUNCC() pred8x8l_left_dc (uint8_t * _src, int has_topleft, int has_topright, ptrdiff_t _stride) static
Definition at line 893 of file h264pred_template.c.
pred8x8l_top_dc()
static void FUNCC() pred8x8l_top_dc (uint8_t * _src, int has_topleft, int has_topright, ptrdiff_t _stride) static
Definition at line 903 of file h264pred_template.c.
pred8x8l_dc()
static void FUNCC() pred8x8l_dc (uint8_t * _src, int has_topleft, int has_topright, ptrdiff_t _stride) static
Definition at line 913 of file h264pred_template.c.
pred8x8l_horizontal()
static void FUNCC() pred8x8l_horizontal (uint8_t * _src, int has_topleft, int has_topright, ptrdiff_t _stride) static
Definition at line 925 of file h264pred_template.c.
pred8x8l_vertical()
static void FUNCC() pred8x8l_vertical (uint8_t * _src, int has_topleft, int has_topright, ptrdiff_t _stride) static
Definition at line 939 of file h264pred_template.c.
pred8x8l_down_left()
static void FUNCC() pred8x8l_down_left (uint8_t * _src, int has_topleft, int has_topright, ptrdiff_t _stride) static
Definition at line 963 of file h264pred_template.c.
pred8x8l_down_right()
static void FUNCC() pred8x8l_down_right (uint8_t * _src, int has_topleft, int has_topright, ptrdiff_t _stride) static
Definition at line 986 of file h264pred_template.c.
pred8x8l_vertical_right()
static void FUNCC() pred8x8l_vertical_right (uint8_t * _src, int has_topleft, int has_topright, ptrdiff_t _stride) static
Definition at line 1010 of file h264pred_template.c.
pred8x8l_horizontal_down()
static void FUNCC() pred8x8l_horizontal_down (uint8_t * _src, int has_topleft, int has_topright, ptrdiff_t _stride) static
Definition at line 1041 of file h264pred_template.c.
pred8x8l_vertical_left()
static void FUNCC() pred8x8l_vertical_left (uint8_t * _src, int has_topleft, int has_topright, ptrdiff_t _stride) static
Definition at line 1072 of file h264pred_template.c.
pred8x8l_horizontal_up()
static void FUNCC() pred8x8l_horizontal_up (uint8_t * _src, int has_topleft, int has_topright, ptrdiff_t _stride) static
Definition at line 1102 of file h264pred_template.c.
pred8x8l_vertical_filter_add()
static void FUNCC() pred8x8l_vertical_filter_add (uint8_t * _src, int16_t * _block, int has_topleft, int has_topright, ptrdiff_t _stride) static
Definition at line 1128 of file h264pred_template.c.
pred8x8l_horizontal_filter_add()
static void FUNCC() pred8x8l_horizontal_filter_add (uint8_t * _src, int16_t * _block, int has_topleft, int has_topright, ptrdiff_t _stride) static
Definition at line 1164 of file h264pred_template.c.
pred4x4_vertical_add()
static void FUNCC() pred4x4_vertical_add (uint8_t * _pix, int16_t * _block, ptrdiff_t stride) static
Definition at line 1210 of file h264pred_template.c.
Referenced by pred16x16_vertical_add(), pred8x16_vertical_add(), and pred8x8_vertical_add().
pred4x4_horizontal_add()
static void FUNCC() pred4x4_horizontal_add (uint8_t * _pix, int16_t * _block, ptrdiff_t stride) static
Definition at line 1231 of file h264pred_template.c.
Referenced by pred16x16_horizontal_add(), pred8x16_horizontal_add(), and pred8x8_horizontal_add().
pred8x8l_vertical_add()
static void FUNCC() pred8x8l_vertical_add (uint8_t * _pix, int16_t * _block, ptrdiff_t stride) static
Definition at line 1251 of file h264pred_template.c.
pred8x8l_horizontal_add()
static void FUNCC() pred8x8l_horizontal_add (uint8_t * _pix, int16_t * _block, ptrdiff_t stride) static
Definition at line 1276 of file h264pred_template.c.
pred16x16_vertical_add()
static void FUNCC() pred16x16_vertical_add (uint8_t * pix, const int * block_offset, int16_t * block, ptrdiff_t stride) static
Definition at line 1300 of file h264pred_template.c.
pred16x16_horizontal_add()
static void FUNCC() pred16x16_horizontal_add (uint8_t * pix, const int * block_offset, int16_t * block, ptrdiff_t stride) static
Definition at line 1309 of file h264pred_template.c.
pred8x8_vertical_add()
static void FUNCC() pred8x8_vertical_add (uint8_t * pix, const int * block_offset, int16_t * block, ptrdiff_t stride) static
Definition at line 1319 of file h264pred_template.c.
pred8x16_vertical_add()
static void FUNCC() pred8x16_vertical_add (uint8_t * pix, const int * block_offset, int16_t * block, ptrdiff_t stride) static
Definition at line 1327 of file h264pred_template.c.
pred8x8_horizontal_add()
static void FUNCC() pred8x8_horizontal_add (uint8_t * pix, const int * block_offset, int16_t * block, ptrdiff_t stride) static
Definition at line 1337 of file h264pred_template.c.
pred8x16_horizontal_add()
static void FUNCC() pred8x16_horizontal_add (uint8_t * pix, const int * block_offset, int16_t * block, ptrdiff_t stride) static
Definition at line 1346 of file h264pred_template.c.
Variable Documentation
V
V = (V + (V>>2)) >> 4
Definition at line 462 of file h264pred_template.c.
Referenced by for(), pred8x16_plane(), and pred8x8_plane().
else
else
Initial value:
{
    H = ( 5*H+32 ) >> 6
Definition at line 463 of file h264pred_template.c.
a
a = 16*(src1[0] + src2[16] + 1) - 7*(V+H)
Definition at line 468 of file h264pred_template.c.
Referenced by a64_compress_colram(), a64multi_encode_init(), abs_pow34_v(), add_bytes_c(), add_bytes_l2_c(), add_cb(), add_hfyu_left_pred_bgr32_c(), add_int16_c(), ARRAY_RENAME(), audiogen(), av_add_i(), av_add_sf(), av_clip64_c(), av_clip_c(), av_clip_int16_c(), av_clip_int8_c(), av_clip_intp2_c(), av_clip_uint16_c(), av_clip_uint8_c(), av_clip_uintp2_c(), av_clipd_c(), av_clipf_c(), av_clipl_int32_c(), av_compare_ts(), av_d2q(), av_div_sf(), av_gcd(), av_i2int(), av_int2i(), av_isxdigit(), av_mlfg_get(), av_mod_i(), av_mul_sf(), av_nearer_q(), av_normalize1_sf(), av_normalize_sf(), av_rescale_delta(), av_rescale_rnd(), av_sub_i(), avg_no_rnd_vc1_chroma_mc4_c(), avpriv_trc_arib_std_b67(), avpriv_trc_bt1361(), avpriv_trc_bt709(), avpriv_trc_iec61966_2_1(), avpriv_trc_iec61966_2_4(), avpriv_trc_smpte240M(), avui_decode_frame(), bidir_refine(), bidir_sal(), bidirectional_obmc(), blend_plane(), blur_power(), body(), calc_lowcomp1(), calc_pe_3gpp(), can_merge_formats(), chebyshev1_bp_filter(), chebyshev2_bp_filter(), check_ipred(), clipf_c_one(), clone_filter_formats(), cmp_color(), cmp_func_names(), cmp_intervals(), cmp_pkt_sub_pos_ts(), cmp_pkt_sub_ts_pos(), compare_codec_desc(), compare_vlcspec(), compute_metric(), convert_alignment(), cpu_suffix(), cqt_calc(), create_vorbis_context(), cubic_interpolate_func(), decode_argb(), decode_argbi(), decode_argx(), decode_argxi(), decode_aybr(), decode_aybri(), decode_block(), decode_block_coeffs_internal(), decode_ca4i(), decode_ca4p(), decode_coeffs(), decode_end(), decode_flush(), decode_frame(), decode_init(), decode_mode(), decode_predictor_coeffs(), decode_rgb_frame(), decode_subframe_fixed(), decorrelate(), decorrelate_ls(), decorrelate_sf(), decorrelate_sm(), decorrelate_sr(), decorrelate_stereo(), deInterlaceBlendLinear(), deInterlaceInterpolateLinear(), deInterlaceMedian(), diff_bytes_c(), diff_int16_c(), diff_pixels_mvi(), draw_axis_rgb(), dss_sp_convert_coeffs(), dss_sp_shift_sq_add(), dss_sp_shift_sq_sub(), dss_sp_unpack_coeffs(), dss_sp_update_state(), dv_guess_qnos(), dvbsub_init_decoder(), encode_block(), encode_dvb_subtitles(), encode_frame(), encode_init(), encode_picture(), encode_residual_fixed(), encode_rgb_frame(), encode_superframe(), end(), extract_color(), ff_add_png_paeth_prediction(), ff_adx_calculate_coeffs(), ff_asv_common_init(), ff_audio_data_alloc(), ff_avc_find_startcode_internal(), ff_avg_pixels4_xy2_8_mmi(), ff_avg_pixels8_xy2_8_mmi(), ff_big_add(), ff_big_mul(), ff_celp_lp_synthesis_filterf(), ff_dsd2pcm_translate(), ff_eval_refl(), ff_get_qtpalette(), ff_h263_pred_acdc(), ff_h263_pred_dc(), ff_h264_chroma_dc_dequant_idct(), ff_h264_chroma_dc_dequant_idct_8_mmi(), ff_h264_filter_mb(), ff_index_search_timestamp(), ff_interp(), ff_intra_pred_8_16x16_msa(), ff_intra_pred_8_32x32_msa(), ff_lpc_calc_ref_coefs_f(), ff_merge_channel_layouts(), ff_merge_formats(), ff_merge_samplerates(), ff_mov_read_stsd_entries(), ff_mpeg4_pred_dc(), ff_msmpeg4_coded_block_pred(), ff_msmpeg4_pred_dc(), ff_nut_sp_pos_cmp(), ff_nut_sp_pts_cmp(), ff_put_no_rnd_pixels8_xy2_8_mmi(), ff_put_pixels4_xy2_8_mmi(), ff_put_pixels8_xy2_8_mmi(), ff_put_vp8_bilinear16_h_mmi(), ff_put_vp8_bilinear16_hv_mmi(), ff_put_vp8_bilinear4_h_mmi(), ff_put_vp8_bilinear4_hv_mmi(), ff_put_vp8_bilinear8_h_mmi(), ff_put_vp8_bilinear8_hv_mmi(), ff_rate_estimate_qscale(), ff_rfps_calculate(), ff_sqrf(), ff_stream_add_bitstream_filter(), ff_sws_alphablendaway(), ff_u8_to_s8(), ff_ut10_huff_cmp_len(), ff_ut_huff_cmp_len(), ff_vc1_h_overlap_mmi(), ff_vc1_h_s_overlap_mmi(), ff_vc1_pred_dc(), ff_vc1_v_overlap_mmi(), ff_vc1_v_s_overlap_mmi(), ff_wma_init(), ffat_compare_channel_descriptions(), fft_ref(), fill24(), filter_common(), filter_frame(), filter_mb_edgech(), filter_mb_edgecv(), filter_mb_edgeh(), filter_mb_edgev(), filter_mb_mbaff_edgecv(), filter_mb_mbaff_edgev(), filter_slice(), flac_decorrelate_ls_c(), flac_decorrelate_ms_c(), flac_decorrelate_rs_c(), float_near_ulp(), for(), gen_sub_bitmap(), get(), get_amv(), get_diff_limited_q(), get_integral_patch_value(), get_qscale(), get_shift(), get_symbol(), get_symbol_inline(), getSplineCoeff(), glyph_cmp(), gmc_motion(), h264_filter_mb_fast_internal(), h_block_filter(), hardthresh_c(), horizX1Filter(), huff_cmp(), huff_cmp_len(), huff_cmp_len10(), huff_cmp_sym(), init(), init_luts(), init_pass2(), int_cos(), int_pow(), int_sin(), interleave(), interpol(), interpolate(), intra_pred(), intra_pred_dc_128(), intra_pred_horiz(), intra_pred_vert(), intra_recon(), invert_step(), lag_decode_frame(), lbr_bank_c(), lcg_seek(), lfe_fir_fixed_c(), lfe_fir_float_c(), lfe_x96_fixed_c(), lfe_x96_float_c(), loco_predict(), main(), matroska_parse_rm_audio(), mc_block(), mediumthresh_c(), mid_pred(), mix_core(), mode02(), mode03(), mode04(), mov_read_default(), MPA_encode_init(), mpeg4_decode_sprite_trajectory(), mul_thrmat_c(), multiswap_dec(), multiswap_enc(), non_j_pixfmt(), norm__(), paint_mouse_pointer(), parse_high_res_grid(), parse_pixel_format(), plot_freq(), plot_freqs(), png_filter_row(), pow_m1_4(), pred16x16_horizontal(), pred16x16_vertical(), pred4x4_127_dc(), pred4x4_128_dc(), pred4x4_129_dc(), pred4x4_dc(), pred4x4_left_dc(), pred4x4_top_dc(), pred4x4_vertical(), pred8x16_plane(), pred8x8_plane(), pred8x8l_horizontal(), pred8x8l_vertical(), pred_dc(), pred_spatial_direct_motion(), predict(), premult2straight(), ps_decorrelate_c(), put_no_rnd_pixels_l2(), put_symbol(), put_symbol_inline(), quant(), read_highpass(), ready_residue(), render_charset(), replicate32(), replicate64(), resample_cubic(), resample_flush(), residue_encode(), ripemd128_transform(), ripemd160_transform(), ripemd256_transform(), ripemd320_transform(), run_postproc(), run_psnr(), run_test(), set(), set_palette(), set_string_binary(), sha1_transform(), sha256_transform(), sha512_transform(), silk_decode_excitation(), softthresh_c(), spatial_compensation_0(), ssim_4x4x2_core(), ssim_4x4xn_16bit(), ssim_4x4xn_8bit(), sub_left_prediction_bgr32(), sub_png_paeth_prediction(), swri_realloc_audio(), sws_scale(), synth_filter_fixed(), synth_filter_fixed_64(), synth_filter_float(), synth_filter_float_64(), tgq_calculate_qtable(), transform_step(), uninit(), upsample_plane_c(), v408_decode_frame(), v408_encode_frame(), v_block_filter(), vb_decode_framedata(), vc1_coded_block_pred(), vc1_h_overlap_c(), vc1_h_s_overlap_c(), vc1_i_pred_dc(), vc1_v_overlap_c(), vc1_v_s_overlap_c(), vcr1_decode_frame(), vertX1Filter(), video_audio_display(), vorbis_encode_frame(), vp6_build_huff_tree(), vp6_huff_cmp(), vp8_filter_common_is4tap(), vp8_filter_common_isnot4tap(), wait_frame(), wma_decode_block(), wma_lsp_to_curve_init(), x8_get_prediction(), xan_wc3_decode_frame(), yae_load_data(), yae_load_frag(), yae_overlap_add(), and ycocg2rgba().
dc2splat
<<(BIT_DEPTH-1))+0) PRED8x8_X(129, (1<<(BIT_DEPTH-1))+1) static void FUNCC(pred8x16_128_dc)(uint8_t *_src, ptrdiff_t stride) { FUNCC(pred8x8_128_dc)(_src, stride); FUNCC(pred8x8_128_dc)(_src+8*stride, stride); } static void FUNCC(pred8x8_left_dc)(uint8_t *_src, ptrdiff_t stride) { int i; int dc0, dc2; pixel4 dc0splat, dc2splat; pixel *src = (pixel*)_src; stride >>= sizeof(pixel)-1; dc0=dc2=0; for(i=0;i<4; i++){ dc0+= src[-1+i*stride]; dc2+= src[-1+(i+4)*stride]; } dc0splat = PIXEL_SPLAT_X4((dc0 + 2)>> dc2splat = PIXEL_SPLAT_X4((dc2 + 2)>>2)
Definition at line 578 of file h264pred_template.c.
Referenced by pred8x16_dc(), and pred8x8_dc().