FFmpeg: libavcodec/hap.c File Reference
hap.c File Reference
Hap utilities.
#include "hap.h"
Functions
int ff_hap_set_chunk_count (HapContext *ctx, int count, int first_in_frame)
av_cold void ff_hap_free_context (HapContext *ctx)
Detailed Description
Hap utilities.
Definition in file hap.c.
Function Documentation
ff_hap_set_chunk_count()
int ff_hap_set_chunk_count (HapContext * ctx, int count, int first_in_frame)
Definition at line 28 of file hap.c.
Referenced by hap_init(), hap_parse_decode_instructions(), and hap_parse_frame_header().
ff_hap_free_context()
av_cold void ff_hap_free_context (HapContext * ctx)
Definition at line 50 of file hap.c.
Referenced by hap_close().