FFmpeg: libavcodec/hap.h File Reference
hap.h File Reference
#include <stdint.h>
#include "libavutil/opt.h"
#include "bytestream.h"
#include "texturedsp.h"
Data Structures
struct HapChunk
struct HapContext
Enumerations
enum HapTextureFormat { HAP_FMT_RGBDXT1 = 0x0B, HAP_FMT_RGBADXT5 = 0x0E, HAP_FMT_YCOCGDXT5 = 0x0F }
enum HapCompressor { HAP_COMP_NONE = 0xA0, HAP_COMP_SNAPPY = 0xB0, HAP_COMP_COMPLEX = 0xC0 }
enum HapSectionType { HAP_ST_DECODE_INSTRUCTIONS = 0x01, HAP_ST_COMPRESSOR_TABLE = 0x02, HAP_ST_SIZE_TABLE = 0x03, HAP_ST_OFFSET_TABLE = 0x04 }
Functions
int ff_hap_set_chunk_count (HapContext *ctx, int count, int first_in_frame)
av_cold void ff_hap_free_context (HapContext *ctx)
Enumeration Type Documentation
HapTextureFormat
enum HapTextureFormat
Enumerator
HAP_FMT_RGBDXT1
HAP_FMT_RGBADXT5
HAP_FMT_YCOCGDXT5
Definition at line 33 of file hap.h.
HapCompressor
enum HapCompressor
Enumerator
HAP_COMP_NONE
HAP_COMP_SNAPPY
HAP_COMP_COMPLEX
Definition at line 39 of file hap.h.
HapSectionType
enum HapSectionType
Enumerator
HAP_ST_DECODE_INSTRUCTIONS
HAP_ST_COMPRESSOR_TABLE
HAP_ST_SIZE_TABLE
HAP_ST_OFFSET_TABLE
Definition at line 45 of file hap.h.
Function Documentation
ff_hap_set_chunk_count()
int ff_hap_set_chunk_count (HapContext * ctx, int count, int first_in_frame)
Definition at line 28 of file hap.c.
Referenced by hap_init(), hap_parse_decode_instructions(), and hap_parse_frame_header().
ff_hap_free_context()
av_cold void ff_hap_free_context (HapContext * ctx)
Definition at line 50 of file hap.c.
Referenced by hap_close().