FFmpeg: libavcodec/hapdec.c File Reference
hapdec.c File Reference
Hap decoder.
#include <stdint.h>
#include "libavutil/imgutils.h"
#include "avcodec.h"
#include "bytestream.h"
#include "hap.h"
#include "internal.h"
#include "snappy.h"
#include "texturedsp.h"
#include "thread.h"
Functions
static int parse_section_header (GetByteContext *gbc, int *section_size, enum HapSectionType *section_type)
static int hap_parse_decode_instructions (HapContext *ctx, int size)
static int hap_can_use_tex_in_place (HapContext *ctx)
static int hap_parse_frame_header (AVCodecContext *avctx)
static int decompress_chunks_thread (AVCodecContext *avctx, void *arg, int chunk_nb, int thread_nb)
static int decompress_texture_thread (AVCodecContext *avctx, void *arg, int slice, int thread_nb)
static int hap_decode (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int hap_init (AVCodecContext *avctx)
static av_cold int hap_close (AVCodecContext *avctx)
Variables
AVCodec ff_hap_decoder
Detailed Description
Hap decoder.
Fourcc: Hap1, Hap5, HapY
https://github.com/Vidvox/hap/blob/master/documentation/HapVideoDRAFT.md
Definition in file hapdec.c.
Function Documentation
parse_section_header()
static int parse_section_header (GetByteContext * gbc, int * section_size, enum HapSectionType * section_type) static
Definition at line 47 of file hapdec.c.
Referenced by hap_parse_decode_instructions(), and hap_parse_frame_header().
hap_parse_decode_instructions()
static int hap_parse_decode_instructions (HapContext * ctx, int size) static
Definition at line 69 of file hapdec.c.
Referenced by hap_parse_frame_header().
hap_can_use_tex_in_place()
static int hap_can_use_tex_in_place (HapContext * ctx) static
Definition at line 138 of file hapdec.c.
Referenced by hap_decode().
hap_parse_frame_header()
static int hap_parse_frame_header (AVCodecContext * avctx) static
Definition at line 151 of file hapdec.c.
Referenced by hap_decode().
decompress_chunks_thread()
static int decompress_chunks_thread (AVCodecContext * avctx, void * arg, int chunk_nb, int thread_nb) static
Definition at line 240 of file hapdec.c.
Referenced by hap_decode().
decompress_texture_thread()
static int decompress_texture_thread (AVCodecContext * avctx, void * arg, int slice, int thread_nb) static
Definition at line 268 of file hapdec.c.
Referenced by hap_decode().
hap_decode()
static int hap_decode (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 305 of file hapdec.c.
hap_init()
static av_cold int hap_init (AVCodecContext * avctx) static
Definition at line 369 of file hapdec.c.
hap_close()
static av_cold int hap_close (AVCodecContext * avctx) static
Definition at line 418 of file hapdec.c.
Variable Documentation
ff_hap_decoder
AVCodec ff_hap_decoder
Initial value:
= {
    .name           = "hap",
    .long_name      = NULL_IF_CONFIG_SMALL("Vidvox Hap"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_HAP,
    .init           = hap_init,
    .decode         = hap_decode,
    .close          = hap_close,
    .priv_data_size = sizeof(HapContext),
    .capabilities   = AV_CODEC_CAP_FRAME_THREADS | AV_CODEC_CAP_SLICE_THREADS |
                      AV_CODEC_CAP_DR1,
    .caps_internal  = FF_CODEC_CAP_INIT_THREADSAFE |
                      FF_CODEC_CAP_INIT_CLEANUP,
}
Definition at line 427 of file hapdec.c.