FFmpeg: libavcodec/hapenc.c File Reference
hapenc.c File Reference
Hap encoder.
#include <stdint.h>
#include "snappy-c.h"
#include "libavutil/frame.h"
#include "libavutil/imgutils.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "bytestream.h"
#include "hap.h"
#include "internal.h"
#include "texturedsp.h"
Macros
#define HAP_MAX_CHUNKS 64
#define OFFSET(x) offsetof(HapContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Enumerations
enum HapHeaderLength { HAP_HDR_SHORT = 4, HAP_HDR_LONG = 8 }
Functions
static int compress_texture (AVCodecContext *avctx, uint8_t *out, int out_length, const AVFrame *f)
static void hap_write_section_header (PutByteContext *pbc, enum HapHeaderLength header_length, int section_length, enum HapSectionType section_type)
static int hap_compress_frame (AVCodecContext *avctx, uint8_t *dst)
static int hap_decode_instructions_length (HapContext *ctx)
static int hap_header_length (HapContext *ctx)
static void hap_write_frame_header (HapContext *ctx, uint8_t *dst, int frame_length)
static int hap_encode (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *frame, int *got_packet)
static av_cold int hap_init (AVCodecContext *avctx)
static av_cold int hap_close (AVCodecContext *avctx)
Variables
static const AVOption options []
static const AVClass hapenc_class
AVCodec ff_hap_encoder
Detailed Description
Hap encoder.
Fourcc: Hap1, Hap5, HapY
https://github.com/Vidvox/hap/blob/master/documentation/HapVideoDRAFT.md
Definition in file hapenc.c.
Macro Definition Documentation
HAP_MAX_CHUNKS
#define HAP_MAX_CHUNKS 64
Definition at line 46 of file hapenc.c.
Referenced by hap_init().
OFFSET
#define OFFSET (x) offsetof(HapContext, x)
Definition at line 331 of file hapenc.c.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 332 of file hapenc.c.
Enumeration Type Documentation
HapHeaderLength
enum HapHeaderLength
Enumerator
HAP_HDR_SHORT
HAP_HDR_LONG
Definition at line 48 of file hapenc.c.
Function Documentation
compress_texture()
static int compress_texture (AVCodecContext * avctx, uint8_t * out, int out_length, const AVFrame * f) static
Definition at line 55 of file hapenc.c.
Referenced by hap_encode().
hap_write_section_header()
static void hap_write_section_header (PutByteContext * pbc, enum HapHeaderLength header_length, int section_length, enum HapSectionType section_type) static
Definition at line 75 of file hapenc.c.
Referenced by hap_write_frame_header().
hap_compress_frame()
static int hap_compress_frame (AVCodecContext * avctx, uint8_t * dst) static
Definition at line 92 of file hapenc.c.
Referenced by hap_encode().
hap_decode_instructions_length()
static int hap_decode_instructions_length (HapContext * ctx) static
Definition at line 140 of file hapenc.c.
Referenced by hap_header_length(), and hap_write_frame_header().
hap_header_length()
static int hap_header_length (HapContext * ctx) static
Definition at line 149 of file hapenc.c.
Referenced by hap_encode().
hap_write_frame_header()
static void hap_write_frame_header (HapContext * ctx, uint8_t * dst, int frame_length) static
Definition at line 162 of file hapenc.c.
Referenced by hap_encode().
hap_encode()
static int hap_encode (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * frame, int * got_packet) static
Definition at line 194 of file hapenc.c.
hap_init()
static av_cold int hap_init (AVCodecContext * avctx) static
Definition at line 236 of file hapenc.c.
hap_close()
static av_cold int hap_close (AVCodecContext * avctx) static
Definition at line 322 of file hapenc.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "format", NULL, OFFSET(opt_tex_fmt), AV_OPT_TYPE_INT, { .i64 = HAP_FMT_RGBDXT1 }, HAP_FMT_RGBDXT1, HAP_FMT_YCOCGDXT5, FLAGS, "format" },
        { "hap",       "Hap 1 (DXT1 textures)", 0, AV_OPT_TYPE_CONST, { .i64 = HAP_FMT_RGBDXT1   }, 0, 0, FLAGS, "format" },
        { "hap_alpha", "Hap Alpha (DXT5 textures)", 0, AV_OPT_TYPE_CONST, { .i64 = HAP_FMT_RGBADXT5  }, 0, 0, FLAGS, "format" },
        { "hap_q",     "Hap Q (DXT5-YCoCg textures)", 0, AV_OPT_TYPE_CONST, { .i64 = HAP_FMT_YCOCGDXT5 }, 0, 0, FLAGS, "format" },
    { "chunks", "chunk count", OFFSET(opt_chunk_count), AV_OPT_TYPE_INT, {.i64 = 1 }, 1, HAP_MAX_CHUNKS, FLAGS, },
    { "compressor", "second-stage compressor", OFFSET(opt_compressor), AV_OPT_TYPE_INT, { .i64 = HAP_COMP_SNAPPY }, HAP_COMP_NONE, HAP_COMP_SNAPPY, FLAGS, "compressor" },
        { "none",       "None", 0, AV_OPT_TYPE_CONST, { .i64 = HAP_COMP_NONE }, 0, 0, FLAGS, "compressor" },
        { "snappy",     "Snappy", 0, AV_OPT_TYPE_CONST, { .i64 = HAP_COMP_SNAPPY }, 0, 0, FLAGS, "compressor" },
    { NULL },
}
Definition at line 333 of file hapenc.c.
hapenc_class
const AVClass hapenc_class static
Initial value:
= {
    .class_name = "Hap encoder",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 345 of file hapenc.c.
ff_hap_encoder
AVCodec ff_hap_encoder
Initial value:
= {
    .name           = "hap",
    .long_name      = NULL_IF_CONFIG_SMALL("Vidvox Hap"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_HAP,
    .priv_data_size = sizeof(HapContext),
    .priv_class     = &hapenc_class,
    .init           = hap_init,
    .encode2        = hap_encode,
    .close          = hap_close,
    .pix_fmts       = (const enum AVPixelFormat[]) {
        AV_PIX_FMT_RGBA, AV_PIX_FMT_NONE,
    },
    .caps_internal  = FF_CODEC_CAP_INIT_THREADSAFE |
                      FF_CODEC_CAP_INIT_CLEANUP,
}
Definition at line 352 of file hapenc.c.