FFmpeg: libavcodec/mips/hevc_mc_biw_msa.c File Reference
hevc_mc_biw_msa.c File Reference
#include "libavutil/mips/generic_macros_msa.h"
#include "libavcodec/mips/hevcdsp_mips.h"
#include "libavcodec/mips/hevc_macros_msa.h"
Macros
#define HEVC_BIW_RND_CLIP2(in0, in1, vec0, vec1, wgt, rnd, offset, out0_r, out1_r, out0_l, out1_l)
#define HEVC_BIW_RND_CLIP4(in0, in1, in2, in3, vec0, vec1, vec2, vec3, wgt, rnd, offset, out0_r, out1_r, out2_r, out3_r, out0_l, out1_l, out2_l, out3_l)
#define HEVC_BI_RND_CLIP2(in0, in1, vec0, vec1, rnd_val, out0, out1)
#define HEVC_BI_RND_CLIP4(in0, in1, in2, in3, vec0, vec1, vec2, vec3, rnd_val, out0, out1, out2, out3)
#define BI_W_MC_COPY(WIDTH)
#define BI_W_MC(PEL, DIR, WIDTH, TAP, DIR1, FILT_DIR)
#define BI_W_MC_HV(PEL, DIR, WIDTH, TAP, DIR1)
Functions
static void hevc_biwgt_copy_4w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_biwgt_copy_6w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_biwgt_copy_8w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_biwgt_copy_12w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_biwgt_copy_16multx4mult_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val, int32_t width)
static void hevc_biwgt_copy_16w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_biwgt_copy_24w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_biwgt_copy_32w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_biwgt_copy_48w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_biwgt_copy_64w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hz_biwgt_8t_4w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hz_biwgt_8t_8w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hz_biwgt_8t_12w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hz_biwgt_8t_16w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hz_biwgt_8t_24w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hz_biwgt_8t_32w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hz_biwgt_8t_48w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hz_biwgt_8t_64w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_vt_biwgt_8t_4w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_vt_biwgt_8t_8w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_vt_biwgt_8t_12w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_vt_biwgt_8t_16multx2mult_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val, int32_t width)
static void hevc_vt_biwgt_8t_16w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_vt_biwgt_8t_24w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_vt_biwgt_8t_32w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_vt_biwgt_8t_48w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_vt_biwgt_8t_64w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hv_biwgt_8t_4w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hv_biwgt_8t_8multx2mult_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val, int32_t width)
static void hevc_hv_biwgt_8t_8w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hv_biwgt_8t_12w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hv_biwgt_8t_16w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hv_biwgt_8t_24w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hv_biwgt_8t_32w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hv_biwgt_8t_48w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hv_biwgt_8t_64w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hz_biwgt_4t_4x2_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hz_biwgt_4t_4x4_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hz_biwgt_4t_4x8multiple_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hz_biwgt_4t_4w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hz_biwgt_4t_6w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hz_biwgt_4t_8x2_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hz_biwgt_4t_8x6_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hz_biwgt_4t_8x4multiple_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hz_biwgt_4t_8w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hz_biwgt_4t_12w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hz_biwgt_4t_16w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hz_biwgt_4t_24w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hz_biwgt_4t_32w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_vt_biwgt_4t_4x2_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_vt_biwgt_4t_4x4_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_vt_biwgt_4t_4x8multiple_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_vt_biwgt_4t_4w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_vt_biwgt_4t_6w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_vt_biwgt_4t_8x2_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_vt_biwgt_4t_8x6_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_vt_biwgt_4t_8x4multiple_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_vt_biwgt_4t_8w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_vt_biwgt_4t_12w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_vt_biwgt_4t_16w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_vt_biwgt_4t_24w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_vt_biwgt_4t_32w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hv_biwgt_4t_4x2_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hv_biwgt_4t_4x4_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hv_biwgt_4t_4multx8mult_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hv_biwgt_4t_4w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hv_biwgt_4t_6w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hv_biwgt_4t_8x2_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hv_biwgt_4t_8x6_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hv_biwgt_4t_8multx4mult_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val, int32_t width)
static void hevc_hv_biwgt_4t_8w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hv_biwgt_4t_12w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hv_biwgt_4t_16w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hv_biwgt_4t_24w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
static void hevc_hv_biwgt_4t_32w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val)
BI_W_MC_COPY (4)
BI_W_MC_COPY (6)
BI_W_MC_COPY (8)
BI_W_MC_COPY (12)
BI_W_MC_COPY (16)
BI_W_MC_COPY (24)
BI_W_MC_COPY (32)
BI_W_MC_COPY (48)
BI_W_MC_COPY (64)
BI_W_MC (qpel, h, 4, 8, hz, mx)
BI_W_MC (qpel, h, 8, 8, hz, mx)
BI_W_MC (qpel, h, 12, 8, hz, mx)
BI_W_MC (qpel, h, 16, 8, hz, mx)
BI_W_MC (qpel, h, 24, 8, hz, mx)
BI_W_MC (qpel, h, 32, 8, hz, mx)
BI_W_MC (qpel, h, 48, 8, hz, mx)
BI_W_MC (qpel, h, 64, 8, hz, mx)
BI_W_MC (qpel, v, 4, 8, vt, my)
BI_W_MC (qpel, v, 8, 8, vt, my)
BI_W_MC (qpel, v, 12, 8, vt, my)
BI_W_MC (qpel, v, 16, 8, vt, my)
BI_W_MC (qpel, v, 24, 8, vt, my)
BI_W_MC (qpel, v, 32, 8, vt, my)
BI_W_MC (qpel, v, 48, 8, vt, my)
BI_W_MC (qpel, v, 64, 8, vt, my)
BI_W_MC (epel, h, 4, 4, hz, mx)
BI_W_MC (epel, h, 8, 4, hz, mx)
BI_W_MC (epel, h, 6, 4, hz, mx)
BI_W_MC (epel, h, 12, 4, hz, mx)
BI_W_MC (epel, h, 16, 4, hz, mx)
BI_W_MC (epel, h, 24, 4, hz, mx)
BI_W_MC (epel, h, 32, 4, hz, mx)
BI_W_MC (epel, v, 4, 4, vt, my)
BI_W_MC (epel, v, 8, 4, vt, my)
BI_W_MC (epel, v, 6, 4, vt, my)
BI_W_MC (epel, v, 12, 4, vt, my)
BI_W_MC (epel, v, 16, 4, vt, my)
BI_W_MC (epel, v, 24, 4, vt, my)
BI_W_MC (epel, v, 32, 4, vt, my)
BI_W_MC_HV (qpel, hv, 4, 8, hv)
BI_W_MC_HV (qpel, hv, 8, 8, hv)
BI_W_MC_HV (qpel, hv, 12, 8, hv)
BI_W_MC_HV (qpel, hv, 16, 8, hv)
BI_W_MC_HV (qpel, hv, 24, 8, hv)
BI_W_MC_HV (qpel, hv, 32, 8, hv)
BI_W_MC_HV (qpel, hv, 48, 8, hv)
BI_W_MC_HV (qpel, hv, 64, 8, hv)
BI_W_MC_HV (epel, hv, 4, 4, hv)
BI_W_MC_HV (epel, hv, 8, 4, hv)
BI_W_MC_HV (epel, hv, 6, 4, hv)
BI_W_MC_HV (epel, hv, 12, 4, hv)
BI_W_MC_HV (epel, hv, 16, 4, hv)
BI_W_MC_HV (epel, hv, 24, 4, hv)
BI_W_MC_HV (epel, hv, 32, 4, hv)
Macro Definition Documentation
HEVC_BIW_RND_CLIP2
#define HEVC_BIW_RND_CLIP2 (in0, in1, vec0, vec1, wgt, rnd, offset, out0_r, out1_r, out0_l, out1_l)
Value:
{                                                                   \
    ILVR_H2_SW(in0, vec0, in1, vec1, out0_r, out1_r);               \
    ILVL_H2_SW(in0, vec0, in1, vec1, out0_l, out1_l);               \
                                                                    \
    out0_r = __msa_dpadd_s_w(offset, (v8i16) out0_r, (v8i16) wgt);  \
    out1_r = __msa_dpadd_s_w(offset, (v8i16) out1_r, (v8i16) wgt);  \
    out0_l = __msa_dpadd_s_w(offset, (v8i16) out0_l, (v8i16) wgt);  \
    out1_l = __msa_dpadd_s_w(offset, (v8i16) out1_l, (v8i16) wgt);  \
                                                                    \
    SRAR_W4_SW(out0_r, out1_r, out0_l, out1_l, rnd);                \
                                                                    \
    out0_r = CLIP_SW_0_255(out0_r);                                 \
    out1_r = CLIP_SW_0_255(out1_r);                                 \
    out0_l = CLIP_SW_0_255(out0_l);                                 \
    out1_l = CLIP_SW_0_255(out1_l);                                 \
}
Definition at line 25 of file hevc_mc_biw_msa.c.
Referenced by hevc_biwgt_copy_12w_msa(), hevc_biwgt_copy_4w_msa(), hevc_biwgt_copy_8w_msa(), hevc_hv_biwgt_4t_4x4_msa(), hevc_hv_biwgt_4t_8x2_msa(), hevc_hv_biwgt_4t_8x6_msa(), hevc_hz_biwgt_4t_12w_msa(), hevc_hz_biwgt_4t_24w_msa(), hevc_hz_biwgt_4t_4x4_msa(), hevc_hz_biwgt_4t_8x2_msa(), hevc_hz_biwgt_4t_8x6_msa(), hevc_hz_biwgt_8t_24w_msa(), hevc_hz_biwgt_8t_48w_msa(), hevc_hz_biwgt_8t_4w_msa(), hevc_vt_biwgt_4t_12w_msa(), hevc_vt_biwgt_4t_24w_msa(), hevc_vt_biwgt_4t_4x4_msa(), hevc_vt_biwgt_4t_8x2_msa(), hevc_vt_biwgt_4t_8x6_msa(), and hevc_vt_biwgt_8t_12w_msa().
HEVC_BIW_RND_CLIP4
#define HEVC_BIW_RND_CLIP4 (in0, in1, in2, in3, vec0, vec1, vec2, vec3, wgt, rnd, offset, out0_r, out1_r, out2_r, out3_r, out0_l, out1_l, out2_l, out3_l)
Value:
{                                                                       \
    HEVC_BIW_RND_CLIP2(in0, in1, vec0, vec1, wgt, rnd, offset,          \
                       out0_r, out1_r, out0_l, out1_l)                  \
    HEVC_BIW_RND_CLIP2(in2, in3, vec2, vec3, wgt, rnd, offset,          \
                       out2_r, out3_r, out2_l, out3_l)                  \
}
Definition at line 44 of file hevc_mc_biw_msa.c.
Referenced by hevc_biwgt_copy_12w_msa(), hevc_biwgt_copy_16multx4mult_msa(), hevc_biwgt_copy_4w_msa(), hevc_biwgt_copy_6w_msa(), hevc_biwgt_copy_8w_msa(), hevc_hv_biwgt_4t_4multx8mult_msa(), hevc_hv_biwgt_4t_6w_msa(), hevc_hv_biwgt_4t_8multx4mult_msa(), hevc_hv_biwgt_4t_8x6_msa(), hevc_hz_biwgt_4t_12w_msa(), hevc_hz_biwgt_4t_16w_msa(), hevc_hz_biwgt_4t_24w_msa(), hevc_hz_biwgt_4t_32w_msa(), hevc_hz_biwgt_4t_4x8multiple_msa(), hevc_hz_biwgt_4t_6w_msa(), hevc_hz_biwgt_4t_8x4multiple_msa(), hevc_hz_biwgt_4t_8x6_msa(), hevc_hz_biwgt_8t_16w_msa(), hevc_hz_biwgt_8t_32w_msa(), hevc_hz_biwgt_8t_64w_msa(), hevc_hz_biwgt_8t_8w_msa(), hevc_vt_biwgt_4t_12w_msa(), hevc_vt_biwgt_4t_16w_msa(), hevc_vt_biwgt_4t_24w_msa(), hevc_vt_biwgt_4t_32w_msa(), hevc_vt_biwgt_4t_4x8multiple_msa(), hevc_vt_biwgt_4t_6w_msa(), hevc_vt_biwgt_4t_8x4multiple_msa(), hevc_vt_biwgt_4t_8x6_msa(), hevc_vt_biwgt_8t_16multx2mult_msa(), hevc_vt_biwgt_8t_4w_msa(), and hevc_vt_biwgt_8t_8w_msa().
HEVC_BI_RND_CLIP2
#define HEVC_BI_RND_CLIP2 (in0, in1, vec0, vec1, rnd_val, out0, out1)
Value:
{                                                                     \
    ADDS_SH2_SH(vec0, in0, vec1, in1, out0, out1);                    \
    SRARI_H2_SH(out0, out1, rnd_val);                                 \
    CLIP_SH2_0_255(out0, out1);                                       \
}
Definition at line 55 of file hevc_mc_biw_msa.c.
HEVC_BI_RND_CLIP4
#define HEVC_BI_RND_CLIP4 (in0, in1, in2, in3, vec0, vec1, vec2, vec3, rnd_val, out0, out1, out2, out3)
Value:
{                                                                  \
    HEVC_BI_RND_CLIP2(in0, in1, vec0, vec1, rnd_val, out0, out1);  \
    HEVC_BI_RND_CLIP2(in2, in3, vec2, vec3, rnd_val, out2, out3);  \
}
Definition at line 62 of file hevc_mc_biw_msa.c.
BI_W_MC_COPY
#define BI_W_MC_COPY (WIDTH)
Value:
void ff_hevc_put_hevc_bi_w_pel_pixels##WIDTH##_8_msa(uint8_t *dst,           \
                                                     ptrdiff_t dst_stride,   \
                                                     uint8_t *src,           \
                                                     ptrdiff_t src_stride,   \
                                                     int16_t *src_16bit,     \
                                                     int height,             \
                                                     int denom,              \
                                                     int weight0,            \
                                                     int weight1,            \
                                                     int offset0,            \
                                                     int offset1,            \
                                                     intptr_t mx,            \
                                                     intptr_t my,            \
                                                     int width)              \
{                                                                            \
    int shift = 14 + 1 - 8;                                                  \
    int log2Wd = denom + shift - 1;                                          \
                                                                             \
    hevc_biwgt_copy_##WIDTH##w_msa(src, src_stride, src_16bit, MAX_PB_SIZE,  \
                                   dst, dst_stride, height,                  \
                                   weight0, weight1, offset0,                \
                                   offset1, log2Wd);                         \
}
Definition at line 5419 of file hevc_mc_biw_msa.c.
BI_W_MC
#define BI_W_MC (PEL, DIR, WIDTH, TAP, DIR1, FILT_DIR)
Value:
void ff_hevc_put_hevc_bi_w_##PEL##_##DIR##WIDTH##_8_msa(uint8_t *dst,          \
                                                          ptrdiff_t            \
                                                          dst_stride,          \
                                                          uint8_t *src,        \
                                                          ptrdiff_t            \
                                                          src_stride,          \
                                                          int16_t *src_16bit,  \
                                                          int height,          \
                                                          int denom,           \
                                                          int weight0,         \
                                                          int weight1,         \
                                                          int offset0,         \
                                                          int offset1,         \
                                                          intptr_t mx,         \
                                                          intptr_t my,         \
                                                          int width)           \
{                                                                              \
    const int8_t *filter = ff_hevc_##PEL##_filters[FILT_DIR - 1];              \
                                                                               \
    int shift = 14 + 1 - 8;                                                    \
    int log2Wd = denom + shift - 1;                                            \
                                                                               \
    hevc_##DIR1##_biwgt_##TAP##t_##WIDTH##w_msa(src, src_stride,               \
                                                src_16bit, MAX_PB_SIZE,        \
                                                dst, dst_stride,               \
                                                filter, height,                \
                                                weight0, weight1, offset0,     \
                                                offset1, log2Wd);              \
}
Definition at line 5456 of file hevc_mc_biw_msa.c.
BI_W_MC_HV
#define BI_W_MC_HV (PEL, DIR, WIDTH, TAP, DIR1)
Value:
void ff_hevc_put_hevc_bi_w_##PEL##_##DIR##WIDTH##_8_msa(uint8_t *dst,          \
                                                          ptrdiff_t            \
                                                          dst_stride,          \
                                                          uint8_t *src,        \
                                                          ptrdiff_t            \
                                                          src_stride,          \
                                                          int16_t *src_16bit,  \
                                                          int height,          \
                                                          int denom,           \
                                                          int weight0,         \
                                                          int weight1,         \
                                                          int offset0,         \
                                                          int offset1,         \
                                                          intptr_t mx,         \
                                                          intptr_t my,         \
                                                          int width)           \
{                                                                              \
    const int8_t *filter_x = ff_hevc_##PEL##_filters[mx - 1];                  \
    const int8_t *filter_y = ff_hevc_##PEL##_filters[my - 1];                  \
                                                                               \
    int shift = 14 + 1 - 8;                                                    \
    int log2Wd = denom + shift - 1;                                            \
                                                                               \
    hevc_##DIR1##_biwgt_##TAP##t_##WIDTH##w_msa(src, src_stride,               \
                                                src_16bit, MAX_PB_SIZE,        \
                                                dst, dst_stride,               \
                                                filter_x, filter_y,            \
                                                height, weight0, weight1,      \
                                                offset0, offset1, log2Wd);     \
}
Definition at line 5523 of file hevc_mc_biw_msa.c.
Function Documentation
hevc_biwgt_copy_4w_msa()
static void hevc_biwgt_copy_4w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 70 of file hevc_mc_biw_msa.c.
hevc_biwgt_copy_6w_msa()
static void hevc_biwgt_copy_6w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 175 of file hevc_mc_biw_msa.c.
hevc_biwgt_copy_8w_msa()
static void hevc_biwgt_copy_8w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 227 of file hevc_mc_biw_msa.c.
Referenced by hevc_biwgt_copy_24w_msa().
hevc_biwgt_copy_12w_msa()
static void hevc_biwgt_copy_12w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 332 of file hevc_mc_biw_msa.c.
hevc_biwgt_copy_16multx4mult_msa()
static void hevc_biwgt_copy_16multx4mult_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val, int32_t width) static
Definition at line 398 of file hevc_mc_biw_msa.c.
Referenced by hevc_biwgt_copy_16w_msa(), hevc_biwgt_copy_24w_msa(), hevc_biwgt_copy_32w_msa(), hevc_biwgt_copy_48w_msa(), and hevc_biwgt_copy_64w_msa().
hevc_biwgt_copy_16w_msa()
static void hevc_biwgt_copy_16w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 482 of file hevc_mc_biw_msa.c.
hevc_biwgt_copy_24w_msa()
static void hevc_biwgt_copy_24w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 501 of file hevc_mc_biw_msa.c.
hevc_biwgt_copy_32w_msa()
static void hevc_biwgt_copy_32w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 524 of file hevc_mc_biw_msa.c.
hevc_biwgt_copy_48w_msa()
static void hevc_biwgt_copy_48w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 543 of file hevc_mc_biw_msa.c.
hevc_biwgt_copy_64w_msa()
static void hevc_biwgt_copy_64w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 562 of file hevc_mc_biw_msa.c.
hevc_hz_biwgt_8t_4w_msa()
static void hevc_hz_biwgt_8t_4w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 581 of file hevc_mc_biw_msa.c.
Referenced by hevc_hz_biwgt_8t_12w_msa().
hevc_hz_biwgt_8t_8w_msa()
static void hevc_hz_biwgt_8t_8w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 655 of file hevc_mc_biw_msa.c.
Referenced by hevc_hz_biwgt_8t_12w_msa().
hevc_hz_biwgt_8t_12w_msa()
static void hevc_hz_biwgt_8t_12w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 741 of file hevc_mc_biw_msa.c.
hevc_hz_biwgt_8t_16w_msa()
static void hevc_hz_biwgt_8t_16w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 763 of file hevc_mc_biw_msa.c.
hevc_hz_biwgt_8t_24w_msa()
static void hevc_hz_biwgt_8t_24w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 853 of file hevc_mc_biw_msa.c.
hevc_hz_biwgt_8t_32w_msa()
static void hevc_hz_biwgt_8t_32w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 949 of file hevc_mc_biw_msa.c.
hevc_hz_biwgt_8t_48w_msa()
static void hevc_hz_biwgt_8t_48w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 1041 of file hevc_mc_biw_msa.c.
hevc_hz_biwgt_8t_64w_msa()
static void hevc_hz_biwgt_8t_64w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 1176 of file hevc_mc_biw_msa.c.
hevc_vt_biwgt_8t_4w_msa()
static void hevc_vt_biwgt_8t_4w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 1281 of file hevc_mc_biw_msa.c.
hevc_vt_biwgt_8t_8w_msa()
static void hevc_vt_biwgt_8t_8w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 1385 of file hevc_mc_biw_msa.c.
Referenced by hevc_vt_biwgt_8t_24w_msa().
hevc_vt_biwgt_8t_12w_msa()
static void hevc_vt_biwgt_8t_12w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 1478 of file hevc_mc_biw_msa.c.
hevc_vt_biwgt_8t_16multx2mult_msa()
static void hevc_vt_biwgt_8t_16multx2mult_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val, int32_t width) static
Definition at line 1589 of file hevc_mc_biw_msa.c.
Referenced by hevc_vt_biwgt_8t_16w_msa(), hevc_vt_biwgt_8t_24w_msa(), hevc_vt_biwgt_8t_32w_msa(), hevc_vt_biwgt_8t_48w_msa(), and hevc_vt_biwgt_8t_64w_msa().
hevc_vt_biwgt_8t_16w_msa()
static void hevc_vt_biwgt_8t_16w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 1709 of file hevc_mc_biw_msa.c.
hevc_vt_biwgt_8t_24w_msa()
static void hevc_vt_biwgt_8t_24w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 1730 of file hevc_mc_biw_msa.c.
hevc_vt_biwgt_8t_32w_msa()
static void hevc_vt_biwgt_8t_32w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 1755 of file hevc_mc_biw_msa.c.
hevc_vt_biwgt_8t_48w_msa()
static void hevc_vt_biwgt_8t_48w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 1776 of file hevc_mc_biw_msa.c.
hevc_vt_biwgt_8t_64w_msa()
static void hevc_vt_biwgt_8t_64w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 1797 of file hevc_mc_biw_msa.c.
hevc_hv_biwgt_8t_4w_msa()
static void hevc_hv_biwgt_8t_4w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 1818 of file hevc_mc_biw_msa.c.
Referenced by hevc_hv_biwgt_8t_12w_msa().
hevc_hv_biwgt_8t_8multx2mult_msa()
static void hevc_hv_biwgt_8t_8multx2mult_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val, int32_t width) static
Definition at line 1956 of file hevc_mc_biw_msa.c.
Referenced by hevc_hv_biwgt_8t_12w_msa(), hevc_hv_biwgt_8t_16w_msa(), hevc_hv_biwgt_8t_24w_msa(), hevc_hv_biwgt_8t_32w_msa(), hevc_hv_biwgt_8t_48w_msa(), hevc_hv_biwgt_8t_64w_msa(), and hevc_hv_biwgt_8t_8w_msa().
hevc_hv_biwgt_8t_8w_msa()
static void hevc_hv_biwgt_8t_8w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 2165 of file hevc_mc_biw_msa.c.
hevc_hv_biwgt_8t_12w_msa()
static void hevc_hv_biwgt_8t_12w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 2187 of file hevc_mc_biw_msa.c.
hevc_hv_biwgt_8t_16w_msa()
static void hevc_hv_biwgt_8t_16w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 2214 of file hevc_mc_biw_msa.c.
hevc_hv_biwgt_8t_24w_msa()
static void hevc_hv_biwgt_8t_24w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 2236 of file hevc_mc_biw_msa.c.
hevc_hv_biwgt_8t_32w_msa()
static void hevc_hv_biwgt_8t_32w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 2258 of file hevc_mc_biw_msa.c.
hevc_hv_biwgt_8t_48w_msa()
static void hevc_hv_biwgt_8t_48w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 2280 of file hevc_mc_biw_msa.c.
hevc_hv_biwgt_8t_64w_msa()
static void hevc_hv_biwgt_8t_64w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 2302 of file hevc_mc_biw_msa.c.
hevc_hz_biwgt_4t_4x2_msa()
static void hevc_hz_biwgt_4t_4x2_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 2324 of file hevc_mc_biw_msa.c.
Referenced by hevc_hz_biwgt_4t_4w_msa().
hevc_hz_biwgt_4t_4x4_msa()
static void hevc_hz_biwgt_4t_4x4_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 2386 of file hevc_mc_biw_msa.c.
Referenced by hevc_hz_biwgt_4t_4w_msa().
hevc_hz_biwgt_4t_4x8multiple_msa()
static void hevc_hz_biwgt_4t_4x8multiple_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 2449 of file hevc_mc_biw_msa.c.
Referenced by hevc_hz_biwgt_4t_4w_msa().
hevc_hz_biwgt_4t_4w_msa()
static void hevc_hz_biwgt_4t_4w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 2530 of file hevc_mc_biw_msa.c.
hevc_hz_biwgt_4t_6w_msa()
static void hevc_hz_biwgt_4t_6w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 2561 of file hevc_mc_biw_msa.c.
hevc_hz_biwgt_4t_8x2_msa()
static void hevc_hz_biwgt_4t_8x2_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 2638 of file hevc_mc_biw_msa.c.
Referenced by hevc_hz_biwgt_4t_8w_msa().
hevc_hz_biwgt_4t_8x6_msa()
static void hevc_hz_biwgt_4t_8x6_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 2697 of file hevc_mc_biw_msa.c.
Referenced by hevc_hz_biwgt_4t_8w_msa().
hevc_hz_biwgt_4t_8x4multiple_msa()
static void hevc_hz_biwgt_4t_8x4multiple_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 2782 of file hevc_mc_biw_msa.c.
Referenced by hevc_hz_biwgt_4t_8w_msa().
hevc_hz_biwgt_4t_8w_msa()
static void hevc_hz_biwgt_4t_8w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 2858 of file hevc_mc_biw_msa.c.
hevc_hz_biwgt_4t_12w_msa()
static void hevc_hz_biwgt_4t_12w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 2889 of file hevc_mc_biw_msa.c.
hevc_hz_biwgt_4t_16w_msa()
static void hevc_hz_biwgt_4t_16w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 2984 of file hevc_mc_biw_msa.c.
hevc_hz_biwgt_4t_24w_msa()
static void hevc_hz_biwgt_4t_24w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 3085 of file hevc_mc_biw_msa.c.
hevc_hz_biwgt_4t_32w_msa()
static void hevc_hz_biwgt_4t_32w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 3181 of file hevc_mc_biw_msa.c.
hevc_vt_biwgt_4t_4x2_msa()
static void hevc_vt_biwgt_4t_4x2_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 3260 of file hevc_mc_biw_msa.c.
Referenced by hevc_vt_biwgt_4t_4w_msa().
hevc_vt_biwgt_4t_4x4_msa()
static void hevc_vt_biwgt_4t_4x4_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 3327 of file hevc_mc_biw_msa.c.
Referenced by hevc_vt_biwgt_4t_4w_msa().
hevc_vt_biwgt_4t_4x8multiple_msa()
static void hevc_vt_biwgt_4t_4x8multiple_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 3397 of file hevc_mc_biw_msa.c.
Referenced by hevc_vt_biwgt_4t_4w_msa().
hevc_vt_biwgt_4t_4w_msa()
static void hevc_vt_biwgt_4t_4w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 3490 of file hevc_mc_biw_msa.c.
hevc_vt_biwgt_4t_6w_msa()
static void hevc_vt_biwgt_4t_6w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 3521 of file hevc_mc_biw_msa.c.
hevc_vt_biwgt_4t_8x2_msa()
static void hevc_vt_biwgt_4t_8x2_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 3601 of file hevc_mc_biw_msa.c.
Referenced by hevc_vt_biwgt_4t_8w_msa().
hevc_vt_biwgt_4t_8x6_msa()
static void hevc_vt_biwgt_4t_8x6_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 3661 of file hevc_mc_biw_msa.c.
Referenced by hevc_vt_biwgt_4t_8w_msa().
hevc_vt_biwgt_4t_8x4multiple_msa()
static void hevc_vt_biwgt_4t_8x4multiple_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 3743 of file hevc_mc_biw_msa.c.
Referenced by hevc_vt_biwgt_4t_8w_msa().
hevc_vt_biwgt_4t_8w_msa()
static void hevc_vt_biwgt_4t_8w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 3823 of file hevc_mc_biw_msa.c.
hevc_vt_biwgt_4t_12w_msa()
static void hevc_vt_biwgt_4t_12w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 3854 of file hevc_mc_biw_msa.c.
hevc_vt_biwgt_4t_16w_msa()
static void hevc_vt_biwgt_4t_16w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 3955 of file hevc_mc_biw_msa.c.
hevc_vt_biwgt_4t_24w_msa()
static void hevc_vt_biwgt_4t_24w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 4061 of file hevc_mc_biw_msa.c.
hevc_vt_biwgt_4t_32w_msa()
static void hevc_vt_biwgt_4t_32w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 4215 of file hevc_mc_biw_msa.c.
hevc_hv_biwgt_4t_4x2_msa()
static void hevc_hv_biwgt_4t_4x2_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 4347 of file hevc_mc_biw_msa.c.
Referenced by hevc_hv_biwgt_4t_4w_msa().
hevc_hv_biwgt_4t_4x4_msa()
static void hevc_hv_biwgt_4t_4x4_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 4445 of file hevc_mc_biw_msa.c.
Referenced by hevc_hv_biwgt_4t_4w_msa().
hevc_hv_biwgt_4t_4multx8mult_msa()
static void hevc_hv_biwgt_4t_4multx8mult_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 4555 of file hevc_mc_biw_msa.c.
Referenced by hevc_hv_biwgt_4t_4w_msa().
hevc_hv_biwgt_4t_4w_msa()
static void hevc_hv_biwgt_4t_4w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 4702 of file hevc_mc_biw_msa.c.
Referenced by hevc_hv_biwgt_4t_12w_msa().
hevc_hv_biwgt_4t_6w_msa()
static void hevc_hv_biwgt_4t_6w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 4736 of file hevc_mc_biw_msa.c.
hevc_hv_biwgt_4t_8x2_msa()
static void hevc_hv_biwgt_4t_8x2_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 4868 of file hevc_mc_biw_msa.c.
Referenced by hevc_hv_biwgt_4t_8w_msa().
hevc_hv_biwgt_4t_8x6_msa()
static void hevc_hv_biwgt_4t_8x6_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 4973 of file hevc_mc_biw_msa.c.
Referenced by hevc_hv_biwgt_4t_8w_msa().
hevc_hv_biwgt_4t_8multx4mult_msa()
static void hevc_hv_biwgt_4t_8multx4mult_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val, int32_t width) static
Definition at line 5143 of file hevc_mc_biw_msa.c.
Referenced by hevc_hv_biwgt_4t_12w_msa(), hevc_hv_biwgt_4t_16w_msa(), hevc_hv_biwgt_4t_24w_msa(), hevc_hv_biwgt_4t_32w_msa(), and hevc_hv_biwgt_4t_8w_msa().
hevc_hv_biwgt_4t_8w_msa()
static void hevc_hv_biwgt_4t_8w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 5292 of file hevc_mc_biw_msa.c.
hevc_hv_biwgt_4t_12w_msa()
static void hevc_hv_biwgt_4t_12w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 5326 of file hevc_mc_biw_msa.c.
hevc_hv_biwgt_4t_16w_msa()
static void hevc_hv_biwgt_4t_16w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 5353 of file hevc_mc_biw_msa.c.
hevc_hv_biwgt_4t_24w_msa()
static void hevc_hv_biwgt_4t_24w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 5375 of file hevc_mc_biw_msa.c.
hevc_hv_biwgt_4t_32w_msa()
static void hevc_hv_biwgt_4t_32w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight0, int32_t weight1, int32_t offset0, int32_t offset1, int32_t rnd_val) static
Definition at line 5397 of file hevc_mc_biw_msa.c.
BI_W_MC_COPY() [1/9]
BI_W_MC_COPY (4)
BI_W_MC_COPY() [2/9]
BI_W_MC_COPY (6)
BI_W_MC_COPY() [3/9]
BI_W_MC_COPY (8)
BI_W_MC_COPY() [4/9]
BI_W_MC_COPY (12)
BI_W_MC_COPY() [5/9]
BI_W_MC_COPY (16)
BI_W_MC_COPY() [6/9]
BI_W_MC_COPY (24)
BI_W_MC_COPY() [7/9]
BI_W_MC_COPY (32)
BI_W_MC_COPY() [8/9]
BI_W_MC_COPY (48)
BI_W_MC_COPY() [9/9]
BI_W_MC_COPY (64)
BI_W_MC() [1/30]
BI_W_MC (qpel , h , 4 , 8 , hz , mx)
BI_W_MC() [2/30]
BI_W_MC (qpel , h , 8 , 8 , hz , mx)
BI_W_MC() [3/30]
BI_W_MC (qpel , h , 12 , 8 , hz , mx)
BI_W_MC() [4/30]
BI_W_MC (qpel , h , 16 , 8 , hz , mx)
BI_W_MC() [5/30]
BI_W_MC (qpel , h , 24 , 8 , hz , mx)
BI_W_MC() [6/30]
BI_W_MC (qpel , h , 32 , 8 , hz , mx)
BI_W_MC() [7/30]
BI_W_MC (qpel , h , 48 , 8 , hz , mx)
BI_W_MC() [8/30]
BI_W_MC (qpel , h , 64 , 8 , hz , mx)
BI_W_MC() [9/30]
BI_W_MC (qpel , v , 4 , 8 , vt , my)
BI_W_MC() [10/30]
BI_W_MC (qpel , v , 8 , 8 , vt , my)
BI_W_MC() [11/30]
BI_W_MC (qpel , v , 12 , 8 , vt , my)
BI_W_MC() [12/30]
BI_W_MC (qpel , v , 16 , 8 , vt , my)
BI_W_MC() [13/30]
BI_W_MC (qpel , v , 24 , 8 , vt , my)
BI_W_MC() [14/30]
BI_W_MC (qpel , v , 32 , 8 , vt , my)
BI_W_MC() [15/30]
BI_W_MC (qpel , v , 48 , 8 , vt , my)
BI_W_MC() [16/30]
BI_W_MC (qpel , v , 64 , 8 , vt , my)
BI_W_MC() [17/30]
BI_W_MC (epel , h , 4 , 4 , hz , mx)
BI_W_MC() [18/30]
BI_W_MC (epel , h , 8 , 4 , hz , mx)
BI_W_MC() [19/30]
BI_W_MC (epel , h , 6 , 4 , hz , mx)
BI_W_MC() [20/30]
BI_W_MC (epel , h , 12 , 4 , hz , mx)
BI_W_MC() [21/30]
BI_W_MC (epel , h , 16 , 4 , hz , mx)
BI_W_MC() [22/30]
BI_W_MC (epel , h , 24 , 4 , hz , mx)
BI_W_MC() [23/30]
BI_W_MC (epel , h , 32 , 4 , hz , mx)
BI_W_MC() [24/30]
BI_W_MC (epel , v , 4 , 4 , vt , my)
BI_W_MC() [25/30]
BI_W_MC (epel , v , 8 , 4 , vt , my)
BI_W_MC() [26/30]
BI_W_MC (epel , v , 6 , 4 , vt , my)
BI_W_MC() [27/30]
BI_W_MC (epel , v , 12 , 4 , vt , my)
BI_W_MC() [28/30]
BI_W_MC (epel , v , 16 , 4 , vt , my)
BI_W_MC() [29/30]
BI_W_MC (epel , v , 24 , 4 , vt , my)
BI_W_MC() [30/30]
BI_W_MC (epel , v , 32 , 4 , vt , my)
BI_W_MC_HV() [1/15]
BI_W_MC_HV (qpel , hv , 4 , 8 , hv)
BI_W_MC_HV() [2/15]
BI_W_MC_HV (qpel , hv , 8 , 8 , hv)
BI_W_MC_HV() [3/15]
BI_W_MC_HV (qpel , hv , 12 , 8 , hv)
BI_W_MC_HV() [4/15]
BI_W_MC_HV (qpel , hv , 16 , 8 , hv)
BI_W_MC_HV() [5/15]
BI_W_MC_HV (qpel , hv , 24 , 8 , hv)
BI_W_MC_HV() [6/15]
BI_W_MC_HV (qpel , hv , 32 , 8 , hv)
BI_W_MC_HV() [7/15]
BI_W_MC_HV (qpel , hv , 48 , 8 , hv)
BI_W_MC_HV() [8/15]
BI_W_MC_HV (qpel , hv , 64 , 8 , hv)
BI_W_MC_HV() [9/15]
BI_W_MC_HV (epel , hv , 4 , 4 , hv)
BI_W_MC_HV() [10/15]
BI_W_MC_HV (epel , hv , 8 , 4 , hv)
BI_W_MC_HV() [11/15]
BI_W_MC_HV (epel , hv , 6 , 4 , hv)
BI_W_MC_HV() [12/15]
BI_W_MC_HV (epel , hv , 12 , 4 , hv)
BI_W_MC_HV() [13/15]
BI_W_MC_HV (epel , hv , 16 , 4 , hv)
BI_W_MC_HV() [14/15]
BI_W_MC_HV (epel , hv , 24 , 4 , hv)
BI_W_MC_HV() [15/15]
BI_W_MC_HV (epel , hv , 32 , 4 , hv)