FFmpeg: libavcodec/hevc_ps_enc.c File Reference
hevc_ps_enc.c File Reference
#include "golomb.h"
#include "hevc.h"
#include "put_bits.h"
Functions
static void write_ptl_layer (PutBitContext *pb, PTLCommon *ptl)
static void write_ptl (PutBitContext *pb, PTL *ptl, int max_num_sub_layers)
int ff_hevc_encode_nal_vps (HEVCVPS *vps, unsigned int id, uint8_t *buf, int buf_size)
Function Documentation
write_ptl_layer()
static void write_ptl_layer (PutBitContext * pb, PTLCommon * ptl) static
Definition at line 25 of file hevc_ps_enc.c.
Referenced by write_ptl().
write_ptl()
static void write_ptl (PutBitContext * pb, PTL * ptl, int max_num_sub_layers) static
Definition at line 42 of file hevc_ps_enc.c.
Referenced by ff_hevc_encode_nal_vps().
ff_hevc_encode_nal_vps()
int ff_hevc_encode_nal_vps (HEVCVPS * vps, unsigned int id, uint8_t * buf, int buf_size)
Definition at line 66 of file hevc_ps_enc.c.
Referenced by generate_fake_vps().