FFmpeg: libavcodec/mips/hevc_mc_bi_msa.c File Reference
hevc_mc_bi_msa.c File Reference
#include "libavutil/mips/generic_macros_msa.h"
#include "libavcodec/mips/hevcdsp_mips.h"
#include "libavcodec/mips/hevc_macros_msa.h"
Macros
#define HEVC_BI_RND_CLIP2(in0, in1, vec0, vec1, rnd_val, out0, out1)
#define HEVC_BI_RND_CLIP4(in0, in1, in2, in3, vec0, vec1, vec2, vec3, rnd_val, out0, out1, out2, out3)
#define BI_MC_COPY(WIDTH)
#define BI_MC(PEL, DIR, WIDTH, TAP, DIR1, FILT_DIR)
#define BI_MC_HV(PEL, DIR, WIDTH, TAP, DIR1)
Functions
static void hevc_bi_copy_4w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void hevc_bi_copy_6w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void hevc_bi_copy_8w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void hevc_bi_copy_12w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void hevc_bi_copy_16multx4mult_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t width)
static void hevc_bi_copy_16w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void hevc_bi_copy_24w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void hevc_bi_copy_32w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void hevc_bi_copy_48w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void hevc_bi_copy_64w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void hevc_hz_bi_8t_4w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_bi_8t_8w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_bi_8t_12w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_bi_8t_16w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_bi_8t_24w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_bi_8t_32w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_bi_8t_48w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_bi_8t_64w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_bi_8t_4w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_bi_8t_8w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_bi_8t_12w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_bi_8t_16multx2mult_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t width)
static void hevc_vt_bi_8t_16w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_bi_8t_24w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_bi_8t_32w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_bi_8t_48w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_bi_8t_64w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hv_bi_8t_4w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_bi_8t_8multx2mult_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t width)
static void hevc_hv_bi_8t_8w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_bi_8t_12w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_bi_8t_16w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_bi_8t_24w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_bi_8t_32w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_bi_8t_48w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_bi_8t_64w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hz_bi_4t_4x2_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_bi_4t_4x4_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_bi_4t_4x8multiple_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_bi_4t_4w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_bi_4t_6w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_bi_4t_8x2_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_bi_4t_8x6_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_bi_4t_8x4multiple_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_bi_4t_8w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_bi_4t_12w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_bi_4t_16w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_bi_4t_24w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_bi_4t_32w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_bi_4t_4x2_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_bi_4t_4x4_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_bi_4t_4x8multiple_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_bi_4t_4w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_bi_4t_6w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_bi_4t_8x2_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_bi_4t_8x6_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_bi_4t_8x4multiple_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_bi_4t_8w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_bi_4t_12w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_bi_4t_16w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_bi_4t_24w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_bi_4t_32w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hv_bi_4t_4x2_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_bi_4t_4x4_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_bi_4t_4multx8mult_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_bi_4t_4w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_bi_4t_6w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_bi_4t_8x2_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_bi_4t_8x6_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_bi_4t_8multx4mult_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t width)
static void hevc_hv_bi_4t_8w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_bi_4t_12w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_bi_4t_16w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_bi_4t_24w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_bi_4t_32w_msa (uint8_t *src0_ptr, int32_t src_stride, int16_t *src1_ptr, int32_t src2_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const const int8_t *filter_y, int32_t height)
BI_MC_COPY (4)
BI_MC_COPY (6)
BI_MC_COPY (8)
BI_MC_COPY (12)
BI_MC_COPY (16)
BI_MC_COPY (24)
BI_MC_COPY (32)
BI_MC_COPY (48)
BI_MC_COPY (64)
BI_MC (qpel, h, 4, 8, hz, mx)
BI_MC (qpel, h, 8, 8, hz, mx)
BI_MC (qpel, h, 12, 8, hz, mx)
BI_MC (qpel, h, 16, 8, hz, mx)
BI_MC (qpel, h, 24, 8, hz, mx)
BI_MC (qpel, h, 32, 8, hz, mx)
BI_MC (qpel, h, 48, 8, hz, mx)
BI_MC (qpel, h, 64, 8, hz, mx)
BI_MC (qpel, v, 4, 8, vt, my)
BI_MC (qpel, v, 8, 8, vt, my)
BI_MC (qpel, v, 12, 8, vt, my)
BI_MC (qpel, v, 16, 8, vt, my)
BI_MC (qpel, v, 24, 8, vt, my)
BI_MC (qpel, v, 32, 8, vt, my)
BI_MC (qpel, v, 48, 8, vt, my)
BI_MC (qpel, v, 64, 8, vt, my)
BI_MC (epel, h, 4, 4, hz, mx)
BI_MC (epel, h, 8, 4, hz, mx)
BI_MC (epel, h, 6, 4, hz, mx)
BI_MC (epel, h, 12, 4, hz, mx)
BI_MC (epel, h, 16, 4, hz, mx)
BI_MC (epel, h, 24, 4, hz, mx)
BI_MC (epel, h, 32, 4, hz, mx)
BI_MC (epel, v, 4, 4, vt, my)
BI_MC (epel, v, 8, 4, vt, my)
BI_MC (epel, v, 6, 4, vt, my)
BI_MC (epel, v, 12, 4, vt, my)
BI_MC (epel, v, 16, 4, vt, my)
BI_MC (epel, v, 24, 4, vt, my)
BI_MC (epel, v, 32, 4, vt, my)
BI_MC_HV (qpel, hv, 4, 8, hv)
BI_MC_HV (qpel, hv, 8, 8, hv)
BI_MC_HV (qpel, hv, 12, 8, hv)
BI_MC_HV (qpel, hv, 16, 8, hv)
BI_MC_HV (qpel, hv, 24, 8, hv)
BI_MC_HV (qpel, hv, 32, 8, hv)
BI_MC_HV (qpel, hv, 48, 8, hv)
BI_MC_HV (qpel, hv, 64, 8, hv)
BI_MC_HV (epel, hv, 4, 4, hv)
BI_MC_HV (epel, hv, 8, 4, hv)
BI_MC_HV (epel, hv, 6, 4, hv)
BI_MC_HV (epel, hv, 12, 4, hv)
BI_MC_HV (epel, hv, 16, 4, hv)
BI_MC_HV (epel, hv, 24, 4, hv)
BI_MC_HV (epel, hv, 32, 4, hv)
Macro Definition Documentation
HEVC_BI_RND_CLIP2
#define HEVC_BI_RND_CLIP2 (in0, in1, vec0, vec1, rnd_val, out0, out1)
Value:
{                                                                     \
    ADDS_SH2_SH(vec0, in0, vec1, in1, out0, out1);                    \
    SRARI_H2_SH(out0, out1, rnd_val);                                 \
    CLIP_SH2_0_255(out0, out1);                                       \
}
Definition at line 25 of file hevc_mc_bi_msa.c.
Referenced by hevc_bi_copy_12w_msa(), hevc_bi_copy_4w_msa(), hevc_bi_copy_8w_msa(), hevc_hv_bi_4t_4x4_msa(), hevc_hv_bi_4t_8x2_msa(), hevc_hv_bi_4t_8x6_msa(), hevc_hz_bi_4t_12w_msa(), hevc_hz_bi_4t_4x4_msa(), hevc_hz_bi_4t_8x2_msa(), hevc_hz_bi_4t_8x6_msa(), hevc_hz_bi_8t_24w_msa(), hevc_hz_bi_8t_48w_msa(), hevc_vt_bi_4t_12w_msa(), hevc_vt_bi_4t_24w_msa(), hevc_vt_bi_4t_4x4_msa(), hevc_vt_bi_4t_8x2_msa(), hevc_vt_bi_4t_8x6_msa(), and hevc_vt_bi_8t_12w_msa().
HEVC_BI_RND_CLIP4
#define HEVC_BI_RND_CLIP4 (in0, in1, in2, in3, vec0, vec1, vec2, vec3, rnd_val, out0, out1, out2, out3)
Value:
{                                                                  \
    HEVC_BI_RND_CLIP2(in0, in1, vec0, vec1, rnd_val, out0, out1);  \
    HEVC_BI_RND_CLIP2(in2, in3, vec2, vec3, rnd_val, out2, out3);  \
}
Definition at line 32 of file hevc_mc_bi_msa.c.
Referenced by hevc_bi_copy_12w_msa(), hevc_bi_copy_16multx4mult_msa(), hevc_bi_copy_4w_msa(), hevc_bi_copy_6w_msa(), hevc_bi_copy_8w_msa(), hevc_hv_bi_4t_4multx8mult_msa(), hevc_hv_bi_4t_6w_msa(), hevc_hv_bi_4t_8multx4mult_msa(), hevc_hv_bi_4t_8x6_msa(), hevc_hz_bi_4t_12w_msa(), hevc_hz_bi_4t_16w_msa(), hevc_hz_bi_4t_24w_msa(), hevc_hz_bi_4t_32w_msa(), hevc_hz_bi_4t_4x8multiple_msa(), hevc_hz_bi_4t_6w_msa(), hevc_hz_bi_4t_8x4multiple_msa(), hevc_hz_bi_4t_8x6_msa(), hevc_hz_bi_8t_16w_msa(), hevc_hz_bi_8t_32w_msa(), hevc_hz_bi_8t_4w_msa(), hevc_hz_bi_8t_64w_msa(), hevc_hz_bi_8t_8w_msa(), hevc_vt_bi_4t_12w_msa(), hevc_vt_bi_4t_16w_msa(), hevc_vt_bi_4t_24w_msa(), hevc_vt_bi_4t_32w_msa(), hevc_vt_bi_4t_4x8multiple_msa(), hevc_vt_bi_4t_6w_msa(), hevc_vt_bi_4t_8x4multiple_msa(), hevc_vt_bi_4t_8x6_msa(), hevc_vt_bi_8t_12w_msa(), hevc_vt_bi_8t_16multx2mult_msa(), hevc_vt_bi_8t_4w_msa(), and hevc_vt_bi_8t_8w_msa().
BI_MC_COPY
#define BI_MC_COPY (WIDTH)
Value:
void ff_hevc_put_hevc_bi_pel_pixels##WIDTH##_8_msa(uint8_t *dst,          \
                                                   ptrdiff_t dst_stride,  \
                                                   uint8_t *src,          \
                                                   ptrdiff_t src_stride,  \
                                                   int16_t *src_16bit,    \
                                                   int height,            \
                                                   intptr_t mx,           \
                                                   intptr_t my,           \
                                                   int width)             \
{                                                                         \
    hevc_bi_copy_##WIDTH##w_msa(src, src_stride, src_16bit, MAX_PB_SIZE,  \
                                dst, dst_stride, height);                 \
}
Definition at line 4344 of file hevc_mc_bi_msa.c.
BI_MC
#define BI_MC (PEL, DIR, WIDTH, TAP, DIR1, FILT_DIR)
Value:
void ff_hevc_put_hevc_bi_##PEL##_##DIR##WIDTH##_8_msa(uint8_t *dst,            \
                                                        ptrdiff_t dst_stride,  \
                                                        uint8_t *src,          \
                                                        ptrdiff_t src_stride,  \
                                                        int16_t *src_16bit,    \
                                                        int height,            \
                                                        intptr_t mx,           \
                                                        intptr_t my,           \
                                                        int width)             \
{                                                                              \
    const int8_t *filter = ff_hevc_##PEL##_filters[FILT_DIR - 1];              \
                                                                               \
    hevc_##DIR1##_bi_##TAP##t_##WIDTH##w_msa(src, src_stride, src_16bit,       \
                                             MAX_PB_SIZE, dst, dst_stride,     \
                                             filter, height);                  \
}
Definition at line 4371 of file hevc_mc_bi_msa.c.
BI_MC_HV
#define BI_MC_HV (PEL, DIR, WIDTH, TAP, DIR1)
Value:
void ff_hevc_put_hevc_bi_##PEL##_##DIR##WIDTH##_8_msa(uint8_t *dst,            \
                                                        ptrdiff_t dst_stride,  \
                                                        uint8_t *src,          \
                                                        ptrdiff_t src_stride,  \
                                                        int16_t *src_16bit,    \
                                                        int height,            \
                                                        intptr_t mx,           \
                                                        intptr_t my,           \
                                                        int width)             \
{                                                                              \
    const int8_t *filter_x = ff_hevc_##PEL##_filters[mx - 1];                  \
    const int8_t *filter_y = ff_hevc_##PEL##_filters[my - 1];                  \
                                                                               \
    hevc_##DIR1##_bi_##TAP##t_##WIDTH##w_msa(src, src_stride, src_16bit,       \
                                             MAX_PB_SIZE, dst, dst_stride,     \
                                             filter_x, filter_y,               \
                                             height);                          \
}
Definition at line 4425 of file hevc_mc_bi_msa.c.
Function Documentation
hevc_bi_copy_4w_msa()
static void hevc_bi_copy_4w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 40 of file hevc_mc_bi_msa.c.
hevc_bi_copy_6w_msa()
static void hevc_bi_copy_6w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 120 of file hevc_mc_bi_msa.c.
hevc_bi_copy_8w_msa()
static void hevc_bi_copy_8w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 163 of file hevc_mc_bi_msa.c.
Referenced by hevc_bi_copy_24w_msa().
hevc_bi_copy_12w_msa()
static void hevc_bi_copy_12w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 269 of file hevc_mc_bi_msa.c.
hevc_bi_copy_16multx4mult_msa()
static void hevc_bi_copy_16multx4mult_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t width) static
Definition at line 310 of file hevc_mc_bi_msa.c.
Referenced by hevc_bi_copy_16w_msa(), hevc_bi_copy_24w_msa(), hevc_bi_copy_32w_msa(), hevc_bi_copy_48w_msa(), and hevc_bi_copy_64w_msa().
hevc_bi_copy_16w_msa()
static void hevc_bi_copy_16w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 373 of file hevc_mc_bi_msa.c.
hevc_bi_copy_24w_msa()
static void hevc_bi_copy_24w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 385 of file hevc_mc_bi_msa.c.
hevc_bi_copy_32w_msa()
static void hevc_bi_copy_32w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 400 of file hevc_mc_bi_msa.c.
hevc_bi_copy_48w_msa()
static void hevc_bi_copy_48w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 412 of file hevc_mc_bi_msa.c.
hevc_bi_copy_64w_msa()
static void hevc_bi_copy_64w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 424 of file hevc_mc_bi_msa.c.
hevc_hz_bi_8t_4w_msa()
static void hevc_hz_bi_8t_4w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 436 of file hevc_mc_bi_msa.c.
Referenced by hevc_hz_bi_8t_12w_msa().
hevc_hz_bi_8t_8w_msa()
static void hevc_hz_bi_8t_8w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 509 of file hevc_mc_bi_msa.c.
Referenced by hevc_hz_bi_8t_12w_msa().
hevc_hz_bi_8t_12w_msa()
static void hevc_hz_bi_8t_12w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 577 of file hevc_mc_bi_msa.c.
hevc_hz_bi_8t_16w_msa()
static void hevc_hz_bi_8t_16w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 592 of file hevc_mc_bi_msa.c.
hevc_hz_bi_8t_24w_msa()
static void hevc_hz_bi_8t_24w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 663 of file hevc_mc_bi_msa.c.
hevc_hz_bi_8t_32w_msa()
static void hevc_hz_bi_8t_32w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 735 of file hevc_mc_bi_msa.c.
hevc_hz_bi_8t_48w_msa()
static void hevc_hz_bi_8t_48w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 807 of file hevc_mc_bi_msa.c.
hevc_hz_bi_8t_64w_msa()
static void hevc_hz_bi_8t_64w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 908 of file hevc_mc_bi_msa.c.
hevc_vt_bi_8t_4w_msa()
static void hevc_vt_bi_8t_4w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 996 of file hevc_mc_bi_msa.c.
hevc_vt_bi_8t_8w_msa()
static void hevc_vt_bi_8t_8w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1082 of file hevc_mc_bi_msa.c.
Referenced by hevc_vt_bi_8t_24w_msa().
hevc_vt_bi_8t_12w_msa()
static void hevc_vt_bi_8t_12w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1160 of file hevc_mc_bi_msa.c.
hevc_vt_bi_8t_16multx2mult_msa()
static void hevc_vt_bi_8t_16multx2mult_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t width) static
Definition at line 1266 of file hevc_mc_bi_msa.c.
Referenced by hevc_vt_bi_8t_16w_msa(), hevc_vt_bi_8t_24w_msa(), hevc_vt_bi_8t_32w_msa(), hevc_vt_bi_8t_48w_msa(), and hevc_vt_bi_8t_64w_msa().
hevc_vt_bi_8t_16w_msa()
static void hevc_vt_bi_8t_16w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1372 of file hevc_mc_bi_msa.c.
hevc_vt_bi_8t_24w_msa()
static void hevc_vt_bi_8t_24w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1385 of file hevc_mc_bi_msa.c.
hevc_vt_bi_8t_32w_msa()
static void hevc_vt_bi_8t_32w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1400 of file hevc_mc_bi_msa.c.
hevc_vt_bi_8t_48w_msa()
static void hevc_vt_bi_8t_48w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1413 of file hevc_mc_bi_msa.c.
hevc_vt_bi_8t_64w_msa()
static void hevc_vt_bi_8t_64w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1426 of file hevc_mc_bi_msa.c.
hevc_hv_bi_8t_4w_msa()
static void hevc_hv_bi_8t_4w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 1439 of file hevc_mc_bi_msa.c.
Referenced by hevc_hv_bi_8t_12w_msa().
hevc_hv_bi_8t_8multx2mult_msa()
static void hevc_hv_bi_8t_8multx2mult_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t width) static
Definition at line 1558 of file hevc_mc_bi_msa.c.
Referenced by hevc_hv_bi_8t_12w_msa(), hevc_hv_bi_8t_16w_msa(), hevc_hv_bi_8t_24w_msa(), hevc_hv_bi_8t_32w_msa(), hevc_hv_bi_8t_48w_msa(), hevc_hv_bi_8t_64w_msa(), and hevc_hv_bi_8t_8w_msa().
hevc_hv_bi_8t_8w_msa()
static void hevc_hv_bi_8t_8w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 1735 of file hevc_mc_bi_msa.c.
hevc_hv_bi_8t_12w_msa()
static void hevc_hv_bi_8t_12w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 1750 of file hevc_mc_bi_msa.c.
hevc_hv_bi_8t_16w_msa()
static void hevc_hv_bi_8t_16w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 1768 of file hevc_mc_bi_msa.c.
hevc_hv_bi_8t_24w_msa()
static void hevc_hv_bi_8t_24w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 1783 of file hevc_mc_bi_msa.c.
hevc_hv_bi_8t_32w_msa()
static void hevc_hv_bi_8t_32w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 1798 of file hevc_mc_bi_msa.c.
hevc_hv_bi_8t_48w_msa()
static void hevc_hv_bi_8t_48w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 1813 of file hevc_mc_bi_msa.c.
hevc_hv_bi_8t_64w_msa()
static void hevc_hv_bi_8t_64w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 1828 of file hevc_mc_bi_msa.c.
hevc_hz_bi_4t_4x2_msa()
static void hevc_hz_bi_4t_4x2_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1843 of file hevc_mc_bi_msa.c.
Referenced by hevc_hz_bi_4t_4w_msa().
hevc_hz_bi_4t_4x4_msa()
static void hevc_hz_bi_4t_4x4_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1886 of file hevc_mc_bi_msa.c.
Referenced by hevc_hz_bi_4t_4w_msa().
hevc_hz_bi_4t_4x8multiple_msa()
static void hevc_hz_bi_4t_4x8multiple_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1931 of file hevc_mc_bi_msa.c.
Referenced by hevc_hz_bi_4t_4w_msa().
hevc_hz_bi_4t_4w_msa()
static void hevc_hz_bi_4t_4w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1994 of file hevc_mc_bi_msa.c.
hevc_hz_bi_4t_6w_msa()
static void hevc_hz_bi_4t_6w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2016 of file hevc_mc_bi_msa.c.
hevc_hz_bi_4t_8x2_msa()
static void hevc_hz_bi_4t_8x2_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2074 of file hevc_mc_bi_msa.c.
Referenced by hevc_hz_bi_4t_8w_msa().
hevc_hz_bi_4t_8x6_msa()
static void hevc_hz_bi_4t_8x6_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2117 of file hevc_mc_bi_msa.c.
Referenced by hevc_hz_bi_4t_8w_msa().
hevc_hz_bi_4t_8x4multiple_msa()
static void hevc_hz_bi_4t_8x4multiple_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2181 of file hevc_mc_bi_msa.c.
Referenced by hevc_hz_bi_4t_8w_msa().
hevc_hz_bi_4t_8w_msa()
static void hevc_hz_bi_4t_8w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2239 of file hevc_mc_bi_msa.c.
hevc_hz_bi_4t_12w_msa()
static void hevc_hz_bi_4t_12w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2261 of file hevc_mc_bi_msa.c.
hevc_hz_bi_4t_16w_msa()
static void hevc_hz_bi_4t_16w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2334 of file hevc_mc_bi_msa.c.
hevc_hz_bi_4t_24w_msa()
static void hevc_hz_bi_4t_24w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2409 of file hevc_mc_bi_msa.c.
hevc_hz_bi_4t_32w_msa()
static void hevc_hz_bi_4t_32w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2514 of file hevc_mc_bi_msa.c.
hevc_vt_bi_4t_4x2_msa()
static void hevc_vt_bi_4t_4x2_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2602 of file hevc_mc_bi_msa.c.
Referenced by hevc_vt_bi_4t_4w_msa().
hevc_vt_bi_4t_4x4_msa()
static void hevc_vt_bi_4t_4x4_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2650 of file hevc_mc_bi_msa.c.
Referenced by hevc_vt_bi_4t_4w_msa().
hevc_vt_bi_4t_4x8multiple_msa()
static void hevc_vt_bi_4t_4x8multiple_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2699 of file hevc_mc_bi_msa.c.
Referenced by hevc_vt_bi_4t_4w_msa().
hevc_vt_bi_4t_4w_msa()
static void hevc_vt_bi_4t_4w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2772 of file hevc_mc_bi_msa.c.
hevc_vt_bi_4t_6w_msa()
static void hevc_vt_bi_4t_6w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2794 of file hevc_mc_bi_msa.c.
hevc_vt_bi_4t_8x2_msa()
static void hevc_vt_bi_4t_8x2_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2857 of file hevc_mc_bi_msa.c.
Referenced by hevc_vt_bi_4t_8w_msa().
hevc_vt_bi_4t_8x6_msa()
static void hevc_vt_bi_4t_8x6_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2901 of file hevc_mc_bi_msa.c.
Referenced by hevc_vt_bi_4t_8w_msa().
hevc_vt_bi_4t_8x4multiple_msa()
static void hevc_vt_bi_4t_8x4multiple_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2962 of file hevc_mc_bi_msa.c.
Referenced by hevc_vt_bi_4t_8w_msa().
hevc_vt_bi_4t_8w_msa()
static void hevc_vt_bi_4t_8w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 3024 of file hevc_mc_bi_msa.c.
hevc_vt_bi_4t_12w_msa()
static void hevc_vt_bi_4t_12w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 3046 of file hevc_mc_bi_msa.c.
hevc_vt_bi_4t_16w_msa()
static void hevc_vt_bi_4t_16w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 3126 of file hevc_mc_bi_msa.c.
hevc_vt_bi_4t_24w_msa()
static void hevc_vt_bi_4t_24w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 3211 of file hevc_mc_bi_msa.c.
hevc_vt_bi_4t_32w_msa()
static void hevc_vt_bi_4t_32w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 3335 of file hevc_mc_bi_msa.c.
hevc_hv_bi_4t_4x2_msa()
static void hevc_hv_bi_4t_4x2_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 3445 of file hevc_mc_bi_msa.c.
Referenced by hevc_hv_bi_4t_4w_msa().
hevc_hv_bi_4t_4x4_msa()
static void hevc_hv_bi_4t_4x4_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 3525 of file hevc_mc_bi_msa.c.
Referenced by hevc_hv_bi_4t_4w_msa().
hevc_hv_bi_4t_4multx8mult_msa()
static void hevc_hv_bi_4t_4multx8mult_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 3619 of file hevc_mc_bi_msa.c.
Referenced by hevc_hv_bi_4t_4w_msa().
hevc_hv_bi_4t_4w_msa()
static void hevc_hv_bi_4t_4w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 3751 of file hevc_mc_bi_msa.c.
Referenced by hevc_hv_bi_4t_12w_msa().
hevc_hv_bi_4t_6w_msa()
static void hevc_hv_bi_4t_6w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 3775 of file hevc_mc_bi_msa.c.
hevc_hv_bi_4t_8x2_msa()
static void hevc_hv_bi_4t_8x2_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 3890 of file hevc_mc_bi_msa.c.
Referenced by hevc_hv_bi_4t_8w_msa().
hevc_hv_bi_4t_8x6_msa()
static void hevc_hv_bi_4t_8x6_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 3978 of file hevc_mc_bi_msa.c.
Referenced by hevc_hv_bi_4t_8w_msa().
hevc_hv_bi_4t_8multx4mult_msa()
static void hevc_hv_bi_4t_8multx4mult_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t width) static
Definition at line 4127 of file hevc_mc_bi_msa.c.
Referenced by hevc_hv_bi_4t_12w_msa(), hevc_hv_bi_4t_16w_msa(), hevc_hv_bi_4t_24w_msa(), hevc_hv_bi_4t_32w_msa(), and hevc_hv_bi_4t_8w_msa().
hevc_hv_bi_4t_8w_msa()
static void hevc_hv_bi_4t_8w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 4258 of file hevc_mc_bi_msa.c.
hevc_hv_bi_4t_12w_msa()
static void hevc_hv_bi_4t_12w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 4282 of file hevc_mc_bi_msa.c.
hevc_hv_bi_4t_16w_msa()
static void hevc_hv_bi_4t_16w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 4299 of file hevc_mc_bi_msa.c.
hevc_hv_bi_4t_24w_msa()
static void hevc_hv_bi_4t_24w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 4314 of file hevc_mc_bi_msa.c.
hevc_hv_bi_4t_32w_msa()
static void hevc_hv_bi_4t_32w_msa (uint8_t * src0_ptr, int32_t src_stride, int16_t * src1_ptr, int32_t src2_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const const int8_t * filter_y, int32_t height) static
Definition at line 4329 of file hevc_mc_bi_msa.c.
BI_MC_COPY() [1/9]
BI_MC_COPY (4)
BI_MC_COPY() [2/9]
BI_MC_COPY (6)
BI_MC_COPY() [3/9]
BI_MC_COPY (8)
BI_MC_COPY() [4/9]
BI_MC_COPY (12)
BI_MC_COPY() [5/9]
BI_MC_COPY (16)
BI_MC_COPY() [6/9]
BI_MC_COPY (24)
BI_MC_COPY() [7/9]
BI_MC_COPY (32)
BI_MC_COPY() [8/9]
BI_MC_COPY (48)
BI_MC_COPY() [9/9]
BI_MC_COPY (64)
BI_MC() [1/30]
BI_MC (qpel , h , 4 , 8 , hz , mx)
BI_MC() [2/30]
BI_MC (qpel , h , 8 , 8 , hz , mx)
BI_MC() [3/30]
BI_MC (qpel , h , 12 , 8 , hz , mx)
BI_MC() [4/30]
BI_MC (qpel , h , 16 , 8 , hz , mx)
BI_MC() [5/30]
BI_MC (qpel , h , 24 , 8 , hz , mx)
BI_MC() [6/30]
BI_MC (qpel , h , 32 , 8 , hz , mx)
BI_MC() [7/30]
BI_MC (qpel , h , 48 , 8 , hz , mx)
BI_MC() [8/30]
BI_MC (qpel , h , 64 , 8 , hz , mx)
BI_MC() [9/30]
BI_MC (qpel , v , 4 , 8 , vt , my)
BI_MC() [10/30]
BI_MC (qpel , v , 8 , 8 , vt , my)
BI_MC() [11/30]
BI_MC (qpel , v , 12 , 8 , vt , my)
BI_MC() [12/30]
BI_MC (qpel , v , 16 , 8 , vt , my)
BI_MC() [13/30]
BI_MC (qpel , v , 24 , 8 , vt , my)
BI_MC() [14/30]
BI_MC (qpel , v , 32 , 8 , vt , my)
BI_MC() [15/30]
BI_MC (qpel , v , 48 , 8 , vt , my)
BI_MC() [16/30]
BI_MC (qpel , v , 64 , 8 , vt , my)
BI_MC() [17/30]
BI_MC (epel , h , 4 , 4 , hz , mx)
BI_MC() [18/30]
BI_MC (epel , h , 8 , 4 , hz , mx)
BI_MC() [19/30]
BI_MC (epel , h , 6 , 4 , hz , mx)
BI_MC() [20/30]
BI_MC (epel , h , 12 , 4 , hz , mx)
BI_MC() [21/30]
BI_MC (epel , h , 16 , 4 , hz , mx)
BI_MC() [22/30]
BI_MC (epel , h , 24 , 4 , hz , mx)
BI_MC() [23/30]
BI_MC (epel , h , 32 , 4 , hz , mx)
BI_MC() [24/30]
BI_MC (epel , v , 4 , 4 , vt , my)
BI_MC() [25/30]
BI_MC (epel , v , 8 , 4 , vt , my)
BI_MC() [26/30]
BI_MC (epel , v , 6 , 4 , vt , my)
BI_MC() [27/30]
BI_MC (epel , v , 12 , 4 , vt , my)
BI_MC() [28/30]
BI_MC (epel , v , 16 , 4 , vt , my)
BI_MC() [29/30]
BI_MC (epel , v , 24 , 4 , vt , my)
BI_MC() [30/30]
BI_MC (epel , v , 32 , 4 , vt , my)
BI_MC_HV() [1/15]
BI_MC_HV (qpel , hv , 4 , 8 , hv)
BI_MC_HV() [2/15]
BI_MC_HV (qpel , hv , 8 , 8 , hv)
BI_MC_HV() [3/15]
BI_MC_HV (qpel , hv , 12 , 8 , hv)
BI_MC_HV() [4/15]
BI_MC_HV (qpel , hv , 16 , 8 , hv)
BI_MC_HV() [5/15]
BI_MC_HV (qpel , hv , 24 , 8 , hv)
BI_MC_HV() [6/15]
BI_MC_HV (qpel , hv , 32 , 8 , hv)
BI_MC_HV() [7/15]
BI_MC_HV (qpel , hv , 48 , 8 , hv)
BI_MC_HV() [8/15]
BI_MC_HV (qpel , hv , 64 , 8 , hv)
BI_MC_HV() [9/15]
BI_MC_HV (epel , hv , 4 , 4 , hv)
BI_MC_HV() [10/15]
BI_MC_HV (epel , hv , 8 , 4 , hv)
BI_MC_HV() [11/15]
BI_MC_HV (epel , hv , 6 , 4 , hv)
BI_MC_HV() [12/15]
BI_MC_HV (epel , hv , 12 , 4 , hv)
BI_MC_HV() [13/15]
BI_MC_HV (epel , hv , 16 , 4 , hv)
BI_MC_HV() [14/15]
BI_MC_HV (epel , hv , 24 , 4 , hv)
BI_MC_HV() [15/15]
BI_MC_HV (epel , hv , 32 , 4 , hv)