FFmpeg: libavcodec/arm/hevcdsp_init_neon.c File Reference
hevcdsp_init_neon.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/arm/cpu.h"
#include "libavcodec/hevcdsp.h"
#include "hevcdsp_arm.h"
Macros
#define PUT_PIXELS(name)
#define QPEL_FUNC(name)
#define QPEL_FUNC_UW_PIX(name)
#define QPEL_FUNC_UW(name)
Functions
void ff_hevc_v_loop_filter_luma_neon (uint8_t *_pix, ptrdiff_t _stride, int _beta, int *_tc, uint8_t *_no_p, uint8_t *_no_q)
void ff_hevc_h_loop_filter_luma_neon (uint8_t *_pix, ptrdiff_t _stride, int _beta, int *_tc, uint8_t *_no_p, uint8_t *_no_q)
void ff_hevc_v_loop_filter_chroma_neon (uint8_t *_pix, ptrdiff_t _stride, int *_tc, uint8_t *_no_p, uint8_t *_no_q)
void ff_hevc_h_loop_filter_chroma_neon (uint8_t *_pix, ptrdiff_t _stride, int *_tc, uint8_t *_no_p, uint8_t *_no_q)
void ff_hevc_transform_4x4_neon_8 (int16_t *coeffs, int col_limit)
void ff_hevc_transform_8x8_neon_8 (int16_t *coeffs, int col_limit)
void ff_hevc_idct_4x4_dc_neon_8 (int16_t *coeffs)
void ff_hevc_idct_8x8_dc_neon_8 (int16_t *coeffs)
void ff_hevc_idct_16x16_dc_neon_8 (int16_t *coeffs)
void ff_hevc_idct_32x32_dc_neon_8 (int16_t *coeffs)
void ff_hevc_transform_luma_4x4_neon_8 (int16_t *coeffs)
void ff_hevc_transform_add_4x4_neon_8 (uint8_t *_dst, int16_t *coeffs, ptrdiff_t stride)
void ff_hevc_transform_add_8x8_neon_8 (uint8_t *_dst, int16_t *coeffs, ptrdiff_t stride)
void ff_hevc_transform_add_16x16_neon_8 (uint8_t *_dst, int16_t *coeffs, ptrdiff_t stride)
void ff_hevc_transform_add_32x32_neon_8 (uint8_t *_dst, int16_t *coeffs, ptrdiff_t stride)
PUT_PIXELS (ff_hevc_put_pixels_w2_neon_8)
PUT_PIXELS (ff_hevc_put_pixels_w4_neon_8)
PUT_PIXELS (ff_hevc_put_pixels_w6_neon_8)
PUT_PIXELS (ff_hevc_put_pixels_w8_neon_8)
PUT_PIXELS (ff_hevc_put_pixels_w12_neon_8)
PUT_PIXELS (ff_hevc_put_pixels_w16_neon_8)
PUT_PIXELS (ff_hevc_put_pixels_w24_neon_8)
PUT_PIXELS (ff_hevc_put_pixels_w32_neon_8)
PUT_PIXELS (ff_hevc_put_pixels_w48_neon_8)
PUT_PIXELS (ff_hevc_put_pixels_w64_neon_8)
void ff_hevc_put_qpel_neon_wrapper (int16_t *dst, uint8_t *src, ptrdiff_t srcstride, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_qpel_uni_neon_wrapper (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_qpel_bi_neon_wrapper (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int16_t *src2, int height, intptr_t mx, intptr_t my, int width)
QPEL_FUNC (ff_hevc_put_qpel_v1_neon_8)
QPEL_FUNC (ff_hevc_put_qpel_v2_neon_8)
QPEL_FUNC (ff_hevc_put_qpel_v3_neon_8)
QPEL_FUNC (ff_hevc_put_qpel_h1_neon_8)
QPEL_FUNC (ff_hevc_put_qpel_h2_neon_8)
QPEL_FUNC (ff_hevc_put_qpel_h3_neon_8)
QPEL_FUNC (ff_hevc_put_qpel_h1v1_neon_8)
QPEL_FUNC (ff_hevc_put_qpel_h1v2_neon_8)
QPEL_FUNC (ff_hevc_put_qpel_h1v3_neon_8)
QPEL_FUNC (ff_hevc_put_qpel_h2v1_neon_8)
QPEL_FUNC (ff_hevc_put_qpel_h2v2_neon_8)
QPEL_FUNC (ff_hevc_put_qpel_h2v3_neon_8)
QPEL_FUNC (ff_hevc_put_qpel_h3v1_neon_8)
QPEL_FUNC (ff_hevc_put_qpel_h3v2_neon_8)
QPEL_FUNC (ff_hevc_put_qpel_h3v3_neon_8)
QPEL_FUNC_UW_PIX (ff_hevc_put_qpel_uw_pixels_w4_neon_8)
QPEL_FUNC_UW_PIX (ff_hevc_put_qpel_uw_pixels_w8_neon_8)
QPEL_FUNC_UW_PIX (ff_hevc_put_qpel_uw_pixels_w16_neon_8)
QPEL_FUNC_UW_PIX (ff_hevc_put_qpel_uw_pixels_w24_neon_8)
QPEL_FUNC_UW_PIX (ff_hevc_put_qpel_uw_pixels_w32_neon_8)
QPEL_FUNC_UW_PIX (ff_hevc_put_qpel_uw_pixels_w48_neon_8)
QPEL_FUNC_UW_PIX (ff_hevc_put_qpel_uw_pixels_w64_neon_8)
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_pixels_neon_8)
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_v1_neon_8)
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_v2_neon_8)
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_v3_neon_8)
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h1_neon_8)
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h2_neon_8)
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h3_neon_8)
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h1v1_neon_8)
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h1v2_neon_8)
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h1v3_neon_8)
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h2v1_neon_8)
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h2v2_neon_8)
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h2v3_neon_8)
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h3v1_neon_8)
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h3v2_neon_8)
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h3v3_neon_8)
av_cold void ff_hevcdsp_init_neon (HEVCDSPContext *c, const int bit_depth)
Variables
static void(* put_hevc_qpel_neon [4][4])(int16_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int height, int width)
static void(* put_hevc_qpel_uw_neon [4][4])(uint8_t *dst, ptrdiff_t dststride, uint8_t *_src, ptrdiff_t _srcstride, int width, int height, int16_t *src2, ptrdiff_t src2stride)
Macro Definition Documentation
PUT_PIXELS
#define PUT_PIXELS (name)
Value:
void name(int16_t *dst, uint8_t *src, \
                                ptrdiff_t srcstride, int height, \
                                intptr_t mx, intptr_t my, int width)
Definition at line 46 of file hevcdsp_init_neon.c.
QPEL_FUNC
#define QPEL_FUNC (name)
Value:
void name(int16_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, \
                                   int height, int width)
Definition at line 73 of file hevcdsp_init_neon.c.
QPEL_FUNC_UW_PIX
#define QPEL_FUNC_UW_PIX (name)
Value:
void name(uint8_t *dst, ptrdiff_t dststride, uint8_t *_src, ptrdiff_t _srcstride, \
                                   int height, intptr_t mx, intptr_t my, int width);
Definition at line 94 of file hevcdsp_init_neon.c.
QPEL_FUNC_UW
#define QPEL_FUNC_UW (name)
Value:
void name(uint8_t *dst, ptrdiff_t dststride, uint8_t *_src, ptrdiff_t _srcstride, \
                                   int width, int height, int16_t* src2, ptrdiff_t src2stride);
Definition at line 106 of file hevcdsp_init_neon.c.
Function Documentation
ff_hevc_v_loop_filter_luma_neon()
void ff_hevc_v_loop_filter_luma_neon (uint8_t * _pix, ptrdiff_t _stride, int _beta, int * _tc, uint8_t * _no_p, uint8_t * _no_q)
Referenced by ff_hevcdsp_init_neon().
ff_hevc_h_loop_filter_luma_neon()
void ff_hevc_h_loop_filter_luma_neon (uint8_t * _pix, ptrdiff_t _stride, int _beta, int * _tc, uint8_t * _no_p, uint8_t * _no_q)
Referenced by ff_hevcdsp_init_neon().
ff_hevc_v_loop_filter_chroma_neon()
void ff_hevc_v_loop_filter_chroma_neon (uint8_t * _pix, ptrdiff_t _stride, int * _tc, uint8_t * _no_p, uint8_t * _no_q)
Referenced by ff_hevcdsp_init_neon().
ff_hevc_h_loop_filter_chroma_neon()
void ff_hevc_h_loop_filter_chroma_neon (uint8_t * _pix, ptrdiff_t _stride, int * _tc, uint8_t * _no_p, uint8_t * _no_q)
Referenced by ff_hevcdsp_init_neon().
ff_hevc_transform_4x4_neon_8()
void ff_hevc_transform_4x4_neon_8 (int16_t * coeffs, int col_limit)
Referenced by ff_hevcdsp_init_neon().
ff_hevc_transform_8x8_neon_8()
void ff_hevc_transform_8x8_neon_8 (int16_t * coeffs, int col_limit)
Referenced by ff_hevcdsp_init_neon().
ff_hevc_idct_4x4_dc_neon_8()
void ff_hevc_idct_4x4_dc_neon_8 (int16_t * coeffs)
Referenced by ff_hevcdsp_init_neon().
ff_hevc_idct_8x8_dc_neon_8()
void ff_hevc_idct_8x8_dc_neon_8 (int16_t * coeffs)
Referenced by ff_hevcdsp_init_neon().
ff_hevc_idct_16x16_dc_neon_8()
void ff_hevc_idct_16x16_dc_neon_8 (int16_t * coeffs)
Referenced by ff_hevcdsp_init_neon().
ff_hevc_idct_32x32_dc_neon_8()
void ff_hevc_idct_32x32_dc_neon_8 (int16_t * coeffs)
Referenced by ff_hevcdsp_init_neon().
ff_hevc_transform_luma_4x4_neon_8()
void ff_hevc_transform_luma_4x4_neon_8 (int16_t * coeffs)
Referenced by ff_hevcdsp_init_neon().
ff_hevc_transform_add_4x4_neon_8()
void ff_hevc_transform_add_4x4_neon_8 (uint8_t * _dst, int16_t * coeffs, ptrdiff_t stride)
Referenced by ff_hevcdsp_init_neon().
ff_hevc_transform_add_8x8_neon_8()
void ff_hevc_transform_add_8x8_neon_8 (uint8_t * _dst, int16_t * coeffs, ptrdiff_t stride)
Referenced by ff_hevcdsp_init_neon().
ff_hevc_transform_add_16x16_neon_8()
void ff_hevc_transform_add_16x16_neon_8 (uint8_t * _dst, int16_t * coeffs, ptrdiff_t stride)
Referenced by ff_hevcdsp_init_neon().
ff_hevc_transform_add_32x32_neon_8()
void ff_hevc_transform_add_32x32_neon_8 (uint8_t * _dst, int16_t * coeffs, ptrdiff_t stride)
Referenced by ff_hevcdsp_init_neon().
PUT_PIXELS() [1/10]
PUT_PIXELS (ff_hevc_put_pixels_w2_neon_8)
PUT_PIXELS() [2/10]
PUT_PIXELS (ff_hevc_put_pixels_w4_neon_8)
PUT_PIXELS() [3/10]
PUT_PIXELS (ff_hevc_put_pixels_w6_neon_8)
PUT_PIXELS() [4/10]
PUT_PIXELS (ff_hevc_put_pixels_w8_neon_8)
PUT_PIXELS() [5/10]
PUT_PIXELS (ff_hevc_put_pixels_w12_neon_8)
PUT_PIXELS() [6/10]
PUT_PIXELS (ff_hevc_put_pixels_w16_neon_8)
PUT_PIXELS() [7/10]
PUT_PIXELS (ff_hevc_put_pixels_w24_neon_8)
PUT_PIXELS() [8/10]
PUT_PIXELS (ff_hevc_put_pixels_w32_neon_8)
PUT_PIXELS() [9/10]
PUT_PIXELS (ff_hevc_put_pixels_w48_neon_8)
PUT_PIXELS() [10/10]
PUT_PIXELS (ff_hevc_put_pixels_w64_neon_8)
ff_hevc_put_qpel_neon_wrapper()
void ff_hevc_put_qpel_neon_wrapper (int16_t * dst, uint8_t * src, ptrdiff_t srcstride, int height, intptr_t mx, intptr_t my, int width)
Definition at line 127 of file hevcdsp_init_neon.c.
Referenced by ff_hevcdsp_init_neon().
ff_hevc_put_qpel_uni_neon_wrapper()
void ff_hevc_put_qpel_uni_neon_wrapper (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int height, intptr_t mx, intptr_t my, int width)
Definition at line 133 of file hevcdsp_init_neon.c.
Referenced by ff_hevcdsp_init_neon().
ff_hevc_put_qpel_bi_neon_wrapper()
void ff_hevc_put_qpel_bi_neon_wrapper (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int16_t * src2, int height, intptr_t mx, intptr_t my, int width)
Definition at line 139 of file hevcdsp_init_neon.c.
Referenced by ff_hevcdsp_init_neon().
QPEL_FUNC() [1/15]
QPEL_FUNC (ff_hevc_put_qpel_v1_neon_8)
QPEL_FUNC() [2/15]
QPEL_FUNC (ff_hevc_put_qpel_v2_neon_8)
QPEL_FUNC() [3/15]
QPEL_FUNC (ff_hevc_put_qpel_v3_neon_8)
QPEL_FUNC() [4/15]
QPEL_FUNC (ff_hevc_put_qpel_h1_neon_8)
QPEL_FUNC() [5/15]
QPEL_FUNC (ff_hevc_put_qpel_h2_neon_8)
QPEL_FUNC() [6/15]
QPEL_FUNC (ff_hevc_put_qpel_h3_neon_8)
QPEL_FUNC() [7/15]
QPEL_FUNC (ff_hevc_put_qpel_h1v1_neon_8)
QPEL_FUNC() [8/15]
QPEL_FUNC (ff_hevc_put_qpel_h1v2_neon_8)
QPEL_FUNC() [9/15]
QPEL_FUNC (ff_hevc_put_qpel_h1v3_neon_8)
QPEL_FUNC() [10/15]
QPEL_FUNC (ff_hevc_put_qpel_h2v1_neon_8)
QPEL_FUNC() [11/15]
QPEL_FUNC (ff_hevc_put_qpel_h2v2_neon_8)
QPEL_FUNC() [12/15]
QPEL_FUNC (ff_hevc_put_qpel_h2v3_neon_8)
QPEL_FUNC() [13/15]
QPEL_FUNC (ff_hevc_put_qpel_h3v1_neon_8)
QPEL_FUNC() [14/15]
QPEL_FUNC (ff_hevc_put_qpel_h3v2_neon_8)
QPEL_FUNC() [15/15]
QPEL_FUNC (ff_hevc_put_qpel_h3v3_neon_8)
QPEL_FUNC_UW_PIX() [1/7]
QPEL_FUNC_UW_PIX (ff_hevc_put_qpel_uw_pixels_w4_neon_8)
QPEL_FUNC_UW_PIX() [2/7]
QPEL_FUNC_UW_PIX (ff_hevc_put_qpel_uw_pixels_w8_neon_8)
QPEL_FUNC_UW_PIX() [3/7]
QPEL_FUNC_UW_PIX (ff_hevc_put_qpel_uw_pixels_w16_neon_8)
QPEL_FUNC_UW_PIX() [4/7]
QPEL_FUNC_UW_PIX (ff_hevc_put_qpel_uw_pixels_w24_neon_8)
QPEL_FUNC_UW_PIX() [5/7]
QPEL_FUNC_UW_PIX (ff_hevc_put_qpel_uw_pixels_w32_neon_8)
QPEL_FUNC_UW_PIX() [6/7]
QPEL_FUNC_UW_PIX (ff_hevc_put_qpel_uw_pixels_w48_neon_8)
QPEL_FUNC_UW_PIX() [7/7]
QPEL_FUNC_UW_PIX (ff_hevc_put_qpel_uw_pixels_w64_neon_8)
QPEL_FUNC_UW() [1/16]
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_pixels_neon_8)
QPEL_FUNC_UW() [2/16]
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_v1_neon_8)
QPEL_FUNC_UW() [3/16]
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_v2_neon_8)
QPEL_FUNC_UW() [4/16]
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_v3_neon_8)
QPEL_FUNC_UW() [5/16]
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h1_neon_8)
QPEL_FUNC_UW() [6/16]
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h2_neon_8)
QPEL_FUNC_UW() [7/16]
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h3_neon_8)
QPEL_FUNC_UW() [8/16]
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h1v1_neon_8)
QPEL_FUNC_UW() [9/16]
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h1v2_neon_8)
QPEL_FUNC_UW() [10/16]
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h1v3_neon_8)
QPEL_FUNC_UW() [11/16]
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h2v1_neon_8)
QPEL_FUNC_UW() [12/16]
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h2v2_neon_8)
QPEL_FUNC_UW() [13/16]
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h2v3_neon_8)
QPEL_FUNC_UW() [14/16]
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h3v1_neon_8)
QPEL_FUNC_UW() [15/16]
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h3v2_neon_8)
QPEL_FUNC_UW() [16/16]
QPEL_FUNC_UW (ff_hevc_put_qpel_uw_h3v3_neon_8)
ff_hevcdsp_init_neon()
av_cold void ff_hevcdsp_init_neon (HEVCDSPContext * c, const int bit_depth)
Definition at line 145 of file hevcdsp_init_neon.c.
Referenced by ff_hevcdsp_init_arm().
Variable Documentation
put_hevc_qpel_neon
void(* put_hevc_qpel_neon[4][4])(int16_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int height, int width) static
Definition at line 62 of file hevcdsp_init_neon.c.
Referenced by ff_hevc_put_qpel_neon_wrapper(), and ff_hevcdsp_init_neon().
put_hevc_qpel_uw_neon
void(* put_hevc_qpel_uw_neon[4][4])(uint8_t *dst, ptrdiff_t dststride, uint8_t *_src, ptrdiff_t _srcstride, int width, int height, int16_t *src2, ptrdiff_t src2stride) static
Definition at line 64 of file hevcdsp_init_neon.c.
Referenced by ff_hevc_put_qpel_bi_neon_wrapper(), ff_hevc_put_qpel_uni_neon_wrapper(), and ff_hevcdsp_init_neon().