FFmpeg: libavcodec/mips/hevcdsp_msa.c File Reference
hevcdsp_msa.c File Reference
#include "libavutil/mips/generic_macros_msa.h"
#include "libavcodec/mips/hevcdsp_mips.h"
#include "libavcodec/mips/hevc_macros_msa.h"
Macros
#define MC_COPY(WIDTH)
#define MC(PEL, DIR, WIDTH, TAP, DIR1, FILT_DIR)
#define MC_HV(PEL, DIR, WIDTH, TAP, DIR1)
Functions
static void hevc_copy_4w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, int32_t height)
static void hevc_copy_6w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, int32_t height)
static void hevc_copy_8w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, int32_t height)
static void hevc_copy_12w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, int32_t height)
static void hevc_copy_16multx8mult_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, int32_t height, int32_t width)
static void hevc_copy_16w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, int32_t height)
static void hevc_copy_24w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, int32_t height)
static void hevc_copy_32w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, int32_t height)
static void hevc_copy_48w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, int32_t height)
static void hevc_copy_64w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, int32_t height)
static void hevc_hz_8t_4w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_8t_8w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_8t_12w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_8t_16w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_8t_24w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_8t_32w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_8t_48w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_8t_64w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_8t_4w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_8t_8w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_8t_12w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_8t_16multx4mult_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t width)
static void hevc_vt_8t_16w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_8t_24w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_8t_32w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_8t_48w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_8t_64w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hv_8t_4w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_8t_8multx2mult_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t width)
static void hevc_hv_8t_8w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_8t_12w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_8t_16w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_8t_24w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_8t_32w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_8t_48w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_8t_64w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hz_4t_4x2_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter)
static void hevc_hz_4t_4x4_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter)
static void hevc_hz_4t_4x8multiple_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_4t_4w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_4t_6w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_4t_8x2multiple_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_4t_8x4multiple_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_4t_8w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_4t_12w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_4t_16w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_4t_24w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hz_4t_32w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_4t_4x2_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter)
static void hevc_vt_4t_4x4_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_4t_4x8multiple_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_4t_4w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_4t_6w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_4t_8x2_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter)
static void hevc_vt_4t_8x6_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter)
static void hevc_vt_4t_8x4multiple_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_4t_8w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_4t_12w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_4t_16w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_4t_24w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_vt_4t_32w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height)
static void hevc_hv_4t_4x2_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y)
static void hevc_hv_4t_4x4_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y)
static void hevc_hv_4t_4multx8mult_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_4t_4w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_4t_6w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_4t_8x2_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_4t_8x6_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_4t_8multx4mult_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t width)
static void hevc_hv_4t_8w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_4t_12w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_4t_16w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_4t_24w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
static void hevc_hv_4t_32w_msa (uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height)
MC_COPY (4)
MC_COPY (6)
MC_COPY (8)
MC_COPY (12)
MC_COPY (16)
MC_COPY (24)
MC_COPY (32)
MC_COPY (48)
MC_COPY (64)
MC (qpel, h, 4, 8, hz, mx)
MC (qpel, h, 8, 8, hz, mx)
MC (qpel, h, 12, 8, hz, mx)
MC (qpel, h, 16, 8, hz, mx)
MC (qpel, h, 24, 8, hz, mx)
MC (qpel, h, 32, 8, hz, mx)
MC (qpel, h, 48, 8, hz, mx)
MC (qpel, h, 64, 8, hz, mx)
MC (qpel, v, 4, 8, vt, my)
MC (qpel, v, 8, 8, vt, my)
MC (qpel, v, 12, 8, vt, my)
MC (qpel, v, 16, 8, vt, my)
MC (qpel, v, 24, 8, vt, my)
MC (qpel, v, 32, 8, vt, my)
MC (qpel, v, 48, 8, vt, my)
MC (qpel, v, 64, 8, vt, my)
MC (epel, h, 4, 4, hz, mx)
MC (epel, h, 6, 4, hz, mx)
MC (epel, h, 8, 4, hz, mx)
MC (epel, h, 12, 4, hz, mx)
MC (epel, h, 16, 4, hz, mx)
MC (epel, h, 24, 4, hz, mx)
MC (epel, h, 32, 4, hz, mx)
MC (epel, v, 4, 4, vt, my)
MC (epel, v, 6, 4, vt, my)
MC (epel, v, 8, 4, vt, my)
MC (epel, v, 12, 4, vt, my)
MC (epel, v, 16, 4, vt, my)
MC (epel, v, 24, 4, vt, my)
MC (epel, v, 32, 4, vt, my)
MC_HV (qpel, hv, 4, 8, hv)
MC_HV (qpel, hv, 8, 8, hv)
MC_HV (qpel, hv, 12, 8, hv)
MC_HV (qpel, hv, 16, 8, hv)
MC_HV (qpel, hv, 24, 8, hv)
MC_HV (qpel, hv, 32, 8, hv)
MC_HV (qpel, hv, 48, 8, hv)
MC_HV (qpel, hv, 64, 8, hv)
MC_HV (epel, hv, 4, 4, hv)
MC_HV (epel, hv, 6, 4, hv)
MC_HV (epel, hv, 8, 4, hv)
MC_HV (epel, hv, 12, 4, hv)
MC_HV (epel, hv, 16, 4, hv)
MC_HV (epel, hv, 24, 4, hv)
MC_HV (epel, hv, 32, 4, hv)
Macro Definition Documentation
MC_COPY
#define MC_COPY (WIDTH)
Value:
void ff_hevc_put_hevc_pel_pixels##WIDTH##_8_msa(int16_t *dst,             \
                                                uint8_t *src,             \
                                                ptrdiff_t src_stride,     \
                                                int height,               \
                                                intptr_t mx,              \
                                                intptr_t my,              \
                                                int width)                \
{                                                                         \
    hevc_copy_##WIDTH##w_msa(src, src_stride, dst, MAX_PB_SIZE, height);  \
}
Definition at line 3770 of file hevcdsp_msa.c.
MC
#define MC (PEL, DIR, WIDTH, TAP, DIR1, FILT_DIR)
Value:
void ff_hevc_put_hevc_##PEL##_##DIR##WIDTH##_8_msa(int16_t *dst,            \
                                                     uint8_t *src,          \
                                                     ptrdiff_t src_stride,  \
                                                     int height,            \
                                                     intptr_t mx,           \
                                                     intptr_t my,           \
                                                     int width)             \
{                                                                           \
    const int8_t *filter = ff_hevc_##PEL##_filters[FILT_DIR - 1];           \
                                                                            \
    hevc_##DIR1##_##TAP##t_##WIDTH##w_msa(src, src_stride, dst,             \
                                          MAX_PB_SIZE, filter, height);     \
}
Definition at line 3794 of file hevcdsp_msa.c.
MC_HV
#define MC_HV (PEL, DIR, WIDTH, TAP, DIR1)
Value:
void ff_hevc_put_hevc_##PEL##_##DIR##WIDTH##_8_msa(int16_t *dst,              \
                                                     uint8_t *src,            \
                                                     ptrdiff_t src_stride,    \
                                                     int height,              \
                                                     intptr_t mx,             \
                                                     intptr_t my,             \
                                                     int width)               \
{                                                                             \
    const int8_t *filter_x = ff_hevc_##PEL##_filters[mx - 1];                 \
    const int8_t *filter_y = ff_hevc_##PEL##_filters[my - 1];                 \
                                                                              \
    hevc_##DIR1##_##TAP##t_##WIDTH##w_msa(src, src_stride, dst, MAX_PB_SIZE,  \
                                          filter_x, filter_y, height);        \
}
Definition at line 3845 of file hevcdsp_msa.c.
Function Documentation
hevc_copy_4w_msa()
static void hevc_copy_4w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 25 of file hevcdsp_msa.c.
hevc_copy_6w_msa()
static void hevc_copy_6w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 73 of file hevcdsp_msa.c.
hevc_copy_8w_msa()
static void hevc_copy_8w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 97 of file hevcdsp_msa.c.
Referenced by hevc_copy_24w_msa().
hevc_copy_12w_msa()
static void hevc_copy_12w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 158 of file hevcdsp_msa.c.
hevc_copy_16multx8mult_msa()
static void hevc_copy_16multx8mult_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, int32_t height, int32_t width) static
Definition at line 195 of file hevcdsp_msa.c.
Referenced by hevc_copy_16w_msa(), hevc_copy_24w_msa(), hevc_copy_32w_msa(), hevc_copy_48w_msa(), and hevc_copy_64w_msa().
hevc_copy_16w_msa()
static void hevc_copy_16w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 245 of file hevcdsp_msa.c.
hevc_copy_24w_msa()
static void hevc_copy_24w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 310 of file hevcdsp_msa.c.
hevc_copy_32w_msa()
static void hevc_copy_32w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 318 of file hevcdsp_msa.c.
hevc_copy_48w_msa()
static void hevc_copy_48w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 325 of file hevcdsp_msa.c.
hevc_copy_64w_msa()
static void hevc_copy_64w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 332 of file hevcdsp_msa.c.
hevc_hz_8t_4w_msa()
static void hevc_hz_8t_4w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 339 of file hevcdsp_msa.c.
Referenced by hevc_hz_8t_12w_msa().
hevc_hz_8t_8w_msa()
static void hevc_hz_8t_8w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 394 of file hevcdsp_msa.c.
Referenced by hevc_hz_8t_12w_msa().
hevc_hz_8t_12w_msa()
static void hevc_hz_8t_12w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 449 of file hevcdsp_msa.c.
hevc_hz_8t_16w_msa()
static void hevc_hz_8t_16w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 457 of file hevcdsp_msa.c.
hevc_hz_8t_24w_msa()
static void hevc_hz_8t_24w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 534 of file hevcdsp_msa.c.
hevc_hz_8t_32w_msa()
static void hevc_hz_8t_32w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 609 of file hevcdsp_msa.c.
hevc_hz_8t_48w_msa()
static void hevc_hz_8t_48w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 669 of file hevcdsp_msa.c.
hevc_hz_8t_64w_msa()
static void hevc_hz_8t_64w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 739 of file hevcdsp_msa.c.
hevc_vt_8t_4w_msa()
static void hevc_vt_8t_4w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 833 of file hevcdsp_msa.c.
hevc_vt_8t_8w_msa()
static void hevc_vt_8t_8w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 903 of file hevcdsp_msa.c.
Referenced by hevc_vt_8t_24w_msa().
hevc_vt_8t_12w_msa()
static void hevc_vt_8t_12w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 966 of file hevcdsp_msa.c.
hevc_vt_8t_16multx4mult_msa()
static void hevc_vt_8t_16multx4mult_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t width) static
Definition at line 1053 of file hevcdsp_msa.c.
Referenced by hevc_vt_8t_16w_msa(), hevc_vt_8t_24w_msa(), hevc_vt_8t_32w_msa(), hevc_vt_8t_48w_msa(), and hevc_vt_8t_64w_msa().
hevc_vt_8t_16w_msa()
static void hevc_vt_8t_16w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1161 of file hevcdsp_msa.c.
hevc_vt_8t_24w_msa()
static void hevc_vt_8t_24w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1169 of file hevcdsp_msa.c.
hevc_vt_8t_32w_msa()
static void hevc_vt_8t_32w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1179 of file hevcdsp_msa.c.
hevc_vt_8t_48w_msa()
static void hevc_vt_8t_48w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1187 of file hevcdsp_msa.c.
hevc_vt_8t_64w_msa()
static void hevc_vt_8t_64w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1195 of file hevcdsp_msa.c.
hevc_hv_8t_4w_msa()
static void hevc_hv_8t_4w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 1203 of file hevcdsp_msa.c.
Referenced by hevc_hv_8t_12w_msa().
hevc_hv_8t_8multx2mult_msa()
static void hevc_hv_8t_8multx2mult_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t width) static
Definition at line 1305 of file hevcdsp_msa.c.
Referenced by hevc_hv_8t_12w_msa(), hevc_hv_8t_16w_msa(), hevc_hv_8t_24w_msa(), hevc_hv_8t_32w_msa(), hevc_hv_8t_48w_msa(), hevc_hv_8t_64w_msa(), and hevc_hv_8t_8w_msa().
hevc_hv_8t_8w_msa()
static void hevc_hv_8t_8w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 1463 of file hevcdsp_msa.c.
hevc_hv_8t_12w_msa()
static void hevc_hv_8t_12w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 1472 of file hevcdsp_msa.c.
hevc_hv_8t_16w_msa()
static void hevc_hv_8t_16w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 1484 of file hevcdsp_msa.c.
hevc_hv_8t_24w_msa()
static void hevc_hv_8t_24w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 1493 of file hevcdsp_msa.c.
hevc_hv_8t_32w_msa()
static void hevc_hv_8t_32w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 1502 of file hevcdsp_msa.c.
hevc_hv_8t_48w_msa()
static void hevc_hv_8t_48w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 1511 of file hevcdsp_msa.c.
hevc_hv_8t_64w_msa()
static void hevc_hv_8t_64w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 1520 of file hevcdsp_msa.c.
hevc_hz_4t_4x2_msa()
static void hevc_hz_4t_4x2_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter) static
Definition at line 1529 of file hevcdsp_msa.c.
Referenced by hevc_hz_4t_4w_msa().
hevc_hz_4t_4x4_msa()
static void hevc_hz_4t_4x4_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter) static
Definition at line 1562 of file hevcdsp_msa.c.
Referenced by hevc_hz_4t_4w_msa().
hevc_hz_4t_4x8multiple_msa()
static void hevc_hz_4t_4x8multiple_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1599 of file hevcdsp_msa.c.
Referenced by hevc_hz_4t_4w_msa().
hevc_hz_4t_4w_msa()
static void hevc_hz_4t_4w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1648 of file hevcdsp_msa.c.
hevc_hz_4t_6w_msa()
static void hevc_hz_4t_6w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1665 of file hevcdsp_msa.c.
hevc_hz_4t_8x2multiple_msa()
static void hevc_hz_4t_8x2multiple_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1736 of file hevcdsp_msa.c.
Referenced by hevc_hz_4t_8w_msa().
hevc_hz_4t_8x4multiple_msa()
static void hevc_hz_4t_8x4multiple_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1780 of file hevcdsp_msa.c.
Referenced by hevc_hz_4t_8w_msa().
hevc_hz_4t_8w_msa()
static void hevc_hz_4t_8w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1833 of file hevcdsp_msa.c.
hevc_hz_4t_12w_msa()
static void hevc_hz_4t_12w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1849 of file hevcdsp_msa.c.
hevc_hz_4t_16w_msa()
static void hevc_hz_4t_16w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1910 of file hevcdsp_msa.c.
hevc_hz_4t_24w_msa()
static void hevc_hz_4t_24w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 1982 of file hevcdsp_msa.c.
hevc_hz_4t_32w_msa()
static void hevc_hz_4t_32w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2083 of file hevcdsp_msa.c.
hevc_vt_4t_4x2_msa()
static void hevc_vt_4t_4x2_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter) static
Definition at line 2164 of file hevcdsp_msa.c.
Referenced by hevc_vt_4t_4w_msa().
hevc_vt_4t_4x4_msa()
static void hevc_vt_4t_4x4_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2197 of file hevcdsp_msa.c.
Referenced by hevc_vt_4t_4w_msa().
hevc_vt_4t_4x8multiple_msa()
static void hevc_vt_4t_4x8multiple_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2234 of file hevcdsp_msa.c.
Referenced by hevc_vt_4t_4w_msa().
hevc_vt_4t_4w_msa()
static void hevc_vt_4t_4w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2295 of file hevcdsp_msa.c.
hevc_vt_4t_6w_msa()
static void hevc_vt_4t_6w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2312 of file hevcdsp_msa.c.
hevc_vt_4t_8x2_msa()
static void hevc_vt_4t_8x2_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter) static
Definition at line 2386 of file hevcdsp_msa.c.
Referenced by hevc_vt_4t_8w_msa().
hevc_vt_4t_8x6_msa()
static void hevc_vt_4t_8x6_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter) static
Definition at line 2421 of file hevcdsp_msa.c.
Referenced by hevc_vt_4t_8w_msa().
hevc_vt_4t_8x4multiple_msa()
static void hevc_vt_4t_8x4multiple_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2483 of file hevcdsp_msa.c.
Referenced by hevc_vt_4t_8w_msa().
hevc_vt_4t_8w_msa()
static void hevc_vt_4t_8w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2536 of file hevcdsp_msa.c.
hevc_vt_4t_12w_msa()
static void hevc_vt_4t_12w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2553 of file hevcdsp_msa.c.
hevc_vt_4t_16w_msa()
static void hevc_vt_4t_16w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2617 of file hevcdsp_msa.c.
hevc_vt_4t_24w_msa()
static void hevc_vt_4t_24w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2684 of file hevcdsp_msa.c.
hevc_vt_4t_32w_msa()
static void hevc_vt_4t_32w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height) static
Definition at line 2782 of file hevcdsp_msa.c.
hevc_hv_4t_4x2_msa()
static void hevc_hv_4t_4x2_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y) static
Definition at line 2888 of file hevcdsp_msa.c.
Referenced by hevc_hv_4t_4w_msa().
hevc_hv_4t_4x4_msa()
static void hevc_hv_4t_4x4_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y) static
Definition at line 2960 of file hevcdsp_msa.c.
Referenced by hevc_hv_4t_4w_msa().
hevc_hv_4t_4multx8mult_msa()
static void hevc_hv_4t_4multx8mult_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 3052 of file hevcdsp_msa.c.
Referenced by hevc_hv_4t_4w_msa().
hevc_hv_4t_4w_msa()
static void hevc_hv_4t_4w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 3184 of file hevcdsp_msa.c.
Referenced by hevc_hv_4t_12w_msa().
hevc_hv_4t_6w_msa()
static void hevc_hv_4t_6w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 3204 of file hevcdsp_msa.c.
hevc_hv_4t_8x2_msa()
static void hevc_hv_4t_8x2_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 3335 of file hevcdsp_msa.c.
Referenced by hevc_hv_4t_8w_msa().
hevc_hv_4t_8x6_msa()
static void hevc_hv_4t_8x6_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 3417 of file hevcdsp_msa.c.
Referenced by hevc_hv_4t_8w_msa().
hevc_hv_4t_8multx4mult_msa()
static void hevc_hv_4t_8multx4mult_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t width) static
Definition at line 3568 of file hevcdsp_msa.c.
Referenced by hevc_hv_4t_12w_msa(), hevc_hv_4t_16w_msa(), hevc_hv_4t_24w_msa(), hevc_hv_4t_32w_msa(), and hevc_hv_4t_8w_msa().
hevc_hv_4t_8w_msa()
static void hevc_hv_4t_8w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 3697 of file hevcdsp_msa.c.
hevc_hv_4t_12w_msa()
static void hevc_hv_4t_12w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 3718 of file hevcdsp_msa.c.
hevc_hv_4t_16w_msa()
static void hevc_hv_4t_16w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 3734 of file hevcdsp_msa.c.
hevc_hv_4t_24w_msa()
static void hevc_hv_4t_24w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 3746 of file hevcdsp_msa.c.
hevc_hv_4t_32w_msa()
static void hevc_hv_4t_32w_msa (uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height) static
Definition at line 3758 of file hevcdsp_msa.c.
MC_COPY() [1/9]
MC_COPY (4)
MC_COPY() [2/9]
MC_COPY (6)
MC_COPY() [3/9]
MC_COPY (8)
MC_COPY() [4/9]
MC_COPY (12)
MC_COPY() [5/9]
MC_COPY (16)
MC_COPY() [6/9]
MC_COPY (24)
MC_COPY() [7/9]
MC_COPY (32)
MC_COPY() [8/9]
MC_COPY (48)
MC_COPY() [9/9]
MC_COPY (64)
MC() [1/30]
MC (qpel , h , 4 , 8 , hz , mx)
MC() [2/30]
MC (qpel , h , 8 , 8 , hz , mx)
MC() [3/30]
MC (qpel , h , 12 , 8 , hz , mx)
MC() [4/30]
MC (qpel , h , 16 , 8 , hz , mx)
MC() [5/30]
MC (qpel , h , 24 , 8 , hz , mx)
MC() [6/30]
MC (qpel , h , 32 , 8 , hz , mx)
MC() [7/30]
MC (qpel , h , 48 , 8 , hz , mx)
MC() [8/30]
MC (qpel , h , 64 , 8 , hz , mx)
MC() [9/30]
MC (qpel , v , 4 , 8 , vt , my)
MC() [10/30]
MC (qpel , v , 8 , 8 , vt , my)
MC() [11/30]
MC (qpel , v , 12 , 8 , vt , my)
MC() [12/30]
MC (qpel , v , 16 , 8 , vt , my)
MC() [13/30]
MC (qpel , v , 24 , 8 , vt , my)
MC() [14/30]
MC (qpel , v , 32 , 8 , vt , my)
MC() [15/30]
MC (qpel , v , 48 , 8 , vt , my)
MC() [16/30]
MC (qpel , v , 64 , 8 , vt , my)
MC() [17/30]
MC (epel , h , 4 , 4 , hz , mx)
MC() [18/30]
MC (epel , h , 6 , 4 , hz , mx)
MC() [19/30]
MC (epel , h , 8 , 4 , hz , mx)
MC() [20/30]
MC (epel , h , 12 , 4 , hz , mx)
MC() [21/30]
MC (epel , h , 16 , 4 , hz , mx)
MC() [22/30]
MC (epel , h , 24 , 4 , hz , mx)
MC() [23/30]
MC (epel , h , 32 , 4 , hz , mx)
MC() [24/30]
MC (epel , v , 4 , 4 , vt , my)
MC() [25/30]
MC (epel , v , 6 , 4 , vt , my)
MC() [26/30]
MC (epel , v , 8 , 4 , vt , my)
MC() [27/30]
MC (epel , v , 12 , 4 , vt , my)
MC() [28/30]
MC (epel , v , 16 , 4 , vt , my)
MC() [29/30]
MC (epel , v , 24 , 4 , vt , my)
MC() [30/30]
MC (epel , v , 32 , 4 , vt , my)
MC_HV() [1/15]
MC_HV (qpel , hv , 4 , 8 , hv)
MC_HV() [2/15]
MC_HV (qpel , hv , 8 , 8 , hv)
MC_HV() [3/15]
MC_HV (qpel , hv , 12 , 8 , hv)
MC_HV() [4/15]
MC_HV (qpel , hv , 16 , 8 , hv)
MC_HV() [5/15]
MC_HV (qpel , hv , 24 , 8 , hv)
MC_HV() [6/15]
MC_HV (qpel , hv , 32 , 8 , hv)
MC_HV() [7/15]
MC_HV (qpel , hv , 48 , 8 , hv)
MC_HV() [8/15]
MC_HV (qpel , hv , 64 , 8 , hv)
MC_HV() [9/15]
MC_HV (epel , hv , 4 , 4 , hv)
MC_HV() [10/15]
MC_HV (epel , hv , 6 , 4 , hv)
MC_HV() [11/15]
MC_HV (epel , hv , 8 , 4 , hv)
MC_HV() [12/15]
MC_HV (epel , hv , 12 , 4 , hv)
MC_HV() [13/15]
MC_HV (epel , hv , 16 , 4 , hv)
MC_HV() [14/15]
MC_HV (epel , hv , 24 , 4 , hv)
MC_HV() [15/15]
MC_HV (epel , hv , 32 , 4 , hv)