FFmpeg: libavcodec/mips/hevc_mc_uniw_msa.c File Reference
hevc_mc_uniw_msa.c File Reference
#include "libavutil/mips/generic_macros_msa.h"
#include "libavcodec/mips/hevcdsp_mips.h"
#include "libavcodec/mips/hevc_macros_msa.h"
Macros
#define HEVC_HV_UNIW_RND_CLIP4(in0, in1, in2, in3, wgt, offset, rnd, out0, out1, out2, out3)
#define HEVC_UNIW_RND_CLIP2(in0, in1, wgt, offset, rnd, out0_r, out1_r, out0_l, out1_l)
#define HEVC_UNIW_RND_CLIP4(in0, in1, in2, in3, wgt, offset, rnd, out0_r, out1_r, out2_r, out3_r, out0_l, out1_l, out2_l, out3_l)
#define UNIWGT_MC_COPY(WIDTH)
#define UNI_W_MC(PEL, DIR, WIDTH, TAP, DIR1, FILT_DIR)
#define UNI_W_MC_HV(PEL, DIR, WIDTH, TAP, DIR1)
Functions
static void hevc_uniwgt_copy_4w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_uniwgt_copy_6w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_uniwgt_copy_8w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_uniwgt_copy_12w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_uniwgt_copy_16multx4mult_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val, int32_t width)
static void hevc_uniwgt_copy_16w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_uniwgt_copy_24w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_uniwgt_copy_32w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_uniwgt_copy_48w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_uniwgt_copy_64w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hz_uniwgt_8t_4w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hz_uniwgt_8t_8w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hz_uniwgt_8t_12w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hz_uniwgt_8t_16w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hz_uniwgt_8t_24w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hz_uniwgt_8t_32w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hz_uniwgt_8t_48w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hz_uniwgt_8t_64w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_vt_uniwgt_8t_4w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_vt_uniwgt_8t_8w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_vt_uniwgt_8t_12w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_vt_uniwgt_8t_16multx2mult_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val, int32_t width)
static void hevc_vt_uniwgt_8t_16w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_vt_uniwgt_8t_24w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_vt_uniwgt_8t_32w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_vt_uniwgt_8t_48w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_vt_uniwgt_8t_64w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hv_uniwgt_8t_4w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hv_uniwgt_8t_8multx2mult_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val, int32_t width)
static void hevc_hv_uniwgt_8t_8w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hv_uniwgt_8t_12w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hv_uniwgt_8t_16w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hv_uniwgt_8t_24w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hv_uniwgt_8t_32w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hv_uniwgt_8t_48w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hv_uniwgt_8t_64w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hz_uniwgt_4t_4x2_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hz_uniwgt_4t_4x4_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hz_uniwgt_4t_4x8multiple_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hz_uniwgt_4t_4w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hz_uniwgt_4t_6w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hz_uniwgt_4t_8x2_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hz_uniwgt_4t_8x6_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hz_uniwgt_4t_8x4multiple_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hz_uniwgt_4t_8w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hz_uniwgt_4t_12w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hz_uniwgt_4t_16w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hz_uniwgt_4t_24w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hz_uniwgt_4t_32w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_vt_uniwgt_4t_4x2_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_vt_uniwgt_4t_4x4_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_vt_uniwgt_4t_4x8multiple_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_vt_uniwgt_4t_4w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_vt_uniwgt_4t_6w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_vt_uniwgt_4t_8x2_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_vt_uniwgt_4t_8x6_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_vt_uniwgt_4t_8x4multiple_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_vt_uniwgt_4t_8w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_vt_uniwgt_4t_12w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_vt_uniwgt_4t_16w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_vt_uniwgt_4t_24w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_vt_uniwgt_4t_32w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hv_uniwgt_4t_4x2_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hv_uniwgt_4t_4x4_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hv_uniwgt_4t_4multx8mult_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hv_uniwgt_4t_4w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hv_uniwgt_4t_6w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hv_uniwgt_4t_8x2_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hv_uniwgt_4t_8x6_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hv_uniwgt_4t_8multx4mult_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val, int32_t width)
static void hevc_hv_uniwgt_4t_8w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hv_uniwgt_4t_12w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hv_uniwgt_4t_16w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hv_uniwgt_4t_24w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
static void hevc_hv_uniwgt_4t_32w_msa (uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, const int8_t *filter_x, const int8_t *filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val)
UNIWGT_MC_COPY (4)
UNIWGT_MC_COPY (6)
UNIWGT_MC_COPY (8)
UNIWGT_MC_COPY (12)
UNIWGT_MC_COPY (16)
UNIWGT_MC_COPY (24)
UNIWGT_MC_COPY (32)
UNIWGT_MC_COPY (48)
UNIWGT_MC_COPY (64)
UNI_W_MC (qpel, h, 4, 8, hz, mx)
UNI_W_MC (qpel, h, 8, 8, hz, mx)
UNI_W_MC (qpel, h, 12, 8, hz, mx)
UNI_W_MC (qpel, h, 16, 8, hz, mx)
UNI_W_MC (qpel, h, 24, 8, hz, mx)
UNI_W_MC (qpel, h, 32, 8, hz, mx)
UNI_W_MC (qpel, h, 48, 8, hz, mx)
UNI_W_MC (qpel, h, 64, 8, hz, mx)
UNI_W_MC (qpel, v, 4, 8, vt, my)
UNI_W_MC (qpel, v, 8, 8, vt, my)
UNI_W_MC (qpel, v, 12, 8, vt, my)
UNI_W_MC (qpel, v, 16, 8, vt, my)
UNI_W_MC (qpel, v, 24, 8, vt, my)
UNI_W_MC (qpel, v, 32, 8, vt, my)
UNI_W_MC (qpel, v, 48, 8, vt, my)
UNI_W_MC (qpel, v, 64, 8, vt, my)
UNI_W_MC (epel, h, 4, 4, hz, mx)
UNI_W_MC (epel, h, 6, 4, hz, mx)
UNI_W_MC (epel, h, 8, 4, hz, mx)
UNI_W_MC (epel, h, 12, 4, hz, mx)
UNI_W_MC (epel, h, 16, 4, hz, mx)
UNI_W_MC (epel, h, 24, 4, hz, mx)
UNI_W_MC (epel, h, 32, 4, hz, mx)
UNI_W_MC (epel, v, 4, 4, vt, my)
UNI_W_MC (epel, v, 6, 4, vt, my)
UNI_W_MC (epel, v, 8, 4, vt, my)
UNI_W_MC (epel, v, 12, 4, vt, my)
UNI_W_MC (epel, v, 16, 4, vt, my)
UNI_W_MC (epel, v, 24, 4, vt, my)
UNI_W_MC (epel, v, 32, 4, vt, my)
UNI_W_MC_HV (qpel, hv, 4, 8, hv)
UNI_W_MC_HV (qpel, hv, 8, 8, hv)
UNI_W_MC_HV (qpel, hv, 12, 8, hv)
UNI_W_MC_HV (qpel, hv, 16, 8, hv)
UNI_W_MC_HV (qpel, hv, 24, 8, hv)
UNI_W_MC_HV (qpel, hv, 32, 8, hv)
UNI_W_MC_HV (qpel, hv, 48, 8, hv)
UNI_W_MC_HV (qpel, hv, 64, 8, hv)
UNI_W_MC_HV (epel, hv, 4, 4, hv)
UNI_W_MC_HV (epel, hv, 6, 4, hv)
UNI_W_MC_HV (epel, hv, 8, 4, hv)
UNI_W_MC_HV (epel, hv, 12, 4, hv)
UNI_W_MC_HV (epel, hv, 16, 4, hv)
UNI_W_MC_HV (epel, hv, 24, 4, hv)
UNI_W_MC_HV (epel, hv, 32, 4, hv)
Macro Definition Documentation
HEVC_HV_UNIW_RND_CLIP4
#define HEVC_HV_UNIW_RND_CLIP4 (in0, in1, in2, in3, wgt, offset, rnd, out0, out1, out2, out3)
Value:
{                                                                          \
    MUL4(in0, wgt, in1, wgt, in2, wgt, in3, wgt, out0, out1, out2, out3);  \
    SRAR_W4_SW(out0, out1, out2, out3, rnd);                               \
    ADD4(out0, offset, out1, offset, out2, offset, out3, offset,           \
         out0, out1, out2, out3);                                          \
    out0 = CLIP_SW_0_255(out0);                                            \
    out1 = CLIP_SW_0_255(out1);                                            \
    out2 = CLIP_SW_0_255(out2);                                            \
    out3 = CLIP_SW_0_255(out3);                                            \
}
Definition at line 25 of file hevc_mc_uniw_msa.c.
Referenced by hevc_hv_uniwgt_4t_4multx8mult_msa(), hevc_hv_uniwgt_4t_4x4_msa(), hevc_hv_uniwgt_4t_6w_msa(), hevc_hv_uniwgt_4t_8multx4mult_msa(), hevc_hv_uniwgt_4t_8x2_msa(), hevc_hv_uniwgt_4t_8x6_msa(), and hevc_hv_uniwgt_8t_8multx2mult_msa().
HEVC_UNIW_RND_CLIP2
#define HEVC_UNIW_RND_CLIP2 (in0, in1, wgt, offset, rnd, out0_r, out1_r, out0_l, out1_l)
Value:
{                                                                    \
    ILVR_H2_SW(in0, in0, in1, in1, out0_r, out1_r);                  \
    ILVL_H2_SW(in0, in0, in1, in1, out0_l, out1_l);                  \
    DOTP_SH4_SW(out0_r, out1_r, out0_l, out1_l, wgt, wgt, wgt, wgt,  \
                out0_r, out1_r, out0_l, out1_l);                     \
    SRAR_W4_SW(out0_r, out1_r, out0_l, out1_l, rnd);                 \
    ADD4(out0_r, offset, out1_r, offset,                             \
         out0_l, offset, out1_l, offset,                             \
         out0_r, out1_r, out0_l, out1_l);                            \
    out0_r = CLIP_SW_0_255(out0_r);                                  \
    out1_r = CLIP_SW_0_255(out1_r);                                  \
    out0_l = CLIP_SW_0_255(out0_l);                                  \
    out1_l = CLIP_SW_0_255(out1_l);                                  \
}
Definition at line 38 of file hevc_mc_uniw_msa.c.
Referenced by hevc_hz_uniwgt_4t_12w_msa(), hevc_hz_uniwgt_4t_24w_msa(), hevc_hz_uniwgt_4t_4x4_msa(), hevc_hz_uniwgt_4t_8x2_msa(), hevc_hz_uniwgt_4t_8x6_msa(), hevc_hz_uniwgt_8t_24w_msa(), hevc_hz_uniwgt_8t_48w_msa(), hevc_uniwgt_copy_12w_msa(), hevc_uniwgt_copy_4w_msa(), hevc_uniwgt_copy_8w_msa(), hevc_vt_uniwgt_4t_12w_msa(), hevc_vt_uniwgt_4t_24w_msa(), hevc_vt_uniwgt_4t_4x4_msa(), hevc_vt_uniwgt_4t_8x2_msa(), hevc_vt_uniwgt_4t_8x6_msa(), and hevc_vt_uniwgt_8t_12w_msa().
HEVC_UNIW_RND_CLIP4
#define HEVC_UNIW_RND_CLIP4 (in0, in1, in2, in3, wgt, offset, rnd, out0_r, out1_r, out2_r, out3_r, out0_l, out1_l, out2_l, out3_l)
Value:
{                                                                  \
    HEVC_UNIW_RND_CLIP2(in0, in1, wgt, offset, rnd,                \
                        out0_r, out1_r, out0_l, out1_l);           \
    HEVC_UNIW_RND_CLIP2(in2, in3, wgt, offset, rnd,                \
                        out2_r, out3_r, out2_l, out3_l);           \
}
Definition at line 55 of file hevc_mc_uniw_msa.c.
Referenced by hevc_hz_uniwgt_4t_12w_msa(), hevc_hz_uniwgt_4t_16w_msa(), hevc_hz_uniwgt_4t_24w_msa(), hevc_hz_uniwgt_4t_32w_msa(), hevc_hz_uniwgt_4t_4x8multiple_msa(), hevc_hz_uniwgt_4t_6w_msa(), hevc_hz_uniwgt_4t_8x4multiple_msa(), hevc_hz_uniwgt_4t_8x6_msa(), hevc_hz_uniwgt_8t_16w_msa(), hevc_hz_uniwgt_8t_24w_msa(), hevc_hz_uniwgt_8t_32w_msa(), hevc_hz_uniwgt_8t_48w_msa(), hevc_hz_uniwgt_8t_4w_msa(), hevc_hz_uniwgt_8t_64w_msa(), hevc_hz_uniwgt_8t_8w_msa(), hevc_uniwgt_copy_12w_msa(), hevc_uniwgt_copy_16multx4mult_msa(), hevc_uniwgt_copy_4w_msa(), hevc_uniwgt_copy_6w_msa(), hevc_uniwgt_copy_8w_msa(), hevc_vt_uniwgt_4t_12w_msa(), hevc_vt_uniwgt_4t_16w_msa(), hevc_vt_uniwgt_4t_24w_msa(), hevc_vt_uniwgt_4t_32w_msa(), hevc_vt_uniwgt_4t_4x8multiple_msa(), hevc_vt_uniwgt_4t_6w_msa(), hevc_vt_uniwgt_4t_8x4multiple_msa(), hevc_vt_uniwgt_4t_8x6_msa(), hevc_vt_uniwgt_8t_12w_msa(), hevc_vt_uniwgt_8t_16multx2mult_msa(), hevc_vt_uniwgt_8t_4w_msa(), and hevc_vt_uniwgt_8t_8w_msa().
UNIWGT_MC_COPY
#define UNIWGT_MC_COPY (WIDTH)
Value:
void ff_hevc_put_hevc_uni_w_pel_pixels##WIDTH##_8_msa(uint8_t *dst,          \
                                                      ptrdiff_t dst_stride,  \
                                                      uint8_t *src,          \
                                                      ptrdiff_t src_stride,  \
                                                      int height,            \
                                                      int denom,             \
                                                      int weight,            \
                                                      int offset,            \
                                                      intptr_t mx,           \
                                                      intptr_t my,           \
                                                      int width)             \
{                                                                            \
    int shift = denom + 14 - 8;                                              \
    hevc_uniwgt_copy_##WIDTH##w_msa(src, src_stride, dst, dst_stride,        \
                                    height, weight, offset, shift);          \
}
Definition at line 4659 of file hevc_mc_uniw_msa.c.
UNI_W_MC
#define UNI_W_MC (PEL, DIR, WIDTH, TAP, DIR1, FILT_DIR)
Value:
void ff_hevc_put_hevc_uni_w_##PEL##_##DIR##WIDTH##_8_msa(uint8_t *dst,        \
                                                           ptrdiff_t          \
                                                           dst_stride,        \
                                                           uint8_t *src,      \
                                                           ptrdiff_t          \
                                                           src_stride,        \
                                                           int height,        \
                                                           int denom,         \
                                                           int weight,        \
                                                           int offset,        \
                                                           intptr_t mx,       \
                                                           intptr_t my,       \
                                                           int width)         \
{                                                                             \
    const int8_t *filter = ff_hevc_##PEL##_filters[FILT_DIR - 1];             \
    int shift = denom + 14 - 8;                                               \
                                                                              \
    hevc_##DIR1##_uniwgt_##TAP##t_##WIDTH##w_msa(src, src_stride, dst,        \
                                                 dst_stride, filter, height,  \
                                                 weight, offset, shift);      \
}
Definition at line 4689 of file hevc_mc_uniw_msa.c.
UNI_W_MC_HV
#define UNI_W_MC_HV (PEL, DIR, WIDTH, TAP, DIR1)
Value:
void ff_hevc_put_hevc_uni_w_##PEL##_##DIR##WIDTH##_8_msa(uint8_t *dst,       \
                                                           ptrdiff_t         \
                                                           dst_stride,       \
                                                           uint8_t *src,     \
                                                           ptrdiff_t         \
                                                           src_stride,       \
                                                           int height,       \
                                                           int denom,        \
                                                           int weight,       \
                                                           int offset,       \
                                                           intptr_t mx,      \
                                                           intptr_t my,      \
                                                           int width)        \
{                                                                            \
    const int8_t *filter_x = ff_hevc_##PEL##_filters[mx - 1];                \
    const int8_t *filter_y = ff_hevc_##PEL##_filters[my - 1];                \
    int shift = denom + 14 - 8;                                              \
                                                                             \
    hevc_##DIR1##_uniwgt_##TAP##t_##WIDTH##w_msa(src, src_stride, dst,       \
                                                 dst_stride, filter_x,       \
                                                 filter_y,  height, weight,  \
                                                 offset, shift);             \
}
Definition at line 4748 of file hevc_mc_uniw_msa.c.
Function Documentation
hevc_uniwgt_copy_4w_msa()
static void hevc_uniwgt_copy_4w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 65 of file hevc_mc_uniw_msa.c.
hevc_uniwgt_copy_6w_msa()
static void hevc_uniwgt_copy_6w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 148 of file hevc_mc_uniw_msa.c.
hevc_uniwgt_copy_8w_msa()
static void hevc_uniwgt_copy_8w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 202 of file hevc_mc_uniw_msa.c.
Referenced by hevc_uniwgt_copy_24w_msa().
hevc_uniwgt_copy_12w_msa()
static void hevc_uniwgt_copy_12w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 288 of file hevc_mc_uniw_msa.c.
hevc_uniwgt_copy_16multx4mult_msa()
static void hevc_uniwgt_copy_16multx4mult_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val, int32_t width) static
Definition at line 337 of file hevc_mc_uniw_msa.c.
Referenced by hevc_uniwgt_copy_16w_msa(), hevc_uniwgt_copy_24w_msa(), hevc_uniwgt_copy_32w_msa(), hevc_uniwgt_copy_48w_msa(), and hevc_uniwgt_copy_64w_msa().
hevc_uniwgt_copy_16w_msa()
static void hevc_uniwgt_copy_16w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 404 of file hevc_mc_uniw_msa.c.
hevc_uniwgt_copy_24w_msa()
static void hevc_uniwgt_copy_24w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 417 of file hevc_mc_uniw_msa.c.
hevc_uniwgt_copy_32w_msa()
static void hevc_uniwgt_copy_32w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 433 of file hevc_mc_uniw_msa.c.
hevc_uniwgt_copy_48w_msa()
static void hevc_uniwgt_copy_48w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 446 of file hevc_mc_uniw_msa.c.
hevc_uniwgt_copy_64w_msa()
static void hevc_uniwgt_copy_64w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 459 of file hevc_mc_uniw_msa.c.
hevc_hz_uniwgt_8t_4w_msa()
static void hevc_hz_uniwgt_8t_4w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 472 of file hevc_mc_uniw_msa.c.
Referenced by hevc_hz_uniwgt_8t_12w_msa().
hevc_hz_uniwgt_8t_8w_msa()
static void hevc_hz_uniwgt_8t_8w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 548 of file hevc_mc_uniw_msa.c.
Referenced by hevc_hz_uniwgt_8t_12w_msa().
hevc_hz_uniwgt_8t_12w_msa()
static void hevc_hz_uniwgt_8t_12w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 623 of file hevc_mc_uniw_msa.c.
hevc_hz_uniwgt_8t_16w_msa()
static void hevc_hz_uniwgt_8t_16w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 639 of file hevc_mc_uniw_msa.c.
hevc_hz_uniwgt_8t_24w_msa()
static void hevc_hz_uniwgt_8t_24w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 715 of file hevc_mc_uniw_msa.c.
hevc_hz_uniwgt_8t_32w_msa()
static void hevc_hz_uniwgt_8t_32w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 811 of file hevc_mc_uniw_msa.c.
hevc_hz_uniwgt_8t_48w_msa()
static void hevc_hz_uniwgt_8t_48w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 891 of file hevc_mc_uniw_msa.c.
hevc_hz_uniwgt_8t_64w_msa()
static void hevc_hz_uniwgt_8t_64w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 988 of file hevc_mc_uniw_msa.c.
hevc_vt_uniwgt_8t_4w_msa()
static void hevc_vt_uniwgt_8t_4w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 1078 of file hevc_mc_uniw_msa.c.
hevc_vt_uniwgt_8t_8w_msa()
static void hevc_vt_uniwgt_8t_8w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 1170 of file hevc_mc_uniw_msa.c.
Referenced by hevc_vt_uniwgt_8t_24w_msa().
hevc_vt_uniwgt_8t_12w_msa()
static void hevc_vt_uniwgt_8t_12w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 1250 of file hevc_mc_uniw_msa.c.
hevc_vt_uniwgt_8t_16multx2mult_msa()
static void hevc_vt_uniwgt_8t_16multx2mult_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val, int32_t width) static
Definition at line 1356 of file hevc_mc_uniw_msa.c.
Referenced by hevc_vt_uniwgt_8t_16w_msa(), hevc_vt_uniwgt_8t_24w_msa(), hevc_vt_uniwgt_8t_32w_msa(), hevc_vt_uniwgt_8t_48w_msa(), and hevc_vt_uniwgt_8t_64w_msa().
hevc_vt_uniwgt_8t_16w_msa()
static void hevc_vt_uniwgt_8t_16w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 1457 of file hevc_mc_uniw_msa.c.
hevc_vt_uniwgt_8t_24w_msa()
static void hevc_vt_uniwgt_8t_24w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 1472 of file hevc_mc_uniw_msa.c.
hevc_vt_uniwgt_8t_32w_msa()
static void hevc_vt_uniwgt_8t_32w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 1490 of file hevc_mc_uniw_msa.c.
hevc_vt_uniwgt_8t_48w_msa()
static void hevc_vt_uniwgt_8t_48w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 1505 of file hevc_mc_uniw_msa.c.
hevc_vt_uniwgt_8t_64w_msa()
static void hevc_vt_uniwgt_8t_64w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 1520 of file hevc_mc_uniw_msa.c.
hevc_hv_uniwgt_8t_4w_msa()
static void hevc_hv_uniwgt_8t_4w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 1535 of file hevc_mc_uniw_msa.c.
Referenced by hevc_hv_uniwgt_8t_12w_msa().
hevc_hv_uniwgt_8t_8multx2mult_msa()
static void hevc_hv_uniwgt_8t_8multx2mult_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val, int32_t width) static
Definition at line 1654 of file hevc_mc_uniw_msa.c.
Referenced by hevc_hv_uniwgt_8t_12w_msa(), hevc_hv_uniwgt_8t_16w_msa(), hevc_hv_uniwgt_8t_24w_msa(), hevc_hv_uniwgt_8t_32w_msa(), hevc_hv_uniwgt_8t_48w_msa(), hevc_hv_uniwgt_8t_64w_msa(), and hevc_hv_uniwgt_8t_8w_msa().
hevc_hv_uniwgt_8t_8w_msa()
static void hevc_hv_uniwgt_8t_8w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 1819 of file hevc_mc_uniw_msa.c.
hevc_hv_uniwgt_8t_12w_msa()
static void hevc_hv_uniwgt_8t_12w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 1835 of file hevc_mc_uniw_msa.c.
hevc_hv_uniwgt_8t_16w_msa()
static void hevc_hv_uniwgt_8t_16w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 1854 of file hevc_mc_uniw_msa.c.
hevc_hv_uniwgt_8t_24w_msa()
static void hevc_hv_uniwgt_8t_24w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 1870 of file hevc_mc_uniw_msa.c.
hevc_hv_uniwgt_8t_32w_msa()
static void hevc_hv_uniwgt_8t_32w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 1886 of file hevc_mc_uniw_msa.c.
hevc_hv_uniwgt_8t_48w_msa()
static void hevc_hv_uniwgt_8t_48w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 1902 of file hevc_mc_uniw_msa.c.
hevc_hv_uniwgt_8t_64w_msa()
static void hevc_hv_uniwgt_8t_64w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 1918 of file hevc_mc_uniw_msa.c.
hevc_hz_uniwgt_4t_4x2_msa()
static void hevc_hz_uniwgt_4t_4x2_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 1934 of file hevc_mc_uniw_msa.c.
Referenced by hevc_hz_uniwgt_4t_4w_msa().
hevc_hz_uniwgt_4t_4x4_msa()
static void hevc_hz_uniwgt_4t_4x4_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 1988 of file hevc_mc_uniw_msa.c.
Referenced by hevc_hz_uniwgt_4t_4w_msa().
hevc_hz_uniwgt_4t_4x8multiple_msa()
static void hevc_hz_uniwgt_4t_4x8multiple_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 2043 of file hevc_mc_uniw_msa.c.
Referenced by hevc_hz_uniwgt_4t_4w_msa().
hevc_hz_uniwgt_4t_4w_msa()
static void hevc_hz_uniwgt_4t_4w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 2112 of file hevc_mc_uniw_msa.c.
hevc_hz_uniwgt_4t_6w_msa()
static void hevc_hz_uniwgt_4t_6w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 2135 of file hevc_mc_uniw_msa.c.
hevc_hz_uniwgt_4t_8x2_msa()
static void hevc_hz_uniwgt_4t_8x2_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 2206 of file hevc_mc_uniw_msa.c.
Referenced by hevc_hz_uniwgt_4t_8w_msa().
hevc_hz_uniwgt_4t_8x6_msa()
static void hevc_hz_uniwgt_4t_8x6_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 2257 of file hevc_mc_uniw_msa.c.
Referenced by hevc_hz_uniwgt_4t_8w_msa().
hevc_hz_uniwgt_4t_8x4multiple_msa()
static void hevc_hz_uniwgt_4t_8x4multiple_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 2338 of file hevc_mc_uniw_msa.c.
Referenced by hevc_hz_uniwgt_4t_8w_msa().
hevc_hz_uniwgt_4t_8w_msa()
static void hevc_hz_uniwgt_4t_8w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 2409 of file hevc_mc_uniw_msa.c.
hevc_hz_uniwgt_4t_12w_msa()
static void hevc_hz_uniwgt_4t_12w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 2432 of file hevc_mc_uniw_msa.c.
hevc_hz_uniwgt_4t_16w_msa()
static void hevc_hz_uniwgt_4t_16w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 2521 of file hevc_mc_uniw_msa.c.
hevc_hz_uniwgt_4t_24w_msa()
static void hevc_hz_uniwgt_4t_24w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 2618 of file hevc_mc_uniw_msa.c.
hevc_hz_uniwgt_4t_32w_msa()
static void hevc_hz_uniwgt_4t_32w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 2709 of file hevc_mc_uniw_msa.c.
hevc_vt_uniwgt_4t_4x2_msa()
static void hevc_vt_uniwgt_4t_4x2_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 2814 of file hevc_mc_uniw_msa.c.
Referenced by hevc_vt_uniwgt_4t_4w_msa().
hevc_vt_uniwgt_4t_4x4_msa()
static void hevc_vt_uniwgt_4t_4x4_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 2870 of file hevc_mc_uniw_msa.c.
Referenced by hevc_vt_uniwgt_4t_4w_msa().
hevc_vt_uniwgt_4t_4x8multiple_msa()
static void hevc_vt_uniwgt_4t_4x8multiple_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 2926 of file hevc_mc_uniw_msa.c.
Referenced by hevc_vt_uniwgt_4t_4w_msa().
hevc_vt_uniwgt_4t_4w_msa()
static void hevc_vt_uniwgt_4t_4w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 3003 of file hevc_mc_uniw_msa.c.
hevc_vt_uniwgt_4t_6w_msa()
static void hevc_vt_uniwgt_4t_6w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 3026 of file hevc_mc_uniw_msa.c.
hevc_vt_uniwgt_4t_8x2_msa()
static void hevc_vt_uniwgt_4t_8x2_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 3096 of file hevc_mc_uniw_msa.c.
Referenced by hevc_vt_uniwgt_4t_8w_msa().
hevc_vt_uniwgt_4t_8x6_msa()
static void hevc_vt_uniwgt_4t_8x6_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 3146 of file hevc_mc_uniw_msa.c.
Referenced by hevc_vt_uniwgt_4t_8w_msa().
hevc_vt_uniwgt_4t_8x4multiple_msa()
static void hevc_vt_uniwgt_4t_8x4multiple_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 3217 of file hevc_mc_uniw_msa.c.
Referenced by hevc_vt_uniwgt_4t_8w_msa().
hevc_vt_uniwgt_4t_8w_msa()
static void hevc_vt_uniwgt_4t_8w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 3286 of file hevc_mc_uniw_msa.c.
hevc_vt_uniwgt_4t_12w_msa()
static void hevc_vt_uniwgt_4t_12w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 3309 of file hevc_mc_uniw_msa.c.
hevc_vt_uniwgt_4t_16w_msa()
static void hevc_vt_uniwgt_4t_16w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 3395 of file hevc_mc_uniw_msa.c.
hevc_vt_uniwgt_4t_24w_msa()
static void hevc_vt_uniwgt_4t_24w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 3485 of file hevc_mc_uniw_msa.c.
hevc_vt_uniwgt_4t_32w_msa()
static void hevc_vt_uniwgt_4t_32w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 3606 of file hevc_mc_uniw_msa.c.
hevc_hv_uniwgt_4t_4x2_msa()
static void hevc_hv_uniwgt_4t_4x2_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 3717 of file hevc_mc_uniw_msa.c.
Referenced by hevc_hv_uniwgt_4t_4w_msa().
hevc_hv_uniwgt_4t_4x4_msa()
static void hevc_hv_uniwgt_4t_4x4_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 3805 of file hevc_mc_uniw_msa.c.
Referenced by hevc_hv_uniwgt_4t_4w_msa().
hevc_hv_uniwgt_4t_4multx8mult_msa()
static void hevc_hv_uniwgt_4t_4multx8mult_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 3906 of file hevc_mc_uniw_msa.c.
Referenced by hevc_hv_uniwgt_4t_4w_msa().
hevc_hv_uniwgt_4t_4w_msa()
static void hevc_hv_uniwgt_4t_4w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 4044 of file hevc_mc_uniw_msa.c.
Referenced by hevc_hv_uniwgt_4t_12w_msa().
hevc_hv_uniwgt_4t_6w_msa()
static void hevc_hv_uniwgt_4t_6w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 4070 of file hevc_mc_uniw_msa.c.
hevc_hv_uniwgt_4t_8x2_msa()
static void hevc_hv_uniwgt_4t_8x2_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 4191 of file hevc_mc_uniw_msa.c.
Referenced by hevc_hv_uniwgt_4t_8w_msa().
hevc_hv_uniwgt_4t_8x6_msa()
static void hevc_hv_uniwgt_4t_8x6_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 4282 of file hevc_mc_uniw_msa.c.
Referenced by hevc_hv_uniwgt_4t_8w_msa().
hevc_hv_uniwgt_4t_8multx4mult_msa()
static void hevc_hv_uniwgt_4t_8multx4mult_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val, int32_t width) static
Definition at line 4437 of file hevc_mc_uniw_msa.c.
Referenced by hevc_hv_uniwgt_4t_12w_msa(), hevc_hv_uniwgt_4t_16w_msa(), hevc_hv_uniwgt_4t_24w_msa(), hevc_hv_uniwgt_4t_32w_msa(), and hevc_hv_uniwgt_4t_8w_msa().
hevc_hv_uniwgt_4t_8w_msa()
static void hevc_hv_uniwgt_4t_8w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 4565 of file hevc_mc_uniw_msa.c.
hevc_hv_uniwgt_4t_12w_msa()
static void hevc_hv_uniwgt_4t_12w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 4592 of file hevc_mc_uniw_msa.c.
hevc_hv_uniwgt_4t_16w_msa()
static void hevc_hv_uniwgt_4t_16w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 4611 of file hevc_mc_uniw_msa.c.
hevc_hv_uniwgt_4t_24w_msa()
static void hevc_hv_uniwgt_4t_24w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 4627 of file hevc_mc_uniw_msa.c.
hevc_hv_uniwgt_4t_32w_msa()
static void hevc_hv_uniwgt_4t_32w_msa (uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, const int8_t * filter_x, const int8_t * filter_y, int32_t height, int32_t weight, int32_t offset, int32_t rnd_val) static
Definition at line 4643 of file hevc_mc_uniw_msa.c.
UNIWGT_MC_COPY() [1/9]
UNIWGT_MC_COPY (4)
UNIWGT_MC_COPY() [2/9]
UNIWGT_MC_COPY (6)
UNIWGT_MC_COPY() [3/9]
UNIWGT_MC_COPY (8)
UNIWGT_MC_COPY() [4/9]
UNIWGT_MC_COPY (12)
UNIWGT_MC_COPY() [5/9]
UNIWGT_MC_COPY (16)
UNIWGT_MC_COPY() [6/9]
UNIWGT_MC_COPY (24)
UNIWGT_MC_COPY() [7/9]
UNIWGT_MC_COPY (32)
UNIWGT_MC_COPY() [8/9]
UNIWGT_MC_COPY (48)
UNIWGT_MC_COPY() [9/9]
UNIWGT_MC_COPY (64)
UNI_W_MC() [1/30]
UNI_W_MC (qpel , h , 4 , 8 , hz , mx)
UNI_W_MC() [2/30]
UNI_W_MC (qpel , h , 8 , 8 , hz , mx)
UNI_W_MC() [3/30]
UNI_W_MC (qpel , h , 12 , 8 , hz , mx)
UNI_W_MC() [4/30]
UNI_W_MC (qpel , h , 16 , 8 , hz , mx)
UNI_W_MC() [5/30]
UNI_W_MC (qpel , h , 24 , 8 , hz , mx)
UNI_W_MC() [6/30]
UNI_W_MC (qpel , h , 32 , 8 , hz , mx)
UNI_W_MC() [7/30]
UNI_W_MC (qpel , h , 48 , 8 , hz , mx)
UNI_W_MC() [8/30]
UNI_W_MC (qpel , h , 64 , 8 , hz , mx)
UNI_W_MC() [9/30]
UNI_W_MC (qpel , v , 4 , 8 , vt , my)
UNI_W_MC() [10/30]
UNI_W_MC (qpel , v , 8 , 8 , vt , my)
UNI_W_MC() [11/30]
UNI_W_MC (qpel , v , 12 , 8 , vt , my)
UNI_W_MC() [12/30]
UNI_W_MC (qpel , v , 16 , 8 , vt , my)
UNI_W_MC() [13/30]
UNI_W_MC (qpel , v , 24 , 8 , vt , my)
UNI_W_MC() [14/30]
UNI_W_MC (qpel , v , 32 , 8 , vt , my)
UNI_W_MC() [15/30]
UNI_W_MC (qpel , v , 48 , 8 , vt , my)
UNI_W_MC() [16/30]
UNI_W_MC (qpel , v , 64 , 8 , vt , my)
UNI_W_MC() [17/30]
UNI_W_MC (epel , h , 4 , 4 , hz , mx)
UNI_W_MC() [18/30]
UNI_W_MC (epel , h , 6 , 4 , hz , mx)
UNI_W_MC() [19/30]
UNI_W_MC (epel , h , 8 , 4 , hz , mx)
UNI_W_MC() [20/30]
UNI_W_MC (epel , h , 12 , 4 , hz , mx)
UNI_W_MC() [21/30]
UNI_W_MC (epel , h , 16 , 4 , hz , mx)
UNI_W_MC() [22/30]
UNI_W_MC (epel , h , 24 , 4 , hz , mx)
UNI_W_MC() [23/30]
UNI_W_MC (epel , h , 32 , 4 , hz , mx)
UNI_W_MC() [24/30]
UNI_W_MC (epel , v , 4 , 4 , vt , my)
UNI_W_MC() [25/30]
UNI_W_MC (epel , v , 6 , 4 , vt , my)
UNI_W_MC() [26/30]
UNI_W_MC (epel , v , 8 , 4 , vt , my)
UNI_W_MC() [27/30]
UNI_W_MC (epel , v , 12 , 4 , vt , my)
UNI_W_MC() [28/30]
UNI_W_MC (epel , v , 16 , 4 , vt , my)
UNI_W_MC() [29/30]
UNI_W_MC (epel , v , 24 , 4 , vt , my)
UNI_W_MC() [30/30]
UNI_W_MC (epel , v , 32 , 4 , vt , my)
UNI_W_MC_HV() [1/15]
UNI_W_MC_HV (qpel , hv , 4 , 8 , hv)
UNI_W_MC_HV() [2/15]
UNI_W_MC_HV (qpel , hv , 8 , 8 , hv)
UNI_W_MC_HV() [3/15]
UNI_W_MC_HV (qpel , hv , 12 , 8 , hv)
UNI_W_MC_HV() [4/15]
UNI_W_MC_HV (qpel , hv , 16 , 8 , hv)
UNI_W_MC_HV() [5/15]
UNI_W_MC_HV (qpel , hv , 24 , 8 , hv)
UNI_W_MC_HV() [6/15]
UNI_W_MC_HV (qpel , hv , 32 , 8 , hv)
UNI_W_MC_HV() [7/15]
UNI_W_MC_HV (qpel , hv , 48 , 8 , hv)
UNI_W_MC_HV() [8/15]
UNI_W_MC_HV (qpel , hv , 64 , 8 , hv)
UNI_W_MC_HV() [9/15]
UNI_W_MC_HV (epel , hv , 4 , 4 , hv)
UNI_W_MC_HV() [10/15]
UNI_W_MC_HV (epel , hv , 6 , 4 , hv)
UNI_W_MC_HV() [11/15]
UNI_W_MC_HV (epel , hv , 8 , 4 , hv)
UNI_W_MC_HV() [12/15]
UNI_W_MC_HV (epel , hv , 12 , 4 , hv)
UNI_W_MC_HV() [13/15]
UNI_W_MC_HV (epel , hv , 16 , 4 , hv)
UNI_W_MC_HV() [14/15]
UNI_W_MC_HV (epel , hv , 24 , 4 , hv)
UNI_W_MC_HV() [15/15]
UNI_W_MC_HV (epel , hv , 32 , 4 , hv)