FFmpeg: libavcodec/hevc_parser.c File Reference
hevc_parser.c File Reference
#include "libavutil/common.h"
#include "golomb.h"
#include "hevc.h"
#include "h2645_parse.h"
#include "parser.h"
Data Structures
struct HEVCParserContext
Macros
#define START_CODE 0x000001
start_code_prefix_one_3bytes
#define IS_IRAP_NAL(nal) (nal->type >= 16 && nal->type <= 23)
#define ADVANCED_PARSER CONFIG_HEVC_DECODER
Functions
static int hevc_parse_slice_header (AVCodecParserContext *s, H2645NAL *nal, AVCodecContext *avctx)
static int parse_nal_units (AVCodecParserContext *s, const uint8_t *buf, int buf_size, AVCodecContext *avctx)
static int hevc_find_frame_end (AVCodecParserContext *s, const uint8_t *buf, int buf_size)
Find the end of the current frame in the bitstream.
static int hevc_parse (AVCodecParserContext *s, AVCodecContext *avctx, const uint8_t **poutbuf, int *poutbuf_size, const uint8_t *buf, int buf_size)
static int hevc_split (AVCodecContext *avctx, const uint8_t *buf, int buf_size)
static void hevc_parser_close (AVCodecParserContext *s)
Variables
AVCodecParser ff_hevc_parser
Macro Definition Documentation
START_CODE
#define START_CODE 0x000001
start_code_prefix_one_3bytes
Definition at line 30 of file hevc_parser.c.
Referenced by hevc_find_frame_end(), and hevc_split().
IS_IRAP_NAL
#define IS_IRAP_NAL (nal) (nal->type >= 16 && nal->type <= 23)
Definition at line 32 of file hevc_parser.c.
Referenced by hevc_parse_slice_header().
ADVANCED_PARSER
#define ADVANCED_PARSER CONFIG_HEVC_DECODER
Definition at line 34 of file hevc_parser.c.
Function Documentation
hevc_parse_slice_header()
static int hevc_parse_slice_header (AVCodecParserContext * s, H2645NAL * nal, AVCodecContext * avctx) static
Definition at line 50 of file hevc_parser.c.
Referenced by parse_nal_units().
parse_nal_units()
static int parse_nal_units (AVCodecParserContext * s, const uint8_t * buf, int buf_size, AVCodecContext * avctx) static
Definition at line 86 of file hevc_parser.c.
Referenced by hevc_find_frame_end(), and hevc_parse().
hevc_find_frame_end()
static int hevc_find_frame_end (AVCodecParserContext * s, const uint8_t * buf, int buf_size) static
Find the end of the current frame in the bitstream.
Returns
the position of the first byte of the next frame, or END_NOT_FOUND
Definition at line 138 of file hevc_parser.c.
Referenced by hevc_parse().
hevc_parse()
static int hevc_parse (AVCodecParserContext * s, AVCodecContext * avctx, const uint8_t ** poutbuf, int * poutbuf_size, const uint8_t * buf, int buf_size) static
Definition at line 392 of file hevc_parser.c.
hevc_split()
static int hevc_split (AVCodecContext * avctx, const uint8_t * buf, int buf_size) static
Definition at line 425 of file hevc_parser.c.
hevc_parser_close()
static void hevc_parser_close (AVCodecParserContext * s) static
Definition at line 457 of file hevc_parser.c.
Variable Documentation
ff_hevc_parser
AVCodecParser ff_hevc_parser
Initial value:
= {
    .codec_ids      = { AV_CODEC_ID_HEVC },
    .priv_data_size = sizeof(HEVCParserContext),
    .parser_parse   = hevc_parse,
    .parser_close   = hevc_parser_close,
    .split          = hevc_split,
}
Definition at line 491 of file hevc_parser.c.