FFmpeg: libavcodec/hevc_sei.c File Reference
hevc_sei.c File Reference
#include "golomb.h"
#include "hevc.h"
Enumerations
enum HEVC_SEI_TYPE {
SEI_TYPE_BUFFERING_PERIOD = 0, SEI_TYPE_PICTURE_TIMING = 1, SEI_TYPE_PAN_SCAN_RECT = 2, SEI_TYPE_FILLER_PAYLOAD = 3,
SEI_TYPE_USER_DATA_REGISTERED_ITU_T_T35 = 4, SEI_TYPE_USER_DATA_UNREGISTERED = 5, SEI_TYPE_RECOVERY_POINT = 6, SEI_TYPE_SCENE_INFO = 9,
SEI_TYPE_FULL_FRAME_SNAPSHOT = 15, SEI_TYPE_PROGRESSIVE_REFINEMENT_SEGMENT_START = 16, SEI_TYPE_PROGRESSIVE_REFINEMENT_SEGMENT_END = 17, SEI_TYPE_FILM_GRAIN_CHARACTERISTICS = 19,
SEI_TYPE_POST_FILTER_HINT = 22, SEI_TYPE_TONE_MAPPING_INFO = 23, SEI_TYPE_FRAME_PACKING = 45, SEI_TYPE_DISPLAY_ORIENTATION = 47,
SEI_TYPE_SOP_DESCRIPTION = 128, SEI_TYPE_ACTIVE_PARAMETER_SETS = 129, SEI_TYPE_DECODING_UNIT_INFO = 130, SEI_TYPE_TEMPORAL_LEVEL0_INDEX = 131,
SEI_TYPE_DECODED_PICTURE_HASH = 132, SEI_TYPE_SCALABLE_NESTING = 133, SEI_TYPE_REGION_REFRESH_INFO = 134, SEI_TYPE_MASTERING_DISPLAY_INFO = 137,
SEI_TYPE_CONTENT_LIGHT_LEVEL_INFO = 144
}
Functions
static int decode_nal_sei_decoded_picture_hash (HEVCContext *s)
static int decode_nal_sei_mastering_display_info (HEVCContext *s)
static int decode_nal_sei_frame_packing_arrangement (HEVCContext *s)
static int decode_nal_sei_display_orientation (HEVCContext *s)
static int decode_pic_timing (HEVCContext *s)
static int decode_registered_user_data_closed_caption (HEVCContext *s, int size)
static int decode_nal_sei_user_data_registered_itu_t_t35 (HEVCContext *s, int size)
static int active_parameter_sets (HEVCContext *s)
static int decode_nal_sei_prefix (HEVCContext *s, int type, int size)
static int decode_nal_sei_suffix (HEVCContext *s, int type, int size)
static int decode_nal_sei_message (HEVCContext *s)
static int more_rbsp_data (GetBitContext *gb)
int ff_hevc_decode_nal_sei (HEVCContext *s)
void ff_hevc_reset_sei (HEVCContext *s)
Reset SEI values that are stored on the Context.
Enumeration Type Documentation
HEVC_SEI_TYPE
enum HEVC_SEI_TYPE
Enumerator
SEI_TYPE_BUFFERING_PERIOD
SEI_TYPE_PICTURE_TIMING
SEI_TYPE_PAN_SCAN_RECT
SEI_TYPE_FILLER_PAYLOAD
SEI_TYPE_USER_DATA_REGISTERED_ITU_T_T35
SEI_TYPE_USER_DATA_UNREGISTERED
SEI_TYPE_RECOVERY_POINT
SEI_TYPE_SCENE_INFO
SEI_TYPE_FULL_FRAME_SNAPSHOT
SEI_TYPE_PROGRESSIVE_REFINEMENT_SEGMENT_START
SEI_TYPE_PROGRESSIVE_REFINEMENT_SEGMENT_END
SEI_TYPE_FILM_GRAIN_CHARACTERISTICS
SEI_TYPE_POST_FILTER_HINT
SEI_TYPE_TONE_MAPPING_INFO
SEI_TYPE_FRAME_PACKING
SEI_TYPE_DISPLAY_ORIENTATION
SEI_TYPE_SOP_DESCRIPTION
SEI_TYPE_ACTIVE_PARAMETER_SETS
SEI_TYPE_DECODING_UNIT_INFO
SEI_TYPE_TEMPORAL_LEVEL0_INDEX
SEI_TYPE_DECODED_PICTURE_HASH
SEI_TYPE_SCALABLE_NESTING
SEI_TYPE_REGION_REFRESH_INFO
SEI_TYPE_MASTERING_DISPLAY_INFO
SEI_TYPE_CONTENT_LIGHT_LEVEL_INFO
Definition at line 28 of file hevc_sei.c.
Function Documentation
decode_nal_sei_decoded_picture_hash()
static int decode_nal_sei_decoded_picture_hash (HEVCContext * s) static
Definition at line 56 of file hevc_sei.c.
Referenced by decode_nal_sei_prefix(), and decode_nal_sei_suffix().
decode_nal_sei_mastering_display_info()
static int decode_nal_sei_mastering_display_info (HEVCContext * s) static
Definition at line 81 of file hevc_sei.c.
Referenced by decode_nal_sei_prefix().
decode_nal_sei_frame_packing_arrangement()
static int decode_nal_sei_frame_packing_arrangement (HEVCContext * s) static
Definition at line 105 of file hevc_sei.c.
Referenced by decode_nal_sei_prefix().
decode_nal_sei_display_orientation()
static int decode_nal_sei_display_orientation (HEVCContext * s) static
Definition at line 131 of file hevc_sei.c.
Referenced by decode_nal_sei_prefix().
decode_pic_timing()
static int decode_pic_timing (HEVCContext * s) static
Definition at line 148 of file hevc_sei.c.
Referenced by decode_nal_sei_prefix().
decode_registered_user_data_closed_caption()
static int decode_registered_user_data_closed_caption (HEVCContext * s, int size) static
Definition at line 173 of file hevc_sei.c.
Referenced by decode_nal_sei_user_data_registered_itu_t_t35().
decode_nal_sei_user_data_registered_itu_t_t35()
static int decode_nal_sei_user_data_registered_itu_t_t35 (HEVCContext * s, int size) static
Definition at line 225 of file hevc_sei.c.
Referenced by decode_nal_sei_prefix().
active_parameter_sets()
static int active_parameter_sets (HEVCContext * s) static
Definition at line 257 of file hevc_sei.c.
Referenced by decode_nal_sei_prefix().
decode_nal_sei_prefix()
static int decode_nal_sei_prefix (HEVCContext * s, int type, int size) static
Definition at line 287 of file hevc_sei.c.
Referenced by decode_nal_sei_message().
decode_nal_sei_suffix()
static int decode_nal_sei_suffix (HEVCContext * s, int type, int size) static
Definition at line 320 of file hevc_sei.c.
Referenced by decode_nal_sei_message().
decode_nal_sei_message()
static int decode_nal_sei_message (HEVCContext * s) static
Definition at line 334 of file hevc_sei.c.
Referenced by ff_hevc_decode_nal_sei().
more_rbsp_data()
static int more_rbsp_data (GetBitContext * gb) static
Definition at line 360 of file hevc_sei.c.
Referenced by ff_hevc_decode_nal_sei().
ff_hevc_decode_nal_sei()
int ff_hevc_decode_nal_sei (HEVCContext * s)
Definition at line 365 of file hevc_sei.c.
Referenced by decode_nal_unit(), and hevc_find_frame_end().
ff_hevc_reset_sei()
void ff_hevc_reset_sei (HEVCContext * s)
Reset SEI values that are stored on the Context.
e.g. Caption data that was extracted during NAL parsing.
Parameters
s HEVCContext.
Definition at line 377 of file hevc_sei.c.
Referenced by hevc_find_frame_end(), and hevc_init_context().