FFmpeg: libavformat/hls.c File Reference
hls.c File Reference
Apple HTTP Live Streaming demuxer http://tools.ietf.org/html/draft-pantos-http-live-streaming.
#include "libavutil/avstring.h"
#include "libavutil/avassert.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/mathematics.h"
#include "libavutil/opt.h"
#include "libavutil/dict.h"
#include "libavutil/time.h"
#include "avformat.h"
#include "internal.h"
#include "avio_internal.h"
#include "id3v2.h"
Data Structures
struct segment
struct playlist
struct rendition
struct variant
struct HLSContext
struct variant_info
struct key_info
struct init_section_info
struct rendition_info
Macros
#define INITIAL_BUFFER_SIZE 32768
#define MAX_FIELD_LEN 64
#define MAX_CHARACTERISTICS_LEN 512
#define MPEG_TIME_BASE 90000
#define MPEG_TIME_BASE_Q (AVRational){1, MPEG_TIME_BASE}
#define OFFSET(x) offsetof(HLSContext, x)
#define FLAGS AV_OPT_FLAG_DECODING_PARAM
Enumerations
enum KeyType { KEY_NONE, KEY_AES_128, KEY_SAMPLE_AES }
enum PlaylistType {
PLS_TYPE_UNSPECIFIED, PLS_TYPE_EVENT, PLS_TYPE_VOD, PLAYLIST_TYPE_NONE,
PLAYLIST_TYPE_EVENT, PLAYLIST_TYPE_VOD, PLAYLIST_TYPE_NB
}
enum ReadFromURLMode { READ_NORMAL, READ_COMPLETE }
Functions
static int read_chomp_line (AVIOContext *s, char *buf, int maxlen)
static void free_segment_list (struct playlist *pls)
static void free_init_section_list (struct playlist *pls)
static void free_playlist_list (HLSContext *c)
static void free_variant_list (HLSContext *c)
static void free_rendition_list (HLSContext *c)
static void reset_packet (AVPacket *pkt)
static struct playlist * new_playlist (HLSContext *c, const char *url, const char *base)
static struct variant * new_variant (HLSContext *c, struct variant_info *info, const char *url, const char *base)
static void handle_variant_args (struct variant_info *info, const char *key, int key_len, char **dest, int *dest_len)
static void handle_key_args (struct key_info *info, const char *key, int key_len, char **dest, int *dest_len)
static struct segment * new_init_section (struct playlist *pls, struct init_section_info *info, const char *url_base)
static void handle_init_section_args (struct init_section_info *info, const char *key, int key_len, char **dest, int *dest_len)
static struct rendition * new_rendition (HLSContext *c, struct rendition_info *info, const char *url_base)
static void handle_rendition_args (struct rendition_info *info, const char *key, int key_len, char **dest, int *dest_len)
static int ensure_playlist (HLSContext *c, struct playlist **pls, const char *url)
static void update_options (char **dest, const char *name, void *src)
static int open_url (AVFormatContext *s, AVIOContext **pb, const char *url, AVDictionary *opts, AVDictionary *opts2, int *is_http)
static int parse_playlist (HLSContext *c, const char *url, struct playlist *pls, AVIOContext *in)
static struct segment * current_segment (struct playlist *pls)
static int read_from_url (struct playlist *pls, struct segment *seg, uint8_t *buf, int buf_size, enum ReadFromURLMode mode)
static void parse_id3 (AVFormatContext *s, AVIOContext *pb, AVDictionary **metadata, int64_t *dts, ID3v2ExtraMetaAPIC **apic, ID3v2ExtraMeta **extra_meta)
static int id3_has_changed_values (struct playlist *pls, AVDictionary *metadata, ID3v2ExtraMetaAPIC *apic)
static void handle_id3 (AVIOContext *pb, struct playlist *pls)
static void intercept_id3 (struct playlist *pls, uint8_t *buf, int buf_size, int *len)
static int open_input (HLSContext *c, struct playlist *pls, struct segment *seg)
static int update_init_section (struct playlist *pls, struct segment *seg)
static int64_t default_reload_interval (struct playlist *pls)
static int read_data (void *opaque, uint8_t *buf, int buf_size)
static void add_renditions_to_variant (HLSContext *c, struct variant *var, enum AVMediaType type, const char *group_id)
static void add_metadata_from_renditions (AVFormatContext *s, struct playlist *pls, enum AVMediaType type)
static int find_timestamp_in_playlist (HLSContext *c, struct playlist *pls, int64_t timestamp, int *seq_no)
static int select_cur_seq_no (HLSContext *c, struct playlist *pls)
static int save_avio_options (AVFormatContext *s)
static int nested_io_open (AVFormatContext *s, AVIOContext **pb, const char *url, int flags, AVDictionary **opts)
static void add_stream_to_programs (AVFormatContext *s, struct playlist *pls, AVStream *stream)
static int set_stream_info_from_input_stream (AVStream *st, struct playlist *pls, AVStream *ist)
static int update_streams_from_subdemuxer (AVFormatContext *s, struct playlist *pls)
static void update_noheader_flag (AVFormatContext *s)
static int hls_close (AVFormatContext *s)
static int hls_read_header (AVFormatContext *s)
static int recheck_discard_flags (AVFormatContext *s, int first)
static void fill_timing_for_id3_timestamped_stream (struct playlist *pls)
static AVRational get_timebase (struct playlist *pls)
static int compare_ts_with_wrapdetect (int64_t ts_a, struct playlist *pls_a, int64_t ts_b, struct playlist *pls_b)
static int hls_read_packet (AVFormatContext *s, AVPacket *pkt)
static int hls_read_seek (AVFormatContext *s, int stream_index, int64_t timestamp, int flags)
static int hls_probe (AVProbeData *p)
Variables
static const AVOption hls_options []
static const AVClass hls_class
AVInputFormat ff_hls_demuxer
Detailed Description
Apple HTTP Live Streaming demuxer http://tools.ietf.org/html/draft-pantos-http-live-streaming.
Definition in file hls.c.
Macro Definition Documentation
INITIAL_BUFFER_SIZE
#define INITIAL_BUFFER_SIZE 32768
Definition at line 41 of file hls.c.
Referenced by hls_read_header().
MAX_FIELD_LEN
#define MAX_FIELD_LEN 64
Definition at line 43 of file hls.c.
MAX_CHARACTERISTICS_LEN
#define MAX_CHARACTERISTICS_LEN 512
Definition at line 44 of file hls.c.
MPEG_TIME_BASE
#define MPEG_TIME_BASE 90000
Definition at line 46 of file hls.c.
Referenced by set_stream_info_from_input_stream().
MPEG_TIME_BASE_Q
#define MPEG_TIME_BASE_Q (AVRational){1, MPEG_TIME_BASE}
Definition at line 47 of file hls.c.
Referenced by compare_ts_with_wrapdetect(), fill_timing_for_id3_timestamped_stream(), and get_timebase().
OFFSET
#define OFFSET (x) offsetof(HLSContext, x)
Definition at line 2140 of file hls.c.
FLAGS
#define FLAGS AV_OPT_FLAG_DECODING_PARAM
Definition at line 2141 of file hls.c.
Enumeration Type Documentation
KeyType
enum KeyType
Enumerator
KEY_NONE
KEY_AES_128
KEY_SAMPLE_AES
Definition at line 61 of file hls.c.
PlaylistType
enum PlaylistType
Enumerator
PLS_TYPE_UNSPECIFIED
PLS_TYPE_EVENT
PLS_TYPE_VOD
PLAYLIST_TYPE_NONE
PLAYLIST_TYPE_EVENT
PLAYLIST_TYPE_VOD
PLAYLIST_TYPE_NB
Definition at line 81 of file hls.c.
ReadFromURLMode
enum ReadFromURLMode
Enumerator
READ_NORMAL
READ_COMPLETE
Definition at line 867 of file hls.c.
Function Documentation
read_chomp_line()
static int read_chomp_line (AVIOContext * s, char * buf, int maxlen) static
Definition at line 209 of file hls.c.
Referenced by parse_playlist().
free_segment_list()
static void free_segment_list (struct playlist * pls) static
Definition at line 217 of file hls.c.
Referenced by free_playlist_list(), and parse_playlist().
free_init_section_list()
static void free_init_section_list (struct playlist * pls) static
Definition at line 229 of file hls.c.
Referenced by free_playlist_list().
free_playlist_list()
static void free_playlist_list (HLSContext * c) static
Definition at line 240 of file hls.c.
Referenced by hls_close().
free_variant_list()
static void free_variant_list (HLSContext * c) static
Definition at line 271 of file hls.c.
Referenced by hls_close().
free_rendition_list()
static void free_rendition_list (HLSContext * c) static
Definition at line 283 of file hls.c.
Referenced by hls_close().
reset_packet()
static void reset_packet (AVPacket * pkt) static
Definition at line 296 of file hls.c.
Referenced by hls_read_packet(), hls_read_seek(), and new_playlist().
new_playlist()
static struct playlist* new_playlist (HLSContext * c, const char * url, const char * base) static
Definition at line 302 of file hls.c.
Referenced by new_rendition(), and new_variant().
new_variant()
static struct variant* new_variant (HLSContext * c, struct variant_info * info, const char * url, const char * base) static
Definition at line 327 of file hls.c.
Referenced by ensure_playlist(), and parse_playlist().
handle_variant_args()
static void handle_variant_args (struct variant_info * info, const char * key, int key_len, char ** dest, int * dest_len) static
Definition at line 353 of file hls.c.
Referenced by parse_playlist().
handle_key_args()
static void handle_key_args (struct key_info * info, const char * key, int key_len, char ** dest, int * dest_len) static
Definition at line 377 of file hls.c.
Referenced by parse_playlist().
new_init_section()
static struct segment* new_init_section (struct playlist * pls, struct init_section_info * info, const char * url_base) static
Definition at line 397 of file hls.c.
Referenced by parse_playlist().
handle_init_section_args()
static void handle_init_section_args (struct init_section_info * info, const char * key, int key_len, char ** dest, int * dest_len) static
Definition at line 434 of file hls.c.
Referenced by parse_playlist().
new_rendition()
static struct rendition* new_rendition (HLSContext * c, struct rendition_info * info, const char * url_base) static
Definition at line 458 of file hls.c.
Referenced by parse_playlist().
handle_rendition_args()
static void handle_rendition_args (struct rendition_info * info, const char * key, int key_len, char ** dest, int * dest_len) static
Definition at line 536 of file hls.c.
Referenced by parse_playlist().
ensure_playlist()
static int ensure_playlist (HLSContext * c, struct playlist ** pls, const char * url) static
Definition at line 580 of file hls.c.
Referenced by parse_playlist().
update_options()
static void update_options (char ** dest, const char * name, void * src) static
Definition at line 590 of file hls.c.
Referenced by hls_read_header(), and open_url().
open_url()
static int open_url (AVFormatContext * s, AVIOContext ** pb, const char * url, AVDictionary * opts, AVDictionary * opts2, int * is_http) static
Definition at line 598 of file hls.c.
Referenced by open_input().
parse_playlist()
static int parse_playlist (HLSContext * c, const char * url, struct playlist * pls, AVIOContext * in) static
Definition at line 646 of file hls.c.
Referenced by hls_read_header(), read_data(), and select_cur_seq_no().
current_segment()
static struct segment* current_segment (struct playlist * pls) static
Definition at line 862 of file hls.c.
Referenced by intercept_id3(), and read_data().
read_from_url()
static int read_from_url (struct playlist * pls, struct segment * seg, uint8_t * buf, int buf_size, enum ReadFromURLMode mode) static
Definition at line 872 of file hls.c.
Referenced by intercept_id3(), read_data(), and update_init_section().
parse_id3()
static void parse_id3 (AVFormatContext * s, AVIOContext * pb, AVDictionary ** metadata, int64_t * dts, ID3v2ExtraMetaAPIC ** apic, ID3v2ExtraMeta ** extra_meta) static
Definition at line 896 of file hls.c.
Referenced by handle_id3().
id3_has_changed_values()
static int id3_has_changed_values (struct playlist * pls, AVDictionary * metadata, ID3v2ExtraMetaAPIC * apic) static
Definition at line 922 of file hls.c.
Referenced by handle_id3().
handle_id3()
static void handle_id3 (AVIOContext * pb, struct playlist * pls) static
Definition at line 951 of file hls.c.
Referenced by intercept_id3().
intercept_id3()
static void intercept_id3 (struct playlist * pls, uint8_t * buf, int buf_size, int * len) static
Definition at line 992 of file hls.c.
Referenced by read_data().
open_input()
static int open_input (HLSContext * c, struct playlist * pls, struct segment * seg) static
Definition at line 1092 of file hls.c.
Referenced by read_data(), and update_init_section().
update_init_section()
static int update_init_section (struct playlist * pls, struct segment * seg) static
Definition at line 1188 of file hls.c.
Referenced by read_data().
default_reload_interval()
static int64_t default_reload_interval (struct playlist * pls) static
Definition at line 1245 of file hls.c.
Referenced by read_data(), and select_cur_seq_no().
read_data()
static int read_data (void * opaque, uint8_t * buf, int buf_size) static
Definition at line 1252 of file hls.c.
Referenced by hls_read_header(), pulse_read_packet(), and tls_client_handshake_loop().
add_renditions_to_variant()
static void add_renditions_to_variant (HLSContext * c, struct variant * var, enum AVMediaType type, const char * group_id) static
Definition at line 1369 of file hls.c.
Referenced by hls_read_header().
add_metadata_from_renditions()
static void add_metadata_from_renditions (AVFormatContext * s, struct playlist * pls, enum AVMediaType type) static
Definition at line 1393 of file hls.c.
Referenced by hls_read_header().
find_timestamp_in_playlist()
static int find_timestamp_in_playlist (HLSContext * c, struct playlist * pls, int64_t timestamp, int * seq_no) static
Definition at line 1425 of file hls.c.
Referenced by hls_read_seek(), and select_cur_seq_no().
select_cur_seq_no()
static int select_cur_seq_no (HLSContext * c, struct playlist * pls) static
Definition at line 1451 of file hls.c.
Referenced by hls_read_header(), and recheck_discard_flags().
save_avio_options()
static int save_avio_options (AVFormatContext * s) static
Definition at line 1490 of file hls.c.
Referenced by hls_read_header().
nested_io_open()
static int nested_io_open (AVFormatContext * s, AVIOContext ** pb, const char * url, int flags, AVDictionary ** opts) static
Definition at line 1512 of file hls.c.
Referenced by hls_read_header().
add_stream_to_programs()
static void add_stream_to_programs (AVFormatContext * s, struct playlist * pls, AVStream * stream) static
Definition at line 1522 of file hls.c.
Referenced by update_streams_from_subdemuxer().
set_stream_info_from_input_stream()
static int set_stream_info_from_input_stream (AVStream * st, struct playlist * pls, AVStream * ist) static
Definition at line 1548 of file hls.c.
Referenced by hls_read_packet(), and update_streams_from_subdemuxer().
update_streams_from_subdemuxer()
static int update_streams_from_subdemuxer (AVFormatContext * s, struct playlist * pls) static
Definition at line 1567 of file hls.c.
Referenced by hls_read_header(), and hls_read_packet().
update_noheader_flag()
static void update_noheader_flag (AVFormatContext * s) static
Definition at line 1592 of file hls.c.
Referenced by hls_read_header(), and hls_read_packet().
hls_close()
static int hls_close (AVFormatContext * s) static
Definition at line 1613 of file hls.c.
Referenced by hls_read_header().
hls_read_header()
static int hls_read_header (AVFormatContext * s) static
Definition at line 1626 of file hls.c.
recheck_discard_flags()
static int recheck_discard_flags (AVFormatContext * s, int first) static
Definition at line 1831 of file hls.c.
Referenced by hls_read_packet().
fill_timing_for_id3_timestamped_stream()
static void fill_timing_for_id3_timestamped_stream (struct playlist * pls) static
Definition at line 1871 of file hls.c.
Referenced by hls_read_packet().
get_timebase()
static AVRational get_timebase (struct playlist * pls) static
Definition at line 1896 of file hls.c.
Referenced by compare_ts_with_wrapdetect(), and hls_read_packet().
compare_ts_with_wrapdetect()
static int compare_ts_with_wrapdetect (int64_t ts_a, struct playlist * pls_a, int64_t ts_b, struct playlist * pls_b) static
Definition at line 1904 of file hls.c.
Referenced by hls_read_packet().
hls_read_packet()
static int hls_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 1913 of file hls.c.
hls_read_seek()
static int hls_read_seek (AVFormatContext * s, int stream_index, int64_t timestamp, int flags) static
Definition at line 2044 of file hls.c.
hls_probe()
static int hls_probe (AVProbeData * p) static
Definition at line 2126 of file hls.c.
Variable Documentation
hls_options
const AVOption hls_options[] static
Initial value:
= {
    {"live_start_index", "segment index to start live streams at (negative values are from the end)",
        OFFSET(live_start_index), AV_OPT_TYPE_INT, {.i64 = -3}, INT_MIN, INT_MAX, FLAGS},
    {NULL}
}
Definition at line 2142 of file hls.c.
hls_class
const AVClass hls_class static
Initial value:
= {
    .class_name = "hls,applehttp",
    .item_name  = av_default_item_name,
    .option     = hls_options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 2148 of file hls.c.
ff_hls_demuxer
AVInputFormat ff_hls_demuxer
Initial value:
= {
    .name           = "hls,applehttp",
    .long_name      = NULL_IF_CONFIG_SMALL("Apple HTTP Live Streaming"),
    .priv_class     = &hls_class,
    .priv_data_size = sizeof(HLSContext),
    .read_probe     = hls_probe,
    .read_header    = hls_read_header,
    .read_packet    = hls_read_packet,
    .read_close     = hls_close,
    .read_seek      = hls_read_seek,
}
Definition at line 2155 of file hls.c.