FFmpeg: libavformat/hlsenc.c File Reference
hlsenc.c File Reference
#include "config.h"
#include <float.h>
#include <stdint.h>
#include "libavutil/avassert.h"
#include "libavutil/mathematics.h"
#include "libavutil/parseutils.h"
#include "libavutil/avstring.h"
#include "libavutil/opt.h"
#include "libavutil/log.h"
#include "libavutil/time_internal.h"
#include "avformat.h"
#include "avio_internal.h"
#include "internal.h"
#include "os_support.h"
Data Structures
struct HLSSegment
struct HLSContext
Macros
#define KEYSIZE 16
#define LINE_BUFFER_SIZE 1024
#define OFFSET(x) offsetof(HLSContext, x)
#define E AV_OPT_FLAG_ENCODING_PARAM
Enumerations
enum HLSFlags {
HLS_SINGLE_FILE = (1 << 0), HLS_DELETE_SEGMENTS = (1 << 1), HLS_ROUND_DURATIONS = (1 << 2), HLS_DISCONT_START = (1 << 3),
HLS_OMIT_ENDLIST = (1 << 4), HLS_SPLIT_BY_TIME = (1 << 5), HLS_APPEND_LIST = (1 << 6), HLS_PROGRAM_DATE_TIME = (1 << 7),
HLS_SECOND_LEVEL_SEGMENT_INDEX = (1 << 8)
}
enum PlaylistType {
PLS_TYPE_UNSPECIFIED, PLS_TYPE_EVENT, PLS_TYPE_VOD, PLAYLIST_TYPE_NONE,
PLAYLIST_TYPE_EVENT, PLAYLIST_TYPE_VOD, PLAYLIST_TYPE_NB
}
Functions
static int mkdir_p (const char *path)
static int hls_delete_old_segments (HLSContext *hls)
static int hls_encryption_start (AVFormatContext *s)
static int read_chomp_line (AVIOContext *s, char *buf, int maxlen)
static int hls_mux_init (AVFormatContext *s)
static HLSSegment * find_segment_by_filename (HLSSegment *segment, const char *filename)
static int hls_append_segment (struct AVFormatContext *s, HLSContext *hls, double duration, int64_t pos, int64_t size)
static int parse_playlist (AVFormatContext *s, const char *url)
static void hls_free_segments (HLSSegment *p)
static void set_http_options (AVDictionary **options, HLSContext *c)
static int hls_window (AVFormatContext *s, int last)
static int hls_start (AVFormatContext *s)
static const char * get_default_pattern_localtime_fmt (void)
static int hls_write_header (AVFormatContext *s)
static int hls_write_packet (AVFormatContext *s, AVPacket *pkt)
static int hls_write_trailer (struct AVFormatContext *s)
Variables
static const AVOption options []
static const AVClass hls_class
AVOutputFormat ff_hls_muxer
Macro Definition Documentation
KEYSIZE
#define KEYSIZE 16
Definition at line 42 of file hlsenc.c.
Referenced by hls_encryption_start(), and hls_start().
LINE_BUFFER_SIZE
#define LINE_BUFFER_SIZE 1024
Definition at line 43 of file hlsenc.c.
OFFSET
#define OFFSET (x) offsetof(HLSContext, x)
Definition at line 1144 of file hlsenc.c.
E
#define E AV_OPT_FLAG_ENCODING_PARAM
Definition at line 1145 of file hlsenc.c.
Enumeration Type Documentation
HLSFlags
enum HLSFlags
Enumerator
HLS_SINGLE_FILE
HLS_DELETE_SEGMENTS
HLS_ROUND_DURATIONS
HLS_DISCONT_START
HLS_OMIT_ENDLIST
HLS_SPLIT_BY_TIME
HLS_APPEND_LIST
HLS_PROGRAM_DATE_TIME
HLS_SECOND_LEVEL_SEGMENT_INDEX
Definition at line 59 of file hlsenc.c.
PlaylistType
enum PlaylistType
Enumerator
PLS_TYPE_UNSPECIFIED
PLS_TYPE_EVENT
PLS_TYPE_VOD
PLAYLIST_TYPE_NONE
PLAYLIST_TYPE_EVENT
PLAYLIST_TYPE_VOD
PLAYLIST_TYPE_NB
Definition at line 72 of file hlsenc.c.
Function Documentation
mkdir_p()
static int mkdir_p (const char * path) static
Definition at line 139 of file hlsenc.c.
Referenced by hls_start().
hls_delete_old_segments()
static int hls_delete_old_segments (HLSContext * hls) static
Definition at line 172 of file hlsenc.c.
Referenced by hls_append_segment().
hls_encryption_start()
static int hls_encryption_start (AVFormatContext * s) static
Definition at line 262 of file hlsenc.c.
Referenced by hls_start().
read_chomp_line()
static int read_chomp_line (AVIOContext * s, char * buf, int maxlen) static
Definition at line 314 of file hlsenc.c.
Referenced by parse_playlist().
hls_mux_init()
static int hls_mux_init (AVFormatContext * s) static
Definition at line 322 of file hlsenc.c.
Referenced by hls_write_header().
find_segment_by_filename()
static HLSSegment* find_segment_by_filename (HLSSegment * segment, const char * filename) static
Definition at line 370 of file hlsenc.c.
Referenced by hls_append_segment().
hls_append_segment()
static int hls_append_segment (struct AVFormatContext * s, HLSContext * hls, double duration, int64_t pos, int64_t size) static
Definition at line 381 of file hlsenc.c.
Referenced by hls_write_packet(), hls_write_trailer(), and parse_playlist().
parse_playlist()
static int parse_playlist (AVFormatContext * s, const char * url) static
Definition at line 457 of file hlsenc.c.
Referenced by hls_write_header().
hls_free_segments()
static void hls_free_segments (HLSSegment * p) static
Definition at line 509 of file hlsenc.c.
Referenced by hls_write_trailer().
set_http_options()
static void set_http_options (AVDictionary ** options, HLSContext * c) static
Definition at line 520 of file hlsenc.c.
Referenced by hls_start(), and hls_window().
hls_window()
static int hls_window (AVFormatContext * s, int last) static
Definition at line 526 of file hlsenc.c.
Referenced by hls_write_packet(), and hls_write_trailer().
hls_start()
static int hls_start (AVFormatContext * s) static
Definition at line 676 of file hlsenc.c.
Referenced by hls_write_header(), and hls_write_packet().
get_default_pattern_localtime_fmt()
static const char* get_default_pattern_localtime_fmt (void) static
Definition at line 810 of file hlsenc.c.
Referenced by hls_write_header().
hls_write_header()
static int hls_write_header (AVFormatContext * s) static
Definition at line 820 of file hlsenc.c.
hls_write_packet()
static int hls_write_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 1007 of file hlsenc.c.
hls_write_trailer()
static int hls_write_trailer (struct AVFormatContext * s) static
Definition at line 1108 of file hlsenc.c.
Variable Documentation
options
const AVOption options[] static
Definition at line 1146 of file hlsenc.c.
Referenced by hls_start(), hls_window(), and hls_write_header().
hls_class
const AVClass hls_class static
Initial value:
= {
    .class_name = "hls muxer",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1180 of file hlsenc.c.
ff_hls_muxer
AVOutputFormat ff_hls_muxer
Initial value:
= {
    .name           = "hls",
    .long_name      = NULL_IF_CONFIG_SMALL("Apple HTTP Live Streaming"),
    .extensions     = "m3u8",
    .priv_data_size = sizeof(HLSContext),
    .audio_codec    = AV_CODEC_ID_AAC,
    .video_codec    = AV_CODEC_ID_H264,
    .subtitle_codec = AV_CODEC_ID_WEBVTT,
    .flags          = AVFMT_NOFILE | AVFMT_ALLOW_FLUSH,
    .write_header   = hls_write_header,
    .write_packet   = hls_write_packet,
    .write_trailer  = hls_write_trailer,
    .priv_class     = &hls_class,
}
Definition at line 1188 of file hlsenc.c.