FFmpeg: libavcodec/hnm4video.c File Reference
hnm4video.c File Reference
#include <string.h>
#include "libavutil/imgutils.h"
#include "libavutil/internal.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/mem.h"
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
Data Structures
struct Hnm4VideoContext
Macros
#define HNM4_CHUNK_ID_PL 19536
#define HNM4_CHUNK_ID_IZ 23113
#define HNM4_CHUNK_ID_IU 21833
#define HNM4_CHUNK_ID_SD 17491
Functions
static int getbit (GetByteContext *gb, uint32_t *bitbuf, int *bits)
static void unpack_intraframe (AVCodecContext *avctx, uint8_t *src, uint32_t size)
static void postprocess_current_frame (AVCodecContext *avctx)
static void copy_processed_frame (AVCodecContext *avctx, AVFrame *frame)
static void decode_interframe_v4 (AVCodecContext *avctx, uint8_t *src, uint32_t size)
static void decode_interframe_v4a (AVCodecContext *avctx, uint8_t *src, uint32_t size)
static void hnm_update_palette (AVCodecContext *avctx, uint8_t *src, uint32_t size)
static void hnm_flip_buffers (Hnm4VideoContext *hnm)
static int hnm_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int hnm_decode_init (AVCodecContext *avctx)
static av_cold int hnm_decode_end (AVCodecContext *avctx)
Variables
AVCodec ff_hnm4_video_decoder
Macro Definition Documentation
HNM4_CHUNK_ID_PL
#define HNM4_CHUNK_ID_PL 19536
Definition at line 33 of file hnm4video.c.
Referenced by hnm_decode_frame().
HNM4_CHUNK_ID_IZ
#define HNM4_CHUNK_ID_IZ 23113
Definition at line 34 of file hnm4video.c.
Referenced by hnm_decode_frame().
HNM4_CHUNK_ID_IU
#define HNM4_CHUNK_ID_IU 21833
Definition at line 35 of file hnm4video.c.
Referenced by hnm_decode_frame().
HNM4_CHUNK_ID_SD
#define HNM4_CHUNK_ID_SD 17491
Definition at line 36 of file hnm4video.c.
Function Documentation
getbit()
static int getbit (GetByteContext * gb, uint32_t * bitbuf, int * bits) static
Definition at line 50 of file hnm4video.c.
Referenced by unpack_intraframe().
unpack_intraframe()
static void unpack_intraframe (AVCodecContext * avctx, uint8_t * src, uint32_t size) static
Definition at line 66 of file hnm4video.c.
Referenced by hnm_decode_frame().
postprocess_current_frame()
static void postprocess_current_frame (AVCodecContext * avctx) static
Definition at line 117 of file hnm4video.c.
Referenced by hnm_decode_frame().
copy_processed_frame()
static void copy_processed_frame (AVCodecContext * avctx, AVFrame * frame) static
Definition at line 132 of file hnm4video.c.
Referenced by hnm_decode_frame().
decode_interframe_v4()
static void decode_interframe_v4 (AVCodecContext * avctx, uint8_t * src, uint32_t size) static
Definition at line 146 of file hnm4video.c.
Referenced by hnm_decode_frame().
decode_interframe_v4a()
static void decode_interframe_v4a (AVCodecContext * avctx, uint8_t * src, uint32_t size) static
Definition at line 273 of file hnm4video.c.
Referenced by hnm_decode_frame().
hnm_update_palette()
static void hnm_update_palette (AVCodecContext * avctx, uint8_t * src, uint32_t size) static
Definition at line 352 of file hnm4video.c.
Referenced by hnm_decode_frame().
hnm_flip_buffers()
static void hnm_flip_buffers (Hnm4VideoContext * hnm) static
Definition at line 384 of file hnm4video.c.
Referenced by hnm_decode_frame().
hnm_decode_frame()
static int hnm_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 393 of file hnm4video.c.
hnm_decode_init()
static av_cold int hnm_decode_init (AVCodecContext * avctx) static
Definition at line 454 of file hnm4video.c.
hnm_decode_end()
static av_cold int hnm_decode_end (AVCodecContext * avctx) static
Definition at line 493 of file hnm4video.c.
Variable Documentation
ff_hnm4_video_decoder
AVCodec ff_hnm4_video_decoder
Initial value:
= {
    .name           = "hnm4video",
    .long_name      = NULL_IF_CONFIG_SMALL("HNM 4 video"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_HNM4_VIDEO,
    .priv_data_size = sizeof(Hnm4VideoContext),
    .init           = hnm_decode_init,
    .close          = hnm_decode_end,
    .decode         = hnm_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 504 of file hnm4video.c.