FFmpeg: libavcodec/aarch64/hpeldsp_init_aarch64.c File Reference
hpeldsp_init_aarch64.c File Reference
#include <stddef.h>
#include <stdint.h>
#include "config.h"
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/aarch64/cpu.h"
#include "libavcodec/hpeldsp.h"
Functions
void ff_put_pixels16_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_x2_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_y2_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_xy2_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_x2_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_y2_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_xy2_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_x2_no_rnd_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_y2_no_rnd_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_xy2_no_rnd_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_x2_no_rnd_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_y2_no_rnd_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_xy2_no_rnd_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_x2_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_y2_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_xy2_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_x2_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_y2_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_xy2_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_x2_no_rnd_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_y2_no_rnd_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_xy2_no_rnd_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
av_cold void ff_hpeldsp_init_aarch64 (HpelDSPContext *c, int flags)
Function Documentation
ff_put_pixels16_neon()
void ff_put_pixels16_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_put_pixels16_x2_neon()
void ff_put_pixels16_x2_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_put_pixels16_y2_neon()
void ff_put_pixels16_y2_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_put_pixels16_xy2_neon()
void ff_put_pixels16_xy2_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_put_pixels8_neon()
void ff_put_pixels8_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_put_pixels8_x2_neon()
void ff_put_pixels8_x2_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_put_pixels8_y2_neon()
void ff_put_pixels8_y2_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_put_pixels8_xy2_neon()
void ff_put_pixels8_xy2_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_put_pixels16_x2_no_rnd_neon()
void ff_put_pixels16_x2_no_rnd_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_put_pixels16_y2_no_rnd_neon()
void ff_put_pixels16_y2_no_rnd_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_put_pixels16_xy2_no_rnd_neon()
void ff_put_pixels16_xy2_no_rnd_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_put_pixels8_x2_no_rnd_neon()
void ff_put_pixels8_x2_no_rnd_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_put_pixels8_y2_no_rnd_neon()
void ff_put_pixels8_y2_no_rnd_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_put_pixels8_xy2_no_rnd_neon()
void ff_put_pixels8_xy2_no_rnd_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_avg_pixels16_neon()
void ff_avg_pixels16_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_avg_pixels16_x2_neon()
void ff_avg_pixels16_x2_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_avg_pixels16_y2_neon()
void ff_avg_pixels16_y2_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_avg_pixels16_xy2_neon()
void ff_avg_pixels16_xy2_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_avg_pixels8_neon()
void ff_avg_pixels8_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_avg_pixels8_x2_neon()
void ff_avg_pixels8_x2_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_avg_pixels8_y2_neon()
void ff_avg_pixels8_y2_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_avg_pixels8_xy2_neon()
void ff_avg_pixels8_xy2_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_avg_pixels16_x2_no_rnd_neon()
void ff_avg_pixels16_x2_no_rnd_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_avg_pixels16_y2_no_rnd_neon()
void ff_avg_pixels16_y2_no_rnd_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_avg_pixels16_xy2_no_rnd_neon()
void ff_avg_pixels16_xy2_no_rnd_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_aarch64().
ff_hpeldsp_init_aarch64()
av_cold void ff_hpeldsp_init_aarch64 (HpelDSPContext * c, int flags)
Definition at line 86 of file hpeldsp_init_aarch64.c.
Referenced by ff_hpeldsp_init().