FFmpeg: libavcodec/arm/hpeldsp_init_armv6.c File Reference
hpeldsp_init_armv6.c File Reference
#include <stddef.h>
#include <stdint.h>
#include "libavutil/attributes.h"
#include "hpeldsp_arm.h"
Functions
void ff_put_pixels16_armv6 (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels16_x2_armv6 (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels16_y2_armv6 (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels16_x2_no_rnd_armv6 (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels16_y2_no_rnd_armv6 (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_avg_pixels16_armv6 (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels8_armv6 (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels8_x2_armv6 (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels8_y2_armv6 (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels8_x2_no_rnd_armv6 (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels8_y2_no_rnd_armv6 (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_avg_pixels8_armv6 (uint8_t *, const uint8_t *, ptrdiff_t, int)
av_cold void ff_hpeldsp_init_armv6 (HpelDSPContext *c, int flags)
Function Documentation
ff_put_pixels16_armv6()
void ff_put_pixels16_armv6 (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_armv6().
ff_put_pixels16_x2_armv6()
void ff_put_pixels16_x2_armv6 (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_armv6().
ff_put_pixels16_y2_armv6()
void ff_put_pixels16_y2_armv6 (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_armv6().
ff_put_pixels16_x2_no_rnd_armv6()
void ff_put_pixels16_x2_no_rnd_armv6 (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_armv6().
ff_put_pixels16_y2_no_rnd_armv6()
void ff_put_pixels16_y2_no_rnd_armv6 (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_armv6().
ff_avg_pixels16_armv6()
void ff_avg_pixels16_armv6 (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_armv6().
ff_put_pixels8_armv6()
void ff_put_pixels8_armv6 (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_armv6().
ff_put_pixels8_x2_armv6()
void ff_put_pixels8_x2_armv6 (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_armv6().
ff_put_pixels8_y2_armv6()
void ff_put_pixels8_y2_armv6 (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_armv6().
ff_put_pixels8_x2_no_rnd_armv6()
void ff_put_pixels8_x2_no_rnd_armv6 (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_armv6().
ff_put_pixels8_y2_no_rnd_armv6()
void ff_put_pixels8_y2_no_rnd_armv6 (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_armv6().
ff_avg_pixels8_armv6()
void ff_avg_pixels8_armv6 (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_armv6().
ff_hpeldsp_init_armv6()
av_cold void ff_hpeldsp_init_armv6 (HpelDSPContext * c, int flags)
Definition at line 45 of file hpeldsp_init_armv6.c.
Referenced by ff_hpeldsp_init_arm().