FFmpeg: libavcodec/arm/hpeldsp_init_arm.c File Reference
hpeldsp_init_arm.c File Reference
#include "libavutil/arm/cpu.h"
#include "libavutil/attributes.h"
#include "libavcodec/pixels.h"
#include "hpeldsp_arm.h"
Functions
void ff_put_pixels8_arm (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_x2_arm (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_y2_arm (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_xy2_arm (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels8_x2_arm (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels8_y2_arm (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels8_xy2_arm (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_arm (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
av_cold void ff_hpeldsp_init_arm (HpelDSPContext *c, int flags)
Function Documentation
ff_put_pixels8_arm()
void ff_put_pixels8_arm (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_arm().
ff_put_pixels8_x2_arm()
void ff_put_pixels8_x2_arm (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_arm().
ff_put_pixels8_y2_arm()
void ff_put_pixels8_y2_arm (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_arm().
ff_put_pixels8_xy2_arm()
void ff_put_pixels8_xy2_arm (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_arm().
ff_put_no_rnd_pixels8_x2_arm()
void ff_put_no_rnd_pixels8_x2_arm (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_arm().
ff_put_no_rnd_pixels8_y2_arm()
void ff_put_no_rnd_pixels8_y2_arm (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_arm().
ff_put_no_rnd_pixels8_xy2_arm()
void ff_put_no_rnd_pixels8_xy2_arm (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_arm().
ff_put_pixels16_arm()
void ff_put_pixels16_arm (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by ff_hpeldsp_init_arm().
ff_hpeldsp_init_arm()
av_cold void ff_hpeldsp_init_arm (HpelDSPContext * c, int flags)
Definition at line 45 of file hpeldsp_init_arm.c.
Referenced by ff_hpeldsp_init().