FFmpeg: libavcodec/mips/hpeldsp_mmi.c File Reference
hpeldsp_mmi.c File Reference
#include "hpeldsp_mips.h"
#include "libavcodec/bit_depth_template.c"
#include "libavutil/mips/mmiutils.h"
#include "constants.h"
Functions
void ff_put_pixels4_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels4_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels4_l2_8_mmi (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, int dst_stride, int src_stride1, int src_stride2, int h)
void ff_put_pixels8_l2_8_mmi (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, int dst_stride, int src_stride1, int src_stride2, int h)
void ff_put_pixels16_l2_8_mmi (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, int dst_stride, int src_stride1, int src_stride2, int h)
void ff_avg_pixels4_l2_8_mmi (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, int dst_stride, int src_stride1, int src_stride2, int h)
void ff_avg_pixels8_l2_8_mmi (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, int dst_stride, int src_stride1, int src_stride2, int h)
void ff_avg_pixels16_l2_8_mmi (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, int dst_stride, int src_stride1, int src_stride2, int h)
void ff_put_pixels4_x2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_x2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_x2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels4_x2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_x2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_x2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels8_l2_8_mmi (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, int dst_stride, int src_stride1, int src_stride2, int h)
void ff_put_no_rnd_pixels8_x2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels16_x2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels4_y2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_y2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_y2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels4_y2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_y2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_y2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels8_y2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels16_y2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels4_xy2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_xy2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_xy2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels4_xy2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_xy2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_xy2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels8_xy2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels16_xy2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
Function Documentation
ff_put_pixels4_8_mmi()
void ff_put_pixels4_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 29 of file hpeldsp_mmi.c.
ff_put_pixels8_8_mmi()
void ff_put_pixels8_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 69 of file hpeldsp_mmi.c.
ff_put_pixels16_8_mmi()
void ff_put_pixels16_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 110 of file hpeldsp_mmi.c.
ff_avg_pixels4_8_mmi()
void ff_avg_pixels4_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 159 of file hpeldsp_mmi.c.
ff_avg_pixels8_8_mmi()
void ff_avg_pixels8_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 211 of file hpeldsp_mmi.c.
ff_avg_pixels16_8_mmi()
void ff_avg_pixels16_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 263 of file hpeldsp_mmi.c.
ff_put_pixels4_l2_8_mmi()
void ff_put_pixels4_l2_8_mmi (uint8_t * dst, const uint8_t * src1, const uint8_t * src2, int dst_stride, int src_stride1, int src_stride2, int h) inline
Definition at line 333 of file hpeldsp_mmi.c.
Referenced by ff_put_h264_qpel4_mc01_mmi(), ff_put_h264_qpel4_mc03_mmi(), ff_put_h264_qpel4_mc10_mmi(), ff_put_h264_qpel4_mc11_mmi(), ff_put_h264_qpel4_mc12_mmi(), ff_put_h264_qpel4_mc13_mmi(), ff_put_h264_qpel4_mc21_mmi(), ff_put_h264_qpel4_mc23_mmi(), ff_put_h264_qpel4_mc30_mmi(), ff_put_h264_qpel4_mc31_mmi(), ff_put_h264_qpel4_mc32_mmi(), ff_put_h264_qpel4_mc33_mmi(), ff_put_pixels4_x2_8_mmi(), and ff_put_pixels4_y2_8_mmi().
ff_put_pixels8_l2_8_mmi()
void ff_put_pixels8_l2_8_mmi (uint8_t * dst, const uint8_t * src1, const uint8_t * src2, int dst_stride, int src_stride1, int src_stride2, int h) inline
Definition at line 393 of file hpeldsp_mmi.c.
Referenced by ff_put_h264_qpel8_mc01_mmi(), ff_put_h264_qpel8_mc03_mmi(), ff_put_h264_qpel8_mc10_mmi(), ff_put_h264_qpel8_mc11_mmi(), ff_put_h264_qpel8_mc13_mmi(), ff_put_h264_qpel8_mc30_mmi(), ff_put_h264_qpel8_mc31_mmi(), ff_put_h264_qpel8_mc33_mmi(), ff_put_pixels8_x2_8_mmi(), and ff_put_pixels8_y2_8_mmi().
ff_put_pixels16_l2_8_mmi()
void ff_put_pixels16_l2_8_mmi (uint8_t * dst, const uint8_t * src1, const uint8_t * src2, int dst_stride, int src_stride1, int src_stride2, int h) inline
Definition at line 454 of file hpeldsp_mmi.c.
Referenced by ff_put_h264_qpel16_mc01_mmi(), ff_put_h264_qpel16_mc03_mmi(), ff_put_h264_qpel16_mc10_mmi(), ff_put_h264_qpel16_mc11_mmi(), ff_put_h264_qpel16_mc13_mmi(), ff_put_h264_qpel16_mc30_mmi(), ff_put_h264_qpel16_mc31_mmi(), ff_put_h264_qpel16_mc33_mmi(), ff_put_pixels16_x2_8_mmi(), and ff_put_pixels16_y2_8_mmi().
ff_avg_pixels4_l2_8_mmi()
void ff_avg_pixels4_l2_8_mmi (uint8_t * dst, const uint8_t * src1, const uint8_t * src2, int dst_stride, int src_stride1, int src_stride2, int h) inline
Definition at line 533 of file hpeldsp_mmi.c.
Referenced by ff_avg_h264_qpel4_mc01_mmi(), ff_avg_h264_qpel4_mc03_mmi(), ff_avg_h264_qpel4_mc10_mmi(), ff_avg_h264_qpel4_mc11_mmi(), ff_avg_h264_qpel4_mc12_mmi(), ff_avg_h264_qpel4_mc13_mmi(), ff_avg_h264_qpel4_mc21_mmi(), ff_avg_h264_qpel4_mc23_mmi(), ff_avg_h264_qpel4_mc30_mmi(), ff_avg_h264_qpel4_mc31_mmi(), ff_avg_h264_qpel4_mc32_mmi(), ff_avg_h264_qpel4_mc33_mmi(), ff_avg_pixels4_x2_8_mmi(), and ff_avg_pixels4_y2_8_mmi().
ff_avg_pixels8_l2_8_mmi()
void ff_avg_pixels8_l2_8_mmi (uint8_t * dst, const uint8_t * src1, const uint8_t * src2, int dst_stride, int src_stride1, int src_stride2, int h) inline
Definition at line 605 of file hpeldsp_mmi.c.
Referenced by ff_avg_h264_qpel8_mc01_mmi(), ff_avg_h264_qpel8_mc03_mmi(), ff_avg_h264_qpel8_mc10_mmi(), ff_avg_h264_qpel8_mc11_mmi(), ff_avg_h264_qpel8_mc13_mmi(), ff_avg_h264_qpel8_mc30_mmi(), ff_avg_h264_qpel8_mc31_mmi(), ff_avg_h264_qpel8_mc33_mmi(), ff_avg_pixels16_l2_8_mmi(), ff_avg_pixels8_x2_8_mmi(), and ff_avg_pixels8_y2_8_mmi().
ff_avg_pixels16_l2_8_mmi()
void ff_avg_pixels16_l2_8_mmi (uint8_t * dst, const uint8_t * src1, const uint8_t * src2, int dst_stride, int src_stride1, int src_stride2, int h) inline
Definition at line 677 of file hpeldsp_mmi.c.
Referenced by ff_avg_h264_qpel16_mc01_mmi(), ff_avg_h264_qpel16_mc03_mmi(), ff_avg_h264_qpel16_mc10_mmi(), ff_avg_h264_qpel16_mc11_mmi(), ff_avg_h264_qpel16_mc13_mmi(), ff_avg_h264_qpel16_mc30_mmi(), ff_avg_h264_qpel16_mc31_mmi(), and ff_avg_h264_qpel16_mc33_mmi().
ff_put_pixels4_x2_8_mmi()
void ff_put_pixels4_x2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 687 of file hpeldsp_mmi.c.
ff_put_pixels8_x2_8_mmi()
void ff_put_pixels8_x2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 694 of file hpeldsp_mmi.c.
ff_put_pixels16_x2_8_mmi()
void ff_put_pixels16_x2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 701 of file hpeldsp_mmi.c.
ff_avg_pixels4_x2_8_mmi()
void ff_avg_pixels4_x2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 708 of file hpeldsp_mmi.c.
ff_avg_pixels8_x2_8_mmi()
void ff_avg_pixels8_x2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 715 of file hpeldsp_mmi.c.
Referenced by ff_avg_pixels16_x2_8_mmi().
ff_avg_pixels16_x2_8_mmi()
void ff_avg_pixels16_x2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 722 of file hpeldsp_mmi.c.
ff_put_no_rnd_pixels8_l2_8_mmi()
void ff_put_no_rnd_pixels8_l2_8_mmi (uint8_t * dst, const uint8_t * src1, const uint8_t * src2, int dst_stride, int src_stride1, int src_stride2, int h) inline
Definition at line 729 of file hpeldsp_mmi.c.
Referenced by ff_put_no_rnd_pixels8_x2_8_mmi(), and ff_put_no_rnd_pixels8_y2_8_mmi().
ff_put_no_rnd_pixels8_x2_8_mmi()
void ff_put_no_rnd_pixels8_x2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 804 of file hpeldsp_mmi.c.
Referenced by ff_put_no_rnd_pixels16_x2_8_mmi().
ff_put_no_rnd_pixels16_x2_8_mmi()
void ff_put_no_rnd_pixels16_x2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 811 of file hpeldsp_mmi.c.
ff_put_pixels4_y2_8_mmi()
void ff_put_pixels4_y2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 818 of file hpeldsp_mmi.c.
ff_put_pixels8_y2_8_mmi()
void ff_put_pixels8_y2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 825 of file hpeldsp_mmi.c.
ff_put_pixels16_y2_8_mmi()
void ff_put_pixels16_y2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 832 of file hpeldsp_mmi.c.
ff_avg_pixels4_y2_8_mmi()
void ff_avg_pixels4_y2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 839 of file hpeldsp_mmi.c.
ff_avg_pixels8_y2_8_mmi()
void ff_avg_pixels8_y2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 846 of file hpeldsp_mmi.c.
Referenced by ff_avg_pixels16_y2_8_mmi().
ff_avg_pixels16_y2_8_mmi()
void ff_avg_pixels16_y2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 853 of file hpeldsp_mmi.c.
ff_put_no_rnd_pixels8_y2_8_mmi()
void ff_put_no_rnd_pixels8_y2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 860 of file hpeldsp_mmi.c.
Referenced by ff_put_no_rnd_pixels16_y2_8_mmi().
ff_put_no_rnd_pixels16_y2_8_mmi()
void ff_put_no_rnd_pixels16_y2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 867 of file hpeldsp_mmi.c.
ff_put_pixels4_xy2_8_mmi()
void ff_put_pixels4_xy2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 874 of file hpeldsp_mmi.c.
ff_put_pixels8_xy2_8_mmi()
void ff_put_pixels8_xy2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 912 of file hpeldsp_mmi.c.
Referenced by ff_put_pixels16_xy2_8_mmi().
ff_put_pixels16_xy2_8_mmi()
void ff_put_pixels16_xy2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1045 of file hpeldsp_mmi.c.
ff_avg_pixels4_xy2_8_mmi()
void ff_avg_pixels4_xy2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1052 of file hpeldsp_mmi.c.
ff_avg_pixels8_xy2_8_mmi()
void ff_avg_pixels8_xy2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1090 of file hpeldsp_mmi.c.
Referenced by ff_avg_pixels16_xy2_8_mmi().
ff_avg_pixels16_xy2_8_mmi()
void ff_avg_pixels16_xy2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1134 of file hpeldsp_mmi.c.
ff_put_no_rnd_pixels8_xy2_8_mmi()
void ff_put_no_rnd_pixels8_xy2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1141 of file hpeldsp_mmi.c.
Referenced by ff_put_no_rnd_pixels16_xy2_8_mmi().
ff_put_no_rnd_pixels16_xy2_8_mmi()
void ff_put_no_rnd_pixels16_xy2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1185 of file hpeldsp_mmi.c.