FFmpeg: libavcodec/x86/hpeldsp_init.c File Reference
hpeldsp_init.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/x86/cpu.h"
#include "libavcodec/avcodec.h"
#include "libavcodec/hpeldsp.h"
#include "libavcodec/pixels.h"
#include "fpel.h"
#include "hpeldsp.h"
Macros
#define avg_pixels8_mmx ff_avg_pixels8_mmx
#define avg_pixels8_x2_mmx ff_avg_pixels8_x2_mmx
#define avg_pixels16_mmx ff_avg_pixels16_mmx
#define avg_pixels8_xy2_mmx ff_avg_pixels8_xy2_mmx
#define avg_pixels16_xy2_mmx ff_avg_pixels16_xy2_mmx
#define put_pixels8_mmx ff_put_pixels8_mmx
#define put_pixels16_mmx ff_put_pixels16_mmx
#define put_pixels8_xy2_mmx ff_put_pixels8_xy2_mmx
#define put_pixels16_xy2_mmx ff_put_pixels16_xy2_mmx
#define avg_no_rnd_pixels16_mmx ff_avg_pixels16_mmx
#define put_no_rnd_pixels8_mmx ff_put_pixels8_mmx
#define put_no_rnd_pixels16_mmx ff_put_pixels16_mmx
#define SET_HPEL_FUNCS_EXT(PFX, IDX, SIZE, CPU)
#define SET_HPEL_FUNCS(PFX, IDX, SIZE, CPU)
Functions
void ff_put_pixels8_x2_mmxext (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_x2_3dnow (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_x2_mmxext (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_x2_3dnow (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_x2_sse2 (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_x2_sse2 (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_y2_sse2 (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_y2_sse2 (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels8_x2_mmxext (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels8_x2_3dnow (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels8_x2_exact_mmxext (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels8_x2_exact_3dnow (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_y2_mmxext (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_y2_3dnow (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels8_y2_mmxext (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels8_y2_3dnow (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels8_y2_exact_mmxext (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels8_y2_exact_3dnow (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_3dnow (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_x2_mmxext (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_x2_3dnow (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_y2_mmxext (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_y2_3dnow (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_xy2_3dnow (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_approx_pixels8_xy2_mmxext (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_approx_pixels8_xy2_3dnow (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
static void hpeldsp_init_mmx (HpelDSPContext *c, int flags, int cpu_flags)
static void hpeldsp_init_mmxext (HpelDSPContext *c, int flags, int cpu_flags)
static void hpeldsp_init_3dnow (HpelDSPContext *c, int flags, int cpu_flags)
static void hpeldsp_init_sse2 (HpelDSPContext *c, int flags, int cpu_flags)
static void hpeldsp_init_ssse3 (HpelDSPContext *c, int flags, int cpu_flags)
av_cold void ff_hpeldsp_init_x86 (HpelDSPContext *c, int flags)
Macro Definition Documentation
avg_pixels8_mmx
#define avg_pixels8_mmx ff_avg_pixels8_mmx
Definition at line 91 of file hpeldsp_init.c.
avg_pixels8_x2_mmx
#define avg_pixels8_x2_mmx ff_avg_pixels8_x2_mmx
Definition at line 92 of file hpeldsp_init.c.
avg_pixels16_mmx
#define avg_pixels16_mmx ff_avg_pixels16_mmx
Definition at line 93 of file hpeldsp_init.c.
avg_pixels8_xy2_mmx
#define avg_pixels8_xy2_mmx ff_avg_pixels8_xy2_mmx
Definition at line 94 of file hpeldsp_init.c.
avg_pixels16_xy2_mmx
#define avg_pixels16_xy2_mmx ff_avg_pixels16_xy2_mmx
Definition at line 95 of file hpeldsp_init.c.
put_pixels8_mmx
#define put_pixels8_mmx ff_put_pixels8_mmx
Definition at line 96 of file hpeldsp_init.c.
put_pixels16_mmx
#define put_pixels16_mmx ff_put_pixels16_mmx
Definition at line 97 of file hpeldsp_init.c.
put_pixels8_xy2_mmx
#define put_pixels8_xy2_mmx ff_put_pixels8_xy2_mmx
Definition at line 98 of file hpeldsp_init.c.
put_pixels16_xy2_mmx
#define put_pixels16_xy2_mmx ff_put_pixels16_xy2_mmx
Definition at line 99 of file hpeldsp_init.c.
avg_no_rnd_pixels16_mmx
#define avg_no_rnd_pixels16_mmx ff_avg_pixels16_mmx
Definition at line 100 of file hpeldsp_init.c.
put_no_rnd_pixels8_mmx
#define put_no_rnd_pixels8_mmx ff_put_pixels8_mmx
Definition at line 101 of file hpeldsp_init.c.
put_no_rnd_pixels16_mmx
#define put_no_rnd_pixels16_mmx ff_put_pixels16_mmx
Definition at line 102 of file hpeldsp_init.c.
SET_HPEL_FUNCS_EXT
#define SET_HPEL_FUNCS_EXT (PFX, IDX, SIZE, CPU)
Value:
if (HAVE_MMX_EXTERNAL)                                                  \
    c->PFX ## _pixels_tab IDX [0] = PFX ## _pixels ## SIZE ## _     ## CPU;
Definition at line 180 of file hpeldsp_init.c.
SET_HPEL_FUNCS
#define SET_HPEL_FUNCS (PFX, IDX, SIZE, CPU)
Value:
do {                                                                        \
        SET_HPEL_FUNCS_EXT(PFX, IDX, SIZE, CPU)                                 \
    } while (0)
Definition at line 193 of file hpeldsp_init.c.
Referenced by hpeldsp_init_mmx().
Function Documentation
ff_put_pixels8_x2_mmxext()
void ff_put_pixels8_x2_mmxext (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_mmxext().
ff_put_pixels8_x2_3dnow()
void ff_put_pixels8_x2_3dnow (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_3dnow().
ff_put_pixels16_x2_mmxext()
void ff_put_pixels16_x2_mmxext (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_mmxext().
ff_put_pixels16_x2_3dnow()
void ff_put_pixels16_x2_3dnow (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_3dnow().
ff_put_pixels16_x2_sse2()
void ff_put_pixels16_x2_sse2 (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_sse2().
ff_avg_pixels16_x2_sse2()
void ff_avg_pixels16_x2_sse2 (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_sse2().
ff_put_pixels16_y2_sse2()
void ff_put_pixels16_y2_sse2 (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_sse2().
ff_avg_pixels16_y2_sse2()
void ff_avg_pixels16_y2_sse2 (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_sse2().
ff_put_no_rnd_pixels8_x2_mmxext()
void ff_put_no_rnd_pixels8_x2_mmxext (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_mmxext().
ff_put_no_rnd_pixels8_x2_3dnow()
void ff_put_no_rnd_pixels8_x2_3dnow (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_3dnow().
ff_put_no_rnd_pixels8_x2_exact_mmxext()
void ff_put_no_rnd_pixels8_x2_exact_mmxext (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_mmxext().
ff_put_no_rnd_pixels8_x2_exact_3dnow()
void ff_put_no_rnd_pixels8_x2_exact_3dnow (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_3dnow().
ff_put_pixels8_y2_mmxext()
void ff_put_pixels8_y2_mmxext (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_mmxext().
ff_put_pixels8_y2_3dnow()
void ff_put_pixels8_y2_3dnow (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_3dnow().
ff_put_no_rnd_pixels8_y2_mmxext()
void ff_put_no_rnd_pixels8_y2_mmxext (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_mmxext().
ff_put_no_rnd_pixels8_y2_3dnow()
void ff_put_no_rnd_pixels8_y2_3dnow (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_3dnow().
ff_put_no_rnd_pixels8_y2_exact_mmxext()
void ff_put_no_rnd_pixels8_y2_exact_mmxext (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_mmxext().
ff_put_no_rnd_pixels8_y2_exact_3dnow()
void ff_put_no_rnd_pixels8_y2_exact_3dnow (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_3dnow().
ff_avg_pixels8_3dnow()
void ff_avg_pixels8_3dnow (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_3dnow().
ff_avg_pixels8_x2_mmxext()
void ff_avg_pixels8_x2_mmxext (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_mmxext().
ff_avg_pixels8_x2_3dnow()
void ff_avg_pixels8_x2_3dnow (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_3dnow().
ff_avg_pixels8_y2_mmxext()
void ff_avg_pixels8_y2_mmxext (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_mmxext().
ff_avg_pixels8_y2_3dnow()
void ff_avg_pixels8_y2_3dnow (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_3dnow().
ff_avg_pixels8_xy2_3dnow()
void ff_avg_pixels8_xy2_3dnow (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_3dnow().
ff_avg_approx_pixels8_xy2_mmxext()
void ff_avg_approx_pixels8_xy2_mmxext (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_mmxext().
ff_avg_approx_pixels8_xy2_3dnow()
void ff_avg_approx_pixels8_xy2_3dnow (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_3dnow().
hpeldsp_init_mmx()
static void hpeldsp_init_mmx (HpelDSPContext * c, int flags, int cpu_flags) static
Definition at line 199 of file hpeldsp_init.c.
Referenced by ff_hpeldsp_init_x86().
hpeldsp_init_mmxext()
static void hpeldsp_init_mmxext (HpelDSPContext * c, int flags, int cpu_flags) static
Definition at line 217 of file hpeldsp_init.c.
Referenced by ff_hpeldsp_init_x86().
hpeldsp_init_3dnow()
static void hpeldsp_init_3dnow (HpelDSPContext * c, int flags, int cpu_flags) static
Definition at line 253 of file hpeldsp_init.c.
Referenced by ff_hpeldsp_init_x86().
hpeldsp_init_sse2()
static void hpeldsp_init_sse2 (HpelDSPContext * c, int flags, int cpu_flags) static
Definition at line 289 of file hpeldsp_init.c.
Referenced by ff_hpeldsp_init_x86().
hpeldsp_init_ssse3()
static void hpeldsp_init_ssse3 (HpelDSPContext * c, int flags, int cpu_flags) static
Definition at line 307 of file hpeldsp_init.c.
Referenced by ff_hpeldsp_init_x86().
ff_hpeldsp_init_x86()
av_cold void ff_hpeldsp_init_x86 (HpelDSPContext * c, int flags)
Definition at line 317 of file hpeldsp_init.c.
Referenced by ff_hpeldsp_init().