FFmpeg: libavcodec/arm/hpeldsp_init_neon.c File Reference
hpeldsp_init_neon.c File Reference
#include <stddef.h>
#include <stdint.h>
#include "libavutil/attributes.h"
#include "hpeldsp_arm.h"
Functions
void ff_put_pixels16_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels16_x2_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels16_y2_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels16_xy2_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels8_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels8_x2_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels8_y2_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels8_xy2_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels16_x2_no_rnd_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels16_y2_no_rnd_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels16_xy2_no_rnd_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels8_x2_no_rnd_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels8_y2_no_rnd_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_put_pixels8_xy2_no_rnd_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_avg_pixels16_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_avg_pixels16_x2_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_avg_pixels16_y2_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_avg_pixels16_xy2_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_avg_pixels8_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_avg_pixels8_x2_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_avg_pixels8_y2_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_avg_pixels8_xy2_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_avg_pixels16_x2_no_rnd_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_avg_pixels16_y2_no_rnd_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
void ff_avg_pixels16_xy2_no_rnd_neon (uint8_t *, const uint8_t *, ptrdiff_t, int)
av_cold void ff_hpeldsp_init_neon (HpelDSPContext *c, int flags)
Function Documentation
ff_put_pixels16_neon()
void ff_put_pixels16_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_put_pixels16_x2_neon()
void ff_put_pixels16_x2_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_put_pixels16_y2_neon()
void ff_put_pixels16_y2_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_put_pixels16_xy2_neon()
void ff_put_pixels16_xy2_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_put_pixels8_neon()
void ff_put_pixels8_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_put_pixels8_x2_neon()
void ff_put_pixels8_x2_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_put_pixels8_y2_neon()
void ff_put_pixels8_y2_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_put_pixels8_xy2_neon()
void ff_put_pixels8_xy2_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_put_pixels16_x2_no_rnd_neon()
void ff_put_pixels16_x2_no_rnd_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_put_pixels16_y2_no_rnd_neon()
void ff_put_pixels16_y2_no_rnd_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_put_pixels16_xy2_no_rnd_neon()
void ff_put_pixels16_xy2_no_rnd_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_put_pixels8_x2_no_rnd_neon()
void ff_put_pixels8_x2_no_rnd_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_put_pixels8_y2_no_rnd_neon()
void ff_put_pixels8_y2_no_rnd_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_put_pixels8_xy2_no_rnd_neon()
void ff_put_pixels8_xy2_no_rnd_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_avg_pixels16_neon()
void ff_avg_pixels16_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_avg_pixels16_x2_neon()
void ff_avg_pixels16_x2_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_avg_pixels16_y2_neon()
void ff_avg_pixels16_y2_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_avg_pixels16_xy2_neon()
void ff_avg_pixels16_xy2_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_avg_pixels8_neon()
void ff_avg_pixels8_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_avg_pixels8_x2_neon()
void ff_avg_pixels8_x2_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_avg_pixels8_y2_neon()
void ff_avg_pixels8_y2_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_avg_pixels8_xy2_neon()
void ff_avg_pixels8_xy2_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_avg_pixels16_x2_no_rnd_neon()
void ff_avg_pixels16_x2_no_rnd_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_avg_pixels16_y2_no_rnd_neon()
void ff_avg_pixels16_y2_no_rnd_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_avg_pixels16_xy2_no_rnd_neon()
void ff_avg_pixels16_xy2_no_rnd_neon (uint8_t * , const uint8_t * , ptrdiff_t , int)
Referenced by ff_hpeldsp_init_neon().
ff_hpeldsp_init_neon()
av_cold void ff_hpeldsp_init_neon (HpelDSPContext * c, int flags)
Definition at line 55 of file hpeldsp_init_neon.c.
Referenced by ff_hpeldsp_init_arm().