FFmpeg: libavcodec/mips/hpeldsp_msa.c File Reference
hpeldsp_msa.c File Reference
#include "libavutil/mips/generic_macros_msa.h"
#include "libavcodec/mips/hpeldsp_mips.h"
Macros
#define PCKEV_AVG_ST_UB(in0, in1, dst, pdst)
#define PCKEV_ST_SB4(in0, in1, in2, in3, in4, in5, in6, in7, pdst, stride)
#define PCKEV_AVG_ST8x4_UB(in1, dst0, in2, dst1, in3, dst2, in4, dst3, pdst, stride)
Functions
static void common_hz_bil_4w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t height)
static void common_hz_bil_8w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t height)
static void common_hz_bil_16w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t height)
static void common_hz_bil_no_rnd_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void common_hz_bil_no_rnd_4x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void common_hz_bil_no_rnd_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void common_hz_bil_no_rnd_8x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void common_hz_bil_and_aver_dst_4w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t height)
static void common_hz_bil_and_aver_dst_8w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t height)
static void common_hz_bil_and_aver_dst_16w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t height)
static void common_vt_bil_4w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t height)
static void common_vt_bil_8w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t height)
static void common_vt_bil_16w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t height)
static void common_vt_bil_no_rnd_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void common_vt_bil_no_rnd_4x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void common_vt_bil_no_rnd_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void common_vt_bil_no_rnd_8x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void common_vt_bil_and_aver_dst_4w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t height)
static void common_vt_bil_and_aver_dst_8w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t height)
static void common_vt_bil_and_aver_dst_16w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t height)
static void common_hv_bil_4w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t height)
static void common_hv_bil_8w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t height)
static void common_hv_bil_16w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t height)
static void common_hv_bil_no_rnd_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void common_hv_bil_no_rnd_4x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void common_hv_bil_no_rnd_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void common_hv_bil_no_rnd_8x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void common_hv_bil_and_aver_dst_4w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t height)
static void common_hv_bil_and_aver_dst_8w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t height)
static void common_hv_bil_and_aver_dst_16w_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, uint8_t height)
static void copy_width8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void copy_16multx8mult_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t width)
static void copy_width16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avg_width4_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avg_width8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avg_width16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
void ff_put_pixels16_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_x2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_y2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_xy2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_x2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_y2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_xy2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels4_x2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels4_y2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels4_xy2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels16_x2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels16_y2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels16_xy2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels8_x2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels8_y2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_no_rnd_pixels8_xy2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_x2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_y2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_xy2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_x2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_y2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_xy2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels4_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels4_x2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels4_y2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels4_xy2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
Macro Definition Documentation
PCKEV_AVG_ST_UB
#define PCKEV_AVG_ST_UB (in0, in1, dst, pdst)
Value:
{                                                             \
    v16u8 tmp_m;                                              \
                                                              \
    tmp_m = (v16u8) __msa_pckev_b((v16i8) in0, (v16i8) in1);  \
    tmp_m = __msa_aver_u_b(tmp_m, (v16u8) dst);               \
    ST_UB(tmp_m, (pdst));                                     \
}
Definition at line 24 of file hpeldsp_msa.c.
Referenced by common_hv_bil_and_aver_dst_16w_msa().
PCKEV_ST_SB4
#define PCKEV_ST_SB4 (in0, in1, in2, in3, in4, in5, in6, in7, pdst, stride)
Value:
{                                                                           \
    v16i8 tmp0_m, tmp1_m, tmp2_m, tmp3_m;                                   \
    uint8_t *pdst_m = (uint8_t *) (pdst);                                   \
                                                                            \
    PCKEV_B4_SB(in0, in1, in2, in3, in4, in5, in6, in7,                     \
                tmp0_m, tmp1_m, tmp2_m, tmp3_m);                            \
    ST_SB4(tmp0_m, tmp1_m, tmp2_m, tmp3_m, pdst_m, stride);                 \
}
Definition at line 33 of file hpeldsp_msa.c.
Referenced by common_hv_bil_16w_msa(), common_hv_bil_no_rnd_16x16_msa(), and common_hv_bil_no_rnd_8x16_msa().
PCKEV_AVG_ST8x4_UB
#define PCKEV_AVG_ST8x4_UB (in1, dst0, in2, dst1, in3, dst2, in4, dst3, pdst, stride)
Value:
{                                                                       \
    v16u8 tmp0_m, tmp1_m, tmp2_m, tmp3_m;                               \
    uint8_t *pdst_m = (uint8_t *) (pdst);                               \
                                                                        \
    PCKEV_B2_UB(in2, in1, in4, in3, tmp0_m, tmp1_m);                    \
    PCKEV_D2_UB(dst1, dst0, dst3, dst2, tmp2_m, tmp3_m);                \
    AVER_UB2_UB(tmp0_m, tmp2_m, tmp1_m, tmp3_m, tmp0_m, tmp1_m);        \
    ST8x4_UB(tmp0_m, tmp1_m, pdst_m, stride);                           \
}
Definition at line 43 of file hpeldsp_msa.c.
Referenced by common_hv_bil_and_aver_dst_8w_msa().
Function Documentation
common_hz_bil_4w_msa()
static void common_hz_bil_4w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t height) static
Definition at line 55 of file hpeldsp_msa.c.
Referenced by ff_put_pixels4_x2_msa().
common_hz_bil_8w_msa()
static void common_hz_bil_8w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t height) static
Definition at line 79 of file hpeldsp_msa.c.
Referenced by ff_put_pixels8_x2_msa().
common_hz_bil_16w_msa()
static void common_hz_bil_16w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t height) static
Definition at line 98 of file hpeldsp_msa.c.
Referenced by ff_put_pixels16_x2_msa().
common_hz_bil_no_rnd_8x8_msa()
static void common_hz_bil_no_rnd_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 122 of file hpeldsp_msa.c.
Referenced by ff_put_no_rnd_pixels8_x2_msa().
common_hz_bil_no_rnd_4x8_msa()
static void common_hz_bil_no_rnd_4x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 144 of file hpeldsp_msa.c.
Referenced by ff_put_no_rnd_pixels8_x2_msa().
common_hz_bil_no_rnd_16x16_msa()
static void common_hz_bil_no_rnd_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 156 of file hpeldsp_msa.c.
Referenced by ff_put_no_rnd_pixels16_x2_msa().
common_hz_bil_no_rnd_8x16_msa()
static void common_hz_bil_no_rnd_8x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 191 of file hpeldsp_msa.c.
Referenced by ff_put_no_rnd_pixels16_x2_msa().
common_hz_bil_and_aver_dst_4w_msa()
static void common_hz_bil_and_aver_dst_4w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t height) static
Definition at line 209 of file hpeldsp_msa.c.
Referenced by ff_avg_pixels4_x2_msa().
common_hz_bil_and_aver_dst_8w_msa()
static void common_hz_bil_and_aver_dst_8w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t height) static
Definition at line 243 of file hpeldsp_msa.c.
Referenced by ff_avg_pixels8_x2_msa().
common_hz_bil_and_aver_dst_16w_msa()
static void common_hz_bil_and_aver_dst_16w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t height) static
Definition at line 264 of file hpeldsp_msa.c.
Referenced by ff_avg_pixels16_x2_msa().
common_vt_bil_4w_msa()
static void common_vt_bil_4w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t height) static
Definition at line 288 of file hpeldsp_msa.c.
Referenced by ff_put_pixels4_y2_msa().
common_vt_bil_8w_msa()
static void common_vt_bil_8w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t height) static
Definition at line 316 of file hpeldsp_msa.c.
Referenced by ff_put_pixels8_y2_msa().
common_vt_bil_16w_msa()
static void common_vt_bil_16w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t height) static
Definition at line 338 of file hpeldsp_msa.c.
Referenced by ff_put_pixels16_y2_msa().
common_vt_bil_no_rnd_8x8_msa()
static void common_vt_bil_no_rnd_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 363 of file hpeldsp_msa.c.
Referenced by ff_put_no_rnd_pixels8_y2_msa().
common_vt_bil_no_rnd_4x8_msa()
static void common_vt_bil_no_rnd_4x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 380 of file hpeldsp_msa.c.
Referenced by ff_put_no_rnd_pixels8_y2_msa().
common_vt_bil_no_rnd_16x16_msa()
static void common_vt_bil_no_rnd_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 390 of file hpeldsp_msa.c.
Referenced by ff_put_no_rnd_pixels16_y2_msa().
common_vt_bil_no_rnd_8x16_msa()
static void common_vt_bil_no_rnd_8x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 417 of file hpeldsp_msa.c.
Referenced by ff_put_no_rnd_pixels16_y2_msa().
common_vt_bil_and_aver_dst_4w_msa()
static void common_vt_bil_and_aver_dst_4w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t height) static
Definition at line 434 of file hpeldsp_msa.c.
Referenced by ff_avg_pixels4_y2_msa().
common_vt_bil_and_aver_dst_8w_msa()
static void common_vt_bil_and_aver_dst_8w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t height) static
Definition at line 468 of file hpeldsp_msa.c.
Referenced by ff_avg_pixels8_y2_msa().
common_vt_bil_and_aver_dst_16w_msa()
static void common_vt_bil_and_aver_dst_16w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t height) static
Definition at line 490 of file hpeldsp_msa.c.
Referenced by ff_avg_pixels16_y2_msa().
common_hv_bil_4w_msa()
static void common_hv_bil_4w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t height) static
Definition at line 523 of file hpeldsp_msa.c.
Referenced by ff_put_pixels4_xy2_msa().
common_hv_bil_8w_msa()
static void common_hv_bil_8w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t height) static
Definition at line 558 of file hpeldsp_msa.c.
Referenced by ff_put_pixels8_xy2_msa().
common_hv_bil_16w_msa()
static void common_hv_bil_16w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t height) static
Definition at line 593 of file hpeldsp_msa.c.
Referenced by ff_put_pixels16_xy2_msa().
common_hv_bil_no_rnd_8x8_msa()
static void common_hv_bil_no_rnd_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 651 of file hpeldsp_msa.c.
Referenced by ff_put_no_rnd_pixels8_xy2_msa().
common_hv_bil_no_rnd_4x8_msa()
static void common_hv_bil_no_rnd_4x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 697 of file hpeldsp_msa.c.
Referenced by ff_put_no_rnd_pixels8_xy2_msa().
common_hv_bil_no_rnd_16x16_msa()
static void common_hv_bil_no_rnd_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 729 of file hpeldsp_msa.c.
Referenced by ff_put_no_rnd_pixels16_xy2_msa().
common_hv_bil_no_rnd_8x16_msa()
static void common_hv_bil_no_rnd_8x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 846 of file hpeldsp_msa.c.
Referenced by ff_put_no_rnd_pixels16_xy2_msa().
common_hv_bil_and_aver_dst_4w_msa()
static void common_hv_bil_and_aver_dst_4w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t height) static
Definition at line 910 of file hpeldsp_msa.c.
Referenced by ff_avg_pixels4_xy2_msa().
common_hv_bil_and_aver_dst_8w_msa()
static void common_hv_bil_and_aver_dst_8w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t height) static
Definition at line 950 of file hpeldsp_msa.c.
Referenced by ff_avg_pixels8_xy2_msa().
common_hv_bil_and_aver_dst_16w_msa()
static void common_hv_bil_and_aver_dst_16w_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, uint8_t height) static
Definition at line 988 of file hpeldsp_msa.c.
Referenced by ff_avg_pixels16_xy2_msa().
copy_width8_msa()
static void copy_width8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 1060 of file hpeldsp_msa.c.
Referenced by ff_put_pixels8_msa().
copy_16multx8mult_msa()
static void copy_16multx8mult_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t width) static
Definition at line 1146 of file hpeldsp_msa.c.
Referenced by copy_width16_msa().
copy_width16_msa()
static void copy_width16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 1174 of file hpeldsp_msa.c.
Referenced by ff_put_pixels16_msa().
avg_width4_msa()
static void avg_width4_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 1208 of file hpeldsp_msa.c.
Referenced by ff_avg_pixels4_msa().
avg_width8_msa()
static void avg_width8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 1253 of file hpeldsp_msa.c.
Referenced by ff_avg_pixels8_msa().
avg_width16_msa()
static void avg_width16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 1279 of file hpeldsp_msa.c.
Referenced by ff_avg_pixels16_msa().
ff_put_pixels16_msa()
void ff_put_pixels16_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1301 of file hpeldsp_msa.c.
ff_put_pixels16_x2_msa()
void ff_put_pixels16_x2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1307 of file hpeldsp_msa.c.
ff_put_pixels16_y2_msa()
void ff_put_pixels16_y2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1313 of file hpeldsp_msa.c.
ff_put_pixels16_xy2_msa()
void ff_put_pixels16_xy2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1319 of file hpeldsp_msa.c.
ff_put_pixels8_msa()
void ff_put_pixels8_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1325 of file hpeldsp_msa.c.
ff_put_pixels8_x2_msa()
void ff_put_pixels8_x2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1331 of file hpeldsp_msa.c.
ff_put_pixels8_y2_msa()
void ff_put_pixels8_y2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1337 of file hpeldsp_msa.c.
ff_put_pixels8_xy2_msa()
void ff_put_pixels8_xy2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1343 of file hpeldsp_msa.c.
ff_put_pixels4_x2_msa()
void ff_put_pixels4_x2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1349 of file hpeldsp_msa.c.
ff_put_pixels4_y2_msa()
void ff_put_pixels4_y2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1355 of file hpeldsp_msa.c.
ff_put_pixels4_xy2_msa()
void ff_put_pixels4_xy2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1361 of file hpeldsp_msa.c.
ff_put_no_rnd_pixels16_x2_msa()
void ff_put_no_rnd_pixels16_x2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1367 of file hpeldsp_msa.c.
ff_put_no_rnd_pixels16_y2_msa()
void ff_put_no_rnd_pixels16_y2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1377 of file hpeldsp_msa.c.
ff_put_no_rnd_pixels16_xy2_msa()
void ff_put_no_rnd_pixels16_xy2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1387 of file hpeldsp_msa.c.
ff_put_no_rnd_pixels8_x2_msa()
void ff_put_no_rnd_pixels8_x2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1398 of file hpeldsp_msa.c.
ff_put_no_rnd_pixels8_y2_msa()
void ff_put_no_rnd_pixels8_y2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1408 of file hpeldsp_msa.c.
ff_put_no_rnd_pixels8_xy2_msa()
void ff_put_no_rnd_pixels8_xy2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1418 of file hpeldsp_msa.c.
ff_avg_pixels16_msa()
void ff_avg_pixels16_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1428 of file hpeldsp_msa.c.
ff_avg_pixels16_x2_msa()
void ff_avg_pixels16_x2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1434 of file hpeldsp_msa.c.
ff_avg_pixels16_y2_msa()
void ff_avg_pixels16_y2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1440 of file hpeldsp_msa.c.
ff_avg_pixels16_xy2_msa()
void ff_avg_pixels16_xy2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1446 of file hpeldsp_msa.c.
ff_avg_pixels8_msa()
void ff_avg_pixels8_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1452 of file hpeldsp_msa.c.
ff_avg_pixels8_x2_msa()
void ff_avg_pixels8_x2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1458 of file hpeldsp_msa.c.
ff_avg_pixels8_y2_msa()
void ff_avg_pixels8_y2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1464 of file hpeldsp_msa.c.
ff_avg_pixels8_xy2_msa()
void ff_avg_pixels8_xy2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1470 of file hpeldsp_msa.c.
ff_avg_pixels4_msa()
void ff_avg_pixels4_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1476 of file hpeldsp_msa.c.
ff_avg_pixels4_x2_msa()
void ff_avg_pixels4_x2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1482 of file hpeldsp_msa.c.
ff_avg_pixels4_y2_msa()
void ff_avg_pixels4_y2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1488 of file hpeldsp_msa.c.
ff_avg_pixels4_xy2_msa()
void ff_avg_pixels4_xy2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Definition at line 1494 of file hpeldsp_msa.c.