FFmpeg: libavcodec/mips/hpeldsp_mips.h File Reference
hpeldsp_mips.h File Reference
#include "libavcodec/bit_depth_template.c"
Functions
void ff_put_pixels16_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels16_x2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels16_y2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels16_xy2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels8_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels8_x2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels8_y2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels8_xy2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels4_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels4_x2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels4_y2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels4_xy2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_no_rnd_pixels16_x2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_no_rnd_pixels16_y2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_no_rnd_pixels16_xy2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_no_rnd_pixels8_x2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_no_rnd_pixels8_y2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_no_rnd_pixels8_xy2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels16_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels16_x2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels16_y2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels16_xy2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels8_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels8_x2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels8_y2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels8_xy2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels4_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels4_x2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels4_y2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels4_xy2_msa (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels16_l2_8_mmi (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, int dst_stride, int src_stride1, int src_stride2, int h)
void ff_put_pixels8_l2_8_mmi (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, int dst_stride, int src_stride1, int src_stride2, int h)
void ff_put_pixels4_l2_8_mmi (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, int dst_stride, int src_stride1, int src_stride2, int h)
void ff_avg_pixels16_l2_8_mmi (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, int dst_stride, int src_stride1, int src_stride2, int h)
void ff_avg_pixels8_l2_8_mmi (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, int dst_stride, int src_stride1, int src_stride2, int h)
void ff_avg_pixels4_l2_8_mmi (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, int dst_stride, int src_stride1, int src_stride2, int h)
void ff_put_no_rnd_pixels16_l2_8_mmi (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, int dst_stride, int src_stride1, int src_stride2, int h)
void ff_put_no_rnd_pixels8_l2_8_mmi (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, int dst_stride, int src_stride1, int src_stride2, int h)
void ff_put_pixels16_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels16_x2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels16_y2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels16_xy2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels8_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels8_x2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels8_y2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels8_xy2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels4_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels4_x2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels4_y2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_pixels4_xy2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_no_rnd_pixels16_x2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_no_rnd_pixels16_y2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_no_rnd_pixels16_xy2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_no_rnd_pixels8_x2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_no_rnd_pixels8_y2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_put_no_rnd_pixels8_xy2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels16_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels16_x2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels16_y2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels16_xy2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels8_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels8_x2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels8_y2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels8_xy2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels4_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels4_x2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels4_y2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
void ff_avg_pixels4_xy2_8_mmi (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int32_t h)
Function Documentation
ff_put_pixels16_msa()
void ff_put_pixels16_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_pixels16_x2_msa()
void ff_put_pixels16_x2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_pixels16_y2_msa()
void ff_put_pixels16_y2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_pixels16_xy2_msa()
void ff_put_pixels16_xy2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_pixels8_msa()
void ff_put_pixels8_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_pixels8_x2_msa()
void ff_put_pixels8_x2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_pixels8_y2_msa()
void ff_put_pixels8_y2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_pixels8_xy2_msa()
void ff_put_pixels8_xy2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_pixels4_msa()
void ff_put_pixels4_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_pixels4_x2_msa()
void ff_put_pixels4_x2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_pixels4_y2_msa()
void ff_put_pixels4_y2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_pixels4_xy2_msa()
void ff_put_pixels4_xy2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_no_rnd_pixels16_x2_msa()
void ff_put_no_rnd_pixels16_x2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_no_rnd_pixels16_y2_msa()
void ff_put_no_rnd_pixels16_y2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_no_rnd_pixels16_xy2_msa()
void ff_put_no_rnd_pixels16_xy2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_no_rnd_pixels8_x2_msa()
void ff_put_no_rnd_pixels8_x2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_no_rnd_pixels8_y2_msa()
void ff_put_no_rnd_pixels8_y2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_no_rnd_pixels8_xy2_msa()
void ff_put_no_rnd_pixels8_xy2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_avg_pixels16_msa()
void ff_avg_pixels16_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_avg_pixels16_x2_msa()
void ff_avg_pixels16_x2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_avg_pixels16_y2_msa()
void ff_avg_pixels16_y2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_avg_pixels16_xy2_msa()
void ff_avg_pixels16_xy2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_avg_pixels8_msa()
void ff_avg_pixels8_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_avg_pixels8_x2_msa()
void ff_avg_pixels8_x2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_avg_pixels8_y2_msa()
void ff_avg_pixels8_y2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_avg_pixels8_xy2_msa()
void ff_avg_pixels8_xy2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_avg_pixels4_msa()
void ff_avg_pixels4_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_avg_pixels4_x2_msa()
void ff_avg_pixels4_x2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_avg_pixels4_y2_msa()
void ff_avg_pixels4_y2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_avg_pixels4_xy2_msa()
void ff_avg_pixels4_xy2_msa (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_pixels16_l2_8_mmi()
void ff_put_pixels16_l2_8_mmi (uint8_t * dst, const uint8_t * src1, const uint8_t * src2, int dst_stride, int src_stride1, int src_stride2, int h) inline
Definition at line 454 of file hpeldsp_mmi.c.
Referenced by ff_put_h264_qpel16_mc01_mmi(), ff_put_h264_qpel16_mc03_mmi(), ff_put_h264_qpel16_mc10_mmi(), ff_put_h264_qpel16_mc11_mmi(), ff_put_h264_qpel16_mc13_mmi(), ff_put_h264_qpel16_mc30_mmi(), ff_put_h264_qpel16_mc31_mmi(), ff_put_h264_qpel16_mc33_mmi(), ff_put_pixels16_x2_8_mmi(), and ff_put_pixels16_y2_8_mmi().
ff_put_pixels8_l2_8_mmi()
void ff_put_pixels8_l2_8_mmi (uint8_t * dst, const uint8_t * src1, const uint8_t * src2, int dst_stride, int src_stride1, int src_stride2, int h) inline
Definition at line 393 of file hpeldsp_mmi.c.
Referenced by ff_put_h264_qpel8_mc01_mmi(), ff_put_h264_qpel8_mc03_mmi(), ff_put_h264_qpel8_mc10_mmi(), ff_put_h264_qpel8_mc11_mmi(), ff_put_h264_qpel8_mc13_mmi(), ff_put_h264_qpel8_mc30_mmi(), ff_put_h264_qpel8_mc31_mmi(), ff_put_h264_qpel8_mc33_mmi(), ff_put_pixels8_x2_8_mmi(), and ff_put_pixels8_y2_8_mmi().
ff_put_pixels4_l2_8_mmi()
void ff_put_pixels4_l2_8_mmi (uint8_t * dst, const uint8_t * src1, const uint8_t * src2, int dst_stride, int src_stride1, int src_stride2, int h) inline
Definition at line 333 of file hpeldsp_mmi.c.
Referenced by ff_put_h264_qpel4_mc01_mmi(), ff_put_h264_qpel4_mc03_mmi(), ff_put_h264_qpel4_mc10_mmi(), ff_put_h264_qpel4_mc11_mmi(), ff_put_h264_qpel4_mc12_mmi(), ff_put_h264_qpel4_mc13_mmi(), ff_put_h264_qpel4_mc21_mmi(), ff_put_h264_qpel4_mc23_mmi(), ff_put_h264_qpel4_mc30_mmi(), ff_put_h264_qpel4_mc31_mmi(), ff_put_h264_qpel4_mc32_mmi(), ff_put_h264_qpel4_mc33_mmi(), ff_put_pixels4_x2_8_mmi(), and ff_put_pixels4_y2_8_mmi().
ff_avg_pixels16_l2_8_mmi()
void ff_avg_pixels16_l2_8_mmi (uint8_t * dst, const uint8_t * src1, const uint8_t * src2, int dst_stride, int src_stride1, int src_stride2, int h) inline
Definition at line 677 of file hpeldsp_mmi.c.
Referenced by ff_avg_h264_qpel16_mc01_mmi(), ff_avg_h264_qpel16_mc03_mmi(), ff_avg_h264_qpel16_mc10_mmi(), ff_avg_h264_qpel16_mc11_mmi(), ff_avg_h264_qpel16_mc13_mmi(), ff_avg_h264_qpel16_mc30_mmi(), ff_avg_h264_qpel16_mc31_mmi(), and ff_avg_h264_qpel16_mc33_mmi().
ff_avg_pixels8_l2_8_mmi()
void ff_avg_pixels8_l2_8_mmi (uint8_t * dst, const uint8_t * src1, const uint8_t * src2, int dst_stride, int src_stride1, int src_stride2, int h) inline
Definition at line 605 of file hpeldsp_mmi.c.
Referenced by ff_avg_h264_qpel8_mc01_mmi(), ff_avg_h264_qpel8_mc03_mmi(), ff_avg_h264_qpel8_mc10_mmi(), ff_avg_h264_qpel8_mc11_mmi(), ff_avg_h264_qpel8_mc13_mmi(), ff_avg_h264_qpel8_mc30_mmi(), ff_avg_h264_qpel8_mc31_mmi(), ff_avg_h264_qpel8_mc33_mmi(), ff_avg_pixels16_l2_8_mmi(), ff_avg_pixels8_x2_8_mmi(), and ff_avg_pixels8_y2_8_mmi().
ff_avg_pixels4_l2_8_mmi()
void ff_avg_pixels4_l2_8_mmi (uint8_t * dst, const uint8_t * src1, const uint8_t * src2, int dst_stride, int src_stride1, int src_stride2, int h) inline
Definition at line 533 of file hpeldsp_mmi.c.
Referenced by ff_avg_h264_qpel4_mc01_mmi(), ff_avg_h264_qpel4_mc03_mmi(), ff_avg_h264_qpel4_mc10_mmi(), ff_avg_h264_qpel4_mc11_mmi(), ff_avg_h264_qpel4_mc12_mmi(), ff_avg_h264_qpel4_mc13_mmi(), ff_avg_h264_qpel4_mc21_mmi(), ff_avg_h264_qpel4_mc23_mmi(), ff_avg_h264_qpel4_mc30_mmi(), ff_avg_h264_qpel4_mc31_mmi(), ff_avg_h264_qpel4_mc32_mmi(), ff_avg_h264_qpel4_mc33_mmi(), ff_avg_pixels4_x2_8_mmi(), and ff_avg_pixels4_y2_8_mmi().
ff_put_no_rnd_pixels16_l2_8_mmi()
void ff_put_no_rnd_pixels16_l2_8_mmi (uint8_t * dst, const uint8_t * src1, const uint8_t * src2, int dst_stride, int src_stride1, int src_stride2, int h)
ff_put_no_rnd_pixels8_l2_8_mmi()
void ff_put_no_rnd_pixels8_l2_8_mmi (uint8_t * dst, const uint8_t * src1, const uint8_t * src2, int dst_stride, int src_stride1, int src_stride2, int h) inline
Definition at line 729 of file hpeldsp_mmi.c.
Referenced by ff_put_no_rnd_pixels8_x2_8_mmi(), and ff_put_no_rnd_pixels8_y2_8_mmi().
ff_put_pixels16_8_mmi()
void ff_put_pixels16_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
Referenced by ff_put_h264_qpel16_mc00_mmi(), and ff_put_vc1_mspel_mc00_16_mmi().
ff_put_pixels16_x2_8_mmi()
void ff_put_pixels16_x2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_pixels16_y2_8_mmi()
void ff_put_pixels16_y2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_pixels16_xy2_8_mmi()
void ff_put_pixels16_xy2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_pixels8_8_mmi()
void ff_put_pixels8_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
Referenced by ff_put_h264_qpel8_mc00_mmi(), and ff_put_vc1_mspel_mc00_mmi().
ff_put_pixels8_x2_8_mmi()
void ff_put_pixels8_x2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_pixels8_y2_8_mmi()
void ff_put_pixels8_y2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_pixels8_xy2_8_mmi()
void ff_put_pixels8_xy2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_pixels4_8_mmi()
void ff_put_pixels4_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
Referenced by ff_put_h264_qpel4_mc00_mmi().
ff_put_pixels4_x2_8_mmi()
void ff_put_pixels4_x2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_pixels4_y2_8_mmi()
void ff_put_pixels4_y2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_pixels4_xy2_8_mmi()
void ff_put_pixels4_xy2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_no_rnd_pixels16_x2_8_mmi()
void ff_put_no_rnd_pixels16_x2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_no_rnd_pixels16_y2_8_mmi()
void ff_put_no_rnd_pixels16_y2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_no_rnd_pixels16_xy2_8_mmi()
void ff_put_no_rnd_pixels16_xy2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_no_rnd_pixels8_x2_8_mmi()
void ff_put_no_rnd_pixels8_x2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_no_rnd_pixels8_y2_8_mmi()
void ff_put_no_rnd_pixels8_y2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_put_no_rnd_pixels8_xy2_8_mmi()
void ff_put_no_rnd_pixels8_xy2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_avg_pixels16_8_mmi()
void ff_avg_pixels16_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
Referenced by ff_avg_h264_qpel16_mc00_mmi(), and ff_avg_vc1_mspel_mc00_16_mmi().
ff_avg_pixels16_x2_8_mmi()
void ff_avg_pixels16_x2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_avg_pixels16_y2_8_mmi()
void ff_avg_pixels16_y2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_avg_pixels16_xy2_8_mmi()
void ff_avg_pixels16_xy2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_avg_pixels8_8_mmi()
void ff_avg_pixels8_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
Referenced by ff_avg_h264_qpel8_mc00_mmi(), and ff_avg_vc1_mspel_mc00_mmi().
ff_avg_pixels8_x2_8_mmi()
void ff_avg_pixels8_x2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_avg_pixels8_y2_8_mmi()
void ff_avg_pixels8_y2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_avg_pixels8_xy2_8_mmi()
void ff_avg_pixels8_xy2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_avg_pixels4_8_mmi()
void ff_avg_pixels4_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
Referenced by ff_avg_h264_qpel4_mc00_mmi().
ff_avg_pixels4_x2_8_mmi()
void ff_avg_pixels4_x2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_avg_pixels4_y2_8_mmi()
void ff_avg_pixels4_y2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)
ff_avg_pixels4_xy2_8_mmi()
void ff_avg_pixels4_xy2_8_mmi (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int32_t h)