FFmpeg: libavcodec/hpeldsp.c File Reference
hpeldsp.c File Reference
Half-pel DSP functions.
#include "libavutil/attributes.h"
#include "libavutil/intreadwrite.h"
#include "hpeldsp.h"
#include "hpel_template.c"
#include "pel_template.c"
Macros
#define BIT_DEPTH 8
#define PIXOP2(OPNAME, OP)
#define op_avg(a, b) a = rnd_avg32(a, b)
#define op_put(a, b) a = b
#define put_no_rnd_pixels8_8_c put_pixels8_8_c
#define hpel_funcs(prefix, idx, num)
Functions
av_cold void ff_hpeldsp_init (HpelDSPContext *c, int flags)
Detailed Description
Half-pel DSP functions.
Definition in file hpeldsp.c.
Macro Definition Documentation
BIT_DEPTH
#define BIT_DEPTH 8
Definition at line 34 of file hpeldsp.c.
PIXOP2
#define PIXOP2 (OPNAME, OP)
Definition at line 38 of file hpeldsp.c.
op_avg
#define op_avg (a, b) a = rnd_avg32(a, b)
Definition at line 330 of file hpeldsp.c.
op_put
#define op_put (a, b) a = b
Definition at line 331 of file hpeldsp.c.
put_no_rnd_pixels8_8_c
#define put_no_rnd_pixels8_8_c put_pixels8_8_c
Definition at line 332 of file hpeldsp.c.
hpel_funcs
#define hpel_funcs (prefix, idx, num)
Value:
c->prefix ## _pixels_tab idx [0] = prefix ## _pixels ## num ## _8_c; \
    c->prefix ## _pixels_tab idx [1] = prefix ## _pixels ## num ## _x2_8_c; \
    c->prefix ## _pixels_tab idx [2] = prefix ## _pixels ## num ## _y2_8_c; \
    c->prefix ## _pixels_tab idx [3] = prefix ## _pixels ## num ## _xy2_8_c
Referenced by ff_hpeldsp_init().
Function Documentation
ff_hpeldsp_init()
av_cold void ff_hpeldsp_init (HpelDSPContext * c, int flags)
Definition at line 338 of file hpeldsp.c.
Referenced by dct_init(), decode_init(), ff_mjpeg_decode_init(), ff_vp56_init_context(), ipvideo_decode_init(), mca(), mimic_decode_init(), svq1_decode_init(), svq1_encode_init(), svq3_decode_init(), and vp3_decode_init().