FFmpeg: libavcodec/hpeldsp.h File Reference
hpeldsp.h File Reference
Half-pel DSP functions.
#include <stdint.h>
#include <stddef.h>
Data Structures
struct HpelDSPContext
Half-pel DSP context.
Typedefs
typedef void(* op_pixels_func) (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
Functions
void ff_hpeldsp_init (HpelDSPContext *c, int flags)
void ff_hpeldsp_init_aarch64 (HpelDSPContext *c, int flags)
void ff_hpeldsp_init_alpha (HpelDSPContext *c, int flags)
void ff_hpeldsp_init_arm (HpelDSPContext *c, int flags)
void ff_hpeldsp_init_ppc (HpelDSPContext *c, int flags)
void ff_hpeldsp_init_x86 (HpelDSPContext *c, int flags)
void ff_hpeldsp_init_mips (HpelDSPContext *c, int flags)
Detailed Description
Half-pel DSP functions.
Definition in file hpeldsp.h.
Typedef Documentation
op_pixels_func
typedef void(* op_pixels_func) (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
Definition at line 38 of file hpeldsp.h.
Function Documentation
ff_hpeldsp_init()
void ff_hpeldsp_init (HpelDSPContext * c, int flags)
Definition at line 338 of file hpeldsp.c.
Referenced by dct_init(), decode_init(), ff_mjpeg_decode_init(), ff_vp56_init_context(), ipvideo_decode_init(), mca(), mimic_decode_init(), svq1_decode_init(), svq1_encode_init(), svq3_decode_init(), and vp3_decode_init().
ff_hpeldsp_init_aarch64()
void ff_hpeldsp_init_aarch64 (HpelDSPContext * c, int flags)
Definition at line 86 of file hpeldsp_init_aarch64.c.
Referenced by ff_hpeldsp_init().
ff_hpeldsp_init_alpha()
void ff_hpeldsp_init_alpha (HpelDSPContext * c, int flags)
Definition at line 177 of file hpeldsp_alpha.c.
Referenced by ff_hpeldsp_init().
ff_hpeldsp_init_arm()
void ff_hpeldsp_init_arm (HpelDSPContext * c, int flags)
Definition at line 45 of file hpeldsp_init_arm.c.
Referenced by ff_hpeldsp_init().
ff_hpeldsp_init_ppc()
void ff_hpeldsp_init_ppc (HpelDSPContext * c, int flags)
Definition at line 371 of file hpeldsp_altivec.c.
Referenced by ff_hpeldsp_init().
ff_hpeldsp_init_x86()
void ff_hpeldsp_init_x86 (HpelDSPContext * c, int flags)
Definition at line 317 of file hpeldsp_init.c.
Referenced by ff_hpeldsp_init().
ff_hpeldsp_init_mips()
void ff_hpeldsp_init_mips (HpelDSPContext * c, int flags)
Definition at line 114 of file hpeldsp_init_mips.c.
Referenced by ff_hpeldsp_init().