FFmpeg: libavcodec/hq_hqa.c File Reference
hq_hqa.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/intreadwrite.h"
#include "avcodec.h"
#include "canopus.h"
#include "get_bits.h"
#include "internal.h"
#include "hq_hqa.h"
#include "hq_hqadsp.h"
Functions
static void put_blocks (HQContext *c, AVFrame *pic, int plane, int x, int y, int ilace, int16_t *block0, int16_t *block1)
static int hq_decode_block (HQContext *c, GetBitContext *gb, int16_t block[64], int qsel, int is_chroma, int is_hqa)
static int hq_decode_mb (HQContext *c, AVFrame *pic, GetBitContext *gb, int x, int y)
static int hq_decode_frame (HQContext *ctx, AVFrame *pic, int prof_num, size_t data_size)
static int hqa_decode_mb (HQContext *c, AVFrame *pic, int qgroup, GetBitContext *gb, int x, int y)
static int hqa_decode_slice (HQContext *ctx, AVFrame *pic, GetBitContext *gb, int quant, int slice_no, int w, int h)
static int hqa_decode_frame (HQContext *ctx, AVFrame *pic, size_t data_size)
static int hq_hqa_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int hq_hqa_decode_init (AVCodecContext *avctx)
static av_cold int hq_hqa_decode_close (AVCodecContext *avctx)
Variables
AVCodec ff_hq_hqa_decoder
Function Documentation
put_blocks()
static void put_blocks (HQContext * c, AVFrame * pic, int plane, int x, int y, int ilace, int16_t * block0, int16_t * block1) inline static
Definition at line 50 of file hq_hqa.c.
Referenced by hq_decode_mb(), and hqa_decode_mb().
hq_decode_block()
static int hq_decode_block (HQContext * c, GetBitContext * gb, int16_t block[64], int qsel, int is_chroma, int is_hqa) static
Definition at line 62 of file hq_hqa.c.
Referenced by hq_decode_mb(), and hqa_decode_mb().
hq_decode_mb()
static int hq_decode_mb (HQContext * c, AVFrame * pic, GetBitContext * gb, int x, int y) static
Definition at line 93 of file hq_hqa.c.
Referenced by hq_decode_frame().
hq_decode_frame()
static int hq_decode_frame (HQContext * ctx, AVFrame * pic, int prof_num, size_t data_size) static
Definition at line 116 of file hq_hqa.c.
Referenced by hq_hqa_decode_frame().
hqa_decode_mb()
static int hqa_decode_mb (HQContext * c, AVFrame * pic, int qgroup, GetBitContext * gb, int x, int y) static
Definition at line 178 of file hq_hqa.c.
Referenced by hqa_decode_slice().
hqa_decode_slice()
static int hqa_decode_slice (HQContext * ctx, AVFrame * pic, GetBitContext * gb, int quant, int slice_no, int w, int h) static
Definition at line 218 of file hq_hqa.c.
Referenced by hqa_decode_frame().
hqa_decode_frame()
static int hqa_decode_frame (HQContext * ctx, AVFrame * pic, size_t data_size) static
Definition at line 239 of file hq_hqa.c.
Referenced by hq_hqa_decode_frame().
hq_hqa_decode_frame()
static int hq_hqa_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 295 of file hq_hqa.c.
hq_hqa_decode_init()
static av_cold int hq_hqa_decode_init (AVCodecContext * avctx) static
Definition at line 356 of file hq_hqa.c.
hq_hqa_decode_close()
static av_cold int hq_hqa_decode_close (AVCodecContext * avctx) static
Definition at line 366 of file hq_hqa.c.
Variable Documentation
ff_hq_hqa_decoder
AVCodec ff_hq_hqa_decoder
Initial value:
= {
    .name           = "hq_hqa",
    .long_name      = NULL_IF_CONFIG_SMALL("Canopus HQ/HQA"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_HQ_HQA,
    .priv_data_size = sizeof(HQContext),
    .init           = hq_hqa_decode_init,
    .decode         = hq_hqa_decode_frame,
    .close          = hq_hqa_decode_close,
    .capabilities   = AV_CODEC_CAP_DR1,
    .caps_internal  = FF_CODEC_CAP_INIT_THREADSAFE |
                      FF_CODEC_CAP_INIT_CLEANUP,
}
Definition at line 376 of file hq_hqa.c.