FFmpeg: libswscale/hscale_fast_bilinear.c File Reference
hscale_fast_bilinear.c File Reference
#include "swscale_internal.h"
Functions
void ff_hyscale_fast_c (SwsContext *c, int16_t *dst, int dstWidth, const uint8_t *src, int srcW, int xInc)
void ff_hcscale_fast_c (SwsContext *c, int16_t *dst1, int16_t *dst2, int dstWidth, const uint8_t *src1, const uint8_t *src2, int srcW, int xInc)
Function Documentation
ff_hyscale_fast_c()
void ff_hyscale_fast_c (SwsContext * c, int16_t * dst, int dstWidth, const uint8_t * src, int srcW, int xInc)
Definition at line 23 of file hscale_fast_bilinear.c.
Referenced by sws_init_swscale(), and usePal().
ff_hcscale_fast_c()
void ff_hcscale_fast_c (SwsContext * c, int16_t * dst1, int16_t * dst2, int dstWidth, const uint8_t * src1, const uint8_t * src2, int srcW, int xInc)
Definition at line 38 of file hscale_fast_bilinear.c.
Referenced by sws_init_swscale(), and usePal().