FFmpeg: libswscale/hscale.c File Reference
hscale.c File Reference
#include "swscale_internal.h"
Data Structures
struct FilterContext
Scaler instance data.
struct ColorContext
Color conversion instance data.
Functions
static int lum_h_scale (SwsContext *c, SwsFilterDescriptor *desc, int sliceY, int sliceH)
static int lum_convert (SwsContext *c, SwsFilterDescriptor *desc, int sliceY, int sliceH)
int ff_init_desc_fmt_convert (SwsFilterDescriptor *desc, SwsSlice *src, SwsSlice *dst, uint32_t *pal)
initializes lum pixel format conversion descriptor
int ff_init_desc_hscale (SwsFilterDescriptor *desc, SwsSlice *src, SwsSlice *dst, uint16_t *filter, int *filter_pos, int filter_size, int xInc)
initializes lum horizontal scaling descriptor
static int chr_h_scale (SwsContext *c, SwsFilterDescriptor *desc, int sliceY, int sliceH)
static int chr_convert (SwsContext *c, SwsFilterDescriptor *desc, int sliceY, int sliceH)
int ff_init_desc_cfmt_convert (SwsFilterDescriptor *desc, SwsSlice *src, SwsSlice *dst, uint32_t *pal)
initializes chr pixel format conversion descriptor
int ff_init_desc_chscale (SwsFilterDescriptor *desc, SwsSlice *src, SwsSlice *dst, uint16_t *filter, int *filter_pos, int filter_size, int xInc)
initializes chr horizontal scaling descriptor
static int no_chr_scale (SwsContext *c, SwsFilterDescriptor *desc, int sliceY, int sliceH)
int ff_init_desc_no_chr (SwsFilterDescriptor *desc, SwsSlice *src, SwsSlice *dst)
Function Documentation
lum_h_scale()
static int lum_h_scale (SwsContext * c, SwsFilterDescriptor * desc, int sliceY, int sliceH) static
Definition at line 38 of file hscale.c.
Referenced by ff_init_desc_hscale().
lum_convert()
static int lum_convert (SwsContext * c, SwsFilterDescriptor * desc, int sliceY, int sliceH) static
Definition at line 86 of file hscale.c.
Referenced by ff_init_desc_fmt_convert().
ff_init_desc_fmt_convert()
int ff_init_desc_fmt_convert (SwsFilterDescriptor * desc, SwsSlice * src, SwsSlice * dst, uint32_t * pal)
initializes lum pixel format conversion descriptor
Definition at line 127 of file hscale.c.
Referenced by ff_init_filters().
ff_init_desc_hscale()
int ff_init_desc_hscale (SwsFilterDescriptor * desc, SwsSlice * src, SwsSlice * dst, uint16_t * filter, int * filter_pos, int filter_size, int xInc)
initializes lum horizontal scaling descriptor
Definition at line 144 of file hscale.c.
Referenced by ff_init_filters().
chr_h_scale()
static int chr_h_scale (SwsContext * c, SwsFilterDescriptor * desc, int sliceY, int sliceH) static
Definition at line 166 of file hscale.c.
Referenced by ff_init_desc_chscale().
chr_convert()
static int chr_convert (SwsContext * c, SwsFilterDescriptor * desc, int sliceY, int sliceH) static
Definition at line 202 of file hscale.c.
Referenced by ff_init_desc_cfmt_convert().
ff_init_desc_cfmt_convert()
int ff_init_desc_cfmt_convert (SwsFilterDescriptor * desc, SwsSlice * src, SwsSlice * dst, uint32_t * pal)
initializes chr pixel format conversion descriptor
Definition at line 235 of file hscale.c.
Referenced by ff_init_filters().
ff_init_desc_chscale()
int ff_init_desc_chscale (SwsFilterDescriptor * desc, SwsSlice * src, SwsSlice * dst, uint16_t * filter, int * filter_pos, int filter_size, int xInc)
initializes chr horizontal scaling descriptor
Definition at line 250 of file hscale.c.
Referenced by ff_init_filters().
no_chr_scale()
static int no_chr_scale (SwsContext * c, SwsFilterDescriptor * desc, int sliceY, int sliceH) static
Definition at line 272 of file hscale.c.
Referenced by ff_init_desc_no_chr().
ff_init_desc_no_chr()
int ff_init_desc_no_chr (SwsFilterDescriptor * desc, SwsSlice * src, SwsSlice * dst)
Definition at line 281 of file hscale.c.
Referenced by ff_init_filters().