FFmpeg: libavcodec/htmlsubtitles.c File Reference
htmlsubtitles.c File Reference
#include "libavutil/avstring.h"
#include "libavutil/common.h"
#include "libavutil/parseutils.h"
#include "htmlsubtitles.h"
Data Structures
struct SrtStack
Enumerations
enum {
PARAM_UNKNOWN = -1, PARAM_SIZE, PARAM_COLOR, PARAM_FACE,
PARAM_NUMBER
}
Functions
static int html_color_parse (void *log_ctx, const char *str)
static void rstrip_spaces_buf (AVBPrint *buf)
void ff_htmlmarkup_to_ass (void *log_ctx, AVBPrint *dst, const char *in)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PARAM_UNKNOWN
PARAM_SIZE
PARAM_COLOR
PARAM_FACE
PARAM_NUMBER
Definition at line 34 of file htmlsubtitles.c.
Function Documentation
html_color_parse()
static int html_color_parse (void * log_ctx, const char * str) static
Definition at line 26 of file htmlsubtitles.c.
Referenced by ff_htmlmarkup_to_ass().
rstrip_spaces_buf()
static void rstrip_spaces_buf (AVBPrint * buf) static
Definition at line 47 of file htmlsubtitles.c.
Referenced by ff_htmlmarkup_to_ass().
ff_htmlmarkup_to_ass()
void ff_htmlmarkup_to_ass (void * log_ctx, AVBPrint * dst, const char * in)
Definition at line 53 of file htmlsubtitles.c.
Referenced by sami_paragraph_to_ass(), and srt_to_ass().