FFmpeg: libavformat/httpauth.c File Reference
httpauth.c File Reference
#include "httpauth.h"
#include "libavutil/base64.h"
#include "libavutil/avstring.h"
#include "internal.h"
#include "libavutil/random_seed.h"
#include "libavutil/md5.h"
#include "urldecode.h"
#include "avformat.h"
Functions
static void handle_basic_params (HTTPAuthState *state, const char *key, int key_len, char **dest, int *dest_len)
static void handle_digest_params (HTTPAuthState *state, const char *key, int key_len, char **dest, int *dest_len)
static void handle_digest_update (HTTPAuthState *state, const char *key, int key_len, char **dest, int *dest_len)
static void choose_qop (char *qop, int size)
void ff_http_auth_handle_header (HTTPAuthState *state, const char *key, const char *value)
static void update_md5_strings (struct AVMD5 *md5ctx,...)
static char * make_digest_auth (HTTPAuthState *state, const char *username, const char *password, const char *uri, const char *method)
char * ff_http_auth_create_response (HTTPAuthState *state, const char *auth, const char *path, const char *method)
Function Documentation
handle_basic_params()
static void handle_basic_params (HTTPAuthState * state, const char * key, int key_len, char ** dest, int * dest_len) static
Definition at line 31 of file httpauth.c.
Referenced by ff_http_auth_handle_header().
handle_digest_params()
static void handle_digest_params (HTTPAuthState * state, const char * key, int key_len, char ** dest, int * dest_len) static
Definition at line 40 of file httpauth.c.
Referenced by ff_http_auth_handle_header().
handle_digest_update()
static void handle_digest_update (HTTPAuthState * state, const char * key, int key_len, char ** dest, int * dest_len) static
Definition at line 66 of file httpauth.c.
Referenced by ff_http_auth_handle_header().
choose_qop()
static void choose_qop (char * qop, int size) static
Definition at line 77 of file httpauth.c.
Referenced by ff_http_auth_handle_header().
ff_http_auth_handle_header()
void ff_http_auth_handle_header (HTTPAuthState * state, const char * key, const char * value)
Definition at line 90 of file httpauth.c.
Referenced by ff_rtsp_open_transport_ctx(), and process_line().
update_md5_strings()
static void update_md5_strings (struct AVMD5 * md5ctx, ...) static
Definition at line 122 of file httpauth.c.
Referenced by make_digest_auth().
make_digest_auth()
static char* make_digest_auth (HTTPAuthState * state, const char * username, const char * password, const char * uri, const char * method) static
Definition at line 137 of file httpauth.c.
Referenced by ff_http_auth_create_response().
ff_http_auth_create_response()
char* ff_http_auth_create_response (HTTPAuthState * state, const char * auth, const char * path, const char * method)
Definition at line 245 of file httpauth.c.
Referenced by ff_rtsp_open_transport_ctx(), and http_connect().