FFmpeg: libavformat/http.h File Reference
http.h File Reference
#include "url.h"
Macros
#define HTTP_HEADERS_SIZE 4096
Functions
void ff_http_init_auth_state (URLContext *dest, const URLContext *src)
Initialize the authentication state based on another HTTP URLContext.
int ff_http_do_new_request (URLContext *h, const char *uri)
Send a new HTTP request, reusing the old connection.
int ff_http_averror (int status_code, int default_averror)
Macro Definition Documentation
HTTP_HEADERS_SIZE
#define HTTP_HEADERS_SIZE 4096
Definition at line 27 of file http.h.
Referenced by http_connect().
Function Documentation
ff_http_init_auth_state()
void ff_http_init_auth_state (URLContext * dest, const URLContext * src)
Initialize the authentication state based on another HTTP URLContext.
This can be used to pre-initialize the authentication parameters if they are known beforehand, to avoid having to do an initial failing request just to get the parameters.
Parameters
dest URL context whose authentication state gets updated
src URL context whose authentication state gets copied
Definition at line 171 of file http.c.
Referenced by ff_rtsp_open_transport_ctx().
ff_http_do_new_request()
int ff_http_do_new_request (URLContext * h, const char * uri)
Send a new HTTP request, reusing the old connection.
Parameters
h pointer to the resource
uri uri used to perform the request
Returns
a negative value if an error condition occurred, 0 otherwise
Definition at line 299 of file http.c.
Referenced by rtmp_http_send_cmd().
ff_http_averror()
int ff_http_averror (int status_code, int default_averror)
Definition at line 317 of file http.c.
Referenced by check_http_code(), ff_rtsp_averror(), http_open_cnx(), and process_line().