FFmpeg: libavformat/http.c File Reference
http.c File Reference
#include "config.h"
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/opt.h"
#include "libavutil/time.h"
#include "avformat.h"
#include "http.h"
#include "httpauth.h"
#include "internal.h"
#include "network.h"
#include "os_support.h"
#include "url.h"
Data Structures
struct HTTPContext
Macros
#define BUFFER_SIZE MAX_URL_SIZE
#define MAX_REDIRECTS 8
#define HTTP_SINGLE 1
#define HTTP_MUTLI 2
#define OFFSET(x) offsetof(HTTPContext, x)
#define D AV_OPT_FLAG_DECODING_PARAM
#define E AV_OPT_FLAG_ENCODING_PARAM
#define DEFAULT_USER_AGENT "Lavf/" AV_STRINGIFY(LIBAVFORMAT_VERSION)
#define HTTP_CLASS(flavor)
Enumerations
enum HandshakeState { LOWER_PROTO, READ_HEADERS, WRITE_REPLY_HEADERS, FINISH }
Functions
static int http_connect (URLContext *h, const char *path, const char *local_path, const char *hoststr, const char *auth, const char *proxyauth, int *new_location)
static int http_read_header (URLContext *h, int *new_location)
void ff_http_init_auth_state (URLContext *dest, const URLContext *src)
Initialize the authentication state based on another HTTP URLContext.
static int http_open_cnx_internal (URLContext *h, AVDictionary **options)
static int http_open_cnx (URLContext *h, AVDictionary **options)
int ff_http_do_new_request (URLContext *h, const char *uri)
Send a new HTTP request, reusing the old connection.
int ff_http_averror (int status_code, int default_averror)
static int http_write_reply (URLContext *h, int status_code)
static void handle_http_errors (URLContext *h, int error)
static int http_handshake (URLContext *c)
static int http_listen (URLContext *h, const char *uri, int flags, AVDictionary **options)
static int http_open (URLContext *h, const char *uri, int flags, AVDictionary **options)
static int http_accept (URLContext *s, URLContext **c)
static int http_getc (HTTPContext *s)
static int http_get_line (HTTPContext *s, char *line, int line_size)
static int check_http_code (URLContext *h, int http_code, const char *end)
static int parse_location (HTTPContext *s, const char *p)
static void parse_content_range (URLContext *h, const char *p)
static int parse_content_encoding (URLContext *h, const char *p)
static int parse_icy (HTTPContext *s, const char *tag, const char *p)
static int parse_cookie (HTTPContext *s, const char *p, AVDictionary **cookies)
static int cookie_string (AVDictionary *dict, char **cookies)
static int process_line (URLContext *h, char *line, int line_count, int *new_location)
static int get_cookies (HTTPContext *s, char **cookies, const char *path, const char *domain)
Create a string containing cookie values for use as a HTTP cookie header field value for a particular path and domain from the cookie values stored in the HTTP protocol context.
static int has_header (const char *str, const char *header)
static int http_buf_read (URLContext *h, uint8_t *buf, int size)
static int64_t http_seek_internal (URLContext *h, int64_t off, int whence, int force_reconnect)
static int http_read_stream (URLContext *h, uint8_t *buf, int size)
static int http_read_stream_all (URLContext *h, uint8_t *buf, int size)
static void update_metadata (HTTPContext *s, char *data)
static int store_icy (URLContext *h, int size)
static int http_read (URLContext *h, uint8_t *buf, int size)
static int http_write (URLContext *h, const uint8_t *buf, int size)
static int http_shutdown (URLContext *h, int flags)
static int http_close (URLContext *h)
static int64_t http_seek (URLContext *h, int64_t off, int whence)
static int http_get_file_handle (URLContext *h)
Variables
static const AVOption options []
Macro Definition Documentation
BUFFER_SIZE
#define BUFFER_SIZE MAX_URL_SIZE
Definition at line 47 of file http.c.
Referenced by http_getc(), http_seek_internal(), and http_write_reply().
MAX_REDIRECTS
#define MAX_REDIRECTS 8
Definition at line 48 of file http.c.
Referenced by http_open_cnx().
HTTP_SINGLE
#define HTTP_SINGLE 1
Definition at line 49 of file http.c.
Referenced by http_listen().
HTTP_MUTLI
#define HTTP_MUTLI 2
Definition at line 50 of file http.c.
OFFSET
#define OFFSET (x) offsetof(HTTPContext, x)
Definition at line 125 of file http.c.
D
#define D AV_OPT_FLAG_DECODING_PARAM
Definition at line 126 of file http.c.
E
#define E AV_OPT_FLAG_ENCODING_PARAM
Definition at line 127 of file http.c.
DEFAULT_USER_AGENT
#define DEFAULT_USER_AGENT "Lavf/" AV_STRINGIFY(LIBAVFORMAT_VERSION)
Definition at line 128 of file http.c.
Referenced by http_connect().
HTTP_CLASS
#define HTTP_CLASS (flavor)
Value:
static const AVClass flavor ## _context_class = {   \
    .class_name = # flavor,                         \
    .item_name  = av_default_item_name,             \
    .option     = options,                          \
    .version    = LIBAVUTIL_VERSION_INT,            \
}
Definition at line 1527 of file http.c.
Enumeration Type Documentation
HandshakeState
enum HandshakeState
Enumerator
LOWER_PROTO
READ_HEADERS
WRITE_REPLY_HEADERS
FINISH
Definition at line 51 of file http.c.
Function Documentation
http_connect()
static int http_connect (URLContext * h, const char * path, const char * local_path, const char * hoststr, const char * auth, const char * proxyauth, int * new_location) static
Definition at line 1002 of file http.c.
Referenced by http_open_cnx_internal().
http_read_header()
static int http_read_header (URLContext * h, int * new_location) static
Definition at line 970 of file http.c.
Referenced by http_connect(), http_handshake(), and http_read_stream().
ff_http_init_auth_state()
void ff_http_init_auth_state (URLContext * dest, const URLContext * src)
Initialize the authentication state based on another HTTP URLContext.
This can be used to pre-initialize the authentication parameters if they are known beforehand, to avoid having to do an initial failing request just to get the parameters.
Parameters
dest URL context whose authentication state gets updated
src URL context whose authentication state gets copied
Definition at line 171 of file http.c.
Referenced by ff_rtsp_open_transport_ctx().
http_open_cnx_internal()
static int http_open_cnx_internal (URLContext * h, AVDictionary ** options) static
Definition at line 181 of file http.c.
Referenced by http_open_cnx().
http_open_cnx()
static int http_open_cnx (URLContext * h, AVDictionary ** options) static
Definition at line 243 of file http.c.
Referenced by ff_http_do_new_request(), http_open(), and http_seek_internal().
ff_http_do_new_request()
int ff_http_do_new_request (URLContext * h, const char * uri)
Send a new HTTP request, reusing the old connection.
Parameters
h pointer to the resource
uri uri used to perform the request
Returns
a negative value if an error condition occurred, 0 otherwise
Definition at line 299 of file http.c.
Referenced by rtmp_http_send_cmd().
ff_http_averror()
int ff_http_averror (int status_code, int default_averror)
Definition at line 317 of file http.c.
Referenced by check_http_code(), ff_rtsp_averror(), http_open_cnx(), and process_line().
http_write_reply()
static int http_write_reply (URLContext * h, int status_code) static
Definition at line 334 of file http.c.
Referenced by handle_http_errors(), and http_handshake().
handle_http_errors()
static void handle_http_errors (URLContext * h, int error) static
Definition at line 408 of file http.c.
Referenced by http_handshake().
http_handshake()
static int http_handshake (URLContext * c) static
Definition at line 414 of file http.c.
Referenced by http_listen().
http_listen()
static int http_listen (URLContext * h, const char * uri, int flags, AVDictionary ** options) static
Definition at line 450 of file http.c.
Referenced by http_open().
http_open()
static int http_open (URLContext * h, const char * uri, int flags, AVDictionary ** options) static
Definition at line 481 of file http.c.
http_accept()
static int http_accept (URLContext * s, URLContext ** c) static
Definition at line 522 of file http.c.
http_getc()
static int http_getc (HTTPContext * s) static
Definition at line 542 of file http.c.
Referenced by http_get_line().
http_get_line()
static int http_get_line (HTTPContext * s, char * line, int line_size) static
Definition at line 559 of file http.c.
Referenced by http_buf_read(), and http_read_header().
check_http_code()
static int check_http_code (URLContext * h, int http_code, const char * end) static
Definition at line 583 of file http.c.
Referenced by process_line().
parse_location()
static int parse_location (HTTPContext * s, const char * p) static
Definition at line 598 of file http.c.
Referenced by process_line().
parse_content_range()
static void parse_content_range (URLContext * h, const char * p) static
Definition at line 612 of file http.c.
Referenced by process_line().
parse_content_encoding()
static int parse_content_encoding (URLContext * h, const char * p) static
Definition at line 627 of file http.c.
Referenced by process_line().
parse_icy()
static int parse_icy (HTTPContext * s, const char * tag, const char * p) static
Definition at line 661 of file http.c.
Referenced by process_line().
parse_cookie()
static int parse_cookie (HTTPContext * s, const char * p, AVDictionary ** cookies) static
Definition at line 683 of file http.c.
Referenced by get_cookies(), and process_line().
cookie_string()
static int cookie_string (AVDictionary * dict, char ** cookies) static
Definition at line 697 of file http.c.
Referenced by http_read_header().
process_line()
static int process_line (URLContext * h, char * line, int line_count, int * new_location) static
Definition at line 720 of file http.c.
Referenced by http_read_header().
get_cookies()
static int get_cookies (HTTPContext * s, char ** cookies, const char * path, const char * domain) static
Create a string containing cookie values for use as a HTTP cookie header field value for a particular path and domain from the cookie values stored in the HTTP protocol context.
The cookie string is stored in *cookies.
Returns
a negative value if an error condition occurred, 0 otherwise
Definition at line 865 of file http.c.
Referenced by http_connect().
has_header()
static int has_header (const char * str, const char * header) inline static
Definition at line 962 of file http.c.
Referenced by http_connect().
http_buf_read()
static int http_buf_read (URLContext * h, uint8_t * buf, int size) static
Definition at line 1167 of file http.c.
Referenced by http_read_stream().
http_seek_internal()
static int64_t http_seek_internal (URLContext * h, int64_t off, int whence, int force_reconnect) static
Definition at line 1465 of file http.c.
Referenced by http_buf_read(), http_read_stream(), and http_seek().
http_read_stream()
static int http_read_stream (URLContext * h, uint8_t * buf, int size) static
Definition at line 1264 of file http.c.
Referenced by http_read(), and http_read_stream_all().
http_read_stream_all()
static int http_read_stream_all (URLContext * h, uint8_t * buf, int size) static
Definition at line 1309 of file http.c.
Referenced by store_icy().
update_metadata()
static void update_metadata (HTTPContext * s, char * data) static
Definition at line 1321 of file http.c.
Referenced by store_icy().
store_icy()
static int store_icy (URLContext * h, int size) static
Definition at line 1347 of file http.c.
Referenced by http_read().
http_read()
static int http_read (URLContext * h, uint8_t * buf, int size) static
Definition at line 1385 of file http.c.
http_write()
static int http_write (URLContext * h, const uint8_t * buf, int size) static
Definition at line 1402 of file http.c.
http_shutdown()
static int http_shutdown (URLContext * h, int flags) static
Definition at line 1428 of file http.c.
Referenced by http_close().
http_close()
static int http_close (URLContext * h) static
Definition at line 1445 of file http.c.
http_seek()
static int64_t http_seek (URLContext * h, int64_t off, int whence) static
Definition at line 1516 of file http.c.
http_get_file_handle()
static int http_get_file_handle (URLContext * h) static
Definition at line 1521 of file http.c.
Variable Documentation
options
const AVOption options[] static
Definition at line 130 of file http.c.