FFmpeg: libavformat/httpauth.h File Reference
httpauth.h File Reference
Data Structures
struct DigestParams
struct HTTPAuthState
HTTP Authentication state structure.
Enumerations
enum HTTPAuthType { HTTP_AUTH_NONE = 0, HTTP_AUTH_BASIC, HTTP_AUTH_DIGEST }
Authentication types, ordered from weakest to strongest.
Functions
void ff_http_auth_handle_header (HTTPAuthState *state, const char *key, const char *value)
char * ff_http_auth_create_response (HTTPAuthState *state, const char *auth, const char *path, const char *method)
Enumeration Type Documentation
HTTPAuthType
enum HTTPAuthType
Authentication types, ordered from weakest to strongest.
Enumerator
HTTP_AUTH_NONE
No authentication specified.
HTTP_AUTH_BASIC
HTTP 1.0 Basic auth from RFC 1945 (also in RFC 2617)
HTTP_AUTH_DIGEST
HTTP 1.1 Digest auth from RFC 2617.
Definition at line 28 of file httpauth.h.
Function Documentation
ff_http_auth_handle_header()
void ff_http_auth_handle_header (HTTPAuthState * state, const char * key, const char * value)
Definition at line 90 of file httpauth.c.
Referenced by ff_rtsp_open_transport_ctx(), and process_line().
ff_http_auth_create_response()
char* ff_http_auth_create_response (HTTPAuthState * state, const char * auth, const char * path, const char * method)
Definition at line 245 of file httpauth.c.
Referenced by ff_rtsp_open_transport_ctx(), and http_connect().