FFmpeg: libavcodec/huffyuv.c File Reference
huffyuv.c File Reference
huffyuv codec for libavcodec.
#include <stdint.h>
#include "libavutil/mem.h"
#include "avcodec.h"
#include "bswapdsp.h"
#include "huffyuv.h"
Functions
int ff_huffyuv_generate_bits_table (uint32_t *dst, const uint8_t *len_table, int n)
av_cold int ff_huffyuv_alloc_temp (HYuvContext *s)
av_cold void ff_huffyuv_common_init (AVCodecContext *avctx)
av_cold void ff_huffyuv_common_end (HYuvContext *s)
Detailed Description
huffyuv codec for libavcodec.
Definition in file huffyuv.c.
Function Documentation
ff_huffyuv_generate_bits_table()
int ff_huffyuv_generate_bits_table (uint32_t * dst, const uint8_t * len_table, int n)
Definition at line 39 of file huffyuv.c.
Referenced by read_huffman_tables(), and store_huffman_tables().
ff_huffyuv_alloc_temp()
av_cold int ff_huffyuv_alloc_temp (HYuvContext * s)
Definition at line 58 of file huffyuv.c.
Referenced by decode_init(), and encode_init().
ff_huffyuv_common_init()
av_cold void ff_huffyuv_common_init (AVCodecContext * avctx)
Definition at line 71 of file huffyuv.c.
Referenced by decode_init(), and encode_init().
ff_huffyuv_common_end()
av_cold void ff_huffyuv_common_end (HYuvContext * s)
Definition at line 87 of file huffyuv.c.
Referenced by decode_end(), decode_init(), encode_end(), and encode_init().