FFmpeg: libavcodec/x86/huffyuvdsp_init.c File Reference
huffyuvdsp_init.c File Reference
#include "config.h"
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/x86/asm.h"
#include "libavutil/x86/cpu.h"
#include "libavcodec/huffyuvdsp.h"
Functions
void ff_add_bytes_mmx (uint8_t *dst, uint8_t *src, intptr_t w)
void ff_add_bytes_sse2 (uint8_t *dst, uint8_t *src, intptr_t w)
void ff_add_hfyu_median_pred_mmxext (uint8_t *dst, const uint8_t *top, const uint8_t *diff, intptr_t w, int *left, int *left_top)
void ff_add_hfyu_median_pred_sse2 (uint8_t *dst, const uint8_t *top, const uint8_t *diff, intptr_t w, int *left, int *left_top)
int ff_add_hfyu_left_pred_ssse3 (uint8_t *dst, const uint8_t *src, intptr_t w, int left)
int ff_add_hfyu_left_pred_sse4 (uint8_t *dst, const uint8_t *src, intptr_t w, int left)
void ff_add_hfyu_left_pred_bgr32_mmx (uint8_t *dst, const uint8_t *src, intptr_t w, uint8_t *left)
void ff_add_hfyu_left_pred_bgr32_sse2 (uint8_t *dst, const uint8_t *src, intptr_t w, uint8_t *left)
av_cold void ff_huffyuvdsp_init_x86 (HuffYUVDSPContext *c)
Function Documentation
ff_add_bytes_mmx()
void ff_add_bytes_mmx (uint8_t * dst, uint8_t * src, intptr_t w)
Referenced by ff_huffyuvdsp_init_x86().
ff_add_bytes_sse2()
void ff_add_bytes_sse2 (uint8_t * dst, uint8_t * src, intptr_t w)
Referenced by ff_huffyuvdsp_init_x86().
ff_add_hfyu_median_pred_mmxext()
void ff_add_hfyu_median_pred_mmxext (uint8_t * dst, const uint8_t * top, const uint8_t * diff, intptr_t w, int * left, int * left_top)
Referenced by ff_huffyuvdsp_init_x86().
ff_add_hfyu_median_pred_sse2()
void ff_add_hfyu_median_pred_sse2 (uint8_t * dst, const uint8_t * top, const uint8_t * diff, intptr_t w, int * left, int * left_top)
Referenced by ff_huffyuvdsp_init_x86().
ff_add_hfyu_left_pred_ssse3()
int ff_add_hfyu_left_pred_ssse3 (uint8_t * dst, const uint8_t * src, intptr_t w, int left)
Referenced by ff_huffyuvdsp_init_x86().
ff_add_hfyu_left_pred_sse4()
int ff_add_hfyu_left_pred_sse4 (uint8_t * dst, const uint8_t * src, intptr_t w, int left)
Referenced by ff_huffyuvdsp_init_x86().
ff_add_hfyu_left_pred_bgr32_mmx()
void ff_add_hfyu_left_pred_bgr32_mmx (uint8_t * dst, const uint8_t * src, intptr_t w, uint8_t * left)
Referenced by ff_huffyuvdsp_init_x86().
ff_add_hfyu_left_pred_bgr32_sse2()
void ff_add_hfyu_left_pred_bgr32_sse2 (uint8_t * dst, const uint8_t * src, intptr_t w, uint8_t * left)
Referenced by ff_huffyuvdsp_init_x86().
ff_huffyuvdsp_init_x86()
av_cold void ff_huffyuvdsp_init_x86 (HuffYUVDSPContext * c)
Definition at line 86 of file huffyuvdsp_init.c.
Referenced by ff_huffyuvdsp_init().