FFmpeg: libavcodec/huffyuvenc.c File Reference
huffyuvenc.c File Reference
huffyuv encoder
#include "avcodec.h"
#include "huffyuv.h"
#include "huffman.h"
#include "huffyuvencdsp.h"
#include "internal.h"
#include "put_bits.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
Macros
#define STATS_OUT_SIZE 21*MAX_N*3 + 4
#define LOAD4
#define LOADEND int y0 = s->temp[0][width-1];
#define LOADEND_14 int y0 = s->temp16[0][width-1] & mask;
#define LOADEND_16 int y0 = s->temp16[0][width-1];
#define STATEND s->stats[plane][y0]++;
#define STATEND_16 s->stats[plane][y0>>2]++;
#define WRITEEND put_bits(&s->pb, s->len[plane][y0], s->bits[plane][y0]);
#define WRITEEND_16
#define LOAD2
#define LOAD2_14
#define LOAD2_16
#define STAT2
#define STAT2_16
#define WRITE2
#define WRITE2_16
#define LOAD2
#define STAT2
#define WRITE2
#define LOAD_GBRA
#define STAT_BGRA
#define WRITE_GBRA
#define OFFSET(x) offsetof(HYuvContext, x)
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
#define COMMON_OPTIONS
Functions
static void diff_bytes (HYuvContext *s, uint8_t *dst, const uint8_t *src0, const uint8_t *src1, int w)
static int sub_left_prediction (HYuvContext *s, uint8_t *dst, const uint8_t *src, int w, int left)
static void sub_left_prediction_bgr32 (HYuvContext *s, uint8_t *dst, const uint8_t *src, int w, int *red, int *green, int *blue, int *alpha)
static void sub_left_prediction_rgb24 (HYuvContext *s, uint8_t *dst, uint8_t *src, int w, int *red, int *green, int *blue)
static void sub_median_prediction (HYuvContext *s, uint8_t *dst, const uint8_t *src1, const uint8_t *src2, int w, int *left, int *left_top)
static int store_table (HYuvContext *s, const uint8_t *len, uint8_t *buf)
static int store_huffman_tables (HYuvContext *s, uint8_t *buf)
static av_cold int encode_init (AVCodecContext *avctx)
static int encode_422_bitstream (HYuvContext *s, int offset, int count)
static int encode_plane_bitstream (HYuvContext *s, int width, int plane)
static int encode_gray_bitstream (HYuvContext *s, int count)
static int encode_bgra_bitstream (HYuvContext *s, int count, int planes)
static int encode_frame (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *pict, int *got_packet)
static av_cold int encode_end (AVCodecContext *avctx)
Variables
static const AVOption normal_options []
static const AVOption ff_options []
static const AVClass normal_class
static const AVClass ff_class
AVCodec ff_huffyuv_encoder
Detailed Description
huffyuv encoder
Definition in file huffyuvenc.c.
Macro Definition Documentation
STATS_OUT_SIZE
#define STATS_OUT_SIZE 21*MAX_N*3 + 4
Referenced by encode_frame(), and encode_init().
LOAD4
#define LOAD4
Value:
int y0 = y[2 * i];\
            int y1 = y[2 * i + 1];\
            int u0 = u[i];\
            int v0 = v[i];
Referenced by encode_422_bitstream().
LOADEND
#define LOADEND int y0 = s->temp[0][width-1];
Referenced by encode_plane_bitstream().
LOADEND_14
#define LOADEND_14 int y0 = s->temp16[0][width-1] & mask;
Referenced by encode_plane_bitstream().
LOADEND_16
#define LOADEND_16 int y0 = s->temp16[0][width-1];
Referenced by encode_plane_bitstream().
STATEND
#define STATEND s->stats[plane][y0]++;
Referenced by encode_plane_bitstream().
STATEND_16
#define STATEND_16 s->stats[plane][y0>>2]++;
Referenced by encode_plane_bitstream().
WRITEEND
#define WRITEEND put_bits(&s->pb, s->len[plane][y0], s->bits[plane][y0]);
Referenced by encode_plane_bitstream().
WRITEEND_16
#define WRITEEND_16
Value:
put_bits(&s->pb, s->len[plane][y0>>2], s->bits[plane][y0>>2]);\
            put_bits(&s->pb, 2, y0&3);
Referenced by encode_plane_bitstream().
LOAD2 [1/2]
#define LOAD2
Value:
int y0 = s->temp[0][2 * i];\
            int y1 = s->temp[0][2 * i + 1];
Referenced by encode_gray_bitstream(), and encode_plane_bitstream().
LOAD2_14
#define LOAD2_14
Value:
int y0 = s->temp16[0][2 * i] & mask;\
            int y1 = s->temp16[0][2 * i + 1] & mask;
Referenced by encode_plane_bitstream().
LOAD2_16
#define LOAD2_16
Value:
int y0 = s->temp16[0][2 * i];\
            int y1 = s->temp16[0][2 * i + 1];
Referenced by encode_plane_bitstream().
STAT2 [1/2]
#define STAT2
Value:
s->stats[plane][y0]++;\
            s->stats[plane][y1]++;
Referenced by encode_gray_bitstream(), and encode_plane_bitstream().
STAT2_16
#define STAT2_16
Value:
s->stats[plane][y0>>2]++;\
            s->stats[plane][y1>>2]++;
Referenced by encode_plane_bitstream().
WRITE2 [1/2]
#define WRITE2
Value:
put_bits(&s->pb, s->len[plane][y0], s->bits[plane][y0]);\
            put_bits(&s->pb, s->len[plane][y1], s->bits[plane][y1]);
Referenced by encode_gray_bitstream(), and encode_plane_bitstream().
WRITE2_16
#define WRITE2_16
Value:
put_bits(&s->pb, s->len[plane][y0>>2], s->bits[plane][y0>>2]);\
            put_bits(&s->pb, 2, y0&3);\
            put_bits(&s->pb, s->len[plane][y1>>2], s->bits[plane][y1>>2]);\
            put_bits(&s->pb, 2, y1&3);
Referenced by encode_plane_bitstream().
LOAD2 [2/2]
#define LOAD2
Value:
int y0 = s->temp[0][2 * i];\
            int y1 = s->temp[0][2 * i + 1];
STAT2 [2/2]
#define STAT2
Value:
s->stats[0][y0]++;\
            s->stats[0][y1]++;
WRITE2 [2/2]
#define WRITE2
Value:
put_bits(&s->pb, s->len[0][y0], s->bits[0][y0]);\
            put_bits(&s->pb, s->len[0][y1], s->bits[0][y1]);
LOAD_GBRA
#define LOAD_GBRA
Value:
int g = s->temp[0][planes == 3 ? 3 * i + 1 : 4 * i + G];            \
    int b =(s->temp[0][planes == 3 ? 3 * i + 2 : 4 * i + B] - g) & 0xFF;\
    int r =(s->temp[0][planes == 3 ? 3 * i + 0 : 4 * i + R] - g) & 0xFF;\
    int a = s->temp[0][planes * i + A];
Referenced by encode_bgra_bitstream().
STAT_BGRA
#define STAT_BGRA
Value:
s->stats[0][b]++;                                                   \
    s->stats[1][g]++;                                                   \
    s->stats[2][r]++;                                                   \
    if (planes == 4)                                                    \
        s->stats[2][a]++;
Referenced by encode_bgra_bitstream().
WRITE_GBRA
#define WRITE_GBRA
Value:
put_bits(&s->pb, s->len[1][g], s->bits[1][g]);                      \
    put_bits(&s->pb, s->len[0][b], s->bits[0][b]);                      \
    put_bits(&s->pb, s->len[2][r], s->bits[2][r]);                      \
    if (planes == 4)                                                    \
        put_bits(&s->pb, s->len[2][a], s->bits[2][a]);
Referenced by encode_bgra_bitstream().
OFFSET
#define OFFSET (x) offsetof(HYuvContext, x)
Definition at line 1058 of file huffyuvenc.c.
VE
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 1059 of file huffyuvenc.c.
COMMON_OPTIONS
#define COMMON_OPTIONS
Value:
{ "non_deterministic", "Allow multithreading for e.g. context=1 at the expense of determinism", \
      OFFSET(non_determ), AV_OPT_TYPE_BOOL, { .i64 = 1 }, \
      0, 1, VE }, \
    { "pred", "Prediction method", OFFSET(predictor), AV_OPT_TYPE_INT, { .i64 = LEFT }, LEFT, MEDIAN, VE, "pred" }, \
        { "left",   NULL, 0, AV_OPT_TYPE_CONST, { .i64 = LEFT },   INT_MIN, INT_MAX, VE, "pred" }, \
        { "plane",  NULL, 0, AV_OPT_TYPE_CONST, { .i64 = PLANE },  INT_MIN, INT_MAX, VE, "pred" }, \
        { "median", NULL, 0, AV_OPT_TYPE_CONST, { .i64 = MEDIAN }, INT_MIN, INT_MAX, VE, "pred" }, \
Definition at line 1061 of file huffyuvenc.c.
Function Documentation
diff_bytes()
static void diff_bytes (HYuvContext * s, uint8_t * dst, const uint8_t * src0, const uint8_t * src1, int w) inline static
Definition at line 40 of file huffyuvenc.c.
Referenced by encode_frame().
sub_left_prediction()
static int sub_left_prediction (HYuvContext * s, uint8_t * dst, const uint8_t * src, int w, int left) inline static
Definition at line 50 of file huffyuvenc.c.
Referenced by encode_frame().
sub_left_prediction_bgr32()
static void sub_left_prediction_bgr32 (HYuvContext * s, uint8_t * dst, const uint8_t * src, int w, int * red, int * green, int * blue, int * alpha) inline static
Definition at line 93 of file huffyuvenc.c.
Referenced by encode_frame().
sub_left_prediction_rgb24()
static void sub_left_prediction_rgb24 (HYuvContext * s, uint8_t * dst, uint8_t * src, int w, int * red, int * green, int * blue) inline static
Definition at line 128 of file huffyuvenc.c.
Referenced by encode_frame().
sub_median_prediction()
static void sub_median_prediction (HYuvContext * s, uint8_t * dst, const uint8_t * src1, const uint8_t * src2, int w, int * left, int * left_top) static
Definition at line 156 of file huffyuvenc.c.
Referenced by encode_frame().
store_table()
static int store_table (HYuvContext * s, const uint8_t * len, uint8_t * buf) static
Definition at line 165 of file huffyuvenc.c.
Referenced by store_huffman_tables().
store_huffman_tables()
static int store_huffman_tables (HYuvContext * s, uint8_t * buf) static
Definition at line 190 of file huffyuvenc.c.
Referenced by encode_frame(), and encode_init().
encode_init()
static av_cold int encode_init (AVCodecContext * avctx) static
Definition at line 212 of file huffyuvenc.c.
encode_422_bitstream()
static int encode_422_bitstream (HYuvContext * s, int offset, int count) static
Definition at line 449 of file huffyuvenc.c.
Referenced by encode_frame().
encode_plane_bitstream()
static int encode_plane_bitstream (HYuvContext * s, int width, int plane) static
Definition at line 504 of file huffyuvenc.c.
Referenced by encode_frame().
encode_gray_bitstream()
static int encode_gray_bitstream (HYuvContext * s, int count) static
Definition at line 666 of file huffyuvenc.c.
Referenced by encode_frame().
encode_bgra_bitstream()
static int encode_bgra_bitstream (HYuvContext * s, int count, int planes) inline static
Definition at line 711 of file huffyuvenc.c.
Referenced by encode_frame().
encode_frame()
static int encode_frame (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * pict, int * got_packet) static
Definition at line 762 of file huffyuvenc.c.
encode_end()
static av_cold int encode_end (AVCodecContext * avctx) static
Definition at line 1046 of file huffyuvenc.c.
Variable Documentation
normal_options
const AVOption normal_options[] static
Initial value:
= {
    COMMON_OPTIONS
    { NULL },
}
Definition at line 1070 of file huffyuvenc.c.
ff_options
const AVOption ff_options[] static
Initial value:
= {
    COMMON_OPTIONS
    { "context", "Set per-frame huffman tables", OFFSET(context), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, 1, VE },
    { NULL },
}
Definition at line 1075 of file huffyuvenc.c.
normal_class
const AVClass normal_class static
Initial value:
= {
    .class_name = "huffyuv",
    .item_name  = av_default_item_name,
    .option     = normal_options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1081 of file huffyuvenc.c.
ff_class
const AVClass ff_class static
Initial value:
= {
    .class_name = "ffvhuff",
    .item_name  = av_default_item_name,
    .option     = ff_options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1088 of file huffyuvenc.c.
ff_huffyuv_encoder
AVCodec ff_huffyuv_encoder
Initial value:
= {
    .name           = "huffyuv",
    .long_name      = NULL_IF_CONFIG_SMALL("Huffyuv / HuffYUV"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_HUFFYUV,
    .priv_data_size = sizeof(HYuvContext),
    .init           = encode_init,
    .encode2        = encode_frame,
    .close          = encode_end,
    .capabilities   = AV_CODEC_CAP_FRAME_THREADS | AV_CODEC_CAP_INTRA_ONLY,
    .priv_class     = &normal_class,
    .pix_fmts       = (const enum AVPixelFormat[]){
        AV_PIX_FMT_YUV422P, AV_PIX_FMT_RGB24,
        AV_PIX_FMT_RGB32, AV_PIX_FMT_NONE
    },
    .caps_internal  = FF_CODEC_CAP_INIT_THREADSAFE |
                      FF_CODEC_CAP_INIT_CLEANUP,
}
Definition at line 1095 of file huffyuvenc.c.