FFmpeg: libavcodec/x86/huffyuvencdsp_mmx.c File Reference
huffyuvencdsp_mmx.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/x86/asm.h"
#include "libavutil/x86/cpu.h"
#include "libavcodec/huffyuvencdsp.h"
#include "libavcodec/mathops.h"
Functions
void ff_diff_bytes_mmx (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, intptr_t w)
void ff_diff_bytes_sse2 (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, intptr_t w)
void ff_diff_bytes_avx2 (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, intptr_t w)
av_cold void ff_huffyuvencdsp_init_x86 (HuffYUVEncDSPContext *c)
Function Documentation
ff_diff_bytes_mmx()
void ff_diff_bytes_mmx (uint8_t * dst, const uint8_t * src1, const uint8_t * src2, intptr_t w)
Referenced by ff_huffyuvencdsp_init_x86().
ff_diff_bytes_sse2()
void ff_diff_bytes_sse2 (uint8_t * dst, const uint8_t * src1, const uint8_t * src2, intptr_t w)
Referenced by ff_huffyuvencdsp_init_x86().
ff_diff_bytes_avx2()
void ff_diff_bytes_avx2 (uint8_t * dst, const uint8_t * src1, const uint8_t * src2, intptr_t w)
Referenced by ff_huffyuvencdsp_init_x86().
ff_huffyuvencdsp_init_x86()
av_cold void ff_huffyuvencdsp_init_x86 (HuffYUVEncDSPContext * c)
Definition at line 83 of file huffyuvencdsp_mmx.c.
Referenced by ff_huffyuvencdsp_init().