FFmpeg: libavcodec/huffyuvencdsp.c File Reference
huffyuvencdsp.c File Reference
#include "config.h"
#include "libavutil/attributes.h"
#include "huffyuvencdsp.h"
#include "mathops.h"
Macros
#define pb_7f (~0UL / 255 * 0x7f)
#define pb_80 (~0UL / 255 * 0x80)
Functions
static void diff_bytes_c (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, intptr_t w)
static void sub_hfyu_median_pred_c (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, intptr_t w, int *left, int *left_top)
av_cold void ff_huffyuvencdsp_init (HuffYUVEncDSPContext *c)
Macro Definition Documentation
pb_7f
#define pb_7f (~0UL / 255 * 0x7f)
Definition at line 25 of file huffyuvencdsp.c.
Referenced by diff_bytes_c().
pb_80
#define pb_80 (~0UL / 255 * 0x80)
Definition at line 26 of file huffyuvencdsp.c.
Referenced by diff_bytes_c().
Function Documentation
diff_bytes_c()
static void diff_bytes_c (uint8_t * dst, const uint8_t * src1, const uint8_t * src2, intptr_t w) static
Definition at line 28 of file huffyuvencdsp.c.
Referenced by ff_huffyuvencdsp_init().
sub_hfyu_median_pred_c()
static void sub_hfyu_median_pred_c (uint8_t * dst, const uint8_t * src1, const uint8_t * src2, intptr_t w, int * left, int * left_top) static
Definition at line 56 of file huffyuvencdsp.c.
Referenced by ff_huffyuvencdsp_init().
ff_huffyuvencdsp_init()
av_cold void ff_huffyuvencdsp_init (HuffYUVEncDSPContext * c)
Definition at line 77 of file huffyuvencdsp.c.
Referenced by encode_init(), png_enc_init(), and utvideo_encode_init().