FFmpeg: libavcodec/huffyuvdsp.c File Reference
huffyuvdsp.c File Reference
#include <stdint.h>
#include "config.h"
#include "libavutil/attributes.h"
#include "mathops.h"
#include "huffyuvdsp.h"
Macros
#define pb_7f (~0UL / 255 * 0x7f)
#define pb_80 (~0UL / 255 * 0x80)
Functions
static void add_bytes_c (uint8_t *dst, uint8_t *src, intptr_t w)
static void add_hfyu_median_pred_c (uint8_t *dst, const uint8_t *src1, const uint8_t *diff, intptr_t w, int *left, int *left_top)
static int add_hfyu_left_pred_c (uint8_t *dst, const uint8_t *src, intptr_t w, int acc)
static void add_hfyu_left_pred_bgr32_c (uint8_t *dst, const uint8_t *src, intptr_t w, uint8_t *left)
av_cold void ff_huffyuvdsp_init (HuffYUVDSPContext *c)
Macro Definition Documentation
pb_7f
#define pb_7f (~0UL / 255 * 0x7f)
Definition at line 27 of file huffyuvdsp.c.
Referenced by add_bytes_c().
pb_80
#define pb_80 (~0UL / 255 * 0x80)
Definition at line 28 of file huffyuvdsp.c.
Referenced by add_bytes_c().
Function Documentation
add_bytes_c()
static void add_bytes_c (uint8_t * dst, uint8_t * src, intptr_t w) static
Definition at line 30 of file huffyuvdsp.c.
Referenced by ff_huffyuvdsp_init().
add_hfyu_median_pred_c()
static void add_hfyu_median_pred_c (uint8_t * dst, const uint8_t * src1, const uint8_t * diff, intptr_t w, int * left, int * left_top) static
Definition at line 43 of file huffyuvdsp.c.
Referenced by ff_huffyuvdsp_init().
add_hfyu_left_pred_c()
static int add_hfyu_left_pred_c (uint8_t * dst, const uint8_t * src, intptr_t w, int acc) static
Definition at line 63 of file huffyuvdsp.c.
Referenced by ff_huffyuvdsp_init().
add_hfyu_left_pred_bgr32_c()
static void add_hfyu_left_pred_bgr32_c (uint8_t * dst, const uint8_t * src, intptr_t w, uint8_t * left) static
Definition at line 84 of file huffyuvdsp.c.
Referenced by ff_huffyuvdsp_init().
ff_huffyuvdsp_init()
av_cold void ff_huffyuvdsp_init (HuffYUVDSPContext * c)
Definition at line 108 of file huffyuvdsp.c.
Referenced by decode_init(), lag_decode_init(), magy_decode_init(), and vble_decode_init().