FFmpeg: libavcodec/huffyuvencdsp.h File Reference
huffyuvencdsp.h File Reference
#include <stdint.h>
Data Structures
struct HuffYUVEncDSPContext
Functions
void ff_huffyuvencdsp_init (HuffYUVEncDSPContext *c)
void ff_huffyuvencdsp_init_x86 (HuffYUVEncDSPContext *c)
Function Documentation
ff_huffyuvencdsp_init()
void ff_huffyuvencdsp_init (HuffYUVEncDSPContext * c)
Definition at line 77 of file huffyuvencdsp.c.
Referenced by encode_init(), png_enc_init(), and utvideo_encode_init().
ff_huffyuvencdsp_init_x86()
void ff_huffyuvencdsp_init_x86 (HuffYUVEncDSPContext * c)
Definition at line 83 of file huffyuvencdsp_mmx.c.
Referenced by ff_huffyuvencdsp_init().