FFmpeg: libavutil/hwcontext_cuda.c File Reference
hwcontext_cuda.c File Reference
#include "buffer.h"
#include "common.h"
#include "hwcontext.h"
#include "hwcontext_internal.h"
#include "hwcontext_cuda_internal.h"
#include "mem.h"
#include "pixdesc.h"
#include "pixfmt.h"
Data Structures
struct CUDAFramesContext
Macros
#define CUDA_FRAME_ALIGNMENT 256
Functions
static void cuda_buffer_free (void *opaque, uint8_t *data)
static AVBufferRef * cuda_pool_alloc (void *opaque, int size)
static int cuda_frames_init (AVHWFramesContext *ctx)
static int cuda_get_buffer (AVHWFramesContext *ctx, AVFrame *frame)
static int cuda_transfer_get_formats (AVHWFramesContext *ctx, enum AVHWFrameTransferDirection dir, enum AVPixelFormat **formats)
static int cuda_transfer_data_from (AVHWFramesContext *ctx, AVFrame *dst, const AVFrame *src)
static int cuda_transfer_data_to (AVHWFramesContext *ctx, AVFrame *dst, const AVFrame *src)
static void cuda_device_uninit (AVHWDeviceContext *ctx)
static int cuda_device_init (AVHWDeviceContext *ctx)
static int cuda_device_create (AVHWDeviceContext *ctx, const char *device, AVDictionary *opts, int flags)
Variables
static enum AVPixelFormat supported_formats []
const HWContextType ff_hwcontext_type_cuda
Macro Definition Documentation
CUDA_FRAME_ALIGNMENT
#define CUDA_FRAME_ALIGNMENT 256
Definition at line 28 of file hwcontext_cuda.c.
Referenced by cuda_frames_init(), and cuda_get_buffer().
Function Documentation
cuda_buffer_free()
static void cuda_buffer_free (void * opaque, uint8_t * data) static
Definition at line 42 of file hwcontext_cuda.c.
Referenced by cuda_pool_alloc().
cuda_pool_alloc()
static AVBufferRef* cuda_pool_alloc (void * opaque, int size) static
Definition at line 57 of file hwcontext_cuda.c.
Referenced by cuda_frames_init().
cuda_frames_init()
static int cuda_frames_init (AVHWFramesContext * ctx) static
Definition at line 89 of file hwcontext_cuda.c.
cuda_get_buffer()
static int cuda_get_buffer (AVHWFramesContext * ctx, AVFrame * frame) static
Definition at line 133 of file hwcontext_cuda.c.
cuda_transfer_get_formats()
static int cuda_transfer_get_formats (AVHWFramesContext * ctx, enum AVHWFrameTransferDirection dir, enum AVPixelFormat ** formats) static
Definition at line 185 of file hwcontext_cuda.c.
cuda_transfer_data_from()
static int cuda_transfer_data_from (AVHWFramesContext * ctx, AVFrame * dst, const AVFrame * src) static
Definition at line 203 of file hwcontext_cuda.c.
cuda_transfer_data_to()
static int cuda_transfer_data_to (AVHWFramesContext * ctx, AVFrame * dst, const AVFrame * src) static
Definition at line 242 of file hwcontext_cuda.c.
cuda_device_uninit()
static void cuda_device_uninit (AVHWDeviceContext * ctx) static
Definition at line 281 of file hwcontext_cuda.c.
Referenced by cuda_device_create(), and cuda_device_init().
cuda_device_init()
static int cuda_device_init (AVHWDeviceContext * ctx) static
Definition at line 296 of file hwcontext_cuda.c.
Referenced by cuda_device_create().
cuda_device_create()
static int cuda_device_create (AVHWDeviceContext * ctx, const char * device, AVDictionary * opts, int flags) static
Definition at line 322 of file hwcontext_cuda.c.
Variable Documentation
supported_formats
enum AVPixelFormat supported_formats[] static
Initial value:
= {
    AV_PIX_FMT_NV12,
    AV_PIX_FMT_YUV420P,
    AV_PIX_FMT_YUV444P,
    AV_PIX_FMT_P010,
    AV_PIX_FMT_P016,
}
Definition at line 34 of file hwcontext_cuda.c.
Referenced by cuda_frames_init().
ff_hwcontext_type_cuda
const HWContextType ff_hwcontext_type_cuda
Initial value:
= {
    .type                 = AV_HWDEVICE_TYPE_CUDA,
    .name                 = "CUDA",
    .device_hwctx_size    = sizeof(AVCUDADeviceContext),
    .frames_priv_size     = sizeof(CUDAFramesContext),
    .device_create        = cuda_device_create,
    .device_init          = cuda_device_init,
    .device_uninit        = cuda_device_uninit,
    .frames_init          = cuda_frames_init,
    .frames_get_buffer    = cuda_get_buffer,
    .transfer_get_formats = cuda_transfer_get_formats,
    .transfer_data_to     = cuda_transfer_data_to,
    .transfer_data_from   = cuda_transfer_data_from,
    .pix_fmts             = (const enum AVPixelFormat[]){ AV_PIX_FMT_CUDA, AV_PIX_FMT_NONE },
}
Definition at line 369 of file hwcontext_cuda.c.