FFmpeg: libavutil/hwcontext_vaapi.c File Reference
hwcontext_vaapi.c File Reference
#include "config.h"
#include <fcntl.h>
#include "avassert.h"
#include "buffer.h"
#include "common.h"
#include "hwcontext.h"
#include "hwcontext_internal.h"
#include "hwcontext_vaapi.h"
#include "mem.h"
#include "pixdesc.h"
#include "pixfmt.h"
Data Structures
struct VAAPIDevicePriv
struct VAAPISurfaceFormat
struct VAAPIDeviceContext
struct VAAPIFramesContext
struct VAAPISurfaceMap
Macros
#define MAP(va, rt, av)
Enumerations
enum { VAAPI_MAP_READ = 0x01, VAAPI_MAP_WRITE = 0x02, VAAPI_MAP_DIRECT = 0x04 }
Functions
static enum AVPixelFormat vaapi_pix_fmt_from_fourcc (unsigned int fourcc)
static int vaapi_get_image_format (AVHWDeviceContext *hwdev, enum AVPixelFormat pix_fmt, VAImageFormat **image_format)
static int vaapi_frames_get_constraints (AVHWDeviceContext *hwdev, const void *hwconfig, AVHWFramesConstraints *constraints)
static int vaapi_device_init (AVHWDeviceContext *hwdev)
static void vaapi_device_uninit (AVHWDeviceContext *hwdev)
static void vaapi_buffer_free (void *opaque, uint8_t *data)
static AVBufferRef * vaapi_pool_alloc (void *opaque, int size)
static int vaapi_frames_init (AVHWFramesContext *hwfc)
static void vaapi_frames_uninit (AVHWFramesContext *hwfc)
static int vaapi_get_buffer (AVHWFramesContext *hwfc, AVFrame *frame)
static int vaapi_transfer_get_formats (AVHWFramesContext *hwfc, enum AVHWFrameTransferDirection dir, enum AVPixelFormat **formats)
static void vaapi_unmap_frame (void *opaque, uint8_t *data)
static int vaapi_map_frame (AVHWFramesContext *hwfc, AVFrame *dst, const AVFrame *src, int flags)
static int vaapi_transfer_data_from (AVHWFramesContext *hwfc, AVFrame *dst, const AVFrame *src)
static int vaapi_transfer_data_to (AVHWFramesContext *hwfc, AVFrame *dst, const AVFrame *src)
static void vaapi_device_free (AVHWDeviceContext *ctx)
static int vaapi_device_create (AVHWDeviceContext *ctx, const char *device, AVDictionary *opts, int flags)
Variables
struct {
unsigned int fourcc
unsigned int rt_format
enum AVPixelFormat pix_fmt
} vaapi_format_map []
struct {
const char * friendly_name
const char * match_string
unsigned int quirks
} vaapi_driver_quirks_table []
const HWContextType ff_hwcontext_type_vaapi
Macro Definition Documentation
MAP
#define MAP (va, rt, av)
Value:
{ \
        VA_FOURCC_ ## va, \
        VA_RT_FORMAT_ ## rt, \
        AV_PIX_FMT_ ## av \
    }
Definition at line 88 of file hwcontext_vaapi.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
VAAPI_MAP_READ
VAAPI_MAP_WRITE
VAAPI_MAP_DIRECT
Definition at line 73 of file hwcontext_vaapi.c.
Function Documentation
vaapi_pix_fmt_from_fourcc()
static enum AVPixelFormat vaapi_pix_fmt_from_fourcc (unsigned int fourcc) static
Definition at line 127 of file hwcontext_vaapi.c.
Referenced by vaapi_device_init(), and vaapi_frames_get_constraints().
vaapi_get_image_format()
static int vaapi_get_image_format (AVHWDeviceContext * hwdev, enum AVPixelFormat pix_fmt, VAImageFormat ** image_format) static
Definition at line 136 of file hwcontext_vaapi.c.
Referenced by vaapi_frames_init(), and vaapi_map_frame().
vaapi_frames_get_constraints()
static int vaapi_frames_get_constraints (AVHWDeviceContext * hwdev, const void * hwconfig, AVHWFramesConstraints * constraints) static
Definition at line 152 of file hwcontext_vaapi.c.
vaapi_device_init()
static int vaapi_device_init (AVHWDeviceContext * hwdev) static
Definition at line 285 of file hwcontext_vaapi.c.
vaapi_device_uninit()
static void vaapi_device_uninit (AVHWDeviceContext * hwdev) static
Definition at line 367 of file hwcontext_vaapi.c.
vaapi_buffer_free()
static void vaapi_buffer_free (void * opaque, uint8_t * data) static
Definition at line 374 of file hwcontext_vaapi.c.
Referenced by vaapi_pool_alloc().
vaapi_pool_alloc()
static AVBufferRef* vaapi_pool_alloc (void * opaque, int size) static
Definition at line 390 of file hwcontext_vaapi.c.
Referenced by vaapi_frames_init().
vaapi_frames_init()
static int vaapi_frames_init (AVHWFramesContext * hwfc) static
Definition at line 430 of file hwcontext_vaapi.c.
vaapi_frames_uninit()
static void vaapi_frames_uninit (AVHWFramesContext * hwfc) static
Definition at line 583 of file hwcontext_vaapi.c.
vaapi_get_buffer()
static int vaapi_get_buffer (AVHWFramesContext * hwfc, AVFrame * frame) static
Definition at line 592 of file hwcontext_vaapi.c.
vaapi_transfer_get_formats()
static int vaapi_transfer_get_formats (AVHWFramesContext * hwfc, enum AVHWFrameTransferDirection dir, enum AVPixelFormat ** formats) static
Definition at line 606 of file hwcontext_vaapi.c.
vaapi_unmap_frame()
static void vaapi_unmap_frame (void * opaque, uint8_t * data) static
Definition at line 635 of file hwcontext_vaapi.c.
Referenced by vaapi_map_frame().
vaapi_map_frame()
static int vaapi_map_frame (AVHWFramesContext * hwfc, AVFrame * dst, const AVFrame * src, int flags) static
Definition at line 674 of file hwcontext_vaapi.c.
Referenced by vaapi_transfer_data_from(), and vaapi_transfer_data_to().
vaapi_transfer_data_from()
static int vaapi_transfer_data_from (AVHWFramesContext * hwfc, AVFrame * dst, const AVFrame * src) static
Definition at line 814 of file hwcontext_vaapi.c.
vaapi_transfer_data_to()
static int vaapi_transfer_data_to (AVHWFramesContext * hwfc, AVFrame * dst, const AVFrame * src) static
Definition at line 845 of file hwcontext_vaapi.c.
vaapi_device_free()
static void vaapi_device_free (AVHWDeviceContext * ctx) static
Definition at line 876 of file hwcontext_vaapi.c.
Referenced by vaapi_device_create().
vaapi_device_create()
static int vaapi_device_create (AVHWDeviceContext * ctx, const char * device, AVDictionary * opts, int flags) static
Definition at line 895 of file hwcontext_vaapi.c.
Variable Documentation
fourcc
unsigned int fourcc
Definition at line 96 of file hwcontext_vaapi.c.
Referenced by vaapi_device_init(), vaapi_frames_get_constraints(), and vaapi_frames_init().
rt_format
unsigned int rt_format
Definition at line 97 of file hwcontext_vaapi.c.
Referenced by vaapi_frames_init().
pix_fmt
enum AVPixelFormat pix_fmt
Definition at line 98 of file hwcontext_vaapi.c.
Referenced by vaapi_device_init(), vaapi_frames_get_constraints(), and vaapi_frames_init().
vaapi_format_map
struct { ... } vaapi_format_map[]
Initial value:
= {
    MAP(NV12, YUV420,  NV12),
    MAP(YV12, YUV420,  YUV420P),
    MAP(IYUV, YUV420,  YUV420P),
    MAP(422H, YUV422,  YUV422P),
    MAP(UYVY, YUV422,  UYVY422),
    MAP(YUY2, YUV422,  YUYV422),
    MAP(Y800, YUV400,  GRAY8),
    MAP(BGRA, RGB32,   BGRA),
    MAP(BGRX, RGB32,   BGR0),
    MAP(RGBA, RGB32,   RGBA),
    MAP(RGBX, RGB32,   RGB0),
    MAP(ARGB, RGB32,   ARGB),
    MAP(XRGB, RGB32,   0RGB),
}
Referenced by vaapi_frames_init(), and vaapi_pix_fmt_from_fourcc().
friendly_name
const char* friendly_name
Definition at line 269 of file hwcontext_vaapi.c.
Referenced by vaapi_device_init().
match_string
const char* match_string
Definition at line 270 of file hwcontext_vaapi.c.
Referenced by vaapi_device_init().
quirks
unsigned int quirks
Definition at line 271 of file hwcontext_vaapi.c.
vaapi_driver_quirks_table
const { ... } vaapi_driver_quirks_table[]
Initial value:
= {
    {
        "Intel i965 (Quick Sync)",
        "i965",
        AV_VAAPI_DRIVER_QUIRK_RENDER_PARAM_BUFFERS,
    },
    {
        "Intel iHD",
        "ubit",
        AV_VAAPI_DRIVER_QUIRK_ATTRIB_MEMTYPE,
    },
}
Referenced by vaapi_device_init().
ff_hwcontext_type_vaapi
const HWContextType ff_hwcontext_type_vaapi
Initial value:
= {
    .type                   = AV_HWDEVICE_TYPE_VAAPI,
    .name                   = "VAAPI",
    .device_hwctx_size      = sizeof(AVVAAPIDeviceContext),
    .device_priv_size       = sizeof(VAAPIDeviceContext),
    .device_hwconfig_size   = sizeof(AVVAAPIHWConfig),
    .frames_hwctx_size      = sizeof(AVVAAPIFramesContext),
    .frames_priv_size       = sizeof(VAAPIFramesContext),
    .device_create          = &vaapi_device_create,
    .device_init            = &vaapi_device_init,
    .device_uninit          = &vaapi_device_uninit,
    .frames_get_constraints = &vaapi_frames_get_constraints,
    .frames_init            = &vaapi_frames_init,
    .frames_uninit          = &vaapi_frames_uninit,
    .frames_get_buffer      = &vaapi_get_buffer,
    .transfer_get_formats   = &vaapi_transfer_get_formats,
    .transfer_data_to       = &vaapi_transfer_data_to,
    .transfer_data_from     = &vaapi_transfer_data_from,
    .pix_fmts = (const enum AVPixelFormat[]) {
        AV_PIX_FMT_VAAPI,
        AV_PIX_FMT_NONE
    },
}
Definition at line 978 of file hwcontext_vaapi.c.