FFmpeg: libavutil/hwcontext_qsv.c File Reference
hwcontext_qsv.c File Reference
#include <stdint.h>
#include <string.h>
#include <mfx/mfxvideo.h>
#include "config.h"
#include "buffer.h"
#include "common.h"
#include "hwcontext.h"
#include "hwcontext_internal.h"
#include "hwcontext_qsv.h"
#include "mem.h"
#include "pixfmt.h"
#include "pixdesc.h"
#include "time.h"
Data Structures
struct QSVDevicePriv
struct QSVDeviceContext
struct QSVFramesContext
Functions
static int qsv_device_init (AVHWDeviceContext *ctx)
static void qsv_frames_uninit (AVHWFramesContext *ctx)
static void qsv_pool_release_dummy (void *opaque, uint8_t *data)
static AVBufferRef * qsv_pool_alloc (void *opaque, int size)
static int qsv_init_child_ctx (AVHWFramesContext *ctx)
static int qsv_init_pool (AVHWFramesContext *ctx, uint32_t fourcc)
static mfxStatus frame_alloc (mfxHDL pthis, mfxFrameAllocRequest *req, mfxFrameAllocResponse *resp)
static mfxStatus frame_free (mfxHDL pthis, mfxFrameAllocResponse *resp)
static mfxStatus frame_lock (mfxHDL pthis, mfxMemId mid, mfxFrameData *ptr)
static mfxStatus frame_unlock (mfxHDL pthis, mfxMemId mid, mfxFrameData *ptr)
static mfxStatus frame_get_hdl (mfxHDL pthis, mfxMemId mid, mfxHDL *hdl)
static int qsv_init_internal_session (AVHWFramesContext *ctx, mfxSession *session, int upload)
static int qsv_frames_init (AVHWFramesContext *ctx)
static int qsv_get_buffer (AVHWFramesContext *ctx, AVFrame *frame)
static int qsv_transfer_get_formats (AVHWFramesContext *ctx, enum AVHWFrameTransferDirection dir, enum AVPixelFormat **formats)
static int qsv_transfer_data_from (AVHWFramesContext *ctx, AVFrame *dst, const AVFrame *src)
static int qsv_transfer_data_to (AVHWFramesContext *ctx, AVFrame *dst, const AVFrame *src)
static int qsv_frames_get_constraints (AVHWDeviceContext *ctx, const void *hwconfig, AVHWFramesConstraints *constraints)
static void qsv_device_free (AVHWDeviceContext *ctx)
static mfxIMPL choose_implementation (const char *device)
static int qsv_device_create (AVHWDeviceContext *ctx, const char *device, AVDictionary *opts, int flags)
Variables
struct {
mfxHandleType handle_type
enum AVHWDeviceType device_type
enum AVPixelFormat pix_fmt
} supported_handle_types []
struct {
enum AVPixelFormat pix_fmt
uint32_t fourcc
} supported_pixel_formats []
const HWContextType ff_hwcontext_type_qsv
Function Documentation
qsv_device_init()
static int qsv_device_init (AVHWDeviceContext * ctx) static
Definition at line 96 of file hwcontext_qsv.c.
qsv_frames_uninit()
static void qsv_frames_uninit (AVHWFramesContext * ctx) static
Definition at line 130 of file hwcontext_qsv.c.
qsv_pool_release_dummy()
static void qsv_pool_release_dummy (void * opaque, uint8_t * data) static
Definition at line 152 of file hwcontext_qsv.c.
Referenced by qsv_pool_alloc().
qsv_pool_alloc()
static AVBufferRef* qsv_pool_alloc (void * opaque, int size) static
Definition at line 156 of file hwcontext_qsv.c.
Referenced by qsv_init_pool().
qsv_init_child_ctx()
static int qsv_init_child_ctx (AVHWFramesContext * ctx) static
Definition at line 171 of file hwcontext_qsv.c.
Referenced by qsv_init_pool().
qsv_init_pool()
static int qsv_init_pool (AVHWFramesContext * ctx, uint32_t fourcc) static
Definition at line 274 of file hwcontext_qsv.c.
Referenced by qsv_frames_init().
frame_alloc()
static mfxStatus frame_alloc (mfxHDL pthis, mfxFrameAllocRequest * req, mfxFrameAllocResponse * resp) static
Definition at line 336 of file hwcontext_qsv.c.
Referenced by qsv_init_internal_session().
frame_free()
static mfxStatus frame_free (mfxHDL pthis, mfxFrameAllocResponse * resp) static
Definition at line 364 of file hwcontext_qsv.c.
Referenced by qsv_init_internal_session().
frame_lock()
static mfxStatus frame_lock (mfxHDL pthis, mfxMemId mid, mfxFrameData * ptr) static
Definition at line 369 of file hwcontext_qsv.c.
Referenced by qsv_init_internal_session().
frame_unlock()
static mfxStatus frame_unlock (mfxHDL pthis, mfxMemId mid, mfxFrameData * ptr) static
Definition at line 374 of file hwcontext_qsv.c.
Referenced by qsv_init_internal_session().
frame_get_hdl()
static mfxStatus frame_get_hdl (mfxHDL pthis, mfxMemId mid, mfxHDL * hdl) static
Definition at line 379 of file hwcontext_qsv.c.
Referenced by qsv_init_internal_session().
qsv_init_internal_session()
static int qsv_init_internal_session (AVHWFramesContext * ctx, mfxSession * session, int upload) static
Definition at line 385 of file hwcontext_qsv.c.
Referenced by qsv_frames_init().
qsv_frames_init()
static int qsv_frames_init (AVHWFramesContext * ctx) static
Definition at line 459 of file hwcontext_qsv.c.
qsv_get_buffer()
static int qsv_get_buffer (AVHWFramesContext * ctx, AVFrame * frame) static
Definition at line 527 of file hwcontext_qsv.c.
qsv_transfer_get_formats()
static int qsv_transfer_get_formats (AVHWFramesContext * ctx, enum AVHWFrameTransferDirection dir, enum AVPixelFormat ** formats) static
Definition at line 541 of file hwcontext_qsv.c.
qsv_transfer_data_from()
static int qsv_transfer_data_from (AVHWFramesContext * ctx, AVFrame * dst, const AVFrame * src) static
Definition at line 559 of file hwcontext_qsv.c.
qsv_transfer_data_to()
static int qsv_transfer_data_to (AVHWFramesContext * ctx, AVFrame * dst, const AVFrame * src) static
Definition at line 598 of file hwcontext_qsv.c.
qsv_frames_get_constraints()
static int qsv_frames_get_constraints (AVHWDeviceContext * ctx, const void * hwconfig, AVHWFramesConstraints * constraints) static
Definition at line 637 of file hwcontext_qsv.c.
qsv_device_free()
static void qsv_device_free (AVHWDeviceContext * ctx) static
Definition at line 662 of file hwcontext_qsv.c.
Referenced by qsv_device_create().
choose_implementation()
static mfxIMPL choose_implementation (const char * device) static
Definition at line 674 of file hwcontext_qsv.c.
Referenced by qsv_device_create().
qsv_device_create()
static int qsv_device_create (AVHWDeviceContext * ctx, const char * device, AVDictionary * opts, int flags) static
Definition at line 706 of file hwcontext_qsv.c.
Variable Documentation
handle_type
mfxHandleType handle_type
Definition at line 75 of file hwcontext_qsv.c.
Referenced by ff_qsv_init_session_hwcontext(), and qsv_device_create().
device_type
enum AVHWDeviceType device_type
Definition at line 76 of file hwcontext_qsv.c.
pix_fmt
enum AVPixelFormat pix_fmt
Definition at line 77 of file hwcontext_qsv.c.
Referenced by qsv_frames_init().
supported_handle_types
const { ... } supported_handle_types[]
Initial value:
= {
    { 0 },
}
Referenced by qsv_device_init().
fourcc
uint32_t fourcc
Definition at line 90 of file hwcontext_qsv.c.
Referenced by main(), matroska_parse_tracks(), msnwc_tcp_probe(), parse_pixel_format(), print_pix_fmt_fourccs(), qsv_frames_init(), and qsv_init_pool().
supported_pixel_formats
const { ... } supported_pixel_formats[]
Initial value:
= {
    { AV_PIX_FMT_NV12, MFX_FOURCC_NV12 },
    { AV_PIX_FMT_P010, MFX_FOURCC_P010 },
}
Referenced by qsv_frames_get_constraints(), and qsv_frames_init().
ff_hwcontext_type_qsv
const HWContextType ff_hwcontext_type_qsv
Initial value:
= {
    .type                   = AV_HWDEVICE_TYPE_QSV,
    .name                   = "QSV",
    .device_hwctx_size      = sizeof(AVQSVDeviceContext),
    .device_priv_size       = sizeof(QSVDeviceContext),
    .frames_hwctx_size      = sizeof(AVQSVFramesContext),
    .frames_priv_size       = sizeof(QSVFramesContext),
    .device_create          = qsv_device_create,
    .device_init            = qsv_device_init,
    .frames_get_constraints = qsv_frames_get_constraints,
    .frames_init            = qsv_frames_init,
    .frames_uninit          = qsv_frames_uninit,
    .frames_get_buffer      = qsv_get_buffer,
    .transfer_get_formats   = qsv_transfer_get_formats,
    .transfer_data_to       = qsv_transfer_data_to,
    .transfer_data_from     = qsv_transfer_data_from,
    .pix_fmts = (const enum AVPixelFormat[]){ AV_PIX_FMT_QSV, AV_PIX_FMT_NONE },
}
Definition at line 772 of file hwcontext_qsv.c.