FFmpeg: libavformat/id3v2.c File Reference
id3v2.c File Reference
ID3v2 header parser.
#include "config.h"
#include "libavutil/avstring.h"
#include "libavutil/dict.h"
#include "libavutil/intreadwrite.h"
#include "avio_internal.h"
#include "internal.h"
#include "id3v1.h"
#include "id3v2.h"
Data Structures
struct ID3v2EMFunc
Functions
int ff_id3v2_match (const uint8_t *buf, const char *magic)
Detect ID3v2 Header.
int ff_id3v2_tag_len (const uint8_t *buf)
Get the length of an ID3v2 tag.
static unsigned int get_size (AVIOContext *s, int len)
static unsigned int size_to_syncsafe (unsigned int size)
static int is_tag (const char *buf, unsigned int len)
static int check_tag (AVIOContext *s, int offset, unsigned int len)
Return 1 if the tag of length len at the given offset is valid, 0 if not, -1 on error.
static void free_geobtag (void *obj)
Free GEOB type extra metadata.
static int decode_str (AVFormatContext *s, AVIOContext *pb, int encoding, uint8_t **dst, int *maxread)
Decode characters to UTF-8 according to encoding type.
static void read_ttag (AVFormatContext *s, AVIOContext *pb, int taglen, AVDictionary **metadata, const char *key)
Parse a text tag.
static void read_uslt (AVFormatContext *s, AVIOContext *pb, int taglen, AVDictionary **metadata)
static void read_comment (AVFormatContext *s, AVIOContext *pb, int taglen, AVDictionary **metadata)
Parse a comment tag.
static void read_geobtag (AVFormatContext *s, AVIOContext *pb, int taglen, const char *tag, ID3v2ExtraMeta **extra_meta, int isv34)
Parse GEOB tag into a ID3v2ExtraMetaGEOB struct.
static int is_number (const char *str)
static AVDictionaryEntry * get_date_tag (AVDictionary *m, const char *tag)
static void merge_date (AVDictionary **m)
static void free_apic (void *obj)
static void rstrip_spaces (char *buf)
static void read_apic (AVFormatContext *s, AVIOContext *pb, int taglen, const char *tag, ID3v2ExtraMeta **extra_meta, int isv34)
static void read_chapter (AVFormatContext *s, AVIOContext *pb, int len, const char *ttag, ID3v2ExtraMeta **extra_meta, int isv34)
static void free_priv (void *obj)
static void read_priv (AVFormatContext *s, AVIOContext *pb, int taglen, const char *tag, ID3v2ExtraMeta **extra_meta, int isv34)
static const ID3v2EMFunc * get_extra_meta_func (const char *tag, int isv34)
Get the corresponding ID3v2EMFunc struct for a tag.
static void id3v2_parse (AVIOContext *pb, AVDictionary **metadata, AVFormatContext *s, int len, uint8_t version, uint8_t flags, ID3v2ExtraMeta **extra_meta)
static void id3v2_read_internal (AVIOContext *pb, AVDictionary **metadata, AVFormatContext *s, const char *magic, ID3v2ExtraMeta **extra_meta, int64_t max_search_size)
void ff_id3v2_read_dict (AVIOContext *pb, AVDictionary **metadata, const char *magic, ID3v2ExtraMeta **extra_meta)
Read an ID3v2 tag into specified dictionary and retrieve supported extra metadata.
void ff_id3v2_read (AVFormatContext *s, const char *magic, ID3v2ExtraMeta **extra_meta, unsigned int max_search_size)
Read an ID3v2 tag, including supported extra metadata and chapters.
void ff_id3v2_free_extra_meta (ID3v2ExtraMeta **extra_meta)
Free memory allocated parsing special (non-text) metadata.
int ff_id3v2_parse_apic (AVFormatContext *s, ID3v2ExtraMeta **extra_meta)
Create a stream for each APIC (attached picture) extracted from the ID3v2 header.
Variables
const AVMetadataConv ff_id3v2_34_metadata_conv []
const AVMetadataConv ff_id3v2_4_metadata_conv []
static const AVMetadataConv id3v2_2_metadata_conv []
const char ff_id3v2_tags [][4]
A list of text information frames allowed in both ID3 v2.3 and v2.4 http://www.id3.org/id3v2.4.0-frames http://www.id3.org/id3v2.4.0-changes.
const char ff_id3v2_4_tags [][4]
ID3v2.4-only text information frames.
const char ff_id3v2_3_tags [][4]
ID3v2.3-only text information frames.
const char * ff_id3v2_picture_types [21]
const CodecMime ff_id3v2_mime_tags []
static const ID3v2EMFunc id3v2_extra_meta_funcs []
Detailed Description
ID3v2 header parser.
Specifications available at: http://id3.org/Developer_Information
Definition in file id3v2.c.
Function Documentation
ff_id3v2_match()
int ff_id3v2_match (const uint8_t * buf, const char * magic)
Detect ID3v2 Header.
Parameters
buf must be ID3v2_HEADER_SIZE byte long
magic magic bytes to identify the header. If in doubt, use ID3v2_DEFAULT_MAGIC.
Definition at line 141 of file id3v2.c.
Referenced by av_probe_input_format3(), id3v2_read_internal(), intercept_id3(), mp3_read_probe(), and oma_read_probe().
ff_id3v2_tag_len()
int ff_id3v2_tag_len (const uint8_t * buf)
Get the length of an ID3v2 tag.
Parameters
buf must be ID3v2_HEADER_SIZE bytes long and point to the start of an already detected ID3v2 tag
Definition at line 154 of file id3v2.c.
Referenced by av_probe_input_format3(), intercept_id3(), mp3_read_probe(), and oma_read_probe().
get_size()
static unsigned int get_size (AVIOContext * s, int len) static
Definition at line 166 of file id3v2.c.
Referenced by id3v2_parse().
size_to_syncsafe()
static unsigned int size_to_syncsafe (unsigned int size) static
Definition at line 174 of file id3v2.c.
Referenced by id3v2_parse().
is_tag()
static int is_tag (const char * buf, unsigned int len) static
Definition at line 184 of file id3v2.c.
Referenced by check_tag().
check_tag()
static int check_tag (AVIOContext * s, int offset, unsigned int len) static
Return 1 if the tag of length len at the given offset is valid, 0 if not, -1 on error.
Definition at line 202 of file id3v2.c.
Referenced by id3v2_parse().
free_geobtag()
static void free_geobtag (void * obj) static
Free GEOB type extra metadata.
Definition at line 219 of file id3v2.c.
Referenced by read_geobtag().
decode_str()
static int decode_str (AVFormatContext * s, AVIOContext * pb, int encoding, uint8_t ** dst, int * maxread) static
Decode characters to UTF-8 according to encoding type.
The decoded buffer is always null terminated. Stop reading when either *maxread bytes are read from pb or U+0000 character is found.
Parameters
dst Pointer where the address of the buffer with the decoded bytes is stored. Buffer must be freed by caller.
maxread Pointer to maximum number of characters to read from the AVIOContext. After execution the value is decremented by the number of bytes actually read.
Returns
0 if no error occurred, dst is uninitialized on error
Definition at line 241 of file id3v2.c.
Referenced by read_apic(), read_chapter(), read_comment(), read_geobtag(), read_priv(), read_ttag(), and read_uslt().
read_ttag()
static void read_ttag (AVFormatContext * s, AVIOContext * pb, int taglen, AVDictionary ** metadata, const char * key) static
Parse a text tag.
Definition at line 318 of file id3v2.c.
Referenced by id3v2_parse(), and read_chapter().
read_uslt()
static void read_uslt (AVFormatContext * s, AVIOContext * pb, int taglen, AVDictionary ** metadata) static
Definition at line 357 of file id3v2.c.
Referenced by id3v2_parse().
read_comment()
static void read_comment (AVFormatContext * s, AVIOContext * pb, int taglen, AVDictionary ** metadata) static
Parse a comment tag.
Definition at line 405 of file id3v2.c.
Referenced by id3v2_parse().
read_geobtag()
static void read_geobtag (AVFormatContext * s, AVIOContext * pb, int taglen, const char * tag, ID3v2ExtraMeta ** extra_meta, int isv34) static
Parse GEOB tag into a ID3v2ExtraMetaGEOB struct.
Definition at line 447 of file id3v2.c.
is_number()
static int is_number (const char * str) static
Definition at line 524 of file id3v2.c.
Referenced by get_date_tag().
get_date_tag()
static AVDictionaryEntry* get_date_tag (AVDictionary * m, const char * tag) static
Definition at line 531 of file id3v2.c.
Referenced by merge_date().
merge_date()
static void merge_date (AVDictionary ** m) static
Definition at line 540 of file id3v2.c.
Referenced by id3v2_read_internal().
free_apic()
static void free_apic (void * obj) static
Definition at line 572 of file id3v2.c.
Referenced by read_apic().
rstrip_spaces()
static void rstrip_spaces (char * buf) static
Definition at line 580 of file id3v2.c.
Referenced by read_apic().
read_apic()
static void read_apic (AVFormatContext * s, AVIOContext * pb, int taglen, const char * tag, ID3v2ExtraMeta ** extra_meta, int isv34) static
Definition at line 587 of file id3v2.c.
read_chapter()
static void read_chapter (AVFormatContext * s, AVIOContext * pb, int len, const char * ttag, ID3v2ExtraMeta ** extra_meta, int isv34) static
Definition at line 673 of file id3v2.c.
free_priv()
static void free_priv (void * obj) static
Definition at line 728 of file id3v2.c.
Referenced by read_priv().
read_priv()
static void read_priv (AVFormatContext * s, AVIOContext * pb, int taglen, const char * tag, ID3v2ExtraMeta ** extra_meta, int isv34) static
Definition at line 736 of file id3v2.c.
get_extra_meta_func()
static const ID3v2EMFunc* get_extra_meta_func (const char * tag, int isv34) static
Get the corresponding ID3v2EMFunc struct for a tag.
Parameters
isv34 Determines if v2.2 or v2.3/4 strings are used
Returns
A pointer to the ID3v2EMFunc struct if found, NULL otherwise.
Definition at line 795 of file id3v2.c.
Referenced by ff_id3v2_free_extra_meta(), and id3v2_parse().
id3v2_parse()
static void id3v2_parse (AVIOContext * pb, AVDictionary ** metadata, AVFormatContext * s, int len, uint8_t version, uint8_t flags, ID3v2ExtraMeta ** extra_meta) static
Definition at line 809 of file id3v2.c.
Referenced by id3v2_read_internal().
id3v2_read_internal()
static void id3v2_read_internal (AVIOContext * pb, AVDictionary ** metadata, AVFormatContext * s, const char * magic, ID3v2ExtraMeta ** extra_meta, int64_t max_search_size) static
Definition at line 1051 of file id3v2.c.
Referenced by ff_id3v2_read(), and ff_id3v2_read_dict().
ff_id3v2_read_dict()
void ff_id3v2_read_dict (AVIOContext * pb, AVDictionary ** metadata, const char * magic, ID3v2ExtraMeta ** extra_meta)
Read an ID3v2 tag into specified dictionary and retrieve supported extra metadata.
Chapters are not currently read by this variant.
Parameters
metadata Parsed metadata is stored here
extra_meta If not NULL, extra metadata is parsed into a list of ID3v2ExtraMeta structs and *extra_meta points to the head of the list
Definition at line 1095 of file id3v2.c.
Referenced by parse_id3().
ff_id3v2_read()
void ff_id3v2_read (AVFormatContext * s, const char * magic, ID3v2ExtraMeta ** extra_meta, unsigned int max_search_size)
Read an ID3v2 tag, including supported extra metadata and chapters.
Data is read from and stored to AVFormatContext.
Parameters
extra_meta If not NULL, extra metadata is parsed into a list of ID3v2ExtraMeta structs and *extra_meta points to the head of the list
Definition at line 1101 of file id3v2.c.
Referenced by aiff_read_header(), avformat_open_input(), get_id3_tag(), oma_read_header(), parse_dsd_prop(), and read_id3().
ff_id3v2_free_extra_meta()
void ff_id3v2_free_extra_meta (ID3v2ExtraMeta ** extra_meta)
Free memory allocated parsing special (non-text) metadata.
Parameters
extra_meta Pointer to a pointer to the head of a ID3v2ExtraMeta list, *extra_meta is set to NULL.
Definition at line 1107 of file id3v2.c.
Referenced by aiff_read_header(), avformat_open_input(), free_playlist_list(), get_id3_tag(), handle_id3(), hls_read_header(), oma_read_header(), parse_dsd_prop(), and read_id3().
ff_id3v2_parse_apic()
int ff_id3v2_parse_apic (AVFormatContext * s, ID3v2ExtraMeta ** extra_meta)
Create a stream for each APIC (attached picture) extracted from the ID3v2 header.
Definition at line 1123 of file id3v2.c.
Referenced by aiff_read_header(), avformat_open_input(), get_id3_tag(), handle_id3(), hls_read_header(), parse_dsd_prop(), and read_id3().
Variable Documentation
ff_id3v2_34_metadata_conv
const AVMetadataConv ff_id3v2_34_metadata_conv[]
Initial value:
= {
    { "TALB", "album"        },
    { "TCOM", "composer"     },
    { "TCON", "genre"        },
    { "TCOP", "copyright"    },
    { "TENC", "encoded_by"   },
    { "TIT2", "title"        },
    { "TLAN", "language"     },
    { "TPE1", "artist"       },
    { "TPE2", "album_artist" },
    { "TPE3", "performer"    },
    { "TPOS", "disc"         },
    { "TPUB", "publisher"    },
    { "TRCK", "track"        },
    { "TSSE", "encoder"      },
    { "USLT", "lyrics"       },
    { 0 }
}
Definition at line 43 of file id3v2.c.
Referenced by write_metadata().
ff_id3v2_4_metadata_conv
const AVMetadataConv ff_id3v2_4_metadata_conv[]
Initial value:
= {
    { "TCMP", "compilation"   },
    { "TDRC", "date"          },
    { "TDRL", "date"          },
    { "TDEN", "creation_time" },
    { "TSOA", "album-sort"    },
    { "TSOP", "artist-sort"   },
    { "TSOT", "title-sort"    },
    { 0 }
}
Definition at line 62 of file id3v2.c.
Referenced by write_metadata().
id3v2_2_metadata_conv
const AVMetadataConv id3v2_2_metadata_conv[] static
Initial value:
= {
    { "TAL", "album"        },
    { "TCO", "genre"        },
    { "TCP", "compilation"  },
    { "TT2", "title"        },
    { "TEN", "encoded_by"   },
    { "TP1", "artist"       },
    { "TP2", "album_artist" },
    { "TP3", "performer"    },
    { "TRK", "track"        },
    { 0 }
}
Definition at line 73 of file id3v2.c.
ff_id3v2_tags
const char ff_id3v2_tags[][4]
Initial value:
= {
    "TALB", "TBPM", "TCOM", "TCON", "TCOP", "TDLY", "TENC", "TEXT",
    "TFLT", "TIT1", "TIT2", "TIT3", "TKEY", "TLAN", "TLEN", "TMED",
    "TOAL", "TOFN", "TOLY", "TOPE", "TOWN", "TPE1", "TPE2", "TPE3",
    "TPE4", "TPOS", "TPUB", "TRCK", "TRSN", "TRSO", "TSRC", "TSSE",
    { 0 },
}
A list of text information frames allowed in both ID3 v2.3 and v2.4 http://www.id3.org/id3v2.4.0-frames http://www.id3.org/id3v2.4.0-changes.
Definition at line 86 of file id3v2.c.
Referenced by write_metadata().
ff_id3v2_4_tags
const char ff_id3v2_4_tags[][4]
Initial value:
= {
    "TDEN", "TDOR", "TDRC", "TDRL", "TDTG", "TIPL", "TMCL", "TMOO",
    "TPRO", "TSOA", "TSOP", "TSOT", "TSST",
    { 0 },
}
ID3v2.4-only text information frames.
Definition at line 94 of file id3v2.c.
Referenced by write_metadata().
ff_id3v2_3_tags
const char ff_id3v2_3_tags[][4]
Initial value:
= {
    "TDAT", "TIME", "TORY", "TRDA", "TSIZ", "TYER",
    { 0 },
}
ID3v2.3-only text information frames.
Definition at line 100 of file id3v2.c.
Referenced by write_metadata().
ff_id3v2_picture_types
const char* ff_id3v2_picture_types[21]
Initial value:
= {
    "Other",
    "32x32 pixels 'file icon'",
    "Other file icon",
    "Cover (front)",
    "Cover (back)",
    "Leaflet page",
    "Media (e.g. label side of CD)",
    "Lead artist/lead performer/soloist",
    "Artist/performer",
    "Conductor",
    "Band/Orchestra",
    "Composer",
    "Lyricist/text writer",
    "Recording Location",
    "During recording",
    "During performance",
    "Movie/video screen capture",
    "A bright coloured fish",
    "Illustration",
    "Band/artist logotype",
    "Publisher/Studio logotype",
}
Definition at line 105 of file id3v2.c.
Referenced by asf_read_picture(), ff_flac_parse_picture(), ff_id3v2_write_apic(), and read_apic().
ff_id3v2_mime_tags
const CodecMime ff_id3v2_mime_tags[]
Initial value:
= {
    { "image/gif",  AV_CODEC_ID_GIF   },
    { "image/jpeg", AV_CODEC_ID_MJPEG },
    { "image/jpg",  AV_CODEC_ID_MJPEG },
    { "image/png",  AV_CODEC_ID_PNG   },
    { "image/tiff", AV_CODEC_ID_TIFF  },
    { "image/bmp",  AV_CODEC_ID_BMP   },
    { "JPG",        AV_CODEC_ID_MJPEG },
    { "PNG",        AV_CODEC_ID_PNG   },
    { "",           AV_CODEC_ID_NONE  },
}
Definition at line 129 of file id3v2.c.
Referenced by asf_read_picture(), ff_flac_parse_picture(), ff_id3v2_write_apic(), query_codec(), and read_apic().
id3v2_extra_meta_funcs
const ID3v2EMFunc id3v2_extra_meta_funcs[] static
Initial value:
= {
    { "GEO", "GEOB", read_geobtag, free_geobtag },
    { "PIC", "APIC", read_apic,    free_apic    },
    { "CHAP","CHAP", read_chapter, NULL         },
    { "PRIV","PRIV", read_priv,    free_priv    },
    { NULL }
}
Definition at line 782 of file id3v2.c.