FFmpeg: libavformat/id3v1.c File Reference
id3v1.c File Reference
#include "id3v1.h"
#include "libavcodec/avcodec.h"
#include "libavutil/dict.h"
Functions
static void get_string (AVFormatContext *s, const char *key, const uint8_t *buf, int buf_size)
static int parse_tag (AVFormatContext *s, const uint8_t *buf)
Parse an ID3v1 tag.
void ff_id3v1_read (AVFormatContext *s)
Read an ID3v1 tag.
Variables
const char *const ff_id3v1_genre_str [ID3v1_GENRE_MAX+1]
ID3v1 genres.
Function Documentation
get_string()
static void get_string (AVFormatContext * s, const char * key, const uint8_t * buf, int buf_size) static
Definition at line 178 of file id3v1.c.
Referenced by parse_tag().
parse_tag()
static int parse_tag (AVFormatContext * s, const uint8_t * buf) static
Parse an ID3v1 tag.
Parameters
buf ID3v1_TAG_SIZE long buffer containing the tag
Definition at line 213 of file id3v1.c.
Referenced by ff_id3v1_read().
ff_id3v1_read()
void ff_id3v1_read (AVFormatContext * s)
Read an ID3v1 tag.
Definition at line 235 of file id3v1.c.
Referenced by adts_aac_read_header(), mp3_read_header(), mpc_read_header(), tta_read_header(), and wv_read_header().
Variable Documentation
ff_id3v1_genre_str
const char* const ff_id3v1_genre_str[ID3v1_GENRE_MAX+1]
ID3v1 genres.
Definition at line 27 of file id3v1.c.
Referenced by id3v1_create_tag(), mov_metadata_gnre(), parse_tag(), and read_ttag().