FFmpeg: libavcodec/arm/idct.h File Reference
idct.h File Reference
#include <stdint.h>
Functions
void ff_j_rev_dct_arm (int16_t *data)
void ff_simple_idct_arm (int16_t *data)
void ff_simple_idct_armv5te (int16_t *data)
void ff_simple_idct_put_armv5te (uint8_t *dest, int line_size, int16_t *data)
void ff_simple_idct_add_armv5te (uint8_t *dest, int line_size, int16_t *data)
void ff_simple_idct_armv6 (int16_t *data)
void ff_simple_idct_put_armv6 (uint8_t *dest, int line_size, int16_t *data)
void ff_simple_idct_add_armv6 (uint8_t *dest, int line_size, int16_t *data)
void ff_simple_idct_neon (int16_t *data)
void ff_simple_idct_put_neon (uint8_t *dest, int line_size, int16_t *data)
void ff_simple_idct_add_neon (uint8_t *dest, int line_size, int16_t *data)
Function Documentation
ff_j_rev_dct_arm()
void ff_j_rev_dct_arm (int16_t * data)
Referenced by ff_idctdsp_init_arm(), j_rev_dct_arm_add(), and j_rev_dct_arm_put().
ff_simple_idct_arm()
void ff_simple_idct_arm (int16_t * data)
Referenced by ff_idctdsp_init_arm(), simple_idct_arm_add(), and simple_idct_arm_put().
ff_simple_idct_armv5te()
void ff_simple_idct_armv5te (int16_t * data)
Referenced by ff_idctdsp_init_armv5te().
ff_simple_idct_put_armv5te()
void ff_simple_idct_put_armv5te (uint8_t * dest, int line_size, int16_t * data)
Referenced by ff_idctdsp_init_armv5te().
ff_simple_idct_add_armv5te()
void ff_simple_idct_add_armv5te (uint8_t * dest, int line_size, int16_t * data)
Referenced by ff_idctdsp_init_armv5te().
ff_simple_idct_armv6()
void ff_simple_idct_armv6 (int16_t * data)
Referenced by ff_idctdsp_init_armv6().
ff_simple_idct_put_armv6()
void ff_simple_idct_put_armv6 (uint8_t * dest, int line_size, int16_t * data)
Referenced by ff_idctdsp_init_armv6().
ff_simple_idct_add_armv6()
void ff_simple_idct_add_armv6 (uint8_t * dest, int line_size, int16_t * data)
Referenced by ff_idctdsp_init_armv6().
ff_simple_idct_neon()
void ff_simple_idct_neon (int16_t * data)
Referenced by ff_idctdsp_init_neon().
ff_simple_idct_put_neon()
void ff_simple_idct_put_neon (uint8_t * dest, int line_size, int16_t * data)
Referenced by ff_idctdsp_init_neon().
ff_simple_idct_add_neon()
void ff_simple_idct_add_neon (uint8_t * dest, int line_size, int16_t * data)
Referenced by ff_idctdsp_init_neon().