FFmpeg: libavcodec/mips/idctdsp_msa.c File Reference
idctdsp_msa.c File Reference
#include "libavutil/mips/generic_macros_msa.h"
#include "idctdsp_mips.h"
Functions
static void put_pixels_clamped_msa (const int16_t *block, uint8_t *pixels, int32_t stride)
static void put_signed_pixels_clamped_msa (const int16_t *block, uint8_t *pixels, int32_t stride)
static void add_pixels_clamped_msa (const int16_t *block, uint8_t *pixels, int32_t stride)
void ff_put_pixels_clamped_msa (const int16_t *block, uint8_t *av_restrict pixels, ptrdiff_t line_size)
void ff_put_signed_pixels_clamped_msa (const int16_t *block, uint8_t *av_restrict pixels, ptrdiff_t line_size)
void ff_add_pixels_clamped_msa (const int16_t *block, uint8_t *av_restrict pixels, ptrdiff_t line_size)
Function Documentation
put_pixels_clamped_msa()
static void put_pixels_clamped_msa (const int16_t * block, uint8_t * pixels, int32_t stride) static
Definition at line 24 of file idctdsp_msa.c.
Referenced by ff_put_pixels_clamped_msa().
put_signed_pixels_clamped_msa()
static void put_signed_pixels_clamped_msa (const int16_t * block, uint8_t * pixels, int32_t stride) static
Definition at line 49 of file idctdsp_msa.c.
Referenced by ff_put_signed_pixels_clamped_msa().
add_pixels_clamped_msa()
static void add_pixels_clamped_msa (const int16_t * block, uint8_t * pixels, int32_t stride) static
Definition at line 84 of file idctdsp_msa.c.
Referenced by ff_add_pixels_clamped_msa().
ff_put_pixels_clamped_msa()
void ff_put_pixels_clamped_msa (const int16_t * block, uint8_t *av_restrict pixels, ptrdiff_t line_size)
Definition at line 130 of file idctdsp_msa.c.
ff_put_signed_pixels_clamped_msa()
void ff_put_signed_pixels_clamped_msa (const int16_t * block, uint8_t *av_restrict pixels, ptrdiff_t line_size)
Definition at line 137 of file idctdsp_msa.c.
ff_add_pixels_clamped_msa()
void ff_add_pixels_clamped_msa (const int16_t * block, uint8_t *av_restrict pixels, ptrdiff_t line_size)
Definition at line 144 of file idctdsp_msa.c.