FFmpeg: libavcodec/idctdsp.h File Reference
idctdsp.h File Reference
#include <stdint.h>
#include "avcodec.h"
Data Structures
struct ScanTable
Scantable.
struct IDCTDSPContext
Enumerations
enum idct_permutation_type {
FF_IDCT_PERM_NONE, FF_IDCT_PERM_LIBMPEG2, FF_IDCT_PERM_SIMPLE, FF_IDCT_PERM_TRANSPOSE,
FF_IDCT_PERM_PARTTRANS, FF_IDCT_PERM_SSE2
}
Functions
void ff_init_scantable (uint8_t *permutation, ScanTable *st, const uint8_t *src_scantable)
void ff_init_scantable_permutation (uint8_t *idct_permutation, enum idct_permutation_type perm_type)
int ff_init_scantable_permutation_x86 (uint8_t *idct_permutation, enum idct_permutation_type perm_type)
void ff_idctdsp_init (IDCTDSPContext *c, AVCodecContext *avctx)
void ff_idctdsp_init_alpha (IDCTDSPContext *c, AVCodecContext *avctx, unsigned high_bit_depth)
void ff_idctdsp_init_arm (IDCTDSPContext *c, AVCodecContext *avctx, unsigned high_bit_depth)
void ff_idctdsp_init_ppc (IDCTDSPContext *c, AVCodecContext *avctx, unsigned high_bit_depth)
void ff_idctdsp_init_x86 (IDCTDSPContext *c, AVCodecContext *avctx, unsigned high_bit_depth)
void ff_idctdsp_init_mips (IDCTDSPContext *c, AVCodecContext *avctx, unsigned high_bit_depth)
Variables
void(* ff_put_pixels_clamped)(const int16_t *block, uint8_t *pixels, ptrdiff_t line_size)
void(* ff_add_pixels_clamped)(const int16_t *block, uint8_t *pixels, ptrdiff_t line_size)
Enumeration Type Documentation
idct_permutation_type
enum idct_permutation_type
Enumerator
FF_IDCT_PERM_NONE
FF_IDCT_PERM_LIBMPEG2
FF_IDCT_PERM_SIMPLE
FF_IDCT_PERM_TRANSPOSE
FF_IDCT_PERM_PARTTRANS
FF_IDCT_PERM_SSE2
Definition at line 35 of file idctdsp.h.
Function Documentation
ff_init_scantable()
void ff_init_scantable (uint8_t * permutation, ScanTable * st, const uint8_t * src_scantable)
Definition at line 29 of file idctdsp.c.
Referenced by aic_decode_init(), decode_frame_header(), decode_init(), decode_vop_header(), dnxhd_decode_header(), ff_cavs_init(), ff_intrax8_common_init(), ff_mpv_idct_init(), ff_msmpeg4_common_init(), ff_wmv2_common_init(), init_idct(), jpg_init(), ljpeg_encode_init(), mimic_decode_init(), mpeg_decode_picture_coding_extension(), tgq_decode_init(), and tqi_decode_init().
ff_init_scantable_permutation()
void ff_init_scantable_permutation (uint8_t * idct_permutation, enum idct_permutation_type perm_type)
Definition at line 50 of file idctdsp.c.
Referenced by decode_init(), ff_cavs_init(), ff_idctdsp_init(), ff_intrax8_common_init(), ff_proresdsp_init(), ff_wmv2_common_init(), ff_xvid_idct_init(), tgq_decode_init(), and tqi_decode_init().
ff_init_scantable_permutation_x86()
int ff_init_scantable_permutation_x86 (uint8_t * idct_permutation, enum idct_permutation_type perm_type)
Definition at line 42 of file idctdsp_init.c.
Referenced by ff_init_scantable_permutation().
ff_idctdsp_init()
void ff_idctdsp_init (IDCTDSPContext * c, AVCodecContext * avctx)
Definition at line 241 of file idctdsp.c.
Referenced by aic_decode_init(), avcodec_dct_init(), decode_init(), dnxhd_decode_header(), dvvideo_decode_init(), ff_cavs_init(), ff_mpv_idct_init(), ff_rtjpeg_init(), init_idct(), jpg_init(), ljpeg_encode_init(), mimic_decode_init(), and tqi_decode_init().
ff_idctdsp_init_alpha()
void ff_idctdsp_init_alpha (IDCTDSPContext * c, AVCodecContext * avctx, unsigned high_bit_depth)
Definition at line 108 of file idctdsp_alpha.c.
Referenced by ff_idctdsp_init().
ff_idctdsp_init_arm()
void ff_idctdsp_init_arm (IDCTDSPContext * c, AVCodecContext * avctx, unsigned high_bit_depth)
Definition at line 61 of file idctdsp_init_arm.c.
Referenced by ff_idctdsp_init().
ff_idctdsp_init_ppc()
void ff_idctdsp_init_ppc (IDCTDSPContext * c, AVCodecContext * avctx, unsigned high_bit_depth)
Definition at line 256 of file idctdsp.c.
Referenced by ff_idctdsp_init().
ff_idctdsp_init_x86()
void ff_idctdsp_init_x86 (IDCTDSPContext * c, AVCodecContext * avctx, unsigned high_bit_depth)
Definition at line 61 of file idctdsp_init.c.
Referenced by ff_idctdsp_init().
ff_idctdsp_init_mips()
void ff_idctdsp_init_mips (IDCTDSPContext * c, AVCodecContext * avctx, unsigned high_bit_depth)
Definition at line 62 of file idctdsp_init_mips.c.
Referenced by ff_idctdsp_init().
Variable Documentation
ff_put_pixels_clamped
void(* ff_put_pixels_clamped) (const int16_t *block, uint8_t *pixels, ptrdiff_t line_size)
Definition at line 83 of file idctdsp.c.
Referenced by ff_idctdsp_init(), ff_jref_idct_put(), j_rev_dct_arm_put(), simple_idct_arm_put(), and xvid_idct_put().
ff_add_pixels_clamped
void(* ff_add_pixels_clamped) (const int16_t *block, uint8_t *pixels, ptrdiff_t line_size)
Definition at line 84 of file idctdsp.c.
Referenced by ff_idctdsp_init(), ff_jref_idct_add(), j_rev_dct_arm_add(), simple_idct_arm_add(), and xvid_idct_add().