FFmpeg: libavcodec/arm/idctdsp_init_arm.c File Reference
idctdsp_init_arm.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/arm/cpu.h"
#include "libavcodec/avcodec.h"
#include "libavcodec/idctdsp.h"
#include "idct.h"
#include "idctdsp_arm.h"
Functions
void ff_add_pixels_clamped_arm (const int16_t *block, uint8_t *dest, ptrdiff_t line_size)
static void j_rev_dct_arm_put (uint8_t *dest, int line_size, int16_t *block)
static void j_rev_dct_arm_add (uint8_t *dest, int line_size, int16_t *block)
static void simple_idct_arm_put (uint8_t *dest, int line_size, int16_t *block)
static void simple_idct_arm_add (uint8_t *dest, int line_size, int16_t *block)
av_cold void ff_idctdsp_init_arm (IDCTDSPContext *c, AVCodecContext *avctx, unsigned high_bit_depth)
Function Documentation
ff_add_pixels_clamped_arm()
void ff_add_pixels_clamped_arm (const int16_t * block, uint8_t * dest, ptrdiff_t line_size)
Referenced by ff_idctdsp_init_arm().
j_rev_dct_arm_put()
static void j_rev_dct_arm_put (uint8_t * dest, int line_size, int16_t * block) static
Definition at line 37 of file idctdsp_init_arm.c.
Referenced by ff_idctdsp_init_arm().
j_rev_dct_arm_add()
static void j_rev_dct_arm_add (uint8_t * dest, int line_size, int16_t * block) static
Definition at line 43 of file idctdsp_init_arm.c.
Referenced by ff_idctdsp_init_arm().
simple_idct_arm_put()
static void simple_idct_arm_put (uint8_t * dest, int line_size, int16_t * block) static
Definition at line 49 of file idctdsp_init_arm.c.
Referenced by ff_idctdsp_init_arm().
simple_idct_arm_add()
static void simple_idct_arm_add (uint8_t * dest, int line_size, int16_t * block) static
Definition at line 55 of file idctdsp_init_arm.c.
Referenced by ff_idctdsp_init_arm().
ff_idctdsp_init_arm()
av_cold void ff_idctdsp_init_arm (IDCTDSPContext * c, AVCodecContext * avctx, unsigned high_bit_depth)
Definition at line 61 of file idctdsp_init_arm.c.
Referenced by ff_idctdsp_init().