FFmpeg: libavcodec/idctdsp.c File Reference
idctdsp.c File Reference
#include "config.h"
#include "libavutil/attributes.h"
#include "libavutil/common.h"
#include "avcodec.h"
#include "dct.h"
#include "faanidct.h"
#include "idctdsp.h"
#include "simple_idct.h"
#include "xvididct.h"
Functions
av_cold void ff_init_scantable (uint8_t *permutation, ScanTable *st, const uint8_t *src_scantable)
av_cold void ff_init_scantable_permutation (uint8_t *idct_permutation, enum idct_permutation_type perm_type)
static void put_pixels_clamped_c (const int16_t *block, uint8_t *av_restrict pixels, ptrdiff_t line_size)
static void put_pixels_clamped4_c (const int16_t *block, uint8_t *av_restrict pixels, int line_size)
static void put_pixels_clamped2_c (const int16_t *block, uint8_t *av_restrict pixels, int line_size)
static void put_signed_pixels_clamped_c (const int16_t *block, uint8_t *av_restrict pixels, ptrdiff_t line_size)
static void add_pixels_clamped_c (const int16_t *block, uint8_t *av_restrict pixels, ptrdiff_t line_size)
static void add_pixels_clamped4_c (const int16_t *block, uint8_t *av_restrict pixels, int line_size)
static void add_pixels_clamped2_c (const int16_t *block, uint8_t *av_restrict pixels, int line_size)
static void ff_jref_idct4_put (uint8_t *dest, int line_size, int16_t *block)
static void ff_jref_idct4_add (uint8_t *dest, int line_size, int16_t *block)
static void ff_jref_idct2_put (uint8_t *dest, int line_size, int16_t *block)
static void ff_jref_idct2_add (uint8_t *dest, int line_size, int16_t *block)
static void ff_jref_idct1_put (uint8_t *dest, int line_size, int16_t *block)
static void ff_jref_idct1_add (uint8_t *dest, int line_size, int16_t *block)
av_cold void ff_idctdsp_init (IDCTDSPContext *c, AVCodecContext *avctx)
Variables
void(* ff_put_pixels_clamped)(const int16_t *block, uint8_t *pixels, ptrdiff_t line_size)
void(* ff_add_pixels_clamped)(const int16_t *block, uint8_t *pixels, ptrdiff_t line_size)
Function Documentation
ff_init_scantable()
av_cold void ff_init_scantable (uint8_t * permutation, ScanTable * st, const uint8_t * src_scantable)
Definition at line 29 of file idctdsp.c.
Referenced by aic_decode_init(), decode_frame_header(), decode_init(), decode_vop_header(), dnxhd_decode_header(), ff_cavs_init(), ff_intrax8_common_init(), ff_mpv_idct_init(), ff_msmpeg4_common_init(), ff_wmv2_common_init(), init_idct(), jpg_init(), ljpeg_encode_init(), mimic_decode_init(), mpeg_decode_picture_coding_extension(), tgq_decode_init(), and tqi_decode_init().
ff_init_scantable_permutation()
av_cold void ff_init_scantable_permutation (uint8_t * idct_permutation, enum idct_permutation_type perm_type)
Definition at line 50 of file idctdsp.c.
Referenced by decode_init(), ff_cavs_init(), ff_idctdsp_init(), ff_intrax8_common_init(), ff_proresdsp_init(), ff_wmv2_common_init(), ff_xvid_idct_init(), tgq_decode_init(), and tqi_decode_init().
put_pixels_clamped_c()
static void put_pixels_clamped_c (const int16_t * block, uint8_t *av_restrict pixels, ptrdiff_t line_size) static
Definition at line 86 of file idctdsp.c.
Referenced by ff_idctdsp_init().
put_pixels_clamped4_c()
static void put_pixels_clamped4_c (const int16_t * block, uint8_t *av_restrict pixels, int line_size) static
Definition at line 107 of file idctdsp.c.
Referenced by ff_jref_idct4_put().
put_pixels_clamped2_c()
static void put_pixels_clamped2_c (const int16_t * block, uint8_t *av_restrict pixels, int line_size) static
Definition at line 124 of file idctdsp.c.
Referenced by ff_jref_idct2_put().
put_signed_pixels_clamped_c()
static void put_signed_pixels_clamped_c (const int16_t * block, uint8_t *av_restrict pixels, ptrdiff_t line_size) static
Definition at line 139 of file idctdsp.c.
Referenced by ff_idctdsp_init().
add_pixels_clamped_c()
static void add_pixels_clamped_c (const int16_t * block, uint8_t *av_restrict pixels, ptrdiff_t line_size) static
Definition at line 160 of file idctdsp.c.
Referenced by ff_idctdsp_init().
add_pixels_clamped4_c()
static void add_pixels_clamped4_c (const int16_t * block, uint8_t *av_restrict pixels, int line_size) static
Definition at line 180 of file idctdsp.c.
Referenced by ff_jref_idct4_add().
add_pixels_clamped2_c()
static void add_pixels_clamped2_c (const int16_t * block, uint8_t *av_restrict pixels, int line_size) static
Definition at line 196 of file idctdsp.c.
Referenced by ff_jref_idct2_add().
ff_jref_idct4_put()
static void ff_jref_idct4_put (uint8_t * dest, int line_size, int16_t * block) static
Definition at line 210 of file idctdsp.c.
Referenced by ff_idctdsp_init().
ff_jref_idct4_add()
static void ff_jref_idct4_add (uint8_t * dest, int line_size, int16_t * block) static
Definition at line 215 of file idctdsp.c.
Referenced by ff_idctdsp_init().
ff_jref_idct2_put()
static void ff_jref_idct2_put (uint8_t * dest, int line_size, int16_t * block) static
Definition at line 221 of file idctdsp.c.
Referenced by ff_idctdsp_init().
ff_jref_idct2_add()
static void ff_jref_idct2_add (uint8_t * dest, int line_size, int16_t * block) static
Definition at line 226 of file idctdsp.c.
Referenced by ff_idctdsp_init().
ff_jref_idct1_put()
static void ff_jref_idct1_put (uint8_t * dest, int line_size, int16_t * block) static
Definition at line 232 of file idctdsp.c.
Referenced by ff_idctdsp_init().
ff_jref_idct1_add()
static void ff_jref_idct1_add (uint8_t * dest, int line_size, int16_t * block) static
Definition at line 236 of file idctdsp.c.
Referenced by ff_idctdsp_init().
ff_idctdsp_init()
av_cold void ff_idctdsp_init (IDCTDSPContext * c, AVCodecContext * avctx)
Definition at line 241 of file idctdsp.c.
Referenced by aic_decode_init(), avcodec_dct_init(), decode_init(), dnxhd_decode_header(), dvvideo_decode_init(), ff_cavs_init(), ff_mpv_idct_init(), ff_rtjpeg_init(), init_idct(), jpg_init(), ljpeg_encode_init(), mimic_decode_init(), and tqi_decode_init().
Variable Documentation
ff_put_pixels_clamped
void(* ff_put_pixels_clamped) (const int16_t *block, uint8_t *pixels, ptrdiff_t line_size)
Definition at line 83 of file idctdsp.c.
Referenced by ff_idctdsp_init(), ff_jref_idct_put(), j_rev_dct_arm_put(), simple_idct_arm_put(), and xvid_idct_put().
ff_add_pixels_clamped
void(* ff_add_pixels_clamped) (const int16_t *block, uint8_t *pixels, ptrdiff_t line_size)
Definition at line 84 of file idctdsp.c.
Referenced by ff_idctdsp_init(), ff_jref_idct_add(), j_rev_dct_arm_add(), simple_idct_arm_add(), and xvid_idct_add().