FFmpeg: libavcodec/alpha/idctdsp_alpha.h File Reference
idctdsp_alpha.h File Reference
#include <stddef.h>
#include <stdint.h>
Functions
void ff_simple_idct_axp (int16_t *block)
void ff_simple_idct_put_axp (uint8_t *dest, int line_size, int16_t *block)
void ff_simple_idct_add_axp (uint8_t *dest, int line_size, int16_t *block)
Variables
void(* put_pixels_clamped_axp_p)(const int16_t *block, uint8_t *pixels, ptrdiff_t line_size)
void(* add_pixels_clamped_axp_p)(const int16_t *block, uint8_t *pixels, ptrdiff_t line_size)
Function Documentation
ff_simple_idct_axp()
void ff_simple_idct_axp (int16_t * block)
Definition at line 253 of file simple_idct_alpha.c.
Referenced by ff_idctdsp_init_alpha(), ff_simple_idct_add_axp(), and ff_simple_idct_put_axp().
ff_simple_idct_put_axp()
void ff_simple_idct_put_axp (uint8_t * dest, int line_size, int16_t * block)
Definition at line 293 of file simple_idct_alpha.c.
Referenced by ff_idctdsp_init_alpha().
ff_simple_idct_add_axp()
void ff_simple_idct_add_axp (uint8_t * dest, int line_size, int16_t * block)
Definition at line 299 of file simple_idct_alpha.c.
Referenced by ff_idctdsp_init_alpha().
Variable Documentation
put_pixels_clamped_axp_p
void(* put_pixels_clamped_axp_p) (const int16_t *block, uint8_t *pixels, ptrdiff_t line_size)
Definition at line 31 of file idctdsp_alpha.c.
Referenced by ff_idctdsp_init_alpha(), and ff_simple_idct_put_axp().
add_pixels_clamped_axp_p
void(* add_pixels_clamped_axp_p) (const int16_t *block, uint8_t *pixels, ptrdiff_t line_size)
Definition at line 33 of file idctdsp_alpha.c.
Referenced by ff_idctdsp_init_alpha(), and ff_simple_idct_add_axp().