FFmpeg: libavcodec/iirfilter.h File Reference
iirfilter.h File Reference
IIR filter interface.
#include "avcodec.h"
Data Structures
struct FFIIRFilterContext
Enumerations
enum IIRFilterType {
FF_FILTER_TYPE_BESSEL, FF_FILTER_TYPE_BIQUAD, FF_FILTER_TYPE_BUTTERWORTH, FF_FILTER_TYPE_CHEBYSHEV,
FF_FILTER_TYPE_ELLIPTIC
}
enum IIRFilterMode { FF_FILTER_MODE_LOWPASS, FF_FILTER_MODE_HIGHPASS, FF_FILTER_MODE_BANDPASS, FF_FILTER_MODE_BANDSTOP }
Functions
void ff_iir_filter_init (FFIIRFilterContext *f)
Initialize FFIIRFilterContext.
void ff_iir_filter_init_mips (FFIIRFilterContext *f)
struct FFIIRFilterCoeffs * ff_iir_filter_init_coeffs (void *avc, enum IIRFilterType filt_type, enum IIRFilterMode filt_mode, int order, float cutoff_ratio, float stopband, float ripple)
Initialize filter coefficients.
struct FFIIRFilterState * ff_iir_filter_init_state (int order)
Create new filter state.
void ff_iir_filter_free_coeffsp (struct FFIIRFilterCoeffs **coeffs)
Free filter coefficients.
void ff_iir_filter_free_statep (struct FFIIRFilterState **state)
Free and zero filter state.
void ff_iir_filter (const struct FFIIRFilterCoeffs *coeffs, struct FFIIRFilterState *state, int size, const int16_t *src, int sstep, int16_t *dst, int dstep)
Perform IIR filtering on signed 16-bit input samples.
void ff_iir_filter_flt (const struct FFIIRFilterCoeffs *coeffs, struct FFIIRFilterState *state, int size, const float *src, int sstep, float *dst, int dstep)
Perform IIR filtering on floating-point input samples.
Detailed Description
IIR filter interface.
Definition in file iirfilter.h.
Enumeration Type Documentation
IIRFilterType
enum IIRFilterType
Enumerator
FF_FILTER_TYPE_BESSEL
FF_FILTER_TYPE_BIQUAD
FF_FILTER_TYPE_BUTTERWORTH
FF_FILTER_TYPE_CHEBYSHEV
FF_FILTER_TYPE_ELLIPTIC
Definition at line 35 of file iirfilter.h.
IIRFilterMode
enum IIRFilterMode
Enumerator
FF_FILTER_MODE_LOWPASS
FF_FILTER_MODE_HIGHPASS
FF_FILTER_MODE_BANDPASS
FF_FILTER_MODE_BANDSTOP
Definition at line 43 of file iirfilter.h.
Function Documentation
ff_iir_filter_init()
void ff_iir_filter_init (FFIIRFilterContext * f)
Initialize FFIIRFilterContext.
Definition at line 320 of file iirfilter.c.
Referenced by ff_psy_preprocess_init().
ff_iir_filter_init_mips()
void ff_iir_filter_init_mips (FFIIRFilterContext * f)
Definition at line 202 of file iirfilter_mips.c.
Referenced by ff_iir_filter_init().
ff_iir_filter_init_coeffs()
struct FFIIRFilterCoeffs* ff_iir_filter_init_coeffs (void * avc, enum IIRFilterType filt_type, enum IIRFilterMode filt_mode, int order, float cutoff_ratio, float stopband, float ripple)
Initialize filter coefficients.
Parameters
avc a pointer to an arbitrary struct of which the first field is a pointer to an AVClass struct
filt_type filter type (e.g. Butterworth)
filt_mode filter mode (e.g. lowpass)
order filter order
cutoff_ratio cutoff to input frequency ratio
stopband stopband to input frequency ratio (used by bandpass and bandstop filter modes)
ripple ripple factor (used only in Chebyshev filters)
Returns
pointer to filter coefficients structure or NULL if filter cannot be created
Definition at line 162 of file iirfilter.c.
Referenced by ff_psy_preprocess_init(), and main().
ff_iir_filter_init_state()
struct FFIIRFilterState* ff_iir_filter_init_state (int order)
Create new filter state.
Parameters
order filter order
Returns
pointer to new filter state or NULL if state creation fails
Definition at line 204 of file iirfilter.c.
Referenced by ff_psy_preprocess_init(), and main().
ff_iir_filter_free_coeffsp()
void ff_iir_filter_free_coeffsp (struct FFIIRFilterCoeffs ** coeffs)
Free filter coefficients.
Parameters
coeffs pointer allocated with ff_iir_filter_init_coeffs()
Definition at line 310 of file iirfilter.c.
Referenced by ff_iir_filter_init_coeffs(), ff_psy_preprocess_end(), and main().
ff_iir_filter_free_statep()
void ff_iir_filter_free_statep (struct FFIIRFilterState ** state)
Free and zero filter state.
Parameters
state pointer to pointer allocated with ff_iir_filter_init_state()
Definition at line 305 of file iirfilter.c.
Referenced by ff_psy_preprocess_end(), and main().
ff_iir_filter()
void ff_iir_filter (const struct FFIIRFilterCoeffs * coeffs, struct FFIIRFilterState * state, int size, const int16_t * src, int sstep, int16_t * dst, int dstep)
Perform IIR filtering on signed 16-bit input samples.
Parameters
coeffs pointer to filter coefficients
state pointer to filter state
size input length
src source samples
sstep source stride
dst filtered samples (destination may be the same as input)
dstep destination stride
Definition at line 279 of file iirfilter.c.
Referenced by main().
ff_iir_filter_flt()
void ff_iir_filter_flt (const struct FFIIRFilterCoeffs * coeffs, struct FFIIRFilterState * state, int size, const float * src, int sstep, float * dst, int dstep)
Perform IIR filtering on floating-point input samples.
Parameters
coeffs pointer to filter coefficients
state pointer to filter state
size input length
src source samples
sstep source stride
dst filtered samples (destination may be the same as input)
dstep destination stride
Definition at line 292 of file iirfilter.c.
Referenced by ff_iir_filter_init().