FFmpeg: libavcodec/iirfilter.c File Reference
iirfilter.c File Reference
different IIR filters implementation
#include <math.h>
#include "libavutil/attributes.h"
#include "libavutil/common.h"
#include "iirfilter.h"
Data Structures
struct FFIIRFilterCoeffs
IIR filter global parameters.
struct FFIIRFilterState
IIR filter state.
Macros
#define MAXORDER 30
maximum supported filter order
#define CONV_S16(dest, source) dest = av_clip_int16(lrintf(source));
#define CONV_FLT(dest, source) dest = source;
#define FILTER_BW_O4_1(i0, i1, i2, i3, fmt)
#define FILTER_BW_O4(type, fmt)
#define FILTER_DIRECT_FORM_II(type, fmt)
#define FILTER_O2(type, fmt)
Functions
static av_cold int butterworth_init_coeffs (void *avc, struct FFIIRFilterCoeffs *c, enum IIRFilterMode filt_mode, int order, float cutoff_ratio, float stopband)
static av_cold int biquad_init_coeffs (void *avc, struct FFIIRFilterCoeffs *c, enum IIRFilterMode filt_mode, int order, float cutoff_ratio, float stopband)
av_cold struct FFIIRFilterCoeffs * ff_iir_filter_init_coeffs (void *avc, enum IIRFilterType filt_type, enum IIRFilterMode filt_mode, int order, float cutoff_ratio, float stopband, float ripple)
Initialize filter coefficients.
av_cold struct FFIIRFilterState * ff_iir_filter_init_state (int order)
Create new filter state.
void ff_iir_filter (const struct FFIIRFilterCoeffs *c, struct FFIIRFilterState *s, int size, const int16_t *src, int sstep, int16_t *dst, int dstep)
Perform IIR filtering on signed 16-bit input samples.
void ff_iir_filter_flt (const struct FFIIRFilterCoeffs *c, struct FFIIRFilterState *s, int size, const float *src, int sstep, float *dst, int dstep)
Perform IIR filtering on floating-point input samples.
av_cold void ff_iir_filter_free_statep (struct FFIIRFilterState **state)
Free and zero filter state.
av_cold void ff_iir_filter_free_coeffsp (struct FFIIRFilterCoeffs **coeffsp)
Free filter coefficients.
void ff_iir_filter_init (FFIIRFilterContext *f)
Initialize FFIIRFilterContext.
Detailed Description
different IIR filters implementation
Definition in file iirfilter.c.
Macro Definition Documentation
MAXORDER
#define MAXORDER 30
maximum supported filter order
Definition at line 52 of file iirfilter.c.
Referenced by butterworth_init_coeffs(), and ff_iir_filter_init_coeffs().
CONV_S16
#define CONV_S16 (dest, source) dest = av_clip_int16(lrintf(source));
Definition at line 210 of file iirfilter.c.
CONV_FLT
#define CONV_FLT (dest, source) dest = source;
Definition at line 212 of file iirfilter.c.
FILTER_BW_O4_1
#define FILTER_BW_O4_1 (i0, i1, i2, i3, fmt)
Value:
in = *src0    * c->gain  +                          \
         c->cy[0] * s->x[i0] +                          \
         c->cy[1] * s->x[i1] +                          \
         c->cy[2] * s->x[i2] +                          \
         c->cy[3] * s->x[i3];                           \
    res = (s->x[i0] + in)       * 1 +                   \
          (s->x[i1] + s->x[i3]) * 4 +                   \
           s->x[i2]             * 6;                    \
    CONV_ ## fmt(*dst0, res)                            \
    s->x[i0] = in;                                      \
    src0    += sstep;                                   \
    dst0    += dstep;
Definition at line 214 of file iirfilter.c.
FILTER_BW_O4
#define FILTER_BW_O4 (type, fmt)
Value:
{           \
    int i;                                  \
    const type *src0 = src;                 \
    type       *dst0 = dst;                 \
    for (i = 0; i < size; i += 4) {         \
        float in, res;                      \
        FILTER_BW_O4_1(0, 1, 2, 3, fmt);    \
        FILTER_BW_O4_1(1, 2, 3, 0, fmt);    \
        FILTER_BW_O4_1(2, 3, 0, 1, fmt);    \
        FILTER_BW_O4_1(3, 0, 1, 2, fmt);    \
    }                                       \
}
Definition at line 228 of file iirfilter.c.
Referenced by ff_iir_filter(), and ff_iir_filter_flt().
FILTER_DIRECT_FORM_II
#define FILTER_DIRECT_FORM_II (type, fmt)
Value:
{                                  \
    int i;                                                                  \
    const type *src0 = src;                                                 \
    type       *dst0 = dst;                                                 \
    for (i = 0; i < size; i++) {                                            \
        int j;                                                              \
        float in, res;                                                      \
        in = *src0 * c->gain;                                               \
        for (j = 0; j < c->order; j++)                                      \
            in += c->cy[j] * s->x[j];                                       \
        res = s->x[0] + in + s->x[c->order >> 1] * c->cx[c->order >> 1];    \
        for (j = 1; j < c->order >> 1; j++)                                 \
            res += (s->x[j] + s->x[c->order - j]) * c->cx[j];               \
        for (j = 0; j < c->order - 1; j++)                                  \
            s->x[j] = s->x[j + 1];                                          \
        CONV_ ## fmt(*dst0, res)                                            \
        s->x[c->order - 1] = in;                                            \
        src0              += sstep;                                         \
        dst0              += dstep;                                         \
    }                                                                       \
}
Definition at line 241 of file iirfilter.c.
Referenced by ff_iir_filter(), and ff_iir_filter_flt().
FILTER_O2
#define FILTER_O2 (type, fmt)
Value:
{                                              \
    int i;                                                                  \
    const type *src0 = src;                                                 \
    type       *dst0 = dst;                                                 \
    for (i = 0; i < size; i++) {                                            \
        float in = *src0   * c->gain  +                                     \
                   s->x[0] * c->cy[0] +                                     \
                   s->x[1] * c->cy[1];                                      \
        CONV_ ## fmt(*dst0, s->x[0] + in + s->x[1] * c->cx[1])              \
        s->x[0] = s->x[1];                                                  \
        s->x[1] = in;                                                       \
        src0   += sstep;                                                    \
        dst0   += dstep;                                                    \
    }                                                                       \
}
Definition at line 263 of file iirfilter.c.
Referenced by ff_iir_filter(), and ff_iir_filter_flt().
Function Documentation
butterworth_init_coeffs()
static av_cold int butterworth_init_coeffs (void * avc, struct FFIIRFilterCoeffs * c, enum IIRFilterMode filt_mode, int order, float cutoff_ratio, float stopband) static
Definition at line 54 of file iirfilter.c.
Referenced by ff_iir_filter_init_coeffs().
biquad_init_coeffs()
static av_cold int biquad_init_coeffs (void * avc, struct FFIIRFilterCoeffs * c, enum IIRFilterMode filt_mode, int order, float cutoff_ratio, float stopband) static
Definition at line 119 of file iirfilter.c.
Referenced by ff_iir_filter_init_coeffs().
ff_iir_filter_init_coeffs()
av_cold struct FFIIRFilterCoeffs* ff_iir_filter_init_coeffs (void * avc, enum IIRFilterType filt_type, enum IIRFilterMode filt_mode, int order, float cutoff_ratio, float stopband, float ripple)
Initialize filter coefficients.
Parameters
avc a pointer to an arbitrary struct of which the first field is a pointer to an AVClass struct
filt_type filter type (e.g. Butterworth)
filt_mode filter mode (e.g. lowpass)
order filter order
cutoff_ratio cutoff to input frequency ratio
stopband stopband to input frequency ratio (used by bandpass and bandstop filter modes)
ripple ripple factor (used only in Chebyshev filters)
Returns
pointer to filter coefficients structure or NULL if filter cannot be created
Definition at line 162 of file iirfilter.c.
Referenced by ff_psy_preprocess_init(), and main().
ff_iir_filter_init_state()
av_cold struct FFIIRFilterState* ff_iir_filter_init_state (int order)
Create new filter state.
Parameters
order filter order
Returns
pointer to new filter state or NULL if state creation fails
Definition at line 204 of file iirfilter.c.
Referenced by ff_psy_preprocess_init(), and main().
ff_iir_filter()
void ff_iir_filter (const struct FFIIRFilterCoeffs * coeffs, struct FFIIRFilterState * state, int size, const int16_t * src, int sstep, int16_t * dst, int dstep)
Perform IIR filtering on signed 16-bit input samples.
Parameters
coeffs pointer to filter coefficients
state pointer to filter state
size input length
src source samples
sstep source stride
dst filtered samples (destination may be the same as input)
dstep destination stride
Definition at line 279 of file iirfilter.c.
Referenced by main().
ff_iir_filter_flt()
void ff_iir_filter_flt (const struct FFIIRFilterCoeffs * coeffs, struct FFIIRFilterState * state, int size, const float * src, int sstep, float * dst, int dstep)
Perform IIR filtering on floating-point input samples.
Parameters
coeffs pointer to filter coefficients
state pointer to filter state
size input length
src source samples
sstep source stride
dst filtered samples (destination may be the same as input)
dstep destination stride
Definition at line 292 of file iirfilter.c.
Referenced by ff_iir_filter_init().
ff_iir_filter_free_statep()
av_cold void ff_iir_filter_free_statep (struct FFIIRFilterState ** state)
Free and zero filter state.
Parameters
state pointer to pointer allocated with ff_iir_filter_init_state()
Definition at line 305 of file iirfilter.c.
Referenced by ff_psy_preprocess_end(), and main().
ff_iir_filter_free_coeffsp()
av_cold void ff_iir_filter_free_coeffsp (struct FFIIRFilterCoeffs ** coeffs)
Free filter coefficients.
Parameters
coeffs pointer allocated with ff_iir_filter_init_coeffs()
Definition at line 310 of file iirfilter.c.
Referenced by ff_iir_filter_init_coeffs(), ff_psy_preprocess_end(), and main().
ff_iir_filter_init()
void ff_iir_filter_init (FFIIRFilterContext * f)
Initialize FFIIRFilterContext.
Definition at line 320 of file iirfilter.c.
Referenced by ff_psy_preprocess_init().