FFmpeg: libavcodec/imdct15.h File Reference
imdct15.h File Reference
#include <stddef.h>
#include "avfft.h"
Data Structures
struct IMDCT15Context
Functions
int ff_imdct15_init (IMDCT15Context **s, int N)
Init an iMDCT of the length 2 * 15 * (2^N)
void ff_imdct15_uninit (IMDCT15Context **s)
Free an iMDCT.
void ff_imdct15_init_aarch64 (IMDCT15Context *s)
Function Documentation
ff_imdct15_init()
int ff_imdct15_init (IMDCT15Context ** s, int N)
Init an iMDCT of the length 2 * 15 * (2^N)
Definition at line 90 of file imdct15.c.
Referenced by aac_decode_init(), and ff_celt_init().
ff_imdct15_uninit()
void ff_imdct15_uninit (IMDCT15Context ** s)
Free an iMDCT.
Definition at line 69 of file imdct15.c.
Referenced by aac_decode_close(), ff_celt_free(), and ff_imdct15_init().
ff_imdct15_init_aarch64()
void ff_imdct15_init_aarch64 (IMDCT15Context * s)
Definition at line 39 of file imdct15_init.c.
Referenced by ff_imdct15_init().