FFmpeg: libavcodec/imdct15.c File Reference
imdct15.c File Reference
Celt non-power of 2 iMDCT.
#include <float.h>
#include <math.h>
#include <stddef.h>
#include "config.h"
#include "libavutil/attributes.h"
#include "libavutil/common.h"
#include "avfft.h"
#include "imdct15.h"
#include "opus.h"
Macros
#define CELT_MIN_IMDCT_SIZE 120
#define CMUL3(cre, cim, are, aim, bre, bim)
#define CMUL(c, a, b) CMUL3((c).re, (c).im, (a).re, (a).im, (b).re, (b).im)
#define CMUL2(c, d, a, b)
Functions
av_cold void ff_imdct15_uninit (IMDCT15Context **ps)
Free an iMDCT.
static void imdct15_half (IMDCT15Context *s, float *dst, const float *src, ptrdiff_t stride, float scale)
av_cold int ff_imdct15_init (IMDCT15Context **ps, int N)
Init an iMDCT of the length 2 * 15 * (2^N)
static void fft5 (FFTComplex *out, const FFTComplex *in, ptrdiff_t stride)
static void fft15 (IMDCT15Context *s, FFTComplex *out, const FFTComplex *in, ptrdiff_t stride)
static void fft_calc (IMDCT15Context *s, FFTComplex *out, const FFTComplex *in, int N, ptrdiff_t stride)
Detailed Description
Celt non-power of 2 iMDCT.
Definition in file imdct15.c.
Macro Definition Documentation
CELT_MIN_IMDCT_SIZE
#define CELT_MIN_IMDCT_SIZE 120
Definition at line 40 of file imdct15.c.
Referenced by ff_imdct15_init().
CMUL3
#define CMUL3 (cre, cim, are, aim, bre, bim)
Value:
do {                                                 \
    cre = are * bre - aim * bim;                     \
    cim = are * bim + aim * bre;                     \
} while (0)
Definition at line 43 of file imdct15.c.
Referenced by imdct15_half().
CMUL
#define CMUL (c, a, b) CMUL3((c).re, (c).im, (a).re, (a).im, (b).re, (b).im)
Definition at line 49 of file imdct15.c.
Referenced by fft15(), fft_calc(), and imdct15_half().
CMUL2
#define CMUL2 (c, d, a, b)
Value:
do {                                                 \
    float are = (a).re;                              \
    float aim = (a).im;                              \
    float bre = (b).re;                              \
    float bim = (b).im;                              \
    float rr  = are * bre;                           \
    float ri  = are * bim;                           \
    float ir  = aim * bre;                           \
    float ii  = aim * bim;                           \
    (c).re =  rr - ii;                               \
    (c).im =  ri + ir;                               \
    (d).re =  rr + ii;                               \
    (d).im = -ri + ir;                               \
} while (0)
Definition at line 53 of file imdct15.c.
Referenced by fft5().
Function Documentation
ff_imdct15_uninit()
av_cold void ff_imdct15_uninit (IMDCT15Context ** ps)
Free an iMDCT.
Definition at line 69 of file imdct15.c.
Referenced by aac_decode_close(), ff_celt_free(), and ff_imdct15_init().
imdct15_half()
static void imdct15_half (IMDCT15Context * s, float * dst, const float * src, ptrdiff_t stride, float scale) static
Definition at line 246 of file imdct15.c.
Referenced by ff_imdct15_init(), and ff_imdct15_uninit().
ff_imdct15_init()
av_cold int ff_imdct15_init (IMDCT15Context ** ps, int N)
Init an iMDCT of the length 2 * 15 * (2^N)
Definition at line 90 of file imdct15.c.
Referenced by aac_decode_init(), and ff_celt_init().
fft5()
static void fft5 (FFTComplex * out, const FFTComplex * in, ptrdiff_t stride) static
Definition at line 151 of file imdct15.c.
Referenced by fft15().
fft15()
static void fft15 (IMDCT15Context * s, FFTComplex * out, const FFTComplex * in, ptrdiff_t stride) static
Definition at line 184 of file imdct15.c.
Referenced by fft_calc().
fft_calc()
static void fft_calc (IMDCT15Context * s, FFTComplex * out, const FFTComplex * in, int N, ptrdiff_t stride) static
Definition at line 220 of file imdct15.c.
Referenced by imdct15_half().