FFmpeg: libavformat/img2dec.c File Reference
img2dec.c File Reference
#include <sys/stat.h>
#include "libavutil/avstring.h"
#include "libavutil/log.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "libavutil/parseutils.h"
#include "libavutil/intreadwrite.h"
#include "avformat.h"
#include "avio_internal.h"
#include "internal.h"
#include "img2.h"
#include "libavcodec/mjpeg.h"
Macros
#define _DEFAULT_SOURCE
#define _BSD_SOURCE
#define OFFSET(x) offsetof(VideoDemuxData, x)
#define DEC AV_OPT_FLAG_DECODING_PARAM
#define IMAGEAUTO_DEMUXER(imgname, codecid)
Functions
static int infer_size (int *width_ptr, int *height_ptr, int size)
static int is_glob (const char *path)
static int find_image_range (AVIOContext *pb, int *pfirst_index, int *plast_index, const char *path, int start_index, int start_index_range)
Get index range of image files matched by path.
static int img_read_probe (AVProbeData *p)
int ff_img_read_header (AVFormatContext *s1)
int ff_img_read_packet (AVFormatContext *s1, AVPacket *pkt)
static int img_read_close (struct AVFormatContext *s1)
static int img_read_seek (AVFormatContext *s, int stream_index, int64_t timestamp, int flags)
static int bmp_probe (AVProbeData *p)
static int dds_probe (AVProbeData *p)
static int dpx_probe (AVProbeData *p)
static int exr_probe (AVProbeData *p)
static int j2k_probe (AVProbeData *p)
static int jpeg_probe (AVProbeData *p)
static int jpegls_probe (AVProbeData *p)
static int pcx_probe (AVProbeData *p)
static int qdraw_probe (AVProbeData *p)
static int pictor_probe (AVProbeData *p)
static int png_probe (AVProbeData *p)
static int psd_probe (AVProbeData *p)
static int sgi_probe (AVProbeData *p)
static int sunrast_probe (AVProbeData *p)
static int tiff_probe (AVProbeData *p)
static int webp_probe (AVProbeData *p)
static int pnm_magic_check (const AVProbeData *p, int magic)
static int pnm_probe (const AVProbeData *p)
static int pbm_probe (AVProbeData *p)
static int pgmx_probe (AVProbeData *p)
static int pgm_probe (AVProbeData *p)
static int pgmyuv_probe (AVProbeData *p)
static int ppm_probe (AVProbeData *p)
static int pam_probe (AVProbeData *p)
Variables
static const int sizes [][2]
const AVOption ff_img_options []
Macro Definition Documentation
_DEFAULT_SOURCE
#define _DEFAULT_SOURCE
Definition at line 23 of file img2dec.c.
_BSD_SOURCE
#define _BSD_SOURCE
Definition at line 24 of file img2dec.c.
OFFSET
#define OFFSET (x) offsetof(VideoDemuxData, x)
Definition at line 561 of file img2dec.c.
DEC
#define DEC AV_OPT_FLAG_DECODING_PARAM
Definition at line 562 of file img2dec.c.
IMAGEAUTO_DEMUXER
#define IMAGEAUTO_DEMUXER (imgname, codecid)
Value:
static const AVClass imgname ## _class = {\
    .class_name = AV_STRINGIFY(imgname) " demuxer",\
    .item_name  = av_default_item_name,\
    .option     = ff_img_options,\
    .version    = LIBAVUTIL_VERSION_INT,\
};\
AVInputFormat ff_image_ ## imgname ## _pipe_demuxer = {\
    .name           = AV_STRINGIFY(imgname) "_pipe",\
    .long_name      = NULL_IF_CONFIG_SMALL("piped " AV_STRINGIFY(imgname) " sequence"),\
    .priv_data_size = sizeof(VideoDemuxData),\
    .read_probe     = imgname ## _probe,\
    .read_header    = ff_img_read_header,\
    .read_packet    = ff_img_read_packet,\
    .priv_class     = & imgname ## _class,\
    .flags          = AVFMT_GENERIC_INDEX, \
    .raw_codec_id   = codecid,\
};
Definition at line 946 of file img2dec.c.
Function Documentation
infer_size()
static int infer_size (int * width_ptr, int * height_ptr, int size) static
Definition at line 62 of file img2dec.c.
Referenced by ff_img_read_packet().
is_glob()
static int is_glob (const char * path) static
Definition at line 77 of file img2dec.c.
Referenced by ff_img_read_header(), and img_read_probe().
find_image_range()
static int find_image_range (AVIOContext * pb, int * pfirst_index, int * plast_index, const char * path, int start_index, int start_index_range) static
Get index range of image files matched by path.
Parameters
pfirst_index pointer to index updated with the first number in the range
plast_index pointer to index updated with the last number in the range
path path which has to be matched by the image files in the range
start_index minimum accepted value for the first index in the range
Returns
-1 if no image file could be found
Definition at line 107 of file img2dec.c.
Referenced by ff_img_read_header().
img_read_probe()
static int img_read_probe (AVProbeData * p) static
Definition at line 160 of file img2dec.c.
ff_img_read_header()
int ff_img_read_header (AVFormatContext * s1)
Definition at line 179 of file img2dec.c.
ff_img_read_packet()
int ff_img_read_packet (AVFormatContext * s1, AVPacket * pkt)
Definition at line 372 of file img2dec.c.
img_read_close()
static int img_read_close (struct AVFormatContext * s1) static
Definition at line 530 of file img2dec.c.
img_read_seek()
static int img_read_seek (AVFormatContext * s, int stream_index, int64_t timestamp, int flags) static
Definition at line 541 of file img2dec.c.
bmp_probe()
static int bmp_probe (AVProbeData * p) static
Definition at line 622 of file img2dec.c.
dds_probe()
static int dds_probe (AVProbeData * p) static
Definition at line 640 of file img2dec.c.
dpx_probe()
static int dpx_probe (AVProbeData * p) static
Definition at line 651 of file img2dec.c.
exr_probe()
static int exr_probe (AVProbeData * p) static
Definition at line 669 of file img2dec.c.
j2k_probe()
static int j2k_probe (AVProbeData * p) static
Definition at line 678 of file img2dec.c.
jpeg_probe()
static int jpeg_probe (AVProbeData * p) static
Definition at line 688 of file img2dec.c.
jpegls_probe()
static int jpegls_probe (AVProbeData * p) static
Definition at line 763 of file img2dec.c.
pcx_probe()
static int pcx_probe (AVProbeData * p) static
Definition at line 772 of file img2dec.c.
qdraw_probe()
static int qdraw_probe (AVProbeData * p) static
Definition at line 793 of file img2dec.c.
pictor_probe()
static int pictor_probe (AVProbeData * p) static
Definition at line 809 of file img2dec.c.
png_probe()
static int png_probe (AVProbeData * p) static
Definition at line 818 of file img2dec.c.
psd_probe()
static int psd_probe (AVProbeData * p) static
Definition at line 827 of file img2dec.c.
sgi_probe()
static int sgi_probe (AVProbeData * p) static
Definition at line 855 of file img2dec.c.
sunrast_probe()
static int sunrast_probe (AVProbeData * p) static
Definition at line 867 of file img2dec.c.
tiff_probe()
static int tiff_probe (AVProbeData * p) static
Definition at line 876 of file img2dec.c.
webp_probe()
static int webp_probe (AVProbeData * p) static
Definition at line 886 of file img2dec.c.
pnm_magic_check()
static int pnm_magic_check (const AVProbeData * p, int magic) static
Definition at line 896 of file img2dec.c.
Referenced by pam_probe(), pbm_probe(), pgmx_probe(), and ppm_probe().
pnm_probe()
static int pnm_probe (const AVProbeData * p) inline static
Definition at line 903 of file img2dec.c.
Referenced by pam_probe(), pbm_probe(), pgmx_probe(), and ppm_probe().
pbm_probe()
static int pbm_probe (AVProbeData * p) static
Definition at line 914 of file img2dec.c.
pgmx_probe()
static int pgmx_probe (AVProbeData * p) inline static
Definition at line 919 of file img2dec.c.
Referenced by pgm_probe(), and pgmyuv_probe().
pgm_probe()
static int pgm_probe (AVProbeData * p) static
Definition at line 924 of file img2dec.c.
pgmyuv_probe()
static int pgmyuv_probe (AVProbeData * p) static
Definition at line 930 of file img2dec.c.
ppm_probe()
static int ppm_probe (AVProbeData * p) static
Definition at line 936 of file img2dec.c.
pam_probe()
static int pam_probe (AVProbeData * p) static
Definition at line 941 of file img2dec.c.
Variable Documentation
sizes
const int sizes[][2] static
Initial value:
= {
    { 640, 480 },
    { 720, 480 },
    { 720, 576 },
    { 352, 288 },
    { 352, 240 },
    { 160, 128 },
    { 512, 384 },
    { 640, 352 },
    { 640, 240 },
}
Definition at line 50 of file img2dec.c.
Referenced by aac_encode_init(), encode_frame(), infer_size(), ra144_decode_frame(), ra144_encode_frame(), setup_partitions(), svq1_decode_init(), and x8_vlc_init().
ff_img_options
const AVOption ff_img_options[]
Initial value:
= {
    { "framerate",    "set the video framerate",             OFFSET(framerate),    AV_OPT_TYPE_VIDEO_RATE, {.str = "25"}, 0, INT_MAX,   DEC },
    { "loop",         "force loop over input file sequence", OFFSET(loop),         AV_OPT_TYPE_BOOL,   {.i64 = 0   }, 0, 1,       DEC },
    { "pattern_type", "set pattern type",                    OFFSET(pattern_type), AV_OPT_TYPE_INT,    {.i64=PT_DEFAULT}, 0,       INT_MAX, DEC, "pattern_type"},
    { "glob_sequence","select glob/sequence pattern type",   0, AV_OPT_TYPE_CONST,  {.i64=PT_GLOB_SEQUENCE}, INT_MIN, INT_MAX, DEC, "pattern_type" },
    { "glob",         "select glob pattern type",            0, AV_OPT_TYPE_CONST,  {.i64=PT_GLOB         }, INT_MIN, INT_MAX, DEC, "pattern_type" },
    { "sequence",     "select sequence pattern type",        0, AV_OPT_TYPE_CONST,  {.i64=PT_SEQUENCE     }, INT_MIN, INT_MAX, DEC, "pattern_type" },
    { "none",         "disable pattern matching",            0, AV_OPT_TYPE_CONST,  {.i64=PT_NONE         }, INT_MIN, INT_MAX, DEC, "pattern_type" },
    { "pixel_format", "set video pixel format",              OFFSET(pixel_format), AV_OPT_TYPE_STRING, {.str = NULL}, 0, 0,       DEC },
    { "start_number", "set first number in the sequence",    OFFSET(start_number), AV_OPT_TYPE_INT,    {.i64 = 0   }, INT_MIN, INT_MAX, DEC },
    { "start_number_range", "set range for looking at the first sequence number", OFFSET(start_number_range), AV_OPT_TYPE_INT, {.i64 = 5}, 1, INT_MAX, DEC },
    { "video_size",   "set video size",                      OFFSET(width),        AV_OPT_TYPE_IMAGE_SIZE, {.str = NULL}, 0, 0,   DEC },
    { "frame_size",   "force frame size in bytes",           OFFSET(frame_size),   AV_OPT_TYPE_INT,    {.i64 = 0   }, 0, INT_MAX, DEC },
    { "ts_from_file", "set frame timestamp from file's one", OFFSET(ts_from_file), AV_OPT_TYPE_INT,    {.i64 = 0   }, 0, 2,       DEC, "ts_type" },
    { "none", "none",                   0, AV_OPT_TYPE_CONST,    {.i64 = 0   }, 0, 2,       DEC, "ts_type" },
    { "sec",  "second precision",       0, AV_OPT_TYPE_CONST,    {.i64 = 1   }, 0, 2,       DEC, "ts_type" },
    { "ns",   "nano second precision",  0, AV_OPT_TYPE_CONST,    {.i64 = 2   }, 0, 2,       DEC, "ts_type" },
    { NULL },
}
Definition at line 563 of file img2dec.c.