FFmpeg: libavformat/img2.c File Reference
img2.c File Reference
#include "libavutil/avstring.h"
#include "internal.h"
#include "img2.h"
Functions
static enum AVCodecID str2id (const IdStrMap *tags, const char *str)
enum AVCodecID ff_guess_image2_codec (const char *filename)
Variables
const IdStrMap ff_img_tags []
Function Documentation
str2id()
static enum AVCodecID str2id (const IdStrMap * tags, const char * str) static
Definition at line 83 of file img2.c.
Referenced by ff_guess_image2_codec().
ff_guess_image2_codec()
enum AVCodecID ff_guess_image2_codec (const char * filename)
Definition at line 99 of file img2.c.
Referenced by ape_tag_read_field(), av_guess_codec(), av_guess_format(), ff_img_read_header(), and img_read_probe().
Variable Documentation
ff_img_tags
const IdStrMap ff_img_tags[]
Definition at line 27 of file img2.c.
Referenced by query_codec().