FFmpeg: libavutil/imgutils.c File Reference
imgutils.c File Reference
misc image utilities
#include "avassert.h"
#include "common.h"
#include "imgutils.h"
#include "internal.h"
#include "intreadwrite.h"
#include "log.h"
#include "mathematics.h"
#include "pixdesc.h"
#include "rational.h"
Data Structures
struct ImgUtils
Functions
void av_image_fill_max_pixsteps (int max_pixsteps[4], int max_pixstep_comps[4], const AVPixFmtDescriptor *pixdesc)
Compute the max pixel step for each plane of an image with a format described by pixdesc.
static int image_get_linesize (int width, int plane, int max_step, int max_step_comp, const AVPixFmtDescriptor *desc)
int av_image_get_linesize (enum AVPixelFormat pix_fmt, int width, int plane)
Compute the size of an image line with format pix_fmt and width width for the plane plane.
int av_image_fill_linesizes (int linesizes[4], enum AVPixelFormat pix_fmt, int width)
Fill plane linesizes for an image with pixel format pix_fmt and width width.
int av_image_fill_pointers (uint8_t *data[4], enum AVPixelFormat pix_fmt, int height, uint8_t *ptr, const int linesizes[4])
Fill plane data pointers for an image with pixel format pix_fmt and height height.
int avpriv_set_systematic_pal2 (uint32_t pal[256], enum AVPixelFormat pix_fmt)
int av_image_alloc (uint8_t *pointers[4], int linesizes[4], int w, int h, enum AVPixelFormat pix_fmt, int align)
Allocate an image with size w and h and pixel format pix_fmt, and fill pointers and linesizes accordingly.
int av_image_check_size2 (unsigned int w, unsigned int h, int64_t max_pixels, enum AVPixelFormat pix_fmt, int log_offset, void *log_ctx)
Check if the given dimension of an image is valid, meaning that all bytes of a plane of an image with the specified pix_fmt can be addressed with a signed int.
int av_image_check_size (unsigned int w, unsigned int h, int log_offset, void *log_ctx)
Check if the given dimension of an image is valid, meaning that all bytes of the image can be addressed with a signed int.
int av_image_check_sar (unsigned int w, unsigned int h, AVRational sar)
Check if the given sample aspect ratio of an image is valid.
void av_image_copy_plane (uint8_t *dst, int dst_linesize, const uint8_t *src, int src_linesize, int bytewidth, int height)
Copy image plane from src to dst.
void av_image_copy (uint8_t *dst_data[4], int dst_linesizes[4], const uint8_t *src_data[4], const int src_linesizes[4], enum AVPixelFormat pix_fmt, int width, int height)
Copy image in src_data to dst_data.
int av_image_fill_arrays (uint8_t *dst_data[4], int dst_linesize[4], const uint8_t *src, enum AVPixelFormat pix_fmt, int width, int height, int align)
Setup the data pointers and linesizes based on the specified image parameters and the provided array.
int av_image_get_buffer_size (enum AVPixelFormat pix_fmt, int width, int height, int align)
Return the size in bytes of the amount of data required to store an image with the given parameters.
int av_image_copy_to_buffer (uint8_t *dst, int dst_size, const uint8_t *const src_data[4], const int src_linesize[4], enum AVPixelFormat pix_fmt, int width, int height, int align)
Copy image data from an image into a buffer.
Variables
static const AVClass imgutils_class
Detailed Description
misc image utilities
Definition in file imgutils.c.
Function Documentation
image_get_linesize()
static int image_get_linesize (int width, int plane, int max_step, int max_step_comp, const AVPixFmtDescriptor * desc) inline static
Definition at line 53 of file imgutils.c.
Referenced by av_image_fill_linesizes(), and av_image_get_linesize().
avpriv_set_systematic_pal2()
int avpriv_set_systematic_pal2 (uint32_t pal[256], enum AVPixelFormat pix_fmt)
Definition at line 151 of file imgutils.c.
Referenced by av_image_alloc(), bmp_encode_frame(), ff_rint64_clip(), ff_video_frame_pool_get(), filter_frame(), gif_encode_init(), gif_write_header(), pcx_encode_frame(), raw_init_decoder(), and video_get_buffer().
Variable Documentation
imgutils_class
const AVClass imgutils_class static
Initial value:
= {
    .class_name = "IMGUTILS",
    .item_name  = av_default_item_name,
    .version    = LIBAVUTIL_VERSION_INT,
    .log_level_offset_offset   = 0x42,
    .parent_log_context_offset = 0x42,
}
Definition at line 243 of file imgutils.c.
Referenced by av_image_check_size2().