FFmpeg: libavcodec/indeo5.c File Reference
indeo5.c File Reference
Indeo Video Interactive version 5 decoder.
#include "avcodec.h"
#include "get_bits.h"
#include "ivi.h"
#include "ivi_dsp.h"
#include "indeo5data.h"
Macros
#define BITSTREAM_READER_LE
#define IVI5_PIC_SIZE_ESC 15
Enumerations
enum {
FRAMETYPE_INTRA = 0, FRAMETYPE_INTER = 1, FRAMETYPE_INTER_SCAL = 2, FRAMETYPE_INTER_NOREF = 3,
FRAMETYPE_NULL = 4
}
Indeo5 frame types.
Functions
static int decode_gop_header (IVI45DecContext *ctx, AVCodecContext *avctx)
Decode Indeo5 GOP (Group of pictures) header.
static int skip_hdr_extension (GetBitContext *gb)
Skip a header extension.
static int decode_pic_hdr (IVI45DecContext *ctx, AVCodecContext *avctx)
Decode Indeo5 picture header.
static int decode_band_hdr (IVI45DecContext *ctx, IVIBandDesc *band, AVCodecContext *avctx)
Decode Indeo5 band header.
static int decode_mb_info (IVI45DecContext *ctx, IVIBandDesc *band, IVITile *tile, AVCodecContext *avctx)
Decode info (block type, cbp, quant delta, motion vector) for all macroblocks in the current tile.
static void switch_buffers (IVI45DecContext *ctx)
Switch buffers.
static int is_nonnull_frame (IVI45DecContext *ctx)
static av_cold int decode_init (AVCodecContext *avctx)
Initialize Indeo5 decoder.
Variables
AVCodec ff_indeo5_decoder
Detailed Description
Indeo Video Interactive version 5 decoder.
Indeo5 data is usually transported within .avi or .mov files. Known FOURCCs: 'IV50'
Definition in file indeo5.c.
Macro Definition Documentation
BITSTREAM_READER_LE
#define BITSTREAM_READER_LE
Definition at line 30 of file indeo5.c.
IVI5_PIC_SIZE_ESC
#define IVI5_PIC_SIZE_ESC 15
Definition at line 48 of file indeo5.c.
Referenced by decode_gop_header().
Enumeration Type Documentation
anonymous enum
anonymous enum
Indeo5 frame types.
Enumerator
FRAMETYPE_INTRA
FRAMETYPE_INTER
non-droppable P-frame
FRAMETYPE_INTER_SCAL
droppable P-frame used in the scalability mode
FRAMETYPE_INTER_NOREF
droppable P-frame
FRAMETYPE_NULL
empty frame with no data
Definition at line 40 of file indeo5.c.
Function Documentation
decode_gop_header()
static int decode_gop_header (IVI45DecContext * ctx, AVCodecContext * avctx) static
Decode Indeo5 GOP (Group of pictures) header.
This header is present in key frames only. It defines parameters for all frames in a GOP.
Parameters
[in,out] ctx ptr to the decoder context
[in] avctx ptr to the AVCodecContext
Returns
result code: 0 = OK, -1 = error
Definition at line 59 of file indeo5.c.
Referenced by decode_pic_hdr().
skip_hdr_extension()
static int skip_hdr_extension (GetBitContext * gb) inline static
Skip a header extension.
Parameters
[in,out] gb the GetBit context
Definition at line 292 of file indeo5.c.
Referenced by decode_band_hdr(), and decode_pic_hdr().
decode_pic_hdr()
static int decode_pic_hdr (IVI45DecContext * ctx, AVCodecContext * avctx) static
Decode Indeo5 picture header.
Parameters
[in,out] ctx ptr to the decoder context
[in] avctx ptr to the AVCodecContext
Returns
result code: 0 = OK, -1 = error
Definition at line 314 of file indeo5.c.
Referenced by decode_init().
decode_band_hdr()
static int decode_band_hdr (IVI45DecContext * ctx, IVIBandDesc * band, AVCodecContext * avctx) static
Decode Indeo5 band header.
Parameters
[in,out] ctx ptr to the decoder context
[in,out] band ptr to the band descriptor
[in] avctx ptr to the AVCodecContext
Returns
result code: 0 = OK, -1 = error
Definition at line 381 of file indeo5.c.
Referenced by decode_init().
decode_mb_info()
static int decode_mb_info (IVI45DecContext * ctx, IVIBandDesc * band, IVITile * tile, AVCodecContext * avctx) static
Decode info (block type, cbp, quant delta, motion vector) for all macroblocks in the current tile.
Parameters
[in,out] ctx ptr to the decoder context
[in,out] band ptr to the band descriptor
[in,out] tile ptr to the tile descriptor
[in] avctx ptr to the AVCodecContext
Returns
result code: 0 = OK, -1 = error
Definition at line 453 of file indeo5.c.
Referenced by decode_init().
switch_buffers()
static void switch_buffers (IVI45DecContext * ctx) static
Switch buffers.
Parameters
[in,out] ctx ptr to the decoder context
Definition at line 592 of file indeo5.c.
Referenced by decode_init().
is_nonnull_frame()
static int is_nonnull_frame (IVI45DecContext * ctx) static
Definition at line 630 of file indeo5.c.
Referenced by decode_init().
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Initialize Indeo5 decoder.
Definition at line 639 of file indeo5.c.
Variable Documentation
ff_indeo5_decoder
AVCodec ff_indeo5_decoder
Initial value:
= {
    .name           = "indeo5",
    .long_name      = NULL_IF_CONFIG_SMALL("Intel Indeo Video Interactive 5"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_INDEO5,
    .priv_data_size = sizeof(IVI45DecContext),
    .init           = decode_init,
    .close          = ff_ivi_decode_close,
    .decode         = ff_ivi_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 682 of file indeo5.c.