FFmpeg: libavcodec/indeo4.c File Reference
indeo4.c File Reference
Indeo Video Interactive version 4 decoder.
#include "avcodec.h"
#include "get_bits.h"
#include "indeo4data.h"
#include "internal.h"
#include "ivi.h"
#include "ivi_dsp.h"
Macros
#define BITSTREAM_READER_LE
#define IVI4_PIC_SIZE_ESC 7
Functions
static int decode_plane_subdivision (GetBitContext *gb)
Decode subdivision of a plane.
static int scale_tile_size (int def_size, int size_factor)
static int decode_pic_hdr (IVI45DecContext *ctx, AVCodecContext *avctx)
Decode Indeo 4 picture header.
static int decode_band_hdr (IVI45DecContext *ctx, IVIBandDesc *band, AVCodecContext *avctx)
Decode Indeo 4 band header.
static int decode_mb_info (IVI45DecContext *ctx, IVIBandDesc *band, IVITile *tile, AVCodecContext *avctx)
Decode information (block type, cbp, quant delta, motion vector) for all macroblocks in the current tile.
static void switch_buffers (IVI45DecContext *ctx)
Rearrange decoding and reference buffers.
static int is_nonnull_frame (IVI45DecContext *ctx)
static av_cold int decode_init (AVCodecContext *avctx)
Variables
struct {
InvTransformPtr * inv_trans
DCTransformPtr * dc_trans
int is_2d_trans
} transforms [18]
AVCodec ff_indeo4_decoder
Detailed Description
Indeo Video Interactive version 4 decoder.
Indeo 4 data is usually transported within .avi or .mov files. Known FOURCCs: 'IV41'
Definition in file indeo4.c.
Macro Definition Documentation
BITSTREAM_READER_LE
#define BITSTREAM_READER_LE
Definition at line 30 of file indeo4.c.
IVI4_PIC_SIZE_ESC
#define IVI4_PIC_SIZE_ESC 7
Definition at line 38 of file indeo4.c.
Referenced by decode_pic_hdr().
Function Documentation
decode_plane_subdivision()
static int decode_plane_subdivision (GetBitContext * gb) static
Decode subdivision of a plane.
This is a simplified version that checks for two supported subdivisions:
1 wavelet band per plane, size factor 1:1, code pattern: 3
4 wavelet bands per plane, size factor 1:4, code pattern: 2,3,3,3,3 Anything else is either unsupported or corrupt.
Parameters
[in,out] gb the GetBit context
Returns
number of wavelet bands or 0 on error
Definition at line 76 of file indeo4.c.
Referenced by decode_pic_hdr().
scale_tile_size()
static int scale_tile_size (int def_size, int size_factor) inline static
Definition at line 93 of file indeo4.c.
Referenced by decode_pic_hdr().
decode_pic_hdr()
static int decode_pic_hdr (IVI45DecContext * ctx, AVCodecContext * avctx) static
Decode Indeo 4 picture header.
Parameters
[in,out] ctx pointer to the decoder context
[in] avctx pointer to the AVCodecContext
Returns
result code: 0 = OK, negative number = error
Definition at line 105 of file indeo4.c.
Referenced by decode_init().
decode_band_hdr()
static int decode_band_hdr (IVI45DecContext * ctx, IVIBandDesc * band, AVCodecContext * avctx) static
Decode Indeo 4 band header.
Parameters
[in,out] ctx pointer to the decoder context
[in,out] band pointer to the band descriptor
[in] avctx pointer to the AVCodecContext
Returns
result code: 0 = OK, negative number = error
Definition at line 261 of file indeo4.c.
Referenced by decode_init().
decode_mb_info()
static int decode_mb_info (IVI45DecContext * ctx, IVIBandDesc * band, IVITile * tile, AVCodecContext * avctx) static
Decode information (block type, cbp, quant delta, motion vector) for all macroblocks in the current tile.
Parameters
[in,out] ctx pointer to the decoder context
[in,out] band pointer to the band descriptor
[in,out] tile pointer to the tile descriptor
[in] avctx pointer to the AVCodecContext
Returns
result code: 0 = OK, negative number = error
Definition at line 454 of file indeo4.c.
Referenced by decode_init().
switch_buffers()
static void switch_buffers (IVI45DecContext * ctx) static
Rearrange decoding and reference buffers.
Parameters
[in,out] ctx pointer to the decoder context
Definition at line 615 of file indeo4.c.
Referenced by decode_init().
is_nonnull_frame()
static int is_nonnull_frame (IVI45DecContext * ctx) static
Definition at line 644 of file indeo4.c.
Referenced by decode_init().
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 650 of file indeo4.c.
Variable Documentation
inv_trans
InvTransformPtr* inv_trans
Definition at line 42 of file indeo4.c.
Referenced by decode_band_hdr().
dc_trans
DCTransformPtr* dc_trans
Definition at line 43 of file indeo4.c.
is_2d_trans
int is_2d_trans
Definition at line 44 of file indeo4.c.
transforms
const { ... } transforms[18]
Initial value:
= {
    { ff_ivi_inverse_haar_8x8,  ff_ivi_dc_haar_2d,       1 },
    { ff_ivi_row_haar8,         ff_ivi_dc_haar_2d,       0 },
    { ff_ivi_col_haar8,         ff_ivi_dc_haar_2d,       0 },
    { ff_ivi_put_pixels_8x8,    ff_ivi_put_dc_pixel_8x8, 1 },
    { ff_ivi_inverse_slant_8x8, ff_ivi_dc_slant_2d,      1 },
    { ff_ivi_row_slant8,        ff_ivi_dc_row_slant,     1 },
    { ff_ivi_col_slant8,        ff_ivi_dc_col_slant,     1 },
    { NULL, NULL, 0 },
    { NULL, NULL, 0 },
    { NULL, NULL, 0 },
    { ff_ivi_inverse_haar_4x4,  ff_ivi_dc_haar_2d,       1 },
    { ff_ivi_inverse_slant_4x4, ff_ivi_dc_slant_2d,      1 },
    { NULL, NULL, 0 },
    { ff_ivi_row_haar4,         ff_ivi_dc_haar_2d,       0 },
    { ff_ivi_col_haar4,         ff_ivi_dc_haar_2d,       0 },
    { ff_ivi_row_slant4,        ff_ivi_dc_row_slant,     0 },
    { ff_ivi_col_slant4,        ff_ivi_dc_col_slant,     0 },
    { NULL, NULL, 0 },
}
Referenced by decode_band_hdr().
ff_indeo4_decoder
AVCodec ff_indeo4_decoder
Initial value:
= {
    .name           = "indeo4",
    .long_name      = NULL_IF_CONFIG_SMALL("Intel Indeo Video Interactive 4"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_INDEO4,
    .priv_data_size = sizeof(IVI45DecContext),
    .init           = decode_init,
    .close          = ff_ivi_decode_close,
    .decode         = ff_ivi_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 686 of file indeo4.c.