FFmpeg: libavcodec/interplayvideo.c File Reference
interplayvideo.c File Reference
Interplay MVE Video Decoder by Mike Melanson (melan.nosp@m.son@.nosp@m.pcisy.nosp@m.s.ne.nosp@m.t) For more information about the Interplay MVE format, visit: http://www.pcisys.net/~melanson/codecs/interplay-mve.txt This code is written in such a way that the identifiers match up with the encoding descriptions in the document.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "libavutil/intreadwrite.h"
#include "avcodec.h"
#include "bytestream.h"
#include "get_bits.h"
#include "hpeldsp.h"
#include "internal.h"
Data Structures
struct IpvideoContext
Macros
#define BITSTREAM_READER_LE
#define PALETTE_COUNT 256
Functions
static int copy_from (IpvideoContext *s, AVFrame *src, AVFrame *dst, int delta_x, int delta_y)
static int ipvideo_decode_block_opcode_0x0 (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0x1 (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0x2 (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0x3 (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0x4 (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0x5 (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0x6 (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0x7 (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0x8 (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0x9 (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0xA (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0xB (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0xC (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0xD (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0xE (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0xF (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0x6_16 (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0x7_16 (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0x8_16 (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0x9_16 (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0xA_16 (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0xB_16 (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0xC_16 (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0xD_16 (IpvideoContext *s, AVFrame *frame)
static int ipvideo_decode_block_opcode_0xE_16 (IpvideoContext *s, AVFrame *frame)
static void ipvideo_decode_opcodes (IpvideoContext *s, AVFrame *frame)
static av_cold int ipvideo_decode_init (AVCodecContext *avctx)
static int ipvideo_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int ipvideo_decode_end (AVCodecContext *avctx)
Variables
static int(*const ipvideo_decode_block [])(IpvideoContext *s, AVFrame *frame)
static int(*const ipvideo_decode_block16 [])(IpvideoContext *s, AVFrame *frame)
AVCodec ff_interplay_video_decoder
Detailed Description
Interplay MVE Video Decoder by Mike Melanson (melan.nosp@m.son@.nosp@m.pcisy.nosp@m.s.ne.nosp@m.t) For more information about the Interplay MVE format, visit: http://www.pcisys.net/~melanson/codecs/interplay-mve.txt This code is written in such a way that the identifiers match up with the encoding descriptions in the document.
This decoder presently only supports a PAL8 output colorspace.
An Interplay video frame consists of 2 parts: The decoding map and the video data. A demuxer must load these 2 parts together in a single buffer before sending it through the stream to this decoder.
Definition in file interplayvideo.c.
Macro Definition Documentation
BITSTREAM_READER_LE
#define BITSTREAM_READER_LE
Definition at line 43 of file interplayvideo.c.
PALETTE_COUNT
#define PALETTE_COUNT 256
Definition at line 50 of file interplayvideo.c.
Function Documentation
copy_from()
static int copy_from (IpvideoContext * s, AVFrame * src, AVFrame * dst, int delta_x, int delta_y) static
Definition at line 71 of file interplayvideo.c.
Referenced by decode_frame(), ipvideo_decode_block_opcode_0x0(), ipvideo_decode_block_opcode_0x1(), ipvideo_decode_block_opcode_0x2(), ipvideo_decode_block_opcode_0x3(), ipvideo_decode_block_opcode_0x4(), ipvideo_decode_block_opcode_0x5(), and ipvideo_decode_block_opcode_0x6_16().
ipvideo_decode_block_opcode_0x0()
static int ipvideo_decode_block_opcode_0x0 (IpvideoContext * s, AVFrame * frame) static
Definition at line 93 of file interplayvideo.c.
ipvideo_decode_block_opcode_0x1()
static int ipvideo_decode_block_opcode_0x1 (IpvideoContext * s, AVFrame * frame) static
Definition at line 98 of file interplayvideo.c.
ipvideo_decode_block_opcode_0x2()
static int ipvideo_decode_block_opcode_0x2 (IpvideoContext * s, AVFrame * frame) static
Definition at line 103 of file interplayvideo.c.
ipvideo_decode_block_opcode_0x3()
static int ipvideo_decode_block_opcode_0x3 (IpvideoContext * s, AVFrame * frame) static
Definition at line 127 of file interplayvideo.c.
ipvideo_decode_block_opcode_0x4()
static int ipvideo_decode_block_opcode_0x4 (IpvideoContext * s, AVFrame * frame) static
Definition at line 153 of file interplayvideo.c.
ipvideo_decode_block_opcode_0x5()
static int ipvideo_decode_block_opcode_0x5 (IpvideoContext * s, AVFrame * frame) static
Definition at line 174 of file interplayvideo.c.
ipvideo_decode_block_opcode_0x6()
static int ipvideo_decode_block_opcode_0x6 (IpvideoContext * s, AVFrame * frame) static
Definition at line 187 of file interplayvideo.c.
ipvideo_decode_block_opcode_0x7()
static int ipvideo_decode_block_opcode_0x7 (IpvideoContext * s, AVFrame * frame) static
Definition at line 196 of file interplayvideo.c.
ipvideo_decode_block_opcode_0x8()
static int ipvideo_decode_block_opcode_0x8 (IpvideoContext * s, AVFrame * frame) static
Definition at line 240 of file interplayvideo.c.
ipvideo_decode_block_opcode_0x9()
static int ipvideo_decode_block_opcode_0x9 (IpvideoContext * s, AVFrame * frame) static
Definition at line 318 of file interplayvideo.c.
ipvideo_decode_block_opcode_0xA()
static int ipvideo_decode_block_opcode_0xA (IpvideoContext * s, AVFrame * frame) static
Definition at line 388 of file interplayvideo.c.
ipvideo_decode_block_opcode_0xB()
static int ipvideo_decode_block_opcode_0xB (IpvideoContext * s, AVFrame * frame) static
Definition at line 454 of file interplayvideo.c.
ipvideo_decode_block_opcode_0xC()
static int ipvideo_decode_block_opcode_0xC (IpvideoContext * s, AVFrame * frame) static
Definition at line 468 of file interplayvideo.c.
ipvideo_decode_block_opcode_0xD()
static int ipvideo_decode_block_opcode_0xD (IpvideoContext * s, AVFrame * frame) static
Definition at line 487 of file interplayvideo.c.
ipvideo_decode_block_opcode_0xE()
static int ipvideo_decode_block_opcode_0xE (IpvideoContext * s, AVFrame * frame) static
Definition at line 512 of file interplayvideo.c.
ipvideo_decode_block_opcode_0xF()
static int ipvideo_decode_block_opcode_0xF (IpvideoContext * s, AVFrame * frame) static
Definition at line 529 of file interplayvideo.c.
ipvideo_decode_block_opcode_0x6_16()
static int ipvideo_decode_block_opcode_0x6_16 (IpvideoContext * s, AVFrame * frame) static
Definition at line 550 of file interplayvideo.c.
ipvideo_decode_block_opcode_0x7_16()
static int ipvideo_decode_block_opcode_0x7_16 (IpvideoContext * s, AVFrame * frame) static
Definition at line 562 of file interplayvideo.c.
ipvideo_decode_block_opcode_0x8_16()
static int ipvideo_decode_block_opcode_0x8_16 (IpvideoContext * s, AVFrame * frame) static
Definition at line 599 of file interplayvideo.c.
ipvideo_decode_block_opcode_0x9_16()
static int ipvideo_decode_block_opcode_0x9_16 (IpvideoContext * s, AVFrame * frame) static
Definition at line 675 of file interplayvideo.c.
ipvideo_decode_block_opcode_0xA_16()
static int ipvideo_decode_block_opcode_0xA_16 (IpvideoContext * s, AVFrame * frame) static
Definition at line 742 of file interplayvideo.c.
ipvideo_decode_block_opcode_0xB_16()
static int ipvideo_decode_block_opcode_0xB_16 (IpvideoContext * s, AVFrame * frame) static
Definition at line 808 of file interplayvideo.c.
ipvideo_decode_block_opcode_0xC_16()
static int ipvideo_decode_block_opcode_0xC_16 (IpvideoContext * s, AVFrame * frame) static
Definition at line 824 of file interplayvideo.c.
ipvideo_decode_block_opcode_0xD_16()
static int ipvideo_decode_block_opcode_0xD_16 (IpvideoContext * s, AVFrame * frame) static
Definition at line 844 of file interplayvideo.c.
ipvideo_decode_block_opcode_0xE_16()
static int ipvideo_decode_block_opcode_0xE_16 (IpvideoContext * s, AVFrame * frame) static
Definition at line 865 of file interplayvideo.c.
ipvideo_decode_opcodes()
static void ipvideo_decode_opcodes (IpvideoContext * s, AVFrame * frame) static
Definition at line 906 of file interplayvideo.c.
Referenced by ipvideo_decode_frame().
ipvideo_decode_init()
static av_cold int ipvideo_decode_init (AVCodecContext * avctx) static
Definition at line 960 of file interplayvideo.c.
ipvideo_decode_frame()
static int ipvideo_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 982 of file interplayvideo.c.
ipvideo_decode_end()
static av_cold int ipvideo_decode_end (AVCodecContext * avctx) static
Definition at line 1040 of file interplayvideo.c.
Variable Documentation
ipvideo_decode_block
int(* const ipvideo_decode_block[])(IpvideoContext *s, AVFrame *frame) static
Initial value:
= {
    ipvideo_decode_block_opcode_0x0, ipvideo_decode_block_opcode_0x1,
    ipvideo_decode_block_opcode_0x2, ipvideo_decode_block_opcode_0x3,
    ipvideo_decode_block_opcode_0x4, ipvideo_decode_block_opcode_0x5,
    ipvideo_decode_block_opcode_0x6, ipvideo_decode_block_opcode_0x7,
    ipvideo_decode_block_opcode_0x8, ipvideo_decode_block_opcode_0x9,
    ipvideo_decode_block_opcode_0xA, ipvideo_decode_block_opcode_0xB,
    ipvideo_decode_block_opcode_0xC, ipvideo_decode_block_opcode_0xD,
    ipvideo_decode_block_opcode_0xE, ipvideo_decode_block_opcode_0xF,
}
Definition at line 884 of file interplayvideo.c.
Referenced by ipvideo_decode_opcodes().
ipvideo_decode_block16
int(* const ipvideo_decode_block16[])(IpvideoContext *s, AVFrame *frame) static
Initial value:
= {
    ipvideo_decode_block_opcode_0x0,    ipvideo_decode_block_opcode_0x1,
    ipvideo_decode_block_opcode_0x2,    ipvideo_decode_block_opcode_0x3,
    ipvideo_decode_block_opcode_0x4,    ipvideo_decode_block_opcode_0x5,
    ipvideo_decode_block_opcode_0x6_16, ipvideo_decode_block_opcode_0x7_16,
    ipvideo_decode_block_opcode_0x8_16, ipvideo_decode_block_opcode_0x9_16,
    ipvideo_decode_block_opcode_0xA_16, ipvideo_decode_block_opcode_0xB_16,
    ipvideo_decode_block_opcode_0xC_16, ipvideo_decode_block_opcode_0xD_16,
    ipvideo_decode_block_opcode_0xE_16, ipvideo_decode_block_opcode_0x1,
}
Definition at line 895 of file interplayvideo.c.
Referenced by ipvideo_decode_opcodes().
ff_interplay_video_decoder
AVCodec ff_interplay_video_decoder
Initial value:
= {
    .name           = "interplayvideo",
    .long_name      = NULL_IF_CONFIG_SMALL("Interplay MVE video"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_INTERPLAY_VIDEO,
    .priv_data_size = sizeof(IpvideoContext),
    .init           = ipvideo_decode_init,
    .close          = ipvideo_decode_end,
    .decode         = ipvideo_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_PARAM_CHANGE,
}
Definition at line 1050 of file interplayvideo.c.