FFmpeg: libavutil/intfloat.h File Reference
intfloat.h File Reference
#include <stdint.h>
#include "attributes.h"
Data Structures
union av_intfloat32
union av_intfloat64
Functions
static av_always_inline float av_int2float (uint32_t i)
Reinterpret a 32-bit integer as a float.
static av_always_inline uint32_t av_float2int (float f)
Reinterpret a float as a 32-bit integer.
static av_always_inline double av_int2double (uint64_t i)
Reinterpret a 64-bit integer as a double.
static av_always_inline uint64_t av_double2int (double f)
Reinterpret a double as a 64-bit integer.
Function Documentation
av_int2float()
static av_always_inline float av_int2float (uint32_t i) static
Reinterpret a 32-bit integer as a float.
Definition at line 40 of file intfloat.h.
Referenced by cine_read_header(), decode_block(), decode_frame(), decode_header(), ebml_read_float(), ff_exp2fi(), ff_mss12_decode_init(), fourxm_read_header(), ircam_read_header(), main(), mov_read_udta_string(), read_header(), thp_probe(), and thp_read_header().
av_float2int()
static av_always_inline uint32_t av_float2int (float f) static
Reinterpret a float as a 32-bit integer.
Definition at line 50 of file intfloat.h.
Referenced by avpriv_isfinitef(), avpriv_isinff(), avpriv_isnanf(), and decode_coeffs().
av_int2double()
static av_always_inline double av_int2double (uint64_t i) static
Reinterpret a 64-bit integer as a double.
Definition at line 60 of file intfloat.h.
Referenced by amf_parse_object(), amf_tag_contents(), copysign(), ebml_read_float(), ff_amf_get_field_value(), ff_amf_read_number(), get_f64l(), get_tag(), hypot(), mov_parse_stsd_audio(), nuv_header(), oledate_to_iso8601(), parse_keyframes_index(), read_desc_chunk(), and sox_read_header().
av_double2int()
static av_always_inline uint64_t av_double2int (double f) static
Reinterpret a double as a 64-bit integer.
Definition at line 70 of file intfloat.h.
Referenced by aiff_write_header(), avpriv_isfinite(), avpriv_isinf(), avpriv_isnan(), caf_write_header(), copysign(), ff_amf_write_number(), gxf_write_umf_media_audio(), inject_fake_duration_metadata(), mov_write_audio_tag(), put_amf_double(), put_ebml_float(), and sox_write_header().