FFmpeg: libavcodec/intrax8.h File Reference
intrax8.h File Reference
#include "blockdsp.h"
#include "get_bits.h"
#include "idctdsp.h"
#include "intrax8dsp.h"
#include "wmv2dsp.h"
#include "mpegpicture.h"
Data Structures
struct IntraX8Context
Functions
int ff_intrax8_common_init (AVCodecContext *avctx, IntraX8Context *w, IDCTDSPContext *idsp, int16_t(*block)[64], int block_last_index[12], int mb_width, int mb_height)
Initialize IntraX8 frame decoder.
void ff_intrax8_common_end (IntraX8Context *w)
Destroy IntraX8 frame structure.
int ff_intrax8_decode_picture (IntraX8Context *w, Picture *pict, GetBitContext *gb, int *mb_x, int *mb_y, int quant, int halfpq, int loopfilter, int lowdelay)
Decode single IntraX8 frame.
Function Documentation
ff_intrax8_common_init()
int ff_intrax8_common_init (AVCodecContext * avctx, IntraX8Context * w, IDCTDSPContext * idsp, int16_t(*) block[64], int block_last_index[12], int mb_width, int mb_height)
Initialize IntraX8 frame decoder.
Parameters
avctx pointer to AVCodecContext
w pointer to IntraX8Context
idsp pointer to IDCTDSPContext
block pointer to block array
block_last_index pointer to index array
mb_width macroblock width
mb_height macroblock height
Returns
0 on success, a negative AVERROR value on error
Definition at line 728 of file intrax8.c.
Referenced by ff_vc1_decode_init_alloc_tables(), and wmv2_decode_init().
ff_intrax8_common_end()
void ff_intrax8_common_end (IntraX8Context * w)
Destroy IntraX8 frame structure.
Parameters
w pointer to IntraX8Context
Definition at line 768 of file intrax8.c.
Referenced by ff_vc1_decode_end(), and wmv2_decode_end().
ff_intrax8_decode_picture()
int ff_intrax8_decode_picture (IntraX8Context * w, Picture * pict, GetBitContext * gb, int * mb_x, int * mb_y, int quant, int halfpq, int loopfilter, int lowdelay)
Decode single IntraX8 frame.
lowres decoding is theoretically impossible.
Parameters
w pointer to IntraX8Context
pict the output Picture containing an AVFrame
gb open bitstream reader
mb_x pointer to the x coordinate of the current macroblock
mb_y pointer to the y coordinate of the current macroblock
dquant doubled quantizer, it would be odd in case of VC-1 halfpq==1.
quant_offset offset away from zero
loopfilter enable filter after decoding a block
Definition at line 773 of file intrax8.c.
Referenced by ff_vc1_decode_blocks(), and ff_wmv2_decode_secondary_picture_header().