FFmpeg: libavcodec/ituh263dec.c File Reference
ituh263dec.c File Reference
H.263 decoder.
#include <limits.h>
#include "libavutil/attributes.h"
#include "libavutil/imgutils.h"
#include "libavutil/internal.h"
#include "libavutil/mathematics.h"
#include "avcodec.h"
#include "mpegvideo.h"
#include "h263.h"
#include "h263data.h"
#include "internal.h"
#include "mathops.h"
#include "mpegutils.h"
#include "unary.h"
#include "flv.h"
#include "rv10.h"
#include "mpeg4video.h"
#include "mpegvideodata.h"
Macros
#define UNCHECKED_BITSTREAM_READER 1
#define MV_VLC_BITS 9
#define H263_MBTYPE_B_VLC_BITS 6
#define CBPC_B_VLC_BITS 3
Functions
void ff_h263_show_pict_info (MpegEncContext *s)
Print picture info if FF_DEBUG_PICT_INFO is set.
av_cold void ff_h263_decode_init_vlc (void)
int ff_h263_decode_mba (MpegEncContext *s)
static int h263_decode_gob_header (MpegEncContext *s)
Decode the group of blocks header or slice header.
int ff_h263_resync (MpegEncContext *s)
Decode the group of blocks / video packet header.
int ff_h263_decode_motion (MpegEncContext *s, int pred, int f_code)
static int h263p_decode_umotion (MpegEncContext *s, int pred)
static void preview_obmc (MpegEncContext *s)
read the next MVs for OBMC.
static void h263_decode_dquant (MpegEncContext *s)
static int h263_decode_block (MpegEncContext *s, int16_t *block, int n, int coded)
static int h263_skip_b_part (MpegEncContext *s, int cbp)
static int h263_get_modb (GetBitContext *gb, int pb_frame, int *cbpb)
int ff_h263_decode_mb (MpegEncContext *s, int16_t block[6][64])
int ff_h263_decode_picture_header (MpegEncContext *s)
Variables
static const int h263_mb_type_b_map [15]
VLC ff_h263_intra_MCBPC_vlc
VLC ff_h263_inter_MCBPC_vlc
VLC ff_h263_cbpy_vlc
static VLC mv_vlc
static VLC h263_mbtype_b_vlc
static VLC cbpc_b_vlc
Detailed Description
H.263 decoder.
Definition in file ituh263dec.c.
Macro Definition Documentation
UNCHECKED_BITSTREAM_READER
#define UNCHECKED_BITSTREAM_READER 1
Definition at line 30 of file ituh263dec.c.
MV_VLC_BITS
#define MV_VLC_BITS 9
Definition at line 54 of file ituh263dec.c.
Referenced by ff_h263_decode_init_vlc(), ff_h263_decode_motion(), ff_mpeg12_init_vlcs(), and mpeg_decode_motion().
H263_MBTYPE_B_VLC_BITS
#define H263_MBTYPE_B_VLC_BITS 6
Definition at line 55 of file ituh263dec.c.
Referenced by ff_h263_decode_init_vlc(), and ff_h263_decode_mb().
CBPC_B_VLC_BITS
#define CBPC_B_VLC_BITS 3
Definition at line 56 of file ituh263dec.c.
Referenced by ff_h263_decode_init_vlc(), and ff_h263_decode_mb().
Function Documentation
ff_h263_show_pict_info()
void ff_h263_show_pict_info (MpegEncContext * s)
Print picture info if FF_DEBUG_PICT_INFO is set.
Definition at line 76 of file ituh263dec.c.
Referenced by ff_h263_decode_picture_header(), and ff_intel_h263_decode_picture_header().
ff_h263_decode_init_vlc()
av_cold void ff_h263_decode_init_vlc (void)
Definition at line 108 of file ituh263dec.c.
Referenced by ff_h263_decode_init(), and rv10_decode_init().
ff_h263_decode_mba()
int ff_h263_decode_mba (MpegEncContext * s)
Definition at line 139 of file ituh263dec.c.
Referenced by ff_h263_decode_picture_header(), h263_decode_gob_header(), and rv20_decode_picture_header().
h263_decode_gob_header()
static int h263_decode_gob_header (MpegEncContext * s) static
Decode the group of blocks header or slice header.
Returns
<0 if an error occurred
Definition at line 157 of file ituh263dec.c.
Referenced by ff_h263_resync().
ff_h263_resync()
int ff_h263_resync (MpegEncContext * s)
Decode the group of blocks / video packet header.
Returns
bit position of the resync_marker, or <0 if none was found
Definition at line 213 of file ituh263dec.c.
Referenced by ff_h263_decode_frame().
ff_h263_decode_motion()
int ff_h263_decode_motion (MpegEncContext * s, int pred, int f_code)
Definition at line 255 of file ituh263dec.c.
Referenced by ff_h263_decode_mb(), mpeg4_decode_mb(), mpeg4_decode_partition_a(), and preview_obmc().
h263p_decode_umotion()
static int h263p_decode_umotion (MpegEncContext * s, int pred) static
Definition at line 293 of file ituh263dec.c.
Referenced by ff_h263_decode_mb(), and preview_obmc().
preview_obmc()
static void preview_obmc (MpegEncContext * s) static
read the next MVs for OBMC.
yes this is an ugly hack, feel free to send a patch :)
Definition at line 319 of file ituh263dec.c.
Referenced by ff_h263_decode_mb().
h263_decode_dquant()
static void h263_decode_dquant (MpegEncContext * s) static
Definition at line 411 of file ituh263dec.c.
Referenced by ff_h263_decode_mb().
h263_decode_block()
static int h263_decode_block (MpegEncContext * s, int16_t * block, int n, int coded) static
Definition at line 424 of file ituh263dec.c.
Referenced by ff_h263_decode_mb(), and h263_skip_b_part().
h263_skip_b_part()
static int h263_skip_b_part (MpegEncContext * s, int cbp) static
Definition at line 571 of file ituh263dec.c.
Referenced by ff_h263_decode_mb().
h263_get_modb()
static int h263_get_modb (GetBitContext * gb, int pb_frame, int * cbpb) static
Definition at line 593 of file ituh263dec.c.
Referenced by ff_h263_decode_mb().
ff_h263_decode_mb()
int ff_h263_decode_mb (MpegEncContext * s, int16_t block[6][64])
Definition at line 611 of file ituh263dec.c.
Referenced by ff_h263_decode_init(), and rv10_decode_packet().
ff_h263_decode_picture_header()
int ff_h263_decode_picture_header (MpegEncContext * s)
Definition at line 877 of file ituh263dec.c.
Referenced by ff_h263_decode_frame().
Variable Documentation
h263_mb_type_b_map
const int h263_mb_type_b_map[15] static
Initial value:
= {
    MB_TYPE_DIRECT2 | MB_TYPE_L0L1,
    MB_TYPE_DIRECT2 | MB_TYPE_L0L1 | MB_TYPE_CBP,
    MB_TYPE_DIRECT2 | MB_TYPE_L0L1 | MB_TYPE_CBP | MB_TYPE_QUANT,
                      MB_TYPE_L0                                 | MB_TYPE_16x16,
                      MB_TYPE_L0   | MB_TYPE_CBP                 | MB_TYPE_16x16,
                      MB_TYPE_L0   | MB_TYPE_CBP | MB_TYPE_QUANT | MB_TYPE_16x16,
                      MB_TYPE_L1                                 | MB_TYPE_16x16,
                      MB_TYPE_L1   | MB_TYPE_CBP                 | MB_TYPE_16x16,
                      MB_TYPE_L1   | MB_TYPE_CBP | MB_TYPE_QUANT | MB_TYPE_16x16,
                      MB_TYPE_L0L1                               | MB_TYPE_16x16,
                      MB_TYPE_L0L1 | MB_TYPE_CBP                 | MB_TYPE_16x16,
                      MB_TYPE_L0L1 | MB_TYPE_CBP | MB_TYPE_QUANT | MB_TYPE_16x16,
    0,
    MB_TYPE_INTRA4x4                | MB_TYPE_CBP,
    MB_TYPE_INTRA4x4                | MB_TYPE_CBP | MB_TYPE_QUANT,
}
Definition at line 58 of file ituh263dec.c.
Referenced by ff_h263_decode_mb().
ff_h263_intra_MCBPC_vlc
VLC ff_h263_intra_MCBPC_vlc
Definition at line 98 of file ituh263dec.c.
Referenced by mpeg4_decode_mb(), mpeg4_decode_partition_a(), and msmpeg4v12_decode_mb().
ff_h263_inter_MCBPC_vlc
VLC ff_h263_inter_MCBPC_vlc
Definition at line 99 of file ituh263dec.c.
Referenced by mpeg4_decode_mb(), mpeg4_decode_partition_a(), and msmpeg4v12_decode_mb().
ff_h263_cbpy_vlc
VLC ff_h263_cbpy_vlc
Definition at line 100 of file ituh263dec.c.
Referenced by mpeg4_decode_mb(), mpeg4_decode_partition_b(), and msmpeg4v12_decode_mb().
mv_vlc
VLC mv_vlc static
Definition at line 101 of file ituh263dec.c.
h263_mbtype_b_vlc
VLC h263_mbtype_b_vlc static
Definition at line 102 of file ituh263dec.c.
cbpc_b_vlc
VLC cbpc_b_vlc static
Definition at line 103 of file ituh263dec.c.