FFmpeg: libavcodec/j2kenc.c File Reference
j2kenc.c File Reference
JPEG2000 image encoder.
#include <float.h>
#include "avcodec.h"
#include "internal.h"
#include "bytestream.h"
#include "jpeg2000.h"
#include "libavutil/common.h"
#include "libavutil/opt.h"
Data Structures
struct Jpeg2000Tile
struct Jpeg2000EncoderContext
Macros
#define NMSEDEC_BITS 7
#define NMSEDEC_FRACBITS (NMSEDEC_BITS-1)
#define WMSEDEC_SHIFT 13
must be >= 13
#define LAMBDA_SCALE (100000000LL << (WMSEDEC_SHIFT - 13))
#define CODEC_JP2 1
#define CODEC_J2K 0
#define OFFSET(x) offsetof(Jpeg2000EncoderContext, x)
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Functions
static void put_bits (Jpeg2000EncoderContext *s, int val, int n)
put n times val bit
static void put_num (Jpeg2000EncoderContext *s, int num, int n)
put n least significant bits of a number num
static void j2k_flush (Jpeg2000EncoderContext *s)
flush the bitstream
static void tag_tree_code (Jpeg2000EncoderContext *s, Jpeg2000TgtNode *node, int threshold)
code the value stored in node
static void tag_tree_update (Jpeg2000TgtNode *node)
update the value in node
static int put_siz (Jpeg2000EncoderContext *s)
static int put_cod (Jpeg2000EncoderContext *s)
static int put_qcd (Jpeg2000EncoderContext *s, int compno)
static int put_com (Jpeg2000EncoderContext *s, int compno)
static uint8_t * put_sot (Jpeg2000EncoderContext *s, int tileno)
static int init_tiles (Jpeg2000EncoderContext *s)
compute the sizes of tiles, resolution levels, bands, etc.
static void copy_frame (Jpeg2000EncoderContext *s)
static void init_quantization (Jpeg2000EncoderContext *s)
static void init_luts (void)
static int getnmsedec_sig (int x, int bpno)
static int getnmsedec_ref (int x, int bpno)
static void encode_sigpass (Jpeg2000T1Context *t1, int width, int height, int bandno, int *nmsedec, int bpno)
static void encode_refpass (Jpeg2000T1Context *t1, int width, int height, int *nmsedec, int bpno)
static void encode_clnpass (Jpeg2000T1Context *t1, int width, int height, int bandno, int *nmsedec, int bpno)
static void encode_cblk (Jpeg2000EncoderContext *s, Jpeg2000T1Context *t1, Jpeg2000Cblk *cblk, Jpeg2000Tile *tile, int width, int height, int bandpos, int lev)
static void putnumpasses (Jpeg2000EncoderContext *s, int n)
static int encode_packet (Jpeg2000EncoderContext *s, Jpeg2000ResLevel *rlevel, int precno, uint8_t *expn, int numgbits)
static int encode_packets (Jpeg2000EncoderContext *s, Jpeg2000Tile *tile, int tileno)
static int getcut (Jpeg2000Cblk *cblk, int64_t lambda, int dwt_norm)
static void truncpasses (Jpeg2000EncoderContext *s, Jpeg2000Tile *tile)
static int encode_tile (Jpeg2000EncoderContext *s, Jpeg2000Tile *tile, int tileno)
static void cleanup (Jpeg2000EncoderContext *s)
static void reinit (Jpeg2000EncoderContext *s)
static void update_size (uint8_t *size, const uint8_t *end)
static int encode_frame (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *pict, int *got_packet)
static av_cold int j2kenc_init (AVCodecContext *avctx)
static int j2kenc_destroy (AVCodecContext *avctx)
Variables
static int lut_nmsedec_ref [1<< NMSEDEC_BITS]
static int lut_nmsedec_ref0 [1<< NMSEDEC_BITS]
static int lut_nmsedec_sig [1<< NMSEDEC_BITS]
static int lut_nmsedec_sig0 [1<< NMSEDEC_BITS]
static const int dwt_norms [2][4][10]
static const AVOption options []
static const AVClass j2k_class
AVCodec ff_jpeg2000_encoder
Detailed Description
JPEG2000 image encoder.
Author
Kamil Nowosad
Definition in file j2kenc.c.
Macro Definition Documentation
NMSEDEC_BITS
#define NMSEDEC_BITS 7
Definition at line 74 of file j2kenc.c.
Referenced by getnmsedec_ref(), getnmsedec_sig(), and init_luts().
NMSEDEC_FRACBITS
#define NMSEDEC_FRACBITS (NMSEDEC_BITS-1)
Definition at line 75 of file j2kenc.c.
Referenced by encode_cblk(), encode_clnpass(), encode_refpass(), encode_sigpass(), encode_tile(), getnmsedec_ref(), getnmsedec_sig(), and init_luts().
WMSEDEC_SHIFT
#define WMSEDEC_SHIFT 13
must be >= 13
Definition at line 76 of file j2kenc.c.
Referenced by getcut().
LAMBDA_SCALE
#define LAMBDA_SCALE (100000000LL << (WMSEDEC_SHIFT - 13))
Definition at line 77 of file j2kenc.c.
Referenced by encode_frame().
CODEC_JP2
#define CODEC_JP2 1
Definition at line 79 of file j2kenc.c.
Referenced by encode_frame(), and libopenjpeg_decode_frame().
CODEC_J2K
#define CODEC_J2K 0
Definition at line 80 of file j2kenc.c.
Referenced by libopenjpeg_decode_frame().
OFFSET
#define OFFSET (x) offsetof(Jpeg2000EncoderContext, x)
Definition at line 1180 of file j2kenc.c.
VE
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 1181 of file j2kenc.c.
Function Documentation
put_bits()
static void put_bits (Jpeg2000EncoderContext * s, int val, int n) static
put n times val bit
Definition at line 206 of file j2kenc.c.
Referenced by aac_adtstoasc_filter(), aac_encode_frame(), ac3_output_frame_header(), adpcm_encode_frame(), adts_decode_extradata(), adts_write_frame_header(), asv1_encode_block(), asv1_put_level(), asv2_encode_block(), asv2_put_bits(), asv2_put_level(), avpriv_align_put_bits(), avpriv_copy_bits(), avpriv_dca_convert_bitstream(), avpriv_put_string(), bit_copy(), codebook_trellis_rate(), copy_bits(), dnxhd_encode_block(), dnxhd_encode_dc(), dnxhd_encode_thread(), dv_encode_ac(), dv_encode_video_segment(), encode_422_bitstream(), encode_ac_coeffs(), encode_aspect_ratio(), encode_bitstream(), encode_block(), encode_clean_area(), encode_codeword(), encode_color_spec(), encode_dc(), encode_exp_vlc(), encode_ext_header(), encode_flush(), encode_frame(), encode_frame_rate(), encode_frame_size(), encode_hq_slice(), encode_individual_channel(), encode_line(), encode_mb_skip_run(), encode_ms_info(), encode_packet(), encode_parse_info(), encode_picture_ls(), encode_pulses(), encode_quant_matrix(), encode_sample_fmt(), encode_scalar(), encode_scale_factors(), encode_scan_format(), encode_signal_range(), encode_subband(), encode_superframe(), encode_vlc_codeword(), encode_window_bands_info(), ff_aac_encode_ltp_info(), ff_aac_encode_main_pred(), ff_aac_encode_tns_info(), ff_eac3_output_frame_header(), ff_flv2_encode_ac_esc(), ff_flv_encode_picture_header(), ff_h261_encode_mb(), ff_h261_encode_picture_header(), ff_h263_encode_gob_header(), ff_h263_encode_mb(), ff_h263_encode_mba(), ff_h263_encode_motion(), ff_h263_encode_picture_header(), ff_hevc_encode_nal_vps(), ff_mjpeg_encode_dc(), ff_mjpeg_encode_picture_header(), ff_mjpeg_escape_FF(), ff_mjpeg_find_marker(), ff_mpeg1_encode_picture_header(), ff_mpeg1_encode_slice_header(), ff_mpeg4_encode_mb(), ff_mpeg4_encode_picture_header(), ff_mpeg4_encode_video_packet_header(), ff_mpeg4_merge_partitions(), ff_mpeg4_stuffing(), ff_mpv_encode_picture(), ff_msmpeg4_code012(), ff_msmpeg4_encode_block(), ff_msmpeg4_encode_ext_header(), ff_msmpeg4_encode_mb(), ff_msmpeg4_encode_motion(), ff_msmpeg4_encode_picture_header(), ff_rv10_encode_picture_header(), ff_rv20_encode_picture_header(), ff_wmv2_encode_mb(), ff_wmv2_encode_picture_header(), ff_write_quant_matrix(), floor_encode(), flv_write_codec_header(), g726_reset(), gif_image_write_image(), h261_encode_block(), h261_encode_gob_header(), h261_encode_motion(), h263_encode_block(), h263p_encode_umotion(), intlist_read(), jpeg_put_comments(), jpeg_table_header(), latm_write_frame_header(), latm_write_packet(), ls_encode_run(), ls_store_lse(), main(), mov_write_ac3_tag(), mov_write_dvc1_structs(), mov_write_eac3_tag(), mpeg1_encode_block(), mpeg1_encode_mb_internal(), mpeg1_encode_motion(), mpeg1_encode_sequence_header(), mpeg4_encode_block(), mpeg4_encode_dc(), mpeg4_encode_gop_header(), mpeg4_encode_visual_object_header(), mpeg4_encode_vol_header(), msmpeg4_encode_dc(), msmpeg4v2_encode_motion(), output_audio_block(), pack_bitstream(), pack_float_sample(), pnm_decode_frame(), predictor_calc_error(), put_alpha_diff(), put_alpha_run(), put_audio_specific_config(), put_bitstream_info(), put_cabac_bit(), put_cabac_terminate(), put_codebook_header(), put_codeword(), put_floor_header(), put_frame_header(), put_header(), put_huffman_table(), put_ics_info(), put_main_header(), put_marker(), put_mb_modes(), put_num(), put_pack_header(), put_primary_audio_header(), put_qscale(), put_residue_header(), put_subframe(), put_subframe_samples(), put_swf_line_edge(), put_swf_matrix(), put_swf_rect(), put_system_header(), put_vc2_ue_uint(), put_xsub_rle(), quantize_and_encode_band_cost_template(), ra144_encode_frame(), ra144_encode_subblock(), read_packet(), s302m_encode2_frame(), save_bits(), send_mode_a(), send_mode_b(), set_te_golomb(), set_ue_golomb(), set_ur_golomb(), set_ur_golomb_jpegls(), svq1_encode_frame(), svq1_encode_plane(), svq1_write_header(), swf_write_header(), tag_tree_code(), tta_encode_frame(), vaapi_encode_mjpeg_write_image_header(), vaapi_encode_mjpeg_write_marker(), vorbis_encode_frame(), wavpack_encode_sample(), write_block_data(), write_decoding_params(), write_element(), write_element_header(), write_filter_params(), write_frame(), write_frame_footer(), write_frame_header(), write_header(), write_huff_codes(), write_major_sync(), write_matrix_params(), write_ptl(), write_ptl_layer(), write_restart_header(), write_streaminfo(), write_subframes(), write_substrs(), and write_utf8().
put_num()
static void put_num (Jpeg2000EncoderContext * s, int num, int n) static
put n least significant bits of a number num
Definition at line 219 of file j2kenc.c.
Referenced by encode_packet(), and putnumpasses().
j2k_flush()
static void j2k_flush (Jpeg2000EncoderContext * s) static
flush the bitstream
Definition at line 226 of file j2kenc.c.
Referenced by encode_packet().
tag_tree_code()
static void tag_tree_code (Jpeg2000EncoderContext * s, Jpeg2000TgtNode * node, int threshold) static
code the value stored in node
Definition at line 237 of file j2kenc.c.
Referenced by encode_packet().
tag_tree_update()
static void tag_tree_update (Jpeg2000TgtNode * node) static
update the value in node
Definition at line 265 of file j2kenc.c.
Referenced by encode_packet().
put_siz()
static int put_siz (Jpeg2000EncoderContext * s) static
Definition at line 277 of file j2kenc.c.
Referenced by encode_frame().
put_cod()
static int put_cod (Jpeg2000EncoderContext * s) static
Definition at line 306 of file j2kenc.c.
Referenced by encode_frame().
put_qcd()
static int put_qcd (Jpeg2000EncoderContext * s, int compno) static
Definition at line 333 of file j2kenc.c.
Referenced by encode_frame().
put_com()
static int put_com (Jpeg2000EncoderContext * s, int compno) static
Definition at line 359 of file j2kenc.c.
Referenced by encode_frame().
put_sot()
static uint8_t* put_sot (Jpeg2000EncoderContext * s, int tileno) static
Definition at line 378 of file j2kenc.c.
Referenced by encode_frame().
init_tiles()
static int init_tiles (Jpeg2000EncoderContext * s) static
compute the sizes of tiles, resolution levels, bands, etc.
allocate memory for them divide the input image into tile-components
Definition at line 402 of file j2kenc.c.
Referenced by j2kenc_init().
copy_frame()
static void copy_frame (Jpeg2000EncoderContext * s) static
Definition at line 448 of file j2kenc.c.
Referenced by encode_frame().
init_quantization()
static void init_quantization (Jpeg2000EncoderContext * s) static
Definition at line 486 of file j2kenc.c.
Referenced by j2kenc_init().
init_luts()
static void init_luts (void) static
Definition at line 516 of file j2kenc.c.
Referenced by j2kenc_init().
getnmsedec_sig()
static int getnmsedec_sig (int x, int bpno) static
Definition at line 534 of file j2kenc.c.
Referenced by encode_clnpass(), and encode_sigpass().
getnmsedec_ref()
static int getnmsedec_ref (int x, int bpno) static
Definition at line 541 of file j2kenc.c.
Referenced by encode_refpass().
encode_sigpass()
static void encode_sigpass (Jpeg2000T1Context * t1, int width, int height, int bandno, int * nmsedec, int bpno) static
Definition at line 548 of file j2kenc.c.
Referenced by encode_cblk().
encode_refpass()
static void encode_refpass (Jpeg2000T1Context * t1, int width, int height, int * nmsedec, int bpno) static
Definition at line 570 of file j2kenc.c.
Referenced by encode_cblk().
encode_clnpass()
static void encode_clnpass (Jpeg2000T1Context * t1, int width, int height, int bandno, int * nmsedec, int bpno) static
Definition at line 584 of file j2kenc.c.
Referenced by encode_cblk().
encode_cblk()
static void encode_cblk (Jpeg2000EncoderContext * s, Jpeg2000T1Context * t1, Jpeg2000Cblk * cblk, Jpeg2000Tile * tile, int width, int height, int bandpos, int lev) static
Definition at line 639 of file j2kenc.c.
Referenced by encode_tile().
putnumpasses()
static void putnumpasses (Jpeg2000EncoderContext * s, int n) static
Definition at line 696 of file j2kenc.c.
Referenced by encode_packet().
encode_packet()
static int encode_packet (Jpeg2000EncoderContext * s, Jpeg2000ResLevel * rlevel, int precno, uint8_t * expn, int numgbits) static
Definition at line 711 of file j2kenc.c.
Referenced by encode_packets().
encode_packets()
static int encode_packets (Jpeg2000EncoderContext * s, Jpeg2000Tile * tile, int tileno) static
Definition at line 809 of file j2kenc.c.
Referenced by encode_tile().
getcut()
static int getcut (Jpeg2000Cblk * cblk, int64_t lambda, int dwt_norm) static
Definition at line 832 of file j2kenc.c.
Referenced by truncpasses().
truncpasses()
static void truncpasses (Jpeg2000EncoderContext * s, Jpeg2000Tile * tile) static
Definition at line 850 of file j2kenc.c.
Referenced by encode_tile().
encode_tile()
static int encode_tile (Jpeg2000EncoderContext * s, Jpeg2000Tile * tile, int tileno) static
Definition at line 879 of file j2kenc.c.
Referenced by encode_frame().
cleanup()
static void cleanup (Jpeg2000EncoderContext * s) static
Definition at line 960 of file j2kenc.c.
Referenced by j2kenc_destroy().
reinit()
static void reinit (Jpeg2000EncoderContext * s) static
Definition at line 975 of file j2kenc.c.
Referenced by encode_frame().
update_size()
static void update_size (uint8_t * size, const uint8_t * end) static
Definition at line 985 of file j2kenc.c.
Referenced by encode_frame().
encode_frame()
static int encode_frame (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * pict, int * got_packet) static
Definition at line 990 of file j2kenc.c.
j2kenc_init()
static av_cold int j2kenc_init (AVCodecContext * avctx) static
Definition at line 1101 of file j2kenc.c.
j2kenc_destroy()
static int j2kenc_destroy (AVCodecContext * avctx) static
Definition at line 1170 of file j2kenc.c.
Variable Documentation
lut_nmsedec_ref
int lut_nmsedec_ref[1<< NMSEDEC_BITS] static
Definition at line 82 of file j2kenc.c.
Referenced by getnmsedec_ref(), and init_luts().
lut_nmsedec_ref0
int lut_nmsedec_ref0[1<< NMSEDEC_BITS] static
Definition at line 82 of file j2kenc.c.
Referenced by getnmsedec_ref(), and init_luts().
lut_nmsedec_sig
int lut_nmsedec_sig[1<< NMSEDEC_BITS] static
Definition at line 82 of file j2kenc.c.
Referenced by getnmsedec_sig(), and init_luts().
lut_nmsedec_sig0
int lut_nmsedec_sig0[1<< NMSEDEC_BITS] static
Definition at line 82 of file j2kenc.c.
Referenced by getnmsedec_sig(), and init_luts().
dwt_norms
const int dwt_norms[2][4][10] static
Initial value:
= {
    {{10000, 19650, 41770,  84030, 169000, 338400,  676900, 1353000, 2706000, 5409000},
     {20220, 39890, 83550, 170400, 342700, 686300, 1373000, 2746000, 5490000},
     {20220, 39890, 83550, 170400, 342700, 686300, 1373000, 2746000, 5490000},
     {20800, 38650, 83070, 171800, 347100, 695900, 1393000, 2786000, 5572000}},
    {{10000, 15000, 27500, 53750, 106800, 213400, 426700, 853300, 1707000, 3413000},
     {10380, 15920, 29190, 57030, 113300, 226400, 452500, 904800, 1809000},
     {10380, 15920, 29190, 57030, 113300, 226400, 452500, 904800, 1809000},
     { 7186,  9218, 15860, 30430,  60190, 120100, 240000, 479700,  959300}}
}
Definition at line 87 of file j2kenc.c.
Referenced by init_quantization(), and truncpasses().
options
const AVOption options[] static
Initial value:
= {
    { "format",        "Codec Format",      OFFSET(format),        AV_OPT_TYPE_INT,   { .i64 = CODEC_JP2   }, CODEC_J2K, CODEC_JP2,   VE, "format"      },
    { "j2k",           NULL,                0,                     AV_OPT_TYPE_CONST, { .i64 = CODEC_J2K   }, 0,         0,           VE, "format"      },
    { "jp2",           NULL,                0,                     AV_OPT_TYPE_CONST, { .i64 = CODEC_JP2   }, 0,         0,           VE, "format"      },
    { "tile_width",    "Tile Width",        OFFSET(tile_width),    AV_OPT_TYPE_INT,   { .i64 = 256         }, 1,     1<<30,           VE, },
    { "tile_height",   "Tile Height",       OFFSET(tile_height),   AV_OPT_TYPE_INT,   { .i64 = 256         }, 1,     1<<30,           VE, },
    { "pred",          "DWT Type",          OFFSET(pred),          AV_OPT_TYPE_INT,   { .i64 = 0           }, 0,         1,           VE, "pred"        },
    { "dwt97int",      NULL,                0,                     AV_OPT_TYPE_CONST, { .i64 = 0           }, INT_MIN, INT_MAX,       VE, "pred"        },
    { "dwt53",         NULL,                0,                     AV_OPT_TYPE_CONST, { .i64 = 0           }, INT_MIN, INT_MAX,       VE, "pred"        },
    { NULL }
}
Definition at line 1182 of file j2kenc.c.
j2k_class
const AVClass j2k_class static
Initial value:
= {
    .class_name = "jpeg 2000 encoder",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1195 of file j2kenc.c.
ff_jpeg2000_encoder
AVCodec ff_jpeg2000_encoder
Initial value:
= {
    .name           = "jpeg2000",
    .long_name      = NULL_IF_CONFIG_SMALL("JPEG 2000"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_JPEG2000,
    .priv_data_size = sizeof(Jpeg2000EncoderContext),
    .init           = j2kenc_init,
    .encode2        = encode_frame,
    .close          = j2kenc_destroy,
    .pix_fmts       = (const enum AVPixelFormat[]) {
        AV_PIX_FMT_RGB24, AV_PIX_FMT_YUV444P, AV_PIX_FMT_GRAY8,
        AV_PIX_FMT_YUV420P, AV_PIX_FMT_YUV422P,
        AV_PIX_FMT_YUV410P, AV_PIX_FMT_YUV411P,
        AV_PIX_FMT_NONE
    },
    .priv_class     = &j2k_class,
}
Definition at line 1202 of file j2kenc.c.