FFmpeg: libavdevice/jack.c File Reference
jack.c File Reference
#include "config.h"
#include <semaphore.h>
#include <jack/jack.h>
#include "libavutil/internal.h"
#include "libavutil/log.h"
#include "libavutil/fifo.h"
#include "libavutil/opt.h"
#include "libavutil/time.h"
#include "libavcodec/avcodec.h"
#include "libavformat/avformat.h"
#include "libavformat/internal.h"
#include "timefilter.h"
#include "avdevice.h"
Data Structures
struct JackData
Macros
#define FIFO_PACKETS_NUM 16
Size of the internal FIFO buffers as a number of audio packets.
#define OFFSET(x) offsetof(JackData, x)
Functions
static int process_callback (jack_nframes_t nframes, void *arg)
static void shutdown_callback (void *arg)
static int xrun_callback (void *arg)
static int supply_new_packets (JackData *self, AVFormatContext *context)
static int start_jack (AVFormatContext *context)
static void free_pkt_fifo (AVFifoBuffer **fifo)
static void stop_jack (JackData *self)
static int audio_read_header (AVFormatContext *context)
static int audio_read_packet (AVFormatContext *context, AVPacket *pkt)
static int audio_read_close (AVFormatContext *context)
Variables
static const AVOption options []
static const AVClass jack_indev_class
AVInputFormat ff_jack_demuxer
Macro Definition Documentation
FIFO_PACKETS_NUM
#define FIFO_PACKETS_NUM 16
Size of the internal FIFO buffers as a number of audio packets.
Definition at line 41 of file jack.c.
Referenced by start_jack().
OFFSET
#define OFFSET (x) offsetof(JackData, x)
Definition at line 335 of file jack.c.
Function Documentation
process_callback()
static int process_callback (jack_nframes_t nframes, void * arg) static
Definition at line 59 of file jack.c.
Referenced by start_jack().
shutdown_callback()
static void shutdown_callback (void * arg) static
Definition at line 119 of file jack.c.
Referenced by start_jack().
xrun_callback()
static int xrun_callback (void * arg) static
Definition at line 125 of file jack.c.
Referenced by start_jack().
supply_new_packets()
static int supply_new_packets (JackData * self, AVFormatContext * context) static
Definition at line 133 of file jack.c.
Referenced by audio_read_packet(), and start_jack().
start_jack()
static int start_jack (AVFormatContext * context) static
Definition at line 151 of file jack.c.
Referenced by audio_read_header().
free_pkt_fifo()
static void free_pkt_fifo (AVFifoBuffer ** fifo) static
Definition at line 216 of file jack.c.
Referenced by stop_jack().
stop_jack()
static void stop_jack (JackData * self) static
Definition at line 226 of file jack.c.
Referenced by audio_read_close(), and audio_read_header().
audio_read_header()
static int audio_read_header (AVFormatContext * context) static
Definition at line 240 of file jack.c.
audio_read_packet()
static int audio_read_packet (AVFormatContext * context, AVPacket * pkt) static
Definition at line 268 of file jack.c.
audio_read_close()
static int audio_read_close (AVFormatContext * context) static
Definition at line 328 of file jack.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "channels", "Number of audio channels.", OFFSET(nports), AV_OPT_TYPE_INT, { .i64 = 2 }, 1, INT_MAX, AV_OPT_FLAG_DECODING_PARAM },
    { NULL },
}
Definition at line 336 of file jack.c.
jack_indev_class
const AVClass jack_indev_class static
Initial value:
= {
    .class_name     = "JACK indev",
    .item_name      = av_default_item_name,
    .option         = options,
    .version        = LIBAVUTIL_VERSION_INT,
    .category       = AV_CLASS_CATEGORY_DEVICE_AUDIO_INPUT,
}
Definition at line 341 of file jack.c.
ff_jack_demuxer
AVInputFormat ff_jack_demuxer
Initial value:
= {
    .name           = "jack",
    .long_name      = NULL_IF_CONFIG_SMALL("JACK Audio Connection Kit"),
    .priv_data_size = sizeof(JackData),
    .read_header    = audio_read_header,
    .read_packet    = audio_read_packet,
    .read_close     = audio_read_close,
    .flags          = AVFMT_NOFILE,
    .priv_class     = &jack_indev_class,
}
Definition at line 349 of file jack.c.