FFmpeg: libavcodec/jacosub.h File Reference
jacosub.h File Reference
JACOsub shared utils.
#include "libavutil/common.h"
Macros
#define JSS_MAX_LINESIZE 512
Functions
static av_always_inline int jss_whitespace (char c)
static av_always_inline const char * jss_skip_whitespace (const char *p)
Detailed Description
JACOsub shared utils.
Definition in file jacosub.h.
Macro Definition Documentation
JSS_MAX_LINESIZE
#define JSS_MAX_LINESIZE 512
Definition at line 31 of file jacosub.h.
Referenced by jacosub_decode_frame(), and jacosub_read_header().
Function Documentation
jss_whitespace()
static av_always_inline int jss_whitespace (char c) static
Definition at line 33 of file jacosub.h.
Referenced by jacosub_probe(), jacosub_to_ass(), and jss_skip_whitespace().
jss_skip_whitespace()
static av_always_inline const char* jss_skip_whitespace (const char * p) static
Definition at line 38 of file jacosub.h.
Referenced by jacosub_decode_frame(), jacosub_read_header(), and jacosub_to_ass().