FFmpeg: libavcodec/x86/jpeg2000dsp_init.c File Reference
jpeg2000dsp_init.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/x86/cpu.h"
#include "libavcodec/jpeg2000dsp.h"
Functions
void ff_ict_float_sse (void *src0, void *src1, void *src2, int csize)
void ff_ict_float_avx (void *src0, void *src1, void *src2, int csize)
void ff_rct_int_sse2 (void *src0, void *src1, void *src2, int csize)
void ff_rct_int_avx2 (void *src0, void *src1, void *src2, int csize)
av_cold void ff_jpeg2000dsp_init_x86 (Jpeg2000DSPContext *c)
Function Documentation
ff_ict_float_sse()
void ff_ict_float_sse (void * src0, void * src1, void * src2, int csize)
Referenced by ff_jpeg2000dsp_init_x86().
ff_ict_float_avx()
void ff_ict_float_avx (void * src0, void * src1, void * src2, int csize)
Referenced by ff_jpeg2000dsp_init_x86().
ff_rct_int_sse2()
void ff_rct_int_sse2 (void * src0, void * src1, void * src2, int csize)
Referenced by ff_jpeg2000dsp_init_x86().
ff_rct_int_avx2()
void ff_rct_int_avx2 (void * src0, void * src1, void * src2, int csize)
Referenced by ff_jpeg2000dsp_init_x86().
ff_jpeg2000dsp_init_x86()
av_cold void ff_jpeg2000dsp_init_x86 (Jpeg2000DSPContext * c)
Definition at line 32 of file jpeg2000dsp_init.c.
Referenced by ff_jpeg2000dsp_init().