FFmpeg: libavcodec/jpeg2000dec.c File Reference
jpeg2000dec.c File Reference
JPEG 2000 image decoder.
#include <inttypes.h>
#include "libavutil/attributes.h"
#include "libavutil/avassert.h"
#include "libavutil/common.h"
#include "libavutil/imgutils.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
#include "thread.h"
#include "jpeg2000.h"
#include "jpeg2000dsp.h"
#include "profiles.h"
Data Structures
struct Jpeg2000POCEntry
struct Jpeg2000POC
struct Jpeg2000TilePart
struct Jpeg2000Tile
struct Jpeg2000DecoderContext
Macros
#define JP2_SIG_TYPE 0x6A502020
#define JP2_SIG_VALUE 0x0D0A870A
#define JP2_CODESTREAM 0x6A703263
#define JP2_HEADER 0x6A703268
#define HAD_COC 0x01
#define HAD_QCC 0x02
#define MAX_POCS 32
#define RGB_PIXEL_FORMATS AV_PIX_FMT_PAL8,AV_PIX_FMT_RGB24,AV_PIX_FMT_RGBA,AV_PIX_FMT_RGB48,AV_PIX_FMT_RGBA64
#define GRAY_PIXEL_FORMATS AV_PIX_FMT_GRAY8,AV_PIX_FMT_GRAY8A,AV_PIX_FMT_GRAY16,AV_PIX_FMT_YA16
#define YUV_PIXEL_FORMATS
#define XYZ_PIXEL_FORMATS AV_PIX_FMT_XYZ12
#define WRITE_FRAME(D, PIXEL)
#define OFFSET(x) offsetof(Jpeg2000DecoderContext, x)
#define VD AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_DECODING_PARAM
Functions
static int get_bits (Jpeg2000DecoderContext *s, int n)
static void jpeg2000_flush (Jpeg2000DecoderContext *s)
static int tag_tree_decode (Jpeg2000DecoderContext *s, Jpeg2000TgtNode *node, int threshold)
static int pix_fmt_match (enum AVPixelFormat pix_fmt, int components, int bpc, uint32_t log2_chroma_wh, int pal8)
static int get_siz (Jpeg2000DecoderContext *s)
static int get_cox (Jpeg2000DecoderContext *s, Jpeg2000CodingStyle *c)
static int get_cod (Jpeg2000DecoderContext *s, Jpeg2000CodingStyle *c, uint8_t *properties)
static int get_coc (Jpeg2000DecoderContext *s, Jpeg2000CodingStyle *c, uint8_t *properties)
static int get_qcx (Jpeg2000DecoderContext *s, int n, Jpeg2000QuantStyle *q)
static int get_qcd (Jpeg2000DecoderContext *s, int n, Jpeg2000QuantStyle *q, uint8_t *properties)
static int get_qcc (Jpeg2000DecoderContext *s, int n, Jpeg2000QuantStyle *q, uint8_t *properties)
static int get_poc (Jpeg2000DecoderContext *s, int size, Jpeg2000POC *p)
static int get_sot (Jpeg2000DecoderContext *s, int n)
static uint8_t get_tlm (Jpeg2000DecoderContext *s, int n)
static uint8_t get_plt (Jpeg2000DecoderContext *s, int n)
static int init_tile (Jpeg2000DecoderContext *s, int tileno)
static int getnpasses (Jpeg2000DecoderContext *s)
static int getlblockinc (Jpeg2000DecoderContext *s)
static int jpeg2000_decode_packet (Jpeg2000DecoderContext *s, Jpeg2000Tile *tile, int *tp_index, Jpeg2000CodingStyle *codsty, Jpeg2000ResLevel *rlevel, int precno, int layno, uint8_t *expn, int numgbits)
static int jpeg2000_decode_packets_po_iteration (Jpeg2000DecoderContext *s, Jpeg2000Tile *tile, int RSpoc, int CSpoc, int LYEpoc, int REpoc, int CEpoc, int Ppoc, int *tp_index)
static int jpeg2000_decode_packets (Jpeg2000DecoderContext *s, Jpeg2000Tile *tile)
static void decode_sigpass (Jpeg2000T1Context *t1, int width, int height, int bpno, int bandno, int vert_causal_ctx_csty_symbol)
static void decode_refpass (Jpeg2000T1Context *t1, int width, int height, int bpno, int vert_causal_ctx_csty_symbol)
static void decode_clnpass (Jpeg2000DecoderContext *s, Jpeg2000T1Context *t1, int width, int height, int bpno, int bandno, int seg_symbols, int vert_causal_ctx_csty_symbol)
static int decode_cblk (Jpeg2000DecoderContext *s, Jpeg2000CodingStyle *codsty, Jpeg2000T1Context *t1, Jpeg2000Cblk *cblk, int width, int height, int bandpos)
static void dequantization_float (int x, int y, Jpeg2000Cblk *cblk, Jpeg2000Component *comp, Jpeg2000T1Context *t1, Jpeg2000Band *band)
static void dequantization_int (int x, int y, Jpeg2000Cblk *cblk, Jpeg2000Component *comp, Jpeg2000T1Context *t1, Jpeg2000Band *band)
static void dequantization_int_97 (int x, int y, Jpeg2000Cblk *cblk, Jpeg2000Component *comp, Jpeg2000T1Context *t1, Jpeg2000Band *band)
static void mct_decode (Jpeg2000DecoderContext *s, Jpeg2000Tile *tile)
static void tile_codeblocks (Jpeg2000DecoderContext *s, Jpeg2000Tile *tile)
static int jpeg2000_decode_tile (AVCodecContext *avctx, void *td, int jobnr, int threadnr)
static void jpeg2000_dec_cleanup (Jpeg2000DecoderContext *s)
static int jpeg2000_read_main_headers (Jpeg2000DecoderContext *s)
static int jpeg2000_read_bitstream_packets (Jpeg2000DecoderContext *s)
static int jp2_find_codestream (Jpeg2000DecoderContext *s)
static av_cold int jpeg2000_decode_init (AVCodecContext *avctx)
static int jpeg2000_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold void jpeg2000_init_static_data (AVCodec *codec)
Variables
static enum AVPixelFormat rgb_pix_fmts [] = {RGB_PIXEL_FORMATS}
static enum AVPixelFormat gray_pix_fmts [] = {GRAY_PIXEL_FORMATS}
static enum AVPixelFormat yuv_pix_fmts [] = {YUV_PIXEL_FORMATS}
static enum AVPixelFormat xyz_pix_fmts []
static enum AVPixelFormat all_pix_fmts []
static const AVOption options []
static const AVClass jpeg2000_class
AVCodec ff_jpeg2000_decoder
Detailed Description
JPEG 2000 image decoder.
Definition in file jpeg2000dec.c.
Macro Definition Documentation
JP2_SIG_TYPE
#define JP2_SIG_TYPE 0x6A502020
Definition at line 44 of file jpeg2000dec.c.
Referenced by jpeg2000_decode_frame().
JP2_SIG_VALUE
#define JP2_SIG_VALUE 0x0D0A870A
Definition at line 45 of file jpeg2000dec.c.
Referenced by jpeg2000_decode_frame().
JP2_CODESTREAM
#define JP2_CODESTREAM 0x6A703263
Definition at line 46 of file jpeg2000dec.c.
Referenced by jp2_find_codestream().
JP2_HEADER
#define JP2_HEADER 0x6A703268
Definition at line 47 of file jpeg2000dec.c.
Referenced by jp2_find_codestream().
HAD_COC
#define HAD_COC 0x01
Definition at line 49 of file jpeg2000dec.c.
Referenced by get_coc(), and get_cod().
HAD_QCC
#define HAD_QCC 0x02
Definition at line 50 of file jpeg2000dec.c.
Referenced by get_qcc(), and get_qcd().
MAX_POCS
#define MAX_POCS 32
Definition at line 52 of file jpeg2000dec.c.
Referenced by get_poc().
RGB_PIXEL_FORMATS
#define RGB_PIXEL_FORMATS AV_PIX_FMT_PAL8,AV_PIX_FMT_RGB24,AV_PIX_FMT_RGBA,AV_PIX_FMT_RGB48,AV_PIX_FMT_RGBA64
Definition at line 229 of file jpeg2000dec.c.
GRAY_PIXEL_FORMATS
#define GRAY_PIXEL_FORMATS AV_PIX_FMT_GRAY8,AV_PIX_FMT_GRAY8A,AV_PIX_FMT_GRAY16,AV_PIX_FMT_YA16
Definition at line 230 of file jpeg2000dec.c.
YUV_PIXEL_FORMATS
#define YUV_PIXEL_FORMATS
Value:
AV_PIX_FMT_YUV410P,AV_PIX_FMT_YUV411P,AV_PIX_FMT_YUVA420P, \
                            AV_PIX_FMT_YUV420P,AV_PIX_FMT_YUV422P,AV_PIX_FMT_YUVA422P, \
                            AV_PIX_FMT_YUV440P,AV_PIX_FMT_YUV444P,AV_PIX_FMT_YUVA444P, \
                            AV_PIX_FMT_YUV420P9,AV_PIX_FMT_YUV422P9,AV_PIX_FMT_YUV444P9, \
                            AV_PIX_FMT_YUVA420P9,AV_PIX_FMT_YUVA422P9,AV_PIX_FMT_YUVA444P9, \
                            AV_PIX_FMT_YUV420P10,AV_PIX_FMT_YUV422P10,AV_PIX_FMT_YUV444P10, \
                            AV_PIX_FMT_YUVA420P10,AV_PIX_FMT_YUVA422P10,AV_PIX_FMT_YUVA444P10, \
                            AV_PIX_FMT_YUV420P12,AV_PIX_FMT_YUV422P12,AV_PIX_FMT_YUV444P12, \
                            AV_PIX_FMT_YUV420P14,AV_PIX_FMT_YUV422P14,AV_PIX_FMT_YUV444P14, \
                            AV_PIX_FMT_YUV420P16,AV_PIX_FMT_YUV422P16,AV_PIX_FMT_YUV444P16, \
                            AV_PIX_FMT_YUVA420P16,AV_PIX_FMT_YUVA422P16,AV_PIX_FMT_YUVA444P16
Definition at line 231 of file jpeg2000dec.c.
XYZ_PIXEL_FORMATS
#define XYZ_PIXEL_FORMATS AV_PIX_FMT_XYZ12
Definition at line 242 of file jpeg2000dec.c.
WRITE_FRAME
#define WRITE_FRAME (D, PIXEL)
Definition at line 1696 of file jpeg2000dec.c.
OFFSET
#define OFFSET (x) offsetof(Jpeg2000DecoderContext, x)
Definition at line 2142 of file jpeg2000dec.c.
VD
#define VD AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_DECODING_PARAM
Definition at line 2143 of file jpeg2000dec.c.
Function Documentation
get_bits()
static int get_bits (Jpeg2000DecoderContext * s, int n) static
Definition at line 129 of file jpeg2000dec.c.
Referenced by getlblockinc(), getnpasses(), jpeg2000_decode_packet(), and tag_tree_decode().
jpeg2000_flush()
static void jpeg2000_flush (Jpeg2000DecoderContext * s) static
Definition at line 144 of file jpeg2000dec.c.
Referenced by jpeg2000_decode_packet().
tag_tree_decode()
static int tag_tree_decode (Jpeg2000DecoderContext * s, Jpeg2000TgtNode * node, int threshold) static
Definition at line 152 of file jpeg2000dec.c.
Referenced by jpeg2000_decode_packet().
pix_fmt_match()
static int pix_fmt_match (enum AVPixelFormat pix_fmt, int components, int bpc, uint32_t log2_chroma_wh, int pal8) static
Definition at line 192 of file jpeg2000dec.c.
Referenced by get_siz().
get_siz()
static int get_siz (Jpeg2000DecoderContext * s) static
Definition at line 256 of file jpeg2000dec.c.
Referenced by jpeg2000_read_main_headers().
get_cox()
static int get_cox (Jpeg2000DecoderContext * s, Jpeg2000CodingStyle * c) static
Definition at line 429 of file jpeg2000dec.c.
Referenced by get_coc(), and get_cod().
get_cod()
static int get_cod (Jpeg2000DecoderContext * s, Jpeg2000CodingStyle * c, uint8_t * properties) static
Definition at line 504 of file jpeg2000dec.c.
Referenced by jpeg2000_read_main_headers().
get_coc()
static int get_coc (Jpeg2000DecoderContext * s, Jpeg2000CodingStyle * c, uint8_t * properties) static
Definition at line 541 of file jpeg2000dec.c.
Referenced by jpeg2000_read_main_headers().
get_qcx()
static int get_qcx (Jpeg2000DecoderContext * s, int n, Jpeg2000QuantStyle * q) static
Definition at line 571 of file jpeg2000dec.c.
Referenced by get_qcc(), and get_qcd().
get_qcd()
static int get_qcd (Jpeg2000DecoderContext * s, int n, Jpeg2000QuantStyle * q, uint8_t * properties) static
Definition at line 616 of file jpeg2000dec.c.
Referenced by jpeg2000_read_main_headers().
get_qcc()
static int get_qcc (Jpeg2000DecoderContext * s, int n, Jpeg2000QuantStyle * q, uint8_t * properties) static
Definition at line 634 of file jpeg2000dec.c.
Referenced by jpeg2000_read_main_headers().
get_poc()
static int get_poc (Jpeg2000DecoderContext * s, int size, Jpeg2000POC * p) static
Definition at line 655 of file jpeg2000dec.c.
Referenced by jpeg2000_read_main_headers().
get_sot()
static int get_sot (Jpeg2000DecoderContext * s, int n) static
Definition at line 717 of file jpeg2000dec.c.
Referenced by jpeg2000_read_main_headers().
get_tlm()
static uint8_t get_tlm (Jpeg2000DecoderContext * s, int n) static
Definition at line 775 of file jpeg2000dec.c.
Referenced by jpeg2000_read_main_headers().
get_plt()
static uint8_t get_plt (Jpeg2000DecoderContext * s, int n) static
Definition at line 809 of file jpeg2000dec.c.
Referenced by jpeg2000_read_main_headers().
init_tile()
static int init_tile (Jpeg2000DecoderContext * s, int tileno) static
Definition at line 825 of file jpeg2000dec.c.
Referenced by jpeg2000_read_bitstream_packets().
getnpasses()
static int getnpasses (Jpeg2000DecoderContext * s) static
Definition at line 871 of file jpeg2000dec.c.
Referenced by jpeg2000_decode_packet().
getlblockinc()
static int getlblockinc (Jpeg2000DecoderContext * s) static
Definition at line 886 of file jpeg2000dec.c.
Referenced by jpeg2000_decode_packet().
jpeg2000_decode_packet()
static int jpeg2000_decode_packet (Jpeg2000DecoderContext * s, Jpeg2000Tile * tile, int * tp_index, Jpeg2000CodingStyle * codsty, Jpeg2000ResLevel * rlevel, int precno, int layno, uint8_t * expn, int numgbits) static
Definition at line 897 of file jpeg2000dec.c.
Referenced by jpeg2000_decode_packets_po_iteration().
jpeg2000_decode_packets_po_iteration()
static int jpeg2000_decode_packets_po_iteration (Jpeg2000DecoderContext * s, Jpeg2000Tile * tile, int RSpoc, int CSpoc, int LYEpoc, int REpoc, int CEpoc, int Ppoc, int * tp_index) static
Definition at line 1042 of file jpeg2000dec.c.
Referenced by jpeg2000_decode_packets().
jpeg2000_decode_packets()
static int jpeg2000_decode_packets (Jpeg2000DecoderContext * s, Jpeg2000Tile * tile) static
Definition at line 1314 of file jpeg2000dec.c.
Referenced by jpeg2000_read_bitstream_packets().
decode_sigpass()
static void decode_sigpass (Jpeg2000T1Context * t1, int width, int height, int bpno, int bandno, int vert_causal_ctx_csty_symbol) static
Definition at line 1351 of file jpeg2000dec.c.
Referenced by decode_cblk().
decode_refpass()
static void decode_refpass (Jpeg2000T1Context * t1, int width, int height, int bpno, int vert_causal_ctx_csty_symbol) static
Definition at line 1381 of file jpeg2000dec.c.
Referenced by decode_cblk().
decode_clnpass()
static void decode_clnpass (Jpeg2000DecoderContext * s, Jpeg2000T1Context * t1, int width, int height, int bpno, int bandno, int seg_symbols, int vert_causal_ctx_csty_symbol) static
Definition at line 1405 of file jpeg2000dec.c.
Referenced by decode_cblk().
decode_cblk()
static int decode_cblk (Jpeg2000DecoderContext * s, Jpeg2000CodingStyle * codsty, Jpeg2000T1Context * t1, Jpeg2000Cblk * cblk, int width, int height, int bandpos) static
Definition at line 1471 of file jpeg2000dec.c.
Referenced by tile_codeblocks().
dequantization_float()
static void dequantization_float (int x, int y, Jpeg2000Cblk * cblk, Jpeg2000Component * comp, Jpeg2000T1Context * t1, Jpeg2000Band * band) static
Definition at line 1556 of file jpeg2000dec.c.
Referenced by tile_codeblocks().
dequantization_int()
static void dequantization_int (int x, int y, Jpeg2000Cblk * cblk, Jpeg2000Component * comp, Jpeg2000T1Context * t1, Jpeg2000Band * band) static
Definition at line 1571 of file jpeg2000dec.c.
Referenced by tile_codeblocks().
dequantization_int_97()
static void dequantization_int_97 (int x, int y, Jpeg2000Cblk * cblk, Jpeg2000Component * comp, Jpeg2000T1Context * t1, Jpeg2000Band * band) static
Definition at line 1591 of file jpeg2000dec.c.
Referenced by tile_codeblocks().
mct_decode()
static void mct_decode (Jpeg2000DecoderContext * s, Jpeg2000Tile * tile) inline static
Definition at line 1605 of file jpeg2000dec.c.
Referenced by jpeg2000_decode_tile().
tile_codeblocks()
static void tile_codeblocks (Jpeg2000DecoderContext * s, Jpeg2000Tile * tile) inline static
Definition at line 1633 of file jpeg2000dec.c.
Referenced by jpeg2000_decode_tile().
jpeg2000_decode_tile()
static int jpeg2000_decode_tile (AVCodecContext * avctx, void * td, int jobnr, int threadnr) static
Definition at line 1758 of file jpeg2000dec.c.
Referenced by jpeg2000_decode_frame().
jpeg2000_dec_cleanup()
static void jpeg2000_dec_cleanup (Jpeg2000DecoderContext * s) static
Definition at line 1797 of file jpeg2000dec.c.
Referenced by jpeg2000_decode_frame().
jpeg2000_read_main_headers()
static int jpeg2000_read_main_headers (Jpeg2000DecoderContext * s) static
Definition at line 1820 of file jpeg2000dec.c.
Referenced by jpeg2000_decode_frame().
jpeg2000_read_bitstream_packets()
static int jpeg2000_read_bitstream_packets (Jpeg2000DecoderContext * s) static
Definition at line 1939 of file jpeg2000dec.c.
Referenced by jpeg2000_decode_frame().
jp2_find_codestream()
static int jp2_find_codestream (Jpeg2000DecoderContext * s) static
Definition at line 1958 of file jpeg2000dec.c.
Referenced by jpeg2000_decode_frame().
jpeg2000_decode_init()
static av_cold int jpeg2000_decode_init (AVCodecContext * avctx) static
Definition at line 2058 of file jpeg2000dec.c.
jpeg2000_decode_frame()
static int jpeg2000_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 2067 of file jpeg2000dec.c.
jpeg2000_init_static_data()
static av_cold void jpeg2000_init_static_data (AVCodec * codec) static
Definition at line 2136 of file jpeg2000dec.c.
Variable Documentation
rgb_pix_fmts
enum AVPixelFormat rgb_pix_fmts[] = {RGB_PIXEL_FORMATS} static
Definition at line 244 of file jpeg2000dec.c.
Referenced by geq_query_formats(), and get_siz().
gray_pix_fmts
enum AVPixelFormat gray_pix_fmts[] = {GRAY_PIXEL_FORMATS} static
Definition at line 245 of file jpeg2000dec.c.
Referenced by get_siz().
yuv_pix_fmts
enum AVPixelFormat yuv_pix_fmts[] = {YUV_PIXEL_FORMATS} static
Definition at line 246 of file jpeg2000dec.c.
Referenced by geq_query_formats(), and get_siz().
xyz_pix_fmts
enum AVPixelFormat xyz_pix_fmts[] static
Initial value:
= {XYZ_PIXEL_FORMATS,
                                                   YUV_PIXEL_FORMATS}
Definition at line 247 of file jpeg2000dec.c.
Referenced by get_siz().
all_pix_fmts
enum AVPixelFormat all_pix_fmts[] static
Initial value:
= {RGB_PIXEL_FORMATS,
                                                   GRAY_PIXEL_FORMATS,
                                                   YUV_PIXEL_FORMATS,
                                                   XYZ_PIXEL_FORMATS}
Definition at line 249 of file jpeg2000dec.c.
Referenced by get_siz().
options
const AVOption options[] static
Initial value:
= {
    { "lowres",  "Lower the decoding resolution by a power of two",
        OFFSET(reduction_factor), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, JPEG2000_MAX_RESLEVELS - 1, VD },
    { NULL },
}
Definition at line 2145 of file jpeg2000dec.c.
jpeg2000_class
const AVClass jpeg2000_class static
Initial value:
= {
    .class_name = "jpeg2000",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 2151 of file jpeg2000dec.c.
ff_jpeg2000_decoder
AVCodec ff_jpeg2000_decoder
Initial value:
= {
    .name             = "jpeg2000",
    .long_name        = NULL_IF_CONFIG_SMALL("JPEG 2000"),
    .type             = AVMEDIA_TYPE_VIDEO,
    .id               = AV_CODEC_ID_JPEG2000,
    .capabilities     = AV_CODEC_CAP_SLICE_THREADS | AV_CODEC_CAP_FRAME_THREADS | AV_CODEC_CAP_DR1,
    .priv_data_size   = sizeof(Jpeg2000DecoderContext),
    .init_static_data = jpeg2000_init_static_data,
    .init             = jpeg2000_decode_init,
    .decode           = jpeg2000_decode_frame,
    .priv_class       = &jpeg2000_class,
    .max_lowres       = 5,
    .profiles         = NULL_IF_CONFIG_SMALL(ff_jpeg2000_profiles)
}
Definition at line 2158 of file jpeg2000dec.c.