FFmpeg: libavcodec/jpeglsdec.c File Reference
jpeglsdec.c File Reference
JPEG-LS decoder.
#include "avcodec.h"
#include "get_bits.h"
#include "golomb.h"
#include "internal.h"
#include "mathops.h"
#include "mjpeg.h"
#include "mjpegdec.h"
#include "jpegls.h"
#include "jpeglsdec.h"
Functions
int ff_jpegls_decode_lse (MJpegDecodeContext *s)
Decode LSE block with initialization parameters.
static int ls_get_code_regular (GetBitContext *gb, JLSState *state, int Q)
Get context-dependent Golomb code, decode it and update context.
static int ls_get_code_runterm (GetBitContext *gb, JLSState *state, int RItype, int limit_add)
Get Golomb code, decode it and update state for run termination.
static void ls_decode_line (JLSState *state, MJpegDecodeContext *s, void *last, void *dst, int last2, int w, int stride, int comp, int bits)
Decode one line of image.
int ff_jpegls_decode_picture (MJpegDecodeContext *s, int near, int point_transform, int ilv)
Variables
AVCodec ff_jpegls_decoder
Detailed Description
JPEG-LS decoder.
Definition in file jpeglsdec.c.
Function Documentation
ff_jpegls_decode_lse()
int ff_jpegls_decode_lse (MJpegDecodeContext * s)
Decode LSE block with initialization parameters.
Definition at line 51 of file jpeglsdec.c.
Referenced by ff_mjpeg_decode_frame().
ls_get_code_regular()
static int ls_get_code_regular (GetBitContext * gb, JLSState * state, int Q) inline static
Get context-dependent Golomb code, decode it and update context.
Definition at line 148 of file jpeglsdec.c.
Referenced by ls_decode_line().
ls_get_code_runterm()
static int ls_get_code_runterm (GetBitContext * gb, JLSState * state, int RItype, int limit_add) inline static
Get Golomb code, decode it and update state for run termination.
Definition at line 179 of file jpeglsdec.c.
Referenced by ls_decode_line().
ls_decode_line()
static void ls_decode_line (JLSState * state, MJpegDecodeContext * s, void * last, void * dst, int last2, int w, int stride, int comp, int bits) inline static
Decode one line of image.
Definition at line 225 of file jpeglsdec.c.
Referenced by ff_jpegls_decode_picture().
ff_jpegls_decode_picture()
int ff_jpegls_decode_picture (MJpegDecodeContext * s, int near, int point_transform, int ilv)
Definition at line 343 of file jpeglsdec.c.
Referenced by ff_mjpeg_decode_sos().
Variable Documentation
ff_jpegls_decoder
AVCodec ff_jpegls_decoder
Initial value:
= {
    .name           = "jpegls",
    .long_name      = NULL_IF_CONFIG_SMALL("JPEG-LS"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_JPEGLS,
    .priv_data_size = sizeof(MJpegDecodeContext),
    .init           = ff_mjpeg_decode_init,
    .close          = ff_mjpeg_decode_end,
    .decode         = ff_mjpeg_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
    .caps_internal  = FF_CODEC_CAP_INIT_THREADSAFE,
}
Definition at line 517 of file jpeglsdec.c.