FFmpeg: libavcodec/jpeg2000dwt.c File Reference
jpeg2000dwt.c File Reference
Discrete wavelet transform.
#include "libavutil/avassert.h"
#include "libavutil/common.h"
#include "libavutil/mem.h"
#include "jpeg2000dwt.h"
#include "internal.h"
Macros
#define F_LFTG_ALPHA 1.586134342059924f
#define F_LFTG_BETA 0.052980118572961f
#define F_LFTG_GAMMA 0.882911075530934f
#define F_LFTG_DELTA 0.443506852043971f
#define I_LFTG_ALPHA 103949ll
#define I_LFTG_BETA 3472ll
#define I_LFTG_GAMMA 57862ll
#define I_LFTG_DELTA 29066ll
#define I_LFTG_K 80621ll
#define I_LFTG_X 53274ll
#define I_PRESHIFT 8
Functions
static void extend53 (int *p, int i0, int i1)
static void extend97_float (float *p, int i0, int i1)
static void extend97_int (int32_t *p, int i0, int i1)
static void sd_1d53 (int *p, int i0, int i1)
static void dwt_encode53 (DWTContext *s, int *t)
static void sd_1d97_float (float *p, int i0, int i1)
static void dwt_encode97_float (DWTContext *s, float *t)
static void sd_1d97_int (int *p, int i0, int i1)
static void dwt_encode97_int (DWTContext *s, int *t)
static void sr_1d53 (int *p, int i0, int i1)
static void dwt_decode53 (DWTContext *s, int *t)
static void sr_1d97_float (float *p, int i0, int i1)
static void dwt_decode97_float (DWTContext *s, float *t)
static void sr_1d97_int (int32_t *p, int i0, int i1)
static void dwt_decode97_int (DWTContext *s, int32_t *t)
int ff_jpeg2000_dwt_init (DWTContext *s, int border[2][2], int decomp_levels, int type)
Initialize DWT.
int ff_dwt_encode (DWTContext *s, void *t)
int ff_dwt_decode (DWTContext *s, void *t)
void ff_dwt_destroy (DWTContext *s)
Detailed Description
Discrete wavelet transform.
Definition in file jpeg2000dwt.c.
Macro Definition Documentation
F_LFTG_ALPHA
#define F_LFTG_ALPHA 1.586134342059924f
Definition at line 36 of file jpeg2000dwt.c.
Referenced by sr_1d97_float().
F_LFTG_BETA
#define F_LFTG_BETA 0.052980118572961f
Definition at line 37 of file jpeg2000dwt.c.
Referenced by sr_1d97_float().
F_LFTG_GAMMA
#define F_LFTG_GAMMA 0.882911075530934f
Definition at line 38 of file jpeg2000dwt.c.
Referenced by sr_1d97_float().
F_LFTG_DELTA
#define F_LFTG_DELTA 0.443506852043971f
Definition at line 39 of file jpeg2000dwt.c.
Referenced by sr_1d97_float().
I_LFTG_ALPHA
#define I_LFTG_ALPHA 103949ll
Definition at line 43 of file jpeg2000dwt.c.
Referenced by sd_1d97_int(), and sr_1d97_int().
I_LFTG_BETA
#define I_LFTG_BETA 3472ll
Definition at line 44 of file jpeg2000dwt.c.
Referenced by sd_1d97_int(), and sr_1d97_int().
I_LFTG_GAMMA
#define I_LFTG_GAMMA 57862ll
Definition at line 45 of file jpeg2000dwt.c.
Referenced by sd_1d97_int(), and sr_1d97_int().
I_LFTG_DELTA
#define I_LFTG_DELTA 29066ll
Definition at line 46 of file jpeg2000dwt.c.
Referenced by sd_1d97_int(), and sr_1d97_int().
I_LFTG_K
#define I_LFTG_K 80621ll
Definition at line 47 of file jpeg2000dwt.c.
Referenced by dwt_decode97_int(), sd_1d97_int(), and sr_1d97_int().
I_LFTG_X
#define I_LFTG_X 53274ll
Definition at line 48 of file jpeg2000dwt.c.
Referenced by dwt_encode97_int(), sd_1d97_int(), and sr_1d97_int().
I_PRESHIFT
#define I_PRESHIFT 8
Definition at line 49 of file jpeg2000dwt.c.
Referenced by dwt_decode97_int(), and dwt_encode97_int().
Function Documentation
extend53()
static void extend53 (int * p, int i0, int i1) inline static
Definition at line 51 of file jpeg2000dwt.c.
Referenced by sd_1d53(), and sr_1d53().
extend97_float()
static void extend97_float (float * p, int i0, int i1) inline static
Definition at line 59 of file jpeg2000dwt.c.
Referenced by sd_1d97_float(), and sr_1d97_float().
extend97_int()
static void extend97_int (int32_t * p, int i0, int i1) inline static
Definition at line 69 of file jpeg2000dwt.c.
Referenced by sd_1d97_int(), and sr_1d97_int().
sd_1d53()
static void sd_1d53 (int * p, int i0, int i1) static
Definition at line 79 of file jpeg2000dwt.c.
Referenced by dwt_encode53().
dwt_encode53()
static void dwt_encode53 (DWTContext * s, int * t) static
Definition at line 97 of file jpeg2000dwt.c.
Referenced by ff_dwt_encode().
sd_1d97_float()
static void sd_1d97_float (float * p, int i0, int i1) static
Definition at line 147 of file jpeg2000dwt.c.
Referenced by dwt_encode97_float().
dwt_encode97_float()
static void dwt_encode97_float (DWTContext * s, float * t) static
Definition at line 172 of file jpeg2000dwt.c.
Referenced by ff_dwt_encode().
sd_1d97_int()
static void sd_1d97_int (int * p, int i0, int i1) static
Definition at line 223 of file jpeg2000dwt.c.
Referenced by dwt_encode97_int().
dwt_encode97_int()
static void dwt_encode97_int (DWTContext * s, int * t) static
Definition at line 248 of file jpeg2000dwt.c.
Referenced by ff_dwt_encode().
sr_1d53()
static void sr_1d53 (int * p, int i0, int i1) static
Definition at line 308 of file jpeg2000dwt.c.
Referenced by dwt_decode53().
dwt_decode53()
static void dwt_decode53 (DWTContext * s, int * t) static
Definition at line 326 of file jpeg2000dwt.c.
Referenced by ff_dwt_decode().
sr_1d97_float()
static void sr_1d97_float (float * p, int i0, int i1) static
Definition at line 375 of file jpeg2000dwt.c.
Referenced by dwt_decode97_float().
dwt_decode97_float()
static void dwt_decode97_float (DWTContext * s, float * t) static
Definition at line 402 of file jpeg2000dwt.c.
Referenced by ff_dwt_decode().
sr_1d97_int()
static void sr_1d97_int (int32_t * p, int i0, int i1) static
Definition at line 452 of file jpeg2000dwt.c.
Referenced by dwt_decode97_int().
dwt_decode97_int()
static void dwt_decode97_int (DWTContext * s, int32_t * t) static
Definition at line 479 of file jpeg2000dwt.c.
Referenced by ff_dwt_decode().
ff_jpeg2000_dwt_init()
int ff_jpeg2000_dwt_init (DWTContext * s, int border[2][2], int decomp_levels, int type)
Initialize DWT.
Parameters
s DWT context
border coordinates of transformed region {{x0, x1}, {y0, y1}}
decomp_levels number of decomposition levels
type 0 for DWT 9/7; 1 for DWT 5/3
Definition at line 537 of file jpeg2000dwt.c.
Referenced by ff_jpeg2000_init_component(), test_dwt(), and test_dwtf().
ff_dwt_encode()
int ff_dwt_encode (DWTContext * s, void * t)
Definition at line 581 of file jpeg2000dwt.c.
Referenced by encode_tile(), test_dwt(), and test_dwtf().
ff_dwt_decode()
int ff_dwt_decode (DWTContext * s, void * t)
Definition at line 599 of file jpeg2000dwt.c.
Referenced by test_dwt(), test_dwtf(), and tile_codeblocks().
ff_dwt_destroy()
void ff_dwt_destroy (DWTContext * s)
Definition at line 620 of file jpeg2000dwt.c.
Referenced by ff_jpeg2000_cleanup(), test_dwt(), and test_dwtf().