FFmpeg: libavcodec/jpeglsenc.c File Reference
jpeglsenc.c File Reference
JPEG-LS encoder.
#include "avcodec.h"
#include "get_bits.h"
#include "put_bits.h"
#include "golomb.h"
#include "internal.h"
#include "mathops.h"
#include "mjpeg.h"
#include "mjpegenc.h"
#include "jpegls.h"
Data Structures
struct JPEGLSContext
Macros
#define OFFSET(x) offsetof(JPEGLSContext, x)
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Functions
static void ls_encode_regular (JLSState *state, PutBitContext *pb, int Q, int err)
Encode error from regular symbol.
static void ls_encode_runterm (JLSState *state, PutBitContext *pb, int RItype, int err, int limit_add)
Encode error from run termination.
static void ls_encode_run (JLSState *state, PutBitContext *pb, int run, int comp, int trail)
Encode run value as specified by JPEG-LS standard.
static void ls_encode_line (JLSState *state, PutBitContext *pb, void *last, void *cur, int last2, int w, int stride, int comp, int bits)
Encode one line of image.
static void ls_store_lse (JLSState *state, PutBitContext *pb)
static int encode_picture_ls (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *pict, int *got_packet)
static av_cold int encode_init_ls (AVCodecContext *ctx)
Variables
static const AVOption options []
static const AVClass jpegls_class
AVCodec ff_jpegls_encoder
Detailed Description
JPEG-LS encoder.
Definition in file jpeglsenc.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(JPEGLSContext, x)
Definition at line 448 of file jpeglsenc.c.
VE
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 449 of file jpeglsenc.c.
Function Documentation
ls_encode_regular()
static void ls_encode_regular (JLSState * state, PutBitContext * pb, int Q, int err) inline static
Encode error from regular symbol.
Definition at line 47 of file jpeglsenc.c.
Referenced by ls_encode_line().
ls_encode_runterm()
static void ls_encode_runterm (JLSState * state, PutBitContext * pb, int RItype, int err, int limit_add) inline static
Encode error from run termination.
Definition at line 75 of file jpeglsenc.c.
Referenced by ls_encode_line().
ls_encode_run()
static void ls_encode_run (JLSState * state, PutBitContext * pb, int run, int comp, int trail) inline static
Encode run value as specified by JPEG-LS standard.
Definition at line 108 of file jpeglsenc.c.
Referenced by ls_encode_line().
ls_encode_line()
static void ls_encode_line (JLSState * state, PutBitContext * pb, void * last, void * cur, int last2, int w, int stride, int comp, int bits) inline static
Encode one line of image.
Definition at line 130 of file jpeglsenc.c.
Referenced by encode_picture_ls().
ls_store_lse()
static void ls_store_lse (JLSState * state, PutBitContext * pb) static
Definition at line 233 of file jpeglsenc.c.
Referenced by encode_picture_ls().
encode_picture_ls()
static int encode_picture_ls (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * pict, int * got_packet) static
Definition at line 256 of file jpeglsenc.c.
encode_init_ls()
static av_cold int encode_init_ls (AVCodecContext * ctx) static
Definition at line 428 of file jpeglsenc.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
{ "pred", "Prediction method", OFFSET(pred), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, 2, VE, "pred" },
    { "left",   NULL, 0, AV_OPT_TYPE_CONST, { .i64 = 0 }, INT_MIN, INT_MAX, VE, "pred" },
    { "plane",  NULL, 0, AV_OPT_TYPE_CONST, { .i64 = 1 }, INT_MIN, INT_MAX, VE, "pred" },
    { "median", NULL, 0, AV_OPT_TYPE_CONST, { .i64 = 2 }, INT_MIN, INT_MAX, VE, "pred" },
    { NULL},
}
Definition at line 450 of file jpeglsenc.c.
jpegls_class
const AVClass jpegls_class static
Initial value:
= {
    .class_name = "jpegls",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 459 of file jpeglsenc.c.
ff_jpegls_encoder
AVCodec ff_jpegls_encoder
Initial value:
= {
    .name           = "jpegls",
    .long_name      = NULL_IF_CONFIG_SMALL("JPEG-LS"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_JPEGLS,
    .priv_data_size = sizeof(JPEGLSContext),
    .priv_class     = &jpegls_class,
    .init           = encode_init_ls,
    .capabilities   = AV_CODEC_CAP_FRAME_THREADS | AV_CODEC_CAP_INTRA_ONLY,
    .encode2        = encode_picture_ls,
    .pix_fmts       = (const enum AVPixelFormat[]) {
        AV_PIX_FMT_BGR24, AV_PIX_FMT_RGB24,
        AV_PIX_FMT_GRAY8, AV_PIX_FMT_GRAY16,
        AV_PIX_FMT_NONE
    },
    .caps_internal  = FF_CODEC_CAP_INIT_THREADSAFE |
                      FF_CODEC_CAP_INIT_CLEANUP,
}
Definition at line 466 of file jpeglsenc.c.