FFmpeg: libavcodec/jpeg2000dwt.h File Reference
jpeg2000dwt.h File Reference
Discrete wavelet transform.
#include <stdint.h>
Data Structures
struct DWTContext
Macros
#define FF_DWT_MAX_DECLVLS 32
max number of decomposition levels
#define F_LFTG_K 1.230174104914001f
#define F_LFTG_X 0.812893066115961f
Enumerations
enum DWTType { FF_DWT97, FF_DWT53, FF_DWT97_INT, FF_DWT_NB }
Functions
int ff_jpeg2000_dwt_init (DWTContext *s, int border[2][2], int decomp_levels, int type)
Initialize DWT.
int ff_dwt_encode (DWTContext *s, void *t)
int ff_dwt_decode (DWTContext *s, void *t)
void ff_dwt_destroy (DWTContext *s)
Detailed Description
Discrete wavelet transform.
Definition in file jpeg2000dwt.h.
Macro Definition Documentation
FF_DWT_MAX_DECLVLS
#define FF_DWT_MAX_DECLVLS 32
max number of decomposition levels
Definition at line 32 of file jpeg2000dwt.h.
Referenced by main().
F_LFTG_K
#define F_LFTG_K 1.230174104914001f
Definition at line 33 of file jpeg2000dwt.h.
Referenced by init_band_stepsize(), sd_1d97_float(), and sr_1d97_float().
F_LFTG_X
#define F_LFTG_X 0.812893066115961f
Definition at line 34 of file jpeg2000dwt.h.
Referenced by init_band_stepsize(), sd_1d97_float(), and sr_1d97_float().
Enumeration Type Documentation
DWTType
enum DWTType
Enumerator
FF_DWT97
FF_DWT53
FF_DWT97_INT
FF_DWT_NB
Definition at line 36 of file jpeg2000dwt.h.
Function Documentation
ff_jpeg2000_dwt_init()
int ff_jpeg2000_dwt_init (DWTContext * s, int border[2][2], int decomp_levels, int type)
Initialize DWT.
Parameters
s DWT context
border coordinates of transformed region {{x0, x1}, {y0, y1}}
decomp_levels number of decomposition levels
type 0 for DWT 9/7; 1 for DWT 5/3
Definition at line 537 of file jpeg2000dwt.c.
Referenced by ff_jpeg2000_init_component(), test_dwt(), and test_dwtf().
ff_dwt_encode()
int ff_dwt_encode (DWTContext * s, void * t)
Definition at line 581 of file jpeg2000dwt.c.
Referenced by encode_tile(), test_dwt(), and test_dwtf().
ff_dwt_decode()
int ff_dwt_decode (DWTContext * s, void * t)
Definition at line 599 of file jpeg2000dwt.c.
Referenced by test_dwt(), test_dwtf(), and tile_codeblocks().
ff_dwt_destroy()
void ff_dwt_destroy (DWTContext * s)
Definition at line 620 of file jpeg2000dwt.c.
Referenced by ff_jpeg2000_cleanup(), test_dwt(), and test_dwtf().