FFmpeg: libavcodec/jpegls.h File Reference
jpegls.h File Reference
JPEG-LS common code.
#include "libavutil/common.h"
#include "avcodec.h"
#include "internal.h"
Data Structures
struct JpeglsContext
struct JLSState
Macros
#define R(a, i) (bits == 8 ? ((uint8_t *)(a))[i] : ((uint16_t *)(a))[i])
#define W(a, i, v) (bits == 8 ? (((uint8_t *)(a))[i] = v) : (((uint16_t *)(a))[i] = v))
Functions
void ff_jpegls_init_state (JLSState *state)
Calculate initial JPEG-LS parameters.
static int ff_jpegls_quantize (JLSState *s, int v)
Calculate quantized gradient value, used for context determination.
void ff_jpegls_reset_coding_parameters (JLSState *s, int reset_all)
Calculate JPEG-LS codec values.
static void ff_jpegls_downscale_state (JLSState *state, int Q)
static int ff_jpegls_update_state_regular (JLSState *state, int Q, int err)
Detailed Description
JPEG-LS common code.
Definition in file jpegls.h.
Macro Definition Documentation
R
#define R (a, i) (bits == 8 ? ((uint8_t *)(a))[i] : ((uint16_t *)(a))[i])
Definition at line 121 of file jpegls.h.
W
#define W (a, i, v) (bits == 8 ? (((uint8_t *)(a))[i] = v) : (((uint16_t *)(a))[i] = v))
Definition at line 122 of file jpegls.h.
Referenced by epic_decode_pixel_pred(), epic_decode_run_length(), evolve(), fill_rgb2yuv_table(), filter_color(), filter_color2(), filter_mono(), ls_decode_line(), and ls_encode_line().
Function Documentation
ff_jpegls_init_state()
void ff_jpegls_init_state (JLSState * state)
Calculate initial JPEG-LS parameters.
Definition at line 31 of file jpegls.c.
Referenced by encode_picture_ls(), and ff_jpegls_decode_picture().
ff_jpegls_quantize()
static int ff_jpegls_quantize (JLSState * s, int v) inline static
Calculate quantized gradient value, used for context determination.
Definition at line 55 of file jpegls.h.
Referenced by ls_decode_line(), and ls_encode_line().
ff_jpegls_reset_coding_parameters()
void ff_jpegls_reset_coding_parameters (JLSState * s, int reset_all)
Calculate JPEG-LS codec values.
Definition at line 62 of file jpegls.c.
Referenced by encode_picture_ls(), ff_jpegls_decode_picture(), ff_jpegls_quantize(), and ls_store_lse().
ff_jpegls_downscale_state()
static void ff_jpegls_downscale_state (JLSState * state, int Q) inline static
Definition at line 87 of file jpegls.h.
Referenced by ff_jpegls_update_state_regular(), ls_encode_runterm(), and ls_get_code_runterm().
ff_jpegls_update_state_regular()
static int ff_jpegls_update_state_regular (JLSState * state, int Q, int err) inline static
Definition at line 97 of file jpegls.h.
Referenced by ls_encode_regular(), and ls_get_code_regular().