FFmpeg: libavcodec/jpegls.c File Reference
jpegls.c File Reference
JPEG-LS common code.
#include "internal.h"
#include "jpegls.h"
Functions
void ff_jpegls_init_state (JLSState *state)
Calculate initial JPEG-LS parameters.
static int iso_clip (int v, int vmin, int vmax)
Custom value clipping function used in T1, T2, T3 calculation.
void ff_jpegls_reset_coding_parameters (JLSState *s, int reset_all)
Calculate JPEG-LS codec values.
Detailed Description
JPEG-LS common code.
Definition in file jpegls.c.
Function Documentation
ff_jpegls_init_state()
void ff_jpegls_init_state (JLSState * state)
Calculate initial JPEG-LS parameters.
Definition at line 31 of file jpegls.c.
Referenced by encode_picture_ls(), and ff_jpegls_decode_picture().
iso_clip()
static int iso_clip (int v, int vmin, int vmax) inline static
Custom value clipping function used in T1, T2, T3 calculation.
Definition at line 54 of file jpegls.c.
Referenced by ff_jpegls_reset_coding_parameters().
ff_jpegls_reset_coding_parameters()
void ff_jpegls_reset_coding_parameters (JLSState * s, int reset_all)
Calculate JPEG-LS codec values.
Definition at line 62 of file jpegls.c.
Referenced by encode_picture_ls(), ff_jpegls_decode_picture(), ff_jpegls_quantize(), and ls_store_lse().