FFmpeg: libavcodec/kbdwin.h File Reference
kbdwin.h File Reference
#include <stdint.h>
Macros
#define FF_KBD_WINDOW_MAX 1024
Maximum window size for ff_kbd_window_init.
Functions
void ff_kbd_window_init (float *window, float alpha, int n)
Generate a Kaiser-Bessel Derived Window.
void ff_kbd_window_init_fixed (int32_t *window, float alpha, int n)
Macro Definition Documentation
FF_KBD_WINDOW_MAX
#define FF_KBD_WINDOW_MAX 1024
Maximum window size for ff_kbd_window_init.
Definition at line 27 of file kbdwin.h.
Referenced by ff_kbd_window_init(), and ff_kbd_window_init_fixed().
Function Documentation
ff_kbd_window_init()
void ff_kbd_window_init (float * window, float alpha, int n)
Generate a Kaiser-Bessel Derived Window.
Parameters
window pointer to half window
alpha determines window shape
n size of half window, max FF_KBD_WINDOW_MAX
Definition at line 26 of file kbdwin.c.
Referenced by aac_static_table_init(), ac3_decode_init(), dsp_init(), ff_ac3_float_mdct_init(), and ff_kbd_window_init_fixed().
ff_kbd_window_init_fixed()
void ff_kbd_window_init_fixed (int32_t * window, float alpha, int n)
Definition at line 49 of file kbdwin.c.