FFmpeg: libavcodec/kbdwin.c File Reference
kbdwin.c File Reference
#include "libavutil/avassert.h"
#include "libavutil/mathematics.h"
#include "libavutil/attributes.h"
#include "kbdwin.h"
Macros
#define BESSEL_I0_ITER 50
Functions
av_cold void ff_kbd_window_init (float *window, float alpha, int n)
Generate a Kaiser-Bessel Derived Window.
av_cold void ff_kbd_window_init_fixed (int32_t *window, float alpha, int n)
Macro Definition Documentation
BESSEL_I0_ITER
#define BESSEL_I0_ITER 50
Definition at line 24 of file kbdwin.c.
Referenced by ff_kbd_window_init().
Function Documentation
ff_kbd_window_init()
av_cold void ff_kbd_window_init (float * window, float alpha, int n)
Generate a Kaiser-Bessel Derived Window.
Parameters
window pointer to half window
alpha determines window shape
n size of half window, max FF_KBD_WINDOW_MAX
Definition at line 26 of file kbdwin.c.
Referenced by aac_static_table_init(), ac3_decode_init(), dsp_init(), ff_ac3_float_mdct_init(), and ff_kbd_window_init_fixed().
ff_kbd_window_init_fixed()
av_cold void ff_kbd_window_init_fixed (int32_t * window, float alpha, int n)
Definition at line 49 of file kbdwin.c.