FFmpeg: libavcodec/lagarithrac.h File Reference
lagarithrac.h File Reference
Lagarith range decoder.
#include <stdint.h>
#include "libavutil/common.h"
#include "libavutil/intreadwrite.h"
#include "avcodec.h"
#include "get_bits.h"
Data Structures
struct lag_rac
Functions
void ff_lag_rac_init (lag_rac *l, GetBitContext *gb, int length)
static void lag_rac_refill (lag_rac *l)
static uint8_t lag_get_rac (lag_rac *l)
Decode a single byte from the compressed plane described by *l.
Detailed Description
Lagarith range decoder.
Author
Nathan Caldwell
David Conrad
Definition in file lagarithrac.h.
Function Documentation
ff_lag_rac_init()
void ff_lag_rac_init (lag_rac * l, GetBitContext * gb, int length)
Definition at line 33 of file lagarithrac.c.
Referenced by lag_decode_arith_plane().
lag_rac_refill()
static void lag_rac_refill (lag_rac * l) inline static
Definition at line 57 of file lagarithrac.h.
Referenced by lag_get_rac().
lag_get_rac()
static uint8_t lag_get_rac (lag_rac * l) inline static
Decode a single byte from the compressed plane described by *l.
Parameters
l pointer to lag_rac for the current plane
Returns
next byte of decoded data
Definition at line 73 of file lagarithrac.h.
Referenced by lag_decode_line().