FFmpeg: libavfilter/lavfutils.h File Reference
lavfutils.h File Reference
Miscellaneous utilities which make use of the libavformat library.
#include "libavformat/avformat.h"
Functions
int ff_load_image (uint8_t *data[4], int linesize[4], int *w, int *h, enum AVPixelFormat *pix_fmt, const char *filename, void *log_ctx)
Load image from filename and put the resulting image in data.
Detailed Description
Miscellaneous utilities which make use of the libavformat library.
Definition in file lavfutils.h.
Function Documentation
ff_load_image()
int ff_load_image (uint8_t * data[4], int linesize[4], int * w, int * h, enum AVPixelFormat * pix_fmt, const char * filename, void * log_ctx)
Load image from filename and put the resulting image in data.
Parameters
w pointer to the width of the loaded image
h pointer to the height of the loaded image
pix_fmt pointer to the pixel format of the loaded image
filename the name of the image file to load
log_ctx log context
Returns
>= 0 in case of success, a negative error code otherwise.
Definition at line 24 of file lavfutils.c.
Referenced by init(), init_axis_from_file(), and load_mask().