FFmpeg: libavdevice/lavfi.c File Reference
lavfi.c File Reference
libavfilter virtual input device
#include <float.h>
#include "libavutil/bprint.h"
#include "libavutil/channel_layout.h"
#include "libavutil/file.h"
#include "libavutil/imgutils.h"
#include "libavutil/internal.h"
#include "libavutil/log.h"
#include "libavutil/mem.h"
#include "libavutil/opt.h"
#include "libavutil/parseutils.h"
#include "libavutil/pixdesc.h"
#include "libavfilter/avfilter.h"
#include "libavfilter/avfiltergraph.h"
#include "libavfilter/buffersink.h"
#include "libavformat/avio_internal.h"
#include "libavformat/internal.h"
#include "avdevice.h"
Data Structures
struct LavfiContext
Macros
#define FAIL(ERR) { ret = ERR; goto end; }
#define OFFSET(x) offsetof(LavfiContext, x)
#define DEC AV_OPT_FLAG_DECODING_PARAM
Functions
static int * create_all_formats (int n)
static av_cold int lavfi_read_close (AVFormatContext *avctx)
static int create_subcc_streams (AVFormatContext *avctx)
static av_cold int lavfi_read_header (AVFormatContext *avctx)
static int create_subcc_packet (AVFormatContext *avctx, AVFrame *frame, int sink_idx)
static int lavfi_read_packet (AVFormatContext *avctx, AVPacket *pkt)
Variables
static const AVOption options []
static const AVClass lavfi_class
AVInputFormat ff_lavfi_demuxer
Detailed Description
libavfilter virtual input device
Definition in file lavfi.c.
Macro Definition Documentation
FAIL
#define FAIL (ERR) { ret = ERR; goto end; }
Referenced by lavfi_read_header().
OFFSET
#define OFFSET (x) offsetof(LavfiContext, x)
Definition at line 487 of file lavfi.c.
DEC
#define DEC AV_OPT_FLAG_DECODING_PARAM
Definition at line 489 of file lavfi.c.
Function Documentation
create_all_formats()
static int* create_all_formats (int n) static
Definition at line 63 of file lavfi.c.
Referenced by lavfi_read_header().
lavfi_read_close()
static av_cold int lavfi_read_close (AVFormatContext * avctx) static
Definition at line 84 of file lavfi.c.
Referenced by lavfi_read_header().
create_subcc_streams()
static int create_subcc_streams (AVFormatContext * avctx) static
Definition at line 99 of file lavfi.c.
Referenced by lavfi_read_header().
lavfi_read_header()
static av_cold int lavfi_read_header (AVFormatContext * avctx) static
Definition at line 120 of file lavfi.c.
create_subcc_packet()
static int create_subcc_packet (AVFormatContext * avctx, AVFrame * frame, int sink_idx) static
Definition at line 358 of file lavfi.c.
Referenced by lavfi_read_packet().
lavfi_read_packet()
static int lavfi_read_packet (AVFormatContext * avctx, AVPacket * pkt) static
Definition at line 382 of file lavfi.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "graph",     "set libavfilter graph", OFFSET(graph_str),  AV_OPT_TYPE_STRING, {.str = NULL}, 0, 0, DEC },
    { "graph_file","set libavfilter graph filename", OFFSET(graph_filename), AV_OPT_TYPE_STRING, {.str = NULL}, 0, 0, DEC},
    { "dumpgraph", "dump graph to stderr",  OFFSET(dump_graph), AV_OPT_TYPE_STRING, {.str = NULL}, 0, 0, DEC },
    { NULL },
}
Definition at line 491 of file lavfi.c.
Referenced by lavfi_read_header().
lavfi_class
const AVClass lavfi_class static
Initial value:
= {
    .class_name = "lavfi indev",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
    .category   = AV_CLASS_CATEGORY_DEVICE_INPUT,
}
Definition at line 498 of file lavfi.c.
ff_lavfi_demuxer
AVInputFormat ff_lavfi_demuxer
Initial value:
= {
    .name           = "lavfi",
    .long_name      = NULL_IF_CONFIG_SMALL("Libavfilter virtual input device"),
    .priv_data_size = sizeof(LavfiContext),
    .read_header    = lavfi_read_header,
    .read_packet    = lavfi_read_packet,
    .read_close     = lavfi_read_close,
    .flags          = AVFMT_NOFILE,
    .priv_class     = &lavfi_class,
}
Definition at line 506 of file lavfi.c.