FFmpeg: libavcodec/lcldec.c File Reference
lcldec.c File Reference
LCL (LossLess Codec Library) Video Codec Decoder for MSZH and ZLIB codecs Experimental encoder for ZLIB RGB24.
#include <stdio.h>
#include <stdlib.h>
#include "libavutil/mem.h"
#include "libavutil/pixdesc.h"
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
#include "lcl.h"
Data Structures
struct LclDecContext
Functions
static unsigned int mszh_decomp (const unsigned char *srcptr, int srclen, unsigned char *destptr, unsigned int destsize)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int decode_init (AVCodecContext *avctx)
static av_cold int decode_end (AVCodecContext *avctx)
Detailed Description
LCL (LossLess Codec Library) Video Codec Decoder for MSZH and ZLIB codecs Experimental encoder for ZLIB RGB24.
Fourcc: MSZH, ZLIB
Original Win32 dll: Ver2.23 By Kenji Oshima 2000.09.20 avimszh.dll, avizlib.dll
A description of the decoding algorithm can be found here: http://www.pcisys.net/~melanson/codecs
Supports: BGR24 (RGB 24bpp)
Definition in file lcldec.c.
Function Documentation
mszh_decomp()
static unsigned int mszh_decomp (const unsigned char * srcptr, int srclen, unsigned char * destptr, unsigned int destsize) static
Parameters
srcptr compressed source buffer, must be padded with at least 5 extra bytes
destptr must be padded sufficiently for av_memcpy_backptr
Definition at line 75 of file lcldec.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 157 of file lcldec.c.
Referenced by decode_end().
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 467 of file lcldec.c.
Referenced by decode_end().
decode_end()
static av_cold int decode_end (AVCodecContext * avctx) static
Definition at line 621 of file lcldec.c.