FFmpeg: libavutil/lfg.h File Reference
lfg.h File Reference
Data Structures
struct AVLFG
Functions
void av_lfg_init (AVLFG *c, unsigned int seed)
static unsigned int av_lfg_get (AVLFG *c)
Get the next random unsigned 32-bit number using an ALFG.
static unsigned int av_mlfg_get (AVLFG *c)
Get the next random unsigned 32-bit number using a MLFG.
void av_bmg_get (AVLFG *lfg, double out[2])
Get the next two numbers generated by a Box-Muller Gaussian generator using the random numbers issued by lfg.
Function Documentation
av_lfg_init()
void av_lfg_init (AVLFG * c, unsigned int seed)
Definition at line 30 of file lfg.c.
Referenced by a64multi_encode_init(), ac3_decode_init(), amrwb_decode_init(), cinepak_encode_init(), cng_decode_init(), config_input(), config_props(), cook_decode_init(), dct_error(), decode_init(), encode_init(), ff_dither_alloc(), fill_random(), generate_dither_noise(), idct248_error(), init(), init_noise(), main(), mkv_write_attachments(), mkv_write_header(), mpc7_decode_init(), mpc8_decode_init(), roq_encode_init(), and rtmp_handshake().
av_lfg_get()
static unsigned int av_lfg_get (AVLFG * c) inline static
Get the next random unsigned 32-bit number using an ALFG.
Please also consider a simple LCG like state= state*1664525+1013904223, it may be good enough and faster for your specific use case.
Definition at line 38 of file lfg.h.
Referenced by ac3_decode_transform_coeffs_ch(), audiogen(), av_bmg_get(), cng_decode_frame(), dbl_rand(), drand(), ff_dither_alloc(), ff_eac3_apply_spectral_extension(), ff_eac3_decode_transform_coeffs_aht_ch(), fill_random(), filter_frame(), frandom(), generate_dither_noise(), get_high_utility_cell(), http_parse_request(), idct248_error(), idx_to_quant(), init(), init_block(), init_noise(), main(), mkv_write_attachments(), mkv_write_header(), mpc8_decode_frame(), nelly_decode_block(), request_frame(), rtmp_handshake(), rtsp_cmd_setup(), scalar_dequant_float(), scaled_hb_excitation(), and start_multicast().
av_mlfg_get()
static unsigned int av_mlfg_get (AVLFG * c) inline static
Get the next random unsigned 32-bit number using a MLFG.
Please also consider av_lfg_get() above, it is faster.
Definition at line 48 of file lfg.h.
av_bmg_get()
void av_bmg_get (AVLFG * lfg, double out[2])
Get the next two numbers generated by a Box-Muller Gaussian generator using the random numbers issued by lfg.
Parameters
out array where the two generated numbers are placed
Definition at line 47 of file lfg.c.
Referenced by av_mlfg_get(), fill_double_array(), fill_float_array(), and main().