FFmpeg: libavutil/lfg.c File Reference
lfg.c File Reference
#include <inttypes.h>
#include <limits.h>
#include <math.h>
#include "lfg.h"
#include "md5.h"
#include "intreadwrite.h"
#include "attributes.h"
Functions
av_cold void av_lfg_init (AVLFG *c, unsigned int seed)
void av_bmg_get (AVLFG *lfg, double out[2])
Get the next two numbers generated by a Box-Muller Gaussian generator using the random numbers issued by lfg.
Function Documentation
av_lfg_init()
av_cold void av_lfg_init (AVLFG * c, unsigned int seed)
Definition at line 30 of file lfg.c.
Referenced by a64multi_encode_init(), ac3_decode_init(), amrwb_decode_init(), cinepak_encode_init(), cng_decode_init(), config_input(), config_props(), cook_decode_init(), dct_error(), decode_init(), encode_init(), ff_dither_alloc(), fill_random(), generate_dither_noise(), idct248_error(), init(), init_noise(), main(), mkv_write_attachments(), mkv_write_header(), mpc7_decode_init(), mpc8_decode_init(), roq_encode_init(), and rtmp_handshake().
av_bmg_get()
void av_bmg_get (AVLFG * lfg, double out[2])
Get the next two numbers generated by a Box-Muller Gaussian generator using the random numbers issued by lfg.
Parameters
out array where the two generated numbers are placed
Definition at line 47 of file lfg.c.
Referenced by av_mlfg_get(), fill_double_array(), fill_float_array(), and main().