FFmpeg: libavformat/assenc.c File Reference
assenc.c File Reference
#include "libavutil/avstring.h"
#include "avformat.h"
#include "internal.h"
#include "libavutil/opt.h"
Data Structures
struct DialogueLine
struct ASSContext
Macros
#define OFFSET(x) offsetof(ASSContext, x)
#define E AV_OPT_FLAG_ENCODING_PARAM
Functions
static int write_header (AVFormatContext *s)
static void purge_dialogues (AVFormatContext *s, int force)
static void insert_dialogue (ASSContext *ass, DialogueLine *dialogue)
static int write_packet (AVFormatContext *s, AVPacket *pkt)
static int write_trailer (AVFormatContext *s)
Variables
static const AVOption options []
static const AVClass ass_class
AVOutputFormat ff_ass_muxer
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(ASSContext, x)
Definition at line 216 of file assenc.c.
E
#define E AV_OPT_FLAG_ENCODING_PARAM
Definition at line 217 of file assenc.c.
Function Documentation
write_header()
static int write_header (AVFormatContext * s) static
Definition at line 46 of file assenc.c.
purge_dialogues()
static void purge_dialogues (AVFormatContext * s, int force) static
Definition at line 85 of file assenc.c.
Referenced by write_packet(), and write_trailer().
insert_dialogue()
static void insert_dialogue (ASSContext * ass, DialogueLine * dialogue) static
Definition at line 115 of file assenc.c.
Referenced by write_packet().
write_packet()
static int write_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 155 of file assenc.c.
write_trailer()
static int write_trailer (AVFormatContext * s) static
Definition at line 203 of file assenc.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "ignore_readorder", "write events immediately, even if they're out-of-order", OFFSET(ignore_readorder), AV_OPT_TYPE_BOOL, {.i64 = 0}, 0, 1, E },
    { NULL },
}
Definition at line 218 of file assenc.c.
ass_class
const AVClass ass_class static
Initial value:
= {
    .class_name = "ass muxer",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 223 of file assenc.c.
ff_ass_muxer
AVOutputFormat ff_ass_muxer
Initial value:
= {
    .name           = "ass",
    .long_name      = NULL_IF_CONFIG_SMALL("SSA (SubStation Alpha) subtitle"),
    .mime_type      = "text/x-ass",
    .extensions     = "ass,ssa",
    .priv_data_size = sizeof(ASSContext),
    .subtitle_codec = AV_CODEC_ID_ASS,
    .write_header   = write_header,
    .write_packet   = write_packet,
    .write_trailer  = write_trailer,
    .flags          = AVFMT_GLOBALHEADER | AVFMT_NOTIMESTAMPS | AVFMT_TS_NONSTRICT,
    .priv_class     = &ass_class,
}
Definition at line 230 of file assenc.c.