FFmpeg: libavcodec/pthread.c File Reference
pthread.c File Reference
Multithreading support functions.
#include "avcodec.h"
#include "internal.h"
#include "pthread_internal.h"
#include "thread.h"
Functions
static void validate_thread_parameters (AVCodecContext *avctx)
Set the threading algorithms used.
int ff_thread_init (AVCodecContext *avctx)
void ff_thread_free (AVCodecContext *avctx)
Detailed Description
Multithreading support functions.
See also
doc/multithreading.txt
Definition in file pthread.c.
Function Documentation
validate_thread_parameters()
static void validate_thread_parameters (AVCodecContext * avctx) static
Set the threading algorithms used.
Threading requires more than one thread. Frame threading requires entire frames to be passed to the codec, and introduces extra decoding delay, so is incompatible with low_delay.
Parameters
avctx The context.
Definition at line 46 of file pthread.c.
Referenced by ff_thread_init().
ff_thread_init()
int ff_thread_init (AVCodecContext * avctx)
Definition at line 70 of file pthread.c.
ff_thread_free()
void ff_thread_free (AVCodecContext * avctx)
Definition at line 82 of file pthread.c.
Referenced by avcodec_close(), and ff_slice_thread_init().