FFmpeg: libavcodec/internal.h File Reference
internal.h File Reference
common internal api header.
#include <stdint.h>
#include "libavutil/buffer.h"
#include "libavutil/channel_layout.h"
#include "libavutil/mathematics.h"
#include "libavutil/pixfmt.h"
#include "avcodec.h"
#include "config.h"
Data Structures
struct FramePool
struct AVCodecInternal
struct AVCodecDefault
Macros
#define FF_CODEC_CAP_INIT_THREADSAFE (1 << 0)
The codec does not modify any global variables in the init function, allowing to call the init function without locking any global mutexes.
#define FF_CODEC_CAP_INIT_CLEANUP (1 << 1)
The codec allows calling the close function for deallocation even if the init function returned a failure.
#define FF_CODEC_CAP_SETS_PKT_DTS (1 << 2)
Decoders marked with FF_CODEC_CAP_SETS_PKT_DTS want to set AVFrame.pkt_dts manually.
#define FF_CODEC_CAP_SKIP_FRAME_FILL_PARAM (1 << 3)
The decoder extracts and fills its parameters even if the frame is skipped due to the skip_frame setting.
#define ff_tlog(ctx, ...) do { } while(0)
#define FF_SANE_NB_CHANNELS 64U
#define FF_SIGNBIT(x) ((x) >> CHAR_BIT * sizeof(x) - 1)
#define STRIDE_ALIGN 8
#define FF_MAX_EXTRADATA_SIZE ((1 << 28) - AV_INPUT_BUFFER_PADDING_SIZE)
Maximum size in bytes of extradata.
Functions
int ff_match_2uint16 (const uint16_t(*tab)[2], int size, int a, int b)
Return the index into tab at which {a,b} match elements {[0],[1]} of tab.
unsigned int avpriv_toupper4 (unsigned int x)
int ff_init_buffer_info (AVCodecContext *s, AVFrame *frame)
does needed setup of pkt_pts/pos and such for (re)get_buffer();
void ff_color_frame (AVFrame *frame, const int color[4])
int ff_lock_avcodec (AVCodecContext *log_ctx, const AVCodec *codec)
int ff_unlock_avcodec (const AVCodec *codec)
int avpriv_lock_avformat (void)
int avpriv_unlock_avformat (void)
int ff_alloc_packet2 (AVCodecContext *avctx, AVPacket *avpkt, int64_t size, int64_t min_size)
Check AVPacket size and/or allocate data.
attribute_deprecated int ff_alloc_packet (AVPacket *avpkt, int size)
static av_always_inline int64_t ff_samples_to_time_base (AVCodecContext *avctx, int64_t samples)
Rescale from sample rate to AVCodecContext.time_base.
static av_always_inline float ff_exp2fi (int x)
2^(x) for integer x
int ff_get_buffer (AVCodecContext *avctx, AVFrame *frame, int flags)
Get a buffer for a frame.
int ff_reget_buffer (AVCodecContext *avctx, AVFrame *frame)
Identical in function to av_frame_make_writable(), except it uses ff_get_buffer() to allocate the buffer when needed.
int ff_thread_can_start_frame (AVCodecContext *avctx)
int avpriv_h264_has_num_reorder_frames (AVCodecContext *avctx)
int ff_codec_open2_recursive (AVCodecContext *avctx, const AVCodec *codec, AVDictionary **options)
Call avcodec_open2 recursively by decrementing counter, unlocking mutex, calling the function and then restoring again.
int avpriv_bprint_to_extradata (AVCodecContext *avctx, struct AVBPrint *buf)
Finalize buf into extradata and set its size appropriately.
const uint8_t * avpriv_find_start_code (const uint8_t *p, const uint8_t *end, uint32_t *state)
int avpriv_codec_get_cap_skip_frame_fill_param (const AVCodec *codec)
int ff_set_dimensions (AVCodecContext *s, int width, int height)
Check that the provided frame dimensions are valid and set them on the codec context.
int ff_set_sar (AVCodecContext *avctx, AVRational sar)
Check that the provided sample aspect ratio is valid and set it on the codec context.
int ff_side_data_update_matrix_encoding (AVFrame *frame, enum AVMatrixEncoding matrix_encoding)
Add or update AV_FRAME_DATA_MATRIXENCODING side data.
int ff_get_format (AVCodecContext *avctx, const enum AVPixelFormat *fmt)
Select the (possibly hardware accelerated) pixel format.
int ff_decode_frame_props (AVCodecContext *avctx, AVFrame *frame)
Set various frame properties from the codec context / packet data.
AVCPBProperties * ff_add_cpb_side_data (AVCodecContext *avctx)
Add a CPB properties side data to an encoding context.
int ff_side_data_set_encoder_stats (AVPacket *pkt, int quality, int64_t *error, int error_count, int pict_type)
int ff_alloc_a53_sei (const AVFrame *frame, size_t prefix_len, void **data, size_t *sei_size)
Check AVFrame for A53 side data and allocate and fill SEI message with A53 info.
Variables
const uint8_t ff_log2_run [41]
volatile int ff_avcodec_locked
Detailed Description
common internal api header.
Definition in file internal.h.
Macro Definition Documentation
FF_CODEC_CAP_INIT_THREADSAFE
#define FF_CODEC_CAP_INIT_THREADSAFE (1 << 0)
The codec does not modify any global variables in the init function, allowing to call the init function without locking any global mutexes.
Definition at line 40 of file internal.h.
Referenced by decode_flush(), encode_init(), ff_lock_avcodec(), ff_unlock_avcodec(), and sp5x_decode_frame().
FF_CODEC_CAP_INIT_CLEANUP
#define FF_CODEC_CAP_INIT_CLEANUP (1 << 1)
The codec allows calling the close function for deallocation even if the init function returned a failure.
Without this capability flag, a codec does such cleanup internally when returning failures from the init function and does not expect the close function to be called at all.
Definition at line 48 of file internal.h.
Referenced by avcodec_open2(), and nvenc_old_init().
FF_CODEC_CAP_SETS_PKT_DTS
#define FF_CODEC_CAP_SETS_PKT_DTS (1 << 2)
Decoders marked with FF_CODEC_CAP_SETS_PKT_DTS want to set AVFrame.pkt_dts manually.
If the flag is set, utils.c won't overwrite this field. If it's unset, utils.c tries to guess the pkt_dts field from the input AVPacket.
Definition at line 55 of file internal.h.
Referenced by avcodec_decode_video2(), and mediacodec_decode_flush().
FF_CODEC_CAP_SKIP_FRAME_FILL_PARAM
#define FF_CODEC_CAP_SKIP_FRAME_FILL_PARAM (1 << 3)
The decoder extracts and fills its parameters even if the frame is skipped due to the skip_frame setting.
Definition at line 60 of file internal.h.
Referenced by avpriv_codec_get_cap_skip_frame_fill_param(), decode_flush(), and png_dec_end().
ff_tlog
#define ff_tlog (ctx, ...) do { } while(0)
Definition at line 65 of file internal.h.
Referenced by avi_sync(), decode_format80(), decode_residual(), decode_slice(), fetch_diagonal_mv(), ff_filter_frame(), ff_h264_decode_mb_cabac(), ff_h264_decode_mb_cavlc(), ff_h264_filter_mb(), ff_tlog_link(), ff_tlog_ref(), ff_wma_init(), filter_mb_dir(), h263p_decode_umotion(), h264_initialise_ref_list(), h264_probe(), ipvideo_decode_block_opcode_0x2(), ipvideo_decode_block_opcode_0x3(), ipvideo_decode_block_opcode_0x4(), ipvideo_decode_block_opcode_0x5(), ipvideo_decode_block_opcode_0x6_16(), ipvideo_decode_opcodes(), mpeg2_decode_block_intra(), mpeg4_decode_block(), mpeg_decode_mb(), pred_16x8_motion(), pred_8x16_motion(), pred_intra_mode(), pred_motion(), pred_non_zero_count(), pred_pskip_motion(), rv10_decode_packet(), wma_decode_block(), wma_decode_frame(), and wma_decode_superframe().
FF_SANE_NB_CHANNELS
#define FF_SANE_NB_CHANNELS 64U
Definition at line 73 of file internal.h.
Referenced by avcodec_open2(), and ff_init_buffer_info().
FF_SIGNBIT
#define FF_SIGNBIT (x) ((x) >> CHAR_BIT * sizeof(x) - 1)
Definition at line 75 of file internal.h.
Referenced by dnxhd_10bit_dct_quantize(), inter_predict(), mv_pred_direct(), and scale_mv().
STRIDE_ALIGN
#define STRIDE_ALIGN 8
Definition at line 82 of file internal.h.
Referenced by avcodec_align_dimensions2(), load_input_picture(), and update_frame_pool().
FF_MAX_EXTRADATA_SIZE
#define FF_MAX_EXTRADATA_SIZE ((1 << 28) - AV_INPUT_BUFFER_PADDING_SIZE)
Maximum size in bytes of extradata.
This value was chosen such that every bit of the buffer is addressable by a 32-bit signed integer as used by get_bits.
Definition at line 214 of file internal.h.
Referenced by avcodec_open2(), avformat_find_stream_info(), ffm2_read_header(), and ffm_read_header().
Function Documentation
ff_match_2uint16()
int ff_match_2uint16 (const uint16_t(*) tab[2], int size, int a, int b)
Return the index into tab at which {a,b} match elements {[0],[1]} of tab.
If there is no such matching pair then size is returned.
Definition at line 3781 of file utils.c.
Referenced by ff_h263_encode_picture_header(), ff_mpv_encode_init(), and svq1_write_header().
avpriv_toupper4()
unsigned int avpriv_toupper4 (unsigned int x)
Definition at line 3926 of file utils.c.
Referenced by ff_codec_get_id(), ff_mpv_decode_init(), mpeg_decode_frame(), and validate_codec_tag().
ff_init_buffer_info()
int ff_init_buffer_info (AVCodecContext * s, AVFrame * frame)
does needed setup of pkt_pts/pos and such for (re)get_buffer();
Definition at line 755 of file utils.c.
Referenced by ff_decode_frame_props(), reget_buffer_internal(), and thread_get_buffer_internal().
ff_color_frame()
void ff_color_frame (AVFrame * frame, const int color[4])
Definition at line 700 of file utils.c.
Referenced by h264_frame_start().
ff_lock_avcodec()
int ff_lock_avcodec (AVCodecContext * log_ctx, const AVCodec * codec)
Definition at line 3866 of file utils.c.
Referenced by avcodec_open2(), and ff_codec_open2_recursive().
ff_unlock_avcodec()
int ff_unlock_avcodec (const AVCodec * codec)
Definition at line 3892 of file utils.c.
Referenced by avcodec_open2(), ff_codec_open2_recursive(), and ff_lock_avcodec().
avpriv_lock_avformat()
int avpriv_lock_avformat (void)
Definition at line 3908 of file utils.c.
Referenced by avisynth_read_close(), avisynth_read_header(), cleanup(), ff_gnutls_deinit(), ff_gnutls_init(), ff_openssl_deinit(), ff_openssl_init(), and write_header().
avpriv_unlock_avformat()
int avpriv_unlock_avformat (void)
Definition at line 3917 of file utils.c.
Referenced by avisynth_read_close(), avisynth_read_header(), cleanup(), ff_gnutls_deinit(), ff_gnutls_init(), ff_openssl_deinit(), ff_openssl_init(), and write_header().
ff_alloc_packet2()
int ff_alloc_packet2 (AVCodecContext * avctx, AVPacket * avpkt, int64_t size, int64_t min_size)
Check AVPacket size and/or allocate data.
Encoders supporting AVCodec.encode2() can use this as a convenience to ensure the output packet data is large enough, whether provided by the user or allocated in this function.
Parameters
avctx the AVCodecContext of the encoder
avpkt the AVPacket If avpkt->data is already set, avpkt->size is checked to ensure it is large enough. If avpkt->data is NULL, a new buffer is allocated. avpkt->size is set to the specified size. All other AVPacket fields will be reset with av_init_packet().
size the minimum required packet size
min_size This is a hint to the allocation algorithm, which indicates to what minimal size the caller might later shrink the packet to. Encoders often allocate packets which are larger than the amount of data that is written into them as the exact amount is not known at the time of allocation. min_size represents the size a packet might be shrunk to by the caller. Can be set to 0. setting this roughly correctly allows the allocation code to choose between several allocation strategies to improve speed slightly.
Returns
non negative on success, negative error code on failure
Definition at line 1723 of file utils.c.
Referenced by a64multi_encode_frame(), aac_encode_frame(), adpcm_encode_frame(), adx_encode_frame(), alac_encode_frame(), amr_decode_fix_avctx(), amr_wb_encode_frame(), avui_encode_frame(), bmp_encode_frame(), cinepak_encode_frame(), cng_encode_frame(), dnxhd_encode_picture(), dvvideo_encode_frame(), encode_apng(), encode_frame(), encode_nals(), encode_picture_ls(), encode_png(), encode_superframe(), ff_alloc_packet(), ff_mpv_encode_picture(), ffat_encode(), flac_encode_frame(), flashsv2_encode_frame(), flashsv_encode_frame(), g722_encode_frame(), g723_1_encode_frame(), g726_reset(), gif_encode_frame(), hap_encode(), ilbc_encode_frame(), libgsm_encode_frame(), libopenjpeg_encode_frame(), libopus_encode(), libschroedinger_encode_frame(), libshine_encode_frame(), libvorbis_encode_frame(), libwebp_anim_encode_frame(), libwebp_encode_frame(), ljpeg_encode_frame(), mlp_encode_frame(), mp3lame_encode_frame(), MPA_encode_frame(), omx_encode_frame(), pam_encode_frame(), pcm_encode_frame(), pcx_encode_frame(), pnm_encode_frame(), predictor_calc_error(), process_output_surface(), prores_encode_frame(), qtrle_encode_frame(), ra144_encode_frame(), raw_encode(), roq_dpcm_encode_frame(), roq_encode_frame(), s302m_encode2_frame(), storeframe(), sunrast_encode_frame(), svc_encode_frame(), svq1_encode_frame(), targa_encode_frame(), tta_encode_frame(), twolame_encode_frame(), utvideo_encode_frame(), v308_encode_frame(), v408_encode_frame(), v410_encode_frame(), vorbis_encode_frame(), vtenc_cm_to_avpacket(), wavpack_encode_frame(), XAVS_frame(), xbm_encode_frame(), xface_encode_frame(), xvid_encode_frame(), xwd_encode_frame(), y41p_encode_frame(), and yuv4_encode_frame().
ff_alloc_packet()
attribute_deprecated int ff_alloc_packet (AVPacket * avpkt, int size)
Definition at line 1764 of file utils.c.
Referenced by libkvazaar_encode(), and libx265_encode_frame().
ff_samples_to_time_base()
static av_always_inline int64_t ff_samples_to_time_base (AVCodecContext * avctx, int64_t samples) static
Rescale from sample rate to AVCodecContext.time_base.
Definition at line 249 of file internal.h.
Referenced by amr_wb_encode_frame(), avcodec_encode_audio2(), encode_frame(), encode_superframe(), ff_af_queue_remove(), flac_encode_frame(), g722_encode_frame(), libvorbis_encode_frame(), MPA_encode_frame(), tta_encode_frame(), twolame_encode_frame(), vorbis_encode_frame(), and wavpack_encode_frame().
ff_exp2fi()
static av_always_inline float ff_exp2fi (int x) static
2^(x) for integer x
Returns
correctly rounded float
Definition at line 262 of file internal.h.
Referenced by init_band_stepsize(), and sbr_dequant().
ff_get_buffer()
int ff_get_buffer (AVCodecContext * avctx, AVFrame * frame, int flags)
Get a buffer for a frame.
This is a wrapper around AVCodecContext.get_buffer() and should be used instead calling get_buffer() directly.
Definition at line 948 of file utils.c.
Referenced by ac3_decode_frame(), adpcm_decode_frame(), adx_decode_frame(), alloc_frame(), amr_decode_fix_avctx(), amrnb_decode_frame(), amrwb_decode_frame(), ape_decode_frame(), atrac1_decode_frame(), atrac3_decode_frame(), atrac3p_decode_frame(), aura_decode_frame(), avui_decode_frame(), bfi_decode_frame(), bmp_decode_frame(), bmv_aud_decode_frame(), cdg_decode_frame(), cdxl_decode_frame(), cinaudio_decode_frame(), cllc_decode_frame(), cmv_decode_frame(), cng_decode_frame(), cook_decode_frame(), copy_frame(), copy_output(), cuvid_output_frame(), cyuv_decode_frame(), dds_decode(), decode_frame(), decode_pic(), decode_tag(), dfa_decode_frame(), dpcm_decode_frame(), dss_sp_decode_frame(), dvvideo_decode_frame(), dxtory_decode_v1_410(), dxtory_decode_v1_420(), dxtory_decode_v1_444(), dxtory_decode_v1_rgb(), dxtory_decode_v2(), eightsvx_decode_frame(), escape124_decode_frame(), escape130_decode_frame(), evrc_decode_frame(), execute_code(), fdk_aac_decode_frame(), ff_create_schro_frame(), ff_dca_lbr_filter_frame(), ff_dca_xll_filter_frame(), ff_exp2fi(), ff_ivi_decode_frame(), ff_mjpeg_decode_sof(), ff_snow_common_init_after_header(), ff_snow_get_buffer(), ff_thread_get_buffer(), ff_twinvq_decode_frame(), ff_vp56_decode_frame(), ffat_decode(), ffmal_copy_frame(), filter_frame_fixed(), filter_frame_float(), flush(), frame_configure_elements(), g2m_decode_frame(), g722_decode_frame(), g723_1_decode_frame(), g726_reset(), get_buffer(), get_buffer_with_edge(), gif_decode_frame(), gsm_decode_frame(), hnm_decode_frame(), hq_decode_frame(), hqa_decode_frame(), hqx_decode_frame(), idcin_decode_frame(), ilbc_decode_frame(), imc_decode_frame(), ipvideo_decode_frame(), libcelt_dec_decode(), libgsm_decode_frame(), libopus_decode(), libschroedinger_decode_frame(), libspeex_decode_frame(), m101_decode_frame(), mace_decode_frame(), mediacodec_wrap_sw_buffer(), mp_decode_frame(), mpc7_decode_frame(), mpc8_decode_frame(), mss2_decode_frame(), mvc_decode_frame(), mxpeg_decode_frame(), oggvorbis_decode_frame(), on2avc_decode_frame(), opus_decode_packet(), output_data(), paf_audio_decode(), pcm_bluray_decode_frame(), pcm_decode_frame(), pcm_dvd_decode_frame(), pcx_decode_frame(), pix_decode_frame(), pnm_decode_frame(), predictor_calc_error(), ptx_decode_frame(), qcelp_decode_frame(), qdm2_decode_frame(), ra144_decode_frame(), ra288_decode_frame(), reget_buffer_internal(), rl2_decode_frame(), roq_encode_frame(), s302m_decode_frame(), sgirle_decode_frame(), shorten_decode_frame(), sipr_decode_frame(), smka_decode_frame(), submit_frame(), submit_packet(), sunrast_decode_frame(), svc_decode_frame(), svq1_decode_frame(), svq1_encode_frame(), synth_superframe(), tdsc_decode_frame(), tgq_decode_frame(), tgv_decode_frame(), thread_get_buffer_internal(), tmv_decode_frame(), tqi_decode_frame(), truemotion2rt_decode_frame(), truespeech_decode_frame(), txd_decode_frame(), v308_decode_frame(), v408_decode_frame(), v410_decode_frame(), vcr1_decode_frame(), vmdaudio_decode_frame(), vmdvideo_decode_frame(), vorbis_decode_frame(), vpx_decode(), vqa_decode_frame(), wavesynth_decode(), wma_decode_superframe(), ws_snd_decode_frame(), xan_decode_frame(), xbm_decode_frame(), xface_decode_frame(), xwd_decode_frame(), y216_decode_frame(), y41p_decode_frame(), yuv4_decode_frame(), zero12v_decode_frame(), and zerocodec_decode_frame().
ff_reget_buffer()
int ff_reget_buffer (AVCodecContext * avctx, AVFrame * frame)
Identical in function to av_frame_make_writable(), except it uses ff_get_buffer() to allocate the buffer when needed.
Definition at line 997 of file utils.c.
Referenced by aasc_decode_frame(), avs_decode_frame(), bethsoftvid_decode_frame(), cdg_decode_frame(), cinepak_decode_frame(), cinvideo_decode_frame(), cpia_decode_frame(), decode_frame(), ff_exp2fi(), fic_decode_frame(), flashsv_decode_frame(), flic_decode_frame_15_16BPP(), flic_decode_frame_8BPP(), gif_decode_frame(), ir2_decode_frame(), mm_decode_frame(), mp_decode_frame(), msrle_decode_frame(), mss1_decode_frame(), mss2_decode_frame(), mss3_decode_frame(), mss4_decode_frame(), msvideo1_decode_frame(), paf_video_decode(), qtrle_decode_frame(), roq_decode_frame(), rpza_decode_frame(), rscc_decode_frame(), screenpresso_decode_frame(), seqvideo_decode_frame(), smc_decode_frame(), truemotion1_decode_frame(), tscc2_decode_frame(), ulti_decode_frame(), xan_decode_frame(), and yop_decode_frame().
ff_thread_can_start_frame()
int ff_thread_can_start_frame (AVCodecContext * avctx)
Definition at line 747 of file pthread_frame.c.
Referenced by ff_exp2fi(), ff_mpv_frame_start(), and h264_frame_start().
avpriv_h264_has_num_reorder_frames()
int avpriv_h264_has_num_reorder_frames (AVCodecContext * avctx)
Definition at line 62 of file h264dec.c.
Referenced by ff_exp2fi(), and has_decode_delay_been_guessed().
ff_codec_open2_recursive()
int ff_codec_open2_recursive (AVCodecContext * avctx, const AVCodec * codec, AVDictionary ** options)
Call avcodec_open2 recursively by decrementing counter, unlocking mutex, calling the function and then restoring again.
Assumes the mutex is already locked
Definition at line 1230 of file utils.c.
Referenced by ff_exp2fi(), init(), smvjpeg_decode_init(), and tdsc_init().
avpriv_bprint_to_extradata()
int avpriv_bprint_to_extradata (AVCodecContext * avctx, struct AVBPrint * buf)
Finalize buf into extradata and set its size appropriately.
Definition at line 4015 of file utils.c.
Referenced by dvdsub_init(), and ff_exp2fi().
avpriv_find_start_code()
const uint8_t* avpriv_find_start_code (const uint8_t * p, const uint8_t * end, uint32_t * state)
Referenced by avi_read_packet(), cavs_decode_frame(), cavsvideo_probe(), decode_chunks(), ff_exp2fi(), ff_mpeg1_find_frame_end(), ff_mpeg4video_split(), ff_rtp_send_mpegvideo(), find_next_marker(), find_start_code(), h264_split(), hevc_find_frame_end(), hevc_split(), mpeg_decode_slice(), mpegts_write_packet_internal(), mpegvideo_extract_headers(), mpegvideo_probe(), mxf_parse_h264_frame(), slice_decode_thread(), and vc1_split().
avpriv_codec_get_cap_skip_frame_fill_param()
int avpriv_codec_get_cap_skip_frame_fill_param (const AVCodec * codec)
Definition at line 1197 of file utils.c.
Referenced by ff_exp2fi(), try_decode_frame(), and try_decode_video_frame().
ff_set_dimensions()
int ff_set_dimensions (AVCodecContext * s, int width, int height)
Check that the provided frame dimensions are valid and set them on the codec context.
Definition at line 210 of file utils.c.
Referenced by alloc_buffers(), apply_param_change(), avcodec_open2(), avcodec_set_dimensions(), avs_decode_init(), cdxl_decode_frame(), cfhd_decode(), cmv_process_header(), decode_frame(), decode_frame_headers(), decode_header(), decode_init(), decode_seq_header(), dirac_decode_data_unit(), dnxhd_decode_frame(), dvdsub_parse_extradata(), dvvideo_decode_frame(), execute_code(), ff_exp2fi(), ff_h263_decode_frame(), ff_ivi_decode_frame(), ff_mjpeg_decode_sof(), ff_rv34_decode_frame(), ff_vc1_decode_entry_point(), ff_vc1_decode_sequence_header(), ffmal_update_format(), flashsv_decode_frame(), g2m_decode_frame(), gif_decode_frame(), h261_decode_frame(), init_image(), libopenjpeg_decode_frame(), magy_decode_frame(), mediacodec_dec_parse_format(), mpeg4_decode_header(), mpeg_decode_postinit(), mpegvideo_extract_headers(), mvc_decode_init(), parse_presentation_segment(), pcx_decode_frame(), pix_decode_frame(), pixlet_decode_frame(), process_frame_obj(), ptx_decode_frame(), read_huffman_tree(), rv20_decode_picture_header(), smvjpeg_decode_frame(), sunrast_decode_frame(), svc_decode_frame(), svq1_decode_frame(), tdsc_parse_tdsf(), tgq_decode_frame(), tgv_decode_frame(), tqi_decode_frame(), truemotion1_decode_header(), truemotion2rt_decode_header(), txd_decode_frame(), update_dimensions(), update_size(), vp56_size_changed(), vp5_parse_header(), vp6_parse_header(), vp8_lossless_decode_frame(), vpx_decode(), and xbm_decode_frame().
ff_set_sar()
int ff_set_sar (AVCodecContext * avctx, AVRational sar)
Check that the provided sample aspect ratio is valid and set it on the codec context.
Definition at line 225 of file utils.c.
Referenced by decode_frame(), decode_header(), decode_sequence_header_adv(), dirac_decode_data_unit(), dvvideo_decode_frame(), export_stream_params(), ff_exp2fi(), ff_h263_decode_frame(), h264_slice_header_init(), read_huffman_tree(), and truemotion1_decode_header().
ff_side_data_update_matrix_encoding()
int ff_side_data_update_matrix_encoding (AVFrame * frame, enum AVMatrixEncoding matrix_encoding)
Add or update AV_FRAME_DATA_MATRIXENCODING side data.
Definition at line 240 of file utils.c.
Referenced by ac3_decode_frame(), ff_dca_core_filter_frame(), ff_dca_lbr_filter_frame(), ff_dca_xll_filter_frame(), ff_exp2fi(), and output_data().
ff_get_format()
int ff_get_format (AVCodecContext * avctx, const enum AVPixelFormat * fmt)
Select the (possibly hardware accelerated) pixel format.
This is a wrapper around AVCodecContext.get_format() and should be used instead of calling get_format() directly.
Definition at line 1112 of file utils.c.
Referenced by cuvid_decode_init(), decode_init(), ff_exp2fi(), ff_mediacodec_dec_init(), ff_qsv_process_data(), ff_thread_get_format(), ffmmal_init_decoder(), h263_get_format(), submit_packet(), and vc1_decode_init().
ff_decode_frame_props()
int ff_decode_frame_props (AVCodecContext * avctx, AVFrame * frame)
Set various frame properties from the codec context / packet data.
Definition at line 871 of file utils.c.
Referenced by cuvid_output_frame(), ff_exp2fi(), ffmal_copy_frame(), get_buffer_internal(), raw_decode(), and reget_buffer_internal().
ff_add_cpb_side_data()
AVCPBProperties* ff_add_cpb_side_data (AVCodecContext * avctx)
Add a CPB properties side data to an encoding context.
Definition at line 4085 of file utils.c.
Referenced by ff_exp2fi(), ff_mpv_encode_init(), nvenc_setup_encoder(), qsv_retrieve_enc_params(), svc_encode_init(), vpx_init(), and X264_init().
ff_side_data_set_encoder_stats()
int ff_side_data_set_encoder_stats (AVPacket * pkt, int quality, int64_t * error, int error_count, int pict_type)
Definition at line 648 of file avpacket.c.
Referenced by dnxhd_encode_picture(), encode_frame(), ff_exp2fi(), ff_mpv_encode_picture(), process_output_surface(), storeframe(), svq1_encode_frame(), X264_frame(), XAVS_frame(), and xvid_encode_frame().
ff_alloc_a53_sei()
int ff_alloc_a53_sei (const AVFrame * frame, size_t prefix_len, void ** data, size_t * sei_size)
Check AVFrame for A53 side data and allocate and fill SEI message with A53 info.
Parameters
frame Raw frame to get A53 side data from
prefix_len Number of bytes to allocate before SEI message
data Pointer to a variable to store allocated memory Upon return the variable will hold NULL on error or if frame has no A53 info. Otherwise it will point to prefix_len uninitialized bytes followed by *sei_size SEI message
sei_size Pointer to a variable to store generated SEI message length
Returns
Zero on success, negative error code on failure
'GA94' is standard in North America for ATSC, but hard coding this style may not be the right thing to do – other formats do exist. This information is not available in the side_data so we are going with this right now.
Definition at line 4284 of file utils.c.
Referenced by ff_exp2fi(), qsv_h264_set_encode_ctrl(), vtenc_send_frame(), and X264_frame().
Variable Documentation
ff_log2_run
const uint8_t ff_log2_run[41]
Definition at line 40 of file bitstream.c.
Referenced by decode_line(), encode_line(), ls_decode_line(), ls_encode_line(), and ls_encode_run().
ff_avcodec_locked
volatile int ff_avcodec_locked
Definition at line 115 of file utils.c.
Referenced by ff_lock_avcodec(), and ff_unlock_avcodec().