FFmpeg: libavcodec/flacdsp.c File Reference
flacdsp.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/samplefmt.h"
#include "flacdsp.h"
#include "config.h"
#include "flacdsp_template.c"
#include "flacdsp_lpc_template.c"
Macros
#define SAMPLE_SIZE 16
#define PLANAR 0
#define PLANAR 1
#define SAMPLE_SIZE 32
#define PLANAR 0
#define PLANAR 1
Functions
static void flac_lpc_16_c (int32_t *decoded, const int coeffs[32], int pred_order, int qlevel, int len)
static void flac_lpc_32_c (int32_t *decoded, const int coeffs[32], int pred_order, int qlevel, int len)
av_cold void ff_flacdsp_init (FLACDSPContext *c, enum AVSampleFormat fmt, int channels, int bps)
Macro Definition Documentation
SAMPLE_SIZE [1/2]
#define SAMPLE_SIZE 16
Definition at line 37 of file flacdsp.c.
PLANAR [1/4]
#define PLANAR 0
Definition at line 43 of file flacdsp.c.
Referenced by ffprobe_show_pixel_formats().
PLANAR [2/4]
#define PLANAR 1
Definition at line 43 of file flacdsp.c.
SAMPLE_SIZE [2/2]
#define SAMPLE_SIZE 32
Definition at line 37 of file flacdsp.c.
PLANAR [3/4]
#define PLANAR 0
Definition at line 43 of file flacdsp.c.
PLANAR [4/4]
#define PLANAR 1
Definition at line 43 of file flacdsp.c.
Function Documentation
flac_lpc_16_c()
static void flac_lpc_16_c (int32_t * decoded, const int coeffs[32], int pred_order, int qlevel, int len) static
Definition at line 46 of file flacdsp.c.
Referenced by ff_flacdsp_init().
flac_lpc_32_c()
static void flac_lpc_32_c (int32_t * decoded, const int coeffs[32], int pred_order, int qlevel, int len) static
Definition at line 74 of file flacdsp.c.
Referenced by ff_flacdsp_init().
ff_flacdsp_init()
av_cold void ff_flacdsp_init (FLACDSPContext * c, enum AVSampleFormat fmt, int channels, int bps)
Definition at line 88 of file flacdsp.c.
Referenced by checkasm_check_flacdsp(), decode_frame(), flac_decode_init(), flac_encode_init(), and parse_streaminfo().