FFmpeg: libavcodec/vc1dec.c File Reference
vc1dec.c File Reference
VC-1 and WMV3 decoder.
#include "avcodec.h"
#include "blockdsp.h"
#include "get_bits.h"
#include "internal.h"
#include "mpeg_er.h"
#include "mpegvideo.h"
#include "msmpeg4.h"
#include "msmpeg4data.h"
#include "profiles.h"
#include "vc1.h"
#include "vc1data.h"
#include "vdpau_compat.h"
#include "libavutil/avassert.h"
Macros
#define transpose(x) (((x) >> 3) | (((x) & 7) << 3))
Functions
av_cold int ff_vc1_decode_init_alloc_tables (VC1Context *v)
av_cold void ff_vc1_init_transposed_scantables (VC1Context *v)
static av_cold int vc1_decode_init (AVCodecContext *avctx)
Initialize a VC1/WMV3 decoder.
av_cold int ff_vc1_decode_end (AVCodecContext *avctx)
Close a VC1/WMV3 decoder.
static int vc1_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
Decode a VC1/WMV3 frame.
Variables
static enum AVPixelFormat vc1_hwaccel_pixfmt_list_420 []
AVCodec ff_vc1_decoder
Detailed Description
VC-1 and WMV3 decoder.
Definition in file vc1dec.c.
Macro Definition Documentation
transpose
#define transpose (x) (((x) >> 3) | (((x) & 7) << 3))
Referenced by avfilter_register_all(), and ff_vc1_init_transposed_scantables().
Function Documentation
ff_vc1_decode_init_alloc_tables()
av_cold int ff_vc1_decode_init_alloc_tables (VC1Context * v)
Definition at line 324 of file vc1dec.c.
Referenced by vc1_decode_frame(), vc1_decode_init(), and wmv9_init().
ff_vc1_init_transposed_scantables()
av_cold void ff_vc1_init_transposed_scantables (VC1Context * v)
Definition at line 403 of file vc1dec.c.
Referenced by vc1_decode_init(), and wmv9_init().
vc1_decode_init()
static av_cold int vc1_decode_init (AVCodecContext * avctx) static
Initialize a VC1/WMV3 decoder.
Todo:
TODO: Handle VC-1 IDUs (Transport level?)
TODO: Decipher remaining bits in extra_data
Definition at line 422 of file vc1dec.c.
ff_vc1_decode_end()
av_cold int ff_vc1_decode_end (AVCodecContext * avctx)
Close a VC1/WMV3 decoder.
Warning
Initial try at using MpegEncContext stuff
Definition at line 587 of file vc1dec.c.
Referenced by ff_vc1_decode_init_alloc_tables(), mss2_decode_end(), vc1_decode_frame(), and vc1_decode_init().
vc1_decode_frame()
static int vc1_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Decode a VC1/WMV3 frame.
Todo:
TODO: Handle VC-1 IDUs (Transport level?)
Definition at line 622 of file vc1dec.c.
Variable Documentation
vc1_hwaccel_pixfmt_list_420
enum AVPixelFormat vc1_hwaccel_pixfmt_list_420[] static
Initial value:
= {
    AV_PIX_FMT_YUV420P,
    AV_PIX_FMT_NONE
}
Definition at line 1147 of file vc1dec.c.
ff_vc1_decoder
AVCodec ff_vc1_decoder
Initial value:
= {
    .name           = "vc1",
    .long_name      = NULL_IF_CONFIG_SMALL("SMPTE VC-1"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_VC1,
    .priv_data_size = sizeof(VC1Context),
    .init           = vc1_decode_init,
    .close          = ff_vc1_decode_end,
    .decode         = vc1_decode_frame,
    .flush          = ff_mpeg_flush,
    .capabilities   = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_DELAY,
    .pix_fmts       = vc1_hwaccel_pixfmt_list_420,
    .profiles       = NULL_IF_CONFIG_SMALL(ff_vc1_profiles)
}
Definition at line 1164 of file vc1dec.c.