FFmpeg: libavcodec/gifdec.c File Reference
gifdec.c File Reference
#include "libavutil/imgutils.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
#include "lzw.h"
#include "gif.h"
Data Structures
struct GifState
Macros
#define GIF_TRANSPARENT_COLOR 0x00ffffff
Functions
static void gif_read_palette (GifState *s, uint32_t *pal, int nb)
static void gif_fill (AVFrame *picture, uint32_t color)
static void gif_fill_rect (AVFrame *picture, uint32_t color, int l, int t, int w, int h)
static void gif_copy_img_rect (const uint32_t *src, uint32_t *dst, int linesize, int l, int t, int w, int h)
static int gif_read_image (GifState *s, AVFrame *frame)
static int gif_read_extension (GifState *s)
static int gif_read_header1 (GifState *s)
static int gif_parse_next_image (GifState *s, AVFrame *frame)
static av_cold int gif_decode_init (AVCodecContext *avctx)
static int gif_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int gif_decode_close (AVCodecContext *avctx)
Variables
static const AVOption options []
static const AVClass decoder_class
AVCodec ff_gif_decoder
Macro Definition Documentation
GIF_TRANSPARENT_COLOR
#define GIF_TRANSPARENT_COLOR 0x00ffffff
Definition at line 36 of file gifdec.c.
Function Documentation
gif_read_palette()
static void gif_read_palette (GifState * s, uint32_t * pal, int nb) static
Definition at line 79 of file gifdec.c.
Referenced by gif_read_header1(), and gif_read_image().
gif_fill()
static void gif_fill (AVFrame * picture, uint32_t color) static
Definition at line 87 of file gifdec.c.
Referenced by gif_read_image().
gif_fill_rect()
static void gif_fill_rect (AVFrame * picture, uint32_t color, int l, int t, int w, int h) static
Definition at line 96 of file gifdec.c.
Referenced by gif_read_image().
gif_copy_img_rect()
static void gif_copy_img_rect (const uint32_t * src, uint32_t * dst, int linesize, int l, int t, int w, int h) static
Definition at line 112 of file gifdec.c.
Referenced by gif_read_image().
gif_read_image()
static int gif_read_image (GifState * s, AVFrame * frame) static
Definition at line 130 of file gifdec.c.
Referenced by gif_parse_next_image().
gif_read_extension()
static int gif_read_extension (GifState * s) static
Definition at line 307 of file gifdec.c.
Referenced by gif_parse_next_image().
gif_read_header1()
static int gif_read_header1 (GifState * s) static
Definition at line 368 of file gifdec.c.
Referenced by gif_decode_frame().
gif_parse_next_image()
static int gif_parse_next_image (GifState * s, AVFrame * frame) static
Definition at line 417 of file gifdec.c.
Referenced by gif_decode_frame().
gif_decode_init()
static av_cold int gif_decode_init (AVCodecContext * avctx) static
Definition at line 443 of file gifdec.c.
gif_decode_frame()
static int gif_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 457 of file gifdec.c.
gif_decode_close()
static av_cold int gif_decode_close (AVCodecContext * avctx) static
Definition at line 524 of file gifdec.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "trans_color", "color value (ARGB) that is used instead of transparent color",
      0x42, AV_OPT_TYPE_INT,
      {.i64 = GIF_TRANSPARENT_COLOR}, 0, 0xffffffff,
      AV_OPT_FLAG_DECODING_PARAM|AV_OPT_FLAG_VIDEO_PARAM },
    { NULL },
}
Definition at line 536 of file gifdec.c.
decoder_class
const AVClass decoder_class static
Initial value:
= {
    .class_name = "gif decoder",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
    .category   = AV_CLASS_CATEGORY_DECODER,
}
Definition at line 544 of file gifdec.c.
ff_gif_decoder
AVCodec ff_gif_decoder
Initial value:
= {
    .name           = "gif",
    .long_name      = NULL_IF_CONFIG_SMALL("GIF (Graphics Interchange Format)"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_GIF,
    .priv_data_size = sizeof(GifState),
    .init           = gif_decode_init,
    .close          = gif_decode_close,
    .decode         = gif_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
    .priv_class     = &decoder_class,
}
Definition at line 552 of file gifdec.c.