FFmpeg: libavfilter/vf_blend.c File Reference
vf_blend.c File Reference
#include "libavutil/imgutils.h"
#include "libavutil/eval.h"
#include "libavutil/opt.h"
#include "libavutil/pixfmt.h"
#include "avfilter.h"
#include "bufferqueue.h"
#include "formats.h"
#include "internal.h"
#include "dualinput.h"
#include "video.h"
#include "blend.h"
Data Structures
struct BlendContext
struct ThreadData
Macros
#define TOP 0
#define BOTTOM 1
#define COMMON_OPTIONS
#define OFFSET(x) offsetof(BlendContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
#define COPY(src)
#define DEFINE_BLEND8(name, expr)
#define DEFINE_BLEND16(name, expr)
#define A top[j]
#define B bottom[j]
#define MULTIPLY(x, a, b) ((x) * (((a) * (b)) / 255))
#define SCREEN(x, a, b) (255 - (x) * ((255 - (a)) * (255 - (b)) / 255))
#define BURN(a, b) (((a) == 0) ? (a) : FFMAX(0, 255 - ((255 - (b)) << 8) / (a)))
#define DODGE(a, b) (((a) == 255) ? (a) : FFMIN(255, (((b) << 8) / (255 - (a)))))
#define MULTIPLY(x, a, b) ((x) * (((a) * (b)) / 65535))
#define SCREEN(x, a, b) (65535 - (x) * ((65535 - (a)) * (65535 - (b)) / 65535))
#define BURN(a, b) (((a) == 0) ? (a) : FFMAX(0, 65535 - ((65535 - (b)) << 16) / (a)))
#define DODGE(a, b) (((a) == 65535) ? (a) : FFMIN(65535, (((b) << 16) / (65535 - (a)))))
#define DEFINE_BLEND_EXPR(type, name, div)
Enumerations
enum {
VAR_X, VAR_Y, VAR_W, VAR_H,
VAR_SW, VAR_SH, VAR_T, VAR_N,
VAR_A, VAR_B, VAR_TOP, VAR_BOTTOM,
VAR_VARS_NB
}
Functions
AVFILTER_DEFINE_CLASS (blend)
static void blend_normal_8bit (const uint8_t *top, ptrdiff_t top_linesize, const uint8_t *bottom, ptrdiff_t bottom_linesize, uint8_t *dst, ptrdiff_t dst_linesize, ptrdiff_t width, ptrdiff_t height, FilterParams *param, double *values, int starty)
static void blend_normal_16bit (const uint8_t *_top, ptrdiff_t top_linesize, const uint8_t *_bottom, ptrdiff_t bottom_linesize, uint8_t *_dst, ptrdiff_t dst_linesize, ptrdiff_t width, ptrdiff_t height, FilterParams *param, double *values, int starty)
DEFINE_BLEND8 (multiply128, av_clip_uint8((A - 128) *B/32.+128))
static AVFrame * blend_frame (AVFilterContext *ctx, AVFrame *top_buf, const AVFrame *bottom_buf)
static av_cold int init (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
void ff_blend_init (FilterParams *param, int is_16bit)
static int config_output (AVFilterLink *outlink)
Variables
static const char *const var_names [] = { "X", "Y", "W", "H", "SW", "SH", "T", "N", "A", "B", "TOP", "BOTTOM", NULL }
static const AVOption blend_options []
Macro Definition Documentation
TOP
#define TOP 0
Definition at line 33 of file vf_blend.c.
Referenced by config_output().
BOTTOM
#define BOTTOM 1
Definition at line 34 of file vf_blend.c.
Referenced by config_output().
COMMON_OPTIONS
#define COMMON_OPTIONS
Definition at line 62 of file vf_blend.c.
Referenced by config_output().
OFFSET
#define OFFSET (x) offsetof(BlendContext, x)
Definition at line 111 of file vf_blend.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 112 of file vf_blend.c.
COPY
#define COPY (src)
Value:
static void blend_copy ## src(const uint8_t *top, ptrdiff_t top_linesize,    \
                            const uint8_t *bottom, ptrdiff_t bottom_linesize,\
                            uint8_t *dst, ptrdiff_t dst_linesize,            \
                            ptrdiff_t width, ptrdiff_t height,               \
                            FilterParams *param, double *values, int starty) \
{                                                                            \
    av_image_copy_plane(dst, dst_linesize, src, src ## _linesize,            \
                        width, height);                                 \
}
Definition at line 123 of file vf_blend.c.
DEFINE_BLEND8
#define DEFINE_BLEND8 (name, expr)
Value:
static void blend_## name##_8bit(const uint8_t *top, ptrdiff_t top_linesize,         \
                                 const uint8_t *bottom, ptrdiff_t bottom_linesize,   \
                                 uint8_t *dst, ptrdiff_t dst_linesize,               \
                                 ptrdiff_t width, ptrdiff_t height,                \
                                 FilterParams *param, double *values, int starty) \
{                                                                              \
    double opacity = param->opacity;                                           \
    int i, j;                                                                  \
                                                                               \
    for (i = 0; i < height; i++) {                                             \
        for (j = 0; j < width; j++) {                                          \
            dst[j] = top[j] + ((expr) - top[j]) * opacity;                     \
        }                                                                      \
        dst    += dst_linesize;                                                \
        top    += top_linesize;                                                \
        bottom += bottom_linesize;                                             \
    }                                                                          \
}
Definition at line 183 of file vf_blend.c.
DEFINE_BLEND16
#define DEFINE_BLEND16 (name, expr)
Value:
static void blend_## name##_16bit(const uint8_t *_top, ptrdiff_t top_linesize,       \
                                  const uint8_t *_bottom, ptrdiff_t bottom_linesize, \
                                  uint8_t *_dst, ptrdiff_t dst_linesize,             \
                                  ptrdiff_t width, ptrdiff_t height,           \
                                  FilterParams *param, double *values, int starty)         \
{                                                                              \
    const uint16_t *top = (uint16_t*)_top;                                     \
    const uint16_t *bottom = (uint16_t*)_bottom;                               \
    uint16_t *dst = (uint16_t*)_dst;                                           \
    double opacity = param->opacity;                                           \
    int i, j;                                                                  \
    dst_linesize /= 2;                                                         \
    top_linesize /= 2;                                                         \
    bottom_linesize /= 2;                                                      \
                                                                               \
    for (i = 0; i < height; i++) {                                             \
        for (j = 0; j < width; j++) {                                          \
            dst[j] = top[j] + ((expr) - top[j]) * opacity;                     \
        }                                                                      \
        dst    += dst_linesize;                                                \
        top    += top_linesize;                                                \
        bottom += bottom_linesize;                                             \
    }                                                                          \
}
Definition at line 203 of file vf_blend.c.
A
#define A top[j]
Definition at line 229 of file vf_blend.c.
B
#define B bottom[j]
Definition at line 230 of file vf_blend.c.
MULTIPLY [1/2]
#define MULTIPLY (x, a, b) ((x) * (((a) * (b)) / 255))
Definition at line 232 of file vf_blend.c.
SCREEN [1/2]
#define SCREEN (x, a, b) (255 - (x) * ((255 - (a)) * (255 - (b)) / 255))
Definition at line 233 of file vf_blend.c.
BURN [1/2]
#define BURN (a, b) (((a) == 0) ? (a) : FFMAX(0, 255 - ((255 - (b)) << 8) / (a)))
Definition at line 234 of file vf_blend.c.
DODGE [1/2]
#define DODGE (a, b) (((a) == 255) ? (a) : FFMIN(255, (((b) << 8) / (255 - (a)))))
Definition at line 235 of file vf_blend.c.
MULTIPLY [2/2]
#define MULTIPLY (x, a, b) ((x) * (((a) * (b)) / 65535))
Definition at line 232 of file vf_blend.c.
SCREEN [2/2]
#define SCREEN (x, a, b) (65535 - (x) * ((65535 - (a)) * (65535 - (b)) / 65535))
Definition at line 233 of file vf_blend.c.
BURN [2/2]
#define BURN (a, b) (((a) == 0) ? (a) : FFMAX(0, 65535 - ((65535 - (b)) << 16) / (a)))
Definition at line 234 of file vf_blend.c.
DODGE [2/2]
#define DODGE (a, b) (((a) == 65535) ? (a) : FFMIN(65535, (((b) << 16) / (65535 - (a)))))
Definition at line 235 of file vf_blend.c.
DEFINE_BLEND_EXPR
#define DEFINE_BLEND_EXPR (type, name, div)
Value:
static void blend_expr_## name(const uint8_t *_top, ptrdiff_t top_linesize,          \
                               const uint8_t *_bottom, ptrdiff_t bottom_linesize,    \
                               uint8_t *_dst, ptrdiff_t dst_linesize,                \
                               ptrdiff_t width, ptrdiff_t height,              \
                               FilterParams *param, double *values, int starty) \
{                                                                              \
    const type *top = (type*)_top;                                             \
    const type *bottom = (type*)_bottom;                                       \
    type *dst = (type*)_dst;                                                   \
    AVExpr *e = param->e;                                                      \
    int y, x;                                                                  \
    dst_linesize /= div;                                                       \
    top_linesize /= div;                                                       \
    bottom_linesize /= div;                                                    \
                                                                               \
    for (y = 0; y < height; y++) {                                             \
        values[VAR_Y] = y + starty;                                            \
        for (x = 0; x < width; x++) {                                          \
            values[VAR_X]      = x;                                            \
            values[VAR_TOP]    = values[VAR_A] = top[x];                       \
            values[VAR_BOTTOM] = values[VAR_B] = bottom[x];                    \
            dst[x] = av_expr_eval(e, values, NULL);                            \
        }                                                                      \
        dst    += dst_linesize;                                                \
        top    += top_linesize;                                                \
        bottom += bottom_linesize;                                             \
    }                                                                          \
}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
VAR_X
VAR_Y
VAR_W
VAR_H
VAR_SW
VAR_SH
VAR_T
VAR_N
VAR_A
VAR_B
VAR_TOP
VAR_BOTTOM
VAR_VARS_NB
Definition at line 51 of file vf_blend.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (blend)
Referenced by config_output().
blend_normal_8bit()
static void blend_normal_8bit (const uint8_t * top, ptrdiff_t top_linesize, const uint8_t * bottom, ptrdiff_t bottom_linesize, uint8_t * dst, ptrdiff_t dst_linesize, ptrdiff_t width, ptrdiff_t height, FilterParams * param, double * values, int starty) static
Definition at line 139 of file vf_blend.c.
Referenced by ff_blend_init().
blend_normal_16bit()
static void blend_normal_16bit (const uint8_t * _top, ptrdiff_t top_linesize, const uint8_t * _bottom, ptrdiff_t bottom_linesize, uint8_t * _dst, ptrdiff_t dst_linesize, ptrdiff_t width, ptrdiff_t height, FilterParams * param, double * values, int starty) static
Definition at line 158 of file vf_blend.c.
Referenced by ff_blend_init().
DEFINE_BLEND8()
DEFINE_BLEND8 (multiply128 , av_clip_uint8((A - 128) *B/32.+128))
Definition at line 242 of file vf_blend.c.
blend_frame()
static AVFrame* blend_frame (AVFilterContext * ctx, AVFrame * top_buf, const AVFrame * bottom_buf) static
Definition at line 372 of file vf_blend.c.
Referenced by config_output(), and init().
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 405 of file vf_blend.c.
Referenced by config_output().
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 415 of file vf_blend.c.
Referenced by config_output().
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 434 of file vf_blend.c.
Referenced by config_output().
ff_blend_init()
void ff_blend_init (FilterParams * param, int is_16bit)
Definition at line 446 of file vf_blend.c.
Referenced by config_output().
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 493 of file vf_blend.c.
Variable Documentation
var_names
const char* const var_names[] = { "X", "Y", "W", "H", "SW", "SH", "T", "N", "A", "B", "TOP", "BOTTOM", NULL } static
Definition at line 50 of file vf_blend.c.
Referenced by config_output().
blend_options
const AVOption blend_options[] static
Initial value:
= {
    COMMON_OPTIONS,
    { "shortest",    "force termination when the shortest input terminates", OFFSET(dinput.shortest), AV_OPT_TYPE_BOOL, {.i64=0}, 0, 1, FLAGS },
    { "repeatlast",  "repeat last bottom frame", OFFSET(dinput.repeatlast), AV_OPT_TYPE_BOOL, {.i64=1}, 0, 1, FLAGS },
    { NULL }
}
Definition at line 114 of file vf_blend.c.