FFmpeg: libavcodec/h263dec.c File Reference
h263dec.c File Reference
H.263 decoder.
#include "libavutil/cpu.h"
#include "avcodec.h"
#include "error_resilience.h"
#include "flv.h"
#include "h263.h"
#include "h263_parser.h"
#include "internal.h"
#include "mpeg_er.h"
#include "mpeg4video.h"
#include "mpeg4video_parser.h"
#include "mpegutils.h"
#include "mpegvideo.h"
#include "msmpeg4.h"
#include "qpeldsp.h"
#include "vdpau_compat.h"
#include "thread.h"
#include "wmv2.h"
Macros
#define UNCHECKED_BITSTREAM_READER 1
Functions
static enum AVPixelFormat h263_get_format (AVCodecContext *avctx)
av_cold int ff_h263_decode_init (AVCodecContext *avctx)
av_cold int ff_h263_decode_end (AVCodecContext *avctx)
static int get_consumed_bytes (MpegEncContext *s, int buf_size)
Return the number of bytes consumed for building the current frame.
static int decode_slice (MpegEncContext *s)
int ff_h263_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
Variables
enum AVPixelFormat ff_h263_hwaccel_pixfmt_list_420 []
AVCodec ff_h263_decoder
AVCodec ff_h263p_decoder
Detailed Description
H.263 decoder.
Definition in file h263dec.c.
Macro Definition Documentation
UNCHECKED_BITSTREAM_READER
#define UNCHECKED_BITSTREAM_READER 1
Definition at line 28 of file h263dec.c.
Function Documentation
h263_get_format()
static enum AVPixelFormat h263_get_format (AVCodecContext * avctx) static
Definition at line 48 of file h263dec.c.
Referenced by ff_h263_decode_frame(), and ff_h263_decode_init().
ff_h263_decode_init()
av_cold int ff_h263_decode_init (AVCodecContext * avctx)
Definition at line 62 of file h263dec.c.
Referenced by decode_init(), and ff_msmpeg4_decode_init().
ff_h263_decode_end()
av_cold int ff_h263_decode_end (AVCodecContext * avctx)
Definition at line 149 of file h263dec.c.
Referenced by wmv2_decode_end().
get_consumed_bytes()
static int get_consumed_bytes (MpegEncContext * s, int buf_size) static
Return the number of bytes consumed for building the current frame.
Definition at line 160 of file h263dec.c.
Referenced by ff_h263_decode_frame().
decode_slice()
static int decode_slice (MpegEncContext * s) static
Definition at line 186 of file h263dec.c.
Referenced by ff_h263_decode_frame().
ff_h263_decode_frame()
int ff_h263_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt)
Definition at line 409 of file h263dec.c.
Variable Documentation
ff_h263_hwaccel_pixfmt_list_420
enum AVPixelFormat ff_h263_hwaccel_pixfmt_list_420[]
Initial value:
= {
    AV_PIX_FMT_YUV420P,
    AV_PIX_FMT_NONE
}
Definition at line 721 of file h263dec.c.
ff_h263_decoder
AVCodec ff_h263_decoder
Initial value:
= {
    .name           = "h263",
    .long_name      = NULL_IF_CONFIG_SMALL("H.263 / H.263-1996, H.263+ / H.263-1998 / H.263 version 2"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_H263,
    .priv_data_size = sizeof(MpegEncContext),
    .init           = ff_h263_decode_init,
    .close          = ff_h263_decode_end,
    .decode         = ff_h263_decode_frame,
    .capabilities   = AV_CODEC_CAP_DRAW_HORIZ_BAND | AV_CODEC_CAP_DR1 |
                      AV_CODEC_CAP_TRUNCATED | AV_CODEC_CAP_DELAY,
    .flush          = ff_mpeg_flush,
    .max_lowres     = 3,
    .pix_fmts       = ff_h263_hwaccel_pixfmt_list_420,
}
Definition at line 735 of file h263dec.c.
ff_h263p_decoder
AVCodec ff_h263p_decoder
Initial value:
= {
    .name           = "h263p",
    .long_name      = NULL_IF_CONFIG_SMALL("H.263 / H.263-1996, H.263+ / H.263-1998 / H.263 version 2"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_H263P,
    .priv_data_size = sizeof(MpegEncContext),
    .init           = ff_h263_decode_init,
    .close          = ff_h263_decode_end,
    .decode         = ff_h263_decode_frame,
    .capabilities   = AV_CODEC_CAP_DRAW_HORIZ_BAND | AV_CODEC_CAP_DR1 |
                      AV_CODEC_CAP_TRUNCATED | AV_CODEC_CAP_DELAY,
    .flush          = ff_mpeg_flush,
    .max_lowres     = 3,
    .pix_fmts       = ff_h263_hwaccel_pixfmt_list_420,
}
Definition at line 751 of file h263dec.c.