FFmpeg: libavcodec/qsvdec.c File Reference
qsvdec.c File Reference
#include <string.h>
#include <sys/types.h>
#include <mfx/mfxvideo.h>
#include "libavutil/common.h"
#include "libavutil/hwcontext.h"
#include "libavutil/hwcontext_qsv.h"
#include "libavutil/mem.h"
#include "libavutil/log.h"
#include "libavutil/pixdesc.h"
#include "libavutil/pixfmt.h"
#include "libavutil/time.h"
#include "avcodec.h"
#include "internal.h"
#include "qsv.h"
#include "qsv_internal.h"
#include "qsvdec.h"
Functions
static int qsv_init_session (AVCodecContext *avctx, QSVContext *q, mfxSession session, AVBufferRef *hw_frames_ref)
static int qsv_decode_init (AVCodecContext *avctx, QSVContext *q)
static int alloc_frame (AVCodecContext *avctx, QSVContext *q, QSVFrame *frame)
static void qsv_clear_unused_frames (QSVContext *q)
static int get_surface (AVCodecContext *avctx, QSVContext *q, mfxFrameSurface1 **surf)
static QSVFrame * find_frame (QSVContext *q, mfxFrameSurface1 *surf)
static int qsv_decode (AVCodecContext *avctx, QSVContext *q, AVFrame *frame, int *got_frame, AVPacket *avpkt)
int ff_qsv_decode_close (QSVContext *q)
int ff_qsv_process_data (AVCodecContext *avctx, QSVContext *q, AVFrame *frame, int *got_frame, AVPacket *pkt)
void ff_qsv_decode_flush (AVCodecContext *avctx, QSVContext *q)
Function Documentation
qsv_init_session()
static int qsv_init_session (AVCodecContext * avctx, QSVContext * q, mfxSession session, AVBufferRef * hw_frames_ref) static
Definition at line 44 of file qsvdec.c.
Referenced by qsv_decode_init().
qsv_decode_init()
static int qsv_decode_init (AVCodecContext * avctx, QSVContext * q) static
Definition at line 88 of file qsvdec.c.
Referenced by ff_qsv_process_data().
alloc_frame()
static int alloc_frame (AVCodecContext * avctx, QSVContext * q, QSVFrame * frame) static
Definition at line 195 of file qsvdec.c.
Referenced by get_surface().
qsv_clear_unused_frames()
static void qsv_clear_unused_frames (QSVContext * q) static
Definition at line 218 of file qsvdec.c.
Referenced by get_surface().
get_surface()
static int get_surface (AVCodecContext * avctx, QSVContext * q, mfxFrameSurface1 ** surf) static
Definition at line 230 of file qsvdec.c.
Referenced by qsv_decode().
find_frame()
static QSVFrame* find_frame (QSVContext * q, mfxFrameSurface1 * surf) static
Definition at line 271 of file qsvdec.c.
Referenced by qsv_decode().
qsv_decode()
static int qsv_decode (AVCodecContext * avctx, QSVContext * q, AVFrame * frame, int * got_frame, AVPacket * avpkt) static
Definition at line 282 of file qsvdec.c.
Referenced by ff_qsv_process_data().
ff_qsv_decode_close()
int ff_qsv_decode_close (QSVContext * q)
Definition at line 397 of file qsvdec.c.
Referenced by qsv_decode_close().
ff_qsv_process_data()
int ff_qsv_process_data (AVCodecContext * avctx, QSVContext * q, AVFrame * frame, int * got_frame, AVPacket * pkt)
Definition at line 437 of file qsvdec.c.
Referenced by qsv_decode_frame().
ff_qsv_decode_flush()
void ff_qsv_decode_flush (AVCodecContext * avctx, QSVContext * q)
Definition at line 513 of file qsvdec.c.
Referenced by qsv_decode_flush().