FFmpeg: libavcodec/audioconvert.c File Reference
audioconvert.c File Reference
audio conversion
#include "libavutil/avstring.h"
#include "libavutil/common.h"
#include "libavutil/libm.h"
#include "libavutil/samplefmt.h"
#include "avcodec.h"
#include "audioconvert.h"
Data Structures
struct AVAudioConvert
Macros
#define CONV(ofmt, otype, ifmt, expr)
Functions
AVAudioConvert * av_audio_convert_alloc (enum AVSampleFormat out_fmt, int out_channels, enum AVSampleFormat in_fmt, int in_channels, const float *matrix, int flags)
Create an audio sample format converter context.
void av_audio_convert_free (AVAudioConvert *ctx)
Free audio sample format converter context.
int av_audio_convert (AVAudioConvert *ctx, void *const out[6], const int out_stride[6], const void *const in[6], const int in_stride[6], int len)
Convert between audio sample formats.
Detailed Description
audio conversion
Author
Michael Niedermayer micha.nosp@m.elni.nosp@m.@gmx..nosp@m.at
Definition in file audioconvert.c.
Macro Definition Documentation
CONV
#define CONV (ofmt, otype, ifmt, expr)
Value:
if(ctx->fmt_pair == ofmt + AV_SAMPLE_FMT_NB*ifmt){\
    do{\
        *(otype*)po = expr; pi += is; po += os;\
    }while(po < end);\
}
Referenced by av_audio_convert().
Function Documentation
av_audio_convert_alloc()
AVAudioConvert* av_audio_convert_alloc (enum AVSampleFormat out_fmt, int out_channels, enum AVSampleFormat in_fmt, int in_channels, const float * matrix, int flags)
Create an audio sample format converter context.
Parameters
out_fmt Output sample format
out_channels Number of output channels
in_fmt Input sample format
in_channels Number of input channels
[in] matrix Channel mixing matrix (of dimension in_channel*out_channels). Set to NULL to ignore.
flags See AV_CPU_FLAG_xx
Returns
NULL on error
Deprecated:
See libswresample
Definition at line 42 of file audioconvert.c.
Referenced by av_audio_resample_init().
av_audio_convert_free()
void av_audio_convert_free (AVAudioConvert * ctx)
Free audio sample format converter context.
Deprecated:
See libswresample
Definition at line 58 of file audioconvert.c.
Referenced by audio_resample_close(), and av_audio_resample_init().
av_audio_convert()
int av_audio_convert (AVAudioConvert * ctx, void *const out[6], const int out_stride[6], const void *const in[6], const int in_stride[6], int len)
Convert between audio sample formats.
Parameters
[in] out array of output buffers for each channel. set to NULL to ignore processing of the given channel.
[in] out_stride distance between consecutive output samples (measured in bytes)
[in] in array of input buffers for each channel
[in] in_stride distance between consecutive input samples (measured in bytes)
len length of audio frame size (measured in samples)
Deprecated:
See libswresample
Definition at line 63 of file audioconvert.c.
Referenced by audio_resample().