FFmpeg: libavcodec/h264pred.c File Reference
h264pred.c File Reference
H.264 / AVC / MPEG-4 part10 prediction functions.
#include "libavutil/attributes.h"
#include "libavutil/avassert.h"
#include "libavutil/intreadwrite.h"
#include "avcodec.h"
#include "h264pred.h"
#include "h264pred_template.c"
Macros
#define BIT_DEPTH 8
#define BIT_DEPTH 9
#define BIT_DEPTH 10
#define BIT_DEPTH 12
#define BIT_DEPTH 14
#define FUNC(a, depth) a ## _ ## depth
#define FUNCC(a, depth) a ## _ ## depth ## _c
#define FUNCD(a) a ## _c
#define H264_PRED(depth)
Functions
static void pred4x4_vertical_vp8_c (uint8_t *src, const uint8_t *topright, ptrdiff_t stride)
static void pred4x4_horizontal_vp8_c (uint8_t *src, const uint8_t *topright, ptrdiff_t stride)
static void pred4x4_down_left_svq3_c (uint8_t *src, const uint8_t *topright, ptrdiff_t stride)
static void pred4x4_down_left_rv40_c (uint8_t *src, const uint8_t *topright, ptrdiff_t stride)
static void pred4x4_down_left_rv40_nodown_c (uint8_t *src, const uint8_t *topright, ptrdiff_t stride)
static void pred4x4_vertical_left_rv40 (uint8_t *src, const uint8_t *topright, ptrdiff_t stride, const int l0, const int l1, const int l2, const int l3, const int l4)
static void pred4x4_vertical_left_rv40_c (uint8_t *src, const uint8_t *topright, ptrdiff_t stride)
static void pred4x4_vertical_left_rv40_nodown_c (uint8_t *src, const uint8_t *topright, ptrdiff_t stride)
static void pred4x4_vertical_left_vp8_c (uint8_t *src, const uint8_t *topright, ptrdiff_t stride)
static void pred4x4_horizontal_up_rv40_c (uint8_t *src, const uint8_t *topright, ptrdiff_t stride)
static void pred4x4_horizontal_up_rv40_nodown_c (uint8_t *src, const uint8_t *topright, ptrdiff_t stride)
static void pred4x4_tm_vp8_c (uint8_t *src, const uint8_t *topright, ptrdiff_t stride)
static void pred16x16_plane_svq3_c (uint8_t *src, ptrdiff_t stride)
static void pred16x16_plane_rv40_c (uint8_t *src, ptrdiff_t stride)
static void pred16x16_tm_vp8_c (uint8_t *src, ptrdiff_t stride)
static void pred8x8_left_dc_rv40_c (uint8_t *src, ptrdiff_t stride)
static void pred8x8_top_dc_rv40_c (uint8_t *src, ptrdiff_t stride)
static void pred8x8_dc_rv40_c (uint8_t *src, ptrdiff_t stride)
static void pred8x8_tm_vp8_c (uint8_t *src, ptrdiff_t stride)
av_cold void ff_h264_pred_init (H264PredContext *h, int codec_id, const int bit_depth, int chroma_format_idc)
Set the intra prediction function pointers.
Detailed Description
H.264 / AVC / MPEG-4 part10 prediction functions.
Author
Michael Niedermayer micha.nosp@m.elni.nosp@m.@gmx..nosp@m.at
Definition in file h264pred.c.
Macro Definition Documentation
BIT_DEPTH [1/5]
#define BIT_DEPTH 8
Definition at line 50 of file h264pred.c.
BIT_DEPTH [2/5]
#define BIT_DEPTH 9
Definition at line 50 of file h264pred.c.
BIT_DEPTH [3/5]
#define BIT_DEPTH 10
Definition at line 50 of file h264pred.c.
BIT_DEPTH [4/5]
#define BIT_DEPTH 12
Definition at line 50 of file h264pred.c.
BIT_DEPTH [5/5]
#define BIT_DEPTH 14
Definition at line 50 of file h264pred.c.
FUNC
#define FUNC (a, depth) a ## _ ## depth
FUNCC
#define FUNCC (a, depth) a ## _ ## depth ## _c
FUNCD
#define FUNCD (a) a ## _c
H264_PRED
#define H264_PRED (depth)
Referenced by ff_h264_pred_init().
Function Documentation
pred4x4_vertical_vp8_c()
static void pred4x4_vertical_vp8_c (uint8_t * src, const uint8_t * topright, ptrdiff_t stride) static
Definition at line 54 of file h264pred.c.
pred4x4_horizontal_vp8_c()
static void pred4x4_horizontal_vp8_c (uint8_t * src, const uint8_t * topright, ptrdiff_t stride) static
Definition at line 71 of file h264pred.c.
pred4x4_down_left_svq3_c()
static void pred4x4_down_left_svq3_c (uint8_t * src, const uint8_t * topright, ptrdiff_t stride) static
Definition at line 83 of file h264pred.c.
pred4x4_down_left_rv40_c()
static void pred4x4_down_left_rv40_c (uint8_t * src, const uint8_t * topright, ptrdiff_t stride) static
Definition at line 107 of file h264pred.c.
pred4x4_down_left_rv40_nodown_c()
static void pred4x4_down_left_rv40_nodown_c (uint8_t * src, const uint8_t * topright, ptrdiff_t stride) static
Definition at line 133 of file h264pred.c.
pred4x4_vertical_left_rv40()
static void pred4x4_vertical_left_rv40 (uint8_t * src, const uint8_t * topright, ptrdiff_t stride, const int l0, const int l1, const int l2, const int l3, const int l4) static
Definition at line 159 of file h264pred.c.
Referenced by pred4x4_vertical_left_rv40_c(), and pred4x4_vertical_left_rv40_nodown_c().
pred4x4_vertical_left_rv40_c()
static void pred4x4_vertical_left_rv40_c (uint8_t * src, const uint8_t * topright, ptrdiff_t stride) static
Definition at line 185 of file h264pred.c.
pred4x4_vertical_left_rv40_nodown_c()
static void pred4x4_vertical_left_rv40_nodown_c (uint8_t * src, const uint8_t * topright, ptrdiff_t stride) static
Definition at line 194 of file h264pred.c.
pred4x4_vertical_left_vp8_c()
static void pred4x4_vertical_left_vp8_c (uint8_t * src, const uint8_t * topright, ptrdiff_t stride) static
Definition at line 203 of file h264pred.c.
pred4x4_horizontal_up_rv40_c()
static void pred4x4_horizontal_up_rv40_c (uint8_t * src, const uint8_t * topright, ptrdiff_t stride) static
Definition at line 227 of file h264pred.c.
pred4x4_horizontal_up_rv40_nodown_c()
static void pred4x4_horizontal_up_rv40_nodown_c (uint8_t * src, const uint8_t * topright, ptrdiff_t stride) static
Definition at line 253 of file h264pred.c.
pred4x4_tm_vp8_c()
static void pred4x4_tm_vp8_c (uint8_t * src, const uint8_t * topright, ptrdiff_t stride) static
Definition at line 279 of file h264pred.c.
pred16x16_plane_svq3_c()
static void pred16x16_plane_svq3_c (uint8_t * src, ptrdiff_t stride) static
Definition at line 296 of file h264pred.c.
pred16x16_plane_rv40_c()
static void pred16x16_plane_rv40_c (uint8_t * src, ptrdiff_t stride) static
Definition at line 301 of file h264pred.c.
pred16x16_tm_vp8_c()
static void pred16x16_tm_vp8_c (uint8_t * src, ptrdiff_t stride) static
Definition at line 306 of file h264pred.c.
pred8x8_left_dc_rv40_c()
static void pred8x8_left_dc_rv40_c (uint8_t * src, ptrdiff_t stride) static
Definition at line 334 of file h264pred.c.
pred8x8_top_dc_rv40_c()
static void pred8x8_top_dc_rv40_c (uint8_t * src, ptrdiff_t stride) static
Definition at line 350 of file h264pred.c.
pred8x8_dc_rv40_c()
static void pred8x8_dc_rv40_c (uint8_t * src, ptrdiff_t stride) static
Definition at line 366 of file h264pred.c.
pred8x8_tm_vp8_c()
static void pred8x8_tm_vp8_c (uint8_t * src, ptrdiff_t stride) static
Definition at line 388 of file h264pred.c.
ff_h264_pred_init()
av_cold void ff_h264_pred_init (H264PredContext * h, int codec_id, const int bit_depth, int chroma_format_idc)
Set the intra prediction function pointers.
Definition at line 411 of file h264pred.c.
Referenced by checkasm_check_h264pred(), ff_rv34_decode_init(), h264_slice_header_init(), svq3_decode_init(), and vp78_decode_init().