FFmpeg: libavformat/gifdec.c File Reference
gifdec.c File Reference
GIF demuxer.
#include "avformat.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/opt.h"
#include "internal.h"
#include "libavcodec/gif.h"
Data Structures
struct GIFDemuxContext
Macros
#define GIF_DEFAULT_DELAY 10
Major web browsers display gifs at ~10-15fps when rate is not explicitly set or have too low values.
#define GIF_MIN_DELAY 2
By default delay values less than this threshold considered to be invalid.
Functions
static int gif_probe (AVProbeData *p)
static int resync (AVIOContext *pb)
static int gif_read_header (AVFormatContext *s)
static int gif_skip_subblocks (AVIOContext *pb)
static int gif_read_ext (AVFormatContext *s)
static int gif_read_packet (AVFormatContext *s, AVPacket *pkt)
Variables
static const AVOption options []
static const AVClass demuxer_class
AVInputFormat ff_gif_demuxer
Detailed Description
GIF demuxer.
Definition in file gifdec.c.
Macro Definition Documentation
GIF_DEFAULT_DELAY
#define GIF_DEFAULT_DELAY 10
Major web browsers display gifs at ~10-15fps when rate is not explicitly set or have too low values.
We assume default rate to be 10. Default delay = 100hundredths of second / 10fps = 10hos per frame.
Definition at line 65 of file gifdec.c.
GIF_MIN_DELAY
#define GIF_MIN_DELAY 2
By default delay values less than this threshold considered to be invalid.
Definition at line 69 of file gifdec.c.
Function Documentation
gif_probe()
static int gif_probe (AVProbeData * p) static
Definition at line 71 of file gifdec.c.
resync()
static int resync (AVIOContext * pb) static
Definition at line 84 of file gifdec.c.
Referenced by gif_read_header(), and gif_read_packet().
gif_read_header()
static int gif_read_header (AVFormatContext * s) static
Definition at line 97 of file gifdec.c.
gif_skip_subblocks()
static int gif_skip_subblocks (AVIOContext * pb) static
Definition at line 133 of file gifdec.c.
Referenced by gif_read_ext(), and gif_read_packet().
gif_read_ext()
static int gif_read_ext (AVFormatContext * s) static
Definition at line 145 of file gifdec.c.
Referenced by gif_read_packet().
gif_read_packet()
static int gif_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 200 of file gifdec.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "min_delay"    , "minimum valid delay between frames (in hundredths of second)", 0x42    , AV_OPT_TYPE_INT, {.i64 = GIF_MIN_DELAY}    , 0, 100 * 60, AV_OPT_FLAG_DECODING_PARAM },
    { "max_gif_delay", "maximum valid delay between frames (in hundredths of seconds)", 0x42   , AV_OPT_TYPE_INT, {.i64 = 65535}            , 0, 65535   , AV_OPT_FLAG_DECODING_PARAM },
    { "default_delay", "default delay between frames (in hundredths of second)"      , 0x42, AV_OPT_TYPE_INT, {.i64 = GIF_DEFAULT_DELAY}, 0, 100 * 60, AV_OPT_FLAG_DECODING_PARAM },
    { "ignore_loop"  , "ignore loop setting (netscape extension)"                    , 0x42  , AV_OPT_TYPE_BOOL,{.i64 = 1}                , 0,        1, AV_OPT_FLAG_DECODING_PARAM },
    { NULL },
}
Definition at line 321 of file gifdec.c.
demuxer_class
const AVClass demuxer_class static
Initial value:
= {
    .class_name = "GIF demuxer",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
    .category   = AV_CLASS_CATEGORY_DEMUXER,
}
Definition at line 329 of file gifdec.c.
ff_gif_demuxer
AVInputFormat ff_gif_demuxer
Initial value:
= {
    .name           = "gif",
    .long_name      = NULL_IF_CONFIG_SMALL("CompuServe Graphics Interchange Format (GIF)"),
    .priv_data_size = sizeof(GIFDemuxContext),
    .read_probe     = gif_probe,
    .read_header    = gif_read_header,
    .read_packet    = gif_read_packet,
    .flags          = AVFMT_GENERIC_INDEX,
    .priv_class     = &demuxer_class,
}
Definition at line 337 of file gifdec.c.