FFmpeg: libavcodec/videodsp.c File Reference
videodsp.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/avassert.h"
#include "libavutil/common.h"
#include "videodsp.h"
#include "videodsp_template.c"
Macros
#define BIT_DEPTH 8
#define BIT_DEPTH 16
Functions
static void just_return (uint8_t *buf, ptrdiff_t stride, int h)
av_cold void ff_videodsp_init (VideoDSPContext *ctx, int bpc)
Macro Definition Documentation
BIT_DEPTH [1/2]
#define BIT_DEPTH 8
Definition at line 30 of file videodsp.c.
BIT_DEPTH [2/2]
#define BIT_DEPTH 16
Definition at line 30 of file videodsp.c.
Function Documentation
just_return()
static void just_return (uint8_t * buf, ptrdiff_t stride, int h) static
Definition at line 34 of file videodsp.c.
Referenced by ff_videodsp_init().
ff_videodsp_init()
av_cold void ff_videodsp_init (VideoDSPContext * ctx, int bpc)
Definition at line 38 of file videodsp.c.
Referenced by checkasm_check_videodsp(), dct_init(), dirac_decode_init(), dnxhd_encode_init(), ff_cavs_init(), ff_vp56_init_context(), h264_slice_header_init(), mca(), set_sps(), svq3_decode_init(), update_size(), vp3_decode_init(), and vp78_decode_init().