FFmpeg: libavutil/file.c File Reference
file.c File Reference
#include "config.h"
#include "file.h"
#include "internal.h"
#include "log.h"
#include "mem.h"
#include <fcntl.h>
#include <sys/stat.h>
Data Structures
struct FileLogContext
Functions
int av_file_map (const char *filename, uint8_t **bufptr, size_t *size, int log_offset, void *log_ctx)
Read the file with name filename, and put its content in a newly allocated buffer or map it with mmap() when available.
void av_file_unmap (uint8_t *bufptr, size_t size)
Unmap or free the buffer bufptr created by av_file_map().
int av_tempfile (const char *prefix, char **filename, int log_offset, void *log_ctx)
Wrapper to work around the lack of mkstemp() on mingw.
Variables
static const AVClass file_log_ctx_class
Function Documentation
av_file_map()
int av_file_map (const char * filename, uint8_t ** bufptr, size_t * size, int log_offset, void * log_ctx)
Read the file with name filename, and put its content in a newly allocated buffer or map it with mmap() when available.
In case of success set *bufptr to the read or mmapped buffer, and *size to the size in bytes of the buffer in *bufptr. The returned buffer must be released with av_file_unmap().
Parameters
log_offset loglevel offset used for logging
log_ctx context used for logging
Returns
a non negative number in case of success, a negative value corresponding to an AVERROR error code in case of failure
Examples:
avio_reading.c.
Definition at line 49 of file file.c.
Referenced by init(), init_pattern_from_file(), load_textfile(), main(), parse_psfile(), and read_shape_from_file().
av_file_unmap()
void av_file_unmap (uint8_t * bufptr, size_t size)
Unmap or free the buffer bufptr created by av_file_map().
Parameters
size size in bytes of bufptr, must be the same as returned by av_file_map()
Examples:
avio_reading.c.
Definition at line 129 of file file.c.
Referenced by init(), load_textfile(), main(), parse_psfile(), read_shape_from_file(), and uninit().
av_tempfile()
int av_tempfile (const char * prefix, char ** filename, int log_offset, void * log_ctx)
Wrapper to work around the lack of mkstemp() on mingw.
Also, tries to create file in /tmp first, if possible. *prefix can be a character constant; *filename will be allocated internally.
Returns
file descriptor of opened file (or negative value corresponding to an AVERROR code on error) and opened file name in **filename.
Note
On very old libcs it is necessary to set a secure umask before calling this, av_tempfile() can't call umask itself as it is used in libraries and could interfere with the calling application.
Deprecated:
as fd numbers cannot be passed saftely between libs on some platforms
Definition at line 140 of file file.c.
Variable Documentation
file_log_ctx_class
const AVClass file_log_ctx_class static
Initial value:
= {
    "FILE", av_default_item_name, NULL, LIBAVUTIL_VERSION_INT,
    0x42, 0x42
}
Definition at line 44 of file file.c.
Referenced by av_file_map().