FFmpeg: libavcodec/h261dec.c File Reference
h261dec.c File Reference
H.261 decoder.
#include "libavutil/avassert.h"
#include "avcodec.h"
#include "mpeg_er.h"
#include "mpegutils.h"
#include "mpegvideo.h"
#include "h263.h"
#include "h261.h"
#include "internal.h"
Macros
#define H261_MBA_VLC_BITS 9
#define H261_MTYPE_VLC_BITS 6
#define H261_MV_VLC_BITS 7
#define H261_CBP_VLC_BITS 9
#define TCOEFF_VLC_BITS 9
#define MBA_STUFFING 33
#define MBA_STARTCODE 34
Functions
static av_cold void h261_decode_init_vlc (H261Context *h)
static av_cold int h261_decode_init (AVCodecContext *avctx)
static int h261_decode_gob_header (H261Context *h)
Decode the group of blocks header or slice header.
static int h261_resync (H261Context *h)
Decode the group of blocks / video packet header.
static int h261_decode_mb_skipped (H261Context *h, int mba1, int mba2)
Decode skipped macroblocks.
static int decode_mv_component (GetBitContext *gb, int v)
static int h261_decode_block (H261Context *h, int16_t *block, int n, int coded)
Decode a macroblock.
static int h261_decode_mb (H261Context *h)
static int h261_decode_picture_header (H261Context *h)
Decode the H.261 picture header.
static int h261_decode_gob (H261Context *h)
static int get_consumed_bytes (MpegEncContext *s, int buf_size)
returns the number of bytes consumed for building the current frame
static int h261_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int h261_decode_end (AVCodecContext *avctx)
Variables
static VLC h261_mba_vlc
static VLC h261_mtype_vlc
static VLC h261_mv_vlc
static VLC h261_cbp_vlc
static const int mvmap [17]
AVCodec ff_h261_decoder
Detailed Description
H.261 decoder.
Definition in file h261dec.c.
Macro Definition Documentation
H261_MBA_VLC_BITS
#define H261_MBA_VLC_BITS 9
Definition at line 37 of file h261dec.c.
Referenced by h261_decode_init_vlc(), and h261_decode_mb().
H261_MTYPE_VLC_BITS
#define H261_MTYPE_VLC_BITS 6
Definition at line 38 of file h261dec.c.
Referenced by h261_decode_init_vlc(), and h261_decode_mb().
H261_MV_VLC_BITS
#define H261_MV_VLC_BITS 7
Definition at line 39 of file h261dec.c.
Referenced by decode_mv_component(), and h261_decode_init_vlc().
H261_CBP_VLC_BITS
#define H261_CBP_VLC_BITS 9
Definition at line 40 of file h261dec.c.
Referenced by h261_decode_init_vlc(), and h261_decode_mb().
TCOEFF_VLC_BITS
#define TCOEFF_VLC_BITS 9
Definition at line 41 of file h261dec.c.
Referenced by h261_decode_block().
MBA_STUFFING
#define MBA_STUFFING 33
Definition at line 42 of file h261dec.c.
Referenced by h261_decode_gob(), and h261_decode_mb().
MBA_STARTCODE
#define MBA_STARTCODE 34
Definition at line 43 of file h261dec.c.
Referenced by h261_decode_mb().
Function Documentation
h261_decode_init_vlc()
static av_cold void h261_decode_init_vlc (H261Context * h) static
Definition at line 50 of file h261dec.c.
Referenced by h261_decode_init().
h261_decode_init()
static av_cold int h261_decode_init (AVCodecContext * avctx) static
Definition at line 72 of file h261dec.c.
h261_decode_gob_header()
static int h261_decode_gob_header (H261Context * h) static
Decode the group of blocks header or slice header.
Returns
<0 if an error occurred
Definition at line 97 of file h261dec.c.
Referenced by h261_resync().
h261_resync()
static int h261_resync (H261Context * h) static
Decode the group of blocks / video packet header.
Returns
<0 if no resync found
Definition at line 151 of file h261dec.c.
Referenced by h261_decode_frame().
h261_decode_mb_skipped()
static int h261_decode_mb_skipped (H261Context * h, int mba1, int mba2) static
Decode skipped macroblocks.
Returns
0
Definition at line 192 of file h261dec.c.
Referenced by h261_decode_gob().
decode_mv_component()
static int decode_mv_component (GetBitContext * gb, int v) static
Definition at line 236 of file h261dec.c.
Referenced by h261_decode_mb().
h261_decode_block()
static int h261_decode_block (H261Context * h, int16_t * block, int n, int coded) static
Decode a macroblock.
Returns
<0 if an error occurred
Definition at line 262 of file h261dec.c.
Referenced by h261_decode_mb().
h261_decode_mb()
static int h261_decode_mb (H261Context * h) static
Definition at line 354 of file h261dec.c.
Referenced by h261_decode_gob().
h261_decode_picture_header()
static int h261_decode_picture_header (H261Context * h) static
Decode the H.261 picture header.
Returns
<0 if no startcode found
Definition at line 478 of file h261dec.c.
Referenced by h261_decode_frame().
h261_decode_gob()
static int h261_decode_gob (H261Context * h) static
Definition at line 542 of file h261dec.c.
Referenced by h261_decode_frame().
get_consumed_bytes()
static int get_consumed_bytes (MpegEncContext * s, int buf_size) static
returns the number of bytes consumed for building the current frame
Definition at line 574 of file h261dec.c.
Referenced by h261_decode_frame().
h261_decode_frame()
static int h261_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 585 of file h261dec.c.
h261_decode_end()
static av_cold int h261_decode_end (AVCodecContext * avctx) static
Definition at line 670 of file h261dec.c.
Variable Documentation
h261_mba_vlc
VLC h261_mba_vlc static
Definition at line 45 of file h261dec.c.
h261_mtype_vlc
VLC h261_mtype_vlc static
Definition at line 46 of file h261dec.c.
h261_mv_vlc
VLC h261_mv_vlc static
Definition at line 47 of file h261dec.c.
h261_cbp_vlc
VLC h261_cbp_vlc static
Definition at line 48 of file h261dec.c.
mvmap
const int mvmap[17] static
Initial value:
= {
    0, -1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16
}
Definition at line 232 of file h261dec.c.
Referenced by decode_mv_component().
ff_h261_decoder
AVCodec ff_h261_decoder
Initial value:
= {
    .name           = "h261",
    .long_name      = NULL_IF_CONFIG_SMALL("H.261"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_H261,
    .priv_data_size = sizeof(H261Context),
    .init           = h261_decode_init,
    .close          = h261_decode_end,
    .decode         = h261_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
    .max_lowres     = 3,
}
Definition at line 679 of file h261dec.c.