FFmpeg: libavfilter/pthread.c File Reference
pthread.c File Reference
Libavfilter multithreading support.
#include "config.h"
#include "libavutil/common.h"
#include "libavutil/cpu.h"
#include "libavutil/mem.h"
#include "libavutil/thread.h"
#include "avfilter.h"
#include "internal.h"
#include "thread.h"
Data Structures
struct ThreadContext
Functions
static void *attribute_align_arg worker (void *v)
static void slice_thread_uninit (ThreadContext *c)
static void slice_thread_park_workers (ThreadContext *c)
static int thread_execute (AVFilterContext *ctx, avfilter_action_func *func, void *arg, int *ret, int nb_jobs)
static int thread_init_internal (ThreadContext *c, int nb_threads)
int ff_graph_thread_init (AVFilterGraph *graph)
void ff_graph_thread_free (AVFilterGraph *graph)
Detailed Description
Libavfilter multithreading support.
Definition in file pthread.c.
Function Documentation
worker()
static void* attribute_align_arg worker (void * v) static
Definition at line 57 of file pthread.c.
slice_thread_uninit()
static void slice_thread_uninit (ThreadContext * c) static
Definition at line 91 of file pthread.c.
Referenced by ff_graph_thread_free(), and thread_init_internal().
slice_thread_park_workers()
static void slice_thread_park_workers (ThreadContext * c) static
Definition at line 109 of file pthread.c.
Referenced by thread_execute(), and thread_init_internal().
thread_execute()
static int thread_execute (AVFilterContext * ctx, avfilter_action_func * func, void * arg, int * ret, int nb_jobs) static
Definition at line 116 of file pthread.c.
Referenced by ff_graph_thread_init().
thread_init_internal()
static int thread_init_internal (ThreadContext * c, int nb_threads) static
Definition at line 148 of file pthread.c.
Referenced by ff_graph_thread_init().
ff_graph_thread_init()
int ff_graph_thread_init (AVFilterGraph * graph)
Definition at line 193 of file pthread.c.
ff_graph_thread_free()
void ff_graph_thread_free (AVFilterGraph * graph)
Definition at line 224 of file pthread.c.