FFmpeg: libavformat/jvdec.c File Reference
jvdec.c File Reference
Bitmap Brothers JV demuxer.
#include "libavutil/channel_layout.h"
#include "libavutil/intreadwrite.h"
#include "avformat.h"
#include "internal.h"
Data Structures
struct JVFrame
struct JVDemuxContext
Macros
#define JV_PREAMBLE_SIZE 5
#define MAGIC " Compression by John M Phillips Copyright (C) 1995 The Bitmap Brothers Ltd."
Functions
static int read_probe (AVProbeData *pd)
static int read_close (AVFormatContext *s)
static int read_header (AVFormatContext *s)
static int read_packet (AVFormatContext *s, AVPacket *pkt)
static int read_seek (AVFormatContext *s, int stream_index, int64_t ts, int flags)
Variables
AVInputFormat ff_jv_demuxer
Detailed Description
Bitmap Brothers JV demuxer.
Author
Peter Ross pross.nosp@m.@xvi.nosp@m.d.org
Definition in file jvdec.c.
Macro Definition Documentation
JV_PREAMBLE_SIZE
#define JV_PREAMBLE_SIZE 5
Definition at line 34 of file jvdec.c.
Referenced by read_packet().
MAGIC
#define MAGIC " Compression by John M Phillips Copyright (C) 1995 The Bitmap Brothers Ltd."
Definition at line 53 of file jvdec.c.
Referenced by read_probe().
Function Documentation
read_probe()
static int read_probe (AVProbeData * pd) static
Definition at line 55 of file jvdec.c.
Referenced by amr_read_packet(), ff_rtsp_open_transport_ctx(), mmf_read_packet(), and set_spdif().
read_close()
static int read_close (AVFormatContext * s) static
Definition at line 63 of file jvdec.c.
Referenced by read_header().
read_header()
static int read_header (AVFormatContext * s) static
Definition at line 72 of file jvdec.c.
read_packet()
static int read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 163 of file jvdec.c.
read_seek()
static int read_seek (AVFormatContext * s, int stream_index, int64_t ts, int flags) static
Definition at line 223 of file jvdec.c.
Variable Documentation
ff_jv_demuxer
AVInputFormat ff_jv_demuxer
Initial value:
= {
    .name           = "jv",
    .long_name      = NULL_IF_CONFIG_SMALL("Bitmap Brothers JV"),
    .priv_data_size = sizeof(JVDemuxContext),
    .read_probe     = read_probe,
    .read_header    = read_header,
    .read_packet    = read_packet,
    .read_seek      = read_seek,
    .read_close     = read_close,
}
Definition at line 254 of file jvdec.c.