FFmpeg: libavcodec/dnxhddec.c File Reference
dnxhddec.c File Reference
#include "libavutil/imgutils.h"
#include "libavutil/timer.h"
#include "avcodec.h"
#include "blockdsp.h"
#include "get_bits.h"
#include "dnxhddata.h"
#include "idctdsp.h"
#include "internal.h"
#include "profiles.h"
#include "thread.h"
Data Structures
struct RowContext
struct DNXHDContext
Macros
#define UNCHECKED_BITSTREAM_READER 1
#define DNXHD_VLC_BITS 9
#define DNXHD_DC_VLC_BITS 7
Functions
static int dnxhd_decode_dct_block_8 (const DNXHDContext *ctx, RowContext *row, int n)
static int dnxhd_decode_dct_block_10 (const DNXHDContext *ctx, RowContext *row, int n)
static int dnxhd_decode_dct_block_10_444 (const DNXHDContext *ctx, RowContext *row, int n)
static int dnxhd_decode_dct_block_12 (const DNXHDContext *ctx, RowContext *row, int n)
static int dnxhd_decode_dct_block_12_444 (const DNXHDContext *ctx, RowContext *row, int n)
static av_cold int dnxhd_decode_init (AVCodecContext *avctx)
static int dnxhd_init_vlc (DNXHDContext *ctx, uint32_t cid, int bitdepth)
static av_cold int dnxhd_decode_init_thread_copy (AVCodecContext *avctx)
static int dnxhd_get_profile (int cid)
static int dnxhd_decode_header (DNXHDContext *ctx, AVFrame *frame, const uint8_t *buf, int buf_size, int first_field)
static av_always_inline int dnxhd_decode_dct_block (const DNXHDContext *ctx, RowContext *row, int n, int index_bits, int level_bias, int level_shift, int dc_shift)
static int dnxhd_decode_macroblock (const DNXHDContext *ctx, RowContext *row, AVFrame *frame, int x, int y)
static int dnxhd_decode_row (AVCodecContext *avctx, void *data, int rownb, int threadnb)
static int dnxhd_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int dnxhd_decode_close (AVCodecContext *avctx)
Variables
AVCodec ff_dnxhd_decoder
Macro Definition Documentation
UNCHECKED_BITSTREAM_READER
#define UNCHECKED_BITSTREAM_READER 1
Definition at line 31 of file dnxhddec.c.
DNXHD_VLC_BITS
#define DNXHD_VLC_BITS 9
Definition at line 76 of file dnxhddec.c.
Referenced by dnxhd_decode_dct_block(), and dnxhd_init_vlc().
DNXHD_DC_VLC_BITS
#define DNXHD_DC_VLC_BITS 7
Definition at line 77 of file dnxhddec.c.
Referenced by dnxhd_decode_dct_block(), and dnxhd_init_vlc().
Function Documentation
dnxhd_decode_dct_block_8()
static int dnxhd_decode_dct_block_8 (const DNXHDContext * ctx, RowContext * row, int n) static
Definition at line 429 of file dnxhddec.c.
Referenced by dnxhd_decode_header().
dnxhd_decode_dct_block_10()
static int dnxhd_decode_dct_block_10 (const DNXHDContext * ctx, RowContext * row, int n) static
Definition at line 435 of file dnxhddec.c.
Referenced by dnxhd_decode_header().
dnxhd_decode_dct_block_10_444()
static int dnxhd_decode_dct_block_10_444 (const DNXHDContext * ctx, RowContext * row, int n) static
Definition at line 441 of file dnxhddec.c.
Referenced by dnxhd_decode_header().
dnxhd_decode_dct_block_12()
static int dnxhd_decode_dct_block_12 (const DNXHDContext * ctx, RowContext * row, int n) static
Definition at line 447 of file dnxhddec.c.
Referenced by dnxhd_decode_header().
dnxhd_decode_dct_block_12_444()
static int dnxhd_decode_dct_block_12_444 (const DNXHDContext * ctx, RowContext * row, int n) static
Definition at line 453 of file dnxhddec.c.
Referenced by dnxhd_decode_header().
dnxhd_decode_init()
static av_cold int dnxhd_decode_init (AVCodecContext * avctx) static
Definition at line 90 of file dnxhddec.c.
dnxhd_init_vlc()
static int dnxhd_init_vlc (DNXHDContext * ctx, uint32_t cid, int bitdepth) static
Definition at line 108 of file dnxhddec.c.
Referenced by dnxhd_decode_header().
dnxhd_decode_init_thread_copy()
static av_cold int dnxhd_decode_init_thread_copy (AVCodecContext * avctx) static
Definition at line 144 of file dnxhddec.c.
dnxhd_get_profile()
static int dnxhd_get_profile (int cid) static
Definition at line 158 of file dnxhddec.c.
Referenced by dnxhd_decode_header().
dnxhd_decode_header()
static int dnxhd_decode_header (DNXHDContext * ctx, AVFrame * frame, const uint8_t * buf, int buf_size, int first_field) static
Definition at line 175 of file dnxhddec.c.
Referenced by dnxhd_decode_frame().
dnxhd_decode_dct_block()
static av_always_inline int dnxhd_decode_dct_block (const DNXHDContext * ctx, RowContext * row, int n, int index_bits, int level_bias, int level_shift, int dc_shift) static
Definition at line 328 of file dnxhddec.c.
Referenced by dnxhd_decode_dct_block_10(), dnxhd_decode_dct_block_10_444(), dnxhd_decode_dct_block_12(), dnxhd_decode_dct_block_12_444(), and dnxhd_decode_dct_block_8().
dnxhd_decode_macroblock()
static int dnxhd_decode_macroblock (const DNXHDContext * ctx, RowContext * row, AVFrame * frame, int x, int y) static
Definition at line 459 of file dnxhddec.c.
Referenced by dnxhd_decode_row().
dnxhd_decode_row()
static int dnxhd_decode_row (AVCodecContext * avctx, void * data, int rownb, int threadnb) static
Definition at line 561 of file dnxhddec.c.
Referenced by dnxhd_decode_frame().
dnxhd_decode_frame()
static int dnxhd_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 586 of file dnxhddec.c.
dnxhd_decode_close()
static av_cold int dnxhd_decode_close (AVCodecContext * avctx) static
Definition at line 686 of file dnxhddec.c.
Variable Documentation
ff_dnxhd_decoder
AVCodec ff_dnxhd_decoder
Initial value:
= {
    .name           = "dnxhd",
    .long_name      = NULL_IF_CONFIG_SMALL("VC3/DNxHD"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_DNXHD,
    .priv_data_size = sizeof(DNXHDContext),
    .init           = dnxhd_decode_init,
    .close          = dnxhd_decode_close,
    .decode         = dnxhd_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_FRAME_THREADS |
                      AV_CODEC_CAP_SLICE_THREADS,
    .init_thread_copy = ONLY_IF_THREADS_ENABLED(dnxhd_decode_init_thread_copy),
    .profiles       = NULL_IF_CONFIG_SMALL(ff_dnxhd_profiles),
}
Definition at line 699 of file dnxhddec.c.