FFmpeg: libavcodec/diracdec.c File Reference
diracdec.c File Reference
Dirac Decoder.
#include "avcodec.h"
#include "get_bits.h"
#include "bytestream.h"
#include "internal.h"
#include "golomb.h"
#include "dirac_arith.h"
#include "dirac_vlc.h"
#include "mpeg12data.h"
#include "libavcodec/mpegvideo.h"
#include "mpegvideoencdsp.h"
#include "dirac_dwt.h"
#include "dirac.h"
#include "diractab.h"
#include "diracdsp.h"
#include "videodsp.h"
Data Structures
struct DiracFrame
struct DiracBlock
struct SubBand
struct Plane
struct DiracSlice
struct DiracContext
struct SliceCoeffs
Macros
#define MAX_REFERENCE_FRAMES 8
The spec limits this to 3 for frame coding, but in practice can be as high as 6.
#define MAX_DELAY 5 /* limit for main profile for frame coding (TODO: field coding) */
#define MAX_FRAMES (MAX_REFERENCE_FRAMES + MAX_DELAY + 1)
#define MAX_QUANT 255 /* max quant for VC-2 */
#define MAX_BLOCKSIZE 32 /* maximum xblen/yblen we support */
#define DIRAC_REF_MASK_REF1 1
DiracBlock->ref flags, if set then the block does MC from the given ref.
#define DIRAC_REF_MASK_REF2 2
#define DIRAC_REF_MASK_GLOBAL 4
#define DELAYED_PIC_REF 4
Value of Picture.reference when Picture is not a reference picture, but is held for delayed output.
#define CALC_PADDING(size, depth) (((size + (1 << depth) - 1) >> depth) << depth)
#define DIVRNDUP(a, b) (((a) + (b) - 1) / (b))
#define SIGN_CTX(x) (CTX_SIGN_ZERO + ((x) > 0) - ((x) < 0))
#define UNPACK_ARITH(n, type)
#define INTRA_DC_PRED(n, type)
Dirac Specification -> 13.3 intra_dc_prediction(band)
#define PARSE_VALUES(type, x, gb, ebits, buf1, buf2)
#define CHECKEDREAD(dst, cond, errmsg)
#define ROLLOFF(i)
#define DATA_UNIT_HEADER_SIZE 13
Dirac Specification -> 9.6 Parse Info Header Syntax.
Enumerations
enum dirac_subband {
subband_ll = 0, subband_hl = 1, subband_lh = 2, subband_hh = 3,
subband_nb
}
Functions
static int divide3 (int x)
static DiracFrame * remove_frame (DiracFrame *framelist[], int picnum)
static int add_frame (DiracFrame *framelist[], int maxframes, DiracFrame *frame)
static int alloc_sequence_buffers (DiracContext *s)
static int alloc_buffers (DiracContext *s, int stride)
static void free_sequence_buffers (DiracContext *s)
static av_cold int dirac_decode_init (AVCodecContext *avctx)
static void dirac_decode_flush (AVCodecContext *avctx)
static av_cold int dirac_decode_end (AVCodecContext *avctx)
static int coeff_unpack_golomb (GetBitContext *gb, int qfactor, int qoffset)
static void codeblock (DiracContext *s, SubBand *b, GetBitContext *gb, DiracArith *c, int left, int right, int top, int bottom, int blockcnt_one, int is_arith)
Decode the coeffs in the rectangle defined by left, right, top, bottom [DIRAC_STD] 13.4.3.2 Codeblock unpacking loop.
static av_always_inline void decode_subband_internal (DiracContext *s, SubBand *b, int is_arith)
Dirac Specification -> 13.4.2 Non-skipped subbands.
static int decode_subband_arith (AVCodecContext *avctx, void *b)
static int decode_subband_golomb (AVCodecContext *avctx, void *arg)
static void decode_component (DiracContext *s, int comp)
Dirac Specification -> [DIRAC_STD] 13.4.1 core_transform_data()
static void decode_subband (DiracContext *s, GetBitContext *gb, int quant, int slice_x, int slice_y, int bits_end, SubBand *b1, SubBand *b2)
static int decode_lowdelay_slice (AVCodecContext *avctx, void *arg)
Dirac Specification -> 13.5.2 Slices.
static int subband_coeffs (DiracContext *s, int x, int y, int p, SliceCoeffs c[MAX_DWT_LEVELS])
static int decode_hq_slice (DiracContext *s, DiracSlice *slice, uint8_t *tmp_buf)
VC-2 Specification -> 13.5.3 hq_slice(sx,sy)
static int decode_hq_slice_row (AVCodecContext *avctx, void *arg, int jobnr, int threadnr)
static int decode_lowdelay (DiracContext *s)
Dirac Specification -> 13.5.1 low_delay_transform_data()
static void init_planes (DiracContext *s)
static int dirac_unpack_prediction_parameters (DiracContext *s)
Unpack the motion compensation parameters Dirac Specification -> 11.2 Picture prediction data.
static int dirac_unpack_idwt_params (DiracContext *s)
Dirac Specification -> 11.3 Wavelet transform data.
static int pred_sbsplit (uint8_t *sbsplit, int stride, int x, int y)
static int pred_block_mode (DiracBlock *block, int stride, int x, int y, int refmask)
static void pred_block_dc (DiracBlock *block, int stride, int x, int y)
static void pred_mv (DiracBlock *block, int stride, int x, int y, int ref)
static void global_mv (DiracContext *s, DiracBlock *block, int x, int y, int ref)
static void decode_block_params (DiracContext *s, DiracArith arith[8], DiracBlock *block, int stride, int x, int y)
static void propagate_block_data (DiracBlock *block, int stride, int size)
Copies the current block to the other blocks covered by the current superblock split mode.
static int dirac_unpack_block_motion_data (DiracContext *s)
Dirac Specification ->
static int weight (int i, int blen, int offset)
static void init_obmc_weight_row (Plane *p, uint8_t *obmc_weight, int stride, int left, int right, int wy)
static void init_obmc_weight (Plane *p, uint8_t *obmc_weight, int stride, int left, int right, int top, int bottom)
static void init_obmc_weights (DiracContext *s, Plane *p, int by)
static int mc_subpel (DiracContext *s, DiracBlock *block, const uint8_t *src[5], int x, int y, int ref, int plane)
For block x,y, determine which of the hpel planes to do bilinear interpolation from and set src[] to the location in each hpel plane to MC from.
static void add_dc (uint16_t *dst, int dc, int stride, uint8_t *obmc_weight, int xblen, int yblen)
static void block_mc (DiracContext *s, DiracBlock *block, uint16_t *mctmp, uint8_t *obmc_weight, int plane, int dstx, int dsty)
static void mc_row (DiracContext *s, DiracBlock *block, uint16_t *mctmp, int plane, int dsty)
static void select_dsp_funcs (DiracContext *s, int width, int height, int xblen, int yblen)
static int interpolate_refplane (DiracContext *s, DiracFrame *ref, int plane, int width, int height)
static int dirac_decode_frame_internal (DiracContext *s)
Dirac Specification -> 13.0 Transform data syntax.
static int get_buffer_with_edge (AVCodecContext *avctx, AVFrame *f, int flags)
static int dirac_decode_picture_header (DiracContext *s)
Dirac Specification -> 11.1.1 Picture Header.
static int get_delayed_pic (DiracContext *s, AVFrame *picture, int *got_frame)
static int dirac_decode_data_unit (AVCodecContext *avctx, const uint8_t *buf, int size)
static int dirac_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *pkt)
Variables
static const uint8_t epel_weights [4][4][4]
AVCodec ff_dirac_decoder
Detailed Description
Dirac Decoder.
Author
Marco Gerards marco.nosp@m.@gnu.nosp@m..org, David Conrad, Jordi Ortiz nenjo.nosp@m.rdi@.nosp@m.gmail.nosp@m..com
Definition in file diracdec.c.
Macro Definition Documentation
MAX_REFERENCE_FRAMES
#define MAX_REFERENCE_FRAMES 8
The spec limits this to 3 for frame coding, but in practice can be as high as 6.
Definition at line 48 of file diracdec.c.
Referenced by dirac_decode_picture_header().
MAX_DELAY
#define MAX_DELAY 5 /* limit for main profile for frame coding (TODO: field coding) */
Definition at line 49 of file diracdec.c.
Referenced by dirac_decode_frame().
MAX_FRAMES
#define MAX_FRAMES (MAX_REFERENCE_FRAMES + MAX_DELAY + 1)
Definition at line 50 of file diracdec.c.
Referenced by dirac_decode_data_unit(), dirac_decode_end(), dirac_decode_frame(), dirac_decode_init(), dirac_decode_picture_header(), ff_opus_parse_packet(), and free_sequence_buffers().
MAX_QUANT
#define MAX_QUANT 255 /* max quant for VC-2 */
Definition at line 51 of file diracdec.c.
MAX_BLOCKSIZE
#define MAX_BLOCKSIZE 32 /* maximum xblen/yblen we support */
Definition at line 52 of file diracdec.c.
Referenced by add_dc(), alloc_buffers(), alloc_sequence_buffers(), dirac_unpack_prediction_parameters(), filter_channel(), init_obmc_weights(), mlp_encode_frame(), mlp_filter_channel(), and read_major_sync().
DIRAC_REF_MASK_REF1
#define DIRAC_REF_MASK_REF1 1
DiracBlock->ref flags, if set then the block does MC from the given ref.
Definition at line 57 of file diracdec.c.
Referenced by decode_block_params().
DIRAC_REF_MASK_REF2
#define DIRAC_REF_MASK_REF2 2
Definition at line 58 of file diracdec.c.
Referenced by decode_block_params().
DIRAC_REF_MASK_GLOBAL
#define DIRAC_REF_MASK_GLOBAL 4
Definition at line 59 of file diracdec.c.
Referenced by decode_block_params(), and pred_mv().
DELAYED_PIC_REF
#define DELAYED_PIC_REF 4
Value of Picture.reference when Picture is not a reference picture, but is held for delayed output.
Definition at line 65 of file diracdec.c.
Referenced by decode_postinit(), dirac_decode_frame(), dirac_decode_picture_header(), get_delayed_pic(), h264_decode_frame(), h264_field_start(), pic_is_unused(), and unreference_pic().
CALC_PADDING
#define CALC_PADDING (size, depth) (((size + (1 << depth) - 1) >> depth) << depth)
Definition at line 67 of file diracdec.c.
Referenced by alloc_sequence_buffers(), and init_planes().
DIVRNDUP
#define DIVRNDUP (a, b) (((a) + (b) - 1) / (b))
Definition at line 70 of file diracdec.c.
Referenced by alloc_sequence_buffers(), and dirac_unpack_block_motion_data().
SIGN_CTX
#define SIGN_CTX (x) (CTX_SIGN_ZERO + ((x) > 0) - ((x) < 0))
Definition at line 445 of file diracdec.c.
UNPACK_ARITH
#define UNPACK_ARITH (n, type)
Value:
static inline void coeff_unpack_arith_##n(DiracArith *c, int qfactor, int qoffset, \
                                              SubBand *b, type *buf, int x, int y) \
    { \
        int coeff, sign, sign_pred = 0, pred_ctx = CTX_ZPZN_F1; \
        const int mstride = -(b->stride >> (1+b->pshift)); \
        if (b->parent) { \
            const type *pbuf = (type *)b->parent->ibuf; \
            const int stride = b->parent->stride >> (1+b->parent->pshift); \
            pred_ctx += !!pbuf[stride * (y>>1) + (x>>1)] << 1; \
        } \
        if (b->orientation == subband_hl) \
            sign_pred = buf[mstride]; \
        if (x) { \
            pred_ctx += !(buf[-1] | buf[mstride] | buf[-1 + mstride]); \
            if (b->orientation == subband_lh) \
                sign_pred = buf[-1]; \
        } else { \
            pred_ctx += !buf[mstride]; \
        } \
        coeff = dirac_get_arith_uint(c, pred_ctx, CTX_COEFF_DATA); \
        if (coeff) { \
            coeff = (coeff * qfactor + qoffset) >> 2; \
            sign  = dirac_get_arith_bit(c, SIGN_CTX(sign_pred)); \
            coeff = (coeff ^ -sign) + sign; \
        } \
        *buf = coeff; \
    } \
Definition at line 447 of file diracdec.c.
INTRA_DC_PRED
#define INTRA_DC_PRED (n, type)
Value:
static inline void intra_dc_prediction_##n(SubBand *b) \
    { \
        type *buf = (type*)b->ibuf; \
        int x, y; \
        \
        for (x = 1; x < b->width; x++) \
            buf[x] += buf[x-1]; \
        buf += (b->stride >> (1+b->pshift)); \
        \
        for (y = 1; y < b->height; y++) { \
            buf[0] += buf[-(b->stride >> (1+b->pshift))]; \
            \
            for (x = 1; x < b->width; x++) { \
                int pred = buf[x - 1] + buf[x - (b->stride >> (1+b->pshift))] + buf[x - (b->stride >> (1+b->pshift))-1]; \
                buf[x]  += divide3(pred); \
            } \
            buf += (b->stride >> (1+b->pshift)); \
        } \
    } \
Dirac Specification -> 13.3 intra_dc_prediction(band)
Definition at line 560 of file diracdec.c.
PARSE_VALUES
#define PARSE_VALUES (type, x, gb, ebits, buf1, buf2)
Value:
type *buf = (type *)buf1; \
    buf[x] = coeff_unpack_golomb(gb, qfactor, qoffset); \
    if (get_bits_count(gb) >= ebits) \
        return; \
    if (buf2) { \
        buf = (type *)buf2; \
        buf[x] = coeff_unpack_golomb(gb, qfactor, qoffset); \
        if (get_bits_count(gb) >= ebits) \
            return; \
    } \
Definition at line 679 of file diracdec.c.
Referenced by decode_subband().
CHECKEDREAD
#define CHECKEDREAD (dst, cond, errmsg)
Value:
tmp = get_interleaved_ue_golomb(gb); \
    if (cond) { \
        av_log(s->avctx, AV_LOG_ERROR, errmsg); \
        return AVERROR_INVALIDDATA; \
    }\
    dst = tmp;
Referenced by dirac_unpack_idwt_params().
ROLLOFF
#define ROLLOFF (i)
Value:
offset == 1 ? ((i) ? 5 : 3) :        \
    (1 + (6*(i) + offset - 1) / (2*offset - 1))
Referenced by weight().
DATA_UNIT_HEADER_SIZE
#define DATA_UNIT_HEADER_SIZE 13
Dirac Specification -> 9.6 Parse Info Header Syntax.
parse_info() 4 byte start code + byte parse code + 4 byte size + 4 byte previous size
Definition at line 2057 of file diracdec.c.
Referenced by dirac_decode_data_unit(), and dirac_decode_frame().
Enumeration Type Documentation
dirac_subband
enum dirac_subband
Enumerator
subband_ll
subband_hl
subband_lh
subband_hh
subband_nb
Definition at line 240 of file diracdec.c.
Function Documentation
divide3()
static int divide3 (int x) inline static
Definition at line 249 of file diracdec.c.
Referenced by pred_block_dc().
remove_frame()
static DiracFrame* remove_frame (DiracFrame * framelist[], int picnum) static
Definition at line 254 of file diracdec.c.
Referenced by dirac_decode_frame(), and dirac_decode_picture_header().
add_frame()
static int add_frame (DiracFrame * framelist[], int maxframes, DiracFrame * frame) static
Definition at line 272 of file diracdec.c.
Referenced by dirac_decode_frame(), and dirac_decode_picture_header().
alloc_sequence_buffers()
static int alloc_sequence_buffers (DiracContext * s) static
Definition at line 283 of file diracdec.c.
Referenced by dirac_decode_data_unit().
alloc_buffers()
static int alloc_buffers (DiracContext * s, int stride) static
Definition at line 321 of file diracdec.c.
Referenced by dirac_decode_data_unit().
free_sequence_buffers()
static void free_sequence_buffers (DiracContext * s) static
Definition at line 350 of file diracdec.c.
Referenced by dirac_decode_data_unit(), and dirac_decode_flush().
dirac_decode_init()
static av_cold int dirac_decode_init (AVCodecContext * avctx) static
Definition at line 382 of file diracdec.c.
dirac_decode_flush()
static void dirac_decode_flush (AVCodecContext * avctx) static
Definition at line 411 of file diracdec.c.
Referenced by dirac_decode_end().
dirac_decode_end()
static av_cold int dirac_decode_end (AVCodecContext * avctx) static
Definition at line 419 of file diracdec.c.
coeff_unpack_golomb()
static int coeff_unpack_golomb (GetBitContext * gb, int qfactor, int qoffset) inline static
Definition at line 436 of file diracdec.c.
Referenced by codeblock().
codeblock()
static void codeblock (DiracContext * s, SubBand * b, GetBitContext * gb, DiracArith * c, int left, int right, int top, int bottom, int blockcnt_one, int is_arith) inline static
Decode the coeffs in the rectangle defined by left, right, top, bottom [DIRAC_STD] 13.4.3.2 Codeblock unpacking loop.
codeblock()
Definition at line 483 of file diracdec.c.
Referenced by decode_subband_internal().
decode_subband_internal()
static av_always_inline void decode_subband_internal (DiracContext * s, SubBand * b, int is_arith) static
Dirac Specification -> 13.4.2 Non-skipped subbands.
subband_coeffs()
Definition at line 588 of file diracdec.c.
Referenced by decode_subband_arith(), and decode_subband_golomb().
decode_subband_arith()
static int decode_subband_arith (AVCodecContext * avctx, void * b) static
Definition at line 626 of file diracdec.c.
Referenced by decode_component().
decode_subband_golomb()
static int decode_subband_golomb (AVCodecContext * avctx, void * arg) static
Definition at line 633 of file diracdec.c.
Referenced by decode_component().
decode_component()
static void decode_component (DiracContext * s, int comp) static
Dirac Specification -> [DIRAC_STD] 13.4.1 core_transform_data()
Definition at line 645 of file diracdec.c.
Referenced by dirac_decode_frame_internal().
decode_subband()
static void decode_subband (DiracContext * s, GetBitContext * gb, int quant, int slice_x, int slice_y, int bits_end, SubBand * b1, SubBand * b2) static
Definition at line 691 of file diracdec.c.
Referenced by decode_lowdelay_slice().
decode_lowdelay_slice()
static int decode_lowdelay_slice (AVCodecContext * avctx, void * arg) static
Dirac Specification -> 13.5.2 Slices.
slice(sx,sy)
Definition at line 743 of file diracdec.c.
Referenced by decode_lowdelay().
subband_coeffs()
static int subband_coeffs (DiracContext * s, int x, int y, int p, SliceCoeffs c[MAX_DWT_LEVELS]) static
Definition at line 789 of file diracdec.c.
Referenced by decode_hq_slice(), and decode_lowdelay().
decode_hq_slice()
static int decode_hq_slice (DiracContext * s, DiracSlice * slice, uint8_t * tmp_buf) static
VC-2 Specification -> 13.5.3 hq_slice(sx,sy)
Definition at line 810 of file diracdec.c.
Referenced by decode_hq_slice_row().
decode_hq_slice_row()
static int decode_hq_slice_row (AVCodecContext * avctx, void * arg, int jobnr, int threadnr) static
Definition at line 884 of file diracdec.c.
Referenced by decode_lowdelay().
decode_lowdelay()
static int decode_lowdelay (DiracContext * s) static
Dirac Specification -> 13.5.1 low_delay_transform_data()
Definition at line 899 of file diracdec.c.
Referenced by dirac_decode_frame_internal().
init_planes()
static void init_planes (DiracContext * s) static
Definition at line 1013 of file diracdec.c.
Referenced by dirac_decode_picture_header().
dirac_unpack_prediction_parameters()
static int dirac_unpack_prediction_parameters (DiracContext * s) static
Unpack the motion compensation parameters Dirac Specification -> 11.2 Picture prediction data.
picture_prediction()
Definition at line 1067 of file diracdec.c.
Referenced by dirac_decode_picture_header().
dirac_unpack_idwt_params()
static int dirac_unpack_idwt_params (DiracContext * s) static
Dirac Specification -> 11.3 Wavelet transform data.
wavelet_transform()
Definition at line 1186 of file diracdec.c.
Referenced by dirac_decode_picture_header().
pred_sbsplit()
static int pred_sbsplit (uint8_t * sbsplit, int stride, int x, int y) inline static
Definition at line 1278 of file diracdec.c.
Referenced by dirac_unpack_block_motion_data().
pred_block_mode()
static int pred_block_mode (DiracBlock * block, int stride, int x, int y, int refmask) inline static
Definition at line 1292 of file diracdec.c.
Referenced by decode_block_params().
pred_block_dc()
static void pred_block_dc (DiracBlock * block, int stride, int x, int y) inline static
Definition at line 1308 of file diracdec.c.
Referenced by decode_block_params().
pred_mv()
static void pred_mv (DiracBlock * block, int stride, int x, int y, int ref) inline static
Definition at line 1341 of file diracdec.c.
Referenced by decode_block_params(), decode_q_branch(), encode_q_branch(), encode_q_branch2(), and get_block_bits().
global_mv()
static void global_mv (DiracContext * s, DiracBlock * block, int x, int y, int ref) static
Definition at line 1377 of file diracdec.c.
Referenced by decode_block_params().
decode_block_params()
static void decode_block_params (DiracContext * s, DiracArith arith[8], DiracBlock * block, int stride, int x, int y) static
Definition at line 1393 of file diracdec.c.
Referenced by dirac_unpack_block_motion_data().
propagate_block_data()
static void propagate_block_data (DiracBlock * block, int stride, int size) static
Copies the current block to the other blocks covered by the current superblock split mode.
Definition at line 1433 of file diracdec.c.
Referenced by dirac_unpack_block_motion_data().
dirac_unpack_block_motion_data()
static int dirac_unpack_block_motion_data (DiracContext * s) static
Dirac Specification ->
Block motion data syntax
Definition at line 1452 of file diracdec.c.
Referenced by dirac_decode_picture_header().
weight()
static int weight (int i, int blen, int offset) static
Definition at line 1507 of file diracdec.c.
Referenced by apply_delogo(), check_decorrelate_stereo(), dv_init_enc_block(), encode_mb_internal(), ff_h264_biweight_pixels4_8_mmi(), ff_h264_weight_pixels16_8_mmi(), ff_h264_weight_pixels4_8_mmi(), ff_lpc_calc_coefs(), ff_lpc_calc_ref_coefs_f(), find_form_factor(), guess_dc(), hevc_biwgt_copy_12w_msa(), hevc_biwgt_copy_16multx4mult_msa(), hevc_biwgt_copy_4w_msa(), hevc_biwgt_copy_6w_msa(), hevc_biwgt_copy_8w_msa(), hevc_hv_biwgt_4t_4multx8mult_msa(), hevc_hv_biwgt_4t_4x2_msa(), hevc_hv_biwgt_4t_4x4_msa(), hevc_hv_biwgt_4t_6w_msa(), hevc_hv_biwgt_4t_8multx4mult_msa(), hevc_hv_biwgt_4t_8x2_msa(), hevc_hv_biwgt_4t_8x6_msa(), hevc_hz_biwgt_4t_12w_msa(), hevc_hz_biwgt_4t_16w_msa(), hevc_hz_biwgt_4t_24w_msa(), hevc_hz_biwgt_4t_32w_msa(), hevc_hz_biwgt_4t_4x2_msa(), hevc_hz_biwgt_4t_4x4_msa(), hevc_hz_biwgt_4t_4x8multiple_msa(), hevc_hz_biwgt_4t_6w_msa(), hevc_hz_biwgt_4t_8x2_msa(), hevc_hz_biwgt_4t_8x4multiple_msa(), hevc_hz_biwgt_4t_8x6_msa(), hevc_hz_biwgt_8t_16w_msa(), hevc_hz_biwgt_8t_24w_msa(), hevc_hz_biwgt_8t_32w_msa(), hevc_hz_biwgt_8t_48w_msa(), hevc_hz_biwgt_8t_4w_msa(), hevc_hz_biwgt_8t_64w_msa(), hevc_hz_biwgt_8t_8w_msa(), hevc_vt_biwgt_4t_12w_msa(), hevc_vt_biwgt_4t_16w_msa(), hevc_vt_biwgt_4t_24w_msa(), hevc_vt_biwgt_4t_32w_msa(), hevc_vt_biwgt_4t_4x2_msa(), hevc_vt_biwgt_4t_4x4_msa(), hevc_vt_biwgt_4t_4x8multiple_msa(), hevc_vt_biwgt_4t_6w_msa(), hevc_vt_biwgt_4t_8x2_msa(), hevc_vt_biwgt_4t_8x4multiple_msa(), hevc_vt_biwgt_4t_8x6_msa(), hevc_vt_biwgt_8t_12w_msa(), hevc_vt_biwgt_8t_16multx2mult_msa(), hevc_vt_biwgt_8t_4w_msa(), hevc_vt_biwgt_8t_8w_msa(), init_obmc_weight(), init_obmc_weight_row(), interpolate_lpc(), lsp_quantize(), mc_block(), nlmeans_slice(), silk_decode_lpc(), and try_8x8basis().
init_obmc_weight_row()
static void init_obmc_weight_row (Plane * p, uint8_t * obmc_weight, int stride, int left, int right, int wy) static
Definition at line 1519 of file diracdec.c.
Referenced by init_obmc_weight().
init_obmc_weight()
static void init_obmc_weight (Plane * p, uint8_t * obmc_weight, int stride, int left, int right, int top, int bottom) static
Definition at line 1533 of file diracdec.c.
Referenced by init_obmc_weights().
init_obmc_weights()
static void init_obmc_weights (DiracContext * s, Plane * p, int by) static
Definition at line 1552 of file diracdec.c.
Referenced by dirac_decode_frame_internal().
mc_subpel()
static int mc_subpel (DiracContext * s, DiracBlock * block, const uint8_t * src[5], int x, int y, int ref, int plane) static
For block x,y, determine which of the hpel planes to do bilinear interpolation from and set src[] to the location in each hpel plane to MC from.
Returns
the index of the put_dirac_pixels_tab function to use 0 for 1 plane (fpel,hpel), 1 for 2 planes (qpel), 2 for 4 planes (qpel), and 3 for epel
Definition at line 1592 of file diracdec.c.
Referenced by block_mc().
add_dc()
static void add_dc (uint16_t * dst, int dc, int stride, uint8_t * obmc_weight, int xblen, int yblen) static
Definition at line 1687 of file diracdec.c.
Referenced by block_mc().
block_mc()
static void block_mc (DiracContext * s, DiracBlock * block, uint16_t * mctmp, uint8_t * obmc_weight, int plane, int dstx, int dsty) static
Definition at line 1703 of file diracdec.c.
Referenced by mc_row().
mc_row()
static void mc_row (DiracContext * s, DiracBlock * block, uint16_t * mctmp, int plane, int dsty) static
Definition at line 1739 of file diracdec.c.
Referenced by dirac_decode_frame_internal().
select_dsp_funcs()
static void select_dsp_funcs (DiracContext * s, int width, int height, int xblen, int yblen) static
Definition at line 1755 of file diracdec.c.
Referenced by dirac_decode_frame_internal().
interpolate_refplane()
static int interpolate_refplane (DiracContext * s, DiracFrame * ref, int plane, int width, int height) static
Definition at line 1775 of file diracdec.c.
Referenced by dirac_decode_frame_internal().
dirac_decode_frame_internal()
static int dirac_decode_frame_internal (DiracContext * s) static
Dirac Specification -> 13.0 Transform data syntax.
transform_data()
Definition at line 1816 of file diracdec.c.
Referenced by dirac_decode_data_unit().
get_buffer_with_edge()
static int get_buffer_with_edge (AVCodecContext * avctx, AVFrame * f, int flags) static
Definition at line 1911 of file diracdec.c.
Referenced by dirac_decode_data_unit(), and dirac_decode_picture_header().
dirac_decode_picture_header()
static int dirac_decode_picture_header (DiracContext * s) static
Dirac Specification -> 11.1.1 Picture Header.
picture_header()
Definition at line 1938 of file diracdec.c.
Referenced by dirac_decode_data_unit().
get_delayed_pic()
static int get_delayed_pic (DiracContext * s, AVFrame * picture, int * got_frame) static
Definition at line 2026 of file diracdec.c.
Referenced by dirac_decode_frame().
dirac_decode_data_unit()
static int dirac_decode_data_unit (AVCodecContext * avctx, const uint8_t * buf, int size) static
Definition at line 2061 of file diracdec.c.
Referenced by dirac_decode_frame().
dirac_decode_frame()
static int dirac_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * pkt) static
Definition at line 2196 of file diracdec.c.
Variable Documentation
epel_weights
const uint8_t epel_weights[4][4][4] static
Initial value:
= {
    {{ 16,  0,  0,  0 },
     { 12,  4,  0,  0 },
     {  8,  8,  0,  0 },
     {  4, 12,  0,  0 }},
    {{ 12,  0,  4,  0 },
     {  9,  3,  3,  1 },
     {  6,  6,  2,  2 },
     {  3,  9,  1,  3 }},
    {{  8,  0,  8,  0 },
     {  6,  2,  6,  2 },
     {  4,  4,  4,  4 },
     {  2,  6,  2,  6 }},
    {{  4,  0, 12,  0 },
     {  3,  1,  9,  3 },
     {  2,  2,  6,  6 },
     {  1,  3,  3,  9 }}
}
Definition at line 1565 of file diracdec.c.
Referenced by mc_subpel().
ff_dirac_decoder
AVCodec ff_dirac_decoder
Initial value:
= {
    .name           = "dirac",
    .long_name      = NULL_IF_CONFIG_SMALL("BBC Dirac VC-2"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_DIRAC,
    .priv_data_size = sizeof(DiracContext),
    .init           = dirac_decode_init,
    .close          = dirac_decode_end,
    .decode         = dirac_decode_frame,
    .capabilities   = AV_CODEC_CAP_DELAY | AV_CODEC_CAP_SLICE_THREADS | AV_CODEC_CAP_DR1,
    .flush          = dirac_decode_flush,
}
Definition at line 2292 of file diracdec.c.