FFmpeg: libavcodec/g723_1.c File Reference
g723_1.c File Reference
#include <stdint.h>
#include "libavutil/common.h"
#include "acelp_vectors.h"
#include "avcodec.h"
#include "celp_math.h"
#include "g723_1.h"
Functions
int ff_g723_1_scale_vector (int16_t *dst, const int16_t *vector, int length)
Scale vector contents based on the largest of their absolutes.
int ff_g723_1_normalize_bits (int num, int width)
Calculate the number of left-shifts required for normalizing the input.
int ff_g723_1_dot_product (const int16_t *a, const int16_t *b, int length)
void ff_g723_1_get_residual (int16_t *residual, int16_t *prev_excitation, int lag)
Get delayed contribution from the previous excitation vector.
void ff_g723_1_gen_dirac_train (int16_t *buf, int pitch_lag)
Generate a train of dirac functions with period as pitch lag.
void ff_g723_1_gen_acb_excitation (int16_t *vector, int16_t *prev_excitation, int pitch_lag, G723_1_Subframe *subfrm, enum Rate cur_rate)
Generate adaptive codebook excitation.
static void lsp2lpc (int16_t *lpc)
Convert LSP frequencies to LPC coefficients.
void ff_g723_1_lsp_interpolate (int16_t *lpc, int16_t *cur_lsp, int16_t *prev_lsp)
Quantize LSP frequencies by interpolation and convert them to the corresponding LPC coefficients.
void ff_g723_1_inverse_quant (int16_t *cur_lsp, int16_t *prev_lsp, uint8_t *lsp_index, int bad_frame)
Perform inverse quantization of LSP frequencies.
Function Documentation
ff_g723_1_scale_vector()
int ff_g723_1_scale_vector (int16_t * dst, const int16_t * vector, int length)
Scale vector contents based on the largest of their absolutes.
Definition at line 32 of file g723_1.c.
Referenced by comp_autocorr(), comp_interp_index(), formant_postfilter(), and g723_1_encode_frame().
ff_g723_1_normalize_bits()
int ff_g723_1_normalize_bits (int num, int width)
Calculate the number of left-shifts required for normalizing the input.
Parameters
num input number
width width of the input, 16 bits(0) / 32 bits(1)
Definition at line 49 of file g723_1.c.
Referenced by acb_search(), comp_autocorr(), comp_harmonic_coeff(), comp_ppf_coeff(), estimate_pitch(), gain_scale(), get_fcb_param(), lpc2lsp(), and lsp_quantize().
ff_g723_1_dot_product()
int ff_g723_1_dot_product (const int16_t * a, const int16_t * b, int length)
Definition at line 54 of file g723_1.c.
Referenced by acb_search(), autocorr_max(), comp_interp_index(), comp_ppf_coeff(), formant_postfilter(), and get_fcb_param().
ff_g723_1_get_residual()
void ff_g723_1_get_residual (int16_t * residual, int16_t * prev_excitation, int lag)
Get delayed contribution from the previous excitation vector.
Definition at line 60 of file g723_1.c.
Referenced by acb_search(), and ff_g723_1_gen_acb_excitation().
ff_g723_1_gen_dirac_train()
void ff_g723_1_gen_dirac_train (int16_t * buf, int pitch_lag)
Generate a train of dirac functions with period as pitch lag.
Definition at line 74 of file g723_1.c.
Referenced by fcb_search(), gen_fcb_excitation(), and get_fcb_param().
ff_g723_1_gen_acb_excitation()
void ff_g723_1_gen_acb_excitation (int16_t * vector, int16_t * prev_excitation, int pitch_lag, G723_1_Subframe * subfrm, enum Rate cur_rate)
Generate adaptive codebook excitation.
Definition at line 86 of file g723_1.c.
Referenced by g723_1_decode_frame(), g723_1_encode_frame(), and generate_noise().
lsp2lpc()
static void lsp2lpc (int16_t * lpc) static
Convert LSP frequencies to LPC coefficients.
Parameters
lpc buffer for LPC coefficients
Definition at line 118 of file g723_1.c.
Referenced by ff_g723_1_lsp_interpolate().
ff_g723_1_lsp_interpolate()
void ff_g723_1_lsp_interpolate (int16_t * lpc, int16_t * cur_lsp, int16_t * prev_lsp)
Quantize LSP frequencies by interpolation and convert them to the corresponding LPC coefficients.
Parameters
lpc buffer for LPC coefficients
cur_lsp the current LSP vector
prev_lsp the previous LSP vector
Definition at line 180 of file g723_1.c.
Referenced by g723_1_decode_frame(), and g723_1_encode_frame().
ff_g723_1_inverse_quant()
void ff_g723_1_inverse_quant (int16_t * cur_lsp, int16_t * prev_lsp, uint8_t * lsp_index, int bad_frame)
Perform inverse quantization of LSP frequencies.
Parameters
cur_lsp the current LSP vector
prev_lsp the previous LSP vector
lsp_index VQ indices
bad_frame bad frame flag
Definition at line 201 of file g723_1.c.
Referenced by g723_1_decode_frame(), and g723_1_encode_frame().