FFmpeg: libavcodec/hevc.c File Reference
hevc.c File Reference
#include "libavutil/atomic.h"
#include "libavutil/attributes.h"
#include "libavutil/common.h"
#include "libavutil/display.h"
#include "libavutil/internal.h"
#include "libavutil/mastering_display_metadata.h"
#include "libavutil/md5.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "libavutil/stereo3d.h"
#include "bswapdsp.h"
#include "bytestream.h"
#include "cabac_functions.h"
#include "golomb.h"
#include "hevc.h"
#include "profiles.h"
Macros
#define HWACCEL_MAX (CONFIG_HEVC_DXVA2_HWACCEL + CONFIG_HEVC_D3D11VA_HWACCEL + CONFIG_HEVC_VAAPI_HWACCEL + CONFIG_HEVC_VDPAU_HWACCEL)
#define CTB(tab, x, y) ((tab)[(y) * s->ps.sps->ctb_width + (x)])
#define SET_SAO(elem, value)
#define SUBDIVIDE(x, y, idx)
#define POS(c_idx, x, y)
#define OFFSET(x) offsetof(HEVCContext, x)
#define PAR (AV_OPT_FLAG_DECODING_PARAM | AV_OPT_FLAG_VIDEO_PARAM)
Functions
static void pic_arrays_free (HEVCContext *s)
NOTE: Each function hls_foo correspond to the function foo in the specification (HLS stands for High Level Syntax).
static int pic_arrays_init (HEVCContext *s, const HEVCSPS *sps)
static void pred_weight_table (HEVCContext *s, GetBitContext *gb)
static int decode_lt_rps (HEVCContext *s, LongTermRPS *rps, GetBitContext *gb)
static void export_stream_params (AVCodecContext *avctx, const HEVCParamSets *ps, const HEVCSPS *sps)
static int set_sps (HEVCContext *s, const HEVCSPS *sps, enum AVPixelFormat pix_fmt)
static int hls_slice_header (HEVCContext *s)
static void hls_sao_param (HEVCContext *s, int rx, int ry)
static int hls_cross_component_pred (HEVCContext *s, int idx)
static int hls_transform_unit (HEVCContext *s, int x0, int y0, int xBase, int yBase, int cb_xBase, int cb_yBase, int log2_cb_size, int log2_trafo_size, int blk_idx, int cbf_luma, int *cbf_cb, int *cbf_cr)
static void set_deblocking_bypass (HEVCContext *s, int x0, int y0, int log2_cb_size)
static int hls_transform_tree (HEVCContext *s, int x0, int y0, int xBase, int yBase, int cb_xBase, int cb_yBase, int log2_cb_size, int log2_trafo_size, int trafo_depth, int blk_idx, const int *base_cbf_cb, const int *base_cbf_cr)
static int hls_pcm_sample (HEVCContext *s, int x0, int y0, int log2_cb_size)
static void luma_mc_uni (HEVCContext *s, uint8_t *dst, ptrdiff_t dststride, AVFrame *ref, const Mv *mv, int x_off, int y_off, int block_w, int block_h, int luma_weight, int luma_offset)
8.5.3.2.2.1 Luma sample unidirectional interpolation process
static void luma_mc_bi (HEVCContext *s, uint8_t *dst, ptrdiff_t dststride, AVFrame *ref0, const Mv *mv0, int x_off, int y_off, int block_w, int block_h, AVFrame *ref1, const Mv *mv1, struct MvField *current_mv)
8.5.3.2.2.1 Luma sample bidirectional interpolation process
static void chroma_mc_uni (HEVCContext *s, uint8_t *dst0, ptrdiff_t dststride, uint8_t *src0, ptrdiff_t srcstride, int reflist, int x_off, int y_off, int block_w, int block_h, struct MvField *current_mv, int chroma_weight, int chroma_offset)
8.5.3.2.2.2 Chroma sample uniprediction interpolation process
static void chroma_mc_bi (HEVCContext *s, uint8_t *dst0, ptrdiff_t dststride, AVFrame *ref0, AVFrame *ref1, int x_off, int y_off, int block_w, int block_h, struct MvField *current_mv, int cidx)
8.5.3.2.2.2 Chroma sample bidirectional interpolation process
static void hevc_await_progress (HEVCContext *s, HEVCFrame *ref, const Mv *mv, int y0, int height)
static void hevc_luma_mv_mvp_mode (HEVCContext *s, int x0, int y0, int nPbW, int nPbH, int log2_cb_size, int part_idx, int merge_idx, MvField *mv)
static void hls_prediction_unit (HEVCContext *s, int x0, int y0, int nPbW, int nPbH, int log2_cb_size, int partIdx, int idx)
static int luma_intra_pred_mode (HEVCContext *s, int x0, int y0, int pu_size, int prev_intra_luma_pred_flag)
8.4.1
static av_always_inline void set_ct_depth (HEVCContext *s, int x0, int y0, int log2_cb_size, int ct_depth)
static void intra_prediction_unit (HEVCContext *s, int x0, int y0, int log2_cb_size)
static void intra_prediction_unit_default_value (HEVCContext *s, int x0, int y0, int log2_cb_size)
static int hls_coding_unit (HEVCContext *s, int x0, int y0, int log2_cb_size)
static int hls_coding_quadtree (HEVCContext *s, int x0, int y0, int log2_cb_size, int cb_depth)
static void hls_decode_neighbour (HEVCContext *s, int x_ctb, int y_ctb, int ctb_addr_ts)
static int hls_decode_entry (AVCodecContext *avctxt, void *isFilterThread)
static int hls_slice_data (HEVCContext *s)
static int hls_decode_entry_wpp (AVCodecContext *avctxt, void *input_ctb_row, int job, int self_id)
static int hls_slice_data_wpp (HEVCContext *s, const H2645NAL *nal)
static int set_side_data (HEVCContext *s)
static int hevc_frame_start (HEVCContext *s)
static int decode_nal_unit (HEVCContext *s, const H2645NAL *nal)
static int decode_nal_units (HEVCContext *s, const uint8_t *buf, int length)
static void print_md5 (void *log_ctx, int level, uint8_t md5[16])
static int verify_md5 (HEVCContext *s, AVFrame *frame)
static int hevc_decode_extradata (HEVCContext *s, uint8_t *buf, int length)
static int hevc_decode_frame (AVCodecContext *avctx, void *data, int *got_output, AVPacket *avpkt)
static int hevc_ref_frame (HEVCContext *s, HEVCFrame *dst, HEVCFrame *src)
static av_cold int hevc_decode_free (AVCodecContext *avctx)
static av_cold int hevc_init_context (AVCodecContext *avctx)
static int hevc_update_thread_context (AVCodecContext *dst, const AVCodecContext *src)
static av_cold int hevc_decode_init (AVCodecContext *avctx)
static av_cold int hevc_init_thread_copy (AVCodecContext *avctx)
static void hevc_decode_flush (AVCodecContext *avctx)
Variables
const uint8_t ff_hevc_pel_weight [65] = { [2] = 0, [4] = 1, [6] = 2, [8] = 3, [12] = 4, [16] = 5, [24] = 6, [32] = 7, [48] = 8, [64] = 9 }
static const uint8_t tab_mode_idx []
static const AVOption options []
static const AVClass hevc_decoder_class
AVCodec ff_hevc_decoder
Macro Definition Documentation
HWACCEL_MAX
#define HWACCEL_MAX (CONFIG_HEVC_DXVA2_HWACCEL + CONFIG_HEVC_D3D11VA_HWACCEL + CONFIG_HEVC_VAAPI_HWACCEL + CONFIG_HEVC_VDPAU_HWACCEL)
Referenced by set_sps().
CTB
#define CTB (tab, x, y) ((tab)[(y) * s->ps.sps->ctb_width + (x)])
Definition at line 833 of file hevc.c.
Referenced by hls_sao_param().
SET_SAO
#define SET_SAO (elem, value)
Value:
do {                                                    \
    if (!sao_merge_up_flag && !sao_merge_left_flag)     \
        sao->elem = value;                              \
    else if (sao_merge_left_flag)                       \
        sao->elem = CTB(s->sao, rx-1, ry).elem;         \
    else if (sao_merge_up_flag)                         \
        sao->elem = CTB(s->sao, rx, ry-1).elem;         \
    else                                                \
        sao->elem = 0;                                  \
} while (0)
Definition at line 835 of file hevc.c.
Referenced by hls_sao_param().
SUBDIVIDE
#define SUBDIVIDE (x, y, idx)
Value:
do {                                                                            \
    ret = hls_transform_tree(s, x, y, x0, y0, cb_xBase, cb_yBase, log2_cb_size, \
                             log2_trafo_size - 1, trafo_depth + 1, idx,         \
                             cbf_cb, cbf_cr);                                   \
    if (ret < 0)                                                                \
        return ret;                                                             \
} while (0)
Referenced by hls_transform_tree().
POS
#define POS (c_idx, x, y)
Value:
&s->frame->data[c_idx][((y) >> s->ps.sps->vshift[c_idx]) * s->frame->linesize[c_idx] + \
                           (((x) >> s->ps.sps->hshift[c_idx]) << s->ps.sps->pixel_shift)]
Referenced by hls_prediction_unit().
OFFSET
#define OFFSET (x) offsetof(HEVCContext, x)
Definition at line 3386 of file hevc.c.
PAR
#define PAR (AV_OPT_FLAG_DECODING_PARAM | AV_OPT_FLAG_VIDEO_PARAM)
Definition at line 3387 of file hevc.c.
Function Documentation
pic_arrays_free()
static void pic_arrays_free (HEVCContext * s) static
NOTE: Each function hls_foo correspond to the function foo in the specification (HLS stands for High Level Syntax).
Section 5.7
Definition at line 56 of file hevc.c.
Referenced by hevc_decode_free(), pic_arrays_init(), and set_sps().
pic_arrays_init()
static int pic_arrays_init (HEVCContext * s, const HEVCSPS * sps) static
Definition at line 84 of file hevc.c.
Referenced by set_sps().
pred_weight_table()
static void pred_weight_table (HEVCContext * s, GetBitContext * gb) static
Definition at line 140 of file hevc.c.
Referenced by hls_slice_header().
decode_lt_rps()
static int decode_lt_rps (HEVCContext * s, LongTermRPS * rps, GetBitContext * gb) static
Definition at line 233 of file hevc.c.
Referenced by hls_slice_header().
export_stream_params()
static void export_stream_params (AVCodecContext * avctx, const HEVCParamSets * ps, const HEVCSPS * sps) static
Definition at line 285 of file hevc.c.
Referenced by hevc_decode_extradata(), and set_sps().
set_sps()
static int set_sps (HEVCContext * s, const HEVCSPS * sps, enum AVPixelFormat pix_fmt) static
Definition at line 331 of file hevc.c.
Referenced by hevc_update_thread_context(), and hls_slice_header().
hls_slice_header()
static int hls_slice_header (HEVCContext * s) static
Definition at line 428 of file hevc.c.
Referenced by decode_nal_unit().
hls_sao_param()
static void hls_sao_param (HEVCContext * s, int rx, int ry) static
Definition at line 847 of file hevc.c.
Referenced by hls_decode_entry(), and hls_decode_entry_wpp().
hls_cross_component_pred()
static int hls_cross_component_pred (HEVCContext * s, int idx) static
Definition at line 921 of file hevc.c.
Referenced by hls_transform_unit().
hls_transform_unit()
static int hls_transform_unit (HEVCContext * s, int x0, int y0, int xBase, int yBase, int cb_xBase, int cb_yBase, int log2_cb_size, int log2_trafo_size, int blk_idx, int cbf_luma, int * cbf_cb, int * cbf_cr) static
Definition at line 937 of file hevc.c.
Referenced by hls_transform_tree().
set_deblocking_bypass()
static void set_deblocking_bypass (HEVCContext * s, int x0, int y0, int log2_cb_size) static
Definition at line 1143 of file hevc.c.
Referenced by hls_coding_unit(), and hls_transform_tree().
hls_transform_tree()
static int hls_transform_tree (HEVCContext * s, int x0, int y0, int xBase, int yBase, int cb_xBase, int cb_yBase, int log2_cb_size, int log2_trafo_size, int trafo_depth, int blk_idx, const int * base_cbf_cb, const int * base_cbf_cr) static
Definition at line 1158 of file hevc.c.
Referenced by hls_coding_unit().
hls_pcm_sample()
static int hls_pcm_sample (HEVCContext * s, int x0, int y0, int log2_cb_size) static
Definition at line 1281 of file hevc.c.
Referenced by hls_coding_unit().
luma_mc_uni()
static void luma_mc_uni (HEVCContext * s, uint8_t * dst, ptrdiff_t dststride, AVFrame * ref, const Mv * mv, int x_off, int y_off, int block_w, int block_h, int luma_weight, int luma_offset) static
8.5.3.2.2.1 Luma sample unidirectional interpolation process
Parameters
s HEVC decoding context
dst target buffer for block data at block position
dststride stride of the dst buffer
ref reference picture buffer at origin (0, 0)
mv motion vector (relative to block position) to get pixel data from
x_off horizontal position of block from origin (0, 0)
y_off vertical position of block from origin (0, 0)
block_w width of block
block_h height of block
luma_weight weighting factor applied to the luma prediction
luma_offset additive offset applied to the luma prediction value
Definition at line 1338 of file hevc.c.
Referenced by hls_prediction_unit().
luma_mc_bi()
static void luma_mc_bi (HEVCContext * s, uint8_t * dst, ptrdiff_t dststride, AVFrame * ref0, const Mv * mv0, int x_off, int y_off, int block_w, int block_h, AVFrame * ref1, const Mv * mv1, struct MvField * current_mv) static
8.5.3.2.2.1 Luma sample bidirectional interpolation process
Parameters
s HEVC decoding context
dst target buffer for block data at block position
dststride stride of the dst buffer
ref0 reference picture0 buffer at origin (0, 0)
mv0 motion vector0 (relative to block position) to get pixel data from
x_off horizontal position of block from origin (0, 0)
y_off vertical position of block from origin (0, 0)
block_w width of block
block_h height of block
ref1 reference picture1 buffer at origin (0, 0)
mv1 motion vector1 (relative to block position) to get pixel data from
current_mv current motion vector structure
Definition at line 1399 of file hevc.c.
Referenced by hls_prediction_unit().
chroma_mc_uni()
static void chroma_mc_uni (HEVCContext * s, uint8_t * dst0, ptrdiff_t dststride, uint8_t * src0, ptrdiff_t srcstride, int reflist, int x_off, int y_off, int block_w, int block_h, struct MvField * current_mv, int chroma_weight, int chroma_offset) static
8.5.3.2.2.2 Chroma sample uniprediction interpolation process
Parameters
s HEVC decoding context
dst1 target buffer for block data at block position (U plane)
dst2 target buffer for block data at block position (V plane)
dststride stride of the dst1 and dst2 buffers
ref reference picture buffer at origin (0, 0)
mv motion vector (relative to block position) to get pixel data from
x_off horizontal position of block from origin (0, 0)
y_off vertical position of block from origin (0, 0)
block_w width of block
block_h height of block
chroma_weight weighting factor applied to the chroma prediction
chroma_offset additive offset applied to the chroma prediction value
Definition at line 1490 of file hevc.c.
Referenced by hls_prediction_unit().
chroma_mc_bi()
static void chroma_mc_bi (HEVCContext * s, uint8_t * dst0, ptrdiff_t dststride, AVFrame * ref0, AVFrame * ref1, int x_off, int y_off, int block_w, int block_h, struct MvField * current_mv, int cidx) static
8.5.3.2.2.2 Chroma sample bidirectional interpolation process
Parameters
s HEVC decoding context
dst target buffer for block data at block position
dststride stride of the dst buffer
ref0 reference picture0 buffer at origin (0, 0)
mv0 motion vector0 (relative to block position) to get pixel data from
x_off horizontal position of block from origin (0, 0)
y_off vertical position of block from origin (0, 0)
block_w width of block
block_h height of block
ref1 reference picture1 buffer at origin (0, 0)
mv1 motion vector1 (relative to block position) to get pixel data from
current_mv current motion vector structure
cidx chroma component(cb, cr)
Definition at line 1555 of file hevc.c.
Referenced by hls_prediction_unit().
hevc_await_progress()
static void hevc_await_progress (HEVCContext * s, HEVCFrame * ref, const Mv * mv, int y0, int height) static
Definition at line 1645 of file hevc.c.
Referenced by hls_prediction_unit().
hevc_luma_mv_mvp_mode()
static void hevc_luma_mv_mvp_mode (HEVCContext * s, int x0, int y0, int nPbW, int nPbH, int log2_cb_size, int part_idx, int merge_idx, MvField * mv) static
Definition at line 1654 of file hevc.c.
Referenced by hls_prediction_unit().
hls_prediction_unit()
static void hls_prediction_unit (HEVCContext * s, int x0, int y0, int nPbW, int nPbH, int log2_cb_size, int partIdx, int idx) static
Definition at line 1699 of file hevc.c.
Referenced by hls_coding_unit().
luma_intra_pred_mode()
static int luma_intra_pred_mode (HEVCContext * s, int x0, int y0, int pu_size, int prev_intra_luma_pred_flag) static
8.4.1
Definition at line 1825 of file hevc.c.
Referenced by intra_prediction_unit().
set_ct_depth()
static av_always_inline void set_ct_depth (HEVCContext * s, int x0, int y0, int log2_cb_size, int ct_depth) static
Definition at line 1905 of file hevc.c.
Referenced by hls_coding_unit().
intra_prediction_unit()
static void intra_prediction_unit (HEVCContext * s, int x0, int y0, int log2_cb_size) static
Definition at line 1922 of file hevc.c.
Referenced by hls_coding_unit().
intra_prediction_unit_default_value()
static void intra_prediction_unit_default_value (HEVCContext * s, int x0, int y0, int log2_cb_size) static
Definition at line 1990 of file hevc.c.
Referenced by hls_coding_unit().
hls_coding_unit()
static int hls_coding_unit (HEVCContext * s, int x0, int y0, int log2_cb_size) static
Definition at line 2013 of file hevc.c.
Referenced by hls_coding_quadtree().
hls_coding_quadtree()
static int hls_coding_quadtree (HEVCContext * s, int x0, int y0, int log2_cb_size, int cb_depth) static
Definition at line 2176 of file hevc.c.
Referenced by hls_decode_entry(), and hls_decode_entry_wpp().
hls_decode_neighbour()
static void hls_decode_neighbour (HEVCContext * s, int x_ctb, int y_ctb, int ctb_addr_ts) static
Definition at line 2261 of file hevc.c.
Referenced by hls_decode_entry(), and hls_decode_entry_wpp().
hls_decode_entry()
static int hls_decode_entry (AVCodecContext * avctxt, void * isFilterThread) static
Definition at line 2310 of file hevc.c.
Referenced by hls_slice_data().
hls_slice_data()
static int hls_slice_data (HEVCContext * s) static
Definition at line 2366 of file hevc.c.
Referenced by decode_nal_unit().
hls_decode_entry_wpp()
static int hls_decode_entry_wpp (AVCodecContext * avctxt, void * input_ctb_row, int job, int self_id) static
Definition at line 2377 of file hevc.c.
Referenced by hls_slice_data_wpp().
hls_slice_data_wpp()
static int hls_slice_data_wpp (HEVCContext * s, const H2645NAL * nal) static
Definition at line 2454 of file hevc.c.
Referenced by decode_nal_unit().
set_side_data()
static int set_side_data (HEVCContext * s) static
Definition at line 2552 of file hevc.c.
Referenced by hevc_frame_start().
hevc_frame_start()
static int hevc_frame_start (HEVCContext * s) static
Definition at line 2663 of file hevc.c.
Referenced by decode_nal_unit().
decode_nal_unit()
static int decode_nal_unit (HEVCContext * s, const H2645NAL * nal) static
Definition at line 2720 of file hevc.c.
Referenced by decode_nal_units().
decode_nal_units()
static int decode_nal_units (HEVCContext * s, const uint8_t * buf, int length) static
Definition at line 2862 of file hevc.c.
Referenced by hevc_decode_extradata(), and hevc_decode_frame().
print_md5()
static void print_md5 (void * log_ctx, int level, uint8_t md5[16]) static
Definition at line 2903 of file hevc.c.
Referenced by verify_md5().
verify_md5()
static int verify_md5 (HEVCContext * s, AVFrame * frame) static
Definition at line 2910 of file hevc.c.
Referenced by hevc_decode_frame().
hevc_decode_extradata()
static int hevc_decode_extradata (HEVCContext * s, uint8_t * buf, int length) static
Definition at line 2976 of file hevc.c.
Referenced by hevc_decode_frame(), and hevc_decode_init().
hevc_decode_frame()
static int hevc_decode_frame (AVCodecContext * avctx, void * data, int * got_output, AVPacket * avpkt) static
Definition at line 3048 of file hevc.c.
hevc_ref_frame()
static int hevc_ref_frame (HEVCContext * s, HEVCFrame * dst, HEVCFrame * src) static
Definition at line 3111 of file hevc.c.
Referenced by hevc_update_thread_context().
hevc_decode_free()
static av_cold int hevc_decode_free (AVCodecContext * avctx) static
Definition at line 3152 of file hevc.c.
Referenced by hevc_decode_init(), and hevc_init_context().
hevc_init_context()
static av_cold int hevc_init_context (AVCodecContext * avctx) static
Definition at line 3204 of file hevc.c.
Referenced by hevc_decode_init(), hevc_init_thread_copy(), and hevc_update_thread_context().
hevc_update_thread_context()
static int hevc_update_thread_context (AVCodecContext * dst, const AVCodecContext * src) static
Definition at line 3252 of file hevc.c.
hevc_decode_init()
static av_cold int hevc_decode_init (AVCodecContext * avctx) static
Definition at line 3328 of file hevc.c.
hevc_init_thread_copy()
static av_cold int hevc_init_thread_copy (AVCodecContext * avctx) static
Definition at line 3364 of file hevc.c.
hevc_decode_flush()
static void hevc_decode_flush (AVCodecContext * avctx) static
Definition at line 3378 of file hevc.c.
Variable Documentation
ff_hevc_pel_weight
const uint8_t ff_hevc_pel_weight[65] = { [2] = 0, [4] = 1, [6] = 2, [8] = 3, [12] = 4, [16] = 5, [24] = 6, [32] = 7, [48] = 8, [64] = 9 }
Definition at line 44 of file hevc.c.
Referenced by chroma_mc_bi(), chroma_mc_uni(), luma_mc_bi(), and luma_mc_uni().
tab_mode_idx
const uint8_t tab_mode_idx[] static
Initial value:
= {
     0,  1,  2,  2,  2,  2,  3,  5,  7,  8, 10, 12, 13, 15, 17, 18, 19, 20,
    21, 22, 23, 23, 24, 24, 25, 25, 26, 27, 27, 28, 28, 29, 29, 30, 31}
Definition at line 1918 of file hevc.c.
Referenced by intra_prediction_unit().
options
const AVOption options[] static
Initial value:
= {
    { "apply_defdispwin", "Apply default display window from VUI", OFFSET(apply_defdispwin),
        AV_OPT_TYPE_BOOL, {.i64 = 0}, 0, 1, PAR },
    { "strict-displaywin", "stricly apply default display window size", OFFSET(apply_defdispwin),
        AV_OPT_TYPE_BOOL, {.i64 = 0}, 0, 1, PAR },
    { NULL },
}
Definition at line 3389 of file hevc.c.
hevc_decoder_class
const AVClass hevc_decoder_class static
Initial value:
= {
    .class_name = "HEVC decoder",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 3397 of file hevc.c.
ff_hevc_decoder
AVCodec ff_hevc_decoder
Initial value:
= {
    .name                  = "hevc",
    .long_name             = NULL_IF_CONFIG_SMALL("HEVC (High Efficiency Video Coding)"),
    .type                  = AVMEDIA_TYPE_VIDEO,
    .id                    = AV_CODEC_ID_HEVC,
    .priv_data_size        = sizeof(HEVCContext),
    .priv_class            = &hevc_decoder_class,
    .init                  = hevc_decode_init,
    .close                 = hevc_decode_free,
    .decode                = hevc_decode_frame,
    .flush                 = hevc_decode_flush,
    .update_thread_context = hevc_update_thread_context,
    .init_thread_copy      = hevc_init_thread_copy,
    .capabilities          = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_DELAY |
                             AV_CODEC_CAP_SLICE_THREADS | AV_CODEC_CAP_FRAME_THREADS,
    .profiles              = NULL_IF_CONFIG_SMALL(ff_hevc_profiles),
}
Definition at line 3404 of file hevc.c.