FFmpeg: libavcodec/rawdec.c File Reference
rawdec.c File Reference
Raw Video Decoder.
#include "avcodec.h"
#include "bswapdsp.h"
#include "get_bits.h"
#include "internal.h"
#include "raw.h"
#include "libavutil/avassert.h"
#include "libavutil/buffer.h"
#include "libavutil/common.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/imgutils.h"
#include "libavutil/opt.h"
Data Structures
struct RawVideoContext
Macros
#define SCALE16(x, bits) (((x) << (16 - (bits))) | ((x) >> (2 * (bits) - 16)))
#define MKSCALE16(name, r16, w16)
Scale buffer to 16 bits per coded sample resolution.
Functions
static av_cold int raw_init_decoder (AVCodecContext *avctx)
static void flip (AVCodecContext *avctx, AVFrame *frame)
static int raw_decode (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int raw_close_decoder (AVCodecContext *avctx)
Variables
static const AVOption options []
static const AVClass rawdec_class
AVCodec ff_rawvideo_decoder
Detailed Description
Raw Video Decoder.
Definition in file rawdec.c.
Macro Definition Documentation
SCALE16
#define SCALE16 (x, bits) (((x) << (16 - (bits))) | ((x) >> (2 * (bits) - 16)))
Definition at line 143 of file rawdec.c.
MKSCALE16
#define MKSCALE16 (name, r16, w16)
Value:
static void name(AVCodecContext *avctx, uint8_t * dst, const uint8_t *buf, int buf_size, int packed) \
{ \
    int i; \
    if (!packed) { \
        for (i = 0; i + 1 < buf_size; i += 2) \
            w16(dst + i, SCALE16(r16(buf + i), avctx->bits_per_coded_sample)); \
    } else { \
        GetBitContext gb; \
        init_get_bits(&gb, buf, buf_size * 8); \
        for (i = 0; i < avctx->width * avctx->height; i++) { \
            int sample = get_bits(&gb, avctx->bits_per_coded_sample); \
            w16(dst + i*2, SCALE16(sample, avctx->bits_per_coded_sample)); \
        } \
   } \
}
Scale buffer to 16 bits per coded sample resolution.
Definition at line 148 of file rawdec.c.
Function Documentation
raw_init_decoder()
static av_cold int raw_init_decoder (AVCodecContext * avctx) static
Definition at line 69 of file rawdec.c.
flip()
static void flip (AVCodecContext * avctx, AVFrame * frame) static
Definition at line 134 of file rawdec.c.
Referenced by av_display_matrix_flip(), config_input(), ff_oss_audio_open(), filter_frame(), get_video_buffer(), and tnput().
raw_decode()
static int raw_decode (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 168 of file rawdec.c.
raw_close_decoder()
static av_cold int raw_close_decoder (AVCodecContext * avctx) static
Definition at line 485 of file rawdec.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
={
{"top", "top field first", 0x42, AV_OPT_TYPE_BOOL, {.i64 = -1}, -1, 1, AV_OPT_FLAG_DECODING_PARAM|AV_OPT_FLAG_VIDEO_PARAM},
{NULL}
}
Definition at line 58 of file rawdec.c.
rawdec_class
const AVClass rawdec_class static
Initial value:
= {
    .class_name = "rawdec",
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 63 of file rawdec.c.
ff_rawvideo_decoder
AVCodec ff_rawvideo_decoder
Initial value:
= {
    .name           = "rawvideo",
    .long_name      = NULL_IF_CONFIG_SMALL("raw video"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_RAWVIDEO,
    .priv_data_size = sizeof(RawVideoContext),
    .init           = raw_init_decoder,
    .close          = raw_close_decoder,
    .decode         = raw_decode,
    .priv_class     = &rawdec_class,
    .capabilities   = AV_CODEC_CAP_PARAM_CHANGE,
}
Definition at line 493 of file rawdec.c.