FFmpeg: libavcodec/jpeg2000dsp.c File Reference
jpeg2000dsp.c File Reference
#include "config.h"
#include "libavutil/attributes.h"
#include "jpeg2000dsp.h"
Functions
static void ict_float (void *_src0, void *_src1, void *_src2, int csize)
static void ict_int (void *_src0, void *_src1, void *_src2, int csize)
static void rct_int (void *_src0, void *_src1, void *_src2, int csize)
av_cold void ff_jpeg2000dsp_init (Jpeg2000DSPContext *c)
Variables
static const float f_ict_params [4]
static const int i_ict_params [4]
Function Documentation
ict_float()
static void ict_float (void * _src0, void * _src1, void * _src2, int csize) static
Definition at line 43 of file jpeg2000dsp.c.
Referenced by ff_jpeg2000dsp_init().
ict_int()
static void ict_int (void * _src0, void * _src1, void * _src2, int csize) static
Definition at line 60 of file jpeg2000dsp.c.
Referenced by ff_jpeg2000dsp_init().
rct_int()
static void rct_int (void * _src0, void * _src1, void * _src2, int csize) static
Definition at line 77 of file jpeg2000dsp.c.
Referenced by ff_jpeg2000dsp_init().
ff_jpeg2000dsp_init()
av_cold void ff_jpeg2000dsp_init (Jpeg2000DSPContext * c)
Definition at line 93 of file jpeg2000dsp.c.
Referenced by checkasm_check_jpeg2000dsp(), and jpeg2000_decode_init().
Variable Documentation
f_ict_params
const float f_ict_params[4] static
Initial value:
= {
    1.402f,
    0.34413f,
    0.71414f,
    1.772f
}
Definition at line 29 of file jpeg2000dsp.c.
Referenced by ict_float().
i_ict_params
const int i_ict_params[4] static
Initial value:
= {
     91881,
     22553,
     46802,
    116130
}
Definition at line 36 of file jpeg2000dsp.c.
Referenced by ict_int().