FFmpeg: libavresample/resample.h File Reference
resample.h File Reference
#include "avresample.h"
#include "internal.h"
#include "audio_data.h"
Data Structures
struct resample_init_func
Functions
ResampleContext * ff_audio_resample_init (AVAudioResampleContext *avr)
Allocate and initialize a ResampleContext.
void ff_audio_resample_free (ResampleContext **c)
Free a ResampleContext.
int ff_audio_resample (ResampleContext *c, AudioData *dst, AudioData *src)
Resample audio data.
Function Documentation
ff_audio_resample_init()
ResampleContext* ff_audio_resample_init (AVAudioResampleContext * avr)
Allocate and initialize a ResampleContext.
The parameters in the AVAudioResampleContext are used to initialize the ResampleContext.
Parameters
avr AVAudioResampleContext
Returns
newly-allocated ResampleContext
Definition at line 120 of file resample.c.
Referenced by avresample_open().
ff_audio_resample_free()
void ff_audio_resample_free (ResampleContext ** c)
Free a ResampleContext.
Parameters
c ResampleContext
Definition at line 224 of file resample.c.
Referenced by avresample_close().
ff_audio_resample()
int ff_audio_resample (ResampleContext * c, AudioData * dst, AudioData * src)
Resample audio data.
Changes the sample rate.
All samples in the source data may not be consumed depending on the resampling parameters and the size of the output buffer. The unconsumed samples are automatically added to the start of the source in the next call. If the destination data can be reallocated, that may be done in this function in order to fit all available output. If it cannot be reallocated, fewer input samples will be consumed in order to have the output fit in the destination data buffers.
Parameters
c ResampleContext
dst destination audio data
src source audio data
Returns
0 on success, negative AVERROR code on failure
Definition at line 334 of file resample.c.
Referenced by avresample_convert().