FFmpeg: libavfilter/vf_colorspace.c File Reference
vf_colorspace.c File Reference
#include "libavutil/avassert.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "libavutil/pixfmt.h"
#include "avfilter.h"
#include "colorspacedsp.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
Data Structures
struct ColorPrimaries
struct TransferCharacteristics
struct LumaCoefficients
struct WhitepointCoefficients
struct ColorSpaceContext
struct ThreadData
Macros
#define supported_depth(d) ((d) == 8 || (d) == 10 || (d) == 12)
#define supported_subsampling(lcw, lch) (((lcw) == 0 && (lch) == 0) || ((lcw) == 1 && (lch) == 0) || ((lcw) == 1 && (lch) == 1))
#define supported_format(d)
#define OFFSET(x) offsetof(ColorSpaceContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM | AV_OPT_FLAG_VIDEO_PARAM
#define ENUM(x, y, z) { x, "", 0, AV_OPT_TYPE_CONST, { .i64 = y }, INT_MIN, INT_MAX, FLAGS, z }
Enumerations
enum DitherMode { DITHER_NONE, DITHER_FSB, DITHER_NB }
enum Colorspace {
CS_UNSPECIFIED, CS_BT470M, CS_BT470BG, CS_BT601_6_525,
CS_BT601_6_625, CS_BT709, CS_SMPTE170M, CS_SMPTE240M,
CS_BT2020, CS_NB
}
enum Whitepoint { WP_D65, WP_C, WP_DCI, WP_NB }
enum WhitepointAdaptation {
WP_ADAPT_BRADFORD, WP_ADAPT_VON_KRIES, NB_WP_ADAPT_NON_IDENTITY, WP_ADAPT_IDENTITY = NB_WP_ADAPT_NON_IDENTITY,
NB_WP_ADAPT
}
Functions
static const struct LumaCoefficients * get_luma_coefficients (enum AVColorSpace csp)
static void fill_rgb2yuv_table (const struct LumaCoefficients *coeffs, double rgb2yuv[3][3])
static const struct TransferCharacteristics * get_transfer_characteristics (enum AVColorTransferCharacteristic trc)
static const struct ColorPrimaries * get_color_primaries (enum AVColorPrimaries prm)
static void invert_matrix3x3 (const double in[3][3], double out[3][3])
static int fill_gamma_table (ColorSpaceContext *s)
static void fill_rgb2xyz_table (const struct ColorPrimaries *coeffs, double rgb2xyz[3][3])
static void mul3x3 (double dst[3][3], const double src1[3][3], const double src2[3][3])
static void fill_whitepoint_conv_table (double out[3][3], enum WhitepointAdaptation wp_adapt, enum Whitepoint src, enum Whitepoint dst)
static void apply_lut (int16_t *buf[3], ptrdiff_t stride, int w, int h, const int16_t *lut)
static int convert (AVFilterContext *ctx, void *data, int job_nr, int n_jobs)
static int get_range_off (AVFilterContext *ctx, int *off, int *y_rng, int *uv_rng, enum AVColorRange rng, int depth)
static int create_filtergraph (AVFilterContext *ctx, const AVFrame *in, const AVFrame *out)
static int init (AVFilterContext *ctx)
static void uninit (AVFilterContext *ctx)
static int filter_frame (AVFilterLink *link, AVFrame *in)
static int query_formats (AVFilterContext *ctx)
static int config_props (AVFilterLink *outlink)
AVFILTER_DEFINE_CLASS (colorspace)
Variables
static enum AVColorTransferCharacteristic default_trc [CS_NB+1]
static enum AVColorPrimaries default_prm [CS_NB+1]
static enum AVColorSpace default_csp [CS_NB+1]
static const double ycgco_matrix [3][3]
static const struct LumaCoefficients luma_coefficients [AVCOL_SPC_NB]
static const struct TransferCharacteristics transfer_characteristics [AVCOL_TRC_NB]
static const struct WhitepointCoefficients whitepoint_coefficients [WP_NB]
static const struct ColorPrimaries color_primaries [AVCOL_PRI_NB]
static const AVOption colorspace_options []
static const AVFilterPad inputs []
static const AVFilterPad outputs []
AVFilter ff_vf_colorspace
Macro Definition Documentation
supported_depth
#define supported_depth (d) ((d) == 8 || (d) == 10 || (d) == 12)
supported_subsampling
#define supported_subsampling (lcw, lch) (((lcw) == 0 && (lch) == 0) || ((lcw) == 1 && (lch) == 0) || ((lcw) == 1 && (lch) == 1))
supported_format
#define supported_format (d)
Value:
((d) != NULL && (d)->nb_components == 3 && \
     !((d)->flags & AV_PIX_FMT_FLAG_RGB) && \
     supported_depth((d)->comp[0].depth) && \
     supported_subsampling((d)->log2_chroma_w, (d)->log2_chroma_h))
Referenced by create_filtergraph().
OFFSET
#define OFFSET (x) offsetof(ColorSpaceContext, x)
Definition at line 1051 of file vf_colorspace.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM | AV_OPT_FLAG_VIDEO_PARAM
Definition at line 1052 of file vf_colorspace.c.
ENUM
#define ENUM (x, y, z) { x, "", 0, AV_OPT_TYPE_CONST, { .i64 = y }, INT_MIN, INT_MAX, FLAGS, z }
Definition at line 1053 of file vf_colorspace.c.
Enumeration Type Documentation
DitherMode
enum DitherMode
Enumerator
DITHER_NONE
DITHER_FSB
DITHER_NB
Definition at line 37 of file vf_colorspace.c.
Colorspace
enum Colorspace
Enumerator
CS_UNSPECIFIED
CS_BT470M
CS_BT470BG
CS_BT601_6_525
CS_BT601_6_625
CS_BT709
CS_SMPTE170M
CS_SMPTE240M
CS_BT2020
CS_NB
Definition at line 43 of file vf_colorspace.c.
Whitepoint
enum Whitepoint
Enumerator
WP_D65
WP_C
WP_DCI
WP_NB
Definition at line 56 of file vf_colorspace.c.
WhitepointAdaptation
enum WhitepointAdaptation
Enumerator
WP_ADAPT_BRADFORD
WP_ADAPT_VON_KRIES
NB_WP_ADAPT_NON_IDENTITY
WP_ADAPT_IDENTITY
NB_WP_ADAPT
Definition at line 63 of file vf_colorspace.c.
Function Documentation
get_luma_coefficients()
static const struct LumaCoefficients* get_luma_coefficients (enum AVColorSpace csp) static
Definition at line 203 of file vf_colorspace.c.
Referenced by create_filtergraph().
fill_rgb2yuv_table()
static void fill_rgb2yuv_table (const struct LumaCoefficients * coeffs, double rgb2yuv[3][3]) static
Definition at line 216 of file vf_colorspace.c.
Referenced by create_filtergraph().
get_transfer_characteristics()
static const struct TransferCharacteristics* get_transfer_characteristics (enum AVColorTransferCharacteristic trc) static
Definition at line 256 of file vf_colorspace.c.
Referenced by create_filtergraph().
get_color_primaries()
static const struct ColorPrimaries* get_color_primaries (enum AVColorPrimaries prm) static
Definition at line 287 of file vf_colorspace.c.
Referenced by create_filtergraph().
invert_matrix3x3()
static void invert_matrix3x3 (const double in[3][3], double out[3][3]) static
Definition at line 300 of file vf_colorspace.c.
Referenced by create_filtergraph(), fill_rgb2xyz_table(), and fill_whitepoint_conv_table().
fill_gamma_table()
static int fill_gamma_table (ColorSpaceContext * s) static
Definition at line 327 of file vf_colorspace.c.
Referenced by create_filtergraph().
fill_rgb2xyz_table()
static void fill_rgb2xyz_table (const struct ColorPrimaries * coeffs, double rgb2xyz[3][3]) static
Definition at line 370 of file vf_colorspace.c.
Referenced by create_filtergraph().
mul3x3()
static void mul3x3 (double dst[3][3], const double src1[3][3], const double src2[3][3]) static
Definition at line 399 of file vf_colorspace.c.
Referenced by create_filtergraph(), and fill_whitepoint_conv_table().
fill_whitepoint_conv_table()
static void fill_whitepoint_conv_table (double out[3][3], enum WhitepointAdaptation wp_adapt, enum Whitepoint src, enum Whitepoint dst) static
Definition at line 414 of file vf_colorspace.c.
Referenced by create_filtergraph().
apply_lut()
static void apply_lut (int16_t * buf[3], ptrdiff_t stride, int w, int h, const int16_t * lut) static
Definition at line 451 of file vf_colorspace.c.
Referenced by convert().
convert()
static int convert (AVFilterContext * ctx, void * data, int job_nr, int n_jobs) static
Definition at line 474 of file vf_colorspace.c.
Referenced by filter_frame().
get_range_off()
static int get_range_off (AVFilterContext * ctx, int * off, int * y_rng, int * uv_rng, enum AVColorRange rng, int depth) static
Definition at line 544 of file vf_colorspace.c.
Referenced by create_filtergraph().
create_filtergraph()
static int create_filtergraph (AVFilterContext * ctx, const AVFrame * in, const AVFrame * out) static
Definition at line 574 of file vf_colorspace.c.
Referenced by filter_frame().
init()
static int init (AVFilterContext * ctx) static
Definition at line 866 of file vf_colorspace.c.
uninit()
static void uninit (AVFilterContext * ctx) static
Definition at line 875 of file vf_colorspace.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * link, AVFrame * in) static
Definition at line 893 of file vf_colorspace.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 1004 of file vf_colorspace.c.
config_props()
static int config_props (AVFilterLink * outlink) static
Definition at line 1032 of file vf_colorspace.c.
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (colorspace)
Variable Documentation
default_trc
enum AVColorTransferCharacteristic default_trc[CS_NB+1] static
Initial value:
= {
    [CS_UNSPECIFIED] = AVCOL_TRC_UNSPECIFIED,
    [CS_BT470M]      = AVCOL_TRC_GAMMA22,
    [CS_BT470BG]     = AVCOL_TRC_GAMMA28,
    [CS_BT601_6_525] = AVCOL_TRC_SMPTE170M,
    [CS_BT601_6_625] = AVCOL_TRC_SMPTE170M,
    [CS_BT709]       = AVCOL_TRC_BT709,
    [CS_SMPTE170M]   = AVCOL_TRC_SMPTE170M,
    [CS_SMPTE240M]   = AVCOL_TRC_SMPTE240M,
    [CS_BT2020]      = AVCOL_TRC_BT2020_10,
    [CS_NB]          = AVCOL_TRC_UNSPECIFIED,
}
Definition at line 71 of file vf_colorspace.c.
Referenced by create_filtergraph(), and filter_frame().
default_prm
enum AVColorPrimaries default_prm[CS_NB+1] static
Initial value:
= {
    [CS_UNSPECIFIED] = AVCOL_PRI_UNSPECIFIED,
    [CS_BT470M]      = AVCOL_PRI_BT470M,
    [CS_BT470BG]     = AVCOL_PRI_BT470BG,
    [CS_BT601_6_525] = AVCOL_PRI_SMPTE170M,
    [CS_BT601_6_625] = AVCOL_PRI_BT470BG,
    [CS_BT709]       = AVCOL_PRI_BT709,
    [CS_SMPTE170M]   = AVCOL_PRI_SMPTE170M,
    [CS_SMPTE240M]   = AVCOL_PRI_SMPTE240M,
    [CS_BT2020]      = AVCOL_PRI_BT2020,
    [CS_NB]          = AVCOL_PRI_UNSPECIFIED,
}
Definition at line 84 of file vf_colorspace.c.
Referenced by create_filtergraph(), and filter_frame().
default_csp
enum AVColorSpace default_csp[CS_NB+1] static
Initial value:
= {
    [CS_UNSPECIFIED] = AVCOL_SPC_UNSPECIFIED,
    [CS_BT470M]      = AVCOL_SPC_SMPTE170M,
    [CS_BT470BG]     = AVCOL_SPC_BT470BG,
    [CS_BT601_6_525] = AVCOL_SPC_SMPTE170M,
    [CS_BT601_6_625] = AVCOL_SPC_BT470BG,
    [CS_BT709]       = AVCOL_SPC_BT709,
    [CS_SMPTE170M]   = AVCOL_SPC_SMPTE170M,
    [CS_SMPTE240M]   = AVCOL_SPC_SMPTE240M,
    [CS_BT2020]      = AVCOL_SPC_BT2020_NCL,
    [CS_NB]          = AVCOL_SPC_UNSPECIFIED,
}
Definition at line 97 of file vf_colorspace.c.
Referenced by create_filtergraph(), and filter_frame().
ycgco_matrix
const double ycgco_matrix[3][3] static
Initial value:
=
{
    {  0.25, 0.5,  0.25 },
    { -0.25, 0.5, -0.25 },
    {  0.5,  0,   -0.5  },
}
Definition at line 179 of file vf_colorspace.c.
Referenced by fill_rgb2yuv_table().
luma_coefficients
const struct LumaCoefficients luma_coefficients[AVCOL_SPC_NB] static
Initial value:
= {
    [AVCOL_SPC_FCC]        = { 0.30,   0.59,   0.11   },
    [AVCOL_SPC_BT470BG]    = { 0.299,  0.587,  0.114  },
    [AVCOL_SPC_SMPTE170M]  = { 0.299,  0.587,  0.114  },
    [AVCOL_SPC_BT709]      = { 0.2126, 0.7152, 0.0722 },
    [AVCOL_SPC_SMPTE240M]  = { 0.212,  0.701,  0.087  },
    [AVCOL_SPC_YCOCG]      = { 0.25,   0.5,    0.25   },
    [AVCOL_SPC_BT2020_NCL] = { 0.2627, 0.6780, 0.0593 },
    [AVCOL_SPC_BT2020_CL]  = { 0.2627, 0.6780, 0.0593 },
}
Definition at line 192 of file vf_colorspace.c.
transfer_characteristics
const struct TransferCharacteristics transfer_characteristics[AVCOL_TRC_NB] static
Initial value:
= {
    [AVCOL_TRC_BT709]     = { 1.099,  0.018,  0.45, 4.5 },
    [AVCOL_TRC_GAMMA22]   = { 1.0,    0.0,    1.0 / 2.2, 0.0 },
    [AVCOL_TRC_GAMMA28]   = { 1.0,    0.0,    1.0 / 2.8, 0.0 },
    [AVCOL_TRC_SMPTE170M] = { 1.099,  0.018,  0.45, 4.5 },
    [AVCOL_TRC_SMPTE240M] = { 1.1115, 0.0228, 0.45, 4.0 },
    [AVCOL_TRC_IEC61966_2_1] = { 1.055, 0.0031308, 1.0 / 2.4, 12.92 },
    [AVCOL_TRC_IEC61966_2_4] = { 1.099, 0.018, 0.45, 4.5 },
    [AVCOL_TRC_BT2020_10] = { 1.099,  0.018,  0.45, 4.5 },
    [AVCOL_TRC_BT2020_12] = { 1.0993, 0.0181, 0.45, 4.5 },
}
Definition at line 243 of file vf_colorspace.c.
Referenced by vaapi_encode_h265_write_vui_parameters().
whitepoint_coefficients
const struct WhitepointCoefficients whitepoint_coefficients[WP_NB] static
Initial value:
= {
    [WP_D65] = { 0.3127, 0.3290 },
    [WP_C]   = { 0.3100, 0.3160 },
    [WP_DCI] = { 0.3140, 0.3510 },
}
Definition at line 269 of file vf_colorspace.c.
color_primaries
const struct ColorPrimaries color_primaries[AVCOL_PRI_NB] static
Initial value:
= {
    [AVCOL_PRI_BT709]     = { WP_D65, 0.640, 0.330, 0.300, 0.600, 0.150, 0.060 },
    [AVCOL_PRI_BT470M]    = { WP_C,   0.670, 0.330, 0.210, 0.710, 0.140, 0.080 },
    [AVCOL_PRI_BT470BG]   = { WP_D65, 0.640, 0.330, 0.290, 0.600, 0.150, 0.060,},
    [AVCOL_PRI_SMPTE170M] = { WP_D65, 0.630, 0.340, 0.310, 0.595, 0.155, 0.070 },
    [AVCOL_PRI_SMPTE240M] = { WP_D65, 0.630, 0.340, 0.310, 0.595, 0.155, 0.070 },
    [AVCOL_PRI_SMPTE431]  = { WP_DCI, 0.680, 0.320, 0.265, 0.690, 0.150, 0.060 },
    [AVCOL_PRI_SMPTE432]  = { WP_D65, 0.680, 0.320, 0.265, 0.690, 0.150, 0.060 },
    [AVCOL_PRI_FILM]      = { WP_C,   0.681, 0.319, 0.243, 0.692, 0.145, 0.049 },
    [AVCOL_PRI_BT2020]    = { WP_D65, 0.708, 0.292, 0.170, 0.797, 0.131, 0.046 },
}
Definition at line 275 of file vf_colorspace.c.
Referenced by mov_read_colr().
colorspace_options
const AVOption colorspace_options[] static
Definition at line 1055 of file vf_colorspace.c.
inputs
const AVFilterPad inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 1168 of file vf_colorspace.c.
outputs
const AVFilterPad outputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .config_props = config_props,
    },
    { NULL }
}
Definition at line 1177 of file vf_colorspace.c.
ff_vf_colorspace
AVFilter ff_vf_colorspace
Initial value:
= {
    .name            = "colorspace",
    .description     = NULL_IF_CONFIG_SMALL("Convert between colorspaces."),
    .init            = init,
    .uninit          = uninit,
    .query_formats   = query_formats,
    .priv_size       = sizeof(ColorSpaceContext),
    .priv_class      = &colorspace_class,
    .inputs          = inputs,
    .outputs         = outputs,
    .flags           = AVFILTER_FLAG_SUPPORT_TIMELINE_GENERIC | AVFILTER_FLAG_SLICE_THREADS,
}
Definition at line 1186 of file vf_colorspace.c.