FFmpeg: libavcodec/mpc8.c File Reference
mpc8.c File Reference
MPEG Audio Layer 1/2 -like codec with frames of 1152 samples divided into 32 subbands.
#include "libavutil/channel_layout.h"
#include "libavutil/lfg.h"
#include "avcodec.h"
#include "get_bits.h"
#include "internal.h"
#include "mpegaudiodsp.h"
#include "mpc.h"
#include "mpc8data.h"
#include "mpc8huff.h"
Functions
static int mpc8_dec_base (GetBitContext *gb, int k, int n)
static int mpc8_dec_enum (GetBitContext *gb, int k, int n)
static int mpc8_get_mod_golomb (GetBitContext *gb, int m)
static int mpc8_get_mask (GetBitContext *gb, int size, int t)
static av_cold int mpc8_decode_init (AVCodecContext *avctx)
static int mpc8_decode_frame (AVCodecContext *avctx, void *data, int *got_frame_ptr, AVPacket *avpkt)
static av_cold void mpc8_decode_flush (AVCodecContext *avctx)
Variables
static VLC band_vlc
static VLC scfi_vlc [2]
static VLC dscf_vlc [2]
static VLC res_vlc [2]
static VLC q1_vlc
static VLC q2_vlc [2]
static VLC q3_vlc [2]
static VLC quant_vlc [4][2]
static VLC q9up_vlc
static const int q3_offsets [2] = { MPC8_Q3_OFFSET, MPC8_Q4_OFFSET }
static const int quant_offsets [6] = { MPC8_Q5_OFFSET, MPC8_Q6_OFFSET, MPC8_Q7_OFFSET, MPC8_Q8_OFFSET }
static const uint16_t vlc_offsets [13]
AVCodec ff_mpc8_decoder
Detailed Description
MPEG Audio Layer 1/2 -like codec with frames of 1152 samples divided into 32 subbands.
Definition in file mpc8.c.
Function Documentation
mpc8_dec_base()
static int mpc8_dec_base (GetBitContext * gb, int k, int n) inline static
Definition at line 45 of file mpc8.c.
Referenced by mpc8_dec_enum(), and mpc8_get_mod_golomb().
mpc8_dec_enum()
static int mpc8_dec_enum (GetBitContext * gb, int k, int n) inline static
Definition at line 56 of file mpc8.c.
Referenced by mpc8_get_mask().
mpc8_get_mod_golomb()
static int mpc8_get_mod_golomb (GetBitContext * gb, int m) inline static
Definition at line 75 of file mpc8.c.
Referenced by mpc8_decode_frame().
mpc8_get_mask()
static int mpc8_get_mask (GetBitContext * gb, int size, int t) static
Definition at line 81 of file mpc8.c.
Referenced by mpc8_decode_frame().
mpc8_decode_init()
static av_cold int mpc8_decode_init (AVCodecContext * avctx) static
Definition at line 96 of file mpc8.c.
mpc8_decode_frame()
static int mpc8_decode_frame (AVCodecContext * avctx, void * data, int * got_frame_ptr, AVPacket * avpkt) static
Definition at line 239 of file mpc8.c.
mpc8_decode_flush()
static av_cold void mpc8_decode_flush (AVCodecContext * avctx) static
Definition at line 432 of file mpc8.c.
Variable Documentation
band_vlc
VLC band_vlc static
Definition at line 39 of file mpc8.c.
scfi_vlc
VLC scfi_vlc[2] static
Definition at line 39 of file mpc8.c.
dscf_vlc
VLC dscf_vlc[2] static
Definition at line 39 of file mpc8.c.
res_vlc
VLC res_vlc[2] static
Definition at line 39 of file mpc8.c.
q1_vlc
VLC q1_vlc static
Definition at line 40 of file mpc8.c.
q2_vlc
VLC q2_vlc[2] static
Definition at line 40 of file mpc8.c.
q3_vlc
VLC q3_vlc[2] static
Definition at line 40 of file mpc8.c.
quant_vlc
VLC quant_vlc[4][2] static
Definition at line 40 of file mpc8.c.
q9up_vlc
VLC q9up_vlc static
Definition at line 40 of file mpc8.c.
q3_offsets
const int q3_offsets[2] = { MPC8_Q3_OFFSET, MPC8_Q4_OFFSET } static
Definition at line 42 of file mpc8.c.
Referenced by mpc8_decode_frame().
quant_offsets
const int quant_offsets[6] = { MPC8_Q5_OFFSET, MPC8_Q6_OFFSET, MPC8_Q7_OFFSET, MPC8_Q8_OFFSET } static
Definition at line 43 of file mpc8.c.
Referenced by mpc8_decode_frame().
vlc_offsets
const uint16_t vlc_offsets[13] static
Initial value:
= {
    0, 640, 1184, 1748, 2298, 2426, 2554, 3066, 3578, 4106, 4618, 5196, 5708
}
Definition at line 92 of file mpc8.c.
Referenced by mpc8_decode_init().
ff_mpc8_decoder
AVCodec ff_mpc8_decoder
Initial value:
= {
    .name           = "mpc8",
    .long_name      = NULL_IF_CONFIG_SMALL("Musepack SV8"),
    .type           = AVMEDIA_TYPE_AUDIO,
    .id             = AV_CODEC_ID_MUSEPACK8,
    .priv_data_size = sizeof(MPCContext),
    .init           = mpc8_decode_init,
    .decode         = mpc8_decode_frame,
    .flush          = mpc8_decode_flush,
    .capabilities   = AV_CODEC_CAP_DR1,
    .sample_fmts    = (const enum AVSampleFormat[]) { AV_SAMPLE_FMT_S16P,
                                                      AV_SAMPLE_FMT_NONE },
}
Definition at line 438 of file mpc8.c.