FFmpeg: libavcodec/hevc.h File Reference
hevc.h File Reference
#include "libavutil/buffer.h"
#include "libavutil/md5.h"
#include "avcodec.h"
#include "bswapdsp.h"
#include "cabac.h"
#include "get_bits.h"
#include "hevcpred.h"
#include "h2645_parse.h"
#include "hevcdsp.h"
#include "internal.h"
#include "thread.h"
#include "videodsp.h"
Data Structures
struct ShortTermRPS
struct LongTermRPS
struct RefPicList
struct RefPicListTab
struct HEVCWindow
struct VUI
struct PTLCommon
struct PTL
struct HEVCVPS
struct ScalingList
struct HEVCSPS
struct HEVCPPS
struct HEVCParamSets
struct SliceHeader
struct CodingUnit
struct Mv
struct MvField
struct NeighbourAvailable
struct PredictionUnit
struct TransformUnit
struct DBParams
struct HEVCFrame
struct HEVCLocalContext
struct HEVCContext
Macros
#define MAX_DPB_SIZE 16
#define MAX_REFS 16
#define MAX_NB_THREADS 16
#define SHIFT_CTB_WPP 2
#define MAX_SUB_LAYERS 7
7.4.2.1
#define MAX_VPS_COUNT 16
#define MAX_SPS_COUNT 32
#define MAX_PPS_COUNT 256
#define MAX_SHORT_TERM_RPS_COUNT 64
#define MAX_CU_SIZE 128
#define MAX_TRANSFORM_DEPTH 5
#define MAX_TB_SIZE 32
#define MAX_LOG2_CTB_SIZE 6
#define MAX_QP 51
#define DEFAULT_INTRA_TC_OFFSET 2
#define HEVC_CONTEXTS 199
#define MRG_MAX_NUM_CANDS 5
#define L0 0
#define L1 1
#define EPEL_EXTRA_BEFORE 1
#define EPEL_EXTRA_AFTER 2
#define EPEL_EXTRA 3
#define QPEL_EXTRA_BEFORE 3
#define QPEL_EXTRA_AFTER 4
#define QPEL_EXTRA 7
#define EDGE_EMU_BUFFER_STRIDE 80
#define SAMPLE(tab, x, y) ((tab)[(y) * s->sps->width + (x)])
Value of the luma sample at position (x, y) in the 2D array tab.
#define SAMPLE_CTB(tab, x, y) ((tab)[(y) * min_cb_width + (x)])
#define IS_IDR(s) ((s)->nal_unit_type == NAL_IDR_W_RADL || (s)->nal_unit_type == NAL_IDR_N_LP)
#define IS_BLA(s)
#define IS_IRAP(s) ((s)->nal_unit_type >= 16 && (s)->nal_unit_type <= 23)
#define HEVC_FRAME_FLAG_OUTPUT (1 << 0)
#define HEVC_FRAME_FLAG_SHORT_REF (1 << 1)
#define HEVC_FRAME_FLAG_LONG_REF (1 << 2)
#define HEVC_FRAME_FLAG_BUMPING (1 << 3)
#define BOUNDARY_LEFT_SLICE (1 << 0)
#define BOUNDARY_LEFT_TILE (1 << 1)
#define BOUNDARY_UPPER_SLICE (1 << 2)
#define BOUNDARY_UPPER_TILE (1 << 3)
Enumerations
enum NALUnitType {
NAL_TRAIL_N = 0, NAL_TRAIL_R = 1, NAL_TSA_N = 2, NAL_TSA_R = 3,
NAL_STSA_N = 4, NAL_STSA_R = 5, NAL_RADL_N = 6, NAL_RADL_R = 7,
NAL_RASL_N = 8, NAL_RASL_R = 9, NAL_BLA_W_LP = 16, NAL_BLA_W_RADL = 17,
NAL_BLA_N_LP = 18, NAL_IDR_W_RADL = 19, NAL_IDR_N_LP = 20, NAL_CRA_NUT = 21,
NAL_VPS = 32, NAL_SPS = 33, NAL_PPS = 34, NAL_AUD = 35,
NAL_EOS_NUT = 36, NAL_EOB_NUT = 37, NAL_FD_NUT = 38, NAL_SEI_PREFIX = 39,
NAL_SEI_SUFFIX = 40
}
Table 7-3: NAL unit type codes.
enum RPSType {
ST_CURR_BEF = 0, ST_CURR_AFT, ST_FOLL, LT_CURR,
LT_FOLL, NB_RPS_TYPE
}
enum SliceType { B_SLICE = 0, P_SLICE = 1, I_SLICE = 2 }
enum SyntaxElement {
SAO_MERGE_FLAG = 0, SAO_TYPE_IDX, SAO_EO_CLASS, SAO_BAND_POSITION,
SAO_OFFSET_ABS, SAO_OFFSET_SIGN, END_OF_SLICE_FLAG, SPLIT_CODING_UNIT_FLAG,
CU_TRANSQUANT_BYPASS_FLAG, SKIP_FLAG, CU_QP_DELTA, PRED_MODE_FLAG,
PART_MODE, PCM_FLAG, PREV_INTRA_LUMA_PRED_FLAG, MPM_IDX,
REM_INTRA_LUMA_PRED_MODE, INTRA_CHROMA_PRED_MODE, MERGE_FLAG, MERGE_IDX,
INTER_PRED_IDC, REF_IDX_L0, REF_IDX_L1, ABS_MVD_GREATER0_FLAG,
ABS_MVD_GREATER1_FLAG, ABS_MVD_MINUS2, MVD_SIGN_FLAG, MVP_LX_FLAG,
NO_RESIDUAL_DATA_FLAG, SPLIT_TRANSFORM_FLAG, CBF_LUMA, CBF_CB_CR,
TRANSFORM_SKIP_FLAG, EXPLICIT_RDPCM_FLAG, EXPLICIT_RDPCM_DIR_FLAG, LAST_SIGNIFICANT_COEFF_X_PREFIX,
LAST_SIGNIFICANT_COEFF_Y_PREFIX, LAST_SIGNIFICANT_COEFF_X_SUFFIX, LAST_SIGNIFICANT_COEFF_Y_SUFFIX, SIGNIFICANT_COEFF_GROUP_FLAG,
SIGNIFICANT_COEFF_FLAG, COEFF_ABS_LEVEL_GREATER1_FLAG, COEFF_ABS_LEVEL_GREATER2_FLAG, COEFF_ABS_LEVEL_REMAINING,
COEFF_SIGN_FLAG, LOG2_RES_SCALE_ABS, RES_SCALE_SIGN_FLAG, CU_CHROMA_QP_OFFSET_FLAG,
CU_CHROMA_QP_OFFSET_IDX
}
enum PartMode {
PART_2Nx2N = 0, PART_2NxN = 1, PART_Nx2N = 2, PART_NxN = 3,
PART_2NxnU = 4, PART_2NxnD = 5, PART_nLx2N = 6, PART_nRx2N = 7
}
enum PredMode { MODE_INTER = 0, MODE_INTRA, MODE_SKIP }
enum InterPredIdc { PRED_L0 = 0, PRED_L1, PRED_BI }
enum PredFlag { PF_INTRA = 0, PF_L0, PF_L1, PF_BI }
enum IntraPredMode {
INTRA_PLANAR = 0, INTRA_DC, INTRA_ANGULAR_2, INTRA_ANGULAR_3,
INTRA_ANGULAR_4, INTRA_ANGULAR_5, INTRA_ANGULAR_6, INTRA_ANGULAR_7,
INTRA_ANGULAR_8, INTRA_ANGULAR_9, INTRA_ANGULAR_10, INTRA_ANGULAR_11,
INTRA_ANGULAR_12, INTRA_ANGULAR_13, INTRA_ANGULAR_14, INTRA_ANGULAR_15,
INTRA_ANGULAR_16, INTRA_ANGULAR_17, INTRA_ANGULAR_18, INTRA_ANGULAR_19,
INTRA_ANGULAR_20, INTRA_ANGULAR_21, INTRA_ANGULAR_22, INTRA_ANGULAR_23,
INTRA_ANGULAR_24, INTRA_ANGULAR_25, INTRA_ANGULAR_26, INTRA_ANGULAR_27,
INTRA_ANGULAR_28, INTRA_ANGULAR_29, INTRA_ANGULAR_30, INTRA_ANGULAR_31,
INTRA_ANGULAR_32, INTRA_ANGULAR_33, INTRA_ANGULAR_34, VERT_PRED,
HOR_PRED, DC_PRED, DIAG_DOWN_LEFT_PRED, DIAG_DOWN_RIGHT_PRED,
VERT_RIGHT_PRED, HOR_DOWN_PRED, VERT_LEFT_PRED, HOR_UP_PRED,
TM_VP8_PRED, LEFT_DC_PRED, TOP_DC_PRED, DC_128_PRED,
DC_127_PRED, DC_129_PRED, N_INTRA_PRED_MODES
}
enum SAOType { SAO_NOT_APPLIED = 0, SAO_BAND, SAO_EDGE, SAO_APPLIED }
enum SAOEOClass { SAO_EO_HORIZ = 0, SAO_EO_VERT, SAO_EO_135D, SAO_EO_45D }
enum ScanType { SCAN_DIAG = 0, SCAN_HORIZ, SCAN_VERT }
Functions
int ff_hevc_decode_short_term_rps (GetBitContext *gb, AVCodecContext *avctx, ShortTermRPS *rps, const HEVCSPS *sps, int is_slice_header)
int ff_hevc_parse_sps (HEVCSPS *sps, GetBitContext *gb, unsigned int *sps_id, int apply_defdispwin, AVBufferRef **vps_list, AVCodecContext *avctx)
Parse the SPS from the bitstream into the provided HEVCSPS struct.
int ff_hevc_decode_nal_vps (GetBitContext *gb, AVCodecContext *avctx, HEVCParamSets *ps)
int ff_hevc_decode_nal_sps (GetBitContext *gb, AVCodecContext *avctx, HEVCParamSets *ps, int apply_defdispwin)
int ff_hevc_decode_nal_pps (GetBitContext *gb, AVCodecContext *avctx, HEVCParamSets *ps)
int ff_hevc_decode_nal_sei (HEVCContext *s)
void ff_hevc_clear_refs (HEVCContext *s)
Mark all frames in DPB as unused for reference.
void ff_hevc_flush_dpb (HEVCContext *s)
Drop all frames currently in DPB.
int ff_hevc_compute_poc (HEVCContext *s, int poc_lsb)
Compute POC of the current frame and return it.
RefPicList * ff_hevc_get_ref_list (HEVCContext *s, HEVCFrame *frame, int x0, int y0)
int ff_hevc_frame_rps (HEVCContext *s)
Construct the reference picture sets for the current frame.
int ff_hevc_slice_rpl (HEVCContext *s)
Construct the reference picture list(s) for the current slice.
void ff_hevc_save_states (HEVCContext *s, int ctb_addr_ts)
void ff_hevc_cabac_init (HEVCContext *s, int ctb_addr_ts)
int ff_hevc_sao_merge_flag_decode (HEVCContext *s)
int ff_hevc_sao_type_idx_decode (HEVCContext *s)
int ff_hevc_sao_band_position_decode (HEVCContext *s)
int ff_hevc_sao_offset_abs_decode (HEVCContext *s)
int ff_hevc_sao_offset_sign_decode (HEVCContext *s)
int ff_hevc_sao_eo_class_decode (HEVCContext *s)
int ff_hevc_end_of_slice_flag_decode (HEVCContext *s)
int ff_hevc_cu_transquant_bypass_flag_decode (HEVCContext *s)
int ff_hevc_skip_flag_decode (HEVCContext *s, int x0, int y0, int x_cb, int y_cb)
int ff_hevc_pred_mode_decode (HEVCContext *s)
int ff_hevc_split_coding_unit_flag_decode (HEVCContext *s, int ct_depth, int x0, int y0)
int ff_hevc_part_mode_decode (HEVCContext *s, int log2_cb_size)
int ff_hevc_pcm_flag_decode (HEVCContext *s)
int ff_hevc_prev_intra_luma_pred_flag_decode (HEVCContext *s)
int ff_hevc_mpm_idx_decode (HEVCContext *s)
int ff_hevc_rem_intra_luma_pred_mode_decode (HEVCContext *s)
int ff_hevc_intra_chroma_pred_mode_decode (HEVCContext *s)
int ff_hevc_merge_idx_decode (HEVCContext *s)
int ff_hevc_merge_flag_decode (HEVCContext *s)
int ff_hevc_inter_pred_idc_decode (HEVCContext *s, int nPbW, int nPbH)
int ff_hevc_ref_idx_lx_decode (HEVCContext *s, int num_ref_idx_lx)
int ff_hevc_mvp_lx_flag_decode (HEVCContext *s)
int ff_hevc_no_residual_syntax_flag_decode (HEVCContext *s)
int ff_hevc_split_transform_flag_decode (HEVCContext *s, int log2_trafo_size)
int ff_hevc_cbf_cb_cr_decode (HEVCContext *s, int trafo_depth)
int ff_hevc_cbf_luma_decode (HEVCContext *s, int trafo_depth)
int ff_hevc_log2_res_scale_abs (HEVCContext *s, int idx)
int ff_hevc_res_scale_sign_flag (HEVCContext *s, int idx)
int ff_hevc_frame_nb_refs (HEVCContext *s)
Get the number of candidate references for the current frame.
int ff_hevc_set_new_ref (HEVCContext *s, AVFrame **frame, int poc)
int ff_hevc_output_frame (HEVCContext *s, AVFrame *frame, int flush)
Find next frame in output order and put a reference to it in frame.
void ff_hevc_bump_frame (HEVCContext *s)
void ff_hevc_unref_frame (HEVCContext *s, HEVCFrame *frame, int flags)
void ff_hevc_set_neighbour_available (HEVCContext *s, int x0, int y0, int nPbW, int nPbH)
void ff_hevc_luma_mv_merge_mode (HEVCContext *s, int x0, int y0, int nPbW, int nPbH, int log2_cb_size, int part_idx, int merge_idx, MvField *mv)
void ff_hevc_luma_mv_mvp_mode (HEVCContext *s, int x0, int y0, int nPbW, int nPbH, int log2_cb_size, int part_idx, int merge_idx, MvField *mv, int mvp_lx_flag, int LX)
void ff_hevc_set_qPy (HEVCContext *s, int xBase, int yBase, int log2_cb_size)
void ff_hevc_deblocking_boundary_strengths (HEVCContext *s, int x0, int y0, int log2_trafo_size)
int ff_hevc_cu_qp_delta_sign_flag (HEVCContext *s)
int ff_hevc_cu_qp_delta_abs (HEVCContext *s)
int ff_hevc_cu_chroma_qp_offset_flag (HEVCContext *s)
int ff_hevc_cu_chroma_qp_offset_idx (HEVCContext *s)
void ff_hevc_hls_filter (HEVCContext *s, int x, int y, int ctb_size)
void ff_hevc_hls_filters (HEVCContext *s, int x_ctb, int y_ctb, int ctb_size)
void ff_hevc_hls_residual_coding (HEVCContext *s, int x0, int y0, int log2_trafo_size, enum ScanType scan_idx, int c_idx)
void ff_hevc_hls_mvd_coding (HEVCContext *s, int x0, int y0, int log2_cb_size)
int ff_hevc_encode_nal_vps (HEVCVPS *vps, unsigned int id, uint8_t *buf, int buf_size)
void ff_hevc_reset_sei (HEVCContext *s)
Reset SEI values that are stored on the Context.
Variables
const uint8_t ff_hevc_qpel_extra_before [4]
const uint8_t ff_hevc_qpel_extra_after [4]
const uint8_t ff_hevc_qpel_extra [4]
const uint8_t ff_hevc_diag_scan4x4_x [16]
const uint8_t ff_hevc_diag_scan4x4_y [16]
const uint8_t ff_hevc_diag_scan8x8_x [64]
const uint8_t ff_hevc_diag_scan8x8_y [64]
Macro Definition Documentation
MAX_DPB_SIZE
#define MAX_DPB_SIZE 16
Definition at line 40 of file hevc.h.
Referenced by ff_hevc_decode_nal_vps(), and ff_hevc_parse_sps().
MAX_REFS
#define MAX_REFS 16
Definition at line 41 of file hevc.h.
Referenced by ff_hevc_decode_short_term_rps(), ff_hevc_slice_rpl(), and hls_slice_header().
MAX_NB_THREADS
#define MAX_NB_THREADS 16
Definition at line 43 of file hevc.h.
SHIFT_CTB_WPP
#define SHIFT_CTB_WPP 2
Definition at line 44 of file hevc.h.
Referenced by hls_decode_entry_wpp().
MAX_SUB_LAYERS
#define MAX_SUB_LAYERS 7
7.4.2.1
Definition at line 49 of file hevc.h.
Referenced by ff_hevc_decode_nal_vps(), ff_hevc_parse_sps(), generate_fake_vps(), and hvcc_parse_ptl().
MAX_VPS_COUNT
#define MAX_VPS_COUNT 16
Definition at line 50 of file hevc.h.
Referenced by ff_hevc_decode_nal_vps(), ff_hevc_parse_sps(), hvcc_write(), and mediacodec_decode_close().
MAX_SPS_COUNT
#define MAX_SPS_COUNT 32
Definition at line 51 of file hevc.h.
MAX_PPS_COUNT
#define MAX_PPS_COUNT 256
Definition at line 52 of file hevc.h.
MAX_SHORT_TERM_RPS_COUNT
#define MAX_SHORT_TERM_RPS_COUNT 64
Definition at line 53 of file hevc.h.
Referenced by ff_hevc_parse_sps(), and hvcc_parse_sps().
MAX_CU_SIZE
#define MAX_CU_SIZE 128
Definition at line 54 of file hevc.h.
MAX_TRANSFORM_DEPTH
#define MAX_TRANSFORM_DEPTH 5
Definition at line 57 of file hevc.h.
MAX_TB_SIZE
#define MAX_TB_SIZE 32
Definition at line 59 of file hevc.h.
Referenced by intra_pred(), and pred_angular().
MAX_LOG2_CTB_SIZE
#define MAX_LOG2_CTB_SIZE 6
Definition at line 60 of file hevc.h.
Referenced by ff_hevc_parse_sps().
MAX_QP
#define MAX_QP 51
Definition at line 61 of file hevc.h.
Referenced by deblocking_filter_CTB().
DEFAULT_INTRA_TC_OFFSET
#define DEFAULT_INTRA_TC_OFFSET 2
Definition at line 62 of file hevc.h.
Referenced by chroma_tc().
HEVC_CONTEXTS
#define HEVC_CONTEXTS 199
Definition at line 64 of file hevc.h.
Referenced by cabac_init_state(), ff_hevc_save_states(), hevc_init_context(), and load_states().
MRG_MAX_NUM_CANDS
#define MRG_MAX_NUM_CANDS 5
Definition at line 66 of file hevc.h.
Referenced by ff_hevc_luma_mv_merge_mode().
L0
#define L0 0
Definition at line 68 of file hevc.h.
Referenced by fill_pred_weight_table(), hevc_luma_mv_mvp_mode(), hls_slice_header(), pred_weight_table(), and vaapi_hevc_decode_slice().
L1
#define L1 1
Definition at line 69 of file hevc.h.
Referenced by derive_temporal_colocated_mvs(), fill_pred_weight_table(), hevc_luma_mv_mvp_mode(), hls_slice_header(), pred_weight_table(), and vaapi_hevc_decode_slice().
EPEL_EXTRA_BEFORE
#define EPEL_EXTRA_BEFORE 1
Definition at line 71 of file hevc.h.
Referenced by chroma_mc_bi(), chroma_mc_uni(), put_hevc_epel_bi_hv(), put_hevc_epel_bi_w_hv(), put_hevc_epel_hv(), put_hevc_epel_uni_hv(), and put_hevc_epel_uni_w_hv().
EPEL_EXTRA_AFTER
#define EPEL_EXTRA_AFTER 2
Definition at line 72 of file hevc.h.
Referenced by chroma_mc_bi(), and chroma_mc_uni().
EPEL_EXTRA
#define EPEL_EXTRA 3
Definition at line 73 of file hevc.h.
Referenced by chroma_mc_bi(), chroma_mc_uni(), put_hevc_epel_bi_hv(), put_hevc_epel_bi_w_hv(), put_hevc_epel_hv(), put_hevc_epel_uni_hv(), and put_hevc_epel_uni_w_hv().
QPEL_EXTRA_BEFORE
#define QPEL_EXTRA_BEFORE 3
Definition at line 74 of file hevc.h.
Referenced by luma_mc_bi(), luma_mc_uni(), put_hevc_qpel_bi_hv(), put_hevc_qpel_bi_w_hv(), put_hevc_qpel_hv(), put_hevc_qpel_uni_hv(), and put_hevc_qpel_uni_w_hv().
QPEL_EXTRA_AFTER
#define QPEL_EXTRA_AFTER 4
Definition at line 75 of file hevc.h.
Referenced by luma_mc_bi(), and luma_mc_uni().
QPEL_EXTRA
#define QPEL_EXTRA 7
Definition at line 76 of file hevc.h.
Referenced by luma_mc_bi(), luma_mc_uni(), put_hevc_qpel_bi_hv(), put_hevc_qpel_bi_w_hv(), put_hevc_qpel_hv(), put_hevc_qpel_uni_hv(), and put_hevc_qpel_uni_w_hv().
EDGE_EMU_BUFFER_STRIDE
#define EDGE_EMU_BUFFER_STRIDE 80
Definition at line 78 of file hevc.h.
Referenced by chroma_mc_bi(), chroma_mc_uni(), luma_mc_bi(), and luma_mc_uni().
SAMPLE
#define SAMPLE (tab, x, y) ((tab)[(y) * s->sps->width + (x)])
Value of the luma sample at position (x, y) in the 2D array tab.
Definition at line 83 of file hevc.h.
SAMPLE_CTB
#define SAMPLE_CTB (tab, x, y) ((tab)[(y) * min_cb_width + (x)])
Definition at line 84 of file hevc.h.
Referenced by ff_hevc_skip_flag_decode(), hls_coding_unit(), and hls_prediction_unit().
IS_IDR
#define IS_IDR (s) ((s)->nal_unit_type == NAL_IDR_W_RADL || (s)->nal_unit_type == NAL_IDR_N_LP)
Definition at line 86 of file hevc.h.
Referenced by decode_nal_unit(), fill_picture_parameters(), hevc_find_frame_end(), hls_slice_header(), and vdpau_hevc_start_frame().
IS_BLA
#define IS_BLA (s)
Value:
((s)->nal_unit_type == NAL_BLA_W_RADL || (s)->nal_unit_type == NAL_BLA_W_LP || \
                   (s)->nal_unit_type == NAL_BLA_N_LP)
Definition at line 87 of file hevc.h.
Referenced by decode_nal_unit(), find_ref_idx(), and hls_slice_header().
IS_IRAP
#define IS_IRAP (s) ((s)->nal_unit_type >= 16 && (s)->nal_unit_type <= 23)
Definition at line 89 of file hevc.h.
Referenced by fill_picture_parameters(), hevc_find_frame_end(), hevc_frame_start(), hls_slice_header(), set_side_data(), and vdpau_hevc_start_frame().
HEVC_FRAME_FLAG_OUTPUT
#define HEVC_FRAME_FLAG_OUTPUT (1 << 0)
Definition at line 723 of file hevc.h.
Referenced by ff_hevc_bump_frame(), ff_hevc_output_frame(), and ff_hevc_set_new_ref().
HEVC_FRAME_FLAG_SHORT_REF
#define HEVC_FRAME_FLAG_SHORT_REF (1 << 1)
Definition at line 724 of file hevc.h.
Referenced by ff_hevc_clear_refs(), ff_hevc_frame_rps(), ff_hevc_set_new_ref(), fill_picture_parameters(), fill_vaapi_ReferenceFrames(), mark_ref(), and vdpau_hevc_start_frame().
HEVC_FRAME_FLAG_LONG_REF
#define HEVC_FRAME_FLAG_LONG_REF (1 << 2)
Definition at line 725 of file hevc.h.
Referenced by ff_hevc_clear_refs(), ff_hevc_frame_rps(), fill_picture_parameters(), fill_vaapi_pic(), fill_vaapi_ReferenceFrames(), mark_ref(), and vdpau_hevc_start_frame().
HEVC_FRAME_FLAG_BUMPING
#define HEVC_FRAME_FLAG_BUMPING (1 << 3)
Definition at line 726 of file hevc.h.
Referenced by ff_hevc_bump_frame(), and ff_hevc_output_frame().
BOUNDARY_LEFT_SLICE
#define BOUNDARY_LEFT_SLICE (1 << 0)
Definition at line 793 of file hevc.h.
Referenced by ff_hevc_deblocking_boundary_strengths(), and hls_decode_neighbour().
BOUNDARY_LEFT_TILE
#define BOUNDARY_LEFT_TILE (1 << 1)
Definition at line 794 of file hevc.h.
Referenced by ff_hevc_deblocking_boundary_strengths(), and hls_decode_neighbour().
BOUNDARY_UPPER_SLICE
#define BOUNDARY_UPPER_SLICE (1 << 2)
Definition at line 795 of file hevc.h.
Referenced by ff_hevc_deblocking_boundary_strengths(), and hls_decode_neighbour().
BOUNDARY_UPPER_TILE
#define BOUNDARY_UPPER_TILE (1 << 3)
Definition at line 796 of file hevc.h.
Referenced by ff_hevc_deblocking_boundary_strengths(), and hls_decode_neighbour().
Enumeration Type Documentation
NALUnitType
enum NALUnitType
Table 7-3: NAL unit type codes.
Enumerator
NAL_TRAIL_N
NAL_TRAIL_R
NAL_TSA_N
NAL_TSA_R
NAL_STSA_N
NAL_STSA_R
NAL_RADL_N
NAL_RADL_R
NAL_RASL_N
NAL_RASL_R
NAL_BLA_W_LP
NAL_BLA_W_RADL
NAL_BLA_N_LP
NAL_IDR_W_RADL
NAL_IDR_N_LP
NAL_CRA_NUT
NAL_VPS
NAL_SPS
NAL_PPS
NAL_AUD
NAL_EOS_NUT
NAL_EOB_NUT
NAL_FD_NUT
NAL_SEI_PREFIX
NAL_SEI_SUFFIX
Definition at line 94 of file hevc.h.
RPSType
enum RPSType
Enumerator
ST_CURR_BEF
ST_CURR_AFT
ST_FOLL
LT_CURR
LT_FOLL
NB_RPS_TYPE
Definition at line 122 of file hevc.h.
SliceType
enum SliceType
Enumerator
B_SLICE
P_SLICE
I_SLICE
Definition at line 131 of file hevc.h.
SyntaxElement
enum SyntaxElement
Enumerator
SAO_MERGE_FLAG
SAO_TYPE_IDX
SAO_EO_CLASS
SAO_BAND_POSITION
SAO_OFFSET_ABS
SAO_OFFSET_SIGN
END_OF_SLICE_FLAG
SPLIT_CODING_UNIT_FLAG
CU_TRANSQUANT_BYPASS_FLAG
SKIP_FLAG
CU_QP_DELTA
PRED_MODE_FLAG
PART_MODE
PCM_FLAG
PREV_INTRA_LUMA_PRED_FLAG
MPM_IDX
REM_INTRA_LUMA_PRED_MODE
INTRA_CHROMA_PRED_MODE
MERGE_FLAG
MERGE_IDX
INTER_PRED_IDC
REF_IDX_L0
REF_IDX_L1
ABS_MVD_GREATER0_FLAG
ABS_MVD_GREATER1_FLAG
ABS_MVD_MINUS2
MVD_SIGN_FLAG
MVP_LX_FLAG
NO_RESIDUAL_DATA_FLAG
SPLIT_TRANSFORM_FLAG
CBF_LUMA
CBF_CB_CR
TRANSFORM_SKIP_FLAG
EXPLICIT_RDPCM_FLAG
EXPLICIT_RDPCM_DIR_FLAG
LAST_SIGNIFICANT_COEFF_X_PREFIX
LAST_SIGNIFICANT_COEFF_Y_PREFIX
LAST_SIGNIFICANT_COEFF_X_SUFFIX
LAST_SIGNIFICANT_COEFF_Y_SUFFIX
SIGNIFICANT_COEFF_GROUP_FLAG
SIGNIFICANT_COEFF_FLAG
COEFF_ABS_LEVEL_GREATER1_FLAG
COEFF_ABS_LEVEL_GREATER2_FLAG
COEFF_ABS_LEVEL_REMAINING
COEFF_SIGN_FLAG
LOG2_RES_SCALE_ABS
RES_SCALE_SIGN_FLAG
CU_CHROMA_QP_OFFSET_FLAG
CU_CHROMA_QP_OFFSET_IDX
Definition at line 137 of file hevc.h.
PartMode
enum PartMode
Enumerator
PART_2Nx2N
PART_2NxN
PART_Nx2N
PART_NxN
PART_2NxnU
PART_2NxnD
PART_nLx2N
PART_nRx2N
Definition at line 189 of file hevc.h.
PredMode
enum PredMode
Enumerator
MODE_INTER
MODE_INTRA
MODE_SKIP
Definition at line 200 of file hevc.h.
InterPredIdc
enum InterPredIdc
Enumerator
PRED_L0
PRED_L1
PRED_BI
Definition at line 206 of file hevc.h.
PredFlag
enum PredFlag
Enumerator
PF_INTRA
PF_L0
PF_L1
PF_BI
Definition at line 212 of file hevc.h.
IntraPredMode
enum IntraPredMode
Enumerator
INTRA_PLANAR
INTRA_DC
INTRA_ANGULAR_2
INTRA_ANGULAR_3
INTRA_ANGULAR_4
INTRA_ANGULAR_5
INTRA_ANGULAR_6
INTRA_ANGULAR_7
INTRA_ANGULAR_8
INTRA_ANGULAR_9
INTRA_ANGULAR_10
INTRA_ANGULAR_11
INTRA_ANGULAR_12
INTRA_ANGULAR_13
INTRA_ANGULAR_14
INTRA_ANGULAR_15
INTRA_ANGULAR_16
INTRA_ANGULAR_17
INTRA_ANGULAR_18
INTRA_ANGULAR_19
INTRA_ANGULAR_20
INTRA_ANGULAR_21
INTRA_ANGULAR_22
INTRA_ANGULAR_23
INTRA_ANGULAR_24
INTRA_ANGULAR_25
INTRA_ANGULAR_26
INTRA_ANGULAR_27
INTRA_ANGULAR_28
INTRA_ANGULAR_29
INTRA_ANGULAR_30
INTRA_ANGULAR_31
INTRA_ANGULAR_32
INTRA_ANGULAR_33
INTRA_ANGULAR_34
VERT_PRED
HOR_PRED
DC_PRED
DIAG_DOWN_LEFT_PRED
DIAG_DOWN_RIGHT_PRED
VERT_RIGHT_PRED
HOR_DOWN_PRED
VERT_LEFT_PRED
HOR_UP_PRED
TM_VP8_PRED
LEFT_DC_PRED
TOP_DC_PRED
DC_128_PRED
DC_127_PRED
DC_129_PRED
N_INTRA_PRED_MODES
Definition at line 219 of file hevc.h.
SAOType
enum SAOType
Enumerator
SAO_NOT_APPLIED
SAO_BAND
SAO_EDGE
SAO_APPLIED
Definition at line 257 of file hevc.h.
SAOEOClass
enum SAOEOClass
Enumerator
SAO_EO_HORIZ
SAO_EO_VERT
SAO_EO_135D
SAO_EO_45D
Definition at line 264 of file hevc.h.
ScanType
enum ScanType
Enumerator
SCAN_DIAG
SCAN_HORIZ
SCAN_VERT
Definition at line 271 of file hevc.h.
Function Documentation
ff_hevc_decode_short_term_rps()
int ff_hevc_decode_short_term_rps (GetBitContext * gb, AVCodecContext * avctx, ShortTermRPS * rps, const HEVCSPS * sps, int is_slice_header)
Definition at line 110 of file hevc_ps.c.
Referenced by ff_hevc_parse_sps(), and hls_slice_header().
ff_hevc_parse_sps()
int ff_hevc_parse_sps (HEVCSPS * sps, GetBitContext * gb, unsigned int * sps_id, int apply_defdispwin, AVBufferRef ** vps_list, AVCodecContext * avctx)
Parse the SPS from the bitstream into the provided HEVCSPS struct.
Parameters
sps_id the SPS id will be written here
apply_defdispwin if set 1, the default display window from the VUI will be applied to the video dimensions
vps_list if non-NULL, this function will validate that the SPS refers to an existing VPS
Definition at line 825 of file hevc_ps.c.
Referenced by ff_hevc_decode_nal_sps(), and generate_fake_vps().
ff_hevc_decode_nal_vps()
int ff_hevc_decode_nal_vps (GetBitContext * gb, AVCodecContext * avctx, HEVCParamSets * ps)
Definition at line 397 of file hevc_ps.c.
Referenced by decode_nal_unit(), hevc_decode_nal_units(), hevc_find_frame_end(), and parse_nal_units().
ff_hevc_decode_nal_sps()
int ff_hevc_decode_nal_sps (GetBitContext * gb, AVCodecContext * avctx, HEVCParamSets * ps, int apply_defdispwin)
Definition at line 1184 of file hevc_ps.c.
Referenced by decode_nal_unit(), hevc_decode_nal_units(), hevc_find_frame_end(), and parse_nal_units().
ff_hevc_decode_nal_pps()
int ff_hevc_decode_nal_pps (GetBitContext * gb, AVCodecContext * avctx, HEVCParamSets * ps)
Definition at line 1427 of file hevc_ps.c.
Referenced by decode_nal_unit(), hevc_decode_nal_units(), hevc_find_frame_end(), and parse_nal_units().
ff_hevc_decode_nal_sei()
int ff_hevc_decode_nal_sei (HEVCContext * s)
Definition at line 365 of file hevc_sei.c.
Referenced by decode_nal_unit(), and hevc_find_frame_end().
ff_hevc_clear_refs()
void ff_hevc_clear_refs (HEVCContext * s)
Mark all frames in DPB as unused for reference.
Definition at line 65 of file hevc_refs.c.
Referenced by hls_slice_header().
ff_hevc_flush_dpb()
void ff_hevc_flush_dpb (HEVCContext * s)
Drop all frames currently in DPB.
Definition at line 74 of file hevc_refs.c.
Referenced by hevc_decode_flush().
ff_hevc_compute_poc()
int ff_hevc_compute_poc (HEVCContext * s, int poc_lsb)
Compute POC of the current frame and return it.
Definition at line 518 of file hevc_refs.c.
Referenced by hevc_find_frame_end(), and hls_slice_header().
ff_hevc_get_ref_list()
RefPicList* ff_hevc_get_ref_list (HEVCContext * s, HEVCFrame * frame, int x0, int y0)
Definition at line 56 of file hevc_refs.c.
Referenced by ff_hevc_deblocking_boundary_strengths().
ff_hevc_frame_rps()
int ff_hevc_frame_rps (HEVCContext * s)
Construct the reference picture sets for the current frame.
Definition at line 458 of file hevc_refs.c.
Referenced by hevc_frame_start().
ff_hevc_slice_rpl()
int ff_hevc_slice_rpl (HEVCContext * s)
Construct the reference picture list(s) for the current slice.
Definition at line 298 of file hevc_refs.c.
Referenced by decode_nal_unit().
ff_hevc_save_states()
void ff_hevc_save_states (HEVCContext * s, int ctb_addr_ts)
Definition at line 448 of file hevc_cabac.c.
Referenced by hls_decode_entry(), and hls_decode_entry_wpp().
ff_hevc_cabac_init()
void ff_hevc_cabac_init (HEVCContext * s, int ctb_addr_ts)
Definition at line 502 of file hevc_cabac.c.
Referenced by hls_decode_entry(), and hls_decode_entry_wpp().
ff_hevc_sao_merge_flag_decode()
int ff_hevc_sao_merge_flag_decode (HEVCContext * s)
Definition at line 548 of file hevc_cabac.c.
Referenced by hls_sao_param().
ff_hevc_sao_type_idx_decode()
int ff_hevc_sao_type_idx_decode (HEVCContext * s)
Definition at line 553 of file hevc_cabac.c.
Referenced by hls_sao_param().
ff_hevc_sao_band_position_decode()
int ff_hevc_sao_band_position_decode (HEVCContext * s)
Definition at line 563 of file hevc_cabac.c.
Referenced by hls_sao_param().
ff_hevc_sao_offset_abs_decode()
int ff_hevc_sao_offset_abs_decode (HEVCContext * s)
Definition at line 573 of file hevc_cabac.c.
Referenced by hls_sao_param().
ff_hevc_sao_offset_sign_decode()
int ff_hevc_sao_offset_sign_decode (HEVCContext * s)
Definition at line 583 of file hevc_cabac.c.
Referenced by hls_sao_param().
ff_hevc_sao_eo_class_decode()
int ff_hevc_sao_eo_class_decode (HEVCContext * s)
Definition at line 588 of file hevc_cabac.c.
Referenced by hls_sao_param().
ff_hevc_end_of_slice_flag_decode()
int ff_hevc_end_of_slice_flag_decode (HEVCContext * s)
Definition at line 595 of file hevc_cabac.c.
Referenced by hls_coding_quadtree().
ff_hevc_cu_transquant_bypass_flag_decode()
int ff_hevc_cu_transquant_bypass_flag_decode (HEVCContext * s)
Definition at line 600 of file hevc_cabac.c.
Referenced by hls_coding_unit().
ff_hevc_skip_flag_decode()
int ff_hevc_skip_flag_decode (HEVCContext * s, int x0, int y0, int x_cb, int y_cb)
Definition at line 605 of file hevc_cabac.c.
Referenced by hls_coding_unit().
ff_hevc_pred_mode_decode()
int ff_hevc_pred_mode_decode (HEVCContext * s)
Definition at line 666 of file hevc_cabac.c.
Referenced by hls_coding_unit().
ff_hevc_split_coding_unit_flag_decode()
int ff_hevc_split_coding_unit_flag_decode (HEVCContext * s, int ct_depth, int x0, int y0)
Definition at line 671 of file hevc_cabac.c.
Referenced by hls_coding_quadtree().
ff_hevc_part_mode_decode()
int ff_hevc_part_mode_decode (HEVCContext * s, int log2_cb_size)
Definition at line 690 of file hevc_cabac.c.
Referenced by hls_coding_unit().
ff_hevc_pcm_flag_decode()
int ff_hevc_pcm_flag_decode (HEVCContext * s)
Definition at line 727 of file hevc_cabac.c.
Referenced by hls_coding_unit().
ff_hevc_prev_intra_luma_pred_flag_decode()
int ff_hevc_prev_intra_luma_pred_flag_decode (HEVCContext * s)
Definition at line 732 of file hevc_cabac.c.
Referenced by intra_prediction_unit().
ff_hevc_mpm_idx_decode()
int ff_hevc_mpm_idx_decode (HEVCContext * s)
Definition at line 737 of file hevc_cabac.c.
Referenced by intra_prediction_unit().
ff_hevc_rem_intra_luma_pred_mode_decode()
int ff_hevc_rem_intra_luma_pred_mode_decode (HEVCContext * s)
Definition at line 745 of file hevc_cabac.c.
Referenced by intra_prediction_unit().
ff_hevc_intra_chroma_pred_mode_decode()
int ff_hevc_intra_chroma_pred_mode_decode (HEVCContext * s)
Definition at line 755 of file hevc_cabac.c.
Referenced by intra_prediction_unit().
ff_hevc_merge_idx_decode()
int ff_hevc_merge_idx_decode (HEVCContext * s)
Definition at line 766 of file hevc_cabac.c.
Referenced by hls_prediction_unit().
ff_hevc_merge_flag_decode()
int ff_hevc_merge_flag_decode (HEVCContext * s)
Definition at line 777 of file hevc_cabac.c.
Referenced by hls_prediction_unit().
ff_hevc_inter_pred_idc_decode()
int ff_hevc_inter_pred_idc_decode (HEVCContext * s, int nPbW, int nPbH)
Definition at line 782 of file hevc_cabac.c.
Referenced by hevc_luma_mv_mvp_mode().
ff_hevc_ref_idx_lx_decode()
int ff_hevc_ref_idx_lx_decode (HEVCContext * s, int num_ref_idx_lx)
Definition at line 792 of file hevc_cabac.c.
Referenced by hevc_luma_mv_mvp_mode().
ff_hevc_mvp_lx_flag_decode()
int ff_hevc_mvp_lx_flag_decode (HEVCContext * s)
Definition at line 808 of file hevc_cabac.c.
Referenced by hevc_luma_mv_mvp_mode().
ff_hevc_no_residual_syntax_flag_decode()
int ff_hevc_no_residual_syntax_flag_decode (HEVCContext * s)
Definition at line 813 of file hevc_cabac.c.
Referenced by hls_coding_unit().
ff_hevc_split_transform_flag_decode()
int ff_hevc_split_transform_flag_decode (HEVCContext * s, int log2_trafo_size)
Definition at line 851 of file hevc_cabac.c.
Referenced by hls_transform_tree().
ff_hevc_cbf_cb_cr_decode()
int ff_hevc_cbf_cb_cr_decode (HEVCContext * s, int trafo_depth)
Definition at line 856 of file hevc_cabac.c.
Referenced by hls_transform_tree().
ff_hevc_cbf_luma_decode()
int ff_hevc_cbf_luma_decode (HEVCContext * s, int trafo_depth)
Definition at line 861 of file hevc_cabac.c.
Referenced by hls_transform_tree().
ff_hevc_log2_res_scale_abs()
int ff_hevc_log2_res_scale_abs (HEVCContext * s, int idx)
Definition at line 881 of file hevc_cabac.c.
Referenced by hls_cross_component_pred().
ff_hevc_res_scale_sign_flag()
int ff_hevc_res_scale_sign_flag (HEVCContext * s, int idx)
Definition at line 890 of file hevc_cabac.c.
Referenced by hls_cross_component_pred().
ff_hevc_frame_nb_refs()
int ff_hevc_frame_nb_refs (HEVCContext * s)
Get the number of candidate references for the current frame.
Definition at line 541 of file hevc_refs.c.
Referenced by hls_slice_header(), and vdpau_hevc_start_frame().
ff_hevc_set_new_ref()
int ff_hevc_set_new_ref (HEVCContext * s, AVFrame ** frame, int poc)
Definition at line 134 of file hevc_refs.c.
Referenced by hevc_frame_start().
ff_hevc_output_frame()
int ff_hevc_output_frame (HEVCContext * s, AVFrame * frame, int flush)
Find next frame in output order and put a reference to it in frame.
Returns
1 if a frame was output, 0 otherwise
Definition at line 170 of file hevc_refs.c.
Referenced by hevc_decode_frame(), and hevc_frame_start().
ff_hevc_bump_frame()
void ff_hevc_bump_frame (HEVCContext * s)
Definition at line 240 of file hevc_refs.c.
Referenced by hevc_frame_start().
ff_hevc_unref_frame()
void ff_hevc_unref_frame (HEVCContext * s, HEVCFrame * frame, int flags)
Definition at line 31 of file hevc_refs.c.
Referenced by alloc_frame(), ff_hevc_clear_refs(), ff_hevc_flush_dpb(), ff_hevc_frame_rps(), ff_hevc_output_frame(), hevc_decode_frame(), hevc_decode_free(), hevc_frame_start(), hevc_ref_frame(), and hevc_update_thread_context().
ff_hevc_set_neighbour_available()
void ff_hevc_set_neighbour_available (HEVCContext * s, int x0, int y0, int nPbW, int nPbH)
Definition at line 41 of file hevc_mvs.c.
Referenced by ff_hevc_luma_mv_merge_mode(), hevc_luma_mv_mvp_mode(), and hls_transform_unit().
ff_hevc_luma_mv_merge_mode()
void ff_hevc_luma_mv_merge_mode (HEVCContext * s, int x0, int y0, int nPbW, int nPbH, int log2_cb_size, int part_idx, int merge_idx, MvField * mv)
Definition at line 478 of file hevc_mvs.c.
Referenced by hls_prediction_unit().
ff_hevc_luma_mv_mvp_mode()
void ff_hevc_luma_mv_mvp_mode (HEVCContext * s, int x0, int y0, int nPbW, int nPbH, int log2_cb_size, int part_idx, int merge_idx, MvField * mv, int mvp_lx_flag, int LX)
Definition at line 581 of file hevc_mvs.c.
Referenced by hevc_luma_mv_mvp_mode().
ff_hevc_set_qPy()
void ff_hevc_set_qPy (HEVCContext * s, int xBase, int yBase, int log2_cb_size)
Definition at line 121 of file hevc_filter.c.
Referenced by hls_coding_unit(), and hls_transform_unit().
ff_hevc_deblocking_boundary_strengths()
void ff_hevc_deblocking_boundary_strengths (HEVCContext * s, int x0, int y0, int log2_trafo_size)
Definition at line 714 of file hevc_filter.c.
Referenced by hls_coding_unit(), hls_pcm_sample(), and hls_transform_tree().
ff_hevc_cu_qp_delta_sign_flag()
int ff_hevc_cu_qp_delta_sign_flag (HEVCContext * s)
Definition at line 645 of file hevc_cabac.c.
Referenced by hls_transform_unit().
ff_hevc_cu_qp_delta_abs()
int ff_hevc_cu_qp_delta_abs (HEVCContext * s)
Definition at line 620 of file hevc_cabac.c.
Referenced by hls_transform_unit().
ff_hevc_cu_chroma_qp_offset_flag()
int ff_hevc_cu_chroma_qp_offset_flag (HEVCContext * s)
Definition at line 650 of file hevc_cabac.c.
Referenced by hls_transform_unit().
ff_hevc_cu_chroma_qp_offset_idx()
int ff_hevc_cu_chroma_qp_offset_idx (HEVCContext * s)
Definition at line 655 of file hevc_cabac.c.
Referenced by hls_transform_unit().
ff_hevc_hls_filter()
void ff_hevc_hls_filter (HEVCContext * s, int x, int y, int ctb_size)
Definition at line 842 of file hevc_filter.c.
Referenced by ff_hevc_hls_filters(), hls_decode_entry(), and hls_decode_entry_wpp().
ff_hevc_hls_filters()
void ff_hevc_hls_filters (HEVCContext * s, int x_ctb, int y_ctb, int ctb_size)
Definition at line 867 of file hevc_filter.c.
Referenced by hls_decode_entry(), and hls_decode_entry_wpp().
ff_hevc_hls_residual_coding()
void ff_hevc_hls_residual_coding (HEVCContext * s, int x0, int y0, int log2_trafo_size, enum ScanType scan_idx, int c_idx)
Definition at line 1006 of file hevc_cabac.c.
Referenced by hls_transform_unit().
ff_hevc_hls_mvd_coding()
void ff_hevc_hls_mvd_coding (HEVCContext * s, int x0, int y0, int log2_cb_size)
Definition at line 1516 of file hevc_cabac.c.
Referenced by hevc_luma_mv_mvp_mode().
ff_hevc_encode_nal_vps()
int ff_hevc_encode_nal_vps (HEVCVPS * vps, unsigned int id, uint8_t * buf, int buf_size)
Definition at line 66 of file hevc_ps_enc.c.
Referenced by generate_fake_vps().
ff_hevc_reset_sei()
void ff_hevc_reset_sei (HEVCContext * s)
Reset SEI values that are stored on the Context.
e.g. Caption data that was extracted during NAL parsing.
Parameters
s HEVCContext.
Definition at line 377 of file hevc_sei.c.
Referenced by hevc_find_frame_end(), and hevc_init_context().
Variable Documentation
ff_hevc_qpel_extra_before
const uint8_t ff_hevc_qpel_extra_before[4]
ff_hevc_qpel_extra_after
const uint8_t ff_hevc_qpel_extra_after[4]
ff_hevc_qpel_extra
const uint8_t ff_hevc_qpel_extra[4]
ff_hevc_diag_scan4x4_x
const uint8_t ff_hevc_diag_scan4x4_x[16]
Definition at line 25 of file hevc_data.c.
Referenced by ff_hevc_hls_residual_coding(), fill_scaling_lists(), scaling_list_data(), and vdpau_hevc_start_frame().
ff_hevc_diag_scan4x4_y
const uint8_t ff_hevc_diag_scan4x4_y[16]
Definition at line 32 of file hevc_data.c.
Referenced by ff_hevc_hls_residual_coding(), fill_scaling_lists(), scaling_list_data(), and vdpau_hevc_start_frame().
ff_hevc_diag_scan8x8_x
const uint8_t ff_hevc_diag_scan8x8_x[64]
Definition at line 39 of file hevc_data.c.
Referenced by ff_hevc_hls_residual_coding(), fill_scaling_lists(), scaling_list_data(), and vdpau_hevc_start_frame().
ff_hevc_diag_scan8x8_y
const uint8_t ff_hevc_diag_scan8x8_y[64]
Definition at line 58 of file hevc_data.c.
Referenced by ff_hevc_hls_residual_coding(), fill_scaling_lists(), scaling_list_data(), and vdpau_hevc_start_frame().