FFmpeg: libavcodec/anm.c File Reference
anm.c File Reference
Deluxe Paint Animation decoder.
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
Data Structures
struct AnmContext
Macros
#define OP(gb, pixel, count) op(&dst, dst_end, (gb), (pixel), (count), &s->x, avctx->width, s->frame->linesize[0])
Functions
static av_cold int decode_init (AVCodecContext *avctx)
static int op (uint8_t **dst, const uint8_t *dst_end, GetByteContext *gb, int pixel, int count, int *x, int width, int linesize)
Perform decode operation.
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int decode_end (AVCodecContext *avctx)
Variables
AVCodec ff_anm_decoder
Detailed Description
Deluxe Paint Animation decoder.
Definition in file anm.c.
Macro Definition Documentation
OP
#define OP (gb, pixel, count) op(&dst, dst_end, (gb), (pixel), (count), &s->x, avctx->width, s->frame->linesize[0])
Referenced by decode_frame().
Function Documentation
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 38 of file anm.c.
op()
static int op (uint8_t ** dst, const uint8_t * dst_end, GetByteContext * gb, int pixel, int count, int * x, int width, int linesize) inline static
Perform decode operation.
Parameters
dst pointer to destination image buffer
dst_end pointer to end of destination image buffer
gb GetByteContext (optional, see below)
pixel Fill color (optional, see below)
count Pixel count
x Pointer to x-axis counter
width Image width
linesize Destination image buffer linesize
Returns
non-zero if destination buffer is exhausted
a copy operation is achieved when 'gb' is set a fill operation is achieved when 'gb' is null and pixel is >= 0 a skip operation is achieved when 'gb' is null and pixel is < 0
Definition at line 78 of file anm.c.
Referenced by cdxl_decode_ham6(), cdxl_decode_ham8(), check_mc(), checkasm_check_h264qpel(), decode_0(), dxv_decompress_dxt1(), dxv_decompress_dxt5(), ff_h264_decode_ref_pic_list_reordering(), filter_slice(), libvorbis_encode_frame(), main(), mxf_read_partition_pack(), pulse_flash_stream(), pulse_set_mute(), pulse_set_pause(), pulse_set_volume(), pulse_subscribe_events(), pulse_update_sink_info(), pulse_update_sink_input_info(), and seqvideo_decode().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 113 of file anm.c.
decode_end()
static av_cold int decode_end (AVCodecContext * avctx) static
Definition at line 184 of file anm.c.
Variable Documentation
ff_anm_decoder
AVCodec ff_anm_decoder
Initial value:
= {
    .name           = "anm",
    .long_name      = NULL_IF_CONFIG_SMALL("Deluxe Paint Animation"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_ANM,
    .priv_data_size = sizeof(AnmContext),
    .init           = decode_init,
    .close          = decode_end,
    .decode         = decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 192 of file anm.c.