FFmpeg: libavformat/internal.h File Reference
internal.h File Reference
#include <stdint.h>
#include "libavutil/bprint.h"
#include "avformat.h"
#include "os_support.h"
Data Structures
struct AVCodecTag
struct CodecMime
struct FFFrac
The exact value of the fractional number is: 'val + num / den'.
struct AVFormatInternal
struct AVStreamInternal
Macros
#define MAX_URL_SIZE 4096
#define PROBE_BUF_MIN 2048
size of probe buffer, for guessing file type from file contents
#define PROBE_BUF_MAX (1 << 20)
#define MAX_PROBE_PACKETS 2500
#define hex_dump_debug(class, buf, size) do { if (0) av_hex_dump_log(class, AV_LOG_DEBUG, buf, size); } while(0)
#define RAW_PACKET_BUFFER_SIZE 2500000
Remaining size available for raw_packet_buffer, in bytes.
#define dynarray_add(tab, nb_ptr, elem)
#define NTP_OFFSET 2208988800ULL
#define NTP_OFFSET_US (NTP_OFFSET * 1000000ULL)
#define SPACE_CHARS " \t\r\n"
#define FFERROR_REDO FFERRTAG('R','E','D','O')
Returned by demuxers to indicate that data was consumed but discarded (ignored streams or junk data).
#define CONTAINS_PAL 2
Typedefs
typedef void(* ff_parse_key_val_cb) (void *context, const char *key, int key_len, char **dest, int *dest_len)
Callback function type for ff_parse_key_value.
Enumerations
enum AVWriteUncodedFrameFlags { AV_WRITE_UNCODED_FRAME_QUERY = 0x0001 }
Flags for AVFormatContext.write_uncoded_frame()
Functions
struct tm * ff_brktimegm (time_t secs, struct tm *tm)
char * ff_data_to_hex (char *buf, const uint8_t *src, int size, int lowercase)
int ff_hex_to_data (uint8_t *data, const char *p)
Parse a string of hexadecimal strings.
int ff_interleave_add_packet (AVFormatContext *s, AVPacket *pkt, int(*compare)(AVFormatContext *, AVPacket *, AVPacket *))
Add packet to AVFormatContext->packet_buffer list, determining its interleaved position using compare() function argument.
void ff_read_frame_flush (AVFormatContext *s)
Flush the frame reader.
uint64_t ff_ntp_time (void)
Get the current time since NTP epoch in microseconds.
void ff_sdp_write_media (char *buff, int size, AVStream *st, int idx, const char *dest_addr, const char *dest_type, int port, int ttl, AVFormatContext *fmt)
Append the media-specific SDP fragment for the media stream c to the buffer buff.
int ff_write_chained (AVFormatContext *dst, int dst_stream, AVPacket *pkt, AVFormatContext *src, int interleave)
Write a packet to another muxer than the one the user originally intended.
int ff_get_v_length (uint64_t val)
Get the length in bytes which is needed to store val as v.
void ff_put_v (AVIOContext *bc, uint64_t val)
Put val using a variable number of bytes.
int ff_get_line (AVIOContext *s, char *buf, int maxlen)
Read a whole line of text from AVIOContext.
void ff_parse_key_value (const char *str, ff_parse_key_val_cb callback_get_buf, void *context)
Parse a string with comma-separated key=value pairs.
int ff_find_stream_index (AVFormatContext *s, int id)
Find stream index based on format-specific stream ID.
int ff_index_search_timestamp (const AVIndexEntry *entries, int nb_entries, int64_t wanted_timestamp, int flags)
Internal version of av_index_search_timestamp.
int ff_add_index_entry (AVIndexEntry **index_entries, int *nb_index_entries, unsigned int *index_entries_allocated_size, int64_t pos, int64_t timestamp, int size, int distance, int flags)
Internal version of av_add_index_entry.
void ff_configure_buffers_for_index (AVFormatContext *s, int64_t time_tolerance)
AVChapter * avpriv_new_chapter (AVFormatContext *s, int id, AVRational time_base, int64_t start, int64_t end, const char *title)
Add a new chapter.
void ff_reduce_index (AVFormatContext *s, int stream_index)
Ensure the index uses less memory than the maximum specified in AVFormatContext.max_index_size by discarding entries if it grows too large.
enum AVCodecID ff_guess_image2_codec (const char *filename)
int ff_seek_frame_binary (AVFormatContext *s, int stream_index, int64_t target_ts, int flags)
Perform a binary search using av_index_search_timestamp() and AVInputFormat.read_timestamp().
void ff_update_cur_dts (AVFormatContext *s, AVStream *ref_st, int64_t timestamp)
Update cur_dts of all streams based on the given timestamp and AVStream.
int ff_find_last_ts (AVFormatContext *s, int stream_index, int64_t *ts, int64_t *pos, int64_t(*read_timestamp)(struct AVFormatContext *, int, int64_t *, int64_t))
int64_t ff_gen_search (AVFormatContext *s, int stream_index, int64_t target_ts, int64_t pos_min, int64_t pos_max, int64_t pos_limit, int64_t ts_min, int64_t ts_max, int flags, int64_t *ts_ret, int64_t(*read_timestamp)(struct AVFormatContext *, int, int64_t *, int64_t))
Perform a binary search using read_timestamp().
void avpriv_set_pts_info (AVStream *s, int pts_wrap_bits, unsigned int pts_num, unsigned int pts_den)
Set the time base and wrapping info for a given stream.
int ff_add_param_change (AVPacket *pkt, int32_t channels, uint64_t channel_layout, int32_t sample_rate, int32_t width, int32_t height)
Add side data to a packet for changing parameters to the given values.
int ff_framehash_write_header (AVFormatContext *s)
Set the timebase for each stream from the corresponding codec timebase and print it.
int ff_read_packet (AVFormatContext *s, AVPacket *pkt)
Read a transport packet from a media file.
int ff_interleave_packet_per_dts (AVFormatContext *s, AVPacket *out, AVPacket *pkt, int flush)
Interleave a packet per dts in an output media file.
void ff_free_stream (AVFormatContext *s, AVStream *st)
void ff_compute_frame_duration (AVFormatContext *s, int *pnum, int *pden, AVStream *st, AVCodecParserContext *pc, AVPacket *pkt)
Return the frame duration in seconds.
unsigned int ff_codec_get_tag (const AVCodecTag *tags, enum AVCodecID id)
enum AVCodecID ff_codec_get_id (const AVCodecTag *tags, unsigned int tag)
enum AVCodecID ff_get_pcm_codec_id (int bps, int flt, int be, int sflags)
Select a PCM codec based on the given parameters.
AVRational ff_choose_timebase (AVFormatContext *s, AVStream *st, int min_precision)
Chooses a timebase for muxing the specified stream.
enum AVChromaLocation ff_choose_chroma_location (AVFormatContext *s, AVStream *st)
Chooses a timebase for muxing the specified stream.
int ff_generate_avci_extradata (AVStream *st)
Generate standard extradata for AVC-Intra based on width/height and field order.
int ff_stream_add_bitstream_filter (AVStream *st, const char *name, const char *args)
Add a bitstream filter to a stream.
int ff_stream_encode_params_copy (AVStream *dst, const AVStream *src)
Copy encoding parameters from source to destination stream.
static int ff_rename (const char *oldpath, const char *newpath, void *logctx)
Wrap errno on rename() error.
int ff_alloc_extradata (AVCodecParameters *par, int size)
Allocate extradata with additional AV_INPUT_BUFFER_PADDING_SIZE at end which is always set to 0.
int ff_get_extradata (AVFormatContext *s, AVCodecParameters *par, AVIOContext *pb, int size)
Allocate extradata with additional AV_INPUT_BUFFER_PADDING_SIZE at end which is always set to 0 and fill it from pb.
int ff_rfps_add_frame (AVFormatContext *ic, AVStream *st, int64_t dts)
add frame for rfps calculation.
void ff_rfps_calculate (AVFormatContext *ic)
int ff_copy_whiteblacklists (AVFormatContext *dst, const AVFormatContext *src)
Copies the whilelists from one context to the other.
int ffio_open2_wrapper (struct AVFormatContext *s, AVIOContext **pb, const char *url, int flags, const AVIOInterruptCB *int_cb, AVDictionary **options)
int ff_format_output_open (AVFormatContext *s, const char *url, AVDictionary **options)
Utility function to open IO stream of output format.
void ff_format_io_close (AVFormatContext *s, AVIOContext **pb)
int ff_parse_creation_time_metadata (AVFormatContext *s, int64_t *timestamp, int return_seconds)
Parse creation_time in AVFormatContext metadata if exists and warn if the parsing fails.
int ff_standardize_creation_time (AVFormatContext *s)
Standardize creation_time metadata in AVFormatContext to an ISO-8601 timestamp string.
int ff_reshuffle_raw_rgb (AVFormatContext *s, AVPacket **ppkt, AVCodecParameters *par, int expected_stride)
Reshuffles the lines to use the user specified stride.
int ff_get_packet_palette (AVFormatContext *s, AVPacket *pkt, int ret, uint32_t *palette)
Retrieves the palette from a packet, either from side data, or appended to the video data in the packet itself (raw video only).
int ff_bprint_to_codecpar_extradata (AVCodecParameters *par, struct AVBPrint *buf)
Finalize buf into extradata and set its size appropriately.
int ff_interleaved_peek (AVFormatContext *s, int stream, AVPacket *pkt, int add_offset)
Find the next packet in the interleaving queue for the given stream.
Macro Definition Documentation
MAX_URL_SIZE
#define MAX_URL_SIZE 4096
Definition at line 30 of file internal.h.
Referenced by ftp_connect(), ftp_delete(), ftp_move(), ftp_set_dir(), http_open_cnx_internal(), http_read_header(), libssh_delete(), libssh_move(), libssh_open(), libssh_open_dir(), new_init_section(), open_input(), parse_location(), and parse_playlist().
PROBE_BUF_MIN
#define PROBE_BUF_MIN 2048
size of probe buffer, for guessing file type from file contents
Definition at line 33 of file internal.h.
Referenced by av_probe_input_buffer2(), and ff_img_read_packet().
PROBE_BUF_MAX
#define PROBE_BUF_MAX (1 << 20)
Definition at line 34 of file internal.h.
Referenced by av_probe_input_buffer2(), av_probe_input_format3(), and mp3_read_probe().
MAX_PROBE_PACKETS
#define MAX_PROBE_PACKETS 2500
Definition at line 36 of file internal.h.
Referenced by avformat_new_stream(), ff_read_frame_flush(), and set_codec_from_probe_data().
hex_dump_debug
#define hex_dump_debug (class, buf, size) do { if (0) av_hex_dump_log(class, AV_LOG_DEBUG, buf, size); } while(0)
Definition at line 41 of file internal.h.
Referenced by pat_cb(), pmt_cb(), and sdt_cb().
RAW_PACKET_BUFFER_SIZE
#define RAW_PACKET_BUFFER_SIZE 2500000
Remaining size available for raw_packet_buffer, in bytes.
Definition at line 100 of file internal.h.
Referenced by avformat_alloc_context(), avformat_open_input(), and flush_packet_queue().
dynarray_add
#define dynarray_add (tab, nb_ptr, elem)
Value:
do {\
    __typeof__(tab) _tab = (tab);\
    __typeof__(elem) _elem = (elem);\
    (void)sizeof(**_tab == _elem); /* check that types are compatible */\
    av_dynarray_add(_tab, nb_ptr, _elem);\
} while(0)
Definition at line 183 of file internal.h.
Referenced by add_renditions_to_variant(), av_new_program(), avpriv_new_chapter(), ff_rtsp_setup_output_streams(), get_sockaddr(), matroska_parse_frame(), matroska_parse_rm_audio(), matroska_parse_webvtt(), new_init_section(), new_playlist(), new_rendition(), new_variant(), parse_playlist(), rtp_parse_addr_list(), and update_streams_from_subdemuxer().
NTP_OFFSET
#define NTP_OFFSET 2208988800ULL
Definition at line 221 of file internal.h.
Referenced by ff_rtsp_open_transport_ctx().
NTP_OFFSET_US
#define NTP_OFFSET_US (NTP_OFFSET * 1000000ULL)
Definition at line 222 of file internal.h.
Referenced by ff_ntp_time(), and rtp_write_header().
SPACE_CHARS
#define SPACE_CHARS " \t\r\n"
Definition at line 287 of file internal.h.
FFERROR_REDO
#define FFERROR_REDO FFERRTAG('R','E','D','O')
Returned by demuxers to indicate that data was consumed but discarded (ignored streams or junk data).
The framework will re-call the demuxer.
Definition at line 588 of file internal.h.
Referenced by ff_read_packet(), flv_read_packet(), lxf_read_packet(), and mpegps_read_pes_header().
CONTAINS_PAL
#define CONTAINS_PAL 2
Definition at line 626 of file internal.h.
Referenced by ff_get_packet_palette().
Typedef Documentation
ff_parse_key_val_cb
typedef void(* ff_parse_key_val_cb) (void *context, const char *key, int key_len, char **dest, int *dest_len)
Callback function type for ff_parse_key_value.
Parameters
key a pointer to the key
key_len the number of bytes that belong to the key, including the '=' char
dest return the destination pointer for the value in *dest, may be null to ignore the value
dest_len the length of the *dest buffer
Definition at line 299 of file internal.h.
Enumeration Type Documentation
AVWriteUncodedFrameFlags
enum AVWriteUncodedFrameFlags
Flags for AVFormatContext.write_uncoded_frame()
Enumerator
AV_WRITE_UNCODED_FRAME_QUERY
Query whether the feature is possible on this stream.
The frame argument is ignored.
Definition at line 566 of file internal.h.
Function Documentation
ff_brktimegm()
struct tm* ff_brktimegm (time_t secs, struct tm * tm)
Definition at line 31 of file cutils.c.
Referenced by dv_write_pack().
ff_data_to_hex()
char* ff_data_to_hex (char * buf, const uint8_t * src, int size, int lowercase)
Definition at line 4559 of file utils.c.
Referenced by do_llnw_auth(), ff_rdt_calc_response_and_checksum(), hex_log(), hls_encryption_start(), make_digest_auth(), open_input(), and param_write_hex().
ff_hex_to_data()
int ff_hex_to_data (uint8_t * data, const char * p)
Parse a string of hexadecimal strings.
Any space between the hexadecimal digits is ignored.
Parameters
data if non-null, the parsed data is written to this pointer
p the string to parse
Returns
the number of bytes written (or to be written, if data is null)
Definition at line 4580 of file utils.c.
Referenced by parse_fmtp_config(), and parse_playlist().
ff_interleave_add_packet()
int ff_interleave_add_packet (AVFormatContext * s, AVPacket * pkt, int(*)(AVFormatContext *, AVPacket *, AVPacket *) compare)
Add packet to AVFormatContext->packet_buffer list, determining its interleaved position using compare() function argument.
Returns
0, or < 0 on error
Definition at line 967 of file mux.c.
Referenced by ff_audio_rechunk_interleave(), and ff_interleave_packet_per_dts().
ff_read_frame_flush()
void ff_read_frame_flush (AVFormatContext * s)
Flush the frame reader.
Definition at line 1843 of file utils.c.
Referenced by asf_read_pts(), avformat_flush(), avformat_seek_file(), ff_seek_frame_binary(), hls_read_seek(), mpegts_get_dts(), seek_frame_generic(), and seek_frame_internal().
ff_ntp_time()
uint64_t ff_ntp_time (void)
Get the current time since NTP epoch in microseconds.
Definition at line 4420 of file utils.c.
Referenced by rtp_write_header(), rtp_write_packet(), and rtp_write_trailer().
ff_sdp_write_media()
void ff_sdp_write_media (char * buff, int size, AVStream * st, int idx, const char * dest_addr, const char * dest_type, int port, int ttl, AVFormatContext * fmt)
Append the media-specific SDP fragment for the media stream c to the buffer buff.
Note, the buffer needs to be initialized, since it is appended to existing content.
Parameters
buff the buffer to append the SDP fragment to
size the size of the buff buffer
st the AVStream of the media to describe
idx the global stream index
dest_addr the destination address of the media stream, may be NULL
dest_type the destination address type, may be NULL
port the destination port of the media stream, 0 if unknown
ttl the time to live of the stream, 0 if not multicast
fmt the AVFormatContext, which might contain options modifying the generated SDP
Definition at line 832 of file sdp.c.
Referenced by mov_write_udta_sdp().
ff_write_chained()
int ff_write_chained (AVFormatContext * dst, int dst_stream, AVPacket * pkt, AVFormatContext * src, int interleave)
Write a packet to another muxer than the one the user originally intended.
Useful when chaining muxers, where one muxer internally writes a received packet to another muxer.
Parameters
dst the muxer to write the packet to
dst_stream the stream index within dst to write the packet to
pkt the packet to be written
src the muxer the packet originally was intended for
interleave 0->use av_write_frame, 1->av_interleaved_write_frame
Returns
the value av_write_frame returned
Definition at line 1366 of file mux.c.
Referenced by dash_write_packet(), ff_mov_add_hinted_packet(), hds_write_packet(), hls_write_packet(), ism_write_packet(), rtsp_write_packet(), sap_write_packet(), and seg_write_packet().
ff_get_v_length()
int ff_get_v_length (uint64_t val)
Get the length in bytes which is needed to store val as v.
Definition at line 414 of file aviobuf.c.
Referenced by ff_put_v(), and nut_write_packet().
ff_put_v()
void ff_put_v (AVIOContext * bc, uint64_t val)
Put val using a variable number of bytes.
Definition at line 424 of file aviobuf.c.
Referenced by nut_write_packet(), put_packet(), put_s(), put_str(), put_tt(), write_chapter(), write_globalinfo(), write_index(), write_mainheader(), write_sm_data(), write_streamheader(), and write_streaminfo().
ff_get_line()
int ff_get_line (AVIOContext * s, char * buf, int maxlen)
Read a whole line of text from AVIOContext.
Stop reading after reaching either a \n, a \0 or EOF. The returned string is always \0-terminated, and may be truncated if the buffer is too small.
Parameters
s the read-only AVIOContext
buf buffer to store the read line
maxlen size of the buffer
Returns
the length of the string written in the buffer, not including the final \0
Definition at line 765 of file aviobuf.c.
Referenced by aqt_read_header(), concat_read_header(), get_line(), hls_encryption_start(), jacosub_read_header(), microdvd_read_header(), mpl2_read_header(), mpsub_read_header(), nist_read_header(), pjs_read_header(), pvf_read_header(), read_chomp_line(), stl_read_header(), subviewer1_read_header(), subviewer_read_header(), and vplayer_read_header().
ff_parse_key_value()
void ff_parse_key_value (const char * str, ff_parse_key_val_cb callback_get_buf, void * context)
Parse a string with comma-separated key=value pairs.
The value strings may be quoted and may contain escaped characters within quoted strings.
Parameters
str the string to parse
callback_get_buf function that returns where to store the unescaped value string.
context the opaque context pointer to pass to callback_get_buf
Definition at line 4638 of file utils.c.
Referenced by ff_http_auth_handle_header(), and parse_playlist().
ff_find_stream_index()
int ff_find_stream_index (AVFormatContext * s, int id)
Find stream index based on format-specific stream ID.
Returns
stream index, or < 0 on error
Definition at line 4692 of file utils.c.
Referenced by get_sindex(), parse_chunks(), pmt_cb(), and scte_data_cb().
ff_index_search_timestamp()
int ff_index_search_timestamp (const AVIndexEntry * entries, int nb_entries, int64_t wanted_timestamp, int flags)
Internal version of av_index_search_timestamp.
Definition at line 1973 of file utils.c.
Referenced by av_index_search_timestamp(), ff_add_index_entry(), mxf_read_seek(), and read_seek().
ff_add_index_entry()
int ff_add_index_entry (AVIndexEntry ** index_entries, int * nb_index_entries, unsigned int * index_entries_allocated_size, int64_t pos, int64_t timestamp, int size, int distance, int flags)
Internal version of av_add_index_entry.
Definition at line 1905 of file utils.c.
Referenced by av_add_index_entry(), read_header(), and scan_file().
ff_configure_buffers_for_index()
void ff_configure_buffers_for_index (AVFormatContext * s, int64_t time_tolerance)
Definition at line 2016 of file utils.c.
Referenced by mov_read_header().
avpriv_new_chapter()
AVChapter* avpriv_new_chapter (AVFormatContext * s, int id, AVRational time_base, int64_t start, int64_t end, const char * title)
Add a new chapter.
Parameters
s media file handle
id unique ID for this chapter
start chapter start time in time_base units
end chapter end time in time_base units
title chapter title
Returns
AVChapter or NULL on error
Definition at line 4362 of file utils.c.
Referenced by asf_read_marker(), decode_info_header(), flac_read_header(), matroska_read_header(), mov_metadata_hmmt(), mov_read_chapters(), mov_read_chpl(), ogm_chapter(), read_chapter(), and read_header().
ff_reduce_index()
void ff_reduce_index (AVFormatContext * s, int stream_index)
Ensure the index uses less memory than the maximum specified in AVFormatContext.max_index_size by discarding entries if it grows too large.
Definition at line 1892 of file utils.c.
Referenced by av_read_frame(), matroska_parse_block(), mpegps_read_pes_header(), mpegts_get_dts(), and read_frame_internal().
ff_guess_image2_codec()
enum AVCodecID ff_guess_image2_codec (const char * filename)
Definition at line 99 of file img2.c.
Referenced by ape_tag_read_field(), av_guess_codec(), av_guess_format(), ff_img_read_header(), and img_read_probe().
ff_seek_frame_binary()
int ff_seek_frame_binary (AVFormatContext * s, int stream_index, int64_t target_ts, int flags)
Perform a binary search using av_index_search_timestamp() and AVInputFormat.read_timestamp().
Parameters
target_ts target timestamp in the time base of the given stream
stream_index stream number
Definition at line 2088 of file utils.c.
Referenced by asf_read_seek(), ogg_read_seek(), rm_read_seek(), and seek_frame_internal().
ff_update_cur_dts()
void ff_update_cur_dts (AVFormatContext * s, AVStream * ref_st, int64_t timestamp)
Update cur_dts of all streams based on the given timestamp and AVStream.
Stream ref_st unchanged, others set cur_dts in their native time base. Only needed for timestamp wrapping or if (dts not set and pts!=dts).
Parameters
timestamp new dts expressed in time_base of param ref_st
ref_st reference stream giving time_base of param timestamp
Definition at line 1878 of file utils.c.
Referenced by ff_seek_frame_binary(), idcin_read_seek(), matroska_read_seek(), mp3_seek(), mpc8_read_seek(), mxf_read_seek(), read_seek(), and seek_frame_generic().
ff_find_last_ts()
int ff_find_last_ts (AVFormatContext * s, int stream_index, int64_t * ts, int64_t * pos, int64_t(*)(struct AVFormatContext *, int, int64_t *, int64_t) read_timestamp)
Definition at line 2156 of file utils.c.
Referenced by ff_gen_search(), and find_duration().
ff_gen_search()
int64_t ff_gen_search (AVFormatContext * s, int stream_index, int64_t target_ts, int64_t pos_min, int64_t pos_max, int64_t pos_limit, int64_t ts_min, int64_t ts_max, int flags, int64_t * ts_ret, int64_t(*)(struct AVFormatContext *, int, int64_t *, int64_t) read_timestamp)
Perform a binary search using read_timestamp().
Parameters
target_ts target timestamp in the time base of the given stream
stream_index stream number
Definition at line 2194 of file utils.c.
Referenced by ff_seek_frame_binary(), and read_seek().
avpriv_set_pts_info()
void avpriv_set_pts_info (AVStream * s, int pts_wrap_bits, unsigned int pts_num, unsigned int pts_den)
Set the time base and wrapping info for a given stream.
This will be used to interpret the stream's timestamps. If the new time base is invalid (numerator or denominator are non-positive), it leaves the stream unchanged.
Parameters
s stream
pts_wrap_bits number of bits effectively used by the pts (used for wrap control)
pts_num time base numerator
pts_den time base denominator
Definition at line 4608 of file utils.c.
Referenced by acm_read_header(), adp_read_header(), ads_read_header(), adts_aac_read_header(), adx_read_header(), afc_read_header(), aiff_read_header(), aiff_write_header(), aix_read_header(), amr_read_header(), ape_read_header(), apng_read_header(), aqt_read_header(), asf_read_stream_properties(), asf_write_header1(), asfrtp_parse_sdp_line(), ass_read_header(), ast_read_header(), audio_read_header(), audio_write_header(), avformat_new_stream(), avi_read_header(), avi_write_header(), avisynth_create_stream_audio(), avisynth_create_stream_video(), avr_read_header(), bfi_read_header(), bmv_read_header(), cdata_read_header(), cdxl_read_packet(), celt_header(), cin_read_header(), cine_read_header(), create_audio_stream(), create_new_audio_stream(), create_stream(), daala_header(), dc1394_read_common(), dcstr_read_header(), decklink_setup_audio(), decklink_setup_video(), decode_stream_header(), dfa_read_header(), dirac_header(), dshow_add_device(), dss_read_header(), dtshd_read_header(), dv_extract_audio_info(), dv_extract_video_info(), dxa_read_header(), ea_read_header(), epaf_read_header(), fbdev_read_header(), ff_decklink_read_header(), ff_img_read_header(), ff_raw_video_read_header(), ff_rm_read_mdpr_codecdata(), ff_voc_get_packet(), ffm2_read_header(), ffm_read_header(), ffm_write_header(), film_read_header(), flac_header(), flac_read_header(), flic_read_header(), flv_write_header(), fsb_read_header(), g722_read_header(), g723_1_init(), g729_read_header(), gdigrab_read_header(), genh_read_header(), get_audio_config(), get_packet_header(), get_sockaddr(), get_video_config(), gif_read_header(), gif_write_header(), grab_read_header(), gsm_read_header(), gxf_header(), gxf_write_header(), hls_write_header(), hnm_read_header(), idcin_read_header(), iff_read_header(), ilbc_read_header(), init_audio(), init_muxer(), init_stream(), init_video_stream(), ipmovie_read_header(), ircam_read_header(), iss_read_header(), jacosub_read_header(), lavfi_read_header(), lmlm4_read_header(), loas_read_header(), lrc_read_header(), lrc_write_header(), lvf_read_header(), lxf_read_header(), matroska_parse_tracks(), microdvd_read_header(), microdvd_write_header(), mkv_init(), mmf_rate(), mmf_read_header(), modplug_read_header(), mov_init(), mov_read_trak(), mp3_read_header(), mpc8_read_header(), mpc_read_header(), mpeg_mux_init(), mpegts_init(), mpegts_read_header(), mpegts_set_stream_info(), mpjpeg_read_header(), mpl2_read_header(), mpsub_read_header(), msf_read_header(), msnwc_tcp_read_header(), mtaf_read_header(), mtv_read_header(), musx_read_header(), mv_read_header(), mxf_parse_structural_metadata(), mxf_write_header(), mxg_read_header(), nc_read_header(), new_stream(), nist_read_header(), nsv_parse_NSVs_header(), nut_read_header(), nut_write_header(), nuv_header(), ogg_build_vp8_headers(), ogg_new_stream(), ogg_write_header(), ogm_dshow_header(), ogm_header(), old_dirac_header(), old_flac_header(), oma_read_header(), opus_header(), parse_audio_var(), parse_strk(), parse_video_var(), parse_vtrk(), pcm_read_header(), pjs_read_header(), pmp_header(), pulse_read_header(), pulse_write_header(), pva_read_header(), pvf_read_header(), qt_rtp_parse_packet(), qtkit_read_header(), r3d_read_red1(), r3d_read_reda(), rawvideo_read_header(), read_frame(), read_gab2_sub(), read_header(), read_header_gme(), read_header_openmpt(), read_sl_header(), realtext_read_header(), redspark_read_header(), rl2_read_header(), roq_read_packet(), rpl_read_header(), rsd_read_header(), rso_read_header(), rtp_write_header(), sami_read_header(), sbg_read_header(), sdr2_read_header(), seg_init(), seq_read_header(), set_spdif(), set_stream_info_from_input_stream(), siff_parse_vbv1(), skeleton_header(), smacker_read_header(), smjpeg_read_header(), smjpeg_write_header(), smush_read_header(), sol_read_header(), sox_read_header(), speex_header(), srt_read_header(), srt_write_header(), stl_read_header(), str_read_packet(), subviewer1_read_header(), subviewer_read_header(), sup_read_header(), svag_read_header(), swf_read_packet(), tak_read_header(), tedcaptions_read_header(), theora_header(), thp_read_header(), threedostr_read_header(), tmv_read_header(), tta_read_header(), tta_write_header(), txd_read_header(), v210_read_header(), v4l2_read_header(), vag_read_header(), vc1t_read_header(), vc1test_write_header(), vfw_read_header(), vid_read_packet(), vivo_read_header(), vmd_read_header(), vorbis_header(), vp8_header(), vpk_read_header(), vplayer_read_header(), vqf_read_header(), wc3_read_header(), webm_chunk_write_header(), webp_write_header(), webvtt_read_header(), webvtt_write_header(), write_header(), write_stream_data(), wsaud_read_header(), wsvqa_read_header(), wsvqa_read_packet(), wv_read_header(), wve_read_header(), x11grab_read_header(), xa_read_header(), xmv_process_packet_header(), xvag_read_header(), xwma_read_header(), yop_read_header(), and yuv4_read_header().
ff_add_param_change()
int ff_add_param_change (AVPacket * pkt, int32_t channels, uint64_t channel_layout, int32_t sample_rate, int32_t width, int32_t height)
Add side data to a packet for changing parameters to the given values.
Parameters set to 0 aren't included in the change.
Definition at line 4742 of file utils.c.
Referenced by flv_read_packet(), load_ipmovie_packet(), and swf_read_packet().
ff_framehash_write_header()
int ff_framehash_write_header (AVFormatContext * s)
Set the timebase for each stream from the corresponding codec timebase and print it.
Definition at line 23 of file framehash.c.
Referenced by framecrc_write_header(), and write_header().
ff_read_packet()
int ff_read_packet (AVFormatContext * s, AVPacket * pkt)
Read a transport packet from a media file.
Parameters
s media file handle
pkt is filled
Returns
0 if OK, AVERROR_xxx on error
Definition at line 779 of file utils.c.
Referenced by asfrtp_parse_packet(), estimate_timings_from_pts(), get_subtitle_pkt(), read_frame_internal(), read_gab2_sub(), and seek_subtitle().
ff_interleave_packet_per_dts()
int ff_interleave_packet_per_dts (AVFormatContext * s, AVPacket * out, AVPacket * pkt, int flush)
Interleave a packet per dts in an output media file.
Packets with pkt->destruct == av_destruct_packet will be freed inside this function, so they cannot be used after it. Note that calling av_packet_unref() on them is still safe.
Parameters
s media file handle
out the interleaved packet will be output here
pkt the input packet
flush 1 if no further packets are available as input and all remaining packets should be output
Returns
1 if a packet was output, 0 if no packet could be output, < 0 if an error occurred
Definition at line 1068 of file mux.c.
Referenced by gxf_interleave_packet(), and interleave_packet().
ff_free_stream()
void ff_free_stream (AVFormatContext * s, AVStream * st)
Definition at line 4163 of file utils.c.
Referenced by avformat_free_context(), and ff_rm_read_mdpr_codecdata().
ff_compute_frame_duration()
void ff_compute_frame_duration (AVFormatContext * s, int * pnum, int * pden, AVStream * st, AVCodecParserContext * pc, AVPacket * pkt)
Return the frame duration in seconds.
Return 0 if not available.
Definition at line 897 of file utils.c.
Referenced by compute_pkt_fields(), and estimate_timings_from_pts().
ff_codec_get_tag()
unsigned int ff_codec_get_tag (const AVCodecTag * tags, enum AVCodecID id)
Definition at line 3035 of file utils.c.
Referenced by ast_write_header(), caf_write_header(), flv_write_header(), flv_write_packet(), gxf_write_header(), ipod_get_codec_tag(), ircam_write_header(), mkv_write_codecprivate(), mkv_write_track(), mov_find_codec_tag(), mov_get_codec_tag(), mov_write_esds_tag(), mov_write_isml_manifest(), mp4_get_codec_tag(), smjpeg_write_header(), swf_write_video(), and write_stream_codec_info().
ff_codec_get_id()
enum AVCodecID ff_codec_get_id (const AVCodecTag * tags, unsigned int tag)
Definition at line 3045 of file utils.c.
Referenced by asf_read_stream_properties(), ast_read_header(), av_codec_get_id(), avi_read_header(), create_new_audio_stream(), decode_stream_header(), ff_mp4_read_dec_config_descr(), ff_rm_read_mdpr_codecdata(), ff_voc_get_packet(), ff_wav_codec_get_id(), get_aiff_header(), get_codec_data(), get_qt_codec(), ircam_read_header(), lvf_read_header(), lxf_read_header(), matroska_parse_tracks(), mkv_write_codecprivate(), mkv_write_native_codecprivate(), mov_codec_id(), mov_skip_multiple_stsd(), nsv_parse_NSVs_header(), nut_read_header(), ogm_dshow_header(), ogm_header(), oma_read_header(), parse_dsd_prop(), parse_media_type(), parse_video_info(), read_desc_chunk(), read_header(), rm_read_audio_stream_info(), rsd_read_header(), rso_read_header(), smjpeg_read_header(), and swf_read_packet().
ff_get_pcm_codec_id()
enum AVCodecID ff_get_pcm_codec_id (int bps, int flt, int be, int sflags)
Select a PCM codec based on the given parameters.
Parameters
bps bits-per-sample
flt floating-point
be big-endian
sflags signed flags. each bit corresponds to one byte of bit depth. e.g. the 1st bit indicates if 8-bit should be signed or unsigned, the 2nd bit indicates if 16-bit should be signed or unsigned, etc... This is useful for formats such as WAVE where only 8-bit is unsigned and all other bit depths are signed.
Returns
a PCM codec id or AV_CODEC_ID_NONE
Definition at line 3057 of file utils.c.
Referenced by avr_read_header(), ff_mov_get_lpcm_codec_id(), ff_wav_codec_get_id(), get_codec_data(), nist_read_header(), and pvf_read_header().
ff_choose_timebase()
AVRational ff_choose_timebase (AVFormatContext * s, AVStream * st, int min_precision)
Chooses a timebase for muxing the specified stream.
The chosen timebase allows sample accurate timestamps based on the framerate or sample rate for audio streams. It also is at least as precise as 1/min_precision would be.
Definition at line 102 of file mux.c.
Referenced by nut_write_header().
ff_choose_chroma_location()
enum AVChromaLocation ff_choose_chroma_location (AVFormatContext * s, AVStream * st)
Chooses a timebase for muxing the specified stream.
Definition at line 118 of file mux.c.
Referenced by mxf_write_header().
ff_generate_avci_extradata()
int ff_generate_avci_extradata (AVStream * st)
Generate standard extradata for AVC-Intra based on width/height and field order.
Definition at line 5287 of file utils.c.
Referenced by mov_read_trak(), and mxf_parse_structural_metadata().
ff_stream_add_bitstream_filter()
int ff_stream_add_bitstream_filter (AVStream * st, const char * name, const char * args)
Add a bitstream filter to a stream.
Parameters
st output stream to add a filter to
name the name of the filter to add
args filter-specific argument string
Returns
>0 on success; AVERROR code on failure
Definition at line 5497 of file utils.c.
Referenced by force_one_stream(), ivf_check_bitstream(), latm_check_bitstream(), mkv_check_bitstream(), mov_check_bitstream(), and mpegts_check_bitstream().
ff_stream_encode_params_copy()
int ff_stream_encode_params_copy (AVStream * dst, const AVStream * src)
Copy encoding parameters from source to destination stream.
Parameters
dst pointer to destination AVStream
src pointer to source AVStream
Returns
>=0 on success, AVERROR code on error
Definition at line 4058 of file utils.c.
Referenced by fifo_mux_init(), and open_slave().
ff_rename()
static int ff_rename (const char * oldpath, const char * newpath, void * logctx) inline static
Wrap errno on rename() error.
Parameters
oldpath source path
newpath destination path
Returns
0 or AVERROR on failure
Definition at line 524 of file internal.h.
Referenced by hds_flush(), hls_window(), ism_flush(), segment_end(), write_abst(), write_manifest(), and write_packet().
ff_alloc_extradata()
int ff_alloc_extradata (AVCodecParameters * par, int size)
Allocate extradata with additional AV_INPUT_BUFFER_PADDING_SIZE at end which is always set to 0.
Parameters
size size of extradata
Returns
0 if OK, AVERROR_xxx on error
Definition at line 3208 of file utils.c.
Referenced by acm_read_header(), afc_read_header(), ape_read_header(), celt_header(), copy_stream_props(), dfa_read_header(), encode_intervals(), ff_generate_avci_extradata(), ff_get_extradata(), ff_parse_mpeg2_descriptor(), ff_rename(), filter_packet(), flac_header(), flic_read_header(), flv_set_video_codec(), fsb_read_header(), genh_read_header(), init_stream(), matroska_parse_tracks(), matroska_read_header(), mov_create_chapter_track(), msf_read_header(), mxf_parse_structural_metadata(), nist_read_header(), nut_read_header(), ogm_header(), oma_read_header(), opus_header(), parse_fmtp_config(), parse_packed_headers(), qdm2_parse_config(), read_header(), read_kuki_chunk(), redspark_read_header(), rsd_read_header(), set_spdif(), smacker_read_header(), smush_read_header(), speex_header(), svq3_parse_packet(), tta_read_header(), vmd_read_header(), vqf_read_header(), wsvqa_read_packet(), xmv_process_packet_header(), xwma_read_header(), and yop_read_header().
ff_get_extradata()
int ff_get_extradata (AVFormatContext * s, AVCodecParameters * par, AVIOContext * pb, int size)
Allocate extradata with additional AV_INPUT_BUFFER_PADDING_SIZE at end which is always set to 0 and fill it from pb.
Parameters
size size of extradata
Returns
>= 0 if OK, AVERROR_xxx on error
Definition at line 3229 of file utils.c.
Referenced by adx_read_header(), aiff_read_header(), aix_read_header(), apc_read_header(), ape_tag_read_field(), avi_read_header(), decode_stream_header(), ff_get_wav_header(), ff_mp4_read_dec_config_descr(), ff_rename(), flv_get_extradata(), get_codec_data(), idcin_read_header(), mov_parse_stsd_data(), mov_read_dfla(), mov_read_dvc1(), mov_read_glbl(), mov_read_strf(), mov_read_wave(), mpc8_read_header(), mpc_read_header(), read_header(), read_kuki_chunk(), rl2_read_header(), rm_read_extradata(), rsd_read_header(), vc1t_read_header(), and wsvqa_read_header().
ff_rfps_add_frame()
int ff_rfps_add_frame (AVFormatContext * ic, AVStream * st, int64_t dts)
add frame for rfps calculation.
Parameters
dts timestamp of the i-th frame
Returns
0 if OK, AVERROR_xxx on error
Definition at line 3245 of file utils.c.
Referenced by avformat_find_stream_info(), ff_rename(), and mov_build_index().
ff_rfps_calculate()
void ff_rfps_calculate (AVFormatContext * ic)
Definition at line 3303 of file utils.c.
Referenced by avformat_find_stream_info(), ff_rename(), and mov_read_header().
ff_copy_whiteblacklists()
int ff_copy_whiteblacklists (AVFormatContext * dst, const AVFormatContext * src)
Copies the whilelists from one context to the other.
Definition at line 145 of file utils.c.
Referenced by ff_wms_parse_sdp_a_line(), hls_read_header(), ism_write_header(), open_file(), rdt_init(), read_gab2_sub(), and sap_read_header().
ffio_open2_wrapper()
int ffio_open2_wrapper (struct AVFormatContext * s, AVIOContext ** pb, const char * url, int flags, const AVIOInterruptCB * int_cb, AVDictionary ** options)
Definition at line 1063 of file aviobuf.c.
ff_format_output_open()
int ff_format_output_open (AVFormatContext * s, const char * url, AVDictionary ** options)
Utility function to open IO stream of output format.
Parameters
s AVFormatContext
url URL or file name to open for writing optional options which will be passed to io_open callback
Returns
>=0 on success, negative AVERROR in case of failure
Definition at line 5612 of file utils.c.
Referenced by fifo_thread_write_header(), and open_slave().
ff_format_io_close()
void ff_format_io_close (AVFormatContext * s, AVIOContext ** pb)
Definition at line 5622 of file utils.c.
Referenced by chunk_end(), close_file(), close_slave(), copy_moof(), dash_flush(), dash_free(), ff_img_read_packet(), fifo_thread_write_trailer(), find_index_range(), free_playlist_list(), hds_free(), hls_encryption_start(), hls_read_seek(), hls_window(), hls_write_packet(), hls_write_trailer(), mov_read_close(), open_input(), parse_fragment(), parse_playlist(), read_close(), read_data(), read_header(), recheck_discard_flags(), seg_free(), seg_init(), seg_write_header(), seg_write_trailer(), segment_end(), shift_data(), update_init_section(), webm_chunk_write_header(), write_abst(), write_manifest(), and write_packet().
ff_parse_creation_time_metadata()
int ff_parse_creation_time_metadata (AVFormatContext * s, int64_t * timestamp, int return_seconds)
Parse creation_time in AVFormatContext metadata if exists and warn if the parsing fails.
Parameters
s AVFormatContext
timestamp parsed timestamp in microseconds, only set on successful parsing
return_seconds set this to get the number of seconds in timestamp instead of microseconds
Returns
1 if OK, 0 if the metadata was not present, AVERROR(EINVAL) on parse error
Definition at line 5629 of file utils.c.
Referenced by asf_write_header1(), dv_init_mux(), ff_standardize_creation_time(), ffm_write_header(), gxf_write_umf_material_description(), mkv_write_header(), mov_write_header(), and mxf_write_header().
ff_standardize_creation_time()
int ff_standardize_creation_time (AVFormatContext * s)
Standardize creation_time metadata in AVFormatContext to an ISO-8601 timestamp string.
Parameters
s AVFormatContext
Returns
<0 on error
Definition at line 5646 of file utils.c.
Referenced by caf_write_header(), ff_ape_write_tag(), ff_id3v2_write_metadata(), lrc_write_header(), smjpeg_write_header(), write_globalinfo(), write_metadata(), and write_table_entries_attrib().
ff_reshuffle_raw_rgb()
int ff_reshuffle_raw_rgb (AVFormatContext * s, AVPacket ** ppkt, AVCodecParameters * par, int expected_stride)
Reshuffles the lines to use the user specified stride.
Parameters
ppkt input and output packet
Returns
negative error code or 0 if no new packet was allocated non-zero if a new packet was allocated and ppkt has to be freed CONTAINS_PAL if in addition to a new packet the old contained a palette
Definition at line 25 of file rawutils.c.
Referenced by avi_write_packet(), and mov_write_packet().
ff_get_packet_palette()
int ff_get_packet_palette (AVFormatContext * s, AVPacket * pkt, int ret, uint32_t * palette)
Retrieves the palette from a packet, either from side data, or appended to the video data in the packet itself (raw video only).
It is commonly used after a call to ff_reshuffle_raw_rgb().
Use 0 for the ret parameter to check for side data only.
Parameters
pkt pointer to packet before calling ff_reshuffle_raw_rgb()
ret return value from ff_reshuffle_raw_rgb(), or 0
palette pointer to palette buffer
Returns
negative error code or 1 if the packet has a palette, else 0
Definition at line 5655 of file utils.c.
Referenced by avi_write_packet(), and mov_write_packet().
ff_bprint_to_codecpar_extradata()
int ff_bprint_to_codecpar_extradata (AVCodecParameters * par, struct AVBPrint * buf)
Finalize buf into extradata and set its size appropriately.
Definition at line 5680 of file utils.c.
Referenced by ass_read_header(), jacosub_read_header(), sami_read_header(), and subviewer_read_header().
ff_interleaved_peek()
int ff_interleaved_peek (AVFormatContext * s, int stream, AVPacket * pkt, int add_offset)
Find the next packet in the interleaving queue for the given stream.
The pkt parameter is filled in with the queued packet, including references to the data (which the caller is not allowed to keep or modify).
Returns
0 if a packet was found, a negative value if no packet was found
Definition at line 1187 of file mux.c.
Referenced by mov_flush_fragment().