FFmpeg: libavcodec/takdec.c File Reference
takdec.c File Reference
TAK (Tom's lossless Audio Kompressor) decoder.
#include "libavutil/internal.h"
#include "libavutil/samplefmt.h"
#include "audiodsp.h"
#include "thread.h"
#include "avcodec.h"
#include "internal.h"
#include "unary.h"
#include "tak.h"
#include "takdsp.h"
Data Structures
struct MCDParam
struct TAKDecContext
struct CParam
Macros
#define BITSTREAM_READER_LE
#define MAX_SUBFRAMES 8
max number of subframes per channel
#define MAX_PREDICTORS 256
Functions
static int set_bps_params (AVCodecContext *avctx)
static void set_sample_rate_params (AVCodecContext *avctx)
static av_cold int tak_decode_init (AVCodecContext *avctx)
static void decode_lpc (int32_t *coeffs, int mode, int length)
static int decode_segment (TAKDecContext *s, int8_t mode, int32_t *decoded, int len)
static int decode_residues (TAKDecContext *s, int32_t *decoded, int length)
static int get_bits_esc4 (GetBitContext *gb)
static int decode_subframe (TAKDecContext *s, int32_t *decoded, int subframe_size, int prev_subframe_size)
static int decode_channel (TAKDecContext *s, int chan)
static int decorrelate (TAKDecContext *s, int c1, int c2, int length)
static int tak_decode_frame (AVCodecContext *avctx, void *data, int *got_frame_ptr, AVPacket *pkt)
static av_cold int tak_decode_close (AVCodecContext *avctx)
Variables
static const int8_t mc_dmodes [] = { 1, 3, 4, 6, }
static const uint16_t predictor_sizes []
static const struct CParam xcodes [50]
AVCodec ff_tak_decoder
Detailed Description
TAK (Tom's lossless Audio Kompressor) decoder.
Author
Paul B Mahol
Definition in file takdec.c.
Macro Definition Documentation
BITSTREAM_READER_LE
#define BITSTREAM_READER_LE
Definition at line 31 of file takdec.c.
MAX_SUBFRAMES
#define MAX_SUBFRAMES 8
max number of subframes per channel
Definition at line 40 of file takdec.c.
MAX_PREDICTORS
#define MAX_PREDICTORS 256
Definition at line 41 of file takdec.c.
Referenced by decode_subframe().
Function Documentation
set_bps_params()
static int set_bps_params (AVCodecContext * avctx) static
Definition at line 144 of file takdec.c.
Referenced by tak_decode_frame(), and tak_decode_init().
set_sample_rate_params()
static void set_sample_rate_params (AVCodecContext * avctx) static
Definition at line 165 of file takdec.c.
Referenced by tak_decode_frame(), and tak_decode_init().
tak_decode_init()
static av_cold int tak_decode_init (AVCodecContext * avctx) static
Definition at line 183 of file takdec.c.
decode_lpc()
static void decode_lpc (int32_t * coeffs, int mode, int length) static
Definition at line 198 of file takdec.c.
Referenced by decode_subframe(), and tak_decode_frame().
decode_segment()
static int decode_segment (TAKDecContext * s, int8_t mode, int32_t * decoded, int len) static
Definition at line 254 of file takdec.c.
Referenced by decode_residues().
decode_residues()
static int decode_residues (TAKDecContext * s, int32_t * decoded, int length) static
Definition at line 298 of file takdec.c.
Referenced by decode_subframe().
get_bits_esc4()
static int get_bits_esc4 (GetBitContext * gb) static
Definition at line 377 of file takdec.c.
Referenced by decode_channel(), decode_subframe(), and decorrelate().
decode_subframe()
static int decode_subframe (TAKDecContext * s, int32_t * decoded, int subframe_size, int prev_subframe_size) static
Definition at line 385 of file takdec.c.
Referenced by decode_channel().
decode_channel()
static int decode_channel (TAKDecContext * s, int chan) static
Definition at line 509 of file takdec.c.
Referenced by tak_decode_frame().
decorrelate()
static int decorrelate (TAKDecContext * s, int c1, int c2, int length) static
Definition at line 556 of file takdec.c.
Referenced by tak_decode_frame().
tak_decode_frame()
static int tak_decode_frame (AVCodecContext * avctx, void * data, int * got_frame_ptr, AVPacket * pkt) static
Definition at line 676 of file takdec.c.
tak_decode_close()
static av_cold int tak_decode_close (AVCodecContext * avctx) static
Definition at line 938 of file takdec.c.
Variable Documentation
mc_dmodes
const int8_t mc_dmodes[] = { 1, 3, 4, 6, } static
Definition at line 79 of file takdec.c.
Referenced by tak_decode_frame().
predictor_sizes
const uint16_t predictor_sizes[] static
Initial value:
= {
    4, 8, 12, 16, 24, 32, 48, 64, 80, 96, 128, 160, 192, 224, 256, 0,
}
Definition at line 81 of file takdec.c.
Referenced by decode_subframe().
xcodes
const struct CParam xcodes[50] static
Referenced by decode_segment().
ff_tak_decoder
AVCodec ff_tak_decoder
Initial value:
= {
    .name             = "tak",
    .long_name        = NULL_IF_CONFIG_SMALL("TAK (Tom's lossless Audio Kompressor)"),
    .type             = AVMEDIA_TYPE_AUDIO,
    .id               = AV_CODEC_ID_TAK,
    .priv_data_size   = sizeof(TAKDecContext),
    .init             = tak_decode_init,
    .close            = tak_decode_close,
    .decode           = tak_decode_frame,
    .init_thread_copy = ONLY_IF_THREADS_ENABLED(init_thread_copy),
    .update_thread_context = ONLY_IF_THREADS_ENABLED(update_thread_context),
    .capabilities     = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_FRAME_THREADS,
    .sample_fmts      = (const enum AVSampleFormat[]) { AV_SAMPLE_FMT_U8P,
                                                        AV_SAMPLE_FMT_S16P,
                                                        AV_SAMPLE_FMT_S32P,
                                                        AV_SAMPLE_FMT_NONE },
}
Definition at line 947 of file takdec.c.