FFmpeg: libavcodec/dv.c File Reference
dv.c File Reference
DV codec.
#include "libavutil/internal.h"
#include "libavutil/pixdesc.h"
#include "avcodec.h"
#include "dv.h"
#include "dvdata.h"
#include "internal.h"
#include "put_bits.h"
#include "simple_idct.h"
Functions
static void dv_calc_mb_coordinates (const AVDVProfile *d, int chan, int seq, int slot, uint16_t *tbl)
int ff_dv_init_dynamic_tables (DVVideoContext *ctx, const AVDVProfile *d)
av_cold int ff_dvvideo_init (AVCodecContext *avctx)
Variables
RL_VLC_ELEM ff_dv_rl_vlc [1664]
Detailed Description
DV codec.
Definition in file dv.c.
Function Documentation
dv_calc_mb_coordinates()
static void dv_calc_mb_coordinates (const AVDVProfile * d, int chan, int seq, int slot, uint16_t * tbl) inline static
Definition at line 54 of file dv.c.
Referenced by ff_dv_init_dynamic_tables().
ff_dv_init_dynamic_tables()
int ff_dv_init_dynamic_tables (DVVideoContext * ctx, const AVDVProfile * d)
Definition at line 175 of file dv.c.
Referenced by dvvideo_decode_frame(), and dvvideo_encode_init().
ff_dvvideo_init()
av_cold int ff_dvvideo_init (AVCodecContext * avctx)
Definition at line 198 of file dv.c.
Referenced by dvvideo_decode_init(), and dvvideo_encode_init().
Variable Documentation
ff_dv_rl_vlc
RL_VLC_ELEM ff_dv_rl_vlc[1664]
Definition at line 52 of file dv.c.
Referenced by dv_decode_ac().