FFmpeg: libavcodec/vp9dsp.c File Reference
vp9dsp.c File Reference
#include "libavutil/avassert.h"
#include "libavutil/common.h"
#include "vp9dsp.h"
Functions
av_cold void ff_vp9dsp_init (VP9DSPContext *dsp, int bpp, int bitexact)
Variables
const int16_t ff_vp9_subpel_filters [3][16][8]
Function Documentation
ff_vp9dsp_init()
av_cold void ff_vp9dsp_init (VP9DSPContext * dsp, int bpp, int bitexact)
Definition at line 84 of file vp9dsp.c.
Referenced by check_ipred(), check_itxfm(), check_loopfilter(), check_mc(), and update_size().
Variable Documentation
ff_vp9_subpel_filters
const int16_t ff_vp9_subpel_filters[3][16][8]
Definition at line 28 of file vp9dsp.c.