FFmpeg: libavformat/options.c File Reference
options.c File Reference
Options definition for AVFormatContext.
#include "avformat.h"
#include "avio_internal.h"
#include "internal.h"
#include "libavutil/internal.h"
#include "libavutil/opt.h"
#include "options_table.h"
Functions
FF_DISABLE_DEPRECATION_WARNINGS static FF_ENABLE_DEPRECATION_WARNINGS const char * format_to_name (void *ptr)
static void * format_child_next (void *obj, void *prev)
static const AVClass * format_child_class_next (const AVClass *prev)
static AVClassCategory get_category (void *ptr)
static int io_open_default (AVFormatContext *s, AVIOContext **pb, const char *url, int flags, AVDictionary **options)
static void io_close_default (AVFormatContext *s, AVIOContext *pb)
static void avformat_get_context_defaults (AVFormatContext *s)
AVFormatContext * avformat_alloc_context (void)
Allocate an AVFormatContext.
enum AVDurationEstimationMethod av_fmt_ctx_get_duration_estimation_method (const AVFormatContext *ctx)
Returns the method used to set ctx->duration.
const AVClass * avformat_get_class (void)
Get the AVClass for AVFormatContext.
Variables
static const AVClass av_format_context_class
Detailed Description
Options definition for AVFormatContext.
Definition in file options.c.
Function Documentation
format_to_name()
FF_DISABLE_DEPRECATION_WARNINGS static FF_ENABLE_DEPRECATION_WARNINGS const char* format_to_name (void * ptr) static
Definition at line 36 of file options.c.
format_child_next()
static void* format_child_next (void * obj, void * prev) static
Definition at line 44 of file options.c.
format_child_class_next()
static const AVClass* format_child_class_next (const AVClass * prev) static
Definition at line 56 of file options.c.
get_category()
static AVClassCategory get_category (void * ptr) static
Definition at line 84 of file options.c.
io_open_default()
static int io_open_default (AVFormatContext * s, AVIOContext ** pb, const char * url, int flags, AVDictionary ** options) static
Definition at line 102 of file options.c.
Referenced by avformat_get_context_defaults().
io_close_default()
static void io_close_default (AVFormatContext * s, AVIOContext * pb) static
Definition at line 115 of file options.c.
Referenced by avformat_get_context_defaults().
avformat_get_context_defaults()
static void avformat_get_context_defaults (AVFormatContext * s) static
Definition at line 120 of file options.c.
Referenced by avformat_alloc_context().
av_fmt_ctx_get_duration_estimation_method()
enum AVDurationEstimationMethod av_fmt_ctx_get_duration_estimation_method (const AVFormatContext * ctx)
Returns the method used to set ctx->duration.
Returns
AVFMT_DURATION_FROM_PTS, AVFMT_DURATION_FROM_STREAM, or AVFMT_DURATION_FROM_BITRATE.
Definition at line 151 of file options.c.
Variable Documentation
av_format_context_class
const AVClass av_format_context_class static
Initial value:
= {
    .class_name     = "AVFormatContext",
    .item_name      = format_to_name,
    .option         = avformat_options,
    .version        = LIBAVUTIL_VERSION_INT,
    .child_next     = format_child_next,
    .child_class_next = format_child_class_next,
    .category       = AV_CLASS_CATEGORY_MUXER,
    .get_category   = get_category,
}
Definition at line 91 of file options.c.
Referenced by avformat_get_class(), and avformat_get_context_defaults().