FFmpeg: libavcodec/thread.h File Reference
thread.h File Reference
Multithreading support functions.
#include "libavutil/buffer.h"
#include "config.h"
#include "avcodec.h"
Data Structures
struct ThreadFrame
Functions
void ff_thread_flush (AVCodecContext *avctx)
Wait for decoding threads to finish and reset internal state.
int ff_thread_decode_frame (AVCodecContext *avctx, AVFrame *picture, int *got_picture_ptr, AVPacket *avpkt)
Submit a new frame to a decoding thread.
void ff_thread_finish_setup (AVCodecContext *avctx)
If the codec defines update_thread_context(), call this when they are ready for the next thread to start decoding the next frame.
void ff_thread_report_progress (ThreadFrame *f, int progress, int field)
Notify later decoding threads when part of their reference picture is ready.
void ff_thread_await_progress (ThreadFrame *f, int progress, int field)
Wait for earlier decoding threads to finish reference pictures.
enum AVPixelFormat ff_thread_get_format (AVCodecContext *avctx, const enum AVPixelFormat *fmt)
Wrapper around get_format() for frame-multithreaded codecs.
int ff_thread_get_buffer (AVCodecContext *avctx, ThreadFrame *f, int flags)
Wrapper around get_buffer() for frame-multithreaded codecs.
void ff_thread_release_buffer (AVCodecContext *avctx, ThreadFrame *f)
Wrapper around release_buffer() frame-for multithreaded codecs.
int ff_thread_ref_frame (ThreadFrame *dst, ThreadFrame *src)
int ff_thread_init (AVCodecContext *s)
void ff_thread_free (AVCodecContext *s)
int ff_alloc_entries (AVCodecContext *avctx, int count)
void ff_reset_entries (AVCodecContext *avctx)
void ff_thread_report_progress2 (AVCodecContext *avctx, int field, int thread, int n)
void ff_thread_await_progress2 (AVCodecContext *avctx, int field, int thread, int shift)
Detailed Description
Multithreading support functions.
Author
Alexander Strange astra.nosp@m.nge@.nosp@m.ithin.nosp@m.ksw..nosp@m.com
Definition in file thread.h.
Function Documentation
ff_thread_flush()
void ff_thread_flush (AVCodecContext * avctx)
Wait for decoding threads to finish and reset internal state.
Called by avcodec_flush_buffers().
Parameters
avctx The context.
Definition at line 718 of file pthread_frame.c.
Referenced by avcodec_flush_buffers().
ff_thread_decode_frame()
int ff_thread_decode_frame (AVCodecContext * avctx, AVFrame * picture, int * got_picture_ptr, AVPacket * avpkt)
Submit a new frame to a decoding thread.
Returns the next available frame in picture. *got_picture_ptr will be 0 if none is available. The return value on success is the size of the consumed packet for compatibility with avcodec_decode_video2(). This means the decoder has to consume the full packet.
Parameters are the same as avcodec_decode_video2().
Definition at line 386 of file pthread_frame.c.
Referenced by avcodec_decode_audio4(), and avcodec_decode_video2().
ff_thread_finish_setup()
void ff_thread_finish_setup (AVCodecContext * avctx)
If the codec defines update_thread_context(), call this when they are ready for the next thread to start decoding the next frame.
After calling it, do not change any variables read by the update_thread_context() method, or call ff_thread_get_buffer().
Parameters
avctx The context.
Definition at line 507 of file pthread_frame.c.
Referenced by decode_frame(), decode_idat_chunk(), decode_postinit(), ff_h263_decode_frame(), ff_rv34_decode_frame(), frame_worker_thread(), hap_decode(), hevc_frame_start(), mimic_decode_frame(), mpeg_field_start(), tak_decode_frame(), thread_get_buffer_internal(), vp3_decode_frame(), vp78_decode_frame(), and vp9_decode_frame().
ff_thread_report_progress()
void ff_thread_report_progress (ThreadFrame * f, int progress, int field)
Notify later decoding threads when part of their reference picture is ready.
Call this when some part of the picture is finished decoding. Later calls with lower values of progress have no effect.
Parameters
f The picture being decoded.
progress Value, in arbitrary units, of how much of the picture has decoded.
field The field being decoded, for field-picture codecs. 0 for top field or frame pictures, 1 for bottom field.
Definition at line 471 of file pthread_frame.c.
Referenced by decode(), decode_finish_row(), decode_frame(), decode_frame_common(), decode_nal_units(), decode_slice(), ff_h264_decode_slice_header(), ff_h264_field_end(), ff_hevc_hls_filter(), ff_mpv_frame_end(), ff_mpv_frame_start(), ff_mpv_report_decode_progress(), ff_rv34_decode_frame(), finish_frame(), generate_missing_ref(), h264_field_start(), handle_p_frame_apng(), mimic_decode_frame(), rv34_decode_slice(), vp3_decode_frame(), vp3_draw_horiz_band(), vp78_decode_frame(), vp78_decode_mb_row_sliced(), and vp9_decode_frame().
ff_thread_await_progress()
void ff_thread_await_progress (ThreadFrame * f, int progress, int field)
Wait for earlier decoding threads to finish reference pictures.
Call this before accessing some part of a picture, with a given value for progress, and it will return after the responsible decoding thread calls ff_thread_report_progress() with the same or higher value for progress.
Parameters
f The picture being referenced.
progress Value, in arbitrary units, to wait for.
field The field being referenced, for field-picture codecs. 0 for top field or frame pictures, 1 for bottom field.
Definition at line 489 of file pthread_frame.c.
Referenced by await_reference_mb_row(), await_reference_row(), await_references(), decode(), decode_frame(), decode_mb_row_no_filter(), decode_mode(), decode_slice(), ff_er_frame_end(), find_ref_mvs(), guess_mv(), h264_field_start(), handle_p_frame_apng(), handle_p_frame_png(), hevc_await_progress(), is_intra_more_likely(), mc_chroma_scaled(), mc_chroma_unscaled(), mc_luma_scaled(), mc_luma_unscaled(), mpeg4_decode_mb(), mpv_decode_mb_internal(), rv34_decode_mv(), rv34_mc(), temporal_luma_motion_vector(), vp78_decode_frame(), vp8_mc_chroma(), and vp8_mc_luma().
ff_thread_get_format()
enum AVPixelFormat ff_thread_get_format (AVCodecContext * avctx, const enum AVPixelFormat * fmt)
Wrapper around get_format() for frame-multithreaded codecs.
Call this function instead of avctx->get_format(). Cannot be called after the codec has called ff_thread_finish_setup().
Parameters
avctx The current context.
fmt The list of available formats.
Definition at line 815 of file pthread_frame.c.
Referenced by get_pixel_format(), mpeg_get_pixelformat(), set_sps(), and update_size().
ff_thread_get_buffer()
int ff_thread_get_buffer (AVCodecContext * avctx, ThreadFrame * f, int flags)
Wrapper around get_buffer() for frame-multithreaded codecs.
Call this function instead of ff_get_buffer(f). Cannot be called after the codec has called ff_thread_finish_setup().
Parameters
avctx The current context.
f The frame to write into.
Definition at line 841 of file pthread_frame.c.
Referenced by aic_decode_frame(), alloc_frame(), alloc_frame_buffer(), alloc_picture(), cfhd_decode(), decode_element(), decode_entropy_coded_image(), decode_frame(), decode_idat_chunk(), dnxhd_decode_frame(), dxv_decode(), flac_decode_frame(), hap_decode(), init_image(), jpeg2000_decode_frame(), lag_decode_frame(), libopenjpeg_decode_frame(), magy_decode_frame(), mimic_decode_frame(), pixlet_decode_frame(), tak_decode_frame(), tta_decode_frame(), vble_decode_frame(), vp3_decode_frame(), vp8_alloc_frame(), vp9_alloc_frame(), and wavpack_decode_block().
ff_thread_release_buffer()
void ff_thread_release_buffer (AVCodecContext * avctx, ThreadFrame * f)
Wrapper around release_buffer() frame-for multithreaded codecs.
Call this function instead of avctx->release_buffer(f). The AVFrame will be copied and the actual release_buffer() call will be performed later. The contents of data pointed to by the AVFrame should not be changed until ff_thread_get_buffer() is called on it.
Parameters
avctx The current context.
f The picture being released.
Definition at line 849 of file pthread_frame.c.
Referenced by copy_fields(), decode_frame(), decode_frame_common(), decode_idat_chunk(), ff_ffv1_close(), ff_h264_unref_picture(), ff_hevc_unref_frame(), ff_mpeg_unref_picture(), ff_thread_ref_frame(), mimic_decode_end(), mimic_decode_frame(), mimic_decode_init(), png_dec_end(), ref_frame(), update_frames(), vp3_decode_flush(), vp3_decode_frame(), vp8_alloc_frame(), vp8_release_frame(), vp9_decode_flush(), vp9_decode_frame(), vp9_decode_free(), vp9_decode_init(), and vp9_unref_frame().
ff_thread_ref_frame()
int ff_thread_ref_frame (ThreadFrame * dst, ThreadFrame * src)
Definition at line 3934 of file utils.c.
Referenced by copy_fields(), decode_frame_common(), ff_h264_ref_picture(), ff_mpeg_ref_picture(), hevc_ref_frame(), mimic_decode_init(), ref_frame(), update_frames(), vp3_decode_frame(), vp8_release_frame(), vp9_decode_frame(), vp9_decode_init(), and vp9_ref_frame().
ff_thread_init()
int ff_thread_init (AVCodecContext * s)
Definition at line 70 of file pthread.c.
Referenced by avcodec_open2().
ff_thread_free()
void ff_thread_free (AVCodecContext * s)
Definition at line 82 of file pthread.c.
Referenced by avcodec_close(), and ff_slice_thread_init().
ff_alloc_entries()
int ff_alloc_entries (AVCodecContext * avctx, int count)
Definition at line 273 of file pthread_slice.c.
Referenced by hls_slice_data_wpp().
ff_reset_entries()
void ff_reset_entries (AVCodecContext * avctx)
Definition at line 310 of file pthread_slice.c.
Referenced by hls_slice_data_wpp().
ff_thread_report_progress2()
void ff_thread_report_progress2 (AVCodecContext * avctx, int field, int thread, int n)
Definition at line 246 of file pthread_slice.c.
Referenced by hls_decode_entry_wpp().
ff_thread_await_progress2()
void ff_thread_await_progress2 (AVCodecContext * avctx, int field, int thread, int shift)
Definition at line 257 of file pthread_slice.c.
Referenced by hls_decode_entry_wpp().