FFmpeg: libavformat/flvenc.c File Reference
flvenc.c File Reference
#include "libavutil/intreadwrite.h"
#include "libavutil/dict.h"
#include "libavutil/intfloat.h"
#include "libavutil/avassert.h"
#include "libavutil/mathematics.h"
#include "avio_internal.h"
#include "avio.h"
#include "avc.h"
#include "avformat.h"
#include "flv.h"
#include "internal.h"
#include "metadata.h"
#include "libavutil/opt.h"
#include "libavcodec/put_bits.h"
#include "libavcodec/aacenctab.h"
Data Structures
struct FLVFileposition
struct FLVContext
struct FLVStreamContext
Enumerations
enum FLVFlags {
FLV_AAC_SEQ_HEADER_DETECT = (1 << 0), FLV_NO_SEQUENCE_END = (1 << 1), FLV_ADD_KEYFRAME_INDEX = (1 << 2), FLV_NO_METADATA = (1 << 3),
FLV_NO_DURATION_FILESIZE = (1 << 4)
}
Functions
static int get_audio_flags (AVFormatContext *s, AVCodecParameters *par)
static void put_amf_string (AVIOContext *pb, const char *str)
static void put_avc_eos_tag (AVIOContext *pb, unsigned ts)
static void put_amf_double (AVIOContext *pb, double d)
static void put_amf_byte (AVIOContext *pb, unsigned char abyte)
static void put_amf_dword_array (AVIOContext *pb, uint32_t dw)
static void put_amf_bool (AVIOContext *pb, int b)
static void write_metadata (AVFormatContext *s, unsigned int ts)
static int unsupported_codec (AVFormatContext *s, const char *type, int codec_id)
static void flv_write_codec_header (AVFormatContext *s, AVCodecParameters *par)
static int flv_append_keyframe_info (AVFormatContext *s, FLVContext *flv, double ts, int64_t pos)
static int shift_data (AVFormatContext *s)
static int flv_write_header (AVFormatContext *s)
static int flv_write_trailer (AVFormatContext *s)
static int flv_write_packet (AVFormatContext *s, AVPacket *pkt)
Variables
static const AVCodecTag flv_video_codec_ids []
static const AVCodecTag flv_audio_codec_ids []
static const AVOption options []
static const AVClass flv_muxer_class
AVOutputFormat ff_flv_muxer
Enumeration Type Documentation
FLVFlags
enum FLVFlags
Enumerator
FLV_AAC_SEQ_HEADER_DETECT
FLV_NO_SEQUENCE_END
FLV_ADD_KEYFRAME_INDEX
FLV_NO_METADATA
FLV_NO_DURATION_FILESIZE
Definition at line 66 of file flvenc.c.
Function Documentation
get_audio_flags()
static int get_audio_flags (AVFormatContext * s, AVCodecParameters * par) static
Definition at line 127 of file flvenc.c.
Referenced by flv_write_codec_header(), flv_write_header(), and flv_write_packet().
put_amf_string()
static void put_amf_string (AVIOContext * pb, const char * str) static
Definition at line 226 of file flvenc.c.
Referenced by flv_write_packet(), flv_write_trailer(), and write_metadata().
put_avc_eos_tag()
static void put_avc_eos_tag (AVIOContext * pb, unsigned ts) static
Definition at line 233 of file flvenc.c.
Referenced by flv_write_trailer().
put_amf_double()
static void put_amf_double (AVIOContext * pb, double d) static
Definition at line 246 of file flvenc.c.
Referenced by flv_write_trailer(), and write_metadata().
put_amf_byte()
static void put_amf_byte (AVIOContext * pb, unsigned char abyte) static
Definition at line 252 of file flvenc.c.
Referenced by write_metadata().
put_amf_dword_array()
static void put_amf_dword_array (AVIOContext * pb, uint32_t dw) static
Definition at line 257 of file flvenc.c.
Referenced by flv_write_trailer().
put_amf_bool()
static void put_amf_bool (AVIOContext * pb, int b) static
Definition at line 263 of file flvenc.c.
Referenced by write_metadata().
write_metadata()
static void write_metadata (AVFormatContext * s, unsigned int ts) static
Definition at line 269 of file flvenc.c.
Referenced by flv_write_header(), and flv_write_packet().
unsupported_codec()
static int unsupported_codec (AVFormatContext * s, const char * type, int codec_id) static
Definition at line 473 of file flvenc.c.
Referenced by flv_write_header().
flv_write_codec_header()
static void flv_write_codec_header (AVFormatContext * s, AVCodecParameters * par) static
Definition at line 484 of file flvenc.c.
Referenced by flv_write_header(), and flv_write_packet().
flv_append_keyframe_info()
static int flv_append_keyframe_info (AVFormatContext * s, FLVContext * flv, double ts, int64_t pos) static
Definition at line 547 of file flvenc.c.
Referenced by flv_write_packet().
shift_data()
static int shift_data (AVFormatContext * s) static
Definition at line 574 of file flvenc.c.
Referenced by flv_write_trailer().
flv_write_header()
static int flv_write_header (AVFormatContext * s) static
Definition at line 657 of file flvenc.c.
flv_write_trailer()
static int flv_write_trailer (AVFormatContext * s) static
Definition at line 770 of file flvenc.c.
flv_write_packet()
static int flv_write_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 872 of file flvenc.c.
Variable Documentation
flv_video_codec_ids
const AVCodecTag flv_video_codec_ids[] static
Initial value:
= {
    { AV_CODEC_ID_FLV1,     FLV_CODECID_H263 },
    { AV_CODEC_ID_H263,     FLV_CODECID_REALH263 },
    { AV_CODEC_ID_MPEG4,    FLV_CODECID_MPEG4 },
    { AV_CODEC_ID_FLASHSV,  FLV_CODECID_SCREEN },
    { AV_CODEC_ID_FLASHSV2, FLV_CODECID_SCREEN2 },
    { AV_CODEC_ID_VP6F,     FLV_CODECID_VP6 },
    { AV_CODEC_ID_VP6,      FLV_CODECID_VP6 },
    { AV_CODEC_ID_VP6A,     FLV_CODECID_VP6A },
    { AV_CODEC_ID_H264,     FLV_CODECID_H264 },
    { AV_CODEC_ID_NONE,     0 }
}
Definition at line 39 of file flvenc.c.
flv_audio_codec_ids
const AVCodecTag flv_audio_codec_ids[] static
Initial value:
= {
    { AV_CODEC_ID_MP3,        FLV_CODECID_MP3        >> FLV_AUDIO_CODECID_OFFSET },
    { AV_CODEC_ID_PCM_U8,     FLV_CODECID_PCM        >> FLV_AUDIO_CODECID_OFFSET },
    { AV_CODEC_ID_PCM_S16BE,  FLV_CODECID_PCM        >> FLV_AUDIO_CODECID_OFFSET },
    { AV_CODEC_ID_PCM_S16LE,  FLV_CODECID_PCM_LE     >> FLV_AUDIO_CODECID_OFFSET },
    { AV_CODEC_ID_ADPCM_SWF,  FLV_CODECID_ADPCM      >> FLV_AUDIO_CODECID_OFFSET },
    { AV_CODEC_ID_AAC,        FLV_CODECID_AAC        >> FLV_AUDIO_CODECID_OFFSET },
    { AV_CODEC_ID_NELLYMOSER, FLV_CODECID_NELLYMOSER >> FLV_AUDIO_CODECID_OFFSET },
    { AV_CODEC_ID_PCM_MULAW,  FLV_CODECID_PCM_MULAW  >> FLV_AUDIO_CODECID_OFFSET },
    { AV_CODEC_ID_PCM_ALAW,   FLV_CODECID_PCM_ALAW   >> FLV_AUDIO_CODECID_OFFSET },
    { AV_CODEC_ID_SPEEX,      FLV_CODECID_SPEEX      >> FLV_AUDIO_CODECID_OFFSET },
    { AV_CODEC_ID_NONE,       0 }
}
Definition at line 52 of file flvenc.c.
options
const AVOption options[] static
Initial value:
= {
    { "flvflags", "FLV muxer flags", 0x42, AV_OPT_TYPE_FLAGS, {.i64 = 0}, INT_MIN, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM, "flvflags" },
    { "aac_seq_header_detect", "Put AAC sequence header based on stream data", 0, AV_OPT_TYPE_CONST, {.i64 = FLV_AAC_SEQ_HEADER_DETECT}, INT_MIN, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM, "flvflags" },
    { "no_sequence_end", "disable sequence end for FLV", 0, AV_OPT_TYPE_CONST, {.i64 = FLV_NO_SEQUENCE_END}, INT_MIN, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM, "flvflags" },
    { "no_metadata", "disable metadata for FLV", 0, AV_OPT_TYPE_CONST, {.i64 = FLV_NO_METADATA}, INT_MIN, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM, "flvflags" },
    { "no_duration_filesize", "disable duration and filesize zero value metadata for FLV", 0, AV_OPT_TYPE_CONST, {.i64 = FLV_NO_DURATION_FILESIZE}, INT_MIN, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM, "flvflags" },
    { "add_keyframe_index", "Add keyframe index metadata", 0, AV_OPT_TYPE_CONST, {.i64 = FLV_ADD_KEYFRAME_INDEX}, INT_MIN, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM, "flvflags" },
    { NULL },
}
Definition at line 1067 of file flvenc.c.
flv_muxer_class
const AVClass flv_muxer_class static
Initial value:
= {
    .class_name = "flv muxer",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1077 of file flvenc.c.
ff_flv_muxer
AVOutputFormat ff_flv_muxer
Initial value:
= {
    .name           = "flv",
    .long_name      = NULL_IF_CONFIG_SMALL("FLV (Flash Video)"),
    .mime_type      = "video/x-flv",
    .extensions     = "flv",
    .priv_data_size = sizeof(FLVContext),
    .audio_codec    = CONFIG_LIBMP3LAME ? AV_CODEC_ID_MP3 : AV_CODEC_ID_ADPCM_SWF,
    .video_codec    = AV_CODEC_ID_FLV1,
    .write_header   = flv_write_header,
    .write_packet   = flv_write_packet,
    .write_trailer  = flv_write_trailer,
    .codec_tag      = (const AVCodecTag* const []) {
                          flv_video_codec_ids, flv_audio_codec_ids, 0
                      },
    .flags          = AVFMT_GLOBALHEADER | AVFMT_VARIABLE_FPS |
                      AVFMT_TS_NONSTRICT,
    .priv_class     = &flv_muxer_class,
}
Definition at line 1084 of file flvenc.c.