FFmpeg: libavcodec/tests/options.c File Reference
options.c File Reference
#include "libavcodec/options.c"
Data Structures
struct Dummy12Context
struct Dummy3Context
Macros
#define OFFSET(x) offsetof(Dummy12Context, x)
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Functions
static int dummy_init (AVCodecContext *ctx)
static int dummy_close (AVCodecContext *ctx)
static int dummy_encode (AVCodecContext *ctx, AVPacket *pkt, const AVFrame *frame, int *got_packet)
static void test_copy_print_codec (const AVCodecContext *ctx)
static void test_copy (const AVCodec *c1, const AVCodec *c2)
int main (void)
Variables
static const AVOption dummy_options []
static const AVClass dummy_v1_class
static const AVClass dummy_v2_class
static AVCodec dummy_v1_encoder
static AVCodec dummy_v2_encoder
static AVCodec dummy_v3_encoder
static AVCodec dummy_v4_encoder
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(Dummy12Context, x)
Definition at line 56 of file options.c.
Referenced by avcodec_get_subtitle_rect_class().
VE
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 57 of file options.c.
Referenced by avcodec_get_subtitle_rect_class().
Function Documentation
dummy_init()
static int dummy_init (AVCodecContext * ctx) static
Definition at line 24 of file options.c.
Referenced by avcodec_get_subtitle_rect_class().
dummy_close()
static int dummy_close (AVCodecContext * ctx) static
Definition at line 32 of file options.c.
Referenced by avcodec_get_subtitle_rect_class().
dummy_encode()
static int dummy_encode (AVCodecContext * ctx, AVPacket * pkt, const AVFrame * frame, int * got_packet) static
Definition at line 39 of file options.c.
Referenced by avcodec_get_subtitle_rect_class().
test_copy_print_codec()
static void test_copy_print_codec (const AVCodecContext * ctx) static
Definition at line 123 of file options.c.
Referenced by avcodec_get_subtitle_rect_class(), and test_copy().
test_copy()
static void test_copy (const AVCodec * c1, const AVCodec * c2) static
Definition at line 140 of file options.c.
Referenced by avcodec_get_subtitle_rect_class(), and main().
main()
int main (void)
Definition at line 176 of file options.c.
Referenced by avcodec_get_subtitle_rect_class().
Variable Documentation
dummy_options
const AVOption dummy_options[] static
Initial value:
= {
    { "str", "set str", OFFSET(str), AV_OPT_TYPE_STRING, { .str = "i'm src default value" }, 0, 0, VE},
    { "num", "set num", OFFSET(num), AV_OPT_TYPE_INT,    { .i64 = 1500100900 },    0, INT_MAX, VE},
    { NULL },
}
Definition at line 58 of file options.c.
Referenced by avcodec_get_subtitle_rect_class().
dummy_v1_class
const AVClass dummy_v1_class static
Initial value:
= {
    .class_name = "dummy_v1_class",
    .item_name  = av_default_item_name,
    .option     = dummy_options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 64 of file options.c.
Referenced by avcodec_get_subtitle_rect_class().
dummy_v2_class
const AVClass dummy_v2_class static
Initial value:
= {
    .class_name = "dummy_v2_class",
    .item_name  = av_default_item_name,
    .option     = dummy_options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 71 of file options.c.
Referenced by avcodec_get_subtitle_rect_class().
dummy_v1_encoder
AVCodec dummy_v1_encoder static
Initial value:
= {
    .name             = "dummy_v1_codec",
    .type             = AVMEDIA_TYPE_VIDEO,
    .id               = AV_CODEC_ID_NONE - 1,
    .encode2          = dummy_encode,
    .init             = dummy_init,
    .close            = dummy_close,
    .priv_class       = &dummy_v1_class,
    .priv_data_size   = sizeof(Dummy12Context),
}
Definition at line 79 of file options.c.
Referenced by avcodec_get_subtitle_rect_class(), and main().
dummy_v2_encoder
AVCodec dummy_v2_encoder static
Initial value:
= {
    .name             = "dummy_v2_codec",
    .type             = AVMEDIA_TYPE_VIDEO,
    .id               = AV_CODEC_ID_NONE - 2,
    .encode2          = dummy_encode,
    .init             = dummy_init,
    .close            = dummy_close,
    .priv_class       = &dummy_v2_class,
    .priv_data_size   = sizeof(Dummy12Context),
}
Definition at line 91 of file options.c.
Referenced by avcodec_get_subtitle_rect_class(), and main().
dummy_v3_encoder
AVCodec dummy_v3_encoder static
Initial value:
= {
    .name             = "dummy_v3_codec",
    .type             = AVMEDIA_TYPE_VIDEO,
    .id               = AV_CODEC_ID_NONE - 3,
    .encode2          = dummy_encode,
    .init             = dummy_init,
    .close            = dummy_close,
    .priv_data_size   = sizeof(Dummy3Context),
}
Definition at line 103 of file options.c.
Referenced by avcodec_get_subtitle_rect_class(), and main().
dummy_v4_encoder
AVCodec dummy_v4_encoder static
Initial value:
= {
    .name             = "dummy_v4_codec",
    .type             = AVMEDIA_TYPE_VIDEO,
    .id               = AV_CODEC_ID_NONE - 4,
    .encode2          = dummy_encode,
    .init             = dummy_init,
    .close            = dummy_close,
}
Definition at line 114 of file options.c.
Referenced by avcodec_get_subtitle_rect_class(), and main().