FFmpeg: libavcodec/tta.c File Reference
tta.c File Reference
TTA (The Lossless True Audio) decoder.
#include <limits.h>
#include "libavutil/crc.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/opt.h"
#include "ttadata.h"
#include "ttadsp.h"
#include "avcodec.h"
#include "get_bits.h"
#include "thread.h"
#include "unary.h"
#include "internal.h"
Data Structures
struct TTAContext
Macros
#define BITSTREAM_READER_LE
#define FORMAT_SIMPLE 1
#define FORMAT_ENCRYPTED 2
#define PRED(x, k) (int32_t)((((uint64_t)(x) << (k)) - (x)) >> (k))
#define OFFSET(x) offsetof(TTAContext, x)
#define DEC (AV_OPT_FLAG_DECODING_PARAM | AV_OPT_FLAG_AUDIO_PARAM)
Functions
static int tta_check_crc (TTAContext *s, const uint8_t *buf, int buf_size)
static uint64_t tta_check_crc64 (uint8_t *pass)
static int allocate_buffers (AVCodecContext *avctx)
static av_cold int tta_decode_init (AVCodecContext *avctx)
static int tta_decode_frame (AVCodecContext *avctx, void *data, int *got_frame_ptr, AVPacket *avpkt)
static int init_thread_copy (AVCodecContext *avctx)
static av_cold int tta_decode_close (AVCodecContext *avctx)
Variables
static const int64_t tta_channel_layouts [7]
static const AVOption options []
static const AVClass tta_decoder_class
AVCodec ff_tta_decoder
Detailed Description
TTA (The Lossless True Audio) decoder.
See also
http://www.true-audio.com/
http://tta.corecodec.org/
Author
Alex Beregszaszi
Definition in file tta.c.
Macro Definition Documentation
BITSTREAM_READER_LE
#define BITSTREAM_READER_LE
Definition at line 36 of file tta.c.
FORMAT_SIMPLE
#define FORMAT_SIMPLE 1
Definition at line 45 of file tta.c.
FORMAT_ENCRYPTED
#define FORMAT_ENCRYPTED 2
Definition at line 46 of file tta.c.
Referenced by tta_decode_frame(), and tta_decode_init().
PRED
#define PRED (x, k) (int32_t)((((uint64_t)(x) << (k)) - (x)) >> (k))
Referenced by tta_decode_frame().
OFFSET
#define OFFSET (x) offsetof(TTAContext, x)
Definition at line 410 of file tta.c.
DEC
#define DEC (AV_OPT_FLAG_DECODING_PARAM | AV_OPT_FLAG_AUDIO_PARAM)
Definition at line 411 of file tta.c.
Referenced by set_spdif().
Function Documentation
tta_check_crc()
static int tta_check_crc (TTAContext * s, const uint8_t * buf, int buf_size) static
Definition at line 75 of file tta.c.
Referenced by tta_decode_frame().
tta_check_crc64()
static uint64_t tta_check_crc64 (uint8_t * pass) static
Definition at line 89 of file tta.c.
Referenced by tta_decode_init().
allocate_buffers()
static int allocate_buffers (AVCodecContext * avctx) static
Definition at line 104 of file tta.c.
Referenced by init_thread_copy(), and tta_decode_init().
tta_decode_init()
static av_cold int tta_decode_init (AVCodecContext * avctx) static
Definition at line 123 of file tta.c.
tta_decode_frame()
static int tta_decode_frame (AVCodecContext * avctx, void * data, int * got_frame_ptr, AVPacket * avpkt) static
Definition at line 219 of file tta.c.
init_thread_copy()
static int init_thread_copy (AVCodecContext * avctx) static
Definition at line 392 of file tta.c.
Referenced by alac_decode_init(), decode_frame(), ff_vp8_decode_init(), flac_decode_frame(), png_dec_end(), read_huffman_tree(), tak_decode_frame(), and wv_alloc_frame_context().
tta_decode_close()
static av_cold int tta_decode_close (AVCodecContext * avctx) static
Definition at line 399 of file tta.c.
Variable Documentation
tta_channel_layouts
const int64_t tta_channel_layouts[7] static
Initial value:
= {
    AV_CH_LAYOUT_STEREO,
    AV_CH_LAYOUT_STEREO|AV_CH_LOW_FREQUENCY,
    AV_CH_LAYOUT_QUAD,
    0,
    AV_CH_LAYOUT_5POINT1_BACK,
    AV_CH_LAYOUT_5POINT1_BACK|AV_CH_BACK_CENTER,
    AV_CH_LAYOUT_7POINT1_WIDE
}
Definition at line 65 of file tta.c.
Referenced by tta_decode_init().
options
const AVOption options[] static
Initial value:
= {
    { "password", "Set decoding password", OFFSET(pass), AV_OPT_TYPE_STRING, { .str = NULL }, 0, 0, DEC },
    { NULL },
}
Definition at line 412 of file tta.c.
tta_decoder_class
const AVClass tta_decoder_class static
Initial value:
= {
    .class_name = "TTA Decoder",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 417 of file tta.c.
ff_tta_decoder
AVCodec ff_tta_decoder
Initial value:
= {
    .name           = "tta",
    .long_name      = NULL_IF_CONFIG_SMALL("TTA (True Audio)"),
    .type           = AVMEDIA_TYPE_AUDIO,
    .id             = AV_CODEC_ID_TTA,
    .priv_data_size = sizeof(TTAContext),
    .init           = tta_decode_init,
    .close          = tta_decode_close,
    .decode         = tta_decode_frame,
    .init_thread_copy = ONLY_IF_THREADS_ENABLED(init_thread_copy),
    .capabilities   = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_FRAME_THREADS,
    .priv_class     = &tta_decoder_class,
}
Definition at line 424 of file tta.c.