FFmpeg: libavcodec/fmtconvert.c File Reference
fmtconvert.c File Reference
#include "avcodec.h"
#include "fmtconvert.h"
#include "libavutil/common.h"
Functions
static void int32_to_float_fmul_scalar_c (float *dst, const int32_t *src, float mul, int len)
static void int32_to_float_c (float *dst, const int32_t *src, intptr_t len)
static void int32_to_float_fmul_array8_c (FmtConvertContext *c, float *dst, const int32_t *src, const float *mul, int len)
av_cold void ff_fmt_convert_init (FmtConvertContext *c, AVCodecContext *avctx)
Function Documentation
int32_to_float_fmul_scalar_c()
static void int32_to_float_fmul_scalar_c (float * dst, const int32_t * src, float mul, int len) static
Definition at line 27 of file fmtconvert.c.
Referenced by ff_fmt_convert_init().
int32_to_float_c()
static void int32_to_float_c (float * dst, const int32_t * src, intptr_t len) static
Definition at line 35 of file fmtconvert.c.
Referenced by ff_fmt_convert_init().
int32_to_float_fmul_array8_c()
static void int32_to_float_fmul_array8_c (FmtConvertContext * c, float * dst, const int32_t * src, const float * mul, int len) static
Definition at line 43 of file fmtconvert.c.
Referenced by ff_fmt_convert_init().
ff_fmt_convert_init()
av_cold void ff_fmt_convert_init (FmtConvertContext * c, AVCodecContext * avctx)
Definition at line 52 of file fmtconvert.c.
Referenced by ac3_decode_init(), and checkasm_check_fmtconvert().