FFmpeg: libavcodec/bintext.c File Reference
bintext.c File Reference
Binary text decoder eXtended BINary text (XBIN) decoder iCEDraw File decoder.
#include "libavutil/intreadwrite.h"
#include "libavutil/xga_font_data.h"
#include "avcodec.h"
#include "cga_data.h"
#include "bintext.h"
#include "internal.h"
Data Structures
struct XbinContext
Macros
#define DEFAULT_BG_COLOR 0
#define FONT_WIDTH 8
Functions
static av_cold int decode_init (AVCodecContext *avctx)
static av_unused void hscroll (AVCodecContext *avctx)
static void draw_char (AVCodecContext *avctx, int c, int a)
Draw character to screen.
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int decode_end (AVCodecContext *avctx)
Detailed Description
Binary text decoder eXtended BINary text (XBIN) decoder iCEDraw File decoder.
Definition in file bintext.c.
Macro Definition Documentation
DEFAULT_BG_COLOR
#define DEFAULT_BG_COLOR 0
Definition at line 102 of file bintext.c.
Referenced by hscroll().
FONT_WIDTH
#define FONT_WIDTH 8
Definition at line 116 of file bintext.c.
Referenced by draw_char().
Function Documentation
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 47 of file bintext.c.
Referenced by decode_end().
hscroll()
static av_unused void hscroll (AVCodecContext * avctx) static
Definition at line 103 of file bintext.c.
draw_char()
static void draw_char (AVCodecContext * avctx, int c, int a) static
Draw character to screen.
Definition at line 121 of file bintext.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 136 of file bintext.c.
Referenced by decode_end().
decode_end()
static av_cold int decode_end (AVCodecContext * avctx) static
Definition at line 211 of file bintext.c.