FFmpeg: libavresample/aarch64/resample_init.c File Reference
resample_init.c File Reference
#include <stdint.h>
#include "config.h"
#include "libavutil/cpu.h"
#include "libavutil/aarch64/cpu.h"
#include "libavutil/internal.h"
#include "libavutil/samplefmt.h"
#include "libavresample/resample.h"
#include "asm-offsets.h"
Functions
AV_CHECK_OFFSET (struct ResampleContext, filter_bank, FILTER_BANK)
AV_CHECK_OFFSET (struct ResampleContext, filter_length, FILTER_LENGTH)
AV_CHECK_OFFSET (struct ResampleContext, phase_shift, PHASE_SHIFT)
AV_CHECK_OFFSET (struct ResampleContext, phase_mask, PHASE_MASK)
void ff_resample_one_dbl_neon (struct ResampleContext *c, void *dst0, int dst_index, const void *src0, unsigned int index, int frac)
void ff_resample_one_flt_neon (struct ResampleContext *c, void *dst0, int dst_index, const void *src0, unsigned int index, int frac)
void ff_resample_one_s16_neon (struct ResampleContext *c, void *dst0, int dst_index, const void *src0, unsigned int index, int frac)
void ff_resample_one_s32_neon (struct ResampleContext *c, void *dst0, int dst_index, const void *src0, unsigned int index, int frac)
av_cold void ff_audio_resample_init_aarch64 (ResampleContext *c, enum AVSampleFormat sample_fmt)
Function Documentation
AV_CHECK_OFFSET() [1/4]
AV_CHECK_OFFSET (struct ResampleContext , filter_bank , FILTER_BANK)
AV_CHECK_OFFSET() [2/4]
AV_CHECK_OFFSET (struct ResampleContext , filter_length , FILTER_LENGTH)
AV_CHECK_OFFSET() [3/4]
AV_CHECK_OFFSET (struct ResampleContext , phase_shift , PHASE_SHIFT)
AV_CHECK_OFFSET() [4/4]
AV_CHECK_OFFSET (struct ResampleContext , phase_mask , PHASE_MASK)
ff_resample_one_dbl_neon()
void ff_resample_one_dbl_neon (struct ResampleContext * c, void * dst0, int dst_index, const void * src0, unsigned int index, int frac)
Referenced by ff_audio_resample_init_aarch64().
ff_resample_one_flt_neon()
void ff_resample_one_flt_neon (struct ResampleContext * c, void * dst0, int dst_index, const void * src0, unsigned int index, int frac)
Referenced by ff_audio_resample_init_aarch64(), and ff_audio_resample_init_arm().
ff_resample_one_s16_neon()
void ff_resample_one_s16_neon (struct ResampleContext * c, void * dst0, int dst_index, const void * src0, unsigned int index, int frac)
Referenced by ff_audio_resample_init_aarch64(), and ff_audio_resample_init_arm().
ff_resample_one_s32_neon()
void ff_resample_one_s32_neon (struct ResampleContext * c, void * dst0, int dst_index, const void * src0, unsigned int index, int frac)
Referenced by ff_audio_resample_init_aarch64(), and ff_audio_resample_init_arm().
ff_audio_resample_init_aarch64()
av_cold void ff_audio_resample_init_aarch64 (ResampleContext * c, enum AVSampleFormat sample_fmt)
Definition at line 48 of file resample_init.c.
Referenced by ff_audio_resample_init().