FFmpeg: libavcodec/gif.c File Reference
gif.c File Reference
GIF encoder.
#include "libavutil/opt.h"
#include "libavutil/imgutils.h"
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
#include "lzw.h"
#include "gif.h"
#include "put_bits.h"
Data Structures
struct GIFContext
Macros
#define BITSTREAM_WRITER_LE
#define OFFSET(x) offsetof(GIFContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Enumerations
enum { GF_OFFSETTING = 1<<0, GF_TRANSDIFF = 1<<1 }
Functions
static int pick_palette_entry (const uint8_t *buf, int linesize, int w, int h)
static int gif_image_write_image (AVCodecContext *avctx, uint8_t **bytestream, uint8_t *end, const uint32_t *palette, const uint8_t *buf, const int linesize, AVPacket *pkt)
static av_cold int gif_encode_init (AVCodecContext *avctx)
static int get_palette_transparency_index (const uint32_t *palette)
static int gif_encode_frame (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *pict, int *got_packet)
static int gif_encode_close (AVCodecContext *avctx)
Variables
static const AVOption gif_options []
static const AVClass gif_class
AVCodec ff_gif_encoder
Detailed Description
GIF encoder.
See also
http://www.w3.org/Graphics/GIF/spec-gif89a.txt
Definition in file gif.c.
Macro Definition Documentation
BITSTREAM_WRITER_LE
#define BITSTREAM_WRITER_LE
Definition at line 31 of file gif.c.
OFFSET
#define OFFSET (x) offsetof(GIFContext, x)
Definition at line 332 of file gif.c.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 333 of file gif.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
GF_OFFSETTING
GF_TRANSDIFF
Definition at line 56 of file gif.c.
Function Documentation
pick_palette_entry()
static int pick_palette_entry (const uint8_t * buf, int linesize, int w, int h) static
Definition at line 61 of file gif.c.
Referenced by gif_image_write_image().
gif_image_write_image()
static int gif_image_write_image (AVCodecContext * avctx, uint8_t ** bytestream, uint8_t * end, const uint32_t * palette, const uint8_t * buf, const int linesize, AVPacket * pkt) static
Definition at line 77 of file gif.c.
Referenced by gif_encode_frame().
gif_encode_init()
static av_cold int gif_encode_init (AVCodecContext * avctx) static
Definition at line 217 of file gif.c.
get_palette_transparency_index()
static int get_palette_transparency_index (const uint32_t * palette) static
Definition at line 248 of file gif.c.
Referenced by gif_encode_frame().
gif_encode_frame()
static int gif_encode_frame (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * pict, int * got_packet) static
Definition at line 266 of file gif.c.
gif_encode_close()
static int gif_encode_close (AVCodecContext * avctx) static
Definition at line 320 of file gif.c.
Variable Documentation
gif_options
const AVOption gif_options[] static
Initial value:
= {
    { "gifflags", "set GIF flags", OFFSET(flags), AV_OPT_TYPE_FLAGS, {.i64 = GF_OFFSETTING|GF_TRANSDIFF}, 0, INT_MAX, FLAGS, "flags" },
        { "offsetting", "enable picture offsetting", 0, AV_OPT_TYPE_CONST, {.i64=GF_OFFSETTING}, INT_MIN, INT_MAX, FLAGS, "flags" },
        { "transdiff", "enable transparency detection between frames", 0, AV_OPT_TYPE_CONST, {.i64=GF_TRANSDIFF}, INT_MIN, INT_MAX, FLAGS, "flags" },
    { NULL }
}
Definition at line 334 of file gif.c.
gif_class
const AVClass gif_class static
Initial value:
= {
    .class_name = "GIF encoder",
    .item_name  = av_default_item_name,
    .option     = gif_options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 341 of file gif.c.
ff_gif_encoder
AVCodec ff_gif_encoder
Initial value:
= {
    .name           = "gif",
    .long_name      = NULL_IF_CONFIG_SMALL("GIF (Graphics Interchange Format)"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_GIF,
    .priv_data_size = sizeof(GIFContext),
    .init           = gif_encode_init,
    .encode2        = gif_encode_frame,
    .close          = gif_encode_close,
    .pix_fmts       = (const enum AVPixelFormat[]){
        AV_PIX_FMT_RGB8, AV_PIX_FMT_BGR8, AV_PIX_FMT_RGB4_BYTE, AV_PIX_FMT_BGR4_BYTE,
        AV_PIX_FMT_GRAY8, AV_PIX_FMT_PAL8, AV_PIX_FMT_NONE
    },
    .priv_class     = &gif_class,
}
Definition at line 348 of file gif.c.