FFmpeg: libavformat/fifo.c File Reference
fifo.c File Reference
#include "libavutil/opt.h"
#include "libavutil/time.h"
#include "libavutil/thread.h"
#include "libavutil/threadmessage.h"
#include "avformat.h"
#include "internal.h"
Data Structures
struct FifoContext
struct FifoThreadContext
struct FifoMessage
Macros
#define FIFO_DEFAULT_QUEUE_SIZE 60
#define FIFO_DEFAULT_MAX_RECOVERY_ATTEMPTS 0
#define FIFO_DEFAULT_RECOVERY_WAIT_TIME_USEC 5000000
#define OFFSET(x) offsetof(FifoContext, x)
Enumerations
enum FifoMessageType { FIFO_WRITE_HEADER, FIFO_WRITE_PACKET, FIFO_FLUSH_OUTPUT }
Functions
static int fifo_thread_write_header (FifoThreadContext *ctx)
static int fifo_thread_flush_output (FifoThreadContext *ctx)
static int fifo_thread_write_packet (FifoThreadContext *ctx, AVPacket *pkt)
static int fifo_thread_write_trailer (FifoThreadContext *ctx)
static int fifo_thread_dispatch_message (FifoThreadContext *ctx, FifoMessage *msg)
static int is_recoverable (const FifoContext *fifo, int err_no)
static void free_message (void *msg)
static int fifo_thread_process_recovery_failure (FifoThreadContext *ctx, AVPacket *pkt, int err_no)
static int fifo_thread_attempt_recovery (FifoThreadContext *ctx, FifoMessage *msg, int err_no)
static int fifo_thread_recover (FifoThreadContext *ctx, FifoMessage *msg, int err_no)
static void * fifo_consumer_thread (void *data)
static int fifo_mux_init (AVFormatContext *avf, AVOutputFormat *oformat)
static int fifo_init (AVFormatContext *avf)
static int fifo_write_header (AVFormatContext *avf)
static int fifo_write_packet (AVFormatContext *avf, AVPacket *pkt)
static int fifo_write_trailer (AVFormatContext *avf)
static void fifo_deinit (AVFormatContext *avf)
Variables
static const AVOption options []
static const AVClass fifo_muxer_class
AVOutputFormat ff_fifo_muxer
Macro Definition Documentation
FIFO_DEFAULT_QUEUE_SIZE
#define FIFO_DEFAULT_QUEUE_SIZE 60
Definition at line 29 of file fifo.c.
FIFO_DEFAULT_MAX_RECOVERY_ATTEMPTS
#define FIFO_DEFAULT_MAX_RECOVERY_ATTEMPTS 0
Definition at line 30 of file fifo.c.
FIFO_DEFAULT_RECOVERY_WAIT_TIME_USEC
#define FIFO_DEFAULT_RECOVERY_WAIT_TIME_USEC 5000000
Definition at line 31 of file fifo.c.
OFFSET
#define OFFSET (x) offsetof(FifoContext, x)
Definition at line 610 of file fifo.c.
Enumeration Type Documentation
FifoMessageType
enum FifoMessageType
Enumerator
FIFO_WRITE_HEADER
FIFO_WRITE_PACKET
FIFO_FLUSH_OUTPUT
Definition at line 103 of file fifo.c.
Function Documentation
fifo_thread_write_header()
static int fifo_thread_write_header (FifoThreadContext * ctx) static
Definition at line 114 of file fifo.c.
Referenced by fifo_thread_dispatch_message().
fifo_thread_flush_output()
static int fifo_thread_flush_output (FifoThreadContext * ctx) static
Definition at line 153 of file fifo.c.
Referenced by fifo_thread_dispatch_message().
fifo_thread_write_packet()
static int fifo_thread_write_packet (FifoThreadContext * ctx, AVPacket * pkt) static
Definition at line 162 of file fifo.c.
Referenced by fifo_thread_dispatch_message().
fifo_thread_write_trailer()
static int fifo_thread_write_trailer (FifoThreadContext * ctx) static
Definition at line 192 of file fifo.c.
Referenced by fifo_consumer_thread(), and fifo_thread_attempt_recovery().
fifo_thread_dispatch_message()
static int fifo_thread_dispatch_message (FifoThreadContext * ctx, FifoMessage * msg) static
Definition at line 208 of file fifo.c.
Referenced by fifo_consumer_thread(), and fifo_thread_attempt_recovery().
is_recoverable()
static int is_recoverable (const FifoContext * fifo, int err_no) static
Definition at line 230 of file fifo.c.
Referenced by fifo_thread_attempt_recovery().
free_message()
static void free_message (void * msg) static
Definition at line 249 of file fifo.c.
Referenced by fifo_init(), and fifo_thread_attempt_recovery().
fifo_thread_process_recovery_failure()
static int fifo_thread_process_recovery_failure (FifoThreadContext * ctx, AVPacket * pkt, int err_no) static
Definition at line 257 of file fifo.c.
Referenced by fifo_thread_attempt_recovery().
fifo_thread_attempt_recovery()
static int fifo_thread_attempt_recovery (FifoThreadContext * ctx, FifoMessage * msg, int err_no) static
Definition at line 289 of file fifo.c.
Referenced by fifo_thread_recover().
fifo_thread_recover()
static int fifo_thread_recover (FifoThreadContext * ctx, FifoMessage * msg, int err_no) static
Definition at line 360 of file fifo.c.
Referenced by fifo_consumer_thread().
fifo_consumer_thread()
static void* fifo_consumer_thread (void * data) static
Definition at line 386 of file fifo.c.
Referenced by fifo_write_header().
fifo_mux_init()
static int fifo_mux_init (AVFormatContext * avf, AVOutputFormat * oformat) static
Definition at line 442 of file fifo.c.
Referenced by fifo_init().
fifo_init()
static int fifo_init (AVFormatContext * avf) static
Definition at line 477 of file fifo.c.
fifo_write_header()
static int fifo_write_header (AVFormatContext * avf) static
Definition at line 524 of file fifo.c.
fifo_write_packet()
static int fifo_write_packet (AVFormatContext * avf, AVPacket * pkt) static
Definition at line 539 of file fifo.c.
fifo_write_trailer()
static int fifo_write_trailer (AVFormatContext * avf) static
Definition at line 581 of file fifo.c.
fifo_deinit()
static void fifo_deinit (AVFormatContext * avf) static
Definition at line 599 of file fifo.c.
Variable Documentation
options
const AVOption options[] static
Definition at line 611 of file fifo.c.
fifo_muxer_class
const AVClass fifo_muxer_class static
Initial value:
= {
    .class_name = "Fifo muxer",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 645 of file fifo.c.
ff_fifo_muxer
AVOutputFormat ff_fifo_muxer
Initial value:
= {
    .name           = "fifo",
    .long_name      = NULL_IF_CONFIG_SMALL("FIFO queue pseudo-muxer"),
    .priv_data_size = sizeof(FifoContext),
    .init           = fifo_init,
    .write_header   = fifo_write_header,
    .write_packet   = fifo_write_packet,
    .write_trailer  = fifo_write_trailer,
    .deinit         = fifo_deinit,
    .priv_class     = &fifo_muxer_class,
    .flags          = AVFMT_NOFILE | AVFMT_ALLOW_FLUSH | AVFMT_TS_NEGATIVE,
}
Definition at line 652 of file fifo.c.