FFmpeg: libavcodec/alacdsp.c File Reference
alacdsp.c File Reference
#include "libavutil/attributes.h"
#include "alacdsp.h"
#include "config.h"
Functions
static void decorrelate_stereo (int32_t *buffer[2], int nb_samples, int decorr_shift, int decorr_left_weight)
static void append_extra_bits (int32_t *buffer[2], int32_t *extra_bits_buffer[2], int extra_bits, int channels, int nb_samples)
av_cold void ff_alacdsp_init (ALACDSPContext *c)
Function Documentation
decorrelate_stereo()
static void decorrelate_stereo (int32_t * buffer[2], int nb_samples, int decorr_shift, int decorr_left_weight) static
Definition at line 26 of file alacdsp.c.
Referenced by ff_alacdsp_init().
append_extra_bits()
static void append_extra_bits (int32_t * buffer[2], int32_t * extra_bits_buffer[2], int extra_bits, int channels, int nb_samples) static
Definition at line 45 of file alacdsp.c.
Referenced by ff_alacdsp_init().
ff_alacdsp_init()
av_cold void ff_alacdsp_init (ALACDSPContext * c)
Definition at line 55 of file alacdsp.c.
Referenced by alac_decode_init(), check_append_extra_bits(), and check_decorrelate_stereo().