FFmpeg: libavcodec/flacdec.c File Reference
flacdec.c File Reference
FLAC (Free Lossless Audio Codec) decoder.
#include <limits.h>
#include "libavutil/avassert.h"
#include "libavutil/crc.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "internal.h"
#include "get_bits.h"
#include "bytestream.h"
#include "golomb.h"
#include "flac.h"
#include "flacdata.h"
#include "flacdsp.h"
#include "thread.h"
#include "unary.h"
Data Structures
struct FLACContext
Functions
static int allocate_buffers (FLACContext *s)
static void flac_set_bps (FLACContext *s)
static av_cold int flac_decode_init (AVCodecContext *avctx)
static void dump_headers (AVCodecContext *avctx, FLACStreaminfo *s)
static int parse_streaminfo (FLACContext *s, const uint8_t *buf, int buf_size)
Parse the STREAMINFO from an inline header.
static int get_metadata_size (const uint8_t *buf, int buf_size)
Determine the size of an inline header.
static int decode_residuals (FLACContext *s, int32_t *decoded, int pred_order)
static int decode_subframe_fixed (FLACContext *s, int32_t *decoded, int pred_order, int bps)
static void lpc_analyze_remodulate (int32_t *decoded, const int coeffs[32], int order, int qlevel, int len, int bps)
static int decode_subframe_lpc (FLACContext *s, int32_t *decoded, int pred_order, int bps)
static int decode_subframe (FLACContext *s, int channel)
static int decode_frame (FLACContext *s)
static int flac_decode_frame (AVCodecContext *avctx, void *data, int *got_frame_ptr, AVPacket *avpkt)
static av_cold int flac_decode_close (AVCodecContext *avctx)
Variables
static const AVOption options []
static const AVClass flac_decoder_class
AVCodec ff_flac_decoder
Detailed Description
FLAC (Free Lossless Audio Codec) decoder.
Author
Alex Beregszaszi
See also
http://flac.sourceforge.net/
This decoder can be used in 1 of 2 ways: Either raw FLAC data can be fed through, starting from the initial 'fLaC' signature; or by passing the 34-byte streaminfo structure through avctx->extradata[_size] followed by data starting with the 0xFFF8 marker.
Definition in file flacdec.c.
Function Documentation
allocate_buffers()
static int allocate_buffers (FLACContext * s) static
Definition at line 135 of file flacdec.c.
Referenced by decode_frame(), flac_decode_frame(), flac_decode_init(), and parse_streaminfo().
flac_set_bps()
static void flac_set_bps (FLACContext * s) static
Definition at line 73 of file flacdec.c.
Referenced by decode_frame(), flac_decode_init(), and parse_streaminfo().
flac_decode_init()
static av_cold int flac_decode_init (AVCodecContext * avctx) static
Definition at line 95 of file flacdec.c.
dump_headers()
static void dump_headers (AVCodecContext * avctx, FLACStreaminfo * s) static
Definition at line 126 of file flacdec.c.
Referenced by decode_frame().
parse_streaminfo()
static int parse_streaminfo (FLACContext * s, const uint8_t * buf, int buf_size) static
Parse the STREAMINFO from an inline header.
Parameters
s the flac decoding context
buf input buffer, starting with the "fLaC" marker
buf_size buffer size
Returns
non-zero if metadata is invalid
Definition at line 167 of file flacdec.c.
Referenced by flac_decode_frame().
get_metadata_size()
static int get_metadata_size (const uint8_t * buf, int buf_size) static
Determine the size of an inline header.
Parameters
buf input buffer, starting with the "fLaC" marker
buf_size buffer size
Returns
number of bytes in the header, or 0 if more data is needed
Definition at line 200 of file flacdec.c.
Referenced by flac_decode_frame().
decode_residuals()
static int decode_residuals (FLACContext * s, int32_t * decoded, int pred_order) static
Definition at line 221 of file flacdec.c.
Referenced by decode_subframe_fixed(), and decode_subframe_lpc().
decode_subframe_fixed()
static int decode_subframe_fixed (FLACContext * s, int32_t * decoded, int pred_order, int bps) static
Definition at line 271 of file flacdec.c.
Referenced by decode_subframe().
lpc_analyze_remodulate()
static void lpc_analyze_remodulate (int32_t * decoded, const int coeffs[32], int order, int qlevel, int len, int bps) static
Definition at line 323 of file flacdec.c.
Referenced by decode_subframe_lpc().
decode_subframe_lpc()
static int decode_subframe_lpc (FLACContext * s, int32_t * decoded, int pred_order, int bps) static
Definition at line 350 of file flacdec.c.
Referenced by decode_subframe().
decode_subframe()
static int decode_subframe (FLACContext * s, int channel) inline static
Definition at line 394 of file flacdec.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (FLACContext * s) static
Definition at line 461 of file flacdec.c.
Referenced by flac_decode_frame().
flac_decode_frame()
static int flac_decode_frame (AVCodecContext * avctx, void * data, int * got_frame_ptr, AVPacket * avpkt) static
Definition at line 547 of file flacdec.c.
flac_decode_close()
static av_cold int flac_decode_close (AVCodecContext * avctx) static
Definition at line 644 of file flacdec.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
{ "use_buggy_lpc", "emulate old buggy lavc behavior", 0x42, AV_OPT_TYPE_BOOL, {.i64 = 0 }, 0, 1, AV_OPT_FLAG_DECODING_PARAM | AV_OPT_FLAG_AUDIO_PARAM },
{ NULL },
}
Definition at line 653 of file flacdec.c.
flac_decoder_class
const AVClass flac_decoder_class static
Initial value:
= {
    "FLAC decoder",
    av_default_item_name,
    options,
    LIBAVUTIL_VERSION_INT,
}
Definition at line 658 of file flacdec.c.
ff_flac_decoder
AVCodec ff_flac_decoder
Initial value:
= {
    .name           = "flac",
    .long_name      = NULL_IF_CONFIG_SMALL("FLAC (Free Lossless Audio Codec)"),
    .type           = AVMEDIA_TYPE_AUDIO,
    .id             = AV_CODEC_ID_FLAC,
    .priv_data_size = sizeof(FLACContext),
    .init           = flac_decode_init,
    .close          = flac_decode_close,
    .decode         = flac_decode_frame,
    .init_thread_copy = ONLY_IF_THREADS_ENABLED(init_thread_copy),
    .capabilities   = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_FRAME_THREADS,
    .sample_fmts    = (const enum AVSampleFormat[]) { AV_SAMPLE_FMT_S16,
                                                      AV_SAMPLE_FMT_S16P,
                                                      AV_SAMPLE_FMT_S32,
                                                      AV_SAMPLE_FMT_S32P,
                                                      AV_SAMPLE_FMT_NONE },
    .priv_class     = &flac_decoder_class,
}
Definition at line 665 of file flacdec.c.