FFmpeg: libavformat/replaygain.h File Reference
replaygain.h File Reference
#include "libavutil/dict.h"
#include "avformat.h"
Functions
int ff_replaygain_export (AVStream *st, AVDictionary *metadata)
Parse replaygain tags and export them as per-stream side data.
int ff_replaygain_export_raw (AVStream *st, int32_t tg, uint32_t tp, int32_t ag, uint32_t ap)
Export already decoded replaygain values as per-stream side data.
Function Documentation
ff_replaygain_export()
int ff_replaygain_export (AVStream * st, AVDictionary * metadata)
Parse replaygain tags and export them as per-stream side data.
Definition at line 91 of file replaygain.c.
Referenced by flac_read_header(), mov_read_header(), mp3_read_header(), and vorbis_header().
ff_replaygain_export_raw()
int ff_replaygain_export_raw (AVStream * st, int32_t tg, uint32_t tp, int32_t ag, uint32_t ap)
Export already decoded replaygain values as per-stream side data.
Definition at line 70 of file replaygain.c.
Referenced by ff_replaygain_export(), and mp3_parse_info_tag().