FFmpeg: libavformat/dv.h File Reference
dv.h File Reference
#include "avformat.h"
Functions
DVDemuxContext * avpriv_dv_init_demux (AVFormatContext *s)
int avpriv_dv_get_packet (DVDemuxContext *, AVPacket *)
int avpriv_dv_produce_packet (DVDemuxContext *, AVPacket *, uint8_t *, int, int64_t)
void ff_dv_offset_reset (DVDemuxContext *c, int64_t frame_offset)
Function Documentation
avpriv_dv_init_demux()
DVDemuxContext* avpriv_dv_init_demux (AVFormatContext * s)
Definition at line 324 of file dv.c.
Referenced by avi_read_header(), dv1394_read_header(), dv_read_header(), iec61883_read_header(), and mov_finalize_stsd_codec().
avpriv_dv_get_packet()
int avpriv_dv_get_packet (DVDemuxContext * , AVPacket *)
Definition at line 347 of file dv.c.
Referenced by avi_read_packet(), dv1394_read_packet(), dv_read_packet(), iec61883_parse_queue_dv(), and mov_read_packet().
avpriv_dv_produce_packet()
int avpriv_dv_produce_packet (DVDemuxContext * , AVPacket * , uint8_t * , int , int64_t)
Definition at line 364 of file dv.c.
Referenced by avi_read_packet(), dv1394_read_packet(), dv_read_packet(), iec61883_parse_queue_dv(), and mov_read_packet().
ff_dv_offset_reset()
void ff_dv_offset_reset (DVDemuxContext * c, int64_t frame_offset)
Definition at line 436 of file dv.c.
Referenced by avi_read_seek(), and dv_read_seek().