FFmpeg: libavcodec/h264dec.c File Reference
h264dec.c File Reference
H.264 / AVC / MPEG-4 part10 codec.
#include "libavutil/avassert.h"
#include "libavutil/display.h"
#include "libavutil/imgutils.h"
#include "libavutil/opt.h"
#include "libavutil/stereo3d.h"
#include "libavutil/timer.h"
#include "internal.h"
#include "bytestream.h"
#include "cabac.h"
#include "cabac_functions.h"
#include "error_resilience.h"
#include "avcodec.h"
#include "h264.h"
#include "h264dec.h"
#include "h2645_parse.h"
#include "h264data.h"
#include "h264chroma.h"
#include "h264_mvpred.h"
#include "h264_ps.h"
#include "golomb.h"
#include "mathops.h"
#include "me_cmp.h"
#include "mpegutils.h"
#include "profiles.h"
#include "rectangle.h"
#include "thread.h"
#include "vdpau_compat.h"
Macros
#define UNCHECKED_BITSTREAM_READER 1
#define OFFSET(x) offsetof(H264Context, x)
#define VD AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_DECODING_PARAM
Functions
static int h264_decode_end (AVCodecContext *avctx)
int avpriv_h264_has_num_reorder_frames (AVCodecContext *avctx)
static void h264_er_decode_mb (void *opaque, int ref, int mv_dir, int mv_type, int(*mv)[2][4][2], int mb_x, int mb_y, int mb_intra, int mb_skipped)
void ff_h264_draw_horiz_band (const H264Context *h, H264SliceContext *sl, int y, int height)
void ff_h264_free_tables (H264Context *h)
int ff_h264_alloc_tables (H264Context *h)
Allocate tables.
int ff_h264_slice_context_init (H264Context *h, H264SliceContext *sl)
Init context Allocate buffers which are not shared amongst multiple threads.
static int h264_init_context (AVCodecContext *avctx, H264Context *h)
av_cold int ff_h264_decode_init (AVCodecContext *avctx)
static void decode_postinit (H264Context *h, int setup_finished)
Run setup operations that must be run after slice header decoding.
static void idr (H264Context *h)
instantaneous decoder refresh.
void ff_h264_flush_change (H264Context *h)
static void flush_dpb (AVCodecContext *avctx)
static int get_last_needed_nal (H264Context *h)
static void debug_green_metadata (const H264SEIGreenMetaData *gm, void *logctx)
static int decode_nal_units (H264Context *h, const uint8_t *buf, int buf_size)
static int get_consumed_bytes (int pos, int buf_size)
Return the number of bytes consumed for building the current frame.
static int output_frame (H264Context *h, AVFrame *dst, H264Picture *srcp)
static int is_extra (const uint8_t *buf, int buf_size)
static int h264_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
Variables
const uint16_t ff_h264_mb_sizes [4] = { 256, 384, 512, 768 }
static AVOnce h264_vlc_init = AV_ONCE_INIT
static const uint8_t start_code [] = { 0x00, 0x00, 0x01 }
static const AVOption h264_options []
static const AVClass h264_class
AVCodec ff_h264_decoder
Detailed Description
H.264 / AVC / MPEG-4 part10 codec.
Author
Michael Niedermayer micha.nosp@m.elni.nosp@m.@gmx..nosp@m.at
Definition in file h264dec.c.
Macro Definition Documentation
UNCHECKED_BITSTREAM_READER
#define UNCHECKED_BITSTREAM_READER 1
Definition at line 28 of file h264dec.c.
OFFSET
#define OFFSET (x) offsetof(H264Context, x)
Definition at line 1196 of file h264dec.c.
VD
#define VD AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_DECODING_PARAM
Definition at line 1197 of file h264dec.c.
Function Documentation
h264_decode_end()
static av_cold int h264_decode_end (AVCodecContext * avctx) static
Definition at line 360 of file h264dec.c.
Referenced by ff_h264_decode_init().
avpriv_h264_has_num_reorder_frames()
int avpriv_h264_has_num_reorder_frames (AVCodecContext * avctx)
Definition at line 62 of file h264dec.c.
Referenced by ff_exp2fi(), and has_decode_delay_been_guessed().
h264_er_decode_mb()
static void h264_er_decode_mb (void * opaque, int ref, int mv_dir, int mv_type, int(*) mv[2][4][2], int mb_x, int mb_y, int mb_intra, int mb_skipped) static
Definition at line 68 of file h264dec.c.
Referenced by ff_h264_slice_context_init().
ff_h264_draw_horiz_band()
void ff_h264_draw_horiz_band (const H264Context * h, H264SliceContext * sl, int y, int height)
Definition at line 104 of file h264dec.c.
Referenced by decode_finish_row(), dxva2_h264_end_frame(), ff_vdpau_add_buffer(), find_start_code(), vaapi_h264_end_frame(), and vdpau_h264_end_frame().
ff_h264_free_tables()
void ff_h264_free_tables (H264Context * h)
Definition at line 139 of file h264dec.c.
Referenced by ff_h264_alloc_tables(), flush_dpb(), h264_decode_end(), and h264_slice_header_init().
ff_h264_alloc_tables()
int ff_h264_alloc_tables (H264Context * h)
Allocate tables.
needs width/height
Definition at line 182 of file h264dec.c.
Referenced by h264_slice_header_init().
ff_h264_slice_context_init()
int ff_h264_slice_context_init (H264Context * h, H264SliceContext * sl)
Init context Allocate buffers which are not shared amongst multiple threads.
Definition at line 240 of file h264dec.c.
Referenced by find_start_code(), and h264_slice_header_init().
h264_init_context()
static int h264_init_context (AVCodecContext * avctx, H264Context * h) static
Definition at line 305 of file h264dec.c.
Referenced by ff_h264_decode_init().
ff_h264_decode_init()
av_cold int ff_h264_decode_init (AVCodecContext * avctx)
Definition at line 394 of file h264dec.c.
decode_postinit()
static void decode_postinit (H264Context * h, int setup_finished) static
Run setup operations that must be run after slice header decoding.
This includes finding the next displayed frame.
Parameters
h h264 master context
setup_finished enough NALs have been read that we can call ff_thread_finish_setup()
Definition at line 477 of file h264dec.c.
Referenced by decode_nal_units(), and h264_decode_frame().
idr()
static void idr (H264Context * h) static
instantaneous decoder refresh.
Definition at line 596 of file h264dec.c.
Referenced by decode_nal_units(), ff_h264_flush_change(), and h264_probe().
ff_h264_flush_change()
void ff_h264_flush_change (H264Context * h)
Definition at line 609 of file h264dec.c.
Referenced by ff_h264_decode_init(), flush_dpb(), and h264_init_ps().
flush_dpb()
static void flush_dpb (AVCodecContext * avctx) static
Definition at line 636 of file h264dec.c.
get_last_needed_nal()
static int get_last_needed_nal (H264Context * h) static
Definition at line 660 of file h264dec.c.
Referenced by decode_nal_units().
debug_green_metadata()
static void debug_green_metadata (const H264SEIGreenMetaData * gm, void * logctx) static
Definition at line 698 of file h264dec.c.
Referenced by decode_nal_units().
decode_nal_units()
static int decode_nal_units (H264Context * h, const uint8_t * buf, int buf_size) static
< number of NALs that need decoding before the next frame thread starts
Definition at line 726 of file h264dec.c.
Referenced by h264_decode_frame().
get_consumed_bytes()
static int get_consumed_bytes (int pos, int buf_size) static
Return the number of bytes consumed for building the current frame.
Definition at line 974 of file h264dec.c.
Referenced by h264_decode_frame().
output_frame()
static int output_frame (H264Context * h, AVFrame * dst, H264Picture * srcp) static
Examples:
transcode_aac.c.
Definition at line 984 of file h264dec.c.
Referenced by h264_decode_frame(), load_encode_and_write(), and scale_vaapi_filter_frame().
is_extra()
static int is_extra (const uint8_t * buf, int buf_size) static
Definition at line 1018 of file h264dec.c.
Referenced by h264_decode_frame().
h264_decode_frame()
static int h264_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 1040 of file h264dec.c.
Variable Documentation
ff_h264_mb_sizes
const uint16_t ff_h264_mb_sizes[4] = { 256, 384, 512, 768 }
Definition at line 60 of file h264dec.c.
Referenced by ff_h264_decode_mb_cabac(), ff_h264_decode_mb_cavlc(), and hl_decode_mb().
h264_vlc_init
AVOnce h264_vlc_init = AV_ONCE_INIT static
Definition at line 392 of file h264dec.c.
start_code
const uint8_t start_code[] = { 0x00, 0x00, 0x01 } static
Definition at line 657 of file h264dec.c.
Referenced by commit_bitstream_and_slice_buffer(), decode_chunks(), ff_mjpeg_decode_frame(), ff_mjpeg_find_marker(), ff_msmpeg4_decode_picture_header(), ff_rtp_send_mpegvideo(), mpeg_decode_slice(), mpegvideo_extract_headers(), mxpeg_decode_frame(), set_spdif(), and slice_decode_thread().
h264_options
const AVOption h264_options[] static
Initial value:
= {
    {"is_avc", "is avc", 0x42, AV_OPT_TYPE_BOOL, {.i64 = 0}, 0, 1, 0},
    {"nal_length_size", "nal_length_size", 0x42, AV_OPT_TYPE_INT, {.i64 = 0}, 0, 4, 0},
    { "enable_er", "Enable error resilience on damaged frames (unsafe)", OFFSET(enable_er), AV_OPT_TYPE_BOOL, { .i64 = -1 }, -1, 1, VD },
    { NULL },
}
Definition at line 1198 of file h264dec.c.
h264_class
const AVClass h264_class static
Initial value:
= {
    .class_name = "H264 Decoder",
    .item_name  = av_default_item_name,
    .option     = h264_options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1205 of file h264dec.c.
ff_h264_decoder
AVCodec ff_h264_decoder
Initial value:
= {
    .name                  = "h264",
    .long_name             = NULL_IF_CONFIG_SMALL("H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10"),
    .type                  = AVMEDIA_TYPE_VIDEO,
    .id                    = AV_CODEC_ID_H264,
    .priv_data_size        = sizeof(H264Context),
    .init                  = ff_h264_decode_init,
    .close                 = h264_decode_end,
    .decode                = h264_decode_frame,
    .capabilities          =  AV_CODEC_CAP_DR1 |
                             AV_CODEC_CAP_DELAY | AV_CODEC_CAP_SLICE_THREADS |
                             AV_CODEC_CAP_FRAME_THREADS,
    .caps_internal         = FF_CODEC_CAP_INIT_THREADSAFE,
    .flush                 = flush_dpb,
    .init_thread_copy      = ONLY_IF_THREADS_ENABLED(decode_init_thread_copy),
    .update_thread_context = ONLY_IF_THREADS_ENABLED(ff_h264_update_thread_context),
    .profiles              = NULL_IF_CONFIG_SMALL(ff_h264_profiles),
    .priv_class            = &h264_class,
}
Definition at line 1212 of file h264dec.c.