FFmpeg: libavcodec/bswapdsp.c File Reference
bswapdsp.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/bswap.h"
#include "bswapdsp.h"
Functions
static void bswap_buf (uint32_t *dst, const uint32_t *src, int w)
static void bswap16_buf (uint16_t *dst, const uint16_t *src, int len)
av_cold void ff_bswapdsp_init (BswapDSPContext *c)
Function Documentation
bswap_buf()
static void bswap_buf (uint32_t * dst, const uint32_t * src, int w) static
Definition at line 25 of file bswapdsp.c.
Referenced by ff_bswapdsp_init().
bswap16_buf()
static void bswap16_buf (uint16_t * dst, const uint16_t * src, int len) static
Definition at line 43 of file bswapdsp.c.
Referenced by ff_bswapdsp_init().
ff_bswapdsp_init()
av_cold void ff_bswapdsp_init (BswapDSPContext * c)
Definition at line 49 of file bswapdsp.c.
Referenced by ac3_decode_init(), ape_decode_init(), checkasm_check_bswapdsp(), cllc_decode_init(), decode_init(), ff_asv_common_init(), ff_huffyuv_common_init(), flac_encode_init(), hevc_init_context(), imc_decode_init(), mimic_decode_init(), mp_decode_init(), mpc7_decode_init(), raw_init_decoder(), tqi_decode_init(), truespeech_decode_init(), and utvideo_encode_init().