FFmpeg: libavcodec/h264dsp.c File Reference
h264dsp.c File Reference
H.264 / AVC / MPEG-4 part10 DSP functions.
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/avassert.h"
#include "avcodec.h"
#include "h264dsp.h"
#include "h264idct.h"
#include "startcode.h"
#include "libavutil/common.h"
#include "h264dsp_template.c"
#include "h264addpx_template.c"
Macros
#define BIT_DEPTH 8
#define BIT_DEPTH 9
#define BIT_DEPTH 10
#define BIT_DEPTH 12
#define BIT_DEPTH 14
#define BIT_DEPTH 8
#define BIT_DEPTH 16
#define FUNC(a, depth) a ## _ ## depth ## _c
#define ADDPX_DSP(depth)
#define H264_DSP(depth)
Functions
av_cold void ff_h264dsp_init (H264DSPContext *c, const int bit_depth, const int chroma_format_idc)
Detailed Description
H.264 / AVC / MPEG-4 part10 DSP functions.
Author
Michael Niedermayer micha.nosp@m.elni.nosp@m.@gmx..nosp@m.at
Definition in file h264dsp.c.
Macro Definition Documentation
BIT_DEPTH [1/7]
#define BIT_DEPTH 8
Definition at line 63 of file h264dsp.c.
BIT_DEPTH [2/7]
#define BIT_DEPTH 9
Definition at line 63 of file h264dsp.c.
BIT_DEPTH [3/7]
#define BIT_DEPTH 10
Definition at line 63 of file h264dsp.c.
BIT_DEPTH [4/7]
#define BIT_DEPTH 12
Definition at line 63 of file h264dsp.c.
BIT_DEPTH [5/7]
#define BIT_DEPTH 14
Definition at line 63 of file h264dsp.c.
BIT_DEPTH [6/7]
#define BIT_DEPTH 8
Definition at line 63 of file h264dsp.c.
BIT_DEPTH [7/7]
#define BIT_DEPTH 16
Definition at line 63 of file h264dsp.c.
FUNC
#define FUNC (a, depth) a ## _ ## depth ## _c
ADDPX_DSP
#define ADDPX_DSP (depth)
Value:
c->h264_add_pixels4_clear = FUNC(ff_h264_add_pixels4, depth);\
    c->h264_add_pixels8_clear = FUNC(ff_h264_add_pixels8, depth)
Referenced by ff_h264dsp_init().
H264_DSP
#define H264_DSP (depth)
Referenced by ff_h264dsp_init().
Function Documentation
ff_h264dsp_init()
av_cold void ff_h264dsp_init (H264DSPContext * c, const int bit_depth, const int chroma_format_idc)
Definition at line 67 of file h264dsp.c.
Referenced by check_idct(), h264_slice_header_init(), init(), and svq3_decode_init().