FFmpeg: libavformat/flvdec.c File Reference
flvdec.c File Reference
#include "libavutil/avstring.h"
#include "libavutil/channel_layout.h"
#include "libavutil/dict.h"
#include "libavutil/opt.h"
#include "libavutil/intfloat.h"
#include "libavutil/mathematics.h"
#include "libavcodec/bytestream.h"
#include "libavcodec/mpeg4audio.h"
#include "avformat.h"
#include "internal.h"
#include "avio_internal.h"
#include "flv.h"
Data Structures
struct FLVContext
Macros
#define VALIDATE_INDEX_TS_THRESH 2500
#define RESYNC_BUFFER_SIZE (1<<20)
#define TYPE_ONTEXTDATA 1
#define TYPE_ONCAPTION 2
#define TYPE_ONCAPTIONINFO 3
#define TYPE_UNKNOWN 9
#define OFFSET(x) offsetof(FLVContext, x)
#define VD AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_DECODING_PARAM
Functions
static int probe (AVProbeData *p, int live)
static int flv_probe (AVProbeData *p)
static int live_flv_probe (AVProbeData *p)
static void add_keyframes_index (AVFormatContext *s)
static AVStream * create_stream (AVFormatContext *s, int codec_type)
static int flv_same_audio_codec (AVCodecParameters *apar, int flags)
static void flv_set_audio_codec (AVFormatContext *s, AVStream *astream, AVCodecParameters *apar, int flv_codecid)
static int flv_same_video_codec (AVCodecParameters *vpar, int flags)
static int flv_set_video_codec (AVFormatContext *s, AVStream *vstream, int flv_codecid, int read)
static int amf_get_string (AVIOContext *ioc, char *buffer, int buffsize)
static int parse_keyframes_index (AVFormatContext *s, AVIOContext *ioc, int64_t max_pos)
static int amf_parse_object (AVFormatContext *s, AVStream *astream, AVStream *vstream, const char *key, int64_t max_pos, int depth)
static int flv_read_metabody (AVFormatContext *s, int64_t next_pos)
static int flv_read_header (AVFormatContext *s)
static int flv_read_close (AVFormatContext *s)
static int flv_get_extradata (AVFormatContext *s, AVStream *st, int size)
static int flv_queue_extradata (FLVContext *flv, AVIOContext *pb, int stream, int size)
static void clear_index_entries (AVFormatContext *s, int64_t pos)
static int amf_skip_tag (AVIOContext *pb, AMFDataType type)
static int flv_data_packet (AVFormatContext *s, AVPacket *pkt, int64_t dts, int64_t next)
static int resync (AVFormatContext *s)
static int flv_read_packet (AVFormatContext *s, AVPacket *pkt)
static int flv_read_seek (AVFormatContext *s, int stream_index, int64_t ts, int flags)
Variables
static const AVOption options []
static const AVClass flv_class
AVInputFormat ff_flv_demuxer
static const AVClass live_flv_class
AVInputFormat ff_live_flv_demuxer
Macro Definition Documentation
VALIDATE_INDEX_TS_THRESH
#define VALIDATE_INDEX_TS_THRESH 2500
Definition at line 40 of file flvdec.c.
Referenced by flv_read_packet().
RESYNC_BUFFER_SIZE
#define RESYNC_BUFFER_SIZE (1<<20)
Definition at line 42 of file flvdec.c.
Referenced by resync().
TYPE_ONTEXTDATA
#define TYPE_ONTEXTDATA 1
Definition at line 642 of file flvdec.c.
Referenced by flv_read_metabody(), and flv_read_packet().
TYPE_ONCAPTION
#define TYPE_ONCAPTION 2
Definition at line 643 of file flvdec.c.
Referenced by flv_read_metabody(), and flv_read_packet().
TYPE_ONCAPTIONINFO
#define TYPE_ONCAPTIONINFO 3
Definition at line 644 of file flvdec.c.
Referenced by flv_read_metabody().
TYPE_UNKNOWN
#define TYPE_UNKNOWN 9
Definition at line 645 of file flvdec.c.
Referenced by flv_read_metabody(), and flv_read_packet().
OFFSET
#define OFFSET (x) offsetof(FLVContext, x)
Definition at line 1253 of file flvdec.c.
VD
#define VD AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_DECODING_PARAM
Definition at line 1254 of file flvdec.c.
Function Documentation
probe()
static int probe (AVProbeData * p, int live) static
Definition at line 75 of file flvdec.c.
Referenced by flv_probe(), and live_flv_probe().
flv_probe()
static int flv_probe (AVProbeData * p) static
Definition at line 94 of file flvdec.c.
live_flv_probe()
static int live_flv_probe (AVProbeData * p) static
Definition at line 99 of file flvdec.c.
add_keyframes_index()
static void add_keyframes_index (AVFormatContext * s) static
Definition at line 104 of file flvdec.c.
Referenced by amf_parse_object(), and create_stream().
create_stream()
static AVStream* create_stream (AVFormatContext * s, int codec_type) static
Definition at line 135 of file flvdec.c.
Referenced by amf_parse_object(), flv_data_packet(), and flv_read_packet().
flv_same_audio_codec()
static int flv_same_audio_codec (AVCodecParameters * apar, int flags) static
Definition at line 163 of file flvdec.c.
Referenced by flv_read_packet().
flv_set_audio_codec()
static void flv_set_audio_codec (AVFormatContext * s, AVStream * astream, AVCodecParameters * apar, int flv_codecid) static
Definition at line 214 of file flvdec.c.
Referenced by amf_parse_object(), and flv_read_packet().
flv_same_video_codec()
static int flv_same_video_codec (AVCodecParameters * vpar, int flags) static
Definition at line 274 of file flvdec.c.
Referenced by flv_read_packet().
flv_set_video_codec()
static int flv_set_video_codec (AVFormatContext * s, AVStream * vstream, int flv_codecid, int read) static
Definition at line 299 of file flvdec.c.
Referenced by amf_parse_object(), and flv_read_packet().
amf_get_string()
static int amf_get_string (AVIOContext * ioc, char * buffer, int buffsize) static
Definition at line 356 of file flvdec.c.
Referenced by amf_parse_object(), flv_data_packet(), flv_read_metabody(), and parse_keyframes_index().
parse_keyframes_index()
static int parse_keyframes_index (AVFormatContext * s, AVIOContext * ioc, int64_t max_pos) static
Definition at line 371 of file flvdec.c.
Referenced by amf_parse_object().
amf_parse_object()
static int amf_parse_object (AVFormatContext * s, AVStream * astream, AVStream * vstream, const char * key, int64_t max_pos, int depth) static
Definition at line 457 of file flvdec.c.
Referenced by flv_read_metabody().
flv_read_metabody()
static int flv_read_metabody (AVFormatContext * s, int64_t next_pos) static
Definition at line 647 of file flvdec.c.
Referenced by flv_read_packet().
flv_read_header()
static int flv_read_header (AVFormatContext * s) static
Definition at line 707 of file flvdec.c.
flv_read_close()
static int flv_read_close (AVFormatContext * s) static
Definition at line 731 of file flvdec.c.
flv_get_extradata()
static int flv_get_extradata (AVFormatContext * s, AVStream * st, int size) static
Definition at line 742 of file flvdec.c.
Referenced by flv_read_packet().
flv_queue_extradata()
static int flv_queue_extradata (FLVContext * flv, AVIOContext * pb, int stream, int size) static
Definition at line 750 of file flvdec.c.
Referenced by flv_read_packet().
clear_index_entries()
static void clear_index_entries (AVFormatContext * s, int64_t pos) static
Definition at line 763 of file flvdec.c.
Referenced by flv_read_packet().
amf_skip_tag()
static int amf_skip_tag (AVIOContext * pb, AMFDataType type) static
Definition at line 779 of file flvdec.c.
Referenced by flv_data_packet().
flv_data_packet()
static int flv_data_packet (AVFormatContext * s, AVPacket * pkt, int64_t dts, int64_t next) static
Definition at line 820 of file flvdec.c.
Referenced by flv_read_packet().
resync()
static int resync (AVFormatContext * s) static
Definition at line 887 of file flvdec.c.
Referenced by avi_read_packet(), flv_read_packet(), and nut_read_packet().
flv_read_packet()
static int flv_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 917 of file flvdec.c.
flv_read_seek()
static int flv_read_seek (AVFormatContext * s, int stream_index, int64_t ts, int flags) static
Definition at line 1245 of file flvdec.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "flv_metadata", "Allocate streams according to the onMetaData array", OFFSET(trust_metadata), AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, VD },
    { "missing_streams", "", OFFSET(missing_streams), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, 0xFF, VD | AV_OPT_FLAG_EXPORT | AV_OPT_FLAG_READONLY },
    { NULL }
}
Definition at line 1255 of file flvdec.c.
flv_class
const AVClass flv_class static
Initial value:
= {
    .class_name = "flvdec",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1261 of file flvdec.c.
ff_flv_demuxer
AVInputFormat ff_flv_demuxer
Initial value:
= {
    .name           = "flv",
    .long_name      = NULL_IF_CONFIG_SMALL("FLV (Flash Video)"),
    .priv_data_size = sizeof(FLVContext),
    .read_probe     = flv_probe,
    .read_header    = flv_read_header,
    .read_packet    = flv_read_packet,
    .read_seek      = flv_read_seek,
    .read_close     = flv_read_close,
    .extensions     = "flv",
    .priv_class     = &flv_class,
}
Definition at line 1268 of file flvdec.c.
live_flv_class
const AVClass live_flv_class static
Initial value:
= {
    .class_name = "live_flvdec",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1281 of file flvdec.c.
ff_live_flv_demuxer
AVInputFormat ff_live_flv_demuxer
Initial value:
= {
    .name           = "live_flv",
    .long_name      = NULL_IF_CONFIG_SMALL("live RTMP FLV (Flash Video)"),
    .priv_data_size = sizeof(FLVContext),
    .read_probe     = live_flv_probe,
    .read_header    = flv_read_header,
    .read_packet    = flv_read_packet,
    .read_seek      = flv_read_seek,
    .read_close     = flv_read_close,
    .extensions     = "flv",
    .priv_class     = &live_flv_class,
    .flags          = AVFMT_TS_DISCONT
}
Definition at line 1288 of file flvdec.c.