FFmpeg: libavcodec/pixblockdsp.c File Reference
pixblockdsp.c File Reference
#include <stdint.h>
#include "config.h"
#include "libavutil/attributes.h"
#include "libavutil/intreadwrite.h"
#include "avcodec.h"
#include "pixblockdsp.h"
Functions
static void get_pixels_16_c (int16_t *av_restrict block, const uint8_t *pixels, ptrdiff_t line_size)
static void get_pixels_8_c (int16_t *av_restrict block, const uint8_t *pixels, ptrdiff_t line_size)
static void diff_pixels_c (int16_t *av_restrict block, const uint8_t *s1, const uint8_t *s2, int stride)
av_cold void ff_pixblockdsp_init (PixblockDSPContext *c, AVCodecContext *avctx)
Function Documentation
get_pixels_16_c()
static void get_pixels_16_c (int16_t *av_restrict block, const uint8_t * pixels, ptrdiff_t line_size) static
Definition at line 27 of file pixblockdsp.c.
Referenced by ff_pixblockdsp_init().
get_pixels_8_c()
static void get_pixels_8_c (int16_t *av_restrict block, const uint8_t * pixels, ptrdiff_t line_size) static
Definition at line 40 of file pixblockdsp.c.
Referenced by ff_pixblockdsp_init().
diff_pixels_c()
static void diff_pixels_c (int16_t *av_restrict block, const uint8_t * s1, const uint8_t * s2, int stride) static
Definition at line 60 of file pixblockdsp.c.
Referenced by ff_pixblockdsp_init().
ff_pixblockdsp_init()
av_cold void ff_pixblockdsp_init (PixblockDSPContext * c, AVCodecContext * avctx)
Definition at line 81 of file pixblockdsp.c.
Referenced by avcodec_dct_init(), checkasm_check_pixblockdsp(), dnxhd_encode_init(), dvvideo_encode_init(), encode_init(), and ff_mpv_encode_init().