FFmpeg: libavutil/file_open.c File Reference
file_open.c File Reference
#include "config.h"
#include "internal.h"
#include "mem.h"
#include <stdarg.h>
#include <fcntl.h>
#include <sys/stat.h>
Data Structures
struct FileLogContext
Macros
#define O_BINARY 0
#define O_EXCL 0
Functions
int avpriv_open (const char *filename, int flags,...)
A wrapper for open() setting O_CLOEXEC.
int avpriv_tempfile (const char *prefix, char **filename, int log_offset, void *log_ctx)
Wrapper to work around the lack of mkstemp() on mingw.
FILE * av_fopen_utf8 (const char *path, const char *mode)
Open a file using a UTF-8 filename.
Variables
static const AVClass file_log_ctx_class
Macro Definition Documentation
O_BINARY
#define O_BINARY 0
Examples:
ffhash.c.
Referenced by av_fopen_utf8(), avpriv_tempfile(), check(), and file_move().
O_EXCL
#define O_EXCL 0
Referenced by avpriv_tempfile().
Function Documentation
avpriv_open()
int avpriv_open (const char * filename, int flags, ...)
A wrapper for open() setting O_CLOEXEC.
Definition at line 66 of file file_open.c.
Referenced by av_file_map(), av_fopen_utf8(), bktr_init(), dv1394_read_header(), fbdev_read_header(), fbdev_write_header(), ff_fbdev_get_device_list(), ff_oss_audio_open(), ff_rint64_clip(), file_move(), and read_random().
avpriv_tempfile()
int avpriv_tempfile (const char * prefix, char ** filename, int log_offset, void * log_ctx)
Wrapper to work around the lack of mkstemp() on mingw.
Also, tries to create file in /tmp first, if possible. *prefix can be a character constant; *filename will be allocated internally.
Returns
file descriptor of opened file (or negative value corresponding to an AVERROR code on error) and opened file name in **filename.
Note
On very old libcs it is necessary to set a secure umask before calling this, av_tempfile() can't call umask itself as it is used in libraries and could interfere with the calling application.
Definition at line 106 of file file_open.c.
Referenced by av_tempfile(), cache_open(), ff_rint64_clip(), ff_xvid_rate_control_init(), and xvid_encode_init().
Variable Documentation
file_log_ctx_class
const AVClass file_log_ctx_class static
Initial value:
= {
    "TEMPFILE", av_default_item_name, NULL, LIBAVUTIL_VERSION_INT,
    0x42, 0x42
}
Definition at line 101 of file file_open.c.
Referenced by avpriv_tempfile().