FFmpeg: libavcodec/audioconvert.h File Reference
audioconvert.h File Reference
Audio format conversion routines This interface is deprecated and will be dropped in a future version.
#include "version.h"
#include "libavutil/cpu.h"
#include "avcodec.h"
#include "libavutil/channel_layout.h"
Functions
attribute_deprecated AVAudioConvert * av_audio_convert_alloc (enum AVSampleFormat out_fmt, int out_channels, enum AVSampleFormat in_fmt, int in_channels, const float *matrix, int flags)
Create an audio sample format converter context.
attribute_deprecated void av_audio_convert_free (AVAudioConvert *ctx)
Free audio sample format converter context.
attribute_deprecated int av_audio_convert (AVAudioConvert *ctx, void *const out[6], const int out_stride[6], const void *const in[6], const int in_stride[6], int len)
Convert between audio sample formats.
Detailed Description
Audio format conversion routines This interface is deprecated and will be dropped in a future version.
You should use the libswresample library instead.
Definition in file audioconvert.h.
Function Documentation
av_audio_convert_alloc()
attribute_deprecated AVAudioConvert* av_audio_convert_alloc (enum AVSampleFormat out_fmt, int out_channels, enum AVSampleFormat in_fmt, int in_channels, const float * matrix, int flags)
Create an audio sample format converter context.
Parameters
out_fmt Output sample format
out_channels Number of output channels
in_fmt Input sample format
in_channels Number of input channels
[in] matrix Channel mixing matrix (of dimension in_channel*out_channels). Set to NULL to ignore.
flags See AV_CPU_FLAG_xx
Returns
NULL on error
Deprecated:
See libswresample
Definition at line 42 of file audioconvert.c.
Referenced by av_audio_resample_init().
av_audio_convert_free()
attribute_deprecated void av_audio_convert_free (AVAudioConvert * ctx)
Free audio sample format converter context.
Deprecated:
See libswresample
Definition at line 58 of file audioconvert.c.
Referenced by audio_resample_close(), and av_audio_resample_init().
av_audio_convert()
attribute_deprecated int av_audio_convert (AVAudioConvert * ctx, void *const out[6], const int out_stride[6], const void *const in[6], const int in_stride[6], int len)
Convert between audio sample formats.
Parameters
[in] out array of output buffers for each channel. set to NULL to ignore processing of the given channel.
[in] out_stride distance between consecutive output samples (measured in bytes)
[in] in array of input buffers for each channel
[in] in_stride distance between consecutive input samples (measured in bytes)
len length of audio frame size (measured in samples)
Deprecated:
See libswresample
Definition at line 63 of file audioconvert.c.
Referenced by audio_resample().