FFmpeg: libavformat/dv.c File Reference
dv.c File Reference
#include <time.h>
#include "avformat.h"
#include "internal.h"
#include "libavcodec/dv_profile.h"
#include "libavcodec/dv.h"
#include "libavutil/channel_layout.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/mathematics.h"
#include "libavutil/timecode.h"
#include "dv.h"
#include "libavutil/avassert.h"
Data Structures
struct DVDemuxContext
struct RawDVContext
Functions
static uint16_t dv_audio_12to16 (uint16_t sample)
static const uint8_t * dv_extract_pack (const uint8_t *frame, enum dv_pack_type t)
static int dv_extract_audio (const uint8_t *frame, uint8_t **ppcm, const AVDVProfile *sys)
static int dv_extract_audio_info (DVDemuxContext *c, const uint8_t *frame)
static int dv_extract_video_info (DVDemuxContext *c, const uint8_t *frame)
static int dv_extract_timecode (DVDemuxContext *c, const uint8_t *frame, char *tc)
DVDemuxContext * avpriv_dv_init_demux (AVFormatContext *s)
int avpriv_dv_get_packet (DVDemuxContext *c, AVPacket *pkt)
int avpriv_dv_produce_packet (DVDemuxContext *c, AVPacket *pkt, uint8_t *buf, int buf_size, int64_t pos)
static int64_t dv_frame_offset (AVFormatContext *s, DVDemuxContext *c, int64_t timestamp, int flags)
void ff_dv_offset_reset (DVDemuxContext *c, int64_t frame_offset)
static int dv_read_timecode (AVFormatContext *s)
static int dv_read_header (AVFormatContext *s)
static int dv_read_packet (AVFormatContext *s, AVPacket *pkt)
static int dv_read_seek (AVFormatContext *s, int stream_index, int64_t timestamp, int flags)
static int dv_read_close (AVFormatContext *s)
static int dv_probe (AVProbeData *p)
Variables
static const int dv_audio_frequency [3]
AVInputFormat ff_dv_demuxer
Function Documentation
dv_audio_12to16()
static uint16_t dv_audio_12to16 (uint16_t sample) inline static
Definition at line 55 of file dv.c.
Referenced by dv_extract_audio().
dv_extract_pack()
static const uint8_t* dv_extract_pack (const uint8_t * frame, enum dv_pack_type t) static
Definition at line 75 of file dv.c.
Referenced by dv_extract_audio(), dv_extract_audio_info(), dv_extract_timecode(), and dv_extract_video_info().
dv_extract_audio()
static int dv_extract_audio (const uint8_t * frame, uint8_t ** ppcm, const AVDVProfile * sys) static
Definition at line 119 of file dv.c.
Referenced by avpriv_dv_produce_packet().
dv_extract_audio_info()
static int dv_extract_audio_info (DVDemuxContext * c, const uint8_t * frame) static
Definition at line 222 of file dv.c.
Referenced by avpriv_dv_produce_packet().
dv_extract_video_info()
static int dv_extract_video_info (DVDemuxContext * c, const uint8_t * frame) static
Definition at line 282 of file dv.c.
Referenced by avpriv_dv_produce_packet().
dv_extract_timecode()
static int dv_extract_timecode (DVDemuxContext * c, const uint8_t * frame, char * tc) static
Definition at line 306 of file dv.c.
Referenced by dv_read_timecode().
avpriv_dv_init_demux()
DVDemuxContext* avpriv_dv_init_demux (AVFormatContext * s)
Definition at line 324 of file dv.c.
Referenced by avi_read_header(), dv1394_read_header(), dv_read_header(), iec61883_read_header(), and mov_finalize_stsd_codec().
avpriv_dv_get_packet()
int avpriv_dv_get_packet (DVDemuxContext * c, AVPacket * pkt)
Definition at line 347 of file dv.c.
Referenced by avi_read_packet(), dv1394_read_packet(), dv_read_packet(), iec61883_parse_queue_dv(), and mov_read_packet().
avpriv_dv_produce_packet()
int avpriv_dv_produce_packet (DVDemuxContext * c, AVPacket * pkt, uint8_t * buf, int buf_size, int64_t pos)
Definition at line 364 of file dv.c.
Referenced by avi_read_packet(), dv1394_read_packet(), dv_read_packet(), iec61883_parse_queue_dv(), and mov_read_packet().
dv_frame_offset()
static int64_t dv_frame_offset (AVFormatContext * s, DVDemuxContext * c, int64_t timestamp, int flags) static
Definition at line 417 of file dv.c.
Referenced by dv_read_seek().
ff_dv_offset_reset()
void ff_dv_offset_reset (DVDemuxContext * c, int64_t frame_offset)
Definition at line 436 of file dv.c.
Referenced by avi_read_seek(), and dv_read_seek().
dv_read_timecode()
static int dv_read_timecode (AVFormatContext * s) static
Definition at line 459 of file dv.c.
Referenced by dv_read_header().
dv_read_header()
static int dv_read_header (AVFormatContext * s) static
Definition at line 494 of file dv.c.
dv_read_packet()
static int dv_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 543 of file dv.c.
dv_read_seek()
static int dv_read_seek (AVFormatContext * s, int stream_index, int64_t timestamp, int flags) static
Definition at line 569 of file dv.c.
dv_read_close()
static int dv_read_close (AVFormatContext * s) static
Definition at line 583 of file dv.c.
dv_probe()
static int dv_probe (AVProbeData * p) static
Definition at line 590 of file dv.c.
Variable Documentation
dv_audio_frequency
const int dv_audio_frequency[3] static
Initial value:
= {
    48000, 44100, 32000,
}
Definition at line 107 of file dv.c.
Referenced by dv_extract_audio(), and dv_extract_audio_info().
ff_dv_demuxer
AVInputFormat ff_dv_demuxer
Initial value:
= {
    .name           = "dv",
    .long_name      = NULL_IF_CONFIG_SMALL("DV (Digital Video)"),
    .priv_data_size = sizeof(RawDVContext),
    .read_probe     = dv_probe,
    .read_header    = dv_read_header,
    .read_packet    = dv_read_packet,
    .read_close     = dv_read_close,
    .read_seek      = dv_read_seek,
    .extensions     = "dv,dif",
}
Definition at line 632 of file dv.c.