FFmpeg: libavresample/aarch64/audio_convert_init.c File Reference
audio_convert_init.c File Reference
#include <stdint.h>
#include "config.h"
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/aarch64/cpu.h"
#include "libavutil/samplefmt.h"
#include "libavresample/audio_convert.h"
Functions
void ff_conv_flt_to_s16_neon (int16_t *dst, const float *src, int len)
void ff_conv_fltp_to_s16_neon (int16_t *dst, float *const *src, int len, int channels)
void ff_conv_fltp_to_s16_2ch_neon (int16_t *dst, float *const *src, int len, int channels)
av_cold void ff_audio_convert_init_aarch64 (AudioConvert *ac)
Function Documentation
ff_conv_flt_to_s16_neon()
void ff_conv_flt_to_s16_neon (int16_t * dst, const float * src, int len)
Referenced by ff_audio_convert_init_aarch64(), and ff_audio_convert_init_arm().
ff_conv_fltp_to_s16_neon()
void ff_conv_fltp_to_s16_neon (int16_t * dst, float *const * src, int len, int channels)
Referenced by ff_audio_convert_init_aarch64(), and ff_audio_convert_init_arm().
ff_conv_fltp_to_s16_2ch_neon()
void ff_conv_fltp_to_s16_2ch_neon (int16_t * dst, float *const * src, int len, int channels)
Referenced by ff_audio_convert_init_aarch64(), and ff_audio_convert_init_arm().
ff_audio_convert_init_aarch64()
av_cold void ff_audio_convert_init_aarch64 (AudioConvert * ac)
Definition at line 34 of file audio_convert_init.c.