FFmpeg: libavfilter/internal.h File Reference
internal.h File Reference
internal API functions
#include "libavutil/internal.h"
#include "avfilter.h"
#include "avfiltergraph.h"
#include "formats.h"
#include "framepool.h"
#include "framequeue.h"
#include "thread.h"
#include "version.h"
#include "video.h"
#include "libavcodec/avcodec.h"
Data Structures
struct AVFilterCommand
struct AVFilterPad
A filter pad used for either input or output.
struct AVFilterGraphInternal
struct AVFilterInternal
Macros
#define ff_tlog(pctx, ...) do { if (0) av_log(pctx, AV_LOG_DEBUG, __VA_ARGS__); } while (0)
#define FF_TPRINTF_START(ctx, func) ff_tlog(NULL, "%-16s: ", #func)
#define AVFILTER_DEFINE_CLASS(fname)
#define FF_INLINK_IDX(link) ((int)((link)->dstpad - (link)->dst->input_pads))
Find the index of a link.
#define FF_OUTLINK_IDX(link) ((int)((link)->srcpad - (link)->src->output_pads))
Functions
void ff_avfilter_graph_update_heap (AVFilterGraph *graph, AVFilterLink *link)
Update the position of a link in the age heap.
int ff_fmt_is_in (int fmt, const int *fmts)
Tell if an integer is contained in the provided -1-terminated list of integers.
av_warn_unused_result int ff_parse_pixel_format (enum AVPixelFormat *ret, const char *arg, void *log_ctx)
Parse a pixel format.
av_warn_unused_result int ff_parse_sample_rate (int *ret, const char *arg, void *log_ctx)
Parse a sample rate.
av_warn_unused_result int ff_parse_time_base (AVRational *ret, const char *arg, void *log_ctx)
Parse a time base.
av_warn_unused_result int ff_parse_sample_format (int *ret, const char *arg, void *log_ctx)
Parse a sample format name or a corresponding integer representation.
av_warn_unused_result int ff_parse_channel_layout (int64_t *ret, int *nret, const char *arg, void *log_ctx)
Parse a channel layout or a corresponding integer representation.
void ff_update_link_current_pts (AVFilterLink *link, int64_t pts)
void ff_avfilter_link_set_in_status (AVFilterLink *link, int status, int64_t pts)
Set the status field of a link from the source filter.
void ff_avfilter_link_set_out_status (AVFilterLink *link, int status, int64_t pts)
Set the status field of a link from the destination filter.
void ff_command_queue_pop (AVFilterContext *filter)
char * ff_get_ref_perms_string (char *buf, size_t buf_size, int perms)
void ff_tlog_ref (void *ctx, AVFrame *ref, int end)
void ff_tlog_link (void *ctx, AVFilterLink *link, int end)
int ff_insert_pad (unsigned idx, unsigned *count, size_t padidx_off, AVFilterPad **pads, AVFilterLink ***links, AVFilterPad *newpad)
Insert a new pad.
static int ff_insert_inpad (AVFilterContext *f, unsigned index, AVFilterPad *p)
Insert a new input pad for the filter.
static int ff_insert_outpad (AVFilterContext *f, unsigned index, AVFilterPad *p)
Insert a new output pad for the filter.
int ff_poll_frame (AVFilterLink *link)
Poll a frame from the filter chain.
int ff_request_frame (AVFilterLink *link)
Request an input frame from the filter at the other end of the link.
int ff_request_frame_to_filter (AVFilterLink *link)
int ff_filter_frame_to_filter (AVFilterLink *link)
int ff_filter_frame (AVFilterLink *link, AVFrame *frame)
Send a frame of data to the next filter.
AVFilterContext * ff_filter_alloc (const AVFilter *filter, const char *inst_name)
Allocate a new filter context and return it.
int ff_filter_activate (AVFilterContext *filter)
void ff_filter_graph_remove_filter (AVFilterGraph *graph, AVFilterContext *filter)
Remove a filter from a graph;.
int ff_filter_graph_run_once (AVFilterGraph *graph)
Run one round of processing on a filter graph.
static int ff_norm_qscale (int qscale, int type)
Normalize the qscale factor FIXME the H264 qscale is a log based scale, mpeg1/2 is not, the code below cannot be optimal.
int ff_filter_get_nb_threads (AVFilterContext *ctx)
Get number of threads for current filter instance.
Detailed Description
internal API functions
Definition in file internal.h.
Macro Definition Documentation
ff_tlog
#define ff_tlog (pctx, ...) do { if (0) av_log(pctx, AV_LOG_DEBUG, __VA_ARGS__); } while (0)
Definition at line 255 of file internal.h.
FF_TPRINTF_START
#define FF_TPRINTF_START (ctx, func) ff_tlog(NULL, "%-16s: ", #func)
Definition at line 258 of file internal.h.
Referenced by ff_filter_frame(), ff_get_video_buffer(), ff_request_frame(), and ff_request_frame_to_filter().
AVFILTER_DEFINE_CLASS
#define AVFILTER_DEFINE_CLASS (fname)
Value:
static const AVClass fname##_class = {      \
        .class_name = #fname,                   \
        .item_name  = av_default_item_name,     \
        .option     = fname##_options,          \
        .version    = LIBAVUTIL_VERSION_INT,    \
        .category   = AV_CLASS_CATEGORY_FILTER, \
    }
Definition at line 343 of file internal.h.
Referenced by config_output(), filter_frame(), gate(), get_aspect_ratio(), process_command(), query_formats(), request_frame(), and uninit().
FF_INLINK_IDX
#define FF_INLINK_IDX (link) ((int)((link)->dstpad - (link)->dst->input_pads))
Find the index of a link.
I.e. find i such that link == ctx->(in|out)puts[i]
Definition at line 357 of file internal.h.
Referenced by ff_framesync_filter_frame(), filter_frame(), get_audio_buffer(), get_video_buffer(), and process_frame().
FF_OUTLINK_IDX
#define FF_OUTLINK_IDX (link) ((int)((link)->srcpad - (link)->src->output_pads))
Definition at line 358 of file internal.h.
Referenced by config_output(), movie_config_output_props(), movie_request_frame(), and request_frame().
Function Documentation
ff_avfilter_graph_update_heap()
void ff_avfilter_graph_update_heap (AVFilterGraph * graph, AVFilterLink * link)
Update the position of a link in the age heap.
Definition at line 1378 of file avfiltergraph.c.
Referenced by ff_update_link_current_pts().
ff_fmt_is_in()
int ff_fmt_is_in (int fmt, const int * fmts)
Tell if an integer is contained in the provided -1-terminated list of integers.
This is useful for determining (for instance) if an AVPixelFormat is in an array of supported formats.
Parameters
fmt provided format
fmts -1-terminated list of formats
Returns
1 if present, 0 if absent
Definition at line 254 of file formats.c.
Referenced by config_input(), config_input_main(), config_input_overlay(), config_out_props(), and config_props().
ff_parse_pixel_format()
av_warn_unused_result int ff_parse_pixel_format (enum AVPixelFormat * ret, const char * arg, void * log_ctx)
Parse a pixel format.
Parameters
ret pixel format pointer to where the value should be written
arg string to parse
log_ctx log context
Returns
>= 0 in case of success, a negative AVERROR code on error
Definition at line 609 of file formats.c.
Referenced by init().
ff_parse_sample_rate()
av_warn_unused_result int ff_parse_sample_rate (int * ret, const char * arg, void * log_ctx)
Parse a sample rate.
Parameters
ret unsigned integer pointer to where the value should be written
arg string to parse
log_ctx log context
Returns
>= 0 in case of success, a negative AVERROR code on error
Definition at line 650 of file formats.c.
Referenced by init().
ff_parse_time_base()
av_warn_unused_result int ff_parse_time_base (AVRational * ret, const char * arg, void * log_ctx)
Parse a time base.
Parameters
ret unsigned AVRational pointer to where the value should be written
arg string to parse
log_ctx log context
Returns
>= 0 in case of success, a negative AVERROR code on error
Definition at line 639 of file formats.c.
ff_parse_sample_format()
av_warn_unused_result int ff_parse_sample_format (int * ret, const char * arg, void * log_ctx)
Parse a sample format name or a corresponding integer representation.
Parameters
ret integer pointer to where the value should be written
arg string to parse
log_ctx log context
Returns
>= 0 in case of success, a negative AVERROR code on error
Definition at line 624 of file formats.c.
ff_parse_channel_layout()
av_warn_unused_result int ff_parse_channel_layout (int64_t * ret, int * nret, const char * arg, void * log_ctx)
Parse a channel layout or a corresponding integer representation.
Parameters
ret 64bit integer pointer to where the value should be written.
nret integer pointer to the number of channels; if not NULL, then unknown channel layouts are accepted
arg string to parse
log_ctx log context
Returns
>= 0 in case of success, a negative AVERROR code on error
Definition at line 662 of file formats.c.
Referenced by init(), and main().
ff_update_link_current_pts()
void ff_update_link_current_pts (AVFilterLink * link, int64_t pts)
Definition at line 528 of file avfilter.c.
Referenced by ff_avfilter_link_set_out_status(), and ff_filter_frame_framed().
ff_avfilter_link_set_in_status()
void ff_avfilter_link_set_in_status (AVFilterLink * link, int status, int64_t pts)
Set the status field of a link from the source filter.
The pts should reflect the timestamp of the status change, in link time base and relative to the frames timeline. In particular, for AVERROR_EOF, it should reflect the end time of the last frame.
Definition at line 210 of file avfilter.c.
Referenced by av_buffersrc_add_frame_internal(), and ff_request_frame_to_filter().
ff_avfilter_link_set_out_status()
void ff_avfilter_link_set_out_status (AVFilterLink * link, int status, int64_t pts)
Set the status field of a link from the destination filter.
The pts should probably be left unset (AV_NOPTS_VALUE).
Definition at line 223 of file avfilter.c.
Referenced by avfilter_link_set_closed(), ff_filter_frame_to_filter(), ff_request_frame(), and forward_status_change().
ff_command_queue_pop()
void ff_command_queue_pop (AVFilterContext * filter)
Definition at line 95 of file avfilter.c.
Referenced by avfilter_free(), and ff_filter_frame_framed().
ff_get_ref_perms_string()
char* ff_get_ref_perms_string (char * buf, size_t buf_size, int perms)
ff_tlog_ref()
void ff_tlog_ref (void * ctx, AVFrame * ref, int end)
Definition at line 50 of file avfilter.c.
Referenced by ff_filter_frame().
ff_tlog_link()
void ff_tlog_link (void * ctx, AVFilterLink * link, int end)
Definition at line 384 of file avfilter.c.
Referenced by ff_filter_frame(), ff_get_video_buffer(), ff_request_frame(), and ff_request_frame_to_filter().
ff_insert_pad()
int ff_insert_pad (unsigned idx, unsigned * count, size_t padidx_off, AVFilterPad ** pads, AVFilterLink *** links, AVFilterPad * newpad)
Insert a new pad.
Parameters
idx Insertion point. Pad is inserted at the end if this point is beyond the end of the list of pads.
count Pointer to the number of pads in the list
padidx_off Offset within an AVFilterLink structure to the element to increment when inserting a new pad causes link numbering to change
pads Pointer to the pointer to the beginning of the list of pads
links Pointer to the pointer to the beginning of the list of links
newpad The new pad to add. A copy is made when adding.
Returns
>= 0 in case of success, a negative AVERROR code on error
Definition at line 104 of file avfilter.c.
Referenced by ff_insert_inpad(), and ff_insert_outpad().
ff_insert_inpad()
static int ff_insert_inpad (AVFilterContext * f, unsigned index, AVFilterPad * p) inline static
Insert a new input pad for the filter.
Definition at line 285 of file internal.h.
Referenced by decimate_init(), fieldmatch_init(), init(), join_init(), and parse_definition().
ff_insert_outpad()
static int ff_insert_outpad (AVFilterContext * f, unsigned index, AVFilterPad * p) inline static
Insert a new output pad for the filter.
Definition at line 293 of file internal.h.
Referenced by init(), movie_common_init(), parse_definition(), and split_init().
ff_poll_frame()
int ff_poll_frame (AVFilterLink * link)
Poll a frame from the filter chain.
Parameters
link the input link
Returns
the number of immediately available frames, a negative number in case of error
Definition at line 452 of file avfilter.c.
Referenced by ff_insert_outpad(), and ff_poll_frame().
ff_request_frame()
int ff_request_frame (AVFilterLink * link)
Request an input frame from the filter at the other end of the link.
The input filter may pass the request on to its inputs, fulfill the request from an internal buffer or any other means specific to its function.
When the end of a stream is reached AVERROR_EOF is returned and no further frames are returned after that.
When a filter is unable to output a frame for example due to its sources being unable to do so or because it depends on external means pushing data into it then AVERROR(EAGAIN) is returned. It is important that a AVERROR(EAGAIN) return is returned all the way to the caller (generally eventually a user application) as this step may (but does not have to be) necessary to provide the input with the next frame.
If a request is successful then some progress has been made towards providing a frame on the link (through ff_filter_frame()). A filter that needs several frames to produce one is allowed to return success if one more frame has been processed but no output has been produced yet. A filter is also allowed to simply forward a success return value.
Parameters
link the input link
Returns
zero on success AVERROR_EOF on end of file AVERROR(EAGAIN) if the previous filter cannot output a frame currently and can neither guarantee that EOF has been reached.
Definition at line 408 of file avfilter.c.
Referenced by av_buffersink_get_frame_flags(), avfilter_graph_request_oldest(), compressor(), config_output(), ff_framesync_request_frame(), ff_insert_outpad(), ff_request_frame_to_filter(), filter_frame(), gate(), join_request_frame(), plot_spectrum_column(), request_frame(), request_frame_ref(), request_inlink(), request_samples(), and return_audio_frame().
ff_request_frame_to_filter()
int ff_request_frame_to_filter (AVFilterLink * link)
Definition at line 432 of file avfilter.c.
Referenced by ff_filter_activate_default(), ff_insert_outpad(), and forward_status_change().
ff_filter_frame_to_filter()
int ff_filter_frame_to_filter (AVFilterLink * link)
Definition at line 1311 of file avfilter.c.
Referenced by ff_filter_activate_default(), and ff_insert_outpad().
ff_filter_frame()
int ff_filter_frame (AVFilterLink * link, AVFrame * frame)
Send a frame of data to the next filter.
Parameters
link the output link over which the data is being sent
frame a reference to the buffer of data being sent. The receiving filter will free this reference when it no longer needs it or pass it on to the next filter.
Returns
>= 0 on success, a negative AVERROR on error. The receiving filter is responsible for unreferencing frame in case of error.
Definition at line 1187 of file avfilter.c.
Referenced by apply_filter(), channelmap_filter_frame(), compand_delay(), compand_drain(), compand_nodelay(), compressor(), config_output(), cudaupload_filter_frame(), default_filter_frame(), end_last_frame(), filter(), filter_frame(), filter_frame16(), filter_frame8(), filter_frame_ref(), flush(), gate(), geq_filter_frame(), hwdownload_filter_frame(), hwupload_filter_frame(), movie_push_frame(), nppscale_filter_frame(), output_frame(), output_single_frame(), plot_freqs(), plot_spectrum_column(), pp_filter_frame(), process_frame(), process_work_frame(), push_frame(), push_samples(), request_frame(), return_audio_frame(), return_frame(), scale_vaapi_filter_frame(), send_silence(), shuffleplanes_filter_frame(), source_request_frame(), and try_push_frame().
ff_filter_alloc()
AVFilterContext* ff_filter_alloc (const AVFilter * filter, const char * inst_name)
Allocate a new filter context and return it.
Parameters
filter what filter to create an instance of
inst_name name to give to the new filter context
Returns
newly created filter context or NULL on failure
Definition at line 694 of file avfilter.c.
Referenced by avfilter_graph_alloc_filter(), and avfilter_open().
ff_filter_activate()
int ff_filter_activate (AVFilterContext * filter)
Definition at line 1535 of file avfilter.c.
Referenced by ff_filter_graph_run_once().
ff_filter_graph_remove_filter()
void ff_filter_graph_remove_filter (AVFilterGraph * graph, AVFilterContext * filter)
Remove a filter from a graph;.
Definition at line 98 of file avfiltergraph.c.
Referenced by avfilter_free().
ff_filter_graph_run_once()
int ff_filter_graph_run_once (AVFilterGraph * graph)
Run one round of processing on a filter graph.
Definition at line 1420 of file avfiltergraph.c.
Referenced by av_buffersink_get_frame_flags(), avfilter_graph_request_oldest(), and push_frame().
ff_norm_qscale()
static int ff_norm_qscale (int qscale, int type) inline static
Normalize the qscale factor FIXME the H264 qscale is a log based scale, mpeg1/2 is not, the code below cannot be optimal.
Definition at line 400 of file internal.h.
Referenced by filter(), and filter_frame().
ff_filter_get_nb_threads()
int ff_filter_get_nb_threads (AVFilterContext * ctx)
Get number of threads for current filter instance.
This number is always same or less than graph->nb_threads.
Definition at line 833 of file avfilter.c.
Referenced by apply_lut(), averageiir2d(), blend_frame(), config_input(), config_props(), ff_norm_qscale(), filter(), filter_frame(), filter_frame16(), filter_frame8(), gaussianiir2d(), and nlmeans_plane().