FFmpeg: libavcodec/aacdec.c File Reference
aacdec.c File Reference
AAC decoder.
#include "libavutil/float_dsp.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "internal.h"
#include "get_bits.h"
#include "fft.h"
#include "imdct15.h"
#include "lpc.h"
#include "kbdwin.h"
#include "sinewin.h"
#include "aac.h"
#include "aactab.h"
#include "aacdectab.h"
#include "cbrt_data.h"
#include "sbr.h"
#include "aacsbr.h"
#include "mpeg4audio.h"
#include "aacadtsdec.h"
#include "profiles.h"
#include "libavutil/intfloat.h"
#include <errno.h>
#include <math.h>
#include <stdint.h>
#include <string.h>
#include "aacdec_template.c"
Data Structures
struct LATMContext
Macros
#define FFT_FLOAT 1
#define FFT_FIXED_32 0
#define USE_FIXED 0
#define LOAS_SYNC_WORD 0x2b7
11 bits LOAS sync word
Functions
static av_always_inline void reset_predict_state (PredictorState *ps)
static float * VMUL2 (float *dst, const float *v, unsigned idx, const float *scale)
static float * VMUL4 (float *dst, const float *v, unsigned idx, const float *scale)
static float * VMUL2S (float *dst, const float *v, unsigned idx, unsigned sign, const float *scale)
static float * VMUL4S (float *dst, const float *v, unsigned idx, unsigned sign, const float *scale)
static av_always_inline float flt16_round (float pf)
static av_always_inline float flt16_even (float pf)
static av_always_inline float flt16_trunc (float pf)
static av_always_inline void predict (PredictorState *ps, float *coef, int output_enable)
static void apply_dependent_coupling (AACContext *ac, SingleChannelElement *target, ChannelElement *cce, int index)
Apply dependent channel coupling (applied before IMDCT).
static void apply_independent_coupling (AACContext *ac, SingleChannelElement *target, ChannelElement *cce, int index)
Apply independent channel coupling (applied after IMDCT).
static uint32_t latm_get_value (GetBitContext *b)
static int latm_decode_audio_specific_config (struct LATMContext *latmctx, GetBitContext *gb, int asclen)
static int read_stream_mux_config (struct LATMContext *latmctx, GetBitContext *gb)
static int read_payload_length_info (struct LATMContext *ctx, GetBitContext *gb)
static int read_audio_mux_element (struct LATMContext *latmctx, GetBitContext *gb)
static int latm_decode_frame (AVCodecContext *avctx, void *out, int *got_frame_ptr, AVPacket *avpkt)
static av_cold int latm_decode_init (AVCodecContext *avctx)
Variables
AVCodec ff_aac_decoder
AVCodec ff_aac_latm_decoder
Detailed Description
AAC decoder.
Author
Oded Shimon (ods15 ods15 dyndns org)
Maxim Gavrilov (maxim.gavrilov gmail com)
Definition in file aacdec.c.
Macro Definition Documentation
FFT_FLOAT
#define FFT_FLOAT 1
Definition at line 35 of file aacdec.c.
FFT_FIXED_32
#define FFT_FIXED_32 0
Definition at line 36 of file aacdec.c.
USE_FIXED
#define USE_FIXED 0
Definition at line 37 of file aacdec.c.
LOAS_SYNC_WORD
#define LOAS_SYNC_WORD 0x2b7
11 bits LOAS sync word
Definition at line 262 of file aacdec.c.
Referenced by latm_decode_frame().
Function Documentation
reset_predict_state()
static av_always_inline void reset_predict_state (PredictorState * ps) static
Definition at line 72 of file aacdec.c.
Referenced by reset_all_predictors(), and reset_predictor_group().
VMUL2()
static float* VMUL2 (float * dst, const float * v, unsigned idx, const float * scale) inline static
Definition at line 83 of file aacdec.c.
Referenced by decode_spectrum_and_dequant().
VMUL4()
static float* VMUL4 (float * dst, const float * v, unsigned idx, const float * scale) inline static
Definition at line 94 of file aacdec.c.
Referenced by decode_spectrum_and_dequant().
VMUL2S()
static float* VMUL2S (float * dst, const float * v, unsigned idx, unsigned sign, const float * scale) inline static
Definition at line 107 of file aacdec.c.
Referenced by decode_spectrum_and_dequant().
VMUL4S()
static float* VMUL4S (float * dst, const float * v, unsigned idx, unsigned sign, const float * scale) inline static
Definition at line 124 of file aacdec.c.
Referenced by decode_spectrum_and_dequant().
flt16_round()
static av_always_inline float flt16_round (float pf) static
Definition at line 150 of file aacdec.c.
Referenced by predict().
flt16_even()
static av_always_inline float flt16_even (float pf) static
Definition at line 158 of file aacdec.c.
Referenced by predict().
flt16_trunc()
static av_always_inline float flt16_trunc (float pf) static
Definition at line 166 of file aacdec.c.
Referenced by predict().
predict()
static av_always_inline void predict (PredictorState * ps, float * coef, int output_enable) static
Definition at line 174 of file aacdec.c.
Referenced by apply_prediction(), decode_frame(), decode_line(), and encode_line().
apply_dependent_coupling()
static void apply_dependent_coupling (AACContext * ac, SingleChannelElement * target, ChannelElement * cce, int index) static
Apply dependent channel coupling (applied before IMDCT).
Parameters
index index into coupling gain array
Definition at line 210 of file aacdec.c.
Referenced by spectral_to_sample().
apply_independent_coupling()
static void apply_independent_coupling (AACContext * ac, SingleChannelElement * target, ChannelElement * cce, int index) static
Apply independent channel coupling (applied after IMDCT).
Parameters
index index into coupling gain array
Definition at line 246 of file aacdec.c.
Referenced by spectral_to_sample().
latm_get_value()
static uint32_t latm_get_value (GetBitContext * b) inline static
Definition at line 274 of file aacdec.c.
Referenced by read_stream_mux_config().
latm_decode_audio_specific_config()
static int latm_decode_audio_specific_config (struct LATMContext * latmctx, GetBitContext * gb, int asclen) static
Definition at line 281 of file aacdec.c.
Referenced by read_stream_mux_config().
read_stream_mux_config()
static int read_stream_mux_config (struct LATMContext * latmctx, GetBitContext * gb) static
Definition at line 340 of file aacdec.c.
Referenced by read_audio_mux_element().
read_payload_length_info()
static int read_payload_length_info (struct LATMContext * ctx, GetBitContext * gb) static
Definition at line 420 of file aacdec.c.
Referenced by read_audio_mux_element().
read_audio_mux_element()
static int read_audio_mux_element (struct LATMContext * latmctx, GetBitContext * gb) static
Definition at line 441 of file aacdec.c.
Referenced by latm_decode_frame().
latm_decode_frame()
static int latm_decode_frame (AVCodecContext * avctx, void * out, int * got_frame_ptr, AVPacket * avpkt) static
Definition at line 470 of file aacdec.c.
latm_decode_init()
static av_cold int latm_decode_init (AVCodecContext * avctx) static
Definition at line 531 of file aacdec.c.
Variable Documentation
ff_aac_decoder
AVCodec ff_aac_decoder
Initial value:
= {
    .name            = "aac",
    .long_name       = NULL_IF_CONFIG_SMALL("AAC (Advanced Audio Coding)"),
    .type            = AVMEDIA_TYPE_AUDIO,
    .id              = AV_CODEC_ID_AAC,
    .priv_data_size  = sizeof(AACContext),
    .init            = aac_decode_init,
    .close           = aac_decode_close,
    .decode          = aac_decode_frame,
    .sample_fmts     = (const enum AVSampleFormat[]) {
        AV_SAMPLE_FMT_FLTP, AV_SAMPLE_FMT_NONE
    },
    .capabilities    = AV_CODEC_CAP_CHANNEL_CONF | AV_CODEC_CAP_DR1,
    .caps_internal   = FF_CODEC_CAP_INIT_THREADSAFE,
    .channel_layouts = aac_channel_layout,
    .flush = flush,
    .priv_class      = &aac_decoder_class,
    .profiles        = NULL_IF_CONFIG_SMALL(ff_aac_profiles),
}
Definition at line 542 of file aacdec.c.
ff_aac_latm_decoder
AVCodec ff_aac_latm_decoder
Initial value:
= {
    .name            = "aac_latm",
    .long_name       = NULL_IF_CONFIG_SMALL("AAC LATM (Advanced Audio Coding LATM syntax)"),
    .type            = AVMEDIA_TYPE_AUDIO,
    .id              = AV_CODEC_ID_AAC_LATM,
    .priv_data_size  = sizeof(struct LATMContext),
    .init            = latm_decode_init,
    .close           = aac_decode_close,
    .decode          = latm_decode_frame,
    .sample_fmts     = (const enum AVSampleFormat[]) {
        AV_SAMPLE_FMT_FLTP, AV_SAMPLE_FMT_NONE
    },
    .capabilities    = AV_CODEC_CAP_CHANNEL_CONF | AV_CODEC_CAP_DR1,
    .caps_internal   = FF_CODEC_CAP_INIT_THREADSAFE,
    .channel_layouts = aac_channel_layout,
    .flush = flush,
    .profiles        = NULL_IF_CONFIG_SMALL(ff_aac_profiles),
}
Definition at line 567 of file aacdec.c.