FFmpeg: libavformat/jacosubdec.c File Reference
jacosubdec.c File Reference
JACOsub subtitle demuxer.
#include "avformat.h"
#include "internal.h"
#include "subtitles.h"
#include "libavcodec/internal.h"
#include "libavcodec/jacosub.h"
#include "libavutil/avstring.h"
#include "libavutil/bprint.h"
#include "libavutil/intreadwrite.h"
Data Structures
struct JACOsubContext
Macros
#define SSEP "%*1[.:]"
Functions
static int timed_line (const char *ptr)
static int jacosub_probe (AVProbeData *p)
static int get_jss_cmd (char k)
static int jacosub_read_close (AVFormatContext *s)
static const char * read_ts (JACOsubContext *jacosub, const char *buf, int64_t *start, int64_t *duration)
static int get_shift (int timeres, const char *buf)
static int jacosub_read_header (AVFormatContext *s)
static int jacosub_read_packet (AVFormatContext *s, AVPacket *pkt)
static int jacosub_read_seek (AVFormatContext *s, int stream_index, int64_t min_ts, int64_t ts, int64_t max_ts, int flags)
Variables
static const char *const cmds []
AVInputFormat ff_jacosub_demuxer
Detailed Description
JACOsub subtitle demuxer.
See also
http://unicorn.us.com/jacosub/jscripts.html
Todo:
Support P[ALETTE] directive.
Definition in file jacosubdec.c.
Macro Definition Documentation
SSEP
#define SSEP "%*1[.:]"
Referenced by get_shift().
Function Documentation
timed_line()
static int timed_line (const char * ptr) static
Definition at line 43 of file jacosubdec.c.
Referenced by jacosub_probe(), and jacosub_read_header().
jacosub_probe()
static int jacosub_probe (AVProbeData * p) static
Definition at line 51 of file jacosubdec.c.
get_jss_cmd()
static int get_jss_cmd (char k) static
Definition at line 85 of file jacosubdec.c.
Referenced by jacosub_read_header().
jacosub_read_close()
static int jacosub_read_close (AVFormatContext * s) static
Definition at line 96 of file jacosubdec.c.
Referenced by jacosub_read_header().
read_ts()
static const char* read_ts (JACOsubContext * jacosub, const char * buf, int64_t * start, int64_t * duration) static
Definition at line 103 of file jacosubdec.c.
Referenced by jacosub_read_header().
get_shift()
static int get_shift (int timeres, const char * buf) static
Definition at line 134 of file jacosubdec.c.
Referenced by jacosub_read_header().
jacosub_read_header()
static int jacosub_read_header (AVFormatContext * s) static
Definition at line 156 of file jacosubdec.c.
jacosub_read_packet()
static int jacosub_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 251 of file jacosubdec.c.
jacosub_read_seek()
static int jacosub_read_seek (AVFormatContext * s, int stream_index, int64_t min_ts, int64_t ts, int64_t max_ts, int flags) static
Definition at line 257 of file jacosubdec.c.
Variable Documentation
cmds
const char* const cmds[] static
Initial value:
= {
    "CLOCKPAUSE",
    "DIRECTIVE",
    "FONT",
    "HRES",
    "INCLUDE",
    "PALETTE",
    "QUANTIZE",
    "RAMP",
    "SHIFT",
    "TIMERES",
}
Definition at line 72 of file jacosubdec.c.
Referenced by get_jss_cmd(), and jacosub_read_header().
ff_jacosub_demuxer
AVInputFormat ff_jacosub_demuxer
Initial value:
= {
    .name           = "jacosub",
    .long_name      = NULL_IF_CONFIG_SMALL("JACOsub subtitle format"),
    .priv_data_size = sizeof(JACOsubContext),
    .read_probe     = jacosub_probe,
    .read_header    = jacosub_read_header,
    .read_packet    = jacosub_read_packet,
    .read_seek2     = jacosub_read_seek,
    .read_close     = jacosub_read_close,
}
Definition at line 265 of file jacosubdec.c.