FFmpeg: libavcodec/dvenc.c File Reference
dvenc.c File Reference
DV encoder.
#include "config.h"
#include "libavutil/attributes.h"
#include "libavutil/internal.h"
#include "libavutil/pixdesc.h"
#include "avcodec.h"
#include "dv.h"
#include "dv_profile_internal.h"
#include "dv_tablegen.h"
#include "fdctdsp.h"
#include "internal.h"
#include "mathops.h"
#include "me_cmp.h"
#include "pixblockdsp.h"
#include "put_bits.h"
Data Structures
struct EncBlockInfo
Functions
static av_cold int dvvideo_encode_init (AVCodecContext *avctx)
static av_always_inline int dv_rl2vlc (int run, int l, int sign, uint32_t *vlc)
static av_always_inline int dv_rl2vlc_size (int run, int l)
static av_always_inline PutBitContext * dv_encode_ac (EncBlockInfo *bi, PutBitContext *pb_pool, PutBitContext *pb_end)
static av_always_inline int dv_guess_dct_mode (DVVideoContext *s, uint8_t *data, int linesize)
static av_always_inline int dv_init_enc_block (EncBlockInfo *bi, uint8_t *data, int linesize, DVVideoContext *s, int bias)
static void dv_guess_qnos (EncBlockInfo *blks, int *qnos)
static int dv_encode_video_segment (AVCodecContext *avctx, void *arg)
static int dv_write_pack (enum dv_pack_type pack_id, DVVideoContext *c, uint8_t *buf)
static int dv_write_dif_id (enum dv_section_type t, uint8_t chan_num, uint8_t seq_num, uint8_t dif_num, uint8_t *buf)
static int dv_write_ssyb_id (uint8_t syb_num, uint8_t fr, uint8_t *buf)
static void dv_format_frame (DVVideoContext *c, uint8_t *buf)
static int dvvideo_encode_frame (AVCodecContext *c, AVPacket *pkt, const AVFrame *frame, int *got_packet)
Variables
static const int vs_total_ac_bits = (100 * 4 + 68 * 2) * 5
static const int mb_area_start [5] = { 1, 6, 21, 43, 64 }
static const int dv_weight_bits = 18
static const int dv_weight_88 [64]
static const int dv_weight_248 [64]
AVCodec ff_dvvideo_encoder
Detailed Description
DV encoder.
Definition in file dvenc.c.
Function Documentation
dvvideo_encode_init()
static av_cold int dvvideo_encode_init (AVCodecContext * avctx) static
Definition at line 44 of file dvenc.c.
dv_rl2vlc()
static av_always_inline int dv_rl2vlc (int run, int l, int sign, uint32_t * vlc) static
Definition at line 134 of file dvenc.c.
Referenced by dv_encode_ac().
dv_rl2vlc_size()
static av_always_inline int dv_rl2vlc_size (int run, int l) static
Definition at line 140 of file dvenc.c.
Referenced by dv_guess_qnos(), and dv_init_enc_block().
dv_encode_ac()
static av_always_inline PutBitContext* dv_encode_ac (EncBlockInfo * bi, PutBitContext * pb_pool, PutBitContext * pb_end) static
Definition at line 160 of file dvenc.c.
Referenced by dv_encode_video_segment().
dv_guess_dct_mode()
static av_always_inline int dv_guess_dct_mode (DVVideoContext * s, uint8_t * data, int linesize) static
Definition at line 206 of file dvenc.c.
Referenced by dv_init_enc_block().
dv_init_enc_block()
static av_always_inline int dv_init_enc_block (EncBlockInfo * bi, uint8_t * data, int linesize, DVVideoContext * s, int bias) static
Definition at line 243 of file dvenc.c.
Referenced by dv_encode_video_segment().
dv_guess_qnos()
static void dv_guess_qnos (EncBlockInfo * blks, int * qnos) inline static
Definition at line 346 of file dvenc.c.
Referenced by dv_encode_video_segment().
dv_encode_video_segment()
static int dv_encode_video_segment (AVCodecContext * avctx, void * arg) static
Definition at line 418 of file dvenc.c.
Referenced by dvvideo_encode_frame().
dv_write_pack()
static int dv_write_pack (enum dv_pack_type pack_id, DVVideoContext * c, uint8_t * buf) inline static
Definition at line 557 of file dvenc.c.
Referenced by dv_format_frame().
dv_write_dif_id()
static int dv_write_dif_id (enum dv_section_type t, uint8_t chan_num, uint8_t seq_num, uint8_t dif_num, uint8_t * buf) inline static
Definition at line 634 of file dvenc.c.
Referenced by dv_format_frame().
dv_write_ssyb_id()
static int dv_write_ssyb_id (uint8_t syb_num, uint8_t fr, uint8_t * buf) inline static
Definition at line 646 of file dvenc.c.
Referenced by dv_format_frame().
dv_format_frame()
static void dv_format_frame (DVVideoContext * c, uint8_t * buf) static
Definition at line 666 of file dvenc.c.
Referenced by dvvideo_encode_frame().
dvvideo_encode_frame()
static int dvvideo_encode_frame (AVCodecContext * c, AVPacket * pkt, const AVFrame * frame, int * got_packet) static
Definition at line 716 of file dvenc.c.
Variable Documentation
vs_total_ac_bits
const int vs_total_ac_bits = (100 * 4 + 68 * 2) * 5 static
Definition at line 90 of file dvenc.c.
Referenced by dv_encode_video_segment(), and dv_guess_qnos().
mb_area_start
const int mb_area_start[5] = { 1, 6, 21, 43, 64 } static
Definition at line 91 of file dvenc.c.
Referenced by dv_guess_qnos(), and dv_init_enc_block().
dv_weight_bits
const int dv_weight_bits = 18 static
Definition at line 221 of file dvenc.c.
Referenced by dv_init_enc_block().
dv_weight_88
const int dv_weight_88[64] static
Initial value:
= {
    131072, 257107, 257107, 242189, 252167, 242189, 235923, 237536,
    237536, 235923, 229376, 231390, 223754, 231390, 229376, 222935,
    224969, 217965, 217965, 224969, 222935, 200636, 218652, 211916,
    212325, 211916, 218652, 200636, 188995, 196781, 205965, 206433,
    206433, 205965, 196781, 188995, 185364, 185364, 200636, 200704,
    200636, 185364, 185364, 174609, 180568, 195068, 195068, 180568,
    174609, 170091, 175557, 189591, 175557, 170091, 165371, 170627,
    170627, 165371, 160727, 153560, 160727, 144651, 144651, 136258,
}
Definition at line 222 of file dvenc.c.
Referenced by dv_init_enc_block().
dv_weight_248
const int dv_weight_248[64] static
Initial value:
= {
    131072, 262144, 257107, 257107, 242189, 242189, 242189, 242189,
    237536, 237536, 229376, 229376, 200636, 200636, 224973, 224973,
    223754, 223754, 235923, 235923, 229376, 229376, 217965, 217965,
    211916, 211916, 196781, 196781, 185364, 185364, 206433, 206433,
    211916, 211916, 222935, 222935, 200636, 200636, 205964, 205964,
    200704, 200704, 180568, 180568, 175557, 175557, 195068, 195068,
    185364, 185364, 188995, 188995, 174606, 174606, 175557, 175557,
    170627, 170627, 153560, 153560, 165371, 165371, 144651, 144651,
}
Definition at line 232 of file dvenc.c.
Referenced by dv_init_enc_block().
ff_dvvideo_encoder
AVCodec ff_dvvideo_encoder
Initial value:
= {
    .name           = "dvvideo",
    .long_name      = NULL_IF_CONFIG_SMALL("DV (Digital Video)"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_DVVIDEO,
    .priv_data_size = sizeof(DVVideoContext),
    .init           = dvvideo_encode_init,
    .encode2        = dvvideo_encode_frame,
    .capabilities   = AV_CODEC_CAP_SLICE_THREADS | AV_CODEC_CAP_FRAME_THREADS | AV_CODEC_CAP_INTRA_ONLY,
    .pix_fmts       = (const enum AVPixelFormat[]) {
        AV_PIX_FMT_YUV411P, AV_PIX_FMT_YUV422P,
        AV_PIX_FMT_YUV420P, AV_PIX_FMT_NONE
    },
}
Definition at line 748 of file dvenc.c.