FFmpeg: libavcodec/jvdec.c File Reference
jvdec.c File Reference
Bitmap Brothers JV video decoder.
#include "libavutil/intreadwrite.h"
#include "avcodec.h"
#include "blockdsp.h"
#include "get_bits.h"
#include "internal.h"
Data Structures
struct JvContext
Functions
static av_cold int decode_init (AVCodecContext *avctx)
static void decode2x2 (GetBitContext *gb, uint8_t *dst, int linesize)
Decode 2x2 block.
static void decode4x4 (GetBitContext *gb, uint8_t *dst, int linesize)
Decode 4x4 block.
static void decode8x8 (GetBitContext *gb, uint8_t *dst, int linesize, BlockDSPContext *bdsp)
Decode 8x8 block.
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int decode_close (AVCodecContext *avctx)
Variables
AVCodec ff_jv_decoder
Detailed Description
Bitmap Brothers JV video decoder.
Author
Peter Ross pross.nosp@m.@xvi.nosp@m.d.org
Definition in file jvdec.c.
Function Documentation
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 42 of file jvdec.c.
decode2x2()
static void decode2x2 (GetBitContext * gb, uint8_t * dst, int linesize) inline static
Decode 2x2 block.
Definition at line 65 of file jvdec.c.
Referenced by decode4x4().
decode4x4()
static void decode4x4 (GetBitContext * gb, uint8_t * dst, int linesize) inline static
Decode 4x4 block.
Definition at line 92 of file jvdec.c.
Referenced by decode8x8().
decode8x8()
static void decode8x8 (GetBitContext * gb, uint8_t * dst, int linesize, BlockDSPContext * bdsp) inline static
Decode 8x8 block.
Definition at line 122 of file jvdec.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 146 of file jvdec.c.
decode_close()
static av_cold int decode_close (AVCodecContext * avctx) static
Definition at line 216 of file jvdec.c.
Variable Documentation
ff_jv_decoder
AVCodec ff_jv_decoder
Initial value:
= {
    .name           = "jv",
    .long_name      = NULL_IF_CONFIG_SMALL("Bitmap Brothers JV video"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_JV,
    .priv_data_size = sizeof(JvContext),
    .init           = decode_init,
    .close          = decode_close,
    .decode         = decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 225 of file jvdec.c.