FFmpeg: libavformat/dvenc.c File Reference
dvenc.c File Reference
#include <time.h>
#include <stdarg.h>
#include "avformat.h"
#include "internal.h"
#include "libavcodec/dv_profile.h"
#include "libavcodec/dv.h"
#include "dv.h"
#include "libavutil/avassert.h"
#include "libavutil/fifo.h"
#include "libavutil/mathematics.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/opt.h"
#include "libavutil/timecode.h"
Data Structures
struct DVMuxContext
Macros
#define MAX_AUDIO_FRAME_SIZE 192000
Functions
static int dv_audio_frame_size (const AVDVProfile *sys, int frame, int sample_rate)
static int dv_write_pack (enum dv_pack_type pack_id, DVMuxContext *c, uint8_t *buf,...)
static void dv_inject_audio (DVMuxContext *c, int channel, uint8_t *frame_ptr)
static void dv_inject_metadata (DVMuxContext *c, uint8_t *frame)
static int dv_assemble_frame (AVFormatContext *s, DVMuxContext *c, AVStream *st, uint8_t *data, int data_size, uint8_t **frame)
static DVMuxContext * dv_init_mux (AVFormatContext *s)
static void dv_delete_mux (DVMuxContext *c)
static int dv_write_header (AVFormatContext *s)
static int dv_write_packet (struct AVFormatContext *s, AVPacket *pkt)
static int dv_write_trailer (struct AVFormatContext *s)
Variables
static const int dv_aaux_packs_dist [12][9]
AVOutputFormat ff_dv_muxer
Macro Definition Documentation
MAX_AUDIO_FRAME_SIZE
#define MAX_AUDIO_FRAME_SIZE 192000
Definition at line 45 of file dvenc.c.
Referenced by dv_assemble_frame(), and dv_init_mux().
Function Documentation
dv_audio_frame_size()
static int dv_audio_frame_size (const AVDVProfile * sys, int frame, int sample_rate) static
Definition at line 76 of file dvenc.c.
Referenced by dv_assemble_frame(), dv_inject_audio(), and dv_write_pack().
dv_write_pack()
static int dv_write_pack (enum dv_pack_type pack_id, DVMuxContext * c, uint8_t * buf, ...) static
Definition at line 90 of file dvenc.c.
Referenced by dv_inject_audio(), and dv_inject_metadata().
dv_inject_audio()
static void dv_inject_audio (DVMuxContext * c, int channel, uint8_t * frame_ptr) static
Definition at line 187 of file dvenc.c.
Referenced by dv_assemble_frame().
dv_inject_metadata()
static void dv_inject_metadata (DVMuxContext * c, uint8_t * frame) static
Definition at line 209 of file dvenc.c.
Referenced by dv_assemble_frame().
dv_assemble_frame()
static int dv_assemble_frame (AVFormatContext * s, DVMuxContext * c, AVStream * st, uint8_t * data, int data_size, uint8_t ** frame) static
Definition at line 242 of file dvenc.c.
Referenced by dv_write_packet().
dv_init_mux()
static DVMuxContext* dv_init_mux (AVFormatContext * s) static
Definition at line 303 of file dvenc.c.
Referenced by dv_write_header().
dv_delete_mux()
static void dv_delete_mux (DVMuxContext * c) static
Definition at line 385 of file dvenc.c.
Referenced by dv_write_trailer().
dv_write_header()
static int dv_write_header (AVFormatContext * s) static
Definition at line 392 of file dvenc.c.
dv_write_packet()
static int dv_write_packet (struct AVFormatContext * s, AVPacket * pkt) static
Definition at line 420 of file dvenc.c.
dv_write_trailer()
static int dv_write_trailer (struct AVFormatContext * s) static
Definition at line 439 of file dvenc.c.
Variable Documentation
dv_aaux_packs_dist
const int dv_aaux_packs_dist[12][9] static
Initial value:
= {
    { 0xff, 0xff, 0xff, 0x50, 0x51, 0x52, 0x53, 0xff, 0xff },
    { 0x50, 0x51, 0x52, 0x53, 0xff, 0xff, 0xff, 0xff, 0xff },
    { 0xff, 0xff, 0xff, 0x50, 0x51, 0x52, 0x53, 0xff, 0xff },
    { 0x50, 0x51, 0x52, 0x53, 0xff, 0xff, 0xff, 0xff, 0xff },
    { 0xff, 0xff, 0xff, 0x50, 0x51, 0x52, 0x53, 0xff, 0xff },
    { 0x50, 0x51, 0x52, 0x53, 0xff, 0xff, 0xff, 0xff, 0xff },
    { 0xff, 0xff, 0xff, 0x50, 0x51, 0x52, 0x53, 0xff, 0xff },
    { 0x50, 0x51, 0x52, 0x53, 0xff, 0xff, 0xff, 0xff, 0xff },
    { 0xff, 0xff, 0xff, 0x50, 0x51, 0x52, 0x53, 0xff, 0xff },
    { 0x50, 0x51, 0x52, 0x53, 0xff, 0xff, 0xff, 0xff, 0xff },
    { 0xff, 0xff, 0xff, 0x50, 0x51, 0x52, 0x53, 0xff, 0xff },
    { 0x50, 0x51, 0x52, 0x53, 0xff, 0xff, 0xff, 0xff, 0xff },
}
Definition at line 61 of file dvenc.c.
Referenced by dv_inject_audio().
ff_dv_muxer
AVOutputFormat ff_dv_muxer
Initial value:
= {
    .name              = "dv",
    .long_name         = NULL_IF_CONFIG_SMALL("DV (Digital Video)"),
    .extensions        = "dv",
    .priv_data_size    = sizeof(DVMuxContext),
    .audio_codec       = AV_CODEC_ID_PCM_S16LE,
    .video_codec       = AV_CODEC_ID_DVVIDEO,
    .write_header      = dv_write_header,
    .write_packet      = dv_write_packet,
    .write_trailer     = dv_write_trailer,
}
Definition at line 445 of file dvenc.c.