FFmpeg: libavcodec/mpc.c File Reference
mpc.c File Reference
Musepack decoder core MPEG Audio Layer 1/2 -like codec with frames of 1152 samples divided into 32 subbands.
#include "libavutil/attributes.h"
#include "avcodec.h"
#include "mpegaudiodsp.h"
#include "mpegaudio.h"
#include "mpc.h"
#include "mpcdata.h"
Functions
av_cold void ff_mpc_init (void)
static void mpc_synth (MPCContext *c, int16_t **out, int channels)
Process decoded Musepack data and produce PCM.
void ff_mpc_dequantize_and_synth (MPCContext *c, int maxband, int16_t **out, int channels)
Detailed Description
Musepack decoder core MPEG Audio Layer 1/2 -like codec with frames of 1152 samples divided into 32 subbands.
Definition in file mpc.c.
Function Documentation
ff_mpc_init()
av_cold void ff_mpc_init (void)
Definition at line 37 of file mpc.c.
Referenced by mpc7_decode_init(), and mpc8_decode_init().
mpc_synth()
static void mpc_synth (MPCContext * c, int16_t ** out, int channels) static
Process decoded Musepack data and produce PCM.
Definition at line 45 of file mpc.c.
Referenced by ff_mpc_dequantize_and_synth().
ff_mpc_dequantize_and_synth()
void ff_mpc_dequantize_and_synth (MPCContext * c, int maxband, int16_t ** out, int channels)
Definition at line 61 of file mpc.c.
Referenced by mpc7_decode_frame(), and mpc8_decode_frame().