FFmpeg: libavcodec/cdxl.c File Reference
cdxl.c File Reference
Commodore CDXL video decoder.
#include "libavutil/intreadwrite.h"
#include "libavutil/imgutils.h"
#include "avcodec.h"
#include "bytestream.h"
#include "get_bits.h"
#include "internal.h"
Data Structures
struct CDXLVideoContext
Macros
#define UNCHECKED_BITSTREAM_READER 1
#define BIT_PLANAR 0x00
#define CHUNKY 0x20
#define BYTE_PLANAR 0x40
#define BIT_LINE 0x80
#define BYTE_LINE 0xC0
Functions
static av_cold int cdxl_decode_init (AVCodecContext *avctx)
static void import_palette (CDXLVideoContext *c, uint32_t *new_palette)
static void bitplanar2chunky (CDXLVideoContext *c, int linesize, uint8_t *out)
static void bitline2chunky (CDXLVideoContext *c, int linesize, uint8_t *out)
static void chunky2chunky (CDXLVideoContext *c, int linesize, uint8_t *out)
static void import_format (CDXLVideoContext *c, int linesize, uint8_t *out)
static void cdxl_decode_rgb (CDXLVideoContext *c, AVFrame *frame)
static void cdxl_decode_raw (CDXLVideoContext *c, AVFrame *frame)
static void cdxl_decode_ham6 (CDXLVideoContext *c, AVFrame *frame)
static void cdxl_decode_ham8 (CDXLVideoContext *c, AVFrame *frame)
static int cdxl_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *pkt)
static av_cold int cdxl_decode_end (AVCodecContext *avctx)
Variables
AVCodec ff_cdxl_decoder
Detailed Description
Commodore CDXL video decoder.
Author
Paul B Mahol
Definition in file cdxl.c.
Macro Definition Documentation
UNCHECKED_BITSTREAM_READER
#define UNCHECKED_BITSTREAM_READER 1
Definition at line 28 of file cdxl.c.
BIT_PLANAR
#define BIT_PLANAR 0x00
Definition at line 37 of file cdxl.c.
Referenced by cdxl_decode_frame(), and import_format().
CHUNKY
#define CHUNKY 0x20
Definition at line 38 of file cdxl.c.
Referenced by cdxl_decode_frame(), and import_format().
BYTE_PLANAR
#define BYTE_PLANAR 0x40
Definition at line 39 of file cdxl.c.
BIT_LINE
#define BIT_LINE 0x80
Definition at line 40 of file cdxl.c.
Referenced by cdxl_decode_frame(), and import_format().
BYTE_LINE
#define BYTE_LINE 0xC0
Definition at line 41 of file cdxl.c.
Function Documentation
cdxl_decode_init()
static av_cold int cdxl_decode_init (AVCodecContext * avctx) static
Definition at line 56 of file cdxl.c.
import_palette()
static void import_palette (CDXLVideoContext * c, uint32_t * new_palette) static
Definition at line 66 of file cdxl.c.
Referenced by cdxl_decode_ham6(), cdxl_decode_ham8(), and cdxl_decode_rgb().
bitplanar2chunky()
static void bitplanar2chunky (CDXLVideoContext * c, int linesize, uint8_t * out) static
Definition at line 79 of file cdxl.c.
Referenced by import_format().
bitline2chunky()
static void bitline2chunky (CDXLVideoContext * c, int linesize, uint8_t * out) static
Definition at line 95 of file cdxl.c.
Referenced by import_format().
chunky2chunky()
static void chunky2chunky (CDXLVideoContext * c, int linesize, uint8_t * out) static
Definition at line 111 of file cdxl.c.
Referenced by import_format().
import_format()
static void import_format (CDXLVideoContext * c, int linesize, uint8_t * out) static
Definition at line 122 of file cdxl.c.
Referenced by cdxl_decode_ham6(), cdxl_decode_ham8(), cdxl_decode_raw(), and cdxl_decode_rgb().
cdxl_decode_rgb()
static void cdxl_decode_rgb (CDXLVideoContext * c, AVFrame * frame) static
Definition at line 139 of file cdxl.c.
Referenced by cdxl_decode_frame().
cdxl_decode_raw()
static void cdxl_decode_raw (CDXLVideoContext * c, AVFrame * frame) static
Definition at line 148 of file cdxl.c.
Referenced by cdxl_decode_frame().
cdxl_decode_ham6()
static void cdxl_decode_ham6 (CDXLVideoContext * c, AVFrame * frame) static
Definition at line 153 of file cdxl.c.
Referenced by cdxl_decode_frame().
cdxl_decode_ham8()
static void cdxl_decode_ham8 (CDXLVideoContext * c, AVFrame * frame) static
Definition at line 196 of file cdxl.c.
Referenced by cdxl_decode_frame().
cdxl_decode_frame()
static int cdxl_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * pkt) static
Definition at line 239 of file cdxl.c.
cdxl_decode_end()
static av_cold int cdxl_decode_end (AVCodecContext * avctx) static
Definition at line 318 of file cdxl.c.
Variable Documentation
ff_cdxl_decoder
AVCodec ff_cdxl_decoder
Initial value:
= {
    .name           = "cdxl",
    .long_name      = NULL_IF_CONFIG_SMALL("Commodore CDXL video"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_CDXL,
    .priv_data_size = sizeof(CDXLVideoContext),
    .init           = cdxl_decode_init,
    .close          = cdxl_decode_end,
    .decode         = cdxl_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 327 of file cdxl.c.