FFmpeg: libavcodec/flacenc.c File Reference
flacenc.c File Reference
#include "libavutil/avassert.h"
#include "libavutil/crc.h"
#include "libavutil/intmath.h"
#include "libavutil/md5.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "bswapdsp.h"
#include "put_bits.h"
#include "golomb.h"
#include "internal.h"
#include "lpc.h"
#include "flac.h"
#include "flacdata.h"
#include "flacdsp.h"
Data Structures
struct CompressionOptions
struct RiceContext
struct FlacSubframe
struct FlacFrame
struct FlacEncodeContext
Macros
#define FLAC_SUBFRAME_CONSTANT 0
#define FLAC_SUBFRAME_VERBATIM 1
#define FLAC_SUBFRAME_FIXED 8
#define FLAC_SUBFRAME_LPC 32
#define MAX_FIXED_ORDER 4
#define MAX_PARTITION_ORDER 8
#define MAX_PARTITIONS (1 << MAX_PARTITION_ORDER)
#define MAX_LPC_PRECISION 15
#define MIN_LPC_SHIFT 0
#define MAX_LPC_SHIFT 15
#define COPY_SAMPLES(bits)
#define rice_encode_count(sum, n, k) (((n)*((k)+1))+((sum-(n>>1))>>(k)))
#define FLAGS AV_OPT_FLAG_ENCODING_PARAM | AV_OPT_FLAG_AUDIO_PARAM
Enumerations
enum CodingMode { CODING_MODE_RICE = 4, CODING_MODE_RICE2 = 5 }
Functions
static void write_streaminfo (FlacEncodeContext *s, uint8_t *header)
Write streaminfo metadata block to byte array.
static int select_blocksize (int samplerate, int block_time_ms)
Set blocksize based on samplerate.
static av_cold void dprint_compression_options (FlacEncodeContext *s)
static av_cold int flac_encode_init (AVCodecContext *avctx)
static void init_frame (FlacEncodeContext *s, int nb_samples)
static void copy_samples (FlacEncodeContext *s, const void *samples)
Copy channel-interleaved input samples into separate subframes.
static uint64_t rice_count_exact (const int32_t *res, int n, int k)
static uint64_t subframe_count_exact (FlacEncodeContext *s, FlacSubframe *sub, int pred_order)
static int find_optimal_param (uint64_t sum, int n, int max_param)
Solve for d/dk(rice_encode_count) = n-((sum-(n>>1))>>(k+1)) = 0.
static int find_optimal_param_exact (uint64_t sums[32][MAX_PARTITIONS], int i, int max_param)
static uint64_t calc_optimal_rice_params (RiceContext *rc, int porder, uint64_t sums[32][MAX_PARTITIONS], int n, int pred_order, int max_param, int exact)
static void calc_sum_top (int pmax, int kmax, const uint32_t *data, int n, int pred_order, uint64_t sums[32][MAX_PARTITIONS])
static void calc_sum_next (int level, uint64_t sums[32][MAX_PARTITIONS], int kmax)
static uint64_t calc_rice_params (RiceContext *rc, uint32_t udata[FLAC_MAX_BLOCKSIZE], uint64_t sums[32][MAX_PARTITIONS], int pmin, int pmax, const int32_t *data, int n, int pred_order, int exact)
static int get_max_p_order (int max_porder, int n, int order)
static uint64_t find_subframe_rice_params (FlacEncodeContext *s, FlacSubframe *sub, int pred_order)
static void encode_residual_fixed (int32_t *res, const int32_t *smp, int n, int order)
static int encode_residual_ch (FlacEncodeContext *s, int ch)
static int count_frame_header (FlacEncodeContext *s)
static int encode_frame (FlacEncodeContext *s)
static void remove_wasted_bits (FlacEncodeContext *s)
static int estimate_stereo_mode (const int32_t *left_ch, const int32_t *right_ch, int n, int max_rice_param)
static void channel_decorrelation (FlacEncodeContext *s)
Perform stereo channel decorrelation.
static void write_utf8 (PutBitContext *pb, uint32_t val)
static void write_frame_header (FlacEncodeContext *s)
static void write_subframes (FlacEncodeContext *s)
static void write_frame_footer (FlacEncodeContext *s)
static int write_frame (FlacEncodeContext *s, AVPacket *avpkt)
static int update_md5_sum (FlacEncodeContext *s, const void *samples)
static int flac_encode_frame (AVCodecContext *avctx, AVPacket *avpkt, const AVFrame *frame, int *got_packet_ptr)
static av_cold int flac_encode_close (AVCodecContext *avctx)
Variables
static const AVOption options []
static const AVClass flac_encoder_class
AVCodec ff_flac_encoder
Macro Definition Documentation
FLAC_SUBFRAME_CONSTANT
#define FLAC_SUBFRAME_CONSTANT 0
Definition at line 38 of file flacenc.c.
Referenced by encode_residual_ch(), subframe_count_exact(), and write_subframes().
FLAC_SUBFRAME_VERBATIM
#define FLAC_SUBFRAME_VERBATIM 1
Definition at line 39 of file flacenc.c.
Referenced by encode_residual_ch(), subframe_count_exact(), and write_subframes().
FLAC_SUBFRAME_FIXED
#define FLAC_SUBFRAME_FIXED 8
Definition at line 40 of file flacenc.c.
Referenced by encode_residual_ch().
FLAC_SUBFRAME_LPC
#define FLAC_SUBFRAME_LPC 32
Definition at line 41 of file flacenc.c.
Referenced by encode_residual_ch(), find_subframe_rice_params(), subframe_count_exact(), and write_subframes().
MAX_FIXED_ORDER
#define MAX_FIXED_ORDER 4
Definition at line 43 of file flacenc.c.
Referenced by encode_residual_ch(), and flac_encode_init().
MAX_PARTITION_ORDER
#define MAX_PARTITION_ORDER 8
Definition at line 44 of file flacenc.c.
Referenced by calc_rice_params().
MAX_PARTITIONS
#define MAX_PARTITIONS (1 << MAX_PARTITION_ORDER)
Definition at line 45 of file flacenc.c.
MAX_LPC_PRECISION
#define MAX_LPC_PRECISION 15
Definition at line 46 of file flacenc.c.
MIN_LPC_SHIFT
#define MIN_LPC_SHIFT 0
Definition at line 47 of file flacenc.c.
Referenced by encode_residual_ch().
MAX_LPC_SHIFT
#define MAX_LPC_SHIFT 15
Definition at line 48 of file flacenc.c.
Referenced by encode_residual_ch().
COPY_SAMPLES
#define COPY_SAMPLES (bits)
Value:
do {                                     \
    const int ## bits ## _t *samples0 = samples;                    \
    frame = &s->frame;                                              \
    for (i = 0, j = 0; i < frame->blocksize; i++)                   \
        for (ch = 0; ch < s->channels; ch++, j++)                   \
            frame->subframes[ch].samples[i] = samples0[j] >> shift; \
} while (0)
Referenced by copy_samples().
rice_encode_count
#define rice_encode_count (sum, n, k) (((n)*((k)+1))+((sum-(n>>1))>>(k)))
Definition at line 601 of file flacenc.c.
Referenced by calc_optimal_rice_params(), and estimate_stereo_mode().
FLAGS
#define FLAGS AV_OPT_FLAG_ENCODING_PARAM | AV_OPT_FLAG_AUDIO_PARAM
Definition at line 1463 of file flacenc.c.
Enumeration Type Documentation
CodingMode
enum CodingMode
Enumerator
CODING_MODE_RICE
CODING_MODE_RICE2
Definition at line 50 of file flacenc.c.
Function Documentation
write_streaminfo()
static void write_streaminfo (FlacEncodeContext * s, uint8_t * header) static
Write streaminfo metadata block to byte array.
Definition at line 135 of file flacenc.c.
Referenced by flac_encode_frame(), and flac_encode_init().
select_blocksize()
static int select_blocksize (int samplerate, int block_time_ms) static
Set blocksize based on samplerate.
Choose the closest predefined blocksize >= BLOCK_TIME_MS milliseconds.
Definition at line 162 of file flacenc.c.
Referenced by flac_encode_init().
dprint_compression_options()
static av_cold void dprint_compression_options (FlacEncodeContext * s) static
Definition at line 181 of file flacenc.c.
Referenced by flac_encode_init().
flac_encode_init()
static av_cold int flac_encode_init (AVCodecContext * avctx) static
Definition at line 239 of file flacenc.c.
init_frame()
static void init_frame (FlacEncodeContext * s, int nb_samples) static
Definition at line 470 of file flacenc.c.
Referenced by decode_frame(), and flac_encode_frame().
copy_samples()
static void copy_samples (FlacEncodeContext * s, const void * samples) static
Copy channel-interleaved input samples into separate subframes.
Definition at line 515 of file flacenc.c.
Referenced by flac_encode_frame().
rice_count_exact()
static uint64_t rice_count_exact (const int32_t * res, int n, int k) static
Definition at line 537 of file flacenc.c.
Referenced by subframe_count_exact().
subframe_count_exact()
static uint64_t subframe_count_exact (FlacEncodeContext * s, FlacSubframe * sub, int pred_order) static
Definition at line 551 of file flacenc.c.
Referenced by encode_residual_ch().
find_optimal_param()
static int find_optimal_param (uint64_t sum, int n, int max_param) static
Solve for d/dk(rice_encode_count) = n-((sum-(n>>1))>>(k+1)) = 0.
Definition at line 606 of file flacenc.c.
Referenced by calc_optimal_rice_params(), and estimate_stereo_mode().
find_optimal_param_exact()
static int find_optimal_param_exact (uint64_t sums[32][MAX_PARTITIONS], int i, int max_param) static
Definition at line 618 of file flacenc.c.
Referenced by calc_optimal_rice_params().
calc_optimal_rice_params()
static uint64_t calc_optimal_rice_params (RiceContext * rc, int porder, uint64_t sums[32][MAX_PARTITIONS], int n, int pred_order, int max_param, int exact) static
Definition at line 635 of file flacenc.c.
Referenced by calc_rice_params().
calc_sum_top()
static void calc_sum_top (int pmax, int kmax, const uint32_t * data, int n, int pred_order, uint64_t sums[32][MAX_PARTITIONS]) static
Definition at line 665 of file flacenc.c.
Referenced by calc_rice_params().
calc_sum_next()
static void calc_sum_next (int level, uint64_t sums[32][MAX_PARTITIONS], int kmax) static
Definition at line 695 of file flacenc.c.
Referenced by calc_rice_params().
calc_rice_params()
static uint64_t calc_rice_params (RiceContext * rc, uint32_t udata[FLAC_MAX_BLOCKSIZE], uint64_t sums[32][MAX_PARTITIONS], int pmin, int pmax, const int32_t * data, int n, int pred_order, int exact) static
Definition at line 705 of file flacenc.c.
Referenced by find_subframe_rice_params().
get_max_p_order()
static int get_max_p_order (int max_porder, int n, int order) static
Definition at line 745 of file flacenc.c.
Referenced by find_subframe_rice_params().
find_subframe_rice_params()
static uint64_t find_subframe_rice_params (FlacEncodeContext * s, FlacSubframe * sub, int pred_order) static
Definition at line 754 of file flacenc.c.
Referenced by encode_residual_ch().
encode_residual_fixed()
static void encode_residual_fixed (int32_t * res, const int32_t * smp, int n, int order) static
Definition at line 771 of file flacenc.c.
Referenced by encode_residual_ch().
encode_residual_ch()
static int encode_residual_ch (FlacEncodeContext * s, int ch) static
Definition at line 822 of file flacenc.c.
Referenced by encode_frame().
count_frame_header()
static int count_frame_header (FlacEncodeContext * s) static
Definition at line 1021 of file flacenc.c.
Referenced by encode_frame().
encode_frame()
static int encode_frame (FlacEncodeContext * s) static
Definition at line 1057 of file flacenc.c.
Referenced by flac_encode_frame().
remove_wasted_bits()
static void remove_wasted_bits (FlacEncodeContext * s) static
Definition at line 1077 of file flacenc.c.
Referenced by flac_encode_frame().
estimate_stereo_mode()
static int estimate_stereo_mode (const int32_t * left_ch, const int32_t * right_ch, int n, int max_rice_param) static
Definition at line 1109 of file flacenc.c.
Referenced by channel_decorrelation().
channel_decorrelation()
static void channel_decorrelation (FlacEncodeContext * s) static
Perform stereo channel decorrelation.
Definition at line 1153 of file flacenc.c.
Referenced by flac_encode_frame().
write_utf8()
static void write_utf8 (PutBitContext * pb, uint32_t val) static
Definition at line 1198 of file flacenc.c.
Referenced by write_frame_header().
write_frame_header()
static void write_frame_header (FlacEncodeContext * s) static
Definition at line 1205 of file flacenc.c.
Referenced by write_frame().
write_subframes()
static void write_subframes (FlacEncodeContext * s) static
Definition at line 1242 of file flacenc.c.
Referenced by write_frame().
write_frame_footer()
static void write_frame_footer (FlacEncodeContext * s) static
Definition at line 1302 of file flacenc.c.
Referenced by write_frame().
write_frame()
static int write_frame (FlacEncodeContext * s, AVPacket * avpkt) static
Definition at line 1313 of file flacenc.c.
Referenced by flac_encode_frame().
update_md5_sum()
static int update_md5_sum (FlacEncodeContext * s, const void * samples) static
Definition at line 1323 of file flacenc.c.
Referenced by flac_encode_frame().
flac_encode_frame()
static int flac_encode_frame (AVCodecContext * avctx, AVPacket * avpkt, const AVFrame * frame, int * got_packet_ptr) static
Definition at line 1359 of file flacenc.c.
flac_encode_close()
static av_cold int flac_encode_close (AVCodecContext * avctx) static
Definition at line 1450 of file flacenc.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
{ "lpc_coeff_precision", "LPC coefficient precision", 0x42, AV_OPT_TYPE_INT, {.i64 = 15 }, 0, MAX_LPC_PRECISION, FLAGS },
{ "lpc_type", "LPC algorithm", 0x42, AV_OPT_TYPE_INT, {.i64 = FF_LPC_TYPE_DEFAULT }, FF_LPC_TYPE_DEFAULT, FF_LPC_TYPE_NB-1, FLAGS, "lpc_type" },
{ "none",     NULL, 0, AV_OPT_TYPE_CONST, {.i64 = FF_LPC_TYPE_NONE },     INT_MIN, INT_MAX, FLAGS, "lpc_type" },
{ "fixed",    NULL, 0, AV_OPT_TYPE_CONST, {.i64 = FF_LPC_TYPE_FIXED },    INT_MIN, INT_MAX, FLAGS, "lpc_type" },
{ "levinson", NULL, 0, AV_OPT_TYPE_CONST, {.i64 = FF_LPC_TYPE_LEVINSON }, INT_MIN, INT_MAX, FLAGS, "lpc_type" },
{ "cholesky", NULL, 0, AV_OPT_TYPE_CONST, {.i64 = FF_LPC_TYPE_CHOLESKY }, INT_MIN, INT_MAX, FLAGS, "lpc_type" },
{ "lpc_passes", "Number of passes to use for Cholesky factorization during LPC analysis", 0x42,  AV_OPT_TYPE_INT, {.i64 = 2 }, 1, INT_MAX, FLAGS },
{ "min_partition_order",  NULL, 0x42,  AV_OPT_TYPE_INT, {.i64 = -1 },      -1, MAX_PARTITION_ORDER, FLAGS },
{ "max_partition_order",  NULL, 0x42,  AV_OPT_TYPE_INT, {.i64 = -1 },      -1, MAX_PARTITION_ORDER, FLAGS },
{ "prediction_order_method", "Search method for selecting prediction order", 0x42, AV_OPT_TYPE_INT, {.i64 = -1 }, -1, ORDER_METHOD_LOG, FLAGS, "predm" },
{ "estimation", NULL, 0, AV_OPT_TYPE_CONST, {.i64 = ORDER_METHOD_EST },    INT_MIN, INT_MAX, FLAGS, "predm" },
{ "2level",     NULL, 0, AV_OPT_TYPE_CONST, {.i64 = ORDER_METHOD_2LEVEL }, INT_MIN, INT_MAX, FLAGS, "predm" },
{ "4level",     NULL, 0, AV_OPT_TYPE_CONST, {.i64 = ORDER_METHOD_4LEVEL }, INT_MIN, INT_MAX, FLAGS, "predm" },
{ "8level",     NULL, 0, AV_OPT_TYPE_CONST, {.i64 = ORDER_METHOD_8LEVEL }, INT_MIN, INT_MAX, FLAGS, "predm" },
{ "search",     NULL, 0, AV_OPT_TYPE_CONST, {.i64 = ORDER_METHOD_SEARCH }, INT_MIN, INT_MAX, FLAGS, "predm" },
{ "log",        NULL, 0, AV_OPT_TYPE_CONST, {.i64 = ORDER_METHOD_LOG },    INT_MIN, INT_MAX, FLAGS, "predm" },
{ "ch_mode", "Stereo decorrelation mode", 0x42, AV_OPT_TYPE_INT, { .i64 = -1 }, -1, FLAC_CHMODE_MID_SIDE, FLAGS, "ch_mode" },
{ "auto",       NULL, 0, AV_OPT_TYPE_CONST, { .i64 = -1                      }, INT_MIN, INT_MAX, FLAGS, "ch_mode" },
{ "indep",      NULL, 0, AV_OPT_TYPE_CONST, { .i64 = FLAC_CHMODE_INDEPENDENT }, INT_MIN, INT_MAX, FLAGS, "ch_mode" },
{ "left_side",  NULL, 0, AV_OPT_TYPE_CONST, { .i64 = FLAC_CHMODE_LEFT_SIDE   }, INT_MIN, INT_MAX, FLAGS, "ch_mode" },
{ "right_side", NULL, 0, AV_OPT_TYPE_CONST, { .i64 = FLAC_CHMODE_RIGHT_SIDE  }, INT_MIN, INT_MAX, FLAGS, "ch_mode" },
{ "mid_side",   NULL, 0, AV_OPT_TYPE_CONST, { .i64 = FLAC_CHMODE_MID_SIDE    }, INT_MIN, INT_MAX, FLAGS, "ch_mode" },
{ "exact_rice_parameters", "Calculate rice parameters exactly", 0x42, AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, FLAGS },
{ "multi_dim_quant",       "Multi-dimensional quantization",    0x42,       AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, FLAGS },
{ "min_prediction_order", NULL, 0x42, AV_OPT_TYPE_INT, { .i64 = -1 }, -1, MAX_LPC_ORDER, FLAGS },
{ "max_prediction_order", NULL, 0x42, AV_OPT_TYPE_INT, { .i64 = -1 }, -1, MAX_LPC_ORDER, FLAGS },
{ NULL },
}
Definition at line 1464 of file flacenc.c.
flac_encoder_class
const AVClass flac_encoder_class static
Initial value:
= {
    .class_name = "FLAC encoder",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1495 of file flacenc.c.
ff_flac_encoder
AVCodec ff_flac_encoder
Initial value:
= {
    .name           = "flac",
    .long_name      = NULL_IF_CONFIG_SMALL("FLAC (Free Lossless Audio Codec)"),
    .type           = AVMEDIA_TYPE_AUDIO,
    .id             = AV_CODEC_ID_FLAC,
    .priv_data_size = sizeof(FlacEncodeContext),
    .init           = flac_encode_init,
    .encode2        = flac_encode_frame,
    .close          = flac_encode_close,
    .capabilities   = AV_CODEC_CAP_SMALL_LAST_FRAME | AV_CODEC_CAP_DELAY | AV_CODEC_CAP_LOSSLESS,
    .sample_fmts    = (const enum AVSampleFormat[]){ AV_SAMPLE_FMT_S16,
                                                     AV_SAMPLE_FMT_S32,
                                                     AV_SAMPLE_FMT_NONE },
    .priv_class     = &flac_encoder_class,
}
Definition at line 1502 of file flacenc.c.