FFmpeg: libavformat/utils.c File Reference
utils.c File Reference
various utility functions for use within FFmpeg
#include <stdarg.h>
#include <stdint.h>
#include "config.h"
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/dict.h"
#include "libavutil/internal.h"
#include "libavutil/mathematics.h"
#include "libavutil/opt.h"
#include "libavutil/parseutils.h"
#include "libavutil/pixdesc.h"
#include "libavutil/time.h"
#include "libavutil/time_internal.h"
#include "libavutil/timestamp.h"
#include "libavcodec/bytestream.h"
#include "libavcodec/internal.h"
#include "libavcodec/raw.h"
#include "audiointerleave.h"
#include "avformat.h"
#include "avio_internal.h"
#include "id3v2.h"
#include "internal.h"
#include "metadata.h"
#include "riff.h"
#include "url.h"
#include "libavutil/ffversion.h"
Macros
#define LICENSE_PREFIX "libavformat license: "
#define RELATIVE_TS_BASE (INT64_MAX - (1LL<<48))
#define SANE_CHUNK_SIZE (50000000)
#define DURATION_MAX_READ_SIZE 250000LL
#define DURATION_MAX_RETRY 6
#define FAIL(errmsg)
Functions
unsigned avformat_version (void)
Return the LIBAVFORMAT_VERSION_INT constant.
const char * avformat_configuration (void)
Return the libavformat build-time configuration.
const char * avformat_license (void)
Return the libavformat license.
static int is_relative (int64_t ts)
static int64_t wrap_timestamp (const AVStream *st, int64_t timestamp)
Wrap a given time stamp, if there is an indication for an overflow.
int64_t av_stream_get_end_pts (const AVStream *st)
Returns the pts of the last muxed packet + its duration.
struct AVCodecParserContext * av_stream_get_parser (const AVStream *st)
void av_format_inject_global_side_data (AVFormatContext *s)
This function will cause global side data to be injected in the next packet of each stream as well as after any subsequent seek.
int ff_copy_whiteblacklists (AVFormatContext *dst, const AVFormatContext *src)
Copies the whilelists from one context to the other.
static const AVCodec * find_decoder (AVFormatContext *s, const AVStream *st, enum AVCodecID codec_id)
static const AVCodec * find_probe_decoder (AVFormatContext *s, const AVStream *st, enum AVCodecID codec_id)
int av_format_get_probe_score (const AVFormatContext *s)
int ffio_limit (AVIOContext *s, int size)
static int append_packet_chunked (AVIOContext *s, AVPacket *pkt, int size)
int av_get_packet (AVIOContext *s, AVPacket *pkt, int size)
Allocate and read the payload of a packet and initialize its fields with default values.
int av_append_packet (AVIOContext *s, AVPacket *pkt, int size)
Read data and append it to the current content of the AVPacket.
int av_filename_number_test (const char *filename)
Check whether filename actually is a numbered sequence generator.
static int set_codec_from_probe_data (AVFormatContext *s, AVStream *st, AVProbeData *pd)
int av_demuxer_open (AVFormatContext *ic)
static int init_input (AVFormatContext *s, const char *filename, AVDictionary **options)
static int add_to_pktbuf (AVPacketList **packet_buffer, AVPacket *pkt, AVPacketList **plast_pktl, int ref)
int avformat_queue_attached_pictures (AVFormatContext *s)
static int update_stream_avctx (AVFormatContext *s)
int avformat_open_input (AVFormatContext **ps, const char *filename, AVInputFormat *fmt, AVDictionary **options)
Open an input stream and read the header.
static void force_codec_ids (AVFormatContext *s, AVStream *st)
static int probe_codec (AVFormatContext *s, AVStream *st, const AVPacket *pkt)
static int update_wrap_reference (AVFormatContext *s, AVStream *st, int stream_index, AVPacket *pkt)
int ff_read_packet (AVFormatContext *s, AVPacket *pkt)
Read a transport packet from a media file.
static int determinable_frame_size (AVCodecContext *avctx)
void ff_compute_frame_duration (AVFormatContext *s, int *pnum, int *pden, AVStream *st, AVCodecParserContext *pc, AVPacket *pkt)
Return the frame duration in seconds.
static int is_intra_only (enum AVCodecID id)
static int has_decode_delay_been_guessed (AVStream *st)
static AVPacketList * get_next_pkt (AVFormatContext *s, AVStream *st, AVPacketList *pktl)
static int64_t select_from_pts_buffer (AVStream *st, int64_t *pts_buffer, int64_t dts)
static void update_dts_from_pts (AVFormatContext *s, int stream_index, AVPacketList *pkt_buffer)
Updates the dts of packets of a stream in pkt_buffer, by re-ordering the pts of the packets in a window.
static void update_initial_timestamps (AVFormatContext *s, int stream_index, int64_t dts, int64_t pts, AVPacket *pkt)
static void update_initial_durations (AVFormatContext *s, AVStream *st, int stream_index, int duration)
static void compute_pkt_fields (AVFormatContext *s, AVStream *st, AVCodecParserContext *pc, AVPacket *pkt, int64_t next_dts, int64_t next_pts)
static void free_packet_buffer (AVPacketList **pkt_buf, AVPacketList **pkt_buf_end)
static int parse_packet (AVFormatContext *s, AVPacket *pkt, int stream_index)
Parse a packet, add all split parts to parse_queue.
static int read_from_packet_buffer (AVPacketList **pkt_buffer, AVPacketList **pkt_buffer_end, AVPacket *pkt)
static int64_t ts_to_samples (AVStream *st, int64_t ts)
static int read_frame_internal (AVFormatContext *s, AVPacket *pkt)
int av_read_frame (AVFormatContext *s, AVPacket *pkt)
Return the next frame of a stream.
static void flush_packet_queue (AVFormatContext *s)
int av_find_default_stream_index (AVFormatContext *s)
void ff_read_frame_flush (AVFormatContext *s)
Flush the frame reader.
void ff_update_cur_dts (AVFormatContext *s, AVStream *ref_st, int64_t timestamp)
Update cur_dts of all streams based on the given timestamp and AVStream.
void ff_reduce_index (AVFormatContext *s, int stream_index)
Ensure the index uses less memory than the maximum specified in AVFormatContext.max_index_size by discarding entries if it grows too large.
int ff_add_index_entry (AVIndexEntry **index_entries, int *nb_index_entries, unsigned int *index_entries_allocated_size, int64_t pos, int64_t timestamp, int size, int distance, int flags)
Internal version of av_add_index_entry.
int av_add_index_entry (AVStream *st, int64_t pos, int64_t timestamp, int size, int distance, int flags)
Add an index entry into a sorted list.
int ff_index_search_timestamp (const AVIndexEntry *entries, int nb_entries, int64_t wanted_timestamp, int flags)
Internal version of av_index_search_timestamp.
void ff_configure_buffers_for_index (AVFormatContext *s, int64_t time_tolerance)
int av_index_search_timestamp (AVStream *st, int64_t wanted_timestamp, int flags)
Get the index for a specific timestamp.
static int64_t ff_read_timestamp (AVFormatContext *s, int stream_index, int64_t *ppos, int64_t pos_limit, int64_t(*read_timestamp)(struct AVFormatContext *, int, int64_t *, int64_t))
int ff_seek_frame_binary (AVFormatContext *s, int stream_index, int64_t target_ts, int flags)
Perform a binary search using av_index_search_timestamp() and AVInputFormat.read_timestamp().
int ff_find_last_ts (AVFormatContext *s, int stream_index, int64_t *ts, int64_t *pos, int64_t(*read_timestamp)(struct AVFormatContext *, int, int64_t *, int64_t))
int64_t ff_gen_search (AVFormatContext *s, int stream_index, int64_t target_ts, int64_t pos_min, int64_t pos_max, int64_t pos_limit, int64_t ts_min, int64_t ts_max, int flags, int64_t *ts_ret, int64_t(*read_timestamp)(struct AVFormatContext *, int, int64_t *, int64_t))
Perform a binary search using read_timestamp().
static int seek_frame_byte (AVFormatContext *s, int stream_index, int64_t pos, int flags)
static int seek_frame_generic (AVFormatContext *s, int stream_index, int64_t timestamp, int flags)
static int seek_frame_internal (AVFormatContext *s, int stream_index, int64_t timestamp, int flags)
int av_seek_frame (AVFormatContext *s, int stream_index, int64_t timestamp, int flags)
Seek to the keyframe at timestamp.
int avformat_seek_file (AVFormatContext *s, int stream_index, int64_t min_ts, int64_t ts, int64_t max_ts, int flags)
Seek to timestamp ts.
int avformat_flush (AVFormatContext *s)
Discard all internally buffered data.
static int has_duration (AVFormatContext *ic)
Return TRUE if the stream has accurate duration in any stream.
static void update_stream_timings (AVFormatContext *ic)
Estimate the stream timings from the one of each components.
static void fill_all_stream_timings (AVFormatContext *ic)
static void estimate_timings_from_bit_rate (AVFormatContext *ic)
static void estimate_timings_from_pts (AVFormatContext *ic, int64_t old_offset)
static void estimate_timings (AVFormatContext *ic, int64_t old_offset)
static int has_codec_parameters (AVStream *st, const char **errmsg_ptr)
static int try_decode_frame (AVFormatContext *s, AVStream *st, AVPacket *avpkt, AVDictionary **options)
unsigned int ff_codec_get_tag (const AVCodecTag *tags, enum AVCodecID id)
enum AVCodecID ff_codec_get_id (const AVCodecTag *tags, unsigned int tag)
enum AVCodecID ff_get_pcm_codec_id (int bps, int flt, int be, int sflags)
Select a PCM codec based on the given parameters.
unsigned int av_codec_get_tag (const AVCodecTag *const *tags, enum AVCodecID id)
int av_codec_get_tag2 (const AVCodecTag *const *tags, enum AVCodecID id, unsigned int *tag)
enum AVCodecID av_codec_get_id (const AVCodecTag *const *tags, unsigned int tag)
static void compute_chapters_end (AVFormatContext *s)
static int get_std_framerate (int i)
static int tb_unreliable (AVCodecContext *c)
int ff_alloc_extradata (AVCodecParameters *par, int size)
Allocate extradata with additional AV_INPUT_BUFFER_PADDING_SIZE at end which is always set to 0.
int ff_get_extradata (AVFormatContext *s, AVCodecParameters *par, AVIOContext *pb, int size)
Allocate extradata with additional AV_INPUT_BUFFER_PADDING_SIZE at end which is always set to 0 and fill it from pb.
int ff_rfps_add_frame (AVFormatContext *ic, AVStream *st, int64_t ts)
add frame for rfps calculation.
void ff_rfps_calculate (AVFormatContext *ic)
int avformat_find_stream_info (AVFormatContext *ic, AVDictionary **options)
Read packets of a media file to get stream information.
AVProgram * av_find_program_from_stream (AVFormatContext *ic, AVProgram *last, int s)
Find the programs which belong to a given stream.
int av_find_best_stream (AVFormatContext *ic, enum AVMediaType type, int wanted_stream_nb, int related_stream, AVCodec **decoder_ret, int flags)
Find the "best" stream in the file.
int av_read_play (AVFormatContext *s)
Start playing a network-based stream (e.g.
int av_read_pause (AVFormatContext *s)
Pause a network-based stream (e.g.
int ff_stream_encode_params_copy (AVStream *dst, const AVStream *src)
Copy encoding parameters from source to destination stream.
static void free_stream (AVStream **pst)
void ff_free_stream (AVFormatContext *s, AVStream *st)
void avformat_free_context (AVFormatContext *s)
Free an AVFormatContext and all its streams.
void avformat_close_input (AVFormatContext **ps)
Close an opened input AVFormatContext.
AVStream * avformat_new_stream (AVFormatContext *s, const AVCodec *c)
Add a new stream to a media file.
AVProgram * av_new_program (AVFormatContext *ac, int id)
AVChapter * avpriv_new_chapter (AVFormatContext *s, int id, AVRational time_base, int64_t start, int64_t end, const char *title)
Add a new chapter.
void av_program_add_stream_index (AVFormatContext *ac, int progid, unsigned idx)
uint64_t ff_ntp_time (void)
Get the current time since NTP epoch in microseconds.
int av_get_frame_filename2 (char *buf, int buf_size, const char *path, int number, int flags)
Return in 'buf' the path with 'd' replaced by a number.
int av_get_frame_filename (char *buf, int buf_size, const char *path, int number)
void av_url_split (char *proto, int proto_size, char *authorization, int authorization_size, char *hostname, int hostname_size, int *port_ptr, char *path, int path_size, const char *url)
Split a URL string into components.
char * ff_data_to_hex (char *buff, const uint8_t *src, int s, int lowercase)
int ff_hex_to_data (uint8_t *data, const char *p)
Parse a string of hexadecimal strings.
void avpriv_set_pts_info (AVStream *s, int pts_wrap_bits, unsigned int pts_num, unsigned int pts_den)
Set the time base and wrapping info for a given stream.
void ff_parse_key_value (const char *str, ff_parse_key_val_cb callback_get_buf, void *context)
Parse a string with comma-separated key=value pairs.
int ff_find_stream_index (AVFormatContext *s, int id)
Find stream index based on format-specific stream ID.
int avformat_query_codec (const AVOutputFormat *ofmt, enum AVCodecID codec_id, int std_compliance)
Test if the given container can store a codec.
int avformat_network_init (void)
Do global initialization of network components.
int avformat_network_deinit (void)
Undo the initialization done by avformat_network_init.
int ff_add_param_change (AVPacket *pkt, int32_t channels, uint64_t channel_layout, int32_t sample_rate, int32_t width, int32_t height)
Add side data to a packet for changing parameters to the given values.
AVRational av_guess_sample_aspect_ratio (AVFormatContext *format, AVStream *stream, AVFrame *frame)
Guess the sample aspect ratio of a frame, based on both the stream and the frame aspect ratio.
AVRational av_guess_frame_rate (AVFormatContext *format, AVStream *st, AVFrame *frame)
Guess the frame rate, based on both the container and codec information.
int avformat_match_stream_specifier (AVFormatContext *s, AVStream *st, const char *spec)
Check if the stream st contained in s is matched by the stream specifier spec.
int ff_generate_avci_extradata (AVStream *st)
Generate standard extradata for AVC-Intra based on width/height and field order.
uint8_t * av_stream_get_side_data (const AVStream *st, enum AVPacketSideDataType type, int *size)
Get side information from stream.
int av_stream_add_side_data (AVStream *st, enum AVPacketSideDataType type, uint8_t *data, size_t size)
Wrap an existing array as stream side data.
uint8_t * av_stream_new_side_data (AVStream *st, enum AVPacketSideDataType type, int size)
Allocate new information from stream.
int ff_stream_add_bitstream_filter (AVStream *st, const char *name, const char *args)
Add a bitstream filter to a stream.
int ff_format_output_open (AVFormatContext *s, const char *url, AVDictionary **options)
Utility function to open IO stream of output format.
void ff_format_io_close (AVFormatContext *s, AVIOContext **pb)
int ff_parse_creation_time_metadata (AVFormatContext *s, int64_t *timestamp, int return_seconds)
Parse creation_time in AVFormatContext metadata if exists and warn if the parsing fails.
int ff_standardize_creation_time (AVFormatContext *s)
Standardize creation_time metadata in AVFormatContext to an ISO-8601 timestamp string.
int ff_get_packet_palette (AVFormatContext *s, AVPacket *pkt, int ret, uint32_t *palette)
Retrieves the palette from a packet, either from side data, or appended to the video data in the packet itself (raw video only).
int ff_bprint_to_codecpar_extradata (AVCodecParameters *par, struct AVBPrint *buf)
Finalize buf into extradata and set its size appropriately.
int avformat_transfer_internal_stream_timing_info (const AVOutputFormat *ofmt, AVStream *ost, const AVStream *ist, enum AVTimebaseSource copy_tb)
Transfer internal timing information from one stream to another.
AVRational av_stream_get_codec_timebase (const AVStream *st)
Get the internal codec timebase from a stream.
Variables
const char av_format_ffversion [] = "FFmpeg version " FFMPEG_VERSION
Detailed Description
various utility functions for use within FFmpeg
Definition in file utils.c.
Macro Definition Documentation
LICENSE_PREFIX
#define LICENSE_PREFIX "libavformat license: "
Referenced by avformat_license().
RELATIVE_TS_BASE
#define RELATIVE_TS_BASE (INT64_MAX - (1LL<<48))
Definition at line 80 of file utils.c.
Referenced by av_read_frame(), avformat_new_stream(), ff_add_index_entry(), ff_read_frame_flush(), ff_rfps_add_frame(), is_relative(), read_frame_internal(), update_initial_durations(), and update_initial_timestamps().
SANE_CHUNK_SIZE
#define SANE_CHUNK_SIZE (50000000)
Definition at line 224 of file utils.c.
Referenced by append_packet_chunked().
DURATION_MAX_READ_SIZE
#define DURATION_MAX_READ_SIZE 250000LL
Definition at line 2703 of file utils.c.
Referenced by estimate_timings_from_pts().
DURATION_MAX_RETRY
#define DURATION_MAX_RETRY 6
Definition at line 2704 of file utils.c.
Referenced by estimate_timings_from_pts().
FAIL
#define FAIL (errmsg)
Value:
do {                                         \
        if (errmsg_ptr)                                           \
            *errmsg_ptr = errmsg;                                 \
        return 0;                                                 \
    } while (0)
Referenced by has_codec_parameters().
Function Documentation
is_relative()
static int is_relative (int64_t ts) static
Definition at line 82 of file utils.c.
Referenced by av_read_frame(), compute_pkt_fields(), ff_add_index_entry(), ff_read_packet(), ff_rfps_add_frame(), read_frame_internal(), and update_initial_timestamps().
wrap_timestamp()
static int64_t wrap_timestamp (const AVStream * st, int64_t timestamp) static
Wrap a given time stamp, if there is an indication for an overflow.
Parameters
st stream
timestamp the time stamp to wrap
Returns
resulting time stamp
Definition at line 93 of file utils.c.
Referenced by av_add_index_entry(), ff_read_packet(), and ff_read_timestamp().
av_stream_get_end_pts()
int64_t av_stream_get_end_pts (const AVStream * st)
Returns the pts of the last muxed packet + its duration.
the retuned value is undefined when used with a demuxer.
Definition at line 122 of file utils.c.
Referenced by do_video_stats(), and print_report().
av_stream_get_parser()
struct AVCodecParserContext* av_stream_get_parser (const AVStream * st)
Definition at line 130 of file utils.c.
Referenced by process_input_packet().
av_format_inject_global_side_data()
void av_format_inject_global_side_data (AVFormatContext * s)
This function will cause global side data to be injected in the next packet of each stream as well as after any subsequent seek.
Definition at line 135 of file utils.c.
Referenced by read_thread().
ff_copy_whiteblacklists()
int ff_copy_whiteblacklists (AVFormatContext * dst, const AVFormatContext * src)
Copies the whilelists from one context to the other.
Definition at line 145 of file utils.c.
Referenced by ff_wms_parse_sdp_a_line(), hls_read_header(), ism_write_header(), open_file(), rdt_init(), read_gab2_sub(), and sap_read_header().
find_decoder()
static const AVCodec* find_decoder (AVFormatContext * s, const AVStream * st, enum AVCodecID codec_id) static
Definition at line 165 of file utils.c.
Referenced by av_find_best_stream(), and find_probe_decoder().
find_probe_decoder()
static const AVCodec* find_probe_decoder (AVFormatContext * s, const AVStream * st, enum AVCodecID codec_id) static
Definition at line 189 of file utils.c.
Referenced by avformat_find_stream_info(), and try_decode_frame().
av_format_get_probe_score()
int av_format_get_probe_score (const AVFormatContext * s)
Definition at line 218 of file utils.c.
Referenced by show_format().
ffio_limit()
int ffio_limit (AVIOContext * s, int size)
Definition at line 226 of file utils.c.
Referenced by append_packet_chunked(), asf_read_stream_properties(), cin_read_packet(), ebml_parse_elem(), ffio_wfourcc(), rm_assemble_video_frame(), roq_read_packet(), siff_read_packet(), and vmd_read_packet().
append_packet_chunked()
static int append_packet_chunked (AVIOContext * s, AVPacket * pkt, int size) static
Definition at line 248 of file utils.c.
Referenced by av_append_packet(), and av_get_packet().
av_get_packet()
int av_get_packet (AVIOContext * s, AVPacket * pkt, int size)
Allocate and read the payload of a packet and initialize its fields with default values.
Parameters
s associated IO context
pkt packet
size desired payload size
Returns
>0 (read size) if OK, AVERROR_xxx otherwise
Definition at line 289 of file utils.c.
Referenced by adp_read_packet(), ads_read_packet(), adx_read_packet(), aea_read_packet(), afc_read_packet(), aiff_read_packet(), aix_read_packet(), apc_read_packet(), ape_tag_read_field(), asf_read_header(), asf_read_picture(), asf_read_subpayload(), ast_read_packet(), av_append_packet(), avi_read_packet(), bfi_read_packet(), cdata_read_packet(), cdxl_read_packet(), cin_read_packet(), cine_read_packet(), daud_packet(), dcstr_read_packet(), dfa_read_packet(), dsf_read_packet(), dxa_read_packet(), ea_read_packet(), ff_pcm_read_packet(), ff_rm_parse_packet(), ff_rm_retrieve_cache(), ff_voc_get_packet(), film_read_packet(), flv_data_packet(), flv_read_packet(), fourxm_read_packet(), frm_read_packet(), fsb_read_packet(), g729_read_packet(), genh_read_packet(), get_attachment(), gif_read_packet(), gsm_read_packet(), gxf_packet(), hnm_read_packet(), idcin_read_packet(), iff_read_packet(), ingenient_read_packet(), iss_read_packet(), lmlm4_read_packet(), load_ipmovie_packet(), lvf_read_packet(), mmf_read_packet(), mov_read_chapters(), mov_read_covr(), mov_read_packet(), mp3_read_packet(), mpc8_read_packet(), mpegps_read_packet(), mpjpeg_read_packet(), msf_read_packet(), msnwc_tcp_read_packet(), mtaf_read_packet(), mtv_read_packet(), musx_read_packet(), mv_read_packet(), mxf_decrypt_triplet(), mxf_get_d10_aes3_packet(), mxf_read_packet(), mxf_read_packet_old(), nc_read_packet(), nsv_read_chunk(), nuv_packet(), oma_read_packet(), pmp_packet(), pva_read_packet(), qcp_read_packet(), r3d_read_reda(), r3d_read_redv(), raw_read_packet(), rawvideo_read_packet(), read_dst_frame(), read_packet(), redspark_read_packet(), rl2_read_packet(), roq_read_packet(), rpl_read_packet(), rsd_read_packet(), sdr2_read_packet(), seq_read_packet(), set_spdif(), siff_read_packet(), smjpeg_read_packet(), smush_read_packet(), sol_read_packet(), sup_read_packet(), svag_read_packet(), swf_read_packet(), thp_read_packet(), threedostr_read_packet(), tmv_read_packet(), tta_read_packet(), txd_read_packet(), v210_read_packet(), vag_read_packet(), vc1t_read_packet(), vid_read_packet(), vivo_read_packet(), vpk_read_packet(), wc3_read_packet(), wsaud_read_packet(), wsvqa_read_packet(), xa_read_packet(), xmv_fetch_audio_packet(), xmv_fetch_video_packet(), xvag_read_packet(), xwma_read_packet(), yop_read_packet(), and yuv4_read_packet().
av_append_packet()
int av_append_packet (AVIOContext * s, AVPacket * pkt, int size)
Read data and append it to the current content of the AVPacket.
If pkt->size is 0 this is identical to av_get_packet. Note that this uses av_grow_packet and thus involves a realloc which is inefficient. Thus this function should only be used when there is no reasonable way to know (an upper bound of) the final size.
Parameters
s associated IO context
pkt packet
size amount of data to read
Returns
>0 (read size) if OK, AVERROR_xxx otherwise, previous data will not be lost even if an error occurs.
Definition at line 299 of file utils.c.
Referenced by apng_read_packet(), dfa_read_packet(), ea_read_packet(), mpjpeg_read_packet(), read_packet(), sup_read_packet(), vivo_read_packet(), wc3_read_header(), and wc3_read_packet().
set_codec_from_probe_data()
static int set_codec_from_probe_data (AVFormatContext * s, AVStream * st, AVProbeData * pd) static
Definition at line 313 of file utils.c.
Referenced by probe_codec().
init_input()
static int init_input (AVFormatContext * s, const char * filename, AVDictionary ** options) static
Definition at line 394 of file utils.c.
Referenced by avformat_open_input().
add_to_pktbuf()
static int add_to_pktbuf (AVPacketList ** packet_buffer, AVPacket * pkt, AVPacketList ** plast_pktl, int ref) static
Definition at line 425 of file utils.c.
Referenced by av_read_frame(), avformat_find_stream_info(), avformat_queue_attached_pictures(), ff_read_packet(), and parse_packet().
update_stream_avctx()
static int update_stream_avctx (AVFormatContext * s) static
Definition at line 475 of file utils.c.
Referenced by avformat_open_input(), and read_frame_internal().
force_codec_ids()
static void force_codec_ids (AVFormatContext * s, AVStream * st) static
Definition at line 641 of file utils.c.
Referenced by ff_read_packet(), and probe_codec().
probe_codec()
static int probe_codec (AVFormatContext * s, AVStream * st, const AVPacket * pkt) static
Definition at line 663 of file utils.c.
Referenced by ff_read_packet(), and find_probe_decoder().
update_wrap_reference()
static int update_wrap_reference (AVFormatContext * s, AVStream * st, int stream_index, AVPacket * pkt) static
Definition at line 713 of file utils.c.
Referenced by ff_read_packet().
ff_read_packet()
int ff_read_packet (AVFormatContext * s, AVPacket * pkt)
Read a transport packet from a media file.
Parameters
s media file handle
pkt is filled
Returns
0 if OK, AVERROR_xxx on error
Definition at line 779 of file utils.c.
Referenced by asfrtp_parse_packet(), estimate_timings_from_pts(), get_subtitle_pkt(), read_frame_internal(), read_gab2_sub(), and seek_subtitle().
determinable_frame_size()
static int determinable_frame_size (AVCodecContext * avctx) static
Definition at line 883 of file utils.c.
Referenced by has_codec_parameters().
ff_compute_frame_duration()
void ff_compute_frame_duration (AVFormatContext * s, int * pnum, int * pden, AVStream * st, AVCodecParserContext * pc, AVPacket * pkt)
Return the frame duration in seconds.
Return 0 if not available.
Definition at line 897 of file utils.c.
Referenced by compute_pkt_fields(), and estimate_timings_from_pts().
is_intra_only()
static int is_intra_only (enum AVCodecID id) static
Definition at line 964 of file utils.c.
Referenced by compute_pkt_fields().
has_decode_delay_been_guessed()
static int has_decode_delay_been_guessed (AVStream * st) static
Definition at line 974 of file utils.c.
Referenced by avformat_find_stream_info(), compute_pkt_fields(), try_decode_frame(), and update_initial_timestamps().
get_next_pkt()
static AVPacketList* get_next_pkt (AVFormatContext * s, AVStream * st, AVPacketList * pktl) static
Definition at line 992 of file utils.c.
Referenced by update_dts_from_pts(), update_initial_durations(), and update_initial_timestamps().
select_from_pts_buffer()
static int64_t select_from_pts_buffer (AVStream * st, int64_t * pts_buffer, int64_t dts) static
Definition at line 1001 of file utils.c.
Referenced by compute_pkt_fields(), and update_dts_from_pts().
update_dts_from_pts()
static void update_dts_from_pts (AVFormatContext * s, int stream_index, AVPacketList * pkt_buffer) static
Updates the dts of packets of a stream in pkt_buffer, by re-ordering the pts of the packets in a window.
Definition at line 1047 of file utils.c.
Referenced by avformat_find_stream_info(), and update_initial_timestamps().
update_initial_timestamps()
static void update_initial_timestamps (AVFormatContext * s, int stream_index, int64_t dts, int64_t pts, AVPacket * pkt) static
Definition at line 1073 of file utils.c.
Referenced by compute_pkt_fields().
update_initial_durations()
static void update_initial_durations (AVFormatContext * s, AVStream * st, int stream_index, int duration) static
Definition at line 1122 of file utils.c.
Referenced by compute_pkt_fields().
compute_pkt_fields()
static void compute_pkt_fields (AVFormatContext * s, AVStream * st, AVCodecParserContext * pc, AVPacket * pkt, int64_t next_dts, int64_t next_pts) static
Definition at line 1175 of file utils.c.
Referenced by parse_packet(), and read_frame_internal().
free_packet_buffer()
static void free_packet_buffer (AVPacketList ** pkt_buf, AVPacketList ** pkt_buf_end) static
Definition at line 1365 of file utils.c.
Referenced by flush_packet_queue().
parse_packet()
static int parse_packet (AVFormatContext * s, AVPacket * pkt, int stream_index) static
Parse a packet, add all split parts to parse_queue.
Parameters
pkt Packet to parse, NULL when flushing the parser at end of stream.
Definition at line 1381 of file utils.c.
Referenced by read_frame_internal().
read_from_packet_buffer()
static int read_from_packet_buffer (AVPacketList ** pkt_buffer, AVPacketList ** pkt_buffer_end, AVPacket * pkt) static
Definition at line 1474 of file utils.c.
Referenced by av_read_frame(), and read_frame_internal().
ts_to_samples()
static int64_t ts_to_samples (AVStream * st, int64_t ts) static
Definition at line 1489 of file utils.c.
Referenced by read_frame_internal().
read_frame_internal()
static int read_frame_internal (AVFormatContext * s, AVPacket * pkt) static
Definition at line 1494 of file utils.c.
Referenced by av_read_frame(), and avformat_find_stream_info().
flush_packet_queue()
static void flush_packet_queue (AVFormatContext * s) static
Definition at line 1791 of file utils.c.
Referenced by avformat_close_input(), avformat_free_context(), estimate_timings_from_pts(), and ff_read_frame_flush().
ff_read_frame_flush()
void ff_read_frame_flush (AVFormatContext * s)
Flush the frame reader.
Definition at line 1843 of file utils.c.
Referenced by asf_read_pts(), avformat_flush(), avformat_seek_file(), ff_seek_frame_binary(), hls_read_seek(), mpegts_get_dts(), seek_frame_generic(), and seek_frame_internal().
ff_update_cur_dts()
void ff_update_cur_dts (AVFormatContext * s, AVStream * ref_st, int64_t timestamp)
Update cur_dts of all streams based on the given timestamp and AVStream.
Stream ref_st unchanged, others set cur_dts in their native time base. Only needed for timestamp wrapping or if (dts not set and pts!=dts).
Parameters
timestamp new dts expressed in time_base of param ref_st
ref_st reference stream giving time_base of param timestamp
Definition at line 1878 of file utils.c.
Referenced by ff_seek_frame_binary(), idcin_read_seek(), matroska_read_seek(), mp3_seek(), mpc8_read_seek(), mxf_read_seek(), read_seek(), and seek_frame_generic().
ff_reduce_index()
void ff_reduce_index (AVFormatContext * s, int stream_index)
Ensure the index uses less memory than the maximum specified in AVFormatContext.max_index_size by discarding entries if it grows too large.
Definition at line 1892 of file utils.c.
Referenced by av_read_frame(), matroska_parse_block(), mpegps_read_pes_header(), mpegts_get_dts(), and read_frame_internal().
ff_add_index_entry()
int ff_add_index_entry (AVIndexEntry ** index_entries, int * nb_index_entries, unsigned int * index_entries_allocated_size, int64_t pos, int64_t timestamp, int size, int distance, int flags)
Internal version of av_add_index_entry.
Definition at line 1905 of file utils.c.
Referenced by av_add_index_entry(), read_header(), and scan_file().
ff_index_search_timestamp()
int ff_index_search_timestamp (const AVIndexEntry * entries, int nb_entries, int64_t wanted_timestamp, int flags)
Internal version of av_index_search_timestamp.
Definition at line 1973 of file utils.c.
Referenced by av_index_search_timestamp(), ff_add_index_entry(), mxf_read_seek(), and read_seek().
ff_configure_buffers_for_index()
void ff_configure_buffers_for_index (AVFormatContext * s, int64_t time_tolerance)
Definition at line 2016 of file utils.c.
Referenced by mov_read_header().
ff_read_timestamp()
static int64_t ff_read_timestamp (AVFormatContext * s, int stream_index, int64_t * ppos, int64_t pos_limit, int64_t(*)(struct AVFormatContext *, int, int64_t *, int64_t) read_timestamp) static
Definition at line 2079 of file utils.c.
Referenced by ff_find_last_ts(), and ff_gen_search().
ff_seek_frame_binary()
int ff_seek_frame_binary (AVFormatContext * s, int stream_index, int64_t target_ts, int flags)
Perform a binary search using av_index_search_timestamp() and AVInputFormat.read_timestamp().
Parameters
target_ts target timestamp in the time base of the given stream
stream_index stream number
Definition at line 2088 of file utils.c.
Referenced by asf_read_seek(), ogg_read_seek(), rm_read_seek(), and seek_frame_internal().
ff_find_last_ts()
int ff_find_last_ts (AVFormatContext * s, int stream_index, int64_t * ts, int64_t * pos, int64_t(*)(struct AVFormatContext *, int, int64_t *, int64_t) read_timestamp)
Definition at line 2156 of file utils.c.
Referenced by ff_gen_search(), and find_duration().
ff_gen_search()
int64_t ff_gen_search (AVFormatContext * s, int stream_index, int64_t target_ts, int64_t pos_min, int64_t pos_max, int64_t pos_limit, int64_t ts_min, int64_t ts_max, int flags, int64_t * ts_ret, int64_t(*)(struct AVFormatContext *, int, int64_t *, int64_t) read_timestamp)
Perform a binary search using read_timestamp().
Parameters
target_ts target timestamp in the time base of the given stream
stream_index stream number
Definition at line 2194 of file utils.c.
Referenced by ff_seek_frame_binary(), and read_seek().
seek_frame_byte()
static int seek_frame_byte (AVFormatContext * s, int stream_index, int64_t pos, int flags) static
Definition at line 2300 of file utils.c.
Referenced by seek_frame_internal().
seek_frame_generic()
static int seek_frame_generic (AVFormatContext * s, int stream_index, int64_t timestamp, int flags) static
Definition at line 2320 of file utils.c.
Referenced by seek_frame_internal().
seek_frame_internal()
static int seek_frame_internal (AVFormatContext * s, int stream_index, int64_t timestamp, int flags) static
Definition at line 2387 of file utils.c.
Referenced by av_seek_frame().
has_duration()
static int has_duration (AVFormatContext * ic) static
Return TRUE if the stream has accurate duration in any stream.
Returns
TRUE if the stream has accurate duration for at least one component.
Definition at line 2524 of file utils.c.
Referenced by estimate_timings().
update_stream_timings()
static void update_stream_timings (AVFormatContext * ic) static
Estimate the stream timings from the one of each components.
Also computes the global bitrate if possible.
Definition at line 2544 of file utils.c.
Referenced by estimate_timings(), and fill_all_stream_timings().
fill_all_stream_timings()
static void fill_all_stream_timings (AVFormatContext * ic) static
Definition at line 2629 of file utils.c.
Referenced by estimate_timings(), and estimate_timings_from_pts().
estimate_timings_from_bit_rate()
static void estimate_timings_from_bit_rate (AVFormatContext * ic) static
Definition at line 2648 of file utils.c.
Referenced by estimate_timings().
estimate_timings_from_pts()
static void estimate_timings_from_pts (AVFormatContext * ic, int64_t old_offset) static
Definition at line 2707 of file utils.c.
Referenced by estimate_timings().
estimate_timings()
static void estimate_timings (AVFormatContext * ic, int64_t old_offset) static
Definition at line 2842 of file utils.c.
Referenced by avformat_find_stream_info().
has_codec_parameters()
static int has_codec_parameters (AVStream * st, const char ** errmsg_ptr) static
Definition at line 2889 of file utils.c.
Referenced by avformat_find_stream_info(), and try_decode_frame().
try_decode_frame()
static int try_decode_frame (AVFormatContext * s, AVStream * st, AVPacket * avpkt, AVDictionary ** options) static
Definition at line 2937 of file utils.c.
Referenced by avformat_find_stream_info().
ff_codec_get_tag()
unsigned int ff_codec_get_tag (const AVCodecTag * tags, enum AVCodecID id)
Definition at line 3035 of file utils.c.
Referenced by ast_write_header(), caf_write_header(), flv_write_header(), flv_write_packet(), gxf_write_header(), ipod_get_codec_tag(), ircam_write_header(), mkv_write_codecprivate(), mkv_write_track(), mov_find_codec_tag(), mov_get_codec_tag(), mov_write_esds_tag(), mov_write_isml_manifest(), mp4_get_codec_tag(), smjpeg_write_header(), swf_write_video(), and write_stream_codec_info().
ff_codec_get_id()
enum AVCodecID ff_codec_get_id (const AVCodecTag * tags, unsigned int tag)
Definition at line 3045 of file utils.c.
Referenced by asf_read_stream_properties(), ast_read_header(), av_codec_get_id(), avi_read_header(), create_new_audio_stream(), decode_stream_header(), ff_mp4_read_dec_config_descr(), ff_rm_read_mdpr_codecdata(), ff_voc_get_packet(), ff_wav_codec_get_id(), get_aiff_header(), get_codec_data(), get_qt_codec(), ircam_read_header(), lvf_read_header(), lxf_read_header(), matroska_parse_tracks(), mkv_write_codecprivate(), mkv_write_native_codecprivate(), mov_codec_id(), mov_skip_multiple_stsd(), nsv_parse_NSVs_header(), nut_read_header(), ogm_dshow_header(), ogm_header(), oma_read_header(), parse_dsd_prop(), parse_media_type(), parse_video_info(), read_desc_chunk(), read_header(), rm_read_audio_stream_info(), rsd_read_header(), rso_read_header(), smjpeg_read_header(), and swf_read_packet().
ff_get_pcm_codec_id()
enum AVCodecID ff_get_pcm_codec_id (int bps, int flt, int be, int sflags)
Select a PCM codec based on the given parameters.
Parameters
bps bits-per-sample
flt floating-point
be big-endian
sflags signed flags. each bit corresponds to one byte of bit depth. e.g. the 1st bit indicates if 8-bit should be signed or unsigned, the 2nd bit indicates if 16-bit should be signed or unsigned, etc... This is useful for formats such as WAVE where only 8-bit is unsigned and all other bit depths are signed.
Returns
a PCM codec id or AV_CODEC_ID_NONE
Definition at line 3057 of file utils.c.
Referenced by avr_read_header(), ff_mov_get_lpcm_codec_id(), ff_wav_codec_get_id(), get_codec_data(), nist_read_header(), and pvf_read_header().
av_codec_get_tag()
unsigned int av_codec_get_tag (const AVCodecTag *const * tags, enum AVCodecID id)
Definition at line 3106 of file utils.c.
av_codec_get_tag2()
int av_codec_get_tag2 (const AVCodecTag *const * tags, enum AVCodecID id, unsigned int * tag)
Definition at line 3114 of file utils.c.
Referenced by av_codec_get_tag(), and avformat_query_codec().
av_codec_get_id()
enum AVCodecID av_codec_get_id (const AVCodecTag *const * tags, unsigned int tag)
Definition at line 3131 of file utils.c.
compute_chapters_end()
static void compute_chapters_end (AVFormatContext * s) static
Definition at line 3142 of file utils.c.
Referenced by avformat_find_stream_info().
get_std_framerate()
static int get_std_framerate (int i) static
Definition at line 3169 of file utils.c.
Referenced by avformat_find_stream_info(), ff_rfps_add_frame(), and ff_rfps_calculate().
tb_unreliable()
static int tb_unreliable (AVCodecContext * c) static
Definition at line 3193 of file utils.c.
Referenced by avformat_find_stream_info(), and ff_rfps_calculate().
ff_alloc_extradata()
int ff_alloc_extradata (AVCodecParameters * par, int size)
Allocate extradata with additional AV_INPUT_BUFFER_PADDING_SIZE at end which is always set to 0.
Parameters
size size of extradata
Returns
0 if OK, AVERROR_xxx on error
Definition at line 3208 of file utils.c.
Referenced by acm_read_header(), afc_read_header(), ape_read_header(), celt_header(), copy_stream_props(), dfa_read_header(), encode_intervals(), ff_generate_avci_extradata(), ff_get_extradata(), ff_parse_mpeg2_descriptor(), ff_rename(), filter_packet(), flac_header(), flic_read_header(), flv_set_video_codec(), fsb_read_header(), genh_read_header(), init_stream(), matroska_parse_tracks(), matroska_read_header(), mov_create_chapter_track(), msf_read_header(), mxf_parse_structural_metadata(), nist_read_header(), nut_read_header(), ogm_header(), oma_read_header(), opus_header(), parse_fmtp_config(), parse_packed_headers(), qdm2_parse_config(), read_header(), read_kuki_chunk(), redspark_read_header(), rsd_read_header(), set_spdif(), smacker_read_header(), smush_read_header(), speex_header(), svq3_parse_packet(), tta_read_header(), vmd_read_header(), vqf_read_header(), wsvqa_read_packet(), xmv_process_packet_header(), xwma_read_header(), and yop_read_header().
ff_get_extradata()
int ff_get_extradata (AVFormatContext * s, AVCodecParameters * par, AVIOContext * pb, int size)
Allocate extradata with additional AV_INPUT_BUFFER_PADDING_SIZE at end which is always set to 0 and fill it from pb.
Parameters
size size of extradata
Returns
>= 0 if OK, AVERROR_xxx on error
Definition at line 3229 of file utils.c.
Referenced by adx_read_header(), aiff_read_header(), aix_read_header(), apc_read_header(), ape_tag_read_field(), avi_read_header(), decode_stream_header(), ff_get_wav_header(), ff_mp4_read_dec_config_descr(), ff_rename(), flv_get_extradata(), get_codec_data(), idcin_read_header(), mov_parse_stsd_data(), mov_read_dfla(), mov_read_dvc1(), mov_read_glbl(), mov_read_strf(), mov_read_wave(), mpc8_read_header(), mpc_read_header(), read_header(), read_kuki_chunk(), rl2_read_header(), rm_read_extradata(), rsd_read_header(), vc1t_read_header(), and wsvqa_read_header().
ff_rfps_add_frame()
int ff_rfps_add_frame (AVFormatContext * ic, AVStream * st, int64_t dts)
add frame for rfps calculation.
Parameters
dts timestamp of the i-th frame
Returns
0 if OK, AVERROR_xxx on error
Definition at line 3245 of file utils.c.
Referenced by avformat_find_stream_info(), ff_rename(), and mov_build_index().
ff_rfps_calculate()
void ff_rfps_calculate (AVFormatContext * ic)
Definition at line 3303 of file utils.c.
Referenced by avformat_find_stream_info(), ff_rename(), and mov_read_header().
ff_stream_encode_params_copy()
int ff_stream_encode_params_copy (AVStream * dst, const AVStream * src)
Copy encoding parameters from source to destination stream.
Parameters
dst pointer to destination AVStream
src pointer to source AVStream
Returns
>=0 on success, AVERROR code on error
Definition at line 4058 of file utils.c.
Referenced by fifo_mux_init(), and open_slave().
free_stream()
static void free_stream (AVStream ** pst) static
Definition at line 4115 of file utils.c.
Referenced by avformat_new_stream(), and ff_free_stream().
ff_free_stream()
void ff_free_stream (AVFormatContext * s, AVStream * st)
Definition at line 4163 of file utils.c.
Referenced by avformat_free_context(), and ff_rm_read_mdpr_codecdata().
avpriv_new_chapter()
AVChapter* avpriv_new_chapter (AVFormatContext * s, int id, AVRational time_base, int64_t start, int64_t end, const char * title)
Add a new chapter.
Parameters
s media file handle
id unique ID for this chapter
start chapter start time in time_base units
end chapter end time in time_base units
title chapter title
Returns
AVChapter or NULL on error
Definition at line 4362 of file utils.c.
Referenced by asf_read_marker(), decode_info_header(), flac_read_header(), matroska_read_header(), mov_metadata_hmmt(), mov_read_chapters(), mov_read_chpl(), ogm_chapter(), read_chapter(), and read_header().
av_program_add_stream_index()
void av_program_add_stream_index (AVFormatContext * ac, int progid, unsigned idx)
Definition at line 4392 of file utils.c.
ff_ntp_time()
uint64_t ff_ntp_time (void)
Get the current time since NTP epoch in microseconds.
Definition at line 4420 of file utils.c.
Referenced by rtp_write_header(), rtp_write_packet(), and rtp_write_trailer().
ff_data_to_hex()
char* ff_data_to_hex (char * buff, const uint8_t * src, int s, int lowercase)
Definition at line 4559 of file utils.c.
Referenced by do_llnw_auth(), ff_rdt_calc_response_and_checksum(), hex_log(), hls_encryption_start(), make_digest_auth(), open_input(), and param_write_hex().
ff_hex_to_data()
int ff_hex_to_data (uint8_t * data, const char * p)
Parse a string of hexadecimal strings.
Any space between the hexadecimal digits is ignored.
Parameters
data if non-null, the parsed data is written to this pointer
p the string to parse
Returns
the number of bytes written (or to be written, if data is null)
Definition at line 4580 of file utils.c.
Referenced by parse_fmtp_config(), and parse_playlist().
avpriv_set_pts_info()
void avpriv_set_pts_info (AVStream * s, int pts_wrap_bits, unsigned int pts_num, unsigned int pts_den)
Set the time base and wrapping info for a given stream.
This will be used to interpret the stream's timestamps. If the new time base is invalid (numerator or denominator are non-positive), it leaves the stream unchanged.
Parameters
s stream
pts_wrap_bits number of bits effectively used by the pts (used for wrap control)
pts_num time base numerator
pts_den time base denominator
Definition at line 4608 of file utils.c.
Referenced by acm_read_header(), adp_read_header(), ads_read_header(), adts_aac_read_header(), adx_read_header(), afc_read_header(), aiff_read_header(), aiff_write_header(), aix_read_header(), amr_read_header(), ape_read_header(), apng_read_header(), aqt_read_header(), asf_read_stream_properties(), asf_write_header1(), asfrtp_parse_sdp_line(), ass_read_header(), ast_read_header(), audio_read_header(), audio_write_header(), avformat_new_stream(), avi_read_header(), avi_write_header(), avisynth_create_stream_audio(), avisynth_create_stream_video(), avr_read_header(), bfi_read_header(), bmv_read_header(), cdata_read_header(), cdxl_read_packet(), celt_header(), cin_read_header(), cine_read_header(), create_audio_stream(), create_new_audio_stream(), create_stream(), daala_header(), dc1394_read_common(), dcstr_read_header(), decklink_setup_audio(), decklink_setup_video(), decode_stream_header(), dfa_read_header(), dirac_header(), dshow_add_device(), dss_read_header(), dtshd_read_header(), dv_extract_audio_info(), dv_extract_video_info(), dxa_read_header(), ea_read_header(), epaf_read_header(), fbdev_read_header(), ff_decklink_read_header(), ff_img_read_header(), ff_raw_video_read_header(), ff_rm_read_mdpr_codecdata(), ff_voc_get_packet(), ffm2_read_header(), ffm_read_header(), ffm_write_header(), film_read_header(), flac_header(), flac_read_header(), flic_read_header(), flv_write_header(), fsb_read_header(), g722_read_header(), g723_1_init(), g729_read_header(), gdigrab_read_header(), genh_read_header(), get_audio_config(), get_packet_header(), get_sockaddr(), get_video_config(), gif_read_header(), gif_write_header(), grab_read_header(), gsm_read_header(), gxf_header(), gxf_write_header(), hls_write_header(), hnm_read_header(), idcin_read_header(), iff_read_header(), ilbc_read_header(), init_audio(), init_muxer(), init_stream(), init_video_stream(), ipmovie_read_header(), ircam_read_header(), iss_read_header(), jacosub_read_header(), lavfi_read_header(), lmlm4_read_header(), loas_read_header(), lrc_read_header(), lrc_write_header(), lvf_read_header(), lxf_read_header(), matroska_parse_tracks(), microdvd_read_header(), microdvd_write_header(), mkv_init(), mmf_rate(), mmf_read_header(), modplug_read_header(), mov_init(), mov_read_trak(), mp3_read_header(), mpc8_read_header(), mpc_read_header(), mpeg_mux_init(), mpegts_init(), mpegts_read_header(), mpegts_set_stream_info(), mpjpeg_read_header(), mpl2_read_header(), mpsub_read_header(), msf_read_header(), msnwc_tcp_read_header(), mtaf_read_header(), mtv_read_header(), musx_read_header(), mv_read_header(), mxf_parse_structural_metadata(), mxf_write_header(), mxg_read_header(), nc_read_header(), new_stream(), nist_read_header(), nsv_parse_NSVs_header(), nut_read_header(), nut_write_header(), nuv_header(), ogg_build_vp8_headers(), ogg_new_stream(), ogg_write_header(), ogm_dshow_header(), ogm_header(), old_dirac_header(), old_flac_header(), oma_read_header(), opus_header(), parse_audio_var(), parse_strk(), parse_video_var(), parse_vtrk(), pcm_read_header(), pjs_read_header(), pmp_header(), pulse_read_header(), pulse_write_header(), pva_read_header(), pvf_read_header(), qt_rtp_parse_packet(), qtkit_read_header(), r3d_read_red1(), r3d_read_reda(), rawvideo_read_header(), read_frame(), read_gab2_sub(), read_header(), read_header_gme(), read_header_openmpt(), read_sl_header(), realtext_read_header(), redspark_read_header(), rl2_read_header(), roq_read_packet(), rpl_read_header(), rsd_read_header(), rso_read_header(), rtp_write_header(), sami_read_header(), sbg_read_header(), sdr2_read_header(), seg_init(), seq_read_header(), set_spdif(), set_stream_info_from_input_stream(), siff_parse_vbv1(), skeleton_header(), smacker_read_header(), smjpeg_read_header(), smjpeg_write_header(), smush_read_header(), sol_read_header(), sox_read_header(), speex_header(), srt_read_header(), srt_write_header(), stl_read_header(), str_read_packet(), subviewer1_read_header(), subviewer_read_header(), sup_read_header(), svag_read_header(), swf_read_packet(), tak_read_header(), tedcaptions_read_header(), theora_header(), thp_read_header(), threedostr_read_header(), tmv_read_header(), tta_read_header(), tta_write_header(), txd_read_header(), v210_read_header(), v4l2_read_header(), vag_read_header(), vc1t_read_header(), vc1test_write_header(), vfw_read_header(), vid_read_packet(), vivo_read_header(), vmd_read_header(), vorbis_header(), vp8_header(), vpk_read_header(), vplayer_read_header(), vqf_read_header(), wc3_read_header(), webm_chunk_write_header(), webp_write_header(), webvtt_read_header(), webvtt_write_header(), write_header(), write_stream_data(), wsaud_read_header(), wsvqa_read_header(), wsvqa_read_packet(), wv_read_header(), wve_read_header(), x11grab_read_header(), xa_read_header(), xmv_process_packet_header(), xvag_read_header(), xwma_read_header(), yop_read_header(), and yuv4_read_header().
ff_parse_key_value()
void ff_parse_key_value (const char * str, ff_parse_key_val_cb callback_get_buf, void * context)
Parse a string with comma-separated key=value pairs.
The value strings may be quoted and may contain escaped characters within quoted strings.
Parameters
str the string to parse
callback_get_buf function that returns where to store the unescaped value string.
context the opaque context pointer to pass to callback_get_buf
Definition at line 4638 of file utils.c.
Referenced by ff_http_auth_handle_header(), and parse_playlist().
ff_find_stream_index()
int ff_find_stream_index (AVFormatContext * s, int id)
Find stream index based on format-specific stream ID.
Returns
stream index, or < 0 on error
Definition at line 4692 of file utils.c.
Referenced by get_sindex(), parse_chunks(), pmt_cb(), and scte_data_cb().
ff_add_param_change()
int ff_add_param_change (AVPacket * pkt, int32_t channels, uint64_t channel_layout, int32_t sample_rate, int32_t width, int32_t height)
Add side data to a packet for changing parameters to the given values.
Parameters set to 0 aren't included in the change.
Definition at line 4742 of file utils.c.
Referenced by flv_read_packet(), load_ipmovie_packet(), and swf_read_packet().
ff_generate_avci_extradata()
int ff_generate_avci_extradata (AVStream * st)
Generate standard extradata for AVC-Intra based on width/height and field order.
Definition at line 5287 of file utils.c.
Referenced by mov_read_trak(), and mxf_parse_structural_metadata().
ff_stream_add_bitstream_filter()
int ff_stream_add_bitstream_filter (AVStream * st, const char * name, const char * args)
Add a bitstream filter to a stream.
Parameters
st output stream to add a filter to
name the name of the filter to add
args filter-specific argument string
Returns
>0 on success; AVERROR code on failure
Definition at line 5497 of file utils.c.
Referenced by force_one_stream(), ivf_check_bitstream(), latm_check_bitstream(), mkv_check_bitstream(), mov_check_bitstream(), and mpegts_check_bitstream().
ff_format_output_open()
int ff_format_output_open (AVFormatContext * s, const char * url, AVDictionary ** options)
Utility function to open IO stream of output format.
Parameters
s AVFormatContext
url URL or file name to open for writing optional options which will be passed to io_open callback
Returns
>=0 on success, negative AVERROR in case of failure
Definition at line 5612 of file utils.c.
Referenced by fifo_thread_write_header(), and open_slave().
ff_format_io_close()
void ff_format_io_close (AVFormatContext * s, AVIOContext ** pb)
Definition at line 5622 of file utils.c.
Referenced by chunk_end(), close_file(), close_slave(), copy_moof(), dash_flush(), dash_free(), ff_img_read_packet(), fifo_thread_write_trailer(), find_index_range(), free_playlist_list(), hds_free(), hls_encryption_start(), hls_read_seek(), hls_window(), hls_write_packet(), hls_write_trailer(), mov_read_close(), open_input(), parse_fragment(), parse_playlist(), read_close(), read_data(), read_header(), recheck_discard_flags(), seg_free(), seg_init(), seg_write_header(), seg_write_trailer(), segment_end(), shift_data(), update_init_section(), webm_chunk_write_header(), write_abst(), write_manifest(), and write_packet().
ff_parse_creation_time_metadata()
int ff_parse_creation_time_metadata (AVFormatContext * s, int64_t * timestamp, int return_seconds)
Parse creation_time in AVFormatContext metadata if exists and warn if the parsing fails.
Parameters
s AVFormatContext
timestamp parsed timestamp in microseconds, only set on successful parsing
return_seconds set this to get the number of seconds in timestamp instead of microseconds
Returns
1 if OK, 0 if the metadata was not present, AVERROR(EINVAL) on parse error
Definition at line 5629 of file utils.c.
Referenced by asf_write_header1(), dv_init_mux(), ff_standardize_creation_time(), ffm_write_header(), gxf_write_umf_material_description(), mkv_write_header(), mov_write_header(), and mxf_write_header().
ff_standardize_creation_time()
int ff_standardize_creation_time (AVFormatContext * s)
Standardize creation_time metadata in AVFormatContext to an ISO-8601 timestamp string.
Parameters
s AVFormatContext
Returns
<0 on error
Definition at line 5646 of file utils.c.
Referenced by caf_write_header(), ff_ape_write_tag(), ff_id3v2_write_metadata(), lrc_write_header(), smjpeg_write_header(), write_globalinfo(), write_metadata(), and write_table_entries_attrib().
ff_get_packet_palette()
int ff_get_packet_palette (AVFormatContext * s, AVPacket * pkt, int ret, uint32_t * palette)
Retrieves the palette from a packet, either from side data, or appended to the video data in the packet itself (raw video only).
It is commonly used after a call to ff_reshuffle_raw_rgb().
Use 0 for the ret parameter to check for side data only.
Parameters
pkt pointer to packet before calling ff_reshuffle_raw_rgb()
ret return value from ff_reshuffle_raw_rgb(), or 0
palette pointer to palette buffer
Returns
negative error code or 1 if the packet has a palette, else 0
Definition at line 5655 of file utils.c.
Referenced by avi_write_packet(), and mov_write_packet().
ff_bprint_to_codecpar_extradata()
int ff_bprint_to_codecpar_extradata (AVCodecParameters * par, struct AVBPrint * buf)
Finalize buf into extradata and set its size appropriately.
Definition at line 5680 of file utils.c.
Referenced by ass_read_header(), jacosub_read_header(), sami_read_header(), and subviewer_read_header().
Variable Documentation
av_format_ffversion
const char av_format_ffversion[] = "FFmpeg version " FFMPEG_VERSION
Definition at line 56 of file utils.c.