FFmpeg: libavcodec/c93.c File Reference
c93.c File Reference
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
Data Structures
struct C93DecoderContext
Macros
#define WIDTH 320
#define HEIGHT 192
#define C93_HAS_PALETTE 0x01
#define C93_FIRST_FRAME 0x02
Enumerations
enum C93BlockType {
C93_8X8_FROM_PREV = 0x02, C93_4X4_FROM_PREV = 0x06, C93_4X4_FROM_CURR = 0x07, C93_8X8_2COLOR = 0x08,
C93_4X4_2COLOR = 0x0A, C93_4X4_4COLOR_GRP = 0x0B, C93_4X4_4COLOR = 0x0D, C93_NOOP = 0x0E,
C93_8X8_INTRA = 0x0F
}
Functions
static av_cold int decode_end (AVCodecContext *avctx)
static av_cold int decode_init (AVCodecContext *avctx)
static int copy_block (AVCodecContext *avctx, uint8_t *to, uint8_t *from, int offset, int height, int stride)
static void draw_n_color (uint8_t *out, int stride, int width, int height, int bpp, uint8_t cols[4], uint8_t grps[4], uint32_t col)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
Variables
AVCodec ff_c93_decoder
Macro Definition Documentation
WIDTH
#define WIDTH 320
Definition at line 43 of file c93.c.
Referenced by copy_block(), and decode_frame().
HEIGHT
#define HEIGHT 192
Definition at line 44 of file c93.c.
Referenced by copy_block(), and decode_frame().
C93_HAS_PALETTE
#define C93_HAS_PALETTE 0x01
Definition at line 46 of file c93.c.
Referenced by decode_frame().
C93_FIRST_FRAME
#define C93_FIRST_FRAME 0x02
Definition at line 47 of file c93.c.
Referenced by decode_frame().
Enumeration Type Documentation
C93BlockType
enum C93BlockType
Enumerator
C93_8X8_FROM_PREV
C93_4X4_FROM_PREV
C93_4X4_FROM_CURR
C93_8X8_2COLOR
C93_4X4_2COLOR
C93_4X4_4COLOR_GRP
C93_4X4_4COLOR
C93_NOOP
C93_8X8_INTRA
Definition at line 31 of file c93.c.
Function Documentation
decode_end()
static av_cold int decode_end (AVCodecContext * avctx) static
Definition at line 49 of file c93.c.
Referenced by decode_init().
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 59 of file c93.c.
copy_block()
static int copy_block (AVCodecContext * avctx, uint8_t * to, uint8_t * from, int offset, int height, int stride) inline static
Definition at line 74 of file c93.c.
Referenced by decode_frame().
draw_n_color()
static void draw_n_color (uint8_t * out, int stride, int width, int height, int bpp, uint8_t cols[4], uint8_t grps[4], uint32_t col) inline static
Definition at line 108 of file c93.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 124 of file c93.c.
Variable Documentation
ff_c93_decoder
AVCodec ff_c93_decoder
Initial value:
= {
    .name           = "c93",
    .long_name      = NULL_IF_CONFIG_SMALL("Interplay C93"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_C93,
    .priv_data_size = sizeof(C93DecoderContext),
    .init           = decode_init,
    .close          = decode_end,
    .decode         = decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 262 of file c93.c.