FFmpeg: libavutil/thread.h File Reference
thread.h File Reference
#include "config.h"
Macros
#define USE_ATOMICS 1
#define AVMutex char
#define ff_mutex_init(mutex, attr) (0)
#define ff_mutex_lock(mutex) (0)
#define ff_mutex_unlock(mutex) (0)
#define ff_mutex_destroy(mutex) (0)
#define AVOnce char
#define AV_ONCE_INIT 0
Functions
static int ff_thread_once (char *control, void(*routine)(void))
Macro Definition Documentation
USE_ATOMICS
#define USE_ATOMICS 1
Definition at line 149 of file thread.h.
AVMutex
#define AVMutex char
Definition at line 151 of file thread.h.
ff_mutex_init
#define ff_mutex_init (mutex, attr) (0)
Definition at line 153 of file thread.h.
Referenced by av_buffer_pool_init(), and av_buffer_pool_init2().
ff_mutex_lock
#define ff_mutex_lock (mutex) (0)
Definition at line 154 of file thread.h.
Referenced by av_buffer_pool_get(), and pool_release_buffer().
ff_mutex_unlock
#define ff_mutex_unlock (mutex) (0)
Definition at line 155 of file thread.h.
Referenced by av_buffer_pool_get(), and pool_release_buffer().
ff_mutex_destroy
#define ff_mutex_destroy (mutex) (0)
Definition at line 156 of file thread.h.
Referenced by buffer_pool_free().
AVOnce
#define AVOnce char
Definition at line 158 of file thread.h.
AV_ONCE_INIT
#define AV_ONCE_INIT 0
Definition at line 159 of file thread.h.
Function Documentation
ff_thread_once()
static int ff_thread_once (char * control, void(*)(void) routine) inline static
Definition at line 161 of file thread.h.
Referenced by aac_decode_init(), aac_encode_init(), ff_ebur128_init(), and ff_h264_decode_init().