FFmpeg: libavfilter/fifo.c File Reference
fifo.c File Reference
FIFO buffering filter.
#include "libavutil/avassert.h"
#include "libavutil/channel_layout.h"
#include "libavutil/common.h"
#include "libavutil/mathematics.h"
#include "libavutil/samplefmt.h"
#include "audio.h"
#include "avfilter.h"
#include "internal.h"
#include "video.h"
Data Structures
struct Buf
struct FifoContext
Functions
static av_cold int init (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
static int add_to_queue (AVFilterLink *inlink, AVFrame *frame)
static void queue_pop (FifoContext *s)
static void buffer_offset (AVFilterLink *link, AVFrame *frame, int offset)
Move data pointers and pts offset samples forward.
static int calc_ptr_alignment (AVFrame *frame)
static int return_audio_frame (AVFilterContext *ctx)
static int request_frame (AVFilterLink *outlink)
Variables
static const AVFilterPad avfilter_vf_fifo_inputs []
static const AVFilterPad avfilter_vf_fifo_outputs []
AVFilter ff_vf_fifo
static const AVFilterPad avfilter_af_afifo_inputs []
static const AVFilterPad avfilter_af_afifo_outputs []
AVFilter ff_af_afifo
Detailed Description
FIFO buffering filter.
Definition in file fifo.c.
Function Documentation
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 54 of file fifo.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 62 of file fifo.c.
add_to_queue()
static int add_to_queue (AVFilterLink * inlink, AVFrame * frame) static
Definition at line 76 of file fifo.c.
queue_pop()
static void queue_pop (FifoContext * s) static
Definition at line 92 of file fifo.c.
Referenced by request_frame(), and return_audio_frame().
buffer_offset()
static void buffer_offset (AVFilterLink * link, AVFrame * frame, int offset) static
Move data pointers and pts offset samples forward.
Definition at line 104 of file fifo.c.
Referenced by return_audio_frame().
calc_ptr_alignment()
static int calc_ptr_alignment (AVFrame * frame) static
Definition at line 129 of file fifo.c.
Referenced by return_audio_frame().
return_audio_frame()
static int return_audio_frame (AVFilterContext * ctx) static
Definition at line 146 of file fifo.c.
Referenced by request_frame().
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 230 of file fifo.c.
Variable Documentation
avfilter_vf_fifo_inputs
const AVFilterPad avfilter_vf_fifo_inputs[] static
Initial value:
= {
    {
        .name             = "default",
        .type             = AVMEDIA_TYPE_VIDEO,
        .filter_frame     = add_to_queue,
    },
    { NULL }
}
Definition at line 255 of file fifo.c.
avfilter_vf_fifo_outputs
const AVFilterPad avfilter_vf_fifo_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .request_frame = request_frame,
    },
    { NULL }
}
Definition at line 264 of file fifo.c.
ff_vf_fifo
AVFilter ff_vf_fifo
Initial value:
= {
    .name      = "fifo",
    .description = NULL_IF_CONFIG_SMALL("Buffer input images and send them when they are requested."),
    .init      = init,
    .uninit    = uninit,
    .priv_size = sizeof(FifoContext),
    .inputs    = avfilter_vf_fifo_inputs,
    .outputs   = avfilter_vf_fifo_outputs,
}
Definition at line 273 of file fifo.c.
avfilter_af_afifo_inputs
const AVFilterPad avfilter_af_afifo_inputs[] static
Initial value:
= {
    {
        .name             = "default",
        .type             = AVMEDIA_TYPE_AUDIO,
        .filter_frame     = add_to_queue,
    },
    { NULL }
}
Definition at line 286 of file fifo.c.
avfilter_af_afifo_outputs
const AVFilterPad avfilter_af_afifo_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_AUDIO,
        .request_frame = request_frame,
    },
    { NULL }
}
Definition at line 295 of file fifo.c.
ff_af_afifo
AVFilter ff_af_afifo
Initial value:
= {
    .name        = "afifo",
    .description = NULL_IF_CONFIG_SMALL("Buffer input frames and send them when they are requested."),
    .init      = init,
    .uninit    = uninit,
    .priv_size = sizeof(FifoContext),
    .inputs    = avfilter_af_afifo_inputs,
    .outputs   = avfilter_af_afifo_outputs,
}
Definition at line 304 of file fifo.c.