FFmpeg: libavcodec/flv.h File Reference
flv.h File Reference
#include "get_bits.h"
#include "mpegvideo.h"
#include "put_bits.h"
Functions
void ff_flv_encode_picture_header (MpegEncContext *s, int picture_number)
void ff_flv2_encode_ac_esc (PutBitContext *pb, int slevel, int level, int run, int last)
int ff_flv_decode_picture_header (MpegEncContext *s)
Function Documentation
ff_flv_encode_picture_header()
void ff_flv_encode_picture_header (MpegEncContext * s, int picture_number)
Definition at line 27 of file flvenc.c.
Referenced by encode_picture().
ff_flv2_encode_ac_esc()
void ff_flv2_encode_ac_esc (PutBitContext * pb, int slevel, int level, int run, int last)
Definition at line 75 of file flvenc.c.
Referenced by h263_encode_block().
ff_flv_decode_picture_header()
int ff_flv_decode_picture_header (MpegEncContext * s)
Definition at line 28 of file flvdec.c.
Referenced by ff_h263_decode_frame().