FFmpeg: libavcodec/libcelt_dec.c File Reference
libcelt_dec.c File Reference
#include <celt/celt.h>
#include <celt/celt_header.h>
#include "avcodec.h"
#include "internal.h"
#include "libavutil/intreadwrite.h"
Data Structures
struct libcelt_context
Functions
static int ff_celt_error_to_averror (int err)
static int ff_celt_bitstream_version_hack (CELTMode *mode)
static av_cold int libcelt_dec_init (AVCodecContext *c)
static av_cold int libcelt_dec_close (AVCodecContext *c)
static int libcelt_dec_decode (AVCodecContext *c, void *data, int *got_frame_ptr, AVPacket *pkt)
Variables
AVCodec ff_libcelt_decoder
Function Documentation
ff_celt_error_to_averror()
static int ff_celt_error_to_averror (int err) static
Definition at line 34 of file libcelt_dec.c.
Referenced by libcelt_dec_decode(), and libcelt_dec_init().
ff_celt_bitstream_version_hack()
static int ff_celt_bitstream_version_hack (CELTMode * mode) static
Definition at line 52 of file libcelt_dec.c.
Referenced by libcelt_dec_init().
libcelt_dec_init()
static av_cold int libcelt_dec_init (AVCodecContext * c) static
Definition at line 59 of file libcelt_dec.c.
libcelt_dec_close()
static av_cold int libcelt_dec_close (AVCodecContext * c) static
Definition at line 96 of file libcelt_dec.c.
libcelt_dec_decode()
static int libcelt_dec_decode (AVCodecContext * c, void * data, int * got_frame_ptr, AVPacket * pkt) static
Definition at line 105 of file libcelt_dec.c.
Variable Documentation
ff_libcelt_decoder
AVCodec ff_libcelt_decoder
Initial value:
= {
    .name           = "libcelt",
    .long_name      = NULL_IF_CONFIG_SMALL("Xiph CELT decoder using libcelt"),
    .type           = AVMEDIA_TYPE_AUDIO,
    .id             = AV_CODEC_ID_CELT,
    .priv_data_size = sizeof(struct libcelt_context),
    .init           = libcelt_dec_init,
    .close          = libcelt_dec_close,
    .decode         = libcelt_dec_decode,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 130 of file libcelt_dec.c.