FFmpeg: libavcodec/libfdk-aacenc.c File Reference
libfdk-aacenc.c File Reference
#include <fdk-aac/aacenc_lib.h>
#include "libavutil/channel_layout.h"
#include "libavutil/common.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "audio_frame_queue.h"
#include "internal.h"
Data Structures
struct AACContext
main AAC context
Functions
static const char * aac_get_error (AACENC_ERROR err)
static int aac_encode_close (AVCodecContext *avctx)
static av_cold int aac_encode_init (AVCodecContext *avctx)
static int aac_encode_frame (AVCodecContext *avctx, AVPacket *avpkt, const AVFrame *frame, int *got_packet_ptr)
Variables
static const AVOption aac_enc_options []
static const AVClass aac_enc_class
static const AVProfile profiles []
static const AVCodecDefault aac_encode_defaults []
static const uint64_t aac_channel_layout []
static const int aac_sample_rates []
AVCodec ff_libfdk_aac_encoder
Function Documentation
aac_get_error()
static const char* aac_get_error (AACENC_ERROR err) static
Definition at line 60 of file libfdk-aacenc.c.
Referenced by aac_encode_frame(), and aac_encode_init().
aac_encode_close()
static int aac_encode_close (AVCodecContext * avctx) static
Definition at line 92 of file libfdk-aacenc.c.
Referenced by aac_encode_init().
aac_encode_init()
static av_cold int aac_encode_init (AVCodecContext * avctx) static
Definition at line 104 of file libfdk-aacenc.c.
aac_encode_frame()
static int aac_encode_frame (AVCodecContext * avctx, AVPacket * avpkt, const AVFrame * frame, int * got_packet_ptr) static
Definition at line 309 of file libfdk-aacenc.c.
Variable Documentation
aac_enc_options
const AVOption aac_enc_options[] static
Initial value:
= {
    { "afterburner", "Afterburner (improved quality)", 0x42, AV_OPT_TYPE_INT, { .i64 = 1 }, 0, 1, AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_ENCODING_PARAM },
    { "eld_sbr", "Enable SBR for ELD (for SBR in other configurations, use the -profile parameter)", 0x42, AV_OPT_TYPE_INT, { .i64 = 0 }, 0, 1, AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_ENCODING_PARAM },
    { "signaling", "SBR/PS signaling style", 0x42, AV_OPT_TYPE_INT, { .i64 = -1 }, -1, 2, AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_ENCODING_PARAM, "signaling" },
    { "default", "Choose signaling implicitly (explicit hierarchical by default, implicit if global header is disabled)", 0, AV_OPT_TYPE_CONST, { .i64 = -1 }, 0, 0, AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_ENCODING_PARAM, "signaling" },
    { "implicit", "Implicit backwards compatible signaling", 0, AV_OPT_TYPE_CONST, { .i64 = 0 }, 0, 0, AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_ENCODING_PARAM, "signaling" },
    { "explicit_sbr", "Explicit SBR, implicit PS signaling", 0, AV_OPT_TYPE_CONST, { .i64 = 1 }, 0, 0, AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_ENCODING_PARAM, "signaling" },
    { "explicit_hierarchical", "Explicit hierarchical signaling", 0, AV_OPT_TYPE_CONST, { .i64 = 2 }, 0, 0, AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_ENCODING_PARAM, "signaling" },
    { "latm", "Output LATM/LOAS encapsulated data", 0x42, AV_OPT_TYPE_INT, { .i64 = 0 }, 0, 1, AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_ENCODING_PARAM },
    { "header_period", "StreamMuxConfig and PCE repetition period (in frames)", 0x42, AV_OPT_TYPE_INT, { .i64 = 0 }, 0, 0xffff, AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_ENCODING_PARAM },
    { "vbr", "VBR mode (1-5)", 0x42, AV_OPT_TYPE_INT, { .i64 = 0 }, 0, 5, AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_ENCODING_PARAM },
    { NULL }
}
Definition at line 42 of file libfdk-aacenc.c.
aac_enc_class
const AVClass aac_enc_class static
Initial value:
= {
    "libfdk_aac", av_default_item_name, aac_enc_options, LIBAVUTIL_VERSION_INT
}
Definition at line 56 of file libfdk-aacenc.c.
profiles
const AVProfile profiles[] static
Initial value:
= {
    { FF_PROFILE_AAC_LOW,   "LC"       },
    { FF_PROFILE_AAC_HE,    "HE-AAC"   },
    { FF_PROFILE_AAC_HE_V2, "HE-AACv2" },
    { FF_PROFILE_AAC_LD,    "LD"       },
    { FF_PROFILE_AAC_ELD,   "ELD"      },
    { FF_PROFILE_UNKNOWN },
}
Definition at line 378 of file libfdk-aacenc.c.
Referenced by vaapi_encode_config_attributes(), and vpx_free().
aac_encode_defaults
const AVCodecDefault aac_encode_defaults[] static
Initial value:
= {
    { "b", "0" },
    { NULL }
}
Definition at line 387 of file libfdk-aacenc.c.
aac_channel_layout
const uint64_t aac_channel_layout[] static
Initial value:
= {
    AV_CH_LAYOUT_MONO,
    AV_CH_LAYOUT_STEREO,
    AV_CH_LAYOUT_SURROUND,
    AV_CH_LAYOUT_4POINT0,
    AV_CH_LAYOUT_5POINT0_BACK,
    AV_CH_LAYOUT_5POINT1_BACK,
    0,
}
Definition at line 392 of file libfdk-aacenc.c.
aac_sample_rates
const int aac_sample_rates[] static
Initial value:
= {
    96000, 88200, 64000, 48000, 44100, 32000,
    24000, 22050, 16000, 12000, 11025, 8000, 0
}
Definition at line 406 of file libfdk-aacenc.c.
ff_libfdk_aac_encoder
AVCodec ff_libfdk_aac_encoder
Initial value:
= {
    .name                  = "libfdk_aac",
    .long_name             = NULL_IF_CONFIG_SMALL("Fraunhofer FDK AAC"),
    .type                  = AVMEDIA_TYPE_AUDIO,
    .id                    = AV_CODEC_ID_AAC,
    .priv_data_size        = sizeof(AACContext),
    .init                  = aac_encode_init,
    .encode2               = aac_encode_frame,
    .close                 = aac_encode_close,
    .capabilities          = AV_CODEC_CAP_SMALL_LAST_FRAME | AV_CODEC_CAP_DELAY,
    .sample_fmts           = (const enum AVSampleFormat[]){ AV_SAMPLE_FMT_S16,
                                                            AV_SAMPLE_FMT_NONE },
    .priv_class            = &aac_enc_class,
    .defaults              = aac_encode_defaults,
    .profiles              = profiles,
    .supported_samplerates = aac_sample_rates,
    .channel_layouts       = aac_channel_layout,
}
Definition at line 411 of file libfdk-aacenc.c.