FFmpeg: libavcodec/libgsmenc.c File Reference
libgsmenc.c File Reference
Interface to libgsm for GSM encoding.
#include "config.h"
#include <gsm/gsm.h>
#include "libavutil/common.h"
#include "avcodec.h"
#include "internal.h"
#include "gsm.h"
Functions
static av_cold int libgsm_encode_close (AVCodecContext *avctx)
static av_cold int libgsm_encode_init (AVCodecContext *avctx)
static int libgsm_encode_frame (AVCodecContext *avctx, AVPacket *avpkt, const AVFrame *frame, int *got_packet_ptr)
Detailed Description
Interface to libgsm for GSM encoding.
Definition in file libgsmenc.c.
Function Documentation
libgsm_encode_close()
static av_cold int libgsm_encode_close (AVCodecContext * avctx) static
Definition at line 43 of file libgsmenc.c.
Referenced by libgsm_encode_frame(), and libgsm_encode_init().
libgsm_encode_init()
static av_cold int libgsm_encode_init (AVCodecContext * avctx) static
Definition at line 49 of file libgsmenc.c.
Referenced by libgsm_encode_frame().
libgsm_encode_frame()
static int libgsm_encode_frame (AVCodecContext * avctx, AVPacket * avpkt, const AVFrame * frame, int * got_packet_ptr) static
Definition at line 94 of file libgsmenc.c.