FFmpeg: libavcodec/libgsmdec.c File Reference
libgsmdec.c File Reference
Interface to libgsm for GSM decoding.
#include "config.h"
#include <gsm/gsm.h>
#include "libavutil/channel_layout.h"
#include "libavutil/common.h"
#include "avcodec.h"
#include "internal.h"
#include "gsm.h"
Data Structures
struct LibGSMDecodeContext
Functions
static av_cold int libgsm_decode_init (AVCodecContext *avctx)
static av_cold int libgsm_decode_close (AVCodecContext *avctx)
static int libgsm_decode_frame (AVCodecContext *avctx, void *data, int *got_frame_ptr, AVPacket *avpkt)
static void libgsm_flush (AVCodecContext *avctx)
Detailed Description
Interface to libgsm for GSM decoding.
Definition in file libgsmdec.c.
Function Documentation
libgsm_decode_init()
static av_cold int libgsm_decode_init (AVCodecContext * avctx) static
Definition at line 48 of file libgsmdec.c.
Referenced by libgsm_flush().
libgsm_decode_close()
static av_cold int libgsm_decode_close (AVCodecContext * avctx) static
Definition at line 75 of file libgsmdec.c.
Referenced by libgsm_flush().
libgsm_decode_frame()
static int libgsm_decode_frame (AVCodecContext * avctx, void * data, int * got_frame_ptr, AVPacket * avpkt) static
Definition at line 83 of file libgsmdec.c.
Referenced by libgsm_flush().
libgsm_flush()
static void libgsm_flush (AVCodecContext * avctx) static
Definition at line 116 of file libgsmdec.c.