FFmpeg: libavcodec/libmp3lame.c File Reference
libmp3lame.c File Reference
Interface to libmp3lame for mp3 encoding.
#include <lame/lame.h>
#include "libavutil/channel_layout.h"
#include "libavutil/common.h"
#include "libavutil/float_dsp.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/log.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "audio_frame_queue.h"
#include "internal.h"
#include "mpegaudio.h"
#include "mpegaudiodecheader.h"
Data Structures
struct LAMEContext
Macros
#define BUFFER_SIZE (7200 + 2 * MPA_FRAME_SIZE + MPA_FRAME_SIZE / 4+1000)
#define ENCODE_BUFFER(func, buf_type, buf_name)
#define OFFSET(x) offsetof(LAMEContext, x)
#define AE AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Functions
static int realloc_buffer (LAMEContext *s)
static av_cold int mp3lame_encode_close (AVCodecContext *avctx)
static av_cold int mp3lame_encode_init (AVCodecContext *avctx)
static int mp3lame_encode_frame (AVCodecContext *avctx, AVPacket *avpkt, const AVFrame *frame, int *got_packet_ptr)
Variables
static const AVOption options []
static const AVClass libmp3lame_class
static const AVCodecDefault libmp3lame_defaults []
static const int libmp3lame_sample_rates []
AVCodec ff_libmp3lame_encoder
Detailed Description
Interface to libmp3lame for mp3 encoding.
Definition in file libmp3lame.c.
Macro Definition Documentation
BUFFER_SIZE
#define BUFFER_SIZE (7200 + 2 * MPA_FRAME_SIZE + MPA_FRAME_SIZE / 4+1000)
Definition at line 41 of file libmp3lame.c.
Referenced by realloc_buffer().
ENCODE_BUFFER
#define ENCODE_BUFFER (func, buf_type, buf_name)
Value:
do {                        \
    lame_result = func(s->gfp,                                              \
                       (const buf_type *)buf_name[0],                       \
                       (const buf_type *)buf_name[1], frame->nb_samples,    \
                       s->buffer + s->buffer_index,                         \
                       s->buffer_size - s->buffer_index);                   \
} while (0)
Definition at line 180 of file libmp3lame.c.
Referenced by mp3lame_encode_frame().
OFFSET
#define OFFSET (x) offsetof(LAMEContext, x)
Definition at line 307 of file libmp3lame.c.
AE
#define AE AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 308 of file libmp3lame.c.
Function Documentation
realloc_buffer()
static int realloc_buffer (LAMEContext * s) static
Definition at line 60 of file libmp3lame.c.
Referenced by mp3lame_encode_frame(), and mp3lame_encode_init().
mp3lame_encode_close()
static av_cold int mp3lame_encode_close (AVCodecContext * avctx) static
Definition at line 76 of file libmp3lame.c.
Referenced by mp3lame_encode_init().
mp3lame_encode_init()
static av_cold int mp3lame_encode_init (AVCodecContext * avctx) static
Definition at line 91 of file libmp3lame.c.
mp3lame_encode_frame()
static int mp3lame_encode_frame (AVCodecContext * avctx, AVPacket * avpkt, const AVFrame * frame, int * got_packet_ptr) static
Definition at line 188 of file libmp3lame.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "reservoir",    "use bit reservoir", OFFSET(reservoir),    AV_OPT_TYPE_BOOL, { .i64 = 1 }, 0, 1, AE },
    { "joint_stereo", "use joint stereo",  OFFSET(joint_stereo), AV_OPT_TYPE_BOOL, { .i64 = 1 }, 0, 1, AE },
    { "abr",          "use ABR",           OFFSET(abr),          AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, AE },
    { NULL },
}
Definition at line 309 of file libmp3lame.c.
libmp3lame_class
const AVClass libmp3lame_class static
Initial value:
= {
    .class_name = "libmp3lame encoder",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 316 of file libmp3lame.c.
libmp3lame_defaults
const AVCodecDefault libmp3lame_defaults[] static
Initial value:
= {
    { "b",          "0" },
    { NULL },
}
Definition at line 323 of file libmp3lame.c.
libmp3lame_sample_rates
const int libmp3lame_sample_rates[] static
Initial value:
= {
    44100, 48000,  32000, 22050, 24000, 16000, 11025, 12000, 8000, 0
}
Definition at line 328 of file libmp3lame.c.
ff_libmp3lame_encoder
AVCodec ff_libmp3lame_encoder
Initial value:
= {
    .name                  = "libmp3lame",
    .long_name             = NULL_IF_CONFIG_SMALL("libmp3lame MP3 (MPEG audio layer 3)"),
    .type                  = AVMEDIA_TYPE_AUDIO,
    .id                    = AV_CODEC_ID_MP3,
    .priv_data_size        = sizeof(LAMEContext),
    .init                  = mp3lame_encode_init,
    .encode2               = mp3lame_encode_frame,
    .close                 = mp3lame_encode_close,
    .capabilities          = AV_CODEC_CAP_DELAY | AV_CODEC_CAP_SMALL_LAST_FRAME,
    .sample_fmts           = (const enum AVSampleFormat[]) { AV_SAMPLE_FMT_S32P,
                                                             AV_SAMPLE_FMT_FLTP,
                                                             AV_SAMPLE_FMT_S16P,
                                                             AV_SAMPLE_FMT_NONE },
    .supported_samplerates = libmp3lame_sample_rates,
    .channel_layouts       = (const uint64_t[]) { AV_CH_LAYOUT_MONO,
                                                  AV_CH_LAYOUT_STEREO,
                                                  0 },
    .priv_class            = &libmp3lame_class,
    .defaults              = libmp3lame_defaults,
}
Definition at line 332 of file libmp3lame.c.