FFmpeg: libavcodec/libopenjpegenc.c File Reference
libopenjpegenc.c File Reference
JPEG 2000 encoder using libopenjpeg.
#include "libavutil/avassert.h"
#include "libavutil/common.h"
#include "libavutil/imgutils.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "internal.h"
#include <openjpeg.h>
Data Structures
struct LibOpenJPEGContext
Macros
#define OPENJPEG_MAJOR_VERSION 1
#define OPJ(x) x
#define OFFSET(x) offsetof(LibOpenJPEGContext, x)
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Functions
static void error_callback (const char *msg, void *data)
static void warning_callback (const char *msg, void *data)
static void info_callback (const char *msg, void *data)
static void cinema_parameters (opj_cparameters_t *p)
static opj_image_t * mj2_create_image (AVCodecContext *avctx, opj_cparameters_t *parameters)
static av_cold int libopenjpeg_encode_init (AVCodecContext *avctx)
static int libopenjpeg_copy_packed8 (AVCodecContext *avctx, const AVFrame *frame, opj_image_t *image)
static int libopenjpeg_copy_packed12 (AVCodecContext *avctx, const AVFrame *frame, opj_image_t *image)
static int libopenjpeg_copy_packed16 (AVCodecContext *avctx, const AVFrame *frame, opj_image_t *image)
static int libopenjpeg_copy_unpacked8 (AVCodecContext *avctx, const AVFrame *frame, opj_image_t *image)
static int libopenjpeg_copy_unpacked16 (AVCodecContext *avctx, const AVFrame *frame, opj_image_t *image)
static int libopenjpeg_encode_frame (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *frame, int *got_packet)
static av_cold int libopenjpeg_encode_close (AVCodecContext *avctx)
Variables
static const AVOption options []
static const AVClass openjpeg_class
AVCodec ff_libopenjpeg_encoder
Detailed Description
JPEG 2000 encoder using libopenjpeg.
Definition in file libopenjpegenc.c.
Macro Definition Documentation
OPENJPEG_MAJOR_VERSION
#define OPENJPEG_MAJOR_VERSION 1
Definition at line 49 of file libopenjpegenc.c.
OPJ
#define OPJ (x) x
Definition at line 50 of file libopenjpegenc.c.
Referenced by cinema_parameters(), and mj2_create_image().
OFFSET
#define OFFSET (x) offsetof(LibOpenJPEGContext, x)
Definition at line 820 of file libopenjpegenc.c.
VE
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 821 of file libopenjpegenc.c.
Function Documentation
error_callback()
static void error_callback (const char * msg, void * data) static
Definition at line 73 of file libopenjpegenc.c.
Referenced by libopenjpeg_encode_frame().
warning_callback()
static void warning_callback (const char * msg, void * data) static
Definition at line 78 of file libopenjpegenc.c.
Referenced by libopenjpeg_encode_frame().
info_callback()
static void info_callback (const char * msg, void * data) static
Definition at line 83 of file libopenjpegenc.c.
Referenced by libopenjpeg_encode_frame().
cinema_parameters()
static void cinema_parameters (opj_cparameters_t * p) static
Definition at line 160 of file libopenjpegenc.c.
Referenced by libopenjpeg_encode_init().
mj2_create_image()
static opj_image_t* mj2_create_image (AVCodecContext * avctx, opj_cparameters_t * parameters) static
Definition at line 197 of file libopenjpegenc.c.
Referenced by libopenjpeg_encode_frame(), and libopenjpeg_encode_init().
libopenjpeg_encode_init()
static av_cold int libopenjpeg_encode_init (AVCodecContext * avctx) static
Definition at line 302 of file libopenjpegenc.c.
libopenjpeg_copy_packed8()
static int libopenjpeg_copy_packed8 (AVCodecContext * avctx, const AVFrame * frame, opj_image_t * image) static
Definition at line 393 of file libopenjpegenc.c.
Referenced by libopenjpeg_encode_frame().
libopenjpeg_copy_packed12()
static int libopenjpeg_copy_packed12 (AVCodecContext * avctx, const AVFrame * frame, opj_image_t * image) static
Definition at line 433 of file libopenjpegenc.c.
Referenced by libopenjpeg_encode_frame().
libopenjpeg_copy_packed16()
static int libopenjpeg_copy_packed16 (AVCodecContext * avctx, const AVFrame * frame, opj_image_t * image) static
Definition at line 472 of file libopenjpegenc.c.
Referenced by libopenjpeg_encode_frame().
libopenjpeg_copy_unpacked8()
static int libopenjpeg_copy_unpacked8 (AVCodecContext * avctx, const AVFrame * frame, opj_image_t * image) static
Definition at line 512 of file libopenjpegenc.c.
Referenced by libopenjpeg_encode_frame().
libopenjpeg_copy_unpacked16()
static int libopenjpeg_copy_unpacked16 (AVCodecContext * avctx, const AVFrame * frame, opj_image_t * image) static
Definition at line 553 of file libopenjpegenc.c.
Referenced by libopenjpeg_encode_frame().
libopenjpeg_encode_frame()
static int libopenjpeg_encode_frame (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * frame, int * got_packet) static
Definition at line 596 of file libopenjpegenc.c.
libopenjpeg_encode_close()
static av_cold int libopenjpeg_encode_close (AVCodecContext * avctx) static
Definition at line 809 of file libopenjpegenc.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "format",        "Codec Format",      OFFSET(format),        AV_OPT_TYPE_INT,   { .i64 = OPJ(CODEC_JP2)   }, OPJ(CODEC_J2K), OPJ(CODEC_JP2),   VE, "format"      },
    { "j2k",           NULL,                0,                     AV_OPT_TYPE_CONST, { .i64 = OPJ(CODEC_J2K)   }, 0,         0,           VE, "format"      },
    { "jp2",           NULL,                0,                     AV_OPT_TYPE_CONST, { .i64 = OPJ(CODEC_JP2)   }, 0,         0,           VE, "format"      },
    { "profile",       NULL,                OFFSET(profile),       AV_OPT_TYPE_INT,   { .i64 = OPJ(STD_RSIZ)    }, OPJ(STD_RSIZ),  OPJ(CINEMA4K),    VE, "profile"     },
    { "jpeg2000",      NULL,                0,                     AV_OPT_TYPE_CONST, { .i64 = OPJ(STD_RSIZ)    }, 0,         0,           VE, "profile"     },
    { "cinema2k",      NULL,                0,                     AV_OPT_TYPE_CONST, { .i64 = OPJ(CINEMA2K)    }, 0,         0,           VE, "profile"     },
    { "cinema4k",      NULL,                0,                     AV_OPT_TYPE_CONST, { .i64 = OPJ(CINEMA4K)    }, 0,         0,           VE, "profile"     },
    { "cinema_mode",   "Digital Cinema",    OFFSET(cinema_mode),   AV_OPT_TYPE_INT,   { .i64 = OPJ(OFF)         }, OPJ(OFF),       OPJ(CINEMA4K_24), VE, "cinema_mode" },
    { "off",           NULL,                0,                     AV_OPT_TYPE_CONST, { .i64 = OPJ(OFF)         }, 0,         0,           VE, "cinema_mode" },
    { "2k_24",         NULL,                0,                     AV_OPT_TYPE_CONST, { .i64 = OPJ(CINEMA2K_24) }, 0,         0,           VE, "cinema_mode" },
    { "2k_48",         NULL,                0,                     AV_OPT_TYPE_CONST, { .i64 = OPJ(CINEMA2K_48) }, 0,         0,           VE, "cinema_mode" },
    { "4k_24",         NULL,                0,                     AV_OPT_TYPE_CONST, { .i64 = OPJ(CINEMA4K_24) }, 0,         0,           VE, "cinema_mode" },
    { "prog_order",    "Progression Order", OFFSET(prog_order),    AV_OPT_TYPE_INT,   { .i64 = OPJ(LRCP)    }, OPJ(LRCP),  OPJ(CPRL),    VE, "prog_order"  },
    { "lrcp",          NULL,                0,                     AV_OPT_TYPE_CONST, { .i64 = OPJ(LRCP)    }, 0,         0,           VE, "prog_order"  },
    { "rlcp",          NULL,                0,                     AV_OPT_TYPE_CONST, { .i64 = OPJ(RLCP)    }, 0,         0,           VE, "prog_order"  },
    { "rpcl",          NULL,                0,                     AV_OPT_TYPE_CONST, { .i64 = OPJ(RPCL)    }, 0,         0,           VE, "prog_order"  },
    { "pcrl",          NULL,                0,                     AV_OPT_TYPE_CONST, { .i64 = OPJ(PCRL)    }, 0,         0,           VE, "prog_order"  },
    { "cprl",          NULL,                0,                     AV_OPT_TYPE_CONST, { .i64 = OPJ(CPRL)    }, 0,         0,           VE, "prog_order"  },
    { "numresolution", NULL,                OFFSET(numresolution), AV_OPT_TYPE_INT,   { .i64 = 0           }, 0,         INT_MAX,     VE                },
    { "numlayers",     NULL,                OFFSET(numlayers),     AV_OPT_TYPE_INT,   { .i64 = 1           }, 1,         10,          VE                },
    { "disto_alloc",   NULL,                OFFSET(disto_alloc),   AV_OPT_TYPE_INT,   { .i64 = 1           }, 0,         1,           VE                },
    { "fixed_alloc",   NULL,                OFFSET(fixed_alloc),   AV_OPT_TYPE_INT,   { .i64 = 0           }, 0,         1,           VE                },
    { "fixed_quality", NULL,                OFFSET(fixed_quality), AV_OPT_TYPE_INT,   { .i64 = 0           }, 0,         1,           VE                },
    { NULL },
}
Definition at line 822 of file libopenjpegenc.c.
openjpeg_class
const AVClass openjpeg_class static
Initial value:
= {
    .class_name = "libopenjpeg",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 849 of file libopenjpegenc.c.
ff_libopenjpeg_encoder
AVCodec ff_libopenjpeg_encoder
Definition at line 856 of file libopenjpegenc.c.