FFmpeg: libavcodec/libopenjpegdec.c File Reference
libopenjpegdec.c File Reference
JPEG 2000 decoder using libopenjpeg.
#include "libavutil/common.h"
#include "libavutil/imgutils.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/opt.h"
#include "libavutil/pixfmt.h"
#include "avcodec.h"
#include "internal.h"
#include "thread.h"
#include <openjpeg.h>
Data Structures
struct LibOpenJPEGContext
Macros
#define OPENJPEG_MAJOR_VERSION 1
#define OPJ(x) x
#define JP2_SIG_TYPE 0x6A502020
#define JP2_SIG_VALUE 0x0D0A870A
#define RGB_PIXEL_FORMATS
#define GRAY_PIXEL_FORMATS
#define YUV_PIXEL_FORMATS
#define XYZ_PIXEL_FORMATS AV_PIX_FMT_XYZ12
#define OFFSET(x) offsetof(LibOpenJPEGContext, x)
#define VD AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_DECODING_PARAM
Functions
static void error_callback (const char *msg, void *data)
static void warning_callback (const char *msg, void *data)
static void info_callback (const char *msg, void *data)
static int libopenjpeg_matches_pix_fmt (const opj_image_t *image, enum AVPixelFormat pix_fmt)
static enum AVPixelFormat libopenjpeg_guess_pix_fmt (const opj_image_t *image)
static int libopenjpeg_ispacked (enum AVPixelFormat pix_fmt)
static void libopenjpeg_copy_to_packed8 (AVFrame *picture, opj_image_t *image)
static void libopenjpeg_copy_to_packed16 (AVFrame *picture, opj_image_t *image)
static void libopenjpeg_copyto8 (AVFrame *picture, opj_image_t *image)
static void libopenjpeg_copyto16 (AVFrame *picture, opj_image_t *image)
static av_cold int libopenjpeg_decode_init (AVCodecContext *avctx)
static int libopenjpeg_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold void libopenjpeg_static_init (AVCodec *codec)
Variables
static enum AVPixelFormat libopenjpeg_rgb_pix_fmts []
static enum AVPixelFormat libopenjpeg_gray_pix_fmts []
static enum AVPixelFormat libopenjpeg_yuv_pix_fmts []
static enum AVPixelFormat libopenjpeg_all_pix_fmts []
static const AVOption options []
static const AVClass openjpeg_class
AVCodec ff_libopenjpeg_decoder
Detailed Description
JPEG 2000 decoder using libopenjpeg.
Definition in file libopenjpegdec.c.
Macro Definition Documentation
OPENJPEG_MAJOR_VERSION
#define OPENJPEG_MAJOR_VERSION 1
Definition at line 51 of file libopenjpegdec.c.
OPJ
#define OPJ (x) x
Definition at line 52 of file libopenjpegdec.c.
Referenced by libopenjpeg_decode_frame(), and libopenjpeg_guess_pix_fmt().
JP2_SIG_TYPE
#define JP2_SIG_TYPE 0x6A502020
Definition at line 55 of file libopenjpegdec.c.
Referenced by libopenjpeg_decode_frame().
JP2_SIG_VALUE
#define JP2_SIG_VALUE 0x0D0A870A
Definition at line 56 of file libopenjpegdec.c.
Referenced by libopenjpeg_decode_frame().
RGB_PIXEL_FORMATS
#define RGB_PIXEL_FORMATS
Value:
AV_PIX_FMT_RGB24, AV_PIX_FMT_RGBA,                 \
                           AV_PIX_FMT_RGB48, AV_PIX_FMT_RGBA64
Definition at line 60 of file libopenjpegdec.c.
GRAY_PIXEL_FORMATS
#define GRAY_PIXEL_FORMATS
Value:
AV_PIX_FMT_GRAY8, AV_PIX_FMT_YA8,                  \
                           AV_PIX_FMT_GRAY16, AV_PIX_FMT_YA16
Definition at line 63 of file libopenjpegdec.c.
YUV_PIXEL_FORMATS
#define YUV_PIXEL_FORMATS
Value:
AV_PIX_FMT_YUV410P, AV_PIX_FMT_YUV411P, AV_PIX_FMT_YUVA420P, \
                           AV_PIX_FMT_YUV420P, AV_PIX_FMT_YUV422P, AV_PIX_FMT_YUVA422P, \
                           AV_PIX_FMT_YUV440P, AV_PIX_FMT_YUV444P, AV_PIX_FMT_YUVA444P, \
                           AV_PIX_FMT_YUV420P9, AV_PIX_FMT_YUV422P9, AV_PIX_FMT_YUV444P9, \
                           AV_PIX_FMT_YUVA420P9, AV_PIX_FMT_YUVA422P9, AV_PIX_FMT_YUVA444P9, \
                           AV_PIX_FMT_YUV420P10, AV_PIX_FMT_YUV422P10, AV_PIX_FMT_YUV444P10, \
                           AV_PIX_FMT_YUVA420P10, AV_PIX_FMT_YUVA422P10, AV_PIX_FMT_YUVA444P10, \
                           AV_PIX_FMT_YUV420P12, AV_PIX_FMT_YUV422P12, AV_PIX_FMT_YUV444P12, \
                           AV_PIX_FMT_YUV420P14, AV_PIX_FMT_YUV422P14, AV_PIX_FMT_YUV444P14, \
                           AV_PIX_FMT_YUV420P16, AV_PIX_FMT_YUV422P16, AV_PIX_FMT_YUV444P16, \
                           AV_PIX_FMT_YUVA420P16, AV_PIX_FMT_YUVA422P16, AV_PIX_FMT_YUVA444P16
Definition at line 66 of file libopenjpegdec.c.
XYZ_PIXEL_FORMATS
#define XYZ_PIXEL_FORMATS AV_PIX_FMT_XYZ12
Definition at line 78 of file libopenjpegdec.c.
OFFSET
#define OFFSET (x) offsetof(LibOpenJPEGContext, x)
Definition at line 574 of file libopenjpegdec.c.
VD
#define VD AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_DECODING_PARAM
Definition at line 575 of file libopenjpegdec.c.
Function Documentation
error_callback()
static void error_callback (const char * msg, void * data) static
Definition at line 102 of file libopenjpegdec.c.
Referenced by libopenjpeg_decode_frame().
warning_callback()
static void warning_callback (const char * msg, void * data) static
Definition at line 107 of file libopenjpegdec.c.
Referenced by libopenjpeg_decode_frame().
info_callback()
static void info_callback (const char * msg, void * data) static
Definition at line 112 of file libopenjpegdec.c.
Referenced by libopenjpeg_decode_frame().
libopenjpeg_matches_pix_fmt()
static int libopenjpeg_matches_pix_fmt (const opj_image_t * image, enum AVPixelFormat pix_fmt) inline static
Definition at line 177 of file libopenjpegdec.c.
Referenced by libopenjpeg_decode_frame(), and libopenjpeg_guess_pix_fmt().
libopenjpeg_guess_pix_fmt()
static enum AVPixelFormat libopenjpeg_guess_pix_fmt (const opj_image_t * image) inline static
Definition at line 214 of file libopenjpegdec.c.
Referenced by libopenjpeg_decode_frame().
libopenjpeg_ispacked()
static int libopenjpeg_ispacked (enum AVPixelFormat pix_fmt) inline static
Definition at line 246 of file libopenjpegdec.c.
Referenced by libopenjpeg_decode_frame().
libopenjpeg_copy_to_packed8()
static void libopenjpeg_copy_to_packed8 (AVFrame * picture, opj_image_t * image) inline static
Definition at line 261 of file libopenjpegdec.c.
Referenced by libopenjpeg_decode_frame().
libopenjpeg_copy_to_packed16()
static void libopenjpeg_copy_to_packed16 (AVFrame * picture, opj_image_t * image) inline static
Definition at line 273 of file libopenjpegdec.c.
Referenced by libopenjpeg_decode_frame().
libopenjpeg_copyto8()
static void libopenjpeg_copyto8 (AVFrame * picture, opj_image_t * image) inline static
Definition at line 291 of file libopenjpegdec.c.
Referenced by libopenjpeg_decode_frame().
libopenjpeg_copyto16()
static void libopenjpeg_copyto16 (AVFrame * picture, opj_image_t * image) inline static
Definition at line 309 of file libopenjpegdec.c.
Referenced by libopenjpeg_decode_frame().
libopenjpeg_decode_init()
static av_cold int libopenjpeg_decode_init (AVCodecContext * avctx) static
Definition at line 332 of file libopenjpegdec.c.
libopenjpeg_decode_frame()
static int libopenjpeg_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 340 of file libopenjpegdec.c.
libopenjpeg_static_init()
static av_cold void libopenjpeg_static_init (AVCodec * codec) static
Definition at line 565 of file libopenjpegdec.c.
Variable Documentation
libopenjpeg_rgb_pix_fmts
enum AVPixelFormat libopenjpeg_rgb_pix_fmts[] static
Initial value:
= {
    RGB_PIXEL_FORMATS
}
Definition at line 80 of file libopenjpegdec.c.
Referenced by libopenjpeg_guess_pix_fmt().
libopenjpeg_gray_pix_fmts
enum AVPixelFormat libopenjpeg_gray_pix_fmts[] static
Initial value:
= {
    GRAY_PIXEL_FORMATS
}
Definition at line 83 of file libopenjpegdec.c.
Referenced by libopenjpeg_guess_pix_fmt().
libopenjpeg_yuv_pix_fmts
enum AVPixelFormat libopenjpeg_yuv_pix_fmts[] static
Initial value:
= {
    YUV_PIXEL_FORMATS
}
Definition at line 86 of file libopenjpegdec.c.
Referenced by libopenjpeg_guess_pix_fmt().
libopenjpeg_all_pix_fmts
enum AVPixelFormat libopenjpeg_all_pix_fmts[] static
Initial value:
= {
    RGB_PIXEL_FORMATS, GRAY_PIXEL_FORMATS, YUV_PIXEL_FORMATS, XYZ_PIXEL_FORMATS
}
Definition at line 89 of file libopenjpegdec.c.
Referenced by libopenjpeg_guess_pix_fmt().
options
const AVOption options[] static
Initial value:
= {
    { "lowqual", "Limit the number of layers used for decoding",
        OFFSET(lowqual), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, INT_MAX, VD },
    { NULL },
}
Definition at line 577 of file libopenjpegdec.c.
openjpeg_class
const AVClass openjpeg_class static
Initial value:
= {
    .class_name = "libopenjpeg",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 583 of file libopenjpegdec.c.
ff_libopenjpeg_decoder
AVCodec ff_libopenjpeg_decoder
Initial value:
= {
    .name           = "libopenjpeg",
    .long_name      = NULL_IF_CONFIG_SMALL("OpenJPEG JPEG 2000"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_JPEG2000,
    .priv_data_size = sizeof(LibOpenJPEGContext),
    .init           = libopenjpeg_decode_init,
    .decode         = libopenjpeg_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_FRAME_THREADS,
    .max_lowres     = 31,
    .priv_class     = &openjpeg_class,
    .init_static_data = libopenjpeg_static_init,
}
Definition at line 590 of file libopenjpegdec.c.