FFmpeg: libavcodec/libopusenc.c File Reference
libopusenc.c File Reference
#include <opus.h>
#include <opus_multistream.h>
#include "libavutil/opt.h"
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
#include "libopus.h"
#include "vorbis.h"
#include "audio_frame_queue.h"
Data Structures
struct LibopusEncOpts
struct LibopusEncContext
Macros
#define OFFSET(x) offsetof(LibopusEncContext, opts.x)
#define FLAGS AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Functions
static void libopus_write_header (AVCodecContext *avctx, int stream_count, int coupled_stream_count, int mapping_family, const uint8_t *channel_mapping)
static int libopus_configure_encoder (AVCodecContext *avctx, OpusMSEncoder *enc, LibopusEncOpts *opts)
static int libopus_check_max_channels (AVCodecContext *avctx, int max_channels)
static int libopus_check_vorbis_layout (AVCodecContext *avctx, int mapping_family)
static int libopus_validate_layout_and_get_channel_map (AVCodecContext *avctx, int mapping_family, const uint8_t **channel_map_result)
static av_cold int libopus_encode_init (AVCodecContext *avctx)
static void libopus_copy_samples_with_channel_map (uint8_t *dst, const uint8_t *src, const uint8_t *channel_map, int nb_channels, int nb_samples, int bytes_per_sample)
static int libopus_encode (AVCodecContext *avctx, AVPacket *avpkt, const AVFrame *frame, int *got_packet_ptr)
static av_cold int libopus_encode_close (AVCodecContext *avctx)
Variables
static const uint8_t opus_coupled_streams [8]
static const uint8_t opus_vorbis_channel_map [8][8]
static const uint8_t libavcodec_libopus_channel_map [8][8]
static const AVOption libopus_options []
static const AVClass libopus_class
static const AVCodecDefault libopus_defaults []
static const int libopus_sample_rates []
AVCodec ff_libopus_encoder
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(LibopusEncContext, opts.x)
Definition at line 519 of file libopusenc.c.
FLAGS
#define FLAGS AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 520 of file libopusenc.c.
Function Documentation
libopus_write_header()
static void libopus_write_header (AVCodecContext * avctx, int stream_count, int coupled_stream_count, int mapping_family, const uint8_t * channel_mapping) static
Definition at line 82 of file libopusenc.c.
Referenced by libopus_encode_init().
libopus_configure_encoder()
static int libopus_configure_encoder (AVCodecContext * avctx, OpusMSEncoder * enc, LibopusEncOpts * opts) static
Definition at line 106 of file libopusenc.c.
Referenced by libopus_encode_init().
libopus_check_max_channels()
static int libopus_check_max_channels (AVCodecContext * avctx, int max_channels) static
Definition at line 160 of file libopusenc.c.
Referenced by libopus_validate_layout_and_get_channel_map().
libopus_check_vorbis_layout()
static int libopus_check_vorbis_layout (AVCodecContext * avctx, int mapping_family) static
Definition at line 171 of file libopusenc.c.
Referenced by libopus_validate_layout_and_get_channel_map().
libopus_validate_layout_and_get_channel_map()
static int libopus_validate_layout_and_get_channel_map (AVCodecContext * avctx, int mapping_family, const uint8_t ** channel_map_result) static
Definition at line 192 of file libopusenc.c.
Referenced by libopus_encode_init().
libopus_encode_init()
static av_cold int libopus_encode_init (AVCodecContext * avctx) static
Definition at line 237 of file libopusenc.c.
libopus_copy_samples_with_channel_map()
static void libopus_copy_samples_with_channel_map (uint8_t * dst, const uint8_t * src, const uint8_t * channel_map, int nb_channels, int nb_samples, int bytes_per_sample) static
Definition at line 410 of file libopusenc.c.
Referenced by libopus_encode().
libopus_encode()
static int libopus_encode (AVCodecContext * avctx, AVPacket * avpkt, const AVFrame * frame, int * got_packet_ptr) static
Definition at line 424 of file libopusenc.c.
libopus_encode_close()
static av_cold int libopus_encode_close (AVCodecContext * avctx) static
Definition at line 505 of file libopusenc.c.
Variable Documentation
opus_coupled_streams
const uint8_t opus_coupled_streams[8] static
Initial value:
= {
    0, 1, 1, 2, 2, 2, 2, 3
}
Definition at line 54 of file libopusenc.c.
Referenced by libopus_encode_init().
opus_vorbis_channel_map
const uint8_t opus_vorbis_channel_map[8][8] static
Initial value:
= {
    { 0 },
    { 0, 1 },
    { 0, 2, 1 },
    { 0, 1, 2, 3 },
    { 0, 4, 1, 2, 3 },
    { 0, 4, 1, 2, 3, 5 },
    { 0, 4, 1, 2, 3, 5, 6 },
    { 0, 6, 1, 2, 3, 4, 5, 7 },
}
Definition at line 59 of file libopusenc.c.
Referenced by libopus_encode_init().
libavcodec_libopus_channel_map
const uint8_t libavcodec_libopus_channel_map[8][8] static
Initial value:
= {
    { 0 },
    { 0, 1 },
    { 0, 1, 2 },
    { 0, 1, 2, 3 },
    { 0, 1, 3, 4, 2 },
    { 0, 1, 4, 5, 2, 3 },
    { 0, 1, 5, 6, 2, 4, 3 },
    { 0, 1, 6, 7, 4, 5, 2, 3 },
}
Definition at line 71 of file libopusenc.c.
Referenced by libopus_encode_init().
libopus_options
const AVOption libopus_options[] static
Initial value:
= {
    { "application",    "Intended application type",           OFFSET(application),    AV_OPT_TYPE_INT,   { .i64 = OPUS_APPLICATION_AUDIO }, OPUS_APPLICATION_VOIP, OPUS_APPLICATION_RESTRICTED_LOWDELAY, FLAGS, "application" },
        { "voip",           "Favor improved speech intelligibility",   0, AV_OPT_TYPE_CONST, { .i64 = OPUS_APPLICATION_VOIP },                0, 0, FLAGS, "application" },
        { "audio",          "Favor faithfulness to the input",         0, AV_OPT_TYPE_CONST, { .i64 = OPUS_APPLICATION_AUDIO },               0, 0, FLAGS, "application" },
        { "lowdelay",       "Restrict to only the lowest delay modes", 0, AV_OPT_TYPE_CONST, { .i64 = OPUS_APPLICATION_RESTRICTED_LOWDELAY }, 0, 0, FLAGS, "application" },
    { "frame_duration", "Duration of a frame in milliseconds", OFFSET(frame_duration), AV_OPT_TYPE_FLOAT, { .dbl = 20.0 }, 2.5, 60.0, FLAGS },
    { "packet_loss",    "Expected packet loss percentage",     OFFSET(packet_loss),    AV_OPT_TYPE_INT,   { .i64 = 0 },    0,   100,  FLAGS },
    { "vbr",            "Variable bit rate mode",              OFFSET(vbr),            AV_OPT_TYPE_INT,   { .i64 = 1 },    0,   2,    FLAGS, "vbr" },
        { "off",            "Use constant bit rate", 0, AV_OPT_TYPE_CONST, { .i64 = 0 }, 0, 0, FLAGS, "vbr" },
        { "on",             "Use variable bit rate", 0, AV_OPT_TYPE_CONST, { .i64 = 1 }, 0, 0, FLAGS, "vbr" },
        { "constrained",    "Use constrained VBR",   0, AV_OPT_TYPE_CONST, { .i64 = 2 }, 0, 0, FLAGS, "vbr" },
    { "mapping_family", "Channel Mapping Family",              OFFSET(mapping_family), AV_OPT_TYPE_INT,   { .i64 = -1 },   -1,  255,  FLAGS, "mapping_family" },
    { NULL },
}
Definition at line 521 of file libopusenc.c.
libopus_class
const AVClass libopus_class static
Initial value:
= {
    .class_name = "libopus",
    .item_name  = av_default_item_name,
    .option     = libopus_options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 536 of file libopusenc.c.
libopus_defaults
const AVCodecDefault libopus_defaults[] static
Initial value:
= {
    { "b",                 "0" },
    { "compression_level", "10" },
    { NULL },
}
Definition at line 543 of file libopusenc.c.
libopus_sample_rates
const int libopus_sample_rates[] static
Initial value:
= {
    48000, 24000, 16000, 12000, 8000, 0,
}
Definition at line 549 of file libopusenc.c.
ff_libopus_encoder
AVCodec ff_libopus_encoder
Initial value:
= {
    .name            = "libopus",
    .long_name       = NULL_IF_CONFIG_SMALL("libopus Opus"),
    .type            = AVMEDIA_TYPE_AUDIO,
    .id              = AV_CODEC_ID_OPUS,
    .priv_data_size  = sizeof(LibopusEncContext),
    .init            = libopus_encode_init,
    .encode2         = libopus_encode,
    .close           = libopus_encode_close,
    .capabilities    = AV_CODEC_CAP_DELAY | AV_CODEC_CAP_SMALL_LAST_FRAME,
    .sample_fmts     = (const enum AVSampleFormat[]){ AV_SAMPLE_FMT_S16,
                                                      AV_SAMPLE_FMT_FLT,
                                                      AV_SAMPLE_FMT_NONE },
    .supported_samplerates = libopus_sample_rates,
    .priv_class      = &libopus_class,
    .defaults        = libopus_defaults,
}
Definition at line 553 of file libopusenc.c.