FFmpeg: libavcodec/libopenh264.h File Reference
libopenh264.h File Reference
Macros
#define OPENH264_VER_AT_LEAST(maj, min)
Functions
void ff_libopenh264_trace_callback (void *ctx, int level, const char *msg)
int ff_libopenh264_check_version (void *logctx)
Macro Definition Documentation
OPENH264_VER_AT_LEAST
#define OPENH264_VER_AT_LEAST (maj, min)
Value:
((OPENH264_MAJOR  > (maj)) || \
     (OPENH264_MAJOR == (maj) && OPENH264_MINOR >= (min)))
Definition at line 25 of file libopenh264.h.
Function Documentation
ff_libopenh264_trace_callback()
void ff_libopenh264_trace_callback (void * ctx, int level, const char * msg)
Definition at line 41 of file libopenh264.c.
Referenced by svc_decode_init(), and svc_encode_init().
ff_libopenh264_check_version()
int ff_libopenh264_check_version (void * logctx)
Definition at line 49 of file libopenh264.c.
Referenced by svc_decode_init(), and svc_encode_init().