FFmpeg: libswresample/arm/audio_convert_init.c File Reference
audio_convert_init.c File Reference
#include <stdint.h>
#include "config.h"
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/arm/cpu.h"
#include "libavutil/samplefmt.h"
#include "libswresample/swresample_internal.h"
#include "libswresample/audioconvert.h"
Functions
void swri_oldapi_conv_flt_to_s16_neon (int16_t *dst, const float *src, int len)
void swri_oldapi_conv_fltp_to_s16_2ch_neon (int16_t *dst, float *const *src, int len, int channels)
void swri_oldapi_conv_fltp_to_s16_nch_neon (int16_t *dst, float *const *src, int len, int channels)
static void conv_flt_to_s16_neon (uint8_t **dst, const uint8_t **src, int len)
static void conv_fltp_to_s16_2ch_neon (uint8_t **dst, const uint8_t **src, int len)
static void conv_fltp_to_s16_nch_neon (uint8_t **dst, const uint8_t **src, int len)
av_cold void swri_audio_convert_init_arm (struct AudioConvert *ac, enum AVSampleFormat out_fmt, enum AVSampleFormat in_fmt, int channels)
Function Documentation
swri_oldapi_conv_flt_to_s16_neon()
void swri_oldapi_conv_flt_to_s16_neon (int16_t * dst, const float * src, int len)
swri_oldapi_conv_fltp_to_s16_2ch_neon()
void swri_oldapi_conv_fltp_to_s16_2ch_neon (int16_t * dst, float *const * src, int len, int channels)
swri_oldapi_conv_fltp_to_s16_nch_neon()
void swri_oldapi_conv_fltp_to_s16_nch_neon (int16_t * dst, float *const * src, int len, int channels)
conv_flt_to_s16_neon()
static void conv_flt_to_s16_neon (uint8_t ** dst, const uint8_t ** src, int len) static
Definition at line 33 of file audio_convert_init.c.
Referenced by swri_audio_convert_init_arm().
conv_fltp_to_s16_2ch_neon()
static void conv_fltp_to_s16_2ch_neon (uint8_t ** dst, const uint8_t ** src, int len) static
Definition at line 37 of file audio_convert_init.c.
Referenced by swri_audio_convert_init_arm().
conv_fltp_to_s16_nch_neon()
static void conv_fltp_to_s16_nch_neon (uint8_t ** dst, const uint8_t ** src, int len) static
Definition at line 41 of file audio_convert_init.c.
Referenced by swri_audio_convert_init_arm().
swri_audio_convert_init_arm()
av_cold void swri_audio_convert_init_arm (struct AudioConvert * ac, enum AVSampleFormat out_fmt, enum AVSampleFormat in_fmt, int channels)
Definition at line 48 of file audio_convert_init.c.