FFmpeg: libavformat/libsmbclient.c File Reference
libsmbclient.c File Reference
#include <libsmbclient.h>
#include "libavutil/avstring.h"
#include "libavutil/opt.h"
#include "avformat.h"
#include "internal.h"
#include "url.h"
Data Structures
struct LIBSMBContext
Macros
#define OFFSET(x) offsetof(LIBSMBContext, x)
#define D AV_OPT_FLAG_DECODING_PARAM
#define E AV_OPT_FLAG_ENCODING_PARAM
Functions
static void libsmbc_get_auth_data (SMBCCTX *c, const char *server, const char *share, char *workgroup, int workgroup_len, char *username, int username_len, char *password, int password_len)
static av_cold int libsmbc_connect (URLContext *h)
static av_cold int libsmbc_close (URLContext *h)
static av_cold int libsmbc_open (URLContext *h, const char *url, int flags)
static int64_t libsmbc_seek (URLContext *h, int64_t pos, int whence)
static int libsmbc_read (URLContext *h, unsigned char *buf, int size)
static int libsmbc_write (URLContext *h, const unsigned char *buf, int size)
static int libsmbc_open_dir (URLContext *h)
static int libsmbc_read_dir (URLContext *h, AVIODirEntry **next)
static int libsmbc_close_dir (URLContext *h)
static int libsmbc_delete (URLContext *h)
static int libsmbc_move (URLContext *h_src, URLContext *h_dst)
Variables
static const AVOption options []
static const AVClass libsmbclient_context_class
const URLProtocol ff_libsmbclient_protocol
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(LIBSMBContext, x)
Definition at line 351 of file libsmbclient.c.
D
#define D AV_OPT_FLAG_DECODING_PARAM
Definition at line 352 of file libsmbclient.c.
E
#define E AV_OPT_FLAG_ENCODING_PARAM
Definition at line 353 of file libsmbclient.c.
Function Documentation
libsmbc_get_auth_data()
static void libsmbc_get_auth_data (SMBCCTX * c, const char * server, const char * share, char * workgroup, int workgroup_len, char * username, int username_len, char * password, int password_len) static
Definition at line 39 of file libsmbclient.c.
Referenced by libsmbc_connect().
libsmbc_connect()
static av_cold int libsmbc_connect (URLContext * h) static
Definition at line 48 of file libsmbclient.c.
Referenced by libsmbc_delete(), libsmbc_move(), libsmbc_open(), and libsmbc_open_dir().
libsmbc_close()
static av_cold int libsmbc_close (URLContext * h) static
Definition at line 81 of file libsmbclient.c.
Referenced by libsmbc_close_dir(), libsmbc_delete(), libsmbc_move(), libsmbc_open(), and libsmbc_open_dir().
libsmbc_open()
static av_cold int libsmbc_open (URLContext * h, const char * url, int flags) static
Definition at line 95 of file libsmbclient.c.
libsmbc_seek()
static int64_t libsmbc_seek (URLContext * h, int64_t pos, int whence) static
Definition at line 136 of file libsmbclient.c.
libsmbc_read()
static int libsmbc_read (URLContext * h, unsigned char * buf, int size) static
Definition at line 158 of file libsmbclient.c.
libsmbc_write()
static int libsmbc_write (URLContext * h, const unsigned char * buf, int size) static
Definition at line 172 of file libsmbclient.c.
libsmbc_open_dir()
static int libsmbc_open_dir (URLContext * h) static
Definition at line 186 of file libsmbclient.c.
libsmbc_read_dir()
static int libsmbc_read_dir (URLContext * h, AVIODirEntry ** next) static
Definition at line 207 of file libsmbclient.c.
libsmbc_close_dir()
static int libsmbc_close_dir (URLContext * h) static
Definition at line 279 of file libsmbclient.c.
libsmbc_delete()
static int libsmbc_delete (URLContext * h) static
Definition at line 290 of file libsmbclient.c.
libsmbc_move()
static int libsmbc_move (URLContext * h_src, URLContext * h_dst) static
Definition at line 331 of file libsmbclient.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    {"timeout",   "set timeout in ms of socket I/O operations",    OFFSET(timeout), AV_OPT_TYPE_INT, {.i64 = -1}, -1, INT_MAX, D|E },
    {"truncate",  "truncate existing files on write",              OFFSET(trunc),   AV_OPT_TYPE_INT, { .i64 = 1 }, 0, 1, E },
    {"workgroup", "set the workgroup used for making connections", OFFSET(workgroup), AV_OPT_TYPE_STRING, { 0 }, 0, 0, D|E },
    {NULL}
}
Definition at line 354 of file libsmbclient.c.
libsmbclient_context_class
const AVClass libsmbclient_context_class static
Initial value:
= {
    .class_name     = "libsmbc",
    .item_name      = av_default_item_name,
    .option         = options,
    .version        = LIBAVUTIL_VERSION_INT,
}
Definition at line 361 of file libsmbclient.c.
ff_libsmbclient_protocol
const URLProtocol ff_libsmbclient_protocol
Initial value:
= {
    .name                = "smb",
    .url_open            = libsmbc_open,
    .url_read            = libsmbc_read,
    .url_write           = libsmbc_write,
    .url_seek            = libsmbc_seek,
    .url_close           = libsmbc_close,
    .url_delete          = libsmbc_delete,
    .url_move            = libsmbc_move,
    .url_open_dir        = libsmbc_open_dir,
    .url_read_dir        = libsmbc_read_dir,
    .url_close_dir       = libsmbc_close_dir,
    .priv_data_size      = sizeof(LIBSMBContext),
    .priv_data_class     = &libsmbclient_context_class,
    .flags               = URL_PROTOCOL_FLAG_NETWORK,
}
Definition at line 368 of file libsmbclient.c.