FFmpeg: libavformat/libssh.c File Reference
libssh.c File Reference
#include <fcntl.h>
#include <libssh/sftp.h>
#include "libavutil/avstring.h"
#include "libavutil/opt.h"
#include "libavutil/attributes.h"
#include "libavformat/avio.h"
#include "avformat.h"
#include "internal.h"
#include "url.h"
Data Structures
struct LIBSSHContext
Macros
#define LIBSSH_STATIC
#define OFFSET(x) offsetof(LIBSSHContext, x)
#define D AV_OPT_FLAG_DECODING_PARAM
#define E AV_OPT_FLAG_ENCODING_PARAM
Functions
static av_cold int libssh_create_ssh_session (LIBSSHContext *libssh, const char *hostname, unsigned int port)
static av_cold int libssh_authentication (LIBSSHContext *libssh, const char *user, const char *password)
static av_cold int libssh_create_sftp_session (LIBSSHContext *libssh)
static av_cold int libssh_open_file (LIBSSHContext *libssh, int flags, const char *file)
static av_cold void libssh_stat_file (LIBSSHContext *libssh)
static av_cold int libssh_close (URLContext *h)
static av_cold int libssh_connect (URLContext *h, const char *url, char *path, size_t path_size)
static av_cold int libssh_open (URLContext *h, const char *url, int flags)
static int64_t libssh_seek (URLContext *h, int64_t pos, int whence)
static int libssh_read (URLContext *h, unsigned char *buf, int size)
static int libssh_write (URLContext *h, const unsigned char *buf, int size)
static int libssh_open_dir (URLContext *h)
static int libssh_read_dir (URLContext *h, AVIODirEntry **next)
static int libssh_close_dir (URLContext *h)
static int libssh_delete (URLContext *h)
static int libssh_move (URLContext *h_src, URLContext *h_dst)
Variables
static const AVOption options []
static const AVClass libssh_context_class
const URLProtocol ff_libssh_protocol
Macro Definition Documentation
LIBSSH_STATIC
#define LIBSSH_STATIC
Definition at line 22 of file libssh.c.
OFFSET
#define OFFSET (x) offsetof(LIBSSHContext, x)
Definition at line 475 of file libssh.c.
D
#define D AV_OPT_FLAG_DECODING_PARAM
Definition at line 476 of file libssh.c.
E
#define E AV_OPT_FLAG_ENCODING_PARAM
Definition at line 477 of file libssh.c.
Function Documentation
libssh_create_ssh_session()
static av_cold int libssh_create_ssh_session (LIBSSHContext * libssh, const char * hostname, unsigned int port) static
Definition at line 44 of file libssh.c.
Referenced by libssh_connect().
libssh_authentication()
static av_cold int libssh_authentication (LIBSSHContext * libssh, const char * user, const char * password) static
Definition at line 72 of file libssh.c.
Referenced by libssh_connect().
libssh_create_sftp_session()
static av_cold int libssh_create_sftp_session (LIBSSHContext * libssh) static
Definition at line 121 of file libssh.c.
Referenced by libssh_connect().
libssh_open_file()
static av_cold int libssh_open_file (LIBSSHContext * libssh, int flags, const char * file) static
Definition at line 136 of file libssh.c.
Referenced by libssh_open().
libssh_stat_file()
static av_cold void libssh_stat_file (LIBSSHContext * libssh) static
Definition at line 160 of file libssh.c.
Referenced by libssh_open().
libssh_close()
static av_cold int libssh_close (URLContext * h) static
Definition at line 173 of file libssh.c.
Referenced by libssh_close_dir(), libssh_delete(), libssh_move(), libssh_open(), and libssh_open_dir().
libssh_connect()
static av_cold int libssh_connect (URLContext * h, const char * url, char * path, size_t path_size) static
Definition at line 192 of file libssh.c.
Referenced by libssh_delete(), libssh_move(), libssh_open(), and libssh_open_dir().
libssh_open()
static av_cold int libssh_open (URLContext * h, const char * url, int flags) static
Definition at line 229 of file libssh.c.
libssh_seek()
static int64_t libssh_seek (URLContext * h, int64_t pos, int whence) static
Definition at line 250 of file libssh.c.
libssh_read()
static int libssh_read (URLContext * h, unsigned char * buf, int size) static
Definition at line 289 of file libssh.c.
libssh_write()
static int libssh_write (URLContext * h, const unsigned char * buf, int size) static
Definition at line 301 of file libssh.c.
libssh_open_dir()
static int libssh_open_dir (URLContext * h) static
Definition at line 313 of file libssh.c.
libssh_read_dir()
static int libssh_read_dir (URLContext * h, AVIODirEntry ** next) static
Definition at line 335 of file libssh.c.
libssh_close_dir()
static int libssh_close_dir (URLContext * h) static
Definition at line 385 of file libssh.c.
libssh_delete()
static int libssh_delete (URLContext * h) static
Definition at line 395 of file libssh.c.
libssh_move()
static int libssh_move (URLContext * h_src, URLContext * h_dst) static
Definition at line 431 of file libssh.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    {"timeout", "set timeout of socket I/O operations", OFFSET(rw_timeout), AV_OPT_TYPE_INT, {.i64 = -1}, -1, INT_MAX, D|E },
    {"truncate", "Truncate existing files on write", OFFSET(trunc), AV_OPT_TYPE_INT, { .i64 = 1 }, 0, 1, E },
    {"private_key", "set path to private key", OFFSET(priv_key), AV_OPT_TYPE_STRING, { .str = NULL }, 0, 0, D|E },
    {NULL}
}
Definition at line 478 of file libssh.c.
libssh_context_class
const AVClass libssh_context_class static
Initial value:
= {
    .class_name     = "libssh",
    .item_name      = av_default_item_name,
    .option         = options,
    .version        = LIBAVUTIL_VERSION_INT,
}
Definition at line 485 of file libssh.c.
ff_libssh_protocol
const URLProtocol ff_libssh_protocol
Initial value:
= {
    .name                = "sftp",
    .url_open            = libssh_open,
    .url_read            = libssh_read,
    .url_write           = libssh_write,
    .url_seek            = libssh_seek,
    .url_close           = libssh_close,
    .url_delete          = libssh_delete,
    .url_move            = libssh_move,
    .url_open_dir        = libssh_open_dir,
    .url_read_dir        = libssh_read_dir,
    .url_close_dir       = libssh_close_dir,
    .priv_data_size      = sizeof(LIBSSHContext),
    .priv_data_class     = &libssh_context_class,
    .flags               = URL_PROTOCOL_FLAG_NETWORK,
}
Definition at line 492 of file libssh.c.