FFmpeg: libavcodec/libschroedingerenc.c File Reference
libschroedingerenc.c File Reference
Dirac encoder support via libschroedinger-1.0 libraries.
#include <schroedinger/schro.h>
#include <schroedinger/schrodebug.h>
#include <schroedinger/schrovideoformat.h>
#include "libavutil/attributes.h"
#include "libavutil/avassert.h"
#include "libavutil/imgutils.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "internal.h"
#include "libschroedinger.h"
#include "bytestream.h"
Data Structures
struct SchroEncoderParams
libschroedinger encoder private data
Macros
#define OFFSET(x) offsetof(SchroEncoderParams, x)
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Functions
static int set_chroma_format (AVCodecContext *avctx)
Works out Schro-compatible chroma format.
static av_cold int libschroedinger_encode_init (AVCodecContext *avctx)
static SchroFrame * libschroedinger_frame_from_data (AVCodecContext *avctx, const AVFrame *frame)
static void libschroedinger_free_frame (void *data)
static int libschroedinger_encode_frame (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *frame, int *got_packet)
static int libschroedinger_encode_close (AVCodecContext *avctx)
Variables
static const AVOption options []
static const AVClass libschroedinger_class
AVCodec ff_libschroedinger_encoder
Detailed Description
Dirac encoder support via libschroedinger-1.0 libraries.
More details about the Schroedinger project can be found at http://www.diracvideo.org/. The library implements Dirac Specification Version 2.2 (http://dirac.sourceforge.net/specification.html).
Definition in file libschroedingerenc.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(SchroEncoderParams, x)
Definition at line 456 of file libschroedingerenc.c.
VE
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 457 of file libschroedingerenc.c.
Function Documentation
set_chroma_format()
static int set_chroma_format (AVCodecContext * avctx) static
Works out Schro-compatible chroma format.
Definition at line 86 of file libschroedingerenc.c.
Referenced by libschroedinger_encode_init().
libschroedinger_encode_init()
static av_cold int libschroedinger_encode_init (AVCodecContext * avctx) static
Definition at line 109 of file libschroedingerenc.c.
libschroedinger_frame_from_data()
static SchroFrame* libschroedinger_frame_from_data (AVCodecContext * avctx, const AVFrame * frame) static
Definition at line 247 of file libschroedingerenc.c.
Referenced by libschroedinger_encode_frame().
libschroedinger_free_frame()
static void libschroedinger_free_frame (void * data) static
Definition at line 266 of file libschroedingerenc.c.
Referenced by libschroedinger_encode_close(), and libschroedinger_encode_frame().
libschroedinger_encode_frame()
static int libschroedinger_encode_frame (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * frame, int * got_packet) static
Definition at line 274 of file libschroedingerenc.c.
libschroedinger_encode_close()
static int libschroedinger_encode_close (AVCodecContext * avctx) static
Definition at line 434 of file libschroedingerenc.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "noarith", "Enable noarith", OFFSET(noarith), AV_OPT_TYPE_INT, { .i64 = 1 }, 0, 1, VE },
    { NULL },
}
Definition at line 458 of file libschroedingerenc.c.
libschroedinger_class
const AVClass libschroedinger_class static
Initial value:
= {
    .class_name = "libschroedinger",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 464 of file libschroedingerenc.c.
ff_libschroedinger_encoder
AVCodec ff_libschroedinger_encoder
Initial value:
= {
    .name           = "libschroedinger",
    .long_name      = NULL_IF_CONFIG_SMALL("libschroedinger Dirac 2.2"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_DIRAC,
    .priv_data_size = sizeof(SchroEncoderParams),
    .priv_class     = &libschroedinger_class,
    .init           = libschroedinger_encode_init,
    .encode2        = libschroedinger_encode_frame,
    .close          = libschroedinger_encode_close,
    .capabilities   = AV_CODEC_CAP_DELAY,
    .pix_fmts       = (const enum AVPixelFormat[]){
        AV_PIX_FMT_YUV420P, AV_PIX_FMT_YUV422P, AV_PIX_FMT_YUV444P, AV_PIX_FMT_NONE
    },
}
Definition at line 471 of file libschroedingerenc.c.