FFmpeg: libswresample/resample.h File Reference
resample.h File Reference
#include "libavutil/log.h"
#include "libavutil/samplefmt.h"
#include "swresample_internal.h"
Data Structures
struct resample_init_func
Functions
void swri_resample_dsp_init (ResampleContext *c)
void swri_resample_dsp_x86_init (ResampleContext *c)
void swri_resample_dsp_arm_init (ResampleContext *c)
Function Documentation
swri_resample_dsp_init()
void swri_resample_dsp_init (ResampleContext * c)
Definition at line 46 of file resample_dsp.c.
Referenced by resample_init().
swri_resample_dsp_x86_init()
void swri_resample_dsp_x86_init (ResampleContext * c)
Definition at line 46 of file resample_init.c.
Referenced by swri_resample_dsp_init().
swri_resample_dsp_arm_init()
void swri_resample_dsp_arm_init (ResampleContext * c)
Definition at line 105 of file resample_init.c.
Referenced by swri_resample_dsp_init().