FFmpeg: libswresample/audioconvert.h File Reference
audioconvert.h File Reference
Audio format conversion routines.
#include "swresample_internal.h"
#include "libavutil/cpu.h"
Data Structures
struct AudioConvert
Typedefs
typedef void(conv_func_type) (uint8_t *po, const uint8_t *pi, int is, int os, uint8_t *end)
typedef void(simd_func_type) (uint8_t **dst, const uint8_t **src, int len)
Functions
AudioConvert * swri_audio_convert_alloc (enum AVSampleFormat out_fmt, enum AVSampleFormat in_fmt, int channels, const int *ch_map, int flags)
Create an audio sample format converter context.
void swri_audio_convert_free (AudioConvert **ctx)
Free audio sample format converter context.
int swri_audio_convert (AudioConvert *ctx, AudioData *out, AudioData *in, int len)
Convert between audio sample formats.
Detailed Description
Audio format conversion routines.
Definition in file audioconvert.h.
Typedef Documentation
conv_func_type
typedef void(conv_func_type) (uint8_t *po, const uint8_t *pi, int is, int os, uint8_t *end)
Definition at line 36 of file audioconvert.h.
simd_func_type
typedef void(simd_func_type) (uint8_t **dst, const uint8_t **src, int len)
Definition at line 37 of file audioconvert.h.
Function Documentation
swri_audio_convert_alloc()
AudioConvert* swri_audio_convert_alloc (enum AVSampleFormat out_fmt, enum AVSampleFormat in_fmt, int channels, const int * ch_map, int flags)
Create an audio sample format converter context.
Parameters
out_fmt Output sample format
in_fmt Input sample format
channels Number of channels
flags See AV_CPU_FLAG_xx
ch_map list of the channels id to pick from the source stream, NULL if all channels must be selected
Returns
NULL on error
Referenced by swr_init().
swri_audio_convert_free()
void swri_audio_convert_free (AudioConvert ** ctx)
Free audio sample format converter context.
and set the pointer to NULL
Referenced by clear_context().
swri_audio_convert()
int swri_audio_convert (AudioConvert * ctx, AudioData * out, AudioData * in, int len)
Convert between audio sample formats.
Parameters
[in] out array of output buffers for each channel. set to NULL to ignore processing of the given channel.
[in] in array of input buffers for each channel
len length of audio frame size (measured in samples)
Referenced by swr_convert_internal().