FFmpeg: libavcodec/libschroedingerdec.c File Reference
libschroedingerdec.c File Reference
Dirac decoder support via libschroedinger-1.0 libraries.
#include <string.h>
#include "libavutil/imgutils.h"
#include "libavutil/internal.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/mem.h"
#include "avcodec.h"
#include "internal.h"
#include "libschroedinger.h"
#include <schroedinger/schro.h>
#include <schroedinger/schrodebug.h>
#include <schroedinger/schrovideoformat.h>
Data Structures
struct LibSchroFrameContext
SchroFrame and Pts relation.
struct SchroDecoderParams
libschroedinger decoder private data
struct SchroParseUnitContext
Functions
static void libschroedinger_decode_buffer_free (SchroBuffer *schro_buf, void *priv)
static void parse_context_init (SchroParseUnitContext *parse_ctx, const uint8_t *buf, int buf_size)
static SchroBuffer * find_next_parse_unit (SchroParseUnitContext *parse_ctx)
static enum AVPixelFormat get_chroma_format (SchroChromaFormat schro_pix_fmt)
Returns FFmpeg chroma format.
static av_cold int libschroedinger_decode_init (AVCodecContext *avctx)
static void libschroedinger_decode_frame_free (void *frame)
static void libschroedinger_handle_first_access_unit (AVCodecContext *avctx)
static int libschroedinger_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int libschroedinger_decode_close (AVCodecContext *avctx)
static void libschroedinger_flush (AVCodecContext *avctx)
Variables
AVCodec ff_libschroedinger_decoder
Detailed Description
Dirac decoder support via libschroedinger-1.0 libraries.
More details about the Schroedinger project can be found at http://www.diracvideo.org/. The library implements Dirac Specification Version 2.2. (http://dirac.sourceforge.net/specification.html).
Definition in file libschroedingerdec.c.
Function Documentation
libschroedinger_decode_buffer_free()
static void libschroedinger_decode_buffer_free (SchroBuffer * schro_buf, void * priv) static
Definition at line 77 of file libschroedingerdec.c.
Referenced by find_next_parse_unit().
parse_context_init()
static void parse_context_init (SchroParseUnitContext * parse_ctx, const uint8_t * buf, int buf_size) static
Definition at line 83 of file libschroedingerdec.c.
Referenced by libschroedinger_decode_frame().
find_next_parse_unit()
static SchroBuffer* find_next_parse_unit (SchroParseUnitContext * parse_ctx) static
Definition at line 90 of file libschroedingerdec.c.
Referenced by libschroedinger_decode_frame().
get_chroma_format()
static enum AVPixelFormat get_chroma_format (SchroChromaFormat schro_pix_fmt) static
Returns FFmpeg chroma format.
Definition at line 135 of file libschroedingerdec.c.
Referenced by libschroedinger_handle_first_access_unit().
libschroedinger_decode_init()
static av_cold int libschroedinger_decode_init (AVCodecContext * avctx) static
Definition at line 147 of file libschroedingerdec.c.
libschroedinger_decode_frame_free()
static void libschroedinger_decode_frame_free (void * frame) static
Definition at line 166 of file libschroedingerdec.c.
Referenced by libschroedinger_decode_close(), libschroedinger_decode_frame(), and libschroedinger_flush().
libschroedinger_handle_first_access_unit()
static void libschroedinger_handle_first_access_unit (AVCodecContext * avctx) static
Definition at line 171 of file libschroedingerdec.c.
Referenced by libschroedinger_decode_frame().
libschroedinger_decode_frame()
static int libschroedinger_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 202 of file libschroedingerdec.c.
libschroedinger_decode_close()
static av_cold int libschroedinger_decode_close (AVCodecContext * avctx) static
Definition at line 354 of file libschroedingerdec.c.
libschroedinger_flush()
static void libschroedinger_flush (AVCodecContext * avctx) static
Definition at line 368 of file libschroedingerdec.c.
Variable Documentation
ff_libschroedinger_decoder
AVCodec ff_libschroedinger_decoder
Initial value:
= {
    .name           = "libschroedinger",
    .long_name      = NULL_IF_CONFIG_SMALL("libschroedinger Dirac 2.2"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_DIRAC,
    .priv_data_size = sizeof(SchroDecoderParams),
    .init           = libschroedinger_decode_init,
    .close          = libschroedinger_decode_close,
    .decode         = libschroedinger_decode_frame,
    .capabilities   = AV_CODEC_CAP_DELAY | AV_CODEC_CAP_DR1,
    .flush          = libschroedinger_flush,
}
Definition at line 384 of file libschroedingerdec.c.