FFmpeg: libswresample/resample.c File Reference
resample.c File Reference
audio resampling
#include "libavutil/avassert.h"
#include "resample.h"
Functions
static double eval_poly (const double *coeff, int size, double x)
static double bessel (double x)
0th order modified bessel function of the first kind.
static int build_filter (ResampleContext *c, void *filter, double factor, int tap_count, int alloc, int phase_count, int scale, int filter_type, double kaiser_beta)
builds a polyphase filterbank.
static ResampleContext * resample_init (ResampleContext *c, int out_rate, int in_rate, int filter_size, int phase_shift, int linear, double cutoff0, enum AVSampleFormat format, enum SwrFilterType filter_type, double kaiser_beta, double precision, int cheby, int exact_rational)
static void resample_free (ResampleContext **c)
static int rebuild_filter_bank_with_compensation (ResampleContext *c)
static int set_compensation (ResampleContext *c, int sample_delta, int compensation_distance)
static int multiple_resample (ResampleContext *c, AudioData *dst, int dst_size, AudioData *src, int src_size, int *consumed)
static int64_t get_delay (struct SwrContext *s, int64_t base)
static int64_t get_out_samples (struct SwrContext *s, int in_samples)
static int resample_flush (struct SwrContext *s)
static int invert_initial_buffer (ResampleContext *c, AudioData *dst, const AudioData *src, int in_count, int *out_idx, int *out_sz)
Variables
struct Resampler const swri_resampler
Detailed Description
audio resampling
Author
Michael Niedermayer micha.nosp@m.elni.nosp@m.@gmx..nosp@m.at
Definition in file resample.c.
Function Documentation
eval_poly()
static double eval_poly (const double * coeff, int size, double x) inline static
Definition at line 32 of file resample.c.
Referenced by bessel().
bessel()
static double bessel (double x) static
0th order modified bessel function of the first kind.
Algorithm taken from the Boost project, source: https://searchcode.com/codesearch/view/14918379/ Use, modification and distribution are subject to the Boost Software License, Version 1.0 (see notice below). Boost Software License - Version 1.0 - August 17th, 2003 Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute, and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the Software is furnished to do so, all subject to the following:
The copyright notices in the Software and this entire statement, including the above license grant, this restriction and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all derivative works of the Software, unless such copies or derivative works are solely in the form of machine-executable object code generated by a source language processor.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 72 of file resample.c.
Referenced by build_filter().
build_filter()
static int build_filter (ResampleContext * c, void * filter, double factor, int tap_count, int alloc, int phase_count, int scale, int filter_type, double kaiser_beta) static
builds a polyphase filterbank.
Parameters
factor resampling factor
scale wanted sum of coefficients for each filter
filter_type filter type
kaiser_beta kaiser window beta
Returns
0 on success, negative on error
Definition at line 144 of file resample.c.
Referenced by rebuild_filter_bank_with_compensation(), and resample_init().
resample_init()
static ResampleContext* resample_init (ResampleContext * c, int out_rate, int in_rate, int filter_size, int phase_shift, int linear, double cutoff0, enum AVSampleFormat format, enum SwrFilterType filter_type, double kaiser_beta, double precision, int cheby, int exact_rational) static
Definition at line 303 of file resample.c.
resample_free()
static void resample_free (ResampleContext ** c) static
Definition at line 394 of file resample.c.
rebuild_filter_bank_with_compensation()
static int rebuild_filter_bank_with_compensation (ResampleContext * c) static
Definition at line 401 of file resample.c.
Referenced by set_compensation().
set_compensation()
static int set_compensation (ResampleContext * c, int sample_delta, int compensation_distance) static
Definition at line 449 of file resample.c.
multiple_resample()
static int multiple_resample (ResampleContext * c, AudioData * dst, int dst_size, AudioData * src, int src_size, int * consumed) static
Definition at line 470 of file resample.c.
get_delay()
static int64_t get_delay (struct SwrContext * s, int64_t base) static
Definition at line 535 of file resample.c.
get_out_samples()
static int64_t get_out_samples (struct SwrContext * s, int in_samples) static
Definition at line 545 of file resample.c.
resample_flush()
static int resample_flush (struct SwrContext * s) static
Definition at line 564 of file resample.c.
invert_initial_buffer()
static int invert_initial_buffer (ResampleContext * c, AudioData * dst, const AudioData * src, int in_count, int * out_idx, int * out_sz) static
Definition at line 581 of file resample.c.
Variable Documentation
swri_resampler
struct Resampler const swri_resampler
Initial value:
={
  resample_init,
  resample_free,
  multiple_resample,
  resample_flush,
  set_compensation,
  get_delay,
  invert_initial_buffer,
  get_out_samples,
}
Definition at line 628 of file resample.c.
Referenced by swr_init().