FFmpeg: libswscale/utils.c File Reference
utils.c File Reference
#include "config.h"
#include <inttypes.h>
#include <math.h>
#include <stdio.h>
#include <string.h>
#include "libavutil/attributes.h"
#include "libavutil/avassert.h"
#include "libavutil/avutil.h"
#include "libavutil/bswap.h"
#include "libavutil/cpu.h"
#include "libavutil/imgutils.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/libm.h"
#include "libavutil/mathematics.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "libavutil/aarch64/cpu.h"
#include "libavutil/ppc/cpu.h"
#include "libavutil/x86/asm.h"
#include "libavutil/x86/cpu.h"
#include "rgb2rgb.h"
#include "swscale.h"
#include "swscale_internal.h"
Data Structures
struct FormatEntry
struct ScaleAlgorithm
Macros
#define _DEFAULT_SOURCE
#define _SVID_SOURCE
#define _DARWIN_C_SOURCE
#define attribute_deprecated
#define LICENSE_PREFIX "libswscale license: "
#define USE_MMAP (HAVE_MMAP && HAVE_MPROTECT && defined MAP_ANONYMOUS)
Functions
static void handle_formats (SwsContext *c)
unsigned swscale_version (void)
const char * swscale_configuration (void)
Return the libswscale build-time configuration.
const char * swscale_license (void)
Return the libswscale license.
int sws_isSupportedInput (enum AVPixelFormat pix_fmt)
Return a positive value if pix_fmt is a supported input format, 0 otherwise.
int sws_isSupportedOutput (enum AVPixelFormat pix_fmt)
Return a positive value if pix_fmt is a supported output format, 0 otherwise.
int sws_isSupportedEndiannessConversion (enum AVPixelFormat pix_fmt)
static double getSplineCoeff (double a, double b, double c, double d, double dist)
static av_cold int get_local_pos (SwsContext *s, int chr_subsample, int pos, int dir)
static av_cold int initFilter (int16_t **outFilter, int32_t **filterPos, int *outFilterSize, int xInc, int srcW, int dstW, int filterAlign, int one, int flags, int cpu_flags, SwsVector *srcFilter, SwsVector *dstFilter, double param[2], int srcPos, int dstPos)
static void fill_rgb2yuv_table (SwsContext *c, const int table[4], int dstRange)
static void fill_xyztables (struct SwsContext *c)
int sws_setColorspaceDetails (struct SwsContext *c, const int inv_table[4], int srcRange, const int table[4], int dstRange, int brightness, int contrast, int saturation)
int sws_getColorspaceDetails (struct SwsContext *c, int **inv_table, int *srcRange, int **table, int *dstRange, int *brightness, int *contrast, int *saturation)
static int handle_jpeg (enum AVPixelFormat *format)
static int handle_0alpha (enum AVPixelFormat *format)
static int handle_xyz (enum AVPixelFormat *format)
SwsContext * sws_alloc_context (void)
Allocate an empty SwsContext.
static uint16_t * alloc_gamma_tbl (double e)
static enum AVPixelFormat alphaless_fmt (enum AVPixelFormat fmt)
av_cold int sws_init_context (SwsContext *c, SwsFilter *srcFilter, SwsFilter *dstFilter)
Initialize the swscaler context sws_context.
SwsContext * sws_alloc_set_opts (int srcW, int srcH, enum AVPixelFormat srcFormat, int dstW, int dstH, enum AVPixelFormat dstFormat, int flags, const double *param)
Allocate and return an SwsContext.
SwsContext * sws_getContext (int srcW, int srcH, enum AVPixelFormat srcFormat, int dstW, int dstH, enum AVPixelFormat dstFormat, int flags, SwsFilter *srcFilter, SwsFilter *dstFilter, const double *param)
Allocate and return an SwsContext.
static int isnan_vec (SwsVector *a)
static void makenan_vec (SwsVector *a)
SwsFilter * sws_getDefaultFilter (float lumaGBlur, float chromaGBlur, float lumaSharpen, float chromaSharpen, float chromaHShift, float chromaVShift, int verbose)
SwsVector * sws_allocVec (int length)
Allocate and return an uninitialized vector with length coefficients.
SwsVector * sws_getGaussianVec (double variance, double quality)
Return a normalized Gaussian curve used to filter stuff quality = 3 is high quality, lower is lower quality.
SwsVector * sws_getConstVec (double c, int length)
Allocate and return a vector with length coefficients, all with the same value c.
SwsVector * sws_getIdentityVec (void)
Allocate and return a vector with just one coefficient, with value 1.0.
static double sws_dcVec (SwsVector *a)
void sws_scaleVec (SwsVector *a, double scalar)
Scale all the coefficients of a by the scalar value.
void sws_normalizeVec (SwsVector *a, double height)
Scale all the coefficients of a so that their sum equals height.
static SwsVector * sws_getConvVec (SwsVector *a, SwsVector *b)
static SwsVector * sws_sumVec (SwsVector *a, SwsVector *b)
static SwsVector * sws_diffVec (SwsVector *a, SwsVector *b)
static SwsVector * sws_getShiftedVec (SwsVector *a, int shift)
void sws_shiftVec (SwsVector *a, int shift)
void sws_addVec (SwsVector *a, SwsVector *b)
void sws_subVec (SwsVector *a, SwsVector *b)
void sws_convVec (SwsVector *a, SwsVector *b)
SwsVector * sws_cloneVec (SwsVector *a)
void sws_printVec2 (SwsVector *a, AVClass *log_ctx, int log_level)
Print with av_log() a textual representation of the vector a if log_level <= av_log_level.
void sws_freeVec (SwsVector *a)
void sws_freeFilter (SwsFilter *filter)
void sws_freeContext (SwsContext *c)
Free the swscaler context swsContext.
struct SwsContext * sws_getCachedContext (struct SwsContext *context, int srcW, int srcH, enum AVPixelFormat srcFormat, int dstW, int dstH, enum AVPixelFormat dstFormat, int flags, SwsFilter *srcFilter, SwsFilter *dstFilter, const double *param)
Check if context can be reused, otherwise reallocate a new one.
Variables
static const FormatEntry format_entries [AV_PIX_FMT_NB]
static const ScaleAlgorithm scale_algorithms []
Macro Definition Documentation
_DEFAULT_SOURCE
#define _DEFAULT_SOURCE
Definition at line 23 of file utils.c.
_SVID_SOURCE
#define _SVID_SOURCE
Definition at line 24 of file utils.c.
_DARWIN_C_SOURCE
#define _DARWIN_C_SOURCE
Definition at line 25 of file utils.c.
attribute_deprecated
#define attribute_deprecated
Definition at line 60 of file utils.c.
LICENSE_PREFIX
#define LICENSE_PREFIX "libswscale license: "
Referenced by swscale_license().
USE_MMAP
#define USE_MMAP (HAVE_MMAP && HAVE_MPROTECT && defined MAP_ANONYMOUS)
Function Documentation
handle_formats()
static void handle_formats (SwsContext * c) static
Definition at line 1055 of file utils.c.
Referenced by sws_init_context(), and sws_setColorspaceDetails().
getSplineCoeff()
static double getSplineCoeff (double a, double b, double c, double d, double dist) static
Definition at line 275 of file utils.c.
Referenced by initFilter().
get_local_pos()
static av_cold int get_local_pos (SwsContext * s, int chr_subsample, int pos, int dir) static
Definition at line 288 of file utils.c.
Referenced by sws_init_context().
initFilter()
static av_cold int initFilter (int16_t ** outFilter, int32_t ** filterPos, int * outFilterSize, int xInc, int srcW, int dstW, int filterAlign, int one, int flags, int cpu_flags, SwsVector * srcFilter, SwsVector * dstFilter, double param[2], int srcPos, int dstPos) static
Definition at line 317 of file utils.c.
Referenced by sws_init_context().
fill_rgb2yuv_table()
static void fill_rgb2yuv_table (SwsContext * c, const int table[4], int dstRange) static
dstRange &&
Definition at line 722 of file utils.c.
Referenced by sws_setColorspaceDetails().
fill_xyztables()
static void fill_xyztables (struct SwsContext * c) static
Definition at line 816 of file utils.c.
Referenced by handle_formats().
handle_jpeg()
static int handle_jpeg (enum AVPixelFormat * format) static
Definition at line 1005 of file utils.c.
Referenced by sws_init_context().
handle_0alpha()
static int handle_0alpha (enum AVPixelFormat * format) static
Definition at line 1035 of file utils.c.
Referenced by handle_formats().
handle_xyz()
static int handle_xyz (enum AVPixelFormat * format) static
Definition at line 1046 of file utils.c.
Referenced by handle_formats().
alloc_gamma_tbl()
static uint16_t* alloc_gamma_tbl (double e) static
Definition at line 1079 of file utils.c.
Referenced by sws_init_context().
alphaless_fmt()
static enum AVPixelFormat alphaless_fmt (enum AVPixelFormat fmt) static
Definition at line 1093 of file utils.c.
Referenced by sws_init_context().
sws_alloc_set_opts()
SwsContext* sws_alloc_set_opts (int srcW, int srcH, enum AVPixelFormat srcFormat, int dstW, int dstH, enum AVPixelFormat dstFormat, int flags, const double * param)
Allocate and return an SwsContext.
This is like sws_getContext() but does not perform the init step, allowing the user to set additional AVOptions.
See also
sws_getContext()
Definition at line 1833 of file utils.c.
Referenced by sws_getContext(), sws_init_context(), sws_setColorspaceDetails(), and usePal().
isnan_vec()
static int isnan_vec (SwsVector * a) static
Definition at line 1879 of file utils.c.
Referenced by sws_getDefaultFilter().
makenan_vec()
static void makenan_vec (SwsVector * a) static
Definition at line 1888 of file utils.c.
Referenced by sws_addVec(), sws_convVec(), sws_shiftVec(), and sws_subVec().
sws_dcVec()
static double sws_dcVec (SwsVector * a) static
Definition at line 2054 of file utils.c.
Referenced by sws_normalizeVec().
sws_getConvVec()
static SwsVector* sws_getConvVec (SwsVector * a, SwsVector * b) static
Definition at line 2079 of file utils.c.
Referenced by sws_convVec().
sws_sumVec()
static SwsVector* sws_sumVec (SwsVector * a, SwsVector * b) static
Definition at line 2098 of file utils.c.
Referenced by sws_addVec().
sws_diffVec()
static SwsVector* sws_diffVec (SwsVector * a, SwsVector * b) static
Definition at line 2116 of file utils.c.
Referenced by sws_subVec().
sws_getShiftedVec()
static SwsVector* sws_getShiftedVec (SwsVector * a, int shift) static
Definition at line 2135 of file utils.c.
Referenced by sws_shiftVec().
Variable Documentation
format_entries
const FormatEntry format_entries[AV_PIX_FMT_NB] static
Definition at line 98 of file utils.c.
scale_algorithms
const ScaleAlgorithm scale_algorithms[] static
Initial value:
= {
    { SWS_AREA,          "area averaging",                  1  },
    { SWS_BICUBIC,       "bicubic",                         4 },
    { SWS_BICUBLIN,      "luma bicubic / chroma bilinear", -1 },
    { SWS_BILINEAR,      "bilinear",                        2 },
    { SWS_FAST_BILINEAR, "fast bilinear",                  -1 },
    { SWS_GAUSS,         "Gaussian",                        8  },
    { SWS_LANCZOS,       "Lanczos",                        -1  },
    { SWS_POINT,         "nearest neighbor / point",       -1 },
    { SWS_SINC,          "sinc",                           20  },
    { SWS_SPLINE,        "bicubic spline",                 20  },
    { SWS_X,             "experimental",                    8 },
}
Definition at line 303 of file utils.c.