FFmpeg: libavcodec/libtheoraenc.c File Reference
libtheoraenc.c File Reference
Theora encoder using libtheora.
#include "libavutil/common.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/pixdesc.h"
#include "libavutil/log.h"
#include "libavutil/base64.h"
#include "avcodec.h"
#include "internal.h"
#include <theora/theoraenc.h>
Data Structures
struct TheoraContext
Functions
static int concatenate_packet (unsigned int *offset, AVCodecContext *avc_context, const ogg_packet *packet)
Concatenate an ogg_packet into the extradata.
static int get_stats (AVCodecContext *avctx, int eos)
static int submit_stats (AVCodecContext *avctx)
static av_cold int encode_init (AVCodecContext *avc_context)
static int encode_frame (AVCodecContext *avc_context, AVPacket *pkt, const AVFrame *frame, int *got_packet)
static av_cold int encode_close (AVCodecContext *avc_context)
Variables
AVCodec ff_libtheora_encoder
AVCodec struct exposed to libavcodec.
Detailed Description
Theora encoder using libtheora.
Author
Paul Richards paul..nosp@m.rich.nosp@m.ards@.nosp@m.gmai.nosp@m.l.com
A lot of this is copy / paste from other output codecs in libavcodec or pure guesswork (or both).
I have used t_ prefixes on variables which are libtheora types and o_ prefixes on variables which are libogg types.
Definition in file libtheoraenc.c.
Function Documentation
concatenate_packet()
static int concatenate_packet (unsigned int * offset, AVCodecContext * avc_context, const ogg_packet * packet) static
Concatenate an ogg_packet into the extradata.
Definition at line 56 of file libtheoraenc.c.
Referenced by encode_init().
get_stats()
static int get_stats (AVCodecContext * avctx, int eos) static
Definition at line 89 of file libtheoraenc.c.
Referenced by encode_frame(), and encode_init().
submit_stats()
static int submit_stats (AVCodecContext * avctx) static
Definition at line 127 of file libtheoraenc.c.
Referenced by encode_frame(), and encode_init().
encode_init()
static av_cold int encode_init (AVCodecContext * avc_context) static
Definition at line 164 of file libtheoraenc.c.
encode_frame()
static int encode_frame (AVCodecContext * avc_context, AVPacket * pkt, const AVFrame * frame, int * got_packet) static
Definition at line 273 of file libtheoraenc.c.
encode_close()
static av_cold int encode_close (AVCodecContext * avc_context) static
Definition at line 359 of file libtheoraenc.c.
Variable Documentation
ff_libtheora_encoder
AVCodec ff_libtheora_encoder
Initial value:
= {
    .name           = "libtheora",
    .long_name      = NULL_IF_CONFIG_SMALL("libtheora Theora"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_THEORA,
    .priv_data_size = sizeof(TheoraContext),
    .init           = encode_init,
    .close          = encode_close,
    .encode2        = encode_frame,
    .capabilities   = AV_CODEC_CAP_DELAY,
    .pix_fmts       = (const enum AVPixelFormat[]){
        AV_PIX_FMT_YUV420P, AV_PIX_FMT_YUV422P, AV_PIX_FMT_YUV444P, AV_PIX_FMT_NONE
    },
}
AVCodec struct exposed to libavcodec.
Definition at line 373 of file libtheoraenc.c.