FFmpeg: libavcodec/libvpxdec.c File Reference
libvpxdec.c File Reference
VP8/9 decoder support via libvpx.
#include <vpx/vpx_decoder.h>
#include <vpx/vp8dx.h>
#include "libavutil/common.h"
#include "libavutil/imgutils.h"
#include "libavutil/intreadwrite.h"
#include "avcodec.h"
#include "internal.h"
#include "libvpx.h"
#include "profiles.h"
Data Structures
struct VPxContext
Macros
#define VPX_CODEC_DISABLE_COMPAT 1
Functions
static av_cold int vpx_init (AVCodecContext *avctx, const struct vpx_codec_iface *iface, int is_alpha_decoder)
static int set_pix_fmt (AVCodecContext *avctx, struct vpx_image *img, int has_alpha_channel)
static int decode_frame (AVCodecContext *avctx, vpx_codec_ctx_t *decoder, uint8_t *data, uint32_t data_sz)
static int vpx_decode (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int vpx_free (AVCodecContext *avctx)
Detailed Description
VP8/9 decoder support via libvpx.
Definition in file libvpxdec.c.
Macro Definition Documentation
VPX_CODEC_DISABLE_COMPAT
#define VPX_CODEC_DISABLE_COMPAT 1
Definition at line 26 of file libvpxdec.c.
Function Documentation
vpx_init()
static av_cold int vpx_init (AVCodecContext * avctx, const struct vpx_codec_iface * iface, int is_alpha_decoder) static
Definition at line 44 of file libvpxdec.c.
Referenced by vpx_decode(), and vpx_free().
set_pix_fmt()
static int set_pix_fmt (AVCodecContext * avctx, struct vpx_image * img, int has_alpha_channel) static
Definition at line 70 of file libvpxdec.c.
Referenced by vpx_decode(), vpx_free(), and vpx_init().
decode_frame()
static int decode_frame (AVCodecContext * avctx, vpx_codec_ctx_t * decoder, uint8_t * data, uint32_t data_sz) static
Definition at line 179 of file libvpxdec.c.
Referenced by vpx_decode().
vpx_decode()
static int vpx_decode (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 196 of file libvpxdec.c.
Referenced by vpx_free().
vpx_free()
static av_cold int vpx_free (AVCodecContext * avctx) static
Definition at line 285 of file libvpxdec.c.