FFmpeg: libavcodec/libvorbisenc.c File Reference
libvorbisenc.c File Reference
#include <vorbis/vorbisenc.h>
#include "libavutil/avassert.h"
#include "libavutil/fifo.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "audio_frame_queue.h"
#include "internal.h"
#include "vorbis.h"
#include "vorbis_parser.h"
Data Structures
struct LibvorbisEncContext
Macros
#define LIBVORBIS_FRAME_SIZE 64
#define BUFFER_SIZE (1024 * 64)
Functions
static int vorbis_error_to_averror (int ov_err)
static av_cold int libvorbis_setup (vorbis_info *vi, AVCodecContext *avctx)
static int xiph_len (int l)
static av_cold int libvorbis_encode_close (AVCodecContext *avctx)
static av_cold int libvorbis_encode_init (AVCodecContext *avctx)
static int libvorbis_encode_frame (AVCodecContext *avctx, AVPacket *avpkt, const AVFrame *frame, int *got_packet_ptr)
Variables
static const AVOption options []
static const AVCodecDefault defaults []
static const AVClass vorbis_class
AVCodec ff_libvorbis_encoder
Macro Definition Documentation
LIBVORBIS_FRAME_SIZE
#define LIBVORBIS_FRAME_SIZE 64
Definition at line 38 of file libvorbisenc.c.
Referenced by libvorbis_encode_init().
BUFFER_SIZE
#define BUFFER_SIZE (1024 * 64)
Definition at line 40 of file libvorbisenc.c.
Referenced by libvorbis_encode_init().
Function Documentation
vorbis_error_to_averror()
static int vorbis_error_to_averror (int ov_err) static
Definition at line 73 of file libvorbisenc.c.
Referenced by libvorbis_encode_frame(), libvorbis_encode_init(), and libvorbis_setup().
libvorbis_setup()
static av_cold int libvorbis_setup (vorbis_info * vi, AVCodecContext * avctx) static
Definition at line 83 of file libvorbisenc.c.
Referenced by libvorbis_encode_init().
xiph_len()
static int xiph_len (int l) static
Definition at line 169 of file libvorbisenc.c.
Referenced by libvorbis_encode_init().
libvorbis_encode_close()
static av_cold int libvorbis_encode_close (AVCodecContext * avctx) static
Definition at line 174 of file libvorbisenc.c.
Referenced by libvorbis_encode_init().
libvorbis_encode_init()
static av_cold int libvorbis_encode_init (AVCodecContext * avctx) static
Definition at line 195 of file libvorbisenc.c.
libvorbis_encode_frame()
static int libvorbis_encode_frame (AVCodecContext * avctx, AVPacket * avpkt, const AVFrame * frame, int * got_packet_ptr) static
Definition at line 274 of file libvorbisenc.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "iblock", "Sets the impulse block bias", 0x42, AV_OPT_TYPE_DOUBLE, { .dbl = 0 }, -15, 0, AV_OPT_FLAG_AUDIO_PARAM | AV_OPT_FLAG_ENCODING_PARAM },
    { NULL }
}
Definition at line 56 of file libvorbisenc.c.
defaults
const AVCodecDefault defaults[] static
Initial value:
= {
    { "b",  "0" },
    { NULL },
}
Definition at line 61 of file libvorbisenc.c.
vorbis_class
const AVClass vorbis_class static
Initial value:
= {
    .class_name = "libvorbis",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 66 of file libvorbisenc.c.
ff_libvorbis_encoder
AVCodec ff_libvorbis_encoder
Initial value:
= {
    .name           = "libvorbis",
    .long_name      = NULL_IF_CONFIG_SMALL("libvorbis"),
    .type           = AVMEDIA_TYPE_AUDIO,
    .id             = AV_CODEC_ID_VORBIS,
    .priv_data_size = sizeof(LibvorbisEncContext),
    .init           = libvorbis_encode_init,
    .encode2        = libvorbis_encode_frame,
    .close          = libvorbis_encode_close,
    .capabilities   = AV_CODEC_CAP_DELAY | AV_CODEC_CAP_SMALL_LAST_FRAME,
    .sample_fmts    = (const enum AVSampleFormat[]) { AV_SAMPLE_FMT_FLTP,
                                                      AV_SAMPLE_FMT_NONE },
    .priv_class     = &vorbis_class,
    .defaults       = defaults,
}
Definition at line 366 of file libvorbisenc.c.