FFmpeg: libavcodec/libvorbisdec.c File Reference
libvorbisdec.c File Reference
#include <vorbis/vorbisenc.h>
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
Data Structures
struct OggVorbisDecContext
Functions
static int oggvorbis_decode_close (AVCodecContext *avccontext)
static int oggvorbis_decode_init (AVCodecContext *avccontext)
static int conv (int samples, float **pcm, char *buf, int channels)
static int oggvorbis_decode_frame (AVCodecContext *avccontext, void *data, int *got_frame_ptr, AVPacket *avpkt)
Variables
AVCodec ff_libvorbis_decoder
Function Documentation
oggvorbis_decode_close()
static int oggvorbis_decode_close (AVCodecContext * avccontext) static
Definition at line 188 of file libvorbisdec.c.
Referenced by oggvorbis_decode_init().
oggvorbis_decode_init()
static int oggvorbis_decode_init (AVCodecContext * avccontext) static
Definition at line 37 of file libvorbisdec.c.
conv()
static int conv (int samples, float ** pcm, char * buf, int channels) inline static
Definition at line 120 of file libvorbisdec.c.
Referenced by ff_audio_convert_set_func(), findRgbConvFn(), oggvorbis_decode_frame(), palToRgbWrapper(), rgbToRgbWrapper(), and sws_convVec().
oggvorbis_decode_frame()
static int oggvorbis_decode_frame (AVCodecContext * avccontext, void * data, int * got_frame_ptr, AVPacket * avpkt) static
Definition at line 138 of file libvorbisdec.c.
Variable Documentation
ff_libvorbis_decoder
AVCodec ff_libvorbis_decoder
Initial value:
= {
    .name           = "libvorbis",
    .long_name      = NULL_IF_CONFIG_SMALL("libvorbis"),
    .type           = AVMEDIA_TYPE_AUDIO,
    .id             = AV_CODEC_ID_VORBIS,
    .priv_data_size = sizeof(OggVorbisDecContext),
    .init           = oggvorbis_decode_init,
    .decode         = oggvorbis_decode_frame,
    .close          = oggvorbis_decode_close,
    .capabilities   = AV_CODEC_CAP_DELAY,
}
Definition at line 200 of file libvorbisdec.c.