FFmpeg: libavcodec/libwebpenc_common.c File Reference
libwebpenc_common.c File Reference
WebP encoder using libwebp: common structs and methods.
#include "libwebpenc_common.h"
Functions
int ff_libwebp_error_to_averror (int err)
av_cold int ff_libwebp_encode_init_common (AVCodecContext *avctx)
int ff_libwebp_get_frame (AVCodecContext *avctx, LibWebPContextCommon *s, const AVFrame *frame, AVFrame **alt_frame_ptr, WebPPicture **pic_ptr)
Detailed Description
WebP encoder using libwebp: common structs and methods.
Definition in file libwebpenc_common.c.
Function Documentation
ff_libwebp_error_to_averror()
int ff_libwebp_error_to_averror (int err)
Definition at line 29 of file libwebpenc_common.c.
Referenced by libwebp_anim_encode_frame(), and libwebp_encode_frame().
ff_libwebp_encode_init_common()
av_cold int ff_libwebp_encode_init_common (AVCodecContext * avctx)
Definition at line 43 of file libwebpenc_common.c.
Referenced by libwebp_anim_encode_init(), and libwebp_encode_init().
ff_libwebp_get_frame()
int ff_libwebp_get_frame (AVCodecContext * avctx, LibWebPContextCommon * s, const AVFrame * frame, AVFrame ** alt_frame_ptr, WebPPicture ** pic_ptr)
Definition at line 86 of file libwebpenc_common.c.
Referenced by libwebp_anim_encode_frame(), and libwebp_encode_frame().