FFmpeg: libavcodec/libwebpenc_common.h File Reference
libwebpenc_common.h File Reference
WebP encoder using libwebp: common structs and methods.
#include <webp/encode.h>
#include "libavutil/common.h"
#include "libavutil/frame.h"
#include "libavutil/imgutils.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "internal.h"
Data Structures
struct LibWebPContextCommon
Macros
#define OFFSET(x) offsetof(LibWebPContextCommon, x)
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Functions
int ff_libwebp_error_to_averror (int err)
av_cold int ff_libwebp_encode_init_common (AVCodecContext *avctx)
int ff_libwebp_get_frame (AVCodecContext *avctx, LibWebPContextCommon *s, const AVFrame *frame, AVFrame **alt_frame_ptr, WebPPicture **pic_ptr)
Variables
static const AVOption options []
static const AVCodecDefault libwebp_defaults []
Detailed Description
WebP encoder using libwebp: common structs and methods.
Definition in file libwebpenc_common.h.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(LibWebPContextCommon, x)
Definition at line 60 of file libwebpenc_common.h.
VE
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 61 of file libwebpenc_common.h.
Function Documentation
ff_libwebp_error_to_averror()
int ff_libwebp_error_to_averror (int err)
Definition at line 29 of file libwebpenc_common.c.
Referenced by libwebp_anim_encode_frame(), and libwebp_encode_frame().
ff_libwebp_encode_init_common()
av_cold int ff_libwebp_encode_init_common (AVCodecContext * avctx)
Definition at line 43 of file libwebpenc_common.c.
Referenced by libwebp_anim_encode_init(), and libwebp_encode_init().
ff_libwebp_get_frame()
int ff_libwebp_get_frame (AVCodecContext * avctx, LibWebPContextCommon * s, const AVFrame * frame, AVFrame ** alt_frame_ptr, WebPPicture ** pic_ptr)
Definition at line 86 of file libwebpenc_common.c.
Referenced by libwebp_anim_encode_frame(), and libwebp_encode_frame().
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "lossless",   "Use lossless mode",       OFFSET(lossless), AV_OPT_TYPE_INT,   { .i64 =  0 },  0, 1,                           VE           },
    { "preset",     "Configuration preset",    OFFSET(preset),   AV_OPT_TYPE_INT,   { .i64 = -1 }, -1, WEBP_PRESET_TEXT,            VE, "preset" },
    { "none",       "do not use a preset",                              0, AV_OPT_TYPE_CONST, { .i64 = -1                  }, 0, 0, VE, "preset" },
    { "default",    "default preset",                                   0, AV_OPT_TYPE_CONST, { .i64 = WEBP_PRESET_DEFAULT }, 0, 0, VE, "preset" },
    { "picture",    "digital picture, like portrait, inner shot",       0, AV_OPT_TYPE_CONST, { .i64 = WEBP_PRESET_PICTURE }, 0, 0, VE, "preset" },
    { "photo",      "outdoor photograph, with natural lighting",        0, AV_OPT_TYPE_CONST, { .i64 = WEBP_PRESET_PHOTO   }, 0, 0, VE, "preset" },
    { "drawing",    "hand or line drawing, with high-contrast details", 0, AV_OPT_TYPE_CONST, { .i64 = WEBP_PRESET_DRAWING }, 0, 0, VE, "preset" },
    { "icon",       "small-sized colorful images",                      0, AV_OPT_TYPE_CONST, { .i64 = WEBP_PRESET_ICON    }, 0, 0, VE, "preset" },
    { "text",       "text-like",                                        0, AV_OPT_TYPE_CONST, { .i64 = WEBP_PRESET_TEXT    }, 0, 0, VE, "preset" },
    { "cr_threshold","Conditional replenishment threshold",     OFFSET(cr_threshold), AV_OPT_TYPE_INT, { .i64 =  0  },  0, INT_MAX, VE           },
    { "cr_size"     ,"Conditional replenishment block size",    OFFSET(cr_size)     , AV_OPT_TYPE_INT, { .i64 =  16 },  0, 256,     VE           },
    { "quality"     ,"Quality",                OFFSET(quality),  AV_OPT_TYPE_FLOAT, { .dbl =  75 }, 0, 100,                         VE           },
    { NULL },
}
Definition at line 62 of file libwebpenc_common.h.
libwebp_defaults
const AVCodecDefault libwebp_defaults[] static
Initial value:
= {
    { "compression_level",  "4"  },
    { "global_quality",     "-1" },
    { NULL },
}
Definition at line 78 of file libwebpenc_common.h.