FFmpeg: libavcodec/libxvid.c File Reference
libxvid.c File Reference
Interface to xvidcore for MPEG-4 compliant encoding.
#include <stdio.h>
#include <string.h>
#include <xvid.h>
#include "libavutil/avassert.h"
#include "libavutil/cpu.h"
#include "libavutil/file.h"
#include "libavutil/internal.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/mathematics.h"
#include "libavutil/mem.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "internal.h"
#include "libxvid.h"
#include "mpegutils.h"
Data Structures
struct xvid_context
Structure for the private Xvid context.
struct xvid_ff_pass1
Structure for the private first-pass plugin.
Macros
#define BUFFER_SIZE 1024
Buffer management macros.
#define BUFFER_REMAINING(x) (BUFFER_SIZE - strlen(x))
#define BUFFER_CAT(x) (&((x)[strlen(x)]))
#define OFFSET(x) offsetof(struct xvid_context, x)
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Functions
static int xvid_encode_close (AVCodecContext *avctx)
static int xvid_encode_frame (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *picture, int *got_packet)
static int xvid_ff_2pass_create (xvid_plg_create_t *param, void **handle)
Initialize the two-pass plugin and context.
static int xvid_ff_2pass_destroy (struct xvid_context *ref, xvid_plg_destroy_t *param)
Destroy the two-pass plugin context.
static int xvid_ff_2pass_before (struct xvid_context *ref, xvid_plg_data_t *param)
Enable fast encode mode during the first pass.
static int xvid_ff_2pass_after (struct xvid_context *ref, xvid_plg_data_t *param)
Capture statistic data and write it during first pass.
static int xvid_ff_2pass (void *ref, int cmd, void *p1, void *p2)
Dispatch function for our custom plugin.
static int xvid_strip_vol_header (AVCodecContext *avctx, AVPacket *pkt, unsigned int header_len, unsigned int frame_len)
Routine to create a global VO/VOL header for MP4 container.
static void xvid_correct_framerate (AVCodecContext *avctx)
Routine to correct a possibly erroneous framerate being fed to us.
static av_cold int xvid_encode_init (AVCodecContext *avctx)
Variables
static const AVOption options []
static const AVClass xvid_class
AVCodec ff_libxvid_encoder
Detailed Description
Interface to xvidcore for MPEG-4 compliant encoding.
Author
Adam Thayer (krevn.nosp@m.ik@c.nosp@m.omcas.nosp@m.t.ne.nosp@m.t)
Definition in file libxvid.c.
Macro Definition Documentation
BUFFER_SIZE
#define BUFFER_SIZE 1024
Buffer management macros.
Definition at line 57 of file libxvid.c.
Referenced by xvid_encode_init().
BUFFER_REMAINING
#define BUFFER_REMAINING (x) (BUFFER_SIZE - strlen(x))
Definition at line 58 of file libxvid.c.
Referenced by xvid_ff_2pass_after(), and xvid_ff_2pass_create().
BUFFER_CAT
#define BUFFER_CAT (x) (&((x)[strlen(x)]))
Definition at line 59 of file libxvid.c.
Referenced by xvid_ff_2pass_after(), and xvid_ff_2pass_create().
OFFSET
#define OFFSET (x) offsetof(struct xvid_context, x)
Definition at line 930 of file libxvid.c.
VE
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 931 of file libxvid.c.
Function Documentation
xvid_encode_close()
static av_cold int xvid_encode_close (AVCodecContext * avctx) static
Definition at line 903 of file libxvid.c.
xvid_encode_frame()
static int xvid_encode_frame (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * picture, int * got_packet) static
Definition at line 762 of file libxvid.c.
Referenced by xvid_encode_init().
xvid_ff_2pass_create()
static int xvid_ff_2pass_create (xvid_plg_create_t * param, void ** handle) static
Initialize the two-pass plugin and context.
Parameters
param Input construction parameter structure
handle Private context handle
Returns
Returns XVID_ERR_xxxx on failure, or 0 on success.
Definition at line 120 of file libxvid.c.
Referenced by xvid_ff_2pass().
xvid_ff_2pass_destroy()
static int xvid_ff_2pass_destroy (struct xvid_context * ref, xvid_plg_destroy_t * param) static
Destroy the two-pass plugin context.
Parameters
ref Context pointer for the plugin
param Destroy context
Returns
Returns 0, success guaranteed
Definition at line 151 of file libxvid.c.
Referenced by xvid_ff_2pass().
xvid_ff_2pass_before()
static int xvid_ff_2pass_before (struct xvid_context * ref, xvid_plg_data_t * param) static
Enable fast encode mode during the first pass.
Parameters
ref Context pointer for the plugin
param Frame data
Returns
Returns 0, success guaranteed
Definition at line 168 of file libxvid.c.
Referenced by xvid_ff_2pass().
xvid_ff_2pass_after()
static int xvid_ff_2pass_after (struct xvid_context * ref, xvid_plg_data_t * param) static
Capture statistic data and write it during first pass.
Parameters
ref Context pointer for the plugin
param Statistic data
Returns
Returns XVID_ERR_xxxx on failure, or 0 on success
Definition at line 212 of file libxvid.c.
Referenced by xvid_ff_2pass().
xvid_ff_2pass()
static int xvid_ff_2pass (void * ref, int cmd, void * p1, void * p2) static
Dispatch function for our custom plugin.
This handles the dispatch for the Xvid plugin. It passes data on to other functions for actual processing.
Parameters
ref Context pointer for the plugin
cmd The task given for us to complete
p1 First parameter (varies)
p2 Second parameter (varies)
Returns
Returns XVID_ERR_xxxx on failure, or 0 on success
Definition at line 249 of file libxvid.c.
Referenced by xvid_encode_init().
xvid_strip_vol_header()
static int xvid_strip_vol_header (AVCodecContext * avctx, AVPacket * pkt, unsigned int header_len, unsigned int frame_len) static
Routine to create a global VO/VOL header for MP4 container.
What we do here is extract the header from the Xvid bitstream as it is encoded. We also strip the repeated headers from the bitstream when a global header is requested for MPEG-4 ISO compliance.
Parameters
avctx AVCodecContext pointer to context
frame Pointer to encoded frame data
header_len Length of header to search
frame_len Length of encoded frame data
Returns
Returns new length of frame data
Definition at line 281 of file libxvid.c.
Referenced by xvid_encode_frame().
xvid_correct_framerate()
static void xvid_correct_framerate (AVCodecContext * avctx) static
Routine to correct a possibly erroneous framerate being fed to us.
Xvid currently chokes on framerates where the ticks per frame is extremely large. This function works to correct problems in this area by estimating a new framerate and taking the simpler fraction of the two presented.
Parameters
avctx Context that contains the framerate to correct.
Definition at line 323 of file libxvid.c.
Referenced by xvid_encode_init().
xvid_encode_init()
static av_cold int xvid_encode_init (AVCodecContext * avctx) static
Definition at line 373 of file libxvid.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "lumi_aq",     "Luminance masking AQ",            OFFSET(lumi_aq),     AV_OPT_TYPE_INT,   { .i64 = 0 },       0,       1, VE         },
    { "variance_aq", "Variance AQ",                     OFFSET(variance_aq), AV_OPT_TYPE_INT,   { .i64 = 0 },       0,       1, VE         },
    { "ssim",        "Show SSIM information to stdout", OFFSET(ssim),        AV_OPT_TYPE_INT,   { .i64 = 0 },       0,       2, VE, "ssim" },
    { "off",         NULL,                                                0, AV_OPT_TYPE_CONST, { .i64 = 0 }, INT_MIN, INT_MAX, VE, "ssim" },
    { "avg",         NULL,                                                0, AV_OPT_TYPE_CONST, { .i64 = 1 }, INT_MIN, INT_MAX, VE, "ssim" },
    { "frame",       NULL,                                                0, AV_OPT_TYPE_CONST, { .i64 = 2 }, INT_MIN, INT_MAX, VE, "ssim" },
    { "ssim_acc",    "SSIM accuracy",                   OFFSET(ssim_acc),    AV_OPT_TYPE_INT,   { .i64 = 2 },       0,       4, VE         },
    { "gmc",         "use GMC",                         OFFSET(gmc),         AV_OPT_TYPE_INT,   { .i64 = 0 },       0,       1, VE         },
    { "me_quality",  "Motion estimation quality",       OFFSET(me_quality),  AV_OPT_TYPE_INT,   { .i64 = 0 },       0,       6, VE         },
    { "mpeg_quant",  "Use MPEG quantizers instead of H.263", OFFSET(mpeg_quant), AV_OPT_TYPE_INT, { .i64 = 0 },     0,       1, VE         },
    { NULL },
}
Definition at line 932 of file libxvid.c.
xvid_class
const AVClass xvid_class static
Initial value:
= {
    .class_name = "libxvid",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 946 of file libxvid.c.
ff_libxvid_encoder
AVCodec ff_libxvid_encoder
Initial value:
= {
    .name           = "libxvid",
    .long_name      = NULL_IF_CONFIG_SMALL("libxvidcore MPEG-4 part 2"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_MPEG4,
    .priv_data_size = sizeof(struct xvid_context),
    .init           = xvid_encode_init,
    .encode2        = xvid_encode_frame,
    .close          = xvid_encode_close,
    .pix_fmts       = (const enum AVPixelFormat[]) { AV_PIX_FMT_YUV420P, AV_PIX_FMT_NONE },
    .priv_class     = &xvid_class,
    .caps_internal  = FF_CODEC_CAP_INIT_THREADSAFE |
                      FF_CODEC_CAP_INIT_CLEANUP,
}
Definition at line 953 of file libxvid.c.