FFmpeg: libavcodec/libx264.c File Reference
libx264.c File Reference
#include "libavutil/eval.h"
#include "libavutil/internal.h"
#include "libavutil/opt.h"
#include "libavutil/mem.h"
#include "libavutil/pixdesc.h"
#include "libavutil/stereo3d.h"
#include "libavutil/intreadwrite.h"
#include "avcodec.h"
#include "internal.h"
#include <x264.h>
#include <float.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct X264Context
Macros
#define OPT_STR(opt, param)
#define PARSE_X264_OPT(name, var)
#define OFFSET(x) offsetof(X264Context, x)
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Functions
static void X264_log (void *p, int level, const char *fmt, va_list args)
static int encode_nals (AVCodecContext *ctx, AVPacket *pkt, const x264_nal_t *nals, int nnal)
static int avfmt2_num_planes (int avfmt)
static void reconfig_encoder (AVCodecContext *ctx, const AVFrame *frame)
static int X264_frame (AVCodecContext *ctx, AVPacket *pkt, const AVFrame *frame, int *got_packet)
static av_cold int X264_close (AVCodecContext *avctx)
static int convert_pix_fmt (enum AVPixelFormat pix_fmt)
static av_cold int X264_init (AVCodecContext *avctx)
static av_cold void X264_init_static (AVCodec *codec)
Variables
static enum AVPixelFormat pix_fmts_8bit []
static enum AVPixelFormat pix_fmts_9bit []
static enum AVPixelFormat pix_fmts_10bit []
static const AVOption options []
static const AVCodecDefault x264_defaults []
Macro Definition Documentation
OPT_STR
#define OPT_STR (opt, param)
Value:
do {                                                                      \
        int ret;                                                              \
        if ((ret = x264_param_parse(&x4->params, opt, param)) < 0) { \
            if(ret == X264_PARAM_BAD_NAME)                                    \
                av_log(avctx, AV_LOG_ERROR,                                   \
                        "bad option '%s': '%s'\n", opt, param);               \
            else                                                              \
                av_log(avctx, AV_LOG_ERROR,                                   \
                        "bad value for '%s': '%s'\n", opt, param);            \
            return -1;                                                        \
        }                                                                     \
    } while (0)
Definition at line 399 of file libx264.c.
Referenced by X264_init().
PARSE_X264_OPT
#define PARSE_X264_OPT (name, var)
Value:
if (x4->var && x264_param_parse(&x4->params, name, x4->var) < 0) {\
        av_log(avctx, AV_LOG_ERROR, "Error parsing option '%s' with value '%s'.\n", name, x4->var);\
        return AVERROR(EINVAL);\
    }
Definition at line 446 of file libx264.c.
Referenced by X264_init().
OFFSET
#define OFFSET (x) offsetof(X264Context, x)
Definition at line 900 of file libx264.c.
VE
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 901 of file libx264.c.
Function Documentation
X264_log()
static void X264_log (void * p, int level, const char * fmt, va_list args) static
Definition at line 97 of file libx264.c.
Referenced by X264_init().
encode_nals()
static int encode_nals (AVCodecContext * ctx, AVPacket * pkt, const x264_nal_t * nals, int nnal) static
Definition at line 113 of file libx264.c.
Referenced by X264_frame().
avfmt2_num_planes()
static int avfmt2_num_planes (int avfmt) static
Definition at line 151 of file libx264.c.
Referenced by X264_frame().
reconfig_encoder()
static void reconfig_encoder (AVCodecContext * ctx, const AVFrame * frame) static
Definition at line 171 of file libx264.c.
Referenced by X264_frame().
X264_frame()
static int X264_frame (AVCodecContext * ctx, AVPacket * pkt, const AVFrame * frame, int * got_packet) static
Definition at line 271 of file libx264.c.
X264_close()
static av_cold int X264_close (AVCodecContext * avctx) static
Definition at line 384 of file libx264.c.
convert_pix_fmt()
static int convert_pix_fmt (enum AVPixelFormat pix_fmt) static
Definition at line 413 of file libx264.c.
Referenced by X264_init().
X264_init()
static av_cold int X264_init (AVCodecContext * avctx) static
Definition at line 452 of file libx264.c.
X264_init_static()
static av_cold void X264_init_static (AVCodec * codec) static
Definition at line 890 of file libx264.c.
Variable Documentation
pix_fmts_8bit
enum AVPixelFormat pix_fmts_8bit[] static
Initial value:
= {
    AV_PIX_FMT_YUV420P,
    AV_PIX_FMT_YUVJ420P,
    AV_PIX_FMT_YUV422P,
    AV_PIX_FMT_YUVJ422P,
    AV_PIX_FMT_YUV444P,
    AV_PIX_FMT_YUVJ444P,
    AV_PIX_FMT_NV12,
    AV_PIX_FMT_NV16,
    AV_PIX_FMT_NONE
}
Definition at line 855 of file libx264.c.
Referenced by X264_init_static().
pix_fmts_9bit
enum AVPixelFormat pix_fmts_9bit[] static
Initial value:
= {
    AV_PIX_FMT_YUV420P9,
    AV_PIX_FMT_YUV444P9,
    AV_PIX_FMT_NONE
}
Definition at line 869 of file libx264.c.
Referenced by X264_init_static().
pix_fmts_10bit
enum AVPixelFormat pix_fmts_10bit[] static
Initial value:
= {
    AV_PIX_FMT_YUV420P10,
    AV_PIX_FMT_YUV422P10,
    AV_PIX_FMT_YUV444P10,
    AV_PIX_FMT_NV20,
    AV_PIX_FMT_NONE
}
Definition at line 874 of file libx264.c.
Referenced by X264_init_static().
options
const AVOption options[] static
Definition at line 902 of file libx264.c.
x264_defaults
const AVCodecDefault x264_defaults[] static
Definition at line 983 of file libx264.c.