FFmpeg: libavcodec/libx265.c File Reference
libx265.c File Reference
#include <x265.h>
#include <float.h>
#include "libavutil/internal.h"
#include "libavutil/common.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "avcodec.h"
#include "internal.h"
Data Structures
struct libx265Context
Macros
#define OFFSET(x) offsetof(libx265Context, x)
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Functions
static int is_keyframe (NalUnitType naltype)
static av_cold int libx265_encode_close (AVCodecContext *avctx)
static av_cold int libx265_encode_init (AVCodecContext *avctx)
static int libx265_encode_frame (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *pic, int *got_packet)
static av_cold void libx265_encode_init_csp (AVCodec *codec)
Variables
static enum AVPixelFormat x265_csp_eight []
static enum AVPixelFormat x265_csp_ten []
static enum AVPixelFormat x265_csp_twelve []
static const AVOption options []
class {
class_name = "libx265"
item_name = av_default_item_name
option = options
version = LIBAVUTIL_VERSION_INT
};
static const AVCodecDefault x265_defaults []
AVCodec ff_libx265_encoder
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(libx265Context, x)
Definition at line 383 of file libx265.c.
VE
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 384 of file libx265.c.
Function Documentation
is_keyframe()
static int is_keyframe (NalUnitType naltype) static
Definition at line 51 of file libx265.c.
Referenced by ff_rdt_parse_header(), ff_rdt_parse_packet(), libx265_encode_frame(), matroska_parse_cluster(), matroska_parse_cluster_incremental(), and matroska_parse_frame().
libx265_encode_close()
static av_cold int libx265_encode_close (AVCodecContext * avctx) static
Definition at line 66 of file libx265.c.
Referenced by libx265_encode_init().
libx265_encode_init()
static av_cold int libx265_encode_init (AVCodecContext * avctx) static
Definition at line 78 of file libx265.c.
libx265_encode_frame()
static int libx265_encode_frame (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * pic, int * got_packet) static
Definition at line 253 of file libx265.c.
libx265_encode_init_csp()
static av_cold void libx265_encode_init_csp (AVCodec * codec) static
Definition at line 373 of file libx265.c.
Variable Documentation
x265_csp_eight
enum AVPixelFormat x265_csp_eight[] static
Initial value:
= {
    AV_PIX_FMT_YUV420P,
    AV_PIX_FMT_YUV422P,
    AV_PIX_FMT_YUV444P,
    AV_PIX_FMT_GBRP,
    AV_PIX_FMT_GRAY8,
    AV_PIX_FMT_NONE
}
Definition at line 334 of file libx265.c.
Referenced by libx265_encode_init_csp().
x265_csp_ten
enum AVPixelFormat x265_csp_ten[] static
Initial value:
= {
    AV_PIX_FMT_YUV420P,
    AV_PIX_FMT_YUV422P,
    AV_PIX_FMT_YUV444P,
    AV_PIX_FMT_GBRP,
    AV_PIX_FMT_YUV420P10,
    AV_PIX_FMT_YUV422P10,
    AV_PIX_FMT_YUV444P10,
    AV_PIX_FMT_GBRP10,
    AV_PIX_FMT_GRAY8,
    AV_PIX_FMT_NONE
}
Definition at line 343 of file libx265.c.
Referenced by libx265_encode_init_csp().
x265_csp_twelve
enum AVPixelFormat x265_csp_twelve[] static
Initial value:
= {
    AV_PIX_FMT_YUV420P,
    AV_PIX_FMT_YUV422P,
    AV_PIX_FMT_YUV444P,
    AV_PIX_FMT_GBRP,
    AV_PIX_FMT_YUV420P10,
    AV_PIX_FMT_YUV422P10,
    AV_PIX_FMT_YUV444P10,
    AV_PIX_FMT_GBRP10,
    AV_PIX_FMT_YUV420P12,
    AV_PIX_FMT_YUV422P12,
    AV_PIX_FMT_YUV444P12,
    AV_PIX_FMT_GBRP12,
    AV_PIX_FMT_GRAY8,
    AV_PIX_FMT_NONE
}
Definition at line 356 of file libx265.c.
Referenced by libx265_encode_init_csp().
options
const AVOption options[] static
Initial value:
= {
    { "crf",         "set the x265 crf",                                                            OFFSET(crf),       AV_OPT_TYPE_FLOAT,  { .dbl = -1 }, -1, FLT_MAX, VE },
    { "forced-idr",  "if forcing keyframes, force them as IDR frames",                              OFFSET(forced_idr),AV_OPT_TYPE_BOOL,   { .i64 =  0 },  0,       1, VE },
    { "preset",      "set the x265 preset",                                                         OFFSET(preset),    AV_OPT_TYPE_STRING, { 0 }, 0, 0, VE },
    { "tune",        "set the x265 tune parameter",                                                 OFFSET(tune),      AV_OPT_TYPE_STRING, { 0 }, 0, 0, VE },
    { "x265-params", "set the x265 configuration using a :-separated list of key=value parameters", OFFSET(x265_opts), AV_OPT_TYPE_STRING, { 0 }, 0, 0, VE },
    { NULL }
}
Definition at line 385 of file libx265.c.
class_name
class_name = "libx265" private
Definition at line 395 of file libx265.c.
item_name
item_name = av_default_item_name private
Definition at line 396 of file libx265.c.
option
option = options private
Definition at line 397 of file libx265.c.
version
version = LIBAVUTIL_VERSION_INT private
Definition at line 398 of file libx265.c.
@88
const { ... }
x265_defaults
const AVCodecDefault x265_defaults[] static
Initial value:
= {
    { "b", "0" },
    { NULL },
}
Definition at line 401 of file libx265.c.
ff_libx265_encoder
AVCodec ff_libx265_encoder
Initial value:
= {
    .name             = "libx265",
    .long_name        = NULL_IF_CONFIG_SMALL("libx265 H.265 / HEVC"),
    .type             = AVMEDIA_TYPE_VIDEO,
    .id               = AV_CODEC_ID_HEVC,
    .init             = libx265_encode_init,
    .init_static_data = libx265_encode_init_csp,
    .encode2          = libx265_encode_frame,
    .close            = libx265_encode_close,
    .priv_data_size   = sizeof(libx265Context),
    .priv_class       = &class,
    .defaults         = x265_defaults,
    .capabilities     = AV_CODEC_CAP_DELAY | AV_CODEC_CAP_AUTO_THREADS,
}
Definition at line 406 of file libx265.c.