FFmpeg: libavcodec/ljpegenc.c File Reference
ljpegenc.c File Reference
lossless JPEG encoder.
#include "libavutil/frame.h"
#include "libavutil/mem.h"
#include "libavutil/pixdesc.h"
#include "avcodec.h"
#include "idctdsp.h"
#include "internal.h"
#include "jpegtables.h"
#include "mjpegenc_common.h"
#include "mjpeg.h"
#include "mjpegenc.h"
Data Structures
struct LJpegEncContext
Macros
#define OFFSET(x) offsetof(LJpegEncContext, x)
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Functions
static int ljpeg_encode_bgr (AVCodecContext *avctx, PutBitContext *pb, const AVFrame *frame)
static void ljpeg_encode_yuv_mb (LJpegEncContext *s, PutBitContext *pb, const AVFrame *frame, int predictor, int mb_x, int mb_y)
static int ljpeg_encode_yuv (AVCodecContext *avctx, PutBitContext *pb, const AVFrame *frame)
static int ljpeg_encode_frame (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *pict, int *got_packet)
static av_cold int ljpeg_encode_close (AVCodecContext *avctx)
static av_cold int ljpeg_encode_init (AVCodecContext *avctx)
Variables
static const AVOption options []
static const AVClass ljpeg_class
AVCodec ff_ljpeg_encoder
Detailed Description
lossless JPEG encoder.
Definition in file ljpegenc.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(LJpegEncContext, x)
Definition at line 336 of file ljpegenc.c.
VE
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 337 of file ljpegenc.c.
Function Documentation
ljpeg_encode_bgr()
static int ljpeg_encode_bgr (AVCodecContext * avctx, PutBitContext * pb, const AVFrame * frame) static
Definition at line 63 of file ljpegenc.c.
Referenced by ljpeg_encode_frame().
ljpeg_encode_yuv_mb()
static void ljpeg_encode_yuv_mb (LJpegEncContext * s, PutBitContext * pb, const AVFrame * frame, int predictor, int mb_x, int mb_y) inline static
Definition at line 132 of file ljpegenc.c.
Referenced by ljpeg_encode_yuv().
ljpeg_encode_yuv()
static int ljpeg_encode_yuv (AVCodecContext * avctx, PutBitContext * pb, const AVFrame * frame) static
Definition at line 197 of file ljpegenc.c.
Referenced by ljpeg_encode_frame().
ljpeg_encode_frame()
static int ljpeg_encode_frame (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * pict, int * got_packet) static
Definition at line 226 of file ljpegenc.c.
ljpeg_encode_close()
static av_cold int ljpeg_encode_close (AVCodecContext * avctx) static
Definition at line 280 of file ljpegenc.c.
Referenced by ljpeg_encode_init().
ljpeg_encode_init()
static av_cold int ljpeg_encode_init (AVCodecContext * avctx) static
Definition at line 289 of file ljpegenc.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
{ "pred", "Prediction method", OFFSET(pred), AV_OPT_TYPE_INT, { .i64 = 1 }, 1, 3, VE, "pred" },
    { "left",   NULL, 0, AV_OPT_TYPE_CONST, { .i64 = 1 }, INT_MIN, INT_MAX, VE, "pred" },
    { "plane",  NULL, 0, AV_OPT_TYPE_CONST, { .i64 = 2 }, INT_MIN, INT_MAX, VE, "pred" },
    { "median", NULL, 0, AV_OPT_TYPE_CONST, { .i64 = 3 }, INT_MIN, INT_MAX, VE, "pred" },
    { NULL},
}
Definition at line 338 of file ljpegenc.c.
ljpeg_class
const AVClass ljpeg_class static
Initial value:
= {
    .class_name = "ljpeg",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 347 of file ljpegenc.c.
ff_ljpeg_encoder
AVCodec ff_ljpeg_encoder
Initial value:
= {
    .name           = "ljpeg",
    .long_name      = NULL_IF_CONFIG_SMALL("Lossless JPEG"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_LJPEG,
    .priv_data_size = sizeof(LJpegEncContext),
    .priv_class     = &ljpeg_class,
    .init           = ljpeg_encode_init,
    .encode2        = ljpeg_encode_frame,
    .close          = ljpeg_encode_close,
    .capabilities   = AV_CODEC_CAP_FRAME_THREADS | AV_CODEC_CAP_INTRA_ONLY,
    .pix_fmts       = (const enum AVPixelFormat[]){
        AV_PIX_FMT_BGR24   , AV_PIX_FMT_BGRA    , AV_PIX_FMT_BGR0,
        AV_PIX_FMT_YUVJ420P, AV_PIX_FMT_YUVJ444P, AV_PIX_FMT_YUVJ422P,
        AV_PIX_FMT_YUV420P , AV_PIX_FMT_YUV444P , AV_PIX_FMT_YUV422P,
        AV_PIX_FMT_NONE},
}
Definition at line 354 of file ljpegenc.c.