FFmpeg: libavutil/lls.c File Reference
lls.c File Reference
linear least squares model
#include <math.h>
#include <string.h>
#include "attributes.h"
#include "internal.h"
#include "version.h"
#include "lls.h"
Functions
static void update_lls (LLSModel *m, const double *var)
void avpriv_solve_lls (LLSModel *m, double threshold, unsigned short min_order)
static double evaluate_lls (LLSModel *m, const double *param, int order)
av_cold void avpriv_init_lls (LLSModel *m, int indep_count)
Detailed Description
linear least squares model
Definition in file lls.c.
Function Documentation
update_lls()
static void update_lls (LLSModel * m, const double * var) static
Definition at line 36 of file lls.c.
Referenced by avpriv_init_lls().
avpriv_solve_lls()
void avpriv_solve_lls (LLSModel * m, double threshold, unsigned short min_order)
Definition at line 47 of file lls.c.
Referenced by ff_lpc_calc_coefs(), and main().
evaluate_lls()
static double evaluate_lls (LLSModel * m, const double * param, int order) static
Definition at line 104 of file lls.c.
Referenced by avpriv_init_lls().
avpriv_init_lls()
av_cold void avpriv_init_lls (LLSModel * m, int indep_count)
Definition at line 115 of file lls.c.
Referenced by ff_lpc_calc_coefs(), and main().