FFmpeg: libavutil/x86/lls_init.c File Reference
lls_init.c File Reference
#include "libavutil/lls.h"
#include "libavutil/x86/cpu.h"
Functions
void ff_update_lls_sse2 (LLSModel *m, const double *var)
void ff_update_lls_avx (LLSModel *m, const double *var)
void ff_update_lls_fma3 (LLSModel *m, const double *var)
double ff_evaluate_lls_sse2 (LLSModel *m, const double *var, int order)
av_cold void ff_init_lls_x86 (LLSModel *m)
Function Documentation
ff_update_lls_sse2()
void ff_update_lls_sse2 (LLSModel * m, const double * var)
Referenced by ff_init_lls_x86().
ff_update_lls_avx()
void ff_update_lls_avx (LLSModel * m, const double * var)
Referenced by ff_init_lls_x86().
ff_update_lls_fma3()
void ff_update_lls_fma3 (LLSModel * m, const double * var)
Referenced by ff_init_lls_x86().
ff_evaluate_lls_sse2()
double ff_evaluate_lls_sse2 (LLSModel * m, const double * var, int order)
Referenced by ff_init_lls_x86().
ff_init_lls_x86()
av_cold void ff_init_lls_x86 (LLSModel * m)
Definition at line 31 of file lls_init.c.
Referenced by avpriv_init_lls().