FFmpeg: libavutil/lls.h File Reference
lls.h File Reference
#include "macros.h"
#include "mem.h"
#include "version.h"
Data Structures
struct LLSModel
Linear least squares model.
Macros
#define MAX_VARS 32
#define MAX_VARS_ALIGN FFALIGN(MAX_VARS+1,4)
Functions
void avpriv_init_lls (LLSModel *m, int indep_count)
void ff_init_lls_x86 (LLSModel *m)
void avpriv_solve_lls (LLSModel *m, double threshold, unsigned short min_order)
Macro Definition Documentation
MAX_VARS
#define MAX_VARS 32
Definition at line 30 of file lls.h.
MAX_VARS_ALIGN
#define MAX_VARS_ALIGN FFALIGN(MAX_VARS+1,4)
Definition at line 31 of file lls.h.
Referenced by avpriv_solve_lls().
Function Documentation
avpriv_init_lls()
void avpriv_init_lls (LLSModel * m, int indep_count)
Definition at line 115 of file lls.c.
Referenced by ff_lpc_calc_coefs(), and main().
ff_init_lls_x86()
void ff_init_lls_x86 (LLSModel * m)
Definition at line 31 of file lls_init.c.
Referenced by avpriv_init_lls().
avpriv_solve_lls()
void avpriv_solve_lls (LLSModel * m, double threshold, unsigned short min_order)
Definition at line 47 of file lls.c.
Referenced by ff_lpc_calc_coefs(), and main().