FFmpeg: libavcodec/loco.c File Reference
loco.c File Reference
LOCO codec.
#include "avcodec.h"
#include "get_bits.h"
#include "golomb.h"
#include "internal.h"
#include "mathops.h"
Data Structures
struct LOCOContext
struct RICEContext
Macros
#define ADVANCE_BY_DECODED
Enumerations
enum LOCO_MODE {
LOCO_UNKN = 0, LOCO_CYUY2 = -1, LOCO_CRGB = -2, LOCO_CRGBA = -3,
LOCO_CYV12 = -4, LOCO_YUY2 = 1, LOCO_UYVY = 2, LOCO_RGB = 3,
LOCO_RGBA = 4, LOCO_YV12 = 5
}
Functions
static int loco_get_rice_param (RICEContext *r)
static void loco_update_rice_param (RICEContext *r, int val)
static int loco_get_rice (RICEContext *r)
static int loco_predict (uint8_t *data, int stride, int step)
static int loco_decode_plane (LOCOContext *l, uint8_t *data, int width, int height, int stride, const uint8_t *buf, int buf_size, int step)
static void rotate_faulty_loco (uint8_t *data, int width, int height, int stride, int step)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int decode_init (AVCodecContext *avctx)
Variables
AVCodec ff_loco_decoder
Detailed Description
LOCO codec.
Definition in file loco.c.
Macro Definition Documentation
ADVANCE_BY_DECODED
#define ADVANCE_BY_DECODED
Value:
do { \
    if (decoded < 0 || decoded >= buf_size) goto buf_too_small; \
    buf += decoded; buf_size -= decoded; \
} while(0)
Referenced by decode_frame().
Enumeration Type Documentation
LOCO_MODE
enum LOCO_MODE
Enumerator
LOCO_UNKN
LOCO_CYUY2
LOCO_CRGB
LOCO_CRGBA
LOCO_CYV12
LOCO_YUY2
LOCO_UYVY
LOCO_RGB
LOCO_RGBA
LOCO_YV12
Definition at line 33 of file loco.c.
Function Documentation
loco_get_rice_param()
static int loco_get_rice_param (RICEContext * r) static
Definition at line 59 of file loco.c.
Referenced by loco_get_rice().
loco_update_rice_param()
static void loco_update_rice_param (RICEContext * r, int val) inline static
Definition at line 72 of file loco.c.
Referenced by loco_get_rice().
loco_get_rice()
static int loco_get_rice (RICEContext * r) inline static
Definition at line 83 of file loco.c.
Referenced by loco_decode_plane().
loco_predict()
static int loco_predict (uint8_t * data, int stride, int step) inline static
Definition at line 117 of file loco.c.
Referenced by loco_decode_plane().
loco_decode_plane()
static int loco_decode_plane (LOCOContext * l, uint8_t * data, int width, int height, int stride, const uint8_t * buf, int buf_size, int step) static
Definition at line 128 of file loco.c.
Referenced by decode_frame().
rotate_faulty_loco()
static void rotate_faulty_loco (uint8_t * data, int width, int height, int stride, int step) static
Definition at line 174 of file loco.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 191 of file loco.c.
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 272 of file loco.c.
Variable Documentation
ff_loco_decoder
AVCodec ff_loco_decoder
Initial value:
= {
    .name           = "loco",
    .long_name      = NULL_IF_CONFIG_SMALL("LOCO"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_LOCO,
    .priv_data_size = sizeof(LOCOContext),
    .init           = decode_init,
    .decode         = decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 325 of file loco.c.