FFmpeg: libavcodec/lossless_videodsp.h File Reference
lossless_videodsp.h File Reference
#include "avcodec.h"
#include "libavutil/cpu.h"
Data Structures
struct LLVidDSPContext
Functions
void ff_llviddsp_init (LLVidDSPContext *llviddsp, AVCodecContext *avctx)
void ff_llviddsp_init_x86 (LLVidDSPContext *llviddsp, AVCodecContext *avctx)
Function Documentation
ff_llviddsp_init()
void ff_llviddsp_init (LLVidDSPContext * llviddsp, AVCodecContext * avctx)
Definition at line 118 of file lossless_videodsp.c.
Referenced by ff_huffyuv_common_init(), and magy_decode_init().
ff_llviddsp_init_x86()
void ff_llviddsp_init_x86 (LLVidDSPContext * llviddsp, AVCodecContext * avctx)
Definition at line 35 of file lossless_videodsp_init.c.
Referenced by ff_llviddsp_init().