FFmpeg: libavcodec/lossless_videodsp.c File Reference
lossless_videodsp.c File Reference
#include "avcodec.h"
#include "lossless_videodsp.h"
#include "libavcodec/mathops.h"
Functions
static void add_int16_c (uint16_t *dst, const uint16_t *src, unsigned mask, int w)
static void diff_int16_c (uint16_t *dst, const uint16_t *src1, const uint16_t *src2, unsigned mask, int w)
static void add_hfyu_median_pred_int16_c (uint16_t *dst, const uint16_t *src, const uint16_t *diff, unsigned mask, int w, int *left, int *left_top)
static void sub_hfyu_median_pred_int16_c (uint16_t *dst, const uint16_t *src1, const uint16_t *src2, unsigned mask, int w, int *left, int *left_top)
static int add_hfyu_left_pred_int16_c (uint16_t *dst, const uint16_t *src, unsigned mask, int w, unsigned acc)
void ff_llviddsp_init (LLVidDSPContext *c, AVCodecContext *avctx)
Function Documentation
add_int16_c()
static void add_int16_c (uint16_t * dst, const uint16_t * src, unsigned mask, int w) static
Definition at line 24 of file lossless_videodsp.c.
Referenced by ff_llviddsp_init().
diff_int16_c()
static void diff_int16_c (uint16_t * dst, const uint16_t * src1, const uint16_t * src2, unsigned mask, int w) static
Definition at line 37 of file lossless_videodsp.c.
Referenced by ff_llviddsp_init().
add_hfyu_median_pred_int16_c()
static void add_hfyu_median_pred_int16_c (uint16_t * dst, const uint16_t * src, const uint16_t * diff, unsigned mask, int w, int * left, int * left_top) static
Definition at line 63 of file lossless_videodsp.c.
Referenced by ff_llviddsp_init().
sub_hfyu_median_pred_int16_c()
static void sub_hfyu_median_pred_int16_c (uint16_t * dst, const uint16_t * src1, const uint16_t * src2, unsigned mask, int w, int * left, int * left_top) static
Definition at line 80 of file lossless_videodsp.c.
Referenced by ff_llviddsp_init().
add_hfyu_left_pred_int16_c()
static int add_hfyu_left_pred_int16_c (uint16_t * dst, const uint16_t * src, unsigned mask, int w, unsigned acc) static
Definition at line 98 of file lossless_videodsp.c.
Referenced by ff_llviddsp_init().
ff_llviddsp_init()
void ff_llviddsp_init (LLVidDSPContext * c, AVCodecContext * avctx)
Definition at line 118 of file lossless_videodsp.c.
Referenced by ff_huffyuv_common_init(), and magy_decode_init().