FFmpeg: libavcodec/lossless_audiodsp.h File Reference
lossless_audiodsp.h File Reference
#include <stdint.h>
Data Structures
struct LLAudDSPContext
Functions
void ff_llauddsp_init (LLAudDSPContext *c)
void ff_llauddsp_init_arm (LLAudDSPContext *c)
void ff_llauddsp_init_ppc (LLAudDSPContext *c)
void ff_llauddsp_init_x86 (LLAudDSPContext *c)
Function Documentation
ff_llauddsp_init()
void ff_llauddsp_init (LLAudDSPContext * c)
Definition at line 56 of file lossless_audiodsp.c.
Referenced by ape_decode_init(), and decode_init().
ff_llauddsp_init_arm()
void ff_llauddsp_init_arm (LLAudDSPContext * c)
Definition at line 31 of file lossless_audiodsp_init_arm.c.
Referenced by ff_llauddsp_init().
ff_llauddsp_init_ppc()
void ff_llauddsp_init_ppc (LLAudDSPContext * c)
Definition at line 85 of file lossless_audiodsp_altivec.c.
Referenced by ff_llauddsp_init().
ff_llauddsp_init_x86()
void ff_llauddsp_init_x86 (LLAudDSPContext * c)
Definition at line 38 of file lossless_audiodsp_init.c.
Referenced by ff_llauddsp_init().