FFmpeg: libavcodec/x86/lossless_audiodsp_init.c File Reference
lossless_audiodsp_init.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/x86/cpu.h"
#include "libavcodec/lossless_audiodsp.h"
Functions
int32_t ff_scalarproduct_and_madd_int16_mmxext (int16_t *v1, const int16_t *v2, const int16_t *v3, int order, int mul)
int32_t ff_scalarproduct_and_madd_int16_sse2 (int16_t *v1, const int16_t *v2, const int16_t *v3, int order, int mul)
int32_t ff_scalarproduct_and_madd_int16_ssse3 (int16_t *v1, const int16_t *v2, const int16_t *v3, int order, int mul)
int32_t ff_scalarproduct_and_madd_int32_sse4 (int16_t *v1, const int32_t *v2, const int16_t *v3, int order, int mul)
av_cold void ff_llauddsp_init_x86 (LLAudDSPContext *c)
Function Documentation
ff_scalarproduct_and_madd_int16_mmxext()
int32_t ff_scalarproduct_and_madd_int16_mmxext (int16_t * v1, const int16_t * v2, const int16_t * v3, int order, int mul)
Referenced by ff_llauddsp_init_x86().
ff_scalarproduct_and_madd_int16_sse2()
int32_t ff_scalarproduct_and_madd_int16_sse2 (int16_t * v1, const int16_t * v2, const int16_t * v3, int order, int mul)
Referenced by ff_llauddsp_init_x86().
ff_scalarproduct_and_madd_int16_ssse3()
int32_t ff_scalarproduct_and_madd_int16_ssse3 (int16_t * v1, const int16_t * v2, const int16_t * v3, int order, int mul)
Referenced by ff_llauddsp_init_x86().
ff_scalarproduct_and_madd_int32_sse4()
int32_t ff_scalarproduct_and_madd_int32_sse4 (int16_t * v1, const int32_t * v2, const int16_t * v3, int order, int mul)
Referenced by ff_llauddsp_init_x86().
ff_llauddsp_init_x86()
av_cold void ff_llauddsp_init_x86 (LLAudDSPContext * c)
Definition at line 38 of file lossless_audiodsp_init.c.
Referenced by ff_llauddsp_init().