FFmpeg: libavcodec/lossless_audiodsp.c File Reference
lossless_audiodsp.c File Reference
#include "avcodec.h"
#include "lossless_audiodsp.h"
Functions
static int32_t scalarproduct_and_madd_int16_c (int16_t *v1, const int16_t *v2, const int16_t *v3, int order, int mul)
static int32_t scalarproduct_and_madd_int32_c (int16_t *v1, const int32_t *v2, const int16_t *v3, int order, int mul)
av_cold void ff_llauddsp_init (LLAudDSPContext *c)
Function Documentation
scalarproduct_and_madd_int16_c()
static int32_t scalarproduct_and_madd_int16_c (int16_t * v1, const int16_t * v2, const int16_t * v3, int order, int mul) static
Definition at line 26 of file lossless_audiodsp.c.
Referenced by ff_llauddsp_init().
scalarproduct_and_madd_int32_c()
static int32_t scalarproduct_and_madd_int32_c (int16_t * v1, const int32_t * v2, const int16_t * v3, int order, int mul) static
Definition at line 41 of file lossless_audiodsp.c.
Referenced by ff_llauddsp_init().
ff_llauddsp_init()
av_cold void ff_llauddsp_init (LLAudDSPContext * c)
Definition at line 56 of file lossless_audiodsp.c.
Referenced by ape_decode_init(), and decode_init().