FFmpeg: libavcodec/lpc.h File Reference
lpc.h File Reference
#include <stdint.h>
#include "libavutil/avassert.h"
#include "libavutil/lls.h"
#include "aac_defines.h"
Data Structures
struct LPCContext
Macros
#define ORDER_METHOD_EST 0
#define ORDER_METHOD_2LEVEL 1
#define ORDER_METHOD_4LEVEL 2
#define ORDER_METHOD_8LEVEL 3
#define ORDER_METHOD_SEARCH 4
#define ORDER_METHOD_LOG 5
#define MIN_LPC_ORDER 1
#define MAX_LPC_ORDER 32
Typedefs
typedef float LPC_TYPE
Enumerations
enum FFLPCType {
FF_LPC_TYPE_DEFAULT = -1, FF_LPC_TYPE_NONE = 0, FF_LPC_TYPE_FIXED = 1, FF_LPC_TYPE_LEVINSON = 2,
FF_LPC_TYPE_CHOLESKY = 3, FF_LPC_TYPE_NB
}
LPC analysis type.
Functions
int ff_lpc_calc_coefs (LPCContext *s, const int32_t *samples, int blocksize, int min_order, int max_order, int precision, int32_t coefs[][MAX_LPC_ORDER], int *shift, enum FFLPCType lpc_type, int lpc_passes, int omethod, int min_shift, int max_shift, int zero_shift)
Calculate LPC coefficients for multiple orders.
int ff_lpc_calc_ref_coefs (LPCContext *s, const int32_t *samples, int order, double *ref)
double ff_lpc_calc_ref_coefs_f (LPCContext *s, const float *samples, int len, int order, double *ref)
int ff_lpc_init (LPCContext *s, int blocksize, int max_order, enum FFLPCType lpc_type)
Initialize LPCContext.
void ff_lpc_init_x86 (LPCContext *s)
void ff_lpc_end (LPCContext *s)
Uninitialize LPCContext.
static void compute_ref_coefs (const LPC_TYPE *autoc, int max_order, LPC_TYPE *ref, LPC_TYPE *error)
Schur recursion.
static int AAC_RENAME() compute_lpc_coefs (const LPC_TYPE *autoc, int max_order, LPC_TYPE *lpc, int lpc_stride, int fail, int normalize)
Levinson-Durbin recursion.
Macro Definition Documentation
ORDER_METHOD_EST
#define ORDER_METHOD_EST 0
Definition at line 30 of file lpc.h.
Referenced by calc_predictor_params(), dprint_compression_options(), ff_lpc_calc_coefs(), flac_encode_init(), ra144_encode_frame(), and set_filter_params().
ORDER_METHOD_2LEVEL
#define ORDER_METHOD_2LEVEL 1
Definition at line 31 of file lpc.h.
Referenced by dprint_compression_options(), and encode_residual_ch().
ORDER_METHOD_4LEVEL
#define ORDER_METHOD_4LEVEL 2
Definition at line 32 of file lpc.h.
Referenced by dprint_compression_options(), encode_residual_ch(), and flac_encode_init().
ORDER_METHOD_8LEVEL
#define ORDER_METHOD_8LEVEL 3
Definition at line 33 of file lpc.h.
Referenced by dprint_compression_options(), and encode_residual_ch().
ORDER_METHOD_SEARCH
#define ORDER_METHOD_SEARCH 4
Definition at line 34 of file lpc.h.
Referenced by dprint_compression_options(), encode_residual_ch(), and flac_encode_init().
ORDER_METHOD_LOG
#define ORDER_METHOD_LOG 5
Definition at line 35 of file lpc.h.
Referenced by dprint_compression_options(), encode_residual_ch(), and flac_encode_init().
MIN_LPC_ORDER
#define MIN_LPC_ORDER 1
Definition at line 37 of file lpc.h.
Referenced by alac_encode_init(), ff_lpc_calc_coefs(), and flac_encode_init().
MAX_LPC_ORDER
#define MAX_LPC_ORDER 32
Definition at line 38 of file lpc.h.
Referenced by calc_predictor_params(), compute_ref_coefs(), encode_residual_ch(), ff_aac_search_for_tns(), ff_lpc_calc_coefs(), ff_lpc_calc_ref_coefs(), ff_lpc_calc_ref_coefs_f(), flac_encode_init(), ra144_encode_frame(), and set_filter_params().
Typedef Documentation
LPC_TYPE
typedef float LPC_TYPE
Definition at line 124 of file lpc.h.
Enumeration Type Documentation
FFLPCType
enum FFLPCType
LPC analysis type.
Enumerator
FF_LPC_TYPE_DEFAULT
use the codec default LPC type
FF_LPC_TYPE_NONE
do not use LPC prediction or use all zero coefficients
FF_LPC_TYPE_FIXED
fixed LPC coefficients
FF_LPC_TYPE_LEVINSON
Levinson-Durbin recursion.
FF_LPC_TYPE_CHOLESKY
Cholesky factorization.
FF_LPC_TYPE_NB
Not part of ABI.
Definition at line 43 of file lpc.h.
Function Documentation
ff_lpc_calc_coefs()
int ff_lpc_calc_coefs (LPCContext * s, const int32_t * samples, int blocksize, int min_order, int max_order, int precision, int32_t coefs[][MAX_LPC_ORDER], int * shift, enum FFLPCType lpc_type, int lpc_passes, int omethod, int min_shift, int max_shift, int zero_shift)
Calculate LPC coefficients for multiple orders.
Parameters
lpc_type LPC method for determining coefficients, see FFLPCType for details
Definition at line 200 of file lpc.c.
Referenced by calc_predictor_params(), encode_residual_ch(), ra144_encode_frame(), and set_filter_params().
ff_lpc_calc_ref_coefs()
int ff_lpc_calc_ref_coefs (LPCContext * s, const int32_t * samples, int order, double * ref)
Definition at line 159 of file lpc.c.
Referenced by cng_encode_frame().
ff_lpc_calc_ref_coefs_f()
double ff_lpc_calc_ref_coefs_f (LPCContext * s, const float * samples, int len, int order, double * ref)
Definition at line 171 of file lpc.c.
Referenced by ff_aac_search_for_tns().
ff_lpc_init()
int ff_lpc_init (LPCContext * s, int blocksize, int max_order, enum FFLPCType lpc_type)
Initialize LPCContext.
Definition at line 300 of file lpc.c.
Referenced by aac_encode_init(), alac_encode_init(), cng_encode_init(), ff_lpc_calc_coefs(), flac_encode_init(), mlp_encode_init(), and ra144_encode_init().
ff_lpc_init_x86()
void ff_lpc_init_x86 (LPCContext * s)
Definition at line 152 of file lpc.c.
Referenced by ff_lpc_init().
ff_lpc_end()
void ff_lpc_end (LPCContext * s)
Uninitialize LPCContext.
Definition at line 322 of file lpc.c.
Referenced by aac_encode_end(), alac_encode_close(), cng_encode_close(), ff_lpc_calc_coefs(), flac_encode_close(), mlp_encode_close(), and ra144_encode_close().
compute_ref_coefs()
static void compute_ref_coefs (const LPC_TYPE * autoc, int max_order, LPC_TYPE * ref, LPC_TYPE * error) inline static
Schur recursion.
Produces reflection coefficients from autocorrelation data.
Definition at line 132 of file lpc.h.
Referenced by ff_lpc_calc_ref_coefs(), and ff_lpc_calc_ref_coefs_f().
compute_lpc_coefs()
static int AAC_RENAME() compute_lpc_coefs (const LPC_TYPE * autoc, int max_order, LPC_TYPE * lpc, int lpc_stride, int fail, int normalize) inline static
Levinson-Durbin recursion.
Produce LPC coefficients from autocorrelation data.
Definition at line 163 of file lpc.h.
Referenced by apply_tns(), backward_filter(), ff_aac_apply_tns(), and ff_lpc_calc_coefs().