FFmpeg: libavformat/lrcdec.c File Reference
lrcdec.c File Reference
#include <inttypes.h>
#include <stdint.h>
#include <string.h>
#include "avformat.h"
#include "internal.h"
#include "lrc.h"
#include "metadata.h"
#include "subtitles.h"
#include "libavutil/bprint.h"
#include "libavutil/dict.h"
Data Structures
struct LRCContext
Functions
static int64_t find_header (const char *p)
static int64_t count_ts (const char *p)
static int64_t read_ts (const char *p, int64_t *start)
static int64_t read_line (AVBPrint *buf, AVIOContext *pb)
static int lrc_probe (AVProbeData *p)
static int lrc_read_header (AVFormatContext *s)
static int lrc_read_packet (AVFormatContext *s, AVPacket *pkt)
static int lrc_read_seek (AVFormatContext *s, int stream_index, int64_t min_ts, int64_t ts, int64_t max_ts, int flags)
static int lrc_read_close (AVFormatContext *s)
Variables
AVInputFormat ff_lrc_demuxer
Function Documentation
find_header()
static int64_t find_header (const char * p) static
Definition at line 39 of file lrcdec.c.
Referenced by lrc_read_header().
count_ts()
static int64_t count_ts (const char * p) static
Definition at line 52 of file lrcdec.c.
Referenced by lrc_read_header().
read_ts()
static int64_t read_ts (const char * p, int64_t * start) static
Definition at line 77 of file lrcdec.c.
Referenced by lrc_read_header().
read_line()
static int64_t read_line (AVBPrint * buf, AVIOContext * pb) static
Definition at line 102 of file lrcdec.c.
Referenced by lrc_read_header().
lrc_probe()
static int lrc_probe (AVProbeData * p) static
Definition at line 119 of file lrcdec.c.
lrc_read_header()
static int lrc_read_header (AVFormatContext * s) static
Definition at line 156 of file lrcdec.c.
lrc_read_packet()
static int lrc_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 218 of file lrcdec.c.
lrc_read_seek()
static int lrc_read_seek (AVFormatContext * s, int stream_index, int64_t min_ts, int64_t ts, int64_t max_ts, int flags) static
Definition at line 224 of file lrcdec.c.
lrc_read_close()
static int lrc_read_close (AVFormatContext * s) static
Definition at line 232 of file lrcdec.c.
Variable Documentation
ff_lrc_demuxer
AVInputFormat ff_lrc_demuxer
Initial value:
= {
    .name           = "lrc",
    .long_name      = NULL_IF_CONFIG_SMALL("LRC lyrics"),
    .priv_data_size = sizeof (LRCContext),
    .read_probe     = lrc_probe,
    .read_header    = lrc_read_header,
    .read_packet    = lrc_read_packet,
    .read_close     = lrc_read_close,
    .read_seek2     = lrc_read_seek
}
Definition at line 239 of file lrcdec.c.