FFmpeg: libavfilter/lswsutils.h File Reference
lswsutils.h File Reference
Miscellaneous utilities which make use of the libswscale library.
#include "libswscale/swscale.h"
Functions
int ff_scale_image (uint8_t *dst_data[4], int dst_linesize[4], int dst_w, int dst_h, enum AVPixelFormat dst_pix_fmt, uint8_t *const src_data[4], int src_linesize[4], int src_w, int src_h, enum AVPixelFormat src_pix_fmt, void *log_ctx)
Scale image using libswscale.
Detailed Description
Miscellaneous utilities which make use of the libswscale library.
Definition in file lswsutils.h.
Function Documentation
ff_scale_image()
int ff_scale_image (uint8_t * dst_data[4], int dst_linesize[4], int dst_w, int dst_h, enum AVPixelFormat dst_pix_fmt, uint8_t *const src_data[4], int src_linesize[4], int src_w, int src_h, enum AVPixelFormat src_pix_fmt, void * log_ctx)
Scale image using libswscale.
Definition at line 22 of file lswsutils.c.
Referenced by init_axis_from_file(), init_axis_from_font(), and load_mask().