FFmpeg: libavcodec/magicyuv.c File Reference
magicyuv.c File Reference
#include <stdlib.h>
#include <string.h>
#include "libavutil/pixdesc.h"
#include "libavutil/qsort.h"
#include "avcodec.h"
#include "bytestream.h"
#include "get_bits.h"
#include "huffyuvdsp.h"
#include "internal.h"
#include "lossless_videodsp.h"
#include "thread.h"
Data Structures
struct Slice
struct HuffEntry
struct MagicYUVContext
Enumerations
enum Prediction { LEFT = 1, GRADIENT, MEDIAN }
Functions
static int huff_cmp_len (const void *a, const void *b)
static int huff_cmp_len10 (const void *a, const void *b)
static int huff_build10 (VLC *vlc, uint8_t *len)
static int huff_build (VLC *vlc, uint8_t *len)
static void magicyuv_median_pred10 (uint16_t *dst, const uint16_t *src1, const uint16_t *diff, intptr_t w, int *left, int *left_top)
static int magy_decode_slice10 (AVCodecContext *avctx, void *tdata, int j, int threadnr)
static int magy_decode_slice (AVCodecContext *avctx, void *tdata, int j, int threadnr)
static int build_huffman (AVCodecContext *avctx, GetBitContext *gbit, int max)
static int magy_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int magy_decode_init (AVCodecContext *avctx)
static av_cold int magy_decode_end (AVCodecContext *avctx)
Variables
AVCodec ff_magicyuv_decoder
Enumeration Type Documentation
Prediction
enum Prediction
Enumerator
LEFT
GRADIENT
MEDIAN
Definition at line 41 of file magicyuv.c.
Function Documentation
huff_cmp_len()
static int huff_cmp_len (const void * a, const void * b) static
Definition at line 77 of file magicyuv.c.
Referenced by huff_build().
huff_cmp_len10()
static int huff_cmp_len10 (const void * a, const void * b) static
Definition at line 83 of file magicyuv.c.
Referenced by huff_build10().
huff_build10()
static int huff_build10 (VLC * vlc, uint8_t * len) static
Definition at line 89 of file magicyuv.c.
Referenced by magy_decode_frame().
huff_build()
static int huff_build (VLC * vlc, uint8_t * len) static
Definition at line 119 of file magicyuv.c.
Referenced by magy_decode_frame().
magicyuv_median_pred10()
static void magicyuv_median_pred10 (uint16_t * dst, const uint16_t * src1, const uint16_t * diff, intptr_t w, int * left, int * left_top) static
Definition at line 149 of file magicyuv.c.
Referenced by magy_decode_slice10().
magy_decode_slice10()
static int magy_decode_slice10 (AVCodecContext * avctx, void * tdata, int j, int threadnr) static
Definition at line 170 of file magicyuv.c.
Referenced by magy_decode_frame().
magy_decode_slice()
static int magy_decode_slice (AVCodecContext * avctx, void * tdata, int j, int threadnr) static
Definition at line 301 of file magicyuv.c.
Referenced by magy_decode_frame().
build_huffman()
static int build_huffman (AVCodecContext * avctx, GetBitContext * gbit, int max) static
Definition at line 431 of file magicyuv.c.
Referenced by magy_decode_frame().
magy_decode_frame()
static int magy_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 470 of file magicyuv.c.
magy_decode_init()
static av_cold int magy_decode_init (AVCodecContext * avctx) static
Definition at line 698 of file magicyuv.c.
magy_decode_end()
static av_cold int magy_decode_end (AVCodecContext * avctx) static
Definition at line 706 of file magicyuv.c.
Variable Documentation
ff_magicyuv_decoder
AVCodec ff_magicyuv_decoder
Initial value:
= {
    .name             = "magicyuv",
    .long_name        = NULL_IF_CONFIG_SMALL("MagicYUV video"),
    .type             = AVMEDIA_TYPE_VIDEO,
    .id               = AV_CODEC_ID_MAGICYUV,
    .priv_data_size   = sizeof(MagicYUVContext),
    .init             = magy_decode_init,
    .init_thread_copy = ONLY_IF_THREADS_ENABLED(magy_init_thread_copy),
    .close            = magy_decode_end,
    .decode           = magy_decode_frame,
    .capabilities     = AV_CODEC_CAP_DR1 |
                        AV_CODEC_CAP_FRAME_THREADS |
                        AV_CODEC_CAP_SLICE_THREADS,
    .caps_internal    = FF_CODEC_CAP_INIT_THREADSAFE,
}
Definition at line 720 of file magicyuv.c.