FFmpeg: libavformat/matroskaenc.c File Reference
matroskaenc.c File Reference
#include <stdint.h>
#include "avc.h"
#include "hevc.h"
#include "avformat.h"
#include "avio_internal.h"
#include "avlanguage.h"
#include "flacenc.h"
#include "internal.h"
#include "isom.h"
#include "matroska.h"
#include "riff.h"
#include "subtitles.h"
#include "vorbiscomment.h"
#include "wv.h"
#include "libavutil/avstring.h"
#include "libavutil/channel_layout.h"
#include "libavutil/crc.h"
#include "libavutil/dict.h"
#include "libavutil/intfloat.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/lfg.h"
#include "libavutil/mastering_display_metadata.h"
#include "libavutil/mathematics.h"
#include "libavutil/opt.h"
#include "libavutil/parseutils.h"
#include "libavutil/random_seed.h"
#include "libavutil/rational.h"
#include "libavutil/samplefmt.h"
#include "libavutil/sha.h"
#include "libavutil/stereo3d.h"
#include "libavcodec/xiph.h"
#include "libavcodec/mpeg4audio.h"
#include "libavcodec/internal.h"
Data Structures
struct ebml_master
struct mkv_seekhead_entry
struct mkv_seekhead
struct mkv_cuepoint
struct mkv_cues
struct mkv_track
struct mkv_attachment
struct mkv_attachments
struct MatroskaMuxContext
Macros
#define MODE_MATROSKAv2 0x01
#define MODE_WEBM 0x02
#define MAX_TRACKS 126
Maximum number of tracks allowed in a Matroska file (with track numbers in range 1 to 126 (inclusive)
#define MAX_SEEKENTRY_SIZE 21
2 bytes * 3 for EBML IDs, 3 1-byte EBML lengths, 8 bytes for 64 bit offset, 4 bytes for target EBML ID
#define MAX_CUETRACKPOS_SIZE 42
per-cuepoint-track - 5 1-byte EBML IDs, 5 1-byte EBML sizes, 4 8-byte uint max
#define MAX_CUEPOINT_SIZE(num_tracks) 12 + MAX_CUETRACKPOS_SIZE * num_tracks
per-cuepoint - 2 1-byte EBML IDs, 2 1-byte EBML sizes, 8-byte uint max
#define OPUS_SEEK_PREROLL 80000000
Seek preroll value for opus.
#define OFFSET(x) offsetof(MatroskaMuxContext, x)
#define FLAGS AV_OPT_FLAG_ENCODING_PARAM
Functions
static int ebml_id_size (unsigned int id)
static void put_ebml_id (AVIOContext *pb, unsigned int id)
static void put_ebml_size_unknown (AVIOContext *pb, int bytes)
Write an EBML size meaning "unknown size".
static int ebml_num_size (uint64_t num)
Calculate how many bytes are needed to represent a given number in EBML.
static void put_ebml_num (AVIOContext *pb, uint64_t num, int bytes)
Write a number in EBML variable length format.
static void put_ebml_uint (AVIOContext *pb, unsigned int elementid, uint64_t val)
static void put_ebml_sint (AVIOContext *pb, unsigned int elementid, int64_t val)
static void put_ebml_float (AVIOContext *pb, unsigned int elementid, double val)
static void put_ebml_binary (AVIOContext *pb, unsigned int elementid, const void *buf, int size)
static void put_ebml_string (AVIOContext *pb, unsigned int elementid, const char *str)
static void put_ebml_void (AVIOContext *pb, uint64_t size)
Write a void element of a given size.
static ebml_master start_ebml_master (AVIOContext *pb, unsigned int elementid, uint64_t expectedsize)
static void end_ebml_master (AVIOContext *pb, ebml_master master)
static int start_ebml_master_crc32 (AVIOContext *pb, AVIOContext **dyn_cp, MatroskaMuxContext *mkv, ebml_master *master, unsigned int elementid, uint64_t expectedsize)
static void end_ebml_master_crc32 (AVIOContext *pb, AVIOContext **dyn_cp, MatroskaMuxContext *mkv, ebml_master master)
static void put_xiph_size (AVIOContext *pb, int size)
static void mkv_free (MatroskaMuxContext *mkv)
Free the members allocated in the mux context.
static mkv_seekhead * mkv_start_seekhead (AVIOContext *pb, int64_t segment_offset, int numelements)
Initialize a mkv_seekhead element to be ready to index level 1 Matroska elements.
static int mkv_add_seekhead_entry (mkv_seekhead *seekhead, unsigned int elementid, uint64_t filepos)
static int64_t mkv_write_seekhead (AVIOContext *pb, MatroskaMuxContext *mkv)
Write the seek head to the file and free it.
static mkv_cues * mkv_start_cues (int64_t segment_offset)
static int mkv_add_cuepoint (mkv_cues *cues, int stream, int tracknum, int64_t ts, int64_t cluster_pos, int64_t relative_pos, int64_t duration)
static int64_t mkv_write_cues (AVFormatContext *s, mkv_cues *cues, mkv_track *tracks, int num_tracks)
static int put_xiph_codecpriv (AVFormatContext *s, AVIOContext *pb, AVCodecParameters *par)
static int put_wv_codecpriv (AVIOContext *pb, AVCodecParameters *par)
static int put_flac_codecpriv (AVFormatContext *s, AVIOContext *pb, AVCodecParameters *par)
static int get_aac_sample_rates (AVFormatContext *s, AVCodecParameters *par, int *sample_rate, int *output_sample_rate)
static int mkv_write_native_codecprivate (AVFormatContext *s, AVCodecParameters *par, AVIOContext *dyn_cp)
static int mkv_write_codecprivate (AVFormatContext *s, AVIOContext *pb, AVCodecParameters *par, int native_id, int qt_id)
static int mkv_write_video_color (AVIOContext *pb, AVCodecParameters *par, AVStream *st)
static void mkv_write_field_order (AVIOContext *pb, int mode, enum AVFieldOrder field_order)
static int mkv_write_stereo_mode (AVFormatContext *s, AVIOContext *pb, AVStream *st, int mode, int *h_width, int *h_height)
static int mkv_write_track (AVFormatContext *s, MatroskaMuxContext *mkv, int i, AVIOContext *pb, int default_stream_exists)
static int mkv_write_tracks (AVFormatContext *s)
static int mkv_write_chapters (AVFormatContext *s)
static int mkv_write_simpletag (AVIOContext *pb, AVDictionaryEntry *t)
static int mkv_write_tag_targets (AVFormatContext *s, unsigned int elementid, unsigned int uid, ebml_master *tags, ebml_master *tag)
static int mkv_check_tag_name (const char *name, unsigned int elementid)
static int mkv_write_tag (AVFormatContext *s, AVDictionary *m, unsigned int elementid, unsigned int uid, ebml_master *tags)
static int mkv_check_tag (AVDictionary *m, unsigned int elementid)
static int mkv_write_tags (AVFormatContext *s)
static int mkv_write_attachments (AVFormatContext *s)
static int64_t get_metadata_duration (AVFormatContext *s)
static int mkv_write_header (AVFormatContext *s)
static int mkv_blockgroup_size (int pkt_size)
static int mkv_strip_wavpack (const uint8_t *src, uint8_t **pdst, int *size)
static void mkv_write_block (AVFormatContext *s, AVIOContext *pb, unsigned int blockid, AVPacket *pkt, int keyframe)
static int mkv_write_vtt_blocks (AVFormatContext *s, AVIOContext *pb, AVPacket *pkt)
static void mkv_start_new_cluster (AVFormatContext *s, AVPacket *pkt)
static int mkv_check_new_extra_data (AVFormatContext *s, AVPacket *pkt)
static int mkv_write_packet_internal (AVFormatContext *s, AVPacket *pkt, int add_cue)
static int mkv_write_packet (AVFormatContext *s, AVPacket *pkt)
static int mkv_write_flush_packet (AVFormatContext *s, AVPacket *pkt)
static int mkv_write_trailer (AVFormatContext *s)
static int mkv_query_codec (enum AVCodecID codec_id, int std_compliance)
static int mkv_init (struct AVFormatContext *s)
static int mkv_check_bitstream (struct AVFormatContext *s, const AVPacket *pkt)
Variables
static const AVCodecTag additional_audio_tags []
static const AVCodecTag additional_video_tags []
static const AVCodecTag additional_subtitle_tags []
static const AVOption options []
Macro Definition Documentation
MODE_MATROSKAv2
#define MODE_MATROSKAv2 0x01
Definition at line 110 of file matroskaenc.c.
Referenced by mkv_write_header().
MODE_WEBM
#define MODE_WEBM 0x02
Definition at line 111 of file matroskaenc.c.
Referenced by end_ebml_master_crc32(), mkv_write_field_order(), mkv_write_header(), mkv_write_stereo_mode(), mkv_write_track(), mkv_write_trailer(), and start_ebml_master_crc32().
MAX_TRACKS
#define MAX_TRACKS 126
Maximum number of tracks allowed in a Matroska file (with track numbers in range 1 to 126 (inclusive)
Definition at line 115 of file matroskaenc.c.
MAX_SEEKENTRY_SIZE
#define MAX_SEEKENTRY_SIZE 21
2 bytes * 3 for EBML IDs, 3 1-byte EBML lengths, 8 bytes for 64 bit offset, 4 bytes for target EBML ID
Definition at line 167 of file matroskaenc.c.
Referenced by mkv_start_seekhead(), and mkv_write_seekhead().
MAX_CUETRACKPOS_SIZE
#define MAX_CUETRACKPOS_SIZE 42
per-cuepoint-track - 5 1-byte EBML IDs, 5 1-byte EBML sizes, 4 8-byte uint max
Definition at line 171 of file matroskaenc.c.
Referenced by mkv_write_cues().
MAX_CUEPOINT_SIZE
#define MAX_CUEPOINT_SIZE (num_tracks) 12 + MAX_CUETRACKPOS_SIZE * num_tracks
per-cuepoint - 2 1-byte EBML IDs, 2 1-byte EBML sizes, 8-byte uint max
Definition at line 174 of file matroskaenc.c.
Referenced by mkv_write_cues().
OPUS_SEEK_PREROLL
#define OPUS_SEEK_PREROLL 80000000
Seek preroll value for opus.
Definition at line 177 of file matroskaenc.c.
Referenced by mkv_write_track().
OFFSET
#define OFFSET (x) offsetof(MatroskaMuxContext, x)
Definition at line 2522 of file matroskaenc.c.
FLAGS
#define FLAGS AV_OPT_FLAG_ENCODING_PARAM
Definition at line 2523 of file matroskaenc.c.
Function Documentation
ebml_id_size()
static int ebml_id_size (unsigned int id) static
Definition at line 179 of file matroskaenc.c.
Referenced by mkv_write_seekhead(), and put_ebml_id().
put_ebml_id()
static void put_ebml_id (AVIOContext * pb, unsigned int id) static
Definition at line 184 of file matroskaenc.c.
Referenced by mkv_write_block(), mkv_write_seekhead(), mkv_write_vtt_blocks(), put_ebml_binary(), put_ebml_float(), put_ebml_sint(), put_ebml_uint(), put_ebml_void(), and start_ebml_master().
put_ebml_size_unknown()
static void put_ebml_size_unknown (AVIOContext * pb, int bytes) static
Write an EBML size meaning "unknown size".
Parameters
bytes The number of bytes the size should occupy (maximum: 8).
Definition at line 196 of file matroskaenc.c.
Referenced by start_ebml_master().
ebml_num_size()
static int ebml_num_size (uint64_t num) static
Calculate how many bytes are needed to represent a given number in EBML.
Definition at line 206 of file matroskaenc.c.
Referenced by mkv_blockgroup_size(), put_ebml_num(), and start_ebml_master().
put_ebml_num()
static void put_ebml_num (AVIOContext * pb, uint64_t num, int bytes) static
Write a number in EBML variable length format.
Parameters
bytes The number of bytes that need to be used to write the number. If zero, any number of bytes can be used.
Definition at line 220 of file matroskaenc.c.
Referenced by end_ebml_master(), mkv_write_block(), mkv_write_seekhead(), mkv_write_vtt_blocks(), put_ebml_binary(), put_ebml_float(), put_ebml_sint(), put_ebml_uint(), and put_ebml_void().
put_ebml_uint()
static void put_ebml_uint (AVIOContext * pb, unsigned int elementid, uint64_t val) static
Definition at line 239 of file matroskaenc.c.
Referenced by mkv_write_attachments(), mkv_write_block(), mkv_write_chapters(), mkv_write_cues(), mkv_write_field_order(), mkv_write_header(), mkv_write_packet_internal(), mkv_write_seekhead(), mkv_write_stereo_mode(), mkv_write_tag_targets(), mkv_write_track(), mkv_write_video_color(), and mkv_write_vtt_blocks().
put_ebml_sint()
static void put_ebml_sint (AVIOContext * pb, unsigned int elementid, int64_t val) static
Definition at line 252 of file matroskaenc.c.
Referenced by mkv_write_block().
put_ebml_float()
static void put_ebml_float (AVIOContext * pb, unsigned int elementid, double val) static
Definition at line 265 of file matroskaenc.c.
Referenced by mkv_write_header(), mkv_write_track(), mkv_write_trailer(), and mkv_write_video_color().
put_ebml_binary()
static void put_ebml_binary (AVIOContext * pb, unsigned int elementid, const void * buf, int size) static
Definition at line 272 of file matroskaenc.c.
Referenced by end_ebml_master_crc32(), mkv_write_attachments(), mkv_write_codecprivate(), mkv_write_header(), mkv_write_track(), mkv_write_trailer(), and put_ebml_string().
put_ebml_string()
static void put_ebml_string (AVIOContext * pb, unsigned int elementid, const char * str) static
Definition at line 280 of file matroskaenc.c.
Referenced by mkv_write_attachments(), mkv_write_chapters(), mkv_write_header(), mkv_write_simpletag(), mkv_write_tags(), and mkv_write_track().
put_ebml_void()
static void put_ebml_void (AVIOContext * pb, uint64_t size) static
Write a void element of a given size.
Useful for reserving space in the file to be written to later.
Parameters
size The number of bytes to reserve, which must be at least 2.
Definition at line 292 of file matroskaenc.c.
Referenced by mkv_start_seekhead(), mkv_write_header(), mkv_write_seekhead(), mkv_write_tags(), mkv_write_tracks(), mkv_write_trailer(), and start_ebml_master_crc32().
start_ebml_master()
static ebml_master start_ebml_master (AVIOContext * pb, unsigned int elementid, uint64_t expectedsize) static
Definition at line 309 of file matroskaenc.c.
Referenced by mkv_write_attachments(), mkv_write_block(), mkv_write_chapters(), mkv_write_cues(), mkv_write_header(), mkv_write_packet_internal(), mkv_write_seekhead(), mkv_write_simpletag(), mkv_write_tag_targets(), mkv_write_tags(), mkv_write_track(), mkv_write_video_color(), mkv_write_vtt_blocks(), and start_ebml_master_crc32().
end_ebml_master()
static void end_ebml_master (AVIOContext * pb, ebml_master master) static
Definition at line 318 of file matroskaenc.c.
Referenced by end_ebml_master_crc32(), mkv_write_attachments(), mkv_write_block(), mkv_write_chapters(), mkv_write_cues(), mkv_write_header(), mkv_write_packet_internal(), mkv_write_seekhead(), mkv_write_simpletag(), mkv_write_tag(), mkv_write_tag_targets(), mkv_write_tags(), mkv_write_track(), mkv_write_trailer(), mkv_write_video_color(), and mkv_write_vtt_blocks().
start_ebml_master_crc32()
static int start_ebml_master_crc32 (AVIOContext * pb, AVIOContext ** dyn_cp, MatroskaMuxContext * mkv, ebml_master * master, unsigned int elementid, uint64_t expectedsize) static
Definition at line 328 of file matroskaenc.c.
Referenced by mkv_write_attachments(), mkv_write_chapters(), mkv_write_cues(), mkv_write_header(), mkv_write_packet_internal(), mkv_write_seekhead(), mkv_write_tag_targets(), and mkv_write_tracks().
end_ebml_master_crc32()
static void end_ebml_master_crc32 (AVIOContext * pb, AVIOContext ** dyn_cp, MatroskaMuxContext * mkv, ebml_master master) static
Definition at line 346 of file matroskaenc.c.
Referenced by mkv_start_new_cluster(), mkv_write_attachments(), mkv_write_chapters(), mkv_write_cues(), mkv_write_flush_packet(), mkv_write_header(), mkv_write_seekhead(), mkv_write_tags(), mkv_write_tracks(), and mkv_write_trailer().
put_xiph_size()
static void put_xiph_size (AVIOContext * pb, int size) static
Definition at line 370 of file matroskaenc.c.
Referenced by put_xiph_codecpriv().
mkv_free()
static void mkv_free (MatroskaMuxContext * mkv) static
Free the members allocated in the mux context.
Definition at line 379 of file matroskaenc.c.
Referenced by mkv_write_header(), and mkv_write_trailer().
mkv_start_seekhead()
static mkv_seekhead* mkv_start_seekhead (AVIOContext * pb, int64_t segment_offset, int numelements) static
Initialize a mkv_seekhead element to be ready to index level 1 Matroska elements.
If a maximum number of elements is specified, enough space will be reserved at the current file location to write a seek head of that size.
Parameters
segment_offset The absolute offset to the position in the file where the segment begins.
numelements The maximum number of elements that will be indexed by this seek head, 0 if unlimited.
Definition at line 408 of file matroskaenc.c.
Referenced by mkv_write_header().
mkv_add_seekhead_entry()
static int mkv_add_seekhead_entry (mkv_seekhead * seekhead, unsigned int elementid, uint64_t filepos) static
Definition at line 429 of file matroskaenc.c.
Referenced by mkv_write_attachments(), mkv_write_chapters(), mkv_write_header(), mkv_write_tag_targets(), mkv_write_tracks(), and mkv_write_trailer().
mkv_write_seekhead()
static int64_t mkv_write_seekhead (AVIOContext * pb, MatroskaMuxContext * mkv) static
Write the seek head to the file and free it.
If a maximum number of elements was specified to mkv_start_seekhead(), the seek head will be written at the location reserved for it. Otherwise, it is written at the current location in the file.
Returns
The file offset where the seekhead was written, -1 if an error occurred.
Definition at line 457 of file matroskaenc.c.
Referenced by mkv_write_header(), and mkv_write_trailer().
mkv_start_cues()
static mkv_cues* mkv_start_cues (int64_t segment_offset) static
Definition at line 508 of file matroskaenc.c.
Referenced by mkv_write_header().
mkv_add_cuepoint()
static int mkv_add_cuepoint (mkv_cues * cues, int stream, int tracknum, int64_t ts, int64_t cluster_pos, int64_t relative_pos, int64_t duration) static
Definition at line 518 of file matroskaenc.c.
Referenced by mkv_write_packet_internal().
mkv_write_cues()
static int64_t mkv_write_cues (AVFormatContext * s, mkv_cues * cues, mkv_track * tracks, int num_tracks) static
Definition at line 541 of file matroskaenc.c.
Referenced by mkv_write_trailer().
put_xiph_codecpriv()
static int put_xiph_codecpriv (AVFormatContext * s, AVIOContext * pb, AVCodecParameters * par) static
Definition at line 601 of file matroskaenc.c.
Referenced by mkv_write_native_codecprivate().
put_wv_codecpriv()
static int put_wv_codecpriv (AVIOContext * pb, AVCodecParameters * par) static
Definition at line 629 of file matroskaenc.c.
Referenced by mkv_write_native_codecprivate().
put_flac_codecpriv()
static int put_flac_codecpriv (AVFormatContext * s, AVIOContext * pb, AVCodecParameters * par) static
Definition at line 638 of file matroskaenc.c.
Referenced by mkv_write_native_codecprivate().
get_aac_sample_rates()
static int get_aac_sample_rates (AVFormatContext * s, AVCodecParameters * par, int * sample_rate, int * output_sample_rate) static
Definition at line 685 of file matroskaenc.c.
Referenced by mkv_write_track().
mkv_write_native_codecprivate()
static int mkv_write_native_codecprivate (AVFormatContext * s, AVCodecParameters * par, AVIOContext * dyn_cp) static
Definition at line 702 of file matroskaenc.c.
Referenced by mkv_write_codecprivate().
mkv_write_codecprivate()
static int mkv_write_codecprivate (AVFormatContext * s, AVIOContext * pb, AVCodecParameters * par, int native_id, int qt_id) static
Definition at line 742 of file matroskaenc.c.
Referenced by mkv_check_new_extra_data(), and mkv_write_track().
mkv_write_video_color()
static int mkv_write_video_color (AVIOContext * pb, AVCodecParameters * par, AVStream * st) static
Definition at line 809 of file matroskaenc.c.
Referenced by mkv_write_track().
mkv_write_field_order()
static void mkv_write_field_order (AVIOContext * pb, int mode, enum AVFieldOrder field_order) static
Definition at line 888 of file matroskaenc.c.
Referenced by mkv_write_track().
mkv_write_stereo_mode()
static int mkv_write_stereo_mode (AVFormatContext * s, AVIOContext * pb, AVStream * st, int mode, int * h_width, int * h_height) static
Definition at line 927 of file matroskaenc.c.
Referenced by mkv_write_track().
mkv_write_track()
static int mkv_write_track (AVFormatContext * s, MatroskaMuxContext * mkv, int i, AVIOContext * pb, int default_stream_exists) static
Definition at line 1025 of file matroskaenc.c.
Referenced by mkv_write_tracks().
mkv_write_tracks()
static int mkv_write_tracks (AVFormatContext * s) static
Definition at line 1287 of file matroskaenc.c.
Referenced by mkv_write_header().
mkv_write_chapters()
static int mkv_write_chapters (AVFormatContext * s) static
Definition at line 1319 of file matroskaenc.c.
Referenced by mkv_write_header(), and mkv_write_trailer().
mkv_write_simpletag()
static int mkv_write_simpletag (AVIOContext * pb, AVDictionaryEntry * t) static
Definition at line 1373 of file matroskaenc.c.
Referenced by mkv_write_tag().
mkv_write_tag_targets()
static int mkv_write_tag_targets (AVFormatContext * s, unsigned int elementid, unsigned int uid, ebml_master * tags, ebml_master * tag) static
Definition at line 1407 of file matroskaenc.c.
Referenced by mkv_write_tag(), and mkv_write_tags().
mkv_check_tag_name()
static int mkv_check_tag_name (const char * name, unsigned int elementid) static
Definition at line 1432 of file matroskaenc.c.
Referenced by mkv_check_tag(), and mkv_write_tag().
mkv_write_tag()
static int mkv_write_tag (AVFormatContext * s, AVDictionary * m, unsigned int elementid, unsigned int uid, ebml_master * tags) static
Definition at line 1446 of file matroskaenc.c.
Referenced by mkv_write_tags().
mkv_check_tag()
static int mkv_check_tag (AVDictionary * m, unsigned int elementid) static
Definition at line 1470 of file matroskaenc.c.
Referenced by mkv_write_tags().
mkv_write_tags()
static int mkv_write_tags (AVFormatContext * s) static
Definition at line 1481 of file matroskaenc.c.
Referenced by mkv_write_header().
mkv_write_attachments()
static int mkv_write_attachments (AVFormatContext * s) static
Definition at line 1564 of file matroskaenc.c.
Referenced by mkv_write_header().
get_metadata_duration()
static int64_t get_metadata_duration (AVFormatContext * s) static
Definition at line 1662 of file matroskaenc.c.
Referenced by mkv_write_header().
mkv_write_header()
static int mkv_write_header (AVFormatContext * s) static
Definition at line 1686 of file matroskaenc.c.
mkv_blockgroup_size()
static int mkv_blockgroup_size (int pkt_size) static
Definition at line 1883 of file matroskaenc.c.
Referenced by mkv_write_packet_internal(), and mkv_write_vtt_blocks().
mkv_strip_wavpack()
static int mkv_strip_wavpack (const uint8_t * src, uint8_t ** pdst, int * size) static
Definition at line 1894 of file matroskaenc.c.
Referenced by mkv_write_block().
mkv_write_block()
static void mkv_write_block (AVFormatContext * s, AVIOContext * pb, unsigned int blockid, AVPacket * pkt, int keyframe) static
Definition at line 1947 of file matroskaenc.c.
Referenced by mkv_write_packet_internal().
mkv_write_vtt_blocks()
static int mkv_write_vtt_blocks (AVFormatContext * s, AVIOContext * pb, AVPacket * pkt) static
Definition at line 2046 of file matroskaenc.c.
Referenced by mkv_write_packet_internal().
mkv_start_new_cluster()
static void mkv_start_new_cluster (AVFormatContext * s, AVPacket * pkt) static
Definition at line 2084 of file matroskaenc.c.
Referenced by mkv_write_packet(), and mkv_write_packet_internal().
mkv_check_new_extra_data()
static int mkv_check_new_extra_data (AVFormatContext * s, AVPacket * pkt) static
Definition at line 2102 of file matroskaenc.c.
Referenced by mkv_write_packet().
mkv_write_packet_internal()
static int mkv_write_packet_internal (AVFormatContext * s, AVPacket * pkt, int add_cue) static
Definition at line 2148 of file matroskaenc.c.
Referenced by mkv_write_packet(), and mkv_write_trailer().
mkv_write_packet()
static int mkv_write_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 2230 of file matroskaenc.c.
Referenced by mkv_write_flush_packet().
mkv_write_flush_packet()
static int mkv_write_flush_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 2305 of file matroskaenc.c.
mkv_write_trailer()
static int mkv_write_trailer (AVFormatContext * s) static
Definition at line 2326 of file matroskaenc.c.
mkv_query_codec()
static int mkv_query_codec (enum AVCodecID codec_id, int std_compliance) static
Definition at line 2442 of file matroskaenc.c.
mkv_init()
static int mkv_init (struct AVFormatContext * s) static
Definition at line 2459 of file matroskaenc.c.
mkv_check_bitstream()
static int mkv_check_bitstream (struct AVFormatContext * s, const AVPacket * pkt) static
Definition at line 2476 of file matroskaenc.c.
Variable Documentation
additional_audio_tags
const AVCodecTag additional_audio_tags[] static
Initial value:
= {
    { AV_CODEC_ID_ALAC,      0XFFFFFFFF },
    { AV_CODEC_ID_EAC3,      0XFFFFFFFF },
    { AV_CODEC_ID_MLP,       0xFFFFFFFF },
    { AV_CODEC_ID_OPUS,      0xFFFFFFFF },
    { AV_CODEC_ID_PCM_S16BE, 0xFFFFFFFF },
    { AV_CODEC_ID_PCM_S24BE, 0xFFFFFFFF },
    { AV_CODEC_ID_PCM_S32BE, 0xFFFFFFFF },
    { AV_CODEC_ID_QDM2,      0xFFFFFFFF },
    { AV_CODEC_ID_RA_144,    0xFFFFFFFF },
    { AV_CODEC_ID_RA_288,    0xFFFFFFFF },
    { AV_CODEC_ID_COOK,      0xFFFFFFFF },
    { AV_CODEC_ID_TRUEHD,    0xFFFFFFFF },
    { AV_CODEC_ID_NONE,      0xFFFFFFFF }
}
Definition at line 2491 of file matroskaenc.c.
additional_video_tags
const AVCodecTag additional_video_tags[] static
Initial value:
= {
    { AV_CODEC_ID_RV10,      0xFFFFFFFF },
    { AV_CODEC_ID_RV20,      0xFFFFFFFF },
    { AV_CODEC_ID_RV30,      0xFFFFFFFF },
    { AV_CODEC_ID_RV40,      0xFFFFFFFF },
    { AV_CODEC_ID_VP9,       0xFFFFFFFF },
    { AV_CODEC_ID_NONE,      0xFFFFFFFF }
}
Definition at line 2507 of file matroskaenc.c.
additional_subtitle_tags
const AVCodecTag additional_subtitle_tags[] static
Initial value:
= {
    { AV_CODEC_ID_DVB_SUBTITLE,      0xFFFFFFFF },
    { AV_CODEC_ID_HDMV_PGS_SUBTITLE, 0xFFFFFFFF },
    { AV_CODEC_ID_NONE,              0xFFFFFFFF }
}
Definition at line 2516 of file matroskaenc.c.
options
const AVOption options[] static
Initial value:
= {
    { "reserve_index_space", "Reserve a given amount of space (in bytes) at the beginning of the file for the index (cues).", OFFSET(reserve_cues_space), AV_OPT_TYPE_INT,   { .i64 = 0 },   0, INT_MAX,   FLAGS },
    { "cluster_size_limit",  "Store at most the provided amount of bytes in a cluster. ",                                     OFFSET(cluster_size_limit), AV_OPT_TYPE_INT  , { .i64 = -1 }, -1, INT_MAX,   FLAGS },
    { "cluster_time_limit",  "Store at most the provided number of milliseconds in a cluster.",                               OFFSET(cluster_time_limit), AV_OPT_TYPE_INT64, { .i64 = -1 }, -1, INT64_MAX, FLAGS },
    { "dash", "Create a WebM file conforming to WebM DASH specification", OFFSET(is_dash), AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, FLAGS },
    { "dash_track_number", "Track number for the DASH stream", OFFSET(dash_track_number), AV_OPT_TYPE_INT, { .i64 = 1 }, 0, 127, FLAGS },
    { "live", "Write files assuming it is a live stream.", OFFSET(is_live), AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, FLAGS },
    { "allow_raw_vfw", "allow RAW VFW mode", OFFSET(allow_raw_vfw), AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, FLAGS },
    { "write_crc32", "write a CRC32 element inside every Level 1 element", OFFSET(write_crc), AV_OPT_TYPE_BOOL, { .i64 = 1 }, 0, 1, FLAGS },
    { NULL },
}
Definition at line 2524 of file matroskaenc.c.