FFmpeg: libavformat/matroskadec.c File Reference
matroskadec.c File Reference
Matroska file demuxer.
#include "config.h"
#include <inttypes.h>
#include <stdio.h>
#include "libavutil/avstring.h"
#include "libavutil/base64.h"
#include "libavutil/dict.h"
#include "libavutil/intfloat.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/lzo.h"
#include "libavutil/mastering_display_metadata.h"
#include "libavutil/mathematics.h"
#include "libavutil/opt.h"
#include "libavutil/time_internal.h"
#include "libavutil/spherical.h"
#include "libavcodec/bytestream.h"
#include "libavcodec/flac.h"
#include "libavcodec/mpeg4audio.h"
#include "avformat.h"
#include "avio_internal.h"
#include "internal.h"
#include "isom.h"
#include "matroska.h"
#include "oggdec.h"
#include "riff.h"
#include "rmsipr.h"
#include "qtpalette.h"
Data Structures
struct EbmlSyntax
struct EbmlList
struct EbmlBin
struct Ebml
struct MatroskaTrackCompression
struct MatroskaTrackEncryption
struct MatroskaTrackEncoding
struct MatroskaMasteringMeta
struct MatroskaTrackVideoColor
struct MatroskaTrackVideoProjection
struct MatroskaTrackVideo
struct MatroskaTrackAudio
struct MatroskaTrackPlane
struct MatroskaTrackOperation
struct MatroskaTrack
struct MatroskaAttachment
struct MatroskaChapter
struct MatroskaIndexPos
struct MatroskaIndex
struct MatroskaTag
struct MatroskaTagTarget
struct MatroskaTags
struct MatroskaSeekhead
struct MatroskaLevel
struct MatroskaCluster
struct MatroskaLevel1Element
struct MatroskaDemuxContext
struct MatroskaBlock
struct CueDesc
Macros
#define OFFSET(x) offsetof(MatroskaDemuxContext, x)
Enumerations
enum EbmlType {
EBML_NONE, EBML_UINT, EBML_FLOAT, EBML_STR,
EBML_UTF8, EBML_BIN, EBML_NEST, EBML_LEVEL1,
EBML_PASS, EBML_STOP, EBML_SINT, EBML_TYPE_COUNT
}
Functions
static int matroska_read_close (AVFormatContext *s)
static int matroska_resync (MatroskaDemuxContext *matroska, int64_t last_pos)
static int ebml_level_end (MatroskaDemuxContext *matroska)
static int ebml_read_num (MatroskaDemuxContext *matroska, AVIOContext *pb, int max_size, uint64_t *number)
static int ebml_read_length (MatroskaDemuxContext *matroska, AVIOContext *pb, uint64_t *number)
Read a EBML length value.
static int ebml_read_uint (AVIOContext *pb, int size, uint64_t *num)
static int ebml_read_sint (AVIOContext *pb, int size, int64_t *num)
static int ebml_read_float (AVIOContext *pb, int size, double *num)
static int ebml_read_ascii (AVIOContext *pb, int size, char **str)
static int ebml_read_binary (AVIOContext *pb, int length, EbmlBin *bin)
static int ebml_read_master (MatroskaDemuxContext *matroska, uint64_t length)
static int matroska_ebmlnum_uint (MatroskaDemuxContext *matroska, uint8_t *data, uint32_t size, uint64_t *num)
static int matroska_ebmlnum_sint (MatroskaDemuxContext *matroska, uint8_t *data, uint32_t size, int64_t *num)
static int ebml_parse_elem (MatroskaDemuxContext *matroska, EbmlSyntax *syntax, void *data)
static int ebml_parse_id (MatroskaDemuxContext *matroska, EbmlSyntax *syntax, uint32_t id, void *data)
static int ebml_parse (MatroskaDemuxContext *matroska, EbmlSyntax *syntax, void *data)
static int ebml_parse_nest (MatroskaDemuxContext *matroska, EbmlSyntax *syntax, void *data)
static int is_ebml_id_valid (uint32_t id)
static MatroskaLevel1Element * matroska_find_level1_elem (MatroskaDemuxContext *matroska, uint32_t id)
static void ebml_free (EbmlSyntax *syntax, void *data)
static int matroska_probe (AVProbeData *p)
static MatroskaTrack * matroska_find_track_by_num (MatroskaDemuxContext *matroska, int num)
static int matroska_decode_buffer (uint8_t **buf, int *buf_size, MatroskaTrack *track)
static void matroska_convert_tag (AVFormatContext *s, EbmlList *list, AVDictionary **metadata, char *prefix)
static void matroska_convert_tags (AVFormatContext *s)
static int matroska_parse_seekhead_entry (MatroskaDemuxContext *matroska, uint64_t pos)
static void matroska_execute_seekhead (MatroskaDemuxContext *matroska)
static void matroska_add_index_entries (MatroskaDemuxContext *matroska)
static void matroska_parse_cues (MatroskaDemuxContext *matroska)
static int matroska_aac_profile (char *codec_id)
static int matroska_aac_sri (int samplerate)
static void matroska_metadata_creation_time (AVDictionary **metadata, int64_t date_utc)
static int matroska_parse_flac (AVFormatContext *s, MatroskaTrack *track, int *offset)
static int mkv_field_order (MatroskaDemuxContext *matroska, int64_t field_order)
static void mkv_stereo_mode_display_mul (int stereo_mode, int *h_width, int *h_height)
static int mkv_parse_video_color (AVStream *st, const MatroskaTrack *track)
static int mkv_parse_video_projection (AVStream *st, const MatroskaTrack *track)
static int get_qt_codec (MatroskaTrack *track, uint32_t *fourcc, enum AVCodecID *codec_id)
static int matroska_parse_tracks (AVFormatContext *s)
static int matroska_read_header (AVFormatContext *s)
static int matroska_deliver_packet (MatroskaDemuxContext *matroska, AVPacket *pkt)
static void matroska_clear_queue (MatroskaDemuxContext *matroska)
static int matroska_parse_laces (MatroskaDemuxContext *matroska, uint8_t **buf, int *buf_size, int type, uint32_t **lace_buf, int *laces)
static int matroska_parse_rm_audio (MatroskaDemuxContext *matroska, MatroskaTrack *track, AVStream *st, uint8_t *data, int size, uint64_t timecode, int64_t pos)
static int matroska_parse_wavpack (MatroskaTrack *track, uint8_t *src, uint8_t **pdst, int *size)
static int matroska_parse_webvtt (MatroskaDemuxContext *matroska, MatroskaTrack *track, AVStream *st, uint8_t *data, int data_len, uint64_t timecode, uint64_t duration, int64_t pos)
static int matroska_parse_frame (MatroskaDemuxContext *matroska, MatroskaTrack *track, AVStream *st, uint8_t *data, int pkt_size, uint64_t timecode, uint64_t lace_duration, int64_t pos, int is_keyframe, uint8_t *additional, uint64_t additional_id, int additional_size, int64_t discard_padding)
static int matroska_parse_block (MatroskaDemuxContext *matroska, uint8_t *data, int size, int64_t pos, uint64_t cluster_time, uint64_t block_duration, int is_keyframe, uint8_t *additional, uint64_t additional_id, int additional_size, int64_t cluster_pos, int64_t discard_padding)
static int matroska_parse_cluster_incremental (MatroskaDemuxContext *matroska)
static int matroska_parse_cluster (MatroskaDemuxContext *matroska)
static int matroska_read_packet (AVFormatContext *s, AVPacket *pkt)
static int matroska_read_seek (AVFormatContext *s, int stream_index, int64_t timestamp, int flags)
static CueDesc get_cue_desc (AVFormatContext *s, int64_t ts, int64_t cues_start)
static int webm_clusters_start_with_keyframe (AVFormatContext *s)
static int buffer_size_after_time_downloaded (int64_t time_ns, double search_sec, int64_t bps, double min_buffer, double *buffer, double *sec_to_download, AVFormatContext *s, int64_t cues_start)
static int64_t webm_dash_manifest_compute_bandwidth (AVFormatContext *s, int64_t cues_start)
static int webm_dash_manifest_cues (AVFormatContext *s)
static int webm_dash_manifest_read_header (AVFormatContext *s)
static int webm_dash_manifest_read_packet (AVFormatContext *s, AVPacket *pkt)
Variables
static const EbmlSyntax ebml_header []
static const EbmlSyntax ebml_syntax []
static const EbmlSyntax matroska_info []
static const EbmlSyntax matroska_mastering_meta []
static const EbmlSyntax matroska_track_video_color []
static const EbmlSyntax matroska_track_video_projection []
static const EbmlSyntax matroska_track_video []
static const EbmlSyntax matroska_track_audio []
static const EbmlSyntax matroska_track_encoding_compression []
static const EbmlSyntax matroska_track_encoding_encryption []
static const EbmlSyntax matroska_track_encoding []
static const EbmlSyntax matroska_track_encodings []
static const EbmlSyntax matroska_track_plane []
static const EbmlSyntax matroska_track_combine_planes []
static const EbmlSyntax matroska_track_operation []
static const EbmlSyntax matroska_track []
static const EbmlSyntax matroska_tracks []
static const EbmlSyntax matroska_attachment []
static const EbmlSyntax matroska_attachments []
static const EbmlSyntax matroska_chapter_display []
static const EbmlSyntax matroska_chapter_entry []
static const EbmlSyntax matroska_chapter []
static const EbmlSyntax matroska_chapters []
static const EbmlSyntax matroska_index_pos []
static const EbmlSyntax matroska_index_entry []
static const EbmlSyntax matroska_index []
static const EbmlSyntax matroska_simpletag []
static const EbmlSyntax matroska_tagtargets []
static const EbmlSyntax matroska_tag []
static const EbmlSyntax matroska_tags []
static const EbmlSyntax matroska_seekhead_entry []
static const EbmlSyntax matroska_seekhead []
static const EbmlSyntax matroska_segment []
static const EbmlSyntax matroska_segments []
static const EbmlSyntax matroska_blockmore []
static const EbmlSyntax matroska_blockadditions []
static const EbmlSyntax matroska_blockgroup []
static const EbmlSyntax matroska_cluster []
static const EbmlSyntax matroska_clusters []
static const EbmlSyntax matroska_cluster_incremental_parsing []
static const EbmlSyntax matroska_cluster_incremental []
static const EbmlSyntax matroska_clusters_incremental []
static const char *const matroska_doctypes [] = { "matroska", "webm" }
static const AVOption options []
static const AVClass webm_dash_class
AVInputFormat ff_matroska_demuxer
AVInputFormat ff_webm_dash_manifest_demuxer
Detailed Description
Matroska file demuxer.
Author
Ronald Bultje rbult.nosp@m.je@r.nosp@m.onald.nosp@m..bit.nosp@m.freak.nosp@m..net
with a little help from Moritz Bunkus morit.nosp@m.z@bu.nosp@m.nkus..nosp@m.org
totally reworked by Aurelien Jacobs aurel.nosp@m.@gnu.nosp@m.age.o.nosp@m.rg
See also
specs available on the Matroska project page: http://www.matroska.org/
Definition in file matroskadec.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(MatroskaDemuxContext, x)
Definition at line 3871 of file matroskadec.c.
Enumeration Type Documentation
EbmlType
enum EbmlType
Enumerator
EBML_NONE
EBML_UINT
EBML_FLOAT
EBML_STR
EBML_UTF8
EBML_BIN
EBML_NEST
EBML_LEVEL1
EBML_PASS
EBML_STOP
EBML_SINT
EBML_TYPE_COUNT
Definition at line 71 of file matroskadec.c.
Function Documentation
matroska_read_close()
static int matroska_read_close (AVFormatContext * s) static
Definition at line 3499 of file matroskadec.c.
Referenced by matroska_read_header(), and webm_dash_manifest_read_header().
matroska_resync()
static int matroska_resync (MatroskaDemuxContext * matroska, int64_t last_pos) static
Definition at line 759 of file matroskadec.c.
Referenced by matroska_read_header(), and matroska_read_packet().
ebml_level_end()
static int ebml_level_end (MatroskaDemuxContext * matroska) static
Definition at line 794 of file matroskadec.c.
Referenced by ebml_parse_nest(), and matroska_parse_cluster_incremental().
ebml_read_num()
static int ebml_read_num (MatroskaDemuxContext * matroska, AVIOContext * pb, int max_size, uint64_t * number) static
Definition at line 817 of file matroskadec.c.
Referenced by ebml_parse(), ebml_read_length(), matroska_ebmlnum_uint(), webm_clusters_start_with_keyframe(), and webm_dash_manifest_cues().
ebml_read_length()
static int ebml_read_length (MatroskaDemuxContext * matroska, AVIOContext * pb, uint64_t * number) static
Read a EBML length value.
This needs special handling for the "unknown length" case which has multiple encodings.
Definition at line 863 of file matroskadec.c.
Referenced by ebml_parse_elem(), webm_clusters_start_with_keyframe(), and webm_dash_manifest_cues().
ebml_read_uint()
static int ebml_read_uint (AVIOContext * pb, int size, uint64_t * num) static
Definition at line 876 of file matroskadec.c.
Referenced by ebml_parse_elem().
ebml_read_sint()
static int ebml_read_sint (AVIOContext * pb, int size, int64_t * num) static
Definition at line 895 of file matroskadec.c.
Referenced by ebml_parse_elem().
ebml_read_float()
static int ebml_read_float (AVIOContext * pb, int size, double * num) static
Definition at line 919 of file matroskadec.c.
Referenced by ebml_parse_elem().
ebml_read_ascii()
static int ebml_read_ascii (AVIOContext * pb, int size, char ** str) static
Definition at line 937 of file matroskadec.c.
Referenced by ebml_parse_elem().
ebml_read_binary()
static int ebml_read_binary (AVIOContext * pb, int length, EbmlBin * bin) static
Definition at line 960 of file matroskadec.c.
Referenced by ebml_parse_elem().
ebml_read_master()
static int ebml_read_master (MatroskaDemuxContext * matroska, uint64_t length) static
Definition at line 982 of file matroskadec.c.
Referenced by ebml_parse_elem().
matroska_ebmlnum_uint()
static int matroska_ebmlnum_uint (MatroskaDemuxContext * matroska, uint8_t * data, uint32_t size, uint64_t * num) static
Definition at line 1004 of file matroskadec.c.
Referenced by matroska_ebmlnum_sint(), matroska_parse_block(), and matroska_parse_laces().
matroska_ebmlnum_sint()
static int matroska_ebmlnum_sint (MatroskaDemuxContext * matroska, uint8_t * data, uint32_t size, int64_t * num) static
Definition at line 1015 of file matroskadec.c.
Referenced by matroska_parse_laces().
ebml_parse_elem()
static int ebml_parse_elem (MatroskaDemuxContext * matroska, EbmlSyntax * syntax, void * data) static
Definition at line 1146 of file matroskadec.c.
Referenced by ebml_parse_id(), and matroska_ebmlnum_sint().
ebml_parse_id()
static int ebml_parse_id (MatroskaDemuxContext * matroska, EbmlSyntax * syntax, uint32_t id, void * data) static
Definition at line 1034 of file matroskadec.c.
Referenced by ebml_parse(), and ebml_parse_elem().
ebml_parse()
static int ebml_parse (MatroskaDemuxContext * matroska, EbmlSyntax * syntax, void * data) static
Definition at line 1051 of file matroskadec.c.
Referenced by ebml_parse_nest(), matroska_parse_cluster(), matroska_parse_cluster_incremental(), matroska_parse_seekhead_entry(), and matroska_read_header().
ebml_parse_nest()
static int ebml_parse_nest (MatroskaDemuxContext * matroska, EbmlSyntax * syntax, void * data) static
Definition at line 1067 of file matroskadec.c.
Referenced by ebml_parse_elem().
is_ebml_id_valid()
static int is_ebml_id_valid (uint32_t id) static
Definition at line 1098 of file matroskadec.c.
Referenced by matroska_find_level1_elem().
matroska_find_level1_elem()
static MatroskaLevel1Element* matroska_find_level1_elem (MatroskaDemuxContext * matroska, uint32_t id) static
Definition at line 1111 of file matroskadec.c.
Referenced by ebml_parse_elem(), and matroska_execute_seekhead().
ebml_free()
static void ebml_free (EbmlSyntax * syntax, void * data) static
Definition at line 1238 of file matroskadec.c.
Referenced by matroska_parse_cluster(), matroska_parse_cluster_incremental(), matroska_read_close(), and matroska_read_header().
matroska_probe()
static int matroska_probe (AVProbeData * p) static
Definition at line 1272 of file matroskadec.c.
matroska_find_track_by_num()
static MatroskaTrack* matroska_find_track_by_num (MatroskaDemuxContext * matroska, int num) static
Definition at line 1314 of file matroskadec.c.
Referenced by matroska_add_index_entries(), and matroska_parse_block().
matroska_decode_buffer()
static int matroska_decode_buffer (uint8_t ** buf, int * buf_size, MatroskaTrack * track) static
Definition at line 1328 of file matroskadec.c.
Referenced by matroska_parse_frame(), and matroska_parse_tracks().
matroska_convert_tag()
static void matroska_convert_tag (AVFormatContext * s, EbmlList * list, AVDictionary ** metadata, char * prefix) static
Definition at line 1464 of file matroskadec.c.
Referenced by matroska_convert_tags().
matroska_convert_tags()
static void matroska_convert_tags (AVFormatContext * s) static
Definition at line 1499 of file matroskadec.c.
Referenced by matroska_read_header().
matroska_parse_seekhead_entry()
static int matroska_parse_seekhead_entry (MatroskaDemuxContext * matroska, uint64_t pos) static
Definition at line 1564 of file matroskadec.c.
Referenced by matroska_execute_seekhead(), and matroska_parse_cues().
matroska_execute_seekhead()
static void matroska_execute_seekhead (MatroskaDemuxContext * matroska) static
Definition at line 1609 of file matroskadec.c.
Referenced by matroska_read_header().
matroska_add_index_entries()
static void matroska_add_index_entries (MatroskaDemuxContext * matroska) static
Definition at line 1643 of file matroskadec.c.
Referenced by matroska_parse_cues(), and matroska_read_header().
matroska_parse_cues()
static void matroska_parse_cues (MatroskaDemuxContext * matroska) static
Definition at line 1676 of file matroskadec.c.
Referenced by matroska_read_seek(), and webm_dash_manifest_cues().
matroska_aac_profile()
static int matroska_aac_profile (char * codec_id) static
Definition at line 1695 of file matroskadec.c.
Referenced by matroska_parse_tracks().
matroska_aac_sri()
static int matroska_aac_sri (int samplerate) static
Definition at line 1706 of file matroskadec.c.
Referenced by matroska_parse_tracks().
matroska_metadata_creation_time()
static void matroska_metadata_creation_time (AVDictionary ** metadata, int64_t date_utc) static
Definition at line 1716 of file matroskadec.c.
Referenced by matroska_read_header().
matroska_parse_flac()
static int matroska_parse_flac (AVFormatContext * s, MatroskaTrack * track, int * offset) static
Definition at line 1722 of file matroskadec.c.
Referenced by matroska_parse_tracks().
mkv_field_order()
static int mkv_field_order (MatroskaDemuxContext * matroska, int64_t field_order) static
Definition at line 1777 of file matroskadec.c.
Referenced by matroska_parse_tracks().
mkv_stereo_mode_display_mul()
static void mkv_stereo_mode_display_mul (int stereo_mode, int * h_width, int * h_height) static
Definition at line 1804 of file matroskadec.c.
Referenced by matroska_parse_tracks().
mkv_parse_video_color()
static int mkv_parse_video_color (AVStream * st, const MatroskaTrack * track) static
Definition at line 1829 of file matroskadec.c.
Referenced by matroska_parse_tracks().
mkv_parse_video_projection()
static int mkv_parse_video_projection (AVStream * st, const MatroskaTrack * track) static
Definition at line 1908 of file matroskadec.c.
Referenced by matroska_parse_tracks().
get_qt_codec()
static int get_qt_codec (MatroskaTrack * track, uint32_t * fourcc, enum AVCodecID * codec_id) static
Definition at line 1948 of file matroskadec.c.
Referenced by matroska_parse_tracks().
matroska_parse_tracks()
static int matroska_parse_tracks (AVFormatContext * s) static
Definition at line 1975 of file matroskadec.c.
Referenced by matroska_read_header().
matroska_read_header()
static int matroska_read_header (AVFormatContext * s) static
Definition at line 2473 of file matroskadec.c.
Referenced by webm_dash_manifest_read_header().
matroska_deliver_packet()
static int matroska_deliver_packet (MatroskaDemuxContext * matroska, AVPacket * pkt) static
Definition at line 2631 of file matroskadec.c.
Referenced by matroska_read_packet().
matroska_clear_queue()
static void matroska_clear_queue (MatroskaDemuxContext * matroska) static
Definition at line 2672 of file matroskadec.c.
Referenced by matroska_read_close(), matroska_read_seek(), and webm_clusters_start_with_keyframe().
matroska_parse_laces()
static int matroska_parse_laces (MatroskaDemuxContext * matroska, uint8_t ** buf, int * buf_size, int type, uint32_t ** lace_buf, int * laces) static
Definition at line 2686 of file matroskadec.c.
Referenced by matroska_parse_block().
matroska_parse_rm_audio()
static int matroska_parse_rm_audio (MatroskaDemuxContext * matroska, MatroskaTrack * track, AVStream * st, uint8_t * data, int size, uint64_t timecode, int64_t pos) static
Definition at line 2795 of file matroskadec.c.
Referenced by matroska_parse_block().
matroska_parse_wavpack()
static int matroska_parse_wavpack (MatroskaTrack * track, uint8_t * src, uint8_t ** pdst, int * size) static
Definition at line 2872 of file matroskadec.c.
Referenced by matroska_parse_frame().
matroska_parse_webvtt()
static int matroska_parse_webvtt (MatroskaDemuxContext * matroska, MatroskaTrack * track, AVStream * st, uint8_t * data, int data_len, uint64_t timecode, uint64_t duration, int64_t pos) static
Definition at line 2952 of file matroskadec.c.
Referenced by matroska_parse_block().
matroska_parse_frame()
static int matroska_parse_frame (MatroskaDemuxContext * matroska, MatroskaTrack * track, AVStream * st, uint8_t * data, int pkt_size, uint64_t timecode, uint64_t lace_duration, int64_t pos, int is_keyframe, uint8_t * additional, uint64_t additional_id, int additional_size, int64_t discard_padding) static
Definition at line 3068 of file matroskadec.c.
Referenced by matroska_parse_block().
matroska_parse_block()
static int matroska_parse_block (MatroskaDemuxContext * matroska, uint8_t * data, int size, int64_t pos, uint64_t cluster_time, uint64_t block_duration, int is_keyframe, uint8_t * additional, uint64_t additional_id, int additional_size, int64_t cluster_pos, int64_t discard_padding) static
Definition at line 3189 of file matroskadec.c.
Referenced by matroska_parse_cluster(), and matroska_parse_cluster_incremental().
matroska_parse_cluster_incremental()
static int matroska_parse_cluster_incremental (MatroskaDemuxContext * matroska) static
Definition at line 3327 of file matroskadec.c.
Referenced by matroska_parse_cluster().
matroska_parse_cluster()
static int matroska_parse_cluster (MatroskaDemuxContext * matroska) static
Definition at line 3385 of file matroskadec.c.
Referenced by matroska_read_packet(), matroska_read_seek(), and webm_clusters_start_with_keyframe().
matroska_read_packet()
static int matroska_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 3415 of file matroskadec.c.
matroska_read_seek()
static int matroska_read_seek (AVFormatContext * s, int stream_index, int64_t timestamp, int flags) static
Definition at line 3431 of file matroskadec.c.
get_cue_desc()
static CueDesc get_cue_desc (AVFormatContext * s, int64_t ts, int64_t cues_start) static
Definition at line 3527 of file matroskadec.c.
Referenced by buffer_size_after_time_downloaded(), and webm_dash_manifest_compute_bandwidth().
webm_clusters_start_with_keyframe()
static int webm_clusters_start_with_keyframe (AVFormatContext * s) static
Definition at line 3556 of file matroskadec.c.
Referenced by webm_dash_manifest_cues().
buffer_size_after_time_downloaded()
static int buffer_size_after_time_downloaded (int64_t time_ns, double search_sec, int64_t bps, double min_buffer, double * buffer, double * sec_to_download, AVFormatContext * s, int64_t cues_start) static
Definition at line 3595 of file matroskadec.c.
Referenced by webm_dash_manifest_compute_bandwidth().
webm_dash_manifest_compute_bandwidth()
static int64_t webm_dash_manifest_compute_bandwidth (AVFormatContext * s, int64_t cues_start) static
Definition at line 3676 of file matroskadec.c.
Referenced by webm_dash_manifest_cues().
webm_dash_manifest_cues()
static int webm_dash_manifest_cues (AVFormatContext * s) static
Definition at line 3763 of file matroskadec.c.
Referenced by webm_dash_manifest_read_header().
webm_dash_manifest_read_header()
static int webm_dash_manifest_read_header (AVFormatContext * s) static
Definition at line 3827 of file matroskadec.c.
webm_dash_manifest_read_packet()
static int webm_dash_manifest_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 3866 of file matroskadec.c.
Variable Documentation
ebml_header
const EbmlSyntax ebml_header[] static
Initial value:
= {
    { EBML_ID_EBMLREADVERSION,    EBML_UINT, 0, 0x42,         { .u = EBML_VERSION } },
    { EBML_ID_EBMLMAXSIZELENGTH,  EBML_UINT, 0, 0x42,        { .u = 8 } },
    { EBML_ID_EBMLMAXIDLENGTH,    EBML_UINT, 0, 0x42,       { .u = 4 } },
    { EBML_ID_DOCTYPE,            EBML_STR,  0, 0x42,         { .s = "(none)" } },
    { EBML_ID_DOCTYPEREADVERSION, EBML_UINT, 0, 0x42, { .u = 1 } },
    { EBML_ID_EBMLVERSION,        EBML_NONE },
    { EBML_ID_DOCTYPEVERSION,     EBML_NONE },
    { 0 }
}
Definition at line 378 of file matroskadec.c.
Referenced by mkv_write_header().
ebml_syntax
const EbmlSyntax ebml_syntax[] static
Initial value:
= {
    { EBML_ID_HEADER, EBML_NEST, 0, 0, { .n = ebml_header } },
    { 0 }
}
Definition at line 389 of file matroskadec.c.
matroska_info
const EbmlSyntax matroska_info[] static
Initial value:
= {
    { MATROSKA_ID_TIMECODESCALE, EBML_UINT,  0, 0x42, { .u = 1000000 } },
    { MATROSKA_ID_DURATION,      EBML_FLOAT, 0, 0x42 },
    { MATROSKA_ID_TITLE,         EBML_UTF8,  0, 0x42 },
    { MATROSKA_ID_WRITINGAPP,    EBML_NONE },
    { MATROSKA_ID_MUXINGAPP,     EBML_UTF8, 0, 0x42 },
    { MATROSKA_ID_DATEUTC,       EBML_BIN,  0, 0x42 },
    { MATROSKA_ID_SEGMENTUID,    EBML_NONE },
    { 0 }
}
Definition at line 394 of file matroskadec.c.
matroska_mastering_meta
const EbmlSyntax matroska_mastering_meta[] static
Initial value:
= {
    { MATROSKA_ID_VIDEOCOLOR_RX, EBML_FLOAT, 0, 0x42, { .f=-1 } },
    { MATROSKA_ID_VIDEOCOLOR_RY, EBML_FLOAT, 0, 0x42, { .f=-1 } },
    { MATROSKA_ID_VIDEOCOLOR_GX, EBML_FLOAT, 0, 0x42, { .f=-1 } },
    { MATROSKA_ID_VIDEOCOLOR_GY, EBML_FLOAT, 0, 0x42, { .f=-1 } },
    { MATROSKA_ID_VIDEOCOLOR_BX, EBML_FLOAT, 0, 0x42, { .f=-1 } },
    { MATROSKA_ID_VIDEOCOLOR_BY, EBML_FLOAT, 0, 0x42, { .f=-1 } },
    { MATROSKA_ID_VIDEOCOLOR_WHITEX, EBML_FLOAT, 0, 0x42, { .f=-1 } },
    { MATROSKA_ID_VIDEOCOLOR_WHITEY, EBML_FLOAT, 0, 0x42, { .f=-1 } },
    { MATROSKA_ID_VIDEOCOLOR_LUMINANCEMIN, EBML_FLOAT, 0, 0x42, { .f=-1 } },
    { MATROSKA_ID_VIDEOCOLOR_LUMINANCEMAX, EBML_FLOAT, 0, 0x42, { .f=-1 } },
    { 0 }
}
Definition at line 405 of file matroskadec.c.
matroska_track_video_color
const EbmlSyntax matroska_track_video_color[] static
Initial value:
= {
    { MATROSKA_ID_VIDEOCOLORMATRIXCOEFF,      EBML_UINT, 0, 0x42, { .u = AVCOL_SPC_UNSPECIFIED } },
    { MATROSKA_ID_VIDEOCOLORBITSPERCHANNEL,   EBML_UINT, 0, 0x42, { .u=0 } },
    { MATROSKA_ID_VIDEOCOLORCHROMASUBHORZ,    EBML_UINT, 0, 0x42, { .u=0 } },
    { MATROSKA_ID_VIDEOCOLORCHROMASUBVERT,    EBML_UINT, 0, 0x42, { .u=0 } },
    { MATROSKA_ID_VIDEOCOLORCBSUBHORZ,        EBML_UINT, 0, 0x42, { .u=0 } },
    { MATROSKA_ID_VIDEOCOLORCBSUBVERT,        EBML_UINT, 0, 0x42, { .u=0 } },
    { MATROSKA_ID_VIDEOCOLORCHROMASITINGHORZ, EBML_UINT, 0, 0x42, { .u = MATROSKA_COLOUR_CHROMASITINGHORZ_UNDETERMINED } },
    { MATROSKA_ID_VIDEOCOLORCHROMASITINGVERT, EBML_UINT, 0, 0x42, { .u = MATROSKA_COLOUR_CHROMASITINGVERT_UNDETERMINED } },
    { MATROSKA_ID_VIDEOCOLORRANGE,            EBML_UINT, 0, 0x42, { .u = AVCOL_RANGE_UNSPECIFIED } },
    { MATROSKA_ID_VIDEOCOLORTRANSFERCHARACTERISTICS, EBML_UINT, 0, 0x42, { .u = AVCOL_TRC_UNSPECIFIED } },
    { MATROSKA_ID_VIDEOCOLORPRIMARIES,        EBML_UINT, 0, 0x42, { .u = AVCOL_PRI_UNSPECIFIED } },
    { MATROSKA_ID_VIDEOCOLORMAXCLL,           EBML_UINT, 0, 0x42, { .u=0 } },
    { MATROSKA_ID_VIDEOCOLORMAXFALL,          EBML_UINT, 0, 0x42, { .u=0 } },
    { MATROSKA_ID_VIDEOCOLORMASTERINGMETA,    EBML_NEST, 0, 0x42, { .n = matroska_mastering_meta } },
    { 0 }
}
Definition at line 419 of file matroskadec.c.
matroska_track_video_projection
const EbmlSyntax matroska_track_video_projection[] static
Initial value:
= {
    { MATROSKA_ID_VIDEOPROJECTIONTYPE,        EBML_UINT,  0, 0x42, { .u = MATROSKA_VIDEO_PROJECTION_TYPE_RECTANGULAR } },
    { MATROSKA_ID_VIDEOPROJECTIONPRIVATE,     EBML_BIN,   0, 0x42 },
    { MATROSKA_ID_VIDEOPROJECTIONPOSEYAW,     EBML_FLOAT, 0, 0x42, { .f=0.0 } },
    { MATROSKA_ID_VIDEOPROJECTIONPOSEPITCH,   EBML_FLOAT, 0, 0x42, { .f=0.0 } },
    { MATROSKA_ID_VIDEOPROJECTIONPOSEROLL,    EBML_FLOAT, 0, 0x42, { .f=0.0 } },
    { 0 }
}
Definition at line 437 of file matroskadec.c.
matroska_track_video
const EbmlSyntax matroska_track_video[] static
Initial value:
= {
    { MATROSKA_ID_VIDEOFRAMERATE,      EBML_FLOAT, 0, 0x42 },
    { MATROSKA_ID_VIDEODISPLAYWIDTH,   EBML_UINT,  0, 0x42, { .u=-1 } },
    { MATROSKA_ID_VIDEODISPLAYHEIGHT,  EBML_UINT,  0, 0x42, { .u=-1 } },
    { MATROSKA_ID_VIDEOPIXELWIDTH,     EBML_UINT,  0, 0x42 },
    { MATROSKA_ID_VIDEOPIXELHEIGHT,    EBML_UINT,  0, 0x42 },
    { MATROSKA_ID_VIDEOCOLORSPACE,     EBML_BIN,   0, 0x42 },
    { MATROSKA_ID_VIDEOALPHAMODE,      EBML_UINT,  0, 0x42 },
    { MATROSKA_ID_VIDEOCOLOR,          EBML_NEST,  sizeof(MatroskaTrackVideoColor), 0x42, { .n = matroska_track_video_color } },
    { MATROSKA_ID_VIDEOPROJECTION,     EBML_NEST,  0, 0x42, { .n = matroska_track_video_projection } },
    { MATROSKA_ID_VIDEOPIXELCROPB,     EBML_NONE },
    { MATROSKA_ID_VIDEOPIXELCROPT,     EBML_NONE },
    { MATROSKA_ID_VIDEOPIXELCROPL,     EBML_NONE },
    { MATROSKA_ID_VIDEOPIXELCROPR,     EBML_NONE },
    { MATROSKA_ID_VIDEODISPLAYUNIT,    EBML_UINT,  0, 0x42, { .u= MATROSKA_VIDEO_DISPLAYUNIT_PIXELS } },
    { MATROSKA_ID_VIDEOFLAGINTERLACED, EBML_UINT,  0, 0x42,  { .u = MATROSKA_VIDEO_INTERLACE_FLAG_UNDETERMINED } },
    { MATROSKA_ID_VIDEOFIELDORDER,     EBML_UINT,  0, 0x42, { .u = MATROSKA_VIDEO_FIELDORDER_UNDETERMINED } },
    { MATROSKA_ID_VIDEOSTEREOMODE,     EBML_UINT,  0, 0x42, { .u = MATROSKA_VIDEO_STEREOMODE_TYPE_NB } },
    { MATROSKA_ID_VIDEOASPECTRATIO,    EBML_NONE },
    { 0 }
}
Definition at line 446 of file matroskadec.c.
matroska_track_audio
const EbmlSyntax matroska_track_audio[] static
Initial value:
= {
    { MATROSKA_ID_AUDIOSAMPLINGFREQ,    EBML_FLOAT, 0, 0x42, { .f = 8000.0 } },
    { MATROSKA_ID_AUDIOOUTSAMPLINGFREQ, EBML_FLOAT, 0, 0x42 },
    { MATROSKA_ID_AUDIOBITDEPTH,        EBML_UINT,  0, 0x42 },
    { MATROSKA_ID_AUDIOCHANNELS,        EBML_UINT,  0, 0x42,   { .u = 1 } },
    { 0 }
}
Definition at line 468 of file matroskadec.c.
matroska_track_encoding_compression
const EbmlSyntax matroska_track_encoding_compression[] static
Initial value:
= {
    { MATROSKA_ID_ENCODINGCOMPALGO,     EBML_UINT, 0, 0x42, { .u = 0 } },
    { MATROSKA_ID_ENCODINGCOMPSETTINGS, EBML_BIN,  0, 0x42 },
    { 0 }
}
Definition at line 476 of file matroskadec.c.
matroska_track_encoding_encryption
const EbmlSyntax matroska_track_encoding_encryption[] static
Initial value:
= {
    { MATROSKA_ID_ENCODINGENCALGO,        EBML_UINT, 0, 0x42, {.u = 0} },
    { MATROSKA_ID_ENCODINGENCKEYID,       EBML_BIN, 0, 0x42 },
    { MATROSKA_ID_ENCODINGENCAESSETTINGS, EBML_NONE },
    { MATROSKA_ID_ENCODINGSIGALGO,        EBML_NONE },
    { MATROSKA_ID_ENCODINGSIGHASHALGO,    EBML_NONE },
    { MATROSKA_ID_ENCODINGSIGKEYID,       EBML_NONE },
    { MATROSKA_ID_ENCODINGSIGNATURE,      EBML_NONE },
    { 0 }
}
Definition at line 482 of file matroskadec.c.
matroska_track_encoding
const EbmlSyntax matroska_track_encoding[] static
Initial value:
= {
    { MATROSKA_ID_ENCODINGSCOPE,       EBML_UINT, 0, 0x42,       { .u = 1 } },
    { MATROSKA_ID_ENCODINGTYPE,        EBML_UINT, 0, 0x42,        { .u = 0 } },
    { MATROSKA_ID_ENCODINGCOMPRESSION, EBML_NEST, 0, 0x42, { .n = matroska_track_encoding_compression } },
    { MATROSKA_ID_ENCODINGENCRYPTION,  EBML_NEST, 0, 0x42,  { .n = matroska_track_encoding_encryption } },
    { MATROSKA_ID_ENCODINGORDER,       EBML_NONE },
    { 0 }
}
Definition at line 492 of file matroskadec.c.
matroska_track_encodings
const EbmlSyntax matroska_track_encodings[] static
Initial value:
= {
    { MATROSKA_ID_TRACKCONTENTENCODING, EBML_NEST, sizeof(MatroskaTrackEncoding), 0x42, { .n = matroska_track_encoding } },
    { 0 }
}
Definition at line 501 of file matroskadec.c.
matroska_track_plane
const EbmlSyntax matroska_track_plane[] static
Initial value:
= {
    { MATROSKA_ID_TRACKPLANEUID,  EBML_UINT, 0, 0x42 },
    { MATROSKA_ID_TRACKPLANETYPE, EBML_UINT, 0, 0x42 },
    { 0 }
}
Definition at line 506 of file matroskadec.c.
matroska_track_combine_planes
const EbmlSyntax matroska_track_combine_planes[] static
Initial value:
= {
    { MATROSKA_ID_TRACKPLANE, EBML_NEST, sizeof(MatroskaTrackPlane), 0x42, {.n = matroska_track_plane} },
    { 0 }
}
Definition at line 512 of file matroskadec.c.
matroska_track_operation
const EbmlSyntax matroska_track_operation[] static
Initial value:
= {
    { MATROSKA_ID_TRACKCOMBINEPLANES, EBML_NEST, 0, 0, {.n = matroska_track_combine_planes} },
    { 0 }
}
Definition at line 517 of file matroskadec.c.
matroska_track
const EbmlSyntax matroska_track[] static
Initial value:
= {
    { MATROSKA_ID_TRACKNUMBER,           EBML_UINT,  0, 0x42 },
    { MATROSKA_ID_TRACKNAME,             EBML_UTF8,  0, 0x42 },
    { MATROSKA_ID_TRACKUID,              EBML_UINT,  0, 0x42 },
    { MATROSKA_ID_TRACKTYPE,             EBML_UINT,  0, 0x42 },
    { MATROSKA_ID_CODECID,               EBML_STR,   0, 0x42 },
    { MATROSKA_ID_CODECPRIVATE,          EBML_BIN,   0, 0x42 },
    { MATROSKA_ID_CODECDELAY,            EBML_UINT,  0, 0x42 },
    { MATROSKA_ID_TRACKLANGUAGE,         EBML_UTF8,  0, 0x42,     { .s = "eng" } },
    { MATROSKA_ID_TRACKDEFAULTDURATION,  EBML_UINT,  0, 0x42 },
    { MATROSKA_ID_TRACKTIMECODESCALE,    EBML_FLOAT, 0, 0x42,   { .f = 1.0 } },
    { MATROSKA_ID_TRACKFLAGDEFAULT,      EBML_UINT,  0, 0x42, { .u = 1 } },
    { MATROSKA_ID_TRACKFLAGFORCED,       EBML_UINT,  0, 0x42,  { .u = 0 } },
    { MATROSKA_ID_TRACKVIDEO,            EBML_NEST,  0, 0x42,        { .n = matroska_track_video } },
    { MATROSKA_ID_TRACKAUDIO,            EBML_NEST,  0, 0x42,        { .n = matroska_track_audio } },
    { MATROSKA_ID_TRACKOPERATION,        EBML_NEST,  0, 0x42,    { .n = matroska_track_operation } },
    { MATROSKA_ID_TRACKCONTENTENCODINGS, EBML_NEST,  0, 0,                                     { .n = matroska_track_encodings } },
    { MATROSKA_ID_TRACKMAXBLKADDID,      EBML_UINT,  0, 0x42 },
    { MATROSKA_ID_SEEKPREROLL,           EBML_UINT,  0, 0x42 },
    { MATROSKA_ID_TRACKFLAGENABLED,      EBML_NONE },
    { MATROSKA_ID_TRACKFLAGLACING,       EBML_NONE },
    { MATROSKA_ID_CODECNAME,             EBML_NONE },
    { MATROSKA_ID_CODECDECODEALL,        EBML_NONE },
    { MATROSKA_ID_CODECINFOURL,          EBML_NONE },
    { MATROSKA_ID_CODECDOWNLOADURL,      EBML_NONE },
    { MATROSKA_ID_TRACKMINCACHE,         EBML_NONE },
    { MATROSKA_ID_TRACKMAXCACHE,         EBML_NONE },
    { 0 }
}
Definition at line 522 of file matroskadec.c.
matroska_tracks
const EbmlSyntax matroska_tracks[] static
Initial value:
= {
    { MATROSKA_ID_TRACKENTRY, EBML_NEST, sizeof(MatroskaTrack), 0x42, { .n = matroska_track } },
    { 0 }
}
Definition at line 552 of file matroskadec.c.
matroska_attachment
const EbmlSyntax matroska_attachment[] static
Initial value:
= {
    { MATROSKA_ID_FILEUID,      EBML_UINT, 0, 0x42 },
    { MATROSKA_ID_FILENAME,     EBML_UTF8, 0, 0x42 },
    { MATROSKA_ID_FILEMIMETYPE, EBML_STR,  0, 0x42 },
    { MATROSKA_ID_FILEDATA,     EBML_BIN,  0, 0x42 },
    { MATROSKA_ID_FILEDESC,     EBML_NONE },
    { 0 }
}
Definition at line 557 of file matroskadec.c.
matroska_attachments
const EbmlSyntax matroska_attachments[] static
Initial value:
= {
    { MATROSKA_ID_ATTACHEDFILE, EBML_NEST, sizeof(MatroskaAttachment), 0x42, { .n = matroska_attachment } },
    { 0 }
}
Definition at line 566 of file matroskadec.c.
matroska_chapter_display
const EbmlSyntax matroska_chapter_display[] static
Initial value:
= {
    { MATROSKA_ID_CHAPSTRING,  EBML_UTF8, 0, 0x42 },
    { MATROSKA_ID_CHAPLANG,    EBML_NONE },
    { MATROSKA_ID_CHAPCOUNTRY, EBML_NONE },
    { 0 }
}
Definition at line 571 of file matroskadec.c.
matroska_chapter_entry
const EbmlSyntax matroska_chapter_entry[] static
Initial value:
= {
    { MATROSKA_ID_CHAPTERTIMESTART,   EBML_UINT, 0, 0x42, { .u = AV_NOPTS_VALUE } },
    { MATROSKA_ID_CHAPTERTIMEEND,     EBML_UINT, 0, 0x42,   { .u = AV_NOPTS_VALUE } },
    { MATROSKA_ID_CHAPTERUID,         EBML_UINT, 0, 0x42 },
    { MATROSKA_ID_CHAPTERDISPLAY,     EBML_NEST, 0,                        0,         { .n = matroska_chapter_display } },
    { MATROSKA_ID_CHAPTERFLAGHIDDEN,  EBML_NONE },
    { MATROSKA_ID_CHAPTERFLAGENABLED, EBML_NONE },
    { MATROSKA_ID_CHAPTERPHYSEQUIV,   EBML_NONE },
    { MATROSKA_ID_CHAPTERATOM,        EBML_NONE },
    { 0 }
}
Definition at line 578 of file matroskadec.c.
matroska_chapter
const EbmlSyntax matroska_chapter[] static
Initial value:
= {
    { MATROSKA_ID_CHAPTERATOM,        EBML_NEST, sizeof(MatroskaChapter), 0x42, { .n = matroska_chapter_entry } },
    { MATROSKA_ID_EDITIONUID,         EBML_NONE },
    { MATROSKA_ID_EDITIONFLAGHIDDEN,  EBML_NONE },
    { MATROSKA_ID_EDITIONFLAGDEFAULT, EBML_NONE },
    { MATROSKA_ID_EDITIONFLAGORDERED, EBML_NONE },
    { 0 }
}
Definition at line 590 of file matroskadec.c.
matroska_chapters
const EbmlSyntax matroska_chapters[] static
Initial value:
= {
    { MATROSKA_ID_EDITIONENTRY, EBML_NEST, 0, 0, { .n = matroska_chapter } },
    { 0 }
}
Definition at line 599 of file matroskadec.c.
matroska_index_pos
const EbmlSyntax matroska_index_pos[] static
Initial value:
= {
    { MATROSKA_ID_CUETRACK,           EBML_UINT, 0, 0x42 },
    { MATROSKA_ID_CUECLUSTERPOSITION, EBML_UINT, 0, 0x42 },
    { MATROSKA_ID_CUERELATIVEPOSITION,EBML_NONE },
    { MATROSKA_ID_CUEDURATION,        EBML_NONE },
    { MATROSKA_ID_CUEBLOCKNUMBER,     EBML_NONE },
    { 0 }
}
Definition at line 604 of file matroskadec.c.
matroska_index_entry
const EbmlSyntax matroska_index_entry[] static
Initial value:
= {
    { MATROSKA_ID_CUETIME,          EBML_UINT, 0,                        0x42 },
    { MATROSKA_ID_CUETRACKPOSITION, EBML_NEST, sizeof(MatroskaIndexPos), 0x42, { .n = matroska_index_pos } },
    { 0 }
}
Definition at line 613 of file matroskadec.c.
matroska_index
const EbmlSyntax matroska_index[] static
Initial value:
= {
    { MATROSKA_ID_POINTENTRY, EBML_NEST, sizeof(MatroskaIndex), 0x42, { .n = matroska_index_entry } },
    { 0 }
}
Definition at line 619 of file matroskadec.c.
matroska_simpletag
const EbmlSyntax matroska_simpletag[] static
Initial value:
= {
    { MATROSKA_ID_TAGNAME,        EBML_UTF8, 0,                   0x42 },
    { MATROSKA_ID_TAGSTRING,      EBML_UTF8, 0,                   0x42 },
    { MATROSKA_ID_TAGLANG,        EBML_STR,  0,                   0x42, { .s = "und" } },
    { MATROSKA_ID_TAGDEFAULT,     EBML_UINT, 0,                   0x42 },
    { MATROSKA_ID_TAGDEFAULT_BUG, EBML_UINT, 0,                   0x42 },
    { MATROSKA_ID_SIMPLETAG,      EBML_NEST, sizeof(MatroskaTag), 0x42,  { .n = matroska_simpletag } },
    { 0 }
}
Definition at line 624 of file matroskadec.c.
matroska_tagtargets
const EbmlSyntax matroska_tagtargets[] static
Initial value:
= {
    { MATROSKA_ID_TAGTARGETS_TYPE,       EBML_STR,  0, 0x42 },
    { MATROSKA_ID_TAGTARGETS_TYPEVALUE,  EBML_UINT, 0, 0x42, { .u = 50 } },
    { MATROSKA_ID_TAGTARGETS_TRACKUID,   EBML_UINT, 0, 0x42 },
    { MATROSKA_ID_TAGTARGETS_CHAPTERUID, EBML_UINT, 0, 0x42 },
    { MATROSKA_ID_TAGTARGETS_ATTACHUID,  EBML_UINT, 0, 0x42 },
    { 0 }
}
Definition at line 634 of file matroskadec.c.
matroska_tag
const EbmlSyntax matroska_tag[] static
Initial value:
= {
    { MATROSKA_ID_SIMPLETAG,  EBML_NEST, sizeof(MatroskaTag), 0x42,    { .n = matroska_simpletag } },
    { MATROSKA_ID_TAGTARGETS, EBML_NEST, 0,                   0x42, { .n = matroska_tagtargets } },
    { 0 }
}
Definition at line 643 of file matroskadec.c.
matroska_tags
const EbmlSyntax matroska_tags[] static
Initial value:
= {
    { MATROSKA_ID_TAG, EBML_NEST, sizeof(MatroskaTags), 0x42, { .n = matroska_tag } },
    { 0 }
}
Definition at line 649 of file matroskadec.c.
matroska_seekhead_entry
const EbmlSyntax matroska_seekhead_entry[] static
Initial value:
= {
    { MATROSKA_ID_SEEKID,       EBML_UINT, 0, 0x42 },
    { MATROSKA_ID_SEEKPOSITION, EBML_UINT, 0, 0x42, { .u = -1 } },
    { 0 }
}
Definition at line 654 of file matroskadec.c.
matroska_seekhead
const EbmlSyntax matroska_seekhead[] static
Initial value:
= {
    { MATROSKA_ID_SEEKENTRY, EBML_NEST, sizeof(MatroskaSeekhead), 0x42, { .n = matroska_seekhead_entry } },
    { 0 }
}
Definition at line 660 of file matroskadec.c.
matroska_segment
const EbmlSyntax matroska_segment[] static
Initial value:
= {
    { MATROSKA_ID_INFO,        EBML_LEVEL1, 0, 0, { .n = matroska_info } },
    { MATROSKA_ID_TRACKS,      EBML_LEVEL1, 0, 0, { .n = matroska_tracks } },
    { MATROSKA_ID_ATTACHMENTS, EBML_LEVEL1, 0, 0, { .n = matroska_attachments } },
    { MATROSKA_ID_CHAPTERS,    EBML_LEVEL1, 0, 0, { .n = matroska_chapters } },
    { MATROSKA_ID_CUES,        EBML_LEVEL1, 0, 0, { .n = matroska_index } },
    { MATROSKA_ID_TAGS,        EBML_LEVEL1, 0, 0, { .n = matroska_tags } },
    { MATROSKA_ID_SEEKHEAD,    EBML_LEVEL1, 0, 0, { .n = matroska_seekhead } },
    { MATROSKA_ID_CLUSTER,     EBML_STOP },
    { 0 }
}
Definition at line 665 of file matroskadec.c.
matroska_segments
const EbmlSyntax matroska_segments[] static
Initial value:
= {
    { MATROSKA_ID_SEGMENT, EBML_NEST, 0, 0, { .n = matroska_segment } },
    { 0 }
}
Definition at line 677 of file matroskadec.c.
matroska_blockmore
const EbmlSyntax matroska_blockmore[] static
Initial value:
= {
    { MATROSKA_ID_BLOCKADDID,      EBML_UINT, 0, 0x42 },
    { MATROSKA_ID_BLOCKADDITIONAL, EBML_BIN,  0, 0x42 },
    { 0 }
}
Definition at line 682 of file matroskadec.c.
matroska_blockadditions
const EbmlSyntax matroska_blockadditions[] static
Initial value:
= {
    { MATROSKA_ID_BLOCKMORE, EBML_NEST, 0, 0, {.n = matroska_blockmore} },
    { 0 }
}
Definition at line 688 of file matroskadec.c.
matroska_blockgroup
const EbmlSyntax matroska_blockgroup[] static
Initial value:
= {
    { MATROSKA_ID_BLOCK,          EBML_BIN,  0, 0x42 },
    { MATROSKA_ID_BLOCKADDITIONS, EBML_NEST, 0, 0, { .n = matroska_blockadditions} },
    { MATROSKA_ID_SIMPLEBLOCK,    EBML_BIN,  0, 0x42 },
    { MATROSKA_ID_BLOCKDURATION,  EBML_UINT, 0, 0x42 },
    { MATROSKA_ID_DISCARDPADDING, EBML_SINT, 0, 0x42 },
    { MATROSKA_ID_BLOCKREFERENCE, EBML_SINT, 0, 0x42 },
    { MATROSKA_ID_CODECSTATE,     EBML_NONE },
    {                          1, EBML_UINT, 0, 0x42, { .u = 1 } },
    { 0 }
}
Definition at line 693 of file matroskadec.c.
matroska_cluster
const EbmlSyntax matroska_cluster[] static
Initial value:
= {
    { MATROSKA_ID_CLUSTERTIMECODE, EBML_UINT, 0,                     0x42 },
    { MATROSKA_ID_BLOCKGROUP,      EBML_NEST, sizeof(MatroskaBlock), 0x42, { .n = matroska_blockgroup } },
    { MATROSKA_ID_SIMPLEBLOCK,     EBML_PASS, sizeof(MatroskaBlock), 0x42, { .n = matroska_blockgroup } },
    { MATROSKA_ID_CLUSTERPOSITION, EBML_NONE },
    { MATROSKA_ID_CLUSTERPREVSIZE, EBML_NONE },
    { 0 }
}
Definition at line 705 of file matroskadec.c.
matroska_clusters
const EbmlSyntax matroska_clusters[] static
Initial value:
= {
    { MATROSKA_ID_CLUSTER,  EBML_NEST, 0, 0, { .n = matroska_cluster } },
    { MATROSKA_ID_INFO,     EBML_NONE },
    { MATROSKA_ID_CUES,     EBML_NONE },
    { MATROSKA_ID_TAGS,     EBML_NONE },
    { MATROSKA_ID_SEEKHEAD, EBML_NONE },
    { 0 }
}
Definition at line 714 of file matroskadec.c.
matroska_cluster_incremental_parsing
const EbmlSyntax matroska_cluster_incremental_parsing[] static
Initial value:
= {
    { MATROSKA_ID_CLUSTERTIMECODE, EBML_UINT, 0,                     0x42 },
    { MATROSKA_ID_BLOCKGROUP,      EBML_NEST, sizeof(MatroskaBlock), 0x42, { .n = matroska_blockgroup } },
    { MATROSKA_ID_SIMPLEBLOCK,     EBML_PASS, sizeof(MatroskaBlock), 0x42, { .n = matroska_blockgroup } },
    { MATROSKA_ID_CLUSTERPOSITION, EBML_NONE },
    { MATROSKA_ID_CLUSTERPREVSIZE, EBML_NONE },
    { MATROSKA_ID_INFO,            EBML_NONE },
    { MATROSKA_ID_CUES,            EBML_NONE },
    { MATROSKA_ID_TAGS,            EBML_NONE },
    { MATROSKA_ID_SEEKHEAD,        EBML_NONE },
    { MATROSKA_ID_CLUSTER,         EBML_STOP },
    { 0 }
}
Definition at line 723 of file matroskadec.c.
matroska_cluster_incremental
const EbmlSyntax matroska_cluster_incremental[] static
Initial value:
= {
    { MATROSKA_ID_CLUSTERTIMECODE, EBML_UINT, 0, 0x42 },
    { MATROSKA_ID_BLOCKGROUP,      EBML_STOP },
    { MATROSKA_ID_SIMPLEBLOCK,     EBML_STOP },
    { MATROSKA_ID_CLUSTERPOSITION, EBML_NONE },
    { MATROSKA_ID_CLUSTERPREVSIZE, EBML_NONE },
    { 0 }
}
Definition at line 737 of file matroskadec.c.
matroska_clusters_incremental
const EbmlSyntax matroska_clusters_incremental[] static
Initial value:
= {
    { MATROSKA_ID_CLUSTER,  EBML_NEST, 0, 0, { .n = matroska_cluster_incremental } },
    { MATROSKA_ID_INFO,     EBML_NONE },
    { MATROSKA_ID_CUES,     EBML_NONE },
    { MATROSKA_ID_TAGS,     EBML_NONE },
    { MATROSKA_ID_SEEKHEAD, EBML_NONE },
    { 0 }
}
Definition at line 746 of file matroskadec.c.
matroska_doctypes
const char* const matroska_doctypes[] = { "matroska", "webm" } static
Definition at line 755 of file matroskadec.c.
Referenced by matroska_probe(), and matroska_read_header().
options
const AVOption options[] static
Initial value:
= {
    { "live", "flag indicating that the input is a live file that only has the headers.", OFFSET(is_live), AV_OPT_TYPE_BOOL, {.i64 = 0}, 0, 1, AV_OPT_FLAG_DECODING_PARAM },
    { NULL },
}
Definition at line 3872 of file matroskadec.c.
webm_dash_class
const AVClass webm_dash_class static
Initial value:
= {
    .class_name = "WebM DASH Manifest demuxer",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 3877 of file matroskadec.c.
ff_matroska_demuxer
AVInputFormat ff_matroska_demuxer
Initial value:
= {
    .name           = "matroska,webm",
    .long_name      = NULL_IF_CONFIG_SMALL("Matroska / WebM"),
    .extensions     = "mkv,mk3d,mka,mks",
    .priv_data_size = sizeof(MatroskaDemuxContext),
    .read_probe     = matroska_probe,
    .read_header    = matroska_read_header,
    .read_packet    = matroska_read_packet,
    .read_close     = matroska_read_close,
    .read_seek      = matroska_read_seek,
    .mime_type      = "audio/webm,audio/x-matroska,video/webm,video/x-matroska"
}
Definition at line 3884 of file matroskadec.c.
ff_webm_dash_manifest_demuxer
AVInputFormat ff_webm_dash_manifest_demuxer
Initial value:
= {
    .name           = "webm_dash_manifest",
    .long_name      = NULL_IF_CONFIG_SMALL("WebM DASH Manifest"),
    .priv_data_size = sizeof(MatroskaDemuxContext),
    .read_header    = webm_dash_manifest_read_header,
    .read_packet    = webm_dash_manifest_read_packet,
    .read_close     = matroska_read_close,
    .priv_class     = &webm_dash_class,
}
Definition at line 3897 of file matroskadec.c.