FFmpeg: libavcodec/mdec.c File Reference
mdec.c File Reference
Sony PlayStation MDEC (Motion DECoder) This is very similar to intra-only MPEG-1.
#include "avcodec.h"
#include "blockdsp.h"
#include "bswapdsp.h"
#include "idctdsp.h"
#include "mpeg12.h"
#include "thread.h"
Data Structures
struct MDECContext
Functions
static int mdec_decode_block_intra (MDECContext *a, int16_t *block, int n)
static int decode_mb (MDECContext *a, int16_t block[6][64])
static void idct_put (MDECContext *a, AVFrame *frame, int mb_x, int mb_y)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int decode_init (AVCodecContext *avctx)
static av_cold int decode_end (AVCodecContext *avctx)
Variables
AVCodec ff_mdec_decoder
Detailed Description
Sony PlayStation MDEC (Motion DECoder) This is very similar to intra-only MPEG-1.
Definition in file mdec.c.
Function Documentation
mdec_decode_block_intra()
static int mdec_decode_block_intra (MDECContext * a, int16_t * block, int n) inline static
Definition at line 58 of file mdec.c.
Referenced by decode_mb().
decode_mb()
static int decode_mb (MDECContext * a, int16_t block[6][64]) inline static
Definition at line 131 of file mdec.c.
Referenced by decode_frame().
idct_put()
static void idct_put (MDECContext * a, AVFrame * frame, int mb_x, int mb_y) inline static
Definition at line 148 of file mdec.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 168 of file mdec.c.
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 212 of file mdec.c.
decode_end()
static av_cold int decode_end (AVCodecContext * avctx) static
Definition at line 247 of file mdec.c.
Variable Documentation
ff_mdec_decoder
AVCodec ff_mdec_decoder
Initial value:
= {
    .name             = "mdec",
    .long_name        = NULL_IF_CONFIG_SMALL("Sony PlayStation MDEC (Motion DECoder)"),
    .type             = AVMEDIA_TYPE_VIDEO,
    .id               = AV_CODEC_ID_MDEC,
    .priv_data_size   = sizeof(MDECContext),
    .init             = decode_init,
    .close            = decode_end,
    .decode           = decode_frame,
    .capabilities     = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_FRAME_THREADS,
    .init_thread_copy = ONLY_IF_THREADS_ENABLED(decode_init_thread_copy)
}
Definition at line 257 of file mdec.c.