FFmpeg: libavcodec/x86/me_cmp_init.c File Reference
me_cmp_init.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/x86/asm.h"
#include "libavutil/x86/cpu.h"
#include "libavcodec/me_cmp.h"
#include "libavcodec/mpegvideo.h"
Macros
#define hadamard_func(cpu)
Functions
int ff_sum_abs_dctelem_mmx (int16_t *block)
int ff_sum_abs_dctelem_mmxext (int16_t *block)
int ff_sum_abs_dctelem_sse2 (int16_t *block)
int ff_sum_abs_dctelem_ssse3 (int16_t *block)
int ff_sse8_mmx (MpegEncContext *v, uint8_t *pix1, uint8_t *pix2, ptrdiff_t stride, int h)
int ff_sse16_mmx (MpegEncContext *v, uint8_t *pix1, uint8_t *pix2, ptrdiff_t stride, int h)
int ff_sse16_sse2 (MpegEncContext *v, uint8_t *pix1, uint8_t *pix2, ptrdiff_t stride, int h)
int ff_hf_noise8_mmx (uint8_t *pix1, ptrdiff_t stride, int h)
int ff_hf_noise16_mmx (uint8_t *pix1, ptrdiff_t stride, int h)
int ff_sad8_mmxext (MpegEncContext *v, uint8_t *pix1, uint8_t *pix2, ptrdiff_t stride, int h)
int ff_sad16_mmxext (MpegEncContext *v, uint8_t *pix1, uint8_t *pix2, ptrdiff_t stride, int h)
int ff_sad16_sse2 (MpegEncContext *v, uint8_t *pix1, uint8_t *pix2, ptrdiff_t stride, int h)
int ff_sad8_x2_mmxext (MpegEncContext *v, uint8_t *pix1, uint8_t *pix2, ptrdiff_t stride, int h)
int ff_sad16_x2_mmxext (MpegEncContext *v, uint8_t *pix1, uint8_t *pix2, ptrdiff_t stride, int h)
int ff_sad16_x2_sse2 (MpegEncContext *v, uint8_t *pix1, uint8_t *pix2, ptrdiff_t stride, int h)
int ff_sad8_y2_mmxext (MpegEncContext *v, uint8_t *pix1, uint8_t *pix2, ptrdiff_t stride, int h)
int ff_sad16_y2_mmxext (MpegEncContext *v, uint8_t *pix1, uint8_t *pix2, ptrdiff_t stride, int h)
int ff_sad16_y2_sse2 (MpegEncContext *v, uint8_t *pix1, uint8_t *pix2, ptrdiff_t stride, int h)
int ff_sad8_approx_xy2_mmxext (MpegEncContext *v, uint8_t *pix1, uint8_t *pix2, ptrdiff_t stride, int h)
int ff_sad16_approx_xy2_mmxext (MpegEncContext *v, uint8_t *pix1, uint8_t *pix2, ptrdiff_t stride, int h)
int ff_sad16_approx_xy2_sse2 (MpegEncContext *v, uint8_t *pix1, uint8_t *pix2, ptrdiff_t stride, int h)
int ff_vsad_intra8_mmxext (MpegEncContext *v, uint8_t *pix1, uint8_t *pix2, ptrdiff_t stride, int h)
int ff_vsad_intra16_mmxext (MpegEncContext *v, uint8_t *pix1, uint8_t *pix2, ptrdiff_t stride, int h)
int ff_vsad_intra16_sse2 (MpegEncContext *v, uint8_t *pix1, uint8_t *pix2, ptrdiff_t stride, int h)
int ff_vsad8_approx_mmxext (MpegEncContext *v, uint8_t *pix1, uint8_t *pix2, ptrdiff_t stride, int h)
int ff_vsad16_approx_mmxext (MpegEncContext *v, uint8_t *pix1, uint8_t *pix2, ptrdiff_t stride, int h)
int ff_vsad16_approx_sse2 (MpegEncContext *v, uint8_t *pix1, uint8_t *pix2, ptrdiff_t stride, int h)
hadamard_func (mmx)
Macro Definition Documentation
hadamard_func
#define hadamard_func (cpu)
Value:
int ff_hadamard8_diff_ ## cpu(MpegEncContext *s, uint8_t *src1,           \
                                  uint8_t *src2, ptrdiff_t stride, int h);    \
    int ff_hadamard8_diff16_ ## cpu(MpegEncContext *s, uint8_t *src1,         \
                                    uint8_t *src2, ptrdiff_t stride, int h);
Definition at line 81 of file me_cmp_init.c.
Function Documentation
ff_sum_abs_dctelem_mmx()
int ff_sum_abs_dctelem_mmx (int16_t * block)
Referenced by hadamard_func().
ff_sum_abs_dctelem_mmxext()
int ff_sum_abs_dctelem_mmxext (int16_t * block)
Referenced by hadamard_func().
ff_sum_abs_dctelem_sse2()
int ff_sum_abs_dctelem_sse2 (int16_t * block)
Referenced by hadamard_func().
ff_sum_abs_dctelem_ssse3()
int ff_sum_abs_dctelem_ssse3 (int16_t * block)
Referenced by hadamard_func().
ff_sse8_mmx()
int ff_sse8_mmx (MpegEncContext * v, uint8_t * pix1, uint8_t * pix2, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_sse16_mmx()
int ff_sse16_mmx (MpegEncContext * v, uint8_t * pix1, uint8_t * pix2, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_sse16_sse2()
int ff_sse16_sse2 (MpegEncContext * v, uint8_t * pix1, uint8_t * pix2, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_hf_noise8_mmx()
int ff_hf_noise8_mmx (uint8_t * pix1, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_hf_noise16_mmx()
int ff_hf_noise16_mmx (uint8_t * pix1, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_sad8_mmxext()
int ff_sad8_mmxext (MpegEncContext * v, uint8_t * pix1, uint8_t * pix2, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_sad16_mmxext()
int ff_sad16_mmxext (MpegEncContext * v, uint8_t * pix1, uint8_t * pix2, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_sad16_sse2()
int ff_sad16_sse2 (MpegEncContext * v, uint8_t * pix1, uint8_t * pix2, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_sad8_x2_mmxext()
int ff_sad8_x2_mmxext (MpegEncContext * v, uint8_t * pix1, uint8_t * pix2, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_sad16_x2_mmxext()
int ff_sad16_x2_mmxext (MpegEncContext * v, uint8_t * pix1, uint8_t * pix2, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_sad16_x2_sse2()
int ff_sad16_x2_sse2 (MpegEncContext * v, uint8_t * pix1, uint8_t * pix2, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_sad8_y2_mmxext()
int ff_sad8_y2_mmxext (MpegEncContext * v, uint8_t * pix1, uint8_t * pix2, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_sad16_y2_mmxext()
int ff_sad16_y2_mmxext (MpegEncContext * v, uint8_t * pix1, uint8_t * pix2, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_sad16_y2_sse2()
int ff_sad16_y2_sse2 (MpegEncContext * v, uint8_t * pix1, uint8_t * pix2, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_sad8_approx_xy2_mmxext()
int ff_sad8_approx_xy2_mmxext (MpegEncContext * v, uint8_t * pix1, uint8_t * pix2, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_sad16_approx_xy2_mmxext()
int ff_sad16_approx_xy2_mmxext (MpegEncContext * v, uint8_t * pix1, uint8_t * pix2, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_sad16_approx_xy2_sse2()
int ff_sad16_approx_xy2_sse2 (MpegEncContext * v, uint8_t * pix1, uint8_t * pix2, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_vsad_intra8_mmxext()
int ff_vsad_intra8_mmxext (MpegEncContext * v, uint8_t * pix1, uint8_t * pix2, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_vsad_intra16_mmxext()
int ff_vsad_intra16_mmxext (MpegEncContext * v, uint8_t * pix1, uint8_t * pix2, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_vsad_intra16_sse2()
int ff_vsad_intra16_sse2 (MpegEncContext * v, uint8_t * pix1, uint8_t * pix2, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_vsad8_approx_mmxext()
int ff_vsad8_approx_mmxext (MpegEncContext * v, uint8_t * pix1, uint8_t * pix2, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_vsad16_approx_mmxext()
int ff_vsad16_approx_mmxext (MpegEncContext * v, uint8_t * pix1, uint8_t * pix2, ptrdiff_t stride, int h)
Referenced by hadamard_func().
ff_vsad16_approx_sse2()
int ff_vsad16_approx_sse2 (MpegEncContext * v, uint8_t * pix1, uint8_t * pix2, ptrdiff_t stride, int h)
Referenced by hadamard_func().
hadamard_func()
hadamard_func (mmx)
Definition at line 87 of file me_cmp_init.c.