FFmpeg: libavcodec/arm/me_cmp_init_arm.c File Reference
me_cmp_init_arm.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/arm/cpu.h"
#include "libavcodec/avcodec.h"
#include "libavcodec/me_cmp.h"
#include "libavcodec/mpegvideo.h"
Functions
int ff_pix_abs16_armv6 (MpegEncContext *s, uint8_t *blk1, uint8_t *blk2, ptrdiff_t stride, int h)
int ff_pix_abs16_x2_armv6 (MpegEncContext *s, uint8_t *blk1, uint8_t *blk2, ptrdiff_t stride, int h)
int ff_pix_abs16_y2_armv6 (MpegEncContext *s, uint8_t *blk1, uint8_t *blk2, ptrdiff_t stride, int h)
int ff_pix_abs8_armv6 (MpegEncContext *s, uint8_t *blk1, uint8_t *blk2, ptrdiff_t stride, int h)
int ff_sse16_armv6 (MpegEncContext *s, uint8_t *blk1, uint8_t *blk2, ptrdiff_t stride, int h)
av_cold void ff_me_cmp_init_arm (MECmpContext *c, AVCodecContext *avctx)
Function Documentation
ff_pix_abs16_armv6()
int ff_pix_abs16_armv6 (MpegEncContext * s, uint8_t * blk1, uint8_t * blk2, ptrdiff_t stride, int h)
Referenced by ff_me_cmp_init_arm().
ff_pix_abs16_x2_armv6()
int ff_pix_abs16_x2_armv6 (MpegEncContext * s, uint8_t * blk1, uint8_t * blk2, ptrdiff_t stride, int h)
Referenced by ff_me_cmp_init_arm().
ff_pix_abs16_y2_armv6()
int ff_pix_abs16_y2_armv6 (MpegEncContext * s, uint8_t * blk1, uint8_t * blk2, ptrdiff_t stride, int h)
Referenced by ff_me_cmp_init_arm().
ff_pix_abs8_armv6()
int ff_pix_abs8_armv6 (MpegEncContext * s, uint8_t * blk1, uint8_t * blk2, ptrdiff_t stride, int h)
Referenced by ff_me_cmp_init_arm().
ff_sse16_armv6()
int ff_sse16_armv6 (MpegEncContext * s, uint8_t * blk1, uint8_t * blk2, ptrdiff_t stride, int h)
Referenced by ff_me_cmp_init_arm().
ff_me_cmp_init_arm()
av_cold void ff_me_cmp_init_arm (MECmpContext * c, AVCodecContext * avctx)
Definition at line 41 of file me_cmp_init_arm.c.
Referenced by ff_me_cmp_init().