FFmpeg: libavcodec/me_cmp.h File Reference
me_cmp.h File Reference
#include <stdint.h>
#include "avcodec.h"
Data Structures
struct MECmpContext
Typedefs
typedef int(* me_cmp_func) (struct MpegEncContext *c, uint8_t *blk1, uint8_t *blk2, ptrdiff_t stride, int h)
Functions
void ff_me_cmp_init_static (void)
int ff_check_alignment (void)
void ff_me_cmp_init (MECmpContext *c, AVCodecContext *avctx)
void ff_me_cmp_init_alpha (MECmpContext *c, AVCodecContext *avctx)
void ff_me_cmp_init_arm (MECmpContext *c, AVCodecContext *avctx)
void ff_me_cmp_init_ppc (MECmpContext *c, AVCodecContext *avctx)
void ff_me_cmp_init_x86 (MECmpContext *c, AVCodecContext *avctx)
void ff_me_cmp_init_mips (MECmpContext *c, AVCodecContext *avctx)
void ff_set_cmp (MECmpContext *c, me_cmp_func *cmp, int type)
void ff_dsputil_init_dwt (MECmpContext *c)
Variables
uint32_t ff_square_tab [512]
Typedef Documentation
me_cmp_func
typedef int(* me_cmp_func) (struct MpegEncContext *c, uint8_t *blk1, uint8_t *blk2, ptrdiff_t stride, int h)
Definition at line 48 of file me_cmp.h.
Function Documentation
ff_me_cmp_init_static()
void ff_me_cmp_init_static (void)
Definition at line 980 of file me_cmp.c.
Referenced by avcodec_init().
ff_check_alignment()
int ff_check_alignment (void)
Definition at line 988 of file me_cmp.c.
Referenced by encode_thread(), estimate_motion_thread(), ff_me_cmp_init(), and mb_var_thread().
ff_me_cmp_init()
void ff_me_cmp_init (MECmpContext * c, AVCodecContext * avctx)
Definition at line 1009 of file me_cmp.c.
Referenced by dvvideo_encode_init(), ff_ac3_encode_init(), ff_er_frame_start(), ff_mpv_encode_init(), main(), mca(), and svq1_encode_init().
ff_me_cmp_init_alpha()
void ff_me_cmp_init_alpha (MECmpContext * c, AVCodecContext * avctx)
Definition at line 305 of file me_cmp_alpha.c.
Referenced by ff_me_cmp_init().
ff_me_cmp_init_arm()
void ff_me_cmp_init_arm (MECmpContext * c, AVCodecContext * avctx)
Definition at line 41 of file me_cmp_init_arm.c.
Referenced by ff_me_cmp_init().
ff_me_cmp_init_ppc()
void ff_me_cmp_init_ppc (MECmpContext * c, AVCodecContext * avctx)
Definition at line 729 of file me_cmp.c.
Referenced by ff_me_cmp_init().
ff_me_cmp_init_x86()
void ff_me_cmp_init_x86 (MECmpContext * c, AVCodecContext * avctx)
Referenced by ff_me_cmp_init(), and hadamard_func().
ff_me_cmp_init_mips()
void ff_me_cmp_init_mips (MECmpContext * c, AVCodecContext * avctx)
Definition at line 51 of file me_cmp_init_mips.c.
Referenced by ff_me_cmp_init().
ff_set_cmp()
void ff_set_cmp (MECmpContext * c, me_cmp_func * cmp, int type)
Definition at line 440 of file me_cmp.c.
Referenced by dvvideo_encode_init(), encode_init(), ff_init_me(), and ff_mpv_encode_init().
ff_dsputil_init_dwt()
void ff_dsputil_init_dwt (MECmpContext * c)
Definition at line 842 of file snow_dwt.c.
Referenced by ff_me_cmp_init().
Variable Documentation
ff_square_tab
uint32_t ff_square_tab[512]
Definition at line 32 of file me_cmp.c.
Referenced by ff_me_cmp_init_static(), pix_norm1(), pix_norm1_c(), sse(), sse16_c(), sse4_c(), and sse8_c().