FFmpeg: libavcodec/alpha/me_cmp_alpha.c File Reference
me_cmp_alpha.c File Reference
#include "libavutil/attributes.h"
#include "libavcodec/me_cmp.h"
#include "asm.h"
Functions
int pix_abs16x16_mvi_asm (void *v, uint8_t *pix1, uint8_t *pix2, int line_size, int h)
static uint64_t avg2 (uint64_t a, uint64_t b)
static uint64_t avg4 (uint64_t l1, uint64_t l2, uint64_t l3, uint64_t l4)
static int pix_abs8x8_mvi (void *v, uint8_t *pix1, uint8_t *pix2, int line_size, int h)
static int pix_abs16x16_x2_mvi (void *v, uint8_t *pix1, uint8_t *pix2, int line_size, int h)
static int pix_abs16x16_y2_mvi (void *v, uint8_t *pix1, uint8_t *pix2, int line_size, int h)
static int pix_abs16x16_xy2_mvi (void *v, uint8_t *pix1, uint8_t *pix2, int line_size, int h)
av_cold void ff_me_cmp_init_alpha (MECmpContext *c, AVCodecContext *avctx)
Function Documentation
pix_abs16x16_mvi_asm()
int pix_abs16x16_mvi_asm (void * v, uint8_t * pix1, uint8_t * pix2, int line_size, int h)
Referenced by ff_me_cmp_init_alpha().
avg2()
static uint64_t avg2 (uint64_t a, uint64_t b) inline static
Definition at line 28 of file me_cmp_alpha.c.
Referenced by pix_abs16x16_x2_mvi(), and pix_abs16x16_y2_mvi().
avg4()
static uint64_t avg4 (uint64_t l1, uint64_t l2, uint64_t l3, uint64_t l4) inline static
Definition at line 33 of file me_cmp_alpha.c.
Referenced by pix_abs16x16_xy2_mvi().
pix_abs8x8_mvi()
static int pix_abs8x8_mvi (void * v, uint8_t * pix1, uint8_t * pix2, int line_size, int h) static
Definition at line 47 of file me_cmp_alpha.c.
Referenced by ff_me_cmp_init_alpha().
pix_abs16x16_x2_mvi()
static int pix_abs16x16_x2_mvi (void * v, uint8_t * pix1, uint8_t * pix2, int line_size, int h) static
Definition at line 122 of file me_cmp_alpha.c.
Referenced by ff_me_cmp_init_alpha().
pix_abs16x16_y2_mvi()
static int pix_abs16x16_y2_mvi (void * v, uint8_t * pix1, uint8_t * pix2, int line_size, int h) static
Definition at line 195 of file me_cmp_alpha.c.
Referenced by ff_me_cmp_init_alpha().
pix_abs16x16_xy2_mvi()
static int pix_abs16x16_xy2_mvi (void * v, uint8_t * pix1, uint8_t * pix2, int line_size, int h) static
Definition at line 248 of file me_cmp_alpha.c.
Referenced by ff_me_cmp_init_alpha().
ff_me_cmp_init_alpha()
av_cold void ff_me_cmp_init_alpha (MECmpContext * c, AVCodecContext * avctx)
Definition at line 305 of file me_cmp_alpha.c.
Referenced by ff_me_cmp_init().