FFmpeg: libavcodec/mediacodecdec_common.c File Reference
mediacodecdec_common.c File Reference
#include <string.h>
#include <sys/types.h>
#include "libavutil/atomic.h"
#include "libavutil/common.h"
#include "libavutil/mem.h"
#include "libavutil/log.h"
#include "libavutil/pixfmt.h"
#include "libavutil/time.h"
#include "libavutil/timestamp.h"
#include "avcodec.h"
#include "internal.h"
#include "mediacodec.h"
#include "mediacodec_surface.h"
#include "mediacodec_sw_buffer.h"
#include "mediacodec_wrapper.h"
#include "mediacodecdec_common.h"
Macros
#define INPUT_DEQUEUE_TIMEOUT_US 8000
OMX.k3.video.decoder.avc, OMX.NVIDIA.
#define OUTPUT_DEQUEUE_TIMEOUT_US 8000
#define OUTPUT_DEQUEUE_BLOCK_TIMEOUT_US 1000000
Enumerations
enum {
COLOR_FormatYUV420Planar = 0x13, COLOR_FormatYUV420SemiPlanar = 0x15, COLOR_FormatYCbYCr = 0x19, COLOR_FormatAndroidOpaque = 0x7F000789,
COLOR_QCOM_FormatYUV420SemiPlanar = 0x7fa30c00, COLOR_QCOM_FormatYUV420SemiPlanar32m = 0x7fa30c04, COLOR_QCOM_FormatYUV420PackedSemiPlanar64x32Tile2m8ka = 0x7fa30c03, COLOR_TI_FormatYUV420PackedSemiPlanar = 0x7f000100,
COLOR_TI_FormatYUV420PackedSemiPlanarInterlaced = 0x7f000001
}
Functions
static enum AVPixelFormat mcdec_map_color_format (AVCodecContext *avctx, MediaCodecDecContext *s, int color_format)
static void ff_mediacodec_dec_ref (MediaCodecDecContext *s)
static void ff_mediacodec_dec_unref (MediaCodecDecContext *s)
static void mediacodec_buffer_release (void *opaque, uint8_t *data)
static int mediacodec_wrap_hw_buffer (AVCodecContext *avctx, MediaCodecDecContext *s, ssize_t index, FFAMediaCodecBufferInfo *info, AVFrame *frame)
static int mediacodec_wrap_sw_buffer (AVCodecContext *avctx, MediaCodecDecContext *s, uint8_t *data, size_t size, ssize_t index, FFAMediaCodecBufferInfo *info, AVFrame *frame)
static int mediacodec_dec_parse_format (AVCodecContext *avctx, MediaCodecDecContext *s)
static int mediacodec_dec_flush_codec (AVCodecContext *avctx, MediaCodecDecContext *s)
int ff_mediacodec_dec_init (AVCodecContext *avctx, MediaCodecDecContext *s, const char *mime, FFAMediaFormat *format)
int ff_mediacodec_dec_decode (AVCodecContext *avctx, MediaCodecDecContext *s, AVFrame *frame, int *got_frame, AVPacket *pkt)
int ff_mediacodec_dec_flush (AVCodecContext *avctx, MediaCodecDecContext *s)
int ff_mediacodec_dec_close (AVCodecContext *avctx, MediaCodecDecContext *s)
int ff_mediacodec_dec_is_flushing (AVCodecContext *avctx, MediaCodecDecContext *s)
Variables
struct {
int color_format
enum AVPixelFormat pix_fmt
} color_formats []
AVHWAccel ff_h264_mediacodec_hwaccel
AVHWAccel ff_hevc_mediacodec_hwaccel
AVHWAccel ff_mpeg4_mediacodec_hwaccel
AVHWAccel ff_vp8_mediacodec_hwaccel
AVHWAccel ff_vp9_mediacodec_hwaccel
Macro Definition Documentation
INPUT_DEQUEUE_TIMEOUT_US
#define INPUT_DEQUEUE_TIMEOUT_US 8000
OMX.k3.video.decoder.avc, OMX.NVIDIA.
OMX.SEC.avc.dec and OMX.google codec workarounds used in various place are taken from the Gstreamer project.
Gstreamer references: https://cgit.freedesktop.org/gstreamer/gst-plugins-bad/tree/sys/androidmedia/
Gstreamer copyright notice:
Copyright (C) 2012, Collabora Ltd. Author: Sebastian Dröge sebas.nosp@m.tian.nosp@m..droe.nosp@m.ge@c.nosp@m.ollab.nosp@m.ora..nosp@m.co.uk
Copyright (C) 2012, Rafaël Carré <funman>
Copyright (C) 2015, Sebastian Dröge sebas.nosp@m.tian.nosp@m.@cent.nosp@m.ricu.nosp@m.lar.c.nosp@m.om
Copyright (C) 2014-2015, Collabora Ltd. Author: Matthieu Bouron matth.nosp@m.ieu..nosp@m.bouro.nosp@m.n@gc.nosp@m.ollab.nosp@m.ora..nosp@m.com
Copyright (C) 2015, Edward Hervey Author: Edward Hervey bilbo.nosp@m.ed@g.nosp@m.mail..nosp@m.com
Copyright (C) 2015, Matthew Waters matth.nosp@m.ew@c.nosp@m.entri.nosp@m.cula.nosp@m.r.com
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation version 2.1 of the License.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
Definition at line 84 of file mediacodecdec_common.c.
Referenced by ff_mediacodec_dec_decode().
OUTPUT_DEQUEUE_TIMEOUT_US
#define OUTPUT_DEQUEUE_TIMEOUT_US 8000
Definition at line 85 of file mediacodecdec_common.c.
Referenced by ff_mediacodec_dec_decode().
OUTPUT_DEQUEUE_BLOCK_TIMEOUT_US
#define OUTPUT_DEQUEUE_BLOCK_TIMEOUT_US 1000000
Definition at line 86 of file mediacodecdec_common.c.
Referenced by ff_mediacodec_dec_decode().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
COLOR_FormatYUV420Planar
COLOR_FormatYUV420SemiPlanar
COLOR_FormatYCbYCr
COLOR_FormatAndroidOpaque
COLOR_QCOM_FormatYUV420SemiPlanar
COLOR_QCOM_FormatYUV420SemiPlanar32m
COLOR_QCOM_FormatYUV420PackedSemiPlanar64x32Tile2m8ka
COLOR_TI_FormatYUV420PackedSemiPlanar
COLOR_TI_FormatYUV420PackedSemiPlanarInterlaced
Definition at line 88 of file mediacodecdec_common.c.
Function Documentation
mcdec_map_color_format()
static enum AVPixelFormat mcdec_map_color_format (AVCodecContext * avctx, MediaCodecDecContext * s, int color_format) static
Definition at line 117 of file mediacodecdec_common.c.
Referenced by mediacodec_dec_parse_format().
ff_mediacodec_dec_ref()
static void ff_mediacodec_dec_ref (MediaCodecDecContext * s) static
Definition at line 144 of file mediacodecdec_common.c.
Referenced by mediacodec_wrap_hw_buffer().
ff_mediacodec_dec_unref()
static void ff_mediacodec_dec_unref (MediaCodecDecContext * s) static
Definition at line 149 of file mediacodecdec_common.c.
Referenced by ff_mediacodec_dec_close(), and mediacodec_buffer_release().
mediacodec_buffer_release()
static void mediacodec_buffer_release (void * opaque, uint8_t * data) static
Definition at line 175 of file mediacodecdec_common.c.
Referenced by mediacodec_wrap_hw_buffer().
mediacodec_wrap_hw_buffer()
static int mediacodec_wrap_hw_buffer (AVCodecContext * avctx, MediaCodecDecContext * s, ssize_t index, FFAMediaCodecBufferInfo * info, AVFrame * frame) static
Definition at line 189 of file mediacodecdec_common.c.
Referenced by ff_mediacodec_dec_decode().
mediacodec_wrap_sw_buffer()
static int mediacodec_wrap_sw_buffer (AVCodecContext * avctx, MediaCodecDecContext * s, uint8_t * data, size_t size, ssize_t index, FFAMediaCodecBufferInfo * info, AVFrame * frame) static
Definition at line 259 of file mediacodecdec_common.c.
Referenced by ff_mediacodec_dec_decode().
mediacodec_dec_parse_format()
static int mediacodec_dec_parse_format (AVCodecContext * avctx, MediaCodecDecContext * s) static
Definition at line 336 of file mediacodecdec_common.c.
Referenced by ff_mediacodec_dec_decode(), and ff_mediacodec_dec_init().
mediacodec_dec_flush_codec()
static int mediacodec_dec_flush_codec (AVCodecContext * avctx, MediaCodecDecContext * s) static
Definition at line 435 of file mediacodecdec_common.c.
Referenced by ff_mediacodec_dec_flush().
ff_mediacodec_dec_init()
int ff_mediacodec_dec_init (AVCodecContext * avctx, MediaCodecDecContext * s, const char * mime, FFAMediaFormat * format)
Definition at line 455 of file mediacodecdec_common.c.
Referenced by mediacodec_decode_init().
ff_mediacodec_dec_decode()
int ff_mediacodec_dec_decode (AVCodecContext * avctx, MediaCodecDecContext * s, AVFrame * frame, int * got_frame, AVPacket * pkt)
Definition at line 541 of file mediacodecdec_common.c.
Referenced by mediacodec_decode_frame(), and mediacodec_process_data().
ff_mediacodec_dec_flush()
int ff_mediacodec_dec_flush (AVCodecContext * avctx, MediaCodecDecContext * s)
Definition at line 726 of file mediacodecdec_common.c.
Referenced by mediacodec_decode_flush(), and mediacodec_decode_frame().
ff_mediacodec_dec_close()
int ff_mediacodec_dec_close (AVCodecContext * avctx, MediaCodecDecContext * s)
Definition at line 744 of file mediacodecdec_common.c.
Referenced by ff_mediacodec_dec_init(), and mediacodec_decode_close().
ff_mediacodec_dec_is_flushing()
int ff_mediacodec_dec_is_flushing (AVCodecContext * avctx, MediaCodecDecContext * s)
Definition at line 751 of file mediacodecdec_common.c.
Referenced by mediacodec_decode_frame().
Variable Documentation
color_format
int color_format
Definition at line 102 of file mediacodecdec_common.c.
pix_fmt
enum AVPixelFormat pix_fmt
Definition at line 103 of file mediacodecdec_common.c.
Referenced by ff_mediacodec_dec_init().
color_formats
const { ... } color_formats[]
Initial value:
= {
    { COLOR_FormatYUV420Planar,                              AV_PIX_FMT_YUV420P },
    { COLOR_FormatYUV420SemiPlanar,                          AV_PIX_FMT_NV12    },
    { COLOR_QCOM_FormatYUV420SemiPlanar,                     AV_PIX_FMT_NV12    },
    { COLOR_QCOM_FormatYUV420SemiPlanar32m,                  AV_PIX_FMT_NV12    },
    { COLOR_QCOM_FormatYUV420PackedSemiPlanar64x32Tile2m8ka, AV_PIX_FMT_NV12    },
    { COLOR_TI_FormatYUV420PackedSemiPlanar,                 AV_PIX_FMT_NV12    },
    { COLOR_TI_FormatYUV420PackedSemiPlanarInterlaced,       AV_PIX_FMT_NV12    },
    { 0 }
}
Referenced by mcdec_map_color_format().
ff_h264_mediacodec_hwaccel
AVHWAccel ff_h264_mediacodec_hwaccel
Initial value:
= {
    .name    = "mediacodec",
    .type    = AVMEDIA_TYPE_VIDEO,
    .id      = AV_CODEC_ID_H264,
    .pix_fmt = AV_PIX_FMT_MEDIACODEC,
}
Definition at line 756 of file mediacodecdec_common.c.
ff_hevc_mediacodec_hwaccel
AVHWAccel ff_hevc_mediacodec_hwaccel
Initial value:
= {
    .name    = "mediacodec",
    .type    = AVMEDIA_TYPE_VIDEO,
    .id      = AV_CODEC_ID_HEVC,
    .pix_fmt = AV_PIX_FMT_MEDIACODEC,
}
Definition at line 763 of file mediacodecdec_common.c.
ff_mpeg4_mediacodec_hwaccel
AVHWAccel ff_mpeg4_mediacodec_hwaccel
Initial value:
= {
    .name    = "mediacodec",
    .type    = AVMEDIA_TYPE_VIDEO,
    .id      = AV_CODEC_ID_MPEG4,
    .pix_fmt = AV_PIX_FMT_MEDIACODEC,
}
Definition at line 770 of file mediacodecdec_common.c.
ff_vp8_mediacodec_hwaccel
AVHWAccel ff_vp8_mediacodec_hwaccel
Initial value:
= {
    .name    = "mediacodec",
    .type    = AVMEDIA_TYPE_VIDEO,
    .id      = AV_CODEC_ID_VP8,
    .pix_fmt = AV_PIX_FMT_MEDIACODEC,
}
Definition at line 777 of file mediacodecdec_common.c.
ff_vp9_mediacodec_hwaccel
AVHWAccel ff_vp9_mediacodec_hwaccel
Initial value:
= {
    .name    = "mediacodec",
    .type    = AVMEDIA_TYPE_VIDEO,
    .id      = AV_CODEC_ID_VP9,
    .pix_fmt = AV_PIX_FMT_MEDIACODEC,
}
Definition at line 784 of file mediacodecdec_common.c.