FFmpeg: libavcodec/mediacodec_wrapper.c File Reference
mediacodec_wrapper.c File Reference
#include <jni.h>
#include "libavutil/avassert.h"
#include "libavutil/mem.h"
#include "libavutil/avstring.h"
#include "avcodec.h"
#include "ffjni.h"
#include "version.h"
#include "mediacodec_wrapper.h"
Data Structures
struct JNIAMediaCodecListFields
struct JNIAMediaFormatFields
struct FFAMediaFormat
struct JNIAMediaCodecFields
struct FFAMediaCodec
Macros
#define JNI_GET_ENV_OR_RETURN(env, log_ctx, ret)
#define JNI_GET_ENV_OR_RETURN_VOID(env, log_ctx)
Functions
int ff_AMediaCodecProfile_getProfileFromAVCodecContext (AVCodecContext *avctx)
The following API around MediaCodec and MediaFormat is based on the NDK one provided by Google since Android 5.0.
char * ff_AMediaCodecList_getCodecNameByType (const char *mime, int profile, int encoder, void *log_ctx)
FFAMediaFormat * ff_AMediaFormat_new (void)
static FFAMediaFormat * ff_AMediaFormat_newFromObject (void *object)
int ff_AMediaFormat_delete (FFAMediaFormat *format)
char * ff_AMediaFormat_toString (FFAMediaFormat *format)
int ff_AMediaFormat_getInt32 (FFAMediaFormat *format, const char *name, int32_t *out)
int ff_AMediaFormat_getInt64 (FFAMediaFormat *format, const char *name, int64_t *out)
int ff_AMediaFormat_getFloat (FFAMediaFormat *format, const char *name, float *out)
int ff_AMediaFormat_getBuffer (FFAMediaFormat *format, const char *name, void **data, size_t *size)
int ff_AMediaFormat_getString (FFAMediaFormat *format, const char *name, const char **out)
void ff_AMediaFormat_setInt32 (FFAMediaFormat *format, const char *name, int32_t value)
void ff_AMediaFormat_setInt64 (FFAMediaFormat *format, const char *name, int64_t value)
void ff_AMediaFormat_setFloat (FFAMediaFormat *format, const char *name, float value)
void ff_AMediaFormat_setString (FFAMediaFormat *format, const char *name, const char *value)
void ff_AMediaFormat_setBuffer (FFAMediaFormat *format, const char *name, void *data, size_t size)
static int codec_init_static_fields (FFAMediaCodec *codec)
FFAMediaCodec * ff_AMediaCodec_createCodecByName (const char *name)
FFAMediaCodec * ff_AMediaCodec_createDecoderByType (const char *mime)
FFAMediaCodec * ff_AMediaCodec_createEncoderByType (const char *mime)
int ff_AMediaCodec_delete (FFAMediaCodec *codec)
char * ff_AMediaCodec_getName (FFAMediaCodec *codec)
int ff_AMediaCodec_configure (FFAMediaCodec *codec, const FFAMediaFormat *format, void *surface, void *crypto, uint32_t flags)
int ff_AMediaCodec_start (FFAMediaCodec *codec)
int ff_AMediaCodec_stop (FFAMediaCodec *codec)
int ff_AMediaCodec_flush (FFAMediaCodec *codec)
int ff_AMediaCodec_releaseOutputBuffer (FFAMediaCodec *codec, size_t idx, int render)
int ff_AMediaCodec_releaseOutputBufferAtTime (FFAMediaCodec *codec, size_t idx, int64_t timestampNs)
ssize_t ff_AMediaCodec_dequeueInputBuffer (FFAMediaCodec *codec, int64_t timeoutUs)
int ff_AMediaCodec_queueInputBuffer (FFAMediaCodec *codec, size_t idx, off_t offset, size_t size, uint64_t time, uint32_t flags)
ssize_t ff_AMediaCodec_dequeueOutputBuffer (FFAMediaCodec *codec, FFAMediaCodecBufferInfo *info, int64_t timeoutUs)
uint8_t * ff_AMediaCodec_getInputBuffer (FFAMediaCodec *codec, size_t idx, size_t *out_size)
uint8_t * ff_AMediaCodec_getOutputBuffer (FFAMediaCodec *codec, size_t idx, size_t *out_size)
FFAMediaFormat * ff_AMediaCodec_getOutputFormat (FFAMediaCodec *codec)
int ff_AMediaCodec_infoTryAgainLater (FFAMediaCodec *codec, ssize_t idx)
int ff_AMediaCodec_infoOutputBuffersChanged (FFAMediaCodec *codec, ssize_t idx)
int ff_AMediaCodec_infoOutputFormatChanged (FFAMediaCodec *codec, ssize_t idx)
int ff_AMediaCodec_getBufferFlagCodecConfig (FFAMediaCodec *codec)
int ff_AMediaCodec_getBufferFlagEndOfStream (FFAMediaCodec *codec)
int ff_AMediaCodec_getBufferFlagKeyFrame (FFAMediaCodec *codec)
int ff_AMediaCodec_getConfigureFlagEncode (FFAMediaCodec *codec)
int ff_AMediaCodec_cleanOutputBuffers (FFAMediaCodec *codec)
Variables
struct JNIAMediaCodecListFields JNIAMediaCodecListFields
static const struct FFJniField jni_amediacodeclist_mapping []
struct JNIAMediaFormatFields JNIAMediaFormatFields
static const struct FFJniField jni_amediaformat_mapping []
static const AVClass amediaformat_class
struct JNIAMediaCodecFields JNIAMediaCodecFields
static const struct FFJniField jni_amediacodec_mapping []
static const AVClass amediacodec_class
Macro Definition Documentation
JNI_GET_ENV_OR_RETURN
#define JNI_GET_ENV_OR_RETURN (env, log_ctx, ret)
Value:
do {              \
    (env) = ff_jni_get_env(log_ctx);                               \
    if (!(env)) {                                                  \
        return ret;                                                \
    }                                                              \
} while (0)
Definition at line 294 of file mediacodec_wrapper.c.
Referenced by codec_init_static_fields(), ff_AMediaCodec_configure(), ff_AMediaCodec_delete(), ff_AMediaCodec_dequeueInputBuffer(), ff_AMediaCodec_dequeueOutputBuffer(), ff_AMediaCodec_flush(), ff_AMediaCodec_getInputBuffer(), ff_AMediaCodec_getName(), ff_AMediaCodec_getOutputBuffer(), ff_AMediaCodec_getOutputFormat(), ff_AMediaCodec_queueInputBuffer(), ff_AMediaCodec_releaseOutputBuffer(), ff_AMediaCodec_releaseOutputBufferAtTime(), ff_AMediaCodec_start(), ff_AMediaCodec_stop(), ff_AMediaCodecList_getCodecNameByType(), ff_AMediaCodecProfile_getProfileFromAVCodecContext(), ff_AMediaFormat_delete(), ff_AMediaFormat_getBuffer(), ff_AMediaFormat_getFloat(), ff_AMediaFormat_getInt32(), ff_AMediaFormat_getInt64(), ff_AMediaFormat_getString(), and ff_AMediaFormat_toString().
JNI_GET_ENV_OR_RETURN_VOID
#define JNI_GET_ENV_OR_RETURN_VOID (env, log_ctx)
Value:
do {              \
    (env) = ff_jni_get_env(log_ctx);                               \
    if (!(env)) {                                                  \
        return;                                                    \
    }                                                              \
} while (0)
Definition at line 301 of file mediacodec_wrapper.c.
Referenced by ff_AMediaFormat_setBuffer(), ff_AMediaFormat_setFloat(), ff_AMediaFormat_setInt32(), ff_AMediaFormat_setInt64(), and ff_AMediaFormat_setString().
Function Documentation
ff_AMediaCodecProfile_getProfileFromAVCodecContext()
int ff_AMediaCodecProfile_getProfileFromAVCodecContext (AVCodecContext * avctx)
The following API around MediaCodec and MediaFormat is based on the NDK one provided by Google since Android 5.0.
Differences from the NDK API:
Buffers returned by ff_AMediaFormat_toString and ff_AMediaFormat_getString are newly allocated buffer and must be freed by the user after use.
The MediaCrypto API is not implemented.
ff_AMediaCodec_infoTryAgainLater, ff_AMediaCodec_infoOutputBuffersChanged, ff_AMediaCodec_infoOutputFormatChanged, ff_AMediaCodec_cleanOutputBuffers ff_AMediaCodec_getName and ff_AMediaCodec_getBufferFlagEndOfStream are not part of the original NDK API and are convenience functions to hide JNI implementation.
The API around MediaCodecList is not part of the NDK (and is lacking as we still need to retrieve the codec name to work around faulty decoders and encoders).
For documentation, please refers to NdkMediaCodec.h NdkMediaFormat.h and http://developer.android.com/reference/android/media/MediaCodec.html.
Definition at line 308 of file mediacodec_wrapper.c.
Referenced by ff_mediacodec_dec_init().
ff_AMediaCodecList_getCodecNameByType()
char* ff_AMediaCodecList_getCodecNameByType (const char * mime, int profile, int encoder, void * log_ctx)
Definition at line 377 of file mediacodec_wrapper.c.
Referenced by ff_mediacodec_dec_init().
ff_AMediaFormat_new()
FFAMediaFormat* ff_AMediaFormat_new (void)
Definition at line 607 of file mediacodec_wrapper.c.
Referenced by mediacodec_decode_init().
ff_AMediaFormat_newFromObject()
static FFAMediaFormat* ff_AMediaFormat_newFromObject (void * object) static
Definition at line 647 of file mediacodec_wrapper.c.
Referenced by ff_AMediaCodec_getOutputFormat().
ff_AMediaFormat_delete()
int ff_AMediaFormat_delete (FFAMediaFormat * format)
Definition at line 682 of file mediacodec_wrapper.c.
Referenced by ff_mediacodec_dec_decode(), ff_mediacodec_dec_unref(), and mediacodec_decode_init().
ff_AMediaFormat_toString()
char* ff_AMediaFormat_toString (FFAMediaFormat * format)
Definition at line 704 of file mediacodec_wrapper.c.
Referenced by ff_mediacodec_dec_decode(), ff_mediacodec_dec_init(), and mediacodec_dec_parse_format().
ff_AMediaFormat_getInt32()
int ff_AMediaFormat_getInt32 (FFAMediaFormat * format, const char * name, int32_t * out)
Definition at line 729 of file mediacodec_wrapper.c.
Referenced by mediacodec_dec_parse_format().
ff_AMediaFormat_getInt64()
int ff_AMediaFormat_getInt64 (FFAMediaFormat * format, const char * name, int64_t * out)
Definition at line 761 of file mediacodec_wrapper.c.
ff_AMediaFormat_getFloat()
int ff_AMediaFormat_getFloat (FFAMediaFormat * format, const char * name, float * out)
Definition at line 793 of file mediacodec_wrapper.c.
ff_AMediaFormat_getBuffer()
int ff_AMediaFormat_getBuffer (FFAMediaFormat * format, const char * name, void ** data, size_t * size)
Definition at line 825 of file mediacodec_wrapper.c.
ff_AMediaFormat_getString()
int ff_AMediaFormat_getString (FFAMediaFormat * format, const char * name, const char ** out)
Definition at line 876 of file mediacodec_wrapper.c.
ff_AMediaFormat_setInt32()
void ff_AMediaFormat_setInt32 (FFAMediaFormat * format, const char * name, int32_t value)
Definition at line 919 of file mediacodec_wrapper.c.
Referenced by mediacodec_decode_init().
ff_AMediaFormat_setInt64()
void ff_AMediaFormat_setInt64 (FFAMediaFormat * format, const char * name, int64_t value)
Definition at line 944 of file mediacodec_wrapper.c.
ff_AMediaFormat_setFloat()
void ff_AMediaFormat_setFloat (FFAMediaFormat * format, const char * name, float value)
Definition at line 969 of file mediacodec_wrapper.c.
ff_AMediaFormat_setString()
void ff_AMediaFormat_setString (FFAMediaFormat * format, const char * name, const char * value)
Definition at line 994 of file mediacodec_wrapper.c.
Referenced by mediacodec_decode_init().
ff_AMediaFormat_setBuffer()
void ff_AMediaFormat_setBuffer (FFAMediaFormat * format, const char * name, void * data, size_t size)
Definition at line 1029 of file mediacodec_wrapper.c.
Referenced by mediacodec_decode_close().
codec_init_static_fields()
static int codec_init_static_fields (FFAMediaCodec * codec) static
Definition at line 1076 of file mediacodec_wrapper.c.
Referenced by ff_AMediaCodec_createCodecByName(), ff_AMediaCodec_createDecoderByType(), and ff_AMediaCodec_createEncoderByType().
ff_AMediaCodec_createCodecByName()
FFAMediaCodec* ff_AMediaCodec_createCodecByName (const char * name)
Definition at line 1130 of file mediacodec_wrapper.c.
Referenced by ff_mediacodec_dec_init().
ff_AMediaCodec_createDecoderByType()
FFAMediaCodec* ff_AMediaCodec_createDecoderByType (const char * mime)
Definition at line 1188 of file mediacodec_wrapper.c.
ff_AMediaCodec_createEncoderByType()
FFAMediaCodec* ff_AMediaCodec_createEncoderByType (const char * mime)
Definition at line 1246 of file mediacodec_wrapper.c.
ff_AMediaCodec_delete()
int ff_AMediaCodec_delete (FFAMediaCodec * codec)
Definition at line 1304 of file mediacodec_wrapper.c.
Referenced by ff_mediacodec_dec_unref().
ff_AMediaCodec_getName()
char* ff_AMediaCodec_getName (FFAMediaCodec * codec)
Definition at line 1331 of file mediacodec_wrapper.c.
ff_AMediaCodec_configure()
int ff_AMediaCodec_configure (FFAMediaCodec * codec, const FFAMediaFormat * format, void * surface, void * crypto, uint32_t flags)
Definition at line 1350 of file mediacodec_wrapper.c.
Referenced by ff_mediacodec_dec_init().
ff_AMediaCodec_start()
int ff_AMediaCodec_start (FFAMediaCodec * codec)
Definition at line 1367 of file mediacodec_wrapper.c.
Referenced by ff_mediacodec_dec_init().
ff_AMediaCodec_stop()
int ff_AMediaCodec_stop (FFAMediaCodec * codec)
Definition at line 1384 of file mediacodec_wrapper.c.
ff_AMediaCodec_flush()
int ff_AMediaCodec_flush (FFAMediaCodec * codec)
Definition at line 1401 of file mediacodec_wrapper.c.
Referenced by mediacodec_dec_flush_codec().
ff_AMediaCodec_releaseOutputBuffer()
int ff_AMediaCodec_releaseOutputBuffer (FFAMediaCodec * codec, size_t idx, int render)
Definition at line 1418 of file mediacodec_wrapper.c.
Referenced by ff_mediacodec_dec_decode(), mediacodec_buffer_release(), mediacodec_wrap_hw_buffer(), and mediacodec_wrap_sw_buffer().
ff_AMediaCodec_releaseOutputBufferAtTime()
int ff_AMediaCodec_releaseOutputBufferAtTime (FFAMediaCodec * codec, size_t idx, int64_t timestampNs)
Definition at line 1435 of file mediacodec_wrapper.c.
ff_AMediaCodec_dequeueInputBuffer()
ssize_t ff_AMediaCodec_dequeueInputBuffer (FFAMediaCodec * codec, int64_t timeoutUs)
Definition at line 1452 of file mediacodec_wrapper.c.
Referenced by ff_mediacodec_dec_decode().
ff_AMediaCodec_queueInputBuffer()
int ff_AMediaCodec_queueInputBuffer (FFAMediaCodec * codec, size_t idx, off_t offset, size_t size, uint64_t time, uint32_t flags)
Definition at line 1469 of file mediacodec_wrapper.c.
Referenced by ff_mediacodec_dec_decode().
ff_AMediaCodec_dequeueOutputBuffer()
ssize_t ff_AMediaCodec_dequeueOutputBuffer (FFAMediaCodec * codec, FFAMediaCodecBufferInfo * info, int64_t timeoutUs)
Definition at line 1486 of file mediacodec_wrapper.c.
Referenced by ff_mediacodec_dec_decode().
ff_AMediaCodec_getInputBuffer()
uint8_t* ff_AMediaCodec_getInputBuffer (FFAMediaCodec * codec, size_t idx, size_t * out_size)
Definition at line 1538 of file mediacodec_wrapper.c.
Referenced by ff_mediacodec_dec_decode().
ff_AMediaCodec_getOutputBuffer()
uint8_t* ff_AMediaCodec_getOutputBuffer (FFAMediaCodec * codec, size_t idx, size_t * out_size)
Definition at line 1581 of file mediacodec_wrapper.c.
Referenced by ff_mediacodec_dec_decode().
ff_AMediaCodec_getOutputFormat()
FFAMediaFormat* ff_AMediaCodec_getOutputFormat (FFAMediaCodec * codec)
Definition at line 1624 of file mediacodec_wrapper.c.
Referenced by ff_mediacodec_dec_decode(), and ff_mediacodec_dec_init().
ff_AMediaCodec_infoTryAgainLater()
int ff_AMediaCodec_infoTryAgainLater (FFAMediaCodec * codec, ssize_t idx)
Definition at line 1647 of file mediacodec_wrapper.c.
Referenced by ff_mediacodec_dec_decode().
ff_AMediaCodec_infoOutputBuffersChanged()
int ff_AMediaCodec_infoOutputBuffersChanged (FFAMediaCodec * codec, ssize_t idx)
Definition at line 1652 of file mediacodec_wrapper.c.
Referenced by ff_mediacodec_dec_decode().
ff_AMediaCodec_infoOutputFormatChanged()
int ff_AMediaCodec_infoOutputFormatChanged (FFAMediaCodec * codec, ssize_t idx)
Definition at line 1657 of file mediacodec_wrapper.c.
Referenced by ff_mediacodec_dec_decode().
ff_AMediaCodec_getBufferFlagCodecConfig()
int ff_AMediaCodec_getBufferFlagCodecConfig (FFAMediaCodec * codec)
Definition at line 1662 of file mediacodec_wrapper.c.
ff_AMediaCodec_getBufferFlagEndOfStream()
int ff_AMediaCodec_getBufferFlagEndOfStream (FFAMediaCodec * codec)
Definition at line 1667 of file mediacodec_wrapper.c.
Referenced by ff_mediacodec_dec_decode().
ff_AMediaCodec_getBufferFlagKeyFrame()
int ff_AMediaCodec_getBufferFlagKeyFrame (FFAMediaCodec * codec)
Definition at line 1672 of file mediacodec_wrapper.c.
ff_AMediaCodec_getConfigureFlagEncode()
int ff_AMediaCodec_getConfigureFlagEncode (FFAMediaCodec * codec)
Definition at line 1677 of file mediacodec_wrapper.c.
ff_AMediaCodec_cleanOutputBuffers()
int ff_AMediaCodec_cleanOutputBuffers (FFAMediaCodec * codec)
Definition at line 1682 of file mediacodec_wrapper.c.
Referenced by ff_mediacodec_dec_decode().
Variable Documentation
JNIAMediaCodecListFields
struct JNIAMediaCodecListFields JNIAMediaCodecListFields
jni_amediacodeclist_mapping
const struct FFJniField jni_amediacodeclist_mapping[] static
Definition at line 71 of file mediacodec_wrapper.c.
JNIAMediaFormatFields
struct JNIAMediaFormatFields JNIAMediaFormatFields
jni_amediaformat_mapping
const struct FFJniField jni_amediaformat_mapping[] static
Initial value:
= {
    { "android/media/MediaFormat", NULL, NULL, FF_JNI_CLASS, 0x42, 1 },
        { "android/media/MediaFormat", "<init>", "()V", FF_JNI_METHOD, 0x42, 1 },
        { "android/media/MediaFormat", "getInteger", "(Ljava/lang/String;)I", FF_JNI_METHOD, 0x42, 1 },
        { "android/media/MediaFormat", "getLong", "(Ljava/lang/String;)J", FF_JNI_METHOD, 0x42, 1 },
        { "android/media/MediaFormat", "getFloat", "(Ljava/lang/String;)F", FF_JNI_METHOD, 0x42, 1 },
        { "android/media/MediaFormat", "getByteBuffer", "(Ljava/lang/String;)Ljava/nio/ByteBuffer;", FF_JNI_METHOD, 0x42, 1 },
        { "android/media/MediaFormat", "getString", "(Ljava/lang/String;)Ljava/lang/String;", FF_JNI_METHOD, 0x42, 1 },
        { "android/media/MediaFormat", "setInteger", "(Ljava/lang/String;I)V", FF_JNI_METHOD, 0x42, 1 },
        { "android/media/MediaFormat", "setLong", "(Ljava/lang/String;J)V", FF_JNI_METHOD, 0x42, 1 },
        { "android/media/MediaFormat", "setFloat", "(Ljava/lang/String;F)V", FF_JNI_METHOD, 0x42, 1 },
        { "android/media/MediaFormat", "setByteBuffer", "(Ljava/lang/String;Ljava/nio/ByteBuffer;)V", FF_JNI_METHOD, 0x42, 1 },
        { "android/media/MediaFormat", "setString", "(Ljava/lang/String;Ljava/lang/String;)V", FF_JNI_METHOD, 0x42, 1 },
        { "android/media/MediaFormat", "toString", "()Ljava/lang/String;", FF_JNI_METHOD, 0x42, 1 },
    { NULL }
}
Definition at line 130 of file mediacodec_wrapper.c.
amediaformat_class
const AVClass amediaformat_class static
Initial value:
= {
    .class_name = "amediaformat",
    .item_name  = av_default_item_name,
    .version    = LIBAVCODEC_VERSION_INT,
}
Definition at line 152 of file mediacodec_wrapper.c.
Referenced by ff_AMediaFormat_new(), and ff_AMediaFormat_newFromObject().
JNIAMediaCodecFields
struct JNIAMediaCodecFields JNIAMediaCodecFields
jni_amediacodec_mapping
const struct FFJniField jni_amediacodec_mapping[] static
Definition at line 215 of file mediacodec_wrapper.c.
amediacodec_class
const AVClass amediacodec_class static
Initial value:
= {
    .class_name = "amediacodec",
    .item_name  = av_default_item_name,
    .version    = LIBAVCODEC_VERSION_INT,
}
Definition at line 264 of file mediacodec_wrapper.c.
Referenced by ff_AMediaCodec_createCodecByName(), ff_AMediaCodec_createDecoderByType(), and ff_AMediaCodec_createEncoderByType().