FFmpeg: libavcodec/mediacodecdec.c File Reference
mediacodecdec.c File Reference
#include <stdint.h>
#include <string.h>
#include "libavutil/avassert.h"
#include "libavutil/common.h"
#include "libavutil/fifo.h"
#include "libavutil/opt.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/pixfmt.h"
#include "libavutil/atomic.h"
#include "avcodec.h"
#include "h264_parse.h"
#include "hevc_parse.h"
#include "internal.h"
#include "mediacodec_wrapper.h"
#include "mediacodecdec_common.h"
Data Structures
struct MediaCodecH264DecContext
Functions
static av_cold int mediacodec_decode_close (AVCodecContext *avctx)
static av_cold int mediacodec_decode_init (AVCodecContext *avctx)
static int mediacodec_process_data (AVCodecContext *avctx, AVFrame *frame, int *got_frame, AVPacket *pkt)
static int mediacodec_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static void mediacodec_decode_flush (AVCodecContext *avctx)
Function Documentation
mediacodec_decode_close()
static av_cold int mediacodec_decode_close (AVCodecContext * avctx) static
Definition at line 53 of file mediacodecdec.c.
Referenced by mediacodec_decode_flush(), and mediacodec_decode_init().
mediacodec_decode_init()
static av_cold int mediacodec_decode_init (AVCodecContext * avctx) static
Definition at line 295 of file mediacodecdec.c.
Referenced by mediacodec_decode_flush().
mediacodec_process_data()
static int mediacodec_process_data (AVCodecContext * avctx, AVFrame * frame, int * got_frame, AVPacket * pkt) static
Definition at line 422 of file mediacodecdec.c.
Referenced by mediacodec_decode_frame().
mediacodec_decode_frame()
static int mediacodec_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 430 of file mediacodecdec.c.
Referenced by mediacodec_decode_flush().
mediacodec_decode_flush()
static void mediacodec_decode_flush (AVCodecContext * avctx) static
Definition at line 529 of file mediacodecdec.c.