FFmpeg: libavcodec/mediacodecdec_common.h File Reference
mediacodecdec_common.h File Reference
#include <stdint.h>
#include <sys/types.h>
#include "libavutil/frame.h"
#include "libavutil/pixfmt.h"
#include "avcodec.h"
#include "mediacodec_wrapper.h"
Data Structures
struct MediaCodecDecContext
struct AVMediaCodecBuffer
Opaque structure representing a MediaCodec buffer to render.
Functions
int ff_mediacodec_dec_init (AVCodecContext *avctx, MediaCodecDecContext *s, const char *mime, FFAMediaFormat *format)
int ff_mediacodec_dec_decode (AVCodecContext *avctx, MediaCodecDecContext *s, AVFrame *frame, int *got_frame, AVPacket *pkt)
int ff_mediacodec_dec_flush (AVCodecContext *avctx, MediaCodecDecContext *s)
int ff_mediacodec_dec_close (AVCodecContext *avctx, MediaCodecDecContext *s)
int ff_mediacodec_dec_is_flushing (AVCodecContext *avctx, MediaCodecDecContext *s)
Function Documentation
ff_mediacodec_dec_init()
int ff_mediacodec_dec_init (AVCodecContext * avctx, MediaCodecDecContext * s, const char * mime, FFAMediaFormat * format)
Definition at line 455 of file mediacodecdec_common.c.
Referenced by mediacodec_decode_init().
ff_mediacodec_dec_decode()
int ff_mediacodec_dec_decode (AVCodecContext * avctx, MediaCodecDecContext * s, AVFrame * frame, int * got_frame, AVPacket * pkt)
Definition at line 541 of file mediacodecdec_common.c.
Referenced by mediacodec_decode_frame(), and mediacodec_process_data().
ff_mediacodec_dec_flush()
int ff_mediacodec_dec_flush (AVCodecContext * avctx, MediaCodecDecContext * s)
Definition at line 726 of file mediacodecdec_common.c.
Referenced by mediacodec_decode_flush(), and mediacodec_decode_frame().
ff_mediacodec_dec_close()
int ff_mediacodec_dec_close (AVCodecContext * avctx, MediaCodecDecContext * s)
Definition at line 744 of file mediacodecdec_common.c.
Referenced by ff_mediacodec_dec_init(), and mediacodec_decode_close().
ff_mediacodec_dec_is_flushing()
int ff_mediacodec_dec_is_flushing (AVCodecContext * avctx, MediaCodecDecContext * s)
Definition at line 751 of file mediacodecdec_common.c.
Referenced by mediacodec_decode_frame().