FFmpeg: libavformat/metadata.h File Reference
metadata.h File Reference
internal metadata API header see avformat.h or the public API!
#include "avformat.h"
#include "libavutil/dict.h"
Data Structures
struct AVMetadataConv
Functions
void ff_metadata_conv (AVDictionary **pm, const AVMetadataConv *d_conv, const AVMetadataConv *s_conv)
void ff_metadata_conv_ctx (AVFormatContext *ctx, const AVMetadataConv *d_conv, const AVMetadataConv *s_conv)
Detailed Description
internal metadata API header see avformat.h or the public API!
Definition in file metadata.h.
Function Documentation
ff_metadata_conv()
void ff_metadata_conv (AVDictionary ** pm, const AVMetadataConv * d_conv, const AVMetadataConv * s_conv)
Definition at line 26 of file metadata.c.
Referenced by asf_read_header(), asf_write_header1(), ff_metadata_conv_ctx(), ff_riff_write_info(), ff_vorbis_comment(), flac_write_block_comment(), id3v2_read_internal(), matroska_convert_tag(), ogg_write_vorbiscomment(), parse_legacy_attrib(), read_chapter(), write_metadata(), and write_table_entries_attrib().
ff_metadata_conv_ctx()
void ff_metadata_conv_ctx (AVFormatContext * ctx, const AVMetadataConv * d_conv, const AVMetadataConv * s_conv)
Definition at line 59 of file metadata.c.
Referenced by avi_read_header(), lrc_read_header(), lrc_write_header(), mkv_write_tags(), nut_read_header(), set_spdif(), vqf_read_header(), and write_headers().