FFmpeg: libavcodec/metasound.c File Reference
metasound.c File Reference
#include <inttypes.h>
#include <math.h>
#include <stdint.h>
#include "libavutil/channel_layout.h"
#include "libavutil/float_dsp.h"
#include "avcodec.h"
#include "fft.h"
#include "get_bits.h"
#include "internal.h"
#include "lsp.h"
#include "sinewin.h"
#include "twinvq.h"
#include "metasound_data.h"
Data Structures
struct MetasoundProps
Macros
#define BITSTREAM_READER_LE
Functions
static void add_peak (float period, int width, const float *shape, float ppc_gain, float *speech, int len)
static void decode_ppc (TwinVQContext *tctx, int period_coef, int g_coef, const float *shape, float *speech)
static void dec_bark_env (TwinVQContext *tctx, const uint8_t *in, int use_hist, int ch, float *out, float gain, enum TwinVQFrameType ftype)
static void read_cb_data (TwinVQContext *tctx, GetBitContext *gb, uint8_t *dst, enum TwinVQFrameType ftype)
static int metasound_read_bitstream (AVCodecContext *avctx, TwinVQContext *tctx, const uint8_t *buf, int buf_size)
static av_cold int metasound_decode_init (AVCodecContext *avctx)
Variables
static const MetasoundProps codec_props []
AVCodec ff_metasound_decoder
Macro Definition Documentation
BITSTREAM_READER_LE
#define BITSTREAM_READER_LE
Definition at line 31 of file metasound.c.
Function Documentation
add_peak()
static void add_peak (float period, int width, const float * shape, float ppc_gain, float * speech, int len) static
Definition at line 42 of file metasound.c.
Referenced by decode_ppc().
decode_ppc()
static void decode_ppc (TwinVQContext * tctx, int period_coef, int g_coef, const float * shape, float * speech) static
Definition at line 64 of file metasound.c.
Referenced by metasound_decode_init().
dec_bark_env()
static void dec_bark_env (TwinVQContext * tctx, const uint8_t * in, int use_hist, int ch, float * out, float gain, enum TwinVQFrameType ftype) static
Definition at line 115 of file metasound.c.
Referenced by metasound_decode_init().
read_cb_data()
static void read_cb_data (TwinVQContext * tctx, GetBitContext * gb, uint8_t * dst, enum TwinVQFrameType ftype) static
Definition at line 152 of file metasound.c.
Referenced by metasound_read_bitstream().
metasound_read_bitstream()
static int metasound_read_bitstream (AVCodecContext * avctx, TwinVQContext * tctx, const uint8_t * buf, int buf_size) static
Definition at line 165 of file metasound.c.
Referenced by metasound_decode_init().
metasound_decode_init()
static av_cold int metasound_decode_init (AVCodecContext * avctx) static
Definition at line 272 of file metasound.c.
Variable Documentation
codec_props
const MetasoundProps codec_props[] static
Initial value:
= {
    { MKTAG('V','X','0','3'),  6, 1,  8000 },
    { MKTAG('V','X','0','4'), 12, 2,  8000 },
    { MKTAG('V','O','X','i'),  8, 1,  8000 },
    { MKTAG('V','O','X','j'), 10, 1, 11025 },
    { MKTAG('V','O','X','k'), 16, 1, 16000 },
    { MKTAG('V','O','X','L'), 24, 1, 22050 },
    { MKTAG('V','O','X','q'), 32, 1, 44100 },
    { MKTAG('V','O','X','r'), 40, 1, 44100 },
    { MKTAG('V','O','X','s'), 48, 1, 44100 },
    { MKTAG('V','O','X','t'), 16, 2,  8000 },
    { MKTAG('V','O','X','u'), 20, 2, 11025 },
    { MKTAG('V','O','X','v'), 32, 2, 16000 },
    { MKTAG('V','O','X','w'), 48, 2, 22050 },
    { MKTAG('V','O','X','x'), 64, 2, 44100 },
    { MKTAG('V','O','X','y'), 80, 2, 44100 },
    { MKTAG('V','O','X','z'), 96, 2, 44100 },
    { 0, 0, 0, 0 }
}
Definition at line 250 of file metasound.c.
Referenced by metasound_decode_init().
ff_metasound_decoder
AVCodec ff_metasound_decoder
Initial value:
= {
    .name           = "metasound",
    .long_name      = NULL_IF_CONFIG_SMALL("Voxware MetaSound"),
    .type           = AVMEDIA_TYPE_AUDIO,
    .id             = AV_CODEC_ID_METASOUND,
    .priv_data_size = sizeof(TwinVQContext),
    .init           = metasound_decode_init,
    .close          = ff_twinvq_decode_close,
    .decode         = ff_twinvq_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
    .sample_fmts    = (const enum AVSampleFormat[]) { AV_SAMPLE_FMT_FLTP,
                                                      AV_SAMPLE_FMT_NONE },
}
Definition at line 378 of file metasound.c.