FFmpeg: libavcodec/mjpegenc_common.h File Reference
mjpegenc_common.h File Reference
#include <stdint.h>
#include "avcodec.h"
#include "idctdsp.h"
#include "mpegvideo.h"
#include "put_bits.h"
Functions
void ff_mjpeg_encode_picture_header (AVCodecContext *avctx, PutBitContext *pb, ScanTable *intra_scantable, int pred, uint16_t luma_intra_matrix[64], uint16_t chroma_intra_matrix[64])
void ff_mjpeg_encode_picture_trailer (PutBitContext *pb, int header_bits)
void ff_mjpeg_escape_FF (PutBitContext *pb, int start)
int ff_mjpeg_encode_stuffing (MpegEncContext *s)
void ff_mjpeg_init_hvsample (AVCodecContext *avctx, int hsample[4], int vsample[4])
void ff_mjpeg_encode_dc (PutBitContext *pb, int val, uint8_t *huff_size, uint16_t *huff_code)
Function Documentation
ff_mjpeg_encode_picture_header()
void ff_mjpeg_encode_picture_header (AVCodecContext * avctx, PutBitContext * pb, ScanTable * intra_scantable, int pred, uint16_t luma_intra_matrix[64], uint16_t chroma_intra_matrix[64])
Definition at line 202 of file mjpegenc_common.c.
Referenced by encode_picture(), and ljpeg_encode_frame().
ff_mjpeg_encode_picture_trailer()
void ff_mjpeg_encode_picture_trailer (PutBitContext * pb, int header_bits)
Definition at line 401 of file mjpegenc_common.c.
Referenced by ff_mpv_encode_picture(), and ljpeg_encode_frame().
ff_mjpeg_escape_FF()
void ff_mjpeg_escape_FF (PutBitContext * pb, int start)
Definition at line 316 of file mjpegenc_common.c.
Referenced by ff_mjpeg_encode_stuffing(), and ljpeg_encode_frame().
ff_mjpeg_encode_stuffing()
int ff_mjpeg_encode_stuffing (MpegEncContext * s)
Definition at line 375 of file mjpegenc_common.c.
Referenced by write_slice_end().
ff_mjpeg_init_hvsample()
void ff_mjpeg_init_hvsample (AVCodecContext * avctx, int hsample[4], int vsample[4])
Definition at line 175 of file mjpegenc_common.c.
Referenced by ff_mjpeg_encode_picture_header(), and ljpeg_encode_init().
ff_mjpeg_encode_dc()
void ff_mjpeg_encode_dc (PutBitContext * pb, int val, uint8_t * huff_size, uint16_t * huff_code)
Definition at line 408 of file mjpegenc_common.c.
Referenced by encode_block(), ljpeg_encode_bgr(), and ljpeg_encode_yuv_mb().