FFmpeg: libavcodec/mjpegenc.h File Reference
mjpegenc.h File Reference
MJPEG encoder.
#include <stdint.h>
#include "mjpeg.h"
#include "mpegvideo.h"
#include "put_bits.h"
Data Structures
struct MJpegContext
Functions
static void put_marker (PutBitContext *p, enum JpegMarker code)
int ff_mjpeg_encode_init (MpegEncContext *s)
void ff_mjpeg_encode_close (MpegEncContext *s)
void ff_mjpeg_encode_mb (MpegEncContext *s, int16_t block[12][64])
Detailed Description
MJPEG encoder.
Definition in file mjpegenc.h.
Function Documentation
put_marker()
static void put_marker (PutBitContext * p, enum JpegMarker code) inline static
Definition at line 54 of file mjpegenc.h.
Referenced by encode_picture_ls(), ff_mjpeg_encode_picture_header(), ff_mjpeg_encode_picture_trailer(), ff_mjpeg_encode_stuffing(), jpeg_put_comments(), jpeg_table_header(), and ls_store_lse().
ff_mjpeg_encode_init()
int ff_mjpeg_encode_init (MpegEncContext * s)
Definition at line 71 of file mjpegenc.c.
Referenced by ff_mpv_encode_init(), and put_marker().
ff_mjpeg_encode_close()
void ff_mjpeg_encode_close (MpegEncContext * s)
Definition at line 116 of file mjpegenc.c.
Referenced by ff_mpv_encode_end(), and put_marker().
ff_mjpeg_encode_mb()
void ff_mjpeg_encode_mb (MpegEncContext * s, int16_t block[12][64])
Definition at line 179 of file mjpegenc.c.
Referenced by encode_mb_internal(), and put_marker().