FFmpeg: libavcodec/mjpegdec.c File Reference
mjpegdec.c File Reference
MJPEG decoder.
#include "libavutil/imgutils.h"
#include "libavutil/avassert.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "blockdsp.h"
#include "copy_block.h"
#include "idctdsp.h"
#include "internal.h"
#include "jpegtables.h"
#include "mjpeg.h"
#include "mjpegdec.h"
#include "jpeglsdec.h"
#include "put_bits.h"
#include "tiff.h"
#include "exif.h"
#include "bytestream.h"
Macros
#define REFINE_BIT(j)
#define ZERO_RUN
#define copy_data_segment(skip)
Functions
static int build_vlc (VLC *vlc, const uint8_t *bits_table, const uint8_t *val_table, int nb_codes, int use_static, int is_ac)
static void build_basic_mjpeg_vlc (MJpegDecodeContext *s)
static void parse_avid (MJpegDecodeContext *s, uint8_t *buf, int len)
static void init_idct (AVCodecContext *avctx)
av_cold int ff_mjpeg_decode_init (AVCodecContext *avctx)
int ff_mjpeg_decode_dqt (MJpegDecodeContext *s)
int ff_mjpeg_decode_dht (MJpegDecodeContext *s)
int ff_mjpeg_decode_sof (MJpegDecodeContext *s)
static int mjpeg_decode_dc (MJpegDecodeContext *s, int dc_index)
static int decode_block (MJpegDecodeContext *s, int16_t *block, int component, int dc_index, int ac_index, int16_t *quant_matrix)
static int decode_dc_progressive (MJpegDecodeContext *s, int16_t *block, int component, int dc_index, int16_t *quant_matrix, int Al)
static int decode_block_progressive (MJpegDecodeContext *s, int16_t *block, uint8_t *last_nnz, int ac_index, int16_t *quant_matrix, int ss, int se, int Al, int *EOBRUN)
static int decode_block_refinement (MJpegDecodeContext *s, int16_t *block, uint8_t *last_nnz, int ac_index, int16_t *quant_matrix, int ss, int se, int Al, int *EOBRUN)
static int handle_rstn (MJpegDecodeContext *s, int nb_components)
static int ljpeg_decode_rgb_scan (MJpegDecodeContext *s, int nb_components, int predictor, int point_transform)
static int ljpeg_decode_yuv_scan (MJpegDecodeContext *s, int predictor, int point_transform, int nb_components)
static av_always_inline void mjpeg_copy_block (MJpegDecodeContext *s, uint8_t *dst, const uint8_t *src, int linesize, int lowres)
static void shift_output (MJpegDecodeContext *s, uint8_t *ptr, int linesize)
static int mjpeg_decode_scan (MJpegDecodeContext *s, int nb_components, int Ah, int Al, const uint8_t *mb_bitmask, int mb_bitmask_size, const AVFrame *reference)
static int mjpeg_decode_scan_progressive_ac (MJpegDecodeContext *s, int ss, int se, int Ah, int Al)
static void mjpeg_idct_scan_progressive_ac (MJpegDecodeContext *s)
int ff_mjpeg_decode_sos (MJpegDecodeContext *s, const uint8_t *mb_bitmask, int mb_bitmask_size, const AVFrame *reference)
static int mjpeg_decode_dri (MJpegDecodeContext *s)
static int mjpeg_decode_app (MJpegDecodeContext *s)
static int mjpeg_decode_com (MJpegDecodeContext *s)
static int find_marker (const uint8_t **pbuf_ptr, const uint8_t *buf_end)
int ff_mjpeg_find_marker (MJpegDecodeContext *s, const uint8_t **buf_ptr, const uint8_t *buf_end, const uint8_t **unescaped_buf_ptr, int *unescaped_buf_size)
int ff_mjpeg_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
av_cold int ff_mjpeg_decode_end (AVCodecContext *avctx)
static void decode_flush (AVCodecContext *avctx)
Detailed Description
MJPEG decoder.
Definition in file mjpegdec.c.
Macro Definition Documentation
REFINE_BIT
#define REFINE_BIT (j)
Value:
{                                             \
    UPDATE_CACHE(re, &s->gb);                                       \
    sign = block[j] >> 15;                                          \
    block[j] += SHOW_UBITS(re, &s->gb, 1) *                         \
                ((quant_matrix[i] ^ sign) - sign) << Al;            \
    LAST_SKIP_BITS(re, &s->gb, 1);                                  \
}
Definition at line 823 of file mjpegdec.c.
Referenced by decode_block_refinement().
ZERO_RUN
#define ZERO_RUN
Value:
for (; ; i++) {                                                     \
    if (i > last) {                                                 \
        i += run;                                                   \
        if (i > se) {                                               \
            av_log(s->avctx, AV_LOG_ERROR, "error count: %d\n", i); \
            return -1;                                              \
        }                                                           \
        break;                                                      \
    }                                                               \
    j = s->scantable.permutated[i];                                 \
    if (block[j])                                                   \
        REFINE_BIT(j)                                               \
    else if (run-- == 0)                                            \
        break;                                                      \
}
Definition at line 831 of file mjpegdec.c.
Referenced by decode_block_refinement().
copy_data_segment
#define copy_data_segment (skip)
Value:
do {       \
            ptrdiff_t length = (ptr - src) - (skip);  \
            if (length > 0) {                         \
                memcpy(dst, src, length);             \
                dst += length;                        \
                src = ptr;                            \
            }                                         \
        } while (0)
Referenced by ff_mjpeg_find_marker().
Function Documentation
build_vlc()
static int build_vlc (VLC * vlc, const uint8_t * bits_table, const uint8_t * val_table, int nb_codes, int use_static, int is_ac) static
Definition at line 51 of file mjpegdec.c.
Referenced by build_basic_mjpeg_vlc(), and ff_mjpeg_decode_dht().
build_basic_mjpeg_vlc()
static void build_basic_mjpeg_vlc (MJpegDecodeContext * s) static
Definition at line 74 of file mjpegdec.c.
Referenced by ff_mjpeg_decode_init().
parse_avid()
static void parse_avid (MJpegDecodeContext * s, uint8_t * buf, int len) static
Definition at line 90 of file mjpegdec.c.
Referenced by ff_mjpeg_decode_init(), and mjpeg_decode_com().
init_idct()
static void init_idct (AVCodecContext * avctx) static
Definition at line 101 of file mjpegdec.c.
Referenced by ff_mjpeg_decode_init(), and ff_mjpeg_decode_sof().
ff_mjpeg_decode_init()
av_cold int ff_mjpeg_decode_init (AVCodecContext * avctx)
Definition at line 110 of file mjpegdec.c.
Referenced by decode_flush(), mxpeg_decode_init(), and sp5x_decode_frame().
ff_mjpeg_decode_dqt()
int ff_mjpeg_decode_dqt (MJpegDecodeContext * s)
Definition at line 167 of file mjpegdec.c.
Referenced by ff_mjpeg_decode_frame(), mjpegb_decode_frame(), and mxpeg_decode_frame().
ff_mjpeg_decode_dht()
int ff_mjpeg_decode_dht (MJpegDecodeContext * s)
Definition at line 204 of file mjpegdec.c.
Referenced by ff_mjpeg_decode_frame(), ff_mjpeg_decode_init(), mjpegb_decode_frame(), and mxpeg_decode_frame().
ff_mjpeg_decode_sof()
int ff_mjpeg_decode_sof (MJpegDecodeContext * s)
Definition at line 263 of file mjpegdec.c.
Referenced by ff_mjpeg_decode_frame(), mjpegb_decode_frame(), and mxpeg_decode_frame().
mjpeg_decode_dc()
static int mjpeg_decode_dc (MJpegDecodeContext * s, int dc_index) inline static
Definition at line 666 of file mjpegdec.c.
Referenced by decode_block(), decode_dc_progressive(), ljpeg_decode_rgb_scan(), and ljpeg_decode_yuv_scan().
decode_block()
static int decode_block (MJpegDecodeContext * s, int16_t * block, int component, int dc_index, int ac_index, int16_t * quant_matrix) static
Definition at line 684 of file mjpegdec.c.
Referenced by mjpeg_decode_scan().
decode_dc_progressive()
static int decode_dc_progressive (MJpegDecodeContext * s, int16_t * block, int component, int dc_index, int16_t * quant_matrix, int Al) static
Definition at line 733 of file mjpegdec.c.
Referenced by mjpeg_decode_scan().
decode_block_progressive()
static int decode_block_progressive (MJpegDecodeContext * s, int16_t * block, uint8_t * last_nnz, int ac_index, int16_t * quant_matrix, int ss, int se, int Al, int * EOBRUN) static
Definition at line 751 of file mjpegdec.c.
Referenced by mjpeg_decode_scan_progressive_ac().
decode_block_refinement()
static int decode_block_refinement (MJpegDecodeContext * s, int16_t * block, uint8_t * last_nnz, int ac_index, int16_t * quant_matrix, int ss, int se, int Al, int * EOBRUN) static
Definition at line 849 of file mjpegdec.c.
Referenced by mjpeg_decode_scan_progressive_ac().
handle_rstn()
static int handle_rstn (MJpegDecodeContext * s, int nb_components) static
Definition at line 914 of file mjpegdec.c.
Referenced by mjpeg_decode_scan(), and mjpeg_decode_scan_progressive_ac().
ljpeg_decode_rgb_scan()
static int ljpeg_decode_rgb_scan (MJpegDecodeContext * s, int nb_components, int predictor, int point_transform) static
Definition at line 948 of file mjpegdec.c.
Referenced by ff_mjpeg_decode_sos().
ljpeg_decode_yuv_scan()
static int ljpeg_decode_yuv_scan (MJpegDecodeContext * s, int predictor, int point_transform, int nb_components) static
Definition at line 1070 of file mjpegdec.c.
Referenced by ff_mjpeg_decode_sos().
mjpeg_copy_block()
static av_always_inline void mjpeg_copy_block (MJpegDecodeContext * s, uint8_t * dst, const uint8_t * src, int linesize, int lowres) static
Definition at line 1220 of file mjpegdec.c.
Referenced by mjpeg_decode_scan().
shift_output()
static void shift_output (MJpegDecodeContext * s, uint8_t * ptr, int linesize) static
Definition at line 1236 of file mjpegdec.c.
Referenced by mjpeg_decode_scan(), and mjpeg_idct_scan_progressive_ac().
mjpeg_decode_scan()
static int mjpeg_decode_scan (MJpegDecodeContext * s, int nb_components, int Ah, int Al, const uint8_t * mb_bitmask, int mb_bitmask_size, const AVFrame * reference) static
Definition at line 1251 of file mjpegdec.c.
Referenced by ff_mjpeg_decode_sos().
mjpeg_decode_scan_progressive_ac()
static int mjpeg_decode_scan_progressive_ac (MJpegDecodeContext * s, int ss, int se, int Ah, int Al) static
Definition at line 1372 of file mjpegdec.c.
Referenced by ff_mjpeg_decode_sos().
mjpeg_idct_scan_progressive_ac()
static void mjpeg_idct_scan_progressive_ac (MJpegDecodeContext * s) static
Definition at line 1420 of file mjpegdec.c.
Referenced by ff_mjpeg_decode_frame().
ff_mjpeg_decode_sos()
int ff_mjpeg_decode_sos (MJpegDecodeContext * s, const uint8_t * mb_bitmask, int mb_bitmask_size, const AVFrame * reference)
Definition at line 1455 of file mjpegdec.c.
Referenced by ff_mjpeg_decode_frame(), mjpegb_decode_frame(), and mxpeg_decode_frame().
mjpeg_decode_dri()
static int mjpeg_decode_dri (MJpegDecodeContext * s) static
Definition at line 1615 of file mjpegdec.c.
Referenced by ff_mjpeg_decode_frame().
mjpeg_decode_app()
static int mjpeg_decode_app (MJpegDecodeContext * s) static
Definition at line 1627 of file mjpegdec.c.
Referenced by ff_mjpeg_decode_frame().
mjpeg_decode_com()
static int mjpeg_decode_com (MJpegDecodeContext * s) static
Definition at line 1880 of file mjpegdec.c.
Referenced by ff_mjpeg_decode_frame().
find_marker()
static int find_marker (const uint8_t ** pbuf_ptr, const uint8_t * buf_end) static
Definition at line 1920 of file mjpegdec.c.
Referenced by ff_mjpeg_find_marker().
ff_mjpeg_find_marker()
int ff_mjpeg_find_marker (MJpegDecodeContext * s, const uint8_t ** buf_ptr, const uint8_t * buf_end, const uint8_t ** unescaped_buf_ptr, int * unescaped_buf_size)
Definition at line 1945 of file mjpegdec.c.
Referenced by ff_mjpeg_decode_frame(), and mxpeg_decode_frame().
ff_mjpeg_decode_frame()
int ff_mjpeg_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt)
Definition at line 2065 of file mjpegdec.c.
Referenced by decode_flush(), and sp5x_decode_frame().
ff_mjpeg_decode_end()
av_cold int ff_mjpeg_decode_end (AVCodecContext * avctx)
Definition at line 2480 of file mjpegdec.c.
Referenced by decode_flush(), mxpeg_decode_end(), and sp5x_decode_frame().
decode_flush()
static void decode_flush (AVCodecContext * avctx) static
Definition at line 2512 of file mjpegdec.c.