FFmpeg: libavcodec/mjpegdec.h File Reference
mjpegdec.h File Reference
MJPEG decoder.
#include "libavutil/log.h"
#include "libavutil/pixdesc.h"
#include "libavutil/stereo3d.h"
#include "avcodec.h"
#include "blockdsp.h"
#include "get_bits.h"
#include "hpeldsp.h"
#include "idctdsp.h"
Data Structures
struct MJpegDecodeContext
Macros
#define MAX_COMPONENTS 4
Functions
int ff_mjpeg_decode_init (AVCodecContext *avctx)
int ff_mjpeg_decode_end (AVCodecContext *avctx)
int ff_mjpeg_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
int ff_mjpeg_decode_dqt (MJpegDecodeContext *s)
int ff_mjpeg_decode_dht (MJpegDecodeContext *s)
int ff_mjpeg_decode_sof (MJpegDecodeContext *s)
int ff_mjpeg_decode_sos (MJpegDecodeContext *s, const uint8_t *mb_bitmask, int mb_bitmask_size, const AVFrame *reference)
int ff_mjpeg_find_marker (MJpegDecodeContext *s, const uint8_t **buf_ptr, const uint8_t *buf_end, const uint8_t **unescaped_buf_ptr, int *unescaped_buf_size)
Detailed Description
MJPEG decoder.
Definition in file mjpegdec.h.
Macro Definition Documentation
MAX_COMPONENTS
#define MAX_COMPONENTS 4
Definition at line 42 of file mjpegdec.h.
Referenced by ff_jpegls_decode_lse(), ff_mjpeg_decode_end(), ff_mjpeg_decode_sof(), ff_mjpeg_decode_sos(), mjpeg_decode_scan(), and mxpeg_check_dimensions().
Function Documentation
ff_mjpeg_decode_init()
int ff_mjpeg_decode_init (AVCodecContext * avctx)
Definition at line 110 of file mjpegdec.c.
Referenced by decode_flush(), mxpeg_decode_init(), and sp5x_decode_frame().
ff_mjpeg_decode_end()
int ff_mjpeg_decode_end (AVCodecContext * avctx)
Definition at line 2480 of file mjpegdec.c.
Referenced by decode_flush(), mxpeg_decode_end(), and sp5x_decode_frame().
ff_mjpeg_decode_frame()
int ff_mjpeg_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt)
Definition at line 2065 of file mjpegdec.c.
Referenced by decode_flush(), and sp5x_decode_frame().
ff_mjpeg_decode_dqt()
int ff_mjpeg_decode_dqt (MJpegDecodeContext * s)
Definition at line 167 of file mjpegdec.c.
Referenced by ff_mjpeg_decode_frame(), mjpegb_decode_frame(), and mxpeg_decode_frame().
ff_mjpeg_decode_dht()
int ff_mjpeg_decode_dht (MJpegDecodeContext * s)
Definition at line 204 of file mjpegdec.c.
Referenced by ff_mjpeg_decode_frame(), ff_mjpeg_decode_init(), mjpegb_decode_frame(), and mxpeg_decode_frame().
ff_mjpeg_decode_sof()
int ff_mjpeg_decode_sof (MJpegDecodeContext * s)
Definition at line 263 of file mjpegdec.c.
Referenced by ff_mjpeg_decode_frame(), mjpegb_decode_frame(), and mxpeg_decode_frame().
ff_mjpeg_decode_sos()
int ff_mjpeg_decode_sos (MJpegDecodeContext * s, const uint8_t * mb_bitmask, int mb_bitmask_size, const AVFrame * reference)
Definition at line 1455 of file mjpegdec.c.
Referenced by ff_mjpeg_decode_frame(), mjpegb_decode_frame(), and mxpeg_decode_frame().
ff_mjpeg_find_marker()
int ff_mjpeg_find_marker (MJpegDecodeContext * s, const uint8_t ** buf_ptr, const uint8_t * buf_end, const uint8_t ** unescaped_buf_ptr, int * unescaped_buf_size)
Definition at line 1945 of file mjpegdec.c.
Referenced by ff_mjpeg_decode_frame(), and mxpeg_decode_frame().