FFmpeg: libavcodec/mlp_parser.h File Reference
mlp_parser.h File Reference
MLP parser prototypes.
#include "get_bits.h"
Data Structures
struct MLPHeaderInfo
Functions
int ff_mlp_read_major_sync (void *log, MLPHeaderInfo *mh, GetBitContext *gb)
Read a major sync info header - contains high level information about the stream - sample rate, channel arrangement etc.
uint64_t ff_truehd_layout (int chanmap)
Variables
const uint64_t ff_mlp_layout [32]
Detailed Description
MLP parser prototypes.
Definition in file mlp_parser.h.
Function Documentation
ff_mlp_read_major_sync()
int ff_mlp_read_major_sync (void * log, MLPHeaderInfo * mh, GetBitContext * gb)
Read a major sync info header - contains high level information about the stream - sample rate, channel arrangement etc.
Most of this information is not actually necessary for decoding, only for playback. gb must be a freshly initialized GetBitContext with no bits read.
Definition at line 145 of file mlp_parser.c.
Referenced by mlp_parse(), and read_major_sync().
ff_truehd_layout()
uint64_t ff_truehd_layout (int chanmap)
Definition at line 111 of file mlp_parser.c.
Referenced by ff_mlp_read_major_sync().
Variable Documentation
ff_mlp_layout
const uint64_t ff_mlp_layout[32]
Definition at line 47 of file mlp_parser.c.
Referenced by ff_mlp_read_major_sync().