FFmpeg: libavcodec/arm/mlpdsp_init_arm.c File Reference
mlpdsp_init_arm.c File Reference
#include <stdint.h>
#include "libavutil/arm/cpu.h"
#include "libavutil/attributes.h"
#include "libavcodec/mlpdsp.h"
Macros
#define DECLARE_PACK(order, channels, shift) int32_t ff_mlp_pack_output_##order##order_##channels##ch_##shift##shift_armv6(int32_t, uint16_t, int32_t (*)[], void *, uint8_t*, int8_t *, uint8_t, int);
#define ENUMERATE_PACK(order, channels, shift) ff_mlp_pack_output_##order##order_##channels##ch_##shift##shift_armv6,
#define PACK_CHANNELS(macro, order, channels)
#define PACK_ORDER(macro, order)
#define PACK_ALL(macro)
#define ff_mlp_pack_output_outoforder_2ch_mixedshift_armv6 0
#define ff_mlp_pack_output_outoforder_6ch_mixedshift_armv6 0
#define ff_mlp_pack_output_outoforder_8ch_mixedshift_armv6 0
Functions
void ff_mlp_filter_channel_arm (int32_t *state, const int32_t *coeff, int firorder, int iirorder, unsigned int filter_shift, int32_t mask, int blocksize, int32_t *sample_buffer)
void ff_mlp_rematrix_channel_arm (int32_t *samples, const int32_t *coeffs, const uint8_t *bypassed_lsbs, const int8_t *noise_buffer, int index, unsigned int dest_ch, uint16_t blockpos, unsigned int maxchan, int matrix_noise_shift, int access_unit_size_pow2, int32_t mask)
av_cold void ff_mlpdsp_init_arm (MLPDSPContext *c)
Variables
static int32_t(*)(int32_t, uint16_t, int32_t(*)[], void *, uint8_t *, int8_t *, uint8_t, int) mlp_select_pack_output_armv6 (uint8_t *ch_assign, int8_t *output_shift, uint8_t max_matrix_channel, int is32)
Macro Definition Documentation
DECLARE_PACK
#define DECLARE_PACK (order, channels, shift) int32_t ff_mlp_pack_output_##order##order_##channels##ch_##shift##shift_armv6(int32_t, uint16_t, int32_t (*)[], void *, uint8_t*, int8_t *, uint8_t, int);
Definition at line 44 of file mlpdsp_init_arm.c.
ENUMERATE_PACK
#define ENUMERATE_PACK (order, channels, shift) ff_mlp_pack_output_##order##order_##channels##ch_##shift##shift_armv6,
Definition at line 46 of file mlpdsp_init_arm.c.
PACK_CHANNELS
#define PACK_CHANNELS (macro, order, channels)
Value:
macro(order,channels,0) \
        macro(order,channels,1) \
        macro(order,channels,2) \
        macro(order,channels,3) \
        macro(order,channels,4) \
        macro(order,channels,5) \
        macro(order,channels,mixed)
Definition at line 48 of file mlpdsp_init_arm.c.
PACK_ORDER
#define PACK_ORDER (macro, order)
Value:
PACK_CHANNELS(macro,order,2) \
        PACK_CHANNELS(macro,order,6) \
        PACK_CHANNELS(macro,order,8)
Definition at line 56 of file mlpdsp_init_arm.c.
PACK_ALL
#define PACK_ALL (macro)
Value:
PACK_ORDER(macro,outof) \
        PACK_ORDER(macro,in)
Definition at line 60 of file mlpdsp_init_arm.c.
ff_mlp_pack_output_outoforder_2ch_mixedshift_armv6
#define ff_mlp_pack_output_outoforder_2ch_mixedshift_armv6 0
Definition at line 65 of file mlpdsp_init_arm.c.
ff_mlp_pack_output_outoforder_6ch_mixedshift_armv6
#define ff_mlp_pack_output_outoforder_6ch_mixedshift_armv6 0
Definition at line 66 of file mlpdsp_init_arm.c.
ff_mlp_pack_output_outoforder_8ch_mixedshift_armv6
#define ff_mlp_pack_output_outoforder_8ch_mixedshift_armv6 0
Definition at line 67 of file mlpdsp_init_arm.c.
Function Documentation
ff_mlp_filter_channel_arm()
void ff_mlp_filter_channel_arm (int32_t * state, const int32_t * coeff, int firorder, int iirorder, unsigned int filter_shift, int32_t mask, int blocksize, int32_t * sample_buffer)
Referenced by ff_mlpdsp_init_arm().
ff_mlp_rematrix_channel_arm()
void ff_mlp_rematrix_channel_arm (int32_t * samples, const int32_t * coeffs, const uint8_t * bypassed_lsbs, const int8_t * noise_buffer, int index, unsigned int dest_ch, uint16_t blockpos, unsigned int maxchan, int matrix_noise_shift, int access_unit_size_pow2, int32_t mask)
Referenced by ff_mlpdsp_init_arm().
ff_mlpdsp_init_arm()
av_cold void ff_mlpdsp_init_arm (MLPDSPContext * c)
Definition at line 136 of file mlpdsp_init_arm.c.
Referenced by ff_mlpdsp_init().
Variable Documentation
mlp_select_pack_output_armv6
int32_t(*)(int32_t, uint16_t, int32_t (*)[], void *, uint8_t*, int8_t *, uint8_t, int) mlp_select_pack_output_armv6(uint8_t *ch_assign, int8_t *output_shift, uint8_t max_matrix_channel, int is32) static
Definition at line 89 of file mlpdsp_init_arm.c.
Referenced by ff_mlpdsp_init_arm().