FFmpeg: libavcodec/mlpdsp.c File Reference
mlpdsp.c File Reference
#include "config.h"
#include "libavutil/attributes.h"
#include "mlpdsp.h"
#include "mlp.h"
Functions
static void mlp_filter_channel (int32_t *state, const int32_t *coeff, int firorder, int iirorder, unsigned int filter_shift, int32_t mask, int blocksize, int32_t *sample_buffer)
void ff_mlp_rematrix_channel (int32_t *samples, const int32_t *coeffs, const uint8_t *bypassed_lsbs, const int8_t *noise_buffer, int index, unsigned int dest_ch, uint16_t blockpos, unsigned int maxchan, int matrix_noise_shift, int access_unit_size_pow2, int32_t mask)
int32_t ff_mlp_pack_output (int32_t lossless_check_data, uint16_t blockpos, int32_t(*sample_buffer)[MAX_CHANNELS], void *data, uint8_t *ch_assign, int8_t *output_shift, uint8_t max_matrix_channel, int is32)
av_cold void ff_mlpdsp_init (MLPDSPContext *c)
Variables
static int32_t(*)(int32_t, uint16_t, int32_t(*)[], void *, uint8_t *, int8_t *, uint8_t, int) mlp_select_pack_output (uint8_t *ch_assign, int8_t *output_shift, uint8_t max_matrix_channel, int is32)
Function Documentation
mlp_filter_channel()
static void mlp_filter_channel (int32_t * state, const int32_t * coeff, int firorder, int iirorder, unsigned int filter_shift, int32_t mask, int blocksize, int32_t * sample_buffer) static
Definition at line 27 of file mlpdsp.c.
Referenced by ff_mlpdsp_init().
ff_mlp_rematrix_channel()
void ff_mlp_rematrix_channel (int32_t * samples, const int32_t * coeffs, const uint8_t * bypassed_lsbs, const int8_t * noise_buffer, int index, unsigned int dest_ch, uint16_t blockpos, unsigned int maxchan, int matrix_noise_shift, int access_unit_size_pow2, int32_t mask)
Definition at line 60 of file mlpdsp.c.
Referenced by ff_mlpdsp_init().
ff_mlp_pack_output()
int32_t ff_mlp_pack_output (int32_t lossless_check_data, uint16_t blockpos, int32_t(*) sample_buffer[MAX_CHANNELS], void * data, uint8_t * ch_assign, int8_t * output_shift, uint8_t max_matrix_channel, int is32)
Definition at line 100 of file mlpdsp.c.
Referenced by ff_mlpdsp_init().
ff_mlpdsp_init()
av_cold void ff_mlpdsp_init (MLPDSPContext * c)
Definition at line 128 of file mlpdsp.c.
Referenced by mlp_decode_init().
Variable Documentation
mlp_select_pack_output
int32_t(*)(int32_t, uint16_t, int32_t (*)[], void *, uint8_t*, int8_t *, uint8_t, int) mlp_select_pack_output(uint8_t *ch_assign, int8_t *output_shift, uint8_t max_matrix_channel, int is32) static
Definition at line 92 of file mlpdsp.c.
Referenced by ff_mlpdsp_init().