FFmpeg: libavcodec/mlpdsp.h File Reference
mlpdsp.h File Reference
#include <stdint.h>
#include "mlp.h"
Data Structures
struct MLPDSPContext
Functions
void ff_mlp_rematrix_channel (int32_t *samples, const int32_t *coeffs, const uint8_t *bypassed_lsbs, const int8_t *noise_buffer, int index, unsigned int dest_ch, uint16_t blockpos, unsigned int maxchan, int matrix_noise_shift, int access_unit_size_pow2, int32_t mask)
int32_t ff_mlp_pack_output (int32_t lossless_check_data, uint16_t blockpos, int32_t(*sample_buffer)[MAX_CHANNELS], void *data, uint8_t *ch_assign, int8_t *output_shift, uint8_t max_matrix_channel, int is32)
void ff_mlpdsp_init (MLPDSPContext *c)
void ff_mlpdsp_init_arm (MLPDSPContext *c)
void ff_mlpdsp_init_x86 (MLPDSPContext *c)
Function Documentation
ff_mlp_rematrix_channel()
void ff_mlp_rematrix_channel (int32_t * samples, const int32_t * coeffs, const uint8_t * bypassed_lsbs, const int8_t * noise_buffer, int index, unsigned int dest_ch, uint16_t blockpos, unsigned int maxchan, int matrix_noise_shift, int access_unit_size_pow2, int32_t mask)
Definition at line 60 of file mlpdsp.c.
Referenced by ff_mlpdsp_init().
ff_mlp_pack_output()
int32_t ff_mlp_pack_output (int32_t lossless_check_data, uint16_t blockpos, int32_t(*) sample_buffer[MAX_CHANNELS], void * data, uint8_t * ch_assign, int8_t * output_shift, uint8_t max_matrix_channel, int is32)
Definition at line 100 of file mlpdsp.c.
Referenced by ff_mlpdsp_init().
ff_mlpdsp_init()
void ff_mlpdsp_init (MLPDSPContext * c)
Definition at line 128 of file mlpdsp.c.
Referenced by mlp_decode_init().
ff_mlpdsp_init_arm()
void ff_mlpdsp_init_arm (MLPDSPContext * c)
Definition at line 136 of file mlpdsp_init_arm.c.
Referenced by ff_mlpdsp_init().
ff_mlpdsp_init_x86()
void ff_mlpdsp_init_x86 (MLPDSPContext * c)
Definition at line 193 of file mlpdsp_init.c.
Referenced by ff_mlpdsp_init().