FFmpeg: libavcodec/mlz.c File Reference
mlz.c File Reference
#include "mlz.h"
Functions
av_cold void ff_mlz_init_dict (void *context, MLZ *mlz)
Initialize the dictionary.
av_cold void ff_mlz_flush_dict (MLZ *mlz)
Flush the dictionary.
static void set_new_entry_dict (MLZDict *dict, int string_code, int parent_code, int char_code)
static int decode_string (MLZ *mlz, unsigned char *buff, int string_code, int *first_char_code, unsigned long bufsize)
static int input_code (GetBitContext *gb, int len)
int ff_mlz_decompression (MLZ *mlz, GetBitContext *gb, int size, unsigned char *buff)
Run mlz decompression on the next size bits and the output will be stored in buff.
Function Documentation
ff_mlz_init_dict()
av_cold void ff_mlz_init_dict (void * context, MLZ * mlz)
Initialize the dictionary.
Definition at line 23 of file mlz.c.
Referenced by decode_init().
ff_mlz_flush_dict()
av_cold void ff_mlz_flush_dict (MLZ * mlz)
Flush the dictionary.
Definition at line 35 of file mlz.c.
Referenced by decode_init(), ff_mlz_decompression(), and read_diff_float_data().
set_new_entry_dict()
static void set_new_entry_dict (MLZDict * dict, int string_code, int parent_code, int char_code) static
Definition at line 50 of file mlz.c.
Referenced by ff_mlz_decompression().
decode_string()
static int decode_string (MLZ * mlz, unsigned char * buff, int string_code, int * first_char_code, unsigned long bufsize) static
Definition at line 61 of file mlz.c.
Referenced by ff_mlz_decompression().
input_code()
static int input_code (GetBitContext * gb, int len) static
Definition at line 114 of file mlz.c.
Referenced by ff_mlz_decompression().
ff_mlz_decompression()
int ff_mlz_decompression (MLZ * mlz, GetBitContext * gb, int size, unsigned char * buff)
Run mlz decompression on the next size bits and the output will be stored in buff.
Definition at line 123 of file mlz.c.
Referenced by read_diff_float_data().