FFmpeg: libavcodec/mmaldec.c File Reference
mmaldec.c File Reference
MMAL Video Decoder.
#include <bcm_host.h>
#include <interface/mmal/mmal.h>
#include <interface/mmal/mmal_parameters_video.h>
#include <interface/mmal/util/mmal_util.h>
#include <interface/mmal/util/mmal_util_params.h>
#include <interface/mmal/util/mmal_default_components.h>
#include <interface/mmal/vc/mmal_vc_api.h>
#include "avcodec.h"
#include "internal.h"
#include "libavutil/atomic.h"
#include "libavutil/avassert.h"
#include "libavutil/buffer.h"
#include "libavutil/common.h"
#include "libavutil/imgutils.h"
#include "libavutil/opt.h"
#include "libavutil/log.h"
Data Structures
struct FFBufferEntry
struct FFPoolRef
struct FFBufferRef
struct MMALDecodeContext
Macros
#define MAX_DELAYED_FRAMES 16
#define FFMMAL_DEC_CLASS(NAME)
#define FFMMAL_DEC(NAME, ID)
Functions
static void ffmmal_poolref_unref (FFPoolRef *ref)
static void ffmmal_release_frame (void *opaque, uint8_t *data)
static int ffmmal_set_ref (AVFrame *frame, FFPoolRef *pool, MMAL_BUFFER_HEADER_T *buffer)
static void ffmmal_stop_decoder (AVCodecContext *avctx)
static av_cold int ffmmal_close_decoder (AVCodecContext *avctx)
static void input_callback (MMAL_PORT_T *port, MMAL_BUFFER_HEADER_T *buffer)
static void output_callback (MMAL_PORT_T *port, MMAL_BUFFER_HEADER_T *buffer)
static void control_port_cb (MMAL_PORT_T *port, MMAL_BUFFER_HEADER_T *buffer)
static int ffmmal_fill_output_port (AVCodecContext *avctx)
static enum AVColorSpace ffmmal_csp_to_av_csp (MMAL_FOURCC_T fourcc)
static int ffmal_update_format (AVCodecContext *avctx)
static av_cold int ffmmal_init_decoder (AVCodecContext *avctx)
static void ffmmal_flush (AVCodecContext *avctx)
static int ffmmal_add_packet (AVCodecContext *avctx, AVPacket *avpkt, int is_extradata)
static int ffmmal_fill_input_port (AVCodecContext *avctx)
static int ffmal_copy_frame (AVCodecContext *avctx, AVFrame *frame, MMAL_BUFFER_HEADER_T *buffer)
static int ffmmal_read_frame (AVCodecContext *avctx, AVFrame *frame, int *got_frame)
static int ffmmal_decode (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
Variables
AVHWAccel ff_h264_mmal_hwaccel
AVHWAccel ff_mpeg2_mmal_hwaccel
AVHWAccel ff_mpeg4_mmal_hwaccel
AVHWAccel ff_vc1_mmal_hwaccel
static const AVOption options []
Detailed Description
MMAL Video Decoder.
Definition in file mmaldec.c.
Macro Definition Documentation
MAX_DELAYED_FRAMES
#define MAX_DELAYED_FRAMES 16
Definition at line 97 of file mmaldec.c.
Referenced by ffmmal_read_frame().
FFMMAL_DEC_CLASS
#define FFMMAL_DEC_CLASS (NAME)
Value:
static const AVClass ffmmal_##NAME##_dec_class = { \
        .class_name = "mmal_" #NAME "_dec", \
        .option     = options, \
        .version    = LIBAVUTIL_VERSION_INT, \
    };
Definition at line 846 of file mmaldec.c.
FFMMAL_DEC
#define FFMMAL_DEC (NAME, ID)
Value:
FFMMAL_DEC_CLASS(NAME) \
    AVCodec ff_##NAME##_mmal_decoder = { \
        .name           = #NAME "_mmal", \
        .long_name      = NULL_IF_CONFIG_SMALL(#NAME " (mmal)"), \
        .type           = AVMEDIA_TYPE_VIDEO, \
        .id             = ID, \
        .priv_data_size = sizeof(MMALDecodeContext), \
        .init           = ffmmal_init_decoder, \
        .close          = ffmmal_close_decoder, \
        .decode         = ffmmal_decode, \
        .flush          = ffmmal_flush, \
        .priv_class     = &ffmmal_##NAME##_dec_class, \
        .capabilities   = AV_CODEC_CAP_DELAY, \
        .caps_internal  = FF_CODEC_CAP_SETS_PKT_DTS, \
        .pix_fmts       = (const enum AVPixelFormat[]) { AV_PIX_FMT_MMAL, \
                                                         AV_PIX_FMT_YUV420P, \
                                                         AV_PIX_FMT_NONE}, \
    };
Definition at line 853 of file mmaldec.c.
Function Documentation
ffmmal_poolref_unref()
static void ffmmal_poolref_unref (FFPoolRef * ref) static
Definition at line 99 of file mmaldec.c.
Referenced by ffmal_update_format(), ffmmal_close_decoder(), and ffmmal_release_frame().
ffmmal_release_frame()
static void ffmmal_release_frame (void * opaque, uint8_t * data) static
Definition at line 107 of file mmaldec.c.
Referenced by ffmmal_set_ref().
ffmmal_set_ref()
static int ffmmal_set_ref (AVFrame * frame, FFPoolRef * pool, MMAL_BUFFER_HEADER_T * buffer) static
Definition at line 119 of file mmaldec.c.
Referenced by ffmal_copy_frame().
ffmmal_stop_decoder()
static void ffmmal_stop_decoder (AVCodecContext * avctx) static
Definition at line 145 of file mmaldec.c.
Referenced by ffmmal_close_decoder(), and ffmmal_flush().
ffmmal_close_decoder()
static av_cold int ffmmal_close_decoder (AVCodecContext * avctx) static
Definition at line 180 of file mmaldec.c.
Referenced by ffmmal_init_decoder().
input_callback()
static void input_callback (MMAL_PORT_T * port, MMAL_BUFFER_HEADER_T * buffer) static
Definition at line 198 of file mmaldec.c.
Referenced by ffmmal_flush(), and ffmmal_init_decoder().
output_callback()
static void output_callback (MMAL_PORT_T * port, MMAL_BUFFER_HEADER_T * buffer) static
Definition at line 213 of file mmaldec.c.
Referenced by ffmmal_flush(), ffmmal_init_decoder(), and ffmmal_read_frame().
control_port_cb()
static void control_port_cb (MMAL_PORT_T * port, MMAL_BUFFER_HEADER_T * buffer) static
Definition at line 221 of file mmaldec.c.
Referenced by ffmmal_flush(), and ffmmal_init_decoder().
ffmmal_fill_output_port()
static int ffmmal_fill_output_port (AVCodecContext * avctx) static
Definition at line 239 of file mmaldec.c.
Referenced by ffmmal_decode(), and ffmmal_read_frame().
ffmmal_csp_to_av_csp()
static enum AVColorSpace ffmmal_csp_to_av_csp (MMAL_FOURCC_T fourcc) static
Definition at line 259 of file mmaldec.c.
Referenced by ffmal_update_format().
ffmal_update_format()
static int ffmal_update_format (AVCodecContext * avctx) static
Definition at line 272 of file mmaldec.c.
Referenced by ffmmal_init_decoder(), and ffmmal_read_frame().
ffmmal_init_decoder()
static av_cold int ffmmal_init_decoder (AVCodecContext * avctx) static
Definition at line 348 of file mmaldec.c.
ffmmal_flush()
static void ffmmal_flush (AVCodecContext * avctx) static
Definition at line 452 of file mmaldec.c.
ffmmal_add_packet()
static int ffmmal_add_packet (AVCodecContext * avctx, AVPacket * avpkt, int is_extradata) static
Definition at line 479 of file mmaldec.c.
Referenced by ffmmal_decode().
ffmmal_fill_input_port()
static int ffmmal_fill_input_port (AVCodecContext * avctx) static
Definition at line 576 of file mmaldec.c.
Referenced by ffmmal_decode(), and ffmmal_read_frame().
ffmal_copy_frame()
static int ffmal_copy_frame (AVCodecContext * avctx, AVFrame * frame, MMAL_BUFFER_HEADER_T * buffer) static
Definition at line 623 of file mmaldec.c.
Referenced by ffmmal_read_frame().
ffmmal_read_frame()
static int ffmmal_read_frame (AVCodecContext * avctx, AVFrame * frame, int * got_frame) static
Definition at line 670 of file mmaldec.c.
Referenced by ffmmal_decode().
ffmmal_decode()
static int ffmmal_decode (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 771 of file mmaldec.c.
Variable Documentation
ff_h264_mmal_hwaccel
AVHWAccel ff_h264_mmal_hwaccel
Initial value:
= {
    .name       = "h264_mmal",
    .type       = AVMEDIA_TYPE_VIDEO,
    .id         = AV_CODEC_ID_H264,
    .pix_fmt    = AV_PIX_FMT_MMAL,
}
Definition at line 812 of file mmaldec.c.
ff_mpeg2_mmal_hwaccel
AVHWAccel ff_mpeg2_mmal_hwaccel
Initial value:
= {
    .name       = "mpeg2_mmal",
    .type       = AVMEDIA_TYPE_VIDEO,
    .id         = AV_CODEC_ID_MPEG2VIDEO,
    .pix_fmt    = AV_PIX_FMT_MMAL,
}
Definition at line 819 of file mmaldec.c.
ff_mpeg4_mmal_hwaccel
AVHWAccel ff_mpeg4_mmal_hwaccel
Initial value:
= {
    .name       = "mpeg4_mmal",
    .type       = AVMEDIA_TYPE_VIDEO,
    .id         = AV_CODEC_ID_MPEG4,
    .pix_fmt    = AV_PIX_FMT_MMAL,
}
Definition at line 826 of file mmaldec.c.
ff_vc1_mmal_hwaccel
AVHWAccel ff_vc1_mmal_hwaccel
Initial value:
= {
    .name       = "vc1_mmal",
    .type       = AVMEDIA_TYPE_VIDEO,
    .id         = AV_CODEC_ID_VC1,
    .pix_fmt    = AV_PIX_FMT_MMAL,
}
Definition at line 833 of file mmaldec.c.
options
const AVOption options[] static
Initial value:
={
    {"extra_buffers", "extra buffers", 0x42, AV_OPT_TYPE_INT, {.i64 = 10}, 0, 256, 0},
    {"extra_decoder_buffers", "extra MMAL internal buffered frames", 0x42, AV_OPT_TYPE_INT, {.i64 = 10}, 0, 256, 0},
    {NULL}
}
Definition at line 840 of file mmaldec.c.