FFmpeg: libavformat/mmf.c File Reference
mmf.c File Reference
#include "libavutil/channel_layout.h"
#include "avformat.h"
#include "avio_internal.h"
#include "internal.h"
#include "pcm.h"
#include "rawenc.h"
#include "riff.h"
Data Structures
struct MMFContext
Macros
#define MAX_SIZE 4096
Functions
static int mmf_rate (int code)
static int mmf_probe (AVProbeData *p)
static int mmf_read_header (AVFormatContext *s)
static int mmf_read_packet (AVFormatContext *s, AVPacket *pkt)
Variables
static const int mmf_rates [] = { 4000, 8000, 11025, 22050, 44100 }
Macro Definition Documentation
MAX_SIZE
#define MAX_SIZE 4096
Definition at line 279 of file mmf.c.
Referenced by mmf_read_packet().
Function Documentation
mmf_rate()
static int mmf_rate (int code) static
Definition at line 38 of file mmf.c.
Referenced by mmf_read_header().
mmf_probe()
static int mmf_probe (AVProbeData * p) static
Definition at line 183 of file mmf.c.
Referenced by mmf_read_packet().
mmf_read_header()
static int mmf_read_header (AVFormatContext * s) static
Definition at line 196 of file mmf.c.
Referenced by mmf_read_packet().
mmf_read_packet()
static int mmf_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 281 of file mmf.c.
Variable Documentation
mmf_rates
const int mmf_rates[] = { 4000, 8000, 11025, 22050, 44100 } static
Definition at line 36 of file mmf.c.
Referenced by mmf_rate().