FFmpeg: libavformat/mms.h File Reference
mms.h File Reference
#include "url.h"
Data Structures
struct MMSStream
struct MMSContext
Functions
int ff_mms_asf_header_parser (MMSContext *mms)
int ff_mms_read_data (MMSContext *mms, uint8_t *buf, const int size)
int ff_mms_read_header (MMSContext *mms, uint8_t *buf, const int size)
Function Documentation
ff_mms_asf_header_parser()
int ff_mms_asf_header_parser (MMSContext * mms)
Definition at line 54 of file mms.c.
Referenced by get_http_header_data(), and mms_open().
ff_mms_read_data()
int ff_mms_read_data (MMSContext * mms, uint8_t * buf, const int size)
Definition at line 44 of file mms.c.
Referenced by mms_read(), and mmsh_read().
ff_mms_read_header()
int ff_mms_read_header (MMSContext * mms, uint8_t * buf, const int size)
Definition at line 29 of file mms.c.
Referenced by mms_read(), and mmsh_read().