FFmpeg: libavfilter/motion_estimation.h File Reference
motion_estimation.h File Reference
#include "libavutil/avutil.h"
Data Structures
struct AVMotionEstPredictor
struct AVMotionEstContext
Macros
#define AV_ME_METHOD_ESA 1
Copyright (c) 2016 Davinder Singh (DSM_) <ds.mudhar<.com>
#define AV_ME_METHOD_TSS 2
#define AV_ME_METHOD_TDLS 3
#define AV_ME_METHOD_NTSS 4
#define AV_ME_METHOD_FSS 5
#define AV_ME_METHOD_DS 6
#define AV_ME_METHOD_HEXBS 7
#define AV_ME_METHOD_EPZS 8
#define AV_ME_METHOD_UMH 9
Functions
void ff_me_init_context (AVMotionEstContext *me_ctx, int mb_size, int search_param, int width, int height, int x_min, int x_max, int y_min, int y_max)
uint64_t ff_me_cmp_sad (AVMotionEstContext *me_ctx, int x_mb, int y_mb, int x_mv, int y_mv)
uint64_t ff_me_search_esa (AVMotionEstContext *me_ctx, int x_mb, int y_mb, int *mv)
uint64_t ff_me_search_tss (AVMotionEstContext *me_ctx, int x_mb, int y_mb, int *mv)
uint64_t ff_me_search_tdls (AVMotionEstContext *me_ctx, int x_mb, int y_mb, int *mv)
uint64_t ff_me_search_ntss (AVMotionEstContext *me_ctx, int x_mb, int y_mb, int *mv)
uint64_t ff_me_search_fss (AVMotionEstContext *me_ctx, int x_mb, int y_mb, int *mv)
uint64_t ff_me_search_ds (AVMotionEstContext *me_ctx, int x_mb, int y_mb, int *mv)
uint64_t ff_me_search_hexbs (AVMotionEstContext *me_ctx, int x_mb, int y_mb, int *mv)
uint64_t ff_me_search_epzs (AVMotionEstContext *me_ctx, int x_mb, int y_mb, int *mv)
uint64_t ff_me_search_umh (AVMotionEstContext *me_ctx, int x_mb, int y_mb, int *mv)
Macro Definition Documentation
AV_ME_METHOD_ESA
#define AV_ME_METHOD_ESA 1
Copyright (c) 2016 Davinder Singh (DSM_) <ds.mudhar<.com>
This file is part of FFmpeg.
FFmpeg is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
FFmpeg is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with FFmpeg; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
Definition at line 26 of file motion_estimation.h.
Referenced by filter_frame(), and search_mv().
AV_ME_METHOD_TSS
#define AV_ME_METHOD_TSS 2
Definition at line 27 of file motion_estimation.h.
Referenced by filter_frame(), and search_mv().
AV_ME_METHOD_TDLS
#define AV_ME_METHOD_TDLS 3
Definition at line 28 of file motion_estimation.h.
Referenced by filter_frame(), and search_mv().
AV_ME_METHOD_NTSS
#define AV_ME_METHOD_NTSS 4
Definition at line 29 of file motion_estimation.h.
Referenced by filter_frame(), and search_mv().
AV_ME_METHOD_FSS
#define AV_ME_METHOD_FSS 5
Definition at line 30 of file motion_estimation.h.
Referenced by filter_frame(), and search_mv().
AV_ME_METHOD_DS
#define AV_ME_METHOD_DS 6
Definition at line 31 of file motion_estimation.h.
Referenced by filter_frame(), and search_mv().
AV_ME_METHOD_HEXBS
#define AV_ME_METHOD_HEXBS 7
Definition at line 32 of file motion_estimation.h.
Referenced by filter_frame(), and search_mv().
AV_ME_METHOD_EPZS
#define AV_ME_METHOD_EPZS 8
Definition at line 33 of file motion_estimation.h.
Referenced by config_input(), filter_frame(), inject_frame(), and search_mv().
AV_ME_METHOD_UMH
#define AV_ME_METHOD_UMH 9
Definition at line 34 of file motion_estimation.h.
Referenced by filter_frame(), and search_mv().
Function Documentation
ff_me_init_context()
void ff_me_init_context (AVMotionEstContext * me_ctx, int mb_size, int search_param, int width, int height, int x_min, int x_max, int y_min, int y_max)
Definition at line 45 of file motion_estimation.c.
Referenced by config_input().
ff_me_cmp_sad()
uint64_t ff_me_cmp_sad (AVMotionEstContext * me_ctx, int x_mb, int y_mb, int x_mv, int y_mv)
Definition at line 59 of file motion_estimation.c.
Referenced by ff_me_init_context().
ff_me_search_esa()
uint64_t ff_me_search_esa (AVMotionEstContext * me_ctx, int x_mb, int y_mb, int * mv)
Definition at line 77 of file motion_estimation.c.
Referenced by search_mv().
ff_me_search_tss()
uint64_t ff_me_search_tss (AVMotionEstContext * me_ctx, int x_mb, int y_mb, int * mv)
Definition at line 96 of file motion_estimation.c.
Referenced by search_mv().
ff_me_search_tdls()
uint64_t ff_me_search_tdls (AVMotionEstContext * me_ctx, int x_mb, int y_mb, int * mv)
Definition at line 127 of file motion_estimation.c.
Referenced by search_mv().
ff_me_search_ntss()
uint64_t ff_me_search_ntss (AVMotionEstContext * me_ctx, int x_mb, int y_mb, int * mv)
Definition at line 159 of file motion_estimation.c.
Referenced by search_mv().
ff_me_search_fss()
uint64_t ff_me_search_fss (AVMotionEstContext * me_ctx, int x_mb, int y_mb, int * mv)
Definition at line 212 of file motion_estimation.c.
Referenced by search_mv().
ff_me_search_ds()
uint64_t ff_me_search_ds (AVMotionEstContext * me_ctx, int x_mb, int y_mb, int * mv)
Definition at line 244 of file motion_estimation.c.
Referenced by search_mv(), and var_size_bme().
ff_me_search_hexbs()
uint64_t ff_me_search_hexbs (AVMotionEstContext * me_ctx, int x_mb, int y_mb, int * mv)
Definition at line 299 of file motion_estimation.c.
Referenced by search_mv().
ff_me_search_epzs()
uint64_t ff_me_search_epzs (AVMotionEstContext * me_ctx, int x_mb, int y_mb, int * mv)
Definition at line 332 of file motion_estimation.c.
Referenced by filter_frame(), and search_mv().
ff_me_search_umh()
uint64_t ff_me_search_umh (AVMotionEstContext * me_ctx, int x_mb, int y_mb, int * mv)
Definition at line 373 of file motion_estimation.c.
Referenced by filter_frame(), and search_mv().