FFmpeg: libavcodec/motionpixels.c File Reference
motionpixels.c File Reference
#include "avcodec.h"
#include "get_bits.h"
#include "bswapdsp.h"
#include "internal.h"
#include "motionpixels_tablegen.h"
Data Structures
struct HuffCode
struct MotionPixelsContext
Macros
#define MAX_HUFF_CODES 16
Functions
static av_cold int mp_decode_end (AVCodecContext *avctx)
static av_cold int mp_decode_init (AVCodecContext *avctx)
static void mp_read_changes_map (MotionPixelsContext *mp, GetBitContext *gb, int count, int bits_len, int read_color)
static int mp_get_code (MotionPixelsContext *mp, GetBitContext *gb, int size, int code)
static int mp_read_codes_table (MotionPixelsContext *mp, GetBitContext *gb)
static int mp_gradient (MotionPixelsContext *mp, int component, int v)
static YuvPixel mp_get_yuv_from_rgb (MotionPixelsContext *mp, int x, int y)
static void mp_set_rgb_from_yuv (MotionPixelsContext *mp, int x, int y, const YuvPixel *p)
static int mp_get_vlc (MotionPixelsContext *mp, GetBitContext *gb)
static void mp_decode_line (MotionPixelsContext *mp, GetBitContext *gb, int y)
static void mp_decode_frame_helper (MotionPixelsContext *mp, GetBitContext *gb)
static int mp_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
Variables
AVCodec ff_motionpixels_decoder
Macro Definition Documentation
MAX_HUFF_CODES
#define MAX_HUFF_CODES 16
Definition at line 27 of file motionpixels.c.
Referenced by mp_get_code().
Function Documentation
mp_decode_end()
static av_cold int mp_decode_end (AVCodecContext * avctx) static
Definition at line 53 of file motionpixels.c.
Referenced by mp_decode_init().
mp_decode_init()
static av_cold int mp_decode_init (AVCodecContext * avctx) static
Definition at line 66 of file motionpixels.c.
mp_read_changes_map()
static void mp_read_changes_map (MotionPixelsContext * mp, GetBitContext * gb, int count, int bits_len, int read_color) static
Definition at line 101 of file motionpixels.c.
Referenced by mp_decode_frame().
mp_get_code()
static int mp_get_code (MotionPixelsContext * mp, GetBitContext * gb, int size, int code) static
Definition at line 130 of file motionpixels.c.
Referenced by mp_read_codes_table().
mp_read_codes_table()
static int mp_read_codes_table (MotionPixelsContext * mp, GetBitContext * gb) static
Definition at line 152 of file motionpixels.c.
Referenced by mp_decode_frame().
mp_gradient()
static int mp_gradient (MotionPixelsContext * mp, int component, int v) static
Definition at line 174 of file motionpixels.c.
Referenced by mp_decode_frame_helper(), and mp_decode_line().
mp_get_yuv_from_rgb()
static YuvPixel mp_get_yuv_from_rgb (MotionPixelsContext * mp, int x, int y) static
Definition at line 183 of file motionpixels.c.
Referenced by mp_decode_frame_helper(), and mp_decode_line().
mp_set_rgb_from_yuv()
static void mp_set_rgb_from_yuv (MotionPixelsContext * mp, int x, int y, const YuvPixel * p) static
Definition at line 191 of file motionpixels.c.
Referenced by mp_decode_frame_helper(), and mp_decode_line().
mp_get_vlc()
static int mp_get_vlc (MotionPixelsContext * mp, GetBitContext * gb) static
Definition at line 199 of file motionpixels.c.
Referenced by mp_decode_frame_helper(), and mp_decode_line().
mp_decode_line()
static void mp_decode_line (MotionPixelsContext * mp, GetBitContext * gb, int y) static
Definition at line 207 of file motionpixels.c.
Referenced by mp_decode_frame_helper().
mp_decode_frame_helper()
static void mp_decode_frame_helper (MotionPixelsContext * mp, GetBitContext * gb) static
Definition at line 254 of file motionpixels.c.
Referenced by mp_decode_frame().
mp_decode_frame()
static int mp_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 283 of file motionpixels.c.
Variable Documentation
ff_motionpixels_decoder
AVCodec ff_motionpixels_decoder
Initial value:
= {
    .name           = "motionpixels",
    .long_name      = NULL_IF_CONFIG_SMALL("Motion Pixels video"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_MOTIONPIXELS,
    .priv_data_size = sizeof(MotionPixelsContext),
    .init           = mp_decode_init,
    .close          = mp_decode_end,
    .decode         = mp_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 345 of file motionpixels.c.