FFmpeg: libavcodec/motionpixels_tablegen.h File Reference
motionpixels_tablegen.h File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
Data Structures
struct YuvPixel
Functions
static int mp_yuv_to_rgb (int y, int v, int u, int clip_rgb)
static av_cold void mp_set_zero_yuv (YuvPixel *p)
static av_cold void mp_build_rgb_yuv_table (YuvPixel *p)
static av_cold void motionpixels_tableinit (void)
Variables
static YuvPixel mp_rgb_yuv_table [1<< 15]
Function Documentation
mp_yuv_to_rgb()
static int mp_yuv_to_rgb (int y, int v, int u, int clip_rgb) static
Definition at line 33 of file motionpixels_tablegen.h.
Referenced by mp_build_rgb_yuv_table(), and mp_set_rgb_from_yuv().
mp_set_zero_yuv()
static av_cold void mp_set_zero_yuv (YuvPixel * p) static
Definition at line 53 of file motionpixels_tablegen.h.
Referenced by mp_build_rgb_yuv_table().
mp_build_rgb_yuv_table()
static av_cold void mp_build_rgb_yuv_table (YuvPixel * p) static
Definition at line 67 of file motionpixels_tablegen.h.
Referenced by motionpixels_tableinit().
motionpixels_tableinit()
static av_cold void motionpixels_tableinit (void) static
Definition at line 85 of file motionpixels_tablegen.h.
Referenced by main(), and mp_decode_init().
Variable Documentation
mp_rgb_yuv_table
YuvPixel mp_rgb_yuv_table[1<< 15] static
Definition at line 51 of file motionpixels_tablegen.h.
Referenced by main(), and mp_get_yuv_from_rgb().