FFmpeg: libavcodec/motion_est_template.c File Reference
motion_est_template.c File Reference
Motion estimation template.
#include "libavutil/qsort.h"
#include "mpegvideo.h"
Macros
#define LOAD_COMMON
#define CHECK_HALF_MV(dx, dy, x, y)
#define CHECK_QUARTER_MV(dx, dy, x, y)
#define CHECK_MV(x, y)
#define CHECK_CLIPPED_MV(ax, ay)
#define CHECK_MV_DIR(x, y, new_dir)
#define check(x, y, S, v)
#define LOAD_COMMON2
#define SAB_CHECK_MV(ax, ay)
#define MAX_SAB_SIZE ME_MAP_SIZE
Functions
static int hpel_motion_search (MpegEncContext *s, int *mx_ptr, int *my_ptr, int dmin, int src_index, int ref_index, int size, int h)
static int no_sub_motion_search (MpegEncContext *s, int *mx_ptr, int *my_ptr, int dmin, int src_index, int ref_index, int size, int h)
static int get_mb_score (MpegEncContext *s, int mx, int my, int src_index, int ref_index, int size, int h, int add_rate)
int ff_get_mb_score (MpegEncContext *s, int mx, int my, int src_index, int ref_index, int size, int h, int add_rate)
static int qpel_motion_search (MpegEncContext *s, int *mx_ptr, int *my_ptr, int dmin, int src_index, int ref_index, int size, int h)
static av_always_inline int small_diamond_search (MpegEncContext *s, int *best, int dmin, int src_index, int ref_index, const int penalty_factor, int size, int h, int flags)
static int funny_diamond_search (MpegEncContext *s, int *best, int dmin, int src_index, int ref_index, const int penalty_factor, int size, int h, int flags)
static int hex_search (MpegEncContext *s, int *best, int dmin, int src_index, int ref_index, const int penalty_factor, int size, int h, int flags, int dia_size)
static int l2s_dia_search (MpegEncContext *s, int *best, int dmin, int src_index, int ref_index, const int penalty_factor, int size, int h, int flags)
static int umh_search (MpegEncContext *s, int *best, int dmin, int src_index, int ref_index, const int penalty_factor, int size, int h, int flags)
static int full_search (MpegEncContext *s, int *best, int dmin, int src_index, int ref_index, const int penalty_factor, int size, int h, int flags)
static int sab_diamond_search (MpegEncContext *s, int *best, int dmin, int src_index, int ref_index, const int penalty_factor, int size, int h, int flags)
static int var_diamond_search (MpegEncContext *s, int *best, int dmin, int src_index, int ref_index, const int penalty_factor, int size, int h, int flags)
static av_always_inline int diamond_search (MpegEncContext *s, int *best, int dmin, int src_index, int ref_index, const int penalty_factor, int size, int h, int flags)
static av_always_inline int epzs_motion_search_internal (MpegEncContext *s, int *mx_ptr, int *my_ptr, int P[10][2], int src_index, int ref_index, int16_t(*last_mv)[2], int ref_mv_scale, int flags, int size, int h)
int ff_epzs_motion_search (MpegEncContext *s, int *mx_ptr, int *my_ptr, int P[10][2], int src_index, int ref_index, int16_t(*last_mv)[2], int ref_mv_scale, int size, int h)
static int epzs_motion_search4 (MpegEncContext *s, int *mx_ptr, int *my_ptr, int P[10][2], int src_index, int ref_index, int16_t(*last_mv)[2], int ref_mv_scale)
static int epzs_motion_search2 (MpegEncContext *s, int *mx_ptr, int *my_ptr, int P[10][2], int src_index, int ref_index, int16_t(*last_mv)[2], int ref_mv_scale)
Detailed Description
Motion estimation template.
Definition in file motion_est_template.c.
Macro Definition Documentation
LOAD_COMMON
#define LOAD_COMMON
Value:
uint32_t av_unused * const score_map= c->score_map;\
    const int av_unused xmin= c->xmin;\
    const int av_unused ymin= c->ymin;\
    const int av_unused xmax= c->xmax;\
    const int av_unused ymax= c->ymax;\
    uint8_t *mv_penalty= c->current_mv_penalty;\
    const int pred_x= c->pred_x;\
    const int pred_y= c->pred_y;\
Definition at line 31 of file motion_est_template.c.
Referenced by epzs_motion_search2(), epzs_motion_search4(), epzs_motion_search_internal(), full_search(), funny_diamond_search(), get_mb_score(), hex_search(), hpel_motion_search(), l2s_dia_search(), qpel_motion_search(), sab_diamond_search(), sad_hpel_motion_search(), small_diamond_search(), umh_search(), and var_diamond_search().
CHECK_HALF_MV
#define CHECK_HALF_MV (dx, dy, x, y)
Value:
{\
    const int hx= 2*(x)+(dx);\
    const int hy= 2*(y)+(dy);\
    d= cmp_hpel(s, x, y, dx, dy, size, h, ref_index, src_index, cmp_sub, chroma_cmp_sub, flags);\
    d += (mv_penalty[hx - pred_x] + mv_penalty[hy - pred_y])*penalty_factor;\
    COPY3_IF_LT(dmin, d, bx, hx, by, hy)\
}
Definition at line 41 of file motion_est_template.c.
Referenced by hpel_motion_search().
CHECK_QUARTER_MV
#define CHECK_QUARTER_MV (dx, dy, x, y)
Value:
{\
    const int hx= 4*(x)+(dx);\
    const int hy= 4*(y)+(dy);\
    d= cmp_qpel(s, x, y, dx, dy, size, h, ref_index, src_index, cmpf, chroma_cmpf, flags);\
    d += (mv_penalty[hx - pred_x] + mv_penalty[hy - pred_y])*penalty_factor;\
    COPY3_IF_LT(dmin, d, bx, hx, by, hy)\
}
Definition at line 198 of file motion_est_template.c.
Referenced by qpel_motion_search().
CHECK_MV
#define CHECK_MV (x, y)
Value:
{\
    const unsigned key = ((unsigned)(y)<<ME_MAP_MV_BITS) + (x) + map_generation;\
    const int index= (((unsigned)(y)<<ME_MAP_SHIFT) + (x))&(ME_MAP_SIZE-1);\
    av_assert2((x) >= xmin);\
    av_assert2((x) <= xmax);\
    av_assert2((y) >= ymin);\
    av_assert2((y) <= ymax);\
    if(map[index]!=key){\
        d= cmp(s, x, y, 0, 0, size, h, ref_index, src_index, cmpf, chroma_cmpf, flags);\
        map[index]= key;\
        score_map[index]= d;\
        d += (mv_penalty[((x)*(1<<shift))-pred_x] + mv_penalty[((y)*(1<<shift))-pred_y])*penalty_factor;\
        COPY3_IF_LT(dmin, d, best[0], x, best[1], y)\
    }\
}
Definition at line 360 of file motion_est_template.c.
Referenced by epzs_motion_search2(), epzs_motion_search4(), epzs_motion_search_internal(), full_search(), funny_diamond_search(), sab_diamond_search(), umh_search(), and var_diamond_search().
CHECK_CLIPPED_MV
#define CHECK_CLIPPED_MV (ax, ay)
Value:
{\
    const int Lx= ax;\
    const int Ly= ay;\
    const int Lx2= FFMAX(xmin, FFMIN(Lx, xmax));\
    const int Ly2= FFMAX(ymin, FFMIN(Ly, ymax));\
    CHECK_MV(Lx2, Ly2)\
}
Definition at line 377 of file motion_est_template.c.
Referenced by epzs_motion_search2(), epzs_motion_search4(), epzs_motion_search_internal(), full_search(), hex_search(), l2s_dia_search(), and umh_search().
CHECK_MV_DIR
#define CHECK_MV_DIR (x, y, new_dir)
Value:
{\
    const unsigned key = ((unsigned)(y)<<ME_MAP_MV_BITS) + (x) + map_generation;\
    const int index= (((unsigned)(y)<<ME_MAP_SHIFT) + (x))&(ME_MAP_SIZE-1);\
    if(map[index]!=key){\
        d= cmp(s, x, y, 0, 0, size, h, ref_index, src_index, cmpf, chroma_cmpf, flags);\
        map[index]= key;\
        score_map[index]= d;\
        d += (mv_penalty[(int)((unsigned)(x)<<shift)-pred_x] + mv_penalty[(int)((unsigned)(y)<<shift)-pred_y])*penalty_factor;\
        if(d<dmin){\
            best[0]=x;\
            best[1]=y;\
            dmin=d;\
            next_dir= new_dir;\
        }\
    }\
}
Definition at line 386 of file motion_est_template.c.
Referenced by small_diamond_search().
check
#define check (x, y, S, v)
Value:
if((x)<(xmin<<(S))) av_log(NULL, AV_LOG_ERROR, "%d %d %d %d %d xmin" #v, xmin, (x), (y), s->mb_x, s->mb_y);\
if((x)>(xmax<<(S))) av_log(NULL, AV_LOG_ERROR, "%d %d %d %d %d xmax" #v, xmax, (x), (y), s->mb_x, s->mb_y);\
if((y)<(ymin<<(S))) av_log(NULL, AV_LOG_ERROR, "%d %d %d %d %d ymin" #v, ymin, (x), (y), s->mb_x, s->mb_y);\
if((y)>(ymax<<(S))) av_log(NULL, AV_LOG_ERROR, "%d %d %d %d %d ymax" #v, ymax, (x), (y), s->mb_x, s->mb_y);\
Definition at line 404 of file motion_est_template.c.
Referenced by dxv_decompress_dxt5(), h261_decode_block(), and voc_probe().
LOAD_COMMON2
#define LOAD_COMMON2
Value:
uint32_t *map= c->map;\
    const int qpel= flags&FLAG_QPEL;\
    const int shift= 1+qpel;\
Definition at line 410 of file motion_est_template.c.
Referenced by epzs_motion_search2(), epzs_motion_search4(), epzs_motion_search_internal(), full_search(), funny_diamond_search(), hex_search(), l2s_dia_search(), sab_diamond_search(), small_diamond_search(), umh_search(), and var_diamond_search().
SAB_CHECK_MV
#define SAB_CHECK_MV (ax, ay)
Value:
{\
    const unsigned key = ((ay)<<ME_MAP_MV_BITS) + (ax) + map_generation;\
    const int index= (((ay)<<ME_MAP_SHIFT) + (ax))&(ME_MAP_SIZE-1);\
    if(map[index]!=key){\
        d= cmp(s, ax, ay, 0, 0, size, h, ref_index, src_index, cmpf, chroma_cmpf, flags);\
        map[index]= key;\
        score_map[index]= d;\
        d += (mv_penalty[((ax)<<shift)-pred_x] + mv_penalty[((ay)<<shift)-pred_y])*penalty_factor;\
        if(d < minima[minima_count-1].height){\
            int j=0;\
            \
            while(d >= minima[j].height) j++;\
\
            memmove(&minima [j+1], &minima [j], (minima_count - j - 1)*sizeof(Minima));\
\
            minima[j].checked= 0;\
            minima[j].height= d;\
            minima[j].x= ax;\
            minima[j].y= ay;\
            \
            i=-1;\
            continue;\
        }\
    }\
}
Definition at line 652 of file motion_est_template.c.
Referenced by sab_diamond_search().
MAX_SAB_SIZE
#define MAX_SAB_SIZE ME_MAP_SIZE
Definition at line 679 of file motion_est_template.c.
Referenced by ff_init_me(), and sab_diamond_search().
Function Documentation
hpel_motion_search()
static int hpel_motion_search (MpegEncContext * s, int * mx_ptr, int * my_ptr, int dmin, int src_index, int ref_index, int size, int h) static
Definition at line 50 of file motion_est_template.c.
Referenced by direct_search(), and ff_init_me().
no_sub_motion_search()
static int no_sub_motion_search (MpegEncContext * s, int * mx_ptr, int * my_ptr, int dmin, int src_index, int ref_index, int size, int h) static
Definition at line 155 of file motion_est_template.c.
Referenced by ff_init_me().
get_mb_score()
static int get_mb_score (MpegEncContext * s, int mx, int my, int src_index, int ref_index, int size, int h, int add_rate) inline static
Definition at line 165 of file motion_est_template.c.
Referenced by direct_search(), estimate_motion_b(), ff_estimate_p_frame_motion(), and ff_get_mb_score().
ff_get_mb_score()
int ff_get_mb_score (MpegEncContext * s, int mx, int my, int src_index, int ref_index, int size, int h, int add_rate)
Definition at line 192 of file motion_est_template.c.
Referenced by encode_q_branch(), and ff_h263_round_chroma().
qpel_motion_search()
static int qpel_motion_search (MpegEncContext * s, int * mx_ptr, int * my_ptr, int dmin, int src_index, int ref_index, int size, int h) static
Definition at line 207 of file motion_est_template.c.
Referenced by direct_search(), and ff_init_me().
small_diamond_search()
static av_always_inline int small_diamond_search (MpegEncContext * s, int * best, int dmin, int src_index, int ref_index, const int penalty_factor, int size, int h, int flags) static
Definition at line 415 of file motion_est_template.c.
Referenced by diamond_search().
funny_diamond_search()
static int funny_diamond_search (MpegEncContext * s, int * best, int dmin, int src_index, int ref_index, const int penalty_factor, int size, int h, int flags) static
Definition at line 456 of file motion_est_template.c.
Referenced by diamond_search().
hex_search()
static int hex_search (MpegEncContext * s, int * best, int dmin, int src_index, int ref_index, const int penalty_factor, int size, int h, int flags, int dia_size) static
Definition at line 498 of file motion_est_template.c.
Referenced by diamond_search(), and umh_search().
l2s_dia_search()
static int l2s_dia_search (MpegEncContext * s, int * best, int dmin, int src_index, int ref_index, const int penalty_factor, int size, int h, int flags) static
Definition at line 532 of file motion_est_template.c.
Referenced by diamond_search().
umh_search()
static int umh_search (MpegEncContext * s, int * best, int dmin, int src_index, int ref_index, const int penalty_factor, int size, int h, int flags) static
Definition at line 570 of file motion_est_template.c.
Referenced by diamond_search().
full_search()
static int full_search (MpegEncContext * s, int * best, int dmin, int src_index, int ref_index, const int penalty_factor, int size, int h, int flags) static
Definition at line 617 of file motion_est_template.c.
Referenced by diamond_search().
sab_diamond_search()
static int sab_diamond_search (MpegEncContext * s, int * best, int dmin, int src_index, int ref_index, const int penalty_factor, int size, int h, int flags) static
Definition at line 680 of file motion_est_template.c.
Referenced by diamond_search().
var_diamond_search()
static int var_diamond_search (MpegEncContext * s, int * best, int dmin, int src_index, int ref_index, const int penalty_factor, int size, int h, int flags) static
Definition at line 770 of file motion_est_template.c.
Referenced by diamond_search().
diamond_search()
static av_always_inline int diamond_search (MpegEncContext * s, int * best, int dmin, int src_index, int ref_index, const int penalty_factor, int size, int h, int flags) static
Definition at line 831 of file motion_est_template.c.
Referenced by epzs_motion_search2(), epzs_motion_search4(), and epzs_motion_search_internal().
epzs_motion_search_internal()
static av_always_inline int epzs_motion_search_internal (MpegEncContext * s, int * mx_ptr, int * my_ptr, int P[10][2], int src_index, int ref_index, int16_t(*) last_mv[2], int ref_mv_scale, int flags, int size, int h) static
Parameters
P a list of candidate mvs to check before starting the iterative search. If one of the candidates is close to the optimal mv, then it takes fewer iterations. And it increases the chance that we find the optimal mv.
< x and y coordinates of the best motion vector. i.e. the difference between the position of the block currently being encoded and the position of the block chosen to predict it from.
< the score (cmp + penalty) of any given mv
< the best value of d, i.e. the score corresponding to the mv stored in best[].
Definition at line 859 of file motion_est_template.c.
Referenced by ff_epzs_motion_search().
ff_epzs_motion_search()
int ff_epzs_motion_search (MpegEncContext * s, int * mx_ptr, int * my_ptr, int P[10][2], int src_index, int ref_index, int16_t(*) last_mv[2], int ref_mv_scale, int size, int h)
Definition at line 976 of file motion_est_template.c.
Referenced by direct_search(), encode_q_branch(), estimate_motion_b(), ff_estimate_p_frame_motion(), ff_h263_round_chroma(), and ff_pre_estimate_p_frame_motion().
epzs_motion_search4()
static int epzs_motion_search4 (MpegEncContext * s, int * mx_ptr, int * my_ptr, int P[10][2], int src_index, int ref_index, int16_t(*) last_mv[2], int ref_mv_scale) static
Definition at line 992 of file motion_est_template.c.
Referenced by h263_mv4_search().
epzs_motion_search2()
static int epzs_motion_search2 (MpegEncContext * s, int * mx_ptr, int * my_ptr, int P[10][2], int src_index, int ref_index, int16_t(*) last_mv[2], int ref_mv_scale) static
Definition at line 1051 of file motion_est_template.c.
Referenced by interlaced_search().