FFmpeg: libavformat/mov_chan.c File Reference
mov_chan.c File Reference
#include <stdint.h>
#include "libavutil/channel_layout.h"
#include "libavcodec/avcodec.h"
#include "mov_chan.h"
Data Structures
struct MovChannelLayoutMap
Macros
#define MOV_CH_LAYOUT_UNKNOWN 0xFFFF0000
Enumerations
enum MovChannelLayoutTag {
MOV_CH_LAYOUT_USE_DESCRIPTIONS = (0 << 16) | 0, MOV_CH_LAYOUT_USE_BITMAP = (1 << 16) | 0, MOV_CH_LAYOUT_DISCRETEINORDER = (147 << 16) | 0, MOV_CH_LAYOUT_MONO = (100 << 16) | 1,
MOV_CH_LAYOUT_STEREO = (101 << 16) | 2, MOV_CH_LAYOUT_STEREOHEADPHONES = (102 << 16) | 2, MOV_CH_LAYOUT_MATRIXSTEREO = (103 << 16) | 2, MOV_CH_LAYOUT_MIDSIDE = (104 << 16) | 2,
MOV_CH_LAYOUT_XY = (105 << 16) | 2, MOV_CH_LAYOUT_BINAURAL = (106 << 16) | 2, MOV_CH_LAYOUT_AMBISONIC_B_FORMAT = (107 << 16) | 4, MOV_CH_LAYOUT_QUADRAPHONIC = (108 << 16) | 4,
MOV_CH_LAYOUT_PENTAGONAL = (109 << 16) | 5, MOV_CH_LAYOUT_HEXAGONAL = (110 << 16) | 6, MOV_CH_LAYOUT_OCTAGONAL = (111 << 16) | 8, MOV_CH_LAYOUT_CUBE = (112 << 16) | 8,
MOV_CH_LAYOUT_MPEG_3_0_A = (113 << 16) | 3, MOV_CH_LAYOUT_MPEG_3_0_B = (114 << 16) | 3, MOV_CH_LAYOUT_MPEG_4_0_A = (115 << 16) | 4, MOV_CH_LAYOUT_MPEG_4_0_B = (116 << 16) | 4,
MOV_CH_LAYOUT_MPEG_5_0_A = (117 << 16) | 5, MOV_CH_LAYOUT_MPEG_5_0_B = (118 << 16) | 5, MOV_CH_LAYOUT_MPEG_5_0_C = (119 << 16) | 5, MOV_CH_LAYOUT_MPEG_5_0_D = (120 << 16) | 5,
MOV_CH_LAYOUT_MPEG_5_1_A = (121 << 16) | 6, MOV_CH_LAYOUT_MPEG_5_1_B = (122 << 16) | 6, MOV_CH_LAYOUT_MPEG_5_1_C = (123 << 16) | 6, MOV_CH_LAYOUT_MPEG_5_1_D = (124 << 16) | 6,
MOV_CH_LAYOUT_MPEG_6_1_A = (125 << 16) | 7, MOV_CH_LAYOUT_MPEG_7_1_A = (126 << 16) | 8, MOV_CH_LAYOUT_MPEG_7_1_B = (127 << 16) | 8, MOV_CH_LAYOUT_MPEG_7_1_C = (128 << 16) | 8,
MOV_CH_LAYOUT_EMAGIC_DEFAULT_7_1 = (129 << 16) | 8, MOV_CH_LAYOUT_SMPTE_DTV = (130 << 16) | 8, MOV_CH_LAYOUT_ITU_2_1 = (131 << 16) | 3, MOV_CH_LAYOUT_ITU_2_2 = (132 << 16) | 4,
MOV_CH_LAYOUT_DVD_4 = (133 << 16) | 3, MOV_CH_LAYOUT_DVD_5 = (134 << 16) | 4, MOV_CH_LAYOUT_DVD_6 = (135 << 16) | 5, MOV_CH_LAYOUT_DVD_10 = (136 << 16) | 4,
MOV_CH_LAYOUT_DVD_11 = (137 << 16) | 5, MOV_CH_LAYOUT_DVD_18 = (138 << 16) | 5, MOV_CH_LAYOUT_AUDIOUNIT_6_0 = (139 << 16) | 6, MOV_CH_LAYOUT_AUDIOUNIT_7_0 = (140 << 16) | 7,
MOV_CH_LAYOUT_AUDIOUNIT_7_0_FRONT = (148 << 16) | 7, MOV_CH_LAYOUT_AAC_6_0 = (141 << 16) | 6, MOV_CH_LAYOUT_AAC_6_1 = (142 << 16) | 7, MOV_CH_LAYOUT_AAC_7_0 = (143 << 16) | 7,
MOV_CH_LAYOUT_AAC_OCTAGONAL = (144 << 16) | 8, MOV_CH_LAYOUT_TMH_10_2_STD = (145 << 16) | 16, MOV_CH_LAYOUT_TMH_10_2_FULL = (146 << 16) | 21, MOV_CH_LAYOUT_AC3_1_0_1 = (149 << 16) | 2,
MOV_CH_LAYOUT_AC3_3_0 = (150 << 16) | 3, MOV_CH_LAYOUT_AC3_3_1 = (151 << 16) | 4, MOV_CH_LAYOUT_AC3_3_0_1 = (152 << 16) | 4, MOV_CH_LAYOUT_AC3_2_1_1 = (153 << 16) | 4,
MOV_CH_LAYOUT_AC3_3_1_1 = (154 << 16) | 5, MOV_CH_LAYOUT_EAC3_6_0_A = (155 << 16) | 6, MOV_CH_LAYOUT_EAC3_7_0_A = (156 << 16) | 7, MOV_CH_LAYOUT_EAC3_6_1_A = (157 << 16) | 7,
MOV_CH_LAYOUT_EAC3_6_1_B = (158 << 16) | 7, MOV_CH_LAYOUT_EAC3_6_1_C = (159 << 16) | 7, MOV_CH_LAYOUT_EAC3_7_1_A = (160 << 16) | 8, MOV_CH_LAYOUT_EAC3_7_1_B = (161 << 16) | 8,
MOV_CH_LAYOUT_EAC3_7_1_C = (162 << 16) | 8, MOV_CH_LAYOUT_EAC3_7_1_D = (163 << 16) | 8, MOV_CH_LAYOUT_EAC3_7_1_E = (164 << 16) | 8, MOV_CH_LAYOUT_EAC3_7_1_F = (165 << 16) | 8,
MOV_CH_LAYOUT_EAC3_7_1_G = (166 << 16) | 8, MOV_CH_LAYOUT_EAC3_7_1_H = (167 << 16) | 8, MOV_CH_LAYOUT_DTS_3_1 = (168 << 16) | 4, MOV_CH_LAYOUT_DTS_4_1 = (169 << 16) | 5,
MOV_CH_LAYOUT_DTS_6_0_A = (170 << 16) | 6, MOV_CH_LAYOUT_DTS_6_0_B = (171 << 16) | 6, MOV_CH_LAYOUT_DTS_6_0_C = (172 << 16) | 6, MOV_CH_LAYOUT_DTS_6_1_A = (173 << 16) | 7,
MOV_CH_LAYOUT_DTS_6_1_B = (174 << 16) | 7, MOV_CH_LAYOUT_DTS_6_1_C = (175 << 16) | 7, MOV_CH_LAYOUT_DTS_6_1_D = (182 << 16) | 7, MOV_CH_LAYOUT_DTS_7_0 = (176 << 16) | 7,
MOV_CH_LAYOUT_DTS_7_1 = (177 << 16) | 8, MOV_CH_LAYOUT_DTS_8_0_A = (178 << 16) | 8, MOV_CH_LAYOUT_DTS_8_0_B = (179 << 16) | 8, MOV_CH_LAYOUT_DTS_8_1_A = (180 << 16) | 9,
MOV_CH_LAYOUT_DTS_8_1_B = (181 << 16) | 9
}
mov 'chan' tag reading/writing.
Functions
uint64_t ff_mov_get_channel_layout (uint32_t tag, uint32_t bitmap)
mov 'chan' tag reading/writing.
static uint32_t mov_get_channel_label (uint32_t label)
uint32_t ff_mov_get_channel_layout_tag (enum AVCodecID codec_id, uint64_t channel_layout, uint32_t *bitmap)
Get the channel layout tag for the specified codec id and channel layout.
int ff_mov_read_chan (AVFormatContext *s, AVIOContext *pb, AVStream *st, int64_t size)
Read 'chan' tag from the input stream.
Variables
static const struct MovChannelLayoutMap mov_ch_layout_map_misc []
static const struct MovChannelLayoutMap mov_ch_layout_map_1ch []
static const struct MovChannelLayoutMap mov_ch_layout_map_2ch []
static const struct MovChannelLayoutMap mov_ch_layout_map_3ch []
static const struct MovChannelLayoutMap mov_ch_layout_map_4ch []
static const struct MovChannelLayoutMap mov_ch_layout_map_5ch []
static const struct MovChannelLayoutMap mov_ch_layout_map_6ch []
static const struct MovChannelLayoutMap mov_ch_layout_map_7ch []
static const struct MovChannelLayoutMap mov_ch_layout_map_8ch []
static const struct MovChannelLayoutMap mov_ch_layout_map_9ch []
static const struct MovChannelLayoutMap *const mov_ch_layout_map []
static enum MovChannelLayoutTag mov_ch_layouts_aac []
static enum MovChannelLayoutTag mov_ch_layouts_ac3 []
static enum MovChannelLayoutTag mov_ch_layouts_alac []
static enum MovChannelLayoutTag mov_ch_layouts_wav []
struct {
enum AVCodecID codec_id
enum MovChannelLayoutTag * layouts
} mov_codec_ch_layouts []
Macro Definition Documentation
MOV_CH_LAYOUT_UNKNOWN
#define MOV_CH_LAYOUT_UNKNOWN 0xFFFF0000
Definition at line 48 of file mov_chan.c.
Enumeration Type Documentation
MovChannelLayoutTag
enum MovChannelLayoutTag
mov 'chan' tag reading/writing.
Author
Justin Ruggles Channel Layout Tag This tells which channels are present in the audio stream and the order in which they appear.
Note
We're using the channel layout tag to indicate channel order when the value is greater than 0x10000. The Apple documentation has some contradictions as to how this is actually supposed to be handled.
Core Audio File Format Spec: "The high 16 bits indicates a specific ordering of the channels." Core Audio Data Types Reference: "These identifiers specify the channels included in a layout but do not specify a particular ordering of those channels."
Enumerator
MOV_CH_LAYOUT_USE_DESCRIPTIONS
MOV_CH_LAYOUT_USE_BITMAP
MOV_CH_LAYOUT_DISCRETEINORDER
MOV_CH_LAYOUT_MONO
MOV_CH_LAYOUT_STEREO
MOV_CH_LAYOUT_STEREOHEADPHONES
MOV_CH_LAYOUT_MATRIXSTEREO
MOV_CH_LAYOUT_MIDSIDE
MOV_CH_LAYOUT_XY
MOV_CH_LAYOUT_BINAURAL
MOV_CH_LAYOUT_AMBISONIC_B_FORMAT
MOV_CH_LAYOUT_QUADRAPHONIC
MOV_CH_LAYOUT_PENTAGONAL
MOV_CH_LAYOUT_HEXAGONAL
MOV_CH_LAYOUT_OCTAGONAL
MOV_CH_LAYOUT_CUBE
MOV_CH_LAYOUT_MPEG_3_0_A
MOV_CH_LAYOUT_MPEG_3_0_B
MOV_CH_LAYOUT_MPEG_4_0_A
MOV_CH_LAYOUT_MPEG_4_0_B
MOV_CH_LAYOUT_MPEG_5_0_A
MOV_CH_LAYOUT_MPEG_5_0_B
MOV_CH_LAYOUT_MPEG_5_0_C
MOV_CH_LAYOUT_MPEG_5_0_D
MOV_CH_LAYOUT_MPEG_5_1_A
MOV_CH_LAYOUT_MPEG_5_1_B
MOV_CH_LAYOUT_MPEG_5_1_C
MOV_CH_LAYOUT_MPEG_5_1_D
MOV_CH_LAYOUT_MPEG_6_1_A
MOV_CH_LAYOUT_MPEG_7_1_A
MOV_CH_LAYOUT_MPEG_7_1_B
MOV_CH_LAYOUT_MPEG_7_1_C
MOV_CH_LAYOUT_EMAGIC_DEFAULT_7_1
MOV_CH_LAYOUT_SMPTE_DTV
MOV_CH_LAYOUT_ITU_2_1
MOV_CH_LAYOUT_ITU_2_2
MOV_CH_LAYOUT_DVD_4
MOV_CH_LAYOUT_DVD_5
MOV_CH_LAYOUT_DVD_6
MOV_CH_LAYOUT_DVD_10
MOV_CH_LAYOUT_DVD_11
MOV_CH_LAYOUT_DVD_18
MOV_CH_LAYOUT_AUDIOUNIT_6_0
MOV_CH_LAYOUT_AUDIOUNIT_7_0
MOV_CH_LAYOUT_AUDIOUNIT_7_0_FRONT
MOV_CH_LAYOUT_AAC_6_0
MOV_CH_LAYOUT_AAC_6_1
MOV_CH_LAYOUT_AAC_7_0
MOV_CH_LAYOUT_AAC_OCTAGONAL
MOV_CH_LAYOUT_TMH_10_2_STD
MOV_CH_LAYOUT_TMH_10_2_FULL
MOV_CH_LAYOUT_AC3_1_0_1
MOV_CH_LAYOUT_AC3_3_0
MOV_CH_LAYOUT_AC3_3_1
MOV_CH_LAYOUT_AC3_3_0_1
MOV_CH_LAYOUT_AC3_2_1_1
MOV_CH_LAYOUT_AC3_3_1_1
MOV_CH_LAYOUT_EAC3_6_0_A
MOV_CH_LAYOUT_EAC3_7_0_A
MOV_CH_LAYOUT_EAC3_6_1_A
MOV_CH_LAYOUT_EAC3_6_1_B
MOV_CH_LAYOUT_EAC3_6_1_C
MOV_CH_LAYOUT_EAC3_7_1_A
MOV_CH_LAYOUT_EAC3_7_1_B
MOV_CH_LAYOUT_EAC3_7_1_C
MOV_CH_LAYOUT_EAC3_7_1_D
MOV_CH_LAYOUT_EAC3_7_1_E
MOV_CH_LAYOUT_EAC3_7_1_F
MOV_CH_LAYOUT_EAC3_7_1_G
MOV_CH_LAYOUT_EAC3_7_1_H
MOV_CH_LAYOUT_DTS_3_1
MOV_CH_LAYOUT_DTS_4_1
MOV_CH_LAYOUT_DTS_6_0_A
MOV_CH_LAYOUT_DTS_6_0_B
MOV_CH_LAYOUT_DTS_6_0_C
MOV_CH_LAYOUT_DTS_6_1_A
MOV_CH_LAYOUT_DTS_6_1_B
MOV_CH_LAYOUT_DTS_6_1_C
MOV_CH_LAYOUT_DTS_6_1_D
MOV_CH_LAYOUT_DTS_7_0
MOV_CH_LAYOUT_DTS_7_1
MOV_CH_LAYOUT_DTS_8_0_A
MOV_CH_LAYOUT_DTS_8_0_B
MOV_CH_LAYOUT_DTS_8_1_A
MOV_CH_LAYOUT_DTS_8_1_B
Definition at line 47 of file mov_chan.c.
Function Documentation
ff_mov_get_channel_layout()
uint64_t ff_mov_get_channel_layout (uint32_t tag, uint32_t bitmap)
mov 'chan' tag reading/writing.
Author
Justin Ruggles Get the channel layout for the specified channel layout tag.
Parameters
[in] tag channel layout tag
[out] bitmap channel bitmap (only used if needed)
Returns
channel layout
Definition at line 454 of file mov_chan.c.
Referenced by ff_mov_read_chan().
mov_get_channel_label()
static uint32_t mov_get_channel_label (uint32_t label) static
Definition at line 481 of file mov_chan.c.
Referenced by ff_mov_read_chan().
ff_mov_get_channel_layout_tag()
uint32_t ff_mov_get_channel_layout_tag (enum AVCodecID codec_id, uint64_t channel_layout, uint32_t * bitmap)
Get the channel layout tag for the specified codec id and channel layout.
If the layout tag was not found, use a channel bitmap if possible.
Parameters
[in] codec_id codec id
[in] channel_layout channel layout
[out] bitmap channel bitmap
Returns
channel layout tag
Definition at line 494 of file mov_chan.c.
Referenced by mov_write_chan_tag().
ff_mov_read_chan()
int ff_mov_read_chan (AVFormatContext * s, AVIOContext * pb, AVStream * st, int64_t size)
Read 'chan' tag from the input stream.
Parameters
s AVFormatContext
pb AVIOContext
st The stream to set codec values for
size Remaining size in the 'chan' tag
Returns
0 if ok, or negative AVERROR code on failure
Definition at line 547 of file mov_chan.c.
Referenced by aiff_read_header(), mov_read_chan(), and read_header().
Variable Documentation
mov_ch_layout_map_misc
const struct MovChannelLayoutMap mov_ch_layout_map_misc[] static
Initial value:
= {
    { MOV_CH_LAYOUT_USE_DESCRIPTIONS,   0 },
    { MOV_CH_LAYOUT_USE_BITMAP,         0 },
    { MOV_CH_LAYOUT_DISCRETEINORDER,    0 },
    { MOV_CH_LAYOUT_UNKNOWN,            0 },
    { MOV_CH_LAYOUT_TMH_10_2_STD,       0 },
    { MOV_CH_LAYOUT_TMH_10_2_FULL,      0 },
    { 0, 0 },
}
Definition at line 141 of file mov_chan.c.
mov_ch_layout_map_1ch
const struct MovChannelLayoutMap mov_ch_layout_map_1ch[] static
Initial value:
= {
    { MOV_CH_LAYOUT_MONO,               AV_CH_LAYOUT_MONO },
    { 0, 0 },
}
Definition at line 156 of file mov_chan.c.
mov_ch_layout_map_2ch
const struct MovChannelLayoutMap mov_ch_layout_map_2ch[] static
Initial value:
= {
    { MOV_CH_LAYOUT_STEREO,             AV_CH_LAYOUT_STEREO         },
    { MOV_CH_LAYOUT_STEREOHEADPHONES,   AV_CH_LAYOUT_STEREO         },
    { MOV_CH_LAYOUT_BINAURAL,           AV_CH_LAYOUT_STEREO         },
    { MOV_CH_LAYOUT_MIDSIDE,            AV_CH_LAYOUT_STEREO         },
    { MOV_CH_LAYOUT_XY,                 AV_CH_LAYOUT_STEREO         },
    { MOV_CH_LAYOUT_MATRIXSTEREO,       AV_CH_LAYOUT_STEREO_DOWNMIX },
    { MOV_CH_LAYOUT_AC3_1_0_1,          AV_CH_LAYOUT_MONO |
                                        AV_CH_LOW_FREQUENCY         },
    { 0, 0 },
}
Definition at line 161 of file mov_chan.c.
mov_ch_layout_map_3ch
const struct MovChannelLayoutMap mov_ch_layout_map_3ch[] static
Initial value:
= {
    { MOV_CH_LAYOUT_MPEG_3_0_A,         AV_CH_LAYOUT_SURROUND },
    { MOV_CH_LAYOUT_MPEG_3_0_B,         AV_CH_LAYOUT_SURROUND },
    { MOV_CH_LAYOUT_AC3_3_0,            AV_CH_LAYOUT_SURROUND },
    { MOV_CH_LAYOUT_ITU_2_1,            AV_CH_LAYOUT_2_1      },
    { MOV_CH_LAYOUT_DVD_4,              AV_CH_LAYOUT_2POINT1  },
    { 0, 0 },
}
Definition at line 175 of file mov_chan.c.
mov_ch_layout_map_4ch
const struct MovChannelLayoutMap mov_ch_layout_map_4ch[] static
Initial value:
= {
    { MOV_CH_LAYOUT_AMBISONIC_B_FORMAT, 0 },
    { MOV_CH_LAYOUT_QUADRAPHONIC,       AV_CH_LAYOUT_QUAD    },
    { MOV_CH_LAYOUT_MPEG_4_0_A,         AV_CH_LAYOUT_4POINT0 },
    { MOV_CH_LAYOUT_MPEG_4_0_B,         AV_CH_LAYOUT_4POINT0 },
    { MOV_CH_LAYOUT_AC3_3_1,            AV_CH_LAYOUT_4POINT0 },
    { MOV_CH_LAYOUT_ITU_2_2,            AV_CH_LAYOUT_2_2     },
    { MOV_CH_LAYOUT_DVD_5,              AV_CH_LAYOUT_2_1 |
                                        AV_CH_LOW_FREQUENCY  },
    { MOV_CH_LAYOUT_AC3_2_1_1,          AV_CH_LAYOUT_2_1 |
                                        AV_CH_LOW_FREQUENCY  },
    { MOV_CH_LAYOUT_DVD_10,             AV_CH_LAYOUT_3POINT1 },
    { MOV_CH_LAYOUT_AC3_3_0_1,          AV_CH_LAYOUT_3POINT1 },
    { MOV_CH_LAYOUT_DTS_3_1,            AV_CH_LAYOUT_3POINT1 },
    { 0, 0 },
}
Definition at line 186 of file mov_chan.c.
mov_ch_layout_map_5ch
const struct MovChannelLayoutMap mov_ch_layout_map_5ch[] static
Initial value:
= {
    { MOV_CH_LAYOUT_PENTAGONAL,         AV_CH_LAYOUT_5POINT0_BACK },
    { MOV_CH_LAYOUT_MPEG_5_0_A,         AV_CH_LAYOUT_5POINT0 },
    { MOV_CH_LAYOUT_MPEG_5_0_B,         AV_CH_LAYOUT_5POINT0 },
    { MOV_CH_LAYOUT_MPEG_5_0_C,         AV_CH_LAYOUT_5POINT0 },
    { MOV_CH_LAYOUT_MPEG_5_0_D,         AV_CH_LAYOUT_5POINT0 },
    { MOV_CH_LAYOUT_DVD_6,              AV_CH_LAYOUT_2_2 |
                                        AV_CH_LOW_FREQUENCY },
    { MOV_CH_LAYOUT_DVD_18,             AV_CH_LAYOUT_2_2 |
                                        AV_CH_LOW_FREQUENCY },
    { MOV_CH_LAYOUT_DVD_11,             AV_CH_LAYOUT_4POINT1 },
    { MOV_CH_LAYOUT_AC3_3_1_1,          AV_CH_LAYOUT_4POINT1 },
    { MOV_CH_LAYOUT_DTS_4_1,            AV_CH_LAYOUT_4POINT1 },
    { 0, 0 },
}
Definition at line 208 of file mov_chan.c.
mov_ch_layout_map_6ch
const struct MovChannelLayoutMap mov_ch_layout_map_6ch[] static
Initial value:
= {
    { MOV_CH_LAYOUT_HEXAGONAL,          AV_CH_LAYOUT_HEXAGONAL },
    { MOV_CH_LAYOUT_DTS_6_0_C,          AV_CH_LAYOUT_HEXAGONAL },
    { MOV_CH_LAYOUT_MPEG_5_1_A,         AV_CH_LAYOUT_5POINT1 },
    { MOV_CH_LAYOUT_MPEG_5_1_B,         AV_CH_LAYOUT_5POINT1 },
    { MOV_CH_LAYOUT_MPEG_5_1_C,         AV_CH_LAYOUT_5POINT1 },
    { MOV_CH_LAYOUT_MPEG_5_1_D,         AV_CH_LAYOUT_5POINT1 },
    { MOV_CH_LAYOUT_AUDIOUNIT_6_0,      AV_CH_LAYOUT_6POINT0 },
    { MOV_CH_LAYOUT_AAC_6_0,            AV_CH_LAYOUT_6POINT0 },
    { MOV_CH_LAYOUT_EAC3_6_0_A,         AV_CH_LAYOUT_6POINT0 },
    { MOV_CH_LAYOUT_DTS_6_0_A,          AV_CH_LAYOUT_6POINT0_FRONT },
    { MOV_CH_LAYOUT_DTS_6_0_B,          AV_CH_LAYOUT_5POINT0_BACK |
                                        AV_CH_TOP_CENTER },
    { 0, 0 },
}
Definition at line 227 of file mov_chan.c.
mov_ch_layout_map_7ch
const struct MovChannelLayoutMap mov_ch_layout_map_7ch[] static
Initial value:
= {
    { MOV_CH_LAYOUT_MPEG_6_1_A,          AV_CH_LAYOUT_6POINT1 },
    { MOV_CH_LAYOUT_AAC_6_1,             AV_CH_LAYOUT_6POINT1 },
    { MOV_CH_LAYOUT_EAC3_6_1_A,          AV_CH_LAYOUT_6POINT1 },
    { MOV_CH_LAYOUT_DTS_6_1_D,           AV_CH_LAYOUT_6POINT1 },
    { MOV_CH_LAYOUT_AUDIOUNIT_7_0,       AV_CH_LAYOUT_7POINT0 },
    { MOV_CH_LAYOUT_AAC_7_0,             AV_CH_LAYOUT_7POINT0 },
    { MOV_CH_LAYOUT_EAC3_7_0_A,          AV_CH_LAYOUT_7POINT0 },
    { MOV_CH_LAYOUT_AUDIOUNIT_7_0_FRONT, AV_CH_LAYOUT_7POINT0_FRONT },
    { MOV_CH_LAYOUT_DTS_7_0,             AV_CH_LAYOUT_7POINT0_FRONT },
    { MOV_CH_LAYOUT_EAC3_6_1_B,          AV_CH_LAYOUT_5POINT1 |
                                         AV_CH_TOP_CENTER },
    { MOV_CH_LAYOUT_EAC3_6_1_C,          AV_CH_LAYOUT_5POINT1 |
                                         AV_CH_TOP_FRONT_CENTER },
    { MOV_CH_LAYOUT_DTS_6_1_A,           AV_CH_LAYOUT_6POINT1_FRONT },
    { MOV_CH_LAYOUT_DTS_6_1_B,           AV_CH_LAYOUT_5POINT1_BACK |
                                         AV_CH_TOP_CENTER },
    { MOV_CH_LAYOUT_DTS_6_1_C,           AV_CH_LAYOUT_6POINT1_BACK },
    { 0, 0 },
}
Definition at line 247 of file mov_chan.c.
mov_ch_layout_map_8ch
const struct MovChannelLayoutMap mov_ch_layout_map_8ch[] static
Definition at line 275 of file mov_chan.c.
mov_ch_layout_map_9ch
const struct MovChannelLayoutMap mov_ch_layout_map_9ch[] static
Initial value:
= {
    { MOV_CH_LAYOUT_DTS_8_1_A,           AV_CH_LAYOUT_2_2            |
                                         AV_CH_BACK_LEFT             |
                                         AV_CH_BACK_RIGHT            |
                                         AV_CH_FRONT_LEFT_OF_CENTER  |
                                         AV_CH_FRONT_RIGHT_OF_CENTER |
                                         AV_CH_LOW_FREQUENCY },
    { MOV_CH_LAYOUT_DTS_8_1_B,           AV_CH_LAYOUT_7POINT1_WIDE   |
                                         AV_CH_BACK_CENTER },
    { 0, 0 },
}
Definition at line 334 of file mov_chan.c.
mov_ch_layout_map
const struct MovChannelLayoutMap* const mov_ch_layout_map[] static
Initial value:
= {
    mov_ch_layout_map_misc,
    mov_ch_layout_map_1ch,
    mov_ch_layout_map_2ch,
    mov_ch_layout_map_3ch,
    mov_ch_layout_map_4ch,
    mov_ch_layout_map_5ch,
    mov_ch_layout_map_6ch,
    mov_ch_layout_map_7ch,
    mov_ch_layout_map_8ch,
    mov_ch_layout_map_9ch,
}
Definition at line 347 of file mov_chan.c.
mov_ch_layouts_aac
enum MovChannelLayoutTag mov_ch_layouts_aac[] static
Initial value:
= {
    MOV_CH_LAYOUT_MONO,
    MOV_CH_LAYOUT_STEREO,
    MOV_CH_LAYOUT_AC3_1_0_1,
    MOV_CH_LAYOUT_MPEG_3_0_B,
    MOV_CH_LAYOUT_ITU_2_1,
    MOV_CH_LAYOUT_DVD_4,
    MOV_CH_LAYOUT_QUADRAPHONIC,
    MOV_CH_LAYOUT_MPEG_4_0_B,
    MOV_CH_LAYOUT_ITU_2_2,
    MOV_CH_LAYOUT_AC3_2_1_1,
    MOV_CH_LAYOUT_DTS_3_1,
    MOV_CH_LAYOUT_MPEG_5_0_D,
    MOV_CH_LAYOUT_DVD_18,
    MOV_CH_LAYOUT_DTS_4_1,
    MOV_CH_LAYOUT_MPEG_5_1_D,
    MOV_CH_LAYOUT_AAC_6_0,
    MOV_CH_LAYOUT_DTS_6_0_A,
    MOV_CH_LAYOUT_AAC_6_1,
    MOV_CH_LAYOUT_AAC_7_0,
    MOV_CH_LAYOUT_DTS_6_1_A,
    MOV_CH_LAYOUT_AAC_OCTAGONAL,
    MOV_CH_LAYOUT_MPEG_7_1_B,
    MOV_CH_LAYOUT_DTS_8_0_A,
    0,
}
Definition at line 360 of file mov_chan.c.
mov_ch_layouts_ac3
enum MovChannelLayoutTag mov_ch_layouts_ac3[] static
Initial value:
= {
    MOV_CH_LAYOUT_MONO,
    MOV_CH_LAYOUT_STEREO,
    MOV_CH_LAYOUT_AC3_1_0_1,
    MOV_CH_LAYOUT_AC3_3_0,
    MOV_CH_LAYOUT_ITU_2_1,
    MOV_CH_LAYOUT_DVD_4,
    MOV_CH_LAYOUT_AC3_3_1,
    MOV_CH_LAYOUT_ITU_2_2,
    MOV_CH_LAYOUT_AC3_2_1_1,
    MOV_CH_LAYOUT_AC3_3_0_1,
    MOV_CH_LAYOUT_MPEG_5_0_C,
    MOV_CH_LAYOUT_DVD_18,
    MOV_CH_LAYOUT_AC3_3_1_1,
    MOV_CH_LAYOUT_MPEG_5_1_C,
    0,
}
Definition at line 387 of file mov_chan.c.
mov_ch_layouts_alac
enum MovChannelLayoutTag mov_ch_layouts_alac[] static
Initial value:
= {
    MOV_CH_LAYOUT_MONO,
    MOV_CH_LAYOUT_STEREO,
    MOV_CH_LAYOUT_MPEG_3_0_B,
    MOV_CH_LAYOUT_MPEG_4_0_B,
    MOV_CH_LAYOUT_MPEG_5_0_D,
    MOV_CH_LAYOUT_MPEG_5_1_D,
    MOV_CH_LAYOUT_AAC_6_1,
    MOV_CH_LAYOUT_MPEG_7_1_B,
    0,
}
Definition at line 405 of file mov_chan.c.
mov_ch_layouts_wav
enum MovChannelLayoutTag mov_ch_layouts_wav[] static
Initial value:
= {
    MOV_CH_LAYOUT_MONO,
    MOV_CH_LAYOUT_STEREO,
    MOV_CH_LAYOUT_MATRIXSTEREO,
    MOV_CH_LAYOUT_MPEG_3_0_A,
    MOV_CH_LAYOUT_QUADRAPHONIC,
    MOV_CH_LAYOUT_MPEG_5_0_A,
    MOV_CH_LAYOUT_MPEG_5_1_A,
    MOV_CH_LAYOUT_MPEG_6_1_A,
    MOV_CH_LAYOUT_MPEG_7_1_A,
    MOV_CH_LAYOUT_MPEG_7_1_C,
    MOV_CH_LAYOUT_SMPTE_DTV,
    0,
}
Definition at line 417 of file mov_chan.c.
codec_id
enum AVCodecID codec_id
Definition at line 433 of file mov_chan.c.
layouts
enum MovChannelLayoutTag* layouts
Definition at line 434 of file mov_chan.c.
Referenced by aeval_query_formats(), asink_query_formats(), channelmap_query_formats(), compressor(), default_query_formats_common(), ff_mov_get_channel_layout_tag(), ff_mov_write_chan(), filter_frame(), gate(), join_query_formats(), and query_formats().
mov_codec_ch_layouts
const { ... } mov_codec_ch_layouts[]
Initial value:
= {
    { AV_CODEC_ID_AAC,     mov_ch_layouts_aac      },
    { AV_CODEC_ID_AC3,     mov_ch_layouts_ac3      },
    { AV_CODEC_ID_ALAC,    mov_ch_layouts_alac     },
    { AV_CODEC_ID_PCM_U8,    mov_ch_layouts_wav    },
    { AV_CODEC_ID_PCM_S8,    mov_ch_layouts_wav    },
    { AV_CODEC_ID_PCM_S16LE, mov_ch_layouts_wav    },
    { AV_CODEC_ID_PCM_S16BE, mov_ch_layouts_wav    },
    { AV_CODEC_ID_PCM_S24LE, mov_ch_layouts_wav    },
    { AV_CODEC_ID_PCM_S24BE, mov_ch_layouts_wav    },
    { AV_CODEC_ID_PCM_S32LE, mov_ch_layouts_wav    },
    { AV_CODEC_ID_PCM_S32BE, mov_ch_layouts_wav    },
    { AV_CODEC_ID_PCM_F32LE, mov_ch_layouts_wav    },
    { AV_CODEC_ID_PCM_F32BE, mov_ch_layouts_wav    },
    { AV_CODEC_ID_PCM_F64LE, mov_ch_layouts_wav    },
    { AV_CODEC_ID_PCM_F64BE, mov_ch_layouts_wav    },
    { AV_CODEC_ID_NONE,    NULL                    },
}
Referenced by ff_mov_get_channel_layout_tag().