FFmpeg: libavformat/mov_chan.h File Reference
mov_chan.h File Reference
#include <stdint.h>
#include "libavcodec/avcodec.h"
#include "avformat.h"
Functions
uint64_t ff_mov_get_channel_layout (uint32_t tag, uint32_t bitmap)
mov 'chan' tag reading/writing.
uint32_t ff_mov_get_channel_layout_tag (enum AVCodecID codec_id, uint64_t channel_layout, uint32_t *bitmap)
Get the channel layout tag for the specified codec id and channel layout.
int ff_mov_read_chan (AVFormatContext *s, AVIOContext *pb, AVStream *st, int64_t size)
Read 'chan' tag from the input stream.
Function Documentation
ff_mov_get_channel_layout()
uint64_t ff_mov_get_channel_layout (uint32_t tag, uint32_t bitmap)
mov 'chan' tag reading/writing.
Author
Justin Ruggles Get the channel layout for the specified channel layout tag.
Parameters
[in] tag channel layout tag
[out] bitmap channel bitmap (only used if needed)
Returns
channel layout
Definition at line 454 of file mov_chan.c.
Referenced by ff_mov_read_chan().
ff_mov_get_channel_layout_tag()
uint32_t ff_mov_get_channel_layout_tag (enum AVCodecID codec_id, uint64_t channel_layout, uint32_t * bitmap)
Get the channel layout tag for the specified codec id and channel layout.
If the layout tag was not found, use a channel bitmap if possible.
Parameters
[in] codec_id codec id
[in] channel_layout channel layout
[out] bitmap channel bitmap
Returns
channel layout tag
Definition at line 494 of file mov_chan.c.
Referenced by mov_write_chan_tag().
ff_mov_read_chan()
int ff_mov_read_chan (AVFormatContext * s, AVIOContext * pb, AVStream * st, int64_t size)
Read 'chan' tag from the input stream.
Parameters
s AVFormatContext
pb AVIOContext
st The stream to set codec values for
size Remaining size in the 'chan' tag
Returns
0 if ok, or negative AVERROR code on failure
Definition at line 547 of file mov_chan.c.
Referenced by aiff_read_header(), mov_read_chan(), and read_header().