FFmpeg: libavformat/mov.c File Reference
mov.c File Reference
#include <inttypes.h>
#include <limits.h>
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/channel_layout.h"
#include "libavutil/internal.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/intfloat.h"
#include "libavutil/mathematics.h"
#include "libavutil/time_internal.h"
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/dict.h"
#include "libavutil/display.h"
#include "libavutil/opt.h"
#include "libavutil/aes.h"
#include "libavutil/aes_ctr.h"
#include "libavutil/sha.h"
#include "libavutil/spherical.h"
#include "libavutil/stereo3d.h"
#include "libavutil/timecode.h"
#include "libavcodec/ac3tab.h"
#include "libavcodec/flac.h"
#include "libavcodec/mpegaudiodecheader.h"
#include "avformat.h"
#include "internal.h"
#include "avio_internal.h"
#include "riff.h"
#include "isom.h"
#include "libavcodec/get_bits.h"
#include "id3v1.h"
#include "mov_chan.h"
#include "replaygain.h"
#include "qtpalette.h"
Data Structures
struct MOVParseTableEntry
Macros
#define MIN_DATA_ENTRY_BOX_SIZE 12
#define DRM_BLOB_SIZE 56
#define ALAC_EXTRADATA_SIZE 36
#define IS_MATRIX_IDENT(matrix)
#define OFFSET(x) offsetof(MOVContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_DECODING_PARAM
Functions
static int mov_read_default (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_mfra (MOVContext *c, AVIOContext *f)
static int mov_metadata_track_or_disc_number (MOVContext *c, AVIOContext *pb, unsigned len, const char *key)
static int mov_metadata_int8_bypass_padding (MOVContext *c, AVIOContext *pb, unsigned len, const char *key)
static int mov_metadata_int8_no_padding (MOVContext *c, AVIOContext *pb, unsigned len, const char *key)
static int mov_metadata_gnre (MOVContext *c, AVIOContext *pb, unsigned len, const char *key)
static int mov_read_mac_string (MOVContext *c, AVIOContext *pb, int len, char *dst, int dstlen)
static int mov_read_covr (MOVContext *c, AVIOContext *pb, int type, int len)
static int mov_metadata_loci (MOVContext *c, AVIOContext *pb, unsigned len)
static int mov_metadata_hmmt (MOVContext *c, AVIOContext *pb, unsigned len)
static int mov_read_udta_string (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_chpl (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_dref (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_hdlr (MOVContext *c, AVIOContext *pb, MOVAtom atom)
int ff_mov_read_esds (AVFormatContext *fc, AVIOContext *pb)
static int mov_read_esds (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_dac3 (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_dec3 (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_ddts (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_chan (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_wfex (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_pasp (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_mdat (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_adrm (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int aax_filter (uint8_t *input, int size, MOVContext *c)
static int mov_read_ftyp (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_moov (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_moof (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static void mov_metadata_creation_time (AVDictionary **metadata, int64_t time)
static int mov_read_mdhd (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_mvhd (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_enda (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_colr (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_fiel (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_realloc_extradata (AVCodecParameters *par, MOVAtom atom)
static int64_t mov_read_atom_into_extradata (MOVContext *c, AVIOContext *pb, MOVAtom atom, AVCodecParameters *par, uint8_t *buf)
static int mov_read_extradata (MOVContext *c, AVIOContext *pb, MOVAtom atom, enum AVCodecID codec_id)
static int mov_read_alac (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_avss (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_jp2h (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_dpxe (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_avid (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_targa_y216 (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_ares (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_aclr (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_svq3 (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_wave (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_glbl (MOVContext *c, AVIOContext *pb, MOVAtom atom)
This function reads atom content and puts data in extradata without tag nor size unlike mov_read_extradata.
static int mov_read_dvc1 (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_strf (MOVContext *c, AVIOContext *pb, MOVAtom atom)
An strf atom is a BITMAPINFOHEADER struct.
static int mov_read_stco (MOVContext *c, AVIOContext *pb, MOVAtom atom)
enum AVCodecID ff_mov_get_lpcm_codec_id (int bps, int flags)
Compute codec id for 'lpcm' tag.
static int mov_codec_id (AVStream *st, uint32_t format)
static void mov_parse_stsd_video (MOVContext *c, AVIOContext *pb, AVStream *st, MOVStreamContext *sc)
static void mov_parse_stsd_audio (MOVContext *c, AVIOContext *pb, AVStream *st, MOVStreamContext *sc)
static void mov_parse_stsd_subtitle (MOVContext *c, AVIOContext *pb, AVStream *st, MOVStreamContext *sc, int64_t size)
static uint32_t yuv_to_rgba (uint32_t ycbcr)
static int mov_rewrite_dvd_sub_extradata (AVStream *st)
static int mov_parse_stsd_data (MOVContext *c, AVIOContext *pb, AVStream *st, MOVStreamContext *sc, int64_t size)
static int mov_finalize_stsd_codec (MOVContext *c, AVIOContext *pb, AVStream *st, MOVStreamContext *sc)
static int mov_skip_multiple_stsd (MOVContext *c, AVIOContext *pb, int codec_tag, int format, int64_t size)
int ff_mov_read_stsd_entries (MOVContext *c, AVIOContext *pb, int entries)
static int mov_read_stsd (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_stsc (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_get_stsc_samples (MOVStreamContext *sc, int index)
static int mov_read_stps (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_stss (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_stsz (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_stts (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static void mov_update_dts_shift (MOVStreamContext *sc, int duration)
static int mov_read_ctts (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_sbgp (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int get_edit_list_entry (MOVContext *mov, const MOVStreamContext *msc, unsigned int edit_list_index, int64_t *edit_list_media_time, int64_t *edit_list_duration, int64_t global_timescale)
Get ith edit list entry (media time, duration).
static int64_t find_prev_closest_index (AVStream *st, AVIndexEntry *e_old, int nb_old, int64_t timestamp, int flag)
Find the closest previous frame to the timestamp, in e_old index entries.
static int64_t add_index_entry (AVStream *st, int64_t pos, int64_t timestamp, int size, int distance, int flags)
Add index entry with the given values, to the end of st->index_entries.
static void fix_index_entry_timestamps (AVStream *st, int end_index, int64_t end_ts, int64_t *frame_duration_buffer, int frame_duration_buffer_size)
Rewrite timestamps of index entries in the range [end_index - frame_duration_buffer_size, end_index) by subtracting end_ts successively by the amounts given in frame_duration_buffer.
static int64_t add_ctts_entry (MOVStts **ctts_data, unsigned int *ctts_count, unsigned int *allocated_size, int count, int duration)
Append a new ctts entry to ctts_data.
static void mov_fix_index (MOVContext *mov, AVStream *st)
Fix st->index_entries, so that it contains only the entries (and the entries which are needed to decode them) that fall in the edit list time ranges.
static void mov_build_index (MOVContext *mov, AVStream *st)
static int test_same_origin (const char *src, const char *ref)
static int mov_open_dref (MOVContext *c, AVIOContext **pb, const char *src, MOVDref *ref)
static void fix_timescale (MOVContext *c, MOVStreamContext *sc)
static int mov_read_trak (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_ilst (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_keys (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_custom (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_meta (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_tkhd (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_tfhd (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_chap (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_trex (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_tfdt (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_trun (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_sidx (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_wide (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_cmov (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_elst (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_tmcd (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_st3d (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_sv3d (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_parse_uuid_spherical (MOVStreamContext *sc, AVIOContext *pb, size_t len)
static int mov_read_uuid (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_free (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_frma (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_senc (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_saiz (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int mov_read_dfla (MOVContext *c, AVIOContext *pb, MOVAtom atom)
static int cenc_filter (MOVContext *c, MOVStreamContext *sc, uint8_t *input, int size)
static int mov_seek_auxiliary_info (AVFormatContext *s, MOVStreamContext *sc)
static int mov_probe (AVProbeData *p)
static void mov_read_chapters (AVFormatContext *s)
static int parse_timecode_in_framenum_format (AVFormatContext *s, AVStream *st, uint32_t value, int flags)
static int mov_read_rtmd_track (AVFormatContext *s, AVStream *st)
static int mov_read_timecode_track (AVFormatContext *s, AVStream *st)
static int mov_read_close (AVFormatContext *s)
static int tmcd_is_referenced (AVFormatContext *s, int tmcd_id)
static void export_orphan_timecode (AVFormatContext *s)
static int read_tfra (MOVContext *mov, AVIOContext *f)
static int mov_read_header (AVFormatContext *s)
static AVIndexEntry * mov_find_next_sample (AVFormatContext *s, AVStream **st)
static int should_retry (AVIOContext *pb, int error_code)
static int mov_switch_root (AVFormatContext *s, int64_t target)
static int mov_change_extradata (MOVStreamContext *sc, AVPacket *pkt)
static int mov_read_packet (AVFormatContext *s, AVPacket *pkt)
static int mov_seek_fragment (AVFormatContext *s, AVStream *st, int64_t timestamp)
static int mov_seek_stream (AVFormatContext *s, AVStream *st, int64_t timestamp, int flags)
static int mov_read_seek (AVFormatContext *s, int stream_index, int64_t sample_time, int flags)
Variables
static const uint32_t mac_to_unicode [128]
static const MOVParseTableEntry mov_default_parse_table []
static const AVOption mov_options []
static const AVClass mov_class
AVInputFormat ff_mov_demuxer
Macro Definition Documentation
MIN_DATA_ENTRY_BOX_SIZE
#define MIN_DATA_ENTRY_BOX_SIZE 12
Definition at line 563 of file mov.c.
Referenced by mov_read_dref().
DRM_BLOB_SIZE
#define DRM_BLOB_SIZE 56
Definition at line 993 of file mov.c.
Referenced by mov_read_adrm().
ALAC_EXTRADATA_SIZE
#define ALAC_EXTRADATA_SIZE 36
Referenced by mov_read_wave().
IS_MATRIX_IDENT
#define IS_MATRIX_IDENT (matrix)
Value:
((matrix)[0][0] == (1 << 16) &&       \
      (matrix)[1][1] == (1 << 16) &&       \
      (matrix)[2][2] == (1 << 30) &&       \
     !(matrix)[0][1] && !(matrix)[0][2] && \
     !(matrix)[1][0] && !(matrix)[1][2] && \
     !(matrix)[2][0] && !(matrix)[2][1])
Definition at line 3858 of file mov.c.
Referenced by mov_read_tkhd().
OFFSET
#define OFFSET (x) offsetof(MOVContext, x)
Definition at line 6339 of file mov.c.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_DECODING_PARAM
Definition at line 6340 of file mov.c.
Function Documentation
mov_read_default()
static int mov_read_default (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 5201 of file mov.c.
Referenced by ff_mov_read_stsd_entries(), mov_read_cmov(), mov_read_glbl(), mov_read_header(), mov_read_ilst(), mov_read_meta(), mov_read_moof(), mov_read_moov(), mov_read_trak(), mov_read_wave(), and mov_switch_root().
mov_read_mfra()
static int mov_read_mfra (MOVContext * c, AVIOContext * f) static
Definition at line 5745 of file mov.c.
Referenced by mov_read_moof().
mov_metadata_track_or_disc_number()
static int mov_metadata_track_or_disc_number (MOVContext * c, AVIOContext * pb, unsigned len, const char * key) static
Definition at line 77 of file mov.c.
Referenced by mov_read_udta_string().
mov_metadata_int8_bypass_padding()
static int mov_metadata_int8_bypass_padding (MOVContext * c, AVIOContext * pb, unsigned len, const char * key) static
Definition at line 97 of file mov.c.
Referenced by mov_read_udta_string().
mov_metadata_int8_no_padding()
static int mov_metadata_int8_no_padding (MOVContext * c, AVIOContext * pb, unsigned len, const char * key) static
Definition at line 111 of file mov.c.
Referenced by mov_read_udta_string().
mov_metadata_gnre()
static int mov_metadata_gnre (MOVContext * c, AVIOContext * pb, unsigned len, const char * key) static
Definition at line 120 of file mov.c.
Referenced by mov_read_udta_string().
mov_read_mac_string()
static int mov_read_mac_string (MOVContext * c, AVIOContext * pb, int len, char * dst, int dstlen) static
Definition at line 155 of file mov.c.
Referenced by mov_parse_stsd_video(), and mov_read_udta_string().
mov_read_covr()
static int mov_read_covr (MOVContext * c, AVIOContext * pb, int type, int len) static
Definition at line 173 of file mov.c.
Referenced by mov_read_udta_string().
mov_metadata_loci()
static int mov_metadata_loci (MOVContext * c, AVIOContext * pb, unsigned len) static
Definition at line 224 of file mov.c.
Referenced by mov_read_udta_string().
mov_metadata_hmmt()
static int mov_metadata_hmmt (MOVContext * c, AVIOContext * pb, unsigned len) static
Definition at line 274 of file mov.c.
Referenced by mov_read_udta_string().
mov_read_udta_string()
static int mov_read_udta_string (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 291 of file mov.c.
Referenced by mov_read_default().
mov_read_chpl()
static int mov_read_chpl (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 525 of file mov.c.
mov_read_dref()
static int mov_read_dref (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 564 of file mov.c.
mov_read_hdlr()
static int mov_read_hdlr (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 702 of file mov.c.
ff_mov_read_esds()
int ff_mov_read_esds (AVFormatContext * fc, AVIOContext * pb)
Definition at line 765 of file mov.c.
Referenced by mov_read_esds(), and read_kuki_chunk().
mov_read_esds()
static int mov_read_esds (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 787 of file mov.c.
mov_read_dac3()
static int mov_read_dac3 (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 792 of file mov.c.
mov_read_dec3()
static int mov_read_dec3 (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 828 of file mov.c.
mov_read_ddts()
static int mov_read_ddts (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 868 of file mov.c.
mov_read_chan()
static int mov_read_chan (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 927 of file mov.c.
mov_read_wfex()
static int mov_read_wfex (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 946 of file mov.c.
mov_read_pasp()
static int mov_read_pasp (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 961 of file mov.c.
mov_read_mdat()
static int mov_read_mdat (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 985 of file mov.c.
Referenced by mov_read_wide().
mov_read_adrm()
static int mov_read_adrm (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 995 of file mov.c.
aax_filter()
static int aax_filter (uint8_t * input, int size, MOVContext * c) static
Definition at line 1094 of file mov.c.
Referenced by mov_read_packet().
mov_read_ftyp()
static int mov_read_ftyp (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 1108 of file mov.c.
mov_read_moov()
static int mov_read_moov (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 1145 of file mov.c.
mov_read_moof()
static int mov_read_moof (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 1163 of file mov.c.
mov_metadata_creation_time()
static void mov_metadata_creation_time (AVDictionary ** metadata, int64_t time) static
Definition at line 1185 of file mov.c.
Referenced by mov_read_mdhd(), and mov_read_mvhd().
mov_read_mdhd()
static int mov_read_mdhd (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 1194 of file mov.c.
mov_read_mvhd()
static int mov_read_mvhd (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 1243 of file mov.c.
mov_read_enda()
static int mov_read_enda (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 1294 of file mov.c.
mov_read_colr()
static int mov_read_colr (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 1326 of file mov.c.
mov_read_fiel()
static int mov_read_fiel (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 1377 of file mov.c.
mov_realloc_extradata()
static int mov_realloc_extradata (AVCodecParameters * par, MOVAtom atom) static
Definition at line 1411 of file mov.c.
Referenced by mov_read_aclr(), and mov_read_extradata().
mov_read_atom_into_extradata()
static int64_t mov_read_atom_into_extradata (MOVContext * c, AVIOContext * pb, MOVAtom atom, AVCodecParameters * par, uint8_t * buf) static
Definition at line 1426 of file mov.c.
Referenced by mov_read_aclr(), and mov_read_extradata().
mov_read_extradata()
static int mov_read_extradata (MOVContext * c, AVIOContext * pb, MOVAtom atom, enum AVCodecID codec_id) static
Definition at line 1448 of file mov.c.
Referenced by mov_read_alac(), mov_read_avid(), mov_read_avss(), mov_read_dpxe(), mov_read_jp2h(), mov_read_svq3(), and mov_read_targa_y216().
mov_read_alac()
static int mov_read_alac (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 1474 of file mov.c.
mov_read_avss()
static int mov_read_avss (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 1479 of file mov.c.
mov_read_jp2h()
static int mov_read_jp2h (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 1484 of file mov.c.
mov_read_dpxe()
static int mov_read_dpxe (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 1489 of file mov.c.
mov_read_avid()
static int mov_read_avid (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 1494 of file mov.c.
Referenced by mov_read_ares().
mov_read_targa_y216()
static int mov_read_targa_y216 (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 1502 of file mov.c.
mov_read_ares()
static int mov_read_ares (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 1516 of file mov.c.
mov_read_aclr()
static int mov_read_aclr (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 1556 of file mov.c.
mov_read_svq3()
static int mov_read_svq3 (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 1599 of file mov.c.
mov_read_wave()
static int mov_read_wave (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 1604 of file mov.c.
mov_read_glbl()
static int mov_read_glbl (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
This function reads atom content and puts data in extradata without tag nor size unlike mov_read_extradata.
Definition at line 1662 of file mov.c.
Referenced by mov_parse_stsd_subtitle().
mov_read_dvc1()
static int mov_read_dvc1 (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 1695 of file mov.c.
mov_read_strf()
static int mov_read_strf (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
An strf atom is a BITMAPINFOHEADER struct.
This struct is 40 bytes itself, but can have extradata appended at the end after the 40 bytes belonging to the struct.
Definition at line 1726 of file mov.c.
mov_read_stco()
static int mov_read_stco (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 1749 of file mov.c.
ff_mov_get_lpcm_codec_id()
enum AVCodecID ff_mov_get_lpcm_codec_id (int bps, int flags)
Compute codec id for 'lpcm' tag.
See CoreAudioTypes and AudioStreamBasicDescription at Apple.
Definition at line 1798 of file mov.c.
Referenced by mov_parse_stsd_audio(), and read_desc_chunk().
mov_codec_id()
static int mov_codec_id (AVStream * st, uint32_t format) static
Definition at line 1808 of file mov.c.
Referenced by ff_mov_read_stsd_entries(), mov_parse_stsd_audio(), and mov_read_frma().
mov_parse_stsd_video()
static void mov_parse_stsd_video (MOVContext * c, AVIOContext * pb, AVStream * st, MOVStreamContext * sc) static
Definition at line 1841 of file mov.c.
Referenced by ff_mov_read_stsd_entries().
mov_parse_stsd_audio()
static void mov_parse_stsd_audio (MOVContext * c, AVIOContext * pb, AVStream * st, MOVStreamContext * sc) static
Definition at line 1897 of file mov.c.
Referenced by ff_mov_read_stsd_entries().
mov_parse_stsd_subtitle()
static void mov_parse_stsd_subtitle (MOVContext * c, AVIOContext * pb, AVStream * st, MOVStreamContext * sc, int64_t size) static
Definition at line 2006 of file mov.c.
Referenced by ff_mov_read_stsd_entries().
yuv_to_rgba()
static uint32_t yuv_to_rgba (uint32_t ycbcr) static
Definition at line 2020 of file mov.c.
Referenced by mov_rewrite_dvd_sub_extradata().
mov_rewrite_dvd_sub_extradata()
static int mov_rewrite_dvd_sub_extradata (AVStream * st) static
Definition at line 2036 of file mov.c.
Referenced by mov_read_header().
mov_parse_stsd_data()
static int mov_parse_stsd_data (MOVContext * c, AVIOContext * pb, AVStream * st, MOVStreamContext * sc, int64_t size) static
Definition at line 2071 of file mov.c.
Referenced by ff_mov_read_stsd_entries().
mov_finalize_stsd_codec()
static int mov_finalize_stsd_codec (MOVContext * c, AVIOContext * pb, AVStream * st, MOVStreamContext * sc) static
Definition at line 2137 of file mov.c.
Referenced by mov_read_stsd().
mov_skip_multiple_stsd()
static int mov_skip_multiple_stsd (MOVContext * c, AVIOContext * pb, int codec_tag, int format, int64_t size) static
Definition at line 2215 of file mov.c.
Referenced by ff_mov_read_stsd_entries().
ff_mov_read_stsd_entries()
int ff_mov_read_stsd_entries (MOVContext * c, AVIOContext * pb, int entries)
Definition at line 2243 of file mov.c.
Referenced by mov_read_stsd(), and qt_rtp_parse_packet().
mov_read_stsd()
static int mov_read_stsd (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 2338 of file mov.c.
mov_read_stsc()
static int mov_read_stsc (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 2393 of file mov.c.
mov_get_stsc_samples()
static int mov_get_stsc_samples (MOVStreamContext * sc, int index) inline static
Definition at line 2436 of file mov.c.
Referenced by mov_read_packet(), and mov_seek_stream().
mov_read_stps()
static int mov_read_stps (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 2448 of file mov.c.
mov_read_stss()
static int mov_read_stss (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 2483 of file mov.c.
mov_read_stsz()
static int mov_read_stsz (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 2531 of file mov.c.
mov_read_stts()
static int mov_read_stts (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 2616 of file mov.c.
mov_update_dts_shift()
static void mov_update_dts_shift (MOVStreamContext * sc, int duration) static
Definition at line 2686 of file mov.c.
Referenced by mov_read_ctts(), and mov_read_trun().
mov_read_ctts()
static int mov_read_ctts (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 2697 of file mov.c.
mov_read_sbgp()
static int mov_read_sbgp (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 2762 of file mov.c.
get_edit_list_entry()
static int get_edit_list_entry (MOVContext * mov, const MOVStreamContext * msc, unsigned int edit_list_index, int64_t * edit_list_media_time, int64_t * edit_list_duration, int64_t global_timescale) static
Get ith edit list entry (media time, duration).
Definition at line 2807 of file mov.c.
Referenced by mov_fix_index().
find_prev_closest_index()
static int64_t find_prev_closest_index (AVStream * st, AVIndexEntry * e_old, int nb_old, int64_t timestamp, int flag) static
Find the closest previous frame to the timestamp, in e_old index entries.
Searching for just any frame / just key frames can be controlled by last argument 'flag'. Returns the index of the entry in st->index_entries if successful, else returns -1.
Definition at line 2837 of file mov.c.
Referenced by mov_fix_index().
add_index_entry()
static int64_t add_index_entry (AVStream * st, int64_t pos, int64_t timestamp, int size, int distance, int flags) static
Add index entry with the given values, to the end of st->index_entries.
Returns the new size st->index_entries if successful, else returns -1.
This function is similar to ff_add_index_entry in libavformat/utils.c except that here we are always unconditionally adding an index entry to the end, instead of searching the entries list and skipping the add if there is an existing entry with the same timestamp. This is needed because the mov_fix_index calls this func with the same unincremented timestamp for successive discarded frames.
Definition at line 2868 of file mov.c.
Referenced by mov_fix_index().
fix_index_entry_timestamps()
static void fix_index_entry_timestamps (AVStream * st, int end_index, int64_t end_ts, int64_t * frame_duration_buffer, int frame_duration_buffer_size) static
Rewrite timestamps of index entries in the range [end_index - frame_duration_buffer_size, end_index) by subtracting end_ts successively by the amounts given in frame_duration_buffer.
Definition at line 2908 of file mov.c.
Referenced by mov_fix_index().
add_ctts_entry()
static int64_t add_ctts_entry (MOVStts ** ctts_data, unsigned int * ctts_count, unsigned int * allocated_size, int count, int duration) static
Append a new ctts entry to ctts_data.
Returns the new ctts_count if successful, else returns -1.
Definition at line 2923 of file mov.c.
Referenced by mov_fix_index().
mov_fix_index()
static void mov_fix_index (MOVContext * mov, AVStream * st) static
Fix st->index_entries, so that it contains only the entries (and the entries which are needed to decode them) that fall in the edit list time ranges.
Also fixes the timestamps of the index entries to match the timeline specified the edit lists.
Definition at line 2956 of file mov.c.
Referenced by mov_build_index().
mov_build_index()
static void mov_build_index (MOVContext * mov, AVStream * st) static
Definition at line 3217 of file mov.c.
Referenced by mov_read_trak().
test_same_origin()
static int test_same_origin (const char * src, const char * ref) static
Definition at line 3489 of file mov.c.
Referenced by mov_open_dref().
mov_open_dref()
static int mov_open_dref (MOVContext * c, AVIOContext ** pb, const char * src, MOVDref * ref) static
Definition at line 3518 of file mov.c.
Referenced by mov_read_trak().
fix_timescale()
static void fix_timescale (MOVContext * c, MOVStreamContext * sc) static
Definition at line 3590 of file mov.c.
Referenced by mov_read_header(), and mov_read_trak().
mov_read_trak()
static int mov_read_trak (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 3600 of file mov.c.
mov_read_ilst()
static int mov_read_ilst (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 3716 of file mov.c.
mov_read_keys()
static int mov_read_keys (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 3725 of file mov.c.
Referenced by mov_read_default().
mov_read_custom()
static int mov_read_custom (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 3767 of file mov.c.
mov_read_meta()
static int mov_read_meta (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 3843 of file mov.c.
mov_read_tkhd()
static int mov_read_tkhd (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 3866 of file mov.c.
mov_read_tfhd()
static int mov_read_tfhd (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 3977 of file mov.c.
mov_read_chap()
static int mov_read_chap (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 4044 of file mov.c.
mov_read_trex()
static int mov_read_trex (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 4063 of file mov.c.
mov_read_tfdt()
static int mov_read_tfdt (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 4089 of file mov.c.
mov_read_trun()
static int mov_read_trun (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 4119 of file mov.c.
mov_read_sidx()
static int mov_read_sidx (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 4250 of file mov.c.
mov_read_wide()
static int mov_read_wide (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 4371 of file mov.c.
mov_read_cmov()
static int mov_read_cmov (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 4391 of file mov.c.
mov_read_elst()
static int mov_read_elst (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 4444 of file mov.c.
mov_read_tmcd()
static int mov_read_tmcd (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 4494 of file mov.c.
mov_read_st3d()
static int mov_read_st3d (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 4505 of file mov.c.
mov_read_sv3d()
static int mov_read_sv3d (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 4548 of file mov.c.
mov_parse_uuid_spherical()
static int mov_parse_uuid_spherical (MOVStreamContext * sc, AVIOContext * pb, size_t len) static
Definition at line 4637 of file mov.c.
Referenced by mov_read_uuid().
mov_read_uuid()
static int mov_read_uuid (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 4699 of file mov.c.
mov_read_free()
static int mov_read_free (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 4812 of file mov.c.
mov_read_frma()
static int mov_read_frma (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 4834 of file mov.c.
mov_read_senc()
static int mov_read_senc (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 4875 of file mov.c.
mov_read_saiz()
static int mov_read_saiz (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 4928 of file mov.c.
mov_read_dfla()
static int mov_read_dfla (MOVContext * c, AVIOContext * pb, MOVAtom atom) static
Definition at line 4984 of file mov.c.
cenc_filter()
static int cenc_filter (MOVContext * c, MOVStreamContext * sc, uint8_t * input, int size) static
Definition at line 5021 of file mov.c.
Referenced by mov_read_packet().
mov_seek_auxiliary_info()
static int mov_seek_auxiliary_info (AVFormatContext * s, MOVStreamContext * sc) static
Definition at line 5087 of file mov.c.
Referenced by mov_seek_stream().
mov_probe()
static int mov_probe (AVProbeData * p) static
Definition at line 5322 of file mov.c.
mov_read_chapters()
static void mov_read_chapters (AVFormatContext * s) static
Definition at line 5406 of file mov.c.
Referenced by mov_read_header().
parse_timecode_in_framenum_format()
static int parse_timecode_in_framenum_format (AVFormatContext * s, AVStream * st, uint32_t value, int flags) static
Definition at line 5507 of file mov.c.
Referenced by mov_read_timecode_track().
mov_read_rtmd_track()
static int mov_read_rtmd_track (AVFormatContext * s, AVStream * st) static
Definition at line 5521 of file mov.c.
Referenced by mov_read_header().
mov_read_timecode_track()
static int mov_read_timecode_track (AVFormatContext * s, AVStream * st) static
Definition at line 5546 of file mov.c.
Referenced by mov_read_header().
mov_read_close()
static int mov_read_close (AVFormatContext * s) static
Definition at line 5574 of file mov.c.
Referenced by mov_read_header().
tmcd_is_referenced()
static int tmcd_is_referenced (AVFormatContext * s, int tmcd_id) static
Definition at line 5650 of file mov.c.
Referenced by export_orphan_timecode().
export_orphan_timecode()
static void export_orphan_timecode (AVFormatContext * s) static
Definition at line 5666 of file mov.c.
Referenced by mov_read_header().
read_tfra()
static int read_tfra (MOVContext * mov, AVIOContext * f) static
Definition at line 5684 of file mov.c.
Referenced by mov_read_mfra().
mov_read_header()
static int mov_read_header (AVFormatContext * s) static
Definition at line 5790 of file mov.c.
mov_find_next_sample()
static AVIndexEntry* mov_find_next_sample (AVFormatContext * s, AVStream ** st) static
Definition at line 5978 of file mov.c.
Referenced by mov_read_packet(), and mov_read_seek().
should_retry()
static int should_retry (AVIOContext * pb, int error_code) static
Definition at line 6004 of file mov.c.
Referenced by mov_read_packet().
mov_switch_root()
static int mov_switch_root (AVFormatContext * s, int64_t target) static
Definition at line 6011 of file mov.c.
Referenced by mov_read_packet(), and mov_seek_fragment().
mov_change_extradata()
static int mov_change_extradata (MOVStreamContext * sc, AVPacket * pkt) static
Definition at line 6057 of file mov.c.
Referenced by mov_read_packet().
mov_read_packet()
static int mov_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 6080 of file mov.c.
mov_seek_fragment()
static int mov_seek_fragment (AVFormatContext * s, AVStream * st, int64_t timestamp) static
Definition at line 6209 of file mov.c.
Referenced by mov_seek_stream().
mov_seek_stream()
static int mov_seek_stream (AVFormatContext * s, AVStream * st, int64_t timestamp, int flags) static
Definition at line 6235 of file mov.c.
Referenced by mov_read_seek().
mov_read_seek()
static int mov_read_seek (AVFormatContext * s, int stream_index, int64_t sample_time, int flags) static
Definition at line 6287 of file mov.c.
Variable Documentation
mac_to_unicode
const uint32_t mac_to_unicode[128] static
Initial value:
= {
    0x00C4,0x00C5,0x00C7,0x00C9,0x00D1,0x00D6,0x00DC,0x00E1,
    0x00E0,0x00E2,0x00E4,0x00E3,0x00E5,0x00E7,0x00E9,0x00E8,
    0x00EA,0x00EB,0x00ED,0x00EC,0x00EE,0x00EF,0x00F1,0x00F3,
    0x00F2,0x00F4,0x00F6,0x00F5,0x00FA,0x00F9,0x00FB,0x00FC,
    0x2020,0x00B0,0x00A2,0x00A3,0x00A7,0x2022,0x00B6,0x00DF,
    0x00AE,0x00A9,0x2122,0x00B4,0x00A8,0x2260,0x00C6,0x00D8,
    0x221E,0x00B1,0x2264,0x2265,0x00A5,0x00B5,0x2202,0x2211,
    0x220F,0x03C0,0x222B,0x00AA,0x00BA,0x03A9,0x00E6,0x00F8,
    0x00BF,0x00A1,0x00AC,0x221A,0x0192,0x2248,0x2206,0x00AB,
    0x00BB,0x2026,0x00A0,0x00C0,0x00C3,0x00D5,0x0152,0x0153,
    0x2013,0x2014,0x201C,0x201D,0x2018,0x2019,0x00F7,0x25CA,
    0x00FF,0x0178,0x2044,0x20AC,0x2039,0x203A,0xFB01,0xFB02,
    0x2021,0x00B7,0x201A,0x201E,0x2030,0x00C2,0x00CA,0x00C1,
    0x00CB,0x00C8,0x00CD,0x00CE,0x00CF,0x00CC,0x00D3,0x00D4,
    0xF8FF,0x00D2,0x00DA,0x00DB,0x00D9,0x0131,0x02C6,0x02DC,
    0x00AF,0x02D8,0x02D9,0x02DA,0x00B8,0x02DD,0x02DB,0x02C7,
}
Definition at line 136 of file mov.c.
Referenced by mov_read_mac_string().
mov_default_parse_table
const MOVParseTableEntry mov_default_parse_table[] static
Definition at line 5117 of file mov.c.
mov_options
const AVOption mov_options[] static
Definition at line 6341 of file mov.c.
mov_class
const AVClass mov_class static
Initial value:
= {
    .class_name = "mov,mp4,m4a,3gp,3g2,mj2",
    .item_name  = av_default_item_name,
    .option     = mov_options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 6382 of file mov.c.
ff_mov_demuxer
AVInputFormat ff_mov_demuxer
Initial value:
= {
    .name           = "mov,mp4,m4a,3gp,3g2,mj2",
    .long_name      = NULL_IF_CONFIG_SMALL("QuickTime / MOV"),
    .priv_class     = &mov_class,
    .priv_data_size = sizeof(MOVContext),
    .extensions     = "mov,mp4,m4a,3gp,3g2,mj2",
    .read_probe     = mov_probe,
    .read_header    = mov_read_header,
    .read_packet    = mov_read_packet,
    .read_close     = mov_read_close,
    .read_seek      = mov_read_seek,
    .flags          = AVFMT_NO_BYTE_SEEK,
}
Definition at line 6389 of file mov.c.