FFmpeg: libavformat/movenc.c File Reference
movenc.c File Reference
#include <stdint.h>
#include <inttypes.h>
#include "movenc.h"
#include "avformat.h"
#include "avio_internal.h"
#include "riff.h"
#include "avio.h"
#include "isom.h"
#include "avc.h"
#include "libavcodec/ac3_parser.h"
#include "libavcodec/dnxhddata.h"
#include "libavcodec/flac.h"
#include "libavcodec/get_bits.h"
#include "libavcodec/put_bits.h"
#include "libavcodec/vc1_common.h"
#include "libavcodec/raw.h"
#include "internal.h"
#include "libavutil/avstring.h"
#include "libavutil/intfloat.h"
#include "libavutil/mathematics.h"
#include "libavutil/libm.h"
#include "libavutil/opt.h"
#include "libavutil/dict.h"
#include "libavutil/pixdesc.h"
#include "libavutil/timecode.h"
#include "libavutil/color_utils.h"
#include "hevc.h"
#include "rtpenc.h"
#include "mov_chan.h"
#include "vpcc.h"
Data Structures
struct eac3_info
Macros
#define MOV_CLASS(flavor)
#define READ_BLOCK
Functions
static int get_moov_size (AVFormatContext *s)
static int utf8len (const uint8_t *b)
static int64_t update_size (AVIOContext *pb, int64_t pos)
static int co64_required (const MOVTrack *track)
static int mov_write_stco_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_stsz_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_stsc_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_stss_tag (AVIOContext *pb, MOVTrack *track, uint32_t flag)
static int mov_write_amr_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_ac3_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_eac3_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_extradata_tag (AVIOContext *pb, MOVTrack *track)
This function writes extradata "as is".
static int mov_write_enda_tag (AVIOContext *pb)
static int mov_write_enda_tag_be (AVIOContext *pb)
static void put_descr (AVIOContext *pb, int tag, unsigned int size)
static unsigned compute_avg_bitrate (MOVTrack *track)
static int mov_write_esds_tag (AVIOContext *pb, MOVTrack *track)
static int mov_pcm_le_gt16 (enum AVCodecID codec_id)
static int mov_pcm_be_gt16 (enum AVCodecID codec_id)
static int mov_write_ms_tag (AVFormatContext *s, AVIOContext *pb, MOVTrack *track)
static int mov_write_wfex_tag (AVFormatContext *s, AVIOContext *pb, MOVTrack *track)
static int mov_write_dfla_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_chan_tag (AVFormatContext *s, AVIOContext *pb, MOVTrack *track)
static int mov_write_wave_tag (AVFormatContext *s, AVIOContext *pb, MOVTrack *track)
static int mov_write_dvc1_structs (MOVTrack *track, uint8_t *buf)
static int mov_write_dvc1_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_glbl_tag (AVIOContext *pb, MOVTrack *track)
static int mov_get_lpcm_flags (enum AVCodecID codec_id)
Compute flags for 'lpcm' tag.
static int get_cluster_duration (MOVTrack *track, int cluster_idx)
static int get_samples_per_packet (MOVTrack *track)
static int mov_write_audio_tag (AVFormatContext *s, AVIOContext *pb, MOVMuxContext *mov, MOVTrack *track)
static int mov_write_d263_tag (AVIOContext *pb)
static int mov_write_avcc_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_vpcc_tag (AVFormatContext *s, AVIOContext *pb, MOVTrack *track)
static int mov_write_hvcc_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_avid_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_dpxe_tag (AVIOContext *pb, MOVTrack *track)
static int mp4_get_codec_tag (AVFormatContext *s, MOVTrack *track)
static int ipod_get_codec_tag (AVFormatContext *s, MOVTrack *track)
static int mov_get_dv_codec_tag (AVFormatContext *s, MOVTrack *track)
static AVRational find_fps (AVFormatContext *s, AVStream *st)
static int mov_get_mpeg2_xdcam_codec_tag (AVFormatContext *s, MOVTrack *track)
static int mov_get_h264_codec_tag (AVFormatContext *s, MOVTrack *track)
static int mov_get_dnxhd_codec_tag (AVFormatContext *s, MOVTrack *track)
static int mov_get_rawvideo_codec_tag (AVFormatContext *s, MOVTrack *track)
static int mov_get_codec_tag (AVFormatContext *s, MOVTrack *track)
static int mov_find_codec_tag (AVFormatContext *s, MOVTrack *track)
static int mov_write_uuid_tag_ipod (AVIOContext *pb)
Write uuid atom.
static int mov_write_fiel_tag (AVIOContext *pb, MOVTrack *track, int field_order)
static int mov_write_subtitle_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_pasp_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_gama_tag (AVIOContext *pb, MOVTrack *track, double gamma)
static int mov_write_colr_tag (AVIOContext *pb, MOVTrack *track)
static void find_compressor (char *compressor_name, int len, MOVTrack *track)
static int mov_write_video_tag (AVIOContext *pb, MOVMuxContext *mov, MOVTrack *track)
static int mov_write_rtp_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_source_reference_tag (AVIOContext *pb, MOVTrack *track, const char *reel_name)
static int mov_write_tmcd_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_stsd_tag (AVFormatContext *s, AVIOContext *pb, MOVMuxContext *mov, MOVTrack *track)
static int mov_write_ctts_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_stts_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_dref_tag (AVIOContext *pb)
static int mov_write_stbl_tag (AVFormatContext *s, AVIOContext *pb, MOVMuxContext *mov, MOVTrack *track)
static int mov_write_dinf_tag (AVIOContext *pb)
static int mov_write_nmhd_tag (AVIOContext *pb)
static int mov_write_tcmi_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_gmhd_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_smhd_tag (AVIOContext *pb)
static int mov_write_vmhd_tag (AVIOContext *pb)
static int is_clcp_track (MOVTrack *track)
static int mov_write_hdlr_tag (AVFormatContext *s, AVIOContext *pb, MOVTrack *track)
static int mov_write_hmhd_tag (AVIOContext *pb)
static int mov_write_minf_tag (AVFormatContext *s, AVIOContext *pb, MOVMuxContext *mov, MOVTrack *track)
static int mov_write_mdhd_tag (AVIOContext *pb, MOVMuxContext *mov, MOVTrack *track)
static int mov_write_mdia_tag (AVFormatContext *s, AVIOContext *pb, MOVMuxContext *mov, MOVTrack *track)
static void write_matrix (AVIOContext *pb, int16_t a, int16_t b, int16_t c, int16_t d, int16_t tx, int16_t ty)
static int mov_write_tkhd_tag (AVIOContext *pb, MOVMuxContext *mov, MOVTrack *track, AVStream *st)
static int mov_write_tapt_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_edts_tag (AVIOContext *pb, MOVMuxContext *mov, MOVTrack *track)
static int mov_write_tref_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_uuid_tag_psp (AVIOContext *pb, MOVTrack *mov)
static int mov_write_udta_sdp (AVIOContext *pb, MOVTrack *track)
static int mov_write_track_metadata (AVIOContext *pb, AVStream *st, const char *tag, const char *str)
static int mov_write_track_udta_tag (AVIOContext *pb, MOVMuxContext *mov, AVStream *st)
static int mov_write_trak_tag (AVFormatContext *s, AVIOContext *pb, MOVMuxContext *mov, MOVTrack *track, AVStream *st)
static int mov_write_iods_tag (AVIOContext *pb, MOVMuxContext *mov)
static int mov_write_trex_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_mvex_tag (AVIOContext *pb, MOVMuxContext *mov)
static int mov_write_mvhd_tag (AVIOContext *pb, MOVMuxContext *mov)
static int mov_write_itunes_hdlr_tag (AVIOContext *pb, MOVMuxContext *mov, AVFormatContext *s)
static int mov_write_string_data_tag (AVIOContext *pb, const char *data, int lang, int long_style)
static int mov_write_string_tag (AVIOContext *pb, const char *name, const char *value, int lang, int long_style)
static AVDictionaryEntry * get_metadata_lang (AVFormatContext *s, const char *tag, int *lang)
static int mov_write_string_metadata (AVFormatContext *s, AVIOContext *pb, const char *name, const char *tag, int long_style)
static int mov_write_tmpo_tag (AVIOContext *pb, AVFormatContext *s)
static int mov_write_loci_tag (AVFormatContext *s, AVIOContext *pb)
static int mov_write_trkn_tag (AVIOContext *pb, MOVMuxContext *mov, AVFormatContext *s, int disc)
static int mov_write_int8_metadata (AVFormatContext *s, AVIOContext *pb, const char *name, const char *tag, int len)
static int mov_write_ilst_tag (AVIOContext *pb, MOVMuxContext *mov, AVFormatContext *s)
static int mov_write_mdta_hdlr_tag (AVIOContext *pb, MOVMuxContext *mov, AVFormatContext *s)
static int mov_write_mdta_keys_tag (AVIOContext *pb, MOVMuxContext *mov, AVFormatContext *s)
static int mov_write_mdta_ilst_tag (AVIOContext *pb, MOVMuxContext *mov, AVFormatContext *s)
static int mov_write_meta_tag (AVIOContext *pb, MOVMuxContext *mov, AVFormatContext *s)
static int mov_write_raw_metadata_tag (AVFormatContext *s, AVIOContext *pb, const char *name, const char *key)
static int ascii_to_wc (AVIOContext *pb, const uint8_t *b)
static uint16_t language_code (const char *str)
static int mov_write_3gp_udta_tag (AVIOContext *pb, AVFormatContext *s, const char *tag, const char *str)
static int mov_write_chpl_tag (AVIOContext *pb, AVFormatContext *s)
static int mov_write_udta_tag (AVIOContext *pb, MOVMuxContext *mov, AVFormatContext *s)
static void mov_write_psp_udta_tag (AVIOContext *pb, const char *str, const char *lang, int type)
static int mov_write_uuidusmt_tag (AVIOContext *pb, AVFormatContext *s)
static void build_chunks (MOVTrack *trk)
static int mov_setup_track_ids (MOVMuxContext *mov, AVFormatContext *s)
Assign track ids.
static int mov_write_moov_tag (AVIOContext *pb, MOVMuxContext *mov, AVFormatContext *s)
static void param_write_int (AVIOContext *pb, const char *name, int value)
static void param_write_string (AVIOContext *pb, const char *name, const char *value)
static void param_write_hex (AVIOContext *pb, const char *name, const uint8_t *value, int len)
static int mov_write_isml_manifest (AVIOContext *pb, MOVMuxContext *mov, AVFormatContext *s)
static int mov_write_mfhd_tag (AVIOContext *pb, MOVMuxContext *mov)
static uint32_t get_sample_flags (MOVTrack *track, MOVIentry *entry)
static int mov_write_tfhd_tag (AVIOContext *pb, MOVMuxContext *mov, MOVTrack *track, int64_t moof_offset)
static int mov_write_trun_tag (AVIOContext *pb, MOVMuxContext *mov, MOVTrack *track, int moof_size, int first, int end)
static int mov_write_tfxd_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_tfrf_tag (AVIOContext *pb, MOVMuxContext *mov, MOVTrack *track, int entry)
static int mov_write_tfrf_tags (AVIOContext *pb, MOVMuxContext *mov, MOVTrack *track)
static int mov_add_tfra_entries (AVIOContext *pb, MOVMuxContext *mov, int tracks, int size)
static void mov_prune_frag_info (MOVMuxContext *mov, int tracks, int max)
static int mov_write_tfdt_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_traf_tag (AVIOContext *pb, MOVMuxContext *mov, MOVTrack *track, int64_t moof_offset, int moof_size)
static int mov_write_moof_tag_internal (AVIOContext *pb, MOVMuxContext *mov, int tracks, int moof_size)
static int mov_write_sidx_tag (AVIOContext *pb, MOVTrack *track, int ref_size, int total_sidx_size)
static int mov_write_sidx_tags (AVIOContext *pb, MOVMuxContext *mov, int tracks, int ref_size)
static int mov_write_moof_tag (AVIOContext *pb, MOVMuxContext *mov, int tracks, int64_t mdat_size)
static int mov_write_tfra_tag (AVIOContext *pb, MOVTrack *track)
static int mov_write_mfra_tag (AVIOContext *pb, MOVMuxContext *mov)
static int mov_write_mdat_tag (AVIOContext *pb, MOVMuxContext *mov)
static int mov_write_ftyp_tag (AVIOContext *pb, AVFormatContext *s)
static int mov_write_uuidprof_tag (AVIOContext *pb, AVFormatContext *s)
static int mov_write_identification (AVIOContext *pb, AVFormatContext *s)
static int mov_parse_mpeg2_frame (AVPacket *pkt, uint32_t *flags)
static void mov_parse_vc1_frame (AVPacket *pkt, MOVTrack *trk)
static int mov_flush_fragment_interleaving (AVFormatContext *s, MOVTrack *track)
static int mov_flush_fragment (AVFormatContext *s, int force)
static int mov_auto_flush_fragment (AVFormatContext *s, int force)
static int check_pkt (AVFormatContext *s, AVPacket *pkt)
int ff_mov_write_packet (AVFormatContext *s, AVPacket *pkt)
static int mov_write_single_packet (AVFormatContext *s, AVPacket *pkt)
static int mov_write_subtitle_end_packet (AVFormatContext *s, int stream_index, int64_t dts)
static int mov_write_packet (AVFormatContext *s, AVPacket *pkt)
static int mov_create_chapter_track (AVFormatContext *s, int tracknum)
static int mov_check_timecode_track (AVFormatContext *s, AVTimecode *tc, int src_index, const char *tcstr)
static int mov_create_timecode_track (AVFormatContext *s, int index, int src_index, AVTimecode tc)
static void enable_tracks (AVFormatContext *s)
static void mov_free (AVFormatContext *s)
static uint32_t rgb_to_yuv (uint32_t rgb)
static int mov_create_dvd_sub_decoder_specific_info (MOVTrack *track, AVStream *st)
static int mov_init (AVFormatContext *s)
static int mov_write_header (AVFormatContext *s)
static int get_sidx_size (AVFormatContext *s)
static int compute_moov_size (AVFormatContext *s)
static int compute_sidx_size (AVFormatContext *s)
static int shift_data (AVFormatContext *s)
static int mov_write_trailer (AVFormatContext *s)
static int mov_check_bitstream (struct AVFormatContext *s, const AVPacket *pkt)
Variables
static const AVOption options []
static const AVCodecTag codec_ipod_tags []
struct {
enum AVPixelFormat pix_fmt
uint32_t tag
unsigned bps
} mov_pix_fmt_tags []
static const AVCodecTag codec_3gp_tags []
static const AVCodecTag codec_f4v_tags []
static const uint16_t fiel_data []
Macro Definition Documentation
MOV_CLASS
#define MOV_CLASS (flavor)
Value:
static const AVClass flavor ## _muxer_class = {\
    .class_name = #flavor " muxer",\
    .item_name  = av_default_item_name,\
    .option     = options,\
    .version    = LIBAVUTIL_VERSION_INT,\
};
Definition at line 99 of file movenc.c.
Referenced by mov_check_bitstream().
READ_BLOCK
#define READ_BLOCK
Value:
do {                                                             \
    read_size[read_buf_id] = avio_read(read_pb, read_buf[read_buf_id], moov_size);  \
    read_buf_id ^= 1;                                                               \
} while (0)
Referenced by shift_data().
Function Documentation
get_moov_size()
static int get_moov_size (AVFormatContext * s) static
Definition at line 5981 of file movenc.c.
Referenced by compute_moov_size(), and mov_flush_fragment().
utf8len()
static int utf8len (const uint8_t * b) static
Definition at line 109 of file movenc.c.
Referenced by mov_write_3gp_udta_tag(), mov_write_hdlr_tag(), mov_write_psp_udta_tag(), mov_write_tmcd_tag(), and mov_write_track_metadata().
update_size()
static int64_t update_size (AVIOContext * pb, int64_t pos) static
Definition at line 121 of file movenc.c.
Referenced by mov_write_3gp_udta_tag(), mov_write_audio_tag(), mov_write_avcc_tag(), mov_write_chan_tag(), mov_write_chpl_tag(), mov_write_dfla_tag(), mov_write_dinf_tag(), mov_write_esds_tag(), mov_write_ftyp_tag(), mov_write_gmhd_tag(), mov_write_hdlr_tag(), mov_write_hvcc_tag(), mov_write_ilst_tag(), mov_write_iods_tag(), mov_write_isml_manifest(), mov_write_loci_tag(), mov_write_mdia_tag(), mov_write_mdta_ilst_tag(), mov_write_mdta_keys_tag(), mov_write_meta_tag(), mov_write_mfra_tag(), mov_write_minf_tag(), mov_write_moof_tag_internal(), mov_write_moov_tag(), mov_write_ms_tag(), mov_write_mvex_tag(), mov_write_rtp_tag(), mov_write_sidx_tag(), mov_write_source_reference_tag(), mov_write_stbl_tag(), mov_write_stco_tag(), mov_write_string_tag(), mov_write_stsc_tag(), mov_write_stsd_tag(), mov_write_stss_tag(), mov_write_stsz_tag(), mov_write_subtitle_tag(), mov_write_tapt_tag(), mov_write_tcmi_tag(), mov_write_tfdt_tag(), mov_write_tfhd_tag(), mov_write_tfra_tag(), mov_write_tfxd_tag(), mov_write_tmcd_tag(), mov_write_track_metadata(), mov_write_traf_tag(), mov_write_trak_tag(), mov_write_trun_tag(), mov_write_uuidusmt_tag(), mov_write_video_tag(), mov_write_vpcc_tag(), mov_write_wave_tag(), and mov_write_wfex_tag().
co64_required()
static int co64_required (const MOVTrack * track) static
Definition at line 131 of file movenc.c.
Referenced by mov_write_stco_tag().
mov_write_stco_tag()
static int mov_write_stco_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 139 of file movenc.c.
Referenced by mov_write_stbl_tag().
mov_write_stsz_tag()
static int mov_write_stsz_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 163 of file movenc.c.
Referenced by mov_write_stbl_tag().
mov_write_stsc_tag()
static int mov_write_stsc_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 199 of file movenc.c.
Referenced by mov_write_stbl_tag().
mov_write_stss_tag()
static int mov_write_stss_tag (AVIOContext * pb, MOVTrack * track, uint32_t flag) static
Definition at line 228 of file movenc.c.
Referenced by mov_write_stbl_tag().
mov_write_amr_tag()
static int mov_write_amr_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 251 of file movenc.c.
Referenced by mov_write_audio_tag(), and mov_write_wave_tag().
mov_write_ac3_tag()
static int mov_write_ac3_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 265 of file movenc.c.
Referenced by mov_write_audio_tag(), and mov_write_wave_tag().
mov_write_eac3_tag()
static int mov_write_eac3_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 464 of file movenc.c.
Referenced by mov_write_audio_tag(), and mov_write_wave_tag().
mov_write_extradata_tag()
static int mov_write_extradata_tag (AVIOContext * pb, MOVTrack * track) static
This function writes extradata "as is".
Extradata must be formatted like a valid atom (with size and tag).
Definition at line 521 of file movenc.c.
Referenced by mov_write_audio_tag(), mov_write_video_tag(), and mov_write_wave_tag().
mov_write_enda_tag()
static int mov_write_enda_tag (AVIOContext * pb) static
Definition at line 527 of file movenc.c.
Referenced by mov_write_wave_tag().
mov_write_enda_tag_be()
static int mov_write_enda_tag_be (AVIOContext * pb) static
Definition at line 535 of file movenc.c.
Referenced by mov_write_wave_tag().
put_descr()
static void put_descr (AVIOContext * pb, int tag, unsigned int size) static
Definition at line 543 of file movenc.c.
Referenced by mov_write_esds_tag(), and mov_write_iods_tag().
compute_avg_bitrate()
static unsigned compute_avg_bitrate (MOVTrack * track) static
Definition at line 552 of file movenc.c.
Referenced by mov_write_esds_tag().
mov_write_esds_tag()
static int mov_write_esds_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 563 of file movenc.c.
Referenced by mov_write_audio_tag(), mov_write_subtitle_tag(), mov_write_video_tag(), and mov_write_wave_tag().
mov_pcm_le_gt16()
static int mov_pcm_le_gt16 (enum AVCodecID codec_id) static
Definition at line 620 of file movenc.c.
Referenced by mov_write_audio_tag(), and mov_write_wave_tag().
mov_pcm_be_gt16()
static int mov_pcm_be_gt16 (enum AVCodecID codec_id) static
Definition at line 628 of file movenc.c.
Referenced by mov_write_audio_tag(), and mov_write_wave_tag().
mov_write_ms_tag()
static int mov_write_ms_tag (AVFormatContext * s, AVIOContext * pb, MOVTrack * track) static
Definition at line 636 of file movenc.c.
Referenced by mov_write_wave_tag().
mov_write_wfex_tag()
static int mov_write_wfex_tag (AVFormatContext * s, AVIOContext * pb, MOVTrack * track) static
Definition at line 648 of file movenc.c.
Referenced by mov_write_audio_tag().
mov_write_dfla_tag()
static int mov_write_dfla_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 659 of file movenc.c.
Referenced by mov_write_audio_tag().
mov_write_chan_tag()
static int mov_write_chan_tag (AVFormatContext * s, AVIOContext * pb, MOVTrack * track) static
Definition at line 679 of file movenc.c.
Referenced by mov_write_audio_tag().
mov_write_wave_tag()
static int mov_write_wave_tag (AVFormatContext * s, AVIOContext * pb, MOVTrack * track) static
Definition at line 707 of file movenc.c.
Referenced by mov_write_audio_tag().
mov_write_dvc1_structs()
static int mov_write_dvc1_structs (MOVTrack * track, uint8_t * buf) static
Definition at line 750 of file movenc.c.
Referenced by mov_write_dvc1_tag().
mov_write_dvc1_tag()
static int mov_write_dvc1_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 833 of file movenc.c.
Referenced by mov_write_video_tag().
mov_write_glbl_tag()
static int mov_write_glbl_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 849 of file movenc.c.
Referenced by mov_write_audio_tag(), and mov_write_video_tag().
mov_get_lpcm_flags()
static int mov_get_lpcm_flags (enum AVCodecID codec_id) static
Compute flags for 'lpcm' tag.
See CoreAudioTypes and AudioStreamBasicDescription at Apple.
Definition at line 861 of file movenc.c.
Referenced by mov_write_audio_tag().
get_cluster_duration()
static int get_cluster_duration (MOVTrack * track, int cluster_idx) static
Definition at line 886 of file movenc.c.
Referenced by get_samples_per_packet(), mov_flush_fragment(), mov_write_stts_tag(), mov_write_tfhd_tag(), and mov_write_trun_tag().
get_samples_per_packet()
static int get_samples_per_packet (MOVTrack * track) static
Definition at line 906 of file movenc.c.
Referenced by mov_write_audio_tag().
mov_write_audio_tag()
static int mov_write_audio_tag (AVFormatContext * s, AVIOContext * pb, MOVMuxContext * mov, MOVTrack * track) static
Definition at line 927 of file movenc.c.
Referenced by mov_write_stsd_tag().
mov_write_d263_tag()
static int mov_write_d263_tag (AVIOContext * pb) static
Definition at line 1054 of file movenc.c.
Referenced by mov_write_video_tag().
mov_write_avcc_tag()
static int mov_write_avcc_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 1066 of file movenc.c.
Referenced by mov_write_video_tag().
mov_write_vpcc_tag()
static int mov_write_vpcc_tag (AVFormatContext * s, AVIOContext * pb, MOVTrack * track) static
Definition at line 1076 of file movenc.c.
Referenced by mov_write_video_tag().
mov_write_hvcc_tag()
static int mov_write_hvcc_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 1087 of file movenc.c.
Referenced by mov_write_video_tag().
mov_write_avid_tag()
static int mov_write_avid_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 1098 of file movenc.c.
Referenced by mov_write_video_tag().
mov_write_dpxe_tag()
static int mov_write_dpxe_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 1181 of file movenc.c.
Referenced by mov_write_video_tag().
mp4_get_codec_tag()
static int mp4_get_codec_tag (AVFormatContext * s, MOVTrack * track) static
Definition at line 1194 of file movenc.c.
Referenced by mov_find_codec_tag().
ipod_get_codec_tag()
static int ipod_get_codec_tag (AVFormatContext * s, MOVTrack * track) static
Definition at line 1228 of file movenc.c.
Referenced by mov_find_codec_tag().
mov_get_dv_codec_tag()
static int mov_get_dv_codec_tag (AVFormatContext * s, MOVTrack * track) static
Definition at line 1247 of file movenc.c.
Referenced by mov_get_codec_tag().
find_fps()
static AVRational find_fps (AVFormatContext * s, AVStream * st) static
Definition at line 1272 of file movenc.c.
Referenced by find_compressor(), mov_check_timecode_track(), mov_create_timecode_track(), mov_get_h264_codec_tag(), and mov_get_mpeg2_xdcam_codec_tag().
mov_get_mpeg2_xdcam_codec_tag()
static int mov_get_mpeg2_xdcam_codec_tag (AVFormatContext * s, MOVTrack * track) static
Definition at line 1290 of file movenc.c.
Referenced by mov_get_codec_tag().
mov_get_h264_codec_tag()
static int mov_get_h264_codec_tag (AVFormatContext * s, MOVTrack * track) static
Definition at line 1352 of file movenc.c.
Referenced by mov_get_codec_tag().
mov_get_dnxhd_codec_tag()
static int mov_get_dnxhd_codec_tag (AVFormatContext * s, MOVTrack * track) static
Definition at line 1432 of file movenc.c.
Referenced by mov_get_codec_tag().
mov_get_rawvideo_codec_tag()
static int mov_get_rawvideo_codec_tag (AVFormatContext * s, MOVTrack * track) static
Definition at line 1441 of file movenc.c.
Referenced by mov_get_codec_tag().
mov_get_codec_tag()
static int mov_get_codec_tag (AVFormatContext * s, MOVTrack * track) static
Definition at line 1467 of file movenc.c.
Referenced by mov_find_codec_tag().
mov_find_codec_tag()
static int mov_find_codec_tag (AVFormatContext * s, MOVTrack * track) static
Definition at line 1534 of file movenc.c.
Referenced by mov_init().
mov_write_uuid_tag_ipod()
static int mov_write_uuid_tag_ipod (AVIOContext * pb) static
Write uuid atom.
Needed to make file play in iPods running newest firmware goes after avcC atom in moov.trak.mdia.minf.stbl.stsd.avc1
Definition at line 1560 of file movenc.c.
Referenced by mov_write_video_tag().
mov_write_fiel_tag()
static int mov_write_fiel_tag (AVIOContext * pb, MOVTrack * track, int field_order) static
Definition at line 1576 of file movenc.c.
Referenced by mov_write_video_tag().
mov_write_subtitle_tag()
static int mov_write_subtitle_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 1589 of file movenc.c.
Referenced by mov_write_stsd_tag().
mov_write_pasp_tag()
static int mov_write_pasp_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 1606 of file movenc.c.
Referenced by mov_write_video_tag().
mov_write_gama_tag()
static int mov_write_gama_tag (AVIOContext * pb, MOVTrack * track, double gamma) static
Definition at line 1619 of file movenc.c.
Referenced by mov_write_video_tag().
mov_write_colr_tag()
static int mov_write_colr_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 1644 of file movenc.c.
Referenced by mov_write_video_tag().
find_compressor()
static void find_compressor (char * compressor_name, int len, MOVTrack * track) static
Definition at line 1718 of file movenc.c.
Referenced by mov_write_video_tag().
mov_write_video_tag()
static int mov_write_video_tag (AVIOContext * pb, MOVMuxContext * mov, MOVTrack * track) static
Definition at line 1746 of file movenc.c.
Referenced by mov_write_stsd_tag().
mov_write_rtp_tag()
static int mov_write_rtp_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 1892 of file movenc.c.
Referenced by mov_write_stsd_tag().
mov_write_source_reference_tag()
static int mov_write_source_reference_tag (AVIOContext * pb, MOVTrack * track, const char * reel_name) static
Definition at line 1912 of file movenc.c.
Referenced by mov_write_tmcd_tag().
mov_write_tmcd_tag()
static int mov_write_tmcd_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 1931 of file movenc.c.
Referenced by mov_write_stsd_tag().
mov_write_stsd_tag()
static int mov_write_stsd_tag (AVFormatContext * s, AVIOContext * pb, MOVMuxContext * mov, MOVTrack * track) static
Definition at line 1987 of file movenc.c.
Referenced by mov_write_stbl_tag().
mov_write_ctts_tag()
static int mov_write_ctts_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 2007 of file movenc.c.
Referenced by mov_write_stbl_tag().
mov_write_stts_tag()
static int mov_write_stts_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 2043 of file movenc.c.
Referenced by mov_write_stbl_tag().
mov_write_dref_tag()
static int mov_write_dref_tag (AVIOContext * pb) static
Definition at line 2088 of file movenc.c.
Referenced by mov_write_dinf_tag().
mov_write_stbl_tag()
static int mov_write_stbl_tag (AVFormatContext * s, AVIOContext * pb, MOVMuxContext * mov, MOVTrack * track) static
Definition at line 2103 of file movenc.c.
Referenced by mov_write_minf_tag().
mov_write_dinf_tag()
static int mov_write_dinf_tag (AVIOContext * pb) static
Definition at line 2133 of file movenc.c.
Referenced by mov_write_minf_tag().
mov_write_nmhd_tag()
static int mov_write_nmhd_tag (AVIOContext * pb) static
Definition at line 2142 of file movenc.c.
Referenced by mov_write_minf_tag().
mov_write_tcmi_tag()
static int mov_write_tcmi_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 2150 of file movenc.c.
Referenced by mov_write_gmhd_tag().
mov_write_gmhd_tag()
static int mov_write_gmhd_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 2172 of file movenc.c.
Referenced by mov_write_minf_tag().
mov_write_smhd_tag()
static int mov_write_smhd_tag (AVIOContext * pb) static
Definition at line 2218 of file movenc.c.
Referenced by mov_write_minf_tag().
mov_write_vmhd_tag()
static int mov_write_vmhd_tag (AVIOContext * pb) static
Definition at line 2228 of file movenc.c.
Referenced by mov_write_minf_tag().
is_clcp_track()
static int is_clcp_track (MOVTrack * track) static
Definition at line 2237 of file movenc.c.
Referenced by mov_write_hdlr_tag(), mov_write_minf_tag(), and mov_write_trak_tag().
mov_write_hdlr_tag()
static int mov_write_hdlr_tag (AVFormatContext * s, AVIOContext * pb, MOVTrack * track) static
Definition at line 2243 of file movenc.c.
Referenced by mov_write_mdia_tag(), and mov_write_minf_tag().
mov_write_hmhd_tag()
static int mov_write_hmhd_tag (AVIOContext * pb) static
Definition at line 2316 of file movenc.c.
Referenced by mov_write_minf_tag().
mov_write_minf_tag()
static int mov_write_minf_tag (AVFormatContext * s, AVIOContext * pb, MOVMuxContext * mov, MOVTrack * track) static
Definition at line 2331 of file movenc.c.
Referenced by mov_write_mdia_tag().
mov_write_mdhd_tag()
static int mov_write_mdhd_tag (AVIOContext * pb, MOVMuxContext * mov, MOVTrack * track) static
Definition at line 2364 of file movenc.c.
Referenced by mov_write_mdia_tag().
mov_write_mdia_tag()
static int mov_write_mdia_tag (AVFormatContext * s, AVIOContext * pb, MOVMuxContext * mov, MOVTrack * track) static
Definition at line 2403 of file movenc.c.
Referenced by mov_write_trak_tag().
write_matrix()
static void write_matrix (AVIOContext * pb, int16_t a, int16_t b, int16_t c, int16_t d, int16_t tx, int16_t ty) static
Definition at line 2422 of file movenc.c.
Referenced by mov_write_mvhd_tag(), and mov_write_tkhd_tag().
mov_write_tkhd_tag()
static int mov_write_tkhd_tag (AVIOContext * pb, MOVMuxContext * mov, MOVTrack * track, AVStream * st) static
Definition at line 2436 of file movenc.c.
Referenced by mov_write_trak_tag().
mov_write_tapt_tag()
static int mov_write_tapt_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 2547 of file movenc.c.
Referenced by mov_write_trak_tag().
mov_write_edts_tag()
static int mov_write_edts_tag (AVIOContext * pb, MOVMuxContext * mov, MOVTrack * track) static
Definition at line 2579 of file movenc.c.
Referenced by mov_write_trak_tag().
mov_write_tref_tag()
static int mov_write_tref_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 2664 of file movenc.c.
Referenced by mov_write_trak_tag().
mov_write_uuid_tag_psp()
static int mov_write_uuid_tag_psp (AVIOContext * pb, MOVTrack * mov) static
Definition at line 2675 of file movenc.c.
Referenced by mov_write_trak_tag().
mov_write_udta_sdp()
static int mov_write_udta_sdp (AVIOContext * pb, MOVTrack * track) static
Definition at line 2693 of file movenc.c.
Referenced by mov_write_trak_tag().
mov_write_track_metadata()
static int mov_write_track_metadata (AVIOContext * pb, AVStream * st, const char * tag, const char * str) static
Definition at line 2714 of file movenc.c.
Referenced by mov_write_track_udta_tag().
mov_write_track_udta_tag()
static int mov_write_track_udta_tag (AVIOContext * pb, MOVMuxContext * mov, AVStream * st) static
Definition at line 2728 of file movenc.c.
Referenced by mov_write_trak_tag().
mov_write_trak_tag()
static int mov_write_trak_tag (AVFormatContext * s, AVIOContext * pb, MOVMuxContext * mov, MOVTrack * track, AVStream * st) static
Definition at line 2755 of file movenc.c.
Referenced by mov_write_moov_tag().
mov_write_iods_tag()
static int mov_write_iods_tag (AVIOContext * pb, MOVMuxContext * mov) static
Definition at line 2808 of file movenc.c.
Referenced by mov_write_moov_tag().
mov_write_trex_tag()
static int mov_write_trex_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 2837 of file movenc.c.
Referenced by mov_write_mvex_tag().
mov_write_mvex_tag()
static int mov_write_mvex_tag (AVIOContext * pb, MOVMuxContext * mov) static
Definition at line 2850 of file movenc.c.
Referenced by mov_write_moov_tag().
mov_write_mvhd_tag()
static int mov_write_mvhd_tag (AVIOContext * pb, MOVMuxContext * mov) static
Definition at line 2861 of file movenc.c.
Referenced by mov_write_moov_tag().
mov_write_itunes_hdlr_tag()
static int mov_write_itunes_hdlr_tag (AVIOContext * pb, MOVMuxContext * mov, AVFormatContext * s) static
Definition at line 2921 of file movenc.c.
Referenced by mov_write_meta_tag().
mov_write_string_data_tag()
static int mov_write_string_data_tag (AVIOContext * pb, const char * data, int lang, int long_style) static
Definition at line 2937 of file movenc.c.
Referenced by mov_write_mdta_ilst_tag(), and mov_write_string_tag().
mov_write_string_tag()
static int mov_write_string_tag (AVIOContext * pb, const char * name, const char * value, int lang, int long_style) static
Definition at line 2957 of file movenc.c.
Referenced by mov_write_ilst_tag(), and mov_write_string_metadata().
get_metadata_lang()
static AVDictionaryEntry* get_metadata_lang (AVFormatContext * s, const char * tag, int * lang) static
Definition at line 2971 of file movenc.c.
Referenced by mov_write_loci_tag(), and mov_write_string_metadata().
mov_write_string_metadata()
static int mov_write_string_metadata (AVFormatContext * s, AVIOContext * pb, const char * name, const char * tag, int long_style) static
Definition at line 2996 of file movenc.c.
Referenced by mov_write_ilst_tag(), and mov_write_udta_tag().
mov_write_tmpo_tag()
static int mov_write_tmpo_tag (AVIOContext * pb, AVFormatContext * s) static
Definition at line 3008 of file movenc.c.
Referenced by mov_write_ilst_tag().
mov_write_loci_tag()
static int mov_write_loci_tag (AVFormatContext * s, AVIOContext * pb) static
Definition at line 3026 of file movenc.c.
Referenced by mov_write_udta_tag().
mov_write_trkn_tag()
static int mov_write_trkn_tag (AVIOContext * pb, MOVMuxContext * mov, AVFormatContext * s, int disc) static
Definition at line 3077 of file movenc.c.
Referenced by mov_write_ilst_tag().
mov_write_int8_metadata()
static int mov_write_int8_metadata (AVFormatContext * s, AVIOContext * pb, const char * name, const char * tag, int len) static
Definition at line 3104 of file movenc.c.
Referenced by mov_write_ilst_tag().
mov_write_ilst_tag()
static int mov_write_ilst_tag (AVIOContext * pb, MOVMuxContext * mov, AVFormatContext * s) static
Definition at line 3132 of file movenc.c.
Referenced by mov_write_meta_tag().
mov_write_mdta_hdlr_tag()
static int mov_write_mdta_hdlr_tag (AVIOContext * pb, MOVMuxContext * mov, AVFormatContext * s) static
Definition at line 3170 of file movenc.c.
Referenced by mov_write_meta_tag().
mov_write_mdta_keys_tag()
static int mov_write_mdta_keys_tag (AVIOContext * pb, MOVMuxContext * mov, AVFormatContext * s) static
Definition at line 3185 of file movenc.c.
Referenced by mov_write_meta_tag().
mov_write_mdta_ilst_tag()
static int mov_write_mdta_ilst_tag (AVIOContext * pb, MOVMuxContext * mov, AVFormatContext * s) static
Definition at line 3213 of file movenc.c.
Referenced by mov_write_meta_tag().
mov_write_meta_tag()
static int mov_write_meta_tag (AVIOContext * pb, MOVMuxContext * mov, AVFormatContext * s) static
Definition at line 3235 of file movenc.c.
Referenced by mov_write_udta_tag().
mov_write_raw_metadata_tag()
static int mov_write_raw_metadata_tag (AVFormatContext * s, AVIOContext * pb, const char * name, const char * key) static
Definition at line 3257 of file movenc.c.
Referenced by mov_write_udta_tag().
ascii_to_wc()
static int ascii_to_wc (AVIOContext * pb, const uint8_t * b) static
Definition at line 3277 of file movenc.c.
Referenced by mov_write_psp_udta_tag().
language_code()
static uint16_t language_code (const char * str) static
Definition at line 3288 of file movenc.c.
Referenced by mov_write_3gp_udta_tag(), mov_write_psp_udta_tag(), and mov_write_uuidusmt_tag().
mov_write_3gp_udta_tag()
static int mov_write_3gp_udta_tag (AVIOContext * pb, AVFormatContext * s, const char * tag, const char * str) static
Definition at line 3295 of file movenc.c.
Referenced by mov_write_udta_tag().
mov_write_chpl_tag()
static int mov_write_chpl_tag (AVIOContext * pb, AVFormatContext * s) static
Definition at line 3317 of file movenc.c.
Referenced by mov_write_udta_tag().
mov_write_udta_tag()
static int mov_write_udta_tag (AVIOContext * pb, MOVMuxContext * mov, AVFormatContext * s) static
Definition at line 3343 of file movenc.c.
Referenced by mov_write_moov_tag().
mov_write_psp_udta_tag()
static void mov_write_psp_udta_tag (AVIOContext * pb, const char * str, const char * lang, int type) static
Definition at line 3400 of file movenc.c.
Referenced by mov_write_uuidusmt_tag().
mov_write_uuidusmt_tag()
static int mov_write_uuidusmt_tag (AVIOContext * pb, AVFormatContext * s) static
Definition at line 3413 of file movenc.c.
Referenced by mov_write_moov_tag().
build_chunks()
static void build_chunks (MOVTrack * trk) static
Definition at line 3451 of file movenc.c.
Referenced by mov_write_moov_tag().
mov_setup_track_ids()
static int mov_setup_track_ids (MOVMuxContext * mov, AVFormatContext * s) static
Assign track ids.
If option "use_stream_ids_as_track_ids" is set, the stream ids are used as track ids.
This assumes mov->tracks and s->streams are in the same order and there are no gaps in either of them (so mov->tracks[n] refers to s->streams[n]).
As an exception, there can be more entries in s->streams than in mov->tracks, in which case new track ids are generated (starting after the largest found stream id).
Definition at line 3486 of file movenc.c.
Referenced by mov_write_isml_manifest(), and mov_write_moov_tag().
mov_write_moov_tag()
static int mov_write_moov_tag (AVIOContext * pb, MOVMuxContext * mov, AVFormatContext * s) static
Definition at line 3520 of file movenc.c.
Referenced by get_moov_size(), mov_flush_fragment(), mov_write_header(), and mov_write_trailer().
param_write_int()
static void param_write_int (AVIOContext * pb, const char * name, int value) static
Definition at line 3596 of file movenc.c.
Referenced by mov_write_isml_manifest().
param_write_string()
static void param_write_string (AVIOContext * pb, const char * name, const char * value) static
Definition at line 3601 of file movenc.c.
Referenced by mov_write_isml_manifest().
param_write_hex()
static void param_write_hex (AVIOContext * pb, const char * name, const uint8_t * value, int len) static
Definition at line 3606 of file movenc.c.
Referenced by mov_write_isml_manifest().
mov_write_isml_manifest()
static int mov_write_isml_manifest (AVIOContext * pb, MOVMuxContext * mov, AVFormatContext * s) static
Definition at line 3615 of file movenc.c.
Referenced by mov_write_header().
mov_write_mfhd_tag()
static int mov_write_mfhd_tag (AVIOContext * pb, MOVMuxContext * mov) static
Definition at line 3729 of file movenc.c.
Referenced by mov_write_moof_tag_internal().
get_sample_flags()
static uint32_t get_sample_flags (MOVTrack * track, MOVIentry * entry) static
Definition at line 3738 of file movenc.c.
Referenced by mov_write_tfhd_tag(), and mov_write_trun_tag().
mov_write_tfhd_tag()
static int mov_write_tfhd_tag (AVIOContext * pb, MOVMuxContext * mov, MOVTrack * track, int64_t moof_offset) static
Definition at line 3744 of file movenc.c.
Referenced by mov_write_traf_tag().
mov_write_trun_tag()
static int mov_write_trun_tag (AVIOContext * pb, MOVMuxContext * mov, MOVTrack * track, int moof_size, int first, int end) static
Definition at line 3804 of file movenc.c.
Referenced by mov_write_traf_tag().
mov_write_tfxd_tag()
static int mov_write_tfxd_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 3857 of file movenc.c.
Referenced by mov_write_traf_tag().
mov_write_tfrf_tag()
static int mov_write_tfrf_tag (AVIOContext * pb, MOVMuxContext * mov, MOVTrack * track, int entry) static
Definition at line 3878 of file movenc.c.
Referenced by mov_write_tfrf_tags().
mov_write_tfrf_tags()
static int mov_write_tfrf_tags (AVIOContext * pb, MOVMuxContext * mov, MOVTrack * track) static
Definition at line 3913 of file movenc.c.
Referenced by mov_add_tfra_entries().
mov_add_tfra_entries()
static int mov_add_tfra_entries (AVIOContext * pb, MOVMuxContext * mov, int tracks, int size) static
Definition at line 3927 of file movenc.c.
Referenced by mov_write_moof_tag().
mov_prune_frag_info()
static void mov_prune_frag_info (MOVMuxContext * mov, int tracks, int max) static
Definition at line 3967 of file movenc.c.
Referenced by mov_write_moof_tag().
mov_write_tfdt_tag()
static int mov_write_tfdt_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 3981 of file movenc.c.
Referenced by mov_write_traf_tag().
mov_write_traf_tag()
static int mov_write_traf_tag (AVIOContext * pb, MOVMuxContext * mov, MOVTrack * track, int64_t moof_offset, int moof_size) static
Definition at line 3993 of file movenc.c.
Referenced by mov_write_moof_tag_internal().
mov_write_moof_tag_internal()
static int mov_write_moof_tag_internal (AVIOContext * pb, MOVMuxContext * mov, int tracks, int moof_size) static
Definition at line 4033 of file movenc.c.
Referenced by mov_write_moof_tag().
mov_write_sidx_tag()
static int mov_write_sidx_tag (AVIOContext * pb, MOVTrack * track, int ref_size, int total_sidx_size) static
Definition at line 4056 of file movenc.c.
Referenced by mov_write_sidx_tags().
mov_write_sidx_tags()
static int mov_write_sidx_tags (AVIOContext * pb, MOVMuxContext * mov, int tracks, int ref_size) static
Definition at line 4117 of file movenc.c.
Referenced by get_sidx_size(), mov_write_moof_tag(), and mov_write_trailer().
mov_write_moof_tag()
static int mov_write_moof_tag (AVIOContext * pb, MOVMuxContext * mov, int tracks, int64_t mdat_size) static
Definition at line 4152 of file movenc.c.
Referenced by mov_flush_fragment().
mov_write_tfra_tag()
static int mov_write_tfra_tag (AVIOContext * pb, MOVTrack * track) static
Definition at line 4180 of file movenc.c.
Referenced by mov_write_mfra_tag().
mov_write_mfra_tag()
static int mov_write_mfra_tag (AVIOContext * pb, MOVMuxContext * mov) static
Definition at line 4204 of file movenc.c.
Referenced by mov_write_trailer().
mov_write_mdat_tag()
static int mov_write_mdat_tag (AVIOContext * pb, MOVMuxContext * mov) static
Definition at line 4230 of file movenc.c.
Referenced by mov_write_header().
mov_write_ftyp_tag()
static int mov_write_ftyp_tag (AVIOContext * pb, AVFormatContext * s) static
Definition at line 4242 of file movenc.c.
Referenced by mov_write_identification().
mov_write_uuidprof_tag()
static int mov_write_uuidprof_tag (AVIOContext * pb, AVFormatContext * s) static
Definition at line 4317 of file movenc.c.
Referenced by mov_write_identification().
mov_write_identification()
static int mov_write_identification (AVIOContext * pb, AVFormatContext * s) static
Definition at line 4388 of file movenc.c.
Referenced by mov_flush_fragment(), and mov_write_header().
mov_parse_mpeg2_frame()
static int mov_parse_mpeg2_frame (AVPacket * pkt, uint32_t * flags) static
Definition at line 4415 of file movenc.c.
Referenced by ff_mov_write_packet().
mov_parse_vc1_frame()
static void mov_parse_vc1_frame (AVPacket * pkt, MOVTrack * trk) static
Definition at line 4436 of file movenc.c.
Referenced by ff_mov_write_packet().
mov_flush_fragment_interleaving()
static int mov_flush_fragment_interleaving (AVFormatContext * s, MOVTrack * track) static
Definition at line 4496 of file movenc.c.
Referenced by ff_mov_write_packet(), and mov_flush_fragment().
mov_flush_fragment()
static int mov_flush_fragment (AVFormatContext * s, int force) static
Definition at line 4522 of file movenc.c.
Referenced by mov_auto_flush_fragment(), and mov_write_packet().
mov_auto_flush_fragment()
static int mov_auto_flush_fragment (AVFormatContext * s, int force) static
Definition at line 4730 of file movenc.c.
Referenced by mov_write_single_packet(), and mov_write_trailer().
check_pkt()
static int check_pkt (AVFormatContext * s, AVPacket * pkt) static
Definition at line 4744 of file movenc.c.
Referenced by ff_mov_write_packet(), and mov_write_single_packet().
ff_mov_write_packet()
int ff_mov_write_packet (AVFormatContext * s, AVPacket * pkt)
Definition at line 4776 of file movenc.c.
Referenced by ff_mov_add_hinted_packet(), mov_create_chapter_track(), mov_create_timecode_track(), and mov_write_single_packet().
mov_write_single_packet()
static int mov_write_single_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 5047 of file movenc.c.
Referenced by mov_write_packet(), and mov_write_subtitle_end_packet().
mov_write_subtitle_end_packet()
static int mov_write_subtitle_end_packet (AVFormatContext * s, int stream_index, int64_t dts) static
Definition at line 5122 of file movenc.c.
Referenced by mov_write_packet(), and mov_write_trailer().
mov_write_packet()
static int mov_write_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 5143 of file movenc.c.
Referenced by mov_check_bitstream().
mov_create_chapter_track()
static int mov_create_chapter_track (AVFormatContext * s, int tracknum) static
Definition at line 5226 of file movenc.c.
Referenced by mov_write_header(), and mov_write_trailer().
mov_check_timecode_track()
static int mov_check_timecode_track (AVFormatContext * s, AVTimecode * tc, int src_index, const char * tcstr) static
Definition at line 5324 of file movenc.c.
Referenced by mov_init(), and mov_write_header().
mov_create_timecode_track()
static int mov_create_timecode_track (AVFormatContext * s, int index, int src_index, AVTimecode tc) static
Definition at line 5333 of file movenc.c.
Referenced by mov_write_header().
enable_tracks()
static void enable_tracks (AVFormatContext * s) static
Definition at line 5382 of file movenc.c.
Referenced by mov_init().
mov_free()
static void mov_free (AVFormatContext * s) static
Definition at line 5423 of file movenc.c.
Referenced by mov_check_bitstream().
rgb_to_yuv()
static uint32_t rgb_to_yuv (uint32_t rgb) static
Definition at line 5451 of file movenc.c.
Referenced by mov_create_dvd_sub_decoder_specific_info().
mov_create_dvd_sub_decoder_specific_info()
static int mov_create_dvd_sub_decoder_specific_info (MOVTrack * track, AVStream * st) static
Definition at line 5467 of file movenc.c.
Referenced by mov_write_header().
mov_init()
static int mov_init (AVFormatContext * s) static
Definition at line 5516 of file movenc.c.
Referenced by mov_check_bitstream().
mov_write_header()
static int mov_write_header (AVFormatContext * s) static
Definition at line 5834 of file movenc.c.
Referenced by mov_check_bitstream().
get_sidx_size()
static int get_sidx_size (AVFormatContext * s) static
Definition at line 5994 of file movenc.c.
Referenced by compute_sidx_size().
compute_moov_size()
static int compute_moov_size (AVFormatContext * s) static
Definition at line 6012 of file movenc.c.
Referenced by shift_data().
compute_sidx_size()
static int compute_sidx_size (AVFormatContext * s) static
Definition at line 6037 of file movenc.c.
Referenced by shift_data().
shift_data()
static int shift_data (AVFormatContext * s) static
Definition at line 6052 of file movenc.c.
Referenced by mov_write_trailer().
mov_write_trailer()
static int mov_write_trailer (AVFormatContext * s) static
Definition at line 6118 of file movenc.c.
Referenced by mov_check_bitstream().
mov_check_bitstream()
static int mov_check_bitstream (struct AVFormatContext * s, const AVPacket * pkt) static
Definition at line 6233 of file movenc.c.
Variable Documentation
options
const AVOption options[] static
Definition at line 56 of file movenc.c.
codec_ipod_tags
const AVCodecTag codec_ipod_tags[] static
Initial value:
= {
    { AV_CODEC_ID_H264,     MKTAG('a','v','c','1') },
    { AV_CODEC_ID_MPEG4,    MKTAG('m','p','4','v') },
    { AV_CODEC_ID_AAC,      MKTAG('m','p','4','a') },
    { AV_CODEC_ID_ALAC,     MKTAG('a','l','a','c') },
    { AV_CODEC_ID_AC3,      MKTAG('a','c','-','3') },
    { AV_CODEC_ID_MOV_TEXT, MKTAG('t','x','3','g') },
    { AV_CODEC_ID_MOV_TEXT, MKTAG('t','e','x','t') },
    { AV_CODEC_ID_NONE, 0 },
}
Definition at line 1217 of file movenc.c.
Referenced by mov_check_bitstream().
pix_fmt
enum AVPixelFormat pix_fmt
Definition at line 1411 of file movenc.c.
Referenced by mov_get_rawvideo_codec_tag(), and mov_init().
tag
uint32_t tag
Examples:
metadata.c, and remuxing.c.
Definition at line 1412 of file movenc.c.
Referenced by aac_encode_frame(), add_input_streams(), aiff_read_header(), ape_read_header(), apng_find_chunk(), apng_probe(), apng_read_header(), apng_read_packet(), asf_write_header1(), av_codec_get_tag(), av_dict_set(), av_find_info_tag(), avformat_find_stream_info(), avformat_match_stream_specifier(), avi_extract_stream_metadata(), avi_load_index(), avi_read_header(), avi_read_idx1(), avi_read_nikon(), cfhd_decode(), check_tag(), copy_tag(), decode_aiff_header(), decode_frame_common(), decode_interframe_v4(), decode_interframe_v4a(), dump_metadata(), dxa_read_header(), dxv_decode(), ea_read_packet(), eval_function(), ff_aac_ltp_insert_new_frame(), ff_mov_read_esds(), ff_mp4_read_dec_config_descr(), ff_vorbiscomment_length(), ff_vorbiscomment_write(), ffat_convert_layout(), ffat_init_encoder(), ffm_read_header(), get_aiff_header(), get_swf_tag(), guess_ni_flag(), gxf_material_tags(), gxf_track_tags(), hq_hqa_decode_frame(), id3v1_create_tag(), id3v1_set_string(), id3v2_check_write_tag(), id3v2_parse(), iff_read_header(), ipod_get_codec_tag(), ircam_read_header(), ircam_write_header(), ivr_read_header(), libschroedinger_decode_frame(), lz_unpack(), main(), matroska_convert_tags(), mkv_write_codecprivate(), mkv_write_header(), mkv_write_simpletag(), mkv_write_stereo_mode(), mkv_write_tag(), mkv_write_tags(), mkv_write_track(), mmf_read_header(), mov_find_codec_tag(), mov_get_codec_tag(), mov_get_dnxhd_codec_tag(), mov_get_dv_codec_tag(), mov_get_h264_codec_tag(), mov_get_mpeg2_xdcam_codec_tag(), mov_get_rawvideo_codec_tag(), mov_probe(), mov_read_custom(), mov_read_meta(), mov_read_sv3d(), mov_read_udta_string(), mov_write_audio_tag(), mp4_get_codec_tag(), mpc8_parse_seektable(), mpc8_read_header(), mpc8_read_packet(), mpegts_write_pmt(), mxf_parse_package_comments(), new_output_stream(), nuv_resync(), ogm_header(), parse_dsd_diin(), parse_dsd_prop(), parse_fragment(), parse_mp4_descr(), parse_multipart_header(), parse_video_info(), pmt_cb(), process_line(), put_meta(), put_swf_end_tag(), put_swf_tag(), qcp_read_packet(), qt_rtp_parse_packet(), rdt_load_mdpr(), read_chapter(), read_header(), read_moof_duration(), rm_read_header(), rv10_write_header(), sami_paragraph_to_ass(), set_codec_str(), set_spdif(), show_tags(), siff_probe(), siff_read_header(), skip_tag(), smjpeg_write_header(), sol_read_header(), swf_read_header(), swf_read_packet(), tiff_decode_tag(), validate_codec_tag(), vs2av_log(), write_metadata(), write_stream_codec_info(), write_table_entries_attrib(), write_table_redirector_legacy_attrib(), xan_decode_frame(), xwma_read_header(), yop_decode_frame(), and yop_paint_block().
bps
unsigned bps
Examples:
filter_audio.c.
Definition at line 1413 of file movenc.c.
Referenced by avr_read_header(), buffer_size_after_time_downloaded(), config_input(), copy_samples(), decode_aiff_header(), decode_element(), decode_subframe(), decode_wave_header(), ff_audio_resample(), ff_put_wav_header(), ff_spp_init_x86(), ff_wma_init(), get_audio_frame_duration(), gxf_packet(), main(), nist_read_header(), nsv_read_chunk(), parse_waveformatex(), process_output(), pvf_read_header(), rso_read_header(), swap_sample_fmts_on_filter(), and webm_dash_manifest_compute_bandwidth().
mov_pix_fmt_tags
const { ... } mov_pix_fmt_tags[]
Initial value:
= {
    { AV_PIX_FMT_YUYV422, MKTAG('y','u','v','2'),  0 },
    { AV_PIX_FMT_YUYV422, MKTAG('y','u','v','s'),  0 },
    { AV_PIX_FMT_UYVY422, MKTAG('2','v','u','y'),  0 },
    { AV_PIX_FMT_RGB555BE,MKTAG('r','a','w',' '), 16 },
    { AV_PIX_FMT_RGB555LE,MKTAG('L','5','5','5'), 16 },
    { AV_PIX_FMT_RGB565LE,MKTAG('L','5','6','5'), 16 },
    { AV_PIX_FMT_RGB565BE,MKTAG('B','5','6','5'), 16 },
    { AV_PIX_FMT_GRAY16BE,MKTAG('b','1','6','g'), 16 },
    { AV_PIX_FMT_RGB24,   MKTAG('r','a','w',' '), 24 },
    { AV_PIX_FMT_BGR24,   MKTAG('2','4','B','G'), 24 },
    { AV_PIX_FMT_ARGB,    MKTAG('r','a','w',' '), 32 },
    { AV_PIX_FMT_BGRA,    MKTAG('B','G','R','A'), 32 },
    { AV_PIX_FMT_RGBA,    MKTAG('R','G','B','A'), 32 },
    { AV_PIX_FMT_ABGR,    MKTAG('A','B','G','R'), 32 },
    { AV_PIX_FMT_RGB48BE, MKTAG('b','4','8','r'), 48 },
}
Referenced by mov_get_rawvideo_codec_tag().
codec_3gp_tags
const AVCodecTag codec_3gp_tags[] static
Initial value:
= {
    { AV_CODEC_ID_H263,     MKTAG('s','2','6','3') },
    { AV_CODEC_ID_H264,     MKTAG('a','v','c','1') },
    { AV_CODEC_ID_MPEG4,    MKTAG('m','p','4','v') },
    { AV_CODEC_ID_AAC,      MKTAG('m','p','4','a') },
    { AV_CODEC_ID_AMR_NB,   MKTAG('s','a','m','r') },
    { AV_CODEC_ID_AMR_WB,   MKTAG('s','a','w','b') },
    { AV_CODEC_ID_MOV_TEXT, MKTAG('t','x','3','g') },
    { AV_CODEC_ID_NONE, 0 },
}
Definition at line 1514 of file movenc.c.
Referenced by mov_check_bitstream().
codec_f4v_tags
const AVCodecTag codec_f4v_tags[] static
Initial value:
= {
    { AV_CODEC_ID_MP3,    MKTAG('.','m','p','3') },
    { AV_CODEC_ID_AAC,    MKTAG('m','p','4','a') },
    { AV_CODEC_ID_H264,   MKTAG('a','v','c','1') },
    { AV_CODEC_ID_VP6A,   MKTAG('V','P','6','A') },
    { AV_CODEC_ID_VP6F,   MKTAG('V','P','6','F') },
    { AV_CODEC_ID_NONE, 0 },
}
Definition at line 1525 of file movenc.c.
Referenced by mov_check_bitstream().
fiel_data
const uint16_t fiel_data[] static
Initial value:
= {
    0x0000, 0x0100, 0x0201, 0x0206, 0x0209, 0x020e
}
Definition at line 1572 of file movenc.c.
Referenced by mov_write_fiel_tag().