FFmpeg: libavcodec/mpc.h File Reference
mpc.h File Reference
Musepack decoder MPEG Audio Layer 1/2 -like codec with frames of 1152 samples divided into 32 subbands.
#include "libavutil/lfg.h"
#include "avcodec.h"
#include "bswapdsp.h"
#include "mpegaudio.h"
#include "mpegaudiodsp.h"
Data Structures
struct Band
Subband structure - hold all variables for each subband.
struct MPCContext
Macros
#define BANDS 32
#define SAMPLES_PER_BAND 36
#define MPC_FRAME_SIZE (BANDS * SAMPLES_PER_BAND)
Functions
void ff_mpc_init (void)
void ff_mpc_dequantize_and_synth (MPCContext *c, int maxband, int16_t **out, int channels)
Detailed Description
Musepack decoder MPEG Audio Layer 1/2 -like codec with frames of 1152 samples divided into 32 subbands.
Definition in file mpc.h.
Macro Definition Documentation
BANDS
#define BANDS 32
Definition at line 39 of file mpc.h.
SAMPLES_PER_BAND
#define SAMPLES_PER_BAND 36
Definition at line 40 of file mpc.h.
Referenced by ff_mpc_dequantize_and_synth(), idx_to_quant(), mpc7_decode_frame(), mpc8_decode_frame(), and mpc_synth().
MPC_FRAME_SIZE
#define MPC_FRAME_SIZE (BANDS * SAMPLES_PER_BAND)
Definition at line 41 of file mpc.h.
Referenced by mpc7_decode_frame(), and mpc8_decode_frame().
Function Documentation
ff_mpc_init()
void ff_mpc_init (void)
Definition at line 37 of file mpc.c.
Referenced by mpc7_decode_init(), and mpc8_decode_init().
ff_mpc_dequantize_and_synth()
void ff_mpc_dequantize_and_synth (MPCContext * c, int maxband, int16_t ** out, int channels)
Definition at line 61 of file mpc.c.
Referenced by mpc7_decode_frame(), and mpc8_decode_frame().