FFmpeg: libavcodec/mpegutils.c File Reference
mpegutils.c File Reference
#include <stdint.h>
#include "libavutil/common.h"
#include "libavutil/frame.h"
#include "libavutil/pixdesc.h"
#include "avcodec.h"
#include "mpegutils.h"
Functions
void ff_draw_horiz_band (AVCodecContext *avctx, AVFrame *cur, AVFrame *last, int y, int h, int picture_structure, int first_field, int low_delay)
Draw a horizontal band if supported.
Function Documentation
ff_draw_horiz_band()
void ff_draw_horiz_band (AVCodecContext * avctx, AVFrame * cur, AVFrame * last, int y, int h, int picture_structure, int first_field, int low_delay)
Draw a horizontal band if supported.
Parameters
h is the normal height, this will be reduced automatically if needed
Definition at line 30 of file mpegutils.c.
Referenced by ff_intrax8_decode_picture(), ff_mpeg_draw_horiz_band(), and svq3_decode_frame().