FFmpeg: libavcodec/mpeg4_unpack_bframes_bsf.c File Reference
mpeg4_unpack_bframes_bsf.c File Reference
#include "avcodec.h"
#include "bsf.h"
#include "mpeg4video.h"
Data Structures
struct UnpackBFramesBSFContext
Functions
static unsigned int find_startcode (const uint8_t *buf, int buf_size, int *pos)
static void scan_buffer (const uint8_t *buf, int buf_size, int *pos_p, int *nb_vop, int *pos_vop2)
static uint8_t * create_new_buffer (const uint8_t *src, int size)
static int mpeg4_unpack_bframes_filter (AVBSFContext *ctx, AVPacket *out)
static int mpeg4_unpack_bframes_init (AVBSFContext *ctx)
static void mpeg4_unpack_bframes_close (AVBSFContext *bsfc)
Variables
static enum AVCodecID codec_ids []
const AVBitStreamFilter ff_mpeg4_unpack_bframes_bsf
Function Documentation
find_startcode()
static unsigned int find_startcode (const uint8_t * buf, int buf_size, int * pos) static
Definition at line 32 of file mpeg4_unpack_bframes_bsf.c.
Referenced by scan_buffer().
scan_buffer()
static void scan_buffer (const uint8_t * buf, int buf_size, int * pos_p, int * nb_vop, int * pos_vop2) static
Definition at line 49 of file mpeg4_unpack_bframes_bsf.c.
Referenced by mpeg4_unpack_bframes_filter(), and mpeg4_unpack_bframes_init().
create_new_buffer()
static uint8_t* create_new_buffer (const uint8_t * src, int size) static
Definition at line 75 of file mpeg4_unpack_bframes_bsf.c.
Referenced by mpeg4_unpack_bframes_filter().
mpeg4_unpack_bframes_filter()
static int mpeg4_unpack_bframes_filter (AVBSFContext * ctx, AVPacket * out) static
Definition at line 86 of file mpeg4_unpack_bframes_bsf.c.
mpeg4_unpack_bframes_init()
static int mpeg4_unpack_bframes_init (AVBSFContext * ctx) static
Definition at line 169 of file mpeg4_unpack_bframes_bsf.c.
mpeg4_unpack_bframes_close()
static void mpeg4_unpack_bframes_close (AVBSFContext * bsfc) static
Definition at line 184 of file mpeg4_unpack_bframes_bsf.c.
Variable Documentation
codec_ids
enum AVCodecID codec_ids[] static
Initial value:
= {
    AV_CODEC_ID_MPEG4, AV_CODEC_ID_NONE,
}
Definition at line 190 of file mpeg4_unpack_bframes_bsf.c.
ff_mpeg4_unpack_bframes_bsf
const AVBitStreamFilter ff_mpeg4_unpack_bframes_bsf
Initial value:
= {
    .name           = "mpeg4_unpack_bframes",
    .priv_data_size = sizeof(UnpackBFramesBSFContext),
    .init           = mpeg4_unpack_bframes_init,
    .filter         = mpeg4_unpack_bframes_filter,
    .close          = mpeg4_unpack_bframes_close,
    .codec_ids      = codec_ids,
}
Definition at line 194 of file mpeg4_unpack_bframes_bsf.c.