FFmpeg: libavformat/mpegenc.c File Reference
mpegenc.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/fifo.h"
#include "libavutil/log.h"
#include "libavutil/mathematics.h"
#include "libavutil/opt.h"
#include "libavcodec/put_bits.h"
#include "avformat.h"
#include "internal.h"
#include "mpeg.h"
Data Structures
struct PacketDesc
struct StreamInfo
struct MpegMuxContext
Macros
#define MAX_PAYLOAD_SIZE 4096
#define VCD_PADDING_BITRATE_DEN (2279 * 2294)
#define OFFSET(x) offsetof(MpegMuxContext, x)
#define E AV_OPT_FLAG_ENCODING_PARAM
#define MPEGENC_CLASS(flavor)
Functions
static int put_pack_header (AVFormatContext *ctx, uint8_t *buf, int64_t timestamp)
static int put_system_header (AVFormatContext *ctx, uint8_t *buf, int only_for_stream_id)
static int get_system_header_size (AVFormatContext *ctx)
static av_cold int mpeg_mux_init (AVFormatContext *ctx)
static void put_timestamp (AVIOContext *pb, int id, int64_t timestamp)
static int get_vcd_padding_size (AVFormatContext *ctx, int64_t pts)
static void put_padding_packet (AVFormatContext *ctx, AVIOContext *pb, int packet_bytes)
static int get_nb_frames (AVFormatContext *ctx, StreamInfo *stream, int len)
static int flush_packet (AVFormatContext *ctx, int stream_index, int64_t pts, int64_t dts, int64_t scr, int trailer_size)
static void put_vcd_padding_sector (AVFormatContext *ctx)
static int remove_decoded_packets (AVFormatContext *ctx, int64_t scr)
static int output_packet (AVFormatContext *ctx, int flush)
static int mpeg_mux_write_packet (AVFormatContext *ctx, AVPacket *pkt)
static int mpeg_mux_end (AVFormatContext *ctx)
Variables
AVOutputFormat ff_mpeg1vcd_muxer
AVOutputFormat ff_mpeg2dvd_muxer
AVOutputFormat ff_mpeg2svcd_muxer
AVOutputFormat ff_mpeg2vob_muxer
static const AVOption options []
Macro Definition Documentation
MAX_PAYLOAD_SIZE
#define MAX_PAYLOAD_SIZE 4096
Definition at line 36 of file mpegenc.c.
VCD_PADDING_BITRATE_DEN
#define VCD_PADDING_BITRATE_DEN (2279 * 2294)
Referenced by get_vcd_padding_size().
OFFSET
#define OFFSET (x) offsetof(MpegMuxContext, x)
Definition at line 1210 of file mpegenc.c.
E
#define E AV_OPT_FLAG_ENCODING_PARAM
Definition at line 1211 of file mpegenc.c.
MPEGENC_CLASS
#define MPEGENC_CLASS (flavor)
Value:
static const AVClass flavor ## _class = {       \
    .class_name = #flavor " muxer",             \
    .item_name  = av_default_item_name,         \
    .version    = LIBAVUTIL_VERSION_INT,        \
    .option     = options,                      \
};
Definition at line 1218 of file mpegenc.c.
Function Documentation
put_pack_header()
static int put_pack_header (AVFormatContext * ctx, uint8_t * buf, int64_t timestamp) static
Definition at line 91 of file mpegenc.c.
Referenced by flush_packet().
put_system_header()
static int put_system_header (AVFormatContext * ctx, uint8_t * buf, int only_for_stream_id) static
Definition at line 125 of file mpegenc.c.
Referenced by flush_packet().
get_system_header_size()
static int get_system_header_size (AVFormatContext * ctx) static
Definition at line 274 of file mpegenc.c.
Referenced by mpeg_mux_init().
mpeg_mux_init()
static av_cold int mpeg_mux_init (AVFormatContext * ctx) static
Definition at line 297 of file mpegenc.c.
put_timestamp()
static void put_timestamp (AVIOContext * pb, int id, int64_t timestamp) inline static
Definition at line 530 of file mpegenc.c.
Referenced by flush_packet().
get_vcd_padding_size()
static int get_vcd_padding_size (AVFormatContext * ctx, int64_t pts) static
Definition at line 539 of file mpegenc.c.
Referenced by output_packet().
put_padding_packet()
static void put_padding_packet (AVFormatContext * ctx, AVIOContext * pb, int packet_bytes) static
Definition at line 562 of file mpegenc.c.
Referenced by flush_packet().
get_nb_frames()
static int get_nb_frames (AVFormatContext * ctx, StreamInfo * stream, int len) static
Definition at line 580 of file mpegenc.c.
Referenced by flush_packet().
flush_packet()
static int flush_packet (AVFormatContext * ctx, int stream_index, int64_t pts, int64_t dts, int64_t scr, int trailer_size) static
Definition at line 596 of file mpegenc.c.
Referenced by output_packet().
put_vcd_padding_sector()
static void put_vcd_padding_sector (AVFormatContext * ctx) static
Definition at line 909 of file mpegenc.c.
Referenced by output_packet().
remove_decoded_packets()
static int remove_decoded_packets (AVFormatContext * ctx, int64_t scr) static
Definition at line 934 of file mpegenc.c.
Referenced by output_packet().
output_packet()
static int output_packet (AVFormatContext * ctx, int flush) static
Definition at line 961 of file mpegenc.c.
Referenced by mpeg_mux_end(), and mpeg_mux_write_packet().
mpeg_mux_write_packet()
static int mpeg_mux_write_packet (AVFormatContext * ctx, AVPacket * pkt) static
Definition at line 1107 of file mpegenc.c.
mpeg_mux_end()
static int mpeg_mux_end (AVFormatContext * ctx) static
Definition at line 1182 of file mpegenc.c.
Variable Documentation
ff_mpeg1vcd_muxer
AVOutputFormat ff_mpeg1vcd_muxer
Referenced by mpeg_mux_init().
ff_mpeg2dvd_muxer
AVOutputFormat ff_mpeg2dvd_muxer
Referenced by mpeg_mux_init().
ff_mpeg2svcd_muxer
AVOutputFormat ff_mpeg2svcd_muxer
Referenced by mpeg_mux_init().
ff_mpeg2vob_muxer
AVOutputFormat ff_mpeg2vob_muxer
Referenced by mpeg_mux_init().
options
const AVOption options[] static
Initial value:
= {
    { "muxrate", NULL,                                          OFFSET(user_mux_rate), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, ((1<<22) - 1) * (8 * 50), E },
    { "preload", "Initial demux-decode delay in microseconds.", OFFSET(preload),  AV_OPT_TYPE_INT, { .i64 = 500000 }, 0, INT_MAX, E },
    { NULL },
}
Definition at line 1212 of file mpegenc.c.