FFmpeg: libavcodec/x86/mpegvideoencdsp_init.c File Reference
mpegvideoencdsp_init.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/avassert.h"
#include "libavutil/cpu.h"
#include "libavutil/x86/cpu.h"
#include "libavcodec/avcodec.h"
#include "libavcodec/mpegvideoencdsp.h"
Functions
int ff_pix_sum16_mmx (uint8_t *pix, int line_size)
int ff_pix_sum16_mmxext (uint8_t *pix, int line_size)
int ff_pix_sum16_sse2 (uint8_t *pix, int line_size)
int ff_pix_sum16_xop (uint8_t *pix, int line_size)
int ff_pix_norm1_mmx (uint8_t *pix, int line_size)
int ff_pix_norm1_sse2 (uint8_t *pix, int line_size)
av_cold void ff_mpegvideoencdsp_init_x86 (MpegvideoEncDSPContext *c, AVCodecContext *avctx)
Function Documentation
ff_pix_sum16_mmx()
int ff_pix_sum16_mmx (uint8_t * pix, int line_size)
Referenced by ff_mpegvideoencdsp_init_x86().
ff_pix_sum16_mmxext()
int ff_pix_sum16_mmxext (uint8_t * pix, int line_size)
Referenced by ff_mpegvideoencdsp_init_x86().
ff_pix_sum16_sse2()
int ff_pix_sum16_sse2 (uint8_t * pix, int line_size)
Referenced by ff_mpegvideoencdsp_init_x86().
ff_pix_sum16_xop()
int ff_pix_sum16_xop (uint8_t * pix, int line_size)
Referenced by ff_mpegvideoencdsp_init_x86().
ff_pix_norm1_mmx()
int ff_pix_norm1_mmx (uint8_t * pix, int line_size)
Referenced by ff_mpegvideoencdsp_init_x86().
ff_pix_norm1_sse2()
int ff_pix_norm1_sse2 (uint8_t * pix, int line_size)
Referenced by ff_mpegvideoencdsp_init_x86().
ff_mpegvideoencdsp_init_x86()
av_cold void ff_mpegvideoencdsp_init_x86 (MpegvideoEncDSPContext * c, AVCodecContext * avctx)
Definition at line 217 of file mpegvideoencdsp_init.c.
Referenced by ff_mpegvideoencdsp_init().