FFmpeg: libavcodec/mpegvideoencdsp.c File Reference
mpegvideoencdsp.c File Reference
#include <assert.h>
#include <stdint.h>
#include <string.h>
#include "config.h"
#include "libavutil/avassert.h"
#include "libavutil/attributes.h"
#include "libavutil/imgutils.h"
#include "avcodec.h"
#include "me_cmp.h"
#include "mpegvideoencdsp.h"
Functions
static int try_8x8basis_c (int16_t rem[64], int16_t weight[64], int16_t basis[64], int scale)
static void add_8x8basis_c (int16_t rem[64], int16_t basis[64], int scale)
static int pix_sum_c (uint8_t *pix, int line_size)
static int pix_norm1_c (uint8_t *pix, int line_size)
static void draw_edges_8_c (uint8_t *buf, int wrap, int width, int height, int w, int h, int sides)
static void shrink22 (uint8_t *dst, int dst_wrap, const uint8_t *src, int src_wrap, int width, int height)
static void shrink44 (uint8_t *dst, int dst_wrap, const uint8_t *src, int src_wrap, int width, int height)
static void shrink88 (uint8_t *dst, int dst_wrap, const uint8_t *src, int src_wrap, int width, int height)
av_cold void ff_mpegvideoencdsp_init (MpegvideoEncDSPContext *c, AVCodecContext *avctx)
Function Documentation
try_8x8basis_c()
static int try_8x8basis_c (int16_t rem[64], int16_t weight[64], int16_t basis[64], int scale) static
Definition at line 31 of file mpegvideoencdsp.c.
Referenced by ff_mpegvideoencdsp_init().
add_8x8basis_c()
static void add_8x8basis_c (int16_t rem[64], int16_t basis[64], int scale) static
Definition at line 50 of file mpegvideoencdsp.c.
Referenced by ff_mpegvideoencdsp_init().
pix_sum_c()
static int pix_sum_c (uint8_t * pix, int line_size) static
Definition at line 60 of file mpegvideoencdsp.c.
Referenced by ff_mpegvideoencdsp_init().
pix_norm1_c()
static int pix_norm1_c (uint8_t * pix, int line_size) static
Definition at line 81 of file mpegvideoencdsp.c.
Referenced by ff_mpegvideoencdsp_init().
draw_edges_8_c()
static void draw_edges_8_c (uint8_t * buf, int wrap, int width, int height, int w, int h, int sides) static
Definition at line 130 of file mpegvideoencdsp.c.
Referenced by ff_mpegvideoencdsp_init().
shrink22()
static void shrink22 (uint8_t * dst, int dst_wrap, const uint8_t * src, int src_wrap, int width, int height) static
Definition at line 157 of file mpegvideoencdsp.c.
Referenced by ff_mpegvideoencdsp_init().
shrink44()
static void shrink44 (uint8_t * dst, int dst_wrap, const uint8_t * src, int src_wrap, int width, int height) static
Definition at line 190 of file mpegvideoencdsp.c.
Referenced by ff_mpegvideoencdsp_init().
shrink88()
static void shrink88 (uint8_t * dst, int dst_wrap, const uint8_t * src, int src_wrap, int width, int height) static
Definition at line 221 of file mpegvideoencdsp.c.
Referenced by ff_mpegvideoencdsp_init().
ff_mpegvideoencdsp_init()
av_cold void ff_mpegvideoencdsp_init (MpegvideoEncDSPContext * c, AVCodecContext * avctx)
Definition at line 243 of file mpegvideoencdsp.c.
Referenced by dirac_decode_init(), dnxhd_encode_init(), encode_init(), ff_mpv_encode_init(), and svq1_encode_init().