FFmpeg: libavcodec/alpha/mpegvideo_alpha.c File Reference
mpegvideo_alpha.c File Reference
#include "libavutil/attributes.h"
#include "libavcodec/mpegvideo.h"
#include "asm.h"
Functions
static void dct_unquantize_h263_axp (int16_t *block, int n_coeffs, uint64_t qscale, uint64_t qadd)
static void dct_unquantize_h263_intra_axp (MpegEncContext *s, int16_t *block, int n, int qscale)
static void dct_unquantize_h263_inter_axp (MpegEncContext *s, int16_t *block, int n, int qscale)
av_cold void ff_mpv_common_init_axp (MpegEncContext *s)
Function Documentation
dct_unquantize_h263_axp()
static void dct_unquantize_h263_axp (int16_t * block, int n_coeffs, uint64_t qscale, uint64_t qadd) static
Definition at line 26 of file mpegvideo_alpha.c.
Referenced by dct_unquantize_h263_inter_axp(), and dct_unquantize_h263_intra_axp().
dct_unquantize_h263_intra_axp()
static void dct_unquantize_h263_intra_axp (MpegEncContext * s, int16_t * block, int n, int qscale) static
Definition at line 72 of file mpegvideo_alpha.c.
Referenced by ff_mpv_common_init_axp().
dct_unquantize_h263_inter_axp()
static void dct_unquantize_h263_inter_axp (MpegEncContext * s, int16_t * block, int n, int qscale) static
Definition at line 99 of file mpegvideo_alpha.c.
Referenced by ff_mpv_common_init_axp().
ff_mpv_common_init_axp()
av_cold void ff_mpv_common_init_axp (MpegEncContext * s)
Definition at line 106 of file mpegvideo_alpha.c.
Referenced by dct_init().