FFmpeg: libavcodec/mpeg12.h File Reference
mpeg12.h File Reference
#include "mpeg12vlc.h"
#include "mpegvideo.h"
Functions
void ff_mpeg12_common_init (MpegEncContext *s)
static int decode_dc (GetBitContext *gb, int component)
int ff_mpeg1_decode_block_intra (GetBitContext *gb, const uint16_t *quant_matrix, uint8_t *const scantable, int last_dc[3], int16_t *block, int index, int qscale)
void ff_mpeg1_clean_buffers (MpegEncContext *s)
int ff_mpeg1_find_frame_end (ParseContext *pc, const uint8_t *buf, int buf_size, AVCodecParserContext *s)
Find the end of the current frame in the bitstream.
void ff_mpeg1_encode_picture_header (MpegEncContext *s, int picture_number)
void ff_mpeg1_encode_mb (MpegEncContext *s, int16_t block[8][64], int motion_x, int motion_y)
void ff_mpeg1_encode_init (MpegEncContext *s)
void ff_mpeg1_encode_slice_header (MpegEncContext *s)
Variables
uint8_t ff_mpeg12_static_rl_table_store [2][2][2 *MAX_RUN+MAX_LEVEL+3]
Function Documentation
ff_mpeg12_common_init()
void ff_mpeg12_common_init (MpegEncContext * s)
Definition at line 114 of file mpeg12.c.
Referenced by ff_mpeg1_encode_init(), and mpeg_decode_init().
decode_dc()
static int decode_dc (GetBitContext * gb, int component) inline static
Definition at line 32 of file mpeg12.h.
Referenced by ff_mpeg1_decode_block_intra(), mdec_decode_block_intra(), mpeg2_decode_block_intra(), and mpeg2_fast_decode_block_intra().
ff_mpeg1_decode_block_intra()
int ff_mpeg1_decode_block_intra (GetBitContext * gb, const uint16_t * quant_matrix, uint8_t *const scantable, int last_dc[3], int16_t * block, int index, int qscale)
Definition at line 247 of file mpeg12.c.
Referenced by decode_dc(), mpeg_decode_mb(), and tqi_decode_mb().
ff_mpeg1_clean_buffers()
void ff_mpeg1_clean_buffers (MpegEncContext * s)
Definition at line 122 of file mpeg12.c.
Referenced by decode_dc(), encode_thread(), and mpeg_decode_slice().
ff_mpeg1_find_frame_end()
int ff_mpeg1_find_frame_end (ParseContext * pc, const uint8_t * buf, int buf_size, AVCodecParserContext * s)
Find the end of the current frame in the bitstream.
Returns
the position of the first byte of the next frame, or -1
Definition at line 185 of file mpeg12.c.
Referenced by decode_dc(), mpeg_decode_frame(), and mpegvideo_parse().
ff_mpeg1_encode_picture_header()
void ff_mpeg1_encode_picture_header (MpegEncContext * s, int picture_number)
Definition at line 421 of file mpeg12enc.c.
Referenced by decode_dc(), and encode_picture().
ff_mpeg1_encode_mb()
void ff_mpeg1_encode_mb (MpegEncContext * s, int16_t block[8][64], int motion_x, int motion_y)
Definition at line 993 of file mpeg12enc.c.
Referenced by decode_dc(), and encode_mb_internal().
ff_mpeg1_encode_init()
void ff_mpeg1_encode_init (MpegEncContext * s)
Definition at line 1002 of file mpeg12enc.c.
Referenced by decode_dc(), and ff_mpv_encode_init().
ff_mpeg1_encode_slice_header()
void ff_mpeg1_encode_slice_header (MpegEncContext * s)
Definition at line 407 of file mpeg12enc.c.
Referenced by decode_dc(), encode_thread(), and ff_mpeg1_encode_picture_header().
Variable Documentation
ff_mpeg12_static_rl_table_store
uint8_t ff_mpeg12_static_rl_table_store[2][2][2 *MAX_RUN+MAX_LEVEL+3]
Definition at line 44 of file mpeg12.c.
Referenced by ff_mpeg12_init_vlcs(), and ff_mpeg1_encode_init().