FFmpeg: libavcodec/mpegvideodsp.h File Reference
mpegvideodsp.h File Reference
#include <stdint.h>
Data Structures
struct MpegVideoDSPContext
Functions
void ff_gmc_c (uint8_t *dst, uint8_t *src, int stride, int h, int ox, int oy, int dxx, int dxy, int dyx, int dyy, int shift, int r, int width, int height)
void ff_mpegvideodsp_init (MpegVideoDSPContext *c)
void ff_mpegvideodsp_init_ppc (MpegVideoDSPContext *c)
void ff_mpegvideodsp_init_x86 (MpegVideoDSPContext *c)
Function Documentation
ff_gmc_c()
void ff_gmc_c (uint8_t * dst, uint8_t * src, int stride, int h, int ox, int oy, int dxx, int dxy, int dyx, int dyy, int shift, int r, int width, int height)
Definition at line 47 of file mpegvideodsp.c.
Referenced by ff_mpegvideodsp_init().
ff_mpegvideodsp_init()
void ff_mpegvideodsp_init (MpegVideoDSPContext * c)
Definition at line 110 of file mpegvideodsp.c.
Referenced by dct_init().
ff_mpegvideodsp_init_ppc()
void ff_mpegvideodsp_init_ppc (MpegVideoDSPContext * c)
Definition at line 128 of file mpegvideodsp.c.
Referenced by ff_mpegvideodsp_init().
ff_mpegvideodsp_init_x86()
void ff_mpegvideodsp_init_x86 (MpegVideoDSPContext * c)
Definition at line 152 of file mpegvideodsp.c.
Referenced by ff_mpegvideodsp_init().