FFmpeg: libavcodec/mpegaudiodsp.c File Reference
mpegaudiodsp.c File Reference
#include "config.h"
#include "libavutil/attributes.h"
#include "mpegaudiodsp.h"
#include "dct.h"
#include "dct32.h"
Functions
av_cold void ff_mpadsp_init (MPADSPContext *s)
Function Documentation
ff_mpadsp_init()
av_cold void ff_mpadsp_init (MPADSPContext * s)
Definition at line 27 of file mpegaudiodsp.c.
Referenced by decode_init(), mpc7_decode_init(), mpc8_decode_init(), and qdm2_decode_init().