FFmpeg: libavcodec/mpeg4video.c File Reference
mpeg4video.c File Reference
#include "mpegutils.h"
#include "mpegvideo.h"
#include "mpeg4video.h"
#include "mpeg4data.h"
Macros
#define tab_size ((signed)FF_ARRAY_ELEMS(s->direct_scale_mv[0]))
#define tab_bias (tab_size / 2)
Functions
int ff_mpeg4_get_video_packet_prefix_length (MpegEncContext *s)
void ff_mpeg4_clean_buffers (MpegEncContext *s)
void ff_mpeg4_init_direct_mv (MpegEncContext *s)
static void ff_mpeg4_set_one_direct_mv (MpegEncContext *s, int mx, int my, int i)
int ff_mpeg4_set_direct_mv (MpegEncContext *s, int mx, int my)
Variables
uint8_t ff_mpeg4_static_rl_table_store [3][2][2 *MAX_RUN+MAX_LEVEL+3]
Macro Definition Documentation
tab_size
#define tab_size ((signed)FF_ARRAY_ELEMS(s->direct_scale_mv[0]))
Definition at line 67 of file mpeg4video.c.
Referenced by ff_mpeg4_init_direct_mv(), and ff_mpeg4_set_one_direct_mv().
tab_bias
#define tab_bias (tab_size / 2)
Definition at line 68 of file mpeg4video.c.
Referenced by ff_mpeg4_init_direct_mv(), and ff_mpeg4_set_one_direct_mv().
Function Documentation
ff_mpeg4_get_video_packet_prefix_length()
int ff_mpeg4_get_video_packet_prefix_length (MpegEncContext * s)
Definition at line 30 of file mpeg4video.c.
Referenced by ff_mpeg4_decode_video_packet_header(), ff_mpeg4_encode_video_packet_header(), and mpeg4_is_resync().
ff_mpeg4_clean_buffers()
void ff_mpeg4_clean_buffers (MpegEncContext * s)
Definition at line 45 of file mpeg4video.c.
Referenced by encode_thread(), ff_h263_decode_frame(), and ff_msmpeg4_handle_slices().
ff_mpeg4_init_direct_mv()
void ff_mpeg4_init_direct_mv (MpegEncContext * s)
Definition at line 71 of file mpeg4video.c.
Referenced by decode_vop_header(), ff_h263_decode_picture_header(), ff_set_mpeg4_time(), and rv20_decode_picture_header().
ff_mpeg4_set_one_direct_mv()
static void ff_mpeg4_set_one_direct_mv (MpegEncContext * s, int mx, int my, int i) inline static
Definition at line 81 of file mpeg4video.c.
Referenced by ff_mpeg4_set_direct_mv().
ff_mpeg4_set_direct_mv()
int ff_mpeg4_set_direct_mv (MpegEncContext * s, int mx, int my)
Returns
the mb_type
Definition at line 117 of file mpeg4video.c.
Referenced by encode_thread(), ff_h263_decode_mb(), and mpeg4_decode_mb().
Variable Documentation
ff_mpeg4_static_rl_table_store
uint8_t ff_mpeg4_static_rl_table_store[3][2][2 *MAX_RUN+MAX_LEVEL+3]
Definition at line 28 of file mpeg4video.c.
Referenced by encode_init(), and ff_mpeg4videodec_static_init().