FFmpeg: libavcodec/arm/mpegvideo_arm.c File Reference
mpegvideo_arm.c File Reference
#include "libavutil/internal.h"
#include "libavutil/arm/cpu.h"
#include "libavcodec/avcodec.h"
#include "libavcodec/mpegvideo.h"
#include "mpegvideo_arm.h"
#include "asm-offsets.h"
Functions
void ff_dct_unquantize_h263_inter_neon (MpegEncContext *s, int16_t *block, int n, int qscale)
void ff_dct_unquantize_h263_intra_neon (MpegEncContext *s, int16_t *block, int n, int qscale)
av_cold void ff_mpv_common_init_arm (MpegEncContext *s)
Function Documentation
ff_dct_unquantize_h263_inter_neon()
void ff_dct_unquantize_h263_inter_neon (MpegEncContext * s, int16_t * block, int n, int qscale)
Referenced by ff_mpv_common_init_arm().
ff_dct_unquantize_h263_intra_neon()
void ff_dct_unquantize_h263_intra_neon (MpegEncContext * s, int16_t * block, int n, int qscale)
Referenced by ff_mpv_common_init_arm().
ff_mpv_common_init_arm()
av_cold void ff_mpv_common_init_arm (MpegEncContext * s)
Definition at line 43 of file mpegvideo_arm.c.
Referenced by dct_init().