FFmpeg: libavcodec/mpeg4video_parser.c File Reference
mpeg4video_parser.c File Reference
#include "internal.h"
#include "parser.h"
#include "mpegvideo.h"
#include "mpeg4video.h"
#include "mpeg4video_parser.h"
Data Structures
struct Mp4vParseContext
Macros
#define UNCHECKED_BITSTREAM_READER 1
Functions
int ff_mpeg4_find_frame_end (ParseContext *pc, const uint8_t *buf, int buf_size)
Find the end of the current frame in the bitstream.
static int mpeg4_decode_header (AVCodecParserContext *s1, AVCodecContext *avctx, const uint8_t *buf, int buf_size)
static av_cold int mpeg4video_parse_init (AVCodecParserContext *s)
static int mpeg4video_parse (AVCodecParserContext *s, AVCodecContext *avctx, const uint8_t **poutbuf, int *poutbuf_size, const uint8_t *buf, int buf_size)
Variables
AVCodecParser ff_mpeg4video_parser
Macro Definition Documentation
UNCHECKED_BITSTREAM_READER
#define UNCHECKED_BITSTREAM_READER 1
Definition at line 23 of file mpeg4video_parser.c.
Function Documentation
ff_mpeg4_find_frame_end()
int ff_mpeg4_find_frame_end (ParseContext * pc, const uint8_t * buf, int buf_size)
Find the end of the current frame in the bitstream.
Returns
the position of the first byte of the next frame, or -1
Definition at line 37 of file mpeg4video_parser.c.
Referenced by ff_h263_decode_frame(), and mpeg4video_parse().
mpeg4_decode_header()
static int mpeg4_decode_header (AVCodecParserContext * s1, AVCodecContext * avctx, const uint8_t * buf, int buf_size) static
Definition at line 76 of file mpeg4video_parser.c.
Referenced by mpeg4video_parse().
mpeg4video_parse_init()
static av_cold int mpeg4video_parse_init (AVCodecParserContext * s) static
Definition at line 115 of file mpeg4video_parser.c.
mpeg4video_parse()
static int mpeg4video_parse (AVCodecParserContext * s, AVCodecContext * avctx, const uint8_t ** poutbuf, int * poutbuf_size, const uint8_t * buf, int buf_size) static
Definition at line 128 of file mpeg4video_parser.c.
Variable Documentation
ff_mpeg4video_parser
AVCodecParser ff_mpeg4video_parser
Initial value:
= {
    .codec_ids      = { AV_CODEC_ID_MPEG4 },
    .priv_data_size = sizeof(struct Mp4vParseContext),
    .parser_init    = mpeg4video_parse_init,
    .parser_parse   = mpeg4video_parse,
    .parser_close   = ff_parse_close,
    .split          = ff_mpeg4video_split,
}
Definition at line 154 of file mpeg4video_parser.c.