FFmpeg: libavcodec/mips/mpegvideo_msa.c File Reference
mpegvideo_msa.c File Reference
#include "libavutil/mips/generic_macros_msa.h"
#include "h263dsp_mips.h"
Functions
static void h263_dct_unquantize_msa (int16_t *block, int16_t qmul, int16_t qadd, int8_t n_coeffs, uint8_t loop_start)
static int32_t mpeg2_dct_unquantize_inter_msa (int16_t *block, int32_t qscale, const int16_t *quant_matrix)
void ff_dct_unquantize_h263_intra_msa (MpegEncContext *s, int16_t *block, int32_t index, int32_t qscale)
void ff_dct_unquantize_h263_inter_msa (MpegEncContext *s, int16_t *block, int32_t index, int32_t qscale)
void ff_dct_unquantize_mpeg2_inter_msa (MpegEncContext *s, int16_t *block, int32_t index, int32_t qscale)
Function Documentation
h263_dct_unquantize_msa()
static void h263_dct_unquantize_msa (int16_t * block, int16_t qmul, int16_t qadd, int8_t n_coeffs, uint8_t loop_start) static
Definition at line 24 of file mpegvideo_msa.c.
Referenced by ff_dct_unquantize_h263_inter_msa(), and ff_dct_unquantize_h263_intra_msa().
mpeg2_dct_unquantize_inter_msa()
static int32_t mpeg2_dct_unquantize_inter_msa (int16_t * block, int32_t qscale, const int16_t * quant_matrix) static
Definition at line 64 of file mpegvideo_msa.c.
Referenced by ff_dct_unquantize_mpeg2_inter_msa().
ff_dct_unquantize_h263_intra_msa()
void ff_dct_unquantize_h263_intra_msa (MpegEncContext * s, int16_t * block, int32_t index, int32_t qscale)
Definition at line 196 of file mpegvideo_msa.c.
ff_dct_unquantize_h263_inter_msa()
void ff_dct_unquantize_h263_inter_msa (MpegEncContext * s, int16_t * block, int32_t index, int32_t qscale)
Definition at line 221 of file mpegvideo_msa.c.
ff_dct_unquantize_mpeg2_inter_msa()
void ff_dct_unquantize_mpeg2_inter_msa (MpegEncContext * s, int16_t * block, int32_t index, int32_t qscale)
Definition at line 238 of file mpegvideo_msa.c.