FFmpeg: libavformat/mpegtsenc.c File Reference
mpegtsenc.c File Reference
#include "libavutil/avassert.h"
#include "libavutil/bswap.h"
#include "libavutil/crc.h"
#include "libavutil/dict.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/mathematics.h"
#include "libavutil/opt.h"
#include "libavcodec/internal.h"
#include "avformat.h"
#include "avio_internal.h"
#include "internal.h"
#include "mpegts.h"
Data Structures
struct MpegTSSection
struct MpegTSService
struct MpegTSWrite
struct MpegTSWriteStream
Macros
#define PCR_TIME_BASE 27000000
#define DVB_PRIVATE_NETWORK_START 0xff01
#define MPEGTS_FLAG_REEMIT_PAT_PMT 0x01
#define MPEGTS_FLAG_AAC_LATM 0x02
#define MPEGTS_FLAG_PAT_PMT_AT_FRAMES 0x04
#define MPEGTS_FLAG_SYSTEM_B 0x08
#define MPEGTS_FLAG_DISCONT 0x10
#define DEFAULT_PES_HEADER_FREQ 16
#define DEFAULT_PES_PAYLOAD_SIZE ((DEFAULT_PES_HEADER_FREQ - 1) * 184 + 170)
#define SECTION_LENGTH 1020
#define DEFAULT_PROVIDER_NAME "FFmpeg"
#define DEFAULT_SERVICE_NAME "Service01"
#define SDT_RETRANS_TIME 500
#define PAT_RETRANS_TIME 100
#define PCR_RETRANS_TIME 20
Enumerations
enum {
MPEGTS_SERVICE_TYPE_DIGITAL_TV = 0x01, MPEGTS_SERVICE_TYPE_DIGITAL_RADIO = 0x02, MPEGTS_SERVICE_TYPE_TELETEXT = 0x03, MPEGTS_SERVICE_TYPE_ADVANCED_CODEC_DIGITAL_RADIO = 0x0A,
MPEGTS_SERVICE_TYPE_MPEG2_DIGITAL_HDTV = 0x11, MPEGTS_SERVICE_TYPE_ADVANCED_CODEC_DIGITAL_SDTV = 0x16, MPEGTS_SERVICE_TYPE_ADVANCED_CODEC_DIGITAL_HDTV = 0x19, MPEGTS_SERVICE_TYPE_HEVC_DIGITAL_HDTV = 0x1F
}
Functions
static void mpegts_write_section (MpegTSSection *s, uint8_t *buf, int len)
static void put16 (uint8_t **q_ptr, int val)
static int mpegts_write_section1 (MpegTSSection *s, int tid, int id, int version, int sec_num, int last_sec_num, uint8_t *buf, int len)
static void mpegts_write_pat (AVFormatContext *s)
static void putstr8 (uint8_t **q_ptr, const char *str, int write_len)
static int mpegts_write_pmt (AVFormatContext *s, MpegTSService *service)
static void mpegts_write_sdt (AVFormatContext *s)
static MpegTSService * mpegts_add_service (MpegTSWrite *ts, int sid, const char *provider_name, const char *name)
static int64_t get_pcr (const MpegTSWrite *ts, AVIOContext *pb)
static void mpegts_prefix_m2ts_header (AVFormatContext *s)
static void section_write_packet (MpegTSSection *s, const uint8_t *packet)
static int mpegts_init (AVFormatContext *s)
static void retransmit_si_info (AVFormatContext *s, int force_pat, int64_t dts)
static int write_pcr_bits (uint8_t *buf, int64_t pcr)
static void mpegts_insert_null_packet (AVFormatContext *s)
static void mpegts_insert_pcr_only (AVFormatContext *s, AVStream *st)
static void write_pts (uint8_t *q, int fourbits, int64_t pts)
static void set_af_flag (uint8_t *pkt, int flag)
static void extend_af (uint8_t *pkt, int size)
static uint8_t * get_ts_payload_start (uint8_t *pkt)
static void mpegts_write_pes (AVFormatContext *s, AVStream *st, const uint8_t *payload, int payload_size, int64_t pts, int64_t dts, int key, int stream_id)
int ff_check_h264_startcode (AVFormatContext *s, const AVStream *st, const AVPacket *pkt)
Check presence of H264 startcode.
static int check_hevc_startcode (AVFormatContext *s, const AVStream *st, const AVPacket *pkt)
static int opus_get_packet_samples (AVFormatContext *s, AVPacket *pkt)
static int mpegts_write_packet_internal (AVFormatContext *s, AVPacket *pkt)
static void mpegts_write_flush (AVFormatContext *s)
static int mpegts_write_packet (AVFormatContext *s, AVPacket *pkt)
static int mpegts_write_end (AVFormatContext *s)
static void mpegts_deinit (AVFormatContext *s)
static int mpegts_check_bitstream (struct AVFormatContext *s, const AVPacket *pkt)
Variables
static const AVOption options []
static const AVClass mpegts_muxer_class
AVOutputFormat ff_mpegts_muxer
Macro Definition Documentation
PCR_TIME_BASE
#define PCR_TIME_BASE 27000000
Definition at line 37 of file mpegtsenc.c.
Referenced by get_pcr(), and mpegts_init().
DVB_PRIVATE_NETWORK_START
#define DVB_PRIVATE_NETWORK_START 0xff01
Definition at line 41 of file mpegtsenc.c.
MPEGTS_FLAG_REEMIT_PAT_PMT
#define MPEGTS_FLAG_REEMIT_PAT_PMT 0x01
Definition at line 104 of file mpegtsenc.c.
Referenced by mpegts_write_packet_internal().
MPEGTS_FLAG_AAC_LATM
#define MPEGTS_FLAG_AAC_LATM 0x02
Definition at line 105 of file mpegtsenc.c.
Referenced by mpegts_init(), and mpegts_write_pmt().
MPEGTS_FLAG_PAT_PMT_AT_FRAMES
#define MPEGTS_FLAG_PAT_PMT_AT_FRAMES 0x04
Definition at line 106 of file mpegtsenc.c.
Referenced by mpegts_write_pes().
MPEGTS_FLAG_SYSTEM_B
#define MPEGTS_FLAG_SYSTEM_B 0x08
Definition at line 107 of file mpegtsenc.c.
Referenced by mpegts_write_pmt().
MPEGTS_FLAG_DISCONT
#define MPEGTS_FLAG_DISCONT 0x10
Definition at line 108 of file mpegtsenc.c.
Referenced by mpegts_init().
DEFAULT_PES_HEADER_FREQ
#define DEFAULT_PES_HEADER_FREQ 16
Definition at line 121 of file mpegtsenc.c.
DEFAULT_PES_PAYLOAD_SIZE
#define DEFAULT_PES_PAYLOAD_SIZE ((DEFAULT_PES_HEADER_FREQ - 1) * 184 + 170)
Definition at line 122 of file mpegtsenc.c.
SECTION_LENGTH
#define SECTION_LENGTH 1020
Definition at line 126 of file mpegtsenc.c.
Referenced by mpegts_write_pat(), mpegts_write_pmt(), and mpegts_write_sdt().
DEFAULT_PROVIDER_NAME
#define DEFAULT_PROVIDER_NAME "FFmpeg"
Definition at line 222 of file mpegtsenc.c.
Referenced by mpegts_init().
DEFAULT_SERVICE_NAME
#define DEFAULT_SERVICE_NAME "Service01"
Definition at line 223 of file mpegtsenc.c.
Referenced by mpegts_init().
SDT_RETRANS_TIME
#define SDT_RETRANS_TIME 500
Definition at line 226 of file mpegtsenc.c.
Referenced by mpegts_init().
PAT_RETRANS_TIME
#define PAT_RETRANS_TIME 100
Definition at line 227 of file mpegtsenc.c.
Referenced by mpegts_init().
PCR_RETRANS_TIME
#define PCR_RETRANS_TIME 20
Definition at line 228 of file mpegtsenc.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MPEGTS_SERVICE_TYPE_DIGITAL_TV
MPEGTS_SERVICE_TYPE_DIGITAL_RADIO
MPEGTS_SERVICE_TYPE_TELETEXT
MPEGTS_SERVICE_TYPE_ADVANCED_CODEC_DIGITAL_RADIO
MPEGTS_SERVICE_TYPE_MPEG2_DIGITAL_HDTV
MPEGTS_SERVICE_TYPE_ADVANCED_CODEC_DIGITAL_SDTV
MPEGTS_SERVICE_TYPE_ADVANCED_CODEC_DIGITAL_HDTV
MPEGTS_SERVICE_TYPE_HEVC_DIGITAL_HDTV
Definition at line 66 of file mpegtsenc.c.
Function Documentation
mpegts_write_section()
static void mpegts_write_section (MpegTSSection * s, uint8_t * buf, int len) static
Definition at line 129 of file mpegtsenc.c.
Referenced by mpegts_write_section1().
put16()
static void put16 (uint8_t ** q_ptr, int val) inline static
Definition at line 183 of file mpegtsenc.c.
Referenced by mpegts_write_pat(), mpegts_write_pmt(), mpegts_write_sdt(), and mpegts_write_section1().
mpegts_write_section1()
static int mpegts_write_section1 (MpegTSSection * s, int tid, int id, int version, int sec_num, int last_sec_num, uint8_t * buf, int len) static
Definition at line 192 of file mpegtsenc.c.
Referenced by mpegts_write_pat(), mpegts_write_pmt(), and mpegts_write_sdt().
mpegts_write_pat()
static void mpegts_write_pat (AVFormatContext * s) static
Definition at line 250 of file mpegtsenc.c.
Referenced by retransmit_si_info().
putstr8()
static void putstr8 (uint8_t ** q_ptr, const char * str, int write_len) static
Definition at line 268 of file mpegtsenc.c.
Referenced by mpegts_write_pmt(), and mpegts_write_sdt().
mpegts_write_pmt()
static int mpegts_write_pmt (AVFormatContext * s, MpegTSService * service) static
Definition at line 285 of file mpegtsenc.c.
Referenced by retransmit_si_info().
mpegts_write_sdt()
static void mpegts_write_sdt (AVFormatContext * s) static
Definition at line 670 of file mpegtsenc.c.
Referenced by retransmit_si_info().
mpegts_add_service()
static MpegTSService* mpegts_add_service (MpegTSWrite * ts, int sid, const char * provider_name, const char * name) static
Definition at line 708 of file mpegtsenc.c.
Referenced by mpegts_init().
get_pcr()
static int64_t get_pcr (const MpegTSWrite * ts, AVIOContext * pb) static
Definition at line 735 of file mpegtsenc.c.
Referenced by mpegts_insert_pcr_only(), mpegts_prefix_m2ts_header(), and mpegts_write_pes().
mpegts_prefix_m2ts_header()
static void mpegts_prefix_m2ts_header (AVFormatContext * s) static
Definition at line 741 of file mpegtsenc.c.
Referenced by mpegts_insert_null_packet(), mpegts_insert_pcr_only(), mpegts_write_pes(), and section_write_packet().
section_write_packet()
static void section_write_packet (MpegTSSection * s, const uint8_t * packet) static
Definition at line 753 of file mpegtsenc.c.
Referenced by mpegts_init().
mpegts_init()
static int mpegts_init (AVFormatContext * s) static
Definition at line 760 of file mpegtsenc.c.
retransmit_si_info()
static void retransmit_si_info (AVFormatContext * s, int force_pat, int64_t dts) static
Definition at line 1026 of file mpegtsenc.c.
Referenced by mpegts_write_pes().
write_pcr_bits()
static int write_pcr_bits (uint8_t * buf, int64_t pcr) static
Definition at line 1053 of file mpegtsenc.c.
Referenced by mpegts_insert_pcr_only(), and mpegts_write_pes().
mpegts_insert_null_packet()
static void mpegts_insert_null_packet (AVFormatContext * s) static
Definition at line 1068 of file mpegtsenc.c.
Referenced by mpegts_write_pes().
mpegts_insert_pcr_only()
static void mpegts_insert_pcr_only (AVFormatContext * s, AVStream * st) static
Definition at line 1084 of file mpegtsenc.c.
Referenced by mpegts_write_pes().
write_pts()
static void write_pts (uint8_t * q, int fourbits, int64_t pts) static
Definition at line 1113 of file mpegtsenc.c.
Referenced by mpegts_write_pes().
set_af_flag()
static void set_af_flag (uint8_t * pkt, int flag) static
Definition at line 1128 of file mpegtsenc.c.
Referenced by mpegts_write_pes().
extend_af()
static void extend_af (uint8_t * pkt, int size) static
Definition at line 1144 of file mpegtsenc.c.
Referenced by mpegts_write_pes().
get_ts_payload_start()
static uint8_t* get_ts_payload_start (uint8_t * pkt) static
Definition at line 1152 of file mpegtsenc.c.
Referenced by mpegts_write_pes().
mpegts_write_pes()
static void mpegts_write_pes (AVFormatContext * s, AVStream * st, const uint8_t * payload, int payload_size, int64_t pts, int64_t dts, int key, int stream_id) static
Definition at line 1164 of file mpegtsenc.c.
Referenced by mpegts_write_flush(), and mpegts_write_packet_internal().
ff_check_h264_startcode()
int ff_check_h264_startcode (AVFormatContext * s, const AVStream * st, const AVPacket * pkt)
Check presence of H264 startcode.
Returns
<0 to stop processing
Definition at line 1426 of file mpegtsenc.c.
Referenced by avi_write_packet(), mpegts_write_packet_internal(), and write_packet().
check_hevc_startcode()
static int check_hevc_startcode (AVFormatContext * s, const AVStream * st, const AVPacket * pkt) static
Definition at line 1442 of file mpegtsenc.c.
Referenced by mpegts_write_packet_internal().
opus_get_packet_samples()
static int opus_get_packet_samples (AVFormatContext * s, AVPacket * pkt) static
Definition at line 1460 of file mpegtsenc.c.
Referenced by mpegts_write_packet_internal().
mpegts_write_packet_internal()
static int mpegts_write_packet_internal (AVFormatContext * s, AVPacket * pkt) static
Definition at line 1508 of file mpegtsenc.c.
Referenced by mpegts_write_packet().
mpegts_write_flush()
static void mpegts_write_flush (AVFormatContext * s) static
Definition at line 1750 of file mpegtsenc.c.
Referenced by mpegts_write_end(), and mpegts_write_packet().
mpegts_write_packet()
static int mpegts_write_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 1768 of file mpegtsenc.c.
mpegts_write_end()
static int mpegts_write_end (AVFormatContext * s) static
Definition at line 1778 of file mpegtsenc.c.
mpegts_deinit()
static void mpegts_deinit (AVFormatContext * s) static
Definition at line 1786 of file mpegtsenc.c.
mpegts_check_bitstream()
static int mpegts_check_bitstream (struct AVFormatContext * s, const AVPacket * pkt) static
Definition at line 1813 of file mpegtsenc.c.
Variable Documentation
options
const AVOption options[] static
Definition at line 1835 of file mpegtsenc.c.
mpegts_muxer_class
const AVClass mpegts_muxer_class static
Initial value:
= {
    .class_name = "MPEGTS muxer",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1930 of file mpegtsenc.c.
ff_mpegts_muxer
AVOutputFormat ff_mpegts_muxer
Initial value:
= {
    .name           = "mpegts",
    .long_name      = NULL_IF_CONFIG_SMALL("MPEG-TS (MPEG-2 Transport Stream)"),
    .mime_type      = "video/MP2T",
    .extensions     = "ts,m2t,m2ts,mts",
    .priv_data_size = sizeof(MpegTSWrite),
    .audio_codec    = AV_CODEC_ID_MP2,
    .video_codec    = AV_CODEC_ID_MPEG2VIDEO,
    .init           = mpegts_init,
    .write_packet   = mpegts_write_packet,
    .write_trailer  = mpegts_write_end,
    .deinit         = mpegts_deinit,
    .check_bitstream = mpegts_check_bitstream,
    .flags          = AVFMT_ALLOW_FLUSH | AVFMT_VARIABLE_FPS,
    .priv_class     = &mpegts_muxer_class,
}
Definition at line 1937 of file mpegtsenc.c.