FFmpeg: libavcodec/mpeg4videoenc.c File Reference
mpeg4videoenc.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/log.h"
#include "libavutil/opt.h"
#include "mpegutils.h"
#include "mpegvideo.h"
#include "h263.h"
#include "mpeg4video.h"
Macros
#define UNI_MPEG4_ENC_INDEX(last, run, level) ((last) * 128 * 64 + (run) * 128 + (level))
#define OFFSET(x) offsetof(MpegEncContext, x)
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Functions
static int get_block_rate (MpegEncContext *s, int16_t block[64], int block_last_index, uint8_t scantable[64])
Return the number of bits that encoding the 8x8 block in block would need.
static void restore_ac_coeffs (MpegEncContext *s, int16_t block[6][64], const int dir[6], uint8_t *st[6], const int zigzag_last_index[6])
Restore the ac coefficients in block that have been changed by decide_ac_pred().
static int decide_ac_pred (MpegEncContext *s, int16_t block[6][64], const int dir[6], uint8_t *st[6], int zigzag_last_index[6])
Return the optimal value (0 or 1) for the ac_pred element for the given MB in MPEG-4.
void ff_clean_mpeg4_qscales (MpegEncContext *s)
modify mb_type & qscale so that encoding is actually possible in MPEG-4
static void mpeg4_encode_dc (PutBitContext *s, int level, int n)
Encode the dc value.
static int mpeg4_get_dc_length (int level, int n)
static void mpeg4_encode_block (MpegEncContext *s, int16_t *block, int n, int intra_dc, uint8_t *scan_table, PutBitContext *dc_pb, PutBitContext *ac_pb)
Encode an 8x8 block.
static int mpeg4_get_block_length (MpegEncContext *s, int16_t *block, int n, int intra_dc, uint8_t *scan_table)
static void mpeg4_encode_blocks (MpegEncContext *s, int16_t block[6][64], int intra_dc[6], uint8_t **scan_table, PutBitContext *dc_pb, PutBitContext *ac_pb)
static int get_b_cbp (MpegEncContext *s, int16_t block[6][64], int motion_x, int motion_y, int mb_type)
void ff_mpeg4_encode_mb (MpegEncContext *s, int16_t block[6][64], int motion_x, int motion_y)
void ff_mpeg4_stuffing (PutBitContext *pbc)
add MPEG-4 stuffing bits (01...1)
void ff_set_mpeg4_time (MpegEncContext *s)
static void mpeg4_encode_gop_header (MpegEncContext *s)
static void mpeg4_encode_visual_object_header (MpegEncContext *s)
static void mpeg4_encode_vol_header (MpegEncContext *s, int vo_number, int vol_number)
int ff_mpeg4_encode_picture_header (MpegEncContext *s, int picture_number)
static av_cold void init_uni_dc_tab (void)
static av_cold void init_uni_mpeg4_rl_tab (RLTable *rl, uint32_t *bits_tab, uint8_t *len_tab)
static av_cold int encode_init (AVCodecContext *avctx)
void ff_mpeg4_init_partitions (MpegEncContext *s)
void ff_mpeg4_merge_partitions (MpegEncContext *s)
void ff_mpeg4_encode_video_packet_header (MpegEncContext *s)
Variables
static uint8_t uni_DCtab_lum_len [512]
static uint8_t uni_DCtab_chrom_len [512]
static uint16_t uni_DCtab_lum_bits [512]
static uint16_t uni_DCtab_chrom_bits [512]
static uint32_t uni_mpeg4_intra_rl_bits [64 *64 *2 *2]
static uint8_t uni_mpeg4_intra_rl_len [64 *64 *2 *2]
static uint32_t uni_mpeg4_inter_rl_bits [64 *64 *2 *2]
static uint8_t uni_mpeg4_inter_rl_len [64 *64 *2 *2]
static const int dquant_code [5] = { 1, 0, 9, 2, 3 }
static const AVOption options []
static const AVClass mpeg4enc_class
AVCodec ff_mpeg4_encoder
Macro Definition Documentation
UNI_MPEG4_ENC_INDEX
#define UNI_MPEG4_ENC_INDEX (last, run, level) ((last) * 128 * 64 + (run) * 128 + (level))
Definition at line 48 of file mpeg4videoenc.c.
Referenced by init_uni_mpeg4_rl_tab(), mpeg4_encode_block(), and mpeg4_get_block_length().
OFFSET
#define OFFSET (x) offsetof(MpegEncContext, x)
Definition at line 1401 of file mpeg4videoenc.c.
VE
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 1402 of file mpeg4videoenc.c.
Function Documentation
get_block_rate()
static int get_block_rate (MpegEncContext * s, int16_t block[64], int block_last_index, uint8_t scantable[64]) inline static
Return the number of bits that encoding the 8x8 block in block would need.
Parameters
[in] block_last_index last index in scantable order that refers to a non zero element in block.
Definition at line 64 of file mpeg4videoenc.c.
Referenced by decide_ac_pred().
restore_ac_coeffs()
static void restore_ac_coeffs (MpegEncContext * s, int16_t block[6][64], const int dir[6], uint8_t * st[6], const int zigzag_last_index[6]) inline static
Restore the ac coefficients in block that have been changed by decide_ac_pred().
This function also restores s->block_last_index.
Parameters
[in,out] block MB coefficients, these will be restored
[in] dir ac prediction direction for each 8x8 block
[out] st scantable for each 8x8 block
[in] zigzag_last_index index referring to the last non zero coefficient in zigzag order
Definition at line 99 of file mpeg4videoenc.c.
Referenced by decide_ac_pred(), and ff_mpeg4_encode_mb().
decide_ac_pred()
static int decide_ac_pred (MpegEncContext * s, int16_t block[6][64], const int dir[6], uint8_t * st[6], int zigzag_last_index[6]) inline static
Return the optimal value (0 or 1) for the ac_pred element for the given MB in MPEG-4.
This function will also update s->block_last_index and s->ac_val.
Parameters
[in,out] block MB coefficients, these will be updated if 1 is returned
[in] dir ac prediction direction for each 8x8 block
[out] st scantable for each 8x8 block
[out] zigzag_last_index index referring to the last non zero coefficient in zigzag order
Definition at line 130 of file mpeg4videoenc.c.
Referenced by ff_mpeg4_encode_mb().
ff_clean_mpeg4_qscales()
void ff_clean_mpeg4_qscales (MpegEncContext * s)
modify mb_type & qscale so that encoding is actually possible in MPEG-4
Definition at line 213 of file mpeg4videoenc.c.
Referenced by estimate_qp().
mpeg4_encode_dc()
static void mpeg4_encode_dc (PutBitContext * s, int level, int n) inline static
Encode the dc value.
Parameters
n block index (0-3 are luma, 4-5 are chroma)
Definition at line 257 of file mpeg4videoenc.c.
Referenced by mpeg4_encode_block().
mpeg4_get_dc_length()
static int mpeg4_get_dc_length (int level, int n) inline static
Definition at line 298 of file mpeg4videoenc.c.
Referenced by mpeg4_get_block_length().
mpeg4_encode_block()
static void mpeg4_encode_block (MpegEncContext * s, int16_t * block, int n, int intra_dc, uint8_t * scan_table, PutBitContext * dc_pb, PutBitContext * ac_pb) inline static
Encode an 8x8 block.
Parameters
n block index (0-3 are luma, 4-5 are chroma)
Definition at line 310 of file mpeg4videoenc.c.
Referenced by mpeg4_encode_blocks().
mpeg4_get_block_length()
static int mpeg4_get_block_length (MpegEncContext * s, int16_t * block, int n, int intra_dc, uint8_t * scan_table) static
Definition at line 371 of file mpeg4videoenc.c.
Referenced by mpeg4_encode_blocks().
mpeg4_encode_blocks()
static void mpeg4_encode_blocks (MpegEncContext * s, int16_t block[6][64], int intra_dc[6], uint8_t ** scan_table, PutBitContext * dc_pb, PutBitContext * ac_pb) inline static
Definition at line 425 of file mpeg4videoenc.c.
Referenced by ff_mpeg4_encode_mb().
get_b_cbp()
static int get_b_cbp (MpegEncContext * s, int16_t block[6][64], int motion_x, int motion_y, int mb_type) inline static
Definition at line 459 of file mpeg4videoenc.c.
Referenced by ff_mpeg4_encode_mb().
ff_mpeg4_encode_mb()
void ff_mpeg4_encode_mb (MpegEncContext * s, int16_t block[6][64], int motion_x, int motion_y)
Definition at line 503 of file mpeg4videoenc.c.
Referenced by encode_mb_internal().
ff_mpeg4_stuffing()
void ff_mpeg4_stuffing (PutBitContext * pbc)
add MPEG-4 stuffing bits (01...1)
Definition at line 891 of file mpeg4videoenc.c.
Referenced by mpeg4_encode_gop_header(), mpeg4_encode_visual_object_header(), mpeg4_encode_vol_header(), and write_slice_end().
ff_set_mpeg4_time()
void ff_set_mpeg4_time (MpegEncContext * s)
Definition at line 901 of file mpeg4videoenc.c.
Referenced by encode_picture().
mpeg4_encode_gop_header()
static void mpeg4_encode_gop_header (MpegEncContext * s) static
Definition at line 911 of file mpeg4videoenc.c.
Referenced by ff_mpeg4_encode_picture_header().
mpeg4_encode_visual_object_header()
static void mpeg4_encode_visual_object_header (MpegEncContext * s) static
Definition at line 941 of file mpeg4videoenc.c.
Referenced by encode_init(), and ff_mpeg4_encode_picture_header().
mpeg4_encode_vol_header()
static void mpeg4_encode_vol_header (MpegEncContext * s, int vo_number, int vol_number) static
Definition at line 985 of file mpeg4videoenc.c.
Referenced by encode_init(), and ff_mpeg4_encode_picture_header().
ff_mpeg4_encode_picture_header()
int ff_mpeg4_encode_picture_header (MpegEncContext * s, int picture_number)
Definition at line 1089 of file mpeg4videoenc.c.
Referenced by encode_picture().
init_uni_dc_tab()
static av_cold void init_uni_dc_tab (void) static
Definition at line 1149 of file mpeg4videoenc.c.
Referenced by encode_init().
init_uni_mpeg4_rl_tab()
static av_cold void init_uni_mpeg4_rl_tab (RLTable * rl, uint32_t * bits_tab, uint8_t * len_tab) static
Definition at line 1204 of file mpeg4videoenc.c.
Referenced by encode_init().
encode_init()
static av_cold int encode_init (AVCodecContext * avctx) static
Definition at line 1299 of file mpeg4videoenc.c.
ff_mpeg4_init_partitions()
void ff_mpeg4_init_partitions (MpegEncContext * s)
Definition at line 1350 of file mpeg4videoenc.c.
Referenced by encode_thread().
ff_mpeg4_merge_partitions()
void ff_mpeg4_merge_partitions (MpegEncContext * s)
Definition at line 1363 of file mpeg4videoenc.c.
Referenced by write_slice_end().
ff_mpeg4_encode_video_packet_header()
void ff_mpeg4_encode_video_packet_header (MpegEncContext * s)
Definition at line 1389 of file mpeg4videoenc.c.
Referenced by encode_thread().
Variable Documentation
uni_DCtab_lum_len
uint8_t uni_DCtab_lum_len[512] static
Definition at line 34 of file mpeg4videoenc.c.
Referenced by encode_init(), init_uni_dc_tab(), mpeg4_encode_dc(), and mpeg4_get_dc_length().
uni_DCtab_chrom_len
uint8_t uni_DCtab_chrom_len[512] static
Definition at line 35 of file mpeg4videoenc.c.
Referenced by init_uni_dc_tab(), mpeg4_encode_dc(), and mpeg4_get_dc_length().
uni_DCtab_lum_bits
uint16_t uni_DCtab_lum_bits[512] static
Definition at line 36 of file mpeg4videoenc.c.
Referenced by init_uni_dc_tab(), and mpeg4_encode_dc().
uni_DCtab_chrom_bits
uint16_t uni_DCtab_chrom_bits[512] static
Definition at line 37 of file mpeg4videoenc.c.
Referenced by init_uni_dc_tab(), and mpeg4_encode_dc().
uni_mpeg4_intra_rl_bits
uint32_t uni_mpeg4_intra_rl_bits[64 *64 *2 *2] static
Definition at line 41 of file mpeg4videoenc.c.
Referenced by encode_init(), and mpeg4_encode_block().
uni_mpeg4_intra_rl_len
uint8_t uni_mpeg4_intra_rl_len[64 *64 *2 *2] static
Definition at line 42 of file mpeg4videoenc.c.
Referenced by encode_init(), mpeg4_encode_block(), and mpeg4_get_block_length().
uni_mpeg4_inter_rl_bits
uint32_t uni_mpeg4_inter_rl_bits[64 *64 *2 *2] static
Definition at line 43 of file mpeg4videoenc.c.
Referenced by encode_init(), and mpeg4_encode_block().
uni_mpeg4_inter_rl_len
uint8_t uni_mpeg4_inter_rl_len[64 *64 *2 *2] static
Definition at line 44 of file mpeg4videoenc.c.
Referenced by encode_init(), mpeg4_encode_block(), and mpeg4_get_block_length().
dquant_code
const int dquant_code[5] = { 1, 0, 9, 2, 3 } static
Definition at line 501 of file mpeg4videoenc.c.
Referenced by ff_mpeg4_encode_mb().
options
const AVOption options[] static
Initial value:
= {
    { "data_partitioning", "Use data partitioning.",      OFFSET(data_partitioning), AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, VE },
    { "alternate_scan",    "Enable alternate scantable.", OFFSET(alternate_scan),    AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, VE },
    FF_MPV_COMMON_OPTS
    { NULL },
}
Definition at line 1403 of file mpeg4videoenc.c.
mpeg4enc_class
const AVClass mpeg4enc_class static
Initial value:
= {
    .class_name = "MPEG4 encoder",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1410 of file mpeg4videoenc.c.
ff_mpeg4_encoder
AVCodec ff_mpeg4_encoder
Initial value:
= {
    .name           = "mpeg4",
    .long_name      = NULL_IF_CONFIG_SMALL("MPEG-4 part 2"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_MPEG4,
    .priv_data_size = sizeof(MpegEncContext),
    .init           = encode_init,
    .encode2        = ff_mpv_encode_picture,
    .close          = ff_mpv_encode_end,
    .pix_fmts       = (const enum AVPixelFormat[]) { AV_PIX_FMT_YUV420P, AV_PIX_FMT_NONE },
    .capabilities   = AV_CODEC_CAP_DELAY | AV_CODEC_CAP_SLICE_THREADS,
    .priv_class     = &mpeg4enc_class,
}
Definition at line 1417 of file mpeg4videoenc.c.