FFmpeg: libavcodec/arm/mpegvideoencdsp_init_arm.c File Reference
mpegvideoencdsp_init_arm.c File Reference
#include <stdint.h>
#include "libavutil/cpu.h"
#include "libavutil/arm/cpu.h"
#include "libavcodec/avcodec.h"
#include "libavcodec/mpegvideoencdsp.h"
Functions
int ff_pix_norm1_armv6 (uint8_t *pix, int line_size)
int ff_pix_sum_armv6 (uint8_t *pix, int line_size)
av_cold void ff_mpegvideoencdsp_init_arm (MpegvideoEncDSPContext *c, AVCodecContext *avctx)
Function Documentation
ff_pix_norm1_armv6()
int ff_pix_norm1_armv6 (uint8_t * pix, int line_size)
Referenced by ff_mpegvideoencdsp_init_arm().
ff_pix_sum_armv6()
int ff_pix_sum_armv6 (uint8_t * pix, int line_size)
Referenced by ff_mpegvideoencdsp_init_arm().
ff_mpegvideoencdsp_init_arm()
av_cold void ff_mpegvideoencdsp_init_arm (MpegvideoEncDSPContext * c, AVCodecContext * avctx)
Definition at line 29 of file mpegvideoencdsp_init_arm.c.
Referenced by ff_mpegvideoencdsp_init().