FFmpeg: libavcodec/mpegpicture.c File Reference
mpegpicture.c File Reference
#include <stdint.h>
#include "libavutil/avassert.h"
#include "libavutil/common.h"
#include "avcodec.h"
#include "motion_est.h"
#include "mpegpicture.h"
#include "mpegutils.h"
Macros
#define MAKE_WRITABLE(table)
#define UPDATE_TABLE(table)
Functions
static int make_tables_writable (Picture *pic)
int ff_mpeg_framesize_alloc (AVCodecContext *avctx, MotionEstContext *me, ScratchpadContext *sc, int linesize)
static int alloc_frame_buffer (AVCodecContext *avctx, Picture *pic, MotionEstContext *me, ScratchpadContext *sc, int chroma_x_shift, int chroma_y_shift, int linesize, int uvlinesize)
Allocate a frame buffer.
static int alloc_picture_tables (AVCodecContext *avctx, Picture *pic, int encoding, int out_format, int mb_stride, int mb_width, int mb_height, int b8_stride)
int ff_alloc_picture (AVCodecContext *avctx, Picture *pic, MotionEstContext *me, ScratchpadContext *sc, int shared, int encoding, int chroma_x_shift, int chroma_y_shift, int out_format, int mb_stride, int mb_width, int mb_height, int b8_stride, ptrdiff_t *linesize, ptrdiff_t *uvlinesize)
Allocate a Picture.
void ff_mpeg_unref_picture (AVCodecContext *avctx, Picture *pic)
Deallocate a picture.
int ff_update_picture_tables (Picture *dst, Picture *src)
int ff_mpeg_ref_picture (AVCodecContext *avctx, Picture *dst, Picture *src)
static int pic_is_unused (Picture *pic)
static int find_unused_picture (AVCodecContext *avctx, Picture *picture, int shared)
int ff_find_unused_picture (AVCodecContext *avctx, Picture *picture, int shared)
void ff_free_picture_tables (Picture *pic)
Macro Definition Documentation
MAKE_WRITABLE
#define MAKE_WRITABLE (table)
Value:
do {\
    if (pic->table &&\
       (ret = av_buffer_make_writable(&pic->table)) < 0)\
    return ret;\
} while (0)
Referenced by make_tables_writable().
UPDATE_TABLE
#define UPDATE_TABLE (table)
Value:
do {                                                                          \
    if (src->table &&                                                         \
        (!dst->table || dst->table->buffer != src->table->buffer)) {          \
        av_buffer_unref(&dst->table);                                         \
        dst->table = av_buffer_ref(src->table);                               \
        if (!dst->table) {                                                    \
            ff_free_picture_tables(dst);                                      \
            return AVERROR(ENOMEM);                                           \
        }                                                                     \
    }                                                                         \
} while (0)
Referenced by ff_update_picture_tables().
Function Documentation
make_tables_writable()
static int make_tables_writable (Picture * pic) static
Definition at line 31 of file mpegpicture.c.
Referenced by ff_alloc_picture().
ff_mpeg_framesize_alloc()
int ff_mpeg_framesize_alloc (AVCodecContext * avctx, MotionEstContext * me, ScratchpadContext * sc, int linesize)
Definition at line 56 of file mpegpicture.c.
Referenced by alloc_frame_buffer(), ff_mpeg_update_thread_context(), and ff_update_duplicate_context().
alloc_frame_buffer()
static int alloc_frame_buffer (AVCodecContext * avctx, Picture * pic, MotionEstContext * me, ScratchpadContext * sc, int chroma_x_shift, int chroma_y_shift, int linesize, int uvlinesize) static
Allocate a frame buffer.
Definition at line 98 of file mpegpicture.c.
Referenced by ff_alloc_picture().
alloc_picture_tables()
static int alloc_picture_tables (AVCodecContext * avctx, Picture * pic, int encoding, int out_format, int mb_stride, int mb_width, int mb_height, int b8_stride) static
Definition at line 181 of file mpegpicture.c.
Referenced by ff_alloc_picture().
ff_alloc_picture()
int ff_alloc_picture (AVCodecContext * avctx, Picture * pic, MotionEstContext * me, ScratchpadContext * sc, int shared, int encoding, int chroma_x_shift, int chroma_y_shift, int out_format, int mb_stride, int mb_width, int mb_height, int b8_stride, ptrdiff_t * linesize, ptrdiff_t * uvlinesize)
Allocate a Picture.
The pixels are allocated/set by calling get_buffer() if shared = 0
Definition at line 228 of file mpegpicture.c.
Referenced by alloc_picture().
ff_mpeg_unref_picture()
void ff_mpeg_unref_picture (AVCodecContext * avctx, Picture * pic)
Deallocate a picture.
Definition at line 291 of file mpegpicture.c.
Referenced by alloc_frame_buffer(), ff_alloc_picture(), ff_find_unused_picture(), ff_mpeg_flush(), ff_mpeg_ref_picture(), ff_mpeg_update_thread_context(), ff_mpv_common_end(), ff_mpv_encode_end(), ff_mpv_encode_picture(), ff_mpv_frame_start(), frame_start(), and select_input_picture().
ff_update_picture_tables()
int ff_update_picture_tables (Picture * dst, Picture * src)
Definition at line 313 of file mpegpicture.c.
Referenced by ff_mpeg_ref_picture().
ff_mpeg_ref_picture()
int ff_mpeg_ref_picture (AVCodecContext * avctx, Picture * dst, Picture * src)
Definition at line 358 of file mpegpicture.c.
Referenced by ff_mpeg_update_thread_context(), ff_mpv_frame_start(), frame_start(), and select_input_picture().
pic_is_unused()
static int pic_is_unused (Picture * pic) inline static
Definition at line 399 of file mpegpicture.c.
Referenced by find_unused_picture().
find_unused_picture()
static int find_unused_picture (AVCodecContext * avctx, Picture * picture, int shared) static
Definition at line 408 of file mpegpicture.c.
Referenced by ff_find_unused_picture().
ff_find_unused_picture()
int ff_find_unused_picture (AVCodecContext * avctx, Picture * picture, int shared)
Definition at line 441 of file mpegpicture.c.
Referenced by ff_h263_decode_frame(), ff_mpv_frame_start(), load_input_picture(), and select_input_picture().
ff_free_picture_tables()
void ff_free_picture_tables (Picture * pic)
Definition at line 455 of file mpegpicture.c.
Referenced by ff_alloc_picture(), ff_find_unused_picture(), ff_mpeg_unref_picture(), ff_mpv_common_end(), and ff_mpv_encode_end().