FFmpeg: libavcodec/mpegaudiodecheader.h File Reference
mpegaudiodecheader.h File Reference
MPEG Audio header decoder.
#include "avcodec.h"
Data Structures
struct MPADecodeHeader
Macros
#define MP3_MASK 0xFFFE0CCF
#define MPA_DECODE_HEADER
Functions
int avpriv_mpegaudio_decode_header (MPADecodeHeader *s, uint32_t header)
int ff_mpa_decode_header (uint32_t head, int *sample_rate, int *channels, int *frame_size, int *bitrate, enum AVCodecID *codec_id)
int avpriv_mpa_decode_header (AVCodecContext *avctx, uint32_t head, int *sample_rate, int *channels, int *frame_size, int *bitrate)
int avpriv_mpa_decode_header2 (uint32_t head, int *sample_rate, int *channels, int *frame_size, int *bitrate, enum AVCodecID *codec_id)
static int ff_mpa_check_header (uint32_t header)
Detailed Description
MPEG Audio header decoder.
Definition in file mpegaudiodecheader.h.
Macro Definition Documentation
MP3_MASK
#define MP3_MASK 0xFFFE0CCF
Definition at line 32 of file mpegaudiodecheader.h.
Referenced by mp3_header_decompress().
MPA_DECODE_HEADER
#define MPA_DECODE_HEADER
Value:
int frame_size; \
    int error_protection; \
    int layer; \
    int sample_rate; \
    int sample_rate_index; /* between 0 and 8 */ \
    int bit_rate; \
    int nb_channels; \
    int mode; \
    int mode_ext; \
    int lsf;
Definition at line 34 of file mpegaudiodecheader.h.
Function Documentation
avpriv_mpegaudio_decode_header()
int avpriv_mpegaudio_decode_header (MPADecodeHeader * s, uint32_t header)
Definition at line 36 of file mpegaudiodecheader.c.
Referenced by check(), decode_frame(), ff_mpa_decode_header(), flush(), libshine_encode_frame(), mp3_parse_vbr_tags(), mp3_read_probe(), mp3_write_audio_packet(), mp3_write_xing(), and mp3lame_encode_frame().
ff_mpa_decode_header()
int ff_mpa_decode_header (uint32_t head, int * sample_rate, int * channels, int * frame_size, int * bitrate, enum AVCodecID * codec_id)
Definition at line 122 of file mpegaudiodecheader.c.
Referenced by avpriv_mpa_decode_header(), avpriv_mpa_decode_header2(), ffat_create_decoder(), and mpegaudio_parse().
avpriv_mpa_decode_header()
int avpriv_mpa_decode_header (AVCodecContext * avctx, uint32_t head, int * sample_rate, int * channels, int * frame_size, int * bitrate)
Definition at line 162 of file mpegaudiodecheader.c.
avpriv_mpa_decode_header2()
int avpriv_mpa_decode_header2 (uint32_t head, int * sample_rate, int * channels, int * frame_size, int * bitrate, enum AVCodecID * codec_id)
Definition at line 157 of file mpegaudiodecheader.c.
ff_mpa_check_header()
static int ff_mpa_check_header (uint32_t header) inline static
Definition at line 66 of file mpegaudiodecheader.h.
Referenced by avpriv_mpegaudio_decode_header(), check(), mov_read_packet(), and mp3_header_decompress().