FFmpeg: libavformat/mpeg.c File Reference
mpeg.c File Reference
#include "avformat.h"
#include "internal.h"
#include "mpeg.h"
#include "libavutil/avassert.h"
Data Structures
struct MpegDemuxContext
Macros
#define MAX_SYNC_SIZE 100000
Functions
static int check_pes (const uint8_t *p, const uint8_t *end)
static int check_pack_header (const uint8_t *buf)
static int mpegps_probe (AVProbeData *p)
static int mpegps_read_header (AVFormatContext *s)
static int64_t get_pts (AVIOContext *pb, int c)
static int find_next_start_code (AVIOContext *pb, int *size_ptr, int32_t *header_state)
static long mpegps_psm_parse (MpegDemuxContext *m, AVIOContext *pb)
Extract stream types from a program stream map According to ISO/IEC 13818-1 ('MPEG-2 Systems') table 2-35.
static int mpegps_read_pes_header (AVFormatContext *s, int64_t *ppos, int *pstart_code, int64_t *ppts, int64_t *pdts)
static int mpegps_read_packet (AVFormatContext *s, AVPacket *pkt)
static int64_t mpegps_read_dts (AVFormatContext *s, int stream_index, int64_t *ppos, int64_t pos_limit)
Variables
AVInputFormat ff_mpegps_demuxer
Macro Definition Documentation
MAX_SYNC_SIZE
#define MAX_SYNC_SIZE 100000
Definition at line 37 of file mpeg.c.
Referenced by mpegps_read_pes_header().
Function Documentation
check_pes()
static int check_pes (const uint8_t * p, const uint8_t * end) static
Definition at line 39 of file mpeg.c.
Referenced by mpegps_probe().
check_pack_header()
static int check_pack_header (const uint8_t * buf) static
Definition at line 61 of file mpeg.c.
Referenced by mpegps_probe().
mpegps_probe()
static int mpegps_probe (AVProbeData * p) static
Definition at line 66 of file mpeg.c.
mpegps_read_header()
static int mpegps_read_header (AVFormatContext * s) static
Definition at line 138 of file mpeg.c.
get_pts()
static int64_t get_pts (AVIOContext * pb, int c) static
Definition at line 159 of file mpeg.c.
Referenced by mpegps_read_pes_header().
find_next_start_code()
static int find_next_start_code (AVIOContext * pb, int * size_ptr, int32_t * header_state) static
Definition at line 169 of file mpeg.c.
Referenced by mpegps_read_pes_header().
mpegps_psm_parse()
static long mpegps_psm_parse (MpegDemuxContext * m, AVIOContext * pb) static
Extract stream types from a program stream map According to ISO/IEC 13818-1 ('MPEG-2 Systems') table 2-35.
Returns
number of bytes occupied by PSM in the bitstream
Definition at line 203 of file mpeg.c.
Referenced by mpegps_read_pes_header().
mpegps_read_pes_header()
static int mpegps_read_pes_header (AVFormatContext * s, int64_t * ppos, int * pstart_code, int64_t * ppts, int64_t * pdts) static
Definition at line 237 of file mpeg.c.
Referenced by mpegps_read_dts(), and mpegps_read_packet().
mpegps_read_packet()
static int mpegps_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 468 of file mpeg.c.
mpegps_read_dts()
static int64_t mpegps_read_dts (AVFormatContext * s, int stream_index, int64_t * ppos, int64_t pos_limit) static
Definition at line 637 of file mpeg.c.
Variable Documentation
ff_mpegps_demuxer
AVInputFormat ff_mpegps_demuxer
Initial value:
= {
    .name           = "mpeg",
    .long_name      = NULL_IF_CONFIG_SMALL("MPEG-PS (MPEG-2 Program Stream)"),
    .priv_data_size = sizeof(MpegDemuxContext),
    .read_probe     = mpegps_probe,
    .read_header    = mpegps_read_header,
    .read_packet    = mpegps_read_packet,
    .read_timestamp = mpegps_read_dts,
    .flags          = AVFMT_SHOW_IDS | AVFMT_TS_DISCONT,
}
Definition at line 667 of file mpeg.c.