FFmpeg: libavcodec/mpegvideo.h File Reference
mpegvideo.h File Reference
mpegvideo header.
#include <float.h>
#include "avcodec.h"
#include "blockdsp.h"
#include "error_resilience.h"
#include "fdctdsp.h"
#include "get_bits.h"
#include "h264chroma.h"
#include "h263dsp.h"
#include "hpeldsp.h"
#include "idctdsp.h"
#include "internal.h"
#include "me_cmp.h"
#include "motion_est.h"
#include "mpegpicture.h"
#include "mpegvideodsp.h"
#include "mpegvideoencdsp.h"
#include "pixblockdsp.h"
#include "put_bits.h"
#include "ratecontrol.h"
#include "parser.h"
#include "mpegutils.h"
#include "mpeg12data.h"
#include "qpeldsp.h"
#include "thread.h"
#include "videodsp.h"
#include "libavutil/opt.h"
#include "libavutil/timecode.h"
Data Structures
struct MpegEncContext
MpegEncContext.
Macros
#define MAX_THREADS 32
#define MAX_B_FRAMES 16
#define SEQ_END_CODE 0x000001b7
#define SEQ_START_CODE 0x000001b3
#define GOP_START_CODE 0x000001b8
#define PICTURE_START_CODE 0x00000100
#define SLICE_MIN_START_CODE 0x00000101
#define SLICE_MAX_START_CODE 0x000001af
#define EXT_START_CODE 0x000001b5
#define USER_START_CODE 0x000001b2
#define MV_DIR_FORWARD 1
#define MV_DIR_BACKWARD 2
#define MV_DIRECT 4
bidirectional mode where the difference equals the MV of the last P/S/I-Frame (MPEG-4)
#define MV_TYPE_16X16 0
1 vector for the whole mb
#define MV_TYPE_8X8 1
4 vectors (H.263, MPEG-4 4MV)
#define MV_TYPE_16X8 2
2 vectors, one per 16x8 block
#define MV_TYPE_FIELD 3
2 vectors, one per field
#define MV_TYPE_DMV 4
2 vectors, special mpeg2 Dual Prime Vectors
#define UNI_AC_ENC_INDEX(run, level) ((run)*128 + (level))
#define CHROMA_420 1
#define CHROMA_422 2
#define CHROMA_444 3
#define SLICE_OK 0
#define SLICE_ERROR -1
#define SLICE_END -2
end marker found
#define SLICE_NOEND -3
no end marker or error found but mb count exceeded
#define FF_MPV_FLAG_SKIP_RD 0x0001
#define FF_MPV_FLAG_STRICT_GOP 0x0002
#define FF_MPV_FLAG_QP_RD 0x0004
#define FF_MPV_FLAG_CBP_RD 0x0008
#define FF_MPV_FLAG_NAQ 0x0010
#define FF_MPV_FLAG_MV0 0x0020
#define FF_MPV_OPT_CMP_FUNC
#define FF_MPV_OFFSET(x) offsetof(MpegEncContext, x)
#define FF_MPV_OPT_FLAGS (AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM)
#define FF_MPV_COMMON_OPTS
Enumerations
enum rc_strategy { MPV_RC_STRATEGY_FFMPEG, MPV_RC_STRATEGY_XVID, NB_MPV_RC_STRATEGY }
Functions
void ff_mpv_common_defaults (MpegEncContext *s)
Set the given MpegEncContext to common defaults (same for encoding and decoding).
void ff_dct_encode_init_x86 (MpegEncContext *s)
int ff_mpv_common_init (MpegEncContext *s)
init common structure for both encoder and decoder.
void ff_mpv_common_init_arm (MpegEncContext *s)
void ff_mpv_common_init_axp (MpegEncContext *s)
void ff_mpv_common_init_neon (MpegEncContext *s)
void ff_mpv_common_init_ppc (MpegEncContext *s)
void ff_mpv_common_init_x86 (MpegEncContext *s)
void ff_mpv_common_init_mips (MpegEncContext *s)
int ff_mpv_common_frame_size_change (MpegEncContext *s)
void ff_mpv_common_end (MpegEncContext *s)
void ff_mpv_decode_defaults (MpegEncContext *s)
Set the given MpegEncContext to defaults for decoding.
void ff_mpv_decode_init (MpegEncContext *s, AVCodecContext *avctx)
void ff_mpv_decode_mb (MpegEncContext *s, int16_t block[12][64])
void ff_mpv_report_decode_progress (MpegEncContext *s)
int ff_mpv_frame_start (MpegEncContext *s, AVCodecContext *avctx)
generic function called after decoding the header and before a frame is decoded.
void ff_mpv_frame_end (MpegEncContext *s)
int ff_mpv_encode_init (AVCodecContext *avctx)
void ff_mpv_encode_init_x86 (MpegEncContext *s)
int ff_mpv_encode_end (AVCodecContext *avctx)
int ff_mpv_encode_picture (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *frame, int *got_packet)
int ff_mpv_reallocate_putbitbuffer (MpegEncContext *s, size_t threshold, size_t size_increase)
void ff_clean_intra_table_entries (MpegEncContext *s)
Clean dc, ac, coded_block for the current non-intra MB.
void ff_mpeg_draw_horiz_band (MpegEncContext *s, int y, int h)
void ff_mpeg_flush (AVCodecContext *avctx)
void ff_print_debug_info (MpegEncContext *s, Picture *p, AVFrame *pict)
void ff_print_debug_info2 (AVCodecContext *avctx, AVFrame *pict, uint8_t *mbskip_table, uint32_t *mbtype_table, int8_t *qscale_table, int16_t(*motion_val[2])[2], int *low_delay, int mb_width, int mb_height, int mb_stride, int quarter_sample)
Print debugging info for the given picture.
int ff_mpv_export_qp_table (MpegEncContext *s, AVFrame *f, Picture *p, int qp_type)
void ff_write_quant_matrix (PutBitContext *pb, uint16_t *matrix)
int ff_update_duplicate_context (MpegEncContext *dst, MpegEncContext *src)
int ff_mpeg_update_thread_context (AVCodecContext *dst, const AVCodecContext *src)
void ff_set_qscale (MpegEncContext *s, int qscale)
set qscale and update qscale dependent variables.
void ff_mpv_idct_init (MpegEncContext *s)
int ff_dct_encode_init (MpegEncContext *s)
void ff_convert_matrix (MpegEncContext *s, int(*qmat)[64], uint16_t(*qmat16)[2][64], const uint16_t *quant_matrix, int bias, int qmin, int qmax, int intra)
int ff_dct_quantize_c (MpegEncContext *s, int16_t *block, int n, int qscale, int *overflow)
void ff_block_permute (int16_t *block, uint8_t *permutation, const uint8_t *scantable, int last)
Permute an 8x8 block according to permutation.
void ff_init_block_index (MpegEncContext *s)
void ff_mpv_motion (MpegEncContext *s, uint8_t *dest_y, uint8_t *dest_cb, uint8_t *dest_cr, int dir, uint8_t **ref_picture, op_pixels_func(*pix_op)[4], qpel_mc_func(*qpix_op)[16])
static void ff_update_block_index (MpegEncContext *s)
static int get_bits_diff (MpegEncContext *s)
Variables
const AVOption ff_mpv_generic_options []
Detailed Description
mpegvideo header.
Definition in file mpegvideo.h.
Macro Definition Documentation
MAX_THREADS
#define MAX_THREADS 32
Definition at line 61 of file mpegvideo.h.
MAX_B_FRAMES
#define MAX_B_FRAMES 16
Definition at line 63 of file mpegvideo.h.
Referenced by ff_mpv_encode_init().
SEQ_END_CODE
#define SEQ_END_CODE 0x000001b7
Definition at line 66 of file mpegvideo.h.
Referenced by ff_mpeg1_find_frame_end(), and mpeg_decode_frame().
SEQ_START_CODE
#define SEQ_START_CODE 0x000001b3
Definition at line 67 of file mpegvideo.h.
Referenced by decode_chunks(), ff_mpeg1_find_frame_end(), mpeg1_encode_sequence_header(), and mpegvideo_extract_headers().
GOP_START_CODE
#define GOP_START_CODE 0x000001b8
Definition at line 68 of file mpegvideo.h.
Referenced by decode_chunks(), and mpeg1_encode_sequence_header().
PICTURE_START_CODE
#define PICTURE_START_CODE 0x00000100
Definition at line 69 of file mpegvideo.h.
Referenced by decode_chunks(), ff_mpeg1_encode_picture_header(), ff_mpeg1_find_frame_end(), and mpegvideo_extract_headers().
SLICE_MIN_START_CODE
#define SLICE_MIN_START_CODE 0x00000101
Definition at line 70 of file mpegvideo.h.
Referenced by decode_chunks(), ff_mpeg1_encode_slice_header(), ff_mpeg1_find_frame_end(), mpegvideo_extract_headers(), and slice_decode_thread().
SLICE_MAX_START_CODE
#define SLICE_MAX_START_CODE 0x000001af
Definition at line 71 of file mpegvideo.h.
EXT_START_CODE
#define EXT_START_CODE 0x000001b5
Definition at line 72 of file mpegvideo.h.
USER_START_CODE
#define USER_START_CODE 0x000001b2
Definition at line 73 of file mpegvideo.h.
MV_DIR_FORWARD
#define MV_DIR_FORWARD 1
Definition at line 262 of file mpegvideo.h.
Referenced by decode_slice(), encode_mb_internal(), encode_thread(), ff_er_frame_end(), ff_h263_decode_mb(), ff_mpeg4_encode_mb(), ff_wmv2_decode_mb(), ff_xvmc_decode_mb(), guess_mv(), h261_decode_mb(), h261_decode_mb_skipped(), mpeg1_encode_mb_internal(), mpeg4_decode_mb(), mpeg4_decode_partitioned_mb(), mpeg_decode_mb(), mpeg_decode_slice(), mpv_decode_mb_internal(), msmpeg4v12_decode_mb(), msmpeg4v34_decode_mb(), and rv10_decode_packet().
MV_DIR_BACKWARD
#define MV_DIR_BACKWARD 2
Definition at line 263 of file mpegvideo.h.
Referenced by encode_mb_internal(), encode_thread(), ff_er_frame_end(), ff_h263_decode_mb(), ff_mpeg4_encode_mb(), ff_xvmc_decode_mb(), guess_mv(), mpeg1_encode_mb_internal(), mpeg4_decode_mb(), and mpv_decode_mb_internal().
MV_DIRECT
#define MV_DIRECT 4
bidirectional mode where the difference equals the MV of the last P/S/I-Frame (MPEG-4)
Definition at line 264 of file mpegvideo.h.
Referenced by encode_mb_internal(), encode_thread(), ff_h263_decode_mb(), ff_mpeg4_encode_mb(), and mpeg4_decode_mb().
MV_TYPE_16X16
#define MV_TYPE_16X16 0
1 vector for the whole mb
Definition at line 266 of file mpegvideo.h.
Referenced by decode_slice(), direct_search(), encode_thread(), ff_er_frame_end(), ff_h263_decode_mb(), ff_h263_encode_mb(), ff_h263_update_motion_val(), ff_mpeg4_encode_mb(), ff_mpeg4_set_direct_mv(), ff_wmv2_decode_mb(), ff_xvmc_decode_mb(), get_p_cbp(), guess_mv(), h261_decode_mb(), h261_decode_mb_skipped(), lowest_referenced_row(), mpeg1_encode_mb_internal(), mpeg4_decode_mb(), mpeg4_decode_partitioned_mb(), mpeg_decode_mb(), mpeg_decode_slice(), mpv_motion_internal(), MPV_motion_lowres(), msmpeg4v12_decode_mb(), msmpeg4v34_decode_mb(), and rv10_decode_packet().
MV_TYPE_8X8
#define MV_TYPE_8X8 1
4 vectors (H.263, MPEG-4 4MV)
Definition at line 267 of file mpegvideo.h.
Referenced by cmp_direct_inline(), direct_search(), encode_mb_internal(), encode_thread(), ff_er_frame_end(), ff_h263_decode_mb(), ff_h263_update_motion_val(), ff_mpeg4_encode_mb(), ff_mpeg4_set_direct_mv(), lowest_referenced_row(), mpeg4_decode_mb(), mpeg4_decode_partitioned_mb(), mpv_motion_internal(), and MPV_motion_lowres().
MV_TYPE_16X8
#define MV_TYPE_16X8 2
2 vectors, one per 16x8 block
Definition at line 268 of file mpegvideo.h.
Referenced by ff_xvmc_decode_mb(), lowest_referenced_row(), mpeg_decode_mb(), mpv_motion_internal(), and MPV_motion_lowres().
MV_TYPE_FIELD
#define MV_TYPE_FIELD 3
2 vectors, one per field
Definition at line 269 of file mpegvideo.h.
Referenced by encode_thread(), ff_mpeg4_encode_mb(), ff_mpeg4_set_direct_mv(), ff_xvmc_decode_mb(), mpeg1_encode_mb_internal(), mpeg4_decode_mb(), mpeg_decode_mb(), mpeg_decode_slice(), mpv_motion_internal(), and MPV_motion_lowres().
MV_TYPE_DMV
#define MV_TYPE_DMV 4
2 vectors, special mpeg2 Dual Prime Vectors
Definition at line 270 of file mpegvideo.h.
Referenced by ff_xvmc_decode_mb(), mpeg_decode_mb(), mpv_motion_internal(), and MPV_motion_lowres().
UNI_AC_ENC_INDEX
#define UNI_AC_ENC_INDEX (run, level) ((run)*128 + (level))
Definition at line 318 of file mpegvideo.h.
Referenced by bit8x8_c(), dct_quantize_refine(), dct_quantize_trellis_c(), get_block_rate(), init_uni_ac_vlc(), and rd8x8_c().
CHROMA_420
#define CHROMA_420 1
Definition at line 472 of file mpegvideo.h.
Referenced by decode_vol_header(), encode_init(), encode_mb(), ff_mjpeg_encode_mb(), ff_mpeg1_encode_mb(), ff_mpeg1_encode_picture_header(), ff_mpv_encode_init(), and vaapi_mpeg4_start_frame().
CHROMA_422
#define CHROMA_422 2
Definition at line 473 of file mpegvideo.h.
Referenced by encode_mb(), encode_mb_internal(), and ff_mpv_encode_init().
CHROMA_444
#define CHROMA_444 3
Definition at line 474 of file mpegvideo.h.
Referenced by encode_mb_internal(), ff_mjpeg_encode_mb(), and ff_mpv_encode_init().
SLICE_OK
#define SLICE_OK 0
Definition at line 500 of file mpegvideo.h.
Referenced by ff_h263_decode_mb(), h261_decode_mb(), mpeg4_decode_mb(), mpeg4_decode_partitioned_mb(), and rv10_decode_packet().
SLICE_ERROR
#define SLICE_ERROR -1
Definition at line 501 of file mpegvideo.h.
Referenced by h261_decode_mb(), and rv10_decode_packet().
SLICE_END
#define SLICE_END -2
end marker found
Definition at line 502 of file mpegvideo.h.
Referenced by decode_slice(), ff_h263_decode_mb(), h261_decode_gob(), h261_decode_mb(), mpeg4_decode_mb(), mpeg4_decode_partitioned_mb(), and rv10_decode_packet().
SLICE_NOEND
#define SLICE_NOEND -3
no end marker or error found but mb count exceeded
Definition at line 503 of file mpegvideo.h.
Referenced by decode_slice(), and mpeg4_decode_partitioned_mb().
FF_MPV_FLAG_SKIP_RD
#define FF_MPV_FLAG_SKIP_RD 0x0001
Definition at line 570 of file mpegvideo.h.
Referenced by encode_thread().
FF_MPV_FLAG_STRICT_GOP
#define FF_MPV_FLAG_STRICT_GOP 0x0002
Definition at line 571 of file mpegvideo.h.
Referenced by select_input_picture().
FF_MPV_FLAG_QP_RD
#define FF_MPV_FLAG_QP_RD 0x0004
Definition at line 572 of file mpegvideo.h.
Referenced by encode_mb_internal(), encode_thread(), and ff_mpv_encode_init().
FF_MPV_FLAG_CBP_RD
#define FF_MPV_FLAG_CBP_RD 0x0008
Definition at line 573 of file mpegvideo.h.
Referenced by encode_mb_internal(), ff_mpv_encode_init(), get_b_cbp(), and get_p_cbp().
FF_MPV_FLAG_NAQ
#define FF_MPV_FLAG_NAQ 0x0010
Definition at line 574 of file mpegvideo.h.
Referenced by adaptive_quantization(), and ff_mpv_encode_init().
FF_MPV_FLAG_MV0
#define FF_MPV_FLAG_MV0 0x0020
Definition at line 575 of file mpegvideo.h.
Referenced by epzs_motion_search_internal(), ff_estimate_b_frame_motion(), ff_estimate_p_frame_motion(), and ff_mpv_encode_init().
FF_MPV_OPT_CMP_FUNC
#define FF_MPV_OPT_CMP_FUNC
Value:
{ "sad",    "Sum of absolute differences, fast", 0, AV_OPT_TYPE_CONST, {.i64 = FF_CMP_SAD }, INT_MIN, INT_MAX, FF_MPV_OPT_FLAGS, "cmp_func" }, \
{ "sse",    "Sum of squared errors", 0, AV_OPT_TYPE_CONST, {.i64 = FF_CMP_SSE }, INT_MIN, INT_MAX, FF_MPV_OPT_FLAGS, "cmp_func" }, \
{ "satd",   "Sum of absolute Hadamard transformed differences", 0, AV_OPT_TYPE_CONST, {.i64 = FF_CMP_SATD }, INT_MIN, INT_MAX, FF_MPV_OPT_FLAGS, "cmp_func" }, \
{ "dct",    "Sum of absolute DCT transformed differences", 0, AV_OPT_TYPE_CONST, {.i64 = FF_CMP_DCT }, INT_MIN, INT_MAX, FF_MPV_OPT_FLAGS, "cmp_func" }, \
{ "psnr",   "Sum of squared quantization errors, low quality", 0, AV_OPT_TYPE_CONST, {.i64 = FF_CMP_PSNR }, INT_MIN, INT_MAX, FF_MPV_OPT_FLAGS, "cmp_func" }, \
{ "bit",    "Number of bits needed for the block", 0, AV_OPT_TYPE_CONST, {.i64 = FF_CMP_BIT }, INT_MIN, INT_MAX, FF_MPV_OPT_FLAGS, "cmp_func" }, \
{ "rd",     "Rate distortion optimal, slow", 0, AV_OPT_TYPE_CONST, {.i64 = FF_CMP_RD }, INT_MIN, INT_MAX, FF_MPV_OPT_FLAGS, "cmp_func" }, \
{ "zero",   "Zero", 0, AV_OPT_TYPE_CONST, {.i64 = FF_CMP_ZERO }, INT_MIN, INT_MAX, FF_MPV_OPT_FLAGS, "cmp_func" }, \
{ "vsad",   "Sum of absolute vertical differences", 0, AV_OPT_TYPE_CONST, {.i64 = FF_CMP_VSAD }, INT_MIN, INT_MAX, FF_MPV_OPT_FLAGS, "cmp_func" }, \
{ "vsse",   "Sum of squared vertical differences", 0, AV_OPT_TYPE_CONST, {.i64 = FF_CMP_VSSE }, INT_MIN, INT_MAX, FF_MPV_OPT_FLAGS, "cmp_func" }, \
{ "nsse",   "Noise preserving sum of squared differences", 0, AV_OPT_TYPE_CONST, {.i64 = FF_CMP_NSSE }, INT_MIN, INT_MAX, FF_MPV_OPT_FLAGS, "cmp_func" }, \
{ "dct264", NULL, 0, AV_OPT_TYPE_CONST, {.i64 = FF_CMP_DCT264 }, INT_MIN, INT_MAX, FF_MPV_OPT_FLAGS, "cmp_func" }, \
{ "dctmax", NULL, 0, AV_OPT_TYPE_CONST, {.i64 = FF_CMP_DCTMAX }, INT_MIN, INT_MAX, FF_MPV_OPT_FLAGS, "cmp_func" }, \
{ "chroma", NULL, 0, AV_OPT_TYPE_CONST, {.i64 = FF_CMP_CHROMA }, INT_MIN, INT_MAX, FF_MPV_OPT_FLAGS, "cmp_func" }, \
{ "msad",   "Sum of absolute differences, median predicted", 0, AV_OPT_TYPE_CONST, {.i64 = FF_CMP_MEDIAN_SAD }, INT_MIN, INT_MAX, FF_MPV_OPT_FLAGS, "cmp_func" }
Definition at line 583 of file mpegvideo.h.
FF_MPV_OFFSET
#define FF_MPV_OFFSET (x) offsetof(MpegEncContext, x)
Definition at line 601 of file mpegvideo.h.
FF_MPV_OPT_FLAGS
#define FF_MPV_OPT_FLAGS (AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM)
Definition at line 603 of file mpegvideo.h.
FF_MPV_COMMON_OPTS
#define FF_MPV_COMMON_OPTS
Definition at line 604 of file mpegvideo.h.
Enumeration Type Documentation
rc_strategy
enum rc_strategy
Enumerator
MPV_RC_STRATEGY_FFMPEG
MPV_RC_STRATEGY_XVID
NB_MPV_RC_STRATEGY
Definition at line 577 of file mpegvideo.h.
Function Documentation
ff_mpv_common_defaults()
void ff_mpv_common_defaults (MpegEncContext * s)
Set the given MpegEncContext to common defaults (same for encoding and decoding).
The changed fields will not depend upon the prior state of the MpegEncContext.
Definition at line 634 of file mpegvideo.c.
Referenced by ff_mpv_decode_defaults(), and mpv_encode_defaults().
ff_dct_encode_init_x86()
void ff_dct_encode_init_x86 (MpegEncContext * s)
Definition at line 204 of file mpegvideoenc.c.
Referenced by ff_dct_encode_init().
ff_mpv_common_init()
int ff_mpv_common_init (MpegEncContext * s)
init common structure for both encoder and decoder.
this assumes that some variables like width/height are already set
Definition at line 877 of file mpegvideo.c.
Referenced by ff_h263_decode_frame(), ff_h263_decode_init(), ff_mpeg_update_thread_context(), ff_mpv_encode_init(), ff_rv34_decode_init(), ff_rv34_decode_init_thread_copy(), h261_decode_frame(), mpeg_decode_postinit(), rv10_decode_init(), rv20_decode_picture_header(), svq1_encode_init(), and vcr2_init_sequence().
ff_mpv_common_init_arm()
void ff_mpv_common_init_arm (MpegEncContext * s)
Definition at line 43 of file mpegvideo_arm.c.
Referenced by dct_init().
ff_mpv_common_init_axp()
void ff_mpv_common_init_axp (MpegEncContext * s)
Definition at line 106 of file mpegvideo_alpha.c.
Referenced by dct_init().
ff_mpv_common_init_neon()
void ff_mpv_common_init_neon (MpegEncContext * s)
Definition at line 126 of file mpegvideo.c.
Referenced by dct_init().
ff_mpv_common_init_ppc()
void ff_mpv_common_init_ppc (MpegEncContext * s)
Definition at line 117 of file mpegvideo_altivec.c.
Referenced by dct_init().
ff_mpv_common_init_x86()
void ff_mpv_common_init_x86 (MpegEncContext * s)
Definition at line 454 of file mpegvideo.c.
Referenced by dct_init().
ff_mpv_common_init_mips()
void ff_mpv_common_init_mips (MpegEncContext * s)
Definition at line 50 of file mpegvideo_init_mips.c.
Referenced by dct_init().
ff_mpv_common_frame_size_change()
int ff_mpv_common_frame_size_change (MpegEncContext * s)
Definition at line 1036 of file mpegvideo.c.
Referenced by ff_h263_decode_frame(), ff_mpeg_update_thread_context(), ff_rv34_decode_frame(), and ff_rv34_decode_update_thread_context().
ff_mpv_common_end()
void ff_mpv_common_end (MpegEncContext * s)
Definition at line 1115 of file mpegvideo.c.
Referenced by ff_h263_decode_end(), ff_mpv_common_frame_size_change(), ff_mpv_common_init(), ff_mpv_encode_end(), ff_rv34_decode_end(), ff_rv34_decode_init(), ff_rv34_decode_init_thread_copy(), ff_vc1_decode_end(), h261_decode_end(), h261_decode_frame(), mpeg_decode_end(), mpeg_decode_postinit(), rv10_decode_end(), rv20_decode_picture_header(), svq1_encode_end(), vc1_decode_frame(), and vcr2_init_sequence().
ff_mpv_decode_defaults()
void ff_mpv_decode_defaults (MpegEncContext * s)
Set the given MpegEncContext to defaults for decoding.
the changed fields will not depend upon the prior state of the MpegEncContext.
Definition at line 657 of file mpegvideo.c.
Referenced by ff_h263_decode_init(), ff_rv34_decode_init(), h261_decode_init(), mpeg_decode_init(), and rv10_decode_init().
ff_mpv_decode_init()
void ff_mpv_decode_init (MpegEncContext * s, AVCodecContext * avctx)
Definition at line 662 of file mpegvideo.c.
Referenced by ff_h263_decode_init(), ff_rv34_decode_init(), h261_decode_init(), mpeg_decode_init(), and rv10_decode_init().
ff_mpv_decode_mb()
void ff_mpv_decode_mb (MpegEncContext * s, int16_t block[12][64])
Definition at line 2722 of file mpegvideo.c.
Referenced by decode_slice(), encode_mb_hq(), encode_thread(), h261_decode_mb(), h261_decode_mb_skipped(), mpeg_decode_slice(), mpeg_er_decode_mb(), and rv10_decode_packet().
ff_mpv_report_decode_progress()
void ff_mpv_report_decode_progress (MpegEncContext * s)
Definition at line 2818 of file mpegvideo.c.
Referenced by decode_slice(), and mpeg_decode_slice().
ff_mpv_frame_start()
int ff_mpv_frame_start (MpegEncContext * s, AVCodecContext * avctx)
generic function called after decoding the header and before a frame is decoded.
Definition at line 1189 of file mpegvideo.c.
Referenced by decode_wmv9(), ff_h263_decode_frame(), ff_rv34_decode_frame(), h261_decode_frame(), mpeg_field_start(), rv10_decode_packet(), and vc1_decode_frame().
ff_mpv_frame_end()
void ff_mpv_frame_end (MpegEncContext * s)
Definition at line 1421 of file mpegvideo.c.
Referenced by decode_wmv9(), ff_h263_decode_frame(), ff_rv34_decode_frame(), finish_frame(), h261_decode_frame(), rv10_decode_frame(), rv10_decode_packet(), slice_end(), and vc1_decode_frame().
ff_mpv_encode_init()
int ff_mpv_encode_init (AVCodecContext * avctx)
Definition at line 286 of file mpegvideo_enc.c.
Referenced by encode_init(), and wmv2_encode_init().
ff_mpv_encode_init_x86()
void ff_mpv_encode_init_x86 (MpegEncContext * s)
ff_mpv_encode_end()
int ff_mpv_encode_end (AVCodecContext * avctx)
Definition at line 1120 of file mpegvideo_enc.c.
Referenced by ff_mpv_encode_init(), and mpeg12_class().
ff_mpv_encode_picture()
int ff_mpv_encode_picture (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * frame, int * got_packet)
Definition at line 1844 of file mpegvideo_enc.c.
Referenced by amv_encode_picture(), and mpeg12_class().
ff_mpv_reallocate_putbitbuffer()
int ff_mpv_reallocate_putbitbuffer (MpegEncContext * s, size_t threshold, size_t size_increase)
Definition at line 2900 of file mpegvideo_enc.c.
Referenced by encode_thread(), and ff_mjpeg_encode_stuffing().
ff_clean_intra_table_entries()
void ff_clean_intra_table_entries (MpegEncContext * s)
Clean dc, ac, coded_block for the current non-intra MB.
Definition at line 2433 of file mpegvideo.c.
Referenced by encode_thread(), mpeg4_decode_partition_a(), and mpv_decode_mb_internal().
ff_mpeg_draw_horiz_band()
void ff_mpeg_draw_horiz_band (MpegEncContext * s, int y, int h)
Definition at line 2734 of file mpegvideo.c.
Referenced by decode_slice(), dxva2_mpeg2_end_frame(), dxva2_vc1_end_frame(), ff_vaapi_common_end_frame(), ff_vdpau_add_buffer(), ff_vdpau_common_end_frame(), ff_xvmc_decode_mb(), ff_xvmc_field_end(), mpeg_decode_slice(), vc1_decode_b_blocks(), vc1_decode_i_blocks(), vc1_decode_i_blocks_adv(), vc1_decode_p_blocks(), and vc1_decode_skip_blocks().
ff_mpeg_flush()
void ff_mpeg_flush (AVCodecContext * avctx)
Definition at line 2773 of file mpegvideo.c.
Referenced by decode_wmv9(), and flush().
ff_print_debug_info()
void ff_print_debug_info (MpegEncContext * s, Picture * p, AVFrame * pict)
Definition at line 1961 of file mpegvideo.c.
Referenced by ff_h263_decode_frame(), finish_frame(), h261_decode_frame(), rv10_decode_frame(), slice_end(), and vc1_decode_frame().
ff_print_debug_info2()
void ff_print_debug_info2 (AVCodecContext * avctx, AVFrame * pict, uint8_t * mbskip_table, uint32_t * mbtype_table, int8_t * qscale_table, int16_t(*[2]) motion_val[2], int * low_delay, int mb_width, int mb_height, int mb_stride, int quarter_sample)
Print debugging info for the given picture.
Definition at line 1579 of file mpegvideo.c.
Referenced by ff_print_debug_info(), and h264_decode_frame().
ff_mpv_export_qp_table()
int ff_mpv_export_qp_table (MpegEncContext * s, AVFrame * f, Picture * p, int qp_type)
Definition at line 1968 of file mpegvideo.c.
Referenced by ff_h263_decode_frame(), finish_frame(), rv10_decode_frame(), and slice_end().
ff_write_quant_matrix()
void ff_write_quant_matrix (PutBitContext * pb, uint16_t * matrix)
Definition at line 201 of file mpegvideo_enc.c.
Referenced by mpeg1_encode_sequence_header(), and mpeg4_encode_vol_header().
ff_update_duplicate_context()
int ff_update_duplicate_context (MpegEncContext * dst, MpegEncContext * src)
Definition at line 455 of file mpegvideo.c.
Referenced by decode_chunks(), and encode_picture().
ff_mpeg_update_thread_context()
int ff_mpeg_update_thread_context (AVCodecContext * dst, const AVCodecContext * src)
Definition at line 483 of file mpegvideo.c.
Referenced by ff_mpeg4_frame_end(), ff_rv34_decode_update_thread_context(), and mpeg_decode_init().
ff_set_qscale()
void ff_set_qscale (MpegEncContext * s, int qscale)
set qscale and update qscale dependent variables.
Definition at line 2804 of file mpegvideo.c.
Referenced by decode_slice(), encode_mb_internal(), encode_thread(), ff_h261_encode_mb(), h261_decode_gob(), h261_decode_mb(), h263_decode_dquant(), mpeg4_decode_mb(), mpeg4_decode_partition_a(), mpeg4_decode_partition_b(), mpeg4_decode_partitioned_mb(), and rv10_decode_packet().
ff_mpv_idct_init()
void ff_mpv_idct_init (MpegEncContext * s)
Definition at line 330 of file mpegvideo.c.
Referenced by dnxhd_encode_init(), ff_h263_decode_frame(), ff_h263_decode_init(), ff_mpeg4_workaround_bugs(), ff_mpeg_update_thread_context(), ff_mpv_encode_init(), ff_rv34_decode_init(), ff_rv34_decode_init_thread_copy(), h261_decode_frame(), mpeg_decode_init(), mpeg_decode_postinit(), rv10_decode_init(), and vcr2_init_sequence().
ff_dct_encode_init()
int ff_dct_encode_init (MpegEncContext * s)
Definition at line 268 of file mpegvideo_enc.c.
Referenced by dnxhd_encode_init(), and ff_mpv_encode_init().
ff_convert_matrix()
void ff_convert_matrix (MpegEncContext * s, int(*) qmat[64], uint16_t(*) qmat16[2][64], const uint16_t * quant_matrix, int bias, int qmin, int qmax, int intra)
Definition at line 89 of file mpegvideo_enc.c.
Referenced by dnxhd_init_qmat(), encode_picture(), and ff_mpv_encode_init().
ff_dct_quantize_c()
int ff_dct_quantize_c (MpegEncContext * s, int16_t * block, int n, int qscale, int * overflow)
Definition at line 4723 of file mpegvideo_enc.c.
Referenced by dnxhd_encode_init(), encode_mb_internal(), and ff_dct_encode_init().
ff_block_permute()
void ff_block_permute (int16_t * block, uint8_t * permutation, const uint8_t * scantable, int last)
Permute an 8x8 block according to permutation.
Parameters
block the block which will be permuted according to the given permutation vector
permutation the permutation vector
last the last non zero coefficient in scantable order, used to speed the permutation up
scantable the used scantable, this is only used to speed the permutation up, the block is not (inverse) permutated to scantable order!
Definition at line 4698 of file mpegvideo_enc.c.
Referenced by dnxhd_10bit_dct_quantize(), and ff_dct_quantize_c().
ff_init_block_index()
void ff_init_block_index (MpegEncContext * s)
Definition at line 2741 of file mpegvideo.c.
Referenced by decode_slice(), encode_thread(), estimate_motion_thread(), ff_h261_reorder_mb_index(), h261_decode_mb(), h261_decode_mb_skipped(), init_block_index(), mpeg4_decode_partition_a(), mpeg4_decode_partition_b(), mpeg_decode_slice(), mpeg_er_decode_mb(), rv10_decode_packet(), and rv34_decode_slice().
ff_mpv_motion()
void ff_mpv_motion (MpegEncContext * s, uint8_t * dest_y, uint8_t * dest_cb, uint8_t * dest_cr, int dir, uint8_t ** ref_picture, op_pixels_func(*) pix_op[4], qpel_mc_func(*) qpix_op[16])
Definition at line 979 of file mpegvideo_motion.c.
Referenced by encode_mb_internal(), and mpv_decode_mb_internal().
ff_update_block_index()
static void ff_update_block_index (MpegEncContext * s) inline static
Definition at line 730 of file mpegvideo.h.
Referenced by decode_slice(), encode_thread(), ff_h261_reorder_mb_index(), ff_vc1_apply_p_loop_filter(), h261_decode_mb(), h261_decode_mb_skipped(), mpeg4_decode_partition_a(), mpeg4_decode_partition_b(), mpeg_er_decode_mb(), rv10_decode_packet(), rv34_decode_slice(), vc1_decode_b_blocks(), vc1_decode_i_blocks(), vc1_decode_i_blocks_adv(), vc1_decode_p_blocks(), and vc1_decode_skip_blocks().
get_bits_diff()
static int get_bits_diff (MpegEncContext * s) inline static
Definition at line 744 of file mpegvideo.h.
Referenced by ff_h263_encode_mb(), ff_mjpeg_encode_mb(), ff_mpeg4_encode_mb(), ff_msmpeg4_encode_mb(), ff_wmv2_encode_mb(), mpeg1_encode_mb_internal(), and write_slice_end().
Variable Documentation
ff_mpv_generic_options
const AVOption ff_mpv_generic_options[]
Definition at line 84 of file mpegvideo_enc.c.