FFmpeg: libavcodec/mpegvideo.c File Reference
mpegvideo.c File Reference
The simplest mpeg encoder (well, it was the simplest!).
#include "libavutil/attributes.h"
#include "libavutil/avassert.h"
#include "libavutil/imgutils.h"
#include "libavutil/internal.h"
#include "libavutil/motion_vector.h"
#include "libavutil/timer.h"
#include "avcodec.h"
#include "blockdsp.h"
#include "h264chroma.h"
#include "idctdsp.h"
#include "internal.h"
#include "mathops.h"
#include "mpeg_er.h"
#include "mpegutils.h"
#include "mpegvideo.h"
#include "mpegvideodata.h"
#include "mjpegenc.h"
#include "msmpeg4.h"
#include "qpeldsp.h"
#include "thread.h"
#include "wmv2.h"
#include <limits.h>
Macros
#define COPY(a) bak->a = src->a
#define UPDATE_PICTURE(pic)
#define REBASE_PICTURE(pic, new_ctx, old_ctx)
#define COLOR(theta, r)
Functions
static void dct_unquantize_mpeg1_intra_c (MpegEncContext *s, int16_t *block, int n, int qscale)
static void dct_unquantize_mpeg1_inter_c (MpegEncContext *s, int16_t *block, int n, int qscale)
static void dct_unquantize_mpeg2_intra_c (MpegEncContext *s, int16_t *block, int n, int qscale)
static void dct_unquantize_mpeg2_intra_bitexact (MpegEncContext *s, int16_t *block, int n, int qscale)
static void dct_unquantize_mpeg2_inter_c (MpegEncContext *s, int16_t *block, int n, int qscale)
static void dct_unquantize_h263_intra_c (MpegEncContext *s, int16_t *block, int n, int qscale)
static void dct_unquantize_h263_inter_c (MpegEncContext *s, int16_t *block, int n, int qscale)
static void gray16 (uint8_t *dst, const uint8_t *src, ptrdiff_t linesize, int h)
static void gray8 (uint8_t *dst, const uint8_t *src, ptrdiff_t linesize, int h)
static av_cold int dct_init (MpegEncContext *s)
av_cold void ff_mpv_idct_init (MpegEncContext *s)
static int alloc_picture (MpegEncContext *s, Picture *pic, int shared)
static int init_duplicate_context (MpegEncContext *s)
static void free_duplicate_context (MpegEncContext *s)
static void backup_duplicate_context (MpegEncContext *bak, MpegEncContext *src)
int ff_update_duplicate_context (MpegEncContext *dst, MpegEncContext *src)
int ff_mpeg_update_thread_context (AVCodecContext *dst, const AVCodecContext *src)
void ff_mpv_common_defaults (MpegEncContext *s)
Set the given MpegEncContext to common defaults (same for encoding and decoding).
void ff_mpv_decode_defaults (MpegEncContext *s)
Set the given MpegEncContext to defaults for decoding.
void ff_mpv_decode_init (MpegEncContext *s, AVCodecContext *avctx)
static int init_context_frame (MpegEncContext *s)
Initialize and allocates MpegEncContext fields dependent on the resolution.
static void clear_context (MpegEncContext *s)
av_cold int ff_mpv_common_init (MpegEncContext *s)
init common structure for both encoder and decoder.
static void free_context_frame (MpegEncContext *s)
Frees and resets MpegEncContext fields depending on the resolution.
int ff_mpv_common_frame_size_change (MpegEncContext *s)
void ff_mpv_common_end (MpegEncContext *s)
static void gray_frame (AVFrame *frame)
int ff_mpv_frame_start (MpegEncContext *s, AVCodecContext *avctx)
generic function called after decoding the header and before a frame is decoded.
void ff_mpv_frame_end (MpegEncContext *s)
static int clip_line (int *sx, int *sy, int *ex, int *ey, int maxx)
static void draw_line (uint8_t *buf, int sx, int sy, int ex, int ey, int w, int h, int stride, int color)
Draw a line from (ex, ey) -> (sx, sy).
static void draw_arrow (uint8_t *buf, int sx, int sy, int ex, int ey, int w, int h, int stride, int color, int tail, int direction)
Draw an arrow from (ex, ey) -> (sx, sy).
static int add_mb (AVMotionVector *mb, uint32_t mb_type, int dst_x, int dst_y, int motion_x, int motion_y, int motion_scale, int direction)
void ff_print_debug_info2 (AVCodecContext *avctx, AVFrame *pict, uint8_t *mbskip_table, uint32_t *mbtype_table, int8_t *qscale_table, int16_t(*motion_val[2])[2], int *low_delay, int mb_width, int mb_height, int mb_stride, int quarter_sample)
Print debugging info for the given picture.
void ff_print_debug_info (MpegEncContext *s, Picture *p, AVFrame *pict)
int ff_mpv_export_qp_table (MpegEncContext *s, AVFrame *f, Picture *p, int qp_type)
static int hpel_motion_lowres (MpegEncContext *s, uint8_t *dest, uint8_t *src, int field_based, int field_select, int src_x, int src_y, int width, int height, ptrdiff_t stride, int h_edge_pos, int v_edge_pos, int w, int h, h264_chroma_mc_func *pix_op, int motion_x, int motion_y)
static av_always_inline void mpeg_motion_lowres (MpegEncContext *s, uint8_t *dest_y, uint8_t *dest_cb, uint8_t *dest_cr, int field_based, int bottom_field, int field_select, uint8_t **ref_picture, h264_chroma_mc_func *pix_op, int motion_x, int motion_y, int h, int mb_y)
static void chroma_4mv_motion_lowres (MpegEncContext *s, uint8_t *dest_cb, uint8_t *dest_cr, uint8_t **ref_picture, h264_chroma_mc_func *pix_op, int mx, int my)
static void MPV_motion_lowres (MpegEncContext *s, uint8_t *dest_y, uint8_t *dest_cb, uint8_t *dest_cr, int dir, uint8_t **ref_picture, h264_chroma_mc_func *pix_op)
motion compensation of a single macroblock
static int lowest_referenced_row (MpegEncContext *s, int dir)
find the lowest MB row referenced in the MVs
static void put_dct (MpegEncContext *s, int16_t *block, int i, uint8_t *dest, int line_size, int qscale)
static void add_dct (MpegEncContext *s, int16_t *block, int i, uint8_t *dest, int line_size)
static void add_dequant_dct (MpegEncContext *s, int16_t *block, int i, uint8_t *dest, int line_size, int qscale)
void ff_clean_intra_table_entries (MpegEncContext *s)
Clean dc, ac, coded_block for the current non-intra MB.
static av_always_inline void mpv_decode_mb_internal (MpegEncContext *s, int16_t block[12][64], int lowres_flag, int is_mpeg12)
void ff_mpv_decode_mb (MpegEncContext *s, int16_t block[12][64])
void ff_mpeg_draw_horiz_band (MpegEncContext *s, int y, int h)
void ff_init_block_index (MpegEncContext *s)
void ff_mpeg_flush (AVCodecContext *avctx)
void ff_set_qscale (MpegEncContext *s, int qscale)
set qscale and update qscale dependent variables.
void ff_mpv_report_decode_progress (MpegEncContext *s)
Detailed Description
The simplest mpeg encoder (well, it was the simplest!).
Definition in file mpegvideo.c.
Macro Definition Documentation
COPY
#define COPY (a) bak->a = src->a
Referenced by backup_duplicate_context().
UPDATE_PICTURE
#define UPDATE_PICTURE (pic)
Value:
do {\
    ff_mpeg_unref_picture(s->avctx, &s->pic);\
    if (s1->pic.f && s1->pic.f->buf[0])\
        ret = ff_mpeg_ref_picture(s->avctx, &s->pic, &s1->pic);\
    else\
        ret = ff_update_picture_tables(&s->pic, &s1->pic);\
    if (ret < 0)\
        return ret;\
} while (0)
Referenced by ff_mpeg_update_thread_context().
REBASE_PICTURE
#define REBASE_PICTURE (pic, new_ctx, old_ctx)
Value:
((pic && pic >= old_ctx->picture &&                                       \
      pic < old_ctx->picture + MAX_PICTURE_COUNT) ?                           \
        &new_ctx->picture[pic - old_ctx->picture] : NULL)
Referenced by ff_mpeg_update_thread_context().
COLOR
#define COLOR (theta, r)
Value:
u = (int)(128 + r * cos(theta * M_PI / 180)); \
    v = (int)(128 + r * sin(theta * M_PI / 180));
Referenced by ff_print_debug_info2().
Function Documentation
dct_unquantize_mpeg1_intra_c()
static void dct_unquantize_mpeg1_intra_c (MpegEncContext * s, int16_t * block, int n, int qscale) static
Definition at line 53 of file mpegvideo.c.
Referenced by dct_init().
dct_unquantize_mpeg1_inter_c()
static void dct_unquantize_mpeg1_inter_c (MpegEncContext * s, int16_t * block, int n, int qscale) static
Definition at line 82 of file mpegvideo.c.
Referenced by dct_init().
dct_unquantize_mpeg2_intra_c()
static void dct_unquantize_mpeg2_intra_c (MpegEncContext * s, int16_t * block, int n, int qscale) static
Definition at line 111 of file mpegvideo.c.
Referenced by dct_init().
dct_unquantize_mpeg2_intra_bitexact()
static void dct_unquantize_mpeg2_intra_bitexact (MpegEncContext * s, int16_t * block, int n, int qscale) static
Definition at line 141 of file mpegvideo.c.
Referenced by dct_init().
dct_unquantize_mpeg2_inter_c()
static void dct_unquantize_mpeg2_inter_c (MpegEncContext * s, int16_t * block, int n, int qscale) static
Definition at line 175 of file mpegvideo.c.
Referenced by dct_init().
dct_unquantize_h263_intra_c()
static void dct_unquantize_h263_intra_c (MpegEncContext * s, int16_t * block, int n, int qscale) static
Definition at line 209 of file mpegvideo.c.
Referenced by dct_init().
dct_unquantize_h263_inter_c()
static void dct_unquantize_h263_inter_c (MpegEncContext * s, int16_t * block, int n, int qscale) static
Definition at line 243 of file mpegvideo.c.
Referenced by dct_init().
gray16()
static void gray16 (uint8_t * dst, const uint8_t * src, ptrdiff_t linesize, int h) static
Definition at line 270 of file mpegvideo.c.
Referenced by dct_init().
gray8()
static void gray8 (uint8_t * dst, const uint8_t * src, ptrdiff_t linesize, int h) static
Definition at line 276 of file mpegvideo.c.
Referenced by dct_init().
dct_init()
static av_cold int dct_init (MpegEncContext * s) static
Definition at line 283 of file mpegvideo.c.
Referenced by ff_mpv_common_init(), fft_end(), and main().
ff_mpv_idct_init()
av_cold void ff_mpv_idct_init (MpegEncContext * s)
Definition at line 330 of file mpegvideo.c.
Referenced by dnxhd_encode_init(), ff_h263_decode_frame(), ff_h263_decode_init(), ff_mpeg4_workaround_bugs(), ff_mpeg_update_thread_context(), ff_mpv_encode_init(), ff_rv34_decode_init(), ff_rv34_decode_init_thread_copy(), h261_decode_frame(), mpeg_decode_init(), mpeg_decode_postinit(), rv10_decode_init(), and vcr2_init_sequence().
alloc_picture()
static int alloc_picture (MpegEncContext * s, Picture * pic, int shared) static
Definition at line 348 of file mpegvideo.c.
Referenced by ff_mpv_frame_start().
init_duplicate_context()
static int init_duplicate_context (MpegEncContext * s) static
Definition at line 356 of file mpegvideo.c.
Referenced by ff_mpv_common_frame_size_change(), and ff_mpv_common_init().
free_duplicate_context()
static void free_duplicate_context (MpegEncContext * s) static
Definition at line 408 of file mpegvideo.c.
Referenced by ff_mpv_common_end(), and ff_mpv_common_frame_size_change().
backup_duplicate_context()
static void backup_duplicate_context (MpegEncContext * bak, MpegEncContext * src) static
Definition at line 428 of file mpegvideo.c.
Referenced by ff_update_duplicate_context().
ff_update_duplicate_context()
int ff_update_duplicate_context (MpegEncContext * dst, MpegEncContext * src)
Definition at line 455 of file mpegvideo.c.
Referenced by decode_chunks(), and encode_picture().
ff_mpeg_update_thread_context()
int ff_mpeg_update_thread_context (AVCodecContext * dst, const AVCodecContext * src)
Definition at line 483 of file mpegvideo.c.
Referenced by ff_mpeg4_frame_end(), ff_rv34_decode_update_thread_context(), and mpeg_decode_init().
ff_mpv_common_defaults()
void ff_mpv_common_defaults (MpegEncContext * s)
Set the given MpegEncContext to common defaults (same for encoding and decoding).
The changed fields will not depend upon the prior state of the MpegEncContext.
Definition at line 634 of file mpegvideo.c.
Referenced by ff_mpv_decode_defaults(), and mpv_encode_defaults().
ff_mpv_decode_defaults()
void ff_mpv_decode_defaults (MpegEncContext * s)
Set the given MpegEncContext to defaults for decoding.
the changed fields will not depend upon the prior state of the MpegEncContext.
Definition at line 657 of file mpegvideo.c.
Referenced by ff_h263_decode_init(), ff_rv34_decode_init(), h261_decode_init(), mpeg_decode_init(), and rv10_decode_init().
ff_mpv_decode_init()
void ff_mpv_decode_init (MpegEncContext * s, AVCodecContext * avctx)
Definition at line 662 of file mpegvideo.c.
Referenced by ff_h263_decode_init(), ff_rv34_decode_init(), h261_decode_init(), mpeg_decode_init(), and rv10_decode_init().
init_context_frame()
static int init_context_frame (MpegEncContext * s) static
Initialize and allocates MpegEncContext fields dependent on the resolution.
Definition at line 677 of file mpegvideo.c.
Referenced by ff_mpv_common_frame_size_change(), and ff_mpv_common_init().
clear_context()
static void clear_context (MpegEncContext * s) static
Definition at line 798 of file mpegvideo.c.
Referenced by ff_mpv_common_init().
ff_mpv_common_init()
av_cold int ff_mpv_common_init (MpegEncContext * s)
init common structure for both encoder and decoder.
this assumes that some variables like width/height are already set
Definition at line 877 of file mpegvideo.c.
Referenced by ff_h263_decode_frame(), ff_h263_decode_init(), ff_mpeg_update_thread_context(), ff_mpv_encode_init(), ff_rv34_decode_init(), ff_rv34_decode_init_thread_copy(), h261_decode_frame(), mpeg_decode_postinit(), rv10_decode_init(), rv20_decode_picture_header(), svq1_encode_init(), and vcr2_init_sequence().
free_context_frame()
static void free_context_frame (MpegEncContext * s) static
Frees and resets MpegEncContext fields depending on the resolution.
Is used during resolution changes to avoid a full reinitialization of the codec.
Definition at line 987 of file mpegvideo.c.
Referenced by ff_mpv_common_end(), and ff_mpv_common_frame_size_change().
ff_mpv_common_frame_size_change()
int ff_mpv_common_frame_size_change (MpegEncContext * s)
Definition at line 1036 of file mpegvideo.c.
Referenced by ff_h263_decode_frame(), ff_mpeg_update_thread_context(), ff_rv34_decode_frame(), and ff_rv34_decode_update_thread_context().
ff_mpv_common_end()
void ff_mpv_common_end (MpegEncContext * s)
Definition at line 1115 of file mpegvideo.c.
Referenced by ff_h263_decode_end(), ff_mpv_common_frame_size_change(), ff_mpv_common_init(), ff_mpv_encode_end(), ff_rv34_decode_end(), ff_rv34_decode_init(), ff_rv34_decode_init_thread_copy(), ff_vc1_decode_end(), h261_decode_end(), h261_decode_frame(), mpeg_decode_end(), mpeg_decode_postinit(), rv10_decode_end(), rv20_decode_picture_header(), svq1_encode_end(), vc1_decode_frame(), and vcr2_init_sequence().
gray_frame()
static void gray_frame (AVFrame * frame) static
Definition at line 1169 of file mpegvideo.c.
Referenced by ff_mpv_frame_start().
ff_mpv_frame_start()
int ff_mpv_frame_start (MpegEncContext * s, AVCodecContext * avctx)
generic function called after decoding the header and before a frame is decoded.
Definition at line 1189 of file mpegvideo.c.
Referenced by decode_wmv9(), ff_h263_decode_frame(), ff_rv34_decode_frame(), h261_decode_frame(), mpeg_field_start(), rv10_decode_packet(), and vc1_decode_frame().
ff_mpv_frame_end()
void ff_mpv_frame_end (MpegEncContext * s)
Definition at line 1421 of file mpegvideo.c.
Referenced by decode_wmv9(), ff_h263_decode_frame(), ff_rv34_decode_frame(), finish_frame(), h261_decode_frame(), rv10_decode_frame(), rv10_decode_packet(), slice_end(), and vc1_decode_frame().
clip_line()
static int clip_line (int * sx, int * sy, int * ex, int * ey, int maxx) static
Definition at line 1431 of file mpegvideo.c.
Referenced by draw_line().
draw_line()
static void draw_line (uint8_t * buf, int sx, int sy, int ex, int ey, int w, int h, int stride, int color) static
Draw a line from (ex, ey) -> (sx, sy).
Parameters
w width of the image
h height of the image
stride stride/linesize of the image
color color of the arrow
Definition at line 1460 of file mpegvideo.c.
Referenced by draw_arrow().
draw_arrow()
static void draw_arrow (uint8_t * buf, int sx, int sy, int ex, int ey, int w, int h, int stride, int color, int tail, int direction) static
Draw an arrow from (ex, ey) -> (sx, sy).
Parameters
w width of the image
h height of the image
stride stride/linesize of the image
color color of the arrow
Definition at line 1518 of file mpegvideo.c.
Referenced by ff_print_debug_info2().
add_mb()
static int add_mb (AVMotionVector * mb, uint32_t mb_type, int dst_x, int dst_y, int motion_x, int motion_y, int motion_scale, int direction) static
Definition at line 1557 of file mpegvideo.c.
Referenced by ff_print_debug_info2().
ff_print_debug_info2()
void ff_print_debug_info2 (AVCodecContext * avctx, AVFrame * pict, uint8_t * mbskip_table, uint32_t * mbtype_table, int8_t * qscale_table, int16_t(*[2]) motion_val[2], int * low_delay, int mb_width, int mb_height, int mb_stride, int quarter_sample)
Print debugging info for the given picture.
Definition at line 1579 of file mpegvideo.c.
Referenced by ff_print_debug_info(), and h264_decode_frame().
ff_print_debug_info()
void ff_print_debug_info (MpegEncContext * s, Picture * p, AVFrame * pict)
Definition at line 1961 of file mpegvideo.c.
Referenced by ff_h263_decode_frame(), finish_frame(), h261_decode_frame(), rv10_decode_frame(), slice_end(), and vc1_decode_frame().
ff_mpv_export_qp_table()
int ff_mpv_export_qp_table (MpegEncContext * s, AVFrame * f, Picture * p, int qp_type)
Definition at line 1968 of file mpegvideo.c.
Referenced by ff_h263_decode_frame(), finish_frame(), rv10_decode_frame(), and slice_end().
hpel_motion_lowres()
static int hpel_motion_lowres (MpegEncContext * s, uint8_t * dest, uint8_t * src, int field_based, int field_select, int src_x, int src_y, int width, int height, ptrdiff_t stride, int h_edge_pos, int v_edge_pos, int w, int h, h264_chroma_mc_func * pix_op, int motion_x, int motion_y) inline static
Definition at line 1980 of file mpegvideo.c.
Referenced by MPV_motion_lowres().
mpeg_motion_lowres()
static av_always_inline void mpeg_motion_lowres (MpegEncContext * s, uint8_t * dest_y, uint8_t * dest_cb, uint8_t * dest_cr, int field_based, int bottom_field, int field_select, uint8_t ** ref_picture, h264_chroma_mc_func * pix_op, int motion_x, int motion_y, int h, int mb_y) static
Definition at line 2027 of file mpegvideo.c.
Referenced by MPV_motion_lowres().
chroma_4mv_motion_lowres()
static void chroma_4mv_motion_lowres (MpegEncContext * s, uint8_t * dest_cb, uint8_t * dest_cr, uint8_t ** ref_picture, h264_chroma_mc_func * pix_op, int mx, int my) inline static
Definition at line 2166 of file mpegvideo.c.
Referenced by MPV_motion_lowres().
MPV_motion_lowres()
static void MPV_motion_lowres (MpegEncContext * s, uint8_t * dest_y, uint8_t * dest_cb, uint8_t * dest_cr, int dir, uint8_t ** ref_picture, h264_chroma_mc_func * pix_op) inline static
motion compensation of a single macroblock
Parameters
s context
dest_y luma destination pointer
dest_cb chroma cb/u destination pointer
dest_cr chroma cr/v destination pointer
dir direction (0->forward, 1->backward)
ref_picture array[3] of pointers to the 3 planes of the reference picture
pix_op halfpel motion compensation function (average or put normally) the motion vectors are taken from s->mv and the MV type from s->mv_type
Definition at line 2234 of file mpegvideo.c.
Referenced by mpv_decode_mb_internal().
lowest_referenced_row()
static int lowest_referenced_row (MpegEncContext * s, int dir) static
find the lowest MB row referenced in the MVs
Definition at line 2368 of file mpegvideo.c.
Referenced by mpv_decode_mb_internal().
put_dct()
static void put_dct (MpegEncContext * s, int16_t * block, int i, uint8_t * dest, int line_size, int qscale) inline static
Definition at line 2404 of file mpegvideo.c.
Referenced by mpv_decode_mb_internal().
add_dct()
static void add_dct (MpegEncContext * s, int16_t * block, int i, uint8_t * dest, int line_size) inline static
Definition at line 2412 of file mpegvideo.c.
Referenced by mpv_decode_mb_internal().
add_dequant_dct()
static void add_dequant_dct (MpegEncContext * s, int16_t * block, int i, uint8_t * dest, int line_size, int qscale) inline static
Definition at line 2420 of file mpegvideo.c.
Referenced by mpv_decode_mb_internal().
ff_clean_intra_table_entries()
void ff_clean_intra_table_entries (MpegEncContext * s)
Clean dc, ac, coded_block for the current non-intra MB.
Definition at line 2433 of file mpegvideo.c.
Referenced by encode_thread(), mpeg4_decode_partition_a(), and mpv_decode_mb_internal().
mpv_decode_mb_internal()
static av_always_inline void mpv_decode_mb_internal (MpegEncContext * s, int16_t block[12][64], int lowres_flag, int is_mpeg12) static
Definition at line 2474 of file mpegvideo.c.
Referenced by ff_mpv_decode_mb().
ff_mpv_decode_mb()
void ff_mpv_decode_mb (MpegEncContext * s, int16_t block[12][64])
Definition at line 2722 of file mpegvideo.c.
Referenced by decode_slice(), encode_mb_hq(), encode_thread(), h261_decode_mb(), h261_decode_mb_skipped(), mpeg_decode_slice(), mpeg_er_decode_mb(), and rv10_decode_packet().
ff_mpeg_draw_horiz_band()
void ff_mpeg_draw_horiz_band (MpegEncContext * s, int y, int h)
Definition at line 2734 of file mpegvideo.c.
Referenced by decode_slice(), dxva2_mpeg2_end_frame(), dxva2_vc1_end_frame(), ff_vaapi_common_end_frame(), ff_vdpau_add_buffer(), ff_vdpau_common_end_frame(), ff_xvmc_decode_mb(), ff_xvmc_field_end(), mpeg_decode_slice(), vc1_decode_b_blocks(), vc1_decode_i_blocks(), vc1_decode_i_blocks_adv(), vc1_decode_p_blocks(), and vc1_decode_skip_blocks().
ff_init_block_index()
void ff_init_block_index (MpegEncContext * s)
Definition at line 2741 of file mpegvideo.c.
Referenced by decode_slice(), encode_thread(), estimate_motion_thread(), ff_h261_reorder_mb_index(), h261_decode_mb(), h261_decode_mb_skipped(), init_block_index(), mpeg4_decode_partition_a(), mpeg4_decode_partition_b(), mpeg_decode_slice(), mpeg_er_decode_mb(), rv10_decode_packet(), and rv34_decode_slice().
ff_mpeg_flush()
void ff_mpeg_flush (AVCodecContext * avctx)
Definition at line 2773 of file mpegvideo.c.
Referenced by decode_wmv9(), and flush().
ff_set_qscale()
void ff_set_qscale (MpegEncContext * s, int qscale)
set qscale and update qscale dependent variables.
Definition at line 2804 of file mpegvideo.c.
Referenced by decode_slice(), encode_mb_internal(), encode_thread(), ff_h261_encode_mb(), h261_decode_gob(), h261_decode_mb(), h263_decode_dquant(), mpeg4_decode_mb(), mpeg4_decode_partition_a(), mpeg4_decode_partition_b(), mpeg4_decode_partitioned_mb(), and rv10_decode_packet().
ff_mpv_report_decode_progress()
void ff_mpv_report_decode_progress (MpegEncContext * s)
Definition at line 2818 of file mpegvideo.c.
Referenced by decode_slice(), and mpeg_decode_slice().