FFmpeg: libavcodec/mpegaudiodsp.h File Reference
mpegaudiodsp.h File Reference
#include <stdint.h>
#include "libavutil/common.h"
Data Structures
struct MPADSPContext
Macros
#define MDCT_BUF_SIZE FFALIGN(36, 2*4)
For SSE implementation, MDCT_BUF_SIZE/2 should be 128-bit aligned.
Functions
void ff_mpadsp_init (MPADSPContext *s)
void ff_mpa_synth_filter_fixed (MPADSPContext *s, int32_t *synth_buf_ptr, int *synth_buf_offset, int32_t *window, int *dither_state, int16_t *samples, int incr, int32_t *sb_samples)
void ff_mpa_synth_filter_float (MPADSPContext *s, float *synth_buf_ptr, int *synth_buf_offset, float *window, int *dither_state, float *samples, int incr, float *sb_samples)
void ff_mpadsp_init_aarch64 (MPADSPContext *s)
void ff_mpadsp_init_arm (MPADSPContext *s)
void ff_mpadsp_init_ppc (MPADSPContext *s)
void ff_mpadsp_init_x86 (MPADSPContext *s)
void ff_mpadsp_init_mipsfpu (MPADSPContext *s)
void ff_mpadsp_init_mipsdsp (MPADSPContext *s)
void ff_mpa_synth_init_float (float *window)
void ff_mpa_synth_init_fixed (int32_t *window)
void ff_mpadsp_apply_window_float (float *synth_buf, float *window, int *dither_state, float *samples, int incr)
void ff_mpadsp_apply_window_fixed (int32_t *synth_buf, int32_t *window, int *dither_state, int16_t *samples, int incr)
void ff_imdct36_blocks_float (float *out, float *buf, float *in, int count, int switch_point, int block_type)
void ff_imdct36_blocks_fixed (int *out, int *buf, int *in, int count, int switch_point, int block_type)
void ff_init_mpadsp_tabs_float (void)
void ff_init_mpadsp_tabs_fixed (void)
Variables
int32_t ff_mpa_synth_window_fixed []
float ff_mpa_synth_window_float []
const int32_t ff_mpa_enwindow [257]
int ff_mdct_win_fixed [8][MDCT_BUF_SIZE]
Window for MDCT.
float ff_mdct_win_float [8][MDCT_BUF_SIZE]
Macro Definition Documentation
MDCT_BUF_SIZE
#define MDCT_BUF_SIZE FFALIGN(36, 2*4)
For SSE implementation, MDCT_BUF_SIZE/2 should be 128-bit aligned.
Definition at line 85 of file mpegaudiodsp.h.
Referenced by ff_init_mpadsp_tabs(), and imdct36().
Function Documentation
ff_mpadsp_init()
void ff_mpadsp_init (MPADSPContext * s)
Definition at line 27 of file mpegaudiodsp.c.
Referenced by decode_init(), mpc7_decode_init(), mpc8_decode_init(), and qdm2_decode_init().
ff_mpa_synth_filter_fixed()
void ff_mpa_synth_filter_fixed (MPADSPContext * s, int32_t * synth_buf_ptr, int * synth_buf_offset, int32_t * window, int * dither_state, int16_t * samples, int incr, int32_t * sb_samples)
Referenced by mpc_synth().
ff_mpa_synth_filter_float()
void ff_mpa_synth_filter_float (MPADSPContext * s, float * synth_buf_ptr, int * synth_buf_offset, float * window, int * dither_state, float * samples, int incr, float * sb_samples)
Referenced by qdm2_synthesis_filter().
ff_mpadsp_init_aarch64()
void ff_mpadsp_init_aarch64 (MPADSPContext * s)
Definition at line 31 of file mpegaudiodsp_init.c.
Referenced by ff_mpadsp_init().
ff_mpadsp_init_arm()
void ff_mpadsp_init_arm (MPADSPContext * s)
Definition at line 31 of file mpegaudiodsp_init_arm.c.
Referenced by ff_mpadsp_init().
ff_mpadsp_init_ppc()
void ff_mpadsp_init_ppc (MPADSPContext * s)
Definition at line 133 of file mpegaudiodsp_altivec.c.
Referenced by ff_mpadsp_init().
ff_mpadsp_init_x86()
void ff_mpadsp_init_x86 (MPADSPContext * s)
Definition at line 242 of file mpegaudiodsp.c.
Referenced by ff_mpadsp_init().
ff_mpadsp_init_mipsfpu()
void ff_mpadsp_init_mipsfpu (MPADSPContext * s)
Definition at line 1252 of file mpegaudiodsp_mips_float.c.
Referenced by ff_mpadsp_init().
ff_mpadsp_init_mipsdsp()
void ff_mpadsp_init_mipsdsp (MPADSPContext * s)
Definition at line 910 of file mpegaudiodsp_mips_fixed.c.
Referenced by ff_mpadsp_init().
ff_mpa_synth_init_float()
void ff_mpa_synth_init_float (float * window)
Referenced by qdm2_init_static_data().
ff_mpa_synth_init_fixed()
void ff_mpa_synth_init_fixed (int32_t * window)
Referenced by ff_mpc_init().
ff_mpadsp_apply_window_float()
void ff_mpadsp_apply_window_float (float * synth_buf, float * window, int * dither_state, float * samples, int incr)
Referenced by ff_mpadsp_init().
ff_mpadsp_apply_window_fixed()
void ff_mpadsp_apply_window_fixed (int32_t * synth_buf, int32_t * window, int * dither_state, int16_t * samples, int incr)
Referenced by ff_mpadsp_init().
ff_imdct36_blocks_float()
void ff_imdct36_blocks_float (float * out, float * buf, float * in, int count, int switch_point, int block_type)
Referenced by ff_mpadsp_init().
ff_imdct36_blocks_fixed()
void ff_imdct36_blocks_fixed (int * out, int * buf, int * in, int count, int switch_point, int block_type)
Referenced by ff_mpadsp_init().
ff_init_mpadsp_tabs_float()
void ff_init_mpadsp_tabs_float (void)
Referenced by ff_mpadsp_init().
ff_init_mpadsp_tabs_fixed()
void ff_init_mpadsp_tabs_fixed (void)
Referenced by ff_mpadsp_init().
Variable Documentation
ff_mpa_synth_window_fixed
int32_t ff_mpa_synth_window_fixed[]
Definition at line 78 of file mpegaudiodsp_template.c.
Referenced by ff_mpc_init(), and mpc_synth().
ff_mpa_synth_window_float
float ff_mpa_synth_window_float[]
Referenced by qdm2_init_static_data(), and qdm2_synthesis_filter().
ff_mpa_enwindow
const int32_t ff_mpa_enwindow[257]
Definition at line 22 of file mpegaudiodsp_data.c.
Referenced by ff_mpa_synth_init(), and MPA_encode_init().
ff_mdct_win_fixed
int ff_mdct_win_fixed[8][MDCT_BUF_SIZE]
Window for MDCT.
Actually only the elements in [0,17] and [MDCT_BUF_SIZE/2, MDCT_BUF_SIZE/2 + 17] are actually used. The rest is just to preserve alignment for SIMD implementations.
Definition at line 76 of file mpegaudiodsp_template.c.
ff_mdct_win_float
float ff_mdct_win_float[8][MDCT_BUF_SIZE]
Referenced by ff_mpadsp_init_x86().