FFmpeg: libavcodec/mpeg4videodec.c File Reference
mpeg4videodec.c File Reference
#include "libavutil/internal.h"
#include "libavutil/opt.h"
#include "error_resilience.h"
#include "idctdsp.h"
#include "internal.h"
#include "mpegutils.h"
#include "mpegvideo.h"
#include "mpegvideodata.h"
#include "mpeg4video.h"
#include "h263.h"
#include "profiles.h"
#include "thread.h"
#include "xvididct.h"
Macros
#define UNCHECKED_BITSTREAM_READER 1
#define SPRITE_TRAJ_VLC_BITS 6
#define DC_VLC_BITS 9
#define MB_TYPE_B_VLC_BITS 4
#define SET_QPEL_FUNC(postfix1, postfix2)
Functions
void ff_mpeg4_pred_ac (MpegEncContext *s, int16_t *block, int n, int dir)
Predict the ac.
static int mpeg4_is_resync (Mpeg4DecContext *ctx)
check if the next stuff is a resync marker or the end.
static int mpeg4_decode_sprite_trajectory (Mpeg4DecContext *ctx, GetBitContext *gb)
static int decode_new_pred (Mpeg4DecContext *ctx, GetBitContext *gb)
int ff_mpeg4_decode_video_packet_header (Mpeg4DecContext *ctx)
Decode the next video packet.
static int get_amv (Mpeg4DecContext *ctx, int n)
Get the average motion vector for a GMC MB.
static int mpeg4_decode_dc (MpegEncContext *s, int n, int *dir_ptr)
Decode the dc value.
static int mpeg4_decode_partition_a (Mpeg4DecContext *ctx)
Decode first partition.
static int mpeg4_decode_partition_b (MpegEncContext *s, int mb_count)
decode second partition.
int ff_mpeg4_decode_partitions (Mpeg4DecContext *ctx)
Decode the first and second partition.
static int mpeg4_decode_block (Mpeg4DecContext *ctx, int16_t *block, int n, int coded, int intra, int rvlc)
Decode a block.
static int mpeg4_decode_partitioned_mb (MpegEncContext *s, int16_t block[6][64])
decode partition C of one MB.
static int mpeg4_decode_mb (MpegEncContext *s, int16_t block[6][64])
static int mpeg4_decode_gop_header (MpegEncContext *s, GetBitContext *gb)
static int mpeg4_decode_profile_level (MpegEncContext *s, GetBitContext *gb)
static int decode_vol_header (Mpeg4DecContext *ctx, GetBitContext *gb)
static int decode_user_data (Mpeg4DecContext *ctx, GetBitContext *gb)
Decode the user data stuff in the header.
int ff_mpeg4_workaround_bugs (AVCodecContext *avctx)
static int decode_vop_header (Mpeg4DecContext *ctx, GetBitContext *gb)
int ff_mpeg4_decode_picture_header (Mpeg4DecContext *ctx, GetBitContext *gb)
Decode MPEG-4 headers.
av_cold void ff_mpeg4videodec_static_init (void)
int ff_mpeg4_frame_end (AVCodecContext *avctx, const uint8_t *buf, int buf_size)
static av_cold int decode_init (AVCodecContext *avctx)
Variables
static VLC dc_lum
static VLC dc_chrom
static VLC sprite_trajectory
static VLC mb_type_b_vlc
static const int mb_type_b_map [4]
static const AVOption mpeg4_options []
static const AVClass mpeg4_class
AVCodec ff_mpeg4_decoder
Macro Definition Documentation
UNCHECKED_BITSTREAM_READER
#define UNCHECKED_BITSTREAM_READER 1
Definition at line 23 of file mpeg4videodec.c.
SPRITE_TRAJ_VLC_BITS
#define SPRITE_TRAJ_VLC_BITS 6
Definition at line 43 of file mpeg4videodec.c.
Referenced by ff_mpeg4videodec_static_init(), and mpeg4_decode_sprite_trajectory().
DC_VLC_BITS
#define DC_VLC_BITS 9
Definition at line 44 of file mpeg4videodec.c.
Referenced by ff_mpeg4videodec_static_init(), and mpeg4_decode_dc().
MB_TYPE_B_VLC_BITS
#define MB_TYPE_B_VLC_BITS 4
Definition at line 45 of file mpeg4videodec.c.
Referenced by ff_mpeg4videodec_static_init(), and mpeg4_decode_mb().
SET_QPEL_FUNC
#define SET_QPEL_FUNC (postfix1, postfix2)
Value:
s->qdsp.put_        ## postfix1 = ff_put_        ## postfix2;   \
    s->qdsp.put_no_rnd_ ## postfix1 = ff_put_no_rnd_ ## postfix2;   \
    s->qdsp.avg_        ## postfix1 = ff_avg_        ## postfix2;
Referenced by ff_mpeg4_workaround_bugs().
Function Documentation
ff_mpeg4_pred_ac()
void ff_mpeg4_pred_ac (MpegEncContext * s, int16_t * block, int n, int dir)
Predict the ac.
Parameters
n block index (0-3 are luma, 4-5 are chroma)
dir the ac prediction direction
Definition at line 63 of file mpeg4videodec.c.
Referenced by ff_msmpeg4_decode_block(), and mpeg4_decode_block().
mpeg4_is_resync()
static int mpeg4_is_resync (Mpeg4DecContext * ctx) inline static
check if the next stuff is a resync marker or the end.
Returns
0 if not
Definition at line 118 of file mpeg4videodec.c.
Referenced by mpeg4_decode_mb(), and mpeg4_decode_partitioned_mb().
mpeg4_decode_sprite_trajectory()
static int mpeg4_decode_sprite_trajectory (Mpeg4DecContext * ctx, GetBitContext * gb) static
Definition at line 168 of file mpeg4videodec.c.
Referenced by decode_vop_header(), and ff_mpeg4_decode_video_packet_header().
decode_new_pred()
static int decode_new_pred (Mpeg4DecContext * ctx, GetBitContext * gb) static
Definition at line 383 of file mpeg4videodec.c.
Referenced by decode_vop_header(), and ff_mpeg4_decode_video_packet_header().
ff_mpeg4_decode_video_packet_header()
int ff_mpeg4_decode_video_packet_header (Mpeg4DecContext * ctx)
Decode the next video packet.
Returns
<0 if something went wrong
Definition at line 399 of file mpeg4videodec.c.
Referenced by ff_h263_resync().
get_amv()
static int get_amv (Mpeg4DecContext * ctx, int n) inline static
Get the average motion vector for a GMC MB.
Parameters
n either 0 for the x component or 1 for y
Returns
the average MV for a GMC MB
Definition at line 493 of file mpeg4videodec.c.
Referenced by mpeg4_decode_mb(), and mpeg4_decode_partition_a().
mpeg4_decode_dc()
static int mpeg4_decode_dc (MpegEncContext * s, int n, int * dir_ptr) inline static
Decode the dc value.
Parameters
n block index (0-3 are luma, 4-5 are chroma)
dir_ptr the prediction direction will be stored here
Returns
the quantized dc
Definition at line 546 of file mpeg4videodec.c.
Referenced by mpeg4_decode_block(), mpeg4_decode_partition_a(), and mpeg4_decode_partition_b().
mpeg4_decode_partition_a()
static int mpeg4_decode_partition_a (Mpeg4DecContext * ctx) static
Decode first partition.
Returns
number of MBs decoded or <0 if an error occurred
Definition at line 593 of file mpeg4videodec.c.
Referenced by ff_mpeg4_decode_partitions().
mpeg4_decode_partition_b()
static int mpeg4_decode_partition_b (MpegEncContext * s, int mb_count) static
decode second partition.
Returns
<0 if an error occurred
Definition at line 787 of file mpeg4videodec.c.
Referenced by ff_mpeg4_decode_partitions().
ff_mpeg4_decode_partitions()
int ff_mpeg4_decode_partitions (Mpeg4DecContext * ctx)
Decode the first and second partition.
Returns
<0 if error (and sets error type in the error_status_table)
Definition at line 880 of file mpeg4videodec.c.
Referenced by decode_slice().
mpeg4_decode_block()
static int mpeg4_decode_block (Mpeg4DecContext * ctx, int16_t * block, int n, int coded, int intra, int rvlc) inline static
Decode a block.
Returns
<0 if an error occurred
Definition at line 943 of file mpeg4videodec.c.
Referenced by mpeg4_decode_mb(), and mpeg4_decode_partitioned_mb().
mpeg4_decode_partitioned_mb()
static int mpeg4_decode_partitioned_mb (MpegEncContext * s, int16_t block[6][64]) static
decode partition C of one MB.
Returns
<0 if an error occurred
Definition at line 1214 of file mpeg4videodec.c.
Referenced by decode_vop_header().
mpeg4_decode_mb()
static int mpeg4_decode_mb (MpegEncContext * s, int16_t block[6][64]) static
Definition at line 1299 of file mpeg4videodec.c.
Referenced by decode_init(), and decode_vop_header().
mpeg4_decode_gop_header()
static int mpeg4_decode_gop_header (MpegEncContext * s, GetBitContext * gb) static
Definition at line 1678 of file mpeg4videodec.c.
Referenced by ff_mpeg4_decode_picture_header().
mpeg4_decode_profile_level()
static int mpeg4_decode_profile_level (MpegEncContext * s, GetBitContext * gb) static
Definition at line 1700 of file mpeg4videodec.c.
Referenced by ff_mpeg4_decode_picture_header().
decode_vol_header()
static int decode_vol_header (Mpeg4DecContext * ctx, GetBitContext * gb) static
Definition at line 1714 of file mpeg4videodec.c.
Referenced by ff_mpeg4_decode_picture_header().
decode_user_data()
static int decode_user_data (Mpeg4DecContext * ctx, GetBitContext * gb) static
Decode the user data stuff in the header.
Also initializes divx/xvid/lavc_version/build.
Definition at line 2082 of file mpeg4videodec.c.
Referenced by ff_mpeg4_decode_picture_header().
ff_mpeg4_workaround_bugs()
int ff_mpeg4_workaround_bugs (AVCodecContext * avctx)
Definition at line 2132 of file mpeg4videodec.c.
Referenced by ff_h263_decode_frame().
decode_vop_header()
static int decode_vop_header (Mpeg4DecContext * ctx, GetBitContext * gb) static
Definition at line 2250 of file mpeg4videodec.c.
Referenced by ff_mpeg4_decode_picture_header().
ff_mpeg4_decode_picture_header()
int ff_mpeg4_decode_picture_header (Mpeg4DecContext * ctx, GetBitContext * gb)
Decode MPEG-4 headers.
Returns
<0 if no VOP found (or a damaged one) FRAME_SKIPPED if a not coded VOP is found 0 if a VOP is found
Definition at line 2525 of file mpeg4videodec.c.
Referenced by ff_h263_decode_frame(), and mpeg4_decode_header().
ff_mpeg4videodec_static_init()
av_cold void ff_mpeg4videodec_static_init (void)
Definition at line 2642 of file mpeg4videodec.c.
Referenced by decode_init(), and mpeg4video_parse_init().
ff_mpeg4_frame_end()
int ff_mpeg4_frame_end (AVCodecContext * avctx, const uint8_t * buf, int buf_size)
Definition at line 2668 of file mpeg4videodec.c.
Referenced by ff_h263_decode_frame().
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 2739 of file mpeg4videodec.c.
Variable Documentation
dc_lum
VLC dc_lum static
Definition at line 47 of file mpeg4videodec.c.
dc_chrom
VLC dc_chrom static
Definition at line 47 of file mpeg4videodec.c.
sprite_trajectory
VLC sprite_trajectory static
Definition at line 48 of file mpeg4videodec.c.
mb_type_b_vlc
VLC mb_type_b_vlc static
Definition at line 49 of file mpeg4videodec.c.
mb_type_b_map
const int mb_type_b_map[4] static
Initial value:
= {
    MB_TYPE_DIRECT2 | MB_TYPE_L0L1,
    MB_TYPE_L0L1    | MB_TYPE_16x16,
    MB_TYPE_L1      | MB_TYPE_16x16,
    MB_TYPE_L0      | MB_TYPE_16x16,
}
Definition at line 51 of file mpeg4videodec.c.
Referenced by mpeg4_decode_mb().
mpeg4_options
const AVOption mpeg4_options[] static
Initial value:
= {
    {"quarter_sample", "1/4 subpel MC", 0x42, AV_OPT_TYPE_BOOL, {.i64 = 0}, 0, 1, 0},
    {"divx_packed", "divx style packed b frames", 0x42, AV_OPT_TYPE_BOOL, {.i64 = 0}, 0, 1, 0},
    {NULL}
}
Definition at line 2766 of file mpeg4videodec.c.
mpeg4_class
const AVClass mpeg4_class static
Initial value:
= {
    "MPEG4 Video Decoder",
    av_default_item_name,
    mpeg4_options,
    LIBAVUTIL_VERSION_INT,
}
Definition at line 2772 of file mpeg4videodec.c.
ff_mpeg4_decoder
AVCodec ff_mpeg4_decoder
Initial value:
= {
    .name                  = "mpeg4",
    .long_name             = NULL_IF_CONFIG_SMALL("MPEG-4 part 2"),
    .type                  = AVMEDIA_TYPE_VIDEO,
    .id                    = AV_CODEC_ID_MPEG4,
    .priv_data_size        = sizeof(Mpeg4DecContext),
    .init                  = decode_init,
    .close                 = ff_h263_decode_end,
    .decode                = ff_h263_decode_frame,
    .capabilities          = AV_CODEC_CAP_DRAW_HORIZ_BAND | AV_CODEC_CAP_DR1 |
                             AV_CODEC_CAP_TRUNCATED | AV_CODEC_CAP_DELAY |
                             AV_CODEC_CAP_FRAME_THREADS,
    .flush                 = ff_mpeg_flush,
    .max_lowres            = 3,
    .pix_fmts              = ff_h263_hwaccel_pixfmt_list_420,
    .profiles              = NULL_IF_CONFIG_SMALL(ff_mpeg4_video_profiles),
    .update_thread_context = ONLY_IF_THREADS_ENABLED(mpeg4_update_thread_context),
    .priv_class = &mpeg4_class,
}
Definition at line 2779 of file mpeg4videodec.c.