FFmpeg: libavcodec/mpeg12dec.c File Reference
mpeg12dec.c File Reference
MPEG-1/2 decoder.
#include <inttypes.h>
#include "libavutil/attributes.h"
#include "libavutil/imgutils.h"
#include "libavutil/internal.h"
#include "libavutil/stereo3d.h"
#include "avcodec.h"
#include "bytestream.h"
#include "error_resilience.h"
#include "idctdsp.h"
#include "internal.h"
#include "mpeg_er.h"
#include "mpeg12.h"
#include "mpeg12data.h"
#include "mpegutils.h"
#include "mpegvideo.h"
#include "mpegvideodata.h"
#include "profiles.h"
#include "thread.h"
#include "version.h"
#include "vdpau_compat.h"
#include "xvmc_internal.h"
Data Structures
struct Mpeg1Context
Macros
#define UNCHECKED_BITSTREAM_READER 1
#define MB_TYPE_ZERO_MV 0x20000000
#define MAX_INDEX (64 - 1)
#define check_scantable_index(ctx, x)
#define MT_FIELD 1
#define MT_FRAME 2
#define MT_16X8 2
#define MT_DMV 3
#define DECODE_SLICE_ERROR -1
#define DECODE_SLICE_OK 0
Functions
static int mpeg_decode_motion (MpegEncContext *s, int fcode, int pred)
static int mpeg1_decode_block_inter (MpegEncContext *s, int16_t *block, int n)
static int mpeg1_fast_decode_block_inter (MpegEncContext *s, int16_t *block, int n)
Note: this function can read out of range and crash for corrupt streams.
static int mpeg2_decode_block_non_intra (MpegEncContext *s, int16_t *block, int n)
static int mpeg2_fast_decode_block_non_intra (MpegEncContext *s, int16_t *block, int n)
Note: this function can read out of range and crash for corrupt streams.
static int mpeg2_decode_block_intra (MpegEncContext *s, int16_t *block, int n)
static int mpeg2_fast_decode_block_intra (MpegEncContext *s, int16_t *block, int n)
Note: this function can read out of range and crash for corrupt streams.
static int get_dmv (MpegEncContext *s)
static int get_qscale (MpegEncContext *s)
static int mpeg_decode_mb (MpegEncContext *s, int16_t block[12][64])
static av_cold int mpeg_decode_init (AVCodecContext *avctx)
static void quant_matrix_rebuild (uint16_t *matrix, const uint8_t *old_perm, const uint8_t *new_perm)
static enum AVPixelFormat mpeg_get_pixelformat (AVCodecContext *avctx)
static void setup_hwaccel_for_pixfmt (AVCodecContext *avctx)
static int mpeg_decode_postinit (AVCodecContext *avctx)
static int mpeg1_decode_picture (AVCodecContext *avctx, const uint8_t *buf, int buf_size)
static void mpeg_decode_sequence_extension (Mpeg1Context *s1)
static void mpeg_decode_sequence_display_extension (Mpeg1Context *s1)
static void mpeg_decode_picture_display_extension (Mpeg1Context *s1)
static int load_matrix (MpegEncContext *s, uint16_t matrix0[64], uint16_t matrix1[64], int intra)
static void mpeg_decode_quant_matrix_extension (MpegEncContext *s)
static void mpeg_decode_picture_coding_extension (Mpeg1Context *s1)
static int mpeg_field_start (MpegEncContext *s, const uint8_t *buf, int buf_size)
static int mpeg_decode_slice (MpegEncContext *s, int mb_y, const uint8_t **buf, int buf_size)
Decode a slice.
static int slice_decode_thread (AVCodecContext *c, void *arg)
static int slice_end (AVCodecContext *avctx, AVFrame *pict)
Handle slice ends.
static int mpeg1_decode_sequence (AVCodecContext *avctx, const uint8_t *buf, int buf_size)
static int vcr2_init_sequence (AVCodecContext *avctx)
static int mpeg_decode_a53_cc (AVCodecContext *avctx, const uint8_t *p, int buf_size)
static void mpeg_decode_user_data (AVCodecContext *avctx, const uint8_t *p, int buf_size)
static void mpeg_decode_gop (AVCodecContext *avctx, const uint8_t *buf, int buf_size)
static int decode_chunks (AVCodecContext *avctx, AVFrame *picture, int *got_output, const uint8_t *buf, int buf_size)
static int mpeg_decode_frame (AVCodecContext *avctx, void *data, int *got_output, AVPacket *avpkt)
static void flush (AVCodecContext *avctx)
static av_cold int mpeg_decode_end (AVCodecContext *avctx)
Variables
static const uint32_t ptype2mb_type [7]
static const uint32_t btype2mb_type [11]
static enum AVPixelFormat mpeg1_hwaccel_pixfmt_list_420 []
static enum AVPixelFormat mpeg2_hwaccel_pixfmt_list_420 []
static enum AVPixelFormat mpeg12_pixfmt_list_422 []
static enum AVPixelFormat mpeg12_pixfmt_list_444 []
AVCodec ff_mpeg1video_decoder
AVCodec ff_mpeg2video_decoder
AVCodec ff_mpegvideo_decoder
Detailed Description
MPEG-1/2 decoder.
Definition in file mpeg12dec.c.
Macro Definition Documentation
UNCHECKED_BITSTREAM_READER
#define UNCHECKED_BITSTREAM_READER 1
Definition at line 28 of file mpeg12dec.c.
MB_TYPE_ZERO_MV
#define MB_TYPE_ZERO_MV 0x20000000
Definition at line 74 of file mpeg12dec.c.
Referenced by mpeg_decode_mb().
MAX_INDEX
#define MAX_INDEX (64 - 1)
Definition at line 127 of file mpeg12dec.c.
Referenced by mpeg1_decode_block_inter(), mpeg1_fast_decode_block_inter(), mpeg2_decode_block_intra(), mpeg2_decode_block_non_intra(), and mpeg2_fast_decode_block_non_intra().
check_scantable_index
#define check_scantable_index (ctx, x)
Value:
do {                                                                      \
        if ((x) > MAX_INDEX) {                                                \
            av_log(ctx->avctx, AV_LOG_ERROR, "ac-tex damaged at %d %d\n",     \
                   ctx->mb_x, ctx->mb_y);                                     \
            return AVERROR_INVALIDDATA;                                       \
        }                                                                     \
    } while (0)
Definition at line 128 of file mpeg12dec.c.
Referenced by mpeg1_decode_block_inter(), mpeg1_fast_decode_block_inter(), mpeg2_decode_block_intra(), mpeg2_decode_block_non_intra(), mpeg2_fast_decode_block_intra(), and mpeg2_fast_decode_block_non_intra().
MT_FIELD
#define MT_FIELD 1
Definition at line 663 of file mpeg12dec.c.
Referenced by mpeg_decode_mb().
MT_FRAME
#define MT_FRAME 2
Definition at line 664 of file mpeg12dec.c.
Referenced by mpeg_decode_mb().
MT_16X8
#define MT_16X8 2
Definition at line 665 of file mpeg12dec.c.
MT_DMV
#define MT_DMV 3
Definition at line 666 of file mpeg12dec.c.
Referenced by mpeg_decode_mb().
DECODE_SLICE_ERROR
#define DECODE_SLICE_ERROR -1
Definition at line 1715 of file mpeg12dec.c.
Referenced by mpeg_decode_slice().
DECODE_SLICE_OK
#define DECODE_SLICE_OK 0
Definition at line 1716 of file mpeg12dec.c.
Referenced by mpeg_decode_slice().
Function Documentation
mpeg_decode_motion()
static int mpeg_decode_motion (MpegEncContext * s, int fcode, int pred) static
Definition at line 101 of file mpeg12dec.c.
Referenced by mpeg_decode_mb().
mpeg1_decode_block_inter()
static int mpeg1_decode_block_inter (MpegEncContext * s, int16_t * block, int n) inline static
Definition at line 137 of file mpeg12dec.c.
Referenced by mpeg_decode_mb().
mpeg1_fast_decode_block_inter()
static int mpeg1_fast_decode_block_inter (MpegEncContext * s, int16_t * block, int n) inline static
Note: this function can read out of range and crash for corrupt streams.
Changing this would eat up any speed benefits it has. Do not use "fast" flag if you need the code to be robust.
Definition at line 227 of file mpeg12dec.c.
Referenced by mpeg_decode_mb().
mpeg2_decode_block_non_intra()
static int mpeg2_decode_block_non_intra (MpegEncContext * s, int16_t * block, int n) inline static
Definition at line 312 of file mpeg12dec.c.
Referenced by mpeg_decode_mb().
mpeg2_fast_decode_block_non_intra()
static int mpeg2_fast_decode_block_non_intra (MpegEncContext * s, int16_t * block, int n) inline static
Note: this function can read out of range and crash for corrupt streams.
Changing this would eat up any speed benefits it has. Do not use "fast" flag if you need the code to be robust.
Definition at line 403 of file mpeg12dec.c.
Referenced by mpeg_decode_mb().
mpeg2_decode_block_intra()
static int mpeg2_decode_block_intra (MpegEncContext * s, int16_t * block, int n) inline static
Definition at line 475 of file mpeg12dec.c.
Referenced by mpeg_decode_mb().
mpeg2_fast_decode_block_intra()
static int mpeg2_fast_decode_block_intra (MpegEncContext * s, int16_t * block, int n) inline static
Note: this function can read out of range and crash for corrupt streams.
Changing this would eat up any speed benefits it has. Do not use "fast" flag if you need the code to be robust.
Definition at line 565 of file mpeg12dec.c.
Referenced by mpeg_decode_mb().
get_dmv()
static int get_dmv (MpegEncContext * s) inline static
Definition at line 644 of file mpeg12dec.c.
Referenced by mpeg_decode_mb().
get_qscale()
static int get_qscale (MpegEncContext * s) inline static
Definition at line 652 of file mpeg12dec.c.
Referenced by mpeg_decode_mb(), and mpeg_decode_slice().
mpeg_decode_mb()
static int mpeg_decode_mb (MpegEncContext * s, int16_t block[12][64]) static
Definition at line 668 of file mpeg12dec.c.
Referenced by mpeg_decode_slice().
mpeg_decode_init()
static av_cold int mpeg_decode_init (AVCodecContext * avctx) static
Definition at line 1065 of file mpeg12dec.c.
quant_matrix_rebuild()
static void quant_matrix_rebuild (uint16_t * matrix, const uint8_t * old_perm, const uint8_t * new_perm) static
Definition at line 1121 of file mpeg12dec.c.
Referenced by mpeg_decode_postinit().
mpeg_get_pixelformat()
static enum AVPixelFormat mpeg_get_pixelformat (AVCodecContext * avctx) static
Definition at line 1189 of file mpeg12dec.c.
Referenced by mpeg_decode_postinit(), and vcr2_init_sequence().
setup_hwaccel_for_pixfmt()
static void setup_hwaccel_for_pixfmt (AVCodecContext * avctx) static
Definition at line 1210 of file mpeg12dec.c.
Referenced by mpeg_decode_postinit(), and vcr2_init_sequence().
mpeg_decode_postinit()
static int mpeg_decode_postinit (AVCodecContext * avctx) static
Definition at line 1236 of file mpeg12dec.c.
Referenced by decode_chunks().
mpeg1_decode_picture()
static int mpeg1_decode_picture (AVCodecContext * avctx, const uint8_t * buf, int buf_size) static
Definition at line 1372 of file mpeg12dec.c.
Referenced by decode_chunks().
mpeg_decode_sequence_extension()
static void mpeg_decode_sequence_extension (Mpeg1Context * s1) static
Definition at line 1419 of file mpeg12dec.c.
Referenced by decode_chunks().
mpeg_decode_sequence_display_extension()
static void mpeg_decode_sequence_display_extension (Mpeg1Context * s1) static
Definition at line 1462 of file mpeg12dec.c.
Referenced by decode_chunks().
mpeg_decode_picture_display_extension()
static void mpeg_decode_picture_display_extension (Mpeg1Context * s1) static
Definition at line 1486 of file mpeg12dec.c.
Referenced by decode_chunks().
load_matrix()
static int load_matrix (MpegEncContext * s, uint16_t matrix0[64], uint16_t matrix1[64], int intra) static
Definition at line 1520 of file mpeg12dec.c.
Referenced by mpeg1_decode_sequence(), and mpeg_decode_quant_matrix_extension().
mpeg_decode_quant_matrix_extension()
static void mpeg_decode_quant_matrix_extension (MpegEncContext * s) static
Definition at line 1543 of file mpeg12dec.c.
Referenced by decode_chunks().
mpeg_decode_picture_coding_extension()
static void mpeg_decode_picture_coding_extension (Mpeg1Context * s1) static
Definition at line 1557 of file mpeg12dec.c.
Referenced by decode_chunks().
mpeg_field_start()
static int mpeg_field_start (MpegEncContext * s, const uint8_t * buf, int buf_size) static
Definition at line 1616 of file mpeg12dec.c.
Referenced by decode_chunks().
mpeg_decode_slice()
static int mpeg_decode_slice (MpegEncContext * s, int mb_y, const uint8_t ** buf, int buf_size) static
Decode a slice.
MpegEncContext.mb_y must be set to the MB row from the startcode.
Returns
DECODE_SLICE_ERROR if the slice is damaged, DECODE_SLICE_OK if this slice is OK
Definition at line 1724 of file mpeg12dec.c.
Referenced by decode_chunks(), and slice_decode_thread().
slice_decode_thread()
static int slice_decode_thread (AVCodecContext * c, void * arg) static
Definition at line 1999 of file mpeg12dec.c.
Referenced by decode_chunks().
slice_end()
static int slice_end (AVCodecContext * avctx, AVFrame * pict) static
Handle slice ends.
Returns
1 if it seems to be the last slice
Definition at line 2050 of file mpeg12dec.c.
Referenced by compute_sat_hue_metrics16(), compute_sat_hue_metrics8(), decode_chunks(), decode_frame(), DEFINE_BLEND8(), do_chromakey_slice(), do_colorkey_slice(), filter16_3x3(), filter16_5x5(), filter16_brng(), filter16_prewitt(), filter16_sobel(), filter16_tout(), filter16_vrep(), filter8_brng(), filter8_tout(), filter8_vrep(), filter_3x3(), filter_5x5(), filter_color(), filter_color2(), filter_frame(), filter_horizontally(), filter_mono(), filter_postscale(), filter_prewitt(), filter_rgb(), filter_slice(), filter_slice16(), filter_slice8(), filter_slice_alpha(), filter_slice_chroma(), filter_slice_luma(), filter_slice_rgb(), filter_sobel(), filter_vertically(), hqx_filter(), nlmeans_slice(), process_slice_uyvy422(), process_slice_yuv420p(), process_slice_yuv422p(), process_slice_yuv444p(), and xbr_filter().
mpeg1_decode_sequence()
static int mpeg1_decode_sequence (AVCodecContext * avctx, const uint8_t * buf, int buf_size) static
Definition at line 2101 of file mpeg12dec.c.
Referenced by decode_chunks().
vcr2_init_sequence()
static int vcr2_init_sequence (AVCodecContext * avctx) static
Definition at line 2190 of file mpeg12dec.c.
Referenced by mpeg_decode_frame().
mpeg_decode_a53_cc()
static int mpeg_decode_a53_cc (AVCodecContext * avctx, const uint8_t * p, int buf_size) static
Definition at line 2244 of file mpeg12dec.c.
Referenced by mpeg_decode_user_data().
mpeg_decode_user_data()
static void mpeg_decode_user_data (AVCodecContext * avctx, const uint8_t * p, int buf_size) static
Definition at line 2323 of file mpeg12dec.c.
Referenced by decode_chunks().
mpeg_decode_gop()
static void mpeg_decode_gop (AVCodecContext * avctx, const uint8_t * buf, int buf_size) static
Definition at line 2398 of file mpeg12dec.c.
Referenced by decode_chunks().
decode_chunks()
static int decode_chunks (AVCodecContext * avctx, AVFrame * picture, int * got_output, const uint8_t * buf, int buf_size) static
Definition at line 2431 of file mpeg12dec.c.
Referenced by mpeg_decode_frame().
mpeg_decode_frame()
static int mpeg_decode_frame (AVCodecContext * avctx, void * data, int * got_output, AVPacket * avpkt) static
Definition at line 2766 of file mpeg12dec.c.
flush()
static void flush (AVCodecContext * avctx) static
Definition at line 2841 of file mpeg12dec.c.
mpeg_decode_end()
static av_cold int mpeg_decode_end (AVCodecContext * avctx) static
Definition at line 2850 of file mpeg12dec.c.
Variable Documentation
ptype2mb_type
const uint32_t ptype2mb_type[7] static
Initial value:
= {
                    MB_TYPE_INTRA,
                    MB_TYPE_L0 | MB_TYPE_CBP | MB_TYPE_ZERO_MV | MB_TYPE_16x16,
                    MB_TYPE_L0,
                    MB_TYPE_L0 | MB_TYPE_CBP,
    MB_TYPE_QUANT | MB_TYPE_INTRA,
    MB_TYPE_QUANT | MB_TYPE_L0 | MB_TYPE_CBP | MB_TYPE_ZERO_MV | MB_TYPE_16x16,
    MB_TYPE_QUANT | MB_TYPE_L0 | MB_TYPE_CBP,
}
Definition at line 76 of file mpeg12dec.c.
Referenced by mpeg_decode_mb().
btype2mb_type
const uint32_t btype2mb_type[11] static
Initial value:
= {
                    MB_TYPE_INTRA,
                    MB_TYPE_L1,
                    MB_TYPE_L1   | MB_TYPE_CBP,
                    MB_TYPE_L0,
                    MB_TYPE_L0   | MB_TYPE_CBP,
                    MB_TYPE_L0L1,
                    MB_TYPE_L0L1 | MB_TYPE_CBP,
    MB_TYPE_QUANT | MB_TYPE_INTRA,
    MB_TYPE_QUANT | MB_TYPE_L1   | MB_TYPE_CBP,
    MB_TYPE_QUANT | MB_TYPE_L0   | MB_TYPE_CBP,
    MB_TYPE_QUANT | MB_TYPE_L0L1 | MB_TYPE_CBP,
}
Definition at line 86 of file mpeg12dec.c.
Referenced by mpeg_decode_mb().
mpeg1_hwaccel_pixfmt_list_420
enum AVPixelFormat mpeg1_hwaccel_pixfmt_list_420[] static
Initial value:
= {
    AV_PIX_FMT_YUV420P,
    AV_PIX_FMT_NONE
}
Definition at line 1133 of file mpeg12dec.c.
Referenced by mpeg_get_pixelformat().
mpeg2_hwaccel_pixfmt_list_420
enum AVPixelFormat mpeg2_hwaccel_pixfmt_list_420[] static
Initial value:
= {
    AV_PIX_FMT_YUV420P,
    AV_PIX_FMT_NONE
}
Definition at line 1147 of file mpeg12dec.c.
Referenced by mpeg_get_pixelformat().
mpeg12_pixfmt_list_422
enum AVPixelFormat mpeg12_pixfmt_list_422[] static
Initial value:
= {
    AV_PIX_FMT_YUV422P,
    AV_PIX_FMT_NONE
}
Definition at line 1173 of file mpeg12dec.c.
Referenced by mpeg_get_pixelformat().
mpeg12_pixfmt_list_444
enum AVPixelFormat mpeg12_pixfmt_list_444[] static
Initial value:
= {
    AV_PIX_FMT_YUV444P,
    AV_PIX_FMT_NONE
}
Definition at line 1178 of file mpeg12dec.c.
Referenced by mpeg_get_pixelformat().
ff_mpeg1video_decoder
AVCodec ff_mpeg1video_decoder
Initial value:
= {
    .name                  = "mpeg1video",
    .long_name             = NULL_IF_CONFIG_SMALL("MPEG-1 video"),
    .type                  = AVMEDIA_TYPE_VIDEO,
    .id                    = AV_CODEC_ID_MPEG1VIDEO,
    .priv_data_size        = sizeof(Mpeg1Context),
    .init                  = mpeg_decode_init,
    .close                 = mpeg_decode_end,
    .decode                = mpeg_decode_frame,
    .capabilities          = AV_CODEC_CAP_DRAW_HORIZ_BAND | AV_CODEC_CAP_DR1 |
                             AV_CODEC_CAP_TRUNCATED | AV_CODEC_CAP_DELAY |
                             AV_CODEC_CAP_SLICE_THREADS,
    .caps_internal         = FF_CODEC_CAP_SKIP_FRAME_FILL_PARAM,
    .flush                 = flush,
    .max_lowres            = 3,
    .update_thread_context = ONLY_IF_THREADS_ENABLED(mpeg_decode_update_thread_context)
}
Definition at line 2860 of file mpeg12dec.c.
ff_mpeg2video_decoder
AVCodec ff_mpeg2video_decoder
Initial value:
= {
    .name           = "mpeg2video",
    .long_name      = NULL_IF_CONFIG_SMALL("MPEG-2 video"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_MPEG2VIDEO,
    .priv_data_size = sizeof(Mpeg1Context),
    .init           = mpeg_decode_init,
    .close          = mpeg_decode_end,
    .decode         = mpeg_decode_frame,
    .capabilities   = AV_CODEC_CAP_DRAW_HORIZ_BAND | AV_CODEC_CAP_DR1 |
                      AV_CODEC_CAP_TRUNCATED | AV_CODEC_CAP_DELAY |
                      AV_CODEC_CAP_SLICE_THREADS,
    .caps_internal  = FF_CODEC_CAP_SKIP_FRAME_FILL_PARAM,
    .flush          = flush,
    .max_lowres     = 3,
    .profiles       = NULL_IF_CONFIG_SMALL(ff_mpeg2_video_profiles),
}
Definition at line 2878 of file mpeg12dec.c.
ff_mpegvideo_decoder
AVCodec ff_mpegvideo_decoder
Initial value:
= {
    .name           = "mpegvideo",
    .long_name      = NULL_IF_CONFIG_SMALL("MPEG-1 video"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_MPEG2VIDEO,
    .priv_data_size = sizeof(Mpeg1Context),
    .init           = mpeg_decode_init,
    .close          = mpeg_decode_end,
    .decode         = mpeg_decode_frame,
    .capabilities   = AV_CODEC_CAP_DRAW_HORIZ_BAND | AV_CODEC_CAP_DR1 | AV_CODEC_CAP_TRUNCATED | AV_CODEC_CAP_DELAY | AV_CODEC_CAP_SLICE_THREADS,
    .caps_internal  = FF_CODEC_CAP_SKIP_FRAME_FILL_PARAM,
    .flush          = flush,
    .max_lowres     = 3,
}
Definition at line 2897 of file mpeg12dec.c.