FFmpeg: libavformat/mpegts.c File Reference
mpegts.c File Reference
#include "libavutil/buffer.h"
#include "libavutil/crc.h"
#include "libavutil/internal.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/log.h"
#include "libavutil/dict.h"
#include "libavutil/mathematics.h"
#include "libavutil/opt.h"
#include "libavutil/avassert.h"
#include "libavcodec/bytestream.h"
#include "libavcodec/get_bits.h"
#include "libavcodec/opus.h"
#include "avformat.h"
#include "mpegts.h"
#include "internal.h"
#include "avio_internal.h"
#include "mpeg.h"
#include "isom.h"
Data Structures
struct MpegTSPESFilter
struct MpegTSSectionFilter
struct MpegTSFilter
struct Program
struct MpegTSContext
struct PESContext
struct SectionHeader
struct StreamType
struct MP4DescrParseContext
Macros
#define MAX_RESYNC_SIZE 65536
#define MAX_PES_PAYLOAD 200 * 1024
#define MAX_MP4_DESCR_COUNT 16
#define MOD_UNLIKELY(modulus, dividend, divisor, prev_dividend)
#define MAX_PIDS_PER_PROGRAM 64
#define SIZE_STAT_THRESHOLD 10
#define MPEGTS_OPTIONS { "resync_size", "set size limit for looking up a new synchronization", offsetof(MpegTSContext, resync_size), AV_OPT_TYPE_INT, { .i64 = MAX_RESYNC_SIZE}, 0, INT_MAX, AV_OPT_FLAG_DECODING_PARAM }
#define PES_START_SIZE 6
#define PES_HEADER_SIZE 9
#define MAX_PES_HEADER_SIZE (9 + 255)
#define MAX_LEVEL 4
#define R8_CHECK_CLIP_MAX(dst, maxv)
#define CHECK_COUNT 10
#define CHECK_BLOCK 100
#define MAX_PACKET_READAHEAD ((128 * 1024) / 188)
Typedefs
typedef int PESCallback(MpegTSFilter *f, const uint8_t *buf, int len, int is_start, int64_t pos)
typedef void SectionCallback(MpegTSFilter *f, const uint8_t *buf, int len)
typedef void SetServiceCallback(void *opaque, int ret)
Enumerations
enum MpegTSFilterType { MPEGTS_PES, MPEGTS_SECTION, MPEGTS_PCR }
enum MpegTSState {
MPEGTS_HEADER = 0, MPEGTS_PESHEADER, MPEGTS_PESHEADER_FILL, MPEGTS_PAYLOAD,
MPEGTS_SKIP
}
Functions
static struct Program * get_program (MpegTSContext *ts, unsigned int programid)
static void clear_avprogram (MpegTSContext *ts, unsigned int programid)
static void clear_program (MpegTSContext *ts, unsigned int programid)
static void clear_programs (MpegTSContext *ts)
static void add_pat_entry (MpegTSContext *ts, unsigned int programid)
static void add_pid_to_pmt (MpegTSContext *ts, unsigned int programid, unsigned int pid)
static void set_pmt_found (MpegTSContext *ts, unsigned int programid)
static void set_pcr_pid (AVFormatContext *s, unsigned int programid, unsigned int pid)
static int discard_pid (MpegTSContext *ts, unsigned int pid)
discard_pid() decides if the pid is to be discarded according to caller's programs selection
static void write_section_data (MpegTSContext *ts, MpegTSFilter *tss1, const uint8_t *buf, int buf_size, int is_start)
Assemble PES packets out of TS packets, and then call the "section_cb" function when they are complete.
static MpegTSFilter * mpegts_open_filter (MpegTSContext *ts, unsigned int pid, enum MpegTSFilterType type)
static MpegTSFilter * mpegts_open_section_filter (MpegTSContext *ts, unsigned int pid, SectionCallback *section_cb, void *opaque, int check_crc)
static MpegTSFilter * mpegts_open_pes_filter (MpegTSContext *ts, unsigned int pid, PESCallback *pes_cb, void *opaque)
static MpegTSFilter * mpegts_open_pcr_filter (MpegTSContext *ts, unsigned int pid)
static void mpegts_close_filter (MpegTSContext *ts, MpegTSFilter *filter)
static int analyze (const uint8_t *buf, int size, int packet_size, int probe)
static int get_packet_size (const uint8_t *buf, int size)
static int skip_identical (const SectionHeader *h, MpegTSSectionFilter *tssf)
static int get8 (const uint8_t **pp, const uint8_t *p_end)
static int get16 (const uint8_t **pp, const uint8_t *p_end)
static char * getstr8 (const uint8_t **pp, const uint8_t *p_end)
static int parse_section_header (SectionHeader *h, const uint8_t **pp, const uint8_t *p_end)
static void mpegts_find_stream_type (AVStream *st, uint32_t stream_type, const StreamType *types)
static int mpegts_set_stream_info (AVStream *st, PESContext *pes, uint32_t stream_type, uint32_t prog_reg_desc)
static void reset_pes_packet_state (PESContext *pes)
static void new_data_packet (const uint8_t *buffer, int len, AVPacket *pkt)
static int new_pes_packet (PESContext *pes, AVPacket *pkt)
static uint64_t get_ts64 (GetBitContext *gb, int bits)
static int read_sl_header (PESContext *pes, SLConfigDescr *sl, const uint8_t *buf, int buf_size)
static int mpegts_push_data (MpegTSFilter *filter, const uint8_t *buf, int buf_size, int is_start, int64_t pos)
static PESContext * add_pes_stream (MpegTSContext *ts, int pid, int pcr_pid)
static int init_MP4DescrParseContext (MP4DescrParseContext *d, AVFormatContext *s, const uint8_t *buf, unsigned size, Mp4Descr *descr, int max_descr_count)
static void update_offsets (AVIOContext *pb, int64_t *off, int *len)
static int parse_mp4_descr (MP4DescrParseContext *d, int64_t off, int len, int target_tag)
static int parse_mp4_descr_arr (MP4DescrParseContext *d, int64_t off, int len)
static int parse_MP4IODescrTag (MP4DescrParseContext *d, int64_t off, int len)
static int parse_MP4ODescrTag (MP4DescrParseContext *d, int64_t off, int len)
static int parse_MP4ESDescrTag (MP4DescrParseContext *d, int64_t off, int len)
static int parse_MP4DecConfigDescrTag (MP4DescrParseContext *d, int64_t off, int len)
static int parse_MP4SLDescrTag (MP4DescrParseContext *d, int64_t off, int len)
static int mp4_read_iods (AVFormatContext *s, const uint8_t *buf, unsigned size, Mp4Descr *descr, int *descr_count, int max_descr_count)
static int mp4_read_od (AVFormatContext *s, const uint8_t *buf, unsigned size, Mp4Descr *descr, int *descr_count, int max_descr_count)
static void m4sl_cb (MpegTSFilter *filter, const uint8_t *section, int section_len)
static void scte_data_cb (MpegTSFilter *filter, const uint8_t *section, int section_len)
int ff_parse_mpeg2_descriptor (AVFormatContext *fc, AVStream *st, int stream_type, const uint8_t **pp, const uint8_t *desc_list_end, Mp4Descr *mp4_descr, int mp4_descr_count, int pid, MpegTSContext *ts)
Parse an MPEG-2 descriptor.
static int is_pes_stream (int stream_type, uint32_t prog_reg_desc)
static void pmt_cb (MpegTSFilter *filter, const uint8_t *section, int section_len)
static void pat_cb (MpegTSFilter *filter, const uint8_t *section, int section_len)
static void sdt_cb (MpegTSFilter *filter, const uint8_t *section, int section_len)
static int parse_pcr (int64_t *ppcr_high, int *ppcr_low, const uint8_t *packet)
static int handle_packet (MpegTSContext *ts, const uint8_t *packet)
static void reanalyze (MpegTSContext *ts)
static int mpegts_resync (AVFormatContext *s, int seekback, const uint8_t *current_packet)
static int read_packet (AVFormatContext *s, uint8_t *buf, int raw_packet_size, const uint8_t **data)
static void finished_reading_packet (AVFormatContext *s, int raw_packet_size)
static int handle_packets (MpegTSContext *ts, int64_t nb_packets)
static int mpegts_probe (AVProbeData *p)
static void seek_back (AVFormatContext *s, AVIOContext *pb, int64_t pos)
static int mpegts_read_header (AVFormatContext *s)
static int mpegts_raw_read_packet (AVFormatContext *s, AVPacket *pkt)
static int mpegts_read_packet (AVFormatContext *s, AVPacket *pkt)
static void mpegts_free (MpegTSContext *ts)
static int mpegts_read_close (AVFormatContext *s)
static av_unused int64_t mpegts_get_pcr (AVFormatContext *s, int stream_index, int64_t *ppos, int64_t pos_limit)
static int64_t mpegts_get_dts (AVFormatContext *s, int stream_index, int64_t *ppos, int64_t pos_limit)
MpegTSContext * avpriv_mpegts_parse_open (AVFormatContext *s)
int avpriv_mpegts_parse_packet (MpegTSContext *ts, AVPacket *pkt, const uint8_t *buf, int len)
void avpriv_mpegts_parse_close (MpegTSContext *ts)
Variables
static const AVOption options []
static const AVClass mpegts_class
static const AVOption raw_options []
static const AVClass mpegtsraw_class
AVInputFormat ff_mpegts_demuxer
static const StreamType ISO_types []
static const StreamType HDMV_types []
static const StreamType SCTE_types []
static const StreamType MISC_types []
static const StreamType REGD_types []
static const StreamType METADATA_types []
static const StreamType DESC_types []
static const uint8_t opus_coupled_stream_cnt [9]
static const uint8_t opus_stream_cnt [9]
static const uint8_t opus_channel_map [8][8]
AVInputFormat ff_mpegtsraw_demuxer
Macro Definition Documentation
MAX_RESYNC_SIZE
#define MAX_RESYNC_SIZE 65536
Definition at line 43 of file mpegts.c.
MAX_PES_PAYLOAD
#define MAX_PES_PAYLOAD 200 * 1024
Definition at line 45 of file mpegts.c.
Referenced by mpegts_push_data(), and new_pes_packet().
MAX_MP4_DESCR_COUNT
#define MAX_MP4_DESCR_COUNT 16
Definition at line 47 of file mpegts.c.
Referenced by m4sl_cb(), and pmt_cb().
MOD_UNLIKELY
#define MOD_UNLIKELY (modulus, dividend, divisor, prev_dividend)
Value:
do {                                                                       \
        if ((prev_dividend) == 0 || (dividend) - (prev_dividend) != (divisor)) \
            (modulus) = (dividend) % (divisor);                                \
        (prev_dividend) = (dividend);                                          \
    } while (0)
Definition at line 49 of file mpegts.c.
MAX_PIDS_PER_PROGRAM
#define MAX_PIDS_PER_PROGRAM 64
Definition at line 101 of file mpegts.c.
Referenced by add_pid_to_pmt().
SIZE_STAT_THRESHOLD
#define SIZE_STAT_THRESHOLD 10
Definition at line 120 of file mpegts.c.
Referenced by reanalyze().
MPEGTS_OPTIONS
#define MPEGTS_OPTIONS { "resync_size", "set size limit for looking up a new synchronization", offsetof(MpegTSContext, resync_size), AV_OPT_TYPE_INT, { .i64 = MAX_RESYNC_SIZE}, 0, INT_MAX, AV_OPT_FLAG_DECODING_PARAM }
Definition at line 164 of file mpegts.c.
PES_START_SIZE
#define PES_START_SIZE 6
Definition at line 219 of file mpegts.c.
Referenced by mpegts_push_data(), and new_pes_packet().
PES_HEADER_SIZE
#define PES_HEADER_SIZE 9
Definition at line 220 of file mpegts.c.
Referenced by mpegts_push_data().
MAX_PES_HEADER_SIZE
#define MAX_PES_HEADER_SIZE (9 + 255)
Definition at line 221 of file mpegts.c.
MAX_LEVEL
#define MAX_LEVEL 4
Definition at line 1300 of file mpegts.c.
Referenced by parse_mp4_descr().
R8_CHECK_CLIP_MAX
#define R8_CHECK_CLIP_MAX (dst, maxv)
Value:
do {                       \
    descr->sl.dst = avio_r8(&d->pb);                            \
    if (descr->sl.dst > maxv) {                                 \
        descr->sl.dst = maxv;                                   \
        return AVERROR_INVALIDDATA;                             \
    }                                                           \
} while (0)
Referenced by parse_MP4SLDescrTag().
CHECK_COUNT
#define CHECK_COUNT 10
Referenced by mpegts_probe().
CHECK_BLOCK
#define CHECK_BLOCK 100
Referenced by mpegts_probe().
MAX_PACKET_READAHEAD
#define MAX_PACKET_READAHEAD ((128 * 1024) / 188)
Definition at line 2716 of file mpegts.c.
Referenced by mpegts_raw_read_packet().
Typedef Documentation
PESCallback
typedef int PESCallback(MpegTSFilter *f, const uint8_t *buf, int len, int is_start, int64_t pos)
Definition at line 64 of file mpegts.c.
SectionCallback
typedef void SectionCallback(MpegTSFilter *f, const uint8_t *buf, int len)
Definition at line 72 of file mpegts.c.
SetServiceCallback
typedef void SetServiceCallback(void *opaque, int ret)
Definition at line 74 of file mpegts.c.
Enumeration Type Documentation
MpegTSFilterType
enum MpegTSFilterType
Enumerator
MPEGTS_PES
MPEGTS_SECTION
MPEGTS_PCR
Definition at line 56 of file mpegts.c.
MpegTSState
enum MpegTSState
Enumerator
MPEGTS_HEADER
MPEGTS_PESHEADER
MPEGTS_PESHEADER_FILL
MPEGTS_PAYLOAD
MPEGTS_SKIP
Definition at line 210 of file mpegts.c.
Function Documentation
get_program()
static struct Program* get_program (MpegTSContext * ts, unsigned int programid) static
Definition at line 248 of file mpegts.c.
Referenced by add_pid_to_pmt(), and set_pmt_found().
clear_avprogram()
static void clear_avprogram (MpegTSContext * ts, unsigned int programid) static
Definition at line 259 of file mpegts.c.
Referenced by clear_program(), and pat_cb().
clear_program()
static void clear_program (MpegTSContext * ts, unsigned int programid) static
Definition at line 274 of file mpegts.c.
Referenced by pmt_cb().
clear_programs()
static void clear_programs (MpegTSContext * ts) static
Definition at line 286 of file mpegts.c.
Referenced by mpegts_free(), and pat_cb().
add_pat_entry()
static void add_pat_entry (MpegTSContext * ts, unsigned int programid) static
Definition at line 292 of file mpegts.c.
Referenced by pat_cb().
add_pid_to_pmt()
static void add_pid_to_pmt (MpegTSContext * ts, unsigned int programid, unsigned int pid) static
Definition at line 306 of file mpegts.c.
Referenced by pat_cb(), and pmt_cb().
set_pmt_found()
static void set_pmt_found (MpegTSContext * ts, unsigned int programid) static
Definition at line 324 of file mpegts.c.
Referenced by pmt_cb().
set_pcr_pid()
static void set_pcr_pid (AVFormatContext * s, unsigned int programid, unsigned int pid) static
Definition at line 333 of file mpegts.c.
Referenced by pmt_cb().
discard_pid()
static int discard_pid (MpegTSContext * ts, unsigned int pid) static
discard_pid() decides if the pid is to be discarded according to caller's programs selection
Parameters
ts : - TS context
pid : - pid
Returns
1 if the pid is only comprised in programs that have .discard=AVDISCARD_ALL 0 otherwise
Definition at line 352 of file mpegts.c.
Referenced by handle_packet().
write_section_data()
static void write_section_data (MpegTSContext * ts, MpegTSFilter * tss1, const uint8_t * buf, int buf_size, int is_start) static
Assemble PES packets out of TS packets, and then call the "section_cb" function when they are complete.
Definition at line 390 of file mpegts.c.
Referenced by handle_packet().
mpegts_open_filter()
static MpegTSFilter* mpegts_open_filter (MpegTSContext * ts, unsigned int pid, enum MpegTSFilterType type) static
Definition at line 444 of file mpegts.c.
Referenced by mpegts_open_pcr_filter(), mpegts_open_pes_filter(), and mpegts_open_section_filter().
mpegts_open_section_filter()
static MpegTSFilter* mpegts_open_section_filter (MpegTSContext * ts, unsigned int pid, SectionCallback * section_cb, void * opaque, int check_crc) static
Definition at line 467 of file mpegts.c.
Referenced by avpriv_mpegts_parse_open(), ff_parse_mpeg2_descriptor(), mpegts_read_header(), pat_cb(), and pmt_cb().
mpegts_open_pes_filter()
static MpegTSFilter* mpegts_open_pes_filter (MpegTSContext * ts, unsigned int pid, PESCallback * pes_cb, void * opaque) static
Definition at line 492 of file mpegts.c.
Referenced by add_pes_stream().
mpegts_open_pcr_filter()
static MpegTSFilter* mpegts_open_pcr_filter (MpegTSContext * ts, unsigned int pid) static
Definition at line 508 of file mpegts.c.
Referenced by pmt_cb().
mpegts_close_filter()
static void mpegts_close_filter (MpegTSContext * ts, MpegTSFilter * filter) static
Definition at line 513 of file mpegts.c.
Referenced by mpegts_free(), pat_cb(), and pmt_cb().
analyze()
static int analyze (const uint8_t * buf, int size, int packet_size, int probe) static
Definition at line 534 of file mpegts.c.
Referenced by get_packet_size(), and mpegts_probe().
get_packet_size()
static int get_packet_size (const uint8_t * buf, int size) static
Definition at line 563 of file mpegts.c.
Referenced by mpegts_read_header().
skip_identical()
static int skip_identical (const SectionHeader * h, MpegTSSectionFilter * tssf) static
Definition at line 594 of file mpegts.c.
Referenced by m4sl_cb(), pat_cb(), pmt_cb(), and sdt_cb().
get8()
static int get8 (const uint8_t ** pp, const uint8_t * p_end) inline static
Definition at line 605 of file mpegts.c.
Referenced by ff_parse_mpeg2_descriptor(), getstr8(), parse_section_header(), pmt_cb(), and sdt_cb().
get16()
static int get16 (const uint8_t ** pp, const uint8_t * p_end) inline static
Definition at line 618 of file mpegts.c.
Referenced by ff_parse_mpeg2_descriptor(), parse_section_header(), pat_cb(), pmt_cb(), and sdt_cb().
getstr8()
static char* getstr8 (const uint8_t ** pp, const uint8_t * p_end) static
Definition at line 633 of file mpegts.c.
Referenced by sdt_cb().
parse_section_header()
static int parse_section_header (SectionHeader * h, const uint8_t ** pp, const uint8_t * p_end) static
Definition at line 655 of file mpegts.c.
Referenced by m4sl_cb(), pat_cb(), pmt_cb(), and sdt_cb().
mpegts_find_stream_type()
static void mpegts_find_stream_type (AVStream * st, uint32_t stream_type, const StreamType * types) static
Definition at line 773 of file mpegts.c.
Referenced by ff_parse_mpeg2_descriptor(), mpegts_set_stream_info(), and pmt_cb().
mpegts_set_stream_info()
static int mpegts_set_stream_info (AVStream * st, PESContext * pes, uint32_t stream_type, uint32_t prog_reg_desc) static
Definition at line 790 of file mpegts.c.
Referenced by mpegts_push_data(), and pmt_cb().
reset_pes_packet_state()
static void reset_pes_packet_state (PESContext * pes) static
Definition at line 872 of file mpegts.c.
Referenced by mpegts_push_data(), and new_pes_packet().
new_data_packet()
static void new_data_packet (const uint8_t * buffer, int len, AVPacket * pkt) static
Definition at line 881 of file mpegts.c.
Referenced by scte_data_cb().
new_pes_packet()
static int new_pes_packet (PESContext * pes, AVPacket * pkt) static
Definition at line 888 of file mpegts.c.
Referenced by mpegts_push_data(), and mpegts_read_packet().
get_ts64()
static uint64_t get_ts64 (GetBitContext * gb, int bits) static
Definition at line 928 of file mpegts.c.
Referenced by read_sl_header().
read_sl_header()
static int read_sl_header (PESContext * pes, SLConfigDescr * sl, const uint8_t * buf, int buf_size) static
Definition at line 935 of file mpegts.c.
Referenced by mpegts_push_data().
mpegts_push_data()
static int mpegts_push_data (MpegTSFilter * filter, const uint8_t * buf, int buf_size, int is_start, int64_t pos) static
Definition at line 1007 of file mpegts.c.
Referenced by add_pes_stream().
add_pes_stream()
static PESContext* add_pes_stream (MpegTSContext * ts, int pid, int pcr_pid) static
Definition at line 1276 of file mpegts.c.
Referenced by handle_packet(), and pmt_cb().
init_MP4DescrParseContext()
static int init_MP4DescrParseContext (MP4DescrParseContext * d, AVFormatContext * s, const uint8_t * buf, unsigned size, Mp4Descr * descr, int max_descr_count) static
Definition at line 1312 of file mpegts.c.
Referenced by mp4_read_iods(), and mp4_read_od().
update_offsets()
static void update_offsets (AVIOContext * pb, int64_t * off, int * len) static
Definition at line 1334 of file mpegts.c.
Referenced by parse_mp4_descr(), parse_mp4_descr_arr(), parse_MP4ESDescrTag(), parse_MP4IODescrTag(), and parse_MP4ODescrTag().
parse_mp4_descr()
static int parse_mp4_descr (MP4DescrParseContext * d, int64_t off, int len, int target_tag) static
Definition at line 1458 of file mpegts.c.
Referenced by mp4_read_iods(), parse_mp4_descr_arr(), parse_MP4ESDescrTag(), and update_offsets().
parse_mp4_descr_arr()
static int parse_mp4_descr_arr (MP4DescrParseContext * d, int64_t off, int len) static
Definition at line 1344 of file mpegts.c.
Referenced by mp4_read_od(), parse_MP4IODescrTag(), and parse_MP4ODescrTag().
parse_MP4IODescrTag()
static int parse_MP4IODescrTag (MP4DescrParseContext * d, int64_t off, int len) static
Definition at line 1355 of file mpegts.c.
Referenced by parse_mp4_descr().
parse_MP4ODescrTag()
static int parse_MP4ODescrTag (MP4DescrParseContext * d, int64_t off, int len) static
Definition at line 1367 of file mpegts.c.
Referenced by parse_mp4_descr().
parse_MP4ESDescrTag()
static int parse_MP4ESDescrTag (MP4DescrParseContext * d, int64_t off, int len) static
Definition at line 1381 of file mpegts.c.
Referenced by parse_mp4_descr().
parse_MP4DecConfigDescrTag()
static int parse_MP4DecConfigDescrTag (MP4DescrParseContext * d, int64_t off, int len) static
Definition at line 1402 of file mpegts.c.
Referenced by parse_mp4_descr().
parse_MP4SLDescrTag()
static int parse_MP4SLDescrTag (MP4DescrParseContext * d, int64_t off, int len) static
Definition at line 1416 of file mpegts.c.
Referenced by parse_mp4_descr().
mp4_read_iods()
static int mp4_read_iods (AVFormatContext * s, const uint8_t * buf, unsigned size, Mp4Descr * descr, int * descr_count, int max_descr_count) static
Definition at line 1511 of file mpegts.c.
Referenced by pmt_cb().
mp4_read_od()
static int mp4_read_od (AVFormatContext * s, const uint8_t * buf, unsigned size, Mp4Descr * descr, int * descr_count, int max_descr_count) static
Definition at line 1527 of file mpegts.c.
Referenced by m4sl_cb().
m4sl_cb()
static void m4sl_cb (MpegTSFilter * filter, const uint8_t * section, int section_len) static
Definition at line 1543 of file mpegts.c.
Referenced by ff_parse_mpeg2_descriptor().
scte_data_cb()
static void scte_data_cb (MpegTSFilter * filter, const uint8_t * section, int section_len) static
Definition at line 1606 of file mpegts.c.
Referenced by pmt_cb().
ff_parse_mpeg2_descriptor()
int ff_parse_mpeg2_descriptor (AVFormatContext * fc, AVStream * st, int stream_type, const uint8_t ** pp, const uint8_t * desc_list_end, Mp4Descr * mp4_descr, int mp4_descr_count, int pid, MpegTSContext * ts)
Parse an MPEG-2 descriptor.
Parameters
[in] fc Format context (used for logging only)
st Stream
stream_type STREAM_TYPE_xxx
pp Descriptor buffer pointer
desc_list_end End of buffer
Returns
<0 to stop processing
Definition at line 1647 of file mpegts.c.
Referenced by parse_chunks(), and pmt_cb().
is_pes_stream()
static int is_pes_stream (int stream_type, uint32_t prog_reg_desc) static
Definition at line 1906 of file mpegts.c.
Referenced by pmt_cb().
pmt_cb()
static void pmt_cb (MpegTSFilter * filter, const uint8_t * section, int section_len) static
Definition at line 1912 of file mpegts.c.
Referenced by pat_cb().
pat_cb()
static void pat_cb (MpegTSFilter * filter, const uint8_t * section, int section_len) static
Definition at line 2087 of file mpegts.c.
Referenced by avpriv_mpegts_parse_open(), and mpegts_read_header().
sdt_cb()
static void sdt_cb (MpegTSFilter * filter, const uint8_t * section, int section_len) static
Definition at line 2162 of file mpegts.c.
Referenced by avpriv_mpegts_parse_open(), and mpegts_read_header().
parse_pcr()
static int parse_pcr (int64_t * ppcr_high, int * ppcr_low, const uint8_t * packet) static
Definition at line 2576 of file mpegts.c.
Referenced by handle_packet(), mpegts_get_pcr(), mpegts_raw_read_packet(), mpegts_read_header(), and sdt_cb().
handle_packet()
static int handle_packet (MpegTSContext * ts, const uint8_t * packet) static
Definition at line 2250 of file mpegts.c.
Referenced by avpriv_mpegts_parse_packet(), and handle_packets().
reanalyze()
static void reanalyze (MpegTSContext * ts) static
Definition at line 2380 of file mpegts.c.
Referenced by mpegts_resync().
mpegts_resync()
static int mpegts_resync (AVFormatContext * s, int seekback, const uint8_t * current_packet) static
Definition at line 2415 of file mpegts.c.
Referenced by mpegts_get_pcr(), and read_packet().
read_packet()
static int read_packet (AVFormatContext * s, uint8_t * buf, int raw_packet_size, const uint8_t ** data) static
Definition at line 2447 of file mpegts.c.
Referenced by handle_packets(), mpegts_raw_read_packet(), and mpegts_read_header().
finished_reading_packet()
static void finished_reading_packet (AVFormatContext * s, int raw_packet_size) static
Definition at line 2472 of file mpegts.c.
Referenced by handle_packets(), mpegts_raw_read_packet(), and mpegts_read_header().
handle_packets()
static int handle_packets (MpegTSContext * ts, int64_t nb_packets) static
Definition at line 2480 of file mpegts.c.
Referenced by mpegts_read_header(), and mpegts_read_packet().
mpegts_probe()
static int mpegts_probe (AVProbeData * p) static
Definition at line 2533 of file mpegts.c.
seek_back()
static void seek_back (AVFormatContext * s, AVIOContext * pb, int64_t pos) static
Definition at line 2602 of file mpegts.c.
Referenced by mpegts_read_header().
mpegts_read_header()
static int mpegts_read_header (AVFormatContext * s) static
Definition at line 2611 of file mpegts.c.
mpegts_raw_read_packet()
static int mpegts_raw_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 2718 of file mpegts.c.
mpegts_read_packet()
static int mpegts_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 2766 of file mpegts.c.
mpegts_free()
static void mpegts_free (MpegTSContext * ts) static
Definition at line 2796 of file mpegts.c.
Referenced by avpriv_mpegts_parse_close(), and mpegts_read_close().
mpegts_read_close()
static int mpegts_read_close (AVFormatContext * s) static
Definition at line 2807 of file mpegts.c.
mpegts_get_pcr()
static av_unused int64_t mpegts_get_pcr (AVFormatContext * s, int stream_index, int64_t * ppos, int64_t pos_limit) static
Definition at line 2814 of file mpegts.c.
mpegts_get_dts()
static int64_t mpegts_get_dts (AVFormatContext * s, int stream_index, int64_t * ppos, int64_t pos_limit) static
Definition at line 2848 of file mpegts.c.
avpriv_mpegts_parse_open()
MpegTSContext* avpriv_mpegts_parse_open (AVFormatContext * s)
Definition at line 2885 of file mpegts.c.
Referenced by get_sockaddr(), iec61883_read_header(), and mpegts_init().
avpriv_mpegts_parse_packet()
int avpriv_mpegts_parse_packet (MpegTSContext * ts, AVPacket * pkt, const uint8_t * buf, int len)
Definition at line 2904 of file mpegts.c.
Referenced by ff_rtsp_open_transport_ctx(), iec61883_parse_queue_hdv(), and mpegts_handle_packet().
avpriv_mpegts_parse_close()
void avpriv_mpegts_parse_close (MpegTSContext * ts)
Definition at line 2929 of file mpegts.c.
Referenced by ff_rtsp_close_streams(), iec61883_close(), and mpegts_close_context().
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    MPEGTS_OPTIONS,
    {"fix_teletext_pts", "try to fix pts values of dvb teletext streams", 0x42, AV_OPT_TYPE_BOOL,
     {.i64 = 1}, 0, 1, AV_OPT_FLAG_DECODING_PARAM },
    {"ts_packetsize", "output option carrying the raw packet size", 0x42, AV_OPT_TYPE_INT,
     {.i64 = 0}, 0, 0, AV_OPT_FLAG_DECODING_PARAM | AV_OPT_FLAG_EXPORT | AV_OPT_FLAG_READONLY },
    {"scan_all_pmts",   "scan and combine all PMTs", 0x42, AV_OPT_TYPE_BOOL,
     { .i64 =  -1}, -1, 1,  AV_OPT_FLAG_DECODING_PARAM },
    {"skip_changes", "skip changing / adding streams / programs", 0x42, AV_OPT_TYPE_BOOL,
     {.i64 = 0}, 0, 1, 0 },
    {"skip_clear", "skip clearing programs", 0x42, AV_OPT_TYPE_BOOL,
     {.i64 = 0}, 0, 1, 0 },
    { NULL },
}
Definition at line 167 of file mpegts.c.
mpegts_class
const AVClass mpegts_class static
Initial value:
= {
    .class_name = "mpegts demuxer",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 182 of file mpegts.c.
raw_options
const AVOption raw_options[] static
Initial value:
= {
    MPEGTS_OPTIONS,
    { "compute_pcr",   "compute exact PCR for each transport stream packet",
          0x42, AV_OPT_TYPE_BOOL,
          { .i64 = 0 }, 0, 1,  AV_OPT_FLAG_DECODING_PARAM },
    { "ts_packetsize", "output option carrying the raw packet size",
      0x42, AV_OPT_TYPE_INT,
      { .i64 = 0 }, 0, 0,
      AV_OPT_FLAG_DECODING_PARAM | AV_OPT_FLAG_EXPORT | AV_OPT_FLAG_READONLY },
    { NULL },
}
Definition at line 189 of file mpegts.c.
mpegtsraw_class
const AVClass mpegtsraw_class static
Initial value:
= {
    .class_name = "mpegtsraw demuxer",
    .item_name  = av_default_item_name,
    .option     = raw_options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 201 of file mpegts.c.
ff_mpegts_demuxer
AVInputFormat ff_mpegts_demuxer
Initial value:
= {
    .name           = "mpegts",
    .long_name      = NULL_IF_CONFIG_SMALL("MPEG-TS (MPEG-2 Transport Stream)"),
    .priv_data_size = sizeof(MpegTSContext),
    .read_probe     = mpegts_probe,
    .read_header    = mpegts_read_header,
    .read_packet    = mpegts_read_packet,
    .read_close     = mpegts_read_close,
    .read_timestamp = mpegts_get_dts,
    .flags          = AVFMT_SHOW_IDS | AVFMT_TS_DISCONT,
    .priv_class     = &mpegts_class,
}
Definition at line 2935 of file mpegts.c.
ISO_types
const StreamType ISO_types[] static
Initial value:
= {
    { 0x01, AVMEDIA_TYPE_VIDEO, AV_CODEC_ID_MPEG2VIDEO },
    { 0x02, AVMEDIA_TYPE_VIDEO, AV_CODEC_ID_MPEG2VIDEO },
    { 0x03, AVMEDIA_TYPE_AUDIO, AV_CODEC_ID_MP3        },
    { 0x04, AVMEDIA_TYPE_AUDIO, AV_CODEC_ID_MP3        },
    { 0x0f, AVMEDIA_TYPE_AUDIO, AV_CODEC_ID_AAC        },
    { 0x10, AVMEDIA_TYPE_VIDEO, AV_CODEC_ID_MPEG4      },
    { 0x11, AVMEDIA_TYPE_AUDIO, AV_CODEC_ID_AAC_LATM   },
    { 0x1b, AVMEDIA_TYPE_VIDEO, AV_CODEC_ID_H264       },
    { 0x1c, AVMEDIA_TYPE_AUDIO, AV_CODEC_ID_AAC        },
    { 0x20, AVMEDIA_TYPE_VIDEO, AV_CODEC_ID_H264       },
    { 0x21, AVMEDIA_TYPE_VIDEO, AV_CODEC_ID_JPEG2000   },
    { 0x24, AVMEDIA_TYPE_VIDEO, AV_CODEC_ID_HEVC       },
    { 0x42, AVMEDIA_TYPE_VIDEO, AV_CODEC_ID_CAVS       },
    { 0xd1, AVMEDIA_TYPE_VIDEO, AV_CODEC_ID_DIRAC      },
    { 0xea, AVMEDIA_TYPE_VIDEO, AV_CODEC_ID_VC1        },
    { 0 },
}
Definition at line 690 of file mpegts.c.
HDMV_types
const StreamType HDMV_types[] static
Initial value:
= {
    { 0x80, AVMEDIA_TYPE_AUDIO,    AV_CODEC_ID_PCM_BLURAY        },
    { 0x81, AVMEDIA_TYPE_AUDIO,    AV_CODEC_ID_AC3               },
    { 0x82, AVMEDIA_TYPE_AUDIO,    AV_CODEC_ID_DTS               },
    { 0x83, AVMEDIA_TYPE_AUDIO,    AV_CODEC_ID_TRUEHD            },
    { 0x84, AVMEDIA_TYPE_AUDIO,    AV_CODEC_ID_EAC3              },
    { 0x85, AVMEDIA_TYPE_AUDIO,    AV_CODEC_ID_DTS               },
    { 0x86, AVMEDIA_TYPE_AUDIO,    AV_CODEC_ID_DTS               },
    { 0xa1, AVMEDIA_TYPE_AUDIO,    AV_CODEC_ID_EAC3              },
    { 0xa2, AVMEDIA_TYPE_AUDIO,    AV_CODEC_ID_DTS               },
    { 0x90, AVMEDIA_TYPE_SUBTITLE, AV_CODEC_ID_HDMV_PGS_SUBTITLE },
    { 0x92, AVMEDIA_TYPE_SUBTITLE, AV_CODEC_ID_HDMV_TEXT_SUBTITLE },
    { 0 },
}
Definition at line 713 of file mpegts.c.
SCTE_types
const StreamType SCTE_types[] static
Initial value:
= {
    { 0x86, AVMEDIA_TYPE_DATA,  AV_CODEC_ID_SCTE_35    },
    { 0 },
}
Definition at line 729 of file mpegts.c.
MISC_types
const StreamType MISC_types[] static
Initial value:
= {
    { 0x81, AVMEDIA_TYPE_AUDIO, AV_CODEC_ID_AC3 },
    { 0x8a, AVMEDIA_TYPE_AUDIO, AV_CODEC_ID_DTS },
    { 0 },
}
Definition at line 735 of file mpegts.c.
REGD_types
const StreamType REGD_types[] static
Initial value:
= {
    { MKTAG('d', 'r', 'a', 'c'), AVMEDIA_TYPE_VIDEO, AV_CODEC_ID_DIRAC },
    { MKTAG('A', 'C', '-', '3'), AVMEDIA_TYPE_AUDIO, AV_CODEC_ID_AC3   },
    { MKTAG('B', 'S', 'S', 'D'), AVMEDIA_TYPE_AUDIO, AV_CODEC_ID_S302M },
    { MKTAG('D', 'T', 'S', '1'), AVMEDIA_TYPE_AUDIO, AV_CODEC_ID_DTS   },
    { MKTAG('D', 'T', 'S', '2'), AVMEDIA_TYPE_AUDIO, AV_CODEC_ID_DTS   },
    { MKTAG('D', 'T', 'S', '3'), AVMEDIA_TYPE_AUDIO, AV_CODEC_ID_DTS   },
    { MKTAG('E', 'A', 'C', '3'), AVMEDIA_TYPE_AUDIO, AV_CODEC_ID_EAC3  },
    { MKTAG('H', 'E', 'V', 'C'), AVMEDIA_TYPE_VIDEO, AV_CODEC_ID_HEVC  },
    { MKTAG('K', 'L', 'V', 'A'), AVMEDIA_TYPE_DATA,  AV_CODEC_ID_SMPTE_KLV },
    { MKTAG('I', 'D', '3', ' '), AVMEDIA_TYPE_DATA,  AV_CODEC_ID_TIMED_ID3 },
    { MKTAG('V', 'C', '-', '1'), AVMEDIA_TYPE_VIDEO, AV_CODEC_ID_VC1   },
    { MKTAG('O', 'p', 'u', 's'), AVMEDIA_TYPE_AUDIO, AV_CODEC_ID_OPUS  },
    { 0 },
}
Definition at line 741 of file mpegts.c.
METADATA_types
const StreamType METADATA_types[] static
Initial value:
= {
    { MKTAG('K','L','V','A'), AVMEDIA_TYPE_DATA, AV_CODEC_ID_SMPTE_KLV },
    { MKTAG('I','D','3',' '), AVMEDIA_TYPE_DATA, AV_CODEC_ID_TIMED_ID3 },
    { 0 },
}
Definition at line 757 of file mpegts.c.
DESC_types
const StreamType DESC_types[] static
Initial value:
= {
    { 0x6a, AVMEDIA_TYPE_AUDIO,    AV_CODEC_ID_AC3          },
    { 0x7a, AVMEDIA_TYPE_AUDIO,    AV_CODEC_ID_EAC3         },
    { 0x7b, AVMEDIA_TYPE_AUDIO,    AV_CODEC_ID_DTS          },
    { 0x56, AVMEDIA_TYPE_SUBTITLE, AV_CODEC_ID_DVB_TELETEXT },
    { 0x59, AVMEDIA_TYPE_SUBTITLE, AV_CODEC_ID_DVB_SUBTITLE },
    { 0 },
}
Definition at line 764 of file mpegts.c.
opus_coupled_stream_cnt
const uint8_t opus_coupled_stream_cnt[9] static
Initial value:
= {
    1, 0, 1, 1, 2, 2, 2, 3, 3
}
Definition at line 1628 of file mpegts.c.
Referenced by ff_parse_mpeg2_descriptor().
opus_stream_cnt
const uint8_t opus_stream_cnt[9] static
Initial value:
= {
    1, 1, 1, 2, 2, 3, 4, 4, 5,
}
Definition at line 1632 of file mpegts.c.
Referenced by ff_parse_mpeg2_descriptor().
opus_channel_map
const uint8_t opus_channel_map[8][8] static
Initial value:
= {
    { 0 },
    { 0,1 },
    { 0,2,1 },
    { 0,1,2,3 },
    { 0,4,1,2,3 },
    { 0,4,1,2,3,5 },
    { 0,4,1,2,3,5,6 },
    { 0,6,1,2,3,4,5,7 },
}
Definition at line 1636 of file mpegts.c.
Referenced by ff_parse_mpeg2_descriptor().
ff_mpegtsraw_demuxer
AVInputFormat ff_mpegtsraw_demuxer
Initial value:
= {
    .name           = "mpegtsraw",
    .long_name      = NULL_IF_CONFIG_SMALL("raw MPEG-TS (MPEG-2 Transport Stream)"),
    .priv_data_size = sizeof(MpegTSContext),
    .read_header    = mpegts_read_header,
    .read_packet    = mpegts_raw_read_packet,
    .read_close     = mpegts_read_close,
    .read_timestamp = mpegts_get_dts,
    .flags          = AVFMT_SHOW_IDS | AVFMT_TS_DISCONT,
    .priv_class     = &mpegtsraw_class,
}
Definition at line 2948 of file mpegts.c.