FFmpeg: libavcodec/mpegvideo_enc.c File Reference
mpegvideo_enc.c File Reference
The simplest mpeg encoder (well, it was the simplest!).
#include <stdint.h>
#include "libavutil/internal.h"
#include "libavutil/intmath.h"
#include "libavutil/mathematics.h"
#include "libavutil/pixdesc.h"
#include "libavutil/opt.h"
#include "libavutil/timer.h"
#include "avcodec.h"
#include "dct.h"
#include "idctdsp.h"
#include "mpeg12.h"
#include "mpegvideo.h"
#include "mpegvideodata.h"
#include "h261.h"
#include "h263.h"
#include "h263data.h"
#include "mjpegenc_common.h"
#include "mathops.h"
#include "mpegutils.h"
#include "mjpegenc.h"
#include "msmpeg4.h"
#include "pixblockdsp.h"
#include "qpeldsp.h"
#include "faandct.h"
#include "thread.h"
#include "aandcttab.h"
#include "flv.h"
#include "mpeg4video.h"
#include "internal.h"
#include "bytestream.h"
#include "wmv2.h"
#include "rv10.h"
#include <limits.h>
#include "sp5x.h"
Macros
#define QUANT_BIAS_SHIFT 8
#define QMAT_SHIFT_MMX 16
#define QMAT_SHIFT 21
#define COPY(a) dst->a= src->a
#define MERGE(field) dst->field += src->field; src->field=0
#define OFFSET(x) offsetof(MpegEncContext, x)
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Functions
static int encode_picture (MpegEncContext *s, int picture_number)
static int dct_quantize_refine (MpegEncContext *s, int16_t *block, int16_t *weight, int16_t *orig, int n, int qscale)
static int sse_mb (MpegEncContext *s)
static void denoise_dct_c (MpegEncContext *s, int16_t *block)
static int dct_quantize_trellis_c (MpegEncContext *s, int16_t *block, int n, int qscale, int *overflow)
void ff_convert_matrix (MpegEncContext *s, int(*qmat)[64], uint16_t(*qmat16)[2][64], const uint16_t *quant_matrix, int bias, int qmin, int qmax, int intra)
static void update_qscale (MpegEncContext *s)
void ff_write_quant_matrix (PutBitContext *pb, uint16_t *matrix)
void ff_init_qscale_tab (MpegEncContext *s)
init s->current_picture.qscale_table from s->lambda_table
static void update_duplicate_context_after_me (MpegEncContext *dst, MpegEncContext *src)
static void mpv_encode_defaults (MpegEncContext *s)
Set the given MpegEncContext to defaults for encoding.
av_cold int ff_dct_encode_init (MpegEncContext *s)
av_cold int ff_mpv_encode_init (AVCodecContext *avctx)
av_cold int ff_mpv_encode_end (AVCodecContext *avctx)
static int get_sae (uint8_t *src, int ref, int stride)
static int get_intra_count (MpegEncContext *s, uint8_t *src, uint8_t *ref, int stride)
static int alloc_picture (MpegEncContext *s, Picture *pic, int shared)
static int load_input_picture (MpegEncContext *s, const AVFrame *pic_arg)
static int skip_check (MpegEncContext *s, Picture *p, Picture *ref)
static int encode_frame (AVCodecContext *c, AVFrame *frame)
static int estimate_best_b_count (MpegEncContext *s)
static int select_input_picture (MpegEncContext *s)
static void frame_end (MpegEncContext *s)
static void update_noise_reduction (MpegEncContext *s)
static int frame_start (MpegEncContext *s)
int ff_mpv_encode_picture (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *pic_arg, int *got_packet)
static void dct_single_coeff_elimination (MpegEncContext *s, int n, int threshold)
static void clip_coeffs (MpegEncContext *s, int16_t *block, int last_index)
static void get_visual_weight (int16_t *weight, uint8_t *ptr, int stride)
static av_always_inline void encode_mb_internal (MpegEncContext *s, int motion_x, int motion_y, int mb_block_height, int mb_block_width, int mb_block_count)
static av_always_inline void encode_mb (MpegEncContext *s, int motion_x, int motion_y)
static void copy_context_before_encode (MpegEncContext *d, MpegEncContext *s, int type)
static void copy_context_after_encode (MpegEncContext *d, MpegEncContext *s, int type)
static void encode_mb_hq (MpegEncContext *s, MpegEncContext *backup, MpegEncContext *best, int type, PutBitContext pb[2], PutBitContext pb2[2], PutBitContext tex_pb[2], int *dmin, int *next_block, int motion_x, int motion_y)
static int sse (MpegEncContext *s, uint8_t *src1, uint8_t *src2, int w, int h, int stride)
static int pre_estimate_motion_thread (AVCodecContext *c, void *arg)
static int estimate_motion_thread (AVCodecContext *c, void *arg)
static int mb_var_thread (AVCodecContext *c, void *arg)
static void write_slice_end (MpegEncContext *s)
static void write_mb_info (MpegEncContext *s)
static void update_mb_info (MpegEncContext *s, int startcode)
int ff_mpv_reallocate_putbitbuffer (MpegEncContext *s, size_t threshold, size_t size_increase)
static int encode_thread (AVCodecContext *c, void *arg)
static void merge_context_after_me (MpegEncContext *dst, MpegEncContext *src)
static void merge_context_after_encode (MpegEncContext *dst, MpegEncContext *src)
static int estimate_qp (MpegEncContext *s, int dry_run)
static void set_frame_distances (MpegEncContext *s)
static void build_basis (uint8_t *perm)
void ff_block_permute (int16_t *block, uint8_t *permutation, const uint8_t *scantable, int last)
Permute an 8x8 block according to permutation.
int ff_dct_quantize_c (MpegEncContext *s, int16_t *block, int n, int qscale, int *overflow)
Variables
static uint8_t default_mv_penalty [MAX_FCODE+1][MAX_DMV *2+1]
static uint8_t default_fcode_tab [MAX_MV *2+1]
const AVOption ff_mpv_generic_options []
static int16_t basis [64][64]
static const AVOption h263_options []
static const AVClass h263_class
AVCodec ff_h263_encoder
static const AVOption h263p_options []
static const AVClass h263p_class
AVCodec ff_h263p_encoder
static const AVClass msmpeg4v2_class
AVCodec ff_msmpeg4v2_encoder
static const AVClass msmpeg4v3_class
AVCodec ff_msmpeg4v3_encoder
static const AVClass wmv1_class
AVCodec ff_wmv1_encoder
Detailed Description
The simplest mpeg encoder (well, it was the simplest!).
Definition in file mpegvideo_enc.c.
Macro Definition Documentation
QUANT_BIAS_SHIFT
#define QUANT_BIAS_SHIFT 8
Definition at line 70 of file mpegvideo_enc.c.
Referenced by ff_convert_matrix(), ff_dct_quantize_c(), and ff_mpv_encode_init().
QMAT_SHIFT_MMX
#define QMAT_SHIFT_MMX 16
Definition at line 72 of file mpegvideo_enc.c.
Referenced by ff_convert_matrix().
QMAT_SHIFT
#define QMAT_SHIFT 21
Definition at line 73 of file mpegvideo_enc.c.
Referenced by dct_quantize_trellis_c(), ff_convert_matrix(), and ff_dct_quantize_c().
COPY
#define COPY (a) dst->a= src->a
Referenced by update_duplicate_context_after_me().
MERGE
#define MERGE (field) dst->field += src->field; src->field=0
Definition at line 3587 of file mpegvideo_enc.c.
Referenced by merge_context_after_encode(), and merge_context_after_me().
OFFSET
#define OFFSET (x) offsetof(MpegEncContext, x)
Definition at line 4804 of file mpegvideo_enc.c.
VE
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 4805 of file mpegvideo_enc.c.
Function Documentation
encode_picture()
static int encode_picture (MpegEncContext * s, int picture_number) static
Definition at line 3677 of file mpegvideo_enc.c.
Referenced by ff_mpv_encode_picture().
dct_quantize_refine()
static int dct_quantize_refine (MpegEncContext * s, int16_t * block, int16_t * weight, int16_t * orig, int n, int qscale) static
Definition at line 4307 of file mpegvideo_enc.c.
Referenced by encode_mb_internal().
sse_mb()
static int sse_mb (MpegEncContext * s) static
Definition at line 2745 of file mpegvideo_enc.c.
Referenced by encode_mb_hq().
denoise_dct_c()
static void denoise_dct_c (MpegEncContext * s, int16_t * block) static
Definition at line 3952 of file mpegvideo_enc.c.
Referenced by ff_dct_encode_init().
dct_quantize_trellis_c()
static int dct_quantize_trellis_c (MpegEncContext * s, int16_t * block, int n, int qscale, int * overflow) static
Definition at line 3976 of file mpegvideo_enc.c.
Referenced by ff_dct_encode_init().
ff_convert_matrix()
void ff_convert_matrix (MpegEncContext * s, int(*) qmat[64], uint16_t(*) qmat16[2][64], const uint16_t * quant_matrix, int bias, int qmin, int qmax, int intra)
Definition at line 89 of file mpegvideo_enc.c.
Referenced by dnxhd_init_qmat(), encode_picture(), and ff_mpv_encode_init().
update_qscale()
static void update_qscale (MpegEncContext * s) inline static
Definition at line 173 of file mpegvideo_enc.c.
Referenced by encode_mb_internal(), encode_picture(), and estimate_qp().
ff_write_quant_matrix()
void ff_write_quant_matrix (PutBitContext * pb, uint16_t * matrix)
Definition at line 201 of file mpegvideo_enc.c.
Referenced by mpeg1_encode_sequence_header(), and mpeg4_encode_vol_header().
ff_init_qscale_tab()
void ff_init_qscale_tab (MpegEncContext * s)
init s->current_picture.qscale_table from s->lambda_table
Definition at line 217 of file mpegvideo_enc.c.
Referenced by estimate_qp(), and ff_clean_h263_qscales().
update_duplicate_context_after_me()
static void update_duplicate_context_after_me (MpegEncContext * dst, MpegEncContext * src) static
Definition at line 230 of file mpegvideo_enc.c.
Referenced by encode_picture().
mpv_encode_defaults()
static void mpv_encode_defaults (MpegEncContext * s) static
Set the given MpegEncContext to defaults for encoding.
the changed fields will not depend upon the prior state of the MpegEncContext.
Definition at line 253 of file mpegvideo_enc.c.
Referenced by ff_mpv_encode_init().
ff_dct_encode_init()
av_cold int ff_dct_encode_init (MpegEncContext * s)
Definition at line 268 of file mpegvideo_enc.c.
Referenced by dnxhd_encode_init(), and ff_mpv_encode_init().
ff_mpv_encode_init()
av_cold int ff_mpv_encode_init (AVCodecContext * avctx)
Definition at line 286 of file mpegvideo_enc.c.
Referenced by encode_init(), and wmv2_encode_init().
ff_mpv_encode_end()
av_cold int ff_mpv_encode_end (AVCodecContext * avctx)
Definition at line 1120 of file mpegvideo_enc.c.
Referenced by ff_mpv_encode_init(), and mpeg12_class().
get_sae()
static int get_sae (uint8_t * src, int ref, int stride) static
Definition at line 1158 of file mpegvideo_enc.c.
Referenced by get_intra_count().
get_intra_count()
static int get_intra_count (MpegEncContext * s, uint8_t * src, uint8_t * ref, int stride) static
Definition at line 1172 of file mpegvideo_enc.c.
Referenced by select_input_picture().
alloc_picture()
static int alloc_picture (MpegEncContext * s, Picture * pic, int shared) static
Definition at line 1195 of file mpegvideo_enc.c.
Referenced by load_input_picture(), and select_input_picture().
load_input_picture()
static int load_input_picture (MpegEncContext * s, const AVFrame * pic_arg) static
Definition at line 1203 of file mpegvideo_enc.c.
Referenced by ff_mpv_encode_picture().
skip_check()
static int skip_check (MpegEncContext * s, Picture * p, Picture * ref) static
Definition at line 1354 of file mpegvideo_enc.c.
Referenced by select_input_picture().
encode_frame()
static int encode_frame (AVCodecContext * c, AVFrame * frame) static
Definition at line 1395 of file mpegvideo_enc.c.
Referenced by estimate_best_b_count().
estimate_best_b_count()
static int estimate_best_b_count (MpegEncContext * s) static
Definition at line 1410 of file mpegvideo_enc.c.
Referenced by select_input_picture().
select_input_picture()
static int select_input_picture (MpegEncContext * s) static
Definition at line 1527 of file mpegvideo_enc.c.
Referenced by ff_mpv_encode_picture().
frame_end()
static void frame_end (MpegEncContext * s) static
Definition at line 1701 of file mpegvideo_enc.c.
Referenced by bethsoftvid_decode_frame(), bfi_decode_frame(), decode_bmv_frame(), decode_dds1(), decode_dsw1(), decode_tdlt(), decode_tsw1(), decode_wdlt(), ff_h263_decode_frame(), ff_mpv_encode_picture(), get_duration(), gif_read_packet(), and write_subframes().
update_noise_reduction()
static void update_noise_reduction (MpegEncContext * s) static
Definition at line 1751 of file mpegvideo_enc.c.
Referenced by frame_start().
frame_start()
static int frame_start (MpegEncContext * s) static
Definition at line 1772 of file mpegvideo_enc.c.
Referenced by av_timecode_init(), decode_dds1(), decode_dsw1(), decode_tsw1(), ff_mpv_encode_picture(), get_duration(), and gif_read_packet().
ff_mpv_encode_picture()
int ff_mpv_encode_picture (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * pic_arg, int * got_packet)
Definition at line 1844 of file mpegvideo_enc.c.
Referenced by amv_encode_picture(), and mpeg12_class().
dct_single_coeff_elimination()
static void dct_single_coeff_elimination (MpegEncContext * s, int n, int threshold) inline static
Definition at line 2105 of file mpegvideo_enc.c.
Referenced by encode_mb_internal().
clip_coeffs()
static void clip_coeffs (MpegEncContext * s, int16_t * block, int last_index) inline static
Definition at line 2161 of file mpegvideo_enc.c.
Referenced by encode_mb_internal().
get_visual_weight()
static void get_visual_weight (int16_t * weight, uint8_t * ptr, int stride) static
Definition at line 2195 of file mpegvideo_enc.c.
Referenced by encode_mb_internal().
encode_mb_internal()
static av_always_inline void encode_mb_internal (MpegEncContext * s, int motion_x, int motion_y, int mb_block_height, int mb_block_width, int mb_block_count) static
Definition at line 2219 of file mpegvideo_enc.c.
Referenced by encode_mb().
encode_mb()
static av_always_inline void encode_mb (MpegEncContext * s, int motion_x, int motion_y) static
Definition at line 2599 of file mpegvideo_enc.c.
Referenced by encode_mb_hq(), and encode_thread().
copy_context_before_encode()
static void copy_context_before_encode (MpegEncContext * d, MpegEncContext * s, int type) inline static
Definition at line 2606 of file mpegvideo_enc.c.
Referenced by encode_mb_hq(), and encode_thread().
copy_context_after_encode()
static void copy_context_after_encode (MpegEncContext * d, MpegEncContext * s, int type) inline static
Definition at line 2634 of file mpegvideo_enc.c.
Referenced by encode_mb_hq(), and encode_thread().
encode_mb_hq()
static void encode_mb_hq (MpegEncContext * s, MpegEncContext * backup, MpegEncContext * best, int type, PutBitContext pb[2], PutBitContext pb2[2], PutBitContext tex_pb[2], int * dmin, int * next_block, int motion_x, int motion_y) inline static
Definition at line 2673 of file mpegvideo_enc.c.
Referenced by encode_thread().
sse()
static int sse (MpegEncContext * s, uint8_t * src1, uint8_t * src2, int w, int h, int stride) static
Definition at line 2724 of file mpegvideo_enc.c.
Referenced by block_sse(), encode_thread(), ff_libwebp_get_frame(), ff_showcqt_init_x86(), ff_vp9dsp_init_16bpp_x86(), ff_vp9dsp_init_x86(), main(), run_psnr(), sse_16width_msa(), sse_4width_msa(), sse_8width_msa(), and sse_mb().
pre_estimate_motion_thread()
static int pre_estimate_motion_thread (AVCodecContext * c, void * arg) static
Definition at line 2768 of file mpegvideo_enc.c.
Referenced by encode_picture().
estimate_motion_thread()
static int estimate_motion_thread (AVCodecContext * c, void * arg) static
Definition at line 2787 of file mpegvideo_enc.c.
Referenced by encode_picture().
mb_var_thread()
static int mb_var_thread (AVCodecContext * c, void * arg) static
Definition at line 2814 of file mpegvideo_enc.c.
Referenced by encode_picture().
write_slice_end()
static void write_slice_end (MpegEncContext * s) static
Definition at line 2839 of file mpegvideo_enc.c.
Referenced by encode_thread().
write_mb_info()
static void write_mb_info (MpegEncContext * s) static
Definition at line 2857 of file mpegvideo_enc.c.
Referenced by update_mb_info().
update_mb_info()
static void update_mb_info (MpegEncContext * s, int startcode) static
Definition at line 2877 of file mpegvideo_enc.c.
Referenced by encode_thread().
ff_mpv_reallocate_putbitbuffer()
int ff_mpv_reallocate_putbitbuffer (MpegEncContext * s, size_t threshold, size_t size_increase)
Definition at line 2900 of file mpegvideo_enc.c.
Referenced by encode_thread(), and ff_mjpeg_encode_stuffing().
encode_thread()
static int encode_thread (AVCodecContext * c, void * arg) static
Definition at line 2936 of file mpegvideo_enc.c.
Referenced by encode_picture().
merge_context_after_me()
static void merge_context_after_me (MpegEncContext * dst, MpegEncContext * src) static
Definition at line 3588 of file mpegvideo_enc.c.
Referenced by encode_picture().
merge_context_after_encode()
static void merge_context_after_encode (MpegEncContext * dst, MpegEncContext * src) static
Definition at line 3594 of file mpegvideo_enc.c.
Referenced by encode_picture().
estimate_qp()
static int estimate_qp (MpegEncContext * s, int dry_run) static
Definition at line 3626 of file mpegvideo_enc.c.
Referenced by encode_picture().
set_frame_distances()
static void set_frame_distances (MpegEncContext * s) static
Definition at line 3663 of file mpegvideo_enc.c.
Referenced by encode_picture().
build_basis()
static void build_basis (uint8_t * perm) static
Definition at line 4288 of file mpegvideo_enc.c.
Referenced by dct_quantize_refine().
ff_block_permute()
void ff_block_permute (int16_t * block, uint8_t * permutation, const uint8_t * scantable, int last)
Permute an 8x8 block according to permutation.
Parameters
block the block which will be permuted according to the given permutation vector
permutation the permutation vector
last the last non zero coefficient in scantable order, used to speed the permutation up
scantable the used scantable, this is only used to speed the permutation up, the block is not (inverse) permutated to scantable order!
Definition at line 4698 of file mpegvideo_enc.c.
Referenced by dnxhd_10bit_dct_quantize(), and ff_dct_quantize_c().
ff_dct_quantize_c()
int ff_dct_quantize_c (MpegEncContext * s, int16_t * block, int n, int qscale, int * overflow)
Definition at line 4723 of file mpegvideo_enc.c.
Referenced by dnxhd_encode_init(), encode_mb_internal(), and ff_dct_encode_init().
Variable Documentation
default_mv_penalty
uint8_t default_mv_penalty[MAX_FCODE+1][MAX_DMV *2+1] static
Definition at line 81 of file mpegvideo_enc.c.
Referenced by mpv_encode_defaults().
default_fcode_tab
uint8_t default_fcode_tab[MAX_MV *2+1] static
Definition at line 82 of file mpegvideo_enc.c.
Referenced by mpv_encode_defaults().
ff_mpv_generic_options
const AVOption ff_mpv_generic_options[]
Initial value:
= {
    FF_MPV_COMMON_OPTS
    { NULL },
}
Definition at line 84 of file mpegvideo_enc.c.
basis
int16_t basis[64][64] static
Definition at line 4286 of file mpegvideo_enc.c.
Referenced by add_8x8basis(), and try_8x8basis().
h263_options
const AVOption h263_options[] static
Initial value:
= {
    { "obmc",         "use overlapped block motion compensation.", OFFSET(obmc), AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, VE },
    { "mb_info",      "emit macroblock info for RFC 2190 packetization, the parameter value is the maximum payload size", OFFSET(mb_info), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, INT_MAX, VE },
    FF_MPV_COMMON_OPTS
    { NULL },
}
Definition at line 4806 of file mpegvideo_enc.c.
h263_class
const AVClass h263_class static
Initial value:
= {
    .class_name = "H.263 encoder",
    .item_name  = av_default_item_name,
    .option     = h263_options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 4813 of file mpegvideo_enc.c.
ff_h263_encoder
AVCodec ff_h263_encoder
Initial value:
= {
    .name           = "h263",
    .long_name      = NULL_IF_CONFIG_SMALL("H.263 / H.263-1996"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_H263,
    .priv_data_size = sizeof(MpegEncContext),
    .init           = ff_mpv_encode_init,
    .encode2        = ff_mpv_encode_picture,
    .close          = ff_mpv_encode_end,
    .pix_fmts= (const enum AVPixelFormat[]){AV_PIX_FMT_YUV420P, AV_PIX_FMT_NONE},
    .priv_class     = &h263_class,
}
Definition at line 4820 of file mpegvideo_enc.c.
h263p_options
const AVOption h263p_options[] static
Initial value:
= {
    { "umv",        "Use unlimited motion vectors.",    OFFSET(umvplus),       AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, VE },
    { "aiv",        "Use alternative inter VLC.",       OFFSET(alt_inter_vlc), AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, VE },
    { "obmc",       "use overlapped block motion compensation.", OFFSET(obmc), AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, VE },
    { "structured_slices", "Write slice start position at every GOB header instead of just GOB number.", OFFSET(h263_slice_structured), AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, VE},
    FF_MPV_COMMON_OPTS
    { NULL },
}
Definition at line 4833 of file mpegvideo_enc.c.
h263p_class
const AVClass h263p_class static
Initial value:
= {
    .class_name = "H.263p encoder",
    .item_name  = av_default_item_name,
    .option     = h263p_options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 4841 of file mpegvideo_enc.c.
ff_h263p_encoder
AVCodec ff_h263p_encoder
Initial value:
= {
    .name           = "h263p",
    .long_name      = NULL_IF_CONFIG_SMALL("H.263+ / H.263-1998 / H.263 version 2"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_H263P,
    .priv_data_size = sizeof(MpegEncContext),
    .init           = ff_mpv_encode_init,
    .encode2        = ff_mpv_encode_picture,
    .close          = ff_mpv_encode_end,
    .capabilities   = AV_CODEC_CAP_SLICE_THREADS,
    .pix_fmts       = (const enum AVPixelFormat[]){ AV_PIX_FMT_YUV420P, AV_PIX_FMT_NONE },
    .priv_class     = &h263p_class,
}
Definition at line 4848 of file mpegvideo_enc.c.
msmpeg4v2_class
const AVClass msmpeg4v2_class static
Initial value:
= {
    .class_name = "msmpeg4v2 encoder",
    .item_name  = av_default_item_name,
    .option     = ff_mpv_generic_options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 4862 of file mpegvideo_enc.c.
ff_msmpeg4v2_encoder
AVCodec ff_msmpeg4v2_encoder
Initial value:
= {
    .name           = "msmpeg4v2",
    .long_name      = NULL_IF_CONFIG_SMALL("MPEG-4 part 2 Microsoft variant version 2"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_MSMPEG4V2,
    .priv_data_size = sizeof(MpegEncContext),
    .init           = ff_mpv_encode_init,
    .encode2        = ff_mpv_encode_picture,
    .close          = ff_mpv_encode_end,
    .pix_fmts       = (const enum AVPixelFormat[]){ AV_PIX_FMT_YUV420P, AV_PIX_FMT_NONE },
    .priv_class     = &msmpeg4v2_class,
}
Definition at line 4869 of file mpegvideo_enc.c.
msmpeg4v3_class
const AVClass msmpeg4v3_class static
Initial value:
= {
    .class_name = "msmpeg4v3 encoder",
    .item_name  = av_default_item_name,
    .option     = ff_mpv_generic_options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 4882 of file mpegvideo_enc.c.
ff_msmpeg4v3_encoder
AVCodec ff_msmpeg4v3_encoder
Initial value:
= {
    .name           = "msmpeg4",
    .long_name      = NULL_IF_CONFIG_SMALL("MPEG-4 part 2 Microsoft variant version 3"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_MSMPEG4V3,
    .priv_data_size = sizeof(MpegEncContext),
    .init           = ff_mpv_encode_init,
    .encode2        = ff_mpv_encode_picture,
    .close          = ff_mpv_encode_end,
    .pix_fmts       = (const enum AVPixelFormat[]){ AV_PIX_FMT_YUV420P, AV_PIX_FMT_NONE },
    .priv_class     = &msmpeg4v3_class,
}
Definition at line 4889 of file mpegvideo_enc.c.
wmv1_class
const AVClass wmv1_class static
Initial value:
= {
    .class_name = "wmv1 encoder",
    .item_name  = av_default_item_name,
    .option     = ff_mpv_generic_options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 4902 of file mpegvideo_enc.c.
ff_wmv1_encoder
AVCodec ff_wmv1_encoder
Initial value:
= {
    .name           = "wmv1",
    .long_name      = NULL_IF_CONFIG_SMALL("Windows Media Video 7"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_WMV1,
    .priv_data_size = sizeof(MpegEncContext),
    .init           = ff_mpv_encode_init,
    .encode2        = ff_mpv_encode_picture,
    .close          = ff_mpv_encode_end,
    .pix_fmts       = (const enum AVPixelFormat[]){ AV_PIX_FMT_YUV420P, AV_PIX_FMT_NONE },
    .priv_class     = &wmv1_class,
}
Definition at line 4909 of file mpegvideo_enc.c.