FFmpeg: libavcodec/mpeg_er.c File Reference
mpeg_er.c File Reference
#include "error_resilience.h"
#include "mpegvideo.h"
#include "mpeg_er.h"
Functions
static void set_erpic (ERPicture *dst, Picture *src)
void ff_mpeg_er_frame_start (MpegEncContext *s)
static void mpeg_er_decode_mb (void *opaque, int ref, int mv_dir, int mv_type, int(*mv)[2][4][2], int mb_x, int mb_y, int mb_intra, int mb_skipped)
int ff_mpeg_er_init (MpegEncContext *s)
Function Documentation
set_erpic()
static void set_erpic (ERPicture * dst, Picture * src) static
Definition at line 23 of file mpeg_er.c.
Referenced by ff_mpeg_er_frame_start().
ff_mpeg_er_frame_start()
void ff_mpeg_er_frame_start (MpegEncContext * s)
Definition at line 46 of file mpeg_er.c.
Referenced by decode_wmv9(), ff_h263_decode_frame(), ff_rv34_decode_frame(), h261_decode_frame(), mpeg_field_start(), rv10_decode_packet(), and vc1_decode_frame().
mpeg_er_decode_mb()
static void mpeg_er_decode_mb (void * opaque, int ref, int mv_dir, int mv_type, int(*) mv[2][4][2], int mb_x, int mb_y, int mb_intra, int mb_skipped) static
Definition at line 62 of file mpeg_er.c.
Referenced by ff_mpeg_er_init().
ff_mpeg_er_init()
int ff_mpeg_er_init (MpegEncContext * s)
Definition at line 97 of file mpeg_er.c.
Referenced by init_context_frame().