FFmpeg: libavcodec/mpegpicture.h File Reference
mpegpicture.h File Reference
#include <stdint.h>
#include "libavutil/frame.h"
#include "avcodec.h"
#include "motion_est.h"
#include "thread.h"
Data Structures
struct ScratchpadContext
struct Picture
Picture.
Macros
#define MAX_PICTURE_COUNT 36
#define EDGE_WIDTH 16
Functions
int ff_alloc_picture (AVCodecContext *avctx, Picture *pic, MotionEstContext *me, ScratchpadContext *sc, int shared, int encoding, int chroma_x_shift, int chroma_y_shift, int out_format, int mb_stride, int mb_width, int mb_height, int b8_stride, ptrdiff_t *linesize, ptrdiff_t *uvlinesize)
Allocate a Picture.
int ff_mpeg_framesize_alloc (AVCodecContext *avctx, MotionEstContext *me, ScratchpadContext *sc, int linesize)
int ff_mpeg_ref_picture (AVCodecContext *avctx, Picture *dst, Picture *src)
void ff_mpeg_unref_picture (AVCodecContext *avctx, Picture *picture)
Deallocate a picture.
void ff_free_picture_tables (Picture *pic)
int ff_update_picture_tables (Picture *dst, Picture *src)
int ff_find_unused_picture (AVCodecContext *avctx, Picture *picture, int shared)
Macro Definition Documentation
MAX_PICTURE_COUNT
#define MAX_PICTURE_COUNT 36
Definition at line 32 of file mpegpicture.h.
Referenced by ff_find_unused_picture(), ff_mpeg_flush(), ff_mpeg_update_thread_context(), ff_mpv_common_end(), ff_mpv_common_frame_size_change(), ff_mpv_common_init(), ff_mpv_encode_init(), ff_mpv_encode_picture(), ff_mpv_frame_start(), find_unused_picture(), load_input_picture(), and select_input_picture().
EDGE_WIDTH
#define EDGE_WIDTH 16
Definition at line 33 of file mpegpicture.h.
Referenced by alloc_frame_buffer(), avcodec_get_edge_width(), encode_frame(), ff_snow_get_buffer(), ff_snow_release_buffer(), frame_end(), get_buffer_with_edge(), halfpel_interpol(), interpolate_refplane(), and mc_subpel().
Function Documentation
ff_alloc_picture()
int ff_alloc_picture (AVCodecContext * avctx, Picture * pic, MotionEstContext * me, ScratchpadContext * sc, int shared, int encoding, int chroma_x_shift, int chroma_y_shift, int out_format, int mb_stride, int mb_width, int mb_height, int b8_stride, ptrdiff_t * linesize, ptrdiff_t * uvlinesize)
Allocate a Picture.
The pixels are allocated/set by calling get_buffer() if shared = 0.
The pixels are allocated/set by calling get_buffer() if shared = 0
Definition at line 228 of file mpegpicture.c.
Referenced by alloc_picture().
ff_mpeg_framesize_alloc()
int ff_mpeg_framesize_alloc (AVCodecContext * avctx, MotionEstContext * me, ScratchpadContext * sc, int linesize)
Definition at line 56 of file mpegpicture.c.
Referenced by alloc_frame_buffer(), ff_mpeg_update_thread_context(), and ff_update_duplicate_context().
ff_mpeg_ref_picture()
int ff_mpeg_ref_picture (AVCodecContext * avctx, Picture * dst, Picture * src)
Definition at line 358 of file mpegpicture.c.
Referenced by ff_mpeg_update_thread_context(), ff_mpv_frame_start(), frame_start(), and select_input_picture().
ff_mpeg_unref_picture()
void ff_mpeg_unref_picture (AVCodecContext * avctx, Picture * picture)
Deallocate a picture.
Definition at line 291 of file mpegpicture.c.
Referenced by alloc_frame_buffer(), ff_alloc_picture(), ff_find_unused_picture(), ff_mpeg_flush(), ff_mpeg_ref_picture(), ff_mpeg_update_thread_context(), ff_mpv_common_end(), ff_mpv_encode_end(), ff_mpv_encode_picture(), ff_mpv_frame_start(), frame_start(), and select_input_picture().
ff_free_picture_tables()
void ff_free_picture_tables (Picture * pic)
Definition at line 455 of file mpegpicture.c.
Referenced by ff_alloc_picture(), ff_find_unused_picture(), ff_mpeg_unref_picture(), ff_mpv_common_end(), and ff_mpv_encode_end().
ff_update_picture_tables()
int ff_update_picture_tables (Picture * dst, Picture * src)
Definition at line 313 of file mpegpicture.c.
Referenced by ff_mpeg_ref_picture().
ff_find_unused_picture()
int ff_find_unused_picture (AVCodecContext * avctx, Picture * picture, int shared)
Definition at line 441 of file mpegpicture.c.
Referenced by ff_h263_decode_frame(), ff_mpv_frame_start(), load_input_picture(), and select_input_picture().