FFmpeg: libavcodec/mpeg_er.h File Reference
mpeg_er.h File Reference
#include "mpegvideo.h"
Functions
int ff_mpeg_er_init (MpegEncContext *s)
void ff_mpeg_er_frame_start (MpegEncContext *s)
Function Documentation
ff_mpeg_er_init()
int ff_mpeg_er_init (MpegEncContext * s)
Definition at line 97 of file mpeg_er.c.
Referenced by init_context_frame().
ff_mpeg_er_frame_start()
void ff_mpeg_er_frame_start (MpegEncContext * s)
Definition at line 46 of file mpeg_er.c.
Referenced by decode_wmv9(), ff_h263_decode_frame(), ff_rv34_decode_frame(), h261_decode_frame(), mpeg_field_start(), rv10_decode_packet(), and vc1_decode_frame().