FFmpeg: libavformat/mpjpegdec.c File Reference
mpjpegdec.c File Reference
#include "libavutil/avstring.h"
#include "libavutil/opt.h"
#include "avformat.h"
#include "internal.h"
#include "avio_internal.h"
Data Structures
struct MPJPEGDemuxContext
Macros
#define OFFSET(x) offsetof(MPJPEGDemuxContext, x)
#define DEC AV_OPT_FLAG_DECODING_PARAM
Functions
static void trim_right (char *p)
static int get_line (AVIOContext *pb, char *line, int line_size)
static int split_tag_value (char **tag, char **value, char *line)
static int parse_multipart_header (AVIOContext *pb, int *size, const char *expected_boundary, void *log_ctx)
static int mpjpeg_read_close (AVFormatContext *s)
static int mpjpeg_read_probe (AVProbeData *p)
static int mpjpeg_read_header (AVFormatContext *s)
static int parse_content_length (const char *value)
static char * mpjpeg_get_boundary (AVIOContext *pb)
static int mpjpeg_read_packet (AVFormatContext *s, AVPacket *pkt)
Variables
const AVOption mpjpeg_options []
static const AVClass mpjpeg_demuxer_class
AVInputFormat ff_mpjpeg_demuxer
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(MPJPEGDemuxContext, x)
Definition at line 375 of file mpjpegdec.c.
DEC
#define DEC AV_OPT_FLAG_DECODING_PARAM
Definition at line 377 of file mpjpegdec.c.
Function Documentation
trim_right()
static void trim_right (char * p) static
Definition at line 40 of file mpjpegdec.c.
Referenced by get_line(), and split_tag_value().
get_line()
static int get_line (AVIOContext * pb, char * line, int line_size) static
Definition at line 52 of file mpjpegdec.c.
Referenced by mpjpeg_read_header(), and parse_multipart_header().
split_tag_value()
static int split_tag_value (char ** tag, char ** value, char * line) static
Definition at line 68 of file mpjpegdec.c.
Referenced by parse_multipart_header().
parse_multipart_header()
static int parse_multipart_header (AVIOContext * pb, int * size, const char * expected_boundary, void * log_ctx) static
Definition at line 175 of file mpjpegdec.c.
Referenced by mpjpeg_read_packet(), mpjpeg_read_probe(), and split_tag_value().
mpjpeg_read_close()
static int mpjpeg_read_close (AVFormatContext * s) static
Definition at line 106 of file mpjpegdec.c.
mpjpeg_read_probe()
static int mpjpeg_read_probe (AVProbeData * p) static
Definition at line 114 of file mpjpegdec.c.
mpjpeg_read_header()
static int mpjpeg_read_header (AVFormatContext * s) static
Definition at line 134 of file mpjpegdec.c.
parse_content_length()
static int parse_content_length (const char * value) static
Definition at line 164 of file mpjpegdec.c.
Referenced by parse_multipart_header().
mpjpeg_get_boundary()
static char* mpjpeg_get_boundary (AVIOContext * pb) static
Definition at line 253 of file mpjpegdec.c.
Referenced by mpjpeg_read_packet().
mpjpeg_read_packet()
static int mpjpeg_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 297 of file mpjpegdec.c.
Variable Documentation
mpjpeg_options
const AVOption mpjpeg_options[]
Initial value:
= {
    { "strict_mime_boundary",  "require MIME boundaries match", OFFSET(strict_mime_boundary), AV_OPT_TYPE_BOOL, {.i64 = 0}, 0, 1, DEC },
    { NULL }
}
Definition at line 378 of file mpjpegdec.c.
mpjpeg_demuxer_class
const AVClass mpjpeg_demuxer_class static
Initial value:
= {
    .class_name     = "MPJPEG demuxer",
    .item_name      = av_default_item_name,
    .option         = mpjpeg_options,
    .version        = LIBAVUTIL_VERSION_INT,
}
Definition at line 384 of file mpjpegdec.c.
ff_mpjpeg_demuxer
AVInputFormat ff_mpjpeg_demuxer
Initial value:
= {
    .name              = "mpjpeg",
    .long_name         = NULL_IF_CONFIG_SMALL("MIME multipart JPEG"),
    .mime_type         = "multipart/x-mixed-replace",
    .extensions        = "mjpg",
    .priv_data_size    = sizeof(MPJPEGDemuxContext),
    .read_probe        = mpjpeg_read_probe,
    .read_header       = mpjpeg_read_header,
    .read_packet       = mpjpeg_read_packet,
    .read_close        = mpjpeg_read_close,
    .priv_class        = &mpjpeg_demuxer_class,
    .flags             = AVFMT_NOTIMESTAMPS,
}
Definition at line 391 of file mpjpegdec.c.