FFmpeg: libavcodec/mqc.c File Reference
mqc.c File Reference
MQ-coder common (decoder/encoder) functions.
#include <string.h>
#include <stdint.h>
#include "libavutil/attributes.h"
#include "mqc.h"
Data Structures
struct MqcCxState
Functions
void av_cold ff_mqc_init_context_tables (void)
MQ-coder Initialize context tables (QE, NLPS, NMPS)
void ff_mqc_init_contexts (MqcState *mqc)
MQ-coder context initialisations.
Variables
static const MqcCxState cx_states [47]
uint16_t ff_mqc_qe [2 *47]
uint8_t ff_mqc_nlps [2 *47]
uint8_t ff_mqc_nmps [2 *47]
Detailed Description
MQ-coder common (decoder/encoder) functions.
Author
Kamil Nowosad
Definition in file mqc.c.
Function Documentation
ff_mqc_init_context_tables()
void av_cold ff_mqc_init_context_tables (void)
MQ-coder Initialize context tables (QE, NLPS, NMPS)
Definition at line 97 of file mqc.c.
Referenced by j2kenc_init(), and jpeg2000_init_static_data().
ff_mqc_init_contexts()
void ff_mqc_init_contexts (MqcState * mqc)
MQ-coder context initialisations.
Parameters
mqc MQ-coder context
Definition at line 111 of file mqc.c.
Referenced by decode_cblk(), ff_mqc_initdec(), and ff_mqc_initenc().
Variable Documentation
cx_states
const MqcCxState cx_states[47] static
Definition at line 43 of file mqc.c.
ff_mqc_qe
uint16_t ff_mqc_qe[2 *47]
Definition at line 93 of file mqc.c.
Referenced by exchange(), ff_mqc_decode(), ff_mqc_encode(), and ff_mqc_init_context_tables().
ff_mqc_nlps
uint8_t ff_mqc_nlps[2 *47]
Definition at line 94 of file mqc.c.
Referenced by exchange(), ff_mqc_encode(), and ff_mqc_init_context_tables().
ff_mqc_nmps
uint8_t ff_mqc_nmps[2 *47]
Definition at line 95 of file mqc.c.
Referenced by exchange(), ff_mqc_encode(), and ff_mqc_init_context_tables().