FFmpeg: libavcodec/mqc.h File Reference
mqc.h File Reference
MQ-coder.
#include <stdint.h>
Data Structures
struct MqcState
Macros
#define MQC_CX_UNI 17
#define MQC_CX_RL 18
Functions
void ff_mqc_initenc (MqcState *mqc, uint8_t *bp)
initialize the encoder
void ff_mqc_encode (MqcState *mqc, uint8_t *cxstate, int d)
code bit d with context cx
int ff_mqc_length (MqcState *mqc)
number of encoded bytes
int ff_mqc_flush (MqcState *mqc)
flush the encoder [returns number of bytes encoded]
int ff_mqc_flush_to (MqcState *mqc, uint8_t *dst, int *dst_len)
void ff_mqc_initdec (MqcState *mqc, uint8_t *bp, int raw, int reset)
Initialize MQ-decoder.
int ff_mqc_decode (MqcState *mqc, uint8_t *cxstate)
MQ decoder.
void ff_mqc_init_context_tables (void)
MQ-coder Initialize context tables (QE, NLPS, NMPS)
void ff_mqc_init_contexts (MqcState *mqc)
MQ-coder context initialisations.
Variables
uint16_t ff_mqc_qe [2 *47]
uint8_t ff_mqc_nlps [2 *47]
uint8_t ff_mqc_nmps [2 *47]
Detailed Description
MQ-coder.
Author
Kamil Nowosad
Definition in file mqc.h.
Macro Definition Documentation
MQC_CX_UNI
#define MQC_CX_UNI 17
Definition at line 33 of file mqc.h.
Referenced by decode_clnpass(), encode_clnpass(), and ff_mqc_init_contexts().
MQC_CX_RL
#define MQC_CX_RL 18
Definition at line 34 of file mqc.h.
Referenced by decode_clnpass(), encode_clnpass(), and ff_mqc_init_contexts().
Function Documentation
ff_mqc_initenc()
void ff_mqc_initenc (MqcState * mqc, uint8_t * bp)
initialize the encoder
Definition at line 69 of file mqcenc.c.
Referenced by encode_cblk().
ff_mqc_encode()
void ff_mqc_encode (MqcState * mqc, uint8_t * cxstate, int d)
code bit d with context cx
Definition at line 79 of file mqcenc.c.
Referenced by encode_clnpass(), encode_refpass(), and encode_sigpass().
ff_mqc_length()
int ff_mqc_length (MqcState * mqc)
number of encoded bytes
Definition at line 105 of file mqcenc.c.
ff_mqc_flush()
int ff_mqc_flush (MqcState * mqc)
flush the encoder [returns number of bytes encoded]
Definition at line 110 of file mqcenc.c.
Referenced by ff_mqc_flush_to().
ff_mqc_flush_to()
int ff_mqc_flush_to (MqcState * mqc, uint8_t * dst, int * dst_len)
Definition at line 122 of file mqcenc.c.
Referenced by encode_cblk().
ff_mqc_initdec()
void ff_mqc_initdec (MqcState * mqc, uint8_t * bp, int raw, int reset)
Initialize MQ-decoder.
Parameters
mqc MQ decoder state
bp byte pointer
raw raw mode
reset reset states
Definition at line 71 of file mqcdec.c.
Referenced by decode_cblk().
ff_mqc_decode()
int ff_mqc_decode (MqcState * mqc, uint8_t * cxstate)
MQ decoder.
Parameters
mqc MQ decoder state
cxstate Context
Returns
Decision (0 to 1)
Definition at line 93 of file mqcdec.c.
Referenced by decode_clnpass(), decode_refpass(), and decode_sigpass().
ff_mqc_init_context_tables()
void ff_mqc_init_context_tables (void)
MQ-coder Initialize context tables (QE, NLPS, NMPS)
Definition at line 97 of file mqc.c.
Referenced by j2kenc_init(), and jpeg2000_init_static_data().
ff_mqc_init_contexts()
void ff_mqc_init_contexts (MqcState * mqc)
MQ-coder context initialisations.
Parameters
mqc MQ-coder context
Definition at line 111 of file mqc.c.
Referenced by decode_cblk(), ff_mqc_initdec(), and ff_mqc_initenc().
Variable Documentation
ff_mqc_qe
uint16_t ff_mqc_qe[2 *47]
Definition at line 93 of file mqc.c.
Referenced by exchange(), ff_mqc_decode(), ff_mqc_encode(), and ff_mqc_init_context_tables().
ff_mqc_nlps
uint8_t ff_mqc_nlps[2 *47]
Definition at line 94 of file mqc.c.
Referenced by exchange(), ff_mqc_encode(), and ff_mqc_init_context_tables().
ff_mqc_nmps
uint8_t ff_mqc_nmps[2 *47]
Definition at line 95 of file mqc.c.
Referenced by exchange(), ff_mqc_encode(), and ff_mqc_init_context_tables().