FFmpeg: libavcodec/mqcdec.c File Reference
mqcdec.c File Reference
MQ-coder decoder.
#include "mqc.h"
Functions
static void bytein (MqcState *mqc)
static int exchange (MqcState *mqc, uint8_t *cxstate, int lps)
void ff_mqc_initdec (MqcState *mqc, uint8_t *bp, int raw, int reset)
Initialize MQ-decoder.
static int mqc_decode_bypass (MqcState *mqc)
int ff_mqc_decode (MqcState *mqc, uint8_t *cxstate)
MQ decoder.
Detailed Description
MQ-coder decoder.
Author
Kamil Nowosad
Definition in file mqcdec.c.
Function Documentation
bytein()
static void bytein (MqcState * mqc) static
Definition at line 30 of file mqcdec.c.
Referenced by exchange(), ff_mqc_initdec(), and mqc_decode_bypass().
exchange()
static int exchange (MqcState * mqc, uint8_t * cxstate, int lps) static
Definition at line 45 of file mqcdec.c.
Referenced by ff_mqc_decode().
ff_mqc_initdec()
void ff_mqc_initdec (MqcState * mqc, uint8_t * bp, int raw, int reset)
Initialize MQ-decoder.
Parameters
mqc MQ decoder state
bp byte pointer
raw raw mode
reset reset states
Definition at line 71 of file mqcdec.c.
Referenced by decode_cblk().
mqc_decode_bypass()
static int mqc_decode_bypass (MqcState * mqc) static
Definition at line 83 of file mqcdec.c.
Referenced by ff_mqc_decode().
ff_mqc_decode()
int ff_mqc_decode (MqcState * mqc, uint8_t * cxstate)
MQ decoder.
Parameters
mqc MQ decoder state
cxstate Context
Returns
Decision (0 to 1)
Definition at line 93 of file mqcdec.c.
Referenced by decode_clnpass(), decode_refpass(), and decode_sigpass().