FFmpeg: libavcodec/mqcenc.c File Reference
mqcenc.c File Reference
MQ-coder encoder.
#include "libavutil/avassert.h"
#include "mqc.h"
Functions
static void byteout (MqcState *mqc)
static void renorme (MqcState *mqc)
static void setbits (MqcState *mqc)
void ff_mqc_initenc (MqcState *mqc, uint8_t *bp)
initialize the encoder
void ff_mqc_encode (MqcState *mqc, uint8_t *cxstate, int d)
code bit d with context cx
int ff_mqc_length (MqcState *mqc)
number of encoded bytes
int ff_mqc_flush (MqcState *mqc)
flush the encoder [returns number of bytes encoded]
int ff_mqc_flush_to (MqcState *mqc, uint8_t *dst, int *dst_len)
Detailed Description
MQ-coder encoder.
Author
Kamil Nowosad
Definition in file mqcenc.c.
Function Documentation
byteout()
static void byteout (MqcState * mqc) static
Definition at line 31 of file mqcenc.c.
Referenced by ff_mqc_flush(), and renorme().
renorme()
static void renorme (MqcState * mqc) static
Definition at line 51 of file mqcenc.c.
Referenced by ff_mqc_encode().
setbits()
static void setbits (MqcState * mqc) static
Definition at line 61 of file mqcenc.c.
Referenced by ff_mqc_flush().
ff_mqc_initenc()
void ff_mqc_initenc (MqcState * mqc, uint8_t * bp)
initialize the encoder
Definition at line 69 of file mqcenc.c.
Referenced by encode_cblk().
ff_mqc_encode()
void ff_mqc_encode (MqcState * mqc, uint8_t * cxstate, int d)
code bit d with context cx
Definition at line 79 of file mqcenc.c.
Referenced by encode_clnpass(), encode_refpass(), and encode_sigpass().
ff_mqc_length()
int ff_mqc_length (MqcState * mqc)
number of encoded bytes
Definition at line 105 of file mqcenc.c.
ff_mqc_flush()
int ff_mqc_flush (MqcState * mqc)
flush the encoder [returns number of bytes encoded]
Definition at line 110 of file mqcenc.c.
Referenced by ff_mqc_flush_to().
ff_mqc_flush_to()
int ff_mqc_flush_to (MqcState * mqc, uint8_t * dst, int * dst_len)
Definition at line 122 of file mqcenc.c.
Referenced by encode_cblk().