FFmpeg: libavcodec/msmpeg4dec.c File Reference
msmpeg4dec.c File Reference
#include "avcodec.h"
#include "internal.h"
#include "mpegutils.h"
#include "mpegvideo.h"
#include "msmpeg4.h"
#include "libavutil/imgutils.h"
#include "h263.h"
#include "mpeg4video.h"
#include "msmpeg4data.h"
#include "vc1data.h"
#include "wmv2.h"
Macros
#define DC_VLC_BITS 9
#define V2_INTRA_CBPC_VLC_BITS 3
#define V2_MB_TYPE_VLC_BITS 7
#define MV_VLC_BITS 9
#define V2_MV_VLC_BITS 9
#define TEX_VLC_BITS 9
#define DEFAULT_INTER_INDEX 3
Functions
static int msmpeg4v1_pred_dc (MpegEncContext *s, int n, int32_t **dc_val_ptr)
static int msmpeg4v2_decode_motion (MpegEncContext *s, int pred, int f_code)
static int msmpeg4v12_decode_mb (MpegEncContext *s, int16_t block[6][64])
static int msmpeg4v34_decode_mb (MpegEncContext *s, int16_t block[6][64])
av_cold int ff_msmpeg4_decode_init (AVCodecContext *avctx)
int ff_msmpeg4_decode_picture_header (MpegEncContext *s)
int ff_msmpeg4_decode_ext_header (MpegEncContext *s, int buf_size)
static int msmpeg4_decode_dc (MpegEncContext *s, int n, int *dir_ptr)
int ff_msmpeg4_decode_block (MpegEncContext *s, int16_t *block, int n, int coded, const uint8_t *scan_table)
int ff_msmpeg4_decode_motion (MpegEncContext *s, int *mx_ptr, int *my_ptr)
Variables
VLC ff_mb_non_intra_vlc [4]
static VLC v2_dc_lum_vlc
static VLC v2_dc_chroma_vlc
static VLC v2_intra_cbpc_vlc
static VLC v2_mb_type_vlc
static VLC v2_mv_vlc
VLC ff_inter_intra_vlc
AVCodec ff_msmpeg4v1_decoder
AVCodec ff_msmpeg4v2_decoder
AVCodec ff_msmpeg4v3_decoder
AVCodec ff_wmv1_decoder
Macro Definition Documentation
DC_VLC_BITS
#define DC_VLC_BITS 9
Definition at line 37 of file msmpeg4dec.c.
Referenced by ff_msmpeg4_decode_init(), and msmpeg4_decode_dc().
V2_INTRA_CBPC_VLC_BITS
#define V2_INTRA_CBPC_VLC_BITS 3
Definition at line 38 of file msmpeg4dec.c.
Referenced by ff_msmpeg4_decode_init(), and msmpeg4v12_decode_mb().
V2_MB_TYPE_VLC_BITS
#define V2_MB_TYPE_VLC_BITS 7
Definition at line 39 of file msmpeg4dec.c.
Referenced by ff_msmpeg4_decode_init(), and msmpeg4v12_decode_mb().
MV_VLC_BITS
#define MV_VLC_BITS 9
Definition at line 40 of file msmpeg4dec.c.
Referenced by ff_msmpeg4_decode_init(), and ff_msmpeg4_decode_motion().
V2_MV_VLC_BITS
#define V2_MV_VLC_BITS 9
Definition at line 41 of file msmpeg4dec.c.
Referenced by ff_msmpeg4_decode_init(), and msmpeg4v2_decode_motion().
TEX_VLC_BITS
#define TEX_VLC_BITS 9
Definition at line 42 of file msmpeg4dec.c.
Referenced by ff_msmpeg4_decode_block().
DEFAULT_INTER_INDEX
#define DEFAULT_INTER_INDEX 3
Definition at line 44 of file msmpeg4dec.c.
Referenced by msmpeg4v34_decode_mb().
Function Documentation
msmpeg4v1_pred_dc()
static int msmpeg4v1_pred_dc (MpegEncContext * s, int n, int32_t ** dc_val_ptr) inline static
Definition at line 46 of file msmpeg4dec.c.
Referenced by msmpeg4_decode_dc().
msmpeg4v2_decode_motion()
static int msmpeg4v2_decode_motion (MpegEncContext * s, int pred, int f_code) static
Definition at line 73 of file msmpeg4dec.c.
Referenced by msmpeg4v12_decode_mb().
msmpeg4v12_decode_mb()
static int msmpeg4v12_decode_mb (MpegEncContext * s, int16_t block[6][64]) static
Definition at line 104 of file msmpeg4dec.c.
Referenced by ff_msmpeg4_decode_init().
msmpeg4v34_decode_mb()
static int msmpeg4v34_decode_mb (MpegEncContext * s, int16_t block[6][64]) static
Definition at line 194 of file msmpeg4dec.c.
Referenced by ff_msmpeg4_decode_init().
ff_msmpeg4_decode_init()
av_cold int ff_msmpeg4_decode_init (AVCodecContext * avctx)
Definition at line 287 of file msmpeg4dec.c.
Referenced by vc1_decode_frame(), vc1_decode_init(), wmv2_decode_init(), and wmv9_init().
ff_msmpeg4_decode_picture_header()
int ff_msmpeg4_decode_picture_header (MpegEncContext * s)
Definition at line 397 of file msmpeg4dec.c.
Referenced by ff_h263_decode_frame().
ff_msmpeg4_decode_ext_header()
int ff_msmpeg4_decode_ext_header (MpegEncContext * s, int buf_size)
Definition at line 552 of file msmpeg4dec.c.
Referenced by ff_h263_decode_frame(), and ff_msmpeg4_decode_picture_header().
msmpeg4_decode_dc()
static int msmpeg4_decode_dc (MpegEncContext * s, int n, int * dir_ptr) static
Definition at line 580 of file msmpeg4dec.c.
Referenced by ff_msmpeg4_decode_block().
ff_msmpeg4_decode_block()
int ff_msmpeg4_decode_block (MpegEncContext * s, int16_t * block, int n, int coded, const uint8_t * scan_table)
Definition at line 641 of file msmpeg4dec.c.
Referenced by ff_wmv2_decode_mb(), msmpeg4v12_decode_mb(), msmpeg4v34_decode_mb(), and wmv2_decode_inter_block().
ff_msmpeg4_decode_motion()
int ff_msmpeg4_decode_motion (MpegEncContext * s, int * mx_ptr, int * my_ptr)
Definition at line 828 of file msmpeg4dec.c.
Referenced by msmpeg4v34_decode_mb(), and wmv2_decode_motion().
Variable Documentation
ff_mb_non_intra_vlc
VLC ff_mb_non_intra_vlc[4]
Definition at line 64 of file msmpeg4dec.c.
Referenced by ff_wmv2_decode_mb().
v2_dc_lum_vlc
VLC v2_dc_lum_vlc static
Definition at line 65 of file msmpeg4dec.c.
v2_dc_chroma_vlc
VLC v2_dc_chroma_vlc static
Definition at line 66 of file msmpeg4dec.c.
v2_intra_cbpc_vlc
VLC v2_intra_cbpc_vlc static
Definition at line 67 of file msmpeg4dec.c.
v2_mb_type_vlc
VLC v2_mb_type_vlc static
Definition at line 68 of file msmpeg4dec.c.
v2_mv_vlc
VLC v2_mv_vlc static
Definition at line 69 of file msmpeg4dec.c.
ff_inter_intra_vlc
VLC ff_inter_intra_vlc
Definition at line 70 of file msmpeg4dec.c.
Referenced by ff_wmv2_decode_mb().
ff_msmpeg4v1_decoder
AVCodec ff_msmpeg4v1_decoder
Initial value:
= {
    .name           = "msmpeg4v1",
    .long_name      = NULL_IF_CONFIG_SMALL("MPEG-4 part 2 Microsoft variant version 1"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_MSMPEG4V1,
    .priv_data_size = sizeof(MpegEncContext),
    .init           = ff_msmpeg4_decode_init,
    .close          = ff_h263_decode_end,
    .decode         = ff_h263_decode_frame,
    .capabilities   = AV_CODEC_CAP_DRAW_HORIZ_BAND | AV_CODEC_CAP_DR1,
    .max_lowres     = 3,
    .pix_fmts       = (const enum AVPixelFormat[]) {
        AV_PIX_FMT_YUV420P,
        AV_PIX_FMT_NONE
    },
}
Definition at line 866 of file msmpeg4dec.c.
ff_msmpeg4v2_decoder
AVCodec ff_msmpeg4v2_decoder
Initial value:
= {
    .name           = "msmpeg4v2",
    .long_name      = NULL_IF_CONFIG_SMALL("MPEG-4 part 2 Microsoft variant version 2"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_MSMPEG4V2,
    .priv_data_size = sizeof(MpegEncContext),
    .init           = ff_msmpeg4_decode_init,
    .close          = ff_h263_decode_end,
    .decode         = ff_h263_decode_frame,
    .capabilities   = AV_CODEC_CAP_DRAW_HORIZ_BAND | AV_CODEC_CAP_DR1,
    .max_lowres     = 3,
    .pix_fmts       = (const enum AVPixelFormat[]) {
        AV_PIX_FMT_YUV420P,
        AV_PIX_FMT_NONE
    },
}
Definition at line 883 of file msmpeg4dec.c.
ff_msmpeg4v3_decoder
AVCodec ff_msmpeg4v3_decoder
Initial value:
= {
    .name           = "msmpeg4",
    .long_name      = NULL_IF_CONFIG_SMALL("MPEG-4 part 2 Microsoft variant version 3"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_MSMPEG4V3,
    .priv_data_size = sizeof(MpegEncContext),
    .init           = ff_msmpeg4_decode_init,
    .close          = ff_h263_decode_end,
    .decode         = ff_h263_decode_frame,
    .capabilities   = AV_CODEC_CAP_DRAW_HORIZ_BAND | AV_CODEC_CAP_DR1,
    .max_lowres     = 3,
    .pix_fmts       = (const enum AVPixelFormat[]) {
        AV_PIX_FMT_YUV420P,
        AV_PIX_FMT_NONE
    },
}
Definition at line 900 of file msmpeg4dec.c.
ff_wmv1_decoder
AVCodec ff_wmv1_decoder
Initial value:
= {
    .name           = "wmv1",
    .long_name      = NULL_IF_CONFIG_SMALL("Windows Media Video 7"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_WMV1,
    .priv_data_size = sizeof(MpegEncContext),
    .init           = ff_msmpeg4_decode_init,
    .close          = ff_h263_decode_end,
    .decode         = ff_h263_decode_frame,
    .capabilities   = AV_CODEC_CAP_DRAW_HORIZ_BAND | AV_CODEC_CAP_DR1,
    .max_lowres     = 3,
    .pix_fmts       = (const enum AVPixelFormat[]) {
        AV_PIX_FMT_YUV420P,
        AV_PIX_FMT_NONE
    },
}
Definition at line 917 of file msmpeg4dec.c.