FFmpeg: libavcodec/msmpeg4.h File Reference
msmpeg4.h File Reference
#include <stdint.h>
#include "config.h"
#include "avcodec.h"
#include "mpegvideo.h"
#include "msmpeg4data.h"
#include "put_bits.h"
Macros
#define INTER_INTRA_VLC_BITS 3
#define MB_NON_INTRA_VLC_BITS 9
#define MB_INTRA_VLC_BITS 9
#define II_BITRATE 128*1024
#define MBAC_BITRATE 50*1024
#define DC_MAX 119
#define CONFIG_MSMPEG4_DECODER
#define CONFIG_MSMPEG4_ENCODER
Functions
void ff_msmpeg4_code012 (PutBitContext *pb, int n)
void ff_msmpeg4_common_init (MpegEncContext *s)
void ff_msmpeg4_encode_block (MpegEncContext *s, int16_t *block, int n)
void ff_msmpeg4_handle_slices (MpegEncContext *s)
void ff_msmpeg4_encode_motion (MpegEncContext *s, int mx, int my)
int ff_msmpeg4_coded_block_pred (MpegEncContext *s, int n, uint8_t **coded_block_ptr)
int ff_msmpeg4_encode_init (MpegEncContext *s)
void ff_msmpeg4_encode_picture_header (MpegEncContext *s, int picture_number)
void ff_msmpeg4_encode_ext_header (MpegEncContext *s)
void ff_msmpeg4_encode_mb (MpegEncContext *s, int16_t block[6][64], int motion_x, int motion_y)
int ff_msmpeg4_decode_init (AVCodecContext *avctx)
int ff_msmpeg4_decode_picture_header (MpegEncContext *s)
int ff_msmpeg4_decode_ext_header (MpegEncContext *s, int buf_size)
int ff_msmpeg4_decode_motion (MpegEncContext *s, int *mx_ptr, int *my_ptr)
int ff_msmpeg4_decode_block (MpegEncContext *s, int16_t *block, int n, int coded, const uint8_t *scan_table)
int ff_msmpeg4_pred_dc (MpegEncContext *s, int n, int16_t **dc_val_ptr, int *dir_ptr)
Variables
VLC ff_mb_non_intra_vlc [4]
VLC ff_inter_intra_vlc
Macro Definition Documentation
INTER_INTRA_VLC_BITS
#define INTER_INTRA_VLC_BITS 3
Definition at line 33 of file msmpeg4.h.
Referenced by ff_msmpeg4_decode_init(), ff_wmv2_decode_mb(), and msmpeg4v34_decode_mb().
MB_NON_INTRA_VLC_BITS
#define MB_NON_INTRA_VLC_BITS 9
Definition at line 34 of file msmpeg4.h.
Referenced by ff_msmpeg4_decode_init(), ff_wmv2_decode_mb(), and msmpeg4v34_decode_mb().
MB_INTRA_VLC_BITS
#define MB_INTRA_VLC_BITS 9
Definition at line 35 of file msmpeg4.h.
Referenced by ff_msmpeg4_decode_init(), ff_wmv2_decode_mb(), and msmpeg4v34_decode_mb().
II_BITRATE
#define II_BITRATE 128*1024
Definition at line 37 of file msmpeg4.h.
Referenced by ff_msmpeg4_decode_picture_header(), and ff_msmpeg4_encode_picture_header().
MBAC_BITRATE
#define MBAC_BITRATE 50*1024
Definition at line 38 of file msmpeg4.h.
Referenced by ff_msmpeg4_decode_picture_header(), and ff_msmpeg4_encode_picture_header().
DC_MAX
#define DC_MAX 119
Definition at line 40 of file msmpeg4.h.
Referenced by msmpeg4_decode_dc(), and msmpeg4_encode_dc().
CONFIG_MSMPEG4_DECODER
#define CONFIG_MSMPEG4_DECODER
Value:
(CONFIG_MSMPEG4V1_DECODER || \
                                CONFIG_MSMPEG4V2_DECODER || \
                                CONFIG_MSMPEG4V3_DECODER || \
                                CONFIG_WMV1_DECODER      || \
                                CONFIG_WMV2_DECODER      || \
                                CONFIG_VC1_DECODER)
Definition at line 69 of file msmpeg4.h.
Referenced by ff_h263_decode_frame().
CONFIG_MSMPEG4_ENCODER
#define CONFIG_MSMPEG4_ENCODER
Value:
(CONFIG_MSMPEG4V2_ENCODER || \
                                CONFIG_MSMPEG4V3_ENCODER || \
                                CONFIG_WMV1_ENCODER      || \
                                CONFIG_WMV2_ENCODER)
Definition at line 75 of file msmpeg4.h.
Referenced by encode_mb_internal(), encode_picture(), encode_thread(), and ff_mpv_encode_init().
Function Documentation
ff_msmpeg4_code012()
void ff_msmpeg4_code012 (PutBitContext * pb, int n)
Definition at line 70 of file msmpeg4enc.c.
Referenced by ff_msmpeg4_encode_picture_header(), and ff_wmv2_encode_picture_header().
ff_msmpeg4_common_init()
void ff_msmpeg4_common_init (MpegEncContext * s)
Definition at line 109 of file msmpeg4.c.
Referenced by ff_msmpeg4_decode_init(), and ff_msmpeg4_encode_init().
ff_msmpeg4_encode_block()
void ff_msmpeg4_encode_block (MpegEncContext * s, int16_t * block, int n)
Definition at line 582 of file msmpeg4enc.c.
Referenced by ff_msmpeg4_encode_mb(), and ff_wmv2_encode_mb().
ff_msmpeg4_handle_slices()
void ff_msmpeg4_handle_slices (MpegEncContext * s)
Definition at line 335 of file msmpeg4enc.c.
Referenced by ff_msmpeg4_encode_mb(), and ff_wmv2_encode_mb().
ff_msmpeg4_encode_motion()
void ff_msmpeg4_encode_motion (MpegEncContext * s, int mx, int my)
Definition at line 297 of file msmpeg4enc.c.
Referenced by ff_msmpeg4_encode_mb(), and ff_wmv2_encode_mb().
ff_msmpeg4_coded_block_pred()
int ff_msmpeg4_coded_block_pred (MpegEncContext * s, int n, uint8_t ** coded_block_ptr)
Definition at line 153 of file msmpeg4.c.
Referenced by ff_msmpeg4_encode_mb(), ff_wmv2_decode_mb(), ff_wmv2_encode_mb(), and msmpeg4v34_decode_mb().
ff_msmpeg4_encode_init()
int ff_msmpeg4_encode_init (MpegEncContext * s)
Definition at line 121 of file msmpeg4enc.c.
Referenced by ff_mpv_encode_init().
ff_msmpeg4_encode_picture_header()
void ff_msmpeg4_encode_picture_header (MpegEncContext * s, int picture_number)
Definition at line 224 of file msmpeg4enc.c.
Referenced by encode_picture().
ff_msmpeg4_encode_ext_header()
void ff_msmpeg4_encode_ext_header (MpegEncContext * s)
Definition at line 284 of file msmpeg4enc.c.
Referenced by encode_thread(), and ff_msmpeg4_encode_picture_header().
ff_msmpeg4_encode_mb()
void ff_msmpeg4_encode_mb (MpegEncContext * s, int16_t block[6][64], int motion_x, int motion_y)
Definition at line 381 of file msmpeg4enc.c.
Referenced by encode_mb_internal().
ff_msmpeg4_decode_init()
int ff_msmpeg4_decode_init (AVCodecContext * avctx)
Definition at line 287 of file msmpeg4dec.c.
Referenced by vc1_decode_frame(), vc1_decode_init(), wmv2_decode_init(), and wmv9_init().
ff_msmpeg4_decode_picture_header()
int ff_msmpeg4_decode_picture_header (MpegEncContext * s)
Definition at line 397 of file msmpeg4dec.c.
Referenced by ff_h263_decode_frame().
ff_msmpeg4_decode_ext_header()
int ff_msmpeg4_decode_ext_header (MpegEncContext * s, int buf_size)
Definition at line 552 of file msmpeg4dec.c.
Referenced by ff_h263_decode_frame(), and ff_msmpeg4_decode_picture_header().
ff_msmpeg4_decode_motion()
int ff_msmpeg4_decode_motion (MpegEncContext * s, int * mx_ptr, int * my_ptr)
Definition at line 828 of file msmpeg4dec.c.
Referenced by msmpeg4v34_decode_mb(), and wmv2_decode_motion().
ff_msmpeg4_decode_block()
int ff_msmpeg4_decode_block (MpegEncContext * s, int16_t * block, int n, int coded, const uint8_t * scan_table)
Definition at line 641 of file msmpeg4dec.c.
Referenced by ff_wmv2_decode_mb(), msmpeg4v12_decode_mb(), msmpeg4v34_decode_mb(), and wmv2_decode_inter_block().
ff_msmpeg4_pred_dc()
int ff_msmpeg4_pred_dc (MpegEncContext * s, int n, int16_t ** dc_val_ptr, int * dir_ptr)
Definition at line 193 of file msmpeg4.c.
Referenced by msmpeg4_decode_dc(), and msmpeg4_encode_dc().
Variable Documentation
ff_mb_non_intra_vlc
VLC ff_mb_non_intra_vlc[4]
Definition at line 64 of file msmpeg4dec.c.
Referenced by ff_wmv2_decode_mb().
ff_inter_intra_vlc
VLC ff_inter_intra_vlc
Definition at line 70 of file msmpeg4dec.c.
Referenced by ff_wmv2_decode_mb().