FFmpeg: libavcodec/msmpeg4.c File Reference
msmpeg4.c File Reference
MSMPEG4 backend for encoder and decoder.
#include "avcodec.h"
#include "idctdsp.h"
#include "mpegvideo.h"
#include "msmpeg4.h"
#include "libavutil/x86/asm.h"
#include "h263.h"
#include "mpeg4video.h"
#include "msmpeg4data.h"
#include "mpegvideodata.h"
#include "vc1data.h"
#include "libavutil/imgutils.h"
Functions
static av_cold void init_h263_dc_for_msmpeg4 (void)
av_cold void ff_msmpeg4_common_init (MpegEncContext *s)
int ff_msmpeg4_coded_block_pred (MpegEncContext *s, int n, uint8_t **coded_block_ptr)
static int get_dc (uint8_t *src, int stride, int scale, int block_size)
int ff_msmpeg4_pred_dc (MpegEncContext *s, int n, int16_t **dc_val_ptr, int *dir_ptr)
Detailed Description
MSMPEG4 backend for encoder and decoder.
Definition in file msmpeg4.c.
Function Documentation
init_h263_dc_for_msmpeg4()
static av_cold void init_h263_dc_for_msmpeg4 (void) static
Definition at line 52 of file msmpeg4.c.
Referenced by ff_msmpeg4_common_init().
ff_msmpeg4_common_init()
av_cold void ff_msmpeg4_common_init (MpegEncContext * s)
Definition at line 109 of file msmpeg4.c.
Referenced by ff_msmpeg4_decode_init(), and ff_msmpeg4_encode_init().
ff_msmpeg4_coded_block_pred()
int ff_msmpeg4_coded_block_pred (MpegEncContext * s, int n, uint8_t ** coded_block_ptr)
Definition at line 153 of file msmpeg4.c.
Referenced by ff_msmpeg4_encode_mb(), ff_wmv2_decode_mb(), ff_wmv2_encode_mb(), and msmpeg4v34_decode_mb().
get_dc()
static int get_dc (uint8_t * src, int stride, int scale, int block_size) static
Definition at line 179 of file msmpeg4.c.
Referenced by ff_msmpeg4_pred_dc().
ff_msmpeg4_pred_dc()
int ff_msmpeg4_pred_dc (MpegEncContext * s, int n, int16_t ** dc_val_ptr, int * dir_ptr)
Definition at line 193 of file msmpeg4.c.
Referenced by msmpeg4_decode_dc(), and msmpeg4_encode_dc().