FFmpeg: libavcodec/msrledec.h File Reference
msrledec.h File Reference
#include "avcodec.h"
#include "bytestream.h"
Functions
int ff_msrle_decode (AVCodecContext *avctx, AVFrame *pic, int depth, GetByteContext *gb)
Decode stream in MS RLE format into frame.
Function Documentation
ff_msrle_decode()
int ff_msrle_decode (AVCodecContext * avctx, AVFrame * pic, int depth, GetByteContext * gb)
Decode stream in MS RLE format into frame.
Parameters
avctx codec context
pic destination frame
depth bit depth
gb input bytestream context
Definition at line 249 of file msrledec.c.
Referenced by aasc_decode_frame(), bmp_decode_frame(), decode_frame(), and msrle_decode_frame().