FFmpeg: libavcodec/msrledec.c File Reference
msrledec.c File Reference
MS RLE decoder based on decoder by Mike Melanson and my own for TSCC For more information about the MS RLE format, visit: http://www.multimedia.cx/msrle.txt.
#include "libavutil/intreadwrite.h"
#include "avcodec.h"
#include "msrledec.h"
Functions
static int msrle_decode_pal4 (AVCodecContext *avctx, AVFrame *pic, GetByteContext *gb)
static int msrle_decode_8_16_24_32 (AVCodecContext *avctx, AVFrame *pic, int depth, GetByteContext *gb)
int ff_msrle_decode (AVCodecContext *avctx, AVFrame *pic, int depth, GetByteContext *gb)
Decode stream in MS RLE format into frame.
Detailed Description
MS RLE decoder based on decoder by Mike Melanson and my own for TSCC For more information about the MS RLE format, visit: http://www.multimedia.cx/msrle.txt.
Definition in file msrledec.c.
Function Documentation
msrle_decode_pal4()
static int msrle_decode_pal4 (AVCodecContext * avctx, AVFrame * pic, GetByteContext * gb) static
Definition at line 33 of file msrledec.c.
Referenced by ff_msrle_decode().
msrle_decode_8_16_24_32()
static int msrle_decode_8_16_24_32 (AVCodecContext * avctx, AVFrame * pic, int depth, GetByteContext * gb) static
Definition at line 129 of file msrledec.c.
Referenced by ff_msrle_decode().
ff_msrle_decode()
int ff_msrle_decode (AVCodecContext * avctx, AVFrame * pic, int depth, GetByteContext * gb)
Decode stream in MS RLE format into frame.
Parameters
avctx codec context
pic destination frame
depth bit depth
gb input bytestream context
Definition at line 249 of file msrledec.c.
Referenced by aasc_decode_frame(), bmp_decode_frame(), decode_frame(), and msrle_decode_frame().