FFmpeg: libavcodec/mss1.c File Reference
mss1.c File Reference
Microsoft Screen 1 (aka Windows Media Video V7 Screen) decoder.
#include "avcodec.h"
#include "internal.h"
#include "mss12.h"
Data Structures
struct MSS1Context
Functions
static void arith_normalise (ArithCoder *c)
static int arith_get_bits (ArithCoder *c, int bits)
static int arith_get_number (ArithCoder *c, int mod_val)
static int arith_get_prob (ArithCoder *c, int16_t *probs)
static void arith_init (ArithCoder *c, GetBitContext *gb)
static int decode_pal (MSS12Context *ctx, ArithCoder *acoder)
static int mss1_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int mss1_decode_init (AVCodecContext *avctx)
static av_cold int mss1_decode_end (AVCodecContext *avctx)
Variables
AVCodec ff_mss1_decoder
Detailed Description
Microsoft Screen 1 (aka Windows Media Video V7 Screen) decoder.
Definition in file mss1.c.
Function Documentation
arith_normalise()
static void arith_normalise (ArithCoder * c) static
Definition at line 37 of file mss1.c.
Referenced by arith_get_bits(), and arith_get_number().
arith_get_bits()
static int arith_get_bits (ArithCoder * c, int bits) static
Definition at line 65 of file mss1.c.
Referenced by decode_pal().
arith_get_number()
static int arith_get_number (ArithCoder * c, int mod_val) static
Definition at line 79 of file mss1.c.
Referenced by arith_init(), and decode_pal().
arith_get_prob()
static int arith_get_prob (ArithCoder * c, int16_t * probs) static
Definition at line 93 of file mss1.c.
arith_init()
static void arith_init (ArithCoder * c, GetBitContext * gb) static
Definition at line 110 of file mss1.c.
Referenced by mss1_decode_frame().
decode_pal()
static int decode_pal (MSS12Context * ctx, ArithCoder * acoder) static
Definition at line 120 of file mss1.c.
Referenced by mss1_decode_frame().
mss1_decode_frame()
static int mss1_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 139 of file mss1.c.
mss1_decode_init()
static av_cold int mss1_decode_init (AVCodecContext * avctx) static
Definition at line 188 of file mss1.c.
mss1_decode_end()
static av_cold int mss1_decode_end (AVCodecContext * avctx) static
Definition at line 208 of file mss1.c.
Variable Documentation
ff_mss1_decoder
AVCodec ff_mss1_decoder
Initial value:
= {
    .name           = "mss1",
    .long_name      = NULL_IF_CONFIG_SMALL("MS Screen 1"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_MSS1,
    .priv_data_size = sizeof(MSS1Context),
    .init           = mss1_decode_init,
    .close          = mss1_decode_end,
    .decode         = mss1_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 218 of file mss1.c.