FFmpeg: libavcodec/mss2.c File Reference
mss2.c File Reference
Microsoft Screen 2 (aka Windows Media Video V9 Screen) decoder.
#include "libavutil/avassert.h"
#include "error_resilience.h"
#include "internal.h"
#include "mpeg_er.h"
#include "msmpeg4.h"
#include "qpeldsp.h"
#include "vc1.h"
#include "wmv2data.h"
#include "mss12.h"
#include "mss2dsp.h"
Data Structures
struct MSS2Context
struct Rectangle
Macros
#define READ_PAIR(a, b)
#define MAX_WMV9_RECTANGLES 20
#define ARITH2_PADDING 2
Functions
static void arith2_normalise (ArithCoder *c)
static int arith2_get_scaled_value (int value, int n, int range)
static void arith2_rescale_interval (ArithCoder *c, int range, int low, int high, int n)
static int arith2_get_number (ArithCoder *c, int n)
static int arith2_get_prob (ArithCoder *c, int16_t *probs)
static int arith2_get_consumed_bytes (ArithCoder *c)
static void arith2_init (ArithCoder *c, GetByteContext *gB)
static int decode_pal_v2 (MSS12Context *ctx, const uint8_t *buf, int buf_size)
static int decode_555 (GetByteContext *gB, uint16_t *dst, int stride, int keyframe, int w, int h)
static int decode_rle (GetBitContext *gb, uint8_t *pal_dst, int pal_stride, uint8_t *rgb_dst, int rgb_stride, uint32_t *pal, int keyframe, int kf_slipt, int slice, int w, int h)
static int decode_wmv9 (AVCodecContext *avctx, const uint8_t *buf, int buf_size, int x, int y, int w, int h, int wmv9_mask)
static int mss2_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int wmv9_init (AVCodecContext *avctx)
static av_cold int mss2_decode_end (AVCodecContext *avctx)
static av_cold int mss2_decode_init (AVCodecContext *avctx)
Variables
AVCodec ff_mss2_decoder
Detailed Description
Microsoft Screen 2 (aka Windows Media Video V9 Screen) decoder.
Definition in file mss2.c.
Macro Definition Documentation
READ_PAIR
#define READ_PAIR (a, b)
Value:
a  = bytestream2_get_byte(gB) << 4; \
    t  = bytestream2_get_byte(gB);      \
    a |= t >> 4;                        \
    b  = (t & 0xF) << 8;                \
    b |= bytestream2_get_byte(gB);      \
Referenced by decode_555().
MAX_WMV9_RECTANGLES
#define MAX_WMV9_RECTANGLES 20
Definition at line 471 of file mss2.c.
Referenced by mss2_decode_frame().
ARITH2_PADDING
#define ARITH2_PADDING 2
Definition at line 472 of file mss2.c.
Referenced by mss2_decode_frame().
Function Documentation
arith2_normalise()
static void arith2_normalise (ArithCoder * c) static
Definition at line 47 of file mss2.c.
Referenced by arith2_get_number().
arith2_get_scaled_value()
static int arith2_get_scaled_value (int value, int n, int range) static
Definition at line 66 of file mss2.c.
Referenced by arith2_get_number(), and arith2_get_prob().
arith2_rescale_interval()
static void arith2_rescale_interval (ArithCoder * c, int range, int low, int high, int n) static
Definition at line 76 of file mss2.c.
Referenced by arith2_get_number(), and arith2_get_prob().
arith2_get_number()
static int arith2_get_number (ArithCoder * c, int n) static
Definition at line 94 of file mss2.c.
Referenced by arith2_init(), and mss2_decode_frame().
arith2_get_prob()
static int arith2_get_prob (ArithCoder * c, int16_t * probs) static
Definition at line 114 of file mss2.c.
arith2_get_consumed_bytes()
static int arith2_get_consumed_bytes (ArithCoder * c) static
Definition at line 136 of file mss2.c.
Referenced by mss2_decode_frame().
arith2_init()
static void arith2_init (ArithCoder * c, GetByteContext * gB) static
Definition at line 150 of file mss2.c.
Referenced by mss2_decode_frame().
decode_pal_v2()
static int decode_pal_v2 (MSS12Context * ctx, const uint8_t * buf, int buf_size) static
Definition at line 160 of file mss2.c.
Referenced by mss2_decode_frame().
decode_555()
static int decode_555 (GetByteContext * gB, uint16_t * dst, int stride, int keyframe, int w, int h) static
Definition at line 177 of file mss2.c.
Referenced by mss2_decode_frame().
decode_rle()
static int decode_rle (GetBitContext * gb, uint8_t * pal_dst, int pal_stride, uint8_t * rgb_dst, int rgb_stride, uint32_t * pal, int keyframe, int kf_slipt, int slice, int w, int h) static
Definition at line 240 of file mss2.c.
Referenced by mss2_decode_frame().
decode_wmv9()
static int decode_wmv9 (AVCodecContext * avctx, const uint8_t * buf, int buf_size, int x, int y, int w, int h, int wmv9_mask) static
Definition at line 377 of file mss2.c.
Referenced by mss2_decode_frame().
mss2_decode_frame()
static int mss2_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 474 of file mss2.c.
wmv9_init()
static av_cold int wmv9_init (AVCodecContext * avctx) static
Definition at line 748 of file mss2.c.
Referenced by mss2_decode_init().
mss2_decode_end()
static av_cold int mss2_decode_end (AVCodecContext * avctx) static
Definition at line 807 of file mss2.c.
Referenced by mss2_decode_init().
mss2_decode_init()
static av_cold int mss2_decode_init (AVCodecContext * avctx) static
Definition at line 821 of file mss2.c.
Variable Documentation
ff_mss2_decoder
AVCodec ff_mss2_decoder
Initial value:
= {
    .name           = "mss2",
    .long_name      = NULL_IF_CONFIG_SMALL("MS Windows Media Video V9 Screen"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_MSS2,
    .priv_data_size = sizeof(MSS2Context),
    .init           = mss2_decode_init,
    .close          = mss2_decode_end,
    .decode         = mss2_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 851 of file mss2.c.