FFmpeg: libavcodec/mss2dsp.c File Reference
mss2dsp.c File Reference
Microsoft Screen 2 (aka Windows Media Video V9 Screen) decoder DSP routines.
#include "mss2dsp.h"
#include "libavutil/common.h"
Functions
static av_always_inline void mss2_blit_wmv9_template (uint8_t *dst, int dst_stride, int gray, int use_mask, int maskcolor, const uint8_t *mask, int mask_stride, const uint8_t *srcy, int srcy_stride, const uint8_t *srcu, const uint8_t *srcv, int srcuv_stride, int w, int h)
static void mss2_blit_wmv9_c (uint8_t *dst, int dst_stride, const uint8_t *srcy, int srcy_stride, const uint8_t *srcu, const uint8_t *srcv, int srcuv_stride, int w, int h)
static void mss2_blit_wmv9_masked_c (uint8_t *dst, int dst_stride, int maskcolor, const uint8_t *mask, int mask_stride, const uint8_t *srcy, int srcy_stride, const uint8_t *srcu, const uint8_t *srcv, int srcuv_stride, int w, int h)
static void mss2_gray_fill_masked_c (uint8_t *dst, int dst_stride, int maskcolor, const uint8_t *mask, int mask_stride, int w, int h)
static void upsample_plane_c (uint8_t *plane, int plane_stride, int w, int h)
av_cold void ff_mss2dsp_init (MSS2DSPContext *dsp)
Detailed Description
Microsoft Screen 2 (aka Windows Media Video V9 Screen) decoder DSP routines.
Definition in file mss2dsp.c.
Function Documentation
mss2_blit_wmv9_template()
static av_always_inline void mss2_blit_wmv9_template (uint8_t * dst, int dst_stride, int gray, int use_mask, int maskcolor, const uint8_t * mask, int mask_stride, const uint8_t * srcy, int srcy_stride, const uint8_t * srcu, const uint8_t * srcv, int srcuv_stride, int w, int h) static
Definition at line 29 of file mss2dsp.c.
Referenced by mss2_blit_wmv9_c(), mss2_blit_wmv9_masked_c(), and mss2_gray_fill_masked_c().
mss2_blit_wmv9_c()
static void mss2_blit_wmv9_c (uint8_t * dst, int dst_stride, const uint8_t * srcy, int srcy_stride, const uint8_t * srcu, const uint8_t * srcv, int srcuv_stride, int w, int h) static
Definition at line 67 of file mss2dsp.c.
Referenced by ff_mss2dsp_init().
mss2_blit_wmv9_masked_c()
static void mss2_blit_wmv9_masked_c (uint8_t * dst, int dst_stride, int maskcolor, const uint8_t * mask, int mask_stride, const uint8_t * srcy, int srcy_stride, const uint8_t * srcu, const uint8_t * srcv, int srcuv_stride, int w, int h) static
Definition at line 79 of file mss2dsp.c.
Referenced by ff_mss2dsp_init().
mss2_gray_fill_masked_c()
static void mss2_gray_fill_masked_c (uint8_t * dst, int dst_stride, int maskcolor, const uint8_t * mask, int mask_stride, int w, int h) static
Definition at line 93 of file mss2dsp.c.
Referenced by ff_mss2dsp_init().
upsample_plane_c()
static void upsample_plane_c (uint8_t * plane, int plane_stride, int w, int h) static
Definition at line 104 of file mss2dsp.c.
Referenced by ff_mss2dsp_init().
ff_mss2dsp_init()
av_cold void ff_mss2dsp_init (MSS2DSPContext * dsp)
Definition at line 150 of file mss2dsp.c.
Referenced by mss2_decode_init().