FFmpeg: libavcodec/mss34dsp.h File Reference
mss34dsp.h File Reference
#include <stdint.h>
Functions
void ff_mss34_gen_quant_mat (uint16_t *qmat, int quality, int luma)
Generate quantisation matrix for given quality.
void ff_mss34_dct_put (uint8_t *dst, int stride, int *block)
Transform and output DCT block.
Function Documentation
ff_mss34_gen_quant_mat()
void ff_mss34_gen_quant_mat (uint16_t * qmat, int quality, int luma)
Generate quantisation matrix for given quality.
Parameters
qmat destination matrix
quality quality setting (1-100)
luma generate quantisation matrix for luma or chroma
Definition at line 48 of file mss34dsp.c.
Referenced by mss4_decode_frame(), and reset_coders().
ff_mss34_dct_put()
void ff_mss34_dct_put (uint8_t * dst, int stride, int * block)
Transform and output DCT block.
Parameters
dst output plane
stride output plane stride
block block to transform and output
Definition at line 90 of file mss34dsp.c.
Referenced by decode_dct_block(), and mss4_decode_dct_block().