FFmpeg: libavutil/murmur3.c File Reference
murmur3.c File Reference
#include <stdint.h>
#include "mem.h"
#include "intreadwrite.h"
#include "murmur3.h"
Data Structures
struct AVMurMur3
Macros
#define ROT(a, b) (((a) << (b)) | ((a) >> (64 - (b))))
Functions
AVMurMur3 * av_murmur3_alloc (void)
Allocate an AVMurMur3 hash context.
void av_murmur3_init_seeded (AVMurMur3 *c, uint64_t seed)
Initialize or reinitialize an AVMurMur3 hash context with a seed.
void av_murmur3_init (AVMurMur3 *c)
Initialize or reinitialize an AVMurMur3 hash context.
static uint64_t get_k1 (const uint8_t *src)
static uint64_t get_k2 (const uint8_t *src)
static uint64_t update_h1 (uint64_t k, uint64_t h1, uint64_t h2)
static uint64_t update_h2 (uint64_t k, uint64_t h1, uint64_t h2)
void av_murmur3_update (AVMurMur3 *c, const uint8_t *src, int len)
Update hash context with new data.
static uint64_t fmix (uint64_t k)
void av_murmur3_final (AVMurMur3 *c, uint8_t dst[16])
Finish hashing and output digest value.
Variables
static const uint64_t c1 = UINT64_C(0x87c37b91114253d5)
static const uint64_t c2 = UINT64_C(0x4cf5ad432745937f)
Macro Definition Documentation
ROT
#define ROT (a, b) (((a) << (b)) | ((a) >> (64 - (b))))
Definition at line 52 of file murmur3.c.
Referenced by get_k1(), get_k2(), update_h1(), and update_h2().
Function Documentation
get_k1()
static uint64_t get_k1 (const uint8_t * src) inline static
Definition at line 54 of file murmur3.c.
Referenced by av_murmur3_final(), and av_murmur3_update().
get_k2()
static uint64_t get_k2 (const uint8_t * src) inline static
Definition at line 63 of file murmur3.c.
Referenced by av_murmur3_final(), and av_murmur3_update().
update_h1()
static uint64_t update_h1 (uint64_t k, uint64_t h1, uint64_t h2) inline static
Definition at line 72 of file murmur3.c.
Referenced by av_murmur3_update().
update_h2()
static uint64_t update_h2 (uint64_t k, uint64_t h1, uint64_t h2) inline static
Definition at line 82 of file murmur3.c.
Referenced by av_murmur3_update().
fmix()
static uint64_t fmix (uint64_t k) inline static
Definition at line 131 of file murmur3.c.
Referenced by av_murmur3_final().
Variable Documentation
c1
const uint64_t c1 = UINT64_C(0x87c37b91114253d5) static
Definition at line 49 of file murmur3.c.
Referenced by acolor(), acolor16(), aflat(), aflat16(), av_strcasecmp(), av_strncasecmp(), avcodec_get_subtitle_rect_class(), avpriv_trc_smpte_st2084(), close_connection(), cmp_pal_entry(), color(), color16(), compare_fields(), compute_status(), dct4x4(), debug_accuracy(), debug_mean_error(), decode_frame(), decorrelate(), diff(), ff_vp8_luma_dc_wht_msa(), fft_ref_init(), fill_picture_rgb(), flat(), flat16(), get_k1(), get_k2(), http_receive_data(), idct4col_add(), idct4col_put(), idct4row(), idct_row(), init_gaussian_filter(), mode05(), mode06(), mode07(), mode08(), pixel_color7_slow(), ps_tableinit(), qpeg_decode_intra(), rangecmp_wc(), reverse_matrixing(), rgtc2_block_internal(), and wht4x4().
c2
const uint64_t c2 = UINT64_C(0x4cf5ad432745937f) static
Definition at line 50 of file murmur3.c.
Referenced by acolor(), acolor16(), aflat(), aflat16(), av_strcasecmp(), av_strncasecmp(), avcodec_get_subtitle_rect_class(), avpriv_trc_smpte_st2084(), cmp_pal_entry(), color(), color16(), compare_fields(), debug_accuracy(), debug_mean_error(), decorrelate(), diff(), ff_urldecode(), fill_picture_rgb(), get_k1(), get_k2(), idct4col_add(), idct4col_put(), idct4row(), idct_row(), init_gaussian_filter(), mode05(), mode06(), mode07(), mode08(), postProcess(), ps_tableinit(), qpel_motion_search(), rangecmp_wc(), reverse_matrixing(), and sws_init_context().