FFmpeg: libavformat/mux.c File Reference
mux.c File Reference
muxing functions for use within libavformat
#include "avformat.h"
#include "avio_internal.h"
#include "internal.h"
#include "libavcodec/internal.h"
#include "libavcodec/bytestream.h"
#include "libavutil/opt.h"
#include "libavutil/dict.h"
#include "libavutil/pixdesc.h"
#include "libavutil/timestamp.h"
#include "metadata.h"
#include "id3v2.h"
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/internal.h"
#include "libavutil/mathematics.h"
#include "libavutil/parseutils.h"
#include "libavutil/time.h"
#include "riff.h"
#include "audiointerleave.h"
#include "url.h"
#include <stdarg.h>
Macros
#define AV_PKT_FLAG_UNCODED_FRAME 0x2000
#define UNCODED_FRAME_PACKET_SIZE (INT_MIN / 3 * 2 + (int)sizeof(AVFrame))
#define CHUNK_START 0x1000
Functions
static void frac_init (FFFrac *f, int64_t val, int64_t num, int64_t den)
f = val + (num / den) + 0.5.
static void frac_add (FFFrac *f, int64_t incr)
Fractional addition to f: f = f + (incr / f->den).
AVRational ff_choose_timebase (AVFormatContext *s, AVStream *st, int min_precision)
Chooses a timebase for muxing the specified stream.
enum AVChromaLocation ff_choose_chroma_location (AVFormatContext *s, AVStream *st)
Chooses a timebase for muxing the specified stream.
int avformat_alloc_output_context2 (AVFormatContext **avctx, AVOutputFormat *oformat, const char *format, const char *filename)
Allocate an AVFormatContext for an output format.
static int validate_codec_tag (AVFormatContext *s, AVStream *st)
static int init_muxer (AVFormatContext *s, AVDictionary **options)
static int init_pts (AVFormatContext *s)
static int write_header_internal (AVFormatContext *s)
int avformat_init_output (AVFormatContext *s, AVDictionary **options)
Allocate the stream private data and initialize the codec, but do not write the header.
int avformat_write_header (AVFormatContext *s, AVDictionary **options)
Allocate the stream private data and write the stream header to an output media file.
static int write_packet (AVFormatContext *s, AVPacket *pkt)
Make timestamps non negative, move side data from payload to internal struct, call muxer, and restore sidedata.
static int check_packet (AVFormatContext *s, AVPacket *pkt)
static int prepare_input_packet (AVFormatContext *s, AVPacket *pkt)
static int do_packet_auto_bsf (AVFormatContext *s, AVPacket *pkt)
int av_write_frame (AVFormatContext *s, AVPacket *pkt)
Write a packet to an output media file.
int ff_interleave_add_packet (AVFormatContext *s, AVPacket *pkt, int(*compare)(AVFormatContext *, AVPacket *, AVPacket *))
Add packet to AVFormatContext->packet_buffer list, determining its interleaved position using compare() function argument.
static int interleave_compare_dts (AVFormatContext *s, AVPacket *next, AVPacket *pkt)
int ff_interleave_packet_per_dts (AVFormatContext *s, AVPacket *out, AVPacket *pkt, int flush)
Interleave a packet per dts in an output media file.
int ff_interleaved_peek (AVFormatContext *s, int stream, AVPacket *pkt, int add_offset)
Find the next packet in the interleaving queue for the given stream.
static int interleave_packet (AVFormatContext *s, AVPacket *out, AVPacket *in, int flush)
Interleave an AVPacket correctly so it can be muxed.
int av_interleaved_write_frame (AVFormatContext *s, AVPacket *pkt)
Write a packet to an output media file ensuring correct interleaving.
int av_write_trailer (AVFormatContext *s)
Write the stream trailer to an output media file and free the file private data.
int av_get_output_timestamp (struct AVFormatContext *s, int stream, int64_t *dts, int64_t *wall)
Get timing information for the data currently output.
int ff_write_chained (AVFormatContext *dst, int dst_stream, AVPacket *pkt, AVFormatContext *src, int interleave)
Write a packet to another muxer than the one the user originally intended.
static int av_write_uncoded_frame_internal (AVFormatContext *s, int stream_index, AVFrame *frame, int interleaved)
int av_write_uncoded_frame (AVFormatContext *s, int stream_index, AVFrame *frame)
Write an uncoded frame to an output media file.
int av_interleaved_write_uncoded_frame (AVFormatContext *s, int stream_index, AVFrame *frame)
Write an uncoded frame to an output media file.
int av_write_uncoded_frame_query (AVFormatContext *s, int stream_index)
Test whether a muxer supports uncoded frame.
Detailed Description
muxing functions for use within libavformat
Definition in file mux.c.
Macro Definition Documentation
AV_PKT_FLAG_UNCODED_FRAME
#define AV_PKT_FLAG_UNCODED_FRAME 0x2000
Definition at line 559 of file mux.c.
Referenced by av_write_uncoded_frame_internal(), ff_interleave_add_packet(), and write_packet().
UNCODED_FRAME_PACKET_SIZE
#define UNCODED_FRAME_PACKET_SIZE (INT_MIN / 3 * 2 + (int)sizeof(AVFrame))
Definition at line 565 of file mux.c.
Referenced by av_write_uncoded_frame_internal(), ff_interleave_add_packet(), and write_packet().
CHUNK_START
#define CHUNK_START 0x1000
Definition at line 965 of file mux.c.
Referenced by ff_interleave_add_packet().
Function Documentation
frac_init()
static void frac_init (FFFrac * f, int64_t val, int64_t num, int64_t den) static
f = val + (num / den) + 0.5.
'num' is normalized so that it is such as 0 <= num < den.
Parameters
f fractional number
val integer value
num must be >= 0
den must be >= 1
Definition at line 64 of file mux.c.
Referenced by init_pts().
frac_add()
static void frac_add (FFFrac * f, int64_t incr) static
Fractional addition to f: f = f + (incr / f->den).
Parameters
f fractional number
incr increment, can be positive or negative
Definition at line 82 of file mux.c.
ff_choose_timebase()
AVRational ff_choose_timebase (AVFormatContext * s, AVStream * st, int min_precision)
Chooses a timebase for muxing the specified stream.
The chosen timebase allows sample accurate timestamps based on the framerate or sample rate for audio streams. It also is at least as precise as 1/min_precision would be.
Definition at line 102 of file mux.c.
Referenced by nut_write_header().
ff_choose_chroma_location()
enum AVChromaLocation ff_choose_chroma_location (AVFormatContext * s, AVStream * st)
Chooses a timebase for muxing the specified stream.
Definition at line 118 of file mux.c.
Referenced by mxf_write_header().
avformat_alloc_output_context2()
int avformat_alloc_output_context2 (AVFormatContext ** ctx, AVOutputFormat * oformat, const char * format_name, const char * filename)
Allocate an AVFormatContext for an output format.
avformat_free_context() can be used to free the context and everything allocated by the framework within it.
Parameters
*ctx is set to the created format context, or to NULL in case of failure
oformat format to use for allocating the context, if NULL format_name and filename are used instead
format_name the name of output format to use for allocating the context, if NULL filename is used instead
filename the name of the filename to use for allocating the context, may be NULL
Returns
>= 0 in case of success, a negative AVERROR code in case of failure
Definition at line 148 of file mux.c.
Referenced by avdevice_list_output_sinks(), chunk_mux_init(), fifo_mux_init(), hls_mux_init(), initialize_fifo_tst_muxer_chain(), main(), open_output_file(), open_slave(), segment_mux_init(), and write_packet().
validate_codec_tag()
static int validate_codec_tag (AVFormatContext * s, AVStream * st) static
Check that tag + id is in the table If neither is in the table -> OK If tag is in the table with another id -> FAIL If id is in the table with another tag -> FAIL unless strict < normal
Definition at line 202 of file mux.c.
Referenced by init_muxer().
init_muxer()
static int init_muxer (AVFormatContext * s, AVDictionary ** options) static
Definition at line 236 of file mux.c.
Referenced by avformat_init_output().
init_pts()
static int init_pts (AVFormatContext * s) static
Definition at line 437 of file mux.c.
Referenced by avformat_init_output(), and avformat_write_header().
write_header_internal()
static int write_header_internal (AVFormatContext * s) static
Definition at line 474 of file mux.c.
Referenced by av_write_frame(), av_write_trailer(), avformat_write_header(), and write_packet().
write_packet()
static int write_packet (AVFormatContext * s, AVPacket * pkt) static
Make timestamps non negative, move side data from payload to internal struct, call muxer, and restore sidedata.
FIXME: this function should NEVER get undefined pts/dts beside when the AVFMT_NOTIMESTAMPS is set. Those additional safety checks should be dropped once the correct checks are set in the callers.
Definition at line 689 of file mux.c.
Referenced by av_interleaved_write_frame(), av_write_frame(), and av_write_trailer().
check_packet()
static int check_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 792 of file mux.c.
Referenced by prepare_input_packet().
prepare_input_packet()
static int prepare_input_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 811 of file mux.c.
Referenced by av_interleaved_write_frame(), and av_write_frame().
do_packet_auto_bsf()
static int do_packet_auto_bsf (AVFormatContext * s, AVPacket * pkt) static
Definition at line 863 of file mux.c.
Referenced by av_interleaved_write_frame(), and av_write_frame().
ff_interleave_add_packet()
int ff_interleave_add_packet (AVFormatContext * s, AVPacket * pkt, int(*)(AVFormatContext *, AVPacket *, AVPacket *) compare)
Add packet to AVFormatContext->packet_buffer list, determining its interleaved position using compare() function argument.
Returns
0, or < 0 on error
Definition at line 967 of file mux.c.
Referenced by ff_audio_rechunk_interleave(), and ff_interleave_packet_per_dts().
interleave_compare_dts()
static int interleave_compare_dts (AVFormatContext * s, AVPacket * next, AVPacket * pkt) static
Definition at line 1045 of file mux.c.
Referenced by ff_interleave_packet_per_dts().
ff_interleave_packet_per_dts()
int ff_interleave_packet_per_dts (AVFormatContext * s, AVPacket * out, AVPacket * pkt, int flush)
Interleave a packet per dts in an output media file.
Packets with pkt->destruct == av_destruct_packet will be freed inside this function, so they cannot be used after it. Note that calling av_packet_unref() on them is still safe.
Parameters
s media file handle
out the interleaved packet will be output here
pkt the input packet
flush 1 if no further packets are available as input and all remaining packets should be output
Returns
1 if a packet was output, 0 if no packet could be output, < 0 if an error occurred
Definition at line 1068 of file mux.c.
Referenced by gxf_interleave_packet(), and interleave_packet().
ff_interleaved_peek()
int ff_interleaved_peek (AVFormatContext * s, int stream, AVPacket * pkt, int add_offset)
Find the next packet in the interleaving queue for the given stream.
The pkt parameter is filled in with the queued packet, including references to the data (which the caller is not allowed to keep or modify).
Returns
0 if a packet was found, a negative value if no packet was found
Definition at line 1187 of file mux.c.
Referenced by mov_flush_fragment().
interleave_packet()
static int interleave_packet (AVFormatContext * s, AVPacket * out, AVPacket * in, int flush) static
Interleave an AVPacket correctly so it can be muxed.
Parameters
out the interleaved packet will be output here
in the input packet
flush 1 if no further packets are available as input and all remaining packets should be output
Returns
1 if a packet was output, 0 if no packet could be output, < 0 if an error occurred
Definition at line 1222 of file mux.c.
Referenced by av_interleaved_write_frame(), and av_write_trailer().
ff_write_chained()
int ff_write_chained (AVFormatContext * dst, int dst_stream, AVPacket * pkt, AVFormatContext * src, int interleave)
Write a packet to another muxer than the one the user originally intended.
Useful when chaining muxers, where one muxer internally writes a received packet to another muxer.
Parameters
dst the muxer to write the packet to
dst_stream the stream index within dst to write the packet to
pkt the packet to be written
src the muxer the packet originally was intended for
interleave 0->use av_write_frame, 1->av_interleaved_write_frame
Returns
the value av_write_frame returned
Definition at line 1366 of file mux.c.
Referenced by dash_write_packet(), ff_mov_add_hinted_packet(), hds_write_packet(), hls_write_packet(), ism_write_packet(), rtsp_write_packet(), sap_write_packet(), and seg_write_packet().
av_write_uncoded_frame_internal()
static int av_write_uncoded_frame_internal (AVFormatContext * s, int stream_index, AVFrame * frame, int interleaved) static
Definition at line 1395 of file mux.c.
Referenced by av_interleaved_write_uncoded_frame(), and av_write_uncoded_frame().