FFmpeg: libavformat/mvdec.c File Reference
mvdec.c File Reference
Silicon Graphics Movie demuxer.
#include "libavutil/channel_layout.h"
#include "libavutil/eval.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/rational.h"
#include "avformat.h"
#include "internal.h"
Data Structures
struct MvContext
Macros
#define AUDIO_FORMAT_SIGNED 401
Functions
static int mv_probe (AVProbeData *p)
static char * var_read_string (AVIOContext *pb, int size)
static int var_read_int (AVIOContext *pb, int size)
static AVRational var_read_float (AVIOContext *pb, int size)
static void var_read_metadata (AVFormatContext *avctx, const char *tag, int size)
static int set_channels (AVFormatContext *avctx, AVStream *st, int channels)
static int parse_global_var (AVFormatContext *avctx, AVStream *st, const char *name, int size)
Parse global variable.
static int parse_audio_var (AVFormatContext *avctx, AVStream *st, const char *name, int size)
Parse audio variable.
static int parse_video_var (AVFormatContext *avctx, AVStream *st, const char *name, int size)
Parse video variable.
static int read_table (AVFormatContext *avctx, AVStream *st, int(*parse)(AVFormatContext *avctx, AVStream *st, const char *name, int size))
static void read_index (AVIOContext *pb, AVStream *st)
static int mv_read_header (AVFormatContext *avctx)
static int mv_read_packet (AVFormatContext *avctx, AVPacket *pkt)
static int mv_read_seek (AVFormatContext *avctx, int stream_index, int64_t timestamp, int flags)
Variables
AVInputFormat ff_mv_demuxer
Detailed Description
Silicon Graphics Movie demuxer.
Definition in file mvdec.c.
Macro Definition Documentation
AUDIO_FORMAT_SIGNED
#define AUDIO_FORMAT_SIGNED 401
Definition at line 47 of file mvdec.c.
Referenced by mv_read_header().
Function Documentation
mv_probe()
static int mv_probe (AVProbeData * p) static
Definition at line 49 of file mvdec.c.
var_read_string()
static char* var_read_string (AVIOContext * pb, int size) static
Definition at line 57 of file mvdec.c.
Referenced by parse_video_var(), var_read_float(), var_read_int(), and var_read_metadata().
var_read_int()
static int var_read_int (AVIOContext * pb, int size) static
Definition at line 74 of file mvdec.c.
Referenced by parse_audio_var(), parse_global_var(), and parse_video_var().
var_read_float()
static AVRational var_read_float (AVIOContext * pb, int size) static
Definition at line 85 of file mvdec.c.
Referenced by parse_video_var().
var_read_metadata()
static void var_read_metadata (AVFormatContext * avctx, const char * tag, int size) static
Definition at line 96 of file mvdec.c.
Referenced by mv_read_header(), parse_audio_var(), parse_global_var(), and parse_video_var().
set_channels()
static int set_channels (AVFormatContext * avctx, AVStream * st, int channels) static
Definition at line 103 of file mvdec.c.
Referenced by mv_read_header(), and parse_audio_var().
parse_global_var()
static int parse_global_var (AVFormatContext * avctx, AVStream * st, const char * name, int size) static
Parse global variable.
Returns
< 0 if unknown
Definition at line 119 of file mvdec.c.
Referenced by mv_read_header().
parse_audio_var()
static int parse_audio_var (AVFormatContext * avctx, AVStream * st, const char * name, int size) static
Parse audio variable.
Returns
< 0 if unknown
Definition at line 143 of file mvdec.c.
Referenced by mv_read_header().
parse_video_var()
static int parse_video_var (AVFormatContext * avctx, AVStream * st, const char * name, int size) static
Parse video variable.
Returns
< 0 if unknown
Definition at line 173 of file mvdec.c.
Referenced by mv_read_header().
read_table()
static int read_table (AVFormatContext * avctx, AVStream * st, int(*)(AVFormatContext *avctx, AVStream *st, const char *name, int size) parse) static
Definition at line 226 of file mvdec.c.
Referenced by mv_read_header().
read_index()
static void read_index (AVIOContext * pb, AVStream * st) static
Definition at line 253 of file mvdec.c.
Referenced by mv_read_header().
mv_read_header()
static int mv_read_header (AVFormatContext * avctx) static
Definition at line 270 of file mvdec.c.
mv_read_packet()
static int mv_read_packet (AVFormatContext * avctx, AVPacket * pkt) static
Definition at line 408 of file mvdec.c.
mv_read_seek()
static int mv_read_seek (AVFormatContext * avctx, int stream_index, int64_t timestamp, int flags) static
Definition at line 456 of file mvdec.c.
Variable Documentation
ff_mv_demuxer
AVInputFormat ff_mv_demuxer
Initial value:
= {
    .name           = "mv",
    .long_name      = NULL_IF_CONFIG_SMALL("Silicon Graphics Movie"),
    .priv_data_size = sizeof(MvContext),
    .read_probe     = mv_probe,
    .read_header    = mv_read_header,
    .read_packet    = mv_read_packet,
    .read_seek      = mv_read_seek,
}
Definition at line 478 of file mvdec.c.