FFmpeg: libavformat/mxfdec.c File Reference
mxfdec.c File Reference
#include <inttypes.h>
#include "libavutil/aes.h"
#include "libavutil/avassert.h"
#include "libavutil/mathematics.h"
#include "libavcodec/bytestream.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/parseutils.h"
#include "libavutil/timecode.h"
#include "avformat.h"
#include "internal.h"
#include "mxf.h"
Data Structures
struct MXFPartition
struct MXFCryptoContext
struct MXFStructuralComponent
struct MXFSequence
struct MXFTimecodeComponent
struct MXFPulldownComponent
struct MXFEssenceGroup
struct MXFTaggedValue
struct MXFTrack
struct MXFDescriptor
struct MXFIndexTableSegment
struct MXFPackage
struct MXFMetadataSet
struct MXFIndexTable
struct MXFContext
struct MXFMetadataReadTableEntry
Macros
#define MXF_FIELD_DOMINANCE_DEFAULT 0
#define MXF_FIELD_DOMINANCE_FF 1 /* coded first, displayed first */
#define MXF_FIELD_DOMINANCE_FL 2 /* coded first, displayed last */
#define IS_KLV_KEY(x, y) (!memcmp(x, y, sizeof(y)))
#define READ_STR16(type, big_endian)
#define SET_STR_METADATA(pb, name, str)
#define SET_UID_METADATA(pb, name, var, str)
#define SET_TS_METADATA(pb, name, var, str)
Typedefs
typedef int MXFMetadataReadFunc(void *arg, AVIOContext *pb, int tag, int size, UID uid, int64_t klv_offset)
Enumerations
enum MXFPartitionType { Header, BodyPartition, Footer }
enum MXFOP {
OP1a = 1, OP1b, OP1c, OP2a,
OP2b, OP2c, OP3a, OP3b,
OP3c, OPAtom, OPSONYOpt
}
enum MXFWrappingScheme { Frame, Clip }
Functions
static int mxf_read_close (AVFormatContext *s)
static void mxf_free_metadataset (MXFMetadataSet **ctx, int freectx)
static int64_t klv_decode_ber_length (AVIOContext *pb)
static int mxf_read_sync (AVIOContext *pb, const uint8_t *key, unsigned size)
static int klv_read_packet (KLVPacket *klv, AVIOContext *pb)
static int mxf_get_stream_index (AVFormatContext *s, KLVPacket *klv)
static int mxf_get_d10_aes3_packet (AVIOContext *pb, AVStream *st, AVPacket *pkt, int64_t length)
static int mxf_decrypt_triplet (AVFormatContext *s, AVPacket *pkt, KLVPacket *klv)
static int mxf_read_primer_pack (void *arg, AVIOContext *pb, int tag, int size, UID uid, int64_t klv_offset)
static int mxf_read_partition_pack (void *arg, AVIOContext *pb, int tag, int size, UID uid, int64_t klv_offset)
static int mxf_add_metadata_set (MXFContext *mxf, void *metadata_set)
static int mxf_read_cryptographic_context (void *arg, AVIOContext *pb, int tag, int size, UID uid, int64_t klv_offset)
static int mxf_read_strong_ref_array (AVIOContext *pb, UID **refs, int *count)
static int mxf_read_utf16_string (AVIOContext *pb, int size, char **str, int be)
static int mxf_read_content_storage (void *arg, AVIOContext *pb, int tag, int size, UID uid, int64_t klv_offset)
static int mxf_read_source_clip (void *arg, AVIOContext *pb, int tag, int size, UID uid, int64_t klv_offset)
static int mxf_read_timecode_component (void *arg, AVIOContext *pb, int tag, int size, UID uid, int64_t klv_offset)
static int mxf_read_pulldown_component (void *arg, AVIOContext *pb, int tag, int size, UID uid, int64_t klv_offset)
static int mxf_read_track (void *arg, AVIOContext *pb, int tag, int size, UID uid, int64_t klv_offset)
static int mxf_read_sequence (void *arg, AVIOContext *pb, int tag, int size, UID uid, int64_t klv_offset)
static int mxf_read_essence_group (void *arg, AVIOContext *pb, int tag, int size, UID uid, int64_t klv_offset)
static int mxf_read_package (void *arg, AVIOContext *pb, int tag, int size, UID uid, int64_t klv_offset)
static int mxf_read_index_entry_array (AVIOContext *pb, MXFIndexTableSegment *segment)
static int mxf_read_index_table_segment (void *arg, AVIOContext *pb, int tag, int size, UID uid, int64_t klv_offset)
static void mxf_read_pixel_layout (AVIOContext *pb, MXFDescriptor *descriptor)
static int mxf_read_generic_descriptor (void *arg, AVIOContext *pb, int tag, int size, UID uid, int64_t klv_offset)
static int mxf_read_indirect_value (void *arg, AVIOContext *pb, int size)
static int mxf_read_tagged_value (void *arg, AVIOContext *pb, int tag, int size, UID uid, int64_t klv_offset)
static int mxf_match_uid (const UID key, const UID uid, int len)
static const MXFCodecUL * mxf_get_codec_ul (const MXFCodecUL *uls, UID *uid)
static void * mxf_resolve_strong_ref (MXFContext *mxf, UID *strong_ref, enum MXFMetadataSetType type)
static int mxf_get_sorted_table_segments (MXFContext *mxf, int *nb_sorted_segments, MXFIndexTableSegment ***sorted_segments)
static int mxf_absolute_bodysid_offset (MXFContext *mxf, int body_sid, int64_t offset, int64_t *offset_out)
Computes the absolute file offset of the given essence container offset.
static int64_t mxf_essence_container_end (MXFContext *mxf, int body_sid)
Returns the end position of the essence container with given BodySID, or zero if unknown.
static int mxf_edit_unit_absolute_offset (MXFContext *mxf, MXFIndexTable *index_table, int64_t edit_unit, int64_t *edit_unit_out, int64_t *offset_out, int nag)
static int mxf_compute_ptses_fake_index (MXFContext *mxf, MXFIndexTable *index_table)
static int mxf_compute_index_tables (MXFContext *mxf)
Sorts and collects index table segments into index tables.
static int mxf_is_intra_only (MXFDescriptor *descriptor)
static int mxf_uid_to_str (UID uid, char **str)
static int mxf_umid_to_str (UID ul, UID uid, char **str)
static int mxf_add_umid_metadata (AVDictionary **pm, const char *key, MXFPackage *package)
static int mxf_add_timecode_metadata (AVDictionary **pm, const char *key, AVTimecode *tc)
static MXFTimecodeComponent * mxf_resolve_timecode_component (MXFContext *mxf, UID *strong_ref)
static MXFPackage * mxf_resolve_source_package (MXFContext *mxf, UID package_uid)
static MXFDescriptor * mxf_resolve_multidescriptor (MXFContext *mxf, MXFDescriptor *descriptor, int track_id)
static MXFStructuralComponent * mxf_resolve_essence_group_choice (MXFContext *mxf, MXFEssenceGroup *essence_group)
static MXFStructuralComponent * mxf_resolve_sourceclip (MXFContext *mxf, UID *strong_ref)
static int mxf_parse_package_comments (MXFContext *mxf, AVDictionary **pm, MXFPackage *package)
static int mxf_parse_physical_source_package (MXFContext *mxf, MXFTrack *source_track, AVStream *st)
static int mxf_add_metadata_stream (MXFContext *mxf, MXFTrack *track)
static int mxf_parse_structural_metadata (MXFContext *mxf)
static int64_t mxf_timestamp_to_int64 (uint64_t timestamp)
static int mxf_read_identification_metadata (void *arg, AVIOContext *pb, int tag, int size, UID _uid, int64_t klv_offset)
static int mxf_read_preface_metadata (void *arg, AVIOContext *pb, int tag, int size, UID uid, int64_t klv_offset)
static int mxf_metadataset_init (MXFMetadataSet *ctx, enum MXFMetadataSetType type)
static int mxf_read_local_tags (MXFContext *mxf, KLVPacket *klv, MXFMetadataReadFunc *read_child, int ctx_size, enum MXFMetadataSetType type)
static int mxf_is_partition_pack_key (UID key)
Matches any partition pack key, in other words:
static int mxf_parse_klv (MXFContext *mxf, KLVPacket klv, MXFMetadataReadFunc *read, int ctx_size, enum MXFMetadataSetType type)
Parses a metadata KLV.
static int mxf_seek_to_previous_partition (MXFContext *mxf)
Seeks to the previous partition and parses it, if possible.
static int mxf_parse_handle_essence (MXFContext *mxf)
Called when essence is encountered.
static int mxf_parse_handle_partition_or_eof (MXFContext *mxf)
Called when the next partition or EOF is encountered.
static void mxf_compute_essence_containers (MXFContext *mxf)
Figures out the proper offset and length of the essence container in each partition.
static int64_t round_to_kag (int64_t position, int kag_size)
static int is_pcm (enum AVCodecID codec_id)
static AVStream * mxf_get_opatom_stream (MXFContext *mxf)
static void mxf_handle_small_eubc (AVFormatContext *s)
Deal with the case where for some audio atoms EditUnitByteCount is very small (2, 4..).
static int mxf_handle_missing_index_segment (MXFContext *mxf)
Deal with the case where OPAtom files does not have any IndexTableSegments.
static void mxf_read_random_index_pack (AVFormatContext *s)
static int mxf_read_header (AVFormatContext *s)
static int64_t mxf_set_current_edit_unit (MXFContext *mxf, int64_t current_offset)
Sets mxf->current_edit_unit based on what offset we're currently at.
static int mxf_compute_sample_count (MXFContext *mxf, int stream_index, uint64_t *sample_count)
static int mxf_set_audio_pts (MXFContext *mxf, AVCodecParameters *par, AVPacket *pkt)
static int mxf_read_packet_old (AVFormatContext *s, AVPacket *pkt)
static int mxf_read_packet (AVFormatContext *s, AVPacket *pkt)
static int mxf_probe (AVProbeData *p)
static int mxf_read_seek (AVFormatContext *s, int stream_index, int64_t sample_time, int flags)
Variables
static const uint8_t mxf_header_partition_pack_key [] = { 0x06,0x0e,0x2b,0x34,0x02,0x05,0x01,0x01,0x0d,0x01,0x02,0x01,0x01,0x02 }
static const uint8_t mxf_essence_element_key [] = { 0x06,0x0e,0x2b,0x34,0x01,0x02,0x01,0x01,0x0d,0x01,0x03,0x01 }
static const uint8_t mxf_avid_essence_element_key [] = { 0x06,0x0e,0x2b,0x34,0x01,0x02,0x01,0x01,0x0e,0x04,0x03,0x01 }
static const uint8_t mxf_canopus_essence_element_key [] = { 0x06,0x0e,0x2b,0x34,0x01,0x02,0x01,0x0a,0x0e,0x0f,0x03,0x01 }
static const uint8_t mxf_system_item_key [] = { 0x06,0x0e,0x2b,0x34,0x02,0x05,0x01,0x01,0x0d,0x01,0x03,0x01,0x04 }
static const uint8_t mxf_klv_key [] = { 0x06,0x0e,0x2b,0x34 }
static const uint8_t mxf_crypto_source_container_ul [] = { 0x06,0x0e,0x2b,0x34,0x01,0x01,0x01,0x09,0x06,0x01,0x01,0x02,0x02,0x00,0x00,0x00 }
static const uint8_t mxf_encrypted_triplet_key [] = { 0x06,0x0e,0x2b,0x34,0x02,0x04,0x01,0x07,0x0d,0x01,0x03,0x01,0x02,0x7e,0x01,0x00 }
static const uint8_t mxf_encrypted_essence_container [] = { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x07,0x0d,0x01,0x03,0x01,0x02,0x0b,0x01,0x00 }
static const uint8_t mxf_random_index_pack_key [] = { 0x06,0x0e,0x2b,0x34,0x02,0x05,0x01,0x01,0x0d,0x01,0x02,0x01,0x01,0x11,0x01,0x00 }
static const uint8_t mxf_sony_mpeg4_extradata [] = { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x01,0x0e,0x06,0x06,0x02,0x02,0x01,0x00,0x00 }
static const uint8_t mxf_avid_project_name [] = { 0xa5,0xfb,0x7b,0x25,0xf6,0x15,0x94,0xb9,0x62,0xfc,0x37,0x17,0x49,0x2d,0x42,0xbf }
static const uint8_t mxf_jp2k_rsiz [] = { 0x06,0x0e,0x2b,0x34,0x02,0x05,0x01,0x01,0x0d,0x01,0x02,0x01,0x01,0x02,0x01,0x00 }
static const uint8_t mxf_indirect_value_utf16le [] = { 0x4c,0x00,0x02,0x10,0x01,0x00,0x00,0x00,0x00,0x06,0x0e,0x2b,0x34,0x01,0x04,0x01,0x01 }
static const uint8_t mxf_indirect_value_utf16be [] = { 0x42,0x01,0x10,0x02,0x00,0x00,0x00,0x00,0x00,0x06,0x0e,0x2b,0x34,0x01,0x04,0x01,0x01 }
static const MXFCodecUL mxf_picture_essence_container_uls []
static const MXFCodecUL mxf_intra_only_essence_container_uls []
static const MXFCodecUL mxf_intra_only_picture_essence_coding_uls []
static const MXFCodecUL mxf_intra_only_picture_coded_width []
static const MXFCodecUL mxf_sound_essence_container_uls []
static const MXFCodecUL mxf_data_essence_container_uls []
static const char *const mxf_data_essence_descriptor []
static const MXFMetadataReadTableEntry mxf_metadata_read_table []
AVInputFormat ff_mxf_demuxer
Macro Definition Documentation
MXF_FIELD_DOMINANCE_DEFAULT
#define MXF_FIELD_DOMINANCE_DEFAULT 0
Definition at line 179 of file mxfdec.c.
Referenced by mxf_parse_structural_metadata().
MXF_FIELD_DOMINANCE_FF
#define MXF_FIELD_DOMINANCE_FF 1 /* coded first, displayed first */
Definition at line 180 of file mxfdec.c.
Referenced by mxf_parse_structural_metadata().
MXF_FIELD_DOMINANCE_FL
#define MXF_FIELD_DOMINANCE_FL 2 /* coded first, displayed last */
Definition at line 181 of file mxfdec.c.
Referenced by mxf_parse_structural_metadata().
IS_KLV_KEY
#define IS_KLV_KEY (x, y) (!memcmp(x, y, sizeof(y)))
Definition at line 305 of file mxfdec.c.
Referenced by mxf_decrypt_triplet(), mxf_parse_structural_metadata(), mxf_read_cryptographic_context(), mxf_read_generic_descriptor(), mxf_read_header(), mxf_read_packet_old(), mxf_read_preface_metadata(), and mxf_read_random_index_pack().
READ_STR16
#define READ_STR16 (type, big_endian)
Value:
static int mxf_read_utf16 ## type ##_string(AVIOContext *pb, int size, char** str) \
{                                                                                  \
return mxf_read_utf16_string(pb, size, str, big_endian);                           \
}
Definition at line 741 of file mxfdec.c.
SET_STR_METADATA
#define SET_STR_METADATA (pb, name, str)
Value:
do { \
    if ((ret = mxf_read_utf16be_string(pb, size, &str)) < 0) \
        return ret; \
    av_dict_set(&s->metadata, name, str, AV_DICT_DONT_STRDUP_VAL); \
} while (0)
Definition at line 2295 of file mxfdec.c.
Referenced by mxf_read_identification_metadata(), and mxf_read_preface_metadata().
SET_UID_METADATA
#define SET_UID_METADATA (pb, name, var, str)
Value:
do { \
    avio_read(pb, var, 16); \
    if ((ret = mxf_uid_to_str(var, &str)) < 0) \
        return ret; \
    av_dict_set(&s->metadata, name, str, AV_DICT_DONT_STRDUP_VAL); \
} while (0)
Definition at line 2301 of file mxfdec.c.
Referenced by mxf_read_identification_metadata().
SET_TS_METADATA
#define SET_TS_METADATA (pb, name, var, str)
Value:
do { \
    var = avio_rb64(pb); \
    if ((ret = avpriv_dict_set_timestamp(&s->metadata, name, mxf_timestamp_to_int64(var)) < 0)) \
        return ret; \
} while (0)
Definition at line 2308 of file mxfdec.c.
Referenced by mxf_read_identification_metadata().
Typedef Documentation
MXFMetadataReadFunc
typedef int MXFMetadataReadFunc(void *arg, AVIOContext *pb, int tag, int size, UID uid, int64_t klv_offset)
Definition at line 276 of file mxfdec.c.
Enumeration Type Documentation
MXFPartitionType
enum MXFPartitionType
Enumerator
Header
BodyPartition
Footer
Definition at line 59 of file mxfdec.c.
MXFOP
enum MXFOP
Enumerator
OP1a
OP1b
OP1c
OP2a
OP2b
OP2c
OP3a
OP3b
OP3c
OPAtom
OPSONYOpt
Definition at line 65 of file mxfdec.c.
MXFWrappingScheme
enum MXFWrappingScheme
Enumerator
Frame
Clip
Definition at line 270 of file mxfdec.c.
Function Documentation
mxf_read_close()
static int mxf_read_close (AVFormatContext * s) static
Definition at line 3225 of file mxfdec.c.
Referenced by mxf_read_header().
mxf_free_metadataset()
static void mxf_free_metadataset (MXFMetadataSet ** ctx, int freectx) static
Definition at line 307 of file mxfdec.c.
Referenced by mxf_handle_missing_index_segment(), mxf_read_close(), and mxf_read_local_tags().
klv_decode_ber_length()
static int64_t klv_decode_ber_length (AVIOContext * pb) static
Definition at line 348 of file mxfdec.c.
Referenced by klv_read_packet(), and mxf_decrypt_triplet().
mxf_read_sync()
static int mxf_read_sync (AVIOContext * pb, const uint8_t * key, unsigned size) static
Definition at line 363 of file mxfdec.c.
Referenced by klv_read_packet(), and mxf_read_header().
klv_read_packet()
static int klv_read_packet (KLVPacket * klv, AVIOContext * pb) static
Definition at line 376 of file mxfdec.c.
Referenced by mxf_read_header(), mxf_read_packet_old(), mxf_read_random_index_pack(), and mxf_seek_to_previous_partition().
mxf_get_stream_index()
static int mxf_get_stream_index (AVFormatContext * s, KLVPacket * klv) static
Definition at line 387 of file mxfdec.c.
Referenced by mxf_decrypt_triplet(), and mxf_read_packet_old().
mxf_get_d10_aes3_packet()
static int mxf_get_d10_aes3_packet (AVIOContext * pb, AVStream * st, AVPacket * pkt, int64_t length) static
Definition at line 402 of file mxfdec.c.
Referenced by mxf_read_packet_old().
mxf_decrypt_triplet()
static int mxf_decrypt_triplet (AVFormatContext * s, AVPacket * pkt, KLVPacket * klv) static
Definition at line 430 of file mxfdec.c.
Referenced by mxf_read_packet_old().
mxf_read_primer_pack()
static int mxf_read_primer_pack (void * arg, AVIOContext * pb, int tag, int size, UID uid, int64_t klv_offset) static
Definition at line 493 of file mxfdec.c.
mxf_read_partition_pack()
static int mxf_read_partition_pack (void * arg, AVIOContext * pb, int tag, int size, UID uid, int64_t klv_offset) static
Definition at line 519 of file mxfdec.c.
Referenced by mxf_seek_to_previous_partition().
mxf_add_metadata_set()
static int mxf_add_metadata_set (MXFContext * mxf, void * metadata_set) static
Definition at line 679 of file mxfdec.c.
Referenced by mxf_handle_missing_index_segment(), and mxf_read_local_tags().
mxf_read_cryptographic_context()
static int mxf_read_cryptographic_context (void * arg, AVIOContext * pb, int tag, int size, UID uid, int64_t klv_offset) static
Definition at line 692 of file mxfdec.c.
mxf_read_strong_ref_array()
static int mxf_read_strong_ref_array (AVIOContext * pb, UID ** refs, int * count) static
Definition at line 702 of file mxfdec.c.
Referenced by mxf_read_content_storage(), mxf_read_essence_group(), mxf_read_generic_descriptor(), mxf_read_package(), and mxf_read_sequence().
mxf_read_utf16_string()
static int mxf_read_utf16_string (AVIOContext * pb, int size, char ** str, int be) inline static
Definition at line 715 of file mxfdec.c.
mxf_read_content_storage()
static int mxf_read_content_storage (void * arg, AVIOContext * pb, int tag, int size, UID uid, int64_t klv_offset) static
Definition at line 750 of file mxfdec.c.
mxf_read_source_clip()
static int mxf_read_source_clip (void * arg, AVIOContext * pb, int tag, int size, UID uid, int64_t klv_offset) static
Definition at line 763 of file mxfdec.c.
mxf_read_timecode_component()
static int mxf_read_timecode_component (void * arg, AVIOContext * pb, int tag, int size, UID uid, int64_t klv_offset) static
Definition at line 785 of file mxfdec.c.
mxf_read_pulldown_component()
static int mxf_read_pulldown_component (void * arg, AVIOContext * pb, int tag, int size, UID uid, int64_t klv_offset) static
Definition at line 802 of file mxfdec.c.
mxf_read_track()
static int mxf_read_track (void * arg, AVIOContext * pb, int tag, int size, UID uid, int64_t klv_offset) static
Definition at line 813 of file mxfdec.c.
mxf_read_sequence()
static int mxf_read_sequence (void * arg, AVIOContext * pb, int tag, int size, UID uid, int64_t klv_offset) static
Definition at line 837 of file mxfdec.c.
mxf_read_essence_group()
static int mxf_read_essence_group (void * arg, AVIOContext * pb, int tag, int size, UID uid, int64_t klv_offset) static
Definition at line 857 of file mxfdec.c.
mxf_read_package()
static int mxf_read_package (void * arg, AVIOContext * pb, int tag, int size, UID uid, int64_t klv_offset) static
Definition at line 871 of file mxfdec.c.
mxf_read_index_entry_array()
static int mxf_read_index_entry_array (AVIOContext * pb, MXFIndexTableSegment * segment) static
Definition at line 895 of file mxfdec.c.
Referenced by mxf_read_index_table_segment().
mxf_read_index_table_segment()
static int mxf_read_index_table_segment (void * arg, AVIOContext * pb, int tag, int size, UID uid, int64_t klv_offset) static
Definition at line 921 of file mxfdec.c.
mxf_read_pixel_layout()
static void mxf_read_pixel_layout (AVIOContext * pb, MXFDescriptor * descriptor) static
Definition at line 958 of file mxfdec.c.
Referenced by mxf_read_generic_descriptor().
mxf_read_generic_descriptor()
static int mxf_read_generic_descriptor (void * arg, AVIOContext * pb, int tag, int size, UID uid, int64_t klv_offset) static
Definition at line 978 of file mxfdec.c.
mxf_read_indirect_value()
static int mxf_read_indirect_value (void * arg, AVIOContext * pb, int size) static
Definition at line 1082 of file mxfdec.c.
Referenced by mxf_read_tagged_value().
mxf_read_tagged_value()
static int mxf_read_tagged_value (void * arg, AVIOContext * pb, int tag, int size, UID uid, int64_t klv_offset) static
Definition at line 1100 of file mxfdec.c.
mxf_match_uid()
static int mxf_match_uid (const UID key, const UID uid, int len) static
Definition at line 1116 of file mxfdec.c.
Referenced by mxf_get_codec_ul().
mxf_get_codec_ul()
static const MXFCodecUL* mxf_get_codec_ul (const MXFCodecUL * uls, UID * uid) static
Definition at line 1126 of file mxfdec.c.
Referenced by mxf_add_metadata_stream(), mxf_is_intra_only(), and mxf_parse_structural_metadata().
mxf_resolve_strong_ref()
static void* mxf_resolve_strong_ref (MXFContext * mxf, UID * strong_ref, enum MXFMetadataSetType type) static
Definition at line 1136 of file mxfdec.c.
Referenced by mxf_parse_package_comments(), mxf_parse_physical_source_package(), mxf_parse_structural_metadata(), mxf_resolve_essence_group_choice(), mxf_resolve_multidescriptor(), mxf_resolve_sourceclip(), and mxf_resolve_timecode_component().
mxf_get_sorted_table_segments()
static int mxf_get_sorted_table_segments (MXFContext * mxf, int * nb_sorted_segments, MXFIndexTableSegment *** sorted_segments) static
Definition at line 1207 of file mxfdec.c.
Referenced by mxf_compute_index_tables().
mxf_absolute_bodysid_offset()
static int mxf_absolute_bodysid_offset (MXFContext * mxf, int body_sid, int64_t offset, int64_t * offset_out) static
Computes the absolute file offset of the given essence container offset.
Definition at line 1275 of file mxfdec.c.
Referenced by mxf_edit_unit_absolute_offset().
mxf_essence_container_end()
static int64_t mxf_essence_container_end (MXFContext * mxf, int body_sid) static
Returns the end position of the essence container with given BodySID, or zero if unknown.
Definition at line 1304 of file mxfdec.c.
Referenced by mxf_read_packet().
mxf_edit_unit_absolute_offset()
static int mxf_edit_unit_absolute_offset (MXFContext * mxf, MXFIndexTable * index_table, int64_t edit_unit, int64_t * edit_unit_out, int64_t * offset_out, int nag) static
Definition at line 1325 of file mxfdec.c.
Referenced by mxf_read_packet(), mxf_read_seek(), and mxf_set_current_edit_unit().
mxf_compute_ptses_fake_index()
static int mxf_compute_ptses_fake_index (MXFContext * mxf, MXFIndexTable * index_table) static
We have this:
x TemporalOffset 0: 0 1: 1 2: 1 3: -2 4: 1 5: 1 6: -2
We want to transform it into this:
x DTS PTS 0: -1 0 1: 0 3 2: 1 1 3: 2 2 4: 3 6 5: 4 4 6: 5 5
We do this by bucket sorting x by x+TemporalOffset[x] into mxf->ptses, then settings mxf->first_dts = -max(TemporalOffset[x]). The latter makes DTS <= PTS.
Definition at line 1373 of file mxfdec.c.
Referenced by mxf_compute_index_tables().
mxf_compute_index_tables()
static int mxf_compute_index_tables (MXFContext * mxf) static
Sorts and collects index table segments into index tables.
Also computes PTSes if possible.
Definition at line 1491 of file mxfdec.c.
Referenced by mxf_read_header().
mxf_is_intra_only()
static int mxf_is_intra_only (MXFDescriptor * descriptor) static
Definition at line 1591 of file mxfdec.c.
Referenced by mxf_parse_structural_metadata().
mxf_uid_to_str()
static int mxf_uid_to_str (UID uid, char ** str) static
Definition at line 1599 of file mxfdec.c.
mxf_umid_to_str()
static int mxf_umid_to_str (UID ul, UID uid, char ** str) static
Definition at line 1617 of file mxfdec.c.
Referenced by mxf_add_umid_metadata().
mxf_add_umid_metadata()
static int mxf_add_umid_metadata (AVDictionary ** pm, const char * key, MXFPackage * package) static
Definition at line 1638 of file mxfdec.c.
Referenced by mxf_add_metadata_stream(), mxf_parse_physical_source_package(), and mxf_parse_structural_metadata().
mxf_add_timecode_metadata()
static int mxf_add_timecode_metadata (AVDictionary ** pm, const char * key, AVTimecode * tc) static
Definition at line 1650 of file mxfdec.c.
Referenced by mxf_parse_physical_source_package(), and mxf_parse_structural_metadata().
mxf_resolve_timecode_component()
static MXFTimecodeComponent* mxf_resolve_timecode_component (MXFContext * mxf, UID * strong_ref) static
Definition at line 1658 of file mxfdec.c.
Referenced by mxf_parse_physical_source_package().
mxf_resolve_source_package()
static MXFPackage* mxf_resolve_source_package (MXFContext * mxf, UID package_uid) static
Definition at line 1679 of file mxfdec.c.
Referenced by mxf_parse_physical_source_package(), mxf_parse_structural_metadata(), and mxf_resolve_essence_group_choice().
mxf_resolve_multidescriptor()
static MXFDescriptor* mxf_resolve_multidescriptor (MXFContext * mxf, MXFDescriptor * descriptor, int track_id) static
Definition at line 1695 of file mxfdec.c.
Referenced by mxf_parse_structural_metadata().
mxf_resolve_essence_group_choice()
static MXFStructuralComponent* mxf_resolve_essence_group_choice (MXFContext * mxf, MXFEssenceGroup * essence_group) static
Definition at line 1721 of file mxfdec.c.
Referenced by mxf_resolve_sourceclip().
mxf_resolve_sourceclip()
static MXFStructuralComponent* mxf_resolve_sourceclip (MXFContext * mxf, UID * strong_ref) static
Definition at line 1748 of file mxfdec.c.
Referenced by mxf_add_metadata_stream(), and mxf_parse_structural_metadata().
mxf_parse_package_comments()
static int mxf_parse_package_comments (MXFContext * mxf, AVDictionary ** pm, MXFPackage * package) static
Definition at line 1766 of file mxfdec.c.
Referenced by mxf_parse_structural_metadata().
mxf_parse_physical_source_package()
static int mxf_parse_physical_source_package (MXFContext * mxf, MXFTrack * source_track, AVStream * st) static
Definition at line 1788 of file mxfdec.c.
Referenced by mxf_parse_structural_metadata().
mxf_add_metadata_stream()
static int mxf_add_metadata_stream (MXFContext * mxf, MXFTrack * track) static
Definition at line 1858 of file mxfdec.c.
Referenced by mxf_parse_structural_metadata().
mxf_parse_structural_metadata()
static int mxf_parse_structural_metadata (MXFContext * mxf) static
Definition at line 1896 of file mxfdec.c.
Referenced by mxf_read_header().
mxf_timestamp_to_int64()
static int64_t mxf_timestamp_to_int64 (uint64_t timestamp) static
Definition at line 2273 of file mxfdec.c.
mxf_read_identification_metadata()
static int mxf_read_identification_metadata (void * arg, AVIOContext * pb, int tag, int size, UID _uid, int64_t klv_offset) static
Definition at line 2314 of file mxfdec.c.
mxf_read_preface_metadata()
static int mxf_read_preface_metadata (void * arg, AVIOContext * pb, int tag, int size, UID uid, int64_t klv_offset) static
Definition at line 2351 of file mxfdec.c.
mxf_metadataset_init()
static int mxf_metadataset_init (MXFMetadataSet * ctx, enum MXFMetadataSetType type) static
Definition at line 2403 of file mxfdec.c.
Referenced by mxf_read_local_tags().
mxf_read_local_tags()
static int mxf_read_local_tags (MXFContext * mxf, KLVPacket * klv, MXFMetadataReadFunc * read_child, int ctx_size, enum MXFMetadataSetType type) static
Definition at line 2417 of file mxfdec.c.
Referenced by mxf_parse_klv().
mxf_is_partition_pack_key()
static int mxf_is_partition_pack_key (UID key) static
Matches any partition pack key, in other words:
HeaderPartition
BodyPartition
FooterPartition
Returns
non-zero if the key is a partition pack key, zero otherwise
Definition at line 2482 of file mxfdec.c.
Referenced by mxf_read_header(), and mxf_seek_to_previous_partition().
mxf_parse_klv()
static int mxf_parse_klv (MXFContext * mxf, KLVPacket klv, MXFMetadataReadFunc * read, int ctx_size, enum MXFMetadataSetType type) static
Parses a metadata KLV.
Returns
<0 on error, 0 otherwise
Definition at line 2493 of file mxfdec.c.
Referenced by mxf_read_header(), and mxf_seek_to_previous_partition().
mxf_seek_to_previous_partition()
static int mxf_seek_to_previous_partition (MXFContext * mxf) static
Seeks to the previous partition and parses it, if possible.
Returns
<= 0 if we should stop parsing, > 0 if we should keep going
Definition at line 2524 of file mxfdec.c.
Referenced by mxf_parse_handle_essence(), and mxf_parse_handle_partition_or_eof().
mxf_parse_handle_essence()
static int mxf_parse_handle_essence (MXFContext * mxf) static
Called when essence is encountered.
Returns
<= 0 if we should stop parsing, > 0 if we should keep going
Definition at line 2575 of file mxfdec.c.
Referenced by mxf_read_header().
mxf_parse_handle_partition_or_eof()
static int mxf_parse_handle_partition_or_eof (MXFContext * mxf) static
Called when the next partition or EOF is encountered.
Returns
<= 0 if we should stop parsing, > 0 if we should keep going
Definition at line 2618 of file mxfdec.c.
Referenced by mxf_read_header().
mxf_compute_essence_containers()
static void mxf_compute_essence_containers (MXFContext * mxf) static
Figures out the proper offset and length of the essence container in each partition.
Definition at line 2626 of file mxfdec.c.
Referenced by mxf_read_header().
round_to_kag()
static int64_t round_to_kag (int64_t position, int kag_size) static
Definition at line 2656 of file mxfdec.c.
Referenced by mxf_read_header().
is_pcm()
static int is_pcm (enum AVCodecID codec_id) static
Definition at line 2664 of file mxfdec.c.
Referenced by mxf_handle_missing_index_segment(), and mxf_handle_small_eubc().
mxf_get_opatom_stream()
static AVStream* mxf_get_opatom_stream (MXFContext * mxf) static
Definition at line 2670 of file mxfdec.c.
Referenced by mxf_handle_missing_index_segment(), mxf_handle_small_eubc(), and mxf_read_packet().
mxf_handle_small_eubc()
static void mxf_handle_small_eubc (AVFormatContext * s) static
Deal with the case where for some audio atoms EditUnitByteCount is very small (2, 4..).
In those cases we should read more than one sample per call to mxf_read_packet().
Definition at line 2690 of file mxfdec.c.
Referenced by mxf_read_header().
mxf_handle_missing_index_segment()
static int mxf_handle_missing_index_segment (MXFContext * mxf) static
Deal with the case where OPAtom files does not have any IndexTableSegments.
Definition at line 2718 of file mxfdec.c.
Referenced by mxf_read_header().
mxf_read_random_index_pack()
static void mxf_read_random_index_pack (AVFormatContext * s) static
Definition at line 2773 of file mxfdec.c.
Referenced by mxf_read_header().
mxf_read_header()
static int mxf_read_header (AVFormatContext * s) static
Definition at line 2824 of file mxfdec.c.
mxf_set_current_edit_unit()
static int64_t mxf_set_current_edit_unit (MXFContext * mxf, int64_t current_offset) static
Sets mxf->current_edit_unit based on what offset we're currently at.
Returns
next_ofs if OK, <0 on error
Definition at line 2962 of file mxfdec.c.
Referenced by mxf_read_packet_old().
mxf_compute_sample_count()
static int mxf_compute_sample_count (MXFContext * mxf, int stream_index, uint64_t * sample_count) static
Definition at line 2999 of file mxfdec.c.
Referenced by mxf_read_seek().
mxf_set_audio_pts()
static int mxf_set_audio_pts (MXFContext * mxf, AVCodecParameters * par, AVPacket * pkt) static
Definition at line 3040 of file mxfdec.c.
Referenced by mxf_read_packet(), and mxf_read_packet_old().
mxf_read_packet_old()
static int mxf_read_packet_old (AVFormatContext * s, AVPacket * pkt) static
Definition at line 3059 of file mxfdec.c.
Referenced by mxf_read_packet().
mxf_read_packet()
static int mxf_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 3160 of file mxfdec.c.
mxf_probe()
static int mxf_probe (AVProbeData * p) static
Definition at line 3256 of file mxfdec.c.
mxf_read_seek()
static int mxf_read_seek (AVFormatContext * s, int stream_index, int64_t sample_time, int flags) static
Definition at line 3283 of file mxfdec.c.
Variable Documentation
mxf_header_partition_pack_key
const uint8_t mxf_header_partition_pack_key[] = { 0x06,0x0e,0x2b,0x34,0x02,0x05,0x01,0x01,0x0d,0x01,0x02,0x01,0x01,0x02 } static
Definition at line 288 of file mxfdec.c.
Referenced by mxf_is_partition_pack_key(), mxf_probe(), and mxf_read_header().
mxf_essence_element_key
const uint8_t mxf_essence_element_key[] = { 0x06,0x0e,0x2b,0x34,0x01,0x02,0x01,0x01,0x0d,0x01,0x03,0x01 } static
Definition at line 289 of file mxfdec.c.
Referenced by mxf_decrypt_triplet(), mxf_get_stream_index(), mxf_read_header(), and mxf_read_packet_old().
mxf_avid_essence_element_key
const uint8_t mxf_avid_essence_element_key[] = { 0x06,0x0e,0x2b,0x34,0x01,0x02,0x01,0x01,0x0e,0x04,0x03,0x01 } static
Definition at line 290 of file mxfdec.c.
Referenced by mxf_read_header(), and mxf_read_packet_old().
mxf_canopus_essence_element_key
const uint8_t mxf_canopus_essence_element_key[] = { 0x06,0x0e,0x2b,0x34,0x01,0x02,0x01,0x0a,0x0e,0x0f,0x03,0x01 } static
Definition at line 291 of file mxfdec.c.
Referenced by mxf_read_packet_old().
mxf_system_item_key
const uint8_t mxf_system_item_key[] = { 0x06,0x0e,0x2b,0x34,0x02,0x05,0x01,0x01,0x0d,0x01,0x03,0x01,0x04 } static
Definition at line 292 of file mxfdec.c.
Referenced by mxf_read_header().
mxf_klv_key
const uint8_t mxf_klv_key[] = { 0x06,0x0e,0x2b,0x34 } static
Definition at line 293 of file mxfdec.c.
Referenced by klv_read_packet().
mxf_crypto_source_container_ul
const uint8_t mxf_crypto_source_container_ul[] = { 0x06,0x0e,0x2b,0x34,0x01,0x01,0x01,0x09,0x06,0x01,0x01,0x02,0x02,0x00,0x00,0x00 } static
Definition at line 295 of file mxfdec.c.
Referenced by mxf_read_cryptographic_context().
mxf_encrypted_triplet_key
const uint8_t mxf_encrypted_triplet_key[] = { 0x06,0x0e,0x2b,0x34,0x02,0x04,0x01,0x07,0x0d,0x01,0x03,0x01,0x02,0x7e,0x01,0x00 } static
Definition at line 296 of file mxfdec.c.
Referenced by mxf_read_header(), and mxf_read_packet_old().
mxf_encrypted_essence_container
const uint8_t mxf_encrypted_essence_container[] = { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x07,0x0d,0x01,0x03,0x01,0x02,0x0b,0x01,0x00 } static
Definition at line 297 of file mxfdec.c.
Referenced by mxf_parse_structural_metadata().
mxf_random_index_pack_key
const uint8_t mxf_random_index_pack_key[] = { 0x06,0x0e,0x2b,0x34,0x02,0x05,0x01,0x01,0x0d,0x01,0x02,0x01,0x01,0x11,0x01,0x00 } static
Definition at line 298 of file mxfdec.c.
Referenced by mxf_read_random_index_pack().
mxf_sony_mpeg4_extradata
const uint8_t mxf_sony_mpeg4_extradata[] = { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x01,0x0e,0x06,0x06,0x02,0x02,0x01,0x00,0x00 } static
Definition at line 299 of file mxfdec.c.
Referenced by mxf_read_generic_descriptor().
mxf_avid_project_name
const uint8_t mxf_avid_project_name[] = { 0xa5,0xfb,0x7b,0x25,0xf6,0x15,0x94,0xb9,0x62,0xfc,0x37,0x17,0x49,0x2d,0x42,0xbf } static
Definition at line 300 of file mxfdec.c.
Referenced by mxf_read_preface_metadata().
mxf_jp2k_rsiz
const uint8_t mxf_jp2k_rsiz[] = { 0x06,0x0e,0x2b,0x34,0x02,0x05,0x01,0x01,0x0d,0x01,0x02,0x01,0x01,0x02,0x01,0x00 } static
Definition at line 301 of file mxfdec.c.
Referenced by mxf_read_generic_descriptor().
mxf_indirect_value_utf16le
const uint8_t mxf_indirect_value_utf16le[] = { 0x4c,0x00,0x02,0x10,0x01,0x00,0x00,0x00,0x00,0x06,0x0e,0x2b,0x34,0x01,0x04,0x01,0x01 } static
Definition at line 302 of file mxfdec.c.
Referenced by mxf_read_indirect_value().
mxf_indirect_value_utf16be
const uint8_t mxf_indirect_value_utf16be[] = { 0x42,0x01,0x10,0x02,0x00,0x00,0x00,0x00,0x00,0x06,0x0e,0x2b,0x34,0x01,0x04,0x01,0x01 } static
Definition at line 303 of file mxfdec.c.
Referenced by mxf_read_indirect_value().
mxf_picture_essence_container_uls
const MXFCodecUL mxf_picture_essence_container_uls[] static
Initial value:
= {
    { { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x07,0x0d,0x01,0x03,0x01,0x02,0x0c,0x01,0x00 }, 14,   AV_CODEC_ID_JPEG2000 },
    { { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x02,0x0d,0x01,0x03,0x01,0x02,0x10,0x60,0x01 }, 14,       AV_CODEC_ID_H264 },
    { { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x02,0x0d,0x01,0x03,0x01,0x02,0x12,0x01,0x00 }, 14,        AV_CODEC_ID_VC1 },
    { { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x02,0x0d,0x01,0x03,0x01,0x02,0x04,0x60,0x01 }, 14, AV_CODEC_ID_MPEG2VIDEO },
    { { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x01,0x0d,0x01,0x03,0x01,0x02,0x01,0x04,0x01 }, 14, AV_CODEC_ID_MPEG2VIDEO },
    { { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x01,0x0d,0x01,0x03,0x01,0x02,0x02,0x41,0x01 }, 14,    AV_CODEC_ID_DVVIDEO },
    { { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x01,0x0d,0x01,0x03,0x01,0x02,0x05,0x00,0x00 }, 14,   AV_CODEC_ID_RAWVIDEO },
    { { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x0a,0x0e,0x0f,0x03,0x01,0x02,0x20,0x01,0x01 }, 15,     AV_CODEC_ID_HQ_HQA },
    { { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x0a,0x0e,0x0f,0x03,0x01,0x02,0x20,0x02,0x01 }, 15,        AV_CODEC_ID_HQX },
    { { 0x06,0x0e,0x2b,0x34,0x01,0x01,0x01,0xff,0x4b,0x46,0x41,0x41,0x00,0x0d,0x4d,0x4f }, 14,   AV_CODEC_ID_RAWVIDEO },
    { { 0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00 },  0,      AV_CODEC_ID_NONE },
}
Definition at line 1151 of file mxfdec.c.
mxf_intra_only_essence_container_uls
const MXFCodecUL mxf_intra_only_essence_container_uls[] static
Initial value:
= {
    { { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x01,0x0d,0x01,0x03,0x01,0x02,0x01,0x00,0x00 }, 14, AV_CODEC_ID_MPEG2VIDEO },
    { { 0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00 },  0,       AV_CODEC_ID_NONE },
}
Definition at line 1167 of file mxfdec.c.
mxf_intra_only_picture_essence_coding_uls
const MXFCodecUL mxf_intra_only_picture_essence_coding_uls[] static
Initial value:
= {
    { { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x0A,0x04,0x01,0x02,0x02,0x01,0x32,0x00,0x00 }, 14,       AV_CODEC_ID_H264 },
    { { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x07,0x04,0x01,0x02,0x02,0x03,0x01,0x01,0x00 }, 14,   AV_CODEC_ID_JPEG2000 },
    { { 0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00 },  0,       AV_CODEC_ID_NONE },
}
Definition at line 1173 of file mxfdec.c.
mxf_intra_only_picture_coded_width
const MXFCodecUL mxf_intra_only_picture_coded_width[] static
Initial value:
= {
    { { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x0A,0x04,0x01,0x02,0x02,0x01,0x32,0x21,0x01 }, 16, 1440 },
    { { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x0A,0x04,0x01,0x02,0x02,0x01,0x32,0x21,0x02 }, 16, 1440 },
    { { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x0A,0x04,0x01,0x02,0x02,0x01,0x32,0x21,0x03 }, 16, 1440 },
    { { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x0A,0x04,0x01,0x02,0x02,0x01,0x32,0x21,0x04 }, 16, 1440 },
    { { 0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00 },  0,    0 },
}
Definition at line 1180 of file mxfdec.c.
mxf_sound_essence_container_uls
const MXFCodecUL mxf_sound_essence_container_uls[] static
Initial value:
= {
    { { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x01,0x0d,0x01,0x03,0x01,0x02,0x06,0x01,0x00 }, 14, AV_CODEC_ID_PCM_S16LE },
    { { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x02,0x0d,0x01,0x03,0x01,0x02,0x04,0x40,0x01 }, 14,       AV_CODEC_ID_MP2 },
    { { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x01,0x0d,0x01,0x03,0x01,0x02,0x01,0x01,0x01 }, 14, AV_CODEC_ID_PCM_S16LE },
    { { 0x06,0x0e,0x2b,0x34,0x01,0x01,0x01,0xff,0x4b,0x46,0x41,0x41,0x00,0x0d,0x4d,0x4F }, 14, AV_CODEC_ID_PCM_S16LE },
    { { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x03,0x04,0x02,0x02,0x02,0x03,0x03,0x01,0x00 }, 14,       AV_CODEC_ID_AAC },
    { { 0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00 },  0,      AV_CODEC_ID_NONE },
}
Definition at line 1188 of file mxfdec.c.
mxf_data_essence_container_uls
const MXFCodecUL mxf_data_essence_container_uls[] static
Initial value:
= {
    { { 0x06,0x0e,0x2b,0x34,0x04,0x01,0x01,0x09,0x0d,0x01,0x03,0x01,0x02,0x0e,0x00,0x00 }, 16, 0 },
    { { 0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00 },  0, AV_CODEC_ID_NONE },
}
Definition at line 1198 of file mxfdec.c.
mxf_data_essence_descriptor
const char* const mxf_data_essence_descriptor[] static
Initial value:
= {
    "vbi_vanc_smpte_436M",
}
Definition at line 1203 of file mxfdec.c.
mxf_metadata_read_table
const MXFMetadataReadTableEntry mxf_metadata_read_table[] static
Definition at line 2364 of file mxfdec.c.
ff_mxf_demuxer
AVInputFormat ff_mxf_demuxer
Initial value:
= {
    .name           = "mxf",
    .long_name      = NULL_IF_CONFIG_SMALL("MXF (Material eXchange Format)"),
    .flags          = AVFMT_SEEK_TO_PTS,
    .priv_data_size = sizeof(MXFContext),
    .read_probe     = mxf_probe,
    .read_header    = mxf_read_header,
    .read_packet    = mxf_read_packet,
    .read_close     = mxf_read_close,
    .read_seek      = mxf_read_seek,
}
Definition at line 3367 of file mxfdec.c.