FFmpeg: libavformat/mxfenc.c File Reference
mxfenc.c File Reference
#include <inttypes.h>
#include <math.h>
#include <time.h>
#include "libavutil/opt.h"
#include "libavutil/random_seed.h"
#include "libavutil/timecode.h"
#include "libavutil/avassert.h"
#include "libavutil/pixdesc.h"
#include "libavutil/time_internal.h"
#include "libavcodec/bytestream.h"
#include "libavcodec/dnxhddata.h"
#include "libavcodec/h264.h"
#include "libavcodec/internal.h"
#include "audiointerleave.h"
#include "avformat.h"
#include "avio_internal.h"
#include "internal.h"
#include "mxf.h"
#include "config.h"
Data Structures
struct MXFLocalTagPair
struct MXFIndexEntry
struct MXFStreamContext
struct MXFContainerEssenceEntry
struct MXFContext
Macros
#define EDIT_UNITS_PER_BODY 250
#define KAG_SIZE 512
#define DESCRIPTOR_COUNT(essence_container_count) (essence_container_count > 1 ? essence_container_count + 1 : essence_container_count)
#define MXF_COMMON_OPTIONS
Functions
static void mxf_write_wav_desc (AVFormatContext *s, AVStream *st)
static void mxf_write_aes3_desc (AVFormatContext *s, AVStream *st)
static void mxf_write_mpegvideo_desc (AVFormatContext *s, AVStream *st)
static void mxf_write_cdci_desc (AVFormatContext *s, AVStream *st)
static void mxf_write_generic_sound_desc (AVFormatContext *s, AVStream *st)
static void mxf_write_uuid (AVIOContext *pb, enum MXFMetadataSetType type, int value)
static void mxf_write_umid (AVFormatContext *s, int type)
static void mxf_write_refs_count (AVIOContext *pb, int ref_count)
static int klv_ber_length (uint64_t len)
static int klv_encode_ber_length (AVIOContext *pb, uint64_t len)
static void klv_encode_ber4_length (AVIOContext *pb, int len)
static void klv_encode_ber9_length (AVIOContext *pb, uint64_t len)
static int mxf_get_essence_container_ul_index (enum AVCodecID id)
static void mxf_write_primer_pack (AVFormatContext *s)
static void mxf_write_local_tag (AVIOContext *pb, int size, int tag)
static void mxf_write_metadata_key (AVIOContext *pb, unsigned int value)
static void mxf_free (AVFormatContext *s)
static const MXFCodecUL * mxf_get_data_definition_ul (int type)
static void mxf_write_essence_container_refs (AVFormatContext *s)
static void mxf_write_preface (AVFormatContext *s)
static uint64_t mxf_utf16len (const char *utf8_str)
static int mxf_utf16_local_tag_length (const char *utf8_str)
static void mxf_write_local_tag_utf16 (AVIOContext *pb, int tag, const char *value)
static void mxf_write_identification (AVFormatContext *s)
static void mxf_write_content_storage (AVFormatContext *s)
static void mxf_write_track (AVFormatContext *s, AVStream *st, enum MXFMetadataSetType type)
static void mxf_write_common_fields (AVFormatContext *s, AVStream *st)
static void mxf_write_sequence (AVFormatContext *s, AVStream *st, enum MXFMetadataSetType type)
static void mxf_write_timecode_component (AVFormatContext *s, AVStream *st, enum MXFMetadataSetType type)
static void mxf_write_structural_component (AVFormatContext *s, AVStream *st, enum MXFMetadataSetType type)
static void mxf_write_multi_descriptor (AVFormatContext *s)
static void mxf_write_generic_desc (AVFormatContext *s, AVStream *st, const UID key, unsigned size)
static void mxf_write_cdci_common (AVFormatContext *s, AVStream *st, const UID key, unsigned size)
static void mxf_write_generic_sound_common (AVFormatContext *s, AVStream *st, const UID key, unsigned size)
static void mxf_write_wav_common (AVFormatContext *s, AVStream *st, const UID key, unsigned size)
static int mxf_write_tagged_value (AVFormatContext *s, const char *name, const char *value)
static int mxf_write_user_comments (AVFormatContext *s, const AVDictionary *m)
static void mxf_write_package (AVFormatContext *s, enum MXFMetadataSetType type, const char *package_name)
static int mxf_write_essence_container_data (AVFormatContext *s)
static int mxf_write_header_metadata_sets (AVFormatContext *s)
static unsigned klv_fill_size (uint64_t size)
static void mxf_write_index_table_segment (AVFormatContext *s)
static void mxf_write_klv_fill (AVFormatContext *s)
static int mxf_write_partition (AVFormatContext *s, int bodysid, int indexsid, const uint8_t *key, int write_metadata)
static int mxf_parse_dnxhd_frame (AVFormatContext *s, AVStream *st, AVPacket *pkt)
static int mxf_parse_dv_frame (AVFormatContext *s, AVStream *st, AVPacket *pkt)
static int mxf_parse_h264_frame (AVFormatContext *s, AVStream *st, AVPacket *pkt, MXFIndexEntry *e)
static const UID * mxf_get_mpeg2_codec_ul (AVCodecParameters *par)
static int mxf_parse_mpeg2_frame (AVFormatContext *s, AVStream *st, AVPacket *pkt, MXFIndexEntry *e)
static uint64_t mxf_parse_timestamp (time_t timestamp)
static void mxf_gen_umid (AVFormatContext *s)
static int mxf_init_timecode (AVFormatContext *s, AVStream *st, AVRational rate)
static int mxf_write_header (AVFormatContext *s)
static void mxf_write_system_item (AVFormatContext *s)
static void mxf_write_d10_video_packet (AVFormatContext *s, AVStream *st, AVPacket *pkt)
static void mxf_write_d10_audio_packet (AVFormatContext *s, AVStream *st, AVPacket *pkt)
static int mxf_write_opatom_body_partition (AVFormatContext *s)
static int mxf_write_opatom_packet (AVFormatContext *s, AVPacket *pkt, MXFIndexEntry *ie)
static int mxf_write_packet (AVFormatContext *s, AVPacket *pkt)
static void mxf_write_random_index_pack (AVFormatContext *s)
static int mxf_write_footer (AVFormatContext *s)
static int mxf_interleave_get_packet (AVFormatContext *s, AVPacket *out, AVPacket *pkt, int flush)
static int mxf_compare_timestamps (AVFormatContext *s, AVPacket *next, AVPacket *pkt)
static int mxf_interleave (AVFormatContext *s, AVPacket *out, AVPacket *pkt, int flush)
Variables
AVOutputFormat ff_mxf_d10_muxer
AVOutputFormat ff_mxf_opatom_muxer
struct {
enum AVCodecID id
int index
} mxf_essence_mappings []
static const MXFContainerEssenceEntry mxf_essence_container_uls []
static const uint8_t uuid_base [] = { 0xAD,0xAB,0x44,0x24,0x2f,0x25,0x4d,0xc7,0x92,0xff,0x29,0xbd }
static const uint8_t umid_ul [] = { 0x06,0x0A,0x2B,0x34,0x01,0x01,0x01,0x05,0x01,0x01,0x0D,0x00,0x13 }
static const uint8_t op1a_ul [] = { 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x01,0x0D,0x01,0x02,0x01,0x01,0x01,0x09,0x00 }
complete key for operation pattern, partitions, and primer pack
static const uint8_t opatom_ul [] = { 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x02,0x0D,0x01,0x02,0x01,0x10,0x03,0x00,0x00 }
static const uint8_t footer_partition_key [] = { 0x06,0x0E,0x2B,0x34,0x02,0x05,0x01,0x01,0x0D,0x01,0x02,0x01,0x01,0x04,0x04,0x00 }
static const uint8_t primer_pack_key [] = { 0x06,0x0E,0x2B,0x34,0x02,0x05,0x01,0x01,0x0D,0x01,0x02,0x01,0x01,0x05,0x01,0x00 }
static const uint8_t index_table_segment_key [] = { 0x06,0x0E,0x2B,0x34,0x02,0x53,0x01,0x01,0x0d,0x01,0x02,0x01,0x01,0x10,0x01,0x00 }
static const uint8_t random_index_pack_key [] = { 0x06,0x0E,0x2B,0x34,0x02,0x05,0x01,0x01,0x0D,0x01,0x02,0x01,0x01,0x11,0x01,0x00 }
static const uint8_t header_open_partition_key [] = { 0x06,0x0E,0x2B,0x34,0x02,0x05,0x01,0x01,0x0D,0x01,0x02,0x01,0x01,0x02,0x01,0x00 }
static const uint8_t header_closed_partition_key [] = { 0x06,0x0E,0x2B,0x34,0x02,0x05,0x01,0x01,0x0D,0x01,0x02,0x01,0x01,0x02,0x04,0x00 }
static const uint8_t klv_fill_key [] = { 0x06,0x0E,0x2B,0x34,0x01,0x01,0x01,0x02,0x03,0x01,0x02,0x10,0x01,0x00,0x00,0x00 }
static const uint8_t body_partition_key [] = { 0x06,0x0E,0x2B,0x34,0x02,0x05,0x01,0x01,0x0D,0x01,0x02,0x01,0x01,0x03,0x04,0x00 }
static const uint8_t header_metadata_key [] = { 0x06,0x0E,0x2B,0x34,0x02,0x53,0x01,0x01,0x0D,0x01,0x01,0x01,0x01 }
partial key for header metadata
static const uint8_t multiple_desc_ul [] = { 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x03,0x0D,0x01,0x03,0x01,0x02,0x7F,0x01,0x00 }
static const MXFLocalTagPair mxf_local_tag_batch []
SMPTE RP210 http://www.smpte-ra.org/mdd/index.html https://smpte-ra.org/sites/default/files/Labels.xml.
static const MXFLocalTagPair mxf_user_comments_local_tag []
static const uint8_t smpte_12m_timecode_track_data_ul [] = { 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x01,0x01,0x03,0x02,0x01,0x01,0x00,0x00,0x00 }
static const UID mxf_mpegvideo_descriptor_key = { 0x06,0x0E,0x2B,0x34,0x02,0x53,0x01,0x01,0x0d,0x01,0x01,0x01,0x01,0x01,0x51,0x00 }
static const UID mxf_wav_descriptor_key = { 0x06,0x0E,0x2B,0x34,0x02,0x53,0x01,0x01,0x0d,0x01,0x01,0x01,0x01,0x01,0x48,0x00 }
static const UID mxf_aes3_descriptor_key = { 0x06,0x0E,0x2B,0x34,0x02,0x53,0x01,0x01,0x0d,0x01,0x01,0x01,0x01,0x01,0x47,0x00 }
static const UID mxf_cdci_descriptor_key = { 0x06,0x0E,0x2B,0x34,0x02,0x53,0x01,0x01,0x0D,0x01,0x01,0x01,0x01,0x01,0x28,0x00 }
static const UID mxf_generic_sound_descriptor_key = { 0x06,0x0E,0x2B,0x34,0x02,0x53,0x01,0x01,0x0D,0x01,0x01,0x01,0x01,0x01,0x42,0x00 }
static const uint8_t mxf_indirect_value_utf16le [] = { 0x4c,0x00,0x02,0x10,0x01,0x00,0x00,0x00,0x00,0x06,0x0e,0x2b,0x34,0x01,0x04,0x01,0x01 }
struct {
UID uid
int frame_size
int profile
uint8_t interlaced
} mxf_h264_codec_uls []
static const UID mxf_mpeg2_codec_uls []
static const uint8_t system_metadata_pack_key [] = { 0x06,0x0E,0x2B,0x34,0x02,0x05,0x01,0x01,0x0D,0x01,0x03,0x01,0x04,0x01,0x01,0x00 }
static const uint8_t system_metadata_package_set_key [] = { 0x06,0x0E,0x2B,0x34,0x02,0x43,0x01,0x01,0x0D,0x01,0x03,0x01,0x04,0x01,0x02,0x01 }
static const AVOption mxf_options []
static const AVClass mxf_muxer_class
static const AVOption d10_options []
static const AVClass mxf_d10_muxer_class
static const AVOption opatom_options []
static const AVClass mxf_opatom_muxer_class
AVOutputFormat ff_mxf_muxer
Macro Definition Documentation
EDIT_UNITS_PER_BODY
#define EDIT_UNITS_PER_BODY 250
Definition at line 63 of file mxfenc.c.
Referenced by mxf_write_packet().
KAG_SIZE
#define KAG_SIZE 512
Definition at line 64 of file mxfenc.c.
Referenced by klv_fill_size(), mxf_parse_dnxhd_frame(), mxf_parse_dv_frame(), mxf_write_d10_video_packet(), mxf_write_header(), mxf_write_index_table_segment(), mxf_write_klv_fill(), mxf_write_packet(), and mxf_write_partition().
DESCRIPTOR_COUNT
#define DESCRIPTOR_COUNT (essence_container_count) (essence_container_count > 1 ? essence_container_count + 1 : essence_container_count)
Definition at line 591 of file mxfenc.c.
Referenced by mxf_write_essence_container_refs(), mxf_write_partition(), and mxf_write_preface().
MXF_COMMON_OPTIONS
#define MXF_COMMON_OPTIONS
Value:
{ "signal_standard", "Force/set Sigal Standard",\
      offsetof(MXFContext, signal_standard), AV_OPT_TYPE_INT, {.i64 = -1}, -1, 7, AV_OPT_FLAG_ENCODING_PARAM, "signal_standard"},\
    { "bt601", "ITU-R BT.601 and BT.656, also SMPTE 125M (525 and 625 line interlaced)",\
      0, AV_OPT_TYPE_CONST, {.i64 = 1}, -1, 7, AV_OPT_FLAG_ENCODING_PARAM, "signal_standard"},\
    { "bt1358", "ITU-R BT.1358 and ITU-R BT.799-3, also SMPTE 293M (525 and 625 line progressive)",\
      0, AV_OPT_TYPE_CONST, {.i64 = 2}, -1, 7, AV_OPT_FLAG_ENCODING_PARAM, "signal_standard"},\
    { "smpte347m", "SMPTE 347M (540 Mbps mappings)",\
      0, AV_OPT_TYPE_CONST, {.i64 = 3}, -1, 7, AV_OPT_FLAG_ENCODING_PARAM, "signal_standard"},\
    { "smpte274m", "SMPTE 274M (1125 line)",\
      0, AV_OPT_TYPE_CONST, {.i64 = 4}, -1, 7, AV_OPT_FLAG_ENCODING_PARAM, "signal_standard"},\
    { "smpte296m", "SMPTE 296M (750 line progressive)",\
      0, AV_OPT_TYPE_CONST, {.i64 = 5}, -1, 7, AV_OPT_FLAG_ENCODING_PARAM, "signal_standard"},\
    { "smpte349m", "SMPTE 349M (1485 Mbps mappings)",\
      0, AV_OPT_TYPE_CONST, {.i64 = 6}, -1, 7, AV_OPT_FLAG_ENCODING_PARAM, "signal_standard"},\
    { "smpte428", "SMPTE 428-1 DCDM",\
      0, AV_OPT_TYPE_CONST, {.i64 = 7}, -1, 7, AV_OPT_FLAG_ENCODING_PARAM, "signal_standard"},
Definition at line 2655 of file mxfenc.c.
Function Documentation
mxf_write_wav_desc()
static void mxf_write_wav_desc (AVFormatContext * s, AVStream * st) static
Definition at line 1193 of file mxfenc.c.
mxf_write_aes3_desc()
static void mxf_write_aes3_desc (AVFormatContext * s, AVStream * st) static
Definition at line 1198 of file mxfenc.c.
mxf_write_mpegvideo_desc()
static void mxf_write_mpegvideo_desc (AVFormatContext * s, AVStream * st) static
Definition at line 1111 of file mxfenc.c.
mxf_write_cdci_desc()
static void mxf_write_cdci_desc (AVFormatContext * s, AVStream * st) static
Definition at line 1106 of file mxfenc.c.
mxf_write_generic_sound_desc()
static void mxf_write_generic_sound_desc (AVFormatContext * s, AVStream * st) static
Definition at line 1203 of file mxfenc.c.
mxf_write_uuid()
static void mxf_write_uuid (AVIOContext * pb, enum MXFMetadataSetType type, int value) static
Definition at line 456 of file mxfenc.c.
Referenced by mxf_write_content_storage(), mxf_write_essence_container_data(), mxf_write_generic_desc(), mxf_write_identification(), mxf_write_index_table_segment(), mxf_write_multi_descriptor(), mxf_write_package(), mxf_write_preface(), mxf_write_sequence(), mxf_write_structural_component(), mxf_write_tagged_value(), mxf_write_timecode_component(), and mxf_write_track().
mxf_write_umid()
static void mxf_write_umid (AVFormatContext * s, int type) static
Definition at line 463 of file mxfenc.c.
Referenced by mxf_write_essence_container_data(), mxf_write_package(), mxf_write_structural_component(), and mxf_write_system_item().
mxf_write_refs_count()
static void mxf_write_refs_count (AVIOContext * pb, int ref_count) static
Definition at line 472 of file mxfenc.c.
Referenced by mxf_write_content_storage(), mxf_write_essence_container_refs(), mxf_write_multi_descriptor(), mxf_write_package(), mxf_write_preface(), and mxf_write_sequence().
klv_ber_length()
static int klv_ber_length (uint64_t len) static
Definition at line 478 of file mxfenc.c.
Referenced by mxf_write_partition().
klv_encode_ber_length()
static int klv_encode_ber_length (AVIOContext * pb, uint64_t len) static
Definition at line 486 of file mxfenc.c.
Referenced by mxf_write_content_storage(), mxf_write_essence_container_data(), mxf_write_identification(), mxf_write_index_table_segment(), mxf_write_multi_descriptor(), mxf_write_package(), mxf_write_partition(), mxf_write_preface(), mxf_write_primer_pack(), mxf_write_random_index_pack(), mxf_write_sequence(), mxf_write_structural_component(), mxf_write_tagged_value(), mxf_write_timecode_component(), and mxf_write_track().
klv_encode_ber4_length()
static void klv_encode_ber4_length (AVIOContext * pb, int len) static
Definition at line 507 of file mxfenc.c.
Referenced by mxf_write_d10_audio_packet(), mxf_write_d10_video_packet(), mxf_write_generic_desc(), mxf_write_klv_fill(), mxf_write_packet(), and mxf_write_system_item().
klv_encode_ber9_length()
static void klv_encode_ber9_length (AVIOContext * pb, uint64_t len) static
Definition at line 513 of file mxfenc.c.
Referenced by mxf_write_opatom_body_partition().
mxf_get_essence_container_ul_index()
static int mxf_get_essence_container_ul_index (enum AVCodecID id) static
Definition at line 522 of file mxfenc.c.
Referenced by mxf_write_header().
mxf_write_primer_pack()
static void mxf_write_primer_pack (AVFormatContext * s) static
Definition at line 531 of file mxfenc.c.
Referenced by mxf_write_partition().
mxf_write_local_tag()
static void mxf_write_local_tag (AVIOContext * pb, int size, int tag) static
Definition at line 557 of file mxfenc.c.
Referenced by mxf_write_cdci_common(), mxf_write_common_fields(), mxf_write_content_storage(), mxf_write_essence_container_data(), mxf_write_generic_desc(), mxf_write_generic_sound_common(), mxf_write_identification(), mxf_write_index_table_segment(), mxf_write_local_tag_utf16(), mxf_write_mpegvideo_desc(), mxf_write_multi_descriptor(), mxf_write_package(), mxf_write_preface(), mxf_write_sequence(), mxf_write_structural_component(), mxf_write_tagged_value(), mxf_write_timecode_component(), mxf_write_track(), and mxf_write_wav_common().
mxf_write_metadata_key()
static void mxf_write_metadata_key (AVIOContext * pb, unsigned int value) static
Definition at line 563 of file mxfenc.c.
Referenced by mxf_write_content_storage(), mxf_write_essence_container_data(), mxf_write_identification(), mxf_write_multi_descriptor(), mxf_write_package(), mxf_write_preface(), mxf_write_sequence(), mxf_write_structural_component(), mxf_write_tagged_value(), mxf_write_timecode_component(), and mxf_write_track().
mxf_free()
static void mxf_free (AVFormatContext * s) static
Definition at line 569 of file mxfenc.c.
Referenced by mxf_write_footer().
mxf_get_data_definition_ul()
static const MXFCodecUL* mxf_get_data_definition_ul (int type) static
Definition at line 579 of file mxfenc.c.
Referenced by mxf_write_common_fields().
mxf_write_essence_container_refs()
static void mxf_write_essence_container_refs (AVFormatContext * s) static
Definition at line 594 of file mxfenc.c.
Referenced by mxf_write_partition(), and mxf_write_preface().
mxf_write_preface()
static void mxf_write_preface (AVFormatContext * s) static
Definition at line 611 of file mxfenc.c.
Referenced by mxf_write_header_metadata_sets().
mxf_utf16len()
static uint64_t mxf_utf16len (const char * utf8_str) static
Definition at line 662 of file mxfenc.c.
Referenced by mxf_utf16_local_tag_length(), and mxf_write_local_tag_utf16().
mxf_utf16_local_tag_length()
static int mxf_utf16_local_tag_length (const char * utf8_str) static
Definition at line 684 of file mxfenc.c.
Referenced by mxf_write_identification(), mxf_write_package(), and mxf_write_tagged_value().
mxf_write_local_tag_utf16()
static void mxf_write_local_tag_utf16 (AVIOContext * pb, int tag, const char * value) static
Definition at line 703 of file mxfenc.c.
Referenced by mxf_write_identification(), mxf_write_package(), and mxf_write_tagged_value().
mxf_write_identification()
static void mxf_write_identification (AVFormatContext * s) static
Definition at line 716 of file mxfenc.c.
Referenced by mxf_write_header_metadata_sets().
mxf_write_content_storage()
static void mxf_write_content_storage (AVFormatContext * s) static
Definition at line 756 of file mxfenc.c.
Referenced by mxf_write_header_metadata_sets().
mxf_write_track()
static void mxf_write_track (AVFormatContext * s, AVStream * st, enum MXFMetadataSetType type) static
Definition at line 781 of file mxfenc.c.
Referenced by mxf_write_package().
mxf_write_common_fields()
static void mxf_write_common_fields (AVFormatContext * s, AVStream * st) static
Definition at line 828 of file mxfenc.c.
Referenced by mxf_write_sequence(), mxf_write_structural_component(), and mxf_write_timecode_component().
mxf_write_sequence()
static void mxf_write_sequence (AVFormatContext * s, AVStream * st, enum MXFMetadataSetType type) static
Definition at line 852 of file mxfenc.c.
Referenced by mxf_write_package().
mxf_write_timecode_component()
static void mxf_write_timecode_component (AVFormatContext * s, AVStream * st, enum MXFMetadataSetType type) static
Definition at line 880 of file mxfenc.c.
Referenced by mxf_write_package().
mxf_write_structural_component()
static void mxf_write_structural_component (AVFormatContext * s, AVStream * st, enum MXFMetadataSetType type) static
Definition at line 908 of file mxfenc.c.
Referenced by mxf_write_package().
mxf_write_multi_descriptor()
static void mxf_write_multi_descriptor (AVFormatContext * s) static
Definition at line 944 of file mxfenc.c.
Referenced by mxf_write_package().
mxf_write_generic_desc()
static void mxf_write_generic_desc (AVFormatContext * s, AVStream * st, const UID key, unsigned size) static
Definition at line 981 of file mxfenc.c.
Referenced by mxf_write_cdci_common(), and mxf_write_generic_sound_common().
mxf_write_cdci_common()
static void mxf_write_cdci_common (AVFormatContext * s, AVStream * st, const UID key, unsigned size) static
Definition at line 1010 of file mxfenc.c.
Referenced by mxf_write_cdci_desc(), and mxf_write_mpegvideo_desc().
mxf_write_generic_sound_common()
static void mxf_write_generic_sound_common (AVFormatContext * s, AVStream * st, const UID key, unsigned size) static
Definition at line 1134 of file mxfenc.c.
Referenced by mxf_write_generic_sound_desc(), and mxf_write_wav_common().
mxf_write_wav_common()
static void mxf_write_wav_common (AVFormatContext * s, AVStream * st, const UID key, unsigned size) static
Definition at line 1179 of file mxfenc.c.
Referenced by mxf_write_aes3_desc(), and mxf_write_wav_desc().
mxf_write_tagged_value()
static int mxf_write_tagged_value (AVFormatContext * s, const char * name, const char * value) static
Definition at line 1210 of file mxfenc.c.
Referenced by mxf_write_user_comments().
mxf_write_user_comments()
static int mxf_write_user_comments (AVFormatContext * s, const AVDictionary * m) static
Definition at line 1239 of file mxfenc.c.
Referenced by mxf_write_package().
mxf_write_package()
static void mxf_write_package (AVFormatContext * s, enum MXFMetadataSetType type, const char * package_name) static
Definition at line 1257 of file mxfenc.c.
Referenced by mxf_write_header_metadata_sets().
mxf_write_essence_container_data()
static int mxf_write_essence_container_data (AVFormatContext * s) static
Definition at line 1344 of file mxfenc.c.
Referenced by mxf_write_header_metadata_sets().
mxf_write_header_metadata_sets()
static int mxf_write_header_metadata_sets (AVFormatContext * s) static
Definition at line 1366 of file mxfenc.c.
Referenced by mxf_write_partition().
klv_fill_size()
static unsigned klv_fill_size (uint64_t size) static
Definition at line 1399 of file mxfenc.c.
Referenced by mxf_parse_dnxhd_frame(), mxf_parse_dv_frame(), mxf_write_d10_video_packet(), mxf_write_header(), mxf_write_index_table_segment(), mxf_write_klv_fill(), mxf_write_packet(), and mxf_write_partition().
mxf_write_index_table_segment()
static void mxf_write_index_table_segment (AVFormatContext * s) static
Definition at line 1408 of file mxfenc.c.
Referenced by mxf_write_footer(), and mxf_write_packet().
mxf_write_klv_fill()
static void mxf_write_klv_fill (AVFormatContext * s) static
Definition at line 1541 of file mxfenc.c.
Referenced by mxf_write_footer(), mxf_write_opatom_body_partition(), mxf_write_opatom_packet(), mxf_write_packet(), and mxf_write_partition().
mxf_write_partition()
static int mxf_write_partition (AVFormatContext * s, int bodysid, int indexsid, const uint8_t * key, int write_metadata) static
Definition at line 1553 of file mxfenc.c.
Referenced by mxf_write_footer(), mxf_write_opatom_body_partition(), mxf_write_opatom_packet(), and mxf_write_packet().
mxf_parse_dnxhd_frame()
static int mxf_parse_dnxhd_frame (AVFormatContext * s, AVStream * st, AVPacket * pkt) static
Definition at line 1658 of file mxfenc.c.
Referenced by mxf_write_packet().
mxf_parse_dv_frame()
static int mxf_parse_dv_frame (AVFormatContext * s, AVStream * st, AVPacket * pkt) static
Definition at line 1743 of file mxfenc.c.
Referenced by mxf_write_packet().
mxf_parse_h264_frame()
static int mxf_parse_h264_frame (AVFormatContext * s, AVStream * st, AVPacket * pkt, MXFIndexEntry * e) static
Definition at line 1841 of file mxfenc.c.
Referenced by mxf_write_packet().
mxf_get_mpeg2_codec_ul()
static const UID* mxf_get_mpeg2_codec_ul (AVCodecParameters * par) static
Definition at line 1921 of file mxfenc.c.
Referenced by mxf_parse_mpeg2_frame().
mxf_parse_mpeg2_frame()
static int mxf_parse_mpeg2_frame (AVFormatContext * s, AVStream * st, AVPacket * pkt, MXFIndexEntry * e) static
Definition at line 1941 of file mxfenc.c.
Referenced by mxf_write_packet().
mxf_parse_timestamp()
static uint64_t mxf_parse_timestamp (time_t timestamp) static
Definition at line 1999 of file mxfenc.c.
Referenced by mxf_write_header().
mxf_gen_umid()
static void mxf_gen_umid (AVFormatContext * s) static
Definition at line 2013 of file mxfenc.c.
Referenced by mxf_write_header().
mxf_init_timecode()
static int mxf_init_timecode (AVFormatContext * s, AVStream * st, AVRational rate) static
Definition at line 2025 of file mxfenc.c.
Referenced by mxf_write_header().
mxf_write_header()
static int mxf_write_header (AVFormatContext * s) static
Definition at line 2038 of file mxfenc.c.
mxf_write_system_item()
static void mxf_write_system_item (AVFormatContext * s) static
Definition at line 2238 of file mxfenc.c.
Referenced by mxf_write_packet().
mxf_write_d10_video_packet()
static void mxf_write_d10_video_packet (AVFormatContext * s, AVStream * st, AVPacket * pkt) static
Definition at line 2279 of file mxfenc.c.
Referenced by mxf_write_packet().
mxf_write_d10_audio_packet()
static void mxf_write_d10_audio_packet (AVFormatContext * s, AVStream * st, AVPacket * pkt) static
Definition at line 2308 of file mxfenc.c.
Referenced by mxf_write_packet().
mxf_write_opatom_body_partition()
static int mxf_write_opatom_body_partition (AVFormatContext * s) static
Definition at line 2340 of file mxfenc.c.
Referenced by mxf_write_footer(), and mxf_write_opatom_packet().
mxf_write_opatom_packet()
static int mxf_write_opatom_packet (AVFormatContext * s, AVPacket * pkt, MXFIndexEntry * ie) static
Definition at line 2361 of file mxfenc.c.
Referenced by mxf_write_packet().
mxf_write_packet()
static int mxf_write_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 2391 of file mxfenc.c.
mxf_write_random_index_pack()
static void mxf_write_random_index_pack (AVFormatContext * s) static
Definition at line 2495 of file mxfenc.c.
Referenced by mxf_write_footer().
mxf_write_footer()
static int mxf_write_footer (AVFormatContext * s) static
Definition at line 2522 of file mxfenc.c.
mxf_interleave_get_packet()
static int mxf_interleave_get_packet (AVFormatContext * s, AVPacket * out, AVPacket * pkt, int flush) static
Definition at line 2585 of file mxfenc.c.
Referenced by mxf_interleave().
mxf_compare_timestamps()
static int mxf_compare_timestamps (AVFormatContext * s, AVPacket * next, AVPacket * pkt) static
Definition at line 2640 of file mxfenc.c.
Referenced by mxf_interleave().
mxf_interleave()
static int mxf_interleave (AVFormatContext * s, AVPacket * out, AVPacket * pkt, int flush) static
Definition at line 2649 of file mxfenc.c.
Variable Documentation
ff_mxf_d10_muxer
AVOutputFormat ff_mxf_d10_muxer
Initial value:
= {
    .name              = "mxf_d10",
    .long_name         = NULL_IF_CONFIG_SMALL("MXF (Material eXchange Format) D-10 Mapping"),
    .mime_type         = "application/mxf",
    .priv_data_size    = sizeof(MXFContext),
    .audio_codec       = AV_CODEC_ID_PCM_S16LE,
    .video_codec       = AV_CODEC_ID_MPEG2VIDEO,
    .write_header      = mxf_write_header,
    .write_packet      = mxf_write_packet,
    .write_trailer     = mxf_write_footer,
    .flags             = AVFMT_NOTIMESTAMPS,
    .interleave_packet = mxf_interleave,
    .priv_class        = &mxf_d10_muxer_class,
}
Definition at line 2735 of file mxfenc.c.
ff_mxf_opatom_muxer
AVOutputFormat ff_mxf_opatom_muxer
Initial value:
= {
    .name              = "mxf_opatom",
    .long_name         = NULL_IF_CONFIG_SMALL("MXF (Material eXchange Format) Operational Pattern Atom"),
    .mime_type         = "application/mxf",
    .extensions        = "mxf",
    .priv_data_size    = sizeof(MXFContext),
    .audio_codec       = AV_CODEC_ID_PCM_S16LE,
    .video_codec       = AV_CODEC_ID_DNXHD,
    .write_header      = mxf_write_header,
    .write_packet      = mxf_write_packet,
    .write_trailer     = mxf_write_footer,
    .flags             = AVFMT_NOTIMESTAMPS,
    .interleave_packet = mxf_interleave,
    .priv_class        = &mxf_opatom_muxer_class,
}
Definition at line 2750 of file mxfenc.c.
id
enum AVCodecID id
Definition at line 104 of file mxfenc.c.
Referenced by ape_tag_read_field(), asf_read_picture(), av_codec_get_id(), av_new_program(), avi_add_ientry(), avi_get_ientry(), avpriv_new_chapter(), che_configure(), check_section_show_entries(), create_new_audio_stream(), dxtory_decode_v1_rgb(), encode_callback(), eval_expr(), exif_decode_tag(), ff_flac_parse_picture(), ff_get_wav_header(), ff_jpegls_decode_lse(), ff_mjpeg_decode_sos(), ff_mov_read_stsd_entries(), ff_rtsp_tcp_read_packet(), ff_rtsp_tcp_write_packet(), ff_wav_codec_get_id(), ffat_update_ctx(), ffm_read_data(), flush_packet(), frame_configure_elements(), get_codec_data(), get_sindex(), lvf_read_header(), lvf_read_packet(), mark_section_show_entries(), mjpeg_decode_app(), mkv_write_vtt_blocks(), mov_codec_id(), mov_read_covr(), mov_read_frma(), output_configure(), print_section(), put_system_header(), qdm2_parse_subpacket(), read_apic(), remap_deprecated_codec_id(), remove_sps(), remove_vps(), rso_read_header(), set_codec_from_probe_data(), sol_read_header(), txd_read_packet(), wait_frame(), wavpack_decode_block(), webvtt_write_packet(), write_chapter(), and wv_read_block_header().
index
int index
Definition at line 105 of file mxfenc.c.
mxf_essence_mappings
const { ... } mxf_essence_mappings[]
Initial value:
= {
    { AV_CODEC_ID_MPEG2VIDEO, 0 },
    { AV_CODEC_ID_PCM_S24LE,  1 },
    { AV_CODEC_ID_PCM_S16LE,  1 },
    { AV_CODEC_ID_DVVIDEO,   15 },
    { AV_CODEC_ID_DNXHD,     24 },
    { AV_CODEC_ID_JPEG2000,  34 },
    { AV_CODEC_ID_H264,      35 },
    { AV_CODEC_ID_NONE }
}
Referenced by mxf_get_essence_container_ul_index().
mxf_essence_container_uls
const MXFContainerEssenceEntry mxf_essence_container_uls[] static
Definition at line 123 of file mxfenc.c.
uuid_base
const uint8_t uuid_base[] = { 0xAD,0xAB,0x44,0x24,0x2f,0x25,0x4d,0xc7,0x92,0xff,0x29,0xbd } static
Definition at line 330 of file mxfenc.c.
Referenced by mxf_write_uuid().
umid_ul
const uint8_t umid_ul[] = { 0x06,0x0A,0x2B,0x34,0x01,0x01,0x01,0x05,0x01,0x01,0x0D,0x00,0x13 } static
Definition at line 331 of file mxfenc.c.
Referenced by mxf_write_umid().
op1a_ul
const uint8_t op1a_ul[] = { 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x01,0x0D,0x01,0x02,0x01,0x01,0x01,0x09,0x00 } static
complete key for operation pattern, partitions, and primer pack
Definition at line 336 of file mxfenc.c.
Referenced by mxf_write_partition(), and mxf_write_preface().
opatom_ul
const uint8_t opatom_ul[] = { 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x02,0x0D,0x01,0x02,0x01,0x10,0x03,0x00,0x00 } static
Definition at line 337 of file mxfenc.c.
Referenced by mxf_write_partition(), and mxf_write_preface().
footer_partition_key
const uint8_t footer_partition_key[] = { 0x06,0x0E,0x2B,0x34,0x02,0x05,0x01,0x01,0x0D,0x01,0x02,0x01,0x01,0x04,0x04,0x00 } static
Definition at line 338 of file mxfenc.c.
Referenced by mxf_write_footer(), and mxf_write_partition().
primer_pack_key
const uint8_t primer_pack_key[] = { 0x06,0x0E,0x2B,0x34,0x02,0x05,0x01,0x01,0x0D,0x01,0x02,0x01,0x01,0x05,0x01,0x00 } static
Definition at line 339 of file mxfenc.c.
Referenced by mxf_write_primer_pack().
index_table_segment_key
const uint8_t index_table_segment_key[] = { 0x06,0x0E,0x2B,0x34,0x02,0x53,0x01,0x01,0x0d,0x01,0x02,0x01,0x01,0x10,0x01,0x00 } static
Definition at line 340 of file mxfenc.c.
Referenced by mxf_write_index_table_segment().
random_index_pack_key
const uint8_t random_index_pack_key[] = { 0x06,0x0E,0x2B,0x34,0x02,0x05,0x01,0x01,0x0D,0x01,0x02,0x01,0x01,0x11,0x01,0x00 } static
Definition at line 341 of file mxfenc.c.
Referenced by mxf_write_random_index_pack().
header_open_partition_key
const uint8_t header_open_partition_key[] = { 0x06,0x0E,0x2B,0x34,0x02,0x05,0x01,0x01,0x0D,0x01,0x02,0x01,0x01,0x02,0x01,0x00 } static
Definition at line 342 of file mxfenc.c.
Referenced by mxf_write_opatom_packet(), and mxf_write_packet().
header_closed_partition_key
const uint8_t header_closed_partition_key[] = { 0x06,0x0E,0x2B,0x34,0x02,0x05,0x01,0x01,0x0D,0x01,0x02,0x01,0x01,0x02,0x04,0x00 } static
Definition at line 343 of file mxfenc.c.
Referenced by mxf_write_footer().
klv_fill_key
const uint8_t klv_fill_key[] = { 0x06,0x0E,0x2B,0x34,0x01,0x01,0x01,0x02,0x03,0x01,0x02,0x10,0x01,0x00,0x00,0x00 } static
Definition at line 344 of file mxfenc.c.
Referenced by mxf_write_d10_video_packet(), and mxf_write_klv_fill().
body_partition_key
const uint8_t body_partition_key[] = { 0x06,0x0E,0x2B,0x34,0x02,0x05,0x01,0x01,0x0D,0x01,0x02,0x01,0x01,0x03,0x04,0x00 } static
Definition at line 345 of file mxfenc.c.
Referenced by mxf_write_opatom_body_partition(), mxf_write_packet(), and mxf_write_partition().
header_metadata_key
const uint8_t header_metadata_key[] = { 0x06,0x0E,0x2B,0x34,0x02,0x53,0x01,0x01,0x0D,0x01,0x01,0x01,0x01 } static
partial key for header metadata
Definition at line 350 of file mxfenc.c.
Referenced by mxf_write_metadata_key().
multiple_desc_ul
const uint8_t multiple_desc_ul[] = { 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x03,0x0D,0x01,0x03,0x01,0x02,0x7F,0x01,0x00 } static
Definition at line 351 of file mxfenc.c.
Referenced by mxf_write_essence_container_refs(), mxf_write_multi_descriptor(), and mxf_write_system_item().
mxf_local_tag_batch
const MXFLocalTagPair mxf_local_tag_batch[] static
SMPTE RP210 http://www.smpte-ra.org/mdd/index.html https://smpte-ra.org/sites/default/files/Labels.xml.
Definition at line 357 of file mxfenc.c.
mxf_user_comments_local_tag
const MXFLocalTagPair mxf_user_comments_local_tag[] static
Initial value:
= {
    { 0x4406, {0x06,0x0E,0x2B,0x34,0x01,0x01,0x01,0x02,0x03,0x02,0x01,0x02,0x0C,0x00,0x00,0x00}},
    { 0x5001, {0x06,0x0E,0x2B,0x34,0x01,0x01,0x01,0x02,0x03,0x02,0x01,0x02,0x09,0x01,0x00,0x00}},
    { 0x5003, {0x06,0x0E,0x2B,0x34,0x01,0x01,0x01,0x02,0x03,0x02,0x01,0x02,0x0A,0x01,0x00,0x00}},
}
Definition at line 450 of file mxfenc.c.
smpte_12m_timecode_track_data_ul
const uint8_t smpte_12m_timecode_track_data_ul[] = { 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x01,0x01,0x03,0x02,0x01,0x01,0x00,0x00,0x00 } static
Definition at line 826 of file mxfenc.c.
Referenced by mxf_write_common_fields().
mxf_mpegvideo_descriptor_key
const UID mxf_mpegvideo_descriptor_key = { 0x06,0x0E,0x2B,0x34,0x02,0x53,0x01,0x01,0x0d,0x01,0x01,0x01,0x01,0x01,0x51,0x00 } static
Definition at line 1004 of file mxfenc.c.
Referenced by mxf_write_mpegvideo_desc().
mxf_wav_descriptor_key
const UID mxf_wav_descriptor_key = { 0x06,0x0E,0x2B,0x34,0x02,0x53,0x01,0x01,0x0d,0x01,0x01,0x01,0x01,0x01,0x48,0x00 } static
Definition at line 1005 of file mxfenc.c.
Referenced by mxf_write_wav_desc().
mxf_aes3_descriptor_key
const UID mxf_aes3_descriptor_key = { 0x06,0x0E,0x2B,0x34,0x02,0x53,0x01,0x01,0x0d,0x01,0x01,0x01,0x01,0x01,0x47,0x00 } static
Definition at line 1006 of file mxfenc.c.
Referenced by mxf_write_aes3_desc().
mxf_cdci_descriptor_key
const UID mxf_cdci_descriptor_key = { 0x06,0x0E,0x2B,0x34,0x02,0x53,0x01,0x01,0x0D,0x01,0x01,0x01,0x01,0x01,0x28,0x00 } static
Definition at line 1007 of file mxfenc.c.
Referenced by mxf_write_cdci_desc().
mxf_generic_sound_descriptor_key
const UID mxf_generic_sound_descriptor_key = { 0x06,0x0E,0x2B,0x34,0x02,0x53,0x01,0x01,0x0D,0x01,0x01,0x01,0x01,0x01,0x42,0x00 } static
Definition at line 1008 of file mxfenc.c.
Referenced by mxf_write_generic_sound_desc().
mxf_indirect_value_utf16le
const uint8_t mxf_indirect_value_utf16le[] = { 0x4c,0x00,0x02,0x10,0x01,0x00,0x00,0x00,0x00,0x06,0x0e,0x2b,0x34,0x01,0x04,0x01,0x01 } static
Definition at line 1208 of file mxfenc.c.
Referenced by mxf_write_tagged_value().
uid
UID uid
Definition at line 1819 of file mxfenc.c.
Referenced by matroska_convert_tags(), matroska_parse_tracks(), matroska_read_header(), and qsv_load_plugins().
frame_size
int frame_size
Examples:
transcode_aac.c.
Definition at line 1820 of file mxfenc.c.
Referenced by aic_decode_header(), alac_entropy_coder(), alac_linear_predictor(), apply_filter(), av_buffersink_set_frame_size(), avpriv_mpegaudio_decode_header(), build_frame_code(), caf_write_header(), check_codec_match(), dcadec_decode_frame(), decode_frame(), decode_packet(), dfa_read_packet(), do_video_out(), dv_frame_offset(), dvvideo_decode_frame(), encode_frame(), escape124_decode_frame(), ff_celt_decode_frame(), ff_compute_frame_duration(), ff_psy_preprocess(), ff_put_wav_header(), ff_rtp_send_h261(), ff_rtp_send_vc2hq(), ff_sipr_decode_frame_16k(), ff_vbv_update(), ffm2_read_header(), ffm_read_header(), find_expected_header(), flic_decode_frame_15_16BPP(), flic_decode_frame_8BPP(), g723_1_decode_frame(), generate_raw_frame(), get_audio_frame_duration(), init_output_frame(), libopus_encode_init(), lmlm4_read_packet(), load_encode_and_write(), main(), mp3_header_decompress(), mp3_read_header(), mp3lame_encode_frame(), mpegts_init(), mxf_parse_dnxhd_frame(), mxf_parse_dv_frame(), mxf_parse_h264_frame(), mxf_write_d10_audio_packet(), new_subtitle_stream(), new_video_stream(), on2avc_decode_frame(), opus_duration(), pack_bitstream(), prores_encode_frame(), qdm2_decode(), read_packet(), return_stored_frame(), rm_write_header(), rpl_read_packet(), rtp_send_ilbc(), rv10_write_header(), s302m_decode_frame(), s302m_parse_frame_header(), smacker_read_packet(), store_packet(), str_probe(), str_read_packet(), swf_write_video(), vc1t_read_packet(), wavpack_decode_frame(), and xmv_fetch_video_packet().
profile
int profile
Definition at line 1821 of file mxfenc.c.
interlaced
uint8_t interlaced
Definition at line 1822 of file mxfenc.c.
Referenced by avui_decode_frame(), avui_encode_frame(), copy_frame(), dnxhd_find_frame_end(), encode_init(), ff_dnxhd_find_cid(), find_compressor(), ljpeg_decode_yuv_scan(), magy_decode_slice(), magy_decode_slice10(), mov_get_h264_codec_tag(), mov_get_mpeg2_xdcam_codec_tag(), and mov_write_avid_tag().
mxf_h264_codec_uls
const { ... } mxf_h264_codec_uls[]
Initial value:
= {
    {{ 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x0a,0x04,0x01,0x02,0x02,0x01,0x31,0x11,0x01 },      0,  66, 0 },
    {{ 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x0a,0x04,0x01,0x02,0x02,0x01,0x32,0x20,0x01 },      0, 110, 0 },
    {{ 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x0a,0x04,0x01,0x02,0x02,0x01,0x32,0x21,0x01 }, 232960,   0, 1 },
    {{ 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x0a,0x04,0x01,0x02,0x02,0x01,0x32,0x21,0x02 }, 281088,   0, 1 },
    {{ 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x0a,0x04,0x01,0x02,0x02,0x01,0x32,0x21,0x03 }, 232960,   0, 0 },
    {{ 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x0a,0x04,0x01,0x02,0x02,0x01,0x32,0x21,0x04 }, 281088,   0, 0 },
    {{ 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x0a,0x04,0x01,0x02,0x02,0x01,0x32,0x21,0x08 }, 116736,   0, 0 },
    {{ 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x0a,0x04,0x01,0x02,0x02,0x01,0x32,0x21,0x09 }, 140800,   0, 0 },
    {{ 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x0a,0x04,0x01,0x02,0x02,0x01,0x32,0x30,0x01 },      0, 122, 0 },
    {{ 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x0a,0x04,0x01,0x02,0x02,0x01,0x32,0x31,0x01 }, 472576,   0, 1 },
    {{ 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x0a,0x04,0x01,0x02,0x02,0x01,0x32,0x31,0x02 }, 568832,   0, 1 },
    {{ 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x0a,0x04,0x01,0x02,0x02,0x01,0x32,0x31,0x03 }, 472576,   0, 0 },
    {{ 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x0a,0x04,0x01,0x02,0x02,0x01,0x32,0x31,0x04 }, 568832,   0, 0 },
    {{ 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x0a,0x04,0x01,0x02,0x02,0x01,0x32,0x31,0x08 }, 236544,   0, 0 },
    {{ 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x0a,0x04,0x01,0x02,0x02,0x01,0x32,0x31,0x09 }, 284672,   0, 0 },
}
Referenced by mxf_parse_h264_frame().
mxf_mpeg2_codec_uls
const UID mxf_mpeg2_codec_uls[] static
Initial value:
= {
    { 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x03,0x04,0x01,0x02,0x02,0x01,0x01,0x10,0x00 },
    { 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x03,0x04,0x01,0x02,0x02,0x01,0x01,0x11,0x00 },
    { 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x03,0x04,0x01,0x02,0x02,0x01,0x02,0x02,0x00 },
    { 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x03,0x04,0x01,0x02,0x02,0x01,0x02,0x03,0x00 },
    { 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x03,0x04,0x01,0x02,0x02,0x01,0x03,0x02,0x00 },
    { 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x03,0x04,0x01,0x02,0x02,0x01,0x03,0x03,0x00 },
    { 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x03,0x04,0x01,0x02,0x02,0x01,0x04,0x02,0x00 },
    { 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x03,0x04,0x01,0x02,0x02,0x01,0x04,0x03,0x00 },
    { 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x03,0x04,0x01,0x02,0x02,0x01,0x05,0x02,0x00 },
    { 0x06,0x0E,0x2B,0x34,0x04,0x01,0x01,0x03,0x04,0x01,0x02,0x02,0x01,0x05,0x03,0x00 },
}
Definition at line 1908 of file mxfenc.c.
Referenced by mxf_get_mpeg2_codec_ul().
system_metadata_pack_key
const uint8_t system_metadata_pack_key[] = { 0x06,0x0E,0x2B,0x34,0x02,0x05,0x01,0x01,0x0D,0x01,0x03,0x01,0x04,0x01,0x01,0x00 } static
Definition at line 2235 of file mxfenc.c.
Referenced by mxf_write_system_item().
system_metadata_package_set_key
const uint8_t system_metadata_package_set_key[] = { 0x06,0x0E,0x2B,0x34,0x02,0x43,0x01,0x01,0x0D,0x01,0x03,0x01,0x04,0x01,0x02,0x01 } static
Definition at line 2236 of file mxfenc.c.
Referenced by mxf_write_system_item().
mxf_options
const AVOption mxf_options[] static
Initial value:
= {
    MXF_COMMON_OPTIONS
    { "store_user_comments", "",
      0x42, AV_OPT_TYPE_BOOL, {.i64 = 1}, 0, 1, AV_OPT_FLAG_ENCODING_PARAM},
    { NULL },
}
Definition at line 2675 of file mxfenc.c.
mxf_muxer_class
const AVClass mxf_muxer_class static
Initial value:
= {
    .class_name     = "MXF muxer",
    .item_name      = av_default_item_name,
    .option         = mxf_options,
    .version        = LIBAVUTIL_VERSION_INT,
}
Definition at line 2682 of file mxfenc.c.
d10_options
const AVOption d10_options[] static
Initial value:
= {
    { "d10_channelcount", "Force/set channelcount in generic sound essence descriptor",
      0x42, AV_OPT_TYPE_INT, {.i64 = -1}, -1, 8, AV_OPT_FLAG_ENCODING_PARAM},
    MXF_COMMON_OPTIONS
    { "store_user_comments", "",
      0x42, AV_OPT_TYPE_BOOL, {.i64 = 0}, 0, 1, AV_OPT_FLAG_ENCODING_PARAM},
    { NULL },
}
Definition at line 2689 of file mxfenc.c.
mxf_d10_muxer_class
const AVClass mxf_d10_muxer_class static
Initial value:
= {
    .class_name     = "MXF-D10 muxer",
    .item_name      = av_default_item_name,
    .option         = d10_options,
    .version        = LIBAVUTIL_VERSION_INT,
}
Definition at line 2698 of file mxfenc.c.
opatom_options
const AVOption opatom_options[] static
Initial value:
= {
    { "mxf_audio_edit_rate", "Audio edit rate for timecode",
        0x42, AV_OPT_TYPE_RATIONAL, {.dbl=25}, 0, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM },
    MXF_COMMON_OPTIONS
    { NULL },
}
Definition at line 2705 of file mxfenc.c.
mxf_opatom_muxer_class
const AVClass mxf_opatom_muxer_class static
Initial value:
= {
    .class_name     = "MXF-OPAtom muxer",
    .item_name      = av_default_item_name,
    .option         = opatom_options,
    .version        = LIBAVUTIL_VERSION_INT,
}
Definition at line 2712 of file mxfenc.c.
ff_mxf_muxer
AVOutputFormat ff_mxf_muxer
Initial value:
= {
    .name              = "mxf",
    .long_name         = NULL_IF_CONFIG_SMALL("MXF (Material eXchange Format)"),
    .mime_type         = "application/mxf",
    .extensions        = "mxf",
    .priv_data_size    = sizeof(MXFContext),
    .audio_codec       = AV_CODEC_ID_PCM_S16LE,
    .video_codec       = AV_CODEC_ID_MPEG2VIDEO,
    .write_header      = mxf_write_header,
    .write_packet      = mxf_write_packet,
    .write_trailer     = mxf_write_footer,
    .flags             = AVFMT_NOTIMESTAMPS,
    .interleave_packet = mxf_interleave,
    .priv_class        = &mxf_muxer_class,
}
Definition at line 2719 of file mxfenc.c.