FFmpeg: normalize Namespace Reference
normalize Namespace Reference
Variables
ifile = sys.argv[1]
encopt = sys.argv[2:-1]
ofile = sys.argv[-1]
string analysis_cmd = 'ffprobe -v error -of compact=p=0:nk=1 '
probe_out = subprocess.check_output(analysis_cmd, shell=True)
int loudness = -23
sline = line.rstrip()
adjust = ref - float(loudness)
list norm_cmd = ['ffmpeg', '-i', ifile, '-af', 'volume=%fdB' % adjust]
Variable Documentation
ifile
normalize.ifile = sys.argv[1]
Definition at line 6 of file normalize.py.
Referenced by probe_file(), process_input(), and transcode_init().
encopt
normalize.encopt = sys.argv[2:-1]
Definition at line 7 of file normalize.py.
ofile
normalize.ofile = sys.argv[-1]
Definition at line 8 of file normalize.py.
analysis_cmd
string normalize.analysis_cmd = 'ffprobe -v error -of compact=p=0:nk=1 '
Definition at line 13 of file normalize.py.
probe_out
normalize.probe_out = subprocess.check_output(analysis_cmd, shell=True)
Definition at line 17 of file normalize.py.
loudness
normalize.loudness = -23
Definition at line 20 of file normalize.py.
sline
normalize.sline = line.rstrip()
Definition at line 22 of file normalize.py.
adjust
normalize.adjust = ref - float(loudness)
Definition at line 25 of file normalize.py.
Referenced by comp_adjust(), init_gaussian_filter(), libopenjpeg_copy_to_packed16(), and libopenjpeg_copyto16().
norm_cmd
list normalize.norm_cmd = ['ffmpeg', '-i', ifile, '-af', 'volume=%fdB' % adjust]
Definition at line 30 of file normalize.py.