FFmpeg: libavcodec/neon/mpegvideo.c File Reference
mpegvideo.c File Reference
#include <arm_neon.h>
#include "config.h"
#include "libavutil/cpu.h"
#include "libavcodec/mpegvideo.h"
Functions
static void ff_dct_unquantize_h263_neon (int qscale, int qadd, int nCoeffs, int16_t *block)
static void dct_unquantize_h263_inter_neon (MpegEncContext *s, int16_t *block, int n, int qscale)
static void dct_unquantize_h263_intra_neon (MpegEncContext *s, int16_t *block, int n, int qscale)
av_cold void ff_mpv_common_init_neon (MpegEncContext *s)
Function Documentation
ff_dct_unquantize_h263_neon()
static void ff_dct_unquantize_h263_neon (int qscale, int qadd, int nCoeffs, int16_t * block) inline static
Definition at line 35 of file mpegvideo.c.
Referenced by dct_unquantize_h263_inter_neon(), and dct_unquantize_h263_intra_neon().
dct_unquantize_h263_inter_neon()
static void dct_unquantize_h263_inter_neon (MpegEncContext * s, int16_t * block, int n, int qscale) static
Definition at line 85 of file mpegvideo.c.
Referenced by ff_mpv_common_init_neon().
dct_unquantize_h263_intra_neon()
static void dct_unquantize_h263_intra_neon (MpegEncContext * s, int16_t * block, int n, int qscale) static
Definition at line 94 of file mpegvideo.c.
Referenced by ff_mpv_common_init_neon().
ff_mpv_common_init_neon()
av_cold void ff_mpv_common_init_neon (MpegEncContext * s)
Definition at line 126 of file mpegvideo.c.
Referenced by dct_init().