FFmpeg: libavformat/network.h File Reference
network.h File Reference
#include <errno.h>
#include <stdint.h>
#include "config.h"
#include "libavutil/error.h"
#include "os_support.h"
#include "avio.h"
#include "url.h"
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netdb.h>
Data Structures
struct sockaddr_storage
union sockaddr_union
struct addrinfo
Macros
#define ff_neterrno() AVERROR(errno)
#define MSG_NOSIGNAL 0
#define EAI_AGAIN 2
#define EAI_BADFLAGS 3
#define EAI_FAIL 4
#define EAI_FAMILY 5
#define EAI_MEMORY 6
#define EAI_NODATA 7
#define EAI_NONAME 8
#define EAI_SERVICE 9
#define EAI_SOCKTYPE 10
#define AI_PASSIVE 1
#define AI_CANONNAME 2
#define AI_NUMERICHOST 4
#define NI_NOFQDN 1
#define NI_NUMERICHOST 2
#define NI_NAMERQD 4
#define NI_NUMERICSERV 8
#define NI_DGRAM 16
#define getaddrinfo ff_getaddrinfo
#define freeaddrinfo ff_freeaddrinfo
#define getnameinfo ff_getnameinfo
#define gai_strerror ff_gai_strerror
#define INADDR_LOOPBACK 0x7f000001
#define INET_ADDRSTRLEN 16
#define INET6_ADDRSTRLEN INET_ADDRSTRLEN
#define IN_MULTICAST(a) ((((uint32_t)(a)) & 0xf0000000) == 0xe0000000)
#define IN6_IS_ADDR_MULTICAST(a) (((uint8_t *) (a))[0] == 0xff)
#define POLLING_TIME 100
Functions
int ff_socket_nonblock (int socket, int enable)
int ff_network_init (void)
void ff_network_close (void)
int ff_tls_init (void)
void ff_tls_deinit (void)
int ff_network_wait_fd (int fd, int write)
int ff_network_wait_fd_timeout (int fd, int write, int64_t timeout, AVIOInterruptCB *int_cb)
This works similarly to ff_network_wait_fd, but waits up to 'timeout' microseconds Uses ff_network_wait_fd in a loop.
int ff_inet_aton (const char *str, struct in_addr *add)
int ff_getaddrinfo (const char *node, const char *service, const struct addrinfo *hints, struct addrinfo **res)
void ff_freeaddrinfo (struct addrinfo *res)
int ff_getnameinfo (const struct sockaddr *sa, int salen, char *host, int hostlen, char *serv, int servlen, int flags)
const char * ff_gai_strerror (int ecode)
int ff_is_multicast_address (struct sockaddr *addr)
int ff_listen_bind (int fd, const struct sockaddr *addr, socklen_t addrlen, int timeout, URLContext *h)
Bind to a file descriptor and poll for a connection.
int ff_listen (int fd, const struct sockaddr *addr, socklen_t addrlen)
Bind to a file descriptor to an address without accepting connections.
int ff_accept (int fd, int timeout, URLContext *h)
Poll for a single connection on the passed file descriptor.
int ff_listen_connect (int fd, const struct sockaddr *addr, socklen_t addrlen, int timeout, URLContext *h, int will_try_next)
Connect to a file descriptor and poll for result.
int ff_http_match_no_proxy (const char *no_proxy, const char *hostname)
int ff_socket (int domain, int type, int protocol)
Variables
int ff_network_inited_globally
Macro Definition Documentation
ff_neterrno
#define ff_neterrno () AVERROR(errno)
Definition at line 64 of file network.h.
Referenced by ff_accept(), ff_listen(), ff_listen_connect(), ff_network_close(), ff_network_wait_fd(), handle_connection(), http_receive_data(), http_send_data(), http_server(), log_net_error(), rtp_read(), rtp_write(), sctp_open(), sctp_read(), sctp_wait_fd(), sctp_write(), tcp_accept(), tcp_open(), tcp_read(), tcp_write(), udp_get_file_handle(), udp_read(), udp_set_multicast_sources(), udp_write(), unix_open(), unix_read(), and unix_write().
MSG_NOSIGNAL
#define MSG_NOSIGNAL 0
Definition at line 123 of file network.h.
Referenced by ff_sctp_send(), sctp_write(), tcp_write(), and unix_write().
EAI_AGAIN
#define EAI_AGAIN 2
Definition at line 141 of file network.h.
EAI_BADFLAGS
#define EAI_BADFLAGS 3
Definition at line 144 of file network.h.
EAI_FAIL
#define EAI_FAIL 4
Definition at line 147 of file network.h.
EAI_FAMILY
#define EAI_FAMILY 5
Definition at line 150 of file network.h.
EAI_MEMORY
#define EAI_MEMORY 6
Definition at line 153 of file network.h.
EAI_NODATA
#define EAI_NODATA 7
Definition at line 156 of file network.h.
EAI_NONAME
#define EAI_NONAME 8
Definition at line 159 of file network.h.
EAI_SERVICE
#define EAI_SERVICE 9
Definition at line 162 of file network.h.
EAI_SOCKTYPE
#define EAI_SOCKTYPE 10
Definition at line 165 of file network.h.
AI_PASSIVE
#define AI_PASSIVE 1
Definition at line 169 of file network.h.
Referenced by tcp_open(), and udp_socket_create().
AI_CANONNAME
#define AI_CANONNAME 2
Definition at line 173 of file network.h.
AI_NUMERICHOST
#define AI_NUMERICHOST 4
Definition at line 177 of file network.h.
Referenced by ff_tls_open_underlying(), ff_url_join(), and get_sockaddr().
NI_NOFQDN
#define NI_NOFQDN 1
Definition at line 181 of file network.h.
NI_NUMERICHOST
#define NI_NUMERICHOST 2
Definition at line 185 of file network.h.
Referenced by ff_rtsp_open_transport_ctx().
NI_NAMERQD
#define NI_NAMERQD 4
Definition at line 189 of file network.h.
NI_NUMERICSERV
#define NI_NUMERICSERV 8
Definition at line 193 of file network.h.
Referenced by udp_port().
NI_DGRAM
#define NI_DGRAM 16
Definition at line 197 of file network.h.
getaddrinfo
#define getaddrinfo ff_getaddrinfo
Definition at line 207 of file network.h.
Referenced by ff_tls_open_underlying(), ff_url_join(), get_sockaddr(), resolve_host(), rtp_resolve_host(), sap_write_header(), sctp_open(), tcp_open(), and udp_resolve_host().
freeaddrinfo
#define freeaddrinfo ff_freeaddrinfo
Definition at line 208 of file network.h.
Referenced by ff_tls_open_underlying(), ff_url_join(), get_sockaddr(), resolve_host(), rtp_parse_addr_list(), sap_write_header(), sctp_open(), tcp_open(), udp_set_multicast_sources(), udp_set_url(), and udp_socket_create().
getnameinfo
#define getnameinfo ff_getnameinfo
Definition at line 209 of file network.h.
Referenced by ff_rtsp_open_transport_ctx(), and udp_port().
gai_strerror
#define gai_strerror ff_gai_strerror
Definition at line 215 of file network.h.
Referenced by ff_rtsp_open_transport_ctx(), get_sockaddr(), rtp_resolve_host(), sctp_open(), tcp_open(), udp_port(), and udp_resolve_host().
INADDR_LOOPBACK
#define INADDR_LOOPBACK 0x7f000001
Definition at line 219 of file network.h.
INET_ADDRSTRLEN
#define INET_ADDRSTRLEN 16
Definition at line 223 of file network.h.
INET6_ADDRSTRLEN
#define INET6_ADDRSTRLEN INET_ADDRSTRLEN
Definition at line 227 of file network.h.
IN_MULTICAST
#define IN_MULTICAST (a) ((((uint32_t)(a)) & 0xf0000000) == 0xe0000000)
Definition at line 231 of file network.h.
Referenced by ff_is_multicast_address().
IN6_IS_ADDR_MULTICAST
#define IN6_IS_ADDR_MULTICAST (a) (((uint8_t *) (a))[0] == 0xff)
Definition at line 234 of file network.h.
Referenced by ff_is_multicast_address().
POLLING_TIME
#define POLLING_TIME 100
Definition at line 239 of file network.h.
Referenced by ff_network_wait_fd(), and ff_poll_interrupt().
Function Documentation
ff_socket_nonblock()
int ff_socket_nonblock (int socket, int enable)
Referenced by ff_accept(), ff_listen_connect(), new_connection(), socket_open_listen(), udp_get_file_handle(), and udp_open().
ff_network_init()
int ff_network_init (void)
Definition at line 55 of file network.c.
Referenced by avformat_network_init(), ff_rtsp_open_transport_ctx(), sap_read_header(), sap_write_header(), and url_alloc_for_protocol().
ff_network_close()
void ff_network_close (void)
Definition at line 102 of file network.c.
Referenced by avformat_network_deinit(), ff_rtsp_open_transport_ctx(), ffurl_closep(), rtsp_read_close(), rtsp_write_close(), sap_read_close(), sap_write_close(), and url_alloc_for_protocol().
ff_tls_init()
int ff_tls_init (void)
Definition at line 30 of file network.c.
Referenced by avformat_network_init().
ff_tls_deinit()
void ff_tls_deinit (void)
Definition at line 43 of file network.c.
Referenced by avformat_network_deinit().
ff_network_wait_fd()
int ff_network_wait_fd (int fd, int write)
Definition at line 73 of file network.c.
Referenced by ff_network_wait_fd_timeout(), rtp_write(), udp_read(), udp_write(), unix_read(), and unix_write().
ff_network_wait_fd_timeout()
int ff_network_wait_fd_timeout (int fd, int write, int64_t timeout, AVIOInterruptCB * int_cb)
This works similarly to ff_network_wait_fd, but waits up to 'timeout' microseconds Uses ff_network_wait_fd in a loop.
Socket descriptor Set 1 to wait for socket able to be read, 0 to be written Timeout interval, in microseconds. Actual precision is 100000 mcs, due to ff_network_wait_fd usage
Parameters
int_cb Interrupt callback, is checked before each ff_network_wait_fd call
Returns
0 if data can be read/written, AVERROR(ETIMEDOUT) if timeout expired, or negative error code
Definition at line 82 of file network.c.
Referenced by tcp_read(), and tcp_write().
ff_inet_aton()
int ff_inet_aton (const char * str, struct in_addr * add)
Referenced by resolve_host().
ff_getaddrinfo()
int ff_getaddrinfo (const char * node, const char * service, const struct addrinfo * hints, struct addrinfo ** res)
ff_freeaddrinfo()
void ff_freeaddrinfo (struct addrinfo * res)
ff_getnameinfo()
int ff_getnameinfo (const struct sockaddr * sa, int salen, char * host, int hostlen, char * serv, int servlen, int flags)
ff_gai_strerror()
const char* ff_gai_strerror (int ecode)
ff_is_multicast_address()
int ff_is_multicast_address (struct sockaddr * addr)
Definition at line 131 of file network.c.
Referenced by ff_udp_set_remote_url().
ff_listen_bind()
int ff_listen_bind (int fd, const struct sockaddr * addr, socklen_t addrlen, int timeout, URLContext * h)
Bind to a file descriptor and poll for a connection.
Parameters
fd First argument of bind().
addr Second argument of bind().
addrlen Third argument of bind().
timeout Polling timeout in milliseconds.
h URLContext providing interrupt check callback and logging context.
Returns
A non-blocking file descriptor on success or an AVERROR on failure.
Definition at line 226 of file network.c.
Referenced by sctp_open(), tcp_open(), and unix_open().
ff_listen()
int ff_listen (int fd, const struct sockaddr * addr, socklen_t addrlen)
Bind to a file descriptor to an address without accepting connections.
Parameters
fd First argument of bind().
addr Second argument of bind().
addrlen Third argument of bind().
Returns
0 on success or an AVERROR on failure.
Definition at line 190 of file network.c.
Referenced by ff_listen_bind(), and tcp_open().
ff_accept()
int ff_accept (int fd, int timeout, URLContext * h)
Poll for a single connection on the passed file descriptor.
Parameters
fd The listening socket file descriptor.
timeout Polling timeout in milliseconds.
h URLContext providing interrupt check callback and logging context.
Returns
A non-blocking file descriptor on success or an AVERROR on failure.
Definition at line 208 of file network.c.
Referenced by ff_listen_bind(), and tcp_accept().
ff_listen_connect()
int ff_listen_connect (int fd, const struct sockaddr * addr, socklen_t addrlen, int timeout, URLContext * h, int will_try_next)
Connect to a file descriptor and poll for result.
Parameters
fd First argument of connect(), will be set as non-blocking.
addr Second argument of connect().
addrlen Third argument of connect().
timeout Polling timeout in milliseconds.
h URLContext providing interrupt check callback and logging context.
will_try_next Whether the caller will try to connect to another address for the same host name, affecting the form of logged errors.
Returns
0 on success, AVERROR on failure.
Definition at line 238 of file network.c.
Referenced by sctp_open(), tcp_open(), and unix_open().
ff_http_match_no_proxy()
int ff_http_match_no_proxy (const char * no_proxy, const char * hostname)
Definition at line 307 of file network.c.
Referenced by ff_tls_open_underlying(), http_open_cnx_internal(), and test().
ff_socket()
int ff_socket (int domain, int type, int protocol)
Definition at line 166 of file network.c.
Referenced by sctp_open(), tcp_open(), udp_socket_create(), and unix_open().
Variable Documentation
ff_network_inited_globally
int ff_network_inited_globally
Definition at line 53 of file network.c.
Referenced by avformat_network_deinit(), avformat_network_init(), and ff_network_init().