FFmpeg: libavcodec/noise_bsf.c File Reference
noise_bsf.c File Reference
#include <stdlib.h>
#include <string.h>
#include "avcodec.h"
#include "bsf.h"
#include "libavutil/log.h"
#include "libavutil/mem.h"
#include "libavutil/opt.h"
Data Structures
struct NoiseContext
Macros
#define OFFSET(x) offsetof(NoiseContext, x)
Functions
static int noise (AVBSFContext *ctx, AVPacket *out)
Variables
static const AVOption options []
static const AVClass noise_class
const AVBitStreamFilter ff_noise_bsf
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(NoiseContext, x)
Definition at line 73 of file noise_bsf.c.
Function Documentation
noise()
static int noise (AVBSFContext * ctx, AVPacket * out) static
Definition at line 37 of file noise_bsf.c.
Referenced by avfilter_register_all(), dss_sp_sf_synthesis(), ff_eac3_apply_spectral_extension(), init_quantization_noise(), sbr_hf_apply_noise(), swri_noise_shaping(), and wma_decode_block().
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "amount", NULL, OFFSET(amount), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, INT_MAX },
    { NULL },
}
Definition at line 74 of file noise_bsf.c.
noise_class
const AVClass noise_class static
Initial value:
= {
    .class_name = "noise",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 79 of file noise_bsf.c.
ff_noise_bsf
const AVBitStreamFilter ff_noise_bsf
Initial value:
= {
    .name           = "noise",
    .priv_data_size = sizeof(NoiseContext),
    .priv_class     = &noise_class,
    .filter         = noise,
}
Definition at line 86 of file noise_bsf.c.