FFmpeg: libavformat/nsvdec.c File Reference
nsvdec.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/mathematics.h"
#include "avformat.h"
#include "internal.h"
#include "libavutil/dict.h"
#include "libavutil/intreadwrite.h"
Data Structures
struct NSVStream
struct NSVContext
Macros
#define NSV_MAX_RESYNC (500*1024)
#define NSV_MAX_RESYNC_TRIES 300
#define T_NSVF MKTAG('N', 'S', 'V', 'f') /* file header */
#define T_NSVS MKTAG('N', 'S', 'V', 's') /* chunk header */
#define T_TOC2 MKTAG('T', 'O', 'C', '2') /* extra index marker */
#define T_NONE MKTAG('N', 'O', 'N', 'E') /* null a/v 4CC */
#define T_SUBT MKTAG('S', 'U', 'B', 'T') /* subtitle aux data */
#define T_ASYN MKTAG('A', 'S', 'Y', 'N') /* async a/v aux marker */
#define T_KEYF MKTAG('K', 'E', 'Y', 'F') /* video keyframe aux marker (addition) */
#define TB_NSVF MKBETAG('N', 'S', 'V', 'f')
#define TB_NSVS MKBETAG('N', 'S', 'V', 's')
#define NSV_ST_VIDEO 0
#define NSV_ST_AUDIO 1
#define NSV_ST_SUBT 2
#define print_tag(str, tag, size)
Enumerations
enum NSVStatus {
NSV_UNSYNC, NSV_FOUND_NSVF, NSV_HAS_READ_NSVF, NSV_FOUND_NSVS,
NSV_HAS_READ_NSVS, NSV_FOUND_BEEF, NSV_GOT_VIDEO, NSV_GOT_AUDIO
}
Functions
static int nsv_read_chunk (AVFormatContext *s, int fill_header)
static int nsv_resync (AVFormatContext *s)
static int nsv_parse_NSVf_header (AVFormatContext *s)
static int nsv_parse_NSVs_header (AVFormatContext *s)
static int nsv_read_header (AVFormatContext *s)
static int nsv_read_packet (AVFormatContext *s, AVPacket *pkt)
static int nsv_read_seek (AVFormatContext *s, int stream_index, int64_t timestamp, int flags)
static int nsv_read_close (AVFormatContext *s)
static int nsv_probe (AVProbeData *p)
Variables
static const AVCodecTag nsv_codec_video_tags []
static const AVCodecTag nsv_codec_audio_tags []
AVInputFormat ff_nsv_demuxer
Macro Definition Documentation
NSV_MAX_RESYNC
#define NSV_MAX_RESYNC (500*1024)
Definition at line 34 of file nsvdec.c.
Referenced by nsv_resync().
NSV_MAX_RESYNC_TRIES
#define NSV_MAX_RESYNC_TRIES 300
Definition at line 35 of file nsvdec.c.
Referenced by nsv_read_chunk(), and nsv_read_header().
T_NSVF
#define T_NSVF MKTAG('N', 'S', 'V', 'f') /* file header */
Definition at line 126 of file nsvdec.c.
T_NSVS
#define T_NSVS MKTAG('N', 'S', 'V', 's') /* chunk header */
Definition at line 127 of file nsvdec.c.
T_TOC2
#define T_TOC2 MKTAG('T', 'O', 'C', '2') /* extra index marker */
Definition at line 128 of file nsvdec.c.
T_NONE
#define T_NONE MKTAG('N', 'O', 'N', 'E') /* null a/v 4CC */
Definition at line 129 of file nsvdec.c.
Referenced by nsv_parse_NSVs_header().
T_SUBT
#define T_SUBT MKTAG('S', 'U', 'B', 'T') /* subtitle aux data */
Definition at line 130 of file nsvdec.c.
T_ASYN
#define T_ASYN MKTAG('A', 'S', 'Y', 'N') /* async a/v aux marker */
Definition at line 131 of file nsvdec.c.
T_KEYF
#define T_KEYF MKTAG('K', 'E', 'Y', 'F') /* video keyframe aux marker (addition) */
Definition at line 132 of file nsvdec.c.
TB_NSVF
#define TB_NSVF MKBETAG('N', 'S', 'V', 'f')
Definition at line 134 of file nsvdec.c.
Referenced by nsv_resync().
TB_NSVS
#define TB_NSVS MKBETAG('N', 'S', 'V', 's')
Definition at line 135 of file nsvdec.c.
NSV_ST_VIDEO
#define NSV_ST_VIDEO 0
Definition at line 138 of file nsvdec.c.
Referenced by nsv_parse_NSVs_header(), and nsv_read_chunk().
NSV_ST_AUDIO
#define NSV_ST_AUDIO 1
Definition at line 139 of file nsvdec.c.
Referenced by nsv_parse_NSVs_header(), and nsv_read_chunk().
NSV_ST_SUBT
#define NSV_ST_SUBT 2
Definition at line 140 of file nsvdec.c.
print_tag
#define print_tag (str, tag, size)
Value:
av_log(NULL, AV_LOG_TRACE, "%s: tag=%c%c%c%c\n", \
            str, tag & 0xff,            \
            (tag >> 8) & 0xff,          \
            (tag >> 16) & 0xff,         \
            (tag >> 24) & 0xff);
Definition at line 215 of file nsvdec.c.
Referenced by nsv_parse_NSVs_header().
Enumeration Type Documentation
NSVStatus
enum NSVStatus
Enumerator
NSV_UNSYNC
NSV_FOUND_NSVF
NSV_HAS_READ_NSVF
NSV_FOUND_NSVS
NSV_HAS_READ_NSVS
NSV_FOUND_BEEF
NSV_GOT_VIDEO
NSV_GOT_AUDIO
Definition at line 142 of file nsvdec.c.
Function Documentation
nsv_read_chunk()
static int nsv_read_chunk (AVFormatContext * s, int fill_header) static
Definition at line 530 of file nsvdec.c.
Referenced by nsv_read_header(), and nsv_read_packet().
nsv_resync()
static int nsv_resync (AVFormatContext * s) static
Definition at line 223 of file nsvdec.c.
Referenced by nsv_read_chunk(), and nsv_read_header().
nsv_parse_NSVf_header()
static int nsv_parse_NSVf_header (AVFormatContext * s) static
Definition at line 268 of file nsvdec.c.
Referenced by nsv_read_header().
nsv_parse_NSVs_header()
static int nsv_parse_NSVs_header (AVFormatContext * s) static
Definition at line 377 of file nsvdec.c.
Referenced by nsv_read_chunk(), and nsv_read_header().
nsv_read_header()
static int nsv_read_header (AVFormatContext * s) static
Definition at line 494 of file nsvdec.c.
nsv_read_packet()
static int nsv_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 662 of file nsvdec.c.
nsv_read_seek()
static int nsv_read_seek (AVFormatContext * s, int stream_index, int64_t timestamp, int flags) static
Definition at line 690 of file nsvdec.c.
nsv_read_close()
static int nsv_read_close (AVFormatContext * s) static
Definition at line 709 of file nsvdec.c.
nsv_probe()
static int nsv_probe (AVProbeData * p) static
Definition at line 722 of file nsvdec.c.
Variable Documentation
nsv_codec_video_tags
const AVCodecTag nsv_codec_video_tags[] static
Initial value:
= {
    { AV_CODEC_ID_VP3, MKTAG('V', 'P', '3', ' ') },
    { AV_CODEC_ID_VP3, MKTAG('V', 'P', '3', '0') },
    { AV_CODEC_ID_VP3, MKTAG('V', 'P', '3', '1') },
    { AV_CODEC_ID_VP5, MKTAG('V', 'P', '5', ' ') },
    { AV_CODEC_ID_VP5, MKTAG('V', 'P', '5', '0') },
    { AV_CODEC_ID_VP6, MKTAG('V', 'P', '6', ' ') },
    { AV_CODEC_ID_VP6, MKTAG('V', 'P', '6', '0') },
    { AV_CODEC_ID_VP6, MKTAG('V', 'P', '6', '1') },
    { AV_CODEC_ID_VP6, MKTAG('V', 'P', '6', '2') },
    { AV_CODEC_ID_VP8, MKTAG('V', 'P', '8', '0') },
    { AV_CODEC_ID_MPEG4, MKTAG('X', 'V', 'I', 'D') },
    { AV_CODEC_ID_RAWVIDEO, MKTAG('R', 'G', 'B', '3') },
    { AV_CODEC_ID_NONE, 0 },
}
Definition at line 182 of file nsvdec.c.
nsv_codec_audio_tags
const AVCodecTag nsv_codec_audio_tags[] static
Initial value:
= {
    { AV_CODEC_ID_MP3,       MKTAG('M', 'P', '3', ' ') },
    { AV_CODEC_ID_AAC,       MKTAG('A', 'A', 'C', ' ') },
    { AV_CODEC_ID_AAC,       MKTAG('A', 'A', 'C', 'P') },
    { AV_CODEC_ID_AAC,       MKTAG('V', 'L', 'B', ' ') },
    { AV_CODEC_ID_SPEEX,     MKTAG('S', 'P', 'X', ' ') },
    { AV_CODEC_ID_PCM_U16LE, MKTAG('P', 'C', 'M', ' ') },
    { AV_CODEC_ID_NONE,      0 },
}
Definition at line 202 of file nsvdec.c.
ff_nsv_demuxer
AVInputFormat ff_nsv_demuxer
Initial value:
= {
    .name           = "nsv",
    .long_name      = NULL_IF_CONFIG_SMALL("Nullsoft Streaming Video"),
    .priv_data_size = sizeof(NSVContext),
    .read_probe     = nsv_probe,
    .read_header    = nsv_read_header,
    .read_packet    = nsv_read_packet,
    .read_close     = nsv_read_close,
    .read_seek      = nsv_read_seek,
}
Definition at line 753 of file nsvdec.c.