FFmpeg: libavformat/nut.c File Reference
nut.c File Reference
#include "libavutil/mathematics.h"
#include "libavutil/tree.h"
#include "nut.h"
#include "riff.h"
#include "internal.h"
Functions
void ff_nut_reset_ts (NUTContext *nut, AVRational time_base, int64_t val)
int64_t ff_lsb2full (StreamContext *stream, int64_t lsb)
int ff_nut_sp_pos_cmp (const void *a, const void *b)
int ff_nut_sp_pts_cmp (const void *a, const void *b)
int ff_nut_add_sp (NUTContext *nut, int64_t pos, int64_t back_ptr, int64_t ts)
static int enu_free (void *opaque, void *elem)
void ff_nut_free_sp (NUTContext *nut)
Variables
const AVCodecTag ff_nut_subtitle_tags []
const AVCodecTag ff_nut_data_tags []
const AVCodecTag ff_nut_video_tags []
const AVCodecTag ff_nut_audio_extra_tags []
const AVCodecTag ff_nut_audio_tags []
const AVCodecTag *const ff_nut_codec_tags []
const Dispositions ff_nut_dispositions []
const AVMetadataConv ff_nut_metadata_conv []
Function Documentation
ff_nut_reset_ts()
void ff_nut_reset_ts (NUTContext * nut, AVRational time_base, int64_t val)
Definition at line 240 of file nut.c.
Referenced by decode_syncpoint(), and nut_write_packet().
ff_lsb2full()
int64_t ff_lsb2full (StreamContext * stream, int64_t lsb)
Definition at line 251 of file nut.c.
Referenced by decode_frame_header(), and nut_write_packet().
ff_nut_sp_pos_cmp()
int ff_nut_sp_pos_cmp (const void * a, const void * b)
Definition at line 258 of file nut.c.
Referenced by ff_nut_add_sp(), read_seek(), and write_index().
ff_nut_sp_pts_cmp()
int ff_nut_sp_pts_cmp (const void * a, const void * b)
Definition at line 264 of file nut.c.
Referenced by read_seek().
ff_nut_add_sp()
int ff_nut_add_sp (NUTContext * nut, int64_t pos, int64_t back_ptr, int64_t ts)
Definition at line 270 of file nut.c.
Referenced by decode_syncpoint(), and nut_write_packet().
enu_free()
static int enu_free (void * opaque, void * elem) static
Definition at line 295 of file nut.c.
Referenced by ff_nut_free_sp().
ff_nut_free_sp()
void ff_nut_free_sp (NUTContext * nut)
Definition at line 301 of file nut.c.
Referenced by nut_read_close(), and nut_write_deinit().
Variable Documentation
ff_nut_subtitle_tags
const AVCodecTag ff_nut_subtitle_tags[]
Initial value:
= {
    { AV_CODEC_ID_TEXT,             MKTAG('U', 'T', 'F', '8') },
    { AV_CODEC_ID_DVD_SUBTITLE,     MKTAG('D', 'V', 'D', 'S') },
    { AV_CODEC_ID_DVB_SUBTITLE,     MKTAG('D', 'V', 'B', 'S') },
    { AV_CODEC_ID_DVB_TELETEXT,     MKTAG('D', 'V', 'B', 'T') },
    { AV_CODEC_ID_NONE,             0                         }
}
Definition at line 28 of file nut.c.
Referenced by decode_stream_header().
ff_nut_data_tags
const AVCodecTag ff_nut_data_tags[]
Initial value:
= {
    { AV_CODEC_ID_TEXT,             MKTAG('U', 'T', 'F', '8') },
    { AV_CODEC_ID_NONE,             0 }
}
Definition at line 36 of file nut.c.
Referenced by decode_stream_header().
ff_nut_video_tags
const AVCodecTag ff_nut_video_tags[]
Definition at line 41 of file nut.c.
Referenced by decode_stream_header().
ff_nut_audio_extra_tags
const AVCodecTag ff_nut_audio_extra_tags[]
Initial value:
= {
    { AV_CODEC_ID_COMFORT_NOISE,    MKTAG('3', '3', '8', '9') },
    { AV_CODEC_ID_PCM_ALAW,         MKTAG('A', 'L', 'A', 'W') },
    { AV_CODEC_ID_PCM_MULAW,        MKTAG('U', 'L', 'A', 'W') },
    { AV_CODEC_ID_MP3,              MKTAG('M', 'P', '3', ' ') },
    { AV_CODEC_ID_WAVPACK,          MKTAG('w', 'v', 'p', 'k') },
    { AV_CODEC_ID_NONE,             0                         }
}
Definition at line 199 of file nut.c.
Referenced by decode_stream_header().
ff_nut_audio_tags
const AVCodecTag ff_nut_audio_tags[]
Initial value:
= {
    { AV_CODEC_ID_PCM_F32BE,        MKTAG(32 , 'D', 'F', 'P') },
    { AV_CODEC_ID_PCM_F32LE,        MKTAG('P', 'F', 'D', 32 ) },
    { AV_CODEC_ID_PCM_F64BE,        MKTAG(64 , 'D', 'F', 'P') },
    { AV_CODEC_ID_PCM_F64LE,        MKTAG('P', 'F', 'D', 64 ) },
    { AV_CODEC_ID_PCM_S16BE,        MKTAG(16 , 'D', 'S', 'P') },
    { AV_CODEC_ID_PCM_S16LE,        MKTAG('P', 'S', 'D', 16 ) },
    { AV_CODEC_ID_PCM_S24BE,        MKTAG(24 , 'D', 'S', 'P') },
    { AV_CODEC_ID_PCM_S24LE,        MKTAG('P', 'S', 'D', 24 ) },
    { AV_CODEC_ID_PCM_S32BE,        MKTAG(32 , 'D', 'S', 'P') },
    { AV_CODEC_ID_PCM_S32LE,        MKTAG('P', 'S', 'D', 32 ) },
    { AV_CODEC_ID_PCM_S8,           MKTAG('P', 'S', 'D',  8 ) },
    { AV_CODEC_ID_PCM_U16BE,        MKTAG(16 , 'D', 'U', 'P') },
    { AV_CODEC_ID_PCM_U16LE,        MKTAG('P', 'U', 'D', 16 ) },
    { AV_CODEC_ID_PCM_U24BE,        MKTAG(24 , 'D', 'U', 'P') },
    { AV_CODEC_ID_PCM_U24LE,        MKTAG('P', 'U', 'D', 24 ) },
    { AV_CODEC_ID_PCM_U32BE,        MKTAG(32 , 'D', 'U', 'P') },
    { AV_CODEC_ID_PCM_U32LE,        MKTAG('P', 'U', 'D', 32 ) },
    { AV_CODEC_ID_PCM_U8,           MKTAG('P', 'U', 'D',  8 ) },
    { AV_CODEC_ID_PCM_S8_PLANAR,    MKTAG('P', 'S', 'P',  8 ) },
    { AV_CODEC_ID_PCM_S16BE_PLANAR, MKTAG(16 , 'P', 'S', 'P') },
    { AV_CODEC_ID_PCM_S16LE_PLANAR, MKTAG('P', 'S', 'P', 16 ) },
    { AV_CODEC_ID_PCM_S24LE_PLANAR, MKTAG('P', 'S', 'P', 24 ) },
    { AV_CODEC_ID_PCM_S32LE_PLANAR, MKTAG('P', 'S', 'P', 32 ) },
    { AV_CODEC_ID_NONE,             0                         }
}
Definition at line 208 of file nut.c.
Referenced by decode_stream_header().
ff_nut_codec_tags
const AVCodecTag* const ff_nut_codec_tags[]
Initial value:
= {
    ff_nut_video_tags, ff_nut_audio_tags, ff_nut_subtitle_tags,
    ff_codec_bmp_tags, ff_codec_wav_tags, ff_nut_audio_extra_tags, ff_nut_data_tags, 0
}
Definition at line 235 of file nut.c.
ff_nut_dispositions
const Dispositions ff_nut_dispositions[]
Initial value:
= {
    { "default",        AV_DISPOSITION_DEFAULT  },
    { "dub",            AV_DISPOSITION_DUB      },
    { "original",       AV_DISPOSITION_ORIGINAL },
    { "comment",        AV_DISPOSITION_COMMENT  },
    { "lyrics",         AV_DISPOSITION_LYRICS   },
    { "karaoke",        AV_DISPOSITION_KARAOKE  },
    { "",               0                       }
}
Definition at line 309 of file nut.c.
Referenced by set_disposition_bits(), and write_streaminfo().
ff_nut_metadata_conv
const AVMetadataConv ff_nut_metadata_conv[]
Initial value:
= {
    { "Author",         "artist"      },
    { "X-CreationTime", "date"        },
    { "CreationTime",   "date"        },
    { "SourceFilename", "filename"    },
    { "X-Language",     "language"    },
    { "X-Disposition",  "disposition" },
    { "X-Replaces",     "replaces"    },
    { "X-Depends",      "depends"     },
    { "X-Uses",         "uses"        },
    { "X-UsesFont",     "usesfont"    },
    { 0 },
}
Definition at line 319 of file nut.c.
Referenced by nut_read_header(), and write_headers().