FFmpeg: libavformat/nutdec.c File Reference
nutdec.c File Reference
#include "libavutil/avstring.h"
#include "libavutil/avassert.h"
#include "libavutil/bswap.h"
#include "libavutil/dict.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/mathematics.h"
#include "libavutil/tree.h"
#include "libavcodec/bytestream.h"
#include "avio_internal.h"
#include "isom.h"
#include "nut.h"
#include "riff.h"
Macros
#define NUT_MAX_STREAMS 256 /* arbitrary sanity check value */
#define GET_V(dst, check)
Functions
static int64_t nut_read_timestamp (AVFormatContext *s, int stream_index, int64_t *pos_arg, int64_t pos_limit)
static int get_str (AVIOContext *bc, char *string, unsigned int maxlen)
static int64_t get_s (AVIOContext *bc)
static uint64_t get_fourcc (AVIOContext *bc)
static int get_packetheader (NUTContext *nut, AVIOContext *bc, int calculate_checksum, uint64_t startcode)
static uint64_t find_any_startcode (AVIOContext *bc, int64_t pos)
static int64_t find_startcode (AVIOContext *bc, uint64_t code, int64_t pos)
Find the given startcode.
static int nut_probe (AVProbeData *p)
static int skip_reserved (AVIOContext *bc, int64_t pos)
static int decode_main_header (NUTContext *nut)
static int decode_stream_header (NUTContext *nut)
static void set_disposition_bits (AVFormatContext *avf, char *value, int stream_id)
static int decode_info_header (NUTContext *nut)
static int decode_syncpoint (NUTContext *nut, int64_t *ts, int64_t *back_ptr)
static int64_t find_duration (NUTContext *nut, int64_t filesize)
static int find_and_decode_index (NUTContext *nut)
static int nut_read_close (AVFormatContext *s)
static int nut_read_header (AVFormatContext *s)
static int read_sm_data (AVFormatContext *s, AVIOContext *bc, AVPacket *pkt, int is_meta, int64_t maxpos)
static int decode_frame_header (NUTContext *nut, int64_t *pts, int *stream_id, uint8_t *header_idx, int frame_code)
static int decode_frame (NUTContext *nut, AVPacket *pkt, int frame_code)
static int nut_read_packet (AVFormatContext *s, AVPacket *pkt)
static int read_seek (AVFormatContext *s, int stream_index, int64_t pts, int flags)
Variables
AVInputFormat ff_nut_demuxer
Macro Definition Documentation
NUT_MAX_STREAMS
#define NUT_MAX_STREAMS 256 /* arbitrary sanity check value */
Definition at line 36 of file nutdec.c.
Referenced by decode_main_header().
GET_V
#define GET_V (dst, check)
Value:
do {                                                                      \
        tmp = ffio_read_varlen(bc);                                           \
        if (!(check)) {                                                       \
            av_log(s, AV_LOG_ERROR, "Error " #dst " is (%"PRId64")\n", tmp);  \
            ret = AVERROR_INVALIDDATA;                                        \
            goto fail;                                                        \
        }                                                                     \
        dst = tmp;                                                            \
    } while (0)
Definition at line 201 of file nutdec.c.
Referenced by decode_frame_header(), decode_info_header(), decode_main_header(), decode_stream_header(), and find_and_decode_index().
Function Documentation
nut_read_timestamp()
static int64_t nut_read_timestamp (AVFormatContext * s, int stream_index, int64_t * pos_arg, int64_t pos_limit) static
Definition at line 1230 of file nutdec.c.
Referenced by find_duration(), and read_seek().
get_str()
static int get_str (AVIOContext * bc, char * string, unsigned int maxlen) static
Definition at line 41 of file nutdec.c.
Referenced by decode_info_header(), and read_sm_data().
get_s()
static int64_t get_s (AVIOContext * bc) static
Definition at line 65 of file nutdec.c.
Referenced by decode_frame_header(), decode_info_header(), decode_main_header(), get_fourcc(), and read_sm_data().
get_fourcc()
static uint64_t get_fourcc (AVIOContext * bc) static
Definition at line 75 of file nutdec.c.
Referenced by decode_stream_header().
get_packetheader()
static int get_packetheader (NUTContext * nut, AVIOContext * bc, int calculate_checksum, uint64_t startcode) static
Definition at line 124 of file nutdec.c.
Referenced by decode_info_header(), decode_main_header(), decode_stream_header(), decode_syncpoint(), find_and_decode_index(), and nut_read_packet().
find_any_startcode()
static uint64_t find_any_startcode (AVIOContext * bc, int64_t pos) static
Definition at line 145 of file nutdec.c.
Referenced by find_startcode(), nut_read_header(), and nut_read_packet().
find_startcode()
static int64_t find_startcode (AVIOContext * bc, uint64_t code, int64_t pos) static
Find the given startcode.
Parameters
code the startcode
pos the start position of the search, or -1 if the current position
Returns
the position of the startcode or -1 if not found
Definition at line 176 of file nutdec.c.
Referenced by nut_read_header(), nut_read_timestamp(), and read_seek().
nut_probe()
static int nut_probe (AVProbeData * p) static
Definition at line 188 of file nutdec.c.
skip_reserved()
static int skip_reserved (AVIOContext * bc, int64_t pos) static
Definition at line 212 of file nutdec.c.
Referenced by decode_info_header(), decode_main_header(), decode_stream_header(), decode_syncpoint(), and find_and_decode_index().
decode_main_header()
static int decode_main_header (NUTContext * nut) static
Definition at line 228 of file nutdec.c.
Referenced by nut_read_header().
decode_stream_header()
static int decode_stream_header (NUTContext * nut) static
Definition at line 398 of file nutdec.c.
Referenced by nut_read_header().
set_disposition_bits()
static void set_disposition_bits (AVFormatContext * avf, char * value, int stream_id) static
Definition at line 505 of file nutdec.c.
Referenced by decode_info_header().
decode_info_header()
static int decode_info_header (NUTContext * nut) static
Definition at line 520 of file nutdec.c.
Referenced by nut_read_header(), and nut_read_packet().
decode_syncpoint()
static int decode_syncpoint (NUTContext * nut, int64_t * ts, int64_t * back_ptr) static
Definition at line 643 of file nutdec.c.
Referenced by nut_read_packet(), and nut_read_timestamp().
find_duration()
static int64_t find_duration (NUTContext * nut, int64_t filesize) static
Definition at line 687 of file nutdec.c.
Referenced by find_and_decode_index().
find_and_decode_index()
static int find_and_decode_index (NUTContext * nut) static
Definition at line 699 of file nutdec.c.
Referenced by nut_read_header().
nut_read_close()
static int nut_read_close (AVFormatContext * s) static
Definition at line 813 of file nutdec.c.
Referenced by nut_read_header().
nut_read_header()
static int nut_read_header (AVFormatContext * s) static
Definition at line 827 of file nutdec.c.
read_sm_data()
static int read_sm_data (AVFormatContext * s, AVIOContext * bc, AVPacket * pkt, int is_meta, int64_t maxpos) static
Definition at line 896 of file nutdec.c.
Referenced by decode_frame().
decode_frame_header()
static int decode_frame_header (NUTContext * nut, int64_t * pts, int * stream_id, uint8_t * header_idx, int frame_code) static
Definition at line 1021 of file nutdec.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (NUTContext * nut, AVPacket * pkt, int frame_code) static
Definition at line 1104 of file nutdec.c.
Referenced by nut_read_packet().
nut_read_packet()
static int nut_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 1172 of file nutdec.c.
read_seek()
static int read_seek (AVFormatContext * s, int stream_index, int64_t pts, int flags) static
Definition at line 1257 of file nutdec.c.
Variable Documentation
ff_nut_demuxer
AVInputFormat ff_nut_demuxer
Initial value:
= {
    .name           = "nut",
    .long_name      = NULL_IF_CONFIG_SMALL("NUT"),
    .flags          = AVFMT_SEEK_TO_PTS,
    .priv_data_size = sizeof(NUTContext),
    .read_probe     = nut_probe,
    .read_header    = nut_read_header,
    .read_packet    = nut_read_packet,
    .read_close     = nut_read_close,
    .read_seek      = read_seek,
    .extensions     = "nut",
    .codec_tag      = ff_nut_codec_tags,
}
Definition at line 1329 of file nutdec.c.