FFmpeg: libavformat/oggdec.c File Reference
oggdec.c File Reference
#include <stdio.h>
#include "libavutil/avassert.h"
#include "libavutil/intreadwrite.h"
#include "oggdec.h"
#include "avformat.h"
#include "internal.h"
#include "vorbiscomment.h"
Macros
#define MAX_PAGE_SIZE 65307
#define DECODER_BUFFER_SIZE MAX_PAGE_SIZE
Functions
static int64_t ogg_calc_pts (AVFormatContext *s, int idx, int64_t *dts)
static int ogg_new_stream (AVFormatContext *s, uint32_t serial)
static int ogg_restore (AVFormatContext *s, int discard)
static int ogg_save (AVFormatContext *s)
static int ogg_reset (AVFormatContext *s)
static const struct ogg_codec * ogg_find_codec (uint8_t *buf, int size)
static int ogg_replace_stream (AVFormatContext *s, uint32_t serial, int nsegs)
Replace the current stream with a new one.
static int ogg_new_buf (struct ogg *ogg, int idx)
static int data_packets_seen (const struct ogg *ogg)
static int ogg_read_page (AVFormatContext *s, int *sid)
static int ogg_packet (AVFormatContext *s, int *sid, int *dstart, int *dsize, int64_t *fpos)
find the next Ogg packet
static int ogg_get_length (AVFormatContext *s)
static int ogg_read_close (AVFormatContext *s)
static int ogg_read_header (AVFormatContext *s)
static void ogg_validate_keyframe (AVFormatContext *s, int idx, int pstart, int psize)
static int ogg_read_packet (AVFormatContext *s, AVPacket *pkt)
static int64_t ogg_read_timestamp (AVFormatContext *s, int stream_index, int64_t *pos_arg, int64_t pos_limit)
static int ogg_read_seek (AVFormatContext *s, int stream_index, int64_t timestamp, int flags)
static int ogg_probe (AVProbeData *p)
Variables
static const struct ogg_codec *const ogg_codecs []
AVInputFormat ff_ogg_demuxer
Macro Definition Documentation
MAX_PAGE_SIZE
#define MAX_PAGE_SIZE 65307
Definition at line 39 of file oggdec.c.
Referenced by ogg_get_length(), and ogg_read_page().
DECODER_BUFFER_SIZE
#define DECODER_BUFFER_SIZE MAX_PAGE_SIZE
Definition at line 40 of file oggdec.c.
Referenced by ogg_new_stream().
Function Documentation
ogg_calc_pts()
static int64_t ogg_calc_pts (AVFormatContext * s, int idx, int64_t * dts) static
Definition at line 730 of file oggdec.c.
Referenced by ogg_get_length(), ogg_read_packet(), and ogg_read_timestamp().
ogg_new_stream()
static int ogg_new_stream (AVFormatContext * s, uint32_t serial) static
Definition at line 244 of file oggdec.c.
Referenced by ogg_read_page(), and ogg_replace_stream().
ogg_restore()
static int ogg_restore (AVFormatContext * s, int discard) static
Definition at line 103 of file oggdec.c.
Referenced by ogg_get_length(), and ogg_save().
ogg_save()
static int ogg_save (AVFormatContext * s) static
Definition at line 67 of file oggdec.c.
Referenced by ogg_get_length().
ogg_reset()
static int ogg_reset (AVFormatContext * s) static
Definition at line 138 of file oggdec.c.
Referenced by ogg_get_length(), ogg_read_packet(), ogg_read_seek(), and ogg_read_timestamp().
ogg_find_codec()
static const struct ogg_codec* ogg_find_codec (uint8_t * buf, int size) static
Definition at line 172 of file oggdec.c.
Referenced by ogg_packet(), and ogg_replace_stream().
ogg_replace_stream()
static int ogg_replace_stream (AVFormatContext * s, uint32_t serial, int nsegs) static
Replace the current stream with a new one.
This is a typical webradio situation where a new audio stream spawn (identified with a new serial) and must replace the previous one (track switch).
Definition at line 189 of file oggdec.c.
Referenced by ogg_read_page().
ogg_new_buf()
static int ogg_new_buf (struct ogg * ogg, int idx) static
Definition at line 286 of file oggdec.c.
Referenced by ogg_read_page().
data_packets_seen()
static int data_packets_seen (const struct ogg * ogg) static
Definition at line 307 of file oggdec.c.
Referenced by ogg_read_page().
ogg_read_page()
static int ogg_read_page (AVFormatContext * s, int * sid) static
Definition at line 317 of file oggdec.c.
Referenced by ogg_get_length(), and ogg_packet().
ogg_packet()
static int ogg_packet (AVFormatContext * s, int * sid, int * dstart, int * dsize, int64_t * fpos) static
find the next Ogg packet
Parameters
*sid is set to the stream for the packet or -1 if there is no matching stream, in that case assume all other return values to be uninitialized.
Returns
negative value on error or EOF.
Definition at line 458 of file oggdec.c.
Referenced by encode_frame(), encode_init(), libvorbis_encode_frame(), libvorbis_encode_init(), ogg_get_length(), ogg_read_header(), ogg_read_packet(), ogg_read_timestamp(), and oggvorbis_decode_frame().
ogg_get_length()
static int ogg_get_length (AVFormatContext * s) static
Definition at line 593 of file oggdec.c.
Referenced by ogg_read_header().
ogg_read_close()
static int ogg_read_close (AVFormatContext * s) static
Definition at line 662 of file oggdec.c.
Referenced by ogg_read_header().
ogg_read_header()
static int ogg_read_header (AVFormatContext * s) static
Definition at line 683 of file oggdec.c.
ogg_validate_keyframe()
static void ogg_validate_keyframe (AVFormatContext * s, int idx, int pstart, int psize) static
Definition at line 760 of file oggdec.c.
Referenced by ogg_read_packet(), and ogg_read_timestamp().
ogg_read_packet()
static int ogg_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 781 of file oggdec.c.
ogg_read_timestamp()
static int64_t ogg_read_timestamp (AVFormatContext * s, int stream_index, int64_t * pos_arg, int64_t pos_limit) static
Definition at line 854 of file oggdec.c.
ogg_read_seek()
static int ogg_read_seek (AVFormatContext * s, int stream_index, int64_t timestamp, int flags) static
Definition at line 895 of file oggdec.c.
ogg_probe()
static int ogg_probe (AVProbeData * p) static
Definition at line 921 of file oggdec.c.
Variable Documentation
ogg_codecs
const struct ogg_codec* const ogg_codecs[] static
Initial value:
= {
    &ff_skeleton_codec,
    &ff_daala_codec,
    &ff_dirac_codec,
    &ff_speex_codec,
    &ff_vorbis_codec,
    &ff_theora_codec,
    &ff_flac_codec,
    &ff_celt_codec,
    &ff_opus_codec,
    &ff_vp8_codec,
    &ff_old_dirac_codec,
    &ff_old_flac_codec,
    &ff_ogm_video_codec,
    &ff_ogm_audio_codec,
    &ff_ogm_text_codec,
    &ff_ogm_old_codec,
    NULL
}
Definition at line 42 of file oggdec.c.
ff_ogg_demuxer
AVInputFormat ff_ogg_demuxer
Initial value:
= {
    .name           = "ogg",
    .long_name      = NULL_IF_CONFIG_SMALL("Ogg"),
    .priv_data_size = sizeof(struct ogg),
    .read_probe     = ogg_probe,
    .read_header    = ogg_read_header,
    .read_packet    = ogg_read_packet,
    .read_close     = ogg_read_close,
    .read_seek      = ogg_read_seek,
    .read_timestamp = ogg_read_timestamp,
    .extensions     = "ogg",
    .flags          = AVFMT_GENERIC_INDEX | AVFMT_TS_DISCONT | AVFMT_NOBINSEARCH,
}
Definition at line 928 of file oggdec.c.