FFmpeg: libavformat/oggdec.h File Reference
oggdec.h File Reference
#include "avformat.h"
#include "metadata.h"
Data Structures
struct ogg_codec
Copyright (C) 2005 Michael Ahlberg, Måns Rullgård.
struct ogg_stream
struct ogg_state
struct ogg
Macros
#define OGG_FLAG_CONT 1
#define OGG_FLAG_BOS 2
#define OGG_FLAG_EOS 4
#define OGG_NOGRANULE_VALUE (-1ull)
Functions
int ff_vorbis_comment (AVFormatContext *ms, AVDictionary **m, const uint8_t *buf, int size, int parse_picture)
int ff_vorbis_stream_comment (AVFormatContext *as, AVStream *st, const uint8_t *buf, int size)
static int ogg_find_stream (struct ogg *ogg, int serial)
static uint64_t ogg_gptopts (AVFormatContext *s, int i, uint64_t gp, int64_t *dts)
Variables
const struct ogg_codec ff_celt_codec
const struct ogg_codec ff_daala_codec
const struct ogg_codec ff_dirac_codec
const struct ogg_codec ff_flac_codec
const struct ogg_codec ff_ogm_audio_codec
const struct ogg_codec ff_ogm_old_codec
const struct ogg_codec ff_ogm_text_codec
const struct ogg_codec ff_ogm_video_codec
const struct ogg_codec ff_old_dirac_codec
const struct ogg_codec ff_old_flac_codec
const struct ogg_codec ff_opus_codec
const struct ogg_codec ff_skeleton_codec
const struct ogg_codec ff_speex_codec
const struct ogg_codec ff_theora_codec
const struct ogg_codec ff_vorbis_codec
const struct ogg_codec ff_vp8_codec
Macro Definition Documentation
OGG_FLAG_CONT
#define OGG_FLAG_CONT 1
Definition at line 110 of file oggdec.h.
Referenced by ogg_read_page().
OGG_FLAG_BOS
#define OGG_FLAG_BOS 2
Definition at line 111 of file oggdec.h.
Referenced by ogg_read_page(), ogg_read_timestamp(), and opus_header().
OGG_FLAG_EOS
#define OGG_FLAG_EOS 4
Definition at line 112 of file oggdec.h.
Referenced by daala_packet(), ogg_read_timestamp(), opus_packet(), skeleton_header(), speex_packet(), theora_packet(), vorbis_packet(), and vp8_packet().
OGG_NOGRANULE_VALUE
#define OGG_NOGRANULE_VALUE (-1ull)
Definition at line 114 of file oggdec.h.
Referenced by ogg_new_stream(), ogg_read_header(), and skeleton_header().
Function Documentation
ff_vorbis_comment()
int ff_vorbis_comment (AVFormatContext * ms, AVDictionary ** m, const uint8_t * buf, int size, int parse_picture)
Definition at line 87 of file oggparsevorbis.c.
Referenced by ff_vorbis_stream_comment(), flac_read_header(), and matroska_parse_flac().
ff_vorbis_stream_comment()
int ff_vorbis_stream_comment (AVFormatContext * as, AVStream * st, const uint8_t * buf, int size)
Definition at line 75 of file oggparsevorbis.c.
Referenced by celt_header(), daala_header(), flac_header(), ogm_header(), opus_header(), speex_header(), theora_header(), vorbis_update_metadata(), and vp8_header().
ogg_find_stream()
static int ogg_find_stream (struct ogg * ogg, int serial) inline static
Definition at line 140 of file oggdec.h.
Referenced by ogg_read_page(), and skeleton_header().
ogg_gptopts()
static uint64_t ogg_gptopts (AVFormatContext * s, int i, uint64_t gp, int64_t * dts) inline static
Definition at line 152 of file oggdec.h.
Referenced by ogg_calc_pts(), ogg_get_length(), and ogg_read_header().
Variable Documentation
ff_celt_codec
const struct ogg_codec ff_celt_codec
Definition at line 85 of file oggparsecelt.c.
Referenced by celt_header().
ff_daala_codec
const struct ogg_codec ff_daala_codec
Definition at line 247 of file oggparsedaala.c.
Referenced by daala_header().
ff_dirac_codec
const struct ogg_codec ff_dirac_codec
Definition at line 116 of file oggparsedirac.c.
ff_flac_codec
const struct ogg_codec ff_flac_codec
Definition at line 128 of file oggparseflac.c.
ff_ogm_audio_codec
const struct ogg_codec ff_ogm_audio_codec
Definition at line 195 of file oggparseogm.c.
ff_ogm_old_codec
const struct ogg_codec ff_ogm_old_codec
Definition at line 213 of file oggparseogm.c.
ff_ogm_text_codec
const struct ogg_codec ff_ogm_text_codec
Definition at line 204 of file oggparseogm.c.
ff_ogm_video_codec
const struct ogg_codec ff_ogm_video_codec
Definition at line 186 of file oggparseogm.c.
Referenced by ogg_read_timestamp().
ff_old_dirac_codec
const struct ogg_codec ff_old_dirac_codec
Definition at line 125 of file oggparsedirac.c.
ff_old_flac_codec
const struct ogg_codec ff_old_flac_codec
Definition at line 135 of file oggparseflac.c.
ff_opus_codec
const struct ogg_codec ff_opus_codec
Definition at line 179 of file oggparseopus.c.
ff_skeleton_codec
const struct ogg_codec ff_skeleton_codec
Definition at line 96 of file oggparseskeleton.c.
ff_speex_codec
const struct ogg_codec ff_speex_codec
Definition at line 147 of file oggparsespeex.c.
ff_theora_codec
const struct ogg_codec ff_theora_codec
Definition at line 207 of file oggparsetheora.c.
ff_vorbis_codec
const struct ogg_codec ff_vorbis_codec
Definition at line 496 of file oggparsevorbis.c.
ff_vp8_codec
const struct ogg_codec ff_vp8_codec
Definition at line 139 of file oggparsevp8.c.