FFmpeg: libavformat/oggenc.c File Reference
oggenc.c File Reference
#include <stdint.h>
#include "libavutil/crc.h"
#include "libavutil/mathematics.h"
#include "libavutil/opt.h"
#include "libavutil/random_seed.h"
#include "libavcodec/xiph.h"
#include "libavcodec/bytestream.h"
#include "libavcodec/flac.h"
#include "avformat.h"
#include "avio_internal.h"
#include "internal.h"
#include "vorbiscomment.h"
Data Structures
struct OGGPage
struct OGGStreamContext
struct OGGPageList
struct OGGContext
Macros
#define MAX_PAGE_SIZE 65025
#define OFFSET(x) offsetof(OGGContext, x)
#define PARAM AV_OPT_FLAG_ENCODING_PARAM
#define OGG_CLASS(flavor, name)
#define SPEEX_HEADER_SIZE 80
#define OPUS_HEADER_SIZE 19
#define VP8_HEADER_SIZE 26
Functions
static void ogg_update_checksum (AVFormatContext *s, AVIOContext *pb, int64_t crc_offset)
static int ogg_write_page (AVFormatContext *s, OGGPage *page, int extra_flags)
static int ogg_key_granule (OGGStreamContext *oggstream, int64_t granule)
static int64_t ogg_granule_to_timestamp (OGGStreamContext *oggstream, int64_t granule)
static int ogg_compare_granule (AVFormatContext *s, OGGPage *next, OGGPage *page)
static int ogg_reset_cur_page (OGGStreamContext *oggstream)
static int ogg_buffer_page (AVFormatContext *s, OGGStreamContext *oggstream)
static int ogg_buffer_data (AVFormatContext *s, AVStream *st, uint8_t *data, unsigned size, int64_t granule, int header)
static uint8_t * ogg_write_vorbiscomment (int64_t offset, int bitexact, int *header_len, AVDictionary **m, int framing_bit)
static int ogg_build_flac_headers (AVCodecParameters *par, OGGStreamContext *oggstream, int bitexact, AVDictionary **m)
static int ogg_build_speex_headers (AVCodecParameters *par, OGGStreamContext *oggstream, int bitexact, AVDictionary **m)
static int ogg_build_opus_headers (AVCodecParameters *par, OGGStreamContext *oggstream, int bitexact, AVDictionary **m)
static int ogg_build_vp8_headers (AVFormatContext *s, AVStream *st, OGGStreamContext *oggstream, int bitexact)
static void ogg_write_pages (AVFormatContext *s, int flush)
static int ogg_write_header (AVFormatContext *s)
static int ogg_write_packet_internal (AVFormatContext *s, AVPacket *pkt)
static int ogg_write_packet (AVFormatContext *s, AVPacket *pkt)
static int ogg_write_trailer (AVFormatContext *s)
Variables
static const AVOption options []
Macro Definition Documentation
MAX_PAGE_SIZE
#define MAX_PAGE_SIZE 65025
Definition at line 36 of file oggenc.c.
Referenced by ogg_buffer_data().
OFFSET
#define OFFSET (x) offsetof(OGGContext, x)
Definition at line 79 of file oggenc.c.
PARAM
#define PARAM AV_OPT_FLAG_ENCODING_PARAM
Definition at line 80 of file oggenc.c.
OGG_CLASS
#define OGG_CLASS (flavor, name)
Value:
static const AVClass flavor ## _muxer_class = {\
    .class_name = #name " muxer",\
    .item_name  = av_default_item_name,\
    .option     = options,\
    .version    = LIBAVUTIL_VERSION_INT,\
};
Definition at line 94 of file oggenc.c.
Referenced by ogg_write_trailer().
SPEEX_HEADER_SIZE
#define SPEEX_HEADER_SIZE 80
Definition at line 355 of file oggenc.c.
Referenced by ogg_build_speex_headers().
OPUS_HEADER_SIZE
#define OPUS_HEADER_SIZE 19
Definition at line 384 of file oggenc.c.
Referenced by ogg_build_opus_headers().
VP8_HEADER_SIZE
#define VP8_HEADER_SIZE 26
Definition at line 413 of file oggenc.c.
Referenced by ogg_build_vp8_headers().
Function Documentation
ogg_update_checksum()
static void ogg_update_checksum (AVFormatContext * s, AVIOContext * pb, int64_t crc_offset) static
Definition at line 102 of file oggenc.c.
Referenced by ogg_write_page().
ogg_write_page()
static int ogg_write_page (AVFormatContext * s, OGGPage * page, int extra_flags) static
Definition at line 111 of file oggenc.c.
Referenced by ogg_write_pages().
ogg_key_granule()
static int ogg_key_granule (OGGStreamContext * oggstream, int64_t granule) static
Definition at line 149 of file oggenc.c.
Referenced by ogg_buffer_data().
ogg_granule_to_timestamp()
static int64_t ogg_granule_to_timestamp (OGGStreamContext * oggstream, int64_t granule) static
Definition at line 155 of file oggenc.c.
Referenced by ogg_buffer_data(), ogg_buffer_page(), and ogg_compare_granule().
ogg_compare_granule()
static int ogg_compare_granule (AVFormatContext * s, OGGPage * next, OGGPage * page) static
Definition at line 166 of file oggenc.c.
Referenced by ogg_buffer_page().
ogg_reset_cur_page()
static int ogg_reset_cur_page (OGGStreamContext * oggstream) static
Definition at line 182 of file oggenc.c.
Referenced by ogg_buffer_page().
ogg_buffer_page()
static int ogg_buffer_page (AVFormatContext * s, OGGStreamContext * oggstream) static
Definition at line 191 of file oggenc.c.
Referenced by ogg_buffer_data(), ogg_write_header(), ogg_write_packet(), and ogg_write_trailer().
ogg_buffer_data()
static int ogg_buffer_data (AVFormatContext * s, AVStream * st, uint8_t * data, unsigned size, int64_t granule, int header) static
Definition at line 216 of file oggenc.c.
Referenced by ogg_write_header(), and ogg_write_packet_internal().
ogg_write_vorbiscomment()
static uint8_t* ogg_write_vorbiscomment (int64_t offset, int bitexact, int * header_len, AVDictionary ** m, int framing_bit) static
Definition at line 293 of file oggenc.c.
Referenced by ogg_build_flac_headers(), ogg_build_opus_headers(), ogg_build_speex_headers(), ogg_build_vp8_headers(), and ogg_write_header().
ogg_build_flac_headers()
static int ogg_build_flac_headers (AVCodecParameters * par, OGGStreamContext * oggstream, int bitexact, AVDictionary ** m) static
Definition at line 319 of file oggenc.c.
Referenced by ogg_write_header().
ogg_build_speex_headers()
static int ogg_build_speex_headers (AVCodecParameters * par, OGGStreamContext * oggstream, int bitexact, AVDictionary ** m) static
Definition at line 357 of file oggenc.c.
Referenced by ogg_write_header().
ogg_build_opus_headers()
static int ogg_build_opus_headers (AVCodecParameters * par, OGGStreamContext * oggstream, int bitexact, AVDictionary ** m) static
Definition at line 386 of file oggenc.c.
Referenced by ogg_write_header().
ogg_build_vp8_headers()
static int ogg_build_vp8_headers (AVFormatContext * s, AVStream * st, OGGStreamContext * oggstream, int bitexact) static
Definition at line 415 of file oggenc.c.
Referenced by ogg_write_header().
ogg_write_pages()
static void ogg_write_pages (AVFormatContext * s, int flush) static
Definition at line 464 of file oggenc.c.
Referenced by ogg_write_header(), ogg_write_packet(), ogg_write_packet_internal(), and ogg_write_trailer().
ogg_write_header()
static int ogg_write_header (AVFormatContext * s) static
KFGSHIFT is the width of the less significant section of the granule position The less significant section is the frame count since the last keyframe
Definition at line 486 of file oggenc.c.
Referenced by ogg_write_trailer().
ogg_write_packet_internal()
static int ogg_write_packet_internal (AVFormatContext * s, AVPacket * pkt) static
Definition at line 645 of file oggenc.c.
Referenced by ogg_write_packet().
ogg_write_packet()
static int ogg_write_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 697 of file oggenc.c.
Referenced by ogg_write_trailer().
ogg_write_trailer()
static int ogg_write_trailer (AVFormatContext * s) static
Definition at line 714 of file oggenc.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "serial_offset", "serial number offset",
        OFFSET(serial_offset), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, INT_MAX, PARAM },
    { "oggpagesize", "Set preferred Ogg page size.",
      OFFSET(pref_size), AV_OPT_TYPE_INT, {.i64 = 0}, 0, MAX_PAGE_SIZE, PARAM},
    { "pagesize", "preferred page size in bytes (deprecated)",
        OFFSET(pref_size), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, MAX_PAGE_SIZE, PARAM },
    { "page_duration", "preferred page duration, in microseconds",
        OFFSET(pref_duration), AV_OPT_TYPE_INT64, { .i64 = 1000000 }, 0, INT64_MAX, PARAM },
    { NULL },
}
Definition at line 82 of file oggenc.c.