FFmpeg: libavformat/oggparsevorbis.c File Reference
oggparsevorbis.c File Reference
#include <stdlib.h>
#include "libavutil/avstring.h"
#include "libavutil/base64.h"
#include "libavutil/bswap.h"
#include "libavutil/dict.h"
#include "libavcodec/bytestream.h"
#include "libavcodec/vorbis_parser.h"
#include "avformat.h"
#include "flac_picture.h"
#include "internal.h"
#include "oggdec.h"
#include "vorbiscomment.h"
#include "replaygain.h"
Data Structures
struct oggvorbis_private
Functions
static int ogm_chapter (AVFormatContext *as, uint8_t *key, uint8_t *val)
int ff_vorbis_stream_comment (AVFormatContext *as, AVStream *st, const uint8_t *buf, int size)
int ff_vorbis_comment (AVFormatContext *as, AVDictionary **m, const uint8_t *buf, int size, int parse_picture)
static int fixup_vorbis_headers (AVFormatContext *as, struct oggvorbis_private *priv, uint8_t **buf)
static void vorbis_cleanup (AVFormatContext *s, int idx)
static int vorbis_update_metadata (AVFormatContext *s, int idx)
static int vorbis_header (AVFormatContext *s, int idx)
static int vorbis_packet (AVFormatContext *s, int idx)
Variables
const struct ogg_codec ff_vorbis_codec
Function Documentation
ogm_chapter()
static int ogm_chapter (AVFormatContext * as, uint8_t * key, uint8_t * val) static
Definition at line 42 of file oggparsevorbis.c.
Referenced by ff_vorbis_comment().
ff_vorbis_stream_comment()
int ff_vorbis_stream_comment (AVFormatContext * as, AVStream * st, const uint8_t * buf, int size)
Definition at line 75 of file oggparsevorbis.c.
Referenced by celt_header(), daala_header(), flac_header(), ogm_header(), opus_header(), speex_header(), theora_header(), vorbis_update_metadata(), and vp8_header().
ff_vorbis_comment()
int ff_vorbis_comment (AVFormatContext * as, AVDictionary ** m, const uint8_t * buf, int size, int parse_picture)
Definition at line 87 of file oggparsevorbis.c.
Referenced by ff_vorbis_stream_comment(), flac_read_header(), and matroska_parse_flac().
fixup_vorbis_headers()
static int fixup_vorbis_headers (AVFormatContext * as, struct oggvorbis_private * priv, uint8_t ** buf) static
Definition at line 223 of file oggparsevorbis.c.
Referenced by vorbis_header().
vorbis_cleanup()
static void vorbis_cleanup (AVFormatContext * s, int idx) static
Definition at line 252 of file oggparsevorbis.c.
vorbis_update_metadata()
static int vorbis_update_metadata (AVFormatContext * s, int idx) static
Definition at line 265 of file oggparsevorbis.c.
Referenced by vorbis_header(), and vorbis_packet().
vorbis_header()
static int vorbis_header (AVFormatContext * s, int idx) static
Definition at line 295 of file oggparsevorbis.c.
vorbis_packet()
static int vorbis_packet (AVFormatContext * s, int idx) static
Definition at line 404 of file oggparsevorbis.c.
Variable Documentation
ff_vorbis_codec
const struct ogg_codec ff_vorbis_codec
Initial value:
= {
    .magic     = "\001vorbis",
    .magicsize = 7,
    .header    = vorbis_header,
    .packet    = vorbis_packet,
    .cleanup   = vorbis_cleanup,
    .nb_header = 3,
}
Definition at line 496 of file oggparsevorbis.c.