FFmpeg: libavformat/omadec.c File Reference
omadec.c File Reference
This is a demuxer for Sony OpenMG Music files.
#include <inttypes.h>
#include "libavutil/channel_layout.h"
#include "avformat.h"
#include "internal.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/des.h"
#include "libavutil/mathematics.h"
#include "oma.h"
#include "pcm.h"
#include "id3v2.h"
Data Structures
struct OMAContext
Macros
#define OMA_RPROBE_M_VAL 48 + 1
Functions
static void hex_log (AVFormatContext *s, int level, const char *name, const uint8_t *value, int len)
static int kset (AVFormatContext *s, const uint8_t *r_val, const uint8_t *n_val, int len)
static int rprobe (AVFormatContext *s, uint8_t *enc_header, unsigned size, const uint8_t *r_val)
static int nprobe (AVFormatContext *s, uint8_t *enc_header, unsigned size, const uint8_t *n_val)
static int decrypt_init (AVFormatContext *s, ID3v2ExtraMeta *em, uint8_t *header)
static int oma_read_header (AVFormatContext *s)
static int oma_read_packet (AVFormatContext *s, AVPacket *pkt)
static int oma_read_probe (AVProbeData *p)
static int oma_read_seek (struct AVFormatContext *s, int stream_index, int64_t timestamp, int flags)
static int oma_read_close (AVFormatContext *s)
Variables
static const uint64_t leaf_table []
AVInputFormat ff_oma_demuxer
Detailed Description
This is a demuxer for Sony OpenMG Music files.
Known file extensions: ".oma", "aa3" The format of such files consists of three parts:
"ea3" header carrying overall info and metadata. Except for starting with "ea" instead of "ID", it's an ID3v2 header.
"EA3" header is a Sony-specific header containing information about the OpenMG file: codec type (usually ATRAC, can also be MP3 or WMA), codec specific info (packet size, sample rate, channels and so on) and DRM related info (file encryption, content id).
Sound data organized in packets follow the EA3 header (can be encrypted using the Sony DRM!).
Supported decoders: ATRAC3, ATRAC3+, MP3, LPCM
Definition in file omadec.c.
Macro Definition Documentation
OMA_RPROBE_M_VAL
#define OMA_RPROBE_M_VAL 48 + 1
Definition at line 121 of file omadec.c.
Referenced by rprobe().
Function Documentation
hex_log()
static void hex_log (AVFormatContext * s, int level, const char * name, const uint8_t * value, int len) static
Definition at line 80 of file omadec.c.
Referenced by decrypt_init().
kset()
static int kset (AVFormatContext * s, const uint8_t * r_val, const uint8_t * n_val, int len) static
Definition at line 92 of file omadec.c.
Referenced by decrypt_init(), and nprobe().
rprobe()
static int rprobe (AVFormatContext * s, uint8_t * enc_header, unsigned size, const uint8_t * r_val) static
Definition at line 123 of file omadec.c.
Referenced by decrypt_init(), and nprobe().
nprobe()
static int nprobe (AVFormatContext * s, uint8_t * enc_header, unsigned size, const uint8_t * n_val) static
Definition at line 159 of file omadec.c.
Referenced by decrypt_init().
decrypt_init()
static int decrypt_init (AVFormatContext * s, ID3v2ExtraMeta * em, uint8_t * header) static
Definition at line 208 of file omadec.c.
Referenced by oma_read_header().
oma_read_header()
static int oma_read_header (AVFormatContext * s) static
Definition at line 305 of file omadec.c.
oma_read_packet()
static int oma_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 431 of file omadec.c.
oma_read_probe()
static int oma_read_probe (AVProbeData * p) static
Definition at line 469 of file omadec.c.
oma_read_seek()
static int oma_read_seek (struct AVFormatContext * s, int stream_index, int64_t timestamp, int flags) static
Definition at line 490 of file omadec.c.
oma_read_close()
static int oma_read_close (AVFormatContext * s) static
Definition at line 516 of file omadec.c.
Variable Documentation
leaf_table
const uint64_t leaf_table[] static
Initial value:
= {
    0xd79e8283acea4620, 0x7a9762f445afd0d8,
    0x354d60a60b8c79f1, 0x584e1cde00b07aee,
    0x1573cd93da7df623, 0x47f98d79620dd535
}
Definition at line 56 of file omadec.c.
Referenced by decrypt_init().
ff_oma_demuxer
AVInputFormat ff_oma_demuxer
Initial value:
= {
    .name           = "oma",
    .long_name      = NULL_IF_CONFIG_SMALL("Sony OpenMG audio"),
    .priv_data_size = sizeof(OMAContext),
    .read_probe     = oma_read_probe,
    .read_header    = oma_read_header,
    .read_packet    = oma_read_packet,
    .read_seek      = oma_read_seek,
    .read_close     = oma_read_close,
    .flags          = AVFMT_GENERIC_INDEX,
    .extensions     = "oma,omg,aa3",
    .codec_tag      = (const AVCodecTag* const []){ff_oma_codec_tags, 0},
}
Definition at line 523 of file omadec.c.