FFmpeg: libavdevice/openal-dec.c File Reference
openal-dec.c File Reference
OpenAL 1.1 capture device for libavdevice.
#include <AL/al.h>
#include <AL/alc.h>
#include "libavutil/opt.h"
#include "libavutil/time.h"
#include "libavformat/internal.h"
#include "avdevice.h"
Data Structures
struct al_data
struct al_format_info
Macros
#define LOWEST_AL_FORMAT FFMIN(FFMIN(AL_FORMAT_MONO8,AL_FORMAT_MONO16),FFMIN(AL_FORMAT_STEREO8,AL_FORMAT_STEREO16))
#define OFFSET(x) offsetof(al_data, x)
Functions
static const al_format_info * get_al_format_info (ALCenum al_fmt)
Get information about an AL_FORMAT value.
static int al_get_error (ALCdevice *device, const char **error_msg_ret)
Get the OpenAL error code, translated into an av/errno error code.
static void print_al_capture_devices (void *log_ctx)
Print out a list of OpenAL capture devices on this system.
static int read_header (AVFormatContext *ctx)
static int read_packet (AVFormatContext *ctx, AVPacket *pkt)
static int read_close (AVFormatContext *ctx)
Variables
static const AVOption options []
class {
class_name = "openal"
item_name = av_default_item_name
option = options
version = LIBAVUTIL_VERSION_INT
category = AV_CLASS_CATEGORY_DEVICE_AUDIO_INPUT
};
AVInputFormat ff_openal_demuxer
Detailed Description
OpenAL 1.1 capture device for libavdevice.
Definition in file openal-dec.c.
Macro Definition Documentation
LOWEST_AL_FORMAT
#define LOWEST_AL_FORMAT FFMIN(FFMIN(AL_FORMAT_MONO8,AL_FORMAT_MONO16),FFMIN(AL_FORMAT_STEREO8,AL_FORMAT_STEREO16))
Definition at line 56 of file openal-dec.c.
Referenced by get_al_format_info().
OFFSET
#define OFFSET (x) offsetof(al_data, x)
Definition at line 231 of file openal-dec.c.
Function Documentation
get_al_format_info()
static const al_format_info* get_al_format_info (ALCenum al_fmt) inline static
Get information about an AL_FORMAT value.
Parameters
al_fmt the AL_FORMAT value to find information about.
Returns
A pointer to a structure containing information about the AL_FORMAT value.
Definition at line 63 of file openal-dec.c.
Referenced by read_header().
al_get_error()
static int al_get_error (ALCdevice * device, const char ** error_msg_ret) inline static
Get the OpenAL error code, translated into an av/errno error code.
Parameters
device The ALC device to check for errors.
error_msg_ret A pointer to a char* in which to return the error message, or NULL if desired.
Returns
The error code, or 0 if there is no error.
Definition at line 81 of file openal-dec.c.
Referenced by read_header(), and read_packet().
print_al_capture_devices()
static void print_al_capture_devices (void * log_ctx) inline static
Print out a list of OpenAL capture devices on this system.
Definition at line 108 of file openal-dec.c.
Referenced by read_header().
read_header()
static int read_header (AVFormatContext * ctx) static
Definition at line 121 of file openal-dec.c.
read_packet()
static int read_packet (AVFormatContext * ctx, AVPacket * pkt) static
Definition at line 183 of file openal-dec.c.
read_close()
static int read_close (AVFormatContext * ctx) static
Definition at line 220 of file openal-dec.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    {"channels", "set number of channels",     OFFSET(channels),     AV_OPT_TYPE_INT, {.i64=2},     1, 2,      AV_OPT_FLAG_DECODING_PARAM },
    {"sample_rate", "set sample rate",         OFFSET(sample_rate),  AV_OPT_TYPE_INT, {.i64=44100}, 1, 192000, AV_OPT_FLAG_DECODING_PARAM },
    {"sample_size", "set sample size",         OFFSET(sample_size),  AV_OPT_TYPE_INT, {.i64=16},    8, 16,     AV_OPT_FLAG_DECODING_PARAM },
    {"list_devices", "list available devices", OFFSET(list_devices), AV_OPT_TYPE_INT, {.i64=0},     0, 1,      AV_OPT_FLAG_DECODING_PARAM, "list_devices"  },
    {"true",  "", 0, AV_OPT_TYPE_CONST, {.i64=1}, 0, 0, AV_OPT_FLAG_DECODING_PARAM, "list_devices" },
    {"false", "", 0, AV_OPT_TYPE_CONST, {.i64=0}, 0, 0, AV_OPT_FLAG_DECODING_PARAM, "list_devices" },
    {NULL},
}
Definition at line 233 of file openal-dec.c.
class_name
class_name = "openal" private
Definition at line 244 of file openal-dec.c.
item_name
item_name = av_default_item_name private
Definition at line 245 of file openal-dec.c.
option
option = options private
Definition at line 246 of file openal-dec.c.
version
version = LIBAVUTIL_VERSION_INT private
Definition at line 247 of file openal-dec.c.
category
category = AV_CLASS_CATEGORY_DEVICE_AUDIO_INPUT private
Definition at line 248 of file openal-dec.c.
Referenced by device_next(), dshow_cycle_pins(), mono_decode(), and unpack_SQVH().
@158
const { ... }
ff_openal_demuxer
AVInputFormat ff_openal_demuxer
Initial value:
= {
    .name = "openal",
    .long_name = NULL_IF_CONFIG_SMALL("OpenAL audio capture device"),
    .priv_data_size = sizeof(al_data),
    .read_probe = NULL,
    .read_header = read_header,
    .read_packet = read_packet,
    .read_close = read_close,
    .flags = AVFMT_NOFILE,
    .priv_class = &class
}
Definition at line 251 of file openal-dec.c.