FFmpeg: libavutil/opt.c File Reference
opt.c File Reference
AVOptions.
#include "avutil.h"
#include "avassert.h"
#include "avstring.h"
#include "channel_layout.h"
#include "common.h"
#include "dict.h"
#include "eval.h"
#include "log.h"
#include "parseutils.h"
#include "pixdesc.h"
#include "mathematics.h"
#include "opt.h"
#include "samplefmt.h"
#include "bprint.h"
#include <float.h>
Macros
#define DEFAULT_NUMVAL(opt)
#define OPT_EVAL_NUMBER(name, opttype, vartype)
#define WHITESPACES " \n\t\r"
Functions
const AVOption * av_opt_next (const void *obj, const AVOption *last)
Iterate over all AVOptions belonging to obj.
static int read_number (const AVOption *o, const void *dst, double *num, int *den, int64_t *intnum)
static int write_number (void *obj, const AVOption *o, void *dst, double num, int den, int64_t intnum)
static int hexchar2int (char c)
static int set_string_binary (void *obj, const AVOption *o, const char *val, uint8_t **dst)
static int set_string (void *obj, const AVOption *o, const char *val, uint8_t **dst)
static int set_string_number (void *obj, void *target_obj, const AVOption *o, const char *val, void *dst)
static int set_string_image_size (void *obj, const AVOption *o, const char *val, int *dst)
static int set_string_video_rate (void *obj, const AVOption *o, const char *val, AVRational *dst)
static int set_string_color (void *obj, const AVOption *o, const char *val, uint8_t *dst)
static const char * get_bool_name (int val)
static int set_string_bool (void *obj, const AVOption *o, const char *val, int *dst)
static int set_string_fmt (void *obj, const AVOption *o, const char *val, uint8_t *dst, int fmt_nb, int((*get_fmt)(const char *)), const char *desc)
static int set_string_pixel_fmt (void *obj, const AVOption *o, const char *val, uint8_t *dst)
static int set_string_sample_fmt (void *obj, const AVOption *o, const char *val, uint8_t *dst)
int av_opt_set (void *obj, const char *name, const char *val, int search_flags)
static int set_number (void *obj, const char *name, double num, int den, int64_t intnum, int search_flags)
int av_opt_set_int (void *obj, const char *name, int64_t val, int search_flags)
int av_opt_set_double (void *obj, const char *name, double val, int search_flags)
int av_opt_set_q (void *obj, const char *name, AVRational val, int search_flags)
int av_opt_set_bin (void *obj, const char *name, const uint8_t *val, int len, int search_flags)
int av_opt_set_image_size (void *obj, const char *name, int w, int h, int search_flags)
int av_opt_set_video_rate (void *obj, const char *name, AVRational val, int search_flags)
static int set_format (void *obj, const char *name, int fmt, int search_flags, enum AVOptionType type, const char *desc, int nb_fmts)
int av_opt_set_pixel_fmt (void *obj, const char *name, enum AVPixelFormat fmt, int search_flags)
int av_opt_set_sample_fmt (void *obj, const char *name, enum AVSampleFormat fmt, int search_flags)
int av_opt_set_channel_layout (void *obj, const char *name, int64_t cl, int search_flags)
int av_opt_set_dict_val (void *obj, const char *name, const AVDictionary *val, int search_flags)
static void format_duration (char *buf, size_t size, int64_t d)
int av_opt_get (void *obj, const char *name, int search_flags, uint8_t **out_val)
static int get_number (void *obj, const char *name, const AVOption **o_out, double *num, int *den, int64_t *intnum, int search_flags)
int av_opt_get_int (void *obj, const char *name, int search_flags, int64_t *out_val)
int av_opt_get_double (void *obj, const char *name, int search_flags, double *out_val)
int av_opt_get_q (void *obj, const char *name, int search_flags, AVRational *out_val)
int av_opt_get_image_size (void *obj, const char *name, int search_flags, int *w_out, int *h_out)
int av_opt_get_video_rate (void *obj, const char *name, int search_flags, AVRational *out_val)
static int get_format (void *obj, const char *name, int search_flags, int *out_fmt, enum AVOptionType type, const char *desc)
int av_opt_get_pixel_fmt (void *obj, const char *name, int search_flags, enum AVPixelFormat *out_fmt)
int av_opt_get_sample_fmt (void *obj, const char *name, int search_flags, enum AVSampleFormat *out_fmt)
int av_opt_get_channel_layout (void *obj, const char *name, int search_flags, int64_t *cl)
int av_opt_get_dict_val (void *obj, const char *name, int search_flags, AVDictionary **out_val)
int av_opt_flag_is_set (void *obj, const char *field_name, const char *flag_name)
Check whether a particular flag is set in a flags field.
static void log_value (void *av_log_obj, int level, double d)
static const char * get_opt_const_name (void *obj, const char *unit, int64_t value)
static char * get_opt_flags_string (void *obj, const char *unit, int64_t value)
static void opt_list (void *obj, void *av_log_obj, const char *unit, int req_flags, int rej_flags)
int av_opt_show2 (void *obj, void *av_log_obj, int req_flags, int rej_flags)
Show the obj options.
void av_opt_set_defaults (void *s)
Set the values of all AVOption fields to their default values.
void av_opt_set_defaults2 (void *s, int mask, int flags)
Set the values of all AVOption fields to their default values.
static int parse_key_value_pair (void *ctx, const char **buf, const char *key_val_sep, const char *pairs_sep)
Store the value in the field in ctx that is named like key.
int av_set_options_string (void *ctx, const char *opts, const char *key_val_sep, const char *pairs_sep)
Parse the key/value pairs list in opts.
static int is_key_char (char c)
static int get_key (const char **ropts, const char *delim, char **rkey)
Read a key from a string.
int av_opt_get_key_value (const char **ropts, const char *key_val_sep, const char *pairs_sep, unsigned flags, char **rkey, char **rval)
Extract a key-value pair from the beginning of a string.
int av_opt_set_from_string (void *ctx, const char *opts, const char *const *shorthand, const char *key_val_sep, const char *pairs_sep)
Parse the key-value pairs list in opts.
void av_opt_free (void *obj)
Free all allocated objects in obj.
int av_opt_set_dict2 (void *obj, AVDictionary **options, int search_flags)
Set all the options from a given dictionary on an object.
int av_opt_set_dict (void *obj, AVDictionary **options)
Set all the options from a given dictionary on an object.
const AVOption * av_opt_find (void *obj, const char *name, const char *unit, int opt_flags, int search_flags)
Look for an option in an object.
const AVOption * av_opt_find2 (void *obj, const char *name, const char *unit, int opt_flags, int search_flags, void **target_obj)
Look for an option in an object.
void * av_opt_child_next (void *obj, void *prev)
Iterate over AVOptions-enabled children of obj.
const AVClass * av_opt_child_class_next (const AVClass *parent, const AVClass *prev)
Iterate over potential AVOptions-enabled children of parent.
void * av_opt_ptr (const AVClass *class, void *obj, const char *name)
Gets a pointer to the requested field in a struct.
static int opt_size (enum AVOptionType type)
int av_opt_copy (void *dst, const void *src)
Copy options from src object into dest object.
int av_opt_query_ranges (AVOptionRanges **ranges_arg, void *obj, const char *key, int flags)
Get a list of allowed ranges for the given option.
int av_opt_query_ranges_default (AVOptionRanges **ranges_arg, void *obj, const char *key, int flags)
Get a default list of allowed ranges for the given option.
void av_opt_freep_ranges (AVOptionRanges **rangesp)
Free an AVOptionRanges struct and set it to NULL.
int av_opt_is_set_to_default (void *obj, const AVOption *o)
Check if given option is set to its default value.
int av_opt_is_set_to_default_by_name (void *obj, const char *name, int search_flags)
Check if given option is set to its default value.
int av_opt_serialize (void *obj, int opt_flags, int flags, char **buffer, const char key_val_sep, const char pairs_sep)
Serialize object's options.
Detailed Description
AVOptions.
Author
Michael Niedermayer micha.nosp@m.elni.nosp@m.@gmx..nosp@m.at
Definition in file opt.c.
Macro Definition Documentation
DEFAULT_NUMVAL
#define DEFAULT_NUMVAL (opt)
Value:
((opt->type == AV_OPT_TYPE_INT64 || \
                              opt->type == AV_OPT_TYPE_UINT64 || \
                              opt->type == AV_OPT_TYPE_CONST || \
                              opt->type == AV_OPT_TYPE_FLAGS || \
                              opt->type == AV_OPT_TYPE_INT)     \
                             ? opt->default_val.i64             \
                             : opt->default_val.dbl)
Definition at line 221 of file opt.c.
Referenced by set_string_number().
OPT_EVAL_NUMBER
#define OPT_EVAL_NUMBER (name, opttype, vartype)
Value:
int av_opt_eval_ ## name(void *obj, const AVOption *o,                  \
                         const char *val, vartype *name ## _out)        \
{                                                                       \
    if (!o || o->type != opttype || o->flags & AV_OPT_FLAG_READONLY)    \
        return AVERROR(EINVAL);                                         \
    return set_string_number(obj, obj, o, val, name ## _out);           \
}
Definition at line 528 of file opt.c.
WHITESPACES
#define WHITESPACES " \n\t\r"
Definition at line 1434 of file opt.c.
Referenced by get_key().
Function Documentation
read_number()
static int read_number (const AVOption * o, const void * dst, double * num, int * den, int64_t * intnum) static
Definition at line 58 of file opt.c.
Referenced by av_opt_is_set_to_default(), get_number(), and set_string_number().
write_number()
static int write_number (void * obj, const AVOption * o, void * dst, double num, int den, int64_t intnum) static
Definition at line 97 of file opt.c.
Referenced by av_opt_set(), av_opt_set_defaults2(), set_number(), and set_string_number().
hexchar2int()
static int hexchar2int (char c) static
Definition at line 170 of file opt.c.
Referenced by set_string_binary().
set_string_binary()
static int set_string_binary (void * obj, const AVOption * o, const char * val, uint8_t ** dst) static
Definition at line 180 of file opt.c.
Referenced by av_opt_is_set_to_default(), av_opt_set(), and av_opt_set_defaults2().
set_string()
static int set_string (void * obj, const AVOption * o, const char * val, uint8_t ** dst) static
Definition at line 214 of file opt.c.
Referenced by av_opt_set(), and av_opt_set_defaults2().
set_string_number()
static int set_string_number (void * obj, void * target_obj, const AVOption * o, const char * val, void * dst) static
Definition at line 229 of file opt.c.
Referenced by av_opt_set().
set_string_image_size()
static int set_string_image_size (void * obj, const AVOption * o, const char * val, int * dst) static
Definition at line 318 of file opt.c.
Referenced by av_opt_set(), and av_opt_set_defaults2().
set_string_video_rate()
static int set_string_video_rate (void * obj, const AVOption * o, const char * val, AVRational * dst) static
Definition at line 333 of file opt.c.
Referenced by av_opt_set(), and av_opt_set_defaults2().
set_string_color()
static int set_string_color (void * obj, const AVOption * o, const char * val, uint8_t * dst) static
Definition at line 346 of file opt.c.
Referenced by av_opt_set(), and av_opt_set_defaults2().
get_bool_name()
static const char* get_bool_name (int val) static
Definition at line 361 of file opt.c.
Referenced by av_opt_get(), and opt_list().
set_string_bool()
static int set_string_bool (void * obj, const AVOption * o, const char * val, int * dst) static
Definition at line 368 of file opt.c.
Referenced by av_opt_set().
set_string_fmt()
static int set_string_fmt (void * obj, const AVOption * o, const char * val, uint8_t * dst, int fmt_nb, int((*get_fmt)(const char *)) , const char * desc) static
Definition at line 399 of file opt.c.
Referenced by set_string_pixel_fmt(), and set_string_sample_fmt().
set_string_pixel_fmt()
static int set_string_pixel_fmt (void * obj, const AVOption * o, const char * val, uint8_t * dst) static
Definition at line 439 of file opt.c.
Referenced by av_opt_set().
set_string_sample_fmt()
static int set_string_sample_fmt (void * obj, const AVOption * o, const char * val, uint8_t * dst) static
Definition at line 445 of file opt.c.
Referenced by av_opt_set().
set_number()
static int set_number (void * obj, const char * name, double num, int den, int64_t intnum, int search_flags) static
Definition at line 544 of file opt.c.
Referenced by av_opt_set_double(), av_opt_set_int(), av_opt_set_q(), and av_opt_set_video_rate().
set_format()
static int set_format (void * obj, const char * name, int fmt, int search_flags, enum AVOptionType type, const char * desc, int nb_fmts) static
Definition at line 644 of file opt.c.
Referenced by av_opt_set_pixel_fmt(), av_opt_set_sample_fmt(), and dshow_cycle_pins().
format_duration()
static void format_duration (char * buf, size_t size, int64_t d) static
Definition at line 718 of file opt.c.
Referenced by av_opt_get(), and opt_list().
get_number()
static int get_number (void * obj, const char * name, const AVOption ** o_out, double * num, int * den, int64_t * intnum, int search_flags) static
Definition at line 857 of file opt.c.
Referenced by av_opt_get_double(), av_opt_get_int(), av_opt_get_q(), and av_opt_get_video_rate().
get_format()
static int get_format (void * obj, const char * name, int search_flags, int * out_fmt, enum AVOptionType type, const char * desc) static
Definition at line 951 of file opt.c.
Referenced by av_opt_get_pixel_fmt(), and av_opt_get_sample_fmt().
log_value()
static void log_value (void * av_log_obj, int level, double d) static
Definition at line 1026 of file opt.c.
Referenced by opt_list().
get_opt_const_name()
static const char* get_opt_const_name (void * obj, const char * unit, int64_t value) static
Definition at line 1059 of file opt.c.
Referenced by opt_list().
get_opt_flags_string()
static char* get_opt_flags_string (void * obj, const char * unit, int64_t value) static
Definition at line 1072 of file opt.c.
Referenced by opt_list().
opt_list()
static void opt_list (void * obj, void * av_log_obj, const char * unit, int req_flags, int rej_flags) static
Definition at line 1093 of file opt.c.
Referenced by av_opt_show2().
parse_key_value_pair()
static int parse_key_value_pair (void * ctx, const char ** buf, const char * key_val_sep, const char * pairs_sep) static
Store the value in the field in ctx that is named like key.
ctx must be an AVClass context, storing is done using AVOptions.
Parameters
buf the string to parse, buf will be updated to point at the separator just after the parsed key/value pair
key_val_sep a 0-terminated list of characters used to separate key from value
pairs_sep a 0-terminated list of characters used to separate two pairs from each other
Returns
0 if the key/value pair has been successfully parsed and set, or a negative value corresponding to an AVERROR code in case of error: AVERROR(EINVAL) if the key/value pair cannot be parsed, the error code issued by av_opt_set() if the key/value pair cannot be set
Definition at line 1380 of file opt.c.
Referenced by av_set_options_string().
is_key_char()
static int is_key_char (char c) static
Definition at line 1436 of file opt.c.
Referenced by get_key().
get_key()
static int get_key (const char ** ropts, const char * delim, char ** rkey) static
Read a key from a string.
The key consists of is_key_char characters and must be terminated by a character from the delim string; spaces are ignored.
Returns
0 for success (even with ellipsis), <0 for failure
Definition at line 1451 of file opt.c.
Referenced by av_opt_get_key_value().
opt_size()
static int opt_size (enum AVOptionType type) static
Definition at line 1669 of file opt.c.
Referenced by av_opt_copy(), and av_opt_is_set_to_default().