FFmpeg: libavcodec/opus_rc.h File Reference
opus_rc.h File Reference
#include <stdint.h>
#include "get_bits.h"
Data Structures
struct RawBitsContext
struct OpusRangeCoder
Macros
#define opus_ilog(i) (av_log2(i) + !!(i))
Functions
static av_always_inline uint32_t opus_rc_tell (const OpusRangeCoder *rc)
CELT: estimate bits of entropy that have thus far been consumed for the current CELT frame, to integer and fractional (1/8th bit) precision.
static av_always_inline uint32_t opus_rc_tell_frac (const OpusRangeCoder *rc)
uint32_t ff_opus_rc_dec_cdf (OpusRangeCoder *rc, const uint16_t *cdf)
uint32_t ff_opus_rc_dec_log (OpusRangeCoder *rc, uint32_t bits)
uint32_t ff_opus_rc_dec_uint (OpusRangeCoder *rc, uint32_t size)
CELT: read a uniform distribution.
uint32_t ff_opus_rc_dec_uint_step (OpusRangeCoder *rc, int k0)
uint32_t ff_opus_rc_dec_uint_tri (OpusRangeCoder *rc, int qn)
uint32_t ff_opus_rc_get_raw (OpusRangeCoder *rc, uint32_t count)
CELT: read 1-25 raw bits at the end of the frame, backwards byte-wise.
int ff_opus_rc_dec_laplace (OpusRangeCoder *rc, uint32_t symbol, int decay)
int ff_opus_rc_dec_init (OpusRangeCoder *rc, const uint8_t *data, int size)
void ff_opus_rc_dec_raw_init (OpusRangeCoder *rc, const uint8_t *rightend, uint32_t bytes)
Macro Definition Documentation
opus_ilog
#define opus_ilog (i) (av_log2(i) + !!(i))
Definition at line 29 of file opus_rc.h.
Referenced by celt_log2tan(), ff_opus_rc_dec_uint(), silk_decode_lpc(), and silk_is_lpc_stable().
Function Documentation
opus_rc_tell()
static av_always_inline uint32_t opus_rc_tell (const OpusRangeCoder * rc) static
CELT: estimate bits of entropy that have thus far been consumed for the current CELT frame, to integer and fractional (1/8th bit) precision.
Definition at line 50 of file opus_rc.h.
Referenced by celt_decode_allocation(), celt_decode_coarse_energy(), celt_decode_tf_changes(), ff_celt_decode_frame(), opus_decode_frame(), and parse_postfilter().
opus_rc_tell_frac()
static av_always_inline uint32_t opus_rc_tell_frac (const OpusRangeCoder * rc) static
Definition at line 55 of file opus_rc.h.
Referenced by celt_decode_allocation(), celt_decode_band(), and celt_decode_bands().
ff_opus_rc_dec_cdf()
uint32_t ff_opus_rc_dec_cdf (OpusRangeCoder * rc, const uint16_t * cdf)
Definition at line 44 of file opus_rc.c.
Referenced by celt_decode_allocation(), celt_decode_coarse_energy(), opus_rc_tell_frac(), parse_postfilter(), silk_count_children(), silk_decode_excitation(), silk_decode_frame(), and silk_decode_lpc().
ff_opus_rc_dec_log()
uint32_t ff_opus_rc_dec_log (OpusRangeCoder * rc, uint32_t bits)
Definition at line 63 of file opus_rc.c.
Referenced by celt_decode_allocation(), celt_decode_band(), celt_decode_coarse_energy(), celt_decode_tf_changes(), ff_celt_decode_frame(), ff_silk_decode_superframe(), opus_decode_frame(), opus_rc_tell_frac(), and parse_postfilter().
ff_opus_rc_dec_uint()
uint32_t ff_opus_rc_dec_uint (OpusRangeCoder * rc, uint32_t size)
CELT: read a uniform distribution.
Definition at line 104 of file opus_rc.c.
Referenced by celt_decode_allocation(), celt_decode_band(), celt_decode_pulses(), opus_decode_frame(), opus_rc_tell_frac(), and parse_postfilter().
ff_opus_rc_dec_uint_step()
uint32_t ff_opus_rc_dec_uint_step (OpusRangeCoder * rc, int k0)
Definition at line 123 of file opus_rc.c.
Referenced by celt_decode_band(), and opus_rc_tell_frac().
ff_opus_rc_dec_uint_tri()
uint32_t ff_opus_rc_dec_uint_tri (OpusRangeCoder * rc, int qn)
Definition at line 138 of file opus_rc.c.
Referenced by celt_decode_band(), and opus_rc_tell_frac().
ff_opus_rc_get_raw()
uint32_t ff_opus_rc_get_raw (OpusRangeCoder * rc, uint32_t count)
CELT: read 1-25 raw bits at the end of the frame, backwards byte-wise.
Definition at line 83 of file opus_rc.c.
Referenced by celt_decode_band(), celt_decode_final_energy(), celt_decode_fine_energy(), ff_celt_decode_frame(), ff_opus_rc_dec_uint(), opus_rc_tell_frac(), and parse_postfilter().
ff_opus_rc_dec_laplace()
int ff_opus_rc_dec_laplace (OpusRangeCoder * rc, uint32_t symbol, int decay)
Definition at line 162 of file opus_rc.c.
Referenced by celt_decode_coarse_energy(), and opus_rc_tell_frac().
ff_opus_rc_dec_init()
int ff_opus_rc_dec_init (OpusRangeCoder * rc, const uint8_t * data, int size)
Definition at line 201 of file opus_rc.c.
Referenced by opus_decode_frame(), opus_decode_redundancy(), and opus_rc_tell_frac().
ff_opus_rc_dec_raw_init()
void ff_opus_rc_dec_raw_init (OpusRangeCoder * rc, const uint8_t * rightend, uint32_t bytes)
Definition at line 215 of file opus_rc.c.
Referenced by opus_decode_frame(), opus_decode_redundancy(), and opus_rc_tell_frac().