FFmpeg: libavcodec/opusdec.c File Reference
opusdec.c File Reference
Opus decoder.
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/audio_fifo.h"
#include "libavutil/channel_layout.h"
#include "libavutil/opt.h"
#include "libswresample/swresample.h"
#include "avcodec.h"
#include "get_bits.h"
#include "internal.h"
#include "mathops.h"
#include "opus.h"
#include "opustab.h"
Functions
static int get_silk_samplerate (int config)
static void opus_fade (float *out, const float *in1, const float *in2, const float *window, int len)
static int opus_flush_resample (OpusStreamContext *s, int nb_samples)
static int opus_init_resample (OpusStreamContext *s)
static int opus_decode_redundancy (OpusStreamContext *s, const uint8_t *data, int size)
static int opus_decode_frame (OpusStreamContext *s, const uint8_t *data, int size)
static int opus_decode_subpacket (OpusStreamContext *s, const uint8_t *buf, int buf_size, float **out, int out_size, int nb_samples)
static int opus_decode_packet (AVCodecContext *avctx, void *data, int *got_frame_ptr, AVPacket *avpkt)
static av_cold void opus_decode_flush (AVCodecContext *ctx)
static av_cold int opus_decode_close (AVCodecContext *avctx)
static av_cold int opus_decode_init (AVCodecContext *avctx)
Variables
static const uint16_t silk_frame_duration_ms [16]
static const int silk_resample_delay []
static const uint8_t celt_band_end [] = { 13, 17, 17, 19, 21 }
AVCodec ff_opus_decoder
Detailed Description
Opus decoder.
Author
Andrew D'Addesio, Anton Khirnov
Codec homepage: http://opus-codec.org/ Specification: http://tools.ietf.org/html/rfc6716 Ogg Opus specification: https://tools.ietf.org/html/draft-ietf-codec-oggopus-03
Ogg-contained .opus files can be produced with opus-tools: http://git.xiph.org/?p=opus-tools.git
Definition in file opusdec.c.
Function Documentation
get_silk_samplerate()
static int get_silk_samplerate (int config) static
Definition at line 68 of file opusdec.c.
Referenced by opus_decode_packet().
opus_fade()
static void opus_fade (float * out, const float * in1, const float * in2, const float * window, int len) static
Definition at line 77 of file opusdec.c.
Referenced by opus_decode_frame(), and opus_flush_resample().
opus_flush_resample()
static int opus_flush_resample (OpusStreamContext * s, int nb_samples) static
Definition at line 86 of file opusdec.c.
Referenced by opus_decode_subpacket().
opus_init_resample()
static int opus_init_resample (OpusStreamContext * s) static
Definition at line 129 of file opusdec.c.
Referenced by opus_decode_frame().
opus_decode_redundancy()
static int opus_decode_redundancy (OpusStreamContext * s, const uint8_t * data, int size) static
Definition at line 154 of file opusdec.c.
Referenced by opus_decode_frame().
opus_decode_frame()
static int opus_decode_frame (OpusStreamContext * s, const uint8_t * data, int size) static
Definition at line 181 of file opusdec.c.
Referenced by opus_decode_subpacket().
opus_decode_subpacket()
static int opus_decode_subpacket (OpusStreamContext * s, const uint8_t * buf, int buf_size, float ** out, int out_size, int nb_samples) static
Definition at line 340 of file opusdec.c.
Referenced by opus_decode_packet().
opus_decode_packet()
static int opus_decode_packet (AVCodecContext * avctx, void * data, int * got_frame_ptr, AVPacket * avpkt) static
Definition at line 422 of file opusdec.c.
opus_decode_flush()
static av_cold void opus_decode_flush (AVCodecContext * ctx) static
Definition at line 576 of file opusdec.c.
opus_decode_close()
static av_cold int opus_decode_close (AVCodecContext * avctx) static
Definition at line 598 of file opusdec.c.
Referenced by opus_decode_init().
opus_decode_init()
static av_cold int opus_decode_init (AVCodecContext * avctx) static
Definition at line 635 of file opusdec.c.
Variable Documentation
silk_frame_duration_ms
const uint16_t silk_frame_duration_ms[16] static
Initial value:
= {
    10, 20, 40, 60,
    10, 20, 40, 60,
    10, 20, 40, 60,
    10, 20,
    10, 20,
}
Definition at line 52 of file opusdec.c.
Referenced by opus_decode_frame().
silk_resample_delay
const int silk_resample_delay[] static
Initial value:
= {
    4, 8, 11, 11, 11
}
Definition at line 62 of file opusdec.c.
Referenced by opus_init_resample().
celt_band_end
const uint8_t celt_band_end[] = { 13, 17, 17, 19, 21 } static
Definition at line 66 of file opusdec.c.
Referenced by opus_decode_frame(), and opus_decode_redundancy().
ff_opus_decoder
AVCodec ff_opus_decoder
Initial value:
= {
    .name            = "opus",
    .long_name       = NULL_IF_CONFIG_SMALL("Opus"),
    .type            = AVMEDIA_TYPE_AUDIO,
    .id              = AV_CODEC_ID_OPUS,
    .priv_data_size  = sizeof(OpusContext),
    .init            = opus_decode_init,
    .close           = opus_decode_close,
    .decode          = opus_decode_packet,
    .flush           = opus_decode_flush,
    .capabilities    = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_DELAY,
}
Definition at line 723 of file opusdec.c.