FFmpeg: libavcodec/opus_silk.c File Reference
opus_silk.c File Reference
Opus SILK decoder.
#include <stdint.h>
#include "opus.h"
#include "opustab.h"
Data Structures
struct SilkFrame
struct SilkContext
Macros
#define SILK_MAX_LAG (288 + LTP_ORDER / 2)
Maximum residual history according to 4.2.7.6.1.
#define LTP_ORDER 5
Order of the LTP filter.
Functions
static void silk_stabilize_lsf (int16_t nlsf[16], int order, const uint16_t min_delta[17])
static int silk_is_lpc_stable (const int16_t lpc[16], int order)
static void silk_lsp2poly (const int32_t lsp[16], int32_t pol[16], int half_order)
static void silk_lsf2lpc (const int16_t nlsf[16], float lpcf[16], int order)
static void silk_decode_lpc (SilkContext *s, SilkFrame *frame, OpusRangeCoder *rc, float lpc_leadin[16], float lpc[16], int *lpc_order, int *has_lpc_leadin, int voiced)
static void silk_count_children (OpusRangeCoder *rc, int model, int32_t total, int32_t child[2])
static void silk_decode_excitation (SilkContext *s, OpusRangeCoder *rc, float *excitationf, int qoffset_high, int active, int voiced)
static void silk_decode_frame (SilkContext *s, OpusRangeCoder *rc, int frame_num, int channel, int coded_channels, int active, int active1)
static void silk_unmix_ms (SilkContext *s, float *l, float *r)
static void silk_flush_frame (SilkFrame *frame)
int ff_silk_decode_superframe (SilkContext *s, OpusRangeCoder *rc, float *output[2], enum OpusBandwidth bandwidth, int coded_channels, int duration_ms)
Decode the LP layer of one Opus frame (which may correspond to several SILK frames).
void ff_silk_free (SilkContext **ps)
void ff_silk_flush (SilkContext *s)
int ff_silk_init (AVCodecContext *avctx, SilkContext **ps, int output_channels)
Detailed Description
Opus SILK decoder.
Definition in file opus_silk.c.
Macro Definition Documentation
SILK_MAX_LAG
#define SILK_MAX_LAG (288 + LTP_ORDER / 2)
Maximum residual history according to 4.2.7.6.1.
Definition at line 495 of file opus_silk.c.
Referenced by silk_decode_frame().
LTP_ORDER
#define LTP_ORDER 5
Order of the LTP filter.
Definition at line 498 of file opus_silk.c.
Referenced by silk_decode_frame().
Function Documentation
silk_stabilize_lsf()
static void silk_stabilize_lsf (int16_t nlsf[16], int order, const uint16_t min_delta[17]) inline static
Definition at line 65 of file opus_silk.c.
Referenced by silk_decode_lpc().
silk_is_lpc_stable()
static int silk_is_lpc_stable (const int16_t lpc[16], int order) inline static
Definition at line 144 of file opus_silk.c.
Referenced by silk_lsf2lpc().
silk_lsp2poly()
static void silk_lsp2poly (const int32_t lsp[16], int32_t pol[16], int half_order) static
Definition at line 195 of file opus_silk.c.
Referenced by silk_lsf2lpc().
silk_lsf2lpc()
static void silk_lsf2lpc (const int16_t nlsf[16], float lpcf[16], int order) static
Definition at line 211 of file opus_silk.c.
Referenced by silk_decode_lpc().
silk_decode_lpc()
static void silk_decode_lpc (SilkContext * s, SilkFrame * frame, OpusRangeCoder * rc, float lpc_leadin[16], float lpc[16], int * lpc_order, int * has_lpc_leadin, int voiced) inline static
Definition at line 296 of file opus_silk.c.
Referenced by silk_decode_frame().
silk_count_children()
static void silk_count_children (OpusRangeCoder * rc, int model, int32_t total, int32_t child[2]) inline static
Definition at line 393 of file opus_silk.c.
Referenced by silk_decode_excitation().
silk_decode_excitation()
static void silk_decode_excitation (SilkContext * s, OpusRangeCoder * rc, float * excitationf, int qoffset_high, int active, int voiced) inline static
Definition at line 406 of file opus_silk.c.
Referenced by silk_decode_frame().
silk_decode_frame()
static void silk_decode_frame (SilkContext * s, OpusRangeCoder * rc, int frame_num, int channel, int coded_channels, int active, int active1) static
Definition at line 500 of file opus_silk.c.
Referenced by ff_silk_decode_superframe().
silk_unmix_ms()
static void silk_unmix_ms (SilkContext * s, float * l, float * r) static
Definition at line 727 of file opus_silk.c.
Referenced by ff_silk_decode_superframe().
silk_flush_frame()
static void silk_flush_frame (SilkFrame * frame) static
Definition at line 757 of file opus_silk.c.
Referenced by ff_silk_decode_superframe(), and ff_silk_flush().
ff_silk_decode_superframe()
int ff_silk_decode_superframe (SilkContext * s, OpusRangeCoder * rc, float * output[2], enum OpusBandwidth bandwidth, int coded_channels, int duration_ms)
Decode the LP layer of one Opus frame (which may correspond to several SILK frames).
Definition at line 775 of file opus_silk.c.
Referenced by opus_decode_frame().
ff_silk_free()
void ff_silk_free (SilkContext ** ps)
Definition at line 839 of file opus_silk.c.
Referenced by opus_decode_close().
ff_silk_flush()
void ff_silk_flush (SilkContext * s)
Definition at line 844 of file opus_silk.c.
Referenced by ff_silk_init(), opus_decode_flush(), and opus_decode_frame().
ff_silk_init()
int ff_silk_init (AVCodecContext * avctx, SilkContext ** ps, int output_channels)
Definition at line 852 of file opus_silk.c.
Referenced by opus_decode_init().