FFmpeg: libavcodec/opus.h File Reference
opus.h File Reference
#include <stdint.h>
#include "libavutil/audio_fifo.h"
#include "libavutil/float_dsp.h"
#include "libavutil/frame.h"
#include "libswresample/swresample.h"
#include "avcodec.h"
#include "opus_rc.h"
Data Structures
struct OpusPacket
struct OpusStreamContext
struct ChannelMap
struct OpusContext
Macros
#define MAX_FRAME_SIZE 1275
#define MAX_FRAMES 48
#define MAX_PACKET_DUR 5760
#define CELT_SHORT_BLOCKSIZE 120
#define CELT_OVERLAP CELT_SHORT_BLOCKSIZE
#define CELT_MAX_LOG_BLOCKS 3
#define CELT_MAX_FRAME_SIZE (CELT_SHORT_BLOCKSIZE * (1 << CELT_MAX_LOG_BLOCKS))
#define CELT_MAX_BANDS 21
#define CELT_VECTORS 11
#define CELT_ALLOC_STEPS 6
#define CELT_FINE_OFFSET 21
#define CELT_MAX_FINE_BITS 8
#define CELT_NORM_SCALE 16384
#define CELT_QTHETA_OFFSET 4
#define CELT_QTHETA_OFFSET_TWOPHASE 16
#define CELT_DEEMPH_COEFF 0.85000610f
#define CELT_POSTFILTER_MINPERIOD 15
#define CELT_ENERGY_SILENCE (-28.0f)
#define SILK_HISTORY 322
#define SILK_MAX_LPC 16
#define ROUND_MULL(a, b, s) (((MUL64(a, b) >> ((s) - 1)) + 1) >> 1)
#define ROUND_MUL16(a, b) ((MUL16(a, b) + 16384) >> 15)
#define OPUS_TS_HEADER 0x7FE0
#define OPUS_TS_MASK 0xFFE0
Enumerations
enum OpusMode { OPUS_MODE_SILK, OPUS_MODE_HYBRID, OPUS_MODE_CELT }
enum OpusBandwidth {
OPUS_BANDWIDTH_NARROWBAND, OPUS_BANDWIDTH_MEDIUMBAND, OPUS_BANDWIDTH_WIDEBAND, OPUS_BANDWIDTH_SUPERWIDEBAND,
OPUS_BANDWIDTH_FULLBAND
}
Functions
int ff_opus_parse_packet (OpusPacket *pkt, const uint8_t *buf, int buf_size, int self_delimited)
Parse Opus packet info from raw packet data.
int ff_opus_parse_extradata (AVCodecContext *avctx, OpusContext *s)
int ff_silk_init (AVCodecContext *avctx, SilkContext **ps, int output_channels)
void ff_silk_free (SilkContext **ps)
void ff_silk_flush (SilkContext *s)
int ff_silk_decode_superframe (SilkContext *s, OpusRangeCoder *rc, float *output[2], enum OpusBandwidth bandwidth, int coded_channels, int duration_ms)
Decode the LP layer of one Opus frame (which may correspond to several SILK frames).
int ff_celt_init (AVCodecContext *avctx, CeltContext **s, int output_channels)
void ff_celt_free (CeltContext **s)
void ff_celt_flush (CeltContext *s)
int ff_celt_decode_frame (CeltContext *s, OpusRangeCoder *rc, float **output, int coded_channels, int frame_size, int startband, int endband)
Variables
static const uint8_t opus_default_extradata [30]
Macro Definition Documentation
MAX_FRAME_SIZE
#define MAX_FRAME_SIZE 1275
Definition at line 37 of file opus.h.
MAX_FRAMES
#define MAX_FRAMES 48
Definition at line 38 of file opus.h.
MAX_PACKET_DUR
#define MAX_PACKET_DUR 5760
Definition at line 39 of file opus.h.
Referenced by ff_opus_parse_packet().
CELT_SHORT_BLOCKSIZE
#define CELT_SHORT_BLOCKSIZE 120
Definition at line 41 of file opus.h.
Referenced by ff_celt_decode_frame().
CELT_OVERLAP
#define CELT_OVERLAP CELT_SHORT_BLOCKSIZE
Definition at line 42 of file opus.h.
Referenced by celt_postfilter(), celt_postfilter_apply_transition(), and ff_celt_decode_frame().
CELT_MAX_LOG_BLOCKS
#define CELT_MAX_LOG_BLOCKS 3
Definition at line 43 of file opus.h.
Referenced by ff_celt_decode_frame().
CELT_MAX_FRAME_SIZE
#define CELT_MAX_FRAME_SIZE (CELT_SHORT_BLOCKSIZE * (1 << CELT_MAX_LOG_BLOCKS))
Definition at line 44 of file opus.h.
Referenced by ff_imdct15_init().
CELT_MAX_BANDS
#define CELT_MAX_BANDS 21
Definition at line 45 of file opus.h.
Referenced by celt_decode_allocation(), celt_decode_band(), celt_decode_coarse_energy(), ff_celt_decode_frame(), and ff_celt_flush().
CELT_VECTORS
#define CELT_VECTORS 11
Definition at line 46 of file opus.h.
Referenced by celt_decode_allocation().
CELT_ALLOC_STEPS
#define CELT_ALLOC_STEPS 6
Definition at line 47 of file opus.h.
Referenced by celt_decode_allocation().
CELT_FINE_OFFSET
#define CELT_FINE_OFFSET 21
Definition at line 48 of file opus.h.
Referenced by celt_decode_allocation().
CELT_MAX_FINE_BITS
#define CELT_MAX_FINE_BITS 8
Definition at line 49 of file opus.h.
Referenced by celt_decode_allocation(), and celt_decode_final_energy().
CELT_NORM_SCALE
#define CELT_NORM_SCALE 16384
Definition at line 50 of file opus.h.
CELT_QTHETA_OFFSET
#define CELT_QTHETA_OFFSET 4
Definition at line 51 of file opus.h.
Referenced by celt_decode_band().
CELT_QTHETA_OFFSET_TWOPHASE
#define CELT_QTHETA_OFFSET_TWOPHASE 16
Definition at line 52 of file opus.h.
Referenced by celt_decode_band().
CELT_DEEMPH_COEFF
#define CELT_DEEMPH_COEFF 0.85000610f
Definition at line 53 of file opus.h.
Referenced by ff_celt_decode_frame().
CELT_POSTFILTER_MINPERIOD
#define CELT_POSTFILTER_MINPERIOD 15
Definition at line 54 of file opus.h.
Referenced by parse_postfilter().
CELT_ENERGY_SILENCE
#define CELT_ENERGY_SILENCE (-28.0f)
Definition at line 55 of file opus.h.
Referenced by ff_celt_decode_frame(), and ff_celt_flush().
SILK_HISTORY
#define SILK_HISTORY 322
Definition at line 57 of file opus.h.
Referenced by ff_silk_decode_superframe(), silk_decode_frame(), and silk_unmix_ms().
SILK_MAX_LPC
#define SILK_MAX_LPC 16
Definition at line 58 of file opus.h.
ROUND_MULL
#define ROUND_MULL (a, b, s) (((MUL64(a, b) >> ((s) - 1)) + 1) >> 1)
Definition at line 60 of file opus.h.
Referenced by silk_is_lpc_stable(), silk_lsf2lpc(), and silk_lsp2poly().
ROUND_MUL16
#define ROUND_MUL16 (a, b) ((MUL16(a, b) + 16384) >> 15)
Definition at line 61 of file opus.h.
Referenced by celt_cos(), celt_decode_band(), and celt_log2tan().
OPUS_TS_HEADER
#define OPUS_TS_HEADER 0x7FE0
Definition at line 63 of file opus.h.
Referenced by opus_find_frame_end().
OPUS_TS_MASK
#define OPUS_TS_MASK 0xFFE0
Definition at line 64 of file opus.h.
Referenced by opus_find_frame_end().
Enumeration Type Documentation
OpusMode
enum OpusMode
Enumerator
OPUS_MODE_SILK
OPUS_MODE_HYBRID
OPUS_MODE_CELT
Definition at line 72 of file opus.h.
OpusBandwidth
enum OpusBandwidth
Enumerator
OPUS_BANDWIDTH_NARROWBAND
OPUS_BANDWIDTH_MEDIUMBAND
OPUS_BANDWIDTH_WIDEBAND
OPUS_BANDWIDTH_SUPERWIDEBAND
OPUS_BANDWIDTH_FULLBAND
Definition at line 78 of file opus.h.
Function Documentation
ff_opus_parse_packet()
int ff_opus_parse_packet (OpusPacket * pkt, const uint8_t * buf, int buf_size, int self_delimited)
Parse Opus packet info from raw packet data.
Definition at line 89 of file opus.c.
Referenced by opus_decode_packet(), and opus_find_frame_end().
ff_opus_parse_extradata()
int ff_opus_parse_extradata (AVCodecContext * avctx, OpusContext * s)
Definition at line 290 of file opus.c.
Referenced by opus_decode_init(), and opus_find_frame_end().
ff_silk_init()
int ff_silk_init (AVCodecContext * avctx, SilkContext ** ps, int output_channels)
Definition at line 852 of file opus_silk.c.
Referenced by opus_decode_init().
ff_silk_free()
void ff_silk_free (SilkContext ** ps)
Definition at line 839 of file opus_silk.c.
Referenced by opus_decode_close().
ff_silk_flush()
void ff_silk_flush (SilkContext * s)
Definition at line 844 of file opus_silk.c.
Referenced by ff_silk_init(), opus_decode_flush(), and opus_decode_frame().
ff_silk_decode_superframe()
int ff_silk_decode_superframe (SilkContext * s, OpusRangeCoder * rc, float * output[2], enum OpusBandwidth bandwidth, int coded_channels, int duration_ms)
Decode the LP layer of one Opus frame (which may correspond to several SILK frames).
Definition at line 775 of file opus_silk.c.
Referenced by opus_decode_frame().
ff_celt_init()
int ff_celt_init (AVCodecContext * avctx, CeltContext ** s, int output_channels)
Definition at line 1801 of file opus_celt.c.
Referenced by opus_decode_init().
ff_celt_free()
void ff_celt_free (CeltContext ** s)
Definition at line 1786 of file opus_celt.c.
Referenced by ff_celt_init(), and opus_decode_close().
ff_celt_flush()
void ff_celt_flush (CeltContext * s)
Definition at line 1759 of file opus_celt.c.
Referenced by ff_celt_init(), opus_decode_flush(), and opus_decode_frame().
ff_celt_decode_frame()
int ff_celt_decode_frame (CeltContext * s, OpusRangeCoder * rc, float ** output, int coded_channels, int frame_size, int startband, int endband)
Definition at line 1589 of file opus_celt.c.
Referenced by opus_decode_frame(), and opus_decode_redundancy().
Variable Documentation
opus_default_extradata
const uint8_t opus_default_extradata[30] static
Initial value:
= {
    'O', 'p', 'u', 's', 'H', 'e', 'a', 'd',
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
}
Definition at line 66 of file opus.h.
Referenced by ff_opus_parse_extradata(), and ff_parse_mpeg2_descriptor().