FFmpeg: libavcodec/opus_celt.c File Reference
opus_celt.c File Reference
Opus CELT decoder.
#include <stdint.h>
#include "libavutil/float_dsp.h"
#include "libavutil/libm.h"
#include "imdct15.h"
#include "opus.h"
#include "opustab.h"
Data Structures
struct CeltFrame
struct CeltContext
Macros
#define CELT_PVQ_U(n, k) (ff_celt_pvq_u_row[FFMIN(n, k)][FFMAX(n, k)])
#define CELT_PVQ_V(n, k) (CELT_PVQ_U(n, k) + CELT_PVQ_U(n, (k) + 1))
Enumerations
enum CeltSpread { CELT_SPREAD_NONE, CELT_SPREAD_LIGHT, CELT_SPREAD_NORMAL, CELT_SPREAD_AGGRESSIVE }
Functions
static int16_t celt_cos (int16_t x)
static int celt_log2tan (int isin, int icos)
static uint32_t celt_rng (CeltContext *s)
static void celt_decode_coarse_energy (CeltContext *s, OpusRangeCoder *rc)
static void celt_decode_fine_energy (CeltContext *s, OpusRangeCoder *rc)
static void celt_decode_final_energy (CeltContext *s, OpusRangeCoder *rc, int bits_left)
static void celt_decode_tf_changes (CeltContext *s, OpusRangeCoder *rc, int transient)
static void celt_decode_allocation (CeltContext *s, OpusRangeCoder *rc)
static int celt_bits2pulses (const uint8_t *cache, int bits)
static int celt_pulses2bits (const uint8_t *cache, int pulses)
static void celt_normalize_residual (const int *av_restrict iy, float *av_restrict X, int N, float g)
static void celt_exp_rotation1 (float *X, unsigned int len, unsigned int stride, float c, float s)
static void celt_exp_rotation (float *X, unsigned int len, unsigned int stride, unsigned int K, enum CeltSpread spread)
static unsigned int celt_extract_collapse_mask (const int *iy, unsigned int N, unsigned int B)
static void celt_renormalize_vector (float *X, int N, float gain)
static void celt_stereo_merge (float *X, float *Y, float mid, int N)
static void celt_interleave_hadamard (float *tmp, float *X, int N0, int stride, int hadamard)
static void celt_deinterleave_hadamard (float *tmp, float *X, int N0, int stride, int hadamard)
static void celt_haar1 (float *X, int N0, int stride)
static int celt_compute_qn (int N, int b, int offset, int pulse_cap, int dualstereo)
static uint64_t celt_cwrsi (unsigned int N, unsigned int K, unsigned int i, int *y)
static float celt_decode_pulses (OpusRangeCoder *rc, int *y, unsigned int N, unsigned int K)
static unsigned int celt_alg_unquant (OpusRangeCoder *rc, float *X, unsigned int N, unsigned int K, enum CeltSpread spread, unsigned int blocks, float gain)
Decode pulse vector and combine the result with the pitch vector to produce the final normalised signal in the current band.
static unsigned int celt_decode_band (CeltContext *s, OpusRangeCoder *rc, const int band, float *X, float *Y, int N, int b, unsigned int blocks, float *lowband, int duration, float *lowband_out, int level, float gain, float *lowband_scratch, int fill)
static void celt_denormalize (CeltContext *s, CeltFrame *frame, float *data)
static void celt_postfilter_apply_transition (CeltFrame *frame, float *data)
static void celt_postfilter_apply (CeltFrame *frame, float *data, int len)
static void celt_postfilter (CeltContext *s, CeltFrame *frame)
static int parse_postfilter (CeltContext *s, OpusRangeCoder *rc, int consumed)
static void process_anticollapse (CeltContext *s, CeltFrame *frame, float *X)
static void celt_decode_bands (CeltContext *s, OpusRangeCoder *rc)
int ff_celt_decode_frame (CeltContext *s, OpusRangeCoder *rc, float **output, int coded_channels, int frame_size, int startband, int endband)
void ff_celt_flush (CeltContext *s)
void ff_celt_free (CeltContext **ps)
int ff_celt_init (AVCodecContext *avctx, CeltContext **ps, int output_channels)
Detailed Description
Opus CELT decoder.
Definition in file opus_celt.c.
Macro Definition Documentation
CELT_PVQ_U
#define CELT_PVQ_U (n, k) (ff_celt_pvq_u_row[FFMIN(n, k)][FFMAX(n, k)])
CELT_PVQ_V
#define CELT_PVQ_V (n, k) (CELT_PVQ_U(n, k) + CELT_PVQ_U(n, (k) + 1))
Referenced by celt_decode_pulses().
Enumeration Type Documentation
CeltSpread
enum CeltSpread
Enumerator
CELT_SPREAD_NONE
CELT_SPREAD_LIGHT
CELT_SPREAD_NORMAL
CELT_SPREAD_AGGRESSIVE
Definition at line 36 of file opus_celt.c.
Function Documentation
celt_cos()
static int16_t celt_cos (int16_t x) inline static
Definition at line 106 of file opus_celt.c.
Referenced by celt_decode_band().
celt_log2tan()
static int celt_log2tan (int isin, int icos) inline static
Definition at line 113 of file opus_celt.c.
Referenced by celt_decode_band().
celt_rng()
static uint32_t celt_rng (CeltContext * s) inline static
Definition at line 125 of file opus_celt.c.
Referenced by celt_decode_band(), and process_anticollapse().
celt_decode_coarse_energy()
static void celt_decode_coarse_energy (CeltContext * s, OpusRangeCoder * rc) static
Definition at line 131 of file opus_celt.c.
Referenced by ff_celt_decode_frame().
celt_decode_fine_energy()
static void celt_decode_fine_energy (CeltContext * s, OpusRangeCoder * rc) static
Definition at line 181 of file opus_celt.c.
Referenced by ff_celt_decode_frame().
celt_decode_final_energy()
static void celt_decode_final_energy (CeltContext * s, OpusRangeCoder * rc, int bits_left) static
Definition at line 200 of file opus_celt.c.
Referenced by ff_celt_decode_frame().
celt_decode_tf_changes()
static void celt_decode_tf_changes (CeltContext * s, OpusRangeCoder * rc, int transient) static
Definition at line 222 of file opus_celt.c.
Referenced by ff_celt_decode_frame().
celt_decode_allocation()
static void celt_decode_allocation (CeltContext * s, OpusRangeCoder * rc) static
Definition at line 250 of file opus_celt.c.
Referenced by ff_celt_decode_frame().
celt_bits2pulses()
static int celt_bits2pulses (const uint8_t * cache, int bits) inline static
Definition at line 582 of file opus_celt.c.
Referenced by celt_decode_band().
celt_pulses2bits()
static int celt_pulses2bits (const uint8_t * cache, int pulses) inline static
Definition at line 601 of file opus_celt.c.
Referenced by celt_decode_band().
celt_normalize_residual()
static void celt_normalize_residual (const int *av_restrict iy, float *av_restrict X, int N, float g) inline static
Definition at line 607 of file opus_celt.c.
Referenced by celt_alg_unquant().
celt_exp_rotation1()
static void celt_exp_rotation1 (float * X, unsigned int len, unsigned int stride, float c, float s) static
Definition at line 615 of file opus_celt.c.
Referenced by celt_exp_rotation().
celt_exp_rotation()
static void celt_exp_rotation (float * X, unsigned int len, unsigned int stride, unsigned int K, enum CeltSpread spread) inline static
Definition at line 640 of file opus_celt.c.
Referenced by celt_alg_unquant().
celt_extract_collapse_mask()
static unsigned int celt_extract_collapse_mask (const int * iy, unsigned int N, unsigned int B) inline static
Definition at line 676 of file opus_celt.c.
Referenced by celt_alg_unquant().
celt_renormalize_vector()
static void celt_renormalize_vector (float * X, int N, float gain) inline static
Definition at line 697 of file opus_celt.c.
Referenced by celt_decode_band(), and process_anticollapse().
celt_stereo_merge()
static void celt_stereo_merge (float * X, float * Y, float mid, int N) inline static
Definition at line 709 of file opus_celt.c.
Referenced by celt_decode_band().
celt_interleave_hadamard()
static void celt_interleave_hadamard (float * tmp, float * X, int N0, int stride, int hadamard) static
Definition at line 749 of file opus_celt.c.
Referenced by celt_decode_band().
celt_deinterleave_hadamard()
static void celt_deinterleave_hadamard (float * tmp, float * X, int N0, int stride, int hadamard) static
Definition at line 770 of file opus_celt.c.
Referenced by celt_decode_band().
celt_haar1()
static void celt_haar1 (float * X, int N0, int stride) static
Definition at line 791 of file opus_celt.c.
Referenced by celt_decode_band().
celt_compute_qn()
static int celt_compute_qn (int N, int b, int offset, int pulse_cap, int dualstereo) inline static
Definition at line 805 of file opus_celt.c.
Referenced by celt_decode_band().
celt_cwrsi()
static uint64_t celt_cwrsi (unsigned int N, unsigned int K, unsigned int i, int * y) inline static
Definition at line 822 of file opus_celt.c.
Referenced by celt_decode_pulses().
celt_decode_pulses()
static float celt_decode_pulses (OpusRangeCoder * rc, int * y, unsigned int N, unsigned int K) inline static
Definition at line 907 of file opus_celt.c.
Referenced by celt_alg_unquant().
celt_alg_unquant()
static unsigned int celt_alg_unquant (OpusRangeCoder * rc, float * X, unsigned int N, unsigned int K, enum CeltSpread spread, unsigned int blocks, float gain) inline static
Decode pulse vector and combine the result with the pitch vector to produce the final normalised signal in the current band.
Definition at line 918 of file opus_celt.c.
Referenced by celt_decode_band().
celt_decode_band()
static unsigned int celt_decode_band (CeltContext * s, OpusRangeCoder * rc, const int band, float * X, float * Y, int N, int b, unsigned int blocks, float * lowband, int duration, float * lowband_out, int level, float gain, float * lowband_scratch, int fill) static
Definition at line 931 of file opus_celt.c.
Referenced by celt_decode_bands().
celt_denormalize()
static void celt_denormalize (CeltContext * s, CeltFrame * frame, float * data) static
Definition at line 1287 of file opus_celt.c.
Referenced by ff_celt_decode_frame().
celt_postfilter_apply_transition()
static void celt_postfilter_apply_transition (CeltFrame * frame, float * data) static
Definition at line 1300 of file opus_celt.c.
Referenced by celt_postfilter().
celt_postfilter_apply()
static void celt_postfilter_apply (CeltFrame * frame, float * data, int len) static
Definition at line 1345 of file opus_celt.c.
Referenced by celt_postfilter().
celt_postfilter()
static void celt_postfilter (CeltContext * s, CeltFrame * frame) static
Definition at line 1377 of file opus_celt.c.
Referenced by ff_celt_decode_frame().
parse_postfilter()
static int parse_postfilter (CeltContext * s, OpusRangeCoder * rc, int consumed) static
Definition at line 1401 of file opus_celt.c.
Referenced by ff_celt_decode_frame().
process_anticollapse()
static void process_anticollapse (CeltContext * s, CeltFrame * frame, float * X) static
Definition at line 1441 of file opus_celt.c.
Referenced by ff_celt_decode_frame().
celt_decode_bands()
static void celt_decode_bands (CeltContext * s, OpusRangeCoder * rc) static
Definition at line 1493 of file opus_celt.c.
Referenced by ff_celt_decode_frame().
ff_celt_decode_frame()
int ff_celt_decode_frame (CeltContext * s, OpusRangeCoder * rc, float ** output, int coded_channels, int frame_size, int startband, int endband)
Definition at line 1589 of file opus_celt.c.
Referenced by opus_decode_frame(), and opus_decode_redundancy().
ff_celt_flush()
void ff_celt_flush (CeltContext * s)
Definition at line 1759 of file opus_celt.c.
Referenced by ff_celt_init(), opus_decode_flush(), and opus_decode_frame().
ff_celt_free()
void ff_celt_free (CeltContext ** ps)
Definition at line 1786 of file opus_celt.c.
Referenced by ff_celt_init(), and opus_decode_close().
ff_celt_init()
int ff_celt_init (AVCodecContext * avctx, CeltContext ** ps, int output_channels)
Definition at line 1801 of file opus_celt.c.
Referenced by opus_decode_init().