FFmpeg: compat/os2threads.h File Reference
os2threads.h File Reference
os2threads to pthreads wrapper
#include <os2.h>
#include <stdlib.h>
#include <sys/builtin.h>
#include <sys/fmutex.h>
#include "libavutil/attributes.h"
Data Structures
struct pthread_t
struct pthread_cond_t
union pthread_once_t
Macros
#define INCL_DOS
#define PTHREAD_ONCE_INIT {0, _FMUTEX_INITIALIZER}
Typedefs
typedef void pthread_attr_t
typedef HMTX pthread_mutex_t
typedef void pthread_mutexattr_t
typedef void pthread_condattr_t
Functions
static void thread_entry (void *arg)
static av_always_inline int pthread_create (pthread_t *thread, const pthread_attr_t *attr, void *(*start_routine)(void *), void *arg)
static av_always_inline int pthread_join (pthread_t thread, void **value_ptr)
static av_always_inline int pthread_mutex_init (pthread_mutex_t *mutex, const pthread_mutexattr_t *attr)
static av_always_inline int pthread_mutex_destroy (pthread_mutex_t *mutex)
static av_always_inline int pthread_mutex_lock (pthread_mutex_t *mutex)
static av_always_inline int pthread_mutex_unlock (pthread_mutex_t *mutex)
static av_always_inline int pthread_cond_init (pthread_cond_t *cond, const pthread_condattr_t *attr)
static av_always_inline int pthread_cond_destroy (pthread_cond_t *cond)
static av_always_inline int pthread_cond_signal (pthread_cond_t *cond)
static av_always_inline int pthread_cond_broadcast (pthread_cond_t *cond)
static av_always_inline int pthread_cond_wait (pthread_cond_t *cond, pthread_mutex_t *mutex)
static av_always_inline int pthread_once (pthread_once_t *once_control, void(*init_routine)(void))
Detailed Description
os2threads to pthreads wrapper
Definition in file os2threads.h.
Macro Definition Documentation
INCL_DOS
#define INCL_DOS
Definition at line 29 of file os2threads.h.
PTHREAD_ONCE_INIT
#define PTHREAD_ONCE_INIT {0, _FMUTEX_INITIALIZER}
Definition at line 65 of file os2threads.h.
Typedef Documentation
pthread_attr_t
typedef void pthread_attr_t
Definition at line 47 of file os2threads.h.
pthread_mutex_t
typedef HMTX pthread_mutex_t
Definition at line 49 of file os2threads.h.
pthread_mutexattr_t
typedef void pthread_mutexattr_t
Definition at line 50 of file os2threads.h.
pthread_condattr_t
typedef void pthread_condattr_t
Definition at line 58 of file os2threads.h.
Function Documentation
thread_entry()
static void thread_entry (void * arg) static
Definition at line 67 of file os2threads.h.
Referenced by pthread_create().
pthread_create()
static av_always_inline int pthread_create (pthread_t * thread, const pthread_attr_t * attr, void *(*)(void *) start_routine, void * arg) static
Definition at line 74 of file os2threads.h.
Referenced by async_open(), check_keyboard_interaction(), ff_frame_thread_encoder_init(), ff_frame_thread_init(), ff_slice_thread_init(), fifo_write_header(), iec61883_read_header(), main(), thread_init_internal(), and udp_open().
pthread_join()
static av_always_inline int pthread_join (pthread_t thread, void ** value_ptr) static
Definition at line 88 of file os2threads.h.
Referenced by async_close(), check_keyboard_interaction(), ff_frame_thread_encoder_free(), ff_frame_thread_free(), ff_slice_thread_free(), fifo_write_trailer(), iec61883_close(), main(), slice_thread_uninit(), and udp_close().
pthread_mutex_init()
static av_always_inline int pthread_mutex_init (pthread_mutex_t * mutex, const pthread_mutexattr_t * attr) static
Definition at line 98 of file os2threads.h.
Referenced by async_open(), av_thread_message_queue_alloc(), avf_read_header(), avpacket_queue_init(), decklink_input_callback::decklink_input_callback(), ff_alloc_entries(), ff_frame_thread_encoder_init(), ff_frame_thread_init(), ff_openssl_init(), ff_slice_thread_init(), fifo_init(), iec61883_read_header(), init_opencl_mtx(), omx_encode_init(), qtkit_read_header(), thread_init_internal(), udp_open(), update_dimensions(), and vtenc_init().
pthread_mutex_destroy()
static av_always_inline int pthread_mutex_destroy (pthread_mutex_t * mutex) static
Definition at line 106 of file os2threads.h.
Referenced by async_close(), async_open(), av_thread_message_queue_alloc(), av_thread_message_queue_free(), avpacket_queue_end(), cleanup(), destroy_context(), ff_frame_thread_encoder_free(), ff_frame_thread_free(), ff_openssl_deinit(), ff_slice_thread_free(), fifo_deinit(), free_buffers(), iec61883_close(), init_opencl_mtx(), slice_thread_uninit(), udp_close(), udp_open(), vtenc_close(), and decklink_input_callback::~decklink_input_callback().
pthread_mutex_lock()
static av_always_inline int pthread_mutex_lock (pthread_mutex_t * mutex) static
Definition at line 113 of file os2threads.h.
Referenced by decklink_input_callback::AddRef(), append_buffer(), async_buffer_task(), async_close(), async_read_internal(), async_seek(), av_log_default_callback(), av_thread_message_flush(), av_thread_message_queue_recv(), av_thread_message_queue_send(), av_thread_message_queue_set_err_recv(), av_thread_message_queue_set_err_send(), avpacket_queue_flush(), avpacket_queue_get(), avpacket_queue_put(), avpacket_queue_size(), avpriv_atomic_lock(), cleanup(), event_handler(), ff_frame_thread_encoder_free(), ff_frame_thread_free(), ff_jni_get_env(), ff_slice_thread_free(), ff_slice_thread_init(), ff_thread_await_progress(), ff_thread_await_progress2(), ff_thread_decode_frame(), ff_thread_finish_setup(), ff_thread_get_format(), ff_thread_release_buffer(), ff_thread_report_progress(), ff_thread_report_progress2(), ff_thread_video_encode_frame(), fifo_consumer_thread(), fifo_write_packet(), frame_worker_thread(), get_buffer(), iec61883_callback(), iec61883_read_packet(), iec61883_receive_task(), lock_frames(), park_frame_worker_threads(), pthread_cond_wait(), decklink_input_callback::Release(), release_delayed_buffers(), set_async_error(), slice_thread_uninit(), submit_packet(), thread_execute(), thread_get_buffer_internal(), thread_init_internal(), udp_close(), udp_get_file_handle(), udp_read(), udp_write(), vtenc_q_pop(), vtenc_q_push(), wait_for_state(), and worker().
pthread_mutex_unlock()
static av_always_inline int pthread_mutex_unlock (pthread_mutex_t * mutex) static
Definition at line 120 of file os2threads.h.
Referenced by decklink_input_callback::AddRef(), append_buffer(), async_buffer_task(), async_close(), async_read_internal(), async_seek(), av_log_default_callback(), av_thread_message_flush(), av_thread_message_queue_recv(), av_thread_message_queue_send(), av_thread_message_queue_set_err_recv(), av_thread_message_queue_set_err_send(), avpacket_queue_flush(), avpacket_queue_get(), avpacket_queue_put(), avpacket_queue_size(), avpriv_atomic_unlock(), cleanup(), event_handler(), ff_frame_thread_encoder_free(), ff_frame_thread_free(), ff_jni_get_env(), ff_slice_thread_free(), ff_slice_thread_init(), ff_thread_await_progress(), ff_thread_await_progress2(), ff_thread_decode_frame(), ff_thread_finish_setup(), ff_thread_get_format(), ff_thread_release_buffer(), ff_thread_report_progress(), ff_thread_report_progress2(), ff_thread_video_encode_frame(), fifo_consumer_thread(), fifo_write_packet(), frame_worker_thread(), get_buffer(), iec61883_callback(), iec61883_read_packet(), iec61883_receive_task(), park_frame_worker_threads(), pthread_cond_wait(), decklink_input_callback::Release(), release_delayed_buffers(), set_async_error(), slice_thread_park_workers(), slice_thread_uninit(), submit_packet(), thread_get_buffer_internal(), thread_init_internal(), thread_park_workers(), udp_close(), udp_get_file_handle(), udp_read(), udp_write(), unlock_frames(), vtenc_q_pop(), vtenc_q_push(), wait_for_state(), and worker().
pthread_cond_init()
static av_always_inline int pthread_cond_init (pthread_cond_t * cond, const pthread_condattr_t * attr) static
Definition at line 127 of file os2threads.h.
Referenced by async_open(), av_thread_message_queue_alloc(), avf_read_header(), avpacket_queue_init(), ff_alloc_entries(), ff_frame_thread_encoder_init(), ff_frame_thread_init(), ff_slice_thread_init(), iec61883_read_header(), omx_encode_init(), qtkit_read_header(), thread_init_internal(), udp_open(), update_dimensions(), and vtenc_init().
pthread_cond_destroy()
static av_always_inline int pthread_cond_destroy (pthread_cond_t * cond) static
Definition at line 138 of file os2threads.h.
Referenced by async_close(), async_open(), av_thread_message_queue_alloc(), av_thread_message_queue_free(), avpacket_queue_end(), cleanup(), destroy_context(), ff_frame_thread_encoder_free(), ff_frame_thread_free(), ff_slice_thread_free(), free_buffers(), iec61883_close(), slice_thread_uninit(), udp_close(), udp_open(), and vtenc_close().
pthread_cond_signal()
static av_always_inline int pthread_cond_signal (pthread_cond_t * cond) static
Definition at line 146 of file os2threads.h.
Referenced by async_buffer_task(), async_close(), async_read_internal(), async_seek(), av_thread_message_queue_free(), avpacket_queue_put(), AVFFrameReceiver::captureOutput:didOutputSampleBuffer:fromConnection:, AVFAudioReceiver::captureOutput:didOutputSampleBuffer:fromConnection:, FFMPEG_FrameReceiver::captureOutput:didOutputVideoFrame:withSampleBuffer:fromConnection:, ff_frame_thread_free(), ff_thread_report_progress2(), ff_thread_video_encode_frame(), frame_worker_thread(), pthread_cond_broadcast(), submit_packet(), udp_close(), udp_get_file_handle(), udp_write(), vtenc_q_push(), and worker().
pthread_cond_broadcast()
static av_always_inline int pthread_cond_broadcast (pthread_cond_t * cond) static
Definition at line 156 of file os2threads.h.
Referenced by append_buffer(), av_thread_message_flush(), av_thread_message_queue_set_err_recv(), av_thread_message_queue_set_err_send(), event_handler(), ff_frame_thread_encoder_free(), ff_slice_thread_free(), ff_thread_finish_setup(), ff_thread_get_format(), ff_thread_report_progress(), frame_worker_thread(), iec61883_callback(), iec61883_receive_task(), slice_thread_uninit(), thread_execute(), and thread_get_buffer_internal().
pthread_cond_wait()
static av_always_inline int pthread_cond_wait (pthread_cond_t * cond, pthread_mutex_t * mutex) static
Definition at line 164 of file os2threads.h.
Referenced by async_buffer_task(), async_read_internal(), async_seek(), av_thread_message_queue_free(), avf_read_packet(), avpacket_queue_get(), ff_thread_await_progress(), ff_thread_await_progress2(), ff_thread_decode_frame(), ff_thread_get_format(), ff_thread_video_encode_frame(), frame_worker_thread(), get_buffer(), iec61883_read_packet(), park_frame_worker_threads(), qtkit_read_packet(), slice_thread_park_workers(), submit_packet(), thread_get_buffer_internal(), thread_park_workers(), udp_get_file_handle(), vtenc_q_pop(), wait_for_state(), and worker().
pthread_once()
static av_always_inline int pthread_once (pthread_once_t * once_control, void(*)(void) init_routine) static
Definition at line 182 of file os2threads.h.
Referenced by ff_jni_get_env().