FFmpeg: libavdevice/oss.c File Reference
oss.c File Reference
#include "config.h"
#include <string.h>
#include <sys/soundcard.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include "libavutil/log.h"
#include "libavcodec/avcodec.h"
#include "avdevice.h"
#include "oss.h"
Macros
#define CHECK_IOCTL_ERROR(event)
Functions
int ff_oss_audio_open (AVFormatContext *s1, int is_output, const char *audio_device)
int ff_oss_audio_close (OSSAudioData *s)
Macro Definition Documentation
CHECK_IOCTL_ERROR
#define CHECK_IOCTL_ERROR (event)
Value:
if (err < 0) {                                                            \
        av_log(s1, AV_LOG_ERROR, #event ": %s\n", av_err2str(AVERROR(errno)));\
        goto fail;                                                            \
    }
Referenced by ff_oss_audio_open().
Function Documentation
ff_oss_audio_open()
int ff_oss_audio_open (AVFormatContext * s1, int is_output, const char * audio_device)
Definition at line 45 of file oss.c.
Referenced by audio_read_header(), and audio_write_header().
ff_oss_audio_close()
int ff_oss_audio_close (OSSAudioData * s)
Definition at line 140 of file oss.c.
Referenced by audio_read_close(), and audio_write_trailer().