FFmpeg: libavdevice/oss.h File Reference
oss.h File Reference
#include "libavcodec/avcodec.h"
#include "libavformat/avformat.h"
Data Structures
struct OSSAudioData
Macros
#define OSS_AUDIO_BLOCK_SIZE 4096
Functions
int ff_oss_audio_open (AVFormatContext *s1, int is_output, const char *audio_device)
int ff_oss_audio_close (OSSAudioData *s)
Macro Definition Documentation
OSS_AUDIO_BLOCK_SIZE
#define OSS_AUDIO_BLOCK_SIZE 4096
Definition at line 26 of file oss.h.
Referenced by audio_write_packet(), and ff_oss_audio_open().
Function Documentation
ff_oss_audio_open()
int ff_oss_audio_open (AVFormatContext * s1, int is_output, const char * audio_device)
Definition at line 45 of file oss.c.
Referenced by audio_read_header(), and audio_write_header().
ff_oss_audio_close()
int ff_oss_audio_close (OSSAudioData * s)
Definition at line 140 of file oss.c.
Referenced by audio_read_close(), and audio_write_trailer().