FFmpeg: libavcodec/parser.h File Reference
parser.h File Reference
#include "avcodec.h"
Data Structures
struct ParseContext
Macros
#define END_NOT_FOUND (-100)
Functions
int ff_combine_frame (ParseContext *pc, int next, const uint8_t **buf, int *buf_size)
Combine the (truncated) bitstream to a complete frame.
int ff_mpeg4video_split (AVCodecContext *avctx, const uint8_t *buf, int buf_size)
void ff_parse_close (AVCodecParserContext *s)
void ff_fetch_timestamp (AVCodecParserContext *s, int off, int remove, int fuzzy)
Fetch timestamps for a specific byte within the current access unit.
Macro Definition Documentation
END_NOT_FOUND
#define END_NOT_FOUND (-100)
Definition at line 40 of file parser.h.
Referenced by adx_parse(), bmp_parse(), cavs_find_frame_end(), dca_find_frame_end(), dnxhd_find_frame_end(), dpx_parse(), ff_aac_ac3_parse(), ff_combine_frame(), ff_h263_find_frame_end(), ff_mpeg1_find_frame_end(), ff_mpeg4_find_frame_end(), find_frame_end(), g729_parse(), gsm_parse(), h261_find_frame_end(), h264_find_frame_end(), h264_parse(), hevc_find_frame_end(), latm_find_frame_end(), mlp_parse(), mpegaudio_parse(), opus_find_frame_end(), png_parse(), pnm_parse(), tak_parse(), and vc1_parse().
Function Documentation
ff_combine_frame()
int ff_combine_frame (ParseContext * pc, int next, const uint8_t ** buf, int * buf_size)
Combine the (truncated) bitstream to a complete frame.
Returns
-1 if no complete frame could be created, AVERROR(ENOMEM) if there was a memory allocation error
Definition at line 251 of file parser.c.
Referenced by adx_parse(), bmp_parse(), cavsvideo_parse(), dca_parse(), dnxhd_parse(), dpx_parse(), ff_aac_ac3_parse(), ff_h263_decode_frame(), g729_parse(), gsm_parse(), h261_parse(), h263_parse(), h264_parse(), hevc_parse(), jpeg_parse(), latm_parse(), mlp_parse(), mpeg4video_parse(), mpeg_decode_frame(), mpegaudio_parse(), mpegvideo_parse(), opus_parse(), png_parse(), pnm_parse(), tak_parse(), and vc1_parse().
ff_mpeg4video_split()
int ff_mpeg4video_split (AVCodecContext * avctx, const uint8_t * buf, int buf_size)
Definition at line 334 of file parser.c.
ff_parse_close()
void ff_parse_close (AVCodecParserContext * s)
Definition at line 327 of file parser.c.
ff_fetch_timestamp()
void ff_fetch_timestamp (AVCodecParserContext * s, int off, int remove, int fuzzy)
Fetch timestamps for a specific byte within the current access unit.
Parameters
off byte position within the access unit
remove Found timestamps will be removed if set to 1, kept if set to 0.
fuzzy Only use found value if it is more informative than what we already have
Definition at line 106 of file parser.c.
Referenced by av_parser_parse2(), and ff_mpeg1_find_frame_end().