FFmpeg: libavutil/pca.c File Reference
pca.c File Reference
principal component analysis (PCA)
#include "common.h"
#include "pca.h"
Data Structures
struct PCA
Macros
#define ROTATE(a, i, j, k, l)
Functions
PCA * ff_pca_init (int n)
void ff_pca_free (PCA *pca)
void ff_pca_add (PCA *pca, const double *v)
int ff_pca (PCA *pca, double *eigenvector, double *eigenvalue)
Detailed Description
principal component analysis (PCA)
Definition in file pca.c.
Macro Definition Documentation
ROTATE
#define ROTATE (a, i, j, k, l)
Value:
{\
    double g=a[j + i*n];\
    double h=a[l + k*n];\
    a[j + i*n]=g-s*(h+g*tau);\
    a[l + k*n]=h+s*(g-h*tau); }
Referenced by ff_pca().
Function Documentation
ff_pca_init()
PCA* ff_pca_init (int n)
Definition at line 38 of file pca.c.
Referenced by main().
ff_pca_free()
void ff_pca_free (PCA * pca)
Definition at line 61 of file pca.c.
Referenced by ff_pca_init().
ff_pca_add()
void ff_pca_add (PCA * pca, const double * v)
Definition at line 68 of file pca.c.
Referenced by main().
ff_pca()
int ff_pca (PCA * pca, double * eigenvector, double * eigenvalue)
Definition at line 80 of file pca.c.
Referenced by main().