FFmpeg: libavutil/pca.h File Reference
pca.h File Reference
principal component analysis (PCA)
Functions
struct PCA * ff_pca_init (int n)
void ff_pca_free (struct PCA *pca)
void ff_pca_add (struct PCA *pca, const double *v)
int ff_pca (struct PCA *pca, double *eigenvector, double *eigenvalue)
Detailed Description
principal component analysis (PCA)
Definition in file pca.h.
Function Documentation
ff_pca_init()
struct PCA* ff_pca_init (int n)
Definition at line 38 of file pca.c.
Referenced by main().
ff_pca_free()
void ff_pca_free (struct PCA * pca)
Definition at line 61 of file pca.c.
Referenced by ff_pca_init().
ff_pca_add()
void ff_pca_add (struct PCA * pca, const double * v)
Definition at line 68 of file pca.c.
Referenced by main().
ff_pca()
int ff_pca (struct PCA * pca, double * eigenvector, double * eigenvalue)
Definition at line 80 of file pca.c.
Referenced by main().