FFmpeg: libavcodec/pgssubdec.c File Reference
pgssubdec.c File Reference
PGS subtitle decoder.
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
#include "mathops.h"
#include "libavutil/colorspace.h"
#include "libavutil/imgutils.h"
#include "libavutil/opt.h"
Data Structures
struct PGSSubObjectRef
struct PGSSubPresentation
struct PGSSubObject
struct PGSSubObjects
struct PGSSubPalette
struct PGSSubPalettes
struct PGSSubContext
Macros
#define RGBA(r, g, b, a) (((unsigned)(a) << 24) | ((r) << 16) | ((g) << 8) | (b))
#define MAX_EPOCH_PALETTES 8
#define MAX_EPOCH_OBJECTS 64
#define MAX_OBJECT_REFS 2
#define OFFSET(x) offsetof(PGSSubContext, x)
#define SD AV_OPT_FLAG_SUBTITLE_PARAM | AV_OPT_FLAG_DECODING_PARAM
Enumerations
enum SegmentType {
PALETTE_SEGMENT = 0x14, OBJECT_SEGMENT = 0x15, PRESENTATION_SEGMENT = 0x16, WINDOW_SEGMENT = 0x17,
DISPLAY_SEGMENT = 0x80
}
Functions
static void flush_cache (AVCodecContext *avctx)
static PGSSubObject * find_object (int id, PGSSubObjects *objects)
static PGSSubPalette * find_palette (int id, PGSSubPalettes *palettes)
static av_cold int init_decoder (AVCodecContext *avctx)
static av_cold int close_decoder (AVCodecContext *avctx)
static int decode_rle (AVCodecContext *avctx, AVSubtitleRect *rect, const uint8_t *buf, unsigned int buf_size)
Decode the RLE data.
static int parse_object_segment (AVCodecContext *avctx, const uint8_t *buf, int buf_size)
Parse the picture segment packet.
static int parse_palette_segment (AVCodecContext *avctx, const uint8_t *buf, int buf_size)
Parse the palette segment packet.
static int parse_presentation_segment (AVCodecContext *avctx, const uint8_t *buf, int buf_size, int64_t pts)
Parse the presentation segment packet.
static int display_end_segment (AVCodecContext *avctx, void *data, const uint8_t *buf, int buf_size)
Parse the display segment packet.
static int decode (AVCodecContext *avctx, void *data, int *data_size, AVPacket *avpkt)
Variables
static const AVOption options []
static const AVClass pgsdec_class
AVCodec ff_pgssub_decoder
Detailed Description
PGS subtitle decoder.
Definition in file pgssubdec.c.
Macro Definition Documentation
RGBA
#define RGBA (r, g, b, a) (((unsigned)(a) << 24) | ((r) << 16) | ((g) << 8) | (b))
Definition at line 36 of file pgssubdec.c.
Referenced by parse_palette_segment().
MAX_EPOCH_PALETTES
#define MAX_EPOCH_PALETTES 8
Definition at line 37 of file pgssubdec.c.
Referenced by parse_palette_segment().
MAX_EPOCH_OBJECTS
#define MAX_EPOCH_OBJECTS 64
Definition at line 38 of file pgssubdec.c.
Referenced by parse_object_segment().
MAX_OBJECT_REFS
#define MAX_OBJECT_REFS 2
Definition at line 39 of file pgssubdec.c.
Referenced by parse_presentation_segment().
OFFSET
#define OFFSET (x) offsetof(PGSSubContext, x)
Definition at line 695 of file pgssubdec.c.
SD
#define SD AV_OPT_FLAG_SUBTITLE_PARAM | AV_OPT_FLAG_DECODING_PARAM
Definition at line 696 of file pgssubdec.c.
Enumeration Type Documentation
SegmentType
enum SegmentType
Enumerator
PALETTE_SEGMENT
OBJECT_SEGMENT
PRESENTATION_SEGMENT
WINDOW_SEGMENT
DISPLAY_SEGMENT
Definition at line 41 of file pgssubdec.c.
Function Documentation
flush_cache()
static void flush_cache (AVCodecContext * avctx) static
Definition at line 101 of file pgssubdec.c.
Referenced by close_decoder(), and parse_presentation_segment().
find_object()
static PGSSubObject* find_object (int id, PGSSubObjects * objects) static
Definition at line 115 of file pgssubdec.c.
Referenced by display_end_segment(), and parse_object_segment().
find_palette()
static PGSSubPalette* find_palette (int id, PGSSubPalettes * palettes) static
Definition at line 126 of file pgssubdec.c.
Referenced by display_end_segment(), and parse_palette_segment().
init_decoder()
static av_cold int init_decoder (AVCodecContext * avctx) static
Definition at line 137 of file pgssubdec.c.
close_decoder()
static av_cold int close_decoder (AVCodecContext * avctx) static
Definition at line 144 of file pgssubdec.c.
decode_rle()
static int decode_rle (AVCodecContext * avctx, AVSubtitleRect * rect, const uint8_t * buf, unsigned int buf_size) static
Decode the RLE data.
The subtitle is stored as a Run Length Encoded image.
Parameters
avctx contains the current codec context
sub pointer to the processed subtitle data
buf pointer to the RLE data to process
buf_size size of the RLE data to process
Definition at line 161 of file pgssubdec.c.
Referenced by display_end_segment().
parse_object_segment()
static int parse_object_segment (AVCodecContext * avctx, const uint8_t * buf, int buf_size) static
Parse the picture segment packet.
The picture segment contains details on the sequence id, width, height and Run Length Encoded (RLE) bitmap data.
Parameters
avctx contains the current codec context
buf pointer to the packet to process
buf_size size of packet to process
Definition at line 231 of file pgssubdec.c.
Referenced by decode().
parse_palette_segment()
static int parse_palette_segment (AVCodecContext * avctx, const uint8_t * buf, int buf_size) static
Parse the palette segment packet.
The palette segment contains details of the palette, a maximum of 256 colors can be defined.
Parameters
avctx contains the current codec context
buf pointer to the packet to process
buf_size size of packet to process
Definition at line 323 of file pgssubdec.c.
Referenced by decode().
parse_presentation_segment()
static int parse_presentation_segment (AVCodecContext * avctx, const uint8_t * buf, int buf_size, int64_t pts) static
Parse the presentation segment packet.
The presentation segment contains details on the video width, video height, x & y subtitle position.
Parameters
avctx contains the current codec context
buf pointer to the packet to process
buf_size size of packet to process
Todo:
TODO: Implement cropping
Definition at line 385 of file pgssubdec.c.
Referenced by decode().
display_end_segment()
static int display_end_segment (AVCodecContext * avctx, void * data, const uint8_t * buf, int buf_size) static
Parse the display segment packet.
The display segment controls the updating of the display.
Parameters
avctx contains the current codec context
data pointer to the data pertaining the subtitle to display
buf pointer to the packet to process
buf_size size of packet to process
Definition at line 495 of file pgssubdec.c.
Referenced by decode().
decode()
static int decode (AVCodecContext * avctx, void * data, int * data_size, AVPacket * avpkt) static
Definition at line 614 of file pgssubdec.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    {"forced_subs_only", "Only show forced subtitles", OFFSET(forced_subs_only), AV_OPT_TYPE_BOOL, {.i64 = 0}, 0, 1, SD},
    { NULL },
}
Definition at line 697 of file pgssubdec.c.
pgsdec_class
const AVClass pgsdec_class static
Initial value:
= {
    .class_name = "PGS subtitle decoder",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 702 of file pgssubdec.c.
ff_pgssub_decoder
AVCodec ff_pgssub_decoder
Initial value:
= {
    .name           = "pgssub",
    .long_name      = NULL_IF_CONFIG_SMALL("HDMV Presentation Graphic Stream subtitles"),
    .type           = AVMEDIA_TYPE_SUBTITLE,
    .id             = AV_CODEC_ID_HDMV_PGS_SUBTITLE,
    .priv_data_size = sizeof(PGSSubContext),
    .init           = init_decoder,
    .close          = close_decoder,
    .decode         = decode,
    .priv_class     = &pgsdec_class,
}
Definition at line 709 of file pgssubdec.c.