FFmpeg: libavcodec/arm/pixblockdsp_init_arm.c File Reference
pixblockdsp_init_arm.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/arm/cpu.h"
#include "libavcodec/avcodec.h"
#include "libavcodec/pixblockdsp.h"
Functions
void ff_get_pixels_armv6 (int16_t *block, const uint8_t *pixels, ptrdiff_t stride)
void ff_diff_pixels_armv6 (int16_t *block, const uint8_t *s1, const uint8_t *s2, int stride)
av_cold void ff_pixblockdsp_init_arm (PixblockDSPContext *c, AVCodecContext *avctx, unsigned high_bit_depth)
Function Documentation
ff_get_pixels_armv6()
void ff_get_pixels_armv6 (int16_t * block, const uint8_t * pixels, ptrdiff_t stride)
Referenced by ff_pixblockdsp_init_arm().
ff_diff_pixels_armv6()
void ff_diff_pixels_armv6 (int16_t * block, const uint8_t * s1, const uint8_t * s2, int stride)
Referenced by ff_pixblockdsp_init_arm().
ff_pixblockdsp_init_arm()
av_cold void ff_pixblockdsp_init_arm (PixblockDSPContext * c, AVCodecContext * avctx, unsigned high_bit_depth)
Definition at line 31 of file pixblockdsp_init_arm.c.
Referenced by ff_pixblockdsp_init().