FFmpeg: libavcodec/mips/pixblockdsp_msa.c File Reference
pixblockdsp_msa.c File Reference
#include "libavutil/mips/generic_macros_msa.h"
#include "pixblockdsp_mips.h"
Functions
static void diff_pixels_msa (int16_t *block, const uint8_t *src1, const uint8_t *src2, int32_t stride)
static void copy_8bit_to_16bit_width8_msa (const uint8_t *src, int32_t src_stride, int16_t *dst, int32_t dst_stride, int32_t height)
static void copy_16multx8mult_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height, int32_t width)
static void copy_width16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
void ff_get_pixels_16_msa (int16_t *av_restrict dest, const uint8_t *src, ptrdiff_t stride)
void ff_get_pixels_8_msa (int16_t *av_restrict dest, const uint8_t *src, ptrdiff_t stride)
void ff_diff_pixels_msa (int16_t *av_restrict block, const uint8_t *src1, const uint8_t *src2, int stride)
Function Documentation
diff_pixels_msa()
static void diff_pixels_msa (int16_t * block, const uint8_t * src1, const uint8_t * src2, int32_t stride) static
Definition at line 24 of file pixblockdsp_msa.c.
Referenced by ff_diff_pixels_msa().
copy_8bit_to_16bit_width8_msa()
static void copy_8bit_to_16bit_width8_msa (const uint8_t * src, int32_t src_stride, int16_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 42 of file pixblockdsp_msa.c.
Referenced by ff_get_pixels_8_msa().
copy_16multx8mult_msa()
static void copy_16multx8mult_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height, int32_t width) static
Definition at line 65 of file pixblockdsp_msa.c.
Referenced by copy_width16_msa().
copy_width16_msa()
static void copy_width16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 93 of file pixblockdsp_msa.c.
Referenced by ff_get_pixels_16_msa().
ff_get_pixels_16_msa()
void ff_get_pixels_16_msa (int16_t *av_restrict dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 127 of file pixblockdsp_msa.c.
ff_get_pixels_8_msa()
void ff_get_pixels_8_msa (int16_t *av_restrict dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 133 of file pixblockdsp_msa.c.
ff_diff_pixels_msa()
void ff_diff_pixels_msa (int16_t *av_restrict block, const uint8_t * src1, const uint8_t * src2, int stride)
Definition at line 139 of file pixblockdsp_msa.c.