FFmpeg: libavcodec/pixblockdsp.h File Reference
pixblockdsp.h File Reference
#include <stdint.h>
#include "avcodec.h"
Data Structures
struct PixblockDSPContext
Functions
void ff_pixblockdsp_init (PixblockDSPContext *c, AVCodecContext *avctx)
void ff_pixblockdsp_init_alpha (PixblockDSPContext *c, AVCodecContext *avctx, unsigned high_bit_depth)
void ff_pixblockdsp_init_arm (PixblockDSPContext *c, AVCodecContext *avctx, unsigned high_bit_depth)
void ff_pixblockdsp_init_ppc (PixblockDSPContext *c, AVCodecContext *avctx, unsigned high_bit_depth)
void ff_pixblockdsp_init_x86 (PixblockDSPContext *c, AVCodecContext *avctx, unsigned high_bit_depth)
void ff_pixblockdsp_init_mips (PixblockDSPContext *c, AVCodecContext *avctx, unsigned high_bit_depth)
Function Documentation
ff_pixblockdsp_init()
void ff_pixblockdsp_init (PixblockDSPContext * c, AVCodecContext * avctx)
Definition at line 81 of file pixblockdsp.c.
Referenced by avcodec_dct_init(), checkasm_check_pixblockdsp(), dnxhd_encode_init(), dvvideo_encode_init(), encode_init(), and ff_mpv_encode_init().
ff_pixblockdsp_init_alpha()
void ff_pixblockdsp_init_alpha (PixblockDSPContext * c, AVCodecContext * avctx, unsigned high_bit_depth)
Definition at line 70 of file pixblockdsp_alpha.c.
Referenced by ff_pixblockdsp_init().
ff_pixblockdsp_init_arm()
void ff_pixblockdsp_init_arm (PixblockDSPContext * c, AVCodecContext * avctx, unsigned high_bit_depth)
Definition at line 31 of file pixblockdsp_init_arm.c.
Referenced by ff_pixblockdsp_init().
ff_pixblockdsp_init_ppc()
void ff_pixblockdsp_init_ppc (PixblockDSPContext * c, AVCodecContext * avctx, unsigned high_bit_depth)
Definition at line 268 of file pixblockdsp.c.
Referenced by ff_pixblockdsp_init().
ff_pixblockdsp_init_x86()
void ff_pixblockdsp_init_x86 (PixblockDSPContext * c, AVCodecContext * avctx, unsigned high_bit_depth)
Definition at line 33 of file pixblockdsp_init.c.
Referenced by ff_pixblockdsp_init().
ff_pixblockdsp_init_mips()
void ff_pixblockdsp_init_mips (PixblockDSPContext * c, AVCodecContext * avctx, unsigned high_bit_depth)
Definition at line 60 of file pixblockdsp_init_mips.c.
Referenced by ff_pixblockdsp_init().