FFmpeg: libavutil/pixdesc.c File Reference
pixdesc.c File Reference
#include <stdio.h>
#include <string.h>
#include "avassert.h"
#include "avstring.h"
#include "common.h"
#include "pixfmt.h"
#include "pixdesc.h"
#include "internal.h"
#include "intreadwrite.h"
#include "version.h"
Macros
#define BAYER8_DESC_COMMON
#define BAYER16_DESC_COMMON
#define X_NE(be, le) le
#define FF_COLOR_NA -1
#define FF_COLOR_RGB 0
RGB color space.
#define FF_COLOR_GRAY 1
gray color space
#define FF_COLOR_YUV 2
YUV color space.
#define FF_COLOR_YUV_JPEG 3
YUV color space.
#define FF_COLOR_XYZ 4
#define pixdesc_has_alpha(pixdesc) ((pixdesc)->nb_components == 2 || (pixdesc)->nb_components == 4 || (pixdesc)->flags & AV_PIX_FMT_FLAG_PAL)
Functions
void av_read_image_line (uint16_t *dst, const uint8_t *data[4], const int linesize[4], const AVPixFmtDescriptor *desc, int x, int y, int c, int w, int read_pal_component)
Read a line from an image, and write the values of the pixel format component c to dst.
void av_write_image_line (const uint16_t *src, uint8_t *data[4], const int linesize[4], const AVPixFmtDescriptor *desc, int x, int y, int c, int w)
Write the values from src to the pixel format component c of an image line.
static enum AVPixelFormat get_pix_fmt_internal (const char *name)
const char * av_get_pix_fmt_name (enum AVPixelFormat pix_fmt)
Return the short name for a pixel format, NULL in case pix_fmt is unknown.
enum AVPixelFormat av_get_pix_fmt (const char *name)
Return the pixel format corresponding to name.
int av_get_bits_per_pixel (const AVPixFmtDescriptor *pixdesc)
Return the number of bits per pixel used by the pixel format described by pixdesc.
int av_get_padded_bits_per_pixel (const AVPixFmtDescriptor *pixdesc)
Return the number of bits per pixel for the pixel format described by pixdesc, including any padding or unused bits.
char * av_get_pix_fmt_string (char *buf, int buf_size, enum AVPixelFormat pix_fmt)
Print in buf the string corresponding to the pixel format with number pix_fmt, or a header if pix_fmt is negative.
const AVPixFmtDescriptor * av_pix_fmt_desc_get (enum AVPixelFormat pix_fmt)
const AVPixFmtDescriptor * av_pix_fmt_desc_next (const AVPixFmtDescriptor *prev)
Iterate over all pixel format descriptors known to libavutil.
enum AVPixelFormat av_pix_fmt_desc_get_id (const AVPixFmtDescriptor *desc)
int av_pix_fmt_get_chroma_sub_sample (enum AVPixelFormat pix_fmt, int *h_shift, int *v_shift)
Utility function to access log2_chroma_w log2_chroma_h from the pixel format AVPixFmtDescriptor.
int av_pix_fmt_count_planes (enum AVPixelFormat pix_fmt)
void ff_check_pixfmt_descriptors (void)
enum AVPixelFormat av_pix_fmt_swap_endianness (enum AVPixelFormat pix_fmt)
Utility function to swap the endianness of a pixel format.
static int get_color_type (const AVPixFmtDescriptor *desc)
static int get_pix_fmt_depth (int *min, int *max, enum AVPixelFormat pix_fmt)
static int get_pix_fmt_score (enum AVPixelFormat dst_pix_fmt, enum AVPixelFormat src_pix_fmt, unsigned *lossp, unsigned consider)
int av_get_pix_fmt_loss (enum AVPixelFormat dst_pix_fmt, enum AVPixelFormat src_pix_fmt, int has_alpha)
Compute what kind of losses will occur when converting from one specific pixel format to another.
enum AVPixelFormat av_find_best_pix_fmt_of_2 (enum AVPixelFormat dst_pix_fmt1, enum AVPixelFormat dst_pix_fmt2, enum AVPixelFormat src_pix_fmt, int has_alpha, int *loss_ptr)
Compute what kind of losses will occur when converting from one specific pixel format to another.
const char * av_color_range_name (enum AVColorRange range)
const char * av_color_primaries_name (enum AVColorPrimaries primaries)
const char * av_color_transfer_name (enum AVColorTransferCharacteristic transfer)
const char * av_color_space_name (enum AVColorSpace space)
const char * av_chroma_location_name (enum AVChromaLocation location)
Variables
static FF_DISABLE_DEPRECATION_WARNINGS const AVPixFmtDescriptor av_pix_fmt_descriptors [AV_PIX_FMT_NB]
static FF_ENABLE_DEPRECATION_WARNINGS const char * color_range_names []
static const char * color_primaries_names [AVCOL_PRI_NB]
static const char * color_transfer_names []
static const char * color_space_names []
static const char * chroma_location_names []
Macro Definition Documentation
BAYER8_DESC_COMMON
#define BAYER8_DESC_COMMON
Value:
.nb_components= 3, \
        .log2_chroma_w= 0, \
        .log2_chroma_h= 0, \
        .comp = {          \
            {0,1,0,0,2,0,1,1},\
            {0,1,0,0,4,0,3,1},\
            {0,1,0,0,2,0,1,1},\
        },                 \
BAYER16_DESC_COMMON
#define BAYER16_DESC_COMMON
Value:
.nb_components= 3, \
        .log2_chroma_w= 0, \
        .log2_chroma_h= 0, \
        .comp = {          \
            {0,2,0,0,4,1,3,1},\
            {0,2,0,0,8,1,7,1},\
            {0,2,0,0,4,1,3,1},\
        },                 \
X_NE
#define X_NE (be, le) le
Definition at line 2257 of file pixdesc.c.
Referenced by av_get_pix_fmt().
FF_COLOR_NA
#define FF_COLOR_NA -1
Definition at line 2447 of file pixdesc.c.
Referenced by get_color_type().
FF_COLOR_RGB
#define FF_COLOR_RGB 0
RGB color space.
Definition at line 2448 of file pixdesc.c.
Referenced by get_color_type(), and get_pix_fmt_score().
FF_COLOR_GRAY
#define FF_COLOR_GRAY 1
gray color space
Definition at line 2449 of file pixdesc.c.
Referenced by get_color_type(), and get_pix_fmt_score().
FF_COLOR_YUV
#define FF_COLOR_YUV 2
YUV color space.
16 <= Y <= 235, 16 <= U, V <= 240
Definition at line 2450 of file pixdesc.c.
Referenced by get_color_type(), and get_pix_fmt_score().
FF_COLOR_YUV_JPEG
#define FF_COLOR_YUV_JPEG 3
YUV color space.
0 <= Y <= 255, 0 <= U, V <= 255
Definition at line 2451 of file pixdesc.c.
Referenced by get_color_type(), and get_pix_fmt_score().
FF_COLOR_XYZ
#define FF_COLOR_XYZ 4
Definition at line 2452 of file pixdesc.c.
Referenced by get_color_type().
pixdesc_has_alpha
#define pixdesc_has_alpha (pixdesc) ((pixdesc)->nb_components == 2 || (pixdesc)->nb_components == 4 || (pixdesc)->flags & AV_PIX_FMT_FLAG_PAL)
Definition at line 2454 of file pixdesc.c.
Referenced by get_pix_fmt_score().
Function Documentation
av_read_image_line()
void av_read_image_line (uint16_t * dst, const uint8_t * data[4], const int linesize[4], const AVPixFmtDescriptor * desc, int x, int y, int c, int w, int read_pal_component)
Read a line from an image, and write the values of the pixel format component c to dst.
Parameters
data the array containing the pointers to the planes of the image
linesize the array containing the linesizes of the image
desc the pixel format descriptor for the image
x the horizontal coordinate of the first pixel to read
y the vertical coordinate of the first pixel to read
w the width of the line to read, that is the number of values to write to dst
read_pal_component if not zero and the format is a paletted format writes the values corresponding to the palette component c in data[1] to dst, rather than the palette indexes in data[0]. The behavior is undefined if the format is not paletted.
Definition at line 34 of file pixdesc.c.
Referenced by ff_check_pixfmt_descriptors(), and filter_frame().
av_write_image_line()
void av_write_image_line (const uint16_t * src, uint8_t * data[4], const int linesize[4], const AVPixFmtDescriptor * desc, int x, int y, int c, int w)
Write the values from src to the pixel format component c of an image line.
Parameters
src array containing the values to write
data the array containing the pointers to the planes of the image to write into. It is supposed to be zeroed.
linesize the array containing the linesizes of the image
desc the pixel format descriptor for the image
x the horizontal coordinate of the first pixel to write
y the vertical coordinate of the first pixel to write
w the width of the line to write, that is the number of values to write to the image line
Definition at line 82 of file pixdesc.c.
Referenced by ff_check_pixfmt_descriptors(), and filter_frame().
get_pix_fmt_internal()
static enum AVPixelFormat get_pix_fmt_internal (const char * name) static
Definition at line 2235 of file pixdesc.c.
Referenced by av_get_pix_fmt(), and av_pix_fmt_swap_endianness().
av_get_pix_fmt_name()
const char* av_get_pix_fmt_name (enum AVPixelFormat pix_fmt)
Return the short name for a pixel format, NULL in case pix_fmt is unknown.
See also
av_get_pix_fmt(), av_get_pix_fmt_string()
Examples:
demuxing_decoding.c, and scaling_video.c.
Definition at line 2248 of file pixdesc.c.
Referenced by add_video_device(), av_hwframe_ctx_init(), av_opt_get(), avcodec_open2(), avcodec_string(), avi_write_header(), caca_write_header(), choose_pix_fmts(), choose_pixel_fmt(), config_input_overlay(), config_output(), config_props(), create_filtergraph(), cuda_frames_init(), dc1394_read_common(), decode_frame_header(), decode_packet(), decode_video(), device_try_init(), dnxhd_decode_frame(), dshow_cycle_formats(), dvvideo_encode_init(), dxva2_init_pool(), fbdev_read_header(), fbdev_write_packet(), ff_hevc_decode_nal_sps(), ff_qsv_process_data(), ff_scale_image(), ff_tlog_link(), ff_yuv2rgb_get_func_ptr(), ff_yuv2rgb_init_tables_ppc(), get_cv_pixel_info(), h264_init_ps(), handle_p_frame_apng(), hwdownload_config_output(), hwupload_config_output(), init_output_stream_encode(), init_processing_chain(), init_video(), libkvazaar_encode(), libopenjpeg_encode_frame(), list_formats(), main(), mj2_create_image(), mov_get_rawvideo_codec_tag(), movie_push_frame(), nvenc_alloc_surface(), nvenc_register_frame(), opengl_compile_shaders(), opt_list(), palToRgbWrapper(), pick_format(), planarRgbToRgbWrapper(), print_link_prop(), reget_buffer_internal(), rgbToPlanarRgbWrapper(), rgbToRgbWrapper(), scale_vaapi_config_output(), scale_vaapi_filter_frame(), sdl2_write_header(), show_frame(), show_stream(), sws_init_context(), targa_encode_frame(), vaapi_build_decoder_config(), vaapi_device_init(), vaapi_encode_create_recon_frames(), vaapi_frames_init(), vdpau_frames_init(), vdpau_transfer_data_from(), vdpau_transfer_data_to(), video_get_buffer(), video_thread(), write_header(), xv_write_header(), yuv4_write_header(), and yuv4_write_packet().
av_get_pix_fmt()
enum AVPixelFormat av_get_pix_fmt (const char * name)
Return the pixel format corresponding to name.
If there is no pixel format with name name, then looks for a pixel format with the name corresponding to the native endian format of name. For example in a little-endian system, first looks for "gray16", then for "gray16le".
Finally if no pixel format has been found, returns AV_PIX_FMT_NONE.
Definition at line 2260 of file pixdesc.c.
Referenced by add_input_streams(), dc1394_read_common(), ff_check_pixfmt_descriptors(), ff_img_read_header(), ff_parse_pixel_format(), ffserver_parse_config_stream(), fileTest(), main(), new_video_stream(), nppscale_init(), rawvideo_read_header(), scale_vaapi_init(), set_string_pixel_fmt(), and v4l2_read_header().
av_get_bits_per_pixel()
int av_get_bits_per_pixel (const AVPixFmtDescriptor * pixdesc)
Return the number of bits per pixel used by the pixel format described by pixdesc.
Note that this is not the same as the number of bits per sample.
The returned number of bits refers to the number of bits actually used for storing the pixel information, that is padding bits are not counted.
Definition at line 2284 of file pixdesc.c.
Referenced by av_get_pix_fmt_string(), caca_write_header(), config_input(), config_output(), config_props(), decode_frame(), encode_frame(), ff_fill_line_with_color(), ffprobe_show_pixel_formats(), raw_decode(), raw_encode_init(), show_pix_fmts(), sws_init_context(), sws_setColorspaceDetails(), targa_encode_frame(), and xwd_encode_frame().
av_get_padded_bits_per_pixel()
int av_get_padded_bits_per_pixel (const AVPixFmtDescriptor * pixdesc)
Return the number of bits per pixel for the pixel format described by pixdesc, including any padding or unused bits.
Definition at line 2297 of file pixdesc.c.
Referenced by av_find_best_pix_fmt_of_2(), config_input(), config_output(), filter_frame(), lavfi_read_header(), main(), and request_frame().
av_get_pix_fmt_string()
char* av_get_pix_fmt_string (char * buf, int buf_size, enum AVPixelFormat pix_fmt)
Print in buf the string corresponding to the pixel format with number pix_fmt, or a header if pix_fmt is negative.
Parameters
buf the buffer where to write the string
buf_size the size of buf
pix_fmt the number of the pixel format to print the corresponding info string, or a negative value to print the corresponding header.
Definition at line 2317 of file pixdesc.c.
av_pix_fmt_desc_get()
const AVPixFmtDescriptor* av_pix_fmt_desc_get (enum AVPixelFormat pix_fmt)
Returns
a pixel format descriptor for provided pixel format or NULL if this pixel format is unknown.
Definition at line 2332 of file pixdesc.c.
Referenced by av_find_best_pix_fmt_of_2(), av_image_alloc(), av_image_copy(), av_image_copy_to_buffer(), av_image_fill_linesizes(), av_image_fill_pointers(), av_image_get_buffer_size(), av_image_get_linesize(), av_picture_crop(), av_picture_pad(), av_pix_fmt_count_planes(), av_pix_fmt_get_chroma_sub_sample(), av_pix_fmt_swap_endianness(), avcodec_align_dimensions(), avcodec_align_dimensions2(), avcodec_get_chroma_sub_sample(), avcodec_open2(), avcodec_string(), caca_write_header(), check_image_pointers(), choose_pixel_fmt(), config_input(), config_input_main(), config_input_overlay(), config_input_ref(), config_inputx(), config_inputy(), config_out_props(), config_output(), config_props(), config_props_output(), copy_picture_field(), create_all_formats(), create_filtergraph(), decode_frame(), decode_slice(), doTest(), draw_horiz_band(), encode_frame(), encode_init(), encode_slice(), ff_choose_chroma_location(), ff_color_frame(), ff_draw_horiz_band(), ff_draw_init(), ff_draw_supported_pixel_formats(), ff_fill_line_with_color(), ff_get_format(), ff_get_unscaled_swscale(), ff_h264_draw_horiz_band(), ff_hevc_output_frame(), ff_llviddsp_init_x86(), ff_merge_formats(), ff_mjpeg_decode_frame(), ff_mjpeg_decode_sof(), ff_opencl_deshake_process_inout_buf(), ff_parse_pixel_format(), ff_pnm_decode_header(), ff_sws_alphablendaway(), ff_sws_init_output_funcs(), ff_video_frame_pool_get(), ff_video_frame_pool_init(), ffm2_read_header(), ffm_read_header(), fill_picture_parameters(), filter_frame(), frame_end(), geq_config_props(), get_aspect_ratio(), get_bit_depth(), get_deinterleaved_format(), get_format(), get_pix_fmt_depth(), get_pix_fmt_score(), get_video_buffer(), hScale16To15_c(), hScale16To19_c(), init(), init_image(), init_output_stream_encode(), is16BPS(), is_hwaccel_pix_fmt(), isALPHA(), isBE(), isNBPS(), isPackedRGB(), isPlanar(), isPlanarRGB(), isPlanarYUV(), isRGB(), isYUV(), lavfi_read_header(), libopenjpeg_copy_to_packed16(), libopenjpeg_copyto16(), libopenjpeg_decode_frame(), libopenjpeg_ispacked(), libopenjpeg_matches_pix_fmt(), libx265_encode_frame(), libx265_encode_init(), main(), map_pixel_format(), mj2_create_image(), mxf_write_header(), opengl_draw(), opengl_fill_color_map(), opengl_init_context(), output_frame(), pick_format(), pix_fmt_match(), planarCopyWrapper(), planarRgb16ToRgb16Wrapper(), pnm_encode_frame(), print_digraph(), qsv_decode_init(), qsv_init_pool(), query_formats(), raw_decode(), raw_encode_init(), raw_init_decoder(), request_frame(), Rgb16ToPlanarRgb16Wrapper(), rgb48Toxyz12(), rgbToRgbWrapper(), selfTest(), shuffleplanes_config_input(), smv_img_pnt(), smvjpeg_decode_frame(), sws_init_context(), sws_setColorspaceDetails(), swscale(), targa_encode_frame(), tiff_unpack_strip(), usePal(), utvideo_encode_init(), vaapi_build_decoder_config(), validate_avframe_allocation(), vc2_encode_init(), verify_md5(), video_frame_cksum(), video_get_buffer(), write_header(), write_packet(), xwd_encode_frame(), xyz12Torgb48(), yuv2gbrp16_full_X_c(), and yuv2gbrp_full_X_c().
av_pix_fmt_desc_next()
const AVPixFmtDescriptor* av_pix_fmt_desc_next (const AVPixFmtDescriptor * prev)
Iterate over all pixel format descriptors known to libavutil.
Parameters
prev previous descriptor. NULL to get the first descriptor.
Returns
next descriptor or NULL after the last descriptor
Definition at line 2339 of file pixdesc.c.
Referenced by ff_all_formats(), ffprobe_show_pixel_formats(), hwdownload_query_formats(), init(), query_formats(), and show_pix_fmts().
av_pix_fmt_desc_get_id()
enum AVPixelFormat av_pix_fmt_desc_get_id (const AVPixFmtDescriptor * desc)
Returns
an AVPixelFormat id described by desc, or AV_PIX_FMT_NONE if desc is not a valid pointer to a pixel format descriptor.
Definition at line 2351 of file pixdesc.c.
Referenced by ff_all_formats(), hwdownload_query_formats(), init(), query_formats(), and show_pix_fmts().
av_pix_fmt_get_chroma_sub_sample()
int av_pix_fmt_get_chroma_sub_sample (enum AVPixelFormat pix_fmt, int * h_shift, int * v_shift)
Utility function to access log2_chroma_w log2_chroma_h from the pixel format AVPixFmtDescriptor.
See av_get_chroma_sub_sample() for a function that asserts a valid pixel format instead of returning an error code. Its recommended that you use avcodec_get_chroma_sub_sample unless you do check the return code!
Parameters
[in] pix_fmt the pixel format
[out] h_shift store log2_chroma_w (horizontal/width shift)
[out] v_shift store log2_chroma_h (vertical/height shift)
Returns
0 on success, AVERROR(ENOSYS) on invalid or unknown pixel format
Definition at line 2360 of file pixdesc.c.
Referenced by alloc_picture(), amv_encode_picture(), cuda_frames_init(), decode_frame(), decode_init(), encode_frame(), encode_init(), ff_mjpeg_init_hvsample(), ff_mpv_frame_start(), get_vpx_chroma_subsampling(), gray_frame(), h264_slice_header_init(), init_stage(), load_input_picture(), mjpeg_decode_scan(), sws_init_context(), and yuv4_write_packet().
av_pix_fmt_count_planes()
int av_pix_fmt_count_planes (enum AVPixelFormat pix_fmt)
Returns
number of planes in pix_fmt, a negative AVERROR if pix_fmt is not a valid pixel format.
Definition at line 2372 of file pixdesc.c.
Referenced by alloc_buffers(), cfhd_decode(), config_input(), config_inputx(), config_output(), config_props(), config_props_output(), ff_mjpeg_decode_frame(), frame_copy_video(), get_deinterleaved_format(), init(), magy_decode_frame(), query_formats(), shuffleplanes_config_input(), and validate_avframe_allocation().
ff_check_pixfmt_descriptors()
void ff_check_pixfmt_descriptors (void)
Definition at line 2387 of file pixdesc.c.
Referenced by avpriv_mirror(), and main().
av_pix_fmt_swap_endianness()
enum AVPixelFormat av_pix_fmt_swap_endianness (enum AVPixelFormat pix_fmt)
Utility function to swap the endianness of a pixel format.
Parameters
[in] pix_fmt the pixel format
Returns
pixel format with swapped endianness if it exists, otherwise AV_PIX_FMT_NONE
Definition at line 2429 of file pixdesc.c.
Referenced by sws_init_context().
get_color_type()
static int get_color_type (const AVPixFmtDescriptor * desc) static
Definition at line 2458 of file pixdesc.c.
Referenced by get_pix_fmt_score(), and main().
get_pix_fmt_depth()
static int get_pix_fmt_depth (int * min, int * max, enum AVPixelFormat pix_fmt) static
Definition at line 2480 of file pixdesc.c.
Referenced by get_pix_fmt_score().
get_pix_fmt_score()
static int get_pix_fmt_score (enum AVPixelFormat dst_pix_fmt, enum AVPixelFormat src_pix_fmt, unsigned * lossp, unsigned consider) static
Definition at line 2498 of file pixdesc.c.
Referenced by av_find_best_pix_fmt_of_2(), and av_get_pix_fmt_loss().
av_get_pix_fmt_loss()
int av_get_pix_fmt_loss (enum AVPixelFormat dst_pix_fmt, enum AVPixelFormat src_pix_fmt, int has_alpha)
Compute what kind of losses will occur when converting from one specific pixel format to another.
When converting from one pixel format to another, information loss may occur. For example, when converting from RGB24 to GRAY, the color information will be lost. Similarly, other losses occur when converting from some formats to other formats. These losses can involve loss of chroma, but also loss of resolution, loss of color depth, loss due to the color space conversion, loss of the alpha bits or loss due to color quantization. av_get_fix_fmt_loss() informs you about the various types of losses which will occur when converting from one pixel format to another.
Parameters
[in] dst_pix_fmt destination pixel format
[in] src_pix_fmt source pixel format
[in] has_alpha Whether the source pixel format alpha channel is used.
Returns
Combination of flags informing you what kind of losses will occur (maximum loss for an invalid dst_pix_fmt).
Definition at line 2603 of file pixdesc.c.
Referenced by av_find_best_pix_fmt_of_2(), and avcodec_get_pix_fmt_loss().
av_find_best_pix_fmt_of_2()
enum AVPixelFormat av_find_best_pix_fmt_of_2 (enum AVPixelFormat dst_pix_fmt1, enum AVPixelFormat dst_pix_fmt2, enum AVPixelFormat src_pix_fmt, int has_alpha, int * loss_ptr)
Compute what kind of losses will occur when converting from one specific pixel format to another.
When converting from one pixel format to another, information loss may occur. For example, when converting from RGB24 to GRAY, the color information will be lost. Similarly, other losses occur when converting from some formats to other formats. These losses can involve loss of chroma, but also loss of resolution, loss of color depth, loss due to the color space conversion, loss of the alpha bits or loss due to color quantization. av_get_fix_fmt_loss() informs you about the various types of losses which will occur when converting from one pixel format to another.
Parameters
[in] dst_pix_fmt destination pixel format
[in] src_pix_fmt source pixel format
[in] has_alpha Whether the source pixel format alpha channel is used.
Returns
Combination of flags informing you what kind of losses will occur (maximum loss for an invalid dst_pix_fmt).
Definition at line 2614 of file pixdesc.c.
Referenced by avcodec_find_best_pix_fmt_of_2(), and pick_format().
av_color_range_name()
const char* av_color_range_name (enum AVColorRange range)
Returns
the name for provided color range or NULL if unknown.
Definition at line 2645 of file pixdesc.c.
Referenced by avcodec_string(), create_filtergraph(), get_cv_pixel_info(), and show_stream().
av_color_primaries_name()
const char* av_color_primaries_name (enum AVColorPrimaries primaries)
Returns
the name for provided color primaries or NULL if unknown.
Definition at line 2651 of file pixdesc.c.
Referenced by avcodec_string(), create_filtergraph(), get_cv_color_primaries(), and show_stream().
av_color_transfer_name()
const char* av_color_transfer_name (enum AVColorTransferCharacteristic transfer)
Returns
the name for provided color transfer or NULL if unknown.
Definition at line 2657 of file pixdesc.c.
Referenced by avcodec_string(), create_filtergraph(), get_cv_transfer_function(), and show_stream().
av_color_space_name()
const char* av_color_space_name (enum AVColorSpace space)
Returns
the name for provided color space or NULL if unknown.
Definition at line 2663 of file pixdesc.c.
Referenced by avcodec_string(), create_filtergraph(), and get_cv_ycbcr_matrix().
av_chroma_location_name()
const char* av_chroma_location_name (enum AVChromaLocation location)
Returns
the name for provided chroma location or NULL if unknown.
Definition at line 2669 of file pixdesc.c.
Referenced by avcodec_string(), and show_stream().
Variable Documentation
av_pix_fmt_descriptors
FF_DISABLE_DEPRECATION_WARNINGS const AVPixFmtDescriptor av_pix_fmt_descriptors[AV_PIX_FMT_NB] static
Definition at line 133 of file pixdesc.c.
Referenced by av_pix_fmt_desc_get_id().
color_range_names
FF_ENABLE_DEPRECATION_WARNINGS const char* color_range_names[] static
Initial value:
= {
    [AVCOL_RANGE_UNSPECIFIED] = "unknown",
    [AVCOL_RANGE_MPEG] = "tv",
    [AVCOL_RANGE_JPEG] = "pc",
}
Definition at line 2166 of file pixdesc.c.
Referenced by av_color_range_name().
color_primaries_names
const char* color_primaries_names[AVCOL_PRI_NB] static
Initial value:
= {
    [AVCOL_PRI_RESERVED0] = "reserved",
    [AVCOL_PRI_BT709] = "bt709",
    [AVCOL_PRI_UNSPECIFIED] = "unknown",
    [AVCOL_PRI_RESERVED] = "reserved",
    [AVCOL_PRI_BT470M] = "bt470m",
    [AVCOL_PRI_BT470BG] = "bt470bg",
    [AVCOL_PRI_SMPTE170M] = "smpte170m",
    [AVCOL_PRI_SMPTE240M] = "smpte240m",
    [AVCOL_PRI_FILM] = "film",
    [AVCOL_PRI_BT2020] = "bt2020",
    [AVCOL_PRI_SMPTE428] = "smpte428",
    [AVCOL_PRI_SMPTE431] = "smpte431",
    [AVCOL_PRI_SMPTE432] = "smpte432",
}
Definition at line 2172 of file pixdesc.c.
Referenced by av_color_primaries_name().
color_transfer_names
const char* color_transfer_names[] static
Initial value:
= {
    [AVCOL_TRC_RESERVED0] = "reserved",
    [AVCOL_TRC_BT709] = "bt709",
    [AVCOL_TRC_UNSPECIFIED] = "unknown",
    [AVCOL_TRC_RESERVED] = "reserved",
    [AVCOL_TRC_GAMMA22] = "bt470m",
    [AVCOL_TRC_GAMMA28] = "bt470bg",
    [AVCOL_TRC_SMPTE170M] = "smpte170m",
    [AVCOL_TRC_SMPTE240M] = "smpte240m",
    [AVCOL_TRC_LINEAR] = "linear",
    [AVCOL_TRC_LOG] = "log100",
    [AVCOL_TRC_LOG_SQRT] = "log316",
    [AVCOL_TRC_IEC61966_2_4] = "iec61966-2-4",
    [AVCOL_TRC_BT1361_ECG] = "bt1361e",
    [AVCOL_TRC_IEC61966_2_1] = "iec61966-2-1",
    [AVCOL_TRC_BT2020_10] = "bt2020-10",
    [AVCOL_TRC_BT2020_12] = "bt2020-12",
    [AVCOL_TRC_SMPTE2084] = "smpte2084",
    [AVCOL_TRC_SMPTE428] = "smpte428",
    [AVCOL_TRC_ARIB_STD_B67] = "arib-std-b67",
}
Definition at line 2188 of file pixdesc.c.
Referenced by av_color_transfer_name().
color_space_names
const char* color_space_names[] static
Initial value:
= {
    [AVCOL_SPC_RGB] = "gbr",
    [AVCOL_SPC_BT709] = "bt709",
    [AVCOL_SPC_UNSPECIFIED] = "unknown",
    [AVCOL_SPC_RESERVED] = "reserved",
    [AVCOL_SPC_FCC] = "fcc",
    [AVCOL_SPC_BT470BG] = "bt470bg",
    [AVCOL_SPC_SMPTE170M] = "smpte170m",
    [AVCOL_SPC_SMPTE240M] = "smpte240m",
    [AVCOL_SPC_YCOCG] = "ycgco",
    [AVCOL_SPC_BT2020_NCL] = "bt2020nc",
    [AVCOL_SPC_BT2020_CL] = "bt2020c",
    [AVCOL_SPC_SMPTE2085] = "smpte2085",
}
Definition at line 2210 of file pixdesc.c.
Referenced by av_color_space_name().
chroma_location_names
const char* chroma_location_names[] static
Initial value:
= {
    [AVCHROMA_LOC_UNSPECIFIED] = "unspecified",
    [AVCHROMA_LOC_LEFT] = "left",
    [AVCHROMA_LOC_CENTER] = "center",
    [AVCHROMA_LOC_TOPLEFT] = "topleft",
    [AVCHROMA_LOC_TOP] = "top",
    [AVCHROMA_LOC_BOTTOMLEFT] = "bottomleft",
    [AVCHROMA_LOC_BOTTOM] = "bottom",
}
Definition at line 2225 of file pixdesc.c.
Referenced by av_chroma_location_name().