FFmpeg: libavutil/x86/pixelutils_init.c File Reference
pixelutils_init.c File Reference
#include "config.h"
#include "pixelutils.h"
#include "cpu.h"
Functions
int ff_pixelutils_sad_8x8_mmx (const uint8_t *src1, ptrdiff_t stride1, const uint8_t *src2, ptrdiff_t stride2)
int ff_pixelutils_sad_8x8_mmxext (const uint8_t *src1, ptrdiff_t stride1, const uint8_t *src2, ptrdiff_t stride2)
int ff_pixelutils_sad_16x16_mmxext (const uint8_t *src1, ptrdiff_t stride1, const uint8_t *src2, ptrdiff_t stride2)
int ff_pixelutils_sad_16x16_sse2 (const uint8_t *src1, ptrdiff_t stride1, const uint8_t *src2, ptrdiff_t stride2)
int ff_pixelutils_sad_a_16x16_sse2 (const uint8_t *src1, ptrdiff_t stride1, const uint8_t *src2, ptrdiff_t stride2)
int ff_pixelutils_sad_u_16x16_sse2 (const uint8_t *src1, ptrdiff_t stride1, const uint8_t *src2, ptrdiff_t stride2)
void ff_pixelutils_sad_init_x86 (av_pixelutils_sad_fn *sad, int aligned)
Function Documentation
ff_pixelutils_sad_8x8_mmx()
int ff_pixelutils_sad_8x8_mmx (const uint8_t * src1, ptrdiff_t stride1, const uint8_t * src2, ptrdiff_t stride2)
Referenced by ff_pixelutils_sad_init_x86().
ff_pixelutils_sad_8x8_mmxext()
int ff_pixelutils_sad_8x8_mmxext (const uint8_t * src1, ptrdiff_t stride1, const uint8_t * src2, ptrdiff_t stride2)
Referenced by ff_pixelutils_sad_init_x86().
ff_pixelutils_sad_16x16_mmxext()
int ff_pixelutils_sad_16x16_mmxext (const uint8_t * src1, ptrdiff_t stride1, const uint8_t * src2, ptrdiff_t stride2)
Referenced by ff_pixelutils_sad_init_x86().
ff_pixelutils_sad_16x16_sse2()
int ff_pixelutils_sad_16x16_sse2 (const uint8_t * src1, ptrdiff_t stride1, const uint8_t * src2, ptrdiff_t stride2)
Referenced by ff_pixelutils_sad_init_x86().
ff_pixelutils_sad_a_16x16_sse2()
int ff_pixelutils_sad_a_16x16_sse2 (const uint8_t * src1, ptrdiff_t stride1, const uint8_t * src2, ptrdiff_t stride2)
Referenced by ff_pixelutils_sad_init_x86().
ff_pixelutils_sad_u_16x16_sse2()
int ff_pixelutils_sad_u_16x16_sse2 (const uint8_t * src1, ptrdiff_t stride1, const uint8_t * src2, ptrdiff_t stride2)
Referenced by ff_pixelutils_sad_init_x86().
ff_pixelutils_sad_init_x86()
void ff_pixelutils_sad_init_x86 (av_pixelutils_sad_fn * sad, int aligned)
Definition at line 38 of file pixelutils_init.c.
Referenced by av_pixelutils_get_sad_fn().