FFmpeg: libavcodec/pixlet.c File Reference
pixlet.c File Reference
#include <stdint.h>
#include "libavutil/imgutils.h"
#include "libavutil/intmath.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "bytestream.h"
#include "get_bits.h"
#include "unary.h"
#include "internal.h"
#include "thread.h"
Data Structures
struct SubBand
struct PixletContext
Macros
#define NB_LEVELS 4
#define H 0
#define V 1
#define SQR(a) ((a) * (a))
Functions
static int init_decoder (AVCodecContext *avctx)
static void free_buffers (AVCodecContext *avctx)
static av_cold int pixlet_close (AVCodecContext *avctx)
static av_cold int pixlet_init (AVCodecContext *avctx)
static int read_low_coeffs (AVCodecContext *avctx, int16_t *dst, int size, int width, ptrdiff_t stride)
static int read_high_coeffs (AVCodecContext *avctx, uint8_t *src, int16_t *dst, int size, int c, int a, int d, int width, ptrdiff_t stride)
static int read_highpass (AVCodecContext *avctx, uint8_t *ptr, int plane, AVFrame *frame)
static void lowpass_prediction (int16_t *dst, int16_t *pred, int width, int height, ptrdiff_t stride)
static void filter (int16_t *dest, int16_t *tmp, unsigned size, float SCALE)
static void reconstruction (AVCodecContext *avctx, int16_t *dest, unsigned width, unsigned height, ptrdiff_t stride, int nb_levels, float *scaling_H, float *scaling_V)
static void postprocess_luma (AVFrame *frame, int w, int h, int depth)
static void postprocess_chroma (AVFrame *frame, int w, int h, int depth)
static int decode_plane (AVCodecContext *avctx, int plane, AVPacket *avpkt, AVFrame *frame)
static int pixlet_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
Variables
AVCodec ff_pixlet_decoder
Macro Definition Documentation
NB_LEVELS
#define NB_LEVELS 4
Definition at line 35 of file pixlet.c.
Referenced by decode_plane(), init_decoder(), and pixlet_decode_frame().
H
#define H 0
Definition at line 37 of file pixlet.c.
Referenced by check_loopfilter(), decode_plane(), filter_color(), filter_color2(), filter_frame(), filter_mono(), filter_plane_cols(), filter_plane_rows(), for(), idct(), and loop_filter().
V
#define V 1
Definition at line 38 of file pixlet.c.
Referenced by decode_plane().
SQR
#define SQR (a) ((a) * (a))
Definition at line 452 of file pixlet.c.
Referenced by postprocess_luma().
Function Documentation
init_decoder()
static int init_decoder (AVCodecContext * avctx) static
Definition at line 62 of file pixlet.c.
Referenced by pixlet_decode_frame().
free_buffers()
static void free_buffers (AVCodecContext * avctx) static
Definition at line 97 of file pixlet.c.
Referenced by pixlet_close(), and pixlet_decode_frame().
pixlet_close()
static av_cold int pixlet_close (AVCodecContext * avctx) static
Definition at line 106 of file pixlet.c.
pixlet_init()
static av_cold int pixlet_init (AVCodecContext * avctx) static
Definition at line 115 of file pixlet.c.
read_low_coeffs()
static int read_low_coeffs (AVCodecContext * avctx, int16_t * dst, int size, int width, ptrdiff_t stride) static
Definition at line 122 of file pixlet.c.
Referenced by decode_plane().
read_high_coeffs()
static int read_high_coeffs (AVCodecContext * avctx, uint8_t * src, int16_t * dst, int size, int c, int a, int d, int width, ptrdiff_t stride) static
Definition at line 196 of file pixlet.c.
Referenced by read_highpass().
read_highpass()
static int read_highpass (AVCodecContext * avctx, uint8_t * ptr, int plane, AVFrame * frame) static
Definition at line 309 of file pixlet.c.
Referenced by decode_plane().
lowpass_prediction()
static void lowpass_prediction (int16_t * dst, int16_t * pred, int width, int height, ptrdiff_t stride) static
Definition at line 344 of file pixlet.c.
Referenced by decode_plane().
filter()
static void filter (int16_t * dest, int16_t * tmp, unsigned size, float SCALE) static
Definition at line 363 of file pixlet.c.
Referenced by reconstruction().
reconstruction()
static void reconstruction (AVCodecContext * avctx, int16_t * dest, unsigned width, unsigned height, ptrdiff_t stride, int nb_levels, float * scaling_H, float * scaling_V) static
Definition at line 408 of file pixlet.c.
Referenced by decode_plane().
postprocess_luma()
static void postprocess_luma (AVFrame * frame, int w, int h, int depth) static
Definition at line 454 of file pixlet.c.
Referenced by pixlet_decode_frame().
postprocess_chroma()
static void postprocess_chroma (AVFrame * frame, int w, int h, int depth) static
Definition at line 471 of file pixlet.c.
Referenced by pixlet_decode_frame().
decode_plane()
static int decode_plane (AVCodecContext * avctx, int plane, AVPacket * avpkt, AVFrame * frame) static
Definition at line 495 of file pixlet.c.
Referenced by pixlet_decode_frame().
pixlet_decode_frame()
static int pixlet_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 562 of file pixlet.c.
Variable Documentation
ff_pixlet_decoder
AVCodec ff_pixlet_decoder
Initial value:
= {
    .name             = "pixlet",
    .long_name        = NULL_IF_CONFIG_SMALL("Apple Pixlet"),
    .type             = AVMEDIA_TYPE_VIDEO,
    .id               = AV_CODEC_ID_PIXLET,
    .init             = pixlet_init,
    .init_thread_copy = ONLY_IF_THREADS_ENABLED(pixlet_init_thread_copy),
    .close            = pixlet_close,
    .decode           = pixlet_decode_frame,
    .priv_data_size   = sizeof(PixletContext),
    .capabilities     = AV_CODEC_CAP_DR1 |
                        AV_CODEC_CAP_FRAME_THREADS,
    .caps_internal    = FF_CODEC_CAP_INIT_THREADSAFE |
                        FF_CODEC_CAP_INIT_CLEANUP,
}
Definition at line 663 of file pixlet.c.