FFmpeg: libavcodec/png.c File Reference
png.c File Reference
#include "avcodec.h"
#include "png.h"
Functions
void * ff_png_zalloc (void *opaque, unsigned int items, unsigned int size)
void ff_png_zfree (void *opaque, void *ptr)
int ff_png_get_nb_channels (int color_type)
int ff_png_pass_row_size (int pass, int bits_per_pixel, int width)
Variables
const uint8_t ff_png_pass_ymask [NB_PASSES]
static const uint8_t ff_png_pass_xmin [NB_PASSES]
static const uint8_t ff_png_pass_xshift [NB_PASSES]
Function Documentation
ff_png_zalloc()
void* ff_png_zalloc (void * opaque, unsigned int items, unsigned int size)
Definition at line 39 of file png.c.
Referenced by decode_frame_common(), decode_zbuf(), and png_enc_init().
ff_png_zfree()
void ff_png_zfree (void * opaque, void * ptr)
Definition at line 44 of file png.c.
Referenced by decode_frame_common(), decode_zbuf(), and png_enc_init().
ff_png_get_nb_channels()
int ff_png_get_nb_channels (int color_type)
Definition at line 49 of file png.c.
Referenced by decode_idat_chunk(), and png_enc_init().
ff_png_pass_row_size()
int ff_png_pass_row_size (int pass, int bits_per_pixel, int width)
Definition at line 62 of file png.c.
Referenced by decode_idat_chunk(), encode_frame(), and png_handle_row().
Variable Documentation
ff_png_pass_ymask
const uint8_t ff_png_pass_ymask[NB_PASSES]
Initial value:
= {
    0x80, 0x80, 0x08, 0x88, 0x22, 0xaa, 0x55,
}
Definition at line 25 of file png.c.
Referenced by encode_frame(), and png_handle_row().
ff_png_pass_xmin
const uint8_t ff_png_pass_xmin[NB_PASSES] static
Initial value:
= {
    0, 4, 0, 2, 0, 1, 0
}
Definition at line 30 of file png.c.
Referenced by ff_png_pass_row_size().
ff_png_pass_xshift
const uint8_t ff_png_pass_xshift[NB_PASSES] static
Initial value:
= {
    3, 3, 2, 2, 1, 1, 0
}
Definition at line 35 of file png.c.
Referenced by ff_png_pass_row_size().