FFmpeg: libavcodec/pngdec.c File Reference
pngdec.c File Reference
#include "libavutil/avassert.h"
#include "libavutil/bprint.h"
#include "libavutil/imgutils.h"
#include "libavutil/stereo3d.h"
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
#include "apng.h"
#include "png.h"
#include "pngdsp.h"
#include "thread.h"
#include <zlib.h>
Data Structures
struct PNGDecContext
Macros
#define UNROLL1(bpp, op)
#define UNROLL_FILTER(op)
#define OP_SUB(x, s, l) ((x) + (s))
#define OP_AVG(x, s, l) (((((x) + (l)) >> 1) + (s)) & 0xff)
#define YUV2RGB(NAME, TYPE)
#define FAST_DIV255(x) ((((x) + 128) * 257) >> 16)
Functions
static void png_put_interlaced_row (uint8_t *dst, int width, int bits_per_pixel, int pass, int color_type, const uint8_t *src)
void ff_add_png_paeth_prediction (uint8_t *dst, uint8_t *src, uint8_t *top, int w, int bpp)
static void png_filter_row (PNGDSPContext *dsp, uint8_t *dst, int filter_type, uint8_t *src, uint8_t *last, int size, int bpp)
static void png_handle_row (PNGDecContext *s)
static int png_decode_idat (PNGDecContext *s, int length)
static int decode_zbuf (AVBPrint *bp, const uint8_t *data, const uint8_t *data_end)
static uint8_t * iso88591_to_utf8 (const uint8_t *in, size_t size_in)
static int decode_text_chunk (PNGDecContext *s, uint32_t length, int compressed, AVDictionary **dict)
static int decode_ihdr_chunk (AVCodecContext *avctx, PNGDecContext *s, uint32_t length)
static int decode_phys_chunk (AVCodecContext *avctx, PNGDecContext *s)
static int decode_idat_chunk (AVCodecContext *avctx, PNGDecContext *s, uint32_t length, AVFrame *p)
static int decode_plte_chunk (AVCodecContext *avctx, PNGDecContext *s, uint32_t length)
static int decode_trns_chunk (AVCodecContext *avctx, PNGDecContext *s, uint32_t length)
static void handle_small_bpp (PNGDecContext *s, AVFrame *p)
static int decode_fctl_chunk (AVCodecContext *avctx, PNGDecContext *s, uint32_t length)
static void handle_p_frame_png (PNGDecContext *s, AVFrame *p)
static int handle_p_frame_apng (AVCodecContext *avctx, PNGDecContext *s, AVFrame *p)
static int decode_frame_common (AVCodecContext *avctx, PNGDecContext *s, AVFrame *p, AVPacket *avpkt)
static av_cold int png_dec_init (AVCodecContext *avctx)
static av_cold int png_dec_end (AVCodecContext *avctx)
Variables
static const uint8_t png_pass_mask [NB_PASSES]
static const uint8_t png_pass_dsp_ymask [NB_PASSES]
static const uint8_t png_pass_dsp_mask [NB_PASSES]
Macro Definition Documentation
UNROLL1
#define UNROLL1 (bpp, op)
Value:
{                                                                         \
        r = dst[0];                                                           \
        if (bpp >= 2)                                                         \
            g = dst[1];                                                       \
        if (bpp >= 3)                                                         \
            b = dst[2];                                                       \
        if (bpp >= 4)                                                         \
            a = dst[3];                                                       \
        for (; i <= size - bpp; i += bpp) {                                   \
            dst[i + 0] = r = op(r, src[i + 0], last[i + 0]);                  \
            if (bpp == 1)                                                     \
                continue;                                                     \
            dst[i + 1] = g = op(g, src[i + 1], last[i + 1]);                  \
            if (bpp == 2)                                                     \
                continue;                                                     \
            dst[i + 2] = b = op(b, src[i + 2], last[i + 2]);                  \
            if (bpp == 3)                                                     \
                continue;                                                     \
            dst[i + 3] = a = op(a, src[i + 3], last[i + 3]);                  \
        }                                                                     \
    }
Definition at line 201 of file pngdec.c.
UNROLL_FILTER
#define UNROLL_FILTER (op)
Value:
if (bpp == 1) {                                                           \
        UNROLL1(1, op)                                                        \
    } else if (bpp == 2) {                                                    \
        UNROLL1(2, op)                                                        \
    } else if (bpp == 3) {                                                    \
        UNROLL1(3, op)                                                        \
    } else if (bpp == 4) {                                                    \
        UNROLL1(4, op)                                                        \
    }                                                                         \
    for (; i < size; i++) {                                                   \
        dst[i] = op(dst[i - bpp], src[i], last[i]);                           \
    }
Definition at line 224 of file pngdec.c.
Referenced by png_filter_row().
OP_SUB
#define OP_SUB (x, s, l) ((x) + (s))
Referenced by png_filter_row().
OP_AVG
#define OP_AVG (x, s, l) (((((x) + (l)) >> 1) + (s)) & 0xff)
Referenced by png_filter_row().
YUV2RGB
#define YUV2RGB (NAME, TYPE)
Value:
static void deloco_ ## NAME(TYPE *dst, int size, int alpha) \
{ \
    int i; \
    for (i = 0; i < size; i += 3 + alpha) { \
        int g = dst [i + 1]; \
        dst[i + 0] += g; \
        dst[i + 2] += g; \
    } \
}
Definition at line 296 of file pngdec.c.
FAST_DIV255
#define FAST_DIV255 (x) ((((x) + 128) * 257) >> 16)
Definition at line 972 of file pngdec.c.
Referenced by handle_p_frame_apng().
Function Documentation
png_put_interlaced_row()
static void png_put_interlaced_row (uint8_t * dst, int width, int bits_per_pixel, int pass, int color_type, const uint8_t * src) static
Definition at line 103 of file pngdec.c.
Referenced by png_handle_row().
ff_add_png_paeth_prediction()
void ff_add_png_paeth_prediction (uint8_t * dst, uint8_t * src, uint8_t * top, int w, int bpp)
Definition at line 173 of file pngdec.c.
Referenced by ff_pngdsp_init(), and png_filter_row().
png_filter_row()
static void png_filter_row (PNGDSPContext * dsp, uint8_t * dst, int filter_type, uint8_t * src, uint8_t * last, int size, int bpp) static
Definition at line 239 of file pngdec.c.
Referenced by png_handle_row().
png_handle_row()
static void png_handle_row (PNGDecContext * s) static
Definition at line 311 of file pngdec.c.
Referenced by png_decode_idat().
png_decode_idat()
static int png_decode_idat (PNGDecContext * s, int length) static
Definition at line 392 of file pngdec.c.
Referenced by decode_idat_chunk().
decode_zbuf()
static int decode_zbuf (AVBPrint * bp, const uint8_t * data, const uint8_t * data_end) static
Definition at line 422 of file pngdec.c.
Referenced by decode_text_chunk().
iso88591_to_utf8()
static uint8_t* iso88591_to_utf8 (const uint8_t * in, size_t size_in) static
Definition at line 466 of file pngdec.c.
Referenced by decode_text_chunk().
decode_text_chunk()
static int decode_text_chunk (PNGDecContext * s, uint32_t length, int compressed, AVDictionary ** dict) static
Definition at line 490 of file pngdec.c.
Referenced by decode_frame_common().
decode_ihdr_chunk()
static int decode_ihdr_chunk (AVCodecContext * avctx, PNGDecContext * s, uint32_t length) static
Definition at line 538 of file pngdec.c.
Referenced by decode_frame_common().
decode_phys_chunk()
static int decode_phys_chunk (AVCodecContext * avctx, PNGDecContext * s) static
Definition at line 577 of file pngdec.c.
Referenced by decode_frame_common().
decode_idat_chunk()
static int decode_idat_chunk (AVCodecContext * avctx, PNGDecContext * s, uint32_t length, AVFrame * p) static
Definition at line 593 of file pngdec.c.
Referenced by decode_frame_common().
decode_plte_chunk()
static int decode_plte_chunk (AVCodecContext * avctx, PNGDecContext * s, uint32_t length) static
Definition at line 747 of file pngdec.c.
Referenced by decode_frame_common().
decode_trns_chunk()
static int decode_trns_chunk (AVCodecContext * avctx, PNGDecContext * s, uint32_t length) static
Definition at line 770 of file pngdec.c.
Referenced by decode_frame_common().
handle_small_bpp()
static void handle_small_bpp (PNGDecContext * s, AVFrame * p) static
Definition at line 807 of file pngdec.c.
Referenced by decode_frame_common().
decode_fctl_chunk()
static int decode_fctl_chunk (AVCodecContext * avctx, PNGDecContext * s, uint32_t length) static
Definition at line 880 of file pngdec.c.
Referenced by decode_frame_common().
handle_p_frame_png()
static void handle_p_frame_png (PNGDecContext * s, AVFrame * p) static
Definition at line 954 of file pngdec.c.
Referenced by decode_frame_common().
handle_p_frame_apng()
static int handle_p_frame_apng (AVCodecContext * avctx, PNGDecContext * s, AVFrame * p) static
Definition at line 974 of file pngdec.c.
Referenced by decode_frame_common().
decode_frame_common()
static int decode_frame_common (AVCodecContext * avctx, PNGDecContext * s, AVFrame * p, AVPacket * avpkt) static
Definition at line 1087 of file pngdec.c.
png_dec_init()
static av_cold int png_dec_init (AVCodecContext * avctx) static
Definition at line 1457 of file pngdec.c.
Referenced by png_dec_end().
png_dec_end()
static av_cold int png_dec_end (AVCodecContext * avctx) static
Definition at line 1482 of file pngdec.c.
Variable Documentation
png_pass_mask
const uint8_t png_pass_mask[NB_PASSES] static
Initial value:
= {
    0x01, 0x01, 0x11, 0x11, 0x55, 0x55, 0xff,
}
Definition at line 86 of file pngdec.c.
Referenced by png_put_interlaced_row().
png_pass_dsp_ymask
const uint8_t png_pass_dsp_ymask[NB_PASSES] static
Initial value:
= {
    0xff, 0xff, 0x0f, 0xff, 0x33, 0xff, 0x55,
}
Definition at line 91 of file pngdec.c.
Referenced by png_handle_row().
png_pass_dsp_mask
const uint8_t png_pass_dsp_mask[NB_PASSES] static
Initial value:
= {
    0xff, 0x0f, 0xff, 0x33, 0xff, 0x55, 0xff
}
Definition at line 96 of file pngdec.c.
Referenced by png_put_interlaced_row().