FFmpeg: libavcodec/x86/pngdsp_init.c File Reference
pngdsp_init.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/common.h"
#include "libavutil/x86/cpu.h"
#include "libavcodec/pngdsp.h"
Functions
void ff_add_png_paeth_prediction_mmxext (uint8_t *dst, uint8_t *src, uint8_t *top, int w, int bpp)
void ff_add_png_paeth_prediction_ssse3 (uint8_t *dst, uint8_t *src, uint8_t *top, int w, int bpp)
void ff_add_bytes_l2_mmx (uint8_t *dst, uint8_t *src1, uint8_t *src2, int w)
void ff_add_bytes_l2_sse2 (uint8_t *dst, uint8_t *src1, uint8_t *src2, int w)
av_cold void ff_pngdsp_init_x86 (PNGDSPContext *dsp)
Function Documentation
ff_add_png_paeth_prediction_mmxext()
void ff_add_png_paeth_prediction_mmxext (uint8_t * dst, uint8_t * src, uint8_t * top, int w, int bpp)
Referenced by ff_pngdsp_init_x86().
ff_add_png_paeth_prediction_ssse3()
void ff_add_png_paeth_prediction_ssse3 (uint8_t * dst, uint8_t * src, uint8_t * top, int w, int bpp)
Referenced by ff_pngdsp_init_x86().
ff_add_bytes_l2_mmx()
void ff_add_bytes_l2_mmx (uint8_t * dst, uint8_t * src1, uint8_t * src2, int w)
Referenced by ff_pngdsp_init_x86().
ff_add_bytes_l2_sse2()
void ff_add_bytes_l2_sse2 (uint8_t * dst, uint8_t * src1, uint8_t * src2, int w)
Referenced by ff_pngdsp_init_x86().
ff_pngdsp_init_x86()
av_cold void ff_pngdsp_init_x86 (PNGDSPContext * dsp)
Definition at line 36 of file pngdsp_init.c.
Referenced by ff_pngdsp_init().