FFmpeg: libavcodec/pngenc.c File Reference
pngenc.c File Reference
#include "avcodec.h"
#include "internal.h"
#include "bytestream.h"
#include "huffyuvencdsp.h"
#include "png.h"
#include "apng.h"
#include "libavutil/avassert.h"
#include "libavutil/crc.h"
#include "libavutil/libm.h"
#include "libavutil/opt.h"
#include "libavutil/color_utils.h"
#include "libavutil/stereo3d.h"
#include <zlib.h>
Data Structures
struct APNGFctlChunk
struct PNGEncContext
Macros
#define IOBUF_SIZE 4096
#define AV_WB32_PNG(buf, n) AV_WB32(buf, lrint((n) * 100000))
#define OFFSET(x) offsetof(PNGEncContext, x)
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Functions
static void png_get_interlaced_row (uint8_t *dst, int row_size, int bits_per_pixel, int pass, const uint8_t *src, int width)
static void sub_png_paeth_prediction (uint8_t *dst, uint8_t *src, uint8_t *top, int w, int bpp)
static void sub_left_prediction (PNGEncContext *c, uint8_t *dst, const uint8_t *src, int bpp, int size)
static void png_filter_row (PNGEncContext *c, uint8_t *dst, int filter_type, uint8_t *src, uint8_t *top, int size, int bpp)
static uint8_t * png_choose_filter (PNGEncContext *s, uint8_t *dst, uint8_t *src, uint8_t *top, int size, int bpp)
static void png_write_chunk (uint8_t **f, uint32_t tag, const uint8_t *buf, int length)
static void png_write_image_data (AVCodecContext *avctx, const uint8_t *buf, int length)
static int png_write_row (AVCodecContext *avctx, const uint8_t *data, int size)
static int png_get_chrm (enum AVColorPrimaries prim, uint8_t *buf)
static int png_get_gama (enum AVColorTransferCharacteristic trc, uint8_t *buf)
static int encode_headers (AVCodecContext *avctx, const AVFrame *pict)
static int encode_frame (AVCodecContext *avctx, const AVFrame *pict)
static int encode_png (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *pict, int *got_packet)
static int apng_do_inverse_blend (AVFrame *output, const AVFrame *input, APNGFctlChunk *fctl_chunk, uint8_t bpp)
static int apng_encode_frame (AVCodecContext *avctx, const AVFrame *pict, APNGFctlChunk *best_fctl_chunk, APNGFctlChunk *best_last_fctl_chunk)
static int encode_apng (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *pict, int *got_packet)
static av_cold int png_enc_init (AVCodecContext *avctx)
static av_cold int png_enc_close (AVCodecContext *avctx)
Variables
static const AVOption options []
static const AVClass pngenc_class
static const AVClass apngenc_class
AVCodec ff_png_encoder
AVCodec ff_apng_encoder
Macro Definition Documentation
IOBUF_SIZE
#define IOBUF_SIZE 4096
Definition at line 38 of file pngenc.c.
Referenced by encode_apng(), encode_frame(), encode_png(), and png_write_row().
AV_WB32_PNG
#define AV_WB32_PNG (buf, n) AV_WB32(buf, lrint((n) * 100000))
Definition at line 292 of file pngenc.c.
Referenced by png_get_chrm(), and png_get_gama().
OFFSET
#define OFFSET (x) offsetof(PNGEncContext, x)
Definition at line 1111 of file pngenc.c.
VE
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 1112 of file pngenc.c.
Function Documentation
png_get_interlaced_row()
static void png_get_interlaced_row (uint8_t * dst, int row_size, int bits_per_pixel, int pass, const uint8_t * src, int width) static
Definition at line 82 of file pngenc.c.
Referenced by encode_frame().
sub_png_paeth_prediction()
static void sub_png_paeth_prediction (uint8_t * dst, uint8_t * src, uint8_t * top, int w, int bpp) static
Definition at line 121 of file pngenc.c.
Referenced by png_filter_row().
sub_left_prediction()
static void sub_left_prediction (PNGEncContext * c, uint8_t * dst, const uint8_t * src, int bpp, int size) static
Definition at line 149 of file pngenc.c.
Referenced by png_filter_row().
png_filter_row()
static void png_filter_row (PNGEncContext * c, uint8_t * dst, int filter_type, uint8_t * src, uint8_t * top, int size, int bpp) static
Definition at line 165 of file pngenc.c.
Referenced by png_choose_filter().
png_choose_filter()
static uint8_t* png_choose_filter (PNGEncContext * s, uint8_t * dst, uint8_t * src, uint8_t * top, int size, int bpp) static
Definition at line 194 of file pngenc.c.
Referenced by encode_frame().
png_write_chunk()
static void png_write_chunk (uint8_t ** f, uint32_t tag, const uint8_t * buf, int length) static
Definition at line 224 of file pngenc.c.
Referenced by encode_apng(), encode_headers(), encode_png(), and png_write_image_data().
png_write_image_data()
static void png_write_image_data (AVCodecContext * avctx, const uint8_t * buf, int length) static
Definition at line 243 of file pngenc.c.
Referenced by encode_frame(), and png_write_row().
png_write_row()
static int png_write_row (AVCodecContext * avctx, const uint8_t * data, int size) static
Definition at line 271 of file pngenc.c.
Referenced by encode_frame().
png_get_chrm()
static int png_get_chrm (enum AVColorPrimaries prim, uint8_t * buf) static
Definition at line 293 of file pngenc.c.
Referenced by encode_headers().
png_get_gama()
static int png_get_gama (enum AVColorTransferCharacteristic trc, uint8_t * buf) static
Definition at line 335 of file pngenc.c.
Referenced by encode_headers().
encode_headers()
static int encode_headers (AVCodecContext * avctx, const AVFrame * pict) static
Definition at line 345 of file pngenc.c.
Referenced by encode_apng(), and encode_png().
encode_frame()
static int encode_frame (AVCodecContext * avctx, const AVFrame * pict) static
Definition at line 431 of file pngenc.c.
Referenced by apng_encode_frame(), and encode_png().
encode_png()
static int encode_png (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * pict, int * got_packet) static
Definition at line 524 of file pngenc.c.
apng_do_inverse_blend()
static int apng_do_inverse_blend (AVFrame * output, const AVFrame * input, APNGFctlChunk * fctl_chunk, uint8_t bpp) static
Definition at line 569 of file pngenc.c.
Referenced by apng_encode_frame().
apng_encode_frame()
static int apng_encode_frame (AVCodecContext * avctx, const AVFrame * pict, APNGFctlChunk * best_fctl_chunk, APNGFctlChunk * best_last_fctl_chunk) static
Definition at line 712 of file pngenc.c.
Referenced by encode_apng().
encode_apng()
static int encode_apng (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * pict, int * got_packet) static
Definition at line 841 of file pngenc.c.
png_enc_init()
static av_cold int png_enc_init (AVCodecContext * avctx) static
Definition at line 989 of file pngenc.c.
png_enc_close()
static av_cold int png_enc_close (AVCodecContext * avctx) static
Definition at line 1098 of file pngenc.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    {"dpi", "Set image resolution (in dots per inch)",  OFFSET(dpi), AV_OPT_TYPE_INT, {.i64 = 0}, 0, 0x10000, VE},
    {"dpm", "Set image resolution (in dots per meter)", OFFSET(dpm), AV_OPT_TYPE_INT, {.i64 = 0}, 0, 0x10000, VE},
    { "pred", "Prediction method", OFFSET(filter_type), AV_OPT_TYPE_INT, { .i64 = PNG_FILTER_VALUE_NONE }, PNG_FILTER_VALUE_NONE, PNG_FILTER_VALUE_MIXED, VE, "pred" },
        { "none",  NULL, 0, AV_OPT_TYPE_CONST, { .i64 = PNG_FILTER_VALUE_NONE },  INT_MIN, INT_MAX, VE, "pred" },
        { "sub",   NULL, 0, AV_OPT_TYPE_CONST, { .i64 = PNG_FILTER_VALUE_SUB },   INT_MIN, INT_MAX, VE, "pred" },
        { "up",    NULL, 0, AV_OPT_TYPE_CONST, { .i64 = PNG_FILTER_VALUE_UP },    INT_MIN, INT_MAX, VE, "pred" },
        { "avg",   NULL, 0, AV_OPT_TYPE_CONST, { .i64 = PNG_FILTER_VALUE_AVG },   INT_MIN, INT_MAX, VE, "pred" },
        { "paeth", NULL, 0, AV_OPT_TYPE_CONST, { .i64 = PNG_FILTER_VALUE_PAETH }, INT_MIN, INT_MAX, VE, "pred" },
        { "mixed", NULL, 0, AV_OPT_TYPE_CONST, { .i64 = PNG_FILTER_VALUE_MIXED }, INT_MIN, INT_MAX, VE, "pred" },
    { NULL},
}
Definition at line 1113 of file pngenc.c.
pngenc_class
const AVClass pngenc_class static
Initial value:
= {
    .class_name = "PNG encoder",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1126 of file pngenc.c.
apngenc_class
const AVClass apngenc_class static
Initial value:
= {
    .class_name = "APNG encoder",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1133 of file pngenc.c.
ff_png_encoder
AVCodec ff_png_encoder
Initial value:
= {
    .name           = "png",
    .long_name      = NULL_IF_CONFIG_SMALL("PNG (Portable Network Graphics) image"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_PNG,
    .priv_data_size = sizeof(PNGEncContext),
    .init           = png_enc_init,
    .close          = png_enc_close,
    .encode2        = encode_png,
    .capabilities   = AV_CODEC_CAP_FRAME_THREADS | AV_CODEC_CAP_INTRA_ONLY,
    .pix_fmts       = (const enum AVPixelFormat[]) {
        AV_PIX_FMT_RGB24, AV_PIX_FMT_RGBA,
        AV_PIX_FMT_RGB48BE, AV_PIX_FMT_RGBA64BE,
        AV_PIX_FMT_PAL8,
        AV_PIX_FMT_GRAY8, AV_PIX_FMT_GRAY8A,
        AV_PIX_FMT_GRAY16BE, AV_PIX_FMT_YA16BE,
        AV_PIX_FMT_MONOBLACK, AV_PIX_FMT_NONE
    },
    .priv_class     = &pngenc_class,
}
Definition at line 1140 of file pngenc.c.
ff_apng_encoder
AVCodec ff_apng_encoder
Initial value:
= {
    .name           = "apng",
    .long_name      = NULL_IF_CONFIG_SMALL("APNG (Animated Portable Network Graphics) image"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_APNG,
    .priv_data_size = sizeof(PNGEncContext),
    .init           = png_enc_init,
    .close          = png_enc_close,
    .encode2        = encode_apng,
    .capabilities   = CODEC_CAP_DELAY,
    .pix_fmts       = (const enum AVPixelFormat[]) {
        AV_PIX_FMT_RGB24, AV_PIX_FMT_RGBA,
        AV_PIX_FMT_RGB48BE, AV_PIX_FMT_RGBA64BE,
        AV_PIX_FMT_PAL8,
        AV_PIX_FMT_GRAY8, AV_PIX_FMT_GRAY8A,
        AV_PIX_FMT_GRAY16BE, AV_PIX_FMT_YA16BE,
        AV_PIX_FMT_MONOBLACK, AV_PIX_FMT_NONE
    },
    .priv_class     = &apngenc_class,
}
Definition at line 1161 of file pngenc.c.