FFmpeg: libavcodec/pnm.c File Reference
pnm.c File Reference
#include <stdlib.h>
#include <string.h>
#include "libavutil/imgutils.h"
#include "avcodec.h"
#include "pnm.h"
Functions
static int pnm_space (int c)
static void pnm_get (PNMContext *sc, char *str, int buf_size)
int ff_pnm_decode_header (AVCodecContext *avctx, PNMContext *const s)
Function Documentation
pnm_space()
static int pnm_space (int c) inline static
Definition at line 29 of file pnm.c.
Referenced by pnm_get().
pnm_get()
static void pnm_get (PNMContext * sc, char * str, int buf_size) static
Definition at line 34 of file pnm.c.
Referenced by ff_pnm_decode_header().
ff_pnm_decode_header()
int ff_pnm_decode_header (AVCodecContext * avctx, PNMContext *const s)
Definition at line 60 of file pnm.c.
Referenced by pnm_decode_frame(), and pnm_parse().