FFmpeg: libavcodec/ppc/blockdsp.c File Reference
blockdsp.c File Reference
#include "config.h"
#include <string.h>
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/mem.h"
#include "libavutil/ppc/cpu.h"
#include "libavutil/ppc/types_altivec.h"
#include "libavcodec/blockdsp.h"
Functions
static void clear_blocks_dcbz32_ppc (int16_t *blocks)
static void clear_blocks_dcbz128_ppc (int16_t *blocks)
static long check_dcbzl_effect (void)
av_cold void ff_blockdsp_init_ppc (BlockDSPContext *c)
Function Documentation
clear_blocks_dcbz32_ppc()
static void clear_blocks_dcbz32_ppc (int16_t * blocks) static
Definition at line 55 of file blockdsp.c.
Referenced by ff_blockdsp_init_ppc().
clear_blocks_dcbz128_ppc()
static void clear_blocks_dcbz128_ppc (int16_t * blocks) static
Definition at line 79 of file blockdsp.c.
Referenced by ff_blockdsp_init_ppc().
check_dcbzl_effect()
static long check_dcbzl_effect (void) static
Definition at line 102 of file blockdsp.c.
Referenced by ff_blockdsp_init_ppc().
ff_blockdsp_init_ppc()
av_cold void ff_blockdsp_init_ppc (BlockDSPContext * c)
Definition at line 146 of file blockdsp.c.
Referenced by ff_blockdsp_init().