FFmpeg: doc/print_options.c File Reference
print_options.c File Reference
#include <stddef.h>
#include <string.h>
#include <float.h>
#include "libavformat/avformat.h"
#include "libavformat/options_table.h"
#include "libavcodec/avcodec.h"
#include "libavcodec/options_table.h"
#include "libavutil/opt.h"
Macros
#define AVFORMAT_OS_SUPPORT_H
Functions
static void print_usage (void)
static void print_option (const AVOption *opts, const AVOption *o, int per_stream)
static void show_opts (const AVOption *opts, int per_stream)
static void show_format_opts (void)
static void show_codec_opts (void)
int main (int argc, char **argv)
Macro Definition Documentation
AVFORMAT_OS_SUPPORT_H
#define AVFORMAT_OS_SUPPORT_H
Definition at line 31 of file print_options.c.
Function Documentation
print_usage()
static void print_usage (void) static
Definition at line 39 of file print_options.c.
Referenced by main().
print_option()
static void print_option (const AVOption * opts, const AVOption * o, int per_stream) static
Definition at line 46 of file print_options.c.
Referenced by show_opts().
show_opts()
static void show_opts (const AVOption * opts, int per_stream) static
Definition at line 91 of file print_options.c.
Referenced by show_codec_opts(), and show_format_opts().
show_format_opts()
static void show_format_opts (void) static
Definition at line 103 of file print_options.c.
Referenced by main().
show_codec_opts()
static void show_codec_opts (void) static
Definition at line 109 of file print_options.c.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 115 of file print_options.c.