FFmpeg: libavcodec/proresenc_anatoliy.c File Reference
proresenc_anatoliy.c File Reference
Apple ProRes encoder (Anatoliy Wasserman version) Known FOURCCs: 'apch' (HQ), 'apcn' (SD), 'apcs' (LT), 'acpo' (Proxy)
#include "avcodec.h"
#include "dct.h"
#include "internal.h"
#include "put_bits.h"
#include "bytestream.h"
#include "fdctdsp.h"
Data Structures
struct ProresContext
Macros
#define DEFAULT_SLICE_MB_WIDTH 8
#define FF_PROFILE_PRORES_PROXY 0
#define FF_PROFILE_PRORES_LT 1
#define FF_PROFILE_PRORES_STANDARD 2
#define FF_PROFILE_PRORES_HQ 3
#define QSCALE(qmat, ind, val) ((val) / ((qmat)[ind]))
#define TO_GOLOMB(val) (((val) << 1) ^ ((val) >> 31))
#define DIFF_SIGN(val, sign) (((val) >> 31) ^ (sign))
#define IS_NEGATIVE(val) ((((val) >> 31) ^ -1) + 1)
#define TO_GOLOMB2(val, sign) ((val)==0 ? 0 : ((val) << 1) + (sign))
#define FIRST_DC_CB 0xB8
Functions
static void encode_codeword (PutBitContext *pb, int val, int codebook)
static av_always_inline int get_level (int val)
static void encode_dc_coeffs (PutBitContext *pb, int16_t *in, int blocks_per_slice, int *qmat)
static void encode_ac_coeffs (AVCodecContext *avctx, PutBitContext *pb, int16_t *in, int blocks_per_slice, int *qmat)
static void get (uint8_t *pixels, int stride, int16_t *block)
static void fdct_get (FDCTDSPContext *fdsp, uint8_t *pixels, int stride, int16_t *block)
static int encode_slice_plane (AVCodecContext *avctx, int mb_count, uint8_t *src, int src_stride, uint8_t *buf, unsigned buf_size, int *qmat, int chroma)
static av_always_inline unsigned encode_slice_data (AVCodecContext *avctx, uint8_t *dest_y, uint8_t *dest_u, uint8_t *dest_v, int luma_stride, int chroma_stride, unsigned mb_count, uint8_t *buf, unsigned data_size, unsigned *y_data_size, unsigned *u_data_size, unsigned *v_data_size, int qp)
static void subimage_with_fill (uint16_t *src, unsigned x, unsigned y, unsigned stride, unsigned width, unsigned height, uint16_t *dst, unsigned dst_width, unsigned dst_height)
static int encode_slice (AVCodecContext *avctx, const AVFrame *pic, int mb_x, int mb_y, unsigned mb_count, uint8_t *buf, unsigned data_size, int unsafe, int *qp)
static int prores_encode_picture (AVCodecContext *avctx, const AVFrame *pic, uint8_t *buf, const int buf_size)
static int prores_encode_frame (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *pict, int *got_packet)
static void scale_mat (const uint8_t *src, int *dst, int scale)
static av_cold int prores_encode_init (AVCodecContext *avctx)
static av_cold int prores_encode_close (AVCodecContext *avctx)
Variables
static const AVProfile profiles []
static const int qp_start_table [4] = { 4, 1, 1, 1 }
static const int qp_end_table [4] = { 8, 9, 6, 6 }
static const int bitrate_table [5] = { 1000, 2100, 3500, 5400 }
static const uint8_t progressive_scan [64]
static const uint8_t QMAT_LUMA [4][64]
static const uint8_t QMAT_CHROMA [4][64]
static const uint8_t dc_codebook [7] = { 0x04, 0x28, 0x28, 0x4D, 0x4D, 0x70, 0x70}
static const uint8_t run_to_cb [16]
static const uint8_t lev_to_cb [10]
AVCodec ff_prores_aw_encoder
AVCodec ff_prores_encoder
Detailed Description
Apple ProRes encoder (Anatoliy Wasserman version) Known FOURCCs: 'apch' (HQ), 'apcn' (SD), 'apcs' (LT), 'acpo' (Proxy)
Definition in file proresenc_anatoliy.c.
Macro Definition Documentation
DEFAULT_SLICE_MB_WIDTH
#define DEFAULT_SLICE_MB_WIDTH 8
Definition at line 36 of file proresenc_anatoliy.c.
Referenced by encode_slice_plane(), prores_encode_init(), and prores_encode_picture().
FF_PROFILE_PRORES_PROXY
#define FF_PROFILE_PRORES_PROXY 0
Definition at line 38 of file proresenc_anatoliy.c.
Referenced by prores_encode_init().
FF_PROFILE_PRORES_LT
#define FF_PROFILE_PRORES_LT 1
Definition at line 39 of file proresenc_anatoliy.c.
FF_PROFILE_PRORES_STANDARD
#define FF_PROFILE_PRORES_STANDARD 2
Definition at line 40 of file proresenc_anatoliy.c.
Referenced by prores_encode_init().
FF_PROFILE_PRORES_HQ
#define FF_PROFILE_PRORES_HQ 3
Definition at line 41 of file proresenc_anatoliy.c.
Referenced by prores_encode_init().
QSCALE
#define QSCALE (qmat, ind, val) ((val) / ((qmat)[ind]))
Definition at line 185 of file proresenc_anatoliy.c.
Referenced by encode_ac_coeffs(), and encode_dc_coeffs().
TO_GOLOMB
#define TO_GOLOMB (val) (((val) << 1) ^ ((val) >> 31))
Definition at line 186 of file proresenc_anatoliy.c.
Referenced by encode_dc_coeffs().
DIFF_SIGN
#define DIFF_SIGN (val, sign) (((val) >> 31) ^ (sign))
Definition at line 187 of file proresenc_anatoliy.c.
Referenced by encode_dc_coeffs().
IS_NEGATIVE
#define IS_NEGATIVE (val) ((((val) >> 31) ^ -1) + 1)
Definition at line 188 of file proresenc_anatoliy.c.
Referenced by encode_ac_coeffs().
TO_GOLOMB2
#define TO_GOLOMB2 (val, sign) ((val)==0 ? 0 : ((val) << 1) + (sign))
Definition at line 189 of file proresenc_anatoliy.c.
Referenced by encode_dc_coeffs().
FIRST_DC_CB
#define FIRST_DC_CB 0xB8
Definition at line 197 of file proresenc_anatoliy.c.
Referenced by encode_dc_coeffs().
Function Documentation
encode_codeword()
static void encode_codeword (PutBitContext * pb, int val, int codebook) static
Definition at line 157 of file proresenc_anatoliy.c.
Referenced by encode_ac_coeffs(), and encode_dc_coeffs().
get_level()
static av_always_inline int get_level (int val) static
Definition at line 191 of file proresenc_anatoliy.c.
Referenced by encode_ac_coeffs(), and encode_dc_coeffs().
encode_dc_coeffs()
static void encode_dc_coeffs (PutBitContext * pb, int16_t * in, int blocks_per_slice, int * qmat) static
Definition at line 201 of file proresenc_anatoliy.c.
Referenced by encode_slice_plane().
encode_ac_coeffs()
static void encode_ac_coeffs (AVCodecContext * avctx, PutBitContext * pb, int16_t * in, int blocks_per_slice, int * qmat) static
Definition at line 232 of file proresenc_anatoliy.c.
Referenced by encode_slice_plane().
get()
static void get (uint8_t * pixels, int stride, int16_t * block) static
Definition at line 263 of file proresenc_anatoliy.c.
fdct_get()
static void fdct_get (FDCTDSPContext * fdsp, uint8_t * pixels, int stride, int16_t * block) static
Definition at line 275 of file proresenc_anatoliy.c.
Referenced by encode_slice_plane().
encode_slice_plane()
static int encode_slice_plane (AVCodecContext * avctx, int mb_count, uint8_t * src, int src_stride, uint8_t * buf, unsigned buf_size, int * qmat, int chroma) static
Definition at line 281 of file proresenc_anatoliy.c.
Referenced by encode_slice_data().
encode_slice_data()
static av_always_inline unsigned encode_slice_data (AVCodecContext * avctx, uint8_t * dest_y, uint8_t * dest_u, uint8_t * dest_v, int luma_stride, int chroma_stride, unsigned mb_count, uint8_t * buf, unsigned data_size, unsigned * y_data_size, unsigned * u_data_size, unsigned * v_data_size, int qp) static
Definition at line 315 of file proresenc_anatoliy.c.
Referenced by encode_slice().
subimage_with_fill()
static void subimage_with_fill (uint16_t * src, unsigned x, unsigned y, unsigned stride, unsigned width, unsigned height, uint16_t * dst, unsigned dst_width, unsigned dst_height) static
Definition at line 340 of file proresenc_anatoliy.c.
Referenced by encode_slice().
encode_slice()
static int encode_slice (AVCodecContext * avctx, const AVFrame * pic, int mb_x, int mb_y, unsigned mb_count, uint8_t * buf, unsigned data_size, int unsafe, int * qp) static
Definition at line 370 of file proresenc_anatoliy.c.
Referenced by prores_encode_picture().
prores_encode_picture()
static int prores_encode_picture (AVCodecContext * avctx, const AVFrame * pic, uint8_t * buf, const int buf_size) static
Definition at line 440 of file proresenc_anatoliy.c.
Referenced by prores_encode_frame().
prores_encode_frame()
static int prores_encode_frame (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * pict, int * got_packet) static
Definition at line 488 of file proresenc_anatoliy.c.
scale_mat()
static void scale_mat (const uint8_t * src, int * dst, int scale) static
Definition at line 531 of file proresenc_anatoliy.c.
Referenced by prores_encode_init().
prores_encode_init()
static av_cold int prores_encode_init (AVCodecContext * avctx) static
Definition at line 538 of file proresenc_anatoliy.c.
prores_encode_close()
static av_cold int prores_encode_close (AVCodecContext * avctx) static
Definition at line 596 of file proresenc_anatoliy.c.
Variable Documentation
profiles
const AVProfile profiles[] static
Initial value:
= {
    { FF_PROFILE_PRORES_PROXY,    "apco"},
    { FF_PROFILE_PRORES_LT,       "apcs"},
    { FF_PROFILE_PRORES_STANDARD, "apcn"},
    { FF_PROFILE_PRORES_HQ,       "apch"},
    { FF_PROFILE_UNKNOWN }
}
Definition at line 43 of file proresenc_anatoliy.c.
qp_start_table
const int qp_start_table[4] = { 4, 1, 1, 1 } static
Definition at line 51 of file proresenc_anatoliy.c.
Referenced by encode_slice(), and prores_encode_picture().
qp_end_table
const int qp_end_table[4] = { 8, 9, 6, 6 } static
Definition at line 52 of file proresenc_anatoliy.c.
Referenced by encode_slice().
bitrate_table
const int bitrate_table[5] = { 1000, 2100, 3500, 5400 } static
Definition at line 53 of file proresenc_anatoliy.c.
Referenced by encode_slice().
progressive_scan
const uint8_t progressive_scan[64] static
Initial value:
= {
     0,  1,  8,  9,  2,  3, 10, 11,
    16, 17, 24, 25, 18, 19, 26, 27,
     4,  5, 12, 20, 13,  6,  7, 14,
    21, 28, 29, 22, 15, 23, 30, 31,
    32, 33, 40, 48, 41, 34, 35, 42,
    49, 56, 57, 50, 43, 36, 37, 44,
    51, 58, 59, 52, 45, 38, 39, 46,
    53, 60, 61, 54, 47, 55, 62, 63
}
Definition at line 55 of file proresenc_anatoliy.c.
Referenced by encode_ac_coeffs().
QMAT_LUMA
const uint8_t QMAT_LUMA[4][64] static
Definition at line 66 of file proresenc_anatoliy.c.
Referenced by prores_encode_frame(), and prores_encode_init().
QMAT_CHROMA
const uint8_t QMAT_CHROMA[4][64] static
Definition at line 106 of file proresenc_anatoliy.c.
Referenced by prores_encode_frame(), and prores_encode_init().
dc_codebook
const uint8_t dc_codebook[7] = { 0x04, 0x28, 0x28, 0x4D, 0x4D, 0x70, 0x70} static
Definition at line 199 of file proresenc_anatoliy.c.
Referenced by encode_dc_coeffs().
run_to_cb
const uint8_t run_to_cb[16] static
Initial value:
= { 0x06, 0x06, 0x05, 0x05, 0x04, 0x29,
        0x29, 0x29, 0x29, 0x28, 0x28, 0x28, 0x28, 0x28, 0x28, 0x4C }
Definition at line 227 of file proresenc_anatoliy.c.
Referenced by encode_ac_coeffs().
lev_to_cb
const uint8_t lev_to_cb[10] static
Initial value:
= { 0x04, 0x0A, 0x05, 0x06, 0x04, 0x28,
        0x28, 0x28, 0x28, 0x4C }
Definition at line 229 of file proresenc_anatoliy.c.
Referenced by encode_ac_coeffs().
ff_prores_aw_encoder
AVCodec ff_prores_aw_encoder
Initial value:
= {
    .name           = "prores_aw",
    .long_name      = NULL_IF_CONFIG_SMALL("Apple ProRes"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_PRORES,
    .priv_data_size = sizeof(ProresContext),
    .init           = prores_encode_init,
    .close          = prores_encode_close,
    .encode2        = prores_encode_frame,
    .pix_fmts       = (const enum AVPixelFormat[]){AV_PIX_FMT_YUV422P10, AV_PIX_FMT_NONE},
    .capabilities   = AV_CODEC_CAP_FRAME_THREADS | AV_CODEC_CAP_INTRA_ONLY,
    .profiles       = profiles
}
Definition at line 604 of file proresenc_anatoliy.c.
ff_prores_encoder
AVCodec ff_prores_encoder
Initial value:
= {
    .name           = "prores",
    .long_name      = NULL_IF_CONFIG_SMALL("Apple ProRes"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_PRORES,
    .priv_data_size = sizeof(ProresContext),
    .init           = prores_encode_init,
    .close          = prores_encode_close,
    .encode2        = prores_encode_frame,
    .pix_fmts       = (const enum AVPixelFormat[]){AV_PIX_FMT_YUV422P10, AV_PIX_FMT_NONE},
    .capabilities   = AV_CODEC_CAP_FRAME_THREADS | AV_CODEC_CAP_INTRA_ONLY,
    .profiles       = profiles
}
Definition at line 618 of file proresenc_anatoliy.c.