FFmpeg: libavcodec/proresdec2.c File Reference
proresdec2.c File Reference
Known FOURCCs: 'apch' (HQ), 'apcn' (SD), 'apcs' (LT), 'acpo' (Proxy), 'ap4h' (4444)
#include "libavutil/internal.h"
#include "avcodec.h"
#include "get_bits.h"
#include "idctdsp.h"
#include "internal.h"
#include "simple_idct.h"
#include "proresdec.h"
#include "proresdata.h"
Macros
#define LONG_BITSTREAM_READER
#define DECODE_CODEWORD(val, codebook)
#define TOSIGNED(x) (((x) >> 1) ^ (-((x) & 1)))
#define FIRST_DC_CB 0xB8
Functions
static void permute (uint8_t *dst, const uint8_t *src, const uint8_t permutation[64])
static av_cold int decode_init (AVCodecContext *avctx)
static int decode_frame_header (ProresContext *ctx, const uint8_t *buf, const int data_size, AVCodecContext *avctx)
static int decode_picture_header (AVCodecContext *avctx, const uint8_t *buf, const int buf_size)
static av_always_inline void decode_dc_coeffs (GetBitContext *gb, int16_t *out, int blocks_per_slice)
static av_always_inline int decode_ac_coeffs (AVCodecContext *avctx, GetBitContext *gb, int16_t *out, int blocks_per_slice)
static int decode_slice_luma (AVCodecContext *avctx, SliceContext *slice, uint16_t *dst, int dst_stride, const uint8_t *buf, unsigned buf_size, const int16_t *qmat)
static int decode_slice_chroma (AVCodecContext *avctx, SliceContext *slice, uint16_t *dst, int dst_stride, const uint8_t *buf, unsigned buf_size, const int16_t *qmat, int log2_blocks_per_mb)
static void unpack_alpha (GetBitContext *gb, uint16_t *dst, int num_coeffs, const int num_bits)
static void decode_slice_alpha (ProresContext *ctx, uint16_t *dst, int dst_stride, const uint8_t *buf, int buf_size, int blocks_per_slice)
Decode alpha slice plane.
static int decode_slice_thread (AVCodecContext *avctx, void *arg, int jobnr, int threadnr)
static int decode_picture (AVCodecContext *avctx)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int decode_close (AVCodecContext *avctx)
Variables
static const uint8_t dc_codebook [7] = { 0x04, 0x28, 0x28, 0x4D, 0x4D, 0x70, 0x70}
static const uint8_t run_to_cb [16] = { 0x06, 0x06, 0x05, 0x05, 0x04, 0x29, 0x29, 0x29, 0x29, 0x28, 0x28, 0x28, 0x28, 0x28, 0x28, 0x4C }
static const uint8_t lev_to_cb [10] = { 0x04, 0x0A, 0x05, 0x06, 0x04, 0x28, 0x28, 0x28, 0x28, 0x4C }
AVCodec ff_prores_decoder
Detailed Description
Known FOURCCs: 'apch' (HQ), 'apcn' (SD), 'apcs' (LT), 'acpo' (Proxy), 'ap4h' (4444)
Definition in file proresdec2.c.
Macro Definition Documentation
LONG_BITSTREAM_READER
#define LONG_BITSTREAM_READER
Definition at line 29 of file proresdec2.c.
DECODE_CODEWORD
#define DECODE_CODEWORD (val, codebook)
Value:
do {                                                                \
        unsigned int rice_order, exp_order, switch_bits;                \
        unsigned int q, buf, bits;                                      \
                                                                        \
        UPDATE_CACHE(re, gb);                                           \
        buf = GET_CACHE(re, gb);                                        \
                                                                        \
        /* number of bits to switch between rice and exp golomb */      \
        switch_bits =  codebook & 3;                                    \
        rice_order  =  codebook >> 5;                                   \
        exp_order   = (codebook >> 2) & 7;                              \
                                                                        \
        q = 31 - av_log2(buf);                                          \
                                                                        \
        if (q > switch_bits) { /* exp golomb */                         \
            bits = exp_order - switch_bits + (q<<1);                    \
            val = SHOW_UBITS(re, gb, bits) - (1 << exp_order) +         \
                ((switch_bits + 1) << rice_order);                      \
            SKIP_BITS(re, gb, bits);                                    \
        } else if (rice_order) {                                        \
            SKIP_BITS(re, gb, q+1);                                     \
            val = (q << rice_order) + SHOW_UBITS(re, gb, rice_order);   \
            SKIP_BITS(re, gb, rice_order);                              \
        } else {                                                        \
            val = q;                                                    \
            SKIP_BITS(re, gb, q+1);                                     \
        }                                                               \
    } while (0)
Definition at line 253 of file proresdec2.c.
Referenced by decode_ac_coeffs(), and decode_dc_coeffs().
TOSIGNED
#define TOSIGNED (x) (((x) >> 1) ^ (-((x) & 1)))
Definition at line 283 of file proresdec2.c.
Referenced by decode_dc_coeffs().
FIRST_DC_CB
#define FIRST_DC_CB 0xB8
Definition at line 285 of file proresdec2.c.
Referenced by decode_dc_coeffs().
Function Documentation
permute()
static void permute (uint8_t * dst, const uint8_t * src, const uint8_t permutation[64]) static
Definition at line 40 of file proresdec2.c.
Referenced by decode_frame_header(), decode_init(), vp5_parse_coeff(), vp6_parse_coeff(), and vp6_parse_coeff_huffman().
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 47 of file proresdec2.c.
decode_frame_header()
static int decode_frame_header (ProresContext * ctx, const uint8_t * buf, const int data_size, AVCodecContext * avctx) static
Definition at line 66 of file proresdec2.c.
Referenced by decode_frame().
decode_picture_header()
static int decode_picture_header (AVCodecContext * avctx, const uint8_t * buf, const int buf_size) static
Definition at line 148 of file proresdec2.c.
Referenced by decode_frame().
decode_dc_coeffs()
static av_always_inline void decode_dc_coeffs (GetBitContext * gb, int16_t * out, int blocks_per_slice) static
Definition at line 289 of file proresdec2.c.
Referenced by decode_slice_chroma(), and decode_slice_luma().
decode_ac_coeffs()
static av_always_inline int decode_ac_coeffs (AVCodecContext * avctx, GetBitContext * gb, int16_t * out, int blocks_per_slice) static
Definition at line 319 of file proresdec2.c.
Referenced by decode_slice_chroma(), and decode_slice_luma().
decode_slice_luma()
static int decode_slice_luma (AVCodecContext * avctx, SliceContext * slice, uint16_t * dst, int dst_stride, const uint8_t * buf, unsigned buf_size, const int16_t * qmat) static
Definition at line 362 of file proresdec2.c.
Referenced by decode_slice_thread().
decode_slice_chroma()
static int decode_slice_chroma (AVCodecContext * avctx, SliceContext * slice, uint16_t * dst, int dst_stride, const uint8_t * buf, unsigned buf_size, const int16_t * qmat, int log2_blocks_per_mb) static
Definition at line 395 of file proresdec2.c.
Referenced by decode_slice_thread().
unpack_alpha()
static void unpack_alpha (GetBitContext * gb, uint16_t * dst, int num_coeffs, const int num_bits) static
Definition at line 428 of file proresdec2.c.
Referenced by decode_slice_alpha().
decode_slice_alpha()
static void decode_slice_alpha (ProresContext * ctx, uint16_t * dst, int dst_stride, const uint8_t * buf, int buf_size, int blocks_per_slice) static
Decode alpha slice plane.
Definition at line 476 of file proresdec2.c.
Referenced by decode_slice_thread().
decode_slice_thread()
static int decode_slice_thread (AVCodecContext * avctx, void * arg, int jobnr, int threadnr) static
Definition at line 505 of file proresdec2.c.
Referenced by decode_picture().
decode_picture()
static int decode_picture (AVCodecContext * avctx) static
Definition at line 613 of file proresdec2.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 627 of file proresdec2.c.
decode_close()
static av_cold int decode_close (AVCodecContext * avctx) static
Definition at line 684 of file proresdec2.c.
Variable Documentation
dc_codebook
const uint8_t dc_codebook[7] = { 0x04, 0x28, 0x28, 0x4D, 0x4D, 0x70, 0x70} static
Definition at line 287 of file proresdec2.c.
Referenced by decode_dc_coeffs().
run_to_cb
const uint8_t run_to_cb[16] = { 0x06, 0x06, 0x05, 0x05, 0x04, 0x29, 0x29, 0x29, 0x29, 0x28, 0x28, 0x28, 0x28, 0x28, 0x28, 0x4C } static
Definition at line 316 of file proresdec2.c.
Referenced by decode_ac_coeffs().
lev_to_cb
const uint8_t lev_to_cb[10] = { 0x04, 0x0A, 0x05, 0x06, 0x04, 0x28, 0x28, 0x28, 0x28, 0x4C } static
Definition at line 317 of file proresdec2.c.
Referenced by decode_ac_coeffs().
ff_prores_decoder
AVCodec ff_prores_decoder
Initial value:
= {
    .name           = "prores",
    .long_name      = NULL_IF_CONFIG_SMALL("ProRes"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_PRORES,
    .priv_data_size = sizeof(ProresContext),
    .init           = decode_init,
    .close          = decode_close,
    .decode         = decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_SLICE_THREADS,
}
Definition at line 693 of file proresdec2.c.