FFmpeg: libavcodec/proresenc_kostya.c File Reference
proresenc_kostya.c File Reference
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "avcodec.h"
#include "fdctdsp.h"
#include "put_bits.h"
#include "bytestream.h"
#include "internal.h"
#include "proresdata.h"
Data Structures
struct prores_profile
struct TrellisNode
struct ProresThreadData
struct ProresContext
Macros
#define CFACTOR_Y422 2
#define CFACTOR_Y444 3
#define MAX_MBS_PER_SLICE 8
#define MAX_PLANES 4
#define NUM_MB_LIMITS 4
#define TRELLIS_WIDTH 16
#define SCORE_LIMIT INT_MAX / 2
#define MAX_STORED_Q 16
#define GET_SIGN(x) ((x) >> 31)
#define MAKE_CODE(x) (((x) << 1) ^ GET_SIGN(x))
#define OFFSET(x) offsetof(ProresContext, x)
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Enumerations
enum {
PRORES_PROFILE_AUTO = -1, PRORES_PROFILE_PROXY = 0, PRORES_PROFILE_LT, PRORES_PROFILE_STANDARD,
PRORES_PROFILE_HQ, PRORES_PROFILE_4444
}
enum {
QUANT_MAT_PROXY = 0, QUANT_MAT_LT, QUANT_MAT_STANDARD, QUANT_MAT_HQ,
QUANT_MAT_DEFAULT
}
Functions
static void get_slice_data (ProresContext *ctx, const uint16_t *src, int linesize, int x, int y, int w, int h, int16_t *blocks, uint16_t *emu_buf, int mbs_per_slice, int blocks_per_mb, int is_chroma)
static void get_alpha_data (ProresContext *ctx, const uint16_t *src, int linesize, int x, int y, int w, int h, int16_t *blocks, int mbs_per_slice, int abits)
static void encode_vlc_codeword (PutBitContext *pb, unsigned codebook, int val)
Write an unsigned rice/exp golomb codeword.
static void encode_dcs (PutBitContext *pb, int16_t *blocks, int blocks_per_slice, int scale)
static void encode_acs (PutBitContext *pb, int16_t *blocks, int blocks_per_slice, int plane_size_factor, const uint8_t *scan, const int16_t *qmat)
static int encode_slice_plane (ProresContext *ctx, PutBitContext *pb, const uint16_t *src, int linesize, int mbs_per_slice, int16_t *blocks, int blocks_per_mb, int plane_size_factor, const int16_t *qmat)
static void put_alpha_diff (PutBitContext *pb, int cur, int prev, int abits)
static void put_alpha_run (PutBitContext *pb, int run)
static int encode_alpha_plane (ProresContext *ctx, PutBitContext *pb, int mbs_per_slice, uint16_t *blocks, int quant)
static int encode_slice (AVCodecContext *avctx, const AVFrame *pic, PutBitContext *pb, int sizes[4], int x, int y, int quant, int mbs_per_slice)
static int estimate_vlc (unsigned codebook, int val)
static int estimate_dcs (int *error, int16_t *blocks, int blocks_per_slice, int scale)
static int estimate_acs (int *error, int16_t *blocks, int blocks_per_slice, int plane_size_factor, const uint8_t *scan, const int16_t *qmat)
static int estimate_slice_plane (ProresContext *ctx, int *error, int plane, const uint16_t *src, int linesize, int mbs_per_slice, int blocks_per_mb, int plane_size_factor, const int16_t *qmat, ProresThreadData *td)
static int est_alpha_diff (int cur, int prev, int abits)
static int estimate_alpha_plane (ProresContext *ctx, int *error, const uint16_t *src, int linesize, int mbs_per_slice, int quant, int16_t *blocks)
static int find_slice_quant (AVCodecContext *avctx, int trellis_node, int x, int y, int mbs_per_slice, ProresThreadData *td)
static int find_quant_thread (AVCodecContext *avctx, void *arg, int jobnr, int threadnr)
static int encode_frame (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *pic, int *got_packet)
static av_cold int encode_close (AVCodecContext *avctx)
static void prores_fdct (FDCTDSPContext *fdsp, const uint16_t *src, int linesize, int16_t *block)
static av_cold int encode_init (AVCodecContext *avctx)
Variables
static const uint8_t prores_quant_matrices [][64]
static const int prores_mb_limits [NUM_MB_LIMITS]
static const struct prores_profile prores_profile_info [5]
static const AVOption options []
static const AVClass proresenc_class
AVCodec ff_prores_ks_encoder
Macro Definition Documentation
CFACTOR_Y422
#define CFACTOR_Y422 2
Definition at line 35 of file proresenc_kostya.c.
Referenced by encode_init().
CFACTOR_Y444
#define CFACTOR_Y444 3
Definition at line 36 of file proresenc_kostya.c.
Referenced by encode_init(), encode_slice(), and find_slice_quant().
MAX_MBS_PER_SLICE
#define MAX_MBS_PER_SLICE 8
Definition at line 38 of file proresenc_kostya.c.
MAX_PLANES
#define MAX_PLANES 4
Definition at line 40 of file proresenc_kostya.c.
Referenced by find_slice_quant().
NUM_MB_LIMITS
#define NUM_MB_LIMITS 4
Definition at line 112 of file proresenc_kostya.c.
Referenced by encode_init().
TRELLIS_WIDTH
#define TRELLIS_WIDTH 16
Definition at line 170 of file proresenc_kostya.c.
Referenced by encode_init(), find_quant_thread(), and find_slice_quant().
SCORE_LIMIT
#define SCORE_LIMIT INT_MAX / 2
Definition at line 171 of file proresenc_kostya.c.
Referenced by find_slice_quant().
MAX_STORED_Q
#define MAX_STORED_Q 16
Definition at line 180 of file proresenc_kostya.c.
Referenced by encode_init(), encode_slice(), and find_slice_quant().
GET_SIGN
#define GET_SIGN (x) ((x) >> 31)
Definition at line 360 of file proresenc_kostya.c.
Referenced by encode_acs(), encode_dcs(), and estimate_dcs().
MAKE_CODE
#define MAKE_CODE (x) (((x) << 1) ^ GET_SIGN(x))
Definition at line 361 of file proresenc_kostya.c.
Referenced by encode_dcs(), and estimate_dcs().
OFFSET
#define OFFSET (x) offsetof(ProresContext, x)
Definition at line 1290 of file proresenc_kostya.c.
VE
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 1291 of file proresenc_kostya.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PRORES_PROFILE_AUTO
PRORES_PROFILE_PROXY
PRORES_PROFILE_LT
PRORES_PROFILE_STANDARD
PRORES_PROFILE_HQ
PRORES_PROFILE_4444
Definition at line 42 of file proresenc_kostya.c.
anonymous enum
anonymous enum
Enumerator
QUANT_MAT_PROXY
QUANT_MAT_LT
QUANT_MAT_STANDARD
QUANT_MAT_HQ
QUANT_MAT_DEFAULT
Definition at line 51 of file proresenc_kostya.c.
Function Documentation
get_slice_data()
static void get_slice_data (ProresContext * ctx, const uint16_t * src, int linesize, int x, int y, int w, int h, int16_t * blocks, uint16_t * emu_buf, int mbs_per_slice, int blocks_per_mb, int is_chroma) static
Definition at line 229 of file proresenc_kostya.c.
Referenced by encode_slice(), and find_slice_quant().
get_alpha_data()
static void get_alpha_data (ProresContext * ctx, const uint16_t * src, int linesize, int x, int y, int w, int h, int16_t * blocks, int mbs_per_slice, int abits) static
Definition at line 300 of file proresenc_kostya.c.
Referenced by encode_slice(), and find_slice_quant().
encode_vlc_codeword()
static void encode_vlc_codeword (PutBitContext * pb, unsigned codebook, int val) inline static
Write an unsigned rice/exp golomb codeword.
Definition at line 331 of file proresenc_kostya.c.
Referenced by encode_acs(), and encode_dcs().
encode_dcs()
static void encode_dcs (PutBitContext * pb, int16_t * blocks, int blocks_per_slice, int scale) static
Definition at line 363 of file proresenc_kostya.c.
Referenced by encode_slice_plane().
encode_acs()
static void encode_acs (PutBitContext * pb, int16_t * blocks, int blocks_per_slice, int plane_size_factor, const uint8_t * scan, const int16_t * qmat) static
Definition at line 389 of file proresenc_kostya.c.
Referenced by encode_slice_plane().
encode_slice_plane()
static int encode_slice_plane (ProresContext * ctx, PutBitContext * pb, const uint16_t * src, int linesize, int mbs_per_slice, int16_t * blocks, int blocks_per_mb, int plane_size_factor, const int16_t * qmat) static
Definition at line 423 of file proresenc_kostya.c.
Referenced by encode_slice().
put_alpha_diff()
static void put_alpha_diff (PutBitContext * pb, int cur, int prev, int abits) static
Definition at line 442 of file proresenc_kostya.c.
Referenced by encode_alpha_plane().
put_alpha_run()
static void put_alpha_run (PutBitContext * pb, int run) static
Definition at line 461 of file proresenc_kostya.c.
Referenced by encode_alpha_plane().
encode_alpha_plane()
static int encode_alpha_plane (ProresContext * ctx, PutBitContext * pb, int mbs_per_slice, uint16_t * blocks, int quant) static
Definition at line 475 of file proresenc_kostya.c.
Referenced by encode_slice().
encode_slice()
static int encode_slice (AVCodecContext * avctx, const AVFrame * pic, PutBitContext * pb, int sizes[4], int x, int y, int quant, int mbs_per_slice) static
Definition at line 507 of file proresenc_kostya.c.
Referenced by encode_frame().
estimate_vlc()
static int estimate_vlc (unsigned codebook, int val) inline static
Definition at line 583 of file proresenc_kostya.c.
Referenced by estimate_acs(), and estimate_dcs().
estimate_dcs()
static int estimate_dcs (int * error, int16_t * blocks, int blocks_per_slice, int scale) static
Definition at line 605 of file proresenc_kostya.c.
Referenced by estimate_slice_plane().
estimate_acs()
static int estimate_acs (int * error, int16_t * blocks, int blocks_per_slice, int plane_size_factor, const uint8_t * scan, const int16_t * qmat) static
Definition at line 636 of file proresenc_kostya.c.
Referenced by estimate_slice_plane().
estimate_slice_plane()
static int estimate_slice_plane (ProresContext * ctx, int * error, int plane, const uint16_t * src, int linesize, int mbs_per_slice, int blocks_per_mb, int plane_size_factor, const int16_t * qmat, ProresThreadData * td) static
Definition at line 672 of file proresenc_kostya.c.
Referenced by find_slice_quant().
est_alpha_diff()
static int est_alpha_diff (int cur, int prev, int abits) static
Definition at line 690 of file proresenc_kostya.c.
Referenced by estimate_alpha_plane().
estimate_alpha_plane()
static int estimate_alpha_plane (ProresContext * ctx, int * error, const uint16_t * src, int linesize, int mbs_per_slice, int quant, int16_t * blocks) static
Definition at line 705 of file proresenc_kostya.c.
Referenced by find_slice_quant().
find_slice_quant()
static int find_slice_quant (AVCodecContext * avctx, int trellis_node, int x, int y, int mbs_per_slice, ProresThreadData * td) static
Definition at line 749 of file proresenc_kostya.c.
Referenced by find_quant_thread().
find_quant_thread()
static int find_quant_thread (AVCodecContext * avctx, void * arg, int jobnr, int threadnr) static
Definition at line 905 of file proresenc_kostya.c.
Referenced by encode_frame().
encode_frame()
static int encode_frame (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * pic, int * got_packet) static
Definition at line 929 of file proresenc_kostya.c.
encode_close()
static av_cold int encode_close (AVCodecContext * avctx) static
Definition at line 1090 of file proresenc_kostya.c.
Referenced by encode_init().
prores_fdct()
static void prores_fdct (FDCTDSPContext * fdsp, const uint16_t * src, int linesize, int16_t * block) static
Definition at line 1105 of file proresenc_kostya.c.
Referenced by encode_init().
encode_init()
static av_cold int encode_init (AVCodecContext * avctx) static
Definition at line 1119 of file proresenc_kostya.c.
Variable Documentation
prores_quant_matrices
const uint8_t prores_quant_matrices[][64] static
Definition at line 59 of file proresenc_kostya.c.
Referenced by encode_init().
prores_mb_limits
const int prores_mb_limits[NUM_MB_LIMITS] static
Initial value:
= {
    1620,
    2700,
    6075,
    9216,
}
Definition at line 113 of file proresenc_kostya.c.
Referenced by encode_init().
prores_profile_info
const struct prores_profile prores_profile_info[5] static
Referenced by encode_init().
options
const AVOption options[] static
Definition at line 1293 of file proresenc_kostya.c.
proresenc_class
const AVClass proresenc_class static
Initial value:
= {
    .class_name = "ProRes encoder",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1334 of file proresenc_kostya.c.
ff_prores_ks_encoder
AVCodec ff_prores_ks_encoder
Initial value:
= {
    .name           = "prores_ks",
    .long_name      = NULL_IF_CONFIG_SMALL("Apple ProRes (iCodec Pro)"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_PRORES,
    .priv_data_size = sizeof(ProresContext),
    .init           = encode_init,
    .close          = encode_close,
    .encode2        = encode_frame,
    .capabilities   = AV_CODEC_CAP_SLICE_THREADS,
    .pix_fmts       = (const enum AVPixelFormat[]) {
                          AV_PIX_FMT_YUV422P10, AV_PIX_FMT_YUV444P10,
                          AV_PIX_FMT_YUVA444P10, AV_PIX_FMT_NONE
                      },
    .priv_class     = &proresenc_class,
}
Definition at line 1341 of file proresenc_kostya.c.