FFmpeg: libavcodec/proresdsp.c File Reference
proresdsp.c File Reference
#include "config.h"
#include "libavutil/attributes.h"
#include "libavutil/common.h"
#include "idctdsp.h"
#include "proresdsp.h"
#include "simple_idct.h"
Macros
#define BIAS (1 << (PRORES_BITS_PER_SAMPLE - 1))
bias value for converting signed pixels into unsigned ones
#define CLIP_MIN (1 << (PRORES_BITS_PER_SAMPLE - 8))
minimum value for clipping resulting pixels
#define CLIP_MAX (1 << PRORES_BITS_PER_SAMPLE) - CLIP_MIN - 1
maximum value for clipping resulting pixels
#define CLIP(x) (av_clip((x), CLIP_MIN, CLIP_MAX))
Functions
static void put_pixels (uint16_t *dst, int stride, const int16_t *in)
Add bias value, clamp and output pixels of a slice.
static void prores_idct_put_c (uint16_t *out, int linesize, int16_t *block, const int16_t *qmat)
av_cold void ff_proresdsp_init (ProresDSPContext *dsp, AVCodecContext *avctx)
Macro Definition Documentation
BIAS
#define BIAS (1 << (PRORES_BITS_PER_SAMPLE - 1))
bias value for converting signed pixels into unsigned ones
Definition at line 30 of file proresdsp.c.
CLIP_MIN
#define CLIP_MIN (1 << (PRORES_BITS_PER_SAMPLE - 8))
minimum value for clipping resulting pixels
Definition at line 31 of file proresdsp.c.
CLIP_MAX
#define CLIP_MAX (1 << PRORES_BITS_PER_SAMPLE) - CLIP_MIN - 1
maximum value for clipping resulting pixels
Definition at line 32 of file proresdsp.c.
CLIP
#define CLIP (x) (av_clip((x), CLIP_MIN, CLIP_MAX))
Definition at line 34 of file proresdsp.c.
Referenced by put_pixels().
Function Documentation
put_pixels()
static void put_pixels (uint16_t * dst, int stride, const int16_t * in) static
Add bias value, clamp and output pixels of a slice.
Definition at line 39 of file proresdsp.c.
Referenced by prores_idct_put_c().
prores_idct_put_c()
static void prores_idct_put_c (uint16_t * out, int linesize, int16_t * block, const int16_t * qmat) static
Definition at line 52 of file proresdsp.c.
Referenced by ff_proresdsp_init().
ff_proresdsp_init()
av_cold void ff_proresdsp_init (ProresDSPContext * dsp, AVCodecContext * avctx)
Definition at line 58 of file proresdsp.c.
Referenced by decode_init().