FFmpeg: libavcodec/proresdec_lgpl.c File Reference
proresdec_lgpl.c File Reference
This is a decoder for Apple ProRes 422 SD/HQ/LT/Proxy and ProRes 4444.
#include <stdint.h>
#include "libavutil/intmath.h"
#include "avcodec.h"
#include "idctdsp.h"
#include "internal.h"
#include "proresdata.h"
#include "proresdsp.h"
#include "get_bits.h"
Data Structures
struct ProresThreadData
struct ProresContext
Macros
#define LONG_BITSTREAM_READER
#define LSB2SIGN(x) (-((x) & 1))
#define TOSIGNED(x) (((x) >> 1) ^ LSB2SIGN(x))
#define MAX_PADDING 16
#define MOVE_DATA_PTR(nbytes) buf += (nbytes); buf_size -= (nbytes)
Functions
static av_cold int decode_init (AVCodecContext *avctx)
static int decode_frame_header (ProresContext *ctx, const uint8_t *buf, const int data_size, AVCodecContext *avctx)
static int decode_picture_header (ProresContext *ctx, const uint8_t *buf, const int data_size, AVCodecContext *avctx)
static int decode_vlc_codeword (GetBitContext *gb, unsigned codebook)
Read an unsigned rice/exp golomb codeword.
static void decode_dc_coeffs (GetBitContext *gb, int16_t *out, int nblocks)
Decode DC coefficients for all blocks in a slice.
static int decode_ac_coeffs (GetBitContext *gb, int16_t *out, int blocks_per_slice, int plane_size_factor, const uint8_t *scan)
Decode AC coefficients for all blocks in a slice.
static int decode_slice_plane (ProresContext *ctx, ProresThreadData *td, const uint8_t *buf, int data_size, uint16_t *out_ptr, int linesize, int mbs_per_slice, int blocks_per_mb, int plane_size_factor, const int16_t *qmat, int is_chroma)
Decode a slice plane (luma or chroma).
static void unpack_alpha (GetBitContext *gb, uint16_t *dst, int num_coeffs, const int num_bits)
static void decode_alpha_plane (ProresContext *ctx, ProresThreadData *td, const uint8_t *buf, int data_size, uint16_t *out_ptr, int linesize, int mbs_per_slice)
Decode alpha slice plane.
static int decode_slice (AVCodecContext *avctx, void *tdata)
static int decode_picture (ProresContext *ctx, int pic_num, AVCodecContext *avctx)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int decode_close (AVCodecContext *avctx)
Variables
AVCodec ff_prores_lgpl_decoder
Detailed Description
This is a decoder for Apple ProRes 422 SD/HQ/LT/Proxy and ProRes 4444.
It is used for storing and editing high definition video data in Apple's Final Cut Pro.
See also
http://wiki.multimedia.cx/index.php?title=Apple_ProRes
Definition in file proresdec_lgpl.c.
Macro Definition Documentation
LONG_BITSTREAM_READER
#define LONG_BITSTREAM_READER
Definition at line 31 of file proresdec_lgpl.c.
LSB2SIGN
#define LSB2SIGN (x) (-((x) & 1))
Definition at line 339 of file proresdec_lgpl.c.
TOSIGNED
#define TOSIGNED (x) (((x) >> 1) ^ LSB2SIGN(x))
Definition at line 340 of file proresdec_lgpl.c.
Referenced by decode_dc_coeffs().
MAX_PADDING
#define MAX_PADDING 16
Definition at line 369 of file proresdec_lgpl.c.
Referenced by decode_ac_coeffs().
MOVE_DATA_PTR
#define MOVE_DATA_PTR (nbytes) buf += (nbytes); buf_size -= (nbytes)
Definition at line 714 of file proresdec_lgpl.c.
Referenced by decode_frame().
Function Documentation
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 81 of file proresdec_lgpl.c.
decode_frame_header()
static int decode_frame_header (ProresContext * ctx, const uint8_t * buf, const int data_size, AVCodecContext * avctx) static
Definition at line 99 of file proresdec_lgpl.c.
Referenced by decode_frame().
decode_picture_header()
static int decode_picture_header (ProresContext * ctx, const uint8_t * buf, const int data_size, AVCodecContext * avctx) static
Definition at line 217 of file proresdec_lgpl.c.
Referenced by decode_frame().
decode_vlc_codeword()
static int decode_vlc_codeword (GetBitContext * gb, unsigned codebook) inline static
Read an unsigned rice/exp golomb codeword.
Definition at line 301 of file proresdec_lgpl.c.
Referenced by decode_ac_coeffs(), and decode_dc_coeffs().
decode_dc_coeffs()
static void decode_dc_coeffs (GetBitContext * gb, int16_t * out, int nblocks) inline static
Decode DC coefficients for all blocks in a slice.
Definition at line 345 of file proresdec_lgpl.c.
Referenced by decode_slice_plane().
decode_ac_coeffs()
static int decode_ac_coeffs (GetBitContext * gb, int16_t * out, int blocks_per_slice, int plane_size_factor, const uint8_t * scan) inline static
Decode AC coefficients for all blocks in a slice.
Definition at line 374 of file proresdec_lgpl.c.
Referenced by decode_slice_plane().
decode_slice_plane()
static int decode_slice_plane (ProresContext * ctx, ProresThreadData * td, const uint8_t * buf, int data_size, uint16_t * out_ptr, int linesize, int mbs_per_slice, int blocks_per_mb, int plane_size_factor, const int16_t * qmat, int is_chroma) static
Decode a slice plane (luma or chroma).
Definition at line 425 of file proresdec_lgpl.c.
Referenced by decode_slice().
unpack_alpha()
static void unpack_alpha (GetBitContext * gb, uint16_t * dst, int num_coeffs, const int num_bits) static
Definition at line 485 of file proresdec_lgpl.c.
Referenced by decode_alpha_plane().
decode_alpha_plane()
static void decode_alpha_plane (ProresContext * ctx, ProresThreadData * td, const uint8_t * buf, int data_size, uint16_t * out_ptr, int linesize, int mbs_per_slice) static
Decode alpha slice plane.
Definition at line 531 of file proresdec_lgpl.c.
Referenced by decode_slice().
decode_slice()
static int decode_slice (AVCodecContext * avctx, void * tdata) static
Definition at line 558 of file proresdec_lgpl.c.
Referenced by decode_picture().
decode_picture()
static int decode_picture (ProresContext * ctx, int pic_num, AVCodecContext * avctx) static
Definition at line 683 of file proresdec_lgpl.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 716 of file proresdec_lgpl.c.
decode_close()
static av_cold int decode_close (AVCodecContext * avctx) static
Definition at line 764 of file proresdec_lgpl.c.
Variable Documentation
ff_prores_lgpl_decoder
AVCodec ff_prores_lgpl_decoder
Initial value:
= {
    .name           = "prores_lgpl",
    .long_name      = NULL_IF_CONFIG_SMALL("Apple ProRes (iCodec Pro)"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_PRORES,
    .priv_data_size = sizeof(ProresContext),
    .init           = decode_init,
    .close          = decode_close,
    .decode         = decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_SLICE_THREADS,
}
Definition at line 774 of file proresdec_lgpl.c.