FFmpeg: libavcodec/psymodel.h File Reference
psymodel.h File Reference
#include "avcodec.h"
Data Structures
struct FFPsyBand
single band psychoacoustic information
struct FFPsyChannel
single channel psychoacoustic information
struct FFPsyChannelGroup
psychoacoustic information for an arbitrary group of channels
struct FFPsyWindowInfo
windowing related information
struct FFPsyContext
context used by psychoacoustic model
struct FFPsyModel
codec-specific psychoacoustic model implementation
Macros
#define PSY_MAX_BANDS 128
maximum possible number of bands
#define PSY_MAX_CHANS 20
maximum number of channels
#define AAC_CUTOFF_FROM_BITRATE(bit_rate, channels, sample_rate)
#define AAC_CUTOFF(s)
Functions
int ff_psy_init (FFPsyContext *ctx, AVCodecContext *avctx, int num_lens, const uint8_t **bands, const int *num_bands, int num_groups, const uint8_t *group_map)
Initialize psychoacoustic model.
FFPsyChannelGroup * ff_psy_find_group (FFPsyContext *ctx, int channel)
Determine what group a channel belongs to.
void ff_psy_end (FFPsyContext *ctx)
Cleanup model context at the end.
struct FFPsyPreprocessContext * ff_psy_preprocess_init (AVCodecContext *avctx)
psychoacoustic model audio preprocessing initialization
void ff_psy_preprocess (struct FFPsyPreprocessContext *ctx, float **audio, int channels)
Preprocess several channel in audio frame in order to compress it better.
void ff_psy_preprocess_end (struct FFPsyPreprocessContext *ctx)
Cleanup audio preprocessing module.
Macro Definition Documentation
PSY_MAX_BANDS
#define PSY_MAX_BANDS 128
maximum possible number of bands
Definition at line 28 of file psymodel.h.
PSY_MAX_CHANS
#define PSY_MAX_CHANS 20
maximum number of channels
Definition at line 30 of file psymodel.h.
AAC_CUTOFF_FROM_BITRATE
#define AAC_CUTOFF_FROM_BITRATE (bit_rate, channels, sample_rate)
Value:
(bit_rate ? FFMIN3(FFMIN3(\
    FFMAX(bit_rate/channels/5, bit_rate/channels*15/32 - 5500), \
    3000 + bit_rate/channels/4, \
    12000 + bit_rate/channels/16), \
    22000, \
    sample_rate / 2): (sample_rate / 2))
Definition at line 35 of file psymodel.h.
Referenced by mark_pns(), search_for_pns(), and search_for_quantizers_twoloop().
AAC_CUTOFF
#define AAC_CUTOFF (s)
Value:
(\
    (s->flags & CODEC_FLAG_QSCALE) \
    ? s->sample_rate / 2 \
    : AAC_CUTOFF_FROM_BITRATE(s->bit_rate, s->channels, s->sample_rate) \
)
Definition at line 41 of file psymodel.h.
Referenced by psy_3gpp_init().
Function Documentation
ff_psy_init()
int ff_psy_init (FFPsyContext * ctx, AVCodecContext * avctx, int num_lens, const uint8_t ** bands, const int * num_bands, int num_groups, const uint8_t * group_map)
Initialize psychoacoustic model.
Parameters
ctx model context
avctx codec context
num_lens number of possible frame lengths
bands scalefactor band lengths for all frame lengths
num_bands number of scalefactor bands for all frame lengths
num_groups number of channel groups
group_map array with # of channels in group - 1, for each group
Returns
zero if successful, a negative value if not
Definition at line 31 of file psymodel.c.
Referenced by aac_encode_init().
ff_psy_find_group()
FFPsyChannelGroup* ff_psy_find_group (FFPsyContext * ctx, int channel)
Determine what group a channel belongs to.
Parameters
ctx psymodel context
channel channel to locate the group for
Returns
pointer to the FFPsyChannelGroup this channel belongs to
Definition at line 73 of file psymodel.c.
Referenced by psy_3gpp_analyze().
ff_psy_end()
void ff_psy_end (FFPsyContext * ctx)
Cleanup model context at the end.
Parameters
ctx model context
Definition at line 83 of file psymodel.c.
Referenced by aac_encode_end(), and ff_psy_init().
ff_psy_preprocess_init()
struct FFPsyPreprocessContext* ff_psy_preprocess_init (AVCodecContext * avctx)
psychoacoustic model audio preprocessing initialization
Definition at line 103 of file psymodel.c.
Referenced by aac_encode_init().
ff_psy_preprocess()
void ff_psy_preprocess (struct FFPsyPreprocessContext * ctx, float ** audio, int channels)
Preprocess several channel in audio frame in order to compress it better.
Parameters
ctx preprocessing context
audio samples to be filtered (in place)
channels number of channel to preprocess
Definition at line 139 of file psymodel.c.
Referenced by aac_encode_frame().
ff_psy_preprocess_end()
void ff_psy_preprocess_end (struct FFPsyPreprocessContext * ctx)
Cleanup audio preprocessing module.
Definition at line 152 of file psymodel.c.
Referenced by aac_encode_end().