FFmpeg: libavcodec/psymodel.c File Reference
psymodel.c File Reference
#include <string.h>
#include "avcodec.h"
#include "psymodel.h"
#include "iirfilter.h"
#include "libavutil/mem.h"
Data Structures
struct FFPsyPreprocessContext
Macros
#define FILT_ORDER 4
Functions
av_cold int ff_psy_init (FFPsyContext *ctx, AVCodecContext *avctx, int num_lens, const uint8_t **bands, const int *num_bands, int num_groups, const uint8_t *group_map)
Initialize psychoacoustic model.
FFPsyChannelGroup * ff_psy_find_group (FFPsyContext *ctx, int channel)
Determine what group a channel belongs to.
av_cold void ff_psy_end (FFPsyContext *ctx)
Cleanup model context at the end.
av_cold struct FFPsyPreprocessContext * ff_psy_preprocess_init (AVCodecContext *avctx)
psychoacoustic model audio preprocessing initialization
void ff_psy_preprocess (struct FFPsyPreprocessContext *ctx, float **audio, int channels)
Preprocess several channel in audio frame in order to compress it better.
av_cold void ff_psy_preprocess_end (struct FFPsyPreprocessContext *ctx)
Cleanup audio preprocessing module.
Variables
const FFPsyModel ff_aac_psy_model
Macro Definition Documentation
FILT_ORDER
#define FILT_ORDER 4
Definition at line 101 of file psymodel.c.
Referenced by ff_psy_preprocess_init().
Function Documentation
ff_psy_init()
av_cold int ff_psy_init (FFPsyContext * ctx, AVCodecContext * avctx, int num_lens, const uint8_t ** bands, const int * num_bands, int num_groups, const uint8_t * group_map)
Initialize psychoacoustic model.
Parameters
ctx model context
avctx codec context
num_lens number of possible frame lengths
bands scalefactor band lengths for all frame lengths
num_bands number of scalefactor bands for all frame lengths
num_groups number of channel groups
group_map array with # of channels in group - 1, for each group
Returns
zero if successful, a negative value if not
Definition at line 31 of file psymodel.c.
Referenced by aac_encode_init().
ff_psy_find_group()
FFPsyChannelGroup* ff_psy_find_group (FFPsyContext * ctx, int channel)
Determine what group a channel belongs to.
Parameters
ctx psymodel context
channel channel to locate the group for
Returns
pointer to the FFPsyChannelGroup this channel belongs to
Definition at line 73 of file psymodel.c.
Referenced by psy_3gpp_analyze().
ff_psy_end()
av_cold void ff_psy_end (FFPsyContext * ctx)
Cleanup model context at the end.
Parameters
ctx model context
Definition at line 83 of file psymodel.c.
Referenced by aac_encode_end(), and ff_psy_init().
ff_psy_preprocess_init()
av_cold struct FFPsyPreprocessContext* ff_psy_preprocess_init (AVCodecContext * avctx)
psychoacoustic model audio preprocessing initialization
Definition at line 103 of file psymodel.c.
Referenced by aac_encode_init().
ff_psy_preprocess()
void ff_psy_preprocess (struct FFPsyPreprocessContext * ctx, float ** audio, int channels)
Preprocess several channel in audio frame in order to compress it better.
Parameters
ctx preprocessing context
audio samples to be filtered (in place)
channels number of channel to preprocess
Definition at line 139 of file psymodel.c.
Referenced by aac_encode_frame().
ff_psy_preprocess_end()
av_cold void ff_psy_preprocess_end (struct FFPsyPreprocessContext * ctx)
Cleanup audio preprocessing module.
Definition at line 152 of file psymodel.c.
Referenced by aac_encode_end().
Variable Documentation
ff_aac_psy_model
const FFPsyModel ff_aac_psy_model
Definition at line 1018 of file aacpsy.c.
Referenced by ff_psy_init().