FFmpeg: libavcodec/pthread_internal.h File Reference
pthread_internal.h File Reference
#include "avcodec.h"
Macros
#define MAX_AUTO_THREADS 16
Functions
int ff_slice_thread_init (AVCodecContext *avctx)
void ff_slice_thread_free (AVCodecContext *avctx)
int ff_frame_thread_init (AVCodecContext *avctx)
void ff_frame_thread_free (AVCodecContext *avctx, int thread_count)
Macro Definition Documentation
MAX_AUTO_THREADS
#define MAX_AUTO_THREADS 16
Definition at line 26 of file pthread_internal.h.
Referenced by ff_frame_thread_init(), ff_slice_thread_init(), and validate_thread_parameters().
Function Documentation
ff_slice_thread_init()
int ff_slice_thread_init (AVCodecContext * avctx)
Definition at line 179 of file pthread_slice.c.
Referenced by ff_thread_init().
ff_slice_thread_free()
void ff_slice_thread_free (AVCodecContext * avctx)
Definition at line 103 of file pthread_slice.c.
Referenced by ff_thread_free().
ff_frame_thread_init()
int ff_frame_thread_init (AVCodecContext * avctx)
Definition at line 604 of file pthread_frame.c.
Referenced by ff_thread_init().
ff_frame_thread_free()
void ff_frame_thread_free (AVCodecContext * avctx, int thread_count)
Definition at line 540 of file pthread_frame.c.
Referenced by ff_frame_thread_init(), and ff_thread_free().