FFmpeg: libavcodec/pthread_frame.c File Reference
pthread_frame.c File Reference
Frame multithreading support functions.
#include "config.h"
#include <stdint.h>
#include "avcodec.h"
#include "internal.h"
#include "pthread_internal.h"
#include "thread.h"
#include "version.h"
#include "libavutil/avassert.h"
#include "libavutil/buffer.h"
#include "libavutil/common.h"
#include "libavutil/cpu.h"
#include "libavutil/frame.h"
#include "libavutil/internal.h"
#include "libavutil/log.h"
#include "libavutil/mem.h"
#include "libavutil/opt.h"
#include "libavutil/thread.h"
Data Structures
struct PerThreadContext
Context used by codec threads and stored in their AVCodecInternal thread_ctx.
struct FrameThreadContext
Context stored in the client AVCodecInternal thread_ctx.
Macros
#define THREAD_SAFE_CALLBACKS(avctx) ((avctx)->thread_safe_callbacks || (avctx)->get_buffer2 == avcodec_default_get_buffer2)
#define copy_fields(s, e) memcpy(&dst->s, &src->s, (char*)&dst->e - (char*)&dst->s);
Functions
static attribute_align_arg void * frame_worker_thread (void *arg)
Codec worker thread.
static int update_context_from_thread (AVCodecContext *dst, AVCodecContext *src, int for_user)
Update the next thread's AVCodecContext with values from the reference thread's context.
static int update_context_from_user (AVCodecContext *dst, AVCodecContext *src)
Update the next thread's AVCodecContext with values set by the user.
static void release_delayed_buffers (PerThreadContext *p)
Releases the buffers that this decoding thread was the last user of.
static int submit_packet (PerThreadContext *p, AVPacket *avpkt)
int ff_thread_decode_frame (AVCodecContext *avctx, AVFrame *picture, int *got_picture_ptr, AVPacket *avpkt)
Submit a new frame to a decoding thread.
void ff_thread_report_progress (ThreadFrame *f, int n, int field)
Notify later decoding threads when part of their reference picture is ready.
void ff_thread_await_progress (ThreadFrame *f, int n, int field)
Wait for earlier decoding threads to finish reference pictures.
void ff_thread_finish_setup (AVCodecContext *avctx)
If the codec defines update_thread_context(), call this when they are ready for the next thread to start decoding the next frame.
static void park_frame_worker_threads (FrameThreadContext *fctx, int thread_count)
Waits for all threads to finish.
void ff_frame_thread_free (AVCodecContext *avctx, int thread_count)
int ff_frame_thread_init (AVCodecContext *avctx)
void ff_thread_flush (AVCodecContext *avctx)
Wait for decoding threads to finish and reset internal state.
int ff_thread_can_start_frame (AVCodecContext *avctx)
static int thread_get_buffer_internal (AVCodecContext *avctx, ThreadFrame *f, int flags)
enum AVPixelFormat ff_thread_get_format (AVCodecContext *avctx, const enum AVPixelFormat *fmt)
Wrapper around get_format() for frame-multithreaded codecs.
int ff_thread_get_buffer (AVCodecContext *avctx, ThreadFrame *f, int flags)
Wrapper around get_buffer() for frame-multithreaded codecs.
void ff_thread_release_buffer (AVCodecContext *avctx, ThreadFrame *f)
Wrapper around release_buffer() frame-for multithreaded codecs.
Detailed Description
Frame multithreading support functions.
See also
doc/multithreading.txt
Definition in file pthread_frame.c.
Macro Definition Documentation
THREAD_SAFE_CALLBACKS
#define THREAD_SAFE_CALLBACKS (avctx) ((avctx)->thread_safe_callbacks || (avctx)->get_buffer2 == avcodec_default_get_buffer2)
Definition at line 118 of file pthread_frame.c.
Referenced by ff_thread_can_start_frame(), frame_worker_thread(), and thread_get_buffer_internal().
copy_fields
#define copy_fields (s, e) memcpy(&dst->s, &src->s, (char*)&dst->e - (char*)&dst->s);
Referenced by ref_frames(), and update_context_from_user().
Function Documentation
frame_worker_thread()
static attribute_align_arg void* frame_worker_thread (void * arg) static
Codec worker thread.
Automatically calls ff_thread_finish_setup() if the codec does not provide an update_thread_context method, or if the codec returns before calling it.
Definition at line 128 of file pthread_frame.c.
Referenced by ff_frame_thread_init().
update_context_from_thread()
static int update_context_from_thread (AVCodecContext * dst, AVCodecContext * src, int for_user) static
Update the next thread's AVCodecContext with values from the reference thread's context.
Parameters
dst The destination context.
src The source context.
for_user 0 if the destination is a codec thread, 1 if the destination is the user's thread
Returns
0 on success, negative error code on failure
Definition at line 184 of file pthread_frame.c.
Referenced by ff_frame_thread_free(), ff_frame_thread_init(), ff_thread_decode_frame(), ff_thread_flush(), and submit_packet().
update_context_from_user()
static int update_context_from_user (AVCodecContext * dst, AVCodecContext * src) static
Update the next thread's AVCodecContext with values set by the user.
Parameters
dst The destination context.
src The source context.
Returns
0 on success, negative error code on failure
Definition at line 253 of file pthread_frame.c.
Referenced by ff_thread_decode_frame().
release_delayed_buffers()
static void release_delayed_buffers (PerThreadContext * p) static
Releases the buffers that this decoding thread was the last user of.
Definition at line 290 of file pthread_frame.c.
Referenced by ff_frame_thread_free(), ff_thread_flush(), and submit_packet().
submit_packet()
static int submit_packet (PerThreadContext * p, AVPacket * avpkt) static
Definition at line 310 of file pthread_frame.c.
Referenced by ff_thread_decode_frame().
ff_thread_decode_frame()
int ff_thread_decode_frame (AVCodecContext * avctx, AVFrame * picture, int * got_picture_ptr, AVPacket * avpkt)
Submit a new frame to a decoding thread.
Returns the next available frame in picture. *got_picture_ptr will be 0 if none is available. The return value on success is the size of the consumed packet for compatibility with avcodec_decode_video2(). This means the decoder has to consume the full packet.
Parameters are the same as avcodec_decode_video2().
Definition at line 386 of file pthread_frame.c.
Referenced by avcodec_decode_audio4(), and avcodec_decode_video2().
ff_thread_report_progress()
void ff_thread_report_progress (ThreadFrame * f, int progress, int field)
Notify later decoding threads when part of their reference picture is ready.
Call this when some part of the picture is finished decoding. Later calls with lower values of progress have no effect.
Parameters
f The picture being decoded.
progress Value, in arbitrary units, of how much of the picture has decoded.
field The field being decoded, for field-picture codecs. 0 for top field or frame pictures, 1 for bottom field.
Definition at line 471 of file pthread_frame.c.
Referenced by decode(), decode_finish_row(), decode_frame(), decode_frame_common(), decode_nal_units(), decode_slice(), ff_h264_decode_slice_header(), ff_h264_field_end(), ff_hevc_hls_filter(), ff_mpv_frame_end(), ff_mpv_frame_start(), ff_mpv_report_decode_progress(), ff_rv34_decode_frame(), finish_frame(), generate_missing_ref(), h264_field_start(), handle_p_frame_apng(), mimic_decode_frame(), rv34_decode_slice(), vp3_decode_frame(), vp3_draw_horiz_band(), vp78_decode_frame(), vp78_decode_mb_row_sliced(), and vp9_decode_frame().
ff_thread_await_progress()
void ff_thread_await_progress (ThreadFrame * f, int progress, int field)
Wait for earlier decoding threads to finish reference pictures.
Call this before accessing some part of a picture, with a given value for progress, and it will return after the responsible decoding thread calls ff_thread_report_progress() with the same or higher value for progress.
Parameters
f The picture being referenced.
progress Value, in arbitrary units, to wait for.
field The field being referenced, for field-picture codecs. 0 for top field or frame pictures, 1 for bottom field.
Definition at line 489 of file pthread_frame.c.
Referenced by await_reference_mb_row(), await_reference_row(), await_references(), decode(), decode_frame(), decode_mb_row_no_filter(), decode_mode(), decode_slice(), ff_er_frame_end(), find_ref_mvs(), guess_mv(), h264_field_start(), handle_p_frame_apng(), handle_p_frame_png(), hevc_await_progress(), is_intra_more_likely(), mc_chroma_scaled(), mc_chroma_unscaled(), mc_luma_scaled(), mc_luma_unscaled(), mpeg4_decode_mb(), mpv_decode_mb_internal(), rv34_decode_mv(), rv34_mc(), temporal_luma_motion_vector(), vp78_decode_frame(), vp8_mc_chroma(), and vp8_mc_luma().
ff_thread_finish_setup()
void ff_thread_finish_setup (AVCodecContext * avctx)
If the codec defines update_thread_context(), call this when they are ready for the next thread to start decoding the next frame.
After calling it, do not change any variables read by the update_thread_context() method, or call ff_thread_get_buffer().
Parameters
avctx The context.
Definition at line 507 of file pthread_frame.c.
Referenced by decode_frame(), decode_idat_chunk(), decode_postinit(), ff_h263_decode_frame(), ff_rv34_decode_frame(), frame_worker_thread(), hap_decode(), hevc_frame_start(), mimic_decode_frame(), mpeg_field_start(), tak_decode_frame(), thread_get_buffer_internal(), vp3_decode_frame(), vp78_decode_frame(), and vp9_decode_frame().
park_frame_worker_threads()
static void park_frame_worker_threads (FrameThreadContext * fctx, int thread_count) static
Waits for all threads to finish.
Definition at line 523 of file pthread_frame.c.
Referenced by ff_frame_thread_free(), and ff_thread_flush().
ff_frame_thread_free()
void ff_frame_thread_free (AVCodecContext * avctx, int thread_count)
Definition at line 540 of file pthread_frame.c.
Referenced by ff_frame_thread_init(), and ff_thread_free().
ff_frame_thread_init()
int ff_frame_thread_init (AVCodecContext * avctx)
Definition at line 604 of file pthread_frame.c.
Referenced by ff_thread_init().
ff_thread_flush()
void ff_thread_flush (AVCodecContext * avctx)
Wait for decoding threads to finish and reset internal state.
Called by avcodec_flush_buffers().
Parameters
avctx The context.
Definition at line 718 of file pthread_frame.c.
Referenced by avcodec_flush_buffers().
ff_thread_can_start_frame()
int ff_thread_can_start_frame (AVCodecContext * avctx)
Definition at line 747 of file pthread_frame.c.
thread_get_buffer_internal()
static int thread_get_buffer_internal (AVCodecContext * avctx, ThreadFrame * f, int flags) static
Definition at line 757 of file pthread_frame.c.
Referenced by ff_thread_get_buffer().
ff_thread_get_format()
enum AVPixelFormat ff_thread_get_format (AVCodecContext * avctx, const enum AVPixelFormat * fmt)
Wrapper around get_format() for frame-multithreaded codecs.
Call this function instead of avctx->get_format(). Cannot be called after the codec has called ff_thread_finish_setup().
Parameters
avctx The current context.
fmt The list of available formats.
Definition at line 815 of file pthread_frame.c.
Referenced by get_pixel_format(), mpeg_get_pixelformat(), set_sps(), and update_size().
ff_thread_get_buffer()
int ff_thread_get_buffer (AVCodecContext * avctx, ThreadFrame * f, int flags)
Wrapper around get_buffer() for frame-multithreaded codecs.
Call this function instead of ff_get_buffer(f). Cannot be called after the codec has called ff_thread_finish_setup().
Parameters
avctx The current context.
f The frame to write into.
Definition at line 841 of file pthread_frame.c.
Referenced by aic_decode_frame(), alloc_frame(), alloc_frame_buffer(), alloc_picture(), cfhd_decode(), decode_element(), decode_entropy_coded_image(), decode_frame(), decode_idat_chunk(), dnxhd_decode_frame(), dxv_decode(), flac_decode_frame(), hap_decode(), init_image(), jpeg2000_decode_frame(), lag_decode_frame(), libopenjpeg_decode_frame(), magy_decode_frame(), mimic_decode_frame(), pixlet_decode_frame(), tak_decode_frame(), tta_decode_frame(), vble_decode_frame(), vp3_decode_frame(), vp8_alloc_frame(), vp9_alloc_frame(), and wavpack_decode_block().
ff_thread_release_buffer()
void ff_thread_release_buffer (AVCodecContext * avctx, ThreadFrame * f)
Wrapper around release_buffer() frame-for multithreaded codecs.
Call this function instead of avctx->release_buffer(f). The AVFrame will be copied and the actual release_buffer() call will be performed later. The contents of data pointed to by the AVFrame should not be changed until ff_thread_get_buffer() is called on it.
Parameters
avctx The current context.
f The picture being released.
Definition at line 849 of file pthread_frame.c.
Referenced by copy_fields(), decode_frame(), decode_frame_common(), decode_idat_chunk(), ff_ffv1_close(), ff_h264_unref_picture(), ff_hevc_unref_frame(), ff_mpeg_unref_picture(), mimic_decode_end(), mimic_decode_frame(), mimic_decode_init(), png_dec_end(), ref_frame(), update_frames(), vp3_decode_flush(), vp3_decode_frame(), vp8_alloc_frame(), vp8_release_frame(), vp9_decode_flush(), vp9_decode_frame(), vp9_decode_free(), vp9_decode_init(), and vp9_unref_frame().