FFmpeg: libavdevice/pulse_audio_common.c File Reference
pulse_audio_common.c File Reference
#include "pulse_audio_common.h"
#include "libavutil/attributes.h"
#include "libavutil/avstring.h"
#include "libavutil/mem.h"
#include "libavutil/avassert.h"
Data Structures
struct PulseAudioDeviceList
Enumerations
enum PulseAudioContextState { PULSE_CONTEXT_INITIALIZING, PULSE_CONTEXT_READY, PULSE_CONTEXT_FINISHED }
Functions
pa_sample_format_t av_cold ff_codec_id_to_pulse_format (enum AVCodecID codec_id)
static void pa_state_cb (pa_context *c, void *userdata)
void ff_pulse_audio_disconnect_context (pa_mainloop **pa_ml, pa_context **pa_ctx)
int ff_pulse_audio_connect_context (pa_mainloop **pa_ml, pa_context **pa_ctx, const char *server, const char *description)
static void pulse_add_detected_device (PulseAudioDeviceList *info, const char *name, const char *description)
static void pulse_audio_source_device_cb (pa_context *c, const pa_source_info *dev, int eol, void *userdata)
static void pulse_audio_sink_device_cb (pa_context *c, const pa_sink_info *dev, int eol, void *userdata)
static void pulse_server_info_cb (pa_context *c, const pa_server_info *i, void *userdata)
int ff_pulse_audio_get_devices (AVDeviceInfoList *devices, const char *server, int output)
Enumeration Type Documentation
PulseAudioContextState
enum PulseAudioContextState
Enumerator
PULSE_CONTEXT_INITIALIZING
PULSE_CONTEXT_READY
PULSE_CONTEXT_FINISHED
Definition at line 47 of file pulse_audio_common.c.
Function Documentation
ff_codec_id_to_pulse_format()
pa_sample_format_t av_cold ff_codec_id_to_pulse_format (enum AVCodecID codec_id)
Definition at line 29 of file pulse_audio_common.c.
Referenced by pulse_read_header(), and pulse_write_header().
pa_state_cb()
static void pa_state_cb (pa_context * c, void * userdata) static
Definition at line 60 of file pulse_audio_common.c.
Referenced by ff_pulse_audio_connect_context().
ff_pulse_audio_disconnect_context()
void ff_pulse_audio_disconnect_context (pa_mainloop ** pa_ml, pa_context ** pa_ctx)
Definition at line 77 of file pulse_audio_common.c.
Referenced by ff_pulse_audio_connect_context(), ff_pulse_audio_get_devices(), and pulse_update_sink_input_info().
ff_pulse_audio_connect_context()
int ff_pulse_audio_connect_context (pa_mainloop ** pa_ml, pa_context ** pa_ctx, const char * server, const char * description)
Definition at line 93 of file pulse_audio_common.c.
Referenced by ff_pulse_audio_get_devices(), and pulse_update_sink_input_info().
pulse_add_detected_device()
static void pulse_add_detected_device (PulseAudioDeviceList * info, const char * name, const char * description) static
Definition at line 135 of file pulse_audio_common.c.
Referenced by pulse_audio_sink_device_cb(), and pulse_audio_source_device_cb().
pulse_audio_source_device_cb()
static void pulse_audio_source_device_cb (pa_context * c, const pa_source_info * dev, int eol, void * userdata) static
Definition at line 172 of file pulse_audio_common.c.
Referenced by ff_pulse_audio_get_devices().
pulse_audio_sink_device_cb()
static void pulse_audio_sink_device_cb (pa_context * c, const pa_sink_info * dev, int eol, void * userdata) static
Definition at line 179 of file pulse_audio_common.c.
Referenced by ff_pulse_audio_get_devices().
pulse_server_info_cb()
static void pulse_server_info_cb (pa_context * c, const pa_server_info * i, void * userdata) static
Definition at line 186 of file pulse_audio_common.c.
Referenced by ff_pulse_audio_get_devices().
ff_pulse_audio_get_devices()
int ff_pulse_audio_get_devices (AVDeviceInfoList * devices, const char * server, int output)
Definition at line 197 of file pulse_audio_common.c.
Referenced by pulse_get_device_list().