FFmpeg: libavcodec/put_bits.h File Reference
put_bits.h File Reference
bitstream writer API
#include <stdint.h>
#include <stddef.h>
#include "libavutil/intreadwrite.h"
#include "libavutil/avassert.h"
Data Structures
struct PutBitContext
Functions
static void init_put_bits (PutBitContext *s, uint8_t *buffer, int buffer_size)
Initialize the PutBitContext s.
static void rebase_put_bits (PutBitContext *s, uint8_t *buffer, int buffer_size)
Rebase the bit writer onto a reallocated buffer.
static int put_bits_count (PutBitContext *s)
static int put_bits_left (PutBitContext *s)
static void flush_put_bits (PutBitContext *s)
Pad the end of the output stream with zeros.
void avpriv_align_put_bits (PutBitContext *s)
Pad the bitstream with zeros up to the next byte boundary.
void avpriv_put_string (PutBitContext *pb, const char *string, int terminate_string)
Put the string string in the bitstream.
void avpriv_copy_bits (PutBitContext *pb, const uint8_t *src, int length)
Copy the content of src to the bitstream.
static void put_bits (PutBitContext *s, int n, unsigned int value)
Write up to 31 bits into a bitstream.
static void put_sbits (PutBitContext *pb, int n, int32_t value)
static void av_unused put_bits32 (PutBitContext *s, uint32_t value)
Write exactly 32 bits into a bitstream.
static uint8_t * put_bits_ptr (PutBitContext *s)
Return the pointer to the byte where the bitstream writer will put the next bit.
static void skip_put_bytes (PutBitContext *s, int n)
Skip the given number of bytes.
static void skip_put_bits (PutBitContext *s, int n)
Skip the given number of bits.
static void set_put_bits_buffer_size (PutBitContext *s, int size)
Change the end of the buffer.
Detailed Description
bitstream writer API
Definition in file put_bits.h.
Function Documentation
init_put_bits()
static void init_put_bits (PutBitContext * s, uint8_t * buffer, int buffer_size) inline static
Initialize the PutBitContext s.
Parameters
buffer the buffer where to put bits
buffer_size the size in bytes of buffer
Definition at line 48 of file put_bits.h.
Referenced by aac_adtstoasc_filter(), aac_encode_frame(), adpcm_encode_frame(), adts_decode_extradata(), adts_write_frame_header(), adx_encode(), avpriv_dca_convert_bitstream(), decode_init(), decode_packet(), dnxhd_encode_thread(), dv_decode_video_segment(), dv_encode_video_segment(), encode_bitstream(), encode_block(), encode_ext_header(), encode_frame(), encode_init(), encode_picture_ls(), encode_slice(), encode_slice_plane(), encode_slices(), encode_thread(), ff_ac3_output_frame(), ff_hevc_encode_nal_vps(), ff_init_cabac_encoder(), ff_lzw_encode_init(), ff_mjpeg_find_marker(), ff_mpeg4_init_partitions(), ff_mpv_encode_picture(), flush(), flv_write_codec_header(), g726_reset(), latm_write_packet(), ljpeg_encode_frame(), main(), mov_write_ac3_tag(), mov_write_dvc1_structs(), mov_write_eac3_tag(), MPA_encode_frame(), pack_bitstream(), pnm_decode_frame(), predictor_calc_error(), put_audio_specific_config(), put_line(), put_main_header(), put_pack_header(), put_swf_matrix(), put_swf_rect(), put_system_header(), ra144_encode_frame(), read_packet(), s302m_encode2_frame(), save_bits(), send_mode_a(), send_mode_b(), svq1_encode_frame(), svq1_encode_plane(), swf_write_header(), tta_encode_frame(), vaapi_encode_h264_write_extra_header(), vaapi_encode_h264_write_sei(), vaapi_encode_h264_write_sequence_header(), vaapi_encode_h264_write_slice_header(), vaapi_encode_h265_write_sequence_header(), vaapi_encode_h265_write_slice_header(), vaapi_encode_mjpeg_write_image_header(), vorbis_encode_frame(), wavpack_encode_block(), wmavoice_decode_packet(), write_frame(), write_header(), write_huff_codes(), write_major_sync(), write_streaminfo(), write_substrs(), and xsub_encode().
rebase_put_bits()
static void rebase_put_bits (PutBitContext * s, uint8_t * buffer, int buffer_size) inline static
Rebase the bit writer onto a reallocated buffer.
Parameters
buffer the buffer where to put bits
buffer_size the size in bytes of buffer, must be larger than the previous size
Definition at line 71 of file put_bits.h.
Referenced by ff_mpv_reallocate_putbitbuffer().
put_bits_count()
static int put_bits_count (PutBitContext * s) inline static
Returns
the total number of bits written to the bitstream.
Definition at line 85 of file put_bits.h.
Referenced by aac_encode_frame(), avpriv_copy_bits(), avpriv_copy_pce_data(), avpriv_dca_convert_bitstream(), copy_bits(), dnxhd_encode_thread(), dv_decode_video_segment(), dv_encode_video_segment(), encode_422_bitstream(), encode_alpha_plane(), encode_bgra_bitstream(), encode_block(), encode_frame(), encode_gray_bitstream(), encode_hq_slice(), encode_init(), encode_line(), encode_mb(), encode_mb_hq(), encode_parse_info(), encode_picture(), encode_picture_ls(), encode_plane_bitstream(), encode_slice_plane(), encode_superframe(), encode_thread(), ff_hevc_encode_nal_vps(), ff_mjpeg_encode_picture_header(), ff_mjpeg_encode_stuffing(), ff_mjpeg_escape_FF(), ff_mpeg1_encode_picture_header(), ff_mpeg4_merge_partitions(), ff_mpeg4_stuffing(), ff_mpv_encode_picture(), ff_mpv_reallocate_putbitbuffer(), floor_encode(), get_bits_diff(), latm_write_packet(), ljpeg_encode_bgr(), ljpeg_encode_frame(), ljpeg_encode_yuv(), merge_context_after_encode(), MPA_encode_frame(), output_frame_end(), predictor_calc_error(), put_bitstream_info(), put_cabac_terminate(), put_codeword(), put_main_header(), save_bits(), skip_put_bytes(), svq1_encode_frame(), svq1_encode_plane(), tta_encode_frame(), update_mb_info(), vaapi_encode_h264_write_extra_header(), vaapi_encode_h264_write_sei(), vaapi_encode_h264_write_sequence_header(), vaapi_encode_h264_write_slice_header(), vaapi_encode_h264_write_trailing_rbsp(), vaapi_encode_h265_write_rbsp_trailing_bits(), vaapi_encode_h265_write_sequence_header(), vaapi_encode_h265_write_slice_header(), vaapi_encode_h265_write_slice_header2(), vaapi_encode_mjpeg_write_image_header(), vc2_encode_frame(), vorbis_encode_frame(), wavpack_encode_block(), write_frame(), write_frame_footer(), write_frame_header(), write_huff_codes(), write_mb_info(), write_restart_header(), write_substrs(), writtenBytes(), xsub_encode(), and xsub_encode_rle().
put_bits_left()
static int put_bits_left (PutBitContext * s) inline static
Returns
the number of bits available in the bitstream.
Definition at line 93 of file put_bits.h.
Referenced by avpriv_copy_bits(), dv_encode_ac(), encode_slice(), save_bits(), and tta_encode_frame().
flush_put_bits()
static void flush_put_bits (PutBitContext * s) inline static
Pad the end of the output stream with zeros.
Definition at line 101 of file put_bits.h.
Referenced by aac_adtstoasc_filter(), aac_encode_frame(), adpcm_encode_frame(), adts_decode_extradata(), adts_write_frame_header(), adx_encode(), avpriv_copy_bits(), avpriv_dca_convert_bitstream(), dnxhd_encode_thread(), dv_decode_video_segment(), dv_encode_video_segment(), encode_alpha_plane(), encode_bitstream(), encode_block(), encode_ext_header(), encode_frame(), encode_hq_slice(), encode_init(), encode_picture_ls(), encode_slice_plane(), encode_slices(), encode_superframe(), encode_thread(), ff_mjpeg_escape_FF(), ff_mjpeg_find_marker(), ff_mpeg4_merge_partitions(), ff_mpv_encode_picture(), flv_write_codec_header(), g726_reset(), gif_image_write_image(), jpeg_put_comments(), jpeg_table_header(), latm_write_packet(), ljpeg_encode_frame(), main(), merge_context_after_encode(), mov_write_ac3_tag(), mov_write_dvc1_structs(), mov_write_eac3_tag(), output_frame_end(), pack_bitstream(), pnm_decode_frame(), predictor_calc_error(), put_audio_specific_config(), put_cabac_terminate(), put_line(), put_main_header(), put_pack_header(), put_swf_matrix(), put_swf_rect(), put_system_header(), ra144_encode_frame(), read_packet(), s302m_encode2_frame(), save_bits(), send_mode_a(), send_mode_b(), svq1_encode_frame(), svq1_encode_plane(), swf_write_header(), tta_encode_frame(), vaapi_encode_h264_write_extra_header(), vaapi_encode_h264_write_sei(), vaapi_encode_h264_write_sequence_header(), vaapi_encode_h264_write_slice_header(), vaapi_encode_h265_write_sequence_header(), vaapi_encode_h265_write_slice_header(), vaapi_encode_mjpeg_write_image_header(), vc2_encode_frame(), vorbis_encode_frame(), wavpack_encode_block(), wmavoice_decode_packet(), write_frame(), write_frame_footer(), write_frame_header(), write_header(), write_huff_codes(), write_major_sync(), write_restart_header(), write_slice_end(), write_streaminfo(), write_substrs(), and xsub_encode().
avpriv_align_put_bits()
void avpriv_align_put_bits (PutBitContext * s)
Pad the bitstream with zeros up to the next byte boundary.
Definition at line 49 of file bitstream.c.
Referenced by avpriv_copy_pce_data(), encode_block(), encode_frame(), encode_hq_slice(), encode_parse_info(), encode_picture_header(), encode_picture_ls(), encode_picture_start(), encode_seq_header(), encode_slices(), encode_wavelet_transform(), ff_flv_encode_picture_header(), ff_h261_encode_picture_header(), ff_h263_encode_picture_header(), ff_hevc_encode_nal_vps(), ff_msmpeg4_encode_picture_header(), ff_rv10_encode_picture_header(), flush_put_bits(), latm_write_packet(), put_bitstream_info(), put_header(), write_slice_end(), xsub_encode(), and xsub_encode_rle().
avpriv_put_string()
void avpriv_put_string (PutBitContext * pb, const char * string, int terminate_string)
Put the string string in the bitstream.
Parameters
terminate_string 0-terminates the written string if value is 1
Definition at line 54 of file bitstream.c.
Referenced by encode_frame(), encode_parse_info(), flush_put_bits(), jpeg_put_comments(), and mpeg4_encode_vol_header().
avpriv_copy_bits()
void avpriv_copy_bits (PutBitContext * pb, const uint8_t * src, int length)
Copy the content of src to the bitstream.
Parameters
length the number of bits of src to copy
Definition at line 65 of file bitstream.c.
Referenced by copy_bits(), encode_thread(), ff_mpeg4_merge_partitions(), flush_put_bits(), latm_write_frame_header(), latm_write_packet(), merge_context_after_encode(), save_bits(), and svq1_encode_plane().
put_bits()
static void put_bits (PutBitContext * s, int n, unsigned int value) inline static
Write up to 31 bits into a bitstream.
Use put_bits32 to write 32 bits.
Definition at line 152 of file put_bits.h.
Referenced by put_bits32(), and put_sbits().
put_sbits()
static void put_sbits (PutBitContext * pb, int n, int32_t value) inline static
Definition at line 200 of file put_bits.h.
Referenced by adpcm_encode_frame(), adx_encode(), asv1_put_level(), dv_encode_video_segment(), encode_acs(), encode_block(), encode_codeword(), encode_vlc_codeword(), ff_flv2_encode_ac_esc(), ff_h261_encode_picture_header(), ff_h263_encode_picture_header(), ff_mjpeg_encode_dc(), ff_msmpeg4_encode_block(), ff_rv20_encode_picture_header(), h261_encode_block(), h263_encode_block(), mpeg1_encode_block(), mpeg1_encode_mb_internal(), mpeg1_encode_sequence_header(), output_audio_block(), pack_float_sample(), pack_int32(), put_header(), put_line(), put_subframe_samples(), quantize_and_encode_band_cost_template(), set_ur_golomb_jpegls(), write_block_data(), write_decoding_params(), write_element(), write_filter_params(), write_matrix_params(), and write_subframes().
put_bits32()
static void av_unused put_bits32 (PutBitContext * s, uint32_t value) static
Write exactly 32 bits into a bitstream.
Definition at line 210 of file put_bits.h.
Referenced by dv_decode_video_segment(), encode_parse_info(), encode_picture_header(), ff_hevc_encode_nal_vps(), mov_write_dvc1_structs(), put_float(), put_main_header(), put_pack_header(), put_system_header(), tta_encode_frame(), write_element_header(), and write_ptl_layer().
put_bits_ptr()
static uint8_t* put_bits_ptr (PutBitContext * s) inline static
Return the pointer to the byte where the bitstream writer will put the next bit.
Definition at line 227 of file put_bits.h.
Referenced by avpriv_copy_bits(), encode_block(), encode_hq_slice(), encode_slice_plane(), encode_slices(), encode_superframe(), encode_thread(), ff_h261_encode_picture_header(), ff_h263_encode_picture_header(), ff_mpeg4_init_partitions(), jpeg_put_comments(), jpeg_table_header(), ljpeg_encode_frame(), output_frame_end(), put_pack_header(), put_swf_matrix(), put_swf_rect(), put_system_header(), and swf_write_header().
skip_put_bytes()
static void skip_put_bytes (PutBitContext * s, int n) inline static
Skip the given number of bytes.
PutBitContext must be flushed & aligned to a byte boundary before calling this.
Definition at line 236 of file put_bits.h.
Referenced by avpriv_copy_bits(), encode_hq_slice(), encode_slices(), and ff_mjpeg_escape_FF().
skip_put_bits()
static void skip_put_bits (PutBitContext * s, int n) inline static
Skip the given number of bits.
Must only be used if the actual values in the bitstream do not matter. If n is 0 the behavior is undefined.
Definition at line 249 of file put_bits.h.
Referenced by ff_h263_encode_motion_vector(), mpeg4_encode_blocks(), and pack_bitstream().
set_put_bits_buffer_size()
static void set_put_bits_buffer_size (PutBitContext * s, int size) inline static
Change the end of the buffer.
Parameters
size the new size in bytes of the buffer where to put bits
Definition at line 261 of file put_bits.h.
Referenced by encode_picture(), ff_mpeg4_init_partitions(), and ff_mpeg4_merge_partitions().