FFmpeg: libavcodec/qdm2.c File Reference
qdm2.c File Reference
QDM2 decoder.
#include <math.h>
#include <stddef.h>
#include <stdio.h>
#include "libavutil/channel_layout.h"
#include "avcodec.h"
#include "get_bits.h"
#include "internal.h"
#include "mpegaudio.h"
#include "mpegaudiodsp.h"
#include "rdft.h"
#include "qdm2_tablegen.h"
Data Structures
struct QDM2SubPacket
Subpacket.
struct QDM2SubPNode
A node in the subpacket list.
struct QDM2Complex
struct FFTTone
struct FFTCoefficient
struct QDM2FFT
struct QDM2Context
QDM2 decoder context.
Macros
#define BITSTREAM_READER_LE
#define QDM2_LIST_ADD(list, size, packet)
#define QDM2_SB_USED(sub_sampling) (((sub_sampling) >= 2) ? 30 : 8 << (sub_sampling))
#define FIX_NOISE_IDX(noise_idx)
#define SB_DITHERING_NOISE(sb, noise_idx) (noise_table[(noise_idx)++] * sb_noise_attenuation[(sb)])
#define SAMPLES_NEEDED av_log (NULL,AV_LOG_INFO,"This file triggers some untested code. Please contact the developers.\n");
#define SAMPLES_NEEDED_2(why) av_log (NULL,AV_LOG_INFO,"This file triggers some missing code. Please contact the developers.\nPosition: %s\n",why);
#define QDM2_MAX_FRAME_SIZE 512
Typedefs
typedef int8_t sb_int8_array[2][30][64]
Functions
static int qdm2_get_vlc (GetBitContext *gb, const VLC *vlc, int flag, int depth)
static int qdm2_get_se_vlc (const VLC *vlc, GetBitContext *gb, int depth)
static uint16_t qdm2_packet_checksum (const uint8_t *data, int length, int value)
QDM2 checksum.
static void qdm2_decode_sub_packet_header (GetBitContext *gb, QDM2SubPacket *sub_packet)
Fill a QDM2SubPacket structure with packet type, size, and data pointer.
static QDM2SubPNode * qdm2_search_subpacket_type_in_list (QDM2SubPNode *list, int type)
Return node pointer to first packet of requested type in list.
static void average_quantized_coeffs (QDM2Context *q)
Replace 8 elements with their average value.
static void build_sb_samples_from_noise (QDM2Context *q, int sb)
Build subband samples with noise weighted by q->tone_level.
static int fix_coding_method_array (int sb, int channels, sb_int8_array coding_method)
Called while processing data from subpackets 11 and 12.
static void fill_tone_level_array (QDM2Context *q, int flag)
Related to synthesis filter Called by process_subpacket_10.
static void fill_coding_method_array (sb_int8_array tone_level_idx, sb_int8_array tone_level_idx_temp, sb_int8_array coding_method, int nb_channels, int c, int superblocktype_2_3, int cm_table_select)
Related to synthesis filter Called by process_subpacket_11 c is built with data from subpacket 11 Most of this function is used only if superblock_type_2_3 == 0, never seen it in samples.
static int synthfilt_build_sb_samples (QDM2Context *q, GetBitContext *gb, int length, int sb_min, int sb_max)
Called by process_subpacket_11 to process more data from subpacket 11 with sb 0-8.
static int init_quantized_coeffs_elem0 (int8_t *quantized_coeffs, GetBitContext *gb)
Init the first element of a channel in quantized_coeffs with data from packet 10 (quantized_coeffs[ch][0]).
static void init_tone_level_dequantization (QDM2Context *q, GetBitContext *gb)
Related to synthesis filter, process data from packet 10 Init part of quantized_coeffs via function init_quantized_coeffs_elem0 Init tone_level_idx_hi1, tone_level_idx_hi2, tone_level_idx_mid with data from packet 10.
static int process_subpacket_9 (QDM2Context *q, QDM2SubPNode *node)
Process subpacket 9, init quantized_coeffs with data from it.
static void process_subpacket_10 (QDM2Context *q, QDM2SubPNode *node)
Process subpacket 10 if not null, else.
static void process_subpacket_11 (QDM2Context *q, QDM2SubPNode *node)
Process subpacket 11.
static void process_subpacket_12 (QDM2Context *q, QDM2SubPNode *node)
Process subpacket 12.
static void process_synthesis_subpackets (QDM2Context *q, QDM2SubPNode *list)
Process new subpackets for synthesis filter.
static void qdm2_decode_super_block (QDM2Context *q)
Decode superblock, fill packet lists.
static void qdm2_fft_init_coefficient (QDM2Context *q, int sub_packet, int offset, int duration, int channel, int exp, int phase)
static void qdm2_fft_decode_tones (QDM2Context *q, int duration, GetBitContext *gb, int b)
static void qdm2_decode_fft_packets (QDM2Context *q)
static void qdm2_fft_generate_tone (QDM2Context *q, FFTTone *tone)
static void qdm2_fft_tone_synthesizer (QDM2Context *q, int sub_packet)
static void qdm2_calculate_fft (QDM2Context *q, int channel, int sub_packet)
static void qdm2_synthesis_filter (QDM2Context *q, int index)
static av_cold void qdm2_init_static_data (void)
Init static data (does not depend on specific file)
static av_cold int qdm2_decode_init (AVCodecContext *avctx)
Init parameters from codec extradata.
static av_cold int qdm2_decode_close (AVCodecContext *avctx)
static int qdm2_decode (QDM2Context *q, const uint8_t *in, int16_t *out)
static int qdm2_decode_frame (AVCodecContext *avctx, void *data, int *got_frame_ptr, AVPacket *avpkt)
Variables
static const int switchtable [23]
AVCodec ff_qdm2_decoder
Detailed Description
QDM2 decoder.
Author
Ewald Snel, Benjamin Larsson, Alex Beregszaszi, Roberto Togni
The decoder is not perfect yet, there are still some distortions especially on files encoded with 16 or 8 subbands.
Definition in file qdm2.c.
Macro Definition Documentation
BITSTREAM_READER_LE
#define BITSTREAM_READER_LE
Definition at line 40 of file qdm2.c.
QDM2_LIST_ADD
#define QDM2_LIST_ADD (list, size, packet)
Value:
do { \
      if (size > 0) { \
    list[size - 1].next = &list[size]; \
      } \
      list[size].packet = packet; \
      list[size].next = NULL; \
      size++; \
} while(0)
Definition at line 50 of file qdm2.c.
Referenced by qdm2_decode_super_block().
QDM2_SB_USED
#define QDM2_SB_USED (sub_sampling) (((sub_sampling) >= 2) ? 30 : 8 << (sub_sampling))
Definition at line 61 of file qdm2.c.
Referenced by average_quantized_coeffs(), fill_tone_level_array(), init_tone_level_dequantization(), process_subpacket_12(), process_subpacket_9(), and qdm2_synthesis_filter().
FIX_NOISE_IDX
#define FIX_NOISE_IDX (noise_idx)
Value:
if ((noise_idx) >= 3840) \
    (noise_idx) -= 3840; \
Definition at line 63 of file qdm2.c.
Referenced by build_sb_samples_from_noise(), and synthfilt_build_sb_samples().
SB_DITHERING_NOISE
#define SB_DITHERING_NOISE (sb, noise_idx) (noise_table[(noise_idx)++] * sb_noise_attenuation[(sb)])
Definition at line 67 of file qdm2.c.
Referenced by build_sb_samples_from_noise(), and synthfilt_build_sb_samples().
SAMPLES_NEEDED
#define SAMPLES_NEEDED av_log (NULL,AV_LOG_INFO,"This file triggers some untested code. Please contact the developers.\n");
Definition at line 69 of file qdm2.c.
Referenced by fix_coding_method_array().
SAMPLES_NEEDED_2
#define SAMPLES_NEEDED_2 (why) av_log (NULL,AV_LOG_INFO,"This file triggers some missing code. Please contact the developers.\nPosition: %s\n",why);
Definition at line 72 of file qdm2.c.
Referenced by qdm2_decode(), and qdm2_decode_super_block().
QDM2_MAX_FRAME_SIZE
#define QDM2_MAX_FRAME_SIZE 512
Definition at line 75 of file qdm2.c.
Referenced by qdm2_decode_init().
Typedef Documentation
sb_int8_array
typedef int8_t sb_int8_array[2][30][64]
Definition at line 77 of file qdm2.c.
Function Documentation
qdm2_get_vlc()
static int qdm2_get_vlc (GetBitContext * gb, const VLC * vlc, int flag, int depth) static
Definition at line 200 of file qdm2.c.
Referenced by init_quantized_coeffs_elem0(), init_tone_level_dequantization(), process_subpacket_9(), qdm2_decode_super_block(), qdm2_fft_decode_tones(), qdm2_get_se_vlc(), and synthfilt_build_sb_samples().
qdm2_get_se_vlc()
static int qdm2_get_se_vlc (const VLC * vlc, GetBitContext * gb, int depth) static
Definition at line 229 of file qdm2.c.
Referenced by init_quantized_coeffs_elem0(), and process_subpacket_9().
qdm2_packet_checksum()
static uint16_t qdm2_packet_checksum (const uint8_t * data, int length, int value) static
QDM2 checksum.
Parameters
data pointer to data to be checksummed
length data length
value checksum value
Returns
0 if checksum is OK
Definition at line 245 of file qdm2.c.
Referenced by qdm2_decode_super_block().
qdm2_decode_sub_packet_header()
static void qdm2_decode_sub_packet_header (GetBitContext * gb, QDM2SubPacket * sub_packet) static
Fill a QDM2SubPacket structure with packet type, size, and data pointer.
Parameters
gb bitreader context
sub_packet packet under analysis
Definition at line 261 of file qdm2.c.
Referenced by qdm2_decode_super_block().
qdm2_search_subpacket_type_in_list()
static QDM2SubPNode* qdm2_search_subpacket_type_in_list (QDM2SubPNode * list, int type) static
Return node pointer to first packet of requested type in list.
Parameters
list list of subpackets to be scanned
type type of searched subpacket
Returns
node pointer for subpacket if found, else NULL
Definition at line 296 of file qdm2.c.
Referenced by process_synthesis_subpackets().
average_quantized_coeffs()
static void average_quantized_coeffs (QDM2Context * q) static
Replace 8 elements with their average value.
Called by qdm2_decode_superblock before starting subblock decoding.
Parameters
q context
Definition at line 313 of file qdm2.c.
Referenced by qdm2_decode_super_block().
build_sb_samples_from_noise()
static void build_sb_samples_from_noise (QDM2Context * q, int sb) static
Build subband samples with noise weighted by q->tone_level.
Called by synthfilt_build_sb_samples.
Parameters
q context
sb subband index
Definition at line 342 of file qdm2.c.
Referenced by synthfilt_build_sb_samples().
fix_coding_method_array()
static int fix_coding_method_array (int sb, int channels, sb_int8_array coding_method) static
Called while processing data from subpackets 11 and 12.
Used after making changes to coding_method array.
Parameters
sb subband index
channels number of channels
coding_method q->coding_method[0][0][0]
Definition at line 369 of file qdm2.c.
Referenced by fill_coding_method_array(), and synthfilt_build_sb_samples().
fill_tone_level_array()
static void fill_tone_level_array (QDM2Context * q, int flag) static
Related to synthesis filter Called by process_subpacket_10.
Parameters
q context
flag 1 if called after getting data from subpacket 10, 0 if no subpacket 10
Definition at line 435 of file qdm2.c.
Referenced by process_subpacket_10().
fill_coding_method_array()
static void fill_coding_method_array (sb_int8_array tone_level_idx, sb_int8_array tone_level_idx_temp, sb_int8_array coding_method, int nb_channels, int c, int superblocktype_2_3, int cm_table_select) static
Related to synthesis filter Called by process_subpacket_11 c is built with data from subpacket 11 Most of this function is used only if superblock_type_2_3 == 0, never seen it in samples.
Parameters
tone_level_idx
tone_level_idx_temp
coding_method q->coding_method[0][0][0]
nb_channels number of channels
c coming from subpacket 11, passed as 8*c
superblocktype_2_3 flag based on superblock packet type
cm_table_select q->cm_table_select
Definition at line 524 of file qdm2.c.
Referenced by process_subpacket_11().
synthfilt_build_sb_samples()
static int synthfilt_build_sb_samples (QDM2Context * q, GetBitContext * gb, int length, int sb_min, int sb_max) static
Called by process_subpacket_11 to process more data from subpacket 11 with sb 0-8.
Called by process_subpacket_12 to process data from subpacket 12 with sb 8-sb_used.
Parameters
q context
gb bitreader context
length packet length in bits
sb_min lower subband processed (sb_min included)
sb_max higher subband processed (sb_max excluded)
Definition at line 651 of file qdm2.c.
Referenced by process_subpacket_11(), and process_subpacket_12().
init_quantized_coeffs_elem0()
static int init_quantized_coeffs_elem0 (int8_t * quantized_coeffs, GetBitContext * gb) static
Init the first element of a channel in quantized_coeffs with data from packet 10 (quantized_coeffs[ch][0]).
This is similar to process_subpacket_9, but for a single channel and for element [0] same VLC tables as process_subpacket_9 are used.
Parameters
quantized_coeffs pointer to quantized_coeffs[ch][0]
gb bitreader context
Definition at line 867 of file qdm2.c.
Referenced by init_tone_level_dequantization().
init_tone_level_dequantization()
static void init_tone_level_dequantization (QDM2Context * q, GetBitContext * gb) static
Related to synthesis filter, process data from packet 10 Init part of quantized_coeffs via function init_quantized_coeffs_elem0 Init tone_level_idx_hi1, tone_level_idx_hi2, tone_level_idx_mid with data from packet 10.
Parameters
q context
gb bitreader context
Definition at line 908 of file qdm2.c.
Referenced by process_subpacket_10().
process_subpacket_9()
static int process_subpacket_9 (QDM2Context * q, QDM2SubPNode * node) static
Process subpacket 9, init quantized_coeffs with data from it.
Parameters
q context
node pointer to node with packet
Definition at line 971 of file qdm2.c.
Referenced by process_synthesis_subpackets().
process_subpacket_10()
static void process_subpacket_10 (QDM2Context * q, QDM2SubPNode * node) static
Process subpacket 10 if not null, else.
Parameters
q context
node pointer to node with packet
Definition at line 1013 of file qdm2.c.
Referenced by process_synthesis_subpackets(), and qdm2_decode_super_block().
process_subpacket_11()
static void process_subpacket_11 (QDM2Context * q, QDM2SubPNode * node) static
Process subpacket 11.
Parameters
q context
node pointer to node with packet
Definition at line 1032 of file qdm2.c.
Referenced by process_synthesis_subpackets(), and qdm2_decode_super_block().
process_subpacket_12()
static void process_subpacket_12 (QDM2Context * q, QDM2SubPNode * node) static
Process subpacket 12.
Parameters
q context
node pointer to node with packet
Definition at line 1061 of file qdm2.c.
Referenced by process_synthesis_subpackets(), and qdm2_decode_super_block().
process_synthesis_subpackets()
static void process_synthesis_subpackets (QDM2Context * q, QDM2SubPNode * list) static
Process new subpackets for synthesis filter.
Parameters
q context
list list with synthesis filter packets (list D)
Definition at line 1080 of file qdm2.c.
Referenced by qdm2_decode_super_block().
qdm2_decode_super_block()
static void qdm2_decode_super_block (QDM2Context * q) static
Decode superblock, fill packet lists.
Parameters
q context
Definition at line 1112 of file qdm2.c.
Referenced by qdm2_decode().
qdm2_fft_init_coefficient()
static void qdm2_fft_init_coefficient (QDM2Context * q, int sub_packet, int offset, int duration, int channel, int exp, int phase) static
Definition at line 1236 of file qdm2.c.
Referenced by qdm2_fft_decode_tones().
qdm2_fft_decode_tones()
static void qdm2_fft_decode_tones (QDM2Context * q, int duration, GetBitContext * gb, int b) static
Definition at line 1252 of file qdm2.c.
Referenced by qdm2_decode_fft_packets().
qdm2_decode_fft_packets()
static void qdm2_decode_fft_packets (QDM2Context * q) static
Definition at line 1338 of file qdm2.c.
Referenced by qdm2_decode().
qdm2_fft_generate_tone()
static void qdm2_fft_generate_tone (QDM2Context * q, FFTTone * tone) static
Definition at line 1412 of file qdm2.c.
Referenced by qdm2_fft_tone_synthesizer().
qdm2_fft_tone_synthesizer()
static void qdm2_fft_tone_synthesizer (QDM2Context * q, int sub_packet) static
Definition at line 1458 of file qdm2.c.
Referenced by qdm2_decode().
qdm2_calculate_fft()
static void qdm2_calculate_fft (QDM2Context * q, int channel, int sub_packet) static
Definition at line 1529 of file qdm2.c.
Referenced by qdm2_decode().
qdm2_synthesis_filter()
static void qdm2_synthesis_filter (QDM2Context * q, int index) static
Parameters
q context
index subpacket number
Definition at line 1549 of file qdm2.c.
Referenced by qdm2_decode().
qdm2_init_static_data()
static av_cold void qdm2_init_static_data (void) static
Init static data (does not depend on specific file)
Parameters
q context
Definition at line 1587 of file qdm2.c.
Referenced by qdm2_decode_init().
qdm2_decode_init()
static av_cold int qdm2_decode_init (AVCodecContext * avctx) static
Init parameters from codec extradata.
Definition at line 1605 of file qdm2.c.
qdm2_decode_close()
static av_cold int qdm2_decode_close (AVCodecContext * avctx) static
Definition at line 1780 of file qdm2.c.
qdm2_decode()
static int qdm2_decode (QDM2Context * q, const uint8_t * in, int16_t * out) static
Definition at line 1789 of file qdm2.c.
Referenced by qdm2_decode_frame().
qdm2_decode_frame()
static int qdm2_decode_frame (AVCodecContext * avctx, void * data, int * got_frame_ptr, AVPacket * avpkt) static
Definition at line 1851 of file qdm2.c.
Variable Documentation
switchtable
const int switchtable[23] static
Initial value:
= {
    0, 5, 1, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 3, 5, 5, 5, 5, 5, 4
}
Definition at line 196 of file qdm2.c.
Referenced by fix_coding_method_array().
ff_qdm2_decoder
AVCodec ff_qdm2_decoder
Initial value:
= {
    .name             = "qdm2",
    .long_name        = NULL_IF_CONFIG_SMALL("QDesign Music Codec 2"),
    .type             = AVMEDIA_TYPE_AUDIO,
    .id               = AV_CODEC_ID_QDM2,
    .priv_data_size   = sizeof(QDM2Context),
    .init             = qdm2_decode_init,
    .close            = qdm2_decode_close,
    .decode           = qdm2_decode_frame,
    .capabilities     = AV_CODEC_CAP_DR1,
}
Definition at line 1883 of file qdm2.c.