FFmpeg: libavcodec/qdrw.c File Reference
qdrw.c File Reference
Apple QuickDraw codec.
#include "libavutil/common.h"
#include "libavutil/intreadwrite.h"
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
Enumerations
enum QuickdrawOpcodes {
PACKBITSRECT = 0x0098, PACKBITSRGN, DIRECTBITSRECT, DIRECTBITSRGN,
EOP = 0x00FF
}
Functions
static int parse_palette (AVCodecContext *avctx, GetByteContext *gbc, uint32_t *pal, int colors)
static int decode_rle (AVCodecContext *avctx, AVFrame *p, GetByteContext *gbc, int step)
static int check_header (const char *buf, int buf_size)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
Variables
AVCodec ff_qdraw_decoder
Detailed Description
Apple QuickDraw codec.
https://developer.apple.com/legacy/library/documentation/mac/QuickDraw/QuickDraw-461.html
Definition in file qdrw.c.
Enumeration Type Documentation
QuickdrawOpcodes
enum QuickdrawOpcodes
Enumerator
PACKBITSRECT
PACKBITSRGN
DIRECTBITSRECT
DIRECTBITSRGN
EOP
Definition at line 35 of file qdrw.c.
Function Documentation
parse_palette()
static int parse_palette (AVCodecContext * avctx, GetByteContext * gbc, uint32_t * pal, int colors) static
Definition at line 44 of file qdrw.c.
Referenced by decode_frame().
decode_rle()
static int decode_rle (AVCodecContext * avctx, AVFrame * p, GetByteContext * gbc, int step) static
Definition at line 69 of file qdrw.c.
Referenced by decode_frame().
check_header()
static int check_header (const char * buf, int buf_size) static
Definition at line 121 of file qdrw.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 144 of file qdrw.c.
Variable Documentation
ff_qdraw_decoder
AVCodec ff_qdraw_decoder
Initial value:
= {
    .name           = "qdraw",
    .long_name      = NULL_IF_CONFIG_SMALL("Apple QuickDraw"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_QDRAW,
    .decode         = decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 334 of file qdrw.c.