FFmpeg: libavcodec/qpeg.c File Reference
qpeg.c File Reference
QPEG codec.
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
Data Structures
struct QpegContext
Functions
static void qpeg_decode_intra (QpegContext *qctx, uint8_t *dst, int stride, int width, int height)
static void av_noinline qpeg_decode_inter (QpegContext *qctx, uint8_t *dst, int stride, int width, int height, int delta, const uint8_t *ctable, uint8_t *refdata)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static void decode_flush (AVCodecContext *avctx)
static av_cold int decode_end (AVCodecContext *avctx)
static av_cold int decode_init (AVCodecContext *avctx)
Variables
static const int qpeg_table_h [16]
static const int qpeg_table_w [16]
AVCodec ff_qpeg_decoder
Detailed Description
QPEG codec.
Definition in file qpeg.c.
Function Documentation
qpeg_decode_intra()
static void qpeg_decode_intra (QpegContext * qctx, uint8_t * dst, int stride, int width, int height) static
Definition at line 38 of file qpeg.c.
Referenced by decode_frame().
qpeg_decode_inter()
static void av_noinline qpeg_decode_inter (QpegContext * qctx, uint8_t * dst, int stride, int width, int height, int delta, const uint8_t * ctable, uint8_t * refdata) static
Definition at line 113 of file qpeg.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 253 of file qpeg.c.
decode_flush()
static void decode_flush (AVCodecContext * avctx) static
Definition at line 307 of file qpeg.c.
Referenced by decode_init().
decode_end()
static av_cold int decode_end (AVCodecContext * avctx) static
Definition at line 319 of file qpeg.c.
Referenced by decode_init().
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 329 of file qpeg.c.
Variable Documentation
qpeg_table_h
const int qpeg_table_h[16] static
Initial value:
=
 { 0x00, 0x20, 0x20, 0x20, 0x18, 0x10, 0x10, 0x20, 0x10, 0x08, 0x18, 0x08, 0x08, 0x18, 0x10, 0x04}
Definition at line 107 of file qpeg.c.
Referenced by qpeg_decode_inter().
qpeg_table_w
const int qpeg_table_w[16] static
Initial value:
=
 { 0x00, 0x20, 0x18, 0x08, 0x18, 0x10, 0x20, 0x10, 0x08, 0x10, 0x20, 0x20, 0x08, 0x10, 0x18, 0x04}
Definition at line 109 of file qpeg.c.
Referenced by qpeg_decode_inter().
ff_qpeg_decoder
AVCodec ff_qpeg_decoder
Initial value:
= {
    .name           = "qpeg",
    .long_name      = NULL_IF_CONFIG_SMALL("Q-team QPEG"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_QPEG,
    .priv_data_size = sizeof(QpegContext),
    .init           = decode_init,
    .close          = decode_end,
    .decode         = decode_frame,
    .flush          = decode_flush,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 347 of file qpeg.c.