FFmpeg: libavcodec/mips/qpeldsp_msa.c File Reference
qpeldsp_msa.c File Reference
#include "libavutil/mips/generic_macros_msa.h"
#include "qpeldsp_mips.h"
Macros
#define APPLY_HORIZ_QPEL_FILTER(inp0, inp1, mask, coef0, coef1, coef2)
#define APPLY_HORIZ_QPEL_FILTER_8BYTE(inp0, inp1, mask0, mask1, mask2, mask3, coef0, coef1, coef2)
#define APPLY_HORIZ_QPEL_FILTER_8BYTE_1ROW(inp0, mask0, mask1, mask2, mask3, coef0, coef1, coef2)
#define APPLY_HORIZ_QPEL_NO_ROUND_FILTER_8BYTE_1ROW(inp0, mask0, mask1, mask2, mask3, coef0, coef1, coef2)
#define APPLY_HORIZ_QPEL_NO_ROUND_FILTER(inp0, inp1, mask, coef0, coef1, coef2)
#define APPLY_HORIZ_QPEL_NO_ROUND_FILTER_8BYTE(inp0, inp1, mask0, mask1, mask2, mask3, coef0, coef1, coef2)
#define APPLY_VERT_QPEL_FILTER(inp0, inp1, inp2, inp3, inp4, inp5, inp6, inp7, coef0, coef1, coef2)
#define APPLY_VERT_QPEL_FILTER_8BYTE(inp00, inp01, inp02, inp03, inp04, inp05, inp06, inp07, inp10, inp11, inp12, inp13, inp14, inp15, inp16, inp17, coef0, coef1, coef2)
#define APPLY_VERT_QPEL_NO_ROUND_FILTER(inp0, inp1, inp2, inp3, inp4, inp5, inp6, inp7, coef0, coef1, coef2)
#define APPLY_VERT_QPEL_NO_ROUND_FILTER_8BYTE(inp00, inp01, inp02, inp03, inp04, inp05, inp06, inp07, inp10, inp11, inp12, inp13, inp14, inp15, inp16, inp17, coef0, coef1, coef2)
Functions
static void horiz_mc_qpel_aver_src0_8width_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void horiz_mc_qpel_aver_src0_16width_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void horiz_mc_qpel_8width_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void horiz_mc_qpel_16width_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void horiz_mc_qpel_aver_src1_8width_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void horiz_mc_qpel_aver_src1_16width_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void horiz_mc_qpel_no_rnd_aver_src0_8width_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void horiz_mc_qpel_no_rnd_aver_src0_16width_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void horiz_mc_qpel_no_rnd_8width_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void horiz_mc_qpel_no_rnd_16width_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void horiz_mc_qpel_no_rnd_aver_src1_8width_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void horiz_mc_qpel_no_rnd_aver_src1_16width_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void horiz_mc_qpel_avg_dst_aver_src0_8width_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void horiz_mc_qpel_avg_dst_aver_src0_16width_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void horiz_mc_qpel_avg_dst_8width_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void horiz_mc_qpel_avg_dst_16width_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void horiz_mc_qpel_avg_dst_aver_src1_8width_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void horiz_mc_qpel_avg_dst_aver_src1_16width_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void vert_mc_qpel_aver_src0_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void vert_mc_qpel_aver_src0_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void vert_mc_qpel_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void vert_mc_qpel_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void vert_mc_qpel_aver_src1_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void vert_mc_qpel_aver_src1_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void vert_mc_qpel_no_rnd_aver_src0_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void vert_mc_qpel_no_rnd_aver_src0_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void vert_mc_qpel_no_rnd_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void vert_mc_qpel_no_rnd_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void vert_mc_qpel_no_rnd_aver_src1_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void vert_mc_qpel_no_rnd_aver_src1_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void vert_mc_qpel_avg_dst_aver_src0_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void vert_mc_qpel_avg_dst_aver_src0_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void vert_mc_qpel_avg_dst_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void vert_mc_qpel_avg_dst_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void vert_mc_qpel_avg_dst_aver_src1_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void vert_mc_qpel_avg_dst_aver_src1_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_no_rnd_horiz_src0_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void hv_mc_qpel_no_rnd_aver_hv_src00_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_no_rnd_aver_hv_src00_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_no_rnd_horiz_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void hv_mc_qpel_no_rnd_aver_v_src0_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_no_rnd_aver_v_src0_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_no_rnd_horiz_src1_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void hv_mc_qpel_no_rnd_aver_hv_src10_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_no_rnd_aver_hv_src10_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_no_rnd_aver_h_src0_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_no_rnd_aver_h_src0_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_no_rnd_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_no_rnd_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_no_rnd_aver_h_src1_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_no_rnd_aver_h_src1_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_no_rnd_aver_hv_src01_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_no_rnd_aver_hv_src01_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_no_rnd_aver_v_src1_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_no_rnd_aver_v_src1_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_no_rnd_aver_hv_src11_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_no_rnd_aver_hv_src11_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_aver_horiz_src0_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void hv_mc_qpel_aver_hv_src00_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_aver_hv_src00_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_aver_horiz_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void hv_mc_qpel_aver_v_src0_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_aver_v_src0_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_aver_horiz_src1_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void hv_mc_qpel_aver_hv_src10_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_aver_hv_src10_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_aver_h_src0_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_aver_h_src0_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_aver_h_src1_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_aver_h_src1_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_aver_hv_src01_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_aver_hv_src01_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_aver_v_src1_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_aver_v_src1_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_aver_hv_src11_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_aver_hv_src11_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_avg_dst_aver_hv_src00_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_avg_dst_aver_hv_src00_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_avg_dst_aver_v_src0_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_avg_dst_aver_v_src0_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_avg_dst_aver_hv_src10_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_avg_dst_aver_hv_src10_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_avg_dst_aver_h_src0_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_avg_dst_aver_h_src0_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_avg_dst_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_avg_dst_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_avg_dst_aver_h_src1_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_avg_dst_aver_h_src1_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_avg_dst_aver_hv_src01_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_avg_dst_aver_hv_src01_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_avg_dst_aver_v_src1_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_avg_dst_aver_v_src1_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_avg_dst_aver_hv_src11_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void hv_mc_qpel_avg_dst_aver_hv_src11_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void copy_8x8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void copy_16x16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride)
static void avg_width8_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
static void avg_width16_msa (const uint8_t *src, int32_t src_stride, uint8_t *dst, int32_t dst_stride, int32_t height)
void ff_copy_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_copy_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_horiz_mc_qpel_aver_src0_8width_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_horiz_mc_qpel_aver_src0_16width_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_horiz_mc_qpel_8width_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_horiz_mc_qpel_16width_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_horiz_mc_qpel_aver_src1_8width_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_horiz_mc_qpel_aver_src1_16width_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_horiz_mc_qpel_no_rnd_aver_src0_8width_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_horiz_mc_qpel_no_rnd_aver_src0_16width_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_horiz_mc_qpel_no_rnd_8width_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_horiz_mc_qpel_no_rnd_16width_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_horiz_mc_qpel_no_rnd_aver_src1_8width_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_horiz_mc_qpel_no_rnd_aver_src1_16width_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_avg_width8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_avg_width16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_horiz_mc_qpel_avg_dst_aver_src0_8width_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_horiz_mc_qpel_avg_dst_aver_src0_16width_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_horiz_mc_qpel_avg_dst_8width_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_horiz_mc_qpel_avg_dst_16width_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_horiz_mc_qpel_avg_dst_aver_src1_8width_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_horiz_mc_qpel_avg_dst_aver_src1_16width_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_vert_mc_qpel_aver_src0_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_vert_mc_qpel_aver_src0_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_vert_mc_qpel_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_vert_mc_qpel_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_vert_mc_qpel_aver_src1_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_vert_mc_qpel_aver_src1_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_vert_mc_qpel_no_rnd_aver_src0_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_vert_mc_qpel_no_rnd_aver_src0_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_vert_mc_qpel_no_rnd_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_vert_mc_qpel_no_rnd_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_vert_mc_qpel_no_rnd_aver_src1_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_vert_mc_qpel_no_rnd_aver_src1_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_vert_mc_qpel_avg_dst_aver_src0_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_vert_mc_qpel_avg_dst_aver_src0_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_vert_mc_qpel_avg_dst_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_vert_mc_qpel_avg_dst_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_vert_mc_qpel_avg_dst_aver_src1_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_vert_mc_qpel_avg_dst_aver_src1_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_aver_hv_src00_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_aver_hv_src00_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_aver_v_src0_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_aver_v_src0_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_aver_hv_src10_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_aver_hv_src10_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_aver_h_src0_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_aver_h_src0_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_aver_h_src1_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_aver_h_src1_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_aver_hv_src01_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_aver_hv_src01_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_aver_v_src1_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_aver_v_src1_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_aver_hv_src11_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_aver_hv_src11_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_avg_dst_aver_hv_src00_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_avg_dst_aver_hv_src00_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_avg_dst_aver_v_src0_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_avg_dst_aver_v_src0_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_avg_dst_aver_hv_src10_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_avg_dst_aver_hv_src10_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_avg_dst_aver_h_src0_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_avg_dst_aver_h_src0_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_avg_dst_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_avg_dst_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_avg_dst_aver_h_src1_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_avg_dst_aver_h_src1_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_avg_dst_aver_hv_src01_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_avg_dst_aver_hv_src01_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_avg_dst_aver_v_src1_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_avg_dst_aver_v_src1_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_avg_dst_aver_hv_src11_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_avg_dst_aver_hv_src11_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_no_rnd_aver_hv_src00_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_no_rnd_aver_hv_src00_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_no_rnd_aver_v_src0_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_no_rnd_aver_v_src0_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_no_rnd_aver_hv_src10_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_no_rnd_aver_hv_src10_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_no_rnd_aver_h_src0_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_no_rnd_aver_h_src0_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_no_rnd_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_no_rnd_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_no_rnd_aver_h_src1_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_no_rnd_aver_h_src1_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_no_rnd_aver_hv_src01_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_no_rnd_aver_hv_src01_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_no_rnd_aver_v_src1_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_no_rnd_aver_v_src1_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_no_rnd_aver_hv_src11_16x16_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
void ff_hv_mc_qpel_no_rnd_aver_hv_src11_8x8_msa (uint8_t *dest, const uint8_t *src, ptrdiff_t stride)
Macro Definition Documentation
APPLY_HORIZ_QPEL_FILTER
#define APPLY_HORIZ_QPEL_FILTER (inp0, inp1, mask, coef0, coef1, coef2)
Definition at line 24 of file qpeldsp_msa.c.
Referenced by horiz_mc_qpel_16width_msa(), horiz_mc_qpel_aver_src0_16width_msa(), horiz_mc_qpel_aver_src1_16width_msa(), horiz_mc_qpel_avg_dst_16width_msa(), horiz_mc_qpel_avg_dst_aver_src0_16width_msa(), horiz_mc_qpel_avg_dst_aver_src1_16width_msa(), hv_mc_qpel_aver_horiz_16x16_msa(), hv_mc_qpel_aver_horiz_src0_16x16_msa(), and hv_mc_qpel_aver_horiz_src1_16x16_msa().
APPLY_HORIZ_QPEL_FILTER_8BYTE
#define APPLY_HORIZ_QPEL_FILTER_8BYTE (inp0, inp1, mask0, mask1, mask2, mask3, coef0, coef1, coef2)
Value:
({                                                                     \
    v16u8 out;                                                          \
    v8u16 sum0_r, sum1_r, sum2_r, sum3_r;                               \
    v8u16 sum4_r, sum5_r, sum6_r, sum7_r;                               \
    v8i16 res0_r, res1_r;                                               \
                                                                        \
    VSHF_B2_UH(inp0, inp0, inp1, inp1, mask0, mask0, sum0_r, sum4_r);   \
    VSHF_B2_UH(inp0, inp0, inp1, inp1, mask3, mask3, sum3_r, sum7_r);   \
    HADD_UB2_UH(sum3_r, sum7_r, sum3_r, sum7_r);                        \
    DOTP_UB2_UH(sum0_r, sum4_r, coef0, coef0, sum0_r, sum4_r);          \
    VSHF_B2_UH(inp0, inp0, inp1, inp1, mask2, mask2, sum2_r, sum6_r);   \
    VSHF_B2_UH(inp0, inp0, inp1, inp1, mask1, mask1, sum1_r, sum5_r);   \
    DPADD_UB2_UH(sum2_r, sum6_r, coef2, coef2, sum0_r, sum4_r);         \
    DPADD_UB2_UH(sum1_r, sum5_r, coef1, coef1, sum3_r, sum7_r);         \
    res0_r = (v8i16) (sum0_r - sum3_r);                                 \
    res1_r = (v8i16) (sum4_r - sum7_r);                                 \
    SRARI_H2_SH(res0_r, res1_r, 5);                                     \
    CLIP_SH2_0_255(res0_r, res1_r);                                     \
    out = (v16u8) __msa_pckev_b((v16i8) res1_r, (v16i8) res0_r);        \
                                                                        \
    out;                                                                \
})
Definition at line 58 of file qpeldsp_msa.c.
Referenced by horiz_mc_qpel_8width_msa(), horiz_mc_qpel_aver_src0_8width_msa(), horiz_mc_qpel_aver_src1_8width_msa(), horiz_mc_qpel_avg_dst_8width_msa(), horiz_mc_qpel_avg_dst_aver_src0_8width_msa(), horiz_mc_qpel_avg_dst_aver_src1_8width_msa(), hv_mc_qpel_8x8_msa(), hv_mc_qpel_aver_h_src0_8x8_msa(), hv_mc_qpel_aver_h_src1_8x8_msa(), hv_mc_qpel_aver_hv_src00_8x8_msa(), hv_mc_qpel_aver_hv_src01_8x8_msa(), hv_mc_qpel_aver_hv_src10_8x8_msa(), hv_mc_qpel_aver_hv_src11_8x8_msa(), hv_mc_qpel_aver_v_src0_8x8_msa(), hv_mc_qpel_aver_v_src1_8x8_msa(), hv_mc_qpel_avg_dst_8x8_msa(), hv_mc_qpel_avg_dst_aver_h_src0_8x8_msa(), hv_mc_qpel_avg_dst_aver_h_src1_8x8_msa(), hv_mc_qpel_avg_dst_aver_hv_src00_8x8_msa(), hv_mc_qpel_avg_dst_aver_hv_src01_8x8_msa(), hv_mc_qpel_avg_dst_aver_hv_src10_8x8_msa(), hv_mc_qpel_avg_dst_aver_hv_src11_8x8_msa(), hv_mc_qpel_avg_dst_aver_v_src0_8x8_msa(), and hv_mc_qpel_avg_dst_aver_v_src1_8x8_msa().
APPLY_HORIZ_QPEL_FILTER_8BYTE_1ROW
#define APPLY_HORIZ_QPEL_FILTER_8BYTE_1ROW (inp0, mask0, mask1, mask2, mask3, coef0, coef1, coef2)
Value:
({                                                                     \
    v16u8 out;                                                          \
    v8i16 res0_r;                                                       \
    v8u16 sum0_r, sum1_r, sum2_r, sum3_r;                               \
                                                                        \
    VSHF_B2_UH(inp0, inp0, inp0, inp0, mask0, mask3, sum0_r, sum3_r);   \
    sum3_r = __msa_hadd_u_h((v16u8) sum3_r, (v16u8) sum3_r);            \
    sum0_r = __msa_dotp_u_h((v16u8) sum0_r, (v16u8) coef0);             \
    VSHF_B2_UH(inp0, inp0, inp0, inp0, mask2, mask1, sum2_r, sum1_r);   \
    DPADD_UB2_UH(sum2_r, sum1_r, coef2, coef1, sum0_r, sum3_r);         \
    res0_r = (v8i16) (sum0_r - sum3_r);                                 \
    res0_r = __msa_srari_h(res0_r, 5);                                  \
    res0_r = CLIP_SH_0_255(res0_r);                                     \
    out = (v16u8) __msa_pckev_b((v16i8) res0_r, (v16i8) res0_r);        \
                                                                        \
    out;                                                                \
})
Definition at line 84 of file qpeldsp_msa.c.
Referenced by hv_mc_qpel_8x8_msa(), hv_mc_qpel_aver_h_src0_8x8_msa(), hv_mc_qpel_aver_h_src1_8x8_msa(), hv_mc_qpel_aver_hv_src00_8x8_msa(), hv_mc_qpel_aver_hv_src01_8x8_msa(), hv_mc_qpel_aver_hv_src10_8x8_msa(), hv_mc_qpel_aver_hv_src11_8x8_msa(), hv_mc_qpel_aver_v_src0_8x8_msa(), hv_mc_qpel_aver_v_src1_8x8_msa(), hv_mc_qpel_avg_dst_8x8_msa(), hv_mc_qpel_avg_dst_aver_h_src0_8x8_msa(), hv_mc_qpel_avg_dst_aver_h_src1_8x8_msa(), hv_mc_qpel_avg_dst_aver_hv_src00_8x8_msa(), hv_mc_qpel_avg_dst_aver_hv_src01_8x8_msa(), hv_mc_qpel_avg_dst_aver_hv_src10_8x8_msa(), hv_mc_qpel_avg_dst_aver_hv_src11_8x8_msa(), hv_mc_qpel_avg_dst_aver_v_src0_8x8_msa(), and hv_mc_qpel_avg_dst_aver_v_src1_8x8_msa().
APPLY_HORIZ_QPEL_NO_ROUND_FILTER_8BYTE_1ROW
#define APPLY_HORIZ_QPEL_NO_ROUND_FILTER_8BYTE_1ROW (inp0, mask0, mask1, mask2, mask3, coef0, coef1, coef2)
Value:
({                                                                       \
    v16u8 out;                                                            \
    v8i16 res0_r;                                                         \
    v8u16 sum0_r, sum1_r, sum2_r, sum3_r;                                 \
                                                                          \
    VSHF_B2_UH(inp0, inp0, inp0, inp0, mask0, mask3, sum0_r, sum3_r);     \
    sum3_r = __msa_hadd_u_h((v16u8) sum3_r, (v16u8) sum3_r);              \
    sum0_r = __msa_dotp_u_h((v16u8) sum0_r, (v16u8) coef0);               \
    VSHF_B2_UH(inp0, inp0, inp0, inp0, mask2, mask1, sum2_r, sum1_r);     \
    DPADD_UB2_UH(sum2_r, sum1_r, coef2, coef1, sum0_r, sum3_r);           \
    res0_r = (v8i16) (sum0_r - sum3_r);                                   \
    res0_r += 15;                                                         \
    res0_r >>= 5;                                                         \
    res0_r = CLIP_SH_0_255(res0_r);                                       \
    out = (v16u8) __msa_pckev_b((v16i8) res0_r, (v16i8) res0_r);          \
                                                                          \
    out;                                                                  \
})
Definition at line 105 of file qpeldsp_msa.c.
Referenced by hv_mc_qpel_no_rnd_8x8_msa(), hv_mc_qpel_no_rnd_aver_h_src0_8x8_msa(), hv_mc_qpel_no_rnd_aver_h_src1_8x8_msa(), hv_mc_qpel_no_rnd_aver_hv_src00_8x8_msa(), hv_mc_qpel_no_rnd_aver_hv_src01_8x8_msa(), hv_mc_qpel_no_rnd_aver_hv_src10_8x8_msa(), hv_mc_qpel_no_rnd_aver_hv_src11_8x8_msa(), hv_mc_qpel_no_rnd_aver_v_src0_8x8_msa(), and hv_mc_qpel_no_rnd_aver_v_src1_8x8_msa().
APPLY_HORIZ_QPEL_NO_ROUND_FILTER
#define APPLY_HORIZ_QPEL_NO_ROUND_FILTER (inp0, inp1, mask, coef0, coef1, coef2)
Definition at line 127 of file qpeldsp_msa.c.
Referenced by horiz_mc_qpel_no_rnd_16width_msa(), horiz_mc_qpel_no_rnd_aver_src0_16width_msa(), horiz_mc_qpel_no_rnd_aver_src1_16width_msa(), hv_mc_qpel_no_rnd_horiz_16x16_msa(), hv_mc_qpel_no_rnd_horiz_src0_16x16_msa(), and hv_mc_qpel_no_rnd_horiz_src1_16x16_msa().
APPLY_HORIZ_QPEL_NO_ROUND_FILTER_8BYTE
#define APPLY_HORIZ_QPEL_NO_ROUND_FILTER_8BYTE (inp0, inp1, mask0, mask1, mask2, mask3, coef0, coef1, coef2)
Value:
({                                                                         \
    v16u8 out;                                                              \
    v8i16 res0_r, res1_r;                                                   \
    v8u16 sum0_r, sum1_r, sum2_r, sum3_r;                                   \
    v8u16 sum4_r, sum5_r, sum6_r, sum7_r;                                   \
                                                                            \
    VSHF_B2_UH(inp0, inp0, inp1, inp1, mask0, mask0, sum0_r, sum4_r);       \
    VSHF_B2_UH(inp0, inp0, inp1, inp1, mask3, mask3, sum3_r, sum7_r);       \
    HADD_UB2_UH(sum3_r, sum7_r, sum3_r, sum7_r);                            \
    DOTP_UB2_UH(sum0_r, sum4_r, coef0, coef0, sum0_r, sum4_r);              \
    VSHF_B2_UH(inp0, inp0, inp1, inp1, mask2, mask2, sum2_r, sum6_r);       \
    VSHF_B2_UH(inp0, inp0, inp1, inp1, mask1, mask1, sum1_r, sum5_r);       \
    DPADD_UB2_UH(sum2_r, sum6_r, coef2, coef2, sum0_r, sum4_r);             \
    DPADD_UB2_UH(sum1_r, sum5_r, coef1, coef1, sum3_r, sum7_r);             \
    res0_r = (v8i16) (sum0_r - sum3_r);                                     \
    res1_r = (v8i16) (sum4_r - sum7_r);                                     \
    res0_r += 15;                                                           \
    res1_r += 15;                                                           \
    res0_r >>= 5;                                                           \
    res1_r >>= 5;                                                           \
    CLIP_SH2_0_255(res0_r, res1_r);                                         \
    out = (v16u8) __msa_pckev_b((v16i8) res1_r, (v16i8) res0_r);            \
                                                                            \
    out;                                                                    \
})
Definition at line 165 of file qpeldsp_msa.c.
Referenced by horiz_mc_qpel_no_rnd_8width_msa(), horiz_mc_qpel_no_rnd_aver_src0_8width_msa(), horiz_mc_qpel_no_rnd_aver_src1_8width_msa(), hv_mc_qpel_no_rnd_8x8_msa(), hv_mc_qpel_no_rnd_aver_h_src0_8x8_msa(), hv_mc_qpel_no_rnd_aver_h_src1_8x8_msa(), hv_mc_qpel_no_rnd_aver_hv_src00_8x8_msa(), hv_mc_qpel_no_rnd_aver_hv_src01_8x8_msa(), hv_mc_qpel_no_rnd_aver_hv_src10_8x8_msa(), hv_mc_qpel_no_rnd_aver_hv_src11_8x8_msa(), hv_mc_qpel_no_rnd_aver_v_src0_8x8_msa(), and hv_mc_qpel_no_rnd_aver_v_src1_8x8_msa().
APPLY_VERT_QPEL_FILTER
#define APPLY_VERT_QPEL_FILTER (inp0, inp1, inp2, inp3, inp4, inp5, inp6, inp7, coef0, coef1, coef2)
Value:
({                                                                     \
    v16u8 res;                                                          \
    v8i16 res_r, res_l;                                                 \
    v8u16 sum0_r, sum1_r, sum2_r, sum3_r;                               \
    v8u16 sum0_l, sum1_l, sum2_l, sum3_l;                               \
                                                                        \
    ILVRL_B2_UH(inp4, inp0, sum0_r, sum0_l);                            \
    ILVRL_B2_UH(inp7, inp3, sum3_r, sum3_l);                            \
    DOTP_UB2_UH(sum0_r, sum0_l, coef0, coef0, sum0_r, sum0_l);          \
    HADD_UB2_UH(sum3_r, sum3_l, sum3_r, sum3_l);                        \
    ILVRL_B2_UH(inp6, inp2, sum2_r, sum2_l);                            \
    ILVRL_B2_UH(inp5, inp1, sum1_r, sum1_l);                            \
    DPADD_UB2_UH(sum2_r, sum2_l, coef2, coef2, sum0_r, sum0_l);         \
    DPADD_UB2_UH(sum1_r, sum1_l, coef1, coef1, sum3_r, sum3_l);         \
    res_r = (v8i16) (sum0_r - sum3_r);                                  \
    res_l = (v8i16) (sum0_l - sum3_l);                                  \
    SRARI_H2_SH(res_r, res_l, 5);                                       \
    CLIP_SH2_0_255(res_r, res_l);                                       \
    res = (v16u8) __msa_pckev_b((v16i8) res_l, (v16i8) res_r);          \
                                                                        \
    res;                                                                \
})
Definition at line 194 of file qpeldsp_msa.c.
Referenced by vert_mc_qpel_16x16_msa(), vert_mc_qpel_aver_src0_16x16_msa(), vert_mc_qpel_aver_src1_16x16_msa(), vert_mc_qpel_avg_dst_16x16_msa(), vert_mc_qpel_avg_dst_aver_src0_16x16_msa(), and vert_mc_qpel_avg_dst_aver_src1_16x16_msa().
APPLY_VERT_QPEL_FILTER_8BYTE
#define APPLY_VERT_QPEL_FILTER_8BYTE (inp00, inp01, inp02, inp03, inp04, inp05, inp06, inp07, inp10, inp11, inp12, inp13, inp14, inp15, inp16, inp17, coef0, coef1, coef2)
Value:
({                                                                     \
    v16u8 res;                                                          \
    v8i16 val0, val1;                                                   \
    v8u16 sum00, sum01, sum02, sum03;                                   \
    v8u16 sum10, sum11, sum12, sum13;                                   \
                                                                        \
    ILVR_B4_UH(inp04, inp00, inp14, inp10, inp07, inp03, inp17, inp13,  \
               sum00, sum10, sum03, sum13);                             \
    DOTP_UB2_UH(sum00, sum10, coef0, coef0, sum00, sum10);              \
    HADD_UB2_UH(sum03, sum13, sum03, sum13);                            \
    ILVR_B4_UH(inp06, inp02, inp16, inp12, inp05, inp01, inp15, inp11,  \
               sum02, sum12, sum01, sum11);                             \
    DPADD_UB2_UH(sum02, sum12, coef2, coef2, sum00, sum10);             \
    DPADD_UB2_UH(sum01, sum11, coef1, coef1, sum03, sum13);             \
    val0 = (v8i16) (sum00 - sum03);                                     \
    val1 = (v8i16) (sum10 - sum13);                                     \
    SRARI_H2_SH(val0, val1, 5);                                         \
    CLIP_SH2_0_255(val0, val1);                                         \
    res = (v16u8) __msa_pckev_b((v16i8) val1, (v16i8) val0);            \
                                                                        \
    res;                                                                \
})
Definition at line 220 of file qpeldsp_msa.c.
Referenced by hv_mc_qpel_8x8_msa(), hv_mc_qpel_aver_h_src0_8x8_msa(), hv_mc_qpel_aver_h_src1_8x8_msa(), hv_mc_qpel_aver_hv_src00_8x8_msa(), hv_mc_qpel_aver_hv_src01_8x8_msa(), hv_mc_qpel_aver_hv_src10_8x8_msa(), hv_mc_qpel_aver_hv_src11_8x8_msa(), hv_mc_qpel_aver_v_src0_8x8_msa(), hv_mc_qpel_aver_v_src1_8x8_msa(), hv_mc_qpel_avg_dst_8x8_msa(), hv_mc_qpel_avg_dst_aver_h_src0_8x8_msa(), hv_mc_qpel_avg_dst_aver_h_src1_8x8_msa(), hv_mc_qpel_avg_dst_aver_hv_src00_8x8_msa(), hv_mc_qpel_avg_dst_aver_hv_src01_8x8_msa(), hv_mc_qpel_avg_dst_aver_hv_src10_8x8_msa(), hv_mc_qpel_avg_dst_aver_hv_src11_8x8_msa(), hv_mc_qpel_avg_dst_aver_v_src0_8x8_msa(), hv_mc_qpel_avg_dst_aver_v_src1_8x8_msa(), vert_mc_qpel_8x8_msa(), vert_mc_qpel_aver_src0_8x8_msa(), vert_mc_qpel_aver_src1_8x8_msa(), vert_mc_qpel_avg_dst_8x8_msa(), vert_mc_qpel_avg_dst_aver_src0_8x8_msa(), and vert_mc_qpel_avg_dst_aver_src1_8x8_msa().
APPLY_VERT_QPEL_NO_ROUND_FILTER
#define APPLY_VERT_QPEL_NO_ROUND_FILTER (inp0, inp1, inp2, inp3, inp4, inp5, inp6, inp7, coef0, coef1, coef2)
Value:
({                                                                     \
    v16u8 res;                                                          \
    v8i16 res_r, res_l;                                                 \
    v8u16 sum0_r, sum1_r, sum2_r, sum3_r;                               \
    v8u16 sum0_l, sum1_l, sum2_l, sum3_l;                               \
                                                                        \
    ILVRL_B2_UH(inp4, inp0, sum0_r, sum0_l);                            \
    ILVRL_B2_UH(inp7, inp3, sum3_r, sum3_l);                            \
    DOTP_UB2_UH(sum0_r, sum0_l, coef0, coef0, sum0_r, sum0_l);          \
    HADD_UB2_UH(sum3_r, sum3_l, sum3_r, sum3_l);                        \
    ILVRL_B2_UH(inp6, inp2, sum2_r, sum2_l);                            \
    ILVRL_B2_UH(inp5, inp1, sum1_r, sum1_l);                            \
    DPADD_UB2_UH(sum2_r, sum2_l, coef2, coef2, sum0_r, sum0_l);         \
    DPADD_UB2_UH(sum1_r, sum1_l, coef1, coef1, sum3_r, sum3_l);         \
    res_r = (v8i16) (sum0_r - sum3_r);                                  \
    res_l = (v8i16) (sum0_l - sum3_l);                                  \
    res_r += 15;                                                        \
    res_l += 15;                                                        \
    res_r >>= 5;                                                        \
    res_l >>= 5;                                                        \
    CLIP_SH2_0_255(res_r, res_l);                                       \
    res = (v16u8) __msa_pckev_b((v16i8) res_l, (v16i8) res_r);          \
                                                                        \
    res;                                                                \
})
Definition at line 248 of file qpeldsp_msa.c.
Referenced by vert_mc_qpel_no_rnd_16x16_msa(), vert_mc_qpel_no_rnd_aver_src0_16x16_msa(), and vert_mc_qpel_no_rnd_aver_src1_16x16_msa().
APPLY_VERT_QPEL_NO_ROUND_FILTER_8BYTE
#define APPLY_VERT_QPEL_NO_ROUND_FILTER_8BYTE (inp00, inp01, inp02, inp03, inp04, inp05, inp06, inp07, inp10, inp11, inp12, inp13, inp14, inp15, inp16, inp17, coef0, coef1, coef2)
Value:
({                                                                        \
    v16u8 res;                                                             \
    v8i16 val0, val1;                                                      \
    v8u16 sum00, sum01, sum02, sum03;                                      \
    v8u16 sum10, sum11, sum12, sum13;                                      \
                                                                           \
    ILVR_B4_UH(inp04, inp00, inp14, inp10, inp07, inp03, inp17, inp13,     \
               sum00, sum10, sum03, sum13);                                \
    DOTP_UB2_UH(sum00, sum10, coef0, coef0, sum00, sum10);                 \
    HADD_UB2_UH(sum03, sum13, sum03, sum13);                               \
    ILVR_B4_UH(inp06, inp02, inp16, inp12, inp05, inp01, inp15, inp11,     \
               sum02, sum12, sum01, sum11);                                \
    DPADD_UB2_UH(sum02, sum12, coef2, coef2, sum00, sum10);                \
    DPADD_UB2_UH(sum01, sum11, coef1, coef1, sum03, sum13);                \
    val0 = (v8i16) (sum00 - sum03);                                        \
    val1 = (v8i16) (sum10 - sum13);                                        \
    val0 += 15;                                                            \
    val1 += 15;                                                            \
    val0 >>= 5;                                                            \
    val1 >>= 5;                                                            \
    CLIP_SH2_0_255(val0, val1);                                            \
    res = (v16u8) __msa_pckev_b((v16i8) val1, (v16i8) val0);               \
                                                                           \
    res;                                                                   \
})
Definition at line 277 of file qpeldsp_msa.c.
Referenced by hv_mc_qpel_no_rnd_8x8_msa(), hv_mc_qpel_no_rnd_aver_h_src0_8x8_msa(), hv_mc_qpel_no_rnd_aver_h_src1_8x8_msa(), hv_mc_qpel_no_rnd_aver_hv_src00_8x8_msa(), hv_mc_qpel_no_rnd_aver_hv_src01_8x8_msa(), hv_mc_qpel_no_rnd_aver_hv_src10_8x8_msa(), hv_mc_qpel_no_rnd_aver_hv_src11_8x8_msa(), hv_mc_qpel_no_rnd_aver_v_src0_8x8_msa(), hv_mc_qpel_no_rnd_aver_v_src1_8x8_msa(), vert_mc_qpel_no_rnd_8x8_msa(), vert_mc_qpel_no_rnd_aver_src0_8x8_msa(), and vert_mc_qpel_no_rnd_aver_src1_8x8_msa().
Function Documentation
horiz_mc_qpel_aver_src0_8width_msa()
static void horiz_mc_qpel_aver_src0_8width_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 308 of file qpeldsp_msa.c.
Referenced by ff_horiz_mc_qpel_aver_src0_8width_msa().
horiz_mc_qpel_aver_src0_16width_msa()
static void horiz_mc_qpel_aver_src0_16width_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 342 of file qpeldsp_msa.c.
Referenced by ff_horiz_mc_qpel_aver_src0_16width_msa().
horiz_mc_qpel_8width_msa()
static void horiz_mc_qpel_8width_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 386 of file qpeldsp_msa.c.
Referenced by ff_horiz_mc_qpel_8width_msa().
horiz_mc_qpel_16width_msa()
static void horiz_mc_qpel_16width_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 417 of file qpeldsp_msa.c.
Referenced by ff_horiz_mc_qpel_16width_msa().
horiz_mc_qpel_aver_src1_8width_msa()
static void horiz_mc_qpel_aver_src1_8width_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 457 of file qpeldsp_msa.c.
Referenced by ff_horiz_mc_qpel_aver_src1_8width_msa().
horiz_mc_qpel_aver_src1_16width_msa()
static void horiz_mc_qpel_aver_src1_16width_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 493 of file qpeldsp_msa.c.
Referenced by ff_horiz_mc_qpel_aver_src1_16width_msa().
horiz_mc_qpel_no_rnd_aver_src0_8width_msa()
static void horiz_mc_qpel_no_rnd_aver_src0_8width_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 537 of file qpeldsp_msa.c.
Referenced by ff_horiz_mc_qpel_no_rnd_aver_src0_8width_msa().
horiz_mc_qpel_no_rnd_aver_src0_16width_msa()
static void horiz_mc_qpel_no_rnd_aver_src0_16width_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 572 of file qpeldsp_msa.c.
Referenced by ff_horiz_mc_qpel_no_rnd_aver_src0_16width_msa().
horiz_mc_qpel_no_rnd_8width_msa()
static void horiz_mc_qpel_no_rnd_8width_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 616 of file qpeldsp_msa.c.
Referenced by ff_horiz_mc_qpel_no_rnd_8width_msa().
horiz_mc_qpel_no_rnd_16width_msa()
static void horiz_mc_qpel_no_rnd_16width_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 647 of file qpeldsp_msa.c.
Referenced by ff_horiz_mc_qpel_no_rnd_16width_msa().
horiz_mc_qpel_no_rnd_aver_src1_8width_msa()
static void horiz_mc_qpel_no_rnd_aver_src1_8width_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 687 of file qpeldsp_msa.c.
Referenced by ff_horiz_mc_qpel_no_rnd_aver_src1_8width_msa().
horiz_mc_qpel_no_rnd_aver_src1_16width_msa()
static void horiz_mc_qpel_no_rnd_aver_src1_16width_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 724 of file qpeldsp_msa.c.
Referenced by ff_horiz_mc_qpel_no_rnd_aver_src1_16width_msa().
horiz_mc_qpel_avg_dst_aver_src0_8width_msa()
static void horiz_mc_qpel_avg_dst_aver_src0_8width_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 768 of file qpeldsp_msa.c.
Referenced by ff_horiz_mc_qpel_avg_dst_aver_src0_8width_msa().
horiz_mc_qpel_avg_dst_aver_src0_16width_msa()
static void horiz_mc_qpel_avg_dst_aver_src0_16width_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 807 of file qpeldsp_msa.c.
Referenced by ff_horiz_mc_qpel_avg_dst_aver_src0_16width_msa().
horiz_mc_qpel_avg_dst_8width_msa()
static void horiz_mc_qpel_avg_dst_8width_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 848 of file qpeldsp_msa.c.
Referenced by ff_horiz_mc_qpel_avg_dst_8width_msa().
horiz_mc_qpel_avg_dst_16width_msa()
static void horiz_mc_qpel_avg_dst_16width_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 884 of file qpeldsp_msa.c.
Referenced by ff_horiz_mc_qpel_avg_dst_16width_msa().
horiz_mc_qpel_avg_dst_aver_src1_8width_msa()
static void horiz_mc_qpel_avg_dst_aver_src1_8width_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 923 of file qpeldsp_msa.c.
Referenced by ff_horiz_mc_qpel_avg_dst_aver_src1_8width_msa().
horiz_mc_qpel_avg_dst_aver_src1_16width_msa()
static void horiz_mc_qpel_avg_dst_aver_src1_16width_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 964 of file qpeldsp_msa.c.
Referenced by ff_horiz_mc_qpel_avg_dst_aver_src1_16width_msa().
vert_mc_qpel_aver_src0_8x8_msa()
static void vert_mc_qpel_aver_src0_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 1004 of file qpeldsp_msa.c.
Referenced by ff_vert_mc_qpel_aver_src0_8x8_msa().
vert_mc_qpel_aver_src0_16x16_msa()
static void vert_mc_qpel_aver_src0_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 1055 of file qpeldsp_msa.c.
Referenced by ff_vert_mc_qpel_aver_src0_16x16_msa(), hv_mc_qpel_aver_hv_src00_16x16_msa(), hv_mc_qpel_aver_hv_src10_16x16_msa(), and hv_mc_qpel_aver_v_src0_16x16_msa().
vert_mc_qpel_8x8_msa()
static void vert_mc_qpel_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 1196 of file qpeldsp_msa.c.
Referenced by ff_vert_mc_qpel_8x8_msa().
vert_mc_qpel_16x16_msa()
static void vert_mc_qpel_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 1241 of file qpeldsp_msa.c.
Referenced by ff_vert_mc_qpel_16x16_msa(), hv_mc_qpel_16x16_msa(), hv_mc_qpel_aver_h_src0_16x16_msa(), and hv_mc_qpel_aver_h_src1_16x16_msa().
vert_mc_qpel_aver_src1_8x8_msa()
static void vert_mc_qpel_aver_src1_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 1377 of file qpeldsp_msa.c.
Referenced by ff_vert_mc_qpel_aver_src1_8x8_msa().
vert_mc_qpel_aver_src1_16x16_msa()
static void vert_mc_qpel_aver_src1_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 1428 of file qpeldsp_msa.c.
Referenced by ff_vert_mc_qpel_aver_src1_16x16_msa(), hv_mc_qpel_aver_hv_src01_16x16_msa(), hv_mc_qpel_aver_hv_src11_16x16_msa(), and hv_mc_qpel_aver_v_src1_16x16_msa().
vert_mc_qpel_no_rnd_aver_src0_8x8_msa()
static void vert_mc_qpel_no_rnd_aver_src0_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 1579 of file qpeldsp_msa.c.
Referenced by ff_vert_mc_qpel_no_rnd_aver_src0_8x8_msa().
vert_mc_qpel_no_rnd_aver_src0_16x16_msa()
static void vert_mc_qpel_no_rnd_aver_src0_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 1632 of file qpeldsp_msa.c.
Referenced by ff_vert_mc_qpel_no_rnd_aver_src0_16x16_msa(), hv_mc_qpel_no_rnd_aver_hv_src00_16x16_msa(), hv_mc_qpel_no_rnd_aver_hv_src10_16x16_msa(), and hv_mc_qpel_no_rnd_aver_v_src0_16x16_msa().
vert_mc_qpel_no_rnd_8x8_msa()
static void vert_mc_qpel_no_rnd_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 1782 of file qpeldsp_msa.c.
Referenced by ff_vert_mc_qpel_no_rnd_8x8_msa().
vert_mc_qpel_no_rnd_16x16_msa()
static void vert_mc_qpel_no_rnd_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 1827 of file qpeldsp_msa.c.
Referenced by ff_vert_mc_qpel_no_rnd_16x16_msa(), hv_mc_qpel_no_rnd_16x16_msa(), hv_mc_qpel_no_rnd_aver_h_src0_16x16_msa(), and hv_mc_qpel_no_rnd_aver_h_src1_16x16_msa().
vert_mc_qpel_no_rnd_aver_src1_8x8_msa()
static void vert_mc_qpel_no_rnd_aver_src1_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 1960 of file qpeldsp_msa.c.
Referenced by ff_vert_mc_qpel_no_rnd_aver_src1_8x8_msa().
vert_mc_qpel_no_rnd_aver_src1_16x16_msa()
static void vert_mc_qpel_no_rnd_aver_src1_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 2012 of file qpeldsp_msa.c.
Referenced by ff_vert_mc_qpel_no_rnd_aver_src1_16x16_msa(), hv_mc_qpel_no_rnd_aver_hv_src01_16x16_msa(), hv_mc_qpel_no_rnd_aver_hv_src11_16x16_msa(), and hv_mc_qpel_no_rnd_aver_v_src1_16x16_msa().
vert_mc_qpel_avg_dst_aver_src0_8x8_msa()
static void vert_mc_qpel_avg_dst_aver_src0_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 2161 of file qpeldsp_msa.c.
Referenced by ff_vert_mc_qpel_avg_dst_aver_src0_8x8_msa().
vert_mc_qpel_avg_dst_aver_src0_16x16_msa()
static void vert_mc_qpel_avg_dst_aver_src0_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 2223 of file qpeldsp_msa.c.
Referenced by ff_vert_mc_qpel_avg_dst_aver_src0_16x16_msa(), hv_mc_qpel_avg_dst_aver_hv_src00_16x16_msa(), hv_mc_qpel_avg_dst_aver_hv_src10_16x16_msa(), and hv_mc_qpel_avg_dst_aver_v_src0_16x16_msa().
vert_mc_qpel_avg_dst_8x8_msa()
static void vert_mc_qpel_avg_dst_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 2355 of file qpeldsp_msa.c.
Referenced by ff_vert_mc_qpel_avg_dst_8x8_msa().
vert_mc_qpel_avg_dst_16x16_msa()
static void vert_mc_qpel_avg_dst_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 2409 of file qpeldsp_msa.c.
Referenced by ff_vert_mc_qpel_avg_dst_16x16_msa(), hv_mc_qpel_avg_dst_16x16_msa(), hv_mc_qpel_avg_dst_aver_h_src0_16x16_msa(), and hv_mc_qpel_avg_dst_aver_h_src1_16x16_msa().
vert_mc_qpel_avg_dst_aver_src1_8x8_msa()
static void vert_mc_qpel_avg_dst_aver_src1_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 2534 of file qpeldsp_msa.c.
Referenced by ff_vert_mc_qpel_avg_dst_aver_src1_8x8_msa().
vert_mc_qpel_avg_dst_aver_src1_16x16_msa()
static void vert_mc_qpel_avg_dst_aver_src1_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 2593 of file qpeldsp_msa.c.
Referenced by ff_vert_mc_qpel_avg_dst_aver_src1_16x16_msa(), hv_mc_qpel_avg_dst_aver_hv_src01_16x16_msa(), hv_mc_qpel_avg_dst_aver_hv_src11_16x16_msa(), and hv_mc_qpel_avg_dst_aver_v_src1_16x16_msa().
hv_mc_qpel_no_rnd_horiz_src0_16x16_msa()
static void hv_mc_qpel_no_rnd_horiz_src0_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 2726 of file qpeldsp_msa.c.
Referenced by hv_mc_qpel_no_rnd_aver_h_src0_16x16_msa(), hv_mc_qpel_no_rnd_aver_hv_src00_16x16_msa(), and hv_mc_qpel_no_rnd_aver_hv_src01_16x16_msa().
hv_mc_qpel_no_rnd_aver_hv_src00_16x16_msa()
static void hv_mc_qpel_no_rnd_aver_hv_src00_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 2776 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_no_rnd_aver_hv_src00_16x16_msa().
hv_mc_qpel_no_rnd_aver_hv_src00_8x8_msa()
static void hv_mc_qpel_no_rnd_aver_hv_src00_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 2787 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_no_rnd_aver_hv_src00_8x8_msa().
hv_mc_qpel_no_rnd_horiz_16x16_msa()
static void hv_mc_qpel_no_rnd_horiz_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 2881 of file qpeldsp_msa.c.
Referenced by hv_mc_qpel_no_rnd_16x16_msa(), hv_mc_qpel_no_rnd_aver_v_src0_16x16_msa(), and hv_mc_qpel_no_rnd_aver_v_src1_16x16_msa().
hv_mc_qpel_no_rnd_aver_v_src0_16x16_msa()
static void hv_mc_qpel_no_rnd_aver_v_src0_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 2926 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_no_rnd_aver_v_src0_16x16_msa().
hv_mc_qpel_no_rnd_aver_v_src0_8x8_msa()
static void hv_mc_qpel_no_rnd_aver_v_src0_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 2937 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_no_rnd_aver_v_src0_8x8_msa().
hv_mc_qpel_no_rnd_horiz_src1_16x16_msa()
static void hv_mc_qpel_no_rnd_horiz_src1_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 3025 of file qpeldsp_msa.c.
Referenced by hv_mc_qpel_no_rnd_aver_h_src1_16x16_msa(), hv_mc_qpel_no_rnd_aver_hv_src10_16x16_msa(), and hv_mc_qpel_no_rnd_aver_hv_src11_16x16_msa().
hv_mc_qpel_no_rnd_aver_hv_src10_16x16_msa()
static void hv_mc_qpel_no_rnd_aver_hv_src10_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 3075 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_no_rnd_aver_hv_src10_16x16_msa().
hv_mc_qpel_no_rnd_aver_hv_src10_8x8_msa()
static void hv_mc_qpel_no_rnd_aver_hv_src10_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 3086 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_no_rnd_aver_hv_src10_8x8_msa().
hv_mc_qpel_no_rnd_aver_h_src0_16x16_msa()
static void hv_mc_qpel_no_rnd_aver_h_src0_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 3189 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_no_rnd_aver_h_src0_16x16_msa().
hv_mc_qpel_no_rnd_aver_h_src0_8x8_msa()
static void hv_mc_qpel_no_rnd_aver_h_src0_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 3200 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_no_rnd_aver_h_src0_8x8_msa().
hv_mc_qpel_no_rnd_16x16_msa()
static void hv_mc_qpel_no_rnd_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 3287 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_no_rnd_16x16_msa().
hv_mc_qpel_no_rnd_8x8_msa()
static void hv_mc_qpel_no_rnd_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 3298 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_no_rnd_8x8_msa().
hv_mc_qpel_no_rnd_aver_h_src1_16x16_msa()
static void hv_mc_qpel_no_rnd_aver_h_src1_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 3375 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_no_rnd_aver_h_src1_16x16_msa().
hv_mc_qpel_no_rnd_aver_h_src1_8x8_msa()
static void hv_mc_qpel_no_rnd_aver_h_src1_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 3386 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_no_rnd_aver_h_src1_8x8_msa().
hv_mc_qpel_no_rnd_aver_hv_src01_16x16_msa()
static void hv_mc_qpel_no_rnd_aver_hv_src01_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 3480 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_no_rnd_aver_hv_src01_16x16_msa().
hv_mc_qpel_no_rnd_aver_hv_src01_8x8_msa()
static void hv_mc_qpel_no_rnd_aver_hv_src01_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 3491 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_no_rnd_aver_hv_src01_8x8_msa().
hv_mc_qpel_no_rnd_aver_v_src1_16x16_msa()
static void hv_mc_qpel_no_rnd_aver_v_src1_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 3586 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_no_rnd_aver_v_src1_16x16_msa().
hv_mc_qpel_no_rnd_aver_v_src1_8x8_msa()
static void hv_mc_qpel_no_rnd_aver_v_src1_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 3597 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_no_rnd_aver_v_src1_8x8_msa().
hv_mc_qpel_no_rnd_aver_hv_src11_16x16_msa()
static void hv_mc_qpel_no_rnd_aver_hv_src11_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 3682 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_no_rnd_aver_hv_src11_16x16_msa().
hv_mc_qpel_no_rnd_aver_hv_src11_8x8_msa()
static void hv_mc_qpel_no_rnd_aver_hv_src11_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 3693 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_no_rnd_aver_hv_src11_8x8_msa().
hv_mc_qpel_aver_horiz_src0_16x16_msa()
static void hv_mc_qpel_aver_horiz_src0_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 3793 of file qpeldsp_msa.c.
Referenced by hv_mc_qpel_aver_h_src0_16x16_msa(), hv_mc_qpel_aver_hv_src00_16x16_msa(), hv_mc_qpel_aver_hv_src01_16x16_msa(), hv_mc_qpel_avg_dst_aver_h_src0_16x16_msa(), hv_mc_qpel_avg_dst_aver_hv_src00_16x16_msa(), and hv_mc_qpel_avg_dst_aver_hv_src01_16x16_msa().
hv_mc_qpel_aver_hv_src00_16x16_msa()
static void hv_mc_qpel_aver_hv_src00_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 3842 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_aver_hv_src00_16x16_msa().
hv_mc_qpel_aver_hv_src00_8x8_msa()
static void hv_mc_qpel_aver_hv_src00_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 3853 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_aver_hv_src00_8x8_msa().
hv_mc_qpel_aver_horiz_16x16_msa()
static void hv_mc_qpel_aver_horiz_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 3940 of file qpeldsp_msa.c.
Referenced by hv_mc_qpel_16x16_msa(), hv_mc_qpel_aver_v_src0_16x16_msa(), hv_mc_qpel_aver_v_src1_16x16_msa(), hv_mc_qpel_avg_dst_16x16_msa(), hv_mc_qpel_avg_dst_aver_v_src0_16x16_msa(), and hv_mc_qpel_avg_dst_aver_v_src1_16x16_msa().
hv_mc_qpel_aver_v_src0_16x16_msa()
static void hv_mc_qpel_aver_v_src0_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 3984 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_aver_v_src0_16x16_msa().
hv_mc_qpel_aver_v_src0_8x8_msa()
static void hv_mc_qpel_aver_v_src0_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 3995 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_aver_v_src0_8x8_msa().
hv_mc_qpel_aver_horiz_src1_16x16_msa()
static void hv_mc_qpel_aver_horiz_src1_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 4079 of file qpeldsp_msa.c.
Referenced by hv_mc_qpel_aver_h_src1_16x16_msa(), hv_mc_qpel_aver_hv_src10_16x16_msa(), hv_mc_qpel_aver_hv_src11_16x16_msa(), hv_mc_qpel_avg_dst_aver_h_src1_16x16_msa(), hv_mc_qpel_avg_dst_aver_hv_src10_16x16_msa(), and hv_mc_qpel_avg_dst_aver_hv_src11_16x16_msa().
hv_mc_qpel_aver_hv_src10_16x16_msa()
static void hv_mc_qpel_aver_hv_src10_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 4128 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_aver_hv_src10_16x16_msa().
hv_mc_qpel_aver_hv_src10_8x8_msa()
static void hv_mc_qpel_aver_hv_src10_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 4139 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_aver_hv_src10_8x8_msa().
hv_mc_qpel_aver_h_src0_16x16_msa()
static void hv_mc_qpel_aver_h_src0_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 4233 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_aver_h_src0_16x16_msa().
hv_mc_qpel_aver_h_src0_8x8_msa()
static void hv_mc_qpel_aver_h_src0_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 4244 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_aver_h_src0_8x8_msa().
hv_mc_qpel_16x16_msa()
static void hv_mc_qpel_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 4325 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_16x16_msa().
hv_mc_qpel_8x8_msa()
static void hv_mc_qpel_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 4336 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_8x8_msa().
hv_mc_qpel_aver_h_src1_16x16_msa()
static void hv_mc_qpel_aver_h_src1_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 4410 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_aver_h_src1_16x16_msa().
hv_mc_qpel_aver_h_src1_8x8_msa()
static void hv_mc_qpel_aver_h_src1_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 4421 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_aver_h_src1_8x8_msa().
hv_mc_qpel_aver_hv_src01_16x16_msa()
static void hv_mc_qpel_aver_hv_src01_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 4508 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_aver_hv_src01_16x16_msa().
hv_mc_qpel_aver_hv_src01_8x8_msa()
static void hv_mc_qpel_aver_hv_src01_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 4519 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_aver_hv_src01_8x8_msa().
hv_mc_qpel_aver_v_src1_16x16_msa()
static void hv_mc_qpel_aver_v_src1_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 4609 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_aver_v_src1_16x16_msa().
hv_mc_qpel_aver_v_src1_8x8_msa()
static void hv_mc_qpel_aver_v_src1_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 4620 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_aver_v_src1_8x8_msa().
hv_mc_qpel_aver_hv_src11_16x16_msa()
static void hv_mc_qpel_aver_hv_src11_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 4705 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_aver_hv_src11_16x16_msa().
hv_mc_qpel_aver_hv_src11_8x8_msa()
static void hv_mc_qpel_aver_hv_src11_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 4716 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_aver_hv_src11_8x8_msa().
hv_mc_qpel_avg_dst_aver_hv_src00_16x16_msa()
static void hv_mc_qpel_avg_dst_aver_hv_src00_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 4812 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_avg_dst_aver_hv_src00_16x16_msa().
hv_mc_qpel_avg_dst_aver_hv_src00_8x8_msa()
static void hv_mc_qpel_avg_dst_aver_hv_src00_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 4823 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_avg_dst_aver_hv_src00_8x8_msa().
hv_mc_qpel_avg_dst_aver_v_src0_16x16_msa()
static void hv_mc_qpel_avg_dst_aver_v_src0_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 4925 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_avg_dst_aver_v_src0_16x16_msa().
hv_mc_qpel_avg_dst_aver_v_src0_8x8_msa()
static void hv_mc_qpel_avg_dst_aver_v_src0_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 4936 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_avg_dst_aver_v_src0_8x8_msa().
hv_mc_qpel_avg_dst_aver_hv_src10_16x16_msa()
static void hv_mc_qpel_avg_dst_aver_hv_src10_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 5034 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_avg_dst_aver_hv_src10_16x16_msa().
hv_mc_qpel_avg_dst_aver_hv_src10_8x8_msa()
static void hv_mc_qpel_avg_dst_aver_hv_src10_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 5045 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_avg_dst_aver_hv_src10_8x8_msa().
hv_mc_qpel_avg_dst_aver_h_src0_16x16_msa()
static void hv_mc_qpel_avg_dst_aver_h_src0_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 5159 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_avg_dst_aver_h_src0_16x16_msa().
hv_mc_qpel_avg_dst_aver_h_src0_8x8_msa()
static void hv_mc_qpel_avg_dst_aver_h_src0_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 5170 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_avg_dst_aver_h_src0_8x8_msa().
hv_mc_qpel_avg_dst_16x16_msa()
static void hv_mc_qpel_avg_dst_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 5265 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_avg_dst_16x16_msa().
hv_mc_qpel_avg_dst_8x8_msa()
static void hv_mc_qpel_avg_dst_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 5275 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_avg_dst_8x8_msa().
hv_mc_qpel_avg_dst_aver_h_src1_16x16_msa()
static void hv_mc_qpel_avg_dst_aver_h_src1_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 5363 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_avg_dst_aver_h_src1_16x16_msa().
hv_mc_qpel_avg_dst_aver_h_src1_8x8_msa()
static void hv_mc_qpel_avg_dst_aver_h_src1_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 5374 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_avg_dst_aver_h_src1_8x8_msa().
hv_mc_qpel_avg_dst_aver_hv_src01_16x16_msa()
static void hv_mc_qpel_avg_dst_aver_hv_src01_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 5479 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_avg_dst_aver_hv_src01_16x16_msa().
hv_mc_qpel_avg_dst_aver_hv_src01_8x8_msa()
static void hv_mc_qpel_avg_dst_aver_hv_src01_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 5490 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_avg_dst_aver_hv_src01_8x8_msa().
hv_mc_qpel_avg_dst_aver_v_src1_16x16_msa()
static void hv_mc_qpel_avg_dst_aver_v_src1_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 5593 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_avg_dst_aver_v_src1_16x16_msa().
hv_mc_qpel_avg_dst_aver_v_src1_8x8_msa()
static void hv_mc_qpel_avg_dst_aver_v_src1_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 5604 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_avg_dst_aver_v_src1_8x8_msa().
hv_mc_qpel_avg_dst_aver_hv_src11_16x16_msa()
static void hv_mc_qpel_avg_dst_aver_hv_src11_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 5700 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_avg_dst_aver_hv_src11_16x16_msa().
hv_mc_qpel_avg_dst_aver_hv_src11_8x8_msa()
static void hv_mc_qpel_avg_dst_aver_hv_src11_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 5711 of file qpeldsp_msa.c.
Referenced by ff_hv_mc_qpel_avg_dst_aver_hv_src11_8x8_msa().
copy_8x8_msa()
static void copy_8x8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 5818 of file qpeldsp_msa.c.
Referenced by ff_copy_8x8_msa().
copy_16x16_msa()
static void copy_16x16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride) static
Definition at line 5837 of file qpeldsp_msa.c.
Referenced by ff_copy_16x16_msa().
avg_width8_msa()
static void avg_width8_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 5854 of file qpeldsp_msa.c.
Referenced by ff_avg_width8_msa().
avg_width16_msa()
static void avg_width16_msa (const uint8_t * src, int32_t src_stride, uint8_t * dst, int32_t dst_stride, int32_t height) static
Definition at line 5880 of file qpeldsp_msa.c.
Referenced by ff_avg_width16_msa().
ff_copy_16x16_msa()
void ff_copy_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 5902 of file qpeldsp_msa.c.
ff_copy_8x8_msa()
void ff_copy_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 5907 of file qpeldsp_msa.c.
ff_horiz_mc_qpel_aver_src0_8width_msa()
void ff_horiz_mc_qpel_aver_src0_8width_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 5912 of file qpeldsp_msa.c.
ff_horiz_mc_qpel_aver_src0_16width_msa()
void ff_horiz_mc_qpel_aver_src0_16width_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 5919 of file qpeldsp_msa.c.
ff_horiz_mc_qpel_8width_msa()
void ff_horiz_mc_qpel_8width_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 5926 of file qpeldsp_msa.c.
ff_horiz_mc_qpel_16width_msa()
void ff_horiz_mc_qpel_16width_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 5932 of file qpeldsp_msa.c.
ff_horiz_mc_qpel_aver_src1_8width_msa()
void ff_horiz_mc_qpel_aver_src1_8width_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 5938 of file qpeldsp_msa.c.
ff_horiz_mc_qpel_aver_src1_16width_msa()
void ff_horiz_mc_qpel_aver_src1_16width_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 5945 of file qpeldsp_msa.c.
ff_horiz_mc_qpel_no_rnd_aver_src0_8width_msa()
void ff_horiz_mc_qpel_no_rnd_aver_src0_8width_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 5952 of file qpeldsp_msa.c.
ff_horiz_mc_qpel_no_rnd_aver_src0_16width_msa()
void ff_horiz_mc_qpel_no_rnd_aver_src0_16width_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 5959 of file qpeldsp_msa.c.
ff_horiz_mc_qpel_no_rnd_8width_msa()
void ff_horiz_mc_qpel_no_rnd_8width_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 5966 of file qpeldsp_msa.c.
ff_horiz_mc_qpel_no_rnd_16width_msa()
void ff_horiz_mc_qpel_no_rnd_16width_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 5972 of file qpeldsp_msa.c.
ff_horiz_mc_qpel_no_rnd_aver_src1_8width_msa()
void ff_horiz_mc_qpel_no_rnd_aver_src1_8width_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 5978 of file qpeldsp_msa.c.
ff_horiz_mc_qpel_no_rnd_aver_src1_16width_msa()
void ff_horiz_mc_qpel_no_rnd_aver_src1_16width_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 5985 of file qpeldsp_msa.c.
ff_avg_width8_msa()
void ff_avg_width8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 5992 of file qpeldsp_msa.c.
ff_avg_width16_msa()
void ff_avg_width16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 5997 of file qpeldsp_msa.c.
ff_horiz_mc_qpel_avg_dst_aver_src0_8width_msa()
void ff_horiz_mc_qpel_avg_dst_aver_src0_8width_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6002 of file qpeldsp_msa.c.
ff_horiz_mc_qpel_avg_dst_aver_src0_16width_msa()
void ff_horiz_mc_qpel_avg_dst_aver_src0_16width_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6009 of file qpeldsp_msa.c.
ff_horiz_mc_qpel_avg_dst_8width_msa()
void ff_horiz_mc_qpel_avg_dst_8width_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6016 of file qpeldsp_msa.c.
ff_horiz_mc_qpel_avg_dst_16width_msa()
void ff_horiz_mc_qpel_avg_dst_16width_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6022 of file qpeldsp_msa.c.
ff_horiz_mc_qpel_avg_dst_aver_src1_8width_msa()
void ff_horiz_mc_qpel_avg_dst_aver_src1_8width_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6028 of file qpeldsp_msa.c.
ff_horiz_mc_qpel_avg_dst_aver_src1_16width_msa()
void ff_horiz_mc_qpel_avg_dst_aver_src1_16width_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6035 of file qpeldsp_msa.c.
ff_vert_mc_qpel_aver_src0_8x8_msa()
void ff_vert_mc_qpel_aver_src0_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6043 of file qpeldsp_msa.c.
ff_vert_mc_qpel_aver_src0_16x16_msa()
void ff_vert_mc_qpel_aver_src0_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6049 of file qpeldsp_msa.c.
ff_vert_mc_qpel_8x8_msa()
void ff_vert_mc_qpel_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6055 of file qpeldsp_msa.c.
ff_vert_mc_qpel_16x16_msa()
void ff_vert_mc_qpel_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6061 of file qpeldsp_msa.c.
ff_vert_mc_qpel_aver_src1_8x8_msa()
void ff_vert_mc_qpel_aver_src1_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6067 of file qpeldsp_msa.c.
ff_vert_mc_qpel_aver_src1_16x16_msa()
void ff_vert_mc_qpel_aver_src1_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6073 of file qpeldsp_msa.c.
ff_vert_mc_qpel_no_rnd_aver_src0_8x8_msa()
void ff_vert_mc_qpel_no_rnd_aver_src0_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6079 of file qpeldsp_msa.c.
ff_vert_mc_qpel_no_rnd_aver_src0_16x16_msa()
void ff_vert_mc_qpel_no_rnd_aver_src0_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6086 of file qpeldsp_msa.c.
ff_vert_mc_qpel_no_rnd_8x8_msa()
void ff_vert_mc_qpel_no_rnd_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6093 of file qpeldsp_msa.c.
ff_vert_mc_qpel_no_rnd_16x16_msa()
void ff_vert_mc_qpel_no_rnd_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6099 of file qpeldsp_msa.c.
ff_vert_mc_qpel_no_rnd_aver_src1_8x8_msa()
void ff_vert_mc_qpel_no_rnd_aver_src1_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6105 of file qpeldsp_msa.c.
ff_vert_mc_qpel_no_rnd_aver_src1_16x16_msa()
void ff_vert_mc_qpel_no_rnd_aver_src1_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6112 of file qpeldsp_msa.c.
ff_vert_mc_qpel_avg_dst_aver_src0_8x8_msa()
void ff_vert_mc_qpel_avg_dst_aver_src0_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6119 of file qpeldsp_msa.c.
ff_vert_mc_qpel_avg_dst_aver_src0_16x16_msa()
void ff_vert_mc_qpel_avg_dst_aver_src0_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6126 of file qpeldsp_msa.c.
ff_vert_mc_qpel_avg_dst_8x8_msa()
void ff_vert_mc_qpel_avg_dst_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6133 of file qpeldsp_msa.c.
ff_vert_mc_qpel_avg_dst_16x16_msa()
void ff_vert_mc_qpel_avg_dst_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6139 of file qpeldsp_msa.c.
ff_vert_mc_qpel_avg_dst_aver_src1_8x8_msa()
void ff_vert_mc_qpel_avg_dst_aver_src1_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6145 of file qpeldsp_msa.c.
ff_vert_mc_qpel_avg_dst_aver_src1_16x16_msa()
void ff_vert_mc_qpel_avg_dst_aver_src1_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6152 of file qpeldsp_msa.c.
ff_hv_mc_qpel_aver_hv_src00_16x16_msa()
void ff_hv_mc_qpel_aver_hv_src00_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6160 of file qpeldsp_msa.c.
ff_hv_mc_qpel_aver_hv_src00_8x8_msa()
void ff_hv_mc_qpel_aver_hv_src00_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6167 of file qpeldsp_msa.c.
ff_hv_mc_qpel_aver_v_src0_16x16_msa()
void ff_hv_mc_qpel_aver_v_src0_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6173 of file qpeldsp_msa.c.
ff_hv_mc_qpel_aver_v_src0_8x8_msa()
void ff_hv_mc_qpel_aver_v_src0_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6179 of file qpeldsp_msa.c.
ff_hv_mc_qpel_aver_hv_src10_16x16_msa()
void ff_hv_mc_qpel_aver_hv_src10_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6185 of file qpeldsp_msa.c.
ff_hv_mc_qpel_aver_hv_src10_8x8_msa()
void ff_hv_mc_qpel_aver_hv_src10_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6192 of file qpeldsp_msa.c.
ff_hv_mc_qpel_aver_h_src0_16x16_msa()
void ff_hv_mc_qpel_aver_h_src0_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6198 of file qpeldsp_msa.c.
ff_hv_mc_qpel_aver_h_src0_8x8_msa()
void ff_hv_mc_qpel_aver_h_src0_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6204 of file qpeldsp_msa.c.
ff_hv_mc_qpel_16x16_msa()
void ff_hv_mc_qpel_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6210 of file qpeldsp_msa.c.
ff_hv_mc_qpel_8x8_msa()
void ff_hv_mc_qpel_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6216 of file qpeldsp_msa.c.
ff_hv_mc_qpel_aver_h_src1_16x16_msa()
void ff_hv_mc_qpel_aver_h_src1_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6222 of file qpeldsp_msa.c.
ff_hv_mc_qpel_aver_h_src1_8x8_msa()
void ff_hv_mc_qpel_aver_h_src1_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6228 of file qpeldsp_msa.c.
ff_hv_mc_qpel_aver_hv_src01_16x16_msa()
void ff_hv_mc_qpel_aver_hv_src01_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6234 of file qpeldsp_msa.c.
ff_hv_mc_qpel_aver_hv_src01_8x8_msa()
void ff_hv_mc_qpel_aver_hv_src01_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6241 of file qpeldsp_msa.c.
ff_hv_mc_qpel_aver_v_src1_16x16_msa()
void ff_hv_mc_qpel_aver_v_src1_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6247 of file qpeldsp_msa.c.
ff_hv_mc_qpel_aver_v_src1_8x8_msa()
void ff_hv_mc_qpel_aver_v_src1_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6253 of file qpeldsp_msa.c.
ff_hv_mc_qpel_aver_hv_src11_16x16_msa()
void ff_hv_mc_qpel_aver_hv_src11_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6259 of file qpeldsp_msa.c.
ff_hv_mc_qpel_aver_hv_src11_8x8_msa()
void ff_hv_mc_qpel_aver_hv_src11_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6266 of file qpeldsp_msa.c.
ff_hv_mc_qpel_avg_dst_aver_hv_src00_16x16_msa()
void ff_hv_mc_qpel_avg_dst_aver_hv_src00_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6272 of file qpeldsp_msa.c.
ff_hv_mc_qpel_avg_dst_aver_hv_src00_8x8_msa()
void ff_hv_mc_qpel_avg_dst_aver_hv_src00_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6279 of file qpeldsp_msa.c.
ff_hv_mc_qpel_avg_dst_aver_v_src0_16x16_msa()
void ff_hv_mc_qpel_avg_dst_aver_v_src0_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6286 of file qpeldsp_msa.c.
ff_hv_mc_qpel_avg_dst_aver_v_src0_8x8_msa()
void ff_hv_mc_qpel_avg_dst_aver_v_src0_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6293 of file qpeldsp_msa.c.
ff_hv_mc_qpel_avg_dst_aver_hv_src10_16x16_msa()
void ff_hv_mc_qpel_avg_dst_aver_hv_src10_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6300 of file qpeldsp_msa.c.
ff_hv_mc_qpel_avg_dst_aver_hv_src10_8x8_msa()
void ff_hv_mc_qpel_avg_dst_aver_hv_src10_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6307 of file qpeldsp_msa.c.
ff_hv_mc_qpel_avg_dst_aver_h_src0_16x16_msa()
void ff_hv_mc_qpel_avg_dst_aver_h_src0_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6314 of file qpeldsp_msa.c.
ff_hv_mc_qpel_avg_dst_aver_h_src0_8x8_msa()
void ff_hv_mc_qpel_avg_dst_aver_h_src0_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6321 of file qpeldsp_msa.c.
ff_hv_mc_qpel_avg_dst_16x16_msa()
void ff_hv_mc_qpel_avg_dst_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6328 of file qpeldsp_msa.c.
ff_hv_mc_qpel_avg_dst_8x8_msa()
void ff_hv_mc_qpel_avg_dst_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6334 of file qpeldsp_msa.c.
ff_hv_mc_qpel_avg_dst_aver_h_src1_16x16_msa()
void ff_hv_mc_qpel_avg_dst_aver_h_src1_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6340 of file qpeldsp_msa.c.
ff_hv_mc_qpel_avg_dst_aver_h_src1_8x8_msa()
void ff_hv_mc_qpel_avg_dst_aver_h_src1_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6347 of file qpeldsp_msa.c.
ff_hv_mc_qpel_avg_dst_aver_hv_src01_16x16_msa()
void ff_hv_mc_qpel_avg_dst_aver_hv_src01_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6354 of file qpeldsp_msa.c.
ff_hv_mc_qpel_avg_dst_aver_hv_src01_8x8_msa()
void ff_hv_mc_qpel_avg_dst_aver_hv_src01_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6361 of file qpeldsp_msa.c.
ff_hv_mc_qpel_avg_dst_aver_v_src1_16x16_msa()
void ff_hv_mc_qpel_avg_dst_aver_v_src1_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6368 of file qpeldsp_msa.c.
ff_hv_mc_qpel_avg_dst_aver_v_src1_8x8_msa()
void ff_hv_mc_qpel_avg_dst_aver_v_src1_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6375 of file qpeldsp_msa.c.
ff_hv_mc_qpel_avg_dst_aver_hv_src11_16x16_msa()
void ff_hv_mc_qpel_avg_dst_aver_hv_src11_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6382 of file qpeldsp_msa.c.
ff_hv_mc_qpel_avg_dst_aver_hv_src11_8x8_msa()
void ff_hv_mc_qpel_avg_dst_aver_hv_src11_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6389 of file qpeldsp_msa.c.
ff_hv_mc_qpel_no_rnd_aver_hv_src00_16x16_msa()
void ff_hv_mc_qpel_no_rnd_aver_hv_src00_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6396 of file qpeldsp_msa.c.
ff_hv_mc_qpel_no_rnd_aver_hv_src00_8x8_msa()
void ff_hv_mc_qpel_no_rnd_aver_hv_src00_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6403 of file qpeldsp_msa.c.
ff_hv_mc_qpel_no_rnd_aver_v_src0_16x16_msa()
void ff_hv_mc_qpel_no_rnd_aver_v_src0_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6410 of file qpeldsp_msa.c.
ff_hv_mc_qpel_no_rnd_aver_v_src0_8x8_msa()
void ff_hv_mc_qpel_no_rnd_aver_v_src0_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6417 of file qpeldsp_msa.c.
ff_hv_mc_qpel_no_rnd_aver_hv_src10_16x16_msa()
void ff_hv_mc_qpel_no_rnd_aver_hv_src10_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6424 of file qpeldsp_msa.c.
ff_hv_mc_qpel_no_rnd_aver_hv_src10_8x8_msa()
void ff_hv_mc_qpel_no_rnd_aver_hv_src10_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6431 of file qpeldsp_msa.c.
ff_hv_mc_qpel_no_rnd_aver_h_src0_16x16_msa()
void ff_hv_mc_qpel_no_rnd_aver_h_src0_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6438 of file qpeldsp_msa.c.
ff_hv_mc_qpel_no_rnd_aver_h_src0_8x8_msa()
void ff_hv_mc_qpel_no_rnd_aver_h_src0_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6445 of file qpeldsp_msa.c.
ff_hv_mc_qpel_no_rnd_16x16_msa()
void ff_hv_mc_qpel_no_rnd_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6452 of file qpeldsp_msa.c.
ff_hv_mc_qpel_no_rnd_8x8_msa()
void ff_hv_mc_qpel_no_rnd_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6458 of file qpeldsp_msa.c.
ff_hv_mc_qpel_no_rnd_aver_h_src1_16x16_msa()
void ff_hv_mc_qpel_no_rnd_aver_h_src1_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6464 of file qpeldsp_msa.c.
ff_hv_mc_qpel_no_rnd_aver_h_src1_8x8_msa()
void ff_hv_mc_qpel_no_rnd_aver_h_src1_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6471 of file qpeldsp_msa.c.
ff_hv_mc_qpel_no_rnd_aver_hv_src01_16x16_msa()
void ff_hv_mc_qpel_no_rnd_aver_hv_src01_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6478 of file qpeldsp_msa.c.
ff_hv_mc_qpel_no_rnd_aver_hv_src01_8x8_msa()
void ff_hv_mc_qpel_no_rnd_aver_hv_src01_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6485 of file qpeldsp_msa.c.
ff_hv_mc_qpel_no_rnd_aver_v_src1_16x16_msa()
void ff_hv_mc_qpel_no_rnd_aver_v_src1_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6492 of file qpeldsp_msa.c.
ff_hv_mc_qpel_no_rnd_aver_v_src1_8x8_msa()
void ff_hv_mc_qpel_no_rnd_aver_v_src1_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6499 of file qpeldsp_msa.c.
ff_hv_mc_qpel_no_rnd_aver_hv_src11_16x16_msa()
void ff_hv_mc_qpel_no_rnd_aver_hv_src11_16x16_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6506 of file qpeldsp_msa.c.
ff_hv_mc_qpel_no_rnd_aver_hv_src11_8x8_msa()
void ff_hv_mc_qpel_no_rnd_aver_hv_src11_8x8_msa (uint8_t * dest, const uint8_t * src, ptrdiff_t stride)
Definition at line 6513 of file qpeldsp_msa.c.