FFmpeg: libavcodec/qpeldsp.h File Reference
qpeldsp.h File Reference
quarterpel DSP functions
#include <stddef.h>
#include <stdint.h>
Data Structures
struct QpelDSPContext
quarterpel DSP context
Macros
#define DEF_OLD_QPEL(name)
Typedefs
typedef void(* qpel_mc_func) (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
Functions
void ff_put_pixels8x8_c (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_pixels8x8_c (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_pixels16x16_c (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_avg_pixels16x16_c (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
void ff_put_pixels8_l2_8 (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, int dst_stride, int src_stride1, int src_stride2, int h)
void ff_qpeldsp_init (QpelDSPContext *c)
void ff_qpeldsp_init_x86 (QpelDSPContext *c)
void ff_qpeldsp_init_mips (QpelDSPContext *c)
Detailed Description
quarterpel DSP functions
Definition in file qpeldsp.h.
Macro Definition Documentation
DEF_OLD_QPEL
#define DEF_OLD_QPEL (name)
Value:
void ff_put_        ## name(uint8_t *dst /* align width (8 or 16) */,   \
                            const uint8_t *src /* align 1 */,           \
                            ptrdiff_t stride);                          \
void ff_put_no_rnd_ ## name(uint8_t *dst /* align width (8 or 16) */,   \
                            const uint8_t *src /* align 1 */,           \
                            ptrdiff_t stride);                          \
void ff_avg_        ## name(uint8_t *dst /* align width (8 or 16) */,   \
                            const uint8_t *src /* align 1 */,           \
                            ptrdiff_t stride);
Definition at line 41 of file qpeldsp.h.
Typedef Documentation
qpel_mc_func
typedef void(* qpel_mc_func) (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
Definition at line 65 of file qpeldsp.h.
Function Documentation
ff_put_pixels8x8_c()
void ff_put_pixels8x8_c (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 703 of file qpeldsp.c.
Referenced by ff_wmv2dsp_init().
ff_avg_pixels8x8_c()
void ff_avg_pixels8x8_c (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 708 of file qpeldsp.c.
ff_put_pixels16x16_c()
void ff_put_pixels16x16_c (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 713 of file qpeldsp.c.
ff_avg_pixels16x16_c()
void ff_avg_pixels16x16_c (uint8_t * dst, const uint8_t * src, ptrdiff_t stride)
Definition at line 718 of file qpeldsp.c.
ff_put_pixels8_l2_8()
void ff_put_pixels8_l2_8 (uint8_t * dst, const uint8_t * src1, const uint8_t * src2, int dst_stride, int src_stride1, int src_stride2, int h)
Definition at line 730 of file qpeldsp.c.
Referenced by put_mspel8_mc10_c(), put_mspel8_mc12_c(), put_mspel8_mc30_c(), and put_mspel8_mc32_c().
ff_qpeldsp_init()
void ff_qpeldsp_init (QpelDSPContext * c)
Definition at line 783 of file qpeldsp.c.
Referenced by ff_h263_decode_init(), ff_mpv_encode_init(), mss2_decode_init(), and vc1_decode_init().
ff_qpeldsp_init_x86()
void ff_qpeldsp_init_x86 (QpelDSPContext * c)
Definition at line 529 of file qpeldsp_init.c.
Referenced by ff_qpeldsp_init().
ff_qpeldsp_init_mips()
void ff_qpeldsp_init_mips (QpelDSPContext * c)
Definition at line 162 of file qpeldsp_init_mips.c.
Referenced by ff_qpeldsp_init().