FFmpeg: libavcodec/qsv_internal.h File Reference
qsv_internal.h File Reference
#include <mfx/mfxvideo.h>
#include "libavutil/frame.h"
#include "avcodec.h"
Data Structures
struct QSVFrame
struct QSVFramesContext
Macros
#define QSV_VERSION_MAJOR 1
#define QSV_VERSION_MINOR 1
#define ASYNC_DEPTH_DEFAULT 4
#define QSV_MAX_ENC_PAYLOAD 2
#define QSV_VERSION_ATLEAST(MAJOR, MINOR)
Functions
int ff_qsv_error (int mfx_err)
Convert a libmfx error code into an ffmpeg error code.
int ff_qsv_codec_id_to_mfx (enum AVCodecID codec_id)
int ff_qsv_profile_to_mfx (enum AVCodecID codec_id, int profile)
int ff_qsv_map_pixfmt (enum AVPixelFormat format, uint32_t *fourcc)
int ff_qsv_init_internal_session (AVCodecContext *avctx, mfxSession *session, const char *load_plugins)
int ff_qsv_init_session_hwcontext (AVCodecContext *avctx, mfxSession *session, QSVFramesContext *qsv_frames_ctx, const char *load_plugins, int opaque)
Macro Definition Documentation
QSV_VERSION_MAJOR
#define QSV_VERSION_MAJOR 1
Definition at line 30 of file qsv_internal.h.
Referenced by ff_qsv_init_internal_session().
QSV_VERSION_MINOR
#define QSV_VERSION_MINOR 1
Definition at line 31 of file qsv_internal.h.
Referenced by ff_qsv_init_internal_session().
ASYNC_DEPTH_DEFAULT
#define ASYNC_DEPTH_DEFAULT 4
Definition at line 33 of file qsv_internal.h.
QSV_MAX_ENC_PAYLOAD
#define QSV_MAX_ENC_PAYLOAD 2
Definition at line 35 of file qsv_internal.h.
Referenced by free_encoder_ctrl_payloads(), and get_free_frame().
QSV_VERSION_ATLEAST
#define QSV_VERSION_ATLEAST (MAJOR, MINOR)
Value:
(MFX_VERSION_MAJOR > (MAJOR) ||         \
     MFX_VERSION_MAJOR == (MAJOR) && MFX_VERSION_MINOR >= (MINOR))
Definition at line 37 of file qsv_internal.h.
Function Documentation
ff_qsv_error()
int ff_qsv_error (int mfx_err)
Convert a libmfx error code into an ffmpeg error code.
Definition at line 73 of file qsv.c.
Referenced by encode_frame(), ff_qsv_enc_init(), ff_qsv_init_internal_session(), ff_qsv_init_session_hwcontext(), qsv_decode(), qsv_decode_init(), qsv_load_plugins(), and qsv_retrieve_enc_params().
ff_qsv_codec_id_to_mfx()
int ff_qsv_codec_id_to_mfx (enum AVCodecID codec_id)
Definition at line 36 of file qsv.c.
Referenced by init_video_param(), and qsv_decode_init().
ff_qsv_profile_to_mfx()
int ff_qsv_profile_to_mfx (enum AVCodecID codec_id, int profile)
Definition at line 57 of file qsv.c.
Referenced by qsv_decode_init().
ff_qsv_map_pixfmt()
int ff_qsv_map_pixfmt (enum AVPixelFormat format, uint32_t * fourcc)
Definition at line 108 of file qsv.c.
Referenced by ff_qsv_process_data().
ff_qsv_init_internal_session()
int ff_qsv_init_internal_session (AVCodecContext * avctx, mfxSession * session, const char * load_plugins)
Definition at line 173 of file qsv.c.
Referenced by qsv_init_session(), and qsvenc_init_session().
ff_qsv_init_session_hwcontext()
int ff_qsv_init_session_hwcontext (AVCodecContext * avctx, mfxSession * session, QSVFramesContext * qsv_frames_ctx, const char * load_plugins, int opaque)
Definition at line 264 of file qsv.c.
Referenced by qsv_init_session(), and qsvenc_init_session().