FFmpeg: libavcodec/qsv.c File Reference
qsv.c File Reference
#include <mfx/mfxvideo.h>
#include <mfx/mfxplugin.h>
#include <stdio.h>
#include <string.h>
#include "libavutil/avstring.h"
#include "libavutil/common.h"
#include "libavutil/error.h"
#include "libavutil/hwcontext.h"
#include "libavutil/hwcontext_qsv.h"
#include "avcodec.h"
#include "qsv_internal.h"
Functions
int ff_qsv_codec_id_to_mfx (enum AVCodecID codec_id)
int ff_qsv_profile_to_mfx (enum AVCodecID codec_id, int profile)
int ff_qsv_error (int mfx_err)
Convert a libmfx error code into an ffmpeg error code.
int ff_qsv_map_pixfmt (enum AVPixelFormat format, uint32_t *fourcc)
static int qsv_load_plugins (mfxSession session, const char *load_plugins, void *logctx)
int ff_qsv_init_internal_session (AVCodecContext *avctx, mfxSession *session, const char *load_plugins)
static mfxStatus qsv_frame_alloc (mfxHDL pthis, mfxFrameAllocRequest *req, mfxFrameAllocResponse *resp)
static mfxStatus qsv_frame_free (mfxHDL pthis, mfxFrameAllocResponse *resp)
static mfxStatus qsv_frame_lock (mfxHDL pthis, mfxMemId mid, mfxFrameData *ptr)
static mfxStatus qsv_frame_unlock (mfxHDL pthis, mfxMemId mid, mfxFrameData *ptr)
static mfxStatus qsv_frame_get_hdl (mfxHDL pthis, mfxMemId mid, mfxHDL *hdl)
int ff_qsv_init_session_hwcontext (AVCodecContext *avctx, mfxSession *psession, QSVFramesContext *qsv_frames_ctx, const char *load_plugins, int opaque)
Function Documentation
ff_qsv_codec_id_to_mfx()
int ff_qsv_codec_id_to_mfx (enum AVCodecID codec_id)
Definition at line 36 of file qsv.c.
Referenced by init_video_param(), and qsv_decode_init().
ff_qsv_profile_to_mfx()
int ff_qsv_profile_to_mfx (enum AVCodecID codec_id, int profile)
Definition at line 57 of file qsv.c.
Referenced by qsv_decode_init().
ff_qsv_error()
int ff_qsv_error (int mfx_err)
Convert a libmfx error code into an ffmpeg error code.
Definition at line 73 of file qsv.c.
Referenced by encode_frame(), ff_qsv_enc_init(), ff_qsv_init_internal_session(), ff_qsv_init_session_hwcontext(), qsv_decode(), qsv_decode_init(), qsv_load_plugins(), and qsv_retrieve_enc_params().
ff_qsv_map_pixfmt()
int ff_qsv_map_pixfmt (enum AVPixelFormat format, uint32_t * fourcc)
Definition at line 108 of file qsv.c.
Referenced by ff_qsv_process_data().
qsv_load_plugins()
static int qsv_load_plugins (mfxSession session, const char * load_plugins, void * logctx) static
Definition at line 123 of file qsv.c.
Referenced by ff_qsv_init_internal_session(), and ff_qsv_init_session_hwcontext().
ff_qsv_init_internal_session()
int ff_qsv_init_internal_session (AVCodecContext * avctx, mfxSession * session, const char * load_plugins)
Definition at line 173 of file qsv.c.
Referenced by qsv_init_session(), and qsvenc_init_session().
qsv_frame_alloc()
static mfxStatus qsv_frame_alloc (mfxHDL pthis, mfxFrameAllocRequest * req, mfxFrameAllocResponse * resp) static
Definition at line 217 of file qsv.c.
Referenced by ff_qsv_init_session_hwcontext().
qsv_frame_free()
static mfxStatus qsv_frame_free (mfxHDL pthis, mfxFrameAllocResponse * resp) static
Definition at line 243 of file qsv.c.
Referenced by ff_qsv_init_session_hwcontext().
qsv_frame_lock()
static mfxStatus qsv_frame_lock (mfxHDL pthis, mfxMemId mid, mfxFrameData * ptr) static
Definition at line 248 of file qsv.c.
Referenced by ff_qsv_init_session_hwcontext().
qsv_frame_unlock()
static mfxStatus qsv_frame_unlock (mfxHDL pthis, mfxMemId mid, mfxFrameData * ptr) static
Definition at line 253 of file qsv.c.
Referenced by ff_qsv_init_session_hwcontext().
qsv_frame_get_hdl()
static mfxStatus qsv_frame_get_hdl (mfxHDL pthis, mfxMemId mid, mfxHDL * hdl) static
Definition at line 258 of file qsv.c.
Referenced by ff_qsv_init_session_hwcontext().
ff_qsv_init_session_hwcontext()
int ff_qsv_init_session_hwcontext (AVCodecContext * avctx, mfxSession * psession, QSVFramesContext * qsv_frames_ctx, const char * load_plugins, int opaque)
Definition at line 264 of file qsv.c.
Referenced by qsv_init_session(), and qsvenc_init_session().