FFmpeg: libavcodec/qsvdec.h File Reference
qsvdec.h File Reference
#include <stdint.h>
#include <sys/types.h>
#include <mfx/mfxvideo.h>
#include "libavutil/fifo.h"
#include "libavutil/frame.h"
#include "libavutil/pixfmt.h"
#include "avcodec.h"
#include "qsv_internal.h"
Data Structures
struct QSVContext
Functions
int ff_qsv_process_data (AVCodecContext *avctx, QSVContext *q, AVFrame *frame, int *got_frame, AVPacket *pkt)
void ff_qsv_decode_flush (AVCodecContext *avctx, QSVContext *q)
int ff_qsv_decode_close (QSVContext *q)
Function Documentation
ff_qsv_process_data()
int ff_qsv_process_data (AVCodecContext * avctx, QSVContext * q, AVFrame * frame, int * got_frame, AVPacket * pkt)
Definition at line 437 of file qsvdec.c.
Referenced by qsv_decode_frame().
ff_qsv_decode_flush()
void ff_qsv_decode_flush (AVCodecContext * avctx, QSVContext * q)
Definition at line 513 of file qsvdec.c.
Referenced by qsv_decode_flush().
ff_qsv_decode_close()
int ff_qsv_decode_close (QSVContext * q)
Definition at line 397 of file qsvdec.c.
Referenced by qsv_decode_close().