FFmpeg: libavcodec/qsvdec_vc1.c File Reference
qsvdec_vc1.c File Reference
#include <stdint.h>
#include <string.h>
#include <mfx/mfxvideo.h>
#include "libavutil/common.h"
#include "libavutil/fifo.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "internal.h"
#include "qsv_internal.h"
#include "qsvdec.h"
#include "qsv.h"
Data Structures
struct QSVVC1Context
Macros
#define OFFSET(x) offsetof(QSVVC1Context, x)
#define VD AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_DECODING_PARAM
Functions
static void qsv_clear_buffers (QSVVC1Context *s)
static av_cold int qsv_decode_close (AVCodecContext *avctx)
static av_cold int qsv_decode_init (AVCodecContext *avctx)
static int qsv_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static void qsv_decode_flush (AVCodecContext *avctx)
Variables
AVHWAccel ff_vc1_qsv_hwaccel
static const AVOption options []
class {
class_name = "vc1_qsv"
item_name = av_default_item_name
option = options
version = LIBAVUTIL_VERSION_INT
};
AVCodec ff_vc1_qsv_decoder
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(QSVVC1Context, x)
Definition at line 147 of file qsvdec_vc1.c.
VD
#define VD AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_DECODING_PARAM
Definition at line 148 of file qsvdec_vc1.c.
Function Documentation
qsv_clear_buffers()
static void qsv_clear_buffers (QSVVC1Context * s) static
Definition at line 45 of file qsvdec_vc1.c.
Referenced by qsv_decode_close(), and qsv_decode_flush().
qsv_decode_close()
static av_cold int qsv_decode_close (AVCodecContext * avctx) static
Definition at line 56 of file qsvdec_vc1.c.
Referenced by qsv_decode_init().
qsv_decode_init()
static av_cold int qsv_decode_init (AVCodecContext * avctx) static
Definition at line 69 of file qsvdec_vc1.c.
qsv_decode_frame()
static int qsv_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 86 of file qsvdec_vc1.c.
qsv_decode_flush()
static void qsv_decode_flush (AVCodecContext * avctx) static
Definition at line 132 of file qsvdec_vc1.c.
Variable Documentation
ff_vc1_qsv_hwaccel
AVHWAccel ff_vc1_qsv_hwaccel
Initial value:
= {
    .name           = "vc1_qsv",
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_VC1,
    .pix_fmt        = AV_PIX_FMT_QSV,
}
Definition at line 140 of file qsvdec_vc1.c.
options
const AVOption options[] static
Initial value:
= {
    { "async_depth", "Internal parallelization depth, the higher the value the higher the latency.", OFFSET(qsv.async_depth), AV_OPT_TYPE_INT, { .i64 = ASYNC_DEPTH_DEFAULT }, 0, INT_MAX, VD },
    { NULL },
}
Definition at line 149 of file qsvdec_vc1.c.
class_name
class_name = "vc1_qsv" private
Definition at line 155 of file qsvdec_vc1.c.
item_name
item_name = av_default_item_name private
Definition at line 156 of file qsvdec_vc1.c.
option
option = options private
Definition at line 157 of file qsvdec_vc1.c.
version
version = LIBAVUTIL_VERSION_INT private
Definition at line 158 of file qsvdec_vc1.c.
@107
const { ... }
ff_vc1_qsv_decoder
AVCodec ff_vc1_qsv_decoder
Initial value:
= {
    .name           = "vc1_qsv",
    .long_name      = NULL_IF_CONFIG_SMALL("VC-1 video (Intel Quick Sync Video acceleration)"),
    .priv_data_size = sizeof(QSVVC1Context),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_VC1,
    .init           = qsv_decode_init,
    .decode         = qsv_decode_frame,
    .flush          = qsv_decode_flush,
    .close          = qsv_decode_close,
    .capabilities   = AV_CODEC_CAP_DELAY | AV_CODEC_CAP_DR1 | AV_CODEC_CAP_AVOID_PROBING,
    .priv_class     = &class,
    .pix_fmts       = (const enum AVPixelFormat[]){ AV_PIX_FMT_NV12,
                                                    AV_PIX_FMT_QSV,
                                                    AV_PIX_FMT_NONE },
}
Definition at line 161 of file qsvdec_vc1.c.