FFmpeg: libavcodec/qsvdec_h2645.c File Reference
qsvdec_h2645.c File Reference
#include <stdint.h>
#include <string.h>
#include <mfx/mfxvideo.h>
#include "libavutil/common.h"
#include "libavutil/fifo.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "internal.h"
#include "qsv_internal.h"
#include "qsvdec.h"
#include "qsv.h"
Data Structures
struct QSVH2645Context
Macros
#define OFFSET(x) offsetof(QSVH2645Context, x)
#define VD AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_DECODING_PARAM
Enumerations
enum LoadPlugin {
LOAD_PLUGIN_NONE, LOAD_PLUGIN_HEVC_SW, LOAD_PLUGIN_HEVC_HW, LOAD_PLUGIN_NONE,
LOAD_PLUGIN_HEVC_SW, LOAD_PLUGIN_HEVC_HW
}
Functions
static void qsv_clear_buffers (QSVH2645Context *s)
static av_cold int qsv_decode_close (AVCodecContext *avctx)
static av_cold int qsv_decode_init (AVCodecContext *avctx)
static int qsv_init_bsf (AVCodecContext *avctx, QSVH2645Context *s)
static int qsv_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static void qsv_decode_flush (AVCodecContext *avctx)
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(QSVH2645Context, x)
Definition at line 228 of file qsvdec_h2645.c.
VD
#define VD AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_DECODING_PARAM
Definition at line 229 of file qsvdec_h2645.c.
Enumeration Type Documentation
LoadPlugin
enum LoadPlugin
Enumerator
LOAD_PLUGIN_NONE
LOAD_PLUGIN_HEVC_SW
LOAD_PLUGIN_HEVC_HW
LOAD_PLUGIN_NONE
LOAD_PLUGIN_HEVC_SW
LOAD_PLUGIN_HEVC_HW
Definition at line 40 of file qsvdec_h2645.c.
Function Documentation
qsv_clear_buffers()
static void qsv_clear_buffers (QSVH2645Context * s) static
Definition at line 60 of file qsvdec_h2645.c.
Referenced by qsv_decode_close(), and qsv_decode_flush().
qsv_decode_close()
static av_cold int qsv_decode_close (AVCodecContext * avctx) static
Definition at line 73 of file qsvdec_h2645.c.
Referenced by qsv_decode_init().
qsv_decode_init()
static av_cold int qsv_decode_init (AVCodecContext * avctx) static
Definition at line 86 of file qsvdec_h2645.c.
qsv_init_bsf()
static int qsv_init_bsf (AVCodecContext * avctx, QSVH2645Context * s) static
Definition at line 123 of file qsvdec_h2645.c.
Referenced by qsv_decode_frame().
qsv_decode_frame()
static int qsv_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 154 of file qsvdec_h2645.c.
qsv_decode_flush()
static void qsv_decode_flush (AVCodecContext * avctx) static
Definition at line 220 of file qsvdec_h2645.c.