FFmpeg: libavcodec/qsvenc.c File Reference
qsvenc.c File Reference
#include <string.h>
#include <sys/types.h>
#include <mfx/mfxvideo.h>
#include "libavutil/common.h"
#include "libavutil/hwcontext.h"
#include "libavutil/hwcontext_qsv.h"
#include "libavutil/mem.h"
#include "libavutil/log.h"
#include "libavutil/time.h"
#include "libavutil/imgutils.h"
#include "libavcodec/bytestream.h"
#include "avcodec.h"
#include "internal.h"
#include "qsv.h"
#include "qsv_internal.h"
#include "qsvenc.h"
Functions
static const char * print_profile (mfxU16 profile)
static const char * print_ratecontrol (mfxU16 rc_mode)
static const char * print_threestate (mfxU16 val)
static void dump_video_param (AVCodecContext *avctx, QSVEncContext *q, mfxExtBuffer **coding_opts)
static int select_rc_mode (AVCodecContext *avctx, QSVEncContext *q)
static int rc_supported (QSVEncContext *q)
static int init_video_param (AVCodecContext *avctx, QSVEncContext *q)
static int qsv_retrieve_enc_params (AVCodecContext *avctx, QSVEncContext *q)
static int qsv_init_opaque_alloc (AVCodecContext *avctx, QSVEncContext *q)
static int qsvenc_init_session (AVCodecContext *avctx, QSVEncContext *q)
int ff_qsv_enc_init (AVCodecContext *avctx, QSVEncContext *q)
static void free_encoder_ctrl_payloads (mfxEncodeCtrl *enc_ctrl)
static void clear_unused_frames (QSVEncContext *q)
static int get_free_frame (QSVEncContext *q, QSVFrame **f)
static int submit_frame (QSVEncContext *q, const AVFrame *frame, QSVFrame **new_frame)
static void print_interlace_msg (AVCodecContext *avctx, QSVEncContext *q)
static int encode_frame (AVCodecContext *avctx, QSVEncContext *q, const AVFrame *frame)
int ff_qsv_encode (AVCodecContext *avctx, QSVEncContext *q, AVPacket *pkt, const AVFrame *frame, int *got_packet)
int ff_qsv_enc_close (AVCodecContext *avctx, QSVEncContext *q)
Variables
struct {
mfxU16 profile
const char * name
} profile_names []
struct {
mfxU16 rc_mode
const char * name
} rc_names []
Function Documentation
print_profile()
static const char* print_profile (mfxU16 profile) static
Definition at line 72 of file qsvenc.c.
Referenced by dump_video_param().
print_ratecontrol()
static const char* print_ratecontrol (mfxU16 rc_mode) static
Definition at line 110 of file qsvenc.c.
Referenced by dump_video_param().
print_threestate()
static const char* print_threestate (mfxU16 val) static
Definition at line 119 of file qsvenc.c.
Referenced by dump_video_param().
dump_video_param()
static void dump_video_param (AVCodecContext * avctx, QSVEncContext * q, mfxExtBuffer ** coding_opts) static
Definition at line 128 of file qsvenc.c.
Referenced by qsv_retrieve_enc_params().
select_rc_mode()
static int select_rc_mode (AVCodecContext * avctx, QSVEncContext * q) static
Definition at line 263 of file qsvenc.c.
Referenced by init_video_param().
rc_supported()
static int rc_supported (QSVEncContext * q) static
Definition at line 336 of file qsvenc.c.
Referenced by init_video_param().
init_video_param()
static int init_video_param (AVCodecContext * avctx, QSVEncContext * q) static
Definition at line 348 of file qsvenc.c.
Referenced by ff_qsv_enc_init().
qsv_retrieve_enc_params()
static int qsv_retrieve_enc_params (AVCodecContext * avctx, QSVEncContext * q) static
Definition at line 543 of file qsvenc.c.
Referenced by ff_qsv_enc_init().
qsv_init_opaque_alloc()
static int qsv_init_opaque_alloc (AVCodecContext * avctx, QSVEncContext * q) static
Definition at line 617 of file qsvenc.c.
Referenced by ff_qsv_enc_init().
qsvenc_init_session()
static int qsvenc_init_session (AVCodecContext * avctx, QSVEncContext * q) static
Definition at line 654 of file qsvenc.c.
Referenced by ff_qsv_enc_init().
ff_qsv_enc_init()
int ff_qsv_enc_init (AVCodecContext * avctx, QSVEncContext * q)
Definition at line 687 of file qsvenc.c.
Referenced by qsv_enc_init().
free_encoder_ctrl_payloads()
static void free_encoder_ctrl_payloads (mfxEncodeCtrl * enc_ctrl) static
Definition at line 792 of file qsvenc.c.
Referenced by clear_unused_frames().
clear_unused_frames()
static void clear_unused_frames (QSVEncContext * q) static
Definition at line 803 of file qsvenc.c.
Referenced by get_free_frame().
get_free_frame()
static int get_free_frame (QSVEncContext * q, QSVFrame ** f) static
Definition at line 816 of file qsvenc.c.
Referenced by submit_frame().
submit_frame()
static int submit_frame (QSVEncContext * q, const AVFrame * frame, QSVFrame ** new_frame) static
Definition at line 854 of file qsvenc.c.
Referenced by encode_frame().
print_interlace_msg()
static void print_interlace_msg (AVCodecContext * avctx, QSVEncContext * q) static
Definition at line 920 of file qsvenc.c.
Referenced by encode_frame().
encode_frame()
static int encode_frame (AVCodecContext * avctx, QSVEncContext * q, const AVFrame * frame) static
Definition at line 932 of file qsvenc.c.
Referenced by ff_qsv_encode().
ff_qsv_encode()
int ff_qsv_encode (AVCodecContext * avctx, QSVEncContext * q, AVPacket * pkt, const AVFrame * frame, int * got_packet)
Definition at line 1010 of file qsvenc.c.
Referenced by qsv_enc_frame().
ff_qsv_enc_close()
int ff_qsv_enc_close (AVCodecContext * avctx, QSVEncContext * q)
Definition at line 1079 of file qsvenc.c.
Referenced by qsv_enc_close(), and qsv_enc_init().
Variable Documentation
profile
mfxU16 profile
Definition at line 44 of file qsvenc.c.
Referenced by avcodec_string(), ff_h264_get_profile(), ff_isom_write_vpcc(), ff_mediacodec_dec_init(), ff_qsv_profile_to_mfx(), ff_rtsp_open_transport_ctx(), get_vt_profile_level(), hq_decode_frame(), matroska_aac_profile(), matroska_parse_tracks(), mov_write_dvc1_structs(), parse_frame(), parse_high_res_grid(), show_stream(), vaapi_build_decoder_config(), vc1_probe(), vdpau_h264_init(), vdpau_hevc_init(), vdpau_mpeg4_init(), vdpau_mpeg_decode_slice(), vdpau_vc1_init(), vp7_decode_frame_header(), and vp9_superframe_filter().
name
const char* name
Definition at line 45 of file qsvenc.c.
profile_names
const { ... } profile_names[]
Initial value:
= {
    { MFX_PROFILE_AVC_BASELINE,                 "baseline"              },
    { MFX_PROFILE_AVC_MAIN,                     "main"                  },
    { MFX_PROFILE_AVC_EXTENDED,                 "extended"              },
    { MFX_PROFILE_AVC_HIGH,                     "high"                  },
    { MFX_PROFILE_MPEG2_SIMPLE,                 "simple"                },
    { MFX_PROFILE_MPEG2_MAIN,                   "main"                  },
    { MFX_PROFILE_MPEG2_HIGH,                   "high"                  },
    { MFX_PROFILE_VC1_SIMPLE,                   "simple"                },
    { MFX_PROFILE_VC1_MAIN,                     "main"                  },
    { MFX_PROFILE_VC1_ADVANCED,                 "advanced"              },
}
Referenced by print_profile().
rc_mode
mfxU16 rc_mode
Definition at line 82 of file qsvenc.c.
Referenced by select_rc_mode().
rc_names
const { ... } rc_names[]
Initial value:
= {
    { MFX_RATECONTROL_CBR,     "CBR" },
    { MFX_RATECONTROL_VBR,     "VBR" },
    { MFX_RATECONTROL_CQP,     "CQP" },
    { MFX_RATECONTROL_AVBR,    "AVBR" },
}
Referenced by print_ratecontrol().