FFmpeg: libavdevice/qtkit.m File Reference
qtkit.m File Reference
QTKit input device.
#import <QTKit/QTKit.h>
#include <pthread.h>
#include "libavutil/pixdesc.h"
#include "libavutil/opt.h"
#include "libavformat/internal.h"
#include "libavutil/internal.h"
#include "libavutil/time.h"
#include "avdevice.h"
Data Structures
struct CaptureContext
class FFMPEG_FrameReceiver
FrameReciever class - delegate for QTCaptureSession.
Macros
#define QTKIT_TIMEBASE 100
Functions
static void lock_frames (CaptureContext *ctx)
static void unlock_frames (CaptureContext *ctx)
static void destroy_context (CaptureContext *ctx)
static int qtkit_read_header (AVFormatContext *s)
static int qtkit_read_packet (AVFormatContext *s, AVPacket *pkt)
static int qtkit_close (AVFormatContext *s)
Variables
static const AVRational kQTKitTimeBase_q
static const AVOption options []
static const AVClass qtkit_class
AVInputFormat ff_qtkit_demuxer
Detailed Description
QTKit input device.
Author
Vadim Kalinsky vadim.nosp@m.@kal.nosp@m.insky.nosp@m..ru
Definition in file qtkit.m.
Macro Definition Documentation
QTKIT_TIMEBASE
#define QTKIT_TIMEBASE 100
Definition at line 42 of file qtkit.m.
Referenced by qtkit_read_header().
Function Documentation
lock_frames()
static void lock_frames (CaptureContext * ctx) static
Definition at line 68 of file qtkit.m.
Referenced by FFMPEG_FrameReceiver::captureOutput:didOutputVideoFrame:withSampleBuffer:fromConnection:, qtkit_read_header(), and qtkit_read_packet().
unlock_frames()
static void unlock_frames (CaptureContext * ctx) static
Definition at line 73 of file qtkit.m.
Referenced by FFMPEG_FrameReceiver::captureOutput:didOutputVideoFrame:withSampleBuffer:fromConnection:, qtkit_read_header(), and qtkit_read_packet().
destroy_context()
static void destroy_context (CaptureContext * ctx) static
Definition at line 125 of file qtkit.m.
Referenced by qtkit_close(), and qtkit_read_header().
qtkit_read_header()
static int qtkit_read_header (AVFormatContext * s) static
Definition at line 144 of file qtkit.m.
qtkit_read_packet()
static int qtkit_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 292 of file qtkit.m.
qtkit_close()
static int qtkit_close (AVFormatContext * s) static
Definition at line 327 of file qtkit.m.
Variable Documentation
kQTKitTimeBase_q
const AVRational kQTKitTimeBase_q static
Initial value:
= {
    .num = 1,
    .den = QTKIT_TIMEBASE
}
Definition at line 44 of file qtkit.m.
options
const AVOption options[] static
Initial value:
= {
    { "frame_rate", "set frame rate", 0x42, AV_OPT_TYPE_FLOAT, { .dbl = 30.0 }, 0.1, 30.0, AV_OPT_TYPE_VIDEO_RATE, NULL },
    { "list_devices", "list available devices", 0x42, AV_OPT_TYPE_INT, {.i64=0}, 0, 1, AV_OPT_FLAG_DECODING_PARAM, "list_devices" },
    { "true", "", 0, AV_OPT_TYPE_CONST, {.i64=1}, 0, 0, AV_OPT_FLAG_DECODING_PARAM, "list_devices" },
    { "false", "", 0, AV_OPT_TYPE_CONST, {.i64=0}, 0, 0, AV_OPT_FLAG_DECODING_PARAM, "list_devices" },
    { "video_device_index", "select video device by index for devices with same name (starts at 0)", 0x42, AV_OPT_TYPE_INT, {.i64 = -1}, -1, INT_MAX, AV_OPT_FLAG_DECODING_PARAM },
    { NULL },
}
Definition at line 336 of file qtkit.m.
qtkit_class
const AVClass qtkit_class static
Initial value:
= {
    .class_name = "QTKit input device",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
    .category   = AV_CLASS_CATEGORY_DEVICE_VIDEO_INPUT,
}
Definition at line 345 of file qtkit.m.
ff_qtkit_demuxer
AVInputFormat ff_qtkit_demuxer
Initial value:
= {
    .name           = "qtkit",
    .long_name      = NULL_IF_CONFIG_SMALL("QTKit input device"),
    .priv_data_size = sizeof(CaptureContext),
    .read_header    = qtkit_read_header,
    .read_packet    = qtkit_read_packet,
    .read_close     = qtkit_close,
    .flags          = AVFMT_NOFILE,
    .priv_class     = &qtkit_class,
}
Definition at line 353 of file qtkit.m.