FFmpeg: libavcodec/qtrle.c File Reference
qtrle.c File Reference
QT RLE Video Decoder by Mike Melanson (melan.nosp@m.son@.nosp@m.pcisy.nosp@m.s.ne.nosp@m.t) For more information about the QT RLE format, visit: http://www.pcisys.net/~melanson/codecs/.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
Data Structures
struct QtrleContext
Macros
#define CHECK_PIXEL_PTR(n)
Functions
static void qtrle_decode_1bpp (QtrleContext *s, int row_ptr, int lines_to_change)
static void qtrle_decode_2n4bpp (QtrleContext *s, int row_ptr, int lines_to_change, int bpp)
static void qtrle_decode_8bpp (QtrleContext *s, int row_ptr, int lines_to_change)
static void qtrle_decode_16bpp (QtrleContext *s, int row_ptr, int lines_to_change)
static void qtrle_decode_24bpp (QtrleContext *s, int row_ptr, int lines_to_change)
static void qtrle_decode_32bpp (QtrleContext *s, int row_ptr, int lines_to_change)
static av_cold int qtrle_decode_init (AVCodecContext *avctx)
static int qtrle_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int qtrle_decode_end (AVCodecContext *avctx)
Variables
AVCodec ff_qtrle_decoder
Detailed Description
QT RLE Video Decoder by Mike Melanson (melan.nosp@m.son@.nosp@m.pcisy.nosp@m.s.ne.nosp@m.t) For more information about the QT RLE format, visit: http://www.pcisys.net/~melanson/codecs/.
The QT RLE decoder has seven modes of operation: 1, 2, 4, 8, 16, 24, and 32 bits per pixel. For modes 1, 2, 4, and 8 the decoder outputs PAL8 colorspace data. 16-bit data yields RGB555 data. 24-bit data is RGB24 and 32-bit data is RGB32.
Definition in file qtrle.c.
Macro Definition Documentation
CHECK_PIXEL_PTR
#define CHECK_PIXEL_PTR (n)
Value:
if ((pixel_ptr + n > pixel_limit) || (pixel_ptr + n < 0)) {                       \
        av_log (s->avctx, AV_LOG_ERROR, "Problem: pixel_ptr = %d, pixel_limit = %d\n",\
                pixel_ptr + n, pixel_limit);                                          \
        return;                                                                       \
    }                                                                                 \
Definition at line 50 of file qtrle.c.
Referenced by qtrle_decode_16bpp(), qtrle_decode_1bpp(), qtrle_decode_24bpp(), qtrle_decode_2n4bpp(), qtrle_decode_32bpp(), and qtrle_decode_8bpp().
Function Documentation
qtrle_decode_1bpp()
static void qtrle_decode_1bpp (QtrleContext * s, int row_ptr, int lines_to_change) static
Definition at line 57 of file qtrle.c.
Referenced by qtrle_decode_frame().
qtrle_decode_2n4bpp()
static void qtrle_decode_2n4bpp (QtrleContext * s, int row_ptr, int lines_to_change, int bpp) inline static
Definition at line 142 of file qtrle.c.
Referenced by qtrle_decode_frame().
qtrle_decode_8bpp()
static void qtrle_decode_8bpp (QtrleContext * s, int row_ptr, int lines_to_change) static
Definition at line 199 of file qtrle.c.
Referenced by qtrle_decode_frame().
qtrle_decode_16bpp()
static void qtrle_decode_16bpp (QtrleContext * s, int row_ptr, int lines_to_change) static
Definition at line 248 of file qtrle.c.
Referenced by qtrle_decode_frame().
qtrle_decode_24bpp()
static void qtrle_decode_24bpp (QtrleContext * s, int row_ptr, int lines_to_change) static
Definition at line 292 of file qtrle.c.
Referenced by qtrle_decode_frame().
qtrle_decode_32bpp()
static void qtrle_decode_32bpp (QtrleContext * s, int row_ptr, int lines_to_change) static
Definition at line 339 of file qtrle.c.
Referenced by qtrle_decode_frame().
qtrle_decode_init()
static av_cold int qtrle_decode_init (AVCodecContext * avctx) static
Definition at line 383 of file qtrle.c.
qtrle_decode_frame()
static int qtrle_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 425 of file qtrle.c.
qtrle_decode_end()
static av_cold int qtrle_decode_end (AVCodecContext * avctx) static
Definition at line 532 of file qtrle.c.
Variable Documentation
ff_qtrle_decoder
AVCodec ff_qtrle_decoder
Initial value:
= {
    .name           = "qtrle",
    .long_name      = NULL_IF_CONFIG_SMALL("QuickTime Animation (RLE) video"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_QTRLE,
    .priv_data_size = sizeof(QtrleContext),
    .init           = qtrle_decode_init,
    .close          = qtrle_decode_end,
    .decode         = qtrle_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 541 of file qtrle.c.