FFmpeg: libavformat/r3d.c File Reference
r3d.c File Reference
#include "libavutil/intreadwrite.h"
#include "libavutil/dict.h"
#include "libavutil/mathematics.h"
#include "avformat.h"
#include "internal.h"
Data Structures
struct R3DContext
struct Atom
Functions
static int read_atom (AVFormatContext *s, Atom *atom)
static int r3d_read_red1 (AVFormatContext *s)
static int r3d_read_rdvo (AVFormatContext *s, Atom *atom)
static void r3d_read_reos (AVFormatContext *s)
static int r3d_read_header (AVFormatContext *s)
static int r3d_read_redv (AVFormatContext *s, AVPacket *pkt, Atom *atom)
static int r3d_read_reda (AVFormatContext *s, AVPacket *pkt, Atom *atom)
static int r3d_read_packet (AVFormatContext *s, AVPacket *pkt)
static int r3d_probe (AVProbeData *p)
static int r3d_seek (AVFormatContext *s, int stream_index, int64_t sample_time, int flags)
static int r3d_close (AVFormatContext *s)
Variables
AVInputFormat ff_r3d_demuxer
Function Documentation
read_atom()
static int read_atom (AVFormatContext * s, Atom * atom) static
Definition at line 42 of file r3d.c.
Referenced by r3d_read_header(), and r3d_read_packet().
r3d_read_red1()
static int r3d_read_red1 (AVFormatContext * s) static
Definition at line 54 of file r3d.c.
Referenced by r3d_read_header().
r3d_read_rdvo()
static int r3d_read_rdvo (AVFormatContext * s, Atom * atom) static
Definition at line 114 of file r3d.c.
Referenced by r3d_read_header().
r3d_read_reos()
static void r3d_read_reos (AVFormatContext * s) static
Definition at line 143 of file r3d.c.
Referenced by r3d_read_header().
r3d_read_header()
static int r3d_read_header (AVFormatContext * s) static
Definition at line 162 of file r3d.c.
r3d_read_redv()
static int r3d_read_redv (AVFormatContext * s, AVPacket * pkt, Atom * atom) static
Definition at line 218 of file r3d.c.
Referenced by r3d_read_packet().
r3d_read_reda()
static int r3d_read_reda (AVFormatContext * s, AVPacket * pkt, Atom * atom) static
Definition at line 273 of file r3d.c.
Referenced by r3d_read_packet().
r3d_read_packet()
static int r3d_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 337 of file r3d.c.
r3d_probe()
static int r3d_probe (AVProbeData * p) static
Definition at line 371 of file r3d.c.
r3d_seek()
static int r3d_seek (AVFormatContext * s, int stream_index, int64_t sample_time, int flags) static
Definition at line 378 of file r3d.c.
r3d_close()
static int r3d_close (AVFormatContext * s) static
Definition at line 403 of file r3d.c.
Variable Documentation
ff_r3d_demuxer
AVInputFormat ff_r3d_demuxer
Initial value:
= {
    .name           = "r3d",
    .long_name      = NULL_IF_CONFIG_SMALL("REDCODE R3D"),
    .priv_data_size = sizeof(R3DContext),
    .read_probe     = r3d_probe,
    .read_header    = r3d_read_header,
    .read_packet    = r3d_read_packet,
    .read_close     = r3d_close,
    .read_seek      = r3d_seek,
}
Definition at line 412 of file r3d.c.