FFmpeg: libavcodec/ra288.h File Reference
ra288.h File Reference
#include <stdint.h>
#include "libavutil/common.h"
Variables
static const float amptable [8]
static const int16_t codetable [128][5]
static const float syn_window [FFALIGN(111, 16)]
static const float gain_window [FFALIGN(38, 16)]
static const float syn_bw_tab [FFALIGN(36, 16)]
synthesis bandwidth broadening table
static const float gain_bw_tab [FFALIGN(10, 16)]
gain bandwidth broadening table
Variable Documentation
amptable
const float amptable[8] static
Initial value:
={
     0.515625,  0.90234375,  1.57910156,  2.76342773,
    -0.515625, -0.90234375, -1.57910156, -2.76342773
}
Definition at line 28 of file ra288.h.
Referenced by ra288_decode_frame().
codetable
const int16_t codetable[128][5] static
Definition at line 33 of file ra288.h.
Referenced by decode().
syn_window
const float syn_window[FFALIGN(111, 16)] static
Initial value:
={
  0.576690972, 0.580838025, 0.585013986, 0.589219987, 0.59345597,  0.597723007,
  0.602020264, 0.606384277, 0.610748291, 0.615142822, 0.619598389, 0.624084473,
  0.628570557, 0.633117676, 0.637695313, 0.642272949, 0.646911621, 0.651580811,
  0.656280518, 0.66104126,  0.665802002, 0.670593262, 0.675445557, 0.680328369,
  0.685241699, 0.690185547, 0.695159912, 0.700164795, 0.705230713, 0.710327148,
  0.715454102, 0.720611572, 0.725830078, 0.731048584, 0.736328125, 0.741638184,
  0.747009277, 0.752380371, 0.7578125,   0.763305664, 0.768798828, 0.774353027,
  0.779937744, 0.785583496, 0.791229248, 0.796936035, 0.802703857, 0.808502197,
  0.814331055, 0.820220947, 0.826141357, 0.832092285, 0.838104248, 0.844146729,
  0.850250244, 0.856384277, 0.862548828, 0.868774414, 0.875061035, 0.881378174,
  0.88772583,  0.894134521, 0.900604248, 0.907104492, 0.913635254, 0.920227051,
  0.926879883, 0.933563232, 0.940307617, 0.94708252,  0.953918457, 0.96081543,
  0.96774292,  0.974731445, 0.981781006, 0.988861084, 0.994842529, 0.998565674,
  0.999969482, 0.99911499,  0.996002197, 0.990600586, 0.982910156, 0.973022461,
  0.960876465, 0.946533203, 0.930053711, 0.911437988, 0.89074707,  0.868041992,
  0.843322754, 0.816680908, 0.788208008, 0.757904053, 0.725891113, 0.692199707,
  0.656921387, 0.620178223, 0.582000732, 0.542480469, 0.501739502, 0.459838867,
  0.416900635, 0.373016357, 0.328277588, 0.282775879, 0.236663818, 0.189971924,
  0.142852783, 0.0954284668,0.0477600098
}
Definition at line 100 of file ra288.h.
Referenced by ra288_decode_frame().
gain_window
const float gain_window[FFALIGN(38, 16)] static
Initial value:
={
  0.505699992, 0.524200022, 0.54339999,  0.563300014, 0.583953857, 0.60534668,
  0.627502441, 0.650482178, 0.674316406, 0.699005127, 0.724578857, 0.75112915,
  0.778625488, 0.807128906, 0.836669922, 0.86730957,  0.899078369, 0.932006836,
  0.961486816, 0.982757568, 0.995635986, 1,           0.995819092, 0.983154297,
  0.96206665,  0.932769775, 0.895507813, 0.850585938, 0.798400879, 0.739379883,
  0.674072266, 0.602996826, 0.526763916, 0.446014404, 0.361480713, 0.273834229,
  0.183868408, 0.0923461914
}
Definition at line 122 of file ra288.h.
Referenced by ra288_decode_frame().
syn_bw_tab
const float syn_bw_tab[FFALIGN(36, 16)] static
Initial value:
= {
  0.98828125,  0.976699829, 0.965254128, 0.953942537, 0.942763507, 0.931715488,
  0.920796931, 0.910006344, 0.899342179, 0.888803005, 0.878387332, 0.868093729,
  0.857920766, 0.847867012, 0.837931097, 0.828111589, 0.818407178, 0.808816493,
  0.799338162, 0.789970934, 0.780713439, 0.771564424, 0.762522638, 0.753586829,
  0.744755745, 0.736028135, 0.727402806, 0.718878567, 0.710454226, 0.702128589,
  0.693900526, 0.685768902, 0.677732527, 0.669790328, 0.66194123,  0.654184103
}
synthesis bandwidth broadening table
Definition at line 133 of file ra288.h.
Referenced by ra288_decode_frame().
gain_bw_tab
const float gain_bw_tab[FFALIGN(10, 16)] static
Initial value:
= {
  0.90625,     0.821289063, 0.74432373,  0.674499512, 0.61126709,
  0.553955078, 0.50201416,  0.454956055, 0.41229248,  0.373657227
}
gain bandwidth broadening table
Definition at line 143 of file ra288.h.
Referenced by ra288_decode_frame().