FFmpeg: libavutil/random_seed.c File Reference
random_seed.c File Reference
#include "config.h"
#include <fcntl.h>
#include <math.h>
#include <time.h>
#include <string.h>
#include "avassert.h"
#include "internal.h"
#include "intreadwrite.h"
#include "timer.h"
#include "random_seed.h"
#include "sha.h"
Macros
#define TEST 0
Functions
static int read_random (uint32_t *dst, const char *file)
static uint32_t get_generic_seed (void)
uint32_t av_get_random_seed (void)
Get a seed to use in conjunction with random functions.
Macro Definition Documentation
TEST
#define TEST 0
Definition at line 45 of file random_seed.c.
Referenced by get_generic_seed().
Function Documentation
read_random()
static int read_random (uint32_t * dst, const char * file) static
Definition at line 48 of file random_seed.c.
Referenced by av_get_random_seed().
get_generic_seed()
static uint32_t get_generic_seed (void) static
Definition at line 65 of file random_seed.c.
Referenced by av_get_random_seed(), and main().