FFmpeg: libavcodec/rangecoder.c File Reference
rangecoder.c File Reference
Range coder.
#include <string.h>
#include "libavutil/attributes.h"
#include "libavutil/avassert.h"
#include "libavutil/intreadwrite.h"
#include "avcodec.h"
#include "rangecoder.h"
Functions
av_cold void ff_init_range_encoder (RangeCoder *c, uint8_t *buf, int buf_size)
av_cold void ff_init_range_decoder (RangeCoder *c, const uint8_t *buf, int buf_size)
void ff_build_rac_states (RangeCoder *c, int factor, int max_p)
int ff_rac_terminate (RangeCoder *c)
Detailed Description
Range coder.
based upon "Range encoding: an algorithm for removing redundancy from a digitised message. G. N. N. Martin Presented in March 1979 to the Video & Data Recording Conference, IBM UK Scientific Center held in Southampton July 24-27 1979."
Definition in file rangecoder.c.
Function Documentation
ff_init_range_encoder()
av_cold void ff_init_range_encoder (RangeCoder * c, uint8_t * buf, int buf_size)
Definition at line 42 of file rangecoder.c.
Referenced by encode_frame(), ff_init_range_decoder(), main(), predictor_calc_error(), and write_extradata().
ff_init_range_decoder()
av_cold void ff_init_range_decoder (RangeCoder * c, const uint8_t * buf, int buf_size)
Definition at line 53 of file rangecoder.c.
Referenced by decode_frame(), main(), predictor_calc_error(), and read_extra_header().
ff_build_rac_states()
void ff_build_rac_states (RangeCoder * c, int factor, int max_p)
Definition at line 63 of file rangecoder.c.
Referenced by decode_frame(), encode_frame(), encode_init(), main(), predictor_calc_error(), read_extra_header(), and write_extradata().
ff_rac_terminate()
int ff_rac_terminate (RangeCoder * c)
Definition at line 104 of file rangecoder.c.
Referenced by encode_frame(), encode_slice(), main(), predictor_calc_error(), and write_extradata().