FFmpeg: libavcodec/rangecoder.h File Reference
rangecoder.h File Reference
Range coder.
#include <stdint.h>
#include "libavutil/common.h"
#include "libavutil/avassert.h"
Data Structures
struct RangeCoder
Functions
void ff_init_range_encoder (RangeCoder *c, uint8_t *buf, int buf_size)
void ff_init_range_decoder (RangeCoder *c, const uint8_t *buf, int buf_size)
int ff_rac_terminate (RangeCoder *c)
void ff_build_rac_states (RangeCoder *c, int factor, int max_p)
static void renorm_encoder (RangeCoder *c)
static int get_rac_count (RangeCoder *c)
static void put_rac (RangeCoder *c, uint8_t *const state, int bit)
static void refill (RangeCoder *c)
static int get_rac (RangeCoder *c, uint8_t *const state)
Detailed Description
Range coder.
Definition in file rangecoder.h.
Function Documentation
ff_init_range_encoder()
void ff_init_range_encoder (RangeCoder * c, uint8_t * buf, int buf_size)
Definition at line 42 of file rangecoder.c.
Referenced by encode_frame(), ff_init_range_decoder(), main(), predictor_calc_error(), and write_extradata().
ff_init_range_decoder()
void ff_init_range_decoder (RangeCoder * c, const uint8_t * buf, int buf_size)
Definition at line 53 of file rangecoder.c.
Referenced by decode_frame(), main(), predictor_calc_error(), and read_extra_header().
ff_rac_terminate()
int ff_rac_terminate (RangeCoder * c)
Definition at line 104 of file rangecoder.c.
Referenced by encode_frame(), encode_slice(), main(), predictor_calc_error(), and write_extradata().
ff_build_rac_states()
void ff_build_rac_states (RangeCoder * c, int factor, int max_p)
Definition at line 63 of file rangecoder.c.
Referenced by decode_frame(), encode_frame(), encode_init(), main(), predictor_calc_error(), read_extra_header(), and write_extradata().
renorm_encoder()
static void renorm_encoder (RangeCoder * c) inline static
Definition at line 52 of file rangecoder.h.
Referenced by ff_rac_terminate(), and put_rac().
get_rac_count()
static int get_rac_count (RangeCoder * c) inline static
Definition at line 77 of file rangecoder.h.
Referenced by encode_q_branch().
put_rac()
static void put_rac (RangeCoder * c, uint8_t *const state, int bit) inline static
Definition at line 85 of file rangecoder.h.
refill()
static void refill (RangeCoder * c) inline static
Definition at line 104 of file rangecoder.h.
Referenced by get_rac().
get_rac()
static int get_rac (RangeCoder * c, uint8_t *const state) inline static
Definition at line 115 of file rangecoder.h.
Referenced by decode_frame(), decode_header(), decode_line(), decode_q_branch(), decode_slice(), decode_slice_header(), get_symbol(), get_symbol2(), get_symbol_inline(), main(), read_extra_header(), read_header(), and unpack_coeffs().