FFmpeg: libavcodec/ratecontrol.h File Reference
ratecontrol.h File Reference
ratecontrol header.
#include <stdio.h>
#include <stdint.h>
#include "libavutil/eval.h"
Data Structures
struct Predictor
struct RateControlEntry
struct RateControlContext
rate control context.
Functions
int ff_rate_control_init (struct MpegEncContext *s)
float ff_rate_estimate_qscale (struct MpegEncContext *s, int dry_run)
void ff_write_pass1_stats (struct MpegEncContext *s)
void ff_rate_control_uninit (struct MpegEncContext *s)
int ff_vbv_update (struct MpegEncContext *s, int frame_size)
void ff_get_2pass_fcode (struct MpegEncContext *s)
int ff_xvid_rate_control_init (struct MpegEncContext *s)
void ff_xvid_rate_control_uninit (struct MpegEncContext *s)
float ff_xvid_rate_estimate_qscale (struct MpegEncContext *s, int dry_run)
Detailed Description
ratecontrol header.
Definition in file ratecontrol.h.
Function Documentation
ff_rate_control_init()
int ff_rate_control_init (struct MpegEncContext * s)
Definition at line 84 of file ratecontrol.c.
Referenced by encode_init(), and ff_mpv_encode_init().
ff_rate_estimate_qscale()
float ff_rate_estimate_qscale (struct MpegEncContext * s, int dry_run)
Definition at line 753 of file ratecontrol.c.
Referenced by encode_frame(), estimate_qp(), and ratecontrol_1pass().
ff_write_pass1_stats()
void ff_write_pass1_stats (struct MpegEncContext * s)
Definition at line 42 of file ratecontrol.c.
Referenced by encode_frame(), and ff_mpv_encode_picture().
ff_rate_control_uninit()
void ff_rate_control_uninit (struct MpegEncContext * s)
Definition at line 312 of file ratecontrol.c.
Referenced by encode_end(), ff_mpv_encode_end(), and ff_rate_control_init().
ff_vbv_update()
int ff_vbv_update (struct MpegEncContext * s, int frame_size)
Definition at line 326 of file ratecontrol.c.
Referenced by ff_mpv_encode_picture(), init_pass2(), and select_input_picture().
ff_get_2pass_fcode()
void ff_get_2pass_fcode (struct MpegEncContext * s)
Definition at line 742 of file ratecontrol.c.
Referenced by encode_picture().
ff_xvid_rate_control_init()
int ff_xvid_rate_control_init (struct MpegEncContext * s)
Definition at line 42 of file libxvid_rc.c.
Referenced by ff_rate_control_init().
ff_xvid_rate_control_uninit()
void ff_xvid_rate_control_uninit (struct MpegEncContext * s)
Definition at line 158 of file libxvid_rc.c.
Referenced by ff_rate_control_uninit().
ff_xvid_rate_estimate_qscale()
float ff_xvid_rate_estimate_qscale (struct MpegEncContext * s, int dry_run)
Definition at line 101 of file libxvid_rc.c.
Referenced by ff_rate_estimate_qscale().