FFmpeg: libavcodec/raw.h File Reference
raw.h File Reference
Raw Video Codec.
#include "avcodec.h"
#include "libavutil/internal.h"
Data Structures
struct PixelFormatTag
Functions
const struct PixelFormatTag * avpriv_get_raw_pix_fmt_tags (void)
enum AVPixelFormat avpriv_find_pix_fmt (const PixelFormatTag *tags, unsigned int fourcc)
Variables
const PixelFormatTag ff_raw_pix_fmt_tags []
av_export const PixelFormatTag avpriv_pix_fmt_bps_avi []
av_export const PixelFormatTag avpriv_pix_fmt_bps_mov []
Detailed Description
Raw Video Codec.
Definition in file raw.h.
Function Documentation
avpriv_get_raw_pix_fmt_tags()
const struct PixelFormatTag* avpriv_get_raw_pix_fmt_tags (void)
Definition at line 283 of file raw.c.
Referenced by avformat_find_stream_info(), dshow_pixfmt(), and main().
avpriv_find_pix_fmt()
enum AVPixelFormat avpriv_find_pix_fmt (const PixelFormatTag * tags, unsigned int fourcc)
Definition at line 1031 of file utils.c.
Referenced by avformat_find_stream_info(), avi_write_header(), dshow_pixfmt(), frm_read_header(), mov_get_rawvideo_codec_tag(), and raw_init_decoder().
Variable Documentation
ff_raw_pix_fmt_tags
const PixelFormatTag ff_raw_pix_fmt_tags[]
Definition at line 31 of file raw.c.
Referenced by avcodec_pix_fmt_to_codec_tag(), avpriv_get_raw_pix_fmt_tags(), and raw_init_decoder().
avpriv_pix_fmt_bps_avi
av_export const PixelFormatTag avpriv_pix_fmt_bps_avi[]
Definition at line 299 of file raw.c.
Referenced by avi_write_header(), and raw_init_decoder().
avpriv_pix_fmt_bps_mov
av_export const PixelFormatTag avpriv_pix_fmt_bps_mov[]
Definition at line 312 of file raw.c.
Referenced by mov_get_rawvideo_codec_tag(), and raw_init_decoder().