FFmpeg: libavcodec/rdft.c File Reference
rdft.c File Reference
(Inverse) Real Discrete Fourier Transforms.
#include <stdlib.h>
#include <math.h>
#include "libavutil/mathematics.h"
#include "rdft.h"
Functions
SINTABLE (16)
SINTABLE (32)
SINTABLE (64)
SINTABLE (128)
SINTABLE (256)
SINTABLE (512)
SINTABLE (1024)
SINTABLE (2048)
SINTABLE (4096)
SINTABLE (8192)
SINTABLE (16384)
SINTABLE (32768)
SINTABLE (65536)
static void rdft_calc_c (RDFTContext *s, FFTSample *data)
Map one real FFT into two parallel real even and odd FFTs.
av_cold int ff_rdft_init (RDFTContext *s, int nbits, enum RDFTransformType trans)
Set up a real FFT.
av_cold void ff_rdft_end (RDFTContext *s)
Variables
static SINTABLE_CONST FFTSample *const ff_sin_tabs []
Detailed Description
(Inverse) Real Discrete Fourier Transforms.
Definition in file rdft.c.
Function Documentation
SINTABLE() [1/13]
SINTABLE (16)
SINTABLE() [2/13]
SINTABLE (32)
SINTABLE() [3/13]
SINTABLE (64)
SINTABLE() [4/13]
SINTABLE (128)
SINTABLE() [5/13]
SINTABLE (256)
SINTABLE() [6/13]
SINTABLE (512)
SINTABLE() [7/13]
SINTABLE (1024)
SINTABLE() [8/13]
SINTABLE (2048)
SINTABLE() [9/13]
SINTABLE (4096)
SINTABLE() [10/13]
SINTABLE (8192)
SINTABLE() [11/13]
SINTABLE (16384)
SINTABLE() [12/13]
SINTABLE (32768)
SINTABLE() [13/13]
SINTABLE (65536)
rdft_calc_c()
static void rdft_calc_c (RDFTContext * s, FFTSample * data) static
Map one real FFT into two parallel real even and odd FFTs.
Then interleave the two real FFTs into one complex FFT. Unmangle the results. ref: http://www.engineeringproductivitytools.com/stuff/T0001/PT10.HTM
Definition at line 57 of file rdft.c.
Referenced by ff_rdft_init().
ff_rdft_init()
av_cold int ff_rdft_init (RDFTContext * s, int nbits, enum RDFTransformType trans)
Set up a real FFT.
Parameters
nbits log2 of the length of the input array
trans the type of transform
Definition at line 99 of file rdft.c.
Referenced by av_fft_end(), decode_init(), ff_dct_init(), fft_end(), qdm2_decode_init(), and wmavoice_decode_init().
ff_rdft_end()
av_cold void ff_rdft_end (RDFTContext * s)
Definition at line 132 of file rdft.c.
Referenced by av_fft_end(), decode_end(), ff_dct_end(), fft_end(), qdm2_decode_close(), and wmavoice_decode_end().
Variable Documentation
ff_sin_tabs
SINTABLE_CONST FFTSample* const ff_sin_tabs[] static
Initial value:
= {
    NULL, NULL, NULL, NULL,
    ff_sin_16, ff_sin_32, ff_sin_64, ff_sin_128, ff_sin_256, ff_sin_512, ff_sin_1024,
    ff_sin_2048, ff_sin_4096, ff_sin_8192, ff_sin_16384, ff_sin_32768, ff_sin_65536,
}
Definition at line 47 of file rdft.c.
Referenced by ff_rdft_init().