FFmpeg: libavcodec/rdft.h File Reference
rdft.h File Reference
#include "config.h"
#include "fft.h"
Data Structures
struct RDFTContext
Macros
#define AVCODEC_RDFT_H
#define SINTABLE_CONST
#define SINTABLE(size) SINTABLE_CONST DECLARE_ALIGNED(16, FFTSample, ff_sin_##size)[size/2]
Functions
SINTABLE (16)
SINTABLE (32)
SINTABLE (64)
SINTABLE (128)
SINTABLE (256)
SINTABLE (512)
SINTABLE (1024)
SINTABLE (2048)
SINTABLE (4096)
SINTABLE (8192)
SINTABLE (16384)
SINTABLE (32768)
SINTABLE (65536)
int ff_rdft_init (RDFTContext *s, int nbits, enum RDFTransformType trans)
Set up a real FFT.
void ff_rdft_end (RDFTContext *s)
void ff_rdft_init_arm (RDFTContext *s)
Macro Definition Documentation
AVCODEC_RDFT_H
#define AVCODEC_RDFT_H
Definition at line 23 of file rdft.h.
SINTABLE_CONST
#define SINTABLE_CONST
Definition at line 31 of file rdft.h.
SINTABLE
#define SINTABLE (size) SINTABLE_CONST DECLARE_ALIGNED(16, FFTSample, ff_sin_##size)[size/2]
Definition at line 34 of file rdft.h.
Function Documentation
SINTABLE() [1/13]
SINTABLE (16)
SINTABLE() [2/13]
SINTABLE (32)
SINTABLE() [3/13]
SINTABLE (64)
SINTABLE() [4/13]
SINTABLE (128)
SINTABLE() [5/13]
SINTABLE (256)
SINTABLE() [6/13]
SINTABLE (512)
SINTABLE() [7/13]
SINTABLE (1024)
SINTABLE() [8/13]
SINTABLE (2048)
SINTABLE() [9/13]
SINTABLE (4096)
SINTABLE() [10/13]
SINTABLE (8192)
SINTABLE() [11/13]
SINTABLE (16384)
SINTABLE() [12/13]
SINTABLE (32768)
SINTABLE() [13/13]
SINTABLE (65536)
ff_rdft_init()
int ff_rdft_init (RDFTContext * s, int nbits, enum RDFTransformType trans)
Set up a real FFT.
Parameters
nbits log2 of the length of the input array
trans the type of transform
Definition at line 99 of file rdft.c.
Referenced by av_fft_end(), decode_init(), ff_dct_init(), fft_end(), qdm2_decode_init(), and wmavoice_decode_init().
ff_rdft_end()
void ff_rdft_end (RDFTContext * s)
Definition at line 132 of file rdft.c.
Referenced by av_fft_end(), decode_end(), ff_dct_end(), fft_end(), qdm2_decode_close(), and wmavoice_decode_end().
ff_rdft_init_arm()
void ff_rdft_init_arm (RDFTContext * s)
Definition at line 27 of file rdft_init_arm.c.
Referenced by ff_rdft_init().