FFmpeg: libswresample/x86/rematrix_init.c File Reference
rematrix_init.c File Reference
#include "libavutil/x86/cpu.h"
#include "libswresample/swresample_internal.h"
Macros
#define D(type, simd)
Functions
D (D(float, sse)
Macro Definition Documentation
D
#define D (type, simd)
Value:
mix_1_1_func_type ff_mix_1_1_a_## type ## _ ## simd;\
mix_2_1_func_type ff_mix_2_1_a_## type ## _ ## simd;
Definition at line 24 of file rematrix_init.c.
Function Documentation
D()
D (D(float, sse)
Definition at line 28 of file rematrix_init.c.
Referenced by avg_no_rnd_vc1_chroma_mc4_c(), avg_no_rnd_vc1_chroma_mc8_c(), butterworth_fo_section(), chebyshev1_fo_section(), color_graticule(), color_graticule16(), decode_haar_block(), ff_avg_h264_chroma_mc4_mmi(), ff_avg_h264_chroma_mc8_mmi(), ff_avg_no_rnd_vc1_chroma_mc4_mmi(), ff_avg_no_rnd_vc1_chroma_mc8_mmi(), ff_put_h264_chroma_mc4_mmi(), ff_put_h264_chroma_mc8_mmi(), ff_put_no_rnd_vc1_chroma_mc4_mmi(), ff_put_no_rnd_vc1_chroma_mc8_mmi(), gmc1_c(), horizX1Filter(), idct(), put_no_rnd_vc1_chroma_mc4_c(), and put_no_rnd_vc1_chroma_mc8_c().