FFmpeg: libswresample/rematrix_template.c File Reference
rematrix_template.c File Reference
Functions
typedef void (RENAME(mix_any_func_type))
static void RENAME() copy (SAMPLE *out, const SAMPLE *in, COEFF *coeffp, integer index, integer len)
static void RENAME() mix6to2 (SAMPLE **out, const SAMPLE **in, COEFF *coeffp, integer len)
static void RENAME() mix8to2 (SAMPLE **out, const SAMPLE **in, COEFF *coeffp, integer len)
static RENAME (mix_any_func_type)
Function Documentation
void()
typedef void (RENAME(mix_any_func_type))
Definition at line 52 of file rematrix_template.c.
Referenced by av_vlog(), bayer_to_rgb24_wrapper(), bayer_to_yv12_wrapper(), check_idct(), check_idct_dc4(), check_loopfilter_16y(), check_loopfilter_8uv(), check_loopfilter_simple(), check_luma_dc_wht(), checkasm_check_h264pred(), dct_error(), encode_dvb_subtitles(), flush_packet(), glob_vector(), hl_decode_mb(), hl_decode_mb_idct_luma(), hl_decode_mb_predict_luma(), main(), palToRgbWrapper(), sgi_rle_encode(), spectral_to_sample(), and vaapi_encode_h264_write_sei().
copy()
static void RENAME() copy (SAMPLE * out, const SAMPLE * in, COEFF * coeffp, integer index, integer len) static
Definition at line 63 of file rematrix_template.c.
mix6to2()
static void RENAME() mix6to2 (SAMPLE ** out, const SAMPLE ** in, COEFF * coeffp, integer len) static
Definition at line 70 of file rematrix_template.c.
Referenced by RENAME().
mix8to2()
static void RENAME() mix8to2 (SAMPLE ** out, const SAMPLE ** in, COEFF * coeffp, integer len) static
Definition at line 80 of file rematrix_template.c.
Referenced by RENAME().
RENAME()
static RENAME (mix_any_func_type) static
Definition at line 90 of file rematrix_template.c.