FFmpeg: libavformat/riff.h File Reference
riff.h File Reference
internal header for RIFF based (de)muxers do NOT include this in end user applications
#include "libavcodec/avcodec.h"
#include "avio.h"
#include "internal.h"
#include "metadata.h"
Data Structures
struct AVCodecGuid
Macros
#define FF_PUT_WAV_HEADER_FORCE_WAVEFORMATEX 0x00000001
Tell ff_put_wav_header() to use WAVEFORMATEX even for PCM codecs.
#define FF_PUT_WAV_HEADER_SKIP_CHANNELMASK 0x00000002
Tell ff_put_wav_header() to write an empty channel mask.
#define FF_PRI_GUID
#define FF_ARG_GUID(g)
#define FF_MEDIASUBTYPE_BASE_GUID 0x00, 0x00, 0x10, 0x00, 0x80, 0x00, 0x00, 0xAA, 0x00, 0x38, 0x9B, 0x71
#define FF_AMBISONIC_BASE_GUID 0x21, 0x07, 0xD3, 0x11, 0x86, 0x44, 0xC8, 0xC1, 0xCA, 0x00, 0x00, 0x00
Typedefs
typedef uint8_t ff_asf_guid[16]
Functions
int64_t ff_start_tag (AVIOContext *pb, const char *tag)
void ff_end_tag (AVIOContext *pb, int64_t start)
int ff_get_bmp_header (AVIOContext *pb, AVStream *st, unsigned *esize)
Read BITMAPINFOHEADER structure and set AVStream codec width, height and bits_per_encoded_sample fields.
void ff_put_bmp_header (AVIOContext *pb, AVCodecParameters *par, const AVCodecTag *tags, int for_asf, int ignore_extradata)
int ff_put_wav_header (AVFormatContext *s, AVIOContext *pb, AVCodecParameters *par, int flags)
Write WAVEFORMAT header structure.
enum AVCodecID ff_wav_codec_get_id (unsigned int tag, int bps)
int ff_get_wav_header (AVFormatContext *s, AVIOContext *pb, AVCodecParameters *par, int size, int big_endian)
void ff_parse_specific_params (AVStream *st, int *au_rate, int *au_ssize, int *au_scale)
int ff_read_riff_info (AVFormatContext *s, int64_t size)
void ff_riff_write_info (AVFormatContext *s)
Write all recognized RIFF tags from s->metadata.
void ff_riff_write_info_tag (AVIOContext *pb, const char *tag, const char *str)
Write a single RIFF info tag.
static av_always_inline int ff_guidcmp (const void *g1, const void *g2)
int ff_get_guid (AVIOContext *s, ff_asf_guid *g)
void ff_put_guid (AVIOContext *s, const ff_asf_guid *g)
const ff_asf_guid * ff_get_codec_guid (enum AVCodecID id, const AVCodecGuid *av_guid)
enum AVCodecID ff_codec_guid_get_id (const AVCodecGuid *guids, ff_asf_guid guid)
Variables
const AVMetadataConv ff_riff_info_conv []
const AVCodecTag ff_codec_bmp_tags []
const AVCodecTag ff_codec_wav_tags []
const AVCodecGuid ff_codec_wav_guids []
Detailed Description
internal header for RIFF based (de)muxers do NOT include this in end user applications
Definition in file riff.h.
Macro Definition Documentation
FF_PUT_WAV_HEADER_FORCE_WAVEFORMATEX
#define FF_PUT_WAV_HEADER_FORCE_WAVEFORMATEX 0x00000001
Tell ff_put_wav_header() to use WAVEFORMATEX even for PCM codecs.
Definition at line 53 of file riff.h.
Referenced by asf_write_header1(), ff_put_wav_header(), mkv_write_codecprivate(), and mov_write_wfex_tag().
FF_PUT_WAV_HEADER_SKIP_CHANNELMASK
#define FF_PUT_WAV_HEADER_SKIP_CHANNELMASK 0x00000002
Tell ff_put_wav_header() to write an empty channel mask.
Definition at line 58 of file riff.h.
Referenced by avi_write_header(), and ff_put_wav_header().
FF_PRI_GUID
#define FF_PRI_GUID
Value:
"%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x " \
    "{%02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-%02x%02x%02x%02x%02x%02x}"
Definition at line 98 of file riff.h.
Referenced by parse_chunks(), parse_legacy_attrib(), parse_media_type(), parse_waveformatex(), qcp_read_header(), set_spdif(), and wtvfile_open2().
FF_ARG_GUID
#define FF_ARG_GUID (g)
Value:
g[0], g[1], g[2],  g[3],  g[4],  g[5],  g[6],  g[7], \
    g[8], g[9], g[10], g[11], g[12], g[13], g[14], g[15],\
    g[3], g[2], g[1],  g[0],  g[5],  g[4],  g[7],  g[6], \
    g[8], g[9], g[10], g[11], g[12], g[13], g[14], g[15]
Definition at line 102 of file riff.h.
Referenced by parse_chunks(), parse_legacy_attrib(), parse_media_type(), parse_waveformatex(), qcp_read_header(), set_spdif(), and wtvfile_open2().
FF_MEDIASUBTYPE_BASE_GUID
#define FF_MEDIASUBTYPE_BASE_GUID 0x00, 0x00, 0x10, 0x00, 0x80, 0x00, 0x00, 0xAA, 0x00, 0x38, 0x9B, 0x71
Definition at line 108 of file riff.h.
Referenced by parse_media_type(), parse_waveformatex(), and write_stream_codec_info().
FF_AMBISONIC_BASE_GUID
#define FF_AMBISONIC_BASE_GUID 0x21, 0x07, 0xD3, 0x11, 0x86, 0x44, 0xC8, 0xC1, 0xCA, 0x00, 0x00, 0x00
Definition at line 110 of file riff.h.
Referenced by parse_waveformatex().
Typedef Documentation
ff_asf_guid
typedef uint8_t ff_asf_guid[16]
Definition at line 89 of file riff.h.
Function Documentation
ff_start_tag()
int64_t ff_start_tag (AVIOContext * pb, const char * tag)
Definition at line 31 of file riffenc.c.
Referenced by avi_start_new_riff(), avi_write_header(), avi_write_idx1(), avi_write_packet(), ff_riff_write_info(), mmf_rate(), and write_odml_master().
ff_end_tag()
void ff_end_tag (AVIOContext * pb, int64_t start)
Definition at line 38 of file riffenc.c.
Referenced by avi_write_header(), avi_write_idx1(), avi_write_packet(), avi_write_packet_internal(), avi_write_trailer(), ff_riff_write_info(), and write_odml_master().
ff_get_bmp_header()
int ff_get_bmp_header (AVIOContext * pb, AVStream * st, unsigned * esize)
Read BITMAPINFOHEADER structure and set AVStream codec width, height and bits_per_encoded_sample fields.
Does not read extradata.
Returns
codec tag
Definition at line 208 of file riffdec.c.
Referenced by avi_read_header(), parse_video_info(), and parse_videoinfoheader2().
ff_put_bmp_header()
void ff_put_bmp_header (AVIOContext * pb, AVCodecParameters * par, const AVCodecTag * tags, int for_asf, int ignore_extradata)
Definition at line 209 of file riffenc.c.
Referenced by asf_write_header1(), avi_write_header(), mkv_write_codecprivate(), and put_videoinfoheader2().
ff_put_wav_header()
int ff_put_wav_header (AVFormatContext * s, AVIOContext * pb, AVCodecParameters * par, int flags)
Write WAVEFORMAT header structure.
Parameters
flags a combination of FF_PUT_WAV_HEADER_* constants
Returns
the size or -1 on error
Definition at line 54 of file riffenc.c.
Referenced by asf_write_header1(), avi_write_header(), mkv_write_codecprivate(), mov_write_ms_tag(), mov_write_wfex_tag(), and write_stream_codec_info().
ff_wav_codec_get_id()
enum AVCodecID ff_wav_codec_get_id (unsigned int tag, int bps)
Definition at line 191 of file riffdec.c.
Referenced by ff_get_wav_header(), get_codec_data(), parse_media_type(), parse_waveformatex(), and xmv_read_header().
ff_get_wav_header()
int ff_get_wav_header (AVFormatContext * s, AVIOContext * pb, AVCodecParameters * par, int size, int big_endian)
Definition at line 88 of file riffdec.c.
Referenced by asf_read_stream_properties(), avi_read_header(), dxa_read_header(), matroska_parse_tracks(), mov_read_wfex(), parse_media_type(), read_header(), scan_file(), set_spdif(), and xwma_read_header().
ff_parse_specific_params()
void ff_parse_specific_params (AVStream * st, int * au_rate, int * au_ssize, int * au_scale)
Definition at line 265 of file riffenc.c.
Referenced by avi_write_counters(), avi_write_header(), nut_write_header(), and update_odml_entry().
ff_read_riff_info()
int ff_read_riff_info (AVFormatContext * s, int64_t size)
Definition at line 226 of file riffdec.c.
Referenced by avi_load_index(), avi_read_header(), and set_spdif().
ff_riff_write_info()
void ff_riff_write_info (AVFormatContext * s)
Write all recognized RIFF tags from s->metadata.
Definition at line 327 of file riffenc.c.
Referenced by avi_write_header().
ff_riff_write_info_tag()
void ff_riff_write_info_tag (AVIOContext * pb, const char * tag, const char * str)
Write a single RIFF info tag.
Definition at line 295 of file riffenc.c.
Referenced by avi_write_header(), and ff_riff_write_info().
ff_guidcmp()
static av_always_inline int ff_guidcmp (const void * g1, const void * g2) static
Definition at line 113 of file riff.h.
Referenced by asf_build_simple_index(), asf_probe(), asf_read_header(), asf_read_stream_properties(), ff_codec_guid_get_id(), parse_chunks(), parse_legacy_attrib(), parse_media_type(), read_probe(), and wtvfile_open2().
ff_get_guid()
int ff_get_guid (AVIOContext * s, ff_asf_guid * g)
Definition at line 32 of file riffdec.c.
Referenced by asf_build_simple_index(), asf_read_ext_stream_properties(), asf_read_file_properties(), asf_read_header(), asf_read_stream_properties(), detect_unknown_subobject(), ff_guidcmp(), parse_chunks(), parse_legacy_attrib(), parse_media_type(), parse_waveformatex(), and process_metadata().
ff_put_guid()
void ff_put_guid (AVIOContext * s, const ff_asf_guid * g)
Definition at line 349 of file riffenc.c.
Referenced by asf_write_header1(), asf_write_index(), asf_write_markers(), ff_guidcmp(), ff_put_wav_header(), put_header(), write_chunk_header(), write_header(), write_index(), write_metadata_header(), write_root_table(), and write_stream_codec_info().
ff_get_codec_guid()
const ff_asf_guid* ff_get_codec_guid (enum AVCodecID id, const AVCodecGuid * av_guid)
Definition at line 355 of file riffenc.c.
Referenced by ff_guidcmp(), ff_put_wav_header(), and write_stream_codec_info().
ff_codec_guid_get_id()
enum AVCodecID ff_codec_guid_get_id (const AVCodecGuid * guids, ff_asf_guid guid)
Definition at line 44 of file riffdec.c.
Referenced by ff_guidcmp(), parse_media_type(), and parse_waveformatex().
Variable Documentation
ff_riff_info_conv
const AVMetadataConv ff_riff_info_conv[]
Definition at line 524 of file riff.c.
Referenced by avi_read_header(), ff_riff_write_info(), and set_spdif().
ff_codec_bmp_tags
const AVCodecTag ff_codec_bmp_tags[]
Definition at line 32 of file riff.c.
Referenced by asf_read_stream_properties(), asf_write_header1(), avformat_get_riff_video_tags(), avi_read_header(), avi_write_header(), decode_stream_header(), get_codec_data(), lvf_read_header(), matroska_parse_tracks(), mkv_write_codecprivate(), mkv_write_track(), mov_codec_id(), mov_get_codec_tag(), nut_read_header(), ogm_dshow_header(), ogm_header(), parse_media_type(), parse_video_info(), put_videoinfoheader2(), read_header(), and write_stream_codec_info().
ff_codec_wav_tags
const AVCodecTag ff_codec_wav_tags[]
Definition at line 440 of file riff.c.
Referenced by avformat_get_riff_audio_tags(), decode_stream_header(), ff_wav_codec_get_id(), lvf_read_header(), mkv_write_codecprivate(), mov_codec_id(), mov_get_codec_tag(), mov_write_isml_manifest(), nut_read_header(), ogm_dshow_header(), ogm_header(), set_spdif(), and write_stream_codec_info().
ff_codec_wav_guids
const AVCodecGuid ff_codec_wav_guids[]
Definition at line 551 of file riff.c.
Referenced by ff_put_wav_header(), parse_media_type(), parse_waveformatex(), and write_stream_codec_info().