FFmpeg: libavformat/riffdec.c File Reference
riffdec.c File Reference
#include "libavutil/dict.h"
#include "libavutil/error.h"
#include "libavutil/log.h"
#include "libavutil/mathematics.h"
#include "libavcodec/avcodec.h"
#include "libavcodec/bytestream.h"
#include "avformat.h"
#include "avio_internal.h"
#include "riff.h"
Functions
int ff_get_guid (AVIOContext *s, ff_asf_guid *g)
enum AVCodecID ff_codec_guid_get_id (const AVCodecGuid *guids, ff_asf_guid guid)
static void parse_waveformatex (AVIOContext *pb, AVCodecParameters *par)
int ff_get_wav_header (AVFormatContext *s, AVIOContext *pb, AVCodecParameters *par, int size, int big_endian)
enum AVCodecID ff_wav_codec_get_id (unsigned int tag, int bps)
int ff_get_bmp_header (AVIOContext *pb, AVStream *st, unsigned *esize)
Read BITMAPINFOHEADER structure and set AVStream codec width, height and bits_per_encoded_sample fields.
int ff_read_riff_info (AVFormatContext *s, int64_t size)
Function Documentation
ff_get_guid()
int ff_get_guid (AVIOContext * s, ff_asf_guid * g)
Definition at line 32 of file riffdec.c.
Referenced by asf_build_simple_index(), asf_read_ext_stream_properties(), asf_read_file_properties(), asf_read_header(), asf_read_stream_properties(), detect_unknown_subobject(), ff_guidcmp(), parse_chunks(), parse_legacy_attrib(), parse_media_type(), parse_waveformatex(), and process_metadata().
ff_codec_guid_get_id()
enum AVCodecID ff_codec_guid_get_id (const AVCodecGuid * guids, ff_asf_guid guid)
Definition at line 44 of file riffdec.c.
Referenced by ff_guidcmp(), parse_media_type(), and parse_waveformatex().
parse_waveformatex()
static void parse_waveformatex (AVIOContext * pb, AVCodecParameters * par) static
Definition at line 61 of file riffdec.c.
Referenced by ff_get_wav_header().
ff_get_wav_header()
int ff_get_wav_header (AVFormatContext * s, AVIOContext * pb, AVCodecParameters * par, int size, int big_endian)
Definition at line 88 of file riffdec.c.
Referenced by asf_read_stream_properties(), avi_read_header(), dxa_read_header(), matroska_parse_tracks(), mov_read_wfex(), parse_media_type(), read_header(), scan_file(), set_spdif(), and xwma_read_header().
ff_wav_codec_get_id()
enum AVCodecID ff_wav_codec_get_id (unsigned int tag, int bps)
Definition at line 191 of file riffdec.c.
Referenced by ff_get_wav_header(), get_codec_data(), parse_media_type(), parse_waveformatex(), and xmv_read_header().
ff_get_bmp_header()
int ff_get_bmp_header (AVIOContext * pb, AVStream * st, unsigned * esize)
Read BITMAPINFOHEADER structure and set AVStream codec width, height and bits_per_encoded_sample fields.
Does not read extradata.
Returns
codec tag
Definition at line 208 of file riffdec.c.
Referenced by avi_read_header(), parse_video_info(), and parse_videoinfoheader2().
ff_read_riff_info()
int ff_read_riff_info (AVFormatContext * s, int64_t size)
Definition at line 226 of file riffdec.c.
Referenced by avi_load_index(), avi_read_header(), and set_spdif().