FFmpeg: libavformat/riffenc.c File Reference
riffenc.c File Reference
#include "libavutil/dict.h"
#include "libavutil/log.h"
#include "libavutil/mathematics.h"
#include "libavcodec/avcodec.h"
#include "libavcodec/bytestream.h"
#include "avformat.h"
#include "avio_internal.h"
#include "riff.h"
Functions
int64_t ff_start_tag (AVIOContext *pb, const char *tag)
void ff_end_tag (AVIOContext *pb, int64_t start)
int ff_put_wav_header (AVFormatContext *s, AVIOContext *pb, AVCodecParameters *par, int flags)
Write WAVEFORMAT header structure.
void ff_put_bmp_header (AVIOContext *pb, AVCodecParameters *par, const AVCodecTag *tags, int for_asf, int ignore_extradata)
void ff_parse_specific_params (AVStream *st, int *au_rate, int *au_ssize, int *au_scale)
void ff_riff_write_info_tag (AVIOContext *pb, const char *tag, const char *str)
Write a single RIFF info tag.
static int riff_has_valid_tags (AVFormatContext *s)
void ff_riff_write_info (AVFormatContext *s)
Write all recognized RIFF tags from s->metadata.
void ff_put_guid (AVIOContext *s, const ff_asf_guid *g)
const ff_asf_guid * ff_get_codec_guid (enum AVCodecID id, const AVCodecGuid *av_guid)
Variables
static const char riff_tags [][5]
Function Documentation
ff_start_tag()
int64_t ff_start_tag (AVIOContext * pb, const char * tag)
Definition at line 31 of file riffenc.c.
Referenced by avi_start_new_riff(), avi_write_header(), avi_write_idx1(), avi_write_packet(), ff_riff_write_info(), mmf_rate(), and write_odml_master().
ff_end_tag()
void ff_end_tag (AVIOContext * pb, int64_t start)
Definition at line 38 of file riffenc.c.
Referenced by avi_write_header(), avi_write_idx1(), avi_write_packet(), avi_write_packet_internal(), avi_write_trailer(), ff_riff_write_info(), and write_odml_master().
ff_put_wav_header()
int ff_put_wav_header (AVFormatContext * s, AVIOContext * pb, AVCodecParameters * par, int flags)
Write WAVEFORMAT header structure.
Parameters
flags a combination of FF_PUT_WAV_HEADER_* constants
Returns
the size or -1 on error
Definition at line 54 of file riffenc.c.
Referenced by asf_write_header1(), avi_write_header(), mkv_write_codecprivate(), mov_write_ms_tag(), mov_write_wfex_tag(), and write_stream_codec_info().
ff_put_bmp_header()
void ff_put_bmp_header (AVIOContext * pb, AVCodecParameters * par, const AVCodecTag * tags, int for_asf, int ignore_extradata)
Definition at line 209 of file riffenc.c.
Referenced by asf_write_header1(), avi_write_header(), mkv_write_codecprivate(), and put_videoinfoheader2().
ff_parse_specific_params()
void ff_parse_specific_params (AVStream * st, int * au_rate, int * au_ssize, int * au_scale)
Definition at line 265 of file riffenc.c.
Referenced by avi_write_counters(), avi_write_header(), nut_write_header(), and update_odml_entry().
ff_riff_write_info_tag()
void ff_riff_write_info_tag (AVIOContext * pb, const char * tag, const char * str)
Write a single RIFF info tag.
Definition at line 295 of file riffenc.c.
Referenced by avi_write_header(), and ff_riff_write_info().
riff_has_valid_tags()
static int riff_has_valid_tags (AVFormatContext * s) static
Definition at line 316 of file riffenc.c.
Referenced by ff_riff_write_info().
ff_riff_write_info()
void ff_riff_write_info (AVFormatContext * s)
Write all recognized RIFF tags from s->metadata.
Definition at line 327 of file riffenc.c.
Referenced by avi_write_header().
ff_put_guid()
void ff_put_guid (AVIOContext * s, const ff_asf_guid * g)
Definition at line 349 of file riffenc.c.
Referenced by asf_write_header1(), asf_write_index(), asf_write_markers(), ff_guidcmp(), ff_put_wav_header(), put_header(), write_chunk_header(), write_header(), write_index(), write_metadata_header(), write_root_table(), and write_stream_codec_info().
ff_get_codec_guid()
const ff_asf_guid* ff_get_codec_guid (enum AVCodecID id, const AVCodecGuid * av_guid)
Definition at line 355 of file riffenc.c.
Referenced by ff_guidcmp(), ff_put_wav_header(), and write_stream_codec_info().
Variable Documentation
riff_tags
const char riff_tags[][5] static
Initial value:
= {
    "IARL", "IART", "IAS1", "IAS2", "IAS3", "IAS4", "IAS5", "IAS6", "IAS7",
    "IAS8", "IAS9", "ICMS", "ICMT", "ICOP", "ICRD", "ICRP", "IDIM", "IDPI",
    "IENG", "IGNR", "IKEY", "ILGT", "ILNG", "IMED", "INAM", "IPLT", "IPRD",
    "IPRT", "ITRK", "ISBJ", "ISFT", "ISHP", "ISMP", "ISRC", "ISRF", "ITCH",
    { 0 }
}
Definition at line 308 of file riffenc.c.
Referenced by ff_riff_write_info(), and riff_has_valid_tags().