FFmpeg: libavcodec/rl.c File Reference
rl.c File Reference
#include <stdint.h>
#include <string.h>
#include "libavutil/attributes.h"
#include "libavutil/avassert.h"
#include "libavutil/mem.h"
#include "rl.h"
Functions
void ff_rl_free (RLTable *rl)
Free the contents of a dynamically allocated table.
av_cold int ff_rl_init (RLTable *rl, uint8_t static_store[2][2 *MAX_RUN+MAX_LEVEL+3])
av_cold void ff_rl_init_vlc (RLTable *rl, unsigned static_size)
Function Documentation
ff_rl_free()
void ff_rl_free (RLTable * rl)
Free the contents of a dynamically allocated table.
Definition at line 28 of file rl.c.
Referenced by ff_rl_init().
ff_rl_init()
av_cold int ff_rl_init (RLTable * rl, uint8_t static_store[2][2 *MAX_RUN+MAX_LEVEL+3])
Parameters
static_store static uint8_t array[2][2*MAX_RUN + MAX_LEVEL + 3] which will hold the level and run tables, if this is NULL av_malloc() will be used
Definition at line 39 of file rl.c.
Referenced by encode_init(), ff_h261_common_init(), ff_h263_decode_init_vlc(), ff_h263_encode_init(), ff_mpeg12_init_vlcs(), ff_mpeg1_encode_init(), ff_mpeg4videodec_static_init(), ff_msmpeg4_decode_init(), and ff_msmpeg4_encode_init().
ff_rl_init_vlc()
av_cold void ff_rl_init_vlc (RLTable * rl, unsigned static_size)
Definition at line 105 of file rl.c.