FFmpeg: libavcodec/rl.h File Reference
rl.h File Reference
rl header.
#include <stdint.h>
#include "vlc.h"
Data Structures
struct RLTable
RLTable.
Macros
#define MAX_RUN 64
#define MAX_LEVEL 64
#define INIT_VLC_RL(rl, static_size)
Functions
int ff_rl_init (RLTable *rl, uint8_t static_store[2][2 *MAX_RUN+MAX_LEVEL+3])
void ff_rl_init_vlc (RLTable *rl, unsigned static_size)
void ff_rl_free (RLTable *rl)
Free the contents of a dynamically allocated table.
static int get_rl_index (const RLTable *rl, int last, int run, int level)
Detailed Description
rl header.
Definition in file rl.h.
Macro Definition Documentation
MAX_RUN
#define MAX_RUN 64
Definition at line 35 of file rl.h.
Referenced by ff_mpv_encode_init(), ff_msmpeg4_encode_block(), ff_msmpeg4_encode_init(), ff_rl_init(), find_best_tables(), init_uni_h261_rl_tab(), init_uni_h263_rl_tab(), init_uni_mpeg4_rl_tab(), and mpeg4_decode_block().
MAX_LEVEL
#define MAX_LEVEL 64
Definition at line 36 of file rl.h.
Referenced by ff_mpv_encode_init(), ff_msmpeg4_encode_block(), ff_msmpeg4_encode_init(), ff_rl_init(), ff_rl_init_vlc(), filter(), find_best_tables(), get_size_of_code(), init_2d_vlc_rl(), init_uni_h261_rl_tab(), init_uni_h263_rl_tab(), init_uni_mpeg4_rl_tab(), mpeg4_decode_block(), and process_command().
INIT_VLC_RL
#define INIT_VLC_RL (rl, static_size)
Value:
{\
    int q;\
    static RL_VLC_ELEM rl_vlc_table[32][static_size];\
\
    if(!rl.rl_vlc[0]){\
        for(q=0; q<32; q++)\
            rl.rl_vlc[q]= rl_vlc_table[q];\
\
        ff_rl_init_vlc(&rl, static_size);\
    }\
}
Definition at line 63 of file rl.h.
Referenced by ff_h263_decode_init_vlc(), ff_mpeg4videodec_static_init(), ff_msmpeg4_decode_init(), and h261_decode_init_vlc().
Function Documentation
ff_rl_init()
int ff_rl_init (RLTable * rl, uint8_t static_store[2][2 *MAX_RUN+MAX_LEVEL+3])
Parameters
static_store static uint8_t array[2][2*MAX_RUN + MAX_LEVEL + 3] which will hold the level and run tables, if this is NULL av_malloc() will be used
Definition at line 39 of file rl.c.
Referenced by encode_init(), ff_h261_common_init(), ff_h263_decode_init_vlc(), ff_h263_encode_init(), ff_mpeg12_init_vlcs(), ff_mpeg1_encode_init(), ff_mpeg4videodec_static_init(), ff_msmpeg4_decode_init(), and ff_msmpeg4_encode_init().
ff_rl_init_vlc()
void ff_rl_init_vlc (RLTable * rl, unsigned static_size)
Definition at line 105 of file rl.c.
ff_rl_free()
void ff_rl_free (RLTable * rl)
Free the contents of a dynamically allocated table.
Definition at line 28 of file rl.c.
Referenced by ff_rl_init().
get_rl_index()
static int get_rl_index (const RLTable * rl, int last, int run, int level) inline static
Definition at line 76 of file rl.h.
Referenced by ff_msmpeg4_encode_block(), get_size_of_code(), h261_encode_block(), h263_encode_block(), init_uni_h261_rl_tab(), init_uni_h263_rl_tab(), and init_uni_mpeg4_rl_tab().