FFmpeg: libavcodec/rle.h File Reference
rle.h File Reference
#include <stdint.h>
Functions
int ff_rle_count_pixels (const uint8_t *start, int len, int bpp, int same)
Count up to 127 consecutive pixels which are either all the same or all differ from the previous and next pixels.
int ff_rle_encode (uint8_t *outbuf, int out_size, const uint8_t *inbuf, int bpp, int w, int add_rep, int xor_rep, int add_raw, int xor_raw)
RLE compress the row, with maximum size of out_size.
Function Documentation
ff_rle_count_pixels()
int ff_rle_count_pixels (const uint8_t * start, int len, int bpp, int same)
Count up to 127 consecutive pixels which are either all the same or all differ from the previous and next pixels.
Parameters
start Pointer to the first pixel
len Maximum number of pixels
bpp Bytes per pixel
same 1 if searching for identical pixel values, 0 for differing
Returns
Number of matching consecutive pixels found
Definition at line 27 of file rle.c.
Referenced by ff_rle_encode(), and sgi_rle_encode().
ff_rle_encode()
int ff_rle_encode (uint8_t * outbuf, int out_size, const uint8_t * inbuf, int bpp, int w, int add_rep, int xor_rep, int add_raw, int xor_raw)
RLE compress the row, with maximum size of out_size.
Value before repeated bytes is (count ^ xor_rep) + add_rep. Value before raw bytes is (count ^ xor_raw) + add_raw.
Parameters
outbuf Output buffer
out_size Maximum output size
inbuf Input buffer
bpp Bytes per pixel
w Image width
Returns
Size of output in bytes, or -1 if larger than out_size
Definition at line 52 of file rle.c.
Referenced by encode_strip(), and targa_encode_rle().