FFmpeg: libavformat/rm.h File Reference
rm.h File Reference
#include "avformat.h"
#include "internal.h"
Functions
RMStream * ff_rm_alloc_rmstream (void)
void ff_rm_free_rmstream (RMStream *rms)
int ff_rm_read_mdpr_codecdata (AVFormatContext *s, AVIOContext *pb, AVStream *st, RMStream *rst, unsigned int codec_data_size, const uint8_t *mime)
Read the MDPR chunk, which contains stream-specific codec initialization parameters.
int ff_rm_parse_packet (AVFormatContext *s, AVIOContext *pb, AVStream *st, RMStream *rst, int len, AVPacket *pkt, int *seq, int flags, int64_t ts)
Parse one rm-stream packet from the input bytestream.
int ff_rm_retrieve_cache (AVFormatContext *s, AVIOContext *pb, AVStream *st, RMStream *rst, AVPacket *pkt)
Retrieve one cached packet from the rm-context.
Variables
const char *const ff_rm_metadata [4]
const AVCodecTag ff_rm_codec_tags []
AVInputFormat ff_rdt_demuxer
Function Documentation
ff_rm_alloc_rmstream()
RMStream* ff_rm_alloc_rmstream (void)
Definition at line 113 of file rmdec.c.
Referenced by ivr_read_header(), rdt_parse_sdp_line(), rm_read_header(), rm_read_header_old(), and rm_read_multi().
ff_rm_free_rmstream()
void ff_rm_free_rmstream (RMStream * rms)
Definition at line 122 of file rmdec.c.
Referenced by rdt_close_context(), and rm_read_close().
ff_rm_read_mdpr_codecdata()
int ff_rm_read_mdpr_codecdata (AVFormatContext * s, AVIOContext * pb, AVStream * st, RMStream * rst, unsigned int codec_data_size, const uint8_t * mime)
Read the MDPR chunk, which contains stream-specific codec initialization parameters.
Parameters
s context containing RMContext and AVIOContext for stream reading
pb context to read the data from
st the stream that the MDPR chunk belongs to and where to store the parameters read from the chunk into
rst real-specific stream information
codec_data_size size of the MDPR chunk
Returns
0 on success, errno codes on error
Definition at line 314 of file rmdec.c.
Referenced by ivr_read_header(), rdt_load_mdpr(), rm_read_header(), and rm_read_multi().
ff_rm_parse_packet()
int ff_rm_parse_packet (AVFormatContext * s, AVIOContext * pb, AVStream * st, RMStream * rst, int len, AVPacket * pkt, int * seq, int flags, int64_t ts)
Parse one rm-stream packet from the input bytestream.
Parameters
s context containing RMContext and AVIOContext for stream reading
pb context to read the data from
st stream to which the packet to be read belongs
rst Real-specific stream information
len packet length to read from the input
pkt packet location to store the parsed packet data
seq pointer to an integer containing the sequence number, may be updated
flags the packet flags
ts timestamp of the current packet
Returns
<0 on error, 0 if a packet was placed in the pkt pointer. A value >0 means that no data was placed in pkt, but that cached data is available by calling ff_rm_retrieve_cache().
Definition at line 888 of file rmdec.c.
Referenced by ivr_read_packet(), rdt_parse_packet(), and rm_read_packet().
ff_rm_retrieve_cache()
int ff_rm_retrieve_cache (AVFormatContext * s, AVIOContext * pb, AVStream * st, RMStream * rst, AVPacket * pkt)
Retrieve one cached packet from the rm-context.
The real container can store several packets (as interpreted by the codec) in a single container packet, which means the demuxer holds some back when the first container packet is parsed and returned. The result is that rm->audio_pkt_cnt is a positive number, the amount of cached packets. Using this function, each of those packets can be retrieved sequentially.
Parameters
s context containing RMContext and AVIOContext for stream reading
pb context to read the data from
st stream that this packet belongs to
rst Real-specific stream information
pkt location to store the packet data
Returns
the number of samples left for subsequent calls to this same function, or 0 if all samples have been retrieved.
Definition at line 987 of file rmdec.c.
Referenced by ivr_read_packet(), rdt_parse_packet(), and rm_read_packet().
Variable Documentation
ff_rm_metadata
const char* const ff_rm_metadata[4]
Definition at line 24 of file rm.c.
Referenced by rm_read_metadata(), and rv10_write_header().
ff_rm_codec_tags
const AVCodecTag ff_rm_codec_tags[]
Definition at line 31 of file rm.c.
Referenced by ff_rm_read_mdpr_codecdata(), and rm_read_audio_stream_info().
ff_rdt_demuxer
AVInputFormat ff_rdt_demuxer
Definition at line 1169 of file rmdec.c.
Referenced by rdt_init().