FFmpeg: libavformat/rmdec.c File Reference
rmdec.c File Reference
#include <inttypes.h>
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/channel_layout.h"
#include "libavutil/internal.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/dict.h"
#include "avformat.h"
#include "avio_internal.h"
#include "internal.h"
#include "rmsipr.h"
#include "rm.h"
Data Structures
struct RMStream
struct RMDemuxContext
Macros
#define DEINT_ID_GENR MKTAG('g', 'e', 'n', 'r')
interleaving for Cooker/ATRAC
#define DEINT_ID_INT0 MKTAG('I', 'n', 't', '0')
no interleaving needed
#define DEINT_ID_INT4 MKTAG('I', 'n', 't', '4')
interleaving for 28.8
#define DEINT_ID_SIPR MKTAG('s', 'i', 'p', 'r')
interleaving for Sipro
#define DEINT_ID_VBRF MKTAG('v', 'b', 'r', 'f')
VBR case for AAC.
#define DEINT_ID_VBRS MKTAG('v', 'b', 'r', 's')
VBR case for AAC.
#define RAW_PACKET_SIZE 1000
Functions
static int rm_read_close (AVFormatContext *s)
static void get_strl (AVIOContext *pb, char *buf, int buf_size, int len)
static void get_str8 (AVIOContext *pb, char *buf, int buf_size)
static int rm_read_extradata (AVFormatContext *s, AVIOContext *pb, AVCodecParameters *par, unsigned size)
static void rm_read_metadata (AVFormatContext *s, AVIOContext *pb, int wide)
RMStream * ff_rm_alloc_rmstream (void)
void ff_rm_free_rmstream (RMStream *rms)
static int rm_read_audio_stream_info (AVFormatContext *s, AVIOContext *pb, AVStream *st, RMStream *ast, int read_all)
int ff_rm_read_mdpr_codecdata (AVFormatContext *s, AVIOContext *pb, AVStream *st, RMStream *rst, unsigned int codec_data_size, const uint8_t *mime)
Read the MDPR chunk, which contains stream-specific codec initialization parameters.
static int rm_read_index (AVFormatContext *s)
this function assumes that the demuxer has already seeked to the start of the INDX chunk, and will bail out if not.
static int rm_read_header_old (AVFormatContext *s)
static int rm_read_multi (AVFormatContext *s, AVIOContext *pb, AVStream *st, char *mime)
static int rm_read_header (AVFormatContext *s)
static int get_num (AVIOContext *pb, int *len)
static int rm_sync (AVFormatContext *s, int64_t *timestamp, int *flags, int *stream_index, int64_t *pos)
static int rm_assemble_video_frame (AVFormatContext *s, AVIOContext *pb, RMDemuxContext *rm, RMStream *vst, AVPacket *pkt, int len, int *pseq, int64_t *timestamp)
static void rm_ac3_swap_bytes (AVStream *st, AVPacket *pkt)
static int readfull (AVFormatContext *s, AVIOContext *pb, uint8_t *dst, int n)
int ff_rm_parse_packet (AVFormatContext *s, AVIOContext *pb, AVStream *st, RMStream *ast, int len, AVPacket *pkt, int *seq, int flags, int64_t timestamp)
Parse one rm-stream packet from the input bytestream.
int ff_rm_retrieve_cache (AVFormatContext *s, AVIOContext *pb, AVStream *st, RMStream *ast, AVPacket *pkt)
Retrieve one cached packet from the rm-context.
static int rm_read_packet (AVFormatContext *s, AVPacket *pkt)
static int rm_probe (AVProbeData *p)
static int64_t rm_read_dts (AVFormatContext *s, int stream_index, int64_t *ppos, int64_t pos_limit)
static int rm_read_seek (AVFormatContext *s, int stream_index, int64_t pts, int flags)
static int ivr_probe (AVProbeData *p)
static int ivr_read_header (AVFormatContext *s)
static int ivr_read_packet (AVFormatContext *s, AVPacket *pkt)
Variables
AVInputFormat ff_rm_demuxer
AVInputFormat ff_rdt_demuxer
AVInputFormat ff_ivr_demuxer
Macro Definition Documentation
DEINT_ID_GENR
#define DEINT_ID_GENR MKTAG('g', 'e', 'n', 'r')
interleaving for Cooker/ATRAC
Definition at line 36 of file rmdec.c.
Referenced by ff_rm_parse_packet(), and rm_read_audio_stream_info().
DEINT_ID_INT0
#define DEINT_ID_INT0 MKTAG('I', 'n', 't', '0')
no interleaving needed
Definition at line 37 of file rmdec.c.
Referenced by rm_read_audio_stream_info().
DEINT_ID_INT4
#define DEINT_ID_INT4 MKTAG('I', 'n', 't', '4')
interleaving for 28.8
Definition at line 38 of file rmdec.c.
Referenced by ff_rm_parse_packet(), and rm_read_audio_stream_info().
DEINT_ID_SIPR
#define DEINT_ID_SIPR MKTAG('s', 'i', 'p', 'r')
interleaving for Sipro
Definition at line 39 of file rmdec.c.
Referenced by ff_rm_parse_packet(), and rm_read_audio_stream_info().
DEINT_ID_VBRF
#define DEINT_ID_VBRF MKTAG('v', 'b', 'r', 'f')
VBR case for AAC.
Definition at line 40 of file rmdec.c.
Referenced by ff_rm_parse_packet(), ff_rm_retrieve_cache(), and rm_read_audio_stream_info().
DEINT_ID_VBRS
#define DEINT_ID_VBRS MKTAG('v', 'b', 'r', 's')
VBR case for AAC.
Definition at line 41 of file rmdec.c.
Referenced by ff_rm_parse_packet(), ff_rm_retrieve_cache(), and rm_read_audio_stream_info().
RAW_PACKET_SIZE
#define RAW_PACKET_SIZE 1000
Definition at line 683 of file rmdec.c.
Referenced by rm_read_packet().
Function Documentation
rm_read_close()
static int rm_read_close (AVFormatContext * s) static
Definition at line 1076 of file rmdec.c.
Referenced by rm_read_header().
get_strl()
static void get_strl (AVIOContext * pb, char * buf, int buf_size, int len) inline static
Definition at line 71 of file rmdec.c.
Referenced by ff_rm_read_mdpr_codecdata(), get_str8(), and rm_read_metadata().
get_str8()
static void get_str8 (AVIOContext * pb, char * buf, int buf_size) static
Definition at line 85 of file rmdec.c.
Referenced by ff_rm_read_mdpr_codecdata(), rm_read_audio_stream_info(), and rm_read_header().
rm_read_extradata()
static int rm_read_extradata (AVFormatContext * s, AVIOContext * pb, AVCodecParameters * par, unsigned size) static
Definition at line 90 of file rmdec.c.
Referenced by ff_rm_read_mdpr_codecdata(), and rm_read_audio_stream_info().
rm_read_metadata()
static void rm_read_metadata (AVFormatContext * s, AVIOContext * pb, int wide) static
Definition at line 101 of file rmdec.c.
Referenced by rm_read_audio_stream_info(), and rm_read_header().
ff_rm_alloc_rmstream()
RMStream* ff_rm_alloc_rmstream (void)
Definition at line 113 of file rmdec.c.
Referenced by ivr_read_header(), rdt_parse_sdp_line(), rm_read_header(), rm_read_header_old(), and rm_read_multi().
ff_rm_free_rmstream()
void ff_rm_free_rmstream (RMStream * rms)
Definition at line 122 of file rmdec.c.
Referenced by rdt_close_context(), and rm_read_close().
rm_read_audio_stream_info()
static int rm_read_audio_stream_info (AVFormatContext * s, AVIOContext * pb, AVStream * st, RMStream * ast, int read_all) static
Definition at line 127 of file rmdec.c.
Referenced by ff_rm_read_mdpr_codecdata(), and rm_read_header_old().
ff_rm_read_mdpr_codecdata()
int ff_rm_read_mdpr_codecdata (AVFormatContext * s, AVIOContext * pb, AVStream * st, RMStream * rst, unsigned int codec_data_size, const uint8_t * mime)
Read the MDPR chunk, which contains stream-specific codec initialization parameters.
Parameters
s context containing RMContext and AVIOContext for stream reading
pb context to read the data from
st the stream that the MDPR chunk belongs to and where to store the parameters read from the chunk into
rst real-specific stream information
codec_data_size size of the MDPR chunk
Returns
0 on success, errno codes on error
Definition at line 314 of file rmdec.c.
Referenced by ivr_read_header(), rdt_load_mdpr(), rm_read_header(), and rm_read_multi().
rm_read_index()
static int rm_read_index (AVFormatContext * s) static
this function assumes that the demuxer has already seeked to the start of the INDX chunk, and will bail out if not.
Definition at line 422 of file rmdec.c.
Referenced by rm_read_header().
rm_read_header_old()
static int rm_read_header_old (AVFormatContext * s) static
Definition at line 478 of file rmdec.c.
Referenced by rm_read_header().
rm_read_multi()
static int rm_read_multi (AVFormatContext * s, AVIOContext * pb, AVStream * st, char * mime) static
Definition at line 493 of file rmdec.c.
Referenced by ivr_read_header(), and rm_read_header().
rm_read_header()
static int rm_read_header (AVFormatContext * s) static
Definition at line 534 of file rmdec.c.
get_num()
static int get_num (AVIOContext * pb, int * len) static
Definition at line 666 of file rmdec.c.
Referenced by rm_assemble_video_frame().
rm_sync()
static int rm_sync (AVFormatContext * s, int64_t * timestamp, int * flags, int * stream_index, int64_t * pos) static
Definition at line 685 of file rmdec.c.
Referenced by rm_read_dts(), and rm_read_packet().
rm_assemble_video_frame()
static int rm_assemble_video_frame (AVFormatContext * s, AVIOContext * pb, RMDemuxContext * rm, RMStream * vst, AVPacket * pkt, int len, int * pseq, int64_t * timestamp) static
Definition at line 756 of file rmdec.c.
Referenced by ff_rm_parse_packet().
rm_ac3_swap_bytes()
static void rm_ac3_swap_bytes (AVStream * st, AVPacket * pkt) inline static
Definition at line 863 of file rmdec.c.
Referenced by ff_rm_parse_packet().
readfull()
static int readfull (AVFormatContext * s, AVIOContext * pb, uint8_t * dst, int n) static
Definition at line 877 of file rmdec.c.
Referenced by ff_rm_parse_packet().
ff_rm_parse_packet()
int ff_rm_parse_packet (AVFormatContext * s, AVIOContext * pb, AVStream * st, RMStream * rst, int len, AVPacket * pkt, int * seq, int flags, int64_t ts)
Parse one rm-stream packet from the input bytestream.
Parameters
s context containing RMContext and AVIOContext for stream reading
pb context to read the data from
st stream to which the packet to be read belongs
rst Real-specific stream information
len packet length to read from the input
pkt packet location to store the parsed packet data
seq pointer to an integer containing the sequence number, may be updated
flags the packet flags
ts timestamp of the current packet
Returns
<0 on error, 0 if a packet was placed in the pkt pointer. A value >0 means that no data was placed in pkt, but that cached data is available by calling ff_rm_retrieve_cache().
Definition at line 888 of file rmdec.c.
Referenced by ivr_read_packet(), rdt_parse_packet(), and rm_read_packet().
ff_rm_retrieve_cache()
int ff_rm_retrieve_cache (AVFormatContext * s, AVIOContext * pb, AVStream * st, RMStream * rst, AVPacket * pkt)
Retrieve one cached packet from the rm-context.
The real container can store several packets (as interpreted by the codec) in a single container packet, which means the demuxer holds some back when the first container packet is parsed and returned. The result is that rm->audio_pkt_cnt is a positive number, the amount of cached packets. Using this function, each of those packets can be retrieved sequentially.
Parameters
s context containing RMContext and AVIOContext for stream reading
pb context to read the data from
st stream that this packet belongs to
rst Real-specific stream information
pkt location to store the packet data
Returns
the number of samples left for subsequent calls to this same function, or 0 if all samples have been retrieved.
Definition at line 987 of file rmdec.c.
Referenced by ivr_read_packet(), rdt_parse_packet(), and rm_read_packet().
rm_read_packet()
static int rm_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 1018 of file rmdec.c.
rm_probe()
static int rm_probe (AVProbeData * p) static
Definition at line 1086 of file rmdec.c.
rm_read_dts()
static int64_t rm_read_dts (AVFormatContext * s, int stream_index, int64_t * ppos, int64_t pos_limit) static
Definition at line 1099 of file rmdec.c.
rm_read_seek()
static int rm_read_seek (AVFormatContext * s, int stream_index, int64_t pts, int flags) static
Definition at line 1145 of file rmdec.c.
ivr_probe()
static int ivr_probe (AVProbeData * p) static
Definition at line 1177 of file rmdec.c.
ivr_read_header()
static int ivr_read_header (AVFormatContext * s) static
Definition at line 1186 of file rmdec.c.
ivr_read_packet()
static int ivr_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 1321 of file rmdec.c.
Variable Documentation
ff_rm_demuxer
AVInputFormat ff_rm_demuxer
Initial value:
= {
    .name           = "rm",
    .long_name      = NULL_IF_CONFIG_SMALL("RealMedia"),
    .priv_data_size = sizeof(RMDemuxContext),
    .read_probe     = rm_probe,
    .read_header    = rm_read_header,
    .read_packet    = rm_read_packet,
    .read_close     = rm_read_close,
    .read_timestamp = rm_read_dts,
    .read_seek      = rm_read_seek,
}
Definition at line 1157 of file rmdec.c.
ff_rdt_demuxer
AVInputFormat ff_rdt_demuxer
Initial value:
= {
    .name           = "rdt",
    .long_name      = NULL_IF_CONFIG_SMALL("RDT demuxer"),
    .priv_data_size = sizeof(RMDemuxContext),
    .read_close     = rm_read_close,
    .flags          = AVFMT_NOFILE,
}
Definition at line 1169 of file rmdec.c.
Referenced by rdt_init().
ff_ivr_demuxer
AVInputFormat ff_ivr_demuxer
Initial value:
= {
    .name           = "ivr",
    .long_name      = NULL_IF_CONFIG_SMALL("IVR (Internet Video Recording)"),
    .priv_data_size = sizeof(RMDemuxContext),
    .read_probe     = ivr_probe,
    .read_header    = ivr_read_header,
    .read_packet    = ivr_read_packet,
    .read_close     = rm_read_close,
    .extensions     = "ivr",
}
Definition at line 1402 of file rmdec.c.