FFmpeg: libavformat/rmenc.c File Reference
rmenc.c File Reference
#include "avformat.h"
#include "avio_internal.h"
#include "rm.h"
#include "libavutil/dict.h"
Data Structures
struct StreamInfo
struct RMMuxContext
Macros
#define BUFFER_DURATION 0
#define MAX_HEADER_SIZE (7 + 4 + 12)
#define MAX_PACKET_SIZE (UINT16_MAX - MAX_HEADER_SIZE)
Functions
static void put_str (AVIOContext *s, const char *tag)
static void put_str8 (AVIOContext *s, const char *tag)
static int rv10_write_header (AVFormatContext *ctx, int data_size, int index_pos)
static void write_packet_header (AVFormatContext *ctx, StreamInfo *stream, int length, int key_frame)
static int rm_write_header (AVFormatContext *s)
static int rm_write_audio (AVFormatContext *s, const uint8_t *buf, int size, int flags)
static int rm_write_video (AVFormatContext *s, const uint8_t *buf, int size, int flags)
static int rm_write_packet (AVFormatContext *s, AVPacket *pkt)
static int rm_write_trailer (AVFormatContext *s)
Variables
AVOutputFormat ff_rm_muxer
Macro Definition Documentation
BUFFER_DURATION
#define BUFFER_DURATION 0
Definition at line 46 of file rmenc.c.
Referenced by rv10_write_header().
MAX_HEADER_SIZE
#define MAX_HEADER_SIZE (7 + 4 + 12)
Definition at line 48 of file rmenc.c.
MAX_PACKET_SIZE
#define MAX_PACKET_SIZE (UINT16_MAX - MAX_HEADER_SIZE)
Definition at line 50 of file rmenc.c.
Referenced by rm_write_video().
Function Documentation
put_str()
static void put_str (AVIOContext * s, const char * tag) static
Definition at line 53 of file rmenc.c.
Referenced by rv10_write_header().
put_str8()
static void put_str8 (AVIOContext * s, const char * tag) static
Definition at line 61 of file rmenc.c.
Referenced by rv10_write_header().
rv10_write_header()
static int rv10_write_header (AVFormatContext * ctx, int data_size, int index_pos) static
Definition at line 69 of file rmenc.c.
Referenced by rm_write_header(), and rm_write_trailer().
write_packet_header()
static void write_packet_header (AVFormatContext * ctx, StreamInfo * stream, int length, int key_frame) static
Definition at line 296 of file rmenc.c.
Referenced by rm_write_audio(), and rm_write_video().
rm_write_header()
static int rm_write_header (AVFormatContext * s) static
Definition at line 316 of file rmenc.c.
rm_write_audio()
static int rm_write_audio (AVFormatContext * s, const uint8_t * buf, int size, int flags) static
Definition at line 370 of file rmenc.c.
Referenced by rm_write_packet().
rm_write_video()
static int rm_write_video (AVFormatContext * s, const uint8_t * buf, int size, int flags) static
Definition at line 392 of file rmenc.c.
Referenced by rm_write_packet().
rm_write_packet()
static int rm_write_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 440 of file rmenc.c.
rm_write_trailer()
static int rm_write_trailer (AVFormatContext * s) static
Definition at line 449 of file rmenc.c.
Variable Documentation
ff_rm_muxer
AVOutputFormat ff_rm_muxer
Initial value:
= {
    .name              = "rm",
    .long_name         = NULL_IF_CONFIG_SMALL("RealMedia"),
    .mime_type         = "application/vnd.rn-realmedia",
    .extensions        = "rm,ra",
    .priv_data_size    = sizeof(RMMuxContext),
    .audio_codec       = AV_CODEC_ID_AC3,
    .video_codec       = AV_CODEC_ID_RV10,
    .write_header      = rm_write_header,
    .write_packet      = rm_write_packet,
    .write_trailer     = rm_write_trailer,
    .codec_tag         = (const AVCodecTag* const []){ ff_rm_codec_tags, 0 },
}
Definition at line 480 of file rmenc.c.