FFmpeg: libavcodec/rnd_avg.h File Reference
rnd_avg.h File Reference
#include <stddef.h>
#include <stdint.h>
Macros
#define BYTE_VEC32(c) ((c) * 0x01010101UL)
#define BYTE_VEC64(c) ((c) * 0x0001000100010001UL)
Functions
static uint32_t rnd_avg32 (uint32_t a, uint32_t b)
static uint32_t no_rnd_avg32 (uint32_t a, uint32_t b)
static uint64_t rnd_avg64 (uint64_t a, uint64_t b)
static uint64_t no_rnd_avg64 (uint64_t a, uint64_t b)
Macro Definition Documentation
BYTE_VEC32
#define BYTE_VEC32 (c) ((c) * 0x01010101UL)
Definition at line 28 of file rnd_avg.h.
Referenced by no_rnd_avg32(), and rnd_avg32().
BYTE_VEC64
#define BYTE_VEC64 (c) ((c) * 0x0001000100010001UL)
Definition at line 29 of file rnd_avg.h.
Referenced by no_rnd_avg64(), and rnd_avg64().
Function Documentation
rnd_avg32()
static uint32_t rnd_avg32 (uint32_t a, uint32_t b) inline static
Definition at line 31 of file rnd_avg.h.
Referenced by ff_avg_pixels4_xy2_8_mmi(), and ff_avg_pixels8_xy2_8_mmi().
no_rnd_avg32()
static uint32_t no_rnd_avg32 (uint32_t a, uint32_t b) inline static
Definition at line 36 of file rnd_avg.h.
Referenced by put_no_rnd_pixels_l2().
rnd_avg64()
static uint64_t rnd_avg64 (uint64_t a, uint64_t b) inline static
Definition at line 41 of file rnd_avg.h.
no_rnd_avg64()
static uint64_t no_rnd_avg64 (uint64_t a, uint64_t b) inline static
Definition at line 46 of file rnd_avg.h.