FFmpeg: libavcodec/roqvideo.c File Reference
roqvideo.c File Reference
id RoQ Video common functions based on work by Dr.
#include "avcodec.h"
#include "roqvideo.h"
Functions
static void block_copy (unsigned char *out, unsigned char *in, int outstride, int instride, int sz)
void ff_apply_vector_2x2 (RoqContext *ri, int x, int y, roq_cell *cell)
void ff_apply_vector_4x4 (RoqContext *ri, int x, int y, roq_cell *cell)
static void apply_motion_generic (RoqContext *ri, int x, int y, int deltax, int deltay, int sz)
void ff_apply_motion_4x4 (RoqContext *ri, int x, int y, int deltax, int deltay)
void ff_apply_motion_8x8 (RoqContext *ri, int x, int y, int deltax, int deltay)
Detailed Description
id RoQ Video common functions based on work by Dr.
Tim Ferguson
Definition in file roqvideo.c.
Function Documentation
block_copy()
static void block_copy (unsigned char * out, unsigned char * in, int outstride, int instride, int sz) inline static
Definition at line 30 of file roqvideo.c.
Referenced by apply_motion_generic().
ff_apply_vector_2x2()
void ff_apply_vector_2x2 (RoqContext * ri, int x, int y, roq_cell * cell)
Definition at line 41 of file roqvideo.c.
Referenced by reconstruct_and_encode_image(), and roqvideo_decode_frame().
ff_apply_vector_4x4()
void ff_apply_vector_4x4 (RoqContext * ri, int x, int y, roq_cell * cell)
Definition at line 71 of file roqvideo.c.
Referenced by reconstruct_and_encode_image(), and roqvideo_decode_frame().
apply_motion_generic()
static void apply_motion_generic (RoqContext * ri, int x, int y, int deltax, int deltay, int sz) inline static
Definition at line 102 of file roqvideo.c.
Referenced by ff_apply_motion_4x4(), and ff_apply_motion_8x8().
ff_apply_motion_4x4()
void ff_apply_motion_4x4 (RoqContext * ri, int x, int y, int deltax, int deltay)
Definition at line 133 of file roqvideo.c.
Referenced by reconstruct_and_encode_image(), and roqvideo_decode_frame().
ff_apply_motion_8x8()
void ff_apply_motion_8x8 (RoqContext * ri, int x, int y, int deltax, int deltay)
Definition at line 139 of file roqvideo.c.
Referenced by reconstruct_and_encode_image(), and roqvideo_decode_frame().