FFmpeg: libavformat/rpl.c File Reference
rpl.c File Reference
#include <inttypes.h>
#include <stdlib.h>
#include "libavutil/avstring.h"
#include "libavutil/dict.h"
#include "avformat.h"
#include "internal.h"
Data Structures
struct RPLContext
Macros
#define RPL_SIGNATURE "ARMovie\x0A"
#define RPL_SIGNATURE_SIZE 8
#define RPL_LINE_LENGTH 256
256 is arbitrary, but should be big enough for any reasonable file.
Functions
static int rpl_probe (AVProbeData *p)
static int read_line (AVIOContext *pb, char *line, int bufsize)
static int32_t read_int (const char *line, const char **endptr, int *error)
static int32_t read_line_and_int (AVIOContext *pb, int *error)
static AVRational read_fps (const char *line, int *error)
Parsing for fps, which can be a fraction.
static int rpl_read_header (AVFormatContext *s)
static int rpl_read_packet (AVFormatContext *s, AVPacket *pkt)
Variables
AVInputFormat ff_rpl_demuxer
Macro Definition Documentation
RPL_SIGNATURE
#define RPL_SIGNATURE "ARMovie\x0A"
Definition at line 30 of file rpl.c.
Referenced by rpl_probe().
RPL_SIGNATURE_SIZE
#define RPL_SIGNATURE_SIZE 8
Definition at line 31 of file rpl.c.
Referenced by rpl_probe().
RPL_LINE_LENGTH
#define RPL_LINE_LENGTH 256
256 is arbitrary, but should be big enough for any reasonable file.
Definition at line 34 of file rpl.c.
Referenced by read_line_and_int(), and rpl_read_header().
Function Documentation
rpl_probe()
static int rpl_probe (AVProbeData * p) static
Definition at line 36 of file rpl.c.
read_line()
static int read_line (AVIOContext * pb, char * line, int bufsize) static
Definition at line 54 of file rpl.c.
Referenced by read_line_and_int(), and rpl_read_header().
read_int()
static int32_t read_int (const char * line, const char ** endptr, int * error) static
Definition at line 71 of file rpl.c.
Referenced by read_fps(), and read_line_and_int().
read_line_and_int()
static int32_t read_line_and_int (AVIOContext * pb, int * error) static
Definition at line 83 of file rpl.c.
Referenced by rpl_read_header().
read_fps()
static AVRational read_fps (const char * line, int * error) static
Parsing for fps, which can be a fraction.
Unfortunately, the spec for the header leaves out a lot of details, so this is mostly guessing.
Definition at line 95 of file rpl.c.
Referenced by rpl_read_header().
rpl_read_header()
static int rpl_read_header (AVFormatContext * s) static
Definition at line 115 of file rpl.c.
rpl_read_packet()
static int rpl_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 275 of file rpl.c.
Variable Documentation
ff_rpl_demuxer
AVInputFormat ff_rpl_demuxer
Initial value:
= {
    .name           = "rpl",
    .long_name      = NULL_IF_CONFIG_SMALL("RPL / ARMovie"),
    .priv_data_size = sizeof(RPLContext),
    .read_probe     = rpl_probe,
    .read_header    = rpl_read_header,
    .read_packet    = rpl_read_packet,
}
Definition at line 357 of file rpl.c.