FFmpeg: libavcodec/rtjpeg.h File Reference
rtjpeg.h File Reference
#include <stdint.h>
#include "libavutil/mem.h"
#include "idctdsp.h"
Data Structures
struct RTJpegContext
Macros
#define RTJPEG_FILE_VERSION 0
#define RTJPEG_HEADER_SIZE 12
Functions
void ff_rtjpeg_init (RTJpegContext *c, AVCodecContext *avctx)
void ff_rtjpeg_decode_init (RTJpegContext *c, int width, int height, const uint32_t *lquant, const uint32_t *cquant)
initialize an RTJpegContext, may be called multiple times
int ff_rtjpeg_decode_frame_yuv420 (RTJpegContext *c, AVFrame *f, const uint8_t *buf, int buf_size)
decode one rtjpeg YUV420 frame
Macro Definition Documentation
RTJPEG_FILE_VERSION
#define RTJPEG_FILE_VERSION 0
Definition at line 30 of file rtjpeg.h.
RTJPEG_HEADER_SIZE
#define RTJPEG_HEADER_SIZE 12
Definition at line 31 of file rtjpeg.h.
Referenced by codec_reinit(), and decode_frame().
Function Documentation
ff_rtjpeg_init()
void ff_rtjpeg_init (RTJpegContext * c, AVCodecContext * avctx)
Definition at line 170 of file rtjpeg.c.
Referenced by decode_init().
ff_rtjpeg_decode_init()
void ff_rtjpeg_decode_init (RTJpegContext * c, int width, int height, const uint32_t * lquant, const uint32_t * cquant)
initialize an RTJpegContext, may be called multiple times
Parameters
c context to initialize
width width of image, will be rounded down to the nearest multiple of 16 for decoding
height height of image, will be rounded down to the nearest multiple of 16 for decoding
lquant luma quantization table to use
cquant chroma quantization table to use
Definition at line 158 of file rtjpeg.c.
Referenced by codec_reinit(), and decode_frame().
ff_rtjpeg_decode_frame_yuv420()
int ff_rtjpeg_decode_frame_yuv420 (RTJpegContext * c, AVFrame * f, const uint8_t * buf, int buf_size)
decode one rtjpeg YUV420 frame
Parameters
c context, must be initialized via ff_rtjpeg_decode_init
f AVFrame to place decoded frame into. If parts of the frame are not coded they are left unchanged, so consider initializing it
buf buffer containing input data
buf_size length of input data in bytes
Returns
number of bytes consumed from the input buffer
Definition at line 106 of file rtjpeg.c.
Referenced by decode_frame().