FFmpeg: libavformat/rtmpproto.c File Reference
rtmpproto.c File Reference
RTMP protocol.
#include "libavcodec/bytestream.h"
#include "libavutil/avstring.h"
#include "libavutil/base64.h"
#include "libavutil/hmac.h"
#include "libavutil/intfloat.h"
#include "libavutil/lfg.h"
#include "libavutil/md5.h"
#include "libavutil/opt.h"
#include "libavutil/random_seed.h"
#include "avformat.h"
#include "internal.h"
#include "network.h"
#include "flv.h"
#include "rtmp.h"
#include "rtmpcrypt.h"
#include "rtmppkt.h"
#include "url.h"
Data Structures
struct TrackedMethod
struct RTMPContext
protocol handler context
Macros
#define APP_MAX_LENGTH 1024
#define PLAYPATH_MAX_LENGTH 512
#define TCURL_MAX_LENGTH 1024
#define FLASHVER_MAX_LENGTH 64
#define RTMP_PKTDATA_DEFAULT_SIZE 4096
#define RTMP_HEADER 11
#define PLAYER_KEY_OPEN_PART_LEN 30
length of partial key used for first client digest signing
#define SERVER_KEY_OPEN_PART_LEN 36
length of partial key used for first server digest signing
#define RTMP_CTRL_ABORT_MESSAGE (2)
#define OFFSET(x) offsetof(RTMPContext, x)
#define DEC AV_OPT_FLAG_DECODING_PARAM
#define ENC AV_OPT_FLAG_ENCODING_PARAM
#define RTMP_PROTOCOL(flavor)
Enumerations
enum ClientState {
STATE_START, STATE_HANDSHAKED, STATE_FCPUBLISH, STATE_PLAYING,
STATE_SEEKING, STATE_PUBLISHING, STATE_RECEIVING, STATE_SENDING,
STATE_STOPPED
}
RTMP protocol handler state.
Functions
static int handle_chunk_size (URLContext *s, RTMPPacket *pkt)
static int handle_server_bw (URLContext *s, RTMPPacket *pkt)
static int handle_client_bw (URLContext *s, RTMPPacket *pkt)
static int add_tracked_method (RTMPContext *rt, const char *name, int id)
static void del_tracked_method (RTMPContext *rt, int index)
static int find_tracked_method (URLContext *s, RTMPPacket *pkt, int offset, char **tracked_method)
static void free_tracked_methods (RTMPContext *rt)
static int rtmp_send_packet (RTMPContext *rt, RTMPPacket *pkt, int track)
static int rtmp_write_amf_data (URLContext *s, char *param, uint8_t **p)
static int gen_connect (URLContext *s, RTMPContext *rt)
Generate 'connect' call and send it to the server.
static int read_connect (URLContext *s, RTMPContext *rt)
static int gen_release_stream (URLContext *s, RTMPContext *rt)
Generate 'releaseStream' call and send it to the server.
static int gen_fcpublish_stream (URLContext *s, RTMPContext *rt)
Generate 'FCPublish' call and send it to the server.
static int gen_fcunpublish_stream (URLContext *s, RTMPContext *rt)
Generate 'FCUnpublish' call and send it to the server.
static int gen_create_stream (URLContext *s, RTMPContext *rt)
Generate 'createStream' call and send it to the server.
static int gen_delete_stream (URLContext *s, RTMPContext *rt)
Generate 'deleteStream' call and send it to the server.
static int gen_get_stream_length (URLContext *s, RTMPContext *rt)
Generate 'getStreamLength' call and send it to the server.
static int gen_buffer_time (URLContext *s, RTMPContext *rt)
Generate client buffer time and send it to the server.
static int gen_play (URLContext *s, RTMPContext *rt)
Generate 'play' call and send it to the server, then ping the server to start actual playing.
static int gen_seek (URLContext *s, RTMPContext *rt, int64_t timestamp)
static int gen_pause (URLContext *s, RTMPContext *rt, int pause, uint32_t timestamp)
Generate a pause packet that either pauses or unpauses the current stream.
static int gen_publish (URLContext *s, RTMPContext *rt)
Generate 'publish' call and send it to the server.
static int gen_pong (URLContext *s, RTMPContext *rt, RTMPPacket *ppkt)
Generate ping reply and send it to the server.
static int gen_swf_verification (URLContext *s, RTMPContext *rt)
Generate SWF verification message and send it to the server.
static int gen_server_bw (URLContext *s, RTMPContext *rt)
Generate server bandwidth message and send it to the server.
static int gen_check_bw (URLContext *s, RTMPContext *rt)
Generate check bandwidth message and send it to the server.
static int gen_bytes_read (URLContext *s, RTMPContext *rt, uint32_t ts)
Generate report on bytes read so far and send it to the server.
static int gen_fcsubscribe_stream (URLContext *s, RTMPContext *rt, const char *subscribe)
int ff_rtmp_calc_digest (const uint8_t *src, int len, int gap, const uint8_t *key, int keylen, uint8_t *dst)
Calculate HMAC-SHA2 digest for RTMP handshake packets.
int ff_rtmp_calc_digest_pos (const uint8_t *buf, int off, int mod_val, int add_val)
Calculate digest position for RTMP handshake packets.
static int rtmp_handshake_imprint_with_digest (uint8_t *buf, int encrypted)
Put HMAC-SHA2 digest of packet data (except for the bytes where this digest will be stored) into that packet.
static int rtmp_validate_digest (uint8_t *buf, int off)
Verify that the received server response has the expected digest value.
static int rtmp_calc_swf_verification (URLContext *s, RTMPContext *rt, uint8_t *buf)
static int rtmp_calc_swfhash (URLContext *s)
static int rtmp_handshake (URLContext *s, RTMPContext *rt)
Perform handshake with the server by means of exchanging pseudorandom data signed with HMAC-SHA2 digest.
static int rtmp_receive_hs_packet (RTMPContext *rt, uint32_t *first_int, uint32_t *second_int, char *arraydata, int size)
static int rtmp_send_hs_packet (RTMPContext *rt, uint32_t first_int, uint32_t second_int, char *arraydata, int size)
static int rtmp_server_handshake (URLContext *s, RTMPContext *rt)
rtmp handshake server side
static int handle_ping (URLContext *s, RTMPPacket *pkt)
static int do_adobe_auth (RTMPContext *rt, const char *user, const char *salt, const char *opaque, const char *challenge)
static int do_llnw_auth (RTMPContext *rt, const char *user, const char *nonce)
static int handle_connect_error (URLContext *s, const char *desc)
static int handle_invoke_error (URLContext *s, RTMPPacket *pkt)
static int write_begin (URLContext *s)
static int write_status (URLContext *s, RTMPPacket *pkt, const char *status, const char *filename)
static int send_invoke_response (URLContext *s, RTMPPacket *pkt)
static int read_number_result (RTMPPacket *pkt, double *number)
Read the AMF_NUMBER response ("_result") to a function call (e.g.
static int handle_invoke_result (URLContext *s, RTMPPacket *pkt)
static int handle_invoke_status (URLContext *s, RTMPPacket *pkt)
static int handle_invoke (URLContext *s, RTMPPacket *pkt)
static int update_offset (RTMPContext *rt, int size)
static int append_flv_data (RTMPContext *rt, RTMPPacket *pkt, int skip)
static int handle_notify (URLContext *s, RTMPPacket *pkt)
static int rtmp_parse_result (URLContext *s, RTMPContext *rt, RTMPPacket *pkt)
Parse received packet and possibly perform some action depending on the packet contents.
static int handle_metadata (RTMPContext *rt, RTMPPacket *pkt)
static int get_packet (URLContext *s, int for_header)
Interact with the server by receiving and sending RTMP packets until there is some significant data (media data or expected status notification).
static int rtmp_close (URLContext *h)
static int inject_fake_duration_metadata (RTMPContext *rt)
Insert a fake onMetadata packet into the FLV stream to notify the FLV demuxer about the duration of the stream.
static int rtmp_open (URLContext *s, const char *uri, int flags)
Open RTMP connection and verify that the stream can be played.
static int rtmp_read (URLContext *s, uint8_t *buf, int size)
static int64_t rtmp_seek (URLContext *s, int stream_index, int64_t timestamp, int flags)
static int rtmp_pause (URLContext *s, int pause)
static int rtmp_write (URLContext *s, const uint8_t *buf, int size)
Variables
static const uint8_t rtmp_player_key []
Client key used for digest signing.
static const uint8_t rtmp_server_key []
Key used for RTMP server digest signing.
static const AVOption rtmp_options []
Detailed Description
RTMP protocol.
Definition in file rtmpproto.c.
Macro Definition Documentation
APP_MAX_LENGTH
#define APP_MAX_LENGTH 1024
Definition at line 51 of file rtmpproto.c.
Referenced by gen_connect(), and rtmp_open().
PLAYPATH_MAX_LENGTH
#define PLAYPATH_MAX_LENGTH 512
Definition at line 52 of file rtmpproto.c.
Referenced by rtmp_open().
TCURL_MAX_LENGTH
#define TCURL_MAX_LENGTH 1024
Definition at line 53 of file rtmpproto.c.
Referenced by rtmp_open().
FLASHVER_MAX_LENGTH
#define FLASHVER_MAX_LENGTH 64
Definition at line 54 of file rtmpproto.c.
Referenced by rtmp_open().
RTMP_PKTDATA_DEFAULT_SIZE
#define RTMP_PKTDATA_DEFAULT_SIZE 4096
Definition at line 55 of file rtmpproto.c.
Referenced by read_connect(), send_invoke_response(), and write_status().
RTMP_HEADER
#define RTMP_HEADER 11
Definition at line 56 of file rtmpproto.c.
Referenced by append_flv_data(), handle_invoke_status(), handle_metadata(), inject_fake_duration_metadata(), and rtmp_write().
PLAYER_KEY_OPEN_PART_LEN
#define PLAYER_KEY_OPEN_PART_LEN 30
length of partial key used for first client digest signing
Definition at line 135 of file rtmpproto.c.
Referenced by rtmp_handshake_imprint_with_digest().
SERVER_KEY_OPEN_PART_LEN
#define SERVER_KEY_OPEN_PART_LEN 36
length of partial key used for first server digest signing
Definition at line 146 of file rtmpproto.c.
Referenced by rtmp_validate_digest().
RTMP_CTRL_ABORT_MESSAGE
#define RTMP_CTRL_ABORT_MESSAGE (2)
Definition at line 405 of file rtmpproto.c.
Referenced by read_connect().
OFFSET
#define OFFSET (x) offsetof(RTMPContext, x)
Definition at line 3106 of file rtmpproto.c.
DEC
#define DEC AV_OPT_FLAG_DECODING_PARAM
Definition at line 3107 of file rtmpproto.c.
ENC
#define ENC AV_OPT_FLAG_ENCODING_PARAM
Definition at line 3108 of file rtmpproto.c.
RTMP_PROTOCOL
#define RTMP_PROTOCOL (flavor)
Value:
static const AVClass flavor##_class = {          \
    .class_name = #flavor,                       \
    .item_name  = av_default_item_name,          \
    .option     = rtmp_options,                  \
    .version    = LIBAVUTIL_VERSION_INT,         \
};                                               \
                                                 \
const URLProtocol ff_##flavor##_protocol = {     \
    .name           = #flavor,                   \
    .url_open       = rtmp_open,                 \
    .url_read       = rtmp_read,                 \
    .url_read_seek  = rtmp_seek,                 \
    .url_read_pause = rtmp_pause,                \
    .url_write      = rtmp_write,                \
    .url_close      = rtmp_close,                \
    .priv_data_size = sizeof(RTMPContext),       \
    .flags          = URL_PROTOCOL_FLAG_NETWORK, \
    .priv_data_class= &flavor##_class,           \
};
Definition at line 3134 of file rtmpproto.c.
Enumeration Type Documentation
ClientState
enum ClientState
RTMP protocol handler state.
Enumerator
STATE_START
client has not done anything yet
STATE_HANDSHAKED
client has performed handshake
STATE_FCPUBLISH
client FCPublishing stream (for output)
STATE_PLAYING
client has started receiving multimedia data from server
STATE_SEEKING
client has started the seek operation. Back on STATE_PLAYING when the time comes
STATE_PUBLISHING
client has started sending multimedia data to server (for output)
STATE_RECEIVING
received a publish command (for input)
STATE_SENDING
received a play command (for output)
STATE_STOPPED
the broadcast has been stopped
Definition at line 59 of file rtmpproto.c.
Function Documentation
handle_chunk_size()
static int handle_chunk_size (URLContext * s, RTMPPacket * pkt) static
Definition at line 1519 of file rtmpproto.c.
Referenced by read_connect(), and rtmp_parse_result().
handle_server_bw()
static int handle_server_bw (URLContext * s, RTMPPacket * pkt) static
Definition at line 1603 of file rtmpproto.c.
Referenced by read_connect(), and rtmp_parse_result().
handle_client_bw()
static int handle_client_bw (URLContext * s, RTMPPacket * pkt) static
Definition at line 1579 of file rtmpproto.c.
Referenced by read_connect(), and rtmp_parse_result().
add_tracked_method()
static int add_tracked_method (RTMPContext * rt, const char * name, int id) static
Definition at line 162 of file rtmpproto.c.
Referenced by rtmp_send_packet().
del_tracked_method()
static void del_tracked_method (RTMPContext * rt, int index) static
Definition at line 185 of file rtmpproto.c.
Referenced by find_tracked_method().
find_tracked_method()
static int find_tracked_method (URLContext * s, RTMPPacket * pkt, int offset, char ** tracked_method) static
Definition at line 192 of file rtmpproto.c.
Referenced by handle_invoke_error(), and handle_invoke_result().
free_tracked_methods()
static void free_tracked_methods (RTMPContext * rt) static
Definition at line 217 of file rtmpproto.c.
Referenced by rtmp_close(), and rtmp_open().
rtmp_send_packet()
static int rtmp_send_packet (RTMPContext * rt, RTMPPacket * pkt, int track) static
Definition at line 228 of file rtmpproto.c.
Referenced by gen_buffer_time(), gen_bytes_read(), gen_check_bw(), gen_connect(), gen_create_stream(), gen_delete_stream(), gen_fcpublish_stream(), gen_fcsubscribe_stream(), gen_fcunpublish_stream(), gen_get_stream_length(), gen_pause(), gen_play(), gen_pong(), gen_publish(), gen_release_stream(), gen_seek(), gen_server_bw(), gen_swf_verification(), and rtmp_write().
rtmp_write_amf_data()
static int rtmp_write_amf_data (URLContext * s, char * param, uint8_t ** p) static
Definition at line 256 of file rtmpproto.c.
Referenced by gen_connect().
gen_connect()
static int gen_connect (URLContext * s, RTMPContext * rt) static
Generate 'connect' call and send it to the server.
Definition at line 319 of file rtmpproto.c.
Referenced by rtmp_open().
read_connect()
static int read_connect (URLContext * s, RTMPContext * rt) static
Definition at line 407 of file rtmpproto.c.
Referenced by rtmp_open().
gen_release_stream()
static int gen_release_stream (URLContext * s, RTMPContext * rt) static
Generate 'releaseStream' call and send it to the server.
It should make the server release some channel for media streams.
Definition at line 591 of file rtmpproto.c.
Referenced by handle_invoke_result().
gen_fcpublish_stream()
static int gen_fcpublish_stream (URLContext * s, RTMPContext * rt) static
Generate 'FCPublish' call and send it to the server.
It should make the server prepare for receiving media streams.
Definition at line 615 of file rtmpproto.c.
Referenced by handle_invoke_result().
gen_fcunpublish_stream()
static int gen_fcunpublish_stream (URLContext * s, RTMPContext * rt) static
Generate 'FCUnpublish' call and send it to the server.
It should make the server destroy stream.
Definition at line 639 of file rtmpproto.c.
Referenced by rtmp_close().
gen_create_stream()
static int gen_create_stream (URLContext * s, RTMPContext * rt) static
Generate 'createStream' call and send it to the server.
It should make the server allocate some channel for media streams.
Definition at line 663 of file rtmpproto.c.
Referenced by handle_invoke_result().
gen_delete_stream()
static int gen_delete_stream (URLContext * s, RTMPContext * rt) static
Generate 'deleteStream' call and send it to the server.
It should make the server remove some channel for media streams.
Definition at line 688 of file rtmpproto.c.
Referenced by rtmp_close().
gen_get_stream_length()
static int gen_get_stream_length (URLContext * s, RTMPContext * rt) static
Generate 'getStreamLength' call and send it to the server.
If the server knows the duration of the selected stream, it will reply with the duration in seconds.
Definition at line 714 of file rtmpproto.c.
Referenced by handle_invoke_result().
gen_buffer_time()
static int gen_buffer_time (URLContext * s, RTMPContext * rt) static
Generate client buffer time and send it to the server.
Definition at line 736 of file rtmpproto.c.
Referenced by handle_invoke_result().
gen_play()
static int gen_play (URLContext * s, RTMPContext * rt) static
Generate 'play' call and send it to the server, then ping the server to start actual playing.
Definition at line 758 of file rtmpproto.c.
Referenced by handle_invoke_result().
gen_seek()
static int gen_seek (URLContext * s, RTMPContext * rt, int64_t timestamp) static
Definition at line 782 of file rtmpproto.c.
Referenced by rtmp_seek().
gen_pause()
static int gen_pause (URLContext * s, RTMPContext * rt, int pause, uint32_t timestamp) static
Generate a pause packet that either pauses or unpauses the current stream.
Definition at line 808 of file rtmpproto.c.
Referenced by rtmp_pause().
gen_publish()
static int gen_publish (URLContext * s, RTMPContext * rt) static
Generate 'publish' call and send it to the server.
Definition at line 835 of file rtmpproto.c.
Referenced by handle_invoke_result().
gen_pong()
static int gen_pong (URLContext * s, RTMPContext * rt, RTMPPacket * ppkt) static
Generate ping reply and send it to the server.
Definition at line 862 of file rtmpproto.c.
Referenced by handle_ping().
gen_swf_verification()
static int gen_swf_verification (URLContext * s, RTMPContext * rt) static
Generate SWF verification message and send it to the server.
Definition at line 888 of file rtmpproto.c.
Referenced by handle_ping().
gen_server_bw()
static int gen_server_bw (URLContext * s, RTMPContext * rt) static
Generate server bandwidth message and send it to the server.
Definition at line 909 of file rtmpproto.c.
Referenced by handle_invoke_result().
gen_check_bw()
static int gen_check_bw (URLContext * s, RTMPContext * rt) static
Generate check bandwidth message and send it to the server.
Definition at line 928 of file rtmpproto.c.
Referenced by handle_invoke().
gen_bytes_read()
static int gen_bytes_read (URLContext * s, RTMPContext * rt, uint32_t ts) static
Generate report on bytes read so far and send it to the server.
Definition at line 949 of file rtmpproto.c.
Referenced by get_packet().
gen_fcsubscribe_stream()
static int gen_fcsubscribe_stream (URLContext * s, RTMPContext * rt, const char * subscribe) static
Definition at line 965 of file rtmpproto.c.
Referenced by handle_invoke_result().
ff_rtmp_calc_digest()
int ff_rtmp_calc_digest (const uint8_t * src, int len, int gap, const uint8_t * key, int keylen, uint8_t * dst)
Calculate HMAC-SHA2 digest for RTMP handshake packets.
Parameters
src input buffer
len input buffer length (should be 1536)
gap offset in buffer where 32 bytes should not be taken into account when calculating digest (since it will be used to store that digest)
key digest key
keylen digest key length
dst buffer where calculated digest will be stored (32 bytes)
Definition at line 985 of file rtmpproto.c.
Referenced by ff_rtmpe_compute_secret_key(), rtmp_calc_swf_verification(), rtmp_calc_swfhash(), rtmp_handshake(), rtmp_handshake_imprint_with_digest(), and rtmp_validate_digest().
ff_rtmp_calc_digest_pos()
int ff_rtmp_calc_digest_pos (const uint8_t * buf, int off, int mod_val, int add_val)
Calculate digest position for RTMP handshake packets.
Parameters
buf input buffer (should be 1536 bytes)
off offset in buffer where to start calculating digest position
mod_val value used for computing modulo
add_val value added at the end (after computing modulo)
Definition at line 1008 of file rtmpproto.c.
Referenced by ff_rtmpe_compute_secret_key(), ff_rtmpe_gen_pub_key(), rtmp_handshake_imprint_with_digest(), and rtmp_validate_digest().
rtmp_handshake_imprint_with_digest()
static int rtmp_handshake_imprint_with_digest (uint8_t * buf, int encrypted) static
Put HMAC-SHA2 digest of packet data (except for the bytes where this digest will be stored) into that packet.
Parameters
buf handshake data (1536 bytes)
encrypted use an encrypted connection (RTMPE)
Returns
offset to the digest inside input data
Definition at line 1028 of file rtmpproto.c.
Referenced by rtmp_handshake().
rtmp_validate_digest()
static int rtmp_validate_digest (uint8_t * buf, int off) static
Verify that the received server response has the expected digest value.
Parameters
buf handshake data received from the server (1536 bytes)
off position to search digest offset from
Returns
0 if digest is valid, digest position otherwise
Definition at line 1053 of file rtmpproto.c.
Referenced by rtmp_handshake().
rtmp_calc_swf_verification()
static int rtmp_calc_swf_verification (URLContext * s, RTMPContext * rt, uint8_t * buf) static
Definition at line 1071 of file rtmpproto.c.
Referenced by rtmp_handshake().
rtmp_calc_swfhash()
static int rtmp_calc_swfhash (URLContext * s) static
Definition at line 1139 of file rtmpproto.c.
Referenced by rtmp_open().
rtmp_handshake()
static int rtmp_handshake (URLContext * s, RTMPContext * rt) static
Perform handshake with the server by means of exchanging pseudorandom data signed with HMAC-SHA2 digest.
Returns
0 if handshake succeeds, negative value otherwise
Definition at line 1225 of file rtmpproto.c.
Referenced by rtmp_open().
rtmp_receive_hs_packet()
static int rtmp_receive_hs_packet (RTMPContext * rt, uint32_t * first_int, uint32_t * second_int, char * arraydata, int size) static
Definition at line 1404 of file rtmpproto.c.
Referenced by rtmp_server_handshake().
rtmp_send_hs_packet()
static int rtmp_send_hs_packet (RTMPContext * rt, uint32_t first_int, uint32_t second_int, char * arraydata, int size) static
Definition at line 1425 of file rtmpproto.c.
Referenced by rtmp_server_handshake().
rtmp_server_handshake()
static int rtmp_server_handshake (URLContext * s, RTMPContext * rt) static
rtmp handshake server side
Definition at line 1445 of file rtmpproto.c.
Referenced by rtmp_open().
handle_ping()
static int handle_ping (URLContext * s, RTMPPacket * pkt) static
Definition at line 1552 of file rtmpproto.c.
Referenced by rtmp_parse_result().
do_adobe_auth()
static int do_adobe_auth (RTMPContext * rt, const char * user, const char * salt, const char * opaque, const char * challenge) static
Definition at line 1625 of file rtmpproto.c.
Referenced by handle_connect_error().
do_llnw_auth()
static int do_llnw_auth (RTMPContext * rt, const char * user, const char * nonce) static
Definition at line 1664 of file rtmpproto.c.
Referenced by handle_connect_error().
handle_connect_error()
static int handle_connect_error (URLContext * s, const char * desc) static
Definition at line 1723 of file rtmpproto.c.
Referenced by handle_invoke_error().
handle_invoke_error()
static int handle_invoke_error (URLContext * s, RTMPPacket * pkt) static
Definition at line 1814 of file rtmpproto.c.
Referenced by handle_invoke().
write_begin()
static int write_begin (URLContext * s) static
Definition at line 1853 of file rtmpproto.c.
Referenced by send_invoke_response().
write_status()
static int write_status (URLContext * s, RTMPPacket * pkt, const char * status, const char * filename) static
Definition at line 1879 of file rtmpproto.c.
Referenced by send_invoke_response().
send_invoke_response()
static int send_invoke_response (URLContext * s, RTMPPacket * pkt) static
Definition at line 1925 of file rtmpproto.c.
Referenced by handle_invoke().
read_number_result()
static int read_number_result (RTMPPacket * pkt, double * number) static
Read the AMF_NUMBER response ("_result") to a function call (e.g.
createStream()). This response should be made up of the AMF_STRING "result", a NULL object and then the response encoded as AMF_NUMBER. On a successful response, we will return set the value to number (otherwise number will not be changed).
Returns
0 if reading the value succeeds, negative value otherwise
Definition at line 2034 of file rtmpproto.c.
Referenced by handle_invoke_result().
handle_invoke_result()
static int handle_invoke_result (URLContext * s, RTMPPacket * pkt) static
Definition at line 2064 of file rtmpproto.c.
Referenced by handle_invoke().
handle_invoke_status()
static int handle_invoke_status (URLContext * s, RTMPPacket * pkt) static
Definition at line 2136 of file rtmpproto.c.
Referenced by handle_invoke().
handle_invoke()
static int handle_invoke (URLContext * s, RTMPPacket * pkt) static
Definition at line 2173 of file rtmpproto.c.
Referenced by rtmp_parse_result().
update_offset()
static int update_offset (RTMPContext * rt, int size) static
Definition at line 2204 of file rtmpproto.c.
Referenced by append_flv_data(), and handle_metadata().
append_flv_data()
static int append_flv_data (RTMPContext * rt, RTMPPacket * pkt, int skip) static
Definition at line 2223 of file rtmpproto.c.
Referenced by get_packet(), and handle_notify().
handle_notify()
static int handle_notify (URLContext * s, RTMPPacket * pkt) static
Definition at line 2256 of file rtmpproto.c.
Referenced by get_packet().
rtmp_parse_result()
static int rtmp_parse_result (URLContext * s, RTMPContext * rt, RTMPPacket * pkt) static
Parse received packet and possibly perform some action depending on the packet contents.
Returns
0 for no errors, negative values for serious errors which prevent further communications, positive values for uncritical errors
Definition at line 2319 of file rtmpproto.c.
Referenced by get_packet(), and rtmp_write().
handle_metadata()
static int handle_metadata (RTMPContext * rt, RTMPPacket * pkt) static
Definition at line 2364 of file rtmpproto.c.
Referenced by get_packet().
get_packet()
static int get_packet (URLContext * s, int for_header) static
Interact with the server by receiving and sending RTMP packets until there is some significant data (media data or expected status notification).
Parameters
s reading context
for_header non-zero value tells function to work until it gets notification from the server that playing has been started, otherwise function will work until some media data is received (or an error happens)
Returns
0 for successful operation, negative value in case of error
Definition at line 2425 of file rtmpproto.c.
Referenced by ff_audio_rechunk_interleave(), rtmp_open(), and rtmp_read().
rtmp_close()
static int rtmp_close (URLContext * h) static
Definition at line 2508 of file rtmpproto.c.
Referenced by rtmp_open().
inject_fake_duration_metadata()
static int inject_fake_duration_metadata (RTMPContext * rt) static
Insert a fake onMetadata packet into the FLV stream to notify the FLV demuxer about the duration of the stream.
This should only be done if there was no real onMetadata packet sent by the server at the start of the stream and if we were able to retrieve a valid duration via a getStreamLength call.
Returns
0 for successful operation, negative value in case of error
Definition at line 2544 of file rtmpproto.c.
Referenced by rtmp_open().
rtmp_open()
static int rtmp_open (URLContext * s, const char * uri, int flags) static
Open RTMP connection and verify that the stream can be played.
URL syntax: rtmp://server[:port][/app][/playpath] where 'app' is first one or two directories in the path (e.g. /ondemand/, /flash/live/, etc.) and 'playpath' is a file name (the rest of the path, may be prefixed with "mp4:")
Definition at line 2607 of file rtmpproto.c.
rtmp_read()
static int rtmp_read (URLContext * s, uint8_t * buf, int size) static
Definition at line 2904 of file rtmpproto.c.
rtmp_seek()
static int64_t rtmp_seek (URLContext * s, int stream_index, int64_t timestamp, int flags) static
Definition at line 2931 of file rtmpproto.c.
rtmp_pause()
static int rtmp_pause (URLContext * s, int pause) static
Definition at line 2951 of file rtmpproto.c.
rtmp_write()
static int rtmp_write (URLContext * s, const uint8_t * buf, int size) static
Definition at line 2965 of file rtmpproto.c.
Variable Documentation
rtmp_player_key
const uint8_t rtmp_player_key[] static
Initial value:
= {
    'G', 'e', 'n', 'u', 'i', 'n', 'e', ' ', 'A', 'd', 'o', 'b', 'e', ' ',
    'F', 'l', 'a', 's', 'h', ' ', 'P', 'l', 'a', 'y', 'e', 'r', ' ', '0', '0', '1',
    0xF0, 0xEE, 0xC2, 0x4A, 0x80, 0x68, 0xBE, 0xE8, 0x2E, 0x00, 0xD0, 0xD1, 0x02,
    0x9E, 0x7E, 0x57, 0x6E, 0xEC, 0x5D, 0x2D, 0x29, 0x80, 0x6F, 0xAB, 0x93, 0xB8,
    0xE6, 0x36, 0xCF, 0xEB, 0x31, 0xAE
}
Client key used for digest signing.
Definition at line 137 of file rtmpproto.c.
Referenced by rtmp_handshake(), and rtmp_handshake_imprint_with_digest().
rtmp_server_key
const uint8_t rtmp_server_key[] static
Initial value:
= {
    'G', 'e', 'n', 'u', 'i', 'n', 'e', ' ', 'A', 'd', 'o', 'b', 'e', ' ',
    'F', 'l', 'a', 's', 'h', ' ', 'M', 'e', 'd', 'i', 'a', ' ',
    'S', 'e', 'r', 'v', 'e', 'r', ' ', '0', '0', '1',
    0xF0, 0xEE, 0xC2, 0x4A, 0x80, 0x68, 0xBE, 0xE8, 0x2E, 0x00, 0xD0, 0xD1, 0x02,
    0x9E, 0x7E, 0x57, 0x6E, 0xEC, 0x5D, 0x2D, 0x29, 0x80, 0x6F, 0xAB, 0x93, 0xB8,
    0xE6, 0x36, 0xCF, 0xEB, 0x31, 0xAE
}
Key used for RTMP server digest signing.
Definition at line 148 of file rtmpproto.c.
Referenced by rtmp_handshake(), and rtmp_validate_digest().
rtmp_options
const AVOption rtmp_options[] static
Initial value:
= {
    {"rtmp_app", "Name of application to connect to on the RTMP server", OFFSET(app), AV_OPT_TYPE_STRING, {.str = NULL }, 0, 0, DEC|ENC},
    {"rtmp_buffer", "Set buffer time in milliseconds. The default is 3000.", OFFSET(client_buffer_time), AV_OPT_TYPE_INT, {.i64 = 3000}, 0, INT_MAX, DEC|ENC},
    {"rtmp_conn", "Append arbitrary AMF data to the Connect message", OFFSET(conn), AV_OPT_TYPE_STRING, {.str = NULL }, 0, 0, DEC|ENC},
    {"rtmp_flashver", "Version of the Flash plugin used to run the SWF player.", OFFSET(flashver), AV_OPT_TYPE_STRING, {.str = NULL }, 0, 0, DEC|ENC},
    {"rtmp_flush_interval", "Number of packets flushed in the same request (RTMPT only).", OFFSET(flush_interval), AV_OPT_TYPE_INT, {.i64 = 10}, 0, INT_MAX, ENC},
    {"rtmp_live", "Specify that the media is a live stream.", OFFSET(live), AV_OPT_TYPE_INT, {.i64 = -2}, INT_MIN, INT_MAX, DEC, "rtmp_live"},
    {"any", "both", 0, AV_OPT_TYPE_CONST, {.i64 = -2}, 0, 0, DEC, "rtmp_live"},
    {"live", "live stream", 0, AV_OPT_TYPE_CONST, {.i64 = -1}, 0, 0, DEC, "rtmp_live"},
    {"recorded", "recorded stream", 0, AV_OPT_TYPE_CONST, {.i64 = 0}, 0, 0, DEC, "rtmp_live"},
    {"rtmp_pageurl", "URL of the web page in which the media was embedded. By default no value will be sent.", OFFSET(pageurl), AV_OPT_TYPE_STRING, {.str = NULL }, 0, 0, DEC},
    {"rtmp_playpath", "Stream identifier to play or to publish", OFFSET(playpath), AV_OPT_TYPE_STRING, {.str = NULL }, 0, 0, DEC|ENC},
    {"rtmp_subscribe", "Name of live stream to subscribe to. Defaults to rtmp_playpath.", OFFSET(subscribe), AV_OPT_TYPE_STRING, {.str = NULL }, 0, 0, DEC},
    {"rtmp_swfhash", "SHA256 hash of the decompressed SWF file (32 bytes).", OFFSET(swfhash), AV_OPT_TYPE_BINARY, .flags = DEC},
    {"rtmp_swfsize", "Size of the decompressed SWF file, required for SWFVerification.", OFFSET(swfsize), AV_OPT_TYPE_INT, {.i64 = 0}, 0, INT_MAX, DEC},
    {"rtmp_swfurl", "URL of the SWF player. By default no value will be sent", OFFSET(swfurl), AV_OPT_TYPE_STRING, {.str = NULL }, 0, 0, DEC|ENC},
    {"rtmp_swfverify", "URL to player swf file, compute hash/size automatically.", OFFSET(swfverify), AV_OPT_TYPE_STRING, {.str = NULL }, 0, 0, DEC},
    {"rtmp_tcurl", "URL of the target stream. Defaults to proto://host[:port]/app.", OFFSET(tcurl), AV_OPT_TYPE_STRING, {.str = NULL }, 0, 0, DEC|ENC},
    {"rtmp_listen", "Listen for incoming rtmp connections", OFFSET(listen), AV_OPT_TYPE_INT, {.i64 = 0}, INT_MIN, INT_MAX, DEC, "rtmp_listen" },
    {"listen",      "Listen for incoming rtmp connections", OFFSET(listen), AV_OPT_TYPE_INT, {.i64 = 0}, INT_MIN, INT_MAX, DEC, "rtmp_listen" },
    {"timeout", "Maximum timeout (in seconds) to wait for incoming connections. -1 is infinite. Implies -rtmp_listen 1",  OFFSET(listen_timeout), AV_OPT_TYPE_INT, {.i64 = -1}, INT_MIN, INT_MAX, DEC, "rtmp_listen" },
    { NULL },
}
Definition at line 3110 of file rtmpproto.c.