FFmpeg: libavformat/rtmp.h File Reference
rtmp.h File Reference
#include "avformat.h"
Macros
#define RTMP_DEFAULT_PORT 1935
#define RTMPS_DEFAULT_PORT 443
#define RTMP_HANDSHAKE_PACKET_SIZE 1536
#define RTMP_CLIENT_PLATFORM "LNX"
emulated Flash client version - 9.0.124.2 on Linux
#define RTMP_CLIENT_VER1 9
#define RTMP_CLIENT_VER2 0
#define RTMP_CLIENT_VER3 124
#define RTMP_CLIENT_VER4 2
Functions
int ff_rtmp_calc_digest (const uint8_t *src, int len, int gap, const uint8_t *key, int keylen, uint8_t *dst)
Calculate HMAC-SHA2 digest for RTMP handshake packets.
int ff_rtmp_calc_digest_pos (const uint8_t *buf, int off, int mod_val, int add_val)
Calculate digest position for RTMP handshake packets.
Macro Definition Documentation
RTMP_DEFAULT_PORT
#define RTMP_DEFAULT_PORT 1935
Definition at line 27 of file rtmp.h.
Referenced by rtmp_open().
RTMPS_DEFAULT_PORT
#define RTMPS_DEFAULT_PORT 443
Definition at line 28 of file rtmp.h.
Referenced by rtmp_open().
RTMP_HANDSHAKE_PACKET_SIZE
#define RTMP_HANDSHAKE_PACKET_SIZE 1536
Definition at line 30 of file rtmp.h.
Referenced by ff_rtmpe_update_keystream(), rtmp_handshake(), rtmp_handshake_imprint_with_digest(), rtmp_receive_hs_packet(), rtmp_send_hs_packet(), rtmp_server_handshake(), and rtmp_validate_digest().
RTMP_CLIENT_PLATFORM
#define RTMP_CLIENT_PLATFORM "LNX"
emulated Flash client version - 9.0.124.2 on Linux
Definition at line 36 of file rtmp.h.
Referenced by rtmp_open().
RTMP_CLIENT_VER1
#define RTMP_CLIENT_VER1 9
Definition at line 37 of file rtmp.h.
Referenced by rtmp_handshake(), and rtmp_open().
RTMP_CLIENT_VER2
#define RTMP_CLIENT_VER2 0
Definition at line 38 of file rtmp.h.
Referenced by rtmp_handshake(), and rtmp_open().
RTMP_CLIENT_VER3
#define RTMP_CLIENT_VER3 124
Definition at line 39 of file rtmp.h.
Referenced by rtmp_handshake(), and rtmp_open().
RTMP_CLIENT_VER4
#define RTMP_CLIENT_VER4 2
Definition at line 40 of file rtmp.h.
Referenced by rtmp_handshake(), and rtmp_open().
Function Documentation
ff_rtmp_calc_digest()
int ff_rtmp_calc_digest (const uint8_t * src, int len, int gap, const uint8_t * key, int keylen, uint8_t * dst)
Calculate HMAC-SHA2 digest for RTMP handshake packets.
Parameters
src input buffer
len input buffer length (should be 1536)
gap offset in buffer where 32 bytes should not be taken into account when calculating digest (since it will be used to store that digest)
key digest key
keylen digest key length
dst buffer where calculated digest will be stored (32 bytes)
Definition at line 985 of file rtmpproto.c.
Referenced by ff_rtmpe_compute_secret_key(), rtmp_calc_swf_verification(), rtmp_calc_swfhash(), rtmp_handshake(), rtmp_handshake_imprint_with_digest(), and rtmp_validate_digest().
ff_rtmp_calc_digest_pos()
int ff_rtmp_calc_digest_pos (const uint8_t * buf, int off, int mod_val, int add_val)
Calculate digest position for RTMP handshake packets.
Parameters
buf input buffer (should be 1536 bytes)
off offset in buffer where to start calculating digest position
mod_val value used for computing modulo
add_val value added at the end (after computing modulo)
Definition at line 1008 of file rtmpproto.c.
Referenced by ff_rtmpe_compute_secret_key(), ff_rtmpe_gen_pub_key(), rtmp_handshake_imprint_with_digest(), and rtmp_validate_digest().