FFmpeg: libavformat/rtmppkt.h File Reference
rtmppkt.h File Reference
#include "libavcodec/bytestream.h"
#include "avformat.h"
#include "url.h"
Data Structures
struct RTMPPacket
structure for holding RTMP packets
Macros
#define RTMP_CHANNELS 65599
maximum possible number of different RTMP channels
Enumerations
enum RTMPChannel {
RTMP_NETWORK_CHANNEL = 2, RTMP_SYSTEM_CHANNEL, RTMP_AUDIO_CHANNEL, RTMP_VIDEO_CHANNEL = 6,
RTMP_SOURCE_CHANNEL = 8
}
channels used to for RTMP packets with different purposes (i.e.
enum RTMPPacketType {
RTMP_PT_CHUNK_SIZE = 1, RTMP_PT_BYTES_READ = 3, RTMP_PT_PING, RTMP_PT_SERVER_BW,
RTMP_PT_CLIENT_BW, RTMP_PT_AUDIO = 8, RTMP_PT_VIDEO, RTMP_PT_FLEX_STREAM = 15,
RTMP_PT_FLEX_OBJECT, RTMP_PT_FLEX_MESSAGE, RTMP_PT_NOTIFY, RTMP_PT_SHARED_OBJ,
RTMP_PT_INVOKE, RTMP_PT_METADATA = 22
}
known RTMP packet types
enum RTMPPacketSize { RTMP_PS_TWELVEBYTES = 0, RTMP_PS_EIGHTBYTES, RTMP_PS_FOURBYTES, RTMP_PS_ONEBYTE }
possible RTMP packet header sizes
Functions
int ff_rtmp_packet_create (RTMPPacket *pkt, int channel_id, RTMPPacketType type, int timestamp, int size)
Create new RTMP packet with given attributes.
void ff_rtmp_packet_destroy (RTMPPacket *pkt)
Free RTMP packet.
int ff_rtmp_packet_read (URLContext *h, RTMPPacket *p, int chunk_size, RTMPPacket **prev_pkt, int *nb_prev_pkt)
Read RTMP packet sent by the server.
int ff_rtmp_packet_read_internal (URLContext *h, RTMPPacket *p, int chunk_size, RTMPPacket **prev_pkt, int *nb_prev_pkt, uint8_t c)
Read internal RTMP packet sent by the server.
int ff_rtmp_packet_write (URLContext *h, RTMPPacket *p, int chunk_size, RTMPPacket **prev_pkt, int *nb_prev_pkt)
Send RTMP packet to the server.
void ff_rtmp_packet_dump (void *ctx, RTMPPacket *p)
Print information and contents of RTMP packet.
int ff_rtmp_check_alloc_array (RTMPPacket **prev_pkt, int *nb_prev_pkt, int channel)
Enlarge the prev_pkt array to fit the given channel.
Functions used to work with the AMF format (which is also used in .flv)
See also
amf_* funcs in libavformat/flvdec.c
int ff_amf_tag_size (const uint8_t *data, const uint8_t *data_end)
Calculate number of bytes taken by first AMF entry in data.
int ff_amf_get_field_value (const uint8_t *data, const uint8_t *data_end, const uint8_t *name, uint8_t *dst, int dst_size)
Retrieve value of given AMF object field in string form.
void ff_amf_write_bool (uint8_t **dst, int val)
Write boolean value in AMF format to buffer.
void ff_amf_write_number (uint8_t **dst, double num)
Write number in AMF format to buffer.
void ff_amf_write_string (uint8_t **dst, const char *str)
Write string in AMF format to buffer.
void ff_amf_write_string2 (uint8_t **dst, const char *str1, const char *str2)
Write a string consisting of two parts in AMF format to a buffer.
void ff_amf_write_null (uint8_t **dst)
Write AMF NULL value to buffer.
void ff_amf_write_object_start (uint8_t **dst)
Write marker for AMF object to buffer.
void ff_amf_write_field_name (uint8_t **dst, const char *str)
Write string used as field name in AMF object to buffer.
void ff_amf_write_object_end (uint8_t **dst)
Write marker for end of AMF object to buffer.
int ff_amf_read_bool (GetByteContext *gbc, int *val)
Read AMF boolean value.
int ff_amf_read_number (GetByteContext *gbc, double *val)
Read AMF number value.
int ff_amf_get_string (GetByteContext *bc, uint8_t *str, int strsize, int *length)
Get AMF string value.
int ff_amf_read_string (GetByteContext *gbc, uint8_t *str, int strsize, int *length)
Read AMF string value.
int ff_amf_read_null (GetByteContext *gbc)
Read AMF NULL value.
int ff_amf_match_string (const uint8_t *data, int size, const char *str)
Match AMF string with a NULL-terminated string.
Macro Definition Documentation
RTMP_CHANNELS
#define RTMP_CHANNELS 65599
maximum possible number of different RTMP channels
Definition at line 30 of file rtmppkt.h.
Enumeration Type Documentation
RTMPChannel
enum RTMPChannel
channels used to for RTMP packets with different purposes (i.e.
data, network control, remote procedure calls, etc.)
Enumerator
RTMP_NETWORK_CHANNEL
channel for network-related messages (bandwidth report, ping, etc)
RTMP_SYSTEM_CHANNEL
channel for sending server control messages
RTMP_AUDIO_CHANNEL
channel for audio data
RTMP_VIDEO_CHANNEL
channel for video data
RTMP_SOURCE_CHANNEL
channel for a/v invokes
Definition at line 36 of file rtmppkt.h.
RTMPPacketType
enum RTMPPacketType
known RTMP packet types
Enumerator
RTMP_PT_CHUNK_SIZE
chunk size change
RTMP_PT_BYTES_READ
number of bytes read
RTMP_PT_PING
ping
RTMP_PT_SERVER_BW
server bandwidth
RTMP_PT_CLIENT_BW
client bandwidth
RTMP_PT_AUDIO
audio packet
RTMP_PT_VIDEO
video packet
RTMP_PT_FLEX_STREAM
Flex shared stream.
RTMP_PT_FLEX_OBJECT
Flex shared object.
RTMP_PT_FLEX_MESSAGE
Flex shared message.
RTMP_PT_NOTIFY
some notification
RTMP_PT_SHARED_OBJ
shared object
RTMP_PT_INVOKE
invoke some stream action
RTMP_PT_METADATA
FLV metadata.
Definition at line 47 of file rtmppkt.h.
RTMPPacketSize
enum RTMPPacketSize
possible RTMP packet header sizes
Enumerator
RTMP_PS_TWELVEBYTES
packet has 12-byte header
RTMP_PS_EIGHTBYTES
packet has 8-byte header
RTMP_PS_FOURBYTES
packet has 4-byte header
RTMP_PS_ONEBYTE
packet is really a next chunk of a packet
Definition at line 67 of file rtmppkt.h.
Function Documentation
ff_rtmp_packet_create()
int ff_rtmp_packet_create (RTMPPacket * pkt, int channel_id, RTMPPacketType type, int timestamp, int size)
Create new RTMP packet with given attributes.
Parameters
pkt packet
channel_id packet channel ID
type packet type
timestamp packet timestamp
size packet size
Returns
zero on success, negative value otherwise
Definition at line 410 of file rtmppkt.c.
Referenced by gen_buffer_time(), gen_bytes_read(), gen_check_bw(), gen_connect(), gen_create_stream(), gen_delete_stream(), gen_fcpublish_stream(), gen_fcsubscribe_stream(), gen_fcunpublish_stream(), gen_get_stream_length(), gen_pause(), gen_play(), gen_pong(), gen_publish(), gen_release_stream(), gen_seek(), gen_server_bw(), gen_swf_verification(), read_connect(), rtmp_packet_read_one_chunk(), rtmp_write(), send_invoke_response(), write_begin(), and write_status().
ff_rtmp_packet_destroy()
void ff_rtmp_packet_destroy (RTMPPacket * pkt)
Free RTMP packet.
Parameters
pkt packet
Definition at line 428 of file rtmppkt.c.
Referenced by gen_connect(), get_packet(), read_connect(), rtmp_close(), rtmp_packet_read_one_chunk(), rtmp_send_packet(), rtmp_write(), send_invoke_response(), write_begin(), and write_status().
ff_rtmp_packet_read()
int ff_rtmp_packet_read (URLContext * h, RTMPPacket * p, int chunk_size, RTMPPacket ** prev_pkt, int * nb_prev_pkt)
Read RTMP packet sent by the server.
Parameters
h reader context
p packet
chunk_size current chunk size
prev_pkt previously read packet headers for all channels (may be needed for restoring incomplete packet header)
nb_prev_pkt number of allocated elements in prev_pkt
Returns
number of bytes read on success, negative value otherwise
Definition at line 159 of file rtmppkt.c.
Referenced by get_packet(), and read_connect().
ff_rtmp_packet_read_internal()
int ff_rtmp_packet_read_internal (URLContext * h, RTMPPacket * p, int chunk_size, RTMPPacket ** prev_pkt, int * nb_prev_pkt, uint8_t c)
Read internal RTMP packet sent by the server.
Parameters
h reader context
p packet
chunk_size current chunk size
prev_pkt previously read packet headers for all channels (may be needed for restoring incomplete packet header)
nb_prev_pkt number of allocated elements in prev_pkt
c the first byte already read
Returns
number of bytes read on success, negative value otherwise
Definition at line 298 of file rtmppkt.c.
Referenced by ff_rtmp_packet_read(), and rtmp_write().
ff_rtmp_packet_write()
int ff_rtmp_packet_write (URLContext * h, RTMPPacket * p, int chunk_size, RTMPPacket ** prev_pkt, int * nb_prev_pkt)
Send RTMP packet to the server.
Parameters
h reader context
p packet to send
chunk_size current chunk size
prev_pkt previously sent packet headers for all channels (may be used for packet header compressing)
nb_prev_pkt number of allocated elements in prev_pkt
Returns
number of bytes written on success, negative value otherwise
Definition at line 313 of file rtmppkt.c.
Referenced by handle_chunk_size(), read_connect(), rtmp_send_packet(), send_invoke_response(), write_begin(), and write_status().
ff_rtmp_packet_dump()
void ff_rtmp_packet_dump (void * ctx, RTMPPacket * p)
Print information and contents of RTMP packet.
Parameters
ctx output context
p packet to dump
Definition at line 618 of file rtmppkt.c.
Referenced by read_connect(), and rtmp_parse_result().
ff_rtmp_check_alloc_array()
int ff_rtmp_check_alloc_array (RTMPPacket ** prev_pkt, int * nb_prev_pkt, int channel)
Enlarge the prev_pkt array to fit the given channel.
Parameters
prev_pkt array with previously sent packet headers
nb_prev_pkt number of allocated elements in prev_pkt
channel the channel number that needs to be allocated
Definition at line 138 of file rtmppkt.c.
Referenced by ff_rtmp_packet_write(), rtmp_packet_read_one_chunk(), and rtmp_write().
ff_amf_tag_size()
int ff_amf_tag_size (const uint8_t * data, const uint8_t * data_end)
Calculate number of bytes taken by first AMF entry in data.
Parameters
data input data
data_end input buffer end
Returns
number of bytes used by first AMF entry
Definition at line 436 of file rtmppkt.c.
Referenced by amf_tag_contents(), ff_amf_get_field_value(), ff_amf_tag_size(), ff_rtmp_packet_dump(), handle_invoke_status(), and handle_notify().
ff_amf_get_field_value()
int ff_amf_get_field_value (const uint8_t * data, const uint8_t * data_end, const uint8_t * name, uint8_t * dst, int dst_size)
Retrieve value of given AMF object field in string form.
Parameters
data AMF object data
data_end input buffer end
name name of field to retrieve
dst buffer for storing result
dst_size output buffer size
Returns
0 if search and retrieval succeeded, negative value otherwise
Definition at line 480 of file rtmppkt.c.
Referenced by handle_invoke_error(), handle_invoke_status(), and read_connect().
ff_amf_write_bool()
void ff_amf_write_bool (uint8_t ** dst, int val)
Write boolean value in AMF format to buffer.
Parameters
dst pointer to the input buffer (will be modified)
val value to write
Definition at line 31 of file rtmppkt.c.
Referenced by gen_connect(), gen_pause(), and rtmp_write_amf_data().
ff_amf_write_number()
void ff_amf_write_number (uint8_t ** dst, double num)
Write number in AMF format to buffer.
Parameters
dst pointer to the input buffer (will be modified)
num value to write
Definition at line 37 of file rtmppkt.c.
Referenced by gen_check_bw(), gen_connect(), gen_create_stream(), gen_delete_stream(), gen_fcpublish_stream(), gen_fcsubscribe_stream(), gen_fcunpublish_stream(), gen_get_stream_length(), gen_pause(), gen_play(), gen_publish(), gen_release_stream(), gen_seek(), read_connect(), rtmp_write_amf_data(), send_invoke_response(), and write_status().
ff_amf_write_string()
void ff_amf_write_string (uint8_t ** dst, const char * str)
Write string in AMF format to buffer.
Parameters
dst pointer to the input buffer (will be modified)
str string to write
Definition at line 43 of file rtmppkt.c.
Referenced by gen_check_bw(), gen_connect(), gen_create_stream(), gen_delete_stream(), gen_fcpublish_stream(), gen_fcsubscribe_stream(), gen_fcunpublish_stream(), gen_get_stream_length(), gen_pause(), gen_play(), gen_publish(), gen_release_stream(), gen_seek(), read_connect(), rtmp_write(), rtmp_write_amf_data(), send_invoke_response(), and write_status().
ff_amf_write_string2()
void ff_amf_write_string2 (uint8_t ** dst, const char * str1, const char * str2)
Write a string consisting of two parts in AMF format to a buffer.
Parameters
dst pointer to the input buffer (will be modified)
str1 first string to write, may be null
str2 second string to write, may be null
Definition at line 50 of file rtmppkt.c.
Referenced by gen_connect().
ff_amf_write_null()
void ff_amf_write_null (uint8_t ** dst)
Write AMF NULL value to buffer.
Parameters
dst pointer to the input buffer (will be modified)
Definition at line 63 of file rtmppkt.c.
Referenced by gen_check_bw(), gen_create_stream(), gen_delete_stream(), gen_fcpublish_stream(), gen_fcsubscribe_stream(), gen_fcunpublish_stream(), gen_get_stream_length(), gen_pause(), gen_play(), gen_publish(), gen_release_stream(), gen_seek(), read_connect(), rtmp_write_amf_data(), send_invoke_response(), and write_status().
ff_amf_write_object_start()
void ff_amf_write_object_start (uint8_t ** dst)
Write marker for AMF object to buffer.
Parameters
dst pointer to the input buffer (will be modified)
Definition at line 68 of file rtmppkt.c.
Referenced by gen_connect(), read_connect(), rtmp_write_amf_data(), and write_status().
ff_amf_write_field_name()
void ff_amf_write_field_name (uint8_t ** dst, const char * str)
Write string used as field name in AMF object to buffer.
Parameters
dst pointer to the input buffer (will be modified)
str string to write
Definition at line 73 of file rtmppkt.c.
Referenced by gen_connect(), read_connect(), rtmp_write_amf_data(), and write_status().
ff_amf_write_object_end()
void ff_amf_write_object_end (uint8_t ** dst)
Write marker for end of AMF object to buffer.
Parameters
dst pointer to the input buffer (will be modified)
Definition at line 79 of file rtmppkt.c.
Referenced by gen_connect(), read_connect(), rtmp_write_amf_data(), and write_status().
ff_amf_read_bool()
int ff_amf_read_bool (GetByteContext * gbc, int * val)
Read AMF boolean value.
Parameters
[in,out] gbc GetByteContext initialized with AMF-formatted data
[out] val 0 or 1
Returns
0 on success or an AVERROR code on failure
Definition at line 87 of file rtmppkt.c.
ff_amf_read_number()
int ff_amf_read_number (GetByteContext * gbc, double * val)
Read AMF number value.
Parameters
[in,out] gbc GetByteContext initialized with AMF-formatted data
[out] val read value
Returns
0 on success or an AVERROR code on failure
Definition at line 95 of file rtmppkt.c.
Referenced by find_tracked_method(), read_connect(), read_number_result(), rtmp_send_packet(), and send_invoke_response().
ff_amf_get_string()
int ff_amf_get_string (GetByteContext * bc, uint8_t * str, int strsize, int * length)
Get AMF string value.
This function behaves the same as ff_amf_read_string except that it does not expect the AMF type prepended to the actual data. Appends a trailing null byte to output string in order to ease later parsing.
Parameters
[in,out] gbc GetByteContext initialized with AMF-formatted data
[out] str read string
[in] strsize buffer size available to store the read string
[out] length read string length
Returns
0 on success or an AVERROR code on failure
Definition at line 105 of file rtmppkt.c.
Referenced by ff_amf_read_string(), and handle_notify().
ff_amf_read_string()
int ff_amf_read_string (GetByteContext * gbc, uint8_t * str, int strsize, int * length)
Read AMF string value.
Appends a trailing null byte to output string in order to ease later parsing.
Parameters
[in,out] gbc GetByteContext initialized with AMF-formatted data
[out] str read string
[in] strsize buffer size available to store the read string
[out] length read string length
Returns
0 on success or an AVERROR code on failure
Definition at line 123 of file rtmppkt.c.
Referenced by handle_notify(), read_connect(), read_number_result(), rtmp_send_packet(), rtmp_write(), and send_invoke_response().
ff_amf_read_null()
int ff_amf_read_null (GetByteContext * gbc)
Read AMF NULL value.
Parameters
[in,out] gbc GetByteContext initialized with AMF-formatted data
Returns
0 on success or an AVERROR code on failure
Definition at line 131 of file rtmppkt.c.
Referenced by read_number_result(), and send_invoke_response().
ff_amf_match_string()
int ff_amf_match_string (const uint8_t * data, int size, const char * str)
Match AMF string with a NULL-terminated string.
Returns
0 if the strings do not match.
Definition at line 644 of file rtmppkt.c.
Referenced by handle_invoke().