FFmpeg: libavformat/rtmpcrypt.h File Reference
rtmpcrypt.h File Reference
#include <stdint.h>
#include "url.h"
Functions
int ff_rtmpe_gen_pub_key (URLContext *h, uint8_t *buf)
Initialize the Diffie-Hellmann context and generate the public key.
int ff_rtmpe_compute_secret_key (URLContext *h, const uint8_t *serverdata, const uint8_t *clientdata, int type)
Compute the shared secret key and initialize the RC4 encryption.
void ff_rtmpe_encrypt_sig (URLContext *h, uint8_t *signature, const uint8_t *digest, int type)
Encrypt the signature.
int ff_rtmpe_update_keystream (URLContext *h)
Update the keystream and set RC4 keys for encryption.
Function Documentation
ff_rtmpe_gen_pub_key()
int ff_rtmpe_gen_pub_key (URLContext * h, uint8_t * buf)
Initialize the Diffie-Hellmann context and generate the public key.
Parameters
h an URLContext
buf handshake data (1536 bytes)
Returns
zero on success, negative value otherwise
Definition at line 122 of file rtmpcrypt.c.
Referenced by rtmp_handshake().
ff_rtmpe_compute_secret_key()
int ff_rtmpe_compute_secret_key (URLContext * h, const uint8_t * serverdata, const uint8_t * clientdata, int type)
Compute the shared secret key and initialize the RC4 encryption.
Parameters
h an URLContext
serverdata server data (1536 bytes)
clientdata client data (1536 bytes)
type the position of the server digest
Returns
zero on success, negative value otherwise
Definition at line 145 of file rtmpcrypt.c.
Referenced by rtmp_handshake().
ff_rtmpe_encrypt_sig()
void ff_rtmpe_encrypt_sig (URLContext * h, uint8_t * signature, const uint8_t * digest, int type)
Encrypt the signature.
Parameters
h an URLContext
signature the signature to encrypt
digest the digest used for finding the encryption key
type type of encryption (8 for XTEA, 9 for Blowfish)
Definition at line 207 of file rtmpcrypt.c.
Referenced by rtmp_handshake().
ff_rtmpe_update_keystream()
int ff_rtmpe_update_keystream (URLContext * h)
Update the keystream and set RC4 keys for encryption.
Parameters
h an URLContext
Returns
zero on success, negative value otherwise
Definition at line 223 of file rtmpcrypt.c.
Referenced by rtmp_handshake().