FFmpeg: libavformat/rtpdec_xiph.c File Reference
rtpdec_xiph.c File Reference
Xiph / RTP Code.
#include "libavutil/attributes.h"
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/base64.h"
#include "libavcodec/bytestream.h"
#include "avio_internal.h"
#include "internal.h"
#include "rtpdec.h"
#include "rtpdec_formats.h"
Data Structures
struct PayloadContext
RTP/JPEG specific private data.
Functions
static void xiph_close_context (PayloadContext *data)
static int xiph_handle_packet (AVFormatContext *ctx, PayloadContext *data, AVStream *st, AVPacket *pkt, uint32_t *timestamp, const uint8_t *buf, int len, uint16_t seq, int flags)
static int get_base128 (const uint8_t **buf, const uint8_t *buf_end)
Length encoding described in RFC5215 section 3.1.1.
static int parse_packed_headers (AVFormatContext *s, const uint8_t *packed_headers, const uint8_t *packed_headers_end, AVCodecParameters *par, PayloadContext *xiph_data)
Based off parse_packed_headers in Vorbis RTP.
static int xiph_parse_fmtp_pair (AVFormatContext *s, AVStream *stream, PayloadContext *xiph_data, const char *attr, const char *value)
static int xiph_parse_sdp_line (AVFormatContext *s, int st_index, PayloadContext *data, const char *line)
Variables
RTPDynamicProtocolHandler ff_theora_dynamic_handler
RTPDynamicProtocolHandler ff_vorbis_dynamic_handler
Detailed Description
Xiph / RTP Code.
Author
Colin McQuillan m.nil.nosp@m.oc@g.nosp@m.mail..nosp@m.com
Josh Allmann joshu.nosp@m.a.al.nosp@m.lmann.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Definition in file rtpdec_xiph.c.
Function Documentation
xiph_close_context()
static void xiph_close_context (PayloadContext * data) static
Definition at line 53 of file rtpdec_xiph.c.
xiph_handle_packet()
static int xiph_handle_packet (AVFormatContext * ctx, PayloadContext * data, AVStream * st, AVPacket * pkt, uint32_t * timestamp, const uint8_t * buf, int len, uint16_t seq, int flags) static
Definition at line 60 of file rtpdec_xiph.c.
get_base128()
static int get_base128 (const uint8_t ** buf, const uint8_t * buf_end) static
Length encoding described in RFC5215 section 3.1.1.
Definition at line 207 of file rtpdec_xiph.c.
Referenced by parse_packed_headers().
parse_packed_headers()
static int parse_packed_headers (AVFormatContext * s, const uint8_t * packed_headers, const uint8_t * packed_headers_end, AVCodecParameters * par, PayloadContext * xiph_data) static
Based off parse_packed_headers in Vorbis RTP.
Definition at line 225 of file rtpdec_xiph.c.
Referenced by xiph_parse_fmtp_pair().
xiph_parse_fmtp_pair()
static int xiph_parse_fmtp_pair (AVFormatContext * s, AVStream * stream, PayloadContext * xiph_data, const char * attr, const char * value) static
Definition at line 286 of file rtpdec_xiph.c.
Referenced by xiph_parse_sdp_line().
xiph_parse_sdp_line()
static int xiph_parse_sdp_line (AVFormatContext * s, int st_index, PayloadContext * data, const char * line) static
Definition at line 354 of file rtpdec_xiph.c.
Variable Documentation
ff_theora_dynamic_handler
RTPDynamicProtocolHandler ff_theora_dynamic_handler
Initial value:
= {
    .enc_name         = "theora",
    .codec_type       = AVMEDIA_TYPE_VIDEO,
    .codec_id         = AV_CODEC_ID_THEORA,
    .priv_data_size   = sizeof(PayloadContext),
    .parse_sdp_a_line = xiph_parse_sdp_line,
    .close            = xiph_close_context,
    .parse_packet     = xiph_handle_packet,
}
Definition at line 370 of file rtpdec_xiph.c.
Referenced by ff_register_rtp_dynamic_payload_handlers().
ff_vorbis_dynamic_handler
RTPDynamicProtocolHandler ff_vorbis_dynamic_handler
Initial value:
= {
    .enc_name         = "vorbis",
    .codec_type       = AVMEDIA_TYPE_AUDIO,
    .codec_id         = AV_CODEC_ID_VORBIS,
    .need_parsing     = AVSTREAM_PARSE_HEADERS,
    .priv_data_size   = sizeof(PayloadContext),
    .parse_sdp_a_line = xiph_parse_sdp_line,
    .close            = xiph_close_context,
    .parse_packet     = xiph_handle_packet,
}
Definition at line 380 of file rtpdec_xiph.c.
Referenced by ff_register_rtp_dynamic_payload_handlers().