FFmpeg: libavformat/rtpdec.h File Reference
rtpdec.h File Reference
#include "libavcodec/avcodec.h"
#include "avformat.h"
#include "rtp.h"
#include "url.h"
#include "srtp.h"
Data Structures
struct RTPStatistics
struct RTPDynamicProtocolHandler
struct RTPPacket
struct RTPDemuxContext
Macros
#define RTP_MIN_PACKET_LENGTH 12
#define RTP_MAX_PACKET_LENGTH 8192
#define RTP_REORDER_QUEUE_DEFAULT_SIZE 500
#define RTP_NOTS_VALUE ((uint32_t)-1)
#define RTP_FLAG_KEY 0x1
RTP packet contains a keyframe.
#define RTP_FLAG_MARKER 0x2
RTP marker bit was set for this packet.
Typedefs
typedef int(* DynamicPayloadPacketHandlerProc) (AVFormatContext *ctx, PayloadContext *s, AVStream *st, AVPacket *pkt, uint32_t *timestamp, const uint8_t *buf, int len, uint16_t seq, int flags)
Packet parsing for "private" payloads in the RTP specs.
Functions
RTPDemuxContext * ff_rtp_parse_open (AVFormatContext *s1, AVStream *st, int payload_type, int queue_size)
open a new RTP parse context for stream 'st'.
void ff_rtp_parse_set_dynamic_protocol (RTPDemuxContext *s, PayloadContext *ctx, RTPDynamicProtocolHandler *handler)
void ff_rtp_parse_set_crypto (RTPDemuxContext *s, const char *suite, const char *params)
int ff_rtp_parse_packet (RTPDemuxContext *s, AVPacket *pkt, uint8_t **buf, int len)
Parse an RTP or RTCP packet directly sent as a buffer.
void ff_rtp_parse_close (RTPDemuxContext *s)
int64_t ff_rtp_queued_packet_time (RTPDemuxContext *s)
void ff_rtp_reset_packet_queue (RTPDemuxContext *s)
void ff_rtp_send_punch_packets (URLContext *rtp_handle)
Send a dummy packet on both port pairs to set up the connection state in potential NAT routers, so that we're able to receive packets.
int ff_rtp_check_and_send_back_rr (RTPDemuxContext *s, URLContext *fd, AVIOContext *avio, int count)
some rtp servers assume client is dead if they don't hear from them...
int ff_rtp_send_rtcp_feedback (RTPDemuxContext *s, URLContext *fd, AVIOContext *avio)
void ff_register_dynamic_payload_handler (RTPDynamicProtocolHandler *handler)
RTPDynamicProtocolHandler * ff_rtp_handler_find_by_name (const char *name, enum AVMediaType codec_type)
RTPDynamicProtocolHandler * ff_rtp_handler_find_by_id (int id, enum AVMediaType codec_type)
int ff_rtsp_next_attr_and_value (const char **p, char *attr, int attr_size, char *value, int value_size)
int ff_parse_fmtp (AVFormatContext *s, AVStream *stream, PayloadContext *data, const char *p, int(*parse_fmtp)(AVFormatContext *s, AVStream *stream, PayloadContext *data, const char *attr, const char *value))
void ff_register_rtp_dynamic_payload_handlers (void)
int ff_rtp_finalize_packet (AVPacket *pkt, AVIOContext **dyn_buf, int stream_idx)
Close the dynamic buffer and make a packet from it.
Macro Definition Documentation
RTP_MIN_PACKET_LENGTH
#define RTP_MIN_PACKET_LENGTH 12
Definition at line 35 of file rtpdec.h.
RTP_MAX_PACKET_LENGTH
#define RTP_MAX_PACKET_LENGTH 8192
Definition at line 36 of file rtpdec.h.
Referenced by ff_rtsp_open_transport_ctx(), main(), rtp_parse_mp4_au(), sap_fetch_packet(), sap_read_header(), and test_encrypt().
RTP_REORDER_QUEUE_DEFAULT_SIZE
#define RTP_REORDER_QUEUE_DEFAULT_SIZE 500
Definition at line 38 of file rtpdec.h.
Referenced by ff_rtsp_open_transport_ctx().
RTP_NOTS_VALUE
#define RTP_NOTS_VALUE ((uint32_t)-1)
Definition at line 40 of file rtpdec.h.
Referenced by finalize_packet(), mpegts_handle_packet(), qdm2_parse_packet(), rtp_parse_one_packet(), and store_packet().
RTP_FLAG_KEY
#define RTP_FLAG_KEY 0x1
RTP packet contains a keyframe.
Definition at line 92 of file rtpdec.h.
Referenced by ff_rdt_parse_packet(), and rdt_parse_packet().
RTP_FLAG_MARKER
#define RTP_FLAG_MARKER 0x2
RTP marker bit was set for this packet.
Definition at line 93 of file rtpdec.h.
Referenced by aac_parse_packet(), ac3_handle_packet(), asfrtp_parse_packet(), dv_handle_packet(), h261_handle_packet(), h263_handle_packet(), jpeg_parse_packet(), latm_parse_packet(), qt_rtp_parse_packet(), rtp_parse_packet_internal(), vc2hq_handle_frame_fragment(), vp8_handle_packet(), and vp9_handle_packet().
Typedef Documentation
DynamicPayloadPacketHandlerProc
typedef int(* DynamicPayloadPacketHandlerProc) (AVFormatContext *ctx, PayloadContext *s, AVStream *st, AVPacket *pkt, uint32_t *timestamp, const uint8_t *buf, int len, uint16_t seq, int flags)
Packet parsing for "private" payloads in the RTP specs.
Parameters
ctx RTSP demuxer context
s stream context
st stream that this packet belongs to
pkt packet in which to write the parsed data
timestamp pointer to the RTP timestamp of the input data, can be updated by the function if returning older, buffered data
buf pointer to raw RTP packet data
len length of buf
seq RTP sequence number of the packet
flags flags from the RTP packet header (RTP_FLAG_*)
Definition at line 108 of file rtpdec.h.
Function Documentation
ff_rtp_parse_open()
RTPDemuxContext* ff_rtp_parse_open (AVFormatContext * s1, AVStream * st, int payload_type, int queue_size)
open a new RTP parse context for stream 'st'.
'st' can be NULL for MPEG-2 TS streams.
Definition at line 521 of file rtpdec.c.
Referenced by ff_rtsp_open_transport_ctx().
ff_rtp_parse_set_dynamic_protocol()
void ff_rtp_parse_set_dynamic_protocol (RTPDemuxContext * s, PayloadContext * ctx, RTPDynamicProtocolHandler * handler)
Definition at line 557 of file rtpdec.c.
Referenced by ff_rtsp_open_transport_ctx().
ff_rtp_parse_set_crypto()
void ff_rtp_parse_set_crypto (RTPDemuxContext * s, const char * suite, const char * params)
Definition at line 564 of file rtpdec.c.
Referenced by ff_rtsp_open_transport_ctx().
ff_rtp_parse_packet()
int ff_rtp_parse_packet (RTPDemuxContext * s, AVPacket * pkt, uint8_t ** bufptr, int len)
Parse an RTP or RTCP packet directly sent as a buffer.
Parameters
s RTP parse context.
pkt returned packet
bufptr pointer to the input buffer or NULL to read the next packets
len buffer len
Returns
0 if a packet is returned, 1 if a packet is returned and more can follow (use buf as NULL to read the next). -1 if no packet (error or no more packet).
Definition at line 852 of file rtpdec.c.
Referenced by ff_rtsp_open_transport_ctx().
ff_rtp_parse_close()
void ff_rtp_parse_close (RTPDemuxContext * s)
Definition at line 865 of file rtpdec.c.
Referenced by ff_rtsp_undo_setup().
ff_rtp_queued_packet_time()
int64_t ff_rtp_queued_packet_time (RTPDemuxContext * s)
Definition at line 738 of file rtpdec.c.
Referenced by ff_rtsp_open_transport_ctx().
ff_rtp_reset_packet_queue()
void ff_rtp_reset_packet_queue (RTPDemuxContext * s)
Definition at line 693 of file rtpdec.c.
Referenced by ff_rtp_parse_close(), and rtsp_read_play().
ff_rtp_send_punch_packets()
void ff_rtp_send_punch_packets (URLContext * rtp_handle)
Send a dummy packet on both port pairs to set up the connection state in potential NAT routers, so that we're able to receive packets.
Note, this only works if the NAT router doesn't remap ports. This isn't a standardized procedure, but it works in many cases in practice.
The same routine is used with RDT too, even if RDT doesn't use normal RTP packets otherwise.
Definition at line 385 of file rtpdec.c.
Referenced by rtsp_read_play().
ff_rtp_check_and_send_back_rr()
int ff_rtp_check_and_send_back_rr (RTPDemuxContext * s, URLContext * fd, AVIOContext * avio, int count)
some rtp servers assume client is dead if they don't hear from them...
so we send a Receiver Report to the provided URLContext or AVIOContext (we don't have access to the rtcp handle from here)
Definition at line 282 of file rtpdec.c.
Referenced by ff_rtsp_open_transport_ctx().
ff_rtp_send_rtcp_feedback()
int ff_rtp_send_rtcp_feedback (RTPDemuxContext * s, URLContext * fd, AVIOContext * avio)
Definition at line 453 of file rtpdec.c.
Referenced by ff_rtsp_open_transport_ctx().
ff_register_dynamic_payload_handler()
void ff_register_dynamic_payload_handler (RTPDynamicProtocolHandler * handler)
Definition at line 74 of file rtpdec.c.
Referenced by ff_register_rdt_dynamic_payload_handlers(), and ff_register_rtp_dynamic_payload_handlers().
ff_rtp_handler_find_by_name()
RTPDynamicProtocolHandler* ff_rtp_handler_find_by_name (const char * name, enum AVMediaType codec_type)
Definition at line 131 of file rtpdec.c.
Referenced by get_sockaddr().
ff_rtp_handler_find_by_id()
RTPDynamicProtocolHandler* ff_rtp_handler_find_by_id (int id, enum AVMediaType codec_type)
Definition at line 144 of file rtpdec.c.
Referenced by get_sockaddr().
ff_rtsp_next_attr_and_value()
int ff_rtsp_next_attr_and_value (const char ** p, char * attr, int attr_size, char * value, int value_size)
Referenced by ff_parse_fmtp(), and get_sockaddr().
ff_parse_fmtp()
int ff_parse_fmtp (AVFormatContext * s, AVStream * stream, PayloadContext * data, const char * p, int(*)(AVFormatContext *s, AVStream *stream, PayloadContext *data, const char *attr, const char *value) parse_fmtp)
Definition at line 872 of file rtpdec.c.
Referenced by amr_parse_sdp_line(), dv_parse_sdp_line(), hevc_parse_sdp_line(), ilbc_parse_sdp_line(), latm_parse_sdp_line(), parse_h264_sdp_line(), parse_sdp_line(), and xiph_parse_sdp_line().
ff_register_rtp_dynamic_payload_handlers()
void ff_register_rtp_dynamic_payload_handlers (void)
Definition at line 80 of file rtpdec.c.
Referenced by av_register_all().
ff_rtp_finalize_packet()
int ff_rtp_finalize_packet (AVPacket * pkt, AVIOContext ** dyn_buf, int stream_idx)
Close the dynamic buffer and make a packet from it.
Definition at line 910 of file rtpdec.c.
Referenced by ac3_handle_packet(), dv_handle_packet(), h261_handle_packet(), h263_handle_packet(), jpeg_parse_packet(), mpa_robust_parse_packet(), svq3_parse_packet(), vc2hq_handle_frame_fragment(), vp8_handle_packet(), vp9_handle_packet(), and xiph_handle_packet().