FFmpeg: libavformat/rtpdec.c File Reference
rtpdec.c File Reference
#include "libavutil/mathematics.h"
#include "libavutil/avstring.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/time.h"
#include "avformat.h"
#include "network.h"
#include "srtp.h"
#include "url.h"
#include "rtpdec.h"
#include "rtpdec_formats.h"
Macros
#define MIN_FEEDBACK_INTERVAL 200000 /* 200 ms in us */
#define RTP_SEQ_MOD (1 << 16)
Functions
void ff_register_dynamic_payload_handler (RTPDynamicProtocolHandler *handler)
void ff_register_rtp_dynamic_payload_handlers (void)
RTPDynamicProtocolHandler * ff_rtp_handler_find_by_name (const char *name, enum AVMediaType codec_type)
RTPDynamicProtocolHandler * ff_rtp_handler_find_by_id (int id, enum AVMediaType codec_type)
static int rtcp_parse_packet (RTPDemuxContext *s, const unsigned char *buf, int len)
static void rtp_init_statistics (RTPStatistics *s, uint16_t base_sequence)
static void rtp_init_sequence (RTPStatistics *s, uint16_t seq)
static int rtp_valid_packet_in_sequence (RTPStatistics *s, uint16_t seq)
static void rtcp_update_jitter (RTPStatistics *s, uint32_t sent_timestamp, uint32_t arrival_timestamp)
int ff_rtp_check_and_send_back_rr (RTPDemuxContext *s, URLContext *fd, AVIOContext *avio, int count)
some rtp servers assume client is dead if they don't hear from them...
void ff_rtp_send_punch_packets (URLContext *rtp_handle)
Send a dummy packet on both port pairs to set up the connection state in potential NAT routers, so that we're able to receive packets.
static int find_missing_packets (RTPDemuxContext *s, uint16_t *first_missing, uint16_t *missing_mask)
int ff_rtp_send_rtcp_feedback (RTPDemuxContext *s, URLContext *fd, AVIOContext *avio)
RTPDemuxContext * ff_rtp_parse_open (AVFormatContext *s1, AVStream *st, int payload_type, int queue_size)
open a new RTP parse context for stream 'st'.
void ff_rtp_parse_set_dynamic_protocol (RTPDemuxContext *s, PayloadContext *ctx, RTPDynamicProtocolHandler *handler)
void ff_rtp_parse_set_crypto (RTPDemuxContext *s, const char *suite, const char *params)
static void finalize_packet (RTPDemuxContext *s, AVPacket *pkt, uint32_t timestamp)
This was the second switch in rtp_parse packet.
static int rtp_parse_packet_internal (RTPDemuxContext *s, AVPacket *pkt, const uint8_t *buf, int len)
void ff_rtp_reset_packet_queue (RTPDemuxContext *s)
static int enqueue_packet (RTPDemuxContext *s, uint8_t *buf, int len)
static int has_next_packet (RTPDemuxContext *s)
int64_t ff_rtp_queued_packet_time (RTPDemuxContext *s)
static int rtp_parse_queued_packet (RTPDemuxContext *s, AVPacket *pkt)
static int rtp_parse_one_packet (RTPDemuxContext *s, AVPacket *pkt, uint8_t **bufptr, int len)
int ff_rtp_parse_packet (RTPDemuxContext *s, AVPacket *pkt, uint8_t **bufptr, int len)
Parse an RTP or RTCP packet directly sent as a buffer.
void ff_rtp_parse_close (RTPDemuxContext *s)
int ff_parse_fmtp (AVFormatContext *s, AVStream *stream, PayloadContext *data, const char *p, int(*parse_fmtp)(AVFormatContext *s, AVStream *stream, PayloadContext *data, const char *attr, const char *value))
int ff_rtp_finalize_packet (AVPacket *pkt, AVIOContext **dyn_buf, int stream_idx)
Close the dynamic buffer and make a packet from it.
Variables
static RTPDynamicProtocolHandler l24_dynamic_handler
static RTPDynamicProtocolHandler gsm_dynamic_handler
static RTPDynamicProtocolHandler realmedia_mp3_dynamic_handler
static RTPDynamicProtocolHandler speex_dynamic_handler
static RTPDynamicProtocolHandler opus_dynamic_handler
static RTPDynamicProtocolHandler t140_dynamic_handler
static RTPDynamicProtocolHandler * rtp_first_dynamic_payload_handler = NULL
Macro Definition Documentation
MIN_FEEDBACK_INTERVAL
#define MIN_FEEDBACK_INTERVAL 200000 /* 200 ms in us */
Definition at line 34 of file rtpdec.c.
Referenced by ff_rtp_send_rtcp_feedback().
RTP_SEQ_MOD
#define RTP_SEQ_MOD (1 << 16)
Definition at line 191 of file rtpdec.c.
Referenced by rtp_init_sequence(), and rtp_valid_packet_in_sequence().
Function Documentation
ff_register_dynamic_payload_handler()
void ff_register_dynamic_payload_handler (RTPDynamicProtocolHandler * handler)
Definition at line 74 of file rtpdec.c.
Referenced by ff_register_rdt_dynamic_payload_handlers(), and ff_register_rtp_dynamic_payload_handlers().
ff_register_rtp_dynamic_payload_handlers()
void ff_register_rtp_dynamic_payload_handlers (void)
Definition at line 80 of file rtpdec.c.
Referenced by av_register_all().
ff_rtp_handler_find_by_name()
RTPDynamicProtocolHandler* ff_rtp_handler_find_by_name (const char * name, enum AVMediaType codec_type)
Definition at line 131 of file rtpdec.c.
Referenced by get_sockaddr().
ff_rtp_handler_find_by_id()
RTPDynamicProtocolHandler* ff_rtp_handler_find_by_id (int id, enum AVMediaType codec_type)
Definition at line 144 of file rtpdec.c.
Referenced by get_sockaddr().
rtcp_parse_packet()
static int rtcp_parse_packet (RTPDemuxContext * s, const unsigned char * buf, int len) static
Definition at line 156 of file rtpdec.c.
Referenced by rtp_parse_one_packet().
rtp_init_statistics()
static void rtp_init_statistics (RTPStatistics * s, uint16_t base_sequence) static
Definition at line 193 of file rtpdec.c.
Referenced by ff_rtp_parse_open().
rtp_init_sequence()
static void rtp_init_sequence (RTPStatistics * s, uint16_t seq) static
Definition at line 204 of file rtpdec.c.
Referenced by rtp_valid_packet_in_sequence().
rtp_valid_packet_in_sequence()
static int rtp_valid_packet_in_sequence (RTPStatistics * s, uint16_t seq) static
Definition at line 218 of file rtpdec.c.
Referenced by rtp_parse_packet_internal().
rtcp_update_jitter()
static void rtcp_update_jitter (RTPStatistics * s, uint32_t sent_timestamp, uint32_t arrival_timestamp) static
Definition at line 264 of file rtpdec.c.
Referenced by rtp_parse_one_packet().
ff_rtp_check_and_send_back_rr()
int ff_rtp_check_and_send_back_rr (RTPDemuxContext * s, URLContext * fd, AVIOContext * avio, int count)
some rtp servers assume client is dead if they don't hear from them...
so we send a Receiver Report to the provided URLContext or AVIOContext (we don't have access to the rtcp handle from here)
Definition at line 282 of file rtpdec.c.
Referenced by ff_rtsp_open_transport_ctx().
ff_rtp_send_punch_packets()
void ff_rtp_send_punch_packets (URLContext * rtp_handle)
Send a dummy packet on both port pairs to set up the connection state in potential NAT routers, so that we're able to receive packets.
Note, this only works if the NAT router doesn't remap ports. This isn't a standardized procedure, but it works in many cases in practice.
The same routine is used with RDT too, even if RDT doesn't use normal RTP packets otherwise.
Definition at line 385 of file rtpdec.c.
Referenced by rtsp_read_play().
find_missing_packets()
static int find_missing_packets (RTPDemuxContext * s, uint16_t * first_missing, uint16_t * missing_mask) static
Definition at line 423 of file rtpdec.c.
Referenced by ff_rtp_send_rtcp_feedback().
ff_rtp_send_rtcp_feedback()
int ff_rtp_send_rtcp_feedback (RTPDemuxContext * s, URLContext * fd, AVIOContext * avio)
Definition at line 453 of file rtpdec.c.
Referenced by ff_rtsp_open_transport_ctx().
ff_rtp_parse_open()
RTPDemuxContext* ff_rtp_parse_open (AVFormatContext * s1, AVStream * st, int payload_type, int queue_size)
open a new RTP parse context for stream 'st'.
'st' can be NULL for MPEG-2 TS streams.
Definition at line 521 of file rtpdec.c.
Referenced by ff_rtsp_open_transport_ctx().
ff_rtp_parse_set_dynamic_protocol()
void ff_rtp_parse_set_dynamic_protocol (RTPDemuxContext * s, PayloadContext * ctx, RTPDynamicProtocolHandler * handler)
Definition at line 557 of file rtpdec.c.
Referenced by ff_rtsp_open_transport_ctx().
ff_rtp_parse_set_crypto()
void ff_rtp_parse_set_crypto (RTPDemuxContext * s, const char * suite, const char * params)
Definition at line 564 of file rtpdec.c.
Referenced by ff_rtsp_open_transport_ctx().
finalize_packet()
static void finalize_packet (RTPDemuxContext * s, AVPacket * pkt, uint32_t timestamp) static
This was the second switch in rtp_parse packet.
Normalizes time, if required, sets stream_index, etc.
Definition at line 575 of file rtpdec.c.
Referenced by rtp_parse_one_packet(), and rtp_parse_packet_internal().
rtp_parse_packet_internal()
static int rtp_parse_packet_internal (RTPDemuxContext * s, AVPacket * pkt, const uint8_t * buf, int len) static
Definition at line 610 of file rtpdec.c.
Referenced by rtp_parse_one_packet(), and rtp_parse_queued_packet().
ff_rtp_reset_packet_queue()
void ff_rtp_reset_packet_queue (RTPDemuxContext * s)
Definition at line 693 of file rtpdec.c.
Referenced by ff_rtp_parse_close(), and rtsp_read_play().
enqueue_packet()
static int enqueue_packet (RTPDemuxContext * s, uint8_t * buf, int len) static
Definition at line 706 of file rtpdec.c.
Referenced by rtp_parse_one_packet().
has_next_packet()
static int has_next_packet (RTPDemuxContext * s) static
Definition at line 733 of file rtpdec.c.
Referenced by ff_rtp_parse_packet(), and rtp_parse_queued_packet().
ff_rtp_queued_packet_time()
int64_t ff_rtp_queued_packet_time (RTPDemuxContext * s)
Definition at line 738 of file rtpdec.c.
Referenced by ff_rtsp_open_transport_ctx().
rtp_parse_queued_packet()
static int rtp_parse_queued_packet (RTPDemuxContext * s, AVPacket * pkt) static
Definition at line 743 of file rtpdec.c.
Referenced by ff_rtp_parse_packet(), and rtp_parse_one_packet().
rtp_parse_one_packet()
static int rtp_parse_one_packet (RTPDemuxContext * s, AVPacket * pkt, uint8_t ** bufptr, int len) static
Definition at line 765 of file rtpdec.c.
Referenced by ff_rtp_parse_packet().
ff_rtp_parse_packet()
int ff_rtp_parse_packet (RTPDemuxContext * s, AVPacket * pkt, uint8_t ** bufptr, int len)
Parse an RTP or RTCP packet directly sent as a buffer.
Parameters
s RTP parse context.
pkt returned packet
bufptr pointer to the input buffer or NULL to read the next packets
len buffer len
Returns
0 if a packet is returned, 1 if a packet is returned and more can follow (use buf as NULL to read the next). -1 if no packet (error or no more packet).
Definition at line 852 of file rtpdec.c.
Referenced by ff_rtsp_open_transport_ctx().
ff_rtp_parse_close()
void ff_rtp_parse_close (RTPDemuxContext * s)
Definition at line 865 of file rtpdec.c.
Referenced by ff_rtsp_undo_setup().
ff_parse_fmtp()
int ff_parse_fmtp (AVFormatContext * s, AVStream * stream, PayloadContext * data, const char * p, int(*)(AVFormatContext *s, AVStream *stream, PayloadContext *data, const char *attr, const char *value) parse_fmtp)
Definition at line 872 of file rtpdec.c.
Referenced by amr_parse_sdp_line(), dv_parse_sdp_line(), hevc_parse_sdp_line(), ilbc_parse_sdp_line(), latm_parse_sdp_line(), parse_h264_sdp_line(), parse_sdp_line(), and xiph_parse_sdp_line().
ff_rtp_finalize_packet()
int ff_rtp_finalize_packet (AVPacket * pkt, AVIOContext ** dyn_buf, int stream_idx)
Close the dynamic buffer and make a packet from it.
Definition at line 910 of file rtpdec.c.
Referenced by ac3_handle_packet(), dv_handle_packet(), h261_handle_packet(), h263_handle_packet(), jpeg_parse_packet(), mpa_robust_parse_packet(), svq3_parse_packet(), vc2hq_handle_frame_fragment(), vp8_handle_packet(), vp9_handle_packet(), and xiph_handle_packet().
Variable Documentation
l24_dynamic_handler
RTPDynamicProtocolHandler l24_dynamic_handler static
Initial value:
= {
    .enc_name   = "L24",
    .codec_type = AVMEDIA_TYPE_AUDIO,
    .codec_id   = AV_CODEC_ID_PCM_S24BE,
}
Definition at line 36 of file rtpdec.c.
gsm_dynamic_handler
RTPDynamicProtocolHandler gsm_dynamic_handler static
Initial value:
= {
    .enc_name   = "GSM",
    .codec_type = AVMEDIA_TYPE_AUDIO,
    .codec_id   = AV_CODEC_ID_GSM,
}
Definition at line 42 of file rtpdec.c.
realmedia_mp3_dynamic_handler
RTPDynamicProtocolHandler realmedia_mp3_dynamic_handler static
Initial value:
= {
    .enc_name   = "X-MP3-draft-00",
    .codec_type = AVMEDIA_TYPE_AUDIO,
    .codec_id   = AV_CODEC_ID_MP3ADU,
}
Definition at line 48 of file rtpdec.c.
speex_dynamic_handler
RTPDynamicProtocolHandler speex_dynamic_handler static
Initial value:
= {
    .enc_name   = "speex",
    .codec_type = AVMEDIA_TYPE_AUDIO,
    .codec_id   = AV_CODEC_ID_SPEEX,
}
Definition at line 54 of file rtpdec.c.
opus_dynamic_handler
RTPDynamicProtocolHandler opus_dynamic_handler static
Initial value:
= {
    .enc_name   = "opus",
    .codec_type = AVMEDIA_TYPE_AUDIO,
    .codec_id   = AV_CODEC_ID_OPUS,
}
Definition at line 60 of file rtpdec.c.
t140_dynamic_handler
RTPDynamicProtocolHandler t140_dynamic_handler static
Initial value:
= {
    .enc_name   = "t140",
    .codec_type = AVMEDIA_TYPE_SUBTITLE,
    .codec_id   = AV_CODEC_ID_TEXT,
}
Definition at line 66 of file rtpdec.c.
rtp_first_dynamic_payload_handler
RTPDynamicProtocolHandler* rtp_first_dynamic_payload_handler = NULL static
Definition at line 72 of file rtpdec.c.
Referenced by ff_register_dynamic_payload_handler().