FFmpeg: libavformat/rtpenc_h264_hevc.c File Reference
rtpenc_h264_hevc.c File Reference
H.264/HEVC packetization.
#include "libavutil/intreadwrite.h"
#include "avformat.h"
#include "avc.h"
#include "rtpenc.h"
Functions
static void flush_buffered (AVFormatContext *s1, int last)
static void nal_send (AVFormatContext *s1, const uint8_t *buf, int size, int last)
void ff_rtp_send_h264_hevc (AVFormatContext *s1, const uint8_t *buf1, int size)
Detailed Description
H.264/HEVC packetization.
Author
Luca Abeni lucab.nosp@m.e72@.nosp@m.email.nosp@m..it
Definition in file rtpenc_h264_hevc.c.
Function Documentation
flush_buffered()
static void flush_buffered (AVFormatContext * s1, int last) static
Definition at line 36 of file rtpenc_h264_hevc.c.
Referenced by ff_rtp_send_h264_hevc(), and nal_send().
nal_send()
static void nal_send (AVFormatContext * s1, const uint8_t * buf, int size, int last) static
Definition at line 55 of file rtpenc_h264_hevc.c.
Referenced by ff_rtp_send_h264_hevc().
ff_rtp_send_h264_hevc()
void ff_rtp_send_h264_hevc (AVFormatContext * s1, const uint8_t * buf1, int size)
Definition at line 180 of file rtpenc_h264_hevc.c.
Referenced by rtp_write_packet().