FFmpeg: libavformat/rtpenc_vc2hq.c File Reference
rtpenc_vc2hq.c File Reference
#include "libavutil/intreadwrite.h"
#include "libavcodec/dirac.h"
#include "libavcodec/get_bits.h"
#include "libavcodec/golomb.h"
#include "avformat.h"
#include "rtpenc.h"
Macros
#define RTP_VC2HQ_PL_HEADER_SIZE 4
#define DIRAC_DATA_UNIT_HEADER_SIZE 13
#define DIRAC_PIC_NR_SIZE 4
#define DIRAC_RTP_PCODE_HQ_PIC_FRAGMENT 0xEC
Functions
static void send_packet (AVFormatContext *ctx, uint8_t parse_code, int info_hdr_size, const uint8_t *buf, int size, int i, int f, int rtp_m)
static void send_picture (AVFormatContext *ctx, const uint8_t *buf, int size, int interlaced)
void ff_rtp_send_vc2hq (AVFormatContext *ctx, const uint8_t *frame_buf, int frame_size, int interlaced)
Macro Definition Documentation
RTP_VC2HQ_PL_HEADER_SIZE
#define RTP_VC2HQ_PL_HEADER_SIZE 4
Definition at line 30 of file rtpenc_vc2hq.c.
Referenced by send_packet().
DIRAC_DATA_UNIT_HEADER_SIZE
#define DIRAC_DATA_UNIT_HEADER_SIZE 13
Definition at line 32 of file rtpenc_vc2hq.c.
Referenced by ff_rtp_send_vc2hq().
DIRAC_PIC_NR_SIZE
#define DIRAC_PIC_NR_SIZE 4
Definition at line 33 of file rtpenc_vc2hq.c.
Referenced by send_picture().
DIRAC_RTP_PCODE_HQ_PIC_FRAGMENT
#define DIRAC_RTP_PCODE_HQ_PIC_FRAGMENT 0xEC
Definition at line 34 of file rtpenc_vc2hq.c.
Referenced by send_picture().
Function Documentation
send_packet()
static void send_packet (AVFormatContext * ctx, uint8_t parse_code, int info_hdr_size, const uint8_t * buf, int size, int i, int f, int rtp_m) static
Definition at line 36 of file rtpenc_vc2hq.c.
Referenced by ff_rtp_send_vc2hq(), and send_picture().
send_picture()
static void send_picture (AVFormatContext * ctx, const uint8_t * buf, int size, int interlaced) static
Definition at line 48 of file rtpenc_vc2hq.c.
Referenced by ff_rtp_send_vc2hq().
ff_rtp_send_vc2hq()
void ff_rtp_send_vc2hq (AVFormatContext * ctx, const uint8_t * frame_buf, int frame_size, int interlaced)
Definition at line 102 of file rtpenc_vc2hq.c.
Referenced by rtp_write_packet().