FFmpeg: libavformat/rtpenc.c File Reference
rtpenc.c File Reference
#include "avformat.h"
#include "mpegts.h"
#include "internal.h"
#include "libavutil/mathematics.h"
#include "libavutil/random_seed.h"
#include "libavutil/opt.h"
#include "rtpenc.h"
Macros
#define RTCP_SR_SIZE 28
Functions
static int is_supported (enum AVCodecID id)
static int rtp_write_header (AVFormatContext *s1)
static void rtcp_send_sr (AVFormatContext *s1, int64_t ntp_time, int bye)
void ff_rtp_send_data (AVFormatContext *s1, const uint8_t *buf1, int len, int m)
static int rtp_send_samples (AVFormatContext *s1, const uint8_t *buf1, int size, int sample_size_bits)
static void rtp_send_mpegaudio (AVFormatContext *s1, const uint8_t *buf1, int size)
static void rtp_send_raw (AVFormatContext *s1, const uint8_t *buf1, int size)
static void rtp_send_mpegts_raw (AVFormatContext *s1, const uint8_t *buf1, int size)
static int rtp_send_ilbc (AVFormatContext *s1, const uint8_t *buf, int size)
static int rtp_write_packet (AVFormatContext *s1, AVPacket *pkt)
static int rtp_write_trailer (AVFormatContext *s1)
Variables
static const AVOption options []
static const AVClass rtp_muxer_class
AVOutputFormat ff_rtp_muxer
Macro Definition Documentation
RTCP_SR_SIZE
#define RTCP_SR_SIZE 28
Definition at line 47 of file rtpenc.c.
Referenced by rtp_write_packet().
Function Documentation
is_supported()
static int is_supported (enum AVCodecID id) static
Definition at line 49 of file rtpenc.c.
Referenced by rtp_write_header().
rtp_write_header()
static int rtp_write_header (AVFormatContext * s1) static
Definition at line 91 of file rtpenc.c.
rtcp_send_sr()
static void rtcp_send_sr (AVFormatContext * s1, int64_t ntp_time, int bye) static
Definition at line 283 of file rtpenc.c.
Referenced by rtp_write_packet(), and rtp_write_trailer().
ff_rtp_send_data()
void ff_rtp_send_data (AVFormatContext * s1, const uint8_t * buf1, int len, int m)
Definition at line 330 of file rtpenc.c.
Referenced by ff_rtp_send_aac(), ff_rtp_send_amr(), ff_rtp_send_h261(), ff_rtp_send_h263(), ff_rtp_send_jpeg(), ff_rtp_send_latm(), ff_rtp_send_mpegvideo(), ff_rtp_send_vp8(), ff_rtp_send_vp9(), ff_rtp_send_xiph(), flush_buffered(), nal_send(), rtp_send_ilbc(), rtp_send_mpegaudio(), rtp_send_mpegts_raw(), rtp_send_raw(), rtp_send_samples(), send_mode_a(), send_mode_b(), and send_packet().
rtp_send_samples()
static int rtp_send_samples (AVFormatContext * s1, const uint8_t * buf1, int size, int sample_size_bits) static
Definition at line 353 of file rtpenc.c.
Referenced by rtp_write_packet().
rtp_send_mpegaudio()
static void rtp_send_mpegaudio (AVFormatContext * s1, const uint8_t * buf1, int size) static
Definition at line 382 of file rtpenc.c.
Referenced by rtp_write_packet().
rtp_send_raw()
static void rtp_send_raw (AVFormatContext * s1, const uint8_t * buf1, int size) static
Definition at line 434 of file rtpenc.c.
Referenced by rtp_write_packet().
rtp_send_mpegts_raw()
static void rtp_send_mpegts_raw (AVFormatContext * s1, const uint8_t * buf1, int size) static
Definition at line 456 of file rtpenc.c.
Referenced by rtp_write_packet().
rtp_send_ilbc()
static int rtp_send_ilbc (AVFormatContext * s1, const uint8_t * buf, int size) static
Definition at line 480 of file rtpenc.c.
Referenced by rtp_write_packet().
rtp_write_packet()
static int rtp_write_packet (AVFormatContext * s1, AVPacket * pkt) static
Definition at line 515 of file rtpenc.c.
rtp_write_trailer()
static int rtp_write_trailer (AVFormatContext * s1) static
Definition at line 633 of file rtpenc.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    FF_RTP_FLAG_OPTS(RTPMuxContext, flags),
    { "payload_type", "Specify RTP payload type", 0x42, AV_OPT_TYPE_INT, {.i64 = -1 }, -1, 127, AV_OPT_FLAG_ENCODING_PARAM },
    { "ssrc", "Stream identifier", 0x42, AV_OPT_TYPE_INT, { .i64 = 0 }, INT_MIN, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM },
    { "cname", "CNAME to include in RTCP SR packets", 0x42, AV_OPT_TYPE_STRING, { .str = NULL }, 0, 0, AV_OPT_FLAG_ENCODING_PARAM },
    { "seq", "Starting sequence number", 0x42, AV_OPT_TYPE_INT, { .i64 = -1 }, -1, 65535, AV_OPT_FLAG_ENCODING_PARAM },
    { NULL },
}
Definition at line 31 of file rtpenc.c.
rtp_muxer_class
const AVClass rtp_muxer_class static
Initial value:
= {
    .class_name = "RTP muxer",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 40 of file rtpenc.c.
ff_rtp_muxer
AVOutputFormat ff_rtp_muxer
Initial value:
= {
    .name              = "rtp",
    .long_name         = NULL_IF_CONFIG_SMALL("RTP output"),
    .priv_data_size    = sizeof(RTPMuxContext),
    .audio_codec       = AV_CODEC_ID_PCM_MULAW,
    .video_codec       = AV_CODEC_ID_MPEG4,
    .write_header      = rtp_write_header,
    .write_packet      = rtp_write_packet,
    .write_trailer     = rtp_write_trailer,
    .priv_class        = &rtp_muxer_class,
    .flags             = AVFMT_TS_NONSTRICT,
}
Definition at line 646 of file rtpenc.c.