FFmpeg: libavformat/rtpenc_h263_rfc2190.c File Reference
rtpenc_h263_rfc2190.c File Reference
#include "avformat.h"
#include "rtpenc.h"
#include "libavcodec/put_bits.h"
#include "libavcodec/get_bits.h"
Data Structures
struct H263Info
struct H263State
Functions
static void send_mode_a (AVFormatContext *s1, const struct H263Info *info, const uint8_t *buf, int len, int ebits, int m)
static void send_mode_b (AVFormatContext *s1, const struct H263Info *info, const struct H263State *state, const uint8_t *buf, int len, int sbits, int ebits, int m)
void ff_rtp_send_h263_rfc2190 (AVFormatContext *s1, const uint8_t *buf, int size, const uint8_t *mb_info, int mb_info_size)
Function Documentation
send_mode_a()
static void send_mode_a (AVFormatContext * s1, const struct H263Info * info, const uint8_t * buf, int len, int ebits, int m) static
Definition at line 44 of file rtpenc_h263_rfc2190.c.
Referenced by ff_rtp_send_h263_rfc2190().
send_mode_b()
static void send_mode_b (AVFormatContext * s1, const struct H263Info * info, const struct H263State * state, const uint8_t * buf, int len, int sbits, int ebits, int m) static
Definition at line 70 of file rtpenc_h263_rfc2190.c.
Referenced by ff_rtp_send_h263_rfc2190().
ff_rtp_send_h263_rfc2190()
void ff_rtp_send_h263_rfc2190 (AVFormatContext * s1, const uint8_t * buf, int size, const uint8_t * mb_info, int mb_info_size)
Definition at line 101 of file rtpenc_h263_rfc2190.c.
Referenced by rtp_write_packet().