FFmpeg: libavformat/rtpenc_chain.c File Reference
rtpenc_chain.c File Reference
#include "avformat.h"
#include "avio_internal.h"
#include "rtpenc_chain.h"
#include "rtp.h"
#include "libavutil/opt.h"
Functions
int ff_rtp_chain_mux_open (AVFormatContext **out, AVFormatContext *s, AVStream *st, URLContext *handle, int packet_size, int idx)
Function Documentation
ff_rtp_chain_mux_open()
int ff_rtp_chain_mux_open (AVFormatContext ** out, AVFormatContext * s, AVStream * st, URLContext * handle, int packet_size, int idx)
Definition at line 28 of file rtpenc_chain.c.
Referenced by ff_mov_init_hinting(), ff_rtsp_open_transport_ctx(), and sap_write_header().