FFmpeg: libavformat/rtpenc.h File Reference
rtpenc.h File Reference
#include "avformat.h"
#include "rtp.h"
Data Structures
struct RTPMuxContext
Macros
#define FF_RTP_FLAG_MP4A_LATM 1
#define FF_RTP_FLAG_RFC2190 2
#define FF_RTP_FLAG_SKIP_RTCP 4
#define FF_RTP_FLAG_H264_MODE0 8
#define FF_RTP_FLAG_SEND_BYE 16
#define FF_RTP_FLAG_OPTS(ctx, fieldname)
Functions
void ff_rtp_send_data (AVFormatContext *s1, const uint8_t *buf1, int len, int m)
void ff_rtp_send_h264_hevc (AVFormatContext *s1, const uint8_t *buf1, int size)
void ff_rtp_send_h261 (AVFormatContext *s1, const uint8_t *buf1, int size)
void ff_rtp_send_h263 (AVFormatContext *s1, const uint8_t *buf1, int size)
Packetize H.263 frames into RTP packets according to RFC 4629.
void ff_rtp_send_h263_rfc2190 (AVFormatContext *s1, const uint8_t *buf1, int size, const uint8_t *mb_info, int mb_info_size)
void ff_rtp_send_aac (AVFormatContext *s1, const uint8_t *buff, int size)
void ff_rtp_send_latm (AVFormatContext *s1, const uint8_t *buff, int size)
void ff_rtp_send_amr (AVFormatContext *s1, const uint8_t *buff, int size)
Packetize AMR frames into RTP packets according to RFC 3267, in octet-aligned mode.
void ff_rtp_send_mpegvideo (AVFormatContext *s1, const uint8_t *buf1, int size)
void ff_rtp_send_xiph (AVFormatContext *s1, const uint8_t *buff, int size)
Packetize Xiph frames into RTP according to RFC 5215 (Vorbis) and the Theora RFC draft.
void ff_rtp_send_vc2hq (AVFormatContext *s1, const uint8_t *buf, int size, int interlaced)
void ff_rtp_send_vp8 (AVFormatContext *s1, const uint8_t *buff, int size)
void ff_rtp_send_vp9 (AVFormatContext *s1, const uint8_t *buff, int size)
void ff_rtp_send_jpeg (AVFormatContext *s1, const uint8_t *buff, int size)
const uint8_t * ff_h263_find_resync_marker_reverse (const uint8_t *av_restrict start, const uint8_t *av_restrict end)
Macro Definition Documentation
FF_RTP_FLAG_MP4A_LATM
#define FF_RTP_FLAG_MP4A_LATM 1
Definition at line 68 of file rtpenc.h.
Referenced by rtp_write_packet().
FF_RTP_FLAG_RFC2190
#define FF_RTP_FLAG_RFC2190 2
Definition at line 69 of file rtpenc.h.
Referenced by rtp_write_packet().
FF_RTP_FLAG_SKIP_RTCP
#define FF_RTP_FLAG_SKIP_RTCP 4
Definition at line 70 of file rtpenc.h.
Referenced by rtp_write_packet().
FF_RTP_FLAG_H264_MODE0
#define FF_RTP_FLAG_H264_MODE0 8
Definition at line 71 of file rtpenc.h.
Referenced by nal_send().
FF_RTP_FLAG_SEND_BYE
#define FF_RTP_FLAG_SEND_BYE 16
Definition at line 72 of file rtpenc.h.
Referenced by rtp_write_trailer().
FF_RTP_FLAG_OPTS
#define FF_RTP_FLAG_OPTS (ctx, fieldname)
Value:
{ "rtpflags", "RTP muxer flags", offsetof(ctx, fieldname), AV_OPT_TYPE_FLAGS, {.i64 = 0}, INT_MIN, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM, "rtpflags" }, \
    { "latm", "Use MP4A-LATM packetization instead of MPEG4-GENERIC for AAC", 0, AV_OPT_TYPE_CONST, {.i64 = FF_RTP_FLAG_MP4A_LATM}, INT_MIN, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM, "rtpflags" }, \
    { "rfc2190", "Use RFC 2190 packetization instead of RFC 4629 for H.263", 0, AV_OPT_TYPE_CONST, {.i64 = FF_RTP_FLAG_RFC2190}, INT_MIN, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM, "rtpflags" }, \
    { "skip_rtcp", "Don't send RTCP sender reports", 0, AV_OPT_TYPE_CONST, {.i64 = FF_RTP_FLAG_SKIP_RTCP}, INT_MIN, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM, "rtpflags" }, \
    { "h264_mode0", "Use mode 0 for H.264 in RTP", 0, AV_OPT_TYPE_CONST, {.i64 = FF_RTP_FLAG_H264_MODE0}, INT_MIN, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM, "rtpflags" }, \
    { "send_bye", "Send RTCP BYE packets when finishing", 0, AV_OPT_TYPE_CONST, {.i64 = FF_RTP_FLAG_SEND_BYE}, INT_MIN, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM, "rtpflags" } \
Definition at line 74 of file rtpenc.h.
Function Documentation
ff_rtp_send_data()
void ff_rtp_send_data (AVFormatContext * s1, const uint8_t * buf1, int len, int m)
Definition at line 330 of file rtpenc.c.
Referenced by ff_rtp_send_aac(), ff_rtp_send_amr(), ff_rtp_send_h261(), ff_rtp_send_h263(), ff_rtp_send_jpeg(), ff_rtp_send_latm(), ff_rtp_send_mpegvideo(), ff_rtp_send_vp8(), ff_rtp_send_vp9(), ff_rtp_send_xiph(), flush_buffered(), nal_send(), rtp_send_ilbc(), rtp_send_mpegaudio(), rtp_send_mpegts_raw(), rtp_send_raw(), rtp_send_samples(), send_mode_a(), send_mode_b(), and send_packet().
ff_rtp_send_h264_hevc()
void ff_rtp_send_h264_hevc (AVFormatContext * s1, const uint8_t * buf1, int size)
Definition at line 180 of file rtpenc_h264_hevc.c.
Referenced by rtp_write_packet().
ff_rtp_send_h261()
void ff_rtp_send_h261 (AVFormatContext * s1, const uint8_t * buf1, int size)
Definition at line 39 of file rtpenc_h261.c.
Referenced by rtp_write_packet().
ff_rtp_send_h263()
void ff_rtp_send_h263 (AVFormatContext * s1, const uint8_t * buf1, int size)
Packetize H.263 frames into RTP packets according to RFC 4629.
Definition at line 43 of file rtpenc_h263.c.
Referenced by rtp_write_packet().
ff_rtp_send_h263_rfc2190()
void ff_rtp_send_h263_rfc2190 (AVFormatContext * s1, const uint8_t * buf1, int size, const uint8_t * mb_info, int mb_info_size)
Definition at line 101 of file rtpenc_h263_rfc2190.c.
Referenced by rtp_write_packet().
ff_rtp_send_aac()
void ff_rtp_send_aac (AVFormatContext * s1, const uint8_t * buff, int size)
Definition at line 27 of file rtpenc_aac.c.
Referenced by rtp_write_packet().
ff_rtp_send_latm()
void ff_rtp_send_latm (AVFormatContext * s1, const uint8_t * buff, int size)
Definition at line 25 of file rtpenc_latm.c.
Referenced by rtp_write_packet().
ff_rtp_send_amr()
void ff_rtp_send_amr (AVFormatContext * s1, const uint8_t * buff, int size)
Packetize AMR frames into RTP packets according to RFC 3267, in octet-aligned mode.
Definition at line 30 of file rtpenc_amr.c.
Referenced by rtp_write_packet().
ff_rtp_send_mpegvideo()
void ff_rtp_send_mpegvideo (AVFormatContext * s1, const uint8_t * buf1, int size)
Definition at line 29 of file rtpenc_mpv.c.
Referenced by rtp_write_packet().
ff_rtp_send_xiph()
void ff_rtp_send_xiph (AVFormatContext * s1, const uint8_t * buff, int size)
Packetize Xiph frames into RTP according to RFC 5215 (Vorbis) and the Theora RFC draft.
(http://svn.xiph.org/trunk/theora/doc/draft-ietf-avt-rtp-theora-00.txt)
Definition at line 33 of file rtpenc_xiph.c.
Referenced by rtp_write_packet().
ff_rtp_send_vc2hq()
void ff_rtp_send_vc2hq (AVFormatContext * s1, const uint8_t * buf, int size, int interlaced)
Definition at line 102 of file rtpenc_vc2hq.c.
Referenced by rtp_write_packet().
ff_rtp_send_vp8()
void ff_rtp_send_vp8 (AVFormatContext * s1, const uint8_t * buff, int size)
Definition at line 26 of file rtpenc_vp8.c.
Referenced by rtp_write_packet().
ff_rtp_send_vp9()
void ff_rtp_send_vp9 (AVFormatContext * s1, const uint8_t * buff, int size)
Definition at line 26 of file rtpenc_vp9.c.
Referenced by rtp_write_packet().
ff_rtp_send_jpeg()
void ff_rtp_send_jpeg (AVFormatContext * s1, const uint8_t * buff, int size)
Definition at line 28 of file rtpenc_jpeg.c.
Referenced by rtp_write_packet().
ff_h263_find_resync_marker_reverse()
const uint8_t* ff_h263_find_resync_marker_reverse (const uint8_t *av_restrict start, const uint8_t *av_restrict end)
Definition at line 26 of file rtpenc_h263.c.
Referenced by ff_rtp_send_h263(), and ff_rtp_send_h263_rfc2190().