FFmpeg: libavformat/rtpproto.c File Reference
rtpproto.c File Reference
RTP protocol.
#include "libavutil/parseutils.h"
#include "libavutil/avstring.h"
#include "libavutil/opt.h"
#include "avformat.h"
#include "avio_internal.h"
#include "rtp.h"
#include "rtpproto.h"
#include "url.h"
#include <stdarg.h>
#include "internal.h"
#include "network.h"
#include "os_support.h"
#include <fcntl.h>
Data Structures
struct RTPContext
Macros
#define OFFSET(x) offsetof(RTPContext, x)
#define D AV_OPT_FLAG_DECODING_PARAM
#define E AV_OPT_FLAG_ENCODING_PARAM
Functions
int ff_rtp_set_remote_url (URLContext *h, const char *uri)
If no filename is given to av_open_input_file because you want to get the local port first, then you must call this function to set the remote server address.
static struct addrinfo * rtp_resolve_host (const char *hostname, int port, int type, int family, int flags)
static int compare_addr (const struct sockaddr_storage *a, const struct sockaddr_storage *b)
static int get_port (const struct sockaddr_storage *ss)
static void set_port (struct sockaddr_storage *ss, int port)
static int rtp_check_source_lists (RTPContext *s, struct sockaddr_storage *source_addr_ptr)
static av_printf_format (3, 4)
add option to url of the form: "http://host:port/path?option1=val1&option2=val2...
static void build_udp_url (RTPContext *s, char *buf, int buf_size, const char *hostname, int port, int local_port, const char *include_sources, const char *exclude_sources)
static void rtp_parse_addr_list (URLContext *h, char *buf, struct sockaddr_storage ***address_list_ptr, int *address_list_size_ptr)
static int rtp_open (URLContext *h, const char *uri, int flags)
url syntax: rtp://host:port[?option=val...] option: 'ttl=n' : set the ttl value (for multicast only) 'rtcpport=n' : set the remote rtcp port to n 'localrtpport=n' : set the local rtp port to n 'localrtcpport=n' : set the local rtcp port to n 'pkt_size=n' : set max packet size 'connect=0/1' : do a connect() on the UDP socket 'sources=ip[,ip]' : list allowed source IP addresses 'block=ip[,ip]' : list disallowed source IP addresses 'write_to_source=0/1' : send packets to the source address of the latest received packet 'dscp=n' : set DSCP value to n (QoS) deprecated option: 'localport=n' : set the local port to n
static int rtp_read (URLContext *h, uint8_t *buf, int size)
static int rtp_write (URLContext *h, const uint8_t *buf, int size)
static int rtp_close (URLContext *h)
int ff_rtp_get_local_rtp_port (URLContext *h)
Return the local rtp port used by the RTP connection.
int ff_rtp_get_local_rtcp_port (URLContext *h)
Return the local rtcp port used by the RTP connection.
static int rtp_get_file_handle (URLContext *h)
static int rtp_get_multi_file_handle (URLContext *h, int **handles, int *numhandles)
Variables
static const AVOption options []
static const AVClass rtp_class
const URLProtocol ff_rtp_protocol
Detailed Description
RTP protocol.
Definition in file rtpproto.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(RTPContext, x)
Definition at line 64 of file rtpproto.c.
D
#define D AV_OPT_FLAG_DECODING_PARAM
Definition at line 65 of file rtpproto.c.
E
#define E AV_OPT_FLAG_ENCODING_PARAM
Definition at line 66 of file rtpproto.c.
Function Documentation
ff_rtp_set_remote_url()
int ff_rtp_set_remote_url (URLContext * h, const char * uri)
If no filename is given to av_open_input_file because you want to get the local port first, then you must call this function to set the remote server address.
Parameters
h media file context
uri of the remote server
Returns
zero if no error.
Definition at line 100 of file rtpproto.c.
Referenced by ff_rtsp_open_transport_ctx().
rtp_resolve_host()
static struct addrinfo* rtp_resolve_host (const char * hostname, int port, int type, int family, int flags) static
Definition at line 129 of file rtpproto.c.
Referenced by rtp_parse_addr_list().
compare_addr()
static int compare_addr (const struct sockaddr_storage * a, const struct sockaddr_storage * b) static
Definition at line 148 of file rtpproto.c.
Referenced by rtp_check_source_lists().
get_port()
static int get_port (const struct sockaddr_storage * ss) static
Definition at line 168 of file rtpproto.c.
Referenced by rtp_write().
set_port()
static void set_port (struct sockaddr_storage * ss, int port) static
Definition at line 179 of file rtpproto.c.
Referenced by rtp_write().
rtp_check_source_lists()
static int rtp_check_source_lists (RTPContext * s, struct sockaddr_storage * source_addr_ptr) static
Definition at line 189 of file rtpproto.c.
Referenced by rtp_read().
av_printf_format()
static av_printf_format (3 , 4) static
add option to url of the form: "http://host:port/path?option1=val1&option2=val2...
Definition at line 213 of file rtpproto.c.
build_udp_url()
static void build_udp_url (RTPContext * s, char * buf, int buf_size, const char * hostname, int port, int local_port, const char * include_sources, const char * exclude_sources) static
Definition at line 228 of file rtpproto.c.
Referenced by rtp_open().
rtp_parse_addr_list()
static void rtp_parse_addr_list (URLContext * h, char * buf, struct sockaddr_storage *** address_list_ptr, int * address_list_size_ptr) static
Definition at line 255 of file rtpproto.c.
Referenced by rtp_open().
rtp_open()
static int rtp_open (URLContext * h, const char * uri, int flags) static
url syntax: rtp://host:port[?option=val...] option: 'ttl=n' : set the ttl value (for multicast only) 'rtcpport=n' : set the remote rtcp port to n 'localrtpport=n' : set the local rtp port to n 'localrtcpport=n' : set the local rtcp port to n 'pkt_size=n' : set max packet size 'connect=0/1' : do a connect() on the UDP socket 'sources=ip[,ip]' : list allowed source IP addresses 'block=ip[,ip]' : list disallowed source IP addresses 'write_to_source=0/1' : send packets to the source address of the latest received packet 'dscp=n' : set DSCP value to n (QoS) deprecated option: 'localport=n' : set the local port to n
if rtcpport isn't set the rtcp port will be the rtp port + 1 if local rtp port isn't set any available port will be used for the local rtp and rtcp ports if the local rtcp port is not set it will be the local rtp port + 1
Definition at line 318 of file rtpproto.c.
rtp_read()
static int rtp_read (URLContext * h, uint8_t * buf, int size) static
Definition at line 476 of file rtpproto.c.
rtp_write()
static int rtp_write (URLContext * h, const uint8_t * buf, int size) static
Definition at line 518 of file rtpproto.c.
rtp_close()
static int rtp_close (URLContext * h) static
Definition at line 604 of file rtpproto.c.
ff_rtp_get_local_rtp_port()
int ff_rtp_get_local_rtp_port (URLContext * h)
Return the local rtp port used by the RTP connection.
Parameters
h media file context
Returns
the local port number
Definition at line 628 of file rtpproto.c.
Referenced by ff_rtsp_open_transport_ctx(), rtsp_cmd_setup(), and rtsp_read_setup().
ff_rtp_get_local_rtcp_port()
int ff_rtp_get_local_rtcp_port (URLContext * h)
Return the local rtcp port used by the RTP connection.
Parameters
h media file context
Returns
the local port number
Definition at line 640 of file rtpproto.c.
Referenced by rtsp_cmd_setup().
rtp_get_file_handle()
static int rtp_get_file_handle (URLContext * h) static
Definition at line 646 of file rtpproto.c.
rtp_get_multi_file_handle()
static int rtp_get_multi_file_handle (URLContext * h, int ** handles, int * numhandles) static
Definition at line 652 of file rtpproto.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "ttl",                "Time to live (in milliseconds, multicast only)",                   OFFSET(ttl),             AV_OPT_TYPE_INT,    { .i64 = -1 },    -1, INT_MAX, .flags = D|E },
    { "buffer_size",        "Send/Receive buffer size (in bytes)",                              OFFSET(buffer_size),     AV_OPT_TYPE_INT,    { .i64 = -1 },    -1, INT_MAX, .flags = D|E },
    { "rtcp_port",          "Custom rtcp port",                                                 OFFSET(rtcp_port),       AV_OPT_TYPE_INT,    { .i64 = -1 },    -1, INT_MAX, .flags = D|E },
    { "local_rtpport",      "Local rtp port",                                                   OFFSET(local_rtpport),   AV_OPT_TYPE_INT,    { .i64 = -1 },    -1, INT_MAX, .flags = D|E },
    { "local_rtcpport",     "Local rtcp port",                                                  OFFSET(local_rtcpport),  AV_OPT_TYPE_INT,    { .i64 = -1 },    -1, INT_MAX, .flags = D|E },
    { "connect",            "Connect socket",                                                   OFFSET(connect),         AV_OPT_TYPE_BOOL,   { .i64 =  0 },     0, 1,       .flags = D|E },
    { "write_to_source",    "Send packets to the source address of the latest received packet", OFFSET(write_to_source), AV_OPT_TYPE_BOOL,   { .i64 =  0 },     0, 1,       .flags = D|E },
    { "pkt_size",           "Maximum packet size",                                              OFFSET(pkt_size),        AV_OPT_TYPE_INT,    { .i64 = -1 },    -1, INT_MAX, .flags = D|E },
    { "dscp",               "DSCP class",                                                       OFFSET(dscp),            AV_OPT_TYPE_INT,    { .i64 = -1 },    -1, INT_MAX, .flags = D|E },
    { "sources",            "Source list",                                                      OFFSET(sources),         AV_OPT_TYPE_STRING, { .str = NULL },               .flags = D|E },
    { "block",              "Block list",                                                       OFFSET(block),           AV_OPT_TYPE_STRING, { .str = NULL },               .flags = D|E },
    { "fec",                "FEC",                                                              OFFSET(fec_options_str), AV_OPT_TYPE_STRING, { .str = NULL },               .flags = E },
    { NULL }
}
Definition at line 67 of file rtpproto.c.
rtp_class
const AVClass rtp_class static
Initial value:
= {
    .class_name = "rtp",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 83 of file rtpproto.c.
ff_rtp_protocol
const URLProtocol ff_rtp_protocol
Initial value:
= {
    .name                      = "rtp",
    .url_open                  = rtp_open,
    .url_read                  = rtp_read,
    .url_write                 = rtp_write,
    .url_close                 = rtp_close,
    .url_get_file_handle       = rtp_get_file_handle,
    .url_get_multi_file_handle = rtp_get_multi_file_handle,
    .priv_data_size            = sizeof(RTPContext),
    .flags                     = URL_PROTOCOL_FLAG_NETWORK,
    .priv_data_class           = &rtp_class,
}
Definition at line 665 of file rtpproto.c.