FFmpeg: libavformat/rtpproto.h File Reference
rtpproto.h File Reference
#include "url.h"
Functions
int ff_rtp_set_remote_url (URLContext *h, const char *uri)
If no filename is given to av_open_input_file because you want to get the local port first, then you must call this function to set the remote server address.
int ff_rtp_get_local_rtp_port (URLContext *h)
Return the local rtp port used by the RTP connection.
int ff_rtp_get_local_rtcp_port (URLContext *h)
Return the local rtcp port used by the RTP connection.
Function Documentation
ff_rtp_set_remote_url()
int ff_rtp_set_remote_url (URLContext * h, const char * uri)
If no filename is given to av_open_input_file because you want to get the local port first, then you must call this function to set the remote server address.
Parameters
h media file context
uri of the remote server
Returns
zero if no error.
Definition at line 100 of file rtpproto.c.
Referenced by ff_rtsp_open_transport_ctx().
ff_rtp_get_local_rtp_port()
int ff_rtp_get_local_rtp_port (URLContext * h)
Return the local rtp port used by the RTP connection.
Parameters
h media file context
Returns
the local port number
Definition at line 628 of file rtpproto.c.
Referenced by ff_rtsp_open_transport_ctx(), rtsp_cmd_setup(), and rtsp_read_setup().
ff_rtp_get_local_rtcp_port()
int ff_rtp_get_local_rtcp_port (URLContext * h)
Return the local rtcp port used by the RTP connection.
Parameters
h media file context
Returns
the local port number
Definition at line 640 of file rtpproto.c.
Referenced by rtsp_cmd_setup().