FFmpeg: libavformat/rtspcodes.h File Reference
rtspcodes.h File Reference
#include "libavutil/common.h"
#include "libavformat/http.h"
Macros
#define RTSP_STATUS_CODE2STRING(x)
Enumerations
enum RTSPStatusCode {
RTSP_STATUS_CONTINUE =100, RTSP_STATUS_OK =200, RTSP_STATUS_CREATED =201, RTSP_STATUS_LOW_ON_STORAGE_SPACE =250,
RTSP_STATUS_MULTIPLE_CHOICES =300, RTSP_STATUS_MOVED_PERMANENTLY =301, RTSP_STATUS_MOVED_TEMPORARILY =302, RTSP_STATUS_SEE_OTHER =303,
RTSP_STATUS_NOT_MODIFIED =304, RTSP_STATUS_USE_PROXY =305, RTSP_STATUS_BAD_REQUEST =400, RTSP_STATUS_UNAUTHORIZED =401,
RTSP_STATUS_PAYMENT_REQUIRED =402, RTSP_STATUS_FORBIDDEN =403, RTSP_STATUS_NOT_FOUND =404, RTSP_STATUS_METHOD =405,
RTSP_STATUS_NOT_ACCEPTABLE =406, RTSP_STATUS_PROXY_AUTH_REQUIRED =407, RTSP_STATUS_REQ_TIME_OUT =408, RTSP_STATUS_GONE =410,
RTSP_STATUS_LENGTH_REQUIRED =411, RTSP_STATUS_PRECONDITION_FAILED =412, RTSP_STATUS_REQ_ENTITY_2LARGE =413, RTSP_STATUS_REQ_URI_2LARGE =414,
RTSP_STATUS_UNSUPPORTED_MTYPE =415, RTSP_STATUS_PARAM_NOT_UNDERSTOOD =451, RTSP_STATUS_CONFERENCE_NOT_FOUND =452, RTSP_STATUS_BANDWIDTH =453,
RTSP_STATUS_SESSION =454, RTSP_STATUS_STATE =455, RTSP_STATUS_INVALID_HEADER_FIELD =456, RTSP_STATUS_INVALID_RANGE =457,
RTSP_STATUS_RONLY_PARAMETER =458, RTSP_STATUS_AGGREGATE =459, RTSP_STATUS_ONLY_AGGREGATE =460, RTSP_STATUS_TRANSPORT =461,
RTSP_STATUS_UNREACHABLE =462, RTSP_STATUS_INTERNAL =500, RTSP_STATUS_NOT_IMPLEMENTED =501, RTSP_STATUS_BAD_GATEWAY =502,
RTSP_STATUS_SERVICE =503, RTSP_STATUS_GATEWAY_TIME_OUT =504, RTSP_STATUS_VERSION =505, RTSP_STATUS_UNSUPPORTED_OPTION =551
}
RTSP handling.
enum RTSPMethod {
DESCRIBE, ANNOUNCE, OPTIONS, SETUP,
PLAY, PAUSE, TEARDOWN, GET_PARAMETER,
SET_PARAMETER, REDIRECT, RECORD, UNKNOWN = -1
}
Functions
static int ff_rtsp_averror (enum RTSPStatusCode status_code, int default_averror)
Variables
static const av_unused char *const rtsp_status_strings []
Macro Definition Documentation
RTSP_STATUS_CODE2STRING
#define RTSP_STATUS_CODE2STRING (x)
Value:
(\
x >= 100 && x < FF_ARRAY_ELEMS(rtsp_status_strings) && rtsp_status_strings[x] \
)? rtsp_status_strings[x] : NULL
Definition at line 125 of file rtspcodes.h.
Referenced by rtsp_reply_header().
Enumeration Type Documentation
RTSPStatusCode
enum RTSPStatusCode
RTSP handling.
Enumerator
RTSP_STATUS_CONTINUE
RTSP_STATUS_OK
RTSP_STATUS_CREATED
RTSP_STATUS_LOW_ON_STORAGE_SPACE
RTSP_STATUS_MULTIPLE_CHOICES
RTSP_STATUS_MOVED_PERMANENTLY
RTSP_STATUS_MOVED_TEMPORARILY
RTSP_STATUS_SEE_OTHER
RTSP_STATUS_NOT_MODIFIED
RTSP_STATUS_USE_PROXY
RTSP_STATUS_BAD_REQUEST
RTSP_STATUS_UNAUTHORIZED
RTSP_STATUS_PAYMENT_REQUIRED
RTSP_STATUS_FORBIDDEN
RTSP_STATUS_NOT_FOUND
RTSP_STATUS_METHOD
RTSP_STATUS_NOT_ACCEPTABLE
RTSP_STATUS_PROXY_AUTH_REQUIRED
RTSP_STATUS_REQ_TIME_OUT
RTSP_STATUS_GONE
RTSP_STATUS_LENGTH_REQUIRED
RTSP_STATUS_PRECONDITION_FAILED
RTSP_STATUS_REQ_ENTITY_2LARGE
RTSP_STATUS_REQ_URI_2LARGE
RTSP_STATUS_UNSUPPORTED_MTYPE
RTSP_STATUS_PARAM_NOT_UNDERSTOOD
RTSP_STATUS_CONFERENCE_NOT_FOUND
RTSP_STATUS_BANDWIDTH
RTSP_STATUS_SESSION
RTSP_STATUS_STATE
RTSP_STATUS_INVALID_HEADER_FIELD
RTSP_STATUS_INVALID_RANGE
RTSP_STATUS_RONLY_PARAMETER
RTSP_STATUS_AGGREGATE
RTSP_STATUS_ONLY_AGGREGATE
RTSP_STATUS_TRANSPORT
RTSP_STATUS_UNREACHABLE
RTSP_STATUS_INTERNAL
RTSP_STATUS_NOT_IMPLEMENTED
RTSP_STATUS_BAD_GATEWAY
RTSP_STATUS_SERVICE
RTSP_STATUS_GATEWAY_TIME_OUT
RTSP_STATUS_VERSION
RTSP_STATUS_UNSUPPORTED_OPTION
Definition at line 31 of file rtspcodes.h.
RTSPMethod
enum RTSPMethod
Enumerator
DESCRIBE
ANNOUNCE
OPTIONS
SETUP
PLAY
PAUSE
TEARDOWN
GET_PARAMETER
SET_PARAMETER
REDIRECT
RECORD
UNKNOWN
Definition at line 129 of file rtspcodes.h.
Function Documentation
ff_rtsp_averror()
static int ff_rtsp_averror (enum RTSPStatusCode status_code, int default_averror) inline static
Definition at line 144 of file rtspcodes.h.
Referenced by ff_rtsp_open_transport_ctx(), ff_rtsp_setup_input_streams(), ff_rtsp_setup_output_streams(), rtsp_read_packet(), rtsp_read_pause(), rtsp_read_play(), and rtsp_write_record().
Variable Documentation
rtsp_status_strings
const av_unused char* const rtsp_status_strings[] static
Definition at line 78 of file rtspcodes.h.