FFmpeg: libavformat/rtspenc.c File Reference
rtspenc.c File Reference
#include "avformat.h"
#include "network.h"
#include "os_support.h"
#include "rtsp.h"
#include "internal.h"
#include "avio_internal.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/avstring.h"
#include "libavutil/time.h"
#include "url.h"
Macros
#define SDP_MAX_SIZE 16384
Functions
int ff_rtsp_setup_output_streams (AVFormatContext *s, const char *addr)
Announce the stream to the server and set up the RTSPStream child objects for each media stream.
static int rtsp_write_record (AVFormatContext *s)
static int rtsp_write_header (AVFormatContext *s)
int ff_rtsp_tcp_write_packet (AVFormatContext *s, RTSPStream *rtsp_st)
Send buffered packets over TCP.
static int rtsp_write_packet (AVFormatContext *s, AVPacket *pkt)
static int rtsp_write_close (AVFormatContext *s)
Variables
static const AVClass rtsp_muxer_class
AVOutputFormat ff_rtsp_muxer
Macro Definition Documentation
SDP_MAX_SIZE
#define SDP_MAX_SIZE 16384
Definition at line 37 of file rtspenc.c.
Referenced by ff_rtsp_setup_output_streams().
Function Documentation
ff_rtsp_setup_output_streams()
int ff_rtsp_setup_output_streams (AVFormatContext * s, const char * addr)
Announce the stream to the server and set up the RTSPStream child objects for each media stream.
Definition at line 46 of file rtspenc.c.
Referenced by ff_rtsp_open_transport_ctx().
rtsp_write_record()
static int rtsp_write_record (AVFormatContext * s) static
Definition at line 109 of file rtspenc.c.
Referenced by rtsp_write_header().
rtsp_write_header()
static int rtsp_write_header (AVFormatContext * s) static
Definition at line 124 of file rtspenc.c.
ff_rtsp_tcp_write_packet()
int ff_rtsp_tcp_write_packet (AVFormatContext * s, RTSPStream * rtsp_st)
Send buffered packets over TCP.
Definition at line 140 of file rtspenc.c.
Referenced by ff_rtsp_undo_setup(), and rtsp_write_packet().
rtsp_write_packet()
static int rtsp_write_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 179 of file rtspenc.c.
rtsp_write_close()
static int rtsp_write_close (AVFormatContext * s) static
Definition at line 225 of file rtspenc.c.
Variable Documentation
rtsp_muxer_class
const AVClass rtsp_muxer_class static
Initial value:
= {
    .class_name = "RTSP muxer",
    .item_name  = av_default_item_name,
    .option     = ff_rtsp_options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 39 of file rtspenc.c.
ff_rtsp_muxer
AVOutputFormat ff_rtsp_muxer
Initial value:
= {
    .name              = "rtsp",
    .long_name         = NULL_IF_CONFIG_SMALL("RTSP output"),
    .priv_data_size    = sizeof(RTSPState),
    .audio_codec       = AV_CODEC_ID_AAC,
    .video_codec       = AV_CODEC_ID_MPEG4,
    .write_header      = rtsp_write_header,
    .write_packet      = rtsp_write_packet,
    .write_trailer     = rtsp_write_close,
    .flags             = AVFMT_NOFILE | AVFMT_GLOBALHEADER,
    .priv_class        = &rtsp_muxer_class,
}
Definition at line 242 of file rtspenc.c.