FFmpeg: libavformat/rtsp.c File Reference
rtsp.c File Reference
#include "libavutil/avassert.h"
#include "libavutil/base64.h"
#include "libavutil/avstring.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/mathematics.h"
#include "libavutil/parseutils.h"
#include "libavutil/random_seed.h"
#include "libavutil/dict.h"
#include "libavutil/opt.h"
#include "libavutil/time.h"
#include "avformat.h"
#include "avio_internal.h"
#include "internal.h"
#include "network.h"
#include "os_support.h"
#include "http.h"
#include "rtsp.h"
#include "rtpdec.h"
#include "rtpproto.h"
#include "rdt.h"
#include "rtpdec_formats.h"
#include "rtpenc_chain.h"
#include "url.h"
#include "rtpenc.h"
#include "mpegts.h"
Macros
#define POLL_TIMEOUT_MS 100
#define READ_PACKET_TIMEOUT_S 10
#define MAX_TIMEOUTS READ_PACKET_TIMEOUT_S * 1000 / POLL_TIMEOUT_MS
#define SDP_MAX_SIZE 16384
#define RECVBUF_SIZE 10 * RTP_MAX_PACKET_LENGTH
#define DEFAULT_REORDERING_DELAY 100000
#define OFFSET(x) offsetof(RTSPState, x)
#define DEC AV_OPT_FLAG_DECODING_PARAM
#define ENC AV_OPT_FLAG_ENCODING_PARAM
#define RTSP_FLAG_OPTS(name, longname)
#define RTSP_MEDIATYPE_OPTS(name, longname)
#define COMMON_OPTS()
Functions
static AVDictionary * map_to_opts (RTSPState *rt)
static void get_word_until_chars (char *buf, int buf_size, const char *sep, const char **pp)
static void get_word_sep (char *buf, int buf_size, const char *sep, const char **pp)
static void get_word (char *buf, int buf_size, const char **pp)
static void rtsp_parse_range_npt (const char *p, int64_t *start, int64_t *end)
Parse a string p in the form of Range:npt=xx-xx, and determine the start and end time.
static int get_sockaddr (AVFormatContext *s, const char *buf, struct sockaddr_storage *sock)
void ff_rtsp_undo_setup (AVFormatContext *s, int send_packets)
Undo the effect of ff_rtsp_make_setup_request, close the transport_priv and rtp_handle fields.
void ff_rtsp_close_streams (AVFormatContext *s)
Close and free all streams within the RTSP (de)muxer.
int ff_rtsp_open_transport_ctx (AVFormatContext *s, RTSPStream *rtsp_st)
Open RTSP transport context.
Variables
const AVOption ff_rtsp_options []
static const AVOption sdp_options []
static const AVOption rtp_options []
Macro Definition Documentation
POLL_TIMEOUT_MS
#define POLL_TIMEOUT_MS 100
Definition at line 55 of file rtsp.c.
Referenced by ff_rtsp_open_transport_ctx().
READ_PACKET_TIMEOUT_S
#define READ_PACKET_TIMEOUT_S 10
Definition at line 56 of file rtsp.c.
MAX_TIMEOUTS
#define MAX_TIMEOUTS READ_PACKET_TIMEOUT_S * 1000 / POLL_TIMEOUT_MS
Definition at line 57 of file rtsp.c.
Referenced by ff_rtsp_open_transport_ctx().
SDP_MAX_SIZE
#define SDP_MAX_SIZE 16384
Definition at line 58 of file rtsp.c.
Referenced by ff_rtsp_open_transport_ctx().
RECVBUF_SIZE
#define RECVBUF_SIZE 10 * RTP_MAX_PACKET_LENGTH
Definition at line 59 of file rtsp.c.
Referenced by ff_rtsp_open_transport_ctx().
DEFAULT_REORDERING_DELAY
#define DEFAULT_REORDERING_DELAY 100000
Definition at line 60 of file rtsp.c.
Referenced by ff_rtsp_open_transport_ctx().
OFFSET
#define OFFSET (x) offsetof(RTSPState, x)
Definition at line 62 of file rtsp.c.
DEC
#define DEC AV_OPT_FLAG_DECODING_PARAM
Definition at line 63 of file rtsp.c.
ENC
#define ENC AV_OPT_FLAG_ENCODING_PARAM
Definition at line 64 of file rtsp.c.
RTSP_FLAG_OPTS
#define RTSP_FLAG_OPTS (name, longname)
Value:
{ name, longname, OFFSET(rtsp_flags), AV_OPT_TYPE_FLAGS, {.i64 = 0}, INT_MIN, INT_MAX, DEC, "rtsp_flags" }, \
    { "filter_src", "only receive packets from the negotiated peer IP", 0, AV_OPT_TYPE_CONST, {.i64 = RTSP_FLAG_FILTER_SRC}, 0, 0, DEC, "rtsp_flags" }
Definition at line 66 of file rtsp.c.
RTSP_MEDIATYPE_OPTS
#define RTSP_MEDIATYPE_OPTS (name, longname)
Value:
{ name, longname, OFFSET(media_type_mask), AV_OPT_TYPE_FLAGS, { .i64 = (1 << (AVMEDIA_TYPE_SUBTITLE+1)) - 1 }, INT_MIN, INT_MAX, DEC, "allowed_media_types" }, \
    { "video", "Video", 0, AV_OPT_TYPE_CONST, {.i64 = 1 << AVMEDIA_TYPE_VIDEO}, 0, 0, DEC, "allowed_media_types" }, \
    { "audio", "Audio", 0, AV_OPT_TYPE_CONST, {.i64 = 1 << AVMEDIA_TYPE_AUDIO}, 0, 0, DEC, "allowed_media_types" }, \
    { "data", "Data", 0, AV_OPT_TYPE_CONST, {.i64 = 1 << AVMEDIA_TYPE_DATA}, 0, 0, DEC, "allowed_media_types" }, \
    { "subtitle", "Subtitle", 0, AV_OPT_TYPE_CONST, {.i64 = 1 << AVMEDIA_TYPE_SUBTITLE}, 0, 0, DEC, "allowed_media_types" }
Definition at line 70 of file rtsp.c.
COMMON_OPTS
#define COMMON_OPTS ()
Value:
{ "reorder_queue_size", "set number of packets to buffer for handling of reordered packets", OFFSET(reordering_queue_size), AV_OPT_TYPE_INT, { .i64 = -1 }, -1, INT_MAX, DEC }, \
    { "buffer_size",        "Underlying protocol send/receive buffer size",                  OFFSET(buffer_size),           AV_OPT_TYPE_INT, { .i64 = -1 }, -1, INT_MAX, DEC|ENC } \
Definition at line 77 of file rtsp.c.
Function Documentation
map_to_opts()
static AVDictionary* map_to_opts (RTSPState * rt) static
Definition at line 119 of file rtsp.c.
Referenced by ff_rtsp_open_transport_ctx().
get_word_until_chars()
static void get_word_until_chars (char * buf, int buf_size, const char * sep, const char ** pp) static
Definition at line 130 of file rtsp.c.
Referenced by get_word(), and get_word_sep().
get_word_sep()
static void get_word_sep (char * buf, int buf_size, const char * sep, const char ** pp) static
Definition at line 149 of file rtsp.c.
Referenced by ff_rtsp_open_transport_ctx(), get_sockaddr(), and rtsp_parse_range_npt().
get_word()
static void get_word (char * buf, int buf_size, const char ** pp) static
Definition at line 156 of file rtsp.c.
Referenced by ff_rtsp_open_transport_ctx(), and get_sockaddr().
rtsp_parse_range_npt()
static void rtsp_parse_range_npt (const char * p, int64_t * start, int64_t * end) static
Parse a string p in the form of Range:npt=xx-xx, and determine the start and end time.
Used for seeking in the rtp stream.
Definition at line 165 of file rtsp.c.
Referenced by ff_rtsp_open_transport_ctx(), and get_sockaddr().
get_sockaddr()
static int get_sockaddr (AVFormatContext * s, const char * buf, struct sockaddr_storage * sock) static
Definition at line 187 of file rtsp.c.
Referenced by ff_rtsp_open_transport_ctx().
ff_rtsp_undo_setup()
void ff_rtsp_undo_setup (AVFormatContext * s, int send_packets)
Undo the effect of ff_rtsp_make_setup_request, close the transport_priv and rtp_handle fields.
Definition at line 726 of file rtsp.c.
Referenced by ff_rtsp_close_streams(), ff_rtsp_open_transport_ctx(), resetup_tcp(), and rtsp_write_close().
ff_rtsp_close_streams()
void ff_rtsp_close_streams (AVFormatContext * s)
Close and free all streams within the RTSP (de)muxer.
Parameters
s RTSP (de)muxer context
Definition at line 760 of file rtsp.c.
Referenced by ff_rtsp_open_transport_ctx(), rtsp_read_close(), rtsp_read_header(), rtsp_write_close(), and rtsp_write_header().
ff_rtsp_open_transport_ctx()
int ff_rtsp_open_transport_ctx (AVFormatContext * s, RTSPStream * rtsp_st)
Open RTSP transport context.
Definition at line 796 of file rtsp.c.
Referenced by ff_rtsp_open_transport_ctx(), and rtsp_read_setup().
Variable Documentation
ff_rtsp_options
const AVOption ff_rtsp_options[]
Initial value:
= {
    { "initial_pause",  "do not start playing the stream immediately", OFFSET(initial_pause), AV_OPT_TYPE_BOOL, {.i64 = 0}, 0, 1, DEC },
    FF_RTP_FLAG_OPTS(RTSPState, rtp_muxer_flags),
    { "rtsp_transport", "set RTSP transport protocols", OFFSET(lower_transport_mask), AV_OPT_TYPE_FLAGS, {.i64 = 0}, INT_MIN, INT_MAX, DEC|ENC, "rtsp_transport" },
    { "udp", "UDP", 0, AV_OPT_TYPE_CONST, {.i64 = 1 << RTSP_LOWER_TRANSPORT_UDP}, 0, 0, DEC|ENC, "rtsp_transport" },
    { "tcp", "TCP", 0, AV_OPT_TYPE_CONST, {.i64 = 1 << RTSP_LOWER_TRANSPORT_TCP}, 0, 0, DEC|ENC, "rtsp_transport" },
    { "udp_multicast", "UDP multicast", 0, AV_OPT_TYPE_CONST, {.i64 = 1 << RTSP_LOWER_TRANSPORT_UDP_MULTICAST}, 0, 0, DEC, "rtsp_transport" },
    { "http", "HTTP tunneling", 0, AV_OPT_TYPE_CONST, {.i64 = (1 << RTSP_LOWER_TRANSPORT_HTTP)}, 0, 0, DEC, "rtsp_transport" },
    RTSP_FLAG_OPTS("rtsp_flags", "set RTSP flags"),
    { "listen", "wait for incoming connections", 0, AV_OPT_TYPE_CONST, {.i64 = RTSP_FLAG_LISTEN}, 0, 0, DEC, "rtsp_flags" },
    { "prefer_tcp", "try RTP via TCP first, if available", 0, AV_OPT_TYPE_CONST, {.i64 = RTSP_FLAG_PREFER_TCP}, 0, 0, DEC|ENC, "rtsp_flags" },
    RTSP_MEDIATYPE_OPTS("allowed_media_types", "set media types to accept from the server"),
    { "min_port", "set minimum local UDP port", OFFSET(rtp_port_min), AV_OPT_TYPE_INT, {.i64 = RTSP_RTP_PORT_MIN}, 0, 65535, DEC|ENC },
    { "max_port", "set maximum local UDP port", OFFSET(rtp_port_max), AV_OPT_TYPE_INT, {.i64 = RTSP_RTP_PORT_MAX}, 0, 65535, DEC|ENC },
    { "timeout", "set maximum timeout (in seconds) to wait for incoming connections (-1 is infinite, imply flag listen)", OFFSET(initial_timeout), AV_OPT_TYPE_INT, {.i64 = -1}, INT_MIN, INT_MAX, DEC },
    { "stimeout", "set timeout (in microseconds) of socket TCP I/O operations", OFFSET(stimeout), AV_OPT_TYPE_INT, {.i64 = 0}, INT_MIN, INT_MAX, DEC },
    COMMON_OPTS(),
    { "user-agent", "override User-Agent header", OFFSET(user_agent), AV_OPT_TYPE_STRING, {.str = LIBAVFORMAT_IDENT}, 0, 0, DEC },
    { NULL },
}
Definition at line 82 of file rtsp.c.
sdp_options
const AVOption sdp_options[] static
Initial value:
= {
    RTSP_FLAG_OPTS("sdp_flags", "SDP flags"),
    { "custom_io", "use custom I/O", 0, AV_OPT_TYPE_CONST, {.i64 = RTSP_FLAG_CUSTOM_IO}, 0, 0, DEC, "rtsp_flags" },
    { "rtcp_to_source", "send RTCP packets to the source address of received packets", 0, AV_OPT_TYPE_CONST, {.i64 = RTSP_FLAG_RTCP_TO_SOURCE}, 0, 0, DEC, "rtsp_flags" },
    RTSP_MEDIATYPE_OPTS("allowed_media_types", "set media types to accept from the server"),
    COMMON_OPTS(),
    { NULL },
}
Definition at line 103 of file rtsp.c.
Referenced by ff_rtsp_open_transport_ctx().
rtp_options
const AVOption rtp_options[] static
Initial value:
= {
    RTSP_FLAG_OPTS("rtp_flags", "set RTP flags"),
    COMMON_OPTS(),
    { NULL },
}
Definition at line 112 of file rtsp.c.
Referenced by ff_rtsp_open_transport_ctx().