FFmpeg: libavformat/rtspdec.c File Reference
rtspdec.c File Reference
#include "libavutil/avstring.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/mathematics.h"
#include "libavutil/random_seed.h"
#include "libavutil/time.h"
#include "avformat.h"
#include "internal.h"
#include "network.h"
#include "os_support.h"
#include "rtpproto.h"
#include "rtsp.h"
#include "rdt.h"
#include "tls.h"
#include "url.h"
Data Structures
struct RTSPStatusMessage
Functions
static int rtsp_read_close (AVFormatContext *s)
static int read_line (AVFormatContext *s, char *rbuf, const int rbufsize, int *rbuflen)
static int rtsp_send_reply (AVFormatContext *s, enum RTSPStatusCode code, const char *extracontent, uint16_t seq)
static int check_sessionid (AVFormatContext *s, RTSPMessageHeader *request)
static int rtsp_read_request (AVFormatContext *s, RTSPMessageHeader *request, const char *method)
static int rtsp_read_announce (AVFormatContext *s)
static int rtsp_read_options (AVFormatContext *s)
static int rtsp_read_setup (AVFormatContext *s, char *host, char *controlurl)
static int rtsp_read_record (AVFormatContext *s)
static int parse_command_line (AVFormatContext *s, const char *line, int linelen, char *uri, int urisize, char *method, int methodsize, enum RTSPMethod *methodcode)
int ff_rtsp_parse_streaming_commands (AVFormatContext *s)
Parse RTSP commands (OPTIONS, PAUSE and TEARDOWN) during streaming in listen mode.
static int rtsp_read_play (AVFormatContext *s)
static int rtsp_read_pause (AVFormatContext *s)
int ff_rtsp_setup_input_streams (AVFormatContext *s, RTSPMessageHeader *reply)
Get the description of the stream and set up the RTSPStream child objects.
static int rtsp_listen (AVFormatContext *s)
static int rtsp_probe (AVProbeData *p)
static int rtsp_read_header (AVFormatContext *s)
int ff_rtsp_tcp_read_packet (AVFormatContext *s, RTSPStream **prtsp_st, uint8_t *buf, int buf_size)
Receive one RTP packet from an TCP interleaved RTSP stream.
static int resetup_tcp (AVFormatContext *s)
static int rtsp_read_packet (AVFormatContext *s, AVPacket *pkt)
static int rtsp_read_seek (AVFormatContext *s, int stream_index, int64_t timestamp, int flags)
Variables
static const struct RTSPStatusMessage status_messages []
static const AVClass rtsp_demuxer_class
AVInputFormat ff_rtsp_demuxer
Function Documentation
rtsp_read_close()
static int rtsp_read_close (AVFormatContext * s) static
Definition at line 56 of file rtspdec.c.
read_line()
static int read_line (AVFormatContext * s, char * rbuf, const int rbufsize, int * rbuflen) inline static
Definition at line 71 of file rtspdec.c.
Referenced by ff_rtsp_parse_streaming_commands(), rtsp_listen(), and rtsp_read_request().
rtsp_send_reply()
static int rtsp_send_reply (AVFormatContext * s, enum RTSPStatusCode code, const char * extracontent, uint16_t seq) static
Definition at line 96 of file rtspdec.c.
Referenced by check_sessionid(), ff_rtsp_parse_streaming_commands(), rtsp_read_announce(), rtsp_read_options(), rtsp_read_record(), and rtsp_read_setup().
check_sessionid()
static int check_sessionid (AVFormatContext * s, RTSPMessageHeader * request) inline static
Definition at line 123 of file rtspdec.c.
Referenced by rtsp_read_record(), and rtsp_read_request().
rtsp_read_request()
static int rtsp_read_request (AVFormatContext * s, RTSPMessageHeader * request, const char * method) inline static
Definition at line 141 of file rtspdec.c.
Referenced by ff_rtsp_parse_streaming_commands(), rtsp_read_announce(), rtsp_read_options(), rtsp_read_record(), and rtsp_read_setup().
rtsp_read_announce()
static int rtsp_read_announce (AVFormatContext * s) static
Definition at line 171 of file rtspdec.c.
Referenced by rtsp_listen().
rtsp_read_options()
static int rtsp_read_options (AVFormatContext * s) static
Definition at line 212 of file rtspdec.c.
Referenced by rtsp_listen().
rtsp_read_setup()
static int rtsp_read_setup (AVFormatContext * s, char * host, char * controlurl) static
Definition at line 230 of file rtspdec.c.
Referenced by rtsp_listen().
rtsp_read_record()
static int rtsp_read_record (AVFormatContext * s) static
Definition at line 340 of file rtspdec.c.
Referenced by rtsp_listen().
parse_command_line()
static int parse_command_line (AVFormatContext * s, const char * line, int linelen, char * uri, int urisize, char * method, int methodsize, enum RTSPMethod * methodcode) inline static
Definition at line 362 of file rtspdec.c.
Referenced by ff_rtsp_parse_streaming_commands(), and rtsp_listen().
ff_rtsp_parse_streaming_commands()
int ff_rtsp_parse_streaming_commands (AVFormatContext * s)
Parse RTSP commands (OPTIONS, PAUSE and TEARDOWN) during streaming in listen mode.
Definition at line 465 of file rtspdec.c.
Referenced by ff_rtsp_open_transport_ctx().
rtsp_read_play()
static int rtsp_read_play (AVFormatContext * s) static
Definition at line 506 of file rtspdec.c.
Referenced by rtsp_read_header(), rtsp_read_packet(), and rtsp_read_seek().
rtsp_read_pause()
static int rtsp_read_pause (AVFormatContext * s) static
Definition at line 577 of file rtspdec.c.
Referenced by rtsp_read_packet(), and rtsp_read_seek().
ff_rtsp_setup_input_streams()
int ff_rtsp_setup_input_streams (AVFormatContext * s, RTSPMessageHeader * reply)
Get the description of the stream and set up the RTSPStream child objects.
The Require: attribute is needed for proper streaming from Realmedia servers.
Definition at line 594 of file rtspdec.c.
Referenced by ff_rtsp_open_transport_ctx().
rtsp_listen()
static int rtsp_listen (AVFormatContext * s) static
Definition at line 631 of file rtspdec.c.
Referenced by rtsp_read_header().
rtsp_probe()
static int rtsp_probe (AVProbeData * p) static
Definition at line 704 of file rtspdec.c.
rtsp_read_header()
static int rtsp_read_header (AVFormatContext * s) static
Definition at line 715 of file rtspdec.c.
ff_rtsp_tcp_read_packet()
int ff_rtsp_tcp_read_packet (AVFormatContext * s, RTSPStream ** prtsp_st, uint8_t * buf, int buf_size)
Receive one RTP packet from an TCP interleaved RTSP stream.
Definition at line 752 of file rtspdec.c.
Referenced by ff_rtsp_open_transport_ctx().
resetup_tcp()
static int resetup_tcp (AVFormatContext * s) static
Definition at line 802 of file rtspdec.c.
Referenced by rtsp_read_packet().
rtsp_read_packet()
static int rtsp_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 815 of file rtspdec.c.
rtsp_read_seek()
static int rtsp_read_seek (AVFormatContext * s, int stream_index, int64_t timestamp, int flags) static
Definition at line 930 of file rtspdec.c.
Variable Documentation
status_messages
const struct RTSPStatusMessage status_messages[] static
Initial value:
= {
    { RTSP_STATUS_OK,             "OK"                               },
    { RTSP_STATUS_METHOD,         "Method Not Allowed"               },
    { RTSP_STATUS_BANDWIDTH,      "Not Enough Bandwidth"             },
    { RTSP_STATUS_SESSION,        "Session Not Found"                },
    { RTSP_STATUS_STATE,          "Method Not Valid in This State"   },
    { RTSP_STATUS_AGGREGATE,      "Aggregate operation not allowed"  },
    { RTSP_STATUS_ONLY_AGGREGATE, "Only aggregate operation allowed" },
    { RTSP_STATUS_TRANSPORT,      "Unsupported transport"            },
    { RTSP_STATUS_INTERNAL,       "Internal Server Error"            },
    { RTSP_STATUS_SERVICE,        "Service Unavailable"              },
    { RTSP_STATUS_VERSION,        "RTSP Version not supported"       },
    { 0,                          "NULL"                             }
}
Referenced by rtsp_send_reply().
rtsp_demuxer_class
const AVClass rtsp_demuxer_class static
Initial value:
= {
    .class_name     = "RTSP demuxer",
    .item_name      = av_default_item_name,
    .option         = ff_rtsp_options,
    .version        = LIBAVUTIL_VERSION_INT,
}
Definition at line 957 of file rtspdec.c.
ff_rtsp_demuxer
AVInputFormat ff_rtsp_demuxer
Initial value:
= {
    .name           = "rtsp",
    .long_name      = NULL_IF_CONFIG_SMALL("RTSP input"),
    .priv_data_size = sizeof(RTSPState),
    .read_probe     = rtsp_probe,
    .read_header    = rtsp_read_header,
    .read_packet    = rtsp_read_packet,
    .read_close     = rtsp_read_close,
    .read_seek      = rtsp_read_seek,
    .flags          = AVFMT_NOFILE,
    .read_play      = rtsp_read_play,
    .read_pause     = rtsp_read_pause,
    .priv_class     = &rtsp_demuxer_class,
}
Definition at line 964 of file rtspdec.c.