FFmpeg: libavcodec/rv10.h File Reference
rv10.h File Reference
#include <stdint.h>
#include "mpegvideo.h"
Functions
int ff_rv_decode_dc (MpegEncContext *s, int n)
int ff_rv10_encode_picture_header (MpegEncContext *s, int picture_number)
void ff_rv20_encode_picture_header (MpegEncContext *s, int picture_number)
Function Documentation
ff_rv_decode_dc()
int ff_rv_decode_dc (MpegEncContext * s, int n)
Definition at line 198 of file rv10.c.
Referenced by h263_decode_block().
ff_rv10_encode_picture_header()
int ff_rv10_encode_picture_header (MpegEncContext * s, int picture_number)
Definition at line 32 of file rv10enc.c.
Referenced by encode_picture().
ff_rv20_encode_picture_header()
void ff_rv20_encode_picture_header (MpegEncContext * s, int picture_number)
Definition at line 35 of file rv20enc.c.
Referenced by encode_picture().