FFmpeg: libavcodec/rv30.c File Reference
rv30.c File Reference
RV30 decoder.
#include "avcodec.h"
#include "mpegutils.h"
#include "mpegvideo.h"
#include "golomb.h"
#include "rv34.h"
#include "rv30data.h"
Functions
static int rv30_parse_slice_header (RV34DecContext *r, GetBitContext *gb, SliceInfo *si)
static int rv30_decode_intra_types (RV34DecContext *r, GetBitContext *gb, int8_t *dst)
Decode 4x4 intra types array.
static int rv30_decode_mb_info (RV34DecContext *r)
Decode macroblock information.
static void rv30_weak_loop_filter (uint8_t *src, const int step, const int stride, const int lim)
static void rv30_loop_filter (RV34DecContext *r, int row)
static av_cold int rv30_decode_init (AVCodecContext *avctx)
Initialize decoder.
Variables
AVCodec ff_rv30_decoder
Detailed Description
RV30 decoder.
Definition in file rv30.c.
Function Documentation
rv30_parse_slice_header()
static int rv30_parse_slice_header (RV34DecContext * r, GetBitContext * gb, SliceInfo * si) static
Definition at line 36 of file rv30.c.
Referenced by rv30_decode_init().
rv30_decode_intra_types()
static int rv30_decode_intra_types (RV34DecContext * r, GetBitContext * gb, int8_t * dst) static
Decode 4x4 intra types array.
Definition at line 86 of file rv30.c.
Referenced by rv30_decode_init().
rv30_decode_mb_info()
static int rv30_decode_mb_info (RV34DecContext * r) static
Decode macroblock information.
Definition at line 114 of file rv30.c.
Referenced by rv30_decode_init().
rv30_weak_loop_filter()
static void rv30_weak_loop_filter (uint8_t * src, const int step, const int stride, const int lim) inline static
Definition at line 136 of file rv30.c.
Referenced by rv30_loop_filter().
rv30_loop_filter()
static void rv30_loop_filter (RV34DecContext * r, int row) static
Definition at line 151 of file rv30.c.
Referenced by rv30_decode_init().
rv30_decode_init()
static av_cold int rv30_decode_init (AVCodecContext * avctx) static
Initialize decoder.
Definition at line 260 of file rv30.c.
Variable Documentation
ff_rv30_decoder
AVCodec ff_rv30_decoder
Initial value:
= {
    .name                  = "rv30",
    .long_name             = NULL_IF_CONFIG_SMALL("RealVideo 3.0"),
    .type                  = AVMEDIA_TYPE_VIDEO,
    .id                    = AV_CODEC_ID_RV30,
    .priv_data_size        = sizeof(RV34DecContext),
    .init                  = rv30_decode_init,
    .close                 = ff_rv34_decode_end,
    .decode                = ff_rv34_decode_frame,
    .capabilities          = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_DELAY |
                             AV_CODEC_CAP_FRAME_THREADS,
    .flush                 = ff_mpeg_flush,
    .pix_fmts              = (const enum AVPixelFormat[]) {
        AV_PIX_FMT_YUV420P,
        AV_PIX_FMT_NONE
    },
    .init_thread_copy      = ONLY_IF_THREADS_ENABLED(ff_rv34_decode_init_thread_copy),
    .update_thread_context = ONLY_IF_THREADS_ENABLED(ff_rv34_decode_update_thread_context),
}
Definition at line 291 of file rv30.c.