FFmpeg: libavcodec/x86/rv34dsp_init.c File Reference
rv34dsp_init.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/x86/cpu.h"
#include "libavcodec/rv34dsp.h"
Functions
void ff_rv34_idct_dc_mmxext (int16_t *block)
void ff_rv34_idct_dc_noround_mmxext (int16_t *block)
void ff_rv34_idct_dc_add_mmx (uint8_t *dst, ptrdiff_t stride, int dc)
void ff_rv34_idct_dc_add_sse4 (uint8_t *dst, ptrdiff_t stride, int dc)
void ff_rv34_idct_add_mmxext (uint8_t *dst, ptrdiff_t stride, int16_t *block)
av_cold void ff_rv34dsp_init_x86 (RV34DSPContext *c)
Function Documentation
ff_rv34_idct_dc_mmxext()
void ff_rv34_idct_dc_mmxext (int16_t * block)
ff_rv34_idct_dc_noround_mmxext()
void ff_rv34_idct_dc_noround_mmxext (int16_t * block)
Referenced by ff_rv34dsp_init_x86().
ff_rv34_idct_dc_add_mmx()
void ff_rv34_idct_dc_add_mmx (uint8_t * dst, ptrdiff_t stride, int dc)
Referenced by ff_rv34dsp_init_x86().
ff_rv34_idct_dc_add_sse4()
void ff_rv34_idct_dc_add_sse4 (uint8_t * dst, ptrdiff_t stride, int dc)
Referenced by ff_rv34dsp_init_x86().
ff_rv34_idct_add_mmxext()
void ff_rv34_idct_add_mmxext (uint8_t * dst, ptrdiff_t stride, int16_t * block)
Referenced by ff_rv34dsp_init_x86().
ff_rv34dsp_init_x86()
av_cold void ff_rv34dsp_init_x86 (RV34DSPContext * c)
Definition at line 33 of file rv34dsp_init.c.
Referenced by ff_rv34dsp_init().