FFmpeg: libavcodec/rv34dsp.h File Reference
rv34dsp.h File Reference
RV30/40 decoder motion compensation functions.
#include "h264chroma.h"
#include "qpeldsp.h"
Data Structures
struct RV34DSPContext
Typedefs
typedef void(* rv40_weight_func) (uint8_t *dst, uint8_t *src1, uint8_t *src2, int w1, int w2, ptrdiff_t stride)
typedef void(* rv34_inv_transform_func) (int16_t *block)
typedef void(* rv34_idct_add_func) (uint8_t *dst, ptrdiff_t stride, int16_t *block)
typedef void(* rv34_idct_dc_add_func) (uint8_t *dst, ptrdiff_t stride, int dc)
typedef void(* rv40_weak_loop_filter_func) (uint8_t *src, ptrdiff_t stride, int filter_p1, int filter_q1, int alpha, int beta, int lims, int lim_q1, int lim_p1)
typedef void(* rv40_strong_loop_filter_func) (uint8_t *src, ptrdiff_t stride, int alpha, int lims, int dmode, int chroma)
typedef int(* rv40_loop_filter_strength_func) (uint8_t *src, ptrdiff_t stride, int beta, int beta2, int edge, int *p1, int *q1)
Functions
void ff_rv30dsp_init (RV34DSPContext *c)
void ff_rv34dsp_init (RV34DSPContext *c)
void ff_rv40dsp_init (RV34DSPContext *c)
void ff_rv34dsp_init_arm (RV34DSPContext *c)
void ff_rv34dsp_init_x86 (RV34DSPContext *c)
void ff_rv40dsp_init_aarch64 (RV34DSPContext *c)
void ff_rv40dsp_init_x86 (RV34DSPContext *c)
void ff_rv40dsp_init_arm (RV34DSPContext *c)
Detailed Description
RV30/40 decoder motion compensation functions.
Definition in file rv34dsp.h.
Typedef Documentation
rv40_weight_func
typedef void(* rv40_weight_func) (uint8_t *dst, uint8_t *src1, uint8_t *src2, int w1, int w2, ptrdiff_t stride)
Definition at line 33 of file rv34dsp.h.
rv34_inv_transform_func
typedef void(* rv34_inv_transform_func) (int16_t *block)
Definition at line 38 of file rv34dsp.h.
rv34_idct_add_func
typedef void(* rv34_idct_add_func) (uint8_t *dst, ptrdiff_t stride, int16_t *block)
Definition at line 40 of file rv34dsp.h.
rv34_idct_dc_add_func
typedef void(* rv34_idct_dc_add_func) (uint8_t *dst, ptrdiff_t stride, int dc)
Definition at line 41 of file rv34dsp.h.
rv40_weak_loop_filter_func
typedef void(* rv40_weak_loop_filter_func) (uint8_t *src, ptrdiff_t stride, int filter_p1, int filter_q1, int alpha, int beta, int lims, int lim_q1, int lim_p1)
Definition at line 44 of file rv34dsp.h.
rv40_strong_loop_filter_func
typedef void(* rv40_strong_loop_filter_func) (uint8_t *src, ptrdiff_t stride, int alpha, int lims, int dmode, int chroma)
Definition at line 49 of file rv34dsp.h.
rv40_loop_filter_strength_func
typedef int(* rv40_loop_filter_strength_func) (uint8_t *src, ptrdiff_t stride, int beta, int beta2, int edge, int *p1, int *q1)
Definition at line 53 of file rv34dsp.h.
Function Documentation
ff_rv30dsp_init()
void ff_rv30dsp_init (RV34DSPContext * c)
Definition at line 265 of file rv30dsp.c.
Referenced by ff_rv34_decode_init().
ff_rv34dsp_init()
void ff_rv34dsp_init (RV34DSPContext * c)
Definition at line 131 of file rv34dsp.c.
Referenced by ff_rv30dsp_init(), and ff_rv40dsp_init().
ff_rv40dsp_init()
void ff_rv40dsp_init (RV34DSPContext * c)
Definition at line 614 of file rv40dsp.c.
Referenced by ff_rv34_decode_init().
ff_rv34dsp_init_arm()
void ff_rv34dsp_init_arm (RV34DSPContext * c)
Definition at line 35 of file rv34dsp_init_arm.c.
Referenced by ff_rv34dsp_init().
ff_rv34dsp_init_x86()
void ff_rv34dsp_init_x86 (RV34DSPContext * c)
Definition at line 33 of file rv34dsp_init.c.
Referenced by ff_rv34dsp_init().
ff_rv40dsp_init_aarch64()
void ff_rv40dsp_init_aarch64 (RV34DSPContext * c)
Definition at line 38 of file rv40dsp_init_aarch64.c.
Referenced by ff_rv40dsp_init().
ff_rv40dsp_init_x86()
void ff_rv40dsp_init_x86 (RV34DSPContext * c)
Definition at line 215 of file rv40dsp_init.c.
Referenced by ff_rv40dsp_init().
ff_rv40dsp_init_arm()
void ff_rv40dsp_init_arm (RV34DSPContext * c)
Definition at line 144 of file rv40dsp_init_arm.c.
Referenced by ff_rv40dsp_init().