FFmpeg: libavcodec/rv34dsp.c File Reference
rv34dsp.c File Reference
RV30/40 decoder common dsp functions.
#include "rv34dsp.h"
#include "libavutil/common.h"
Functions
av_cold void ff_rv34dsp_init (RV34DSPContext *c)
RV30/40 inverse transform functions
static av_always_inline void rv34_row_transform (int temp[16], int16_t *block)
static void rv34_idct_add_c (uint8_t *dst, ptrdiff_t stride, int16_t *block)
Real Video 3.0/4.0 inverse transform + sample reconstruction Code is almost the same as in SVQ3, only scaling is different.
static void rv34_inv_transform_noround_c (int16_t *block)
RealVideo 3.0/4.0 inverse transform for DC block.
static void rv34_idct_dc_add_c (uint8_t *dst, ptrdiff_t stride, int dc)
static void rv34_inv_transform_dc_noround_c (int16_t *block)
Detailed Description
RV30/40 decoder common dsp functions.
Definition in file rv34dsp.c.
Function Documentation
rv34_row_transform()
static av_always_inline void rv34_row_transform (int temp[16], int16_t * block) static
Definition at line 36 of file rv34dsp.c.
Referenced by rv34_idct_add_c(), and rv34_inv_transform_noround_c().
rv34_idct_add_c()
static void rv34_idct_add_c (uint8_t * dst, ptrdiff_t stride, int16_t * block) static
Real Video 3.0/4.0 inverse transform + sample reconstruction Code is almost the same as in SVQ3, only scaling is different.
Definition at line 57 of file rv34dsp.c.
Referenced by ff_rv34dsp_init().
rv34_inv_transform_noround_c()
static void rv34_inv_transform_noround_c (int16_t * block) static
RealVideo 3.0/4.0 inverse transform for DC block.
Code is almost the same as rv34_inv_transform() but final coefficients are multiplied by 1.5 and have no rounding.
Definition at line 85 of file rv34dsp.c.
Referenced by ff_rv34dsp_init().
rv34_idct_dc_add_c()
static void rv34_idct_dc_add_c (uint8_t * dst, ptrdiff_t stride, int dc) static
Definition at line 104 of file rv34dsp.c.
Referenced by ff_rv34dsp_init().
rv34_inv_transform_dc_noround_c()
static void rv34_inv_transform_dc_noround_c (int16_t * block) static
Definition at line 118 of file rv34dsp.c.
Referenced by ff_rv34dsp_init().
ff_rv34dsp_init()
av_cold void ff_rv34dsp_init (RV34DSPContext * c)
Definition at line 131 of file rv34dsp.c.
Referenced by ff_rv30dsp_init(), and ff_rv40dsp_init().