FFmpeg: libavcodec/arm/rv34dsp_init_arm.c File Reference
rv34dsp_init_arm.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavcodec/avcodec.h"
#include "libavcodec/rv34dsp.h"
#include "libavutil/arm/cpu.h"
Functions
void ff_rv34_inv_transform_noround_neon (int16_t *block)
void ff_rv34_inv_transform_noround_dc_neon (int16_t *block)
void ff_rv34_idct_add_neon (uint8_t *dst, ptrdiff_t stride, int16_t *block)
void ff_rv34_idct_dc_add_neon (uint8_t *dst, ptrdiff_t stride, int dc)
av_cold void ff_rv34dsp_init_arm (RV34DSPContext *c)
Function Documentation
ff_rv34_inv_transform_noround_neon()
void ff_rv34_inv_transform_noround_neon (int16_t * block)
Referenced by ff_rv34dsp_init_arm().
ff_rv34_inv_transform_noround_dc_neon()
void ff_rv34_inv_transform_noround_dc_neon (int16_t * block)
Referenced by ff_rv34dsp_init_arm().
ff_rv34_idct_add_neon()
void ff_rv34_idct_add_neon (uint8_t * dst, ptrdiff_t stride, int16_t * block)
Referenced by ff_rv34dsp_init_arm().
ff_rv34_idct_dc_add_neon()
void ff_rv34_idct_dc_add_neon (uint8_t * dst, ptrdiff_t stride, int dc)
Referenced by ff_rv34dsp_init_arm().
ff_rv34dsp_init_arm()
av_cold void ff_rv34dsp_init_arm (RV34DSPContext * c)
Definition at line 35 of file rv34dsp_init_arm.c.
Referenced by ff_rv34dsp_init().