FFmpeg: libavcodec/aarch64/rv40dsp_init_aarch64.c File Reference
rv40dsp_init_aarch64.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/aarch64/cpu.h"
#include "libavcodec/rv34dsp.h"
#include "config.h"
Functions
void ff_put_rv40_chroma_mc8_neon (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_put_rv40_chroma_mc4_neon (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_avg_rv40_chroma_mc8_neon (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_avg_rv40_chroma_mc4_neon (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
av_cold void ff_rv40dsp_init_aarch64 (RV34DSPContext *c)
Function Documentation
ff_put_rv40_chroma_mc8_neon()
void ff_put_rv40_chroma_mc8_neon (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_rv40dsp_init_aarch64().
ff_put_rv40_chroma_mc4_neon()
void ff_put_rv40_chroma_mc4_neon (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_rv40dsp_init_aarch64().
ff_avg_rv40_chroma_mc8_neon()
void ff_avg_rv40_chroma_mc8_neon (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_rv40dsp_init_aarch64().
ff_avg_rv40_chroma_mc4_neon()
void ff_avg_rv40_chroma_mc4_neon (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_rv40dsp_init_aarch64().
ff_rv40dsp_init_aarch64()
av_cold void ff_rv40dsp_init_aarch64 (RV34DSPContext * c)
Definition at line 38 of file rv40dsp_init_aarch64.c.
Referenced by ff_rv40dsp_init().