FFmpeg: libavcodec/rv40.c File Reference
rv40.c File Reference
RV40 decoder.
#include "libavutil/imgutils.h"
#include "avcodec.h"
#include "mpegutils.h"
#include "mpegvideo.h"
#include "golomb.h"
#include "rv34.h"
#include "rv40vlc2.h"
#include "rv40data.h"
Macros
#define MASK_CUR 0x0001
#define MASK_RIGHT 0x0008
#define MASK_BOTTOM 0x0010
#define MASK_TOP 0x1000
#define MASK_Y_TOP_ROW 0x000F
#define MASK_Y_LAST_ROW 0xF000
#define MASK_Y_LEFT_COL 0x1111
#define MASK_Y_RIGHT_COL 0x8888
#define MASK_C_TOP_ROW 0x0003
#define MASK_C_LAST_ROW 0x000C
#define MASK_C_LEFT_COL 0x0005
#define MASK_C_RIGHT_COL 0x000A
Enumerations
enum RV40BlockPos { POS_CUR, POS_TOP, POS_LEFT, POS_BOTTOM }
Functions
static av_cold void rv40_init_tables (void)
Initialize all tables.
static int get_dimension (GetBitContext *gb, const int *dim)
Get stored dimension from bitstream.
static void rv40_parse_picture_size (GetBitContext *gb, int *w, int *h)
Get encoded picture size - usually this is called from rv40_parse_slice_header.
static int rv40_parse_slice_header (RV34DecContext *r, GetBitContext *gb, SliceInfo *si)
static int rv40_decode_intra_types (RV34DecContext *r, GetBitContext *gb, int8_t *dst)
Decode 4x4 intra types array.
static int rv40_decode_mb_info (RV34DecContext *r)
Decode macroblock information.
static void rv40_adaptive_loop_filter (RV34DSPContext *rdsp, uint8_t *src, int stride, int dmode, int lim_q1, int lim_p1, int alpha, int beta, int beta2, int chroma, int edge, int dir)
static void rv40_loop_filter (RV34DecContext *r, int row)
RV40 loop filtering function.
static av_cold int rv40_decode_init (AVCodecContext *avctx)
Initialize decoder.
Variables
static VLC aic_top_vlc
static VLC aic_mode1_vlc [AIC_MODE1_NUM]
static VLC aic_mode2_vlc [AIC_MODE2_NUM]
static VLC ptype_vlc [NUM_PTYPE_VLCS]
static VLC btype_vlc [NUM_BTYPE_VLCS]
static const int16_t mode2_offs []
static const int neighbour_offs_x [4] = { 0, 0, -1, 0 }
static const int neighbour_offs_y [4] = { 0, -1, 0, 1 }
AVCodec ff_rv40_decoder
Detailed Description
RV40 decoder.
Definition in file rv40.c.
Macro Definition Documentation
MASK_CUR
#define MASK_CUR 0x0001
Definition at line 290 of file rv40.c.
Referenced by rv40_loop_filter().
MASK_RIGHT
#define MASK_RIGHT 0x0008
Definition at line 291 of file rv40.c.
Referenced by rv40_loop_filter().
MASK_BOTTOM
#define MASK_BOTTOM 0x0010
Definition at line 292 of file rv40.c.
Referenced by rv40_loop_filter().
MASK_TOP
#define MASK_TOP 0x1000
Definition at line 293 of file rv40.c.
Referenced by rv40_loop_filter().
MASK_Y_TOP_ROW
#define MASK_Y_TOP_ROW 0x000F
Definition at line 294 of file rv40.c.
Referenced by rv40_loop_filter().
MASK_Y_LAST_ROW
#define MASK_Y_LAST_ROW 0xF000
Definition at line 295 of file rv40.c.
Referenced by rv40_loop_filter().
MASK_Y_LEFT_COL
#define MASK_Y_LEFT_COL 0x1111
Definition at line 296 of file rv40.c.
Referenced by rv40_loop_filter().
MASK_Y_RIGHT_COL
#define MASK_Y_RIGHT_COL 0x8888
Definition at line 297 of file rv40.c.
Referenced by rv40_loop_filter().
MASK_C_TOP_ROW
#define MASK_C_TOP_ROW 0x0003
Definition at line 298 of file rv40.c.
Referenced by rv40_loop_filter().
MASK_C_LAST_ROW
#define MASK_C_LAST_ROW 0x000C
Definition at line 299 of file rv40.c.
Referenced by rv40_loop_filter().
MASK_C_LEFT_COL
#define MASK_C_LEFT_COL 0x0005
Definition at line 300 of file rv40.c.
Referenced by rv40_loop_filter().
MASK_C_RIGHT_COL
#define MASK_C_RIGHT_COL 0x000A
Definition at line 301 of file rv40.c.
Referenced by rv40_loop_filter().
Enumeration Type Documentation
RV40BlockPos
enum RV40BlockPos
Enumerator
POS_CUR
POS_TOP
POS_LEFT
POS_BOTTOM
Definition at line 283 of file rv40.c.
Function Documentation
rv40_init_tables()
static av_cold void rv40_init_tables (void) static
Initialize all tables.
Definition at line 50 of file rv40.c.
Referenced by rv40_decode_init().
get_dimension()
static int get_dimension (GetBitContext * gb, const int * dim) static
Get stored dimension from bitstream.
If the width/height is the standard one then it's coded as a 3-bit index. Otherwise it is coded as escaped 8-bit portions.
Definition at line 104 of file rv40.c.
Referenced by rv40_parse_picture_size().
rv40_parse_picture_size()
static void rv40_parse_picture_size (GetBitContext * gb, int * w, int * h) static
Get encoded picture size - usually this is called from rv40_parse_slice_header.
Definition at line 124 of file rv40.c.
Referenced by rv40_parse_slice_header().
rv40_parse_slice_header()
static int rv40_parse_slice_header (RV34DecContext * r, GetBitContext * gb, SliceInfo * si) static
Definition at line 130 of file rv40.c.
Referenced by rv40_decode_init().
rv40_decode_intra_types()
static int rv40_decode_intra_types (RV34DecContext * r, GetBitContext * gb, int8_t * dst) static
Decode 4x4 intra types array.
Definition at line 164 of file rv40.c.
Referenced by rv40_decode_init().
rv40_decode_mb_info()
static int rv40_decode_mb_info (RV34DecContext * r) static
Decode macroblock information.
Definition at line 227 of file rv40.c.
Referenced by rv40_decode_init().
rv40_adaptive_loop_filter()
static void rv40_adaptive_loop_filter (RV34DSPContext * rdsp, uint8_t * src, int stride, int dmode, int lim_q1, int lim_p1, int alpha, int beta, int beta2, int chroma, int edge, int dir) static
Definition at line 306 of file rv40.c.
Referenced by rv40_loop_filter().
rv40_loop_filter()
static void rv40_loop_filter (RV34DecContext * r, int row) static
RV40 loop filtering function.
< current macroblock and its neighbours types
flags indicating that macroblock can be filtered with strong filter it is set only for intra coded MB and MB with DCs coded separately
< MB filter clipping value calculated from filtering strength
coded block patterns for luma part of current macroblock and its neighbours Format: LSB corresponds to the top left block, each nibble represents one row of subblocks.
coded block patterns for chroma part of current macroblock and its neighbours Format is the same as for luma with two subblocks in a row.
This mask represents the pattern of luma subblocks that should be filtered in addition to the coded ones because they lie at the edge of 8x8 block with different enough motion vectors
Definition at line 337 of file rv40.c.
Referenced by rv40_decode_init().
rv40_decode_init()
static av_cold int rv40_decode_init (AVCodecContext * avctx) static
Initialize decoder.
Definition at line 551 of file rv40.c.
Variable Documentation
aic_top_vlc
VLC aic_top_vlc static
Definition at line 38 of file rv40.c.
aic_mode1_vlc
VLC aic_mode1_vlc[AIC_MODE1_NUM] static
Definition at line 39 of file rv40.c.
aic_mode2_vlc
VLC aic_mode2_vlc[AIC_MODE2_NUM] static
Definition at line 39 of file rv40.c.
ptype_vlc
VLC ptype_vlc[NUM_PTYPE_VLCS] static
Definition at line 40 of file rv40.c.
btype_vlc
VLC btype_vlc[NUM_BTYPE_VLCS] static
Definition at line 40 of file rv40.c.
mode2_offs
const int16_t mode2_offs[] static
Initial value:
= {
       0,  614, 1222, 1794, 2410,  3014,  3586,  4202,  4792, 5382, 5966, 6542,
    7138, 7716, 8292, 8864, 9444, 10030, 10642, 11212, 11814
}
Definition at line 42 of file rv40.c.
Referenced by rv40_init_tables().
neighbour_offs_x
const int neighbour_offs_x[4] = { 0, 0, -1, 0 } static
Definition at line 303 of file rv40.c.
Referenced by rv40_loop_filter().
neighbour_offs_y
const int neighbour_offs_y[4] = { 0, -1, 0, 1 } static
Definition at line 304 of file rv40.c.
Referenced by rv40_loop_filter().
ff_rv40_decoder
AVCodec ff_rv40_decoder
Initial value:
= {
    .name                  = "rv40",
    .long_name             = NULL_IF_CONFIG_SMALL("RealVideo 4.0"),
    .type                  = AVMEDIA_TYPE_VIDEO,
    .id                    = AV_CODEC_ID_RV40,
    .priv_data_size        = sizeof(RV34DecContext),
    .init                  = rv40_decode_init,
    .close                 = ff_rv34_decode_end,
    .decode                = ff_rv34_decode_frame,
    .capabilities          = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_DELAY |
                             AV_CODEC_CAP_FRAME_THREADS,
    .flush                 = ff_mpeg_flush,
    .pix_fmts              = (const enum AVPixelFormat[]) {
        AV_PIX_FMT_YUV420P,
        AV_PIX_FMT_NONE
    },
    .init_thread_copy      = ONLY_IF_THREADS_ENABLED(ff_rv34_decode_init_thread_copy),
    .update_thread_context = ONLY_IF_THREADS_ENABLED(ff_rv34_decode_update_thread_context),
}
Definition at line 570 of file rv40.c.