FFmpeg: libavcodec/sbrdsp.h File Reference
sbrdsp.h File Reference
#include <stdint.h>
#include "aac_defines.h"
#include "libavutil/softfloat.h"
Data Structures
struct SBRDSPContext
Functions
const INTFLOAT AAC_RENAME (ff_sbr_noise_table)[][2]
void AAC_RENAME() ff_sbrdsp_init (SBRDSPContext *s)
void ff_sbrdsp_init_arm (SBRDSPContext *s)
void ff_sbrdsp_init_x86 (SBRDSPContext *s)
void ff_sbrdsp_init_mips (SBRDSPContext *s)
Function Documentation
AAC_RENAME()
const INTFLOAT AAC_RENAME (ff_sbr_noise_table)
ff_sbrdsp_init()
void AAC_RENAME() ff_sbrdsp_init (SBRDSPContext * s)
Definition at line 71 of file sbrdsp_template.c.
Referenced by ff_aac_sbr_ctx_init().
ff_sbrdsp_init_arm()
void ff_sbrdsp_init_arm (SBRDSPContext * s)
Definition at line 53 of file sbrdsp_init_arm.c.
Referenced by ff_sbrdsp_init().
ff_sbrdsp_init_x86()
void ff_sbrdsp_init_x86 (SBRDSPContext * s)
Definition at line 59 of file sbrdsp_init.c.
Referenced by ff_sbrdsp_init().
ff_sbrdsp_init_mips()
void ff_sbrdsp_init_mips (SBRDSPContext * s)
Definition at line 890 of file sbrdsp_mips.c.
Referenced by ff_sbrdsp_init().