FFmpeg: libavcodec/sbrdsp_fixed.c File Reference
sbrdsp_fixed.c File Reference
#include "aac.h"
#include "config.h"
#include "libavutil/attributes.h"
#include "libavutil/intfloat.h"
#include "sbrdsp.h"
#include "sbrdsp_template.c"
Macros
#define USE_FIXED 1
Functions
static SoftFloat sbr_sum_square_c (int(*x)[2], int n)
static void sbr_neg_odd_64_c (int *x)
static void sbr_qmf_pre_shuffle_c (int *z)
static void sbr_qmf_post_shuffle_c (int W[32][2], const int *z)
static void sbr_qmf_deint_neg_c (int *v, const int *src)
static av_always_inline SoftFloat autocorr_calc (int64_t accu)
static av_always_inline void autocorrelate (const int x[40][2], SoftFloat phi[3][2][2], int lag)
static void sbr_autocorrelate_c (const int x[40][2], SoftFloat phi[3][2][2])
static void sbr_hf_gen_c (int(*X_high)[2], const int(*X_low)[2], const int alpha0[2], const int alpha1[2], int bw, int start, int end)
static void sbr_hf_g_filt_c (int(*Y)[2], const int(*X_high)[40][2], const SoftFloat *g_filt, int m_max, intptr_t ixh)
static av_always_inline void sbr_hf_apply_noise (int(*Y)[2], const SoftFloat *s_m, const SoftFloat *q_filt, int noise, int phi_sign0, int phi_sign1, int m_max)
Macro Definition Documentation
USE_FIXED
#define USE_FIXED 1
Definition at line 26 of file sbrdsp_fixed.c.
Function Documentation
sbr_sum_square_c()
static SoftFloat sbr_sum_square_c (int(*) x[2], int n) static
Definition at line 34 of file sbrdsp_fixed.c.
sbr_neg_odd_64_c()
static void sbr_neg_odd_64_c (int * x) static
Definition at line 72 of file sbrdsp_fixed.c.
sbr_qmf_pre_shuffle_c()
static void sbr_qmf_pre_shuffle_c (int * z) static
Definition at line 79 of file sbrdsp_fixed.c.
sbr_qmf_post_shuffle_c()
static void sbr_qmf_post_shuffle_c (int W[32][2], const int * z) static
Definition at line 90 of file sbrdsp_fixed.c.
sbr_qmf_deint_neg_c()
static void sbr_qmf_deint_neg_c (int * v, const int * src) static
Definition at line 99 of file sbrdsp_fixed.c.
autocorr_calc()
static av_always_inline SoftFloat autocorr_calc (int64_t accu) static
Definition at line 108 of file sbrdsp_fixed.c.
Referenced by autocorrelate().
autocorrelate()
static av_always_inline void autocorrelate (const int x[40][2], SoftFloat phi[3][2][2], int lag) static
Definition at line 131 of file sbrdsp_fixed.c.
Referenced by sbr_autocorrelate_c(), and sbr_qmf_deint_neg_c().
sbr_autocorrelate_c()
static void sbr_autocorrelate_c (const int x[40][2], SoftFloat phi[3][2][2]) static
Definition at line 186 of file sbrdsp_fixed.c.
sbr_hf_gen_c()
static void sbr_hf_gen_c (int(*) X_high[2], const int(*) X_low[2], const int alpha0[2], const int alpha1[2], int bw, int start, int end) static
Definition at line 193 of file sbrdsp_fixed.c.
sbr_hf_g_filt_c()
static void sbr_hf_g_filt_c (int(*) Y[2], const int(*) X_high[40][2], const SoftFloat * g_filt, int m_max, intptr_t ixh) static
Definition at line 229 of file sbrdsp_fixed.c.
sbr_hf_apply_noise()
static av_always_inline void sbr_hf_apply_noise (int(*) Y[2], const SoftFloat * s_m, const SoftFloat * q_filt, int noise, int phi_sign0, int phi_sign1, int m_max) static
Definition at line 245 of file sbrdsp_fixed.c.