FFmpeg: libavcodec/sbrdsp_template.c File Reference
sbrdsp_template.c File Reference
Functions
static void sbr_sum64x5_c (INTFLOAT *z)
static void sbr_qmf_deint_bfly_c (INTFLOAT *v, const INTFLOAT *src0, const INTFLOAT *src1)
static void sbr_hf_apply_noise_0 (INTFLOAT(*Y)[2], const AAC_FLOAT *s_m, const AAC_FLOAT *q_filt, int noise, int kx, int m_max)
static void sbr_hf_apply_noise_1 (INTFLOAT(*Y)[2], const AAC_FLOAT *s_m, const AAC_FLOAT *q_filt, int noise, int kx, int m_max)
static void sbr_hf_apply_noise_2 (INTFLOAT(*Y)[2], const AAC_FLOAT *s_m, const AAC_FLOAT *q_filt, int noise, int kx, int m_max)
static void sbr_hf_apply_noise_3 (INTFLOAT(*Y)[2], const AAC_FLOAT *s_m, const AAC_FLOAT *q_filt, int noise, int kx, int m_max)
av_cold void AAC_RENAME() ff_sbrdsp_init (SBRDSPContext *s)
Function Documentation
sbr_sum64x5_c()
static void sbr_sum64x5_c (INTFLOAT * z) static
Definition at line 23 of file sbrdsp_template.c.
Referenced by ff_sbrdsp_init().
sbr_qmf_deint_bfly_c()
static void sbr_qmf_deint_bfly_c (INTFLOAT * v, const INTFLOAT * src0, const INTFLOAT * src1) static
Definition at line 32 of file sbrdsp_template.c.
Referenced by ff_sbrdsp_init().
sbr_hf_apply_noise_0()
static void sbr_hf_apply_noise_0 (INTFLOAT(*) Y[2], const AAC_FLOAT * s_m, const AAC_FLOAT * q_filt, int noise, int kx, int m_max) static
Definition at line 41 of file sbrdsp_template.c.
Referenced by ff_sbrdsp_init().
sbr_hf_apply_noise_1()
static void sbr_hf_apply_noise_1 (INTFLOAT(*) Y[2], const AAC_FLOAT * s_m, const AAC_FLOAT * q_filt, int noise, int kx, int m_max) static
Definition at line 48 of file sbrdsp_template.c.
Referenced by ff_sbrdsp_init().
sbr_hf_apply_noise_2()
static void sbr_hf_apply_noise_2 (INTFLOAT(*) Y[2], const AAC_FLOAT * s_m, const AAC_FLOAT * q_filt, int noise, int kx, int m_max) static
Definition at line 56 of file sbrdsp_template.c.
Referenced by ff_sbrdsp_init().
sbr_hf_apply_noise_3()
static void sbr_hf_apply_noise_3 (INTFLOAT(*) Y[2], const AAC_FLOAT * s_m, const AAC_FLOAT * q_filt, int noise, int kx, int m_max) static
Definition at line 63 of file sbrdsp_template.c.
Referenced by ff_sbrdsp_init().
ff_sbrdsp_init()
av_cold void AAC_RENAME() ff_sbrdsp_init (SBRDSPContext * s)
Definition at line 71 of file sbrdsp_template.c.
Referenced by ff_aac_sbr_ctx_init().