FFmpeg: libavcodec/sbrdsp.c File Reference
sbrdsp.c File Reference
#include "aac.h"
#include "config.h"
#include "libavutil/attributes.h"
#include "libavutil/intfloat.h"
#include "sbrdsp.h"
#include "sbrdsp_template.c"
Macros
#define USE_FIXED 0
Functions
static float sbr_sum_square_c (float(*x)[2], int n)
static void sbr_neg_odd_64_c (float *x)
static void sbr_qmf_pre_shuffle_c (float *z)
static void sbr_qmf_post_shuffle_c (float W[32][2], const float *z)
static void sbr_qmf_deint_neg_c (float *v, const float *src)
static void sbr_autocorrelate_c (const float x[40][2], float phi[3][2][2])
static void sbr_hf_gen_c (float(*X_high)[2], const float(*X_low)[2], const float alpha0[2], const float alpha1[2], float bw, int start, int end)
static void sbr_hf_g_filt_c (float(*Y)[2], const float(*X_high)[40][2], const float *g_filt, int m_max, intptr_t ixh)
static av_always_inline void sbr_hf_apply_noise (float(*Y)[2], const float *s_m, const float *q_filt, int noise, float phi_sign0, float phi_sign1, int m_max)
Macro Definition Documentation
USE_FIXED
#define USE_FIXED 0
Definition at line 23 of file sbrdsp.c.
Function Documentation
sbr_sum_square_c()
static float sbr_sum_square_c (float(*) x[2], int n) static
Definition at line 31 of file sbrdsp.c.
Referenced by ff_sbrdsp_init().
sbr_neg_odd_64_c()
static void sbr_neg_odd_64_c (float * x) static
Definition at line 47 of file sbrdsp.c.
Referenced by ff_sbrdsp_init().
sbr_qmf_pre_shuffle_c()
static void sbr_qmf_pre_shuffle_c (float * z) static
Definition at line 57 of file sbrdsp.c.
Referenced by ff_sbrdsp_init().
sbr_qmf_post_shuffle_c()
static void sbr_qmf_post_shuffle_c (float W[32][2], const float * z) static
Definition at line 74 of file sbrdsp.c.
Referenced by ff_sbrdsp_init().
sbr_qmf_deint_neg_c()
static void sbr_qmf_deint_neg_c (float * v, const float * src) static
Definition at line 87 of file sbrdsp.c.
Referenced by ff_sbrdsp_init().
sbr_autocorrelate_c()
static void sbr_autocorrelate_c (const float x[40][2], float phi[3][2][2]) static
Definition at line 135 of file sbrdsp.c.
Referenced by ff_sbrdsp_init(), and sbr_qmf_deint_neg_c().
sbr_hf_gen_c()
static void sbr_hf_gen_c (float(*) X_high[2], const float(*) X_low[2], const float alpha0[2], const float alpha1[2], float bw, int start, int end) static
Definition at line 159 of file sbrdsp.c.
Referenced by ff_sbrdsp_init().
sbr_hf_g_filt_c()
static void sbr_hf_g_filt_c (float(*) Y[2], const float(*) X_high[40][2], const float * g_filt, int m_max, intptr_t ixh) static
Definition at line 187 of file sbrdsp.c.
Referenced by ff_sbrdsp_init().
sbr_hf_apply_noise()
static av_always_inline void sbr_hf_apply_noise (float(*) Y[2], const float * s_m, const float * q_filt, int noise, float phi_sign0, float phi_sign1, int m_max) static
Definition at line 198 of file sbrdsp.c.
Referenced by sbr_hf_apply_noise_0(), sbr_hf_apply_noise_1(), sbr_hf_apply_noise_2(), and sbr_hf_apply_noise_3().