FFmpeg: libavcodec/arm/sbrdsp_init_arm.c File Reference
sbrdsp_init_arm.c File Reference
#include "config.h"
#include "libavutil/arm/cpu.h"
#include "libavutil/attributes.h"
#include "libavcodec/sbrdsp.h"
Functions
void ff_sbr_sum64x5_neon (float *z)
float ff_sbr_sum_square_neon (float(*x)[2], int n)
void ff_sbr_neg_odd_64_neon (float *x)
void ff_sbr_qmf_pre_shuffle_neon (float *z)
void ff_sbr_qmf_post_shuffle_neon (float W[32][2], const float *z)
void ff_sbr_qmf_deint_neg_neon (float *v, const float *src)
void ff_sbr_qmf_deint_bfly_neon (float *v, const float *src0, const float *src1)
void ff_sbr_hf_g_filt_neon (float(*Y)[2], const float(*X_high)[40][2], const float *g_filt, int m_max, intptr_t ixh)
void ff_sbr_hf_gen_neon (float(*X_high)[2], const float(*X_low)[2], const float alpha0[2], const float alpha1[2], float bw, int start, int end)
void ff_sbr_autocorrelate_neon (const float x[40][2], float phi[3][2][2])
void ff_sbr_hf_apply_noise_0_neon (float Y[64][2], const float *s_m, const float *q_filt, int noise, int kx, int m_max)
void ff_sbr_hf_apply_noise_1_neon (float Y[64][2], const float *s_m, const float *q_filt, int noise, int kx, int m_max)
void ff_sbr_hf_apply_noise_2_neon (float Y[64][2], const float *s_m, const float *q_filt, int noise, int kx, int m_max)
void ff_sbr_hf_apply_noise_3_neon (float Y[64][2], const float *s_m, const float *q_filt, int noise, int kx, int m_max)
av_cold void ff_sbrdsp_init_arm (SBRDSPContext *s)
Function Documentation
ff_sbr_sum64x5_neon()
void ff_sbr_sum64x5_neon (float * z)
Referenced by ff_sbrdsp_init_arm().
ff_sbr_sum_square_neon()
float ff_sbr_sum_square_neon (float(*) x[2], int n)
Referenced by ff_sbrdsp_init_arm().
ff_sbr_neg_odd_64_neon()
void ff_sbr_neg_odd_64_neon (float * x)
Referenced by ff_sbrdsp_init_arm().
ff_sbr_qmf_pre_shuffle_neon()
void ff_sbr_qmf_pre_shuffle_neon (float * z)
Referenced by ff_sbrdsp_init_arm().
ff_sbr_qmf_post_shuffle_neon()
void ff_sbr_qmf_post_shuffle_neon (float W[32][2], const float * z)
Referenced by ff_sbrdsp_init_arm().
ff_sbr_qmf_deint_neg_neon()
void ff_sbr_qmf_deint_neg_neon (float * v, const float * src)
Referenced by ff_sbrdsp_init_arm().
ff_sbr_qmf_deint_bfly_neon()
void ff_sbr_qmf_deint_bfly_neon (float * v, const float * src0, const float * src1)
Referenced by ff_sbrdsp_init_arm().
ff_sbr_hf_g_filt_neon()
void ff_sbr_hf_g_filt_neon (float(*) Y[2], const float(*) X_high[40][2], const float * g_filt, int m_max, intptr_t ixh)
Referenced by ff_sbrdsp_init_arm().
ff_sbr_hf_gen_neon()
void ff_sbr_hf_gen_neon (float(*) X_high[2], const float(*) X_low[2], const float alpha0[2], const float alpha1[2], float bw, int start, int end)
Referenced by ff_sbrdsp_init_arm().
ff_sbr_autocorrelate_neon()
void ff_sbr_autocorrelate_neon (const float x[40][2], float phi[3][2][2])
Referenced by ff_sbrdsp_init_arm().
ff_sbr_hf_apply_noise_0_neon()
void ff_sbr_hf_apply_noise_0_neon (float Y[64][2], const float * s_m, const float * q_filt, int noise, int kx, int m_max)
Referenced by ff_sbrdsp_init_arm().
ff_sbr_hf_apply_noise_1_neon()
void ff_sbr_hf_apply_noise_1_neon (float Y[64][2], const float * s_m, const float * q_filt, int noise, int kx, int m_max)
Referenced by ff_sbrdsp_init_arm().
ff_sbr_hf_apply_noise_2_neon()
void ff_sbr_hf_apply_noise_2_neon (float Y[64][2], const float * s_m, const float * q_filt, int noise, int kx, int m_max)
Referenced by ff_sbrdsp_init_arm().
ff_sbr_hf_apply_noise_3_neon()
void ff_sbr_hf_apply_noise_3_neon (float Y[64][2], const float * s_m, const float * q_filt, int noise, int kx, int m_max)
Referenced by ff_sbrdsp_init_arm().
ff_sbrdsp_init_arm()
av_cold void ff_sbrdsp_init_arm (SBRDSPContext * s)
Definition at line 53 of file sbrdsp_init_arm.c.
Referenced by ff_sbrdsp_init().