FFmpeg: libavdevice/sdl2.c File Reference
sdl2.c File Reference
libSDL2 output device
#include <SDL.h>
#include <SDL_thread.h>
#include "libavutil/avstring.h"
#include "libavutil/imgutils.h"
#include "libavutil/opt.h"
#include "libavutil/parseutils.h"
#include "libavutil/pixdesc.h"
#include "libavutil/time.h"
#include "avdevice.h"
Data Structures
struct SDLContext
struct sdl_texture_format_entry
Macros
#define SDL_BASE_FLAGS (SDL_SWSURFACE|SDL_WINDOW_RESIZABLE)
#define OFFSET(x) offsetof(SDLContext,x)
Functions
static void compute_texture_rect (AVFormatContext *s)
static int sdl2_write_trailer (AVFormatContext *s)
static int sdl2_write_header (AVFormatContext *s)
static int sdl2_write_packet (AVFormatContext *s, AVPacket *pkt)
Variables
static const struct sdl_texture_format_entry sdl_texture_format_map []
static const AVOption options []
static const AVClass sdl2_class
AVOutputFormat ff_sdl2_muxer
Detailed Description
libSDL2 output device
Definition in file sdl2.c.
Macro Definition Documentation
SDL_BASE_FLAGS
#define SDL_BASE_FLAGS (SDL_SWSURFACE|SDL_WINDOW_RESIZABLE)
Definition at line 157 of file sdl2.c.
Referenced by sdl2_write_header().
OFFSET
#define OFFSET (x) offsetof(SDLContext,x)
Definition at line 336 of file sdl2.c.
Function Documentation
compute_texture_rect()
static void compute_texture_rect (AVFormatContext * s) static
Definition at line 95 of file sdl2.c.
Referenced by sdl2_write_packet().
sdl2_write_trailer()
static int sdl2_write_trailer (AVFormatContext * s) static
Definition at line 135 of file sdl2.c.
Referenced by sdl2_write_header(), and sdl2_write_packet().
sdl2_write_header()
static int sdl2_write_header (AVFormatContext * s) static
Definition at line 159 of file sdl2.c.
sdl2_write_packet()
static int sdl2_write_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 241 of file sdl2.c.
Variable Documentation
sdl_texture_format_map
const struct sdl_texture_format_entry sdl_texture_format_map[] static
Initial value:
= {
    { AV_PIX_FMT_RGB8,    SDL_PIXELFORMAT_RGB332 },
    { AV_PIX_FMT_RGB444,  SDL_PIXELFORMAT_RGB444 },
    { AV_PIX_FMT_RGB555,  SDL_PIXELFORMAT_RGB555 },
    { AV_PIX_FMT_BGR555,  SDL_PIXELFORMAT_BGR555 },
    { AV_PIX_FMT_RGB565,  SDL_PIXELFORMAT_RGB565 },
    { AV_PIX_FMT_BGR565,  SDL_PIXELFORMAT_BGR565 },
    { AV_PIX_FMT_RGB24,   SDL_PIXELFORMAT_RGB24 },
    { AV_PIX_FMT_BGR24,   SDL_PIXELFORMAT_BGR24 },
    { AV_PIX_FMT_0RGB32,  SDL_PIXELFORMAT_RGB888 },
    { AV_PIX_FMT_0BGR32,  SDL_PIXELFORMAT_BGR888 },
    { AV_PIX_FMT_0BGR,    SDL_PIXELFORMAT_RGBX8888 },
    { AV_PIX_FMT_0RGB,    SDL_PIXELFORMAT_BGRX8888 },
    { AV_PIX_FMT_RGB32,   SDL_PIXELFORMAT_ARGB8888 },
    { AV_PIX_FMT_RGB32_1, SDL_PIXELFORMAT_RGBA8888 },
    { AV_PIX_FMT_BGR32,   SDL_PIXELFORMAT_ABGR8888 },
    { AV_PIX_FMT_BGR32_1, SDL_PIXELFORMAT_BGRA8888 },
    { AV_PIX_FMT_YUV420P, SDL_PIXELFORMAT_IYUV },
    { AV_PIX_FMT_YUYV422, SDL_PIXELFORMAT_YUY2 },
    { AV_PIX_FMT_UYVY422, SDL_PIXELFORMAT_UYVY },
    { AV_PIX_FMT_NONE,    0                },
}
Referenced by sdl2_write_header().
options
const AVOption options[] static
Initial value:
= {
    { "window_title",      "set SDL window title",       OFFSET(window_title), AV_OPT_TYPE_STRING,     { .str = NULL }, 0, 0, AV_OPT_FLAG_ENCODING_PARAM },
    { "window_size",       "set SDL window forced size", OFFSET(window_width), AV_OPT_TYPE_IMAGE_SIZE, { .str = NULL }, 0, 0, AV_OPT_FLAG_ENCODING_PARAM },
    { "window_fullscreen", "set SDL window fullscreen",  OFFSET(window_fullscreen), AV_OPT_TYPE_BOOL,  { .i64 = 0 },    0, 1, AV_OPT_FLAG_ENCODING_PARAM },
    { "window_borderless", "set SDL window border off",  OFFSET(window_borderless), AV_OPT_TYPE_BOOL,  { .i64 = 0 },    0, 1, AV_OPT_FLAG_ENCODING_PARAM },
    { NULL },
}
Definition at line 338 of file sdl2.c.
sdl2_class
const AVClass sdl2_class static
Initial value:
= {
    .class_name = "sdl2 outdev",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
    .category   = AV_CLASS_CATEGORY_DEVICE_VIDEO_OUTPUT,
}
Definition at line 346 of file sdl2.c.
ff_sdl2_muxer
AVOutputFormat ff_sdl2_muxer
Initial value:
= {
    .name           = "sdl,sdl2",
    .long_name      = NULL_IF_CONFIG_SMALL("SDL2 output device"),
    .priv_data_size = sizeof(SDLContext),
    .audio_codec    = AV_CODEC_ID_NONE,
    .video_codec    = AV_CODEC_ID_RAWVIDEO,
    .write_header   = sdl2_write_header,
    .write_packet   = sdl2_write_packet,
    .write_trailer  = sdl2_write_trailer,
    .flags          = AVFMT_NOFILE | AVFMT_VARIABLE_FPS | AVFMT_NOTIMESTAMPS,
    .priv_class     = &sdl2_class,
}
Definition at line 354 of file sdl2.c.