FFmpeg: libavformat/segment.c File Reference
segment.c File Reference
#include <float.h>
#include <time.h>
#include "avformat.h"
#include "avio_internal.h"
#include "internal.h"
#include "libavutil/avassert.h"
#include "libavutil/internal.h"
#include "libavutil/log.h"
#include "libavutil/opt.h"
#include "libavutil/avstring.h"
#include "libavutil/parseutils.h"
#include "libavutil/mathematics.h"
#include "libavutil/timecode.h"
#include "libavutil/time_internal.h"
#include "libavutil/timestamp.h"
Data Structures
struct SegmentListEntry
struct SegmentContext
Macros
#define SEGMENT_LIST_FLAG_CACHE 1
#define SEGMENT_LIST_FLAG_LIVE 2
#define FAIL(err) ret = err; goto end
#define FAIL(err) ret = err; goto end
#define OFFSET(x) offsetof(SegmentContext, x)
#define E AV_OPT_FLAG_ENCODING_PARAM
Enumerations
enum ListType {
LIST_TYPE_UNDEFINED = -1, LIST_TYPE_FLAT = 0, LIST_TYPE_CSV, LIST_TYPE_M3U8,
LIST_TYPE_EXT, LIST_TYPE_FFCONCAT, LIST_TYPE_NB
}
Functions
static void print_csv_escaped_str (AVIOContext *ctx, const char *str)
static int segment_mux_init (AVFormatContext *s)
static int set_segment_filename (AVFormatContext *s)
static int segment_start (AVFormatContext *s, int write_header)
static int segment_list_open (AVFormatContext *s)
static void segment_list_print_entry (AVIOContext *list_ioctx, ListType list_type, const SegmentListEntry *list_entry, void *log_ctx)
static int segment_end (AVFormatContext *s, int write_trailer, int is_last)
static int parse_times (void *log_ctx, int64_t **times, int *nb_times, const char *times_str)
static int parse_frames (void *log_ctx, int **frames, int *nb_frames, const char *frames_str)
static int open_null_ctx (AVIOContext **ctx)
static void close_null_ctxp (AVIOContext **pb)
static int select_reference_stream (AVFormatContext *s)
static void seg_free (AVFormatContext *s)
static int seg_init (AVFormatContext *s)
static int seg_write_header (AVFormatContext *s)
static int seg_write_packet (AVFormatContext *s, AVPacket *pkt)
static int seg_write_trailer (struct AVFormatContext *s)
static int seg_check_bitstream (struct AVFormatContext *s, const AVPacket *pkt)
Variables
static const AVOption options []
static const AVClass seg_class
AVOutputFormat ff_segment_muxer
static const AVClass sseg_class
AVOutputFormat ff_stream_segment_muxer
Macro Definition Documentation
SEGMENT_LIST_FLAG_CACHE
#define SEGMENT_LIST_FLAG_CACHE 1
Definition at line 68 of file segment.c.
Referenced by segment_list_open().
SEGMENT_LIST_FLAG_LIVE
#define SEGMENT_LIST_FLAG_LIVE 2
Definition at line 69 of file segment.c.
FAIL [1/2]
#define FAIL (err) ret = err; goto end
Referenced by parse_frames(), and parse_times().
FAIL [2/2]
#define FAIL (err) ret = err; goto end
OFFSET
#define OFFSET (x) offsetof(SegmentContext, x)
Definition at line 1017 of file segment.c.
E
#define E AV_OPT_FLAG_ENCODING_PARAM
Definition at line 1018 of file segment.c.
Enumeration Type Documentation
ListType
enum ListType
Enumerator
LIST_TYPE_UNDEFINED
LIST_TYPE_FLAT
LIST_TYPE_CSV
LIST_TYPE_M3U8
LIST_TYPE_EXT
deprecated
LIST_TYPE_FFCONCAT
LIST_TYPE_NB
Definition at line 58 of file segment.c.
Function Documentation
print_csv_escaped_str()
static void print_csv_escaped_str (AVIOContext * ctx, const char * str) static
Definition at line 132 of file segment.c.
Referenced by segment_list_print_entry().
segment_mux_init()
static int segment_mux_init (AVFormatContext * s) static
Definition at line 148 of file segment.c.
Referenced by seg_init(), and segment_start().
set_segment_filename()
static int set_segment_filename (AVFormatContext * s) static
Definition at line 192 of file segment.c.
Referenced by seg_init(), and segment_start().
segment_start()
static int segment_start (AVFormatContext * s, int write_header) static
Definition at line 230 of file segment.c.
Referenced by seg_write_packet().
segment_list_open()
static int segment_list_open (AVFormatContext * s) static
Definition at line 275 of file segment.c.
Referenced by seg_init(), and segment_end().
segment_list_print_entry()
static void segment_list_print_entry (AVIOContext * list_ioctx, ListType list_type, const SegmentListEntry * list_entry, void * log_ctx) static
Definition at line 310 of file segment.c.
Referenced by segment_end().
segment_end()
static int segment_end (AVFormatContext * s, int write_trailer, int is_last) static
Definition at line 345 of file segment.c.
Referenced by seg_write_packet(), and seg_write_trailer().
parse_times()
static int parse_times (void * log_ctx, int64_t ** times, int * nb_times, const char * times_str) static
Definition at line 438 of file segment.c.
Referenced by seg_init().
parse_frames()
static int parse_frames (void * log_ctx, int ** frames, int * nb_frames, const char * frames_str) static
Definition at line 496 of file segment.c.
Referenced by seg_init().
open_null_ctx()
static int open_null_ctx (AVIOContext ** ctx) static
Definition at line 555 of file segment.c.
Referenced by seg_init(), and seg_write_trailer().
close_null_ctxp()
static void close_null_ctxp (AVIOContext ** pb) static
Definition at line 569 of file segment.c.
Referenced by seg_write_header(), and seg_write_trailer().
select_reference_stream()
static int select_reference_stream (AVFormatContext * s) static
Definition at line 575 of file segment.c.
Referenced by seg_init().
seg_free()
static void seg_free (AVFormatContext * s) static
Definition at line 632 of file segment.c.
seg_init()
static int seg_init (AVFormatContext * s) static
Definition at line 640 of file segment.c.
seg_write_header()
static int seg_write_header (AVFormatContext * s) static
Definition at line 797 of file segment.c.
seg_write_packet()
static int seg_write_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 842 of file segment.c.
seg_write_trailer()
static int seg_write_trailer (struct AVFormatContext * s) static
Definition at line 955 of file segment.c.
seg_check_bitstream()
static int seg_check_bitstream (struct AVFormatContext * s, const AVPacket * pkt) static
Definition at line 998 of file segment.c.
Variable Documentation
options
const AVOption options[] static
Definition at line 1019 of file segment.c.
Referenced by seg_init(), and segment_start().
seg_class
const AVClass seg_class static
Initial value:
= {
    .class_name = "segment muxer",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1063 of file segment.c.
ff_segment_muxer
AVOutputFormat ff_segment_muxer
Initial value:
= {
    .name           = "segment",
    .long_name      = NULL_IF_CONFIG_SMALL("segment"),
    .priv_data_size = sizeof(SegmentContext),
    .flags          = AVFMT_NOFILE|AVFMT_GLOBALHEADER,
    .init           = seg_init,
    .write_header   = seg_write_header,
    .write_packet   = seg_write_packet,
    .write_trailer  = seg_write_trailer,
    .deinit         = seg_free,
    .check_bitstream = seg_check_bitstream,
    .priv_class     = &seg_class,
}
Definition at line 1070 of file segment.c.
sseg_class
const AVClass sseg_class static
Initial value:
= {
    .class_name = "stream_segment muxer",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1084 of file segment.c.
ff_stream_segment_muxer
AVOutputFormat ff_stream_segment_muxer
Initial value:
= {
    .name           = "stream_segment,ssegment",
    .long_name      = NULL_IF_CONFIG_SMALL("streaming segment muxer"),
    .priv_data_size = sizeof(SegmentContext),
    .flags          = AVFMT_NOFILE,
    .init           = seg_init,
    .write_header   = seg_write_header,
    .write_packet   = seg_write_packet,
    .write_trailer  = seg_write_trailer,
    .deinit         = seg_free,
    .check_bitstream = seg_check_bitstream,
    .priv_class     = &sseg_class,
}
Definition at line 1091 of file segment.c.