FFmpeg: libavcodec/sgidec.c File Reference
sgidec.c File Reference
#include "libavutil/imgutils.h"
#include "libavutil/avassert.h"
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
#include "sgi.h"
Data Structures
struct SgiState
Functions
static int expand_rle_row8 (SgiState *s, uint8_t *out_buf, int len, int pixelstride)
Expand an RLE row into a channel.
static int expand_rle_row16 (SgiState *s, uint16_t *out_buf, int len, int pixelstride)
static int read_rle_sgi (uint8_t *out_buf, SgiState *s)
Read a run length encoded SGI image.
static int read_uncompressed_sgi (unsigned char *out_buf, SgiState *s)
Read an uncompressed SGI image.
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int sgi_decode_init (AVCodecContext *avctx)
Variables
AVCodec ff_sgi_decoder
Function Documentation
expand_rle_row8()
static int expand_rle_row8 (SgiState * s, uint8_t * out_buf, int len, int pixelstride) static
Expand an RLE row into a channel.
Parameters
s the current image state
out_buf Points to one line after the output buffer.
len length of out_buf in bytes
pixelstride pixel stride of input buffer
Returns
size of output in bytes, else return error code.
Definition at line 47 of file sgidec.c.
Referenced by read_rle_sgi().
expand_rle_row16()
static int expand_rle_row16 (SgiState * s, uint16_t * out_buf, int len, int pixelstride) static
Definition at line 85 of file sgidec.c.
Referenced by read_rle_sgi().
read_rle_sgi()
static int read_rle_sgi (uint8_t * out_buf, SgiState * s) static
Read a run length encoded SGI image.
Parameters
out_buf output buffer
s the current image state
Returns
0 if no error, else return error code.
Definition at line 131 of file sgidec.c.
Referenced by decode_frame().
read_uncompressed_sgi()
static int read_uncompressed_sgi (unsigned char * out_buf, SgiState * s) static
Read an uncompressed SGI image.
Parameters
out_buf output buffer
s the current image state
Returns
0 if read success, else return error code.
Definition at line 169 of file sgidec.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 202 of file sgidec.c.
sgi_decode_init()
static av_cold int sgi_decode_init (AVCodecContext * avctx) static
Definition at line 282 of file sgidec.c.
Variable Documentation
ff_sgi_decoder
AVCodec ff_sgi_decoder
Initial value:
= {
    .name           = "sgi",
    .long_name      = NULL_IF_CONFIG_SMALL("SGI image"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_SGI,
    .priv_data_size = sizeof(SgiState),
    .decode         = decode_frame,
    .init           = sgi_decode_init,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 291 of file sgidec.c.