FFmpeg: libavcodec/sheervideo.c File Reference
sheervideo.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "libavutil/intreadwrite.h"
#include "avcodec.h"
#include "get_bits.h"
#include "internal.h"
#include "thread.h"
Data Structures
struct SheerVideoContext
Functions
static void decode_ca4i (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_ca4p (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_ybr10i (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_ybr10 (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_yry10i (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_yry10 (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_ca2i (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_ca2p (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_c82i (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_c82p (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_ybyr (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_byryi (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_byry (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_ybri (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_ybr (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_aybri (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_aybr (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_argxi (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_argx (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_rgbxi (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_rgbx (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_argbi (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_argb (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_rgbi (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static void decode_rgb (AVCodecContext *avctx, AVFrame *p, GetBitContext *gb)
static int build_vlc (VLC *vlc, const uint8_t *len, int count)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int decode_end (AVCodecContext *avctx)
Variables
static const uint8_t l_r_rgb [256]
static const uint8_t l_r_rgbi [256]
static const uint8_t l_g_rgbi [256]
static const uint8_t l_g_rgb [256]
static const uint8_t l_y_ybr [256]
static const uint8_t l_u_ybr [256]
static const uint8_t l_y_ybyr [256]
static const uint8_t l_u_ybyr [256]
static const uint8_t l_y_byry [256]
static const uint8_t l_u_byry [256]
static const uint8_t l_y_ybr10i [1024]
static const uint8_t l_y_ybr10 [1024]
static const uint8_t l_u_ybr10i [1024]
static const uint8_t l_u_ybr10 [1024]
static const uint8_t l_r_rgbx [1024]
static const uint8_t l_g_rgbx [1024]
static const uint8_t l_y_yry10 [1024]
static const uint8_t l_y_yry10i [1024]
static const uint8_t l_u_yry10 [1024]
static const uint8_t l_u_yry10i [1024]
static const uint8_t l_y_ybri [256]
static const uint8_t l_u_ybri [256]
static const uint8_t l_y_byryi [256]
static const uint8_t l_u_byryi [256]
static const uint8_t l_r_rgbxi [1024]
static const uint8_t l_g_rgbxi [1024]
AVCodec ff_sheervideo_decoder
Function Documentation
decode_ca4i()
static void decode_ca4i (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 1109 of file sheervideo.c.
Referenced by decode_frame().
decode_ca4p()
static void decode_ca4p (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 1153 of file sheervideo.c.
Referenced by decode_frame().
decode_ybr10i()
static void decode_ybr10i (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 1241 of file sheervideo.c.
Referenced by decode_frame().
decode_ybr10()
static void decode_ybr10 (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 1280 of file sheervideo.c.
Referenced by decode_frame().
decode_yry10i()
static void decode_yry10i (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 1356 of file sheervideo.c.
Referenced by decode_frame().
decode_yry10()
static void decode_yry10 (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 1398 of file sheervideo.c.
Referenced by decode_frame().
decode_ca2i()
static void decode_ca2i (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 1481 of file sheervideo.c.
Referenced by decode_frame().
decode_ca2p()
static void decode_ca2p (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 1531 of file sheervideo.c.
Referenced by decode_frame().
decode_c82i()
static void decode_c82i (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 1633 of file sheervideo.c.
Referenced by decode_frame().
decode_c82p()
static void decode_c82p (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 1683 of file sheervideo.c.
Referenced by decode_frame().
decode_ybyr()
static void decode_ybyr (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 1785 of file sheervideo.c.
Referenced by decode_frame().
decode_byryi()
static void decode_byryi (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 1868 of file sheervideo.c.
Referenced by decode_frame().
decode_byry()
static void decode_byry (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 1942 of file sheervideo.c.
Referenced by decode_frame().
decode_ybri()
static void decode_ybri (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 2025 of file sheervideo.c.
Referenced by decode_frame().
decode_ybr()
static void decode_ybr (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 2093 of file sheervideo.c.
Referenced by decode_frame().
decode_aybri()
static void decode_aybri (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 2169 of file sheervideo.c.
Referenced by decode_frame().
decode_aybr()
static void decode_aybr (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 2247 of file sheervideo.c.
Referenced by decode_frame().
decode_argxi()
static void decode_argxi (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 2335 of file sheervideo.c.
Referenced by decode_frame().
decode_argx()
static void decode_argx (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 2379 of file sheervideo.c.
Referenced by decode_frame().
decode_rgbxi()
static void decode_rgbxi (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 2467 of file sheervideo.c.
Referenced by decode_frame().
decode_rgbx()
static void decode_rgbx (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 2506 of file sheervideo.c.
Referenced by decode_frame().
decode_argbi()
static void decode_argbi (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 2582 of file sheervideo.c.
Referenced by decode_frame().
decode_argb()
static void decode_argb (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 2648 of file sheervideo.c.
Referenced by decode_frame().
decode_rgbi()
static void decode_rgbi (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 2724 of file sheervideo.c.
Referenced by decode_frame().
decode_rgb()
static void decode_rgb (AVCodecContext * avctx, AVFrame * p, GetBitContext * gb) static
Definition at line 2783 of file sheervideo.c.
Referenced by decode_frame().
build_vlc()
static int build_vlc (VLC * vlc, const uint8_t * len, int count) static
Definition at line 2850 of file sheervideo.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 2873 of file sheervideo.c.
decode_end()
static av_cold int decode_end (AVCodecContext * avctx) static
Definition at line 3143 of file sheervideo.c.
Variable Documentation
l_r_rgb
const uint8_t l_r_rgb[256] static
Initial value:
= {
     3,  3,  4,  4,  5,  5,  5,  6,  6,  6,  7,  7,  7,  7,  7,  8,
     8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10,
    10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 14, 14, 14,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 13, 13, 13,
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 10, 10,
    10, 10, 10, 10, 10, 10,  9,  9,  9,  9,  9,  9,  9,  8,  8,  8,
     8,  8,  8,  7,  7,  7,  7,  7,  6,  6,  6,  5,  5,  4,  4,  4,
}
Definition at line 39 of file sheervideo.c.
Referenced by decode_frame().
l_r_rgbi
const uint8_t l_r_rgbi[256] static
Initial value:
= {
     3,  4,  4,  4,  5,  5,  5,  6,  6,  6,  7,  7,  7,  7,  7,  7,
     8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11,
    11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 13, 13, 13, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 11, 11, 11, 11, 11,
    11, 11, 11, 11, 11, 11, 11, 10, 10, 10, 10, 10, 10, 10, 10, 10,
    10, 10,  9,  9,  9,  9,  9,  9,  9,  8,  8,  8,  8,  8,  8,  8,
     8,  7,  7,  7,  7,  7,  7,  6,  6,  6,  6,  5,  5,  4,  4,  4,
}
Definition at line 58 of file sheervideo.c.
Referenced by decode_frame().
l_g_rgbi
const uint8_t l_g_rgbi[256] static
Initial value:
= {
     1,  3,  4,  5,  6,  7,  7,  8,  9,  9, 10, 10, 10, 10, 11, 11,
    11, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14,
    14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 14,
    14, 14, 14, 14, 14, 13, 13, 13, 13, 13, 13, 12, 12, 12, 12, 12,
    11, 11, 11, 10, 10, 10,  9,  9,  9,  8,  8,  7,  6,  5,  5,  3,
}
Definition at line 77 of file sheervideo.c.
Referenced by decode_frame().
l_g_rgb
const uint8_t l_g_rgb[256] static
Initial value:
= {
     2,  2,  4,  4,  6,  7,  9,  9, 10, 11, 11, 11, 12, 12, 12, 13,
    13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 14, 14, 14, 14, 14, 14, 14, 14, 13, 13,
    13, 13, 12, 12, 12, 11, 11, 11, 10,  9,  9,  8,  6,  4,  3,  3,
}
Definition at line 96 of file sheervideo.c.
Referenced by decode_frame().
l_y_ybr
const uint8_t l_y_ybr[256] static
Initial value:
= {
     3,  3,  4,  4,  5,  5,  6,  6,  6,  7,  7,  7,  7,  7,  8,  8,
     8,  8,  8,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10,
    10, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 11, 11, 11, 11, 11, 11, 11, 11,
    11, 10, 10, 10, 10, 10, 10, 10,  9,  9,  9,  9,  9,  9,  8,  8,
     8,  8,  8,  8,  7,  7,  7,  7,  6,  6,  6,  6,  5,  4,  4,  3,
}
Definition at line 115 of file sheervideo.c.
Referenced by decode_frame().
l_u_ybr
const uint8_t l_u_ybr[256] static
Initial value:
= {
     1,  2,  4,  6,  9, 10, 11, 11, 12, 12, 13, 13, 13, 14, 14, 14,
    14, 14, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 15, 15, 15, 15, 15,
    14, 14, 14, 14, 14, 13, 13, 13, 12, 12, 11, 11, 10,  8,  5,  3,
}
Definition at line 134 of file sheervideo.c.
Referenced by decode_frame().
l_y_ybyr
const uint8_t l_y_ybyr[256] static
Initial value:
= {
     3,  3,  4,  4,  5,  5,  5,  6,  6,  6,  7,  7,  7,  7,  7,  8,
     8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10,
    10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 14,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 13, 13,
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 10, 10,
    10, 10, 10, 10, 10, 10,  9,  9,  9,  9,  9,  9,  9,  8,  8,  8,
     8,  8,  8,  7,  7,  7,  7,  7,  6,  6,  6,  5,  5,  4,  4,  4,
}
Definition at line 153 of file sheervideo.c.
Referenced by decode_frame().
l_u_ybyr
const uint8_t l_u_ybyr[256] static
Initial value:
= {
     1,  2,  4,  6,  8,  9, 10, 10, 11, 11, 12, 12, 12, 13, 13, 14,
    14, 14, 14, 14, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 15, 15, 15, 15, 15, 14, 14,
    14, 14, 13, 13, 13, 12, 12, 11, 11, 10, 10,  9,  8,  7,  6,  3,
}
Definition at line 172 of file sheervideo.c.
Referenced by decode_frame().
l_y_byry
const uint8_t l_y_byry[256] static
Initial value:
= {
     3,  3,  4,  4,  5,  5,  6,  6,  6,  7,  7,  7,  7,  7,  8,  8,
     8,  8,  8,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10,
    10, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 11, 11, 11, 11, 11, 11, 11,
    11, 10, 10, 10, 10, 10, 10, 10,  9,  9,  9,  9,  9,  9,  8,  8,
     8,  8,  8,  8,  7,  7,  7,  7,  6,  6,  6,  6,  5,  4,  4,  3,
}
Definition at line 191 of file sheervideo.c.
Referenced by decode_frame().
l_u_byry
const uint8_t l_u_byry[256] static
Initial value:
= {
     1,  2,  4,  6,  8,  9,  9, 10, 11, 11, 12, 12, 13, 13, 13, 14,
    14, 14, 14, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 15, 15, 15, 15, 15, 15, 14,
    14, 14, 14, 13, 13, 12, 12, 12, 11, 11, 10,  9,  8,  7,  6,  3,
}
Definition at line 210 of file sheervideo.c.
Referenced by decode_frame().
l_y_ybr10i
const uint8_t l_y_ybr10i[1024] static
Definition at line 229 of file sheervideo.c.
Referenced by decode_frame().
l_y_ybr10
const uint8_t l_y_ybr10[1024] static
Definition at line 296 of file sheervideo.c.
Referenced by decode_frame().
l_u_ybr10i
const uint8_t l_u_ybr10i[1024] static
Definition at line 363 of file sheervideo.c.
Referenced by decode_frame().
l_u_ybr10
const uint8_t l_u_ybr10[1024] static
Definition at line 430 of file sheervideo.c.
Referenced by decode_frame().
l_r_rgbx
const uint8_t l_r_rgbx[1024] static
Definition at line 497 of file sheervideo.c.
Referenced by decode_frame().
l_g_rgbx
const uint8_t l_g_rgbx[1024] static
Definition at line 564 of file sheervideo.c.
Referenced by decode_frame().
l_y_yry10
const uint8_t l_y_yry10[1024] static
Definition at line 631 of file sheervideo.c.
Referenced by decode_frame().
l_y_yry10i
const uint8_t l_y_yry10i[1024] static
Definition at line 698 of file sheervideo.c.
Referenced by decode_frame().
l_u_yry10
const uint8_t l_u_yry10[1024] static
Definition at line 765 of file sheervideo.c.
Referenced by decode_frame().
l_u_yry10i
const uint8_t l_u_yry10i[1024] static
Definition at line 832 of file sheervideo.c.
Referenced by decode_frame().
l_y_ybri
const uint8_t l_y_ybri[256] static
Initial value:
= {
     3,  3,  4,  4,  5,  5,  6,  6,  6,  7,  7,  7,  7,  7,  8,  8,
     8,  8,  8,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10,
    10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 14, 14, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 13, 13, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 10, 10,
    10, 10, 10, 10, 10, 10, 10,  9,  9,  9,  9,  9,  9,  9,  8,  8,
     8,  8,  8,  7,  7,  7,  7,  7,  6,  6,  6,  5,  5,  5,  4,  3,
}
Definition at line 899 of file sheervideo.c.
Referenced by decode_frame().
l_u_ybri
const uint8_t l_u_ybri[256] static
Initial value:
= {
     1,  3,  5,  6,  8,  8,  9, 10, 10, 11, 11, 12, 12, 13, 13, 13,
    14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 15, 15, 15, 15, 15, 14, 14, 14, 14, 14,
    14, 13, 13, 13, 12, 12, 11, 11, 10, 10,  9,  8,  8,  6,  5,  2,
}
Definition at line 918 of file sheervideo.c.
Referenced by decode_frame().
l_y_byryi
const uint8_t l_y_byryi[256] static
Initial value:
= {
     3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  7,  7,  7,  7,  8,  8,
     8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10,
    10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 14, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 13, 13, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 10,
    10, 10, 10, 10, 10, 10, 10,  9,  9,  9,  9,  9,  9,  9,  8,  8,
     8,  8,  8,  7,  7,  7,  7,  7,  7,  6,  6,  6,  5,  4,  4,  3,
}
Definition at line 937 of file sheervideo.c.
Referenced by decode_frame().
l_u_byryi
const uint8_t l_u_byryi[256] static
Initial value:
= {
     1,  3,  4,  6,  6,  7,  8,  8,  9,  9, 10, 10, 10, 11, 11, 11,
    12, 12, 12, 12, 13, 13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15,
    15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 15, 15, 15,
    15, 15, 15, 15, 14, 14, 14, 14, 14, 13, 13, 13, 13, 12, 12, 12,
    12, 11, 11, 11, 10, 10, 10,  9,  9,  8,  8,  7,  7,  5,  4,  3,
}
Definition at line 956 of file sheervideo.c.
Referenced by decode_frame().
l_r_rgbxi
const uint8_t l_r_rgbxi[1024] static
Definition at line 975 of file sheervideo.c.
Referenced by decode_frame().
l_g_rgbxi
const uint8_t l_g_rgbxi[1024] static
Definition at line 1042 of file sheervideo.c.
Referenced by decode_frame().
ff_sheervideo_decoder
AVCodec ff_sheervideo_decoder
Initial value:
= {
    .name             = "sheervideo",
    .long_name        = NULL_IF_CONFIG_SMALL("BitJazz SheerVideo"),
    .type             = AVMEDIA_TYPE_VIDEO,
    .id               = AV_CODEC_ID_SHEERVIDEO,
    .priv_data_size   = sizeof(SheerVideoContext),
    .init_thread_copy = ONLY_IF_THREADS_ENABLED(decode_init_thread_copy),
    .close            = decode_end,
    .decode           = decode_frame,
    .capabilities     = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_FRAME_THREADS,
}
Definition at line 3153 of file sheervideo.c.