FFmpeg: tools/sidxindex.c File Reference
sidxindex.c File Reference
#include <stdio.h>
#include <string.h>
#include "libavformat/avformat.h"
#include "libavutil/avstring.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/mathematics.h"
Data Structures
struct Track
struct Tracks
Functions
static int usage (const char *argv0, int ret)
static void set_codec_str (AVCodecParameters *codecpar, char *str, int size)
static int find_sidx (struct Tracks *tracks, int start_index, const char *file)
static int handle_file (struct Tracks *tracks, const char *file)
static void write_time (FILE *out, int64_t time, int decimals, enum AVRounding round)
static int output_mpd (struct Tracks *tracks, const char *filename)
static void clean_tracks (struct Tracks *tracks)
int main (int argc, char **argv)
Function Documentation
usage()
static int usage (const char * argv0, int ret) static
Definition at line 29 of file sidxindex.c.
Referenced by main().
set_codec_str()
static void set_codec_str (AVCodecParameters * codecpar, char * str, int size) static
Definition at line 55 of file sidxindex.c.
Referenced by handle_file().
find_sidx()
static int find_sidx (struct Tracks * tracks, int start_index, const char * file) static
Definition at line 78 of file sidxindex.c.
Referenced by handle_file().
handle_file()
static int handle_file (struct Tracks * tracks, const char * file) static
Definition at line 117 of file sidxindex.c.
Referenced by main().
write_time()
static void write_time (FILE * out, int64_t time, int decimals, enum AVRounding round) static
Definition at line 216 of file sidxindex.c.
Referenced by output_mpd().
output_mpd()
static int output_mpd (struct Tracks * tracks, const char * filename) static
Definition at line 233 of file sidxindex.c.
Referenced by main().
clean_tracks()
static void clean_tracks (struct Tracks * tracks) static
Definition at line 350 of file sidxindex.c.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 360 of file sidxindex.c.