FFmpeg: libavformat/siff.c File Reference
siff.c File Reference
#include "libavutil/channel_layout.h"
#include "libavutil/intreadwrite.h"
#include "avformat.h"
#include "internal.h"
#include "avio_internal.h"
Data Structures
struct SIFFContext
Enumerations
enum SIFFTags {
TAG_SIFF = MKTAG('S', 'I', 'F', 'F'), TAG_BODY = MKTAG('B', 'O', 'D', 'Y'), TAG_VBHD = MKTAG('V', 'B', 'H', 'D'), TAG_SHDR = MKTAG('S', 'H', 'D', 'R'),
TAG_VBV1 = MKTAG('V', 'B', 'V', '1'), TAG_SOUN = MKTAG('S', 'O', 'U', 'N')
}
enum VBFlags {
VB_HAS_GMC = 0x01, VB_HAS_AUDIO = 0x04, VB_HAS_VIDEO = 0x08, VB_HAS_PALETTE = 0x10,
VB_HAS_LENGTH = 0x20, VB_HAS_GMC = 0x01, VB_HAS_AUDIO = 0x04, VB_HAS_VIDEO = 0x08,
VB_HAS_PALETTE = 0x10, VB_HAS_LENGTH = 0x20
}
Functions
static int siff_probe (AVProbeData *p)
static int create_audio_stream (AVFormatContext *s, SIFFContext *c)
static int siff_parse_vbv1 (AVFormatContext *s, SIFFContext *c, AVIOContext *pb)
static int siff_parse_soun (AVFormatContext *s, SIFFContext *c, AVIOContext *pb)
static int siff_read_header (AVFormatContext *s)
static int siff_read_packet (AVFormatContext *s, AVPacket *pkt)
Variables
AVInputFormat ff_siff_demuxer
Enumeration Type Documentation
SIFFTags
enum SIFFTags
Enumerator
TAG_SIFF
TAG_BODY
TAG_VBHD
TAG_SHDR
TAG_VBV1
TAG_SOUN
Definition at line 29 of file siff.c.
VBFlags
enum VBFlags
Enumerator
VB_HAS_GMC
VB_HAS_AUDIO
VB_HAS_VIDEO
VB_HAS_PALETTE
VB_HAS_LENGTH
VB_HAS_GMC
VB_HAS_AUDIO
VB_HAS_VIDEO
VB_HAS_PALETTE
VB_HAS_LENGTH
Definition at line 38 of file siff.c.
Function Documentation
siff_probe()
static int siff_probe (AVProbeData * p) static
Definition at line 65 of file siff.c.
create_audio_stream()
static int create_audio_stream (AVFormatContext * s, SIFFContext * c) static
Definition at line 75 of file siff.c.
Referenced by siff_parse_soun(), and siff_parse_vbv1().
siff_parse_vbv1()
static int siff_parse_vbv1 (AVFormatContext * s, SIFFContext * c, AVIOContext * pb) static
Definition at line 92 of file siff.c.
Referenced by siff_read_header().
siff_parse_soun()
static int siff_parse_soun (AVFormatContext * s, SIFFContext * c, AVIOContext * pb) static
Definition at line 145 of file siff.c.
Referenced by siff_read_header().
siff_read_header()
static int siff_read_header (AVFormatContext * s) static
Definition at line 162 of file siff.c.
siff_read_packet()
static int siff_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 192 of file siff.c.
Variable Documentation
ff_siff_demuxer
AVInputFormat ff_siff_demuxer
Initial value:
= {
    .name           = "siff",
    .long_name      = NULL_IF_CONFIG_SMALL("Beam Software SIFF"),
    .priv_data_size = sizeof(SIFFContext),
    .read_probe     = siff_probe,
    .read_header    = siff_read_header,
    .read_packet    = siff_read_packet,
    .extensions     = "vb,son",
}
Definition at line 250 of file siff.c.