FFmpeg: libavcodec/mips/simple_idct_msa.c File Reference
simple_idct_msa.c File Reference
#include "libavutil/mips/generic_macros_msa.h"
#include "idctdsp_mips.h"
Functions
static void simple_idct_msa (int16_t *block)
static void simple_idct_put_msa (uint8_t *dst, int32_t dst_stride, int16_t *block)
static void simple_idct_add_msa (uint8_t *dst, int32_t dst_stride, int16_t *block)
void ff_simple_idct_msa (int16_t *block)
void ff_simple_idct_put_msa (uint8_t *dst, int32_t dst_stride, int16_t *block)
void ff_simple_idct_add_msa (uint8_t *dst, int32_t dst_stride, int16_t *block)
Function Documentation
simple_idct_msa()
static void simple_idct_msa (int16_t * block) static
Definition at line 24 of file simple_idct_msa.c.
Referenced by ff_simple_idct_msa().
simple_idct_put_msa()
static void simple_idct_put_msa (uint8_t * dst, int32_t dst_stride, int16_t * block) static
Definition at line 185 of file simple_idct_msa.c.
Referenced by ff_simple_idct_put_msa().
simple_idct_add_msa()
static void simple_idct_add_msa (uint8_t * dst, int32_t dst_stride, int16_t * block) static
Definition at line 370 of file simple_idct_msa.c.
Referenced by ff_simple_idct_add_msa().
ff_simple_idct_msa()
void ff_simple_idct_msa (int16_t * block)
Definition at line 560 of file simple_idct_msa.c.
ff_simple_idct_put_msa()
void ff_simple_idct_put_msa (uint8_t * dst, int32_t dst_stride, int16_t * block)
Definition at line 565 of file simple_idct_msa.c.
ff_simple_idct_add_msa()
void ff_simple_idct_add_msa (uint8_t * dst, int32_t dst_stride, int16_t * block)
Definition at line 570 of file simple_idct_msa.c.