FFmpeg: libavcodec/simple_idct_template.c File Reference
simple_idct_template.c File Reference
simpleidct in C.
#include "simple_idct.h"
#include "bit_depth_template.c"
Macros
#define IDCT_COLS
Functions
static void FUNC() idctRowCondDC (int16_t *row, int extra_shift)
static void FUNC() idctSparseColPut (pixel *dest, int line_size, int16_t *col)
static void FUNC() idctSparseColAdd (pixel *dest, int line_size, int16_t *col)
static void FUNC() idctSparseCol (int16_t *col)
void FUNC() ff_simple_idct_put (uint8_t *dest_, int line_size, int16_t *block)
void FUNC() ff_simple_idct_add (uint8_t *dest_, int line_size, int16_t *block)
void FUNC() ff_simple_idct (int16_t *block)
Detailed Description
simpleidct in C.
Definition in file simple_idct_template.c.
Macro Definition Documentation
IDCT_COLS
#define IDCT_COLS
Definition at line 200 of file simple_idct_template.c.
Referenced by idctSparseCol(), idctSparseColAdd(), and idctSparseColPut().
Function Documentation
idctRowCondDC()
static void FUNC() idctRowCondDC (int16_t * row, int extra_shift) inline static
Definition at line 112 of file simple_idct_template.c.
Referenced by ff_simple_idct(), ff_simple_idct_add(), and ff_simple_idct_put().
idctSparseColPut()
static void FUNC() idctSparseColPut (pixel * dest, int line_size, int16_t * col) inline static
Definition at line 253 of file simple_idct_template.c.
Referenced by ff_simple_idct_put().
idctSparseColAdd()
static void FUNC() idctSparseColAdd (pixel * dest, int line_size, int16_t * col) inline static
Definition at line 277 of file simple_idct_template.c.
Referenced by ff_simple_idct_add().
idctSparseCol()
static void FUNC() idctSparseCol (int16_t * col) inline static
Definition at line 301 of file simple_idct_template.c.
Referenced by ff_simple_idct().
ff_simple_idct_put()
void FUNC() ff_simple_idct_put (uint8_t * dest_, int line_size, int16_t * block)
Definition at line 319 of file simple_idct_template.c.
ff_simple_idct_add()
void FUNC() ff_simple_idct_add (uint8_t * dest_, int line_size, int16_t * block)
Definition at line 333 of file simple_idct_template.c.
ff_simple_idct()
void FUNC() ff_simple_idct (int16_t * block)
Definition at line 347 of file simple_idct_template.c.