FFmpeg: libavcodec/simple_idct.h File Reference
simple_idct.h File Reference
simple idct header.
#include <stdint.h>
Functions
void ff_simple_idct_put_8 (uint8_t *dest, int line_size, int16_t *block)
void ff_simple_idct_add_8 (uint8_t *dest, int line_size, int16_t *block)
void ff_simple_idct_8 (int16_t *block)
void ff_simple_idct_put_10 (uint8_t *dest, int line_size, int16_t *block)
void ff_simple_idct_add_10 (uint8_t *dest, int line_size, int16_t *block)
void ff_simple_idct_10 (int16_t *block)
void ff_simple_idct_put_12 (uint8_t *dest, int line_size, int16_t *block)
void ff_simple_idct_add_12 (uint8_t *dest, int line_size, int16_t *block)
void ff_simple_idct_12 (int16_t *block)
void ff_prores_idct (int16_t *block, const int16_t *qmat)
Special version of ff_simple_idct_10() which does dequantization and scales by a factor of 2 more between the two IDCTs to account for larger scale of input coefficients.
void ff_simple_idct248_put (uint8_t *dest, int line_size, int16_t *block)
void ff_simple_idct84_add (uint8_t *dest, int line_size, int16_t *block)
void ff_simple_idct48_add (uint8_t *dest, int line_size, int16_t *block)
void ff_simple_idct44_add (uint8_t *dest, int line_size, int16_t *block)
Detailed Description
simple idct header.
Definition in file simple_idct.h.
Function Documentation
ff_simple_idct_put_8()
void ff_simple_idct_put_8 (uint8_t * dest, int line_size, int16_t * block)
Referenced by ff_idctdsp_init().
ff_simple_idct_add_8()
void ff_simple_idct_add_8 (uint8_t * dest, int line_size, int16_t * block)
Referenced by ff_idctdsp_init(), and ff_vc1_decode_sequence_header().
ff_simple_idct_8()
void ff_simple_idct_8 (int16_t * block)
Referenced by ff_idctdsp_init(), ff_vc1_decode_sequence_header(), and quant_psnr8x8_c().
ff_simple_idct_put_10()
void ff_simple_idct_put_10 (uint8_t * dest, int line_size, int16_t * block)
Referenced by ff_idctdsp_init().
ff_simple_idct_add_10()
void ff_simple_idct_add_10 (uint8_t * dest, int line_size, int16_t * block)
Referenced by ff_idctdsp_init().
ff_simple_idct_10()
void ff_simple_idct_10 (int16_t * block)
Referenced by ff_idctdsp_init().
ff_simple_idct_put_12()
void ff_simple_idct_put_12 (uint8_t * dest, int line_size, int16_t * block)
Referenced by ff_idctdsp_init().
ff_simple_idct_add_12()
void ff_simple_idct_add_12 (uint8_t * dest, int line_size, int16_t * block)
Referenced by ff_idctdsp_init().
ff_simple_idct_12()
void ff_simple_idct_12 (int16_t * block)
Referenced by ff_idctdsp_init().
ff_prores_idct()
void ff_prores_idct (int16_t * block, const int16_t * qmat)
Special version of ff_simple_idct_10() which does dequantization and scales by a factor of 2 more between the two IDCTs to account for larger scale of input coefficients.
Definition at line 230 of file simple_idct.c.
Referenced by ff_prores_idct_wrap(), and prores_idct_put_c().
ff_simple_idct248_put()
void ff_simple_idct248_put (uint8_t * dest, int line_size, int16_t * block)
Definition at line 97 of file simple_idct.c.
Referenced by dvvideo_decode_init(), and main().
ff_simple_idct84_add()
void ff_simple_idct84_add (uint8_t * dest, int line_size, int16_t * block)
Definition at line 185 of file simple_idct.c.
Referenced by ff_vc1_decode_sequence_header(), and wmv2_add_block().
ff_simple_idct48_add()
void ff_simple_idct48_add (uint8_t * dest, int line_size, int16_t * block)
Definition at line 200 of file simple_idct.c.
Referenced by ff_vc1_decode_sequence_header(), and wmv2_add_block().
ff_simple_idct44_add()
void ff_simple_idct44_add (uint8_t * dest, int line_size, int16_t * block)
Definition at line 215 of file simple_idct.c.
Referenced by ff_vc1_decode_sequence_header().