FFmpeg: libavcodec/sinewin_tablegen.h File Reference
sinewin_tablegen.h File Reference
#include <assert.h>
#include <math.h>
#include "libavcodec/aac_defines.h"
#include "libavutil/attributes.h"
#include "libavutil/common.h"
Macros
#define SIN_FIX(a) a
Functions
SINETABLE (32)
SINETABLE (64)
SINETABLE (128)
SINETABLE (256)
SINETABLE (512)
SINETABLE (1024)
SINETABLE (2048)
SINETABLE (4096)
SINETABLE (8192)
SINETABLE_CONST INTFLOAT *const AAC_RENAME (ff_sine_windows)[]
av_cold void AAC_RENAME() ff_sine_window_init (INTFLOAT *window, int n)
Generate a sine window.
av_cold void AAC_RENAME() ff_init_ff_sine_windows (int index)
initialize the specified entry of ff_sine_windows
Macro Definition Documentation
SIN_FIX
#define SIN_FIX (a) a
Definition at line 55 of file sinewin_tablegen.h.
Referenced by ff_sine_window_init().
Function Documentation
SINETABLE() [1/9]
SINETABLE (32)
SINETABLE() [2/9]
SINETABLE (64)
SINETABLE() [3/9]
SINETABLE (128)
SINETABLE() [4/9]
SINETABLE (256)
SINETABLE() [5/9]
SINETABLE (512)
SINETABLE() [6/9]
SINETABLE (1024)
SINETABLE() [7/9]
SINETABLE (2048)
SINETABLE() [8/9]
SINETABLE (4096)
SINETABLE() [9/9]
SINETABLE (8192)
AAC_RENAME()
SINETABLE_CONST INTFLOAT* const AAC_RENAME (ff_sine_windows)
Referenced by ff_init_ff_sine_windows().
ff_sine_window_init()
av_cold void AAC_RENAME() ff_sine_window_init (INTFLOAT * window, int n)
Generate a sine window.
Parameters
window pointer to half window
n size of half window
Definition at line 66 of file sinewin_tablegen.h.
Referenced by ff_init_ff_sine_windows(), imc_decode_init(), init_cook_mlt(), and wmavoice_decode_init().
ff_init_ff_sine_windows()
av_cold void AAC_RENAME() ff_init_ff_sine_windows (int index)
initialize the specified entry of ff_sine_windows
Definition at line 72 of file sinewin_tablegen.h.
Referenced by aac_static_table_init(), atrac1_decode_init(), decode_init(), dsp_init(), encode_init(), ff_atrac3p_init_imdct(), ff_wma_init(), init_mdct_win(), and main().