FFmpeg: libswscale/slice.c File Reference
slice.c File Reference
#include "swscale_internal.h"
Functions
static void free_lines (SwsSlice *s)
static int alloc_lines (SwsSlice *s, int size, int width)
static int alloc_slice (SwsSlice *s, enum AVPixelFormat fmt, int lumLines, int chrLines, int h_sub_sample, int v_sub_sample, int ring)
static void free_slice (SwsSlice *s)
int ff_rotate_slice (SwsSlice *s, int lum, int chr)
int ff_init_slice_from_src (SwsSlice *s, uint8_t *src[4], int stride[4], int srcW, int lumY, int lumH, int chrY, int chrH, int relative)
static void fill_ones (SwsSlice *s, int n, int is16bit)
static void get_min_buffer_size (SwsContext *c, int *out_lum_size, int *out_chr_size)
int ff_init_filters (SwsContext *c)
int ff_free_filters (SwsContext *c)
Function Documentation
free_lines()
static void free_lines (SwsSlice * s) static
Definition at line 23 of file slice.c.
Referenced by alloc_lines(), and free_slice().
alloc_lines()
static int alloc_lines (SwsSlice * s, int size, int width) static
Definition at line 45 of file slice.c.
Referenced by ff_init_filters().
alloc_slice()
static int alloc_slice (SwsSlice * s, enum AVPixelFormat fmt, int lumLines, int chrLines, int h_sub_sample, int v_sub_sample, int ring) static
Definition at line 78 of file slice.c.
Referenced by ff_init_filters().
free_slice()
static void free_slice (SwsSlice * s) static
Definition at line 106 of file slice.c.
Referenced by ff_free_filters().
ff_rotate_slice()
int ff_rotate_slice (SwsSlice * s, int lum, int chr)
Definition at line 119 of file slice.c.
Referenced by swscale().
ff_init_slice_from_src()
int ff_init_slice_from_src (SwsSlice * s, uint8_t * src[4], int stride[4], int srcW, int lumY, int lumH, int chrY, int chrH, int relative)
Definition at line 147 of file slice.c.
Referenced by swscale().
fill_ones()
static void fill_ones (SwsSlice * s, int n, int is16bit) static
Definition at line 192 of file slice.c.
Referenced by ff_init_filters().
get_min_buffer_size()
static void get_min_buffer_size (SwsContext * c, int * out_lum_size, int * out_chr_size) static
Definition at line 220 of file slice.c.
Referenced by ff_init_filters().
ff_init_filters()
int ff_init_filters (SwsContext * c)
Definition at line 249 of file slice.c.
Referenced by sws_init_context().
ff_free_filters()
int ff_free_filters (SwsContext * c)
Definition at line 377 of file slice.c.
Referenced by ff_init_filters(), sws_freeContext(), and sws_init_context().