FFmpeg: libavformat/smoothstreamingenc.c File Reference
smoothstreamingenc.c File Reference
#include "config.h"
#include <float.h>
#include "avformat.h"
#include "avio_internal.h"
#include "internal.h"
#include "os_support.h"
#include "avc.h"
#include "url.h"
#include "isom.h"
#include "libavutil/opt.h"
#include "libavutil/avstring.h"
#include "libavutil/file.h"
#include "libavutil/mathematics.h"
#include "libavutil/intreadwrite.h"
Data Structures
struct Fragment
struct OutputStream
struct SmoothStreamingContext
Macros
#define OFFSET(x) offsetof(SmoothStreamingContext, x)
#define E AV_OPT_FLAG_ENCODING_PARAM
Functions
static int ism_write (void *opaque, uint8_t *buf, int buf_size)
static int64_t ism_seek (void *opaque, int64_t offset, int whence)
static void get_private_data (OutputStream *os)
static void ism_free (AVFormatContext *s)
static void output_chunk_list (OutputStream *os, AVIOContext *out, int final, int skip, int window_size)
static int write_manifest (AVFormatContext *s, int final)
static int ism_write_header (AVFormatContext *s)
static int parse_fragment (AVFormatContext *s, const char *filename, int64_t *start_ts, int64_t *duration, int64_t *moof_size, int64_t size)
static int add_fragment (OutputStream *os, const char *file, const char *infofile, int64_t start_time, int64_t duration, int64_t start_pos, int64_t size)
static int copy_moof (AVFormatContext *s, const char *infile, const char *outfile, int64_t size)
static int ism_flush (AVFormatContext *s, int final)
static int ism_write_packet (AVFormatContext *s, AVPacket *pkt)
static int ism_write_trailer (AVFormatContext *s)
Variables
static const AVOption options []
static const AVClass ism_class
AVOutputFormat ff_smoothstreaming_muxer
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(SmoothStreamingContext, x)
Definition at line 621 of file smoothstreamingenc.c.
E
#define E AV_OPT_FLAG_ENCODING_PARAM
Definition at line 622 of file smoothstreamingenc.c.
Function Documentation
ism_write()
static int ism_write (void * opaque, uint8_t * buf, int buf_size) static
Definition at line 82 of file smoothstreamingenc.c.
Referenced by ism_write_header().
ism_seek()
static int64_t ism_seek (void * opaque, int64_t offset, int whence) static
Definition at line 95 of file smoothstreamingenc.c.
Referenced by ism_write_header().
get_private_data()
static void get_private_data (OutputStream * os) static
Definition at line 147 of file smoothstreamingenc.c.
Referenced by ism_write_header().
ism_free()
static void ism_free (AVFormatContext * s) static
Definition at line 170 of file smoothstreamingenc.c.
Referenced by ism_write_header(), and ism_write_trailer().
output_chunk_list()
static void output_chunk_list (OutputStream * os, AVIOContext * out, int final, int skip, int window_size) static
Definition at line 196 of file smoothstreamingenc.c.
Referenced by write_manifest().
write_manifest()
static int write_manifest (AVFormatContext * s, int final) static
Definition at line 216 of file smoothstreamingenc.c.
Referenced by ism_flush(), and ism_write_header().
ism_write_header()
static int ism_write_header (AVFormatContext * s) static
Definition at line 292 of file smoothstreamingenc.c.
parse_fragment()
static int parse_fragment (AVFormatContext * s, const char * filename, int64_t * start_ts, int64_t * duration, int64_t * moof_size, int64_t size) static
Definition at line 410 of file smoothstreamingenc.c.
Referenced by ism_flush().
add_fragment()
static int add_fragment (OutputStream * os, const char * file, const char * infofile, int64_t start_time, int64_t duration, int64_t start_pos, int64_t size) static
Definition at line 460 of file smoothstreamingenc.c.
Referenced by ism_flush().
copy_moof()
static int copy_moof (AVFormatContext * s, const char * infile, const char * outfile, int64_t size) static
Definition at line 488 of file smoothstreamingenc.c.
Referenced by ism_flush().
ism_flush()
static int ism_flush (AVFormatContext * s, int final) static
Definition at line 515 of file smoothstreamingenc.c.
Referenced by ism_write_packet(), and ism_write_trailer().
ism_write_packet()
static int ism_write_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 580 of file smoothstreamingenc.c.
ism_write_trailer()
static int ism_write_trailer (AVFormatContext * s) static
Definition at line 605 of file smoothstreamingenc.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "window_size", "number of fragments kept in the manifest", OFFSET(window_size), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, INT_MAX, E },
    { "extra_window_size", "number of fragments kept outside of the manifest before removing from disk", OFFSET(extra_window_size), AV_OPT_TYPE_INT, { .i64 = 5 }, 0, INT_MAX, E },
    { "lookahead_count", "number of lookahead fragments", OFFSET(lookahead_count), AV_OPT_TYPE_INT, { .i64 = 2 }, 0, INT_MAX, E },
    { "min_frag_duration", "minimum fragment duration (in microseconds)", OFFSET(min_frag_duration), AV_OPT_TYPE_INT64, { .i64 = 5000000 }, 0, INT_MAX, E },
    { "remove_at_exit", "remove all fragments when finished", OFFSET(remove_at_exit), AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, E },
    { NULL },
}
Definition at line 623 of file smoothstreamingenc.c.
ism_class
const AVClass ism_class static
Initial value:
= {
    .class_name = "smooth streaming muxer",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 632 of file smoothstreamingenc.c.
ff_smoothstreaming_muxer
AVOutputFormat ff_smoothstreaming_muxer
Initial value:
= {
    .name           = "smoothstreaming",
    .long_name      = NULL_IF_CONFIG_SMALL("Smooth Streaming Muxer"),
    .priv_data_size = sizeof(SmoothStreamingContext),
    .audio_codec    = AV_CODEC_ID_AAC,
    .video_codec    = AV_CODEC_ID_H264,
    .flags          = AVFMT_GLOBALHEADER | AVFMT_NOFILE,
    .write_header   = ism_write_header,
    .write_packet   = ism_write_packet,
    .write_trailer  = ism_write_trailer,
    .codec_tag      = (const AVCodecTag* const []){ ff_mp4_obj_type, 0 },
    .priv_class     = &ism_class,
}
Definition at line 640 of file smoothstreamingenc.c.