FFmpeg: libavcodec/smvjpegdec.c File Reference
smvjpegdec.c File Reference
SMV JPEG decoder.
#include "avcodec.h"
#include "libavutil/opt.h"
#include "libavutil/imgutils.h"
#include "mjpegdec.h"
#include "internal.h"
Data Structures
struct SMVJpegDecodeContext
Functions
static void smv_img_pnt_plane (uint8_t **dst, uint8_t *src, int src_linesize, int height, int nlines)
static void smv_img_pnt (uint8_t *dst_data[4], uint8_t *src_data[4], const int src_linesizes[4], enum AVPixelFormat pix_fmt, int width, int height, int nlines)
static av_cold int smvjpeg_decode_end (AVCodecContext *avctx)
static av_cold int smvjpeg_decode_init (AVCodecContext *avctx)
static int smvjpeg_decode_frame (AVCodecContext *avctx, void *data, int *data_size, AVPacket *avpkt)
Variables
static const AVClass smvjpegdec_class
AVCodec ff_smvjpeg_decoder
Detailed Description
SMV JPEG decoder.
Definition in file smvjpegdec.c.
Function Documentation
smv_img_pnt_plane()
static void smv_img_pnt_plane (uint8_t ** dst, uint8_t * src, int src_linesize, int height, int nlines) inline static
Definition at line 42 of file smvjpegdec.c.
Referenced by smv_img_pnt().
smv_img_pnt()
static void smv_img_pnt (uint8_t * dst_data[4], uint8_t * src_data[4], const int src_linesizes[4], enum AVPixelFormat pix_fmt, int width, int height, int nlines) inline static
Definition at line 51 of file smvjpegdec.c.
Referenced by smvjpeg_decode_frame().
smvjpeg_decode_end()
static av_cold int smvjpeg_decode_end (AVCodecContext * avctx) static
Definition at line 78 of file smvjpegdec.c.
Referenced by smvjpeg_decode_init().
smvjpeg_decode_init()
static av_cold int smvjpeg_decode_init (AVCodecContext * avctx) static
Definition at line 92 of file smvjpegdec.c.
smvjpeg_decode_frame()
static int smvjpeg_decode_frame (AVCodecContext * avctx, void * data, int * data_size, AVPacket * avpkt) static
Definition at line 145 of file smvjpegdec.c.
Variable Documentation
smvjpegdec_class
const AVClass smvjpegdec_class static
Initial value:
= {
    .class_name = "SMVJPEG decoder",
    .item_name  = av_default_item_name,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 210 of file smvjpegdec.c.
ff_smvjpeg_decoder
AVCodec ff_smvjpeg_decoder
Initial value:
= {
    .name           = "smvjpeg",
    .long_name      = NULL_IF_CONFIG_SMALL("SMV JPEG"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_SMVJPEG,
    .priv_data_size = sizeof(SMVJpegDecodeContext),
    .init           = smvjpeg_decode_init,
    .close          = smvjpeg_decode_end,
    .decode         = smvjpeg_decode_frame,
    .priv_class     = &smvjpegdec_class,
}
Definition at line 216 of file smvjpegdec.c.