FFmpeg: libavdevice/sndio.c File Reference
sndio.c File Reference
#include <stdint.h>
#include <sndio.h>
#include "avdevice.h"
Functions
static void movecb (void *addr, int delta)
av_cold int ff_sndio_open (AVFormatContext *s1, int is_output, const char *audio_device)
int ff_sndio_close (SndioData *s)
Function Documentation
movecb()
static void movecb (void * addr, int delta) inline static
Definition at line 29 of file sndio.c.
Referenced by ff_sndio_open().
ff_sndio_open()
av_cold int ff_sndio_open (AVFormatContext * s1, int is_output, const char * audio_device)
Definition at line 36 of file sndio.c.
Referenced by audio_read_header(), and audio_write_header().
ff_sndio_close()
int ff_sndio_close (SndioData * s)
Definition at line 112 of file sndio.c.
Referenced by audio_read_close(), and audio_write_trailer().