FFmpeg: libavcodec/snow.c File Reference
snow.c File Reference
#include "libavutil/intmath.h"
#include "libavutil/log.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "me_cmp.h"
#include "snow_dwt.h"
#include "internal.h"
#include "snow.h"
#include "snowdata.h"
#include "rangecoder.h"
#include "mathops.h"
#include "h263.h"
Macros
#define MC_STRIDE(x) (needs[x] ? 64 : stride)
#define mca(dx, dy, b_w)
#define mcf(dx, dy)
#define mcfh(dx, dy)
#define USE_HALFPEL_PLANE 0
Functions
void ff_snow_inner_add_yblock (const uint8_t *obmc, const int obmc_stride, uint8_t **block, int b_w, int b_h, int src_x, int src_y, int src_stride, slice_buffer *sb, int add, uint8_t *dst8)
int ff_snow_get_buffer (SnowContext *s, AVFrame *frame)
void ff_snow_reset_contexts (SnowContext *s)
int ff_snow_alloc_blocks (SnowContext *s)
static av_cold void init_qexp (void)
static void mc_block (Plane *p, uint8_t *dst, const uint8_t *src, int stride, int b_w, int b_h, int dx, int dy)
void ff_snow_pred_block (SnowContext *s, uint8_t *dst, uint8_t *tmp, ptrdiff_t stride, int sx, int sy, int b_w, int b_h, const BlockNode *block, int plane_index, int w, int h)
mca (mca(0, mca(0, 16)
int ff_snow_common_init_after_header (AVCodecContext *avctx)
static int halfpel_interpol (SnowContext *s, uint8_t *halfpel[4][4], AVFrame *frame)
void ff_snow_release_buffer (AVCodecContext *avctx)
int ff_snow_frame_start (SnowContext *s)
av_cold void ff_snow_common_end (SnowContext *s)
Macro Definition Documentation
MC_STRIDE
#define MC_STRIDE (x) (needs[x] ? 64 : stride)
Referenced by mc_block().
mca
#define mca (dx, dy, b_w)
Value:
static void mc_block_hpel ## dx ## dy ## b_w(uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int h){\
    av_assert2(h==b_w);\
    mc_block(NULL, dst, src-(HTAPS_MAX/2-1)-(HTAPS_MAX/2-1)*stride, stride, b_w, b_w, dx, dy);\
}
Definition at line 415 of file snow.c.
mcf
#define mcf (dx, dy)
Value:
s->qdsp.put_qpel_pixels_tab       [0][dy+dx/4]=\
    s->qdsp.put_no_rnd_qpel_pixels_tab[0][dy+dx/4]=\
        s->h264qpel.put_h264_qpel_pixels_tab[0][dy+dx/4];\
    s->qdsp.put_qpel_pixels_tab       [1][dy+dx/4]=\
    s->qdsp.put_no_rnd_qpel_pixels_tab[1][dy+dx/4]=\
        s->h264qpel.put_h264_qpel_pixels_tab[1][dy+dx/4];
Referenced by mca().
mcfh
#define mcfh (dx, dy)
Value:
s->hdsp.put_pixels_tab       [0][dy/4+dx/8]=\
    s->hdsp.put_no_rnd_pixels_tab[0][dy/4+dx/8]=\
        mc_block_hpel ## dx ## dy ## 16;\
    s->hdsp.put_pixels_tab       [1][dy/4+dx/8]=\
    s->hdsp.put_no_rnd_pixels_tab[1][dy/4+dx/8]=\
        mc_block_hpel ## dx ## dy ## 8;
Referenced by mca().
USE_HALFPEL_PLANE
#define USE_HALFPEL_PLANE 0
Definition at line 586 of file snow.c.
Referenced by ff_snow_frame_start().
Function Documentation
ff_snow_inner_add_yblock()
void ff_snow_inner_add_yblock (const uint8_t * obmc, const int obmc_stride, uint8_t ** block, int b_w, int b_h, int src_x, int src_y, int src_stride, slice_buffer * sb, int add, uint8_t * dst8)
Definition at line 36 of file snow.c.
Referenced by ff_dwt_init().
ff_snow_get_buffer()
int ff_snow_get_buffer (SnowContext * s, AVFrame * frame)
Definition at line 69 of file snow.c.
Referenced by encode_init(), ff_snow_frame_start(), and snow_horizontal_compose_liftS_lead_out().
ff_snow_reset_contexts()
void ff_snow_reset_contexts (SnowContext * s)
Definition at line 96 of file snow.c.
Referenced by decode_header(), encode_header(), and snow_horizontal_compose_liftS_lead_out().
ff_snow_alloc_blocks()
int ff_snow_alloc_blocks (SnowContext * s)
Definition at line 110 of file snow.c.
Referenced by decode_frame(), encode_init(), and snow_horizontal_compose_liftS_lead_out().
init_qexp()
static av_cold void init_qexp (void) static
Definition at line 125 of file snow.c.
Referenced by mca().
mc_block()
static void mc_block (Plane * p, uint8_t * dst, const uint8_t * src, int stride, int b_w, int b_h, int dx, int dy) static
Definition at line 134 of file snow.c.
Referenced by ff_snow_pred_block().
ff_snow_pred_block()
void ff_snow_pred_block (SnowContext * s, uint8_t * dst, uint8_t * tmp, ptrdiff_t stride, int sx, int sy, int b_w, int b_h, const BlockNode * block, int plane_index, int w, int h)
Definition at line 327 of file snow.c.
Referenced by add_yblock(), get_block_rd(), and snow_horizontal_compose_liftS_lead_out().
mca()
mca (mca(0, mca(0, 16)
Definition at line 421 of file snow.c.
ff_snow_common_init_after_header()
int ff_snow_common_init_after_header (AVCodecContext * avctx)
Definition at line 514 of file snow.c.
Referenced by decode_frame(), encode_frame(), and snow_horizontal_compose_liftS_lead_out().
halfpel_interpol()
static int halfpel_interpol (SnowContext * s, uint8_t * halfpel[4][4], AVFrame * frame) static
Definition at line 588 of file snow.c.
Referenced by ff_snow_frame_start().
ff_snow_release_buffer()
void ff_snow_release_buffer (AVCodecContext * avctx)
Definition at line 640 of file snow.c.
Referenced by decode_frame(), encode_frame(), ff_snow_frame_start(), and snow_horizontal_compose_liftS_lead_out().
ff_snow_frame_start()
int ff_snow_frame_start (SnowContext * s)
Definition at line 655 of file snow.c.
Referenced by decode_frame(), encode_frame(), and snow_horizontal_compose_liftS_lead_out().
ff_snow_common_end()
av_cold void ff_snow_common_end (SnowContext * s)
Definition at line 693 of file snow.c.
Referenced by decode_end(), encode_end(), and snow_horizontal_compose_liftS_lead_out().