FFmpeg: libavcodec/snowdec.c File Reference
snowdec.c File Reference
#include "libavutil/intmath.h"
#include "libavutil/log.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "snow_dwt.h"
#include "internal.h"
#include "snow.h"
#include "rangecoder.h"
#include "mathops.h"
#include "mpegvideo.h"
#include "h263.h"
Macros
#define GET_S(dst, check)
Functions
static av_always_inline void predict_slice_buffered (SnowContext *s, slice_buffer *sb, IDWTELEM *old_buffer, int plane_index, int add, int mb_y)
static void decode_subband_slice_buffered (SnowContext *s, SubBand *b, slice_buffer *sb, int start_y, int h, int save_state[1])
static int decode_q_branch (SnowContext *s, int level, int x, int y)
static void dequantize_slice_buffered (SnowContext *s, slice_buffer *sb, SubBand *b, IDWTELEM *src, int stride, int start_y, int end_y)
static void correlate_slice_buffered (SnowContext *s, slice_buffer *sb, SubBand *b, IDWTELEM *src, int stride, int inverse, int use_median, int start_y, int end_y)
static void decode_qlogs (SnowContext *s)
static int decode_header (SnowContext *s)
static av_cold int decode_init (AVCodecContext *avctx)
static int decode_blocks (SnowContext *s)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int decode_end (AVCodecContext *avctx)
Variables
AVCodec ff_snow_decoder
Macro Definition Documentation
GET_S
#define GET_S (dst, check)
Value:
tmp= get_symbol(&s->c, s->header_state, 0);\
    if(!(check)){\
        av_log(s->avctx, AV_LOG_ERROR, "Error " #dst " is %d\n", tmp);\
        return AVERROR_INVALIDDATA;\
    }\
    dst= tmp;
Definition at line 285 of file snowdec.c.
Referenced by decode_header().
Function Documentation
predict_slice_buffered()
static av_always_inline void predict_slice_buffered (SnowContext * s, slice_buffer * sb, IDWTELEM * old_buffer, int plane_index, int add, int mb_y) static
Definition at line 35 of file snowdec.c.
Referenced by decode_frame().
decode_subband_slice_buffered()
static void decode_subband_slice_buffered (SnowContext * s, SubBand * b, slice_buffer * sb, int start_y, int h, int save_state[1]) inline static
Definition at line 117 of file snowdec.c.
Referenced by decode_frame().
decode_q_branch()
static int decode_q_branch (SnowContext * s, int level, int x, int y) static
Definition at line 158 of file snowdec.c.
Referenced by decode_blocks().
dequantize_slice_buffered()
static void dequantize_slice_buffered (SnowContext * s, slice_buffer * sb, SubBand * b, IDWTELEM * src, int stride, int start_y, int end_y) static
Definition at line 216 of file snowdec.c.
Referenced by decode_frame().
correlate_slice_buffered()
static void correlate_slice_buffered (SnowContext * s, slice_buffer * sb, SubBand * b, IDWTELEM * src, int stride, int inverse, int use_median, int start_y, int end_y) static
Definition at line 239 of file snowdec.c.
Referenced by decode_frame().
decode_qlogs()
static void decode_qlogs (SnowContext * s) static
Definition at line 269 of file snowdec.c.
Referenced by decode_header().
decode_header()
static int decode_header (SnowContext * s) static
Definition at line 293 of file snowdec.c.
Referenced by decode_frame().
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 402 of file snowdec.c.
decode_blocks()
static int decode_blocks (SnowContext * s) static
Definition at line 413 of file snowdec.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 428 of file snowdec.c.
decode_end()
static av_cold int decode_end (AVCodecContext * avctx) static
Definition at line 628 of file snowdec.c.
Variable Documentation
ff_snow_decoder
AVCodec ff_snow_decoder
Initial value:
= {
    .name           = "snow",
    .long_name      = NULL_IF_CONFIG_SMALL("Snow"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_SNOW,
    .priv_data_size = sizeof(SnowContext),
    .init           = decode_init,
    .close          = decode_end,
    .decode         = decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1 ,
    .caps_internal  = FF_CODEC_CAP_INIT_THREADSAFE |
                      FF_CODEC_CAP_INIT_CLEANUP,
}
Definition at line 639 of file snowdec.c.