FFmpeg: libavformat/spdifenc.c File Reference
spdifenc.c File Reference
IEC-61937 encapsulation of various formats, used by S/PDIF.
#include <inttypes.h>
#include "avformat.h"
#include "avio_internal.h"
#include "spdif.h"
#include "libavcodec/ac3.h"
#include "libavcodec/dca.h"
#include "libavcodec/dca_syncwords.h"
#include "libavcodec/aacadtsdec.h"
#include "libavutil/opt.h"
Data Structures
struct IEC61937Context
Macros
#define SPDIF_FLAG_BIGENDIAN 0x01
#define MAT_FRAME_SIZE 61424
#define TRUEHD_FRAME_OFFSET 2560
#define MAT_MIDDLE_CODE_OFFSET -4
Functions
static int spdif_header_ac3 (AVFormatContext *s, AVPacket *pkt)
static int spdif_header_eac3 (AVFormatContext *s, AVPacket *pkt)
static int spdif_dts4_subtype (int period)
static int spdif_header_dts4 (AVFormatContext *s, AVPacket *pkt, int core_size, int sample_rate, int blocks)
static int spdif_header_dts (AVFormatContext *s, AVPacket *pkt)
static int spdif_header_mpeg (AVFormatContext *s, AVPacket *pkt)
static int spdif_header_aac (AVFormatContext *s, AVPacket *pkt)
static int spdif_header_truehd (AVFormatContext *s, AVPacket *pkt)
static int spdif_write_header (AVFormatContext *s)
static int spdif_write_trailer (AVFormatContext *s)
static av_always_inline void spdif_put_16 (IEC61937Context *ctx, AVIOContext *pb, unsigned int val)
static int spdif_write_packet (struct AVFormatContext *s, AVPacket *pkt)
Variables
static const AVOption options []
static const AVClass spdif_class
static enum IEC61937DataType mpeg_data_type [2][3]
AVOutputFormat ff_spdif_muxer
Detailed Description
IEC-61937 encapsulation of various formats, used by S/PDIF.
Author
Bartlomiej Wolowiec
Anssi Hannula
Carl Eugen Hoyos
Definition in file spdifenc.c.
Macro Definition Documentation
SPDIF_FLAG_BIGENDIAN
#define SPDIF_FLAG_BIGENDIAN 0x01
Definition at line 82 of file spdifenc.c.
Referenced by spdif_put_16(), and spdif_write_packet().
MAT_FRAME_SIZE
#define MAT_FRAME_SIZE 61424
Definition at line 393 of file spdifenc.c.
Referenced by spdif_header_truehd(), and spdif_write_header().
TRUEHD_FRAME_OFFSET
#define TRUEHD_FRAME_OFFSET 2560
Definition at line 394 of file spdifenc.c.
Referenced by spdif_header_truehd().
MAT_MIDDLE_CODE_OFFSET
#define MAT_MIDDLE_CODE_OFFSET -4
Definition at line 395 of file spdifenc.c.
Referenced by spdif_header_truehd().
Function Documentation
spdif_header_ac3()
static int spdif_header_ac3 (AVFormatContext * s, AVPacket * pkt) static
Definition at line 105 of file spdifenc.c.
Referenced by spdif_write_header().
spdif_header_eac3()
static int spdif_header_eac3 (AVFormatContext * s, AVPacket * pkt) static
Definition at line 115 of file spdifenc.c.
Referenced by spdif_write_header().
spdif_dts4_subtype()
static int spdif_dts4_subtype (int period) static
Definition at line 153 of file spdifenc.c.
Referenced by spdif_header_dts4().
spdif_header_dts4()
static int spdif_header_dts4 (AVFormatContext * s, AVPacket * pkt, int core_size, int sample_rate, int blocks) static
Definition at line 166 of file spdifenc.c.
Referenced by spdif_header_dts().
spdif_header_dts()
static int spdif_header_dts (AVFormatContext * s, AVPacket * pkt) static
Definition at line 243 of file spdifenc.c.
Referenced by spdif_write_header().
spdif_header_mpeg()
static int spdif_header_mpeg (AVFormatContext * s, AVPacket * pkt) static
Definition at line 326 of file spdifenc.c.
Referenced by spdif_write_header().
spdif_header_aac()
static int spdif_header_aac (AVFormatContext * s, AVPacket * pkt) static
Definition at line 349 of file spdifenc.c.
Referenced by spdif_write_header().
spdif_header_truehd()
static int spdif_header_truehd (AVFormatContext * s, AVPacket * pkt) static
Definition at line 397 of file spdifenc.c.
Referenced by spdif_write_header().
spdif_write_header()
static int spdif_write_header (AVFormatContext * s) static
Definition at line 443 of file spdifenc.c.
spdif_write_trailer()
static int spdif_write_trailer (AVFormatContext * s) static
Definition at line 479 of file spdifenc.c.
spdif_put_16()
static av_always_inline void spdif_put_16 (IEC61937Context * ctx, AVIOContext * pb, unsigned int val) static
Definition at line 487 of file spdifenc.c.
Referenced by spdif_write_packet().
spdif_write_packet()
static int spdif_write_packet (struct AVFormatContext * s, AVPacket * pkt) static
Definition at line 496 of file spdifenc.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
{ "spdif_flags", "IEC 61937 encapsulation flags", 0x42, AV_OPT_TYPE_FLAGS, {.i64 = 0}, 0, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM, "spdif_flags" },
{ "be", "output in big-endian format (for use as s16be)", 0, AV_OPT_TYPE_CONST, {.i64 = SPDIF_FLAG_BIGENDIAN},  0, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM, "spdif_flags" },
{ "dtshd_rate", "mux complete DTS frames in HD mode at the specified IEC958 rate (in Hz, default 0=disabled)", 0x42, AV_OPT_TYPE_INT, {.i64 = 0}, 0, 768000, AV_OPT_FLAG_ENCODING_PARAM },
{ "dtshd_fallback_time", "min secs to strip HD for after an overflow (-1: till the end, default 60)", 0x42, AV_OPT_TYPE_INT, {.i64 = 60}, -1, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM },
{ NULL },
}
Definition at line 90 of file spdifenc.c.
spdif_class
const AVClass spdif_class static
Initial value:
= {
    .class_name     = "spdif",
    .item_name      = av_default_item_name,
    .option         = options,
    .version        = LIBAVUTIL_VERSION_INT,
}
Definition at line 98 of file spdifenc.c.
mpeg_data_type
enum IEC61937DataType mpeg_data_type[2][3] static
Initial value:
= {
    { IEC61937_MPEG2_LAYER1_LSF, IEC61937_MPEG2_LAYER2_LSF, IEC61937_MPEG2_LAYER3_LSF },
    { IEC61937_MPEG1_LAYER1,     IEC61937_MPEG1_LAYER23,    IEC61937_MPEG1_LAYER23 },
}
Definition at line 320 of file spdifenc.c.
Referenced by spdif_header_mpeg().
ff_spdif_muxer
AVOutputFormat ff_spdif_muxer
Initial value:
= {
    .name              = "spdif",
    .long_name         = NULL_IF_CONFIG_SMALL("IEC 61937 (used on S/PDIF - IEC958)"),
    .extensions        = "spdif",
    .priv_data_size    = sizeof(IEC61937Context),
    .audio_codec       = AV_CODEC_ID_AC3,
    .video_codec       = AV_CODEC_ID_NONE,
    .write_header      = spdif_write_header,
    .write_packet      = spdif_write_packet,
    .write_trailer     = spdif_write_trailer,
    .flags             = AVFMT_NOTIMESTAMPS,
    .priv_class        = &spdif_class,
}
Definition at line 548 of file spdifenc.c.