FFmpeg: libavformat/spdifdec.c File Reference
spdifdec.c File Reference
IEC 61937 demuxer, used for compressed data in S/PDIF.
#include "avformat.h"
#include "spdif.h"
#include "libavcodec/ac3.h"
#include "libavcodec/aacadtsdec.h"
Macros
#define SPDIF_MAX_OFFSET 16384
Functions
static int spdif_get_offset_and_codec (AVFormatContext *s, enum IEC61937DataType data_type, const char *buf, int *offset, enum AVCodecID *codec)
static int spdif_probe (AVProbeData *p)
int ff_spdif_probe (const uint8_t *p_buf, int buf_size, enum AVCodecID *codec)
static int spdif_read_header (AVFormatContext *s)
int ff_spdif_read_packet (AVFormatContext *s, AVPacket *pkt)
Variables
AVInputFormat ff_spdif_demuxer
Detailed Description
IEC 61937 demuxer, used for compressed data in S/PDIF.
Author
Anssi Hannula
Definition in file spdifdec.c.
Macro Definition Documentation
SPDIF_MAX_OFFSET
#define SPDIF_MAX_OFFSET 16384
Definition at line 104 of file spdifdec.c.
Referenced by ff_spdif_probe().
Function Documentation
spdif_get_offset_and_codec()
static int spdif_get_offset_and_codec (AVFormatContext * s, enum IEC61937DataType data_type, const char * buf, int * offset, enum AVCodecID * codec) static
Definition at line 33 of file spdifdec.c.
Referenced by ff_spdif_probe(), and ff_spdif_read_packet().
spdif_probe()
static int spdif_probe (AVProbeData * p) static
Definition at line 106 of file spdifdec.c.
ff_spdif_probe()
int ff_spdif_probe (const uint8_t * p_buf, int buf_size, enum AVCodecID * codec)
Definition at line 112 of file spdifdec.c.
Referenced by set_spdif(), and spdif_probe().
spdif_read_header()
static int spdif_read_header (AVFormatContext * s) static
Definition at line 163 of file spdifdec.c.
ff_spdif_read_packet()
int ff_spdif_read_packet (AVFormatContext * s, AVPacket * pkt)
Definition at line 169 of file spdifdec.c.
Referenced by set_spdif().
Variable Documentation
ff_spdif_demuxer
AVInputFormat ff_spdif_demuxer
Initial value:
= {
    .name           = "spdif",
    .long_name      = NULL_IF_CONFIG_SMALL("IEC 61937 (compressed data in S/PDIF)"),
    .read_probe     = spdif_probe,
    .read_header    = spdif_read_header,
    .read_packet    = ff_spdif_read_packet,
    .flags          = AVFMT_GENERIC_INDEX,
}
Definition at line 233 of file spdifdec.c.