FFmpeg: libavformat/srtp.h File Reference
srtp.h File Reference
#include <stdint.h>
Data Structures
struct SRTPContext
Functions
int ff_srtp_set_crypto (struct SRTPContext *s, const char *suite, const char *params)
void ff_srtp_free (struct SRTPContext *s)
int ff_srtp_decrypt (struct SRTPContext *s, uint8_t *buf, int *lenptr)
int ff_srtp_encrypt (struct SRTPContext *s, const uint8_t *in, int len, uint8_t *out, int outlen)
Function Documentation
ff_srtp_set_crypto()
int ff_srtp_set_crypto (struct SRTPContext * s, const char * suite, const char * params)
Definition at line 65 of file srtp.c.
Referenced by ff_rtp_parse_set_crypto(), main(), srtp_open(), and test_encrypt().
ff_srtp_free()
void ff_srtp_free (struct SRTPContext * s)
Definition at line 31 of file srtp.c.
Referenced by ff_rtp_parse_close(), ff_srtp_set_crypto(), main(), srtp_close(), and test_encrypt().
ff_srtp_decrypt()
int ff_srtp_decrypt (struct SRTPContext * s, uint8_t * buf, int * lenptr)
Definition at line 126 of file srtp.c.
Referenced by ff_rtp_parse_packet(), srtp_read(), test_decrypt(), and test_encrypt().
ff_srtp_encrypt()
int ff_srtp_encrypt (struct SRTPContext * s, const uint8_t * in, int len, uint8_t * out, int outlen)
Definition at line 238 of file srtp.c.
Referenced by srtp_write(), and test_encrypt().