FFmpeg: compat/atomics/pthread/stdatomic.c File Reference
stdatomic.c File Reference
#include <pthread.h>
#include <stdint.h>
#include "stdatomic.h"
Functions
void avpriv_atomic_lock (void)
void avpriv_atomic_unlock (void)
Variables
static pthread_mutex_t atomic_lock = PTHREAD_MUTEX_INITIALIZER
Function Documentation
avpriv_atomic_lock()
void avpriv_atomic_lock (void)
Definition at line 31 of file stdatomic.c.
Referenced by atomic_compare_exchange_strong(), atomic_exchange(), atomic_load(), atomic_store(), and atomic_thread_fence().
avpriv_atomic_unlock()
void avpriv_atomic_unlock (void)
Definition at line 36 of file stdatomic.c.
Referenced by atomic_compare_exchange_strong(), atomic_exchange(), atomic_load(), atomic_store(), and atomic_thread_fence().
Variable Documentation
atomic_lock
pthread_mutex_t atomic_lock = PTHREAD_MUTEX_INITIALIZER static
Definition at line 29 of file stdatomic.c.
Referenced by avpriv_atomic_lock(), and avpriv_atomic_unlock().