FFmpeg: libavutil/stereo3d.c File Reference
stereo3d.c File Reference
#include <stdint.h>
#include <string.h>
#include "common.h"
#include "mem.h"
#include "stereo3d.h"
Functions
AVStereo3D * av_stereo3d_alloc (void)
Allocate an AVStereo3D structure and set its fields to default values.
AVStereo3D * av_stereo3d_create_side_data (AVFrame *frame)
Allocate a complete AVFrameSideData and add it to the frame.
const char * av_stereo3d_type_name (unsigned int type)
Provide a human-readable name of a given stereo3d type.
int av_stereo3d_from_name (const char *name)
Get the AVStereo3DType form a human-readable name.
Variables
static const char * stereo3d_type_names []
Function Documentation
av_stereo3d_alloc()
AVStereo3D* av_stereo3d_alloc (void)
Allocate an AVStereo3D structure and set its fields to default values.
The resulting struct can be freed using av_freep().
Returns
An AVStereo3D filled with default values or NULL on failure.
Definition at line 28 of file stereo3d.c.
Referenced by ff_mkv_stereo3d_conv(), mjpeg_decode_app(), mov_parse_uuid_spherical(), and mov_read_st3d().
av_stereo3d_create_side_data()
AVStereo3D* av_stereo3d_create_side_data (AVFrame * frame)
Allocate a complete AVFrameSideData and add it to the frame.
Parameters
frame The frame which side data is added to.
Returns
The AVStereo3D structure to be filled by caller.
Definition at line 33 of file stereo3d.c.
Referenced by decode_frame_common(), ff_mjpeg_decode_frame(), h264_export_frame_props(), mpeg_field_start(), set_side_data(), and try_push_frame().
av_stereo3d_type_name()
const char* av_stereo3d_type_name (unsigned int type)
Provide a human-readable name of a given stereo3d type.
Parameters
type The input stereo3d type value.
Returns
The name of the stereo3d value, or "unknown".
Definition at line 57 of file stereo3d.c.
Referenced by dump_stereo3d(), and print_pkt_side_data().
av_stereo3d_from_name()
int av_stereo3d_from_name (const char * name)
Get the AVStereo3DType form a human-readable name.
Parameters
type The input string.
Returns
The AVStereo3DType value, or -1 if not found.
Definition at line 65 of file stereo3d.c.
Variable Documentation
stereo3d_type_names
const char* stereo3d_type_names[] static
Initial value:
= {
    [AV_STEREO3D_2D]                  = "2D",
    [AV_STEREO3D_SIDEBYSIDE]          = "side by side",
    [AV_STEREO3D_TOPBOTTOM]           = "top and bottom",
    [AV_STEREO3D_FRAMESEQUENCE]       = "frame alternate",
    [AV_STEREO3D_CHECKERBOARD]        = "checkerboard",
    [AV_STEREO3D_SIDEBYSIDE_QUINCUNX] = "side by side (quincunx subsampling)",
    [AV_STEREO3D_LINES]               = "interleaved lines",
    [AV_STEREO3D_COLUMNS]             = "interleaved columns",
}
Definition at line 46 of file stereo3d.c.
Referenced by av_stereo3d_from_name(), and av_stereo3d_type_name().