FFmpeg: compat/strtod.c File Reference
strtod.c File Reference
#include <limits.h>
#include <stdlib.h>
#include "libavutil/avstring.h"
#include "libavutil/mathematics.h"
Functions
static char * check_nan_suffix (char *s)
double strtod (const char *, char **)
double avpriv_strtod (const char *nptr, char **endptr)
Function Documentation
check_nan_suffix()
static char* check_nan_suffix (char * s) static
Definition at line 28 of file strtod.c.
Referenced by avpriv_strtod().
strtod()
double strtod (const char * , char **)
Referenced by av_parse_color(), av_strtod(), avpriv_strtod(), check_nan_suffix(), ffserver_parse_config_feed(), ffserver_set_float_param(), lex_double(), mov_write_loci_tag(), parse_dB(), parse_options(), rtmp_write_amf_data(), and str_to_time().
avpriv_strtod()
double avpriv_strtod (const char * nptr, char ** endptr)
Definition at line 45 of file strtod.c.