FFmpeg: MSS2DSPContext Struct Reference
MSS2DSPContext Struct Reference
#include <libavcodec/mss2dsp.h>
Data Fields
void(* mss2_blit_wmv9)(uint8_t *dst, int dst_stride, const uint8_t *srcy, int srcy_stride, const uint8_t *srcu, const uint8_t *srcv, int srcuv_stride, int w, int h)
void(* mss2_blit_wmv9_masked)(uint8_t *dst, int dst_stride, int maskcolor, const uint8_t *mask, int mask_stride, const uint8_t *srcy, int srcy_stride, const uint8_t *srcu, const uint8_t *srcv, int srcuv_stride, int w, int h)
void(* mss2_gray_fill_masked)(uint8_t *dst, int dst_stride, int maskcolor, const uint8_t *mask, int mask_stride, int w, int h)
void(* upsample_plane)(uint8_t *plane, int plane_stride, int w, int h)
Detailed Description
Definition at line 31 of file mss2dsp.h.
Field Documentation
mss2_blit_wmv9
void(* MSS2DSPContext::mss2_blit_wmv9) (uint8_t *dst, int dst_stride, const uint8_t *srcy, int srcy_stride, const uint8_t *srcu, const uint8_t *srcv, int srcuv_stride, int w, int h)
Definition at line 32 of file mss2dsp.h.
Referenced by decode_wmv9(), and ff_mss2dsp_init().
mss2_blit_wmv9_masked
void(* MSS2DSPContext::mss2_blit_wmv9_masked) (uint8_t *dst, int dst_stride, int maskcolor, const uint8_t *mask, int mask_stride, const uint8_t *srcy, int srcy_stride, const uint8_t *srcu, const uint8_t *srcv, int srcuv_stride, int w, int h)
Definition at line 36 of file mss2dsp.h.
Referenced by decode_wmv9(), and ff_mss2dsp_init().
mss2_gray_fill_masked
void(* MSS2DSPContext::mss2_gray_fill_masked) (uint8_t *dst, int dst_stride, int maskcolor, const uint8_t *mask, int mask_stride, int w, int h)
Definition at line 42 of file mss2dsp.h.
Referenced by ff_mss2dsp_init(), and mss2_decode_frame().
upsample_plane
void(* MSS2DSPContext::upsample_plane) (uint8_t *plane, int plane_stride, int w, int h)
Definition at line 45 of file mss2dsp.h.
Referenced by decode_wmv9(), and ff_mss2dsp_init().
The documentation for this struct was generated from the following file:
libavcodec/mss2dsp.h