FFmpeg: FDCTDSPContext Struct Reference
FDCTDSPContext Struct Reference
#include <libavcodec/fdctdsp.h>
Data Fields
void(* fdct)(int16_t *block)
void(* fdct248)(int16_t *block)
Detailed Description
Definition at line 26 of file fdctdsp.h.
Field Documentation
fdct
void(* FDCTDSPContext::fdct) (int16_t *block)
Definition at line 27 of file fdctdsp.h.
Referenced by dct_get(), dct_max8x8_c(), dct_quantize_refine(), dct_quantize_trellis_c(), dct_sad8x8_c(), dnxhd_10bit_dct_quantize(), dvvideo_encode_init(), encode_init(), fdct_get(), ff_convert_matrix(), ff_dct_quantize_c(), ff_fdctdsp_init(), ff_fdctdsp_init_ppc(), ff_fdctdsp_init_x86(), and prores_fdct().
fdct248
void(* FDCTDSPContext::fdct248) (int16_t *block)
Definition at line 28 of file fdctdsp.h.
Referenced by dvvideo_encode_init(), and ff_fdctdsp_init().
The documentation for this struct was generated from the following file:
libavcodec/fdctdsp.h