FFmpeg: AVFContext Struct Reference
AVFContext Struct Reference
Protected Attributes
AVClass * class
int frames_captured
int audio_frames_captured
int64_t first_pts
int64_t first_audio_pts
pthread_mutex_t frame_lock
pthread_cond_t frame_wait_cond
id avf_delegate
id avf_audio_delegate
AVRational framerate
int width
int height
int capture_cursor
int capture_mouse_clicks
int list_devices
int video_device_index
int video_stream_index
int audio_device_index
int audio_stream_index
char * video_filename
char * audio_filename
int num_video_devices
int audio_channels
int audio_bits_per_sample
int audio_float
int audio_be
int audio_signed_integer
int audio_packed
int audio_non_interleaved
int32_t * audio_buffer
int audio_buffer_size
enum AVPixelFormat pixel_format
AVCaptureSession * capture_session
AVCaptureVideoDataOutput * video_output
AVCaptureAudioDataOutput * audio_output
CMSampleBufferRef current_frame
CMSampleBufferRef current_audio_frame
Detailed Description
Definition at line 81 of file avfoundation.m.
Field Documentation
class
- (AVClass*) class protected
Definition at line 83 of file avfoundation.m.
frames_captured
- (int) frames_captured protected
Definition at line 85 of file avfoundation.m.
Referenced by AVFFrameReceiver::captureOutput:didOutputSampleBuffer:fromConnection:, and get_video_config().
audio_frames_captured
- (int) audio_frames_captured protected
Definition at line 86 of file avfoundation.m.
Referenced by AVFAudioReceiver::captureOutput:didOutputSampleBuffer:fromConnection:, and get_audio_config().
first_pts
- (int64_t) first_pts protected
Definition at line 87 of file avfoundation.m.
Referenced by avf_read_header().
first_audio_pts
- (int64_t) first_audio_pts protected
Definition at line 88 of file avfoundation.m.
Referenced by avf_read_header().
frame_lock
- (pthread_mutex_t) frame_lock protected
Definition at line 89 of file avfoundation.m.
Referenced by avf_read_header(), avf_read_packet(), destroy_context(), lock_frames(), and unlock_frames().
frame_wait_cond
- (pthread_cond_t) frame_wait_cond protected
Definition at line 90 of file avfoundation.m.
Referenced by avf_read_header(), avf_read_packet(), AVFFrameReceiver::captureOutput:didOutputSampleBuffer:fromConnection:, AVFAudioReceiver::captureOutput:didOutputSampleBuffer:fromConnection:, and destroy_context().
avf_delegate
- (id) avf_delegate protected
Definition at line 91 of file avfoundation.m.
Referenced by add_video_device(), and destroy_context().
avf_audio_delegate
- (id) avf_audio_delegate protected
Definition at line 92 of file avfoundation.m.
Referenced by add_audio_device(), and destroy_context().
framerate
- (AVRational) framerate protected
Definition at line 94 of file avfoundation.m.
Referenced by avf_read_header(), and configure_video_device().
width
- (int) width protected
Definition at line 95 of file avfoundation.m.
Referenced by configure_video_device().
height
- (int) height protected
Definition at line 95 of file avfoundation.m.
Referenced by configure_video_device().
capture_cursor
- (int) capture_cursor protected
Definition at line 97 of file avfoundation.m.
Referenced by avf_read_header().
capture_mouse_clicks
- (int) capture_mouse_clicks protected
Definition at line 98 of file avfoundation.m.
Referenced by avf_read_header().
list_devices
- (int) list_devices protected
Definition at line 100 of file avfoundation.m.
Referenced by avf_read_header().
video_device_index
- (int) video_device_index protected
Definition at line 101 of file avfoundation.m.
Referenced by add_video_device(), and avf_read_header().
video_stream_index
- (int) video_stream_index protected
Definition at line 102 of file avfoundation.m.
Referenced by avf_read_packet(), and get_video_config().
audio_device_index
- (int) audio_device_index protected
Definition at line 103 of file avfoundation.m.
Referenced by avf_read_header().
audio_stream_index
- (int) audio_stream_index protected
Definition at line 104 of file avfoundation.m.
Referenced by avf_read_packet(), and get_audio_config().
video_filename
- (char*) video_filename protected
Definition at line 106 of file avfoundation.m.
Referenced by avf_read_header(), and parse_device_name().
audio_filename
- (char*) audio_filename protected
Definition at line 107 of file avfoundation.m.
Referenced by avf_read_header(), and parse_device_name().
num_video_devices
- (int) num_video_devices protected
Definition at line 109 of file avfoundation.m.
Referenced by add_video_device(), and avf_read_header().
audio_channels
- (int) audio_channels protected
Definition at line 111 of file avfoundation.m.
Referenced by avf_read_packet(), and get_audio_config().
audio_bits_per_sample
- (int) audio_bits_per_sample protected
Definition at line 112 of file avfoundation.m.
Referenced by avf_read_packet(), and get_audio_config().
audio_float
- (int) audio_float protected
Definition at line 113 of file avfoundation.m.
Referenced by get_audio_config().
audio_be
- (int) audio_be protected
Definition at line 114 of file avfoundation.m.
Referenced by get_audio_config().
audio_signed_integer
- (int) audio_signed_integer protected
Definition at line 115 of file avfoundation.m.
Referenced by get_audio_config().
audio_packed
- (int) audio_packed protected
Definition at line 116 of file avfoundation.m.
Referenced by get_audio_config().
audio_non_interleaved
- (int) audio_non_interleaved protected
Definition at line 117 of file avfoundation.m.
Referenced by avf_read_packet(), and get_audio_config().
audio_buffer
- (int32_t*) audio_buffer protected
Definition at line 119 of file avfoundation.m.
Referenced by avf_read_packet(), destroy_context(), and get_audio_config().
audio_buffer_size
- (int) audio_buffer_size protected
Definition at line 120 of file avfoundation.m.
Referenced by avf_read_packet(), and get_audio_config().
pixel_format
- (enum AVPixelFormat) pixel_format protected
Definition at line 122 of file avfoundation.m.
Referenced by add_video_device(), and get_video_config().
capture_session
- (AVCaptureSession*) capture_session protected
Definition at line 124 of file avfoundation.m.
Referenced by add_audio_device(), add_video_device(), avf_read_header(), and destroy_context().
video_output
- (AVCaptureVideoDataOutput*) video_output protected
Definition at line 125 of file avfoundation.m.
Referenced by add_video_device(), and destroy_context().
audio_output
- (AVCaptureAudioDataOutput*) audio_output protected
Definition at line 126 of file avfoundation.m.
Referenced by add_audio_device(), and destroy_context().
current_frame
- (CMSampleBufferRef) current_frame protected
Definition at line 127 of file avfoundation.m.
Referenced by avf_read_packet(), AVFFrameReceiver::captureOutput:didOutputSampleBuffer:fromConnection:, destroy_context(), and get_video_config().
current_audio_frame
- (CMSampleBufferRef) current_audio_frame protected
Definition at line 128 of file avfoundation.m.
Referenced by avf_read_packet(), AVFAudioReceiver::captureOutput:didOutputSampleBuffer:fromConnection:, and get_audio_config().
The documentation for this struct was generated from the following file:
libavdevice/avfoundation.m