FFmpeg: LLVidDSPContext Struct Reference
LLVidDSPContext Struct Reference
#include <libavcodec/lossless_videodsp.h>
Data Fields
void(* add_int16)(uint16_t *dst, const uint16_t *src, unsigned mask, int w)
void(* diff_int16)(uint16_t *dst, const uint16_t *src1, const uint16_t *src2, unsigned mask, int w)
void(* sub_hfyu_median_pred_int16)(uint16_t *dst, const uint16_t *src1, const uint16_t *src2, unsigned mask, int w, int *left, int *left_top)
void(* add_hfyu_median_pred_int16)(uint16_t *dst, const uint16_t *top, const uint16_t *diff, unsigned mask, int w, int *left, int *left_top)
int(* add_hfyu_left_pred_int16)(uint16_t *dst, const uint16_t *src, unsigned mask, int w, unsigned left)
Detailed Description
Definition at line 28 of file lossless_videodsp.h.
Field Documentation
add_int16
void(* LLVidDSPContext::add_int16) (uint16_t *dst, const uint16_t *src, unsigned mask, int w)
Definition at line 29 of file lossless_videodsp.h.
Referenced by add_bytes(), ff_llviddsp_init(), and ff_llviddsp_init_x86().
diff_int16
void(* LLVidDSPContext::diff_int16) (uint16_t *dst, const uint16_t *src1, const uint16_t *src2, unsigned mask, int w)
Definition at line 30 of file lossless_videodsp.h.
Referenced by diff_bytes(), ff_llviddsp_init(), ff_llviddsp_init_x86(), and sub_left_prediction().
sub_hfyu_median_pred_int16
void(* LLVidDSPContext::sub_hfyu_median_pred_int16) (uint16_t *dst, const uint16_t *src1, const uint16_t *src2, unsigned mask, int w, int *left, int *left_top)
Definition at line 32 of file lossless_videodsp.h.
Referenced by ff_llviddsp_init(), ff_llviddsp_init_x86(), and sub_median_prediction().
add_hfyu_median_pred_int16
void(* LLVidDSPContext::add_hfyu_median_pred_int16) (uint16_t *dst, const uint16_t *top, const uint16_t *diff, unsigned mask, int w, int *left, int *left_top)
Definition at line 33 of file lossless_videodsp.h.
Referenced by add_median_prediction(), ff_llviddsp_init(), and ff_llviddsp_init_x86().
add_hfyu_left_pred_int16
int(* LLVidDSPContext::add_hfyu_left_pred_int16) (uint16_t *dst, const uint16_t *src, unsigned mask, int w, unsigned left)
Definition at line 34 of file lossless_videodsp.h.
Referenced by ff_llviddsp_init(), ff_llviddsp_init_x86(), left_prediction(), and magy_decode_slice10().
The documentation for this struct was generated from the following file:
libavcodec/lossless_videodsp.h