FFmpeg: VP9DSPContext Struct Reference
VP9DSPContext Struct Reference
#include <libavcodec/vp9dsp.h>
Data Fields
void(* intra_pred [N_TXFM_SIZES][N_INTRA_PRED_MODES])(uint8_t *dst, ptrdiff_t stride, const uint8_t *left, const uint8_t *top)
void(* itxfm_add [N_TXFM_SIZES+1][N_TXFM_TYPES])(uint8_t *dst, ptrdiff_t stride, int16_t *block, int eob)
void(* loop_filter_8 [3][2])(uint8_t *dst, ptrdiff_t stride, int mb_lim, int lim, int hev_thr)
void(* loop_filter_16 [2])(uint8_t *dst, ptrdiff_t stride, int mb_lim, int lim, int hev_thr)
void(* loop_filter_mix2 [2][2][2])(uint8_t *dst, ptrdiff_t stride, int mb_lim, int lim, int hev_thr)
vp9_mc_func mc [5][4][2][2][2]
vp9_scaled_mc_func smc [5][4][2]
Detailed Description
Definition at line 39 of file vp9dsp.h.
Field Documentation
intra_pred
void(* VP9DSPContext::intra_pred[N_TXFM_SIZES][N_INTRA_PRED_MODES])(uint8_t *dst, ptrdiff_t stride, const uint8_t *left, const uint8_t *top)
Definition at line 51 of file vp9dsp.h.
Referenced by check_ipred(), and intra_recon().
itxfm_add
void(* VP9DSPContext::itxfm_add[N_TXFM_SIZES + 1][N_TXFM_TYPES])(uint8_t *dst, ptrdiff_t stride, int16_t *block, int eob)
Definition at line 70 of file vp9dsp.h.
Referenced by check_itxfm(), ff_vp9dsp_init_x86(), inter_recon(), and intra_recon().
loop_filter_8
void(* VP9DSPContext::loop_filter_8[3][2])(uint8_t *dst, ptrdiff_t stride, int mb_lim, int lim, int hev_thr)
Definition at line 80 of file vp9dsp.h.
Referenced by check_loopfilter(), ff_vp9dsp_init_x86(), filter_plane_cols(), filter_plane_rows(), lf_8_fns(), and vp9dsp_loopfilter_init_aarch64().
loop_filter_16
void(* VP9DSPContext::loop_filter_16[2])(uint8_t *dst, ptrdiff_t stride, int mb_lim, int lim, int hev_thr)
Definition at line 88 of file vp9dsp.h.
Referenced by check_loopfilter(), filter_plane_cols(), filter_plane_rows(), lf_8_fns(), and vp9dsp_loopfilter_init_aarch64().
loop_filter_mix2
void(* VP9DSPContext::loop_filter_mix2[2][2][2])(uint8_t *dst, ptrdiff_t stride, int mb_lim, int lim, int hev_thr)
Definition at line 102 of file vp9dsp.h.
Referenced by check_loopfilter(), filter_plane_cols(), filter_plane_rows(), lf_8_fns(), and vp9dsp_loopfilter_init_aarch64().
mc
vp9_mc_func VP9DSPContext::mc[5][4][2][2][2]
Definition at line 114 of file vp9dsp.h.
Referenced by check_mc(), and decode_b().
smc
vp9_scaled_mc_func VP9DSPContext::smc[5][4][2]
Definition at line 120 of file vp9dsp.h.
The documentation for this struct was generated from the following file:
libavcodec/vp9dsp.h