FFmpeg: DitherDSPContext Struct Reference
DitherDSPContext Struct Reference
#include <libavresample/dither.h>
Data Fields
void(* quantize)(int16_t *dst, const float *src, float *dither, int len)
Convert samples from flt to s16 with added dither noise.
int ptr_align
src and dst constraints for quantize()
int samples_align
len constraints for quantize()
void(* dither_int_to_float)(float *dst, int *src0, int len)
Convert dither noise from int to float with triangular distribution.
Detailed Description
Definition at line 29 of file dither.h.
Field Documentation
quantize
void(* DitherDSPContext::quantize) (int16_t *dst, const float *src, float *dither, int len)
Convert samples from flt to s16 with added dither noise.
Parameters
dst destination float array, range -0.5 to 0.5
src source int array, range INT_MIN to INT_MAX.
dither float dither noise array
len number of samples
Definition at line 38 of file dither.h.
Referenced by dither_init(), ff_convert_dither(), and ff_dither_init_x86().
ptr_align
int DitherDSPContext::ptr_align
src and dst constraints for quantize()
Definition at line 40 of file dither.h.
Referenced by dither_init(), ff_convert_dither(), and ff_dither_init_x86().
samples_align
int DitherDSPContext::samples_align
len constraints for quantize()
Definition at line 41 of file dither.h.
Referenced by dither_init(), ff_convert_dither(), and ff_dither_init_x86().
dither_int_to_float
void(* DitherDSPContext::dither_int_to_float) (float *dst, int *src0, int len)
Convert dither noise from int to float with triangular distribution.
Parameters
dst destination float array, range -0.5 to 0.5 constraints: 32-byte aligned
src0 source int array, range INT_MIN to INT_MAX. the array size is len * 2 constraints: 32-byte aligned
len number of output noise samples constraints: multiple of 16
Definition at line 54 of file dither.h.
Referenced by dither_init(), ff_dither_init_x86(), and generate_dither_noise().
The documentation for this struct was generated from the following file:
libavresample/dither.h