FFmpeg: IntraX8DSPContext Struct Reference
IntraX8DSPContext Struct Reference
#include <libavcodec/intrax8dsp.h>
Data Fields
void(* v_loop_filter)(uint8_t *src, int stride, int qscale)
void(* h_loop_filter)(uint8_t *src, int stride, int qscale)
void(* spatial_compensation [12])(uint8_t *src, uint8_t *dst, int linesize)
void(* setup_spatial_compensation)(uint8_t *src, uint8_t *dst, int linesize, int *range, int *sum, int edges)
Detailed Description
Definition at line 24 of file intrax8dsp.h.
Field Documentation
v_loop_filter
void(* IntraX8DSPContext::v_loop_filter) (uint8_t *src, int stride, int qscale)
Definition at line 25 of file intrax8dsp.h.
Referenced by ff_intrax8dsp_init(), and x8_decode_intra_mb().
h_loop_filter
void(* IntraX8DSPContext::h_loop_filter) (uint8_t *src, int stride, int qscale)
Definition at line 26 of file intrax8dsp.h.
Referenced by ff_intrax8dsp_init(), and x8_decode_intra_mb().
spatial_compensation
void(* IntraX8DSPContext::spatial_compensation[12])(uint8_t *src, uint8_t *dst, int linesize)
Definition at line 28 of file intrax8dsp.h.
Referenced by ff_intrax8dsp_init(), and x8_decode_intra_mb().
setup_spatial_compensation
void(* IntraX8DSPContext::setup_spatial_compensation) (uint8_t *src, uint8_t *dst, int linesize, int *range, int *sum, int edges)
Definition at line 29 of file intrax8dsp.h.
Referenced by ff_intrax8dsp_init(), and x8_setup_spatial_predictor().
The documentation for this struct was generated from the following file:
libavcodec/intrax8dsp.h