FFmpeg: VC1DSPContext Struct Reference
VC1DSPContext Struct Reference
#include <libavcodec/vc1dsp.h>
Data Fields
void(* vc1_inv_trans_8x8)(int16_t *b)
void(* vc1_inv_trans_8x4)(uint8_t *dest, int line_size, int16_t *block)
void(* vc1_inv_trans_4x8)(uint8_t *dest, int line_size, int16_t *block)
void(* vc1_inv_trans_4x4)(uint8_t *dest, int line_size, int16_t *block)
void(* vc1_inv_trans_8x8_dc)(uint8_t *dest, int line_size, int16_t *block)
void(* vc1_inv_trans_8x4_dc)(uint8_t *dest, int line_size, int16_t *block)
void(* vc1_inv_trans_4x8_dc)(uint8_t *dest, int line_size, int16_t *block)
void(* vc1_inv_trans_4x4_dc)(uint8_t *dest, int line_size, int16_t *block)
void(* vc1_v_overlap)(uint8_t *src, int stride)
void(* vc1_h_overlap)(uint8_t *src, int stride)
void(* vc1_v_s_overlap)(int16_t *top, int16_t *bottom)
void(* vc1_h_s_overlap)(int16_t *left, int16_t *right)
void(* vc1_v_loop_filter4)(uint8_t *src, int stride, int pq)
void(* vc1_h_loop_filter4)(uint8_t *src, int stride, int pq)
void(* vc1_v_loop_filter8)(uint8_t *src, int stride, int pq)
void(* vc1_h_loop_filter8)(uint8_t *src, int stride, int pq)
void(* vc1_v_loop_filter16)(uint8_t *src, int stride, int pq)
void(* vc1_h_loop_filter16)(uint8_t *src, int stride, int pq)
vc1op_pixels_func put_vc1_mspel_pixels_tab [2][16]
vc1op_pixels_func avg_vc1_mspel_pixels_tab [2][16]
h264_chroma_mc_func put_no_rnd_vc1_chroma_pixels_tab [3]
h264_chroma_mc_func avg_no_rnd_vc1_chroma_pixels_tab [3]
void(* sprite_h)(uint8_t *dst, const uint8_t *src, int offset, int advance, int count)
void(* sprite_v_single)(uint8_t *dst, const uint8_t *src1a, const uint8_t *src1b, int offset, int width)
void(* sprite_v_double_noscale)(uint8_t *dst, const uint8_t *src1a, const uint8_t *src2a, int alpha, int width)
void(* sprite_v_double_onescale)(uint8_t *dst, const uint8_t *src1a, const uint8_t *src1b, int offset1, const uint8_t *src2a, int alpha, int width)
void(* sprite_v_double_twoscale)(uint8_t *dst, const uint8_t *src1a, const uint8_t *src1b, int offset1, const uint8_t *src2a, const uint8_t *src2b, int offset2, int alpha, int width)
int(* startcode_find_candidate)(const uint8_t *buf, int size)
Search buf from the start for up to size bytes.
Detailed Description
Definition at line 35 of file vc1dsp.h.
Field Documentation
vc1_inv_trans_8x8
void(* VC1DSPContext::vc1_inv_trans_8x8) (int16_t *b)
Definition at line 37 of file vc1dsp.h.
Referenced by ff_vc1_decode_sequence_header(), ff_vc1dsp_init(), ff_vc1dsp_init_neon(), ff_vc1dsp_init_ppc(), vc1_decode_b_mb(), vc1_decode_b_mb_intfi(), vc1_decode_b_mb_intfr(), vc1_decode_i_blocks(), vc1_decode_i_blocks_adv(), vc1_decode_p_block(), vc1_decode_p_mb(), vc1_decode_p_mb_intfi(), and vc1_decode_p_mb_intfr().
vc1_inv_trans_8x4
void(* VC1DSPContext::vc1_inv_trans_8x4) (uint8_t *dest, int line_size, int16_t *block)
Definition at line 38 of file vc1dsp.h.
Referenced by ff_vc1_decode_sequence_header(), ff_vc1dsp_init(), ff_vc1dsp_init_neon(), ff_vc1dsp_init_ppc(), and vc1_decode_p_block().
vc1_inv_trans_4x8
void(* VC1DSPContext::vc1_inv_trans_4x8) (uint8_t *dest, int line_size, int16_t *block)
Definition at line 39 of file vc1dsp.h.
Referenced by ff_vc1_decode_sequence_header(), ff_vc1dsp_init(), ff_vc1dsp_init_neon(), and vc1_decode_p_block().
vc1_inv_trans_4x4
void(* VC1DSPContext::vc1_inv_trans_4x4) (uint8_t *dest, int line_size, int16_t *block)
Definition at line 40 of file vc1dsp.h.
Referenced by ff_vc1_decode_sequence_header(), ff_vc1dsp_init(), ff_vc1dsp_init_neon(), and vc1_decode_p_block().
vc1_inv_trans_8x8_dc
void(* VC1DSPContext::vc1_inv_trans_8x8_dc) (uint8_t *dest, int line_size, int16_t *block)
Definition at line 41 of file vc1dsp.h.
Referenced by ff_vc1_decode_sequence_header(), ff_vc1dsp_init(), ff_vc1dsp_init_neon(), ff_vc1dsp_init_x86(), and vc1_decode_p_block().
vc1_inv_trans_8x4_dc
void(* VC1DSPContext::vc1_inv_trans_8x4_dc) (uint8_t *dest, int line_size, int16_t *block)
Definition at line 42 of file vc1dsp.h.
Referenced by ff_vc1_decode_sequence_header(), ff_vc1dsp_init(), ff_vc1dsp_init_neon(), ff_vc1dsp_init_x86(), and vc1_decode_p_block().
vc1_inv_trans_4x8_dc
void(* VC1DSPContext::vc1_inv_trans_4x8_dc) (uint8_t *dest, int line_size, int16_t *block)
Definition at line 43 of file vc1dsp.h.
Referenced by ff_vc1_decode_sequence_header(), ff_vc1dsp_init(), ff_vc1dsp_init_neon(), ff_vc1dsp_init_x86(), and vc1_decode_p_block().
vc1_inv_trans_4x4_dc
void(* VC1DSPContext::vc1_inv_trans_4x4_dc) (uint8_t *dest, int line_size, int16_t *block)
Definition at line 44 of file vc1dsp.h.
Referenced by ff_vc1_decode_sequence_header(), ff_vc1dsp_init(), ff_vc1dsp_init_neon(), ff_vc1dsp_init_x86(), and vc1_decode_p_block().
vc1_v_overlap
void(* VC1DSPContext::vc1_v_overlap) (uint8_t *src, int stride)
Definition at line 45 of file vc1dsp.h.
Referenced by ff_vc1dsp_init(), vc1_decode_i_blocks(), and vc1_decode_p_mb().
vc1_h_overlap
void(* VC1DSPContext::vc1_h_overlap) (uint8_t *src, int stride)
Definition at line 46 of file vc1dsp.h.
Referenced by ff_vc1dsp_init(), vc1_decode_i_blocks(), and vc1_decode_p_mb().
vc1_v_s_overlap
void(* VC1DSPContext::vc1_v_s_overlap) (int16_t *top, int16_t *bottom)
Definition at line 47 of file vc1dsp.h.
Referenced by ff_vc1_smooth_overlap_filter_iblk(), and ff_vc1dsp_init().
vc1_h_s_overlap
void(* VC1DSPContext::vc1_h_s_overlap) (int16_t *left, int16_t *right)
Definition at line 48 of file vc1dsp.h.
Referenced by ff_vc1_smooth_overlap_filter_iblk(), and ff_vc1dsp_init().
vc1_v_loop_filter4
void(* VC1DSPContext::vc1_v_loop_filter4) (uint8_t *src, int stride, int pq)
Definition at line 49 of file vc1dsp.h.
Referenced by ff_vc1dsp_init(), and vc1_apply_p_v_loop_filter().
vc1_h_loop_filter4
void(* VC1DSPContext::vc1_h_loop_filter4) (uint8_t *src, int stride, int pq)
Definition at line 50 of file vc1dsp.h.
Referenced by ff_vc1dsp_init(), and vc1_apply_p_h_loop_filter().
vc1_v_loop_filter8
void(* VC1DSPContext::vc1_v_loop_filter8) (uint8_t *src, int stride, int pq)
Definition at line 51 of file vc1dsp.h.
Referenced by ff_vc1_loop_filter_iblk(), ff_vc1_loop_filter_iblk_delayed(), ff_vc1dsp_init(), ff_vc1dsp_init_x86(), and vc1_apply_p_v_loop_filter().
vc1_h_loop_filter8
void(* VC1DSPContext::vc1_h_loop_filter8) (uint8_t *src, int stride, int pq)
Definition at line 52 of file vc1dsp.h.
Referenced by ff_vc1_loop_filter_iblk(), ff_vc1_loop_filter_iblk_delayed(), ff_vc1dsp_init(), ff_vc1dsp_init_x86(), and vc1_apply_p_h_loop_filter().
vc1_v_loop_filter16
void(* VC1DSPContext::vc1_v_loop_filter16) (uint8_t *src, int stride, int pq)
Definition at line 53 of file vc1dsp.h.
Referenced by ff_vc1_loop_filter_iblk(), ff_vc1_loop_filter_iblk_delayed(), ff_vc1dsp_init(), and ff_vc1dsp_init_x86().
vc1_h_loop_filter16
void(* VC1DSPContext::vc1_h_loop_filter16) (uint8_t *src, int stride, int pq)
Definition at line 54 of file vc1dsp.h.
Referenced by ff_vc1_loop_filter_iblk(), ff_vc1_loop_filter_iblk_delayed(), ff_vc1dsp_init(), and ff_vc1dsp_init_x86().
put_vc1_mspel_pixels_tab
vc1op_pixels_func VC1DSPContext::put_vc1_mspel_pixels_tab[2][16]
Definition at line 59 of file vc1dsp.h.
Referenced by ff_vc1_mc_1mv(), ff_vc1_mc_4mv_luma(), ff_vc1dsp_init(), ff_vc1dsp_init_neon(), and ff_vc1dsp_init_x86().
avg_vc1_mspel_pixels_tab
vc1op_pixels_func VC1DSPContext::avg_vc1_mspel_pixels_tab[2][16]
Definition at line 60 of file vc1dsp.h.
Referenced by ff_vc1_interp_mc(), ff_vc1_mc_4mv_luma(), ff_vc1dsp_init(), and ff_vc1dsp_init_x86().
put_no_rnd_vc1_chroma_pixels_tab
h264_chroma_mc_func VC1DSPContext::put_no_rnd_vc1_chroma_pixels_tab[3]
Definition at line 63 of file vc1dsp.h.
Referenced by ff_vc1_mc_1mv(), ff_vc1_mc_4mv_chroma(), ff_vc1_mc_4mv_chroma4(), ff_vc1dsp_init(), ff_vc1dsp_init_aarch64(), ff_vc1dsp_init_neon(), ff_vc1dsp_init_ppc(), and ff_vc1dsp_init_x86().
avg_no_rnd_vc1_chroma_pixels_tab
h264_chroma_mc_func VC1DSPContext::avg_no_rnd_vc1_chroma_pixels_tab[3]
Definition at line 64 of file vc1dsp.h.
Referenced by ff_vc1_interp_mc(), ff_vc1_mc_4mv_chroma4(), ff_vc1dsp_init(), ff_vc1dsp_init_aarch64(), ff_vc1dsp_init_neon(), ff_vc1dsp_init_ppc(), and ff_vc1dsp_init_x86().
sprite_h
void(* VC1DSPContext::sprite_h) (uint8_t *dst, const uint8_t *src, int offset, int advance, int count)
Definition at line 67 of file vc1dsp.h.
Referenced by ff_vc1dsp_init().
sprite_v_single
void(* VC1DSPContext::sprite_v_single) (uint8_t *dst, const uint8_t *src1a, const uint8_t *src1b, int offset, int width)
Definition at line 68 of file vc1dsp.h.
Referenced by ff_vc1dsp_init().
sprite_v_double_noscale
void(* VC1DSPContext::sprite_v_double_noscale) (uint8_t *dst, const uint8_t *src1a, const uint8_t *src2a, int alpha, int width)
Definition at line 69 of file vc1dsp.h.
Referenced by ff_vc1dsp_init().
sprite_v_double_onescale
void(* VC1DSPContext::sprite_v_double_onescale) (uint8_t *dst, const uint8_t *src1a, const uint8_t *src1b, int offset1, const uint8_t *src2a, int alpha, int width)
Definition at line 70 of file vc1dsp.h.
Referenced by ff_vc1dsp_init().
sprite_v_double_twoscale
void(* VC1DSPContext::sprite_v_double_twoscale) (uint8_t *dst, const uint8_t *src1a, const uint8_t *src1b, int offset1, const uint8_t *src2a, const uint8_t *src2b, int offset2, int alpha, int width)
Definition at line 72 of file vc1dsp.h.
Referenced by ff_vc1dsp_init().
startcode_find_candidate
int(* VC1DSPContext::startcode_find_candidate) (const uint8_t *buf, int size)
Search buf from the start for up to size bytes.
Return the index of a zero byte, or >= size if not found. Ideally, use lookahead to filter out any zero bytes that are known to not be followed by one or more further zero bytes and a one byte.
Definition at line 82 of file vc1dsp.h.
Referenced by ff_vc1dsp_init(), ff_vc1dsp_init_arm(), and vc1_parse().
The documentation for this struct was generated from the following file:
libavcodec/vc1dsp.h