FFmpeg: CAVSDSPContext Struct Reference
CAVSDSPContext Struct Reference
#include <libavcodec/cavsdsp.h>
Data Fields
qpel_mc_func put_cavs_qpel_pixels_tab [2][16]
qpel_mc_func avg_cavs_qpel_pixels_tab [2][16]
void(* cavs_filter_lv)(uint8_t *pix, int stride, int alpha, int beta, int tc, int bs1, int bs2)
void(* cavs_filter_lh)(uint8_t *pix, int stride, int alpha, int beta, int tc, int bs1, int bs2)
void(* cavs_filter_cv)(uint8_t *pix, int stride, int alpha, int beta, int tc, int bs1, int bs2)
void(* cavs_filter_ch)(uint8_t *pix, int stride, int alpha, int beta, int tc, int bs1, int bs2)
void(* cavs_idct8_add)(uint8_t *dst, int16_t *block, int stride)
int idct_perm
Detailed Description
Definition at line 30 of file cavsdsp.h.
Field Documentation
put_cavs_qpel_pixels_tab
qpel_mc_func CAVSDSPContext::put_cavs_qpel_pixels_tab[2][16]
Definition at line 31 of file cavsdsp.h.
Referenced by cavsdsp_init_mmx(), ff_cavs_inter(), and ff_cavsdsp_init_x86().
avg_cavs_qpel_pixels_tab
qpel_mc_func CAVSDSPContext::avg_cavs_qpel_pixels_tab[2][16]
Definition at line 32 of file cavsdsp.h.
Referenced by cavsdsp_init_mmx(), ff_cavs_inter(), and ff_cavsdsp_init_x86().
cavs_filter_lv
void(* CAVSDSPContext::cavs_filter_lv) (uint8_t *pix, int stride, int alpha, int beta, int tc, int bs1, int bs2)
Definition at line 33 of file cavsdsp.h.
Referenced by ff_cavs_filter(), and ff_cavsdsp_init().
cavs_filter_lh
void(* CAVSDSPContext::cavs_filter_lh) (uint8_t *pix, int stride, int alpha, int beta, int tc, int bs1, int bs2)
Definition at line 34 of file cavsdsp.h.
Referenced by ff_cavs_filter(), and ff_cavsdsp_init().
cavs_filter_cv
void(* CAVSDSPContext::cavs_filter_cv) (uint8_t *pix, int stride, int alpha, int beta, int tc, int bs1, int bs2)
Definition at line 35 of file cavsdsp.h.
Referenced by ff_cavs_filter(), and ff_cavsdsp_init().
cavs_filter_ch
void(* CAVSDSPContext::cavs_filter_ch) (uint8_t *pix, int stride, int alpha, int beta, int tc, int bs1, int bs2)
Definition at line 36 of file cavsdsp.h.
Referenced by ff_cavs_filter(), and ff_cavsdsp_init().
cavs_idct8_add
void(* CAVSDSPContext::cavs_idct8_add) (uint8_t *dst, int16_t *block, int stride)
Definition at line 37 of file cavsdsp.h.
Referenced by cavsdsp_init_mmx(), decode_residual_block(), and ff_cavsdsp_init().
idct_perm
int CAVSDSPContext::idct_perm
Definition at line 38 of file cavsdsp.h.
Referenced by cavsdsp_init_mmx(), ff_cavs_init(), and ff_cavsdsp_init().
The documentation for this struct was generated from the following file:
libavcodec/cavsdsp.h