FFmpeg: FmtConvertContext Struct Reference
FmtConvertContext Struct Reference
#include <libavcodec/fmtconvert.h>
Data Fields
void(* int32_to_float_fmul_scalar)(float *dst, const int32_t *src, float mul, int len)
Convert an array of int32_t to float and multiply by a float value.
void(* int32_to_float)(float *dst, const int32_t *src, intptr_t len)
Convert an array of int32_t to float.
void(* int32_to_float_fmul_array8)(struct FmtConvertContext *c, float *dst, const int32_t *src, const float *mul, int len)
Convert an array of int32_t to float and multiply by a float value from another array, stepping along the float array once for each 8 integers.
Detailed Description
Definition at line 28 of file fmtconvert.h.
Field Documentation
int32_to_float_fmul_scalar
void(* FmtConvertContext::int32_to_float_fmul_scalar) (float *dst, const int32_t *src, float mul, int len)
Convert an array of int32_t to float and multiply by a float value.
Parameters
dst destination array of float. constraints: 16-byte aligned
src source array of int32_t. constraints: 16-byte aligned
len number of elements to convert. constraints: multiple of 8
Definition at line 38 of file fmtconvert.h.
Referenced by checkasm_check_fmtconvert(), ff_fmt_convert_init(), ff_fmt_convert_init_aarch64(), ff_fmt_convert_init_arm(), ff_fmt_convert_init_mips(), ff_fmt_convert_init_ppc(), ff_fmt_convert_init_x86(), and int32_to_float_fmul_array8_c().
int32_to_float
void(* FmtConvertContext::int32_to_float) (float *dst, const int32_t *src, intptr_t len)
Convert an array of int32_t to float.
Parameters
dst destination array of float. constraints: 32-byte aligned
src source array of int32_t. constraints: 32-byte aligned
len number of elements to convert. constraints: multiple of 8
Definition at line 49 of file fmtconvert.h.
Referenced by ff_fmt_convert_init().
int32_to_float_fmul_array8
void(* FmtConvertContext::int32_to_float_fmul_array8) (struct FmtConvertContext *c, float *dst, const int32_t *src, const float *mul, int len)
Convert an array of int32_t to float and multiply by a float value from another array, stepping along the float array once for each 8 integers.
Parameters
c pointer to FmtConvertContext.
dst destination array of float. constraints: 16-byte aligned
src source array of int32_t. constraints: 16-byte aligned
mul source array of float multipliers.
len number of elements to convert. constraints: multiple of 8
Definition at line 63 of file fmtconvert.h.
Referenced by checkasm_check_fmtconvert(), ff_fmt_convert_init(), ff_fmt_convert_init_aarch64(), ff_fmt_convert_init_arm(), and ff_fmt_convert_init_x86().
The documentation for this struct was generated from the following file:
libavcodec/fmtconvert.h