FFmpeg: H264DSPContext Struct Reference
H264DSPContext Struct Reference
Context for storing H.264 DSP functions.
#include <libavcodec/h264dsp.h>
Data Fields
h264_weight_func weight_h264_pixels_tab [4]
h264_biweight_func biweight_h264_pixels_tab [4]
void(* h264_v_loop_filter_luma)(uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
void(* h264_h_loop_filter_luma)(uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
void(* h264_h_loop_filter_luma_mbaff)(uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
void(* h264_v_loop_filter_luma_intra)(uint8_t *pix, int stride, int alpha, int beta)
void(* h264_h_loop_filter_luma_intra)(uint8_t *pix, int stride, int alpha, int beta)
void(* h264_h_loop_filter_luma_mbaff_intra)(uint8_t *pix, int stride, int alpha, int beta)
void(* h264_v_loop_filter_chroma)(uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
void(* h264_h_loop_filter_chroma)(uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
void(* h264_h_loop_filter_chroma_mbaff)(uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
void(* h264_v_loop_filter_chroma_intra)(uint8_t *pix, int stride, int alpha, int beta)
void(* h264_h_loop_filter_chroma_intra)(uint8_t *pix, int stride, int alpha, int beta)
void(* h264_h_loop_filter_chroma_mbaff_intra)(uint8_t *pix, int stride, int alpha, int beta)
void(* h264_loop_filter_strength)(int16_t bS[2][4][4], uint8_t nnz[40], int8_t ref[2][40], int16_t mv[2][40][2], int bidir, int edges, int step, int mask_mv0, int mask_mv1, int field)
void(* h264_idct_add)(uint8_t *dst, int16_t *block, int stride)
void(* h264_idct8_add)(uint8_t *dst, int16_t *block, int stride)
void(* h264_idct_dc_add)(uint8_t *dst, int16_t *block, int stride)
void(* h264_idct8_dc_add)(uint8_t *dst, int16_t *block, int stride)
void(* h264_idct_add16)(uint8_t *dst, const int *blockoffset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
void(* h264_idct8_add4)(uint8_t *dst, const int *blockoffset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
void(* h264_idct_add8)(uint8_t **dst, const int *blockoffset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
void(* h264_idct_add16intra)(uint8_t *dst, const int *blockoffset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
void(* h264_luma_dc_dequant_idct)(int16_t *output, int16_t *input, int qmul)
void(* h264_chroma_dc_dequant_idct)(int16_t *block, int qmul)
void(* h264_add_pixels8_clear)(uint8_t *dst, int16_t *block, int stride)
void(* h264_add_pixels4_clear)(uint8_t *dst, int16_t *block, int stride)
int(* startcode_find_candidate)(const uint8_t *buf, int size)
Search buf from the start for up to size bytes.
Detailed Description
Context for storing H.264 DSP functions.
Definition at line 42 of file h264dsp.h.
Field Documentation
weight_h264_pixels_tab
h264_weight_func H264DSPContext::weight_h264_pixels_tab[4]
Definition at line 44 of file h264dsp.h.
Referenced by ff_h264dsp_init_aarch64(), ff_h264dsp_init_ppc(), and h264dsp_init_neon().
biweight_h264_pixels_tab
h264_biweight_func H264DSPContext::biweight_h264_pixels_tab[4]
Definition at line 45 of file h264dsp.h.
Referenced by ff_h264dsp_init_aarch64(), ff_h264dsp_init_ppc(), and h264dsp_init_neon().
h264_v_loop_filter_luma
void(* H264DSPContext::h264_v_loop_filter_luma) (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
Definition at line 48 of file h264dsp.h.
Referenced by ff_h264dsp_init_aarch64(), ff_h264dsp_init_ppc(), filter_mb_edgeh(), and h264dsp_init_neon().
h264_h_loop_filter_luma
void(* H264DSPContext::h264_h_loop_filter_luma) (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
Definition at line 50 of file h264dsp.h.
Referenced by ff_h264dsp_init_aarch64(), ff_h264dsp_init_ppc(), filter_mb_edgev(), and h264dsp_init_neon().
h264_h_loop_filter_luma_mbaff
void(* H264DSPContext::h264_h_loop_filter_luma_mbaff) (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
Definition at line 52 of file h264dsp.h.
Referenced by filter_mb_mbaff_edgev().
h264_v_loop_filter_luma_intra
void(* H264DSPContext::h264_v_loop_filter_luma_intra) (uint8_t *pix, int stride, int alpha, int beta)
Definition at line 55 of file h264dsp.h.
Referenced by filter_mb_edgeh().
h264_h_loop_filter_luma_intra
void(* H264DSPContext::h264_h_loop_filter_luma_intra) (uint8_t *pix, int stride, int alpha, int beta)
Definition at line 57 of file h264dsp.h.
Referenced by filter_mb_edgev().
h264_h_loop_filter_luma_mbaff_intra
void(* H264DSPContext::h264_h_loop_filter_luma_mbaff_intra) (uint8_t *pix, int stride, int alpha, int beta)
Definition at line 59 of file h264dsp.h.
Referenced by filter_mb_mbaff_edgev().
h264_v_loop_filter_chroma
void(* H264DSPContext::h264_v_loop_filter_chroma) (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
Definition at line 61 of file h264dsp.h.
Referenced by ff_h264dsp_init_aarch64(), filter_mb_edgech(), and h264dsp_init_neon().
h264_h_loop_filter_chroma
void(* H264DSPContext::h264_h_loop_filter_chroma) (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
Definition at line 63 of file h264dsp.h.
Referenced by ff_h264dsp_init_aarch64(), filter_mb_edgecv(), and h264dsp_init_neon().
h264_h_loop_filter_chroma_mbaff
void(* H264DSPContext::h264_h_loop_filter_chroma_mbaff) (uint8_t *pix, int stride, int alpha, int beta, int8_t *tc0)
Definition at line 65 of file h264dsp.h.
Referenced by filter_mb_mbaff_edgecv().
h264_v_loop_filter_chroma_intra
void(* H264DSPContext::h264_v_loop_filter_chroma_intra) (uint8_t *pix, int stride, int alpha, int beta)
Definition at line 68 of file h264dsp.h.
Referenced by filter_mb_edgech().
h264_h_loop_filter_chroma_intra
void(* H264DSPContext::h264_h_loop_filter_chroma_intra) (uint8_t *pix, int stride, int alpha, int beta)
Definition at line 70 of file h264dsp.h.
Referenced by filter_mb_edgecv().
h264_h_loop_filter_chroma_mbaff_intra
void(* H264DSPContext::h264_h_loop_filter_chroma_mbaff_intra) (uint8_t *pix, int stride, int alpha, int beta)
Definition at line 72 of file h264dsp.h.
Referenced by filter_mb_mbaff_edgecv().
h264_loop_filter_strength
void(* H264DSPContext::h264_loop_filter_strength) (int16_t bS[2][4][4], uint8_t nnz[40], int8_t ref[2][40], int16_t mv[2][40][2], int bidir, int edges, int step, int mask_mv0, int mask_mv1, int field)
Definition at line 75 of file h264dsp.h.
Referenced by ff_h264_filter_mb_fast(), and h264_filter_mb_fast_internal().
h264_idct_add
void(* H264DSPContext::h264_idct_add) (uint8_t *dst, int16_t *block, int stride)
Definition at line 81 of file h264dsp.h.
Referenced by check_idct(), ff_h264dsp_init_aarch64(), ff_h264dsp_init_ppc(), h264dsp_init_neon(), and hl_decode_mb_predict_luma().
h264_idct8_add
void(* H264DSPContext::h264_idct8_add) (uint8_t *dst, int16_t *block, int stride)
Definition at line 83 of file h264dsp.h.
Referenced by check_idct(), ff_h264dsp_init_aarch64(), ff_h264dsp_init_ppc(), h264dsp_init_neon(), and hl_decode_mb_predict_luma().
h264_idct_dc_add
void(* H264DSPContext::h264_idct_dc_add) (uint8_t *dst, int16_t *block, int stride)
Definition at line 85 of file h264dsp.h.
Referenced by check_idct(), ff_h264dsp_init_aarch64(), ff_h264dsp_init_ppc(), h264dsp_init_neon(), and hl_decode_mb_predict_luma().
h264_idct8_dc_add
void(* H264DSPContext::h264_idct8_dc_add) (uint8_t *dst, int16_t *block, int stride)
Definition at line 87 of file h264dsp.h.
Referenced by check_idct(), ff_h264dsp_init_aarch64(), ff_h264dsp_init_ppc(), h264dsp_init_neon(), and hl_decode_mb_predict_luma().
h264_idct_add16
void(* H264DSPContext::h264_idct_add16) (uint8_t *dst, const int *blockoffset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
Definition at line 90 of file h264dsp.h.
Referenced by ff_h264dsp_init_aarch64(), ff_h264dsp_init_ppc(), h264dsp_init_neon(), and hl_decode_mb_idct_luma().
h264_idct8_add4
void(* H264DSPContext::h264_idct8_add4) (uint8_t *dst, const int *blockoffset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
Definition at line 93 of file h264dsp.h.
Referenced by ff_h264dsp_init_aarch64(), ff_h264dsp_init_ppc(), h264dsp_init_neon(), and hl_decode_mb_idct_luma().
h264_idct_add8
void(* H264DSPContext::h264_idct_add8) (uint8_t **dst, const int *blockoffset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
Definition at line 96 of file h264dsp.h.
Referenced by ff_h264dsp_init_aarch64(), ff_h264dsp_init_ppc(), and h264dsp_init_neon().
h264_idct_add16intra
void(* H264DSPContext::h264_idct_add16intra) (uint8_t *dst, const int *blockoffset, int16_t *block, int stride, const uint8_t nnzc[15 *8])
Definition at line 99 of file h264dsp.h.
Referenced by ff_h264dsp_init_aarch64(), ff_h264dsp_init_ppc(), h264dsp_init_neon(), and hl_decode_mb_idct_luma().
h264_luma_dc_dequant_idct
void(* H264DSPContext::h264_luma_dc_dequant_idct) (int16_t *output, int16_t *input, int qmul)
Definition at line 102 of file h264dsp.h.
Referenced by hl_decode_mb_predict_luma().
h264_chroma_dc_dequant_idct
void(* H264DSPContext::h264_chroma_dc_dequant_idct) (int16_t *block, int qmul)
Definition at line 104 of file h264dsp.h.
Referenced by hl_decode_mb().
h264_add_pixels8_clear
void(* H264DSPContext::h264_add_pixels8_clear) (uint8_t *dst, int16_t *block, int stride)
Definition at line 107 of file h264dsp.h.
Referenced by hl_decode_mb_idct_luma(), and hl_decode_mb_predict_luma().
h264_add_pixels4_clear
void(* H264DSPContext::h264_add_pixels4_clear) (uint8_t *dst, int16_t *block, int stride)
Definition at line 108 of file h264dsp.h.
Referenced by hl_decode_mb_idct_luma(), and hl_decode_mb_predict_luma().
startcode_find_candidate
int(* H264DSPContext::startcode_find_candidate) (const uint8_t *buf, int size)
Search buf from the start for up to size bytes.
Return the index of a zero byte, or >= size if not found. Ideally, use lookahead to filter out any zero bytes that are known to not be followed by one or more further zero bytes and a one byte. Better still, filter out any bytes that form the trailing_zero_8bits syntax element too.
Definition at line 117 of file h264dsp.h.
Referenced by ff_h264dsp_init(), ff_h264dsp_init_arm(), and h264_find_frame_end().
The documentation for this struct was generated from the following file:
libavcodec/h264dsp.h