FFmpeg: AVFilterPad Struct Reference
AVFilterPad Struct Reference
A filter pad used for either input or output.
#include <libavfilter/internal.h>
Data Fields
const char * name
Pad name.
enum AVMediaType type
AVFilterPad type.
AVFrame *(* get_video_buffer)(AVFilterLink *link, int w, int h)
Callback function to get a video buffer.
AVFrame *(* get_audio_buffer)(AVFilterLink *link, int nb_samples)
Callback function to get an audio buffer.
int(* filter_frame)(AVFilterLink *link, AVFrame *frame)
Filtering callback.
int(* poll_frame)(AVFilterLink *link)
Frame poll callback.
int(* request_frame)(AVFilterLink *link)
Frame request callback.
int(* config_props)(AVFilterLink *link)
Link configuration callback.
int needs_fifo
The filter expects a fifo to be inserted on its input link, typically because it has a delay.
int needs_writable
The filter expects writable frames from its input link, duplicating data buffers if needed.
Detailed Description
A filter pad used for either input or output.
Definition at line 54 of file internal.h.
Field Documentation
name
const char* AVFilterPad::name
Pad name.
The name is unique among inputs and among outputs, but an input may have the same name as an output. This may be NULL if this pad has no need to ever be referenced by name.
Definition at line 60 of file internal.h.
Referenced by avfilter_graph_dump_to_buf(), avfilter_graph_request_oldest(), avfilter_pad_count(), avfilter_pad_get_name(), close_input(), compressor(), config_output(), decimate_init(), decimate_uninit(), fieldmatch_init(), fieldmatch_uninit(), filter_frame(), gate(), get_aspect_ratio(), graph_check_validity(), init(), join_init(), join_uninit(), movie_common_init(), movie_uninit(), parse_definition(), plot_spectrum_column(), process_frame(), query_formats(), request_frame(), split_init(), split_uninit(), and uninit().
type
enum AVMediaType AVFilterPad::type
AVFilterPad type.
Definition at line 65 of file internal.h.
Referenced by av_buffersrc_parameters_set(), avfilter_link(), avfilter_pad_get_type(), graph_check_validity(), init(), join_init(), movie_common_init(), parse_definition(), and split_init().
get_video_buffer
AVFrame*(* AVFilterPad::get_video_buffer) (AVFilterLink *link, int w, int h)
Callback function to get a video buffer.
If NULL, the filter system will use ff_default_get_video_buffer().
Input video pads only.
Definition at line 73 of file internal.h.
Referenced by ff_get_video_buffer(), and init().
get_audio_buffer
AVFrame*(* AVFilterPad::get_audio_buffer) (AVFilterLink *link, int nb_samples)
Callback function to get an audio buffer.
If NULL, the filter system will use ff_default_get_audio_buffer().
Input audio pads only.
Definition at line 81 of file internal.h.
Referenced by ff_get_audio_buffer(), and init().
filter_frame
int(* AVFilterPad::filter_frame) (AVFilterLink *link, AVFrame *frame)
Filtering callback.
This is where a filter receives a frame with audio/video data and should do its processing.
Input pads only.
Returns
>= 0 on success, a negative AVERROR on error. This function must ensure that frame is properly unreferenced on error if it hasn't been passed on to another filter.
Definition at line 93 of file internal.h.
Referenced by ff_filter_frame_framed(), init(), join_init(), and parse_definition().
poll_frame
int(* AVFilterPad::poll_frame) (AVFilterLink *link)
Frame poll callback.
This returns the number of immediately available samples. It should return a positive value if the next request_frame() is guaranteed to return one frame (with no delay).
Defaults to just calling the source poll_frame() method.
Output pads only.
Definition at line 104 of file internal.h.
Referenced by ff_poll_frame().
request_frame
int(* AVFilterPad::request_frame) (AVFilterLink *link)
Frame request callback.
A call to this should result in some progress towards producing output over the given link. This should return zero on success, and another value on error.
Output pads only.
Definition at line 113 of file internal.h.
Referenced by av_buffersrc_add_frame_internal(), ff_request_frame_to_filter(), init(), movie_common_init(), and parse_definition().
config_props
int(* AVFilterPad::config_props) (AVFilterLink *link)
Link configuration callback.
For output pads, this should set the link properties such as width/height. This should NOT set the format property - that is negotiated between filters by the filter system using the query_formats() callback before this function is called.
For input pads, this should check the properties of the link, and update the filter's internal state as necessary.
For both input and output filters, this should return zero on success, and another value on error.
Definition at line 129 of file internal.h.
Referenced by avfilter_config_links(), decimate_init(), fieldmatch_init(), init(), movie_common_init(), and parse_definition().
needs_fifo
int AVFilterPad::needs_fifo
The filter expects a fifo to be inserted on its input link, typically because it has a delay.
input pads only.
Definition at line 137 of file internal.h.
Referenced by graph_insert_fifos(), and join_init().
needs_writable
int AVFilterPad::needs_writable
The filter expects writable frames from its input link, duplicating data buffers if needed.
input pads only.
Definition at line 145 of file internal.h.
Referenced by ff_filter_frame_framed().
The documentation for this struct was generated from the following file:
libavfilter/internal.h