FFmpeg: BlockDSPContext Struct Reference
BlockDSPContext Struct Reference
#include <libavcodec/blockdsp.h>
Data Fields
void(* clear_block)(int16_t *block)
void(* clear_blocks)(int16_t *blocks)
op_fill_func fill_block_tab [2]
Detailed Description
Definition at line 34 of file blockdsp.h.
Field Documentation
clear_block
void(* BlockDSPContext::clear_block) (int16_t *block)
Definition at line 35 of file blockdsp.h.
Referenced by bink_decode_plane(), binkb_decode_plane(), decode_dc_progressive(), decode_mb(), decode_residual_block(), decode_slice_alpha(), decode_slice_chroma(), decode_slice_luma(), dnxhd_decode_dct_block(), dnxhd_get_blocks(), ff_blockdsp_init(), ff_blockdsp_init_neon(), ff_blockdsp_init_ppc(), ff_blockdsp_init_x86(), get_b_cbp(), get_p_cbp(), h263_decode_block(), jpg_decode_block(), mjpeg_decode_scan(), vc1_decode_intra_block(), vc1_decode_p_block(), vlc_decode_block(), wmv2_add_block(), and x8_decode_intra_mb().
clear_blocks
void(* BlockDSPContext::clear_blocks) (int16_t *blocks)
Definition at line 36 of file blockdsp.h.
Referenced by decode_i_mb(), decode_mb(), ff_blockdsp_init(), ff_blockdsp_init_alpha(), ff_blockdsp_init_neon(), ff_blockdsp_init_ppc(), ff_blockdsp_init_x86(), ff_h263_decode_mb(), ff_wmv2_decode_mb(), h261_decode_mb(), jpg_decode_data(), mpeg4_decode_mb(), mpeg4_decode_partitioned_mb(), mpeg_decode_mb(), mpeg_er_decode_mb(), msmpeg4v12_decode_mb(), msmpeg4v34_decode_mb(), tqi_decode_mb(), vc1_decode_i_blocks(), and vc1_decode_i_blocks_adv().
fill_block_tab
op_fill_func BlockDSPContext::fill_block_tab[2]
Definition at line 38 of file blockdsp.h.
Referenced by bink_decode_plane(), binkb_decode_plane(), decode8x8(), and ff_blockdsp_init().
The documentation for this struct was generated from the following file:
libavcodec/blockdsp.h