FFmpeg: FFPsyModel Struct Reference
FFPsyModel Struct Reference
codec-specific psychoacoustic model implementation
#include <libavcodec/psymodel.h>
Data Fields
const char * name
int(* init)(FFPsyContext *apc)
FFPsyWindowInfo(* window)(FFPsyContext *ctx, const float *audio, const float *la, int channel, int prev_type)
Suggest window sequence for channel.
void(* analyze)(FFPsyContext *ctx, int channel, const float **coeffs, const FFPsyWindowInfo *wi)
Perform psychoacoustic analysis and set band info (threshold, energy) for a group of channels.
void(* end)(FFPsyContext *apc)
Detailed Description
codec-specific psychoacoustic model implementation
Definition at line 114 of file psymodel.h.
Field Documentation
name
const char* FFPsyModel::name
Definition at line 115 of file psymodel.h.
init
int(* FFPsyModel::init) (FFPsyContext *apc)
Definition at line 116 of file psymodel.h.
Referenced by ff_psy_init().
window
FFPsyWindowInfo(* FFPsyModel::window) (FFPsyContext *ctx, const float *audio, const float *la, int channel, int prev_type)
Suggest window sequence for channel.
Parameters
ctx model context
audio samples for the current frame
la lookahead samples (NULL when unavailable)
channel number of channel element to analyze
prev_type previous window type
Returns
suggested window information in a structure
Definition at line 129 of file psymodel.h.
Referenced by aac_encode_frame().
analyze
void(* FFPsyModel::analyze) (FFPsyContext *ctx, int channel, const float **coeffs, const FFPsyWindowInfo *wi)
Perform psychoacoustic analysis and set band info (threshold, energy) for a group of channels.
Parameters
ctx model context
channel channel number of the first channel in the group to perform analysis on
coeffs array of pointers to the transformed coefficients
wi window information for the channels in the group
Definition at line 139 of file psymodel.h.
Referenced by aac_encode_frame().
end
void(* FFPsyModel::end) (FFPsyContext *apc)
Definition at line 141 of file psymodel.h.
Referenced by ff_psy_end().
The documentation for this struct was generated from the following file:
libavcodec/psymodel.h