FFmpeg: AACCoefficientsEncoder Struct Reference
AACCoefficientsEncoder Struct Reference
#include <libavcodec/aacenc.h>
Data Fields
void(* search_for_quantizers)(AVCodecContext *avctx, struct AACEncContext *s, SingleChannelElement *sce, const float lambda)
void(* encode_window_bands_info)(struct AACEncContext *s, SingleChannelElement *sce, int win, int group_len, const float lambda)
void(* quantize_and_encode_band)(struct AACEncContext *s, PutBitContext *pb, const float *in, float *out, int size, int scale_idx, int cb, const float lambda, int rtz)
void(* encode_tns_info)(struct AACEncContext *s, SingleChannelElement *sce)
void(* encode_ltp_info)(struct AACEncContext *s, SingleChannelElement *sce, int common_window)
void(* encode_main_pred)(struct AACEncContext *s, SingleChannelElement *sce)
void(* adjust_common_pred)(struct AACEncContext *s, ChannelElement *cpe)
void(* adjust_common_ltp)(struct AACEncContext *s, ChannelElement *cpe)
void(* apply_main_pred)(struct AACEncContext *s, SingleChannelElement *sce)
void(* apply_tns_filt)(struct AACEncContext *s, SingleChannelElement *sce)
void(* update_ltp)(struct AACEncContext *s, SingleChannelElement *sce)
void(* ltp_insert_new_frame)(struct AACEncContext *s)
void(* set_special_band_scalefactors)(struct AACEncContext *s, SingleChannelElement *sce)
void(* search_for_pns)(struct AACEncContext *s, AVCodecContext *avctx, SingleChannelElement *sce)
void(* mark_pns)(struct AACEncContext *s, AVCodecContext *avctx, SingleChannelElement *sce)
void(* search_for_tns)(struct AACEncContext *s, SingleChannelElement *sce)
void(* search_for_ltp)(struct AACEncContext *s, SingleChannelElement *sce, int common_window)
void(* search_for_ms)(struct AACEncContext *s, ChannelElement *cpe)
void(* search_for_is)(struct AACEncContext *s, AVCodecContext *avctx, ChannelElement *cpe)
void(* search_for_pred)(struct AACEncContext *s, SingleChannelElement *sce)
Detailed Description
Definition at line 55 of file aacenc.h.
Field Documentation
search_for_quantizers
void(* AACCoefficientsEncoder::search_for_quantizers) (AVCodecContext *avctx, struct AACEncContext *s, SingleChannelElement *sce, const float lambda)
Definition at line 56 of file aacenc.h.
Referenced by aac_encode_frame(), and ff_aac_coder_init_mips().
encode_window_bands_info
void(* AACCoefficientsEncoder::encode_window_bands_info) (struct AACEncContext *s, SingleChannelElement *sce, int win, int group_len, const float lambda)
Definition at line 58 of file aacenc.h.
Referenced by encode_band_info(), and ff_aac_coder_init_mips().
quantize_and_encode_band
void(* AACCoefficientsEncoder::quantize_and_encode_band) (struct AACEncContext *s, PutBitContext *pb, const float *in, float *out, int size, int scale_idx, int cb, const float lambda, int rtz)
Definition at line 60 of file aacenc.h.
Referenced by encode_spectral_coeffs(), and ff_aac_coder_init_mips().
encode_tns_info
void(* AACCoefficientsEncoder::encode_tns_info) (struct AACEncContext *s, SingleChannelElement *sce)
Definition at line 62 of file aacenc.h.
Referenced by encode_individual_channel().
encode_ltp_info
void(* AACCoefficientsEncoder::encode_ltp_info) (struct AACEncContext *s, SingleChannelElement *sce, int common_window)
Definition at line 63 of file aacenc.h.
Referenced by aac_encode_frame(), and encode_individual_channel().
encode_main_pred
void(* AACCoefficientsEncoder::encode_main_pred) (struct AACEncContext *s, SingleChannelElement *sce)
Definition at line 64 of file aacenc.h.
Referenced by aac_encode_frame(), and encode_individual_channel().
adjust_common_pred
void(* AACCoefficientsEncoder::adjust_common_pred) (struct AACEncContext *s, ChannelElement *cpe)
Definition at line 65 of file aacenc.h.
Referenced by aac_encode_frame().
adjust_common_ltp
void(* AACCoefficientsEncoder::adjust_common_ltp) (struct AACEncContext *s, ChannelElement *cpe)
Definition at line 66 of file aacenc.h.
Referenced by aac_encode_frame().
apply_main_pred
void(* AACCoefficientsEncoder::apply_main_pred) (struct AACEncContext *s, SingleChannelElement *sce)
Definition at line 67 of file aacenc.h.
Referenced by aac_encode_frame().
apply_tns_filt
void(* AACCoefficientsEncoder::apply_tns_filt) (struct AACEncContext *s, SingleChannelElement *sce)
Definition at line 68 of file aacenc.h.
Referenced by aac_encode_frame().
update_ltp
void(* AACCoefficientsEncoder::update_ltp) (struct AACEncContext *s, SingleChannelElement *sce)
Definition at line 69 of file aacenc.h.
Referenced by aac_encode_frame().
ltp_insert_new_frame
void(* AACCoefficientsEncoder::ltp_insert_new_frame) (struct AACEncContext *s)
Definition at line 70 of file aacenc.h.
Referenced by aac_encode_frame().
set_special_band_scalefactors
void(* AACCoefficientsEncoder::set_special_band_scalefactors) (struct AACEncContext *s, SingleChannelElement *sce)
Definition at line 71 of file aacenc.h.
Referenced by encode_band_info().
search_for_pns
void(* AACCoefficientsEncoder::search_for_pns) (struct AACEncContext *s, AVCodecContext *avctx, SingleChannelElement *sce)
Definition at line 72 of file aacenc.h.
Referenced by aac_encode_frame().
mark_pns
void(* AACCoefficientsEncoder::mark_pns) (struct AACEncContext *s, AVCodecContext *avctx, SingleChannelElement *sce)
Definition at line 73 of file aacenc.h.
Referenced by aac_encode_frame().
search_for_tns
void(* AACCoefficientsEncoder::search_for_tns) (struct AACEncContext *s, SingleChannelElement *sce)
Definition at line 74 of file aacenc.h.
Referenced by aac_encode_frame().
search_for_ltp
void(* AACCoefficientsEncoder::search_for_ltp) (struct AACEncContext *s, SingleChannelElement *sce, int common_window)
Definition at line 75 of file aacenc.h.
Referenced by aac_encode_frame().
search_for_ms
void(* AACCoefficientsEncoder::search_for_ms) (struct AACEncContext *s, ChannelElement *cpe)
Definition at line 76 of file aacenc.h.
Referenced by aac_encode_frame(), and ff_aac_coder_init_mips().
search_for_is
void(* AACCoefficientsEncoder::search_for_is) (struct AACEncContext *s, AVCodecContext *avctx, ChannelElement *cpe)
Definition at line 77 of file aacenc.h.
Referenced by aac_encode_frame().
search_for_pred
void(* AACCoefficientsEncoder::search_for_pred) (struct AACEncContext *s, SingleChannelElement *sce)
Definition at line 78 of file aacenc.h.
Referenced by aac_encode_frame().
The documentation for this struct was generated from the following file:
libavcodec/aacenc.h