FFmpeg: DCTContext Struct Reference
DCTContext Struct Reference
#include <libavcodec/dct.h>
Data Fields
int nbits
int inverse
RDFTContext rdft
const float * costab
FFTSample * csc2
void(* dct_calc)(struct DCTContext *s, FFTSample *data)
void(* dct32)(FFTSample *out, const FFTSample *in)
Detailed Description
Definition at line 31 of file dct.h.
Field Documentation
nbits
int DCTContext::nbits
Definition at line 32 of file dct.h.
Referenced by dct_calc_I_c(), dct_calc_II_c(), dct_calc_III_c(), dst_calc_I_c(), and ff_dct_init().
inverse
int DCTContext::inverse
Definition at line 33 of file dct.h.
Referenced by ff_dct_init().
rdft
RDFTContext DCTContext::rdft
Definition at line 34 of file dct.h.
Referenced by dct_calc_I_c(), dct_calc_II_c(), dct_calc_III_c(), dst_calc_I_c(), ff_dct_end(), and ff_dct_init().
costab
const float* DCTContext::costab
Definition at line 35 of file dct.h.
Referenced by ff_dct_init().
csc2
FFTSample* DCTContext::csc2
Definition at line 36 of file dct.h.
Referenced by dct_calc_III_c(), ff_dct_end(), and ff_dct_init().
dct_calc
void(* DCTContext::dct_calc) (struct DCTContext *s, FFTSample *data)
Definition at line 37 of file dct.h.
Referenced by av_fft_end(), calc_input_response(), decode_block(), ff_dct_init(), and fft_end().
dct32
void(* DCTContext::dct32) (FFTSample *out, const FFTSample *in)
Definition at line 38 of file dct.h.
Referenced by dct32_func(), ff_dct_init(), ff_dct_init_x86(), and ff_mpadsp_init().
The documentation for this struct was generated from the following file:
libavcodec/dct.h