FFmpeg: AVCodecParser Struct Reference
AVCodecParser Struct Reference
libavcodec » Decoding » Frame parsing
#include <libavcodec/avcodec.h>
Data Fields
int codec_ids [5]
int priv_data_size
int(* parser_init)(AVCodecParserContext *s)
int(* parser_parse)(AVCodecParserContext *s, AVCodecContext *avctx, const uint8_t **poutbuf, int *poutbuf_size, const uint8_t *buf, int buf_size)
void(* parser_close)(AVCodecParserContext *s)
int(* split)(AVCodecContext *avctx, const uint8_t *buf, int buf_size)
struct AVCodecParser * next
Detailed Description
Definition at line 5167 of file avcodec.h.
Field Documentation
codec_ids
int AVCodecParser::codec_ids[5]
Definition at line 5168 of file avcodec.h.
Referenced by av_parser_init(), av_parser_parse2(), av_vorbis_parse_init(), and rv34_parse().
priv_data_size
int AVCodecParser::priv_data_size
Definition at line 5169 of file avcodec.h.
Referenced by av_parser_init().
parser_init
int(* AVCodecParser::parser_init) (AVCodecParserContext *s)
Definition at line 5170 of file avcodec.h.
Referenced by av_parser_init().
parser_parse
int(* AVCodecParser::parser_parse) (AVCodecParserContext *s, AVCodecContext *avctx, const uint8_t **poutbuf, int *poutbuf_size, const uint8_t *buf, int buf_size)
Definition at line 5173 of file avcodec.h.
Referenced by av_parser_parse2().
parser_close
void(* AVCodecParser::parser_close) (AVCodecParserContext *s)
Definition at line 5177 of file avcodec.h.
Referenced by av_parser_close().
split
int(* AVCodecParser::split) (AVCodecContext *avctx, const uint8_t *buf, int buf_size)
Definition at line 5178 of file avcodec.h.
Referenced by av_parser_change(), avformat_find_stream_info(), and remove_extradata().
next
struct AVCodecParser* AVCodecParser::next
Definition at line 5179 of file avcodec.h.
Referenced by av_parser_init(), av_parser_next(), and av_register_codec_parser().
The documentation for this struct was generated from the following file:
libavcodec/avcodec.h