FFmpeg: PSDSPContext Struct Reference
PSDSPContext Struct Reference
#include <libavcodec/aacpsdsp.h>
Data Fields
void(* add_squares)(INTFLOAT *dst, const INTFLOAT(*src)[2], int n)
void(* mul_pair_single)(INTFLOAT(*dst)[2], INTFLOAT(*src0)[2], INTFLOAT *src1, int n)
void(* hybrid_analysis)(INTFLOAT(*out)[2], INTFLOAT(*in)[2], const INTFLOAT(*filter)[8][2], int stride, int n)
void(* hybrid_analysis_ileave)(INTFLOAT(*out)[32][2], INTFLOAT L[2][38][64], int i, int len)
void(* hybrid_synthesis_deint)(INTFLOAT out[2][38][64], INTFLOAT(*in)[32][2], int i, int len)
void(* decorrelate)(INTFLOAT(*out)[2], INTFLOAT(*delay)[2], INTFLOAT(*ap_delay)[PS_QMF_TIME_SLOTS+PS_MAX_AP_DELAY][2], const INTFLOAT phi_fract[2], const INTFLOAT(*Q_fract)[2], const INTFLOAT *transient_gain, INTFLOAT g_decay_slope, int len)
void(* stereo_interpolate [2])(INTFLOAT(*l)[2], INTFLOAT(*r)[2], INTFLOAT h[2][4], INTFLOAT h_step[2][4], int len)
Detailed Description
Definition at line 30 of file aacpsdsp.h.
Field Documentation
add_squares
void(* PSDSPContext::add_squares) (INTFLOAT *dst, const INTFLOAT(*src)[2], int n)
Definition at line 31 of file aacpsdsp.h.
Referenced by decorrelation(), ff_psdsp_init_arm(), ff_psdsp_init_mips(), and ff_psdsp_init_x86().
mul_pair_single
void(* PSDSPContext::mul_pair_single) (INTFLOAT(*dst)[2], INTFLOAT(*src0)[2], INTFLOAT *src1, int n)
Definition at line 32 of file aacpsdsp.h.
Referenced by decorrelation(), ff_psdsp_init_arm(), ff_psdsp_init_mips(), and ff_psdsp_init_x86().
hybrid_analysis
void(* PSDSPContext::hybrid_analysis) (INTFLOAT(*out)[2], INTFLOAT(*in)[2], const INTFLOAT(*filter)[8][2], int stride, int n)
Definition at line 34 of file aacpsdsp.h.
Referenced by ff_psdsp_init_arm(), ff_psdsp_init_x86(), hybrid4_8_12_cx(), and hybrid6_cx().
hybrid_analysis_ileave
void(* PSDSPContext::hybrid_analysis_ileave) (INTFLOAT(*out)[32][2], INTFLOAT L[2][38][64], int i, int len)
Definition at line 37 of file aacpsdsp.h.
Referenced by ff_psdsp_init_mips(), and hybrid_analysis().
hybrid_synthesis_deint
void(* PSDSPContext::hybrid_synthesis_deint) (INTFLOAT out[2][38][64], INTFLOAT(*in)[32][2], int i, int len)
Definition at line 39 of file aacpsdsp.h.
Referenced by ff_psdsp_init_arm(), ff_psdsp_init_mips(), and hybrid_synthesis().
decorrelate
void(* PSDSPContext::decorrelate) (INTFLOAT(*out)[2], INTFLOAT(*delay)[2], INTFLOAT(*ap_delay)[PS_QMF_TIME_SLOTS+PS_MAX_AP_DELAY][2], const INTFLOAT phi_fract[2], const INTFLOAT(*Q_fract)[2], const INTFLOAT *transient_gain, INTFLOAT g_decay_slope, int len)
Definition at line 41 of file aacpsdsp.h.
Referenced by decorrelation(), and ff_psdsp_init_mips().
stereo_interpolate
void(* PSDSPContext::stereo_interpolate[2])(INTFLOAT(*l)[2], INTFLOAT(*r)[2], INTFLOAT h[2][4], INTFLOAT h_step[2][4], int len)
Definition at line 47 of file aacpsdsp.h.
Referenced by ff_psdsp_init_arm(), ff_psdsp_init_mips(), ff_psdsp_init_x86(), and stereo_processing().
The documentation for this struct was generated from the following file:
libavcodec/aacpsdsp.h