FFmpeg: MPADSPContext Struct Reference
MPADSPContext Struct Reference
#include <libavcodec/mpegaudiodsp.h>
Data Fields
void(* apply_window_float)(float *synth_buf, float *window, int *dither_state, float *samples, int incr)
void(* apply_window_fixed)(int32_t *synth_buf, int32_t *window, int *dither_state, int16_t *samples, int incr)
void(* dct32_float)(float *dst, const float *src)
void(* dct32_fixed)(int *dst, const int *src)
void(* imdct36_blocks_float)(float *out, float *buf, float *in, int count, int switch_point, int block_type)
void(* imdct36_blocks_fixed)(int *out, int *buf, int *in, int count, int switch_point, int block_type)
Detailed Description
Definition at line 25 of file mpegaudiodsp.h.
Field Documentation
apply_window_float
void(* MPADSPContext::apply_window_float) (float *synth_buf, float *window, int *dither_state, float *samples, int incr)
Definition at line 26 of file mpegaudiodsp.h.
Referenced by ff_mpadsp_init(), ff_mpadsp_init_aarch64(), ff_mpadsp_init_mipsfpu(), ff_mpadsp_init_ppc(), and ff_mpadsp_init_x86().
apply_window_fixed
void(* MPADSPContext::apply_window_fixed) (int32_t *synth_buf, int32_t *window, int *dither_state, int16_t *samples, int incr)
Definition at line 28 of file mpegaudiodsp.h.
Referenced by ff_mpadsp_init(), ff_mpadsp_init_aarch64(), ff_mpadsp_init_arm(), and ff_mpadsp_init_mipsdsp().
dct32_float
void(* MPADSPContext::dct32_float) (float *dst, const float *src)
Definition at line 30 of file mpegaudiodsp.h.
Referenced by ff_mpadsp_init(), and ff_mpadsp_init_mipsfpu().
dct32_fixed
void(* MPADSPContext::dct32_fixed) (int *dst, const int *src)
Definition at line 31 of file mpegaudiodsp.h.
Referenced by ff_mpadsp_init().
imdct36_blocks_float
void(* MPADSPContext::imdct36_blocks_float) (float *out, float *buf, float *in, int count, int switch_point, int block_type)
Definition at line 33 of file mpegaudiodsp.h.
Referenced by ff_mpadsp_init(), ff_mpadsp_init_mipsfpu(), and ff_mpadsp_init_x86().
imdct36_blocks_fixed
void(* MPADSPContext::imdct36_blocks_fixed) (int *out, int *buf, int *in, int count, int switch_point, int block_type)
Definition at line 35 of file mpegaudiodsp.h.
Referenced by ff_mpadsp_init(), and ff_mpadsp_init_mipsdsp().
The documentation for this struct was generated from the following file:
libavcodec/mpegaudiodsp.h