FFmpeg: HuffYUVEncDSPContext Struct Reference
HuffYUVEncDSPContext Struct Reference
#include <libavcodec/huffyuvencdsp.h>
Data Fields
void(* diff_bytes)(uint8_t *dst, const uint8_t *src1, const uint8_t *src2, intptr_t w)
void(* sub_hfyu_median_pred)(uint8_t *dst, const uint8_t *src1, const uint8_t *src2, intptr_t w, int *left, int *left_top)
Subtract HuffYUV's variant of median prediction.
Detailed Description
Definition at line 24 of file huffyuvencdsp.h.
Field Documentation
diff_bytes
void(* HuffYUVEncDSPContext::diff_bytes) (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, intptr_t w)
Definition at line 25 of file huffyuvencdsp.h.
Referenced by diff_bytes(), encode_frame(), ff_huffyuvencdsp_init(), ff_huffyuvencdsp_init_x86(), png_filter_row(), sub_left_prediction(), sub_left_prediction_bgr32(), and sub_left_prediction_rgb24().
sub_hfyu_median_pred
void(* HuffYUVEncDSPContext::sub_hfyu_median_pred) (uint8_t *dst, const uint8_t *src1, const uint8_t *src2, intptr_t w, int *left, int *left_top)
Subtract HuffYUV's variant of median prediction.
Note, this might read from src1[-1], src2[-1].
Definition at line 33 of file huffyuvencdsp.h.
Referenced by encode_frame(), ff_huffyuvencdsp_init(), ff_huffyuvencdsp_init_x86(), median_predict(), and sub_median_prediction().
The documentation for this struct was generated from the following file:
libavcodec/huffyuvencdsp.h