FFmpeg: LPCContext Struct Reference
LPCContext Struct Reference
#include <libavcodec/lpc.h>
Data Fields
int blocksize
int max_order
enum FFLPCType lpc_type
double * windowed_buffer
double * windowed_samples
void(* lpc_apply_welch_window)(const int32_t *data, int len, double *w_data)
Apply a Welch window to an array of input samples.
void(* lpc_compute_autocorr)(const double *data, int len, int lag, double *autoc)
Perform autocorrelation on input samples with delay of 0 to lag.
LLSModel lls_models [2]
Detailed Description
Definition at line 52 of file lpc.h.
Field Documentation
blocksize
int LPCContext::blocksize
Definition at line 53 of file lpc.h.
Referenced by ff_lpc_calc_coefs(), ff_lpc_calc_ref_coefs(), and ff_lpc_init().
max_order
int LPCContext::max_order
Definition at line 54 of file lpc.h.
Referenced by compute_lpc_coefs(), compute_ref_coefs(), ff_lpc_calc_coefs(), and ff_lpc_init().
lpc_type
enum FFLPCType LPCContext::lpc_type
Definition at line 55 of file lpc.h.
Referenced by ff_lpc_calc_coefs(), and ff_lpc_init().
windowed_buffer
double* LPCContext::windowed_buffer
Definition at line 56 of file lpc.h.
Referenced by ff_lpc_end(), and ff_lpc_init().
windowed_samples
double* LPCContext::windowed_samples
Definition at line 57 of file lpc.h.
Referenced by ff_lpc_calc_coefs(), ff_lpc_calc_ref_coefs(), ff_lpc_calc_ref_coefs_f(), and ff_lpc_init().
lpc_apply_welch_window
void(* LPCContext::lpc_apply_welch_window) (const int32_t *data, int len, double *w_data)
Apply a Welch window to an array of input samples.
The output samples have the same scale as the input, but are in double sample format.
Parameters
data input samples
len number of input samples
w_data output samples
Definition at line 67 of file lpc.h.
Referenced by ff_lpc_calc_coefs(), ff_lpc_calc_ref_coefs(), ff_lpc_init(), and ff_lpc_init_x86().
lpc_compute_autocorr
void(* LPCContext::lpc_compute_autocorr) (const double *data, int len, int lag, double *autoc)
Perform autocorrelation on input samples with delay of 0 to lag.
Parameters
data input samples. constraints: no alignment needed, but must have at least lag*sizeof(double) valid bytes preceding it, and size must be at least (len+1)*sizeof(double) if data is 16-byte aligned or (len+2)*sizeof(double) if data is unaligned.
len number of input samples to process
lag maximum delay to calculate
autoc output autocorrelation coefficients. constraints: array size must be at least lag+1.
Definition at line 82 of file lpc.h.
Referenced by ff_lpc_calc_coefs(), ff_lpc_calc_ref_coefs(), ff_lpc_calc_ref_coefs_f(), ff_lpc_init(), and ff_lpc_init_x86().
lls_models
LLSModel LPCContext::lls_models[2]
Definition at line 86 of file lpc.h.
Referenced by ff_lpc_calc_coefs().
The documentation for this struct was generated from the following file:
libavcodec/lpc.h