FFmpeg: TTADSPContext Struct Reference
TTADSPContext Struct Reference
#include <libavcodec/ttadsp.h>
Data Fields
void(* filter_process)(int32_t *qm, int32_t *dx, int32_t *dl, int32_t *error, int32_t *in, int32_t shift, int32_t round)
Detailed Description
Definition at line 24 of file ttadsp.h.
Field Documentation
filter_process
void(* TTADSPContext::filter_process) (int32_t *qm, int32_t *dx, int32_t *dl, int32_t *error, int32_t *in, int32_t shift, int32_t round)
Definition at line 25 of file ttadsp.h.
Referenced by ff_ttadsp_init(), ff_ttadsp_init_x86(), and tta_decode_frame().
The documentation for this struct was generated from the following file:
libavcodec/ttadsp.h