FFmpeg: SnowDWTContext Struct Reference
SnowDWTContext Struct Reference
#include <libavcodec/snow_dwt.h>
Data Fields
void(* vertical_compose97i)(IDWTELEM *b0, IDWTELEM *b1, IDWTELEM *b2, IDWTELEM *b3, IDWTELEM *b4, IDWTELEM *b5, int width)
void(* horizontal_compose97i)(IDWTELEM *b, IDWTELEM *temp, int width)
void(* inner_add_yblock)(const uint8_t *obmc, const int obmc_stride, uint8_t **block, int b_w, int b_h, int src_x, int src_y, int src_stride, slice_buffer *sb, int add, uint8_t *dst8)
Detailed Description
Definition at line 54 of file snow_dwt.h.
Field Documentation
vertical_compose97i
void(* SnowDWTContext::vertical_compose97i) (IDWTELEM *b0, IDWTELEM *b1, IDWTELEM *b2, IDWTELEM *b3, IDWTELEM *b4, IDWTELEM *b5, int width)
Definition at line 55 of file snow_dwt.h.
Referenced by ff_dwt_init(), ff_dwt_init_x86(), and spatial_compose97i_dy_buffered().
horizontal_compose97i
void(* SnowDWTContext::horizontal_compose97i) (IDWTELEM *b, IDWTELEM *temp, int width)
Definition at line 58 of file snow_dwt.h.
Referenced by ff_dwt_init(), ff_dwt_init_x86(), and spatial_compose97i_dy_buffered().
inner_add_yblock
void(* SnowDWTContext::inner_add_yblock) (const uint8_t *obmc, const int obmc_stride, uint8_t **block, int b_w, int b_h, int src_x, int src_y, int src_stride, slice_buffer *sb, int add, uint8_t *dst8)
Definition at line 59 of file snow_dwt.h.
Referenced by add_yblock(), ff_dwt_init(), and ff_dwt_init_x86().
The documentation for this struct was generated from the following file:
libavcodec/snow_dwt.h