FFmpeg: AudioDSPContext Struct Reference
AudioDSPContext Struct Reference
#include <libavcodec/audiodsp.h>
Data Fields
int32_t(* scalarproduct_int16)(const int16_t *v1, const int16_t *v2, int len)
Calculate scalar product of two vectors.
void(* vector_clip_int32)(int32_t *dst, const int32_t *src, int32_t min, int32_t max, unsigned int len)
Clip each element in an array of int32_t to a given minimum and maximum value.
void(* vector_clipf)(float *dst, const float *src, float min, float max, int len)
Detailed Description
Definition at line 24 of file audiodsp.h.
Field Documentation
scalarproduct_int16
int32_t(* AudioDSPContext::scalarproduct_int16) (const int16_t *v1, const int16_t *v2, int len)
Calculate scalar product of two vectors.
Parameters
len length of vectors, should be multiple of 16
Definition at line 29 of file audiodsp.h.
Referenced by decode_subframe(), decoder_init(), decorrelate(), ff_acelp_decode_gain_code(), ff_audiodsp_init(), ff_audiodsp_init_neon(), ff_audiodsp_init_ppc(), ff_audiodsp_init_x86(), ff_irms(), get_tilt_comp(), and long_term_filter().
vector_clip_int32
void(* AudioDSPContext::vector_clip_int32) (int32_t *dst, const int32_t *src, int32_t min, int32_t max, unsigned int len)
Clip each element in an array of int32_t to a given minimum and maximum value.
Parameters
dst destination array constraints: 16-byte aligned
src source array constraints: 16-byte aligned
min minimum value constraints: must be in the range [-(1 << 24), 1 << 24]
max maximum value constraints: must be in the range [-(1 << 24), 1 << 24]
len number of elements in the array constraints: multiple of 32 greater than zero
Definition at line 46 of file audiodsp.h.
Referenced by clip_coefficients(), ff_audiodsp_init(), ff_audiodsp_init_neon(), and ff_audiodsp_init_x86().
vector_clipf
void(* AudioDSPContext::vector_clipf) (float *dst, const float *src, float min, float max, int len)
Definition at line 49 of file audiodsp.h.
Referenced by clip_coefficients(), ff_audiodsp_init(), ff_audiodsp_init_neon(), ff_audiodsp_init_x86(), and saturate_output_float().
The documentation for this struct was generated from the following file:
libavcodec/audiodsp.h