FFmpeg: MLPDSPContext Struct Reference
MLPDSPContext Struct Reference
#include <libavcodec/mlpdsp.h>
Data Fields
void(* mlp_filter_channel)(int32_t *state, const int32_t *coeff, int firorder, int iirorder, unsigned int filter_shift, int32_t mask, int blocksize, int32_t *sample_buffer)
void(* mlp_rematrix_channel)(int32_t *samples, const int32_t *coeffs, const uint8_t *bypassed_lsbs, const int8_t *noise_buffer, int index, unsigned int dest_ch, uint16_t blockpos, unsigned int maxchan, int matrix_noise_shift, int access_unit_size_pow2, int32_t mask)
int32_t(*(* mlp_select_pack_output)(uint8_t *ch_assign, int8_t *output_shift, uint8_t max_matrix_channel, int is32))(int32_t
int32_t(*(* uint16_t)
int32_t(*(*) int32_t void)
int32_t(* mlp_pack_output)(int32_t lossless_check_data, uint16_t blockpos, int32_t(*sample_buffer)[MAX_CHANNELS], void *data, uint8_t *ch_assign, int8_t *output_shift, uint8_t max_matrix_channel, int is32)
Detailed Description
Definition at line 49 of file mlpdsp.h.
Field Documentation
mlp_filter_channel
void(* MLPDSPContext::mlp_filter_channel) (int32_t *state, const int32_t *coeff, int firorder, int iirorder, unsigned int filter_shift, int32_t mask, int blocksize, int32_t *sample_buffer)
Definition at line 50 of file mlpdsp.h.
Referenced by ff_mlpdsp_init(), ff_mlpdsp_init_arm(), ff_mlpdsp_init_x86(), and filter_channel().
mlp_rematrix_channel
void(* MLPDSPContext::mlp_rematrix_channel) (int32_t *samples, const int32_t *coeffs, const uint8_t *bypassed_lsbs, const int8_t *noise_buffer, int index, unsigned int dest_ch, uint16_t blockpos, unsigned int maxchan, int matrix_noise_shift, int access_unit_size_pow2, int32_t mask)
Definition at line 54 of file mlpdsp.h.
Referenced by ff_mlpdsp_init(), ff_mlpdsp_init_arm(), ff_mlpdsp_init_x86(), and output_data().
mlp_select_pack_output
int32_t(*(* MLPDSPContext::mlp_select_pack_output) (uint8_t *ch_assign, int8_t *output_shift, uint8_t max_matrix_channel, int is32))(int32_t
Definition at line 65 of file mlpdsp.h.
Referenced by ff_mlpdsp_init(), ff_mlpdsp_init_arm(), read_decoding_params(), read_major_sync(), and read_restart_header().
uint16_t
int32_t(*(* MLPDSPContext::uint16_t)
Definition at line 68 of file mlpdsp.h.
void
int32_t(*(*) int32_t MLPDSPContext::void)
Definition at line 68 of file mlpdsp.h.
mlp_pack_output
int32_t(* MLPDSPContext::mlp_pack_output) (int32_t lossless_check_data, uint16_t blockpos, int32_t(*sample_buffer)[MAX_CHANNELS], void *data, uint8_t *ch_assign, int8_t *output_shift, uint8_t max_matrix_channel, int is32)
Definition at line 69 of file mlpdsp.h.
Referenced by ff_mlpdsp_init(), output_data(), read_decoding_params(), read_major_sync(), and read_restart_header().
The documentation for this struct was generated from the following file:
libavcodec/mlpdsp.h