FFmpeg: SynthFilterContext Struct Reference
SynthFilterContext Struct Reference
#include <libavcodec/synth_filter.h>
Data Fields
void(* synth_filter_float)(FFTContext *imdct, float *synth_buf_ptr, int *synth_buf_offset, float synth_buf2[32], const float window[512], float out[32], const float in[32], float scale)
void(* synth_filter_float_64)(FFTContext *imdct, float *synth_buf_ptr, int *synth_buf_offset, float synth_buf2[64], const float window[1024], float out[64], const float in[64], float scale)
void(* synth_filter_fixed)(DCADCTContext *imdct, int32_t *synth_buf_ptr, int *synth_buf_offset, int32_t synth_buf2[32], const int32_t window[512], int32_t out[32], const int32_t in[32])
void(* synth_filter_fixed_64)(DCADCTContext *imdct, int32_t *synth_buf_ptr, int *synth_buf_offset, int32_t synth_buf2[64], const int32_t window[1024], int32_t out[64], const int32_t in[64])
Detailed Description
Definition at line 27 of file synth_filter.h.
Field Documentation
synth_filter_float
void(* SynthFilterContext::synth_filter_float) (FFTContext *imdct, float *synth_buf_ptr, int *synth_buf_offset, float synth_buf2[32], const float window[512], float out[32], const float in[32], float scale)
Definition at line 28 of file synth_filter.h.
Referenced by checkasm_check_synth_filter(), ff_synth_filter_init(), ff_synth_filter_init_aarch64(), ff_synth_filter_init_arm(), ff_synth_filter_init_x86(), and sub_qmf32_float_c().
synth_filter_float_64
void(* SynthFilterContext::synth_filter_float_64) (FFTContext *imdct, float *synth_buf_ptr, int *synth_buf_offset, float synth_buf2[64], const float window[1024], float out[64], const float in[64], float scale)
Definition at line 33 of file synth_filter.h.
Referenced by ff_synth_filter_init(), and sub_qmf64_float_c().
synth_filter_fixed
void(* SynthFilterContext::synth_filter_fixed) (DCADCTContext *imdct, int32_t *synth_buf_ptr, int *synth_buf_offset, int32_t synth_buf2[32], const int32_t window[512], int32_t out[32], const int32_t in[32])
Definition at line 37 of file synth_filter.h.
Referenced by ff_synth_filter_init(), and sub_qmf32_fixed_c().
synth_filter_fixed_64
void(* SynthFilterContext::synth_filter_fixed_64) (DCADCTContext *imdct, int32_t *synth_buf_ptr, int *synth_buf_offset, int32_t synth_buf2[64], const int32_t window[1024], int32_t out[64], const int32_t in[64])
Definition at line 41 of file synth_filter.h.
Referenced by ff_synth_filter_init(), and sub_qmf64_fixed_c().
The documentation for this struct was generated from the following file:
libavcodec/synth_filter.h