FFmpeg: OMXContext Struct Reference
OMXContext Struct Reference
Data Fields
void * lib
void * lib2
OMX_ERRORTYPE(* ptr_Init)(void)
OMX_ERRORTYPE(* ptr_Deinit)(void)
OMX_ERRORTYPE(* ptr_ComponentNameEnum)(OMX_STRING, OMX_U32, OMX_U32)
OMX_ERRORTYPE(* ptr_GetHandle)(OMX_HANDLETYPE *, OMX_STRING, OMX_PTR, OMX_CALLBACKTYPE *)
OMX_ERRORTYPE(* ptr_FreeHandle)(OMX_HANDLETYPE)
OMX_ERRORTYPE(* ptr_GetComponentsOfRole)(OMX_STRING, OMX_U32 *, OMX_U8 **)
OMX_ERRORTYPE(* ptr_GetRolesOfComponent)(OMX_STRING, OMX_U32 *, OMX_U8 **)
void(* host_init)(void)
Detailed Description
Definition at line 76 of file omx.c.
Field Documentation
lib
void* OMXContext::lib
Definition at line 77 of file omx.c.
Referenced by omx_deinit(), and omx_try_load().
lib2
void* OMXContext::lib2
Definition at line 78 of file omx.c.
Referenced by omx_try_load().
ptr_Init
OMX_ERRORTYPE(* OMXContext::ptr_Init) (void)
Definition at line 79 of file omx.c.
Referenced by omx_init(), and omx_try_load().
ptr_Deinit
OMX_ERRORTYPE(* OMXContext::ptr_Deinit) (void)
Definition at line 80 of file omx.c.
Referenced by omx_deinit(), and omx_try_load().
ptr_ComponentNameEnum
OMX_ERRORTYPE(* OMXContext::ptr_ComponentNameEnum) (OMX_STRING, OMX_U32, OMX_U32)
Definition at line 81 of file omx.c.
Referenced by omx_try_load().
ptr_GetHandle
OMX_ERRORTYPE(* OMXContext::ptr_GetHandle) (OMX_HANDLETYPE *, OMX_STRING, OMX_PTR, OMX_CALLBACKTYPE *)
Definition at line 82 of file omx.c.
Referenced by omx_component_init(), and omx_try_load().
ptr_FreeHandle
OMX_ERRORTYPE(* OMXContext::ptr_FreeHandle) (OMX_HANDLETYPE)
Definition at line 83 of file omx.c.
Referenced by cleanup(), and omx_try_load().
ptr_GetComponentsOfRole
OMX_ERRORTYPE(* OMXContext::ptr_GetComponentsOfRole) (OMX_STRING, OMX_U32 *, OMX_U8 **)
Definition at line 84 of file omx.c.
Referenced by find_component(), and omx_try_load().
ptr_GetRolesOfComponent
OMX_ERRORTYPE(* OMXContext::ptr_GetRolesOfComponent) (OMX_STRING, OMX_U32 *, OMX_U8 **)
Definition at line 85 of file omx.c.
Referenced by omx_try_load().
host_init
void(* OMXContext::host_init) (void)
Definition at line 86 of file omx.c.
Referenced by omx_init(), and omx_try_load().
The documentation for this struct was generated from the following file:
libavcodec/omx.c