FFmpeg: DCADSPContext Struct Reference
DCADSPContext Struct Reference
#include <libavcodec/dcadsp.h>
Data Fields
void(* decode_hf)(int32_t **dst, const int32_t *vq_index, const int8_t hf_vq[1024][32], int32_t scale_factors[32][2], ptrdiff_t sb_start, ptrdiff_t sb_end, ptrdiff_t ofs, ptrdiff_t len)
void(* decode_joint)(int32_t **dst, int32_t **src, const int32_t *scale_factors, ptrdiff_t sb_start, ptrdiff_t sb_end, ptrdiff_t ofs, ptrdiff_t len)
void(* lfe_fir_float [2])(float *pcm_samples, int32_t *lfe_samples, const float *filter_coeff, ptrdiff_t npcmblocks)
void(* lfe_x96_float)(float *dst, const float *src, float *hist, ptrdiff_t len)
void(* sub_qmf_float [2])(SynthFilterContext *synth, FFTContext *imdct, float *pcm_samples, int32_t **subband_samples_lo, int32_t **subband_samples_hi, float *hist1, int *offset, float *hist2, const float *filter_coeff, ptrdiff_t npcmblocks, float scale)
void(* lfe_fir_fixed)(int32_t *pcm_samples, int32_t *lfe_samples, const int32_t *filter_coeff, ptrdiff_t npcmblocks)
void(* lfe_x96_fixed)(int32_t *dst, const int32_t *src, int32_t *hist, ptrdiff_t len)
void(* sub_qmf_fixed [2])(SynthFilterContext *synth, DCADCTContext *imdct, int32_t *pcm_samples, int32_t **subband_samples_lo, int32_t **subband_samples_hi, int32_t *hist1, int *offset, int32_t *hist2, const int32_t *filter_coeff, ptrdiff_t npcmblocks)
void(* decor)(int32_t *dst, const int32_t *src, int coeff, ptrdiff_t len)
void(* dmix_sub_xch)(int32_t *dst1, int32_t *dst2, const int32_t *src, ptrdiff_t len)
void(* dmix_sub)(int32_t *dst, const int32_t *src, int coeff, ptrdiff_t len)
void(* dmix_add)(int32_t *dst, const int32_t *src, int coeff, ptrdiff_t len)
void(* dmix_scale)(int32_t *dst, int scale, ptrdiff_t len)
void(* dmix_scale_inv)(int32_t *dst, int scale_inv, ptrdiff_t len)
void(* assemble_freq_bands)(int32_t *dst, int32_t *src0, int32_t *src1, const int32_t *coeff, ptrdiff_t len)
void(* lbr_bank)(float output[32][4], float **input, const float *coeff, ptrdiff_t ofs, ptrdiff_t len)
void(* lfe_iir)(float *output, const float *input, const float iir[5][4], float hist[5][2], ptrdiff_t factor)
Detailed Description
Definition at line 30 of file dcadsp.h.
Field Documentation
decode_hf
void(* DCADSPContext::decode_hf) (int32_t **dst, const int32_t *vq_index, const int8_t hf_vq[1024][32], int32_t scale_factors[32][2], ptrdiff_t sb_start, ptrdiff_t sb_end, ptrdiff_t ofs, ptrdiff_t len)
Definition at line 31 of file dcadsp.h.
Referenced by ff_dcadsp_init(), and parse_subframe_audio().
decode_joint
void(* DCADSPContext::decode_joint) (int32_t **dst, int32_t **src, const int32_t *scale_factors, ptrdiff_t sb_start, ptrdiff_t sb_end, ptrdiff_t ofs, ptrdiff_t len)
Definition at line 38 of file dcadsp.h.
Referenced by ff_dcadsp_init(), parse_subframe_audio(), and parse_x96_subframe_audio().
lfe_fir_float
void(* DCADSPContext::lfe_fir_float[2])(float *pcm_samples, int32_t *lfe_samples, const float *filter_coeff, ptrdiff_t npcmblocks)
Definition at line 43 of file dcadsp.h.
Referenced by ff_dcadsp_init(), and filter_frame_float().
lfe_x96_float
void(* DCADSPContext::lfe_x96_float) (float *dst, const float *src, float *hist, ptrdiff_t len)
Definition at line 46 of file dcadsp.h.
Referenced by ff_dcadsp_init(), and filter_frame_float().
sub_qmf_float
void(* DCADSPContext::sub_qmf_float[2])(SynthFilterContext *synth, FFTContext *imdct, float *pcm_samples, int32_t **subband_samples_lo, int32_t **subband_samples_hi, float *hist1, int *offset, float *hist2, const float *filter_coeff, ptrdiff_t npcmblocks, float scale)
Definition at line 49 of file dcadsp.h.
Referenced by ff_dcadsp_init(), and filter_frame_float().
lfe_fir_fixed
void(* DCADSPContext::lfe_fir_fixed) (int32_t *pcm_samples, int32_t *lfe_samples, const int32_t *filter_coeff, ptrdiff_t npcmblocks)
Definition at line 58 of file dcadsp.h.
Referenced by ff_dca_core_filter_fixed(), and ff_dcadsp_init().
lfe_x96_fixed
void(* DCADSPContext::lfe_x96_fixed) (int32_t *dst, const int32_t *src, int32_t *hist, ptrdiff_t len)
Definition at line 61 of file dcadsp.h.
Referenced by ff_dca_core_filter_fixed(), and ff_dcadsp_init().
sub_qmf_fixed
void(* DCADSPContext::sub_qmf_fixed[2])(SynthFilterContext *synth, DCADCTContext *imdct, int32_t *pcm_samples, int32_t **subband_samples_lo, int32_t **subband_samples_hi, int32_t *hist1, int *offset, int32_t *hist2, const int32_t *filter_coeff, ptrdiff_t npcmblocks)
Definition at line 64 of file dcadsp.h.
Referenced by ff_dca_core_filter_fixed(), and ff_dcadsp_init().
decor
void(* DCADSPContext::decor) (int32_t *dst, const int32_t *src, int coeff, ptrdiff_t len)
Definition at line 72 of file dcadsp.h.
Referenced by chs_filter_band_data(), and ff_dcadsp_init().
dmix_sub_xch
void(* DCADSPContext::dmix_sub_xch) (int32_t *dst1, int32_t *dst2, const int32_t *src, ptrdiff_t len)
Definition at line 74 of file dcadsp.h.
Referenced by ff_dcadsp_init(), and filter_frame_fixed().
dmix_sub
void(* DCADSPContext::dmix_sub) (int32_t *dst, const int32_t *src, int coeff, ptrdiff_t len)
Definition at line 77 of file dcadsp.h.
Referenced by ff_dcadsp_init(), filter_frame_fixed(), and undo_down_mix().
dmix_add
void(* DCADSPContext::dmix_add) (int32_t *dst, const int32_t *src, int coeff, ptrdiff_t len)
Definition at line 79 of file dcadsp.h.
Referenced by ff_dca_downmix_to_stereo_fixed(), and ff_dcadsp_init().
dmix_scale
void(* DCADSPContext::dmix_scale) (int32_t *dst, int scale, ptrdiff_t len)
Definition at line 81 of file dcadsp.h.
Referenced by ff_dca_downmix_to_stereo_fixed(), ff_dcadsp_init(), and scale_down_mix().
dmix_scale_inv
void(* DCADSPContext::dmix_scale_inv) (int32_t *dst, int scale_inv, ptrdiff_t len)
Definition at line 83 of file dcadsp.h.
Referenced by ff_dcadsp_init(), and filter_frame_fixed().
assemble_freq_bands
void(* DCADSPContext::assemble_freq_bands) (int32_t *dst, int32_t *src0, int32_t *src1, const int32_t *coeff, ptrdiff_t len)
Definition at line 85 of file dcadsp.h.
Referenced by chs_assemble_freq_bands(), and ff_dcadsp_init().
lbr_bank
void(* DCADSPContext::lbr_bank) (float output[32][4], float **input, const float *coeff, ptrdiff_t ofs, ptrdiff_t len)
Definition at line 88 of file dcadsp.h.
Referenced by ff_dcadsp_init(), and transform_channel().
lfe_iir
void(* DCADSPContext::lfe_iir) (float *output, const float *input, const float iir[5][4], float hist[5][2], ptrdiff_t factor)
Definition at line 91 of file dcadsp.h.
Referenced by ff_dca_lbr_filter_frame(), and ff_dcadsp_init().
The documentation for this struct was generated from the following file:
libavcodec/dcadsp.h