FFmpeg: AVHMAC Struct Reference
AVHMAC Struct Reference
Data Fields
void * hash
int blocklen
int hashlen
void(* final)(void *, uint8_t *)
void(* update)(void *, const uint8_t *, int len)
void(* init)(void *)
uint8_t key [MAX_BLOCKLEN]
int keylen
Detailed Description
Definition at line 33 of file hmac.c.
Field Documentation
hash
void* AVHMAC::hash
Definition at line 34 of file hmac.c.
Referenced by av_hmac_alloc(), av_hmac_final(), av_hmac_free(), av_hmac_init(), and av_hmac_update().
blocklen
int AVHMAC::blocklen
Definition at line 35 of file hmac.c.
Referenced by av_hmac_alloc(), av_hmac_final(), and av_hmac_init().
hashlen
int AVHMAC::hashlen
Definition at line 35 of file hmac.c.
Referenced by av_hmac_alloc(), av_hmac_final(), av_hmac_init(), and main().
final
void(* AVHMAC::final) (void *, uint8_t *)
Definition at line 36 of file hmac.c.
Referenced by av_hmac_alloc(), av_hmac_final(), and av_hmac_init().
update
void(* AVHMAC::update) (void *, const uint8_t *, int len)
Definition at line 37 of file hmac.c.
Referenced by av_hmac_alloc(), av_hmac_final(), av_hmac_init(), and av_hmac_update().
init
void(* AVHMAC::init) (void *)
Definition at line 38 of file hmac.c.
Referenced by av_hmac_alloc(), av_hmac_final(), and av_hmac_init().
key
uint8_t AVHMAC::key[MAX_BLOCKLEN]
Definition at line 39 of file hmac.c.
Referenced by av_hmac_final(), and av_hmac_init().
keylen
int AVHMAC::keylen
Definition at line 40 of file hmac.c.
Referenced by av_hmac_final(), and av_hmac_init().
The documentation for this struct was generated from the following file:
libavutil/hmac.c