FFmpeg: MpegvideoEncDSPContext Struct Reference
MpegvideoEncDSPContext Struct Reference
#include <libavcodec/mpegvideoencdsp.h>
Data Fields
int(* try_8x8basis)(int16_t rem[64], int16_t weight[64], int16_t basis[64], int scale)
void(* add_8x8basis)(int16_t rem[64], int16_t basis[64], int scale)
int(* pix_sum)(uint8_t *pix, int line_size)
int(* pix_norm1)(uint8_t *pix, int line_size)
void(* shrink [4])(uint8_t *dst, int dst_wrap, const uint8_t *src, int src_wrap, int width, int height)
void(* draw_edges)(uint8_t *buf, int wrap, int width, int height, int w, int h, int sides)
Detailed Description
Definition at line 32 of file mpegvideoencdsp.h.
Field Documentation
try_8x8basis
int(* MpegvideoEncDSPContext::try_8x8basis) (int16_t rem[64], int16_t weight[64], int16_t basis[64], int scale)
Definition at line 33 of file mpegvideoencdsp.h.
Referenced by dct_quantize_refine(), ff_mpegvideoencdsp_init(), and ff_mpegvideoencdsp_init_x86().
add_8x8basis
void(* MpegvideoEncDSPContext::add_8x8basis) (int16_t rem[64], int16_t basis[64], int scale)
Definition at line 35 of file mpegvideoencdsp.h.
Referenced by dct_quantize_refine(), ff_mpegvideoencdsp_init(), and ff_mpegvideoencdsp_init_x86().
pix_sum
int(* MpegvideoEncDSPContext::pix_sum) (uint8_t *pix, int line_size)
Definition at line 37 of file mpegvideoencdsp.h.
Referenced by dnxhd_mb_var_thread(), ff_estimate_p_frame_motion(), ff_mpegvideoencdsp_init(), ff_mpegvideoencdsp_init_arm(), ff_mpegvideoencdsp_init_ppc(), ff_mpegvideoencdsp_init_x86(), get_intra_count(), and mb_var_thread().
pix_norm1
int(* MpegvideoEncDSPContext::pix_norm1) (uint8_t *pix, int line_size)
Definition at line 38 of file mpegvideoencdsp.h.
Referenced by dnxhd_mb_var_thread(), ff_estimate_p_frame_motion(), ff_mpegvideoencdsp_init(), ff_mpegvideoencdsp_init_arm(), ff_mpegvideoencdsp_init_ppc(), ff_mpegvideoencdsp_init_x86(), and mb_var_thread().
shrink
void(* MpegvideoEncDSPContext::shrink[4])(uint8_t *dst, int dst_wrap, const uint8_t *src, int src_wrap, int width, int height)
Definition at line 40 of file mpegvideoencdsp.h.
Referenced by estimate_best_b_count(), and ff_mpegvideoencdsp_init().
draw_edges
void(* MpegvideoEncDSPContext::draw_edges) (uint8_t *buf, int wrap, int width, int height, int w, int h, int sides)
Definition at line 43 of file mpegvideoencdsp.h.
Referenced by encode_frame(), ff_mpegvideoencdsp_init(), ff_mpegvideoencdsp_init_x86(), frame_end(), interpolate_refplane(), and load_input_picture().
The documentation for this struct was generated from the following file:
libavcodec/mpegvideoencdsp.h