FFmpeg: PixblockDSPContext Struct Reference
PixblockDSPContext Struct Reference
#include <libavcodec/pixblockdsp.h>
Data Fields
void(* get_pixels)(int16_t *block, const uint8_t *pixels, ptrdiff_t line_size)
void(* diff_pixels)(int16_t *block, const uint8_t *s1, const uint8_t *s2, int stride)
Detailed Description
Definition at line 26 of file pixblockdsp.h.
Field Documentation
get_pixels
void(* PixblockDSPContext::get_pixels) (int16_t *block, const uint8_t *pixels, ptrdiff_t line_size)
Definition at line 27 of file pixblockdsp.h.
Referenced by checkasm_check_pixblockdsp(), dct_get(), dnxhd_get_blocks(), dvvideo_encode_init(), encode_mb_internal(), ff_pixblockdsp_init(), ff_pixblockdsp_init_alpha(), ff_pixblockdsp_init_arm(), ff_pixblockdsp_init_ppc(), and ff_pixblockdsp_init_x86().
diff_pixels
void(* PixblockDSPContext::diff_pixels) (int16_t *block, const uint8_t *s1, const uint8_t *s2, int stride)
Definition at line 30 of file pixblockdsp.h.
Referenced by bit8x8_c(), checkasm_check_pixblockdsp(), dct_max8x8_c(), dct_sad8x8_c(), encode_mb_internal(), ff_pixblockdsp_init(), ff_pixblockdsp_init_alpha(), ff_pixblockdsp_init_arm(), ff_pixblockdsp_init_ppc(), ff_pixblockdsp_init_x86(), quant_psnr8x8_c(), and rd8x8_c().
The documentation for this struct was generated from the following file:
libavcodec/pixblockdsp.h