FFmpeg: DCADCTContext Struct Reference
DCADCTContext Struct Reference
#include <libavcodec/dcadct.h>
Data Fields
void(* imdct_half [2])(int32_t *output, const int32_t *input)
Detailed Description
Definition at line 26 of file dcadct.h.
Field Documentation
imdct_half
void(* DCADCTContext::imdct_half[2])(int32_t *output, const int32_t *input)
Definition at line 27 of file dcadct.h.
Referenced by ff_dcadct_init(), synth_filter_fixed(), and synth_filter_fixed_64().
The documentation for this struct was generated from the following file:
libavcodec/dcadct.h