FFmpeg: PSNRDSPContext Struct Reference
PSNRDSPContext Struct Reference
#include <libavfilter/psnr.h>
Data Fields
uint64_t(* sse_line)(const uint8_t *buf, const uint8_t *ref, int w)
Detailed Description
Definition at line 27 of file psnr.h.
Field Documentation
sse_line
uint64_t(* PSNRDSPContext::sse_line) (const uint8_t *buf, const uint8_t *ref, int w)
Definition at line 28 of file psnr.h.
Referenced by compute_images_mse(), config_input_ref(), and ff_psnr_init_x86().
The documentation for this struct was generated from the following file:
libavfilter/psnr.h