FFmpeg: FFTContext Struct Reference
FFTContext Struct Reference
#include <libavcodec/fft.h>
Data Fields
int nbits
int inverse
uint16_t * revtab
FFTComplex * tmp_buf
int mdct_size
int mdct_bits
FFTSample * tcos
FFTSample * tsin
void(* fft_permute)(struct FFTContext *s, FFTComplex *z)
Do the permutation needed BEFORE calling fft_calc().
void(* fft_calc)(struct FFTContext *s, FFTComplex *z)
Do a complex FFT with the parameters defined in ff_fft_init().
void(* imdct_calc)(struct FFTContext *s, FFTSample *output, const FFTSample *input)
void(* imdct_half)(struct FFTContext *s, FFTSample *output, const FFTSample *input)
void(* mdct_calc)(struct FFTContext *s, FFTSample *output, const FFTSample *input)
void(* mdct_calcw)(struct FFTContext *s, FFTDouble *output, const FFTSample *input)
enum fft_permutation_type fft_permutation
enum mdct_permutation_type mdct_permutation
uint32_t * revtab32
Detailed Description
Definition at line 88 of file fft.h.
Field Documentation
nbits
int FFTContext::nbits
Definition at line 89 of file fft.h.
Referenced by ff_fft_end(), ff_fft_fixed_init_arm(), ff_fft_init(), ff_fft_init_x86(), fft_calc_c(), fft_perm_avx(), and fft_permute_c().
inverse
int FFTContext::inverse
Definition at line 90 of file fft.h.
Referenced by ff_fft_fixed_init_arm(), ff_fft_init(), and fft_perm_avx().
revtab
uint16_t* FFTContext::revtab
Definition at line 91 of file fft.h.
Referenced by ff_fft_end(), ff_fft_init(), ff_imdct_half_c(), ff_mdct_calc_c(), ff_mdct_calcw_c(), fft_perm_avx(), and fft_permute_c().
tmp_buf
FFTComplex* FFTContext::tmp_buf
Definition at line 92 of file fft.h.
Referenced by ff_fft_end(), ff_fft_init(), ff_mdct_calcw_c(), and fft_permute_c().
mdct_size
int FFTContext::mdct_size
Definition at line 93 of file fft.h.
Referenced by ff_mdct_init().
mdct_bits
int FFTContext::mdct_bits
Definition at line 94 of file fft.h.
Referenced by ff_fft_init_ppc(), ff_imdct_calc_c(), ff_imdct_half_c(), ff_mdct_calc_c(), ff_mdct_calcw_c(), and ff_mdct_init().
tcos
FFTSample* FFTContext::tcos
Definition at line 96 of file fft.h.
Referenced by ff_imdct_half_c(), ff_mdct_calc_c(), ff_mdct_calcw_c(), ff_mdct_end(), and ff_mdct_init().
tsin
FFTSample* FFTContext::tsin
Definition at line 97 of file fft.h.
Referenced by ff_imdct_half_c(), ff_mdct_calc_c(), ff_mdct_calcw_c(), and ff_mdct_init().
fft_permute
void(* FFTContext::fft_permute) (struct FFTContext *s, FFTComplex *z)
Do the permutation needed BEFORE calling fft_calc().
Definition at line 101 of file fft.h.
Referenced by av_fft_permute(), ff_fft_init(), ff_fft_init_aarch64(), ff_fft_init_arm(), ff_fft_init_x86(), fft_permute(), imc_imdct256(), rdft_calc_c(), wtf_end_1024(), and wtf_end_512().
fft_calc
void(* FFTContext::fft_calc) (struct FFTContext *s, FFTComplex *z)
Do a complex FFT with the parameters defined in ff_fft_init().
The input data must be permuted before. No 1.0/sqrt(n) normalization is done.
Definition at line 106 of file fft.h.
Referenced by av_fft_calc(), ff_fft_fixed_init_arm(), ff_fft_init(), ff_fft_init_aarch64(), ff_fft_init_arm(), ff_fft_init_mips(), ff_fft_init_ppc(), ff_fft_init_x86(), ff_imdct_half_c(), ff_mdct_calc_c(), ff_mdct_calcw_c(), fft_calc(), imc_imdct256(), rdft_calc_c(), wtf_end_1024(), and wtf_end_512().
imdct_calc
void(* FFTContext::imdct_calc) (struct FFTContext *s, FFTSample *output, const FFTSample *input)
Definition at line 107 of file fft.h.
Referenced by av_fft_end(), ff_atrac3p_imdct(), ff_fft_init(), ff_fft_init_aarch64(), ff_fft_init_arm(), ff_fft_init_mips(), ff_fft_init_ppc(), ff_fft_init_x86(), imdct_calc(), imlt(), imlt_gain(), transform_channel(), and wma_decode_block().
imdct_half
void(* FFTContext::imdct_half) (struct FFTContext *s, FFTSample *output, const FFTSample *input)
Definition at line 108 of file fft.h.
Referenced by at1_imdct(), av_fft_end(), decode_subframe(), ff_atrac3p_ipqf(), ff_fft_init(), ff_fft_init_aarch64(), ff_fft_init_arm(), ff_fft_init_mips(), ff_fft_init_ppc(), ff_fft_init_x86(), imdct_and_window(), imdct_and_windowing(), imdct_and_windowing_eld(), imdct_and_windowing_ld(), nelly_decode_block(), on2avc_reconstruct_channel(), on2avc_reconstruct_channel_ext(), sbr_qmf_analysis(), sbr_qmf_synthesis(), synth_filter_float(), synth_filter_float_64(), and vorbis_parse_audio_packet().
mdct_calc
void(* FFTContext::mdct_calc) (struct FFTContext *s, FFTSample *output, const FFTSample *input)
Definition at line 109 of file fft.h.
Referenced by aac_encode_frame(), apply_mdct(), apply_window_and_mdct(), av_fft_end(), ff_fft_fixed_init_arm(), ff_fft_init(), ff_fft_init_aarch64(), ff_fft_init_arm(), mdct_calc(), and windowing_and_mdct_ltp().
mdct_calcw
void(* FFTContext::mdct_calcw) (struct FFTContext *s, FFTDouble *output, const FFTSample *input)
Definition at line 110 of file fft.h.
Referenced by apply_mdct(), ff_fft_fixed_init_arm(), and ff_fft_init().
fft_permutation
enum fft_permutation_type FFTContext::fft_permutation
Definition at line 111 of file fft.h.
Referenced by ff_fft_fixed_init_arm(), ff_fft_init(), and ff_fft_init_x86().
mdct_permutation
enum mdct_permutation_type FFTContext::mdct_permutation
Definition at line 112 of file fft.h.
Referenced by ff_fft_fixed_init_arm(), ff_fft_init_aarch64(), ff_fft_init_arm(), and ff_mdct_init().
revtab32
uint32_t* FFTContext::revtab32
Definition at line 113 of file fft.h.
Referenced by ff_fft_end(), ff_fft_init(), and fft_permute_c().
The documentation for this struct was generated from the following file:
libavcodec/fft.h