FFmpeg: MpegVideoDSPContext Struct Reference
MpegVideoDSPContext Struct Reference
#include <libavcodec/mpegvideodsp.h>
Data Fields
void(* gmc1)(uint8_t *dst, uint8_t *src, int srcStride, int h, int x16, int y16, int rounder)
translational global motion compensation.
void(* gmc)(uint8_t *dst, uint8_t *src, int stride, int h, int ox, int oy, int dxx, int dxy, int dyx, int dyy, int shift, int r, int width, int height)
global motion compensation.
Detailed Description
Definition at line 28 of file mpegvideodsp.h.
Field Documentation
gmc1
void(* MpegVideoDSPContext::gmc1) (uint8_t *dst, uint8_t *src, int srcStride, int h, int x16, int y16, int rounder)
translational global motion compensation.
Definition at line 32 of file mpegvideodsp.h.
Referenced by ff_mpegvideodsp_init(), ff_mpegvideodsp_init_ppc(), and gmc1_motion().
gmc
void(* MpegVideoDSPContext::gmc) (uint8_t *dst, uint8_t *src, int stride, int h, int ox, int oy, int dxx, int dxy, int dyx, int dyy, int shift, int r, int width, int height)
global motion compensation.
Definition at line 37 of file mpegvideodsp.h.
Referenced by ff_mpegvideodsp_init(), ff_mpegvideodsp_init_x86(), and gmc_motion().
The documentation for this struct was generated from the following file:
libavcodec/mpegvideodsp.h