FFmpeg: VP8DSPContext Struct Reference
VP8DSPContext Struct Reference
#include <libavcodec/vp8dsp.h>
Data Fields
void(* vp8_luma_dc_wht)(int16_t block[4][4][16], int16_t dc[16])
void(* vp8_luma_dc_wht_dc)(int16_t block[4][4][16], int16_t dc[16])
void(* vp8_idct_add)(uint8_t *dst, int16_t block[16], ptrdiff_t stride)
void(* vp8_idct_dc_add)(uint8_t *dst, int16_t block[16], ptrdiff_t stride)
void(* vp8_idct_dc_add4y)(uint8_t *dst, int16_t block[4][16], ptrdiff_t stride)
void(* vp8_idct_dc_add4uv)(uint8_t *dst, int16_t block[4][16], ptrdiff_t stride)
void(* vp8_v_loop_filter16y)(uint8_t *dst, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
void(* vp8_h_loop_filter16y)(uint8_t *dst, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
void(* vp8_v_loop_filter8uv)(uint8_t *dstU, uint8_t *dstV, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
void(* vp8_h_loop_filter8uv)(uint8_t *dstU, uint8_t *dstV, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
void(* vp8_v_loop_filter16y_inner)(uint8_t *dst, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
void(* vp8_h_loop_filter16y_inner)(uint8_t *dst, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
void(* vp8_v_loop_filter8uv_inner)(uint8_t *dstU, uint8_t *dstV, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
void(* vp8_h_loop_filter8uv_inner)(uint8_t *dstU, uint8_t *dstV, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
void(* vp8_v_loop_filter_simple)(uint8_t *dst, ptrdiff_t stride, int flim)
void(* vp8_h_loop_filter_simple)(uint8_t *dst, ptrdiff_t stride, int flim)
vp8_mc_func put_vp8_epel_pixels_tab [3][3][3]
first dimension: 4-log2(width) second dimension: 0 if no vertical interpolation is needed; 1 4-tap vertical interpolation filter (my & 1) 2 6-tap vertical interpolation filter (!(my & 1)) third dimension: same as second dimension, for horizontal interpolation so something like put_vp8_epel_pixels_tab[4-log2(width)][2*!!my-(my&1)]2*!!mx-(mx&1)
vp8_mc_func put_vp8_bilinear_pixels_tab [3][3][3]
Detailed Description
Definition at line 37 of file vp8dsp.h.
Field Documentation
vp8_luma_dc_wht
void(* VP8DSPContext::vp8_luma_dc_wht) (int16_t block[4][4][16], int16_t dc[16])
Definition at line 38 of file vp8dsp.h.
Referenced by check_luma_dc_wht(), decode_mb_coeffs(), ff_vp78dsp_init(), ff_vp8dsp_init_armv6(), ff_vp8dsp_init_neon(), and ff_vp8dsp_init_x86().
vp8_luma_dc_wht_dc
void(* VP8DSPContext::vp8_luma_dc_wht_dc) (int16_t block[4][4][16], int16_t dc[16])
Definition at line 39 of file vp8dsp.h.
Referenced by check_luma_dc_wht(), decode_mb_coeffs(), ff_vp78dsp_init(), and ff_vp8dsp_init_armv6().
vp8_idct_add
void(* VP8DSPContext::vp8_idct_add) (uint8_t *dst, int16_t block[16], ptrdiff_t stride)
Definition at line 40 of file vp8dsp.h.
Referenced by check_idct(), ff_vp78dsp_init(), ff_vp8dsp_init_armv6(), ff_vp8dsp_init_neon(), ff_vp8dsp_init_x86(), idct_mb(), and intra_predict().
vp8_idct_dc_add
void(* VP8DSPContext::vp8_idct_dc_add) (uint8_t *dst, int16_t block[16], ptrdiff_t stride)
Definition at line 41 of file vp8dsp.h.
Referenced by check_idct(), ff_vp78dsp_init(), ff_vp8dsp_init_armv6(), ff_vp8dsp_init_neon(), ff_vp8dsp_init_x86(), idct_mb(), and intra_predict().
vp8_idct_dc_add4y
void(* VP8DSPContext::vp8_idct_dc_add4y) (uint8_t *dst, int16_t block[4][16], ptrdiff_t stride)
Definition at line 42 of file vp8dsp.h.
Referenced by check_idct_dc4(), ff_vp78dsp_init(), ff_vp8dsp_init_armv6(), ff_vp8dsp_init_neon(), ff_vp8dsp_init_x86(), and idct_mb().
vp8_idct_dc_add4uv
void(* VP8DSPContext::vp8_idct_dc_add4uv) (uint8_t *dst, int16_t block[4][16], ptrdiff_t stride)
Definition at line 44 of file vp8dsp.h.
Referenced by check_idct_dc4(), ff_vp78dsp_init(), ff_vp8dsp_init_armv6(), ff_vp8dsp_init_neon(), ff_vp8dsp_init_x86(), and idct_mb().
vp8_v_loop_filter16y
void(* VP8DSPContext::vp8_v_loop_filter16y) (uint8_t *dst, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
Definition at line 48 of file vp8dsp.h.
Referenced by check_loopfilter_16y(), ff_vp78dsp_init(), ff_vp8dsp_init_armv6(), ff_vp8dsp_init_neon(), ff_vp8dsp_init_x86(), and filter_mb().
vp8_h_loop_filter16y
void(* VP8DSPContext::vp8_h_loop_filter16y) (uint8_t *dst, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
Definition at line 50 of file vp8dsp.h.
Referenced by check_loopfilter_16y(), ff_vp78dsp_init(), ff_vp8dsp_init_armv6(), ff_vp8dsp_init_neon(), ff_vp8dsp_init_x86(), and filter_mb().
vp8_v_loop_filter8uv
void(* VP8DSPContext::vp8_v_loop_filter8uv) (uint8_t *dstU, uint8_t *dstV, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
Definition at line 52 of file vp8dsp.h.
Referenced by check_loopfilter_8uv(), ff_vp78dsp_init(), ff_vp8dsp_init_armv6(), ff_vp8dsp_init_neon(), ff_vp8dsp_init_x86(), and filter_mb().
vp8_h_loop_filter8uv
void(* VP8DSPContext::vp8_h_loop_filter8uv) (uint8_t *dstU, uint8_t *dstV, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
Definition at line 54 of file vp8dsp.h.
Referenced by check_loopfilter_8uv(), ff_vp78dsp_init(), ff_vp8dsp_init_armv6(), ff_vp8dsp_init_neon(), ff_vp8dsp_init_x86(), and filter_mb().
vp8_v_loop_filter16y_inner
void(* VP8DSPContext::vp8_v_loop_filter16y_inner) (uint8_t *dst, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
Definition at line 58 of file vp8dsp.h.
Referenced by check_loopfilter_16y(), ff_vp78dsp_init(), ff_vp8dsp_init_armv6(), ff_vp8dsp_init_neon(), ff_vp8dsp_init_x86(), and filter_mb().
vp8_h_loop_filter16y_inner
void(* VP8DSPContext::vp8_h_loop_filter16y_inner) (uint8_t *dst, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
Definition at line 60 of file vp8dsp.h.
Referenced by check_loopfilter_16y(), ff_vp78dsp_init(), ff_vp8dsp_init_armv6(), ff_vp8dsp_init_neon(), and ff_vp8dsp_init_x86().
vp8_v_loop_filter8uv_inner
void(* VP8DSPContext::vp8_v_loop_filter8uv_inner) (uint8_t *dstU, uint8_t *dstV, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
Definition at line 62 of file vp8dsp.h.
Referenced by check_loopfilter_8uv(), ff_vp78dsp_init(), ff_vp8dsp_init_armv6(), ff_vp8dsp_init_neon(), ff_vp8dsp_init_x86(), and filter_mb().
vp8_h_loop_filter8uv_inner
void(* VP8DSPContext::vp8_h_loop_filter8uv_inner) (uint8_t *dstU, uint8_t *dstV, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
Definition at line 65 of file vp8dsp.h.
Referenced by check_loopfilter_8uv(), ff_vp78dsp_init(), ff_vp8dsp_init_armv6(), ff_vp8dsp_init_neon(), and ff_vp8dsp_init_x86().
vp8_v_loop_filter_simple
void(* VP8DSPContext::vp8_v_loop_filter_simple) (uint8_t *dst, ptrdiff_t stride, int flim)
Definition at line 69 of file vp8dsp.h.
Referenced by check_loopfilter_simple(), ff_vp78dsp_init(), ff_vp8dsp_init_armv6(), ff_vp8dsp_init_neon(), ff_vp8dsp_init_x86(), and filter_mb_simple().
vp8_h_loop_filter_simple
void(* VP8DSPContext::vp8_h_loop_filter_simple) (uint8_t *dst, ptrdiff_t stride, int flim)
Definition at line 70 of file vp8dsp.h.
Referenced by check_loopfilter_simple(), ff_vp78dsp_init(), ff_vp8dsp_init_armv6(), ff_vp8dsp_init_neon(), ff_vp8dsp_init_x86(), and filter_mb_simple().
put_vp8_epel_pixels_tab
vp8_mc_func VP8DSPContext::put_vp8_epel_pixels_tab[3][3][3]
first dimension: 4-log2(width) second dimension: 0 if no vertical interpolation is needed; 1 4-tap vertical interpolation filter (my & 1) 2 6-tap vertical interpolation filter (!(my & 1)) third dimension: same as second dimension, for horizontal interpolation so something like put_vp8_epel_pixels_tab[4-log2(width)][2*!!my-(my&1)]2*!!mx-(mx&1)
Definition at line 80 of file vp8dsp.h.
Referenced by check_mc(), ff_vp78dsp_init_armv6(), ff_vp78dsp_init_neon(), ff_vp78dsp_init_ppc(), ff_vp78dsp_init_x86(), vp7_decode_frame_header(), and vp8_decode_frame_header().
put_vp8_bilinear_pixels_tab
vp8_mc_func VP8DSPContext::put_vp8_bilinear_pixels_tab[3][3][3]
Definition at line 81 of file vp8dsp.h.
Referenced by check_mc(), ff_vp78dsp_init_armv6(), ff_vp78dsp_init_neon(), ff_vp78dsp_init_x86(), and vp8_decode_frame_header().
The documentation for this struct was generated from the following file:
libavcodec/vp8dsp.h