FFmpeg: FLACDSPContext Struct Reference
FLACDSPContext Struct Reference
#include <libavcodec/flacdsp.h>
Data Fields
void(* decorrelate [4])(uint8_t **out, int32_t **in, int channels, int len, int shift)
void(* lpc16)(int32_t *samples, const int coeffs[32], int order, int qlevel, int len)
void(* lpc32)(int32_t *samples, const int coeffs[32], int order, int qlevel, int len)
void(* lpc16_encode)(int32_t *res, const int32_t *smp, int len, int order, const int32_t coefs[32], int shift)
void(* lpc32_encode)(int32_t *res, const int32_t *smp, int len, int order, const int32_t coefs[32], int shift)
Detailed Description
Definition at line 25 of file flacdsp.h.
Field Documentation
decorrelate
void(* FLACDSPContext::decorrelate[4])(uint8_t **out, int32_t **in, int channels, int len, int shift)
Definition at line 26 of file flacdsp.h.
Referenced by checkasm_check_flacdsp(), ff_flacdsp_init(), ff_flacdsp_init_x86(), and flac_decode_frame().
lpc16
void(* FLACDSPContext::lpc16) (int32_t *samples, const int coeffs[32], int order, int qlevel, int len)
Definition at line 28 of file flacdsp.h.
Referenced by decode_subframe_lpc(), ff_flacdsp_init(), and ff_flacdsp_init_arm().
lpc32
void(* FLACDSPContext::lpc32) (int32_t *samples, const int coeffs[32], int order, int qlevel, int len)
Definition at line 30 of file flacdsp.h.
Referenced by decode_subframe_lpc(), ff_flacdsp_init(), and ff_flacdsp_init_x86().
lpc16_encode
void(* FLACDSPContext::lpc16_encode) (int32_t *res, const int32_t *smp, int len, int order, const int32_t coefs[32], int shift)
Definition at line 32 of file flacdsp.h.
Referenced by encode_residual_ch(), ff_flacdsp_init(), and ff_flacdsp_init_x86().
lpc32_encode
void(* FLACDSPContext::lpc32_encode) (int32_t *res, const int32_t *smp, int len, int order, const int32_t coefs[32], int shift)
Definition at line 34 of file flacdsp.h.
Referenced by encode_residual_ch(), and ff_flacdsp_init().
The documentation for this struct was generated from the following file:
libavcodec/flacdsp.h