FFmpeg: AACSBRContext Struct Reference
AACSBRContext Struct Reference
aacsbr functions pointers
#include <libavcodec/sbr.h>
Data Fields
int(* sbr_lf_gen)(AACContext *ac, SpectralBandReplication *sbr, INTFLOAT X_low[32][40][2], const INTFLOAT W[2][32][32][2], int buf_idx)
void(* sbr_hf_assemble)(INTFLOAT Y1[38][64][2], const INTFLOAT X_high[64][40][2], SpectralBandReplication *sbr, SBRData *ch_data, const int e_a[2])
int(* sbr_x_gen)(SpectralBandReplication *sbr, INTFLOAT X[2][38][64], const INTFLOAT Y0[38][64][2], const INTFLOAT Y1[38][64][2], const INTFLOAT X_low[32][40][2], int ch)
void(* sbr_hf_inverse_filter)(SBRDSPContext *dsp, INTFLOAT(*alpha0)[2], INTFLOAT(*alpha1)[2], const INTFLOAT X_low[32][40][2], int k0)
Detailed Description
aacsbr functions pointers
Definition at line 120 of file sbr.h.
Field Documentation
sbr_lf_gen
int(* AACSBRContext::sbr_lf_gen) (AACContext *ac, SpectralBandReplication *sbr, INTFLOAT X_low[32][40][2], const INTFLOAT W[2][32][32][2], int buf_idx)
Definition at line 121 of file sbr.h.
Referenced by aacsbr_func_ptr_init(), and ff_aacsbr_func_ptr_init_mips().
sbr_hf_assemble
void(* AACSBRContext::sbr_hf_assemble) (INTFLOAT Y1[38][64][2], const INTFLOAT X_high[64][40][2], SpectralBandReplication *sbr, SBRData *ch_data, const int e_a[2])
Definition at line 124 of file sbr.h.
Referenced by aacsbr_func_ptr_init(), and ff_aacsbr_func_ptr_init_mips().
sbr_x_gen
int(* AACSBRContext::sbr_x_gen) (SpectralBandReplication *sbr, INTFLOAT X[2][38][64], const INTFLOAT Y0[38][64][2], const INTFLOAT Y1[38][64][2], const INTFLOAT X_low[32][40][2], int ch)
Definition at line 128 of file sbr.h.
Referenced by aacsbr_func_ptr_init(), and ff_aacsbr_func_ptr_init_mips().
sbr_hf_inverse_filter
void(* AACSBRContext::sbr_hf_inverse_filter) (SBRDSPContext *dsp, INTFLOAT(*alpha0)[2], INTFLOAT(*alpha1)[2], const INTFLOAT X_low[32][40][2], int k0)
Definition at line 131 of file sbr.h.
Referenced by aacsbr_func_ptr_init(), and ff_aacsbr_func_ptr_init_mips().
The documentation for this struct was generated from the following file:
libavcodec/sbr.h