FFmpeg: VorbisDSPContext Struct Reference
VorbisDSPContext Struct Reference
#include <libavcodec/vorbisdsp.h>
Data Fields
void(* vorbis_inverse_coupling)(float *mag, float *ang, intptr_t blocksize)
Detailed Description
Definition at line 24 of file vorbisdsp.h.
Field Documentation
vorbis_inverse_coupling
void(* VorbisDSPContext::vorbis_inverse_coupling) (float *mag, float *ang, intptr_t blocksize)
Definition at line 26 of file vorbisdsp.h.
Referenced by ff_vorbisdsp_init(), ff_vorbisdsp_init_aarch64(), ff_vorbisdsp_init_arm(), ff_vorbisdsp_init_ppc(), ff_vorbisdsp_init_x86(), and vorbis_parse_audio_packet().
The documentation for this struct was generated from the following file:
libavcodec/vorbisdsp.h