FFmpeg: V210EncContext Struct Reference
V210EncContext Struct Reference
#include <libavcodec/v210enc.h>
Data Fields
void(* pack_line_8)(const uint8_t *y, const uint8_t *u, const uint8_t *v, uint8_t *dst, ptrdiff_t width)
void(* pack_line_10)(const uint16_t *y, const uint16_t *u, const uint16_t *v, uint8_t *dst, ptrdiff_t width)
int sample_factor_8
int sample_factor_10
Detailed Description
Definition at line 26 of file v210enc.h.
Field Documentation
pack_line_8
void(* V210EncContext::pack_line_8) (const uint8_t *y, const uint8_t *u, const uint8_t *v, uint8_t *dst, ptrdiff_t width)
Definition at line 27 of file v210enc.h.
Referenced by checkasm_check_v210enc(), encode_frame(), ff_v210enc_init(), and ff_v210enc_init_x86().
pack_line_10
void(* V210EncContext::pack_line_10) (const uint16_t *y, const uint16_t *u, const uint16_t *v, uint8_t *dst, ptrdiff_t width)
Definition at line 29 of file v210enc.h.
Referenced by checkasm_check_v210enc(), encode_frame(), ff_v210enc_init(), and ff_v210enc_init_x86().
sample_factor_8
int V210EncContext::sample_factor_8
Definition at line 31 of file v210enc.h.
Referenced by encode_frame(), ff_v210enc_init(), and ff_v210enc_init_x86().
sample_factor_10
int V210EncContext::sample_factor_10
Definition at line 32 of file v210enc.h.
Referenced by encode_frame(), ff_v210enc_init(), and ff_v210enc_init_x86().
The documentation for this struct was generated from the following file:
libavcodec/v210enc.h