FFmpeg: CELPMContext Struct Reference
CELPMContext Struct Reference
#include <libavcodec/celp_math.h>
Data Fields
float(* dot_productf)(const float *a, const float *b, int length)
Return the dot product.
Detailed Description
Definition at line 28 of file celp_math.h.
Field Documentation
dot_productf
float(* CELPMContext::dot_productf) (const float *a, const float *b, int length)
Return the dot product.
Parameters
a input data array
b input data array
length number of elements
Returns
dot product = sum of elementwise products
Definition at line 37 of file celp_math.h.
Referenced by amrnb_decode_frame(), amrwb_decode_frame(), ff_celp_math_init(), ff_celp_math_init_mips(), find_hb_gain(), postfilter(), scaled_hb_excitation(), synthesis(), tilt_factor(), upsample_5_4(), and voice_factor().
The documentation for this struct was generated from the following file:
libavcodec/celp_math.h