FFmpeg: CELPFContext Struct Reference
CELPFContext Struct Reference
#include <libavcodec/celp_filters.h>
Data Fields
void(* celp_lp_synthesis_filterf)(float *out, const float *filter_coeffs, const float *in, int buffer_length, int filter_length)
LP synthesis filter.
void(* celp_lp_zero_synthesis_filterf)(float *out, const float *filter_coeffs, const float *in, int buffer_length, int filter_length)
LP zero synthesis filter.
Detailed Description
Definition at line 28 of file celp_filters.h.
Field Documentation
celp_lp_synthesis_filterf
void(* CELPFContext::celp_lp_synthesis_filterf) (float *out, const float *filter_coeffs, const float *in, int buffer_length, int filter_length)
LP synthesis filter.
Parameters
[out] out pointer to output buffer
the array out[-filter_length, -1] must contain the previous result of this filter
filter_coeffs filter coefficients.
in input signal
buffer_length amount of data to process
filter_length filter length (10 for 10th order LP filter). Must be greater than 4 and even.
Note
Output buffer must contain filter_length samples of past speech data before pointer.
Routine applies 1/A(z) filter to given speech data.
Definition at line 45 of file celp_filters.h.
Referenced by ff_celp_filter_init(), ff_celp_filter_init_mips(), hb_synthesis(), postfilter(), synthesis(), and tilt_factor().
celp_lp_zero_synthesis_filterf
void(* CELPFContext::celp_lp_zero_synthesis_filterf) (float *out, const float *filter_coeffs, const float *in, int buffer_length, int filter_length)
LP zero synthesis filter.
Parameters
[out] out pointer to output buffer
filter_coeffs filter coefficients.
in input signal
the array in[-filter_length, -1] must contain the previous input of this filter
buffer_length amount of data to process (should be a multiple of eight)
filter_length filter length (10 for 10th order LP filter; should be a multiple of two)
Note
Output buffer must contain filter_length samples of past speech data before pointer.
Routine applies A(z) filter to given speech data.
Definition at line 65 of file celp_filters.h.
Referenced by ff_celp_filter_init(), ff_celp_filter_init_mips(), and postfilter().
The documentation for this struct was generated from the following file:
libavcodec/celp_filters.h