FFmpeg: VP3DSPContext Struct Reference
VP3DSPContext Struct Reference
#include <libavcodec/vp3dsp.h>
Data Fields
void(* put_no_rnd_pixels_l2)(uint8_t *dst, const uint8_t *a, const uint8_t *b, ptrdiff_t stride, int h)
Copy 8xH pixels from source to destination buffer using a bilinear filter with no rounding (i.e.
void(* idct_put)(uint8_t *dest, int line_size, int16_t *block)
void(* idct_add)(uint8_t *dest, int line_size, int16_t *block)
void(* idct_dc_add)(uint8_t *dest, int line_size, int16_t *block)
void(* v_loop_filter)(uint8_t *src, int stride, int *bounding_values)
void(* h_loop_filter)(uint8_t *src, int stride, int *bounding_values)
Detailed Description
Definition at line 25 of file vp3dsp.h.
Field Documentation
put_no_rnd_pixels_l2
void(* VP3DSPContext::put_no_rnd_pixels_l2) (uint8_t *dst, const uint8_t *a, const uint8_t *b, ptrdiff_t stride, int h)
Copy 8xH pixels from source to destination buffer using a bilinear filter with no rounding (i.e.
*dst = (*a + *b) >> 1).
Parameters
dst destination buffer, aligned by 8
a first source buffer, no alignment
b second source buffer, no alignment
stride distance between two lines in source/dest buffers
h height
Definition at line 36 of file vp3dsp.h.
Referenced by ff_vp3dsp_init(), ff_vp3dsp_init_x86(), and render_slice().
idct_put
void(* VP3DSPContext::idct_put) (uint8_t *dest, int line_size, int16_t *block)
Definition at line 41 of file vp3dsp.h.
Referenced by ff_vp3dsp_init(), ff_vp3dsp_init_arm(), ff_vp3dsp_init_ppc(), ff_vp3dsp_init_x86(), and render_slice().
idct_add
void(* VP3DSPContext::idct_add) (uint8_t *dest, int line_size, int16_t *block)
Definition at line 42 of file vp3dsp.h.
Referenced by ff_vp3dsp_init(), ff_vp3dsp_init_arm(), ff_vp3dsp_init_ppc(), ff_vp3dsp_init_x86(), and render_slice().
idct_dc_add
void(* VP3DSPContext::idct_dc_add) (uint8_t *dest, int line_size, int16_t *block)
Definition at line 43 of file vp3dsp.h.
Referenced by ff_vp3dsp_init(), ff_vp3dsp_init_arm(), ff_vp3dsp_init_x86(), and render_slice().
v_loop_filter
void(* VP3DSPContext::v_loop_filter) (uint8_t *src, int stride, int *bounding_values)
Definition at line 44 of file vp3dsp.h.
Referenced by apply_loop_filter(), ff_vp3dsp_init(), ff_vp3dsp_init_arm(), and ff_vp3dsp_init_x86().
h_loop_filter
void(* VP3DSPContext::h_loop_filter) (uint8_t *src, int stride, int *bounding_values)
Definition at line 45 of file vp3dsp.h.
Referenced by apply_loop_filter(), ff_vp3dsp_init(), ff_vp3dsp_init_arm(), and ff_vp3dsp_init_x86().
The documentation for this struct was generated from the following file:
libavcodec/vp3dsp.h