FFmpeg: LLAudDSPContext Struct Reference
LLAudDSPContext Struct Reference
#include <libavcodec/lossless_audiodsp.h>
Data Fields
int32_t(* scalarproduct_and_madd_int16)(int16_t *v1, const int16_t *v2, const int16_t *v3, int len, int mul)
Calculate scalar product of v1 and v2, and v1[i] += v3[i] * mul.
int32_t(* scalarproduct_and_madd_int32)(int16_t *v1, const int32_t *v2, const int16_t *v3, int len, int mul)
Detailed Description
Definition at line 28 of file lossless_audiodsp.h.
Field Documentation
scalarproduct_and_madd_int16
int32_t(* LLAudDSPContext::scalarproduct_and_madd_int16) (int16_t *v1, const int16_t *v2, const int16_t *v3, int len, int mul)
Calculate scalar product of v1 and v2, and v1[i] += v3[i] * mul.
Parameters
len length of vectors, should be multiple of 16, or padd v3 and v1 or v2 with zeros.
Definition at line 35 of file lossless_audiodsp.h.
Referenced by do_apply_filter(), ff_llauddsp_init(), ff_llauddsp_init_arm(), ff_llauddsp_init_ppc(), and ff_llauddsp_init_x86().
scalarproduct_and_madd_int32
int32_t(* LLAudDSPContext::scalarproduct_and_madd_int32) (int16_t *v1, const int32_t *v2, const int16_t *v3, int len, int mul)
Definition at line 40 of file lossless_audiodsp.h.
Referenced by ff_llauddsp_init(), and ff_llauddsp_init_x86().
The documentation for this struct was generated from the following file:
libavcodec/lossless_audiodsp.h