FFmpeg: VP56DSPContext Struct Reference
VP56DSPContext Struct Reference
#include <libavcodec/vp56dsp.h>
Data Fields
void(* edge_filter_hor)(uint8_t *yuv, int stride, int t)
void(* edge_filter_ver)(uint8_t *yuv, int stride, int t)
void(* vp6_filter_diag4)(uint8_t *dst, uint8_t *src, int stride, const int16_t *h_weights, const int16_t *v_weights)
Detailed Description
Definition at line 27 of file vp56dsp.h.
Field Documentation
edge_filter_hor
void(* VP56DSPContext::edge_filter_hor) (uint8_t *yuv, int stride, int t)
Definition at line 28 of file vp56dsp.h.
Referenced by ff_vp6dsp_init_arm().
edge_filter_ver
void(* VP56DSPContext::edge_filter_ver) (uint8_t *yuv, int stride, int t)
Definition at line 29 of file vp56dsp.h.
Referenced by ff_vp6dsp_init_arm().
vp6_filter_diag4
void(* VP56DSPContext::vp6_filter_diag4) (uint8_t *dst, uint8_t *src, int stride, const int16_t *h_weights, const int16_t *v_weights)
Definition at line 31 of file vp56dsp.h.
Referenced by ff_vp6dsp_init_x86().
The documentation for this struct was generated from the following file:
libavcodec/vp56dsp.h