FFmpeg: HEVCDSPContext Struct Reference
HEVCDSPContext Struct Reference
#include <libavcodec/hevcdsp.h>
Data Fields
void(* put_pcm)(uint8_t *_dst, ptrdiff_t _stride, int width, int height, struct GetBitContext *gb, int pcm_bit_depth)
void(* transform_add [4])(uint8_t *_dst, int16_t *coeffs, ptrdiff_t _stride)
void(* transform_skip)(int16_t *coeffs, int16_t log2_size)
void(* transform_rdpcm)(int16_t *coeffs, int16_t log2_size, int mode)
void(* idct_4x4_luma)(int16_t *coeffs)
void(* idct [4])(int16_t *coeffs, int col_limit)
void(* idct_dc [4])(int16_t *coeffs)
void(* sao_band_filter [5])(uint8_t *_dst, uint8_t *_src, ptrdiff_t _stride_dst, ptrdiff_t _stride_src, int16_t *sao_offset_val, int sao_left_class, int width, int height)
void(* sao_edge_filter [5])(uint8_t *_dst, uint8_t *_src, ptrdiff_t stride_dst, int16_t *sao_offset_val, int sao_eo_class, int width, int height)
void(* sao_edge_restore [2])(uint8_t *_dst, uint8_t *_src, ptrdiff_t _stride_dst, ptrdiff_t _stride_src, struct SAOParams *sao, int *borders, int _width, int _height, int c_idx, uint8_t *vert_edge, uint8_t *horiz_edge, uint8_t *diag_edge)
void(* put_hevc_qpel [10][2][2])(int16_t *dst, uint8_t *src, ptrdiff_t srcstride, int height, intptr_t mx, intptr_t my, int width)
void(* put_hevc_qpel_uni [10][2][2])(uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int height, intptr_t mx, intptr_t my, int width)
void(* put_hevc_qpel_uni_w [10][2][2])(uint8_t *_dst, ptrdiff_t _dststride, uint8_t *_src, ptrdiff_t _srcstride, int height, int denom, int wx, int ox, intptr_t mx, intptr_t my, int width)
void(* put_hevc_qpel_bi [10][2][2])(uint8_t *dst, ptrdiff_t dststride, uint8_t *_src, ptrdiff_t _srcstride, int16_t *src2, int height, intptr_t mx, intptr_t my, int width)
void(* put_hevc_qpel_bi_w [10][2][2])(uint8_t *dst, ptrdiff_t dststride, uint8_t *_src, ptrdiff_t _srcstride, int16_t *src2, int height, int denom, int wx0, int wx1, int ox0, int ox1, intptr_t mx, intptr_t my, int width)
void(* put_hevc_epel [10][2][2])(int16_t *dst, uint8_t *src, ptrdiff_t srcstride, int height, intptr_t mx, intptr_t my, int width)
void(* put_hevc_epel_uni [10][2][2])(uint8_t *dst, ptrdiff_t dststride, uint8_t *_src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
void(* put_hevc_epel_uni_w [10][2][2])(uint8_t *_dst, ptrdiff_t _dststride, uint8_t *_src, ptrdiff_t _srcstride, int height, int denom, int wx, int ox, intptr_t mx, intptr_t my, int width)
void(* put_hevc_epel_bi [10][2][2])(uint8_t *dst, ptrdiff_t dststride, uint8_t *_src, ptrdiff_t _srcstride, int16_t *src2, int height, intptr_t mx, intptr_t my, int width)
void(* put_hevc_epel_bi_w [10][2][2])(uint8_t *dst, ptrdiff_t dststride, uint8_t *_src, ptrdiff_t _srcstride, int16_t *src2, int height, int denom, int wx0, int ox0, int wx1, int ox1, intptr_t mx, intptr_t my, int width)
void(* hevc_h_loop_filter_luma)(uint8_t *pix, ptrdiff_t stride, int beta, int32_t *tc, uint8_t *no_p, uint8_t *no_q)
void(* hevc_v_loop_filter_luma)(uint8_t *pix, ptrdiff_t stride, int beta, int32_t *tc, uint8_t *no_p, uint8_t *no_q)
void(* hevc_h_loop_filter_chroma)(uint8_t *pix, ptrdiff_t stride, int32_t *tc, uint8_t *no_p, uint8_t *no_q)
void(* hevc_v_loop_filter_chroma)(uint8_t *pix, ptrdiff_t stride, int32_t *tc, uint8_t *no_p, uint8_t *no_q)
void(* hevc_h_loop_filter_luma_c)(uint8_t *pix, ptrdiff_t stride, int beta, int32_t *tc, uint8_t *no_p, uint8_t *no_q)
void(* hevc_v_loop_filter_luma_c)(uint8_t *pix, ptrdiff_t stride, int beta, int32_t *tc, uint8_t *no_p, uint8_t *no_q)
void(* hevc_h_loop_filter_chroma_c)(uint8_t *pix, ptrdiff_t stride, int32_t *tc, uint8_t *no_p, uint8_t *no_q)
void(* hevc_v_loop_filter_chroma_c)(uint8_t *pix, ptrdiff_t stride, int32_t *tc, uint8_t *no_p, uint8_t *no_q)
Detailed Description
Definition at line 45 of file hevcdsp.h.
Field Documentation
put_pcm
void(* HEVCDSPContext::put_pcm) (uint8_t *_dst, ptrdiff_t _stride, int width, int height, struct GetBitContext *gb, int pcm_bit_depth)
Definition at line 46 of file hevcdsp.h.
Referenced by hls_pcm_sample().
transform_add
void(* HEVCDSPContext::transform_add[4])(uint8_t *_dst, int16_t *coeffs, ptrdiff_t _stride)
Definition at line 49 of file hevcdsp.h.
Referenced by ff_hevc_dsp_init_x86(), ff_hevc_hls_residual_coding(), ff_hevcdsp_init_neon(), and hls_transform_unit().
transform_skip
void(* HEVCDSPContext::transform_skip) (int16_t *coeffs, int16_t log2_size)
Definition at line 51 of file hevcdsp.h.
Referenced by ff_hevc_hls_residual_coding().
transform_rdpcm
void(* HEVCDSPContext::transform_rdpcm) (int16_t *coeffs, int16_t log2_size, int mode)
Definition at line 53 of file hevcdsp.h.
Referenced by ff_hevc_hls_residual_coding().
idct_4x4_luma
void(* HEVCDSPContext::idct_4x4_luma) (int16_t *coeffs)
Definition at line 55 of file hevcdsp.h.
Referenced by ff_hevc_hls_residual_coding(), and ff_hevcdsp_init_neon().
idct
void(* HEVCDSPContext::idct[4])(int16_t *coeffs, int col_limit)
Definition at line 57 of file hevcdsp.h.
Referenced by ff_hevc_hls_residual_coding(), and ff_hevcdsp_init_neon().
idct_dc
void(* HEVCDSPContext::idct_dc[4])(int16_t *coeffs)
Definition at line 59 of file hevcdsp.h.
Referenced by ff_hevc_dsp_init_x86(), ff_hevc_hls_residual_coding(), and ff_hevcdsp_init_neon().
sao_band_filter
void(* HEVCDSPContext::sao_band_filter[5])(uint8_t *_dst, uint8_t *_src, ptrdiff_t _stride_dst, ptrdiff_t _stride_src, int16_t *sao_offset_val, int sao_left_class, int width, int height)
Definition at line 61 of file hevcdsp.h.
Referenced by ff_hevc_dsp_init_x86(), and sao_filter_CTB().
sao_edge_filter
void(* HEVCDSPContext::sao_edge_filter[5])(uint8_t *_dst, uint8_t *_src, ptrdiff_t stride_dst, int16_t *sao_offset_val, int sao_eo_class, int width, int height)
Definition at line 65 of file hevcdsp.h.
Referenced by ff_hevc_dsp_init_x86(), and sao_filter_CTB().
sao_edge_restore
void(* HEVCDSPContext::sao_edge_restore[2])(uint8_t *_dst, uint8_t *_src, ptrdiff_t _stride_dst, ptrdiff_t _stride_src, struct SAOParams *sao, int *borders, int _width, int _height, int c_idx, uint8_t *vert_edge, uint8_t *horiz_edge, uint8_t *diag_edge)
Definition at line 68 of file hevcdsp.h.
Referenced by sao_filter_CTB().
put_hevc_qpel
void(* HEVCDSPContext::put_hevc_qpel[10][2][2])(int16_t *dst, uint8_t *src, ptrdiff_t srcstride, int height, intptr_t mx, intptr_t my, int width)
Definition at line 72 of file hevcdsp.h.
Referenced by ff_hevc_dsp_init_x86(), ff_hevcdsp_init_neon(), and luma_mc_bi().
put_hevc_qpel_uni
void(* HEVCDSPContext::put_hevc_qpel_uni[10][2][2])(uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int height, intptr_t mx, intptr_t my, int width)
Definition at line 74 of file hevcdsp.h.
Referenced by ff_hevc_dsp_init_x86(), ff_hevcdsp_init_neon(), and luma_mc_uni().
put_hevc_qpel_uni_w
void(* HEVCDSPContext::put_hevc_qpel_uni_w[10][2][2])(uint8_t *_dst, ptrdiff_t _dststride, uint8_t *_src, ptrdiff_t _srcstride, int height, int denom, int wx, int ox, intptr_t mx, intptr_t my, int width)
Definition at line 76 of file hevcdsp.h.
Referenced by luma_mc_uni().
put_hevc_qpel_bi
void(* HEVCDSPContext::put_hevc_qpel_bi[10][2][2])(uint8_t *dst, ptrdiff_t dststride, uint8_t *_src, ptrdiff_t _srcstride, int16_t *src2, int height, intptr_t mx, intptr_t my, int width)
Definition at line 79 of file hevcdsp.h.
Referenced by ff_hevc_dsp_init_x86(), ff_hevcdsp_init_neon(), and luma_mc_bi().
put_hevc_qpel_bi_w
void(* HEVCDSPContext::put_hevc_qpel_bi_w[10][2][2])(uint8_t *dst, ptrdiff_t dststride, uint8_t *_src, ptrdiff_t _srcstride, int16_t *src2, int height, int denom, int wx0, int wx1, int ox0, int ox1, intptr_t mx, intptr_t my, int width)
Definition at line 82 of file hevcdsp.h.
Referenced by luma_mc_bi().
put_hevc_epel
void(* HEVCDSPContext::put_hevc_epel[10][2][2])(int16_t *dst, uint8_t *src, ptrdiff_t srcstride, int height, intptr_t mx, intptr_t my, int width)
Definition at line 86 of file hevcdsp.h.
Referenced by chroma_mc_bi(), and ff_hevc_dsp_init_x86().
put_hevc_epel_uni
void(* HEVCDSPContext::put_hevc_epel_uni[10][2][2])(uint8_t *dst, ptrdiff_t dststride, uint8_t *_src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
Definition at line 89 of file hevcdsp.h.
Referenced by chroma_mc_uni(), and ff_hevc_dsp_init_x86().
put_hevc_epel_uni_w
void(* HEVCDSPContext::put_hevc_epel_uni_w[10][2][2])(uint8_t *_dst, ptrdiff_t _dststride, uint8_t *_src, ptrdiff_t _srcstride, int height, int denom, int wx, int ox, intptr_t mx, intptr_t my, int width)
Definition at line 91 of file hevcdsp.h.
Referenced by chroma_mc_uni().
put_hevc_epel_bi
void(* HEVCDSPContext::put_hevc_epel_bi[10][2][2])(uint8_t *dst, ptrdiff_t dststride, uint8_t *_src, ptrdiff_t _srcstride, int16_t *src2, int height, intptr_t mx, intptr_t my, int width)
Definition at line 93 of file hevcdsp.h.
Referenced by chroma_mc_bi(), and ff_hevc_dsp_init_x86().
put_hevc_epel_bi_w
void(* HEVCDSPContext::put_hevc_epel_bi_w[10][2][2])(uint8_t *dst, ptrdiff_t dststride, uint8_t *_src, ptrdiff_t _srcstride, int16_t *src2, int height, int denom, int wx0, int ox0, int wx1, int ox1, intptr_t mx, intptr_t my, int width)
Definition at line 96 of file hevcdsp.h.
Referenced by chroma_mc_bi().
hevc_h_loop_filter_luma
void(* HEVCDSPContext::hevc_h_loop_filter_luma) (uint8_t *pix, ptrdiff_t stride, int beta, int32_t *tc, uint8_t *no_p, uint8_t *no_q)
Definition at line 101 of file hevcdsp.h.
Referenced by deblocking_filter_CTB(), ff_hevc_dsp_init_x86(), and ff_hevcdsp_init_neon().
hevc_v_loop_filter_luma
void(* HEVCDSPContext::hevc_v_loop_filter_luma) (uint8_t *pix, ptrdiff_t stride, int beta, int32_t *tc, uint8_t *no_p, uint8_t *no_q)
Definition at line 104 of file hevcdsp.h.
Referenced by deblocking_filter_CTB(), ff_hevc_dsp_init_x86(), and ff_hevcdsp_init_neon().
hevc_h_loop_filter_chroma
void(* HEVCDSPContext::hevc_h_loop_filter_chroma) (uint8_t *pix, ptrdiff_t stride, int32_t *tc, uint8_t *no_p, uint8_t *no_q)
Definition at line 107 of file hevcdsp.h.
Referenced by deblocking_filter_CTB(), ff_hevc_dsp_init_x86(), and ff_hevcdsp_init_neon().
hevc_v_loop_filter_chroma
void(* HEVCDSPContext::hevc_v_loop_filter_chroma) (uint8_t *pix, ptrdiff_t stride, int32_t *tc, uint8_t *no_p, uint8_t *no_q)
Definition at line 109 of file hevcdsp.h.
Referenced by deblocking_filter_CTB(), ff_hevc_dsp_init_x86(), and ff_hevcdsp_init_neon().
hevc_h_loop_filter_luma_c
void(* HEVCDSPContext::hevc_h_loop_filter_luma_c) (uint8_t *pix, ptrdiff_t stride, int beta, int32_t *tc, uint8_t *no_p, uint8_t *no_q)
Definition at line 111 of file hevcdsp.h.
Referenced by deblocking_filter_CTB().
hevc_v_loop_filter_luma_c
void(* HEVCDSPContext::hevc_v_loop_filter_luma_c) (uint8_t *pix, ptrdiff_t stride, int beta, int32_t *tc, uint8_t *no_p, uint8_t *no_q)
Definition at line 114 of file hevcdsp.h.
Referenced by deblocking_filter_CTB().
hevc_h_loop_filter_chroma_c
void(* HEVCDSPContext::hevc_h_loop_filter_chroma_c) (uint8_t *pix, ptrdiff_t stride, int32_t *tc, uint8_t *no_p, uint8_t *no_q)
Definition at line 117 of file hevcdsp.h.
Referenced by deblocking_filter_CTB().
hevc_v_loop_filter_chroma_c
void(* HEVCDSPContext::hevc_v_loop_filter_chroma_c) (uint8_t *pix, ptrdiff_t stride, int32_t *tc, uint8_t *no_p, uint8_t *no_q)
Definition at line 120 of file hevcdsp.h.
Referenced by deblocking_filter_CTB().
The documentation for this struct was generated from the following file:
libavcodec/hevcdsp.h