FFmpeg: CaptureContext Struct Reference
CaptureContext Struct Reference
Protected Attributes
AVClass * class
float frame_rate
int frames_captured
int64_t first_pts
pthread_mutex_t frame_lock
pthread_cond_t frame_wait_cond
id qt_delegate
int list_devices
int video_device_index
QTCaptureSession * capture_session
QTCaptureDecompressedVideoOutput * video_output
CVImageBufferRef current_frame
Detailed Description
Definition at line 49 of file qtkit.m.
Field Documentation
class
- (AVClass*) class protected
Definition at line 51 of file qtkit.m.
frame_rate
- (float) frame_rate protected
Definition at line 53 of file qtkit.m.
frames_captured
- (int) frames_captured protected
Definition at line 54 of file qtkit.m.
Referenced by FFMPEG_FrameReceiver::captureOutput:didOutputVideoFrame:withSampleBuffer:fromConnection:, and qtkit_read_header().
first_pts
- (int64_t) first_pts protected
Definition at line 55 of file qtkit.m.
Referenced by qtkit_read_header(), and qtkit_read_packet().
frame_lock
- (pthread_mutex_t) frame_lock protected
Definition at line 56 of file qtkit.m.
Referenced by destroy_context(), lock_frames(), qtkit_read_header(), qtkit_read_packet(), and unlock_frames().
frame_wait_cond
- (pthread_cond_t) frame_wait_cond protected
Definition at line 57 of file qtkit.m.
Referenced by FFMPEG_FrameReceiver::captureOutput:didOutputVideoFrame:withSampleBuffer:fromConnection:, destroy_context(), qtkit_read_header(), and qtkit_read_packet().
qt_delegate
- (id) qt_delegate protected
Definition at line 58 of file qtkit.m.
Referenced by destroy_context(), and qtkit_read_header().
list_devices
- (int) list_devices protected
Definition at line 60 of file qtkit.m.
Referenced by qtkit_read_header().
video_device_index
- (int) video_device_index protected
Definition at line 61 of file qtkit.m.
Referenced by qtkit_read_header().
capture_session
- (QTCaptureSession*) capture_session protected
Definition at line 63 of file qtkit.m.
Referenced by destroy_context(), and qtkit_read_header().
video_output
- (QTCaptureDecompressedVideoOutput*) video_output protected
Definition at line 64 of file qtkit.m.
Referenced by destroy_context(), and qtkit_read_header().
current_frame
- (CVImageBufferRef) current_frame protected
Definition at line 65 of file qtkit.m.
Referenced by FFMPEG_FrameReceiver::captureOutput:didOutputVideoFrame:withSampleBuffer:fromConnection:, destroy_context(), qtkit_read_header(), and qtkit_read_packet().
The documentation for this struct was generated from the following file:
libavdevice/qtkit.m