FFmpeg: RDFTContext Struct Reference
RDFTContext Struct Reference
#include <libavcodec/rdft.h>
Data Fields
int nbits
int inverse
int sign_convention
const FFTSample * tcos
SINTABLE_CONST FFTSample * tsin
FFTContext fft
void(* rdft_calc)(struct RDFTContext *s, FFTSample *z)
Detailed Description
Definition at line 51 of file rdft.h.
Field Documentation
nbits
int RDFTContext::nbits
Definition at line 52 of file rdft.h.
Referenced by ff_rdft_init(), and rdft_calc_c().
inverse
int RDFTContext::inverse
Definition at line 53 of file rdft.h.
Referenced by ff_rdft_init(), and rdft_calc_c().
sign_convention
int RDFTContext::sign_convention
Definition at line 54 of file rdft.h.
Referenced by ff_rdft_init(), and rdft_calc_c().
tcos
const FFTSample* RDFTContext::tcos
Definition at line 57 of file rdft.h.
Referenced by ff_rdft_init(), and rdft_calc_c().
tsin
SINTABLE_CONST FFTSample* RDFTContext::tsin
Definition at line 58 of file rdft.h.
Referenced by ff_rdft_init(), and rdft_calc_c().
fft
FFTContext RDFTContext::fft
Definition at line 59 of file rdft.h.
Referenced by ff_rdft_end(), ff_rdft_init(), and rdft_calc_c().
rdft_calc
void(* RDFTContext::rdft_calc) (struct RDFTContext *s, FFTSample *z)
Definition at line 60 of file rdft.h.
Referenced by av_fft_end(), calc_input_response(), dct_calc_I_c(), dct_calc_II_c(), dct_calc_III_c(), decode_block(), dst_calc_I_c(), ff_rdft_init(), ff_rdft_init_arm(), fft_end(), qdm2_calculate_fft(), and wiener_denoise().
The documentation for this struct was generated from the following file:
libavcodec/rdft.h