FFmpeg: ogg_codec Struct Reference
ogg_codec Struct Reference
Copyright (C) 2005 Michael Ahlberg, M책ns Rullg책rd.
#include <libavformat/oggdec.h>
Data Fields
const int8_t * magic
uint8_t magicsize
const int8_t * name
int(* header)(AVFormatContext *, int)
Attempt to process a packet as a header.
int(* packet)(AVFormatContext *, int)
uint64_t(* gptopts)(AVFormatContext *, int, uint64_t, int64_t *dts)
Translate a granule into a timestamp.
int granule_is_start
1 if granule is the start time of the associated packet.
int nb_header
Number of expected headers.
void(* cleanup)(AVFormatContext *s, int idx)
Detailed Description
Copyright (C) 2005 Michael Ahlberg, M책ns Rullg책rd.
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 31 of file oggdec.h.
Field Documentation
magic
const int8_t* ogg_codec::magic
Definition at line 32 of file oggdec.h.
Referenced by celt_header(), ogg_find_codec(), and ogg_replace_stream().
magicsize
uint8_t ogg_codec::magicsize
Definition at line 33 of file oggdec.h.
Referenced by celt_header(), daala_header(), and ogg_find_codec().
name
const int8_t* ogg_codec::name
Definition at line 34 of file oggdec.h.
header
int(* ogg_codec::header) (AVFormatContext *, int)
Attempt to process a packet as a header.
Returns
1 if the packet was a valid header, 0 if the packet was not a header (was a data packet) -1 if an error occurred or for unsupported stream
Definition at line 41 of file oggdec.h.
Referenced by ogg_packet().
packet
int(* ogg_codec::packet) (AVFormatContext *, int)
Definition at line 42 of file oggdec.h.
Referenced by ogg_packet().
gptopts
uint64_t(* ogg_codec::gptopts) (AVFormatContext *, int, uint64_t, int64_t *dts)
Translate a granule into a timestamp.
Will set dts if non-null and known.
Returns
pts
Definition at line 48 of file oggdec.h.
Referenced by ogg_gptopts().
granule_is_start
int ogg_codec::granule_is_start
1 if granule is the start time of the associated packet.
0 if granule is the end time of the associated packet.
Definition at line 53 of file oggdec.h.
Referenced by ogg_calc_pts().
nb_header
int ogg_codec::nb_header
Number of expected headers.
Definition at line 57 of file oggdec.h.
Referenced by ogg_read_header().
cleanup
void(* ogg_codec::cleanup) (AVFormatContext *s, int idx)
Definition at line 58 of file oggdec.h.
Referenced by ogg_read_close().
The documentation for this struct was generated from the following file:
libavformat/oggdec.h