FFmpeg: H264PredContext Struct Reference
H264PredContext Struct Reference
Context for storing H.264 prediction functions.
#include <libavcodec/h264pred.h>
Data Fields
void(* pred4x4 [9+3+3])(uint8_t *src, const uint8_t *topright, ptrdiff_t stride)
void(* pred8x8l [9+3])(uint8_t *src, int topleft, int topright, ptrdiff_t stride)
void(* pred8x8 [4+3+4])(uint8_t *src, ptrdiff_t stride)
void(* pred16x16 [4+3+2])(uint8_t *src, ptrdiff_t stride)
void(* pred4x4_add [2])(uint8_t *pix, int16_t *block, ptrdiff_t stride)
void(* pred8x8l_add [2])(uint8_t *pix, int16_t *block, ptrdiff_t stride)
void(* pred8x8l_filter_add [2])(uint8_t *pix, int16_t *block, int topleft, int topright, ptrdiff_t stride)
void(* pred8x8_add [3])(uint8_t *pix, const int *block_offset, int16_t *block, ptrdiff_t stride)
void(* pred16x16_add [3])(uint8_t *pix, const int *block_offset, int16_t *block, ptrdiff_t stride)
Detailed Description
Context for storing H.264 prediction functions.
Definition at line 92 of file h264pred.h.
Field Documentation
pred4x4
void(* H264PredContext::pred4x4[9 + 3 + 3])(uint8_t *src, const uint8_t *topright, ptrdiff_t stride)
Definition at line 93 of file h264pred.h.
Referenced by check_pred4x4(), hl_decode_mb_predict_luma(), intra_predict(), and rv34_pred_4x4_block().
pred8x8l
void(* H264PredContext::pred8x8l[9 + 3])(uint8_t *src, int topleft, int topright, ptrdiff_t stride)
Definition at line 95 of file h264pred.h.
Referenced by check_pred8x8l(), and hl_decode_mb_predict_luma().
pred8x8
void(* H264PredContext::pred8x8[4 + 3 + 4])(uint8_t *src, ptrdiff_t stride)
Definition at line 97 of file h264pred.h.
Referenced by check_pred8x8(), h264_pred_init_neon(), hl_decode_mb(), intra_predict(), and rv34_output_i16x16().
pred16x16
void(* H264PredContext::pred16x16[4 + 3 + 2])(uint8_t *src, ptrdiff_t stride)
Definition at line 98 of file h264pred.h.
Referenced by check_pred16x16(), h264_pred_init_neon(), hl_decode_mb_predict_luma(), intra_predict(), and rv34_output_i16x16().
pred4x4_add
void(* H264PredContext::pred4x4_add[2])(uint8_t *pix, int16_t *block, ptrdiff_t stride)
Definition at line 100 of file h264pred.h.
Referenced by hl_decode_mb_predict_luma().
pred8x8l_add
void(* H264PredContext::pred8x8l_add[2])(uint8_t *pix, int16_t *block, ptrdiff_t stride)
Definition at line 102 of file h264pred.h.
Referenced by hl_decode_mb_predict_luma().
pred8x8l_filter_add
void(* H264PredContext::pred8x8l_filter_add[2])(uint8_t *pix, int16_t *block, int topleft, int topright, ptrdiff_t stride)
Definition at line 104 of file h264pred.h.
Referenced by hl_decode_mb_predict_luma().
pred8x8_add
void(* H264PredContext::pred8x8_add[3])(uint8_t *pix, const int *block_offset, int16_t *block, ptrdiff_t stride)
Definition at line 106 of file h264pred.h.
pred16x16_add
void(* H264PredContext::pred16x16_add[3])(uint8_t *pix, const int *block_offset, int16_t *block, ptrdiff_t stride)
Definition at line 109 of file h264pred.h.
Referenced by hl_decode_mb_idct_luma().
The documentation for this struct was generated from the following file:
libavcodec/h264pred.h