FFmpeg: VLC Struct Reference
VLC Struct Reference
#include <libavcodec/vlc.h>
Data Fields
int bits
VLC_TYPE(* table)[2]
code, bits
int table_size
int table_allocated
Detailed Description
Definition at line 26 of file vlc.h.
Field Documentation
bits
int VLC::bits
Definition at line 27 of file vlc.h.
Referenced by alloc_table(), dca_get_vlc(), decode_argb(), decode_argbi(), decode_argx(), decode_argxi(), decode_aybr(), decode_aybri(), decode_byry(), decode_byryi(), decode_c82i(), decode_c82p(), decode_ca2i(), decode_ca2p(), decode_ca4i(), decode_ca4p(), decode_channel(), decode_channel_sf_idx(), decode_channel_wordlen(), decode_envelope(), decode_frame(), decode_gainc_loc_codes(), decode_plane(), decode_plane10(), decode_qu_spectra(), decode_rgb(), decode_rgbi(), decode_rgbx(), decode_rgbxi(), decode_ybr(), decode_ybr10(), decode_ybr10i(), decode_ybri(), decode_ybyr(), decode_yry10(), decode_yry10i(), decouple_info(), ff_init_vlc_sparse(), gainc_loc_mode1(), get_coeff(), hqx_decode_422a(), hqx_decode_444a(), huffman_decode(), imc_read_level_coeffs(), magy_decode_slice(), magy_decode_slice10(), parse_vlc(), qdm2_get_vlc(), rv34_decode_cbp(), rv40_decode_init(), unpack_SQVH(), and vlc_decode_block().
table
VLC_TYPE(* VLC::table)[2]
code, bits
Definition at line 28 of file vlc.h.
Referenced by alloc_table(), asv1_decode_block(), asv1_get_level(), asv2_decode_block(), asv2_get_level(), atrac3_init_static_data(), bitplane_decoding(), build_canonical_huff(), build_table(), dca_get_vlc(), decode_argb(), decode_argbi(), decode_argx(), decode_argxi(), decode_aybr(), decode_aybri(), decode_bgr_1(), decode_block(), decode_block_progressive(), decode_block_refinement(), decode_byry(), decode_byryi(), decode_c82i(), decode_c82p(), decode_ca2i(), decode_ca2p(), decode_ca4i(), decode_ca4p(), decode_cce(), decode_channel(), decode_channel_sf_idx(), decode_channel_wordlen(), decode_coeff(), decode_coeffs(), decode_dc(), decode_envelope(), decode_exp_vlc(), decode_frame(), decode_gainc_loc_codes(), decode_group3_2d_line(), decode_i_block(), decode_i_frame(), decode_init(), decode_init_static(), decode_mb_info(), decode_mv_component(), decode_p_block(), decode_plane(), decode_plane10(), decode_plane_bitstream(), decode_qu_spectra(), decode_residual(), decode_rgb(), decode_rgbi(), decode_rgbx(), decode_rgbxi(), decode_rle(), decode_scale_factors(), decode_scalefactors(), decode_spectrum_and_dequant(), decode_ybr(), decode_ybr10(), decode_ybr10i(), decode_ybri(), decode_ybyr(), decode_yry10(), decode_yry10i(), decouple_info(), dnxhd_decode_dct_block(), ff_atrac3p_init_vlcs(), ff_ccitt_unpack_init(), ff_cfhd_init_vlcs(), ff_dvvideo_init(), ff_free_vlc(), ff_h263_decode_mb(), ff_h263_decode_motion(), ff_h264_decode_init_vlc(), ff_init_vlc_sparse(), ff_ivi_dec_huff_desc(), ff_ivi_decode_close(), ff_ivi_init_static_vlc(), ff_mjpeg_decode_sos(), ff_msmpeg4_decode_motion(), ff_rl_init_vlc(), ff_rv_decode_dc(), ff_vc1_init_common(), ff_vc1_parse_frame_header_adv(), ff_wma_run_level_decode(), ff_wmv2_decode_mb(), fraps2_decode_plane(), gainc_loc_mode1(), get_coeff(), get_mvdata_interlaced(), get_scale_idx(), h261_decode_mb(), hq_decode_block(), hqa_decode_mb(), hqx_decode_422a(), hqx_decode_444a(), huff_reader_get_symbol(), huffman_decode(), imc_decode_init(), imc_read_level_coeffs(), init_2d_vlc_rl(), init_vlcs(), ir2_decode_init(), ir2_get_code(), ivi_decode_coded_blocks(), jpg_decode_block(), magy_decode_slice(), magy_decode_slice10(), mjpeg_decode_dc(), mp_get_vlc(), mpc7_decode_frame(), mpc7_decode_init(), mpc8_decode_frame(), mpc8_decode_init(), mpeg4_decode_dc(), mpeg4_decode_mb(), mpeg4_decode_partition_a(), mpeg4_decode_partition_b(), mpeg4_decode_sprite_trajectory(), mpeg_decode_mb(), mpeg_decode_motion(), mpeg_decode_slice(), msmpeg4_decode_dc(), msmpeg4v12_decode_mb(), msmpeg4v2_decode_motion(), msmpeg4v34_decode_mb(), mss4_decode_dct(), on2avc_decode_band_scales(), on2avc_decode_pairs(), on2avc_decode_quads(), parse_ch(), parse_vlc(), preview_obmc(), qdm2_get_vlc(), qdm2_init_vlc(), read_bfraction(), read_code_table(), read_rgb24_component_line(), read_sbr_envelope(), read_sbr_noise(), read_yuv_component_line(), rv34_decode_block(), rv34_decode_cbp(), rv34_gen_vlc(), rv40_decode_intra_types(), rv40_init_tables(), setup_classifs(), smacker_decode_bigtree(), svq1_decode_block_intra(), svq1_decode_block_non_intra(), svq1_decode_delta_block(), svq1_decode_init(), svq1_decode_motion_vector(), synth_frame(), tm2_free_codes(), tm2_get_token(), tscc2_decode_mb(), unpack_block_qpis(), unpack_modes(), unpack_SQVH(), unpack_superblocks(), unpack_vectors(), unpack_vlcs(), vc1_decode_b_mb(), vc1_decode_b_mb_intfi(), vc1_decode_b_mb_intfr(), vc1_decode_i_block(), vc1_decode_i_block_adv(), vc1_decode_i_blocks(), vc1_decode_i_blocks_adv(), vc1_decode_intra_block(), vc1_decode_p_block(), vc1_decode_p_mb(), vc1_decode_p_mb_intfi(), vc1_decode_p_mb_intfr(), vlc_decode_block(), vorbis_floor0_decode(), vorbis_floor1_decode(), vorbis_residue_decode_internal(), vp6_parse_coeff_huffman(), wma_decode_block(), wnv1_get_code(), x8_get_ac_rlf(), x8_get_dc_rlf(), and x8_get_orient_vlc().
table_size
int VLC::table_size
Definition at line 29 of file vlc.h.
Referenced by alloc_table(), ff_cfhd_init_vlcs(), ff_dvvideo_init(), ff_init_vlc_sparse(), ff_rl_init_vlc(), and init_2d_vlc_rl().
table_allocated
int VLC::table_allocated
Definition at line 29 of file vlc.h.
Referenced by alloc_table(), atrac3_init_static_data(), build_canonical_huff(), decode_init(), decode_init_static(), ff_atrac3p_init_vlcs(), ff_ccitt_unpack_init(), ff_h264_decode_init_vlc(), ff_init_vlc_sparse(), ff_ivi_init_static_vlc(), ff_vc1_init_common(), imc_decode_init(), init_vlcs(), ir2_decode_init(), mpc7_decode_init(), mpc8_decode_init(), qdm2_init_vlc(), rv34_gen_vlc(), rv40_init_tables(), and svq1_decode_init().
The documentation for this struct was generated from the following file:
libavcodec/vlc.h