FFmpeg: DiracDSPContext Struct Reference
DiracDSPContext Struct Reference
#include <libavcodec/diracdsp.h>
Data Fields
void(* dirac_hpel_filter)(uint8_t *dsth, uint8_t *dstv, uint8_t *dstc, const uint8_t *src, int stride, int width, int height)
void(* put_dirac_pixels_tab [3][4])(uint8_t *dst, const uint8_t *src[5], int stride, int h)
dirac_pixels_tab[width][subpel] width is 2 for 32, 1 for 16, 0 for 8 subpel is 0 for fpel and hpel (only need to copy from the first plane in src) 1 if an average of the first 2 planes is needed (TODO: worth it?) 2 for general qpel (avg of 4) 3 for general epel (biweight of 4 using the weights in src[4]) src[0-3] is each of the hpel planes src[4] is the 1/8 pel weights if needed
void(* avg_dirac_pixels_tab [3][4])(uint8_t *dst, const uint8_t *src[5], int stride, int h)
void(* put_signed_rect_clamped [3])(uint8_t *dst, int dst_stride, const uint8_t *src, int src_stride, int width, int height)
void(* put_rect_clamped)(uint8_t *dst, int dst_stride, const uint8_t *src, int src_stride, int width, int height)
void(* add_rect_clamped)(uint8_t *dst, const uint16_t *src, int stride, const int16_t *idwt, int idwt_stride, int width, int height)
void(* add_dirac_obmc [3])(uint16_t *dst, const uint8_t *src, int stride, const uint8_t *obmc_weight, int yblen)
void(* dequant_subband [4])(uint8_t *src, uint8_t *dst, ptrdiff_t stride, const int qf, const int qs, int tot_v, int tot_h)
dirac_weight_func weight_dirac_pixels_tab [3]
dirac_biweight_func biweight_dirac_pixels_tab [3]
Detailed Description
Definition at line 30 of file diracdsp.h.
Field Documentation
dirac_hpel_filter
void(* DiracDSPContext::dirac_hpel_filter) (uint8_t *dsth, uint8_t *dstv, uint8_t *dstc, const uint8_t *src, int stride, int width, int height)
Definition at line 31 of file diracdsp.h.
Referenced by ff_diracdsp_init(), and interpolate_refplane().
put_dirac_pixels_tab
void(* DiracDSPContext::put_dirac_pixels_tab[3][4])(uint8_t *dst, const uint8_t *src[5], int stride, int h)
dirac_pixels_tab[width][subpel] width is 2 for 32, 1 for 16, 0 for 8 subpel is 0 for fpel and hpel (only need to copy from the first plane in src) 1 if an average of the first 2 planes is needed (TODO: worth it?) 2 for general qpel (avg of 4) 3 for general epel (biweight of 4 using the weights in src[4]) src[0-3] is each of the hpel planes src[4] is the 1/8 pel weights if needed
Definition at line 42 of file diracdsp.h.
Referenced by select_dsp_funcs().
avg_dirac_pixels_tab
void(* DiracDSPContext::avg_dirac_pixels_tab[3][4])(uint8_t *dst, const uint8_t *src[5], int stride, int h)
Definition at line 43 of file diracdsp.h.
Referenced by select_dsp_funcs().
put_signed_rect_clamped
void(* DiracDSPContext::put_signed_rect_clamped[3])(uint8_t *dst, int dst_stride, const uint8_t *src, int src_stride, int width, int height)
Definition at line 45 of file diracdsp.h.
Referenced by dirac_decode_frame_internal(), and ff_diracdsp_init().
put_rect_clamped
void(* DiracDSPContext::put_rect_clamped) (uint8_t *dst, int dst_stride, const uint8_t *src, int src_stride, int width, int height)
Definition at line 46 of file diracdsp.h.
add_rect_clamped
void(* DiracDSPContext::add_rect_clamped) (uint8_t *dst, const uint16_t *src, int stride, const int16_t *idwt, int idwt_stride, int width, int height)
Definition at line 47 of file diracdsp.h.
Referenced by dirac_decode_frame_internal(), and ff_diracdsp_init().
add_dirac_obmc
void(* DiracDSPContext::add_dirac_obmc[3])(uint16_t *dst, const uint8_t *src, int stride, const uint8_t *obmc_weight, int yblen)
Definition at line 48 of file diracdsp.h.
Referenced by ff_diracdsp_init(), and select_dsp_funcs().
dequant_subband
void(* DiracDSPContext::dequant_subband[4])(uint8_t *src, uint8_t *dst, ptrdiff_t stride, const int qf, const int qs, int tot_v, int tot_h)
Definition at line 51 of file diracdsp.h.
Referenced by decode_hq_slice(), and ff_diracdsp_init().
weight_dirac_pixels_tab
dirac_weight_func DiracDSPContext::weight_dirac_pixels_tab[3]
Definition at line 53 of file diracdsp.h.
Referenced by ff_diracdsp_init(), and select_dsp_funcs().
biweight_dirac_pixels_tab
dirac_biweight_func DiracDSPContext::biweight_dirac_pixels_tab[3]
Definition at line 54 of file diracdsp.h.
Referenced by ff_diracdsp_init(), and select_dsp_funcs().
The documentation for this struct was generated from the following file:
libavcodec/diracdsp.h