FFmpeg: WMV2DSPContext Struct Reference
WMV2DSPContext Struct Reference
#include <libavcodec/wmv2dsp.h>
Data Fields
void(* idct_add)(uint8_t *dest, int line_size, int16_t *block)
void(* idct_put)(uint8_t *dest, int line_size, int16_t *block)
qpel_mc_func put_mspel_pixels_tab [8]
int idct_perm
Detailed Description
Definition at line 26 of file wmv2dsp.h.
Field Documentation
idct_add
void(* WMV2DSPContext::idct_add) (uint8_t *dest, int line_size, int16_t *block)
Definition at line 27 of file wmv2dsp.h.
Referenced by ff_wmv2_common_init(), ff_wmv2dsp_init(), wmv2_add_block(), and x8_decode_intra_mb().
idct_put
void(* WMV2DSPContext::idct_put) (uint8_t *dest, int line_size, int16_t *block)
Definition at line 28 of file wmv2dsp.h.
Referenced by ff_wmv2_common_init(), and ff_wmv2dsp_init().
put_mspel_pixels_tab
qpel_mc_func WMV2DSPContext::put_mspel_pixels_tab[8]
Definition at line 30 of file wmv2dsp.h.
Referenced by ff_mspel_motion(), and ff_wmv2dsp_init().
idct_perm
int WMV2DSPContext::idct_perm
Definition at line 32 of file wmv2dsp.h.
Referenced by ff_intrax8_common_init(), ff_wmv2_common_init(), and ff_wmv2dsp_init().
The documentation for this struct was generated from the following file:
libavcodec/wmv2dsp.h