FFmpeg: SBRDSPContext Struct Reference
SBRDSPContext Struct Reference
#include <libavcodec/sbrdsp.h>
Data Fields
void(* sum64x5)(INTFLOAT *z)
AAC_FLOAT(* sum_square)(INTFLOAT(*x)[2], int n)
void(* neg_odd_64)(INTFLOAT *x)
void(* qmf_pre_shuffle)(INTFLOAT *z)
void(* qmf_post_shuffle)(INTFLOAT W[32][2], const INTFLOAT *z)
void(* qmf_deint_neg)(INTFLOAT *v, const INTFLOAT *src)
void(* qmf_deint_bfly)(INTFLOAT *v, const INTFLOAT *src0, const INTFLOAT *src1)
void(* autocorrelate)(const INTFLOAT x[40][2], AAC_FLOAT phi[3][2][2])
void(* hf_gen)(INTFLOAT(*X_high)[2], const INTFLOAT(*X_low)[2], const INTFLOAT alpha0[2], const INTFLOAT alpha1[2], INTFLOAT bw, int start, int end)
void(* hf_g_filt)(INTFLOAT(*Y)[2], const INTFLOAT(*X_high)[40][2], const AAC_FLOAT *g_filt, int m_max, intptr_t ixh)
void(* hf_apply_noise [4])(INTFLOAT(*Y)[2], const AAC_FLOAT *s_m, const AAC_FLOAT *q_filt, int noise, int kx, int m_max)
Detailed Description
Definition at line 28 of file sbrdsp.h.
Field Documentation
sum64x5
void(* SBRDSPContext::sum64x5) (INTFLOAT *z)
Definition at line 29 of file sbrdsp.h.
Referenced by ff_sbrdsp_init_arm(), ff_sbrdsp_init_mips(), and ff_sbrdsp_init_x86().
sum_square
AAC_FLOAT(* SBRDSPContext::sum_square) (INTFLOAT(*x)[2], int n)
Definition at line 30 of file sbrdsp.h.
Referenced by ff_sbrdsp_init_arm(), ff_sbrdsp_init_mips(), ff_sbrdsp_init_x86(), and sbr_env_estimate().
neg_odd_64
void(* SBRDSPContext::neg_odd_64) (INTFLOAT *x)
Definition at line 31 of file sbrdsp.h.
Referenced by ff_sbrdsp_init_arm(), and ff_sbrdsp_init_x86().
qmf_pre_shuffle
void(* SBRDSPContext::qmf_pre_shuffle) (INTFLOAT *z)
Definition at line 32 of file sbrdsp.h.
Referenced by ff_sbrdsp_init_arm(), ff_sbrdsp_init_mips(), and ff_sbrdsp_init_x86().
qmf_post_shuffle
void(* SBRDSPContext::qmf_post_shuffle) (INTFLOAT W[32][2], const INTFLOAT *z)
Definition at line 33 of file sbrdsp.h.
Referenced by ff_sbrdsp_init_arm(), ff_sbrdsp_init_mips(), and ff_sbrdsp_init_x86().
qmf_deint_neg
void(* SBRDSPContext::qmf_deint_neg) (INTFLOAT *v, const INTFLOAT *src)
Definition at line 34 of file sbrdsp.h.
Referenced by ff_sbrdsp_init_arm(), and ff_sbrdsp_init_x86().
qmf_deint_bfly
void(* SBRDSPContext::qmf_deint_bfly) (INTFLOAT *v, const INTFLOAT *src0, const INTFLOAT *src1)
Definition at line 35 of file sbrdsp.h.
Referenced by ff_sbrdsp_init_arm(), ff_sbrdsp_init_mips(), and ff_sbrdsp_init_x86().
autocorrelate
void(* SBRDSPContext::autocorrelate) (const INTFLOAT x[40][2], AAC_FLOAT phi[3][2][2])
Definition at line 36 of file sbrdsp.h.
Referenced by ff_sbrdsp_init_arm(), ff_sbrdsp_init_mips(), ff_sbrdsp_init_x86(), and sbr_hf_inverse_filter().
hf_gen
void(* SBRDSPContext::hf_gen) (INTFLOAT(*X_high)[2], const INTFLOAT(*X_low)[2], const INTFLOAT alpha0[2], const INTFLOAT alpha1[2], INTFLOAT bw, int start, int end)
Definition at line 37 of file sbrdsp.h.
Referenced by ff_sbrdsp_init_arm(), ff_sbrdsp_init_mips(), ff_sbrdsp_init_x86(), and sbr_hf_gen().
hf_g_filt
void(* SBRDSPContext::hf_g_filt) (INTFLOAT(*Y)[2], const INTFLOAT(*X_high)[40][2], const AAC_FLOAT *g_filt, int m_max, intptr_t ixh)
Definition at line 40 of file sbrdsp.h.
Referenced by ff_sbrdsp_init_arm(), ff_sbrdsp_init_mips(), ff_sbrdsp_init_x86(), and sbr_hf_assemble().
hf_apply_noise
void(* SBRDSPContext::hf_apply_noise[4])(INTFLOAT(*Y)[2], const AAC_FLOAT *s_m, const AAC_FLOAT *q_filt, int noise, int kx, int m_max)
Definition at line 42 of file sbrdsp.h.
Referenced by ff_sbrdsp_init_arm(), ff_sbrdsp_init_mips(), ff_sbrdsp_init_x86(), and sbr_hf_assemble().
The documentation for this struct was generated from the following file:
libavcodec/sbrdsp.h