FFmpeg: AC3DSPContext Struct Reference
AC3DSPContext Struct Reference
#include <libavcodec/ac3dsp.h>
Data Fields
void(* ac3_exponent_min)(uint8_t *exp, int num_reuse_blocks, int nb_coefs)
Set each encoded exponent in a block to the minimum of itself and the exponents in the same frequency bin of up to 5 following blocks.
int(* ac3_max_msb_abs_int16)(const int16_t *src, int len)
Calculate the maximum MSB of the absolute value of each element in an array of int16_t.
void(* ac3_lshift_int16)(int16_t *src, unsigned int len, unsigned int shift)
Left-shift each value in an array of int16_t by a specified amount.
void(* ac3_rshift_int32)(int32_t *src, unsigned int len, unsigned int shift)
Right-shift each value in an array of int32_t by a specified amount.
void(* float_to_fixed24)(int32_t *dst, const float *src, unsigned int len)
Convert an array of float in range [-1.0,1.0] to int32_t with range [-(1<<24),(1<<24)].
void(* bit_alloc_calc_bap)(int16_t *mask, int16_t *psd, int start, int end, int snr_offset, int floor, const uint8_t *bap_tab, uint8_t *bap)
Calculate bit allocation pointers.
void(* update_bap_counts)(uint16_t mant_cnt[16], uint8_t *bap, int len)
Update bap counts using the supplied array of bap.
int(* compute_mantissa_size)(uint16_t mant_cnt[6][16])
Calculate the number of bits needed to encode a set of mantissas.
void(* extract_exponents)(uint8_t *exp, int32_t *coef, int nb_coefs)
void(* sum_square_butterfly_int32)(int64_t sum[4], const int32_t *coef0, const int32_t *coef1, int len)
void(* sum_square_butterfly_float)(float sum[4], const float *coef0, const float *coef1, int len)
void(* downmix)(float **samples, float(*matrix)[2], int out_ch, int in_ch, int len)
void(* downmix_fixed)(int32_t **samples, int16_t(*matrix)[2], int out_ch, int in_ch, int len)
void(* apply_window_int16)(int16_t *output, const int16_t *input, const int16_t *window, unsigned int len)
Apply symmetric window in 16-bit fixed-point.
Detailed Description
Definition at line 33 of file ac3dsp.h.
Field Documentation
ac3_exponent_min
void(* AC3DSPContext::ac3_exponent_min) (uint8_t *exp, int num_reuse_blocks, int nb_coefs)
Set each encoded exponent in a block to the minimum of itself and the exponents in the same frequency bin of up to 5 following blocks.
Parameters
exp pointer to the start of the current block of exponents. constraints: align 16
num_reuse_blocks number of blocks that will reuse exponents from the current block. constraints: range 0 to 5
nb_coefs number of frequency coefficients.
Definition at line 43 of file ac3dsp.h.
Referenced by encode_exponents(), ff_ac3dsp_init(), ff_ac3dsp_init_arm(), and ff_ac3dsp_init_x86().
ac3_max_msb_abs_int16
int(* AC3DSPContext::ac3_max_msb_abs_int16) (const int16_t *src, int len)
Calculate the maximum MSB of the absolute value of each element in an array of int16_t.
Parameters
src input array constraints: align 16. values must be in range [-32767,32767]
len number of values in the array constraints: multiple of 16 greater than 0
Returns
a value with the same MSB as max(abs(src[]))
Definition at line 54 of file ac3dsp.h.
Referenced by ff_ac3dsp_init(), ff_ac3dsp_init_arm(), ff_ac3dsp_init_x86(), and normalize_samples().
ac3_lshift_int16
void(* AC3DSPContext::ac3_lshift_int16) (int16_t *src, unsigned int len, unsigned int shift)
Left-shift each value in an array of int16_t by a specified amount.
Parameters
src input array constraints: align 16
len number of values in the array constraints: multiple of 32 greater than 0
shift left shift amount constraints: range [0,15]
Definition at line 65 of file ac3dsp.h.
Referenced by ff_ac3dsp_init(), ff_ac3dsp_init_arm(), ff_ac3dsp_init_x86(), and normalize_samples().
ac3_rshift_int32
void(* AC3DSPContext::ac3_rshift_int32) (int32_t *src, unsigned int len, unsigned int shift)
Right-shift each value in an array of int32_t by a specified amount.
Parameters
src input array constraints: align 16
len number of values in the array constraints: multiple of 16 greater than 0
shift right shift amount constraints: range [0,31]
Definition at line 76 of file ac3dsp.h.
Referenced by ff_ac3dsp_init(), ff_ac3dsp_init_arm(), ff_ac3dsp_init_x86(), and scale_coefficients().
float_to_fixed24
void(* AC3DSPContext::float_to_fixed24) (int32_t *dst, const float *src, unsigned int len)
Convert an array of float in range [-1.0,1.0] to int32_t with range [-(1<<24),(1<<24)].
Parameters
dst destination array of int32_t. constraints: 16-byte aligned
src source array of float. constraints: 16-byte aligned
len number of elements to convert. constraints: multiple of 32 greater than zero
Definition at line 89 of file ac3dsp.h.
Referenced by apply_channel_coupling(), ff_ac3dsp_init(), ff_ac3dsp_init_arm(), ff_ac3dsp_init_mips(), ff_ac3dsp_init_x86(), and scale_coefficients().
bit_alloc_calc_bap
void(* AC3DSPContext::bit_alloc_calc_bap) (int16_t *mask, int16_t *psd, int start, int end, int snr_offset, int floor, const uint8_t *bap_tab, uint8_t *bap)
Calculate bit allocation pointers.
The SNR is the difference between the masking curve and the signal. AC-3 uses this value for each frequency bin to allocate bits. The snroffset parameter is a global adjustment to the SNR for all bins.
Parameters
[in] mask masking curve
[in] psd signal power for each frequency bin
[in] start starting bin location
[in] end ending bin location
[in] snr_offset SNR adjustment
[in] floor noise floor
[in] bap_tab look-up table for bit allocation pointers
[out] bap bit allocation pointers
Definition at line 106 of file ac3dsp.h.
Referenced by bit_alloc(), ff_ac3dsp_init(), ff_ac3dsp_init_arm(), and ff_ac3dsp_init_mips().
update_bap_counts
void(* AC3DSPContext::update_bap_counts) (uint16_t mant_cnt[16], uint8_t *bap, int len)
Update bap counts using the supplied array of bap.
Parameters
[out] mant_cnt bap counts for 1 block
[in] bap array of bap, pointing to start coef bin
[in] len number of elements to process
Definition at line 117 of file ac3dsp.h.
Referenced by count_mantissa_bits_update_ch(), ff_ac3dsp_init(), ff_ac3dsp_init_arm(), and ff_ac3dsp_init_mips().
compute_mantissa_size
int(* AC3DSPContext::compute_mantissa_size) (uint16_t mant_cnt[6][16])
Calculate the number of bits needed to encode a set of mantissas.
Parameters
[in] mant_cnt bap counts for all blocks
Returns
mantissa bit count
Definition at line 125 of file ac3dsp.h.
Referenced by count_mantissa_bits(), ff_ac3dsp_init(), and ff_ac3dsp_init_x86().
extract_exponents
void(* AC3DSPContext::extract_exponents) (uint8_t *exp, int32_t *coef, int nb_coefs)
Definition at line 127 of file ac3dsp.h.
Referenced by apply_channel_coupling(), extract_exponents(), ff_ac3dsp_init(), ff_ac3dsp_init_arm(), and ff_ac3dsp_init_x86().
sum_square_butterfly_int32
void(* AC3DSPContext::sum_square_butterfly_int32) (int64_t sum[4], const int32_t *coef0, const int32_t *coef1, int len)
Definition at line 129 of file ac3dsp.h.
Referenced by ff_ac3dsp_init(), ff_ac3dsp_init_arm(), and sum_square_butterfly().
sum_square_butterfly_float
void(* AC3DSPContext::sum_square_butterfly_float) (float sum[4], const float *coef0, const float *coef1, int len)
Definition at line 132 of file ac3dsp.h.
Referenced by ff_ac3dsp_init(), ff_ac3dsp_init_arm(), and sum_square_butterfly().
downmix
void(* AC3DSPContext::downmix) (float **samples, float(*matrix)[2], int out_ch, int in_ch, int len)
Definition at line 135 of file ac3dsp.h.
Referenced by ff_ac3dsp_init(), ff_ac3dsp_init_mips(), and ff_ac3dsp_init_x86().
downmix_fixed
void(* AC3DSPContext::downmix_fixed) (int32_t **samples, int16_t(*matrix)[2], int out_ch, int in_ch, int len)
Definition at line 138 of file ac3dsp.h.
Referenced by ff_ac3dsp_init().
apply_window_int16
void(* AC3DSPContext::apply_window_int16) (int16_t *output, const int16_t *input, const int16_t *window, unsigned int len)
Apply symmetric window in 16-bit fixed-point.
Parameters
output destination array constraints: 16-byte aligned
input source array constraints: 16-byte aligned
window window array constraints: 16-byte aligned, at least len/2 elements
len full window length constraints: multiple of ? greater than zero
Definition at line 152 of file ac3dsp.h.
Referenced by apply_mdct(), ff_ac3dsp_init(), ff_ac3dsp_init_arm(), and ff_ac3dsp_init_x86().
The documentation for this struct was generated from the following file:
libavcodec/ac3dsp.h