FFmpeg: VideoDSPContext Struct Reference
VideoDSPContext Struct Reference
#include <libavcodec/videodsp.h>
Data Fields
void(* emulated_edge_mc)(uint8_t *dst, const uint8_t *src, ptrdiff_t dst_linesize, ptrdiff_t src_linesize, int block_w, int block_h, int src_x, int src_y, int w, int h)
Copy a rectangular area of samples to a temporary buffer and replicate the border samples.
void(* prefetch)(uint8_t *buf, ptrdiff_t stride, int h)
Prefetch memory into cache (if supported by hardware).
Detailed Description
Definition at line 41 of file videodsp.h.
Field Documentation
emulated_edge_mc
void(* VideoDSPContext::emulated_edge_mc) (uint8_t *dst, const uint8_t *src, ptrdiff_t dst_linesize, ptrdiff_t src_linesize, int block_w, int block_h, int src_x, int src_y, int w, int h)
Copy a rectangular area of samples to a temporary buffer and replicate the border samples.
Parameters
dst destination buffer
dst_stride number of bytes between 2 vertically adjacent samples in destination buffer
src source buffer
dst_linesize number of bytes between 2 vertically adjacent samples in the destination buffer
src_linesize number of bytes between 2 vertically adjacent samples in both the source buffer
block_w width of block
block_h height of block
src_x x coordinate of the top left sample of the block in the source buffer
src_y y coordinate of the top left sample of the block in the source buffer
w width of the source buffer
h height of the source buffer
Definition at line 63 of file videodsp.h.
Referenced by apply_8x8(), checkasm_check_videodsp(), chroma_4mv_motion(), chroma_4mv_motion_lowres(), chroma_mc_bi(), chroma_mc_uni(), dnxhd_get_blocks(), encode_mb_internal(), ff_mspel_motion(), ff_snow_pred_block(), ff_vc1_interp_mc(), ff_vc1_mc_1mv(), ff_vc1_mc_4mv_chroma(), ff_vc1_mc_4mv_chroma4(), ff_vc1_mc_4mv_luma(), ff_videodsp_init(), ff_videodsp_init_x86(), gmc1_motion(), hpel_motion(), hpel_motion_lowres(), luma_mc_bi(), luma_mc_uni(), mc_chroma_scaled(), mc_chroma_unscaled(), mc_dir_part(), mc_luma_scaled(), mc_luma_unscaled(), mc_subpel(), mpeg_motion_internal(), mpeg_motion_lowres(), qpel_motion(), render_slice(), rv34_mc(), svq3_mc_dir_part(), vp8_mc_chroma(), and vp8_mc_luma().
prefetch
void(* VideoDSPContext::prefetch) (uint8_t *buf, ptrdiff_t stride, int h)
Prefetch memory into cache (if supported by hardware).
Parameters
buf pointer to buffer to prefetch memory from
stride distance between two lines of buf (in bytes)
h number of lines to prefetch
Definition at line 76 of file videodsp.h.
Referenced by decode_mb_row_no_filter(), ff_videodsp_init(), ff_videodsp_init_aarch64(), ff_videodsp_init_armv5te(), ff_videodsp_init_ppc(), ff_videodsp_init_x86(), hl_decode_mb(), and prefetch_motion().
The documentation for this struct was generated from the following file:
libavcodec/videodsp.h