FFmpeg: FSPPContext Struct Reference
FSPPContext Struct Reference
#include <libavfilter/vf_fspp.h>
Data Fields
AVClass * class
uint64_t threshold_mtx_noq [8 *2]
uint64_t threshold_mtx [8 *2]
int log2_count
int strength
int hsub
int vsub
int temp_stride
int qp
int qscale_type
int prev_q
uint8_t * src
int16_t * temp
uint8_t * non_b_qp_table
int non_b_qp_alloc_size
int use_bframe_qp
void(* store_slice)(uint8_t *dst, int16_t *src, ptrdiff_t dst_stride, ptrdiff_t src_stride, ptrdiff_t width, ptrdiff_t height, ptrdiff_t log2_scale)
void(* store_slice2)(uint8_t *dst, int16_t *src, ptrdiff_t dst_stride, ptrdiff_t src_stride, ptrdiff_t width, ptrdiff_t height, ptrdiff_t log2_scale)
void(* mul_thrmat)(int16_t *thr_adr_noq, int16_t *thr_adr, int q)
void(* column_fidct)(int16_t *thr_adr, int16_t *data, int16_t *output, int cnt)
void(* row_idct)(int16_t *workspace, int16_t *output_adr, ptrdiff_t output_stride, int cnt)
void(* row_fdct)(int16_t *data, const uint8_t *pixels, ptrdiff_t line_size, int cnt)
Detailed Description
Definition at line 55 of file vf_fspp.h.
Field Documentation
class
AVClass* FSPPContext::class
Definition at line 56 of file vf_fspp.h.
threshold_mtx_noq
uint64_t FSPPContext::threshold_mtx_noq[8 *2]
Definition at line 57 of file vf_fspp.h.
Referenced by filter(), and filter_frame().
threshold_mtx
uint64_t FSPPContext::threshold_mtx[8 *2]
Definition at line 58 of file vf_fspp.h.
Referenced by filter(), and filter_frame().
log2_count
int FSPPContext::log2_count
Definition at line 60 of file vf_fspp.h.
Referenced by filter(), and filter_frame().
strength
int FSPPContext::strength
Definition at line 61 of file vf_fspp.h.
Referenced by filter_frame().
hsub
int FSPPContext::hsub
Definition at line 62 of file vf_fspp.h.
Referenced by config_input(), filter(), and filter_frame().
vsub
int FSPPContext::vsub
Definition at line 63 of file vf_fspp.h.
Referenced by config_input(), filter(), and filter_frame().
temp_stride
int FSPPContext::temp_stride
Definition at line 64 of file vf_fspp.h.
Referenced by config_input(), and filter().
qp
int FSPPContext::qp
Definition at line 65 of file vf_fspp.h.
Referenced by config_input(), filter(), and filter_frame().
qscale_type
int FSPPContext::qscale_type
Definition at line 66 of file vf_fspp.h.
Referenced by filter(), and filter_frame().
prev_q
int FSPPContext::prev_q
Definition at line 67 of file vf_fspp.h.
Referenced by filter(), and filter_frame().
src
uint8_t* FSPPContext::src
Definition at line 68 of file vf_fspp.h.
Referenced by config_input(), filter(), and uninit().
temp
int16_t* FSPPContext::temp
Definition at line 69 of file vf_fspp.h.
Referenced by config_input(), filter(), and uninit().
non_b_qp_table
uint8_t* FSPPContext::non_b_qp_table
Definition at line 70 of file vf_fspp.h.
Referenced by config_input(), filter_frame(), and uninit().
non_b_qp_alloc_size
int FSPPContext::non_b_qp_alloc_size
Definition at line 71 of file vf_fspp.h.
Referenced by config_input(), and filter_frame().
use_bframe_qp
int FSPPContext::use_bframe_qp
Definition at line 72 of file vf_fspp.h.
Referenced by config_input(), and filter_frame().
store_slice
void(* FSPPContext::store_slice) (uint8_t *dst, int16_t *src, ptrdiff_t dst_stride, ptrdiff_t src_stride, ptrdiff_t width, ptrdiff_t height, ptrdiff_t log2_scale)
Definition at line 74 of file vf_fspp.h.
Referenced by config_input(), ff_fspp_init_x86(), and filter().
store_slice2
void(* FSPPContext::store_slice2) (uint8_t *dst, int16_t *src, ptrdiff_t dst_stride, ptrdiff_t src_stride, ptrdiff_t width, ptrdiff_t height, ptrdiff_t log2_scale)
Definition at line 78 of file vf_fspp.h.
Referenced by config_input(), ff_fspp_init_x86(), and filter().
mul_thrmat
void(* FSPPContext::mul_thrmat) (int16_t *thr_adr_noq, int16_t *thr_adr, int q)
Definition at line 82 of file vf_fspp.h.
Referenced by config_input(), ff_fspp_init_x86(), filter(), and filter_frame().
column_fidct
void(* FSPPContext::column_fidct) (int16_t *thr_adr, int16_t *data, int16_t *output, int cnt)
Definition at line 84 of file vf_fspp.h.
Referenced by config_input(), ff_fspp_init_x86(), and filter().
row_idct
void(* FSPPContext::row_idct) (int16_t *workspace, int16_t *output_adr, ptrdiff_t output_stride, int cnt)
Definition at line 87 of file vf_fspp.h.
Referenced by config_input(), ff_fspp_init_x86(), and filter().
row_fdct
void(* FSPPContext::row_fdct) (int16_t *data, const uint8_t *pixels, ptrdiff_t line_size, int cnt)
Definition at line 90 of file vf_fspp.h.
Referenced by config_input(), ff_fspp_init_x86(), and filter().
The documentation for this struct was generated from the following file:
libavfilter/vf_fspp.h