FFmpeg: TextureDSPContext Struct Reference
TextureDSPContext Struct Reference
#include <libavcodec/texturedsp.h>
Data Fields
int(* dxt1_block)(uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
int(* dxt1a_block)(uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
int(* dxt2_block)(uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
int(* dxt3_block)(uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
int(* dxt4_block)(uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
int(* dxt5_block)(uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
int(* dxt5y_block)(uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
int(* dxt5ys_block)(uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
int(* rgtc1s_block)(uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
int(* rgtc1u_block)(uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
int(* rgtc2s_block)(uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
int(* rgtc2u_block)(uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
int(* dxn3dc_block)(uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Detailed Description
Definition at line 45 of file texturedsp.h.
Field Documentation
dxt1_block
int(* TextureDSPContext::dxt1_block) (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Definition at line 46 of file texturedsp.h.
Referenced by dxv_decode(), ff_texturedsp_init(), ff_texturedspenc_init(), hap_init(), and txd_decode_frame().
dxt1a_block
int(* TextureDSPContext::dxt1a_block) (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Definition at line 47 of file texturedsp.h.
Referenced by ff_texturedsp_init(), and parse_pixel_format().
dxt2_block
int(* TextureDSPContext::dxt2_block) (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Definition at line 48 of file texturedsp.h.
Referenced by ff_texturedsp_init(), and parse_pixel_format().
dxt3_block
int(* TextureDSPContext::dxt3_block) (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Definition at line 49 of file texturedsp.h.
Referenced by ff_texturedsp_init(), parse_pixel_format(), and txd_decode_frame().
dxt4_block
int(* TextureDSPContext::dxt4_block) (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Definition at line 50 of file texturedsp.h.
Referenced by ff_texturedsp_init(), and parse_pixel_format().
dxt5_block
int(* TextureDSPContext::dxt5_block) (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Definition at line 51 of file texturedsp.h.
Referenced by dxv_decode(), ff_texturedsp_init(), ff_texturedspenc_init(), hap_init(), and parse_pixel_format().
dxt5y_block
int(* TextureDSPContext::dxt5y_block) (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Definition at line 52 of file texturedsp.h.
Referenced by ff_texturedsp_init(), and parse_pixel_format().
dxt5ys_block
int(* TextureDSPContext::dxt5ys_block) (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Definition at line 53 of file texturedsp.h.
Referenced by ff_texturedsp_init(), ff_texturedspenc_init(), hap_init(), and parse_pixel_format().
rgtc1s_block
int(* TextureDSPContext::rgtc1s_block) (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Definition at line 54 of file texturedsp.h.
Referenced by ff_texturedsp_init(), and parse_pixel_format().
rgtc1u_block
int(* TextureDSPContext::rgtc1u_block) (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Definition at line 55 of file texturedsp.h.
Referenced by ff_texturedsp_init(), and parse_pixel_format().
rgtc2s_block
int(* TextureDSPContext::rgtc2s_block) (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Definition at line 56 of file texturedsp.h.
Referenced by ff_texturedsp_init(), and parse_pixel_format().
rgtc2u_block
int(* TextureDSPContext::rgtc2u_block) (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Definition at line 57 of file texturedsp.h.
Referenced by ff_texturedsp_init(), and parse_pixel_format().
dxn3dc_block
int(* TextureDSPContext::dxn3dc_block) (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Definition at line 58 of file texturedsp.h.
Referenced by ff_texturedsp_init(), and parse_pixel_format().
The documentation for this struct was generated from the following file:
libavcodec/texturedsp.h