FFmpeg: ProresDSPContext Struct Reference
ProresDSPContext Struct Reference
#include <libavcodec/proresdsp.h>
Data Fields
int idct_permutation_type
uint8_t idct_permutation [64]
void(* idct_put)(uint16_t *out, int linesize, int16_t *block, const int16_t *qmat)
Detailed Description
Definition at line 31 of file proresdsp.h.
Field Documentation
idct_permutation_type
int ProresDSPContext::idct_permutation_type
Definition at line 32 of file proresdsp.h.
Referenced by decode_init(), ff_proresdsp_init(), and ff_proresdsp_init_x86().
idct_permutation
uint8_t ProresDSPContext::idct_permutation[64]
Definition at line 33 of file proresdsp.h.
Referenced by decode_frame_header(), decode_slice(), and ff_proresdsp_init().
idct_put
void(* ProresDSPContext::idct_put) (uint16_t *out, int linesize, int16_t *block, const int16_t *qmat)
Definition at line 34 of file proresdsp.h.
Referenced by decode_slice_chroma(), decode_slice_luma(), decode_slice_plane(), ff_proresdsp_init(), and ff_proresdsp_init_x86().
The documentation for this struct was generated from the following file:
libavcodec/proresdsp.h