FFmpeg: LLSModel Struct Reference
LLSModel Struct Reference
Linear least squares model.
#include <libavutil/lls.h>
Data Fields
double covariance [(((32+1)+(4) -1)&~((4) -1))][(((32+1)+(4) -1)&~((4) -1))]
double coeff [32][32]
double variance [MAX_VARS]
int indep_count
void(* update_lls)(struct LLSModel *m, const double *var)
Take the outer-product of var[] with itself, and add to the covariance matrix.
double(* evaluate_lls)(struct LLSModel *m, const double *var, int order)
Inner product of var[] and the LPC coefs.
Detailed Description
Linear least squares model.
Definition at line 38 of file lls.h.
Field Documentation
covariance
double LLSModel::covariance[(((32+1)+(4) -1)&~((4) -1))][(((32+1)+(4) -1)&~((4) -1))]
Definition at line 39 of file lls.h.
Referenced by avpriv_solve_lls(), and update_lls().
coeff
double LLSModel::coeff[32][32]
Definition at line 40 of file lls.h.
Referenced by avpriv_solve_lls(), evaluate_lls(), ff_lpc_calc_coefs(), and main().
variance
double LLSModel::variance[MAX_VARS]
Definition at line 41 of file lls.h.
Referenced by avpriv_solve_lls(), and main().
indep_count
int LLSModel::indep_count
Definition at line 42 of file lls.h.
Referenced by avpriv_init_lls(), avpriv_solve_lls(), ff_init_lls_x86(), and update_lls().
update_lls
void(* LLSModel::update_lls) (struct LLSModel *m, const double *var)
Take the outer-product of var[] with itself, and add to the covariance matrix.
Parameters
m this context
var training samples, starting with the value to be predicted 32-byte aligned, and any padding elements must be initialized (i.e not denormal/nan).
Definition at line 50 of file lls.h.
Referenced by avpriv_init_lls(), ff_init_lls_x86(), ff_lpc_calc_coefs(), and main().
evaluate_lls
double(* LLSModel::evaluate_lls) (struct LLSModel *m, const double *var, int order)
Inner product of var[] and the LPC coefs.
Parameters
m this context
var training samples, excluding the value to be predicted. unaligned.
order lpc order
Definition at line 57 of file lls.h.
Referenced by avpriv_init_lls(), ff_init_lls_x86(), ff_lpc_calc_coefs(), and main().
The documentation for this struct was generated from the following file:
libavutil/lls.h