FFmpeg: ACELPVContext Struct Reference
ACELPVContext Struct Reference
#include <libavcodec/acelp_vectors.h>
Data Fields
void(* weighted_vector_sumf)(float *out, const float *in_a, const float *in_b, float weight_coeff_a, float weight_coeff_b, int length)
float implementation of weighted sum of two vectors.
Detailed Description
Definition at line 28 of file acelp_vectors.h.
Field Documentation
weighted_vector_sumf
void(* ACELPVContext::weighted_vector_sumf) (float *out, const float *in_a, const float *in_b, float weight_coeff_a, float weight_coeff_b, int length)
float implementation of weighted sum of two vectors.
Parameters
[out] out result of addition
in_a first vector
in_b second vector
weight_coeff_a first vector weight coefficient
weight_coeff_a second vector weight coefficient
length vectors length (should be a multiple of two)
Note
It is safe to pass the same buffer for out and in_a or in_b.
Definition at line 40 of file acelp_vectors.h.
Referenced by amrnb_decode_frame(), ff_acelp_vectors_init(), ff_acelp_vectors_init_mips(), hb_synthesis(), interpolate_lsf(), and synthesis().
The documentation for this struct was generated from the following file:
libavcodec/acelp_vectors.h