FFmpeg: BinkDSPContext Struct Reference
BinkDSPContext Struct Reference
#include <libavcodec/binkdsp.h>
Data Fields
void(* idct_put)(uint8_t *dest, int line_size, int32_t *block)
void(* idct_add)(uint8_t *dest, int line_size, int32_t *block)
void(* scale_block)(const uint8_t src[64], uint8_t *dst, int linesize)
void(* add_pixels8)(uint8_t *pixels, int16_t *block, int line_size)
Detailed Description
Definition at line 32 of file binkdsp.h.
Field Documentation
idct_put
void(* BinkDSPContext::idct_put) (uint8_t *dest, int line_size, int32_t *block)
Definition at line 33 of file binkdsp.h.
Referenced by bink_decode_plane(), binkb_decode_plane(), and ff_binkdsp_init().
idct_add
void(* BinkDSPContext::idct_add) (uint8_t *dest, int line_size, int32_t *block)
Definition at line 34 of file binkdsp.h.
Referenced by bink_decode_plane(), binkb_decode_plane(), and ff_binkdsp_init().
scale_block
void(* BinkDSPContext::scale_block) (const uint8_t src[64], uint8_t *dst, int linesize)
Definition at line 35 of file binkdsp.h.
Referenced by bink_decode_plane(), and ff_binkdsp_init().
add_pixels8
void(* BinkDSPContext::add_pixels8) (uint8_t *pixels, int16_t *block, int line_size)
Definition at line 36 of file binkdsp.h.
Referenced by bink_decode_plane(), binkb_decode_plane(), and ff_binkdsp_init().
The documentation for this struct was generated from the following file:
libavcodec/binkdsp.h