FFmpeg: HWContextType Struct Reference
HWContextType Struct Reference
#include <libavutil/hwcontext_internal.h>
Data Fields
enum AVHWDeviceType type
const char * name
enum AVPixelFormat * pix_fmts
An array of pixel formats supported by the AVHWFramesContext instances Terminated by AV_PIX_FMT_NONE.
size_t device_hwctx_size
size of the public hardware-specific context, i.e.
size_t device_priv_size
size of the private data, i.e.
size_t device_hwconfig_size
Size of the hardware-specific device configuration.
size_t frames_hwctx_size
size of the public frame pool hardware-specific context, i.e.
size_t frames_priv_size
size of the private data, i.e.
int(* device_create)(AVHWDeviceContext *ctx, const char *device, AVDictionary *opts, int flags)
int(* device_init)(AVHWDeviceContext *ctx)
void(* device_uninit)(AVHWDeviceContext *ctx)
int(* frames_get_constraints)(AVHWDeviceContext *ctx, const void *hwconfig, AVHWFramesConstraints *constraints)
int(* frames_init)(AVHWFramesContext *ctx)
void(* frames_uninit)(AVHWFramesContext *ctx)
int(* frames_get_buffer)(AVHWFramesContext *ctx, AVFrame *frame)
int(* transfer_get_formats)(AVHWFramesContext *ctx, enum AVHWFrameTransferDirection dir, enum AVPixelFormat **formats)
int(* transfer_data_to)(AVHWFramesContext *ctx, AVFrame *dst, const AVFrame *src)
int(* transfer_data_from)(AVHWFramesContext *ctx, AVFrame *dst, const AVFrame *src)
Detailed Description
Definition at line 29 of file hwcontext_internal.h.
Field Documentation
type
enum AVHWDeviceType HWContextType::type
Definition at line 30 of file hwcontext_internal.h.
name
const char* HWContextType::name
Definition at line 31 of file hwcontext_internal.h.
Referenced by av_hwframe_ctx_init().
pix_fmts
enum AVPixelFormat* HWContextType::pix_fmts
An array of pixel formats supported by the AVHWFramesContext instances Terminated by AV_PIX_FMT_NONE.
Definition at line 37 of file hwcontext_internal.h.
Referenced by av_hwframe_ctx_init().
device_hwctx_size
size_t HWContextType::device_hwctx_size
size of the public hardware-specific context, i.e.
AVHWDeviceContext.hwctx
Definition at line 43 of file hwcontext_internal.h.
Referenced by av_hwdevice_ctx_alloc().
device_priv_size
size_t HWContextType::device_priv_size
size of the private data, i.e.
AVHWDeviceInternal.priv
Definition at line 48 of file hwcontext_internal.h.
Referenced by av_hwdevice_ctx_alloc().
device_hwconfig_size
size_t HWContextType::device_hwconfig_size
Size of the hardware-specific device configuration.
(Used to query hwframe constraints.)
Definition at line 54 of file hwcontext_internal.h.
frames_hwctx_size
size_t HWContextType::frames_hwctx_size
size of the public frame pool hardware-specific context, i.e.
AVHWFramesContext.hwctx
Definition at line 60 of file hwcontext_internal.h.
frames_priv_size
size_t HWContextType::frames_priv_size
size of the private data, i.e.
AVHWFramesInternal.priv
Definition at line 65 of file hwcontext_internal.h.
device_create
int(* HWContextType::device_create) (AVHWDeviceContext *ctx, const char *device, AVDictionary *opts, int flags)
Definition at line 67 of file hwcontext_internal.h.
Referenced by av_hwdevice_ctx_create().
device_init
int(* HWContextType::device_init) (AVHWDeviceContext *ctx)
Definition at line 70 of file hwcontext_internal.h.
Referenced by av_hwdevice_ctx_init().
device_uninit
void(* HWContextType::device_uninit) (AVHWDeviceContext *ctx)
Definition at line 71 of file hwcontext_internal.h.
Referenced by av_hwdevice_ctx_init(), and hwdevice_ctx_free().
frames_get_constraints
int(* HWContextType::frames_get_constraints) (AVHWDeviceContext *ctx, const void *hwconfig, AVHWFramesConstraints *constraints)
Definition at line 73 of file hwcontext_internal.h.
frames_init
int(* HWContextType::frames_init) (AVHWFramesContext *ctx)
Definition at line 77 of file hwcontext_internal.h.
Referenced by av_hwframe_ctx_init().
frames_uninit
void(* HWContextType::frames_uninit) (AVHWFramesContext *ctx)
Definition at line 78 of file hwcontext_internal.h.
Referenced by av_hwframe_ctx_init(), and hwframe_ctx_free().
frames_get_buffer
int(* HWContextType::frames_get_buffer) (AVHWFramesContext *ctx, AVFrame *frame)
Definition at line 80 of file hwcontext_internal.h.
Referenced by av_hwframe_get_buffer().
transfer_get_formats
int(* HWContextType::transfer_get_formats) (AVHWFramesContext *ctx, enum AVHWFrameTransferDirection dir, enum AVPixelFormat **formats)
Definition at line 81 of file hwcontext_internal.h.
Referenced by av_hwframe_transfer_get_formats().
transfer_data_to
int(* HWContextType::transfer_data_to) (AVHWFramesContext *ctx, AVFrame *dst, const AVFrame *src)
Definition at line 84 of file hwcontext_internal.h.
Referenced by av_hwframe_transfer_data().
transfer_data_from
int(* HWContextType::transfer_data_from) (AVHWFramesContext *ctx, AVFrame *dst, const AVFrame *src)
Definition at line 86 of file hwcontext_internal.h.
Referenced by av_hwframe_transfer_data().
The documentation for this struct was generated from the following file:
libavutil/hwcontext_internal.h