FFmpeg: ColorSpaceDSPContext Struct Reference
ColorSpaceDSPContext Struct Reference
#include <libavfilter/colorspacedsp.h>
Data Fields
yuv2rgb_fn yuv2rgb [NB_BPP][NB_SS]
rgb2yuv_fn rgb2yuv [NB_BPP][NB_SS]
rgb2yuv_fsb_fn rgb2yuv_fsb [NB_BPP][NB_SS]
yuv2yuv_fn yuv2yuv [NB_BPP][NB_BPP][NB_SS]
void(* multiply3x3)(int16_t *data[3], ptrdiff_t stride, int w, int h, const int16_t m[3][3][8])
Detailed Description
Definition at line 59 of file colorspacedsp.h.
Field Documentation
yuv2rgb
yuv2rgb_fn ColorSpaceDSPContext::yuv2rgb[NB_BPP][NB_SS]
Definition at line 62 of file colorspacedsp.h.
Referenced by check_yuv2rgb(), and create_filtergraph().
rgb2yuv
rgb2yuv_fn ColorSpaceDSPContext::rgb2yuv[NB_BPP][NB_SS]
Definition at line 65 of file colorspacedsp.h.
Referenced by check_rgb2yuv(), and create_filtergraph().
rgb2yuv_fsb
rgb2yuv_fsb_fn ColorSpaceDSPContext::rgb2yuv_fsb[NB_BPP][NB_SS]
Definition at line 67 of file colorspacedsp.h.
Referenced by create_filtergraph().
yuv2yuv
yuv2yuv_fn ColorSpaceDSPContext::yuv2yuv[NB_BPP][NB_BPP][NB_SS]
Definition at line 70 of file colorspacedsp.h.
Referenced by check_yuv2yuv(), and create_filtergraph().
multiply3x3
void(* ColorSpaceDSPContext::multiply3x3) (int16_t *data[3], ptrdiff_t stride, int w, int h, const int16_t m[3][3][8])
Definition at line 74 of file colorspacedsp.h.
Referenced by check_multiply3x3(), convert(), ff_colorspacedsp_init(), and ff_colorspacedsp_x86_init().
The documentation for this struct was generated from the following file:
libavfilter/colorspacedsp.h