FFmpeg: AVFloatDSPContext Struct Reference
AVFloatDSPContext Struct Reference
#include <libavutil/float_dsp.h>
Data Fields
void(* vector_fmul)(float *dst, const float *src0, const float *src1, int len)
Calculate the entry wise product of two vectors of floats and store the result in a vector of floats.
void(* vector_fmac_scalar)(float *dst, const float *src, float mul, int len)
Multiply a vector of floats by a scalar float and add to destination vector.
void(* vector_fmul_scalar)(float *dst, const float *src, float mul, int len)
Multiply a vector of floats by a scalar float.
void(* vector_dmul_scalar)(double *dst, const double *src, double mul, int len)
Multiply a vector of double by a scalar double.
void(* vector_fmul_window)(float *dst, const float *src0, const float *src1, const float *win, int len)
Overlap/add with window function.
void(* vector_fmul_add)(float *dst, const float *src0, const float *src1, const float *src2, int len)
Calculate the entry wise product of two vectors of floats, add a third vector of floats and store the result in a vector of floats.
void(* vector_fmul_reverse)(float *dst, const float *src0, const float *src1, int len)
Calculate the entry wise product of two vectors of floats, and store the result in a vector of floats.
void(* butterflies_float)(float *av_restrict v1, float *av_restrict v2, int len)
Calculate the sum and difference of two vectors of floats.
float(* scalarproduct_float)(const float *v1, const float *v2, int len)
Calculate the scalar product of two vectors of floats.
Detailed Description
Definition at line 24 of file float_dsp.h.
Field Documentation
vector_fmul
void(* AVFloatDSPContext::vector_fmul) (float *dst, const float *src0, const float *src1, int len)
Calculate the entry wise product of two vectors of floats and store the result in a vector of floats.
Parameters
dst output vector constraints: 32-byte aligned
src0 first input vector constraints: 32-byte aligned
src1 second input vector constraints: 32-byte aligned
len number of elements in the input constraints: multiple of 16
Definition at line 38 of file float_dsp.h.
Referenced by apply_mdct(), apply_window_and_mdct(), avpriv_float_dsp_alloc(), backward_filter(), do_hybrid_window(), ff_atrac3p_generate_tones(), ff_atrac3p_imdct(), ff_float_dsp_init_aarch64(), ff_float_dsp_init_mips(), ff_float_dsp_init_neon(), ff_float_dsp_init_ppc(), ff_float_dsp_init_vfp(), ff_float_dsp_init_x86(), imlt(), read_and_decode_spectrum(), sbr_qmf_synthesis(), test_vector_fmul(), vorbis_parse_audio_packet(), and windowing_and_mdct_ltp().
vector_fmac_scalar
void(* AVFloatDSPContext::vector_fmac_scalar) (float *dst, const float *src, float mul, int len)
Multiply a vector of floats by a scalar float and add to destination vector.
Source and destination vectors must overlap exactly or not at all.
Parameters
dst result vector constraints: 32-byte aligned
src input vector constraints: 32-byte aligned
mul scalar value
len length of vector constraints: multiple of 16
Definition at line 54 of file float_dsp.h.
Referenced by avpriv_float_dsp_alloc(), ff_celt_decode_frame(), ff_dca_downmix_to_stereo_float(), ff_float_dsp_init_aarch64(), ff_float_dsp_init_neon(), ff_float_dsp_init_x86(), filter_frame_float(), opus_decode_frame(), opus_flush_resample(), output_frame(), and test_vector_fmac_scalar().
vector_fmul_scalar
void(* AVFloatDSPContext::vector_fmul_scalar) (float *dst, const float *src, float mul, int len)
Multiply a vector of floats by a scalar float.
Source and destination vectors must overlap exactly or not at all.
Parameters
dst result vector constraints: 16-byte aligned
src input vector constraints: 16-byte aligned
mul scalar value
len length of vector constraints: multiple of 4
Definition at line 69 of file float_dsp.h.
Referenced by apply_intensity_stereo(), apply_window_and_mdct(), avpriv_float_dsp_alloc(), compensate_volume(), decode_spectrum_and_dequant(), decode_subframe(), ff_dca_downmix_to_stereo_float(), ff_float_dsp_init_aarch64(), ff_float_dsp_init_mips(), ff_float_dsp_init_neon(), ff_float_dsp_init_x86(), filter_frame(), filter_frame_float(), inverse_channel_transform(), mp3lame_encode_frame(), opus_decode_packet(), pcm_decode_frame(), search_for_pns(), test_vector_fmul_scalar(), and waves_synth().
vector_dmul_scalar
void(* AVFloatDSPContext::vector_dmul_scalar) (double *dst, const double *src, double mul, int len)
Multiply a vector of double by a scalar double.
Source and destination vectors must overlap exactly or not at all.
Parameters
dst result vector constraints: 32-byte aligned
src input vector constraints: 32-byte aligned
mul scalar value
len length of vector constraints: multiple of 8
Definition at line 84 of file float_dsp.h.
Referenced by avpriv_float_dsp_alloc(), ff_float_dsp_init_aarch64(), ff_float_dsp_init_x86(), filter_frame(), and test_vector_dmul_scalar().
vector_fmul_window
void(* AVFloatDSPContext::vector_fmul_window) (float *dst, const float *src0, const float *src1, const float *win, int len)
Overlap/add with window function.
Used primarily by MDCT-based audio codecs. Source and destination vectors must overlap exactly or not at all.
Parameters
dst result vector constraints: 16-byte aligned
src0 first source vector constraints: 16-byte aligned
src1 second source vector constraints: 16-byte aligned
win half-window vector constraints: 16-byte aligned
len length of vector constraints: multiple of 4
Definition at line 103 of file float_dsp.h.
Referenced by at1_imdct_block(), avpriv_float_dsp_alloc(), ff_celt_decode_frame(), ff_float_dsp_init_aarch64(), ff_float_dsp_init_mips(), ff_float_dsp_init_neon(), ff_float_dsp_init_ppc(), ff_float_dsp_init_vfp(), ff_float_dsp_init_x86(), imdct_and_window(), imdct_and_windowing(), imdct_and_windowing_ld(), nelly_decode_block(), on2avc_reconstruct_channel(), on2avc_reconstruct_channel_ext(), test_vector_fmul_window(), vorbis_parse_audio_packet(), and wmapro_window().
vector_fmul_add
void(* AVFloatDSPContext::vector_fmul_add) (float *dst, const float *src0, const float *src1, const float *src2, int len)
Calculate the entry wise product of two vectors of floats, add a third vector of floats and store the result in a vector of floats.
Parameters
dst output vector constraints: 32-byte aligned
src0 first input vector constraints: 32-byte aligned
src1 second input vector constraints: 32-byte aligned
src2 third input vector constraints: 32-byte aligned
len number of elements in the input constraints: multiple of 16
Definition at line 121 of file float_dsp.h.
Referenced by avpriv_float_dsp_alloc(), ff_float_dsp_init_aarch64(), ff_float_dsp_init_neon(), ff_float_dsp_init_ppc(), ff_float_dsp_init_x86(), sbr_qmf_synthesis(), test_vector_fmul_add(), transform_channel(), and wma_window().
vector_fmul_reverse
void(* AVFloatDSPContext::vector_fmul_reverse) (float *dst, const float *src0, const float *src1, int len)
Calculate the entry wise product of two vectors of floats, and store the result in a vector of floats.
The second vector of floats is iterated over in reverse order.
Parameters
dst output vector constraints: 32-byte aligned
src0 first input vector constraints: 32-byte aligned
src1 second input vector constraints: 32-byte aligned
len number of elements in the input constraints: multiple of 16
Definition at line 138 of file float_dsp.h.
Referenced by apply_mdct(), apply_window_and_mdct(), avpriv_float_dsp_alloc(), ff_atrac3p_imdct(), ff_float_dsp_init_aarch64(), ff_float_dsp_init_mips(), ff_float_dsp_init_neon(), ff_float_dsp_init_ppc(), ff_float_dsp_init_vfp(), ff_float_dsp_init_x86(), sbr_qmf_analysis(), test_vector_fmul_reverse(), transform_channel(), update_ltp(), windowing_and_mdct_ltp(), and wma_window().
butterflies_float
void(* AVFloatDSPContext::butterflies_float) (float *av_restrict v1, float *av_restrict v2, int len)
Calculate the sum and difference of two vectors of floats.
Parameters
v1 first input vector, sum output, 16-byte aligned
v2 second input vector, difference output, 16-byte aligned
len length of vectors, multiple of 4
Definition at line 148 of file float_dsp.h.
Referenced by apply_mid_side_stereo(), avpriv_float_dsp_alloc(), compute_stereo(), ff_float_dsp_init_aarch64(), ff_float_dsp_init_mips(), ff_float_dsp_init_neon(), ff_float_dsp_init_vfp(), ff_float_dsp_init_x86(), filter_frame_float(), imc_decode_frame(), imdct_output(), test_butterflies_float(), and wma_decode_block().
scalarproduct_float
float(* AVFloatDSPContext::scalarproduct_float) (const float *v1, const float *v2, int len)
Calculate the scalar product of two vectors of floats.
Parameters
v1 first vector, 16-byte aligned
v2 second vector, 16-byte aligned
len length of vectors, multiple of 4
Returns
sum of elementwise products
Definition at line 159 of file float_dsp.h.
Referenced by avpriv_float_dsp_alloc(), compensate_volume(), decode_spectrum_and_dequant(), dot_prod(), ff_float_dsp_init_aarch64(), ff_float_dsp_init_neon(), ff_float_dsp_init_x86(), search_for_pns(), sofalizer_convolute(), and test_scalarproduct_float().
The documentation for this struct was generated from the following file:
libavutil/float_dsp.h