FFmpeg: HuffYUVDSPContext Struct Reference
HuffYUVDSPContext Struct Reference
#include <libavcodec/huffyuvdsp.h>
Data Fields
void(* add_bytes)(uint8_t *dst, uint8_t *src, intptr_t w)
void(* add_hfyu_median_pred)(uint8_t *dst, const uint8_t *top, const uint8_t *diff, intptr_t w, int *left, int *left_top)
int(* add_hfyu_left_pred)(uint8_t *dst, const uint8_t *src, intptr_t w, int left)
void(* add_hfyu_left_pred_bgr32)(uint8_t *dst, const uint8_t *src, intptr_t w, uint8_t *left)
Detailed Description
Definition at line 37 of file huffyuvdsp.h.
Field Documentation
add_bytes
void(* HuffYUVDSPContext::add_bytes) (uint8_t *dst, uint8_t *src, intptr_t w)
Definition at line 38 of file huffyuvdsp.h.
Referenced by add_bytes(), decode_frame(), ff_huffyuvdsp_init(), ff_huffyuvdsp_init_ppc(), ff_huffyuvdsp_init_x86(), and magy_decode_slice().
add_hfyu_median_pred
void(* HuffYUVDSPContext::add_hfyu_median_pred) (uint8_t *dst, const uint8_t *top, const uint8_t *diff, intptr_t w, int *left, int *left_top)
Definition at line 40 of file huffyuvdsp.h.
Referenced by add_median_prediction(), decode_frame(), ff_huffyuvdsp_init(), ff_huffyuvdsp_init_x86(), lag_pred_line_yuy2(), magy_decode_slice(), restore_median_planar(), restore_median_planar_il(), and vble_restore_plane().
add_hfyu_left_pred
int(* HuffYUVDSPContext::add_hfyu_left_pred) (uint8_t *dst, const uint8_t *src, intptr_t w, int left)
Definition at line 43 of file huffyuvdsp.h.
Referenced by decode_frame(), ff_huffyuvdsp_init(), ff_huffyuvdsp_init_x86(), lag_pred_line(), lag_pred_line_yuy2(), left_prediction(), magy_decode_slice(), restore_median_planar(), and restore_median_planar_il().
add_hfyu_left_pred_bgr32
void(* HuffYUVDSPContext::add_hfyu_left_pred_bgr32) (uint8_t *dst, const uint8_t *src, intptr_t w, uint8_t *left)
Definition at line 45 of file huffyuvdsp.h.
Referenced by decode_frame(), ff_huffyuvdsp_init(), and ff_huffyuvdsp_init_x86().
The documentation for this struct was generated from the following file:
libavcodec/huffyuvdsp.h