FFmpeg: VAAPIEncodeType Struct Reference
VAAPIEncodeType Struct Reference
#include <libavcodec/vaapi_encode.h>
Data Fields
size_t priv_data_size
int(* configure)(AVCodecContext *avctx)
size_t sequence_params_size
size_t picture_params_size
size_t slice_params_size
int(* init_sequence_params)(AVCodecContext *avctx)
int(* init_picture_params)(AVCodecContext *avctx, VAAPIEncodePicture *pic)
int(* init_slice_params)(AVCodecContext *avctx, VAAPIEncodePicture *pic, VAAPIEncodeSlice *slice)
int sequence_header_type
int picture_header_type
int slice_header_type
int(* write_sequence_header)(AVCodecContext *avctx, char *data, size_t *data_len)
int(* write_picture_header)(AVCodecContext *avctx, VAAPIEncodePicture *pic, char *data, size_t *data_len)
int(* write_slice_header)(AVCodecContext *avctx, VAAPIEncodePicture *pic, VAAPIEncodeSlice *slice, char *data, size_t *data_len)
int(* write_extra_buffer)(AVCodecContext *avctx, VAAPIEncodePicture *pic, int index, int *type, char *data, size_t *data_len)
int(* write_extra_header)(AVCodecContext *avctx, VAAPIEncodePicture *pic, int index, int *type, char *data, size_t *data_len)
Detailed Description
Definition at line 209 of file vaapi_encode.h.
Field Documentation
priv_data_size
size_t VAAPIEncodeType::priv_data_size
Definition at line 210 of file vaapi_encode.h.
Referenced by ff_vaapi_encode_init().
configure
int(* VAAPIEncodeType::configure) (AVCodecContext *avctx)
Definition at line 215 of file vaapi_encode.h.
Referenced by ff_vaapi_encode_init().
sequence_params_size
size_t VAAPIEncodeType::sequence_params_size
Definition at line 219 of file vaapi_encode.h.
Referenced by ff_vaapi_encode_init(), and vaapi_encode_issue().
picture_params_size
size_t VAAPIEncodeType::picture_params_size
Definition at line 220 of file vaapi_encode.h.
Referenced by ff_vaapi_encode_init(), and vaapi_encode_issue().
slice_params_size
size_t VAAPIEncodeType::slice_params_size
Definition at line 221 of file vaapi_encode.h.
Referenced by vaapi_encode_issue().
init_sequence_params
int(* VAAPIEncodeType::init_sequence_params) (AVCodecContext *avctx)
Definition at line 224 of file vaapi_encode.h.
Referenced by ff_vaapi_encode_init(), and vaapi_encode_issue().
init_picture_params
int(* VAAPIEncodeType::init_picture_params) (AVCodecContext *avctx, VAAPIEncodePicture *pic)
Definition at line 225 of file vaapi_encode.h.
Referenced by vaapi_encode_issue().
init_slice_params
int(* VAAPIEncodeType::init_slice_params) (AVCodecContext *avctx, VAAPIEncodePicture *pic, VAAPIEncodeSlice *slice)
Definition at line 227 of file vaapi_encode.h.
Referenced by vaapi_encode_issue().
sequence_header_type
int VAAPIEncodeType::sequence_header_type
Definition at line 233 of file vaapi_encode.h.
Referenced by vaapi_encode_issue().
picture_header_type
int VAAPIEncodeType::picture_header_type
Definition at line 234 of file vaapi_encode.h.
Referenced by vaapi_encode_issue().
slice_header_type
int VAAPIEncodeType::slice_header_type
Definition at line 235 of file vaapi_encode.h.
Referenced by vaapi_encode_issue().
write_sequence_header
int(* VAAPIEncodeType::write_sequence_header) (AVCodecContext *avctx, char *data, size_t *data_len)
Definition at line 240 of file vaapi_encode.h.
Referenced by ff_vaapi_encode_init(), and vaapi_encode_issue().
write_picture_header
int(* VAAPIEncodeType::write_picture_header) (AVCodecContext *avctx, VAAPIEncodePicture *pic, char *data, size_t *data_len)
Definition at line 242 of file vaapi_encode.h.
Referenced by vaapi_encode_issue().
write_slice_header
int(* VAAPIEncodeType::write_slice_header) (AVCodecContext *avctx, VAAPIEncodePicture *pic, VAAPIEncodeSlice *slice, char *data, size_t *data_len)
Definition at line 245 of file vaapi_encode.h.
Referenced by vaapi_encode_issue().
write_extra_buffer
int(* VAAPIEncodeType::write_extra_buffer) (AVCodecContext *avctx, VAAPIEncodePicture *pic, int index, int *type, char *data, size_t *data_len)
Definition at line 254 of file vaapi_encode.h.
Referenced by vaapi_encode_issue().
write_extra_header
int(* VAAPIEncodeType::write_extra_header) (AVCodecContext *avctx, VAAPIEncodePicture *pic, int index, int *type, char *data, size_t *data_len)
Definition at line 262 of file vaapi_encode.h.
Referenced by vaapi_encode_issue().
The documentation for this struct was generated from the following file:
libavcodec/vaapi_encode.h