FFmpeg: ACELPFContext Struct Reference
ACELPFContext Struct Reference
#include <libavcodec/acelp_filters.h>
Data Fields
void(* acelp_interpolatef)(float *out, const float *in, const float *filter_coeffs, int precision, int frac_pos, int filter_length, int length)
Floating point version of ff_acelp_interpolate()
void(* acelp_apply_order_2_transfer_function)(float *out, const float *in, const float zero_coeffs[2], const float pole_coeffs[2], float gain, float mem[2], int n)
Apply an order 2 rational transfer function in-place.
Detailed Description
Definition at line 28 of file acelp_filters.h.
Field Documentation
acelp_interpolatef
void(* ACELPFContext::acelp_interpolatef) (float *out, const float *in, const float *filter_coeffs, int precision, int frac_pos, int filter_length, int length)
Floating point version of ff_acelp_interpolate()
Definition at line 32 of file acelp_filters.h.
Referenced by decode_pitch_vector(), ff_acelp_filter_init(), and ff_acelp_filter_init_mips().
acelp_apply_order_2_transfer_function
void(* ACELPFContext::acelp_apply_order_2_transfer_function) (float *out, const float *in, const float zero_coeffs[2], const float pole_coeffs[2], float gain, float mem[2], int n)
Apply an order 2 rational transfer function in-place.
Parameters
out output buffer for filtered speech samples
in input buffer containing speech data (may be the same as out)
zero_coeffs z^-1 and z^-2 coefficients of the numerator
pole_coeffs z^-1 and z^-2 coefficients of the denominator
gain scale factor for final output
mem intermediate values used by filter (should be 0 initially)
n number of samples (should be a multiple of eight)
Definition at line 47 of file acelp_filters.h.
Referenced by amrnb_decode_frame(), amrwb_decode_frame(), ff_acelp_filter_init(), and ff_acelp_filter_init_mips().
The documentation for this struct was generated from the following file:
libavcodec/acelp_filters.h