FFmpeg: PNGDSPContext Struct Reference
PNGDSPContext Struct Reference
#include <libavcodec/pngdsp.h>
Data Fields
void(* add_bytes_l2)(uint8_t *dst, uint8_t *src1, uint8_t *src2, int w)
void(* add_paeth_prediction)(uint8_t *dst, uint8_t *src, uint8_t *top, int w, int bpp)
Detailed Description
Definition at line 27 of file pngdsp.h.
Field Documentation
add_bytes_l2
void(* PNGDSPContext::add_bytes_l2) (uint8_t *dst, uint8_t *src1, uint8_t *src2, int w)
Definition at line 28 of file pngdsp.h.
Referenced by ff_pngdsp_init(), ff_pngdsp_init_x86(), and png_filter_row().
add_paeth_prediction
void(* PNGDSPContext::add_paeth_prediction) (uint8_t *dst, uint8_t *src, uint8_t *top, int w, int bpp)
Definition at line 33 of file pngdsp.h.
Referenced by ff_pngdsp_init(), ff_pngdsp_init_x86(), and png_filter_row().
The documentation for this struct was generated from the following file:
libavcodec/pngdsp.h