FFmpeg: BswapDSPContext Struct Reference
BswapDSPContext Struct Reference
#include <libavcodec/bswapdsp.h>
Data Fields
void(* bswap_buf)(uint32_t *dst, const uint32_t *src, int w)
void(* bswap16_buf)(uint16_t *dst, const uint16_t *src, int len)
Detailed Description
Definition at line 24 of file bswapdsp.h.
Field Documentation
bswap_buf
void(* BswapDSPContext::bswap_buf) (uint32_t *dst, const uint32_t *src, int w)
Definition at line 25 of file bswapdsp.h.
Referenced by ape_decode_frame(), checkasm_check_bswapdsp(), decode_frame(), decode_i_frame(), decode_p_frame(), decode_plane(), decode_plane10(), encode_frame(), encode_plane(), ff_bswapdsp_init(), ff_bswapdsp_init_x86(), fraps2_decode_plane(), mimic_decode_frame(), mp_decode_frame(), mpc7_decode_frame(), mpc7_decode_init(), raw_decode(), tqi_decode_frame(), and truespeech_read_frame().
bswap16_buf
void(* BswapDSPContext::bswap16_buf) (uint16_t *dst, const uint16_t *src, int len)
Definition at line 26 of file bswapdsp.h.
Referenced by checkasm_check_bswapdsp(), cllc_decode_frame(), decode_frame(), ff_bswapdsp_init(), imc_decode_frame(), raw_decode(), update_md5_sum(), and verify_md5().
The documentation for this struct was generated from the following file:
libavcodec/bswapdsp.h