FFmpeg: ALACDSPContext Struct Reference
ALACDSPContext Struct Reference
#include <libavcodec/alacdsp.h>
Data Fields
void(* decorrelate_stereo)(int32_t *buffer[2], int nb_samples, int decorr_shift, int decorr_left_weight)
void(* append_extra_bits [2])(int32_t *buffer[2], int32_t *extra_bits_buffer[2], int extra_bits, int channels, int nb_samples)
Detailed Description
Definition at line 24 of file alacdsp.h.
Field Documentation
decorrelate_stereo
void(* ALACDSPContext::decorrelate_stereo) (int32_t *buffer[2], int nb_samples, int decorr_shift, int decorr_left_weight)
Definition at line 25 of file alacdsp.h.
Referenced by check_decorrelate_stereo(), decode_element(), ff_alacdsp_init(), and ff_alacdsp_init_x86().
append_extra_bits
void(* ALACDSPContext::append_extra_bits[2])(int32_t *buffer[2], int32_t *extra_bits_buffer[2], int extra_bits, int channels, int nb_samples)
Definition at line 27 of file alacdsp.h.
Referenced by check_append_extra_bits(), decode_element(), ff_alacdsp_init(), and ff_alacdsp_init_x86().
The documentation for this struct was generated from the following file:
libavcodec/alacdsp.h