FFmpeg: HEVCPredContext Struct Reference
HEVCPredContext Struct Reference
#include <libavcodec/hevcpred.h>
Data Fields
void(* intra_pred [4])(struct HEVCContext *s, int x0, int y0, int c_idx)
void(* pred_planar [4])(uint8_t *src, const uint8_t *top, const uint8_t *left, ptrdiff_t stride)
void(* pred_dc)(uint8_t *src, const uint8_t *top, const uint8_t *left, ptrdiff_t stride, int log2_size, int c_idx)
void(* pred_angular [4])(uint8_t *src, const uint8_t *top, const uint8_t *left, ptrdiff_t stride, int c_idx, int mode)
Detailed Description
Definition at line 31 of file hevcpred.h.
Field Documentation
intra_pred
void(* HEVCPredContext::intra_pred[4])(struct HEVCContext *s, int x0, int y0, int c_idx)
Definition at line 32 of file hevcpred.h.
Referenced by hls_transform_unit().
pred_planar
void(* HEVCPredContext::pred_planar[4])(uint8_t *src, const uint8_t *top, const uint8_t *left, ptrdiff_t stride)
Definition at line 34 of file hevcpred.h.
Referenced by ff_intra_pred_8_16x16_msa(), and ff_intra_pred_8_32x32_msa().
pred_dc
void(* HEVCPredContext::pred_dc) (uint8_t *src, const uint8_t *top, const uint8_t *left, ptrdiff_t stride, int log2_size, int c_idx)
Definition at line 36 of file hevcpred.h.
Referenced by ff_intra_pred_8_16x16_msa(), and ff_intra_pred_8_32x32_msa().
pred_angular
void(* HEVCPredContext::pred_angular[4])(uint8_t *src, const uint8_t *top, const uint8_t *left, ptrdiff_t stride, int c_idx, int mode)
Definition at line 38 of file hevcpred.h.
Referenced by ff_intra_pred_8_16x16_msa(), and ff_intra_pred_8_32x32_msa().
The documentation for this struct was generated from the following file:
libavcodec/hevcpred.h