FFmpeg: CoreImageContext Struct Reference
CoreImageContext Struct Reference
Protected Attributes
const AVClass * class
int is_video_source
filter is used as video source
int w
int h
video size
AVRational sar
sample aspect ratio
AVRational frame_rate
video frame rate
AVRational time_base
stream time base
int64_t duration
duration expressed in microseconds
int64_t pts
increasing presentation time stamp
AVFrame * picref
cached reference containing the painted picture
CFTypeRef glctx
OpenGL context.
CGContextRef cgctx
Bitmap context for image copy.
CFTypeRef input_image
Input image container for passing into Core Image API.
CGColorSpaceRef color_space
Common color space for input image and cgcontext.
int bits_per_component
Shared bpc for input-output operation.
char * filter_string
The complete user provided filter definition.
CFTypeRef * filters
CIFilter object for all requested filters.
int num_filters
Amount of filters in *filters.
char * output_rect
Rectangle to be filled with filter intput.
int list_filters
Option used to list all available filters including generators.
int list_generators
Option used to list all available generators.
Detailed Description
Definition at line 37 of file vf_coreimage.m.
Field Documentation
class
- (const AVClass*) class protected
Definition at line 38 of file vf_coreimage.m.
is_video_source
- (int) is_video_source protected
filter is used as video source
Definition at line 40 of file vf_coreimage.m.
Referenced by apply_filter(), and init_src().
w
- (int) w protected
Definition at line 42 of file vf_coreimage.m.
Referenced by config_output(), and request_frame().
h
- (int) h protected
video size
Definition at line 42 of file vf_coreimage.m.
Referenced by config_output(), and request_frame().
sar
- (AVRational) sar protected
sample aspect ratio
Definition at line 43 of file vf_coreimage.m.
Referenced by config_output(), and request_frame().
frame_rate
- (AVRational) frame_rate protected
video frame rate
Definition at line 44 of file vf_coreimage.m.
Referenced by config_output(), and init_src().
time_base
- (AVRational) time_base protected
stream time base
Definition at line 45 of file vf_coreimage.m.
Referenced by config_output(), init_src(), and request_frame().
duration
- (int64_t) duration protected
duration expressed in microseconds
Definition at line 46 of file vf_coreimage.m.
Referenced by request_frame().
pts
- (int64_t) pts protected
increasing presentation time stamp
Definition at line 47 of file vf_coreimage.m.
Referenced by init_src(), and request_frame().
picref
- (AVFrame*) picref protected
cached reference containing the painted picture
Definition at line 48 of file vf_coreimage.m.
Referenced by request_frame(), and uninit().
glctx
- (CFTypeRef) glctx protected
OpenGL context.
Definition at line 50 of file vf_coreimage.m.
Referenced by init(), and uninit().
cgctx
- (CGContextRef) cgctx protected
Bitmap context for image copy.
Definition at line 51 of file vf_coreimage.m.
Referenced by apply_filter(), and uninit().
input_image
- (CFTypeRef) input_image protected
Input image container for passing into Core Image API.
Definition at line 52 of file vf_coreimage.m.
Referenced by apply_filter(), init(), and uninit().
color_space
- (CGColorSpaceRef) color_space protected
Common color space for input image and cgcontext.
Definition at line 53 of file vf_coreimage.m.
Referenced by apply_filter(), init(), and uninit().
bits_per_component
- (int) bits_per_component protected
Shared bpc for input-output operation.
Definition at line 54 of file vf_coreimage.m.
Referenced by apply_filter(), config_input(), and config_output().
filter_string
- (char*) filter_string protected
The complete user provided filter definition.
Definition at line 56 of file vf_coreimage.m.
Referenced by init().
filters
- (CFTypeRef*) filters protected
CIFilter object for all requested filters.
Definition at line 57 of file vf_coreimage.m.
Referenced by apply_filter(), init(), list_filters(), and uninit().
num_filters
- (int) num_filters protected
Amount of filters in *filters.
Definition at line 58 of file vf_coreimage.m.
Referenced by apply_filter(), init(), and uninit().
output_rect
- (char*) output_rect protected
Rectangle to be filled with filter intput.
Definition at line 60 of file vf_coreimage.m.
Referenced by apply_filter().
list_filters
- (int) list_filters protected
Option used to list all available filters including generators.
Definition at line 61 of file vf_coreimage.m.
Referenced by init(), and list_filters().
list_generators
- (int) list_generators protected
Option used to list all available generators.
Definition at line 62 of file vf_coreimage.m.
Referenced by init(), and list_filters().
The documentation for this struct was generated from the following file:
libavfilter/vf_coreimage.m