FFmpeg: TAKDSPContext Struct Reference
TAKDSPContext Struct Reference
#include <libavcodec/takdsp.h>
Data Fields
void(* decorrelate_ls)(int32_t *p1, int32_t *p2, int length)
void(* decorrelate_sr)(int32_t *p1, int32_t *p2, int length)
void(* decorrelate_sm)(int32_t *p1, int32_t *p2, int length)
void(* decorrelate_sf)(int32_t *p1, int32_t *p2, int length, int dshift, int dfactor)
Detailed Description
Definition at line 24 of file takdsp.h.
Field Documentation
decorrelate_ls
void(* TAKDSPContext::decorrelate_ls) (int32_t *p1, int32_t *p2, int length)
Definition at line 25 of file takdsp.h.
Referenced by decorrelate(), ff_takdsp_init(), and ff_takdsp_init_x86().
decorrelate_sr
void(* TAKDSPContext::decorrelate_sr) (int32_t *p1, int32_t *p2, int length)
Definition at line 26 of file takdsp.h.
Referenced by decorrelate(), ff_takdsp_init(), and ff_takdsp_init_x86().
decorrelate_sm
void(* TAKDSPContext::decorrelate_sm) (int32_t *p1, int32_t *p2, int length)
Definition at line 27 of file takdsp.h.
Referenced by decorrelate(), ff_takdsp_init(), and ff_takdsp_init_x86().
decorrelate_sf
void(* TAKDSPContext::decorrelate_sf) (int32_t *p1, int32_t *p2, int length, int dshift, int dfactor)
Definition at line 28 of file takdsp.h.
Referenced by decorrelate(), ff_takdsp_init(), and ff_takdsp_init_x86().
The documentation for this struct was generated from the following file:
libavcodec/takdsp.h