FFmpeg: W3FDIFDSPContext Struct Reference
W3FDIFDSPContext Struct Reference
#include <libavfilter/w3fdif.h>
Data Fields
void(* filter_simple_low)(int32_t *work_line, uint8_t *in_lines_cur[2], const int16_t *coef, int linesize)
void(* filter_complex_low)(int32_t *work_line, uint8_t *in_lines_cur[4], const int16_t *coef, int linesize)
void(* filter_simple_high)(int32_t *work_line, uint8_t *in_lines_cur[3], uint8_t *in_lines_adj[3], const int16_t *coef, int linesize)
void(* filter_complex_high)(int32_t *work_line, uint8_t *in_lines_cur[5], uint8_t *in_lines_adj[5], const int16_t *coef, int linesize)
void(* filter_scale)(uint8_t *out_pixel, const int32_t *work_pixel, int linesize, int max)
Detailed Description
Definition at line 27 of file w3fdif.h.
Field Documentation
filter_simple_low
void(* W3FDIFDSPContext::filter_simple_low) (int32_t *work_line, uint8_t *in_lines_cur[2], const int16_t *coef, int linesize)
Definition at line 28 of file w3fdif.h.
Referenced by config_input(), deinterlace_slice(), and ff_w3fdif_init_x86().
filter_complex_low
void(* W3FDIFDSPContext::filter_complex_low) (int32_t *work_line, uint8_t *in_lines_cur[4], const int16_t *coef, int linesize)
Definition at line 31 of file w3fdif.h.
Referenced by config_input(), deinterlace_slice(), and ff_w3fdif_init_x86().
filter_simple_high
void(* W3FDIFDSPContext::filter_simple_high) (int32_t *work_line, uint8_t *in_lines_cur[3], uint8_t *in_lines_adj[3], const int16_t *coef, int linesize)
Definition at line 34 of file w3fdif.h.
Referenced by config_input(), deinterlace_slice(), and ff_w3fdif_init_x86().
filter_complex_high
void(* W3FDIFDSPContext::filter_complex_high) (int32_t *work_line, uint8_t *in_lines_cur[5], uint8_t *in_lines_adj[5], const int16_t *coef, int linesize)
Definition at line 38 of file w3fdif.h.
Referenced by config_input(), deinterlace_slice(), and ff_w3fdif_init_x86().
filter_scale
void(* W3FDIFDSPContext::filter_scale) (uint8_t *out_pixel, const int32_t *work_pixel, int linesize, int max)
Definition at line 42 of file w3fdif.h.
Referenced by config_input(), deinterlace_slice(), and ff_w3fdif_init_x86().
The documentation for this struct was generated from the following file:
libavfilter/w3fdif.h