FFmpeg: FFIIRFilterContext Struct Reference
FFIIRFilterContext Struct Reference
#include <libavcodec/iirfilter.h>
Data Fields
void(* filter_flt)(const struct FFIIRFilterCoeffs *coeffs, struct FFIIRFilterState *state, int size, const float *src, int sstep, float *dst, int dstep)
Perform IIR filtering on floating-point input samples.
Detailed Description
Definition at line 50 of file iirfilter.h.
Field Documentation
filter_flt
void(* FFIIRFilterContext::filter_flt) (const struct FFIIRFilterCoeffs *coeffs, struct FFIIRFilterState *state, int size, const float *src, int sstep, float *dst, int dstep)
Perform IIR filtering on floating-point input samples.
Parameters
coeffs pointer to filter coefficients
state pointer to filter state
size input length
src source samples
sstep source stride
dst filtered samples (destination may be the same as input)
dstep destination stride
Definition at line 62 of file iirfilter.h.
Referenced by ff_iir_filter_init(), ff_iir_filter_init_mips(), and ff_psy_preprocess().
The documentation for this struct was generated from the following file:
libavcodec/iirfilter.h