FFmpeg: Jpeg2000DSPContext Struct Reference
Jpeg2000DSPContext Struct Reference
#include <libavcodec/jpeg2000dsp.h>
Data Fields
void(* mct_decode [FF_DWT_NB])(void *src0, void *src1, void *src2, int csize)
Detailed Description
Definition at line 29 of file jpeg2000dsp.h.
Field Documentation
mct_decode
void(* Jpeg2000DSPContext::mct_decode[FF_DWT_NB])(void *src0, void *src1, void *src2, int csize)
Definition at line 30 of file jpeg2000dsp.h.
Referenced by checkasm_check_jpeg2000dsp(), ff_jpeg2000dsp_init(), ff_jpeg2000dsp_init_x86(), and mct_decode().
The documentation for this struct was generated from the following file:
libavcodec/jpeg2000dsp.h