FFmpeg: V210DecContext Struct Reference
V210DecContext Struct Reference
#include <libavcodec/v210dec.h>
Data Fields
AVClass * av_class
int custom_stride
int aligned_input
int stride_warning_shown
void(* unpack_frame)(const uint32_t *src, uint16_t *y, uint16_t *u, uint16_t *v, int width)
Detailed Description
Definition at line 26 of file v210dec.h.
Field Documentation
av_class
AVClass* V210DecContext::av_class
Definition at line 27 of file v210dec.h.
custom_stride
int V210DecContext::custom_stride
Definition at line 28 of file v210dec.h.
Referenced by decode_frame().
aligned_input
int V210DecContext::aligned_input
Definition at line 29 of file v210dec.h.
Referenced by decode_frame(), and ff_v210_x86_init().
stride_warning_shown
int V210DecContext::stride_warning_shown
Definition at line 30 of file v210dec.h.
Referenced by decode_frame().
unpack_frame
void(* V210DecContext::unpack_frame) (const uint32_t *src, uint16_t *y, uint16_t *u, uint16_t *v, int width)
Definition at line 31 of file v210dec.h.
Referenced by decode_frame(), decode_init(), and ff_v210_x86_init().
The documentation for this struct was generated from the following file:
libavcodec/v210dec.h