FFmpeg: OCVFilterEntry Struct Reference
OCVFilterEntry Struct Reference
Data Fields
const char * name
size_t priv_size
int(* init)(AVFilterContext *ctx, const char *args)
void(* uninit)(AVFilterContext *ctx)
void(* end_frame_filter)(AVFilterContext *ctx, IplImage *inimg, IplImage *outimg)
Detailed Description
Definition at line 323 of file vf_libopencv.c.
Field Documentation
name
const char* OCVFilterEntry::name
Definition at line 324 of file vf_libopencv.c.
Referenced by init().
priv_size
size_t OCVFilterEntry::priv_size
Definition at line 325 of file vf_libopencv.c.
Referenced by init().
init
int(* OCVFilterEntry::init) (AVFilterContext *ctx, const char *args)
Definition at line 326 of file vf_libopencv.c.
Referenced by init().
uninit
void(* OCVFilterEntry::uninit) (AVFilterContext *ctx)
Definition at line 327 of file vf_libopencv.c.
Referenced by init().
end_frame_filter
void(* OCVFilterEntry::end_frame_filter) (AVFilterContext *ctx, IplImage *inimg, IplImage *outimg)
Definition at line 328 of file vf_libopencv.c.
Referenced by init().
The documentation for this struct was generated from the following file:
libavfilter/vf_libopencv.c