FFmpeg: OCVContext Struct Reference
OCVContext Struct Reference
Data Fields
const AVClass * class
char * name
char * params
int(* init)(AVFilterContext *ctx, const char *args)
void(* uninit)(AVFilterContext *ctx)
void(* end_frame_filter)(AVFilterContext *ctx, IplImage *inimg, IplImage *outimg)
void * priv
Detailed Description
Definition at line 78 of file vf_libopencv.c.
Field Documentation
class
const AVClass* OCVContext::class
Definition at line 79 of file vf_libopencv.c.
name
char* OCVContext::name
Definition at line 80 of file vf_libopencv.c.
Referenced by init().
params
char* OCVContext::params
Definition at line 81 of file vf_libopencv.c.
Referenced by init().
init
int(* OCVContext::init) (AVFilterContext *ctx, const char *args)
Definition at line 82 of file vf_libopencv.c.
Referenced by init().
uninit
void(* OCVContext::uninit) (AVFilterContext *ctx)
Definition at line 83 of file vf_libopencv.c.
Referenced by init(), and uninit().
end_frame_filter
void(* OCVContext::end_frame_filter) (AVFilterContext *ctx, IplImage *inimg, IplImage *outimg)
Definition at line 84 of file vf_libopencv.c.
Referenced by filter_frame(), and init().
priv
void* OCVContext::priv
Definition at line 85 of file vf_libopencv.c.
Referenced by dilate_end_frame_filter(), dilate_init(), dilate_uninit(), erode_end_frame_filter(), init(), smooth_end_frame_filter(), smooth_init(), and uninit().
The documentation for this struct was generated from the following file:
libavfilter/vf_libopencv.c