FFmpeg: libavcodec/svq1enc.c File Reference
svq1enc.c File Reference
Sorenson Vector Quantizer #1 (SVQ1) video codec.
#include "avcodec.h"
#include "hpeldsp.h"
#include "me_cmp.h"
#include "mpegvideo.h"
#include "h263.h"
#include "internal.h"
#include "mpegutils.h"
#include "svq1.h"
#include "svq1enc.h"
#include "svq1enc_cb.h"
#include "libavutil/avassert.h"
Macros
#define QUALITY_THRESHOLD 100
#define THRESHOLD_MULTIPLIER 0.6
#define OFFSET(x) offsetof(struct SVQ1EncContext, x)
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Functions
static void svq1_write_header (SVQ1EncContext *s, int frame_type)
static int ssd_int8_vs_int16_c (const int8_t *pix1, const int16_t *pix2, intptr_t size)
static int encode_block (SVQ1EncContext *s, uint8_t *src, uint8_t *ref, uint8_t *decoded, int stride, int level, int threshold, int lambda, int intra)
static void init_block_index (MpegEncContext *s)
static int svq1_encode_plane (SVQ1EncContext *s, int plane, unsigned char *src_plane, unsigned char *ref_plane, unsigned char *decoded_plane, int width, int height, int src_stride, int stride)
static av_cold int svq1_encode_end (AVCodecContext *avctx)
static av_cold int svq1_encode_init (AVCodecContext *avctx)
static int svq1_encode_frame (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *pict, int *got_packet)
Variables
static const AVOption options []
static const AVClass svq1enc_class
AVCodec ff_svq1_encoder
Detailed Description
Sorenson Vector Quantizer #1 (SVQ1) video codec.
For more information of the SVQ1 algorithm, visit: http://www.pcisys.net/~melanson/codecs/
Definition in file svq1enc.c.
Macro Definition Documentation
QUALITY_THRESHOLD
#define QUALITY_THRESHOLD 100
Definition at line 76 of file svq1enc.c.
Referenced by svq1_encode_plane().
THRESHOLD_MULTIPLIER
#define THRESHOLD_MULTIPLIER 0.6
Definition at line 77 of file svq1enc.c.
Referenced by svq1_encode_plane().
OFFSET
#define OFFSET (x) offsetof(struct SVQ1EncContext, x)
Definition at line 679 of file svq1enc.c.
VE
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 680 of file svq1enc.c.
Function Documentation
svq1_write_header()
static void svq1_write_header (SVQ1EncContext * s, int frame_type) static
Definition at line 42 of file svq1enc.c.
Referenced by svq1_encode_frame().
ssd_int8_vs_int16_c()
static int ssd_int8_vs_int16_c (const int8_t * pix1, const int16_t * pix2, intptr_t size) static
Definition at line 79 of file svq1enc.c.
Referenced by svq1_encode_init().
encode_block()
static int encode_block (SVQ1EncContext * s, uint8_t * src, uint8_t * ref, uint8_t * decoded, int stride, int level, int threshold, int lambda, int intra) static
Definition at line 89 of file svq1enc.c.
Referenced by svq1_encode_plane().
init_block_index()
static void init_block_index (MpegEncContext * s) static
Definition at line 237 of file svq1enc.c.
Referenced by svq1_encode_plane().
svq1_encode_plane()
static int svq1_encode_plane (SVQ1EncContext * s, int plane, unsigned char * src_plane, unsigned char * ref_plane, unsigned char * decoded_plane, int width, int height, int src_stride, int stride) static
Definition at line 246 of file svq1enc.c.
Referenced by svq1_encode_frame().
svq1_encode_end()
static av_cold int svq1_encode_end (AVCodecContext * avctx) static
Definition at line 497 of file svq1enc.c.
Referenced by svq1_encode_init().
svq1_encode_init()
static av_cold int svq1_encode_init (AVCodecContext * avctx) static
Definition at line 527 of file svq1enc.c.
svq1_encode_frame()
static int svq1_encode_frame (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * pict, int * got_packet) static
Definition at line 593 of file svq1enc.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "motion-est", "Motion estimation algorithm", OFFSET(motion_est), AV_OPT_TYPE_INT, { .i64 = FF_ME_EPZS }, FF_ME_ZERO, FF_ME_XONE, VE, "motion-est"},
        { "zero", NULL, 0, AV_OPT_TYPE_CONST, { .i64 = FF_ME_ZERO }, 0, 0, FF_MPV_OPT_FLAGS, "motion-est" },
        { "epzs", NULL, 0, AV_OPT_TYPE_CONST, { .i64 = FF_ME_EPZS }, 0, 0, FF_MPV_OPT_FLAGS, "motion-est" },
        { "xone", NULL, 0, AV_OPT_TYPE_CONST, { .i64 = FF_ME_XONE }, 0, 0, FF_MPV_OPT_FLAGS, "motion-est" },
    { NULL },
}
Definition at line 681 of file svq1enc.c.
svq1enc_class
const AVClass svq1enc_class static
Initial value:
= {
    .class_name = "svq1enc",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 690 of file svq1enc.c.
ff_svq1_encoder
AVCodec ff_svq1_encoder
Initial value:
= {
    .name           = "svq1",
    .long_name      = NULL_IF_CONFIG_SMALL("Sorenson Vector Quantizer 1 / Sorenson Video 1 / SVQ1"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_SVQ1,
    .priv_data_size = sizeof(SVQ1EncContext),
    .priv_class     = &svq1enc_class,
    .init           = svq1_encode_init,
    .encode2        = svq1_encode_frame,
    .close          = svq1_encode_end,
    .pix_fmts       = (const enum AVPixelFormat[]) { AV_PIX_FMT_YUV410P,
                                                     AV_PIX_FMT_NONE },
}
Definition at line 697 of file svq1enc.c.