FFmpeg: libavcodec/x86/svq1enc_init.c File Reference
svq1enc_init.c File Reference
#include "config.h"
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/x86/cpu.h"
#include "libavcodec/svq1enc.h"
Functions
int ff_ssd_int8_vs_int16_mmx (const int8_t *pix1, const int16_t *pix2, intptr_t size)
int ff_ssd_int8_vs_int16_sse2 (const int8_t *pix1, const int16_t *pix2, intptr_t size)
av_cold void ff_svq1enc_init_x86 (SVQ1EncContext *c)
Function Documentation
ff_ssd_int8_vs_int16_mmx()
int ff_ssd_int8_vs_int16_mmx (const int8_t * pix1, const int16_t * pix2, intptr_t size)
Referenced by ff_svq1enc_init_x86().
ff_ssd_int8_vs_int16_sse2()
int ff_ssd_int8_vs_int16_sse2 (const int8_t * pix1, const int16_t * pix2, intptr_t size)
Referenced by ff_svq1enc_init_x86().
ff_svq1enc_init_x86()
av_cold void ff_svq1enc_init_x86 (SVQ1EncContext * c)
Definition at line 32 of file svq1enc_init.c.
Referenced by svq1_encode_init().