FFmpeg: libavformat/swfenc.c File Reference
swfenc.c File Reference
#include "libavcodec/put_bits.h"
#include "libavutil/avassert.h"
#include "avformat.h"
#include "swf.h"
Macros
#define FRAC_BITS 16
Functions
static void put_swf_tag (AVFormatContext *s, int tag)
static void put_swf_end_tag (AVFormatContext *s)
static void max_nbits (int *nbits_ptr, int val)
static void put_swf_rect (AVIOContext *pb, int xmin, int xmax, int ymin, int ymax)
static void put_swf_line_edge (PutBitContext *pb, int dx, int dy)
static void put_swf_matrix (AVIOContext *pb, int a, int b, int c, int d, int tx, int ty)
static int swf_write_header (AVFormatContext *s)
static int swf_write_video (AVFormatContext *s, AVCodecParameters *par, const uint8_t *buf, int size)
static int swf_write_audio (AVFormatContext *s, AVCodecParameters *par, uint8_t *buf, int size)
static int swf_write_packet (AVFormatContext *s, AVPacket *pkt)
static int swf_write_trailer (AVFormatContext *s)
Macro Definition Documentation
FRAC_BITS
#define FRAC_BITS 16
Definition at line 136 of file swfenc.c.
Referenced by swf_write_header(), and swf_write_video().
Function Documentation
put_swf_tag()
static void put_swf_tag (AVFormatContext * s, int tag) static
Definition at line 28 of file swfenc.c.
Referenced by swf_write_header(), swf_write_trailer(), and swf_write_video().
put_swf_end_tag()
static void put_swf_end_tag (AVFormatContext * s) static
Definition at line 44 of file swfenc.c.
Referenced by swf_write_header(), swf_write_trailer(), and swf_write_video().
max_nbits()
static void max_nbits (int * nbits_ptr, int val) inline static
Definition at line 66 of file swfenc.c.
Referenced by put_swf_line_edge(), put_swf_matrix(), and put_swf_rect().
put_swf_rect()
static void put_swf_rect (AVIOContext * pb, int xmin, int xmax, int ymin, int ymax) static
Definition at line 82 of file swfenc.c.
Referenced by swf_write_header().
put_swf_line_edge()
static void put_swf_line_edge (PutBitContext * pb, int dx, int dy) static
Definition at line 109 of file swfenc.c.
Referenced by swf_write_header().
put_swf_matrix()
static void put_swf_matrix (AVIOContext * pb, int a, int b, int c, int d, int tx, int ty) static
Definition at line 138 of file swfenc.c.
Referenced by swf_write_header(), and swf_write_video().
swf_write_header()
static int swf_write_header (AVFormatContext * s) static
Definition at line 174 of file swfenc.c.
Referenced by swf_write_trailer().
swf_write_video()
static int swf_write_video (AVFormatContext * s, AVCodecParameters * par, const uint8_t * buf, int size) static
Definition at line 344 of file swfenc.c.
Referenced by swf_write_audio(), and swf_write_packet().
swf_write_audio()
static int swf_write_audio (AVFormatContext * s, AVCodecParameters * par, uint8_t * buf, int size) static
Definition at line 449 of file swfenc.c.
Referenced by swf_write_packet().
swf_write_packet()
static int swf_write_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 473 of file swfenc.c.
Referenced by swf_write_trailer().
swf_write_trailer()
static int swf_write_trailer (AVFormatContext * s) static
Definition at line 482 of file swfenc.c.