FFmpeg: libswresample/swresample_frame.c File Reference
swresample_frame.c File Reference
#include "swresample_internal.h"
#include "libavutil/frame.h"
#include "libavutil/opt.h"
Functions
int swr_config_frame (SwrContext *s, const AVFrame *out, const AVFrame *in)
Configure or reconfigure the SwrContext using the information provided by the AVFrames.
static int config_changed (SwrContext *s, const AVFrame *out, const AVFrame *in)
static int convert_frame (SwrContext *s, AVFrame *out, const AVFrame *in)
static int available_samples (AVFrame *out)
int swr_convert_frame (SwrContext *s, AVFrame *out, const AVFrame *in)
Convert the samples in the input AVFrame and write them to the output AVFrame.
Function Documentation
config_changed()
static int config_changed (SwrContext * s, const AVFrame * out, const AVFrame * in) static
Definition at line 54 of file swresample_frame.c.
Referenced by swr_convert_frame().
convert_frame()
static int convert_frame (SwrContext * s, AVFrame * out, const AVFrame * in) inline static
Definition at line 78 of file swresample_frame.c.
Referenced by swr_convert_frame().
available_samples()
static int available_samples (AVFrame * out) inline static
Definition at line 110 of file swresample_frame.c.
Referenced by swr_convert_frame().