FFmpeg: libavcodec/synth_filter.h File Reference
synth_filter.h File Reference
#include "fft.h"
#include "dcadct.h"
Data Structures
struct SynthFilterContext
Functions
void ff_synth_filter_init (SynthFilterContext *c)
void ff_synth_filter_init_aarch64 (SynthFilterContext *c)
void ff_synth_filter_init_arm (SynthFilterContext *c)
void ff_synth_filter_init_x86 (SynthFilterContext *c)
Function Documentation
ff_synth_filter_init()
void ff_synth_filter_init (SynthFilterContext * c)
Definition at line 171 of file synth_filter.c.
Referenced by checkasm_check_synth_filter(), and ff_dca_core_init().
ff_synth_filter_init_aarch64()
void ff_synth_filter_init_aarch64 (SynthFilterContext * c)
Definition at line 41 of file synth_filter_init.c.
Referenced by ff_synth_filter_init().
ff_synth_filter_init_arm()
void ff_synth_filter_init_arm (SynthFilterContext * c)
Definition at line 41 of file synth_filter_init_arm.c.
Referenced by ff_synth_filter_init().
ff_synth_filter_init_x86()
void ff_synth_filter_init_x86 (SynthFilterContext * c)
Definition at line 54 of file synth_filter_init.c.
Referenced by ff_synth_filter_init().