FFmpeg: libavcodec/arm/synth_filter_init_arm.c File Reference
synth_filter_init_arm.c File Reference
#include "config.h"
#include "libavutil/arm/cpu.h"
#include "libavutil/attributes.h"
#include "libavutil/internal.h"
#include "libavcodec/fft.h"
#include "libavcodec/synth_filter.h"
Functions
void ff_synth_filter_float_vfp (FFTContext *imdct, float *synth_buf_ptr, int *synth_buf_offset, float synth_buf2[32], const float window[512], float out[32], const float in[32], float scale)
void ff_synth_filter_float_neon (FFTContext *imdct, float *synth_buf_ptr, int *synth_buf_offset, float synth_buf2[32], const float window[512], float out[32], const float in[32], float scale)
av_cold void ff_synth_filter_init_arm (SynthFilterContext *s)
Function Documentation
ff_synth_filter_float_vfp()
void ff_synth_filter_float_vfp (FFTContext * imdct, float * synth_buf_ptr, int * synth_buf_offset, float synth_buf2[32], const float window[512], float out[32], const float in[32], float scale)
Referenced by ff_synth_filter_init_arm().
ff_synth_filter_float_neon()
void ff_synth_filter_float_neon (FFTContext * imdct, float * synth_buf_ptr, int * synth_buf_offset, float synth_buf2[32], const float window[512], float out[32], const float in[32], float scale)
Referenced by ff_synth_filter_init_arm().
ff_synth_filter_init_arm()
av_cold void ff_synth_filter_init_arm (SynthFilterContext * s)
Definition at line 41 of file synth_filter_init_arm.c.
Referenced by ff_synth_filter_init().