FFmpeg: libavcodec/tak.c File Reference
tak.c File Reference
#include "libavutil/crc.h"
#include "libavutil/intreadwrite.h"
#include "tak.h"
Macros
#define BITSTREAM_READER_LE
Functions
static int tak_get_nb_samples (int sample_rate, enum TAKFrameSizeType type)
int ff_tak_check_crc (const uint8_t *buf, unsigned int buf_size)
void avpriv_tak_parse_streaminfo (GetBitContext *gb, TAKStreamInfo *s)
Parse the Streaminfo metadata block.
int ff_tak_decode_frame_header (AVCodecContext *avctx, GetBitContext *gb, TAKStreamInfo *ti, int log_level_offset)
Validate and decode a frame header.
Variables
static const int64_t tak_channel_layouts []
static const uint16_t frame_duration_type_quants []
Macro Definition Documentation
BITSTREAM_READER_LE
#define BITSTREAM_READER_LE
Definition at line 25 of file tak.c.
Function Documentation
tak_get_nb_samples()
static int tak_get_nb_samples (int sample_rate, enum TAKFrameSizeType type) static
Definition at line 54 of file tak.c.
Referenced by avpriv_tak_parse_streaminfo().
ff_tak_check_crc()
int ff_tak_check_crc (const uint8_t * buf, unsigned int buf_size)
Definition at line 77 of file tak.c.
Referenced by tak_decode_frame(), and tak_parse().
avpriv_tak_parse_streaminfo()
void avpriv_tak_parse_streaminfo (GetBitContext * gb, TAKStreamInfo * s)
Parse the Streaminfo metadata block.
Parameters
[in] gb pointer to GetBitContext
[out] s storage for parsed information
Definition at line 93 of file tak.c.
Referenced by ff_tak_decode_frame_header(), and tak_read_header().
ff_tak_decode_frame_header()
int ff_tak_decode_frame_header (AVCodecContext * avctx, GetBitContext * gb, TAKStreamInfo * s, int log_level_offset)
Validate and decode a frame header.
Parameters
avctx AVCodecContext to use as av_log() context
[in] gb GetBitContext from which to read frame header
[out] s frame information
log_level_offset log level offset, can be used to silence error messages.
Returns
non-zero on error, 0 if OK
Definition at line 128 of file tak.c.
Referenced by tak_decode_frame(), and tak_parse().
Variable Documentation
tak_channel_layouts
const int64_t tak_channel_layouts[] static
Initial value:
= {
    0,
    AV_CH_FRONT_LEFT,
    AV_CH_FRONT_RIGHT,
    AV_CH_FRONT_CENTER,
    AV_CH_LOW_FREQUENCY,
    AV_CH_BACK_LEFT,
    AV_CH_BACK_RIGHT,
    AV_CH_FRONT_LEFT_OF_CENTER,
    AV_CH_FRONT_RIGHT_OF_CENTER,
    AV_CH_BACK_CENTER,
    AV_CH_SIDE_LEFT,
    AV_CH_SIDE_RIGHT,
    AV_CH_TOP_CENTER,
    AV_CH_TOP_FRONT_LEFT,
    AV_CH_TOP_FRONT_CENTER,
    AV_CH_TOP_FRONT_RIGHT,
    AV_CH_TOP_BACK_LEFT,
    AV_CH_TOP_BACK_CENTER,
    AV_CH_TOP_BACK_RIGHT,
}
Definition at line 28 of file tak.c.
Referenced by avpriv_tak_parse_streaminfo().
frame_duration_type_quants
const uint16_t frame_duration_type_quants[] static
Initial value:
= {
    3, 4, 6, 8, 4096, 8192, 16384, 512, 1024, 2048,
}
Definition at line 50 of file tak.c.
Referenced by tak_get_nb_samples().