FFmpeg: libavcodec/x86/takdsp_init.c File Reference
takdsp_init.c File Reference
#include "libavcodec/takdsp.h"
#include "libavutil/x86/cpu.h"
#include "config.h"
Functions
void ff_tak_decorrelate_ls_sse2 (int32_t *p1, int32_t *p2, int length)
void ff_tak_decorrelate_sr_sse2 (int32_t *p1, int32_t *p2, int length)
void ff_tak_decorrelate_sm_sse2 (int32_t *p1, int32_t *p2, int length)
void ff_tak_decorrelate_sf_sse4 (int32_t *p1, int32_t *p2, int length, int dshift, int dfactor)
av_cold void ff_takdsp_init_x86 (TAKDSPContext *c)
Function Documentation
ff_tak_decorrelate_ls_sse2()
void ff_tak_decorrelate_ls_sse2 (int32_t * p1, int32_t * p2, int length)
Referenced by ff_takdsp_init_x86().
ff_tak_decorrelate_sr_sse2()
void ff_tak_decorrelate_sr_sse2 (int32_t * p1, int32_t * p2, int length)
Referenced by ff_takdsp_init_x86().
ff_tak_decorrelate_sm_sse2()
void ff_tak_decorrelate_sm_sse2 (int32_t * p1, int32_t * p2, int length)
Referenced by ff_takdsp_init_x86().
ff_tak_decorrelate_sf_sse4()
void ff_tak_decorrelate_sf_sse4 (int32_t * p1, int32_t * p2, int length, int dshift, int dfactor)
Referenced by ff_takdsp_init_x86().
ff_takdsp_init_x86()
av_cold void ff_takdsp_init_x86 (TAKDSPContext * c)
Definition at line 30 of file takdsp_init.c.
Referenced by ff_takdsp_init().