FFmpeg: libavcodec/targa.c File Reference
targa.c File Reference
#include "libavutil/intreadwrite.h"
#include "libavutil/imgutils.h"
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
#include "targa.h"
Data Structures
struct TargaContext
Functions
static uint8_t * advance_line (uint8_t *start, uint8_t *line, int stride, int *y, int h, int interleave)
static int targa_decode_rle (AVCodecContext *avctx, TargaContext *s, uint8_t *start, int w, int h, int stride, int bpp, int interleave)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
Variables
AVCodec ff_targa_decoder
Function Documentation
advance_line()
static uint8_t* advance_line (uint8_t * start, uint8_t * line, int stride, int * y, int h, int interleave) static
Definition at line 33 of file targa.c.
Referenced by decode_frame(), and targa_decode_rle().
targa_decode_rle()
static int targa_decode_rle (AVCodecContext * avctx, TargaContext * s, uint8_t * start, int w, int h, int stride, int bpp, int interleave) static
Definition at line 50 of file targa.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 109 of file targa.c.
Variable Documentation
ff_targa_decoder
AVCodec ff_targa_decoder
Initial value:
= {
    .name           = "targa",
    .long_name      = NULL_IF_CONFIG_SMALL("Truevision Targa image"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_TARGA,
    .priv_data_size = sizeof(TargaContext),
    .decode         = decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 299 of file targa.c.