FFmpeg: libavcodec/tdsc.c File Reference
tdsc.c File Reference
TDSC decoder.
#include <stdint.h>
#include <zlib.h>
#include "libavutil/imgutils.h"
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
Data Structures
struct TDSCContext
Macros
#define BITMAPINFOHEADER_SIZE 0x28
#define TDSF_HEADER_SIZE 0x56
#define TDSB_HEADER_SIZE 0x08
#define APPLY_ALPHA(src, new, alpha) src = (src * (256 - alpha) + new * alpha) >> 8
Enumerations
enum TDSCCursorFormat { CUR_FMT_MONO = 0x01010004, CUR_FMT_BGRA = 0x20010004, CUR_FMT_RGBA = 0x20010008 }
Functions
static av_cold int tdsc_close (AVCodecContext *avctx)
static av_cold int tdsc_init (AVCodecContext *avctx)
static void tdsc_paint_cursor (AVCodecContext *avctx, uint8_t *dst, int stride)
static int tdsc_load_cursor (AVCodecContext *avctx)
static void tdsc_yuv2rgb (uint8_t *out, int Y, int U, int V)
static av_always_inline void tdsc_blit (uint8_t *dst, int dst_stride, const uint8_t *srcy, int srcy_stride, const uint8_t *srcu, const uint8_t *srcv, int srcuv_stride, int width, int height)
static int tdsc_decode_jpeg_tile (AVCodecContext *avctx, int tile_size, int x, int y, int w, int h)
static int tdsc_decode_tiles (AVCodecContext *avctx, int number_tiles)
static int tdsc_parse_tdsf (AVCodecContext *avctx, int number_tiles)
static int tdsc_parse_dtsm (AVCodecContext *avctx)
static int tdsc_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
Variables
AVCodec ff_tdsc_decoder
Detailed Description
TDSC decoder.
Fourcc: TSDC
TDSC is very simple. It codes picture by tiles, storing them in raw BGR24 format or compressing them in JPEG. Frames can be full pictures or just updates to the previous frame. Cursor is found in its own frame or at the bottom of the picture. Every frame is then packed with zlib.
Supports: BGR24
Definition in file tdsc.c.
Macro Definition Documentation
BITMAPINFOHEADER_SIZE
#define BITMAPINFOHEADER_SIZE 0x28
Definition at line 45 of file tdsc.c.
Referenced by tdsc_parse_tdsf().
TDSF_HEADER_SIZE
#define TDSF_HEADER_SIZE 0x56
Definition at line 46 of file tdsc.c.
Referenced by tdsc_decode_frame().
TDSB_HEADER_SIZE
#define TDSB_HEADER_SIZE 0x08
Definition at line 47 of file tdsc.c.
Referenced by tdsc_decode_tiles().
APPLY_ALPHA
#define APPLY_ALPHA (src, new, alpha) src = (src * (256 - alpha) + new * alpha) >> 8
Definition at line 138 of file tdsc.c.
Referenced by tdsc_paint_cursor().
Enumeration Type Documentation
TDSCCursorFormat
enum TDSCCursorFormat
Enumerator
CUR_FMT_MONO
CUR_FMT_BGRA
CUR_FMT_RGBA
Definition at line 71 of file tdsc.c.
Function Documentation
tdsc_close()
static av_cold int tdsc_close (AVCodecContext * avctx) static
Definition at line 77 of file tdsc.c.
tdsc_init()
static av_cold int tdsc_init (AVCodecContext * avctx) static
Definition at line 91 of file tdsc.c.
tdsc_paint_cursor()
static void tdsc_paint_cursor (AVCodecContext * avctx, uint8_t * dst, int stride) static
Definition at line 142 of file tdsc.c.
Referenced by tdsc_decode_frame().
tdsc_load_cursor()
static int tdsc_load_cursor (AVCodecContext * avctx) static
Definition at line 187 of file tdsc.c.
Referenced by tdsc_parse_dtsm().
tdsc_yuv2rgb()
static void tdsc_yuv2rgb (uint8_t * out, int Y, int U, int V) inline static
Definition at line 314 of file tdsc.c.
Referenced by tdsc_blit().
tdsc_blit()
static av_always_inline void tdsc_blit (uint8_t * dst, int dst_stride, const uint8_t * srcy, int srcy_stride, const uint8_t * srcu, const uint8_t * srcv, int srcuv_stride, int width, int height) static
Definition at line 322 of file tdsc.c.
Referenced by tdsc_decode_jpeg_tile().
tdsc_decode_jpeg_tile()
static int tdsc_decode_jpeg_tile (AVCodecContext * avctx, int tile_size, int x, int y, int w, int h) static
Definition at line 341 of file tdsc.c.
Referenced by tdsc_decode_tiles().
tdsc_decode_tiles()
static int tdsc_decode_tiles (AVCodecContext * avctx, int number_tiles) static
Definition at line 381 of file tdsc.c.
Referenced by tdsc_parse_tdsf().
tdsc_parse_tdsf()
static int tdsc_parse_tdsf (AVCodecContext * avctx, int number_tiles) static
Definition at line 450 of file tdsc.c.
Referenced by tdsc_decode_frame().
tdsc_parse_dtsm()
static int tdsc_parse_dtsm (AVCodecContext * avctx) static
Definition at line 493 of file tdsc.c.
Referenced by tdsc_decode_frame().
tdsc_decode_frame()
static int tdsc_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 520 of file tdsc.c.
Variable Documentation
ff_tdsc_decoder
AVCodec ff_tdsc_decoder
Initial value:
= {
    .name           = "tdsc",
    .long_name      = NULL_IF_CONFIG_SMALL("TDSC"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_TDSC,
    .init           = tdsc_init,
    .decode         = tdsc_decode_frame,
    .close          = tdsc_close,
    .priv_data_size = sizeof(TDSCContext),
    .capabilities   = AV_CODEC_CAP_DR1,
    .caps_internal  = FF_CODEC_CAP_INIT_THREADSAFE |
                      FF_CODEC_CAP_INIT_CLEANUP,
}
Definition at line 615 of file tdsc.c.