FFmpeg: libavformat/tee.c File Reference
tee.c File Reference
#include "libavutil/avutil.h"
#include "libavutil/avstring.h"
#include "libavutil/opt.h"
#include "internal.h"
#include "avformat.h"
#include "avio_internal.h"
#include "tee_common.h"
Data Structures
struct TeeSlave
struct TeeContext
Macros
#define DEFAULT_SLAVE_FAILURE_POLICY ON_SLAVE_FAILURE_ABORT
#define OFFSET(x) offsetof(TeeContext, x)
#define STEAL_OPTION(option, field)
Enumerations
enum SlaveFailurePolicy { ON_SLAVE_FAILURE_ABORT = 1, ON_SLAVE_FAILURE_IGNORE = 2 }
Functions
static int parse_slave_failure_policy_option (const char *opt, TeeSlave *tee_slave)
static int parse_slave_fifo_options (const char *use_fifo, const char *fifo_options, TeeSlave *tee_slave)
static int close_slave (TeeSlave *tee_slave)
static void close_slaves (AVFormatContext *avf)
static int open_slave (AVFormatContext *avf, char *slave, TeeSlave *tee_slave)
static void log_slave (TeeSlave *slave, void *log_ctx, int log_level)
static int tee_process_slave_failure (AVFormatContext *avf, unsigned slave_idx, int err_n)
static int tee_write_header (AVFormatContext *avf)
static int tee_write_trailer (AVFormatContext *avf)
static int tee_write_packet (AVFormatContext *avf, AVPacket *pkt)
Variables
static const char *const slave_delim = "|"
static const char *const slave_bsfs_spec_sep = "/"
static const char *const slave_select_sep = ","
static const AVOption options []
static const AVClass tee_muxer_class
AVOutputFormat ff_tee_muxer
Macro Definition Documentation
DEFAULT_SLAVE_FAILURE_POLICY
#define DEFAULT_SLAVE_FAILURE_POLICY ON_SLAVE_FAILURE_ABORT
Definition at line 36 of file tee.c.
Referenced by parse_slave_failure_policy_option().
OFFSET
#define OFFSET (x) offsetof(TeeContext, x)
Definition at line 66 of file tee.c.
STEAL_OPTION
#define STEAL_OPTION (option, field)
Value:
do {                                \
        if ((entry = av_dict_get(options, option, NULL, 0))) {          \
            field = entry->value;                                       \
            entry->value = NULL; /* prevent it from being freed */      \
            av_dict_set(&options, option, NULL, 0);                     \
        }                                                               \
    } while (0)
Referenced by open_slave().
Enumeration Type Documentation
SlaveFailurePolicy
enum SlaveFailurePolicy
Enumerator
ON_SLAVE_FAILURE_ABORT
ON_SLAVE_FAILURE_IGNORE
Definition at line 31 of file tee.c.
Function Documentation
parse_slave_failure_policy_option()
static int parse_slave_failure_policy_option (const char * opt, TeeSlave * tee_slave) inline static
Definition at line 82 of file tee.c.
Referenced by open_slave().
parse_slave_fifo_options()
static int parse_slave_fifo_options (const char * use_fifo, const char * fifo_options, TeeSlave * tee_slave) static
Definition at line 99 of file tee.c.
Referenced by open_slave().
close_slave()
static int close_slave (TeeSlave * tee_slave) static
Definition at line 122 of file tee.c.
Referenced by close_slaves(), tee_process_slave_failure(), and tee_write_trailer().
close_slaves()
static void close_slaves (AVFormatContext * avf) static
Definition at line 148 of file tee.c.
Referenced by tee_write_header().
open_slave()
static int open_slave (AVFormatContext * avf, char * slave, TeeSlave * tee_slave) static
Definition at line 159 of file tee.c.
Referenced by tee_write_header().
log_slave()
static void log_slave (TeeSlave * slave, void * log_ctx, int log_level) static
Definition at line 405 of file tee.c.
Referenced by tee_write_header().
tee_process_slave_failure()
static int tee_process_slave_failure (AVFormatContext * avf, unsigned slave_idx, int err_n) static
Definition at line 425 of file tee.c.
Referenced by tee_write_header(), tee_write_packet(), and tee_write_trailer().
tee_write_header()
static int tee_write_header (AVFormatContext * avf) static
Definition at line 447 of file tee.c.
tee_write_trailer()
static int tee_write_trailer (AVFormatContext * avf) static
Definition at line 519 of file tee.c.
tee_write_packet()
static int tee_write_packet (AVFormatContext * avf, AVPacket * pkt) static
Definition at line 536 of file tee.c.
Variable Documentation
slave_delim
const char* const slave_delim = "|" static
Definition at line 62 of file tee.c.
Referenced by tee_write_header().
slave_bsfs_spec_sep
const char* const slave_bsfs_spec_sep = "/" static
Definition at line 63 of file tee.c.
Referenced by open_slave().
slave_select_sep
const char* const slave_select_sep = "," static
Definition at line 64 of file tee.c.
Referenced by open_slave().
options
const AVOption options[] static
Initial value:
= {
        {"use_fifo", "Use fifo pseudo-muxer to separate actual muxers from encoder",
         OFFSET(use_fifo), AV_OPT_TYPE_BOOL, {.i64 = 0}, 0, 1, AV_OPT_FLAG_ENCODING_PARAM},
        {"fifo_options", "fifo pseudo-muxer options", OFFSET(fifo_options_str),
         AV_OPT_TYPE_STRING, {.str = NULL}, 0, 0, AV_OPT_FLAG_ENCODING_PARAM},
        {NULL}
}
Definition at line 67 of file tee.c.
tee_muxer_class
const AVClass tee_muxer_class static
Initial value:
= {
    .class_name = "Tee muxer",
    .item_name  = av_default_item_name,
    .option = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 75 of file tee.c.
ff_tee_muxer
AVOutputFormat ff_tee_muxer
Initial value:
= {
    .name              = "tee",
    .long_name         = NULL_IF_CONFIG_SMALL("Multiple muxer tee"),
    .priv_data_size    = sizeof(TeeContext),
    .write_header      = tee_write_header,
    .write_trailer     = tee_write_trailer,
    .write_packet      = tee_write_packet,
    .priv_class        = &tee_muxer_class,
    .flags             = AVFMT_NOFILE | AVFMT_ALLOW_FLUSH,
}
Definition at line 609 of file tee.c.