FFmpeg: libavutil/tests/float_dsp.c File Reference
float_dsp.c File Reference
#include "config.h"
#include <float.h>
#include <math.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include "compat/getopt.c"
#include "libavutil/common.h"
#include "libavutil/cpu.h"
#include "libavutil/internal.h"
#include "libavutil/lfg.h"
#include "libavutil/log.h"
#include "libavutil/random_seed.h"
#include "libavutil/float_dsp.h"
Macros
#define LEN 240
#define ARBITRARY_FMAC_SCALAR_CONST 0.005
#define ARBITRARY_FMUL_WINDOW_CONST 0.008
#define ARBITRARY_FMUL_ADD_CONST 0.005
#define ARBITRARY_SCALARPRODUCT_CONST 0.2
Functions
static void fill_float_array (AVLFG *lfg, float *a, int len)
static int compare_floats (const float *a, const float *b, int len, float max_diff)
static void fill_double_array (AVLFG *lfg, double *a, int len)
static int compare_doubles (const double *a, const double *b, int len, double max_diff)
static int test_vector_fmul (AVFloatDSPContext *fdsp, AVFloatDSPContext *cdsp, const float *v1, const float *v2)
static int test_vector_fmac_scalar (AVFloatDSPContext *fdsp, AVFloatDSPContext *cdsp, const float *v1, const float *src0, float scale)
static int test_vector_fmul_scalar (AVFloatDSPContext *fdsp, AVFloatDSPContext *cdsp, const float *v1, float scale)
static int test_vector_dmul_scalar (AVFloatDSPContext *fdsp, AVFloatDSPContext *cdsp, const double *v1, double scale)
static int test_vector_fmul_window (AVFloatDSPContext *fdsp, AVFloatDSPContext *cdsp, const float *v1, const float *v2, const float *v3)
static int test_vector_fmul_add (AVFloatDSPContext *fdsp, AVFloatDSPContext *cdsp, const float *v1, const float *v2, const float *v3)
static int test_vector_fmul_reverse (AVFloatDSPContext *fdsp, AVFloatDSPContext *cdsp, const float *v1, const float *v2)
static int test_butterflies_float (AVFloatDSPContext *fdsp, AVFloatDSPContext *cdsp, const float *v1, const float *v2)
static int test_scalarproduct_float (AVFloatDSPContext *fdsp, AVFloatDSPContext *cdsp, const float *v1, const float *v2)
int main (int argc, char **argv)
Macro Definition Documentation
LEN
#define LEN 240
Definition at line 41 of file float_dsp.c.
Referenced by main(), test_butterflies_float(), test_scalarproduct_float(), test_vector_dmul_scalar(), test_vector_fmac_scalar(), test_vector_fmul(), test_vector_fmul_add(), test_vector_fmul_reverse(), test_vector_fmul_scalar(), and test_vector_fmul_window().
ARBITRARY_FMAC_SCALAR_CONST
#define ARBITRARY_FMAC_SCALAR_CONST 0.005
Definition at line 111 of file float_dsp.c.
Referenced by test_vector_fmac_scalar().
ARBITRARY_FMUL_WINDOW_CONST
#define ARBITRARY_FMUL_WINDOW_CONST 0.008
Definition at line 163 of file float_dsp.c.
Referenced by test_vector_fmul_window().
ARBITRARY_FMUL_ADD_CONST
#define ARBITRARY_FMUL_ADD_CONST 0.005
Definition at line 180 of file float_dsp.c.
Referenced by test_vector_fmul_add().
ARBITRARY_SCALARPRODUCT_CONST
#define ARBITRARY_SCALARPRODUCT_CONST 0.2
Definition at line 237 of file float_dsp.c.
Referenced by test_scalarproduct_float().
Function Documentation
fill_float_array()
static void fill_float_array (AVLFG * lfg, float * a, int len) static
Definition at line 43 of file float_dsp.c.
Referenced by main().
compare_floats()
static int compare_floats (const float * a, const float * b, int len, float max_diff) static
Definition at line 54 of file float_dsp.c.
Referenced by test_butterflies_float(), test_scalarproduct_float(), test_vector_fmac_scalar(), test_vector_fmul(), test_vector_fmul_add(), test_vector_fmul_reverse(), test_vector_fmul_scalar(), and test_vector_fmul_window().
fill_double_array()
static void fill_double_array (AVLFG * lfg, double * a, int len) static
Definition at line 68 of file float_dsp.c.
Referenced by main().
compare_doubles()
static int compare_doubles (const double * a, const double * b, int len, double max_diff) static
Definition at line 80 of file float_dsp.c.
Referenced by test_vector_dmul_scalar().
test_vector_fmul()
static int test_vector_fmul (AVFloatDSPContext * fdsp, AVFloatDSPContext * cdsp, const float * v1, const float * v2) static
Definition at line 95 of file float_dsp.c.
Referenced by main().
test_vector_fmac_scalar()
static int test_vector_fmac_scalar (AVFloatDSPContext * fdsp, AVFloatDSPContext * cdsp, const float * v1, const float * src0, float scale) static
Definition at line 112 of file float_dsp.c.
Referenced by main().
test_vector_fmul_scalar()
static int test_vector_fmul_scalar (AVFloatDSPContext * fdsp, AVFloatDSPContext * cdsp, const float * v1, float scale) static
Definition at line 131 of file float_dsp.c.
Referenced by main().
test_vector_dmul_scalar()
static int test_vector_dmul_scalar (AVFloatDSPContext * fdsp, AVFloatDSPContext * cdsp, const double * v1, double scale) static
Definition at line 147 of file float_dsp.c.
Referenced by main().
test_vector_fmul_window()
static int test_vector_fmul_window (AVFloatDSPContext * fdsp, AVFloatDSPContext * cdsp, const float * v1, const float * v2, const float * v3) static
Definition at line 164 of file float_dsp.c.
Referenced by main().
test_vector_fmul_add()
static int test_vector_fmul_add (AVFloatDSPContext * fdsp, AVFloatDSPContext * cdsp, const float * v1, const float * v2, const float * v3) static
Definition at line 181 of file float_dsp.c.
Referenced by main().
test_vector_fmul_reverse()
static int test_vector_fmul_reverse (AVFloatDSPContext * fdsp, AVFloatDSPContext * cdsp, const float * v1, const float * v2) static
Definition at line 197 of file float_dsp.c.
Referenced by main().
test_butterflies_float()
static int test_butterflies_float (AVFloatDSPContext * fdsp, AVFloatDSPContext * cdsp, const float * v1, const float * v2) static
Definition at line 213 of file float_dsp.c.
Referenced by main().
test_scalarproduct_float()
static int test_scalarproduct_float (AVFloatDSPContext * fdsp, AVFloatDSPContext * cdsp, const float * v1, const float * v2) static
Definition at line 238 of file float_dsp.c.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 253 of file float_dsp.c.