FFmpeg: libavutil/tests/parseutils.c File Reference
parseutils.c File Reference
#include "libavutil/parseutils.c"
#include <stdint.h>
#include <stdio.h>
#include "libavutil/common.h"
#include "libavutil/log.h"
#include "libavutil/rational.h"
Macros
#define TEST
Functions
static uint32_t av_get_random_seed_deterministic (void)
static void test_av_parse_video_rate (void)
static void test_av_parse_color (void)
static void test_av_small_strptime (void)
static void test_av_parse_time (void)
static void test_av_get_known_color_name (void)
static void test_av_find_info_tag (void)
int main (void)
Variables
static uint32_t randomv = MKTAG('L','A','V','U')
Macro Definition Documentation
TEST
#define TEST
Definition at line 19 of file parseutils.c.
Function Documentation
av_get_random_seed_deterministic()
static uint32_t av_get_random_seed_deterministic (void) static
Definition at line 31 of file parseutils.c.
test_av_parse_video_rate()
static void test_av_parse_video_rate (void) static
Definition at line 36 of file parseutils.c.
Referenced by main().
test_av_parse_color()
static void test_av_parse_color (void) static
Definition at line 76 of file parseutils.c.
Referenced by main().
test_av_small_strptime()
static void test_av_small_strptime (void) static
Definition at line 130 of file parseutils.c.
Referenced by main().
test_av_parse_time()
static void test_av_parse_time (void) static
Definition at line 159 of file parseutils.c.
Referenced by main().
test_av_get_known_color_name()
static void test_av_get_known_color_name (void) static
Definition at line 209 of file parseutils.c.
Referenced by main().
test_av_find_info_tag()
static void test_av_find_info_tag (void) static
Definition at line 225 of file parseutils.c.
Referenced by main().
main()
int main (void)
Definition at line 240 of file parseutils.c.
Variable Documentation
randomv
uint32_t randomv = MKTAG('L','A','V','U') static
Definition at line 29 of file parseutils.c.
Referenced by av_get_random_seed_deterministic().