FFmpeg: libavcodec/tests/cabac.c File Reference
cabac.c File Reference
#include "libavcodec/cabac.c"
#include "libavutil/lfg.h"
#include "libavcodec/avcodec.h"
Macros
#define SIZE 10240
Functions
static void put_cabac_bit (CABACContext *c, int b)
static void renorm_cabac_encoder (CABACContext *c)
static void put_cabac (CABACContext *c, uint8_t *const state, int bit)
static void put_cabac_bypass (CABACContext *c, int bit)
static int put_cabac_terminate (CABACContext *c, int bit)
int main (void)
Macro Definition Documentation
SIZE
#define SIZE 10240
Definition at line 23 of file cabac.c.
Referenced by main().
Function Documentation
put_cabac_bit()
static void put_cabac_bit (CABACContext * c, int b) inline static
Definition at line 28 of file cabac.c.
Referenced by put_cabac_bypass(), put_cabac_terminate(), and renorm_cabac_encoder().
renorm_cabac_encoder()
static void renorm_cabac_encoder (CABACContext * c) inline static
Definition at line 35 of file cabac.c.
Referenced by put_cabac(), and put_cabac_terminate().
put_cabac()
static void put_cabac (CABACContext * c, uint8_t *const state, int bit) static
Definition at line 53 of file cabac.c.
Referenced by main().
put_cabac_bypass()
static void put_cabac_bypass (CABACContext * c, int bit) static
Parameters
bit 0 -> write zero bit, !=0 write one bit
Definition at line 71 of file cabac.c.
Referenced by main().
put_cabac_terminate()
static int put_cabac_terminate (CABACContext * c, int bit) static
Returns
the number of bytes written
Definition at line 93 of file cabac.c.
Referenced by main().
main()
int main (void)
Definition at line 114 of file cabac.c.