FFmpeg: libavcodec/texturedsp.h File Reference
texturedsp.h File Reference
Texture block (4x4) module.
#include <stddef.h>
#include <stdint.h>
Data Structures
struct TextureDSPContext
Macros
#define TEXTURE_BLOCK_W 4
#define TEXTURE_BLOCK_H 4
Functions
void ff_texturedsp_init (TextureDSPContext *c)
void ff_texturedspenc_init (TextureDSPContext *c)
Detailed Description
Texture block (4x4) module.
References: https://www.opengl.org/wiki/S3_Texture_Compression https://www.opengl.org/wiki/Red_Green_Texture_Compression https://msdn.microsoft.com/en-us/library/bb694531%28v=vs.85%29.aspx
All functions return how much data has been written or read.
Pixel input or output format is always AV_PIX_FMT_RGBA.
Definition in file texturedsp.h.
Macro Definition Documentation
TEXTURE_BLOCK_W
#define TEXTURE_BLOCK_W 4
Definition at line 42 of file texturedsp.h.
Referenced by dds_decode(), decompress_texture_thread(), hap_decode(), and hap_init().
TEXTURE_BLOCK_H
#define TEXTURE_BLOCK_H 4
Definition at line 43 of file texturedsp.h.
Referenced by dds_decode(), decompress_texture_thread(), dxv_init(), hap_decode(), and hap_init().
Function Documentation
ff_texturedsp_init()
void ff_texturedsp_init (TextureDSPContext * c)
Definition at line 599 of file texturedsp.c.
Referenced by dds_decode(), dxv_init(), hap_init(), and txd_decode_frame().
ff_texturedspenc_init()
void ff_texturedspenc_init (TextureDSPContext * c)
Definition at line 650 of file texturedspenc.c.
Referenced by hap_init().