FFmpeg: libavcodec/texturedsp.c File Reference
texturedsp.c File Reference
#include <stddef.h>
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/common.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/libm.h"
#include "texturedsp.h"
Macros
#define RGBA(r, g, b, a)
Functions
static av_always_inline void extract_color (uint32_t colors[4], uint16_t color0, uint16_t color1, int dxtn, int alpha)
static void dxt1_block_internal (uint8_t *dst, ptrdiff_t stride, const uint8_t *block, uint8_t alpha)
static int dxt1_block (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Decompress one block of a DXT1 texture and store the resulting RGBA pixels in 'dst'.
static int dxt1a_block (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Decompress one block of a DXT1 with 1-bit alpha texture and store the resulting RGBA pixels in 'dst'.
static void dxt3_block_internal (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
static av_always_inline void premult2straight (uint8_t *src)
Convert a premultiplied alpha pixel to a straight alpha pixel.
static int dxt2_block (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Decompress one block of a DXT2 texture and store the resulting RGBA pixels in 'dst'.
static int dxt3_block (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Decompress one block of a DXT3 texture and store the resulting RGBA pixels in 'dst'.
static void decompress_indices (uint8_t *dst, const uint8_t *src)
Decompress a BC 16x3 index block stored as h g f e d c b a p o n m l k j i.
static void dxt5_block_internal (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
static int dxt4_block (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Decompress one block of a DXT4 texture and store the resulting RGBA pixels in 'dst'.
static int dxt5_block (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Decompress one block of a DXT5 texture and store the resulting RGBA pixels in 'dst'.
static av_always_inline void ycocg2rgba (uint8_t *src, int scaled)
Convert a YCoCg buffer to RGBA.
static int dxt5y_block (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Decompress one block of a DXT5 texture with classic YCoCg and store the resulting RGBA pixels in 'dst'.
static int dxt5ys_block (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Decompress one block of a DXT5 texture with scaled YCoCg and store the resulting RGBA pixels in 'dst'.
static void rgtc_block_internal (uint8_t *dst, ptrdiff_t stride, const uint8_t *block, const int *color_tab)
static void rgtc1_block_internal (uint8_t *dst, ptrdiff_t stride, const uint8_t *block, int sign)
static int rgtc1s_block (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Decompress one block of a RGRC1 texture with signed components and store the resulting RGBA pixels in 'dst'.
static int rgtc1u_block (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Decompress one block of a RGRC1 texture with unsigned components and store the resulting RGBA pixels in 'dst'.
static void rgtc2_block_internal (uint8_t *dst, ptrdiff_t stride, const uint8_t *block, int sign)
static int rgtc2s_block (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Decompress one block of a RGRC2 texture with signed components and store the resulting RGBA pixels in 'dst'.
static int rgtc2u_block (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Decompress one block of a RGRC2 texture with unsigned components and store the resulting RGBA pixels in 'dst'.
static int dxn3dc_block (uint8_t *dst, ptrdiff_t stride, const uint8_t *block)
Decompress one block of a 3Dc texture with unsigned components and store the resulting RGBA pixels in 'dst'.
av_cold void ff_texturedsp_init (TextureDSPContext *c)
Macro Definition Documentation
RGBA
#define RGBA (r, g, b, a)
Value:
(((uint8_t)(r) <<  0) | \
                          ((uint8_t)(g) <<  8) | \
                          ((uint8_t)(b) << 16) | \
                          ((uint8_t)(a) << 24))
Definition at line 35 of file texturedsp.c.
Referenced by extract_color(), and rgtc_block_internal().
Function Documentation
extract_color()
static av_always_inline void extract_color (uint32_t colors[4], uint16_t color0, uint16_t color1, int dxtn, int alpha) static
Definition at line 40 of file texturedsp.c.
Referenced by dxt1_block_internal(), dxt3_block_internal(), and dxt5_block_internal().
dxt1_block_internal()
static void dxt1_block_internal (uint8_t * dst, ptrdiff_t stride, const uint8_t * block, uint8_t alpha) inline static
Definition at line 85 of file texturedsp.c.
Referenced by dxt1_block(), and dxt1a_block().
dxt1_block()
static int dxt1_block (uint8_t * dst, ptrdiff_t stride, const uint8_t * block) static
Decompress one block of a DXT1 texture and store the resulting RGBA pixels in 'dst'.
Alpha component is fully opaque.
Parameters
dst output buffer.
stride scanline in bytes.
block block to decompress.
Returns
how much texture data has been consumed.
Definition at line 115 of file texturedsp.c.
Referenced by ff_texturedsp_init().
dxt1a_block()
static int dxt1a_block (uint8_t * dst, ptrdiff_t stride, const uint8_t * block) static
Decompress one block of a DXT1 with 1-bit alpha texture and store the resulting RGBA pixels in 'dst'.
Alpha is either fully opaque or fully transparent.
Parameters
dst output buffer.
stride scanline in bytes.
block block to decompress.
Returns
how much texture data has been consumed.
Definition at line 132 of file texturedsp.c.
Referenced by ff_texturedsp_init().
dxt3_block_internal()
static void dxt3_block_internal (uint8_t * dst, ptrdiff_t stride, const uint8_t * block) inline static
Definition at line 139 of file texturedsp.c.
Referenced by dxt2_block(), and dxt3_block().
premult2straight()
static av_always_inline void premult2straight (uint8_t * src) static
Convert a premultiplied alpha pixel to a straight alpha pixel.
Definition at line 171 of file texturedsp.c.
Referenced by dxt2_block(), and dxt4_block().
dxt2_block()
static int dxt2_block (uint8_t * dst, ptrdiff_t stride, const uint8_t * block) static
Decompress one block of a DXT2 texture and store the resulting RGBA pixels in 'dst'.
Parameters
dst output buffer.
stride scanline in bytes.
block block to decompress.
Returns
how much texture data has been consumed.
Definition at line 192 of file texturedsp.c.
Referenced by ff_texturedsp_init().
dxt3_block()
static int dxt3_block (uint8_t * dst, ptrdiff_t stride, const uint8_t * block) static
Decompress one block of a DXT3 texture and store the resulting RGBA pixels in 'dst'.
Parameters
dst output buffer.
stride scanline in bytes.
block block to decompress.
Returns
how much texture data has been consumed.
Definition at line 216 of file texturedsp.c.
Referenced by ff_texturedsp_init().
decompress_indices()
static void decompress_indices (uint8_t * dst, const uint8_t * src) static
Decompress a BC 16x3 index block stored as h g f e d c b a p o n m l k j i.
Bits packed as | h | g | f | e | d | c | b | a | // Entry |765 432 107 654 321 076 543 210| // Bit |0000000000111111111112222222222| // Byte
into 16 8-bit indices.
Definition at line 237 of file texturedsp.c.
Referenced by dxt5_block_internal(), and rgtc_block_internal().
dxt5_block_internal()
static void dxt5_block_internal (uint8_t * dst, ptrdiff_t stride, const uint8_t * block) inline static
Definition at line 253 of file texturedsp.c.
Referenced by dxt4_block(), dxt5_block(), dxt5y_block(), and dxt5ys_block().
dxt4_block()
static int dxt4_block (uint8_t * dst, ptrdiff_t stride, const uint8_t * block) static
Decompress one block of a DXT4 texture and store the resulting RGBA pixels in 'dst'.
Parameters
dst output buffer.
stride scanline in bytes.
block block to decompress.
Returns
how much texture data has been consumed.
Definition at line 311 of file texturedsp.c.
Referenced by ff_texturedsp_init().
dxt5_block()
static int dxt5_block (uint8_t * dst, ptrdiff_t stride, const uint8_t * block) static
Decompress one block of a DXT5 texture and store the resulting RGBA pixels in 'dst'.
Parameters
dst output buffer.
stride scanline in bytes.
block block to decompress.
Returns
how much texture data has been consumed.
Definition at line 335 of file texturedsp.c.
Referenced by ff_texturedsp_init().
ycocg2rgba()
static av_always_inline void ycocg2rgba (uint8_t * src, int scaled) static
Convert a YCoCg buffer to RGBA.
Parameters
src input buffer.
scaled variant with scaled chroma components and opaque alpha.
Definition at line 348 of file texturedsp.c.
Referenced by dxt5y_block(), and dxt5ys_block().
dxt5y_block()
static int dxt5y_block (uint8_t * dst, ptrdiff_t stride, const uint8_t * block) static
Decompress one block of a DXT5 texture with classic YCoCg and store the resulting RGBA pixels in 'dst'.
Alpha component is fully opaque.
Parameters
dst output buffer.
stride scanline in bytes.
block block to decompress.
Returns
how much texture data has been consumed.
Definition at line 375 of file texturedsp.c.
Referenced by ff_texturedsp_init().
dxt5ys_block()
static int dxt5ys_block (uint8_t * dst, ptrdiff_t stride, const uint8_t * block) static
Decompress one block of a DXT5 texture with scaled YCoCg and store the resulting RGBA pixels in 'dst'.
Alpha component is fully opaque.
Parameters
dst output buffer.
stride scanline in bytes.
block block to decompress.
Returns
how much texture data has been consumed.
Definition at line 399 of file texturedsp.c.
Referenced by ff_texturedsp_init().
rgtc_block_internal()
static void rgtc_block_internal (uint8_t * dst, ptrdiff_t stride, const uint8_t * block, const int * color_tab) inline static
Definition at line 414 of file texturedsp.c.
Referenced by rgtc1_block_internal().
rgtc1_block_internal()
static void rgtc1_block_internal (uint8_t * dst, ptrdiff_t stride, const uint8_t * block, int sign) inline static
Definition at line 438 of file texturedsp.c.
Referenced by rgtc1s_block(), rgtc1u_block(), and rgtc2_block_internal().
rgtc1s_block()
static int rgtc1s_block (uint8_t * dst, ptrdiff_t stride, const uint8_t * block) static
Decompress one block of a RGRC1 texture with signed components and store the resulting RGBA pixels in 'dst'.
Parameters
dst output buffer.
stride scanline in bytes.
block block to decompress.
Returns
how much texture data has been consumed.
Definition at line 487 of file texturedsp.c.
Referenced by ff_texturedsp_init().
rgtc1u_block()
static int rgtc1u_block (uint8_t * dst, ptrdiff_t stride, const uint8_t * block) static
Decompress one block of a RGRC1 texture with unsigned components and store the resulting RGBA pixels in 'dst'.
Parameters
dst output buffer.
stride scanline in bytes.
block block to decompress.
Returns
how much texture data has been consumed.
Definition at line 503 of file texturedsp.c.
Referenced by ff_texturedsp_init().
rgtc2_block_internal()
static void rgtc2_block_internal (uint8_t * dst, ptrdiff_t stride, const uint8_t * block, int sign) inline static
Definition at line 510 of file texturedsp.c.
Referenced by dxn3dc_block(), rgtc2s_block(), and rgtc2u_block().
rgtc2s_block()
static int rgtc2s_block (uint8_t * dst, ptrdiff_t stride, const uint8_t * block) static
Decompress one block of a RGRC2 texture with signed components and store the resulting RGBA pixels in 'dst'.
Alpha is fully opaque.
Parameters
dst output buffer.
stride scanline in bytes.
block block to decompress.
Returns
how much texture data has been consumed.
Definition at line 551 of file texturedsp.c.
Referenced by ff_texturedsp_init().
rgtc2u_block()
static int rgtc2u_block (uint8_t * dst, ptrdiff_t stride, const uint8_t * block) static
Decompress one block of a RGRC2 texture with unsigned components and store the resulting RGBA pixels in 'dst'.
Alpha is fully opaque.
Parameters
dst output buffer.
stride scanline in bytes.
block block to decompress.
Returns
how much texture data has been consumed.
Definition at line 567 of file texturedsp.c.
Referenced by ff_texturedsp_init().
dxn3dc_block()
static int dxn3dc_block (uint8_t * dst, ptrdiff_t stride, const uint8_t * block) static
Decompress one block of a 3Dc texture with unsigned components and store the resulting RGBA pixels in 'dst'.
Alpha is fully opaque.
Parameters
dst output buffer.
stride scanline in bytes.
block block to decompress.
Returns
how much texture data has been consumed.
Definition at line 583 of file texturedsp.c.
Referenced by ff_texturedsp_init().
ff_texturedsp_init()
av_cold void ff_texturedsp_init (TextureDSPContext * c)
Definition at line 599 of file texturedsp.c.
Referenced by dds_decode(), dxv_init(), hap_init(), and txd_decode_frame().