FFmpeg: libavcodec/tiertexseqv.c File Reference
tiertexseqv.c File Reference
Tiertex Limited SEQ video decoder.
#include "avcodec.h"
#include "get_bits.h"
#include "internal.h"
Data Structures
struct SeqVideoContext
Macros
#define BITSTREAM_READER_LE
Functions
static const unsigned char * seq_unpack_rle_block (const unsigned char *src, const unsigned char *src_end, unsigned char *dst, int dst_size)
static const unsigned char * seq_decode_op1 (SeqVideoContext *seq, const unsigned char *src, const unsigned char *src_end, unsigned char *dst)
static const unsigned char * seq_decode_op2 (SeqVideoContext *seq, const unsigned char *src, const unsigned char *src_end, unsigned char *dst)
static const unsigned char * seq_decode_op3 (SeqVideoContext *seq, const unsigned char *src, const unsigned char *src_end, unsigned char *dst)
static int seqvideo_decode (SeqVideoContext *seq, const unsigned char *data, int data_size)
static av_cold int seqvideo_decode_init (AVCodecContext *avctx)
static int seqvideo_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int seqvideo_decode_end (AVCodecContext *avctx)
Variables
AVCodec ff_tiertexseqvideo_decoder
Detailed Description
Tiertex Limited SEQ video decoder.
Definition in file tiertexseqv.c.
Macro Definition Documentation
BITSTREAM_READER_LE
#define BITSTREAM_READER_LE
Definition at line 27 of file tiertexseqv.c.
Function Documentation
seq_unpack_rle_block()
static const unsigned char* seq_unpack_rle_block (const unsigned char * src, const unsigned char * src_end, unsigned char * dst, int dst_size) static
Definition at line 39 of file tiertexseqv.c.
Referenced by seq_decode_op1().
seq_decode_op1()
static const unsigned char* seq_decode_op1 (SeqVideoContext * seq, const unsigned char * src, const unsigned char * src_end, unsigned char * dst) static
Definition at line 77 of file tiertexseqv.c.
Referenced by seqvideo_decode().
seq_decode_op2()
static const unsigned char* seq_decode_op2 (SeqVideoContext * seq, const unsigned char * src, const unsigned char * src_end, unsigned char * dst) static
Definition at line 127 of file tiertexseqv.c.
Referenced by seqvideo_decode().
seq_decode_op3()
static const unsigned char* seq_decode_op3 (SeqVideoContext * seq, const unsigned char * src, const unsigned char * src_end, unsigned char * dst) static
Definition at line 146 of file tiertexseqv.c.
Referenced by seqvideo_decode().
seqvideo_decode()
static int seqvideo_decode (SeqVideoContext * seq, const unsigned char * data, int data_size) static
Definition at line 164 of file tiertexseqv.c.
Referenced by seqvideo_decode_frame().
seqvideo_decode_init()
static av_cold int seqvideo_decode_init (AVCodecContext * avctx) static
Definition at line 213 of file tiertexseqv.c.
seqvideo_decode_frame()
static int seqvideo_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 227 of file tiertexseqv.c.
seqvideo_decode_end()
static av_cold int seqvideo_decode_end (AVCodecContext * avctx) static
Definition at line 250 of file tiertexseqv.c.
Variable Documentation
ff_tiertexseqvideo_decoder
AVCodec ff_tiertexseqvideo_decoder
Initial value:
= {
    .name           = "tiertexseqvideo",
    .long_name      = NULL_IF_CONFIG_SMALL("Tiertex Limited SEQ video"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_TIERTEXSEQVIDEO,
    .priv_data_size = sizeof(SeqVideoContext),
    .init           = seqvideo_decode_init,
    .close          = seqvideo_decode_end,
    .decode         = seqvideo_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 259 of file tiertexseqv.c.