FFmpeg: libavcodec/tiffenc.c File Reference
tiffenc.c File Reference
TIFF image encoder.
#include "config.h"
#include "libavutil/imgutils.h"
#include "libavutil/log.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
#include "lzw.h"
#include "put_bits.h"
#include "rle.h"
#include "tiff.h"
Data Structures
struct TiffEncoderContext
Macros
#define TIFF_MAX_ENTRY 32
#define ADD_ENTRY(s, tag, type, count, ptr_val)
#define ADD_ENTRY1(s, tag, type, val)
#define OFFSET(x) offsetof(TiffEncoderContext, x)
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Functions
static int check_size (TiffEncoderContext *s, uint64_t need)
Check free space in buffer.
static void tnput (uint8_t **p, int n, const uint8_t *val, enum TiffTypes type, int flip)
Put n values to buffer.
static int add_entry (TiffEncoderContext *s, enum TiffTags tag, enum TiffTypes type, int count, const void *ptr_val)
Add entry to directory in tiff header.
static int add_entry1 (TiffEncoderContext *s, enum TiffTags tag, enum TiffTypes type, int val)
static int encode_strip (TiffEncoderContext *s, const int8_t *src, uint8_t *dst, int n, int compr)
Encode one strip in tiff file.
static void pack_yuv (TiffEncoderContext *s, const AVFrame *p, uint8_t *dst, int lnum)
static int encode_frame (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *pict, int *got_packet)
static av_cold int encode_init (AVCodecContext *avctx)
static av_cold int encode_close (AVCodecContext *avctx)
Variables
static const uint8_t type_sizes2 [14]
sizes of various TIFF field types (string size = 1)
static const AVOption options []
static const AVClass tiffenc_class
AVCodec ff_tiff_encoder
Detailed Description
TIFF image encoder.
Author
Bartlomiej Wolowiec
Definition in file tiffenc.c.
Macro Definition Documentation
TIFF_MAX_ENTRY
#define TIFF_MAX_ENTRY 32
Definition at line 45 of file tiffenc.c.
Referenced by add_entry().
ADD_ENTRY
#define ADD_ENTRY (s, tag, type, count, ptr_val)
Value:
do {                                                \
        ret = add_entry(s, tag, type, count, ptr_val);  \
        if (ret < 0)                                    \
            goto fail;                                  \
    } while (0)
Definition at line 231 of file tiffenc.c.
Referenced by encode_frame().
ADD_ENTRY1
#define ADD_ENTRY1 (s, tag, type, val)
Value:
do {                                        \
        ret = add_entry1(s, tag, type, val);    \
        if (ret < 0)                            \
            goto fail;                          \
    } while (0)
Definition at line 238 of file tiffenc.c.
Referenced by encode_frame().
OFFSET
#define OFFSET (x) offsetof(TiffEncoderContext, x)
Definition at line 558 of file tiffenc.c.
VE
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 559 of file tiffenc.c.
Function Documentation
check_size()
static int check_size (TiffEncoderContext * s, uint64_t need) inline static
Check free space in buffer.
Parameters
s Tiff context
need Needed bytes
Returns
0 - ok, 1 - no free space
Definition at line 87 of file tiffenc.c.
Referenced by add_entry(), encode_frame(), and encode_strip().
tnput()
static void tnput (uint8_t ** p, int n, const uint8_t * val, enum TiffTypes type, int flip) static
Put n values to buffer.
Parameters
p pointer to pointer to output buffer
n number of values
val pointer to values
type type of values
flip = 0 - normal copy, >0 - flip
Definition at line 106 of file tiffenc.c.
Referenced by add_entry().
add_entry()
static int add_entry (TiffEncoderContext * s, enum TiffTags tag, enum TiffTypes type, int count, const void * ptr_val) static
Add entry to directory in tiff header.
Parameters
s Tiff context
tag tag that identifies the entry
type entry type
count the number of values
ptr_val pointer to values
Definition at line 126 of file tiffenc.c.
Referenced by add_entry1().
add_entry1()
static int add_entry1 (TiffEncoderContext * s, enum TiffTags tag, enum TiffTypes type, int val) static
Definition at line 150 of file tiffenc.c.
encode_strip()
static int encode_strip (TiffEncoderContext * s, const int8_t * src, uint8_t * dst, int n, int compr) static
Encode one strip in tiff file.
Parameters
s Tiff context
src input buffer
dst output buffer
n size of input buffer
compr compression method
Returns
number of output bytes. If an output error is encountered, a negative value corresponding to an AVERROR error code is returned.
Definition at line 170 of file tiffenc.c.
Referenced by encode_frame().
pack_yuv()
static void pack_yuv (TiffEncoderContext * s, const AVFrame * p, uint8_t * dst, int lnum) static
Definition at line 203 of file tiffenc.c.
Referenced by encode_frame().
encode_frame()
static int encode_frame (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * pict, int * got_packet) static
according to CCIR Recommendation 601.1
Definition at line 245 of file tiffenc.c.
encode_init()
static av_cold int encode_init (AVCodecContext * avctx) static
Definition at line 524 of file tiffenc.c.
encode_close()
static av_cold int encode_close (AVCodecContext * avctx) static
Definition at line 547 of file tiffenc.c.
Variable Documentation
type_sizes2
const uint8_t type_sizes2[14] static
Initial value:
= {
    0, 1, 1, 2, 4, 8, 1, 1, 2, 4, 8, 4, 8, 4
}
sizes of various TIFF field types (string size = 1)
Definition at line 48 of file tiffenc.c.
Referenced by add_entry(), and tnput().
options
const AVOption options[] static
Initial value:
= {
    {"dpi", "set the image resolution (in dpi)", OFFSET(dpi), AV_OPT_TYPE_INT, {.i64 = 72}, 1, 0x10000, AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_ENCODING_PARAM},
    { "compression_algo", NULL, OFFSET(compr), AV_OPT_TYPE_INT,   { .i64 = TIFF_PACKBITS }, TIFF_RAW, TIFF_DEFLATE, VE, "compression_algo" },
    { "packbits",         NULL, 0,             AV_OPT_TYPE_CONST, { .i64 = TIFF_PACKBITS }, 0,        0,            VE, "compression_algo" },
    { "raw",              NULL, 0,             AV_OPT_TYPE_CONST, { .i64 = TIFF_RAW      }, 0,        0,            VE, "compression_algo" },
    { "lzw",              NULL, 0,             AV_OPT_TYPE_CONST, { .i64 = TIFF_LZW      }, 0,        0,            VE, "compression_algo" },
    { "deflate",          NULL, 0,             AV_OPT_TYPE_CONST, { .i64 = TIFF_DEFLATE  }, 0,        0,            VE, "compression_algo" },
    { NULL },
}
Definition at line 560 of file tiffenc.c.
tiffenc_class
const AVClass tiffenc_class static
Initial value:
= {
    .class_name = "TIFF encoder",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 570 of file tiffenc.c.
ff_tiff_encoder
AVCodec ff_tiff_encoder
Initial value:
= {
    .name           = "tiff",
    .long_name      = NULL_IF_CONFIG_SMALL("TIFF image"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_TIFF,
    .priv_data_size = sizeof(TiffEncoderContext),
    .init           = encode_init,
    .close          = encode_close,
    .capabilities   = AV_CODEC_CAP_FRAME_THREADS | AV_CODEC_CAP_INTRA_ONLY,
    .encode2        = encode_frame,
    .pix_fmts       = (const enum AVPixelFormat[]) {
        AV_PIX_FMT_RGB24, AV_PIX_FMT_RGB48LE, AV_PIX_FMT_PAL8,
        AV_PIX_FMT_RGBA, AV_PIX_FMT_RGBA64LE,
        AV_PIX_FMT_GRAY8, AV_PIX_FMT_GRAY8A, AV_PIX_FMT_GRAY16LE, AV_PIX_FMT_YA16LE,
        AV_PIX_FMT_MONOBLACK, AV_PIX_FMT_MONOWHITE,
        AV_PIX_FMT_YUV420P, AV_PIX_FMT_YUV422P, AV_PIX_FMT_YUV440P, AV_PIX_FMT_YUV444P,
        AV_PIX_FMT_YUV410P, AV_PIX_FMT_YUV411P,
        AV_PIX_FMT_NONE
    },
    .priv_class     = &tiffenc_class,
}
Definition at line 577 of file tiffenc.c.