FFmpeg: libavcodec/tiff.c File Reference
tiff.c File Reference
TIFF image decoder.
#include "config.h"
#include "libavutil/attributes.h"
#include "libavutil/avstring.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/imgutils.h"
#include "avcodec.h"
#include "bytestream.h"
#include "faxcompr.h"
#include "internal.h"
#include "lzw.h"
#include "mathops.h"
#include "tiff.h"
#include "tiff_data.h"
#include "thread.h"
Data Structures
struct TiffContext
Macros
#define RET_GEOKEY(TYPE, array, element)
#define RET_GEOKEY_VAL(TYPE, array)
#define ADD_METADATA(count, name, sep)
Functions
static void free_geotags (TiffContext *const s)
static const char * get_geokey_name (int key)
static int get_geokey_type (int key)
static int cmp_id_key (const void *id, const void *k)
static const char * search_keyval (const TiffGeoTagKeyName *keys, int n, int id)
static char * get_geokey_val (int key, int val)
static char * doubles2str (double *dp, int count, const char *sep)
static int add_metadata (int count, int type, const char *name, const char *sep, TiffContext *s, AVFrame *frame)
static void av_always_inline horizontal_fill (unsigned int bpp, uint8_t *dst, int usePtr, const uint8_t *src, uint8_t c, int width, int offset)
static int deinvert_buffer (TiffContext *s, const uint8_t *src, int size)
static void unpack_yuv (TiffContext *s, AVFrame *p, const uint8_t *src, int lnum)
static int tiff_unpack_fax (TiffContext *s, uint8_t *dst, int stride, const uint8_t *src, int size, int width, int lines)
static int tiff_unpack_strip (TiffContext *s, AVFrame *p, uint8_t *dst, int stride, const uint8_t *src, int size, int strip_start, int lines)
static int init_image (TiffContext *s, ThreadFrame *frame)
static void set_sar (TiffContext *s, unsigned tag, unsigned num, unsigned den)
static int tiff_decode_tag (TiffContext *s, AVFrame *frame)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int tiff_init (AVCodecContext *avctx)
static av_cold int tiff_end (AVCodecContext *avctx)
Variables
AVCodec ff_tiff_decoder
Detailed Description
TIFF image decoder.
Author
Konstantin Shishkov
Definition in file tiff.c.
Macro Definition Documentation
RET_GEOKEY
#define RET_GEOKEY (TYPE, array, element)
Value:
if (key >= TIFF_##TYPE##_KEY_ID_OFFSET &&\
        key - TIFF_##TYPE##_KEY_ID_OFFSET < FF_ARRAY_ELEMS(ff_tiff_##array##_name_type_map))\
        return ff_tiff_##array##_name_type_map[key - TIFF_##TYPE##_KEY_ID_OFFSET].element;
Definition at line 93 of file tiff.c.
Referenced by get_geokey_name(), and get_geokey_type().
RET_GEOKEY_VAL
#define RET_GEOKEY_VAL (TYPE, array)
Value:
if (val >= TIFF_##TYPE##_OFFSET &&\
        val - TIFF_##TYPE##_OFFSET < FF_ARRAY_ELEMS(ff_tiff_##array##_codes))\
        return av_strdup(ff_tiff_##array##_codes[val - TIFF_##TYPE##_OFFSET]);
Referenced by get_geokey_val().
ADD_METADATA
#define ADD_METADATA (count, name, sep)
Value:
if ((ret = add_metadata(count, type, name, sep, s, frame)) < 0) {\
        av_log(s->avctx, AV_LOG_ERROR, "Error allocating temporary buffer\n");\
        goto end;\
    }
Referenced by tiff_decode_tag().
Function Documentation
free_geotags()
static void free_geotags (TiffContext *const s) static
Definition at line 82 of file tiff.c.
Referenced by decode_frame(), and tiff_end().
get_geokey_name()
static const char* get_geokey_name (int key) static
Definition at line 98 of file tiff.c.
Referenced by decode_frame().
get_geokey_type()
static int get_geokey_type (int key) static
Definition at line 108 of file tiff.c.
Referenced by decode_frame().
cmp_id_key()
static int cmp_id_key (const void * id, const void * k) static
Definition at line 118 of file tiff.c.
Referenced by search_keyval().
search_keyval()
static const char* search_keyval (const TiffGeoTagKeyName * keys, int n, int id) static
Definition at line 123 of file tiff.c.
Referenced by get_geokey_val().
get_geokey_val()
static char* get_geokey_val (int key, int val) static
Definition at line 132 of file tiff.c.
Referenced by tiff_decode_tag().
doubles2str()
static char* doubles2str (double * dp, int count, const char * sep) static
Definition at line 200 of file tiff.c.
Referenced by tiff_decode_tag().
add_metadata()
static int add_metadata (int count, int type, const char * name, const char * sep, TiffContext * s, AVFrame * frame) static
Definition at line 226 of file tiff.c.
horizontal_fill()
static void av_always_inline horizontal_fill (unsigned int bpp, uint8_t * dst, int usePtr, const uint8_t * src, uint8_t c, int width, int offset) static
Definition at line 237 of file tiff.c.
Referenced by tiff_unpack_fax(), tiff_unpack_strip(), and unpack_yuv().
deinvert_buffer()
static int deinvert_buffer (TiffContext * s, const uint8_t * src, int size) static
Definition at line 277 of file tiff.c.
Referenced by tiff_unpack_strip(), and unpack_yuv().
unpack_yuv()
static void unpack_yuv (TiffContext * s, AVFrame * p, const uint8_t * src, int lnum) static
Definition at line 290 of file tiff.c.
Referenced by tiff_unpack_strip().
tiff_unpack_fax()
static int tiff_unpack_fax (TiffContext * s, uint8_t * dst, int stride, const uint8_t * src, int size, int width, int lines) static
Definition at line 450 of file tiff.c.
Referenced by tiff_unpack_strip().
tiff_unpack_strip()
static int tiff_unpack_strip (TiffContext * s, AVFrame * p, uint8_t * dst, int stride, const uint8_t * src, int size, int strip_start, int lines) static
Definition at line 482 of file tiff.c.
Referenced by decode_frame().
init_image()
static int init_image (TiffContext * s, ThreadFrame * frame) static
Definition at line 652 of file tiff.c.
Referenced by decode_frame().
set_sar()
static void set_sar (TiffContext * s, unsigned tag, unsigned num, unsigned den) static
Definition at line 770 of file tiff.c.
Referenced by tiff_decode_tag().
tiff_decode_tag()
static int tiff_decode_tag (TiffContext * s, AVFrame * frame) static
Definition at line 789 of file tiff.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 1184 of file tiff.c.
tiff_init()
static av_cold int tiff_init (AVCodecContext * avctx) static
Definition at line 1366 of file tiff.c.
tiff_end()
static av_cold int tiff_end (AVCodecContext * avctx) static
Definition at line 1381 of file tiff.c.
Variable Documentation
ff_tiff_decoder
AVCodec ff_tiff_decoder
Initial value:
= {
    .name           = "tiff",
    .long_name      = NULL_IF_CONFIG_SMALL("TIFF image"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_TIFF,
    .priv_data_size = sizeof(TiffContext),
    .init           = tiff_init,
    .close          = tiff_end,
    .decode         = decode_frame,
    .init_thread_copy = ONLY_IF_THREADS_ENABLED(tiff_init),
    .capabilities   = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_FRAME_THREADS,
}
Definition at line 1392 of file tiff.c.