FFmpeg: libavutil/time.h File Reference
time.h File Reference
#include <stdint.h>
Functions
int64_t av_gettime (void)
Get the current time in microseconds.
int64_t av_gettime_relative (void)
Get the current time in microseconds since some unspecified starting point.
int av_gettime_relative_is_monotonic (void)
Indicates with a boolean result if the av_gettime_relative() time source is monotonic.
int av_usleep (unsigned usec)
Sleep for a period of time.
Function Documentation
av_gettime()
int64_t av_gettime (void)
Get the current time in microseconds.
Definition at line 39 of file time.c.
Referenced by audio_get_output_timestamp(), audio_read_packet(), av_gettime_relative(), av_parse_time(), avf_read_header(), bktr_getframe(), config_input(), convert_timestamp(), create_stream(), etime(), fbdev_read_packet(), ff_ntp_time(), ff_read_packet(), ff_rtsp_setup_output_streams(), fill_rand_int(), filter_frame(), gdigrab_read_header(), gdigrab_read_packet(), grab_read_header(), grab_read_packet(), http_server(), init_convert_timestamp(), main(), nut_write_packet(), open_input_stream(), plot_cqt(), process_callback(), pulse_get_output_timestamp(), pulse_read_packet(), qtkit_read_header(), qtkit_read_packet(), read_packet(), sap_write_header(), seg_write_packet(), udp_read(), wait_frame(), x11grab_read_header(), and x11grab_read_packet().
av_gettime_relative()
int64_t av_gettime_relative (void)
Get the current time in microseconds since some unspecified starting point.
On platforms that support it, the time comes from a monotonic clock This property makes this time source ideal for measuring relative time. The returned values may not be monotonic on platforms where a monotonic clock is not available.
Definition at line 56 of file time.c.
Referenced by audio_decode_frame(), dct_error(), enqueue_packet(), event_loop(), ff_network_wait_fd_timeout(), ff_rtp_check_and_send_back_rr(), ff_rtp_send_rtcp_feedback(), ff_rtsp_open_transport_ctx(), fifo_overflow_drop_test(), fifo_thread_attempt_recovery(), fifo_thread_process_recovery_failure(), fifo_thread_recover(), filter_frame(), get_clock(), get_input_packet(), getutime(), hls_read(), idct248_error(), main(), mmap_release_buffer(), parse_playlist(), read_data(), refresh_loop_wait_event(), retry_transfer_wrapper(), rtcp_parse_packet(), rtp_parse_one_packet(), rtsp_read_packet(), run_opencl_bench(), sap_write_packet(), sdl_audio_callback(), select_cur_seq_no(), set_clock(), stream_toggle_pause(), test_motion(), transcode(), transcode_init(), udp_get_file_handle(), video_audio_display(), video_refresh(), video_thread(), and decklink_input_callback::VideoInputFrameArrived().
av_gettime_relative_is_monotonic()
int av_gettime_relative_is_monotonic (void)
Indicates with a boolean result if the av_gettime_relative() time source is monotonic.
Definition at line 67 of file time.c.
av_usleep()
int av_usleep (unsigned usec)
Sleep for a period of time.
Although the duration is expressed in microseconds, the actual delay may be rounded to the precision of the system timer.
Parameters
usec Number of microseconds to sleep.
Returns
zero on success or (negative) error code.
Definition at line 76 of file time.c.
Referenced by audio_decode_frame(), check_keyboard_interaction(), encode_frame(), failing_write_packet(), ff_dxva2_common_end_frame(), fifo_thread_recover(), filter_frame(), gdigrab_read_packet(), hls_read(), http_read_stream(), main(), qsv_decode(), qsv_transfer_data_from(), qsv_transfer_data_to(), read_data(), read_packet(), refresh_loop_wait_event(), retry_transfer_wrapper(), rtmp_http_read(), transcode_step(), udp_get_file_handle(), and wait_frame().