FFmpeg: libavformat/tls.h File Reference
tls.h File Reference
#include "config.h"
#include "url.h"
#include "libavutil/opt.h"
Data Structures
struct TLSShared
Macros
#define CONFIG_TLS_PROTOCOL (CONFIG_TLS_GNUTLS_PROTOCOL | CONFIG_TLS_OPENSSL_PROTOCOL | CONFIG_TLS_SECURETRANSPORT_PROTOCOL | CONFIG_TLS_SCHANNEL_PROTOCOL)
#define TLS_OPTFL (AV_OPT_FLAG_DECODING_PARAM | AV_OPT_FLAG_ENCODING_PARAM)
#define TLS_COMMON_OPTIONS(pstruct, options_field)
Functions
int ff_tls_open_underlying (TLSShared *c, URLContext *parent, const char *uri, AVDictionary **options)
void ff_gnutls_init (void)
void ff_gnutls_deinit (void)
int ff_openssl_init (void)
void ff_openssl_deinit (void)
Macro Definition Documentation
CONFIG_TLS_PROTOCOL
#define CONFIG_TLS_PROTOCOL (CONFIG_TLS_GNUTLS_PROTOCOL | CONFIG_TLS_OPENSSL_PROTOCOL | CONFIG_TLS_SECURETRANSPORT_PROTOCOL | CONFIG_TLS_SCHANNEL_PROTOCOL)
Definition at line 29 of file tls.h.
Referenced by rtsp_probe().
TLS_OPTFL
#define TLS_OPTFL (AV_OPT_FLAG_DECODING_PARAM | AV_OPT_FLAG_ENCODING_PARAM)
Definition at line 46 of file tls.h.
TLS_COMMON_OPTIONS
#define TLS_COMMON_OPTIONS (pstruct, options_field)
Value:
{"ca_file",    "Certificate Authority database file", offsetof(pstruct, options_field . ca_file),   AV_OPT_TYPE_STRING, .flags = TLS_OPTFL }, \
    {"cafile",     "Certificate Authority database file", offsetof(pstruct, options_field . ca_file),   AV_OPT_TYPE_STRING, .flags = TLS_OPTFL }, \
    {"tls_verify", "Verify the peer certificate",         offsetof(pstruct, options_field . verify),    AV_OPT_TYPE_INT, { .i64 = 0 }, 0, 1, .flags = TLS_OPTFL }, \
    {"cert_file",  "Certificate file",                    offsetof(pstruct, options_field . cert_file), AV_OPT_TYPE_STRING, .flags = TLS_OPTFL }, \
    {"key_file",   "Private key file",                    offsetof(pstruct, options_field . key_file),  AV_OPT_TYPE_STRING, .flags = TLS_OPTFL }, \
    {"listen",     "Listen for incoming connections",     offsetof(pstruct, options_field . listen),    AV_OPT_TYPE_INT, { .i64 = 0 }, 0, 1, .flags = TLS_OPTFL }, \
    {"verifyhost", "Verify against a specific hostname",  offsetof(pstruct, options_field . host),      AV_OPT_TYPE_STRING, .flags = TLS_OPTFL }
Definition at line 47 of file tls.h.
Function Documentation
ff_tls_open_underlying()
int ff_tls_open_underlying (TLSShared * c, URLContext * parent, const char * uri, AVDictionary ** options)
Definition at line 56 of file tls.c.
Referenced by tls_open().
ff_gnutls_init()
void ff_gnutls_init (void)
Definition at line 52 of file tls_gnutls.c.
Referenced by ff_tls_init(), and tls_open().
ff_gnutls_deinit()
void ff_gnutls_deinit (void)
Definition at line 63 of file tls_gnutls.c.
Referenced by ff_tls_deinit(), and tls_close().
ff_openssl_init()
int ff_openssl_init (void)
Definition at line 150 of file tls_openssl.c.
Referenced by ff_tls_init(), and tls_open().
ff_openssl_deinit()
void ff_openssl_deinit (void)
Definition at line 180 of file tls_openssl.c.
Referenced by ff_tls_deinit(), and tls_close().