FFmpeg: libavformat/tls_gnutls.c File Reference
tls_gnutls.c File Reference
#include <errno.h>
#include <gnutls/gnutls.h>
#include <gnutls/x509.h>
#include "avformat.h"
#include "internal.h"
#include "network.h"
#include "os_support.h"
#include "url.h"
#include "tls.h"
#include "libavcodec/internal.h"
#include "libavutil/avstring.h"
#include "libavutil/opt.h"
#include "libavutil/parseutils.h"
Data Structures
struct TLSContext
Functions
void ff_gnutls_init (void)
void ff_gnutls_deinit (void)
static int print_tls_error (URLContext *h, int ret)
static int tls_close (URLContext *h)
static ssize_t gnutls_url_pull (gnutls_transport_ptr_t transport, void *buf, size_t len)
static ssize_t gnutls_url_push (gnutls_transport_ptr_t transport, const void *buf, size_t len)
static int tls_open (URLContext *h, const char *uri, int flags, AVDictionary **options)
static int tls_read (URLContext *h, uint8_t *buf, int size)
static int tls_write (URLContext *h, const uint8_t *buf, int size)
static int tls_get_file_handle (URLContext *h)
Variables
static const AVOption options []
static const AVClass tls_class
const URLProtocol ff_tls_gnutls_protocol
Function Documentation
ff_gnutls_init()
void ff_gnutls_init (void)
Definition at line 52 of file tls_gnutls.c.
Referenced by ff_tls_init(), and tls_open().
ff_gnutls_deinit()
void ff_gnutls_deinit (void)
Definition at line 63 of file tls_gnutls.c.
Referenced by ff_tls_deinit(), and tls_close().
print_tls_error()
static int print_tls_error (URLContext * h, int ret) static
Definition at line 70 of file tls_gnutls.c.
Referenced by tls_open(), tls_read(), and tls_write().
tls_close()
static int tls_close (URLContext * h) static
Definition at line 86 of file tls_gnutls.c.
Referenced by tls_open().
gnutls_url_pull()
static ssize_t gnutls_url_pull (gnutls_transport_ptr_t transport, void * buf, size_t len) static
Definition at line 101 of file tls_gnutls.c.
Referenced by tls_open().
gnutls_url_push()
static ssize_t gnutls_url_push (gnutls_transport_ptr_t transport, const void * buf, size_t len) static
Definition at line 114 of file tls_gnutls.c.
Referenced by tls_open().
tls_open()
static int tls_open (URLContext * h, const char * uri, int flags, AVDictionary ** options) static
Definition at line 127 of file tls_gnutls.c.
tls_read()
static int tls_read (URLContext * h, uint8_t * buf, int size) static
Definition at line 216 of file tls_gnutls.c.
tls_write()
static int tls_write (URLContext * h, const uint8_t * buf, int size) static
Definition at line 227 of file tls_gnutls.c.
tls_get_file_handle()
static int tls_get_file_handle (URLContext * h) static
Definition at line 238 of file tls_gnutls.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    TLS_COMMON_OPTIONS(TLSContext, tls_shared),
    { NULL }
}
Definition at line 244 of file tls_gnutls.c.
tls_class
const AVClass tls_class static
Initial value:
= {
    .class_name = "tls",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 249 of file tls_gnutls.c.
ff_tls_gnutls_protocol
const URLProtocol ff_tls_gnutls_protocol
Initial value:
= {
    .name           = "tls",
    .url_open2      = tls_open,
    .url_read       = tls_read,
    .url_write      = tls_write,
    .url_close      = tls_close,
    .url_get_file_handle = tls_get_file_handle,
    .priv_data_size = sizeof(TLSContext),
    .flags          = URL_PROTOCOL_FLAG_NETWORK,
    .priv_data_class = &tls_class,
}
Definition at line 256 of file tls_gnutls.c.