FFmpeg: libavcodec/tpeldsp.c File Reference
tpeldsp.c File Reference
thirdpel DSP functions
#include <stdint.h>
#include "libavutil/attributes.h"
#include "tpeldsp.h"
#include "pel_template.c"
Macros
#define BIT_DEPTH 8
Functions
static void put_tpel_pixels_mc00_c (uint8_t *dst, const uint8_t *src, int stride, int width, int height)
static void put_tpel_pixels_mc10_c (uint8_t *dst, const uint8_t *src, int stride, int width, int height)
static void put_tpel_pixels_mc20_c (uint8_t *dst, const uint8_t *src, int stride, int width, int height)
static void put_tpel_pixels_mc01_c (uint8_t *dst, const uint8_t *src, int stride, int width, int height)
static void put_tpel_pixels_mc11_c (uint8_t *dst, const uint8_t *src, int stride, int width, int height)
static void put_tpel_pixels_mc12_c (uint8_t *dst, const uint8_t *src, int stride, int width, int height)
static void put_tpel_pixels_mc02_c (uint8_t *dst, const uint8_t *src, int stride, int width, int height)
static void put_tpel_pixels_mc21_c (uint8_t *dst, const uint8_t *src, int stride, int width, int height)
static void put_tpel_pixels_mc22_c (uint8_t *dst, const uint8_t *src, int stride, int width, int height)
static void avg_tpel_pixels_mc00_c (uint8_t *dst, const uint8_t *src, int stride, int width, int height)
static void avg_tpel_pixels_mc10_c (uint8_t *dst, const uint8_t *src, int stride, int width, int height)
static void avg_tpel_pixels_mc20_c (uint8_t *dst, const uint8_t *src, int stride, int width, int height)
static void avg_tpel_pixels_mc01_c (uint8_t *dst, const uint8_t *src, int stride, int width, int height)
static void avg_tpel_pixels_mc11_c (uint8_t *dst, const uint8_t *src, int stride, int width, int height)
static void avg_tpel_pixels_mc12_c (uint8_t *dst, const uint8_t *src, int stride, int width, int height)
static void avg_tpel_pixels_mc02_c (uint8_t *dst, const uint8_t *src, int stride, int width, int height)
static void avg_tpel_pixels_mc21_c (uint8_t *dst, const uint8_t *src, int stride, int width, int height)
static void avg_tpel_pixels_mc22_c (uint8_t *dst, const uint8_t *src, int stride, int width, int height)
av_cold void ff_tpeldsp_init (TpelDSPContext *c)
Detailed Description
thirdpel DSP functions
Definition in file tpeldsp.c.
Macro Definition Documentation
BIT_DEPTH
#define BIT_DEPTH 8
Definition at line 31 of file tpeldsp.c.
Function Documentation
put_tpel_pixels_mc00_c()
static void put_tpel_pixels_mc00_c (uint8_t * dst, const uint8_t * src, int stride, int width, int height) inline static
Definition at line 34 of file tpeldsp.c.
Referenced by ff_tpeldsp_init().
put_tpel_pixels_mc10_c()
static void put_tpel_pixels_mc10_c (uint8_t * dst, const uint8_t * src, int stride, int width, int height) inline static
Definition at line 53 of file tpeldsp.c.
Referenced by ff_tpeldsp_init().
put_tpel_pixels_mc20_c()
static void put_tpel_pixels_mc20_c (uint8_t * dst, const uint8_t * src, int stride, int width, int height) inline static
Definition at line 67 of file tpeldsp.c.
Referenced by ff_tpeldsp_init().
put_tpel_pixels_mc01_c()
static void put_tpel_pixels_mc01_c (uint8_t * dst, const uint8_t * src, int stride, int width, int height) inline static
Definition at line 81 of file tpeldsp.c.
Referenced by ff_tpeldsp_init().
put_tpel_pixels_mc11_c()
static void put_tpel_pixels_mc11_c (uint8_t * dst, const uint8_t * src, int stride, int width, int height) inline static
Definition at line 95 of file tpeldsp.c.
Referenced by ff_tpeldsp_init().
put_tpel_pixels_mc12_c()
static void put_tpel_pixels_mc12_c (uint8_t * dst, const uint8_t * src, int stride, int width, int height) inline static
Definition at line 110 of file tpeldsp.c.
Referenced by ff_tpeldsp_init().
put_tpel_pixels_mc02_c()
static void put_tpel_pixels_mc02_c (uint8_t * dst, const uint8_t * src, int stride, int width, int height) inline static
Definition at line 125 of file tpeldsp.c.
Referenced by ff_tpeldsp_init().
put_tpel_pixels_mc21_c()
static void put_tpel_pixels_mc21_c (uint8_t * dst, const uint8_t * src, int stride, int width, int height) inline static
Definition at line 139 of file tpeldsp.c.
Referenced by ff_tpeldsp_init().
put_tpel_pixels_mc22_c()
static void put_tpel_pixels_mc22_c (uint8_t * dst, const uint8_t * src, int stride, int width, int height) inline static
Definition at line 154 of file tpeldsp.c.
Referenced by ff_tpeldsp_init().
avg_tpel_pixels_mc00_c()
static void avg_tpel_pixels_mc00_c (uint8_t * dst, const uint8_t * src, int stride, int width, int height) inline static
Definition at line 169 of file tpeldsp.c.
Referenced by ff_tpeldsp_init().
avg_tpel_pixels_mc10_c()
static void avg_tpel_pixels_mc10_c (uint8_t * dst, const uint8_t * src, int stride, int width, int height) inline static
Definition at line 188 of file tpeldsp.c.
Referenced by ff_tpeldsp_init().
avg_tpel_pixels_mc20_c()
static void avg_tpel_pixels_mc20_c (uint8_t * dst, const uint8_t * src, int stride, int width, int height) inline static
Definition at line 203 of file tpeldsp.c.
Referenced by ff_tpeldsp_init().
avg_tpel_pixels_mc01_c()
static void avg_tpel_pixels_mc01_c (uint8_t * dst, const uint8_t * src, int stride, int width, int height) inline static
Definition at line 218 of file tpeldsp.c.
Referenced by ff_tpeldsp_init().
avg_tpel_pixels_mc11_c()
static void avg_tpel_pixels_mc11_c (uint8_t * dst, const uint8_t * src, int stride, int width, int height) inline static
Definition at line 233 of file tpeldsp.c.
Referenced by ff_tpeldsp_init().
avg_tpel_pixels_mc12_c()
static void avg_tpel_pixels_mc12_c (uint8_t * dst, const uint8_t * src, int stride, int width, int height) inline static
Definition at line 249 of file tpeldsp.c.
Referenced by ff_tpeldsp_init().
avg_tpel_pixels_mc02_c()
static void avg_tpel_pixels_mc02_c (uint8_t * dst, const uint8_t * src, int stride, int width, int height) inline static
Definition at line 265 of file tpeldsp.c.
Referenced by ff_tpeldsp_init().
avg_tpel_pixels_mc21_c()
static void avg_tpel_pixels_mc21_c (uint8_t * dst, const uint8_t * src, int stride, int width, int height) inline static
Definition at line 280 of file tpeldsp.c.
Referenced by ff_tpeldsp_init().
avg_tpel_pixels_mc22_c()
static void avg_tpel_pixels_mc22_c (uint8_t * dst, const uint8_t * src, int stride, int width, int height) inline static
Definition at line 296 of file tpeldsp.c.
Referenced by ff_tpeldsp_init().
ff_tpeldsp_init()
av_cold void ff_tpeldsp_init (TpelDSPContext * c)
Definition at line 312 of file tpeldsp.c.
Referenced by svq3_decode_init().