FFmpeg: libavutil/tree.c File Reference
tree.c File Reference
#include "error.h"
#include "log.h"
#include "mem.h"
#include "tree.h"
Data Structures
struct AVTreeNode
Functions
struct AVTreeNode * av_tree_node_alloc (void)
Allocate an AVTreeNode.
void * av_tree_find (const AVTreeNode *t, void *key, int(*cmp)(const void *key, const void *b), void *next[2])
void * av_tree_insert (AVTreeNode **tp, void *key, int(*cmp)(const void *key, const void *b), AVTreeNode **next)
Insert or remove an element.
void av_tree_destroy (AVTreeNode *t)
void av_tree_enumerate (AVTreeNode *t, void *opaque, int(*cmp)(void *opaque, void *elem), int(*enu)(void *opaque, void *elem))
Apply enu(opaque, &elem) to all the elements in the tree in a given range.
Variables
const int av_tree_node_size = sizeof(AVTreeNode)
Function Documentation
av_tree_find()
void* av_tree_find (const AVTreeNode * t, void * key, int(*)(const void *key, const void *b) cmp, void * next[2])
Definition at line 39 of file tree.c.
Referenced by add_entry(), av_tree_insert(), cache_read(), draw_glyphs(), draw_text(), main(), read_seek(), and write_index().