FFmpeg: libavcodec/truespeech.c File Reference
truespeech.c File Reference
TrueSpeech decoder.
#include "libavutil/channel_layout.h"
#include "libavutil/intreadwrite.h"
#include "avcodec.h"
#include "bswapdsp.h"
#include "get_bits.h"
#include "internal.h"
#include "truespeech_data.h"
Data Structures
struct TSContext
TrueSpeech decoder context.
Functions
static av_cold int truespeech_decode_init (AVCodecContext *avctx)
static void truespeech_read_frame (TSContext *dec, const uint8_t *input)
static void truespeech_correlate_filter (TSContext *dec)
static void truespeech_filters_merge (TSContext *dec)
static void truespeech_apply_twopoint_filter (TSContext *dec, int quart)
static void truespeech_place_pulses (TSContext *dec, int16_t *out, int quart)
static void truespeech_update_filters (TSContext *dec, int16_t *out, int quart)
static void truespeech_synth (TSContext *dec, int16_t *out, int quart)
static void truespeech_save_prevvec (TSContext *c)
static int truespeech_decode_frame (AVCodecContext *avctx, void *data, int *got_frame_ptr, AVPacket *avpkt)
Variables
AVCodec ff_truespeech_decoder
Detailed Description
TrueSpeech decoder.
Definition in file truespeech.c.
Function Documentation
truespeech_decode_init()
static av_cold int truespeech_decode_init (AVCodecContext * avctx) static
Definition at line 61 of file truespeech.c.
truespeech_read_frame()
static void truespeech_read_frame (TSContext * dec, const uint8_t * input) static
Definition at line 78 of file truespeech.c.
Referenced by truespeech_decode_frame().
truespeech_correlate_filter()
static void truespeech_correlate_filter (TSContext * dec) static
Definition at line 126 of file truespeech.c.
Referenced by truespeech_decode_frame().
truespeech_filters_merge()
static void truespeech_filters_merge (TSContext * dec) static
Definition at line 146 of file truespeech.c.
Referenced by truespeech_decode_frame().
truespeech_apply_twopoint_filter()
static void truespeech_apply_twopoint_filter (TSContext * dec, int quart) static
Definition at line 167 of file truespeech.c.
Referenced by truespeech_decode_frame().
truespeech_place_pulses()
static void truespeech_place_pulses (TSContext * dec, int16_t * out, int quart) static
Definition at line 193 of file truespeech.c.
Referenced by truespeech_decode_frame().
truespeech_update_filters()
static void truespeech_update_filters (TSContext * dec, int16_t * out, int quart) static
Definition at line 236 of file truespeech.c.
Referenced by truespeech_decode_frame().
truespeech_synth()
static void truespeech_synth (TSContext * dec, int16_t * out, int quart) static
Definition at line 247 of file truespeech.c.
Referenced by truespeech_decode_frame().
truespeech_save_prevvec()
static void truespeech_save_prevvec (TSContext * c) static
Definition at line 298 of file truespeech.c.
Referenced by truespeech_decode_frame().
truespeech_decode_frame()
static int truespeech_decode_frame (AVCodecContext * avctx, void * data, int * got_frame_ptr, AVPacket * avpkt) static
Definition at line 306 of file truespeech.c.
Variable Documentation
ff_truespeech_decoder
AVCodec ff_truespeech_decoder
Initial value:
= {
    .name           = "truespeech",
    .long_name      = NULL_IF_CONFIG_SMALL("DSP Group TrueSpeech"),
    .type           = AVMEDIA_TYPE_AUDIO,
    .id             = AV_CODEC_ID_TRUESPEECH,
    .priv_data_size = sizeof(TSContext),
    .init           = truespeech_decode_init,
    .decode         = truespeech_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 357 of file truespeech.c.