FFmpeg: libavcodec/truemotion1.c File Reference
truemotion1.c File Reference
Duck TrueMotion v1 Video Decoder by Alex Beregszaszi and Mike Melanson (melan.nosp@m.son@.nosp@m.pcisy.nosp@m.s.ne.nosp@m.t)
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "avcodec.h"
#include "internal.h"
#include "libavutil/imgutils.h"
#include "libavutil/internal.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/mem.h"
#include "truemotion1data.h"
Data Structures
struct TrueMotion1Context
struct frame_header
struct comp_types
Macros
#define FLAG_SPRITE 32
#define FLAG_KEYFRAME 16
#define FLAG_INTERFRAME 8
#define FLAG_INTERPOLATED 4
#define ALGO_NOP 0
#define ALGO_RGB16V 1
#define ALGO_RGB16H 2
#define ALGO_RGB24H 3
#define BLOCK_2x2 0
#define BLOCK_2x4 1
#define BLOCK_4x2 2
#define BLOCK_4x4 3
#define GET_NEXT_INDEX()
#define INC_INDEX
#define APPLY_C_PREDICTOR()
#define APPLY_C_PREDICTOR_24()
#define APPLY_Y_PREDICTOR()
#define APPLY_Y_PREDICTOR_24()
#define OUTPUT_PIXEL_PAIR()
Functions
static void select_delta_tables (TrueMotion1Context *s, int delta_table_index)
static int make_ydt15_entry (int p1, int p2, int16_t *ydt)
static int make_cdt15_entry (int p1, int p2, int16_t *cdt)
static int make_ydt16_entry (int p1, int p2, int16_t *ydt)
static int make_cdt16_entry (int p1, int p2, int16_t *cdt)
static int make_ydt24_entry (int p1, int p2, int16_t *ydt)
static int make_cdt24_entry (int p1, int p2, int16_t *cdt)
static void gen_vector_table15 (TrueMotion1Context *s, const uint8_t *sel_vector_table)
static void gen_vector_table16 (TrueMotion1Context *s, const uint8_t *sel_vector_table)
static void gen_vector_table24 (TrueMotion1Context *s, const uint8_t *sel_vector_table)
static int truemotion1_decode_header (TrueMotion1Context *s)
static av_cold int truemotion1_decode_init (AVCodecContext *avctx)
static void truemotion1_decode_16bit (TrueMotion1Context *s)
static void truemotion1_decode_24bit (TrueMotion1Context *s)
static int truemotion1_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int truemotion1_decode_end (AVCodecContext *avctx)
Variables
static const comp_types compression_types [17]
AVCodec ff_truemotion1_decoder
Detailed Description
Duck TrueMotion v1 Video Decoder by Alex Beregszaszi and Mike Melanson (melan.nosp@m.son@.nosp@m.pcisy.nosp@m.s.ne.nosp@m.t)
The TrueMotion v1 decoder presently only decodes 16-bit TM1 data and outputs RGB555 (or RGB565) data. 24-bit TM1 data is not supported yet.
Definition in file truemotion1.c.
Macro Definition Documentation
FLAG_SPRITE
#define FLAG_SPRITE 32
Definition at line 82 of file truemotion1.c.
Referenced by truemotion1_decode_header().
FLAG_KEYFRAME
#define FLAG_KEYFRAME 16
Definition at line 83 of file truemotion1.c.
Referenced by truemotion1_decode_16bit(), truemotion1_decode_24bit(), and truemotion1_decode_header().
FLAG_INTERFRAME
#define FLAG_INTERFRAME 8
Definition at line 84 of file truemotion1.c.
Referenced by truemotion1_decode_header().
FLAG_INTERPOLATED
#define FLAG_INTERPOLATED 4
Definition at line 85 of file truemotion1.c.
Referenced by truemotion1_decode_header().
ALGO_NOP
#define ALGO_NOP 0
Definition at line 105 of file truemotion1.c.
Referenced by truemotion1_decode_frame().
ALGO_RGB16V
#define ALGO_RGB16V 1
Definition at line 106 of file truemotion1.c.
ALGO_RGB16H
#define ALGO_RGB16H 2
Definition at line 107 of file truemotion1.c.
ALGO_RGB24H
#define ALGO_RGB24H 3
Definition at line 108 of file truemotion1.c.
Referenced by truemotion1_decode_frame(), and truemotion1_decode_header().
BLOCK_2x2
#define BLOCK_2x2 0
Definition at line 111 of file truemotion1.c.
Referenced by truemotion1_decode_16bit(), and truemotion1_decode_24bit().
BLOCK_2x4
#define BLOCK_2x4 1
Definition at line 112 of file truemotion1.c.
BLOCK_4x2
#define BLOCK_4x2 2
Definition at line 113 of file truemotion1.c.
Referenced by truemotion1_decode_16bit(), and truemotion1_decode_24bit().
BLOCK_4x4
#define BLOCK_4x4 3
Definition at line 114 of file truemotion1.c.
GET_NEXT_INDEX
#define GET_NEXT_INDEX ()
Value:
{\
    if (index_stream_index >= s->index_stream_size) { \
        av_log(s->avctx, AV_LOG_INFO, " help! truemotion1 decoder went out of bounds\n"); \
        return; \
    } \
    index = s->index_stream[index_stream_index++] * 4; \
}
Definition at line 526 of file truemotion1.c.
Referenced by truemotion1_decode_16bit(), and truemotion1_decode_24bit().
INC_INDEX
#define INC_INDEX
Value:
do {                                                                \
    if (index >= 1023) {                                            \
        av_log(s->avctx, AV_LOG_ERROR, "Invalid index value.\n");   \
        return;                                                     \
    }                                                               \
    index++;                                                        \
} while (0)
Definition at line 535 of file truemotion1.c.
APPLY_C_PREDICTOR
#define APPLY_C_PREDICTOR ()
Value:
predictor_pair = s->c_predictor_table[index]; \
    horiz_pred += (predictor_pair >> 1); \
    if (predictor_pair & 1) { \
        GET_NEXT_INDEX() \
        if (!index) { \
            GET_NEXT_INDEX() \
            predictor_pair = s->c_predictor_table[index]; \
            horiz_pred += ((predictor_pair >> 1) * 5); \
            if (predictor_pair & 1) \
                GET_NEXT_INDEX() \
            else \
                INC_INDEX; \
        } \
    } else \
        INC_INDEX;
Definition at line 544 of file truemotion1.c.
Referenced by truemotion1_decode_16bit().
APPLY_C_PREDICTOR_24
#define APPLY_C_PREDICTOR_24 ()
Value:
predictor_pair = s->c_predictor_table[index]; \
    horiz_pred += (predictor_pair >> 1); \
    if (predictor_pair & 1) { \
        GET_NEXT_INDEX() \
        if (!index) { \
            GET_NEXT_INDEX() \
            predictor_pair = s->fat_c_predictor_table[index]; \
            horiz_pred += (predictor_pair >> 1); \
            if (predictor_pair & 1) \
                GET_NEXT_INDEX() \
            else \
                INC_INDEX; \
        } \
    } else \
        INC_INDEX;
Definition at line 561 of file truemotion1.c.
Referenced by truemotion1_decode_24bit().
APPLY_Y_PREDICTOR
#define APPLY_Y_PREDICTOR ()
Value:
predictor_pair = s->y_predictor_table[index]; \
    horiz_pred += (predictor_pair >> 1); \
    if (predictor_pair & 1) { \
        GET_NEXT_INDEX() \
        if (!index) { \
            GET_NEXT_INDEX() \
            predictor_pair = s->y_predictor_table[index]; \
            horiz_pred += ((predictor_pair >> 1) * 5); \
            if (predictor_pair & 1) \
                GET_NEXT_INDEX() \
            else \
                INC_INDEX; \
        } \
    } else \
        INC_INDEX;
Definition at line 579 of file truemotion1.c.
Referenced by truemotion1_decode_16bit().
APPLY_Y_PREDICTOR_24
#define APPLY_Y_PREDICTOR_24 ()
Value:
predictor_pair = s->y_predictor_table[index]; \
    horiz_pred += (predictor_pair >> 1); \
    if (predictor_pair & 1) { \
        GET_NEXT_INDEX() \
        if (!index) { \
            GET_NEXT_INDEX() \
            predictor_pair = s->fat_y_predictor_table[index]; \
            horiz_pred += (predictor_pair >> 1); \
            if (predictor_pair & 1) \
                GET_NEXT_INDEX() \
            else \
                INC_INDEX; \
        } \
    } else \
        INC_INDEX;
Definition at line 596 of file truemotion1.c.
Referenced by truemotion1_decode_24bit().
OUTPUT_PIXEL_PAIR
#define OUTPUT_PIXEL_PAIR ()
Value:
*current_pixel_pair = *vert_pred + horiz_pred; \
    *vert_pred++ = *current_pixel_pair++;
Definition at line 613 of file truemotion1.c.
Referenced by truemotion1_decode_16bit(), and truemotion1_decode_24bit().
Function Documentation
select_delta_tables()
static void select_delta_tables (TrueMotion1Context * s, int delta_table_index) static
Definition at line 148 of file truemotion1.c.
Referenced by truemotion1_decode_header().
make_ydt15_entry()
static int make_ydt15_entry (int p1, int p2, int16_t * ydt) static
Definition at line 174 of file truemotion1.c.
Referenced by gen_vector_table15(), and select_delta_tables().
make_cdt15_entry()
static int make_cdt15_entry (int p1, int p2, int16_t * cdt) static
Definition at line 186 of file truemotion1.c.
Referenced by gen_vector_table15().
make_ydt16_entry()
static int make_ydt16_entry (int p1, int p2, int16_t * ydt) static
Definition at line 199 of file truemotion1.c.
Referenced by gen_vector_table16(), and make_cdt15_entry().
make_cdt16_entry()
static int make_cdt16_entry (int p1, int p2, int16_t * cdt) static
Definition at line 211 of file truemotion1.c.
Referenced by gen_vector_table16().
make_ydt24_entry()
static int make_ydt24_entry (int p1, int p2, int16_t * ydt) static
Definition at line 221 of file truemotion1.c.
Referenced by gen_vector_table24().
make_cdt24_entry()
static int make_cdt24_entry (int p1, int p2, int16_t * cdt) static
Definition at line 230 of file truemotion1.c.
Referenced by gen_vector_table24().
gen_vector_table15()
static void gen_vector_table15 (TrueMotion1Context * s, const uint8_t * sel_vector_table) static
Definition at line 239 of file truemotion1.c.
Referenced by truemotion1_decode_header().
gen_vector_table16()
static void gen_vector_table16 (TrueMotion1Context * s, const uint8_t * sel_vector_table) static
Definition at line 260 of file truemotion1.c.
Referenced by truemotion1_decode_header().
gen_vector_table24()
static void gen_vector_table24 (TrueMotion1Context * s, const uint8_t * sel_vector_table) static
Definition at line 281 of file truemotion1.c.
Referenced by truemotion1_decode_header().
truemotion1_decode_header()
static int truemotion1_decode_header (TrueMotion1Context * s) static
Definition at line 310 of file truemotion1.c.
Referenced by truemotion1_decode_frame().
truemotion1_decode_init()
static av_cold int truemotion1_decode_init (AVCodecContext * avctx) static
Definition at line 473 of file truemotion1.c.
truemotion1_decode_16bit()
static void truemotion1_decode_16bit (TrueMotion1Context * s) static
Definition at line 617 of file truemotion1.c.
Referenced by truemotion1_decode_frame().
truemotion1_decode_24bit()
static void truemotion1_decode_24bit (TrueMotion1Context * s) static
Definition at line 744 of file truemotion1.c.
Referenced by truemotion1_decode_frame().
truemotion1_decode_frame()
static int truemotion1_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 871 of file truemotion1.c.
truemotion1_decode_end()
static av_cold int truemotion1_decode_end (AVCodecContext * avctx) static
Definition at line 903 of file truemotion1.c.
Variable Documentation
compression_types
const comp_types compression_types[17] static
Initial value:
= {
    { ALGO_NOP,    0, 0, 0 },
    { ALGO_RGB16V, 4, 4, BLOCK_4x4 },
    { ALGO_RGB16H, 4, 4, BLOCK_4x4 },
    { ALGO_RGB16V, 4, 2, BLOCK_4x2 },
    { ALGO_RGB16H, 4, 2, BLOCK_4x2 },
    { ALGO_RGB16V, 2, 4, BLOCK_2x4 },
    { ALGO_RGB16H, 2, 4, BLOCK_2x4 },
    { ALGO_RGB16V, 2, 2, BLOCK_2x2 },
    { ALGO_RGB16H, 2, 2, BLOCK_2x2 },
    { ALGO_NOP,    4, 4, BLOCK_4x4 },
    { ALGO_RGB24H, 4, 4, BLOCK_4x4 },
    { ALGO_NOP,    4, 2, BLOCK_4x2 },
    { ALGO_RGB24H, 4, 2, BLOCK_4x2 },
    { ALGO_NOP,    2, 4, BLOCK_2x4 },
    { ALGO_RGB24H, 2, 4, BLOCK_2x4 },
    { ALGO_NOP,    2, 2, BLOCK_2x2 },
    { ALGO_RGB24H, 2, 2, BLOCK_2x2 }
}
Definition at line 124 of file truemotion1.c.
ff_truemotion1_decoder
AVCodec ff_truemotion1_decoder
Initial value:
= {
    .name           = "truemotion1",
    .long_name      = NULL_IF_CONFIG_SMALL("Duck TrueMotion 1.0"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_TRUEMOTION1,
    .priv_data_size = sizeof(TrueMotion1Context),
    .init           = truemotion1_decode_init,
    .close          = truemotion1_decode_end,
    .decode         = truemotion1_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 913 of file truemotion1.c.