FFmpeg: libavcodec/tscc2.c File Reference
tscc2.c File Reference
TechSmith Screen Codec 2 decoder.
#include <inttypes.h>
#include "avcodec.h"
#include "bytestream.h"
#include "get_bits.h"
#include "internal.h"
#include "mathops.h"
#include "tscc2data.h"
Data Structures
struct TSCC2Context
Macros
#define BITSTREAM_READER_LE
#define DEQUANT(val, q) (((q) * (val) + 0x80) >> 8)
#define DCT1D(d0, d1, d2, d3, s0, s1, s2, s3, OP)
#define COL_OP(a, b) a = (b)
#define ROW_OP(a, b) a = ((b) + 0x20) >> 6
Functions
static av_cold void free_vlcs (TSCC2Context *c)
static av_cold int init_vlcs (TSCC2Context *c)
static void tscc2_idct4_put (int *in, int q[3], uint8_t *dst, int stride)
static int tscc2_decode_mb (TSCC2Context *c, int *q, int vlc_set, uint8_t *dst, int stride, int plane)
static int tscc2_decode_slice (TSCC2Context *c, int mb_y, const uint8_t *buf, int buf_size)
static int tscc2_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int tscc2_decode_end (AVCodecContext *avctx)
static av_cold int tscc2_decode_init (AVCodecContext *avctx)
Variables
AVCodec ff_tscc2_decoder
Detailed Description
TechSmith Screen Codec 2 decoder.
Definition in file tscc2.c.
Macro Definition Documentation
BITSTREAM_READER_LE
#define BITSTREAM_READER_LE
Definition at line 29 of file tscc2.c.
DEQUANT
#define DEQUANT (val, q) (((q) * (val) + 0x80) >> 8)
Definition at line 94 of file tscc2.c.
Referenced by tscc2_idct4_put().
DCT1D
#define DCT1D (d0, d1, d2, d3, s0, s1, s2, s3, OP)
Value:
OP(d0, 5 * ((s0) + (s1) + (s2)) + 2 * (s3));  \
    OP(d1, 5 * ((s0) - (s2) - (s3)) + 2 * (s1));  \
    OP(d2, 5 * ((s0) - (s2) + (s3)) - 2 * (s1));  \
    OP(d3, 5 * ((s0) - (s1) + (s2)) - 2 * (s3));  \
Definition at line 95 of file tscc2.c.
Referenced by tscc2_idct4_put().
COL_OP
#define COL_OP (a, b) a = (b)
Definition at line 101 of file tscc2.c.
Referenced by tscc2_idct4_put().
ROW_OP
#define ROW_OP (a, b) a = ((b) + 0x20) >> 6
Definition at line 102 of file tscc2.c.
Referenced by tscc2_idct4_put().
Function Documentation
free_vlcs()
static av_cold void free_vlcs (TSCC2Context * c) static
Definition at line 50 of file tscc2.c.
Referenced by init_vlcs(), tscc2_decode_end(), and tscc2_decode_init().
init_vlcs()
static av_cold int init_vlcs (TSCC2Context * c) static
Definition at line 61 of file tscc2.c.
Referenced by tscc2_decode_init().
tscc2_idct4_put()
static void tscc2_idct4_put (int * in, int q[3], uint8_t * dst, int stride) static
Definition at line 104 of file tscc2.c.
Referenced by tscc2_decode_mb().
tscc2_decode_mb()
static int tscc2_decode_mb (TSCC2Context * c, int * q, int vlc_set, uint8_t * dst, int stride, int plane) static
Definition at line 127 of file tscc2.c.
Referenced by tscc2_decode_slice().
tscc2_decode_slice()
static int tscc2_decode_slice (TSCC2Context * c, int mb_y, const uint8_t * buf, int buf_size) static
Definition at line 192 of file tscc2.c.
Referenced by tscc2_decode_frame().
tscc2_decode_frame()
static int tscc2_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 218 of file tscc2.c.
tscc2_decode_end()
static av_cold int tscc2_decode_end (AVCodecContext * avctx) static
Definition at line 336 of file tscc2.c.
Referenced by tscc2_decode_init().
tscc2_decode_init()
static av_cold int tscc2_decode_init (AVCodecContext * avctx) static
Definition at line 347 of file tscc2.c.
Variable Documentation
ff_tscc2_decoder
AVCodec ff_tscc2_decoder
Initial value:
= {
    .name           = "tscc2",
    .long_name      = NULL_IF_CONFIG_SMALL("TechSmith Screen Codec 2"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_TSCC2,
    .priv_data_size = sizeof(TSCC2Context),
    .init           = tscc2_decode_init,
    .close          = tscc2_decode_end,
    .decode         = tscc2_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 379 of file tscc2.c.