FFmpeg: libavcodec/ttadata.h File Reference
ttadata.h File Reference
#include "internal.h"
Data Structures
struct TTAFilter
struct TTARice
struct TTAChannel
Macros
#define MAX_ORDER 16
Functions
void ff_tta_rice_init (TTARice *c, uint32_t k0, uint32_t k1)
void ff_tta_filter_init (TTAFilter *c, int32_t shift)
Variables
const uint32_t ff_tta_shift_1 []
const uint32_t *const ff_tta_shift_16
const uint8_t ff_tta_filter_configs []
Macro Definition Documentation
MAX_ORDER
#define MAX_ORDER 16
Definition at line 26 of file ttadata.h.
Function Documentation
ff_tta_rice_init()
void ff_tta_rice_init (TTARice * c, uint32_t k0, uint32_t k1)
Definition at line 40 of file ttadata.c.
Referenced by tta_decode_frame(), and tta_encode_frame().
ff_tta_filter_init()
void ff_tta_filter_init (TTAFilter * c, int32_t shift)
Definition at line 48 of file ttadata.c.
Referenced by tta_decode_frame(), and tta_encode_frame().
Variable Documentation
ff_tta_shift_1
const uint32_t ff_tta_shift_1[]
Definition at line 23 of file ttadata.c.
Referenced by ff_tta_filter_init(), tta_decode_frame(), and tta_encode_frame().
ff_tta_shift_16
const uint32_t* const ff_tta_shift_16
Definition at line 36 of file ttadata.c.
Referenced by ff_tta_rice_init(), tta_decode_frame(), and tta_encode_frame().
ff_tta_filter_configs
const uint8_t ff_tta_filter_configs[]
Definition at line 38 of file ttadata.c.
Referenced by tta_decode_frame(), and tta_encode_frame().