FFmpeg: libavformat/udp.c File Reference
udp.c File Reference
UDP protocol.
#include "avformat.h"
#include "avio_internal.h"
#include "libavutil/avassert.h"
#include "libavutil/parseutils.h"
#include "libavutil/fifo.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/avstring.h"
#include "libavutil/opt.h"
#include "libavutil/log.h"
#include "libavutil/time.h"
#include "internal.h"
#include "network.h"
#include "os_support.h"
#include "url.h"
Data Structures
struct UDPContext
Macros
#define _DEFAULT_SOURCE
#define _BSD_SOURCE /* Needed for using struct ip_mreq with recent glibc */
#define UDPLITE_SEND_CSCOV 10
#define UDPLITE_RECV_CSCOV 11
#define IPPROTO_UDPLITE 136
#define HAVE_PTHREAD_CANCEL 0
#define IPV6_ADD_MEMBERSHIP IPV6_JOIN_GROUP
#define IPV6_DROP_MEMBERSHIP IPV6_LEAVE_GROUP
#define UDP_TX_BUF_SIZE 32768
#define UDP_MAX_PKT_SIZE 65536
#define UDP_HEADER_SIZE 8
#define OFFSET(x) offsetof(UDPContext, x)
#define D AV_OPT_FLAG_DECODING_PARAM
#define E AV_OPT_FLAG_ENCODING_PARAM
Functions
static void log_net_error (void *ctx, int level, const char *prefix)
static int udp_set_multicast_ttl (int sockfd, int mcastTTL, struct sockaddr *addr)
static int udp_join_multicast_group (int sockfd, struct sockaddr *addr, struct sockaddr *local_addr)
static int udp_leave_multicast_group (int sockfd, struct sockaddr *addr, struct sockaddr *local_addr)
static struct addrinfo * udp_resolve_host (URLContext *h, const char *hostname, int port, int type, int family, int flags)
static int udp_set_multicast_sources (URLContext *h, int sockfd, struct sockaddr *addr, int addr_len, char **sources, int nb_sources, int include)
static int udp_set_url (URLContext *h, struct sockaddr_storage *addr, const char *hostname, int port)
static int udp_socket_create (URLContext *h, struct sockaddr_storage *addr, socklen_t *addr_len, const char *localaddr)
static int udp_port (struct sockaddr_storage *addr, int addr_len)
int ff_udp_set_remote_url (URLContext *h, const char *uri)
If no filename is given to av_open_input_file because you want to get the local port first, then you must call this function to set the remote server address.
int ff_udp_get_local_port (URLContext *h)
Return the local port used by the UDP connection.
static int udp_get_file_handle (URLContext *h)
Return the udp file handle for select() usage to wait for several RTP streams at the same time.
static int parse_source_list (char *buf, char **sources, int *num_sources, int max_sources)
static int udp_open (URLContext *h, const char *uri, int flags)
static int udplite_open (URLContext *h, const char *uri, int flags)
static int udp_read (URLContext *h, uint8_t *buf, int size)
static int udp_write (URLContext *h, const uint8_t *buf, int size)
static int udp_close (URLContext *h)
Variables
static const AVOption options []
static const AVClass udp_class
static const AVClass udplite_context_class
const URLProtocol ff_udp_protocol
const URLProtocol ff_udplite_protocol
Detailed Description
UDP protocol.
Definition in file udp.c.
Macro Definition Documentation
_DEFAULT_SOURCE
#define _DEFAULT_SOURCE
Definition at line 27 of file udp.c.
_BSD_SOURCE
#define _BSD_SOURCE /* Needed for using struct ip_mreq with recent glibc */
Definition at line 28 of file udp.c.
UDPLITE_SEND_CSCOV
#define UDPLITE_SEND_CSCOV 10
Definition at line 55 of file udp.c.
Referenced by udp_open().
UDPLITE_RECV_CSCOV
#define UDPLITE_RECV_CSCOV 11
Definition at line 56 of file udp.c.
Referenced by udp_open().
IPPROTO_UDPLITE
#define IPPROTO_UDPLITE 136
Definition at line 60 of file udp.c.
Referenced by udp_open(), and udp_socket_create().
HAVE_PTHREAD_CANCEL
#define HAVE_PTHREAD_CANCEL 0
Definition at line 68 of file udp.c.
Referenced by udp_open().
IPV6_ADD_MEMBERSHIP
#define IPV6_ADD_MEMBERSHIP IPV6_JOIN_GROUP
Definition at line 72 of file udp.c.
Referenced by udp_join_multicast_group().
IPV6_DROP_MEMBERSHIP
#define IPV6_DROP_MEMBERSHIP IPV6_LEAVE_GROUP
Definition at line 73 of file udp.c.
Referenced by udp_leave_multicast_group().
UDP_TX_BUF_SIZE
#define UDP_TX_BUF_SIZE 32768
Definition at line 76 of file udp.c.
Referenced by udp_open().
UDP_MAX_PKT_SIZE
#define UDP_MAX_PKT_SIZE 65536
Definition at line 77 of file udp.c.
Referenced by udp_open().
UDP_HEADER_SIZE
#define UDP_HEADER_SIZE 8
Definition at line 78 of file udp.c.
Referenced by udplite_open().
OFFSET
#define OFFSET (x) offsetof(UDPContext, x)
Definition at line 118 of file udp.c.
D
#define D AV_OPT_FLAG_DECODING_PARAM
Definition at line 119 of file udp.c.
E
#define E AV_OPT_FLAG_ENCODING_PARAM
Definition at line 120 of file udp.c.
Function Documentation
log_net_error()
static void log_net_error (void * ctx, int level, const char * prefix) static
Definition at line 157 of file udp.c.
Referenced by ff_udp_set_remote_url(), udp_join_multicast_group(), udp_leave_multicast_group(), udp_open(), udp_set_multicast_sources(), udp_set_multicast_ttl(), and udp_socket_create().
udp_set_multicast_ttl()
static int udp_set_multicast_ttl (int sockfd, int mcastTTL, struct sockaddr * addr) static
Definition at line 164 of file udp.c.
Referenced by udp_open().
udp_join_multicast_group()
static int udp_join_multicast_group (int sockfd, struct sockaddr * addr, struct sockaddr * local_addr) static
Definition at line 186 of file udp.c.
Referenced by udp_open().
udp_leave_multicast_group()
static int udp_leave_multicast_group (int sockfd, struct sockaddr * addr, struct sockaddr * local_addr) static
Definition at line 218 of file udp.c.
Referenced by udp_close().
udp_resolve_host()
static struct addrinfo* udp_resolve_host (URLContext * h, const char * hostname, int port, int type, int family, int flags) static
Definition at line 250 of file udp.c.
Referenced by udp_set_multicast_sources(), udp_set_url(), and udp_socket_create().
udp_set_multicast_sources()
static int udp_set_multicast_sources (URLContext * h, int sockfd, struct sockaddr * addr, int addr_len, char ** sources, int nb_sources, int include) static
Definition at line 280 of file udp.c.
Referenced by udp_open().
udp_set_url()
static int udp_set_url (URLContext * h, struct sockaddr_storage * addr, const char * hostname, int port) static
Definition at line 354 of file udp.c.
Referenced by ff_udp_set_remote_url().
udp_socket_create()
static int udp_socket_create (URLContext * h, struct sockaddr_storage * addr, socklen_t * addr_len, const char * localaddr) static
Definition at line 370 of file udp.c.
Referenced by udp_open().
udp_port()
static int udp_port (struct sockaddr_storage * addr, int addr_len) static
Definition at line 412 of file udp.c.
Referenced by udp_open().
ff_udp_set_remote_url()
int ff_udp_set_remote_url (URLContext * h, const char * uri)
If no filename is given to av_open_input_file because you want to get the local port first, then you must call this function to set the remote server address.
url syntax: udp://host:port[?option=val...] option: 'ttl=n' : set the ttl value (for multicast only) 'localport=n' : set the local port 'pkt_size=n' : set max packet size 'reuse=1' : enable reusing the socket 'overrun_nonfatal=1': survive in case of circular buffer overrun
Parameters
h media file context
uri of the remote server
Returns
zero if no error.
Definition at line 442 of file udp.c.
Referenced by ff_rtp_set_remote_url(), and udp_open().
ff_udp_get_local_port()
int ff_udp_get_local_port (URLContext * h)
Return the local port used by the UDP connection.
Parameters
h media file context
Returns
the local port number
Definition at line 481 of file udp.c.
Referenced by ff_rtp_get_local_rtcp_port(), ff_rtp_get_local_rtp_port(), and rtp_open().
udp_get_file_handle()
static int udp_get_file_handle (URLContext * h) static
Return the udp file handle for select() usage to wait for several RTP streams at the same time.
Parameters
h media file context
Definition at line 492 of file udp.c.
parse_source_list()
static int parse_source_list (char * buf, char ** sources, int * num_sources, int max_sources) static
Definition at line 660 of file udp.c.
Referenced by udp_open().
udp_open()
static int udp_open (URLContext * h, const char * uri, int flags) static
Definition at line 683 of file udp.c.
Referenced by udplite_open().
udplite_open()
static int udplite_open (URLContext * h, const char * uri, int flags) static
Definition at line 1008 of file udp.c.
udp_read()
static int udp_read (URLContext * h, uint8_t * buf, int size) static
Definition at line 1018 of file udp.c.
udp_write()
static int udp_write (URLContext * h, const uint8_t * buf, int size) static
Definition at line 1077 of file udp.c.
udp_close()
static int udp_close (URLContext * h) static
Definition at line 1127 of file udp.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "buffer_size",    "System data size (in bytes)",                     OFFSET(buffer_size),    AV_OPT_TYPE_INT,    { .i64 = -1 },    -1, INT_MAX, .flags = D|E },
    { "bitrate",        "Bits to send per second",                         OFFSET(bitrate),        AV_OPT_TYPE_INT64,  { .i64 = 0  },     0, INT64_MAX, .flags = E },
    { "burst_bits",     "Max length of bursts in bits (when using bitrate)", OFFSET(burst_bits),   AV_OPT_TYPE_INT64,  { .i64 = 0  },     0, INT64_MAX, .flags = E },
    { "localport",      "Local port",                                      OFFSET(local_port),     AV_OPT_TYPE_INT,    { .i64 = -1 },    -1, INT_MAX, D|E },
    { "local_port",     "Local port",                                      OFFSET(local_port),     AV_OPT_TYPE_INT,    { .i64 = -1 },    -1, INT_MAX, .flags = D|E },
    { "localaddr",      "Local address",                                   OFFSET(localaddr),      AV_OPT_TYPE_STRING, { .str = NULL },               .flags = D|E },
    { "udplite_coverage", "choose UDPLite head size which should be validated by checksum", OFFSET(udplite_coverage), AV_OPT_TYPE_INT, {.i64 = 0}, 0, INT_MAX, D|E },
    { "pkt_size",       "Maximum UDP packet size",                         OFFSET(pkt_size),       AV_OPT_TYPE_INT,    { .i64 = 1472 },  -1, INT_MAX, .flags = D|E },
    { "reuse",          "explicitly allow reusing UDP sockets",            OFFSET(reuse_socket),   AV_OPT_TYPE_BOOL,   { .i64 = -1 },    -1, 1,       D|E },
    { "reuse_socket",   "explicitly allow reusing UDP sockets",            OFFSET(reuse_socket),   AV_OPT_TYPE_BOOL,   { .i64 = -1 },    -1, 1,       .flags = D|E },
    { "broadcast", "explicitly allow or disallow broadcast destination",   OFFSET(is_broadcast),   AV_OPT_TYPE_BOOL,   { .i64 = 0  },     0, 1,       E },
    { "ttl",            "Time to live (multicast only)",                   OFFSET(ttl),            AV_OPT_TYPE_INT,    { .i64 = 16 },     0, INT_MAX, E },
    { "connect",        "set if connect() should be called on socket",     OFFSET(is_connected),   AV_OPT_TYPE_BOOL,   { .i64 =  0 },     0, 1,       .flags = D|E },
    { "fifo_size",      "set the UDP receiving circular buffer size, expressed as a number of packets with size of 188 bytes", OFFSET(circular_buffer_size), AV_OPT_TYPE_INT, {.i64 = 7*4096}, 0, INT_MAX, D },
    { "overrun_nonfatal", "survive in case of UDP receiving circular buffer overrun", OFFSET(overrun_nonfatal), AV_OPT_TYPE_BOOL, {.i64 = 0}, 0, 1,    D },
    { "timeout",        "set raise error timeout (only in read mode)",     OFFSET(timeout),        AV_OPT_TYPE_INT,    { .i64 = 0 },      0, INT_MAX, D },
    { "sources",        "Source list",                                     OFFSET(sources),        AV_OPT_TYPE_STRING, { .str = NULL },               .flags = D|E },
    { "block",          "Block list",                                      OFFSET(block),          AV_OPT_TYPE_STRING, { .str = NULL },               .flags = D|E },
    { NULL }
}
Definition at line 121 of file udp.c.
udp_class
const AVClass udp_class static
Initial value:
= {
    .class_name = "udp",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 143 of file udp.c.
udplite_context_class
const AVClass udplite_context_class static
Initial value:
= {
    .class_name     = "udplite",
    .item_name      = av_default_item_name,
    .option         = options,
    .version        = LIBAVUTIL_VERSION_INT,
}
Definition at line 150 of file udp.c.
ff_udp_protocol
const URLProtocol ff_udp_protocol
Initial value:
= {
    .name                = "udp",
    .url_open            = udp_open,
    .url_read            = udp_read,
    .url_write           = udp_write,
    .url_close           = udp_close,
    .url_get_file_handle = udp_get_file_handle,
    .priv_data_size      = sizeof(UDPContext),
    .priv_data_class     = &udp_class,
    .flags               = URL_PROTOCOL_FLAG_NETWORK,
}
Definition at line 1161 of file udp.c.
ff_udplite_protocol
const URLProtocol ff_udplite_protocol
Initial value:
= {
    .name                = "udplite",
    .url_open            = udplite_open,
    .url_read            = udp_read,
    .url_write           = udp_write,
    .url_close           = udp_close,
    .url_get_file_handle = udp_get_file_handle,
    .priv_data_size      = sizeof(UDPContext),
    .priv_data_class     = &udplite_context_class,
    .flags               = URL_PROTOCOL_FLAG_NETWORK,
}
Definition at line 1173 of file udp.c.