FFmpeg: libavcodec/unary.h File Reference
unary.h File Reference
#include "get_bits.h"
Functions
static int get_unary (GetBitContext *gb, int stop, int len)
Get unary code of limited length.
static int get_unary_0_33 (GetBitContext *gb)
Get unary code terminated by a 0 with a maximum length of 33.
static int get_unary_0_9 (GetBitContext *gb)
Function Documentation
get_unary()
static int get_unary (GetBitContext * gb, int stop, int len) inline static
Get unary code of limited length.
Parameters
gb GetBitContext
[in] stop The bitstop value (unary code of 1's or 0's)
[in] len Maximum length
Returns
Unary length/index
Definition at line 33 of file unary.h.
Referenced by ape_decode_value_3860(), decode_block(), decode_frame(), decode_gain_info(), decode_residues(), decode_rice(), decode_segment(), decode_subframe(), decode_sym(), decode_sym_565(), ff_vc1_parse_frame_header(), ff_vc1_parse_frame_header_adv(), get_rice_ook(), get_rice_un(), get_unary_0_33(), get_unary_0_9(), h263_get_modb(), mpc8_parse_seektable(), mss4_decode_image_block(), read_high_coeffs(), read_low_coeffs(), read_var_block_data(), tta_decode_frame(), and vc1_decode_ac_coeff().
get_unary_0_33()
static int get_unary_0_33 (GetBitContext * gb) inline static
Get unary code terminated by a 0 with a maximum length of 33.
Parameters
gb GetBitContext
Returns
Unary length/index
Definition at line 46 of file unary.h.
Referenced by wv_get_value().
get_unary_0_9()
static int get_unary_0_9 (GetBitContext * gb) inline static
Definition at line 51 of file unary.h.
Referenced by decode_scalar().