FFmpeg: libavfilter/unsharp_opencl.c File Reference
unsharp_opencl.c File Reference
unsharp input video
#include "unsharp_opencl.h"
#include "libavutil/common.h"
#include "libavutil/opencl_internal.h"
Macros
#define PLANE_NUM 3
#define ROUND_TO_16(a) (((((a) - 1)/16)+1)*16)
Functions
static void add_mask_counter (uint32_t *dst, uint32_t *counter1, uint32_t *counter2, int len)
static int compute_mask (int step, uint32_t *mask)
static int copy_separable_masks (cl_mem cl_mask_x, cl_mem cl_mask_y, int step_x, int step_y)
static int generate_mask (AVFilterContext *ctx)
int ff_opencl_apply_unsharp (AVFilterContext *ctx, AVFrame *in, AVFrame *out)
int ff_opencl_unsharp_init (AVFilterContext *ctx)
void ff_opencl_unsharp_uninit (AVFilterContext *ctx)
int ff_opencl_unsharp_process_inout_buf (AVFilterContext *ctx, AVFrame *in, AVFrame *out)
Detailed Description
unsharp input video
Definition in file unsharp_opencl.c.
Macro Definition Documentation
PLANE_NUM
#define PLANE_NUM 3
Definition at line 31 of file unsharp_opencl.c.
Referenced by ff_opencl_unsharp_init().
ROUND_TO_16
#define ROUND_TO_16 (a) (((((a) - 1)/16)+1)*16)
Definition at line 32 of file unsharp_opencl.c.
Referenced by ff_opencl_apply_unsharp().
Function Documentation
add_mask_counter()
static void add_mask_counter (uint32_t * dst, uint32_t * counter1, uint32_t * counter2, int len) inline static
Definition at line 34 of file unsharp_opencl.c.
Referenced by compute_mask().
compute_mask()
static int compute_mask (int step, uint32_t * mask) static
Definition at line 42 of file unsharp_opencl.c.
Referenced by copy_separable_masks().
copy_separable_masks()
static int copy_separable_masks (cl_mem cl_mask_x, cl_mem cl_mask_y, int step_x, int step_y) static
Definition at line 90 of file unsharp_opencl.c.
Referenced by generate_mask().
generate_mask()
static int generate_mask (AVFilterContext * ctx) static
Definition at line 123 of file unsharp_opencl.c.
Referenced by ff_opencl_unsharp_init().
ff_opencl_apply_unsharp()
int ff_opencl_apply_unsharp (AVFilterContext * ctx, AVFrame * in, AVFrame * out)
Definition at line 163 of file unsharp_opencl.c.
Referenced by init().
ff_opencl_unsharp_init()
int ff_opencl_unsharp_init (AVFilterContext * ctx)
Definition at line 281 of file unsharp_opencl.c.
Referenced by init().
ff_opencl_unsharp_uninit()
void ff_opencl_unsharp_uninit (AVFilterContext * ctx)
Definition at line 364 of file unsharp_opencl.c.
Referenced by uninit().
ff_opencl_unsharp_process_inout_buf()
int ff_opencl_unsharp_process_inout_buf (AVFilterContext * ctx, AVFrame * in, AVFrame * out)
Definition at line 383 of file unsharp_opencl.c.
Referenced by filter_frame().