FFmpeg: libavfilter/unsharp_opencl.h File Reference
unsharp_opencl.h File Reference
#include "unsharp.h"
Functions
int ff_opencl_unsharp_init (AVFilterContext *ctx)
void ff_opencl_unsharp_uninit (AVFilterContext *ctx)
int ff_opencl_unsharp_process_inout_buf (AVFilterContext *ctx, AVFrame *in, AVFrame *out)
int ff_opencl_apply_unsharp (AVFilterContext *ctx, AVFrame *in, AVFrame *out)
Function Documentation
ff_opencl_unsharp_init()
int ff_opencl_unsharp_init (AVFilterContext * ctx)
Definition at line 281 of file unsharp_opencl.c.
Referenced by init().
ff_opencl_unsharp_uninit()
void ff_opencl_unsharp_uninit (AVFilterContext * ctx)
Definition at line 364 of file unsharp_opencl.c.
Referenced by uninit().
ff_opencl_unsharp_process_inout_buf()
int ff_opencl_unsharp_process_inout_buf (AVFilterContext * ctx, AVFrame * in, AVFrame * out)
Definition at line 383 of file unsharp_opencl.c.
Referenced by filter_frame().
ff_opencl_apply_unsharp()
int ff_opencl_apply_unsharp (AVFilterContext * ctx, AVFrame * in, AVFrame * out)
Definition at line 163 of file unsharp_opencl.c.
Referenced by init().