FFmpeg: libavformat/url.c File Reference
url.c File Reference
URL utility functions.
#include "avformat.h"
#include "config.h"
#include "url.h"
#include "libavutil/avstring.h"
Functions
int ff_url_join (char *str, int size, const char *proto, const char *authorization, const char *hostname, int port, const char *fmt,...)
void ff_make_absolute_url (char *buf, int size, const char *base, const char *rel)
Convert a relative url into an absolute url, given a base url.
AVIODirEntry * ff_alloc_dir_entry (void)
Allocate directory entry with default values.
Detailed Description
URL utility functions.
Definition in file url.c.
Function Documentation
ff_url_join()
int ff_url_join (char * str, int size, const char * proto, const char * authorization, const char * hostname, int port, const char * fmt, ...)
Definition at line 36 of file url.c.
Referenced by build_udp_url(), ff_rtp_set_remote_url(), ff_rtsp_open_transport_ctx(), ff_rtsp_setup_output_streams(), ff_tls_open_underlying(), ftp_connect_control_connection(), ftp_connect_data_connection(), gopher_open(), http_listen(), http_open_cnx_internal(), icecast_open(), mms_open(), mmsh_open_internal(), prompeg_open(), rtmp_http_open(), rtmp_http_send_cmd(), rtmp_open(), rtmpe_open(), rtp_open(), rtsp_listen(), rtsp_read_setup(), sap_read_header(), sap_write_header(), and srtp_open().
ff_make_absolute_url()
void ff_make_absolute_url (char * buf, int size, const char * base, const char * rel)
Convert a relative url into an absolute url, given a base url.
Parameters
buf the buffer where output absolute url is written
size the size of buf
base the base url, may be equal to buf.
rel the new url, which is interpreted relative to base
Definition at line 80 of file url.c.
Referenced by add_file(), new_init_section(), new_playlist(), parse_location(), parse_playlist(), and test().
ff_alloc_dir_entry()
AVIODirEntry* ff_alloc_dir_entry (void)
Allocate directory entry with default values.
Returns
entry or NULL on error
Definition at line 149 of file url.c.
Referenced by file_move(), ftp_read_dir(), libsmbc_read_dir(), and libssh_read_dir().