FFmpeg: libavcodec/utvideo.h File Reference
utvideo.h File Reference
Common Ut Video header.
#include "libavutil/common.h"
#include "avcodec.h"
#include "bswapdsp.h"
#include "huffyuvdsp.h"
#include "huffyuvencdsp.h"
Data Structures
struct UtvideoContext
struct HuffEntry
Enumerations
enum { PRED_NONE = 0, PRED_LEFT, PRED_GRADIENT, PRED_MEDIAN }
enum { COMP_NONE = 0, COMP_HUFF }
enum {
UTVIDEO_RGB = MKTAG(0x00, 0x00, 0x01, 0x18), UTVIDEO_RGBA = MKTAG(0x00, 0x00, 0x02, 0x18), UTVIDEO_420 = MKTAG('Y', 'V', '1', '2'), UTVIDEO_422 = MKTAG('Y', 'U', 'Y', '2'),
UTVIDEO_444 = MKTAG('Y', 'V', '2', '4')
}
Functions
int ff_ut_huff_cmp_len (const void *a, const void *b)
int ff_ut10_huff_cmp_len (const void *a, const void *b)
Variables
const int ff_ut_pred_order [5]
const int ff_ut_rgb_order [4]
Detailed Description
Common Ut Video header.
Definition in file utvideo.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PRED_NONE
PRED_LEFT
PRED_GRADIENT
PRED_MEDIAN
Definition at line 36 of file utvideo.h.
anonymous enum
anonymous enum
Enumerator
COMP_NONE
COMP_HUFF
Definition at line 43 of file utvideo.h.
anonymous enum
anonymous enum
Enumerator
UTVIDEO_RGB
UTVIDEO_RGBA
UTVIDEO_420
UTVIDEO_422
UTVIDEO_444
Definition at line 55 of file utvideo.h.
Function Documentation
ff_ut_huff_cmp_len()
int ff_ut_huff_cmp_len (const void * a, const void * b)
Definition at line 37 of file utvideo.c.
Referenced by build_huff(), and calculate_codes().
ff_ut10_huff_cmp_len()
int ff_ut10_huff_cmp_len (const void * a, const void * b)
Definition at line 43 of file utvideo.c.
Referenced by build_huff10().
Variable Documentation
ff_ut_pred_order
const int ff_ut_pred_order[5]
Definition at line 30 of file utvideo.c.
Referenced by utvideo_encode_init().
ff_ut_rgb_order
const int ff_ut_rgb_order[4]
Definition at line 35 of file utvideo.c.
Referenced by decode_frame().