FFmpeg: libavcodec/utvideo.c File Reference
utvideo.c File Reference
Common Ut Video code.
#include "utvideo.h"
Functions
int ff_ut_huff_cmp_len (const void *a, const void *b)
int ff_ut10_huff_cmp_len (const void *a, const void *b)
Variables
const int ff_ut_pred_order [5]
const int ff_ut_rgb_order [4] = { 1, 2, 0, 3 }
Detailed Description
Common Ut Video code.
Definition in file utvideo.c.
Function Documentation
ff_ut_huff_cmp_len()
int ff_ut_huff_cmp_len (const void * a, const void * b)
Definition at line 37 of file utvideo.c.
Referenced by build_huff(), and calculate_codes().
ff_ut10_huff_cmp_len()
int ff_ut10_huff_cmp_len (const void * a, const void * b)
Definition at line 43 of file utvideo.c.
Referenced by build_huff10().
Variable Documentation
ff_ut_pred_order
const int ff_ut_pred_order[5]
Initial value:
= {
    PRED_LEFT, PRED_MEDIAN, PRED_MEDIAN, PRED_NONE, PRED_GRADIENT
}
Definition at line 30 of file utvideo.c.
Referenced by utvideo_encode_init().
ff_ut_rgb_order
const int ff_ut_rgb_order[4] = { 1, 2, 0, 3 }
Definition at line 35 of file utvideo.c.
Referenced by decode_frame().