FFmpeg: libavcodec/utvideoenc.c File Reference
utvideoenc.c File Reference
Ut Video encoder.
#include "libavutil/imgutils.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/opt.h"
#include "avcodec.h"
#include "internal.h"
#include "bswapdsp.h"
#include "bytestream.h"
#include "put_bits.h"
#include "huffyuvencdsp.h"
#include "mathops.h"
#include "utvideo.h"
#include "huffman.h"
Macros
#define OFFSET(x) offsetof(UtvideoContext, x)
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Functions
static int huff_cmp_sym (const void *a, const void *b)
static av_cold int utvideo_encode_close (AVCodecContext *avctx)
static av_cold int utvideo_encode_init (AVCodecContext *avctx)
static void mangle_rgb_planes (uint8_t *dst[4], int dst_stride, uint8_t *src, int step, int stride, int width, int height)
static void left_predict (uint8_t *src, uint8_t *dst, int stride, int width, int height)
static void median_predict (UtvideoContext *c, uint8_t *src, uint8_t *dst, int stride, int width, int height)
static void count_usage (uint8_t *src, int width, int height, uint64_t *counts)
static void calculate_codes (HuffEntry *he)
static int write_huff_codes (uint8_t *src, uint8_t *dst, int dst_size, int width, int height, HuffEntry *he)
static int encode_plane (AVCodecContext *avctx, uint8_t *src, uint8_t *dst, int stride, int plane_no, int width, int height, PutByteContext *pb)
static int utvideo_encode_frame (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *pic, int *got_packet)
Variables
static const AVOption options []
static const AVClass utvideo_class
AVCodec ff_utvideo_encoder
Detailed Description
Ut Video encoder.
Definition in file utvideoenc.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(UtvideoContext, x)
Definition at line 662 of file utvideoenc.c.
VE
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 663 of file utvideoenc.c.
Function Documentation
huff_cmp_sym()
static int huff_cmp_sym (const void * a, const void * b) static
Definition at line 42 of file utvideoenc.c.
Referenced by calculate_codes().
utvideo_encode_close()
static av_cold int utvideo_encode_close (AVCodecContext * avctx) static
Definition at line 48 of file utvideoenc.c.
Referenced by utvideo_encode_init().
utvideo_encode_init()
static av_cold int utvideo_encode_init (AVCodecContext * avctx) static
Definition at line 60 of file utvideoenc.c.
mangle_rgb_planes()
static void mangle_rgb_planes (uint8_t * dst[4], int dst_stride, uint8_t * src, int step, int stride, int width, int height) static
Definition at line 246 of file utvideoenc.c.
Referenced by utvideo_encode_frame().
left_predict()
static void left_predict (uint8_t * src, uint8_t * dst, int stride, int width, int height) static
Definition at line 280 of file utvideoenc.c.
Referenced by encode_plane().
median_predict()
static void median_predict (UtvideoContext * c, uint8_t * src, uint8_t * dst, int stride, int width, int height) static
Definition at line 300 of file utvideoenc.c.
Referenced by encode_plane().
count_usage()
static void count_usage (uint8_t * src, int width, int height, uint64_t * counts) static
Definition at line 334 of file utvideoenc.c.
Referenced by encode_plane().
calculate_codes()
static void calculate_codes (HuffEntry * he) static
Definition at line 348 of file utvideoenc.c.
Referenced by encode_plane().
write_huff_codes()
static int write_huff_codes (uint8_t * src, uint8_t * dst, int dst_size, int width, int height, HuffEntry * he) static
Definition at line 369 of file utvideoenc.c.
Referenced by encode_plane().
encode_plane()
static int encode_plane (AVCodecContext * avctx, uint8_t * src, uint8_t * dst, int stride, int plane_no, int width, int height, PutByteContext * pb) static
Definition at line 401 of file utvideoenc.c.
Referenced by utvideo_encode_frame().
utvideo_encode_frame()
static int utvideo_encode_frame (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * pic, int * got_packet) static
Definition at line 543 of file utvideoenc.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
{ "pred", "Prediction method", OFFSET(frame_pred), AV_OPT_TYPE_INT, { .i64 = PRED_LEFT }, PRED_NONE, PRED_MEDIAN, VE, "pred" },
    { "none",     NULL, 0, AV_OPT_TYPE_CONST, { .i64 = PRED_NONE }, INT_MIN, INT_MAX, VE, "pred" },
    { "left",     NULL, 0, AV_OPT_TYPE_CONST, { .i64 = PRED_LEFT }, INT_MIN, INT_MAX, VE, "pred" },
    { "gradient", NULL, 0, AV_OPT_TYPE_CONST, { .i64 = PRED_GRADIENT }, INT_MIN, INT_MAX, VE, "pred" },
    { "median",   NULL, 0, AV_OPT_TYPE_CONST, { .i64 = PRED_MEDIAN }, INT_MIN, INT_MAX, VE, "pred" },
    { NULL},
}
Definition at line 664 of file utvideoenc.c.
utvideo_class
const AVClass utvideo_class static
Initial value:
= {
    .class_name = "utvideo",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 674 of file utvideoenc.c.
ff_utvideo_encoder
AVCodec ff_utvideo_encoder
Initial value:
= {
    .name           = "utvideo",
    .long_name      = NULL_IF_CONFIG_SMALL("Ut Video"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_UTVIDEO,
    .priv_data_size = sizeof(UtvideoContext),
    .priv_class     = &utvideo_class,
    .init           = utvideo_encode_init,
    .encode2        = utvideo_encode_frame,
    .close          = utvideo_encode_close,
    .capabilities   = AV_CODEC_CAP_FRAME_THREADS | AV_CODEC_CAP_INTRA_ONLY,
    .pix_fmts       = (const enum AVPixelFormat[]) {
                          AV_PIX_FMT_RGB24, AV_PIX_FMT_RGBA, AV_PIX_FMT_YUV422P,
                          AV_PIX_FMT_YUV420P, AV_PIX_FMT_YUV444P, AV_PIX_FMT_NONE
                      },
}
Definition at line 681 of file utvideoenc.c.