FFmpeg: libavcodec/utvideodec.c File Reference
utvideodec.c File Reference
Ut Video decoder.
#include <inttypes.h>
#include <stdlib.h>
#include "libavutil/intreadwrite.h"
#include "avcodec.h"
#include "bswapdsp.h"
#include "bytestream.h"
#include "get_bits.h"
#include "thread.h"
#include "utvideo.h"
Functions
static int build_huff10 (const uint8_t *src, VLC *vlc, int *fsym)
static int build_huff (const uint8_t *src, VLC *vlc, int *fsym)
static int decode_plane10 (UtvideoContext *c, int plane_no, uint16_t *dst, int step, int stride, int width, int height, const uint8_t *src, const uint8_t *huff, int use_pred)
static int decode_plane (UtvideoContext *c, int plane_no, uint8_t *dst, int step, int stride, int width, int height, const uint8_t *src, int use_pred)
static void restore_rgb_planes (uint8_t *src, int step, int stride, int width, int height)
static void restore_rgb_planes10 (AVFrame *frame, int width, int height)
static void restore_median_planar (UtvideoContext *c, uint8_t *src, int stride, int width, int height, int slices, int rmode)
static void restore_median_planar_il (UtvideoContext *c, uint8_t *src, int stride, int width, int height, int slices, int rmode)
static void restore_median_packed (uint8_t *src, int step, int stride, int width, int height, int slices, int rmode)
static void restore_median_packed_il (uint8_t *src, int step, int stride, int width, int height, int slices, int rmode)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int decode_init (AVCodecContext *avctx)
static av_cold int decode_end (AVCodecContext *avctx)
Variables
AVCodec ff_utvideo_decoder
Detailed Description
Ut Video decoder.
Definition in file utvideodec.c.
Function Documentation
build_huff10()
static int build_huff10 (const uint8_t * src, VLC * vlc, int * fsym) static
Definition at line 38 of file utvideodec.c.
Referenced by decode_plane10().
build_huff()
static int build_huff (const uint8_t * src, VLC * vlc, int * fsym) static
Definition at line 82 of file utvideodec.c.
Referenced by decode_plane().
decode_plane10()
static int decode_plane10 (UtvideoContext * c, int plane_no, uint16_t * dst, int step, int stride, int width, int height, const uint8_t * src, const uint8_t * huff, int use_pred) static
Definition at line 125 of file utvideodec.c.
Referenced by decode_frame().
decode_plane()
static int decode_plane (UtvideoContext * c, int plane_no, uint8_t * dst, int step, int stride, int width, int height, const uint8_t * src, int use_pred) static
Definition at line 230 of file utvideodec.c.
Referenced by decode_frame().
restore_rgb_planes()
static void restore_rgb_planes (uint8_t * src, int step, int stride, int width, int height) static
Definition at line 335 of file utvideodec.c.
Referenced by decode_frame().
restore_rgb_planes10()
static void restore_rgb_planes10 (AVFrame * frame, int width, int height) static
Definition at line 353 of file utvideodec.c.
Referenced by decode_frame().
restore_median_planar()
static void restore_median_planar (UtvideoContext * c, uint8_t * src, int stride, int width, int height, int slices, int rmode) static
Definition at line 379 of file utvideodec.c.
Referenced by decode_frame().
restore_median_planar_il()
static void restore_median_planar_il (UtvideoContext * c, uint8_t * src, int stride, int width, int height, int slices, int rmode) static
Definition at line 427 of file utvideodec.c.
Referenced by decode_frame().
restore_median_packed()
static void restore_median_packed (uint8_t * src, int step, int stride, int width, int height, int slices, int rmode) static
Definition at line 478 of file utvideodec.c.
Referenced by decode_frame().
restore_median_packed_il()
static void restore_median_packed_il (uint8_t * src, int step, int stride, int width, int height, int slices, int rmode) static
Definition at line 534 of file utvideodec.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 604 of file utvideodec.c.
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 823 of file utvideodec.c.
decode_end()
static av_cold int decode_end (AVCodecContext * avctx) static
Definition at line 925 of file utvideodec.c.
Variable Documentation
ff_utvideo_decoder
AVCodec ff_utvideo_decoder
Initial value:
= {
    .name           = "utvideo",
    .long_name      = NULL_IF_CONFIG_SMALL("Ut Video"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_UTVIDEO,
    .priv_data_size = sizeof(UtvideoContext),
    .init           = decode_init,
    .close          = decode_end,
    .decode         = decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_FRAME_THREADS,
}
Definition at line 934 of file utvideodec.c.