FFmpeg: libavcodec/v210enc.h File Reference
v210enc.h File Reference
#include "libavutil/log.h"
#include "libavutil/opt.h"
#include "libavutil/pixfmt.h"
Data Structures
struct V210EncContext
Functions
void ff_v210enc_init (V210EncContext *s)
void ff_v210enc_init_x86 (V210EncContext *s)
Function Documentation
ff_v210enc_init()
void ff_v210enc_init (V210EncContext * s)
Definition at line 85 of file v210enc.c.
Referenced by checkasm_check_v210enc(), and encode_init().
ff_v210enc_init_x86()
void ff_v210enc_init_x86 (V210EncContext * s)
Definition at line 36 of file v210enc_init.c.
Referenced by ff_v210enc_init().