FFmpeg: libavcodec/x86/v210enc_init.c File Reference
v210enc_init.c File Reference
#include "libavutil/x86/cpu.h"
#include "libavcodec/v210enc.h"
Functions
void ff_v210_planar_pack_8_ssse3 (const uint8_t *y, const uint8_t *u, const uint8_t *v, uint8_t *dst, ptrdiff_t width)
void ff_v210_planar_pack_8_avx (const uint8_t *y, const uint8_t *u, const uint8_t *v, uint8_t *dst, ptrdiff_t width)
void ff_v210_planar_pack_8_avx2 (const uint8_t *y, const uint8_t *u, const uint8_t *v, uint8_t *dst, ptrdiff_t width)
void ff_v210_planar_pack_10_ssse3 (const uint16_t *y, const uint16_t *u, const uint16_t *v, uint8_t *dst, ptrdiff_t width)
void ff_v210_planar_pack_10_avx2 (const uint16_t *y, const uint16_t *u, const uint16_t *v, uint8_t *dst, ptrdiff_t width)
av_cold void ff_v210enc_init_x86 (V210EncContext *s)
Function Documentation
ff_v210_planar_pack_8_ssse3()
void ff_v210_planar_pack_8_ssse3 (const uint8_t * y, const uint8_t * u, const uint8_t * v, uint8_t * dst, ptrdiff_t width)
Referenced by ff_v210enc_init_x86().
ff_v210_planar_pack_8_avx()
void ff_v210_planar_pack_8_avx (const uint8_t * y, const uint8_t * u, const uint8_t * v, uint8_t * dst, ptrdiff_t width)
Referenced by ff_v210enc_init_x86().
ff_v210_planar_pack_8_avx2()
void ff_v210_planar_pack_8_avx2 (const uint8_t * y, const uint8_t * u, const uint8_t * v, uint8_t * dst, ptrdiff_t width)
Referenced by ff_v210enc_init_x86().
ff_v210_planar_pack_10_ssse3()
void ff_v210_planar_pack_10_ssse3 (const uint16_t * y, const uint16_t * u, const uint16_t * v, uint8_t * dst, ptrdiff_t width)
Referenced by ff_v210enc_init_x86().
ff_v210_planar_pack_10_avx2()
void ff_v210_planar_pack_10_avx2 (const uint16_t * y, const uint16_t * u, const uint16_t * v, uint8_t * dst, ptrdiff_t width)
Referenced by ff_v210enc_init_x86().
ff_v210enc_init_x86()
av_cold void ff_v210enc_init_x86 (V210EncContext * s)
Definition at line 36 of file v210enc_init.c.
Referenced by ff_v210enc_init().