FFmpeg: libavdevice/v4l2.c File Reference
v4l2.c File Reference
Video4Linux2 grab interface.
#include "v4l2-common.h"
#include <dirent.h>
Data Structures
struct video_data
struct buff_data
Macros
#define V4L_ALLFORMATS 3
#define V4L_RAWFORMATS 1
#define V4L_COMPFORMATS 2
#define V4L_TS_DEFAULT 0
Return timestamps to the user exactly as returned by the kernel.
#define V4L_TS_ABS 1
Autodetect the kind of timestamps returned by the kernel and convert to absolute (wall clock) timestamps.
#define V4L_TS_MONO2ABS 2
Assume kernel timestamps are from the monotonic clock and convert to absolute timestamps.
#define V4L_TS_CONVERT_READY V4L_TS_DEFAULT
Once the kind of timestamps returned by the kernel have been detected, the value of the timefilter (NULL or not) determines whether a conversion takes place.
#define SET_WRAPPERS(prefix)
#define v4l2_open s->open_f
#define v4l2_close s->close_f
#define v4l2_dup s->dup_f
#define v4l2_ioctl s->ioctl_f
#define v4l2_read s->read_f
#define v4l2_mmap s->mmap_f
#define v4l2_munmap s->munmap_f
#define OFFSET(x) offsetof(struct video_data, x)
#define DEC AV_OPT_FLAG_DECODING_PARAM
Functions
static int device_open (AVFormatContext *ctx)
static int device_init (AVFormatContext *ctx, int *width, int *height, uint32_t pixelformat)
static int first_field (const struct video_data *s)
static void list_formats (AVFormatContext *ctx, int type)
static void list_standards (AVFormatContext *ctx)
static int mmap_init (AVFormatContext *ctx)
static int enqueue_buffer (struct video_data *s, struct v4l2_buffer *buf)
static void mmap_release_buffer (void *opaque, uint8_t *data)
static int init_convert_timestamp (AVFormatContext *ctx, int64_t ts)
static int convert_timestamp (AVFormatContext *ctx, int64_t *ts)
static int mmap_read_frame (AVFormatContext *ctx, AVPacket *pkt)
static int mmap_start (AVFormatContext *ctx)
static void mmap_close (struct video_data *s)
static int v4l2_set_parameters (AVFormatContext *ctx)
static int device_try_init (AVFormatContext *ctx, enum AVPixelFormat pix_fmt, int *width, int *height, uint32_t *desired_format, enum AVCodecID *codec_id)
static int v4l2_read_probe (AVProbeData *p)
static int v4l2_read_header (AVFormatContext *ctx)
static int v4l2_read_packet (AVFormatContext *ctx, AVPacket *pkt)
static int v4l2_read_close (AVFormatContext *ctx)
static int v4l2_is_v4l_dev (const char *name)
static int v4l2_get_device_list (AVFormatContext *ctx, AVDeviceInfoList *device_list)
Variables
static const int desired_video_buffers = 256
static const AVOption options []
static const AVClass v4l2_class
AVInputFormat ff_v4l2_demuxer
Detailed Description
Video4Linux2 grab interface.
Part of this file is based on the V4L2 video capture example (http://linuxtv.org/downloads/v4l-dvb-apis/capture-example.html)
Thanks to Michael Niedermayer for providing the mapping between V4L2_PIX_FMT_* and AV_PIX_FMT_*
Definition in file v4l2.c.
Macro Definition Documentation
V4L_ALLFORMATS
#define V4L_ALLFORMATS 3
Definition at line 42 of file v4l2.c.
V4L_RAWFORMATS
#define V4L_RAWFORMATS 1
Definition at line 43 of file v4l2.c.
Referenced by list_formats().
V4L_COMPFORMATS
#define V4L_COMPFORMATS 2
Definition at line 44 of file v4l2.c.
Referenced by list_formats().
V4L_TS_DEFAULT
#define V4L_TS_DEFAULT 0
Return timestamps to the user exactly as returned by the kernel.
Definition at line 49 of file v4l2.c.
V4L_TS_ABS
#define V4L_TS_ABS 1
Autodetect the kind of timestamps returned by the kernel and convert to absolute (wall clock) timestamps.
Definition at line 54 of file v4l2.c.
Referenced by init_convert_timestamp().
V4L_TS_MONO2ABS
#define V4L_TS_MONO2ABS 2
Assume kernel timestamps are from the monotonic clock and convert to absolute timestamps.
Definition at line 59 of file v4l2.c.
Referenced by init_convert_timestamp().
V4L_TS_CONVERT_READY
#define V4L_TS_CONVERT_READY V4L_TS_DEFAULT
Once the kind of timestamps returned by the kernel have been detected, the value of the timefilter (NULL or not) determines whether a conversion takes place.
Definition at line 66 of file v4l2.c.
Referenced by init_convert_timestamp().
SET_WRAPPERS
#define SET_WRAPPERS (prefix)
Value:
do {       \
    s->open_f   = prefix ## open;       \
    s->close_f  = prefix ## close;      \
    s->dup_f    = prefix ## dup;        \
    s->ioctl_f  = prefix ## ioctl;      \
    s->read_f   = prefix ## read;       \
    s->mmap_f   = prefix ## mmap;       \
    s->munmap_f = prefix ## munmap;     \
} while (0)
Referenced by device_open().
v4l2_open
#define v4l2_open s->open_f
Referenced by device_open().
v4l2_close
#define v4l2_close s->close_f
Referenced by device_open(), v4l2_get_device_list(), v4l2_read_close(), and v4l2_read_header().
v4l2_dup
#define v4l2_dup s->dup_f
v4l2_ioctl
#define v4l2_ioctl s->ioctl_f
Referenced by device_init(), device_open(), enqueue_buffer(), first_field(), list_formats(), list_standards(), mmap_close(), mmap_init(), mmap_read_frame(), mmap_start(), v4l2_get_device_list(), v4l2_read_header(), and v4l2_set_parameters().
v4l2_read
#define v4l2_read s->read_f
v4l2_mmap
#define v4l2_mmap s->mmap_f
Referenced by mmap_init().
v4l2_munmap
#define v4l2_munmap s->munmap_f
Referenced by mmap_close().
OFFSET
#define OFFSET (x) offsetof(struct video_data, x)
Definition at line 1087 of file v4l2.c.
DEC
#define DEC AV_OPT_FLAG_DECODING_PARAM
Definition at line 1088 of file v4l2.c.
Function Documentation
device_open()
static int device_open (AVFormatContext * ctx) static
Definition at line 107 of file v4l2.c.
Referenced by v4l2_get_device_list(), and v4l2_read_header().
device_init()
static int device_init (AVFormatContext * ctx, int * width, int * height, uint32_t pixelformat) static
Definition at line 186 of file v4l2.c.
Referenced by device_try_init().
first_field()
static int first_field (const struct video_data * s) static
Definition at line 228 of file v4l2.c.
Referenced by dnxhd_decode_frame(), dnxhd_encode_picture(), and v4l2_read_header().
list_formats()
static void list_formats (AVFormatContext * ctx, int type) static
Definition at line 269 of file v4l2.c.
Referenced by v4l2_read_header().
list_standards()
static void list_standards (AVFormatContext * ctx) static
Definition at line 307 of file v4l2.c.
Referenced by v4l2_read_header().
mmap_init()
static int mmap_init (AVFormatContext * ctx) static
Definition at line 331 of file v4l2.c.
Referenced by v4l2_read_header().
enqueue_buffer()
static int enqueue_buffer (struct video_data * s, struct v4l2_buffer * buf) static
Definition at line 397 of file v4l2.c.
Referenced by mmap_read_frame(), and mmap_release_buffer().
mmap_release_buffer()
static void mmap_release_buffer (void * opaque, uint8_t * data) static
Definition at line 411 of file v4l2.c.
Referenced by mmap_read_frame().
init_convert_timestamp()
static int init_convert_timestamp (AVFormatContext * ctx, int64_t ts) static
Definition at line 432 of file v4l2.c.
Referenced by convert_timestamp().
convert_timestamp()
static int convert_timestamp (AVFormatContext * ctx, int64_t * ts) static
Definition at line 465 of file v4l2.c.
Referenced by mmap_read_frame().
mmap_read_frame()
static int mmap_read_frame (AVFormatContext * ctx, AVPacket * pkt) static
Definition at line 486 of file v4l2.c.
Referenced by v4l2_read_packet().
mmap_start()
static int mmap_start (AVFormatContext * ctx) static
Definition at line 590 of file v4l2.c.
Referenced by v4l2_read_header().
mmap_close()
static void mmap_close (struct video_data * s) static
Definition at line 623 of file v4l2.c.
Referenced by v4l2_read_close().
v4l2_set_parameters()
static int v4l2_set_parameters (AVFormatContext * ctx) static
Definition at line 640 of file v4l2.c.
Referenced by v4l2_read_header().
device_try_init()
static int device_try_init (AVFormatContext * ctx, enum AVPixelFormat pix_fmt, int * width, int * height, uint32_t * desired_format, enum AVCodecID * codec_id) static
Definition at line 758 of file v4l2.c.
Referenced by v4l2_read_header().
v4l2_read_probe()
static int v4l2_read_probe (AVProbeData * p) static
Definition at line 810 of file v4l2.c.
v4l2_read_header()
static int v4l2_read_header (AVFormatContext * ctx) static
Definition at line 817 of file v4l2.c.
v4l2_read_packet()
static int v4l2_read_packet (AVFormatContext * ctx, AVPacket * pkt) static
Definition at line 972 of file v4l2.c.
v4l2_read_close()
static int v4l2_read_close (AVFormatContext * ctx) static
Definition at line 998 of file v4l2.c.
v4l2_is_v4l_dev()
static int v4l2_is_v4l_dev (const char * name) static
Definition at line 1012 of file v4l2.c.
Referenced by v4l2_get_device_list().
v4l2_get_device_list()
static int v4l2_get_device_list (AVFormatContext * ctx, AVDeviceInfoList * device_list) static
Definition at line 1020 of file v4l2.c.
Variable Documentation
desired_video_buffers
const int desired_video_buffers = 256 static
Definition at line 40 of file v4l2.c.
Referenced by mmap_init().
options
const AVOption options[] static
Initial value:
= {
    { "standard",     "set TV standard, used only by analog frame grabber",       OFFSET(standard),     AV_OPT_TYPE_STRING, {.str = NULL }, 0, 0,       DEC },
    { "channel",      "set TV channel, used only by frame grabber",               OFFSET(channel),      AV_OPT_TYPE_INT,    {.i64 = -1 },  -1, INT_MAX, DEC },
    { "video_size",   "set frame size",                                           OFFSET(width),        AV_OPT_TYPE_IMAGE_SIZE, {.str = NULL},  0, 0,   DEC },
    { "pixel_format", "set preferred pixel format",                               OFFSET(pixel_format), AV_OPT_TYPE_STRING, {.str = NULL},  0, 0,       DEC },
    { "input_format", "set preferred pixel format (for raw video) or codec name", OFFSET(pixel_format), AV_OPT_TYPE_STRING, {.str = NULL},  0, 0,       DEC },
    { "framerate",    "set frame rate",                                           OFFSET(framerate),    AV_OPT_TYPE_STRING, {.str = NULL},  0, 0,       DEC },
    { "list_formats", "list available formats and exit",                          OFFSET(list_format),  AV_OPT_TYPE_INT,    {.i64 = 0 },  0, INT_MAX, DEC, "list_formats" },
    { "all",          "show all available formats",                               OFFSET(list_format),  AV_OPT_TYPE_CONST,  {.i64 = V4L_ALLFORMATS  },    0, INT_MAX, DEC, "list_formats" },
    { "raw",          "show only non-compressed formats",                         OFFSET(list_format),  AV_OPT_TYPE_CONST,  {.i64 = V4L_RAWFORMATS  },    0, INT_MAX, DEC, "list_formats" },
    { "compressed",   "show only compressed formats",                             OFFSET(list_format),  AV_OPT_TYPE_CONST,  {.i64 = V4L_COMPFORMATS },    0, INT_MAX, DEC, "list_formats" },
    { "list_standards", "list supported standards and exit",                      OFFSET(list_standard), AV_OPT_TYPE_INT,   {.i64 = 0 },  0, 1, DEC, "list_standards" },
    { "all",            "show all supported standards",                           OFFSET(list_standard), AV_OPT_TYPE_CONST, {.i64 = 1 },  0, 0, DEC, "list_standards" },
    { "timestamps",   "set type of timestamps for grabbed frames",                OFFSET(ts_mode),      AV_OPT_TYPE_INT,    {.i64 = 0 }, 0, 2, DEC, "timestamps" },
    { "ts",           "set type of timestamps for grabbed frames",                OFFSET(ts_mode),      AV_OPT_TYPE_INT,    {.i64 = 0 }, 0, 2, DEC, "timestamps" },
    { "default",      "use timestamps from the kernel",                           OFFSET(ts_mode),      AV_OPT_TYPE_CONST,  {.i64 = V4L_TS_DEFAULT  }, 0, 2, DEC, "timestamps" },
    { "abs",          "use absolute timestamps (wall clock)",                     OFFSET(ts_mode),      AV_OPT_TYPE_CONST,  {.i64 = V4L_TS_ABS      }, 0, 2, DEC, "timestamps" },
    { "mono2abs",     "force conversion from monotonic to absolute timestamps",   OFFSET(ts_mode),      AV_OPT_TYPE_CONST,  {.i64 = V4L_TS_MONO2ABS }, 0, 2, DEC, "timestamps" },
    { "use_libv4l2",  "use libv4l2 (v4l-utils) conversion functions",             OFFSET(use_libv4l2),  AV_OPT_TYPE_BOOL,   {.i64 = 0}, 0, 1, DEC },
    { NULL },
}
Definition at line 1090 of file v4l2.c.
v4l2_class
const AVClass v4l2_class static
Initial value:
= {
    .class_name = "V4L2 indev",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
    .category   = AV_CLASS_CATEGORY_DEVICE_VIDEO_INPUT,
}
Definition at line 1115 of file v4l2.c.
ff_v4l2_demuxer
AVInputFormat ff_v4l2_demuxer
Initial value:
= {
    .name           = "video4linux2,v4l2",
    .long_name      = NULL_IF_CONFIG_SMALL("Video4Linux2 device grab"),
    .priv_data_size = sizeof(struct video_data),
    .read_probe     = v4l2_read_probe,
    .read_header    = v4l2_read_header,
    .read_packet    = v4l2_read_packet,
    .read_close     = v4l2_read_close,
    .get_device_list = v4l2_get_device_list,
    .flags          = AVFMT_NOFILE,
    .priv_class     = &v4l2_class,
}
Definition at line 1123 of file v4l2.c.