FFmpeg: libavdevice/v4l2enc.c File Reference
v4l2enc.c File Reference
#include "v4l2-common.h"
#include "avdevice.h"
Data Structures
struct V4L2Context
Functions
static av_cold int write_header (AVFormatContext *s1)
static int write_packet (AVFormatContext *s1, AVPacket *pkt)
static int write_trailer (AVFormatContext *s1)
Variables
static const AVClass v4l2_class
AVOutputFormat ff_v4l2_muxer
Function Documentation
write_header()
static av_cold int write_header (AVFormatContext * s1) static
Definition at line 29 of file v4l2enc.c.
write_packet()
static int write_packet (AVFormatContext * s1, AVPacket * pkt) static
Definition at line 86 of file v4l2enc.c.
write_trailer()
static int write_trailer (AVFormatContext * s1) static
Definition at line 94 of file v4l2enc.c.
Referenced by mmf_read_packet(), mov_check_bitstream(), ogg_write_trailer(), and swf_write_trailer().
Variable Documentation
v4l2_class
const AVClass v4l2_class static
Initial value:
= {
    .class_name = "V4L2 outdev",
    .item_name  = av_default_item_name,
    .version    = LIBAVUTIL_VERSION_INT,
    .category   = AV_CLASS_CATEGORY_DEVICE_VIDEO_OUTPUT,
}
Definition at line 101 of file v4l2enc.c.
ff_v4l2_muxer
AVOutputFormat ff_v4l2_muxer
Initial value:
= {
    .name           = "v4l2",
    .long_name      = NULL_IF_CONFIG_SMALL("Video4Linux2 output device"),
    .priv_data_size = sizeof(V4L2Context),
    .audio_codec    = AV_CODEC_ID_NONE,
    .video_codec    = AV_CODEC_ID_RAWVIDEO,
    .write_header   = write_header,
    .write_packet   = write_packet,
    .write_trailer  = write_trailer,
    .flags          = AVFMT_NOFILE,
    .priv_class     = &v4l2_class,
}
Definition at line 108 of file v4l2enc.c.