FFmpeg: libavdevice/v4l2-common.c File Reference
v4l2-common.c File Reference
#include "v4l2-common.h"
Functions
uint32_t ff_fmt_ff2v4l (enum AVPixelFormat pix_fmt, enum AVCodecID codec_id)
enum AVPixelFormat ff_fmt_v4l2ff (uint32_t v4l2_fmt, enum AVCodecID codec_id)
enum AVCodecID ff_fmt_v4l2codec (uint32_t v4l2_fmt)
Variables
const struct fmt_map ff_fmt_conversion_table []
Function Documentation
ff_fmt_ff2v4l()
uint32_t ff_fmt_ff2v4l (enum AVPixelFormat pix_fmt, enum AVCodecID codec_id)
Definition at line 64 of file v4l2-common.c.
Referenced by device_try_init(), and write_header().
ff_fmt_v4l2ff()
enum AVPixelFormat ff_fmt_v4l2ff (uint32_t v4l2_fmt, enum AVCodecID codec_id)
Definition at line 80 of file v4l2-common.c.
Referenced by list_formats(), and v4l2_read_header().
ff_fmt_v4l2codec()
enum AVCodecID ff_fmt_v4l2codec (uint32_t v4l2_fmt)
Definition at line 94 of file v4l2-common.c.
Referenced by device_try_init(), and list_formats().
Variable Documentation
ff_fmt_conversion_table
const struct fmt_map ff_fmt_conversion_table[]
Definition at line 21 of file v4l2-common.c.
Referenced by device_try_init().