FFmpeg: libavcodec/vaapi_encode_h264.c File Reference
vaapi_encode_h264.c File Reference
#include <va/va.h>
#include <va/va_enc_h264.h>
#include "libavutil/avassert.h"
#include "libavutil/internal.h"
#include "libavutil/opt.h"
#include "libavutil/pixfmt.h"
#include "avcodec.h"
#include "h264.h"
#include "h264_sei.h"
#include "internal.h"
#include "vaapi_encode.h"
#include "vaapi_encode_h26x.h"
Data Structures
struct VAAPIEncodeH264MiscSequenceParams
struct VAAPIEncodeH264MiscSliceParams
struct VAAPIEncodeH264Slice
struct VAAPIEncodeH264Context
struct VAAPIEncodeH264Options
Macros
#define vseq_var(name) vseq->name, name
#define vseq_field(name) vseq->seq_fields.bits.name, name
#define vvui_field(name) vseq->vui_fields.bits.name, name
#define vpic_var(name) vpic->name, name
#define vpic_field(name) vpic->pic_fields.bits.name, name
#define vslice_var(name) vslice->name, name
#define vslice_field(name) vslice->slice_fields.bits.name, name
#define mseq_var(name) mseq->name, name
#define mslice_var(name) mslice->name, name
#define OFFSET(x)
#define FLAGS (AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM)
Enumerations
enum {
SLICE_TYPE_P = 0, SLICE_TYPE_B = 1, SLICE_TYPE_I = 2, SLICE_TYPE_SP = 3,
SLICE_TYPE_SI = 4
}
Functions
static void vaapi_encode_h264_write_nal_header (PutBitContext *pbc, int nal_unit_type, int nal_ref_idc)
static void vaapi_encode_h264_write_trailing_rbsp (PutBitContext *pbc)
static void vaapi_encode_h264_write_vui (PutBitContext *pbc, VAAPIEncodeContext *ctx)
static void vaapi_encode_h264_write_sps (PutBitContext *pbc, VAAPIEncodeContext *ctx)
static void vaapi_encode_h264_write_pps (PutBitContext *pbc, VAAPIEncodeContext *ctx)
static void vaapi_encode_h264_write_slice_header2 (PutBitContext *pbc, VAAPIEncodeContext *ctx, VAAPIEncodePicture *pic, VAAPIEncodeSlice *slice)
static void vaapi_encode_h264_write_buffering_period (PutBitContext *pbc, VAAPIEncodeContext *ctx, VAAPIEncodePicture *pic)
static void vaapi_encode_h264_write_pic_timing (PutBitContext *pbc, VAAPIEncodeContext *ctx, VAAPIEncodePicture *pic)
static void vaapi_encode_h264_write_identifier (PutBitContext *pbc, VAAPIEncodeContext *ctx, VAAPIEncodePicture *pic)
static void vaapi_encode_h264_write_sei (PutBitContext *pbc, VAAPIEncodeContext *ctx, VAAPIEncodePicture *pic)
static int vaapi_encode_h264_write_sequence_header (AVCodecContext *avctx, char *data, size_t *data_len)
static int vaapi_encode_h264_write_slice_header (AVCodecContext *avctx, VAAPIEncodePicture *pic, VAAPIEncodeSlice *slice, char *data, size_t *data_len)
static int vaapi_encode_h264_write_extra_header (AVCodecContext *avctx, VAAPIEncodePicture *pic, int index, int *type, char *data, size_t *data_len)
static int vaapi_encode_h264_init_sequence_params (AVCodecContext *avctx)
static int vaapi_encode_h264_init_picture_params (AVCodecContext *avctx, VAAPIEncodePicture *pic)
static int vaapi_encode_h264_init_slice_params (AVCodecContext *avctx, VAAPIEncodePicture *pic, VAAPIEncodeSlice *slice)
static av_cold int vaapi_encode_h264_configure (AVCodecContext *avctx)
static av_cold int vaapi_encode_h264_init (AVCodecContext *avctx)
Variables
static const VAAPIEncodeType vaapi_encode_type_h264
static const AVOption vaapi_encode_h264_options []
static const AVCodecDefault vaapi_encode_h264_defaults []
static const AVClass vaapi_encode_h264_class
AVCodec ff_h264_vaapi_encoder
Macro Definition Documentation
vseq_var
#define vseq_var (name) vseq->name, name
Definition at line 174 of file vaapi_encode_h264.c.
Referenced by vaapi_encode_h264_write_sps(), and vaapi_encode_h264_write_vui().
vseq_field
#define vseq_field (name) vseq->seq_fields.bits.name, name
Definition at line 175 of file vaapi_encode_h264.c.
Referenced by vaapi_encode_h264_write_sps().
vvui_field
#define vvui_field (name) vseq->vui_fields.bits.name, name
Definition at line 176 of file vaapi_encode_h264.c.
Referenced by vaapi_encode_h264_write_vui().
vpic_var
#define vpic_var (name) vpic->name, name
Definition at line 177 of file vaapi_encode_h264.c.
Referenced by vaapi_encode_h264_write_buffering_period(), vaapi_encode_h264_write_pps(), and vaapi_encode_h264_write_slice_header2().
vpic_field
#define vpic_field (name) vpic->pic_fields.bits.name, name
Definition at line 178 of file vaapi_encode_h264.c.
Referenced by vaapi_encode_h264_write_pps().
vslice_var
#define vslice_var (name) vslice->name, name
Definition at line 179 of file vaapi_encode_h264.c.
Referenced by vaapi_encode_h264_write_slice_header2().
vslice_field
#define vslice_field (name) vslice->slice_fields.bits.name, name
Definition at line 180 of file vaapi_encode_h264.c.
mseq_var
#define mseq_var (name) mseq->name, name
Definition at line 181 of file vaapi_encode_h264.c.
Referenced by vaapi_encode_h264_write_buffering_period(), vaapi_encode_h264_write_pic_timing(), vaapi_encode_h264_write_pps(), vaapi_encode_h264_write_sps(), and vaapi_encode_h264_write_vui().
mslice_var
#define mslice_var (name) mslice->name, name
Definition at line 182 of file vaapi_encode_h264.c.
Referenced by vaapi_encode_h264_write_slice_header2().
OFFSET
#define OFFSET (x)
Value:
(offsetof(VAAPIEncodeContext, codec_options_data) + \
                   offsetof(VAAPIEncodeH264Options, x))
Definition at line 1258 of file vaapi_encode_h264.c.
FLAGS
#define FLAGS (AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM)
Definition at line 1260 of file vaapi_encode_h264.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SLICE_TYPE_P
SLICE_TYPE_B
SLICE_TYPE_I
SLICE_TYPE_SP
SLICE_TYPE_SI
Definition at line 34 of file vaapi_encode_h264.c.
Function Documentation
vaapi_encode_h264_write_nal_header()
static void vaapi_encode_h264_write_nal_header (PutBitContext * pbc, int nal_unit_type, int nal_ref_idc) static
Definition at line 184 of file vaapi_encode_h264.c.
Referenced by vaapi_encode_h264_write_pps(), vaapi_encode_h264_write_sei(), vaapi_encode_h264_write_slice_header2(), and vaapi_encode_h264_write_sps().
vaapi_encode_h264_write_trailing_rbsp()
static void vaapi_encode_h264_write_trailing_rbsp (PutBitContext * pbc) static
Definition at line 192 of file vaapi_encode_h264.c.
Referenced by vaapi_encode_h264_write_pps(), vaapi_encode_h264_write_sei(), and vaapi_encode_h264_write_sps().
vaapi_encode_h264_write_vui()
static void vaapi_encode_h264_write_vui (PutBitContext * pbc, VAAPIEncodeContext * ctx) static
Definition at line 199 of file vaapi_encode_h264.c.
Referenced by vaapi_encode_h264_write_sps().
vaapi_encode_h264_write_sps()
static void vaapi_encode_h264_write_sps (PutBitContext * pbc, VAAPIEncodeContext * ctx) static
Definition at line 282 of file vaapi_encode_h264.c.
Referenced by vaapi_encode_h264_write_sequence_header().
vaapi_encode_h264_write_pps()
static void vaapi_encode_h264_write_pps (PutBitContext * pbc, VAAPIEncodeContext * ctx) static
Definition at line 368 of file vaapi_encode_h264.c.
Referenced by vaapi_encode_h264_write_sequence_header().
vaapi_encode_h264_write_slice_header2()
static void vaapi_encode_h264_write_slice_header2 (PutBitContext * pbc, VAAPIEncodeContext * ctx, VAAPIEncodePicture * pic, VAAPIEncodeSlice * slice) static
Definition at line 414 of file vaapi_encode_h264.c.
Referenced by vaapi_encode_h264_write_slice_header().
vaapi_encode_h264_write_buffering_period()
static void vaapi_encode_h264_write_buffering_period (PutBitContext * pbc, VAAPIEncodeContext * ctx, VAAPIEncodePicture * pic) static
Definition at line 559 of file vaapi_encode_h264.c.
Referenced by vaapi_encode_h264_write_sei().
vaapi_encode_h264_write_pic_timing()
static void vaapi_encode_h264_write_pic_timing (PutBitContext * pbc, VAAPIEncodeContext * ctx, VAAPIEncodePicture * pic) static
Definition at line 583 of file vaapi_encode_h264.c.
Referenced by vaapi_encode_h264_write_sei().
vaapi_encode_h264_write_identifier()
static void vaapi_encode_h264_write_identifier (PutBitContext * pbc, VAAPIEncodeContext * ctx, VAAPIEncodePicture * pic) static
Definition at line 613 of file vaapi_encode_h264.c.
Referenced by vaapi_encode_h264_write_sei().
vaapi_encode_h264_write_sei()
static void vaapi_encode_h264_write_sei (PutBitContext * pbc, VAAPIEncodeContext * ctx, VAAPIEncodePicture * pic) static
Definition at line 637 of file vaapi_encode_h264.c.
Referenced by vaapi_encode_h264_write_extra_header().
vaapi_encode_h264_write_sequence_header()
static int vaapi_encode_h264_write_sequence_header (AVCodecContext * avctx, char * data, size_t * data_len) static
Definition at line 692 of file vaapi_encode_h264.c.
vaapi_encode_h264_write_slice_header()
static int vaapi_encode_h264_write_slice_header (AVCodecContext * avctx, VAAPIEncodePicture * pic, VAAPIEncodeSlice * slice, char * data, size_t * data_len) static
Definition at line 734 of file vaapi_encode_h264.c.
vaapi_encode_h264_write_extra_header()
static int vaapi_encode_h264_write_extra_header (AVCodecContext * avctx, VAAPIEncodePicture * pic, int index, int * type, char * data, size_t * data_len) static
Definition at line 753 of file vaapi_encode_h264.c.
vaapi_encode_h264_init_sequence_params()
static int vaapi_encode_h264_init_sequence_params (AVCodecContext * avctx) static
Definition at line 779 of file vaapi_encode_h264.c.
vaapi_encode_h264_init_picture_params()
static int vaapi_encode_h264_init_picture_params (AVCodecContext * avctx, VAAPIEncodePicture * pic) static
Definition at line 950 of file vaapi_encode_h264.c.
vaapi_encode_h264_init_slice_params()
static int vaapi_encode_h264_init_slice_params (AVCodecContext * avctx, VAAPIEncodePicture * pic, VAAPIEncodeSlice * slice) static
Definition at line 1008 of file vaapi_encode_h264.c.
vaapi_encode_h264_configure()
static av_cold int vaapi_encode_h264_configure (AVCodecContext * avctx) static
Definition at line 1101 of file vaapi_encode_h264.c.
vaapi_encode_h264_init()
static av_cold int vaapi_encode_h264_init (AVCodecContext * avctx) static
Definition at line 1182 of file vaapi_encode_h264.c.
Variable Documentation
vaapi_encode_type_h264
const VAAPIEncodeType vaapi_encode_type_h264 static
Initial value:
= {
    .priv_data_size        = sizeof(VAAPIEncodeH264Context),
    .configure             = &vaapi_encode_h264_configure,
    .sequence_params_size  = sizeof(VAEncSequenceParameterBufferH264),
    .init_sequence_params  = &vaapi_encode_h264_init_sequence_params,
    .picture_params_size   = sizeof(VAEncPictureParameterBufferH264),
    .init_picture_params   = &vaapi_encode_h264_init_picture_params,
    .slice_params_size     = sizeof(VAEncSliceParameterBufferH264),
    .init_slice_params     = &vaapi_encode_h264_init_slice_params,
    .sequence_header_type  = VAEncPackedHeaderSequence,
    .write_sequence_header = &vaapi_encode_h264_write_sequence_header,
    .slice_header_type     = VAEncPackedHeaderH264_Slice,
    .write_slice_header    = &vaapi_encode_h264_write_slice_header,
    .write_extra_header    = &vaapi_encode_h264_write_extra_header,
}
Definition at line 1159 of file vaapi_encode_h264.c.
vaapi_encode_h264_options
const AVOption vaapi_encode_h264_options[] static
Initial value:
= {
    { "qp", "Constant QP (for P-frames; scaled by qfactor/qoffset for I/B)",
      OFFSET(qp), AV_OPT_TYPE_INT, { .i64 = 20 }, 0, 52, FLAGS },
    { "quality", "Set encode quality (trades off against speed, higher is faster)",
      OFFSET(quality), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, 8, FLAGS },
    { "low_power", "Use low-power encoding mode (experimental: only supported "
      "on some platforms, does not support all features)",
      OFFSET(low_power), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, 1, FLAGS },
    { NULL },
}
Definition at line 1261 of file vaapi_encode_h264.c.
vaapi_encode_h264_defaults
const AVCodecDefault vaapi_encode_h264_defaults[] static
Initial value:
= {
    { "profile",        "100" },
    { "level",          "51"  },
    { "b",              "0"   },
    { "bf",             "2"   },
    { "g",              "120" },
    { "i_qfactor",      "1"   },
    { "i_qoffset",      "0"   },
    { "b_qfactor",      "6/5" },
    { "b_qoffset",      "0"   },
    { NULL },
}
Definition at line 1272 of file vaapi_encode_h264.c.
vaapi_encode_h264_class
const AVClass vaapi_encode_h264_class static
Initial value:
= {
    .class_name = "h264_vaapi",
    .item_name  = av_default_item_name,
    .option     = vaapi_encode_h264_options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1285 of file vaapi_encode_h264.c.
ff_h264_vaapi_encoder
AVCodec ff_h264_vaapi_encoder
Initial value:
= {
    .name           = "h264_vaapi",
    .long_name      = NULL_IF_CONFIG_SMALL("H.264/AVC (VAAPI)"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_H264,
    .priv_data_size = (sizeof(VAAPIEncodeContext) +
                       sizeof(VAAPIEncodeH264Options)),
    .init           = &vaapi_encode_h264_init,
    .encode2        = &ff_vaapi_encode2,
    .close          = &ff_vaapi_encode_close,
    .priv_class     = &vaapi_encode_h264_class,
    .capabilities   = AV_CODEC_CAP_DELAY,
    .defaults       = vaapi_encode_h264_defaults,
    .pix_fmts = (const enum AVPixelFormat[]) {
        AV_PIX_FMT_VAAPI,
        AV_PIX_FMT_NONE,
    },
}
Definition at line 1292 of file vaapi_encode_h264.c.