FFmpeg: libavcodec/vaapi_encode.h File Reference
vaapi_encode.h File Reference
#include <stdint.h>
#include <va/va.h>
#include "libavutil/hwcontext.h"
#include "libavutil/hwcontext_vaapi.h"
#include "avcodec.h"
Data Structures
struct VAAPIEncodeSlice
struct VAAPIEncodePicture
struct VAAPIEncodeContext
struct VAAPIEncodeType
Enumerations
enum {
MAX_CONFIG_ATTRIBUTES = 4, MAX_GLOBAL_PARAMS = 4, MAX_PICTURE_REFERENCES = 2, MAX_PICTURE_SLICES = 1,
MAX_PARAM_BUFFERS = 16, MAX_REORDER_DELAY = 16, MAX_PARAM_BUFFER_SIZE = 1024
}
enum { PICTURE_TYPE_IDR = 0, PICTURE_TYPE_I = 1, PICTURE_TYPE_P = 2, PICTURE_TYPE_B = 3 }
Functions
int ff_vaapi_encode2 (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *input_image, int *got_packet)
int ff_vaapi_encode_init (AVCodecContext *avctx)
int ff_vaapi_encode_close (AVCodecContext *avctx)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MAX_CONFIG_ATTRIBUTES
MAX_GLOBAL_PARAMS
MAX_PICTURE_REFERENCES
MAX_PICTURE_SLICES
MAX_PARAM_BUFFERS
MAX_REORDER_DELAY
MAX_PARAM_BUFFER_SIZE
Definition at line 34 of file vaapi_encode.h.
anonymous enum
anonymous enum
Enumerator
PICTURE_TYPE_IDR
PICTURE_TYPE_I
PICTURE_TYPE_P
PICTURE_TYPE_B
Definition at line 44 of file vaapi_encode.h.
Function Documentation
ff_vaapi_encode2()
int ff_vaapi_encode2 (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * input_image, int * got_packet)
Definition at line 826 of file vaapi_encode.c.
ff_vaapi_encode_init()
int ff_vaapi_encode_init (AVCodecContext * avctx)
Definition at line 1275 of file vaapi_encode.c.
Referenced by vaapi_encode_h264_init(), vaapi_encode_h265_init(), and vaapi_encode_mjpeg_init().
ff_vaapi_encode_close()
int ff_vaapi_encode_close (AVCodecContext * avctx)
Definition at line 1437 of file vaapi_encode.c.
Referenced by ff_vaapi_encode_init().