FFmpeg: libavcodec/vaapi_hevc.c File Reference
vaapi_hevc.c File Reference
This file implements the glue code between FFmpeg's and VA API's structures for HEVC decoding.
#include "vaapi_internal.h"
#include "hevc.h"
#include "mpegutils.h"
Data Structures
struct vaapi_hevc_frame_data
Functions
static void init_vaapi_pic (VAPictureHEVC *va_pic)
Initialize an empty VA API picture.
static void fill_vaapi_pic (VAPictureHEVC *va_pic, const HEVCFrame *pic, int rps_type)
static int find_frame_rps_type (const HEVCContext *h, const HEVCFrame *pic)
static void fill_vaapi_ReferenceFrames (const HEVCContext *h, VAPictureParameterBufferHEVC *pp)
static uint8_t get_ref_pic_index (const HEVCContext *h, const HEVCFrame *frame)
static void fill_picture_parameters (const HEVCContext *h, VAPictureParameterBufferHEVC *pp)
static int vaapi_hevc_start_frame (AVCodecContext *avctx, av_unused const uint8_t *buffer, av_unused uint32_t size)
Initialize and start decoding a frame with VA API.
static int vaapi_hevc_end_frame (AVCodecContext *avctx)
End a hardware decoding based frame.
static int fill_pred_weight_table (HEVCContext *const h, VASliceParameterBufferHEVC *slice_param, SliceHeader *const sh)
static int vaapi_hevc_decode_slice (AVCodecContext *avctx, const uint8_t *buffer, uint32_t size)
Decode the given hevc slice with VA API.
Variables
AVHWAccel ff_hevc_vaapi_hwaccel
Detailed Description
This file implements the glue code between FFmpeg's and VA API's structures for HEVC decoding.
Definition in file vaapi_hevc.c.
Function Documentation
init_vaapi_pic()
static void init_vaapi_pic (VAPictureHEVC * va_pic) static
Initialize an empty VA API picture.
VA API requires a fixed-size reference picture array.
Definition at line 43 of file vaapi_hevc.c.
Referenced by fill_vaapi_ReferenceFrames().
fill_vaapi_pic()
static void fill_vaapi_pic (VAPictureHEVC * va_pic, const HEVCFrame * pic, int rps_type) static
Definition at line 50 of file vaapi_hevc.c.
Referenced by fill_picture_parameters(), and fill_vaapi_ReferenceFrames().
find_frame_rps_type()
static int find_frame_rps_type (const HEVCContext * h, const HEVCFrame * pic) static
Definition at line 68 of file vaapi_hevc.c.
Referenced by fill_vaapi_ReferenceFrames().
fill_vaapi_ReferenceFrames()
static void fill_vaapi_ReferenceFrames (const HEVCContext * h, VAPictureParameterBufferHEVC * pp) static
Definition at line 91 of file vaapi_hevc.c.
Referenced by fill_picture_parameters().
get_ref_pic_index()
static uint8_t get_ref_pic_index (const HEVCContext * h, const HEVCFrame * frame) static
Definition at line 114 of file vaapi_hevc.c.
Referenced by vaapi_hevc_decode_slice().
fill_picture_parameters()
static void fill_picture_parameters (const HEVCContext * h, VAPictureParameterBufferHEVC * pp) static
Definition at line 133 of file vaapi_hevc.c.
Referenced by vaapi_hevc_start_frame().
vaapi_hevc_start_frame()
static int vaapi_hevc_start_frame (AVCodecContext * avctx, av_unused const uint8_t * buffer, av_unused uint32_t size) static
Initialize and start decoding a frame with VA API.
Definition at line 258 of file vaapi_hevc.c.
vaapi_hevc_end_frame()
static int vaapi_hevc_end_frame (AVCodecContext * avctx) static
End a hardware decoding based frame.
Definition at line 315 of file vaapi_hevc.c.
fill_pred_weight_table()
static int fill_pred_weight_table (HEVCContext *const h, VASliceParameterBufferHEVC * slice_param, SliceHeader *const sh) static
Definition at line 339 of file vaapi_hevc.c.
Referenced by vaapi_hevc_decode_slice().
vaapi_hevc_decode_slice()
static int vaapi_hevc_decode_slice (AVCodecContext * avctx, const uint8_t * buffer, uint32_t size) static
Decode the given hevc slice with VA API.
Definition at line 393 of file vaapi_hevc.c.
Variable Documentation
ff_hevc_vaapi_hwaccel
AVHWAccel ff_hevc_vaapi_hwaccel
Initial value:
= {
    .name                 = "hevc_vaapi",
    .type                 = AVMEDIA_TYPE_VIDEO,
    .id                   = AV_CODEC_ID_HEVC,
    .pix_fmt              = AV_PIX_FMT_VAAPI,
    .start_frame          = vaapi_hevc_start_frame,
    .end_frame            = vaapi_hevc_end_frame,
    .decode_slice         = vaapi_hevc_decode_slice,
    .init                 = ff_vaapi_context_init,
    .uninit               = ff_vaapi_context_fini,
    .priv_data_size       = sizeof(FFVAContext),
    .frame_priv_data_size = sizeof(vaapi_hevc_frame_data),
}
Definition at line 476 of file vaapi_hevc.c.