FFmpeg: libavcodec/vaapi_vc1.c File Reference
vaapi_vc1.c File Reference
#include "vaapi_internal.h"
#include "internal.h"
#include "vc1.h"
#include "vc1data.h"
Functions
static int get_VAMvModeVC1 (enum MVModes mv_mode)
Translate FFmpeg MV modes to VA API.
static int vc1_has_MVTYPEMB_bitplane (VC1Context *v)
Check whether the MVTYPEMB bitplane is present.
static int vc1_has_SKIPMB_bitplane (VC1Context *v)
Check whether the SKIPMB bitplane is present.
static int vc1_has_DIRECTMB_bitplane (VC1Context *v)
Check whether the DIRECTMB bitplane is present.
static int vc1_has_ACPRED_bitplane (VC1Context *v)
Check whether the ACPRED bitplane is present.
static int vc1_has_OVERFLAGS_bitplane (VC1Context *v)
Check whether the OVERFLAGS bitplane is present.
static int vc1_get_PTYPE (VC1Context *v)
Reconstruct bitstream PTYPE (7.1.1.4, index into Table-35)
static VAMvModeVC1 vc1_get_MVMODE (VC1Context *v)
Reconstruct bitstream MVMODE (7.1.1.32)
static VAMvModeVC1 vc1_get_MVMODE2 (VC1Context *v)
Reconstruct bitstream MVMODE2 (7.1.1.33)
static int vc1_get_TTFRM (VC1Context *v)
Reconstruct bitstream TTFRM (7.1.1.41, Table-53)
static void vc1_pack_bitplanes (uint8_t *bitplane, int n, const uint8_t *ff_bp[3], int x, int y, int stride)
Pack FFmpeg bitplanes into a VABitPlaneBuffer element.
static int vaapi_vc1_start_frame (AVCodecContext *avctx, av_unused const uint8_t *buffer, av_unused uint32_t size)
static int vaapi_vc1_decode_slice (AVCodecContext *avctx, const uint8_t *buffer, uint32_t size)
Variables
AVHWAccel ff_vc1_vaapi_hwaccel
Function Documentation
get_VAMvModeVC1()
static int get_VAMvModeVC1 (enum MVModes mv_mode) static
Translate FFmpeg MV modes to VA API.
Definition at line 29 of file vaapi_vc1.c.
Referenced by vc1_get_MVMODE(), and vc1_get_MVMODE2().
vc1_has_MVTYPEMB_bitplane()
static int vc1_has_MVTYPEMB_bitplane (VC1Context * v) inline static
Check whether the MVTYPEMB bitplane is present.
Definition at line 42 of file vaapi_vc1.c.
Referenced by vaapi_vc1_start_frame().
vc1_has_SKIPMB_bitplane()
static int vc1_has_SKIPMB_bitplane (VC1Context * v) inline static
Check whether the SKIPMB bitplane is present.
Definition at line 53 of file vaapi_vc1.c.
Referenced by vaapi_vc1_start_frame().
vc1_has_DIRECTMB_bitplane()
static int vc1_has_DIRECTMB_bitplane (VC1Context * v) inline static
Check whether the DIRECTMB bitplane is present.
Definition at line 62 of file vaapi_vc1.c.
Referenced by vaapi_vc1_start_frame().
vc1_has_ACPRED_bitplane()
static int vc1_has_ACPRED_bitplane (VC1Context * v) inline static
Check whether the ACPRED bitplane is present.
Definition at line 70 of file vaapi_vc1.c.
Referenced by vaapi_vc1_start_frame().
vc1_has_OVERFLAGS_bitplane()
static int vc1_has_OVERFLAGS_bitplane (VC1Context * v) inline static
Check whether the OVERFLAGS bitplane is present.
Definition at line 80 of file vaapi_vc1.c.
Referenced by vaapi_vc1_start_frame().
vc1_get_PTYPE()
static int vc1_get_PTYPE (VC1Context * v) static
Reconstruct bitstream PTYPE (7.1.1.4, index into Table-35)
Definition at line 92 of file vaapi_vc1.c.
Referenced by vaapi_vc1_start_frame().
vc1_get_MVMODE()
static VAMvModeVC1 vc1_get_MVMODE (VC1Context * v) inline static
Reconstruct bitstream MVMODE (7.1.1.32)
Definition at line 104 of file vaapi_vc1.c.
Referenced by vaapi_vc1_start_frame().
vc1_get_MVMODE2()
static VAMvModeVC1 vc1_get_MVMODE2 (VC1Context * v) inline static
Reconstruct bitstream MVMODE2 (7.1.1.33)
Definition at line 113 of file vaapi_vc1.c.
Referenced by vaapi_vc1_start_frame().
vc1_get_TTFRM()
static int vc1_get_TTFRM (VC1Context * v) inline static
Reconstruct bitstream TTFRM (7.1.1.41, Table-53)
Definition at line 121 of file vaapi_vc1.c.
Referenced by vaapi_vc1_start_frame().
vc1_pack_bitplanes()
static void vc1_pack_bitplanes (uint8_t * bitplane, int n, const uint8_t * ff_bp[3], int x, int y, int stride) inline static
Pack FFmpeg bitplanes into a VABitPlaneBuffer element.
Definition at line 133 of file vaapi_vc1.c.
Referenced by vaapi_vc1_start_frame().
vaapi_vc1_start_frame()
static int vaapi_vc1_start_frame (AVCodecContext * avctx, av_unused const uint8_t * buffer, av_unused uint32_t size) static
Definition at line 147 of file vaapi_vc1.c.
Referenced by vaapi_vc1_decode_slice().
vaapi_vc1_decode_slice()
static int vaapi_vc1_decode_slice (AVCodecContext * avctx, const uint8_t * buffer, uint32_t size) static
Definition at line 312 of file vaapi_vc1.c.
Variable Documentation
ff_vc1_vaapi_hwaccel
AVHWAccel ff_vc1_vaapi_hwaccel
Initial value:
= {
    .name           = "vc1_vaapi",
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_VC1,
    .pix_fmt        = AV_PIX_FMT_VAAPI,
    .start_frame    = vaapi_vc1_start_frame,
    .end_frame      = ff_vaapi_mpeg_end_frame,
    .decode_slice   = vaapi_vc1_decode_slice,
    .init           = ff_vaapi_context_init,
    .uninit         = ff_vaapi_context_fini,
    .priv_data_size = sizeof(FFVAContext),
}
Definition at line 349 of file vaapi_vc1.c.