FFmpeg: libavcodec/vaapi_encode_h265.c File Reference
vaapi_encode_h265.c File Reference
#include <va/va.h>
#include <va/va_enc_hevc.h>
#include "libavutil/avassert.h"
#include "libavutil/internal.h"
#include "libavutil/opt.h"
#include "libavutil/pixfmt.h"
#include "avcodec.h"
#include "hevc.h"
#include "internal.h"
#include "put_bits.h"
#include "vaapi_encode.h"
#include "vaapi_encode_h26x.h"
Data Structures
struct VAAPIEncodeH265STRPS
struct VAAPIEncodeH265MiscSequenceParams
struct VAAPIEncodeH265MiscSliceParams
struct VAAPIEncodeH265Slice
struct VAAPIEncodeH265Context
struct VAAPIEncodeH265Options
Macros
#define MAX_ST_REF_PIC_SETS 32
#define MAX_DPB_PICS 16
#define MAX_LAYERS 1
#define vseq_var(name) vseq->name, name
#define vseq_field(name) vseq->seq_fields.bits.name, name
#define vpic_var(name) vpic->name, name
#define vpic_field(name) vpic->pic_fields.bits.name, name
#define vslice_var(name) vslice->name, name
#define vslice_field(name) vslice->slice_fields.bits.name, name
#define mseq_var(name) mseq->name, name
#define mslice_var(name) mslice->name, name
#define mstrps_var(name) mstrps->name, name
#define OFFSET(x)
#define FLAGS (AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM)
Functions
static void vaapi_encode_h265_write_nal_unit_header (PutBitContext *pbc, int nal_unit_type)
static void vaapi_encode_h265_write_rbsp_trailing_bits (PutBitContext *pbc)
static void vaapi_encode_h265_write_profile_tier_level (PutBitContext *pbc, VAAPIEncodeContext *ctx)
static void vaapi_encode_h265_write_vps (PutBitContext *pbc, VAAPIEncodeContext *ctx)
static void vaapi_encode_h265_write_st_ref_pic_set (PutBitContext *pbc, int st_rps_idx, VAAPIEncodeH265STRPS *mstrps)
static void vaapi_encode_h265_write_vui_parameters (PutBitContext *pbc, VAAPIEncodeContext *ctx)
static void vaapi_encode_h265_write_sps (PutBitContext *pbc, VAAPIEncodeContext *ctx)
static void vaapi_encode_h265_write_pps (PutBitContext *pbc, VAAPIEncodeContext *ctx)
static void vaapi_encode_h265_write_slice_header2 (PutBitContext *pbc, VAAPIEncodeContext *ctx, VAAPIEncodePicture *pic, VAAPIEncodeSlice *slice)
static int vaapi_encode_h265_write_sequence_header (AVCodecContext *avctx, char *data, size_t *data_len)
static int vaapi_encode_h265_write_slice_header (AVCodecContext *avctx, VAAPIEncodePicture *pic, VAAPIEncodeSlice *slice, char *data, size_t *data_len)
static int vaapi_encode_h265_init_sequence_params (AVCodecContext *avctx)
static int vaapi_encode_h265_init_picture_params (AVCodecContext *avctx, VAAPIEncodePicture *pic)
static int vaapi_encode_h265_init_slice_params (AVCodecContext *avctx, VAAPIEncodePicture *pic, VAAPIEncodeSlice *slice)
static av_cold int vaapi_encode_h265_configure (AVCodecContext *avctx)
static av_cold int vaapi_encode_h265_init (AVCodecContext *avctx)
Variables
static const VAAPIEncodeType vaapi_encode_type_h265
static const AVOption vaapi_encode_h265_options []
static const AVCodecDefault vaapi_encode_h265_defaults []
static const AVClass vaapi_encode_h265_class
AVCodec ff_hevc_vaapi_encoder
Macro Definition Documentation
MAX_ST_REF_PIC_SETS
#define MAX_ST_REF_PIC_SETS 32
Definition at line 35 of file vaapi_encode_h265.c.
MAX_DPB_PICS
#define MAX_DPB_PICS 16
Definition at line 36 of file vaapi_encode_h265.c.
MAX_LAYERS
#define MAX_LAYERS 1
Definition at line 37 of file vaapi_encode_h265.c.
vseq_var
#define vseq_var (name) vseq->name, name
Definition at line 202 of file vaapi_encode_h265.c.
Referenced by vaapi_encode_h265_write_profile_tier_level(), and vaapi_encode_h265_write_sps().
vseq_field
#define vseq_field (name) vseq->seq_fields.bits.name, name
Definition at line 203 of file vaapi_encode_h265.c.
Referenced by vaapi_encode_h265_write_sps().
vpic_var
#define vpic_var (name) vpic->name, name
Definition at line 204 of file vaapi_encode_h265.c.
Referenced by vaapi_encode_h265_write_pps().
vpic_field
#define vpic_field (name) vpic->pic_fields.bits.name, name
Definition at line 205 of file vaapi_encode_h265.c.
Referenced by vaapi_encode_h265_write_pps().
vslice_var
#define vslice_var (name) vslice->name, name
Definition at line 206 of file vaapi_encode_h265.c.
Referenced by vaapi_encode_h265_write_slice_header2().
vslice_field
#define vslice_field (name) vslice->slice_fields.bits.name, name
Definition at line 207 of file vaapi_encode_h265.c.
Referenced by vaapi_encode_h265_write_slice_header2().
mseq_var
#define mseq_var (name) mseq->name, name
Definition at line 208 of file vaapi_encode_h265.c.
Referenced by vaapi_encode_h265_write_pps(), vaapi_encode_h265_write_profile_tier_level(), vaapi_encode_h265_write_sps(), vaapi_encode_h265_write_vps(), and vaapi_encode_h265_write_vui_parameters().
mslice_var
#define mslice_var (name) mslice->name, name
Definition at line 209 of file vaapi_encode_h265.c.
Referenced by vaapi_encode_h265_write_slice_header2().
mstrps_var
#define mstrps_var (name) mstrps->name, name
Definition at line 210 of file vaapi_encode_h265.c.
Referenced by vaapi_encode_h265_write_st_ref_pic_set().
OFFSET
#define OFFSET (x)
Value:
(offsetof(VAAPIEncodeContext, codec_options_data) + \
                   offsetof(VAAPIEncodeH265Options, x))
Definition at line 1264 of file vaapi_encode_h265.c.
FLAGS
#define FLAGS (AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM)
Definition at line 1266 of file vaapi_encode_h265.c.
Function Documentation
vaapi_encode_h265_write_nal_unit_header()
static void vaapi_encode_h265_write_nal_unit_header (PutBitContext * pbc, int nal_unit_type) static
Definition at line 212 of file vaapi_encode_h265.c.
Referenced by vaapi_encode_h265_write_pps(), vaapi_encode_h265_write_slice_header2(), vaapi_encode_h265_write_sps(), and vaapi_encode_h265_write_vps().
vaapi_encode_h265_write_rbsp_trailing_bits()
static void vaapi_encode_h265_write_rbsp_trailing_bits (PutBitContext * pbc) static
Definition at line 221 of file vaapi_encode_h265.c.
Referenced by vaapi_encode_h265_write_pps(), vaapi_encode_h265_write_sps(), and vaapi_encode_h265_write_vps().
vaapi_encode_h265_write_profile_tier_level()
static void vaapi_encode_h265_write_profile_tier_level (PutBitContext * pbc, VAAPIEncodeContext * ctx) static
Definition at line 228 of file vaapi_encode_h265.c.
Referenced by vaapi_encode_h265_write_sps(), and vaapi_encode_h265_write_vps().
vaapi_encode_h265_write_vps()
static void vaapi_encode_h265_write_vps (PutBitContext * pbc, VAAPIEncodeContext * ctx) static
Definition at line 271 of file vaapi_encode_h265.c.
Referenced by vaapi_encode_h265_write_sequence_header().
vaapi_encode_h265_write_st_ref_pic_set()
static void vaapi_encode_h265_write_st_ref_pic_set (PutBitContext * pbc, int st_rps_idx, VAAPIEncodeH265STRPS * mstrps) static
Definition at line 326 of file vaapi_encode_h265.c.
Referenced by vaapi_encode_h265_write_slice_header2(), and vaapi_encode_h265_write_sps().
vaapi_encode_h265_write_vui_parameters()
static void vaapi_encode_h265_write_vui_parameters (PutBitContext * pbc, VAAPIEncodeContext * ctx) static
Definition at line 352 of file vaapi_encode_h265.c.
Referenced by vaapi_encode_h265_write_sps().
vaapi_encode_h265_write_sps()
static void vaapi_encode_h265_write_sps (PutBitContext * pbc, VAAPIEncodeContext * ctx) static
Definition at line 390 of file vaapi_encode_h265.c.
Referenced by vaapi_encode_h265_write_sequence_header().
vaapi_encode_h265_write_pps()
static void vaapi_encode_h265_write_pps (PutBitContext * pbc, VAAPIEncodeContext * ctx) static
Definition at line 486 of file vaapi_encode_h265.c.
Referenced by vaapi_encode_h265_write_sequence_header().
vaapi_encode_h265_write_slice_header2()
static void vaapi_encode_h265_write_slice_header2 (PutBitContext * pbc, VAAPIEncodeContext * ctx, VAAPIEncodePicture * pic, VAAPIEncodeSlice * slice) static
Definition at line 562 of file vaapi_encode_h265.c.
Referenced by vaapi_encode_h265_write_slice_header().
vaapi_encode_h265_write_sequence_header()
static int vaapi_encode_h265_write_sequence_header (AVCodecContext * avctx, char * data, size_t * data_len) static
Definition at line 707 of file vaapi_encode_h265.c.
vaapi_encode_h265_write_slice_header()
static int vaapi_encode_h265_write_slice_header (AVCodecContext * avctx, VAAPIEncodePicture * pic, VAAPIEncodeSlice * slice, char * data, size_t * data_len) static
Definition at line 762 of file vaapi_encode_h265.c.
vaapi_encode_h265_init_sequence_params()
static int vaapi_encode_h265_init_sequence_params (AVCodecContext * avctx) static
Definition at line 781 of file vaapi_encode_h265.c.
vaapi_encode_h265_init_picture_params()
static int vaapi_encode_h265_init_picture_params (AVCodecContext * avctx, VAAPIEncodePicture * pic) static
Definition at line 957 of file vaapi_encode_h265.c.
vaapi_encode_h265_init_slice_params()
static int vaapi_encode_h265_init_slice_params (AVCodecContext * avctx, VAAPIEncodePicture * pic, VAAPIEncodeSlice * slice) static
Definition at line 1031 of file vaapi_encode_h265.c.
vaapi_encode_h265_configure()
static av_cold int vaapi_encode_h265_configure (AVCodecContext * avctx) static
Definition at line 1157 of file vaapi_encode_h265.c.
vaapi_encode_h265_init()
static av_cold int vaapi_encode_h265_init (AVCodecContext * avctx) static
Definition at line 1224 of file vaapi_encode_h265.c.
Variable Documentation
vaapi_encode_type_h265
const VAAPIEncodeType vaapi_encode_type_h265 static
Initial value:
= {
    .priv_data_size        = sizeof(VAAPIEncodeH265Context),
    .configure             = &vaapi_encode_h265_configure,
    .sequence_params_size  = sizeof(VAEncSequenceParameterBufferHEVC),
    .init_sequence_params  = &vaapi_encode_h265_init_sequence_params,
    .picture_params_size   = sizeof(VAEncPictureParameterBufferHEVC),
    .init_picture_params   = &vaapi_encode_h265_init_picture_params,
    .slice_params_size     = sizeof(VAEncSliceParameterBufferHEVC),
    .init_slice_params     = &vaapi_encode_h265_init_slice_params,
    .sequence_header_type  = VAEncPackedHeaderSequence,
    .write_sequence_header = &vaapi_encode_h265_write_sequence_header,
    .slice_header_type     = VAEncPackedHeaderHEVC_Slice,
    .write_slice_header    = &vaapi_encode_h265_write_slice_header,
}
Definition at line 1203 of file vaapi_encode_h265.c.
Referenced by vaapi_encode_h265_init().
vaapi_encode_h265_options
const AVOption vaapi_encode_h265_options[] static
Initial value:
= {
    { "qp", "Constant QP (for P-frames; scaled by qfactor/qoffset for I/B)",
      OFFSET(qp), AV_OPT_TYPE_INT, { .i64 = 25 }, 0, 52, FLAGS },
    { NULL },
}
Definition at line 1267 of file vaapi_encode_h265.c.
vaapi_encode_h265_defaults
const AVCodecDefault vaapi_encode_h265_defaults[] static
Initial value:
= {
    { "profile",        "1"   },
    { "level",          "51"  },
    { "b",              "0"   },
    { "bf",             "2"   },
    { "g",              "120" },
    { "i_qfactor",      "1"   },
    { "i_qoffset",      "0"   },
    { "b_qfactor",      "6/5" },
    { "b_qoffset",      "0"   },
    { NULL },
}
Definition at line 1273 of file vaapi_encode_h265.c.
vaapi_encode_h265_class
const AVClass vaapi_encode_h265_class static
Initial value:
= {
    .class_name = "h265_vaapi",
    .item_name  = av_default_item_name,
    .option     = vaapi_encode_h265_options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 1286 of file vaapi_encode_h265.c.
ff_hevc_vaapi_encoder
AVCodec ff_hevc_vaapi_encoder
Initial value:
= {
    .name           = "hevc_vaapi",
    .long_name      = NULL_IF_CONFIG_SMALL("H.265/HEVC (VAAPI)"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_HEVC,
    .priv_data_size = (sizeof(VAAPIEncodeContext) +
                       sizeof(VAAPIEncodeH265Options)),
    .init           = &vaapi_encode_h265_init,
    .encode2        = &ff_vaapi_encode2,
    .close          = &ff_vaapi_encode_close,
    .priv_class     = &vaapi_encode_h265_class,
    .capabilities   = AV_CODEC_CAP_DELAY,
    .defaults       = vaapi_encode_h265_defaults,
    .pix_fmts = (const enum AVPixelFormat[]) {
        AV_PIX_FMT_VAAPI,
        AV_PIX_FMT_NONE,
    },
}
Definition at line 1293 of file vaapi_encode_h265.c.