FFmpeg: libavcodec/vble.c File Reference
vble.c File Reference
VBLE Decoder.
#include "libavutil/imgutils.h"
#include "avcodec.h"
#include "get_bits.h"
#include "huffyuvdsp.h"
#include "internal.h"
#include "mathops.h"
#include "thread.h"
Data Structures
struct VBLEContext
Macros
#define BITSTREAM_READER_LE
Functions
static int vble_unpack (VBLEContext *ctx, GetBitContext *gb)
static void vble_restore_plane (VBLEContext *ctx, AVFrame *pic, GetBitContext *gb, int plane, int offset, int width, int height)
static int vble_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int vble_decode_close (AVCodecContext *avctx)
static av_cold int vble_decode_init (AVCodecContext *avctx)
Variables
AVCodec ff_vble_decoder
Detailed Description
VBLE Decoder.
Definition in file vble.c.
Macro Definition Documentation
BITSTREAM_READER_LE
#define BITSTREAM_READER_LE
Definition at line 29 of file vble.c.
Function Documentation
vble_unpack()
static int vble_unpack (VBLEContext * ctx, GetBitContext * gb) static
Definition at line 45 of file vble.c.
Referenced by vble_decode_frame().
vble_restore_plane()
static void vble_restore_plane (VBLEContext * ctx, AVFrame * pic, GetBitContext * gb, int plane, int offset, int width, int height) static
Definition at line 85 of file vble.c.
Referenced by vble_decode_frame().
vble_decode_frame()
static int vble_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 117 of file vble.c.
vble_decode_close()
static av_cold int vble_decode_close (AVCodecContext * avctx) static
Definition at line 174 of file vble.c.
Referenced by vble_decode_init().
vble_decode_init()
static av_cold int vble_decode_init (AVCodecContext * avctx) static
Definition at line 182 of file vble.c.
Variable Documentation
ff_vble_decoder
AVCodec ff_vble_decoder
Initial value:
= {
    .name           = "vble",
    .long_name      = NULL_IF_CONFIG_SMALL("VBLE Lossless Codec"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_VBLE,
    .priv_data_size = sizeof(VBLEContext),
    .init           = vble_decode_init,
    .close          = vble_decode_close,
    .decode         = vble_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_FRAME_THREADS,
    .init_thread_copy = ONLY_IF_THREADS_ENABLED(vble_decode_init),
}
Definition at line 207 of file vble.c.