FFmpeg: libavcodec/vc1_loopfilter.c File Reference
vc1_loopfilter.c File Reference
VC-1 and WMV3 loopfilter.
#include "avcodec.h"
#include "mpegvideo.h"
#include "vc1.h"
#include "vc1dsp.h"
Functions
void ff_vc1_loop_filter_iblk (VC1Context *v, int pq)
void ff_vc1_loop_filter_iblk_delayed (VC1Context *v, int pq)
void ff_vc1_smooth_overlap_filter_iblk (VC1Context *v)
static av_always_inline void vc1_apply_p_v_loop_filter (VC1Context *v, int block_num)
static av_always_inline void vc1_apply_p_h_loop_filter (VC1Context *v, int block_num)
void ff_vc1_apply_p_loop_filter (VC1Context *v)
Detailed Description
VC-1 and WMV3 loopfilter.
Definition in file vc1_loopfilter.c.
Function Documentation
ff_vc1_loop_filter_iblk()
void ff_vc1_loop_filter_iblk (VC1Context * v, int pq)
Definition at line 34 of file vc1_loopfilter.c.
Referenced by vc1_decode_b_blocks(), and vc1_decode_i_blocks().
ff_vc1_loop_filter_iblk_delayed()
void ff_vc1_loop_filter_iblk_delayed (VC1Context * v, int pq)
Definition at line 64 of file vc1_loopfilter.c.
Referenced by vc1_decode_i_blocks_adv().
ff_vc1_smooth_overlap_filter_iblk()
void ff_vc1_smooth_overlap_filter_iblk (VC1Context * v)
Definition at line 134 of file vc1_loopfilter.c.
Referenced by vc1_decode_i_blocks_adv().
vc1_apply_p_v_loop_filter()
static av_always_inline void vc1_apply_p_v_loop_filter (VC1Context * v, int block_num) static
Definition at line 211 of file vc1_loopfilter.c.
Referenced by ff_vc1_apply_p_loop_filter().
vc1_apply_p_h_loop_filter()
static av_always_inline void vc1_apply_p_h_loop_filter (VC1Context * v, int block_num) static
Definition at line 275 of file vc1_loopfilter.c.
Referenced by ff_vc1_apply_p_loop_filter().
ff_vc1_apply_p_loop_filter()
void ff_vc1_apply_p_loop_filter (VC1Context * v)
Definition at line 335 of file vc1_loopfilter.c.
Referenced by vc1_decode_p_blocks().