FFmpeg: libavcodec/vc1_block.c File Reference
vc1_block.c File Reference
VC-1 and WMV3 block decoding routines.
#include "avcodec.h"
#include "mpegutils.h"
#include "mpegvideo.h"
#include "msmpeg4data.h"
#include "unary.h"
#include "vc1.h"
#include "vc1_pred.h"
#include "vc1acdata.h"
#include "vc1data.h"
Macros
#define MB_INTRA_VLC_BITS 9
#define DC_VLC_BITS 9
#define inc_blk_idx(idx)
Functions
static void vc1_put_signed_blocks_clamped (VC1Context *v)
static int vc1_decode_p_mb (VC1Context *v)
Decode one P-frame MB.
static int vc1_decode_p_mb_intfr (VC1Context *v)
static int vc1_decode_p_mb_intfi (VC1Context *v)
static void vc1_decode_b_mb (VC1Context *v)
Decode one B-frame MB (in Main profile)
static void vc1_decode_b_mb_intfi (VC1Context *v)
Decode one B-frame MB (in interlaced field B picture)
static int vc1_decode_b_mb_intfr (VC1Context *v)
Decode one B-frame MB (in interlaced frame B picture)
static void vc1_decode_i_blocks (VC1Context *v)
Decode blocks of I-frame.
static void vc1_decode_i_blocks_adv (VC1Context *v)
Decode blocks of I-frame for advanced profile.
static void vc1_decode_p_blocks (VC1Context *v)
static void vc1_decode_b_blocks (VC1Context *v)
static void vc1_decode_skip_blocks (VC1Context *v)
void ff_vc1_decode_blocks (VC1Context *v)
VC-1 Bitplane decoding
See also
8.7, p56
static void init_block_index (VC1Context *v)
VC1 Macroblock-level functions in Simple/Main Profiles
See also
7.1.4, p91 and 8.1.1.7, p(1)04
static int vc1_coded_block_pred (MpegEncContext *s, int n, uint8_t **coded_block_ptr)
static void vc1_decode_ac_coeff (VC1Context *v, int *last, int *skip, int *value, int codingset)
Decode one AC coefficient.
static int vc1_decode_i_block (VC1Context *v, int16_t block[64], int n, int coded, int codingset)
Decode intra block in intra frames - should be faster than decode_intra_block.
static int vc1_decode_i_block_adv (VC1Context *v, int16_t block[64], int n, int coded, int codingset, int mquant)
Decode intra block in intra frames - should be faster than decode_intra_block.
static int vc1_decode_intra_block (VC1Context *v, int16_t block[64], int n, int coded, int mquant, int codingset)
Decode intra block in inter frames - more generic version than vc1_decode_i_block.
static int vc1_decode_p_block (VC1Context *v, int16_t block[64], int n, int mquant, int ttmb, int first_block, uint8_t *dst, int linesize, int skip_block, int *ttmb_out)
Decode P block.
Variables
static const uint8_t offset_table [2][9]
static const uint8_t size_table [6] = { 0, 2, 3, 4, 5, 8 }
VC-1 Block-level functions
See also
7.1.4, p91 and 8.1.1.7, p(1)04
#define GET_MQUANT()
Get macroblock-level quantizer scale.
#define GET_MVDATA(_dmv_x, _dmv_y)
Get MV differentials.
static av_always_inline void get_mvdata_interlaced (VC1Context *v, int *dmv_x, int *dmv_y, int *pred_flag)
static void vc1_b_mc (VC1Context *v, int dmv_x[2], int dmv_y[2], int direct, int mode)
Reconstruct motion vector for B-frame and do motion compensation.
static int vc1_i_pred_dc (MpegEncContext *s, int overlap, int pq, int n, int16_t **dc_val_ptr, int *dir_ptr)
Get predicted DC value for I-frames only prediction dir: left=0, top=1.
static int ff_vc1_pred_dc (MpegEncContext *s, int overlap, int pq, int n, int a_avail, int c_avail, int16_t **dc_val_ptr, int *dir_ptr)
Get predicted DC value prediction dir: left=0, top=1.
Detailed Description
VC-1 and WMV3 block decoding routines.
Definition in file vc1_block.c.
Macro Definition Documentation
MB_INTRA_VLC_BITS
#define MB_INTRA_VLC_BITS 9
Definition at line 39 of file vc1_block.c.
Referenced by vc1_decode_i_blocks(), and vc1_decode_i_blocks_adv().
DC_VLC_BITS
#define DC_VLC_BITS 9
Definition at line 40 of file vc1_block.c.
Referenced by vc1_decode_i_block(), vc1_decode_i_block_adv(), and vc1_decode_intra_block().
inc_blk_idx
#define inc_blk_idx (idx)
Value:
do { \
        idx++; \
        if (idx >= v->n_allocated_blks) \
            idx = 0; \
    } while (0)
Referenced by vc1_put_signed_blocks_clamped().
GET_MQUANT
#define GET_MQUANT ()
Get macroblock-level quantizer scale.
Definition at line 163 of file vc1_block.c.
Referenced by vc1_decode_b_mb(), vc1_decode_b_mb_intfi(), vc1_decode_b_mb_intfr(), vc1_decode_i_blocks_adv(), vc1_decode_p_mb(), vc1_decode_p_mb_intfi(), and vc1_decode_p_mb_intfr().
GET_MVDATA
#define GET_MVDATA (_dmv_x, _dmv_y)
Get MV differentials.
See also
MVDATA decoding from 8.3.5.2, p(1)20
Parameters
_dmv_x Horizontal differential for decoded MV
_dmv_y Vertical differential for decoded MV
Definition at line 205 of file vc1_block.c.
Referenced by vc1_decode_b_mb(), and vc1_decode_p_mb().
Function Documentation
init_block_index()
static void init_block_index (VC1Context * v) inline static
Definition at line 56 of file vc1_block.c.
Referenced by vc1_decode_b_blocks(), vc1_decode_i_blocks(), vc1_decode_i_blocks_adv(), vc1_decode_p_blocks(), and vc1_decode_skip_blocks().
vc1_put_signed_blocks_clamped()
static void vc1_put_signed_blocks_clamped (VC1Context * v) static
Definition at line 69 of file vc1_block.c.
Referenced by vc1_decode_i_blocks_adv().
get_mvdata_interlaced()
static av_always_inline void get_mvdata_interlaced (VC1Context * v, int * dmv_x, int * dmv_y, int * pred_flag) static
Definition at line 243 of file vc1_block.c.
Referenced by vc1_decode_b_mb_intfi(), vc1_decode_b_mb_intfr(), vc1_decode_p_mb_intfi(), and vc1_decode_p_mb_intfr().
vc1_b_mc()
static void vc1_b_mc (VC1Context * v, int dmv_x[2], int dmv_y[2], int direct, int mode) inline static
Reconstruct motion vector for B-frame and do motion compensation.
Definition at line 294 of file vc1_block.c.
Referenced by vc1_decode_b_mb(), and vc1_decode_b_mb_intfi().
vc1_i_pred_dc()
static int vc1_i_pred_dc (MpegEncContext * s, int overlap, int pq, int n, int16_t ** dc_val_ptr, int * dir_ptr) inline static
Get predicted DC value for I-frames only prediction dir: left=0, top=1.
Parameters
s MpegEncContext
overlap flag indicating that overlap filtering is used
pq integer part of picture quantizer
[in] n block index in the current MB
dc_val_ptr Pointer to DC predictor
dir_ptr Prediction direction for use in AC prediction
Definition at line 320 of file vc1_block.c.
Referenced by vc1_decode_i_block().
ff_vc1_pred_dc()
static int ff_vc1_pred_dc (MpegEncContext * s, int overlap, int pq, int n, int a_avail, int c_avail, int16_t ** dc_val_ptr, int * dir_ptr) inline static
Get predicted DC value prediction dir: left=0, top=1.
Parameters
s MpegEncContext
overlap flag indicating that overlap filtering is used
pq integer part of picture quantizer
[in] n block index in the current MB
a_avail flag indicating top block availability
c_avail flag indicating left block availability
dc_val_ptr Pointer to DC predictor
dir_ptr Prediction direction for use in AC prediction
Definition at line 385 of file vc1_block.c.
Referenced by vc1_decode_i_block_adv(), and vc1_decode_intra_block().
vc1_coded_block_pred()
static int vc1_coded_block_pred (MpegEncContext * s, int n, uint8_t ** coded_block_ptr) inline static
Definition at line 456 of file vc1_block.c.
Referenced by vc1_decode_i_blocks(), and vc1_decode_i_blocks_adv().
vc1_decode_ac_coeff()
static void vc1_decode_ac_coeff (VC1Context * v, int * last, int * skip, int * value, int codingset) static
Decode one AC coefficient.
Parameters
v The VC1 context
last Last coefficient
skip How much zero coefficients to skip
value Decoded AC coefficient value
codingset set of VLC to decode data
See also
8.1.3.4
Definition at line 492 of file vc1_block.c.
Referenced by vc1_decode_i_block(), vc1_decode_i_block_adv(), vc1_decode_intra_block(), and vc1_decode_p_block().
vc1_decode_i_block()
static int vc1_decode_i_block (VC1Context * v, int16_t block[64], int n, int coded, int codingset) static
Decode intra block in intra frames - should be faster than decode_intra_block.
Parameters
v VC1Context
block block to decode
[in] n subblock index
coded are AC coeffs present or not
codingset set of VLC to decode data
Definition at line 553 of file vc1_block.c.
Referenced by vc1_decode_i_blocks().
vc1_decode_i_block_adv()
static int vc1_decode_i_block_adv (VC1Context * v, int16_t block[64], int n, int coded, int codingset, int mquant) static
Decode intra block in intra frames - should be faster than decode_intra_block.
Parameters
v VC1Context
block block to decode
[in] n subblock number
coded are AC coeffs present or not
codingset set of VLC to decode data
mquant quantizer value for this macroblock
Definition at line 693 of file vc1_block.c.
Referenced by vc1_decode_i_blocks_adv().
vc1_decode_intra_block()
static int vc1_decode_intra_block (VC1Context * v, int16_t block[64], int n, int coded, int mquant, int codingset) static
Decode intra block in inter frames - more generic version than vc1_decode_i_block.
Parameters
v VC1Context
block block to decode
[in] n subblock index
coded are AC coeffs present or not
mquant block quantizer
codingset set of VLC to decode data
Definition at line 883 of file vc1_block.c.
Referenced by vc1_decode_b_mb(), vc1_decode_b_mb_intfi(), vc1_decode_b_mb_intfr(), vc1_decode_p_mb(), vc1_decode_p_mb_intfi(), and vc1_decode_p_mb_intfr().
vc1_decode_p_block()
static int vc1_decode_p_block (VC1Context * v, int16_t block[64], int n, int mquant, int ttmb, int first_block, uint8_t * dst, int linesize, int skip_block, int * ttmb_out) static
Decode P block.
Definition at line 1089 of file vc1_block.c.
Referenced by vc1_decode_b_mb(), vc1_decode_b_mb_intfi(), vc1_decode_b_mb_intfr(), vc1_decode_p_mb(), vc1_decode_p_mb_intfi(), and vc1_decode_p_mb_intfr().
vc1_decode_p_mb()
static int vc1_decode_p_mb (VC1Context * v) static
Decode one P-frame MB.
Definition at line 1252 of file vc1_block.c.
Referenced by vc1_decode_p_blocks().
vc1_decode_p_mb_intfr()
static int vc1_decode_p_mb_intfr (VC1Context * v) static
Definition at line 1496 of file vc1_block.c.
Referenced by vc1_decode_p_blocks().
vc1_decode_p_mb_intfi()
static int vc1_decode_p_mb_intfi (VC1Context * v) static
Definition at line 1704 of file vc1_block.c.
Referenced by vc1_decode_p_blocks().
vc1_decode_b_mb()
static void vc1_decode_b_mb (VC1Context * v) static
Decode one B-frame MB (in Main profile)
Definition at line 1825 of file vc1_block.c.
Referenced by vc1_decode_b_blocks().
vc1_decode_b_mb_intfi()
static void vc1_decode_b_mb_intfi (VC1Context * v) static
Decode one B-frame MB (in interlaced field B picture)
Definition at line 1980 of file vc1_block.c.
Referenced by vc1_decode_b_blocks().
vc1_decode_b_mb_intfr()
static int vc1_decode_b_mb_intfr (VC1Context * v) static
Decode one B-frame MB (in interlaced frame B picture)
Definition at line 2140 of file vc1_block.c.
Referenced by vc1_decode_b_blocks().
vc1_decode_i_blocks()
static void vc1_decode_i_blocks (VC1Context * v) static
Decode blocks of I-frame.
Definition at line 2487 of file vc1_block.c.
Referenced by ff_vc1_decode_blocks().
vc1_decode_i_blocks_adv()
static void vc1_decode_i_blocks_adv (VC1Context * v) static
Decode blocks of I-frame for advanced profile.
Definition at line 2632 of file vc1_block.c.
Referenced by ff_vc1_decode_blocks().
vc1_decode_p_blocks()
static void vc1_decode_p_blocks (VC1Context * v) static
Definition at line 2766 of file vc1_block.c.
Referenced by ff_vc1_decode_blocks().
vc1_decode_b_blocks()
static void vc1_decode_b_blocks (VC1Context * v) static
Definition at line 2843 of file vc1_block.c.
Referenced by ff_vc1_decode_blocks().
vc1_decode_skip_blocks()
static void vc1_decode_skip_blocks (VC1Context * v) static
Definition at line 2907 of file vc1_block.c.
Referenced by ff_vc1_decode_blocks().
ff_vc1_decode_blocks()
void ff_vc1_decode_blocks (VC1Context * v)
Definition at line 2929 of file vc1_block.c.
Referenced by decode_wmv9(), and vc1_decode_frame().
Variable Documentation
offset_table
const uint8_t offset_table[2][9] static
Initial value:
= {
    {  0,  1,  2,  4,  8, 16, 32,  64, 128 },
    {  0,  1,  3,  7, 15, 31, 63, 127, 255 },
}
Definition at line 43 of file vc1_block.c.
Referenced by get_mvdata_interlaced().
size_table
const uint8_t size_table[6] = { 0, 2, 3, 4, 5, 8 } static
Definition at line 1248 of file vc1_block.c.