FFmpeg: libavcodec/vc1_pred.c File Reference
vc1_pred.c File Reference
VC-1 and WMV3 block decoding routines.
#include "mathops.h"
#include "mpegutils.h"
#include "mpegvideo.h"
#include "vc1.h"
#include "vc1_pred.h"
#include "vc1data.h"
Functions
static av_always_inline int scaleforsame_x (VC1Context *v, int n, int dir)
static av_always_inline int scaleforsame_y (VC1Context *v, int i, int n, int dir)
static av_always_inline int scaleforopp_x (VC1Context *v, int n)
static av_always_inline int scaleforopp_y (VC1Context *v, int n, int dir)
static av_always_inline int scaleforsame (VC1Context *v, int i, int n, int dim, int dir)
static av_always_inline int scaleforopp (VC1Context *v, int n, int dim, int dir)
void ff_vc1_pred_mv (VC1Context *v, int n, int dmv_x, int dmv_y, int mv1, int r_x, int r_y, uint8_t *is_intra, int pred_flag, int dir)
Predict and set motion vector.
void ff_vc1_pred_mv_intfr (VC1Context *v, int n, int dmv_x, int dmv_y, int mvn, int r_x, int r_y, uint8_t *is_intra, int dir)
Predict and set motion vector for interlaced frame picture MBs.
void ff_vc1_pred_b_mv (VC1Context *v, int dmv_x[2], int dmv_y[2], int direct, int mvtype)
void ff_vc1_pred_b_mv_intfi (VC1Context *v, int n, int *dmv_x, int *dmv_y, int mv1, int *pred_flag)
Detailed Description
VC-1 and WMV3 block decoding routines.
Definition in file vc1_pred.c.
Function Documentation
scaleforsame_x()
static av_always_inline int scaleforsame_x (VC1Context * v, int n, int dir) static
Definition at line 36 of file vc1_pred.c.
Referenced by scaleforsame().
scaleforsame_y()
static av_always_inline int scaleforsame_y (VC1Context * v, int i, int n, int dir) static
Definition at line 69 of file vc1_pred.c.
Referenced by scaleforsame().
scaleforopp_x()
static av_always_inline int scaleforopp_x (VC1Context * v, int n) static
Definition at line 106 of file vc1_pred.c.
Referenced by scaleforopp().
scaleforopp_y()
static av_always_inline int scaleforopp_y (VC1Context * v, int n, int dir) static
Definition at line 133 of file vc1_pred.c.
Referenced by scaleforopp().
scaleforsame()
static av_always_inline int scaleforsame (VC1Context * v, int i, int n, int dim, int dir) static
Definition at line 164 of file vc1_pred.c.
Referenced by ff_vc1_pred_mv().
scaleforopp()
static av_always_inline int scaleforopp (VC1Context * v, int n, int dim, int dir) static
Definition at line 185 of file vc1_pred.c.
Referenced by ff_vc1_pred_mv().
ff_vc1_pred_mv()
void ff_vc1_pred_mv (VC1Context * v, int n, int dmv_x, int dmv_y, int mv1, int r_x, int r_y, uint8_t * is_intra, int pred_flag, int dir)
Predict and set motion vector.
Definition at line 211 of file vc1_pred.c.
Referenced by ff_vc1_pred_b_mv_intfi(), vc1_decode_p_mb(), and vc1_decode_p_mb_intfi().
ff_vc1_pred_mv_intfr()
void ff_vc1_pred_mv_intfr (VC1Context * v, int n, int dmv_x, int dmv_y, int mvn, int r_x, int r_y, uint8_t * is_intra, int dir)
Predict and set motion vector for interlaced frame picture MBs.
Definition at line 463 of file vc1_pred.c.
Referenced by vc1_decode_b_mb_intfr(), and vc1_decode_p_mb_intfr().
ff_vc1_pred_b_mv()
void ff_vc1_pred_b_mv (VC1Context * v, int dmv_x[2], int dmv_y[2], int direct, int mvtype)
Definition at line 684 of file vc1_pred.c.
Referenced by vc1_decode_b_mb().
ff_vc1_pred_b_mv_intfi()
void ff_vc1_pred_b_mv_intfi (VC1Context * v, int n, int * dmv_x, int * dmv_y, int mv1, int * pred_flag)
Definition at line 884 of file vc1_pred.c.
Referenced by vc1_decode_b_mb_intfi().