FFmpeg: libavcodec/arm/vc1dsp_init_neon.c File Reference
vc1dsp_init_neon.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavcodec/vc1dsp.h"
#include "vc1dsp.h"
#include "config.h"
Macros
#define DECL_PUT(X, Y)
#define FN_ASSIGN(X, Y)
Functions
void ff_vc1_inv_trans_8x8_neon (int16_t *block)
void ff_vc1_inv_trans_4x8_neon (uint8_t *dest, int linesize, int16_t *block)
void ff_vc1_inv_trans_8x4_neon (uint8_t *dest, int linesize, int16_t *block)
void ff_vc1_inv_trans_4x4_neon (uint8_t *dest, int linesize, int16_t *block)
void ff_vc1_inv_trans_8x8_dc_neon (uint8_t *dest, int linesize, int16_t *block)
void ff_vc1_inv_trans_4x8_dc_neon (uint8_t *dest, int linesize, int16_t *block)
void ff_vc1_inv_trans_8x4_dc_neon (uint8_t *dest, int linesize, int16_t *block)
void ff_vc1_inv_trans_4x4_dc_neon (uint8_t *dest, int linesize, int16_t *block)
void ff_put_pixels8x8_neon (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int rnd)
void ff_put_vc1_chroma_mc8_neon (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_avg_vc1_chroma_mc8_neon (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_put_vc1_chroma_mc4_neon (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_avg_vc1_chroma_mc4_neon (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
av_cold void ff_vc1dsp_init_neon (VC1DSPContext *dsp)
Macro Definition Documentation
DECL_PUT
#define DECL_PUT (X, Y)
Value:
void ff_put_vc1_mspel_mc##X##Y##_neon(uint8_t *dst, const uint8_t *src, \
                                      ptrdiff_t stride, int rnd); \
static void ff_put_vc1_mspel_mc##X##Y##_16_neon(uint8_t *dst, const uint8_t *src, \
                                         ptrdiff_t stride, int rnd) \
{ \
  ff_put_vc1_mspel_mc##X##Y##_neon(dst+0, src+0, stride, rnd); \
  ff_put_vc1_mspel_mc##X##Y##_neon(dst+8, src+8, stride, rnd); \
  dst += 8*stride; src += 8*stride; \
  ff_put_vc1_mspel_mc##X##Y##_neon(dst+0, src+0, stride, rnd); \
  ff_put_vc1_mspel_mc##X##Y##_neon(dst+8, src+8, stride, rnd); \
}
Definition at line 40 of file vc1dsp_init_neon.c.
FN_ASSIGN
#define FN_ASSIGN (X, Y)
Value:
dsp->put_vc1_mspel_pixels_tab[0][X+4*Y] = ff_put_vc1_mspel_mc##X##Y##_16_neon; \
    dsp->put_vc1_mspel_pixels_tab[1][X+4*Y] = ff_put_vc1_mspel_mc##X##Y##_neon
Definition at line 82 of file vc1dsp_init_neon.c.
Referenced by ff_vc1dsp_init_neon().
Function Documentation
ff_vc1_inv_trans_8x8_neon()
void ff_vc1_inv_trans_8x8_neon (int16_t * block)
Referenced by ff_vc1dsp_init_neon().
ff_vc1_inv_trans_4x8_neon()
void ff_vc1_inv_trans_4x8_neon (uint8_t * dest, int linesize, int16_t * block)
Referenced by ff_vc1dsp_init_neon().
ff_vc1_inv_trans_8x4_neon()
void ff_vc1_inv_trans_8x4_neon (uint8_t * dest, int linesize, int16_t * block)
Referenced by ff_vc1dsp_init_neon().
ff_vc1_inv_trans_4x4_neon()
void ff_vc1_inv_trans_4x4_neon (uint8_t * dest, int linesize, int16_t * block)
Referenced by ff_vc1dsp_init_neon().
ff_vc1_inv_trans_8x8_dc_neon()
void ff_vc1_inv_trans_8x8_dc_neon (uint8_t * dest, int linesize, int16_t * block)
Referenced by ff_vc1dsp_init_neon().
ff_vc1_inv_trans_4x8_dc_neon()
void ff_vc1_inv_trans_4x8_dc_neon (uint8_t * dest, int linesize, int16_t * block)
Referenced by ff_vc1dsp_init_neon().
ff_vc1_inv_trans_8x4_dc_neon()
void ff_vc1_inv_trans_8x4_dc_neon (uint8_t * dest, int linesize, int16_t * block)
Referenced by ff_vc1dsp_init_neon().
ff_vc1_inv_trans_4x4_dc_neon()
void ff_vc1_inv_trans_4x4_dc_neon (uint8_t * dest, int linesize, int16_t * block)
Referenced by ff_vc1dsp_init_neon().
ff_put_pixels8x8_neon()
void ff_put_pixels8x8_neon (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int rnd)
Referenced by ff_vc1dsp_init_neon().
ff_put_vc1_chroma_mc8_neon()
void ff_put_vc1_chroma_mc8_neon (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_vc1dsp_init_neon().
ff_avg_vc1_chroma_mc8_neon()
void ff_avg_vc1_chroma_mc8_neon (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_vc1dsp_init_neon().
ff_put_vc1_chroma_mc4_neon()
void ff_put_vc1_chroma_mc4_neon (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_vc1dsp_init_neon().
ff_avg_vc1_chroma_mc4_neon()
void ff_avg_vc1_chroma_mc4_neon (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_vc1dsp_init_neon().
ff_vc1dsp_init_neon()
av_cold void ff_vc1dsp_init_neon (VC1DSPContext * dsp)
Definition at line 86 of file vc1dsp_init_neon.c.
Referenced by ff_vc1dsp_init_arm().