FFmpeg: libavcodec/aarch64/vc1dsp_init_aarch64.c File Reference
vc1dsp_init_aarch64.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/aarch64/cpu.h"
#include "libavcodec/vc1dsp.h"
#include "config.h"
Functions
void ff_put_vc1_chroma_mc8_neon (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_avg_vc1_chroma_mc8_neon (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_put_vc1_chroma_mc4_neon (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_avg_vc1_chroma_mc4_neon (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
av_cold void ff_vc1dsp_init_aarch64 (VC1DSPContext *dsp)
Function Documentation
ff_put_vc1_chroma_mc8_neon()
void ff_put_vc1_chroma_mc8_neon (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_vc1dsp_init_aarch64().
ff_avg_vc1_chroma_mc8_neon()
void ff_avg_vc1_chroma_mc8_neon (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_vc1dsp_init_aarch64().
ff_put_vc1_chroma_mc4_neon()
void ff_put_vc1_chroma_mc4_neon (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_vc1dsp_init_aarch64().
ff_avg_vc1_chroma_mc4_neon()
void ff_avg_vc1_chroma_mc4_neon (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_vc1dsp_init_aarch64().
ff_vc1dsp_init_aarch64()
av_cold void ff_vc1dsp_init_aarch64 (VC1DSPContext * dsp)
Definition at line 37 of file vc1dsp_init_aarch64.c.
Referenced by ff_vc1dsp_init().