FFmpeg: libavcodec/mips/vc1dsp_mips.h File Reference
vc1dsp_mips.h File Reference
#include "libavcodec/vc1dsp.h"
Functions
void ff_put_vc1_mspel_mc00_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc01_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc02_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc03_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc10_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc11_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc12_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc13_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc20_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc21_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc22_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc23_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc30_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc31_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc32_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc33_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc00_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc01_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc02_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc03_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc10_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc11_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc12_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc13_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc20_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc21_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc22_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc23_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc30_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc31_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc32_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc33_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc00_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc01_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc02_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc03_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc10_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc11_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc12_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc13_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc20_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc21_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc22_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc23_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc30_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc31_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc32_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_put_vc1_mspel_mc33_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc00_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc01_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc02_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc03_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc10_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc11_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc12_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc13_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc20_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc21_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc22_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc23_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc30_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc31_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc32_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_avg_vc1_mspel_mc33_16_mmi (uint8_t *dst, const uint8_t *src, ptrdiff_t stride, int rnd)
void ff_vc1_inv_trans_8x8_mmi (int16_t block[64])
void ff_vc1_inv_trans_8x4_mmi (uint8_t *dest, int linesize, int16_t *block)
void ff_vc1_inv_trans_4x8_mmi (uint8_t *dest, int linesize, int16_t *block)
void ff_vc1_inv_trans_4x4_mmi (uint8_t *dest, int linesize, int16_t *block)
void ff_vc1_inv_trans_4x4_dc_mmi (uint8_t *dest, int linesize, int16_t *block)
void ff_vc1_inv_trans_4x8_dc_mmi (uint8_t *dest, int linesize, int16_t *block)
void ff_vc1_inv_trans_8x4_dc_mmi (uint8_t *dest, int linesize, int16_t *block)
void ff_vc1_inv_trans_8x8_dc_mmi (uint8_t *dest, int linesize, int16_t *block)
void ff_vc1_v_overlap_mmi (uint8_t *src, int stride)
void ff_vc1_h_overlap_mmi (uint8_t *src, int stride)
void ff_vc1_v_s_overlap_mmi (int16_t *top, int16_t *bottom)
void ff_vc1_h_s_overlap_mmi (int16_t *left, int16_t *right)
void ff_vc1_v_loop_filter4_mmi (uint8_t *src, int stride, int pq)
void ff_vc1_h_loop_filter4_mmi (uint8_t *src, int stride, int pq)
void ff_vc1_v_loop_filter8_mmi (uint8_t *src, int stride, int pq)
void ff_vc1_h_loop_filter8_mmi (uint8_t *src, int stride, int pq)
void ff_vc1_v_loop_filter16_mmi (uint8_t *src, int stride, int pq)
void ff_vc1_h_loop_filter16_mmi (uint8_t *src, int stride, int pq)
void ff_put_no_rnd_vc1_chroma_mc8_mmi (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_put_no_rnd_vc1_chroma_mc4_mmi (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_avg_no_rnd_vc1_chroma_mc8_mmi (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_avg_no_rnd_vc1_chroma_mc4_mmi (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
Function Documentation
ff_put_vc1_mspel_mc00_mmi()
void ff_put_vc1_mspel_mc00_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
Definition at line 1202 of file vc1dsp_mmi.c.
ff_put_vc1_mspel_mc01_mmi()
void ff_put_vc1_mspel_mc01_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc02_mmi()
void ff_put_vc1_mspel_mc02_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc03_mmi()
void ff_put_vc1_mspel_mc03_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc10_mmi()
void ff_put_vc1_mspel_mc10_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc11_mmi()
void ff_put_vc1_mspel_mc11_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc12_mmi()
void ff_put_vc1_mspel_mc12_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc13_mmi()
void ff_put_vc1_mspel_mc13_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc20_mmi()
void ff_put_vc1_mspel_mc20_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc21_mmi()
void ff_put_vc1_mspel_mc21_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc22_mmi()
void ff_put_vc1_mspel_mc22_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc23_mmi()
void ff_put_vc1_mspel_mc23_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc30_mmi()
void ff_put_vc1_mspel_mc30_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc31_mmi()
void ff_put_vc1_mspel_mc31_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc32_mmi()
void ff_put_vc1_mspel_mc32_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc33_mmi()
void ff_put_vc1_mspel_mc33_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc00_mmi()
void ff_avg_vc1_mspel_mc00_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
Definition at line 1212 of file vc1dsp_mmi.c.
ff_avg_vc1_mspel_mc01_mmi()
void ff_avg_vc1_mspel_mc01_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc02_mmi()
void ff_avg_vc1_mspel_mc02_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc03_mmi()
void ff_avg_vc1_mspel_mc03_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc10_mmi()
void ff_avg_vc1_mspel_mc10_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc11_mmi()
void ff_avg_vc1_mspel_mc11_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc12_mmi()
void ff_avg_vc1_mspel_mc12_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc13_mmi()
void ff_avg_vc1_mspel_mc13_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc20_mmi()
void ff_avg_vc1_mspel_mc20_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc21_mmi()
void ff_avg_vc1_mspel_mc21_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc22_mmi()
void ff_avg_vc1_mspel_mc22_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc23_mmi()
void ff_avg_vc1_mspel_mc23_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc30_mmi()
void ff_avg_vc1_mspel_mc30_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc31_mmi()
void ff_avg_vc1_mspel_mc31_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc32_mmi()
void ff_avg_vc1_mspel_mc32_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc33_mmi()
void ff_avg_vc1_mspel_mc33_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc00_16_mmi()
void ff_put_vc1_mspel_mc00_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
Definition at line 1207 of file vc1dsp_mmi.c.
ff_put_vc1_mspel_mc01_16_mmi()
void ff_put_vc1_mspel_mc01_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc02_16_mmi()
void ff_put_vc1_mspel_mc02_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc03_16_mmi()
void ff_put_vc1_mspel_mc03_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc10_16_mmi()
void ff_put_vc1_mspel_mc10_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc11_16_mmi()
void ff_put_vc1_mspel_mc11_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc12_16_mmi()
void ff_put_vc1_mspel_mc12_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc13_16_mmi()
void ff_put_vc1_mspel_mc13_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc20_16_mmi()
void ff_put_vc1_mspel_mc20_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc21_16_mmi()
void ff_put_vc1_mspel_mc21_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc22_16_mmi()
void ff_put_vc1_mspel_mc22_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc23_16_mmi()
void ff_put_vc1_mspel_mc23_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc30_16_mmi()
void ff_put_vc1_mspel_mc30_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc31_16_mmi()
void ff_put_vc1_mspel_mc31_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc32_16_mmi()
void ff_put_vc1_mspel_mc32_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_put_vc1_mspel_mc33_16_mmi()
void ff_put_vc1_mspel_mc33_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc00_16_mmi()
void ff_avg_vc1_mspel_mc00_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
Definition at line 1217 of file vc1dsp_mmi.c.
ff_avg_vc1_mspel_mc01_16_mmi()
void ff_avg_vc1_mspel_mc01_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc02_16_mmi()
void ff_avg_vc1_mspel_mc02_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc03_16_mmi()
void ff_avg_vc1_mspel_mc03_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc10_16_mmi()
void ff_avg_vc1_mspel_mc10_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc11_16_mmi()
void ff_avg_vc1_mspel_mc11_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc12_16_mmi()
void ff_avg_vc1_mspel_mc12_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc13_16_mmi()
void ff_avg_vc1_mspel_mc13_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc20_16_mmi()
void ff_avg_vc1_mspel_mc20_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc21_16_mmi()
void ff_avg_vc1_mspel_mc21_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc22_16_mmi()
void ff_avg_vc1_mspel_mc22_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc23_16_mmi()
void ff_avg_vc1_mspel_mc23_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc30_16_mmi()
void ff_avg_vc1_mspel_mc30_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc31_16_mmi()
void ff_avg_vc1_mspel_mc31_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc32_16_mmi()
void ff_avg_vc1_mspel_mc32_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_avg_vc1_mspel_mc33_16_mmi()
void ff_avg_vc1_mspel_mc33_16_mmi (uint8_t * dst, const uint8_t * src, ptrdiff_t stride, int rnd)
ff_vc1_inv_trans_8x8_mmi()
void ff_vc1_inv_trans_8x8_mmi (int16_t block[64])
Referenced by ff_vc1_inv_trans_8x8_dc_mmi().
ff_vc1_inv_trans_8x4_mmi()
void ff_vc1_inv_trans_8x4_mmi (uint8_t * dest, int linesize, int16_t * block)
Referenced by ff_vc1_inv_trans_8x4_dc_mmi().
ff_vc1_inv_trans_4x8_mmi()
void ff_vc1_inv_trans_4x8_mmi (uint8_t * dest, int linesize, int16_t * block)
Referenced by ff_vc1_inv_trans_4x8_dc_mmi().
ff_vc1_inv_trans_4x4_mmi()
void ff_vc1_inv_trans_4x4_mmi (uint8_t * dest, int linesize, int16_t * block)
Definition at line 889 of file vc1dsp_mmi.c.
ff_vc1_inv_trans_4x4_dc_mmi()
void ff_vc1_inv_trans_4x4_dc_mmi (uint8_t * dest, int linesize, int16_t * block)
Definition at line 841 of file vc1dsp_mmi.c.
ff_vc1_inv_trans_4x8_dc_mmi()
void ff_vc1_inv_trans_4x8_dc_mmi (uint8_t * dest, int linesize, int16_t * block)
Definition at line 602 of file vc1dsp_mmi.c.
ff_vc1_inv_trans_8x4_dc_mmi()
void ff_vc1_inv_trans_8x4_dc_mmi (uint8_t * dest, int linesize, int16_t * block)
Definition at line 371 of file vc1dsp_mmi.c.
ff_vc1_inv_trans_8x8_dc_mmi()
void ff_vc1_inv_trans_8x8_dc_mmi (uint8_t * dest, int linesize, int16_t * block)
Definition at line 144 of file vc1dsp_mmi.c.
ff_vc1_v_overlap_mmi()
void ff_vc1_v_overlap_mmi (uint8_t * src, int stride)
Definition at line 1049 of file vc1dsp_mmi.c.
ff_vc1_h_overlap_mmi()
void ff_vc1_h_overlap_mmi (uint8_t * src, int stride)
Definition at line 999 of file vc1dsp_mmi.c.
ff_vc1_v_s_overlap_mmi()
void ff_vc1_v_s_overlap_mmi (int16_t * top, int16_t * bottom)
Definition at line 1072 of file vc1dsp_mmi.c.
ff_vc1_h_s_overlap_mmi()
void ff_vc1_h_s_overlap_mmi (int16_t * left, int16_t * right)
Definition at line 1022 of file vc1dsp_mmi.c.
ff_vc1_v_loop_filter4_mmi()
void ff_vc1_v_loop_filter4_mmi (uint8_t * src, int stride, int pq)
Definition at line 1172 of file vc1dsp_mmi.c.
ff_vc1_h_loop_filter4_mmi()
void ff_vc1_h_loop_filter4_mmi (uint8_t * src, int stride, int pq)
Definition at line 1177 of file vc1dsp_mmi.c.
ff_vc1_v_loop_filter8_mmi()
void ff_vc1_v_loop_filter8_mmi (uint8_t * src, int stride, int pq)
Definition at line 1182 of file vc1dsp_mmi.c.
ff_vc1_h_loop_filter8_mmi()
void ff_vc1_h_loop_filter8_mmi (uint8_t * src, int stride, int pq)
Definition at line 1187 of file vc1dsp_mmi.c.
ff_vc1_v_loop_filter16_mmi()
void ff_vc1_v_loop_filter16_mmi (uint8_t * src, int stride, int pq)
Definition at line 1192 of file vc1dsp_mmi.c.
ff_vc1_h_loop_filter16_mmi()
void ff_vc1_h_loop_filter16_mmi (uint8_t * src, int stride, int pq)
Definition at line 1197 of file vc1dsp_mmi.c.
ff_put_no_rnd_vc1_chroma_mc8_mmi()
void ff_put_no_rnd_vc1_chroma_mc8_mmi (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Definition at line 1861 of file vc1dsp_mmi.c.
ff_put_no_rnd_vc1_chroma_mc4_mmi()
void ff_put_no_rnd_vc1_chroma_mc4_mmi (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Definition at line 1916 of file vc1dsp_mmi.c.
ff_avg_no_rnd_vc1_chroma_mc8_mmi()
void ff_avg_no_rnd_vc1_chroma_mc8_mmi (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Definition at line 1969 of file vc1dsp_mmi.c.
ff_avg_no_rnd_vc1_chroma_mc4_mmi()
void ff_avg_no_rnd_vc1_chroma_mc4_mmi (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Definition at line 2027 of file vc1dsp_mmi.c.