FFmpeg: libavcodec/vc1dsp.h File Reference
vc1dsp.h File Reference
VC-1 and WMV3 decoder.
#include "hpeldsp.h"
#include "h264chroma.h"
Data Structures
struct VC1DSPContext
Typedefs
typedef void(* vc1op_pixels_func) (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
Functions
void ff_vc1dsp_init (VC1DSPContext *c)
void ff_vc1dsp_init_aarch64 (VC1DSPContext *dsp)
void ff_vc1dsp_init_arm (VC1DSPContext *dsp)
void ff_vc1dsp_init_ppc (VC1DSPContext *c)
void ff_vc1dsp_init_x86 (VC1DSPContext *dsp)
void ff_vc1dsp_init_mips (VC1DSPContext *dsp)
Detailed Description
VC-1 and WMV3 decoder.
Definition in file vc1dsp.h.
Typedef Documentation
vc1op_pixels_func
typedef void(* vc1op_pixels_func) (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
Definition at line 33 of file vc1dsp.h.
Function Documentation
ff_vc1dsp_init()
void ff_vc1dsp_init (VC1DSPContext * c)
Definition at line 968 of file vc1dsp.c.
Referenced by ff_vc1_init_common(), and wmv9_init().
ff_vc1dsp_init_aarch64()
void ff_vc1dsp_init_aarch64 (VC1DSPContext * dsp)
Definition at line 37 of file vc1dsp_init_aarch64.c.
Referenced by ff_vc1dsp_init().
ff_vc1dsp_init_arm()
void ff_vc1dsp_init_arm (VC1DSPContext * dsp)
Definition at line 27 of file vc1dsp_init_arm.c.
Referenced by ff_vc1dsp_init().
ff_vc1dsp_init_ppc()
void ff_vc1dsp_init_ppc (VC1DSPContext * c)
Definition at line 352 of file vc1dsp_altivec.c.
Referenced by ff_vc1dsp_init().
ff_vc1dsp_init_x86()
void ff_vc1dsp_init_x86 (VC1DSPContext * dsp)
Definition at line 105 of file vc1dsp_init.c.
Referenced by ff_vc1dsp_init().
ff_vc1dsp_init_mips()
void ff_vc1dsp_init_mips (VC1DSPContext * dsp)
Definition at line 103 of file vc1dsp_init_mips.c.
Referenced by ff_vc1dsp_init().