FFmpeg: libavcodec/x86/vc1dsp_init.c File Reference
vc1dsp_init.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/x86/cpu.h"
#include "libavutil/x86/asm.h"
#include "libavcodec/vc1dsp.h"
#include "fpel.h"
#include "vc1dsp.h"
#include "config.h"
Macros
#define LOOP_FILTER(EXT)
#define ASSIGN_LF(EXT)
Functions
void ff_put_vc1_chroma_mc8_nornd_mmx (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_avg_vc1_chroma_mc8_nornd_mmxext (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_avg_vc1_chroma_mc8_nornd_3dnow (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_put_vc1_chroma_mc8_nornd_ssse3 (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_avg_vc1_chroma_mc8_nornd_ssse3 (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_vc1_inv_trans_4x4_dc_mmxext (uint8_t *dest, int linesize, int16_t *block)
void ff_vc1_inv_trans_4x8_dc_mmxext (uint8_t *dest, int linesize, int16_t *block)
void ff_vc1_inv_trans_8x4_dc_mmxext (uint8_t *dest, int linesize, int16_t *block)
void ff_vc1_inv_trans_8x8_dc_mmxext (uint8_t *dest, int linesize, int16_t *block)
av_cold void ff_vc1dsp_init_x86 (VC1DSPContext *dsp)
Macro Definition Documentation
LOOP_FILTER
#define LOOP_FILTER (EXT)
Value:
void ff_vc1_v_loop_filter4_ ## EXT(uint8_t *src, int stride, int pq); \
void ff_vc1_h_loop_filter4_ ## EXT(uint8_t *src, int stride, int pq); \
void ff_vc1_v_loop_filter8_ ## EXT(uint8_t *src, int stride, int pq); \
void ff_vc1_h_loop_filter8_ ## EXT(uint8_t *src, int stride, int pq); \
\
static void vc1_v_loop_filter16_ ## EXT(uint8_t *src, int stride, int pq) \
{ \
    ff_vc1_v_loop_filter8_ ## EXT(src,   stride, pq); \
    ff_vc1_v_loop_filter8_ ## EXT(src+8, stride, pq); \
} \
\
static void vc1_h_loop_filter16_ ## EXT(uint8_t *src, int stride, int pq) \
{ \
    ff_vc1_h_loop_filter8_ ## EXT(src,          stride, pq); \
    ff_vc1_h_loop_filter8_ ## EXT(src+8*stride, stride, pq); \
}
Definition at line 36 of file vc1dsp_init.c.
ASSIGN_LF
#define ASSIGN_LF (EXT)
Value:
dsp->vc1_v_loop_filter4  = ff_vc1_v_loop_filter4_ ## EXT; \
        dsp->vc1_h_loop_filter4  = ff_vc1_h_loop_filter4_ ## EXT; \
        dsp->vc1_v_loop_filter8  = ff_vc1_v_loop_filter8_ ## EXT; \
        dsp->vc1_h_loop_filter8  = ff_vc1_h_loop_filter8_ ## EXT; \
        dsp->vc1_v_loop_filter16 = vc1_v_loop_filter16_ ## EXT; \
        dsp->vc1_h_loop_filter16 = vc1_h_loop_filter16_ ## EXT
Referenced by ff_vc1dsp_init_x86().
Function Documentation
ff_put_vc1_chroma_mc8_nornd_mmx()
void ff_put_vc1_chroma_mc8_nornd_mmx (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_vc1dsp_init_x86().
ff_avg_vc1_chroma_mc8_nornd_mmxext()
void ff_avg_vc1_chroma_mc8_nornd_mmxext (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_vc1dsp_init_x86().
ff_avg_vc1_chroma_mc8_nornd_3dnow()
void ff_avg_vc1_chroma_mc8_nornd_3dnow (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_vc1dsp_init_x86().
ff_put_vc1_chroma_mc8_nornd_ssse3()
void ff_put_vc1_chroma_mc8_nornd_ssse3 (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_vc1dsp_init_x86().
ff_avg_vc1_chroma_mc8_nornd_ssse3()
void ff_avg_vc1_chroma_mc8_nornd_ssse3 (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_vc1dsp_init_x86().
ff_vc1_inv_trans_4x4_dc_mmxext()
void ff_vc1_inv_trans_4x4_dc_mmxext (uint8_t * dest, int linesize, int16_t * block)
Referenced by ff_vc1dsp_init_x86().
ff_vc1_inv_trans_4x8_dc_mmxext()
void ff_vc1_inv_trans_4x8_dc_mmxext (uint8_t * dest, int linesize, int16_t * block)
Referenced by ff_vc1dsp_init_x86().
ff_vc1_inv_trans_8x4_dc_mmxext()
void ff_vc1_inv_trans_8x4_dc_mmxext (uint8_t * dest, int linesize, int16_t * block)
Referenced by ff_vc1dsp_init_x86().
ff_vc1_inv_trans_8x8_dc_mmxext()
void ff_vc1_inv_trans_8x8_dc_mmxext (uint8_t * dest, int linesize, int16_t * block)
Referenced by ff_vc1dsp_init_x86().
ff_vc1dsp_init_x86()
av_cold void ff_vc1dsp_init_x86 (VC1DSPContext * dsp)
Definition at line 105 of file vc1dsp_init.c.
Referenced by ff_vc1dsp_init().