FFmpeg: libavcodec/vc2enc_dwt.c File Reference
vc2enc_dwt.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/mem.h"
#include "vc2enc_dwt.h"
Functions
static av_always_inline void deinterleave (dwtcoef *linell, ptrdiff_t stride, int width, int height, dwtcoef *synthl)
static void vc2_subband_dwt_97 (VC2TransformContext *t, dwtcoef *data, ptrdiff_t stride, int width, int height)
static void vc2_subband_dwt_53 (VC2TransformContext *t, dwtcoef *data, ptrdiff_t stride, int width, int height)
static av_always_inline void dwt_haar (VC2TransformContext *t, dwtcoef *data, ptrdiff_t stride, int width, int height, const int s)
static void vc2_subband_dwt_haar (VC2TransformContext *t, dwtcoef *data, ptrdiff_t stride, int width, int height)
static void vc2_subband_dwt_haar_shift (VC2TransformContext *t, dwtcoef *data, ptrdiff_t stride, int width, int height)
av_cold int ff_vc2enc_init_transforms (VC2TransformContext *s, int p_width, int p_height)
av_cold void ff_vc2enc_free_transforms (VC2TransformContext *s)
Function Documentation
deinterleave()
static av_always_inline void deinterleave (dwtcoef * linell, ptrdiff_t stride, int width, int height, dwtcoef * synthl) static
Definition at line 30 of file vc2enc_dwt.c.
Referenced by dwt_haar(), vc2_subband_dwt_53(), and vc2_subband_dwt_97().
vc2_subband_dwt_97()
static void vc2_subband_dwt_97 (VC2TransformContext * t, dwtcoef * data, ptrdiff_t stride, int width, int height) static
Definition at line 55 of file vc2enc_dwt.c.
Referenced by ff_vc2enc_init_transforms().
vc2_subband_dwt_53()
static void vc2_subband_dwt_53 (VC2TransformContext * t, dwtcoef * data, ptrdiff_t stride, int width, int height) static
Definition at line 140 of file vc2enc_dwt.c.
Referenced by ff_vc2enc_init_transforms().
dwt_haar()
static av_always_inline void dwt_haar (VC2TransformContext * t, dwtcoef * data, ptrdiff_t stride, int width, int height, const int s) static
Definition at line 214 of file vc2enc_dwt.c.
Referenced by vc2_subband_dwt_haar(), and vc2_subband_dwt_haar_shift().
vc2_subband_dwt_haar()
static void vc2_subband_dwt_haar (VC2TransformContext * t, dwtcoef * data, ptrdiff_t stride, int width, int height) static
Definition at line 246 of file vc2enc_dwt.c.
Referenced by ff_vc2enc_init_transforms().
vc2_subband_dwt_haar_shift()
static void vc2_subband_dwt_haar_shift (VC2TransformContext * t, dwtcoef * data, ptrdiff_t stride, int width, int height) static
Definition at line 252 of file vc2enc_dwt.c.
Referenced by ff_vc2enc_init_transforms().
ff_vc2enc_init_transforms()
av_cold int ff_vc2enc_init_transforms (VC2TransformContext * s, int p_width, int p_height)
Definition at line 258 of file vc2enc_dwt.c.
Referenced by vc2_encode_init().
ff_vc2enc_free_transforms()
av_cold void ff_vc2enc_free_transforms (VC2TransformContext * s)
Definition at line 272 of file vc2enc_dwt.c.
Referenced by vc2_encode_end().