FFmpeg: libavcodec/vda_h264.c File Reference
vda_h264.c File Reference
#include <CoreFoundation/CFDictionary.h>
#include <CoreFoundation/CFNumber.h>
#include <CoreFoundation/CFData.h>
#include "vda.h"
#include "libavutil/avutil.h"
#include "h264dec.h"
#include "internal.h"
#include "vda_vt_internal.h"
Data Structures
struct vda_buffer
Functions
static void vda_decoder_callback (void *vda_hw_ctx, CFDictionaryRef user_info, OSStatus status, uint32_t infoFlags, CVImageBufferRef image_buffer)
static int vda_sync_decode (VTContext *ctx, struct vda_context *vda_ctx)
static int vda_old_h264_start_frame (AVCodecContext *avctx, av_unused const uint8_t *buffer, av_unused uint32_t size)
static int vda_old_h264_decode_slice (AVCodecContext *avctx, const uint8_t *buffer, uint32_t size)
static void vda_h264_release_buffer (void *opaque, uint8_t *data)
static int vda_old_h264_end_frame (AVCodecContext *avctx)
int ff_vda_create_decoder (struct vda_context *vda_ctx, uint8_t *extradata, int extradata_size)
Create the video decoder.
int ff_vda_destroy_decoder (struct vda_context *vda_ctx)
Destroy the video decoder.
void ff_vda_output_callback (void *opaque, CFDictionaryRef user_info, OSStatus status, uint32_t infoFlags, CVImageBufferRef image_buffer)
static int vda_h264_end_frame (AVCodecContext *avctx)
int ff_vda_default_init (AVCodecContext *avctx)
Variables
AVHWAccel ff_h264_vda_old_hwaccel
AVHWAccel ff_h264_vda_hwaccel
Function Documentation
vda_decoder_callback()
static void vda_decoder_callback (void * vda_hw_ctx, CFDictionaryRef user_info, OSStatus status, uint32_t infoFlags, CVImageBufferRef image_buffer) static
Definition at line 38 of file vda_h264.c.
Referenced by ff_vda_create_decoder().
vda_sync_decode()
static int vda_sync_decode (VTContext * ctx, struct vda_context * vda_ctx) static
< kVDADecoderFlush_emitFrames
Definition at line 58 of file vda_h264.c.
Referenced by vda_old_h264_end_frame().
vda_old_h264_start_frame()
static int vda_old_h264_start_frame (AVCodecContext * avctx, av_unused const uint8_t * buffer, av_unused uint32_t size) static
Definition at line 79 of file vda_h264.c.
vda_old_h264_decode_slice()
static int vda_old_h264_decode_slice (AVCodecContext * avctx, const uint8_t * buffer, uint32_t size) static
Definition at line 94 of file vda_h264.c.
vda_h264_release_buffer()
static void vda_h264_release_buffer (void * opaque, uint8_t * data) static
Definition at line 121 of file vda_h264.c.
Referenced by vda_old_h264_end_frame().
vda_old_h264_end_frame()
static int vda_old_h264_end_frame (AVCodecContext * avctx) static
Definition at line 128 of file vda_h264.c.
ff_vda_output_callback()
void ff_vda_output_callback (void * opaque, CFDictionaryRef user_info, OSStatus status, uint32_t infoFlags, CVImageBufferRef image_buffer)
Definition at line 273 of file vda_h264.c.
Referenced by ff_vda_default_init().
vda_h264_end_frame()
static int vda_h264_end_frame (AVCodecContext * avctx) static
< kVDADecoderFlush_emitFrames
Definition at line 294 of file vda_h264.c.
ff_vda_default_init()
int ff_vda_default_init (AVCodecContext * avctx)
Definition at line 330 of file vda_h264.c.
Variable Documentation
ff_h264_vda_old_hwaccel
AVHWAccel ff_h264_vda_old_hwaccel
Initial value:
= {
    .name           = "h264_vda",
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_H264,
    .pix_fmt        = AV_PIX_FMT_VDA_VLD,
    .start_frame    = vda_old_h264_start_frame,
    .decode_slice   = vda_old_h264_decode_slice,
    .end_frame      = vda_old_h264_end_frame,
    .uninit         = ff_videotoolbox_uninit,
    .priv_data_size = sizeof(VTContext),
}
Definition at line 261 of file vda_h264.c.
ff_h264_vda_hwaccel
AVHWAccel ff_h264_vda_hwaccel
Initial value:
= {
    .name           = "h264_vda",
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_H264,
    .pix_fmt        = AV_PIX_FMT_VDA,
    .alloc_frame    = ff_videotoolbox_alloc_frame,
    .start_frame    = ff_videotoolbox_h264_start_frame,
    .decode_slice   = ff_videotoolbox_h264_decode_slice,
    .end_frame      = vda_h264_end_frame,
    .uninit         = ff_videotoolbox_uninit,
    .priv_data_size = sizeof(VTContext),
}
Definition at line 414 of file vda_h264.c.