FFmpeg: libavcodec/vda_h264_dec.c File Reference
vda_h264_dec.c File Reference
H.264 decoder via VDA.
#include <string.h>
#include <CoreFoundation/CoreFoundation.h>
#include "vda.h"
#include "h264dec.h"
#include "avcodec.h"
Data Structures
struct VDADecoderContext
struct VDABufferContext
Macros
#define kCFCoreFoundationVersionNumber10_7 635.00
Functions
static enum AVPixelFormat get_format (struct AVCodecContext *avctx, const enum AVPixelFormat *fmt)
static void release_buffer (void *opaque, uint8_t *data)
static int get_buffer2 (AVCodecContext *avctx, AVFrame *pic, int flag)
static void set_context (AVCodecContext *avctx)
static void restore_context (AVCodecContext *avctx)
static int vdadec_decode (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int vdadec_close (AVCodecContext *avctx)
static av_cold int vdadec_init (AVCodecContext *avctx)
static void vdadec_flush (AVCodecContext *avctx)
Variables
AVCodec ff_h264_decoder
AVCodec ff_h264_vda_decoder
static enum AVPixelFormat vda_pixfmts_prior_10_7 []
static enum AVPixelFormat vda_pixfmts []
Detailed Description
H.264 decoder via VDA.
Author
Xidorn Quan quanx.nosp@m.unzh.nosp@m.en@gm.nosp@m.ail..nosp@m.com
Definition in file vda_h264_dec.c.
Macro Definition Documentation
kCFCoreFoundationVersionNumber10_7
#define kCFCoreFoundationVersionNumber10_7 635.00
Definition at line 35 of file vda_h264_dec.c.
Referenced by vdadec_init().
Function Documentation
get_format()
static enum AVPixelFormat get_format (struct AVCodecContext * avctx, const enum AVPixelFormat * fmt) static
Definition at line 67 of file vda_h264_dec.c.
Referenced by set_context().
release_buffer()
static void release_buffer (void * opaque, uint8_t * data) static
Definition at line 77 of file vda_h264_dec.c.
Referenced by get_buffer2().
get_buffer2()
static int get_buffer2 (AVCodecContext * avctx, AVFrame * pic, int flag) static
Definition at line 85 of file vda_h264_dec.c.
Referenced by set_context().
set_context()
static void set_context (AVCodecContext * avctx) inline static
Definition at line 99 of file vda_h264_dec.c.
Referenced by vdadec_close(), vdadec_decode(), vdadec_flush(), and vdadec_init().
restore_context()
static void restore_context (AVCodecContext * avctx) inline static
Definition at line 110 of file vda_h264_dec.c.
Referenced by vdadec_close(), vdadec_decode(), vdadec_flush(), and vdadec_init().
vdadec_decode()
static int vdadec_decode (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 118 of file vda_h264_dec.c.
vdadec_close()
static av_cold int vdadec_close (AVCodecContext * avctx) static
Definition at line 154 of file vda_h264_dec.c.
Referenced by vdadec_init().
vdadec_init()
static av_cold int vdadec_init (AVCodecContext * avctx) static
Definition at line 168 of file vda_h264_dec.c.
vdadec_flush()
static void vdadec_flush (AVCodecContext * avctx) static
Definition at line 245 of file vda_h264_dec.c.
Variable Documentation
ff_h264_decoder
AVCodec ff_h264_decoder
Definition at line 1212 of file h264dec.c.
ff_h264_vda_decoder
AVCodec ff_h264_vda_decoder
Initial value:
= {
    .name           = "h264_vda",
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_H264,
    .priv_data_size = sizeof(VDADecoderContext),
    .init           = vdadec_init,
    .close          = vdadec_close,
    .decode         = vdadec_decode,
    .capabilities   = AV_CODEC_CAP_DELAY,
    .flush          = vdadec_flush,
    .long_name      = NULL_IF_CONFIG_SMALL("H.264 (VDA acceleration)"),
}
Definition at line 252 of file vda_h264_dec.c.
vda_pixfmts_prior_10_7
enum AVPixelFormat vda_pixfmts_prior_10_7[] static
Initial value:
= {
    AV_PIX_FMT_UYVY422,
    AV_PIX_FMT_YUV420P,
    AV_PIX_FMT_NONE
}
Definition at line 40 of file vda_h264_dec.c.
Referenced by vdadec_init().
vda_pixfmts
enum AVPixelFormat vda_pixfmts[] static
Initial value:
= {
    AV_PIX_FMT_UYVY422,
    AV_PIX_FMT_YUYV422,
    AV_PIX_FMT_NV12,
    AV_PIX_FMT_YUV420P,
    AV_PIX_FMT_NONE
}
Definition at line 46 of file vda_h264_dec.c.
Referenced by vdadec_init().