FFmpeg: libavcodec/vda_vt_internal.h File Reference
vda_vt_internal.h File Reference
Data Structures
struct VTContext
Functions
void ff_vda_output_callback (void *vda_hw_ctx, CFDictionaryRef user_info, OSStatus status, uint32_t infoFlags, CVImageBufferRef image_buffer)
int ff_vda_default_init (AVCodecContext *avctx)
void ff_vda_default_free (AVCodecContext *avctx)
int ff_videotoolbox_alloc_frame (AVCodecContext *avctx, AVFrame *frame)
int ff_videotoolbox_uninit (AVCodecContext *avctx)
int ff_videotoolbox_buffer_create (VTContext *vtctx, AVFrame *frame)
int ff_videotoolbox_h264_start_frame (AVCodecContext *avctx, const uint8_t *buffer, uint32_t size)
int ff_videotoolbox_h264_decode_slice (AVCodecContext *avctx, const uint8_t *buffer, uint32_t size)
CFDataRef ff_videotoolbox_avcc_extradata_create (AVCodecContext *avctx)
Function Documentation
ff_vda_output_callback()
void ff_vda_output_callback (void * vda_hw_ctx, CFDictionaryRef user_info, OSStatus status, uint32_t infoFlags, CVImageBufferRef image_buffer)
Definition at line 273 of file vda_h264.c.
Referenced by ff_vda_default_init().
ff_vda_default_init()
int ff_vda_default_init (AVCodecContext * avctx)
Definition at line 330 of file vda_h264.c.
ff_vda_default_free()
void ff_vda_default_free (AVCodecContext * avctx)
ff_videotoolbox_alloc_frame()
int ff_videotoolbox_alloc_frame (AVCodecContext * avctx, AVFrame * frame)
Definition at line 67 of file videotoolbox.c.
Referenced by ff_videotoolbox_uninit().
ff_videotoolbox_uninit()
int ff_videotoolbox_uninit (AVCodecContext * avctx)
Definition at line 177 of file videotoolbox.c.
ff_videotoolbox_buffer_create()
int ff_videotoolbox_buffer_create (VTContext * vtctx, AVFrame * frame)
Definition at line 115 of file videotoolbox.c.
Referenced by ff_videotoolbox_uninit(), and vda_h264_end_frame().
ff_videotoolbox_h264_start_frame()
int ff_videotoolbox_h264_start_frame (AVCodecContext * avctx, const uint8_t * buffer, uint32_t size)
Definition at line 134 of file videotoolbox.c.
Referenced by ff_videotoolbox_uninit().
ff_videotoolbox_h264_decode_slice()
int ff_videotoolbox_h264_decode_slice (AVCodecContext * avctx, const uint8_t * buffer, uint32_t size)
Definition at line 150 of file videotoolbox.c.
Referenced by ff_videotoolbox_uninit().
ff_videotoolbox_avcc_extradata_create()
CFDataRef ff_videotoolbox_avcc_extradata_create (AVCodecContext * avctx)
Definition at line 82 of file videotoolbox.c.
Referenced by ff_vda_default_init(), and ff_videotoolbox_uninit().