FFmpeg: libavcodec/vdpau_compat.h File Reference
vdpau_compat.h File Reference
#include <stdint.h>
#include "h264dec.h"
#include "mpeg4video.h"
Functions
void ff_vdpau_add_data_chunk (uint8_t *data, const uint8_t *buf, int buf_size)
void ff_vdpau_mpeg_picture_complete (MpegEncContext *s, const uint8_t *buf, int buf_size, int slice_count)
void ff_vdpau_h264_picture_start (H264Context *h)
void ff_vdpau_h264_set_reference_frames (H264Context *h)
void ff_vdpau_h264_picture_complete (H264Context *h)
void ff_vdpau_vc1_decode_picture (MpegEncContext *s, const uint8_t *buf, int buf_size)
void ff_vdpau_mpeg4_decode_picture (Mpeg4DecContext *s, const uint8_t *buf, int buf_size)
Function Documentation
ff_vdpau_add_data_chunk()
void ff_vdpau_add_data_chunk (uint8_t * data, const uint8_t * buf, int buf_size)
Referenced by decode_nal_units(), and ff_vdpau_add_buffer().
ff_vdpau_mpeg_picture_complete()
void ff_vdpau_mpeg_picture_complete (MpegEncContext * s, const uint8_t * buf, int buf_size, int slice_count)
Referenced by decode_chunks(), and ff_vdpau_add_buffer().
ff_vdpau_h264_picture_start()
void ff_vdpau_h264_picture_start (H264Context * h)
Referenced by decode_nal_units(), and ff_vdpau_add_buffer().
ff_vdpau_h264_set_reference_frames()
void ff_vdpau_h264_set_reference_frames (H264Context * h)
Referenced by ff_h264_field_end(), and ff_vdpau_add_buffer().
ff_vdpau_h264_picture_complete()
void ff_vdpau_h264_picture_complete (H264Context * h)
Referenced by ff_h264_field_end(), and ff_vdpau_add_buffer().
ff_vdpau_vc1_decode_picture()
void ff_vdpau_vc1_decode_picture (MpegEncContext * s, const uint8_t * buf, int buf_size)
Referenced by ff_vdpau_add_buffer(), and vc1_decode_frame().
ff_vdpau_mpeg4_decode_picture()
void ff_vdpau_mpeg4_decode_picture (Mpeg4DecContext * s, const uint8_t * buf, int buf_size)
Referenced by ff_h263_decode_frame(), and ff_vdpau_add_buffer().