FFmpeg: libavcodec/vdpau_h264.c File Reference
vdpau_h264.c File Reference
#include <vdpau/vdpau.h>
#include "avcodec.h"
#include "internal.h"
#include "h264dec.h"
#include "h264_ps.h"
#include "mpegutils.h"
#include "vdpau.h"
#include "vdpau_internal.h"
Macros
#define H264_RF_COUNT FF_ARRAY_ELEMS(info->referenceFrames)
Functions
static int32_t h264_foc (int foc)
static void vdpau_h264_clear_rf (VdpReferenceFrameH264 *rf)
static void vdpau_h264_set_rf (VdpReferenceFrameH264 *rf, H264Picture *pic, int pic_structure)
static void vdpau_h264_set_reference_frames (AVCodecContext *avctx)
static int vdpau_h264_start_frame (AVCodecContext *avctx, const uint8_t *buffer, uint32_t size)
static int vdpau_h264_decode_slice (AVCodecContext *avctx, const uint8_t *buffer, uint32_t size)
static int vdpau_h264_end_frame (AVCodecContext *avctx)
static int vdpau_h264_init (AVCodecContext *avctx)
Variables
static const uint8_t start_code_prefix [3] = { 0x00, 0x00, 0x01 }
AVHWAccel ff_h264_vdpau_hwaccel
Macro Definition Documentation
H264_RF_COUNT
#define H264_RF_COUNT FF_ARRAY_ELEMS(info->referenceFrames)
Referenced by ff_vdpau_add_buffer(), and vdpau_h264_set_reference_frames().
Function Documentation
h264_foc()
static int32_t h264_foc (int foc) static
Definition at line 34 of file vdpau_h264.c.
Referenced by vdpau_h264_set_rf(), and vdpau_h264_start_frame().
vdpau_h264_clear_rf()
static void vdpau_h264_clear_rf (VdpReferenceFrameH264 * rf) static
Definition at line 41 of file vdpau_h264.c.
Referenced by vdpau_h264_set_reference_frames().
vdpau_h264_set_rf()
static void vdpau_h264_set_rf (VdpReferenceFrameH264 * rf, H264Picture * pic, int pic_structure) static
Definition at line 52 of file vdpau_h264.c.
Referenced by vdpau_h264_set_reference_frames().
vdpau_h264_set_reference_frames()
static void vdpau_h264_set_reference_frames (AVCodecContext * avctx) static
Definition at line 69 of file vdpau_h264.c.
Referenced by vdpau_h264_start_frame().
vdpau_h264_start_frame()
static int vdpau_h264_start_frame (AVCodecContext * avctx, const uint8_t * buffer, uint32_t size) static
Definition at line 120 of file vdpau_h264.c.
vdpau_h264_decode_slice()
static int vdpau_h264_decode_slice (AVCodecContext * avctx, const uint8_t * buffer, uint32_t size) static
Definition at line 181 of file vdpau_h264.c.
vdpau_h264_end_frame()
static int vdpau_h264_end_frame (AVCodecContext * avctx) static
Definition at line 201 of file vdpau_h264.c.
vdpau_h264_init()
static int vdpau_h264_init (AVCodecContext * avctx) static
Definition at line 217 of file vdpau_h264.c.
Variable Documentation
start_code_prefix
const uint8_t start_code_prefix[3] = { 0x00, 0x00, 0x01 } static
Definition at line 179 of file vdpau_h264.c.
Referenced by vdpau_h264_decode_slice().
ff_h264_vdpau_hwaccel
AVHWAccel ff_h264_vdpau_hwaccel
Initial value:
= {
    .name           = "h264_vdpau",
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_H264,
    .pix_fmt        = AV_PIX_FMT_VDPAU,
    .start_frame    = vdpau_h264_start_frame,
    .end_frame      = vdpau_h264_end_frame,
    .decode_slice   = vdpau_h264_decode_slice,
    .frame_priv_data_size = sizeof(struct vdpau_picture_context),
    .init           = vdpau_h264_init,
    .uninit         = ff_vdpau_common_uninit,
    .priv_data_size = sizeof(VDPAUContext),
}
Definition at line 264 of file vdpau_h264.c.