FFmpeg: libavcodec/vdpau_internal.h File Reference
vdpau_internal.h File Reference
#include <stdint.h>
#include <vdpau/vdpau.h>
#include "libavutil/frame.h"
#include "avcodec.h"
#include "vdpau.h"
Data Structures
union VDPAUPictureInfo
struct VDPAUHWContext
struct VDPAUContext
struct vdpau_picture_context
Functions
static uintptr_t ff_vdpau_get_surface_id (AVFrame *pic)
Extract VdpVideoSurface from an AVFrame.
int ff_vdpau_common_init (AVCodecContext *avctx, VdpDecoderProfile profile, int level)
int ff_vdpau_common_uninit (AVCodecContext *avctx)
int ff_vdpau_common_start_frame (struct vdpau_picture_context *pic, const uint8_t *buffer, uint32_t size)
int ff_vdpau_common_end_frame (AVCodecContext *avctx, AVFrame *frame, struct vdpau_picture_context *pic)
int ff_vdpau_mpeg_end_frame (AVCodecContext *avctx)
int ff_vdpau_add_buffer (struct vdpau_picture_context *pic, const uint8_t *buf, uint32_t buf_size)
Function Documentation
ff_vdpau_get_surface_id()
static uintptr_t ff_vdpau_get_surface_id (AVFrame * pic) inline static
Extract VdpVideoSurface from an AVFrame.
Definition at line 36 of file vdpau_internal.h.
Referenced by ff_vdpau_common_end_frame(), vdpau_h264_set_reference_frames(), vdpau_h264_set_rf(), vdpau_hevc_start_frame(), vdpau_mpeg4_start_frame(), vdpau_mpeg_start_frame(), and vdpau_vc1_start_frame().
ff_vdpau_common_start_frame()
int ff_vdpau_common_start_frame (struct vdpau_picture_context * pic, const uint8_t * buffer, uint32_t size)
ff_vdpau_mpeg_end_frame()
int ff_vdpau_mpeg_end_frame (AVCodecContext * avctx)
Referenced by ff_vdpau_common_end_frame(), vdpau_mpeg_decode_slice(), and vdpau_vc1_init().