FFmpeg: libavfilter/vf_framepack.c File Reference
vf_framepack.c File Reference
Generate a frame packed video, by combining two views in a single surface.
#include <string.h>
#include "libavutil/common.h"
#include "libavutil/imgutils.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "libavutil/rational.h"
#include "libavutil/stereo3d.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
Data Structures
struct FramepackContext
Macros
#define LEFT 0
#define RIGHT 1
#define OFFSET(x) offsetof(FramepackContext, x)
#define V AV_OPT_FLAG_VIDEO_PARAM
Functions
static int query_formats (AVFilterContext *ctx)
static av_cold void framepack_uninit (AVFilterContext *ctx)
static int config_output (AVFilterLink *outlink)
static void horizontal_frame_pack (AVFilterLink *outlink, AVFrame *out, int interleaved)
static void vertical_frame_pack (AVFilterLink *outlink, AVFrame *out, int interleaved)
static av_always_inline void spatial_frame_pack (AVFilterLink *outlink, AVFrame *dst)
static int try_push_frame (AVFilterContext *ctx)
static int filter_frame_left (AVFilterLink *inlink, AVFrame *frame)
static int filter_frame_right (AVFilterLink *inlink, AVFrame *frame)
static int request_frame (AVFilterLink *outlink)
AVFILTER_DEFINE_CLASS (framepack)
Variables
static enum AVPixelFormat formats_supported []
static const AVOption framepack_options []
static const AVFilterPad framepack_inputs []
static const AVFilterPad framepack_outputs []
AVFilter ff_vf_framepack
Detailed Description
Generate a frame packed video, by combining two views in a single surface.
Definition in file vf_framepack.c.
Macro Definition Documentation
LEFT
#define LEFT 0
Definition at line 40 of file vf_framepack.c.
Referenced by config_output(), filter_frame_left(), framepack_uninit(), horizontal_frame_pack(), and try_push_frame().
RIGHT
#define RIGHT 1
Definition at line 41 of file vf_framepack.c.
Referenced by config_output(), filter_frame_right(), framepack_uninit(), and horizontal_frame_pack().
OFFSET
#define OFFSET (x) offsetof(FramepackContext, x)
Definition at line 364 of file vf_framepack.c.
V
#define V AV_OPT_FLAG_VIDEO_PARAM
Definition at line 365 of file vf_framepack.c.
Function Documentation
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 62 of file vf_framepack.c.
framepack_uninit()
static av_cold void framepack_uninit (AVFilterContext * ctx) static
Definition at line 71 of file vf_framepack.c.
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 80 of file vf_framepack.c.
horizontal_frame_pack()
static void horizontal_frame_pack (AVFilterLink * outlink, AVFrame * out, int interleaved) static
Definition at line 147 of file vf_framepack.c.
Referenced by spatial_frame_pack().
vertical_frame_pack()
static void vertical_frame_pack (AVFilterLink * outlink, AVFrame * out, int interleaved) static
Definition at line 212 of file vf_framepack.c.
Referenced by spatial_frame_pack().
spatial_frame_pack()
static av_always_inline void spatial_frame_pack (AVFilterLink * outlink, AVFrame * dst) static
Definition at line 251 of file vf_framepack.c.
Referenced by try_push_frame().
try_push_frame()
static int try_push_frame (AVFilterContext * ctx) static
Definition at line 305 of file vf_framepack.c.
Referenced by filter_frame_left(), filter_frame_right(), and spatial_frame_pack().
filter_frame_left()
static int filter_frame_left (AVFilterLink * inlink, AVFrame * frame) static
Definition at line 274 of file vf_framepack.c.
filter_frame_right()
static int filter_frame_right (AVFilterLink * inlink, AVFrame * frame) static
Definition at line 281 of file vf_framepack.c.
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 288 of file vf_framepack.c.
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (framepack)
Variable Documentation
formats_supported
enum AVPixelFormat formats_supported[] static
Initial value:
= {
    AV_PIX_FMT_YUV420P,  AV_PIX_FMT_YUV422P,  AV_PIX_FMT_YUV444P,
    AV_PIX_FMT_YUV410P,  AV_PIX_FMT_YUVA420P, AV_PIX_FMT_YUVJ420P,
    AV_PIX_FMT_YUVJ422P, AV_PIX_FMT_YUVJ444P, AV_PIX_FMT_YUVJ440P,
    AV_PIX_FMT_NONE
}
Definition at line 55 of file vf_framepack.c.
Referenced by query_formats().
framepack_options
const AVOption framepack_options[] static
Initial value:
= {
    { "format", "Frame pack output format", OFFSET(format), AV_OPT_TYPE_INT,
        { .i64 = AV_STEREO3D_SIDEBYSIDE }, 0, INT_MAX, .flags = V, .unit = "format" },
    { "sbs", "Views are packed next to each other", 0, AV_OPT_TYPE_CONST,
        { .i64 = AV_STEREO3D_SIDEBYSIDE }, INT_MIN, INT_MAX, .flags = V, .unit = "format" },
    { "tab", "Views are packed on top of each other", 0, AV_OPT_TYPE_CONST,
        { .i64 = AV_STEREO3D_TOPBOTTOM }, INT_MIN, INT_MAX, .flags = V, .unit = "format" },
    { "frameseq", "Views are one after the other", 0, AV_OPT_TYPE_CONST,
        { .i64 = AV_STEREO3D_FRAMESEQUENCE }, INT_MIN, INT_MAX, .flags = V, .unit = "format" },
    { "lines", "Views are interleaved by lines", 0, AV_OPT_TYPE_CONST,
        { .i64 = AV_STEREO3D_LINES }, INT_MIN, INT_MAX, .flags = V, .unit = "format" },
    { "columns", "Views are interleaved by columns", 0, AV_OPT_TYPE_CONST,
        { .i64 = AV_STEREO3D_COLUMNS }, INT_MIN, INT_MAX, .flags = V, .unit = "format" },
    { NULL },
}
Definition at line 366 of file vf_framepack.c.
framepack_inputs
const AVFilterPad framepack_inputs[] static
Initial value:
= {
    {
        .name         = "left",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame_left,
        .needs_fifo   = 1,
    },
    {
        .name         = "right",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame_right,
        .needs_fifo   = 1,
    },
    { NULL }
}
Definition at line 384 of file vf_framepack.c.
framepack_outputs
const AVFilterPad framepack_outputs[] static
Initial value:
= {
    {
        .name          = "packed",
        .type          = AVMEDIA_TYPE_VIDEO,
        .config_props  = config_output,
        .request_frame = request_frame,
    },
    { NULL }
}
Definition at line 400 of file vf_framepack.c.
ff_vf_framepack
AVFilter ff_vf_framepack
Initial value:
= {
    .name          = "framepack",
    .description   = NULL_IF_CONFIG_SMALL("Generate a frame packed stereoscopic video."),
    .priv_size     = sizeof(FramepackContext),
    .priv_class    = &framepack_class,
    .query_formats = query_formats,
    .inputs        = framepack_inputs,
    .outputs       = framepack_outputs,
    .uninit        = framepack_uninit,
}
Definition at line 410 of file vf_framepack.c.