FFmpeg: libavfilter/vf_rotate.c File Reference
vf_rotate.c File Reference
rotation filter, partially based on the tests/rotozoom.c program
#include "libavutil/avstring.h"
#include "libavutil/eval.h"
#include "libavutil/opt.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/parseutils.h"
#include "libavutil/pixdesc.h"
#include "avfilter.h"
#include "drawutils.h"
#include "internal.h"
#include "video.h"
#include <float.h>
Data Structures
struct RotContext
struct ThreadData
Macros
#define OFFSET(x) offsetof(RotContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
#define FIXP (1<<16)
#define FIXP2 (1<<20)
#define INT_PI 3294199
#define SET_SIZE_EXPR(name, opt_name)
#define TS2T(ts, tb) ((ts) == AV_NOPTS_VALUE ? NAN : (double)(ts)*av_q2d(tb))
Enumerations
enum var_name {
VAR_CH, VAR_N, VAR_NB_IN_CHANNELS, VAR_NB_OUT_CHANNELS,
VAR_T, VAR_S, VAR_VARS_NB, VAR_VALUE1,
VAR_VALUE2, VAR_VARS_NB, VAR_TB, VAR_PTS,
VAR_START_PTS, VAR_PREV_PTS, VAR_PREV_SELECTED_PTS, VAR_T,
VAR_START_T, VAR_PREV_T, VAR_PREV_SELECTED_T, VAR_PICT_TYPE,
VAR_I, VAR_P, VAR_B, VAR_S,
VAR_SI, VAR_SP, VAR_BI, VAR_PICT_TYPE_I,
VAR_PICT_TYPE_P, VAR_PICT_TYPE_B, VAR_PICT_TYPE_S, VAR_PICT_TYPE_SI,
VAR_PICT_TYPE_SP, VAR_PICT_TYPE_BI, VAR_INTERLACE_TYPE, VAR_INTERLACE_TYPE_P,
VAR_INTERLACE_TYPE_T, VAR_INTERLACE_TYPE_B, VAR_CONSUMED_SAMPLES_N, VAR_SAMPLES_N,
VAR_SAMPLE_RATE, VAR_N, VAR_SELECTED_N, VAR_PREV_SELECTED_N,
VAR_KEY, VAR_POS, VAR_SCENE, VAR_CONCATDEC_SELECT,
VAR_VARS_NB, VAR_FRAME_RATE, VAR_INTERLACED, VAR_N,
VAR_NB_CONSUMED_SAMPLES, VAR_NB_SAMPLES, VAR_POS, VAR_PREV_INPTS,
VAR_PREV_INT, VAR_PREV_OUTPTS, VAR_PREV_OUTT, VAR_PTS,
VAR_SAMPLE_RATE, VAR_STARTPTS, VAR_STARTT, VAR_T,
VAR_TB, VAR_RTCTIME, VAR_RTCSTART, VAR_S,
VAR_SR, VAR_VARS_NB, VAR_AVTB, VAR_INTB,
VAR_SR, VAR_VARS_NB, VAR_W, VAR_H,
VAR_A, VAR_DAR, VAR_SAR, VAR_HSUB,
VAR_VSUB, VARS_NB, VAR_W, VAR_H,
VAR_CW, VAR_CH, VAR_HSUB, VAR_VSUB,
VARS_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_A, VAR_SAR, VAR_DAR,
VAR_HSUB, VAR_VSUB, VAR_X, VAR_Y,
VAR_N, VAR_POS, VAR_T, VAR_VARS_NB,
VAR_DAR, VAR_HSUB, VAR_VSUB, VAR_IN_H,
VAR_IH, VAR_IN_W, VAR_IW, VAR_SAR,
VAR_X, VAR_Y, VAR_H, VAR_W,
VAR_T, VAR_MAX, VARS_NB, VAR_DAR,
VAR_HSUB, VAR_VSUB, VAR_LINE_H, VAR_LH,
VAR_MAIN_H, VAR_h, VAR_H, VAR_MAIN_W,
VAR_w, VAR_W, VAR_MAX_GLYPH_A, VAR_ASCENT,
VAR_MAX_GLYPH_D, VAR_DESCENT, VAR_MAX_GLYPH_H, VAR_MAX_GLYPH_W,
VAR_N, VAR_SAR, VAR_T, VAR_TEXT_H,
VAR_TH, VAR_TEXT_W, VAR_TW, VAR_X,
VAR_Y, VAR_PICT_TYPE, VAR_VARS_NB, VAR_N,
VAR_POS, VAR_R, VAR_T, VAR_NB,
VAR_N, VAR_PTS, VAR_R, VAR_T,
VAR_TB, VAR_NB, VAR_W, VAR_H,
VAR_VAL, VAR_MAXVAL, VAR_MINVAL, VAR_NEGVAL,
VAR_CLIPVAL, VAR_VARS_NB, VAR_W, VAR_H,
VAR_X, VAR_Y, VAR_BITDEPTHX, VAR_BITDEPTHY,
VAR_VARS_NB, VAR_MAIN_W, VAR_MW, VAR_MAIN_H,
VAR_MH, VAR_OVERLAY_W, VAR_OW, VAR_OVERLAY_H,
VAR_OH, VAR_HSUB, VAR_VSUB, VAR_X,
VAR_Y, VAR_N, VAR_POS, VAR_T,
VAR_VARS_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_X, VAR_Y, VAR_A,
VAR_SAR, VAR_DAR, VAR_HSUB, VAR_VSUB,
VARS_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_HSUB, VAR_VSUB, VAR_N,
VAR_T, VAR_VARS_NB, VAR_IN_W, VAR_IW,
VAR_IN_H, VAR_IH, VAR_OUT_W, VAR_OW,
VAR_OUT_H, VAR_OH, VAR_A, VAR_SAR,
VAR_DAR, VAR_HSUB, VAR_VSUB, VAR_OHSUB,
VAR_OVSUB, VARS_NB, VAR_PI, VAR_PHI,
VAR_E, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_A, VAR_DAR, VAR_SAR,
VARS_NB, VAR_W, VAR_H, VAR_N,
VAR_PTS, VAR_R, VAR_T, VAR_TB,
VAR_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_IN, VAR_ON, VAR_DURATION,
VAR_PDURATION, VAR_TIME, VAR_FRAME, VAR_ZOOM,
VAR_PZOOM, VAR_X, VAR_PX, VAR_Y,
VAR_PY, VAR_A, VAR_SAR, VAR_DAR,
VAR_HSUB, VAR_VSUB, VARS_NB, VAR_IN_W,
VAR_IW, VAR_IN_H, VAR_IH, VAR_OUT_W,
VAR_OW, VAR_OUT_H, VAR_OH, VAR_A,
VAR_SAR, VAR_DAR, VAR_HSUB, VAR_VSUB,
VAR_OHSUB, VAR_OVSUB, VARS_NB, VAR_X,
VAR_Y, VAR_W, VAR_H, VAR_TIME,
VAR_SPEED, VAR_TEMPO, VAR_ORDER, VAR_PATTERN,
VAR_ROW, VAR_VARS_NB
}
Functions
AVFILTER_DEFINE_CLASS (rotate)
static av_cold int init (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static double get_rotated_w (void *opaque, double angle)
static double get_rotated_h (void *opaque, double angle)
static int64_t int_sin (int64_t a)
Compute the sin of a using integer values.
static uint8_t * interpolate_bilinear8 (uint8_t *dst_color, const uint8_t *src, int src_linesize, int src_linestep, int x, int y, int max_x, int max_y)
Interpolate the color in src at position x and y using bilinear interpolation.
static uint8_t * interpolate_bilinear16 (uint8_t *dst_color, const uint8_t *src, int src_linesize, int src_linestep, int x, int y, int max_x, int max_y)
Interpolate the color in src at position x and y using bilinear interpolation.
static int config_props (AVFilterLink *outlink)
static av_always_inline void copy_elem (uint8_t *pout, const uint8_t *pin, int elem_size)
static av_always_inline void simple_rotate_internal (uint8_t *dst, const uint8_t *src, int src_linesize, int angle, int elem_size, int len)
static av_always_inline void simple_rotate (uint8_t *dst, const uint8_t *src, int src_linesize, int angle, int elem_size, int len)
static int filter_slice (AVFilterContext *ctx, void *arg, int job, int nb_jobs)
static int filter_frame (AVFilterLink *inlink, AVFrame *in)
static int process_command (AVFilterContext *ctx, const char *cmd, const char *args, char *res, int res_len, int flags)
Variables
static const char *const var_names []
static const AVOption rotate_options []
static double(*const func1 [])(void *, double)
static const char *const func1_names []
static const AVFilterPad rotate_inputs []
static const AVFilterPad rotate_outputs []
AVFilter ff_vf_rotate
Detailed Description
rotation filter, partially based on the tests/rotozoom.c program
Definition in file vf_rotate.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(RotContext, x)
Definition at line 95 of file vf_rotate.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 96 of file vf_rotate.c.
FIXP
#define FIXP (1<<16)
Definition at line 201 of file vf_rotate.c.
Referenced by filter_frame(), and filter_slice().
FIXP2
#define FIXP2 (1<<20)
Definition at line 202 of file vf_rotate.c.
Referenced by int_sin().
INT_PI
#define INT_PI 3294199
Definition at line 203 of file vf_rotate.c.
Referenced by filter_frame(), and int_sin().
SET_SIZE_EXPR
#define SET_SIZE_EXPR (name, opt_name)
Value:
do {                                         \
    ret = av_expr_parse_and_eval(&res, expr = rot->name##_expr_str,                \
                                 var_names, rot->var_values,                       \
                                 func1_names, func1, NULL, NULL, rot, 0, ctx);     \
    if (ret < 0 || isnan(res) || isinf(res) || res <= 0) {                         \
        av_log(ctx, AV_LOG_ERROR,                                                  \
               "Error parsing or evaluating expression for option %s: "            \
               "invalid expression '%s' or non-positive or indefinite value %f\n", \
               opt_name, expr, res);                                               \
        return ret;                                                                \
    }                                                                              \
} while (0)
Referenced by config_props().
TS2T
#define TS2T (ts, tb) ((ts) == AV_NOPTS_VALUE ? NAN : (double)(ts)*av_q2d(tb))
Definition at line 417 of file vf_rotate.c.
Referenced by filter_frame().
Enumeration Type Documentation
var_name
enum var_name
Enumerator
VAR_CH
VAR_N
VAR_NB_IN_CHANNELS
VAR_NB_OUT_CHANNELS
VAR_T
VAR_S
VAR_VARS_NB
VAR_VALUE1
VAR_VALUE2
VAR_VARS_NB
VAR_TB
VAR_PTS
VAR_START_PTS
VAR_PREV_PTS
VAR_PREV_SELECTED_PTS
VAR_T
VAR_START_T
VAR_PREV_T
VAR_PREV_SELECTED_T
VAR_PICT_TYPE
VAR_I
VAR_P
VAR_B
VAR_S
VAR_SI
VAR_SP
VAR_BI
VAR_PICT_TYPE_I
VAR_PICT_TYPE_P
VAR_PICT_TYPE_B
VAR_PICT_TYPE_S
VAR_PICT_TYPE_SI
VAR_PICT_TYPE_SP
VAR_PICT_TYPE_BI
VAR_INTERLACE_TYPE
VAR_INTERLACE_TYPE_P
VAR_INTERLACE_TYPE_T
VAR_INTERLACE_TYPE_B
VAR_CONSUMED_SAMPLES_N
VAR_SAMPLES_N
VAR_SAMPLE_RATE
VAR_N
VAR_SELECTED_N
VAR_PREV_SELECTED_N
VAR_KEY
VAR_POS
VAR_SCENE
VAR_CONCATDEC_SELECT
VAR_VARS_NB
VAR_FRAME_RATE
VAR_INTERLACED
VAR_N
VAR_NB_CONSUMED_SAMPLES
VAR_NB_SAMPLES
VAR_POS
VAR_PREV_INPTS
VAR_PREV_INT
VAR_PREV_OUTPTS
VAR_PREV_OUTT
VAR_PTS
VAR_SAMPLE_RATE
VAR_STARTPTS
VAR_STARTT
VAR_T
VAR_TB
VAR_RTCTIME
VAR_RTCSTART
VAR_S
VAR_SR
VAR_VARS_NB
VAR_AVTB
VAR_INTB
VAR_SR
VAR_VARS_NB
VAR_W
VAR_H
VAR_A
VAR_DAR
VAR_SAR
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_W
VAR_H
VAR_CW
VAR_CH
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_X
VAR_Y
VAR_N
VAR_POS
VAR_T
VAR_VARS_NB
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_IN_H
VAR_IH
VAR_IN_W
VAR_IW
VAR_SAR
VAR_X
VAR_Y
VAR_H
VAR_W
VAR_T
VAR_MAX
VARS_NB
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_LINE_H
VAR_LH
VAR_MAIN_H
VAR_h
VAR_H
VAR_MAIN_W
VAR_w
VAR_W
VAR_MAX_GLYPH_A
VAR_ASCENT
VAR_MAX_GLYPH_D
VAR_DESCENT
VAR_MAX_GLYPH_H
VAR_MAX_GLYPH_W
VAR_N
VAR_SAR
VAR_T
VAR_TEXT_H
VAR_TH
VAR_TEXT_W
VAR_TW
VAR_X
VAR_Y
VAR_PICT_TYPE
VAR_VARS_NB
VAR_N
VAR_POS
VAR_R
VAR_T
VAR_NB
VAR_N
VAR_PTS
VAR_R
VAR_T
VAR_TB
VAR_NB
VAR_W
VAR_H
VAR_VAL
VAR_MAXVAL
VAR_MINVAL
VAR_NEGVAL
VAR_CLIPVAL
VAR_VARS_NB
VAR_W
VAR_H
VAR_X
VAR_Y
VAR_BITDEPTHX
VAR_BITDEPTHY
VAR_VARS_NB
VAR_MAIN_W
VAR_MW
VAR_MAIN_H
VAR_MH
VAR_OVERLAY_W
VAR_OW
VAR_OVERLAY_H
VAR_OH
VAR_HSUB
VAR_VSUB
VAR_X
VAR_Y
VAR_N
VAR_POS
VAR_T
VAR_VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_X
VAR_Y
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_HSUB
VAR_VSUB
VAR_N
VAR_T
VAR_VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_OHSUB
VAR_OVSUB
VARS_NB
VAR_PI
VAR_PHI
VAR_E
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_DAR
VAR_SAR
VARS_NB
VAR_W
VAR_H
VAR_N
VAR_PTS
VAR_R
VAR_T
VAR_TB
VAR_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_IN
VAR_ON
VAR_DURATION
VAR_PDURATION
VAR_TIME
VAR_FRAME
VAR_ZOOM
VAR_PZOOM
VAR_X
VAR_PX
VAR_Y
VAR_PY
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_OHSUB
VAR_OVSUB
VARS_NB
VAR_X
VAR_Y
VAR_W
VAR_H
VAR_TIME
VAR_SPEED
VAR_TEMPO
VAR_ORDER
VAR_PATTERN
VAR_ROW
VAR_VARS_NB
Definition at line 52 of file vf_rotate.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (rotate)
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 113 of file vf_rotate.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 126 of file vf_rotate.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 134 of file vf_rotate.c.
get_rotated_w()
static double get_rotated_w (void * opaque, double angle) static
Definition at line 165 of file vf_rotate.c.
get_rotated_h()
static double get_rotated_h (void * opaque, double angle) static
Definition at line 177 of file vf_rotate.c.
int_sin()
static int64_t int_sin (int64_t a) static
Compute the sin of a using integer values.
Input is scaled by FIXP2 and output values are scaled by FIXP.
Definition at line 209 of file vf_rotate.c.
Referenced by filter_frame().
interpolate_bilinear8()
static uint8_t* interpolate_bilinear8 (uint8_t * dst_color, const uint8_t * src, int src_linesize, int src_linestep, int x, int y, int max_x, int max_y) static
Interpolate the color in src at position x and y using bilinear interpolation.
Definition at line 232 of file vf_rotate.c.
Referenced by config_props().
interpolate_bilinear16()
static uint8_t* interpolate_bilinear16 (uint8_t * dst_color, const uint8_t * src, int src_linesize, int src_linestep, int x, int y, int max_x, int max_y) static
Interpolate the color in src at position x and y using bilinear interpolation.
Definition at line 262 of file vf_rotate.c.
Referenced by config_props().
config_props()
static int config_props (AVFilterLink * outlink) static
Definition at line 288 of file vf_rotate.c.
copy_elem()
static av_always_inline void copy_elem (uint8_t * pout, const uint8_t * pin, int elem_size) static
Definition at line 361 of file vf_rotate.c.
Referenced by simple_rotate_internal().
simple_rotate_internal()
static av_always_inline void simple_rotate_internal (uint8_t * dst, const uint8_t * src, int src_linesize, int angle, int elem_size, int len) static
Definition at line 384 of file vf_rotate.c.
Referenced by simple_rotate().
simple_rotate()
static av_always_inline void simple_rotate (uint8_t * dst, const uint8_t * src, int src_linesize, int angle, int elem_size, int len) static
Definition at line 406 of file vf_rotate.c.
Referenced by filter_slice().
filter_slice()
static int filter_slice (AVFilterContext * ctx, void * arg, int job, int nb_jobs) static
Definition at line 419 of file vf_rotate.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 509 of file vf_rotate.c.
process_command()
static int process_command (AVFilterContext * ctx, const char * cmd, const char * args, char * res, int res_len, int flags) static
Definition at line 563 of file vf_rotate.c.
Variable Documentation
var_names
const char* const var_names[] static
Initial value:
= {
    "in_w" , "iw",
    "in_h" , "ih",
    "out_w", "ow",
    "out_h", "oh",
    "hsub", "vsub",
    "n",
    "t",
    NULL
}
Definition at line 41 of file vf_rotate.c.
Referenced by config_props(), and process_command().
rotate_options
const AVOption rotate_options[] static
Initial value:
= {
    { "angle",     "set angle (in radians)",       OFFSET(angle_expr_str), AV_OPT_TYPE_STRING, {.str="0"}, CHAR_MIN, CHAR_MAX, .flags=FLAGS },
    { "a",         "set angle (in radians)",       OFFSET(angle_expr_str), AV_OPT_TYPE_STRING, {.str="0"}, CHAR_MIN, CHAR_MAX, .flags=FLAGS },
    { "out_w",     "set output width expression",  OFFSET(outw_expr_str), AV_OPT_TYPE_STRING, {.str="iw"}, CHAR_MIN, CHAR_MAX, .flags=FLAGS },
    { "ow",        "set output width expression",  OFFSET(outw_expr_str), AV_OPT_TYPE_STRING, {.str="iw"}, CHAR_MIN, CHAR_MAX, .flags=FLAGS },
    { "out_h",     "set output height expression", OFFSET(outh_expr_str), AV_OPT_TYPE_STRING, {.str="ih"}, CHAR_MIN, CHAR_MAX, .flags=FLAGS },
    { "oh",        "set output height expression", OFFSET(outh_expr_str), AV_OPT_TYPE_STRING, {.str="ih"}, CHAR_MIN, CHAR_MAX, .flags=FLAGS },
    { "fillcolor", "set background fill color",    OFFSET(fillcolor_str), AV_OPT_TYPE_STRING, {.str="black"}, CHAR_MIN, CHAR_MAX, .flags=FLAGS },
    { "c",         "set background fill color",    OFFSET(fillcolor_str), AV_OPT_TYPE_STRING, {.str="black"}, CHAR_MIN, CHAR_MAX, .flags=FLAGS },
    { "bilinear",  "use bilinear interpolation",   OFFSET(use_bilinear),  AV_OPT_TYPE_BOOL, {.i64=1}, 0, 1, .flags=FLAGS },
    { NULL }
}
Definition at line 98 of file vf_rotate.c.
func1
double(* const func1[])(void *, double) static
Initial value:
= {
    get_rotated_w,
    get_rotated_h,
    NULL
}
Definition at line 189 of file vf_rotate.c.
Referenced by config_props(), ff_rate_control_init(), and parse_channel_expressions().
func1_names
const char* const func1_names[] static
Initial value:
= {
    "rotw",
    "roth",
    NULL
}
Definition at line 195 of file vf_rotate.c.
Referenced by config_props(), ff_rate_control_init(), and parse_channel_expressions().
rotate_inputs
const AVFilterPad rotate_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 586 of file vf_rotate.c.
rotate_outputs
const AVFilterPad rotate_outputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .config_props = config_props,
    },
    { NULL }
}
Definition at line 595 of file vf_rotate.c.
ff_vf_rotate
AVFilter ff_vf_rotate
Initial value:
= {
    .name          = "rotate",
    .description   = NULL_IF_CONFIG_SMALL("Rotate the input image."),
    .priv_size     = sizeof(RotContext),
    .init          = init,
    .uninit        = uninit,
    .query_formats = query_formats,
    .process_command = process_command,
    .inputs        = rotate_inputs,
    .outputs       = rotate_outputs,
    .priv_class    = &rotate_class,
    .flags         = AVFILTER_FLAG_SUPPORT_TIMELINE_GENERIC | AVFILTER_FLAG_SLICE_THREADS,
}
Definition at line 604 of file vf_rotate.c.