FFmpeg: libavfilter/vf_bwdif.c File Reference
vf_bwdif.c File Reference
#include "libavutil/avassert.h"
#include "libavutil/common.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "libavutil/imgutils.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
#include "bwdif.h"
Data Structures
struct ThreadData
Macros
#define FILTER_INTRA()
#define FILTER1()
#define SPAT_CHECK()
#define FILTER_LINE()
#define FILTER_EDGE()
#define FILTER2()
#define OFFSET(x) offsetof(BWDIFContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
#define CONST(name, help, val, unit) { name, help, 0, AV_OPT_TYPE_CONST, {.i64=val}, INT_MIN, INT_MAX, FLAGS, unit }
Functions
static void filter_intra (void *dst1, void *cur1, int w, int prefs, int mrefs, int prefs3, int mrefs3, int parity, int clip_max)
static void filter_line_c (void *dst1, void *prev1, void *cur1, void *next1, int w, int prefs, int mrefs, int prefs2, int mrefs2, int prefs3, int mrefs3, int prefs4, int mrefs4, int parity, int clip_max)
static void filter_edge (void *dst1, void *prev1, void *cur1, void *next1, int w, int prefs, int mrefs, int prefs2, int mrefs2, int parity, int clip_max, int spat)
static void filter_intra_16bit (void *dst1, void *cur1, int w, int prefs, int mrefs, int prefs3, int mrefs3, int parity, int clip_max)
static void filter_line_c_16bit (void *dst1, void *prev1, void *cur1, void *next1, int w, int prefs, int mrefs, int prefs2, int mrefs2, int prefs3, int mrefs3, int prefs4, int mrefs4, int parity, int clip_max)
static void filter_edge_16bit (void *dst1, void *prev1, void *cur1, void *next1, int w, int prefs, int mrefs, int prefs2, int mrefs2, int parity, int clip_max, int spat)
static int filter_slice (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static void filter (AVFilterContext *ctx, AVFrame *dstpic, int parity, int tff)
static int return_frame (AVFilterContext *ctx, int is_second)
static int checkstride (BWDIFContext *bwdif, const AVFrame *a, const AVFrame *b)
static void fixstride (AVFilterLink *link, AVFrame *f)
static int filter_frame (AVFilterLink *link, AVFrame *frame)
static int request_frame (AVFilterLink *link)
static av_cold void uninit (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static int config_props (AVFilterLink *link)
AVFILTER_DEFINE_CLASS (bwdif)
Variables
static const uint16_t coef_lf [2] = { 4309, 213 }
static const uint16_t coef_hf [3] = { 5570, 3801, 1016 }
static const uint16_t coef_sp [2] = { 5077, 981 }
static const AVOption bwdif_options []
static const AVFilterPad avfilter_vf_bwdif_inputs []
static const AVFilterPad avfilter_vf_bwdif_outputs []
AVFilter ff_vf_bwdif
Macro Definition Documentation
FILTER_INTRA
#define FILTER_INTRA ()
Value:
for (x = 0; x < w; x++) { \
        interpol = (coef_sp[0] * (cur[mrefs] + cur[prefs]) - coef_sp[1] * (cur[mrefs3] + cur[prefs3])) >> 13; \
        dst[0] = av_clip(interpol, 0, clip_max); \
 \
        dst++; \
        cur++; \
    }
Definition at line 60 of file vf_bwdif.c.
Referenced by filter_intra(), and filter_intra_16bit().
FILTER1
#define FILTER1 ()
Value:
for (x = 0; x < w; x++) { \
        int c = cur[mrefs]; \
        int d = (prev2[0] + next2[0]) >> 1; \
        int e = cur[prefs]; \
        int temporal_diff0 = FFABS(prev2[0] - next2[0]); \
        int temporal_diff1 =(FFABS(prev[mrefs] - c) + FFABS(prev[prefs] - e)) >> 1; \
        int temporal_diff2 =(FFABS(next[mrefs] - c) + FFABS(next[prefs] - e)) >> 1; \
        int diff = FFMAX3(temporal_diff0 >> 1, temporal_diff1, temporal_diff2); \
 \
        if (!diff) { \
            dst[0] = d; \
        } else {
Definition at line 69 of file vf_bwdif.c.
Referenced by filter_edge(), filter_edge_16bit(), filter_line_c(), and filter_line_c_16bit().
SPAT_CHECK
#define SPAT_CHECK ()
Value:
int b = ((prev2[mrefs2] + next2[mrefs2]) >> 1) - c; \
            int f = ((prev2[prefs2] + next2[prefs2]) >> 1) - e; \
            int dc = d - c; \
            int de = d - e; \
            int max = FFMAX3(de, dc, FFMIN(b, f)); \
            int min = FFMIN3(de, dc, FFMAX(b, f)); \
            diff = FFMAX3(diff, min, -max);
Definition at line 83 of file vf_bwdif.c.
FILTER_LINE
#define FILTER_LINE ()
Value:
SPAT_CHECK() \
            if (FFABS(c - e) > temporal_diff0) { \
                interpol = (((coef_hf[0] * (prev2[0] + next2[0]) \
                    - coef_hf[1] * (prev2[mrefs2] + next2[mrefs2] + prev2[prefs2] + next2[prefs2]) \
                    + coef_hf[2] * (prev2[mrefs4] + next2[mrefs4] + prev2[prefs4] + next2[prefs4])) >> 2) \
                    + coef_lf[0] * (c + e) - coef_lf[1] * (cur[mrefs3] + cur[prefs3])) >> 13; \
            } else { \
                interpol = (coef_sp[0] * (c + e) - coef_sp[1] * (cur[mrefs3] + cur[prefs3])) >> 13; \
            }
Definition at line 92 of file vf_bwdif.c.
Referenced by filter_line_c(), and filter_line_c_16bit().
FILTER_EDGE
#define FILTER_EDGE ()
Value:
if (spat) { \
                SPAT_CHECK() \
            } \
            interpol = (c + e) >> 1;
Definition at line 103 of file vf_bwdif.c.
Referenced by filter_edge(), and filter_edge_16bit().
FILTER2
#define FILTER2 ()
Value:
if (interpol > d + diff) \
                interpol = d + diff; \
            else if (interpol < d - diff) \
                interpol = d - diff; \
 \
            dst[0] = av_clip(interpol, 0, clip_max); \
        } \
 \
        dst++; \
        cur++; \
        prev++; \
        next++; \
        prev2++; \
        next2++; \
    }
Definition at line 109 of file vf_bwdif.c.
Referenced by filter_edge(), filter_edge_16bit(), filter_line_c(), and filter_line_c_16bit().
OFFSET
#define OFFSET (x) offsetof(BWDIFContext, x)
Definition at line 531 of file vf_bwdif.c.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 532 of file vf_bwdif.c.
CONST
#define CONST (name, help, val, unit) { name, help, 0, AV_OPT_TYPE_CONST, {.i64=val}, INT_MIN, INT_MAX, FLAGS, unit }
Definition at line 534 of file vf_bwdif.c.
Referenced by bound().
Function Documentation
filter_intra()
static void filter_intra (void * dst1, void * cur1, int w, int prefs, int mrefs, int prefs3, int mrefs3, int parity, int clip_max) static
Definition at line 126 of file vf_bwdif.c.
Referenced by config_props().
filter_line_c()
static void filter_line_c (void * dst1, void * prev1, void * cur1, void * next1, int w, int prefs, int mrefs, int prefs2, int mrefs2, int prefs3, int mrefs3, int prefs4, int mrefs4, int parity, int clip_max) static
Definition at line 136 of file vf_bwdif.c.
Referenced by config_props().
filter_edge()
static void filter_edge (void * dst1, void * prev1, void * cur1, void * next1, int w, int prefs, int mrefs, int prefs2, int mrefs2, int parity, int clip_max, int spat) static
Definition at line 154 of file vf_bwdif.c.
Referenced by config_props().
filter_intra_16bit()
static void filter_intra_16bit (void * dst1, void * cur1, int w, int prefs, int mrefs, int prefs3, int mrefs3, int parity, int clip_max) static
Definition at line 171 of file vf_bwdif.c.
Referenced by config_props().
filter_line_c_16bit()
static void filter_line_c_16bit (void * dst1, void * prev1, void * cur1, void * next1, int w, int prefs, int mrefs, int prefs2, int mrefs2, int prefs3, int mrefs3, int prefs4, int mrefs4, int parity, int clip_max) static
Definition at line 181 of file vf_bwdif.c.
Referenced by config_props().
filter_edge_16bit()
static void filter_edge_16bit (void * dst1, void * prev1, void * cur1, void * next1, int w, int prefs, int mrefs, int prefs2, int mrefs2, int parity, int clip_max, int spat) static
Definition at line 199 of file vf_bwdif.c.
Referenced by config_props().
filter_slice()
static int filter_slice (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 216 of file vf_bwdif.c.
Referenced by blend_frame(), and filter().
filter()
static void filter (AVFilterContext * ctx, AVFrame * dstpic, int parity, int tff) static
Definition at line 261 of file vf_bwdif.c.
Referenced by return_frame().
return_frame()
static int return_frame (AVFilterContext * ctx, int is_second) static
Definition at line 290 of file vf_bwdif.c.
Referenced by filter_frame(), and request_frame().
checkstride()
static int checkstride (BWDIFContext * bwdif, const AVFrame * a, const AVFrame * b) static
Definition at line 332 of file vf_bwdif.c.
Referenced by filter_frame().
fixstride()
static void fixstride (AVFilterLink * link, AVFrame * f) static
Definition at line 341 of file vf_bwdif.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * link, AVFrame * frame) static
Definition at line 355 of file vf_bwdif.c.
Referenced by request_frame().
request_frame()
static int request_frame (AVFilterLink * link) static
Definition at line 422 of file vf_bwdif.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 456 of file vf_bwdif.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 465 of file vf_bwdif.c.
config_props()
static int config_props (AVFilterLink * link) static
Definition at line 495 of file vf_bwdif.c.
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (bwdif)
Variable Documentation
coef_lf
const uint16_t coef_lf[2] = { 4309, 213 } static
Definition at line 48 of file vf_bwdif.c.
coef_hf
const uint16_t coef_hf[3] = { 5570, 3801, 1016 } static
Definition at line 49 of file vf_bwdif.c.
coef_sp
const uint16_t coef_sp[2] = { 5077, 981 } static
Definition at line 50 of file vf_bwdif.c.
bwdif_options
const AVOption bwdif_options[] static
Initial value:
= {
    { "mode",   "specify the interlacing mode", OFFSET(mode), AV_OPT_TYPE_INT, {.i64=BWDIF_MODE_SEND_FIELD}, 0, 1, FLAGS, "mode"},
    CONST("send_frame", "send one frame for each frame", BWDIF_MODE_SEND_FRAME, "mode"),
    CONST("send_field", "send one frame for each field", BWDIF_MODE_SEND_FIELD, "mode"),
    { "parity", "specify the assumed picture field parity", OFFSET(parity), AV_OPT_TYPE_INT, {.i64=BWDIF_PARITY_AUTO}, -1, 1, FLAGS, "parity" },
    CONST("tff",  "assume top field first",    BWDIF_PARITY_TFF,  "parity"),
    CONST("bff",  "assume bottom field first", BWDIF_PARITY_BFF,  "parity"),
    CONST("auto", "auto detect parity",        BWDIF_PARITY_AUTO, "parity"),
    { "deint", "specify which frames to deinterlace", OFFSET(deint), AV_OPT_TYPE_INT, {.i64=BWDIF_DEINT_ALL}, 0, 1, FLAGS, "deint" },
    CONST("all",        "deinterlace all frames",                       BWDIF_DEINT_ALL,        "deint"),
    CONST("interlaced", "only deinterlace frames marked as interlaced", BWDIF_DEINT_INTERLACED, "deint"),
    { NULL }
}
Definition at line 536 of file vf_bwdif.c.
avfilter_vf_bwdif_inputs
const AVFilterPad avfilter_vf_bwdif_inputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .filter_frame  = filter_frame,
    },
    { NULL }
}
Definition at line 555 of file vf_bwdif.c.
avfilter_vf_bwdif_outputs
const AVFilterPad avfilter_vf_bwdif_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .request_frame = request_frame,
        .config_props  = config_props,
    },
    { NULL }
}
Definition at line 564 of file vf_bwdif.c.
ff_vf_bwdif
AVFilter ff_vf_bwdif
Initial value:
= {
    .name          = "bwdif",
    .description   = NULL_IF_CONFIG_SMALL("Deinterlace the input image."),
    .priv_size     = sizeof(BWDIFContext),
    .priv_class    = &bwdif_class,
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = avfilter_vf_bwdif_inputs,
    .outputs       = avfilter_vf_bwdif_outputs,
    .flags         = AVFILTER_FLAG_SUPPORT_TIMELINE_INTERNAL | AVFILTER_FLAG_SLICE_THREADS,
}
Definition at line 574 of file vf_bwdif.c.