FFmpeg: libavfilter/x86/vf_bwdif_init.c File Reference
vf_bwdif_init.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/mem.h"
#include "libavutil/x86/asm.h"
#include "libavutil/x86/cpu.h"
#include "libavfilter/bwdif.h"
Functions
void ff_bwdif_filter_line_mmxext (void *dst, void *prev, void *cur, void *next, int w, int prefs, int mrefs, int prefs2, int mrefs2, int prefs3, int mrefs3, int prefs4, int mrefs4, int parity, int clip_max)
void ff_bwdif_filter_line_sse2 (void *dst, void *prev, void *cur, void *next, int w, int prefs, int mrefs, int prefs2, int mrefs2, int prefs3, int mrefs3, int prefs4, int mrefs4, int parity, int clip_max)
void ff_bwdif_filter_line_ssse3 (void *dst, void *prev, void *cur, void *next, int w, int prefs, int mrefs, int prefs2, int mrefs2, int prefs3, int mrefs3, int prefs4, int mrefs4, int parity, int clip_max)
void ff_bwdif_filter_line_12bit_mmxext (void *dst, void *prev, void *cur, void *next, int w, int prefs, int mrefs, int prefs2, int mrefs2, int prefs3, int mrefs3, int prefs4, int mrefs4, int parity, int clip_max)
void ff_bwdif_filter_line_12bit_sse2 (void *dst, void *prev, void *cur, void *next, int w, int prefs, int mrefs, int prefs2, int mrefs2, int prefs3, int mrefs3, int prefs4, int mrefs4, int parity, int clip_max)
void ff_bwdif_filter_line_12bit_ssse3 (void *dst, void *prev, void *cur, void *next, int w, int prefs, int mrefs, int prefs2, int mrefs2, int prefs3, int mrefs3, int prefs4, int mrefs4, int parity, int clip_max)
av_cold void ff_bwdif_init_x86 (BWDIFContext *bwdif)
Function Documentation
ff_bwdif_filter_line_mmxext()
void ff_bwdif_filter_line_mmxext (void * dst, void * prev, void * cur, void * next, int w, int prefs, int mrefs, int prefs2, int mrefs2, int prefs3, int mrefs3, int prefs4, int mrefs4, int parity, int clip_max)
Referenced by ff_bwdif_init_x86().
ff_bwdif_filter_line_sse2()
void ff_bwdif_filter_line_sse2 (void * dst, void * prev, void * cur, void * next, int w, int prefs, int mrefs, int prefs2, int mrefs2, int prefs3, int mrefs3, int prefs4, int mrefs4, int parity, int clip_max)
Referenced by ff_bwdif_init_x86().
ff_bwdif_filter_line_ssse3()
void ff_bwdif_filter_line_ssse3 (void * dst, void * prev, void * cur, void * next, int w, int prefs, int mrefs, int prefs2, int mrefs2, int prefs3, int mrefs3, int prefs4, int mrefs4, int parity, int clip_max)
Referenced by ff_bwdif_init_x86().
ff_bwdif_filter_line_12bit_mmxext()
void ff_bwdif_filter_line_12bit_mmxext (void * dst, void * prev, void * cur, void * next, int w, int prefs, int mrefs, int prefs2, int mrefs2, int prefs3, int mrefs3, int prefs4, int mrefs4, int parity, int clip_max)
Referenced by ff_bwdif_init_x86().
ff_bwdif_filter_line_12bit_sse2()
void ff_bwdif_filter_line_12bit_sse2 (void * dst, void * prev, void * cur, void * next, int w, int prefs, int mrefs, int prefs2, int mrefs2, int prefs3, int mrefs3, int prefs4, int mrefs4, int parity, int clip_max)
Referenced by ff_bwdif_init_x86().
ff_bwdif_filter_line_12bit_ssse3()
void ff_bwdif_filter_line_12bit_ssse3 (void * dst, void * prev, void * cur, void * next, int w, int prefs, int mrefs, int prefs2, int mrefs2, int prefs3, int mrefs3, int prefs4, int mrefs4, int parity, int clip_max)
Referenced by ff_bwdif_init_x86().
ff_bwdif_init_x86()
av_cold void ff_bwdif_init_x86 (BWDIFContext * bwdif)
Definition at line 54 of file vf_bwdif_init.c.
Referenced by config_props().