FFmpeg: libavfilter/vf_atadenoise.c File Reference
vf_atadenoise.c File Reference
Adaptive Temporal Averaging Denoiser, based on paper "Video Denoising Based on Adaptive Temporal Averaging" by David Bartovčak and Miroslav Vrankić
#include "libavutil/imgutils.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "avfilter.h"
#include "bufferqueue.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
Data Structures
struct ATADenoiseContext
struct ThreadData
Macros
#define FF_BUFQUEUE_SIZE 129
#define SIZE FF_BUFQUEUE_SIZE
#define OFFSET(x) offsetof(ATADenoiseContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Functions
AVFILTER_DEFINE_CLASS (atadenoise)
static int query_formats (AVFilterContext *ctx)
static av_cold int init (AVFilterContext *ctx)
static int filter_slice8 (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int filter_slice16 (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int config_input (AVFilterLink *inlink)
static int filter_frame (AVFilterLink *inlink, AVFrame *buf)
static int request_frame (AVFilterLink *outlink)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const AVOption atadenoise_options []
static const AVFilterPad inputs []
static const AVFilterPad outputs []
AVFilter ff_vf_atadenoise
Detailed Description
Adaptive Temporal Averaging Denoiser, based on paper "Video Denoising Based on Adaptive Temporal Averaging" by David Bartovčak and Miroslav Vrankić
Definition in file vf_atadenoise.c.
Macro Definition Documentation
FF_BUFQUEUE_SIZE
#define FF_BUFQUEUE_SIZE 129
Definition at line 33 of file vf_atadenoise.c.
SIZE
#define SIZE FF_BUFQUEUE_SIZE
Definition at line 40 of file vf_atadenoise.c.
Referenced by filter_slice16(), and filter_slice8().
OFFSET
#define OFFSET (x) offsetof(ATADenoiseContext, x)
Definition at line 62 of file vf_atadenoise.c.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 63 of file vf_atadenoise.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (atadenoise)
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 79 of file vf_atadenoise.c.
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 107 of file vf_atadenoise.c.
filter_slice8()
static int filter_slice8 (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 124 of file vf_atadenoise.c.
Referenced by config_input().
filter_slice16()
static int filter_slice16 (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 201 of file vf_atadenoise.c.
Referenced by config_input().
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 278 of file vf_atadenoise.c.
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * buf) static
Definition at line 308 of file vf_atadenoise.c.
Referenced by request_frame().
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 377 of file vf_atadenoise.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 397 of file vf_atadenoise.c.
Variable Documentation
atadenoise_options
const AVOption atadenoise_options[] static
Initial value:
= {
    { "0a", "set threshold A for 1st plane", OFFSET(fthra[0]), AV_OPT_TYPE_FLOAT, {.dbl=0.02}, 0, 0.3, FLAGS },
    { "0b", "set threshold B for 1st plane", OFFSET(fthrb[0]), AV_OPT_TYPE_FLOAT, {.dbl=0.04}, 0, 5.0, FLAGS },
    { "1a", "set threshold A for 2nd plane", OFFSET(fthra[1]), AV_OPT_TYPE_FLOAT, {.dbl=0.02}, 0, 0.3, FLAGS },
    { "1b", "set threshold B for 2nd plane", OFFSET(fthrb[1]), AV_OPT_TYPE_FLOAT, {.dbl=0.04}, 0, 5.0, FLAGS },
    { "2a", "set threshold A for 3rd plane", OFFSET(fthra[2]), AV_OPT_TYPE_FLOAT, {.dbl=0.02}, 0, 0.3, FLAGS },
    { "2b", "set threshold B for 3rd plane", OFFSET(fthrb[2]), AV_OPT_TYPE_FLOAT, {.dbl=0.04}, 0, 5.0, FLAGS },
    { "s",  "set how many frames to use",    OFFSET(size),     AV_OPT_TYPE_INT,   {.i64=9},   5, SIZE, FLAGS },
    { "p",  "set what planes to filter",     OFFSET(planes),   AV_OPT_TYPE_FLAGS, {.i64=7},    0, 15,  FLAGS },
    { NULL }
}
Definition at line 65 of file vf_atadenoise.c.
inputs
const AVFilterPad inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
        .config_props = config_input,
    },
    { NULL }
}
Definition at line 404 of file vf_atadenoise.c.
outputs
const AVFilterPad outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .request_frame = request_frame,
    },
    { NULL }
}
Definition at line 414 of file vf_atadenoise.c.
ff_vf_atadenoise
AVFilter ff_vf_atadenoise
Initial value:
= {
    .name          = "atadenoise",
    .description   = NULL_IF_CONFIG_SMALL("Apply an Adaptive Temporal Averaging Denoiser."),
    .priv_size     = sizeof(ATADenoiseContext),
    .priv_class    = &atadenoise_class,
    .init          = init,
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = inputs,
    .outputs       = outputs,
    .flags         = AVFILTER_FLAG_SUPPORT_TIMELINE_INTERNAL | AVFILTER_FLAG_SLICE_THREADS,
}
Definition at line 423 of file vf_atadenoise.c.