FFmpeg: libavfilter/vf_ssim.c File Reference
vf_ssim.c File Reference
#include "libavutil/avstring.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "avfilter.h"
#include "dualinput.h"
#include "drawutils.h"
#include "formats.h"
#include "internal.h"
#include "ssim.h"
#include "video.h"
Data Structures
struct SSIMContext
Macros
#define OFFSET(x) offsetof(SSIMContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
#define PF(suf) AV_PIX_FMT_YUV420##suf, AV_PIX_FMT_YUV422##suf, AV_PIX_FMT_YUV444##suf, AV_PIX_FMT_GBR##suf
Functions
AVFILTER_DEFINE_CLASS (ssim)
static void set_meta (AVDictionary **metadata, const char *key, char comp, float d)
static void ssim_4x4xn_16bit (const uint8_t *main8, ptrdiff_t main_stride, const uint8_t *ref8, ptrdiff_t ref_stride, int64_t(*sums)[4], int width)
static void ssim_4x4xn_8bit (const uint8_t *main, ptrdiff_t main_stride, const uint8_t *ref, ptrdiff_t ref_stride, int(*sums)[4], int width)
static float ssim_end1x (int64_t s1, int64_t s2, int64_t ss, int64_t s12, int max)
static float ssim_end1 (int s1, int s2, int ss, int s12)
static float ssim_endn_16bit (const int64_t(*sum0)[4], const int64_t(*sum1)[4], int width, int max)
static float ssim_endn_8bit (const int(*sum0)[4], const int(*sum1)[4], int width)
static float ssim_plane_16bit (SSIMDSPContext *dsp, uint8_t *main, int main_stride, uint8_t *ref, int ref_stride, int width, int height, void *temp, int max)
static float ssim_plane (SSIMDSPContext *dsp, uint8_t *main, int main_stride, uint8_t *ref, int ref_stride, int width, int height, void *temp, int max)
static double ssim_db (double ssim, double weight)
static AVFrame * do_ssim (AVFilterContext *ctx, AVFrame *main, const AVFrame *ref)
static av_cold int init (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static int config_input_ref (AVFilterLink *inlink)
static int config_output (AVFilterLink *outlink)
static int filter_frame (AVFilterLink *inlink, AVFrame *buf)
static int request_frame (AVFilterLink *outlink)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const AVOption ssim_options []
static const AVFilterPad ssim_inputs []
static const AVFilterPad ssim_outputs []
AVFilter ff_vf_ssim
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(SSIMContext, x)
Definition at line 72 of file vf_ssim.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 73 of file vf_ssim.c.
PF
#define PF (suf) AV_PIX_FMT_YUV420##suf, AV_PIX_FMT_YUV422##suf, AV_PIX_FMT_YUV444##suf, AV_PIX_FMT_GBR##suf
Referenced by query_formats().
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (ssim)
set_meta()
static void set_meta (AVDictionary ** metadata, const char * key, char comp, float d) static
Definition at line 83 of file vf_ssim.c.
Referenced by do_ssim().
ssim_4x4xn_16bit()
static void ssim_4x4xn_16bit (const uint8_t * main8, ptrdiff_t main_stride, const uint8_t * ref8, ptrdiff_t ref_stride, int64_t(*) sums[4], int width) static
Definition at line 96 of file vf_ssim.c.
Referenced by ssim_plane_16bit().
ssim_4x4xn_8bit()
static void ssim_4x4xn_8bit (const uint8_t * main, ptrdiff_t main_stride, const uint8_t * ref, ptrdiff_t ref_stride, int(*) sums[4], int width) static
Definition at line 132 of file vf_ssim.c.
Referenced by config_input_ref().
ssim_end1x()
static float ssim_end1x (int64_t s1, int64_t s2, int64_t ss, int64_t s12, int max) static
Definition at line 163 of file vf_ssim.c.
Referenced by ssim_endn_16bit().
ssim_end1()
static float ssim_end1 (int s1, int s2, int ss, int s12) static
Definition at line 179 of file vf_ssim.c.
Referenced by ssim_endn_8bit().
ssim_endn_16bit()
static float ssim_endn_16bit (const int64_t(*) sum0[4], const int64_t(*) sum1[4], int width, int max) static
Definition at line 195 of file vf_ssim.c.
Referenced by ssim_plane_16bit().
ssim_endn_8bit()
static float ssim_endn_8bit (const int(*) sum0[4], const int(*) sum1[4], int width) static
Definition at line 209 of file vf_ssim.c.
Referenced by config_input_ref().
ssim_plane_16bit()
static float ssim_plane_16bit (SSIMDSPContext * dsp, uint8_t * main, int main_stride, uint8_t * ref, int ref_stride, int width, int height, void * temp, int max) static
Definition at line 222 of file vf_ssim.c.
Referenced by config_input_ref().
ssim_plane()
static float ssim_plane (SSIMDSPContext * dsp, uint8_t * main, int main_stride, uint8_t * ref, int ref_stride, int width, int height, void * temp, int max) static
Definition at line 250 of file vf_ssim.c.
ssim_db()
static double ssim_db (double ssim, double weight) static
Definition at line 278 of file vf_ssim.c.
Referenced by do_ssim(), and uninit().
do_ssim()
static AVFrame* do_ssim (AVFilterContext * ctx, AVFrame * main, const AVFrame * ref) static
Definition at line 283 of file vf_ssim.c.
Referenced by init().
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 324 of file vf_ssim.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 350 of file vf_ssim.c.
config_input_ref()
static int config_input_ref (AVFilterLink * inlink) static
Definition at line 371 of file vf_ssim.c.
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 419 of file vf_ssim.c.
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * buf) static
Definition at line 438 of file vf_ssim.c.
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 444 of file vf_ssim.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 450 of file vf_ssim.c.
Variable Documentation
ssim_options
const AVOption ssim_options[] static
Initial value:
= {
    {"stats_file", "Set file where to store per-frame difference information", OFFSET(stats_file_str), AV_OPT_TYPE_STRING, {.str=NULL}, 0, 0, FLAGS },
    {"f",          "Set file where to store per-frame difference information", OFFSET(stats_file_str), AV_OPT_TYPE_STRING, {.str=NULL}, 0, 0, FLAGS },
    { NULL }
}
Definition at line 75 of file vf_ssim.c.
ssim_inputs
const AVFilterPad ssim_inputs[] static
Initial value:
= {
    {
        .name         = "main",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
    },{
        .name         = "reference",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
        .config_props = config_input_ref,
    },
    { NULL }
}
Definition at line 475 of file vf_ssim.c.
ssim_outputs
const AVFilterPad ssim_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .config_props  = config_output,
        .request_frame = request_frame,
    },
    { NULL }
}
Definition at line 489 of file vf_ssim.c.
ff_vf_ssim
AVFilter ff_vf_ssim
Initial value:
= {
    .name          = "ssim",
    .description   = NULL_IF_CONFIG_SMALL("Calculate the SSIM between two video streams."),
    .init          = init,
    .uninit        = uninit,
    .query_formats = query_formats,
    .priv_size     = sizeof(SSIMContext),
    .priv_class    = &ssim_class,
    .inputs        = ssim_inputs,
    .outputs       = ssim_outputs,
}
Definition at line 499 of file vf_ssim.c.