FFmpeg: libavfilter/vf_idet.c File Reference
vf_idet.c File Reference
#include <float.h>
#include "libavutil/cpu.h"
#include "libavutil/common.h"
#include "libavutil/opt.h"
#include "internal.h"
#include "vf_idet.h"
Macros
#define OFFSET(x) offsetof(IDETContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
#define PRECISION 1048576
Functions
AVFILTER_DEFINE_CLASS (idet)
static const char * type2str (Type type)
static uint64_t uintpow (uint64_t b, unsigned int e)
static int av_dict_set_fxp (AVDictionary **pm, const char *key, uint64_t value, unsigned int digits, int flags)
static const char * rep2str (RepeatedField repeated_field)
int ff_idet_filter_line_c (const uint8_t *a, const uint8_t *b, const uint8_t *c, int w)
int ff_idet_filter_line_c_16bit (const uint16_t *a, const uint16_t *b, const uint16_t *c, int w)
static void filter (AVFilterContext *ctx)
static int filter_frame (AVFilterLink *link, AVFrame *picref)
static int request_frame (AVFilterLink *link)
static av_cold void uninit (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static av_cold int init (AVFilterContext *ctx)
Variables
static const AVOption idet_options []
static const AVFilterPad idet_inputs []
static const AVFilterPad idet_outputs []
AVFilter ff_vf_idet
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(IDETContext, x)
Definition at line 29 of file vf_idet.c.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 30 of file vf_idet.c.
PRECISION
#define PRECISION 1048576
Definition at line 54 of file vf_idet.c.
Referenced by av_dict_set_fxp(), filter(), and init().
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (idet)
type2str()
static const char* type2str (Type type) static
Definition at line 43 of file vf_idet.c.
Referenced by filter().
uintpow()
static uint64_t uintpow (uint64_t b, unsigned int e) static
Definition at line 56 of file vf_idet.c.
Referenced by av_dict_set_fxp().
av_dict_set_fxp()
static int av_dict_set_fxp (AVDictionary ** pm, const char * key, uint64_t value, unsigned int digits, int flags) static
Definition at line 63 of file vf_idet.c.
Referenced by filter().
rep2str()
static const char* rep2str (RepeatedField repeated_field) static
Definition at line 77 of file vf_idet.c.
Referenced by filter().
ff_idet_filter_line_c()
int ff_idet_filter_line_c (const uint8_t * a, const uint8_t * b, const uint8_t * c, int w)
Definition at line 87 of file vf_idet.c.
Referenced by init().
ff_idet_filter_line_c_16bit()
int ff_idet_filter_line_c_16bit (const uint16_t * a, const uint16_t * b, const uint16_t * c, int w)
Definition at line 100 of file vf_idet.c.
Referenced by filter_frame().
filter()
static void filter (AVFilterContext * ctx) static
Definition at line 113 of file vf_idet.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * link, AVFrame * picref) static
Definition at line 234 of file vf_idet.c.
Referenced by request_frame().
request_frame()
static int request_frame (AVFilterLink * link) static
Definition at line 312 of file vf_idet.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 336 of file vf_idet.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 364 of file vf_idet.c.
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 403 of file vf_idet.c.
Variable Documentation
idet_options
const AVOption idet_options[] static
Initial value:
= {
    { "intl_thres", "set interlacing threshold", OFFSET(interlace_threshold),   AV_OPT_TYPE_FLOAT, {.dbl = 1.04}, -1, FLT_MAX, FLAGS },
    { "prog_thres", "set progressive threshold", OFFSET(progressive_threshold), AV_OPT_TYPE_FLOAT, {.dbl = 1.5},  -1, FLT_MAX, FLAGS },
    { "rep_thres",  "set repeat threshold",      OFFSET(repeat_threshold),      AV_OPT_TYPE_FLOAT, {.dbl = 3.0},  -1, FLT_MAX, FLAGS },
    { "half_life", "half life of cumulative statistics", OFFSET(half_life),     AV_OPT_TYPE_FLOAT, {.dbl = 0.0},  -1, INT_MAX, FLAGS },
    { "analyze_interlaced_flag", "set number of frames to use to determine if the interlace flag is accurate", OFFSET(analyze_interlaced_flag), AV_OPT_TYPE_INT, {.i64 = 0 }, 0, INT_MAX, FLAGS },
    { NULL }
}
Definition at line 32 of file vf_idet.c.
idet_inputs
const AVFilterPad idet_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 424 of file vf_idet.c.
idet_outputs
const AVFilterPad idet_outputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .request_frame = request_frame
    },
    { NULL }
}
Definition at line 433 of file vf_idet.c.
ff_vf_idet
AVFilter ff_vf_idet
Initial value:
= {
    .name          = "idet",
    .description   = NULL_IF_CONFIG_SMALL("Interlace detect Filter."),
    .priv_size     = sizeof(IDETContext),
    .init          = init,
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = idet_inputs,
    .outputs       = idet_outputs,
    .priv_class    = &idet_class,
}
Definition at line 442 of file vf_idet.c.