FFmpeg: libavfilter/vf_psnr.c File Reference
vf_psnr.c File Reference
Caculate the PSNR between two input videos.
#include "libavutil/avstring.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "avfilter.h"
#include "dualinput.h"
#include "drawutils.h"
#include "formats.h"
#include "internal.h"
#include "psnr.h"
#include "video.h"
Data Structures
struct PSNRContext
Macros
#define OFFSET(x) offsetof(PSNRContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
#define PF_NOALPHA(suf) AV_PIX_FMT_YUV420##suf, AV_PIX_FMT_YUV422##suf, AV_PIX_FMT_YUV444##suf
#define PF_ALPHA(suf) AV_PIX_FMT_YUVA420##suf, AV_PIX_FMT_YUVA422##suf, AV_PIX_FMT_YUVA444##suf
#define PF(suf) PF_NOALPHA(suf), PF_ALPHA(suf)
Functions
AVFILTER_DEFINE_CLASS (psnr)
static unsigned pow2 (unsigned base)
static double get_psnr (double mse, uint64_t nb_frames, int max)
static uint64_t sse_line_8bit (const uint8_t *main_line, const uint8_t *ref_line, int outw)
static uint64_t sse_line_16bit (const uint8_t *_main_line, const uint8_t *_ref_line, int outw)
static void compute_images_mse (PSNRContext *s, const uint8_t *main_data[4], const int main_linesizes[4], const uint8_t *ref_data[4], const int ref_linesizes[4], int w, int h, double mse[4])
static void set_meta (AVDictionary **metadata, const char *key, char comp, float d)
static AVFrame * do_psnr (AVFilterContext *ctx, AVFrame *main, const AVFrame *ref)
static av_cold int init (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static int config_input_ref (AVFilterLink *inlink)
static int config_output (AVFilterLink *outlink)
static int filter_frame (AVFilterLink *inlink, AVFrame *inpicref)
static int request_frame (AVFilterLink *outlink)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const AVOption psnr_options []
static const AVFilterPad psnr_inputs []
static const AVFilterPad psnr_outputs []
AVFilter ff_vf_psnr
Detailed Description
Caculate the PSNR between two input videos.
Definition in file vf_psnr.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(PSNRContext, x)
Definition at line 60 of file vf_psnr.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 61 of file vf_psnr.c.
PF_NOALPHA
#define PF_NOALPHA (suf) AV_PIX_FMT_YUV420##suf, AV_PIX_FMT_YUV422##suf, AV_PIX_FMT_YUV444##suf
Referenced by query_formats().
PF_ALPHA
#define PF_ALPHA (suf) AV_PIX_FMT_YUVA420##suf, AV_PIX_FMT_YUVA422##suf, AV_PIX_FMT_YUVA444##suf
PF
#define PF (suf) PF_NOALPHA(suf), PF_ALPHA(suf)
Referenced by query_formats().
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (psnr)
pow2()
static unsigned pow2 (unsigned base) inline static
Definition at line 73 of file vf_psnr.c.
Referenced by get_psnr(), sse_line_16bit(), and sse_line_8bit().
get_psnr()
static double get_psnr (double mse, uint64_t nb_frames, int max) inline static
Definition at line 78 of file vf_psnr.c.
Referenced by do_psnr(), and uninit().
sse_line_8bit()
static uint64_t sse_line_8bit (const uint8_t * main_line, const uint8_t * ref_line, int outw) static
Definition at line 83 of file vf_psnr.c.
Referenced by config_input_ref().
sse_line_16bit()
static uint64_t sse_line_16bit (const uint8_t * _main_line, const uint8_t * _ref_line, int outw) static
Definition at line 94 of file vf_psnr.c.
Referenced by config_input_ref().
compute_images_mse()
static void compute_images_mse (PSNRContext * s, const uint8_t * main_data[4], const int main_linesizes[4], const uint8_t * ref_data[4], const int ref_linesizes[4], int w, int h, double mse[4]) inline static
Definition at line 108 of file vf_psnr.c.
Referenced by do_psnr().
set_meta()
static void set_meta (AVDictionary ** metadata, const char * key, char comp, float d) static
Definition at line 132 of file vf_psnr.c.
Referenced by do_psnr().
do_psnr()
static AVFrame* do_psnr (AVFilterContext * ctx, AVFrame * main, const AVFrame * ref) static
Definition at line 145 of file vf_psnr.c.
Referenced by init().
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 220 of file vf_psnr.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 252 of file vf_psnr.c.
config_input_ref()
static int config_input_ref (AVFilterLink * inlink) static
Definition at line 275 of file vf_psnr.c.
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 327 of file vf_psnr.c.
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * inpicref) static
Definition at line 345 of file vf_psnr.c.
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 351 of file vf_psnr.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 357 of file vf_psnr.c.
Variable Documentation
psnr_options
const AVOption psnr_options[] static
Initial value:
= {
    {"stats_file", "Set file where to store per-frame difference information", OFFSET(stats_file_str), AV_OPT_TYPE_STRING, {.str=NULL}, 0, 0, FLAGS },
    {"f",          "Set file where to store per-frame difference information", OFFSET(stats_file_str), AV_OPT_TYPE_STRING, {.str=NULL}, 0, 0, FLAGS },
    {"stats_version", "Set the format version for the stats file.",               OFFSET(stats_version),  AV_OPT_TYPE_INT,    {.i64=1},    1, 2, FLAGS },
    {"output_max",  "Add raw stats (max values) to the output log.",            OFFSET(stats_add_max), AV_OPT_TYPE_BOOL, {.i64=0}, 0, 1, FLAGS},
    { NULL }
}
Definition at line 63 of file vf_psnr.c.
psnr_inputs
const AVFilterPad psnr_inputs[] static
Initial value:
= {
    {
        .name         = "main",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
    },{
        .name         = "reference",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
        .config_props = config_input_ref,
    },
    { NULL }
}
Definition at line 384 of file vf_psnr.c.
psnr_outputs
const AVFilterPad psnr_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .config_props  = config_output,
        .request_frame = request_frame,
    },
    { NULL }
}
Definition at line 398 of file vf_psnr.c.
ff_vf_psnr
AVFilter ff_vf_psnr
Initial value:
= {
    .name          = "psnr",
    .description   = NULL_IF_CONFIG_SMALL("Calculate the PSNR between two video streams."),
    .init          = init,
    .uninit        = uninit,
    .query_formats = query_formats,
    .priv_size     = sizeof(PSNRContext),
    .priv_class    = &psnr_class,
    .inputs        = psnr_inputs,
    .outputs       = psnr_outputs,
}
Definition at line 408 of file vf_psnr.c.