FFmpeg: libavfilter/vf_yadif.c File Reference
vf_yadif.c File Reference
#include "libavutil/avassert.h"
#include "libavutil/cpu.h"
#include "libavutil/common.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "libavutil/imgutils.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
#include "yadif.h"
Data Structures
struct ThreadData
Macros
#define CHECK(j)
#define FILTER(start, end, is_not_edge)
#define MAX_ALIGN 8
#define OFFSET(x) offsetof(YADIFContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
#define CONST(name, help, val, unit) { name, help, 0, AV_OPT_TYPE_CONST, {.i64=val}, INT_MIN, INT_MAX, FLAGS, unit }
Functions
static void filter_line_c (void *dst1, void *prev1, void *cur1, void *next1, int w, int prefs, int mrefs, int parity, int mode)
static void filter_edges (void *dst1, void *prev1, void *cur1, void *next1, int w, int prefs, int mrefs, int parity, int mode)
static void filter_line_c_16bit (void *dst1, void *prev1, void *cur1, void *next1, int w, int prefs, int mrefs, int parity, int mode)
static void filter_edges_16bit (void *dst1, void *prev1, void *cur1, void *next1, int w, int prefs, int mrefs, int parity, int mode)
static int filter_slice (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static void filter (AVFilterContext *ctx, AVFrame *dstpic, int parity, int tff)
static int return_frame (AVFilterContext *ctx, int is_second)
static int checkstride (YADIFContext *yadif, const AVFrame *a, const AVFrame *b)
static void fixstride (AVFilterLink *link, AVFrame *f)
static int filter_frame (AVFilterLink *link, AVFrame *frame)
static int request_frame (AVFilterLink *link)
static av_cold void uninit (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static int config_props (AVFilterLink *link)
AVFILTER_DEFINE_CLASS (yadif)
Variables
static const AVOption yadif_options []
static const AVFilterPad avfilter_vf_yadif_inputs []
static const AVFilterPad avfilter_vf_yadif_outputs []
AVFilter ff_vf_yadif
Macro Definition Documentation
CHECK
#define CHECK (j)
Value:
{   int score = FFABS(cur[mrefs - 1 + (j)] - cur[prefs - 1 - (j)])\
                  + FFABS(cur[mrefs  +(j)] - cur[prefs  -(j)])\
                  + FFABS(cur[mrefs + 1 + (j)] - cur[prefs + 1 - (j)]);\
        if (score < spatial_score) {\
            spatial_score= score;\
            spatial_pred= (cur[mrefs  +(j)] + cur[prefs  -(j)])>>1;\
Definition at line 42 of file vf_yadif.c.
FILTER
#define FILTER (start, end, is_not_edge)
Definition at line 53 of file vf_yadif.c.
Referenced by filter_edges(), filter_edges_16bit(), filter_line_c(), and filter_line_c_16bit().
MAX_ALIGN
#define MAX_ALIGN 8
Definition at line 114 of file vf_yadif.c.
Referenced by filter_edges(), filter_edges_16bit(), and filter_slice().
OFFSET
#define OFFSET (x) offsetof(YADIFContext, x)
Definition at line 504 of file vf_yadif.c.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 505 of file vf_yadif.c.
CONST
#define CONST (name, help, val, unit) { name, help, 0, AV_OPT_TYPE_CONST, {.i64=val}, INT_MIN, INT_MAX, FLAGS, unit }
Definition at line 507 of file vf_yadif.c.
Function Documentation
filter_line_c()
static void filter_line_c (void * dst1, void * prev1, void * cur1, void * next1, int w, int prefs, int mrefs, int parity, int mode) static
Definition at line 95 of file vf_yadif.c.
Referenced by config_props().
filter_edges()
static void filter_edges (void * dst1, void * prev1, void * cur1, void * next1, int w, int prefs, int mrefs, int parity, int mode) static
Definition at line 115 of file vf_yadif.c.
Referenced by config_props().
filter_line_c_16bit()
static void filter_line_c_16bit (void * dst1, void * prev1, void * cur1, void * next1, int w, int prefs, int mrefs, int parity, int mode) static
Definition at line 142 of file vf_yadif.c.
Referenced by config_props().
filter_edges_16bit()
static void filter_edges_16bit (void * dst1, void * prev1, void * cur1, void * next1, int w, int prefs, int mrefs, int parity, int mode) static
Definition at line 160 of file vf_yadif.c.
Referenced by config_props().
filter_slice()
static int filter_slice (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 186 of file vf_yadif.c.
Referenced by filter().
filter()
static void filter (AVFilterContext * ctx, AVFrame * dstpic, int parity, int tff) static
Definition at line 224 of file vf_yadif.c.
Referenced by return_frame().
return_frame()
static int return_frame (AVFilterContext * ctx, int is_second) static
Definition at line 251 of file vf_yadif.c.
Referenced by filter_frame(), and request_frame().
checkstride()
static int checkstride (YADIFContext * yadif, const AVFrame * a, const AVFrame * b) static
Definition at line 291 of file vf_yadif.c.
Referenced by filter_frame().
fixstride()
static void fixstride (AVFilterLink * link, AVFrame * f) static
Definition at line 300 of file vf_yadif.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * link, AVFrame * frame) static
Definition at line 314 of file vf_yadif.c.
Referenced by request_frame().
request_frame()
static int request_frame (AVFilterLink * link) static
Definition at line 378 of file vf_yadif.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 411 of file vf_yadif.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 420 of file vf_yadif.c.
config_props()
static int config_props (AVFilterLink * link) static
Definition at line 469 of file vf_yadif.c.
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (yadif)
Variable Documentation
yadif_options
const AVOption yadif_options[] static
Initial value:
= {
    { "mode",   "specify the interlacing mode", OFFSET(mode), AV_OPT_TYPE_INT, {.i64=YADIF_MODE_SEND_FRAME}, 0, 3, FLAGS, "mode"},
    CONST("send_frame",           "send one frame for each frame",                                     YADIF_MODE_SEND_FRAME,           "mode"),
    CONST("send_field",           "send one frame for each field",                                     YADIF_MODE_SEND_FIELD,           "mode"),
    CONST("send_frame_nospatial", "send one frame for each frame, but skip spatial interlacing check", YADIF_MODE_SEND_FRAME_NOSPATIAL, "mode"),
    CONST("send_field_nospatial", "send one frame for each field, but skip spatial interlacing check", YADIF_MODE_SEND_FIELD_NOSPATIAL, "mode"),
    { "parity", "specify the assumed picture field parity", OFFSET(parity), AV_OPT_TYPE_INT, {.i64=YADIF_PARITY_AUTO}, -1, 1, FLAGS, "parity" },
    CONST("tff",  "assume top field first",    YADIF_PARITY_TFF,  "parity"),
    CONST("bff",  "assume bottom field first", YADIF_PARITY_BFF,  "parity"),
    CONST("auto", "auto detect parity",        YADIF_PARITY_AUTO, "parity"),
    { "deint", "specify which frames to deinterlace", OFFSET(deint), AV_OPT_TYPE_INT, {.i64=YADIF_DEINT_ALL}, 0, 1, FLAGS, "deint" },
    CONST("all",        "deinterlace all frames",                       YADIF_DEINT_ALL,         "deint"),
    CONST("interlaced", "only deinterlace frames marked as interlaced", YADIF_DEINT_INTERLACED,  "deint"),
    { NULL }
}
Definition at line 509 of file vf_yadif.c.
avfilter_vf_yadif_inputs
const AVFilterPad avfilter_vf_yadif_inputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .filter_frame  = filter_frame,
    },
    { NULL }
}
Definition at line 530 of file vf_yadif.c.
avfilter_vf_yadif_outputs
const AVFilterPad avfilter_vf_yadif_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .request_frame = request_frame,
        .config_props  = config_props,
    },
    { NULL }
}
Definition at line 539 of file vf_yadif.c.
ff_vf_yadif
AVFilter ff_vf_yadif
Initial value:
= {
    .name          = "yadif",
    .description   = NULL_IF_CONFIG_SMALL("Deinterlace the input image."),
    .priv_size     = sizeof(YADIFContext),
    .priv_class    = &yadif_class,
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = avfilter_vf_yadif_inputs,
    .outputs       = avfilter_vf_yadif_outputs,
    .flags         = AVFILTER_FLAG_SUPPORT_TIMELINE_INTERNAL | AVFILTER_FLAG_SLICE_THREADS,
}
Definition at line 549 of file vf_yadif.c.