FFmpeg: libavfilter/vf_vaguedenoiser.c File Reference
vf_vaguedenoiser.c File Reference
#include <float.h>
#include "libavutil/imgutils.h"
#include "libavutil/attributes.h"
#include "libavutil/common.h"
#include "libavutil/pixdesc.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/opt.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
Data Structures
struct VagueDenoiserContext
Macros
#define OFFSET(x) offsetof(VagueDenoiserContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_FILTERING_PARAM
#define NPAD 10
Functions
AVFILTER_DEFINE_CLASS (vaguedenoiser)
static int query_formats (AVFilterContext *ctx)
static int config_input (AVFilterLink *inlink)
static void copy (const float *p1, float *p2, const int length)
static void copyv (const float *p1, const int stride1, float *p2, const int length)
static void copyh (const float *p1, float *p2, const int stride2, const int length)
static void symmetric_extension (float *output, const int size, const int left_ext, const int right_ext)
static void transform_step (float *input, float *output, const int size, const int low_size, VagueDenoiserContext *s)
static void invert_step (const float *input, float *output, float *temp, const int size, VagueDenoiserContext *s)
static void hard_thresholding (float *block, const int width, const int height, const int stride, const float threshold, const float percent, const int unused)
static void soft_thresholding (float *block, const int width, const int height, const int stride, const float threshold, const float percent, const int nsteps)
static void qian_thresholding (float *block, const int width, const int height, const int stride, const float threshold, const float percent, const int unused)
static void filter (VagueDenoiserContext *s, AVFrame *in, AVFrame *out)
static int filter_frame (AVFilterLink *inlink, AVFrame *in)
static av_cold int init (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const AVOption vaguedenoiser_options []
static const float analysis_low [9]
static const float analysis_high [7]
static const float synthesis_low [7]
static const float synthesis_high [9]
static const AVFilterPad vaguedenoiser_inputs []
static const AVFilterPad vaguedenoiser_outputs []
AVFilter ff_vf_vaguedenoiser
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(VagueDenoiserContext, x)
Definition at line 65 of file vf_vaguedenoiser.c.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_FILTERING_PARAM
Definition at line 66 of file vf_vaguedenoiser.c.
NPAD
#define NPAD 10
Definition at line 81 of file vf_vaguedenoiser.c.
Referenced by filter(), invert_step(), symmetric_extension(), and transform_step().
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (vaguedenoiser)
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 103 of file vf_vaguedenoiser.c.
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 131 of file vf_vaguedenoiser.c.
copy()
static void copy (const float * p1, float * p2, const int length) inline static
Definition at line 183 of file vf_vaguedenoiser.c.
Referenced by av_buffersrc_add_frame_flags(), av_buffersrc_add_frame_internal(), avfilter_init_str(), avfilter_register_all(), bayer_to_rgb24_wrapper(), bayer_to_yv12_wrapper(), decode_tdlt(), ff_frame_thread_init(), ff_jni_jstring_to_utf_chars(), filter(), filter_frame(), intlist_read(), intra_predict(), qpeg_decode_intra(), read_thread(), roq_decode_frame(), and rtmp_write().
copyv()
static void copyv (const float * p1, const int stride1, float * p2, const int length) inline static
Definition at line 188 of file vf_vaguedenoiser.c.
Referenced by filter().
copyh()
static void copyh (const float * p1, float * p2, const int stride2, const int length) inline static
Definition at line 198 of file vf_vaguedenoiser.c.
Referenced by filter().
symmetric_extension()
static void symmetric_extension (float * output, const int size, const int left_ext, const int right_ext) static
Definition at line 214 of file vf_vaguedenoiser.c.
Referenced by invert_step(), and transform_step().
transform_step()
static void transform_step (float * input, float * output, const int size, const int low_size, VagueDenoiserContext * s) static
Definition at line 239 of file vf_vaguedenoiser.c.
Referenced by filter().
invert_step()
static void invert_step (const float * input, float * output, float * temp, const int size, VagueDenoiserContext * s) static
Definition at line 272 of file vf_vaguedenoiser.c.
Referenced by filter().
hard_thresholding()
static void hard_thresholding (float * block, const int width, const int height, const int stride, const float threshold, const float percent, const int unused) static
Definition at line 327 of file vf_vaguedenoiser.c.
Referenced by init().
soft_thresholding()
static void soft_thresholding (float * block, const int width, const int height, const int stride, const float threshold, const float percent, const int nsteps) static
Definition at line 343 of file vf_vaguedenoiser.c.
Referenced by init().
qian_thresholding()
static void qian_thresholding (float * block, const int width, const int height, const int stride, const float threshold, const float percent, const int unused) static
Definition at line 370 of file vf_vaguedenoiser.c.
Referenced by init().
filter()
static void filter (VagueDenoiserContext * s, AVFrame * in, AVFrame * out) static
Definition at line 393 of file vf_vaguedenoiser.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 496 of file vf_vaguedenoiser.c.
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 524 of file vf_vaguedenoiser.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 543 of file vf_vaguedenoiser.c.
Variable Documentation
vaguedenoiser_options
const AVOption vaguedenoiser_options[] static
Initial value:
= {
    { "threshold", "set filtering strength",   OFFSET(threshold), AV_OPT_TYPE_FLOAT, {.dbl=2.},  0,DBL_MAX, FLAGS },
    { "method",    "set filtering method",     OFFSET(method),    AV_OPT_TYPE_INT,   {.i64=2 },  0, 2,      FLAGS, "method" },
        { "hard",   "hard thresholding",       0,                 AV_OPT_TYPE_CONST, {.i64=0},   0, 0,      FLAGS, "method" },
        { "soft",   "soft thresholding",       0,                 AV_OPT_TYPE_CONST, {.i64=1},   0, 0,      FLAGS, "method" },
        { "garrote", "garotte thresholding",   0,                 AV_OPT_TYPE_CONST, {.i64=2},   0, 0,      FLAGS, "method" },
    { "nsteps",    "set number of steps",      OFFSET(nsteps),    AV_OPT_TYPE_INT,   {.i64=6 },  1, 32,     FLAGS },
    { "percent", "set percent of full denoising", OFFSET(percent),AV_OPT_TYPE_FLOAT, {.dbl=85},  0,100,     FLAGS },
    { "planes",    "set planes to filter",     OFFSET(planes),    AV_OPT_TYPE_INT,   {.i64=15 }, 0, 15,     FLAGS },
    { NULL }
}
Definition at line 67 of file vf_vaguedenoiser.c.
analysis_low
const float analysis_low[9] static
Initial value:
= {
    0.037828455506995f, -0.023849465019380f, -0.110624404418423f, 0.377402855612654f,
    0.852698679009403f, 0.377402855612654f, -0.110624404418423f, -0.023849465019380f, 0.037828455506995f
}
Definition at line 83 of file vf_vaguedenoiser.c.
Referenced by transform_step().
analysis_high
const float analysis_high[7] static
Initial value:
= {
    -0.064538882628938f, 0.040689417609558f, 0.418092273222212f, -0.788485616405664f,
    0.418092273222212f, 0.040689417609558f, -0.064538882628938f
}
Definition at line 88 of file vf_vaguedenoiser.c.
Referenced by transform_step().
synthesis_low
const float synthesis_low[7] static
Initial value:
= {
    -0.064538882628938f, -0.040689417609558f, 0.418092273222212f, 0.788485616405664f,
    0.418092273222212f, -0.040689417609558f, -0.064538882628938f
}
Definition at line 93 of file vf_vaguedenoiser.c.
Referenced by invert_step().
synthesis_high
const float synthesis_high[9] static
Initial value:
= {
    -0.037828455506995f, -0.023849465019380f, 0.110624404418423f, 0.377402855612654f,
    -0.852698679009403f, 0.377402855612654f, 0.110624404418423f, -0.023849465019380f, -0.037828455506995f
}
Definition at line 98 of file vf_vaguedenoiser.c.
Referenced by invert_step().
vaguedenoiser_inputs
const AVFilterPad vaguedenoiser_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .config_props = config_input,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 553 of file vf_vaguedenoiser.c.
vaguedenoiser_outputs
const AVFilterPad vaguedenoiser_outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_VIDEO
    },
    { NULL }
}
Definition at line 564 of file vf_vaguedenoiser.c.
ff_vf_vaguedenoiser
AVFilter ff_vf_vaguedenoiser
Initial value:
= {
    .name          = "vaguedenoiser",
    .description   = NULL_IF_CONFIG_SMALL("Apply a Wavelet based Denoiser."),
    .priv_size     = sizeof(VagueDenoiserContext),
    .priv_class    = &vaguedenoiser_class,
    .init          = init,
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = vaguedenoiser_inputs,
    .outputs       = vaguedenoiser_outputs,
    .flags         = AVFILTER_FLAG_SUPPORT_TIMELINE_GENERIC,
}
Definition at line 572 of file vf_vaguedenoiser.c.