FFmpeg: libavfilter/vf_showinfo.c File Reference
vf_showinfo.c File Reference
filter for showing textual video frame information
#include <inttypes.h>
#include "libavutil/adler32.h"
#include "libavutil/display.h"
#include "libavutil/imgutils.h"
#include "libavutil/internal.h"
#include "libavutil/pixdesc.h"
#include "libavutil/stereo3d.h"
#include "libavutil/timestamp.h"
#include "avfilter.h"
#include "internal.h"
#include "video.h"
Functions
static void dump_stereo3d (AVFilterContext *ctx, AVFrameSideData *sd)
static void update_sample_stats (const uint8_t *src, int len, int64_t *sum, int64_t *sum2)
static int filter_frame (AVFilterLink *inlink, AVFrame *frame)
static int config_props (AVFilterContext *ctx, AVFilterLink *link, int is_out)
static int config_props_in (AVFilterLink *link)
static int config_props_out (AVFilterLink *link)
Variables
static const AVFilterPad avfilter_vf_showinfo_inputs []
static const AVFilterPad avfilter_vf_showinfo_outputs []
AVFilter ff_vf_showinfo
Detailed Description
filter for showing textual video frame information
Definition in file vf_showinfo.c.
Function Documentation
dump_stereo3d()
static void dump_stereo3d (AVFilterContext * ctx, AVFrameSideData * sd) static
Definition at line 39 of file vf_showinfo.c.
Referenced by filter_frame().
update_sample_stats()
static void update_sample_stats (const uint8_t * src, int len, int64_t * sum, int64_t * sum2) static
Definition at line 69 of file vf_showinfo.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * frame) static
Definition at line 79 of file vf_showinfo.c.
config_props()
static int config_props (AVFilterContext * ctx, AVFilterLink * link, int is_out) static
Definition at line 165 of file vf_showinfo.c.
Referenced by config_props_in(), and config_props_out().
config_props_in()
static int config_props_in (AVFilterLink * link) static
Definition at line 176 of file vf_showinfo.c.
config_props_out()
static int config_props_out (AVFilterLink * link) static
Definition at line 182 of file vf_showinfo.c.
Variable Documentation
avfilter_vf_showinfo_inputs
const AVFilterPad avfilter_vf_showinfo_inputs[] static
Initial value:
= {
    {
        .name             = "default",
        .type             = AVMEDIA_TYPE_VIDEO,
        .filter_frame     = filter_frame,
        .config_props     = config_props_in,
    },
    { NULL }
}
Definition at line 188 of file vf_showinfo.c.
avfilter_vf_showinfo_outputs
const AVFilterPad avfilter_vf_showinfo_outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_VIDEO,
        .config_props  = config_props_out,
    },
    { NULL }
}
Definition at line 198 of file vf_showinfo.c.
ff_vf_showinfo
AVFilter ff_vf_showinfo
Initial value:
= {
    .name        = "showinfo",
    .description = NULL_IF_CONFIG_SMALL("Show textual information for each video frame."),
    .inputs      = avfilter_vf_showinfo_inputs,
    .outputs     = avfilter_vf_showinfo_outputs,
}
Definition at line 207 of file vf_showinfo.c.