FFmpeg: libavfilter/x86/vf_w3fdif_init.c File Reference
vf_w3fdif_init.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/mem.h"
#include "libavutil/x86/asm.h"
#include "libavutil/x86/cpu.h"
#include "libavfilter/w3fdif.h"
Functions
void ff_w3fdif_simple_low_sse2 (int32_t *work_line, uint8_t *in_lines_cur[2], const int16_t *coef, int linesize)
void ff_w3fdif_simple_high_sse2 (int32_t *work_line, uint8_t *in_lines_cur[3], uint8_t *in_lines_adj[3], const int16_t *coef, int linesize)
void ff_w3fdif_complex_low_sse2 (int32_t *work_line, uint8_t *in_lines_cur[4], const int16_t *coef, int linesize)
void ff_w3fdif_complex_high_sse2 (int32_t *work_line, uint8_t *in_lines_cur[5], uint8_t *in_lines_adj[5], const int16_t *coef, int linesize)
void ff_w3fdif_scale_sse2 (uint8_t *out_pixel, const int32_t *work_pixel, int linesize, int max)
av_cold void ff_w3fdif_init_x86 (W3FDIFDSPContext *dsp, int depth)
Function Documentation
ff_w3fdif_simple_low_sse2()
void ff_w3fdif_simple_low_sse2 (int32_t * work_line, uint8_t * in_lines_cur[2], const int16_t * coef, int linesize)
Referenced by ff_w3fdif_init_x86().
ff_w3fdif_simple_high_sse2()
void ff_w3fdif_simple_high_sse2 (int32_t * work_line, uint8_t * in_lines_cur[3], uint8_t * in_lines_adj[3], const int16_t * coef, int linesize)
Referenced by ff_w3fdif_init_x86().
ff_w3fdif_complex_low_sse2()
void ff_w3fdif_complex_low_sse2 (int32_t * work_line, uint8_t * in_lines_cur[4], const int16_t * coef, int linesize)
Referenced by ff_w3fdif_init_x86().
ff_w3fdif_complex_high_sse2()
void ff_w3fdif_complex_high_sse2 (int32_t * work_line, uint8_t * in_lines_cur[5], uint8_t * in_lines_adj[5], const int16_t * coef, int linesize)
Referenced by ff_w3fdif_init_x86().
ff_w3fdif_scale_sse2()
void ff_w3fdif_scale_sse2 (uint8_t * out_pixel, const int32_t * work_pixel, int linesize, int max)
Referenced by ff_w3fdif_init_x86().
ff_w3fdif_init_x86()
av_cold void ff_w3fdif_init_x86 (W3FDIFDSPContext * dsp, int depth)
Definition at line 49 of file vf_w3fdif_init.c.
Referenced by config_input().