FFmpeg: libavfilter/vf_drawtext.c File Reference
vf_drawtext.c File Reference
drawtext filter, based on the original vhook/drawtext.c filter by Gustavo Sverzut Barbieri
#include "config.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <time.h>
#include <fenv.h>
#include "libavutil/avstring.h"
#include "libavutil/bprint.h"
#include "libavutil/common.h"
#include "libavutil/file.h"
#include "libavutil/eval.h"
#include "libavutil/opt.h"
#include "libavutil/random_seed.h"
#include "libavutil/parseutils.h"
#include "libavutil/timecode.h"
#include "libavutil/time_internal.h"
#include "libavutil/tree.h"
#include "libavutil/lfg.h"
#include "avfilter.h"
#include "drawutils.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
#include <ft2build.h>
#include <FT_FREETYPE_H>
#include <FT_GLYPH_H>
#include <FT_STROKER_H>
#include <FT_ERRORS_H>
Data Structures
struct DrawTextContext
struct ft_error
struct drawtext_function
Macros
#define OFFSET(x) offsetof(DrawTextContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
#define FT_ERROR_START_LIST {
#define FT_ERRORDEF(e, v, s) { (e), (s) },
#define FT_ERROR_END_LIST { 0, NULL } };
#define FT_ERRMSG(e) ft_errors[e].err_msg
Typedefs
typedef double(* eval_func2) (void *, double a, double b)
Enumerations
enum var_name {
VAR_CH, VAR_N, VAR_NB_IN_CHANNELS, VAR_NB_OUT_CHANNELS,
VAR_T, VAR_S, VAR_VARS_NB, VAR_VALUE1,
VAR_VALUE2, VAR_VARS_NB, VAR_TB, VAR_PTS,
VAR_START_PTS, VAR_PREV_PTS, VAR_PREV_SELECTED_PTS, VAR_T,
VAR_START_T, VAR_PREV_T, VAR_PREV_SELECTED_T, VAR_PICT_TYPE,
VAR_I, VAR_P, VAR_B, VAR_S,
VAR_SI, VAR_SP, VAR_BI, VAR_PICT_TYPE_I,
VAR_PICT_TYPE_P, VAR_PICT_TYPE_B, VAR_PICT_TYPE_S, VAR_PICT_TYPE_SI,
VAR_PICT_TYPE_SP, VAR_PICT_TYPE_BI, VAR_INTERLACE_TYPE, VAR_INTERLACE_TYPE_P,
VAR_INTERLACE_TYPE_T, VAR_INTERLACE_TYPE_B, VAR_CONSUMED_SAMPLES_N, VAR_SAMPLES_N,
VAR_SAMPLE_RATE, VAR_N, VAR_SELECTED_N, VAR_PREV_SELECTED_N,
VAR_KEY, VAR_POS, VAR_SCENE, VAR_CONCATDEC_SELECT,
VAR_VARS_NB, VAR_FRAME_RATE, VAR_INTERLACED, VAR_N,
VAR_NB_CONSUMED_SAMPLES, VAR_NB_SAMPLES, VAR_POS, VAR_PREV_INPTS,
VAR_PREV_INT, VAR_PREV_OUTPTS, VAR_PREV_OUTT, VAR_PTS,
VAR_SAMPLE_RATE, VAR_STARTPTS, VAR_STARTT, VAR_T,
VAR_TB, VAR_RTCTIME, VAR_RTCSTART, VAR_S,
VAR_SR, VAR_VARS_NB, VAR_AVTB, VAR_INTB,
VAR_SR, VAR_VARS_NB, VAR_W, VAR_H,
VAR_A, VAR_DAR, VAR_SAR, VAR_HSUB,
VAR_VSUB, VARS_NB, VAR_W, VAR_H,
VAR_CW, VAR_CH, VAR_HSUB, VAR_VSUB,
VARS_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_A, VAR_SAR, VAR_DAR,
VAR_HSUB, VAR_VSUB, VAR_X, VAR_Y,
VAR_N, VAR_POS, VAR_T, VAR_VARS_NB,
VAR_DAR, VAR_HSUB, VAR_VSUB, VAR_IN_H,
VAR_IH, VAR_IN_W, VAR_IW, VAR_SAR,
VAR_X, VAR_Y, VAR_H, VAR_W,
VAR_T, VAR_MAX, VARS_NB, VAR_DAR,
VAR_HSUB, VAR_VSUB, VAR_LINE_H, VAR_LH,
VAR_MAIN_H, VAR_h, VAR_H, VAR_MAIN_W,
VAR_w, VAR_W, VAR_MAX_GLYPH_A, VAR_ASCENT,
VAR_MAX_GLYPH_D, VAR_DESCENT, VAR_MAX_GLYPH_H, VAR_MAX_GLYPH_W,
VAR_N, VAR_SAR, VAR_T, VAR_TEXT_H,
VAR_TH, VAR_TEXT_W, VAR_TW, VAR_X,
VAR_Y, VAR_PICT_TYPE, VAR_VARS_NB, VAR_N,
VAR_POS, VAR_R, VAR_T, VAR_NB,
VAR_N, VAR_PTS, VAR_R, VAR_T,
VAR_TB, VAR_NB, VAR_W, VAR_H,
VAR_VAL, VAR_MAXVAL, VAR_MINVAL, VAR_NEGVAL,
VAR_CLIPVAL, VAR_VARS_NB, VAR_W, VAR_H,
VAR_X, VAR_Y, VAR_BITDEPTHX, VAR_BITDEPTHY,
VAR_VARS_NB, VAR_MAIN_W, VAR_MW, VAR_MAIN_H,
VAR_MH, VAR_OVERLAY_W, VAR_OW, VAR_OVERLAY_H,
VAR_OH, VAR_HSUB, VAR_VSUB, VAR_X,
VAR_Y, VAR_N, VAR_POS, VAR_T,
VAR_VARS_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_X, VAR_Y, VAR_A,
VAR_SAR, VAR_DAR, VAR_HSUB, VAR_VSUB,
VARS_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_HSUB, VAR_VSUB, VAR_N,
VAR_T, VAR_VARS_NB, VAR_IN_W, VAR_IW,
VAR_IN_H, VAR_IH, VAR_OUT_W, VAR_OW,
VAR_OUT_H, VAR_OH, VAR_A, VAR_SAR,
VAR_DAR, VAR_HSUB, VAR_VSUB, VAR_OHSUB,
VAR_OVSUB, VARS_NB, VAR_PI, VAR_PHI,
VAR_E, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_A, VAR_DAR, VAR_SAR,
VARS_NB, VAR_W, VAR_H, VAR_N,
VAR_PTS, VAR_R, VAR_T, VAR_TB,
VAR_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_IN, VAR_ON, VAR_DURATION,
VAR_PDURATION, VAR_TIME, VAR_FRAME, VAR_ZOOM,
VAR_PZOOM, VAR_X, VAR_PX, VAR_Y,
VAR_PY, VAR_A, VAR_SAR, VAR_DAR,
VAR_HSUB, VAR_VSUB, VARS_NB, VAR_IN_W,
VAR_IW, VAR_IN_H, VAR_IH, VAR_OUT_W,
VAR_OW, VAR_OUT_H, VAR_OH, VAR_A,
VAR_SAR, VAR_DAR, VAR_HSUB, VAR_VSUB,
VAR_OHSUB, VAR_OVSUB, VARS_NB, VAR_X,
VAR_Y, VAR_W, VAR_H, VAR_TIME,
VAR_SPEED, VAR_TEMPO, VAR_ORDER, VAR_PATTERN,
VAR_ROW, VAR_VARS_NB
}
enum expansion_mode { EXP_NONE, EXP_NORMAL, EXP_STRFTIME }
Functions
static double drand (void *opaque, double min, double max)
AVFILTER_DEFINE_CLASS (drawtext)
static int glyph_cmp (const void *key, const void *b)
static int load_glyph (AVFilterContext *ctx, Glyph **glyph_ptr, uint32_t code)
Load glyphs corresponding to the UTF-32 codepoint code.
static int load_font_file (AVFilterContext *ctx, const char *path, int index)
static int load_font (AVFilterContext *ctx)
static int load_textfile (AVFilterContext *ctx)
static int is_newline (uint32_t c)
static av_cold int init (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static int glyph_enu_free (void *opaque, void *elem)
static av_cold void uninit (AVFilterContext *ctx)
static int config_input (AVFilterLink *inlink)
static int command (AVFilterContext *ctx, const char *cmd, const char *arg, char *res, int res_len, int flags)
static int func_pict_type (AVFilterContext *ctx, AVBPrint *bp, char *fct, unsigned argc, char **argv, int tag)
static int func_pts (AVFilterContext *ctx, AVBPrint *bp, char *fct, unsigned argc, char **argv, int tag)
static int func_frame_num (AVFilterContext *ctx, AVBPrint *bp, char *fct, unsigned argc, char **argv, int tag)
static int func_metadata (AVFilterContext *ctx, AVBPrint *bp, char *fct, unsigned argc, char **argv, int tag)
static int func_strftime (AVFilterContext *ctx, AVBPrint *bp, char *fct, unsigned argc, char **argv, int tag)
static int func_eval_expr (AVFilterContext *ctx, AVBPrint *bp, char *fct, unsigned argc, char **argv, int tag)
static int func_eval_expr_int_format (AVFilterContext *ctx, AVBPrint *bp, char *fct, unsigned argc, char **argv, int tag)
static int eval_function (AVFilterContext *ctx, AVBPrint *bp, char *fct, unsigned argc, char **argv)
static int expand_function (AVFilterContext *ctx, AVBPrint *bp, char **rtext)
static int expand_text (AVFilterContext *ctx, char *text, AVBPrint *bp)
static int draw_glyphs (DrawTextContext *s, AVFrame *frame, int width, int height, FFDrawColor *color, int x, int y, int borderw)
static void update_color_with_alpha (DrawTextContext *s, FFDrawColor *color, const FFDrawColor incolor)
static void update_alpha (DrawTextContext *s)
static int draw_text (AVFilterContext *ctx, AVFrame *frame, int width, int height)
static int filter_frame (AVFilterLink *inlink, AVFrame *frame)
Variables
static const char *const var_names []
static const char *const fun2_names []
static const eval_func2 fun2 []
static const AVOption drawtext_options []
static const struct ft_error ft_errors []
static const struct drawtext_function functions []
static const AVFilterPad avfilter_vf_drawtext_inputs []
static const AVFilterPad avfilter_vf_drawtext_outputs []
AVFilter ff_vf_drawtext
Detailed Description
drawtext filter, based on the original vhook/drawtext.c filter by Gustavo Sverzut Barbieri
Definition in file vf_drawtext.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(DrawTextContext, x)
Definition at line 198 of file vf_drawtext.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 199 of file vf_drawtext.c.
FT_ERROR_START_LIST
#define FT_ERROR_START_LIST {
Definition at line 266 of file vf_drawtext.c.
FT_ERRORDEF
#define FT_ERRORDEF (e, v, s) { (e), (s) },
Definition at line 267 of file vf_drawtext.c.
FT_ERROR_END_LIST
#define FT_ERROR_END_LIST { 0, NULL } };
Definition at line 268 of file vf_drawtext.c.
FT_ERRMSG
#define FT_ERRMSG (e) ft_errors[e].err_msg
Referenced by init(), and load_font_file().
Typedef Documentation
eval_func2
typedef double(* eval_func2) (void *, double a, double b)
Definition at line 103 of file vf_drawtext.c.
Enumeration Type Documentation
var_name
enum var_name
Enumerator
VAR_CH
VAR_N
VAR_NB_IN_CHANNELS
VAR_NB_OUT_CHANNELS
VAR_T
VAR_S
VAR_VARS_NB
VAR_VALUE1
VAR_VALUE2
VAR_VARS_NB
VAR_TB
VAR_PTS
VAR_START_PTS
VAR_PREV_PTS
VAR_PREV_SELECTED_PTS
VAR_T
VAR_START_T
VAR_PREV_T
VAR_PREV_SELECTED_T
VAR_PICT_TYPE
VAR_I
VAR_P
VAR_B
VAR_S
VAR_SI
VAR_SP
VAR_BI
VAR_PICT_TYPE_I
VAR_PICT_TYPE_P
VAR_PICT_TYPE_B
VAR_PICT_TYPE_S
VAR_PICT_TYPE_SI
VAR_PICT_TYPE_SP
VAR_PICT_TYPE_BI
VAR_INTERLACE_TYPE
VAR_INTERLACE_TYPE_P
VAR_INTERLACE_TYPE_T
VAR_INTERLACE_TYPE_B
VAR_CONSUMED_SAMPLES_N
VAR_SAMPLES_N
VAR_SAMPLE_RATE
VAR_N
VAR_SELECTED_N
VAR_PREV_SELECTED_N
VAR_KEY
VAR_POS
VAR_SCENE
VAR_CONCATDEC_SELECT
VAR_VARS_NB
VAR_FRAME_RATE
VAR_INTERLACED
VAR_N
VAR_NB_CONSUMED_SAMPLES
VAR_NB_SAMPLES
VAR_POS
VAR_PREV_INPTS
VAR_PREV_INT
VAR_PREV_OUTPTS
VAR_PREV_OUTT
VAR_PTS
VAR_SAMPLE_RATE
VAR_STARTPTS
VAR_STARTT
VAR_T
VAR_TB
VAR_RTCTIME
VAR_RTCSTART
VAR_S
VAR_SR
VAR_VARS_NB
VAR_AVTB
VAR_INTB
VAR_SR
VAR_VARS_NB
VAR_W
VAR_H
VAR_A
VAR_DAR
VAR_SAR
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_W
VAR_H
VAR_CW
VAR_CH
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_X
VAR_Y
VAR_N
VAR_POS
VAR_T
VAR_VARS_NB
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_IN_H
VAR_IH
VAR_IN_W
VAR_IW
VAR_SAR
VAR_X
VAR_Y
VAR_H
VAR_W
VAR_T
VAR_MAX
VARS_NB
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_LINE_H
VAR_LH
VAR_MAIN_H
VAR_h
VAR_H
VAR_MAIN_W
VAR_w
VAR_W
VAR_MAX_GLYPH_A
VAR_ASCENT
VAR_MAX_GLYPH_D
VAR_DESCENT
VAR_MAX_GLYPH_H
VAR_MAX_GLYPH_W
VAR_N
VAR_SAR
VAR_T
VAR_TEXT_H
VAR_TH
VAR_TEXT_W
VAR_TW
VAR_X
VAR_Y
VAR_PICT_TYPE
VAR_VARS_NB
VAR_N
VAR_POS
VAR_R
VAR_T
VAR_NB
VAR_N
VAR_PTS
VAR_R
VAR_T
VAR_TB
VAR_NB
VAR_W
VAR_H
VAR_VAL
VAR_MAXVAL
VAR_MINVAL
VAR_NEGVAL
VAR_CLIPVAL
VAR_VARS_NB
VAR_W
VAR_H
VAR_X
VAR_Y
VAR_BITDEPTHX
VAR_BITDEPTHY
VAR_VARS_NB
VAR_MAIN_W
VAR_MW
VAR_MAIN_H
VAR_MH
VAR_OVERLAY_W
VAR_OW
VAR_OVERLAY_H
VAR_OH
VAR_HSUB
VAR_VSUB
VAR_X
VAR_Y
VAR_N
VAR_POS
VAR_T
VAR_VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_X
VAR_Y
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_HSUB
VAR_VSUB
VAR_N
VAR_T
VAR_VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_OHSUB
VAR_OVSUB
VARS_NB
VAR_PI
VAR_PHI
VAR_E
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_DAR
VAR_SAR
VARS_NB
VAR_W
VAR_H
VAR_N
VAR_PTS
VAR_R
VAR_T
VAR_TB
VAR_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_IN
VAR_ON
VAR_DURATION
VAR_PDURATION
VAR_TIME
VAR_FRAME
VAR_ZOOM
VAR_PZOOM
VAR_X
VAR_PX
VAR_Y
VAR_PY
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_OHSUB
VAR_OVSUB
VARS_NB
VAR_X
VAR_Y
VAR_W
VAR_H
VAR_TIME
VAR_SPEED
VAR_TEMPO
VAR_ORDER
VAR_PATTERN
VAR_ROW
VAR_VARS_NB
Definition at line 110 of file vf_drawtext.c.
expansion_mode
enum expansion_mode
Enumerator
EXP_NONE
EXP_NORMAL
EXP_STRFTIME
Definition at line 131 of file vf_drawtext.c.
Function Documentation
drand()
static double drand (void * opaque, double min, double max) static
Definition at line 98 of file vf_drawtext.c.
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (drawtext)
glyph_cmp()
static int glyph_cmp (const void * key, const void * b) static
Definition at line 291 of file vf_drawtext.c.
Referenced by draw_glyphs(), draw_text(), and load_glyph().
load_glyph()
static int load_glyph (AVFilterContext * ctx, Glyph ** glyph_ptr, uint32_t code) static
Load glyphs corresponding to the UTF-32 codepoint code.
Definition at line 301 of file vf_drawtext.c.
Referenced by draw_text(), and init().
load_font_file()
static int load_font_file (AVFilterContext * ctx, const char * path, int index) static
Definition at line 368 of file vf_drawtext.c.
Referenced by load_font().
load_font()
static int load_font (AVFilterContext * ctx) static
Definition at line 457 of file vf_drawtext.c.
Referenced by init().
load_textfile()
static int load_textfile (AVFilterContext * ctx) static
Definition at line 474 of file vf_drawtext.c.
Referenced by filter_frame(), and init().
is_newline()
static int is_newline (uint32_t c) inline static
Definition at line 501 of file vf_drawtext.c.
Referenced by draw_text().
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 594 of file vf_drawtext.c.
Referenced by command().
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 689 of file vf_drawtext.c.
glyph_enu_free()
static int glyph_enu_free (void * opaque, void * elem) static
Definition at line 694 of file vf_drawtext.c.
Referenced by uninit().
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 704 of file vf_drawtext.c.
Referenced by command().
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 727 of file vf_drawtext.c.
Referenced by command().
command()
static int command (AVFilterContext * ctx, const char * cmd, const char * arg, char * res, int res_len, int flags) static
Definition at line 767 of file vf_drawtext.c.
Referenced by cdg_decode_frame(), check_keyboard_interaction(), decode_subframe_lpc(), ftp_abort(), ftp_current_dir(), ftp_delete(), ftp_file_size(), ftp_list_mlsd(), ftp_list_nlst(), ftp_move(), ftp_passive_mode(), ftp_passive_mode_epsv(), ftp_restart(), ftp_retrieve(), ftp_set_dir(), ftp_store(), ftp_type(), idcin_read_packet(), read_connect(), send_invoke_response(), and uninit().
func_pict_type()
static int func_pict_type (AVFilterContext * ctx, AVBPrint * bp, char * fct, unsigned argc, char ** argv, int tag) static
Definition at line 785 of file vf_drawtext.c.
func_pts()
static int func_pts (AVFilterContext * ctx, AVBPrint * bp, char * fct, unsigned argc, char ** argv, int tag) static
Definition at line 794 of file vf_drawtext.c.
func_frame_num()
static int func_frame_num (AVFilterContext * ctx, AVBPrint * bp, char * fct, unsigned argc, char ** argv, int tag) static
Definition at line 846 of file vf_drawtext.c.
func_metadata()
static int func_metadata (AVFilterContext * ctx, AVBPrint * bp, char * fct, unsigned argc, char ** argv, int tag) static
Definition at line 855 of file vf_drawtext.c.
func_strftime()
static int func_strftime (AVFilterContext * ctx, AVBPrint * bp, char * fct, unsigned argc, char ** argv, int tag) static
Definition at line 868 of file vf_drawtext.c.
func_eval_expr()
static int func_eval_expr (AVFilterContext * ctx, AVBPrint * bp, char * fct, unsigned argc, char ** argv, int tag) static
Definition at line 884 of file vf_drawtext.c.
func_eval_expr_int_format()
static int func_eval_expr_int_format (AVFilterContext * ctx, AVBPrint * bp, char * fct, unsigned argc, char ** argv, int tag) static
Definition at line 904 of file vf_drawtext.c.
eval_function()
static int eval_function (AVFilterContext * ctx, AVBPrint * bp, char * fct, unsigned argc, char ** argv) static
Definition at line 983 of file vf_drawtext.c.
Referenced by expand_function().
expand_function()
static int expand_function (AVFilterContext * ctx, AVBPrint * bp, char ** rtext) static
Definition at line 1010 of file vf_drawtext.c.
Referenced by expand_text().
expand_text()
static int expand_text (AVFilterContext * ctx, char * text, AVBPrint * bp) static
Definition at line 1050 of file vf_drawtext.c.
Referenced by draw_text().
draw_glyphs()
static int draw_glyphs (DrawTextContext * s, AVFrame * frame, int width, int height, FFDrawColor * color, int x, int y, int borderw) static
Definition at line 1073 of file vf_drawtext.c.
Referenced by draw_text().
update_color_with_alpha()
static void update_color_with_alpha (DrawTextContext * s, FFDrawColor * color, const FFDrawColor incolor) static
Definition at line 1117 of file vf_drawtext.c.
Referenced by draw_text().
update_alpha()
static void update_alpha (DrawTextContext * s) static
Definition at line 1124 of file vf_drawtext.c.
Referenced by draw_text().
draw_text()
static int draw_text (AVFilterContext * ctx, AVFrame * frame, int width, int height) static
Definition at line 1139 of file vf_drawtext.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * frame) static
Definition at line 1327 of file vf_drawtext.c.
Variable Documentation
var_names
const char* const var_names[] static
Initial value:
= {
    "dar",
    "hsub", "vsub",
    "line_h", "lh",
    "main_h", "h", "H",
    "main_w", "w", "W",
    "max_glyph_a", "ascent",
    "max_glyph_d", "descent",
    "max_glyph_h",
    "max_glyph_w",
    "n",
    "sar",
    "t",
    "text_h", "th",
    "text_w", "tw",
    "x",
    "y",
    "pict_type",
    NULL
}
Definition at line 73 of file vf_drawtext.c.
Referenced by config_input(), func_eval_expr(), and func_eval_expr_int_format().
fun2_names
const char* const fun2_names[] static
Initial value:
= {
    "rand"
}
Definition at line 94 of file vf_drawtext.c.
Referenced by config_input(), func_eval_expr(), and func_eval_expr_int_format().
fun2
const eval_func2 fun2[] static
Initial value:
= {
    drand,
    NULL
}
Definition at line 105 of file vf_drawtext.c.
Referenced by config_input(), func_eval_expr(), and func_eval_expr_int_format().
drawtext_options
const AVOption drawtext_options[] static
Definition at line 201 of file vf_drawtext.c.
ft_errors
const struct ft_error ft_errors[] static
Initial value:
=
#define FT_ERRMSG(e)
typedef struct Glyph {
    FT_Glyph glyph;
    FT_Glyph border_glyph;
    uint32_t code;
    FT_Bitmap bitmap;
    FT_Bitmap border_bitmap;
    FT_BBox bbox;
    int advance;
    int bitmap_left;
    int bitmap_top;
} Glyph
functions
const struct drawtext_function functions[] static
Initial value:
= {
    { "expr",      1, 1, 0,   func_eval_expr },
    { "e",         1, 1, 0,   func_eval_expr },
    { "expr_int_format", 2, 3, 0, func_eval_expr_int_format },
    { "eif",       2, 3, 0,   func_eval_expr_int_format },
    { "pict_type", 0, 0, 0,   func_pict_type },
    { "pts",       0, 3, 0,   func_pts      },
    { "gmtime",    0, 1, 'G', func_strftime },
    { "localtime", 0, 1, 'L', func_strftime },
    { "frame_num", 0, 0, 0,   func_frame_num },
    { "n",         0, 0, 0,   func_frame_num },
    { "metadata",  1, 2, 0,   func_metadata },
}
Referenced by eval_function().
avfilter_vf_drawtext_inputs
const AVFilterPad avfilter_vf_drawtext_inputs[] static
Initial value:
= {
    {
        .name           = "default",
        .type           = AVMEDIA_TYPE_VIDEO,
        .filter_frame   = filter_frame,
        .config_props   = config_input,
        .needs_writable = 1,
    },
    { NULL }
}
Definition at line 1365 of file vf_drawtext.c.
avfilter_vf_drawtext_outputs
const AVFilterPad avfilter_vf_drawtext_outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_VIDEO,
    },
    { NULL }
}
Definition at line 1376 of file vf_drawtext.c.
ff_vf_drawtext
AVFilter ff_vf_drawtext
Initial value:
= {
    .name          = "drawtext",
    .description   = NULL_IF_CONFIG_SMALL("Draw text on top of video frames using libfreetype library."),
    .priv_size     = sizeof(DrawTextContext),
    .priv_class    = &drawtext_class,
    .init          = init,
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = avfilter_vf_drawtext_inputs,
    .outputs       = avfilter_vf_drawtext_outputs,
    .process_command = command,
    .flags         = AVFILTER_FLAG_SUPPORT_TIMELINE_GENERIC,
}
Definition at line 1384 of file vf_drawtext.c.