FFmpeg: libavfilter/vf_overlay.c File Reference
vf_overlay.c File Reference
overlay one video on top of another
#include "avfilter.h"
#include "formats.h"
#include "libavutil/common.h"
#include "libavutil/eval.h"
#include "libavutil/avstring.h"
#include "libavutil/pixdesc.h"
#include "libavutil/imgutils.h"
#include "libavutil/mathematics.h"
#include "libavutil/opt.h"
#include "libavutil/timestamp.h"
#include "internal.h"
#include "dualinput.h"
#include "drawutils.h"
#include "video.h"
Data Structures
struct OverlayContext
Macros
#define MAIN 0
#define OVERLAY 1
#define R 0
#define G 1
#define B 2
#define A 3
#define Y 0
#define U 1
#define V 2
#define FAST_DIV255(x) ((((x) + 128) * 257) >> 16)
#define UNPREMULTIPLY_ALPHA(x, y) ((((x) << 16) - ((x) << 9) + (x)) / ((((x) + (y)) << 8) - ((x) + (y)) - (y) * (x)))
#define OFFSET(x) offsetof(OverlayContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Enumerations
enum var_name {
VAR_CH, VAR_N, VAR_NB_IN_CHANNELS, VAR_NB_OUT_CHANNELS,
VAR_T, VAR_S, VAR_VARS_NB, VAR_VALUE1,
VAR_VALUE2, VAR_VARS_NB, VAR_TB, VAR_PTS,
VAR_START_PTS, VAR_PREV_PTS, VAR_PREV_SELECTED_PTS, VAR_T,
VAR_START_T, VAR_PREV_T, VAR_PREV_SELECTED_T, VAR_PICT_TYPE,
VAR_I, VAR_P, VAR_B, VAR_S,
VAR_SI, VAR_SP, VAR_BI, VAR_PICT_TYPE_I,
VAR_PICT_TYPE_P, VAR_PICT_TYPE_B, VAR_PICT_TYPE_S, VAR_PICT_TYPE_SI,
VAR_PICT_TYPE_SP, VAR_PICT_TYPE_BI, VAR_INTERLACE_TYPE, VAR_INTERLACE_TYPE_P,
VAR_INTERLACE_TYPE_T, VAR_INTERLACE_TYPE_B, VAR_CONSUMED_SAMPLES_N, VAR_SAMPLES_N,
VAR_SAMPLE_RATE, VAR_N, VAR_SELECTED_N, VAR_PREV_SELECTED_N,
VAR_KEY, VAR_POS, VAR_SCENE, VAR_CONCATDEC_SELECT,
VAR_VARS_NB, VAR_FRAME_RATE, VAR_INTERLACED, VAR_N,
VAR_NB_CONSUMED_SAMPLES, VAR_NB_SAMPLES, VAR_POS, VAR_PREV_INPTS,
VAR_PREV_INT, VAR_PREV_OUTPTS, VAR_PREV_OUTT, VAR_PTS,
VAR_SAMPLE_RATE, VAR_STARTPTS, VAR_STARTT, VAR_T,
VAR_TB, VAR_RTCTIME, VAR_RTCSTART, VAR_S,
VAR_SR, VAR_VARS_NB, VAR_AVTB, VAR_INTB,
VAR_SR, VAR_VARS_NB, VAR_W, VAR_H,
VAR_A, VAR_DAR, VAR_SAR, VAR_HSUB,
VAR_VSUB, VARS_NB, VAR_W, VAR_H,
VAR_CW, VAR_CH, VAR_HSUB, VAR_VSUB,
VARS_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_A, VAR_SAR, VAR_DAR,
VAR_HSUB, VAR_VSUB, VAR_X, VAR_Y,
VAR_N, VAR_POS, VAR_T, VAR_VARS_NB,
VAR_DAR, VAR_HSUB, VAR_VSUB, VAR_IN_H,
VAR_IH, VAR_IN_W, VAR_IW, VAR_SAR,
VAR_X, VAR_Y, VAR_H, VAR_W,
VAR_T, VAR_MAX, VARS_NB, VAR_DAR,
VAR_HSUB, VAR_VSUB, VAR_LINE_H, VAR_LH,
VAR_MAIN_H, VAR_h, VAR_H, VAR_MAIN_W,
VAR_w, VAR_W, VAR_MAX_GLYPH_A, VAR_ASCENT,
VAR_MAX_GLYPH_D, VAR_DESCENT, VAR_MAX_GLYPH_H, VAR_MAX_GLYPH_W,
VAR_N, VAR_SAR, VAR_T, VAR_TEXT_H,
VAR_TH, VAR_TEXT_W, VAR_TW, VAR_X,
VAR_Y, VAR_PICT_TYPE, VAR_VARS_NB, VAR_N,
VAR_POS, VAR_R, VAR_T, VAR_NB,
VAR_N, VAR_PTS, VAR_R, VAR_T,
VAR_TB, VAR_NB, VAR_W, VAR_H,
VAR_VAL, VAR_MAXVAL, VAR_MINVAL, VAR_NEGVAL,
VAR_CLIPVAL, VAR_VARS_NB, VAR_W, VAR_H,
VAR_X, VAR_Y, VAR_BITDEPTHX, VAR_BITDEPTHY,
VAR_VARS_NB, VAR_MAIN_W, VAR_MW, VAR_MAIN_H,
VAR_MH, VAR_OVERLAY_W, VAR_OW, VAR_OVERLAY_H,
VAR_OH, VAR_HSUB, VAR_VSUB, VAR_X,
VAR_Y, VAR_N, VAR_POS, VAR_T,
VAR_VARS_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_X, VAR_Y, VAR_A,
VAR_SAR, VAR_DAR, VAR_HSUB, VAR_VSUB,
VARS_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_HSUB, VAR_VSUB, VAR_N,
VAR_T, VAR_VARS_NB, VAR_IN_W, VAR_IW,
VAR_IN_H, VAR_IH, VAR_OUT_W, VAR_OW,
VAR_OUT_H, VAR_OH, VAR_A, VAR_SAR,
VAR_DAR, VAR_HSUB, VAR_VSUB, VAR_OHSUB,
VAR_OVSUB, VARS_NB, VAR_PI, VAR_PHI,
VAR_E, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_A, VAR_DAR, VAR_SAR,
VARS_NB, VAR_W, VAR_H, VAR_N,
VAR_PTS, VAR_R, VAR_T, VAR_TB,
VAR_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_IN, VAR_ON, VAR_DURATION,
VAR_PDURATION, VAR_TIME, VAR_FRAME, VAR_ZOOM,
VAR_PZOOM, VAR_X, VAR_PX, VAR_Y,
VAR_PY, VAR_A, VAR_SAR, VAR_DAR,
VAR_HSUB, VAR_VSUB, VARS_NB, VAR_IN_W,
VAR_IW, VAR_IN_H, VAR_IH, VAR_OUT_W,
VAR_OW, VAR_OUT_H, VAR_OH, VAR_A,
VAR_SAR, VAR_DAR, VAR_HSUB, VAR_VSUB,
VAR_OHSUB, VAR_OVSUB, VARS_NB, VAR_X,
VAR_Y, VAR_W, VAR_H, VAR_TIME,
VAR_SPEED, VAR_TEMPO, VAR_ORDER, VAR_PATTERN,
VAR_ROW, VAR_VARS_NB
}
enum EOFAction { EOF_ACTION_REPEAT, EOF_ACTION_ENDALL, EOF_ACTION_PASS }
enum EvalMode {
EVAL_MODE_ONCE, EVAL_MODE_FRAME, EVAL_MODE_NB, EVAL_MODE_INIT,
EVAL_MODE_FRAME, EVAL_MODE_NB, EVAL_MODE_INIT, EVAL_MODE_FRAME,
EVAL_MODE_NB, EVAL_MODE_INIT, EVAL_MODE_FRAME, EVAL_MODE_NB,
EVAL_MODE_INIT, EVAL_MODE_FRAME, EVAL_MODE_NB, EVAL_MODE_INIT,
EVAL_MODE_FRAME, EVAL_MODE_NB
}
enum OverlayFormat {
OVERLAY_FORMAT_YUV420, OVERLAY_FORMAT_YUV422, OVERLAY_FORMAT_YUV444, OVERLAY_FORMAT_RGB,
OVERLAY_FORMAT_NB
}
Functions
static av_cold void uninit (AVFilterContext *ctx)
static int normalize_xy (double d, int chroma_sub)
static void eval_expr (AVFilterContext *ctx)
static int set_expr (AVExpr **pexpr, const char *expr, const char *option, void *log_ctx)
static int process_command (AVFilterContext *ctx, const char *cmd, const char *args, char *res, int res_len, int flags)
static int query_formats (AVFilterContext *ctx)
static int config_input_overlay (AVFilterLink *inlink)
static int config_output (AVFilterLink *outlink)
static void blend_image_packed_rgb (AVFilterContext *ctx, AVFrame *dst, const AVFrame *src, int x, int y)
Blend image in src to destination buffer dst at position (x, y).
static av_always_inline void blend_plane (AVFilterContext *ctx, AVFrame *dst, const AVFrame *src, int src_w, int src_h, int dst_w, int dst_h, int i, int hsub, int vsub, int x, int y, int main_has_alpha)
static void alpha_composite (const AVFrame *src, const AVFrame *dst, int src_w, int src_h, int dst_w, int dst_h, int x, int y)
static av_always_inline void blend_image_yuv (AVFilterContext *ctx, AVFrame *dst, const AVFrame *src, int hsub, int vsub, int main_has_alpha, int x, int y)
static void blend_image_yuv420 (AVFilterContext *ctx, AVFrame *dst, const AVFrame *src, int x, int y)
static void blend_image_yuv422 (AVFilterContext *ctx, AVFrame *dst, const AVFrame *src, int x, int y)
static void blend_image_yuv444 (AVFilterContext *ctx, AVFrame *dst, const AVFrame *src, int x, int y)
static int config_input_main (AVFilterLink *inlink)
static AVFrame * do_blend (AVFilterContext *ctx, AVFrame *mainpic, const AVFrame *second)
static int filter_frame (AVFilterLink *inlink, AVFrame *inpicref)
static int request_frame (AVFilterLink *outlink)
static av_cold int init (AVFilterContext *ctx)
AVFILTER_DEFINE_CLASS (overlay)
Variables
static const char *const var_names []
static const char *const eof_action_str []
static enum AVPixelFormat alpha_pix_fmts []
static const AVOption overlay_options []
static const AVFilterPad avfilter_vf_overlay_inputs []
static const AVFilterPad avfilter_vf_overlay_outputs []
AVFilter ff_vf_overlay
Detailed Description
overlay one video on top of another
Definition in file vf_overlay.c.
Macro Definition Documentation
MAIN
#define MAIN 0
Definition at line 83 of file vf_overlay.c.
Referenced by config_input_overlay(), config_output(), and query_formats().
OVERLAY
#define OVERLAY 1
Definition at line 84 of file vf_overlay.c.
Referenced by config_input_overlay(), and query_formats().
R
#define R 0
Definition at line 86 of file vf_overlay.c.
Referenced by blend_image_packed_rgb().
G
#define G 1
Definition at line 87 of file vf_overlay.c.
Referenced by blend_image_packed_rgb().
B
#define B 2
Definition at line 88 of file vf_overlay.c.
Referenced by blend_image_packed_rgb().
A
#define A 3
Definition at line 89 of file vf_overlay.c.
Referenced by blend_image_packed_rgb().
Y
#define Y 0
Definition at line 91 of file vf_overlay.c.
U
#define U 1
Definition at line 92 of file vf_overlay.c.
V
#define V 2
Definition at line 93 of file vf_overlay.c.
FAST_DIV255
#define FAST_DIV255 (x) ((((x) + 128) * 257) >> 16)
Definition at line 378 of file vf_overlay.c.
Referenced by alpha_composite(), blend_image_packed_rgb(), and blend_plane().
UNPREMULTIPLY_ALPHA
#define UNPREMULTIPLY_ALPHA (x, y) ((((x) << 16) - ((x) << 9) + (x)) / ((((x) + (y)) << 8) - ((x) + (y)) - (y) * (x)))
Definition at line 384 of file vf_overlay.c.
Referenced by alpha_composite(), blend_image_packed_rgb(), and blend_plane().
OFFSET
#define OFFSET (x) offsetof(OverlayContext, x)
Definition at line 728 of file vf_overlay.c.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 729 of file vf_overlay.c.
Enumeration Type Documentation
var_name
enum var_name
Enumerator
VAR_CH
VAR_N
VAR_NB_IN_CHANNELS
VAR_NB_OUT_CHANNELS
VAR_T
VAR_S
VAR_VARS_NB
VAR_VALUE1
VAR_VALUE2
VAR_VARS_NB
VAR_TB
VAR_PTS
VAR_START_PTS
VAR_PREV_PTS
VAR_PREV_SELECTED_PTS
VAR_T
VAR_START_T
VAR_PREV_T
VAR_PREV_SELECTED_T
VAR_PICT_TYPE
VAR_I
VAR_P
VAR_B
VAR_S
VAR_SI
VAR_SP
VAR_BI
VAR_PICT_TYPE_I
VAR_PICT_TYPE_P
VAR_PICT_TYPE_B
VAR_PICT_TYPE_S
VAR_PICT_TYPE_SI
VAR_PICT_TYPE_SP
VAR_PICT_TYPE_BI
VAR_INTERLACE_TYPE
VAR_INTERLACE_TYPE_P
VAR_INTERLACE_TYPE_T
VAR_INTERLACE_TYPE_B
VAR_CONSUMED_SAMPLES_N
VAR_SAMPLES_N
VAR_SAMPLE_RATE
VAR_N
VAR_SELECTED_N
VAR_PREV_SELECTED_N
VAR_KEY
VAR_POS
VAR_SCENE
VAR_CONCATDEC_SELECT
VAR_VARS_NB
VAR_FRAME_RATE
VAR_INTERLACED
VAR_N
VAR_NB_CONSUMED_SAMPLES
VAR_NB_SAMPLES
VAR_POS
VAR_PREV_INPTS
VAR_PREV_INT
VAR_PREV_OUTPTS
VAR_PREV_OUTT
VAR_PTS
VAR_SAMPLE_RATE
VAR_STARTPTS
VAR_STARTT
VAR_T
VAR_TB
VAR_RTCTIME
VAR_RTCSTART
VAR_S
VAR_SR
VAR_VARS_NB
VAR_AVTB
VAR_INTB
VAR_SR
VAR_VARS_NB
VAR_W
VAR_H
VAR_A
VAR_DAR
VAR_SAR
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_W
VAR_H
VAR_CW
VAR_CH
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_X
VAR_Y
VAR_N
VAR_POS
VAR_T
VAR_VARS_NB
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_IN_H
VAR_IH
VAR_IN_W
VAR_IW
VAR_SAR
VAR_X
VAR_Y
VAR_H
VAR_W
VAR_T
VAR_MAX
VARS_NB
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_LINE_H
VAR_LH
VAR_MAIN_H
VAR_h
VAR_H
VAR_MAIN_W
VAR_w
VAR_W
VAR_MAX_GLYPH_A
VAR_ASCENT
VAR_MAX_GLYPH_D
VAR_DESCENT
VAR_MAX_GLYPH_H
VAR_MAX_GLYPH_W
VAR_N
VAR_SAR
VAR_T
VAR_TEXT_H
VAR_TH
VAR_TEXT_W
VAR_TW
VAR_X
VAR_Y
VAR_PICT_TYPE
VAR_VARS_NB
VAR_N
VAR_POS
VAR_R
VAR_T
VAR_NB
VAR_N
VAR_PTS
VAR_R
VAR_T
VAR_TB
VAR_NB
VAR_W
VAR_H
VAR_VAL
VAR_MAXVAL
VAR_MINVAL
VAR_NEGVAL
VAR_CLIPVAL
VAR_VARS_NB
VAR_W
VAR_H
VAR_X
VAR_Y
VAR_BITDEPTHX
VAR_BITDEPTHY
VAR_VARS_NB
VAR_MAIN_W
VAR_MW
VAR_MAIN_H
VAR_MH
VAR_OVERLAY_W
VAR_OW
VAR_OVERLAY_H
VAR_OH
VAR_HSUB
VAR_VSUB
VAR_X
VAR_Y
VAR_N
VAR_POS
VAR_T
VAR_VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_X
VAR_Y
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_HSUB
VAR_VSUB
VAR_N
VAR_T
VAR_VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_OHSUB
VAR_OVSUB
VARS_NB
VAR_PI
VAR_PHI
VAR_E
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_DAR
VAR_SAR
VARS_NB
VAR_W
VAR_H
VAR_N
VAR_PTS
VAR_R
VAR_T
VAR_TB
VAR_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_IN
VAR_ON
VAR_DURATION
VAR_PDURATION
VAR_TIME
VAR_FRAME
VAR_ZOOM
VAR_PZOOM
VAR_X
VAR_PX
VAR_Y
VAR_PY
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_OHSUB
VAR_OVSUB
VARS_NB
VAR_X
VAR_Y
VAR_W
VAR_H
VAR_TIME
VAR_SPEED
VAR_TEMPO
VAR_ORDER
VAR_PATTERN
VAR_ROW
VAR_VARS_NB
Definition at line 58 of file vf_overlay.c.
EOFAction
enum EOFAction
Enumerator
EOF_ACTION_REPEAT
EOF_ACTION_ENDALL
EOF_ACTION_PASS
Definition at line 73 of file vf_overlay.c.
EvalMode
enum EvalMode
Enumerator
EVAL_MODE_ONCE
EVAL_MODE_FRAME
EVAL_MODE_NB
EVAL_MODE_INIT
EVAL_MODE_FRAME
EVAL_MODE_NB
EVAL_MODE_INIT
EVAL_MODE_FRAME
EVAL_MODE_NB
EVAL_MODE_INIT
EVAL_MODE_FRAME
EVAL_MODE_NB
EVAL_MODE_INIT
EVAL_MODE_FRAME
EVAL_MODE_NB
EVAL_MODE_INIT
EVAL_MODE_FRAME
EVAL_MODE_NB
Definition at line 95 of file vf_overlay.c.
OverlayFormat
enum OverlayFormat
Enumerator
OVERLAY_FORMAT_YUV420
OVERLAY_FORMAT_YUV422
OVERLAY_FORMAT_YUV444
OVERLAY_FORMAT_RGB
OVERLAY_FORMAT_NB
Definition at line 101 of file vf_overlay.c.
Function Documentation
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 140 of file vf_overlay.c.
normalize_xy()
static int normalize_xy (double d, int chroma_sub) inline static
Definition at line 149 of file vf_overlay.c.
Referenced by eval_expr().
eval_expr()
static void eval_expr (AVFilterContext * ctx) static
Definition at line 156 of file vf_overlay.c.
Referenced by config_input_overlay(), do_blend(), and process_command().
set_expr()
static int set_expr (AVExpr ** pexpr, const char * expr, const char * option, void * log_ctx) static
Definition at line 167 of file vf_overlay.c.
Referenced by config_input_overlay(), and process_command().
process_command()
static int process_command (AVFilterContext * ctx, const char * cmd, const char * args, char * res, int res_len, int flags) static
Definition at line 188 of file vf_overlay.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 213 of file vf_overlay.c.
config_input_overlay()
static int config_input_overlay (AVFilterLink * inlink) static
Definition at line 312 of file vf_overlay.c.
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 360 of file vf_overlay.c.
blend_image_packed_rgb()
static void blend_image_packed_rgb (AVFilterContext * ctx, AVFrame * dst, const AVFrame * src, int x, int y) static
Blend image in src to destination buffer dst at position (x, y).
< the amount of overlay to blend on to main
Definition at line 390 of file vf_overlay.c.
Referenced by config_input_main().
blend_plane()
static av_always_inline void blend_plane (AVFilterContext * ctx, AVFrame * dst, const AVFrame * src, int src_w, int src_h, int dst_w, int dst_h, int i, int hsub, int vsub, int x, int y, int main_has_alpha) static
Definition at line 468 of file vf_overlay.c.
Referenced by blend_image_yuv().
alpha_composite()
static void alpha_composite (const AVFrame * src, const AVFrame * dst, int src_w, int src_h, int dst_w, int dst_h, int x, int y) inline static
< the amount of overlay to blend on to main
Definition at line 547 of file vf_overlay.c.
Referenced by blend_image_yuv().
blend_image_yuv()
static av_always_inline void blend_image_yuv (AVFilterContext * ctx, AVFrame * dst, const AVFrame * src, int hsub, int vsub, int main_has_alpha, int x, int y) static
Definition at line 589 of file vf_overlay.c.
Referenced by blend_image_yuv420(), blend_image_yuv422(), and blend_image_yuv444().
blend_image_yuv420()
static void blend_image_yuv420 (AVFilterContext * ctx, AVFrame * dst, const AVFrame * src, int x, int y) static
Definition at line 608 of file vf_overlay.c.
Referenced by config_input_main().
blend_image_yuv422()
static void blend_image_yuv422 (AVFilterContext * ctx, AVFrame * dst, const AVFrame * src, int x, int y) static
Definition at line 615 of file vf_overlay.c.
Referenced by config_input_main().
blend_image_yuv444()
static void blend_image_yuv444 (AVFilterContext * ctx, AVFrame * dst, const AVFrame * src, int x, int y) static
Definition at line 622 of file vf_overlay.c.
Referenced by config_input_main().
config_input_main()
static int config_input_main (AVFilterLink * inlink) static
Definition at line 629 of file vf_overlay.c.
do_blend()
static AVFrame* do_blend (AVFilterContext * ctx, AVFrame * mainpic, const AVFrame * second) static
Definition at line 661 of file vf_overlay.c.
Referenced by init().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * inpicref) static
Definition at line 693 of file vf_overlay.c.
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 700 of file vf_overlay.c.
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 706 of file vf_overlay.c.
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (overlay)
Variable Documentation
var_names
const char* const var_names[] static
Initial value:
= {
    "main_w",    "W",
    "main_h",    "H",
    "overlay_w", "w",
    "overlay_h", "h",
    "hsub",
    "vsub",
    "x",
    "y",
    "n",
    "pos",
    "t",
    NULL
}
Definition at line 43 of file vf_overlay.c.
Referenced by set_expr().
eof_action_str
const char* const eof_action_str[] static
Initial value:
= {
    "repeat", "endall", "pass"
}
Definition at line 79 of file vf_overlay.c.
Referenced by config_input_overlay().
alpha_pix_fmts
enum AVPixelFormat alpha_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_YUVA420P, AV_PIX_FMT_YUVA422P, AV_PIX_FMT_YUVA444P,
    AV_PIX_FMT_ARGB, AV_PIX_FMT_ABGR, AV_PIX_FMT_RGBA,
    AV_PIX_FMT_BGRA, AV_PIX_FMT_NONE
}
Definition at line 306 of file vf_overlay.c.
Referenced by config_input_main(), and config_input_overlay().
overlay_options
const AVOption overlay_options[] static
Initial value:
= {
    { "x", "set the x expression", OFFSET(x_expr), AV_OPT_TYPE_STRING, {.str = "0"}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "y", "set the y expression", OFFSET(y_expr), AV_OPT_TYPE_STRING, {.str = "0"}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "eof_action", "Action to take when encountering EOF from secondary input ",
        OFFSET(eof_action), AV_OPT_TYPE_INT, { .i64 = EOF_ACTION_REPEAT },
        EOF_ACTION_REPEAT, EOF_ACTION_PASS, .flags = FLAGS, "eof_action" },
        { "repeat", "Repeat the previous frame.",   0, AV_OPT_TYPE_CONST, { .i64 = EOF_ACTION_REPEAT }, .flags = FLAGS, "eof_action" },
        { "endall", "End both streams.",            0, AV_OPT_TYPE_CONST, { .i64 = EOF_ACTION_ENDALL }, .flags = FLAGS, "eof_action" },
        { "pass",   "Pass through the main input.", 0, AV_OPT_TYPE_CONST, { .i64 = EOF_ACTION_PASS },   .flags = FLAGS, "eof_action" },
    { "eval", "specify when to evaluate expressions", OFFSET(eval_mode), AV_OPT_TYPE_INT, {.i64 = EVAL_MODE_FRAME}, 0, EVAL_MODE_NB-1, FLAGS, "eval" },
         { "init",  "eval expressions once during initialization", 0, AV_OPT_TYPE_CONST, {.i64=EVAL_MODE_INIT},  .flags = FLAGS, .unit = "eval" },
         { "frame", "eval expressions per-frame",                  0, AV_OPT_TYPE_CONST, {.i64=EVAL_MODE_FRAME}, .flags = FLAGS, .unit = "eval" },
    { "rgb", "force packed RGB in input and output (deprecated)", OFFSET(allow_packed_rgb), AV_OPT_TYPE_BOOL, {.i64=0}, 0, 1, FLAGS },
    { "shortest", "force termination when the shortest input terminates", OFFSET(dinput.shortest), AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, FLAGS },
    { "format", "set output format", OFFSET(format), AV_OPT_TYPE_INT, {.i64=OVERLAY_FORMAT_YUV420}, 0, OVERLAY_FORMAT_NB-1, FLAGS, "format" },
        { "yuv420", "", 0, AV_OPT_TYPE_CONST, {.i64=OVERLAY_FORMAT_YUV420}, .flags = FLAGS, .unit = "format" },
        { "yuv422", "", 0, AV_OPT_TYPE_CONST, {.i64=OVERLAY_FORMAT_YUV422}, .flags = FLAGS, .unit = "format" },
        { "yuv444", "", 0, AV_OPT_TYPE_CONST, {.i64=OVERLAY_FORMAT_YUV444}, .flags = FLAGS, .unit = "format" },
        { "rgb",    "", 0, AV_OPT_TYPE_CONST, {.i64=OVERLAY_FORMAT_RGB},    .flags = FLAGS, .unit = "format" },
    { "repeatlast", "repeat overlay of the last overlay frame", OFFSET(dinput.repeatlast), AV_OPT_TYPE_BOOL, {.i64=1}, 0, 1, FLAGS },
    { NULL }
}
Definition at line 731 of file vf_overlay.c.
avfilter_vf_overlay_inputs
const AVFilterPad avfilter_vf_overlay_inputs[] static
Initial value:
= {
    {
        .name         = "main",
        .type         = AVMEDIA_TYPE_VIDEO,
        .config_props = config_input_main,
        .filter_frame = filter_frame,
        .needs_writable = 1,
    },
    {
        .name         = "overlay",
        .type         = AVMEDIA_TYPE_VIDEO,
        .config_props = config_input_overlay,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 756 of file vf_overlay.c.
avfilter_vf_overlay_outputs
const AVFilterPad avfilter_vf_overlay_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .config_props  = config_output,
        .request_frame = request_frame,
    },
    { NULL }
}
Definition at line 773 of file vf_overlay.c.
ff_vf_overlay
AVFilter ff_vf_overlay
Initial value:
= {
    .name          = "overlay",
    .description   = NULL_IF_CONFIG_SMALL("Overlay a video source on top of the input."),
    .init          = init,
    .uninit        = uninit,
    .priv_size     = sizeof(OverlayContext),
    .priv_class    = &overlay_class,
    .query_formats = query_formats,
    .process_command = process_command,
    .inputs        = avfilter_vf_overlay_inputs,
    .outputs       = avfilter_vf_overlay_outputs,
    .flags         = AVFILTER_FLAG_SUPPORT_TIMELINE_INTERNAL,
}
Definition at line 783 of file vf_overlay.c.