FFmpeg: libavfilter/vf_coreimage.m File Reference
vf_coreimage.m File Reference
Video processing based on Apple's CoreImage API.
#import <QuartzCore/CoreImage.h>
#import <AppKit/AppKit.h>
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
#include "libavutil/internal.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
Data Structures
struct CoreImageContext
Macros
#define CLAMP_WARNING
#define SafeCFRelease(ptr)
#define OFFSET(x) offsetof(CoreImageContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
#define GENERATOR_OPTIONS
#define FILTER_OPTIONS
Functions
static int config_output (AVFilterLink *link)
static int config_input (AVFilterLink *link)
Determine image properties from input link of filter chain.
static void list_filters (CoreImageContext *ctx)
Print a list of all available filters including options and respective value ranges and defaults.
static int query_formats (AVFilterContext *fctx)
static int query_formats_src (AVFilterContext *fctx)
static int apply_filter (CoreImageContext *ctx, AVFilterLink *link, AVFrame *frame)
static int filter_frame (AVFilterLink *link, AVFrame *frame)
Apply all valid filters successively to the input image.
static int request_frame (AVFilterLink *link)
static void set_option (CoreImageContext *ctx, CIFilter *filter, const char *key, const char *value)
Set an option of the given filter to the provided key-value pair.
static CIFilter * create_filter (CoreImageContext *ctx, const char *filter_name, AVDictionary *filter_options)
Create a filter object by a given name and set all options to defaults.
static av_cold int init (AVFilterContext *fctx)
static av_cold int init_src (AVFilterContext *fctx)
static av_cold void uninit (AVFilterContext *fctx)
AVFILTER_DEFINE_CLASS (coreimage)
AVFILTER_DEFINE_CLASS (coreimagesrc)
Variables
static const AVFilterPad vf_coreimage_inputs []
static const AVFilterPad vf_coreimage_outputs []
static const AVFilterPad vsrc_coreimagesrc_outputs []
static const AVOption coreimage_options []
AVFilter ff_vf_coreimage
static const AVOption coreimagesrc_options []
AVFilter ff_vsrc_coreimagesrc
Detailed Description
Video processing based on Apple's CoreImage API.
Definition in file vf_coreimage.m.
Macro Definition Documentation
CLAMP_WARNING
#define CLAMP_WARNING
Value:
do {     \
av_log(ctx, AV_LOG_WARNING, "Value of \"%f\" for option \"%s\" is out of range [%f %f], clamping to \"%f\".\n", \
       input,                  \
       [input_key UTF8String], \
       min_value.floatValue,   \
       max_value.floatValue,   \
       used_value.floatValue); \
} while(0)
Referenced by set_option().
SafeCFRelease
#define SafeCFRelease (ptr)
Value:
do { \
    if (ptr) {                  \
        CFRelease(ptr);         \
        ptr = NULL;             \
    }                           \
} while (0)
Referenced by uninit().
OFFSET
#define OFFSET (x) offsetof(CoreImageContext, x)
Definition at line 630 of file vf_coreimage.m.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 631 of file vf_coreimage.m.
GENERATOR_OPTIONS
#define GENERATOR_OPTIONS
Value:
{"size",     "set video size",                OFFSET(w),          AV_OPT_TYPE_IMAGE_SIZE, {.str = "320x240"}, 0, 0,         FLAGS}, \
    {"s",        "set video size",                OFFSET(w),          AV_OPT_TYPE_IMAGE_SIZE, {.str = "320x240"}, 0, 0,         FLAGS}, \
    {"rate",     "set video rate",                OFFSET(frame_rate), AV_OPT_TYPE_VIDEO_RATE, {.str = "25"},      0, INT_MAX,         FLAGS}, \
    {"r",        "set video rate",                OFFSET(frame_rate), AV_OPT_TYPE_VIDEO_RATE, {.str = "25"},      0, INT_MAX,         FLAGS}, \
    {"duration", "set video duration",            OFFSET(duration),   AV_OPT_TYPE_DURATION,   {.i64 = -1},       -1, INT64_MAX, FLAGS}, \
    {"d",        "set video duration",            OFFSET(duration),   AV_OPT_TYPE_DURATION,   {.i64 = -1},       -1, INT64_MAX, FLAGS}, \
    {"sar",      "set video sample aspect ratio", OFFSET(sar),        AV_OPT_TYPE_RATIONAL,   {.dbl = 1},         0, INT_MAX,   FLAGS},
Definition at line 633 of file vf_coreimage.m.
FILTER_OPTIONS
#define FILTER_OPTIONS
Value:
{"list_filters",    "list available filters",                OFFSET(list_filters),    AV_OPT_TYPE_BOOL,   {.i64 = 0}, 0, 1, .flags = FLAGS}, \
    {"list_generators", "list available generators",             OFFSET(list_generators), AV_OPT_TYPE_BOOL,   {.i64 = 0}, 0, 1, .flags = FLAGS}, \
    {"filter",          "names and options of filters to apply", OFFSET(filter_string),   AV_OPT_TYPE_STRING, {.str = NULL},    .flags = FLAGS}, \
    {"output_rect",     "output rectangle within output image",  OFFSET(output_rect),     AV_OPT_TYPE_STRING, {.str = NULL},    .flags = FLAGS},
Definition at line 642 of file vf_coreimage.m.
Function Documentation
config_output()
static int config_output (AVFilterLink * link) static
Definition at line 65 of file vf_coreimage.m.
config_input()
static int config_input (AVFilterLink * link) static
Determine image properties from input link of filter chain.
Definition at line 83 of file vf_coreimage.m.
list_filters()
static void list_filters (CoreImageContext * ctx) static
Print a list of all available filters including options and respective value ranges and defaults.
Definition at line 94 of file vf_coreimage.m.
query_formats()
static int query_formats (AVFilterContext * fctx) static
Definition at line 138 of file vf_coreimage.m.
query_formats_src()
static int query_formats_src (AVFilterContext * fctx) static
Definition at line 160 of file vf_coreimage.m.
apply_filter()
static int apply_filter (CoreImageContext * ctx, AVFilterLink * link, AVFrame * frame) static
Definition at line 181 of file vf_coreimage.m.
Referenced by filter_frame(), and request_frame().
filter_frame()
static int filter_frame (AVFilterLink * link, AVFrame * frame) static
Apply all valid filters successively to the input image.
The final output image is copied from the GPU by "drawing" using a bitmap context.
Definition at line 318 of file vf_coreimage.m.
request_frame()
static int request_frame (AVFilterLink * link) static
Definition at line 323 of file vf_coreimage.m.
set_option()
static void set_option (CoreImageContext * ctx, CIFilter * filter, const char * key, const char * value) static
Set an option of the given filter to the provided key-value pair.
Definition at line 358 of file vf_coreimage.m.
Referenced by create_filter().
create_filter()
static CIFilter* create_filter (CoreImageContext * ctx, const char * filter_name, AVDictionary * filter_options) static
Create a filter object by a given name and set all options to defaults.
Overwrite any option given by the user to the provided value in filter_options.
Definition at line 451 of file vf_coreimage.m.
Referenced by init().
init()
static av_cold int init (AVFilterContext * fctx) static
Definition at line 470 of file vf_coreimage.m.
Referenced by init_src().
init_src()
static av_cold int init_src (AVFilterContext * fctx) static
Definition at line 565 of file vf_coreimage.m.
uninit()
static av_cold void uninit (AVFilterContext * fctx) static
Definition at line 576 of file vf_coreimage.m.
AVFILTER_DEFINE_CLASS() [1/2]
AVFILTER_DEFINE_CLASS (coreimage)
AVFILTER_DEFINE_CLASS() [2/2]
AVFILTER_DEFINE_CLASS (coreimagesrc)
Variable Documentation
vf_coreimage_inputs
const AVFilterPad vf_coreimage_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
        .config_props = config_input,
    },
    { NULL }
}
Definition at line 602 of file vf_coreimage.m.
vf_coreimage_outputs
const AVFilterPad vf_coreimage_outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_VIDEO,
    },
    { NULL }
}
Definition at line 612 of file vf_coreimage.m.
vsrc_coreimagesrc_outputs
const AVFilterPad vsrc_coreimagesrc_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .request_frame = request_frame,
        .config_props  = config_output,
    },
    { NULL }
}
Definition at line 620 of file vf_coreimage.m.
coreimage_options
const AVOption coreimage_options[] static
Initial value:
= {
    FILTER_OPTIONS
    { NULL }
}
Definition at line 650 of file vf_coreimage.m.
ff_vf_coreimage
AVFilter ff_vf_coreimage
Initial value:
= {
    .name          = "coreimage",
    .description   = NULL_IF_CONFIG_SMALL("Video filtering using CoreImage API."),
    .init          = init,
    .uninit        = uninit,
    .priv_size     = sizeof(CoreImageContext),
    .priv_class    = &coreimage_class,
    .inputs        = vf_coreimage_inputs,
    .outputs       = vf_coreimage_outputs,
    .query_formats = query_formats,
}
Definition at line 657 of file vf_coreimage.m.
coreimagesrc_options
const AVOption coreimagesrc_options[] static
Initial value:
= {
    GENERATOR_OPTIONS
    FILTER_OPTIONS
    { NULL }
}
Definition at line 670 of file vf_coreimage.m.
ff_vsrc_coreimagesrc
AVFilter ff_vsrc_coreimagesrc
Initial value:
= {
    .name          = "coreimagesrc",
    .description   = NULL_IF_CONFIG_SMALL("Video source using image generators of CoreImage API."),
    .init          = init_src,
    .uninit        = uninit,
    .priv_size     = sizeof(CoreImageContext),
    .priv_class    = &coreimagesrc_class,
    .inputs        = NULL,
    .outputs       = vsrc_coreimagesrc_outputs,
    .query_formats = query_formats_src,
}
Definition at line 678 of file vf_coreimage.m.