FFmpeg: libavfilter/vf_libopencv.c File Reference
vf_libopencv.c File Reference
libopencv wrapper functions
#include "config.h"
#include <opencv/cv.h>
#include <opencv/cxcore.h>
#include "libavutil/avstring.h"
#include "libavutil/common.h"
#include "libavutil/file.h"
#include "libavutil/opt.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
Data Structures
struct OCVContext
struct SmoothContext
struct DilateContext
struct OCVFilterEntry
Macros
#define OFFSET(x) offsetof(OCVContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_FILTERING_PARAM
Functions
static void fill_iplimage_from_frame (IplImage *img, const AVFrame *frame, enum AVPixelFormat pixfmt)
static void fill_frame_from_iplimage (AVFrame *frame, const IplImage *img, enum AVPixelFormat pixfmt)
static int query_formats (AVFilterContext *ctx)
static av_cold int smooth_init (AVFilterContext *ctx, const char *args)
static void smooth_end_frame_filter (AVFilterContext *ctx, IplImage *inimg, IplImage *outimg)
static int read_shape_from_file (int *cols, int *rows, int **values, const char *filename, void *log_ctx)
static int parse_iplconvkernel (IplConvKernel **kernel, char *buf, void *log_ctx)
static av_cold int dilate_init (AVFilterContext *ctx, const char *args)
static av_cold void dilate_uninit (AVFilterContext *ctx)
static void dilate_end_frame_filter (AVFilterContext *ctx, IplImage *inimg, IplImage *outimg)
static void erode_end_frame_filter (AVFilterContext *ctx, IplImage *inimg, IplImage *outimg)
static av_cold int init (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
static int filter_frame (AVFilterLink *inlink, AVFrame *in)
AVFILTER_DEFINE_CLASS (ocv)
Variables
static const OCVFilterEntry ocv_filter_entries []
static const AVOption ocv_options []
static const AVFilterPad avfilter_vf_ocv_inputs []
static const AVFilterPad avfilter_vf_ocv_outputs []
AVFilter ff_vf_ocv
Detailed Description
libopencv wrapper functions
Definition in file vf_libopencv.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(OCVContext, x)
Definition at line 397 of file vf_libopencv.c.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_FILTERING_PARAM
Definition at line 398 of file vf_libopencv.c.
Function Documentation
fill_iplimage_from_frame()
static void fill_iplimage_from_frame (IplImage * img, const AVFrame * frame, enum AVPixelFormat pixfmt) static
Definition at line 43 of file vf_libopencv.c.
Referenced by filter_frame().
fill_frame_from_iplimage()
static void fill_frame_from_iplimage (AVFrame * frame, const IplImage * img, enum AVPixelFormat pixfmt) static
Definition at line 61 of file vf_libopencv.c.
Referenced by filter_frame().
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 67 of file vf_libopencv.c.
smooth_init()
static av_cold int smooth_init (AVFilterContext * ctx, const char * args) static
Definition at line 94 of file vf_libopencv.c.
smooth_end_frame_filter()
static void smooth_end_frame_filter (AVFilterContext * ctx, IplImage * inimg, IplImage * outimg) static
Definition at line 137 of file vf_libopencv.c.
read_shape_from_file()
static int read_shape_from_file (int * cols, int * rows, int ** values, const char * filename, void * log_ctx) static
Definition at line 144 of file vf_libopencv.c.
Referenced by parse_iplconvkernel().
parse_iplconvkernel()
static int parse_iplconvkernel (IplConvKernel ** kernel, char * buf, void * log_ctx) static
Definition at line 211 of file vf_libopencv.c.
Referenced by dilate_init().
dilate_init()
static av_cold int dilate_init (AVFilterContext * ctx, const char * args) static
Definition at line 266 of file vf_libopencv.c.
dilate_uninit()
static av_cold void dilate_uninit (AVFilterContext * ctx) static
Definition at line 301 of file vf_libopencv.c.
dilate_end_frame_filter()
static void dilate_end_frame_filter (AVFilterContext * ctx, IplImage * inimg, IplImage * outimg) static
Definition at line 309 of file vf_libopencv.c.
erode_end_frame_filter()
static void erode_end_frame_filter (AVFilterContext * ctx, IplImage * inimg, IplImage * outimg) static
Definition at line 316 of file vf_libopencv.c.
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 337 of file vf_libopencv.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 363 of file vf_libopencv.c.
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 372 of file vf_libopencv.c.
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (ocv)
Variable Documentation
ocv_filter_entries
const OCVFilterEntry ocv_filter_entries[] static
Initial value:
= {
    { "dilate", sizeof(DilateContext), dilate_init, dilate_uninit, dilate_end_frame_filter },
    { "erode",  sizeof(DilateContext), dilate_init, dilate_uninit, erode_end_frame_filter  },
    { "smooth", sizeof(SmoothContext), smooth_init, NULL, smooth_end_frame_filter },
}
Definition at line 331 of file vf_libopencv.c.
ocv_options
const AVOption ocv_options[] static
Initial value:
= {
    { "filter_name",   NULL, OFFSET(name),   AV_OPT_TYPE_STRING, .flags = FLAGS },
    { "filter_params", NULL, OFFSET(params), AV_OPT_TYPE_STRING, .flags = FLAGS },
    { NULL }
}
Definition at line 399 of file vf_libopencv.c.
avfilter_vf_ocv_inputs
const AVFilterPad avfilter_vf_ocv_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 407 of file vf_libopencv.c.
avfilter_vf_ocv_outputs
const AVFilterPad avfilter_vf_ocv_outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_VIDEO,
    },
    { NULL }
}
Definition at line 416 of file vf_libopencv.c.
ff_vf_ocv
AVFilter ff_vf_ocv
Initial value:
= {
    .name          = "ocv",
    .description   = NULL_IF_CONFIG_SMALL("Apply transform using libopencv."),
    .priv_size     = sizeof(OCVContext),
    .priv_class    = &ocv_class,
    .query_formats = query_formats,
    .init          = init,
    .uninit        = uninit,
    .inputs        = avfilter_vf_ocv_inputs,
    .outputs       = avfilter_vf_ocv_outputs,
}
Definition at line 424 of file vf_libopencv.c.