FFmpeg: libavfilter/x86/vf_removegrain_init.c File Reference
vf_removegrain_init.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/x86/cpu.h"
#include "libavfilter/removegrain.h"
Functions
void ff_rg_fl_mode_1_sse2 (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int pixels)
void ff_rg_fl_mode_10_sse2 (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int pixels)
void ff_rg_fl_mode_11_12_sse2 (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int pixels)
void ff_rg_fl_mode_13_14_sse2 (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int pixels)
void ff_rg_fl_mode_19_sse2 (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int pixels)
void ff_rg_fl_mode_20_sse2 (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int pixels)
void ff_rg_fl_mode_21_sse2 (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int pixels)
void ff_rg_fl_mode_22_sse2 (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int pixels)
av_cold void ff_removegrain_init_x86 (RemoveGrainContext *rg)
Function Documentation
ff_rg_fl_mode_1_sse2()
void ff_rg_fl_mode_1_sse2 (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int pixels)
Referenced by ff_removegrain_init_x86().
ff_rg_fl_mode_10_sse2()
void ff_rg_fl_mode_10_sse2 (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int pixels)
Referenced by ff_removegrain_init_x86().
ff_rg_fl_mode_11_12_sse2()
void ff_rg_fl_mode_11_12_sse2 (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int pixels)
Referenced by ff_removegrain_init_x86().
ff_rg_fl_mode_13_14_sse2()
void ff_rg_fl_mode_13_14_sse2 (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int pixels)
Referenced by ff_removegrain_init_x86().
ff_rg_fl_mode_19_sse2()
void ff_rg_fl_mode_19_sse2 (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int pixels)
Referenced by ff_removegrain_init_x86().
ff_rg_fl_mode_20_sse2()
void ff_rg_fl_mode_20_sse2 (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int pixels)
Referenced by ff_removegrain_init_x86().
ff_rg_fl_mode_21_sse2()
void ff_rg_fl_mode_21_sse2 (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int pixels)
Referenced by ff_removegrain_init_x86().
ff_rg_fl_mode_22_sse2()
void ff_rg_fl_mode_22_sse2 (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int pixels)
Referenced by ff_removegrain_init_x86().
ff_removegrain_init_x86()
av_cold void ff_removegrain_init_x86 (RemoveGrainContext * rg)
Definition at line 50 of file vf_removegrain_init.c.
Referenced by config_input().