FFmpeg: libavfilter/vf_selectivecolor.c File Reference
vf_selectivecolor.c File Reference
#include "libavutil/avassert.h"
#include "libavutil/file.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "libavcodec/mathops.h"
#include "avfilter.h"
#include "drawutils.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
Data Structures
struct process_range
struct ThreadData
struct SelectiveColorContext
Macros
#define R 0
#define G 1
#define B 2
#define A 3
#define OFFSET(x) offsetof(SelectiveColorContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
#define RANGE_OPTION(color_name, range) { color_name"s", "adjust "color_name" regions", OFFSET(opt_cmyk_adjust[range]), AV_OPT_TYPE_STRING, {.str=NULL}, CHAR_MIN, CHAR_MAX, FLAGS }
#define DECLARE_RANGE_SCALE_FUNCS(nbits)
#define READ16(dst)
#define DECLARE_SELECTIVE_COLOR_FUNC(nbits)
#define DEF_SELECTIVE_COLOR_FUNC(name, direct, correction_method, nbits)
#define DEF_SELECTIVE_COLOR_FUNCS(nbits)
Typedefs
typedef int(* get_range_scale_func) (int r, int g, int b, int min_val, int max_val)
typedef int(* selective_color_func_type) (AVFilterContext *ctx, void *td, int jobnr, int nb_jobs)
Enumerations
enum color_range {
RANGE_REDS, RANGE_YELLOWS, RANGE_GREENS, RANGE_CYANS,
RANGE_BLUES, RANGE_MAGENTAS, RANGE_WHITES, RANGE_NEUTRALS,
RANGE_BLACKS, NB_RANGES
}
enum correction_method { CORRECTION_METHOD_ABSOLUTE, CORRECTION_METHOD_RELATIVE, NB_CORRECTION_METHODS }
Functions
AVFILTER_DEFINE_CLASS (selectivecolor)
static int get_rgb_scale (int r, int g, int b, int min_val, int max_val)
static int get_cmy_scale (int r, int g, int b, int min_val, int max_val)
static int register_range (SelectiveColorContext *s, int range_id)
static int parse_psfile (AVFilterContext *ctx, const char *fname)
static int config_input (AVFilterLink *inlink)
static int query_formats (AVFilterContext *ctx)
static int comp_adjust (int scale, float value, float adjust, float k, int correction_method)
static int filter_frame (AVFilterLink *inlink, AVFrame *in)
Variables
static const char * color_names [NB_RANGES]
static const AVOption selectivecolor_options []
static const AVFilterPad selectivecolor_inputs []
static const AVFilterPad selectivecolor_outputs []
AVFilter ff_vf_selectivecolor
Macro Definition Documentation
R
#define R 0
Todo:
use integers so it can be made bitexact and a FATE test can be added
Definition at line 38 of file vf_selectivecolor.c.
G
#define G 1
Definition at line 39 of file vf_selectivecolor.c.
B
#define B 2
Definition at line 40 of file vf_selectivecolor.c.
A
#define A 3
Definition at line 41 of file vf_selectivecolor.c.
OFFSET
#define OFFSET (x) offsetof(SelectiveColorContext, x)
Definition at line 92 of file vf_selectivecolor.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 93 of file vf_selectivecolor.c.
RANGE_OPTION
#define RANGE_OPTION (color_name, range) { color_name"s", "adjust "color_name" regions", OFFSET(opt_cmyk_adjust[range]), AV_OPT_TYPE_STRING, {.str=NULL}, CHAR_MIN, CHAR_MAX, FLAGS }
Definition at line 94 of file vf_selectivecolor.c.
DECLARE_RANGE_SCALE_FUNCS
#define DECLARE_RANGE_SCALE_FUNCS (nbits)
Value:
static int get_neutrals_scale##nbits(int r, int g, int b, int min_val, int max_val)         \
{                                                                                           \
    /* 1 - (|max-0.5| + |min-0.5|) */                                                       \
    return (((1<<nbits)-1)*2 - (  abs((max_val<<1) - ((1<<nbits)-1))                        \
                                + abs((min_val<<1) - ((1<<nbits)-1))) + 1) >> 1;            \
}                                                                                           \
                                                                                            \
static int get_whites_scale##nbits(int r, int g, int b, int min_val, int max_val)           \
{                                                                                           \
    /* (min - 0.5) * 2 */                                                                   \
    return (min_val<<1) - ((1<<nbits)-1);                                                   \
}                                                                                           \
                                                                                            \
static int get_blacks_scale##nbits(int r, int g, int b, int min_val, int max_val)           \
{                                                                                           \
    /* (0.5 - max) * 2 */                                                                   \
    return ((1<<nbits)-1) - (max_val<<1);                                                   \
}                                                                                           \
Definition at line 126 of file vf_selectivecolor.c.
READ16
#define READ16 (dst)
Value:
do {                \
    if (size < 2) {                     \
        ret = AVERROR_INVALIDDATA;      \
        goto end;                       \
    }                                   \
    dst = AV_RB16(buf);                 \
    buf  += 2;                          \
    size -= 2;                          \
} while (0)
Referenced by parse_psfile().
DECLARE_SELECTIVE_COLOR_FUNC
#define DECLARE_SELECTIVE_COLOR_FUNC (nbits)
Definition at line 315 of file vf_selectivecolor.c.
DEF_SELECTIVE_COLOR_FUNC
#define DEF_SELECTIVE_COLOR_FUNC (name, direct, correction_method, nbits)
Value:
static int selective_color_##name##_##nbits(AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)    \
{                                                                                                       \
    return selective_color_##nbits(ctx, arg, jobnr, nb_jobs, direct, correction_method);                \
}
Definition at line 395 of file vf_selectivecolor.c.
DEF_SELECTIVE_COLOR_FUNCS
#define DEF_SELECTIVE_COLOR_FUNCS (nbits)
Value:
DECLARE_SELECTIVE_COLOR_FUNC(nbits)                                                                     \
DEF_SELECTIVE_COLOR_FUNC(indirect_absolute, 0, CORRECTION_METHOD_ABSOLUTE, nbits)                       \
DEF_SELECTIVE_COLOR_FUNC(indirect_relative, 0, CORRECTION_METHOD_RELATIVE, nbits)                       \
DEF_SELECTIVE_COLOR_FUNC(direct_absolute, 1, CORRECTION_METHOD_ABSOLUTE, nbits)                       \
DEF_SELECTIVE_COLOR_FUNC(direct_relative, 1, CORRECTION_METHOD_RELATIVE, nbits)
Definition at line 401 of file vf_selectivecolor.c.
Typedef Documentation
get_range_scale_func
typedef int(* get_range_scale_func) (int r, int g, int b, int min_val, int max_val)
Definition at line 67 of file vf_selectivecolor.c.
selective_color_func_type
typedef int(* selective_color_func_type) (AVFilterContext *ctx, void *td, int jobnr, int nb_jobs)
Definition at line 411 of file vf_selectivecolor.c.
Enumeration Type Documentation
color_range
enum color_range
Enumerator
RANGE_REDS
RANGE_YELLOWS
RANGE_GREENS
RANGE_CYANS
RANGE_BLUES
RANGE_MAGENTAS
RANGE_WHITES
RANGE_NEUTRALS
RANGE_BLACKS
NB_RANGES
Definition at line 43 of file vf_selectivecolor.c.
correction_method
enum correction_method
Enumerator
CORRECTION_METHOD_ABSOLUTE
CORRECTION_METHOD_RELATIVE
NB_CORRECTION_METHODS
Definition at line 57 of file vf_selectivecolor.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (selectivecolor)
get_rgb_scale()
static int get_rgb_scale (int r, int g, int b, int min_val, int max_val) static
Definition at line 116 of file vf_selectivecolor.c.
Referenced by register_range().
get_cmy_scale()
static int get_cmy_scale (int r, int g, int b, int min_val, int max_val) static
Definition at line 121 of file vf_selectivecolor.c.
Referenced by register_range().
register_range()
static int register_range (SelectiveColorContext * s, int range_id) static
Definition at line 149 of file vf_selectivecolor.c.
Referenced by config_input(), and parse_psfile().
parse_psfile()
static int parse_psfile (AVFilterContext * ctx, const char * fname) static
Definition at line 184 of file vf_selectivecolor.c.
Referenced by config_input().
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 237 of file vf_selectivecolor.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 287 of file vf_selectivecolor.c.
comp_adjust()
static int comp_adjust (int scale, float value, float adjust, float k, int correction_method) inline static
Definition at line 305 of file vf_selectivecolor.c.
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 413 of file vf_selectivecolor.c.
Variable Documentation
color_names
const char* color_names[NB_RANGES] static
Initial value:
= {
    "red", "yellow", "green", "cyan", "blue", "magenta", "white", "neutral", "black"
}
Definition at line 63 of file vf_selectivecolor.c.
Referenced by config_input(), register_range(), and test_av_parse_color().
selectivecolor_options
const AVOption selectivecolor_options[] static
Initial value:
= {
    { "correction_method", "select correction method", OFFSET(correction_method), AV_OPT_TYPE_INT, {.i64 = CORRECTION_METHOD_ABSOLUTE}, 0, NB_CORRECTION_METHODS-1, FLAGS, "correction_method" },
        { "absolute", NULL, 0, AV_OPT_TYPE_CONST, {.i64=CORRECTION_METHOD_ABSOLUTE}, INT_MIN, INT_MAX, FLAGS, "correction_method" },
        { "relative", NULL, 0, AV_OPT_TYPE_CONST, {.i64=CORRECTION_METHOD_RELATIVE}, INT_MIN, INT_MAX, FLAGS, "correction_method" },
    RANGE_OPTION("red",     RANGE_REDS),
    RANGE_OPTION("yellow",  RANGE_YELLOWS),
    RANGE_OPTION("green",   RANGE_GREENS),
    RANGE_OPTION("cyan",    RANGE_CYANS),
    RANGE_OPTION("blue",    RANGE_BLUES),
    RANGE_OPTION("magenta", RANGE_MAGENTAS),
    RANGE_OPTION("white",   RANGE_WHITES),
    RANGE_OPTION("neutral", RANGE_NEUTRALS),
    RANGE_OPTION("black",   RANGE_BLACKS),
    { "psfile", "set Photoshop selectivecolor file name", OFFSET(psfile), AV_OPT_TYPE_STRING, {.str=NULL}, .flags = FLAGS },
    { NULL }
}
Definition at line 97 of file vf_selectivecolor.c.
selectivecolor_inputs
const AVFilterPad selectivecolor_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
        .config_props = config_input,
    },
    { NULL }
}
Definition at line 454 of file vf_selectivecolor.c.
selectivecolor_outputs
const AVFilterPad selectivecolor_outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_VIDEO,
    },
    { NULL }
}
Definition at line 464 of file vf_selectivecolor.c.
ff_vf_selectivecolor
AVFilter ff_vf_selectivecolor
Initial value:
= {
    .name          = "selectivecolor",
    .description   = NULL_IF_CONFIG_SMALL("Apply CMYK adjustments to specific color ranges."),
    .priv_size     = sizeof(SelectiveColorContext),
    .query_formats = query_formats,
    .inputs        = selectivecolor_inputs,
    .outputs       = selectivecolor_outputs,
    .priv_class    = &selectivecolor_class,
    .flags         = AVFILTER_FLAG_SUPPORT_TIMELINE_GENERIC | AVFILTER_FLAG_SLICE_THREADS,
}
Definition at line 472 of file vf_selectivecolor.c.