FFmpeg: libavfilter/vf_vectorscope.c File Reference
vf_vectorscope.c File Reference
#include "libavutil/avassert.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/opt.h"
#include "libavutil/parseutils.h"
#include "libavutil/pixdesc.h"
#include "libavutil/xga_font_data.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
Data Structures
struct VectorscopeContext
Macros
#define OFFSET(x) offsetof(VectorscopeContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Enumerations
enum VectorscopeMode {
GRAY, COLOR, COLOR2, COLOR3,
COLOR4, COLOR5, MODE_NB
}
Functions
AVFILTER_DEFINE_CLASS (vectorscope)
static int query_formats (AVFilterContext *ctx)
static int config_output (AVFilterLink *outlink)
static void envelope_instant16 (VectorscopeContext *s, AVFrame *out)
static void envelope_peak16 (VectorscopeContext *s, AVFrame *out)
static void envelope_instant (VectorscopeContext *s, AVFrame *out)
static void envelope_peak (VectorscopeContext *s, AVFrame *out)
static void envelope16 (VectorscopeContext *s, AVFrame *out)
static void envelope (VectorscopeContext *s, AVFrame *out)
static void vectorscope16 (VectorscopeContext *s, AVFrame *in, AVFrame *out, int pd)
static void vectorscope8 (VectorscopeContext *s, AVFrame *in, AVFrame *out, int pd)
static void draw_dots (uint8_t *dst, int L, int v, float o)
static void draw_dots16 (uint16_t *dst, int L, int v, float o)
static void none_graticule (VectorscopeContext *s, AVFrame *out, int X, int Y, int D, int P)
static void draw_htext (AVFrame *out, int x, int y, float o1, float o2, const char *txt, const uint8_t color[4])
static void draw_htext16 (AVFrame *out, int x, int y, float o1, float o2, const char *txt, const uint16_t color[4])
static void color_graticule16 (VectorscopeContext *s, AVFrame *out, int X, int Y, int D, int P)
static void color_graticule (VectorscopeContext *s, AVFrame *out, int X, int Y, int D, int P)
static void green_graticule16 (VectorscopeContext *s, AVFrame *out, int X, int Y, int D, int P)
static void green_graticule (VectorscopeContext *s, AVFrame *out, int X, int Y, int D, int P)
static int filter_frame (AVFilterLink *inlink, AVFrame *in)
static int config_input (AVFilterLink *inlink)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const AVOption vectorscope_options []
static enum AVPixelFormat out_yuv8_pix_fmts []
static enum AVPixelFormat out_yuv9_pix_fmts []
static enum AVPixelFormat out_yuv10_pix_fmts []
static enum AVPixelFormat out_yuv12_pix_fmts []
static enum AVPixelFormat out_rgb8_pix_fmts []
static enum AVPixelFormat out_rgb9_pix_fmts []
static enum AVPixelFormat out_rgb10_pix_fmts []
static enum AVPixelFormat out_rgb12_pix_fmts []
static enum AVPixelFormat in1_pix_fmts []
static enum AVPixelFormat in2_pix_fmts []
static const char * positions_name []
static const uint16_t positions [][14][3]
static const AVFilterPad inputs []
static const AVFilterPad outputs []
AVFilter ff_vf_vectorscope
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(VectorscopeContext, x)
Definition at line 76 of file vf_vectorscope.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 77 of file vf_vectorscope.c.
Enumeration Type Documentation
VectorscopeMode
enum VectorscopeMode
Enumerator
GRAY
COLOR
COLOR2
COLOR3
COLOR4
COLOR5
MODE_NB
Definition at line 32 of file vf_vectorscope.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (vectorscope)
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 194 of file vf_vectorscope.c.
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 253 of file vf_vectorscope.c.
envelope_instant16()
static void envelope_instant16 (VectorscopeContext * s, AVFrame * out) static
Definition at line 276 of file vf_vectorscope.c.
Referenced by envelope16(), and envelope_peak16().
envelope_peak16()
static void envelope_peak16 (VectorscopeContext * s, AVFrame * out) static
Definition at line 297 of file vf_vectorscope.c.
Referenced by envelope16().
envelope_instant()
static void envelope_instant (VectorscopeContext * s, AVFrame * out) static
Definition at line 328 of file vf_vectorscope.c.
Referenced by envelope(), and envelope_peak().
envelope_peak()
static void envelope_peak (VectorscopeContext * s, AVFrame * out) static
Definition at line 348 of file vf_vectorscope.c.
Referenced by envelope().
envelope16()
static void envelope16 (VectorscopeContext * s, AVFrame * out) static
Definition at line 378 of file vf_vectorscope.c.
Referenced by vectorscope16().
envelope()
static void envelope (VectorscopeContext * s, AVFrame * out) static
Definition at line 389 of file vf_vectorscope.c.
vectorscope16()
static void vectorscope16 (VectorscopeContext * s, AVFrame * in, AVFrame * out, int pd) static
Definition at line 400 of file vf_vectorscope.c.
Referenced by config_input().
vectorscope8()
static void vectorscope8 (VectorscopeContext * s, AVFrame * in, AVFrame * out, int pd) static
Definition at line 598 of file vf_vectorscope.c.
Referenced by config_input().
draw_dots()
static void draw_dots (uint8_t * dst, int L, int v, float o) static
Definition at line 850 of file vf_vectorscope.c.
Referenced by color_graticule(), and green_graticule().
draw_dots16()
static void draw_dots16 (uint16_t * dst, int L, int v, float o) static
Definition at line 873 of file vf_vectorscope.c.
Referenced by color_graticule16(), and green_graticule16().
none_graticule()
static void none_graticule (VectorscopeContext * s, AVFrame * out, int X, int Y, int D, int P) static
Definition at line 896 of file vf_vectorscope.c.
Referenced by config_input().
draw_htext()
static void draw_htext (AVFrame * out, int x, int y, float o1, float o2, const char * txt, const uint8_t color[4]) static
Definition at line 900 of file vf_vectorscope.c.
Referenced by color_graticule(), and green_graticule().
draw_htext16()
static void draw_htext16 (AVFrame * out, int x, int y, float o1, float o2, const char * txt, const uint16_t color[4]) static
Definition at line 926 of file vf_vectorscope.c.
Referenced by color_graticule16(), and green_graticule16().
color_graticule16()
static void color_graticule16 (VectorscopeContext * s, AVFrame * out, int X, int Y, int D, int P) static
Definition at line 952 of file vf_vectorscope.c.
Referenced by config_input().
color_graticule()
static void color_graticule (VectorscopeContext * s, AVFrame * out, int X, int Y, int D, int P) static
Definition at line 1020 of file vf_vectorscope.c.
Referenced by config_input().
green_graticule16()
static void green_graticule16 (VectorscopeContext * s, AVFrame * out, int X, int Y, int D, int P) static
Definition at line 1086 of file vf_vectorscope.c.
Referenced by config_input().
green_graticule()
static void green_graticule (VectorscopeContext * s, AVFrame * out, int X, int Y, int D, int P) static
Definition at line 1146 of file vf_vectorscope.c.
Referenced by config_input().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 1204 of file vf_vectorscope.c.
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 1247 of file vf_vectorscope.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 1323 of file vf_vectorscope.c.
Variable Documentation
vectorscope_options
const AVOption vectorscope_options[] static
Definition at line 79 of file vf_vectorscope.c.
out_yuv8_pix_fmts
enum AVPixelFormat out_yuv8_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_YUVA444P, AV_PIX_FMT_YUV444P,
    AV_PIX_FMT_NONE
}
Definition at line 126 of file vf_vectorscope.c.
Referenced by query_formats().
out_yuv9_pix_fmts
enum AVPixelFormat out_yuv9_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_YUVA444P9, AV_PIX_FMT_YUV444P9,
    AV_PIX_FMT_NONE
}
Definition at line 131 of file vf_vectorscope.c.
Referenced by query_formats().
out_yuv10_pix_fmts
enum AVPixelFormat out_yuv10_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_YUVA444P10, AV_PIX_FMT_YUV444P10,
    AV_PIX_FMT_NONE
}
Definition at line 136 of file vf_vectorscope.c.
Referenced by query_formats().
out_yuv12_pix_fmts
enum AVPixelFormat out_yuv12_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_YUV444P12,
    AV_PIX_FMT_NONE
}
Definition at line 141 of file vf_vectorscope.c.
Referenced by query_formats().
out_rgb8_pix_fmts
enum AVPixelFormat out_rgb8_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_GBRAP, AV_PIX_FMT_GBRP,
    AV_PIX_FMT_NONE
}
Definition at line 146 of file vf_vectorscope.c.
Referenced by query_formats().
out_rgb9_pix_fmts
enum AVPixelFormat out_rgb9_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_GBRP9,
    AV_PIX_FMT_NONE
}
Definition at line 151 of file vf_vectorscope.c.
Referenced by query_formats().
out_rgb10_pix_fmts
enum AVPixelFormat out_rgb10_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_GBRP10,
    AV_PIX_FMT_NONE
}
Definition at line 156 of file vf_vectorscope.c.
Referenced by query_formats().
out_rgb12_pix_fmts
enum AVPixelFormat out_rgb12_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_GBRP12, AV_PIX_FMT_GBRAP12,
    AV_PIX_FMT_NONE
}
Definition at line 161 of file vf_vectorscope.c.
Referenced by query_formats().
in1_pix_fmts
enum AVPixelFormat in1_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_YUVA444P, AV_PIX_FMT_YUV444P, AV_PIX_FMT_YUVJ444P,
    AV_PIX_FMT_YUV444P9, AV_PIX_FMT_YUV444P10,
    AV_PIX_FMT_YUVA444P9, AV_PIX_FMT_YUVA444P10,
    AV_PIX_FMT_YUV444P12,
    AV_PIX_FMT_GBRAP, AV_PIX_FMT_GBRP,
    AV_PIX_FMT_GBRP9, AV_PIX_FMT_GBRP10,
    AV_PIX_FMT_GBRP12, AV_PIX_FMT_GBRAP12,
    AV_PIX_FMT_NONE
}
Definition at line 166 of file vf_vectorscope.c.
Referenced by query_formats().
in2_pix_fmts
enum AVPixelFormat in2_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_YUVA420P, AV_PIX_FMT_YUV420P, AV_PIX_FMT_YUVJ420P,
    AV_PIX_FMT_YUVA422P, AV_PIX_FMT_YUV422P, AV_PIX_FMT_YUVJ422P,
    AV_PIX_FMT_YUVA444P, AV_PIX_FMT_YUV444P, AV_PIX_FMT_YUVJ444P,
    AV_PIX_FMT_YUV411P,  AV_PIX_FMT_YUVJ411P,
    AV_PIX_FMT_YUV440P,  AV_PIX_FMT_YUV410P,
    AV_PIX_FMT_GBRAP, AV_PIX_FMT_GBRP,
    AV_PIX_FMT_GBRP9, AV_PIX_FMT_GBRP10,
    AV_PIX_FMT_GBRP12, AV_PIX_FMT_GBRAP12,
    AV_PIX_FMT_YUV420P9, AV_PIX_FMT_YUV422P9, AV_PIX_FMT_YUV444P9,
    AV_PIX_FMT_YUV420P10, AV_PIX_FMT_YUV422P10, AV_PIX_FMT_YUV444P10,
    AV_PIX_FMT_YUVA420P9, AV_PIX_FMT_YUVA422P9, AV_PIX_FMT_YUVA444P9,
    AV_PIX_FMT_YUVA420P10, AV_PIX_FMT_YUVA422P10, AV_PIX_FMT_YUVA444P10,
    AV_PIX_FMT_YUV420P12, AV_PIX_FMT_YUV422P12, AV_PIX_FMT_YUV444P12, AV_PIX_FMT_YUV440P12,
    AV_PIX_FMT_NONE
}
Definition at line 177 of file vf_vectorscope.c.
Referenced by query_formats().
positions_name
const char* positions_name[] static
Initial value:
= {
    "R", "B", "Cy", "Yl", "G", "Mg",
}
Definition at line 792 of file vf_vectorscope.c.
Referenced by color_graticule(), color_graticule16(), green_graticule(), and green_graticule16().
positions
const uint16_t positions[][14][3] static
Definition at line 796 of file vf_vectorscope.c.
Referenced by color_graticule(), color_graticule16(), decode_10bit_pulse(), green_graticule(), and green_graticule16().
inputs
const AVFilterPad inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
        .config_props = config_input,
    },
    { NULL }
}
Definition at line 1331 of file vf_vectorscope.c.
outputs
const AVFilterPad outputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .config_props = config_output,
    },
    { NULL }
}
Definition at line 1341 of file vf_vectorscope.c.
ff_vf_vectorscope
AVFilter ff_vf_vectorscope
Initial value:
= {
    .name          = "vectorscope",
    .description   = NULL_IF_CONFIG_SMALL("Video vectorscope."),
    .priv_size     = sizeof(VectorscopeContext),
    .priv_class    = &vectorscope_class,
    .query_formats = query_formats,
    .uninit        = uninit,
    .inputs        = inputs,
    .outputs       = outputs,
}
Definition at line 1350 of file vf_vectorscope.c.