FFmpeg: libavfilter/vf_geq.c File Reference
vf_geq.c File Reference
Generic equation change filter Originally written by Michael Niedermayer for the MPlayer project, and ported by Clément Bœsch for FFmpeg.
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/eval.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "internal.h"
Data Structures
struct GEQContext
Macros
#define OFFSET(x) offsetof(GEQContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Enumerations
enum {
Y = 0, U, V, A,
G, B, R
}
enum {
VAR_X, VAR_Y, VAR_W, VAR_H,
VAR_N, VAR_SW, VAR_SH, VAR_T,
VAR_VARS_NB
}
Functions
AVFILTER_DEFINE_CLASS (geq)
static double getpix (void *priv, double x, double y, int plane)
static double lum (void *priv, double x, double y)
static double cb (void *priv, double x, double y)
static double cr (void *priv, double x, double y)
static double alpha (void *priv, double x, double y)
static av_cold int geq_init (AVFilterContext *ctx)
static int geq_query_formats (AVFilterContext *ctx)
static int geq_config_props (AVFilterLink *inlink)
static int geq_filter_frame (AVFilterLink *inlink, AVFrame *in)
static av_cold void geq_uninit (AVFilterContext *ctx)
Variables
static const AVOption geq_options []
static const char *const var_names [] = { "X", "Y", "W", "H", "N", "SW", "SH", "T", NULL }
static const AVFilterPad geq_inputs []
static const AVFilterPad geq_outputs []
AVFilter ff_vf_geq
Detailed Description
Generic equation change filter Originally written by Michael Niedermayer for the MPlayer project, and ported by Clément Bœsch for FFmpeg.
Definition in file vf_geq.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(GEQContext, x)
Definition at line 48 of file vf_geq.c.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 49 of file vf_geq.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
Y
U
V
A
G
B
R
Definition at line 46 of file vf_geq.c.
anonymous enum
anonymous enum
Enumerator
VAR_X
VAR_Y
VAR_W
VAR_H
VAR_N
VAR_SW
VAR_SH
VAR_T
VAR_VARS_NB
Definition at line 102 of file vf_geq.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (geq)
getpix()
static double getpix (void * priv, double x, double y, int plane) inline static
Definition at line 71 of file vf_geq.c.
Referenced by alpha(), cb(), cr(), and lum().
lum()
static double lum (void * priv, double x, double y) static
Definition at line 96 of file vf_geq.c.
Referenced by geq_init().
cb()
static double cb (void * priv, double x, double y) static
Definition at line 97 of file vf_geq.c.
Referenced by av_lockmgr_register(), codebook_trellis_rate(), create_vorbis_context(), decode_frame(), decode_lsp(), decode_q_branch(), dvbsub_parse_clut_segment(), encode_frame(), encode_q_branch(), encode_window_bands_info(), escape130_decode_frame(), ff_atrac3p_init_vlcs(), fill_gv_table(), fill_table(), filter_frame(), find_best_vect(), find_min_book(), geq_init(), idct_put(), m101_decode_frame(), paf_audio_decode(), parse_ifo_palette(), parse_palette_segment(), pgmyuv_save(), ps_tableinit(), quantize_and_encode_band_cost_template(), quantize_band_cost_cached(), ready_residue(), register_exit(), rgb_to_yuv(), search_for_quantizers_anmr(), search_for_quantizers_fast(), search_for_quantizers_twoloop(), set_blocks(), unpack_codebook(), vcr1_decode_frame(), vorbis_parse_setup_hdr_codebooks(), yuv_a_to_rgba(), and yuv_to_rgba().
cr()
static double cr (void * priv, double x, double y) static
Definition at line 98 of file vf_geq.c.
Referenced by decode_frame(), decode_q_branch(), draw_mandelbrot(), dvbsub_parse_clut_segment(), encode_frame(), encode_q_branch(), escape130_decode_frame(), geq_init(), idct_put(), m101_decode_frame(), parse_ifo_palette(), parse_palette_segment(), pgmyuv_save(), rgb_to_yuv(), set_blocks(), vcr1_decode_frame(), yuv_a_to_rgba(), and yuv_to_rgba().
alpha()
static double alpha (void * priv, double x, double y) static
Definition at line 99 of file vf_geq.c.
Referenced by adaptive_gain_control(), alpha_composite(), av_parse_color(), avc_h_loop_filter_chroma422_mbaff_msa(), avc_h_loop_filter_chroma422_msa(), avc_h_loop_filter_luma_mbaff_intra_msa(), avc_h_loop_filter_luma_mbaff_msa(), avc_loopfilter_cb_or_cr_inter_edge_hor_msa(), avc_loopfilter_cb_or_cr_inter_edge_ver_msa(), avc_loopfilter_cb_or_cr_intra_edge_hor_msa(), avc_loopfilter_cb_or_cr_intra_edge_ver_msa(), avc_loopfilter_luma_inter_edge_hor_msa(), avc_loopfilter_luma_inter_edge_ver_msa(), avc_loopfilter_luma_intra_edge_hor_msa(), avc_loopfilter_luma_intra_edge_ver_msa(), avg_no_rnd_vc1_chroma_mc4_c(), bidirectional_obmc(), blend_image_packed_rgb(), blend_line(), blend_line16(), blend_pixel(), blend_plane(), bmp_decode_frame(), celt_decode_coarse_energy(), config_input(), config_output(), deblock_v8_luma_intra_8_mmi(), dvbsub_parse_clut_segment(), dxt3_block_internal(), dxt5_block_internal(), encode_frame(), encode_headers(), ff_adaptive_gain_control(), ff_ass_split_override_codes(), ff_blend_mask(), ff_blend_rectangle(), ff_cavs_filter(), ff_deblock_h_chroma_8_mmi(), ff_deblock_h_chroma_intra_8_mmi(), ff_deblock_v8_luma_8_mmi(), ff_mdct_init(), ff_sws_alphablendaway(), fft_ref_init(), filter(), filter_frame(), filter_mb_edgech(), filter_mb_edgecv(), filter_mb_edgeh(), filter_mb_edgev(), filter_mb_mbaff_edgecv(), filter_mb_mbaff_edgev(), g2m_paint_cursor(), geq_init(), interpolate(), loop_filter_c2(), loop_filter_l2(), mpeg4_decode_sprite_trajectory(), parse_palette_segment(), predict(), process_frame(), ps_tableinit(), request_frame(), Rgb16ToPlanarRgb16Wrapper(), rv40_adaptive_loop_filter(), rv40_loop_filter(), sbr_dequant(), sbr_hf_gen_c(), set_frame_data(), set_highshelf_rbj(), set_lp_rbj(), sub_left_prediction_bgr32(), tdsc_paint_cursor(), and vp7_fade_frame().
geq_init()
static av_cold int geq_init (AVFilterContext * ctx) static
Definition at line 104 of file vf_geq.c.
geq_query_formats()
static int geq_query_formats (AVFilterContext * ctx) static
Definition at line 166 of file vf_geq.c.
geq_config_props()
static int geq_config_props (AVFilterLink * inlink) static
Definition at line 191 of file vf_geq.c.
geq_filter_frame()
static int geq_filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 204 of file vf_geq.c.
geq_uninit()
static av_cold void geq_uninit (AVFilterContext * ctx) static
Definition at line 249 of file vf_geq.c.
Variable Documentation
geq_options
const AVOption geq_options[] static
Initial value:
= {
    { "lum_expr",   "set luminance expression",   OFFSET(expr_str[Y]), AV_OPT_TYPE_STRING, {.str=NULL}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "lum",        "set luminance expression",   OFFSET(expr_str[Y]), AV_OPT_TYPE_STRING, {.str=NULL}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "cb_expr",    "set chroma blue expression", OFFSET(expr_str[U]), AV_OPT_TYPE_STRING, {.str=NULL}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "cb",         "set chroma blue expression", OFFSET(expr_str[U]), AV_OPT_TYPE_STRING, {.str=NULL}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "cr_expr",    "set chroma red expression",  OFFSET(expr_str[V]), AV_OPT_TYPE_STRING, {.str=NULL}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "cr",         "set chroma red expression",  OFFSET(expr_str[V]), AV_OPT_TYPE_STRING, {.str=NULL}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "alpha_expr", "set alpha expression",       OFFSET(expr_str[A]), AV_OPT_TYPE_STRING, {.str=NULL}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "a",          "set alpha expression",       OFFSET(expr_str[A]), AV_OPT_TYPE_STRING, {.str=NULL}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "red_expr",   "set red expression",         OFFSET(expr_str[R]), AV_OPT_TYPE_STRING, {.str=NULL}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "r",          "set red expression",         OFFSET(expr_str[R]), AV_OPT_TYPE_STRING, {.str=NULL}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "green_expr", "set green expression",       OFFSET(expr_str[G]), AV_OPT_TYPE_STRING, {.str=NULL}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "g",          "set green expression",       OFFSET(expr_str[G]), AV_OPT_TYPE_STRING, {.str=NULL}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "blue_expr",  "set blue expression",        OFFSET(expr_str[B]), AV_OPT_TYPE_STRING, {.str=NULL}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "b",          "set blue expression",        OFFSET(expr_str[B]), AV_OPT_TYPE_STRING, {.str=NULL}, CHAR_MIN, CHAR_MAX, FLAGS },
    {NULL},
}
Definition at line 51 of file vf_geq.c.
var_names
const char* const var_names[] = { "X", "Y", "W", "H", "N", "SW", "SH", "T", NULL } static
Definition at line 101 of file vf_geq.c.
Referenced by geq_init().
geq_inputs
const AVFilterPad geq_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .config_props = geq_config_props,
        .filter_frame = geq_filter_frame,
    },
    { NULL }
}
Definition at line 258 of file vf_geq.c.
geq_outputs
const AVFilterPad geq_outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_VIDEO,
    },
    { NULL }
}
Definition at line 268 of file vf_geq.c.
ff_vf_geq
AVFilter ff_vf_geq
Initial value:
= {
    .name          = "geq",
    .description   = NULL_IF_CONFIG_SMALL("Apply generic equation to each pixel."),
    .priv_size     = sizeof(GEQContext),
    .init          = geq_init,
    .uninit        = geq_uninit,
    .query_formats = geq_query_formats,
    .inputs        = geq_inputs,
    .outputs       = geq_outputs,
    .priv_class    = &geq_class,
    .flags         = AVFILTER_FLAG_SUPPORT_TIMELINE_GENERIC,
}
Definition at line 276 of file vf_geq.c.