FFmpeg: libavfilter/vf_signalstats.c File Reference
vf_signalstats.c File Reference
#include "libavutil/intreadwrite.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "internal.h"
Data Structures
struct SignalstatsContext
struct ThreadData
struct ThreadDataHueSatMetrics
Macros
#define OFFSET(x) offsetof(SignalstatsContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
#define FILTER(i, j)
#define FILTER3(j) (FILTER(-1, j) && FILTER(0, j) && FILTER(1, j))
#define VREP_START 4
#define DEPTH 256
#define SET_META(key, fmt, val)
Enumerations
enum FilterMode {
FILTER_8TAP_SMOOTH, FILTER_8TAP_REGULAR, FILTER_8TAP_SHARP, FILTER_BILINEAR,
FILTER_SWITCHABLE, MODE_WIRES, MODE_COLORMIX, NB_MODE,
MODE_NONE, MODE_INTERLEAVE, MODE_DEINTERLEAVE, FILTER_NONE = -1,
FILTER_TOUT, FILTER_VREP, FILTER_BRNG, FILT_NUMB
}
Functions
AVFILTER_DEFINE_CLASS (signalstats)
static av_cold int init (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static AVFrame * alloc_frame (enum AVPixelFormat pixfmt, int w, int h)
static int config_props (AVFilterLink *outlink)
static void burn_frame8 (const SignalstatsContext *s, AVFrame *f, int x, int y)
static void burn_frame16 (const SignalstatsContext *s, AVFrame *f, int x, int y)
static int filter8_brng (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int filter16_brng (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int filter_tout_outlier (uint8_t x, uint8_t y, uint8_t z)
static int filter8_tout (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int filter16_tout (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int filter8_vrep (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int filter16_vrep (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int compute_sat_hue_metrics8 (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int compute_sat_hue_metrics16 (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static unsigned compute_bit_depth (uint16_t mask)
static int filter_frame8 (AVFilterLink *link, AVFrame *in)
static int filter_frame16 (AVFilterLink *link, AVFrame *in)
static int filter_frame (AVFilterLink *link, AVFrame *in)
Variables
static const AVOption signalstats_options []
struct {
const char * name
int(* process8)(AVFilterContext *ctx, void
*arg, int jobnr, int nb_jobs)
int(* process16)(AVFilterContext *ctx, void
*arg, int jobnr, int nb_jobs)
} filters_def []
static const AVFilterPad signalstats_inputs []
static const AVFilterPad signalstats_outputs []
AVFilter ff_vf_signalstats
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(SignalstatsContext, x)
Definition at line 69 of file vf_signalstats.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 70 of file vf_signalstats.c.
FILTER
#define FILTER (i, j)
Value:
filter_tout_outlier(p[(y-j) * lw + x + i], \
                            p[    y * lw + x + i], \
                            p[(y+j) * lw + x + i])
FILTER3
#define FILTER3 (j) (FILTER(-1, j) && FILTER(0, j) && FILTER(1, j))
Referenced by filter16_tout(), and filter8_tout().
VREP_START
#define VREP_START 4
Definition at line 383 of file vf_signalstats.c.
Referenced by filter16_vrep(), and filter8_vrep().
DEPTH
#define DEPTH 256
Definition at line 465 of file vf_signalstats.c.
Referenced by filter_frame8().
SET_META
#define SET_META (key, fmt, val)
Value:
do {                                \
    snprintf(metabuf, sizeof(metabuf), fmt, val);                   \
    av_dict_set(&out->metadata, "lavfi.signalstats." key, metabuf, 0);   \
} while (0)
Referenced by filter_frame16(), and filter_frame8().
Enumeration Type Documentation
FilterMode
enum FilterMode
Enumerator
FILTER_8TAP_SMOOTH
FILTER_8TAP_REGULAR
FILTER_8TAP_SHARP
FILTER_BILINEAR
FILTER_SWITCHABLE
MODE_WIRES
MODE_COLORMIX
NB_MODE
MODE_NONE
MODE_INTERLEAVE
MODE_DEINTERLEAVE
FILTER_NONE
FILTER_TOUT
FILTER_VREP
FILTER_BRNG
FILT_NUMB
Definition at line 28 of file vf_signalstats.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (signalstats)
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 88 of file vf_signalstats.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 105 of file vf_signalstats.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 118 of file vf_signalstats.c.
alloc_frame()
static AVFrame* alloc_frame (enum AVPixelFormat pixfmt, int w, int h) static
Definition at line 142 of file vf_signalstats.c.
Referenced by config_props().
config_props()
static int config_props (AVFilterLink * outlink) static
Definition at line 160 of file vf_signalstats.c.
burn_frame8()
static void burn_frame8 (const SignalstatsContext * s, AVFrame * f, int x, int y) static
Definition at line 201 of file vf_signalstats.c.
Referenced by filter8_brng(), filter8_tout(), and filter8_vrep().
burn_frame16()
static void burn_frame16 (const SignalstatsContext * s, AVFrame * f, int x, int y) static
Definition at line 210 of file vf_signalstats.c.
Referenced by filter16_brng(), filter16_tout(), and filter16_vrep().
filter8_brng()
static int filter8_brng (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 220 of file vf_signalstats.c.
filter16_brng()
static int filter16_brng (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 254 of file vf_signalstats.c.
filter_tout_outlier()
static int filter_tout_outlier (uint8_t x, uint8_t y, uint8_t z) static
Definition at line 289 of file vf_signalstats.c.
filter8_tout()
static int filter8_tout (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 294 of file vf_signalstats.c.
filter16_tout()
static int filter16_tout (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 342 of file vf_signalstats.c.
filter8_vrep()
static int filter8_vrep (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 385 of file vf_signalstats.c.
filter16_vrep()
static int filter16_vrep (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 419 of file vf_signalstats.c.
compute_sat_hue_metrics8()
static int compute_sat_hue_metrics8 (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 467 of file vf_signalstats.c.
Referenced by filter_frame8().
compute_sat_hue_metrics16()
static int compute_sat_hue_metrics16 (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 505 of file vf_signalstats.c.
Referenced by filter_frame16().
compute_bit_depth()
static unsigned compute_bit_depth (uint16_t mask) static
Definition at line 544 of file vf_signalstats.c.
Referenced by filter_frame16(), and filter_frame8().
filter_frame8()
static int filter_frame8 (AVFilterLink * link, AVFrame * in) static
Definition at line 549 of file vf_signalstats.c.
Referenced by filter_frame().
filter_frame16()
static int filter_frame16 (AVFilterLink * link, AVFrame * in) static
Definition at line 767 of file vf_signalstats.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * link, AVFrame * in) static
Definition at line 984 of file vf_signalstats.c.
Variable Documentation
signalstats_options
const AVOption signalstats_options[] static
Initial value:
= {
    {"stat", "set statistics filters", OFFSET(filters), AV_OPT_TYPE_FLAGS, {.i64=0}, 0, INT_MAX, FLAGS, "filters"},
        {"tout", "analyze pixels for temporal outliers",                0, AV_OPT_TYPE_CONST, {.i64=1<<FILTER_TOUT}, 0, 0, FLAGS, "filters"},
        {"vrep", "analyze video lines for vertical line repetition",    0, AV_OPT_TYPE_CONST, {.i64=1<<FILTER_VREP}, 0, 0, FLAGS, "filters"},
        {"brng", "analyze for pixels outside of broadcast range",       0, AV_OPT_TYPE_CONST, {.i64=1<<FILTER_BRNG}, 0, 0, FLAGS, "filters"},
    {"out", "set video filter", OFFSET(outfilter), AV_OPT_TYPE_INT, {.i64=FILTER_NONE}, -1, FILT_NUMB-1, FLAGS, "out"},
        {"tout", "highlight pixels that depict temporal outliers",              0, AV_OPT_TYPE_CONST, {.i64=FILTER_TOUT}, 0, 0, FLAGS, "out"},
        {"vrep", "highlight video lines that depict vertical line repetition",  0, AV_OPT_TYPE_CONST, {.i64=FILTER_VREP}, 0, 0, FLAGS, "out"},
        {"brng", "highlight pixels that are outside of broadcast range",        0, AV_OPT_TYPE_CONST, {.i64=FILTER_BRNG}, 0, 0, FLAGS, "out"},
    {"c",     "set highlight color", OFFSET(rgba_color), AV_OPT_TYPE_COLOR, {.str="yellow"}, .flags=FLAGS},
    {"color", "set highlight color", OFFSET(rgba_color), AV_OPT_TYPE_COLOR, {.str="yellow"}, .flags=FLAGS},
    {NULL}
}
Definition at line 72 of file vf_signalstats.c.
name
const char* name
Definition at line 455 of file vf_signalstats.c.
Referenced by filter_frame16(), and filter_frame8().
process8
int(* process8) (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
Definition at line 456 of file vf_signalstats.c.
Referenced by filter_frame8().
process16
int(* process16) (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
Definition at line 457 of file vf_signalstats.c.
Referenced by filter_frame16().
filters_def
const { ... } filters_def[]
Initial value:
= {
    {"TOUT", filter8_tout, filter16_tout},
    {"VREP", filter8_vrep, filter16_vrep},
    {"BRNG", filter8_brng, filter16_brng},
    {NULL}
}
Referenced by filter_frame16(), and filter_frame8().
signalstats_inputs
const AVFilterPad signalstats_inputs[] static
Initial value:
= {
    {
        .name           = "default",
        .type           = AVMEDIA_TYPE_VIDEO,
        .filter_frame   = filter_frame,
    },
    { NULL }
}
Definition at line 995 of file vf_signalstats.c.
signalstats_outputs
const AVFilterPad signalstats_outputs[] static
Initial value:
= {
    {
        .name           = "default",
        .config_props   = config_props,
        .type           = AVMEDIA_TYPE_VIDEO,
    },
    { NULL }
}
Definition at line 1004 of file vf_signalstats.c.
ff_vf_signalstats
AVFilter ff_vf_signalstats
Initial value:
= {
    .name          = "signalstats",
    .description   = "Generate statistics from video analysis.",
    .init          = init,
    .uninit        = uninit,
    .query_formats = query_formats,
    .priv_size     = sizeof(SignalstatsContext),
    .inputs        = signalstats_inputs,
    .outputs       = signalstats_outputs,
    .priv_class    = &signalstats_class,
    .flags         = AVFILTER_FLAG_SLICE_THREADS,
}
Definition at line 1013 of file vf_signalstats.c.