FFmpeg: libavfilter/vf_minterpolate.c File Reference
vf_minterpolate.c File Reference
#include "motion_estimation.h"
#include "libavcodec/mathops.h"
#include "libavutil/avassert.h"
#include "libavutil/common.h"
#include "libavutil/motion_vector.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "libavutil/pixelutils.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
Data Structures
struct Cluster
struct Block
struct Pixel
struct Frame
struct MIContext
Macros
#define ME_MODE_BIDIR 0
Copyright (c) 2014-2015 Michael Niedermayer micha.nosp@m.elni.nosp@m.@gmx..nosp@m.at Copyright (c) 2016 Davinder Singh (DSM_) <ds.mudhar<.com>
#define ME_MODE_BILAT 1
#define MC_MODE_OBMC 0
#define MC_MODE_AOBMC 1
#define SCD_METHOD_NONE 0
#define SCD_METHOD_FDIFF 1
#define NB_FRAMES 4
#define NB_PIXEL_MVS 32
#define NB_CLUSTERS 128
#define ALPHA_MAX 1024
#define CLUSTER_THRESHOLD 4
#define PX_WEIGHT_MAX 255
#define COST_PRED_SCALE 64
#define OFFSET(x) offsetof(MIContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
#define CONST(name, help, val, unit) { name, help, 0, AV_OPT_TYPE_CONST, {.i64=val}, 0, 0, FLAGS, unit }
#define ADD_PRED(preds, px, py)
#define ADD_PIXELS(b_weight, mv_x, mv_y)
Enumerations
enum MIMode { MI_MODE_DUP = 0, MI_MODE_BLEND = 1, MI_MODE_MCI = 2 }
Functions
AVFILTER_DEFINE_CLASS (minterpolate)
static int query_formats (AVFilterContext *ctx)
static uint64_t get_sbad (AVMotionEstContext *me_ctx, int x, int y, int x_mv, int y_mv)
static uint64_t get_sbad_ob (AVMotionEstContext *me_ctx, int x, int y, int x_mv, int y_mv)
static uint64_t get_sad_ob (AVMotionEstContext *me_ctx, int x, int y, int x_mv, int y_mv)
static int config_input (AVFilterLink *inlink)
static int config_output (AVFilterLink *outlink)
static void search_mv (MIContext *mi_ctx, Block *blocks, int mb_x, int mb_y, int dir)
static void bilateral_me (MIContext *mi_ctx)
static int var_size_bme (MIContext *mi_ctx, Block *block, int x_mb, int y_mb, int n)
static int cluster_mvs (MIContext *mi_ctx)
static int inject_frame (AVFilterLink *inlink, AVFrame *avf_in)
static int detect_scene_change (MIContext *mi_ctx)
static void bidirectional_obmc (MIContext *mi_ctx, int alpha)
static void set_frame_data (MIContext *mi_ctx, int alpha, AVFrame *avf_out)
static void var_size_bmc (MIContext *mi_ctx, Block *block, int x_mb, int y_mb, int n, int alpha)
static void bilateral_obmc (MIContext *mi_ctx, Block *block, int mb_x, int mb_y, int alpha)
static void interpolate (AVFilterLink *inlink, AVFrame *avf_out)
static int filter_frame (AVFilterLink *inlink, AVFrame *avf_in)
static av_cold void free_blocks (Block *block, int sb)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const uint8_t obmc_linear32 [1024]
static const uint8_t obmc_linear16 [256]
static const uint8_t obmc_linear8 [64]
static const uint8_t obmc_linear4 [16]
static const uint8_t *const obmc_tab_linear [4]
static const AVOption minterpolate_options []
static const AVFilterPad minterpolate_inputs []
static const AVFilterPad minterpolate_outputs []
AVFilter ff_vf_minterpolate
Macro Definition Documentation
ME_MODE_BIDIR
#define ME_MODE_BIDIR 0
Copyright (c) 2014-2015 Michael Niedermayer micha.nosp@m.elni.nosp@m.@gmx..nosp@m.at Copyright (c) 2016 Davinder Singh (DSM_) <ds.mudhar<.com>
This file is part of FFmpeg.
FFmpeg is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
FFmpeg is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with FFmpeg; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
Definition at line 35 of file vf_minterpolate.c.
Referenced by config_input(), inject_frame(), and interpolate().
ME_MODE_BILAT
#define ME_MODE_BILAT 1
Definition at line 36 of file vf_minterpolate.c.
Referenced by config_input(), inject_frame(), and interpolate().
MC_MODE_OBMC
#define MC_MODE_OBMC 0
Definition at line 38 of file vf_minterpolate.c.
MC_MODE_AOBMC
#define MC_MODE_AOBMC 1
Definition at line 39 of file vf_minterpolate.c.
Referenced by bilateral_obmc(), and inject_frame().
SCD_METHOD_NONE
#define SCD_METHOD_NONE 0
Definition at line 41 of file vf_minterpolate.c.
SCD_METHOD_FDIFF
#define SCD_METHOD_FDIFF 1
Definition at line 42 of file vf_minterpolate.c.
Referenced by config_input(), and detect_scene_change().
NB_FRAMES
#define NB_FRAMES 4
Definition at line 44 of file vf_minterpolate.c.
Referenced by config_input(), filter_frame(), inject_frame(), and uninit().
NB_PIXEL_MVS
#define NB_PIXEL_MVS 32
Definition at line 45 of file vf_minterpolate.c.
NB_CLUSTERS
#define NB_CLUSTERS 128
Definition at line 46 of file vf_minterpolate.c.
Referenced by cluster_mvs(), and inject_frame().
ALPHA_MAX
#define ALPHA_MAX 1024
Definition at line 48 of file vf_minterpolate.c.
Referenced by bidirectional_obmc(), bilateral_obmc(), interpolate(), and set_frame_data().
CLUSTER_THRESHOLD
#define CLUSTER_THRESHOLD 4
Definition at line 49 of file vf_minterpolate.c.
Referenced by cluster_mvs().
PX_WEIGHT_MAX
#define PX_WEIGHT_MAX 255
Definition at line 50 of file vf_minterpolate.c.
Referenced by var_size_bmc().
COST_PRED_SCALE
#define COST_PRED_SCALE 64
Definition at line 51 of file vf_minterpolate.c.
Referenced by get_sad_ob(), get_sbad(), and get_sbad_ob().
OFFSET
#define OFFSET (x) offsetof(MIContext, x)
Definition at line 192 of file vf_minterpolate.c.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 193 of file vf_minterpolate.c.
CONST
#define CONST (name, help, val, unit) { name, help, 0, AV_OPT_TYPE_CONST, {.i64=val}, 0, 0, FLAGS, unit }
Definition at line 194 of file vf_minterpolate.c.
ADD_PRED
#define ADD_PRED (preds, px, py)
Value:
do {\
        preds.mvs[preds.nb][0] = px;\
        preds.mvs[preds.nb][1] = py;\
        preds.nb++;\
    } while(0)
Definition at line 398 of file vf_minterpolate.c.
Referenced by search_mv().
ADD_PIXELS
#define ADD_PIXELS (b_weight, mv_x, mv_y)
Value:
do {\
        if (!b_weight || pixel->nb + 1 >= NB_PIXEL_MVS)\
            continue;\
        pixel->refs[pixel->nb] = 1;\
        pixel->weights[pixel->nb] = b_weight * (ALPHA_MAX - alpha);\
        pixel->mvs[pixel->nb][0] = av_clip((mv_x * alpha) / ALPHA_MAX, x_min, x_max);\
        pixel->mvs[pixel->nb][1] = av_clip((mv_y * alpha) / ALPHA_MAX, y_min, y_max);\
        pixel->nb++;\
        pixel->refs[pixel->nb] = 2;\
        pixel->weights[pixel->nb] = b_weight * alpha;\
        pixel->mvs[pixel->nb][0] = av_clip(-mv_x * (ALPHA_MAX - alpha) / ALPHA_MAX, x_min, x_max);\
        pixel->mvs[pixel->nb][1] = av_clip(-mv_y * (ALPHA_MAX - alpha) / ALPHA_MAX, y_min, y_max);\
        pixel->nb++;\
    } while(0)
Definition at line 835 of file vf_minterpolate.c.
Referenced by bidirectional_obmc(), bilateral_obmc(), and var_size_bmc().
Enumeration Type Documentation
MIMode
enum MIMode
Enumerator
MI_MODE_DUP
MI_MODE_BLEND
MI_MODE_MCI
Definition at line 129 of file vf_minterpolate.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (minterpolate)
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 230 of file vf_minterpolate.c.
get_sbad()
static uint64_t get_sbad (AVMotionEstContext * me_ctx, int x, int y, int x_mv, int y_mv) static
Definition at line 250 of file vf_minterpolate.c.
Referenced by bilateral_obmc(), and inject_frame().
get_sbad_ob()
static uint64_t get_sbad_ob (AVMotionEstContext * me_ctx, int x, int y, int x_mv, int y_mv) static
Definition at line 275 of file vf_minterpolate.c.
Referenced by config_input().
get_sad_ob()
static uint64_t get_sad_ob (AVMotionEstContext * me_ctx, int x, int y, int x_mv, int y_mv) static
Definition at line 301 of file vf_minterpolate.c.
Referenced by config_input().
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 327 of file vf_minterpolate.c.
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 388 of file vf_minterpolate.c.
search_mv()
static void search_mv (MIContext * mi_ctx, Block * blocks, int mb_x, int mb_y, int dir) static
Definition at line 405 of file vf_minterpolate.c.
Referenced by bilateral_me(), and inject_frame().
bilateral_me()
static void bilateral_me (MIContext * mi_ctx) static
Definition at line 547 of file vf_minterpolate.c.
Referenced by inject_frame().
var_size_bme()
static int var_size_bme (MIContext * mi_ctx, Block * block, int x_mb, int y_mb, int n) static
Definition at line 568 of file vf_minterpolate.c.
Referenced by cluster_mvs().
cluster_mvs()
static int cluster_mvs (MIContext * mi_ctx) static
Definition at line 630 of file vf_minterpolate.c.
Referenced by inject_frame().
inject_frame()
static int inject_frame (AVFilterLink * inlink, AVFrame * avf_in) static
Definition at line 720 of file vf_minterpolate.c.
Referenced by filter_frame().
detect_scene_change()
static int detect_scene_change (MIContext * mi_ctx) static
Definition at line 807 of file vf_minterpolate.c.
Referenced by filter_frame().
bidirectional_obmc()
static void bidirectional_obmc (MIContext * mi_ctx, int alpha) static
Definition at line 851 of file vf_minterpolate.c.
Referenced by interpolate().
set_frame_data()
static void set_frame_data (MIContext * mi_ctx, int alpha, AVFrame * avf_out) static
Definition at line 899 of file vf_minterpolate.c.
Referenced by interpolate().
var_size_bmc()
static void var_size_bmc (MIContext * mi_ctx, Block * block, int x_mb, int y_mb, int n, int alpha) static
Definition at line 955 of file vf_minterpolate.c.
Referenced by interpolate().
bilateral_obmc()
static void bilateral_obmc (MIContext * mi_ctx, Block * block, int mb_x, int mb_y, int alpha) static
Definition at line 992 of file vf_minterpolate.c.
Referenced by interpolate().
interpolate()
static void interpolate (AVFilterLink * inlink, AVFrame * avf_out) static
Definition at line 1054 of file vf_minterpolate.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * avf_in) static
Definition at line 1136 of file vf_minterpolate.c.
free_blocks()
static av_cold void free_blocks (Block * block, int sb) static
Definition at line 1186 of file vf_minterpolate.c.
Referenced by uninit().
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 1194 of file vf_minterpolate.c.
Variable Documentation
obmc_linear32
const uint8_t obmc_linear32[1024] static
Definition at line 53 of file vf_minterpolate.c.
obmc_linear16
const uint8_t obmc_linear16[256] static
Initial value:
= {
  0,  4,  4,  8,  8, 12, 12, 16, 16, 12, 12,  8,  8,  4,  4,  0,
  4,  8, 16, 20, 28, 32, 40, 44, 44, 40, 32, 28, 20, 16,  8,  4,
  4, 16, 24, 36, 44, 56, 64, 76, 76, 64, 56, 44, 36, 24, 16,  4,
  8, 20, 36, 48, 64, 76, 92,104,104, 92, 76, 64, 48, 36, 20,  8,
  8, 28, 44, 64, 80,100,116,136,136,116,100, 80, 64, 44, 28,  8,
 12, 32, 56, 76,100,120,144,164,164,144,120,100, 76, 56, 32, 12,
 12, 40, 64, 92,116,144,168,196,196,168,144,116, 92, 64, 40, 12,
 16, 44, 76,104,136,164,196,224,224,196,164,136,104, 76, 44, 16,
 16, 44, 76,104,136,164,196,224,224,196,164,136,104, 76, 44, 16,
 12, 40, 64, 92,116,144,168,196,196,168,144,116, 92, 64, 40, 12,
 12, 32, 56, 76,100,120,144,164,164,144,120,100, 76, 56, 32, 12,
  8, 28, 44, 64, 80,100,116,136,136,116,100, 80, 64, 44, 28,  8,
  8, 20, 36, 48, 64, 76, 92,104,104, 92, 76, 64, 48, 36, 20,  8,
  4, 16, 24, 36, 44, 56, 64, 76, 76, 64, 56, 44, 36, 24, 16,  4,
  4,  8, 16, 20, 28, 32, 40, 44, 44, 40, 32, 28, 20, 16,  8,  4,
  0,  4,  4,  8,  8, 12, 12, 16, 16, 12, 12,  8,  8,  4,  4,  0,
}
Definition at line 88 of file vf_minterpolate.c.
obmc_linear8
const uint8_t obmc_linear8[64] static
Initial value:
= {
  4, 12, 20, 28, 28, 20, 12,  4,
 12, 36, 60, 84, 84, 60, 36, 12,
 20, 60,100,140,140,100, 60, 20,
 28, 84,140,196,196,140, 84, 28,
 28, 84,140,196,196,140, 84, 28,
 20, 60,100,140,140,100, 60, 20,
 12, 36, 60, 84, 84, 60, 36, 12,
  4, 12, 20, 28, 28, 20, 12,  4,
}
Definition at line 107 of file vf_minterpolate.c.
obmc_linear4
const uint8_t obmc_linear4[16] static
Initial value:
= {
 16, 48, 48, 16,
 48,144,144, 48,
 48,144,144, 48,
 16, 48, 48, 16,
}
Definition at line 118 of file vf_minterpolate.c.
obmc_tab_linear
const uint8_t* const obmc_tab_linear[4] static
Initial value:
= {
    obmc_linear32, obmc_linear16, obmc_linear8, obmc_linear4
}
Definition at line 125 of file vf_minterpolate.c.
Referenced by bidirectional_obmc(), and bilateral_obmc().
minterpolate_options
const AVOption minterpolate_options[] static
Definition at line 196 of file vf_minterpolate.c.
minterpolate_inputs
const AVFilterPad minterpolate_inputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .filter_frame  = filter_frame,
        .config_props  = config_input,
    },
    { NULL }
}
Definition at line 1215 of file vf_minterpolate.c.
minterpolate_outputs
const AVFilterPad minterpolate_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .config_props  = config_output,
    },
    { NULL }
}
Definition at line 1225 of file vf_minterpolate.c.
ff_vf_minterpolate
AVFilter ff_vf_minterpolate
Initial value:
= {
    .name          = "minterpolate",
    .description   = NULL_IF_CONFIG_SMALL("Frame rate conversion using Motion Interpolation."),
    .priv_size     = sizeof(MIContext),
    .priv_class    = &minterpolate_class,
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = minterpolate_inputs,
    .outputs       = minterpolate_outputs,
}
Definition at line 1234 of file vf_minterpolate.c.