FFmpeg: libavfilter/vf_nlmeans.c File Reference
vf_nlmeans.c File Reference
#include "libavutil/avassert.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
Data Structures
struct weighted_avg
struct NLMeansContext
struct thread_data
Macros
#define WEIGHT_LUT_NBITS 9
#define WEIGHT_LUT_SIZE (1<<WEIGHT_LUT_NBITS)
#define OFFSET(x) offsetof(NLMeansContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
#define CHECK_ODD_FIELD(field, name)
Functions
AVFILTER_DEFINE_CLASS (nlmeans)
static int query_formats (AVFilterContext *ctx)
static int get_integral_patch_value (const uint32_t *ii, int ii_lz_32, int x, int y, int p)
static void compute_safe_ssd_integral_image_c (uint32_t *dst, int dst_linesize_32, const uint8_t *s1, int linesize1, const uint8_t *s2, int linesize2, int w, int h)
Compute squared difference of the safe area (the zone where s1 and s2 overlap).
static void compute_unsafe_ssd_integral_image (uint32_t *dst, int dst_linesize_32, int startx, int starty, const uint8_t *src, int linesize, int offx, int offy, int r, int sw, int sh, int w, int h)
Compute squared difference of an unsafe area (the zone nor s1 nor s2 could be readable).
static void compute_ssd_integral_image (uint32_t *ii, int ii_linesize_32, const uint8_t *src, int linesize, int offx, int offy, int e, int w, int h)
static int config_input (AVFilterLink *inlink)
static int nlmeans_slice (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int nlmeans_plane (AVFilterContext *ctx, int w, int h, int p, int r, uint8_t *dst, int dst_linesize, const uint8_t *src, int src_linesize)
static int filter_frame (AVFilterLink *inlink, AVFrame *in)
static av_cold int init (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const AVOption nlmeans_options []
static const AVFilterPad nlmeans_inputs []
static const AVFilterPad nlmeans_outputs []
AVFilter ff_vf_nlmeans
Macro Definition Documentation
WEIGHT_LUT_NBITS
#define WEIGHT_LUT_NBITS 9
Definition at line 47 of file vf_nlmeans.c.
WEIGHT_LUT_SIZE
#define WEIGHT_LUT_SIZE (1<<WEIGHT_LUT_NBITS)
Definition at line 48 of file vf_nlmeans.c.
Referenced by init().
OFFSET
#define OFFSET (x) offsetof(NLMeansContext, x)
Definition at line 71 of file vf_nlmeans.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 72 of file vf_nlmeans.c.
CHECK_ODD_FIELD
#define CHECK_ODD_FIELD (field, name)
Value:
do {                       \
    if (!(s->field & 1)) {                                      \
        s->field |= 1;                                          \
        av_log(ctx, AV_LOG_WARNING, name " size must be odd, "  \
               "setting it to %d\n", s->field);                 \
    }                                                           \
} while (0)
Definition at line 473 of file vf_nlmeans.c.
Referenced by init().
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (nlmeans)
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 84 of file vf_nlmeans.c.
get_integral_patch_value()
static int get_integral_patch_value (const uint32_t * ii, int ii_lz_32, int x, int y, int p) inline static
Definition at line 132 of file vf_nlmeans.c.
Referenced by nlmeans_slice().
compute_safe_ssd_integral_image_c()
static void compute_safe_ssd_integral_image_c (uint32_t * dst, int dst_linesize_32, const uint8_t * s1, int linesize1, const uint8_t * s2, int linesize2, int w, int h) static
Compute squared difference of the safe area (the zone where s1 and s2 overlap).
It is likely the largest integral zone, so it is interesting to do as little checks as possible; contrary to the unsafe version of this function, we do not need any clipping here.
The line above dst and the column to its left are always readable.
This C version computes the SSD integral image using a scalar accumulator, while for SIMD implementation it is likely more interesting to use the two-loops algorithm variant.
Definition at line 153 of file vf_nlmeans.c.
Referenced by compute_ssd_integral_image().
compute_unsafe_ssd_integral_image()
static void compute_unsafe_ssd_integral_image (uint32_t * dst, int dst_linesize_32, int startx, int starty, const uint8_t * src, int linesize, int offx, int offy, int r, int sw, int sh, int w, int h) inline static
Compute squared difference of an unsafe area (the zone nor s1 nor s2 could be readable).
On the other hand, the line above dst and the column to its left are always readable.
There is little point in having this function SIMDified as it is likely too complex and only handle small portions of the image.
Parameters
dst integral image
dst_linesize_32 integral image linesize (in 32-bit integers unit)
startx integral starting x position
starty integral starting y position
src source plane buffer
linesize source plane linesize
offx source offsetting in x
offy source offsetting in y r absolute maximum source offsetting
sw source width
sh source height
w width to compute
h height to compute
Definition at line 198 of file vf_nlmeans.c.
Referenced by compute_ssd_integral_image(), and main().
compute_ssd_integral_image()
static void compute_ssd_integral_image (uint32_t * ii, int ii_linesize_32, const uint8_t * src, int linesize, int offx, int offy, int e, int w, int h) static
Definition at line 240 of file vf_nlmeans.c.
Referenced by main(), and nlmeans_plane().
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 303 of file vf_nlmeans.c.
nlmeans_slice()
static int nlmeans_slice (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 366 of file vf_nlmeans.c.
Referenced by nlmeans_plane().
nlmeans_plane()
static int nlmeans_plane (AVFilterContext * ctx, int w, int h, int p, int r, uint8_t * dst, int dst_linesize, const uint8_t * src, int src_linesize) static
Definition at line 394 of file vf_nlmeans.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 445 of file vf_nlmeans.c.
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 481 of file vf_nlmeans.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 515 of file vf_nlmeans.c.
Variable Documentation
nlmeans_options
const AVOption nlmeans_options[] static
Initial value:
= {
    { "s",  "denoising strength", OFFSET(sigma), AV_OPT_TYPE_DOUBLE, { .dbl = 1.0 }, 1.0, 30.0, FLAGS },
    { "p",  "patch size",                   OFFSET(patch_size),    AV_OPT_TYPE_INT, { .i64 = 3*2+1 }, 0, 99, FLAGS },
    { "pc", "patch size for chroma planes", OFFSET(patch_size_uv), AV_OPT_TYPE_INT, { .i64 = 0 },     0, 99, FLAGS },
    { "r",  "research window",                   OFFSET(research_size),    AV_OPT_TYPE_INT, { .i64 = 7*2+1 }, 0, 99, FLAGS },
    { "rc", "research window for chroma planes", OFFSET(research_size_uv), AV_OPT_TYPE_INT, { .i64 = 0 },     0, 99, FLAGS },
    { NULL }
}
Definition at line 73 of file vf_nlmeans.c.
nlmeans_inputs
const AVFilterPad nlmeans_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .config_props = config_input,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 522 of file vf_nlmeans.c.
nlmeans_outputs
const AVFilterPad nlmeans_outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_VIDEO,
    },
    { NULL }
}
Definition at line 532 of file vf_nlmeans.c.
ff_vf_nlmeans
AVFilter ff_vf_nlmeans
Initial value:
= {
    .name          = "nlmeans",
    .description   = NULL_IF_CONFIG_SMALL("Non-local means denoiser."),
    .priv_size     = sizeof(NLMeansContext),
    .init          = init,
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = nlmeans_inputs,
    .outputs       = nlmeans_outputs,
    .priv_class    = &nlmeans_class,
    .flags         = AVFILTER_FLAG_SUPPORT_TIMELINE_GENERIC | AVFILTER_FLAG_SLICE_THREADS,
}
Definition at line 540 of file vf_nlmeans.c.