FFmpeg: libavfilter/vf_idet.h File Reference
vf_idet.h File Reference
#include "libavutil/pixdesc.h"
#include "avfilter.h"
Data Structures
struct IDETContext
Macros
#define HIST_SIZE 4
Typedefs
typedef int(* ff_idet_filter_func) (const uint8_t *a, const uint8_t *b, const uint8_t *c, int w)
Enumerations
enum Type { TFF, BFF, PROGRESSIVE, UNDETERMINED }
enum RepeatedField { REPEAT_NONE, REPEAT_TOP, REPEAT_BOTTOM }
Functions
void ff_idet_init_x86 (IDETContext *idet, int for_16b)
int ff_idet_filter_line_c (const uint8_t *a, const uint8_t *b, const uint8_t *c, int w)
int ff_idet_filter_line_c_16bit (const uint16_t *a, const uint16_t *b, const uint16_t *c, int w)
Macro Definition Documentation
HIST_SIZE
#define HIST_SIZE 4
Definition at line 25 of file vf_idet.h.
Typedef Documentation
ff_idet_filter_func
typedef int(* ff_idet_filter_func) (const uint8_t *a, const uint8_t *b, const uint8_t *c, int w)
Definition at line 27 of file vf_idet.h.
Enumeration Type Documentation
Type
enum Type
Enumerator
TFF
BFF
PROGRESSIVE
UNDETERMINED
Definition at line 29 of file vf_idet.h.
RepeatedField
enum RepeatedField
Enumerator
REPEAT_NONE
REPEAT_TOP
REPEAT_BOTTOM
Definition at line 36 of file vf_idet.h.
Function Documentation
ff_idet_init_x86()
void ff_idet_init_x86 (IDETContext * idet, int for_16b)
Definition at line 69 of file vf_idet_init.c.
Referenced by filter_frame(), and init().
ff_idet_filter_line_c()
int ff_idet_filter_line_c (const uint8_t * a, const uint8_t * b, const uint8_t * c, int w)
Definition at line 87 of file vf_idet.c.
Referenced by init().
ff_idet_filter_line_c_16bit()
int ff_idet_filter_line_c_16bit (const uint16_t * a, const uint16_t * b, const uint16_t * c, int w)
Definition at line 100 of file vf_idet.c.
Referenced by filter_frame().