FFmpeg: libavfilter/vf_fftfilt.c File Reference
vf_fftfilt.c File Reference
FFT domain filtering.
#include "libavfilter/internal.h"
#include "libavutil/common.h"
#include "libavutil/imgutils.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "libavcodec/avfft.h"
#include "libavutil/eval.h"
Data Structures
struct FFTFILTContext
Macros
#define MAX_PLANES 4
#define OFFSET(x) offsetof(FFTFILTContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Enumerations
enum {
VAR_X, VAR_Y, VAR_W, VAR_H,
VAR_VARS_NB
}
enum { Y = 0, U, V }
Functions
AVFILTER_DEFINE_CLASS (fftfilt)
static double lum (void *priv, double x, double y, int plane)
static double weight_Y (void *priv, double x, double y)
static double weight_U (void *priv, double x, double y)
static double weight_V (void *priv, double x, double y)
static void copy_rev (FFTSample *dest, int w, int w2)
static void rdft_horizontal (FFTFILTContext *s, AVFrame *in, int w, int h, int plane)
static void rdft_vertical (FFTFILTContext *s, int h, int plane)
static void irdft_vertical (FFTFILTContext *s, int h, int plane)
static void irdft_horizontal (FFTFILTContext *s, AVFrame *out, int w, int h, int plane)
static av_cold int initialize (AVFilterContext *ctx)
static int config_props (AVFilterLink *inlink)
static int filter_frame (AVFilterLink *inlink, AVFrame *in)
static av_cold void uninit (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
Variables
static const char *const var_names [] = { "X", "Y", "W", "H", NULL }
static const AVOption fftfilt_options []
static const AVFilterPad fftfilt_inputs []
static const AVFilterPad fftfilt_outputs []
AVFilter ff_vf_fftfilt
Detailed Description
FFT domain filtering.
Definition in file vf_fftfilt.c.
Macro Definition Documentation
MAX_PLANES
#define MAX_PLANES 4
Definition at line 34 of file vf_fftfilt.c.
Referenced by uninit().
OFFSET
#define OFFSET (x) offsetof(FFTFILTContext, x)
Definition at line 59 of file vf_fftfilt.c.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 60 of file vf_fftfilt.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
VAR_X
VAR_Y
VAR_W
VAR_H
VAR_VARS_NB
Definition at line 55 of file vf_fftfilt.c.
anonymous enum
anonymous enum
Enumerator
Y
U
V
Definition at line 57 of file vf_fftfilt.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (fftfilt)
lum()
static double lum (void * priv, double x, double y, int plane) inline static
Definition at line 74 of file vf_fftfilt.c.
Referenced by weight_U(), weight_V(), and weight_Y().
weight_Y()
static double weight_Y (void * priv, double x, double y) static
Definition at line 80 of file vf_fftfilt.c.
Referenced by initialize().
weight_U()
static double weight_U (void * priv, double x, double y) static
Definition at line 81 of file vf_fftfilt.c.
Referenced by initialize().
weight_V()
static double weight_V (void * priv, double x, double y) static
Definition at line 82 of file vf_fftfilt.c.
Referenced by initialize().
copy_rev()
static void copy_rev (FFTSample * dest, int w, int w2) static
Definition at line 84 of file vf_fftfilt.c.
Referenced by rdft_horizontal(), and rdft_vertical().
rdft_horizontal()
static void rdft_horizontal (FFTFILTContext * s, AVFrame * in, int w, int h, int plane) static
Definition at line 96 of file vf_fftfilt.c.
Referenced by filter_frame().
rdft_vertical()
static void rdft_vertical (FFTFILTContext * s, int h, int plane) static
Definition at line 115 of file vf_fftfilt.c.
Referenced by filter_frame().
irdft_vertical()
static void irdft_vertical (FFTFILTContext * s, int h, int plane) static
Definition at line 133 of file vf_fftfilt.c.
Referenced by filter_frame().
irdft_horizontal()
static void irdft_horizontal (FFTFILTContext * s, AVFrame * out, int w, int h, int plane) static
Definition at line 149 of file vf_fftfilt.c.
Referenced by filter_frame().
initialize()
static av_cold int initialize (AVFilterContext * ctx) static
Definition at line 166 of file vf_fftfilt.c.
config_props()
static int config_props (AVFilterLink * inlink) static
Definition at line 200 of file vf_fftfilt.c.
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 248 of file vf_fftfilt.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 292 of file vf_fftfilt.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 304 of file vf_fftfilt.c.
Variable Documentation
var_names
const char* const var_names[] = { "X", "Y", "W", "H", NULL } static
Definition at line 54 of file vf_fftfilt.c.
Referenced by initialize().
fftfilt_options
const AVOption fftfilt_options[] static
Initial value:
= {
    { "dc_Y",  "adjust gain in Y plane",              OFFSET(dc[Y]),      AV_OPT_TYPE_INT,    {.i64 = 0},      0,     1000,     FLAGS },
    { "dc_U",  "adjust gain in U plane",              OFFSET(dc[U]),      AV_OPT_TYPE_INT,    {.i64 = 0},      0,     1000,     FLAGS },
    { "dc_V",  "adjust gain in V plane",              OFFSET(dc[V]),      AV_OPT_TYPE_INT,    {.i64 = 0},      0,     1000,     FLAGS },
    { "weight_Y", "set luminance expression in Y plane",   OFFSET(weight_str[Y]), AV_OPT_TYPE_STRING, {.str = "1"}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "weight_U", "set chrominance expression in U plane", OFFSET(weight_str[U]), AV_OPT_TYPE_STRING, {.str = NULL}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "weight_V", "set chrominance expression in V plane", OFFSET(weight_str[V]), AV_OPT_TYPE_STRING, {.str = NULL}, CHAR_MIN, CHAR_MAX, FLAGS },
    {NULL},
}
Definition at line 62 of file vf_fftfilt.c.
fftfilt_inputs
const AVFilterPad fftfilt_inputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_VIDEO,
        .config_props = config_props,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 318 of file vf_fftfilt.c.
fftfilt_outputs
const AVFilterPad fftfilt_outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_VIDEO,
    },
    { NULL }
}
Definition at line 328 of file vf_fftfilt.c.
ff_vf_fftfilt
AVFilter ff_vf_fftfilt
Initial value:
= {
    .name            = "fftfilt",
    .description     = NULL_IF_CONFIG_SMALL("Apply arbitrary expressions to pixels in frequency domain."),
    .priv_size       = sizeof(FFTFILTContext),
    .priv_class      = &fftfilt_class,
    .inputs          = fftfilt_inputs,
    .outputs         = fftfilt_outputs,
    .query_formats   = query_formats,
    .init            = initialize,
    .uninit          = uninit,
}
Definition at line 336 of file vf_fftfilt.c.