FFmpeg: libavfilter/vf_zscale.c File Reference
vf_zscale.c File Reference
zscale video filter using z.lib library
#include <float.h>
#include <stdio.h>
#include <string.h>
#include <zimg.h>
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
#include "libavutil/avstring.h"
#include "libavutil/eval.h"
#include "libavutil/internal.h"
#include "libavutil/mathematics.h"
#include "libavutil/opt.h"
#include "libavutil/parseutils.h"
#include "libavutil/pixdesc.h"
#include "libavutil/imgutils.h"
#include "libavutil/avassert.h"
Data Structures
struct ZScaleContext
Macros
#define OFFSET(x) offsetof(ZScaleContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Enumerations
enum var_name {
VAR_CH, VAR_N, VAR_NB_IN_CHANNELS, VAR_NB_OUT_CHANNELS,
VAR_T, VAR_S, VAR_VARS_NB, VAR_VALUE1,
VAR_VALUE2, VAR_VARS_NB, VAR_TB, VAR_PTS,
VAR_START_PTS, VAR_PREV_PTS, VAR_PREV_SELECTED_PTS, VAR_T,
VAR_START_T, VAR_PREV_T, VAR_PREV_SELECTED_T, VAR_PICT_TYPE,
VAR_I, VAR_P, VAR_B, VAR_S,
VAR_SI, VAR_SP, VAR_BI, VAR_PICT_TYPE_I,
VAR_PICT_TYPE_P, VAR_PICT_TYPE_B, VAR_PICT_TYPE_S, VAR_PICT_TYPE_SI,
VAR_PICT_TYPE_SP, VAR_PICT_TYPE_BI, VAR_INTERLACE_TYPE, VAR_INTERLACE_TYPE_P,
VAR_INTERLACE_TYPE_T, VAR_INTERLACE_TYPE_B, VAR_CONSUMED_SAMPLES_N, VAR_SAMPLES_N,
VAR_SAMPLE_RATE, VAR_N, VAR_SELECTED_N, VAR_PREV_SELECTED_N,
VAR_KEY, VAR_POS, VAR_SCENE, VAR_CONCATDEC_SELECT,
VAR_VARS_NB, VAR_FRAME_RATE, VAR_INTERLACED, VAR_N,
VAR_NB_CONSUMED_SAMPLES, VAR_NB_SAMPLES, VAR_POS, VAR_PREV_INPTS,
VAR_PREV_INT, VAR_PREV_OUTPTS, VAR_PREV_OUTT, VAR_PTS,
VAR_SAMPLE_RATE, VAR_STARTPTS, VAR_STARTT, VAR_T,
VAR_TB, VAR_RTCTIME, VAR_RTCSTART, VAR_S,
VAR_SR, VAR_VARS_NB, VAR_AVTB, VAR_INTB,
VAR_SR, VAR_VARS_NB, VAR_W, VAR_H,
VAR_A, VAR_DAR, VAR_SAR, VAR_HSUB,
VAR_VSUB, VARS_NB, VAR_W, VAR_H,
VAR_CW, VAR_CH, VAR_HSUB, VAR_VSUB,
VARS_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_A, VAR_SAR, VAR_DAR,
VAR_HSUB, VAR_VSUB, VAR_X, VAR_Y,
VAR_N, VAR_POS, VAR_T, VAR_VARS_NB,
VAR_DAR, VAR_HSUB, VAR_VSUB, VAR_IN_H,
VAR_IH, VAR_IN_W, VAR_IW, VAR_SAR,
VAR_X, VAR_Y, VAR_H, VAR_W,
VAR_T, VAR_MAX, VARS_NB, VAR_DAR,
VAR_HSUB, VAR_VSUB, VAR_LINE_H, VAR_LH,
VAR_MAIN_H, VAR_h, VAR_H, VAR_MAIN_W,
VAR_w, VAR_W, VAR_MAX_GLYPH_A, VAR_ASCENT,
VAR_MAX_GLYPH_D, VAR_DESCENT, VAR_MAX_GLYPH_H, VAR_MAX_GLYPH_W,
VAR_N, VAR_SAR, VAR_T, VAR_TEXT_H,
VAR_TH, VAR_TEXT_W, VAR_TW, VAR_X,
VAR_Y, VAR_PICT_TYPE, VAR_VARS_NB, VAR_N,
VAR_POS, VAR_R, VAR_T, VAR_NB,
VAR_N, VAR_PTS, VAR_R, VAR_T,
VAR_TB, VAR_NB, VAR_W, VAR_H,
VAR_VAL, VAR_MAXVAL, VAR_MINVAL, VAR_NEGVAL,
VAR_CLIPVAL, VAR_VARS_NB, VAR_W, VAR_H,
VAR_X, VAR_Y, VAR_BITDEPTHX, VAR_BITDEPTHY,
VAR_VARS_NB, VAR_MAIN_W, VAR_MW, VAR_MAIN_H,
VAR_MH, VAR_OVERLAY_W, VAR_OW, VAR_OVERLAY_H,
VAR_OH, VAR_HSUB, VAR_VSUB, VAR_X,
VAR_Y, VAR_N, VAR_POS, VAR_T,
VAR_VARS_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_X, VAR_Y, VAR_A,
VAR_SAR, VAR_DAR, VAR_HSUB, VAR_VSUB,
VARS_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_HSUB, VAR_VSUB, VAR_N,
VAR_T, VAR_VARS_NB, VAR_IN_W, VAR_IW,
VAR_IN_H, VAR_IH, VAR_OUT_W, VAR_OW,
VAR_OUT_H, VAR_OH, VAR_A, VAR_SAR,
VAR_DAR, VAR_HSUB, VAR_VSUB, VAR_OHSUB,
VAR_OVSUB, VARS_NB, VAR_PI, VAR_PHI,
VAR_E, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_A, VAR_DAR, VAR_SAR,
VARS_NB, VAR_W, VAR_H, VAR_N,
VAR_PTS, VAR_R, VAR_T, VAR_TB,
VAR_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_IN, VAR_ON, VAR_DURATION,
VAR_PDURATION, VAR_TIME, VAR_FRAME, VAR_ZOOM,
VAR_PZOOM, VAR_X, VAR_PX, VAR_Y,
VAR_PY, VAR_A, VAR_SAR, VAR_DAR,
VAR_HSUB, VAR_VSUB, VARS_NB, VAR_IN_W,
VAR_IW, VAR_IN_H, VAR_IH, VAR_OUT_W,
VAR_OW, VAR_OUT_H, VAR_OH, VAR_A,
VAR_SAR, VAR_DAR, VAR_HSUB, VAR_VSUB,
VAR_OHSUB, VAR_OVSUB, VARS_NB, VAR_X,
VAR_Y, VAR_W, VAR_H, VAR_TIME,
VAR_SPEED, VAR_TEMPO, VAR_ORDER, VAR_PATTERN,
VAR_ROW, VAR_VARS_NB
}
Functions
static av_cold int init_dict (AVFilterContext *ctx, AVDictionary **opts)
static int query_formats (AVFilterContext *ctx)
static int config_props (AVFilterLink *outlink)
static int print_zimg_error (AVFilterContext *ctx)
static int convert_chroma_location (enum AVChromaLocation chroma_location)
static int convert_matrix (enum AVColorSpace colorspace)
static int convert_trc (enum AVColorTransferCharacteristic color_trc)
static int convert_primaries (enum AVColorPrimaries color_primaries)
static int convert_range (enum AVColorRange color_range)
static int filter_frame (AVFilterLink *link, AVFrame *in)
static void uninit (AVFilterContext *ctx)
static int process_command (AVFilterContext *ctx, const char *cmd, const char *args, char *res, int res_len, int flags)
Variables
static const char *const var_names []
static const AVOption zscale_options []
static const AVClass zscale_class
static const AVFilterPad avfilter_vf_zscale_inputs []
static const AVFilterPad avfilter_vf_zscale_outputs []
AVFilter ff_vf_zscale
Detailed Description
zscale video filter using z.lib library
Definition in file vf_zscale.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(ZScaleContext, x)
Definition at line 687 of file vf_zscale.c.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 688 of file vf_zscale.c.
Enumeration Type Documentation
var_name
enum var_name
Enumerator
VAR_CH
VAR_N
VAR_NB_IN_CHANNELS
VAR_NB_OUT_CHANNELS
VAR_T
VAR_S
VAR_VARS_NB
VAR_VALUE1
VAR_VALUE2
VAR_VARS_NB
VAR_TB
VAR_PTS
VAR_START_PTS
VAR_PREV_PTS
VAR_PREV_SELECTED_PTS
VAR_T
VAR_START_T
VAR_PREV_T
VAR_PREV_SELECTED_T
VAR_PICT_TYPE
VAR_I
VAR_P
VAR_B
VAR_S
VAR_SI
VAR_SP
VAR_BI
VAR_PICT_TYPE_I
VAR_PICT_TYPE_P
VAR_PICT_TYPE_B
VAR_PICT_TYPE_S
VAR_PICT_TYPE_SI
VAR_PICT_TYPE_SP
VAR_PICT_TYPE_BI
VAR_INTERLACE_TYPE
VAR_INTERLACE_TYPE_P
VAR_INTERLACE_TYPE_T
VAR_INTERLACE_TYPE_B
VAR_CONSUMED_SAMPLES_N
VAR_SAMPLES_N
VAR_SAMPLE_RATE
VAR_N
VAR_SELECTED_N
VAR_PREV_SELECTED_N
VAR_KEY
VAR_POS
VAR_SCENE
VAR_CONCATDEC_SELECT
VAR_VARS_NB
VAR_FRAME_RATE
VAR_INTERLACED
VAR_N
VAR_NB_CONSUMED_SAMPLES
VAR_NB_SAMPLES
VAR_POS
VAR_PREV_INPTS
VAR_PREV_INT
VAR_PREV_OUTPTS
VAR_PREV_OUTT
VAR_PTS
VAR_SAMPLE_RATE
VAR_STARTPTS
VAR_STARTT
VAR_T
VAR_TB
VAR_RTCTIME
VAR_RTCSTART
VAR_S
VAR_SR
VAR_VARS_NB
VAR_AVTB
VAR_INTB
VAR_SR
VAR_VARS_NB
VAR_W
VAR_H
VAR_A
VAR_DAR
VAR_SAR
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_W
VAR_H
VAR_CW
VAR_CH
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_X
VAR_Y
VAR_N
VAR_POS
VAR_T
VAR_VARS_NB
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_IN_H
VAR_IH
VAR_IN_W
VAR_IW
VAR_SAR
VAR_X
VAR_Y
VAR_H
VAR_W
VAR_T
VAR_MAX
VARS_NB
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_LINE_H
VAR_LH
VAR_MAIN_H
VAR_h
VAR_H
VAR_MAIN_W
VAR_w
VAR_W
VAR_MAX_GLYPH_A
VAR_ASCENT
VAR_MAX_GLYPH_D
VAR_DESCENT
VAR_MAX_GLYPH_H
VAR_MAX_GLYPH_W
VAR_N
VAR_SAR
VAR_T
VAR_TEXT_H
VAR_TH
VAR_TEXT_W
VAR_TW
VAR_X
VAR_Y
VAR_PICT_TYPE
VAR_VARS_NB
VAR_N
VAR_POS
VAR_R
VAR_T
VAR_NB
VAR_N
VAR_PTS
VAR_R
VAR_T
VAR_TB
VAR_NB
VAR_W
VAR_H
VAR_VAL
VAR_MAXVAL
VAR_MINVAL
VAR_NEGVAL
VAR_CLIPVAL
VAR_VARS_NB
VAR_W
VAR_H
VAR_X
VAR_Y
VAR_BITDEPTHX
VAR_BITDEPTHY
VAR_VARS_NB
VAR_MAIN_W
VAR_MW
VAR_MAIN_H
VAR_MH
VAR_OVERLAY_W
VAR_OW
VAR_OVERLAY_H
VAR_OH
VAR_HSUB
VAR_VSUB
VAR_X
VAR_Y
VAR_N
VAR_POS
VAR_T
VAR_VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_X
VAR_Y
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_HSUB
VAR_VSUB
VAR_N
VAR_T
VAR_VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_OHSUB
VAR_OVSUB
VARS_NB
VAR_PI
VAR_PHI
VAR_E
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_DAR
VAR_SAR
VARS_NB
VAR_W
VAR_H
VAR_N
VAR_PTS
VAR_R
VAR_T
VAR_TB
VAR_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_IN
VAR_ON
VAR_DURATION
VAR_PDURATION
VAR_TIME
VAR_FRAME
VAR_ZOOM
VAR_PZOOM
VAR_X
VAR_PX
VAR_Y
VAR_PY
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_OHSUB
VAR_OVSUB
VARS_NB
VAR_X
VAR_Y
VAR_W
VAR_H
VAR_TIME
VAR_SPEED
VAR_TEMPO
VAR_ORDER
VAR_PATTERN
VAR_ROW
VAR_VARS_NB
Definition at line 61 of file vf_zscale.c.
Function Documentation
init_dict()
static av_cold int init_dict (AVFilterContext * ctx, AVDictionary ** opts) static
Definition at line 127 of file vf_zscale.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 161 of file vf_zscale.c.
config_props()
static int config_props (AVFilterLink * outlink) static
Definition at line 192 of file vf_zscale.c.
Referenced by filter_frame(), and process_command().
print_zimg_error()
static int print_zimg_error (AVFilterContext * ctx) static
Definition at line 315 of file vf_zscale.c.
Referenced by filter_frame().
convert_chroma_location()
static int convert_chroma_location (enum AVChromaLocation chroma_location) static
Definition at line 325 of file vf_zscale.c.
Referenced by filter_frame().
convert_matrix()
static int convert_matrix (enum AVColorSpace colorspace) static
Definition at line 345 of file vf_zscale.c.
Referenced by filter_frame().
convert_trc()
static int convert_trc (enum AVColorTransferCharacteristic color_trc) static
Definition at line 368 of file vf_zscale.c.
Referenced by filter_frame().
convert_primaries()
static int convert_primaries (enum AVColorPrimaries color_primaries) static
Definition at line 393 of file vf_zscale.c.
Referenced by filter_frame().
convert_range()
static int convert_range (enum AVColorRange color_range) static
Definition at line 412 of file vf_zscale.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * link, AVFrame * in) static
Definition at line 424 of file vf_zscale.c.
uninit()
static void uninit (AVFilterContext * ctx) static
Definition at line 654 of file vf_zscale.c.
process_command()
static int process_command (AVFilterContext * ctx, const char * cmd, const char * args, char * res, int res_len, int flags) static
Definition at line 663 of file vf_zscale.c.
Variable Documentation
var_names
const char* const var_names[] static
Initial value:
= {
    "in_w",   "iw",
    "in_h",   "ih",
    "out_w",  "ow",
    "out_h",  "oh",
    "a",
    "sar",
    "dar",
    "hsub",
    "vsub",
    "ohsub",
    "ovsub",
    NULL
}
Definition at line 46 of file vf_zscale.c.
Referenced by config_props().
zscale_options
const AVOption zscale_options[] static
Definition at line 690 of file vf_zscale.c.
zscale_class
const AVClass zscale_class static
Initial value:
= {
    .class_name       = "zscale",
    .item_name        = av_default_item_name,
    .option           = zscale_options,
    .version          = LIBAVUTIL_VERSION_INT,
    .category         = AV_CLASS_CATEGORY_FILTER,
}
Definition at line 771 of file vf_zscale.c.
avfilter_vf_zscale_inputs
const AVFilterPad avfilter_vf_zscale_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 779 of file vf_zscale.c.
avfilter_vf_zscale_outputs
const AVFilterPad avfilter_vf_zscale_outputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .config_props = config_props,
    },
    { NULL }
}
Definition at line 788 of file vf_zscale.c.
ff_vf_zscale
AVFilter ff_vf_zscale
Initial value:
= {
    .name            = "zscale",
    .description     = NULL_IF_CONFIG_SMALL("Apply resizing, colorspace and bit depth conversion."),
    .init_dict       = init_dict,
    .query_formats   = query_formats,
    .priv_size       = sizeof(ZScaleContext),
    .priv_class      = &zscale_class,
    .uninit          = uninit,
    .inputs          = avfilter_vf_zscale_inputs,
    .outputs         = avfilter_vf_zscale_outputs,
    .process_command = process_command,
}
Definition at line 797 of file vf_zscale.c.