FFmpeg: libavfilter/vf_gblur.c File Reference
vf_gblur.c File Reference
#include "libavutil/imgutils.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
Data Structures
struct GBlurContext
struct ThreadData
Macros
#define OFFSET(x) offsetof(GBlurContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Functions
AVFILTER_DEFINE_CLASS (gblur)
static int filter_horizontally (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int filter_vertically (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int filter_postscale (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static void gaussianiir2d (AVFilterContext *ctx, int plane)
static int query_formats (AVFilterContext *ctx)
static int config_input (AVFilterLink *inlink)
static void set_params (float sigma, int steps, float *postscale, float *boundaryscale, float *nu)
static int filter_frame (AVFilterLink *inlink, AVFrame *in)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const AVOption gblur_options []
static const AVFilterPad gblur_inputs []
static const AVFilterPad gblur_outputs []
AVFilter ff_vf_gblur
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(GBlurContext, x)
Definition at line 57 of file vf_gblur.c.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 58 of file vf_gblur.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (gblur)
filter_horizontally()
static int filter_horizontally (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 75 of file vf_gblur.c.
Referenced by gaussianiir2d().
filter_vertically()
static int filter_vertically (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 111 of file vf_gblur.c.
Referenced by gaussianiir2d().
filter_postscale()
static int filter_postscale (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 149 of file vf_gblur.c.
Referenced by gaussianiir2d().
gaussianiir2d()
static void gaussianiir2d (AVFilterContext * ctx, int plane) static
Definition at line 168 of file vf_gblur.c.
Referenced by filter_frame().
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 186 of file vf_gblur.c.
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 212 of file vf_gblur.c.
set_params()
static void set_params (float sigma, int steps, float * postscale, float * boundaryscale, float * nu) static
Definition at line 236 of file vf_gblur.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 247 of file vf_gblur.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 332 of file vf_gblur.c.
Variable Documentation
gblur_options
const AVOption gblur_options[] static
Initial value:
= {
    { "sigma",  "set sigma",            OFFSET(sigma),  AV_OPT_TYPE_FLOAT, {.dbl=0.5}, 0.0, 1024, FLAGS },
    { "steps",  "set number of steps",  OFFSET(steps),  AV_OPT_TYPE_INT,   {.i64=1},     1,    6, FLAGS },
    { "planes", "set planes to filter", OFFSET(planes), AV_OPT_TYPE_INT,   {.i64=0xF},   0,  0xF, FLAGS },
    { "sigmaV", "set vertical sigma",   OFFSET(sigmaV), AV_OPT_TYPE_FLOAT, {.dbl=-1},   -1, 1024, FLAGS },
    { NULL }
}
Definition at line 60 of file vf_gblur.c.
gblur_inputs
const AVFilterPad gblur_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .config_props = config_input,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 339 of file vf_gblur.c.
gblur_outputs
const AVFilterPad gblur_outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_VIDEO,
    },
    { NULL }
}
Definition at line 349 of file vf_gblur.c.
ff_vf_gblur
AVFilter ff_vf_gblur
Initial value:
= {
    .name          = "gblur",
    .description   = NULL_IF_CONFIG_SMALL("Apply Gaussian Blur filter."),
    .priv_size     = sizeof(GBlurContext),
    .priv_class    = &gblur_class,
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = gblur_inputs,
    .outputs       = gblur_outputs,
    .flags         = AVFILTER_FLAG_SUPPORT_TIMELINE_GENERIC | AVFILTER_FLAG_SLICE_THREADS,
}
Definition at line 357 of file vf_gblur.c.