FFmpeg: libavfilter/x86/vf_pullup_init.c File Reference
vf_pullup_init.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/mem.h"
#include "libavutil/x86/asm.h"
#include "libavutil/x86/cpu.h"
#include "libavfilter/vf_pullup.h"
Functions
int ff_pullup_filter_diff_mmx (const uint8_t *a, const uint8_t *b, ptrdiff_t s)
int ff_pullup_filter_comb_mmx (const uint8_t *a, const uint8_t *b, ptrdiff_t s)
int ff_pullup_filter_var_mmx (const uint8_t *a, const uint8_t *b, ptrdiff_t s)
av_cold void ff_pullup_init_x86 (PullupContext *s)
Function Documentation
ff_pullup_filter_diff_mmx()
int ff_pullup_filter_diff_mmx (const uint8_t * a, const uint8_t * b, ptrdiff_t s)
Referenced by ff_pullup_init_x86().
ff_pullup_filter_comb_mmx()
int ff_pullup_filter_comb_mmx (const uint8_t * a, const uint8_t * b, ptrdiff_t s)
Referenced by ff_pullup_init_x86().
ff_pullup_filter_var_mmx()
int ff_pullup_filter_var_mmx (const uint8_t * a, const uint8_t * b, ptrdiff_t s)
Referenced by ff_pullup_init_x86().
ff_pullup_init_x86()
av_cold void ff_pullup_init_x86 (PullupContext * s)
Definition at line 30 of file vf_pullup_init.c.
Referenced by config_input().