FFmpeg: libavfilter/x86/vf_hqdn3d_init.c File Reference
vf_hqdn3d_init.c File Reference
#include <stddef.h>
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavfilter/vf_hqdn3d.h"
#include "config.h"
Functions
void ff_hqdn3d_row_8_x86 (uint8_t *src, uint8_t *dst, uint16_t *line_ant, uint16_t *frame_ant, ptrdiff_t w, int16_t *spatial, int16_t *temporal)
void ff_hqdn3d_row_9_x86 (uint8_t *src, uint8_t *dst, uint16_t *line_ant, uint16_t *frame_ant, ptrdiff_t w, int16_t *spatial, int16_t *temporal)
void ff_hqdn3d_row_10_x86 (uint8_t *src, uint8_t *dst, uint16_t *line_ant, uint16_t *frame_ant, ptrdiff_t w, int16_t *spatial, int16_t *temporal)
void ff_hqdn3d_row_16_x86 (uint8_t *src, uint8_t *dst, uint16_t *line_ant, uint16_t *frame_ant, ptrdiff_t w, int16_t *spatial, int16_t *temporal)
av_cold void ff_hqdn3d_init_x86 (HQDN3DContext *hqdn3d)
Function Documentation
ff_hqdn3d_row_8_x86()
void ff_hqdn3d_row_8_x86 (uint8_t * src, uint8_t * dst, uint16_t * line_ant, uint16_t * frame_ant, ptrdiff_t w, int16_t * spatial, int16_t * temporal)
Referenced by ff_hqdn3d_init_x86().
ff_hqdn3d_row_9_x86()
void ff_hqdn3d_row_9_x86 (uint8_t * src, uint8_t * dst, uint16_t * line_ant, uint16_t * frame_ant, ptrdiff_t w, int16_t * spatial, int16_t * temporal)
Referenced by ff_hqdn3d_init_x86().
ff_hqdn3d_row_10_x86()
void ff_hqdn3d_row_10_x86 (uint8_t * src, uint8_t * dst, uint16_t * line_ant, uint16_t * frame_ant, ptrdiff_t w, int16_t * spatial, int16_t * temporal)
Referenced by ff_hqdn3d_init_x86().
ff_hqdn3d_row_16_x86()
void ff_hqdn3d_row_16_x86 (uint8_t * src, uint8_t * dst, uint16_t * line_ant, uint16_t * frame_ant, ptrdiff_t w, int16_t * spatial, int16_t * temporal)
Referenced by ff_hqdn3d_init_x86().
ff_hqdn3d_init_x86()
av_cold void ff_hqdn3d_init_x86 (HQDN3DContext * hqdn3d)
Definition at line 41 of file vf_hqdn3d_init.c.
Referenced by config_input().