FFmpeg: libavfilter/vf_swapuv.c File Reference
vf_swapuv.c File Reference
swap UV filter
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "libavutil/version.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
Data Structures
struct SwapUVContext
Functions
AVFILTER_DEFINE_CLASS (swapuv)
static void do_swap (AVFrame *frame)
static AVFrame * get_video_buffer (AVFilterLink *link, int w, int h)
static int filter_frame (AVFilterLink *link, AVFrame *inpicref)
static int is_planar_yuv (const AVPixFmtDescriptor *desc)
static int query_formats (AVFilterContext *ctx)
Variables
static const AVOption swapuv_options []
static const AVFilterPad swapuv_inputs []
static const AVFilterPad swapuv_outputs []
AVFilter ff_vf_swapuv
Detailed Description
swap UV filter
Definition in file vf_swapuv.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (swapuv)
do_swap()
static void do_swap (AVFrame * frame) static
Definition at line 44 of file vf_swapuv.c.
Referenced by filter_frame(), and get_video_buffer().
get_video_buffer()
static AVFrame* get_video_buffer (AVFilterLink * link, int w, int h) static
Definition at line 57 of file vf_swapuv.c.
filter_frame()
static int filter_frame (AVFilterLink * link, AVFrame * inpicref) static
Definition at line 64 of file vf_swapuv.c.
is_planar_yuv()
static int is_planar_yuv (const AVPixFmtDescriptor * desc) static
Definition at line 70 of file vf_swapuv.c.
Referenced by query_formats().
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 88 of file vf_swapuv.c.
Variable Documentation
swapuv_options
const AVOption swapuv_options[] static
Initial value:
= {
    { NULL }
}
Definition at line 38 of file vf_swapuv.c.
swapuv_inputs
const AVFilterPad swapuv_inputs[] static
Initial value:
= {
    {
        .name             = "default",
        .type             = AVMEDIA_TYPE_VIDEO,
        .get_video_buffer = get_video_buffer,
        .filter_frame     = filter_frame,
    },
    { NULL }
}
Definition at line 102 of file vf_swapuv.c.
swapuv_outputs
const AVFilterPad swapuv_outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_VIDEO,
    },
    { NULL }
}
Definition at line 112 of file vf_swapuv.c.
ff_vf_swapuv
AVFilter ff_vf_swapuv
Initial value:
= {
    .name          = "swapuv",
    .description   = NULL_IF_CONFIG_SMALL("Swap U and V components."),
    .query_formats = query_formats,
    .priv_size     = sizeof(SwapUVContext),
    .priv_class    = &swapuv_class,
    .inputs        = swapuv_inputs,
    .outputs       = swapuv_outputs,
    .flags         = AVFILTER_FLAG_SUPPORT_TIMELINE_GENERIC,
}
Definition at line 120 of file vf_swapuv.c.