FFmpeg: libavfilter/vf_w3fdif.c File Reference
vf_w3fdif.c File Reference
#include "libavutil/common.h"
#include "libavutil/imgutils.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
#include "w3fdif.h"
Data Structures
struct W3FDIFContext
struct ThreadData
Macros
#define OFFSET(x) offsetof(W3FDIFContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
#define CONST(name, help, val, unit) { name, help, 0, AV_OPT_TYPE_CONST, {.i64=val}, 0, 0, FLAGS, unit }
Functions
AVFILTER_DEFINE_CLASS (w3fdif)
static int query_formats (AVFilterContext *ctx)
static void filter_simple_low (int32_t *work_line, uint8_t *in_lines_cur[2], const int16_t *coef, int linesize)
static void filter_complex_low (int32_t *work_line, uint8_t *in_lines_cur[4], const int16_t *coef, int linesize)
static void filter_simple_high (int32_t *work_line, uint8_t *in_lines_cur[3], uint8_t *in_lines_adj[3], const int16_t *coef, int linesize)
static void filter_complex_high (int32_t *work_line, uint8_t *in_lines_cur[5], uint8_t *in_lines_adj[5], const int16_t *coef, int linesize)
static void filter_scale (uint8_t *out_pixel, const int32_t *work_pixel, int linesize, int max)
static void filter16_simple_low (int32_t *work_line, uint8_t *in_lines_cur8[2], const int16_t *coef, int linesize)
static void filter16_complex_low (int32_t *work_line, uint8_t *in_lines_cur8[4], const int16_t *coef, int linesize)
static void filter16_simple_high (int32_t *work_line, uint8_t *in_lines_cur8[3], uint8_t *in_lines_adj8[3], const int16_t *coef, int linesize)
static void filter16_complex_high (int32_t *work_line, uint8_t *in_lines_cur8[5], uint8_t *in_lines_adj8[5], const int16_t *coef, int linesize)
static void filter16_scale (uint8_t *out_pixel8, const int32_t *work_pixel, int linesize, int max)
static int config_input (AVFilterLink *inlink)
static int config_output (AVFilterLink *outlink)
static int deinterlace_slice (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int filter (AVFilterContext *ctx, int is_second)
static int filter_frame (AVFilterLink *inlink, AVFrame *frame)
static int request_frame (AVFilterLink *outlink)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const AVOption w3fdif_options []
static const int8_t n_coef_lf [2] = { 2, 4 }
static const int16_t coef_lf [2][4]
static const int8_t n_coef_hf [2] = { 3, 5 }
static const int16_t coef_hf [2][5]
static const AVFilterPad w3fdif_inputs []
static const AVFilterPad w3fdif_outputs []
AVFilter ff_vf_w3fdif
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(W3FDIFContext, x)
Definition at line 51 of file vf_w3fdif.c.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 52 of file vf_w3fdif.c.
CONST
#define CONST (name, help, val, unit) { name, help, 0, AV_OPT_TYPE_CONST, {.i64=val}, 0, 0, FLAGS, unit }
Definition at line 53 of file vf_w3fdif.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (w3fdif)
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 67 of file vf_w3fdif.c.
filter_simple_low()
static void filter_simple_low (int32_t * work_line, uint8_t * in_lines_cur[2], const int16_t * coef, int linesize) static
Definition at line 93 of file vf_w3fdif.c.
Referenced by config_input().
filter_complex_low()
static void filter_complex_low (int32_t * work_line, uint8_t * in_lines_cur[4], const int16_t * coef, int linesize) static
Definition at line 105 of file vf_w3fdif.c.
Referenced by config_input().
filter_simple_high()
static void filter_simple_high (int32_t * work_line, uint8_t * in_lines_cur[3], uint8_t * in_lines_adj[3], const int16_t * coef, int linesize) static
Definition at line 119 of file vf_w3fdif.c.
Referenced by config_input().
filter_complex_high()
static void filter_complex_high (int32_t * work_line, uint8_t * in_lines_cur[5], uint8_t * in_lines_adj[5], const int16_t * coef, int linesize) static
Definition at line 136 of file vf_w3fdif.c.
Referenced by config_input().
filter_scale()
static void filter_scale (uint8_t * out_pixel, const int32_t * work_pixel, int linesize, int max) static
Definition at line 157 of file vf_w3fdif.c.
Referenced by config_input().
filter16_simple_low()
static void filter16_simple_low (int32_t * work_line, uint8_t * in_lines_cur8[2], const int16_t * coef, int linesize) static
Definition at line 165 of file vf_w3fdif.c.
Referenced by config_input().
filter16_complex_low()
static void filter16_complex_low (int32_t * work_line, uint8_t * in_lines_cur8[4], const int16_t * coef, int linesize) static
Definition at line 179 of file vf_w3fdif.c.
Referenced by config_input().
filter16_simple_high()
static void filter16_simple_high (int32_t * work_line, uint8_t * in_lines_cur8[3], uint8_t * in_lines_adj8[3], const int16_t * coef, int linesize) static
Definition at line 198 of file vf_w3fdif.c.
Referenced by config_input().
filter16_complex_high()
static void filter16_complex_high (int32_t * work_line, uint8_t * in_lines_cur8[5], uint8_t * in_lines_adj8[5], const int16_t * coef, int linesize) static
Definition at line 222 of file vf_w3fdif.c.
Referenced by config_input().
filter16_scale()
static void filter16_scale (uint8_t * out_pixel8, const int32_t * work_pixel, int linesize, int max) static
Definition at line 254 of file vf_w3fdif.c.
Referenced by config_input().
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 264 of file vf_w3fdif.c.
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 311 of file vf_w3fdif.c.
deinterlace_slice()
static int deinterlace_slice (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 343 of file vf_w3fdif.c.
Referenced by filter().
filter()
static int filter (AVFilterContext * ctx, int is_second) static
Definition at line 448 of file vf_w3fdif.c.
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * frame) static
Definition at line 488 of file vf_w3fdif.c.
Referenced by request_frame().
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 526 of file vf_w3fdif.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 551 of file vf_w3fdif.c.
Variable Documentation
w3fdif_options
const AVOption w3fdif_options[] static
Initial value:
= {
    { "filter", "specify the filter", OFFSET(filter), AV_OPT_TYPE_INT, {.i64=1}, 0, 1, FLAGS, "filter" },
    CONST("simple",  NULL, 0, "filter"),
    CONST("complex", NULL, 1, "filter"),
    { "deint",  "specify which frames to deinterlace", OFFSET(deint), AV_OPT_TYPE_INT, {.i64=0}, 0, 1, FLAGS, "deint" },
    CONST("all",        "deinterlace all frames",                       0, "deint"),
    CONST("interlaced", "only deinterlace frames marked as interlaced", 1, "deint"),
    { NULL }
}
Definition at line 55 of file vf_w3fdif.c.
n_coef_lf
const int8_t n_coef_lf[2] = { 2, 4 } static
Definition at line 331 of file vf_w3fdif.c.
Referenced by deinterlace_slice().
coef_lf
const int16_t coef_lf[2][4] static
Initial value:
= {{ 16384, 16384,     0,    0},
                                      {  -852, 17236, 17236, -852}}
Definition at line 332 of file vf_w3fdif.c.
Referenced by deinterlace_slice().
n_coef_hf
const int8_t n_coef_hf[2] = { 3, 5 } static
Definition at line 334 of file vf_w3fdif.c.
Referenced by deinterlace_slice().
coef_hf
const int16_t coef_hf[2][5] static
Initial value:
= {{ -2048,  4096, -2048,     0,    0},
                                      {  1016, -3801,  5570, -3801, 1016}}
Definition at line 335 of file vf_w3fdif.c.
Referenced by deinterlace_slice().
w3fdif_inputs
const AVFilterPad w3fdif_inputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .filter_frame  = filter_frame,
        .config_props  = config_input,
    },
    { NULL }
}
Definition at line 566 of file vf_w3fdif.c.
w3fdif_outputs
const AVFilterPad w3fdif_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .config_props  = config_output,
        .request_frame = request_frame,
    },
    { NULL }
}
Definition at line 576 of file vf_w3fdif.c.
ff_vf_w3fdif
AVFilter ff_vf_w3fdif
Initial value:
= {
    .name          = "w3fdif",
    .description   = NULL_IF_CONFIG_SMALL("Apply Martin Weston three field deinterlace."),
    .priv_size     = sizeof(W3FDIFContext),
    .priv_class    = &w3fdif_class,
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = w3fdif_inputs,
    .outputs       = w3fdif_outputs,
    .flags         = AVFILTER_FLAG_SUPPORT_TIMELINE_INTERNAL | AVFILTER_FLAG_SLICE_THREADS,
}
Definition at line 586 of file vf_w3fdif.c.