FFmpeg: libavfilter/x86/vf_psnr_init.c File Reference
vf_psnr_init.c File Reference
#include "libavutil/x86/cpu.h"
#include "libavfilter/psnr.h"
Functions
uint64_t ff_sse_line_8bit_sse2 (const uint8_t *buf, const uint8_t *ref, int w)
uint64_t ff_sse_line_16bit_sse2 (const uint8_t *buf, const uint8_t *ref, int w)
void ff_psnr_init_x86 (PSNRDSPContext *dsp, int bpp)
Function Documentation
ff_sse_line_8bit_sse2()
uint64_t ff_sse_line_8bit_sse2 (const uint8_t * buf, const uint8_t * ref, int w)
Referenced by ff_psnr_init_x86().
ff_sse_line_16bit_sse2()
uint64_t ff_sse_line_16bit_sse2 (const uint8_t * buf, const uint8_t * ref, int w)
Referenced by ff_psnr_init_x86().
ff_psnr_init_x86()
void ff_psnr_init_x86 (PSNRDSPContext * dsp, int bpp)
Definition at line 28 of file vf_psnr_init.c.
Referenced by config_input_ref().