FFmpeg: libavfilter/vf_tile.c File Reference
vf_tile.c File Reference
tile video filter
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "avfilter.h"
#include "drawutils.h"
#include "formats.h"
#include "video.h"
#include "internal.h"
Data Structures
struct TileContext
Macros
#define REASONABLE_SIZE 1024
#define OFFSET(x) offsetof(TileContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Functions
AVFILTER_DEFINE_CLASS (tile)
static av_cold int init (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static int config_props (AVFilterLink *outlink)
static void get_current_tile_pos (AVFilterContext *ctx, unsigned *x, unsigned *y)
static void draw_blank_frame (AVFilterContext *ctx, AVFrame *out_buf)
static int end_last_frame (AVFilterContext *ctx)
static int filter_frame (AVFilterLink *inlink, AVFrame *picref)
static int request_frame (AVFilterLink *outlink)
Variables
static const AVOption tile_options []
static const AVFilterPad tile_inputs []
static const AVFilterPad tile_outputs []
AVFilter ff_vf_tile
Detailed Description
tile video filter
Definition in file vf_tile.c.
Macro Definition Documentation
REASONABLE_SIZE
#define REASONABLE_SIZE 1024
Definition at line 47 of file vf_tile.c.
Referenced by init().
OFFSET
#define OFFSET (x) offsetof(TileContext, x)
Definition at line 49 of file vf_tile.c.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 50 of file vf_tile.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (tile)
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 67 of file vf_tile.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 88 of file vf_tile.c.
config_props()
static int config_props (AVFilterLink * outlink) static
Definition at line 93 of file vf_tile.c.
get_current_tile_pos()
static void get_current_tile_pos (AVFilterContext * ctx, unsigned * x, unsigned * y) static
Definition at line 122 of file vf_tile.c.
Referenced by draw_blank_frame(), and filter_frame().
draw_blank_frame()
static void draw_blank_frame (AVFilterContext * ctx, AVFrame * out_buf) static
Definition at line 133 of file vf_tile.c.
Referenced by end_last_frame().
end_last_frame()
static int end_last_frame (AVFilterContext * ctx) static
Definition at line 145 of file vf_tile.c.
Referenced by filter_frame(), and request_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * picref) static
Definition at line 163 of file vf_tile.c.
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 201 of file vf_tile.c.
Variable Documentation
tile_options
const AVOption tile_options[] static
Initial value:
= {
    { "layout", "set grid size", OFFSET(w), AV_OPT_TYPE_IMAGE_SIZE,
        {.str = "6x5"}, 0, 0, FLAGS },
    { "nb_frames", "set maximum number of frame to render", OFFSET(nb_frames),
        AV_OPT_TYPE_INT, {.i64 = 0}, 0, INT_MAX, FLAGS },
    { "margin",  "set outer border margin in pixels",    OFFSET(margin),
        AV_OPT_TYPE_INT, {.i64 = 0}, 0, 1024, FLAGS },
    { "padding", "set inner border thickness in pixels", OFFSET(padding),
        AV_OPT_TYPE_INT, {.i64 = 0}, 0, 1024, FLAGS },
    { "color",   "set the color of the unused area", OFFSET(rgba_color), AV_OPT_TYPE_COLOR, {.str = "black"}, .flags = FLAGS },
    { NULL }
}
Definition at line 52 of file vf_tile.c.
tile_inputs
const AVFilterPad tile_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 214 of file vf_tile.c.
tile_outputs
const AVFilterPad tile_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .config_props  = config_props,
        .request_frame = request_frame,
    },
    { NULL }
}
Definition at line 223 of file vf_tile.c.
ff_vf_tile
AVFilter ff_vf_tile
Initial value:
= {
    .name          = "tile",
    .description   = NULL_IF_CONFIG_SMALL("Tile several successive frames together."),
    .init          = init,
    .query_formats = query_formats,
    .priv_size     = sizeof(TileContext),
    .inputs        = tile_inputs,
    .outputs       = tile_outputs,
    .priv_class    = &tile_class,
}
Definition at line 233 of file vf_tile.c.