FFmpeg: libavfilter/vf_neighbor.c File Reference
vf_neighbor.c File Reference
#include "libavutil/imgutils.h"
#include "libavutil/pixdesc.h"
#include "libavutil/opt.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
Data Structures
struct NContext
Macros
#define OFFSET(x) offsetof(NContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
#define DEFINE_NEIGHBOR_FILTER(name_, description_)
Functions
static int query_formats (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
static void line_copy8 (uint8_t *line, const uint8_t *srcp, int width, int mergin)
static void erosion (uint8_t *dst, const uint8_t *p1, int width, int threshold, const uint8_t *coordinates[], int coord)
static void dilation (uint8_t *dst, const uint8_t *p1, int width, int threshold, const uint8_t *coordinates[], int coord)
static void deflate (uint8_t *dst, const uint8_t *p1, int width, int threshold, const uint8_t *coordinates[], int coord)
static void inflate (uint8_t *dst, const uint8_t *p1, int width, int threshold, const uint8_t *coordinates[], int coord)
static int config_input (AVFilterLink *inlink)
static int filter_frame (AVFilterLink *inlink, AVFrame *in)
Variables
static const AVFilterPad neighbor_inputs []
static const AVFilterPad neighbor_outputs []
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(NContext, x)
Definition at line 249 of file vf_neighbor.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 250 of file vf_neighbor.c.
DEFINE_NEIGHBOR_FILTER
#define DEFINE_NEIGHBOR_FILTER (name_, description_)
Value:
AVFILTER_DEFINE_CLASS(name_);                                \
                                                             \
AVFilter ff_vf_##name_ = {                                   \
    .name          = #name_,                                 \
    .description   = NULL_IF_CONFIG_SMALL(description_),     \
    .priv_size     = sizeof(NContext),                       \
    .priv_class    = &name_##_class,                         \
    .uninit        = uninit,                                 \
    .query_formats = query_formats,                          \
    .inputs        = neighbor_inputs,                        \
    .outputs       = neighbor_outputs,                       \
    .flags         = AVFILTER_FLAG_SUPPORT_TIMELINE_GENERIC, \
}
Definition at line 252 of file vf_neighbor.c.
Function Documentation
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 43 of file vf_neighbor.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 55 of file vf_neighbor.c.
line_copy8()
static void line_copy8 (uint8_t * line, const uint8_t * srcp, int width, int mergin) inline static
Definition at line 62 of file vf_neighbor.c.
Referenced by filter_frame().
erosion()
static void erosion (uint8_t * dst, const uint8_t * p1, int width, int threshold, const uint8_t * coordinates[], int coord) static
Definition at line 74 of file vf_neighbor.c.
Referenced by avfilter_register_all(), and config_input().
dilation()
static void dilation (uint8_t * dst, const uint8_t * p1, int width, int threshold, const uint8_t * coordinates[], int coord) static
Definition at line 94 of file vf_neighbor.c.
Referenced by avfilter_register_all(), and config_input().
deflate()
static void deflate (uint8_t * dst, const uint8_t * p1, int width, int threshold, const uint8_t * coordinates[], int coord) static
Definition at line 114 of file vf_neighbor.c.
Referenced by avfilter_register_all(), config_input(), encode_frame(), encode_zlibprime(), flashsv2_prime(), and png_write_row().
inflate()
static void inflate (uint8_t * dst, const uint8_t * p1, int width, int threshold, const uint8_t * coordinates[], int coord) static
Definition at line 129 of file vf_neighbor.c.
Referenced by avfilter_register_all(), config_input(), decode_frame(), decode_zbuf(), flashsv2_prime(), flashsv_decode_block(), http_buf_read(), main(), matroska_decode_buffer(), mszh_decomp(), png_decode_idat(), rtmp_calc_swf_verification(), swf_probe(), unpack_yuv(), and zerocodec_decode_frame().
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 144 of file vf_neighbor.c.
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 174 of file vf_neighbor.c.
Variable Documentation
neighbor_inputs
const AVFilterPad neighbor_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
        .config_props = config_input,
    },
    { NULL }
}
Definition at line 231 of file vf_neighbor.c.
neighbor_outputs
const AVFilterPad neighbor_outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_VIDEO,
    },
    { NULL }
}
Definition at line 241 of file vf_neighbor.c.