FFmpeg: libavfilter/vf_maskedmerge.c File Reference
vf_maskedmerge.c File Reference
#include "libavutil/imgutils.h"
#include "libavutil/pixdesc.h"
#include "libavutil/opt.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
#include "maskedmerge.h"
Macros
#define OFFSET(x) offsetof(MaskedMergeContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Functions
AVFILTER_DEFINE_CLASS (maskedmerge)
static int query_formats (AVFilterContext *ctx)
static int process_frame (FFFrameSync *fs)
static void maskedmerge8 (const uint8_t *bsrc, const uint8_t *osrc, const uint8_t *msrc, uint8_t *dst, ptrdiff_t blinesize, ptrdiff_t olinesize, ptrdiff_t mlinesize, ptrdiff_t dlinesize, int w, int h, int half, int shift)
static void maskedmerge16 (const uint8_t *bbsrc, const uint8_t *oosrc, const uint8_t *mmsrc, uint8_t *ddst, ptrdiff_t blinesize, ptrdiff_t olinesize, ptrdiff_t mlinesize, ptrdiff_t dlinesize, int w, int h, int half, int shift)
static int config_input (AVFilterLink *inlink)
static int config_output (AVFilterLink *outlink)
static int filter_frame (AVFilterLink *inlink, AVFrame *buf)
static int request_frame (AVFilterLink *outlink)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const AVOption maskedmerge_options []
static const AVFilterPad maskedmerge_inputs []
static const AVFilterPad maskedmerge_outputs []
AVFilter ff_vf_maskedmerge
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(MaskedMergeContext, x)
Definition at line 30 of file vf_maskedmerge.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 31 of file vf_maskedmerge.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (maskedmerge)
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 40 of file vf_maskedmerge.c.
process_frame()
static int process_frame (FFFrameSync * fs) static
Definition at line 66 of file vf_maskedmerge.c.
Referenced by config_output().
maskedmerge8()
static void maskedmerge8 (const uint8_t * bsrc, const uint8_t * osrc, const uint8_t * msrc, uint8_t * dst, ptrdiff_t blinesize, ptrdiff_t olinesize, ptrdiff_t mlinesize, ptrdiff_t dlinesize, int w, int h, int half, int shift) static
Definition at line 111 of file vf_maskedmerge.c.
Referenced by config_input().
maskedmerge16()
static void maskedmerge16 (const uint8_t * bbsrc, const uint8_t * oosrc, const uint8_t * mmsrc, uint8_t * ddst, ptrdiff_t blinesize, ptrdiff_t olinesize, ptrdiff_t mlinesize, ptrdiff_t dlinesize, int w, int h, int half, int shift) static
Definition at line 132 of file vf_maskedmerge.c.
Referenced by config_input().
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 157 of file vf_maskedmerge.c.
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 187 of file vf_maskedmerge.c.
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * buf) static
Definition at line 254 of file vf_maskedmerge.c.
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 260 of file vf_maskedmerge.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 266 of file vf_maskedmerge.c.
Variable Documentation
maskedmerge_options
const AVOption maskedmerge_options[] static
Initial value:
= {
    { "planes", "set planes", OFFSET(planes), AV_OPT_TYPE_INT, {.i64=0xF}, 0, 0xF, FLAGS },
    { NULL }
}
Definition at line 33 of file vf_maskedmerge.c.
maskedmerge_inputs
const AVFilterPad maskedmerge_inputs[] static
Initial value:
= {
    {
        .name         = "base",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
        .config_props = config_input,
    },
    {
        .name         = "overlay",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
    },
    {
        .name         = "mask",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 273 of file vf_maskedmerge.c.
maskedmerge_outputs
const AVFilterPad maskedmerge_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .config_props  = config_output,
        .request_frame = request_frame,
    },
    { NULL }
}
Definition at line 293 of file vf_maskedmerge.c.
ff_vf_maskedmerge
AVFilter ff_vf_maskedmerge
Initial value:
= {
    .name          = "maskedmerge",
    .description   = NULL_IF_CONFIG_SMALL("Merge first stream with second stream using third stream as mask."),
    .priv_size     = sizeof(MaskedMergeContext),
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = maskedmerge_inputs,
    .outputs       = maskedmerge_outputs,
    .priv_class    = &maskedmerge_class,
    .flags         = AVFILTER_FLAG_SUPPORT_TIMELINE_INTERNAL,
}
Definition at line 303 of file vf_maskedmerge.c.