FFmpeg: libavfilter/vf_scale_npp.c File Reference
vf_scale_npp.c File Reference
scale video filter
#include <nppi.h>
#include <stdio.h>
#include <string.h>
#include "libavutil/avstring.h"
#include "libavutil/common.h"
#include "libavutil/eval.h"
#include "libavutil/hwcontext.h"
#include "libavutil/hwcontext_cuda_internal.h"
#include "libavutil/internal.h"
#include "libavutil/mathematics.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
Data Structures
struct NPPScaleStageContext
struct NPPScaleContext
Macros
#define OFFSET(x) offsetof(NPPScaleContext, x)
#define FLAGS (AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM)
Enumerations
enum var_name {
VAR_CH, VAR_N, VAR_NB_IN_CHANNELS, VAR_NB_OUT_CHANNELS,
VAR_T, VAR_S, VAR_VARS_NB, VAR_VALUE1,
VAR_VALUE2, VAR_VARS_NB, VAR_TB, VAR_PTS,
VAR_START_PTS, VAR_PREV_PTS, VAR_PREV_SELECTED_PTS, VAR_T,
VAR_START_T, VAR_PREV_T, VAR_PREV_SELECTED_T, VAR_PICT_TYPE,
VAR_I, VAR_P, VAR_B, VAR_S,
VAR_SI, VAR_SP, VAR_BI, VAR_PICT_TYPE_I,
VAR_PICT_TYPE_P, VAR_PICT_TYPE_B, VAR_PICT_TYPE_S, VAR_PICT_TYPE_SI,
VAR_PICT_TYPE_SP, VAR_PICT_TYPE_BI, VAR_INTERLACE_TYPE, VAR_INTERLACE_TYPE_P,
VAR_INTERLACE_TYPE_T, VAR_INTERLACE_TYPE_B, VAR_CONSUMED_SAMPLES_N, VAR_SAMPLES_N,
VAR_SAMPLE_RATE, VAR_N, VAR_SELECTED_N, VAR_PREV_SELECTED_N,
VAR_KEY, VAR_POS, VAR_SCENE, VAR_CONCATDEC_SELECT,
VAR_VARS_NB, VAR_FRAME_RATE, VAR_INTERLACED, VAR_N,
VAR_NB_CONSUMED_SAMPLES, VAR_NB_SAMPLES, VAR_POS, VAR_PREV_INPTS,
VAR_PREV_INT, VAR_PREV_OUTPTS, VAR_PREV_OUTT, VAR_PTS,
VAR_SAMPLE_RATE, VAR_STARTPTS, VAR_STARTT, VAR_T,
VAR_TB, VAR_RTCTIME, VAR_RTCSTART, VAR_S,
VAR_SR, VAR_VARS_NB, VAR_AVTB, VAR_INTB,
VAR_SR, VAR_VARS_NB, VAR_W, VAR_H,
VAR_A, VAR_DAR, VAR_SAR, VAR_HSUB,
VAR_VSUB, VARS_NB, VAR_W, VAR_H,
VAR_CW, VAR_CH, VAR_HSUB, VAR_VSUB,
VARS_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_A, VAR_SAR, VAR_DAR,
VAR_HSUB, VAR_VSUB, VAR_X, VAR_Y,
VAR_N, VAR_POS, VAR_T, VAR_VARS_NB,
VAR_DAR, VAR_HSUB, VAR_VSUB, VAR_IN_H,
VAR_IH, VAR_IN_W, VAR_IW, VAR_SAR,
VAR_X, VAR_Y, VAR_H, VAR_W,
VAR_T, VAR_MAX, VARS_NB, VAR_DAR,
VAR_HSUB, VAR_VSUB, VAR_LINE_H, VAR_LH,
VAR_MAIN_H, VAR_h, VAR_H, VAR_MAIN_W,
VAR_w, VAR_W, VAR_MAX_GLYPH_A, VAR_ASCENT,
VAR_MAX_GLYPH_D, VAR_DESCENT, VAR_MAX_GLYPH_H, VAR_MAX_GLYPH_W,
VAR_N, VAR_SAR, VAR_T, VAR_TEXT_H,
VAR_TH, VAR_TEXT_W, VAR_TW, VAR_X,
VAR_Y, VAR_PICT_TYPE, VAR_VARS_NB, VAR_N,
VAR_POS, VAR_R, VAR_T, VAR_NB,
VAR_N, VAR_PTS, VAR_R, VAR_T,
VAR_TB, VAR_NB, VAR_W, VAR_H,
VAR_VAL, VAR_MAXVAL, VAR_MINVAL, VAR_NEGVAL,
VAR_CLIPVAL, VAR_VARS_NB, VAR_W, VAR_H,
VAR_X, VAR_Y, VAR_BITDEPTHX, VAR_BITDEPTHY,
VAR_VARS_NB, VAR_MAIN_W, VAR_MW, VAR_MAIN_H,
VAR_MH, VAR_OVERLAY_W, VAR_OW, VAR_OVERLAY_H,
VAR_OH, VAR_HSUB, VAR_VSUB, VAR_X,
VAR_Y, VAR_N, VAR_POS, VAR_T,
VAR_VARS_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_X, VAR_Y, VAR_A,
VAR_SAR, VAR_DAR, VAR_HSUB, VAR_VSUB,
VARS_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_HSUB, VAR_VSUB, VAR_N,
VAR_T, VAR_VARS_NB, VAR_IN_W, VAR_IW,
VAR_IN_H, VAR_IH, VAR_OUT_W, VAR_OW,
VAR_OUT_H, VAR_OH, VAR_A, VAR_SAR,
VAR_DAR, VAR_HSUB, VAR_VSUB, VAR_OHSUB,
VAR_OVSUB, VARS_NB, VAR_PI, VAR_PHI,
VAR_E, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_A, VAR_DAR, VAR_SAR,
VARS_NB, VAR_W, VAR_H, VAR_N,
VAR_PTS, VAR_R, VAR_T, VAR_TB,
VAR_NB, VAR_IN_W, VAR_IW, VAR_IN_H,
VAR_IH, VAR_OUT_W, VAR_OW, VAR_OUT_H,
VAR_OH, VAR_IN, VAR_ON, VAR_DURATION,
VAR_PDURATION, VAR_TIME, VAR_FRAME, VAR_ZOOM,
VAR_PZOOM, VAR_X, VAR_PX, VAR_Y,
VAR_PY, VAR_A, VAR_SAR, VAR_DAR,
VAR_HSUB, VAR_VSUB, VARS_NB, VAR_IN_W,
VAR_IW, VAR_IN_H, VAR_IH, VAR_OUT_W,
VAR_OW, VAR_OUT_H, VAR_OH, VAR_A,
VAR_SAR, VAR_DAR, VAR_HSUB, VAR_VSUB,
VAR_OHSUB, VAR_OVSUB, VARS_NB, VAR_X,
VAR_Y, VAR_W, VAR_H, VAR_TIME,
VAR_SPEED, VAR_TEMPO, VAR_ORDER, VAR_PATTERN,
VAR_ROW, VAR_VARS_NB
}
enum ScaleStage { STAGE_DEINTERLEAVE, STAGE_RESIZE, STAGE_INTERLEAVE, STAGE_NB }
Functions
static int nppscale_init (AVFilterContext *ctx)
static void nppscale_uninit (AVFilterContext *ctx)
static int nppscale_query_formats (AVFilterContext *ctx)
static int init_stage (NPPScaleStageContext *stage, AVBufferRef *device_ctx)
static int format_is_supported (enum AVPixelFormat fmt)
static enum AVPixelFormat get_deinterleaved_format (enum AVPixelFormat fmt)
static int init_processing_chain (AVFilterContext *ctx, int in_width, int in_height, int out_width, int out_height)
static int nppscale_config_props (AVFilterLink *outlink)
static int nppscale_deinterleave (AVFilterContext *ctx, NPPScaleStageContext *stage, AVFrame *out, AVFrame *in)
static int nppscale_resize (AVFilterContext *ctx, NPPScaleStageContext *stage, AVFrame *out, AVFrame *in)
static int nppscale_interleave (AVFilterContext *ctx, NPPScaleStageContext *stage, AVFrame *out, AVFrame *in)
static int nppscale_scale (AVFilterContext *ctx, AVFrame *out, AVFrame *in)
static int nppscale_filter_frame (AVFilterLink *link, AVFrame *in)
Variables
static enum AVPixelFormat supported_formats []
static enum AVPixelFormat deinterleaved_formats [][2]
static const char *const var_names []
static int(*const nppscale_process [])(AVFilterContext *ctx, NPPScaleStageContext *stage, AVFrame *out, AVFrame *in)
static const AVOption options []
static const AVClass nppscale_class
static const AVFilterPad nppscale_inputs []
static const AVFilterPad nppscale_outputs []
AVFilter ff_vf_scale_npp
Detailed Description
scale video filter
Definition in file vf_scale_npp.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(NPPScaleContext, x)
Definition at line 612 of file vf_scale_npp.c.
FLAGS
#define FLAGS (AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM)
Definition at line 613 of file vf_scale_npp.c.
Enumeration Type Documentation
var_name
enum var_name
Enumerator
VAR_CH
VAR_N
VAR_NB_IN_CHANNELS
VAR_NB_OUT_CHANNELS
VAR_T
VAR_S
VAR_VARS_NB
VAR_VALUE1
VAR_VALUE2
VAR_VARS_NB
VAR_TB
VAR_PTS
VAR_START_PTS
VAR_PREV_PTS
VAR_PREV_SELECTED_PTS
VAR_T
VAR_START_T
VAR_PREV_T
VAR_PREV_SELECTED_T
VAR_PICT_TYPE
VAR_I
VAR_P
VAR_B
VAR_S
VAR_SI
VAR_SP
VAR_BI
VAR_PICT_TYPE_I
VAR_PICT_TYPE_P
VAR_PICT_TYPE_B
VAR_PICT_TYPE_S
VAR_PICT_TYPE_SI
VAR_PICT_TYPE_SP
VAR_PICT_TYPE_BI
VAR_INTERLACE_TYPE
VAR_INTERLACE_TYPE_P
VAR_INTERLACE_TYPE_T
VAR_INTERLACE_TYPE_B
VAR_CONSUMED_SAMPLES_N
VAR_SAMPLES_N
VAR_SAMPLE_RATE
VAR_N
VAR_SELECTED_N
VAR_PREV_SELECTED_N
VAR_KEY
VAR_POS
VAR_SCENE
VAR_CONCATDEC_SELECT
VAR_VARS_NB
VAR_FRAME_RATE
VAR_INTERLACED
VAR_N
VAR_NB_CONSUMED_SAMPLES
VAR_NB_SAMPLES
VAR_POS
VAR_PREV_INPTS
VAR_PREV_INT
VAR_PREV_OUTPTS
VAR_PREV_OUTT
VAR_PTS
VAR_SAMPLE_RATE
VAR_STARTPTS
VAR_STARTT
VAR_T
VAR_TB
VAR_RTCTIME
VAR_RTCSTART
VAR_S
VAR_SR
VAR_VARS_NB
VAR_AVTB
VAR_INTB
VAR_SR
VAR_VARS_NB
VAR_W
VAR_H
VAR_A
VAR_DAR
VAR_SAR
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_W
VAR_H
VAR_CW
VAR_CH
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_X
VAR_Y
VAR_N
VAR_POS
VAR_T
VAR_VARS_NB
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_IN_H
VAR_IH
VAR_IN_W
VAR_IW
VAR_SAR
VAR_X
VAR_Y
VAR_H
VAR_W
VAR_T
VAR_MAX
VARS_NB
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_LINE_H
VAR_LH
VAR_MAIN_H
VAR_h
VAR_H
VAR_MAIN_W
VAR_w
VAR_W
VAR_MAX_GLYPH_A
VAR_ASCENT
VAR_MAX_GLYPH_D
VAR_DESCENT
VAR_MAX_GLYPH_H
VAR_MAX_GLYPH_W
VAR_N
VAR_SAR
VAR_T
VAR_TEXT_H
VAR_TH
VAR_TEXT_W
VAR_TW
VAR_X
VAR_Y
VAR_PICT_TYPE
VAR_VARS_NB
VAR_N
VAR_POS
VAR_R
VAR_T
VAR_NB
VAR_N
VAR_PTS
VAR_R
VAR_T
VAR_TB
VAR_NB
VAR_W
VAR_H
VAR_VAL
VAR_MAXVAL
VAR_MINVAL
VAR_NEGVAL
VAR_CLIPVAL
VAR_VARS_NB
VAR_W
VAR_H
VAR_X
VAR_Y
VAR_BITDEPTHX
VAR_BITDEPTHY
VAR_VARS_NB
VAR_MAIN_W
VAR_MW
VAR_MAIN_H
VAR_MH
VAR_OVERLAY_W
VAR_OW
VAR_OVERLAY_H
VAR_OH
VAR_HSUB
VAR_VSUB
VAR_X
VAR_Y
VAR_N
VAR_POS
VAR_T
VAR_VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_X
VAR_Y
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_HSUB
VAR_VSUB
VAR_N
VAR_T
VAR_VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_OHSUB
VAR_OVSUB
VARS_NB
VAR_PI
VAR_PHI
VAR_E
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_DAR
VAR_SAR
VARS_NB
VAR_W
VAR_H
VAR_N
VAR_PTS
VAR_R
VAR_T
VAR_TB
VAR_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_IN
VAR_ON
VAR_DURATION
VAR_PDURATION
VAR_TIME
VAR_FRAME
VAR_ZOOM
VAR_PZOOM
VAR_X
VAR_PX
VAR_Y
VAR_PY
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VARS_NB
VAR_IN_W
VAR_IW
VAR_IN_H
VAR_IH
VAR_OUT_W
VAR_OW
VAR_OUT_H
VAR_OH
VAR_A
VAR_SAR
VAR_DAR
VAR_HSUB
VAR_VSUB
VAR_OHSUB
VAR_OVSUB
VARS_NB
VAR_X
VAR_Y
VAR_W
VAR_H
VAR_TIME
VAR_SPEED
VAR_TEMPO
VAR_ORDER
VAR_PATTERN
VAR_ROW
VAR_VARS_NB
Definition at line 66 of file vf_scale_npp.c.
ScaleStage
enum ScaleStage
Enumerator
STAGE_DEINTERLEAVE
STAGE_RESIZE
STAGE_INTERLEAVE
STAGE_NB
Definition at line 79 of file vf_scale_npp.c.
Function Documentation
nppscale_init()
static int nppscale_init (AVFilterContext * ctx) static
Definition at line 128 of file vf_scale_npp.c.
nppscale_uninit()
static void nppscale_uninit (AVFilterContext * ctx) static
Definition at line 155 of file vf_scale_npp.c.
nppscale_query_formats()
static int nppscale_query_formats (AVFilterContext * ctx) static
Definition at line 167 of file vf_scale_npp.c.
init_stage()
static int init_stage (NPPScaleStageContext * stage, AVBufferRef * device_ctx) static
Definition at line 177 of file vf_scale_npp.c.
Referenced by init_processing_chain().
format_is_supported()
static int format_is_supported (enum AVPixelFormat fmt) static
Definition at line 229 of file vf_scale_npp.c.
Referenced by init_processing_chain().
get_deinterleaved_format()
static enum AVPixelFormat get_deinterleaved_format (enum AVPixelFormat fmt) static
Definition at line 239 of file vf_scale_npp.c.
Referenced by init_processing_chain().
init_processing_chain()
static int init_processing_chain (AVFilterContext * ctx, int in_width, int in_height, int out_width, int out_height) static
Definition at line 253 of file vf_scale_npp.c.
Referenced by nppscale_config_props().
nppscale_config_props()
static int nppscale_config_props (AVFilterLink * outlink) static
Definition at line 358 of file vf_scale_npp.c.
nppscale_deinterleave()
static int nppscale_deinterleave (AVFilterContext * ctx, NPPScaleStageContext * stage, AVFrame * out, AVFrame * in) static
Definition at line 447 of file vf_scale_npp.c.
nppscale_resize()
static int nppscale_resize (AVFilterContext * ctx, NPPScaleStageContext * stage, AVFrame * out, AVFrame * in) static
Definition at line 471 of file vf_scale_npp.c.
nppscale_interleave()
static int nppscale_interleave (AVFilterContext * ctx, NPPScaleStageContext * stage, AVFrame * out, AVFrame * in) static
Definition at line 499 of file vf_scale_npp.c.
nppscale_scale()
static int nppscale_scale (AVFilterContext * ctx, AVFrame * out, AVFrame * in) static
Definition at line 531 of file vf_scale_npp.c.
Referenced by nppscale_filter_frame().
nppscale_filter_frame()
static int nppscale_filter_frame (AVFilterLink * link, AVFrame * in) static
Definition at line 565 of file vf_scale_npp.c.
Variable Documentation
supported_formats
enum AVPixelFormat supported_formats[] static
Initial value:
= {
    AV_PIX_FMT_YUV420P,
    AV_PIX_FMT_NV12,
    AV_PIX_FMT_YUV444P,
}
Definition at line 43 of file vf_scale_npp.c.
Referenced by format_is_supported().
deinterleaved_formats
enum AVPixelFormat deinterleaved_formats[][2] static
Initial value:
= {
    { AV_PIX_FMT_NV12, AV_PIX_FMT_YUV420P },
}
Definition at line 49 of file vf_scale_npp.c.
Referenced by get_deinterleaved_format().
var_names
const char* const var_names[] static
Initial value:
= {
    "PI",
    "PHI",
    "E",
    "in_w",   "iw",
    "in_h",   "ih",
    "out_w",  "ow",
    "out_h",  "oh",
    "a", "dar",
    "sar",
    NULL
}
Definition at line 53 of file vf_scale_npp.c.
Referenced by nppscale_config_props().
nppscale_process
int(*const nppscale_process[])(AVFilterContext *ctx, NPPScaleStageContext *stage, AVFrame *out, AVFrame *in) static
Initial value:
= {
    [STAGE_DEINTERLEAVE] = nppscale_deinterleave,
    [STAGE_RESIZE]       = nppscale_resize,
    [STAGE_INTERLEAVE]   = nppscale_interleave,
}
Definition at line 524 of file vf_scale_npp.c.
Referenced by nppscale_scale().
options
const AVOption options[] static
Initial value:
= {
    { "w",      "Output video width",  OFFSET(w_expr),     AV_OPT_TYPE_STRING, { .str = "iw"   }, .flags = FLAGS },
    { "h",      "Output video height", OFFSET(h_expr),     AV_OPT_TYPE_STRING, { .str = "ih"   }, .flags = FLAGS },
    { "format", "Output pixel format", OFFSET(format_str), AV_OPT_TYPE_STRING, { .str = "same" }, .flags = FLAGS },
    { "interp_algo", "Interpolation algorithm used for resizing", OFFSET(interp_algo), AV_OPT_TYPE_INT, { .i64 = NPPI_INTER_CUBIC }, 0, INT_MAX, FLAGS, "interp_algo" },
        { "nn",                 "nearest neighbour",                 0, AV_OPT_TYPE_CONST, { .i64 = NPPI_INTER_NN                 }, 0, 0, FLAGS, "interp_algo" },
        { "linear",             "linear",                            0, AV_OPT_TYPE_CONST, { .i64 = NPPI_INTER_LINEAR             }, 0, 0, FLAGS, "interp_algo" },
        { "cubic",              "cubic",                             0, AV_OPT_TYPE_CONST, { .i64 = NPPI_INTER_CUBIC              }, 0, 0, FLAGS, "interp_algo" },
        { "cubic2p_bspline",    "2-parameter cubic (B=1, C=0)",      0, AV_OPT_TYPE_CONST, { .i64 = NPPI_INTER_CUBIC2P_BSPLINE    }, 0, 0, FLAGS, "interp_algo" },
        { "cubic2p_catmullrom", "2-parameter cubic (B=0, C=1/2)",    0, AV_OPT_TYPE_CONST, { .i64 = NPPI_INTER_CUBIC2P_CATMULLROM }, 0, 0, FLAGS, "interp_algo" },
        { "cubic2p_b05c03",     "2-parameter cubic (B=1/2, C=3/10)", 0, AV_OPT_TYPE_CONST, { .i64 = NPPI_INTER_CUBIC2P_B05C03     }, 0, 0, FLAGS, "interp_algo" },
        { "super",              "supersampling",                     0, AV_OPT_TYPE_CONST, { .i64 = NPPI_INTER_SUPER              }, 0, 0, FLAGS, "interp_algo" },
        { "lanczos",            "Lanczos",                           0, AV_OPT_TYPE_CONST, { .i64 = NPPI_INTER_LANCZOS            }, 0, 0, FLAGS, "interp_algo" },
    { NULL },
}
Definition at line 614 of file vf_scale_npp.c.
nppscale_class
const AVClass nppscale_class static
Initial value:
= {
    .class_name = "nppscale",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 631 of file vf_scale_npp.c.
nppscale_inputs
const AVFilterPad nppscale_inputs[] static
Initial value:
= {
    {
        .name        = "default",
        .type        = AVMEDIA_TYPE_VIDEO,
        .filter_frame = nppscale_filter_frame,
    },
    { NULL }
}
Definition at line 638 of file vf_scale_npp.c.
nppscale_outputs
const AVFilterPad nppscale_outputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .config_props = nppscale_config_props,
    },
    { NULL }
}
Definition at line 647 of file vf_scale_npp.c.
ff_vf_scale_npp
AVFilter ff_vf_scale_npp
Initial value:
= {
    .name      = "scale_npp",
    .description = NULL_IF_CONFIG_SMALL("NVIDIA Performance Primitives video "
                                        "scaling and format conversion"),
    .init          = nppscale_init,
    .uninit        = nppscale_uninit,
    .query_formats = nppscale_query_formats,
    .priv_size = sizeof(NPPScaleContext),
    .priv_class = &nppscale_class,
    .inputs    = nppscale_inputs,
    .outputs   = nppscale_outputs,
}
Definition at line 656 of file vf_scale_npp.c.