FFmpeg: libavfilter/vf_waveform.c File Reference
vf_waveform.c File Reference
#include "libavutil/avassert.h"
#include "libavutil/opt.h"
#include "libavutil/parseutils.h"
#include "libavutil/pixdesc.h"
#include "libavutil/xga_font_data.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
Data Structures
struct GraticuleLine
struct GraticuleLines
struct WaveformContext
Macros
#define OFFSET(x) offsetof(WaveformContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
#define LOWPASS16_FUNC(name, column, mirror)
#define LOWPASS_FUNC(name, column, mirror)
Enumerations
enum FilterType {
BUTTERWORTH, CHEBYSHEV1, CHEBYSHEV2, NB_TYPES,
biquad, equalizer, bass, treble,
band, bandpass, bandreject, allpass,
highpass, lowpass, LOWPASS, FLAT,
AFLAT, CHROMA, COLOR, ACOLOR,
NB_FILTERS
}
enum DisplayType { OVERLAY, STACK, PARADE, NB_DISPLAYS }
enum ScaleType { DIGITAL, MILLIVOLTS, IRE, NB_SCALES }
Functions
AVFILTER_DEFINE_CLASS (waveform)
static int query_formats (AVFilterContext *ctx)
static void envelope_instant16 (WaveformContext *s, AVFrame *out, int plane, int component, int offset)
static void envelope_instant (WaveformContext *s, AVFrame *out, int plane, int component, int offset)
static void envelope_peak16 (WaveformContext *s, AVFrame *out, int plane, int component, int offset)
static void envelope_peak (WaveformContext *s, AVFrame *out, int plane, int component, int offset)
static void envelope16 (WaveformContext *s, AVFrame *out, int plane, int component, int offset)
static void envelope (WaveformContext *s, AVFrame *out, int plane, int component, int offset)
static void update16 (uint16_t *target, int max, int intensity, int limit)
static void update (uint8_t *target, int max, int intensity)
static av_always_inline void lowpass16 (WaveformContext *s, AVFrame *in, AVFrame *out, int component, int intensity, int offset_y, int offset_x, int column, int mirror)
static av_always_inline void lowpass (WaveformContext *s, AVFrame *in, AVFrame *out, int component, int intensity, int offset_y, int offset_x, int column, int mirror)
static av_always_inline void flat16 (WaveformContext *s, AVFrame *in, AVFrame *out, int component, int intensity, int offset_y, int offset_x, int column, int mirror)
static av_always_inline void flat (WaveformContext *s, AVFrame *in, AVFrame *out, int component, int intensity, int offset_y, int offset_x, int column, int mirror)
static av_always_inline void aflat16 (WaveformContext *s, AVFrame *in, AVFrame *out, int component, int intensity, int offset_y, int offset_x, int column, int mirror)
static av_always_inline void aflat (WaveformContext *s, AVFrame *in, AVFrame *out, int component, int intensity, int offset_y, int offset_x, int column, int mirror)
static av_always_inline void chroma16 (WaveformContext *s, AVFrame *in, AVFrame *out, int component, int intensity, int offset_y, int offset_x, int column, int mirror)
static av_always_inline void chroma (WaveformContext *s, AVFrame *in, AVFrame *out, int component, int intensity, int offset_y, int offset_x, int column, int mirror)
static av_always_inline void color16 (WaveformContext *s, AVFrame *in, AVFrame *out, int component, int intensity, int offset_y, int offset_x, int column, int mirror)
static av_always_inline void color (WaveformContext *s, AVFrame *in, AVFrame *out, int component, int intensity, int offset_y, int offset_x, int column, int mirror)
static av_always_inline void acolor16 (WaveformContext *s, AVFrame *in, AVFrame *out, int component, int intensity, int offset_y, int offset_x, int column, int mirror)
static av_always_inline void acolor (WaveformContext *s, AVFrame *in, AVFrame *out, int component, int intensity, int offset_y, int offset_x, int column, int mirror)
static void blend_vline (uint8_t *dst, int height, int linesize, float o1, float o2, int v, int step)
static void blend_vline16 (uint16_t *dst, int height, int linesize, float o1, float o2, int v, int step)
static void blend_hline (uint8_t *dst, int width, float o1, float o2, int v, int step)
static void blend_hline16 (uint16_t *dst, int width, float o1, float o2, int v, int step)
static void draw_htext (AVFrame *out, int x, int y, float o1, float o2, const char *txt, const uint8_t color[4])
static void draw_htext16 (AVFrame *out, int x, int y, int mult, float o1, float o2, const char *txt, const uint8_t color[4])
static void draw_vtext (AVFrame *out, int x, int y, float o1, float o2, const char *txt, const uint8_t color[4])
static void draw_vtext16 (AVFrame *out, int x, int y, int mult, float o1, float o2, const char *txt, const uint8_t color[4])
static void graticule_none (WaveformContext *s, AVFrame *out)
static void graticule_green_row (WaveformContext *s, AVFrame *out)
static void graticule16_green_row (WaveformContext *s, AVFrame *out)
static void graticule_green_column (WaveformContext *s, AVFrame *out)
static void graticule16_green_column (WaveformContext *s, AVFrame *out)
static int config_input (AVFilterLink *inlink)
static int config_output (AVFilterLink *outlink)
static int filter_frame (AVFilterLink *inlink, AVFrame *in)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const AVOption waveform_options []
static enum AVPixelFormat in_lowpass_pix_fmts []
static enum AVPixelFormat in_color_pix_fmts []
static enum AVPixelFormat in_flat_pix_fmts []
static enum AVPixelFormat out_rgb8_lowpass_pix_fmts []
static enum AVPixelFormat out_rgb9_lowpass_pix_fmts []
static enum AVPixelFormat out_rgb10_lowpass_pix_fmts []
static enum AVPixelFormat out_rgb12_lowpass_pix_fmts []
static enum AVPixelFormat out_yuv8_lowpass_pix_fmts []
static enum AVPixelFormat out_yuv9_lowpass_pix_fmts []
static enum AVPixelFormat out_yuv10_lowpass_pix_fmts []
static enum AVPixelFormat out_yuv12_lowpass_pix_fmts []
static enum AVPixelFormat out_gray8_lowpass_pix_fmts []
static enum AVPixelFormat out_gray10_lowpass_pix_fmts []
static enum AVPixelFormat out_gray12_lowpass_pix_fmts []
static enum AVPixelFormat flat_pix_fmts []
static const uint8_t black_yuva_color [4] = { 0, 127, 127, 255 }
static const uint8_t green_yuva_color [4] = { 255, 0, 0, 255 }
static const uint8_t black_gbrp_color [4] = { 0, 0, 0, 255 }
static const GraticuleLines aflat_digital8 []
static const GraticuleLines aflat_digital9 []
static const GraticuleLines aflat_digital10 []
static const GraticuleLines aflat_digital12 []
static const GraticuleLines aflat_millivolts8 []
static const GraticuleLines aflat_millivolts9 []
static const GraticuleLines aflat_millivolts10 []
static const GraticuleLines aflat_millivolts12 []
static const GraticuleLines aflat_ire8 []
static const GraticuleLines aflat_ire9 []
static const GraticuleLines aflat_ire10 []
static const GraticuleLines aflat_ire12 []
static const GraticuleLines flat_digital8 []
static const GraticuleLines flat_digital9 []
static const GraticuleLines flat_digital10 []
static const GraticuleLines flat_digital12 []
static const GraticuleLines flat_millivolts8 []
static const GraticuleLines flat_millivolts9 []
static const GraticuleLines flat_millivolts10 []
static const GraticuleLines flat_millivolts12 []
static const GraticuleLines flat_ire8 []
static const GraticuleLines flat_ire9 []
static const GraticuleLines flat_ire10 []
static const GraticuleLines flat_ire12 []
static const GraticuleLines digital8 []
static const GraticuleLines digital9 []
static const GraticuleLines digital10 []
static const GraticuleLines digital12 []
static const GraticuleLines millivolts8 []
static const GraticuleLines millivolts9 []
static const GraticuleLines millivolts10 []
static const GraticuleLines millivolts12 []
static const GraticuleLines ire8 []
static const GraticuleLines ire9 []
static const GraticuleLines ire10 []
static const GraticuleLines ire12 []
static const GraticuleLines chroma_digital8 []
static const GraticuleLines chroma_digital9 []
static const GraticuleLines chroma_digital10 []
static const GraticuleLines chroma_digital12 []
static const AVFilterPad inputs []
static const AVFilterPad outputs []
AVFilter ff_vf_waveform
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(WaveformContext, x)
Definition at line 105 of file vf_waveform.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 106 of file vf_waveform.c.
LOWPASS16_FUNC
#define LOWPASS16_FUNC (name, column, mirror)
Value:
static void lowpass16_##name(WaveformContext *s,           \
                             AVFrame *in, AVFrame *out,    \
                             int component, int intensity, \
                             int offset_y, int offset_x,   \
                             int unused1, int unused2)     \
{                                                          \
    lowpass16(s, in, out, component, intensity,            \
              offset_y, offset_x, column, mirror);         \
}
Definition at line 673 of file vf_waveform.c.
LOWPASS_FUNC
#define LOWPASS_FUNC (name, column, mirror)
Value:
static void lowpass_##name(WaveformContext *s,           \
                           AVFrame *in, AVFrame *out,    \
                           int component, int intensity, \
                           int offset_y, int offset_x,   \
                           int unused1, int unused2)     \
{                                                        \
    lowpass(s, in, out, component, intensity,            \
            offset_y, offset_x, column, mirror);         \
}
Definition at line 771 of file vf_waveform.c.
Enumeration Type Documentation
FilterType
enum FilterType
Enumerator
BUTTERWORTH
CHEBYSHEV1
CHEBYSHEV2
NB_TYPES
biquad
equalizer
bass
treble
band
bandpass
bandreject
allpass
highpass
lowpass
LOWPASS
FLAT
AFLAT
CHROMA
COLOR
ACOLOR
NB_FILTERS
Definition at line 32 of file vf_waveform.c.
DisplayType
enum DisplayType
Enumerator
OVERLAY
STACK
PARADE
NB_DISPLAYS
Definition at line 42 of file vf_waveform.c.
ScaleType
enum ScaleType
Enumerator
DIGITAL
MILLIVOLTS
IRE
NB_SCALES
Definition at line 49 of file vf_waveform.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (waveform)
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 272 of file vf_waveform.c.
envelope_instant16()
static void envelope_instant16 (WaveformContext * s, AVFrame * out, int plane, int component, int offset) static
Definition at line 342 of file vf_waveform.c.
Referenced by envelope16(), and envelope_peak16().
envelope_instant()
static void envelope_instant (WaveformContext * s, AVFrame * out, int plane, int component, int offset) static
Definition at line 390 of file vf_waveform.c.
Referenced by envelope(), and envelope_peak().
envelope_peak16()
static void envelope_peak16 (WaveformContext * s, AVFrame * out, int plane, int component, int offset) static
Definition at line 437 of file vf_waveform.c.
Referenced by envelope16().
envelope_peak()
static void envelope_peak (WaveformContext * s, AVFrame * out, int plane, int component, int offset) static
Definition at line 507 of file vf_waveform.c.
Referenced by envelope().
envelope16()
static void envelope16 (WaveformContext * s, AVFrame * out, int plane, int component, int offset) static
Definition at line 576 of file vf_waveform.c.
Referenced by acolor16(), aflat16(), chroma16(), color16(), flat16(), and lowpass16().
envelope()
static void envelope (WaveformContext * s, AVFrame * out, int plane, int component, int offset) static
Definition at line 587 of file vf_waveform.c.
Referenced by acolor(), aflat(), chroma(), color(), flat(), and lowpass().
update16()
static void update16 (uint16_t * target, int max, int intensity, int limit) static
Definition at line 598 of file vf_waveform.c.
Referenced by acolor16(), aflat16(), chroma16(), flat16(), and lowpass16().
update()
static void update (uint8_t * target, int max, int intensity) static
Definition at line 606 of file vf_waveform.c.
Referenced by acolor(), aflat(), chroma(), flat(), and lowpass().
lowpass16()
static av_always_inline void lowpass16 (WaveformContext * s, AVFrame * in, AVFrame * out, int component, int intensity, int offset_y, int offset_x, int column, int mirror) static
Definition at line 614 of file vf_waveform.c.
lowpass()
static av_always_inline void lowpass (WaveformContext * s, AVFrame * in, AVFrame * out, int component, int intensity, int offset_y, int offset_x, int column, int mirror) static
Definition at line 689 of file vf_waveform.c.
flat16()
static av_always_inline void flat16 (WaveformContext * s, AVFrame * in, AVFrame * out, int component, int intensity, int offset_y, int offset_x, int column, int mirror) static
Definition at line 787 of file vf_waveform.c.
Referenced by config_input().
flat()
static av_always_inline void flat (WaveformContext * s, AVFrame * in, AVFrame * out, int component, int intensity, int offset_y, int offset_x, int column, int mirror) static
Definition at line 899 of file vf_waveform.c.
Referenced by config_input(), ff_loop_filter_h_44_16_msa(), ff_loop_filter_h_48_16_msa(), ff_loop_filter_h_4_8_msa(), ff_loop_filter_h_84_16_msa(), ff_loop_filter_h_88_16_msa(), ff_loop_filter_h_8_8_msa(), ff_loop_filter_v_16_8_msa(), ff_loop_filter_v_44_16_msa(), ff_loop_filter_v_48_16_msa(), ff_loop_filter_v_4_8_msa(), ff_loop_filter_v_84_16_msa(), ff_loop_filter_v_88_16_msa(), ff_loop_filter_v_8_8_msa(), ff_vp8_h_loop_filter16_inner_msa(), ff_vp8_h_loop_filter16_msa(), ff_vp8_h_loop_filter8uv_inner_msa(), ff_vp8_h_loop_filter8uv_msa(), ff_vp8_v_loop_filter16_inner_msa(), ff_vp8_v_loop_filter16_msa(), ff_vp8_v_loop_filter8uv_inner_msa(), ff_vp8_v_loop_filter8uv_msa(), flat_init(), flat_print_section_header(), flat_print_str(), vp9_hz_lpf_t16_16w(), vp9_hz_lpf_t4_and_t8_16w(), vp9_vt_lpf_t16_16w(), vp9_vt_lpf_t16_8w(), vp9_vt_lpf_t4_and_t8_16w(), and vp9_vt_lpf_t4_and_t8_8w().
aflat16()
static av_always_inline void aflat16 (WaveformContext * s, AVFrame * in, AVFrame * out, int component, int intensity, int offset_y, int offset_x, int column, int mirror) static
Definition at line 1009 of file vf_waveform.c.
Referenced by config_input().
aflat()
static av_always_inline void aflat (WaveformContext * s, AVFrame * in, AVFrame * out, int component, int intensity, int offset_y, int offset_x, int column, int mirror) static
Definition at line 1135 of file vf_waveform.c.
Referenced by config_input().
chroma16()
static av_always_inline void chroma16 (WaveformContext * s, AVFrame * in, AVFrame * out, int component, int intensity, int offset_y, int offset_x, int column, int mirror) static
Definition at line 1259 of file vf_waveform.c.
Referenced by config_input().
chroma()
static av_always_inline void chroma (WaveformContext * s, AVFrame * in, AVFrame * out, int component, int intensity, int offset_y, int offset_x, int column, int mirror) static
Definition at line 1337 of file vf_waveform.c.
Referenced by check_idct_dc4(), config_input(), deblocking_filter_CTB(), encode_slice_plane(), ff_h264_filter_mb(), fic_draw_cursor(), filter_frame(), h264_filter_mb_fast_internal(), rv40_adaptive_loop_filter(), set_frame_data(), ulti_decode_frame(), and x8_decode_intra_mb().
color16()
static av_always_inline void color16 (WaveformContext * s, AVFrame * in, AVFrame * out, int component, int intensity, int offset_y, int offset_x, int column, int mirror) static
Definition at line 1413 of file vf_waveform.c.
Referenced by config_input().
color()
static av_always_inline void color (WaveformContext * s, AVFrame * in, AVFrame * out, int component, int intensity, int offset_y, int offset_x, int column, int mirror) static
Definition at line 1518 of file vf_waveform.c.
Referenced by config_input().
acolor16()
static av_always_inline void acolor16 (WaveformContext * s, AVFrame * in, AVFrame * out, int component, int intensity, int offset_y, int offset_x, int column, int mirror) static
Definition at line 1622 of file vf_waveform.c.
Referenced by config_input().
acolor()
static av_always_inline void acolor (WaveformContext * s, AVFrame * in, AVFrame * out, int component, int intensity, int offset_y, int offset_x, int column, int mirror) static
Definition at line 1728 of file vf_waveform.c.
Referenced by config_input().
blend_vline()
static void blend_vline (uint8_t * dst, int height, int linesize, float o1, float o2, int v, int step) static
Definition at line 2149 of file vf_waveform.c.
Referenced by graticule_green_row().
blend_vline16()
static void blend_vline16 (uint16_t * dst, int height, int linesize, float o1, float o2, int v, int step) static
Definition at line 2160 of file vf_waveform.c.
Referenced by graticule16_green_row().
blend_hline()
static void blend_hline (uint8_t * dst, int width, float o1, float o2, int v, int step) static
Definition at line 2171 of file vf_waveform.c.
Referenced by graticule_green_column().
blend_hline16()
static void blend_hline16 (uint16_t * dst, int width, float o1, float o2, int v, int step) static
Definition at line 2180 of file vf_waveform.c.
Referenced by graticule16_green_column().
draw_htext()
static void draw_htext (AVFrame * out, int x, int y, float o1, float o2, const char * txt, const uint8_t color[4]) static
Definition at line 2189 of file vf_waveform.c.
Referenced by graticule_green_column().
draw_htext16()
static void draw_htext16 (AVFrame * out, int x, int y, int mult, float o1, float o2, const char * txt, const uint8_t color[4]) static
Definition at line 2215 of file vf_waveform.c.
Referenced by graticule16_green_column().
draw_vtext()
static void draw_vtext (AVFrame * out, int x, int y, float o1, float o2, const char * txt, const uint8_t color[4]) static
Definition at line 2241 of file vf_waveform.c.
Referenced by graticule_green_row().
draw_vtext16()
static void draw_vtext16 (AVFrame * out, int x, int y, int mult, float o1, float o2, const char * txt, const uint8_t color[4]) static
Definition at line 2266 of file vf_waveform.c.
Referenced by graticule16_green_row().
graticule_none()
static void graticule_none (WaveformContext * s, AVFrame * out) static
Definition at line 2291 of file vf_waveform.c.
Referenced by config_input().
graticule_green_row()
static void graticule_green_row (WaveformContext * s, AVFrame * out) static
Definition at line 2295 of file vf_waveform.c.
Referenced by config_input().
graticule16_green_row()
static void graticule16_green_row (WaveformContext * s, AVFrame * out) static
Definition at line 2335 of file vf_waveform.c.
Referenced by config_input().
graticule_green_column()
static void graticule_green_column (WaveformContext * s, AVFrame * out) static
Definition at line 2376 of file vf_waveform.c.
Referenced by config_input().
graticule16_green_column()
static void graticule16_green_column (WaveformContext * s, AVFrame * out) static
Definition at line 2416 of file vf_waveform.c.
Referenced by config_input().
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 2457 of file vf_waveform.c.
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 2684 of file vf_waveform.c.
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 2743 of file vf_waveform.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 2798 of file vf_waveform.c.
Variable Documentation
waveform_options
const AVOption waveform_options[] static
Definition at line 108 of file vf_waveform.c.
in_lowpass_pix_fmts
enum AVPixelFormat in_lowpass_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_GBRP,     AV_PIX_FMT_GBRAP,
    AV_PIX_FMT_GBRP9,    AV_PIX_FMT_GBRP10, AV_PIX_FMT_GBRP12,
    AV_PIX_FMT_YUV422P,  AV_PIX_FMT_YUV420P,
    AV_PIX_FMT_YUV444P,  AV_PIX_FMT_YUV440P,
    AV_PIX_FMT_YUV411P,  AV_PIX_FMT_YUV410P,
    AV_PIX_FMT_YUVJ440P, AV_PIX_FMT_YUVJ411P, AV_PIX_FMT_YUVJ420P,
    AV_PIX_FMT_YUVJ422P, AV_PIX_FMT_YUVJ444P,
    AV_PIX_FMT_YUVA444P, AV_PIX_FMT_YUVA422P, AV_PIX_FMT_YUVA420P,
    AV_PIX_FMT_GRAY8, AV_PIX_FMT_GRAY10, AV_PIX_FMT_GRAY12,
    AV_PIX_FMT_YUV444P9, AV_PIX_FMT_YUV422P9, AV_PIX_FMT_YUV420P9,
    AV_PIX_FMT_YUVA444P9, AV_PIX_FMT_YUVA422P9, AV_PIX_FMT_YUVA420P9,
    AV_PIX_FMT_YUV444P10, AV_PIX_FMT_YUV422P10, AV_PIX_FMT_YUV420P10,
    AV_PIX_FMT_YUVA444P10, AV_PIX_FMT_YUVA422P10, AV_PIX_FMT_YUVA420P10,
    AV_PIX_FMT_YUV444P12, AV_PIX_FMT_YUV422P12, AV_PIX_FMT_YUV420P12, AV_PIX_FMT_YUV440P12,
    AV_PIX_FMT_NONE
}
Definition at line 160 of file vf_waveform.c.
Referenced by query_formats().
in_color_pix_fmts
enum AVPixelFormat in_color_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_GBRP,     AV_PIX_FMT_GBRAP,
    AV_PIX_FMT_GBRP9,    AV_PIX_FMT_GBRP10, AV_PIX_FMT_GBRP12,
    AV_PIX_FMT_YUV422P,  AV_PIX_FMT_YUV420P,
    AV_PIX_FMT_YUV444P,  AV_PIX_FMT_YUV440P,
    AV_PIX_FMT_YUV411P,
    AV_PIX_FMT_YUVJ440P, AV_PIX_FMT_YUVJ411P, AV_PIX_FMT_YUVJ420P,
    AV_PIX_FMT_YUVJ422P, AV_PIX_FMT_YUVJ444P,
    AV_PIX_FMT_YUVA444P, AV_PIX_FMT_YUVA422P, AV_PIX_FMT_YUVA420P,
    AV_PIX_FMT_YUV444P9, AV_PIX_FMT_YUV422P9, AV_PIX_FMT_YUV420P9,
    AV_PIX_FMT_YUVA444P9, AV_PIX_FMT_YUVA422P9, AV_PIX_FMT_YUVA420P9,
    AV_PIX_FMT_YUV444P10, AV_PIX_FMT_YUV422P10, AV_PIX_FMT_YUV420P10,
    AV_PIX_FMT_YUVA444P10, AV_PIX_FMT_YUVA422P10, AV_PIX_FMT_YUVA420P10,
    AV_PIX_FMT_YUV444P12, AV_PIX_FMT_YUV422P12, AV_PIX_FMT_YUV420P12, AV_PIX_FMT_YUV440P12,
    AV_PIX_FMT_NONE
}
Definition at line 178 of file vf_waveform.c.
Referenced by query_formats().
in_flat_pix_fmts
enum AVPixelFormat in_flat_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_YUV422P,  AV_PIX_FMT_YUV420P,
    AV_PIX_FMT_YUV444P,  AV_PIX_FMT_YUV440P,
    AV_PIX_FMT_YUV411P,
    AV_PIX_FMT_YUVJ440P, AV_PIX_FMT_YUVJ411P, AV_PIX_FMT_YUVJ420P,
    AV_PIX_FMT_YUVJ422P, AV_PIX_FMT_YUVJ444P,
    AV_PIX_FMT_YUVA444P, AV_PIX_FMT_YUVA422P, AV_PIX_FMT_YUVA420P,
    AV_PIX_FMT_YUV444P9, AV_PIX_FMT_YUV422P9, AV_PIX_FMT_YUV420P9,
    AV_PIX_FMT_YUVA444P9, AV_PIX_FMT_YUVA422P9, AV_PIX_FMT_YUVA420P9,
    AV_PIX_FMT_YUV444P10, AV_PIX_FMT_YUV422P10, AV_PIX_FMT_YUV420P10,
    AV_PIX_FMT_YUVA444P10, AV_PIX_FMT_YUVA422P10, AV_PIX_FMT_YUVA420P10,
    AV_PIX_FMT_YUV444P12, AV_PIX_FMT_YUV422P12, AV_PIX_FMT_YUV420P12, AV_PIX_FMT_YUV440P12,
    AV_PIX_FMT_NONE
}
Definition at line 195 of file vf_waveform.c.
Referenced by query_formats().
out_rgb8_lowpass_pix_fmts
enum AVPixelFormat out_rgb8_lowpass_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_GBRP, AV_PIX_FMT_GBRAP,
    AV_PIX_FMT_NONE
}
Definition at line 210 of file vf_waveform.c.
Referenced by query_formats().
out_rgb9_lowpass_pix_fmts
enum AVPixelFormat out_rgb9_lowpass_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_GBRP9,
    AV_PIX_FMT_NONE
}
Definition at line 215 of file vf_waveform.c.
Referenced by query_formats().
out_rgb10_lowpass_pix_fmts
enum AVPixelFormat out_rgb10_lowpass_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_GBRP10,
    AV_PIX_FMT_NONE
}
Definition at line 220 of file vf_waveform.c.
Referenced by query_formats().
out_rgb12_lowpass_pix_fmts
enum AVPixelFormat out_rgb12_lowpass_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_GBRP12,
    AV_PIX_FMT_NONE
}
Definition at line 225 of file vf_waveform.c.
Referenced by query_formats().
out_yuv8_lowpass_pix_fmts
enum AVPixelFormat out_yuv8_lowpass_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_YUV444P,  AV_PIX_FMT_YUVJ444P, AV_PIX_FMT_YUVA444P,
    AV_PIX_FMT_NONE
}
Definition at line 230 of file vf_waveform.c.
Referenced by query_formats().
out_yuv9_lowpass_pix_fmts
enum AVPixelFormat out_yuv9_lowpass_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_YUV444P9, AV_PIX_FMT_YUVA444P9,
    AV_PIX_FMT_NONE
}
Definition at line 235 of file vf_waveform.c.
Referenced by query_formats().
out_yuv10_lowpass_pix_fmts
enum AVPixelFormat out_yuv10_lowpass_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_YUV444P10, AV_PIX_FMT_YUVA444P10,
    AV_PIX_FMT_NONE
}
Definition at line 240 of file vf_waveform.c.
Referenced by query_formats().
out_yuv12_lowpass_pix_fmts
enum AVPixelFormat out_yuv12_lowpass_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_YUV444P12,
    AV_PIX_FMT_NONE
}
Definition at line 245 of file vf_waveform.c.
Referenced by query_formats().
out_gray8_lowpass_pix_fmts
enum AVPixelFormat out_gray8_lowpass_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_GRAY8,
    AV_PIX_FMT_NONE
}
Definition at line 250 of file vf_waveform.c.
Referenced by query_formats().
out_gray10_lowpass_pix_fmts
enum AVPixelFormat out_gray10_lowpass_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_GRAY10,
    AV_PIX_FMT_NONE
}
Definition at line 255 of file vf_waveform.c.
Referenced by query_formats().
out_gray12_lowpass_pix_fmts
enum AVPixelFormat out_gray12_lowpass_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_GRAY12,
    AV_PIX_FMT_NONE
}
Definition at line 260 of file vf_waveform.c.
Referenced by query_formats().
flat_pix_fmts
enum AVPixelFormat flat_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_YUV444P, AV_PIX_FMT_YUVJ444P,
    AV_PIX_FMT_YUV444P9, AV_PIX_FMT_YUV444P10,
    AV_PIX_FMT_YUV444P12,
    AV_PIX_FMT_NONE
}
Definition at line 265 of file vf_waveform.c.
black_yuva_color
const uint8_t black_yuva_color[4] = { 0, 127, 127, 255 } static
Definition at line 1833 of file vf_waveform.c.
Referenced by config_input().
green_yuva_color
const uint8_t green_yuva_color[4] = { 255, 0, 0, 255 } static
Definition at line 1834 of file vf_waveform.c.
Referenced by graticule16_green_column(), graticule16_green_row(), graticule_green_column(), and graticule_green_row().
black_gbrp_color
const uint8_t black_gbrp_color[4] = { 0, 0, 0, 255 } static
Definition at line 1835 of file vf_waveform.c.
Referenced by config_input().
aflat_digital8
const GraticuleLines aflat_digital8[] static
Initial value:
= {
    { { {  "16",  16+128 }, {  "16",  16+128 }, {  "16",  16+128 }, {   "0",   0+128 } } },
    { { { "128", 128+128 }, { "128", 128+128 }, { "128", 128+128 }, { "128", 128+128 } } },
    { { { "235", 235+128 }, { "240", 240+128 }, { "240", 240+128 }, { "255", 255+128 } } },
}
Definition at line 1837 of file vf_waveform.c.
aflat_digital9
const GraticuleLines aflat_digital9[] static
Initial value:
= {
    { { {  "32",  32+256 }, {  "32",  32+256 }, {  "32",  32+256 }, {   "0",   0+256 } } },
    { { { "256", 256+256 }, { "256", 256+256 }, { "256", 256+256 }, { "256", 256+256 } } },
    { { { "470", 470+256 }, { "480", 480+256 }, { "480", 480+256 }, { "511", 511+256 } } },
}
Definition at line 1843 of file vf_waveform.c.
aflat_digital10
const GraticuleLines aflat_digital10[] static
Initial value:
= {
    { { {  "64",  64+512 }, {  "64",  64+512 }, {  "64",  64+512 }, {    "0",    0+512 } } },
    { { { "512", 512+512 }, { "512", 512+512 }, { "512", 512+512 }, {  "512",  512+512 } } },
    { { { "940", 940+512 }, { "960", 960+512 }, { "960", 960+512 }, { "1023", 1023+512 } } },
}
Definition at line 1849 of file vf_waveform.c.
aflat_digital12
const GraticuleLines aflat_digital12[] static
Initial value:
= {
    { { {  "256",  256+2048 }, {  "256",  256+2048 }, {  "256",  256+2048 }, {    "0",    0+2048 } } },
    { { { "2048", 2048+2048 }, { "2048", 2048+2048 }, { "2048", 2048+2048 }, { "2048", 2048+2048 } } },
    { { { "3760", 3760+2048 }, { "3840", 3840+2048 }, { "3840", 3840+2048 }, { "4095", 4095+2048 } } },
}
Definition at line 1855 of file vf_waveform.c.
aflat_millivolts8
const GraticuleLines aflat_millivolts8[] static
Initial value:
= {
    { { {   "0",  16+128 }, {   "0",  16+128 }, {   "0",  16+128 }, {   "0",   0+128 } } },
    { { { "175",  71+128 }, { "175",  72+128 }, { "175",  72+128 }, { "175",  64+128 } } },
    { { { "350", 126+128 }, { "350", 128+128 }, { "350", 128+128 }, { "350", 128+128 } } },
    { { { "525", 180+128 }, { "525", 184+128 }, { "525", 184+128 }, { "525", 192+128 } } },
    { { { "700", 235+128 }, { "700", 240+128 }, { "700", 240+128 }, { "700", 255+128 } } },
}
Definition at line 1861 of file vf_waveform.c.
aflat_millivolts9
const GraticuleLines aflat_millivolts9[] static
Initial value:
= {
    { { {   "0",  32+256 }, {   "0",  32+256 }, {   "0",  32+256 }, {   "0",   0+256 } } },
    { { { "175", 142+256 }, { "175", 144+256 }, { "175", 144+256 }, { "175", 128+256 } } },
    { { { "350", 251+256 }, { "350", 256+256 }, { "350", 256+256 }, { "350", 256+256 } } },
    { { { "525", 361+256 }, { "525", 368+256 }, { "525", 368+256 }, { "525", 384+256 } } },
    { { { "700", 470+256 }, { "700", 480+256 }, { "700", 480+256 }, { "700", 511+256 } } },
}
Definition at line 1869 of file vf_waveform.c.
aflat_millivolts10
const GraticuleLines aflat_millivolts10[] static
Initial value:
= {
    { { {   "0",  64+512 }, {   "0",  64+512 }, {   "0",  64+512 }, {   "0",    0+512 } } },
    { { { "175", 283+512 }, { "175", 288+512 }, { "175", 288+512 }, { "175",  256+512 } } },
    { { { "350", 502+512 }, { "350", 512+512 }, { "350", 512+512 }, { "350",  512+512 } } },
    { { { "525", 721+512 }, { "525", 736+512 }, { "525", 736+512 }, { "525",  768+512 } } },
    { { { "700", 940+512 }, { "700", 960+512 }, { "700", 960+512 }, { "700", 1023+512 } } },
}
Definition at line 1877 of file vf_waveform.c.
aflat_millivolts12
const GraticuleLines aflat_millivolts12[] static
Initial value:
= {
    { { {   "0",  256+2048 }, {   "0",  256+2048 }, {   "0",  256+2048 }, {   "0",    0+2048 } } },
    { { { "175", 1132+2048 }, { "175", 1152+2048 }, { "175", 1152+2048 }, { "175", 1024+2048 } } },
    { { { "350", 2008+2048 }, { "350", 2048+2048 }, { "350", 2048+2048 }, { "350", 2048+2048 } } },
    { { { "525", 2884+2048 }, { "525", 2944+2048 }, { "525", 2944+2048 }, { "525", 3072+2048 } } },
    { { { "700", 3760+2048 }, { "700", 3840+2048 }, { "700", 3840+2048 }, { "700", 4095+2048 } } },
}
Definition at line 1885 of file vf_waveform.c.
aflat_ire8
const GraticuleLines aflat_ire8[] static
Initial value:
= {
    { { { "-25", -39+128 }, { "-25", -40+128 }, { "-25", -40+128 }, { "-25", -64+128 } } },
    { { {   "0",  16+128 }, {   "0",  16+128 }, {   "0",  16+128 }, {   "0",   0+128 } } },
    { { {  "25",  71+128 }, {  "25",  72+128 }, {  "25",  72+128 }, {  "25",  64+128 } } },
    { { {  "50", 126+128 }, {  "50", 128+128 }, {  "50", 128+128 }, {  "50", 128+128 } } },
    { { {  "75", 180+128 }, {  "75", 184+128 }, {  "75", 184+128 }, {  "75", 192+128 } } },
    { { { "100", 235+128 }, { "100", 240+128 }, { "100", 240+128 }, { "100", 256+128 } } },
    { { { "125", 290+128 }, { "125", 296+128 }, { "125", 296+128 }, { "125", 320+128 } } },
}
Definition at line 1893 of file vf_waveform.c.
aflat_ire9
const GraticuleLines aflat_ire9[] static
Initial value:
= {
    { { { "-25", -78+256 }, { "-25", -80+256 }, { "-25", -80+256 }, { "-25",-128+256 } } },
    { { {   "0",  32+256 }, {   "0",  32+256 }, {   "0",  32+256 }, {   "0",   0+256 } } },
    { { {  "25", 142+256 }, {  "25", 144+256 }, {  "25", 144+256 }, {  "25", 128+256 } } },
    { { {  "50", 251+256 }, {  "50", 256+256 }, {  "50", 256+256 }, {  "50", 256+256 } } },
    { { {  "75", 361+256 }, {  "75", 368+256 }, {  "75", 368+256 }, {  "75", 384+256 } } },
    { { { "100", 470+256 }, { "100", 480+256 }, { "100", 480+256 }, { "100", 512+256 } } },
    { { { "125", 580+256 }, { "125", 592+256 }, { "125", 592+256 }, { "125", 640+256 } } },
}
Definition at line 1903 of file vf_waveform.c.
aflat_ire10
const GraticuleLines aflat_ire10[] static
Initial value:
= {
    { { { "-25",-156+512 }, { "-25",-160+512 }, { "-25",-160+512 }, { "-25", -256+512 } } },
    { { {   "0",  64+512 }, {   "0",  64+512 }, {  "0",   64+512 }, {   "0",    0+512 } } },
    { { {  "25", 283+512 }, {  "25", 288+512 }, {  "25", 288+512 }, {  "25",  256+512 } } },
    { { {  "50", 502+512 }, {  "50", 512+512 }, {  "50", 512+512 }, {  "50",  512+512 } } },
    { { {  "75", 721+512 }, {  "75", 736+512 }, {  "75", 736+512 }, {  "75",  768+512 } } },
    { { { "100", 940+512 }, { "100", 960+512 }, { "100", 960+512 }, { "100", 1024+512 } } },
    { { { "125",1160+512 }, { "125",1184+512 }, { "125",1184+512 }, { "125", 1280+512 } } },
}
Definition at line 1913 of file vf_waveform.c.
aflat_ire12
const GraticuleLines aflat_ire12[] static
Initial value:
= {
    { { { "-25", -624+2048 }, { "-25", -640+2048 }, { "-25", -640+2048 }, { "-25",-1024+2048 } } },
    { { {   "0",  256+2048 }, {   "0",  256+2048 }, {   "0",  256+2048 }, {   "0",    0+2048 } } },
    { { {  "25", 1132+2048 }, {  "25", 1152+2048 }, {  "25", 1152+2048 }, {  "25", 1024+2048 } } },
    { { {  "50", 2008+2048 }, {  "50", 2048+2048 }, {  "50", 2048+2048 }, {  "50", 2048+2048 } } },
    { { {  "75", 2884+2048 }, {  "75", 2944+2048 }, {  "75", 2944+2048 }, {  "75", 3072+2048 } } },
    { { { "100", 3760+2048 }, { "100", 3840+2048 }, { "100", 3840+2048 }, { "100", 4096+2048 } } },
    { { { "125", 4640+2048 }, { "125", 4736+2048 }, { "125", 4736+2048 }, { "125", 5120+2048 } } },
}
Definition at line 1923 of file vf_waveform.c.
flat_digital8
const GraticuleLines flat_digital8[] static
Initial value:
= {
    { { {  "16",  16+256 }, {  "16",  16+256 }, {  "16",  16+256 }, {   "0",   0+256 } } },
    { { { "128", 128+256 }, { "128", 128+256 }, { "128", 128+256 }, { "128", 128+256 } } },
    { { { "235", 235+256 }, { "240", 240+256 }, { "240", 240+256 }, { "255", 255+256 } } },
}
Definition at line 1933 of file vf_waveform.c.
flat_digital9
const GraticuleLines flat_digital9[] static
Initial value:
= {
    { { {  "32",  32+512 }, {  "32",  32+512 }, {  "32",  32+512 }, {   "0",   0+512 } } },
    { { { "256", 256+512 }, { "256", 256+512 }, { "256", 256+512 }, { "256", 256+512 } } },
    { { { "470", 470+512 }, { "480", 480+512 }, { "480", 480+512 }, { "511", 511+512 } } },
}
Definition at line 1939 of file vf_waveform.c.
flat_digital10
const GraticuleLines flat_digital10[] static
Initial value:
= {
    { { {  "64",  64+1024 }, {  "64",  64+1024 }, {  "64",  64+1024 }, {    "0",    0+1024 } } },
    { { { "512", 512+1024 }, { "512", 512+1024 }, { "512", 512+1024 }, {  "512",  512+1024 } } },
    { { { "940", 940+1024 }, { "960", 960+1024 }, { "960", 960+1024 }, { "1023", 1023+1024 } } },
}
Definition at line 1945 of file vf_waveform.c.
flat_digital12
const GraticuleLines flat_digital12[] static
Initial value:
= {
    { { {  "256",  256+4096 }, {  "256",  256+4096 }, {  "256",  256+4096 }, {    "0",    0+4096 } } },
    { { { "2048", 2048+4096 }, { "2048", 2048+4096 }, { "2048", 2048+4096 }, { "2048", 2048+4096 } } },
    { { { "3760", 3760+4096 }, { "3840", 3840+4096 }, { "3840", 3840+4096 }, { "4095", 4095+4096 } } },
}
Definition at line 1951 of file vf_waveform.c.
flat_millivolts8
const GraticuleLines flat_millivolts8[] static
Initial value:
= {
    { { {   "0",  16+256 }, {   "0",  16+256 }, {   "0",  16+256 }, {   "0",   0+256 } } },
    { { { "175",  71+256 }, { "175",  72+256 }, { "175",  72+256 }, { "175",  64+256 } } },
    { { { "350", 126+256 }, { "350", 128+256 }, { "350", 128+256 }, { "350", 128+256 } } },
    { { { "525", 180+256 }, { "525", 184+256 }, { "525", 184+256 }, { "525", 192+256 } } },
    { { { "700", 235+256 }, { "700", 240+256 }, { "700", 240+256 }, { "700", 255+256 } } },
}
Definition at line 1957 of file vf_waveform.c.
flat_millivolts9
const GraticuleLines flat_millivolts9[] static
Initial value:
= {
    { { {   "0",  32+512 }, {   "0",  32+512 }, {   "0",  32+512 }, {   "0",   0+512 } } },
    { { { "175", 142+512 }, { "175", 144+512 }, { "175", 144+512 }, { "175", 128+512 } } },
    { { { "350", 251+512 }, { "350", 256+512 }, { "350", 256+512 }, { "350", 256+512 } } },
    { { { "525", 361+512 }, { "525", 368+512 }, { "525", 368+512 }, { "525", 384+512 } } },
    { { { "700", 470+512 }, { "700", 480+512 }, { "700", 480+512 }, { "700", 511+512 } } },
}
Definition at line 1965 of file vf_waveform.c.
flat_millivolts10
const GraticuleLines flat_millivolts10[] static
Initial value:
= {
    { { {   "0",  64+1024 }, {   "0",  64+1024 }, {   "0",  64+1024 }, {   "0",    0+1024 } } },
    { { { "175", 283+1024 }, { "175", 288+1024 }, { "175", 288+1024 }, { "175",  256+1024 } } },
    { { { "350", 502+1024 }, { "350", 512+1024 }, { "350", 512+1024 }, { "350",  512+1024 } } },
    { { { "525", 721+1024 }, { "525", 736+1024 }, { "525", 736+1024 }, { "525",  768+1024 } } },
    { { { "700", 940+1024 }, { "700", 960+1024 }, { "700", 960+1024 }, { "700", 1023+1024 } } },
}
Definition at line 1973 of file vf_waveform.c.
flat_millivolts12
const GraticuleLines flat_millivolts12[] static
Initial value:
= {
    { { {   "0",  256+4096 }, {   "0",  256+4096 }, {   "0",  256+4096 }, {   "0",    0+4096 } } },
    { { { "175", 1132+4096 }, { "175", 1152+4096 }, { "175", 1152+4096 }, { "175", 1024+4096 } } },
    { { { "350", 2008+4096 }, { "350", 2048+4096 }, { "350", 2048+4096 }, { "350", 2048+4096 } } },
    { { { "525", 2884+4096 }, { "525", 2944+4096 }, { "525", 2944+4096 }, { "525", 3072+4096 } } },
    { { { "700", 3760+4096 }, { "700", 3840+4096 }, { "700", 3840+4096 }, { "700", 4095+4096 } } },
}
Definition at line 1981 of file vf_waveform.c.
flat_ire8
const GraticuleLines flat_ire8[] static
Initial value:
= {
    { { { "-25", -39+256 }, { "-25", -40+256 }, { "-25", -40+256 }, { "-25", -64+256 } } },
    { { {   "0",  16+256 }, {   "0",  16+256 }, {   "0",  16+256 }, {   "0",   0+256 } } },
    { { {  "25",  71+256 }, {  "25",  72+256 }, {  "25",  72+256 }, {  "25",  64+256 } } },
    { { {  "50", 126+256 }, {  "50", 128+256 }, {  "50", 128+256 }, {  "50", 128+256 } } },
    { { {  "75", 180+256 }, {  "75", 184+256 }, {  "75", 184+256 }, {  "75", 192+256 } } },
    { { { "100", 235+256 }, { "100", 240+256 }, { "100", 240+256 }, { "100", 256+256 } } },
    { { { "125", 290+256 }, { "125", 296+256 }, { "125", 296+256 }, { "125", 320+256 } } },
}
Definition at line 1989 of file vf_waveform.c.
flat_ire9
const GraticuleLines flat_ire9[] static
Initial value:
= {
    { { { "-25", -78+512 }, { "-25", -80+512 }, { "-25", -80+512 }, { "-25",-128+512 } } },
    { { {   "0",  32+512 }, {   "0",  32+512 }, {   "0",  32+512 }, {   "0",   0+512 } } },
    { { {  "25", 142+512 }, {  "25", 144+512 }, {  "25", 144+512 }, {  "25", 128+512 } } },
    { { {  "50", 251+512 }, {  "50", 256+512 }, {  "50", 256+512 }, {  "50", 256+512 } } },
    { { {  "75", 361+512 }, {  "75", 368+512 }, {  "75", 368+512 }, {  "75", 384+512 } } },
    { { { "100", 470+512 }, { "100", 480+512 }, { "100", 480+512 }, { "100", 512+512 } } },
    { { { "125", 580+512 }, { "125", 592+512 }, { "125", 592+512 }, { "125", 640+512 } } },
}
Definition at line 1999 of file vf_waveform.c.
flat_ire10
const GraticuleLines flat_ire10[] static
Initial value:
= {
    { { { "-25",-156+1024 }, { "-25",-160+1024 }, { "-25",-160+1024 }, { "-25", -256+1024 } } },
    { { {   "0",  64+1024 }, {   "0",  64+1024 }, {  "0",   64+1024 }, {   "0",    0+1024 } } },
    { { {  "25", 283+1024 }, {  "25", 288+1024 }, {  "25", 288+1024 }, {  "25",  256+1024 } } },
    { { {  "50", 502+1024 }, {  "50", 512+1024 }, {  "50", 512+1024 }, {  "50",  512+1024 } } },
    { { {  "75", 721+1024 }, {  "75", 736+1024 }, {  "75", 736+1024 }, {  "75",  768+1024 } } },
    { { { "100", 940+1024 }, { "100", 960+1024 }, { "100", 960+1024 }, { "100", 1024+1024 } } },
    { { { "125",1160+1024 }, { "125",1184+1024 }, { "125",1184+1024 }, { "125", 1280+1024 } } },
}
Definition at line 2009 of file vf_waveform.c.
flat_ire12
const GraticuleLines flat_ire12[] static
Initial value:
= {
    { { { "-25", -624+4096 }, { "-25", -640+4096 }, { "-25", -640+4096 }, { "-25",-1024+4096 } } },
    { { {   "0",  256+4096 }, {   "0",  256+4096 }, {   "0",  256+4096 }, {   "0",    0+4096 } } },
    { { {  "25", 1132+4096 }, {  "25", 1152+4096 }, {  "25", 1152+4096 }, {  "25", 1024+4096 } } },
    { { {  "50", 2008+4096 }, {  "50", 2048+4096 }, {  "50", 2048+4096 }, {  "50", 2048+4096 } } },
    { { {  "75", 2884+4096 }, {  "75", 2944+4096 }, {  "75", 2944+4096 }, {  "75", 3072+4096 } } },
    { { { "100", 3760+4096 }, { "100", 3840+4096 }, { "100", 3840+4096 }, { "100", 4096+4096 } } },
    { { { "125", 4640+4096 }, { "125", 4736+4096 }, { "125", 4736+4096 }, { "125", 5120+4096 } } },
}
Definition at line 2019 of file vf_waveform.c.
digital8
const GraticuleLines digital8[] static
Initial value:
= {
    { { {  "16",  16 }, {  "16",  16 }, {  "16",  16 }, {   "0",   0 } } },
    { { { "128", 128 }, { "128", 128 }, { "128", 128 }, { "128", 128 } } },
    { { { "235", 235 }, { "240", 240 }, { "240", 240 }, { "255", 255 } } },
}
Definition at line 2029 of file vf_waveform.c.
digital9
const GraticuleLines digital9[] static
Initial value:
= {
    { { {  "32",  32 }, {  "32",  32 }, {  "32",  32 }, {   "0",   0 } } },
    { { { "256", 256 }, { "256", 256 }, { "256", 256 }, { "256", 256 } } },
    { { { "470", 470 }, { "480", 480 }, { "480", 480 }, { "511", 511 } } },
}
Definition at line 2035 of file vf_waveform.c.
digital10
const GraticuleLines digital10[] static
Initial value:
= {
    { { {  "64",  64 }, {  "64",  64 }, {  "64",  64 }, {    "0",    0 } } },
    { { { "512", 512 }, { "512", 512 }, { "512", 512 }, {  "512",  512 } } },
    { { { "940", 940 }, { "960", 960 }, { "960", 960 }, { "1023", 1023 } } },
}
Definition at line 2041 of file vf_waveform.c.
digital12
const GraticuleLines digital12[] static
Initial value:
= {
    { { {  "256",  256 }, {  "256",  256 }, {  "256",  256 }, {    "0",    0 } } },
    { { { "2048", 2048 }, { "2048", 2048 }, { "2048", 2048 }, { "2048", 2048 } } },
    { { { "3760", 3760 }, { "3840", 3840 }, { "3840", 3840 }, { "4095", 4095 } } },
}
Definition at line 2047 of file vf_waveform.c.
millivolts8
const GraticuleLines millivolts8[] static
Initial value:
= {
    { { {   "0",  16 }, {   "0",  16 }, {   "0",  16 }, {   "0",   0 } } },
    { { { "175",  71 }, { "175",  72 }, { "175",  72 }, { "175",  64 } } },
    { { { "350", 126 }, { "350", 128 }, { "350", 128 }, { "350", 128 } } },
    { { { "525", 180 }, { "525", 184 }, { "525", 184 }, { "525", 192 } } },
    { { { "700", 235 }, { "700", 240 }, { "700", 240 }, { "700", 255 } } },
}
Definition at line 2053 of file vf_waveform.c.
millivolts9
const GraticuleLines millivolts9[] static
Initial value:
= {
    { { {   "0",  32 }, {   "0",  32 }, {   "0",  32 }, {   "0",   0 } } },
    { { { "175", 142 }, { "175", 144 }, { "175", 144 }, { "175", 128 } } },
    { { { "350", 251 }, { "350", 256 }, { "350", 256 }, { "350", 256 } } },
    { { { "525", 361 }, { "525", 368 }, { "525", 368 }, { "525", 384 } } },
    { { { "700", 470 }, { "700", 480 }, { "700", 480 }, { "700", 511 } } },
}
Definition at line 2061 of file vf_waveform.c.
millivolts10
const GraticuleLines millivolts10[] static
Initial value:
= {
    { { {   "0",  64 }, {   "0",  64 }, {   "0",  64 }, {   "0",    0 } } },
    { { { "175", 283 }, { "175", 288 }, { "175", 288 }, { "175",  256 } } },
    { { { "350", 502 }, { "350", 512 }, { "350", 512 }, { "350",  512 } } },
    { { { "525", 721 }, { "525", 736 }, { "525", 736 }, { "525",  768 } } },
    { { { "700", 940 }, { "700", 960 }, { "700", 960 }, { "700", 1023 } } },
}
Definition at line 2069 of file vf_waveform.c.
millivolts12
const GraticuleLines millivolts12[] static
Initial value:
= {
    { { {   "0",  256 }, {   "0",  256 }, {   "0",  256 }, {   "0",    0 } } },
    { { { "175", 1132 }, { "175", 1152 }, { "175", 1152 }, { "175", 1024 } } },
    { { { "350", 2008 }, { "350", 2048 }, { "350", 2048 }, { "350", 2048 } } },
    { { { "525", 2884 }, { "525", 2944 }, { "525", 2944 }, { "525", 3072 } } },
    { { { "700", 3760 }, { "700", 3840 }, { "700", 3840 }, { "700", 4095 } } },
}
Definition at line 2077 of file vf_waveform.c.
ire8
const GraticuleLines ire8[] static
Initial value:
= {
    { { {   "0",  16 }, {   "0",  16 }, {   "0",  16 }, {   "0",   0 } } },
    { { {  "25",  71 }, {  "25",  72 }, {  "25",  72 }, {  "25",  64 } } },
    { { {  "50", 126 }, {  "50", 128 }, {  "50", 128 }, {  "50", 128 } } },
    { { {  "75", 180 }, {  "75", 184 }, {  "75", 184 }, {  "75", 192 } } },
    { { { "100", 235 }, { "100", 240 }, { "100", 240 }, { "100", 255 } } },
}
Definition at line 2085 of file vf_waveform.c.
ire9
const GraticuleLines ire9[] static
Initial value:
= {
    { { {   "0",  32 }, {   "0",  32 }, {   "0",  32 }, {   "0",   0 } } },
    { { {  "25", 142 }, {  "25", 144 }, {  "25", 144 }, {  "25", 128 } } },
    { { {  "50", 251 }, {  "50", 256 }, {  "50", 256 }, {  "50", 256 } } },
    { { {  "75", 361 }, {  "75", 368 }, {  "75", 368 }, {  "75", 384 } } },
    { { { "100", 470 }, { "100", 480 }, { "100", 480 }, { "100", 511 } } },
}
Definition at line 2093 of file vf_waveform.c.
ire10
const GraticuleLines ire10[] static
Initial value:
= {
    { { {   "0",  64 }, {   "0",  64 }, {  "0",   64 }, {   "0",    0 } } },
    { { {  "25", 283 }, {  "25", 288 }, {  "25", 288 }, {  "25",  256 } } },
    { { {  "50", 502 }, {  "50", 512 }, {  "50", 512 }, {  "50",  512 } } },
    { { {  "75", 721 }, {  "75", 736 }, {  "75", 736 }, {  "75",  768 } } },
    { { { "100", 940 }, { "100", 960 }, { "100", 960 }, { "100", 1023 } } },
}
Definition at line 2101 of file vf_waveform.c.
ire12
const GraticuleLines ire12[] static
Initial value:
= {
    { { {   "0",  256 }, {   "0",  256 }, {   "0",  256 }, {   "0",    0 } } },
    { { {  "25", 1132 }, {  "25", 1152 }, {  "25", 1152 }, {  "25", 1024 } } },
    { { {  "50", 2008 }, {  "50", 2048 }, {  "50", 2048 }, {  "50", 2048 } } },
    { { {  "75", 2884 }, {  "75", 2944 }, {  "75", 2944 }, {  "75", 3072 } } },
    { { { "100", 3760 }, { "100", 3840 }, { "100", 3840 }, { "100", 4095 } } },
}
Definition at line 2109 of file vf_waveform.c.
chroma_digital8
const GraticuleLines chroma_digital8[] static
Initial value:
= {
    { { {  "50",  50 }, {  "50",  50 }, {  "50",  50 }, {  "50",  50 } } },
    { { { "100", 100 }, { "100", 100 }, { "100", 100 }, { "100", 100 } } },
    { { { "150", 150 }, { "150", 150 }, { "150", 150 }, { "150", 150 } } },
    { { { "200", 200 }, { "200", 200 }, { "200", 200 }, { "200", 200 } } },
    { { { "255", 255 }, { "255", 255 }, { "255", 255 }, { "255", 255 } } },
}
Definition at line 2117 of file vf_waveform.c.
chroma_digital9
const GraticuleLines chroma_digital9[] static
Initial value:
= {
    { { { "100", 100 }, { "100", 100 }, { "100", 100 }, { "100", 100 } } },
    { { { "200", 200 }, { "200", 200 }, { "200", 200 }, { "200", 200 } } },
    { { { "300", 300 }, { "300", 300 }, { "300", 300 }, { "300", 300 } } },
    { { { "400", 400 }, { "400", 400 }, { "400", 400 }, { "400", 400 } } },
    { { { "500", 500 }, { "500", 500 }, { "500", 500 }, { "500", 500 } } },
}
Definition at line 2125 of file vf_waveform.c.
chroma_digital10
const GraticuleLines chroma_digital10[] static
Initial value:
= {
    { { { "200", 200 }, { "200", 200 }, { "200", 200 }, { "200", 200 } } },
    { { { "400", 400 }, { "400", 400 }, { "400", 400 }, { "400", 400 } } },
    { { { "600", 600 }, { "600", 600 }, { "600", 600 }, { "600", 600 } } },
    { { { "800", 800 }, { "800", 800 }, { "800", 800 }, { "800", 800 } } },
    { { {"1000",1000 }, {"1000",1000 }, {"1000",1000 }, {"1000",1000 } } },
}
Definition at line 2133 of file vf_waveform.c.
chroma_digital12
const GraticuleLines chroma_digital12[] static
Initial value:
= {
    { { {  "800",  800 }, {  "800",  800 }, {  "800",  800 }, {  "800",  800 } } },
    { { { "1600", 1600 }, { "1600", 1600 }, { "1600", 1600 }, { "1600", 1600 } } },
    { { { "2400", 2400 }, { "2400", 2400 }, { "2400", 2400 }, { "2400", 2400 } } },
    { { { "3200", 3200 }, { "3200", 3200 }, { "3200", 3200 }, { "3200", 3200 } } },
    { { { "4000", 4000 }, { "4000", 4000 }, { "4000", 4000 }, { "4000", 4000 } } },
}
Definition at line 2141 of file vf_waveform.c.
inputs
const AVFilterPad inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
        .config_props = config_input,
    },
    { NULL }
}
Definition at line 2805 of file vf_waveform.c.
outputs
const AVFilterPad outputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .config_props = config_output,
    },
    { NULL }
}
Definition at line 2815 of file vf_waveform.c.
ff_vf_waveform
AVFilter ff_vf_waveform
Initial value:
= {
    .name          = "waveform",
    .description   = NULL_IF_CONFIG_SMALL("Video waveform monitor."),
    .priv_size     = sizeof(WaveformContext),
    .priv_class    = &waveform_class,
    .query_formats = query_formats,
    .uninit        = uninit,
    .inputs        = inputs,
    .outputs       = outputs,
}
Definition at line 2824 of file vf_waveform.c.