FFmpeg: libavfilter/vf_fspp.c File Reference
vf_fspp.c File Reference
Fast Simple Post-processing filter This implementation is based on an algorithm described in "Aria Nosratinia Embedded Post-Processing for Enhancement of Compressed Images (1999)" (http://www.utdallas.edu/~aria/papers/vlsisp99.pdf) Further, with splitting (I)DCT into horizontal/vertical passes, one of them can be performed once per block, not per pixel.
#include "libavutil/avassert.h"
#include "libavutil/imgutils.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "internal.h"
#include "vf_fspp.h"
Macros
#define OFFSET(x) offsetof(FSPPContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
#define STORE(pos)
#define STORE2(pos)
Functions
AVFILTER_DEFINE_CLASS (fspp)
static void store_slice_c (uint8_t *dst, int16_t *src, ptrdiff_t dst_stride, ptrdiff_t src_stride, ptrdiff_t width, ptrdiff_t height, ptrdiff_t log2_scale)
static void store_slice2_c (uint8_t *dst, int16_t *src, ptrdiff_t dst_stride, ptrdiff_t src_stride, ptrdiff_t width, ptrdiff_t height, ptrdiff_t log2_scale)
static void mul_thrmat_c (int16_t *thr_adr_noq, int16_t *thr_adr, int q)
static void filter (FSPPContext *p, uint8_t *dst, uint8_t *src, int dst_stride, int src_stride, int width, int height, uint8_t *qp_store, int qp_stride, int is_luma)
static void column_fidct_c (int16_t *thr_adr, int16_t *data, int16_t *output, int cnt)
static void row_idct_c (int16_t *workspace, int16_t *output_adr, ptrdiff_t output_stride, int cnt)
static void row_fdct_c (int16_t *data, const uint8_t *pixels, ptrdiff_t line_size, int cnt)
static int query_formats (AVFilterContext *ctx)
static int config_input (AVFilterLink *inlink)
static int filter_frame (AVFilterLink *inlink, AVFrame *in)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const AVOption fspp_options []
static const uint8_t dither [8][8]
static const short custom_threshold [64]
static const AVFilterPad fspp_inputs []
static const AVFilterPad fspp_outputs []
AVFilter ff_vf_fspp
Detailed Description
Fast Simple Post-processing filter This implementation is based on an algorithm described in "Aria Nosratinia Embedded Post-Processing for Enhancement of Compressed Images (1999)" (http://www.utdallas.edu/~aria/papers/vlsisp99.pdf) Further, with splitting (I)DCT into horizontal/vertical passes, one of them can be performed once per block, not per pixel.
This allows for much higher speed.
Originally written by Michael Niedermayer and Nikolaj for the MPlayer project, and ported by Arwa Arif for FFmpeg.
Definition in file vf_fspp.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(FSPPContext, x)
Definition at line 45 of file vf_fspp.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 46 of file vf_fspp.c.
STORE
#define STORE (pos)
Value:
temp = (src[x + pos] + (d[pos] >> log2_scale)) >> (6 - log2_scale);        \
    src[x + pos] = src[x + pos - 8 * src_stride] = 0;                          \
    if (temp & 0x100) temp = ~(temp >> 31);                                    \
    dst[x + pos] = temp;
Referenced by store_slice_c().
STORE2
#define STORE2 (pos)
Value:
temp = (src[x + pos] + src[x + pos + 16 * src_stride] + (d[pos] >> log2_scale)) >> (6 - log2_scale);  \
    src[x + pos + 16 * src_stride] = 0;                                                                   \
    if (temp & 0x100) temp = ~(temp >> 31);                                                               \
    dst[x + pos] = temp;
Referenced by store_slice2_c().
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (fspp)
store_slice_c()
static void store_slice_c (uint8_t * dst, int16_t * src, ptrdiff_t dst_stride, ptrdiff_t src_stride, ptrdiff_t width, ptrdiff_t height, ptrdiff_t log2_scale) static
Definition at line 83 of file vf_fspp.c.
Referenced by config_input().
store_slice2_c()
static void store_slice2_c (uint8_t * dst, int16_t * src, ptrdiff_t dst_stride, ptrdiff_t src_stride, ptrdiff_t width, ptrdiff_t height, ptrdiff_t log2_scale) static
Definition at line 113 of file vf_fspp.c.
Referenced by config_input().
mul_thrmat_c()
static void mul_thrmat_c (int16_t * thr_adr_noq, int16_t * thr_adr, int q) static
Definition at line 142 of file vf_fspp.c.
Referenced by config_input().
filter()
static void filter (FSPPContext * p, uint8_t * dst, uint8_t * src, int dst_stride, int src_stride, int width, int height, uint8_t * qp_store, int qp_stride, int is_luma) static
Definition at line 149 of file vf_fspp.c.
Referenced by filter_frame().
column_fidct_c()
static void column_fidct_c (int16_t * thr_adr, int16_t * data, int16_t * output, int cnt) static
Definition at line 247 of file vf_fspp.c.
Referenced by config_input().
row_idct_c()
static void row_idct_c (int16_t * workspace, int16_t * output_adr, ptrdiff_t output_stride, int cnt) static
Definition at line 370 of file vf_fspp.c.
Referenced by config_input().
row_fdct_c()
static void row_fdct_c (int16_t * data, const uint8_t * pixels, ptrdiff_t line_size, int cnt) static
Definition at line 432 of file vf_fspp.c.
Referenced by config_input().
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 493 of file vf_fspp.c.
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 511 of file vf_fspp.c.
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 548 of file vf_fspp.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 657 of file vf_fspp.c.
Variable Documentation
fspp_options
const AVOption fspp_options[] static
Initial value:
= {
    { "quality",       "set quality",                          OFFSET(log2_count),    AV_OPT_TYPE_INT, {.i64 = 4},   4, MAX_LEVEL, FLAGS },
    { "qp",            "force a constant quantizer parameter", OFFSET(qp),            AV_OPT_TYPE_INT, {.i64 = 0},   0, 64,        FLAGS },
    { "strength",      "set filter strength",                  OFFSET(strength),      AV_OPT_TYPE_INT, {.i64 = 0}, -15, 32,        FLAGS },
    { "use_bframe_qp", "use B-frames' QP",                     OFFSET(use_bframe_qp), AV_OPT_TYPE_BOOL,{.i64 = 0},   0, 1,         FLAGS },
    { NULL }
}
Definition at line 47 of file vf_fspp.c.
dither
const uint8_t dither[8][8] static
Initial value:
= {
    {  0,  48,  12,  60,   3,  51,  15,  63, },
    { 32,  16,  44,  28,  35,  19,  47,  31, },
    {  8,  56,   4,  52,  11,  59,   7,  55, },
    { 40,  24,  36,  20,  43,  27,  39,  23, },
    {  2,  50,  14,  62,   1,  49,  13,  61, },
    { 34,  18,  46,  30,  33,  17,  45,  29, },
    { 10,  58,   6,  54,   9,  57,   5,  53, },
    { 42,  26,  38,  22,  41,  25,  37,  21, },
}
Definition at line 57 of file vf_fspp.c.
Referenced by ac3_decode_transform_coeffs_ch(), encode_frame(), quantize_triangular_ns(), render_charset(), rv40_loop_filter(), store_slice2_c(), store_slice_c(), and yuv2yuvX().
custom_threshold
const short custom_threshold[64] static
Initial value:
= {
     71, 296, 295, 237,  71,  40,  38,  19,
    245, 193, 185, 121, 102,  73,  53,  27,
    158, 129, 141, 107,  97,  73,  50,  26,
    102, 116, 109,  98,  82,  66,  45,  23,
     71,  94,  95,  81,  70,  56,  38,  20,
     56,  77,  74,  66,  56,  44,  30,  15,
     38,  53,  50,  45,  38,  30,  21,  11,
     20,  27,  26,  23,  20,  15,  11,   5
}
Definition at line 68 of file vf_fspp.c.
Referenced by filter_frame().
fspp_inputs
const AVFilterPad fspp_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .config_props = config_input,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 665 of file vf_fspp.c.
fspp_outputs
const AVFilterPad fspp_outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_VIDEO,
    },
    { NULL }
}
Definition at line 675 of file vf_fspp.c.
ff_vf_fspp
AVFilter ff_vf_fspp
Initial value:
= {
    .name            = "fspp",
    .description     = NULL_IF_CONFIG_SMALL("Apply Fast Simple Post-processing filter."),
    .priv_size       = sizeof(FSPPContext),
    .uninit          = uninit,
    .query_formats   = query_formats,
    .inputs          = fspp_inputs,
    .outputs         = fspp_outputs,
    .priv_class      = &fspp_class,
    .flags           = AVFILTER_FLAG_SUPPORT_TIMELINE_INTERNAL,
}
Definition at line 683 of file vf_fspp.c.