FFmpeg: libavfilter/vf_displace.c File Reference
vf_displace.c File Reference
#include "libavutil/imgutils.h"
#include "libavutil/pixdesc.h"
#include "libavutil/opt.h"
#include "avfilter.h"
#include "formats.h"
#include "framesync.h"
#include "internal.h"
#include "video.h"
Data Structures
struct DisplaceContext
Macros
#define OFFSET(x) offsetof(DisplaceContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Enumerations
enum EdgeMode { EDGE_BLANK, EDGE_SMEAR, EDGE_WRAP, EDGE_NB }
Functions
AVFILTER_DEFINE_CLASS (displace)
static int query_formats (AVFilterContext *ctx)
static void displace_planar (DisplaceContext *s, const AVFrame *in, const AVFrame *xpic, const AVFrame *ypic, AVFrame *out)
static void displace_packed (DisplaceContext *s, const AVFrame *in, const AVFrame *xpic, const AVFrame *ypic, AVFrame *out)
static int process_frame (FFFrameSync *fs)
static int config_input (AVFilterLink *inlink)
static int config_output (AVFilterLink *outlink)
static int filter_frame (AVFilterLink *inlink, AVFrame *buf)
static int request_frame (AVFilterLink *outlink)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const AVOption displace_options []
static const AVFilterPad displace_inputs []
static const AVFilterPad displace_outputs []
AVFilter ff_vf_displace
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(DisplaceContext, x)
Definition at line 51 of file vf_displace.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 52 of file vf_displace.c.
Enumeration Type Documentation
EdgeMode
enum EdgeMode
Enumerator
EDGE_BLANK
EDGE_SMEAR
EDGE_WRAP
EDGE_NB
Definition at line 30 of file vf_displace.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (displace)
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 64 of file vf_displace.c.
displace_planar()
static void displace_planar (DisplaceContext * s, const AVFrame * in, const AVFrame * xpic, const AVFrame * ypic, AVFrame * out) static
Definition at line 82 of file vf_displace.c.
Referenced by config_input().
displace_packed()
static void displace_packed (DisplaceContext * s, const AVFrame * in, const AVFrame * xpic, const AVFrame * ypic, AVFrame * out) static
Definition at line 142 of file vf_displace.c.
Referenced by config_input().
process_frame()
static int process_frame (FFFrameSync * fs) static
Definition at line 207 of file vf_displace.c.
Referenced by config_output().
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 237 of file vf_displace.c.
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 268 of file vf_displace.c.
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * buf) static
Definition at line 336 of file vf_displace.c.
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 342 of file vf_displace.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 348 of file vf_displace.c.
Variable Documentation
displace_options
const AVOption displace_options[] static
Initial value:
= {
    { "edge", "set edge mode", OFFSET(edge), AV_OPT_TYPE_INT, {.i64=EDGE_SMEAR}, 0, EDGE_NB-1, FLAGS, "edge" },
    {   "blank", "", 0, AV_OPT_TYPE_CONST, {.i64=EDGE_BLANK}, 0, 0, FLAGS, "edge" },
    {   "smear", "", 0, AV_OPT_TYPE_CONST, {.i64=EDGE_SMEAR}, 0, 0, FLAGS, "edge" },
    {   "wrap" , "", 0, AV_OPT_TYPE_CONST, {.i64=EDGE_WRAP},  0, 0, FLAGS, "edge" },
    { NULL }
}
Definition at line 54 of file vf_displace.c.
displace_inputs
const AVFilterPad displace_inputs[] static
Initial value:
= {
    {
        .name         = "source",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
        .config_props = config_input,
    },
    {
        .name         = "xmap",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
    },
    {
        .name         = "ymap",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 355 of file vf_displace.c.
displace_outputs
const AVFilterPad displace_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .config_props  = config_output,
        .request_frame = request_frame,
    },
    { NULL }
}
Definition at line 375 of file vf_displace.c.
ff_vf_displace
AVFilter ff_vf_displace
Initial value:
= {
    .name          = "displace",
    .description   = NULL_IF_CONFIG_SMALL("Displace pixels."),
    .priv_size     = sizeof(DisplaceContext),
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = displace_inputs,
    .outputs       = displace_outputs,
    .priv_class    = &displace_class,
    .flags         = AVFILTER_FLAG_SUPPORT_TIMELINE_INTERNAL,
}
Definition at line 385 of file vf_displace.c.