FFmpeg: libavfilter/vf_find_rect.c File Reference
vf_find_rect.c File Reference
#include "libavutil/avassert.h"
#include "libavutil/imgutils.h"
#include "libavutil/opt.h"
#include "internal.h"
#include "lavfutils.h"
Data Structures
struct FOCContext
Macros
#define MAX_MIPMAPS 5
#define OFFSET(x) offsetof(FOCContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Functions
AVFILTER_DEFINE_CLASS (find_rect)
static int query_formats (AVFilterContext *ctx)
static AVFrame * downscale (AVFrame *in)
static float compare (const AVFrame *haystack, const AVFrame *obj, int offx, int offy)
static int config_input (AVFilterLink *inlink)
static float search (FOCContext *foc, int pass, int maxpass, int xmin, int xmax, int ymin, int ymax, int *best_x, int *best_y, float best_score)
static int filter_frame (AVFilterLink *inlink, AVFrame *in)
static av_cold void uninit (AVFilterContext *ctx)
static av_cold int init (AVFilterContext *ctx)
Variables
static const AVOption find_rect_options []
static const AVFilterPad foc_inputs []
static const AVFilterPad foc_outputs []
AVFilter ff_vf_find_rect
Macro Definition Documentation
MAX_MIPMAPS
#define MAX_MIPMAPS 5
Todo:
switch to dualinput
Definition at line 32 of file vf_find_rect.c.
Referenced by filter_frame(), and uninit().
OFFSET
#define OFFSET (x) offsetof(FOCContext, x)
Definition at line 46 of file vf_find_rect.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 47 of file vf_find_rect.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (find_rect)
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 61 of file vf_find_rect.c.
downscale()
static AVFrame* downscale (AVFrame * in) static
Definition at line 72 of file vf_find_rect.c.
Referenced by filter_frame(), and init().
compare()
static float compare (const AVFrame * haystack, const AVFrame * obj, int offx, int offy) static
Definition at line 105 of file vf_find_rect.c.
Referenced by ff_interleave_add_packet(), and search().
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 143 of file vf_find_rect.c.
search()
static float search (FOCContext * foc, int pass, int maxpass, int xmin, int xmax, int ymin, int ymax, int * best_x, int * best_y, float best_score) static
Definition at line 156 of file vf_find_rect.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 183 of file vf_find_rect.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 228 of file vf_find_rect.c.
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 243 of file vf_find_rect.c.
Variable Documentation
find_rect_options
const AVOption find_rect_options[] static
Initial value:
= {
    { "object", "object bitmap filename", OFFSET(obj_filename), AV_OPT_TYPE_STRING, {.str = NULL}, .flags = FLAGS },
    { "threshold", "set threshold", OFFSET(threshold), AV_OPT_TYPE_FLOAT, {.dbl = 0.5}, 0, 1.0, FLAGS },
    { "mipmaps", "set mipmaps", OFFSET(mipmaps), AV_OPT_TYPE_INT, {.i64 = 3}, 1, MAX_MIPMAPS, FLAGS },
    { "xmin", "", OFFSET(xmin), AV_OPT_TYPE_INT, {.i64 = 0}, 0, INT_MAX, FLAGS },
    { "ymin", "", OFFSET(ymin), AV_OPT_TYPE_INT, {.i64 = 0}, 0, INT_MAX, FLAGS },
    { "xmax", "", OFFSET(xmax), AV_OPT_TYPE_INT, {.i64 = 0}, 0, INT_MAX, FLAGS },
    { "ymax", "", OFFSET(ymax), AV_OPT_TYPE_INT, {.i64 = 0}, 0, INT_MAX, FLAGS },
    { NULL }
}
Definition at line 48 of file vf_find_rect.c.
foc_inputs
const AVFilterPad foc_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .config_props = config_input,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 277 of file vf_find_rect.c.
foc_outputs
const AVFilterPad foc_outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_VIDEO,
    },
    { NULL }
}
Definition at line 287 of file vf_find_rect.c.
ff_vf_find_rect
AVFilter ff_vf_find_rect
Initial value:
= {
    .name            = "find_rect",
    .description     = NULL_IF_CONFIG_SMALL("Find a user specified object."),
    .priv_size       = sizeof(FOCContext),
    .init            = init,
    .uninit          = uninit,
    .query_formats   = query_formats,
    .inputs          = foc_inputs,
    .outputs         = foc_outputs,
    .priv_class      = &find_rect_class,
}
Definition at line 295 of file vf_find_rect.c.