FFmpeg: libavfilter/vf_lut3d.c File Reference
vf_lut3d.c File Reference
3D Lookup table filter
#include "libavutil/opt.h"
#include "libavutil/file.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/avassert.h"
#include "libavutil/pixdesc.h"
#include "libavutil/avstring.h"
#include "avfilter.h"
#include "drawutils.h"
#include "dualinput.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
Data Structures
struct rgbvec
struct LUT3DContext
struct ThreadData
Macros
#define R 0
#define G 1
#define B 2
#define A 3
#define MAX_LEVEL 64
#define OFFSET(x) offsetof(LUT3DContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
#define COMMON_OPTIONS
#define NEAR(x) ((int)((x) + .5))
#define PREV(x) ((int)(x))
#define NEXT(x) (FFMIN((int)(x) + 1, lut3d->lutsize - 1))
#define DEFINE_INTERP_FUNC(name, nbits)
#define MAX_LINE_SIZE 512
#define NEXT_LINE(loop_cond)
#define SET_COLOR(id)
#define SET_FUNC(name)
Enumerations
enum interp_mode { INTERPOLATE_NEAREST, INTERPOLATE_TRILINEAR, INTERPOLATE_TETRAHEDRAL, NB_INTERP_MODE }
Functions
static float lerpf (float v0, float v1, float f)
static struct rgbvec lerp (const struct rgbvec *v0, const struct rgbvec *v1, float f)
static struct rgbvec interp_nearest (const LUT3DContext *lut3d, const struct rgbvec *s)
Get the nearest defined point.
static struct rgbvec interp_trilinear (const LUT3DContext *lut3d, const struct rgbvec *s)
Interpolate using the 8 vertices of a cube.
static struct rgbvec interp_tetrahedral (const LUT3DContext *lut3d, const struct rgbvec *s)
Tetrahedral interpolation.
static int skip_line (const char *p)
static int parse_dat (AVFilterContext *ctx, FILE *f)
static int parse_cube (AVFilterContext *ctx, FILE *f)
static int parse_3dl (AVFilterContext *ctx, FILE *f)
static int parse_m3d (AVFilterContext *ctx, FILE *f)
static void set_identity_matrix (LUT3DContext *lut3d, int size)
static int query_formats (AVFilterContext *ctx)
static int config_input (AVFilterLink *inlink)
static AVFrame * apply_lut (AVFilterLink *inlink, AVFrame *in)
static int filter_frame (AVFilterLink *inlink, AVFrame *in)
Detailed Description
3D Lookup table filter
Definition in file vf_lut3d.c.
Macro Definition Documentation
R
#define R 0
Definition at line 39 of file vf_lut3d.c.
G
#define G 1
Definition at line 40 of file vf_lut3d.c.
B
#define B 2
Definition at line 41 of file vf_lut3d.c.
A
#define A 3
Definition at line 42 of file vf_lut3d.c.
MAX_LEVEL
#define MAX_LEVEL 64
Definition at line 57 of file vf_lut3d.c.
Referenced by filter_frame(), parse_cube(), parse_dat(), and parse_m3d().
OFFSET
#define OFFSET (x) offsetof(LUT3DContext, x)
Definition at line 81 of file vf_lut3d.c.
Referenced by filter_frame().
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 82 of file vf_lut3d.c.
Referenced by filter_frame().
COMMON_OPTIONS
#define COMMON_OPTIONS
Value:
{ "interp", "select interpolation mode", OFFSET(interpolation), AV_OPT_TYPE_INT, {.i64=INTERPOLATE_TETRAHEDRAL}, 0, NB_INTERP_MODE-1, FLAGS, "interp_mode" }, \
        { "nearest",     "use values from the nearest defined points",            0, AV_OPT_TYPE_CONST, {.i64=INTERPOLATE_NEAREST},     INT_MIN, INT_MAX, FLAGS, "interp_mode" }, \
        { "trilinear",   "interpolate values using the 8 points defining a cube", 0, AV_OPT_TYPE_CONST, {.i64=INTERPOLATE_TRILINEAR},   INT_MIN, INT_MAX, FLAGS, "interp_mode" }, \
        { "tetrahedral", "interpolate values using a tetrahedron",                0, AV_OPT_TYPE_CONST, {.i64=INTERPOLATE_TETRAHEDRAL}, INT_MIN, INT_MAX, FLAGS, "interp_mode" }, \
    { NULL }
Definition at line 83 of file vf_lut3d.c.
Referenced by filter_frame().
NEAR
#define NEAR (x) ((int)((x) + .5))
Definition at line 103 of file vf_lut3d.c.
Referenced by interp_nearest().
PREV
#define PREV (x) ((int)(x))
Definition at line 104 of file vf_lut3d.c.
Referenced by interp_tetrahedral(), interp_trilinear(), and tempNoiseReducer().
NEXT
#define NEXT (x) (FFMIN((int)(x) + 1, lut3d->lutsize - 1))
Definition at line 105 of file vf_lut3d.c.
Referenced by interp_tetrahedral(), interp_trilinear(), and tempNoiseReducer().
DEFINE_INTERP_FUNC
#define DEFINE_INTERP_FUNC (name, nbits)
Definition at line 201 of file vf_lut3d.c.
MAX_LINE_SIZE
#define MAX_LINE_SIZE 512
Definition at line 249 of file vf_lut3d.c.
Referenced by parse_3dl(), parse_cube(), parse_dat(), and parse_m3d().
NEXT_LINE
#define NEXT_LINE (loop_cond)
Value:
do {                           \
    if (!fgets(line, sizeof(line), f)) {                    \
        av_log(ctx, AV_LOG_ERROR, "Unexpected EOF\n");      \
        return AVERROR_INVALIDDATA;                         \
    }                                                       \
} while (loop_cond)
Definition at line 258 of file vf_lut3d.c.
Referenced by parse_3dl(), parse_cube(), parse_dat(), and parse_m3d().
SET_COLOR
#define SET_COLOR (id)
Value:
do {                  \
    while (av_isspace(*p))                  \
        p++;                                \
    switch (*p) {                           \
    case 'r': rgb_map[id] = 0; break;       \
    case 'g': rgb_map[id] = 1; break;       \
    case 'b': rgb_map[id] = 2; break;       \
    }                                       \
    while (*p && !av_isspace(*p))           \
        p++;                                \
} while (0)
Referenced by parse_m3d().
SET_FUNC
#define SET_FUNC (name)
Value:
do {                             \
    if (is16bit) lut3d->interp = interp_16_##name;      \
    else         lut3d->interp = interp_8_##name;       \
} while (0)
Referenced by config_input().
Enumeration Type Documentation
interp_mode
enum interp_mode
Enumerator
INTERPOLATE_NEAREST
INTERPOLATE_TRILINEAR
INTERPOLATE_TETRAHEDRAL
NB_INTERP_MODE
Definition at line 44 of file vf_lut3d.c.
Function Documentation
lerpf()
static float lerpf (float v0, float v1, float f) inline static
Definition at line 90 of file vf_lut3d.c.
Referenced by lerp().
lerp()
static struct rgbvec lerp (const struct rgbvec * v0, const struct rgbvec * v1, float f) static
Definition at line 95 of file vf_lut3d.c.
Referenced by interp_trilinear().
interp_nearest()
static struct rgbvec interp_nearest (const LUT3DContext * lut3d, const struct rgbvec * s) static
Get the nearest defined point.
Definition at line 110 of file vf_lut3d.c.
interp_trilinear()
static struct rgbvec interp_trilinear (const LUT3DContext * lut3d, const struct rgbvec * s) static
Interpolate using the 8 vertices of a cube.
See also
https://en.wikipedia.org/wiki/Trilinear_interpolation
Definition at line 120 of file vf_lut3d.c.
interp_tetrahedral()
static struct rgbvec interp_tetrahedral (const LUT3DContext * lut3d, const struct rgbvec * s) static
Tetrahedral interpolation.
Based on code found in Truelight Software Library paper.
See also
http://www.filmlight.ltd.uk/pdf/whitepapers/FL-TL-TN-0057-SoftwareLib.pdf
Definition at line 148 of file vf_lut3d.c.
skip_line()
static int skip_line (const char * p) static
Definition at line 251 of file vf_lut3d.c.
Referenced by parse_3dl(), parse_cube(), and parse_dat().
parse_dat()
static int parse_dat (AVFilterContext * ctx, FILE * f) static
Definition at line 267 of file vf_lut3d.c.
Referenced by filter_frame().
parse_cube()
static int parse_cube (AVFilterContext * ctx, FILE * f) static
Definition at line 300 of file vf_lut3d.c.
Referenced by filter_frame().
parse_3dl()
static int parse_3dl (AVFilterContext * ctx, FILE * f) static
Definition at line 352 of file vf_lut3d.c.
Referenced by filter_frame().
parse_m3d()
static int parse_m3d (AVFilterContext * ctx, FILE * f) static
Definition at line 381 of file vf_lut3d.c.
Referenced by filter_frame().
set_identity_matrix()
static void set_identity_matrix (LUT3DContext * lut3d, int size) static
Definition at line 444 of file vf_lut3d.c.
Referenced by filter_frame().
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 462 of file vf_lut3d.c.
Referenced by filter_frame().
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 480 of file vf_lut3d.c.
Referenced by filter_frame().
apply_lut()
static AVFrame* apply_lut (AVFilterLink * inlink, AVFrame * in) static
Definition at line 513 of file vf_lut3d.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 542 of file vf_lut3d.c.