FFmpeg: libavfilter/x86/vf_tinterlace_init.c File Reference
vf_tinterlace_init.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/internal.h"
#include "libavutil/mem.h"
#include "libavutil/x86/asm.h"
#include "libavutil/x86/cpu.h"
#include "libavfilter/tinterlace.h"
Functions
void ff_lowpass_line_sse2 (uint8_t *dstp, ptrdiff_t linesize, const uint8_t *srcp, const uint8_t *srcp_above, const uint8_t *srcp_below)
void ff_lowpass_line_avx (uint8_t *dstp, ptrdiff_t linesize, const uint8_t *srcp, const uint8_t *srcp_above, const uint8_t *srcp_below)
av_cold void ff_tinterlace_init_x86 (TInterlaceContext *s)
Function Documentation
ff_lowpass_line_sse2()
void ff_lowpass_line_sse2 (uint8_t * dstp, ptrdiff_t linesize, const uint8_t * srcp, const uint8_t * srcp_above, const uint8_t * srcp_below)
Referenced by ff_tinterlace_init_x86().
ff_lowpass_line_avx()
void ff_lowpass_line_avx (uint8_t * dstp, ptrdiff_t linesize, const uint8_t * srcp, const uint8_t * srcp_above, const uint8_t * srcp_below)
Referenced by ff_tinterlace_init_x86().
ff_tinterlace_init_x86()
av_cold void ff_tinterlace_init_x86 (TInterlaceContext * s)
Definition at line 39 of file vf_tinterlace_init.c.
Referenced by config_out_props().