FFmpeg: libavfilter/vf_fps.c File Reference
vf_fps.c File Reference
a filter enforcing given constant framerate
#include <float.h>
#include <stdint.h>
#include "libavutil/common.h"
#include "libavutil/fifo.h"
#include "libavutil/mathematics.h"
#include "libavutil/opt.h"
#include "libavutil/parseutils.h"
#include "avfilter.h"
#include "internal.h"
#include "video.h"
Data Structures
struct FPSContext
Macros
#define OFFSET(x) offsetof(FPSContext, x)
#define V AV_OPT_FLAG_VIDEO_PARAM
#define F AV_OPT_FLAG_FILTERING_PARAM
Functions
AVFILTER_DEFINE_CLASS (fps)
static av_cold int init (AVFilterContext *ctx)
static void flush_fifo (AVFifoBuffer *fifo)
static av_cold void uninit (AVFilterContext *ctx)
static int config_props (AVFilterLink *link)
static int request_frame (AVFilterLink *outlink)
static int write_to_fifo (AVFifoBuffer *fifo, AVFrame *buf)
static int filter_frame (AVFilterLink *inlink, AVFrame *buf)
Variables
static const AVOption fps_options []
static const AVFilterPad avfilter_vf_fps_inputs []
static const AVFilterPad avfilter_vf_fps_outputs []
AVFilter ff_vf_fps
Detailed Description
a filter enforcing given constant framerate
Definition in file vf_fps.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(FPSContext, x)
Definition at line 61 of file vf_fps.c.
V
#define V AV_OPT_FLAG_VIDEO_PARAM
Definition at line 62 of file vf_fps.c.
F
#define F AV_OPT_FLAG_FILTERING_PARAM
Definition at line 63 of file vf_fps.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (fps)
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 78 of file vf_fps.c.
flush_fifo()
static void flush_fifo (AVFifoBuffer * fifo) static
Definition at line 91 of file vf_fps.c.
Referenced by filter_frame(), and uninit().
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 100 of file vf_fps.c.
config_props()
static int config_props (AVFilterLink * link) static
Definition at line 113 of file vf_fps.c.
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 125 of file vf_fps.c.
write_to_fifo()
static int write_to_fifo (AVFifoBuffer * fifo, AVFrame * buf) static
Definition at line 154 of file vf_fps.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * buf) static
Definition at line 168 of file vf_fps.c.
Variable Documentation
fps_options
const AVOption fps_options[] static
Initial value:
= {
    { "fps", "A string describing desired output framerate", OFFSET(framerate), AV_OPT_TYPE_VIDEO_RATE, { .str = "25" }, 0, INT_MAX, V|F },
    { "start_time", "Assume the first PTS should be this value.", OFFSET(start_time), AV_OPT_TYPE_DOUBLE, { .dbl = DBL_MAX}, -DBL_MAX, DBL_MAX, V },
    { "round", "set rounding method for timestamps", OFFSET(rounding), AV_OPT_TYPE_INT, { .i64 = AV_ROUND_NEAR_INF }, 0, 5, V|F, "round" },
    { "zero", "round towards 0",      OFFSET(rounding), AV_OPT_TYPE_CONST, { .i64 = AV_ROUND_ZERO     }, 0, 5, V|F, "round" },
    { "inf",  "round away from 0",    OFFSET(rounding), AV_OPT_TYPE_CONST, { .i64 = AV_ROUND_INF      }, 0, 5, V|F, "round" },
    { "down", "round towards -infty", OFFSET(rounding), AV_OPT_TYPE_CONST, { .i64 = AV_ROUND_DOWN     }, 0, 5, V|F, "round" },
    { "up",   "round towards +infty", OFFSET(rounding), AV_OPT_TYPE_CONST, { .i64 = AV_ROUND_UP       }, 0, 5, V|F, "round" },
    { "near", "round to nearest",     OFFSET(rounding), AV_OPT_TYPE_CONST, { .i64 = AV_ROUND_NEAR_INF }, 0, 5, V|F, "round" },
    { NULL }
}
Definition at line 64 of file vf_fps.c.
avfilter_vf_fps_inputs
const AVFilterPad avfilter_vf_fps_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 267 of file vf_fps.c.
avfilter_vf_fps_outputs
const AVFilterPad avfilter_vf_fps_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .request_frame = request_frame,
        .config_props  = config_props
    },
    { NULL }
}
Definition at line 276 of file vf_fps.c.
ff_vf_fps
AVFilter ff_vf_fps
Initial value:
= {
    .name        = "fps",
    .description = NULL_IF_CONFIG_SMALL("Force constant framerate."),
    .init        = init,
    .uninit      = uninit,
    .priv_size   = sizeof(FPSContext),
    .priv_class  = &fps_class,
    .inputs      = avfilter_vf_fps_inputs,
    .outputs     = avfilter_vf_fps_outputs,
}
Definition at line 286 of file vf_fps.c.