FFmpeg: libavfilter/vf_paletteuse.c File Reference
vf_paletteuse.c File Reference
Use a palette to downsample an input video stream.
#include "libavutil/bprint.h"
#include "libavutil/internal.h"
#include "libavutil/opt.h"
#include "libavutil/qsort.h"
#include "dualinput.h"
#include "avfilter.h"
Data Structures
struct color_node
struct cached_color
struct cache_node
struct PaletteUseContext
struct nearest_color
struct stack_node
struct color
struct color_rect
Macros
#define NBITS 5
#define CACHE_SIZE (1<<(3*NBITS))
#define OFFSET(x) offsetof(PaletteUseContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
#define COLORMAP_NEAREST(search, palette, root, target)
#define INDENT 4
#define DECLARE_CMP_FUNC(name, pos)
#define DEFINE_SET_FRAME(color_search, name, value)
#define DEFINE_SET_FRAME_COLOR_SEARCH(color_search, color_search_macro)
#define DITHERING_ENTRIES(color_search)
Typedefs
typedef int(* set_frame_func) (struct PaletteUseContext *s, AVFrame *out, AVFrame *in, int x_start, int y_start, int width, int height)
typedef int(* cmp_func) (const void *, const void *)
Enumerations
enum dithering_mode {
DITHERING_NONE, DITHERING_BAYER, DITHERING_HECKBERT, DITHERING_FLOYD_STEINBERG,
DITHERING_SIERRA2, DITHERING_SIERRA2_4A, NB_DITHERING
}
enum color_search_method { COLOR_SEARCH_NNS_ITERATIVE, COLOR_SEARCH_NNS_RECURSIVE, COLOR_SEARCH_BRUTEFORCE, NB_COLOR_SEARCHES }
enum diff_mode { DIFF_MODE_NONE, DIFF_MODE_RECTANGLE, NB_DIFF_MODE }
Functions
AVFILTER_DEFINE_CLASS (paletteuse)
static int query_formats (AVFilterContext *ctx)
static av_always_inline int dither_color (uint32_t px, int er, int eg, int eb, int scale, int shift)
static av_always_inline int diff (const uint8_t *c1, const uint8_t *c2)
static av_always_inline uint8_t colormap_nearest_bruteforce (const uint32_t *palette, const uint8_t *rgb)
static void colormap_nearest_node (const struct color_node *map, const int node_pos, const uint8_t *target, struct nearest_color *nearest)
static av_always_inline uint8_t colormap_nearest_recursive (const struct color_node *node, const uint8_t *rgb)
static av_always_inline uint8_t colormap_nearest_iterative (const struct color_node *root, const uint8_t *target)
static av_always_inline int color_get (struct cache_node *cache, uint32_t color, uint8_t r, uint8_t g, uint8_t b, const struct color_node *map, const uint32_t *palette, const enum color_search_method search_method)
Check if the requested color is in the cache already.
static av_always_inline int get_dst_color_err (struct cache_node *cache, uint32_t c, const struct color_node *map, const uint32_t *palette, int *er, int *eg, int *eb, const enum color_search_method search_method)
static av_always_inline int set_frame (PaletteUseContext *s, AVFrame *out, AVFrame *in, int x_start, int y_start, int w, int h, enum dithering_mode dither, const enum color_search_method search_method)
static void disp_node (AVBPrint *buf, const struct color_node *map, int parent_id, int node_id, int depth)
static int disp_tree (const struct color_node *node, const char *fname)
static int debug_accuracy (const struct color_node *node, const uint32_t *palette, const enum color_search_method search_method)
static int get_next_color (const uint8_t *color_used, const uint32_t *palette, int *component, const struct color_rect *box)
static int colormap_insert (struct color_node *map, uint8_t *color_used, int *nb_used, const uint32_t *palette, const struct color_rect *box)
static int cmp_pal_entry (const void *a, const void *b)
static void load_colormap (PaletteUseContext *s)
static void debug_mean_error (PaletteUseContext *s, const AVFrame *in1, const AVFrame *in2, int frame_count)
static void set_processing_window (enum diff_mode diff_mode, const AVFrame *prv_src, const AVFrame *cur_src, const AVFrame *prv_dst, AVFrame *cur_dst, int *xp, int *yp, int *wp, int *hp)
static AVFrame * apply_palette (AVFilterLink *inlink, AVFrame *in)
static int config_output (AVFilterLink *outlink)
static int config_input_palette (AVFilterLink *inlink)
static void load_palette (PaletteUseContext *s, const AVFrame *palette_frame)
static AVFrame * load_apply_palette (AVFilterContext *ctx, AVFrame *main, const AVFrame *second)
static int filter_frame (AVFilterLink *inlink, AVFrame *in)
static int dither_value (int p)
static av_cold int init (AVFilterContext *ctx)
static int request_frame (AVFilterLink *outlink)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const AVOption paletteuse_options []
static const cmp_func cmp_funcs [] = {cmp_r, cmp_g, cmp_b}
static const set_frame_func set_frame_lut [NB_COLOR_SEARCHES][NB_DITHERING]
static const AVFilterPad paletteuse_inputs []
static const AVFilterPad paletteuse_outputs []
AVFilter ff_vf_paletteuse
Detailed Description
Use a palette to downsample an input video stream.
Definition in file vf_paletteuse.c.
Macro Definition Documentation
NBITS
#define NBITS 5
Definition at line 63 of file vf_paletteuse.c.
Referenced by color_get().
CACHE_SIZE
#define CACHE_SIZE (1<<(3*NBITS))
Definition at line 64 of file vf_paletteuse.c.
Referenced by load_palette(), and uninit().
OFFSET
#define OFFSET (x) offsetof(PaletteUseContext, x)
Definition at line 105 of file vf_paletteuse.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 106 of file vf_paletteuse.c.
COLORMAP_NEAREST
#define COLORMAP_NEAREST (search, palette, root, target)
Value:
search == COLOR_SEARCH_NNS_ITERATIVE ? colormap_nearest_iterative(root, target) :      \
    search == COLOR_SEARCH_NNS_RECURSIVE ? colormap_nearest_recursive(root, target) :      \
                                           colormap_nearest_bruteforce(palette, target)
Definition at line 313 of file vf_paletteuse.c.
Referenced by color_get(), and debug_accuracy().
INDENT
#define INDENT 4
Definition at line 481 of file vf_paletteuse.c.
Referenced by disp_node().
DECLARE_CMP_FUNC
#define DECLARE_CMP_FUNC (name, pos)
Value:
static int cmp_##name(const void *pa, const void *pb)   \
{                                                       \
    const struct color *a = pa;                         \
    const struct color *b = pb;                         \
    return   (a->value >> (8 * (2 - (pos))) & 0xff)     \
           - (b->value >> (8 * (2 - (pos))) & 0xff);    \
}
Definition at line 578 of file vf_paletteuse.c.
DEFINE_SET_FRAME
#define DEFINE_SET_FRAME (color_search, name, value)
Value:
static int set_frame_##name(PaletteUseContext *s, AVFrame *out, AVFrame *in,    \
                            int x_start, int y_start, int w, int h)             \
{                                                                               \
    return set_frame(s, out, in, x_start, y_start, w, h, value, color_search);  \
}
Definition at line 971 of file vf_paletteuse.c.
DEFINE_SET_FRAME_COLOR_SEARCH
#define DEFINE_SET_FRAME_COLOR_SEARCH (color_search, color_search_macro)
Value:
DEFINE_SET_FRAME(color_search_macro, color_search##_##none,            DITHERING_NONE)              \
    DEFINE_SET_FRAME(color_search_macro, color_search##_##bayer,           DITHERING_BAYER)             \
    DEFINE_SET_FRAME(color_search_macro, color_search##_##heckbert,        DITHERING_HECKBERT)          \
    DEFINE_SET_FRAME(color_search_macro, color_search##_##floyd_steinberg, DITHERING_FLOYD_STEINBERG)   \
    DEFINE_SET_FRAME(color_search_macro, color_search##_##sierra2,         DITHERING_SIERRA2)           \
    DEFINE_SET_FRAME(color_search_macro, color_search##_##sierra2_4a,      DITHERING_SIERRA2_4A)        \
Definition at line 978 of file vf_paletteuse.c.
DITHERING_ENTRIES
#define DITHERING_ENTRIES (color_search)
Value:
{       \
    set_frame_##color_search##_none,            \
    set_frame_##color_search##_bayer,           \
    set_frame_##color_search##_heckbert,        \
    set_frame_##color_search##_floyd_steinberg, \
    set_frame_##color_search##_sierra2,         \
    set_frame_##color_search##_sierra2_4a,      \
}
Definition at line 990 of file vf_paletteuse.c.
Typedef Documentation
set_frame_func
typedef int(* set_frame_func) (struct PaletteUseContext *s, AVFrame *out, AVFrame *in, int x_start, int y_start, int width, int height)
Definition at line 78 of file vf_paletteuse.c.
cmp_func
typedef int(* cmp_func) (const void *, const void *)
Definition at line 576 of file vf_paletteuse.c.
Enumeration Type Documentation
dithering_mode
enum dithering_mode
Enumerator
DITHERING_NONE
DITHERING_BAYER
DITHERING_HECKBERT
DITHERING_FLOYD_STEINBERG
DITHERING_SIERRA2
DITHERING_SIERRA2_4A
NB_DITHERING
Definition at line 33 of file vf_paletteuse.c.
color_search_method
enum color_search_method
Enumerator
COLOR_SEARCH_NNS_ITERATIVE
COLOR_SEARCH_NNS_RECURSIVE
COLOR_SEARCH_BRUTEFORCE
NB_COLOR_SEARCHES
Definition at line 43 of file vf_paletteuse.c.
diff_mode
enum diff_mode
Enumerator
DIFF_MODE_NONE
DIFF_MODE_RECTANGLE
NB_DIFF_MODE
Definition at line 50 of file vf_paletteuse.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (paletteuse)
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 132 of file vf_paletteuse.c.
dither_color()
static av_always_inline int dither_color (uint32_t px, int er, int eg, int eb, int scale, int shift) static
Definition at line 154 of file vf_paletteuse.c.
Referenced by set_frame().
diff()
static av_always_inline int diff (const uint8_t * c1, const uint8_t * c2) static
Definition at line 161 of file vf_paletteuse.c.
Referenced by colormap_nearest_bruteforce(), colormap_nearest_iterative(), colormap_nearest_node(), debug_accuracy(), and debug_mean_error().
colormap_nearest_bruteforce()
static av_always_inline uint8_t colormap_nearest_bruteforce (const uint32_t * palette, const uint8_t * rgb) static
Definition at line 170 of file vf_paletteuse.c.
Referenced by debug_accuracy().
colormap_nearest_node()
static void colormap_nearest_node (const struct color_node * map, const int node_pos, const uint8_t * target, struct nearest_color * nearest) static
Definition at line 199 of file vf_paletteuse.c.
Referenced by colormap_nearest_recursive().
colormap_nearest_recursive()
static av_always_inline uint8_t colormap_nearest_recursive (const struct color_node * node, const uint8_t * rgb) static
Definition at line 229 of file vf_paletteuse.c.
colormap_nearest_iterative()
static av_always_inline uint8_t colormap_nearest_iterative (const struct color_node * root, const uint8_t * target) static
Definition at line 241 of file vf_paletteuse.c.
color_get()
static av_always_inline int color_get (struct cache_node * cache, uint32_t color, uint8_t r, uint8_t g, uint8_t b, const struct color_node * map, const uint32_t * palette, const enum color_search_method search_method) static
Check if the requested color is in the cache already.
If not, find it in the color tree and cache it. Note: r, g, and b are the component of c but are passed as well to avoid recomputing them (they are generally computed by the caller for other uses).
Definition at line 324 of file vf_paletteuse.c.
Referenced by get_dst_color_err(), and set_frame().
get_dst_color_err()
static av_always_inline int get_dst_color_err (struct cache_node * cache, uint32_t c, const struct color_node * map, const uint32_t * palette, int * er, int * eg, int * eb, const enum color_search_method search_method) static
Definition at line 354 of file vf_paletteuse.c.
Referenced by set_frame().
set_frame()
static av_always_inline int set_frame (PaletteUseContext * s, AVFrame * out, AVFrame * in, int x_start, int y_start, int w, int h, enum dithering_mode dither, const enum color_search_method search_method) static
Definition at line 371 of file vf_paletteuse.c.
disp_node()
static void disp_node (AVBPrint * buf, const struct color_node * map, int parent_id, int node_id, int depth) static
Definition at line 482 of file vf_paletteuse.c.
Referenced by disp_tree().
disp_tree()
static int disp_tree (const struct color_node * node, const char * fname) static
Definition at line 510 of file vf_paletteuse.c.
Referenced by load_colormap().
debug_accuracy()
static int debug_accuracy (const struct color_node * node, const uint32_t * palette, const enum color_search_method search_method) static
Definition at line 535 of file vf_paletteuse.c.
Referenced by load_colormap().
get_next_color()
static int get_next_color (const uint8_t * color_used, const uint32_t * palette, int * component, const struct color_rect * box) static
Definition at line 593 of file vf_paletteuse.c.
Referenced by colormap_insert().
colormap_insert()
static int colormap_insert (struct color_node * map, uint8_t * color_used, int * nb_used, const uint32_t * palette, const struct color_rect * box) static
Definition at line 650 of file vf_paletteuse.c.
Referenced by load_colormap().
cmp_pal_entry()
static int cmp_pal_entry (const void * a, const void * b) static
Definition at line 694 of file vf_paletteuse.c.
Referenced by load_colormap().
load_colormap()
static void load_colormap (PaletteUseContext * s) static
Definition at line 701 of file vf_paletteuse.c.
Referenced by load_palette().
debug_mean_error()
static void debug_mean_error (PaletteUseContext * s, const AVFrame * in1, const AVFrame * in2, int frame_count) static
Definition at line 737 of file vf_paletteuse.c.
Referenced by apply_palette().
set_processing_window()
static void set_processing_window (enum diff_mode diff_mode, const AVFrame * prv_src, const AVFrame * cur_src, const AVFrame * prv_dst, AVFrame * cur_dst, int * xp, int * yp, int * wp, int * hp) static
Definition at line 767 of file vf_paletteuse.c.
Referenced by apply_palette().
apply_palette()
static AVFrame* apply_palette (AVFilterLink * inlink, AVFrame * in) static
Definition at line 856 of file vf_paletteuse.c.
Referenced by load_apply_palette().
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 897 of file vf_paletteuse.c.
config_input_palette()
static int config_input_palette (AVFilterLink * inlink) static
Definition at line 912 of file vf_paletteuse.c.
load_palette()
static void load_palette (PaletteUseContext * s, const AVFrame * palette_frame) static
Definition at line 927 of file vf_paletteuse.c.
Referenced by load_apply_palette().
load_apply_palette()
static AVFrame* load_apply_palette (AVFilterContext * ctx, AVFrame * main, const AVFrame * second) static
Definition at line 954 of file vf_paletteuse.c.
Referenced by init().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * in) static
Definition at line 965 of file vf_paletteuse.c.
dither_value()
static int dither_value (int p) static
Definition at line 1005 of file vf_paletteuse.c.
Referenced by init().
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 1013 of file vf_paletteuse.c.
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 1033 of file vf_paletteuse.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 1039 of file vf_paletteuse.c.
Variable Documentation
paletteuse_options
const AVOption paletteuse_options[] static
Initial value:
= {
    { "dither", "select dithering mode", OFFSET(dither), AV_OPT_TYPE_INT, {.i64=DITHERING_SIERRA2_4A}, 0, NB_DITHERING-1, FLAGS, "dithering_mode" },
        { "bayer",           "ordered 8x8 bayer dithering (deterministic)",                            0, AV_OPT_TYPE_CONST, {.i64=DITHERING_BAYER},           INT_MIN, INT_MAX, FLAGS, "dithering_mode" },
        { "heckbert",        "dithering as defined by Paul Heckbert in 1982 (simple error diffusion)", 0, AV_OPT_TYPE_CONST, {.i64=DITHERING_HECKBERT},        INT_MIN, INT_MAX, FLAGS, "dithering_mode" },
        { "floyd_steinberg", "Floyd and Steingberg dithering (error diffusion)",                       0, AV_OPT_TYPE_CONST, {.i64=DITHERING_FLOYD_STEINBERG}, INT_MIN, INT_MAX, FLAGS, "dithering_mode" },
        { "sierra2",         "Frankie Sierra dithering v2 (error diffusion)",                          0, AV_OPT_TYPE_CONST, {.i64=DITHERING_SIERRA2},         INT_MIN, INT_MAX, FLAGS, "dithering_mode" },
        { "sierra2_4a",      "Frankie Sierra dithering v2 \"Lite\" (error diffusion)",                 0, AV_OPT_TYPE_CONST, {.i64=DITHERING_SIERRA2_4A},      INT_MIN, INT_MAX, FLAGS, "dithering_mode" },
    { "bayer_scale", "set scale for bayer dithering", OFFSET(bayer_scale), AV_OPT_TYPE_INT, {.i64=2}, 0, 5, FLAGS },
    { "diff_mode",   "set frame difference mode",     OFFSET(diff_mode),   AV_OPT_TYPE_INT, {.i64=DIFF_MODE_NONE}, 0, NB_DIFF_MODE-1, FLAGS, "diff_mode" },
        { "rectangle", "process smallest different rectangle", 0, AV_OPT_TYPE_CONST, {.i64=DIFF_MODE_RECTANGLE}, INT_MIN, INT_MAX, FLAGS, "diff_mode" },
    { "debug_kdtree", "save Graphviz graph of the kdtree in specified file", OFFSET(dot_filename), AV_OPT_TYPE_STRING, {.str=NULL}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "color_search", "set reverse colormap color search method", OFFSET(color_search_method), AV_OPT_TYPE_INT, {.i64=COLOR_SEARCH_NNS_ITERATIVE}, 0, NB_COLOR_SEARCHES-1, FLAGS, "search" },
        { "nns_iterative", "iterative search",             0, AV_OPT_TYPE_CONST, {.i64=COLOR_SEARCH_NNS_ITERATIVE}, INT_MIN, INT_MAX, FLAGS, "search" },
        { "nns_recursive", "recursive search",             0, AV_OPT_TYPE_CONST, {.i64=COLOR_SEARCH_NNS_RECURSIVE}, INT_MIN, INT_MAX, FLAGS, "search" },
        { "bruteforce",    "brute-force into the palette", 0, AV_OPT_TYPE_CONST, {.i64=COLOR_SEARCH_BRUTEFORCE},    INT_MIN, INT_MAX, FLAGS, "search" },
    { "mean_err", "compute and print mean error", OFFSET(calc_mean_err), AV_OPT_TYPE_BOOL, {.i64=0}, 0, 1, FLAGS },
    { "debug_accuracy", "test color search accuracy", OFFSET(debug_accuracy), AV_OPT_TYPE_BOOL, {.i64=0}, 0, 1, FLAGS },
    { "new", "take new palette for each output frame", OFFSET(new), AV_OPT_TYPE_BOOL, {.i64=0}, 0, 1, FLAGS },
    { NULL }
}
Definition at line 107 of file vf_paletteuse.c.
cmp_funcs
const cmp_func cmp_funcs[] = {cmp_r, cmp_g, cmp_b} static
Definition at line 591 of file vf_paletteuse.c.
Referenced by get_next_color().
set_frame_lut
const set_frame_func set_frame_lut[NB_COLOR_SEARCHES][NB_DITHERING] static
Initial value:
= {
    DITHERING_ENTRIES(nns_iterative),
    DITHERING_ENTRIES(nns_recursive),
    DITHERING_ENTRIES(bruteforce),
}
Definition at line 999 of file vf_paletteuse.c.
paletteuse_inputs
const AVFilterPad paletteuse_inputs[] static
Initial value:
= {
    {
        .name           = "default",
        .type           = AVMEDIA_TYPE_VIDEO,
        .filter_frame   = filter_frame,
        .needs_writable = 1,
    },{
        .name           = "palette",
        .type           = AVMEDIA_TYPE_VIDEO,
        .config_props   = config_input_palette,
        .filter_frame   = filter_frame,
    },
    { NULL }
}
Definition at line 1051 of file vf_paletteuse.c.
paletteuse_outputs
const AVFilterPad paletteuse_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .config_props  = config_output,
        .request_frame = request_frame,
    },
    { NULL }
}
Definition at line 1066 of file vf_paletteuse.c.
ff_vf_paletteuse
AVFilter ff_vf_paletteuse
Initial value:
= {
    .name          = "paletteuse",
    .description   = NULL_IF_CONFIG_SMALL("Use a palette to downsample an input video stream."),
    .priv_size     = sizeof(PaletteUseContext),
    .query_formats = query_formats,
    .init          = init,
    .uninit        = uninit,
    .inputs        = paletteuse_inputs,
    .outputs       = paletteuse_outputs,
    .priv_class    = &paletteuse_class,
}
Definition at line 1076 of file vf_paletteuse.c.