FFmpeg: libavfilter/vf_framerate.c File Reference
vf_framerate.c File Reference
filter for upsampling or downsampling a progressive source
#include "libavutil/avassert.h"
#include "libavutil/imgutils.h"
#include "libavutil/internal.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "libavutil/pixelutils.h"
#include "avfilter.h"
#include "internal.h"
#include "video.h"
Data Structures
struct FrameRateContext
Macros
#define DEBUG
#define N_SRCE 3
#define OFFSET(x) offsetof(FrameRateContext, x)
#define V AV_OPT_FLAG_VIDEO_PARAM
#define F AV_OPT_FLAG_FILTERING_PARAM
#define FRAMERATE_FLAG_SCD 01
Functions
AVFILTER_DEFINE_CLASS (framerate)
static void next_source (AVFilterContext *ctx)
static av_always_inline int64_t sad_8x8_16 (const uint16_t *src1, ptrdiff_t stride1, const uint16_t *src2, ptrdiff_t stride2)
static double get_scene_score16 (AVFilterContext *ctx, AVFrame *crnt, AVFrame *next)
static double get_scene_score (AVFilterContext *ctx, AVFrame *crnt, AVFrame *next)
static int blend_frames16 (AVFilterContext *ctx, float interpolate, AVFrame *copy_src1, AVFrame *copy_src2)
static int blend_frames8 (AVFilterContext *ctx, float interpolate, AVFrame *copy_src1, AVFrame *copy_src2)
static int process_work_frame (AVFilterContext *ctx, int stop)
static void set_srce_frame_dest_pts (AVFilterContext *ctx)
static void set_work_frame_pts (AVFilterContext *ctx)
static av_cold int init (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static int config_input (AVFilterLink *inlink)
static int filter_frame (AVFilterLink *inlink, AVFrame *inpicref)
static int config_output (AVFilterLink *outlink)
static int request_frame (AVFilterLink *outlink)
Variables
static const AVOption framerate_options []
static const AVFilterPad framerate_inputs []
static const AVFilterPad framerate_outputs []
AVFilter ff_vf_framerate
Detailed Description
filter for upsampling or downsampling a progressive source
Definition in file vf_framerate.c.
Macro Definition Documentation
DEBUG
#define DEBUG
Definition at line 29 of file vf_framerate.c.
Referenced by audio_decode_frame().
N_SRCE
#define N_SRCE 3
Definition at line 42 of file vf_framerate.c.
Referenced by init().
OFFSET
#define OFFSET (x) offsetof(FrameRateContext, x)
Definition at line 83 of file vf_framerate.c.
V
#define V AV_OPT_FLAG_VIDEO_PARAM
Definition at line 84 of file vf_framerate.c.
F
#define F AV_OPT_FLAG_FILTERING_PARAM
Definition at line 85 of file vf_framerate.c.
FRAMERATE_FLAG_SCD
#define FRAMERATE_FLAG_SCD 01
Definition at line 86 of file vf_framerate.c.
Referenced by blend_frames16(), and blend_frames8().
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (framerate)
next_source()
static void next_source (AVFilterContext * ctx) static
Definition at line 104 of file vf_framerate.c.
Referenced by process_work_frame().
sad_8x8_16()
static av_always_inline int64_t sad_8x8_16 (const uint16_t * src1, ptrdiff_t stride1, const uint16_t * src2, ptrdiff_t stride2) static
Definition at line 123 of file vf_framerate.c.
Referenced by get_scene_score16().
get_scene_score16()
static double get_scene_score16 (AVFilterContext * ctx, AVFrame * crnt, AVFrame * next) static
Definition at line 138 of file vf_framerate.c.
Referenced by blend_frames16().
get_scene_score()
static double get_scene_score (AVFilterContext * ctx, AVFrame * crnt, AVFrame * next) static
Definition at line 175 of file vf_framerate.c.
Referenced by blend_frames8().
blend_frames16()
static int blend_frames16 (AVFilterContext * ctx, float interpolate, AVFrame * copy_src1, AVFrame * copy_src2) static
Definition at line 213 of file vf_framerate.c.
Referenced by config_input().
blend_frames8()
static int blend_frames8 (AVFilterContext * ctx, float interpolate, AVFrame * copy_src1, AVFrame * copy_src2) static
Definition at line 277 of file vf_framerate.c.
Referenced by config_input().
process_work_frame()
static int process_work_frame (AVFilterContext * ctx, int stop) static
Definition at line 344 of file vf_framerate.c.
Referenced by filter_frame(), and request_frame().
set_srce_frame_dest_pts()
static void set_srce_frame_dest_pts (AVFilterContext * ctx) static
Definition at line 446 of file vf_framerate.c.
Referenced by filter_frame(), and set_work_frame_pts().
set_work_frame_pts()
static void set_work_frame_pts (AVFilterContext * ctx) static
Definition at line 461 of file vf_framerate.c.
Referenced by filter_frame(), and request_frame().
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 509 of file vf_framerate.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 524 of file vf_framerate.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 536 of file vf_framerate.c.
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 557 of file vf_framerate.c.
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * inpicref) static
Definition at line 587 of file vf_framerate.c.
config_output()
static int config_output (AVFilterLink * outlink) static
Definition at line 612 of file vf_framerate.c.
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 657 of file vf_framerate.c.
Variable Documentation
framerate_options
const AVOption framerate_options[] static
Initial value:
= {
    {"fps",                 "required output frames per second rate", OFFSET(dest_frame_rate), AV_OPT_TYPE_VIDEO_RATE, {.str="50"},             0,       INT_MAX, V|F },
    {"interp_start",        "point to start linear interpolation",    OFFSET(interp_start),    AV_OPT_TYPE_INT,      {.i64=15},                 0,       255,     V|F },
    {"interp_end",          "point to end linear interpolation",      OFFSET(interp_end),      AV_OPT_TYPE_INT,      {.i64=240},                0,       255,     V|F },
    {"scene",               "scene change level",                     OFFSET(scene_score),     AV_OPT_TYPE_DOUBLE,   {.dbl=7.0},                0,       INT_MAX, V|F },
    {"flags",               "set flags",                              OFFSET(flags),           AV_OPT_TYPE_FLAGS,    {.i64=1},                  0,       INT_MAX, V|F, "flags" },
    {"scene_change_detect", "enable scene change detection",          0,                       AV_OPT_TYPE_CONST,    {.i64=FRAMERATE_FLAG_SCD}, INT_MIN, INT_MAX, V|F, "flags" },
    {"scd",                 "enable scene change detection",          0,                       AV_OPT_TYPE_CONST,    {.i64=FRAMERATE_FLAG_SCD}, INT_MIN, INT_MAX, V|F, "flags" },
    {NULL}
}
Definition at line 88 of file vf_framerate.c.
framerate_inputs
const AVFilterPad framerate_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .config_props = config_input,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 701 of file vf_framerate.c.
framerate_outputs
const AVFilterPad framerate_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .request_frame = request_frame,
        .config_props  = config_output,
    },
    { NULL }
}
Definition at line 711 of file vf_framerate.c.
ff_vf_framerate
AVFilter ff_vf_framerate
Initial value:
= {
    .name          = "framerate",
    .description   = NULL_IF_CONFIG_SMALL("Upsamples or downsamples progressive source between specified frame rates."),
    .priv_size     = sizeof(FrameRateContext),
    .priv_class    = &framerate_class,
    .init          = init,
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = framerate_inputs,
    .outputs       = framerate_outputs,
}
Definition at line 721 of file vf_framerate.c.