FFmpeg: libavfilter/x86/vf_yadif_init.c File Reference
vf_yadif_init.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/mem.h"
#include "libavutil/x86/cpu.h"
#include "libavfilter/yadif.h"
Functions
void ff_yadif_filter_line_mmxext (void *dst, void *prev, void *cur, void *next, int w, int prefs, int mrefs, int parity, int mode)
void ff_yadif_filter_line_sse2 (void *dst, void *prev, void *cur, void *next, int w, int prefs, int mrefs, int parity, int mode)
void ff_yadif_filter_line_ssse3 (void *dst, void *prev, void *cur, void *next, int w, int prefs, int mrefs, int parity, int mode)
void ff_yadif_filter_line_16bit_mmxext (void *dst, void *prev, void *cur, void *next, int w, int prefs, int mrefs, int parity, int mode)
void ff_yadif_filter_line_16bit_sse2 (void *dst, void *prev, void *cur, void *next, int w, int prefs, int mrefs, int parity, int mode)
void ff_yadif_filter_line_16bit_ssse3 (void *dst, void *prev, void *cur, void *next, int w, int prefs, int mrefs, int parity, int mode)
void ff_yadif_filter_line_16bit_sse4 (void *dst, void *prev, void *cur, void *next, int w, int prefs, int mrefs, int parity, int mode)
void ff_yadif_filter_line_10bit_mmxext (void *dst, void *prev, void *cur, void *next, int w, int prefs, int mrefs, int parity, int mode)
void ff_yadif_filter_line_10bit_sse2 (void *dst, void *prev, void *cur, void *next, int w, int prefs, int mrefs, int parity, int mode)
void ff_yadif_filter_line_10bit_ssse3 (void *dst, void *prev, void *cur, void *next, int w, int prefs, int mrefs, int parity, int mode)
av_cold void ff_yadif_init_x86 (YADIFContext *yadif)
Function Documentation
ff_yadif_filter_line_mmxext()
void ff_yadif_filter_line_mmxext (void * dst, void * prev, void * cur, void * next, int w, int prefs, int mrefs, int parity, int mode)
Referenced by ff_yadif_init_x86().
ff_yadif_filter_line_sse2()
void ff_yadif_filter_line_sse2 (void * dst, void * prev, void * cur, void * next, int w, int prefs, int mrefs, int parity, int mode)
Referenced by ff_yadif_init_x86().
ff_yadif_filter_line_ssse3()
void ff_yadif_filter_line_ssse3 (void * dst, void * prev, void * cur, void * next, int w, int prefs, int mrefs, int parity, int mode)
Referenced by ff_yadif_init_x86().
ff_yadif_filter_line_16bit_mmxext()
void ff_yadif_filter_line_16bit_mmxext (void * dst, void * prev, void * cur, void * next, int w, int prefs, int mrefs, int parity, int mode)
Referenced by ff_yadif_init_x86().
ff_yadif_filter_line_16bit_sse2()
void ff_yadif_filter_line_16bit_sse2 (void * dst, void * prev, void * cur, void * next, int w, int prefs, int mrefs, int parity, int mode)
Referenced by ff_yadif_init_x86().
ff_yadif_filter_line_16bit_ssse3()
void ff_yadif_filter_line_16bit_ssse3 (void * dst, void * prev, void * cur, void * next, int w, int prefs, int mrefs, int parity, int mode)
Referenced by ff_yadif_init_x86().
ff_yadif_filter_line_16bit_sse4()
void ff_yadif_filter_line_16bit_sse4 (void * dst, void * prev, void * cur, void * next, int w, int prefs, int mrefs, int parity, int mode)
Referenced by ff_yadif_init_x86().
ff_yadif_filter_line_10bit_mmxext()
void ff_yadif_filter_line_10bit_mmxext (void * dst, void * prev, void * cur, void * next, int w, int prefs, int mrefs, int parity, int mode)
Referenced by ff_yadif_init_x86().
ff_yadif_filter_line_10bit_sse2()
void ff_yadif_filter_line_10bit_sse2 (void * dst, void * prev, void * cur, void * next, int w, int prefs, int mrefs, int parity, int mode)
Referenced by ff_yadif_init_x86().
ff_yadif_filter_line_10bit_ssse3()
void ff_yadif_filter_line_10bit_ssse3 (void * dst, void * prev, void * cur, void * next, int w, int prefs, int mrefs, int parity, int mode)
Referenced by ff_yadif_init_x86().
ff_yadif_init_x86()
av_cold void ff_yadif_init_x86 (YADIFContext * yadif)
Definition at line 60 of file vf_yadif_init.c.
Referenced by config_props().