FFmpeg: libavfilter/vf_fspp.h File Reference
vf_fspp.h File Reference
#include "avfilter.h"
Data Structures
struct FSPPContext
Macros
#define BLOCKSZ 12
#define MAX_LEVEL 5
#define DCTSIZE 8
#define DCTSIZE_S "8"
#define FIX(x, s) ((int) ((x) * (1 << s) + 0.5) & 0xffff)
#define C64(x) ((uint64_t)((x) | (x) << 16)) <<32 | (uint64_t)(x) | (uint64_t)(x) << 16
#define FIX64(x, s) C64(FIX(x,s))
#define MULTIPLY16H(x, k) (((x) * (k)) >> 16)
#define THRESHOLD(r, x, t)
#define DESCALE(x, n) (((x) + (1 << ((n) - 1))) >> n)
Typedefs
typedef int32_t int_simd16_t
Functions
void ff_fspp_init_x86 (FSPPContext *fspp)
Variables
static const int16_t FIX_0_382683433 = FIX(0.382683433, 14)
static const int16_t FIX_0_541196100 = FIX(0.541196100, 14)
static const int16_t FIX_0_707106781 = FIX(M_SQRT1_2 , 14)
static const int16_t FIX_1_306562965 = FIX(1.306562965, 14)
static const int16_t FIX_1_414213562_A = FIX(M_SQRT2 , 14)
static const int16_t FIX_1_847759065 = FIX(1.847759065, 13)
static const int16_t FIX_2_613125930 = FIX(-2.613125930, 13)
static const int16_t FIX_1_414213562 = FIX(M_SQRT2 , 13)
static const int16_t FIX_1_082392200 = FIX(1.082392200, 13)
Macro Definition Documentation
BLOCKSZ
#define BLOCKSZ 12
Definition at line 28 of file vf_fspp.h.
Referenced by filter().
MAX_LEVEL
#define MAX_LEVEL 5
Definition at line 29 of file vf_fspp.h.
DCTSIZE
#define DCTSIZE 8
Definition at line 31 of file vf_fspp.h.
DCTSIZE_S
#define DCTSIZE_S "8"
Definition at line 32 of file vf_fspp.h.
FIX
#define FIX (x, s) ((int) ((x) * (1 << s) + 0.5) & 0xffff)
Definition at line 34 of file vf_fspp.h.
C64
#define C64 (x) ((uint64_t)((x) | (x) << 16)) <<32 | (uint64_t)(x) | (uint64_t)(x) << 16
Definition at line 35 of file vf_fspp.h.
FIX64
#define FIX64 (x, s) C64(FIX(x,s))
Definition at line 36 of file vf_fspp.h.
MULTIPLY16H
#define MULTIPLY16H (x, k) (((x) * (k)) >> 16)
Definition at line 38 of file vf_fspp.h.
Referenced by column_fidct_c(), row_fdct_c(), and row_idct_c().
THRESHOLD
#define THRESHOLD (r, x, t)
Value:
if(((unsigned)((x) + t)) > t * 2) r = (x);   \
    else r = 0;
Definition at line 39 of file vf_fspp.h.
Referenced by column_fidct_c().
DESCALE
#define DESCALE (x, n) (((x) + (1 << ((n) - 1))) >> n)
Definition at line 42 of file vf_fspp.h.
Typedef Documentation
int_simd16_t
typedef int32_t int_simd16_t
Definition at line 44 of file vf_fspp.h.
Function Documentation
ff_fspp_init_x86()
void ff_fspp_init_x86 (FSPPContext * fspp)
Definition at line 37 of file vf_fspp_init.c.
Referenced by config_input().
Variable Documentation
FIX_0_382683433
const int16_t FIX_0_382683433 = FIX(0.382683433, 14) static
Definition at line 45 of file vf_fspp.h.
FIX_0_541196100
const int16_t FIX_0_541196100 = FIX(0.541196100, 14) static
Definition at line 46 of file vf_fspp.h.
FIX_0_707106781
const int16_t FIX_0_707106781 = FIX(M_SQRT1_2 , 14) static
Definition at line 47 of file vf_fspp.h.
FIX_1_306562965
const int16_t FIX_1_306562965 = FIX(1.306562965, 14) static
Definition at line 48 of file vf_fspp.h.
FIX_1_414213562_A
const int16_t FIX_1_414213562_A = FIX(M_SQRT2 , 14) static
Definition at line 49 of file vf_fspp.h.
Referenced by column_fidct_c(), and row_idct_c().
FIX_1_847759065
const int16_t FIX_1_847759065 = FIX(1.847759065, 13) static
Definition at line 50 of file vf_fspp.h.
FIX_2_613125930
const int16_t FIX_2_613125930 = FIX(-2.613125930, 13) static
Definition at line 51 of file vf_fspp.h.
FIX_1_414213562
const int16_t FIX_1_414213562 = FIX(M_SQRT2 , 13) static
Definition at line 52 of file vf_fspp.h.
FIX_1_082392200
const int16_t FIX_1_082392200 = FIX(1.082392200, 13) static
Definition at line 53 of file vf_fspp.h.