FFmpeg: libavfilter/x86/vf_fspp_init.c File Reference
vf_fspp_init.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/x86/cpu.h"
#include "libavfilter/vf_fspp.h"
Functions
void ff_store_slice_mmx (uint8_t *dst, int16_t *src, ptrdiff_t dst_stride, ptrdiff_t src_stride, ptrdiff_t width, ptrdiff_t height, ptrdiff_t log2_scale)
void ff_store_slice2_mmx (uint8_t *dst, int16_t *src, ptrdiff_t dst_stride, ptrdiff_t src_stride, ptrdiff_t width, ptrdiff_t height, ptrdiff_t log2_scale)
void ff_mul_thrmat_mmx (int16_t *thr_adr_noq, int16_t *thr_adr, int q)
void ff_column_fidct_mmx (int16_t *thr_adr, int16_t *data, int16_t *output, int cnt)
void ff_row_idct_mmx (int16_t *workspace, int16_t *output_adr, ptrdiff_t output_stride, int cnt)
void ff_row_fdct_mmx (int16_t *data, const uint8_t *pixels, ptrdiff_t line_size, int cnt)
av_cold void ff_fspp_init_x86 (FSPPContext *s)
Function Documentation
ff_store_slice_mmx()
void ff_store_slice_mmx (uint8_t * dst, int16_t * src, ptrdiff_t dst_stride, ptrdiff_t src_stride, ptrdiff_t width, ptrdiff_t height, ptrdiff_t log2_scale)
Referenced by ff_fspp_init_x86().
ff_store_slice2_mmx()
void ff_store_slice2_mmx (uint8_t * dst, int16_t * src, ptrdiff_t dst_stride, ptrdiff_t src_stride, ptrdiff_t width, ptrdiff_t height, ptrdiff_t log2_scale)
Referenced by ff_fspp_init_x86().
ff_mul_thrmat_mmx()
void ff_mul_thrmat_mmx (int16_t * thr_adr_noq, int16_t * thr_adr, int q)
Referenced by ff_fspp_init_x86().
ff_column_fidct_mmx()
void ff_column_fidct_mmx (int16_t * thr_adr, int16_t * data, int16_t * output, int cnt)
Referenced by ff_fspp_init_x86().
ff_row_idct_mmx()
void ff_row_idct_mmx (int16_t * workspace, int16_t * output_adr, ptrdiff_t output_stride, int cnt)
Referenced by ff_fspp_init_x86().
ff_row_fdct_mmx()
void ff_row_fdct_mmx (int16_t * data, const uint8_t * pixels, ptrdiff_t line_size, int cnt)
Referenced by ff_fspp_init_x86().
ff_fspp_init_x86()
av_cold void ff_fspp_init_x86 (FSPPContext * s)
Definition at line 37 of file vf_fspp_init.c.
Referenced by config_input().