FFmpeg: libavfilter/vf_noise.c File Reference
vf_noise.c File Reference
noise generator
#include "libavutil/opt.h"
#include "libavutil/imgutils.h"
#include "libavutil/lfg.h"
#include "libavutil/parseutils.h"
#include "libavutil/pixdesc.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
#include "vf_noise.h"
#include "video.h"
Data Structures
struct ThreadData
Macros
#define OFFSET(x) offsetof(NoiseContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
#define NOISE_PARAMS(name, x, param)
#define RAND_N(range) ((int) ((double) range * av_lfg_get(lfg) / (UINT_MAX + 1.0)))
Functions
AVFILTER_DEFINE_CLASS (noise)
static av_cold int init_noise (NoiseContext *n, int comp)
static int query_formats (AVFilterContext *ctx)
static int config_input (AVFilterLink *inlink)
void ff_line_noise_c (uint8_t *dst, const uint8_t *src, const int8_t *noise, int len, int shift)
void ff_line_noise_avg_c (uint8_t *dst, const uint8_t *src, int len, const int8_t *const *shift)
static void noise (uint8_t *dst, const uint8_t *src, int dst_linesize, int src_linesize, int width, int start, int end, NoiseContext *n, int comp)
static int filter_slice (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int filter_frame (AVFilterLink *inlink, AVFrame *inpicref)
static av_cold int init (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
Variables
static const AVOption noise_options []
static const int8_t patt [4] = { -1, 0, 1, 0 }
static const AVFilterPad noise_inputs []
static const AVFilterPad noise_outputs []
AVFilter ff_vf_noise
Detailed Description
noise generator
Definition in file vf_noise.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(NoiseContext, x)
Definition at line 42 of file vf_noise.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 43 of file vf_noise.c.
NOISE_PARAMS
#define NOISE_PARAMS (name, x, param)
Value:
{#name"_seed", "set component #"#x" noise seed", OFFSET(param.seed), AV_OPT_TYPE_INT, {.i64=-1}, -1, INT_MAX, FLAGS},        \
    {#name"_strength", "set component #"#x" strength", OFFSET(param.strength), AV_OPT_TYPE_INT, {.i64=0}, 0, 100, FLAGS},        \
    {#name"s",         "set component #"#x" strength", OFFSET(param.strength), AV_OPT_TYPE_INT, {.i64=0}, 0, 100, FLAGS},        \
    {#name"_flags", "set component #"#x" flags", OFFSET(param.flags), AV_OPT_TYPE_FLAGS, {.i64=0}, 0, 31, FLAGS, #name"_flags"}, \
    {#name"f", "set component #"#x" flags", OFFSET(param.flags), AV_OPT_TYPE_FLAGS, {.i64=0}, 0, 31, FLAGS, #name"_flags"},      \
    {"a", "averaged noise", 0, AV_OPT_TYPE_CONST, {.i64=NOISE_AVERAGED}, 0, 0, FLAGS, #name"_flags"},                            \
    {"p", "(semi)regular pattern", 0, AV_OPT_TYPE_CONST, {.i64=NOISE_PATTERN},  0, 0, FLAGS, #name"_flags"},                     \
    {"t", "temporal noise", 0, AV_OPT_TYPE_CONST, {.i64=NOISE_TEMPORAL}, 0, 0, FLAGS, #name"_flags"},                            \
    {"u", "uniform noise",  0, AV_OPT_TYPE_CONST, {.i64=NOISE_UNIFORM},  0, 0, FLAGS, #name"_flags"},
Definition at line 45 of file vf_noise.c.
RAND_N
#define RAND_N (range) ((int) ((double) range * av_lfg_get(lfg) / (UINT_MAX + 1.0)))
Definition at line 69 of file vf_noise.c.
Referenced by init_noise().
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (noise)
init_noise()
static av_cold int init_noise (NoiseContext * n, int comp) static
Definition at line 70 of file vf_noise.c.
Referenced by init().
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 133 of file vf_noise.c.
config_input()
static int config_input (AVFilterLink * inlink) static
Definition at line 148 of file vf_noise.c.
ff_line_noise_c()
void ff_line_noise_c (uint8_t * dst, const uint8_t * src, const int8_t * noise, int len, int shift)
Definition at line 165 of file vf_noise.c.
Referenced by init().
ff_line_noise_avg_c()
void ff_line_noise_avg_c (uint8_t * dst, const uint8_t * src, int len, const int8_t *const * shift)
Definition at line 178 of file vf_noise.c.
Referenced by init().
noise()
static void noise (uint8_t * dst, const uint8_t * src, int dst_linesize, int src_linesize, int width, int start, int end, NoiseContext * n, int comp) static
Definition at line 190 of file vf_noise.c.
Referenced by filter_slice(), and init_noise().
filter_slice()
static int filter_slice (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 224 of file vf_noise.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * inpicref) static
Definition at line 242 of file vf_noise.c.
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 283 of file vf_noise.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 313 of file vf_noise.c.
Variable Documentation
noise_options
const AVOption noise_options[] static
Initial value:
= {
    NOISE_PARAMS(c3,  3, param[3])
    {NULL}
}
Definition at line 56 of file vf_noise.c.
patt
const int8_t patt[4] = { -1, 0, 1, 0 } static
Definition at line 67 of file vf_noise.c.
Referenced by filter_frame(), get_rdelta(), and init_noise().
noise_inputs
const AVFilterPad noise_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .filter_frame = filter_frame,
        .config_props = config_input,
    },
    { NULL }
}
Definition at line 322 of file vf_noise.c.
noise_outputs
const AVFilterPad noise_outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_VIDEO,
    },
    { NULL }
}
Definition at line 332 of file vf_noise.c.
ff_vf_noise
AVFilter ff_vf_noise
Initial value:
= {
    .name          = "noise",
    .description   = NULL_IF_CONFIG_SMALL("Add noise."),
    .priv_size     = sizeof(NoiseContext),
    .init          = init,
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = noise_inputs,
    .outputs       = noise_outputs,
    .priv_class    = &noise_class,
    .flags         = AVFILTER_FLAG_SUPPORT_TIMELINE_GENERIC | AVFILTER_FLAG_SLICE_THREADS,
}
Definition at line 340 of file vf_noise.c.