FFmpeg: libavfilter/vf_fade.c File Reference
vf_fade.c File Reference
video fade filter based heavily on vf_negate.c by Bobby Bingham
#include "libavutil/avassert.h"
#include "libavutil/avstring.h"
#include "libavutil/common.h"
#include "libavutil/eval.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "avfilter.h"
#include "drawutils.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
Data Structures
struct FadeContext
Macros
#define R 0
#define G 1
#define B 2
#define A 3
#define Y 0
#define U 1
#define V 2
#define FADE_IN 0
#define FADE_OUT 1
#define INTERP(c_name, c_idx) av_clip_uint8(((c[c_idx]<<16) + ((int)p[c_name] - (int)c[c_idx]) * s->factor + (1<<15)) >> 16)
#define OFFSET(x) offsetof(FadeContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Functions
static av_cold int init (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static int config_props (AVFilterLink *inlink)
static av_always_inline void filter_rgb (FadeContext *s, const AVFrame *frame, int slice_start, int slice_end, int do_alpha, int step)
static int filter_slice_rgb (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int filter_slice_luma (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int filter_slice_chroma (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int filter_slice_alpha (AVFilterContext *ctx, void *arg, int jobnr, int nb_jobs)
static int filter_frame (AVFilterLink *inlink, AVFrame *frame)
AVFILTER_DEFINE_CLASS (fade)
Variables
static const enum AVPixelFormat studio_level_pix_fmts []
static const AVOption fade_options []
static const AVFilterPad avfilter_vf_fade_inputs []
static const AVFilterPad avfilter_vf_fade_outputs []
AVFilter ff_vf_fade
Detailed Description
video fade filter based heavily on vf_negate.c by Bobby Bingham
Definition in file vf_fade.c.
Macro Definition Documentation
R
#define R 0
Definition at line 40 of file vf_fade.c.
Referenced by filter_rgb().
G
#define G 1
Definition at line 41 of file vf_fade.c.
Referenced by filter_rgb().
B
#define B 2
Definition at line 42 of file vf_fade.c.
Referenced by filter_rgb().
A
#define A 3
Definition at line 43 of file vf_fade.c.
Referenced by filter_rgb(), and filter_slice_alpha().
Y
#define Y 0
Definition at line 45 of file vf_fade.c.
U
#define U 1
Definition at line 46 of file vf_fade.c.
V
#define V 2
Definition at line 47 of file vf_fade.c.
FADE_IN
#define FADE_IN 0
Definition at line 49 of file vf_fade.c.
Referenced by init().
FADE_OUT
#define FADE_OUT 1
Definition at line 50 of file vf_fade.c.
Referenced by filter_frame().
INTERP
#define INTERP (c_name, c_idx) av_clip_uint8(((c[c_idx]<<16) + ((int)p[c_name] - (int)c[c_idx]) * s->factor + (1<<15)) >> 16)
Referenced by filter_rgb().
OFFSET
#define OFFSET (x) offsetof(FadeContext, x)
Definition at line 371 of file vf_fade.c.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 372 of file vf_fade.c.
Function Documentation
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 68 of file vf_fade.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 98 of file vf_fade.c.
config_props()
static int config_props (AVFilterLink * inlink) static
Definition at line 154 of file vf_fade.c.
filter_rgb()
static av_always_inline void filter_rgb (FadeContext * s, const AVFrame * frame, int slice_start, int slice_end, int do_alpha, int step) static
Definition at line 177 of file vf_fade.c.
Referenced by filter_slice_rgb().
filter_slice_rgb()
static int filter_slice_rgb (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 202 of file vf_fade.c.
Referenced by filter_frame().
filter_slice_luma()
static int filter_slice_luma (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 218 of file vf_fade.c.
Referenced by filter_frame().
filter_slice_chroma()
static int filter_slice_chroma (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 241 of file vf_fade.c.
Referenced by filter_frame().
filter_slice_alpha()
static int filter_slice_alpha (AVFilterContext * ctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 268 of file vf_fade.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * frame) static
Definition at line 293 of file vf_fade.c.
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (fade)
Variable Documentation
studio_level_pix_fmts
const enum AVPixelFormat studio_level_pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_YUV444P,  AV_PIX_FMT_YUV422P,  AV_PIX_FMT_YUV420P,
    AV_PIX_FMT_YUV411P,  AV_PIX_FMT_YUV410P,
    AV_PIX_FMT_YUV440P,
    AV_PIX_FMT_NONE
}
Definition at line 147 of file vf_fade.c.
Referenced by config_props().
fade_options
const AVOption fade_options[] static
Initial value:
= {
    { "type", "'in' or 'out' for fade-in/fade-out", OFFSET(type), AV_OPT_TYPE_INT, { .i64 = FADE_IN }, FADE_IN, FADE_OUT, FLAGS, "type" },
    { "t",    "'in' or 'out' for fade-in/fade-out", OFFSET(type), AV_OPT_TYPE_INT, { .i64 = FADE_IN }, FADE_IN, FADE_OUT, FLAGS, "type" },
        { "in",  "fade-in",  0, AV_OPT_TYPE_CONST, { .i64 = FADE_IN },  .unit = "type" },
        { "out", "fade-out", 0, AV_OPT_TYPE_CONST, { .i64 = FADE_OUT }, .unit = "type" },
    { "start_frame", "Number of the first frame to which to apply the effect.",
                                                    OFFSET(start_frame), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, INT_MAX, FLAGS },
    { "s",           "Number of the first frame to which to apply the effect.",
                                                    OFFSET(start_frame), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, INT_MAX, FLAGS },
    { "nb_frames",   "Number of frames to which the effect should be applied.",
                                                    OFFSET(nb_frames),   AV_OPT_TYPE_INT, { .i64 = 25 }, 0, INT_MAX, FLAGS },
    { "n",           "Number of frames to which the effect should be applied.",
                                                    OFFSET(nb_frames),   AV_OPT_TYPE_INT, { .i64 = 25 }, 0, INT_MAX, FLAGS },
    { "alpha",       "fade alpha if it is available on the input", OFFSET(alpha),       AV_OPT_TYPE_BOOL, {.i64 = 0    }, 0,       1, FLAGS },
    { "start_time",  "Number of seconds of the beginning of the effect.",
                                                    OFFSET(start_time),  AV_OPT_TYPE_DURATION, {.i64 = 0. }, 0, INT32_MAX, FLAGS },
    { "st",          "Number of seconds of the beginning of the effect.",
                                                    OFFSET(start_time),  AV_OPT_TYPE_DURATION, {.i64 = 0. }, 0, INT32_MAX, FLAGS },
    { "duration",    "Duration of the effect in seconds.",
                                                    OFFSET(duration),    AV_OPT_TYPE_DURATION, {.i64 = 0. }, 0, INT32_MAX, FLAGS },
    { "d",           "Duration of the effect in seconds.",
                                                    OFFSET(duration),    AV_OPT_TYPE_DURATION, {.i64 = 0. }, 0, INT32_MAX, FLAGS },
    { "color",       "set color",                   OFFSET(color_rgba),  AV_OPT_TYPE_COLOR,    {.str = "black"}, CHAR_MIN, CHAR_MAX, FLAGS },
    { "c",           "set color",                   OFFSET(color_rgba),  AV_OPT_TYPE_COLOR,    {.str = "black"}, CHAR_MIN, CHAR_MAX, FLAGS },
    { NULL }
}
Definition at line 374 of file vf_fade.c.
avfilter_vf_fade_inputs
const AVFilterPad avfilter_vf_fade_inputs[] static
Initial value:
= {
    {
        .name           = "default",
        .type           = AVMEDIA_TYPE_VIDEO,
        .config_props   = config_props,
        .filter_frame   = filter_frame,
        .needs_writable = 1,
    },
    { NULL }
}
Definition at line 403 of file vf_fade.c.
avfilter_vf_fade_outputs
const AVFilterPad avfilter_vf_fade_outputs[] static
Initial value:
= {
    {
        .name = "default",
        .type = AVMEDIA_TYPE_VIDEO,
    },
    { NULL }
}
Definition at line 414 of file vf_fade.c.
ff_vf_fade
AVFilter ff_vf_fade
Initial value:
= {
    .name          = "fade",
    .description   = NULL_IF_CONFIG_SMALL("Fade in/out input video."),
    .init          = init,
    .priv_size     = sizeof(FadeContext),
    .priv_class    = &fade_class,
    .query_formats = query_formats,
    .inputs        = avfilter_vf_fade_inputs,
    .outputs       = avfilter_vf_fade_outputs,
    .flags         = AVFILTER_FLAG_SLICE_THREADS,
}
Definition at line 422 of file vf_fade.c.