FFmpeg: libavfilter/vf_thumbnail.c File Reference
vf_thumbnail.c File Reference
Potential thumbnail lookup filter to reduce the risk of an inappropriate selection (such as a black frame) we could get with an absolute seek.
#include "libavutil/opt.h"
#include "avfilter.h"
#include "internal.h"
Data Structures
struct thumb_frame
struct ThumbContext
Macros
#define HIST_SIZE (3*256)
#define OFFSET(x) offsetof(ThumbContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Functions
AVFILTER_DEFINE_CLASS (thumbnail)
static av_cold int init (AVFilterContext *ctx)
static double frame_sum_square_err (const int *hist, const double *median)
Compute Sum-square deviation to estimate "closeness".
static AVFrame * get_best_frame (AVFilterContext *ctx)
static int filter_frame (AVFilterLink *inlink, AVFrame *frame)
static av_cold void uninit (AVFilterContext *ctx)
static int request_frame (AVFilterLink *link)
static int config_props (AVFilterLink *inlink)
static int query_formats (AVFilterContext *ctx)
Variables
static const AVOption thumbnail_options []
static const AVFilterPad thumbnail_inputs []
static const AVFilterPad thumbnail_outputs []
AVFilter ff_vf_thumbnail
Detailed Description
Potential thumbnail lookup filter to reduce the risk of an inappropriate selection (such as a black frame) we could get with an absolute seek.
Simplified version of algorithm by Vadim Zaliva lord@.nosp@m.croc.nosp@m.odile.nosp@m..org.
See also
http://notbrainsurgery.livejournal.com/29773.html
Definition in file vf_thumbnail.c.
Macro Definition Documentation
HIST_SIZE
#define HIST_SIZE (3*256)
Definition at line 34 of file vf_thumbnail.c.
Referenced by frame_sum_square_err(), and get_best_frame().
OFFSET
#define OFFSET (x) offsetof(ThumbContext, x)
Definition at line 49 of file vf_thumbnail.c.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 50 of file vf_thumbnail.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (thumbnail)
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 59 of file vf_thumbnail.c.
frame_sum_square_err()
static double frame_sum_square_err (const int * hist, const double * median) static
Compute Sum-square deviation to estimate "closeness".
Parameters
hist color distribution histogram
median average color distribution histogram
Returns
sum of squared errors
Definition at line 79 of file vf_thumbnail.c.
Referenced by get_best_frame().
get_best_frame()
static AVFrame* get_best_frame (AVFilterContext * ctx) static
Definition at line 91 of file vf_thumbnail.c.
Referenced by filter_frame(), and request_frame().
filter_frame()
static int filter_frame (AVFilterLink * inlink, AVFrame * frame) static
Definition at line 131 of file vf_thumbnail.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 161 of file vf_thumbnail.c.
request_frame()
static int request_frame (AVFilterLink * link) static
Definition at line 170 of file vf_thumbnail.c.
config_props()
static int config_props (AVFilterLink * inlink) static
Definition at line 187 of file vf_thumbnail.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 196 of file vf_thumbnail.c.
Variable Documentation
thumbnail_options
const AVOption thumbnail_options[] static
Initial value:
= {
    { "n", "set the frames batch size", OFFSET(n_frames), AV_OPT_TYPE_INT, {.i64=100}, 2, INT_MAX, FLAGS },
    { NULL }
}
Definition at line 52 of file vf_thumbnail.c.
thumbnail_inputs
const AVFilterPad thumbnail_inputs[] static
Initial value:
= {
    {
        .name         = "default",
        .type         = AVMEDIA_TYPE_VIDEO,
        .config_props = config_props,
        .filter_frame = filter_frame,
    },
    { NULL }
}
Definition at line 208 of file vf_thumbnail.c.
thumbnail_outputs
const AVFilterPad thumbnail_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .request_frame = request_frame,
    },
    { NULL }
}
Definition at line 218 of file vf_thumbnail.c.
ff_vf_thumbnail
AVFilter ff_vf_thumbnail
Initial value:
= {
    .name          = "thumbnail",
    .description   = NULL_IF_CONFIG_SMALL("Select the most representative frame in a given sequence of consecutive frames."),
    .priv_size     = sizeof(ThumbContext),
    .init          = init,
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = thumbnail_inputs,
    .outputs       = thumbnail_outputs,
    .priv_class    = &thumbnail_class,
}
Definition at line 227 of file vf_thumbnail.c.