FFmpeg: libavfilter/vf_chromakey.c File Reference
vf_chromakey.c File Reference
#include "libavutil/opt.h"
#include "libavutil/imgutils.h"
#include "avfilter.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
Data Structures
struct ChromakeyContext
Macros
#define FIXNUM(x) lrint((x) * (1 << 10))
#define RGB_TO_U(rgb) (((- FIXNUM(0.16874) * rgb[0] - FIXNUM(0.33126) * rgb[1] + FIXNUM(0.50000) * rgb[2] + (1 << 9) - 1) >> 10) + 128)
#define RGB_TO_V(rgb) (((FIXNUM(0.50000) * rgb[0] - FIXNUM(0.41869) * rgb[1] - FIXNUM(0.08131) * rgb[2] + (1 << 9) - 1) >> 10) + 128)
#define OFFSET(x) offsetof(ChromakeyContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Functions
static uint8_t do_chromakey_pixel (ChromakeyContext *ctx, uint8_t u[9], uint8_t v[9])
static av_always_inline void get_pixel_uv (AVFrame *frame, int hsub_log2, int vsub_log2, int x, int y, uint8_t *u, uint8_t *v)
static int do_chromakey_slice (AVFilterContext *avctx, void *arg, int jobnr, int nb_jobs)
static int filter_frame (AVFilterLink *link, AVFrame *frame)
static av_cold int initialize_chromakey (AVFilterContext *avctx)
static av_cold int query_formats (AVFilterContext *avctx)
static av_cold int config_input (AVFilterLink *inlink)
AVFILTER_DEFINE_CLASS (chromakey)
Variables
static const AVFilterPad chromakey_inputs []
static const AVFilterPad chromakey_outputs []
static const AVOption chromakey_options []
AVFilter ff_vf_chromakey
Macro Definition Documentation
FIXNUM
#define FIXNUM (x) lrint((x) * (1 << 10))
Definition at line 117 of file vf_chromakey.c.
RGB_TO_U
#define RGB_TO_U (rgb) (((- FIXNUM(0.16874) * rgb[0] - FIXNUM(0.33126) * rgb[1] + FIXNUM(0.50000) * rgb[2] + (1 << 9) - 1) >> 10) + 128)
Definition at line 118 of file vf_chromakey.c.
Referenced by initialize_chromakey().
RGB_TO_V
#define RGB_TO_V (rgb) (((FIXNUM(0.50000) * rgb[0] - FIXNUM(0.41869) * rgb[1] - FIXNUM(0.08131) * rgb[2] + (1 << 9) - 1) >> 10) + 128)
Definition at line 119 of file vf_chromakey.c.
Referenced by initialize_chromakey().
OFFSET
#define OFFSET (x) offsetof(ChromakeyContext, x)
Definition at line 185 of file vf_chromakey.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 186 of file vf_chromakey.c.
Function Documentation
do_chromakey_pixel()
static uint8_t do_chromakey_pixel (ChromakeyContext * ctx, uint8_t u[9], uint8_t v[9]) static
Definition at line 43 of file vf_chromakey.c.
Referenced by do_chromakey_slice().
get_pixel_uv()
static av_always_inline void get_pixel_uv (AVFrame * frame, int hsub_log2, int vsub_log2, int x, int y, uint8_t * u, uint8_t * v) static
Definition at line 64 of file vf_chromakey.c.
Referenced by do_chromakey_slice().
do_chromakey_slice()
static int do_chromakey_slice (AVFilterContext * avctx, void * arg, int jobnr, int nb_jobs) static
Definition at line 76 of file vf_chromakey.c.
Referenced by filter_frame().
filter_frame()
static int filter_frame (AVFilterLink * link, AVFrame * frame) static
Definition at line 106 of file vf_chromakey.c.
initialize_chromakey()
static av_cold int initialize_chromakey (AVFilterContext * avctx) static
Definition at line 121 of file vf_chromakey.c.
query_formats()
static av_cold int query_formats (AVFilterContext * avctx) static
Definition at line 136 of file vf_chromakey.c.
config_input()
static av_cold int config_input (AVFilterLink * inlink) static
Definition at line 154 of file vf_chromakey.c.
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (chromakey)
Variable Documentation
chromakey_inputs
const AVFilterPad chromakey_inputs[] static
Initial value:
= {
    {
        .name           = "default",
        .type           = AVMEDIA_TYPE_VIDEO,
        .needs_writable = 1,
        .filter_frame   = filter_frame,
        .config_props   = config_input,
    },
    { NULL }
}
Definition at line 166 of file vf_chromakey.c.
chromakey_outputs
const AVFilterPad chromakey_outputs[] static
Initial value:
= {
    {
        .name           = "default",
        .type           = AVMEDIA_TYPE_VIDEO,
    },
    { NULL }
}
Definition at line 177 of file vf_chromakey.c.
chromakey_options
const AVOption chromakey_options[] static
Initial value:
= {
    { "color", "set the chromakey key color", OFFSET(chromakey_rgba), AV_OPT_TYPE_COLOR, { .str = "black" }, CHAR_MIN, CHAR_MAX, FLAGS },
    { "similarity", "set the chromakey similarity value", OFFSET(similarity), AV_OPT_TYPE_FLOAT, { .dbl = 0.01 }, 0.01, 1.0, FLAGS },
    { "blend", "set the chromakey key blend value", OFFSET(blend), AV_OPT_TYPE_FLOAT, { .dbl = 0.0 }, 0.0, 1.0, FLAGS },
    { "yuv", "color parameter is in yuv instead of rgb", OFFSET(is_yuv), AV_OPT_TYPE_BOOL, { .i64 = 0 }, 0, 1, FLAGS },
    { NULL }
}
Definition at line 188 of file vf_chromakey.c.
ff_vf_chromakey
AVFilter ff_vf_chromakey
Initial value:
= {
    .name          = "chromakey",
    .description   = NULL_IF_CONFIG_SMALL("Turns a certain color into transparency. Operates on YUV colors."),
    .priv_size     = sizeof(ChromakeyContext),
    .priv_class    = &chromakey_class,
    .init          = initialize_chromakey,
    .query_formats = query_formats,
    .inputs        = chromakey_inputs,
    .outputs       = chromakey_outputs,
    .flags         = AVFILTER_FLAG_SUPPORT_TIMELINE_GENERIC | AVFILTER_FLAG_SLICE_THREADS,
}
Definition at line 198 of file vf_chromakey.c.