FFmpeg: libavdevice/vfwcap.c File Reference
vfwcap.c File Reference
#include "libavutil/internal.h"
#include "libavutil/log.h"
#include "libavutil/opt.h"
#include "libavutil/parseutils.h"
#include "libavformat/internal.h"
#include <windows.h>
#include <vfw.h>
#include "avdevice.h"
Data Structures
struct vfw_ctx
Macros
#define HWND_MESSAGE ((HWND) -3)
#define dstruct(pctx, sname, var, type) av_log(pctx, AV_LOG_DEBUG, #var":\t%"type"\n", sname->var)
#define OFFSET(x) offsetof(struct vfw_ctx, x)
#define DEC AV_OPT_FLAG_DECODING_PARAM
Functions
static enum AVPixelFormat vfw_pixfmt (DWORD biCompression, WORD biBitCount)
static enum AVCodecID vfw_codecid (DWORD biCompression)
static void dump_captureparms (AVFormatContext *s, CAPTUREPARMS *cparms)
static void dump_videohdr (AVFormatContext *s, VIDEOHDR *vhdr)
static void dump_bih (AVFormatContext *s, BITMAPINFOHEADER *bih)
static int shall_we_drop (AVFormatContext *s)
static LRESULT CALLBACK videostream_cb (HWND hwnd, LPVIDEOHDR vdhdr)
static int vfw_read_close (AVFormatContext *s)
static int vfw_read_header (AVFormatContext *s)
static int vfw_read_packet (AVFormatContext *s, AVPacket *pkt)
Variables
static const AVOption options []
static const AVClass vfw_class
AVInputFormat ff_vfwcap_demuxer
Macro Definition Documentation
HWND_MESSAGE
#define HWND_MESSAGE ((HWND) -3)
Definition at line 39 of file vfwcap.c.
Referenced by vfw_read_header().
dstruct
#define dstruct (pctx, sname, var, type) av_log(pctx, AV_LOG_DEBUG, #var":\t%"type"\n", sname->var)
Definition at line 94 of file vfwcap.c.
Referenced by dump_bih(), dump_captureparms(), and dump_videohdr().
OFFSET
#define OFFSET (x) offsetof(struct vfw_ctx, x)
Definition at line 466 of file vfwcap.c.
DEC
#define DEC AV_OPT_FLAG_DECODING_PARAM
Definition at line 467 of file vfwcap.c.
Function Documentation
vfw_pixfmt()
static enum AVPixelFormat vfw_pixfmt (DWORD biCompression, WORD biBitCount) static
Definition at line 54 of file vfwcap.c.
Referenced by vfw_read_header().
vfw_codecid()
static enum AVCodecID vfw_codecid (DWORD biCompression) static
Definition at line 82 of file vfwcap.c.
Referenced by vfw_read_header().
dump_captureparms()
static void dump_captureparms (AVFormatContext * s, CAPTUREPARMS * cparms) static
Definition at line 97 of file vfwcap.c.
Referenced by vfw_read_header().
dump_videohdr()
static void dump_videohdr (AVFormatContext * s, VIDEOHDR * vhdr) static
Definition at line 126 of file vfwcap.c.
Referenced by videostream_cb().
dump_bih()
static void dump_bih (AVFormatContext * s, BITMAPINFOHEADER * bih) static
Definition at line 143 of file vfwcap.c.
Referenced by ff_print_AM_MEDIA_TYPE(), and vfw_read_header().
shall_we_drop()
static int shall_we_drop (AVFormatContext * s) static
Definition at line 161 of file vfwcap.c.
Referenced by videostream_cb().
videostream_cb()
static LRESULT CALLBACK videostream_cb (HWND hwnd, LPVIDEOHDR vdhdr) static
Definition at line 177 of file vfwcap.c.
Referenced by vfw_read_header().
vfw_read_close()
static int vfw_read_close (AVFormatContext * s) static
Definition at line 219 of file vfwcap.c.
Referenced by vfw_read_header().
vfw_read_header()
static int vfw_read_header (AVFormatContext * s) static
Definition at line 245 of file vfwcap.c.
vfw_read_packet()
static int vfw_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 437 of file vfwcap.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "video_size", "A string describing frame size, such as 640x480 or hd720.", OFFSET(video_size), AV_OPT_TYPE_STRING, {.str = NULL}, 0, 0, DEC },
    { "framerate", "", OFFSET(framerate), AV_OPT_TYPE_STRING, {.str = "ntsc"}, 0, 0, DEC },
    { NULL },
}
Definition at line 468 of file vfwcap.c.
vfw_class
const AVClass vfw_class static
Initial value:
= {
    .class_name = "VFW indev",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
    .category   = AV_CLASS_CATEGORY_DEVICE_VIDEO_INPUT
}
Definition at line 474 of file vfwcap.c.
ff_vfwcap_demuxer
AVInputFormat ff_vfwcap_demuxer
Initial value:
= {
    .name           = "vfwcap",
    .long_name      = NULL_IF_CONFIG_SMALL("VfW video capture"),
    .priv_data_size = sizeof(struct vfw_ctx),
    .read_header    = vfw_read_header,
    .read_packet    = vfw_read_packet,
    .read_close     = vfw_read_close,
    .flags          = AVFMT_NOFILE,
    .priv_class     = &vfw_class,
}
Definition at line 482 of file vfwcap.c.