FFmpeg: libavcodec/videotoolbox.c File Reference
videotoolbox.c File Reference
#include "config.h"
#include "vda.h"
#include "vda_vt_internal.h"
#include "libavutil/avutil.h"
#include "bytestream.h"
#include "h264dec.h"
#include "mpegvideo.h"
Macros
#define kVTVideoDecoderSpecification_RequireHardwareAcceleratedVideoDecoder CFSTR("RequireHardwareAcceleratedVideoDecoder")
#define VIDEOTOOLBOX_ESDS_EXTRADATA_PADDING 12
#define AV_W8(p, v) *(p) = (v)
Functions
static void videotoolbox_buffer_release (void *opaque, uint8_t *data)
static int videotoolbox_buffer_copy (VTContext *vtctx, const uint8_t *buffer, uint32_t size)
int ff_videotoolbox_alloc_frame (AVCodecContext *avctx, AVFrame *frame)
CFDataRef ff_videotoolbox_avcc_extradata_create (AVCodecContext *avctx)
int ff_videotoolbox_buffer_create (VTContext *vtctx, AVFrame *frame)
int ff_videotoolbox_h264_start_frame (AVCodecContext *avctx, const uint8_t *buffer, uint32_t size)
int ff_videotoolbox_h264_decode_slice (AVCodecContext *avctx, const uint8_t *buffer, uint32_t size)
int ff_videotoolbox_uninit (AVCodecContext *avctx)
Macro Definition Documentation
kVTVideoDecoderSpecification_RequireHardwareAcceleratedVideoDecoder
#define kVTVideoDecoderSpecification_RequireHardwareAcceleratedVideoDecoder CFSTR("RequireHardwareAcceleratedVideoDecoder")
Definition at line 36 of file videotoolbox.c.
Referenced by ff_videotoolbox_uninit().
VIDEOTOOLBOX_ESDS_EXTRADATA_PADDING
#define VIDEOTOOLBOX_ESDS_EXTRADATA_PADDING 12
Definition at line 39 of file videotoolbox.c.
Referenced by ff_videotoolbox_uninit().
AV_W8
#define AV_W8 (p, v) *(p) = (v)
Definition at line 80 of file videotoolbox.c.
Referenced by ff_videotoolbox_avcc_extradata_create().
Function Documentation
videotoolbox_buffer_release()
static void videotoolbox_buffer_release (void * opaque, uint8_t * data) static
Definition at line 41 of file videotoolbox.c.
Referenced by ff_videotoolbox_buffer_create().
videotoolbox_buffer_copy()
static int videotoolbox_buffer_copy (VTContext * vtctx, const uint8_t * buffer, uint32_t size) static
Definition at line 47 of file videotoolbox.c.
Referenced by ff_videotoolbox_h264_start_frame(), and ff_videotoolbox_uninit().
ff_videotoolbox_alloc_frame()
int ff_videotoolbox_alloc_frame (AVCodecContext * avctx, AVFrame * frame)
Definition at line 67 of file videotoolbox.c.
Referenced by ff_videotoolbox_uninit().
ff_videotoolbox_avcc_extradata_create()
CFDataRef ff_videotoolbox_avcc_extradata_create (AVCodecContext * avctx)
Definition at line 82 of file videotoolbox.c.
Referenced by ff_vda_default_init(), and ff_videotoolbox_uninit().
ff_videotoolbox_buffer_create()
int ff_videotoolbox_buffer_create (VTContext * vtctx, AVFrame * frame)
Definition at line 115 of file videotoolbox.c.
Referenced by ff_videotoolbox_uninit(), and vda_h264_end_frame().
ff_videotoolbox_h264_start_frame()
int ff_videotoolbox_h264_start_frame (AVCodecContext * avctx, const uint8_t * buffer, uint32_t size)
Definition at line 134 of file videotoolbox.c.
Referenced by ff_videotoolbox_uninit().
ff_videotoolbox_h264_decode_slice()
int ff_videotoolbox_h264_decode_slice (AVCodecContext * avctx, const uint8_t * buffer, uint32_t size)
Definition at line 150 of file videotoolbox.c.
Referenced by ff_videotoolbox_uninit().
ff_videotoolbox_uninit()
int ff_videotoolbox_uninit (AVCodecContext * avctx)
Definition at line 177 of file videotoolbox.c.