FFmpeg: libavfilter/video.c File Reference
video.c File Reference
#include <string.h>
#include <stdio.h>
#include "libavutil/avassert.h"
#include "libavutil/buffer.h"
#include "libavutil/imgutils.h"
#include "libavutil/mem.h"
#include "avfilter.h"
#include "internal.h"
#include "video.h"
Macros
#define BUFFER_ALIGN 32
Functions
AVFrame * ff_null_get_video_buffer (AVFilterLink *link, int w, int h)
AVFrame * ff_default_get_video_buffer (AVFilterLink *link, int w, int h)
AVFrame * ff_get_video_buffer (AVFilterLink *link, int w, int h)
Request a picture buffer with a specific set of permissions.
Macro Definition Documentation
BUFFER_ALIGN
#define BUFFER_ALIGN 32
Definition at line 35 of file video.c.
Referenced by ff_default_get_video_buffer().
Function Documentation
ff_null_get_video_buffer()
AVFrame* ff_null_get_video_buffer (AVFilterLink * link, int w, int h)
Definition at line 38 of file video.c.
Referenced by get_video_buffer(), and init().
ff_default_get_video_buffer()
AVFrame* ff_default_get_video_buffer (AVFilterLink * link, int w, int h)
Definition at line 43 of file video.c.
Referenced by ff_get_video_buffer(), fixstride(), and get_video_buffer().
ff_get_video_buffer()
AVFrame* ff_get_video_buffer (AVFilterLink * link, int w, int h)
Request a picture buffer with a specific set of permissions.
Parameters
link the output link to the filter from which the buffer will be requested
w the minimum width of the buffer to allocate
h the minimum height of the buffer to allocate
Returns
A reference to the buffer. This must be unreferenced with avfilter_unref_buffer when you are finished with it.
Definition at line 76 of file video.c.
Referenced by alloc_out_frame(), apply_lut(), apply_palette(), blend_frame(), blend_frames16(), blend_frames8(), config_input(), config_output(), config_video(), config_video_output(), create_weave_frame(), draw_background(), ff_filter_frame_framed(), ff_null_get_video_buffer(), filter(), filter_frame(), geq_filter_frame(), get_frame(), get_palette_frame(), get_video_buffer(), hwdownload_filter_frame(), output_single_frame(), plot_cqt(), plot_freqs(), pp_filter_frame(), process_frame(), request_frame(), return_frame(), shuffleplanes_filter_frame(), source_request_frame(), and try_push_frame().