FFmpeg: libavcodec/videotoolboxenc.c File Reference
videotoolboxenc.c File Reference
#include <VideoToolbox/VideoToolbox.h>
#include <CoreVideo/CoreVideo.h>
#include <CoreMedia/CoreMedia.h>
#include <TargetConditionals.h>
#include <Availability.h>
#include "avcodec.h"
#include "libavutil/opt.h"
#include "libavutil/avassert.h"
#include "libavutil/atomic.h"
#include "libavutil/avstring.h"
#include "libavutil/pixdesc.h"
#include "internal.h"
#include <pthread.h>
#include "h264.h"
#include "h264_sei.h"
Data Structures
struct ExtraSEI
struct BufNode
struct VTEncContext
Macros
#define kCVImageBufferColorPrimaries_ITU_R_2020 CFSTR("ITU_R_2020")
#define kCVImageBufferTransferFunction_ITU_R_2020 CFSTR("ITU_R_2020")
#define kCVImageBufferYCbCrMatrix_ITU_R_2020 CFSTR("ITU_R_2020")
#define OFFSET(x) offsetof(VTEncContext, x)
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Enumerations
enum VT_H264Profile {
H264_PROF_AUTO, H264_PROF_BASELINE, H264_PROF_MAIN, H264_PROF_HIGH,
H264_PROF_COUNT
}
enum VTH264Entropy { VT_ENTROPY_NOT_SET, VT_CAVLC, VT_CABAC }
Functions
static int vtenc_populate_extradata (AVCodecContext *avctx, CMVideoCodecType codec_type, CFStringRef profile_level, CFNumberRef gamma_level, CFDictionaryRef enc_info, CFDictionaryRef pixel_buffer_info)
static void vt_release_num (CFNumberRef *refPtr)
NULL-safe release of *refPtr, and sets value to NULL.
static void set_async_error (VTEncContext *vtctx, int err)
static void clear_frame_queue (VTEncContext *vtctx)
static int vtenc_q_pop (VTEncContext *vtctx, bool wait, CMSampleBufferRef *buf, ExtraSEI **sei)
static void vtenc_q_push (VTEncContext *vtctx, CMSampleBufferRef buffer, ExtraSEI *sei)
static int count_nalus (size_t length_code_size, CMSampleBufferRef sample_buffer, int *count)
static CMVideoCodecType get_cm_codec_type (enum AVCodecID id)
static int get_params_size (AVCodecContext *avctx, CMVideoFormatDescriptionRef vid_fmt, size_t *size)
Get the parameter sets from a CMSampleBufferRef.
static int copy_param_sets (AVCodecContext *avctx, CMVideoFormatDescriptionRef vid_fmt, uint8_t *dst, size_t dst_size)
static int set_extradata (AVCodecContext *avctx, CMSampleBufferRef sample_buffer)
static void vtenc_output_callback (void *ctx, void *sourceFrameCtx, OSStatus status, VTEncodeInfoFlags flags, CMSampleBufferRef sample_buffer)
static int get_length_code_size (AVCodecContext *avctx, CMSampleBufferRef sample_buffer, size_t *size)
static bool get_vt_profile_level (AVCodecContext *avctx, CFStringRef *profile_level_val)
static int get_cv_pixel_format (AVCodecContext *avctx, enum AVPixelFormat fmt, enum AVColorRange range, int *av_pixel_format, int *range_guessed)
static void add_color_attr (AVCodecContext *avctx, CFMutableDictionaryRef dict)
static int create_cv_pixel_buffer_info (AVCodecContext *avctx, CFMutableDictionaryRef *dict)
static int get_cv_color_primaries (AVCodecContext *avctx, CFStringRef *primaries)
static int get_cv_transfer_function (AVCodecContext *avctx, CFStringRef *transfer_fnc, CFNumberRef *gamma_level)
static int get_cv_ycbcr_matrix (AVCodecContext *avctx, CFStringRef *matrix)
static int vtenc_create_encoder (AVCodecContext *avctx, CMVideoCodecType codec_type, CFStringRef profile_level, CFNumberRef gamma_level, CFDictionaryRef enc_info, CFDictionaryRef pixel_buffer_info, VTCompressionSessionRef *session)
static av_cold int vtenc_init (AVCodecContext *avctx)
static void vtenc_get_frame_info (CMSampleBufferRef buffer, bool *is_key_frame)
static int is_post_sei_nal_type (int nal_type)
static int find_sei_end (AVCodecContext *avctx, uint8_t *nal_data, size_t nal_size, uint8_t **sei_end)
static int copy_emulation_prev (const uint8_t *src, size_t src_size, uint8_t *dst, ssize_t dst_offset, size_t dst_size)
Copies the data inserting emulation prevention bytes as needed.
static int write_sei (const ExtraSEI *sei, int sei_type, uint8_t *dst, size_t dst_size)
static int copy_replace_length_codes (AVCodecContext *avctx, size_t length_code_size, CMSampleBufferRef sample_buffer, ExtraSEI *sei, uint8_t *dst_data, size_t dst_size)
Copies NAL units and replaces length codes with H.264 Annex B start codes.
static int get_sei_msg_bytes (const ExtraSEI *sei, int type)
Returns a sufficient number of bytes to contain the sei data.
static int vtenc_cm_to_avpacket (AVCodecContext *avctx, CMSampleBufferRef sample_buffer, AVPacket *pkt, ExtraSEI *sei)
static int get_cv_pixel_info (AVCodecContext *avctx, const AVFrame *frame, int *color, int *plane_count, size_t *widths, size_t *heights, size_t *strides, size_t *contiguous_buf_size)
static void free_avframe (void *release_ctx, const void *data, size_t size, size_t plane_count, const void *plane_addresses[])
static int create_cv_pixel_buffer (AVCodecContext *avctx, const AVFrame *frame, CVPixelBufferRef *cv_img)
TARGET_OS_IPHONE.
static int create_encoder_dict_h264 (const AVFrame *frame, CFDictionaryRef *dict_out)
static int vtenc_send_frame (AVCodecContext *avctx, VTEncContext *vtctx, const AVFrame *frame)
static av_cold int vtenc_frame (AVCodecContext *avctx, AVPacket *pkt, const AVFrame *frame, int *got_packet)
static av_cold int vtenc_close (AVCodecContext *avctx)
Variables
static const uint8_t start_code [] = { 0, 0, 0, 1 }
static enum AVPixelFormat pix_fmts []
static const AVOption options []
static const AVClass h264_videotoolbox_class
AVCodec ff_h264_videotoolbox_encoder
Macro Definition Documentation
kCVImageBufferColorPrimaries_ITU_R_2020
#define kCVImageBufferColorPrimaries_ITU_R_2020 CFSTR("ITU_R_2020")
Definition at line 39 of file videotoolboxenc.c.
Referenced by get_cv_color_primaries().
kCVImageBufferTransferFunction_ITU_R_2020
#define kCVImageBufferTransferFunction_ITU_R_2020 CFSTR("ITU_R_2020")
Definition at line 40 of file videotoolboxenc.c.
Referenced by get_cv_transfer_function().
kCVImageBufferYCbCrMatrix_ITU_R_2020
#define kCVImageBufferYCbCrMatrix_ITU_R_2020 CFSTR("ITU_R_2020")
Definition at line 41 of file videotoolboxenc.c.
Referenced by get_cv_ycbcr_matrix().
OFFSET
#define OFFSET (x) offsetof(VTEncContext, x)
Definition at line 2279 of file videotoolboxenc.c.
VE
#define VE AV_OPT_FLAG_VIDEO_PARAM | AV_OPT_FLAG_ENCODING_PARAM
Definition at line 2280 of file videotoolboxenc.c.
Enumeration Type Documentation
VT_H264Profile
enum VT_H264Profile
Enumerator
H264_PROF_AUTO
H264_PROF_BASELINE
H264_PROF_MAIN
H264_PROF_HIGH
H264_PROF_COUNT
Definition at line 44 of file videotoolboxenc.c.
VTH264Entropy
enum VTH264Entropy
Enumerator
VT_ENTROPY_NOT_SET
VT_CAVLC
VT_CABAC
Definition at line 52 of file videotoolboxenc.c.
Function Documentation
vtenc_populate_extradata()
static int vtenc_populate_extradata (AVCodecContext * avctx, CMVideoCodecType codec_type, CFStringRef profile_level, CFNumberRef gamma_level, CFDictionaryRef enc_info, CFDictionaryRef pixel_buffer_info) static
Definition at line 2138 of file videotoolboxenc.c.
Referenced by vtenc_init().
vt_release_num()
static void vt_release_num (CFNumberRef * refPtr) static
NULL-safe release of *refPtr, and sets value to NULL.
Definition at line 118 of file videotoolboxenc.c.
Referenced by create_cv_pixel_buffer_info().
set_async_error()
static void set_async_error (VTEncContext * vtctx, int err) static
Definition at line 127 of file videotoolboxenc.c.
Referenced by clear_frame_queue(), vtenc_output_callback(), and vtenc_q_push().
clear_frame_queue()
static void clear_frame_queue (VTEncContext * vtctx) static
Definition at line 148 of file videotoolboxenc.c.
Referenced by vtenc_close().
vtenc_q_pop()
static int vtenc_q_pop (VTEncContext * vtctx, bool wait, CMSampleBufferRef * buf, ExtraSEI ** sei) static
Definition at line 153 of file videotoolboxenc.c.
Referenced by vtenc_frame(), and vtenc_populate_extradata().
vtenc_q_push()
static void vtenc_q_push (VTEncContext * vtctx, CMSampleBufferRef buffer, ExtraSEI * sei) static
Definition at line 203 of file videotoolboxenc.c.
Referenced by vtenc_output_callback().
count_nalus()
static int count_nalus (size_t length_code_size, CMSampleBufferRef sample_buffer, int * count) static
Definition at line 230 of file videotoolboxenc.c.
Referenced by vtenc_cm_to_avpacket().
get_cm_codec_type()
static CMVideoCodecType get_cm_codec_type (enum AVCodecID id) static
Definition at line 269 of file videotoolboxenc.c.
Referenced by vtenc_init().
get_params_size()
static int get_params_size (AVCodecContext * avctx, CMVideoFormatDescriptionRef vid_fmt, size_t * size) static
Get the parameter sets from a CMSampleBufferRef.
Parameters
dst If *dst isn't NULL, the parameters are copied into existing memory. *dst_size must be set accordingly when *dst != NULL. If *dst is NULL, it will be allocated. In all cases, *dst_size is set to the number of bytes used starting at *dst.
Definition at line 285 of file videotoolboxenc.c.
Referenced by set_extradata(), and vtenc_cm_to_avpacket().
copy_param_sets()
static int copy_param_sets (AVCodecContext * avctx, CMVideoFormatDescriptionRef vid_fmt, uint8_t * dst, size_t dst_size) static
Definition at line 338 of file videotoolboxenc.c.
Referenced by set_extradata(), and vtenc_cm_to_avpacket().
set_extradata()
static int set_extradata (AVCodecContext * avctx, CMSampleBufferRef sample_buffer) static
Definition at line 401 of file videotoolboxenc.c.
Referenced by vtenc_output_callback().
vtenc_output_callback()
static void vtenc_output_callback (void * ctx, void * sourceFrameCtx, OSStatus status, VTEncodeInfoFlags flags, CMSampleBufferRef sample_buffer) static
Definition at line 435 of file videotoolboxenc.c.
Referenced by vtenc_create_encoder().
get_length_code_size()
static int get_length_code_size (AVCodecContext * avctx, CMSampleBufferRef sample_buffer, size_t * size) static
Definition at line 468 of file videotoolboxenc.c.
Referenced by vtenc_cm_to_avpacket().
get_vt_profile_level()
static bool get_vt_profile_level (AVCodecContext * avctx, CFStringRef * profile_level_val) static
Definition at line 504 of file videotoolboxenc.c.
Referenced by vtenc_init().
get_cv_pixel_format()
static int get_cv_pixel_format (AVCodecContext * avctx, enum AVPixelFormat fmt, enum AVColorRange range, int * av_pixel_format, int * range_guessed) static
Definition at line 576 of file videotoolboxenc.c.
Referenced by create_cv_pixel_buffer_info(), and get_cv_pixel_info().
add_color_attr()
static void add_color_attr (AVCodecContext * avctx, CFMutableDictionaryRef dict) static
Definition at line 601 of file videotoolboxenc.c.
Referenced by create_cv_pixel_buffer(), and create_cv_pixel_buffer_info().
create_cv_pixel_buffer_info()
static int create_cv_pixel_buffer_info (AVCodecContext * avctx, CFMutableDictionaryRef * dict) static
Definition at line 623 of file videotoolboxenc.c.
Referenced by vtenc_init().
get_cv_color_primaries()
static int get_cv_color_primaries (AVCodecContext * avctx, CFStringRef * primaries) static
Definition at line 690 of file videotoolboxenc.c.
Referenced by vtenc_init().
get_cv_transfer_function()
static int get_cv_transfer_function (AVCodecContext * avctx, CFStringRef * transfer_fnc, CFNumberRef * gamma_level) static
Definition at line 716 of file videotoolboxenc.c.
Referenced by vtenc_init().
get_cv_ycbcr_matrix()
static int get_cv_ycbcr_matrix (AVCodecContext * avctx, CFStringRef * matrix) static
Definition at line 762 of file videotoolboxenc.c.
Referenced by vtenc_init().
vtenc_create_encoder()
static int vtenc_create_encoder (AVCodecContext * avctx, CMVideoCodecType codec_type, CFStringRef profile_level, CFNumberRef gamma_level, CFDictionaryRef enc_info, CFDictionaryRef pixel_buffer_info, VTCompressionSessionRef * session) static
Definition at line 793 of file videotoolboxenc.c.
Referenced by vtenc_init(), and vtenc_populate_extradata().
vtenc_init()
static av_cold int vtenc_init (AVCodecContext * avctx) static
Definition at line 1047 of file videotoolboxenc.c.
vtenc_get_frame_info()
static void vtenc_get_frame_info (CMSampleBufferRef buffer, bool * is_key_frame) static
Definition at line 1159 of file videotoolboxenc.c.
Referenced by vtenc_cm_to_avpacket().
is_post_sei_nal_type()
static int is_post_sei_nal_type (int nal_type) static
Definition at line 1186 of file videotoolboxenc.c.
Referenced by copy_replace_length_codes().
find_sei_end()
static int find_sei_end (AVCodecContext * avctx, uint8_t * nal_data, size_t nal_size, uint8_t ** sei_end) static
Definition at line 1197 of file videotoolboxenc.c.
Referenced by copy_replace_length_codes().
copy_emulation_prev()
static int copy_emulation_prev (const uint8_t * src, size_t src_size, uint8_t * dst, ssize_t dst_offset, size_t dst_size) static
Copies the data inserting emulation prevention bytes as needed.
Existing data in the destination can be taken into account by providing dst with a dst_offset > 0.
Returns
The number of bytes copied on success. On failure, the negative of the number of bytes needed to copy src is returned.
Definition at line 1261 of file videotoolboxenc.c.
Referenced by get_sei_msg_bytes(), and write_sei().
write_sei()
static int write_sei (const ExtraSEI * sei, int sei_type, uint8_t * dst, size_t dst_size) static
Definition at line 1312 of file videotoolboxenc.c.
Referenced by copy_replace_length_codes().
copy_replace_length_codes()
static int copy_replace_length_codes (AVCodecContext * avctx, size_t length_code_size, CMSampleBufferRef sample_buffer, ExtraSEI * sei, uint8_t * dst_data, size_t dst_size) static
Copies NAL units and replaces length codes with H.264 Annex B start codes.
On failure, the contents of dst_data may have been modified.
Parameters
length_code_size Byte length of each length code
sample_buffer NAL units prefixed with length codes.
sei Optional A53 closed captions SEI data.
dst_data Must be zeroed before calling this function. Contains the copied NAL units prefixed with start codes when the function returns successfully.
dst_size Length of dst_data
Returns
0 on success AVERROR_INVALIDDATA if length_code_size is invalid AVERROR_BUFFER_TOO_SMALL if dst_data is too small or if a length_code in src_data specifies data beyond the end of its buffer.
Definition at line 1385 of file videotoolboxenc.c.
Referenced by vtenc_cm_to_avpacket().
get_sei_msg_bytes()
static int get_sei_msg_bytes (const ExtraSEI * sei, int type) static
Returns a sufficient number of bytes to contain the sei data.
It may be greater than the minimum required.
Definition at line 1542 of file videotoolboxenc.c.
Referenced by vtenc_cm_to_avpacket().
vtenc_cm_to_avpacket()
static int vtenc_cm_to_avpacket (AVCodecContext * avctx, CMSampleBufferRef sample_buffer, AVPacket * pkt, ExtraSEI * sei) static
Definition at line 1559 of file videotoolboxenc.c.
Referenced by vtenc_frame().
get_cv_pixel_info()
static int get_cv_pixel_info (AVCodecContext * avctx, const AVFrame * frame, int * color, int * plane_count, size_t * widths, size_t * heights, size_t * strides, size_t * contiguous_buf_size) static
Definition at line 1669 of file videotoolboxenc.c.
Referenced by create_cv_pixel_buffer().
free_avframe()
static void free_avframe (void * release_ctx, const void * data, size_t size, size_t plane_count, const void * plane_addresses[]) static
Definition at line 1768 of file videotoolboxenc.c.
Referenced by create_cv_pixel_buffer().
create_cv_pixel_buffer()
static int create_cv_pixel_buffer (AVCodecContext * avctx, const AVFrame * frame, CVPixelBufferRef * cv_img) static
TARGET_OS_IPHONE.
Definition at line 1873 of file videotoolboxenc.c.
Referenced by vtenc_send_frame().
create_encoder_dict_h264()
static int create_encoder_dict_h264 (const AVFrame * frame, CFDictionaryRef * dict_out) static
Definition at line 1999 of file videotoolboxenc.c.
Referenced by vtenc_send_frame().
vtenc_send_frame()
static int vtenc_send_frame (AVCodecContext * avctx, VTEncContext * vtctx, const AVFrame * frame) static
Definition at line 2015 of file videotoolboxenc.c.
Referenced by vtenc_frame(), and vtenc_populate_extradata().
vtenc_frame()
static av_cold int vtenc_frame (AVCodecContext * avctx, AVPacket * pkt, const AVFrame * frame, int * got_packet) static
Definition at line 2071 of file videotoolboxenc.c.
vtenc_close()
static av_cold int vtenc_close (AVCodecContext * avctx) static
Definition at line 2240 of file videotoolboxenc.c.
Variable Documentation
start_code
const uint8_t start_code[] = { 0, 0, 0, 1 } static
Definition at line 58 of file videotoolboxenc.c.
Referenced by copy_param_sets(), copy_replace_length_codes(), get_params_size(), and vtenc_cm_to_avpacket().
pix_fmts
enum AVPixelFormat pix_fmts[] static
Initial value:
= {
    AV_PIX_FMT_VIDEOTOOLBOX,
    AV_PIX_FMT_NV12,
    AV_PIX_FMT_YUV420P,
    AV_PIX_FMT_NONE
}
Definition at line 2272 of file videotoolboxenc.c.
options
const AVOption options[] static
Definition at line 2281 of file videotoolboxenc.c.
h264_videotoolbox_class
const AVClass h264_videotoolbox_class static
Initial value:
= {
    .class_name = "h264_videotoolbox",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
}
Definition at line 2321 of file videotoolboxenc.c.
ff_h264_videotoolbox_encoder
AVCodec ff_h264_videotoolbox_encoder
Initial value:
= {
    .name             = "h264_videotoolbox",
    .long_name        = NULL_IF_CONFIG_SMALL("VideoToolbox H.264 Encoder"),
    .type             = AVMEDIA_TYPE_VIDEO,
    .id               = AV_CODEC_ID_H264,
    .priv_data_size   = sizeof(VTEncContext),
    .pix_fmts         = pix_fmts,
    .init             = vtenc_init,
    .encode2          = vtenc_frame,
    .close            = vtenc_close,
    .capabilities     = AV_CODEC_CAP_DELAY,
    .priv_class       = &h264_videotoolbox_class,
    .caps_internal    = FF_CODEC_CAP_INIT_THREADSAFE |
                        FF_CODEC_CAP_INIT_CLEANUP,
}
Definition at line 2328 of file videotoolboxenc.c.