FFmpeg: libavcodec/videodsp.h File Reference
videodsp.h File Reference
Core video DSP helper functions.
#include <stddef.h>
#include <stdint.h>
Data Structures
struct VideoDSPContext
Macros
#define EMULATED_EDGE(depth)
Functions
void ff_videodsp_init (VideoDSPContext *ctx, int bpc)
void ff_videodsp_init_aarch64 (VideoDSPContext *ctx, int bpc)
void ff_videodsp_init_arm (VideoDSPContext *ctx, int bpc)
void ff_videodsp_init_ppc (VideoDSPContext *ctx, int bpc)
void ff_videodsp_init_x86 (VideoDSPContext *ctx, int bpc)
Detailed Description
Core video DSP helper functions.
Definition in file videodsp.h.
Macro Definition Documentation
EMULATED_EDGE
#define EMULATED_EDGE (depth)
Value:
void ff_emulated_edge_mc_ ## depth(uint8_t *dst, const uint8_t *src, \
                                   ptrdiff_t dst_stride, ptrdiff_t src_stride, \
                                   int block_w, int block_h,\
                                   int src_x, int src_y, int w, int h);
Definition at line 32 of file videodsp.h.
Function Documentation
ff_videodsp_init()
void ff_videodsp_init (VideoDSPContext * ctx, int bpc)
Definition at line 38 of file videodsp.c.
Referenced by checkasm_check_videodsp(), dct_init(), dirac_decode_init(), dnxhd_encode_init(), ff_cavs_init(), ff_vp56_init_context(), h264_slice_header_init(), mca(), set_sps(), svq3_decode_init(), update_size(), vp3_decode_init(), and vp78_decode_init().
ff_videodsp_init_aarch64()
void ff_videodsp_init_aarch64 (VideoDSPContext * ctx, int bpc)
Definition at line 26 of file videodsp_init.c.
Referenced by ff_videodsp_init().
ff_videodsp_init_arm()
void ff_videodsp_init_arm (VideoDSPContext * ctx, int bpc)
Definition at line 26 of file videodsp_init_arm.c.
Referenced by ff_videodsp_init().
ff_videodsp_init_ppc()
void ff_videodsp_init_ppc (VideoDSPContext * ctx, int bpc)
Definition at line 33 of file videodsp_ppc.c.
Referenced by ff_videodsp_init().
ff_videodsp_init_x86()
void ff_videodsp_init_x86 (VideoDSPContext * ctx, int bpc)
Definition at line 279 of file videodsp_init.c.
Referenced by ff_videodsp_init().