FFmpeg: libavfilter/vidstabutils.c File Reference
vidstabutils.c File Reference
#include "vidstabutils.h"
Data Structures
struct VS2AVLogCtx
struct to hold a valid context for logging from within vid.stab lib
Functions
VSPixelFormat ff_av2vs_pixfmt (AVFilterContext *ctx, enum AVPixelFormat pf)
convert AV's pixelformat to vid.stab pixelformat
static int vs2av_log (int type, const char *tag, const char *format,...)
wrapper to log vs_log into av_log
void ff_vs_init (void)
sets the memory allocation function and logging constants to av versions
Function Documentation
ff_av2vs_pixfmt()
VSPixelFormat ff_av2vs_pixfmt (AVFilterContext * ctx, enum AVPixelFormat pf)
convert AV's pixelformat to vid.stab pixelformat
Converts an AVPixelFormat to a VSPixelFormat.
Definition at line 24 of file vidstabutils.c.
Referenced by config_input().
vs2av_log()
static int vs2av_log (int type, const char * tag, const char * format, ...) static
wrapper to log vs_log into av_log
Definition at line 50 of file vidstabutils.c.
Referenced by ff_vs_init().
ff_vs_init()
void ff_vs_init (void)
sets the memory allocation function and logging constants to av versions
Initialize libvidstab.
Definition at line 69 of file vidstabutils.c.
Referenced by init().