FFmpeg: libavcodec/vlc.h File Reference
vlc.h File Reference
#include <stdint.h>
Data Structures
struct VLC
struct RL_VLC_ELEM
Macros
#define VLC_TYPE int16_t
#define init_vlc(vlc, nb_bits, nb_codes, bits, bits_wrap, bits_size, codes, codes_wrap, codes_size, flags)
#define INIT_VLC_LE 2
#define INIT_VLC_USE_NEW_STATIC 4
#define INIT_VLC_STATIC(vlc, bits, a, b, c, d, e, f, g, static_size)
Functions
int ff_init_vlc_sparse (VLC *vlc, int nb_bits, int nb_codes, const void *bits, int bits_wrap, int bits_size, const void *codes, int codes_wrap, int codes_size, const void *symbols, int symbols_wrap, int symbols_size, int flags)
void ff_free_vlc (VLC *vlc)
Macro Definition Documentation
VLC_TYPE
#define VLC_TYPE int16_t
Definition at line 24 of file vlc.h.
Referenced by alloc_table(), build_table(), decode_init(), decode_spectrum_and_dequant(), ff_ccitt_unpack_init(), ff_dca_init_vlcs(), ff_ivi_init_static_vlc(), ff_rl_init_vlc(), ff_vc1_init_common(), init_2d_vlc_rl(), init_vlcs(), ir2_decode_init(), main(), mpc7_decode_init(), mpc8_decode_init(), read_sbr_envelope(), read_sbr_noise(), rv40_init_tables(), svq1_decode_init(), unpack_vlcs(), write_VLC_TYPE_array(), and x8_vlc_init().
init_vlc
#define init_vlc (vlc, nb_bits, nb_codes, bits, bits_wrap, bits_size, codes, codes_wrap, codes_size, flags)
Value:
ff_init_vlc_sparse(vlc, nb_bits, nb_codes,          \
                       bits, bits_wrap, bits_size,      \
                       codes, codes_wrap, codes_size,   \
                       NULL, 0, 0, flags)
Definition at line 38 of file vlc.h.
Referenced by atrac3_init_static_data(), decode_init(), decode_init_static(), decode_rle(), dnxhd_init_vlc(), ff_cfhd_init_vlcs(), ff_dvvideo_init(), ff_h264_decode_init_vlc(), ff_hq_init_vlcs(), ff_hqx_init_vlcs(), ff_rl_init_vlc(), ff_vc1_init_common(), generate_joint_tables(), huff_reader_build_canonical(), imc_decode_init(), init_2d_vlc_rl(), init_coef_vlc(), init_cook_vlc_tables(), init_vlcs(), ir2_decode_init(), ivi_create_huff_from_desc(), mimic_decode_init(), mp_decode_frame(), mpc7_decode_init(), mpc8_decode_init(), on2avc_decode_init(), qdm2_init_vlc(), read_huffman_tables(), read_old_huffman_tables(), rv40_init_tables(), smacker_decode_header_tree(), smka_decode_frame(), svq1_decode_init(), tm2_build_huff_table(), vorbis_parse_setup_hdr_codebooks(), vp3_decode_init(), and wma_decode_init().
INIT_VLC_LE
#define INIT_VLC_LE 2
Definition at line 54 of file vlc.h.
Referenced by build_table(), decode_init(), init_vlcs(), ir2_decode_init(), ivi_create_huff_from_desc(), qdm2_init_vlc(), smacker_decode_header_tree(), smka_decode_frame(), and vorbis_parse_setup_hdr_codebooks().
INIT_VLC_USE_NEW_STATIC
#define INIT_VLC_USE_NEW_STATIC 4
Definition at line 55 of file vlc.h.
Referenced by atrac3_init_static_data(), build_canonical_huff(), build_table(), decode_init(), decode_init_static(), ff_atrac3p_init_vlcs(), ff_ccitt_unpack_init(), ff_h264_decode_init_vlc(), ff_init_vlc_sparse(), ff_rl_init_vlc(), ff_vc1_init_common(), imc_decode_init(), init_2d_vlc_rl(), init_vlcs(), ir2_decode_init(), ivi_create_huff_from_desc(), mpc7_decode_init(), mpc8_decode_init(), qdm2_init_vlc(), rv34_gen_vlc(), rv40_init_tables(), and svq1_decode_init().
INIT_VLC_STATIC
#define INIT_VLC_STATIC (vlc, bits, a, b, c, d, e, f, g, static_size)
Value:
do {                                                                   \
        static VLC_TYPE table[static_size][2];                             \
        (vlc)->table           = table;                                    \
        (vlc)->table_allocated = static_size;                              \
        init_vlc(vlc, bits, a, b, c, d, e, f, g, INIT_VLC_USE_NEW_STATIC); \
    } while (0)
Definition at line 57 of file vlc.h.
Referenced by aac_static_table_init(), decode_init(), ff_ccitt_unpack_init(), ff_h263_decode_init_vlc(), ff_mpeg12_init_vlcs(), ff_mpeg4videodec_static_init(), ff_msmpeg4_decode_init(), ff_vc1_init_common(), h261_decode_init_vlc(), init_static(), init_vlcs(), rv10_decode_init(), svq1_decode_init(), and wmavoice_init_static_data().
Function Documentation
ff_init_vlc_sparse()
int ff_init_vlc_sparse (VLC * vlc, int nb_bits, int nb_codes, const void * bits, int bits_wrap, int bits_size, const void * codes, int codes_wrap, int codes_size, const void * symbols, int symbols_wrap, int symbols_size, int flags)
Definition at line 275 of file bitstream.c.
Referenced by build_canonical_huff(), build_huff(), build_huff10(), build_huff_tree(), build_vlc(), ff_atrac3p_init_vlcs(), ff_ccitt_unpack_init(), generate_joint_tables(), huff_build(), huff_build10(), init_ralf_vlc(), init_vlcs(), mpc8_decode_init(), mss4_init_vlc(), on2avc_decode_init(), read_code_table(), rv34_gen_vlc(), and rv40_init_tables().
ff_free_vlc()
void ff_free_vlc (VLC * vlc)
Definition at line 360 of file bitstream.c.
Referenced by build_vlc(), cfhd_close_decoder(), cook_decode_close(), decode_argb_frame(), decode_close(), decode_end(), decode_plane(), decode_plane10(), decode_rgb24_frame(), decode_rle(), decode_yuv_frame(), dnxhd_decode_close(), dnxhd_init_vlc(), ff_dvvideo_init(), ff_ivi_dec_huff_desc(), ff_ivi_decode_close(), ff_mjpeg_decode_dht(), ff_mjpeg_decode_end(), ff_wma_end(), fraps2_decode_plane(), free_vlcs(), generate_joint_tables(), hq_hqa_decode_close(), hqx_decode_close(), huff_build(), huff_build10(), image_ctx_free(), ivi_free_buffers(), jpg_free_context(), magy_decode_end(), mimic_decode_end(), mp_decode_frame(), mss4_free_vlcs(), on2avc_free_vlcs(), read_huffman_code_normal(), read_huffman_tables(), read_old_huffman_tables(), smacker_decode_header_tree(), smka_decode_frame(), tm2_free_codes(), vorbis_free(), vp3_decode_end(), vp6_build_huff_tree(), and vp6_decode_free_context().