FFmpeg: libavcodec/vmdvideo.c File Reference
vmdvideo.c File Reference
Sierra VMD video decoder by Vladimir "VAG" Gneushev (vagsoft at mail.ru) for more information on the Sierra VMD format, visit: http://www.pcisys.net/~melanson/codecs/.
#include <string.h>
#include "libavutil/common.h"
#include "libavutil/intreadwrite.h"
#include "avcodec.h"
#include "internal.h"
#include "bytestream.h"
Data Structures
struct VmdVideoContext
Macros
#define VMD_HEADER_SIZE 0x330
#define PALETTE_COUNT 256
#define QUEUE_SIZE 0x1000
#define QUEUE_MASK 0x0FFF
Functions
static int lz_unpack (const unsigned char *src, int src_len, unsigned char *dest, int dest_len)
static int rle_unpack (const unsigned char *src, unsigned char *dest, int src_count, int src_size, int dest_len)
static int vmd_decode (VmdVideoContext *s, AVFrame *frame)
static av_cold int vmdvideo_decode_end (AVCodecContext *avctx)
static av_cold int vmdvideo_decode_init (AVCodecContext *avctx)
static int vmdvideo_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
Variables
AVCodec ff_vmdvideo_decoder
Detailed Description
Sierra VMD video decoder by Vladimir "VAG" Gneushev (vagsoft at mail.ru) for more information on the Sierra VMD format, visit: http://www.pcisys.net/~melanson/codecs/.
The video decoder outputs PAL8 colorspace data. The decoder expects a 0x330-byte VMD file header to be transmitted via extradata during codec initialization. Each encoded frame that is sent to this decoder is expected to be prepended with the appropriate 16-byte frame information record from the VMD file.
Definition in file vmdvideo.c.
Macro Definition Documentation
VMD_HEADER_SIZE
#define VMD_HEADER_SIZE 0x330
Definition at line 45 of file vmdvideo.c.
Referenced by vmdvideo_decode_init().
PALETTE_COUNT
#define PALETTE_COUNT 256
Definition at line 46 of file vmdvideo.c.
Referenced by vmd_decode(), vmdvideo_decode_frame(), and vmdvideo_decode_init().
QUEUE_SIZE
#define QUEUE_SIZE 0x1000
Definition at line 63 of file vmdvideo.c.
Referenced by lz_unpack().
QUEUE_MASK
#define QUEUE_MASK 0x0FFF
Definition at line 64 of file vmdvideo.c.
Referenced by lz_unpack().
Function Documentation
lz_unpack()
static int lz_unpack (const unsigned char * src, int src_len, unsigned char * dest, int dest_len) static
Definition at line 66 of file vmdvideo.c.
Referenced by vmd_decode().
rle_unpack()
static int rle_unpack (const unsigned char * src, unsigned char * dest, int src_count, int src_size, int dest_len) static
Definition at line 139 of file vmdvideo.c.
Referenced by vmd_decode().
vmd_decode()
static int vmd_decode (VmdVideoContext * s, AVFrame * frame) static
Definition at line 183 of file vmdvideo.c.
Referenced by vmdvideo_decode_frame().
vmdvideo_decode_end()
static av_cold int vmdvideo_decode_end (AVCodecContext * avctx) static
Definition at line 370 of file vmdvideo.c.
Referenced by vmdvideo_decode_init().
vmdvideo_decode_init()
static av_cold int vmdvideo_decode_init (AVCodecContext * avctx) static
Definition at line 381 of file vmdvideo.c.
vmdvideo_decode_frame()
static int vmdvideo_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 429 of file vmdvideo.c.
Variable Documentation
ff_vmdvideo_decoder
AVCodec ff_vmdvideo_decoder
Initial value:
= {
    .name           = "vmdvideo",
    .long_name      = NULL_IF_CONFIG_SMALL("Sierra VMD video"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_VMDVIDEO,
    .priv_data_size = sizeof(VmdVideoContext),
    .init           = vmdvideo_decode_init,
    .close          = vmdvideo_decode_end,
    .decode         = vmdvideo_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 465 of file vmdvideo.c.