FFmpeg: libavcodec/vmnc.c File Reference
vmnc.c File Reference
VMware Screen Codec (VMnc) decoder As Alex Beregszaszi discovered, this is effectively RFB data dump.
#include <stdio.h>
#include <stdlib.h>
#include "libavutil/common.h"
#include "libavutil/intreadwrite.h"
#include "avcodec.h"
#include "internal.h"
#include "bytestream.h"
Data Structures
struct VmncContext
Enumerations
enum EncTypes {
MAGIC_WMVd = 0x574D5664, MAGIC_WMVe, MAGIC_WMVf, MAGIC_WMVg,
MAGIC_WMVh, MAGIC_WMVi, MAGIC_WMVj
}
enum HexTile_Flags {
HT_RAW = 1, HT_BKG = 2, HT_FG = 4, HT_SUB = 8,
HT_CLR = 16
}
Functions
static av_always_inline int vmnc_get_pixel (GetByteContext *gb, int bpp, int be)
static void load_cursor (VmncContext *c)
static void put_cursor (uint8_t *dst, int stride, VmncContext *c, int dx, int dy)
static av_always_inline void paint_rect (uint8_t *dst, int dx, int dy, int w, int h, int color, int bpp, int stride)
static av_always_inline void paint_raw (uint8_t *dst, int w, int h, GetByteContext *gb, int bpp, int be, int stride)
static int decode_hextile (VmncContext *c, uint8_t *dst, GetByteContext *gb, int w, int h, int stride)
static void reset_buffers (VmncContext *c)
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int decode_init (AVCodecContext *avctx)
static av_cold int decode_end (AVCodecContext *avctx)
Variables
AVCodec ff_vmnc_decoder
Detailed Description
VMware Screen Codec (VMnc) decoder As Alex Beregszaszi discovered, this is effectively RFB data dump.
Definition in file vmnc.c.
Enumeration Type Documentation
EncTypes
enum EncTypes
Enumerator
MAGIC_WMVd
MAGIC_WMVe
MAGIC_WMVf
MAGIC_WMVg
MAGIC_WMVh
MAGIC_WMVi
MAGIC_WMVj
Definition at line 37 of file vmnc.c.
HexTile_Flags
enum HexTile_Flags
Enumerator
HT_RAW
HT_BKG
HT_FG
HT_SUB
HT_CLR
Definition at line 47 of file vmnc.c.
Function Documentation
vmnc_get_pixel()
static av_always_inline int vmnc_get_pixel (GetByteContext * gb, int bpp, int be) static
Definition at line 78 of file vmnc.c.
Referenced by decode_hextile(), load_cursor(), and paint_raw().
load_cursor()
static void load_cursor (VmncContext * c) static
Definition at line 96 of file vmnc.c.
Referenced by decode_frame().
put_cursor()
static void put_cursor (uint8_t * dst, int stride, VmncContext * c, int dx, int dy) static
Definition at line 131 of file vmnc.c.
Referenced by decode_frame().
paint_rect()
static av_always_inline void paint_rect (uint8_t * dst, int dx, int dy, int w, int h, int color, int bpp, int stride) static
Definition at line 191 of file vmnc.c.
Referenced by decode_hextile().
paint_raw()
static av_always_inline void paint_raw (uint8_t * dst, int w, int h, GetByteContext * gb, int bpp, int be, int stride) static
Definition at line 221 of file vmnc.c.
Referenced by decode_frame(), and decode_hextile().
decode_hextile()
static int decode_hextile (VmncContext * c, uint8_t * dst, GetByteContext * gb, int w, int h, int stride) static
Definition at line 245 of file vmnc.c.
Referenced by decode_frame().
reset_buffers()
static void reset_buffers (VmncContext * c) static
Definition at line 309 of file vmnc.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 319 of file vmnc.c.
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 523 of file vmnc.c.
decode_end()
static av_cold int decode_end (AVCodecContext * avctx) static
Definition at line 559 of file vmnc.c.
Variable Documentation
ff_vmnc_decoder
AVCodec ff_vmnc_decoder
Initial value:
= {
    .name           = "vmnc",
    .long_name      = NULL_IF_CONFIG_SMALL("VMware Screen Codec / VMware Video"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_VMNC,
    .priv_data_size = sizeof(VmncContext),
    .init           = decode_init,
    .close          = decode_end,
    .decode         = decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 571 of file vmnc.c.