FFmpeg: libavformat/voc.h File Reference
voc.h File Reference
#include "avformat.h"
#include "internal.h"
Data Structures
struct VocDecContext
Enumerations
enum VocType {
VOC_TYPE_EOF = 0x00, VOC_TYPE_VOICE_DATA = 0x01, VOC_TYPE_VOICE_DATA_CONT = 0x02, VOC_TYPE_SILENCE = 0x03,
VOC_TYPE_MARKER = 0x04, VOC_TYPE_ASCII = 0x05, VOC_TYPE_REPETITION_START = 0x06, VOC_TYPE_REPETITION_END = 0x07,
VOC_TYPE_EXTENDED = 0x08, VOC_TYPE_NEW_VOICE_DATA = 0x09
}
Functions
int ff_voc_get_packet (AVFormatContext *s, AVPacket *pkt, AVStream *st, int max_size)
Variables
const unsigned char ff_voc_magic [21]
const AVCodecTag ff_voc_codec_tags []
Enumeration Type Documentation
VocType
enum VocType
Enumerator
VOC_TYPE_EOF
VOC_TYPE_VOICE_DATA
VOC_TYPE_VOICE_DATA_CONT
VOC_TYPE_SILENCE
VOC_TYPE_MARKER
VOC_TYPE_ASCII
VOC_TYPE_REPETITION_START
VOC_TYPE_REPETITION_END
VOC_TYPE_EXTENDED
VOC_TYPE_NEW_VOICE_DATA
Definition at line 33 of file voc.h.
Function Documentation
ff_voc_get_packet()
int ff_voc_get_packet (AVFormatContext * s, AVPacket * pkt, AVStream * st, int max_size)
Definition at line 27 of file voc_packet.c.
Referenced by avs_read_audio_packet(), read_packet(), and voc_read_packet().
Variable Documentation
ff_voc_magic
const unsigned char ff_voc_magic[21]
Definition at line 25 of file voc.c.
Referenced by voc_probe(), and voc_write_header().
ff_voc_codec_tags
const AVCodecTag ff_voc_codec_tags[]
Definition at line 27 of file voc.c.
Referenced by ff_voc_get_packet().