FFmpeg: libavcodec/vorbisdec.c File Reference
vorbisdec.c File Reference
Vorbis I decoder.
#include <inttypes.h>
#include <math.h>
#include "libavutil/avassert.h"
#include "libavutil/float_dsp.h"
#include "avcodec.h"
#include "fft.h"
#include "get_bits.h"
#include "internal.h"
#include "vorbis.h"
#include "vorbisdsp.h"
#include "xiph.h"
Data Structures
struct vorbis_codebook
struct vorbis_floor
union vorbis_floor::vorbis_floor_u
struct vorbis_floor::vorbis_floor_u::vorbis_floor0_s
struct vorbis_floor::vorbis_floor_u::vorbis_floor1_s
struct vorbis_residue
struct vorbis_mapping
struct vorbis_mode
struct vorbis_context
Macros
#define BITSTREAM_READER_LE
#define V_NB_BITS 8
#define V_NB_BITS2 11
#define V_MAX_VLCS (1 << 16)
#define V_MAX_PARTITIONS (1 << 20)
#define BARK(x) (13.1f * atan(0.00074f * (x)) + 2.24f * atan(1.85e-8f * (x) * (x)) + 1e-4f * (x))
#define VALIDATE_INDEX(idx, limit)
#define GET_VALIDATED_INDEX(idx, bits, limit)
Typedefs
typedef union vorbis_floor_u vorbis_floor_data
typedef struct vorbis_floor0_s vorbis_floor0
typedef struct vorbis_floor1_s vorbis_floor1
typedef int(* vorbis_floor_decode_func) (struct vorbis_context_s *, vorbis_floor_data *, float *)
Functions
static float vorbisfloat2float (unsigned val)
static void vorbis_free (vorbis_context *vc)
static int vorbis_parse_setup_hdr_codebooks (vorbis_context *vc)
static int vorbis_parse_setup_hdr_tdtransforms (vorbis_context *vc)
static int vorbis_floor0_decode (vorbis_context *vc, vorbis_floor_data *vfu, float *vec)
static int create_map (vorbis_context *vc, unsigned floor_number)
static int vorbis_floor1_decode (vorbis_context *vc, vorbis_floor_data *vfu, float *vec)
static int vorbis_parse_setup_hdr_floors (vorbis_context *vc)
static int vorbis_parse_setup_hdr_residues (vorbis_context *vc)
static int vorbis_parse_setup_hdr_mappings (vorbis_context *vc)
static int vorbis_parse_setup_hdr_modes (vorbis_context *vc)
static int vorbis_parse_setup_hdr (vorbis_context *vc)
static int vorbis_parse_id_hdr (vorbis_context *vc)
static av_cold int vorbis_decode_init (AVCodecContext *avctx)
static av_always_inline int setup_classifs (vorbis_context *vc, vorbis_residue *vr, uint8_t *do_not_decode, unsigned ch_used, int partition_count, int ptns_to_read)
static av_always_inline int vorbis_residue_decode_internal (vorbis_context *vc, vorbis_residue *vr, unsigned ch, uint8_t *do_not_decode, float *vec, unsigned vlen, unsigned ch_left, int vr_type)
static int vorbis_residue_decode (vorbis_context *vc, vorbis_residue *vr, unsigned ch, uint8_t *do_not_decode, float *vec, unsigned vlen, unsigned ch_left)
void ff_vorbis_inverse_coupling (float *mag, float *ang, intptr_t blocksize)
static int vorbis_parse_audio_packet (vorbis_context *vc, float **floor_ptr)
static int vorbis_decode_frame (AVCodecContext *avctx, void *data, int *got_frame_ptr, AVPacket *avpkt)
static av_cold int vorbis_decode_close (AVCodecContext *avctx)
static av_cold void vorbis_decode_flush (AVCodecContext *avctx)
Variables
static const char idx_err_str [] = "Index value %d out of range (0 - %d) for %s at %s:%i\n"
AVCodec ff_vorbis_decoder
Detailed Description
Vorbis I decoder.
Author
Denes Balatoni (dbalatoni programozo hu)
This file is part of FFmpeg.
FFmpeg is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
FFmpeg is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with FFmpeg; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
Author
Denes Balatoni (dbalatoni programozo hu)
Definition in file vorbisdec.c.
Macro Definition Documentation
BITSTREAM_READER_LE
#define BITSTREAM_READER_LE
Definition at line 35 of file vorbisdec.c.
V_NB_BITS
#define V_NB_BITS 8
Definition at line 44 of file vorbisdec.c.
Referenced by vorbis_parse_setup_hdr_codebooks().
V_NB_BITS2
#define V_NB_BITS2 11
Definition at line 45 of file vorbisdec.c.
Referenced by vorbis_parse_setup_hdr_codebooks().
V_MAX_VLCS
#define V_MAX_VLCS (1 << 16)
Definition at line 46 of file vorbisdec.c.
Referenced by vorbis_parse_setup_hdr_codebooks().
V_MAX_PARTITIONS
#define V_MAX_PARTITIONS (1 << 20)
Definition at line 47 of file vorbisdec.c.
Referenced by vorbis_parse_setup_hdr_residues().
BARK
#define BARK (x) (13.1f * atan(0.00074f * (x)) + 2.24f * atan(1.85e-8f * (x) * (x)) + 1e-4f * (x))
Definition at line 159 of file vorbisdec.c.
Referenced by create_map().
VALIDATE_INDEX
#define VALIDATE_INDEX (idx, limit)
Value:
if (idx >= limit) {\
        av_log(vc->avctx, AV_LOG_ERROR,\
               idx_err_str,\
               (int)(idx), (int)(limit - 1), #idx, __FILE__, __LINE__);\
        return AVERROR_INVALIDDATA;\
    }
Definition at line 163 of file vorbisdec.c.
Referenced by vorbis_parse_setup_hdr_floors().
GET_VALIDATED_INDEX
#define GET_VALIDATED_INDEX (idx, bits, limit)
Value:
{\
        idx = get_bits(gb, bits);\
        VALIDATE_INDEX(idx, limit)\
    }
Definition at line 170 of file vorbisdec.c.
Referenced by vorbis_parse_audio_packet(), vorbis_parse_setup_hdr_floors(), vorbis_parse_setup_hdr_mappings(), vorbis_parse_setup_hdr_modes(), and vorbis_parse_setup_hdr_residues().
Typedef Documentation
vorbis_floor_data
typedef union vorbis_floor_u vorbis_floor_data
Definition at line 58 of file vorbisdec.c.
vorbis_floor0
typedef struct vorbis_floor0_s vorbis_floor0
Definition at line 59 of file vorbisdec.c.
vorbis_floor1
typedef struct vorbis_floor1_s vorbis_floor1
Definition at line 60 of file vorbisdec.c.
vorbis_floor_decode_func
typedef int(* vorbis_floor_decode_func) (struct vorbis_context_s *, vorbis_floor_data *, float *)
Definition at line 64 of file vorbisdec.c.
Function Documentation
vorbisfloat2float()
static float vorbisfloat2float (unsigned val) static
Definition at line 176 of file vorbisdec.c.
Referenced by vorbis_parse_setup_hdr_codebooks().
vorbis_free()
static void vorbis_free (vorbis_context * vc) static
Definition at line 188 of file vorbisdec.c.
Referenced by vorbis_decode_close(), vorbis_decode_frame(), and vorbis_decode_init().
vorbis_parse_setup_hdr_codebooks()
static int vorbis_parse_setup_hdr_codebooks (vorbis_context * vc) static
Definition at line 238 of file vorbisdec.c.
Referenced by vorbis_parse_setup_hdr().
vorbis_parse_setup_hdr_tdtransforms()
static int vorbis_parse_setup_hdr_tdtransforms (vorbis_context * vc) static
Definition at line 473 of file vorbisdec.c.
Referenced by vorbis_parse_setup_hdr().
vorbis_floor0_decode()
static int vorbis_floor0_decode (vorbis_context * vc, vorbis_floor_data * vfu, float * vec) static
Definition at line 1095 of file vorbisdec.c.
Referenced by vorbis_parse_setup_hdr_floors(), and vorbis_parse_setup_hdr_tdtransforms().
create_map()
static int create_map (vorbis_context * vc, unsigned floor_number) static
Definition at line 850 of file vorbisdec.c.
Referenced by vorbis_parse_setup_hdr_floors(), and vorbis_parse_setup_hdr_tdtransforms().
vorbis_floor1_decode()
static int vorbis_floor1_decode (vorbis_context * vc, vorbis_floor_data * vfu, float * vec) static
Definition at line 1203 of file vorbisdec.c.
Referenced by vorbis_parse_setup_hdr_floors(), and vorbis_parse_setup_hdr_tdtransforms().
vorbis_parse_setup_hdr_floors()
static int vorbis_parse_setup_hdr_floors (vorbis_context * vc) static
Definition at line 499 of file vorbisdec.c.
Referenced by vorbis_parse_setup_hdr().
vorbis_parse_setup_hdr_residues()
static int vorbis_parse_setup_hdr_residues (vorbis_context * vc) static
Definition at line 689 of file vorbisdec.c.
Referenced by vorbis_parse_setup_hdr().
vorbis_parse_setup_hdr_mappings()
static int vorbis_parse_setup_hdr_mappings (vorbis_context * vc) static
Definition at line 770 of file vorbisdec.c.
Referenced by vorbis_parse_setup_hdr().
vorbis_parse_setup_hdr_modes()
static int vorbis_parse_setup_hdr_modes (vorbis_context * vc) static
Definition at line 885 of file vorbisdec.c.
Referenced by vorbis_parse_setup_hdr().
vorbis_parse_setup_hdr()
static int vorbis_parse_setup_hdr (vorbis_context * vc) static
Definition at line 914 of file vorbisdec.c.
Referenced by vorbis_decode_frame(), and vorbis_decode_init().
vorbis_parse_id_hdr()
static int vorbis_parse_id_hdr (vorbis_context * vc) static
Definition at line 960 of file vorbisdec.c.
Referenced by vorbis_decode_frame(), and vorbis_decode_init().
vorbis_decode_init()
static av_cold int vorbis_decode_init (AVCodecContext * avctx) static
Definition at line 1030 of file vorbisdec.c.
setup_classifs()
static av_always_inline int setup_classifs (vorbis_context * vc, vorbis_residue * vr, uint8_t * do_not_decode, unsigned ch_used, int partition_count, int ptns_to_read) static
Definition at line 1330 of file vorbisdec.c.
Referenced by vorbis_residue_decode_internal().
vorbis_residue_decode_internal()
static av_always_inline int vorbis_residue_decode_internal (vorbis_context * vc, vorbis_residue * vr, unsigned ch, uint8_t * do_not_decode, float * vec, unsigned vlen, unsigned ch_left, int vr_type) static
Definition at line 1374 of file vorbisdec.c.
Referenced by vorbis_residue_decode().
vorbis_residue_decode()
static int vorbis_residue_decode (vorbis_context * vc, vorbis_residue * vr, unsigned ch, uint8_t * do_not_decode, float * vec, unsigned vlen, unsigned ch_left) inline static
Definition at line 1531 of file vorbisdec.c.
Referenced by vorbis_parse_audio_packet().
ff_vorbis_inverse_coupling()
void ff_vorbis_inverse_coupling (float * mag, float * ang, intptr_t blocksize)
Definition at line 1549 of file vorbisdec.c.
Referenced by ff_vorbisdsp_init().
vorbis_parse_audio_packet()
static int vorbis_parse_audio_packet (vorbis_context * vc, float ** floor_ptr) static
Definition at line 1575 of file vorbisdec.c.
Referenced by vorbis_decode_frame().
vorbis_decode_frame()
static int vorbis_decode_frame (AVCodecContext * avctx, void * data, int * got_frame_ptr, AVPacket * avpkt) static
Definition at line 1738 of file vorbisdec.c.
vorbis_decode_close()
static av_cold int vorbis_decode_close (AVCodecContext * avctx) static
Definition at line 1833 of file vorbisdec.c.
vorbis_decode_flush()
static av_cold void vorbis_decode_flush (AVCodecContext * avctx) static
Definition at line 1842 of file vorbisdec.c.
Variable Documentation
idx_err_str
const char idx_err_str[] = "Index value %d out of range (0 - %d) for %s at %s:%i\n" static
Definition at line 162 of file vorbisdec.c.
ff_vorbis_decoder
AVCodec ff_vorbis_decoder
Initial value:
= {
    .name            = "vorbis",
    .long_name       = NULL_IF_CONFIG_SMALL("Vorbis"),
    .type            = AVMEDIA_TYPE_AUDIO,
    .id              = AV_CODEC_ID_VORBIS,
    .priv_data_size  = sizeof(vorbis_context),
    .init            = vorbis_decode_init,
    .close           = vorbis_decode_close,
    .decode          = vorbis_decode_frame,
    .flush           = vorbis_decode_flush,
    .capabilities    = AV_CODEC_CAP_DR1,
    .channel_layouts = ff_vorbis_channel_layouts,
    .sample_fmts     = (const enum AVSampleFormat[]) { AV_SAMPLE_FMT_FLTP,
                                                       AV_SAMPLE_FMT_NONE },
}
Definition at line 1854 of file vorbisdec.c.