FFmpeg: libavformat/vorbiscomment.c File Reference
vorbiscomment.c File Reference
#include "avformat.h"
#include "metadata.h"
#include "vorbiscomment.h"
#include "libavcodec/bytestream.h"
#include "libavutil/dict.h"
Functions
int64_t ff_vorbiscomment_length (AVDictionary *m, const char *vendor_string)
Calculate the length in bytes of a VorbisComment.
int ff_vorbiscomment_write (uint8_t **p, AVDictionary **m, const char *vendor_string)
Write a VorbisComment into a buffer.
Variables
const AVMetadataConv ff_vorbiscomment_metadata_conv []
VorbisComment metadata conversion mapping.
Function Documentation
ff_vorbiscomment_length()
int64_t ff_vorbiscomment_length (AVDictionary * m, const char * vendor_string)
Calculate the length in bytes of a VorbisComment.
This is the minimum size required by ff_vorbiscomment_write().
Parameters
m The metadata structure to be parsed. For no metadata, set to NULL.
vendor_string The vendor string to be added into the VorbisComment. For no string, set to an empty string.
Returns
The length in bytes.
Definition at line 41 of file vorbiscomment.c.
Referenced by flac_write_block_comment(), ogg_write_vorbiscomment(), and put_flac_codecpriv().
ff_vorbiscomment_write()
int ff_vorbiscomment_write (uint8_t ** p, AVDictionary ** m, const char * vendor_string)
Write a VorbisComment into a buffer.
The buffer, p, must have enough data to hold the whole VorbisComment. The minimum size required can be obtained by passing the same AVDictionary and vendor_string to ff_vorbiscomment_length()
Parameters
p The buffer in which to write.
m The metadata struct to write.
vendor_string The vendor string to write.
Definition at line 54 of file vorbiscomment.c.
Referenced by flac_write_block_comment(), ogg_write_vorbiscomment(), and put_flac_codecpriv().
Variable Documentation
ff_vorbiscomment_metadata_conv
const AVMetadataConv ff_vorbiscomment_metadata_conv[]
Initial value:
= {
    { "ALBUMARTIST", "album_artist"},
    { "TRACKNUMBER", "track"  },
    { "DISCNUMBER",  "disc"   },
    { "DESCRIPTION", "comment" },
    { 0 }
}
VorbisComment metadata conversion mapping.
from Ogg Vorbis I format specification: comment field and header specification http://xiph.org/vorbis/doc/v-comment.html
Definition at line 33 of file vorbiscomment.c.
Referenced by ff_vorbis_comment(), flac_write_block_comment(), and ogg_write_vorbiscomment().