FFmpeg: libavcodec/vorbisdsp.h File Reference
vorbisdsp.h File Reference
#include <stdint.h>
Data Structures
struct VorbisDSPContext
Functions
void ff_vorbisdsp_init (VorbisDSPContext *dsp)
void ff_vorbisdsp_init_aarch64 (VorbisDSPContext *dsp)
void ff_vorbisdsp_init_x86 (VorbisDSPContext *dsp)
void ff_vorbisdsp_init_arm (VorbisDSPContext *dsp)
void ff_vorbisdsp_init_ppc (VorbisDSPContext *dsp)
Function Documentation
ff_vorbisdsp_init()
void ff_vorbisdsp_init (VorbisDSPContext * dsp)
Definition at line 24 of file vorbisdsp.c.
Referenced by vorbis_decode_init().
ff_vorbisdsp_init_aarch64()
void ff_vorbisdsp_init_aarch64 (VorbisDSPContext * dsp)
Definition at line 27 of file vorbisdsp_init.c.
Referenced by ff_vorbisdsp_init().
ff_vorbisdsp_init_x86()
void ff_vorbisdsp_init_x86 (VorbisDSPContext * dsp)
Definition at line 32 of file vorbisdsp_init.c.
Referenced by ff_vorbisdsp_init().
ff_vorbisdsp_init_arm()
void ff_vorbisdsp_init_arm (VorbisDSPContext * dsp)
Definition at line 30 of file vorbisdsp_init_arm.c.
Referenced by ff_vorbisdsp_init().
ff_vorbisdsp_init_ppc()
void ff_vorbisdsp_init_ppc (VorbisDSPContext * dsp)
Definition at line 55 of file vorbisdsp_altivec.c.
Referenced by ff_vorbisdsp_init().