FFmpeg: libavcodec/vorbis.c File Reference
vorbis.c File Reference
Common code for Vorbis I encoder and decoder.
#include "libavutil/common.h"
#include "avcodec.h"
#include "vorbis.h"
Functions
unsigned int ff_vorbis_nth_root (unsigned int x, unsigned int n)
int ff_vorbis_len2vlc (uint8_t *bits, uint32_t *codes, unsigned num)
int ff_vorbis_ready_floor1_list (AVCodecContext *avctx, vorbis_floor1_entry *list, int values)
static void render_line_unrolled (intptr_t x, int y, int x1, intptr_t sy, int ady, int adx, float *buf)
static void render_line (int x0, int y0, int x1, int y1, float *buf)
void ff_vorbis_floor1_render_list (vorbis_floor1_entry *list, int values, uint16_t *y_list, int *flag, int multiplier, float *out, int samples)
Detailed Description
Common code for Vorbis I encoder and decoder.
Author
Denes Balatoni (dbalatoni programozo hu)
This file is part of FFmpeg.
FFmpeg is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
FFmpeg is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with FFmpeg; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
Author
Denes Balatoni (dbalatoni programozo hu)
Definition in file vorbis.c.
Function Documentation
ff_vorbis_nth_root()
unsigned int ff_vorbis_nth_root (unsigned int x, unsigned int n)
Definition at line 38 of file vorbis.c.
Referenced by cb_lookup_vals(), and vorbis_parse_setup_hdr_codebooks().
ff_vorbis_len2vlc()
int ff_vorbis_len2vlc (uint8_t * bits, uint32_t * codes, unsigned num)
Definition at line 56 of file vorbis.c.
Referenced by ready_codebook(), and vorbis_parse_setup_hdr_codebooks().
ff_vorbis_ready_floor1_list()
int ff_vorbis_ready_floor1_list (AVCodecContext * avctx, vorbis_floor1_entry * list, int values)
Definition at line 106 of file vorbis.c.
Referenced by create_vorbis_context(), and vorbis_parse_setup_hdr_floors().
render_line_unrolled()
static void render_line_unrolled (intptr_t x, int y, int x1, intptr_t sy, int ady, int adx, float * buf) inline static
Definition at line 146 of file vorbis.c.
Referenced by render_line().
render_line()
static void render_line (int x0, int y0, int x1, int y1, float * buf) static
Definition at line 169 of file vorbis.c.
Referenced by ff_vorbis_floor1_render_list().
ff_vorbis_floor1_render_list()
void ff_vorbis_floor1_render_list (vorbis_floor1_entry * list, int values, uint16_t * y_list, int * flag, int multiplier, float * out, int samples)
Definition at line 196 of file vorbis.c.
Referenced by floor_encode(), and vorbis_floor1_decode().