FFmpeg: libavcodec/arm/vp3dsp_init_arm.c File Reference
vp3dsp_init_arm.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/arm/cpu.h"
#include "libavcodec/vp3dsp.h"
Functions
void ff_vp3_idct_put_neon (uint8_t *dest, int line_size, int16_t *data)
void ff_vp3_idct_add_neon (uint8_t *dest, int line_size, int16_t *data)
void ff_vp3_idct_dc_add_neon (uint8_t *dest, int line_size, int16_t *data)
void ff_vp3_v_loop_filter_neon (uint8_t *, int, int *)
void ff_vp3_h_loop_filter_neon (uint8_t *, int, int *)
av_cold void ff_vp3dsp_init_arm (VP3DSPContext *c, int flags)
Function Documentation
ff_vp3_idct_put_neon()
void ff_vp3_idct_put_neon (uint8_t * dest, int line_size, int16_t * data)
Referenced by ff_vp3dsp_init_arm().
ff_vp3_idct_add_neon()
void ff_vp3_idct_add_neon (uint8_t * dest, int line_size, int16_t * data)
Referenced by ff_vp3dsp_init_arm().
ff_vp3_idct_dc_add_neon()
void ff_vp3_idct_dc_add_neon (uint8_t * dest, int line_size, int16_t * data)
Referenced by ff_vp3dsp_init_arm().
ff_vp3_v_loop_filter_neon()
void ff_vp3_v_loop_filter_neon (uint8_t * , int , int *)
Referenced by ff_vp3dsp_init_arm().
ff_vp3_h_loop_filter_neon()
void ff_vp3_h_loop_filter_neon (uint8_t * , int , int *)
Referenced by ff_vp3dsp_init_arm().
ff_vp3dsp_init_arm()
av_cold void ff_vp3dsp_init_arm (VP3DSPContext * c, int flags)
Definition at line 33 of file vp3dsp_init_arm.c.
Referenced by ff_vp3dsp_init().