FFmpeg: libavcodec/vp3dsp.h File Reference
vp3dsp.h File Reference
#include <stddef.h>
#include <stdint.h>
Data Structures
struct VP3DSPContext
Functions
void ff_vp3dsp_init (VP3DSPContext *c, int flags)
void ff_vp3dsp_init_arm (VP3DSPContext *c, int flags)
void ff_vp3dsp_init_ppc (VP3DSPContext *c, int flags)
void ff_vp3dsp_init_x86 (VP3DSPContext *c, int flags)
Function Documentation
ff_vp3dsp_init()
void ff_vp3dsp_init (VP3DSPContext * c, int flags)
Definition at line 280 of file vp3dsp.c.
Referenced by ff_vp56_init_context(), and vp3_decode_init().
ff_vp3dsp_init_arm()
void ff_vp3dsp_init_arm (VP3DSPContext * c, int flags)
Definition at line 33 of file vp3dsp_init_arm.c.
Referenced by ff_vp3dsp_init().
ff_vp3dsp_init_ppc()
void ff_vp3dsp_init_ppc (VP3DSPContext * c, int flags)
Definition at line 194 of file vp3dsp_altivec.c.
Referenced by ff_vp3dsp_init().
ff_vp3dsp_init_x86()
void ff_vp3dsp_init_x86 (VP3DSPContext * c, int flags)
Definition at line 47 of file vp3dsp_init.c.
Referenced by ff_vp3dsp_init().