FFmpeg: libavcodec/x86/vp3dsp_init.c File Reference
vp3dsp_init.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/x86/cpu.h"
#include "libavcodec/avcodec.h"
#include "libavcodec/vp3dsp.h"
Functions
void ff_vp3_idct_put_mmx (uint8_t *dest, int line_size, int16_t *block)
void ff_vp3_idct_add_mmx (uint8_t *dest, int line_size, int16_t *block)
void ff_vp3_idct_put_sse2 (uint8_t *dest, int line_size, int16_t *block)
void ff_vp3_idct_add_sse2 (uint8_t *dest, int line_size, int16_t *block)
void ff_vp3_idct_dc_add_mmxext (uint8_t *dest, int line_size, int16_t *block)
void ff_vp3_v_loop_filter_mmxext (uint8_t *src, int stride, int *bounding_values)
void ff_vp3_h_loop_filter_mmxext (uint8_t *src, int stride, int *bounding_values)
void ff_put_vp_no_rnd_pixels8_l2_mmx (uint8_t *dst, const uint8_t *a, const uint8_t *b, ptrdiff_t stride, int h)
av_cold void ff_vp3dsp_init_x86 (VP3DSPContext *c, int flags)
Function Documentation
ff_vp3_idct_put_mmx()
void ff_vp3_idct_put_mmx (uint8_t * dest, int line_size, int16_t * block)
Referenced by ff_vp3dsp_init_x86().
ff_vp3_idct_add_mmx()
void ff_vp3_idct_add_mmx (uint8_t * dest, int line_size, int16_t * block)
Referenced by ff_vp3dsp_init_x86().
ff_vp3_idct_put_sse2()
void ff_vp3_idct_put_sse2 (uint8_t * dest, int line_size, int16_t * block)
Referenced by ff_vp3dsp_init_x86().
ff_vp3_idct_add_sse2()
void ff_vp3_idct_add_sse2 (uint8_t * dest, int line_size, int16_t * block)
Referenced by ff_vp3dsp_init_x86().
ff_vp3_idct_dc_add_mmxext()
void ff_vp3_idct_dc_add_mmxext (uint8_t * dest, int line_size, int16_t * block)
Referenced by ff_vp3dsp_init_x86().
ff_vp3_v_loop_filter_mmxext()
void ff_vp3_v_loop_filter_mmxext (uint8_t * src, int stride, int * bounding_values)
Referenced by ff_vp3dsp_init_x86().
ff_vp3_h_loop_filter_mmxext()
void ff_vp3_h_loop_filter_mmxext (uint8_t * src, int stride, int * bounding_values)
Referenced by ff_vp3dsp_init_x86().
ff_put_vp_no_rnd_pixels8_l2_mmx()
void ff_put_vp_no_rnd_pixels8_l2_mmx (uint8_t * dst, const uint8_t * a, const uint8_t * b, ptrdiff_t stride, int h)
Referenced by ff_vp3dsp_init_x86().
ff_vp3dsp_init_x86()
av_cold void ff_vp3dsp_init_x86 (VP3DSPContext * c, int flags)
Definition at line 47 of file vp3dsp_init.c.
Referenced by ff_vp3dsp_init().