FFmpeg: libavcodec/vp56dsp.h File Reference
vp56dsp.h File Reference
#include <stdint.h>
#include "avcodec.h"
Data Structures
struct VP56DSPContext
Functions
void ff_vp6_filter_diag4_c (uint8_t *dst, uint8_t *src, int stride, const int16_t *h_weights, const int16_t *v_weights)
void ff_vp56dsp_init (VP56DSPContext *s, enum AVCodecID codec)
void ff_vp6dsp_init_arm (VP56DSPContext *s, enum AVCodecID codec)
void ff_vp6dsp_init_x86 (VP56DSPContext *c, enum AVCodecID codec)
Function Documentation
ff_vp6_filter_diag4_c()
void ff_vp6_filter_diag4_c (uint8_t * dst, uint8_t * src, int stride, const int16_t * h_weights, const int16_t * v_weights)
Definition at line 30 of file vp6dsp.c.
Referenced by ff_vp56dsp_init().
ff_vp56dsp_init()
void ff_vp56dsp_init (VP56DSPContext * s, enum AVCodecID codec)
Definition at line 80 of file vp56dsp.c.
Referenced by ff_vp56_init_context().
ff_vp6dsp_init_arm()
void ff_vp6dsp_init_arm (VP56DSPContext * s, enum AVCodecID codec)
Definition at line 31 of file vp6dsp_init_arm.c.
Referenced by ff_vp56dsp_init().
ff_vp6dsp_init_x86()
void ff_vp6dsp_init_x86 (VP56DSPContext * c, enum AVCodecID codec)
Definition at line 33 of file vp6dsp_init.c.
Referenced by ff_vp56dsp_init().