FFmpeg: libavcodec/vp56rac.c File Reference
vp56rac.c File Reference
#include "libavutil/common.h"
#include "vp56.h"
Functions
void ff_vp56_init_range_decoder (VP56RangeCoder *c, const uint8_t *buf, int buf_size)
Variables
const uint8_t ff_vp56_norm_shift [256]
vp56 specific range coder implementation
Function Documentation
ff_vp56_init_range_decoder()
void ff_vp56_init_range_decoder (VP56RangeCoder * c, const uint8_t * buf, int buf_size)
Definition at line 40 of file vp56rac.c.
Referenced by decode_frame_header(), setup_partitions(), vp5_parse_header(), vp6_parse_header(), vp7_decode_frame_header(), vp8_decode_frame_header(), and vp9_decode_frame().
Variable Documentation
ff_vp56_norm_shift
const uint8_t ff_vp56_norm_shift[256]
Initial value:
= {
 8,7,6,6,5,5,5,5,4,4,4,4,4,4,4,4,
 3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
 2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
 2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
}
vp56 specific range coder implementation
Definition at line 25 of file vp56rac.c.
Referenced by vp56_rac_renorm().