FFmpeg: libavcodec/vp5.c File Reference
vp5.c File Reference
VP5 compatible video decoder.
#include <stdlib.h>
#include <string.h>
#include "avcodec.h"
#include "internal.h"
#include "vp56.h"
#include "vp56data.h"
#include "vp5data.h"
Functions
static int vp5_parse_header (VP56Context *s, const uint8_t *buf, int buf_size)
static void vp5_parse_vector_adjustment (VP56Context *s, VP56mv *vect)
static void vp5_parse_vector_models (VP56Context *s)
static int vp5_parse_coeff_models (VP56Context *s)
static void vp5_parse_coeff (VP56Context *s)
static void vp5_default_models_init (VP56Context *s)
static av_cold int vp5_decode_init (AVCodecContext *avctx)
Variables
AVCodec ff_vp5_decoder
Detailed Description
VP5 compatible video decoder.
Definition in file vp5.c.
Function Documentation
vp5_parse_header()
static int vp5_parse_header (VP56Context * s, const uint8_t * buf, int buf_size) static
Definition at line 37 of file vp5.c.
Referenced by vp5_decode_init().
vp5_parse_vector_adjustment()
static void vp5_parse_vector_adjustment (VP56Context * s, VP56mv * vect) static
Definition at line 79 of file vp5.c.
Referenced by vp5_decode_init().
vp5_parse_vector_models()
static void vp5_parse_vector_models (VP56Context * s) static
Definition at line 103 of file vp5.c.
Referenced by vp5_decode_init().
vp5_parse_coeff_models()
static int vp5_parse_coeff_models (VP56Context * s) static
Definition at line 126 of file vp5.c.
Referenced by vp5_decode_init().
vp5_parse_coeff()
static void vp5_parse_coeff (VP56Context * s) static
Definition at line 173 of file vp5.c.
Referenced by vp5_decode_init().
vp5_default_models_init()
static void vp5_default_models_init (VP56Context * s) static
Definition at line 250 of file vp5.c.
Referenced by vp5_decode_init().
vp5_decode_init()
static av_cold int vp5_decode_init (AVCodecContext * avctx) static
Definition at line 265 of file vp5.c.
Variable Documentation
ff_vp5_decoder
AVCodec ff_vp5_decoder
Initial value:
= {
    .name           = "vp5",
    .long_name      = NULL_IF_CONFIG_SMALL("On2 VP5"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_VP5,
    .priv_data_size = sizeof(VP56Context),
    .init           = vp5_decode_init,
    .close          = ff_vp56_free,
    .decode         = ff_vp56_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 283 of file vp5.c.