FFmpeg: libavcodec/vp6.c File Reference
vp6.c File Reference
VP6 compatible video decoder.
#include <stdlib.h>
#include "avcodec.h"
#include "get_bits.h"
#include "huffman.h"
#include "internal.h"
#include "vp56.h"
#include "vp56data.h"
#include "vp6data.h"
Macros
#define VP6_MAX_HUFF_SIZE 12
Functions
static void vp6_parse_coeff (VP56Context *s)
static void vp6_parse_coeff_huffman (VP56Context *s)
static int vp6_parse_header (VP56Context *s, const uint8_t *buf, int buf_size)
static void vp6_coeff_order_table_init (VP56Context *s)
static void vp6_default_models_init (VP56Context *s)
static void vp6_parse_vector_models (VP56Context *s)
static int vp6_huff_cmp (const void *va, const void *vb)
static int vp6_build_huff_tree (VP56Context *s, uint8_t coeff_model[], const uint8_t *map, unsigned size, VLC *vlc)
static int vp6_parse_coeff_models (VP56Context *s)
static void vp6_parse_vector_adjustment (VP56Context *s, VP56mv *vect)
static unsigned vp6_get_nb_null (VP56Context *s)
Read number of consecutive blocks with null DC or AC.
static int vp6_block_variance (uint8_t *src, int stride)
static void vp6_filter_hv4 (uint8_t *dst, uint8_t *src, int stride, int delta, const int16_t *weights)
static void vp6_filter_diag2 (VP56Context *s, uint8_t *dst, uint8_t *src, int stride, int h_weight, int v_weight)
static void vp6_filter (VP56Context *s, uint8_t *dst, uint8_t *src, int offset1, int offset2, int stride, VP56mv mv, int mask, int select, int luma)
static av_cold void vp6_decode_init_context (VP56Context *s)
static av_cold int vp6_decode_init (AVCodecContext *avctx)
static av_cold void vp6_decode_free_context (VP56Context *s)
static av_cold int vp6_decode_free (AVCodecContext *avctx)
Variables
AVCodec ff_vp6_decoder
AVCodec ff_vp6f_decoder
AVCodec ff_vp6a_decoder
Detailed Description
VP6 compatible video decoder.
The VP6F decoder accepts an optional 1 byte extradata. It is composed of:
upper 4 bits: difference between encoded width and visible width
lower 4 bits: difference between encoded height and visible height
Definition in file vp6.c.
Macro Definition Documentation
VP6_MAX_HUFF_SIZE
#define VP6_MAX_HUFF_SIZE 12
Definition at line 41 of file vp6.c.
Referenced by vp6_build_huff_tree().
Function Documentation
vp6_parse_coeff()
static void vp6_parse_coeff (VP56Context * s) static
Definition at line 442 of file vp6.c.
Referenced by vp6_parse_header().
vp6_parse_coeff_huffman()
static void vp6_parse_coeff_huffman (VP56Context * s) static
Definition at line 383 of file vp6.c.
Referenced by vp6_parse_header().
vp6_parse_header()
static int vp6_parse_header (VP56Context * s, const uint8_t * buf, int buf_size) static
Definition at line 46 of file vp6.c.
Referenced by vp6_decode_init_context().
vp6_coeff_order_table_init()
static void vp6_coeff_order_table_init (VP56Context * s) static
Definition at line 178 of file vp6.c.
Referenced by vp6_default_models_init(), and vp6_parse_coeff_models().
vp6_default_models_init()
static void vp6_default_models_init (VP56Context * s) static
Definition at line 189 of file vp6.c.
Referenced by vp6_decode_init_context().
vp6_parse_vector_models()
static void vp6_parse_vector_models (VP56Context * s) static
Definition at line 207 of file vp6.c.
Referenced by vp6_decode_init_context().
vp6_huff_cmp()
static int vp6_huff_cmp (const void * va, const void * vb) static
Definition at line 232 of file vp6.c.
Referenced by vp6_build_huff_tree().
vp6_build_huff_tree()
static int vp6_build_huff_tree (VP56Context * s, uint8_t coeff_model[], const uint8_t * map, unsigned size, VLC * vlc) static
Definition at line 238 of file vp6.c.
Referenced by vp6_parse_coeff_models().
vp6_parse_coeff_models()
static int vp6_parse_coeff_models (VP56Context * s) static
Definition at line 260 of file vp6.c.
Referenced by vp6_decode_init_context().
vp6_parse_vector_adjustment()
static void vp6_parse_vector_adjustment (VP56Context * s, VP56mv * vect) static
Definition at line 329 of file vp6.c.
Referenced by vp6_decode_init_context().
vp6_get_nb_null()
static unsigned vp6_get_nb_null (VP56Context * s) static
Read number of consecutive blocks with null DC or AC.
This value is < 74.
Definition at line 371 of file vp6.c.
Referenced by vp6_parse_coeff_huffman().
vp6_block_variance()
static int vp6_block_variance (uint8_t * src, int stride) static
Definition at line 517 of file vp6.c.
Referenced by vp6_filter().
vp6_filter_hv4()
static void vp6_filter_hv4 (uint8_t * dst, uint8_t * src, int stride, int delta, const int16_t * weights) static
Definition at line 532 of file vp6.c.
Referenced by vp6_filter().
vp6_filter_diag2()
static void vp6_filter_diag2 (VP56Context * s, uint8_t * dst, uint8_t * src, int stride, int h_weight, int v_weight) static
Definition at line 549 of file vp6.c.
Referenced by vp6_filter().
vp6_filter()
static void vp6_filter (VP56Context * s, uint8_t * dst, uint8_t * src, int offset1, int offset2, int stride, VP56mv mv, int mask, int select, int luma) static
Definition at line 557 of file vp6.c.
Referenced by vp6_decode_init_context().
vp6_decode_init_context()
static av_cold void vp6_decode_init_context (VP56Context * s) static
Definition at line 630 of file vp6.c.
Referenced by vp6_decode_init(), and vp6_filter().
vp6_decode_init()
static av_cold int vp6_decode_init (AVCodecContext * avctx) static
Definition at line 609 of file vp6.c.
vp6_decode_free_context()
static av_cold void vp6_decode_free_context (VP56Context * s) static
Definition at line 660 of file vp6.c.
Referenced by vp6_decode_free(), and vp6_decode_init_context().
vp6_decode_free()
static av_cold int vp6_decode_free (AVCodecContext * avctx) static
Definition at line 644 of file vp6.c.
Variable Documentation
ff_vp6_decoder
AVCodec ff_vp6_decoder
Initial value:
= {
    .name           = "vp6",
    .long_name      = NULL_IF_CONFIG_SMALL("On2 VP6"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_VP6,
    .priv_data_size = sizeof(VP56Context),
    .init           = vp6_decode_init,
    .close          = vp6_decode_free,
    .decode         = ff_vp56_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 673 of file vp6.c.
ff_vp6f_decoder
AVCodec ff_vp6f_decoder
Initial value:
= {
    .name           = "vp6f",
    .long_name      = NULL_IF_CONFIG_SMALL("On2 VP6 (Flash version)"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_VP6F,
    .priv_data_size = sizeof(VP56Context),
    .init           = vp6_decode_init,
    .close          = vp6_decode_free,
    .decode         = ff_vp56_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 686 of file vp6.c.
ff_vp6a_decoder
AVCodec ff_vp6a_decoder
Initial value:
= {
    .name           = "vp6a",
    .long_name      = NULL_IF_CONFIG_SMALL("On2 VP6 (Flash version, with alpha channel)"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_VP6A,
    .priv_data_size = sizeof(VP56Context),
    .init           = vp6_decode_init,
    .close          = vp6_decode_free,
    .decode         = ff_vp56_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_SLICE_THREADS,
}
Definition at line 699 of file vp6.c.