FFmpeg: libavcodec/arm/vp6dsp_init_arm.c File Reference
vp6dsp_init_arm.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/arm/cpu.h"
#include "libavcodec/avcodec.h"
#include "libavcodec/vp56dsp.h"
Functions
void ff_vp6_edge_filter_hor_neon (uint8_t *yuv, int stride, int t)
void ff_vp6_edge_filter_ver_neon (uint8_t *yuv, int stride, int t)
av_cold void ff_vp6dsp_init_arm (VP56DSPContext *s, enum AVCodecID codec)
Function Documentation
ff_vp6_edge_filter_hor_neon()
void ff_vp6_edge_filter_hor_neon (uint8_t * yuv, int stride, int t)
Referenced by ff_vp6dsp_init_arm().
ff_vp6_edge_filter_ver_neon()
void ff_vp6_edge_filter_ver_neon (uint8_t * yuv, int stride, int t)
Referenced by ff_vp6dsp_init_arm().
ff_vp6dsp_init_arm()
av_cold void ff_vp6dsp_init_arm (VP56DSPContext * s, enum AVCodecID codec)
Definition at line 31 of file vp6dsp_init_arm.c.
Referenced by ff_vp56dsp_init().