FFmpeg: libavcodec/x86/vp6dsp_init.c File Reference
vp6dsp_init.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/x86/cpu.h"
#include "libavcodec/vp56dsp.h"
Functions
void ff_vp6_filter_diag4_mmx (uint8_t *dst, uint8_t *src, int stride, const int16_t *h_weights, const int16_t *v_weights)
void ff_vp6_filter_diag4_sse2 (uint8_t *dst, uint8_t *src, int stride, const int16_t *h_weights, const int16_t *v_weights)
av_cold void ff_vp6dsp_init_x86 (VP56DSPContext *c, enum AVCodecID codec)
Function Documentation
ff_vp6_filter_diag4_mmx()
void ff_vp6_filter_diag4_mmx (uint8_t * dst, uint8_t * src, int stride, const int16_t * h_weights, const int16_t * v_weights)
Referenced by ff_vp6dsp_init_x86().
ff_vp6_filter_diag4_sse2()
void ff_vp6_filter_diag4_sse2 (uint8_t * dst, uint8_t * src, int stride, const int16_t * h_weights, const int16_t * v_weights)
Referenced by ff_vp6dsp_init_x86().
ff_vp6dsp_init_x86()
av_cold void ff_vp6dsp_init_x86 (VP56DSPContext * c, enum AVCodecID codec)
Definition at line 33 of file vp6dsp_init.c.
Referenced by ff_vp56dsp_init().