FFmpeg: libavcodec/vp8.h File Reference
vp8.h File Reference
#include "libavutil/buffer.h"
#include "libavutil/thread.h"
#include "h264pred.h"
#include "thread.h"
#include "vp56.h"
#include "vp8dsp.h"
Data Structures
struct VP8FilterStrength
struct VP8Macroblock
struct VP8ThreadData
struct VP8Frame
struct VP8intmv
struct VP8Context
Macros
#define VP8_MAX_QUANT 127
#define MODE_I4x4 4
#define EDGE_EMU_LINESIZE 32
#define MAX_THREADS 8
Enumerations
enum dct_token {
DCT_0, DCT_1, DCT_2, DCT_3,
DCT_4, DCT_CAT1, DCT_CAT2, DCT_CAT3,
DCT_CAT4, DCT_CAT5, DCT_CAT6, DCT_EOB,
NUM_DCT_TOKENS
}
enum inter_mvmode { VP8_MVMODE_ZERO = MODE_I4x4 + 1, VP8_MVMODE_MV, VP8_MVMODE_SPLIT }
enum inter_splitmvmode {
VP8_SPLITMVMODE_16x8 = 0, VP8_SPLITMVMODE_8x16, VP8_SPLITMVMODE_8x8, VP8_SPLITMVMODE_4x4,
VP8_SPLITMVMODE_NONE
}
Functions
int ff_vp8_decode_init (AVCodecContext *avctx)
int ff_vp8_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
int ff_vp8_decode_free (AVCodecContext *avctx)
Macro Definition Documentation
VP8_MAX_QUANT
#define VP8_MAX_QUANT 127
Definition at line 37 of file vp8.h.
MODE_I4x4
#define MODE_I4x4 4
Definition at line 57 of file vp8.h.
Referenced by decode_mb_coeffs(), decode_mb_mode(), decode_mb_row_no_filter(), filter_level_for_mb(), idct_mb(), intra_predict(), and update_lf_deltas().
EDGE_EMU_LINESIZE
#define EDGE_EMU_LINESIZE 32
Definition at line 120 of file vp8.h.
Referenced by vp8_mc_chroma(), and vp8_mc_luma().
MAX_THREADS
#define MAX_THREADS 8
Definition at line 135 of file vp8.h.
Enumeration Type Documentation
dct_token
enum dct_token
Enumerator
DCT_0
DCT_1
DCT_2
DCT_3
DCT_4
DCT_CAT1
DCT_CAT2
DCT_CAT3
DCT_CAT4
DCT_CAT5
DCT_CAT6
DCT_EOB
NUM_DCT_TOKENS
Definition at line 39 of file vp8.h.
inter_mvmode
enum inter_mvmode
Enumerator
VP8_MVMODE_ZERO
VP8_MVMODE_MV
VP8_MVMODE_SPLIT
Definition at line 59 of file vp8.h.
inter_splitmvmode
enum inter_splitmvmode
Enumerator
VP8_SPLITMVMODE_16x8
2 16x8 blocks (vertical)
VP8_SPLITMVMODE_8x16
2 8x16 blocks (horizontal)
VP8_SPLITMVMODE_8x8
2x2 blocks of 8x8px each
VP8_SPLITMVMODE_4x4
4x4 blocks of 4x4px each
VP8_SPLITMVMODE_NONE
(only used in prediction) no split MVs
Definition at line 65 of file vp8.h.
Function Documentation
ff_vp8_decode_init()
int ff_vp8_decode_init (AVCodecContext * avctx)
Definition at line 2767 of file vp8.c.
Referenced by ff_vp8_decode_init(), and vp8_lossy_decode_frame().
ff_vp8_decode_frame()
int ff_vp8_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt)
Definition at line 2683 of file vp8.c.
Referenced by ff_vp8_decode_init(), and vp8_lossy_decode_frame().
ff_vp8_decode_free()
int ff_vp8_decode_free (AVCodecContext * avctx)
Definition at line 2697 of file vp8.c.
Referenced by ff_vp8_decode_init(), vp78_decode_init(), and webp_decode_close().