FFmpeg: libavcodec/vp8dsp.h File Reference
vp8dsp.h File Reference
VP8 compatible video decoder.
#include <stddef.h>
#include <stdint.h>
Data Structures
struct VP8DSPContext
Macros
#define IS_VP7 1
#define IS_VP8 0
Typedefs
typedef void(* vp8_mc_func) (uint8_t *dst, ptrdiff_t dstStride, uint8_t *src, ptrdiff_t srcStride, int h, int x, int y)
Functions
void ff_put_vp8_pixels16_c (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int h, int x, int y)
void ff_put_vp8_pixels8_c (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int h, int x, int y)
void ff_put_vp8_pixels4_c (uint8_t *dst, uint8_t *src, ptrdiff_t stride, int h, int x, int y)
void ff_vp7dsp_init (VP8DSPContext *c)
void ff_vp78dsp_init (VP8DSPContext *c)
void ff_vp78dsp_init_arm (VP8DSPContext *c)
void ff_vp78dsp_init_ppc (VP8DSPContext *c)
void ff_vp78dsp_init_x86 (VP8DSPContext *c)
void ff_vp8dsp_init (VP8DSPContext *c)
void ff_vp8dsp_init_arm (VP8DSPContext *c)
void ff_vp8dsp_init_x86 (VP8DSPContext *c)
void ff_vp8dsp_init_mips (VP8DSPContext *c)
Detailed Description
VP8 compatible video decoder.
Definition in file vp8dsp.h.
Macro Definition Documentation
IS_VP7
#define IS_VP7 1
Definition at line 103 of file vp8dsp.h.
Referenced by ff_vp8_decode_frame(), vp78_decode_init(), vp7_decode_block_coeffs_internal(), vp7_decode_mb_row_sliced(), vp7_decode_mv_mb_modes(), vp7_decode_mvs(), vp7_filter_common(), and vp7_update_dimensions().
IS_VP8
#define IS_VP8 0
Definition at line 104 of file vp8dsp.h.
Referenced by ff_vp8_decode_frame(), ff_vp8_decode_init(), vp8_decode_block_coeffs_internal(), vp8_decode_mb_row_sliced(), vp8_decode_mv_mb_modes(), vp8_decode_mvs(), vp8_filter_common(), and vp8_update_dimensions().
Typedef Documentation
vp8_mc_func
typedef void(* vp8_mc_func) (uint8_t *dst, ptrdiff_t dstStride, uint8_t *src, ptrdiff_t srcStride, int h, int x, int y)
Definition at line 33 of file vp8dsp.h.
Function Documentation
ff_put_vp8_pixels16_c()
void ff_put_vp8_pixels16_c (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int h, int x, int y)
ff_put_vp8_pixels8_c()
void ff_put_vp8_pixels8_c (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int h, int x, int y)
ff_put_vp8_pixels4_c()
void ff_put_vp8_pixels4_c (uint8_t * dst, uint8_t * src, ptrdiff_t stride, int h, int x, int y)
ff_vp7dsp_init()
void ff_vp7dsp_init (VP8DSPContext * c)
Referenced by ff_vp78dsp_init(), and vp78_decode_init().
ff_vp78dsp_init()
void ff_vp78dsp_init (VP8DSPContext * c)
Definition at line 664 of file vp8dsp.c.
Referenced by check_mc(), and vp78_decode_init().
ff_vp78dsp_init_arm()
void ff_vp78dsp_init_arm (VP8DSPContext * c)
Definition at line 26 of file vp8dsp_init_arm.c.
Referenced by ff_vp78dsp_init().
ff_vp78dsp_init_ppc()
void ff_vp78dsp_init_ppc (VP8DSPContext * c)
Definition at line 328 of file vp8dsp_altivec.c.
Referenced by ff_vp78dsp_init().
ff_vp78dsp_init_x86()
void ff_vp78dsp_init_x86 (VP8DSPContext * c)
Definition at line 317 of file vp8dsp_init.c.
Referenced by ff_vp78dsp_init().
ff_vp8dsp_init()
void ff_vp8dsp_init (VP8DSPContext * c)
Referenced by check_idct(), check_idct_dc4(), check_loopfilter_16y(), check_loopfilter_8uv(), check_loopfilter_simple(), check_luma_dc_wht(), ff_vp78dsp_init(), and vp78_decode_init().
ff_vp8dsp_init_arm()
void ff_vp8dsp_init_arm (VP8DSPContext * c)
Definition at line 36 of file vp8dsp_init_arm.c.
Referenced by ff_vp78dsp_init().
ff_vp8dsp_init_x86()
void ff_vp8dsp_init_x86 (VP8DSPContext * c)
Definition at line 367 of file vp8dsp_init.c.
Referenced by ff_vp78dsp_init().
ff_vp8dsp_init_mips()
void ff_vp8dsp_init_mips (VP8DSPContext * c)
Definition at line 194 of file vp8dsp_init_mips.c.
Referenced by ff_vp78dsp_init().