FFmpeg: libavcodec/arm/vp8dsp_init_armv6.c File Reference
vp8dsp_init_armv6.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavcodec/vp8dsp.h"
#include "vp8dsp.h"
Functions
void ff_vp8_luma_dc_wht_armv6 (int16_t block[4][4][16], int16_t dc[16])
void ff_vp8_luma_dc_wht_dc_armv6 (int16_t block[4][4][16], int16_t dc[16])
void ff_vp8_idct_add_armv6 (uint8_t *dst, int16_t block[16], ptrdiff_t stride)
void ff_vp8_idct_dc_add_armv6 (uint8_t *dst, int16_t block[16], ptrdiff_t stride)
void ff_vp8_idct_dc_add4y_armv6 (uint8_t *dst, int16_t block[4][16], ptrdiff_t stride)
void ff_vp8_idct_dc_add4uv_armv6 (uint8_t *dst, int16_t block[4][16], ptrdiff_t stride)
VP8_LF (armv6)
VP8_EPEL (16, armv6)
VP8_EPEL (8, armv6)
VP8_EPEL (4, armv6)
VP8_BILIN (16, armv6)
VP8_BILIN (8, armv6)
VP8_BILIN (4, armv6)
av_cold void ff_vp78dsp_init_armv6 (VP8DSPContext *dsp)
av_cold void ff_vp8dsp_init_armv6 (VP8DSPContext *dsp)
Function Documentation
ff_vp8_luma_dc_wht_armv6()
void ff_vp8_luma_dc_wht_armv6 (int16_t block[4][4][16], int16_t dc[16])
Referenced by ff_vp8dsp_init_armv6().
ff_vp8_luma_dc_wht_dc_armv6()
void ff_vp8_luma_dc_wht_dc_armv6 (int16_t block[4][4][16], int16_t dc[16])
Referenced by ff_vp8dsp_init_armv6().
ff_vp8_idct_add_armv6()
void ff_vp8_idct_add_armv6 (uint8_t * dst, int16_t block[16], ptrdiff_t stride)
Referenced by ff_vp8dsp_init_armv6().
ff_vp8_idct_dc_add_armv6()
void ff_vp8_idct_dc_add_armv6 (uint8_t * dst, int16_t block[16], ptrdiff_t stride)
Referenced by ff_vp8dsp_init_armv6().
ff_vp8_idct_dc_add4y_armv6()
void ff_vp8_idct_dc_add4y_armv6 (uint8_t * dst, int16_t block[4][16], ptrdiff_t stride)
Referenced by ff_vp8dsp_init_armv6().
ff_vp8_idct_dc_add4uv_armv6()
void ff_vp8_idct_dc_add4uv_armv6 (uint8_t * dst, int16_t block[4][16], ptrdiff_t stride)
Referenced by ff_vp8dsp_init_armv6().
VP8_LF()
VP8_LF (armv6)
VP8_EPEL() [1/3]
VP8_EPEL (16 , armv6)
VP8_EPEL() [2/3]
VP8_EPEL (8 , armv6)
VP8_EPEL() [3/3]
VP8_EPEL (4 , armv6)
VP8_BILIN() [1/3]
VP8_BILIN (16 , armv6)
VP8_BILIN() [2/3]
VP8_BILIN (8 , armv6)
VP8_BILIN() [3/3]
VP8_BILIN (4 , armv6)
ff_vp78dsp_init_armv6()
av_cold void ff_vp78dsp_init_armv6 (VP8DSPContext * dsp)
Definition at line 43 of file vp8dsp_init_armv6.c.
Referenced by ff_vp78dsp_init_arm().
ff_vp8dsp_init_armv6()
av_cold void ff_vp8dsp_init_armv6 (VP8DSPContext * dsp)
Definition at line 101 of file vp8dsp_init_armv6.c.
Referenced by ff_vp8dsp_init_arm().