FFmpeg: libavcodec/mips/vp8dsp_mips.h File Reference
vp8dsp_mips.h File Reference
#include "libavutil/mem.h"
#include "libavcodec/vp8dsp.h"
#include "libavcodec/mathops.h"
#include "constants.h"
Functions
void ff_put_vp8_pixels4_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int x, int y)
void ff_put_vp8_pixels8_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int x, int y)
void ff_put_vp8_pixels16_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int x, int y)
void ff_put_vp8_epel16_h4_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel16_h6_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel16_v4_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel16_v6_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel16_h4v4_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel16_h6v4_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel16_h4v6_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel16_h6v6_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel8_h4_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel8_h6_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel8_v4_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel8_v6_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel8_h4v4_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel8_h6v4_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel8_h4v6_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel8_h6v6_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel4_h4_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel4_h6_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel4_v4_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel4_v6_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel4_h4v4_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel4_h6v4_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel4_h4v6_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel4_h6v6_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_bilinear16_h_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_bilinear16_v_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_bilinear16_hv_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_bilinear8_h_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_bilinear8_v_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_bilinear8_hv_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_bilinear4_h_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_bilinear4_v_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_bilinear4_hv_msa (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_vp8_h_loop_filter16_inner_msa (uint8_t *dst, ptrdiff_t stride, int32_t e, int32_t i, int32_t h)
void ff_vp8_v_loop_filter16_inner_msa (uint8_t *dst, ptrdiff_t stride, int32_t e, int32_t i, int32_t h)
void ff_vp8_h_loop_filter8uv_inner_msa (uint8_t *dst_u, uint8_t *dst_v, ptrdiff_t stride, int flim_e, int flim_i, int hev_thresh)
void ff_vp8_v_loop_filter8uv_inner_msa (uint8_t *dst_u, uint8_t *dst_v, ptrdiff_t stride, int flim_e, int flim_i, int hev_thresh)
void ff_vp8_h_loop_filter16_msa (uint8_t *dst, ptrdiff_t stride, int flim_e, int flim_i, int hev_thresh)
void ff_vp8_v_loop_filter16_msa (uint8_t *dst, ptrdiff_t stride, int flim_e, int flim_i, int hev_thresh)
void ff_vp8_h_loop_filter8uv_msa (uint8_t *dst_u, uint8_t *dst_v, ptrdiff_t stride, int flim_e, int flim_i, int hev_thresh)
void ff_vp8_v_loop_filter8uv_msa (uint8_t *dst_u, uint8_t *dst_v, ptrdiff_t stride, int flim_e, int flim_i, int hev_thresh)
void ff_vp8_h_loop_filter_simple_msa (uint8_t *dst, ptrdiff_t stride, int flim)
void ff_vp8_v_loop_filter_simple_msa (uint8_t *dst, ptrdiff_t stride, int flim)
void ff_vp8_luma_dc_wht_msa (int16_t block[4][4][16], int16_t dc[16])
void ff_vp8_idct_add_msa (uint8_t *dst, int16_t block[16], ptrdiff_t stride)
void ff_vp8_idct_dc_add_msa (uint8_t *dst, int16_t block[16], ptrdiff_t stride)
void ff_vp8_idct_dc_add4uv_msa (uint8_t *dst, int16_t block[4][16], ptrdiff_t stride)
void ff_vp8_idct_dc_add4y_msa (uint8_t *dst, int16_t block[4][16], ptrdiff_t stride)
void ff_vp8_luma_dc_wht_mmi (int16_t block[4][4][16], int16_t dc[16])
void ff_vp8_luma_dc_wht_dc_mmi (int16_t block[4][4][16], int16_t dc[16])
void ff_vp8_idct_add_mmi (uint8_t *dst, int16_t block[16], ptrdiff_t stride)
void ff_vp8_idct_dc_add_mmi (uint8_t *dst, int16_t block[16], ptrdiff_t stride)
void ff_vp8_idct_dc_add4y_mmi (uint8_t *dst, int16_t block[4][16], ptrdiff_t stride)
void ff_vp8_idct_dc_add4uv_mmi (uint8_t *dst, int16_t block[4][16], ptrdiff_t stride)
void ff_put_vp8_pixels4_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int x, int y)
void ff_put_vp8_pixels8_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int x, int y)
void ff_put_vp8_pixels16_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int x, int y)
void ff_put_vp8_epel16_h4_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel16_h6_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel16_v4_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel16_v6_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel16_h4v4_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel16_h6v4_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel16_h4v6_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel16_h6v6_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel8_h4_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel8_h6_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel8_v4_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel8_v6_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel8_h4v4_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel8_h6v4_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel8_h4v6_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel8_h6v6_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel4_h4_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel4_h6_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel4_v4_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel4_v6_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel4_h4v4_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel4_h6v4_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel4_h4v6_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_epel4_h6v6_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_bilinear16_h_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_bilinear16_v_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_bilinear16_hv_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_bilinear8_h_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_bilinear8_v_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_bilinear8_hv_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_bilinear4_h_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_bilinear4_v_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_put_vp8_bilinear4_hv_mmi (uint8_t *dst, ptrdiff_t dststride, uint8_t *src, ptrdiff_t srcstride, int h, int mx, int my)
void ff_vp8_v_loop_filter16_mmi (uint8_t *dst, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
void ff_vp8_h_loop_filter16_mmi (uint8_t *dst, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
void ff_vp8_v_loop_filter8uv_mmi (uint8_t *dstU, uint8_t *dstV, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
void ff_vp8_h_loop_filter8uv_mmi (uint8_t *dstU, uint8_t *dstV, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
void ff_vp8_v_loop_filter16_inner_mmi (uint8_t *dst, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
void ff_vp8_h_loop_filter16_inner_mmi (uint8_t *dst, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
void ff_vp8_v_loop_filter8uv_inner_mmi (uint8_t *dstU, uint8_t *dstV, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
void ff_vp8_h_loop_filter8uv_inner_mmi (uint8_t *dstU, uint8_t *dstV, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
void ff_vp8_v_loop_filter_simple_mmi (uint8_t *dst, ptrdiff_t stride, int flim)
void ff_vp8_h_loop_filter_simple_mmi (uint8_t *dst, ptrdiff_t stride, int flim)
Function Documentation
ff_put_vp8_pixels4_msa()
void ff_put_vp8_pixels4_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int x, int y)
ff_put_vp8_pixels8_msa()
void ff_put_vp8_pixels8_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int x, int y)
Definition at line 2244 of file vp8_mc_msa.c.
ff_put_vp8_pixels16_msa()
void ff_put_vp8_pixels16_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int x, int y)
Definition at line 2314 of file vp8_mc_msa.c.
ff_put_vp8_epel16_h4_msa()
void ff_put_vp8_epel16_h4_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 844 of file vp8_mc_msa.c.
ff_put_vp8_epel16_h6_msa()
void ff_put_vp8_epel16_h6_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 284 of file vp8_mc_msa.c.
ff_put_vp8_epel16_v4_msa()
void ff_put_vp8_epel16_v4_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 986 of file vp8_mc_msa.c.
ff_put_vp8_epel16_v6_msa()
void ff_put_vp8_epel16_v6_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 430 of file vp8_mc_msa.c.
ff_put_vp8_epel16_h4v4_msa()
void ff_put_vp8_epel16_h4v4_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1171 of file vp8_mc_msa.c.
ff_put_vp8_epel16_h6v4_msa()
void ff_put_vp8_epel16_h6v4_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1324 of file vp8_mc_msa.c.
ff_put_vp8_epel16_h4v6_msa()
void ff_put_vp8_epel16_h4v6_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1478 of file vp8_mc_msa.c.
ff_put_vp8_epel16_h6v6_msa()
void ff_put_vp8_epel16_h6v6_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 666 of file vp8_mc_msa.c.
ff_put_vp8_epel8_h4_msa()
void ff_put_vp8_epel8_h4_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 809 of file vp8_mc_msa.c.
ff_put_vp8_epel8_h6_msa()
void ff_put_vp8_epel8_h6_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 236 of file vp8_mc_msa.c.
ff_put_vp8_epel8_v4_msa()
void ff_put_vp8_epel8_v4_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 940 of file vp8_mc_msa.c.
ff_put_vp8_epel8_v6_msa()
void ff_put_vp8_epel8_v6_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 380 of file vp8_mc_msa.c.
ff_put_vp8_epel8_h4v4_msa()
void ff_put_vp8_epel8_h4v4_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1104 of file vp8_mc_msa.c.
Referenced by ff_put_vp8_epel16_h4v4_msa().
ff_put_vp8_epel8_h6v4_msa()
void ff_put_vp8_epel8_h6v4_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1251 of file vp8_mc_msa.c.
Referenced by ff_put_vp8_epel16_h6v4_msa().
ff_put_vp8_epel8_h4v6_msa()
void ff_put_vp8_epel8_h4v6_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1403 of file vp8_mc_msa.c.
Referenced by ff_put_vp8_epel16_h4v6_msa().
ff_put_vp8_epel8_h6v6_msa()
void ff_put_vp8_epel8_h6v6_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 579 of file vp8_mc_msa.c.
Referenced by ff_put_vp8_epel16_h6v6_msa().
ff_put_vp8_epel4_h4_msa()
void ff_put_vp8_epel4_h4_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 794 of file vp8_mc_msa.c.
ff_put_vp8_epel4_h6_msa()
void ff_put_vp8_epel4_h6_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 223 of file vp8_mc_msa.c.
ff_put_vp8_epel4_v4_msa()
void ff_put_vp8_epel4_v4_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 893 of file vp8_mc_msa.c.
ff_put_vp8_epel4_v6_msa()
void ff_put_vp8_epel4_v6_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 333 of file vp8_mc_msa.c.
ff_put_vp8_epel4_h4v4_msa()
void ff_put_vp8_epel4_h4v4_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1045 of file vp8_mc_msa.c.
ff_put_vp8_epel4_h6v4_msa()
void ff_put_vp8_epel4_h6v4_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1186 of file vp8_mc_msa.c.
ff_put_vp8_epel4_h4v6_msa()
void ff_put_vp8_epel4_h4v6_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1339 of file vp8_mc_msa.c.
ff_put_vp8_epel4_h6v6_msa()
void ff_put_vp8_epel4_h6v6_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 504 of file vp8_mc_msa.c.
ff_put_vp8_bilinear16_h_msa()
void ff_put_vp8_bilinear16_h_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1658 of file vp8_mc_msa.c.
ff_put_vp8_bilinear16_v_msa()
void ff_put_vp8_bilinear16_v_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1883 of file vp8_mc_msa.c.
ff_put_vp8_bilinear16_hv_msa()
void ff_put_vp8_bilinear16_hv_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2173 of file vp8_mc_msa.c.
ff_put_vp8_bilinear8_h_msa()
void ff_put_vp8_bilinear8_h_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1644 of file vp8_mc_msa.c.
ff_put_vp8_bilinear8_v_msa()
void ff_put_vp8_bilinear8_v_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1869 of file vp8_mc_msa.c.
ff_put_vp8_bilinear8_hv_msa()
void ff_put_vp8_bilinear8_hv_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2157 of file vp8_mc_msa.c.
ff_put_vp8_bilinear4_h_msa()
void ff_put_vp8_bilinear4_h_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1543 of file vp8_mc_msa.c.
ff_put_vp8_bilinear4_v_msa()
void ff_put_vp8_bilinear4_v_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1786 of file vp8_mc_msa.c.
ff_put_vp8_bilinear4_hv_msa()
void ff_put_vp8_bilinear4_hv_msa (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2016 of file vp8_mc_msa.c.
ff_vp8_h_loop_filter16_inner_msa()
void ff_vp8_h_loop_filter16_inner_msa (uint8_t * dst, ptrdiff_t stride, int32_t e, int32_t i, int32_t h)
Definition at line 657 of file vp8_lpf_msa.c.
ff_vp8_v_loop_filter16_inner_msa()
void ff_vp8_v_loop_filter16_inner_msa (uint8_t * dst, ptrdiff_t stride, int32_t e, int32_t i, int32_t h)
Definition at line 637 of file vp8_lpf_msa.c.
ff_vp8_h_loop_filter8uv_inner_msa()
void ff_vp8_h_loop_filter8uv_inner_msa (uint8_t * dst_u, uint8_t * dst_v, ptrdiff_t stride, int flim_e, int flim_i, int hev_thresh)
Definition at line 595 of file vp8_lpf_msa.c.
ff_vp8_v_loop_filter8uv_inner_msa()
void ff_vp8_v_loop_filter8uv_inner_msa (uint8_t * dst_u, uint8_t * dst_v, ptrdiff_t stride, int flim_e, int flim_i, int hev_thresh)
Definition at line 553 of file vp8_lpf_msa.c.
ff_vp8_h_loop_filter16_msa()
void ff_vp8_h_loop_filter16_msa (uint8_t * dst, ptrdiff_t stride, int flim_e, int flim_i, int hev_thresh)
Definition at line 374 of file vp8_lpf_msa.c.
ff_vp8_v_loop_filter16_msa()
void ff_vp8_v_loop_filter16_msa (uint8_t * dst, ptrdiff_t stride, int flim_e, int flim_i, int hev_thresh)
Definition at line 297 of file vp8_lpf_msa.c.
ff_vp8_h_loop_filter8uv_msa()
void ff_vp8_h_loop_filter8uv_msa (uint8_t * dst_u, uint8_t * dst_v, ptrdiff_t stride, int flim_e, int flim_i, int hev_thresh)
Definition at line 439 of file vp8_lpf_msa.c.
ff_vp8_v_loop_filter8uv_msa()
void ff_vp8_v_loop_filter8uv_msa (uint8_t * dst_u, uint8_t * dst_v, ptrdiff_t stride, int flim_e, int flim_i, int hev_thresh)
Definition at line 320 of file vp8_lpf_msa.c.
ff_vp8_h_loop_filter_simple_msa()
void ff_vp8_h_loop_filter_simple_msa (uint8_t * dst, ptrdiff_t stride, int flim)
Definition at line 519 of file vp8_lpf_msa.c.
ff_vp8_v_loop_filter_simple_msa()
void ff_vp8_v_loop_filter_simple_msa (uint8_t * dst, ptrdiff_t stride, int flim)
Definition at line 505 of file vp8_lpf_msa.c.
ff_vp8_luma_dc_wht_msa()
void ff_vp8_luma_dc_wht_msa (int16_t block[4][4][16], int16_t dc[16])
Definition at line 105 of file vp8_idct_msa.c.
ff_vp8_idct_add_msa()
void ff_vp8_idct_add_msa (uint8_t * dst, int16_t block[16], ptrdiff_t stride)
Definition at line 48 of file vp8_idct_msa.c.
ff_vp8_idct_dc_add_msa()
void ff_vp8_idct_dc_add_msa (uint8_t * dst, int16_t block[16], ptrdiff_t stride)
Definition at line 84 of file vp8_idct_msa.c.
Referenced by ff_vp8_idct_dc_add4uv_msa(), and ff_vp8_idct_dc_add4y_msa().
ff_vp8_idct_dc_add4uv_msa()
void ff_vp8_idct_dc_add4uv_msa (uint8_t * dst, int16_t block[4][16], ptrdiff_t stride)
Definition at line 153 of file vp8_idct_msa.c.
ff_vp8_idct_dc_add4y_msa()
void ff_vp8_idct_dc_add4y_msa (uint8_t * dst, int16_t block[4][16], ptrdiff_t stride)
Definition at line 144 of file vp8_idct_msa.c.
ff_vp8_luma_dc_wht_mmi()
void ff_vp8_luma_dc_wht_mmi (int16_t block[4][4][16], int16_t dc[16])
Definition at line 679 of file vp8dsp_mmi.c.
ff_vp8_luma_dc_wht_dc_mmi()
void ff_vp8_luma_dc_wht_dc_mmi (int16_t block[4][4][16], int16_t dc[16])
Definition at line 813 of file vp8dsp_mmi.c.
ff_vp8_idct_add_mmi()
void ff_vp8_idct_add_mmi (uint8_t * dst, int16_t block[16], ptrdiff_t stride)
Definition at line 837 of file vp8dsp_mmi.c.
ff_vp8_idct_dc_add_mmi()
void ff_vp8_idct_dc_add_mmi (uint8_t * dst, int16_t block[16], ptrdiff_t stride)
Definition at line 1006 of file vp8dsp_mmi.c.
Referenced by ff_vp8_idct_dc_add4uv_mmi(), and ff_vp8_idct_dc_add4y_mmi().
ff_vp8_idct_dc_add4y_mmi()
void ff_vp8_idct_dc_add4y_mmi (uint8_t * dst, int16_t block[4][16], ptrdiff_t stride)
Definition at line 1064 of file vp8dsp_mmi.c.
ff_vp8_idct_dc_add4uv_mmi()
void ff_vp8_idct_dc_add4uv_mmi (uint8_t * dst, int16_t block[4][16], ptrdiff_t stride)
Definition at line 1073 of file vp8dsp_mmi.c.
ff_put_vp8_pixels4_mmi()
void ff_put_vp8_pixels4_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int x, int y)
Definition at line 1275 of file vp8dsp_mmi.c.
ff_put_vp8_pixels8_mmi()
void ff_put_vp8_pixels8_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int x, int y)
Definition at line 1235 of file vp8dsp_mmi.c.
ff_put_vp8_pixels16_mmi()
void ff_put_vp8_pixels16_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int x, int y)
Definition at line 1188 of file vp8dsp_mmi.c.
ff_put_vp8_epel16_h4_mmi()
void ff_put_vp8_epel16_h4_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1315 of file vp8dsp_mmi.c.
Referenced by ff_put_vp8_epel16_h4v4_mmi(), and ff_put_vp8_epel16_h4v6_mmi().
ff_put_vp8_epel16_h6_mmi()
void ff_put_vp8_epel16_h6_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1508 of file vp8dsp_mmi.c.
Referenced by ff_put_vp8_epel16_h6v4_mmi(), and ff_put_vp8_epel16_h6v6_mmi().
ff_put_vp8_epel16_v4_mmi()
void ff_put_vp8_epel16_v4_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1704 of file vp8dsp_mmi.c.
Referenced by ff_put_vp8_epel16_h4v4_mmi(), and ff_put_vp8_epel16_h6v4_mmi().
ff_put_vp8_epel16_v6_mmi()
void ff_put_vp8_epel16_v6_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1902 of file vp8dsp_mmi.c.
Referenced by ff_put_vp8_epel16_h4v6_mmi(), and ff_put_vp8_epel16_h6v6_mmi().
ff_put_vp8_epel16_h4v4_mmi()
void ff_put_vp8_epel16_h4v4_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2103 of file vp8dsp_mmi.c.
ff_put_vp8_epel16_h6v4_mmi()
void ff_put_vp8_epel16_h6v4_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2336 of file vp8dsp_mmi.c.
ff_put_vp8_epel16_h4v6_mmi()
void ff_put_vp8_epel16_h4v6_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2219 of file vp8dsp_mmi.c.
ff_put_vp8_epel16_h6v6_mmi()
void ff_put_vp8_epel16_h6v6_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2453 of file vp8dsp_mmi.c.
ff_put_vp8_epel8_h4_mmi()
void ff_put_vp8_epel8_h4_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1392 of file vp8dsp_mmi.c.
Referenced by ff_put_vp8_epel8_h4v4_mmi(), and ff_put_vp8_epel8_h4v6_mmi().
ff_put_vp8_epel8_h6_mmi()
void ff_put_vp8_epel8_h6_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1586 of file vp8dsp_mmi.c.
Referenced by ff_put_vp8_epel8_h6v4_mmi(), and ff_put_vp8_epel8_h6v6_mmi().
ff_put_vp8_epel8_v4_mmi()
void ff_put_vp8_epel8_v4_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1782 of file vp8dsp_mmi.c.
Referenced by ff_put_vp8_epel8_h4v4_mmi(), and ff_put_vp8_epel8_h6v4_mmi().
ff_put_vp8_epel8_v6_mmi()
void ff_put_vp8_epel8_v6_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1981 of file vp8dsp_mmi.c.
Referenced by ff_put_vp8_epel8_h4v6_mmi(), and ff_put_vp8_epel8_h6v6_mmi().
ff_put_vp8_epel8_h4v4_mmi()
void ff_put_vp8_epel8_h4v4_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2142 of file vp8dsp_mmi.c.
ff_put_vp8_epel8_h6v4_mmi()
void ff_put_vp8_epel8_h6v4_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2375 of file vp8dsp_mmi.c.
ff_put_vp8_epel8_h4v6_mmi()
void ff_put_vp8_epel8_h4v6_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2258 of file vp8dsp_mmi.c.
ff_put_vp8_epel8_h6v6_mmi()
void ff_put_vp8_epel8_h6v6_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2492 of file vp8dsp_mmi.c.
ff_put_vp8_epel4_h4_mmi()
void ff_put_vp8_epel4_h4_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1453 of file vp8dsp_mmi.c.
Referenced by ff_put_vp8_epel4_h4v4_mmi(), and ff_put_vp8_epel4_h4v6_mmi().
ff_put_vp8_epel4_h6_mmi()
void ff_put_vp8_epel4_h6_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1648 of file vp8dsp_mmi.c.
Referenced by ff_put_vp8_epel4_h6v4_mmi(), and ff_put_vp8_epel4_h6v6_mmi().
ff_put_vp8_epel4_v4_mmi()
void ff_put_vp8_epel4_v4_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 1845 of file vp8dsp_mmi.c.
Referenced by ff_put_vp8_epel4_h4v4_mmi(), and ff_put_vp8_epel4_h6v4_mmi().
ff_put_vp8_epel4_v6_mmi()
void ff_put_vp8_epel4_v6_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2045 of file vp8dsp_mmi.c.
Referenced by ff_put_vp8_epel4_h4v6_mmi(), and ff_put_vp8_epel4_h6v6_mmi().
ff_put_vp8_epel4_h4v4_mmi()
void ff_put_vp8_epel4_h4v4_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2181 of file vp8dsp_mmi.c.
ff_put_vp8_epel4_h6v4_mmi()
void ff_put_vp8_epel4_h6v4_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2414 of file vp8dsp_mmi.c.
ff_put_vp8_epel4_h4v6_mmi()
void ff_put_vp8_epel4_h4v6_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2297 of file vp8dsp_mmi.c.
ff_put_vp8_epel4_h6v6_mmi()
void ff_put_vp8_epel4_h6v6_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2531 of file vp8dsp_mmi.c.
ff_put_vp8_bilinear16_h_mmi()
void ff_put_vp8_bilinear16_h_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2570 of file vp8dsp_mmi.c.
Referenced by ff_put_vp8_bilinear16_hv_mmi().
ff_put_vp8_bilinear16_v_mmi()
void ff_put_vp8_bilinear16_v_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2646 of file vp8dsp_mmi.c.
Referenced by ff_put_vp8_bilinear16_hv_mmi().
ff_put_vp8_bilinear16_hv_mmi()
void ff_put_vp8_bilinear16_hv_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2714 of file vp8dsp_mmi.c.
ff_put_vp8_bilinear8_h_mmi()
void ff_put_vp8_bilinear8_h_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2748 of file vp8dsp_mmi.c.
Referenced by ff_put_vp8_bilinear8_hv_mmi().
ff_put_vp8_bilinear8_v_mmi()
void ff_put_vp8_bilinear8_v_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2808 of file vp8dsp_mmi.c.
Referenced by ff_put_vp8_bilinear8_hv_mmi().
ff_put_vp8_bilinear8_hv_mmi()
void ff_put_vp8_bilinear8_hv_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2870 of file vp8dsp_mmi.c.
ff_put_vp8_bilinear4_h_mmi()
void ff_put_vp8_bilinear4_h_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2904 of file vp8dsp_mmi.c.
Referenced by ff_put_vp8_bilinear4_hv_mmi().
ff_put_vp8_bilinear4_v_mmi()
void ff_put_vp8_bilinear4_v_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 2961 of file vp8dsp_mmi.c.
Referenced by ff_put_vp8_bilinear4_hv_mmi().
ff_put_vp8_bilinear4_hv_mmi()
void ff_put_vp8_bilinear4_hv_mmi (uint8_t * dst, ptrdiff_t dststride, uint8_t * src, ptrdiff_t srcstride, int h, int mx, int my)
Definition at line 3020 of file vp8dsp_mmi.c.
ff_vp8_v_loop_filter16_mmi()
void ff_vp8_v_loop_filter16_mmi (uint8_t * dst, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
Definition at line 1083 of file vp8dsp_mmi.c.
ff_vp8_h_loop_filter16_mmi()
void ff_vp8_h_loop_filter16_mmi (uint8_t * dst, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
Definition at line 1097 of file vp8dsp_mmi.c.
ff_vp8_v_loop_filter8uv_mmi()
void ff_vp8_v_loop_filter8uv_mmi (uint8_t * dstU, uint8_t * dstV, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
Definition at line 1111 of file vp8dsp_mmi.c.
ff_vp8_h_loop_filter8uv_mmi()
void ff_vp8_h_loop_filter8uv_mmi (uint8_t * dstU, uint8_t * dstV, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
Definition at line 1118 of file vp8dsp_mmi.c.
ff_vp8_v_loop_filter16_inner_mmi()
void ff_vp8_v_loop_filter16_inner_mmi (uint8_t * dst, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
Definition at line 1126 of file vp8dsp_mmi.c.
ff_vp8_h_loop_filter16_inner_mmi()
void ff_vp8_h_loop_filter16_inner_mmi (uint8_t * dst, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
Definition at line 1141 of file vp8dsp_mmi.c.
ff_vp8_v_loop_filter8uv_inner_mmi()
void ff_vp8_v_loop_filter8uv_inner_mmi (uint8_t * dstU, uint8_t * dstV, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
Definition at line 1156 of file vp8dsp_mmi.c.
ff_vp8_h_loop_filter8uv_inner_mmi()
void ff_vp8_h_loop_filter8uv_inner_mmi (uint8_t * dstU, uint8_t * dstV, ptrdiff_t stride, int flim_E, int flim_I, int hev_thresh)
Definition at line 1163 of file vp8dsp_mmi.c.
ff_vp8_v_loop_filter_simple_mmi()
void ff_vp8_v_loop_filter_simple_mmi (uint8_t * dst, ptrdiff_t stride, int flim)
Definition at line 1170 of file vp8dsp_mmi.c.
ff_vp8_h_loop_filter_simple_mmi()
void ff_vp8_h_loop_filter_simple_mmi (uint8_t * dst, ptrdiff_t stride, int flim)
Definition at line 1179 of file vp8dsp_mmi.c.