FFmpeg: libavcodec/vp9_superframe_bsf.c File Reference
vp9_superframe_bsf.c File Reference
#include "libavutil/avassert.h"
#include "avcodec.h"
#include "bsf.h"
#include "get_bits.h"
Data Structures
struct VP9BSFContext
struct VP9BSFContext::CachedBuf
Macros
#define MAX_CACHE 8
#define wloop(mag, wr)
Functions
static void stats (const struct CachedBuf *in, int n_in, unsigned *_max, unsigned *_sum)
static int merge_superframe (const struct CachedBuf *in, int n_in, AVPacket *out)
static int vp9_superframe_filter (AVBSFContext *ctx, AVPacket *out)
static void vp9_superframe_close (AVBSFContext *ctx)
Variables
static enum AVCodecID codec_ids []
const AVBitStreamFilter ff_vp9_superframe_bsf
Macro Definition Documentation
MAX_CACHE
#define MAX_CACHE 8
Definition at line 27 of file vp9_superframe_bsf.c.
Referenced by vp9_superframe_filter().
wloop
#define wloop (mag, wr)
Value:
for (n = 0; n < n_in; n++) { \
        wr; \
        ptr += mag + 1; \
    }
Referenced by merge_superframe().
Function Documentation
stats()
static void stats (const struct CachedBuf * in, int n_in, unsigned * _max, unsigned * _sum) static
Definition at line 36 of file vp9_superframe_bsf.c.
Referenced by ff_rtp_check_and_send_back_rr(), filter_frame(), merge_superframe(), and queue_frames().
merge_superframe()
static int merge_superframe (const struct CachedBuf * in, int n_in, AVPacket * out) static
Definition at line 54 of file vp9_superframe_bsf.c.
Referenced by vp9_superframe_filter().
vp9_superframe_filter()
static int vp9_superframe_filter (AVBSFContext * ctx, AVPacket * out) static
Definition at line 101 of file vp9_superframe_bsf.c.
vp9_superframe_close()
static void vp9_superframe_close (AVBSFContext * ctx) static
Definition at line 185 of file vp9_superframe_bsf.c.
Variable Documentation
codec_ids
enum AVCodecID codec_ids[] static
Initial value:
= {
    AV_CODEC_ID_VP9, AV_CODEC_ID_NONE,
}
Definition at line 195 of file vp9_superframe_bsf.c.
ff_vp9_superframe_bsf
const AVBitStreamFilter ff_vp9_superframe_bsf
Initial value:
= {
    .name           = "vp9_superframe",
    .priv_data_size = sizeof(VP9BSFContext),
    .filter         = vp9_superframe_filter,
    .close          = vp9_superframe_close,
    .codec_ids      = codec_ids,
}
Definition at line 199 of file vp9_superframe_bsf.c.