FFmpeg: libavcodec/vp9.c File Reference
vp9.c File Reference
#include "avcodec.h"
#include "get_bits.h"
#include "internal.h"
#include "profiles.h"
#include "thread.h"
#include "videodsp.h"
#include "vp56.h"
#include "vp9.h"
#include "vp9data.h"
#include "vp9dsp.h"
#include "libavutil/avassert.h"
#include "libavutil/pixdesc.h"
#include "vp9_mc_template.c"
Data Structures
struct VP9Filter
struct VP9Block
struct VP9Context
Macros
#define VP9_SYNCCODE 0x498342
#define HWACCEL_MAX (CONFIG_VP9_DXVA2_HWACCEL + CONFIG_VP9_D3D11VA_HWACCEL + CONFIG_VP9_VAAPI_HWACCEL)
#define assign(var, type, n) var = (type) p; p += s->sb_cols * (n) * sizeof(*var)
#define INVALID_MV 0x80008000U
#define RETURN_DIRECT_MV(mv)
#define RETURN_MV(mv)
#define RETURN_SCALE_MV(mv, scale)
#define SPLAT_CTX(var, val, n)
#define SET_CTXS(dir, off, n)
#define STORE_COEF(c, i, v)
#define MERGE(la, end, step, rd)
#define MERGE_CTX(step, rd)
#define DECODE_Y_COEF_LOOP(step, mode_index, v)
#define SPLAT(la, end, step, cond)
#define SPLAT_CTX(step)
#define DECODE_UV_COEF_LOOP(step, v)
#define memset_bpp(c, i1, v, i2, num)
#define memset_val(c, val, num)
#define assign_bpp(c, i1, v, i2)
#define assign_val(c, i, v)
#define mc_luma_dir(s, mc, dst, dst_ls, src, src_ls, tref, row, col, mv, px, py, pw, ph, bw, bh, w, h, i)
#define mc_chroma_dir(s, mc, dstu, dstv, dst_ls, srcu, srcu_ls, srcv, srcv_ls, tref, row, col, mv, px, py, pw, ph, bw, bh, w, h, i)
#define SCALED 0
#define FN(x) x##_8bpp
#define BYTES_PER_PIXEL 1
#define FN(x) x##_16bpp
#define BYTES_PER_PIXEL 2
#define scale_mv(n, dim) (((int64_t)(n) * scale[dim]) >> 14)
#define mc_luma_dir(s, mc, dst, dst_ls, src, src_ls, tref, row, col, mv, px, py, pw, ph, bw, bh, w, h, i)
#define mc_chroma_dir(s, mc, dstu, dstv, dst_ls, srcu, srcu_ls, srcv, srcv_ls, tref, row, col, mv, px, py, pw, ph, bw, bh, w, h, i)
#define SCALED 1
#define FN(x) x##_scaled_8bpp
#define BYTES_PER_PIXEL 1
#define FN(x) x##_scaled_16bpp
#define BYTES_PER_PIXEL 2
#define SPLAT_ZERO_CTX(v, n)
#define SPLAT_ZERO_YUV(dir, var, off, n, dir2)
Functions
static void vp9_unref_frame (AVCodecContext *ctx, VP9Frame *f)
static int vp9_alloc_frame (AVCodecContext *ctx, VP9Frame *f)
static int vp9_ref_frame (AVCodecContext *ctx, VP9Frame *dst, VP9Frame *src)
static int update_size (AVCodecContext *ctx, int w, int h)
static int update_block_buffers (AVCodecContext *ctx)
static av_always_inline int get_sbits_inv (GetBitContext *gb, int n)
static av_always_inline int inv_recenter_nonneg (int v, int m)
static int update_prob (VP56RangeCoder *c, int p)
static int read_colorspace_details (AVCodecContext *ctx)
static int decode_frame_header (AVCodecContext *ctx, const uint8_t *data, int size, int *ref)
static av_always_inline void clamp_mv (VP56mv *dst, const VP56mv *src, VP9Context *s)
static void find_ref_mvs (VP9Context *s, VP56mv *pmv, int ref, int z, int idx, int sb)
static av_always_inline int read_mv_component (VP9Context *s, int idx, int hp)
static void fill_mv (VP9Context *s, VP56mv *mv, int mode, int sb)
static av_always_inline void setctx_2d (uint8_t *ptr, int w, int h, ptrdiff_t stride, int v)
static void decode_mode (AVCodecContext *ctx)
static av_always_inline int decode_coeffs_b_generic (VP56RangeCoder *c, int16_t *coef, int n_coeffs, int is_tx32x32, int is8bitsperpixel, int bpp, unsigned(*cnt)[6][3], unsigned(*eob)[6][2], uint8_t(*p)[6][11], int nnz, const int16_t *scan, const int16_t(*nb)[2], const int16_t *band_counts, const int16_t *qmul)
static int decode_coeffs_b_8bpp (VP9Context *s, int16_t *coef, int n_coeffs, unsigned(*cnt)[6][3], unsigned(*eob)[6][2], uint8_t(*p)[6][11], int nnz, const int16_t *scan, const int16_t(*nb)[2], const int16_t *band_counts, const int16_t *qmul)
static int decode_coeffs_b32_8bpp (VP9Context *s, int16_t *coef, int n_coeffs, unsigned(*cnt)[6][3], unsigned(*eob)[6][2], uint8_t(*p)[6][11], int nnz, const int16_t *scan, const int16_t(*nb)[2], const int16_t *band_counts, const int16_t *qmul)
static int decode_coeffs_b_16bpp (VP9Context *s, int16_t *coef, int n_coeffs, unsigned(*cnt)[6][3], unsigned(*eob)[6][2], uint8_t(*p)[6][11], int nnz, const int16_t *scan, const int16_t(*nb)[2], const int16_t *band_counts, const int16_t *qmul)
static int decode_coeffs_b32_16bpp (VP9Context *s, int16_t *coef, int n_coeffs, unsigned(*cnt)[6][3], unsigned(*eob)[6][2], uint8_t(*p)[6][11], int nnz, const int16_t *scan, const int16_t(*nb)[2], const int16_t *band_counts, const int16_t *qmul)
static av_always_inline int decode_coeffs (AVCodecContext *ctx, int is8bitsperpixel)
static int decode_coeffs_8bpp (AVCodecContext *ctx)
static int decode_coeffs_16bpp (AVCodecContext *ctx)
static av_always_inline int check_intra_mode (VP9Context *s, int mode, uint8_t **a, uint8_t *dst_edge, ptrdiff_t stride_edge, uint8_t *dst_inner, ptrdiff_t stride_inner, uint8_t *l, int col, int x, int w, int row, int y, enum TxfmMode tx, int p, int ss_h, int ss_v, int bytesperpixel)
static av_always_inline void intra_recon (AVCodecContext *ctx, ptrdiff_t y_off, ptrdiff_t uv_off, int bytesperpixel)
static void intra_recon_8bpp (AVCodecContext *ctx, ptrdiff_t y_off, ptrdiff_t uv_off)
static void intra_recon_16bpp (AVCodecContext *ctx, ptrdiff_t y_off, ptrdiff_t uv_off)
static av_always_inline void mc_luma_unscaled (VP9Context *s, vp9_mc_func(*mc)[2], uint8_t *dst, ptrdiff_t dst_stride, const uint8_t *ref, ptrdiff_t ref_stride, ThreadFrame *ref_frame, ptrdiff_t y, ptrdiff_t x, const VP56mv *mv, int bw, int bh, int w, int h, int bytesperpixel)
static av_always_inline void mc_chroma_unscaled (VP9Context *s, vp9_mc_func(*mc)[2], uint8_t *dst_u, uint8_t *dst_v, ptrdiff_t dst_stride, const uint8_t *ref_u, ptrdiff_t src_stride_u, const uint8_t *ref_v, ptrdiff_t src_stride_v, ThreadFrame *ref_frame, ptrdiff_t y, ptrdiff_t x, const VP56mv *mv, int bw, int bh, int w, int h, int bytesperpixel)
static av_always_inline void mc_luma_scaled (VP9Context *s, vp9_scaled_mc_func smc, vp9_mc_func(*mc)[2], uint8_t *dst, ptrdiff_t dst_stride, const uint8_t *ref, ptrdiff_t ref_stride, ThreadFrame *ref_frame, ptrdiff_t y, ptrdiff_t x, const VP56mv *in_mv, int px, int py, int pw, int ph, int bw, int bh, int w, int h, int bytesperpixel, const uint16_t *scale, const uint8_t *step)
static av_always_inline void mc_chroma_scaled (VP9Context *s, vp9_scaled_mc_func smc, vp9_mc_func(*mc)[2], uint8_t *dst_u, uint8_t *dst_v, ptrdiff_t dst_stride, const uint8_t *ref_u, ptrdiff_t src_stride_u, const uint8_t *ref_v, ptrdiff_t src_stride_v, ThreadFrame *ref_frame, ptrdiff_t y, ptrdiff_t x, const VP56mv *in_mv, int px, int py, int pw, int ph, int bw, int bh, int w, int h, int bytesperpixel, const uint16_t *scale, const uint8_t *step)
static av_always_inline void inter_recon (AVCodecContext *ctx, int bytesperpixel)
static void inter_recon_8bpp (AVCodecContext *ctx)
static void inter_recon_16bpp (AVCodecContext *ctx)
static av_always_inline void mask_edges (uint8_t(*mask)[8][4], int ss_h, int ss_v, int row_and_7, int col_and_7, int w, int h, int col_end, int row_end, enum TxfmMode tx, int skip_inter)
static void decode_b (AVCodecContext *ctx, int row, int col, struct VP9Filter *lflvl, ptrdiff_t yoff, ptrdiff_t uvoff, enum BlockLevel bl, enum BlockPartition bp)
static void decode_sb (AVCodecContext *ctx, int row, int col, struct VP9Filter *lflvl, ptrdiff_t yoff, ptrdiff_t uvoff, enum BlockLevel bl)
static void decode_sb_mem (AVCodecContext *ctx, int row, int col, struct VP9Filter *lflvl, ptrdiff_t yoff, ptrdiff_t uvoff, enum BlockLevel bl)
static av_always_inline void filter_plane_cols (VP9Context *s, int col, int ss_h, int ss_v, uint8_t *lvl, uint8_t(*mask)[4], uint8_t *dst, ptrdiff_t ls)
static av_always_inline void filter_plane_rows (VP9Context *s, int row, int ss_h, int ss_v, uint8_t *lvl, uint8_t(*mask)[4], uint8_t *dst, ptrdiff_t ls)
static void loopfilter_sb (AVCodecContext *ctx, struct VP9Filter *lflvl, int row, int col, ptrdiff_t yoff, ptrdiff_t uvoff)
static void set_tile_offset (int *start, int *end, int idx, int log2_n, int n)
static av_always_inline void adapt_prob (uint8_t *p, unsigned ct0, unsigned ct1, int max_count, int update_factor)
static void adapt_probs (VP9Context *s)
static void free_buffers (VP9Context *s)
static av_cold int vp9_decode_free (AVCodecContext *ctx)
static int vp9_decode_frame (AVCodecContext *ctx, void *frame, int *got_frame, AVPacket *pkt)
static void vp9_decode_flush (AVCodecContext *ctx)
static int init_frames (AVCodecContext *ctx)
static av_cold int vp9_decode_init (AVCodecContext *ctx)
Variables
static const uint8_t bwh_tab [2][N_BS_SIZES][2]
AVCodec ff_vp9_decoder
Macro Definition Documentation
VP9_SYNCCODE
#define VP9_SYNCCODE 0x498342
Definition at line 37 of file vp9.c.
Referenced by decode_frame_header().
HWACCEL_MAX
#define HWACCEL_MAX (CONFIG_VP9_DXVA2_HWACCEL + CONFIG_VP9_D3D11VA_HWACCEL + CONFIG_VP9_VAAPI_HWACCEL)
Referenced by update_size().
assign
#define assign (var, type, n) var = (type) p; p += s->sb_cols * (n) * sizeof(*var)
Referenced by update_size().
INVALID_MV
#define INVALID_MV 0x80008000U
Referenced by find_ref_mvs().
RETURN_DIRECT_MV
#define RETURN_DIRECT_MV (mv)
Value:
do { \
        uint32_t m = AV_RN32A(&mv); \
        if (!idx) { \
            AV_WN32A(pmv, m); \
            return; \
        } else if (mem == INVALID_MV) { \
            mem = m; \
        } else if (m != mem) { \
            AV_WN32A(pmv, m); \
            return; \
        } \
    } while (0)
Referenced by find_ref_mvs().
RETURN_MV
#define RETURN_MV (mv)
Referenced by find_ref_mvs().
RETURN_SCALE_MV
#define RETURN_SCALE_MV (mv, scale)
Value:
do { \
        if (scale) { \
            VP56mv mv_temp = { -mv.x, -mv.y }; \
            RETURN_MV(mv_temp); \
        } else { \
            RETURN_MV(mv); \
        } \
    } while (0)
Referenced by find_ref_mvs().
SPLAT_CTX [1/2]
#define SPLAT_CTX (var, val, n)
Value:
switch (n) { \
    case 1:  var = val;                         break; \
    case 2:  AV_WN16A(&var, val *     0x0101);  break; \
    case 4:  AV_WN32A(&var, val * 0x01010101);  break; \
    case 8: { \
        uint32_t v32 = val * 0x01010101; \
        AV_WN32A(              &var,     v32); \
        AV_WN32A(&((uint8_t *) &var)[4], v32); \
        break; \
    } \
    case 16: { \
        uint32_t v32 = val * 0x01010101; \
        AV_WN32A(              &var,      v32); \
        AV_WN32A(&((uint8_t *) &var)[4],  v32); \
        AV_WN32A(&((uint8_t *) &var)[8],  v32); \
        AV_WN32A(&((uint8_t *) &var)[12], v32); \
        break; \
    } \
    }
Referenced by decode_coeffs().
SET_CTXS
#define SET_CTXS (dir, off, n)
Value:
do { \
        SPLAT_CTX(s->dir##_skip_ctx[off],      b->skip,          n); \
        SPLAT_CTX(s->dir##_txfm_ctx[off],      b->tx,            n); \
        SPLAT_CTX(s->dir##_partition_ctx[off], dir##_ctx[b->bs], n); \
        if (!s->s.h.keyframe && !s->s.h.intraonly) { \
            SPLAT_CTX(s->dir##_intra_ctx[off], b->intra,   n); \
            SPLAT_CTX(s->dir##_comp_ctx[off],  b->comp,    n); \
            SPLAT_CTX(s->dir##_mode_ctx[off],  b->mode[3], n); \
            if (!b->intra) { \
                SPLAT_CTX(s->dir##_ref_ctx[off], vref, n); \
                if (s->s.h.filtermode == FILTER_SWITCHABLE) { \
                    SPLAT_CTX(s->dir##_filter_ctx[off], filter_id, n); \
                } \
            } \
        } \
    } while (0)
Referenced by decode_mode().
STORE_COEF
#define STORE_COEF (c, i, v)
Value:
do { \
    if (is8bitsperpixel) { \
        c[i] = v; \
    } else { \
        AV_WN32A(&c[i * 2], v); \
    } \
} while (0)
Referenced by decode_coeffs_b_generic().
MERGE
#define MERGE (la, end, step, rd)
Value:
for (n = 0; n < end; n += step) \
        la[n] = !!rd(&la[n])
MERGE_CTX
#define MERGE_CTX (step, rd)
Value:
do { \
        MERGE(l, end_y, step, rd); \
        MERGE(a, end_x, step, rd); \
    } while (0)
Referenced by decode_coeffs().
DECODE_Y_COEF_LOOP
#define DECODE_Y_COEF_LOOP (step, mode_index, v)
Value:
for (n = 0, y = 0; y < end_y; y += step) { \
        for (x = 0; x < end_x; x += step, n += step * step) { \
            enum TxfmType txtp = vp9_intra_txfm_type[b->mode[mode_index]]; \
            res = (is8bitsperpixel ? decode_coeffs_b##v##_8bpp : decode_coeffs_b##v##_16bpp) \
                                    (s, s->block + 16 * n * bytesperpixel, 16 * step * step, \
                                     c, e, p, a[x] + l[y], yscans[txtp], \
                                     ynbs[txtp], y_band_counts, qmul[0]); \
            a[x] = l[y] = !!res; \
            total_coeff |= !!res; \
            if (step >= 4) { \
                AV_WN16A(&s->eob[n], res); \
            } else { \
                s->eob[n] = res; \
            } \
        } \
    }
Referenced by decode_coeffs().
SPLAT
#define SPLAT (la, end, step, cond)
Value:
if (step == 2) { \
        for (n = 1; n < end; n += step) \
            la[n] = la[n - 1]; \
    } else if (step == 4) { \
        if (cond) { \
            for (n = 0; n < end; n += step) \
                AV_WN32A(&la[n], la[n] * 0x01010101); \
        } else { \
            for (n = 0; n < end; n += step) \
                memset(&la[n + 1], la[n], FFMIN(end - n - 1, 3)); \
        } \
    } else /* step == 8 */ { \
        if (cond) { \
            if (HAVE_FAST_64BIT) { \
                for (n = 0; n < end; n += step) \
                    AV_WN64A(&la[n], la[n] * 0x0101010101010101ULL); \
            } else { \
                for (n = 0; n < end; n += step) { \
                    uint32_t v32 = la[n] * 0x01010101; \
                    AV_WN32A(&la[n],     v32); \
                    AV_WN32A(&la[n + 4], v32); \
                } \
            } \
        } else { \
            for (n = 0; n < end; n += step) \
                memset(&la[n + 1], la[n], FFMIN(end - n - 1, 7)); \
        } \
    }
SPLAT_CTX [2/2]
#define SPLAT_CTX (step)
Value:
do { \
        SPLAT(a, end_x, step, end_x == w4); \
        SPLAT(l, end_y, step, end_y == h4); \
    } while (0)
DECODE_UV_COEF_LOOP
#define DECODE_UV_COEF_LOOP (step, v)
Value:
for (n = 0, y = 0; y < end_y; y += step) { \
        for (x = 0; x < end_x; x += step, n += step * step) { \
            res = (is8bitsperpixel ? decode_coeffs_b##v##_8bpp : decode_coeffs_b##v##_16bpp) \
                                    (s, s->uvblock[pl] + 16 * n * bytesperpixel, \
                                     16 * step * step, c, e, p, a[x] + l[y], \
                                     uvscan, uvnb, uv_band_counts, qmul[1]); \
            a[x] = l[y] = !!res; \
            total_coeff |= !!res; \
            if (step >= 4) { \
                AV_WN16A(&s->uveob[pl][n], res); \
            } else { \
                s->uveob[pl][n] = res; \
            } \
        } \
    }
Referenced by decode_coeffs().
memset_bpp
#define memset_bpp (c, i1, v, i2, num)
Value:
do { \
    if (bytesperpixel == 1) { \
        memset(&(c)[(i1)], (v)[(i2)], (num)); \
    } else { \
        int n, val = AV_RN16A(&(v)[(i2) * 2]); \
        for (n = 0; n < (num); n++) { \
            AV_WN16A(&(c)[((i1) + n) * 2], val); \
        } \
    } \
} while (0)
Referenced by check_intra_mode().
memset_val
#define memset_val (c, val, num)
Value:
do { \
    if (bytesperpixel == 1) { \
        memset((c), (val), (num)); \
    } else { \
        int n; \
        for (n = 0; n < (num); n++) { \
            AV_WN16A(&(c)[n * 2], (val)); \
        } \
    } \
} while (0)
Referenced by check_intra_mode().
assign_bpp
#define assign_bpp (c, i1, v, i2)
Value:
do { \
    if (bytesperpixel == 1) { \
        (c)[(i1)] = (v)[(i2)]; \
    } else { \
        AV_COPY16(&(c)[(i1) * 2], &(v)[(i2) * 2]); \
    } \
} while (0)
Referenced by check_intra_mode().
assign_val
#define assign_val (c, i, v)
Value:
do { \
    if (bytesperpixel == 1) { \
        (c)[(i)] = (v); \
    } else { \
        AV_WN16A(&(c)[(i) * 2], (v)); \
    } \
} while (0)
Referenced by check_intra_mode().
mc_luma_dir [1/2]
#define mc_luma_dir (s, mc, dst, dst_ls, src, src_ls, tref, row, col, mv, px, py, pw, ph, bw, bh, w, h, i)
Value:
mc_luma_unscaled(s, s->dsp.mc, dst, dst_ls, src, src_ls, tref, row, col, \
                     mv, bw, bh, w, h, bytesperpixel)
Definition at line 2983 of file vp9.c.
Referenced by inter_pred().
mc_chroma_dir [1/2]
#define mc_chroma_dir (s, mc, dstu, dstv, dst_ls, srcu, srcu_ls, srcv, srcv_ls, tref, row, col, mv, px, py, pw, ph, bw, bh, w, h, i)
Value:
mc_chroma_unscaled(s, s->dsp.mc, dstu, dstv, dst_ls, srcu, srcu_ls, srcv, srcv_ls, tref, \
                       row, col, mv, bw, bh, w, h, bytesperpixel)
Definition at line 2988 of file vp9.c.
Referenced by inter_pred().
SCALED [1/2]
#define SCALED 0
Definition at line 2993 of file vp9.c.
FN [1/4]
#define FN (x) x##_8bpp
Definition at line 2999 of file vp9.c.
BYTES_PER_PIXEL [1/4]
#define BYTES_PER_PIXEL 1
Definition at line 3000 of file vp9.c.
Referenced by inter_pred().
FN [2/4]
#define FN (x) x##_16bpp
Definition at line 2999 of file vp9.c.
BYTES_PER_PIXEL [2/4]
#define BYTES_PER_PIXEL 2
Definition at line 3000 of file vp9.c.
scale_mv
#define scale_mv (n, dim) (((int64_t)(n) * scale[dim]) >> 14)
Referenced by ff_vc1_pred_b_mv(), ff_vc1_pred_b_mv_intfi(), mc_chroma_scaled(), mc_luma_scaled(), and vc1_decode_b_mb_intfr().
mc_luma_dir [2/2]
#define mc_luma_dir (s, mc, dst, dst_ls, src, src_ls, tref, row, col, mv, px, py, pw, ph, bw, bh, w, h, i)
Value:
mc_luma_scaled(s, s->dsp.s##mc, s->dsp.mc, dst, dst_ls, src, src_ls, tref, row, col, \
                   mv, px, py, pw, ph, bw, bh, w, h, bytesperpixel, \
                   s->mvscale[b->ref[i]], s->mvstep[b->ref[i]])
Definition at line 2983 of file vp9.c.
mc_chroma_dir [2/2]
#define mc_chroma_dir (s, mc, dstu, dstv, dst_ls, srcu, srcu_ls, srcv, srcv_ls, tref, row, col, mv, px, py, pw, ph, bw, bh, w, h, i)
Value:
mc_chroma_scaled(s, s->dsp.s##mc, s->dsp.mc, dstu, dstv, dst_ls, srcu, srcu_ls, srcv, srcv_ls, tref, \
                     row, col, mv, px, py, pw, ph, bw, bh, w, h, bytesperpixel, \
                     s->mvscale[b->ref[i]], s->mvstep[b->ref[i]])
Definition at line 2988 of file vp9.c.
SCALED [2/2]
#define SCALED 1
Definition at line 2993 of file vp9.c.
FN [3/4]
#define FN (x) x##_scaled_8bpp
Definition at line 2999 of file vp9.c.
BYTES_PER_PIXEL [3/4]
#define BYTES_PER_PIXEL 1
Definition at line 3000 of file vp9.c.
FN [4/4]
#define FN (x) x##_scaled_16bpp
Definition at line 2999 of file vp9.c.
BYTES_PER_PIXEL [4/4]
#define BYTES_PER_PIXEL 2
Definition at line 3000 of file vp9.c.
SPLAT_ZERO_CTX
#define SPLAT_ZERO_CTX (v, n)
Value:
switch (n) { \
    case 1:  v = 0;          break; \
    case 2:  AV_ZERO16(&v);  break; \
    case 4:  AV_ZERO32(&v);  break; \
    case 8:  AV_ZERO64(&v);  break; \
    case 16: AV_ZERO128(&v); break; \
    }
SPLAT_ZERO_YUV
#define SPLAT_ZERO_YUV (dir, var, off, n, dir2)
Value:
do { \
        SPLAT_ZERO_CTX(s->dir##_y_##var[off * 2], n * 2); \
        if (s->ss_##dir2) { \
            SPLAT_ZERO_CTX(s->dir##_uv_##var[0][off], n); \
            SPLAT_ZERO_CTX(s->dir##_uv_##var[1][off], n); \
        } else { \
            SPLAT_ZERO_CTX(s->dir##_uv_##var[0][off * 2], n * 2); \
            SPLAT_ZERO_CTX(s->dir##_uv_##var[1][off * 2], n * 2); \
        } \
    } while (0)
Referenced by decode_b().
Function Documentation
vp9_unref_frame()
static void vp9_unref_frame (AVCodecContext * ctx, VP9Frame * f) static
Definition at line 177 of file vp9.c.
Referenced by vp9_alloc_frame(), vp9_decode_flush(), vp9_decode_frame(), vp9_decode_free(), vp9_decode_init(), and vp9_ref_frame().
vp9_alloc_frame()
static int vp9_alloc_frame (AVCodecContext * ctx, VP9Frame * f) static
Definition at line 186 of file vp9.c.
Referenced by vp9_decode_frame().
vp9_ref_frame()
static int vp9_ref_frame (AVCodecContext * ctx, VP9Frame * dst, VP9Frame * src) static
Definition at line 219 of file vp9.c.
Referenced by vp9_decode_frame(), and vp9_decode_init().
update_size()
static int update_size (AVCodecContext * ctx, int w, int h) static
Definition at line 247 of file vp9.c.
Referenced by decode_frame_header().
update_block_buffers()
static int update_block_buffers (AVCodecContext * ctx) static
Definition at line 346 of file vp9.c.
Referenced by vp9_decode_frame().
get_sbits_inv()
static av_always_inline int get_sbits_inv (GetBitContext * gb, int n) static
Definition at line 389 of file vp9.c.
Referenced by decode_frame_header().
inv_recenter_nonneg()
static av_always_inline int inv_recenter_nonneg (int v, int m) static
Definition at line 395 of file vp9.c.
Referenced by update_prob().
update_prob()
static int update_prob (VP56RangeCoder * c, int p) static
Definition at line 401 of file vp9.c.
Referenced by decode_frame_header().
read_colorspace_details()
static int read_colorspace_details (AVCodecContext * ctx) static
Definition at line 459 of file vp9.c.
Referenced by decode_frame_header().
decode_frame_header()
static int decode_frame_header (AVCodecContext * ctx, const uint8_t * data, int size, int * ref) static
Definition at line 521 of file vp9.c.
Referenced by vp9_decode_frame().
clamp_mv()
static av_always_inline void clamp_mv (VP56mv * dst, const VP56mv * src, VP9Context * s) static
Definition at line 1053 of file vp9.c.
Referenced by find_ref_mvs().
find_ref_mvs()
static void find_ref_mvs (VP9Context * s, VP56mv * pmv, int ref, int z, int idx, int sb) static
Definition at line 1060 of file vp9.c.
Referenced by fill_mv().
read_mv_component()
static av_always_inline int read_mv_component (VP9Context * s, int idx, int hp) static
Definition at line 1262 of file vp9.c.
Referenced by fill_mv().
fill_mv()
static void fill_mv (VP9Context * s, VP56mv * mv, int mode, int sb) static
Definition at line 1315 of file vp9.c.
Referenced by decode_mode().
setctx_2d()
static av_always_inline void setctx_2d (uint8_t * ptr, int w, int h, ptrdiff_t stride, int v) static
Definition at line 1388 of file vp9.c.
Referenced by decode_b(), and decode_mode().
decode_mode()
static void decode_mode (AVCodecContext * ctx) static
Definition at line 1434 of file vp9.c.
Referenced by decode_b().
decode_coeffs_b_generic()
static av_always_inline int decode_coeffs_b_generic (VP56RangeCoder * c, int16_t * coef, int n_coeffs, int is_tx32x32, int is8bitsperpixel, int bpp, unsigned(*) cnt[6][3], unsigned(*) eob[6][2], uint8_t(*) p[6][11], int nnz, const int16_t * scan, const int16_t(*) nb[2], const int16_t * band_counts, const int16_t * qmul) static
Definition at line 2140 of file vp9.c.
Referenced by decode_coeffs_b32_16bpp(), decode_coeffs_b32_8bpp(), decode_coeffs_b_16bpp(), and decode_coeffs_b_8bpp().
decode_coeffs_b_8bpp()
static int decode_coeffs_b_8bpp (VP9Context * s, int16_t * coef, int n_coeffs, unsigned(*) cnt[6][3], unsigned(*) eob[6][2], uint8_t(*) p[6][11], int nnz, const int16_t * scan, const int16_t(*) nb[2], const int16_t * band_counts, const int16_t * qmul) static
Definition at line 2263 of file vp9.c.
decode_coeffs_b32_8bpp()
static int decode_coeffs_b32_8bpp (VP9Context * s, int16_t * coef, int n_coeffs, unsigned(*) cnt[6][3], unsigned(*) eob[6][2], uint8_t(*) p[6][11], int nnz, const int16_t * scan, const int16_t(*) nb[2], const int16_t * band_counts, const int16_t * qmul) static
Definition at line 2273 of file vp9.c.
decode_coeffs_b_16bpp()
static int decode_coeffs_b_16bpp (VP9Context * s, int16_t * coef, int n_coeffs, unsigned(*) cnt[6][3], unsigned(*) eob[6][2], uint8_t(*) p[6][11], int nnz, const int16_t * scan, const int16_t(*) nb[2], const int16_t * band_counts, const int16_t * qmul) static
Definition at line 2283 of file vp9.c.
decode_coeffs_b32_16bpp()
static int decode_coeffs_b32_16bpp (VP9Context * s, int16_t * coef, int n_coeffs, unsigned(*) cnt[6][3], unsigned(*) eob[6][2], uint8_t(*) p[6][11], int nnz, const int16_t * scan, const int16_t(*) nb[2], const int16_t * band_counts, const int16_t * qmul) static
Definition at line 2293 of file vp9.c.
decode_coeffs()
static av_always_inline int decode_coeffs (AVCodecContext * ctx, int is8bitsperpixel) static
Definition at line 2303 of file vp9.c.
Referenced by decode_coeffs_16bpp(), and decode_coeffs_8bpp().
decode_coeffs_8bpp()
static int decode_coeffs_8bpp (AVCodecContext * ctx) static
Definition at line 2470 of file vp9.c.
Referenced by decode_b().
decode_coeffs_16bpp()
static int decode_coeffs_16bpp (AVCodecContext * ctx) static
Definition at line 2475 of file vp9.c.
Referenced by decode_b().
check_intra_mode()
static av_always_inline int check_intra_mode (VP9Context * s, int mode, uint8_t ** a, uint8_t * dst_edge, ptrdiff_t stride_edge, uint8_t * dst_inner, ptrdiff_t stride_inner, uint8_t * l, int col, int x, int w, int row, int y, enum TxfmMode tx, int p, int ss_h, int ss_v, int bytesperpixel) static
Definition at line 2480 of file vp9.c.
Referenced by intra_recon().
intra_recon()
static av_always_inline void intra_recon (AVCodecContext * ctx, ptrdiff_t y_off, ptrdiff_t uv_off, int bytesperpixel) static
Definition at line 2661 of file vp9.c.
Referenced by intra_recon_16bpp(), and intra_recon_8bpp().
intra_recon_8bpp()
static void intra_recon_8bpp (AVCodecContext * ctx, ptrdiff_t y_off, ptrdiff_t uv_off) static
Definition at line 2731 of file vp9.c.
Referenced by decode_b().
intra_recon_16bpp()
static void intra_recon_16bpp (AVCodecContext * ctx, ptrdiff_t y_off, ptrdiff_t uv_off) static
Definition at line 2736 of file vp9.c.
Referenced by decode_b().
mc_luma_unscaled()
static av_always_inline void mc_luma_unscaled (VP9Context * s, vp9_mc_func(*) mc[2], uint8_t * dst, ptrdiff_t dst_stride, const uint8_t * ref, ptrdiff_t ref_stride, ThreadFrame * ref_frame, ptrdiff_t y, ptrdiff_t x, const VP56mv * mv, int bw, int bh, int w, int h, int bytesperpixel) static
Definition at line 2741 of file vp9.c.
Referenced by mc_luma_scaled().
mc_chroma_unscaled()
static av_always_inline void mc_chroma_unscaled (VP9Context * s, vp9_mc_func(*) mc[2], uint8_t * dst_u, uint8_t * dst_v, ptrdiff_t dst_stride, const uint8_t * ref_u, ptrdiff_t src_stride_u, const uint8_t * ref_v, ptrdiff_t src_stride_v, ThreadFrame * ref_frame, ptrdiff_t y, ptrdiff_t x, const VP56mv * mv, int bw, int bh, int w, int h, int bytesperpixel) static
Definition at line 2776 of file vp9.c.
Referenced by mc_chroma_scaled().
mc_luma_scaled()
static av_always_inline void mc_luma_scaled (VP9Context * s, vp9_scaled_mc_func smc, vp9_mc_func(*) mc[2], uint8_t * dst, ptrdiff_t dst_stride, const uint8_t * ref, ptrdiff_t ref_stride, ThreadFrame * ref_frame, ptrdiff_t y, ptrdiff_t x, const VP56mv * in_mv, int px, int py, int pw, int ph, int bw, int bh, int w, int h, int bytesperpixel, const uint16_t * scale, const uint8_t * step) static
Definition at line 2847 of file vp9.c.
mc_chroma_scaled()
static av_always_inline void mc_chroma_scaled (VP9Context * s, vp9_scaled_mc_func smc, vp9_mc_func(*) mc[2], uint8_t * dst_u, uint8_t * dst_v, ptrdiff_t dst_stride, const uint8_t * ref_u, ptrdiff_t src_stride_u, const uint8_t * ref_v, ptrdiff_t src_stride_v, ThreadFrame * ref_frame, ptrdiff_t y, ptrdiff_t x, const VP56mv * in_mv, int px, int py, int pw, int ph, int bw, int bh, int w, int h, int bytesperpixel, const uint16_t * scale, const uint8_t * step) static
Definition at line 2904 of file vp9.c.
inter_recon()
static av_always_inline void inter_recon (AVCodecContext * ctx, int bytesperpixel) static
Definition at line 3008 of file vp9.c.
Referenced by inter_recon_16bpp(), and inter_recon_8bpp().
inter_recon_8bpp()
static void inter_recon_8bpp (AVCodecContext * ctx) static
Definition at line 3074 of file vp9.c.
Referenced by decode_b().
inter_recon_16bpp()
static void inter_recon_16bpp (AVCodecContext * ctx) static
Definition at line 3079 of file vp9.c.
Referenced by decode_b().
mask_edges()
static av_always_inline void mask_edges (uint8_t(*) mask[8][4], int ss_h, int ss_v, int row_and_7, int col_and_7, int w, int h, int col_end, int row_end, enum TxfmMode tx, int skip_inter) static
Definition at line 3084 of file vp9.c.
Referenced by decode_b().
decode_b()
static void decode_b (AVCodecContext * ctx, int row, int col, struct VP9Filter * lflvl, ptrdiff_t yoff, ptrdiff_t uvoff, enum BlockLevel bl, enum BlockPartition bp) static
Definition at line 3206 of file vp9.c.
Referenced by decode_sb(), and decode_sb_mem().
decode_sb()
static void decode_sb (AVCodecContext * ctx, int row, int col, struct VP9Filter * lflvl, ptrdiff_t yoff, ptrdiff_t uvoff, enum BlockLevel bl) static
Definition at line 3406 of file vp9.c.
Referenced by vp9_decode_frame().
decode_sb_mem()
static void decode_sb_mem (AVCodecContext * ctx, int row, int col, struct VP9Filter * lflvl, ptrdiff_t yoff, ptrdiff_t uvoff, enum BlockLevel bl) static
Definition at line 3485 of file vp9.c.
Referenced by vp9_decode_frame().
filter_plane_cols()
static av_always_inline void filter_plane_cols (VP9Context * s, int col, int ss_h, int ss_v, uint8_t * lvl, uint8_t(*) mask[4], uint8_t * dst, ptrdiff_t ls) static
Definition at line 3534 of file vp9.c.
Referenced by loopfilter_sb().
filter_plane_rows()
static av_always_inline void filter_plane_rows (VP9Context * s, int row, int ss_h, int ss_v, uint8_t * lvl, uint8_t(*) mask[4], uint8_t * dst, ptrdiff_t ls) static
Definition at line 3609 of file vp9.c.
Referenced by loopfilter_sb().
loopfilter_sb()
static void loopfilter_sb (AVCodecContext * ctx, struct VP9Filter * lflvl, int row, int col, ptrdiff_t yoff, ptrdiff_t uvoff) static
Definition at line 3686 of file vp9.c.
Referenced by vp9_decode_frame().
set_tile_offset()
static void set_tile_offset (int * start, int * end, int idx, int log2_n, int n) static
Definition at line 3712 of file vp9.c.
Referenced by vp9_decode_frame().
adapt_prob()
static av_always_inline void adapt_prob (uint8_t * p, unsigned ct0, unsigned ct1, int max_count, int update_factor) static
Definition at line 3720 of file vp9.c.
Referenced by adapt_probs().
adapt_probs()
static void adapt_probs (VP9Context * s) static
Definition at line 3737 of file vp9.c.
Referenced by vp9_decode_frame().
free_buffers()
static void free_buffers (VP9Context * s) static
Definition at line 3959 of file vp9.c.
Referenced by vp9_decode_free().
vp9_decode_free()
static av_cold int vp9_decode_free (AVCodecContext * ctx) static
Definition at line 3966 of file vp9.c.
Referenced by init_frames().
vp9_decode_frame()
static int vp9_decode_frame (AVCodecContext * ctx, void * frame, int * got_frame, AVPacket * pkt) static
Definition at line 3992 of file vp9.c.
vp9_decode_flush()
static void vp9_decode_flush (AVCodecContext * ctx) static
Definition at line 4276 of file vp9.c.
init_frames()
static int init_frames (AVCodecContext * ctx) static
Definition at line 4287 of file vp9.c.
Referenced by vp9_decode_init().
vp9_decode_init()
static av_cold int vp9_decode_init (AVCodecContext * ctx) static
Definition at line 4313 of file vp9.c.
Variable Documentation
bwh_tab
const uint8_t bwh_tab[2][N_BS_SIZES][2] static
Initial value:
= {
    {
        { 16, 16 }, { 16, 8 }, { 8, 16 }, { 8, 8 }, { 8, 4 }, { 4, 8 },
        { 4, 4 }, { 4, 2 }, { 2, 4 }, { 2, 2 }, { 2, 1 }, { 1, 2 }, { 1, 1 },
    }, {
        { 8, 8 }, { 8, 4 }, { 4, 8 }, { 4, 4 }, { 4, 2 }, { 2, 4 },
        { 2, 2 }, { 2, 1 }, { 1, 2 }, { 1, 1 }, { 1, 1 }, { 1, 1 }, { 1, 1 },
    }
}
Definition at line 167 of file vp9.c.
Referenced by decode_b(), decode_coeffs(), decode_mode(), inter_pred(), inter_recon(), and intra_recon().
ff_vp9_decoder
AVCodec ff_vp9_decoder
Initial value:
= {
    .name                  = "vp9",
    .long_name             = NULL_IF_CONFIG_SMALL("Google VP9"),
    .type                  = AVMEDIA_TYPE_VIDEO,
    .id                    = AV_CODEC_ID_VP9,
    .priv_data_size        = sizeof(VP9Context),
    .init                  = vp9_decode_init,
    .close                 = vp9_decode_free,
    .decode                = vp9_decode_frame,
    .capabilities          = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_FRAME_THREADS,
    .flush                 = vp9_decode_flush,
    .init_thread_copy      = ONLY_IF_THREADS_ENABLED(vp9_decode_init_thread_copy),
    .update_thread_context = ONLY_IF_THREADS_ENABLED(vp9_decode_update_thread_context),
    .profiles              = NULL_IF_CONFIG_SMALL(ff_vp9_profiles),
}
Definition at line 4376 of file vp9.c.