FFmpeg: libavcodec/vp9dsp.h File Reference
vp9dsp.h File Reference
#include <stddef.h>
#include <stdint.h>
#include "vp9.h"
Data Structures
struct VP9DSPContext
Typedefs
typedef void(* vp9_mc_func) (uint8_t *dst, ptrdiff_t dst_stride, const uint8_t *ref, ptrdiff_t ref_stride, int h, int mx, int my)
typedef void(* vp9_scaled_mc_func) (uint8_t *dst, ptrdiff_t dst_stride, const uint8_t *ref, ptrdiff_t ref_stride, int h, int mx, int my, int dx, int dy)
Functions
void ff_vp9dsp_init (VP9DSPContext *dsp, int bpp, int bitexact)
void ff_vp9dsp_init_8 (VP9DSPContext *dsp)
void ff_vp9dsp_init_10 (VP9DSPContext *dsp)
void ff_vp9dsp_init_12 (VP9DSPContext *dsp)
void ff_vp9dsp_init_aarch64 (VP9DSPContext *dsp, int bpp)
void ff_vp9dsp_init_arm (VP9DSPContext *dsp, int bpp)
void ff_vp9dsp_init_x86 (VP9DSPContext *dsp, int bpp, int bitexact)
void ff_vp9dsp_init_mips (VP9DSPContext *dsp, int bpp)
Variables
const int16_t ff_vp9_subpel_filters [3][16][8]
Typedef Documentation
vp9_mc_func
typedef void(* vp9_mc_func) (uint8_t *dst, ptrdiff_t dst_stride, const uint8_t *ref, ptrdiff_t ref_stride, int h, int mx, int my)
Definition at line 32 of file vp9dsp.h.
vp9_scaled_mc_func
typedef void(* vp9_scaled_mc_func) (uint8_t *dst, ptrdiff_t dst_stride, const uint8_t *ref, ptrdiff_t ref_stride, int h, int mx, int my, int dx, int dy)
Definition at line 35 of file vp9dsp.h.
Function Documentation
ff_vp9dsp_init()
void ff_vp9dsp_init (VP9DSPContext * dsp, int bpp, int bitexact)
Definition at line 84 of file vp9dsp.c.
Referenced by check_ipred(), check_itxfm(), check_loopfilter(), check_mc(), and update_size().
ff_vp9dsp_init_8()
void ff_vp9dsp_init_8 (VP9DSPContext * dsp)
Referenced by ff_vp9dsp_init().
ff_vp9dsp_init_10()
void ff_vp9dsp_init_10 (VP9DSPContext * dsp)
Referenced by ff_vp9dsp_init().
ff_vp9dsp_init_12()
void ff_vp9dsp_init_12 (VP9DSPContext * dsp)
Referenced by ff_vp9dsp_init().
ff_vp9dsp_init_aarch64()
void ff_vp9dsp_init_aarch64 (VP9DSPContext * dsp, int bpp)
Definition at line 251 of file vp9dsp_init_aarch64.c.
Referenced by ff_vp9dsp_init().
ff_vp9dsp_init_arm()
void ff_vp9dsp_init_arm (VP9DSPContext * dsp, int bpp)
Definition at line 250 of file vp9dsp_init_arm.c.
Referenced by ff_vp9dsp_init().
ff_vp9dsp_init_x86()
void ff_vp9dsp_init_x86 (VP9DSPContext * dsp, int bpp, int bitexact)
Definition at line 217 of file vp9dsp_init.c.
Referenced by ff_vp9dsp_init().
ff_vp9dsp_init_mips()
void ff_vp9dsp_init_mips (VP9DSPContext * dsp, int bpp)
Definition at line 171 of file vp9dsp_init_mips.c.
Referenced by ff_vp9dsp_init().
Variable Documentation
ff_vp9_subpel_filters
const int16_t ff_vp9_subpel_filters[3][16][8]
Definition at line 28 of file vp9dsp.c.