FFmpeg: libavcodec/aarch64/vp9dsp_init_aarch64.c File Reference
vp9dsp_init_aarch64.c File Reference
#include <stdint.h>
#include "libavutil/attributes.h"
#include "libavutil/aarch64/cpu.h"
#include "libavcodec/vp9dsp.h"
Macros
#define declare_fpel(type, sz)
#define declare_copy_avg(sz)
#define decl_mc_func(op, filter, dir, sz)
#define define_8tap_2d_fn(op, filter, sz)
#define decl_filter_funcs(op, dir, sz)
#define decl_mc_funcs(sz)
#define ff_vp9_copy32_neon ff_vp9_copy32_aarch64
#define ff_vp9_copy64_neon ff_vp9_copy64_aarch64
#define define_8tap_2d_funcs(sz)
#define init_fpel(idx1, idx2, sz, type, suffix)
#define init_copy(idx, sz, suffix) init_fpel(idx, 0, sz, copy, suffix)
#define init_avg(idx, sz, suffix) init_fpel(idx, 1, sz, avg, suffix)
#define init_copy_avg(idx, sz)
#define init_mc_func(idx1, idx2, op, filter, fname, dir, mx, my, sz, pfx) dsp->mc[idx1][filter][idx2][mx][my] = pfx##op##_##fname##sz##_##dir##_neon
#define init_mc_funcs(idx, dir, mx, my, sz, pfx)
#define init_mc_funcs_dirs(idx, sz)
#define define_itxfm(type_a, type_b, sz)
#define define_itxfm_funcs(sz)
#define init_itxfm(tx, sz)
#define init_idct(tx, nm)
#define define_loop_filter(dir, wd, len) void ff_vp9_loop_filter_##dir##_##wd##_##len##_neon(uint8_t *dst, ptrdiff_t stride, int E, int I, int H)
#define define_loop_filters(wd, len)
Functions
declare_copy_avg (64)
declare_copy_avg (32)
declare_copy_avg (16)
declare_copy_avg (8)
declare_copy_avg (4)
decl_mc_funcs (64)
decl_mc_funcs (32)
decl_mc_funcs (16)
decl_mc_funcs (8)
decl_mc_funcs (4)
define_8tap_2d_funcs (64)
define_itxfm_funcs (4)
define_itxfm_funcs (8)
define_itxfm_funcs (16)
define_itxfm (idct, idct, 32)
define_itxfm (iwht, iwht, 4)
static av_cold void vp9dsp_itxfm_init_aarch64 (VP9DSPContext *dsp, int bpp)
define_loop_filters (4, 8)
define_loop_filters (8, 8)
define_loop_filters (16, 8)
define_loop_filters (16, 16)
define_loop_filters (44, 16)
define_loop_filters (48, 16)
define_loop_filters (84, 16)
define_loop_filters (88, 16)
static av_cold void vp9dsp_loopfilter_init_aarch64 (VP9DSPContext *dsp, int bpp)
av_cold void ff_vp9dsp_init_aarch64 (VP9DSPContext *dsp, int bpp)
Macro Definition Documentation
declare_fpel
#define declare_fpel (type, sz)
Value:
void ff_vp9_##type##sz##_neon(uint8_t *dst, ptrdiff_t dst_stride,       \
                              const uint8_t *src, ptrdiff_t src_stride, \
                              int h, int mx, int my)
Definition at line 27 of file vp9dsp_init_aarch64.c.
declare_copy_avg
#define declare_copy_avg (sz)
Value:
declare_fpel(copy, sz);  \
    declare_fpel(avg , sz)
Definition at line 32 of file vp9dsp_init_aarch64.c.
decl_mc_func
#define decl_mc_func (op, filter, dir, sz)
Value:
void ff_vp9_##op##_##filter##sz##_##dir##_neon(uint8_t *dst, ptrdiff_t dst_stride,       \
                                               const uint8_t *src, ptrdiff_t src_stride, \
                                               int h, int mx, int my)
Definition at line 36 of file vp9dsp_init_aarch64.c.
define_8tap_2d_fn
#define define_8tap_2d_fn (op, filter, sz)
Value:
static void op##_##filter##sz##_hv_neon(uint8_t *dst, ptrdiff_t dst_stride,       \
                                        const uint8_t *src, ptrdiff_t src_stride, \
                                        int h, int mx, int my)                    \
{                                                                                 \
    LOCAL_ALIGNED_16(uint8_t, temp, [((1 + (sz < 64)) * sz + 8) * sz]);           \
    /* We only need h + 7 lines, but the horizontal filter assumes an             \
     * even number of rows, so filter h + 8 lines here. */                        \
    ff_vp9_put_##filter##sz##_h_neon(temp, sz,                                    \
                                     src - 3 * src_stride, src_stride,            \
                                     h + 8, mx, 0);                               \
    ff_vp9_##op##_##filter##sz##_v_neon(dst, dst_stride,                          \
                                        temp + 3 * sz, sz,                        \
                                        h, 0, my);                                \
}
Definition at line 41 of file vp9dsp_init_aarch64.c.
decl_filter_funcs
#define decl_filter_funcs (op, dir, sz)
Value:
decl_mc_func(op, regular, dir, sz); \
    decl_mc_func(op, sharp,   dir, sz); \
    decl_mc_func(op, smooth,  dir, sz)
Definition at line 57 of file vp9dsp_init_aarch64.c.
decl_mc_funcs
#define decl_mc_funcs (sz)
Value:
decl_filter_funcs(put, h,  sz); \
    decl_filter_funcs(avg, h,  sz); \
    decl_filter_funcs(put, v,  sz); \
    decl_filter_funcs(avg, v,  sz); \
    decl_filter_funcs(put, hv, sz); \
    decl_filter_funcs(avg, hv, sz)
Definition at line 62 of file vp9dsp_init_aarch64.c.
ff_vp9_copy32_neon
#define ff_vp9_copy32_neon ff_vp9_copy32_aarch64
Definition at line 70 of file vp9dsp_init_aarch64.c.
ff_vp9_copy64_neon
#define ff_vp9_copy64_neon ff_vp9_copy64_aarch64
Definition at line 71 of file vp9dsp_init_aarch64.c.
define_8tap_2d_funcs
#define define_8tap_2d_funcs (sz)
Value:
define_8tap_2d_fn(put, regular, sz) \
    define_8tap_2d_fn(put, sharp,   sz) \
    define_8tap_2d_fn(put, smooth,  sz) \
    define_8tap_2d_fn(avg, regular, sz) \
    define_8tap_2d_fn(avg, sharp,   sz) \
    define_8tap_2d_fn(avg, smooth,  sz)
Definition at line 85 of file vp9dsp_init_aarch64.c.
init_fpel
#define init_fpel (idx1, idx2, sz, type, suffix)
Value:
dsp->mc[idx1][FILTER_8TAP_SMOOTH ][idx2][0][0] = \
    dsp->mc[idx1][FILTER_8TAP_REGULAR][idx2][0][0] = \
    dsp->mc[idx1][FILTER_8TAP_SHARP  ][idx2][0][0] = \
    dsp->mc[idx1][FILTER_BILINEAR    ][idx2][0][0] = ff_vp9_##type##sz##suffix
init_copy
#define init_copy (idx, sz, suffix) init_fpel(idx, 0, sz, copy, suffix)
Referenced by define_8tap_2d_funcs().
init_avg
#define init_avg (idx, sz, suffix) init_fpel(idx, 1, sz, avg, suffix)
Referenced by define_8tap_2d_funcs().
init_copy_avg
#define init_copy_avg (idx, sz)
Value:
init_copy(idx, sz, _neon); \
    init_avg (idx, sz, _neon)
Referenced by define_8tap_2d_funcs().
init_mc_func
#define init_mc_func (idx1, idx2, op, filter, fname, dir, mx, my, sz, pfx) dsp->mc[idx1][filter][idx2][mx][my] = pfx##op##_##fname##sz##_##dir##_neon
init_mc_funcs
#define init_mc_funcs (idx, dir, mx, my, sz, pfx)
Value:
init_mc_func(idx, 0, put, FILTER_8TAP_REGULAR, regular, dir, mx, my, sz, pfx); \
    init_mc_func(idx, 0, put, FILTER_8TAP_SHARP,   sharp,   dir, mx, my, sz, pfx); \
    init_mc_func(idx, 0, put, FILTER_8TAP_SMOOTH,  smooth,  dir, mx, my, sz, pfx); \
    init_mc_func(idx, 1, avg, FILTER_8TAP_REGULAR, regular, dir, mx, my, sz, pfx); \
    init_mc_func(idx, 1, avg, FILTER_8TAP_SHARP,   sharp,   dir, mx, my, sz, pfx); \
    init_mc_func(idx, 1, avg, FILTER_8TAP_SMOOTH,  smooth,  dir, mx, my, sz, pfx)
init_mc_funcs_dirs
#define init_mc_funcs_dirs (idx, sz)
Value:
init_mc_funcs(idx, h,  1, 0, sz, ff_vp9_); \
    init_mc_funcs(idx, v,  0, 1, sz, ff_vp9_); \
    init_mc_funcs(idx, hv, 1, 1, sz,)
Referenced by define_8tap_2d_funcs().
define_itxfm
#define define_itxfm (type_a, type_b, sz)
Value:
void ff_vp9_##type_a##_##type_b##_##sz##x##sz##_add_neon(uint8_t *_dst,    \
                                                         ptrdiff_t stride, \
                                                         int16_t *_block, int eob)
Definition at line 158 of file vp9dsp_init_aarch64.c.
define_itxfm_funcs
#define define_itxfm_funcs (sz)
Value:
define_itxfm(idct,  idct,  sz); \
    define_itxfm(iadst, idct,  sz); \
    define_itxfm(idct,  iadst, sz); \
    define_itxfm(iadst, iadst, sz)
Definition at line 163 of file vp9dsp_init_aarch64.c.
init_itxfm
#define init_itxfm (tx, sz)
Value:
dsp->itxfm_add[tx][DCT_DCT]   = ff_vp9_idct_idct_##sz##_add_neon;  \
    dsp->itxfm_add[tx][DCT_ADST]  = ff_vp9_iadst_idct_##sz##_add_neon; \
    dsp->itxfm_add[tx][ADST_DCT]  = ff_vp9_idct_iadst_##sz##_add_neon; \
    dsp->itxfm_add[tx][ADST_ADST] = ff_vp9_iadst_iadst_##sz##_add_neon
Referenced by vp9dsp_itxfm_init_aarch64().
init_idct
#define init_idct (tx, nm)
Value:
dsp->itxfm_add[tx][DCT_DCT]   = \
    dsp->itxfm_add[tx][ADST_DCT]  = \
    dsp->itxfm_add[tx][DCT_ADST]  = \
    dsp->itxfm_add[tx][ADST_ADST] = ff_vp9_##nm##_add_neon
Referenced by vp9dsp_itxfm_init_aarch64().
define_loop_filter
#define define_loop_filter (dir, wd, len) void ff_vp9_loop_filter_##dir##_##wd##_##len##_neon(uint8_t *dst, ptrdiff_t stride, int E, int I, int H)
Definition at line 204 of file vp9dsp_init_aarch64.c.
define_loop_filters
#define define_loop_filters (wd, len)
Value:
define_loop_filter(h, wd, len);  \
    define_loop_filter(v, wd, len)
Definition at line 207 of file vp9dsp_init_aarch64.c.
Function Documentation
declare_copy_avg() [1/5]
declare_copy_avg (64)
declare_copy_avg() [2/5]
declare_copy_avg (32)
declare_copy_avg() [3/5]
declare_copy_avg (16)
declare_copy_avg() [4/5]
declare_copy_avg (8)
declare_copy_avg() [5/5]
declare_copy_avg (4)
decl_mc_funcs() [1/5]
decl_mc_funcs (64)
decl_mc_funcs() [2/5]
decl_mc_funcs (32)
decl_mc_funcs() [3/5]
decl_mc_funcs (16)
decl_mc_funcs() [4/5]
decl_mc_funcs (8)
decl_mc_funcs() [5/5]
decl_mc_funcs (4)
define_8tap_2d_funcs()
define_8tap_2d_funcs (64)
Definition at line 93 of file vp9dsp_init_aarch64.c.
define_itxfm_funcs() [1/3]
define_itxfm_funcs (4)
define_itxfm_funcs() [2/3]
define_itxfm_funcs (8)
define_itxfm_funcs() [3/3]
define_itxfm_funcs (16)
define_itxfm() [1/2]
define_itxfm (idct , idct , 32)
define_itxfm() [2/2]
define_itxfm (iwht , iwht , 4)
vp9dsp_itxfm_init_aarch64()
static av_cold void vp9dsp_itxfm_init_aarch64 (VP9DSPContext * dsp, int bpp) static
Definition at line 176 of file vp9dsp_init_aarch64.c.
Referenced by ff_vp9dsp_init_aarch64().
define_loop_filters() [1/8]
define_loop_filters (4 , 8)
define_loop_filters() [2/8]
define_loop_filters (8 , 8)
define_loop_filters() [3/8]
define_loop_filters (16 , 8)
define_loop_filters() [4/8]
define_loop_filters (16 , 16)
define_loop_filters() [5/8]
define_loop_filters (44 , 16)
define_loop_filters() [6/8]
define_loop_filters (48 , 16)
define_loop_filters() [7/8]
define_loop_filters (84 , 16)
define_loop_filters() [8/8]
define_loop_filters (88 , 16)
vp9dsp_loopfilter_init_aarch64()
static av_cold void vp9dsp_loopfilter_init_aarch64 (VP9DSPContext * dsp, int bpp) static
Definition at line 222 of file vp9dsp_init_aarch64.c.
Referenced by ff_vp9dsp_init_aarch64().
ff_vp9dsp_init_aarch64()
av_cold void ff_vp9dsp_init_aarch64 (VP9DSPContext * dsp, int bpp)
Definition at line 251 of file vp9dsp_init_aarch64.c.
Referenced by ff_vp9dsp_init().