FFmpeg: libavformat/vpcc.c File Reference
vpcc.c File Reference
#include "libavutil/pixdesc.h"
#include "libavutil/pixfmt.h"
#include "vpcc.h"
Enumerations
enum VpxColorSpace {
VPX_COLOR_SPACE_UNSPECIFIED = 0, VPX_COLOR_SPACE_BT601 = 1, VPX_COLOR_SPACE_BT709 = 2, VPX_COLOR_SPACE_SMPTE_170 = 3,
VPX_COLOR_SPACE_SMPTE_240 = 4, VPX_COLOR_SPACE_BT2020_NCL = 5, VPX_COLOR_SPACE_BT2020_CL = 6, VPX_COLOR_SPACE_RGB = 7
}
enum VPX_CHROMA_SUBSAMPLING { VPX_SUBSAMPLING_420_VERTICAL = 0, VPX_SUBSAMPLING_420_COLLOCATED_WITH_LUMA = 1, VPX_SUBSAMPLING_422 = 2, VPX_SUBSAMPLING_444 = 3 }
Functions
static int get_vpx_color_space (AVFormatContext *s, enum AVColorSpace color_space)
static int get_vpx_chroma_subsampling (AVFormatContext *s, enum AVPixelFormat pixel_format, enum AVChromaLocation chroma_location)
static int get_bit_depth (AVFormatContext *s, enum AVPixelFormat pixel_format)
static int get_vpx_transfer_function (enum AVColorTransferCharacteristic transfer)
static int get_vpx_video_full_range_flag (enum AVColorRange color_range)
int ff_isom_write_vpcc (AVFormatContext *s, AVIOContext *pb, AVCodecParameters *par)
Writes VP codec configuration to the provided AVIOContext.
Enumeration Type Documentation
VpxColorSpace
enum VpxColorSpace
Enumerator
VPX_COLOR_SPACE_UNSPECIFIED
VPX_COLOR_SPACE_BT601
VPX_COLOR_SPACE_BT709
VPX_COLOR_SPACE_SMPTE_170
VPX_COLOR_SPACE_SMPTE_240
VPX_COLOR_SPACE_BT2020_NCL
VPX_COLOR_SPACE_BT2020_CL
VPX_COLOR_SPACE_RGB
Definition at line 26 of file vpcc.c.
VPX_CHROMA_SUBSAMPLING
enum VPX_CHROMA_SUBSAMPLING
Enumerator
VPX_SUBSAMPLING_420_VERTICAL
VPX_SUBSAMPLING_420_COLLOCATED_WITH_LUMA
VPX_SUBSAMPLING_422
VPX_SUBSAMPLING_444
Definition at line 64 of file vpcc.c.
Function Documentation
get_vpx_color_space()
static int get_vpx_color_space (AVFormatContext * s, enum AVColorSpace color_space) static
Definition at line 38 of file vpcc.c.
Referenced by ff_isom_write_vpcc().
get_vpx_chroma_subsampling()
static int get_vpx_chroma_subsampling (AVFormatContext * s, enum AVPixelFormat pixel_format, enum AVChromaLocation chroma_location) static
Definition at line 72 of file vpcc.c.
Referenced by ff_isom_write_vpcc().
get_bit_depth()
static int get_bit_depth (AVFormatContext * s, enum AVPixelFormat pixel_format) static
Definition at line 92 of file vpcc.c.
Referenced by ff_isom_write_vpcc().
get_vpx_transfer_function()
static int get_vpx_transfer_function (enum AVColorTransferCharacteristic transfer) static
Definition at line 103 of file vpcc.c.
Referenced by ff_isom_write_vpcc().
get_vpx_video_full_range_flag()
static int get_vpx_video_full_range_flag (enum AVColorRange color_range) static
Definition at line 109 of file vpcc.c.
Referenced by ff_isom_write_vpcc().
ff_isom_write_vpcc()
int ff_isom_write_vpcc (AVFormatContext * s, AVIOContext * pb, AVCodecParameters * par)
Writes VP codec configuration to the provided AVIOContext.
Parameters
s address of the AVFormatContext for the logging context.
pb address of the AVIOContext where the vpcC shall be written.
par address of the AVCodecParameters which contains codec information.
Returns
>=0 in case of success, a negative value corresponding to an AVERROR code in case of failure
Definition at line 114 of file vpcc.c.
Referenced by mov_write_vpcc_tag().