FFmpeg: libswscale/vscale.c File Reference
vscale.c File Reference
#include "swscale_internal.h"
Data Structures
struct VScalerContext
Functions
static int lum_planar_vscale (SwsContext *c, SwsFilterDescriptor *desc, int sliceY, int sliceH)
static int chr_planar_vscale (SwsContext *c, SwsFilterDescriptor *desc, int sliceY, int sliceH)
static int packed_vscale (SwsContext *c, SwsFilterDescriptor *desc, int sliceY, int sliceH)
static int any_vscale (SwsContext *c, SwsFilterDescriptor *desc, int sliceY, int sliceH)
int ff_init_vscale (SwsContext *c, SwsFilterDescriptor *desc, SwsSlice *src, SwsSlice *dst)
initializes vertical scaling descriptors
void ff_init_vscale_pfn (SwsContext *c, yuv2planar1_fn yuv2plane1, yuv2planarX_fn yuv2planeX, yuv2interleavedX_fn yuv2nv12cX, yuv2packed1_fn yuv2packed1, yuv2packed2_fn yuv2packed2, yuv2packedX_fn yuv2packedX, yuv2anyX_fn yuv2anyX, int use_mmx)
setup vertical scaler functions
Function Documentation
lum_planar_vscale()
static int lum_planar_vscale (SwsContext * c, SwsFilterDescriptor * desc, int sliceY, int sliceH) static
Definition at line 33 of file vscale.c.
Referenced by ff_init_vscale().
chr_planar_vscale()
static int chr_planar_vscale (SwsContext * c, SwsFilterDescriptor * desc, int sliceY, int sliceH) static
Definition at line 66 of file vscale.c.
Referenced by ff_init_vscale().
packed_vscale()
static int packed_vscale (SwsContext * c, SwsFilterDescriptor * desc, int sliceY, int sliceH) static
Definition at line 101 of file vscale.c.
Referenced by ff_init_vscale().
any_vscale()
static int any_vscale (SwsContext * c, SwsFilterDescriptor * desc, int sliceY, int sliceH) static
Definition at line 165 of file vscale.c.
Referenced by ff_init_vscale().
ff_init_vscale()
int ff_init_vscale (SwsContext * c, SwsFilterDescriptor * desc, SwsSlice * src, SwsSlice * dst)
initializes vertical scaling descriptors
Definition at line 206 of file vscale.c.
Referenced by ff_init_filters().
ff_init_vscale_pfn()
void ff_init_vscale_pfn (SwsContext * c, yuv2planar1_fn yuv2plane1, yuv2planarX_fn yuv2planeX, yuv2interleavedX_fn yuv2nv12cX, yuv2packed1_fn yuv2packed1, yuv2packed2_fn yuv2packed2, yuv2packedX_fn yuv2packedX, yuv2anyX_fn yuv2anyX, int use_mmx)
setup vertical scaler functions
Definition at line 250 of file vscale.c.
Referenced by ff_init_vscale(), and swscale().