FFmpeg: libavfilter/vsrc_testsrc.c File Reference
vsrc_testsrc.c File Reference
Misc test sources.
#include <float.h>
#include "libavutil/avassert.h"
#include "libavutil/common.h"
#include "libavutil/ffmath.h"
#include "libavutil/opt.h"
#include "libavutil/imgutils.h"
#include "libavutil/intreadwrite.h"
#include "libavutil/parseutils.h"
#include "libavutil/xga_font_data.h"
#include "avfilter.h"
#include "drawutils.h"
#include "formats.h"
#include "internal.h"
#include "video.h"
Data Structures
struct TestSourceContext
Macros
#define OFFSET(x) offsetof(TestSourceContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
#define SIZE_OPTIONS
#define COMMON_OPTIONS_NOSIZE
#define COMMON_OPTIONS SIZE_OPTIONS COMMON_OPTIONS_NOSIZE
Functions
static av_cold int init (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
static int config_props (AVFilterLink *outlink)
static int request_frame (AVFilterLink *outlink)
Variables
static const AVOption options []
Detailed Description
Misc test sources.
testsrc is based on the test pattern generator demuxer by Nicolas George: http://lists.ffmpeg.org/pipermail/ffmpeg-devel/2007-October/037845.html
rgbtestsrc is ported from MPlayer libmpcodecs/vf_rgbtest.c by Michael Niedermayer.
allyuv, smptebars and smptehdbars are by Paul B Mahol.
Definition in file vsrc_testsrc.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(TestSourceContext, x)
Definition at line 83 of file vsrc_testsrc.c.
Referenced by request_frame().
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 84 of file vsrc_testsrc.c.
Referenced by request_frame().
SIZE_OPTIONS
#define SIZE_OPTIONS
Value:
{ "size",     "set video size",     OFFSET(w),        AV_OPT_TYPE_IMAGE_SIZE, {.str = "320x240"}, 0, 0, FLAGS },\
    { "s",        "set video size",     OFFSET(w),        AV_OPT_TYPE_IMAGE_SIZE, {.str = "320x240"}, 0, 0, FLAGS },\
Definition at line 86 of file vsrc_testsrc.c.
COMMON_OPTIONS_NOSIZE
#define COMMON_OPTIONS_NOSIZE
Value:
{ "rate",     "set video rate",     OFFSET(frame_rate), AV_OPT_TYPE_VIDEO_RATE, {.str = "25"}, 0, INT_MAX, FLAGS },\
    { "r",        "set video rate",     OFFSET(frame_rate), AV_OPT_TYPE_VIDEO_RATE, {.str = "25"}, 0, INT_MAX, FLAGS },\
    { "duration", "set video duration", OFFSET(duration), AV_OPT_TYPE_DURATION, {.i64 = -1}, -1, INT64_MAX, FLAGS },\
    { "d",        "set video duration", OFFSET(duration), AV_OPT_TYPE_DURATION, {.i64 = -1}, -1, INT64_MAX, FLAGS },\
    { "sar",      "set video sample aspect ratio", OFFSET(sar), AV_OPT_TYPE_RATIONAL, {.dbl= 1},  0, INT_MAX, FLAGS },
Definition at line 90 of file vsrc_testsrc.c.
Referenced by request_frame().
COMMON_OPTIONS
#define COMMON_OPTIONS SIZE_OPTIONS COMMON_OPTIONS_NOSIZE
Definition at line 97 of file vsrc_testsrc.c.
Referenced by request_frame().
Function Documentation
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 104 of file vsrc_testsrc.c.
Referenced by request_frame().
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 119 of file vsrc_testsrc.c.
Referenced by request_frame().
config_props()
static int config_props (AVFilterLink * outlink) static
Definition at line 126 of file vsrc_testsrc.c.
Referenced by request_frame().
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 139 of file vsrc_testsrc.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    COMMON_OPTIONS
    { NULL }
}
Definition at line 99 of file vsrc_testsrc.c.