FFmpeg: libavfilter/vsrc_mandelbrot.c File Reference
vsrc_mandelbrot.c File Reference
Mandelbrot fractal renderer.
#include "avfilter.h"
#include "formats.h"
#include "video.h"
#include "internal.h"
#include "libavutil/imgutils.h"
#include "libavutil/opt.h"
#include "libavutil/parseutils.h"
#include <float.h>
#include <math.h>
Data Structures
struct Point
struct MBContext
Macros
#define SQR(a) ((a)*(a))
#define OFFSET(x) offsetof(MBContext, x)
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
#define Z_Z2_C(outr, outi, inr, ini)
#define Z_Z2_C_ZYKLUS(outr, outi, inr, ini, Z)
Enumerations
enum Outer { ITERATION_COUNT, NORMALIZED_ITERATION_COUNT, WHITE, OUTZ }
enum Inner { BLACK, PERIOD, CONVTIME, MINCOL }
Functions
AVFILTER_DEFINE_CLASS (mandelbrot)
static av_cold int init (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
static int query_formats (AVFilterContext *ctx)
static int config_props (AVFilterLink *inlink)
static void fill_from_cache (AVFilterContext *ctx, uint32_t *color, int *in_cidx, int *out_cidx, double py, double scale)
static int interpol (MBContext *s, uint32_t *color, int x, int y, int linesize)
static void draw_mandelbrot (AVFilterContext *ctx, uint32_t *color, int linesize, int64_t pts)
static int request_frame (AVFilterLink *link)
Variables
static const AVOption mandelbrot_options []
static const AVFilterPad mandelbrot_outputs []
AVFilter ff_vsrc_mandelbrot
Detailed Description
Mandelbrot fractal renderer.
Definition in file vsrc_mandelbrot.c.
Macro Definition Documentation
SQR
#define SQR (a) ((a)*(a))
Definition at line 39 of file vsrc_mandelbrot.c.
Referenced by draw_mandelbrot().
OFFSET
#define OFFSET (x) offsetof(MBContext, x)
Definition at line 86 of file vsrc_mandelbrot.c.
FLAGS
#define FLAGS AV_OPT_FLAG_VIDEO_PARAM|AV_OPT_FLAG_FILTERING_PARAM
Definition at line 87 of file vsrc_mandelbrot.c.
Z_Z2_C
#define Z_Z2_C (outr, outi, inr, ini)
Value:
outr= inr*inr - ini*ini + cr;\
            outi= 2*inr*ini + ci;
Referenced by draw_mandelbrot().
Z_Z2_C_ZYKLUS
#define Z_Z2_C_ZYKLUS (outr, outi, inr, ini, Z)
Value:
Z_Z2_C(outr,outi,inr,ini)\
            if(use_zyklus){\
                if(Z && fabs(s->zyklus[i>>1][0]-outr)+fabs(s->zyklus[i>>1][1]-outi) <= epsilon)\
                    break;\
            }\
            s->zyklus[i][0]= outr;\
            s->zyklus[i][1]= outi;\
Referenced by draw_mandelbrot().
Enumeration Type Documentation
Outer
enum Outer
Enumerator
ITERATION_COUNT
NORMALIZED_ITERATION_COUNT
WHITE
OUTZ
Definition at line 41 of file vsrc_mandelbrot.c.
Inner
enum Inner
Enumerator
BLACK
PERIOD
CONVTIME
MINCOL
Definition at line 48 of file vsrc_mandelbrot.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (mandelbrot)
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 122 of file vsrc_mandelbrot.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 140 of file vsrc_mandelbrot.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 149 of file vsrc_mandelbrot.c.
config_props()
static int config_props (AVFilterLink * inlink) static
Definition at line 162 of file vsrc_mandelbrot.c.
fill_from_cache()
static void fill_from_cache (AVFilterContext * ctx, uint32_t * color, int * in_cidx, int * out_cidx, double py, double scale) static
Definition at line 177 of file vsrc_mandelbrot.c.
Referenced by draw_mandelbrot().
interpol()
static int interpol (MBContext * s, uint32_t * color, int x, int y, int linesize) static
Definition at line 195 of file vsrc_mandelbrot.c.
Referenced by dequant_lsp10r(), dequant_lsp16r(), draw_mandelbrot(), filter_edge(), filter_edge_16bit(), filter_intra(), filter_intra_16bit(), filter_line_c(), and filter_line_c_16bit().
draw_mandelbrot()
static void draw_mandelbrot (AVFilterContext * ctx, uint32_t * color, int linesize, int64_t pts) static
Definition at line 249 of file vsrc_mandelbrot.c.
Referenced by request_frame().
request_frame()
static int request_frame (AVFilterLink * link) static
Definition at line 398 of file vsrc_mandelbrot.c.
Variable Documentation
mandelbrot_options
const AVOption mandelbrot_options[] static
Initial value:
= {
    {"size",        "set frame size",                OFFSET(w),       AV_OPT_TYPE_IMAGE_SIZE, {.str="640x480"},  CHAR_MIN, CHAR_MAX, FLAGS },
    {"s",           "set frame size",                OFFSET(w),       AV_OPT_TYPE_IMAGE_SIZE, {.str="640x480"},  CHAR_MIN, CHAR_MAX, FLAGS },
    {"rate",        "set frame rate",                OFFSET(frame_rate), AV_OPT_TYPE_VIDEO_RATE, {.str="25"},  CHAR_MIN, CHAR_MAX, FLAGS },
    {"r",           "set frame rate",                OFFSET(frame_rate), AV_OPT_TYPE_VIDEO_RATE, {.str="25"},  CHAR_MIN, CHAR_MAX, FLAGS },
    {"maxiter",     "set max iterations number",     OFFSET(maxiter), AV_OPT_TYPE_INT,        {.i64=7189},  1,        INT_MAX, FLAGS },
    {"start_x",     "set the initial x position",    OFFSET(start_x), AV_OPT_TYPE_DOUBLE,     {.dbl=-0.743643887037158704752191506114774}, -100, 100, FLAGS },
    {"start_y",     "set the initial y position",    OFFSET(start_y), AV_OPT_TYPE_DOUBLE,     {.dbl=-0.131825904205311970493132056385139}, -100, 100, FLAGS },
    {"start_scale", "set the initial scale value",   OFFSET(start_scale), AV_OPT_TYPE_DOUBLE, {.dbl=3.0},  0, FLT_MAX, FLAGS },
    {"end_scale",   "set the terminal scale value",  OFFSET(end_scale), AV_OPT_TYPE_DOUBLE,   {.dbl=0.3},  0, FLT_MAX, FLAGS },
    {"end_pts",     "set the terminal pts value",    OFFSET(end_pts), AV_OPT_TYPE_DOUBLE,     {.dbl=400},  0, INT64_MAX, FLAGS },
    {"bailout",     "set the bailout value",         OFFSET(bailout), AV_OPT_TYPE_DOUBLE,     {.dbl=10},   0, FLT_MAX, FLAGS },
    {"morphxf",     "set morph x frequency",         OFFSET(morphxf), AV_OPT_TYPE_DOUBLE,     {.dbl=0.01},   -FLT_MAX, FLT_MAX, FLAGS },
    {"morphyf",     "set morph y frequency",         OFFSET(morphyf), AV_OPT_TYPE_DOUBLE,     {.dbl=0.0123}, -FLT_MAX, FLT_MAX, FLAGS },
    {"morphamp",    "set morph amplitude",           OFFSET(morphamp), AV_OPT_TYPE_DOUBLE,    {.dbl=0},      -FLT_MAX, FLT_MAX, FLAGS },
    {"outer",       "set outer coloring mode",       OFFSET(outer), AV_OPT_TYPE_INT, {.i64=NORMALIZED_ITERATION_COUNT}, 0, INT_MAX, FLAGS, "outer" },
    {"iteration_count", "set iteration count mode",  0, AV_OPT_TYPE_CONST, {.i64=ITERATION_COUNT}, INT_MIN, INT_MAX, FLAGS, "outer" },
    {"normalized_iteration_count", "set normalized iteration count mode",   0, AV_OPT_TYPE_CONST, {.i64=NORMALIZED_ITERATION_COUNT}, INT_MIN, INT_MAX, FLAGS, "outer" },
    {"white", "set white mode",                      0, AV_OPT_TYPE_CONST, {.i64=WHITE}, INT_MIN, INT_MAX, FLAGS, "outer" },
    {"outz",        "set outz mode",                 0, AV_OPT_TYPE_CONST, {.i64=OUTZ}, INT_MIN, INT_MAX, FLAGS, "outer" },
    {"inner",       "set inner coloring mode",       OFFSET(inner), AV_OPT_TYPE_INT, {.i64=MINCOL}, 0, INT_MAX, FLAGS, "inner" },
    {"black",       "set black mode",                0, AV_OPT_TYPE_CONST, {.i64=BLACK}, INT_MIN, INT_MAX, FLAGS, "inner"},
    {"period",      "set period mode",               0, AV_OPT_TYPE_CONST, {.i64=PERIOD}, INT_MIN, INT_MAX, FLAGS, "inner"},
    {"convergence", "show time until convergence",   0, AV_OPT_TYPE_CONST, {.i64=CONVTIME}, INT_MIN, INT_MAX, FLAGS, "inner"},
    {"mincol",      "color based on point closest to the origin of the iterations",   0, AV_OPT_TYPE_CONST, {.i64=MINCOL}, INT_MIN, INT_MAX, FLAGS, "inner"},
    {NULL},
}
Definition at line 89 of file vsrc_mandelbrot.c.
mandelbrot_outputs
const AVFilterPad mandelbrot_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .request_frame = request_frame,
        .config_props  = config_props,
    },
    { NULL }
}
Definition at line 412 of file vsrc_mandelbrot.c.
ff_vsrc_mandelbrot
AVFilter ff_vsrc_mandelbrot
Initial value:
= {
    .name          = "mandelbrot",
    .description   = NULL_IF_CONFIG_SMALL("Render a Mandelbrot fractal."),
    .priv_size     = sizeof(MBContext),
    .priv_class    = &mandelbrot_class,
    .init          = init,
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = NULL,
    .outputs       = mandelbrot_outputs,
}
Definition at line 422 of file vsrc_mandelbrot.c.