FFmpeg: libavfilter/vsrc_cellauto.c File Reference
vsrc_cellauto.c File Reference
cellular automaton video source, based on Stephen Wolfram "experimentus crucis"
#include "libavutil/file.h"
#include "libavutil/internal.h"
#include "libavutil/lfg.h"
#include "libavutil/opt.h"
#include "libavutil/parseutils.h"
#include "libavutil/random_seed.h"
#include "libavutil/avstring.h"
#include "avfilter.h"
#include "internal.h"
#include "formats.h"
#include "video.h"
Data Structures
struct CellAutoContext
Macros
#define OFFSET(x) offsetof(CellAutoContext, x)
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Functions
AVFILTER_DEFINE_CLASS (cellauto)
static int init_pattern_from_string (AVFilterContext *ctx)
static int init_pattern_from_file (AVFilterContext *ctx)
static av_cold int init (AVFilterContext *ctx)
static av_cold void uninit (AVFilterContext *ctx)
static int config_props (AVFilterLink *outlink)
static void evolve (AVFilterContext *ctx)
static void fill_picture (AVFilterContext *ctx, AVFrame *picref)
static int request_frame (AVFilterLink *outlink)
static int query_formats (AVFilterContext *ctx)
Variables
static const AVOption cellauto_options []
static const AVFilterPad cellauto_outputs []
AVFilter ff_vsrc_cellauto
Detailed Description
cellular automaton video source, based on Stephen Wolfram "experimentus crucis"
Definition in file vsrc_cellauto.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(CellAutoContext, x)
Definition at line 60 of file vsrc_cellauto.c.
FLAGS
#define FLAGS AV_OPT_FLAG_FILTERING_PARAM|AV_OPT_FLAG_VIDEO_PARAM
Definition at line 61 of file vsrc_cellauto.c.
Function Documentation
AVFILTER_DEFINE_CLASS()
AVFILTER_DEFINE_CLASS (cellauto)
init_pattern_from_string()
static int init_pattern_from_string (AVFilterContext * ctx) static
Definition at line 104 of file vsrc_cellauto.c.
Referenced by init(), and init_pattern_from_file().
init_pattern_from_file()
static int init_pattern_from_file (AVFilterContext * ctx) static
Definition at line 143 of file vsrc_cellauto.c.
Referenced by init().
init()
static av_cold int init (AVFilterContext * ctx) static
Definition at line 163 of file vsrc_cellauto.c.
uninit()
static av_cold void uninit (AVFilterContext * ctx) static
Definition at line 209 of file vsrc_cellauto.c.
config_props()
static int config_props (AVFilterLink * outlink) static
Definition at line 218 of file vsrc_cellauto.c.
evolve()
static void evolve (AVFilterContext * ctx) static
Definition at line 229 of file vsrc_cellauto.c.
Referenced by request_frame().
fill_picture()
static void fill_picture (AVFilterContext * ctx, AVFrame * picref) static
Definition at line 260 of file vsrc_cellauto.c.
Referenced by request_frame().
request_frame()
static int request_frame (AVFilterLink * outlink) static
Definition at line 288 of file vsrc_cellauto.c.
query_formats()
static int query_formats (AVFilterContext * ctx) static
Definition at line 311 of file vsrc_cellauto.c.
Variable Documentation
cellauto_options
const AVOption cellauto_options[] static
Initial value:
= {
    { "filename", "read initial pattern from file", OFFSET(filename), AV_OPT_TYPE_STRING, {.str = NULL}, 0, 0, FLAGS },
    { "f",        "read initial pattern from file", OFFSET(filename), AV_OPT_TYPE_STRING, {.str = NULL}, 0, 0, FLAGS },
    { "pattern",  "set initial pattern", OFFSET(pattern), AV_OPT_TYPE_STRING, {.str = NULL}, 0, 0, FLAGS },
    { "p",        "set initial pattern", OFFSET(pattern), AV_OPT_TYPE_STRING, {.str = NULL}, 0, 0, FLAGS },
    { "rate",     "set video rate", OFFSET(frame_rate), AV_OPT_TYPE_VIDEO_RATE, {.str = "25"}, 0, INT_MAX, FLAGS },
    { "r",        "set video rate", OFFSET(frame_rate), AV_OPT_TYPE_VIDEO_RATE, {.str = "25"}, 0, INT_MAX, FLAGS },
    { "size",     "set video size", OFFSET(w),    AV_OPT_TYPE_IMAGE_SIZE, {.str = NULL}, 0, 0, FLAGS },
    { "s",        "set video size", OFFSET(w),    AV_OPT_TYPE_IMAGE_SIZE, {.str = NULL}, 0, 0, FLAGS },
    { "rule",     "set rule",       OFFSET(rule), AV_OPT_TYPE_INT,    {.i64 = 110},  0, 255, FLAGS },
    { "random_fill_ratio", "set fill ratio for filling initial grid randomly", OFFSET(random_fill_ratio), AV_OPT_TYPE_DOUBLE, {.dbl = 1/M_PHI}, 0, 1, FLAGS },
    { "ratio",             "set fill ratio for filling initial grid randomly", OFFSET(random_fill_ratio), AV_OPT_TYPE_DOUBLE, {.dbl = 1/M_PHI}, 0, 1, FLAGS },
    { "random_seed", "set the seed for filling the initial grid randomly", OFFSET(random_seed), AV_OPT_TYPE_INT, {.i64 = -1}, -1, UINT32_MAX, FLAGS },
    { "seed",        "set the seed for filling the initial grid randomly", OFFSET(random_seed), AV_OPT_TYPE_INT, {.i64 = -1}, -1, UINT32_MAX, FLAGS },
    { "scroll",      "scroll pattern downward", OFFSET(scroll), AV_OPT_TYPE_BOOL, {.i64 = 1}, 0, 1, FLAGS },
    { "start_full",  "start filling the whole video", OFFSET(start_full), AV_OPT_TYPE_BOOL, {.i64 = 0}, 0, 1, FLAGS },
    { "full",        "start filling the whole video", OFFSET(start_full), AV_OPT_TYPE_BOOL, {.i64 = 1}, 0, 1, FLAGS },
    { "stitch",      "stitch boundaries", OFFSET(stitch), AV_OPT_TYPE_BOOL,    {.i64 = 1},   0, 1, FLAGS },
    { NULL }
}
Definition at line 63 of file vsrc_cellauto.c.
cellauto_outputs
const AVFilterPad cellauto_outputs[] static
Initial value:
= {
    {
        .name          = "default",
        .type          = AVMEDIA_TYPE_VIDEO,
        .request_frame = request_frame,
        .config_props  = config_props,
    },
    { NULL }
}
Definition at line 320 of file vsrc_cellauto.c.
ff_vsrc_cellauto
AVFilter ff_vsrc_cellauto
Initial value:
= {
    .name          = "cellauto",
    .description   = NULL_IF_CONFIG_SMALL("Create pattern generated by an elementary cellular automaton."),
    .priv_size     = sizeof(CellAutoContext),
    .priv_class    = &cellauto_class,
    .init          = init,
    .uninit        = uninit,
    .query_formats = query_formats,
    .inputs        = NULL,
    .outputs       = cellauto_outputs,
}
Definition at line 330 of file vsrc_cellauto.c.