FFmpeg: compat/w32pthreads.h File Reference
w32pthreads.h File Reference
w32threads to pthreads wrapper
#include <windows.h>
#include <process.h>
#include "libavutil/attributes.h"
#include "libavutil/common.h"
#include "libavutil/internal.h"
#include "libavutil/mem.h"
Data Structures
struct pthread_t
struct pthread_cond_t
union pthread_once_t
struct win32_cond_t
Macros
#define WIN32_LEAN_AND_MEAN
#define PTHREAD_ONCE_INIT {0}
Typedefs
typedef CRITICAL_SECTION pthread_mutex_t
Functions
static av_unused unsigned __stdcall attribute_align_arg win32thread_worker (void *arg)
static av_unused int pthread_create (pthread_t *thread, const void *unused_attr, void *(*start_routine)(void *), void *arg)
static av_unused int pthread_join (pthread_t thread, void **value_ptr)
static int pthread_mutex_init (pthread_mutex_t *m, void *attr)
static int pthread_mutex_destroy (pthread_mutex_t *m)
static int pthread_mutex_lock (pthread_mutex_t *m)
static int pthread_mutex_unlock (pthread_mutex_t *m)
static av_unused void w32thread_init (void)
static BOOL (WINAPI *initonce_begin)(pthread_once_t *lpInitOnce
static void w32thread_once_fallback (LONG volatile *state, void(*init_routine)(void))
static av_unused int pthread_once (pthread_once_t *once_control, void(*init_routine)(void))
static void (WINAPI *cond_broadcast)(pthread_cond_t *cond)
static av_unused int pthread_cond_init (pthread_cond_t *cond, const void *unused_attr)
static av_unused int pthread_cond_destroy (pthread_cond_t *cond)
static av_unused int pthread_cond_broadcast (pthread_cond_t *cond)
static av_unused int pthread_cond_wait (pthread_cond_t *cond, pthread_mutex_t *mutex)
static av_unused int pthread_cond_signal (pthread_cond_t *cond)
Variables
static LONG w32thread_init_state = 0
static DWORD dwFlags
static DWORD BOOL * fPending
static DWORD BOOL void ** lpContext
static pthread_mutex_t * mutex
static pthread_mutex_t DWORD milliseconds
Detailed Description
w32threads to pthreads wrapper
Definition in file w32pthreads.h.
Macro Definition Documentation
WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
Definition at line 38 of file w32pthreads.h.
PTHREAD_ONCE_INIT
#define PTHREAD_ONCE_INIT {0}
Definition at line 194 of file w32pthreads.h.
Typedef Documentation
pthread_mutex_t
typedef CRITICAL_SECTION pthread_mutex_t
Definition at line 61 of file w32pthreads.h.
Function Documentation
win32thread_worker()
static av_unused unsigned __stdcall attribute_align_arg win32thread_worker (void * arg) static
Definition at line 78 of file w32pthreads.h.
Referenced by pthread_create().
pthread_create()
static av_unused int pthread_create (pthread_t * thread, const void * unused_attr, void *(*)(void *) start_routine, void * arg) static
Definition at line 85 of file w32pthreads.h.
pthread_join()
static av_unused int pthread_join (pthread_t thread, void ** value_ptr) static
Definition at line 100 of file w32pthreads.h.
pthread_mutex_init()
static int pthread_mutex_init (pthread_mutex_t * m, void * attr) inline static
Definition at line 115 of file w32pthreads.h.
Referenced by pthread_cond_init().
pthread_mutex_destroy()
static int pthread_mutex_destroy (pthread_mutex_t * m) inline static
Definition at line 120 of file w32pthreads.h.
Referenced by pthread_cond_destroy().
pthread_mutex_lock()
static int pthread_mutex_lock (pthread_mutex_t * m) inline static
Definition at line 125 of file w32pthreads.h.
Referenced by pthread_cond_broadcast(), pthread_cond_signal(), and pthread_cond_wait().
pthread_mutex_unlock()
static int pthread_mutex_unlock (pthread_mutex_t * m) inline static
Definition at line 130 of file w32pthreads.h.
Referenced by pthread_cond_broadcast(), pthread_cond_signal(), and pthread_cond_wait().
w32thread_init()
static av_unused void w32thread_init (void) static
Definition at line 397 of file w32pthreads.h.
Referenced by ff_frame_thread_init(), ff_graph_thread_init(), ff_slice_thread_init(), pthread_cond_init(), and pthread_once().
BOOL()
static BOOL (WINAPI * initonce_begin) static
w32thread_once_fallback()
static void w32thread_once_fallback (LONG volatile * state, void(*)(void) init_routine) inline static
Definition at line 201 of file w32pthreads.h.
Referenced by pthread_cond_init(), and pthread_once().
pthread_once()
static av_unused int pthread_once (pthread_once_t * once_control, void(*)(void) init_routine) static
Definition at line 224 of file w32pthreads.h.
Referenced by pthread_mutex_unlock().
void()
static void (WINAPI * cond_broadcast) static
pthread_cond_init()
static av_unused int pthread_cond_init (pthread_cond_t * cond, const void * unused_attr) static
Definition at line 261 of file w32pthreads.h.
Referenced by pthread_mutex_unlock().
pthread_cond_destroy()
static av_unused int pthread_cond_destroy (pthread_cond_t * cond) static
Definition at line 289 of file w32pthreads.h.
Referenced by pthread_mutex_unlock().
pthread_cond_broadcast()
static av_unused int pthread_cond_broadcast (pthread_cond_t * cond) static
Definition at line 306 of file w32pthreads.h.
Referenced by pthread_mutex_unlock().
pthread_cond_wait()
static av_unused int pthread_cond_wait (pthread_cond_t * cond, pthread_mutex_t * mutex) static
Definition at line 338 of file w32pthreads.h.
Referenced by pthread_mutex_unlock().
pthread_cond_signal()
static av_unused int pthread_cond_signal (pthread_cond_t * cond) static
Definition at line 370 of file w32pthreads.h.
Referenced by pthread_mutex_unlock().
Variable Documentation
w32thread_init_state
LONG w32thread_init_state = 0 static
Definition at line 183 of file w32pthreads.h.
dwFlags
static DWORD dwFlags
Definition at line 197 of file w32pthreads.h.
Referenced by dump_videohdr().
fPending
DWORD BOOL* fPending
Definition at line 197 of file w32pthreads.h.
lpContext
static DWORD void * lpContext
Definition at line 197 of file w32pthreads.h.
mutex
pthread_mutex_t* mutex
Definition at line 258 of file w32pthreads.h.
Referenced by av_log_default_callback(), and pthread_mutex_unlock().
milliseconds
pthread_mutex_t DWORD milliseconds
Definition at line 258 of file w32pthreads.h.