FFmpeg: libavcodec/wavpack.c File Reference
wavpack.c File Reference
WavPack lossless audio decoder.
#include "libavutil/channel_layout.h"
#include "avcodec.h"
#include "bytestream.h"
#include "get_bits.h"
#include "internal.h"
#include "thread.h"
#include "unary.h"
#include "wavpack.h"
Data Structures
struct SavedContext
struct WavpackFrameContext
struct WavpackContext
Macros
#define BITSTREAM_READER_LE
#define WV_MAX_FRAME_DECODERS 14
#define LEVEL_DECAY(a) (((a) + 0x80) >> 8)
Functions
static av_always_inline int get_tail (GetBitContext *gb, int k)
static void update_error_limit (WavpackFrameContext *ctx)
static int wv_get_value (WavpackFrameContext *ctx, GetBitContext *gb, int channel, int *last)
static int wv_get_value_integer (WavpackFrameContext *s, uint32_t *crc, int S)
static float wv_get_value_float (WavpackFrameContext *s, uint32_t *crc, int S)
static void wv_reset_saved_context (WavpackFrameContext *s)
static int wv_check_crc (WavpackFrameContext *s, uint32_t crc, uint32_t crc_extra_bits)
static int wv_unpack_stereo (WavpackFrameContext *s, GetBitContext *gb, void *dst_l, void *dst_r, const int type)
static int wv_unpack_mono (WavpackFrameContext *s, GetBitContext *gb, void *dst, const int type)
static av_cold int wv_alloc_frame_context (WavpackContext *c)
static av_cold int wavpack_decode_init (AVCodecContext *avctx)
static av_cold int wavpack_decode_end (AVCodecContext *avctx)
static int wavpack_decode_block (AVCodecContext *avctx, int block_no, AVFrame *frame, const uint8_t *buf, int buf_size)
static void wavpack_decode_flush (AVCodecContext *avctx)
static int wavpack_decode_frame (AVCodecContext *avctx, void *data, int *got_frame_ptr, AVPacket *avpkt)
Variables
AVCodec ff_wavpack_decoder
Detailed Description
WavPack lossless audio decoder.
Definition in file wavpack.c.
Macro Definition Documentation
BITSTREAM_READER_LE
#define BITSTREAM_READER_LE
Definition at line 24 of file wavpack.c.
WV_MAX_FRAME_DECODERS
#define WV_MAX_FRAME_DECODERS 14
Definition at line 73 of file wavpack.c.
Referenced by wv_alloc_frame_context().
LEVEL_DECAY
#define LEVEL_DECAY (a) (((a) + 0x80) >> 8)
Definition at line 86 of file wavpack.c.
Referenced by update_error_limit(), and wv_get_value().
Function Documentation
get_tail()
static av_always_inline int get_tail (GetBitContext * gb, int k) static
Definition at line 88 of file wavpack.c.
Referenced by wv_get_value().
update_error_limit()
static void update_error_limit (WavpackFrameContext * ctx) static
Definition at line 102 of file wavpack.c.
Referenced by wv_get_value().
wv_get_value()
static int wv_get_value (WavpackFrameContext * ctx, GetBitContext * gb, int channel, int * last) static
Definition at line 136 of file wavpack.c.
Referenced by wv_unpack_mono(), and wv_unpack_stereo().
wv_get_value_integer()
static int wv_get_value_integer (WavpackFrameContext * s, uint32_t * crc, int S) inline static
Definition at line 264 of file wavpack.c.
Referenced by wv_unpack_mono(), and wv_unpack_stereo().
wv_get_value_float()
static float wv_get_value_float (WavpackFrameContext * s, uint32_t * crc, int S) static
Definition at line 288 of file wavpack.c.
Referenced by wv_unpack_mono(), and wv_unpack_stereo().
wv_reset_saved_context()
static void wv_reset_saved_context (WavpackFrameContext * s) static
Definition at line 362 of file wavpack.c.
Referenced by wavpack_decode_flush(), wv_alloc_frame_context(), wv_unpack_mono(), and wv_unpack_stereo().
wv_check_crc()
static int wv_check_crc (WavpackFrameContext * s, uint32_t crc, uint32_t crc_extra_bits) inline static
Definition at line 368 of file wavpack.c.
Referenced by wv_unpack_mono(), and wv_unpack_stereo().
wv_unpack_stereo()
static int wv_unpack_stereo (WavpackFrameContext * s, GetBitContext * gb, void * dst_l, void * dst_r, const int type) inline static
Definition at line 383 of file wavpack.c.
Referenced by wavpack_decode_block().
wv_unpack_mono()
static int wv_unpack_mono (WavpackFrameContext * s, GetBitContext * gb, void * dst, const int type) inline static
Definition at line 516 of file wavpack.c.
Referenced by wavpack_decode_block().
wv_alloc_frame_context()
static av_cold int wv_alloc_frame_context (WavpackContext * c) static
Definition at line 585 of file wavpack.c.
Referenced by wavpack_decode_block().
wavpack_decode_init()
static av_cold int wavpack_decode_init (AVCodecContext * avctx) static
Definition at line 609 of file wavpack.c.
wavpack_decode_end()
static av_cold int wavpack_decode_end (AVCodecContext * avctx) static
Definition at line 620 of file wavpack.c.
wavpack_decode_block()
static int wavpack_decode_block (AVCodecContext * avctx, int block_no, AVFrame * frame, const uint8_t * buf, int buf_size) static
Definition at line 632 of file wavpack.c.
Referenced by wavpack_decode_frame().
wavpack_decode_flush()
static void wavpack_decode_flush (AVCodecContext * avctx) static
Definition at line 1044 of file wavpack.c.
Referenced by wavpack_decode_frame().
wavpack_decode_frame()
static int wavpack_decode_frame (AVCodecContext * avctx, void * data, int * got_frame_ptr, AVPacket * avpkt) static
Definition at line 1053 of file wavpack.c.
Variable Documentation
ff_wavpack_decoder
AVCodec ff_wavpack_decoder
Initial value:
= {
    .name           = "wavpack",
    .long_name      = NULL_IF_CONFIG_SMALL("WavPack"),
    .type           = AVMEDIA_TYPE_AUDIO,
    .id             = AV_CODEC_ID_WAVPACK,
    .priv_data_size = sizeof(WavpackContext),
    .init           = wavpack_decode_init,
    .close          = wavpack_decode_end,
    .decode         = wavpack_decode_frame,
    .flush          = wavpack_decode_flush,
    .init_thread_copy = ONLY_IF_THREADS_ENABLED(init_thread_copy),
    .capabilities   = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_FRAME_THREADS,
}
Definition at line 1119 of file wavpack.c.