FFmpeg: libavformat/webmdashenc.c File Reference
webmdashenc.c File Reference
#include <float.h>
#include <stdint.h>
#include <string.h>
#include "avformat.h"
#include "avio_internal.h"
#include "matroska.h"
#include "libavutil/avstring.h"
#include "libavutil/dict.h"
#include "libavutil/opt.h"
#include "libavutil/time_internal.h"
Data Structures
struct AdaptationSet
struct WebMDashMuxContext
Macros
#define OFFSET(x) offsetof(WebMDashMuxContext, x)
Functions
static const char * get_codec_name (int codec_id)
static double get_duration (AVFormatContext *s)
static int write_header (AVFormatContext *s)
static void write_footer (AVFormatContext *s)
static int subsegment_alignment (AVFormatContext *s, AdaptationSet *as)
static int bitstream_switching (AVFormatContext *s, AdaptationSet *as)
static int write_representation (AVFormatContext *s, AVStream *stream, char *id, int output_width, int output_height, int output_sample_rate)
static int check_matching_width (AVFormatContext *s, AdaptationSet *as)
static int check_matching_height (AVFormatContext *s, AdaptationSet *as)
static int check_matching_sample_rate (AVFormatContext *s, AdaptationSet *as)
static void free_adaptation_sets (AVFormatContext *s)
static int parse_filename (char *filename, char **representation_id, char **initialization_pattern, char **media_pattern)
static int write_adaptation_set (AVFormatContext *s, int as_index)
static int to_integer (char *p, int len)
static int parse_adaptation_sets (AVFormatContext *s)
static int webm_dash_manifest_write_header (AVFormatContext *s)
static int webm_dash_manifest_write_packet (AVFormatContext *s, AVPacket *pkt)
static int webm_dash_manifest_write_trailer (AVFormatContext *s)
Variables
static const AVOption options []
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(WebMDashMuxContext, x)
Definition at line 518 of file webmdashenc.c.
Function Documentation
get_codec_name()
static const char* get_codec_name (int codec_id) static
Definition at line 63 of file webmdashenc.c.
Referenced by write_adaptation_set(), and write_representation().
get_duration()
static double get_duration (AVFormatContext * s) static
Definition at line 78 of file webmdashenc.c.
Referenced by webm_dash_manifest_write_header(), and write_header().
write_header()
static int write_header (AVFormatContext * s) static
Definition at line 91 of file webmdashenc.c.
Referenced by webm_dash_manifest_write_header().
write_footer()
static void write_footer (AVFormatContext * s) static
Definition at line 133 of file webmdashenc.c.
Referenced by webm_dash_manifest_write_header().
subsegment_alignment()
static int subsegment_alignment (AVFormatContext * s, AdaptationSet * as) static
Definition at line 138 of file webmdashenc.c.
Referenced by write_adaptation_set().
bitstream_switching()
static int bitstream_switching (AVFormatContext * s, AdaptationSet * as) static
Definition at line 151 of file webmdashenc.c.
Referenced by write_adaptation_set().
write_representation()
static int write_representation (AVFormatContext * s, AVStream * stream, char * id, int output_width, int output_height, int output_sample_rate) static
Definition at line 176 of file webmdashenc.c.
Referenced by write_adaptation_set().
check_matching_width()
static int check_matching_width (AVFormatContext * s, AdaptationSet * as) static
Definition at line 224 of file webmdashenc.c.
Referenced by write_adaptation_set().
check_matching_height()
static int check_matching_height (AVFormatContext * s, AdaptationSet * as) static
Definition at line 237 of file webmdashenc.c.
Referenced by write_adaptation_set().
check_matching_sample_rate()
static int check_matching_sample_rate (AVFormatContext * s, AdaptationSet * as) static
Definition at line 250 of file webmdashenc.c.
Referenced by write_adaptation_set().
free_adaptation_sets()
static void free_adaptation_sets (AVFormatContext * s) static
Definition at line 260 of file webmdashenc.c.
Referenced by webm_dash_manifest_write_header(), and webm_dash_manifest_write_trailer().
parse_filename()
static int parse_filename (char * filename, char ** representation_id, char ** initialization_pattern, char ** media_pattern) static
Definition at line 280 of file webmdashenc.c.
Referenced by write_adaptation_set().
write_adaptation_set()
static int write_adaptation_set (AVFormatContext * s, int as_index) static
Definition at line 318 of file webmdashenc.c.
Referenced by webm_dash_manifest_write_header().
to_integer()
static int to_integer (char * p, int len) static
Definition at line 413 of file webmdashenc.c.
Referenced by parse_adaptation_sets().
parse_adaptation_sets()
static int parse_adaptation_sets (AVFormatContext * s) static
Definition at line 425 of file webmdashenc.c.
Referenced by webm_dash_manifest_write_header().
webm_dash_manifest_write_header()
static int webm_dash_manifest_write_header (AVFormatContext * s) static
Definition at line 472 of file webmdashenc.c.
webm_dash_manifest_write_packet()
static int webm_dash_manifest_write_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 507 of file webmdashenc.c.
webm_dash_manifest_write_trailer()
static int webm_dash_manifest_write_trailer (AVFormatContext * s) static
Definition at line 512 of file webmdashenc.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "adaptation_sets", "Adaptation sets. Syntax: id=0,streams=0,1,2 id=1,streams=3,4 and so on", OFFSET(adaptation_sets), AV_OPT_TYPE_STRING, { 0 }, 0, 0, AV_OPT_FLAG_ENCODING_PARAM },
    { "debug_mode", "[private option - users should never set this]. Create deterministic output", OFFSET(debug_mode), AV_OPT_TYPE_BOOL, {.i64 = 0}, 0, 1, AV_OPT_FLAG_ENCODING_PARAM },
    { "live", "create a live stream manifest", OFFSET(is_live), AV_OPT_TYPE_BOOL, {.i64 = 0}, 0, 1, AV_OPT_FLAG_ENCODING_PARAM },
    { "chunk_start_index",  "start index of the chunk", OFFSET(chunk_start_index), AV_OPT_TYPE_INT, {.i64 = 0}, 0, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM },
    { "chunk_duration_ms", "duration of each chunk (in milliseconds)", OFFSET(chunk_duration), AV_OPT_TYPE_INT, {.i64 = 1000}, 0, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM },
    { "utc_timing_url", "URL of the page that will return the UTC timestamp in ISO format", OFFSET(utc_timing_url), AV_OPT_TYPE_STRING, { 0 }, 0, 0, AV_OPT_FLAG_ENCODING_PARAM },
    { "time_shift_buffer_depth", "Smallest time (in seconds) shifting buffer for which any Representation is guaranteed to be available.", OFFSET(time_shift_buffer_depth), AV_OPT_TYPE_DOUBLE, { .dbl = 60.0 }, 1.0, DBL_MAX, AV_OPT_FLAG_ENCODING_PARAM },
    { "minimum_update_period", "Minimum Update Period (in seconds) of the manifest.", OFFSET(minimum_update_period), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM },
    { NULL },
}
Definition at line 519 of file webmdashenc.c.