FFmpeg: libavformat/webpenc.c File Reference
webpenc.c File Reference
#include "libavutil/intreadwrite.h"
#include "libavutil/opt.h"
#include "avformat.h"
#include "internal.h"
Data Structures
struct WebpContext
Macros
#define OFFSET(x) offsetof(WebpContext, x)
#define ENC AV_OPT_FLAG_ENCODING_PARAM
Functions
static int webp_write_header (AVFormatContext *s)
static int is_animated_webp_packet (AVPacket *pkt)
static int flush (AVFormatContext *s, int trailer, int64_t pts)
static int webp_write_packet (AVFormatContext *s, AVPacket *pkt)
static int webp_write_trailer (AVFormatContext *s)
Variables
static const AVOption options []
static const AVClass webp_muxer_class
AVOutputFormat ff_webp_muxer
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(WebpContext, x)
Definition at line 193 of file webpenc.c.
ENC
#define ENC AV_OPT_FLAG_ENCODING_PARAM
Definition at line 194 of file webpenc.c.
Function Documentation
webp_write_header()
static int webp_write_header (AVFormatContext * s) static
Definition at line 36 of file webpenc.c.
is_animated_webp_packet()
static int is_animated_webp_packet (AVPacket * pkt) static
Definition at line 54 of file webpenc.c.
Referenced by webp_write_packet().
flush()
static int flush (AVFormatContext * s, int trailer, int64_t pts) static
Definition at line 77 of file webpenc.c.
Referenced by webp_write_packet(), and webp_write_trailer().
webp_write_packet()
static int webp_write_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 149 of file webpenc.c.
webp_write_trailer()
static int webp_write_trailer (AVFormatContext * s) static
Definition at line 168 of file webpenc.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "loop", "Number of times to loop the output: 0 - infinite loop", OFFSET(loop),
      AV_OPT_TYPE_INT, { .i64 = 1 }, 0, 65535, ENC },
    { NULL },
}
Definition at line 195 of file webpenc.c.
webp_muxer_class
const AVClass webp_muxer_class static
Initial value:
= {
    .class_name = "WebP muxer",
    .item_name  = av_default_item_name,
    .version    = LIBAVUTIL_VERSION_INT,
    .option     = options,
}
Definition at line 201 of file webpenc.c.
ff_webp_muxer
AVOutputFormat ff_webp_muxer
Initial value:
= {
    .name           = "webp",
    .long_name      = NULL_IF_CONFIG_SMALL("WebP"),
    .extensions     = "webp",
    .priv_data_size = sizeof(WebpContext),
    .video_codec    = AV_CODEC_ID_WEBP,
    .write_header   = webp_write_header,
    .write_packet   = webp_write_packet,
    .write_trailer  = webp_write_trailer,
    .priv_class     = &webp_muxer_class,
    .flags          = AVFMT_VARIABLE_FPS,
}
Definition at line 207 of file webpenc.c.