FFmpeg: libavcodec/wmaenc.c File Reference
wmaenc.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/ffmath.h"
#include "avcodec.h"
#include "internal.h"
#include "wma.h"
#include "libavutil/avassert.h"
Functions
static av_cold int encode_init (AVCodecContext *avctx)
static int apply_window_and_mdct (AVCodecContext *avctx, const AVFrame *frame)
static void init_exp (WMACodecContext *s, int ch, const int *exp_param)
static void encode_exp_vlc (WMACodecContext *s, int ch, const int *exp_param)
static int encode_block (WMACodecContext *s, float(*src_coefs)[BLOCK_MAX_SIZE], int total_gain)
static int encode_frame (WMACodecContext *s, float(*src_coefs)[BLOCK_MAX_SIZE], uint8_t *buf, int buf_size, int total_gain)
static int encode_superframe (AVCodecContext *avctx, AVPacket *avpkt, const AVFrame *frame, int *got_packet_ptr)
Function Documentation
encode_init()
static av_cold int encode_init (AVCodecContext * avctx) static
Definition at line 31 of file wmaenc.c.
Referenced by encode_superframe().
apply_window_and_mdct()
static int apply_window_and_mdct (AVCodecContext * avctx, const AVFrame * frame) static
Definition at line 103 of file wmaenc.c.
Referenced by encode_superframe().
init_exp()
static void init_exp (WMACodecContext * s, int ch, const int * exp_param) static
Definition at line 132 of file wmaenc.c.
Referenced by encode_block().
encode_exp_vlc()
static void encode_exp_vlc (WMACodecContext * s, int ch, const int * exp_param) static
Definition at line 154 of file wmaenc.c.
Referenced by encode_block().
encode_block()
static int encode_block (WMACodecContext * s, float(*) src_coefs[BLOCK_MAX_SIZE], int total_gain) static
Definition at line 182 of file wmaenc.c.
Referenced by encode_frame().
encode_frame()
static int encode_frame (WMACodecContext * s, float(*) src_coefs[BLOCK_MAX_SIZE], uint8_t * buf, int buf_size, int total_gain) static
Definition at line 351 of file wmaenc.c.
Referenced by encode_superframe().
encode_superframe()
static int encode_superframe (AVCodecContext * avctx, AVPacket * avpkt, const AVFrame * frame, int * got_packet_ptr) static
Definition at line 366 of file wmaenc.c.