FFmpeg: libavcodec/wmv2.h File Reference
wmv2.h File Reference
#include "avcodec.h"
#include "intrax8.h"
#include "mpegvideo.h"
#include "wmv2dsp.h"
Data Structures
struct Wmv2Context
Macros
#define SKIP_TYPE_NONE 0
#define SKIP_TYPE_MPEG 1
#define SKIP_TYPE_ROW 2
#define SKIP_TYPE_COL 3
Functions
void ff_wmv2_common_init (Wmv2Context *w)
int ff_wmv2_decode_mb (MpegEncContext *s, int16_t block[6][64])
int ff_wmv2_encode_picture_header (MpegEncContext *s, int picture_number)
void ff_wmv2_encode_mb (MpegEncContext *s, int16_t block[6][64], int motion_x, int motion_y)
int ff_wmv2_decode_picture_header (MpegEncContext *s)
int ff_wmv2_decode_secondary_picture_header (MpegEncContext *s)
void ff_wmv2_add_mb (MpegEncContext *s, int16_t block[6][64], uint8_t *dest_y, uint8_t *dest_cb, uint8_t *dest_cr)
void ff_mspel_motion (MpegEncContext *s, uint8_t *dest_y, uint8_t *dest_cb, uint8_t *dest_cr, uint8_t **ref_picture, op_pixels_func(*pix_op)[4], int motion_x, int motion_y, int h)
static av_always_inline int wmv2_get_cbp_table_index (MpegEncContext *s, int cbp_index)
Macro Definition Documentation
SKIP_TYPE_NONE
#define SKIP_TYPE_NONE 0
Definition at line 29 of file wmv2.h.
Referenced by ff_wmv2_encode_picture_header(), and parse_mb_skip().
SKIP_TYPE_MPEG
#define SKIP_TYPE_MPEG 1
Definition at line 30 of file wmv2.h.
Referenced by parse_mb_skip().
SKIP_TYPE_ROW
#define SKIP_TYPE_ROW 2
Definition at line 31 of file wmv2.h.
Referenced by parse_mb_skip().
SKIP_TYPE_COL
#define SKIP_TYPE_COL 3
Definition at line 32 of file wmv2.h.
Referenced by parse_mb_skip().
Function Documentation
ff_wmv2_common_init()
void ff_wmv2_common_init (Wmv2Context * w)
Definition at line 31 of file wmv2.c.
Referenced by wmv2_decode_init(), and wmv2_encode_init().
ff_wmv2_decode_mb()
int ff_wmv2_decode_mb (MpegEncContext * s, int16_t block[6][64])
Definition at line 339 of file wmv2dec.c.
Referenced by ff_msmpeg4_decode_init().
ff_wmv2_encode_picture_header()
int ff_wmv2_encode_picture_header (MpegEncContext * s, int picture_number)
Definition at line 74 of file wmv2enc.c.
Referenced by encode_picture().
ff_wmv2_encode_mb()
void ff_wmv2_encode_mb (MpegEncContext * s, int16_t block[6][64], int motion_x, int motion_y)
Definition at line 147 of file wmv2enc.c.
Referenced by encode_mb_internal().
ff_wmv2_decode_picture_header()
int ff_wmv2_decode_picture_header (MpegEncContext * s)
Definition at line 120 of file wmv2dec.c.
Referenced by ff_h263_decode_frame().
ff_wmv2_decode_secondary_picture_header()
int ff_wmv2_decode_secondary_picture_header (MpegEncContext * s)
Definition at line 140 of file wmv2dec.c.
Referenced by ff_h263_decode_frame().
ff_wmv2_add_mb()
void ff_wmv2_add_mb (MpegEncContext * s, int16_t block[6][64], uint8_t * dest_y, uint8_t * dest_cb, uint8_t * dest_cr)
Definition at line 83 of file wmv2.c.
Referenced by mpv_decode_mb_internal().
ff_mspel_motion()
void ff_mspel_motion (MpegEncContext * s, uint8_t * dest_y, uint8_t * dest_cb, uint8_t * dest_cr, uint8_t ** ref_picture, op_pixels_func(*) pix_op[4], int motion_x, int motion_y, int h)
Definition at line 100 of file wmv2.c.
Referenced by mpv_motion_internal().
wmv2_get_cbp_table_index()
static av_always_inline int wmv2_get_cbp_table_index (MpegEncContext * s, int cbp_index) static
Definition at line 74 of file wmv2.h.
Referenced by ff_wmv2_decode_secondary_picture_header(), and ff_wmv2_encode_picture_header().