FFmpeg: libavcodec/wmv2.c File Reference
wmv2.c File Reference
#include "avcodec.h"
#include "idctdsp.h"
#include "mpegutils.h"
#include "mpegvideo.h"
#include "msmpeg4data.h"
#include "simple_idct.h"
#include "wmv2.h"
#include "wmv2data.h"
Functions
av_cold void ff_wmv2_common_init (Wmv2Context *w)
static void wmv2_add_block (Wmv2Context *w, int16_t *block1, uint8_t *dst, int stride, int n)
void ff_wmv2_add_mb (MpegEncContext *s, int16_t block1[6][64], uint8_t *dest_y, uint8_t *dest_cb, uint8_t *dest_cr)
void ff_mspel_motion (MpegEncContext *s, uint8_t *dest_y, uint8_t *dest_cb, uint8_t *dest_cr, uint8_t **ref_picture, op_pixels_func(*pix_op)[4], int motion_x, int motion_y, int h)
Function Documentation
ff_wmv2_common_init()
av_cold void ff_wmv2_common_init (Wmv2Context * w)
Definition at line 31 of file wmv2.c.
Referenced by wmv2_decode_init(), and wmv2_encode_init().
wmv2_add_block()
static void wmv2_add_block (Wmv2Context * w, int16_t * block1, uint8_t * dst, int stride, int n) static
Definition at line 57 of file wmv2.c.
Referenced by ff_wmv2_add_mb().
ff_wmv2_add_mb()
void ff_wmv2_add_mb (MpegEncContext * s, int16_t block1[6][64], uint8_t * dest_y, uint8_t * dest_cb, uint8_t * dest_cr)
Definition at line 83 of file wmv2.c.
Referenced by mpv_decode_mb_internal().
ff_mspel_motion()
void ff_mspel_motion (MpegEncContext * s, uint8_t * dest_y, uint8_t * dest_cb, uint8_t * dest_cr, uint8_t ** ref_picture, op_pixels_func(*) pix_op[4], int motion_x, int motion_y, int h)
Definition at line 100 of file wmv2.c.
Referenced by mpv_motion_internal().