FFmpeg: libavcodec/wmv2dec.c File Reference
wmv2dec.c File Reference
#include "avcodec.h"
#include "h263.h"
#include "internal.h"
#include "intrax8.h"
#include "mathops.h"
#include "mpegutils.h"
#include "mpegvideo.h"
#include "msmpeg4.h"
#include "msmpeg4data.h"
#include "wmv2.h"
Functions
static void parse_mb_skip (Wmv2Context *w)
static int decode_ext_header (Wmv2Context *w)
int ff_wmv2_decode_picture_header (MpegEncContext *s)
int ff_wmv2_decode_secondary_picture_header (MpegEncContext *s)
static int wmv2_decode_motion (Wmv2Context *w, int *mx_ptr, int *my_ptr)
static int16_t * wmv2_pred_motion (Wmv2Context *w, int *px, int *py)
static int wmv2_decode_inter_block (Wmv2Context *w, int16_t *block, int n, int cbp)
int ff_wmv2_decode_mb (MpegEncContext *s, int16_t block[6][64])
static av_cold int wmv2_decode_init (AVCodecContext *avctx)
static av_cold int wmv2_decode_end (AVCodecContext *avctx)
Variables
AVCodec ff_wmv2_decoder
Function Documentation
parse_mb_skip()
static void parse_mb_skip (Wmv2Context * w) static
Definition at line 33 of file wmv2dec.c.
Referenced by ff_wmv2_decode_secondary_picture_header().
decode_ext_header()
static int decode_ext_header (Wmv2Context * w) static
Definition at line 82 of file wmv2dec.c.
Referenced by ff_wmv2_decode_picture_header().
ff_wmv2_decode_picture_header()
int ff_wmv2_decode_picture_header (MpegEncContext * s)
Definition at line 120 of file wmv2dec.c.
Referenced by ff_h263_decode_frame().
ff_wmv2_decode_secondary_picture_header()
int ff_wmv2_decode_secondary_picture_header (MpegEncContext * s)
Definition at line 140 of file wmv2dec.c.
Referenced by ff_h263_decode_frame().
wmv2_decode_motion()
static int wmv2_decode_motion (Wmv2Context * w, int * mx_ptr, int * my_ptr) inline static
Definition at line 236 of file wmv2dec.c.
Referenced by ff_wmv2_decode_mb().
wmv2_pred_motion()
static int16_t* wmv2_pred_motion (Wmv2Context * w, int * px, int * py) static
Definition at line 254 of file wmv2dec.c.
Referenced by ff_wmv2_decode_mb().
wmv2_decode_inter_block()
static int wmv2_decode_inter_block (Wmv2Context * w, int16_t * block, int n, int cbp) inline static
Definition at line 299 of file wmv2dec.c.
Referenced by ff_wmv2_decode_mb().
ff_wmv2_decode_mb()
int ff_wmv2_decode_mb (MpegEncContext * s, int16_t block[6][64])
Definition at line 339 of file wmv2dec.c.
Referenced by ff_msmpeg4_decode_init().
wmv2_decode_init()
static av_cold int wmv2_decode_init (AVCodecContext * avctx) static
Definition at line 458 of file wmv2dec.c.
wmv2_decode_end()
static av_cold int wmv2_decode_end (AVCodecContext * avctx) static
Definition at line 477 of file wmv2dec.c.
Variable Documentation
ff_wmv2_decoder
AVCodec ff_wmv2_decoder
Initial value:
= {
    .name           = "wmv2",
    .long_name      = NULL_IF_CONFIG_SMALL("Windows Media Video 8"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_WMV2,
    .priv_data_size = sizeof(Wmv2Context),
    .init           = wmv2_decode_init,
    .close          = wmv2_decode_end,
    .decode         = ff_h263_decode_frame,
    .capabilities   = AV_CODEC_CAP_DRAW_HORIZ_BAND | AV_CODEC_CAP_DR1,
    .pix_fmts       = (const enum AVPixelFormat[]) { AV_PIX_FMT_YUV420P,
                                                     AV_PIX_FMT_NONE },
}
Definition at line 485 of file wmv2dec.c.