FFmpeg: libavcodec/wmv2dsp.h File Reference
wmv2dsp.h File Reference
#include <stdint.h>
#include "qpeldsp.h"
Data Structures
struct WMV2DSPContext
Functions
void ff_wmv2dsp_init (WMV2DSPContext *c)
void ff_wmv2dsp_init_mips (WMV2DSPContext *c)
Function Documentation
ff_wmv2dsp_init()
void ff_wmv2dsp_init (WMV2DSPContext * c)
Definition at line 251 of file wmv2dsp.c.
Referenced by ff_intrax8_common_init(), and ff_wmv2_common_init().
ff_wmv2dsp_init_mips()
void ff_wmv2dsp_init_mips (WMV2DSPContext * c)
Definition at line 33 of file wmv2dsp_init_mips.c.
Referenced by ff_wmv2dsp_init().