FFmpeg: libavcodec/wmv2dsp.c File Reference
wmv2dsp.c File Reference
#include "libavutil/attributes.h"
#include "libavutil/common.h"
#include "avcodec.h"
#include "idctdsp.h"
#include "mathops.h"
#include "wmv2dsp.h"
Macros
#define W0 2048
#define W1 2841 /* 2048*sqrt (2)*cos (1*pi/16) */
#define W2 2676 /* 2048*sqrt (2)*cos (2*pi/16) */
#define W3 2408 /* 2048*sqrt (2)*cos (3*pi/16) */
#define W4 2048 /* 2048*sqrt (2)*cos (4*pi/16) */
#define W5 1609 /* 2048*sqrt (2)*cos (5*pi/16) */
#define W6 1108 /* 2048*sqrt (2)*cos (6*pi/16) */
#define W7 565 /* 2048*sqrt (2)*cos (7*pi/16) */
Functions
static void wmv2_idct_row (short *b)
static void wmv2_idct_col (short *b)
static void wmv2_idct_add_c (uint8_t *dest, int line_size, int16_t *block)
static void wmv2_idct_put_c (uint8_t *dest, int line_size, int16_t *block)
static void wmv2_mspel8_h_lowpass (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride, int h)
static void wmv2_mspel8_v_lowpass (uint8_t *dst, const uint8_t *src, int dstStride, int srcStride, int w)
static void put_mspel8_mc10_c (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
static void put_mspel8_mc20_c (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
static void put_mspel8_mc30_c (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
static void put_mspel8_mc02_c (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
static void put_mspel8_mc12_c (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
static void put_mspel8_mc32_c (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
static void put_mspel8_mc22_c (uint8_t *dst, const uint8_t *src, ptrdiff_t stride)
av_cold void ff_wmv2dsp_init (WMV2DSPContext *c)
Macro Definition Documentation
W0
#define W0 2048
Definition at line 26 of file wmv2dsp.c.
Referenced by wmv2_idct_col(), and wmv2_idct_row().
W1
#define W1 2841 /* 2048*sqrt (2)*cos (1*pi/16) */
Definition at line 27 of file wmv2dsp.c.
Referenced by wmv2_idct_col(), and wmv2_idct_row().
W2
#define W2 2676 /* 2048*sqrt (2)*cos (2*pi/16) */
Definition at line 28 of file wmv2dsp.c.
Referenced by wmv2_idct_col(), and wmv2_idct_row().
W3
#define W3 2408 /* 2048*sqrt (2)*cos (3*pi/16) */
Definition at line 29 of file wmv2dsp.c.
Referenced by wmv2_idct_col(), and wmv2_idct_row().
W4
#define W4 2048 /* 2048*sqrt (2)*cos (4*pi/16) */
Definition at line 30 of file wmv2dsp.c.
W5
#define W5 1609 /* 2048*sqrt (2)*cos (5*pi/16) */
Definition at line 31 of file wmv2dsp.c.
Referenced by wmv2_idct_col(), and wmv2_idct_row().
W6
#define W6 1108 /* 2048*sqrt (2)*cos (6*pi/16) */
Definition at line 32 of file wmv2dsp.c.
Referenced by wmv2_idct_col(), and wmv2_idct_row().
W7
#define W7 565 /* 2048*sqrt (2)*cos (7*pi/16) */
Definition at line 33 of file wmv2dsp.c.
Referenced by wmv2_idct_col(), and wmv2_idct_row().
Function Documentation
wmv2_idct_row()
static void wmv2_idct_row (short * b) static
Definition at line 35 of file wmv2dsp.c.
Referenced by wmv2_idct_add_c(), and wmv2_idct_put_c().
wmv2_idct_col()
static void wmv2_idct_col (short * b) static
Definition at line 65 of file wmv2dsp.c.
Referenced by wmv2_idct_add_c(), and wmv2_idct_put_c().
wmv2_idct_add_c()
static void wmv2_idct_add_c (uint8_t * dest, int line_size, int16_t * block) static
Definition at line 96 of file wmv2dsp.c.
Referenced by ff_wmv2dsp_init().
wmv2_idct_put_c()
static void wmv2_idct_put_c (uint8_t * dest, int line_size, int16_t * block) static
Definition at line 119 of file wmv2dsp.c.
Referenced by ff_wmv2dsp_init().
wmv2_mspel8_h_lowpass()
static void wmv2_mspel8_h_lowpass (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride, int h) static
Definition at line 142 of file wmv2dsp.c.
Referenced by put_mspel8_mc10_c(), put_mspel8_mc12_c(), put_mspel8_mc20_c(), put_mspel8_mc22_c(), put_mspel8_mc30_c(), and put_mspel8_mc32_c().
wmv2_mspel8_v_lowpass()
static void wmv2_mspel8_v_lowpass (uint8_t * dst, const uint8_t * src, int dstStride, int srcStride, int w) static
Definition at line 162 of file wmv2dsp.c.
Referenced by put_mspel8_mc02_c(), put_mspel8_mc12_c(), put_mspel8_mc22_c(), and put_mspel8_mc32_c().
put_mspel8_mc10_c()
static void put_mspel8_mc10_c (uint8_t * dst, const uint8_t * src, ptrdiff_t stride) static
Definition at line 193 of file wmv2dsp.c.
Referenced by ff_wmv2dsp_init().
put_mspel8_mc20_c()
static void put_mspel8_mc20_c (uint8_t * dst, const uint8_t * src, ptrdiff_t stride) static
Definition at line 201 of file wmv2dsp.c.
Referenced by ff_wmv2dsp_init().
put_mspel8_mc30_c()
static void put_mspel8_mc30_c (uint8_t * dst, const uint8_t * src, ptrdiff_t stride) static
Definition at line 206 of file wmv2dsp.c.
Referenced by ff_wmv2dsp_init().
put_mspel8_mc02_c()
static void put_mspel8_mc02_c (uint8_t * dst, const uint8_t * src, ptrdiff_t stride) static
Definition at line 214 of file wmv2dsp.c.
Referenced by ff_wmv2dsp_init().
put_mspel8_mc12_c()
static void put_mspel8_mc12_c (uint8_t * dst, const uint8_t * src, ptrdiff_t stride) static
Definition at line 219 of file wmv2dsp.c.
Referenced by ff_wmv2dsp_init().
put_mspel8_mc32_c()
static void put_mspel8_mc32_c (uint8_t * dst, const uint8_t * src, ptrdiff_t stride) static
Definition at line 231 of file wmv2dsp.c.
Referenced by ff_wmv2dsp_init().
put_mspel8_mc22_c()
static void put_mspel8_mc22_c (uint8_t * dst, const uint8_t * src, ptrdiff_t stride) static
Definition at line 243 of file wmv2dsp.c.
Referenced by ff_wmv2dsp_init().
ff_wmv2dsp_init()
av_cold void ff_wmv2dsp_init (WMV2DSPContext * c)
Definition at line 251 of file wmv2dsp.c.
Referenced by ff_intrax8_common_init(), and ff_wmv2_common_init().