FFmpeg: libavformat/wsddec.c File Reference
wsddec.c File Reference
#include "libavutil/intreadwrite.h"
#include "libavutil/timecode.h"
#include "avformat.h"
#include "internal.h"
#include "rawdec.h"
Functions
static int wsd_probe (AVProbeData *p)
static int empty_string (const char *buf, unsigned size)
static int wsd_to_av_channel_layoyt (AVFormatContext *s, int bit)
static int get_metadata (AVFormatContext *s, const char *const tag, const unsigned size)
static int wsd_read_header (AVFormatContext *s)
Variables
AVInputFormat ff_wsd_demuxer
Function Documentation
wsd_probe()
static int wsd_probe (AVProbeData * p) static
Definition at line 28 of file wsddec.c.
empty_string()
static int empty_string (const char * buf, unsigned size) static
Definition at line 37 of file wsddec.c.
Referenced by get_metadata().
wsd_to_av_channel_layoyt()
static int wsd_to_av_channel_layoyt (AVFormatContext * s, int bit) static
Definition at line 46 of file wsddec.c.
Referenced by wsd_read_header().
get_metadata()
static int get_metadata (AVFormatContext * s, const char *const tag, const unsigned size) static
Definition at line 71 of file wsddec.c.
Referenced by wsd_read_header().
wsd_read_header()
static int wsd_read_header (AVFormatContext * s) static
Definition at line 96 of file wsddec.c.
Variable Documentation
ff_wsd_demuxer
AVInputFormat ff_wsd_demuxer
Initial value:
= {
    .name         = "wsd",
    .long_name    = NULL_IF_CONFIG_SMALL("Wideband Single-bit Data (WSD)"),
    .read_probe   = wsd_probe,
    .read_header  = wsd_read_header,
    .read_packet  = ff_raw_read_partial_packet,
    .extensions   = "wsd",
    .flags        = AVFMT_GENERIC_INDEX | AVFMT_NO_BYTE_SEEK,
    .raw_codec_id = AV_CODEC_ID_DSD_MSBF,
}
Definition at line 164 of file wsddec.c.