FFmpeg: libavformat/wv.h File Reference
wv.h File Reference
#include <stdint.h>
Data Structures
struct WvHeader
Macros
#define WV_HEADER_SIZE 32
#define WV_FLAG_INITIAL_BLOCK (1 << 11)
#define WV_FLAG_FINAL_BLOCK (1 << 12)
#define WV_BLOCK_LIMIT 1048576
Functions
int ff_wv_parse_header (WvHeader *wv, const uint8_t *data)
Parse a WavPack block header.
Macro Definition Documentation
WV_HEADER_SIZE
#define WV_HEADER_SIZE 32
Definition at line 26 of file wv.h.
WV_FLAG_INITIAL_BLOCK
#define WV_FLAG_INITIAL_BLOCK (1 << 11)
Definition at line 28 of file wv.h.
Referenced by ff_wv_parse_header().
WV_FLAG_FINAL_BLOCK
#define WV_FLAG_FINAL_BLOCK (1 << 12)
Definition at line 29 of file wv.h.
Referenced by ff_wv_parse_header(), and wv_read_packet().
WV_BLOCK_LIMIT
#define WV_BLOCK_LIMIT 1048576
Definition at line 32 of file wv.h.
Referenced by ff_wv_parse_header(), and wv_probe().
Function Documentation
ff_wv_parse_header()
int ff_wv_parse_header (WvHeader * wv, const uint8_t * data)
Parse a WavPack block header.
Parameters
wv this struct will be filled with parse header information
data header data, must be WV_HEADER_SIZE bytes long
Returns
0 on success, a negative AVERROR code on failure
Definition at line 29 of file wv.c.
Referenced by mkv_strip_wavpack(), wv_read_block_header(), and wv_write_packet().