FFmpeg: libavformat/wv.c File Reference
wv.c File Reference
#include <stdint.h>
#include <string.h>
#include "libavutil/common.h"
#include "libavutil/intreadwrite.h"
#include "wv.h"
Functions
int ff_wv_parse_header (WvHeader *wv, const uint8_t *data)
Parse a WavPack block header.
Function Documentation
ff_wv_parse_header()
int ff_wv_parse_header (WvHeader * wv, const uint8_t * data)
Parse a WavPack block header.
Parameters
wv this struct will be filled with parse header information
data header data, must be WV_HEADER_SIZE bytes long
Returns
0 on success, a negative AVERROR code on failure
Definition at line 29 of file wv.c.
Referenced by mkv_strip_wavpack(), wv_read_block_header(), and wv_write_packet().