FFmpeg: libavdevice/x11grab.c File Reference
x11grab.c File Reference
X11 frame device demuxer.
#include "config.h"
#include <time.h>
#include <sys/shm.h>
#include <X11/cursorfont.h>
#include <X11/X.h>
#include <X11/Xlib.h>
#include <X11/Xlibint.h>
#include <X11/Xproto.h>
#include <X11/Xutil.h>
#include <X11/extensions/shape.h>
#include <X11/extensions/Xfixes.h>
#include <X11/extensions/XShm.h>
#include "libavutil/internal.h"
#include "libavutil/log.h"
#include "libavutil/opt.h"
#include "libavutil/parseutils.h"
#include "libavformat/internal.h"
#include "avdevice.h"
Data Structures
struct X11GrabContext
X11 device demuxer context.
Macros
#define REGION_WIN_BORDER 3
#define OFFSET(x) offsetof(X11GrabContext, x)
#define DEC AV_OPT_FLAG_DECODING_PARAM
Functions
static void x11grab_draw_region_win (X11GrabContext *s)
Draw grabbing region window.
static void x11grab_region_win_init (X11GrabContext *s)
Initialize grabbing region window.
static int setup_shm (AVFormatContext *s, Display *dpy, XImage **image)
static int setup_mouse (Display *dpy, int screen)
static int pixfmt_from_image (AVFormatContext *s, XImage *image, int *pix_fmt)
static int x11grab_read_header (AVFormatContext *s1)
Initialize the x11 grab device demuxer (public device demuxer API).
static void paint_mouse_pointer (XImage *image, AVFormatContext *s1)
Paint a mouse pointer in an X11 image.
static int xget_zpixmap (Display *dpy, Drawable d, XImage *image, int x, int y)
Read new data in the image structure.
static int x11grab_read_packet (AVFormatContext *s1, AVPacket *pkt)
Grab a frame from x11 (public device demuxer API).
static int x11grab_read_close (AVFormatContext *s1)
Close x11 frame grabber (public device demuxer API).
Variables
static const AVOption options []
static const AVClass x11_class
AVInputFormat ff_x11grab_demuxer
x11 grabber device demuxer declaration
Detailed Description
X11 frame device demuxer.
Author
Clemens Fruhwirth cleme.nosp@m.ns@e.nosp@m.ndorp.nosp@m.hin..nosp@m.org
Edouard Gomez ed.go.nosp@m.mez@.nosp@m.free..nosp@m.fr
Definition in file x11grab.c.
Macro Definition Documentation
REGION_WIN_BORDER
#define REGION_WIN_BORDER 3
Definition at line 92 of file x11grab.c.
Referenced by x11grab_draw_region_win(), x11grab_read_packet(), and x11grab_region_win_init().
OFFSET
#define OFFSET (x) offsetof(X11GrabContext, x)
Definition at line 658 of file x11grab.c.
DEC
#define DEC AV_OPT_FLAG_DECODING_PARAM
Definition at line 659 of file x11grab.c.
Function Documentation
x11grab_draw_region_win()
static void x11grab_draw_region_win (X11GrabContext * s) static
Draw grabbing region window.
Parameters
s x11grab context
Definition at line 99 of file x11grab.c.
Referenced by x11grab_read_packet(), and x11grab_region_win_init().
x11grab_region_win_init()
static void x11grab_region_win_init (X11GrabContext * s) static
Initialize grabbing region window.
Parameters
s x11grab context
Definition at line 120 of file x11grab.c.
Referenced by x11grab_read_packet().
setup_shm()
static int setup_shm (AVFormatContext * s, Display * dpy, XImage ** image) static
Definition at line 147 of file x11grab.c.
Referenced by x11grab_read_header().
setup_mouse()
static int setup_mouse (Display * dpy, int screen) static
Definition at line 176 of file x11grab.c.
Referenced by x11grab_read_header().
pixfmt_from_image()
static int pixfmt_from_image (AVFormatContext * s, XImage * image, int * pix_fmt) static
Definition at line 189 of file x11grab.c.
Referenced by x11grab_read_header().
x11grab_read_header()
static int x11grab_read_header (AVFormatContext * s1) static
Initialize the x11 grab device demuxer (public device demuxer API).
Parameters
s1 Context from avformat core
Returns
AVERROR(ENOMEM) no memory left
AVERROR(EIO) other failure case
0 success
Definition at line 259 of file x11grab.c.
paint_mouse_pointer()
static void paint_mouse_pointer (XImage * image, AVFormatContext * s1) static
Paint a mouse pointer in an X11 image.
Parameters
image image to paint the mouse pointer to
s context used to retrieve original grabbing rectangle coordinates
Definition at line 395 of file x11grab.c.
Referenced by x11grab_read_packet().
xget_zpixmap()
static int xget_zpixmap (Display * dpy, Drawable d, XImage * image, int x, int y) static
Read new data in the image structure.
Parameters
dpy X11 display to grab from
d
image Image where the grab will be put
x Top-Left grabbing rectangle horizontal coordinate
y Top-Left grabbing rectangle vertical coordinate
Returns
0 if error, !0 if successful
Definition at line 475 of file x11grab.c.
Referenced by x11grab_read_packet().
x11grab_read_packet()
static int x11grab_read_packet (AVFormatContext * s1, AVPacket * pkt) static
Grab a frame from x11 (public device demuxer API).
Parameters
s1 Context from avformat core
pkt Packet holding the brabbed frame
Returns
frame size in bytes
Definition at line 517 of file x11grab.c.
x11grab_read_close()
static int x11grab_read_close (AVFormatContext * s1) static
Close x11 frame grabber (public device demuxer API).
Parameters
s1 Context from avformat core
Returns
0 success, !0 failure
Definition at line 633 of file x11grab.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "grab_x", "Initial x coordinate.", OFFSET(x_off), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, INT_MAX, DEC },
    { "grab_y", "Initial y coordinate.", OFFSET(y_off), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, INT_MAX, DEC },
    { "draw_mouse", "draw the mouse pointer", OFFSET(draw_mouse), AV_OPT_TYPE_INT, {.i64 = 1}, 0, 1, DEC },
    { "follow_mouse", "move the grabbing region when the mouse pointer reaches within specified amount of pixels to the edge of region",
      OFFSET(follow_mouse), AV_OPT_TYPE_INT, {.i64 = 0}, -1, INT_MAX, DEC, "follow_mouse" },
    { "centered",     "keep the mouse pointer at the center of grabbing region when following",
      0, AV_OPT_TYPE_CONST, {.i64 = -1}, INT_MIN, INT_MAX, DEC, "follow_mouse" },
    { "framerate",  "set video frame rate",      OFFSET(framerate),   AV_OPT_TYPE_VIDEO_RATE, {.str = "ntsc"}, 0, INT_MAX, DEC },
    { "show_region", "show the grabbing region", OFFSET(show_region), AV_OPT_TYPE_INT,        {.i64 = 0}, 0, 1, DEC },
    { "video_size",  "set video frame size",     OFFSET(width),       AV_OPT_TYPE_IMAGE_SIZE, {.str = "vga"}, 0, 0, DEC },
    { "use_shm",     "use MIT-SHM extension",    OFFSET(use_shm),     AV_OPT_TYPE_INT,        {.i64 = 1}, 0, 1, DEC },
    { NULL },
}
Definition at line 660 of file x11grab.c.
x11_class
const AVClass x11_class static
Initial value:
= {
    .class_name = "X11grab indev",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
    .category   = AV_CLASS_CATEGORY_DEVICE_VIDEO_INPUT,
}
Definition at line 677 of file x11grab.c.
ff_x11grab_demuxer
AVInputFormat ff_x11grab_demuxer
Initial value:
= {
    .name           = "x11grab",
    .long_name      = NULL_IF_CONFIG_SMALL("X11grab"),
    .priv_data_size = sizeof(X11GrabContext),
    .read_header    = x11grab_read_header,
    .read_packet    = x11grab_read_packet,
    .read_close     = x11grab_read_close,
    .flags          = AVFMT_NOFILE,
    .priv_class     = &x11_class,
}
x11 grabber device demuxer declaration
Definition at line 686 of file x11grab.c.