FFmpeg: libavcodec/x86/simple_idct.h File Reference
simple_idct.h File Reference
#include <stdint.h>
Functions
void ff_simple_idct_mmx (int16_t *block)
void ff_simple_idct_add_mmx (uint8_t *dest, int line_size, int16_t *block)
void ff_simple_idct_put_mmx (uint8_t *dest, int line_size, int16_t *block)
void ff_simple_idct10_sse2 (int16_t *block)
void ff_simple_idct10_avx (int16_t *block)
void ff_simple_idct10_put_sse2 (uint8_t *dest, int line_size, int16_t *block)
void ff_simple_idct10_put_avx (uint8_t *dest, int line_size, int16_t *block)
void ff_simple_idct12_sse2 (int16_t *block)
void ff_simple_idct12_avx (int16_t *block)
void ff_simple_idct12_put_sse2 (uint8_t *dest, int line_size, int16_t *block)
void ff_simple_idct12_put_avx (uint8_t *dest, int line_size, int16_t *block)
Function Documentation
ff_simple_idct_mmx()
void ff_simple_idct_mmx (int16_t * block)
Referenced by ff_idctdsp_init_x86().
ff_simple_idct_add_mmx()
void ff_simple_idct_add_mmx (uint8_t * dest, int line_size, int16_t * block)
Referenced by ff_idctdsp_init_x86().
ff_simple_idct_put_mmx()
void ff_simple_idct_put_mmx (uint8_t * dest, int line_size, int16_t * block)
Referenced by ff_idctdsp_init_x86().
ff_simple_idct10_sse2()
void ff_simple_idct10_sse2 (int16_t * block)
Referenced by ff_idctdsp_init_x86().
ff_simple_idct10_avx()
void ff_simple_idct10_avx (int16_t * block)
Referenced by ff_idctdsp_init_x86().
ff_simple_idct10_put_sse2()
void ff_simple_idct10_put_sse2 (uint8_t * dest, int line_size, int16_t * block)
Referenced by ff_idctdsp_init_x86().
ff_simple_idct10_put_avx()
void ff_simple_idct10_put_avx (uint8_t * dest, int line_size, int16_t * block)
Referenced by ff_idctdsp_init_x86().
ff_simple_idct12_sse2()
void ff_simple_idct12_sse2 (int16_t * block)
Referenced by ff_idctdsp_init_x86().
ff_simple_idct12_avx()
void ff_simple_idct12_avx (int16_t * block)
Referenced by ff_idctdsp_init_x86().
ff_simple_idct12_put_sse2()
void ff_simple_idct12_put_sse2 (uint8_t * dest, int line_size, int16_t * block)
Referenced by ff_idctdsp_init_x86().
ff_simple_idct12_put_avx()
void ff_simple_idct12_put_avx (uint8_t * dest, int line_size, int16_t * block)
Referenced by ff_idctdsp_init_x86().