FFmpeg: libavcodec/x86/vorbisdsp_init.c File Reference
vorbisdsp_init.c File Reference
#include "config.h"
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/x86/cpu.h"
#include "libavcodec/vorbisdsp.h"
Functions
void ff_vorbis_inverse_coupling_3dnow (float *mag, float *ang, intptr_t blocksize)
void ff_vorbis_inverse_coupling_sse (float *mag, float *ang, intptr_t blocksize)
av_cold void ff_vorbisdsp_init_x86 (VorbisDSPContext *dsp)
Function Documentation
ff_vorbis_inverse_coupling_3dnow()
void ff_vorbis_inverse_coupling_3dnow (float * mag, float * ang, intptr_t blocksize)
Referenced by ff_vorbisdsp_init_x86().
ff_vorbis_inverse_coupling_sse()
void ff_vorbis_inverse_coupling_sse (float * mag, float * ang, intptr_t blocksize)
Referenced by ff_vorbisdsp_init_x86().
ff_vorbisdsp_init_x86()
av_cold void ff_vorbisdsp_init_x86 (VorbisDSPContext * dsp)
Definition at line 32 of file vorbisdsp_init.c.
Referenced by ff_vorbisdsp_init().