FFmpeg: libavcodec/x86/xvididct.h File Reference
xvididct.h File Reference
header for Xvid IDCT functions
#include <stdint.h>
Functions
void ff_xvid_idct_mmx (short *block)
void ff_xvid_idct_mmx_put (uint8_t *dest, int line_size, int16_t *block)
void ff_xvid_idct_mmx_add (uint8_t *dest, int line_size, int16_t *block)
void ff_xvid_idct_mmxext (short *block)
void ff_xvid_idct_mmxext_put (uint8_t *dest, int line_size, int16_t *block)
void ff_xvid_idct_mmxext_add (uint8_t *dest, int line_size, int16_t *block)
void ff_xvid_idct_sse2 (short *block)
void ff_xvid_idct_put_sse2 (uint8_t *dest, int line_size, short *block)
void ff_xvid_idct_add_sse2 (uint8_t *dest, int line_size, short *block)
Detailed Description
header for Xvid IDCT functions
Definition in file xvididct.h.
Function Documentation
ff_xvid_idct_mmx()
void ff_xvid_idct_mmx (short * block)
Referenced by ff_xvid_idct_init_x86().
ff_xvid_idct_mmx_put()
void ff_xvid_idct_mmx_put (uint8_t * dest, int line_size, int16_t * block)
ff_xvid_idct_mmx_add()
void ff_xvid_idct_mmx_add (uint8_t * dest, int line_size, int16_t * block)
ff_xvid_idct_mmxext()
void ff_xvid_idct_mmxext (short * block)
Referenced by ff_xvid_idct_init_x86().
ff_xvid_idct_mmxext_put()
void ff_xvid_idct_mmxext_put (uint8_t * dest, int line_size, int16_t * block)
ff_xvid_idct_mmxext_add()
void ff_xvid_idct_mmxext_add (uint8_t * dest, int line_size, int16_t * block)
ff_xvid_idct_sse2()
void ff_xvid_idct_sse2 (short * block)
Referenced by ff_xvid_idct_init_x86().
ff_xvid_idct_put_sse2()
void ff_xvid_idct_put_sse2 (uint8_t * dest, int line_size, short * block)
Referenced by ff_xvid_idct_init_x86().
ff_xvid_idct_add_sse2()
void ff_xvid_idct_add_sse2 (uint8_t * dest, int line_size, short * block)
Referenced by ff_xvid_idct_init_x86().