FFmpeg: libavcodec/x86/fft.h File Reference
fft.h File Reference
#include "libavcodec/fft.h"
Functions
void ff_fft_permute_sse (FFTContext *s, FFTComplex *z)
void ff_fft_calc_avx (FFTContext *s, FFTComplex *z)
void ff_fft_calc_sse (FFTContext *s, FFTComplex *z)
void ff_fft_calc_3dnow (FFTContext *s, FFTComplex *z)
void ff_fft_calc_3dnowext (FFTContext *s, FFTComplex *z)
void ff_imdct_calc_3dnow (FFTContext *s, FFTSample *output, const FFTSample *input)
void ff_imdct_half_3dnow (FFTContext *s, FFTSample *output, const FFTSample *input)
void ff_imdct_calc_3dnowext (FFTContext *s, FFTSample *output, const FFTSample *input)
void ff_imdct_half_3dnowext (FFTContext *s, FFTSample *output, const FFTSample *input)
void ff_imdct_calc_sse (FFTContext *s, FFTSample *output, const FFTSample *input)
void ff_imdct_half_sse (FFTContext *s, FFTSample *output, const FFTSample *input)
void ff_imdct_half_avx (FFTContext *s, FFTSample *output, const FFTSample *input)
Function Documentation
ff_fft_permute_sse()
void ff_fft_permute_sse (FFTContext * s, FFTComplex * z)
Referenced by ff_fft_init_x86().
ff_fft_calc_avx()
void ff_fft_calc_avx (FFTContext * s, FFTComplex * z)
Referenced by ff_fft_init_x86().
ff_fft_calc_sse()
void ff_fft_calc_sse (FFTContext * s, FFTComplex * z)
Referenced by ff_fft_init_x86().
ff_fft_calc_3dnow()
void ff_fft_calc_3dnow (FFTContext * s, FFTComplex * z)
Referenced by ff_fft_init_x86().
ff_fft_calc_3dnowext()
void ff_fft_calc_3dnowext (FFTContext * s, FFTComplex * z)
Referenced by ff_fft_init_x86().
ff_imdct_calc_3dnow()
void ff_imdct_calc_3dnow (FFTContext * s, FFTSample * output, const FFTSample * input)
Referenced by ff_fft_init_x86().
ff_imdct_half_3dnow()
void ff_imdct_half_3dnow (FFTContext * s, FFTSample * output, const FFTSample * input)
Referenced by ff_fft_init_x86().
ff_imdct_calc_3dnowext()
void ff_imdct_calc_3dnowext (FFTContext * s, FFTSample * output, const FFTSample * input)
Referenced by ff_fft_init_x86().
ff_imdct_half_3dnowext()
void ff_imdct_half_3dnowext (FFTContext * s, FFTSample * output, const FFTSample * input)
Referenced by ff_fft_init_x86().
ff_imdct_calc_sse()
void ff_imdct_calc_sse (FFTContext * s, FFTSample * output, const FFTSample * input)
Referenced by ff_fft_init_x86().
ff_imdct_half_sse()
void ff_imdct_half_sse (FFTContext * s, FFTSample * output, const FFTSample * input)
Referenced by ff_fft_init_x86().
ff_imdct_half_avx()
void ff_imdct_half_avx (FFTContext * s, FFTSample * output, const FFTSample * input)
Referenced by ff_fft_init_x86().