FFmpeg: libavcodec/x86/videodsp_init.c File Reference
videodsp_init.c File Reference
#include "config.h"
#include "libavutil/attributes.h"
#include "libavutil/avassert.h"
#include "libavutil/common.h"
#include "libavutil/cpu.h"
#include "libavutil/mem.h"
#include "libavutil/x86/asm.h"
#include "libavutil/x86/cpu.h"
#include "libavcodec/videodsp.h"
Functions
void ff_prefetch_mmxext (uint8_t *buf, ptrdiff_t stride, int h)
void ff_prefetch_3dnow (uint8_t *buf, ptrdiff_t stride, int h)
av_cold void ff_videodsp_init_x86 (VideoDSPContext *ctx, int bpc)
Function Documentation
ff_prefetch_mmxext()
void ff_prefetch_mmxext (uint8_t * buf, ptrdiff_t stride, int h)
Referenced by ff_videodsp_init_x86().
ff_prefetch_3dnow()
void ff_prefetch_3dnow (uint8_t * buf, ptrdiff_t stride, int h)
Referenced by ff_videodsp_init_x86().
ff_videodsp_init_x86()
av_cold void ff_videodsp_init_x86 (VideoDSPContext * ctx, int bpc)
Definition at line 279 of file videodsp_init.c.
Referenced by ff_videodsp_init().