FFmpeg: libavcodec/x86/idctdsp.h File Reference
idctdsp.h File Reference
#include <stdint.h>
#include <stddef.h>
Functions
void ff_add_pixels_clamped_mmx (const int16_t *block, uint8_t *pixels, ptrdiff_t line_size)
void ff_add_pixels_clamped_sse2 (const int16_t *block, uint8_t *pixels, ptrdiff_t line_size)
void ff_put_pixels_clamped_mmx (const int16_t *block, uint8_t *pixels, ptrdiff_t line_size)
void ff_put_pixels_clamped_sse2 (const int16_t *block, uint8_t *pixels, ptrdiff_t line_size)
void ff_put_signed_pixels_clamped_mmx (const int16_t *block, uint8_t *pixels, ptrdiff_t line_size)
void ff_put_signed_pixels_clamped_sse2 (const int16_t *block, uint8_t *pixels, ptrdiff_t line_size)
Function Documentation
ff_add_pixels_clamped_mmx()
void ff_add_pixels_clamped_mmx (const int16_t * block, uint8_t * pixels, ptrdiff_t line_size)
Referenced by ff_idctdsp_init_x86().
ff_add_pixels_clamped_sse2()
void ff_add_pixels_clamped_sse2 (const int16_t * block, uint8_t * pixels, ptrdiff_t line_size)
Referenced by ff_idctdsp_init_x86().
ff_put_pixels_clamped_mmx()
void ff_put_pixels_clamped_mmx (const int16_t * block, uint8_t * pixels, ptrdiff_t line_size)
Referenced by ff_idctdsp_init_x86().
ff_put_pixels_clamped_sse2()
void ff_put_pixels_clamped_sse2 (const int16_t * block, uint8_t * pixels, ptrdiff_t line_size)
Referenced by ff_idctdsp_init_x86().
ff_put_signed_pixels_clamped_mmx()
void ff_put_signed_pixels_clamped_mmx (const int16_t * block, uint8_t * pixels, ptrdiff_t line_size)
Referenced by ff_idctdsp_init_x86().
ff_put_signed_pixels_clamped_sse2()
void ff_put_signed_pixels_clamped_sse2 (const int16_t * block, uint8_t * pixels, ptrdiff_t line_size)
Referenced by ff_idctdsp_init_x86().