FFmpeg: libavcodec/x86/hevcdsp.h File Reference
hevcdsp.h File Reference
#include <stddef.h>
#include <stdint.h>
Macros
#define idct_dc_proto(size, bitd, opt) void ff_hevc_idct##size##_dc_add_##bitd##_##opt(uint8_t *dst, int16_t *coeffs, ptrdiff_t stride)
#define PEL_LINK(dst, idx1, idx2, idx3, name, D, opt)
#define PEL_PROTOTYPE(name, D, opt)
#define EPEL_PROTOTYPES(fname, bitd, opt)
#define QPEL_PROTOTYPES(fname, bitd, opt)
#define WEIGHTING_PROTOTYPE(width, bitd, opt)
#define WEIGHTING_PROTOTYPES(bitd, opt)
Functions
EPEL_PROTOTYPES (pel_pixels, 8, sse4)
EPEL_PROTOTYPES (pel_pixels, 10, sse4)
EPEL_PROTOTYPES (pel_pixels, 12, sse4)
void ff_hevc_put_hevc_pel_pixels16_8_avx2 (int16_t *dst, uint8_t *_src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_pel_pixels24_8_avx2 (int16_t *dst, uint8_t *_src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_pel_pixels32_8_avx2 (int16_t *dst, uint8_t *_src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_pel_pixels48_8_avx2 (int16_t *dst, uint8_t *_src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_pel_pixels64_8_avx2 (int16_t *dst, uint8_t *_src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_pel_pixels16_10_avx2 (int16_t *dst, uint8_t *_src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_pel_pixels24_10_avx2 (int16_t *dst, uint8_t *_src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_pel_pixels32_10_avx2 (int16_t *dst, uint8_t *_src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_pel_pixels48_10_avx2 (int16_t *dst, uint8_t *_src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_pel_pixels64_10_avx2 (int16_t *dst, uint8_t *_src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_uni_pel_pixels32_8_avx2 (uint8_t *dst, ptrdiff_t dststride, uint8_t *_src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_uni_pel_pixels48_8_avx2 (uint8_t *dst, ptrdiff_t dststride, uint8_t *_src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_uni_pel_pixels64_8_avx2 (uint8_t *dst, ptrdiff_t dststride, uint8_t *_src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_uni_pel_pixels96_8_avx2 (uint8_t *dst, ptrdiff_t dststride, uint8_t *_src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_uni_pel_pixels128_8_avx2 (uint8_t *dst, ptrdiff_t dststride, uint8_t *_src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_bi_pel_pixels16_8_avx2 (uint8_t *_dst, ptrdiff_t _dststride, uint8_t *_src, ptrdiff_t _srcstride, int16_t *src2, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_bi_pel_pixels24_8_avx2 (uint8_t *_dst, ptrdiff_t _dststride, uint8_t *_src, ptrdiff_t _srcstride, int16_t *src2, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_bi_pel_pixels32_8_avx2 (uint8_t *_dst, ptrdiff_t _dststride, uint8_t *_src, ptrdiff_t _srcstride, int16_t *src2, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_bi_pel_pixels48_8_avx2 (uint8_t *_dst, ptrdiff_t _dststride, uint8_t *_src, ptrdiff_t _srcstride, int16_t *src2, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_bi_pel_pixels64_8_avx2 (uint8_t *_dst, ptrdiff_t _dststride, uint8_t *_src, ptrdiff_t _srcstride, int16_t *src2, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_bi_pel_pixels16_10_avx2 (uint8_t *_dst, ptrdiff_t _dststride, uint8_t *_src, ptrdiff_t _srcstride, int16_t *src2, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_bi_pel_pixels24_10_avx2 (uint8_t *_dst, ptrdiff_t _dststride, uint8_t *_src, ptrdiff_t _srcstride, int16_t *src2, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_bi_pel_pixels32_10_avx2 (uint8_t *_dst, ptrdiff_t _dststride, uint8_t *_src, ptrdiff_t _srcstride, int16_t *src2, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_bi_pel_pixels48_10_avx2 (uint8_t *_dst, ptrdiff_t _dststride, uint8_t *_src, ptrdiff_t _srcstride, int16_t *src2, int height, intptr_t mx, intptr_t my, int width)
void ff_hevc_put_hevc_bi_pel_pixels64_10_avx2 (uint8_t *_dst, ptrdiff_t _dststride, uint8_t *_src, ptrdiff_t _srcstride, int16_t *src2, int height, intptr_t mx, intptr_t my, int width)
EPEL_PROTOTYPES (epel_h, 8, sse4)
EPEL_PROTOTYPES (epel_h, 10, sse4)
EPEL_PROTOTYPES (epel_h, 12, sse4)
EPEL_PROTOTYPES (epel_v, 8, sse4)
EPEL_PROTOTYPES (epel_v, 10, sse4)
EPEL_PROTOTYPES (epel_v, 12, sse4)
EPEL_PROTOTYPES (epel_hv, 8, sse4)
EPEL_PROTOTYPES (epel_hv, 10, sse4)
EPEL_PROTOTYPES (epel_hv, 12, sse4)
PEL_PROTOTYPE (epel_h16, 8, avx2)
PEL_PROTOTYPE (epel_h24, 8, avx2)
PEL_PROTOTYPE (epel_h32, 8, avx2)
PEL_PROTOTYPE (epel_h48, 8, avx2)
PEL_PROTOTYPE (epel_h64, 8, avx2)
PEL_PROTOTYPE (epel_h16, 10, avx2)
PEL_PROTOTYPE (epel_h24, 10, avx2)
PEL_PROTOTYPE (epel_h32, 10, avx2)
PEL_PROTOTYPE (epel_h48, 10, avx2)
PEL_PROTOTYPE (epel_h64, 10, avx2)
PEL_PROTOTYPE (epel_v16, 8, avx2)
PEL_PROTOTYPE (epel_v24, 8, avx2)
PEL_PROTOTYPE (epel_v32, 8, avx2)
PEL_PROTOTYPE (epel_v48, 8, avx2)
PEL_PROTOTYPE (epel_v64, 8, avx2)
PEL_PROTOTYPE (epel_v16, 10, avx2)
PEL_PROTOTYPE (epel_v24, 10, avx2)
PEL_PROTOTYPE (epel_v32, 10, avx2)
PEL_PROTOTYPE (epel_v48, 10, avx2)
PEL_PROTOTYPE (epel_v64, 10, avx2)
PEL_PROTOTYPE (epel_hv16, 8, avx2)
PEL_PROTOTYPE (epel_hv24, 8, avx2)
PEL_PROTOTYPE (epel_hv32, 8, avx2)
PEL_PROTOTYPE (epel_hv48, 8, avx2)
PEL_PROTOTYPE (epel_hv64, 8, avx2)
PEL_PROTOTYPE (epel_hv16, 10, avx2)
PEL_PROTOTYPE (epel_hv24, 10, avx2)
PEL_PROTOTYPE (epel_hv32, 10, avx2)
PEL_PROTOTYPE (epel_hv48, 10, avx2)
PEL_PROTOTYPE (epel_hv64, 10, avx2)
QPEL_PROTOTYPES (qpel_h, 8, sse4)
QPEL_PROTOTYPES (qpel_h, 10, sse4)
QPEL_PROTOTYPES (qpel_h, 12, sse4)
QPEL_PROTOTYPES (qpel_v, 8, sse4)
QPEL_PROTOTYPES (qpel_v, 10, sse4)
QPEL_PROTOTYPES (qpel_v, 12, sse4)
QPEL_PROTOTYPES (qpel_hv, 8, sse4)
QPEL_PROTOTYPES (qpel_hv, 10, sse4)
QPEL_PROTOTYPES (qpel_hv, 12, sse4)
PEL_PROTOTYPE (qpel_h16, 8, avx2)
PEL_PROTOTYPE (qpel_h24, 8, avx2)
PEL_PROTOTYPE (qpel_h32, 8, avx2)
PEL_PROTOTYPE (qpel_h48, 8, avx2)
PEL_PROTOTYPE (qpel_h64, 8, avx2)
PEL_PROTOTYPE (qpel_h16, 10, avx2)
PEL_PROTOTYPE (qpel_h24, 10, avx2)
PEL_PROTOTYPE (qpel_h32, 10, avx2)
PEL_PROTOTYPE (qpel_h48, 10, avx2)
PEL_PROTOTYPE (qpel_h64, 10, avx2)
PEL_PROTOTYPE (qpel_v16, 8, avx2)
PEL_PROTOTYPE (qpel_v24, 8, avx2)
PEL_PROTOTYPE (qpel_v32, 8, avx2)
PEL_PROTOTYPE (qpel_v48, 8, avx2)
PEL_PROTOTYPE (qpel_v64, 8, avx2)
PEL_PROTOTYPE (qpel_v16, 10, avx2)
PEL_PROTOTYPE (qpel_v24, 10, avx2)
PEL_PROTOTYPE (qpel_v32, 10, avx2)
PEL_PROTOTYPE (qpel_v48, 10, avx2)
PEL_PROTOTYPE (qpel_v64, 10, avx2)
PEL_PROTOTYPE (qpel_hv16, 8, avx2)
PEL_PROTOTYPE (qpel_hv24, 8, avx2)
PEL_PROTOTYPE (qpel_hv32, 8, avx2)
PEL_PROTOTYPE (qpel_hv48, 8, avx2)
PEL_PROTOTYPE (qpel_hv64, 8, avx2)
PEL_PROTOTYPE (qpel_hv16, 10, avx2)
PEL_PROTOTYPE (qpel_hv24, 10, avx2)
PEL_PROTOTYPE (qpel_hv32, 10, avx2)
PEL_PROTOTYPE (qpel_hv48, 10, avx2)
PEL_PROTOTYPE (qpel_hv64, 10, avx2)
WEIGHTING_PROTOTYPES (8, sse4)
WEIGHTING_PROTOTYPES (10, sse4)
WEIGHTING_PROTOTYPES (12, sse4)
void ff_hevc_transform_add4_8_mmxext (uint8_t *dst, int16_t *coeffs, ptrdiff_t stride)
void ff_hevc_transform_add8_8_sse2 (uint8_t *dst, int16_t *coeffs, ptrdiff_t stride)
void ff_hevc_transform_add16_8_sse2 (uint8_t *dst, int16_t *coeffs, ptrdiff_t stride)
void ff_hevc_transform_add32_8_sse2 (uint8_t *dst, int16_t *coeffs, ptrdiff_t stride)
void ff_hevc_transform_add8_8_avx (uint8_t *dst, int16_t *coeffs, ptrdiff_t stride)
void ff_hevc_transform_add16_8_avx (uint8_t *dst, int16_t *coeffs, ptrdiff_t stride)
void ff_hevc_transform_add32_8_avx (uint8_t *dst, int16_t *coeffs, ptrdiff_t stride)
void ff_hevc_transform_add32_8_avx2 (uint8_t *dst, int16_t *coeffs, ptrdiff_t stride)
void ff_hevc_transform_add4_10_mmxext (uint8_t *dst, int16_t *coeffs, ptrdiff_t stride)
void ff_hevc_transform_add8_10_sse2 (uint8_t *dst, int16_t *coeffs, ptrdiff_t stride)
void ff_hevc_transform_add16_10_sse2 (uint8_t *dst, int16_t *coeffs, ptrdiff_t stride)
void ff_hevc_transform_add32_10_sse2 (uint8_t *dst, int16_t *coeffs, ptrdiff_t stride)
void ff_hevc_transform_add16_10_avx2 (uint8_t *dst, int16_t *coeffs, ptrdiff_t stride)
void ff_hevc_transform_add32_10_avx2 (uint8_t *dst, int16_t *coeffs, ptrdiff_t stride)
Macro Definition Documentation
idct_dc_proto
#define idct_dc_proto (size, bitd, opt) void ff_hevc_idct##size##_dc_add_##bitd##_##opt(uint8_t *dst, int16_t *coeffs, ptrdiff_t stride)
Definition at line 32 of file hevcdsp.h.
PEL_LINK
#define PEL_LINK (dst, idx1, idx2, idx3, name, D, opt)
Value:
dst[idx1][idx2][idx3] = ff_hevc_put_hevc_ ## name ## _ ## D ## _##opt; \
dst ## _bi[idx1][idx2][idx3] = ff_hevc_put_hevc_bi_ ## name ## _ ## D ## _##opt; \
dst ## _uni[idx1][idx2][idx3] = ff_hevc_put_hevc_uni_ ## name ## _ ## D ## _##opt; \
dst ## _uni_w[idx1][idx2][idx3] = ff_hevc_put_hevc_uni_w_ ## name ## _ ## D ## _##opt; \
dst ## _bi_w[idx1][idx2][idx3] = ff_hevc_put_hevc_bi_w_ ## name ## _ ## D ## _##opt
Definition at line 35 of file hevcdsp.h.
PEL_PROTOTYPE
#define PEL_PROTOTYPE (name, D, opt)
Value:
void ff_hevc_put_hevc_ ## name ## _ ## D ## _##opt(int16_t *dst, uint8_t *_src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my,int width); \
void ff_hevc_put_hevc_bi_ ## name ## _ ## D ## _##opt(uint8_t *_dst, ptrdiff_t _dststride, uint8_t *_src, ptrdiff_t _srcstride, int16_t *src2, int height, intptr_t mx, intptr_t my, int width); \
void ff_hevc_put_hevc_uni_ ## name ## _ ## D ## _##opt(uint8_t *_dst, ptrdiff_t _dststride, uint8_t *_src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width); \
void ff_hevc_put_hevc_uni_w_ ## name ## _ ## D ## _##opt(uint8_t *_dst, ptrdiff_t _dststride, uint8_t *_src, ptrdiff_t _srcstride, int height, int denom, int wx, int ox, intptr_t mx, intptr_t my, int width); \
void ff_hevc_put_hevc_bi_w_ ## name ## _ ## D ## _##opt(uint8_t *_dst, ptrdiff_t _dststride, uint8_t *_src, ptrdiff_t _srcstride, int16_t *src2, int height, int denom, int wx0, int wx1, int ox0, int ox1, intptr_t mx, intptr_t my, int width)
Definition at line 43 of file hevcdsp.h.
EPEL_PROTOTYPES
#define EPEL_PROTOTYPES (fname, bitd, opt)
Value:
PEL_PROTOTYPE(fname##4,  bitd, opt); \
        PEL_PROTOTYPE(fname##6,  bitd, opt); \
        PEL_PROTOTYPE(fname##8,  bitd, opt); \
        PEL_PROTOTYPE(fname##12, bitd, opt); \
        PEL_PROTOTYPE(fname##16, bitd, opt); \
        PEL_PROTOTYPE(fname##24, bitd, opt); \
        PEL_PROTOTYPE(fname##32, bitd, opt); \
        PEL_PROTOTYPE(fname##48, bitd, opt); \
        PEL_PROTOTYPE(fname##64, bitd, opt)
Definition at line 55 of file hevcdsp.h.
QPEL_PROTOTYPES
#define QPEL_PROTOTYPES (fname, bitd, opt)
Value:
PEL_PROTOTYPE(fname##4,  bitd, opt); \
        PEL_PROTOTYPE(fname##8,  bitd, opt); \
        PEL_PROTOTYPE(fname##12, bitd, opt); \
        PEL_PROTOTYPE(fname##16, bitd, opt); \
        PEL_PROTOTYPE(fname##24, bitd, opt); \
        PEL_PROTOTYPE(fname##32, bitd, opt); \
        PEL_PROTOTYPE(fname##48, bitd, opt); \
        PEL_PROTOTYPE(fname##64, bitd, opt)
Definition at line 66 of file hevcdsp.h.
WEIGHTING_PROTOTYPE
#define WEIGHTING_PROTOTYPE (width, bitd, opt)
Value:
void ff_hevc_put_hevc_uni_w##width##_##bitd##_##opt(uint8_t *dst, ptrdiff_t dststride, int16_t *_src, int height, int denom,  int _wx, int _ox); \
void ff_hevc_put_hevc_bi_w##width##_##bitd##_##opt(uint8_t *dst, ptrdiff_t dststride, int16_t *_src, int16_t *_src2, int height, int denom,  int _wx0,  int _wx1, int _ox0, int _ox1)
Definition at line 76 of file hevcdsp.h.
WEIGHTING_PROTOTYPES
#define WEIGHTING_PROTOTYPES (bitd, opt)
Value:
WEIGHTING_PROTOTYPE(2, bitd, opt); \
        WEIGHTING_PROTOTYPE(4, bitd, opt); \
        WEIGHTING_PROTOTYPE(6, bitd, opt); \
        WEIGHTING_PROTOTYPE(8, bitd, opt); \
        WEIGHTING_PROTOTYPE(12, bitd, opt); \
        WEIGHTING_PROTOTYPE(16, bitd, opt); \
        WEIGHTING_PROTOTYPE(24, bitd, opt); \
        WEIGHTING_PROTOTYPE(32, bitd, opt); \
        WEIGHTING_PROTOTYPE(48, bitd, opt); \
        WEIGHTING_PROTOTYPE(64, bitd, opt)
Definition at line 80 of file hevcdsp.h.
Function Documentation
EPEL_PROTOTYPES() [1/12]
EPEL_PROTOTYPES (pel_pixels , 8 , sse4)
EPEL_PROTOTYPES() [2/12]
EPEL_PROTOTYPES (pel_pixels , 10 , sse4)
EPEL_PROTOTYPES() [3/12]
EPEL_PROTOTYPES (pel_pixels , 12 , sse4)
ff_hevc_put_hevc_pel_pixels16_8_avx2()
void ff_hevc_put_hevc_pel_pixels16_8_avx2 (int16_t * dst, uint8_t * _src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
ff_hevc_put_hevc_pel_pixels24_8_avx2()
void ff_hevc_put_hevc_pel_pixels24_8_avx2 (int16_t * dst, uint8_t * _src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
ff_hevc_put_hevc_pel_pixels32_8_avx2()
void ff_hevc_put_hevc_pel_pixels32_8_avx2 (int16_t * dst, uint8_t * _src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_put_hevc_pel_pixels48_8_avx2()
void ff_hevc_put_hevc_pel_pixels48_8_avx2 (int16_t * dst, uint8_t * _src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_put_hevc_pel_pixels64_8_avx2()
void ff_hevc_put_hevc_pel_pixels64_8_avx2 (int16_t * dst, uint8_t * _src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_put_hevc_pel_pixels16_10_avx2()
void ff_hevc_put_hevc_pel_pixels16_10_avx2 (int16_t * dst, uint8_t * _src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_put_hevc_pel_pixels24_10_avx2()
void ff_hevc_put_hevc_pel_pixels24_10_avx2 (int16_t * dst, uint8_t * _src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_put_hevc_pel_pixels32_10_avx2()
void ff_hevc_put_hevc_pel_pixels32_10_avx2 (int16_t * dst, uint8_t * _src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_put_hevc_pel_pixels48_10_avx2()
void ff_hevc_put_hevc_pel_pixels48_10_avx2 (int16_t * dst, uint8_t * _src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_put_hevc_pel_pixels64_10_avx2()
void ff_hevc_put_hevc_pel_pixels64_10_avx2 (int16_t * dst, uint8_t * _src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_put_hevc_uni_pel_pixels32_8_avx2()
void ff_hevc_put_hevc_uni_pel_pixels32_8_avx2 (uint8_t * dst, ptrdiff_t dststride, uint8_t * _src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_put_hevc_uni_pel_pixels48_8_avx2()
void ff_hevc_put_hevc_uni_pel_pixels48_8_avx2 (uint8_t * dst, ptrdiff_t dststride, uint8_t * _src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_put_hevc_uni_pel_pixels64_8_avx2()
void ff_hevc_put_hevc_uni_pel_pixels64_8_avx2 (uint8_t * dst, ptrdiff_t dststride, uint8_t * _src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_put_hevc_uni_pel_pixels96_8_avx2()
void ff_hevc_put_hevc_uni_pel_pixels96_8_avx2 (uint8_t * dst, ptrdiff_t dststride, uint8_t * _src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_put_hevc_uni_pel_pixels128_8_avx2()
void ff_hevc_put_hevc_uni_pel_pixels128_8_avx2 (uint8_t * dst, ptrdiff_t dststride, uint8_t * _src, ptrdiff_t _srcstride, int height, intptr_t mx, intptr_t my, int width)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_put_hevc_bi_pel_pixels16_8_avx2()
void ff_hevc_put_hevc_bi_pel_pixels16_8_avx2 (uint8_t * _dst, ptrdiff_t _dststride, uint8_t * _src, ptrdiff_t _srcstride, int16_t * src2, int height, intptr_t mx, intptr_t my, int width)
ff_hevc_put_hevc_bi_pel_pixels24_8_avx2()
void ff_hevc_put_hevc_bi_pel_pixels24_8_avx2 (uint8_t * _dst, ptrdiff_t _dststride, uint8_t * _src, ptrdiff_t _srcstride, int16_t * src2, int height, intptr_t mx, intptr_t my, int width)
ff_hevc_put_hevc_bi_pel_pixels32_8_avx2()
void ff_hevc_put_hevc_bi_pel_pixels32_8_avx2 (uint8_t * _dst, ptrdiff_t _dststride, uint8_t * _src, ptrdiff_t _srcstride, int16_t * src2, int height, intptr_t mx, intptr_t my, int width)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_put_hevc_bi_pel_pixels48_8_avx2()
void ff_hevc_put_hevc_bi_pel_pixels48_8_avx2 (uint8_t * _dst, ptrdiff_t _dststride, uint8_t * _src, ptrdiff_t _srcstride, int16_t * src2, int height, intptr_t mx, intptr_t my, int width)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_put_hevc_bi_pel_pixels64_8_avx2()
void ff_hevc_put_hevc_bi_pel_pixels64_8_avx2 (uint8_t * _dst, ptrdiff_t _dststride, uint8_t * _src, ptrdiff_t _srcstride, int16_t * src2, int height, intptr_t mx, intptr_t my, int width)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_put_hevc_bi_pel_pixels16_10_avx2()
void ff_hevc_put_hevc_bi_pel_pixels16_10_avx2 (uint8_t * _dst, ptrdiff_t _dststride, uint8_t * _src, ptrdiff_t _srcstride, int16_t * src2, int height, intptr_t mx, intptr_t my, int width)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_put_hevc_bi_pel_pixels24_10_avx2()
void ff_hevc_put_hevc_bi_pel_pixels24_10_avx2 (uint8_t * _dst, ptrdiff_t _dststride, uint8_t * _src, ptrdiff_t _srcstride, int16_t * src2, int height, intptr_t mx, intptr_t my, int width)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_put_hevc_bi_pel_pixels32_10_avx2()
void ff_hevc_put_hevc_bi_pel_pixels32_10_avx2 (uint8_t * _dst, ptrdiff_t _dststride, uint8_t * _src, ptrdiff_t _srcstride, int16_t * src2, int height, intptr_t mx, intptr_t my, int width)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_put_hevc_bi_pel_pixels48_10_avx2()
void ff_hevc_put_hevc_bi_pel_pixels48_10_avx2 (uint8_t * _dst, ptrdiff_t _dststride, uint8_t * _src, ptrdiff_t _srcstride, int16_t * src2, int height, intptr_t mx, intptr_t my, int width)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_put_hevc_bi_pel_pixels64_10_avx2()
void ff_hevc_put_hevc_bi_pel_pixels64_10_avx2 (uint8_t * _dst, ptrdiff_t _dststride, uint8_t * _src, ptrdiff_t _srcstride, int16_t * src2, int height, intptr_t mx, intptr_t my, int width)
Referenced by ff_hevc_dsp_init_x86().
EPEL_PROTOTYPES() [4/12]
EPEL_PROTOTYPES (epel_h , 8 , sse4)
EPEL_PROTOTYPES() [5/12]
EPEL_PROTOTYPES (epel_h , 10 , sse4)
EPEL_PROTOTYPES() [6/12]
EPEL_PROTOTYPES (epel_h , 12 , sse4)
EPEL_PROTOTYPES() [7/12]
EPEL_PROTOTYPES (epel_v , 8 , sse4)
EPEL_PROTOTYPES() [8/12]
EPEL_PROTOTYPES (epel_v , 10 , sse4)
EPEL_PROTOTYPES() [9/12]
EPEL_PROTOTYPES (epel_v , 12 , sse4)
EPEL_PROTOTYPES() [10/12]
EPEL_PROTOTYPES (epel_hv , 8 , sse4)
EPEL_PROTOTYPES() [11/12]
EPEL_PROTOTYPES (epel_hv , 10 , sse4)
EPEL_PROTOTYPES() [12/12]
EPEL_PROTOTYPES (epel_hv , 12 , sse4)
PEL_PROTOTYPE() [1/60]
PEL_PROTOTYPE (epel_h16 , 8 , avx2)
PEL_PROTOTYPE() [2/60]
PEL_PROTOTYPE (epel_h24 , 8 , avx2)
PEL_PROTOTYPE() [3/60]
PEL_PROTOTYPE (epel_h32 , 8 , avx2)
PEL_PROTOTYPE() [4/60]
PEL_PROTOTYPE (epel_h48 , 8 , avx2)
PEL_PROTOTYPE() [5/60]
PEL_PROTOTYPE (epel_h64 , 8 , avx2)
PEL_PROTOTYPE() [6/60]
PEL_PROTOTYPE (epel_h16 , 10 , avx2)
PEL_PROTOTYPE() [7/60]
PEL_PROTOTYPE (epel_h24 , 10 , avx2)
PEL_PROTOTYPE() [8/60]
PEL_PROTOTYPE (epel_h32 , 10 , avx2)
PEL_PROTOTYPE() [9/60]
PEL_PROTOTYPE (epel_h48 , 10 , avx2)
PEL_PROTOTYPE() [10/60]
PEL_PROTOTYPE (epel_h64 , 10 , avx2)
PEL_PROTOTYPE() [11/60]
PEL_PROTOTYPE (epel_v16 , 8 , avx2)
PEL_PROTOTYPE() [12/60]
PEL_PROTOTYPE (epel_v24 , 8 , avx2)
PEL_PROTOTYPE() [13/60]
PEL_PROTOTYPE (epel_v32 , 8 , avx2)
PEL_PROTOTYPE() [14/60]
PEL_PROTOTYPE (epel_v48 , 8 , avx2)
PEL_PROTOTYPE() [15/60]
PEL_PROTOTYPE (epel_v64 , 8 , avx2)
PEL_PROTOTYPE() [16/60]
PEL_PROTOTYPE (epel_v16 , 10 , avx2)
PEL_PROTOTYPE() [17/60]
PEL_PROTOTYPE (epel_v24 , 10 , avx2)
PEL_PROTOTYPE() [18/60]
PEL_PROTOTYPE (epel_v32 , 10 , avx2)
PEL_PROTOTYPE() [19/60]
PEL_PROTOTYPE (epel_v48 , 10 , avx2)
PEL_PROTOTYPE() [20/60]
PEL_PROTOTYPE (epel_v64 , 10 , avx2)
PEL_PROTOTYPE() [21/60]
PEL_PROTOTYPE (epel_hv16 , 8 , avx2)
PEL_PROTOTYPE() [22/60]
PEL_PROTOTYPE (epel_hv24 , 8 , avx2)
PEL_PROTOTYPE() [23/60]
PEL_PROTOTYPE (epel_hv32 , 8 , avx2)
PEL_PROTOTYPE() [24/60]
PEL_PROTOTYPE (epel_hv48 , 8 , avx2)
PEL_PROTOTYPE() [25/60]
PEL_PROTOTYPE (epel_hv64 , 8 , avx2)
PEL_PROTOTYPE() [26/60]
PEL_PROTOTYPE (epel_hv16 , 10 , avx2)
PEL_PROTOTYPE() [27/60]
PEL_PROTOTYPE (epel_hv24 , 10 , avx2)
PEL_PROTOTYPE() [28/60]
PEL_PROTOTYPE (epel_hv32 , 10 , avx2)
PEL_PROTOTYPE() [29/60]
PEL_PROTOTYPE (epel_hv48 , 10 , avx2)
PEL_PROTOTYPE() [30/60]
PEL_PROTOTYPE (epel_hv64 , 10 , avx2)
QPEL_PROTOTYPES() [1/9]
QPEL_PROTOTYPES (qpel_h , 8 , sse4)
QPEL_PROTOTYPES() [2/9]
QPEL_PROTOTYPES (qpel_h , 10 , sse4)
QPEL_PROTOTYPES() [3/9]
QPEL_PROTOTYPES (qpel_h , 12 , sse4)
QPEL_PROTOTYPES() [4/9]
QPEL_PROTOTYPES (qpel_v , 8 , sse4)
QPEL_PROTOTYPES() [5/9]
QPEL_PROTOTYPES (qpel_v , 10 , sse4)
QPEL_PROTOTYPES() [6/9]
QPEL_PROTOTYPES (qpel_v , 12 , sse4)
QPEL_PROTOTYPES() [7/9]
QPEL_PROTOTYPES (qpel_hv , 8 , sse4)
QPEL_PROTOTYPES() [8/9]
QPEL_PROTOTYPES (qpel_hv , 10 , sse4)
QPEL_PROTOTYPES() [9/9]
QPEL_PROTOTYPES (qpel_hv , 12 , sse4)
PEL_PROTOTYPE() [31/60]
PEL_PROTOTYPE (qpel_h16 , 8 , avx2)
PEL_PROTOTYPE() [32/60]
PEL_PROTOTYPE (qpel_h24 , 8 , avx2)
PEL_PROTOTYPE() [33/60]
PEL_PROTOTYPE (qpel_h32 , 8 , avx2)
PEL_PROTOTYPE() [34/60]
PEL_PROTOTYPE (qpel_h48 , 8 , avx2)
PEL_PROTOTYPE() [35/60]
PEL_PROTOTYPE (qpel_h64 , 8 , avx2)
PEL_PROTOTYPE() [36/60]
PEL_PROTOTYPE (qpel_h16 , 10 , avx2)
PEL_PROTOTYPE() [37/60]
PEL_PROTOTYPE (qpel_h24 , 10 , avx2)
PEL_PROTOTYPE() [38/60]
PEL_PROTOTYPE (qpel_h32 , 10 , avx2)
PEL_PROTOTYPE() [39/60]
PEL_PROTOTYPE (qpel_h48 , 10 , avx2)
PEL_PROTOTYPE() [40/60]
PEL_PROTOTYPE (qpel_h64 , 10 , avx2)
PEL_PROTOTYPE() [41/60]
PEL_PROTOTYPE (qpel_v16 , 8 , avx2)
PEL_PROTOTYPE() [42/60]
PEL_PROTOTYPE (qpel_v24 , 8 , avx2)
PEL_PROTOTYPE() [43/60]
PEL_PROTOTYPE (qpel_v32 , 8 , avx2)
PEL_PROTOTYPE() [44/60]
PEL_PROTOTYPE (qpel_v48 , 8 , avx2)
PEL_PROTOTYPE() [45/60]
PEL_PROTOTYPE (qpel_v64 , 8 , avx2)
PEL_PROTOTYPE() [46/60]
PEL_PROTOTYPE (qpel_v16 , 10 , avx2)
PEL_PROTOTYPE() [47/60]
PEL_PROTOTYPE (qpel_v24 , 10 , avx2)
PEL_PROTOTYPE() [48/60]
PEL_PROTOTYPE (qpel_v32 , 10 , avx2)
PEL_PROTOTYPE() [49/60]
PEL_PROTOTYPE (qpel_v48 , 10 , avx2)
PEL_PROTOTYPE() [50/60]
PEL_PROTOTYPE (qpel_v64 , 10 , avx2)
PEL_PROTOTYPE() [51/60]
PEL_PROTOTYPE (qpel_hv16 , 8 , avx2)
PEL_PROTOTYPE() [52/60]
PEL_PROTOTYPE (qpel_hv24 , 8 , avx2)
PEL_PROTOTYPE() [53/60]
PEL_PROTOTYPE (qpel_hv32 , 8 , avx2)
PEL_PROTOTYPE() [54/60]
PEL_PROTOTYPE (qpel_hv48 , 8 , avx2)
PEL_PROTOTYPE() [55/60]
PEL_PROTOTYPE (qpel_hv64 , 8 , avx2)
PEL_PROTOTYPE() [56/60]
PEL_PROTOTYPE (qpel_hv16 , 10 , avx2)
PEL_PROTOTYPE() [57/60]
PEL_PROTOTYPE (qpel_hv24 , 10 , avx2)
PEL_PROTOTYPE() [58/60]
PEL_PROTOTYPE (qpel_hv32 , 10 , avx2)
PEL_PROTOTYPE() [59/60]
PEL_PROTOTYPE (qpel_hv48 , 10 , avx2)
PEL_PROTOTYPE() [60/60]
PEL_PROTOTYPE (qpel_hv64 , 10 , avx2)
WEIGHTING_PROTOTYPES() [1/3]
WEIGHTING_PROTOTYPES (8 , sse4)
WEIGHTING_PROTOTYPES() [2/3]
WEIGHTING_PROTOTYPES (10 , sse4)
WEIGHTING_PROTOTYPES() [3/3]
WEIGHTING_PROTOTYPES (12 , sse4)
ff_hevc_transform_add4_8_mmxext()
void ff_hevc_transform_add4_8_mmxext (uint8_t * dst, int16_t * coeffs, ptrdiff_t stride)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_transform_add8_8_sse2()
void ff_hevc_transform_add8_8_sse2 (uint8_t * dst, int16_t * coeffs, ptrdiff_t stride)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_transform_add16_8_sse2()
void ff_hevc_transform_add16_8_sse2 (uint8_t * dst, int16_t * coeffs, ptrdiff_t stride)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_transform_add32_8_sse2()
void ff_hevc_transform_add32_8_sse2 (uint8_t * dst, int16_t * coeffs, ptrdiff_t stride)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_transform_add8_8_avx()
void ff_hevc_transform_add8_8_avx (uint8_t * dst, int16_t * coeffs, ptrdiff_t stride)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_transform_add16_8_avx()
void ff_hevc_transform_add16_8_avx (uint8_t * dst, int16_t * coeffs, ptrdiff_t stride)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_transform_add32_8_avx()
void ff_hevc_transform_add32_8_avx (uint8_t * dst, int16_t * coeffs, ptrdiff_t stride)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_transform_add32_8_avx2()
void ff_hevc_transform_add32_8_avx2 (uint8_t * dst, int16_t * coeffs, ptrdiff_t stride)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_transform_add4_10_mmxext()
void ff_hevc_transform_add4_10_mmxext (uint8_t * dst, int16_t * coeffs, ptrdiff_t stride)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_transform_add8_10_sse2()
void ff_hevc_transform_add8_10_sse2 (uint8_t * dst, int16_t * coeffs, ptrdiff_t stride)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_transform_add16_10_sse2()
void ff_hevc_transform_add16_10_sse2 (uint8_t * dst, int16_t * coeffs, ptrdiff_t stride)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_transform_add32_10_sse2()
void ff_hevc_transform_add32_10_sse2 (uint8_t * dst, int16_t * coeffs, ptrdiff_t stride)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_transform_add16_10_avx2()
void ff_hevc_transform_add16_10_avx2 (uint8_t * dst, int16_t * coeffs, ptrdiff_t stride)
Referenced by ff_hevc_dsp_init_x86().
ff_hevc_transform_add32_10_avx2()
void ff_hevc_transform_add32_10_avx2 (uint8_t * dst, int16_t * coeffs, ptrdiff_t stride)
Referenced by ff_hevc_dsp_init_x86().