FFmpeg: libavcodec/x86/h264chroma_init.c File Reference
h264chroma_init.c File Reference
#include <stdint.h>
#include "config.h"
#include "libavutil/attributes.h"
#include "libavutil/cpu.h"
#include "libavutil/x86/cpu.h"
#include "libavcodec/h264chroma.h"
Macros
#define CHROMA_MC(OP, NUM, DEPTH, OPT)
Functions
void ff_put_h264_chroma_mc8_rnd_mmx (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_avg_h264_chroma_mc8_rnd_mmxext (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_avg_h264_chroma_mc8_rnd_3dnow (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_put_h264_chroma_mc4_mmx (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_avg_h264_chroma_mc4_mmxext (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_avg_h264_chroma_mc4_3dnow (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_put_h264_chroma_mc2_mmxext (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_avg_h264_chroma_mc2_mmxext (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_put_h264_chroma_mc8_rnd_ssse3 (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_put_h264_chroma_mc4_ssse3 (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_avg_h264_chroma_mc8_rnd_ssse3 (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
void ff_avg_h264_chroma_mc4_ssse3 (uint8_t *dst, uint8_t *src, int stride, int h, int x, int y)
av_cold void ff_h264chroma_init_x86 (H264ChromaContext *c, int bit_depth)
Macro Definition Documentation
CHROMA_MC
#define CHROMA_MC (OP, NUM, DEPTH, OPT)
Value:
void ff_ ## OP ## _h264_chroma_mc ## NUM ## _ ## DEPTH ## _ ## OPT      \
                                      (uint8_t *dst, uint8_t *src,      \
                                       int stride, int h, int x, int y);
Definition at line 56 of file h264chroma_init.c.
Function Documentation
ff_put_h264_chroma_mc8_rnd_mmx()
void ff_put_h264_chroma_mc8_rnd_mmx (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_h264chroma_init_x86().
ff_avg_h264_chroma_mc8_rnd_mmxext()
void ff_avg_h264_chroma_mc8_rnd_mmxext (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_h264chroma_init_x86().
ff_avg_h264_chroma_mc8_rnd_3dnow()
void ff_avg_h264_chroma_mc8_rnd_3dnow (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_h264chroma_init_x86().
ff_put_h264_chroma_mc4_mmx()
void ff_put_h264_chroma_mc4_mmx (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_h264chroma_init_x86().
ff_avg_h264_chroma_mc4_mmxext()
void ff_avg_h264_chroma_mc4_mmxext (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_h264chroma_init_x86().
ff_avg_h264_chroma_mc4_3dnow()
void ff_avg_h264_chroma_mc4_3dnow (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_h264chroma_init_x86().
ff_put_h264_chroma_mc2_mmxext()
void ff_put_h264_chroma_mc2_mmxext (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_h264chroma_init_x86().
ff_avg_h264_chroma_mc2_mmxext()
void ff_avg_h264_chroma_mc2_mmxext (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_h264chroma_init_x86().
ff_put_h264_chroma_mc8_rnd_ssse3()
void ff_put_h264_chroma_mc8_rnd_ssse3 (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_h264chroma_init_x86().
ff_put_h264_chroma_mc4_ssse3()
void ff_put_h264_chroma_mc4_ssse3 (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_h264chroma_init_x86().
ff_avg_h264_chroma_mc8_rnd_ssse3()
void ff_avg_h264_chroma_mc8_rnd_ssse3 (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_h264chroma_init_x86().
ff_avg_h264_chroma_mc4_ssse3()
void ff_avg_h264_chroma_mc4_ssse3 (uint8_t * dst, uint8_t * src, int stride, int h, int x, int y)
Referenced by ff_h264chroma_init_x86().
ff_h264chroma_init_x86()
av_cold void ff_h264chroma_init_x86 (H264ChromaContext * c, int bit_depth)
Definition at line 70 of file h264chroma_init.c.
Referenced by ff_h264chroma_init().