FFmpeg: libavcodec/x86/hpeldsp.h File Reference
hpeldsp.h File Reference
#include <stddef.h>
#include <stdint.h>
Functions
void ff_avg_pixels8_x2_mmx (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_xy2_mmx (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_xy2_mmxext (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels8_xy2_ssse3 (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_xy2_mmx (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_xy2_sse2 (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_avg_pixels16_xy2_ssse3 (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_xy2_mmx (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels8_xy2_ssse3 (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_xy2_mmx (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_xy2_sse2 (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
void ff_put_pixels16_xy2_ssse3 (uint8_t *block, const uint8_t *pixels, ptrdiff_t line_size, int h)
Function Documentation
ff_avg_pixels8_x2_mmx()
void ff_avg_pixels8_x2_mmx (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_mmx().
ff_avg_pixels8_xy2_mmx()
void ff_avg_pixels8_xy2_mmx (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_mmx().
ff_avg_pixels8_xy2_mmxext()
void ff_avg_pixels8_xy2_mmxext (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_mmxext().
ff_avg_pixels8_xy2_ssse3()
void ff_avg_pixels8_xy2_ssse3 (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_ssse3().
ff_avg_pixels16_xy2_mmx()
void ff_avg_pixels16_xy2_mmx (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
ff_avg_pixels16_xy2_sse2()
void ff_avg_pixels16_xy2_sse2 (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_sse2().
ff_avg_pixels16_xy2_ssse3()
void ff_avg_pixels16_xy2_ssse3 (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_ssse3().
ff_put_pixels8_xy2_mmx()
void ff_put_pixels8_xy2_mmx (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
ff_put_pixels8_xy2_ssse3()
void ff_put_pixels8_xy2_ssse3 (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_ssse3().
ff_put_pixels16_xy2_mmx()
void ff_put_pixels16_xy2_mmx (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
ff_put_pixels16_xy2_sse2()
void ff_put_pixels16_xy2_sse2 (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_sse2().
ff_put_pixels16_xy2_ssse3()
void ff_put_pixels16_xy2_ssse3 (uint8_t * block, const uint8_t * pixels, ptrdiff_t line_size, int h)
Referenced by hpeldsp_init_ssse3().