FFmpeg: libavcodec/xbmdec.c File Reference
xbmdec.c File Reference
#include "libavutil/avstring.h"
#include "avcodec.h"
#include "internal.h"
#include "mathops.h"
Functions
static int convert (uint8_t x)
static int parse_str_int (const uint8_t *p, int len, const uint8_t *key)
static int xbm_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
Variables
AVCodec ff_xbm_decoder
Function Documentation
convert()
static int convert (uint8_t x) static
Definition at line 29 of file xbmdec.c.
Referenced by if(), query_formats(), and xbm_decode_frame().
parse_str_int()
static int parse_str_int (const uint8_t * p, int len, const uint8_t * key) static
Definition at line 40 of file xbmdec.c.
Referenced by xbm_decode_frame().
xbm_decode_frame()
static int xbm_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 61 of file xbmdec.c.
Variable Documentation
ff_xbm_decoder
AVCodec ff_xbm_decoder
Initial value:
= {
    .name         = "xbm",
    .long_name    = NULL_IF_CONFIG_SMALL("XBM (X BitMap) image"),
    .type         = AVMEDIA_TYPE_VIDEO,
    .id           = AV_CODEC_ID_XBM,
    .decode       = xbm_decode_frame,
    .capabilities = AV_CODEC_CAP_DR1,
}
Definition at line 130 of file xbmdec.c.