FFmpeg: libavdevice/xcbgrab.c File Reference
xcbgrab.c File Reference
#include "config.h"
#include <stdlib.h>
#include <xcb/xcb.h>
#include "libavutil/internal.h"
#include "libavutil/mathematics.h"
#include "libavutil/opt.h"
#include "libavutil/parseutils.h"
#include "libavutil/time.h"
#include "libavformat/avformat.h"
#include "libavformat/internal.h"
Data Structures
struct XCBGrabContext
Macros
#define FOLLOW_CENTER -1
#define OFFSET(x) offsetof(XCBGrabContext, x)
#define D AV_OPT_FLAG_DECODING_PARAM
Functions
static int xcbgrab_reposition (AVFormatContext *s, xcb_query_pointer_reply_t *p, xcb_get_geometry_reply_t *geo)
static int xcbgrab_frame (AVFormatContext *s, AVPacket *pkt)
static void wait_frame (AVFormatContext *s, AVPacket *pkt)
static void xcbgrab_update_region (AVFormatContext *s)
static int xcbgrab_read_packet (AVFormatContext *s, AVPacket *pkt)
static av_cold int xcbgrab_read_close (AVFormatContext *s)
static xcb_screen_t * get_screen (const xcb_setup_t *setup, int screen_num)
static int pixfmt_from_pixmap_format (AVFormatContext *s, int depth, int *pix_fmt)
static int create_stream (AVFormatContext *s)
static void draw_rectangle (AVFormatContext *s)
static void setup_window (AVFormatContext *s)
static av_cold int xcbgrab_read_header (AVFormatContext *s)
Variables
static const AVOption options []
static const AVClass xcbgrab_class
AVInputFormat ff_x11grab_xcb_demuxer
Macro Definition Documentation
FOLLOW_CENTER
#define FOLLOW_CENTER -1
Definition at line 80 of file xcbgrab.c.
Referenced by xcbgrab_reposition().
OFFSET
#define OFFSET (x) offsetof(XCBGrabContext, x)
Definition at line 82 of file xcbgrab.c.
D
#define D AV_OPT_FLAG_DECODING_PARAM
Definition at line 83 of file xcbgrab.c.
Function Documentation
xcbgrab_reposition()
static int xcbgrab_reposition (AVFormatContext * s, xcb_query_pointer_reply_t * p, xcb_get_geometry_reply_t * geo) static
Definition at line 108 of file xcbgrab.c.
Referenced by xcbgrab_read_packet().
xcbgrab_frame()
static int xcbgrab_frame (AVFormatContext * s, AVPacket * pkt) static
Definition at line 149 of file xcbgrab.c.
Referenced by xcbgrab_read_packet().
wait_frame()
static void wait_frame (AVFormatContext * s, AVPacket * pkt) static
Definition at line 190 of file xcbgrab.c.
Referenced by xcbgrab_read_packet().
xcbgrab_update_region()
static void xcbgrab_update_region (AVFormatContext * s) static
Definition at line 380 of file xcbgrab.c.
Referenced by xcbgrab_read_packet().
xcbgrab_read_packet()
static int xcbgrab_read_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 392 of file xcbgrab.c.
xcbgrab_read_close()
static av_cold int xcbgrab_read_close (AVFormatContext * s) static
Definition at line 434 of file xcbgrab.c.
Referenced by xcbgrab_read_header().
get_screen()
static xcb_screen_t* get_screen (const xcb_setup_t * setup, int screen_num) static
Definition at line 449 of file xcbgrab.c.
Referenced by xcbgrab_read_header().
pixfmt_from_pixmap_format()
static int pixfmt_from_pixmap_format (AVFormatContext * s, int depth, int * pix_fmt) static
Definition at line 466 of file xcbgrab.c.
Referenced by create_stream().
create_stream()
static int create_stream (AVFormatContext * s) static
Definition at line 517 of file xcbgrab.c.
Referenced by xcbgrab_read_header().
draw_rectangle()
static void draw_rectangle (AVFormatContext * s) static
Definition at line 568 of file xcbgrab.c.
Referenced by request_frame(), and setup_window().
setup_window()
static void setup_window (AVFormatContext * s) static
Definition at line 591 of file xcbgrab.c.
Referenced by xcbgrab_read_header().
xcbgrab_read_header()
static av_cold int xcbgrab_read_header (AVFormatContext * s) static
Definition at line 627 of file xcbgrab.c.
Variable Documentation
options
const AVOption options[] static
Initial value:
= {
    { "x", "Initial x coordinate.", OFFSET(x), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, INT_MAX, D },
    { "y", "Initial y coordinate.", OFFSET(y), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, INT_MAX, D },
    { "grab_x", "Initial x coordinate.", OFFSET(x), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, INT_MAX, D },
    { "grab_y", "Initial y coordinate.", OFFSET(y), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, INT_MAX, D },
    { "video_size", "A string describing frame size, such as 640x480 or hd720.", OFFSET(video_size), AV_OPT_TYPE_STRING, {.str = "vga" }, 0, 0, D },
    { "framerate", "", OFFSET(framerate), AV_OPT_TYPE_STRING, {.str = "ntsc" }, 0, 0, D },
    { "draw_mouse", "Draw the mouse pointer.", OFFSET(draw_mouse), AV_OPT_TYPE_INT, { .i64 = 1 }, 0, 1, D },
    { "follow_mouse", "Move the grabbing region when the mouse pointer reaches within specified amount of pixels to the edge of region.",
      OFFSET(follow_mouse), AV_OPT_TYPE_INT, { .i64 = 0 },  FOLLOW_CENTER, INT_MAX, D, "follow_mouse" },
    { "centered", "Keep the mouse pointer at the center of grabbing region when following.", 0, AV_OPT_TYPE_CONST, { .i64 = -1 }, INT_MIN, INT_MAX, D, "follow_mouse" },
    { "show_region", "Show the grabbing region.", OFFSET(show_region), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, 1, D },
    { "region_border", "Set the region border thickness.", OFFSET(region_border), AV_OPT_TYPE_INT, { .i64 = 3 }, 1, 128, D },
    { NULL },
}
Definition at line 84 of file xcbgrab.c.
xcbgrab_class
const AVClass xcbgrab_class static
Initial value:
= {
    .class_name = "xcbgrab indev",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
    .category   = AV_CLASS_CATEGORY_DEVICE_VIDEO_INPUT,
}
Definition at line 100 of file xcbgrab.c.
ff_x11grab_xcb_demuxer
AVInputFormat ff_x11grab_xcb_demuxer
Initial value:
= {
    .name           = "x11grab",
    .long_name      = NULL_IF_CONFIG_SMALL("X11 screen capture, using XCB"),
    .priv_data_size = sizeof(XCBGrabContext),
    .read_header    = xcbgrab_read_header,
    .read_packet    = xcbgrab_read_packet,
    .read_close     = xcbgrab_read_close,
    .flags          = AVFMT_NOFILE,
    .priv_class     = &xcbgrab_class,
}
Definition at line 693 of file xcbgrab.c.