FFmpeg: libavcodec/xfacedec.c File Reference
xfacedec.c File Reference
X-Face decoder, based on libcompface, by James Ashton.
#include "libavutil/pixdesc.h"
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
#include "xface.h"
Data Structures
struct XFaceContext
Functions
static int pop_integer (BigInt *b, const ProbRange *pranges)
static void pop_greys (BigInt *b, char *bitmap, int w, int h)
static void decode_block (BigInt *b, char *bitmap, int w, int h, int level)
static av_cold int xface_decode_init (AVCodecContext *avctx)
static int xface_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
Variables
AVCodec ff_xface_decoder
Detailed Description
X-Face decoder, based on libcompface, by James Ashton.
Definition in file xfacedec.c.
Function Documentation
pop_integer()
static int pop_integer (BigInt * b, const ProbRange * pranges) static
Definition at line 33 of file xfacedec.c.
Referenced by decode_block(), and pop_greys().
pop_greys()
static void pop_greys (BigInt * b, char * bitmap, int w, int h) static
Definition at line 51 of file xfacedec.c.
Referenced by decode_block().
decode_block()
static void decode_block (BigInt * b, char * bitmap, int w, int h, int level) static
Definition at line 69 of file xfacedec.c.
Referenced by xface_decode_frame().
xface_decode_init()
static av_cold int xface_decode_init (AVCodecContext * avctx) static
Definition at line 93 of file xfacedec.c.
xface_decode_frame()
static int xface_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 111 of file xfacedec.c.
Variable Documentation
ff_xface_decoder
AVCodec ff_xface_decoder
Initial value:
= {
    .name           = "xface",
    .long_name      = NULL_IF_CONFIG_SMALL("X-face image"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_XFACE,
    .priv_data_size = sizeof(XFaceContext),
    .init           = xface_decode_init,
    .decode         = xface_decode_frame,
    .pix_fmts       = (const enum AVPixelFormat[]) { AV_PIX_FMT_MONOWHITE, AV_PIX_FMT_NONE },
}
Definition at line 179 of file xfacedec.c.