FFmpeg: libavcodec/xiph.h File Reference
xiph.h File Reference
#include "libavutil/common.h"
Functions
int avpriv_split_xiph_headers (const uint8_t *extradata, int extradata_size, int first_header_size, const uint8_t *header_start[3], int header_len[3])
Split a single extradata buffer into the three headers that most Xiph codecs use.
Function Documentation
avpriv_split_xiph_headers()
int avpriv_split_xiph_headers (const uint8_t * extradata, int extradata_size, int first_header_size, const uint8_t * header_start[3], int header_len[3])
Split a single extradata buffer into the three headers that most Xiph codecs use.
(e.g. Theora and Vorbis) Works both with Matroska's packing and lavc's packing.
Parameters
[in] extradata The single chunk that combines all three headers
[in] extradata_size The size of the extradata buffer
[in] first_header_size The size of the first header, used to differentiate between the Matroska packing and lavc packing.
[out] header_start Pointers to the start of the three separate headers.
[out] header_len The sizes of each of the three headers.
Returns
On error a negative value is returned, on success zero.
Definition at line 24 of file xiph.c.
Referenced by ogg_write_header(), put_xiph_codecpriv(), read_huffman_tree(), vorbis_decode_init(), and vorbis_parse_init().