FFmpeg: libavcodec/xsubenc.c File Reference
xsubenc.c File Reference
#include "avcodec.h"
#include "bytestream.h"
#include "put_bits.h"
Macros
#define PADDING 0
Number of pixels to pad left and right.
#define PADDING_COLOR 0
Functions
static void put_xsub_rle (PutBitContext *pb, int len, int color)
Encode a single color run.
static int xsub_encode_rle (PutBitContext *pb, const uint8_t *bitmap, int linesize, int w, int h)
Encode a 4-color bitmap with XSUB rle.
static int make_tc (uint64_t ms, int *tc)
static int xsub_encode (AVCodecContext *avctx, unsigned char *buf, int bufsize, const AVSubtitle *h)
static av_cold int xsub_encoder_init (AVCodecContext *avctx)
Variables
AVCodec ff_xsub_encoder
Macro Definition Documentation
PADDING
#define PADDING 0
Number of pixels to pad left and right.
The official encoder pads the subtitles with two pixels on either side, but until we find out why, we won't do it (we will pad to have width divisible by 2 though).
Definition at line 34 of file xsubenc.c.
Referenced by xsub_encode(), and xsub_encode_rle().
PADDING_COLOR
#define PADDING_COLOR 0
Definition at line 35 of file xsubenc.c.
Referenced by xsub_encode(), and xsub_encode_rle().
Function Documentation
put_xsub_rle()
static void put_xsub_rle (PutBitContext * pb, int len, int color) static
Encode a single color run.
At most 16 bits will be used.
Parameters
len length of the run, values > 255 mean "until end of line", may not be < 0.
color color to encode, only the lowest two bits are used and all others must be 0.
Definition at line 42 of file xsubenc.c.
Referenced by xsub_encode(), and xsub_encode_rle().
xsub_encode_rle()
static int xsub_encode_rle (PutBitContext * pb, const uint8_t * bitmap, int linesize, int w, int h) static
Encode a 4-color bitmap with XSUB rle.
The encoded bitmap may be wider than the source bitmap due to padding.
Definition at line 56 of file xsubenc.c.
Referenced by xsub_encode().
make_tc()
static int make_tc (uint64_t ms, int * tc) static
Definition at line 101 of file xsubenc.c.
Referenced by xsub_encode().
xsub_encode()
static int xsub_encode (AVCodecContext * avctx, unsigned char * buf, int bufsize, const AVSubtitle * h) static
Definition at line 113 of file xsubenc.c.
xsub_encoder_init()
static av_cold int xsub_encoder_init (AVCodecContext * avctx) static
Definition at line 217 of file xsubenc.c.
Variable Documentation
ff_xsub_encoder
AVCodec ff_xsub_encoder
Initial value:
= {
    .name       = "xsub",
    .long_name  = NULL_IF_CONFIG_SMALL("DivX subtitles (XSUB)"),
    .type       = AVMEDIA_TYPE_SUBTITLE,
    .id         = AV_CODEC_ID_XSUB,
    .init       = xsub_encoder_init,
    .encode_sub = xsub_encode,
}
Definition at line 227 of file xsubenc.c.