FFmpeg: libavdevice/xv.c File Reference
xv.c File Reference
XVideo output device.
#include <X11/Xlib.h>
#include <X11/extensions/Xv.h>
#include <X11/extensions/XShm.h>
#include <X11/extensions/Xvlib.h>
#include <sys/shm.h>
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"
#include "libavutil/imgutils.h"
#include "libavformat/internal.h"
#include "avdevice.h"
Data Structures
struct XVContext
struct XVTagFormatMap
Macros
#define OFFSET(x) offsetof(XVContext, x)
Functions
static int xv_get_tag_from_format (enum AVPixelFormat format)
static int xv_write_trailer (AVFormatContext *s)
static int xv_write_header (AVFormatContext *s)
static void compute_display_area (AVFormatContext *s)
static int xv_repaint (AVFormatContext *s)
static int write_picture (AVFormatContext *s, uint8_t *input_data[4], int linesize[4])
static int xv_write_packet (AVFormatContext *s, AVPacket *pkt)
static int xv_write_frame (AVFormatContext *s, int stream_index, AVFrame **frame, unsigned flags)
static int xv_control_message (AVFormatContext *s, int type, void *data, size_t data_size)
Variables
static const XVTagFormatMap tag_codec_map []
static const AVOption options []
static const AVClass xv_class
AVOutputFormat ff_xv_muxer
Detailed Description
XVideo output device.
TODO:
add support to more formats
Definition in file xv.c.
Macro Definition Documentation
OFFSET
#define OFFSET (x) offsetof(XVContext, x)
Definition at line 353 of file xv.c.
Function Documentation
xv_get_tag_from_format()
static int xv_get_tag_from_format (enum AVPixelFormat format) static
Definition at line 77 of file xv.c.
Referenced by xv_write_header().
xv_write_trailer()
static int xv_write_trailer (AVFormatContext * s) static
Definition at line 88 of file xv.c.
Referenced by xv_write_header().
xv_write_header()
static int xv_write_header (AVFormatContext * s) static
Definition at line 103 of file xv.c.
compute_display_area()
static void compute_display_area (AVFormatContext * s) static
Definition at line 226 of file xv.c.
Referenced by xv_repaint().
xv_repaint()
static int xv_repaint (AVFormatContext * s) static
Definition at line 256 of file xv.c.
Referenced by write_picture(), and xv_control_message().
write_picture()
static int write_picture (AVFormatContext * s, uint8_t * input_data[4], int linesize[4]) static
Definition at line 294 of file xv.c.
Referenced by xv_write_frame(), and xv_write_packet().
xv_write_packet()
static int xv_write_packet (AVFormatContext * s, AVPacket * pkt) static
Definition at line 322 of file xv.c.
xv_write_frame()
static int xv_write_frame (AVFormatContext * s, int stream_index, AVFrame ** frame, unsigned flags) static
Definition at line 333 of file xv.c.
xv_control_message()
static int xv_control_message (AVFormatContext * s, int type, void * data, size_t data_size) static
Definition at line 342 of file xv.c.
Variable Documentation
tag_codec_map
const XVTagFormatMap tag_codec_map[] static
Initial value:
= {
    { MKTAG('I','4','2','0'), AV_PIX_FMT_YUV420P },
    { MKTAG('U','Y','V','Y'), AV_PIX_FMT_UYVY422 },
    { MKTAG('Y','U','Y','2'), AV_PIX_FMT_YUYV422 },
    { 0,                      AV_PIX_FMT_NONE }
}
Definition at line 70 of file xv.c.
Referenced by xv_get_tag_from_format().
options
const AVOption options[] static
Initial value:
= {
    { "display_name", "set display name",       OFFSET(display_name), AV_OPT_TYPE_STRING, {.str = NULL }, 0, 0, AV_OPT_FLAG_ENCODING_PARAM },
    { "window_id",    "set existing window id", OFFSET(window_id),    AV_OPT_TYPE_INT64,  {.i64 = 0 }, 0, INT64_MAX, AV_OPT_FLAG_ENCODING_PARAM },
    { "window_size",  "set window forced size", OFFSET(window_width), AV_OPT_TYPE_IMAGE_SIZE, {.str = NULL}, 0, 0, AV_OPT_FLAG_ENCODING_PARAM },
    { "window_title", "set window title",       OFFSET(window_title), AV_OPT_TYPE_STRING, {.str = NULL }, 0, 0, AV_OPT_FLAG_ENCODING_PARAM },
    { "window_x",     "set window x offset",    OFFSET(window_x),     AV_OPT_TYPE_INT,    {.i64 = 0 }, -INT_MAX, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM },
    { "window_y",     "set window y offset",    OFFSET(window_y),     AV_OPT_TYPE_INT,    {.i64 = 0 }, -INT_MAX, INT_MAX, AV_OPT_FLAG_ENCODING_PARAM },
    { NULL }
}
Definition at line 354 of file xv.c.
xv_class
const AVClass xv_class static
Initial value:
= {
    .class_name = "xvideo outdev",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
    .category   = AV_CLASS_CATEGORY_DEVICE_VIDEO_OUTPUT,
}
Definition at line 365 of file xv.c.
ff_xv_muxer
AVOutputFormat ff_xv_muxer
Initial value:
= {
    .name           = "xv",
    .long_name      = NULL_IF_CONFIG_SMALL("XV (XVideo) output device"),
    .priv_data_size = sizeof(XVContext),
    .audio_codec    = AV_CODEC_ID_NONE,
    .video_codec    = AV_CODEC_ID_RAWVIDEO,
    .write_header   = xv_write_header,
    .write_packet   = xv_write_packet,
    .write_uncoded_frame = xv_write_frame,
    .write_trailer  = xv_write_trailer,
    .control_message = xv_control_message,
    .flags          = AVFMT_NOFILE | AVFMT_VARIABLE_FPS | AVFMT_NOTIMESTAMPS,
    .priv_class     = &xv_class,
}
Definition at line 373 of file xv.c.