FFmpeg: libavcodec/xvididct.h File Reference
xvididct.h File Reference
#include <stdint.h>
#include "avcodec.h"
#include "idctdsp.h"
Functions
void ff_xvid_idct (int16_t *const in)
void ff_xvid_idct_init (IDCTDSPContext *c, AVCodecContext *avctx)
void ff_xvid_idct_init_x86 (IDCTDSPContext *c, AVCodecContext *avctx, unsigned high_bit_depth)
void ff_xvid_idct_init_mips (IDCTDSPContext *c, AVCodecContext *avctx, unsigned high_bit_depth)
Function Documentation
ff_xvid_idct()
void ff_xvid_idct (int16_t *const in)
Definition at line 291 of file xvididct.c.
Referenced by ff_xvid_idct_init(), xvid_idct_add(), and xvid_idct_put().
ff_xvid_idct_init()
void ff_xvid_idct_init (IDCTDSPContext * c, AVCodecContext * avctx)
Definition at line 333 of file xvididct.c.
Referenced by ff_idctdsp_init(), and ff_mpeg4_frame_end().
ff_xvid_idct_init_x86()
void ff_xvid_idct_init_x86 (IDCTDSPContext * c, AVCodecContext * avctx, unsigned high_bit_depth)
Definition at line 55 of file xvididct_init.c.
Referenced by ff_xvid_idct_init().
ff_xvid_idct_init_mips()
void ff_xvid_idct_init_mips (IDCTDSPContext * c, AVCodecContext * avctx, unsigned high_bit_depth)
Definition at line 39 of file xvididct_init_mips.c.
Referenced by ff_xvid_idct_init().