FFmpeg: libavcodec/xxan.c File Reference
xxan.c File Reference
#include "libavutil/intreadwrite.h"
#include "libavutil/mem.h"
#include "avcodec.h"
#include "bytestream.h"
#include "internal.h"
Data Structures
struct XanContext
Functions
static av_cold int xan_decode_end (AVCodecContext *avctx)
static av_cold int xan_decode_init (AVCodecContext *avctx)
static int xan_unpack_luma (XanContext *s, uint8_t *dst, const int dst_size)
static int xan_unpack (XanContext *s, uint8_t *dest, const int dest_len)
static int xan_decode_chroma (AVCodecContext *avctx, unsigned chroma_off)
static int xan_decode_frame_type0 (AVCodecContext *avctx)
static int xan_decode_frame_type1 (AVCodecContext *avctx)
static int xan_decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
Variables
AVCodec ff_xan_wc4_decoder
Function Documentation
xan_decode_end()
static av_cold int xan_decode_end (AVCodecContext * avctx) static
Definition at line 40 of file xxan.c.
Referenced by xan_decode_init().
xan_decode_init()
static av_cold int xan_decode_init (AVCodecContext * avctx) static
Definition at line 52 of file xxan.c.
xan_unpack_luma()
static int xan_unpack_luma (XanContext * s, uint8_t * dst, const int dst_size) static
Definition at line 88 of file xxan.c.
Referenced by xan_decode_frame_type0(), and xan_decode_frame_type1().
xan_unpack()
static int xan_unpack (XanContext * s, uint8_t * dest, const int dest_len) static
Definition at line 130 of file xxan.c.
Referenced by xan_decode_chroma(), and xan_decode_frame_type0().
xan_decode_chroma()
static int xan_decode_chroma (AVCodecContext * avctx, unsigned chroma_off) static
Definition at line 183 of file xxan.c.
Referenced by xan_decode_frame_type0(), and xan_decode_frame_type1().
xan_decode_frame_type0()
static int xan_decode_frame_type0 (AVCodecContext * avctx) static
Definition at line 281 of file xxan.c.
Referenced by xan_decode_frame().
xan_decode_frame_type1()
static int xan_decode_frame_type1 (AVCodecContext * avctx) static
Definition at line 360 of file xxan.c.
Referenced by xan_decode_frame().
xan_decode_frame()
static int xan_decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 405 of file xxan.c.
Variable Documentation
ff_xan_wc4_decoder
AVCodec ff_xan_wc4_decoder
Initial value:
= {
    .name           = "xan_wc4",
    .long_name      = NULL_IF_CONFIG_SMALL("Wing Commander IV / Xxan"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_XAN_WC4,
    .priv_data_size = sizeof(XanContext),
    .init           = xan_decode_init,
    .close          = xan_decode_end,
    .decode         = xan_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 440 of file xxan.c.