FFmpeg: libavcodec/zmbv.c File Reference
zmbv.c File Reference
Zip Motion Blocks Video decoder.
#include <stdio.h>
#include <stdlib.h>
#include "libavutil/common.h"
#include "libavutil/imgutils.h"
#include "libavutil/intreadwrite.h"
#include "avcodec.h"
#include "internal.h"
#include <zlib.h>
Data Structures
struct ZmbvContext
Macros
#define ZMBV_KEYFRAME 1
#define ZMBV_DELTAPAL 2
Enumerations
enum ZmbvFormat {
ZMBV_FMT_NONE = 0, ZMBV_FMT_1BPP = 1, ZMBV_FMT_2BPP = 2, ZMBV_FMT_4BPP = 3,
ZMBV_FMT_8BPP = 4, ZMBV_FMT_15BPP = 5, ZMBV_FMT_16BPP = 6, ZMBV_FMT_24BPP = 7,
ZMBV_FMT_32BPP = 8
}
Functions
static int zmbv_decode_xor_8 (ZmbvContext *c)
Decode XOR'ed frame - 8bpp version.
static int zmbv_decode_xor_16 (ZmbvContext *c)
Decode XOR'ed frame - 15bpp and 16bpp version.
static int zmbv_decode_xor_32 (ZmbvContext *c)
Decode XOR'ed frame - 32bpp version.
static int zmbv_decode_intra (ZmbvContext *c)
Decode intraframe.
static int decode_frame (AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
static av_cold int decode_init (AVCodecContext *avctx)
static av_cold int decode_end (AVCodecContext *avctx)
Variables
AVCodec ff_zmbv_decoder
Detailed Description
Zip Motion Blocks Video decoder.
Definition in file zmbv.c.
Macro Definition Documentation
ZMBV_KEYFRAME
#define ZMBV_KEYFRAME 1
Definition at line 38 of file zmbv.c.
Referenced by decode_frame().
ZMBV_DELTAPAL
#define ZMBV_DELTAPAL 2
Definition at line 39 of file zmbv.c.
Referenced by zmbv_decode_xor_8().
Enumeration Type Documentation
ZmbvFormat
enum ZmbvFormat
Enumerator
ZMBV_FMT_NONE
ZMBV_FMT_1BPP
ZMBV_FMT_2BPP
ZMBV_FMT_4BPP
ZMBV_FMT_8BPP
ZMBV_FMT_15BPP
ZMBV_FMT_16BPP
ZMBV_FMT_24BPP
ZMBV_FMT_32BPP
Definition at line 41 of file zmbv.c.
Function Documentation
zmbv_decode_xor_8()
static int zmbv_decode_xor_8 (ZmbvContext * c) static
Decode XOR'ed frame - 8bpp version.
Definition at line 80 of file zmbv.c.
Referenced by decode_frame().
zmbv_decode_xor_16()
static int zmbv_decode_xor_16 (ZmbvContext * c) static
Decode XOR'ed frame - 15bpp and 16bpp version.
Definition at line 157 of file zmbv.c.
Referenced by decode_frame().
zmbv_decode_xor_32()
static int zmbv_decode_xor_32 (ZmbvContext * c) static
Decode XOR'ed frame - 32bpp version.
Definition at line 315 of file zmbv.c.
Referenced by decode_frame().
zmbv_decode_intra()
static int zmbv_decode_intra (ZmbvContext * c) static
Decode intraframe.
Definition at line 388 of file zmbv.c.
Referenced by decode_frame().
decode_frame()
static int decode_frame (AVCodecContext * avctx, void * data, int * got_frame, AVPacket * avpkt) static
Definition at line 402 of file zmbv.c.
decode_init()
static av_cold int decode_init (AVCodecContext * avctx) static
Definition at line 577 of file zmbv.c.
decode_end()
static av_cold int decode_end (AVCodecContext * avctx) static
Definition at line 615 of file zmbv.c.
Variable Documentation
ff_zmbv_decoder
AVCodec ff_zmbv_decoder
Initial value:
= {
    .name           = "zmbv",
    .long_name      = NULL_IF_CONFIG_SMALL("Zip Motion Blocks Video"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_ZMBV,
    .priv_data_size = sizeof(ZmbvContext),
    .init           = decode_init,
    .close          = decode_end,
    .decode         = decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1,
}
Definition at line 628 of file zmbv.c.